### ISSUE TITLE
Game closes unexpectedly with no error message within 1-3 minutes

### ISSUE THREAD

**Issue by plemmonator** [OpenRCT2/OpenRCT2#10007]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.2.3]
**Commit/Build:** [e.g. 426e106]

So I started off on a custom scenario. Many of the ride selections I had made were not appearing in the build menu. I'm not sure what version of the game it was. I downloaded the latest version (0.2.3) in hopes that it would fix itself. Now the game crashes within 3 minutes no matter what I'm doing at the time, even if I stay on the title screen. I have tried uninstalling OpenRCT2 and redownloading it, uninstalling RCT2 and redownloading it, and uninstalling both and deleting any related files I could find then redownloading both. RCT2 runs fine with no issues. I don't know how to create a dump file, and it's not a specific save so I have nothing to upload(I'm not even sure if a dump file would help, I'm new to this).

- [no ] Reproducible in RCT2 (vanilla)?
- [no ] Specific to multiplayer?

**Steps to reproduce:**
1. launch game
2.

**Comment by AaronVanGeffen** [comment]
I'm sorry you're experiencing this issue. To help you solve this, it is really important we know exactly what build you're trying to get to work, though — you did not fully fill out the issue template. Which build are you trying? You can give us a download link or a commit hash (e.g. 426e106, but that one's over three years old).

**Comment by plemmonator** [comment]
I feel stupid. I realized last night that I had not excluded some of the files from my antivirus search. It was closing the game without any notification. I got it to work last night after tinkering with the antivirus settings. Thanks for reaching out!
