### ISSUE TITLE
Play Button not highlighted in Launcher startup window

### ISSUE THREAD

**Issue by YycJT** [OpenRCT2/OpenRCT2#10008]
Windows 10
Version: 1803
Commit/Build: 17134.950

When I open OponRCT2 Launcher using the desktop icon nothing happens. Previously (last week and the previous month since first installing) everything worked fine, the launcher would load and after approximately 20-30 seconds the "play" button would highlight allowing me to run as expected. Upon opening nothing occurs, the button no longer highlights. i uninstalled OpenRCT2 Launcher and reinstalled via the OpenRCT2 website, but the problem is still occurring. Any suggestions for fixes?

Thanks in advance!

**Comment by Krutonium** [comment]
The Launcher has it's own repo - https://github.com/LRFLEW/OpenRCT2Launcher

**Comment by Gymnasiast** [comment]
Closing this because of the reason stated by Krutonium.
