### ISSUE TITLE
Saved park-brakes all set to 0mph

### ISSUE THREAD

**Issue by Bactrim** [OpenRCT2/OpenRCT2#10028]
**Windows 10**
**0.2.3**
**b82d1bb:**

 I upgraded from 6b21aac on the x64 version and my park's coasters' brakes are all set to 0mph, causing one coaster to rollback.

Reproducible in RCT2 (vanilla)?
- No, brakes aren't set to 0mph when I load it in vanilla, but the game crashes after less than a minute in vanilla when I load the scenario.] 

Specific to multiplayer? No

**Steps to reproduce:**
1. Load the scenario attached 
2. See the hyper coaster stall after hitting a trim brake.

**Save game:**

[Six Flags BYO 1 - Copy.txt](https://github.com/OpenRCT2/OpenRCT2/files/3644651/Six.Flags.BYO.1.-.Copy.txt)

**Comment by SpaceManiac** [comment]
git bisect points to b94b8880aa207658cc1378664b6731da74f96ef0 as the bad commit

**Comment by Bactrim** [comment]
Also, when I fix the brakes and save the game, close out then load the game again, the brakes are set to 0mph again.

**Comment by duncanspumpkin** [comment]
B94b888 is meant to fix this issue not cause it.

**Comment by Job26** [comment]
This also happens to boosters. They all get set to 0

**Comment by duncanspumpkin** [comment]
Well yes they are the same thing.

**Comment by erikhuizinga** [comment]
Just for reference, the bug also applies to multiplayer (probably when loading the saved game for the MP game, as well as to the intro screen sequence of maps, which probably also loads various saved games.

I kind of hoped this would actually crash one intro sequence ride, but it does not... 🤡

**Comment by 17acres** [comment]
FYI: Fix for this problem is pending in PR #10037

**Comment by RCTMASTA** [comment]
This bug also seems to put any block-sectioned ride with multiple stations into a deadlock.

**Comment by 17acres** [comment]
> This bug also seems to put any block-sectioned ride with multiple stations into a deadlock.

I'm pretty sure that problem existed prior to b94b888. I thought that would have been fixed with b94b888 since it seems to fix the problem where guests will magically walk through the sky to the wrong train at the wrong station after they pass through a ride entrance.

**Comment by RCTMASTA** [comment]
I didn't have any issues with the ride in question prior to b94b888, though...
