### ISSUE TITLE
Graphical glitches when zooming on large resolutions

### ISSUE THREAD

**Issue by PurpleMadness** [OpenRCT2/OpenRCT2#1002]
After you resize the window to make it very wide, when you zoom out and back in, graphical glitches will occur as seen in the image.

It's not a large issue as it only occurs on very wide resolutions, also it disappears when you move it offscreen and back onscreen. It seemed to occur at about a width of around 2830px and up. Resizing the window again also fixes the graphical glitches.

![Graphical Glitches image](https://cloud.githubusercontent.com/assets/488574/7035735/2df1c8ea-dd8c-11e4-9fe8-7ea3238cf450.png)

**Comment by pizza2004** [comment]
I have this exact same issue on the title screen and in game all the time, although my width is only ever 2560px.  I have no idea what's causing it, but it's very annoying.

**Comment by Gymnasiast** [comment]
One of my (custom) flat rides has animation glitches, which might be related. (If it isn't, I'll open a separate issue.)

**Comment by PurpleMadness** [comment]
After some more testing it seems to have nothing to do with the width, rather the absolute amount of pixels on screen. It doesn't glitch with 3828x749, but it does glitch with 3828x755.

**Comment by PurpleMadness** [comment]
@pizza2004, yes it also glitches on 2560x1440 (a common resolution). I've determined that 3000x896 doesn't glitch, while 3000x897 does glitch, which is a combined value of 2688000 and 2691000. I have no idea if the combined values are relevant though.

**Comment by IntelOrca** [comment]
This bug has been present since the very beginning. Its most likely a bug related to resolutions that weren't originally possible. It was not introduced with any reversed drawing code etc.

@Gymnasiast Unrelated, this bug is to do with zooming on large resolutions.
