### ISSUE TITLE
Hover object name

### ISSUE THREAD

**Issue by Richard-L** [OpenRCT2/OpenRCT2#10031]
Quick enhancement suggestion for managing custom scenery.

How about a special mode where hovering over an object will show its filename? Perhaps when in object selection mode, to ease the process a bit.

**Comment by Gymnasiast** [comment]
It already shows this information in the bottom right corner:

![afbeelding](https://user-images.githubusercontent.com/1478678/91768013-4966e000-ebdd-11ea-9731-72a2b4a75913.png)
