### ISSUE TITLE
Cablelift is not applied in ride/attraction simulation

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#10044]
**OS:** Windows 10
**Version:** 0.2.3
**Commit/Build:** 0b95dcd

Originally issued at [here](https://gall.dcinside.com/mgallery/board/view/?id=rct&no=20400).
Cablelift is not applied in ride/attraction simulation.

**Steps to reproduce:**
1. Make any gigacoaster, it doesn't matter it is completed or not.
2. Simulate the coaster

**Screenshots / Video:**
![1570204610](https://user-images.githubusercontent.com/10726524/66222800-ee96e100-e70c-11e9-885a-741ee02f3336.gif)

**Comment by duncanspumpkin** [comment]
Cable lifts have a huge section of special code I'm not at all surprised that it doesn't handle simulation mode nicely.

**Comment by Generalcamo** [comment]
This is a duplicate of #9541

**Comment by Meekimoto** [comment]
Mine does this too

**Comment by Gymnasiast** [comment]
Closing this as a duplicate.
