### ISSUE TITLE
Refactor `window_scenery_tab_entries`

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#10055]
`window_scenery_tab_entries` located in `libopenrct2ui/windows/Scenery.cpp` is an array of all of the scenery items on a tab in the scenery window. The type is `uint16_t` but this is actually a *lie*. The type is actually a struct of scenery type and scenery tab index stuffed into a `uint16_t`! This issue is for fixing this.

Create a new struct for the tab entry that has two fields `type` and `index`. Modify all of the code in this file to use the new struct for the type of `window_scenery_tab_entries`. Try to make the changes in stages. Its easy to convert between the old version and the new version as its just a case of stuffing it back into a `uint16_t`.

**Comment by seefly200** [comment]
hello! i'd like to work on this. i'm fairly new to cpp and this seems basic enough that i can do this. thank you in advance!

**Comment by duncanspumpkin** [comment]
Sure give it a shot. The other 4 issues i put up yesterday are perhaps easier.

**Comment by duncanspumpkin** [comment]
@seefly200 how are you getting on?

**Comment by tupaschoal** [comment]
I'm willing to work on this, if the task is still available

**Comment by seefly200** [comment]
hey, sorry, was scheduled at work for the past few days, I'm gonna grind on it tonight

**Comment by babywashbear** [comment]
Since nothing was happening the last two weeks, I took the liberty of looking at this issue. Upon closer inspection, I do not see the issue exactly. The return type is `uint16_t` and nothing in this file suggests that the underlying `type` or `index` is addressed directly. No shifting etc.

Could you elaborate on what exactly it is you want to be done? By changing the `uint16_t` to a struct with `uint8_t type` and `uint8_t index` (btw, is this index the same tab identifier - as in the first array index? If so, I would just change the return type to `uint8_t` instead of `uint16_t`) it just creates a lot of work to rewrite everything and I cannot see any obvious benefits.

**Comment by cskrisz** [comment]
You can get some clues from the `window_scenery_init`, `window_scenery_update`, `window_scenery_scrollpaint`, `SceneryGroupObject::UpdateEntryIndexes` functions and the constants in `Scenery.h`.

**Comment by ZehMatt** [comment]
I'm also not seeing anything that can be refactored, @duncanspumpkin could you perhaps point to a line where the 16 bits are split into index/type, I'm only seeing the value being used as sceneryId and nothing else.

**Comment by cskrisz** [comment]
Right now it's like this:
```
  0x0-0x100: small scenery
0x100-0x200: path scenery
0x200-0x300: walls
etc.
```
Note that `0x100` is `0b1'0000'0000‬`. It would be much simpler to divide the `uint16_t`  so the hight byte is the `type` and the low byte is the `index`.

**Comment by duncanspumpkin** [comment]
Yah what cskrisz wrote is exactly what i was meaning.

**Comment by babywashbear** [comment]
OK. 

So you mean `small scenery` would be type `0`, `path scenery` would be type `1`, `walls` would be type `2` etc.

In other words, a `uint16_t` entry `0xabcd` would mean entry of type `ab` and it is the `cd`th element of that type, right?

**Comment by duncanspumpkin** [comment]
Yes

**Comment by romsenkabomsen** [comment]
Hey, are you still working on this? Can I help some how?

**Comment by duncanspumpkin** [comment]
I've a feeling this might have already been done. I vaguely remember @Gymnasiast doing something about this.

**Comment by Gymnasiast** [comment]
That's correct, it was addressed by https://github.com/OpenRCT2/OpenRCT2/pull/10922.

@romsenkabomsen Thanks for bringing it to our attention.
