### ISSUE TITLE
Refactor `get_map_coordinates_from_pos`

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#10065]
`get_map_coordinates_from_pos` and `get_map_coordinates_from_pos_window` are used to convert a screen coordinate position that a mouse is over into a map position that the game uses and tell you what item you are hovering over. It is quite complex how it works everything out but this refactor is about modifying its calling parameters. To make things easier to understand in the project we are trying to identify the different coordinate systems. This function uses both the map coordinates `CoordsXY` and the screen coordinates `ScreenCoords`. 

Create an overload of `get_map_coordinates_from_pos_window` that takes the current 9 parameters. Make that function call the original. This will be our shim to the old version.

Modify `get_map_coordinates_from_pos_window` to take a `ScreenCoordsXY` instead of `screenX` and `screenY`. Modify it further to take a `&CoordsXY` instead of `*x` and `*y`. Make sure the shim that was created in the first step still works correctly converting between the two.

Repeat the above for `get_map_coordinates_from_pos` and make it so that it calls our new `get_map_coordinates_from_pos_window`.

Later on refactors will look at calling the new version for all functions that call these functions. If you come across some simple ones feel free to do them whilst doing this refactor. Try not to do anything too crazy as it will take longer to review.

**Comment by ahmedkrmn** [comment]
Can I work on this one?

**Comment by duncanspumpkin** [comment]
Sure go ahead.

**Comment by ahmedkrmn** [comment]
What do you think about using [std::pair](https://en.cppreference.com/w/cpp/utility/pair) to represent both  `ScreenCoordsXY`  and `CoordsXY`?

**Comment by duncanspumpkin** [comment]
I don't think it would be useful for this. What did you have in mind.

**Comment by ahmedkrmn** [comment]
@duncanspumpkin I think we can use either a pair, array, vector or a struct.

**Comment by ahmedkrmn** [comment]
@duncanspumpkin If a [std::pair](https://en.cppreference.com/w/cpp/utility/pair) is used, `get_map_coordinates_from_pos_window()` can be overloaded to be as follows:
```
void get_map_coordinates_from_pos_window(
    rct_window* window, std::pair<int32_t, int32_t> ScreenCoordsXY, int32_t flags, std::pair<int16_t*, int16_t*>& CoordsXY,
    int32_t* interactionType, TileElement** tileElement, rct_viewport** viewport);
```

**Comment by duncanspumpkin** [comment]
Ah no the structs already exist.

**Comment by ahmedkrmn** [comment]
@duncanspumpkin so what do you think ?

**Comment by duncanspumpkin** [comment]
So just use the existing structs

**Comment by bentglasstube** [comment]
I didn't see anything in flight here other than the comments, so I went ahead with a PR.  I also didn't see much information about testing changes so I only ensured that this builds, but it should be pretty straightforward changes.

**Comment by Gymnasiast** [comment]
@h4ppybr4z1ll1an It has been done, but we forgot to close this. Thanks for notifying us!
