### ISSUE TITLE
Saved Track Designs do not have lift hills, brakes are set to 0 mph, boosters set to 0 mph

### ISSUE THREAD

**Issue by thewesker** [OpenRCT2/OpenRCT2#10069]
**OS:** Windows 10
**Version:** 0.2.3-411
**Commit/Build:** b793d7e

When placing a saved track design in any park, the designs no longer have lift hills, brakes are set to 0 mph, and boosters are also set to 0 mph. 

- [ ] Reproducible in RCT2 (vanilla)? No

**Steps to reproduce:**
1. Start new scenario or load saved park
2. Build a roller coaster using a saved track design
3. Test or open the ride

**Screenshots / Video:**
![Crazy Castle 2019-10-09 17-13-50](https://user-images.githubusercontent.com/8624039/66521073-6b80dc80-eab8-11e9-8a54-c9b70145577e.png)

**Comment by AaronVanGeffen** [comment]
This ought to be fixed as of a63395eb1c12678a94cfcb0923f3f49c67a6247f. Can you still reproduce this on the latest builds?

**Comment by thewesker** [comment]
I am using build b793d7e which is newer than a63395e.

This issue is affecting scenarios as well as save files.

**Comment by duncanspumpkin** [comment]
Woops. Will have this fixed shortly. Its just the importing that is broken will have broken anything that is currently placed but will be fixed when you place it again.
