### ISSUE TITLE
Refactor TrackDesignEntranceElement

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#10074]
Continueing on from #10064 and #10052 there are further refactoring opportunities for `TrackDesignEntranceElement`. This issue is for fixing the `z` coordinate. In the original game the z component was used as both the z coordinate and also an indicator of the last item in an array. It did this by setting the value `0xFF` if it was the last item in the list. This of course clashes with the value `-1` for the z coordinate so `-1` is represented by `0x80` i.e. -128. We want to move this conversion into the importers and exporters.

- Modify T6Exporter::SaveTrack to put back in the -1 to 0x80 conversion. On the z value 0xFF it should throw an error.
- Modify TD6Importer::Import to undo the conversion.
- Modify TrackDesign::CreateTrackDesignTrack still check for bad z values but now no need to convert the z value.
- Modify track_design_place_ride to simplify the z code.

**Comment by tupaschoal** [comment]
Can this be closed due to 4e111c6 or is something left?
