### ISSUE TITLE
Update Twitch Logo

### ISSUE THREAD

**Issue by tupaschoal** [OpenRCT2/OpenRCT2#10071]
As of September 26, Twitch has refreshed it's visual identity and changed the logo [(source)](https://blog.twitch.tv/en/2019/09/26/nice-to-meet-you-again-for-the-first-time/).

The twitch icon on the settings should be updated to the new one:
![twitch](https://user-images.githubusercontent.com/6443427/66531841-a51b0d00-eae3-11e9-878a-46d698f0ec2d.png)

**Comment by tupaschoal** [comment]
To be clear, I'm trying to do this, but have been struggling to test ;X

**Comment by janisozaur** [comment]
There's twitch icon here: https://github.com/OpenRCT2/OpenRCT2/blob/develop/resources/g2/icons/twitch.png that you have replace, then build `g2` target and replace your old copy with newly created `g2.dat`.

**Comment by Gymnasiast** [comment]
See https://github.com/OpenRCT2/OpenRCT2/pull/10072 for the reason why this hasn't been implemented.
