### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by dustintechno** [OpenRCT2/OpenRCT2#10098]
**OS:** [Windows 10]
**Version:** [0.2.3]
**Commit/Build:** [e.g. 426e106] ( i dont know what this means :/ )

I just want to play with my friends, but the terminal says "command not found" (screenshot below).
I dont know what to do next after researching for 5hrs (srsly).

https://pastebin.com/TCaaFpUp

- [x] Specific to multiplayer? Yes

**Screenshots / Video:**
http://prntscr.com/pjotol

Regards :)

**Comment by Broxzier** [comment]
You've downloaded a Windows build, but it looks like you're on a Linux system.

You're also passing a path to a directory instead of a saved game. The path given to the `host` command needs to be a file that OpenRCT2 can open as a park.

**Comment by dustintechno** [comment]
> You've downloaded a Windows build, but it looks like you're on a Linux system.
> You're also passing a path to a directory instead of a saved game. The path given to the host command needs to be a file that OpenRCT2 can open as a park.

you are my legend today, works :)
