### ISSUE TITLE
Get Admin

### ISSUE THREAD

**Issue by dustintechno** [OpenRCT2/OpenRCT2#10099]
**OS:** [e.g. Windows 10]
**Version:** [0.2.3]

I join the server, and i am a spectetor, how can i get admin / any right to build smth., i did not found it in the permissions thread.

- [x] Specific to multiplayer?

**Steps to reproduce:**
1. Setup a server
2. Join
3. Try to build

Regards, again :(

**Comment by dustintechno** [comment]
(Or how do i acces to the users.json and groups.json (if it is there possible to give someone admin)
(Or how can i change the defaultgroup)

**Comment by Gymnasiast** [comment]
Can you ask these questions on the forums at openrct2.org? This is a bug tracker, it is not meant for general help.
