### ISSUE TITLE
Shortcut key window is too narrow in German

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#10143]
**OS:** GNU/Linux
**Version:** 0.2.3-462
**Commit/Build:** e9bcad193

- [ ] Reproducible in RCT2 (vanilla)? I don't know.
- [ ] Specific to multiplayer? No

**Steps to reproduce:**
1. Set language to German
2. Open key binding window
3. Scroll

Some key binding descriptions are too short and don't fit into the window. Tweaking the translation is not an option, so I think the window must be made a bit wider.

**Comment by AaronVanGeffen** [comment]
![Screenshot_20191026_155933](https://user-images.githubusercontent.com/604665/67620669-9f266b00-f809-11e9-9226-dca0fe1a8f7f.png)

**Comment by Wuzzy2** [comment]
OK, the highlighted string is indeed excessively long. I suggest “Originale/dekompilierte Streckenansicht wechseln”.

But the other strings probably can't be shortened by much.

**Comment by AaronVanGeffen** [comment]
For the other strings, it's probably best to just offset the second column a little more to the right. Should be easy to resolve.

**Comment by Wuzzy2** [comment]
Will post a PR as soon https://github.com/OpenRCT2/Localisation/pull/1762 is merged.

**Comment by AaronVanGeffen** [comment]
@Gymnasiast This doesn't just require changing the strings; there is still string overlap (cf. the bottom of the screenshot).

**Comment by Gymnasiast** [comment]
@AaronVanGeffen The PR autoclosed it. (I'm not very happy it does that, btw.)

**Comment by Wuzzy2** [comment]
The closing was justified. I knew exactly what I was doing. The bug is indeed fixed. I tested it.

If you read the PR again, you will see I also touched `STR_2781`, which specifies the width.

**Comment by AaronVanGeffen** [comment]
Assuming you mean https://github.com/OpenRCT2/Localisation/pull/1762, then no, it does not touch `STR_2781`…?

**Comment by Wuzzy2** [comment]
https://github.com/OpenRCT2/Localisation/pull/1765
