### ISSUE TITLE
openrct2.org changelog is very outdated

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#10142]
Go to <https://openrct2.org/changelog>.

Read it.

The changelogs on this webpage are *very* outdated, they go back to 2016! The latest stable version is 0.2.3, but in the changelog it's only version 0.0.5.

**Comment by AaronVanGeffen** [comment]
Unfortunately, OpenRCT2.org is not [our website](http://openrct2.io/). Please contact the admin there, @JarnoVgr. :)
