### ISSUE TITLE
[Inprovement] Add buttons keyboard to close windows in-game

### ISSUE THREAD

**Issue by md500** [OpenRCT2/OpenRCT2#10151]
OS: Windows 10 LTSC 1809 - Build 17763.832
Version: 0.2.3
Commit/Build: ac7a1eb

Buttons from keyboard to close windows in one shot doesn't exist. ESC button (and alt+ESC to close all) may be very useful, to things to this, like hire many employees, clickling many visitors,viewing many tracks, shops and stalls to then close it with an button from keyboard that clicking to "x" button which is a pain and tedious.

PD: Sorry for my english.

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open employee option
2. Hire several employees of any kind.

(same things occurs: click many visitors, tracks, shop or stalls)

**Screenshots / Video:**
![Global Button to close all windows in-game](https://user-images.githubusercontent.com/3111925/67639314-acecf680-f8c4-11e9-9cb6-ccd0f89812b5.png)

**Save game:**

[Diamond Heights5-win.zip](https://github.com/OpenRCT2/OpenRCT2/files/3776241/Diamond.Heights5-win.zip)

**Comment by Gymnasiast** [comment]
This feature has been implemented since the very first RollerCoaster Tycoon 1, in 1999.
Backspace closes the most recent window, Shift + Backspace closes all of them.

Keyboard shortcuts can be viewed and changed via the Options window.
