### ISSUE TITLE
LINK : fatal error LNK1104: cannot open file 'openrct2.lib' using "Rebuild Solution" from within Visual Studio

### ISSUE THREAD

**Issue by tjwrona1992** [OpenRCT2/OpenRCT2#10162]
**OS:**
Windows 10

**Commit/Build:**
Latest develop: f5c9131f23693aa23ce510f673d09b30bbc0a985

On a clean build that is triggered from within Visual studio 2017 (and also Visual studio 2019) I always get the error:
LINK : fatal error LNK1104: cannot open file 'openrct2.lib'

After the failure building again succeeds.

**Steps to reproduce:**
1. Checkout the latest develop (commit f5c913) and perform the steps to build the application as listed in the README.
2. Open visual studio and perform a clean build.

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/44857895/67822573-2f2d1480-fa97-11e9-8cbb-eb543c0bdcb4.png)

**Comment by janisozaur** [comment]
Please inspect your environment, all our CI build pass: https://ci.appveyor.com/project/OpenRCT2/openrct2/builds/28443551 and they do virtually the same.

Additionally, the commit I'd you provided seems invalid, otherwise GitHub would auto-link it to said commit

**Comment by tjwrona1992** [comment]
Hi @janisozaur I figured out that it happens whenever I use the "Rebuild Solution" option in Visual studio. It happens consistently every time. I can do a clean, then a build and it works fine, only "Rebuild" is broken.

![image](https://user-images.githubusercontent.com/44857895/67903921-3e699c00-fb43-11e9-85c1-70d71dab2c5e.png)

Also I may not have put enough letters in the hash, here is the full commit hash: f5c9131f23693aa23ce510f673d09b30bbc0a985

**Comment by tjwrona1992** [comment]
I found out that a "Rebuild" acts slightly different than a "clean" then a "build" in Visual Studio. This may help in tracking down the exact source of the issue: https://stackoverflow.com/a/17781143/3964397

**Comment by tjwrona1992** [comment]
Here is a build log showing the failure.

[Output-Build.txt](https://github.com/OpenRCT2/OpenRCT2/files/3801771/Output-Build.txt)
