### ISSUE TITLE
Minor render mistake in land tool

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#10176]
**OS:** GNU/Linux
**Version:** 0.2.3
**Commit/Build:** stable

- [ ] Reproducible in RCT2 (vanilla)? No.
- [ ] Specific to multiplayer? No.

**Steps to reproduce:**
1. Open the land tool
2. Activate the slope mode
3. Set the size to 6

The drawn lines in the land size widget look a bit weird now. It appears there's some kind of bad overlap happening with the background grid and the overlay grid.

**Comment by AaronVanGeffen** [comment]
I wonder if this has ever worked properly. Unlike in OpenRCT2, you cannot change the surface area of the mountain tool in vanilla. Nonetheless, the issue is very apparent. Perhaps a new sprite is required to ensure alignment, though.

**Comment by AaronVanGeffen** [comment]
Further investigation revealed it is indeed due to the sprites for the even-numbered selection grids not aligning with that of the mountain tool. We will need to add another sprite to accommodate these.
