### ISSUE TITLE
Placing multiple saved rides ignores the design name.

### ISSUE THREAD

**Issue by Syphilisto** [OpenRCT2/OpenRCT2#10186]
**OS:** [Windows 10 x64]
**Version:** [ 0.2.4]
**Commit/Build:** [d645338]

Placing more than one saved ride ignores the saved design name and treats the name like a generic new design.  This didn't occur in 0.2.3.

EX: If I place multiple saved mazes named "micromaze", it will just name the second maze "Maze 1" and the third "Maze 2" instead of just keeping the "micromaze" name. In the previous release (v0.2.3), it would just place all mazes as "micromaze." I cannot recreate in RCT2 to know which naming convention is desired, and I cannot remember how releases prior to 0.2.3 behaved.

If you change the name of the first placed coaster before placing a new one, the new one will remember the design name, so the game only ignores the design name if a ride is already placed with that name.  Renaming another ride to the same name flags a "name already exists" message, so perhaps an undocumented change was made to protect from having multiple rides with same name.   Perhaps it would be preferable to increment the design name, like "micromaze 2", "micromaze 3" instead of bypassing it entirely.  If the saved name is too long, truncating/replacing the final few characters is always an option.

- [ ] Reproducible in RCT2 (vanilla)?
Unknown, I cannot save rides in RCT2 due to a device I/O error leading into a crash-to-desktop.
- [ ] Specific to multiplayer?
no

**Steps to reproduce:**
1.  Place a saved ride and do not change name
2.  Place an identically-named ride
3.  View name of newly placed ride.

**screenshot**
![image](https://user-images.githubusercontent.com/57280922/68079225-d5349380-fda3-11e9-9137-d8017d04017e.png)

I placed two of the "6x9 Classic Mini" designs and 4 of the "5x5 Spinning Box" rides.  This is how they were named after placement.  In v0.2.3 all the Spinning Wild Mouse coasters would've shared the "5x5 Spinning Box" name without any errors and both of the Classic Mini Coasters would've been named "6x9 Classic Mini".

**Save game:  I made simple numbers with pathing to show first ride placed vs second**
[naming example.txt](https://github.com/OpenRCT2/OpenRCT2/files/3801136/naming.example.txt

**Comment by tupaschoal** [comment]
Still happens on v0.3.1 and I just noticed it is an original bug
