### ISSUE TITLE
FPS drop with opened ride windows

### ISSUE THREAD

**Issue by Richard-L** [OpenRCT2/OpenRCT2#10188]
In the new v0.2.4 (... I am using v0.2.4-42) there is a new drop in framerate when opening several ride windows on the screen that I've not witnessed before.

The game always runs at 60fps on my computer, but each opened ride window will now reduce the framerate step by step, where at around 3 ride windows, it's halved.

![image](https://user-images.githubusercontent.com/4934209/68084395-2476d480-fe35-11e9-9dc8-6a1f403620fb.png)

This is when using "software (hardware display)". The problem does not occur when using the OpenGL renderer.

Thank you for looking into it.

**Comment by IntelOrca** [comment]
This problem has always existed as far as I know. The reason you do not get it in OpenGL is because that draws the entire screen every frame where as software has to repaint all the changed blocks in the screen, the more viewports you have showing, the more expensive that is.

**Comment by Richard-L** [comment]
Hmm, I've not noticed this problem before, but frankly I don't recall the last time I opened many ride windows. The pixel zoom is indeed applied.

**Comment by ZehMatt** [comment]
Its been always like this and not a lot we can do about it right now.

**Comment by Richard-L** [comment]
I shall remove the "new" from the title then I'm afraid.
