### ISSUE TITLE
Decide on a notation for unsigned and long numbers

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#10193]
Currently, we tend to write `1u` and `1ULL`, which is inconsistent. We should decide on one notation and apply that throughout.

I don't have a strong opinion about it, but I find the lower case variant slightly easier to read.

**Comment by Broxzier** [comment]
I prefer uppercase for all integral suffixes, simply because `1l` may look like 11, while `1L` doesn't.

**Comment by AaronVanGeffen** [comment]
Perhaps something to take into account when we inevitably switch to a new version of `clang-format`.

@Broxzier sums up my thoughts on the suffix itself. I do prefer `0x` for hexadecimal and `f` for floats, though, even though uppercase is allowed there. Ambiguity isn't an issue there, fortunately.

**Comment by tupaschoal** [comment]
Why not `std::numeric_limits<unsigned long long>`? I mean, it's a lot longer, but it also seems more correct.

**Comment by ZehMatt** [comment]
Personally I would go for the uppercase one for integers.

**Comment by AaronVanGeffen** [comment]
> Why not `std::numeric_limits<unsigned long long>`? I mean, it's a lot longer, but it also seems more correct.

That's not the kind of number that brought this issue about. The code is littered with e.g. `(1ULL << widgetIndex)`, and the question of whether or not to use capitals for those literals came up in another issue.
