### ISSUE TITLE
Placing door over track yields "land not owned by park"

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#10196]
**OS:** Ubuntu 19.10
**Version:** 0.2.4+
**Commit/Build:** d8d762dcb97fec40781c245ba6e8162e415a90ba

If I try to build a door across the track in the square with brown outline, it will show an error saying "land not owned by park", which is not the case.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Screenshots / Video:**
![Rock 'n' Roll Revival 2019-11-04 22-10-28](https://user-images.githubusercontent.com/1478678/68159379-f5a25080-ff51-11e9-95c5-6c8d1174e149.png)

**Save game:**

[Rock 'n' Roll Revival ZC-dooracrosstrackbug.zip](https://github.com/OpenRCT2/OpenRCT2/files/3806147/Rock.n.Roll.Revival.ZC-dooracrosstrackbug.zip)

**Comment by duncanspumpkin** [comment]
I can't reproduce the error message but I did find a mistake from #6033 which was preventing the door from being placed.
