### ISSUE TITLE
Condor Ride description inaccuracy

### ISSUE THREAD

**Issue by honzi** [OpenRCT2/OpenRCT2#1021]
According to this screenshot http://i.imgur.com/TCJT3ul.png the `Condor Ride` has an inaccurate description. Could this description and other inaccurate descriptions be improved? I don't currently have access to the game to confirm this, just passing on the information I found in [this Reddit post](http://www.reddit.com/r/rct/comments/32qgpu/am_i_missing_something_or_is_the_description_of/).

**Comment by Gymnasiast** [comment]
Not yet. These descriptions are stored in the .DAT files that come with RCT2. Modifying them changes their checksum and will cause all existing games to fail loading the file.

OpenRCT2 will eventually switch to its own format and have an extractor, which will contain metadata - such as better descriptions. (Some languages, such as Dutch, are very badly translated, so it's on the agenda.)

**Comment by RollingStar** [comment]
I'd like to see someone who speaks a non-English language give some examples of a poor translation that the official releases have.

**Comment by Gymnasiast** [comment]
@RollingStar : I speak a non-English language (Dutch). I have mentioned the awful translation quite a few times, which you could easily have found if you searched for it. 

I'm not sure whether the examples are really understandable to a non-Dutch speaker, but the file looks like it has been translated by a computer and never corrected. It has incorrect capitalisation, grammar that can't really pass for it, strange word order, poor choice when a word can be translated in more than one way, even in simple strings that someone who has played RCT2 for an hour will translate better, and probably many other abominations I forgot about.

Not that Dutch is the only badly translated language. According to #704, German has a bad one as well.

**Comment by JarnoVgr** [comment]
@RollingStar The Dutch translation was/is horrible. One thing that bothered me was that the chips stall was translated to the Dutch 'chips', which are crisps. (drama)

**Comment by RollingStar** [comment]
The reason I want a specific example is it looks better on a Wiki page to say "Dutch speakers can compare these two translations". If the Wiki page just said "Gymnasiast says the translation is bad, you can look at the original strings for cable lift hill and the Open RCT2 strings and compare them yourself", it looks unprofessional. We have to prove the translation is bad, not rely on the end-user to do the work for us.

After reading your latest post I searched for "Dutch" and had trouble finding a comparison between original RCT2 and Open 2. There was one post comparing RCT1 and Open RCT2.

One can say that "we don't have to prove anything, nobody cares". They might be correct. I think it is good to have another example of Open RCT2's superiority to RCT2. Much like how Open 2 renders in higher resolutions and lets the user raise land in a >5x5 square.

At a minimum, people should be able to compare the strings in their original language. Only 2 or 3 examples are needed. So for US English I might have:

Original RollerCoaster Tycoon 1:
Scrambled Eggs

Open RCT2:
Twist

And native speakers could decide for themselves if they think the new translation is better.

**Comment by AaronVanGeffen** [comment]
@RollingStar For what it's worth, I agree it's better to provide some actual examples on the wiki, instead of relying solely on anecdote, or indeed plain say-so. A list of ten of the most notorious strings should do, I think?

One of the string that put me off at the time was how "dirt road" was translated into "vies voetpad" -- literally "dirty pavement". That's how bad it was.

**Comment by PFCKrutonium** [comment]
TBH, I have seen some dirt roads that were so tightly packed they might as well have been dirty pavement...
