### ISSUE TITLE
Can't import RCT1 Deluxe from Steam

### ISSUE THREAD

**Issue by nate2014jatc** [OpenRCT2/OpenRCT2#10228]
**OS:** [Linux Mint 19]
**Version:** [0.2.4]
**Commit/Build:** [d64535875]

I am having issues importing from the Steam version of RCT1: Deluxe.
I don't see a css17.dat or mp.dat, did something in the Steam version change?
Seems related to #7022 and #5359

- [?] Reproducible in RCT2 (vanilla)?
- [?] Specific to multiplayer?

**Steps to reproduce:**
1. Attempt to import RCT1 files through GUI on Main Menu Screen.
2. Navigate file browser to `/media/nate/BulkStorage/SteamLibrary/steamapps/common/RollerCoaster Tycoon Deluxe/`, `/media/nate/BulkStorage/SteamLibrary/steamapps/common/RollerCoaster Tycoon Deluxe/RCTdeluxe_install`, and I tried `/media/nate/BulkStorage/SteamLibrary/steamapps/common/RollerCoaster Tycoon Deluxe/RCTdeluxe_install/Data` just for giggles.
3. Receive error "Please select a valid RCT1 directory"

**Dump file**

Not Present
**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/11836893/68748729-2e799f80-05ba-11ea-96f5-eeef03b1aeb7.png)

**Save game:**

N/A

**Comment by Krutonium** [comment]
I confirmed this on my end, and glancing at the code it looks like it should work (Correct file capitalization and everything), but it refuses as shown above. That being said, if you edit `~/.config/OpenRCT2/config.ini` to have the path to your RCT1 install, it works perfectly fine.

**Comment by nate2014jatc** [comment]
Fascinating. 
Which directory did you use, the Steam one or the Installer one?

**Comment by Krutonium** [comment]
Steam

**Comment by Gymnasiast** [comment]
It is still a bug if the GUI does not allow you to select that folder. I'll reopen this to track the GUI bug.

**Comment by catb0t** [comment]
The error in the console is `WARNING[../src/openrct2/util/Util.cpp:417 (safe_strcpy)]: Truncating string "/home/c" to 8 bytes.`. The path does not exist because safe_strcpy truncated the string, probably because the string length it was given was 8 or defaulted to 8 because of a buggy error condition.
