### ISSUE TITLE
Autodetect RCT2 installs instead of asking where it is

### ISSUE THREAD

**Issue by henke37** [OpenRCT2/OpenRCT2#10240]
Look in obvious places before asking where the datafiles are.

In particular, try looking in the windows registry for information of where the game is installed. Also look for an install via steam, parsing the steam config files. I've done [the latter](https://github.com/henke37/HenkesUtilities/blob/master/SteamUtils/SteamHelper.cs) myself.

**Comment by IntelOrca** [comment]
> Look in obvious places before asking where the datafiles are.

We already do this, it includes the default paths of all known releases of RCT2.

**Comment by henke37** [comment]
"Default"? As in [a hard coded list](https://github.com/OpenRCT2/OpenRCT2/blob/83b1d1f72ea1260e45468d5d80225d93068bc8f8/src/openrct2/config/Config.cpp#L661)? That's garbage! At the very least it needs to look up the actual name of "Program Files". Because it's localizable.

Anyway, I experienced a different bug. #10241

**Comment by Gymnasiast** [comment]
Do you honestly think you can speak to us like that? Cut the attitude.
