### ISSUE TITLE
Resizable Tree Scatter Tool

### ISSUE THREAD

**Issue by dr-dirt** [OpenRCT2/OpenRCT2#10246]
Request for making the treeing / tree scatter tool resizable; currently is only a single size.  Suggestion made to Gymnasiast.

**Comment by scrapes** [comment]
Hey i tried making something out of fun:
https://github.com/scrapes/OpenRCT2/tree/scenery-scatter

Added an extra Window with Scatter options if you activate the Scenery-Scatter(Cluster) option. 
Some feedback would be nice :)

**Comment by AaronVanGeffen** [comment]
@scrapes Feel free to open a PR for your branch. Makes it easier for us to give feedback on particular bits of code. :)

**Comment by scrapes** [comment]
Alright, will do it as soon as I can!

**Comment by Umdlye** [comment]
Implemented by #10357
