### ISSUE TITLE
Track Element Preview Incorrect

### ISSUE THREAD

**Issue by 17acres** [OpenRCT2/OpenRCT2#10275]
**OS:** Windows 10
**Version:** 0.2.4-116 
**Commit/Build:** dfe8335

Since recent builds, the track element preview in both the ride construction window and the "ghost" highlighted tiles in the main window are very broken. The interference detection works properly and the actual element is placed correctly, unlike the preview.

This issue appears to happen for any track element larger than a single tile.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1.  Start building a ride
2.  Select a curved track element

**Screenshots / Video:**
<img width="322" alt="2019-11-21 15_48_57-OpenRCT2" src="https://user-images.githubusercontent.com/29017351/69375508-7f525d80-0c76-11ea-844f-75a2e028f9d5.png">

**Comment by Gymnasiast** [comment]
Most likely caused by one of the coordinate refactors.

Tagging @duncanspumpkin or @tupaschoal .

**Comment by tupaschoal** [comment]
Culprit is https://github.com/tupaschoal/OpenRCT2/commit/2acdc577f7c8c50a226d9b0a1091bfdae1e6b97f
