### ISSUE TITLE
OpenRCT2 misses dependency on Ubuntu 18.04

### ISSUE THREAD

**Issue by NESC1US** [OpenRCT2/OpenRCT2#10286]
**OS:** Ubuntu 18.04
**Version:** 0.2.4
**Commit/Build:** https://github.com/OpenRCT2/OpenRCT2/releases/download/v0.2.4/OpenRCT2-0.2.4-linux-x86_64.tar.gz

starting of this game on ubuntu 18.04 is too complicated - dependencies missing: libzip.so.4 libcurl.so.4

./openrct2
./openrct2: error while loading shared libraries: libzip.so.4: cannot open shared object file: No such file or directory
./openrct2
./openrct2: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by /home/user/.local/games/OpenRCT2/libopenrct2.so)

- [ ] Reproducible in RCT2 (vanilla)? no

**Steps to reproduce:**
1. download and extract linux 64bit version of 0.2.4
2. run openrct2
3. report this bug
4. fix it by reusing libzip.so.4 from some random snap package, apt install curl, *add*  LD_LIBRARY_PATH with some paths containing needed libraries.

how to solve this: do a deb package with listed dependencies *OR* include dependencies in the archive.

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by IntelOrca** [comment]
We have a appimage instead which should work.

https://github.com/OpenRCT2/OpenRCT2/releases/download/v0.2.4/OpenRCT2-0.2.4-linux-x86_64.AppImage

**Comment by Ruedii** [comment]
It seems it is looking for the wrong versions of many libraries even the a (newer) compatible version is installed, it is not looking for the "version generic" filename.

Ubuntu 19.10 also has this issue.

Unfortunately the PPA also only provides versions for the dev release, not the stable release.  The stable release stopped being updated for newer ubuntu versions quite a while ago.

BTW the AppImage works good on ubuntu.

**Comment by Gymnasiast** [comment]
@Ruedii There is no stable release, it's just a release and not more stable than development builds. It's mostly there for people with bad internet and repository maintainers.

@NESC1US Just use the PPA. Actually, if you had followed the [Getting Started Guide](https://openrct2.io/getting-started/index.html), you wouldn't even have run into this problem.
