### ISSUE TITLE
Create functions for common operations on CoordsXY(Z)(D)

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#10298]
There are two common operations on CoordsXY.

The first:
```
coords.x &= ~0x1F;
coords.y &= ~0x1F;
```

This resets them to the beginning of the tile.

The second:
```
coords.x &= ~0x1F;
coords.x += 16;
coords.y &= ~0x1F;
coords.y += 16;
```

This changes the coordinates to the centre of the tile.

Considering they're quite common, I think we should create methods for them. Some things to discuss are:
- Their naming
- Whether they should just concern x and y, or also modify z.
- Whether they should modify the object itself, or return a modified version and leave the original intact.

**Comment by duncanspumpkin** [comment]
I agree. For the other modifying function (rotate) it returns a modified new object retaining the original object. I suggest we do the same.

Z coordinates don't factor into this. I don't think there are any instances where z is truncated.

Also note for any person making this change ~0x1F is the same as 0xFFE0 which is also used in lots of places.

**Comment by tupaschoal** [comment]
Sounds like good functions indeed. Would naming them `toTileStart` and `toTileCentre` be good enough?

**Comment by IntelOrca** [comment]
> Whether they should modify the object itself, or return a modified version and leave the original intact.

Definitely return a new one, leave original intact.

**Comment by tupaschoal** [comment]
I didn't find many combinations of what you described to be `toTileCentre`, unless these multiplication operations also mean that
```
    mapTile.x -= (tool_size - 1) * 16;
    mapTile.y -= (tool_size - 1) * 16;
    mapTile.x &= 0xFFE0;
    mapTile.y &= 0xFFE0;
```

**Comment by duncanspumpkin** [comment]
@tupaschoal that would be a subtly different tile centre. A lot of the code that does centering isn't converted to using a CoordsXY at the moment. You will see it a bit in the peep code. Some of the time its not really centring as much as it is rounding up.

If you do a search for 0xFFE0 or ~0x1F you will see that there are a lot of instances of setting to tile start. I've also thought of another variation of the same thing floor2(..., 32) is the same as `& 0xFFE0`.

**Comment by tupaschoal** [comment]
K searched for all the quoted `&` operations, and changed every place that was using `CoordsXY`. The `floor2` option I didn't seek

**Comment by tupaschoal** [comment]
I guess this can be closed now
