### ISSUE TITLE
Incorrect rendering when building flat rides

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#10291]
**OS:** Windows 10
**Version:** 0.2.4
**Commit/Build:** 7718d83

**Steps to reproduce:**
1. Build a flat ride such as Merry-go-ground or Twist or etc.
2. See the screenshot

Anyway it is built successfully.
I experieced similiar issue when I build some pre-designed coaster, but I can't reproduce it now.

**Screenshots / Video:**
![미개척된 숲 2019-11-25 17-39-21](https://user-images.githubusercontent.com/10726524/69525096-ba240080-0faa-11ea-81f8-37efe74b9b98.png)

**Comment by ZehMatt** [comment]
Which drawing engine(s) is/are affected by this?

**Comment by Gymnasiast** [comment]
Your commit is older than https://github.com/OpenRCT2/OpenRCT2/commit/831050745c0c61cffe03c078cab6560652b6819b , which fixed a problem in this window. Please update your game and see if the issue persists.

**Comment by telk5093** [comment]
@Gymnasiast I think it is fixed. Thanks
