### ISSUE TITLE
Crash when running from Windows command line / Powershell

### ISSUE THREAD

**Issue by RollingStar** [OpenRCT2/OpenRCT2#1029]
--verbose also makes it crash.

PS C:\Users\RollingStar> D:\Backup\Downloads\OpenRCT2-0.2.0-develop-b567\openrct2.exe --verbose
Starting OpenRCT2 v0.2.0-develop-54cf1c43713bfaf60aa996f9252721b6759daf34, b567, OpenRCT2.com
  Windows (x86)
  Apr 28 2015 16:14:16

Time: 2015/04/28 20:32:53
VERBOSE: initialising game
VERBOSE: loading object list cache (plugin.dat)
VERBOSE: loading scenario details, C:\Program Files (x86)\GOGcom\RollerCoaster Tycoon 2\Scenarios\Africa - African Diamo
nd Mine.SC6
PS C:\Users\RollingStar>

**Comment by duncanspumpkin** [comment]
Seems to work fine for me.

**Comment by RollingStar** [comment]
Still crashes on the latest build. In admin or regular command prompt. Got a new graphics card since the last time, too.

**Comment by IntelOrca** [comment]
@RollingStar Does it still crash?

**Comment by RollingStar** [comment]
Works fine now. This time I used the OpenRCT2 launcher to download the latest version, then ran it with Powershell. Works with or without **--verbose**.
