### ISSUE TITLE
Feature request: hotkeys for changing the window scale factor

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#10305]
I quite often need to change the window scale factor so the option to assign hotkeys to increasing and decreasing the scale factor would help me and presumably some other people smooth out our gameplay a lot.

**Comment by Gymnasiast** [comment]
For my understanding: why do you change the window scale factor so often?

**Comment by LordMarcel** [comment]
I often use a scale factor of 2 for my videos as otherwise a lot of things are very small and difficult to see on the screen at 1080p, especially for people watching on their phone. During my live streams, I also switch every now and then to zoom in a bit further if I need to show something.

**Comment by AaronVanGeffen** [comment]
I see no harm in adding this, but we probably should not assign a binding by default.

**Comment by 0Cufox0** [comment]
I'm currently trying to do this, and as @AaronVanGeffen said it will not have a binding by default.
