### ISSUE TITLE
Zooming in and out works incorrectly.

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#10304]
**OS:** Windows 10
**Version:** 0.2.4
**Commit/Build:** 7e96ddf

In this build zooming in and out makes the screen move to northern corner of the map: https://www.youtube.com/watch?v=G4xYEEXQjlo This didn't happen yet yesterday.

**Comment by duncanspumpkin** [comment]
Will be caused by refactoring

**Comment by Gymnasiast** [comment]
Also tagging @tupaschoal .

**Comment by tupaschoal** [comment]
I'll look into this tomorrow morning

**Comment by tupaschoal** [comment]
For purposes of reproducing the behavior, the bug only happens when zooming in and out using the mouse wheel, but not when clicking on the zoom buttons

**Comment by tupaschoal** [comment]
Culprit is https://github.com/OpenRCT2/OpenRCT2/commit/b316f447a
