### ISSUE TITLE
Clarify if libsdl2-ttf is required as a dependency

### ISSUE THREAD

**Issue by gktrk** [OpenRCT2/OpenRCT2#10308]
Per https://github.com/OpenRCT2/OpenRCT2/blob/f963f969c10229a07b10a82a2b200f4ca98a1bb3/dockerfiles/ubuntu_amd64/Dockerfile#L39 there is an impression that libsdl2-ttf is a required dependency. However, what seems to really happen is that code from libsdl2-ttf was adopted to OpenRCT2 instead of being linked against (https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/drawing/TTFSDLPort.cpp#L2):

```
/**
 * The following code is from SDL2_ttf (2 Jan 2017).
 * Taking just what was needed for OpenRCT2 with all SDL2 calls
 * removed.
 */
```

Furthermore, libsdl2-ttf installs the header file `SDL_ttf.h` but a simple `$ grep -rn 'SDL_ttf.h'` in the repository yields no hits. It appears that the header file is not being included at all.

Please clarify if libsdl2-ttf is a real dependency.

**Comment by janisozaur** [comment]
No, its not required

**Comment by janisozaur** [comment]
See https://github.com/OpenRCT2/OpenRCT2/pull/5702

**Comment by Gymnasiast** [comment]
@gktrk Is the dockerfile the only place that references `libsdl2-ttf`, or did you find more places?

**Comment by gktrk** [comment]
@Gymnasiast here's what I can find:

```
dockerfiles/full/Dockerfile:53:RUN yaourt -S --noconfirm mingw-w64-sdl2_ttf
dockerfiles/full/Dockerfile:55:RUN yaourt -S --noconfirm lib32-jansson lib32-curl lib32-sdl2 lib32-sdl2_ttf
dockerfiles/mingw-arch/Dockerfile:58:        mingw-w64-sdl2_ttf \
dockerfiles/ubuntu_amd64/Dockerfile:39:RUN apt-get install --no-install-recommends -y ccache cmake libsdl2-dev libsdl2-ttf-dev pkg-config libjansson-dev libspeex-dev libspeexdsp-dev libcurl4-openssl-dev libcrypto++-dev libfontconfig1-dev libfreetype6-dev libpng-dev libzip-dev git libssl-dev ninja-build libicu-dev libgtest-dev
dockerfiles/ubuntu_i686/Dockerfile:9:RUN apt-get install --no-install-recommends -y ccache cmake curl ca-certificates libsdl2-dev:i386 libsdl2-ttf-dev:i386  pkg-config:i386  libjansson-dev:i386 libspeex-dev:i386 libspeexdsp-dev:i386 libcurl4-openssl-dev:i386 libcrypto++-dev:i386 libfontconfig1-dev:i386 libfreetype6-dev:i386 libpng-dev:i386 libzip-dev:i386 libssl-dev:i386 ninja-build libicu-dev:i386
scripts/linux/install.sh:97:		brew install jansson sdl2 sdl2_ttf speex --universal
```

**Comment by Gymnasiast** [comment]
@gktrk Ah, ok. Could you open a pull request to remove them?

**Comment by gktrk** [comment]
Will do
