### ISSUE TITLE
Path items such as benches can be placed on railroad grade crossings

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#10313]
**OS:** Windows 8
**Version:** 0.2.4
**Commit/Build:** 8378790

It's possible to place benches and other path items on a path tile that's part of a railroad's grade crossing. (See screenshot.) This doesn't really hurt anything, of course, but it looks really stupid. I think it would be better if a path tile with a railroad grade crossing on it were treated like a path tile that's a 4-way intersection: error message if you try to place something on it, and if you place something on it before building the crossing, that item will remain invisible and not really there until the crossing is removed.

Edit: the one exception might be for jumping fountains. Just like on a 4-way path intersection, those could still work on a grade crossing and still look fine.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Build path
2. Build miniature railroad across path
3. Build bench on the tile where the railroad crosses the path.

![Fast Foods Factory 2019-11-30 18-13-23](https://user-images.githubusercontent.com/26573303/69908533-b7594f00-13a0-11ea-8c86-53dc0ba8d248.png)

**Comment by Gymnasiast** [comment]
Changing this to `bug`, as I consider it broken.

To fix this, two things need to be taken into account:
- Placing path furniture on level crossings should not be allowed
- When constructing a crossing, remove any existing path furniture (make sure to check _both_ methods of creating one)
