### ISSUE TITLE
Suggestion; an option to make loans more difficult to deal with

### ISSUE THREAD

**Issue by KuronekoLen** [OpenRCT2/OpenRCT2#10322]
Loans are basically an easy button for the game, allowing you to max them out without consequences in parks where company value isn't important. I think an option to enforce "Pay off your loan by deadline" or "compounding interest rate (settable by the user)" would be a good addition.

**Comment by duncanspumpkin** [comment]
You can already set the interest on the loan as far as i remember. There is always scope for more options like this but it comes down to needing a new save format.

**Comment by ocalhoun6** [comment]
And for certain victory conditions, you can require that the loan be repayed as well.

If you're building a scenario and you want to discourage the use of loans, you have several options already:
- decrease maximum loan size (all the way to $0, if you want to ban loans altogether)
- increase interest rate
- increase initial loan amount without increasing cash on hand
