### ISSUE TITLE
CMake Mac Build failes for MacOS 10.14+

### ISSUE THREAD

**Issue by scrapes** [OpenRCT2/OpenRCT2#10355]
Mac OS Catalina 10.15.1 (Suspected since 10.14+)
Current Master Branch / 0.2.4
commit 432ad7867a76363534131f478b7d58247a40e6b8

MacOS Xcode linker doesn´t find  libraries like jansson.
Linker failes with " library not found"

**Dump file**
 ```
    [ 72%] Built target libopenrct2
    Scanning dependencies of target openrct2-cli
    Scanning dependencies of target openrct2
    [ 72%] Building CXX object CMakeFiles/openrct2-cli.dir/src/openrct2-cli/Cli.cpp.o
    [ 73%] Linking CXX executable openrct2-cli
    ld: library not found for -ljansson
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[2]: *** [openrct2-cli] Error 1
    make[1]: *** [CMakeFiles/openrct2-cli.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
 ```

Referenced StackOverflow Question:
https://stackoverflow.com/questions/54068035/linking-not-working-in-homebrews-cmake-since-mojave

The new XCode Linker doesnt use the standard lib path /usr/local/lib where the Homebrew libs are installed. Instead it seems like the Linker searches in the path relative to the Project directory.
Like : $PWD//usr/local/lib 
This could be due to using the -issysroot option.

Tested working hotfix would be adding following lines somewhere in the head of CMakeLists.txt:
 ```
IF(APPLE)
    LINK_DIRECTORIES(/usr/local/lib)
ENDIF()
 ```

Building after change:
 ```
    [ 72%] Built target libopenrct2
    [ 73%] Linking CXX executable openrct2-cli
    [ 73%] Linking CXX executable openrct2
    [ 73%] Built target openrct2-cli
    [100%] Built target openrct2
    Build finished
 ```

this fixes the issue with the standard libary path not searched due to the before mentioned stackoverflow thread.

Would be nice to discuss this Issue since the "Fix" seems rather hacky.

**Comment by tomlankhorst** [comment]
It's CMake's job to find the appropriate include and library directories and pass them around to the compiler and linker. 

I looked at openrct2-ui/CMakeLists.txt and there I find that `jansson` is not a required dependency for non-MSVC platforms. 

Could you try #10521
