### ISSUE TITLE
Guests enter elevator through the base entrance but appear at the top, then they ride the elevator down.

### ISSUE THREAD

**Issue by tjwrona1992** [OpenRCT2/OpenRCT2#10372]
**OS:** Windows 10
**Version:** 0.2.4+
**Commit/Build:** fed417da033fe81d35be7a337e7f5ce4d762a0e1

I built a park with a simple elevator ride trying to reproduce a different bug and stumbled upon some weird behavior. When guests enter the bottom entrance of the elevator they appear at the top and ride the elevator down.

**Steps to reproduce:**
Open the attached save file and check out the elevator ride
[elevator_bug.zip](https://github.com/OpenRCT2/OpenRCT2/files/3962672/elevator_bug.zip)

**Screenshots / Video:**
[OpenRCT2 2019-12-13 15-11-55_Trim.zip](https://github.com/OpenRCT2/OpenRCT2/files/3962677/OpenRCT2.2019-12-13.15-11-55_Trim.zip)

**Comment by tjwrona1992** [comment]
When I go to move the entrance/exit of the elevator I get this warning in the console output: src\openrct2\actions\RideEntranceExitRemoveAction.hpp:104 (RideEntranceExitRemoveAction::Query)]: Track Element not found. x = 2688, y = 1600, ride = 0, station = 1

**Comment by tupaschoal** [comment]
I'm trying to reproduce this, but save starts with guests leaving and they never get in anymore x_x

**Comment by tjwrona1992** [comment]
Yeah the save file seems to not act the same once you reopen it >.<

**Comment by tjwrona1992** [comment]
Good thing I got video proof haha

**Comment by tupaschoal** [comment]
Weirdly I rebuilt it from scratch and couldn't reproduce :(

**Comment by tjwrona1992** [comment]
Me too... very odd.

**Comment by tjwrona1992** [comment]
Here is another map where the bug persists through saving

[elevator_bug.zip](https://github.com/OpenRCT2/OpenRCT2/files/3962967/elevator_bug.zip)

**Comment by tjwrona1992** [comment]
Some additional info: I moved the entrance/exit at the base so they weren't directly under the entrance/exit at the top and it temporarily fixed the issue.... but then after about another hour of gameplay the bug came back even though the entrances/exits are not directly above each other.

**Comment by tupaschoal** [comment]
I went as far as 0d2fd33fd and it still happened, so it is either an old regression or has always been a bug.

**Comment by tellovishous** [comment]
I'm also having this same issue the African Diamond Mines scenario.

**Comment by Fred-1044276** [comment]
Still having this issue in v0.2.5. At the time of writing this and #11261, my commit/build is fdf9806.
