### ISSUE TITLE
Guest List is out of order

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#1038]
https://www.dropbox.com/s/5484iwqap3ciy60/Green%20River%202.SV6?dl=1

The list, where you can see all your guests in the park, the newest peeps coming in the park are listed on top if you open a RCT2 park in OpenRCT
Example:
Original = [guest 1][guest 2][guest 3]
Open it in openRCT: [guest 4][guest 1] etc
So the oldest guests are listed somewhere in the middle
visitor 1913 is the oldest in that save.

This additional save has never been opened in OpenRCT2, if you open it and have guests come in you should see the issue.
https://www.dropbox.com/s/ed8okt9ihdkwblo/Old%20Farms.SV6?dl=1
If you open the guest list right away, you'll see the first new guest appear at the top instead of the bottom

**Comment by rustinlee** [comment]
Can you upload your files somewhere else? Dropbox is throttling your bandwidth.

**Comment by Gymnasiast** [comment]
Cannot reproduce this in the current version. Do you still have this issue?

**Comment by PFCKrutonium** [comment]
Kind of?

Handymen are still bugged (out of order after 10 due to bad sorting) but Guests seem to be fine now.

**Comment by IntelOrca** [comment]
@PFCKrutonium you get that with Windows Explorer, for numbers to be sorted correctly they have to have the same number of digits.

**Comment by PFCKrutonium** [comment]
I know that, but I would prefer the original sorting that actually made sense...

**Comment by Gymnasiast** [comment]
Sorting 10 after 1 and before 2 makes no sense from a human viewpoint indeed. We should correct that. (Also, IIRC, Windows Explorer uses human sorting since XP.)

**Comment by IntelOrca** [comment]
Did it sort correctly in vanilla?

**Comment by Gymnasiast** [comment]
It did, yes.

**Comment by Broxzier** [comment]
Can confirm
![](http://i.imgur.com/dg0Iruc.png)

**Comment by IntelOrca** [comment]
OK, if you use powershell or command prompt its old style.

**Comment by IntelOrca** [comment]
I don't know why the behaviour is different from vanilla, we haven't yet reversed the function for sorting: peep_update_name_sort.

**Comment by PFCKrutonium** [comment]
it's been broken for a very long time, so idk

**Comment by IntelOrca** [comment]
I still don't know how the original sorted numbers because the behaviour in the peep sort function is just literally doing stricmp.

I have now exposed the peep name compare function, so someone is welcome to implement a better one which does the smart number ordering.
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/peep/peep.c#L9321

**Comment by marijnvdwerf** [comment]
Would borrowing `strnatcmp` from PHP be a solution? https://github.com/php/php-src/blob/250938e2d35fc54161a18167b7901c5e3b574371/ext/standard/strnatcmp.c
