### ISSUE TITLE
Redundant "Save Changes?" prompt in permissionless MP

### ISSUE THREAD

**Issue by Richard-L** [OpenRCT2/OpenRCT2#10385]
Totally minor thing, but still feel this would be an improvement:

1. Join an MP server
2. Try to place an object and receive "you do not have building permissions"
3. Use "quit to menu"

A "Do you want to save changes?" prompt appears that I believe is totally superfluous. The save is managed server side, and since you cannot make any changes to the map in the first place, all you _could_ save is the time you've seen pass on the map. I think it's unnecessary and hampers the flow of navigating game menus.

Thanks for considering.

EDIT: stable v0.2.4 (d645338)

**Comment by IntelOrca** [comment]
There may have been edits by other clients and it is asking you whether you want your own saved version of the map. Similar to how we do not automatically exit the game if you disconnect, it gives you time to save the map and continue solo.

**Comment by Richard-L** [comment]
Make sense, although I was the only player connected.
