### ISSUE TITLE
Track height marker is not visible at a certain direction

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#10386]
**OS:** Windows 10
**Version:** 0.2.4
**Commit/Build:** 9d09f1b

**Steps to reproduce:**
1. Show track height marker
2. Rotate the screen

**Screenshots / Video:**
This GIF shows the track marker is not visible when I rotate the screen. (Left is north at the first, rotating anti-clockwise):
![aa](https://user-images.githubusercontent.com/10726524/70864805-2cc84080-1f99-11ea-84f9-f0d250a70d06.gif)

**Comment by duncanspumpkin** [comment]
Caused by #10333 slight mistake with the signness of a value miscalculates which quadrant things are in which causes missing drawings at x, y values past a certain number on certain rotations.
