### ISSUE TITLE
Ride preview incorrectly centered

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#10417]
Probably a regression from the recent Coords refactors.

Current:
![openrct2_2019-12-22_03-59-37](https://user-images.githubusercontent.com/5415177/71316410-77e9c400-246f-11ea-9663-1b1dcf227f0f.jpg)

Expected:
![openrct2_2019-12-22_03-59-07](https://user-images.githubusercontent.com/5415177/71316395-69031180-246f-11ea-8139-b1c33d78e716.jpg)

**Comment by tupaschoal** [comment]
Culprit is 01c62437b
