### ISSUE TITLE
Path deletion using path builder moves cursor in opposite direction

### ISSUE THREAD

**Issue by erikhuizinga** [OpenRCT2/OpenRCT2#10426]
**OS:** macOS 10.14.6
**Version:** 0.2.4
**Commit/Build:** 341f85e

Deleting a path using the constructor (the non-manual path placement builder unit thingy) moves the current path construction cursor in the opposite direction.

- [ ] Reproducible in RCT2 (vanilla)? No: this is a bug compared to RCT2 vanilla.
- [ ] Specific to multiplayer? No: I experienced this in single player only.

**Steps to reproduce:**

1. Start the path constructor on a dead end path
2. Delete one path tile using the constructor
3. 🐛 notice that the constructor now is moved in the direction of the path instead of on the newly (moved back) end of the path.

**Dump file**

N/A

**Screenshots / Video:**

I'd attach two screenshots of steps 2 and 3, but I cannot find where they're stored.

**Save game:**

N/A

**Comment by erikhuizinga** [comment]
I haven't played openrct2 often recently, but I think this may have been introduced in the last two months, because I'm sure I would have noticed this bug immediately if it existed before.

**Comment by duncanspumpkin** [comment]
Yeah no doubt caused by the refactoring work. @tupaschoal

**Comment by tupaschoal** [comment]
Culprit is @duncanspumpkin  fb2f90741

**Comment by erikhuizinga** [comment]
Thanks for the quick fix! I can confirm the issue is no more.
