### ISSUE TITLE
Game crashes when saving

### ISSUE THREAD

**Issue by Wonkie12** [OpenRCT2/OpenRCT2#10434]
**OS:** [Windows 10]
**Version:** [0.2.4-26]
**Commit/Build:** [a2c7ecc]

When I try to save my park it crashes most of the time.
Also appears to crash on the release version.

OpenRCT works normally with "exporting objects" turned off. This object probably causes the crash:
[olitd.zip](https://github.com/OpenRCT2/OpenRCT2/files/4008042/olitd.zip)

- [ ] Reproducible in RCT2 (vanilla)? no
- [ ] Specific to multiplayer? no

**Steps to reproduce:**
1.  save your game as an exsisting file using the save button

**Dump file**
 
[17830202-8715-4c17-ab78-2b2d0d53b322(a2c7ecc_x86-64).zip](https://github.com/OpenRCT2/OpenRCT2/files/3994948/17830202-8715-4c17-ab78-2b2d0d53b322.a2c7ecc_x86-64.zip)

**Screenshots / Video:**

**Save game:**

[empty map.zip](https://github.com/OpenRCT2/OpenRCT2/files/3994896/empty.map.zip)

**Comment by AaronVanGeffen** [comment]
This issue seems to have been overlooked. It is now five years old, and the save export process has changed considerably since. I therefore think it best to close this issue.
