### ISSUE TITLE
Ride's Entrance/Exit is not buildable above a certain height level

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#10468]
**OS:** Windows 10
**Version:** 0.2.4
**Commit/Build:** 98110c0

I can't build the entrance/exit of a ride which is at height equals or more than 9.
If it is at height +8, I can build entrance/exit of it. But if it is at +9, I can't.

**Steps to reproduce:**
1. Build any ride platform at the height >= 9
2. Point the mouse cursor next to the ride to build the entrace or exit
3. The ghost entrance/exit is not displayed

**Screenshots / Video:**
![b](https://user-images.githubusercontent.com/10726524/71556673-bd654d00-2a7e-11ea-9980-23eca5f0b9f5.gif)
(I disabled the support limits to show you this issue, but it doesn't matter if it is enabled or not)

**Comment by Gymnasiast** [comment]
@duncanspumpkin @tupaschoal
