### ISSUE TITLE
Cannot place the Egyptian pyramid in the air

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#10477]
**OS:** Ubuntu 19.10
**Version:** 0.2.4+
**Commit/Build:** 4b0dff92aa871d3d64dad94856ba62e38a5c11c4

Once you start holding shift, the preview will disappear and attempting to place it will only yield `Cannot position this here...` with no further explanation.

Tagging @duncanspumpkin and @tupaschoal .

**Comment by tupaschoal** [comment]
Weirdly, it triggers a failed assertion on debug builds earlier than january. I will bisect with production to see if it is also that old.

**Comment by duncanspumpkin** [comment]
Yeah i know the source of this bug. It's to do with window scaling and protections implemented with that. If you look back a few commits i said this isn't correct but will prevent a crash.

**Comment by duncanspumpkin** [comment]
#10405 is the PR where I fixed the crash that would happen. Also see my comment about how this behaviour differs from vanilla.
