### ISSUE TITLE
Incorrect mouse cursor offset

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#10470]
**OS:** Windows 10
**Version:** 0.2.4
**Commit/Build:** 98110c0

Mouse cursor points differently between the stable and the recent development versions.
I think this issue is occured after new coordinates code had introduced.
It looks like that some kind of offset is changed.

**Steps to reproduce:**
1. When I use the landscape tool like this landscape,
![image](https://user-images.githubusercontent.com/10726524/71559269-6754d180-2a9f-11ea-8b2f-c22ca4dd5271.png)
 point the cursor to the right end edge(>)

2. Or when I place a fence in this yellow direction: 
![image](https://user-images.githubusercontent.com/10726524/71559258-53a96b00-2a9f-11ea-964e-6e464f0912e1.png)

**Screenshots / Video:**
[YouTube Video](https://youtu.be/3X9OUfKzgsw) shows that the cursor works differently between the stable version(00:00-00:02) and the recent development version(00:03-) when I point very similar position.

**Comment by Gymnasiast** [comment]
@duncanspumpkin @tupaschoal

**Comment by duncanspumpkin** [comment]
This is a really odd one will take a little while to work out. I'm having to bisect to find it and it takes a good while to compile with all the header file changes.

**Comment by duncanspumpkin** [comment]
Caused by https://github.com/OpenRCT2/OpenRCT2/pull/10285

**Comment by tupaschoal** [comment]
Thanks for bisecting it and fixing it @duncanspumpkin
