### ISSUE TITLE
Path breaks between level and inclined parts

### ISSUE THREAD

**Issue by erikhuizinga** [OpenRCT2/OpenRCT2#10486]
**OS:** macOS (x86-64)
**Version:** 0.2.4
**Commit/Build:** 2c359736e on develop

- [ ] Reproducible in RCT2 (vanilla)?
   - No: this would be a bug in RCT2 vanilla
- [ ] Specific to multiplayer?
   - No: single player

**Steps to reproduce:**
1. Build a level path
2. Build an inclined path into the air

**Save game:**

Zipped save game: [path-break-bug.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/4011343/path-break-bug.sv6.zip)

**Comment by Gymnasiast** [comment]
You mean that once you build the inclined path, it will disconnect from the flat piece, right?

**Comment by erikhuizinga** [comment]
Correct, that's what I mean.

**Comment by erikhuizinga** [comment]
I see that I uploaded the incorrect save game 🤦‍♂, uploading the correct one in a minute!

**Comment by duncanspumpkin** [comment]
`map_get_footpath_element` is being called with the wrong parameters in `RemoveIntersectingWalls` due to `GetBaseZ()` refactor. `RemoveIntersectingWalls` is badly labelled as it doesn't just remove intersecting walls it also connects paths.

L419 of FootpathPlaceAction.hpp
