### ISSUE TITLE
Edge case where Resolutions don't work correctly: Overscan Corrected Displays (nVidia 750 Ti)

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#1048]
![screenres](https://cloud.githubusercontent.com/assets/3945538/7528032/95ef7a16-f4f0-11e4-81b3-66407fdc0b3c.png)

The actual resolution of the screen is 1824x1036.

**Comment by IntelOrca** [comment]
It works for me still. Did you have more than one monitor?

**Comment by PFCKrutonium** [comment]
Nope, it's just plugged into a HDTV.

**Comment by IntelOrca** [comment]
Seems to also happen when Windows is not 100% DPI scale and openrct2.exe is not set to disable DPI scaling.

**Comment by mrtnptrs** [comment]
I have seen this bug quite a lot of times in the past, but isn't this fixed now?

**Comment by IntelOrca** [comment]
@PFCKrutonium can you still reproduce this?
