### ISSUE TITLE
Keep path objects when changing pathtype

### ISSUE THREAD

**Issue by WackedSwe** [OpenRCT2/OpenRCT2#10483]
When replacing paths it removes benches and lamps. Would there be a possible way to incorporate a texture switch instead of replacing the whole object when using paths?

**Comment by frutiemax** [comment]
If anyone wants to do a commit; commenting line #193 in FootpathPlaceAction.hpp make this work, the benches don't get removed.

```
GameActionResult::Ptr ElementUpdateExecute(PathElement * pathElement, GameActionResult::Ptr res) const
    {
        const int32_t newFootpathType = (_type & (FOOTPATH_PROPERTIES_TYPE_MASK >> 4));
        const bool newPathIsQueue = ((_type >> 7) == 1);
        if (pathElement->GetSurfaceEntryIndex() != newFootpathType || pathElement->IsQueue() != newPathIsQueue)
        {
            res->Cost += MONEY(6, 00);
        }

        footpath_queue_chain_reset();

        if (!(GetFlags() & GAME_COMMAND_FLAG_PATH_SCENERY))
        {
            footpath_remove_edges_at(_loc, reinterpret_cast<TileElement*>(pathElement));
        }

        pathElement->SetSurfaceEntryIndex(_type & ~FOOTPATH_ELEMENT_INSERT_QUEUE);
        if (_type & FOOTPATH_ELEMENT_INSERT_QUEUE)
        {
            pathElement->SetIsQueue(true);
        }
        else
        {
            pathElement->SetIsQueue(false);
        }

        //Issue #10483 fix
        //pathElement->SetAddition(0);
        pathElement->SetIsBroken(false);

        RemoveIntersectingWalls(pathElement);
        return res;
    }
```

**Comment by duncanspumpkin** [comment]
I think this might be done for (possibly questionable) realism.

**Comment by ocalhoun6** [comment]
@frutiemax: Still have to make sure it removes path items when switching between queue and normal paths, though, right?

You don't want a flow of: build trash can on regular path --> replace regular path with queue path --> now have trash can on queue path. (Or vice versa withe queue line TV's.)

I'm not quite conversant enough with the way this code works to be sure, but it looks to me like this could happen if all you do is comment out that line. I think it would need an additional conditional in there, to trigger "pathElement->SetAddition(0)" if the queue/not queue state of the new/old paths don't match.

**Comment by frutiemax** [comment]
Oh right forgot about the queue line. I'll check this out.
