### ISSUE TITLE
Can not build on raspberry pi - /usr/bin/ld: libopenrct2.a(Path.cpp.o): in function `std::filesystem::__cxx11::path::path

### ISSUE THREAD

**Issue by Kashouryo** [OpenRCT2/OpenRCT2#10495]
**OS:**  Raspbian (Debian 10 armv7 armhf)
**Version:** defaut branch

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. git clone https://github.com/OpenRCT2/OpenRCT2
2. mkdir build
3. cd build
4. cmake ../
5. make

error log:
https://pastebin.com/NibRkFm7

**Comment by gibmat** [comment]
Same issue I reported in #10352. I do have a hacky workaround in that issue to manually link in the required library.

**Comment by Kashouryo** [comment]
> Same issue I reported in #10352. I do have a hacky workaround in that issue to manually link in the required library.


Thanks for the quick fix! However, this is what I got after the quick fix:


`-- Performing Test CXX_WNO_CLOBBERED - Success
-- Performing Test CXX_WARN_REDUNDANT_DECLS
-- Performing Test CXX_WARN_REDUNDANT_DECLS - Success
CMake Error at CMakeLists.txt:219 (target_link_libraries):
  Cannot specify link libraries for target "libopenrct2" which is not built
  by this project.


-- Configuring incomplete, errors occurred!
See also "/home/pi/game/OpenRCT2/build/CMakeFiles/CMakeOutput.log".
See also "/home/pi/game/OpenRCT2/build/CMakeFiles/CMakeError.log".`

**Comment by gibmat** [comment]
From your error, it looks like you modified the `CMakeLists.txt` file at the root of the project; you need to edit `src/openrct2/CMakeLists.txt`.

**Comment by Kashouryo** [comment]
It worked like a charm! Thank you so much for your help!

Just a reminder to anyone else who wants to play OpenRCT 2 on a pi, you do need to run

sudo make install

After that, enjoy your game!
