### ISSUE TITLE
Attraktion Lift beim laden eines Spielstands unbrauchbar

### ISSUE THREAD

**Issue by Timmy99** [OpenRCT2/OpenRCT2#10509]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.2.4]
**Commit/Build:** [e.g. d645338]

Ein gebauter Lift mit mehreren Etagen wird nach dem Laden des Spielstands unbrauchbar. Angeblich sind keine Eingänge / Ausgänge vorhanden. Die Parkbesucher stehen an, aber können die Attraktion nicht mehr betreten. Sichtbar wird der Fehler auch am Zaun der Etagen: Es fehlt ein Stück Zaun an der Etage. Scheinbar möchte das Spiel hier den Eingang auf allen Etagen platzieren, was nicht möglich ist.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Platziere einen Lift mit 2 Etagen
2. Setze den Eingang an die untere Etage und den Ausgang an die obere Etage
3. Speichere den Spielstand und verlasse das Spiel
4. Lade den Spielstand

**Save game:**
 [Aufzugspark.zip](https://github.com/OpenRCT2/OpenRCT2/files/4020802/Aufzugspark.zip)

**Comment by Gymnasiast** [comment]
Es gibt hier kaum Leute, der Deutsch sprechen. Können Sie nächster Mal ihre Frage auf Englisch stellen?

**Comment by Gymnasiast** [comment]
(For people who don't speak German:)

This issue describes a problem with the lift getting unusable after saving and reloading. It sounds related to https://github.com/OpenRCT2/OpenRCT2/issues/10372.

**Comment by Gymnasiast** [comment]
Checking reveals that the fence draw bug was already present in 0.2.3.
