### ISSUE TITLE
MacOS 10.15 OpenGL SDL scaling issue

### ISSUE THREAD

**Issue by tomlankhorst** [OpenRCT2/OpenRCT2#10520]
An SDL HiDPI scaling issue occurs on Mac OS 10.15 Catalina. 
This only happens with the OpenGL renderer. 

**OS:** MacOS 10.15
**Commit/Build:** fb3fee8

Can anyone with a Windows system with HiDPI reproduce this? 

![image](https://user-images.githubusercontent.com/675432/71778305-672b6900-2fac-11ea-9ba1-bb68d0a53a3d.png)

**Comment by AaronVanGeffen** [comment]
This is unfortunate. I was hoping we'd fixed this last time by updating SDL2… Obviously not.

**Comment by tomlankhorst** [comment]
Yes, that's what I thought too. Seem to be related to the combination HiDPI, MacOS and OpenGL.

**Comment by AaronVanGeffen** [comment]
@tomlankhorst Has this been fixed by #10909?

**Comment by tomlankhorst** [comment]
Hey @AaronVanGeffen , sorry for the late reply! I don't have a HiDPI screen at this moment either. I'll try to test tomorrow.

**Comment by AaronVanGeffen** [comment]
Tom replied elsewhere that the issues have been resolved: https://github.com/OpenRCT2/OpenRCT2/pull/10909#issuecomment-602256856

Closing this.
