### ISSUE TITLE
Cannot place banners on paths above a certain height

### ISSUE THREAD

**Issue by RoelerCoaster** [OpenRCT2/OpenRCT2#10524]
**OS:** Windows 10
**Version:** v0.2.4-365
**Commit/Build:** 08ab15e

When trying to build a banner on a path above a certain height, the banner will not place and only a ghost piece is visible. The banner-window very briefly opens and then closes again. The ghost-piece does not remain when saving and reloading a park. You **do** lose money when trying to build the banner.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Place a path at at least +8 units
2. Try place a banner on the path

**Screenshots / Video:**

![banners](https://user-images.githubusercontent.com/5968886/71784854-95cf3100-2ff8-11ea-8f1f-d11f75ca1d73.gif)

**Comment by tupaschoal** [comment]
Regression introduced by 9b1395bfb on #10408
