### ISSUE TITLE
Height marks on tracks only showing from 2 sides

### ISSUE THREAD

**Issue by Wonkie12** [OpenRCT2/OpenRCT2#10537]
**OS:**  Windows 10
**Version:** 0.2.4-368
**Commit/Build:** 26d6155

Height marks on tracks only showing from 2 sides

- [ ] Reproducible in RCT2 (vanilla)? NO
- [ ] Specific to multiplayer? NO

**Steps to reproduce:**
1. Build a ride or put height marks for rides on.

**Dump file**

**Screenshots / Video:**

![2020-01-08](https://user-images.githubusercontent.com/37348083/71973841-46634d80-3210-11ea-8114-193f59aa9de7.png)
![2020-01-08 (1)](https://user-images.githubusercontent.com/37348083/71973928-7dd1fa00-3210-11ea-93ec-3f0868fa21db.png)
![2020-01-08 (2)](https://user-images.githubusercontent.com/37348083/71973930-7f9bbd80-3210-11ea-9040-a0a82957f066.png)
![2020-01-08 (3)](https://user-images.githubusercontent.com/37348083/71973934-81658100-3210-11ea-9185-e192d7395141.png)

**Save game:**

**Comment by Gymnasiast** [comment]
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/10386.
