### ISSUE TITLE
Guests getting permanently stopped at one specific level crossing

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#10535]
**OS:** Windows 8
**Version:** 0.2.4
**Commit/Build:** 8378790

Odd glitch I had: at one specific grade crossing, guests that stopped to wait for a train would stay there forever, even though the train was long gone and no more were coming anytime soon. Additional guests would get stuck in that spot as well, waiting for the nonexistent train to go by.

Reloading the game from the saved file didn't resolve the issue, so you'll probably be able to take a look at it by opening that saved game.

After deleting the grade crossing and rebuilding it, the issue was resolved, but I thought it might be worth looking into. If it happened once, it could happen again ... and if I hadn't noticed it happening, the huge mass of stuck guests that would build up might become a problem.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
???

**Dump file**

**Screenshots / Video:**
![Wheel of Time 2020-01-07 15-18-34](https://user-images.githubusercontent.com/26573303/71939839-da79da00-3168-11ea-9ecf-a36012aa1ac9.png)
![Wheel of Time 2020-01-07 15-18-35](https://user-images.githubusercontent.com/26573303/71939845-e1a0e800-3168-11ea-83de-3de50aa1111c.png)

**Save game:**

[Wheel of Time_pl1_error.zip](https://github.com/OpenRCT2/OpenRCT2/files/4033040/Wheel.of.Time_pl1_error.zip)

**Comment by Gymnasiast** [comment]
More people appear to have this problem: https://www.reddit.com/r/openrct2/comments/emazzw/forest_frontier_guest_count/

**Comment by ocalhoun6** [comment]
A quick and dirty band-aid fix might be to just add a maximum amount of time that peeps will wait for a train before moving again?

**Comment by AaronVanGeffen** [comment]
Such a value would need to be stored somewhere on a per-peep basis. We cannot extend the peep structure while maintaining SV6 compatibility, unfortunately. (And if we choose to disregard SV6 for just this, it would break multiplayer, anyway.)

**Comment by Gymnasiast** [comment]
@AaronVanGeffen Are you sure about that? We couldn't _save_ the value, but our sprites and SV6 sprites have been decoupled. The only downside of not being able to save it is that this timer would reset whenever the game is reloaded.

I do think there might be a better solution, though: recalculating the blocked tiles when reloading a save. We already do this for some things that _are_ saved in SV6 but tend to get corrupted.

**Comment by ZehMatt** [comment]
This timer would need to be in sync with everyone in multiplayer.

**Comment by ocalhoun6** [comment]
I've encountered this bug again on another park, adding screenshot and save file in case that helps.

Screenshot:
![Bumbly Beach 2022-08-23 10-39-12](https://user-images.githubusercontent.com/26573303/186282507-77a5ce0a-4e37-41cb-8a6e-5715c83813c6.png)

Save file:
[Bumbly Beach_crossing_error.zip](https://github.com/OpenRCT2/OpenRCT2/files/9411076/Bumbly.Beach_crossing_error.zip) (Rename to .park)

**Comment by rik-smeets** [comment]
I'll take a shot at this one too.
