### ISSUE TITLE
RCT1 parks have too many rides available

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#10547]
Easily visible in scenarios like Forest Frontiers or the competition scenarios. Not entirely surprising, as RCT research is byzantine.

Originally reported as part of https://github.com/OpenRCT2/OpenRCT2/issues/8875 , but since that contained two unrelated issues, I'm splitting this off.

**Comment by Gymnasiast** [comment]
The reason that the Go Karts Competition has too many rides available is because they are all in the research list, but the `available_rides` and `available_vehicles` variables have been modified to hide them. Basically, the list is deliberately corrupted. I could change OpenRCT2's behaviour and not import them, but that would be annoying for people with accidentally corrupted research.

**Comment by IntelOrca** [comment]
You only need to do this logic when importing S4.
