### ISSUE TITLE
Crash on scenario load due to rides being selected in scenario creation

### ISSUE THREAD

**Issue by thegreatpl** [OpenRCT2/OpenRCT2#1054]
When starting a new scenario, if too many rides have been selected during the creation process, the game CTDs (Crash To Desktop). The too many objects is at the least the maximum number usually allowed. This counts for when 128 rides have been selected as rides being available to be built in the game. It also counts for 127 rides selected. And for 100 rides. 

RCT2 vanilla only is installed. I do not currently have the WW and TT discs available to install and test to see if this is a problem with them. 

Further tests with the default settings show that a park can be built with the scenario editor and opened. Testing also shows that when selecting the maximum number of scenery items it allows the scenario to be loaded. 

Testing was achieved by selecting the rides in sequence, without removing the defaults from the list. Which may mean that the problem is in fact with one or more of the rides selected. Max scenery items were also selected on testing 127 and 100 rides. OS is Windows 8.1. Version of openRCT2 is build 81, though the problem (or one similar) has been present since at least build 77, due to myself noticing it a few days ago. 

Actually, on reflection, the problem is more likely to be one of the rides being selected. Which one however is the question. I did check the Looping Rollercoaster, having seen an issue where it apparently has some new launch modes, but it still crashes when excluding it and having 128 rides, and does not crash when just including it. 

Having Chairlift (both types) selected does cause the crash, however, selecting 128 excluding the chairlift still seems to cause the crash. Having only the first chairlift selected (and other defaults) does not cause the crash. Same with only the Ski-lift. Trying selecting all types of wooden rollercoaster (and defaults) likewise causes a crash when trying to load the scenario. However, selecting all the different types of car rides does not cause the crash. 

However, it should be noted that I did play a build-your-own-six-flags game after first encountering this problem, which most definitely has multiple types of wooden rollercoaster selected, indicating a problem with the scenario editor.

**Comment by thegreatpl** [comment]
Having finally updated Visual Studio, the problem appears to be crashing on line 208 in research.c. The problem appears to be that local variable scenarySetEntry has not been set properly from g_scenerySetEntries. Or at least, the memory is not able to be be read.

**Comment by thegreatpl** [comment]
Hmmm, also crashing at line 292, and cannot write the memory. 

Unhandled exception at 0x5C34F769 (openrct2.dll) in openrct2.exe: 0xC0000005: Access violation writing location 0x00000018.

This might be because I made sure chairlift was researched at the beginning of the game.

**Comment by thegreatpl** [comment]
Miniature Railway seems to be fine, as does the mini-rollercoaster. Monorail is not however, same with the metal wild mouse, and the hyper twister rollercoaster, Suspended Swinging rollercoaster, Junior rollercoaster. 

Haven't checked the rest.

**Comment by duncanspumpkin** [comment]
Research.c is often the point where the game crashes even when its not at all related to research. It sounds like something is breaking the loaded object list. Can you provide a save of a crashing scenario and I will try take a look.

**Comment by thegreatpl** [comment]
http://www.mediafire.com/download/qmqhwtasm49oqwc/New_Haven_Resort.sc6 This is one of the scenario attempts that is crashing.

**Comment by Gymnasiast** [comment]
If you create a scenario now, does it still cause the same problems?

**Comment by Gymnasiast** [comment]
With the amount of changes since this has been reported, it's likely this bug report is no longer valid. I will therefore close it.
