### ISSUE TITLE
Hover the mouse cursor with path on a certain height level works weird

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#10550]
**OS:** Windows 10
**Version:** 0.2.4
**Commit/Build:** 09ac8a0

When I try to build a path, while the surface of land is high (above +9~10), the ghost of path is not on the surface but beneath the surface as you can see at the screenshot I attached below:

**Steps to reproduce:**
1. Raise the surface more than 9 or 10
2. Open path window
3. Select "Construct footpath on land"
4. Hover the mouse at (1)

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/10726524/72217773-1f8d7a00-3576-11ea-873a-d8c3c9f60e92.png)

**Comment by Gymnasiast** [comment]
Most likely another overflow because a big Z coordinate is now saved in an 8-bit integer.

Tagging @tupaschoal .
