### ISSUE TITLE
Last action in multiplayer is shifted

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#10587]
**OS:** Windows 10
**Version:** 0.2.4
**Commit/Build:** 8a9f0ee

Last action in multiplayer is shifted as you can see below GIF.
Note that my nickname is ``TELK``, and my action(builing Roto-drop) is displayed as ``troy7737``'s.
``Kotomi17``'s action is displayed as mine(``TELK``'s),
``troy7737``'s action is displayed as ``Kotomi17``'s.
It seems that shifted.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Screenshots / Video:**

![asdf](https://user-images.githubusercontent.com/10726524/72684041-808df280-3b20-11ea-9e84-06c13c7ed197.gif)

**Comment by CorySanin** [comment]
Here's another video: https://streamable.com/vrw1w

**Comment by CorySanin** [comment]
I'm still seeing this sort of issue when using prebuilt ride layouts. Is it just me?

**Comment by Gymnasiast** [comment]
@CorySanin Hard to say. Could you test it thoroughly, and if it is still a problem, open a new issue?

**Comment by CorySanin** [comment]
Will do.
