### ISSUE TITLE
Clearance check not working

### ISSUE THREAD

**Issue by Job26** [OpenRCT2/OpenRCT2#10586]
**OS:** [Windows 10]
**Version:** [0.2.4]
**Commit/Build:** [423-g3ba8369f2(3ba8369 on develop)]

Able to build track/footpath through objects (other track or ground) when the 'disable clearance check' option is disabled

- [-] Reproducible in RCT2 (vanilla)?
- [-] Specific to multiplayer?

**Steps to reproduce:**
1. Build track
2. Build track on same tile at same height

**Dump file**

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/55745329/72683685-a9d76000-3ad9-11ea-9f56-5e1a6585fd40.png)

**Save game:**
https://drive.google.com/open?id=14IpHY8pFq9Ajtx6Miuvh__9CvsSJ_fbi

**Comment by duncanspumpkin** [comment]
Already fixed use the latest version.
