### ISSUE TITLE
Tracks should display file paths/filenames in Track Designer/Manager

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#10592]
**OS:** Windows 7
**Version:** 0.2.4-421
**Commit/Build:** 8a9f0ee

Since scenario and object files are given similar treatment on the Scenario Selection and Object Selection screens, I figured it'd be fitting to do the same for track designs to avoid situations where you would get a blank/invalid track design file that cannot be read by the game, but you can't easily find the offending file(s).
![whereisthecoaster](https://user-images.githubusercontent.com/4167951/72688699-cd99a680-3ad7-11ea-9b9a-82c398c9f438.png)

**Comment by AaronVanGeffen** [comment]
What if it's a .txt file or some such? Shouldn't it just skip the entry entirely?

**Comment by Superjustinbros** [comment]
I remember hearing it's an issue with the Spiral Roller Coaster being the first in the index list, if I'm not mistaken.

**Comment by Gymnasiast** [comment]
@Superjustinbros You're probably thinking of [this bug](https://github.com/OpenRCT2/OpenRCT2/issues/10541).

**Comment by Superjustinbros** [comment]
Yup, that's the one

**Comment by seifer7** [comment]
This feature was implemented in commit 6342fd3d9a3a8067096e51a7d1f0b87f826e3ea2

I believe this can be closed.
