### ISSUE TITLE
"Ride is too large/too much elements" warning on coasters with scenery

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#10602]
**OS:** Windows 7
**Version:** 0.2.4-421
**Commit/Build:** 8a9f0ee

![butwhycantisaveit](https://user-images.githubusercontent.com/4167951/72864482-2a48bd00-3ca2-11ea-8f66-0312090e8874.png)

This track design with scenery brings up the "Ride is too large, contains too many elements, or scenery is too spread out" error message when one tries to save it. This seems like it wouldn't be the case, as all the chosen scenery is on/right next to the track, and it's normal-sized for a Corkscrew coaster. Perhaps there's something else going on that I don't know.

I've attached the .td6 file containing the track and all the scenery it was saved with.
[The Boss(Louis).zip](https://github.com/OpenRCT2/OpenRCT2/files/4095197/The.Boss.Louis.zip)

**Comment by James103** [comment]
Is it possible that a track design can be placed with no problem, but attempting to save it back results in the error saying that the track design is too large to be saved?

**Comment by Superjustinbros** [comment]
> Is it possible that a track design can be placed with no problem, but attempting to save it back exactly as it was placed results in the error saying that the track design is too large to be saved?

Yes.

**Comment by duncanspumpkin** [comment]
I can't reproduce this.

**Comment by Superjustinbros** [comment]
Did you try saving the ride design with the same scenery selected as in the image? (including the paths that I added in)

**Comment by duncanspumpkin** [comment]
Yeah i couldn't do it exactly the same as you didn't provide a save file with all the scenery from the picture.

**Comment by Superjustinbros** [comment]
[The Boss Save Issue.zip](https://github.com/OpenRCT2/OpenRCT2/files/4100300/The.Boss.Save.Issue.zip)
Try this.

**Comment by Superjustinbros** [comment]
[DeluxeCornerBeachSandboxDeluxeApril3.zip](https://github.com/OpenRCT2/OpenRCT2/files/4126242/DeluxeCornerBeachSandboxDeluxeApril3.zip)
Here's another park I'm experiencing save issues with- all of these rides bring up this warning if they're saved with any form of scenery.

**Comment by Derpercoaster** [comment]
I have encountered this problem as well, and it's a bit more complex than you may think. 

 For instance, build a ride and allow it time to get its ratings. Make sure there are scenery items and/or paths nearby, and click "save ride with scenery". Click "select nearby scenery", and then manually remove each scenery item from the selection. 

After doing that, if you click "save", the game will tell you the error mentioned in the above post, even though absolutely no scenery items have been selected.

I think there is more to this issue than simply having too much scenery selected.

**Comment by Derpercoaster** [comment]
Also, just to clarify, this will occur with any ride and any scenery or paths, regardless of item count or ride size.

**Comment by RCTMASTA** [comment]
The first thing I can think of is that a counting variable is being
incorrectly incremented when the nearby objects are automatically selected,
and it's underflowing when everything is de-selected as a result.

 I can't test this hypothesis atm but I'd be curious to know (from someone
who knows where to look) if this is indeed the reason.

**Comment by Derpercoaster** [comment]
The game has some kind of "bit" limit, does it not? (I believe it is the same limit that prevents us from selecting more than the default amount of objects in the scenario editor.) The game might be counting the maximum amount of items immediately, and loops back to zero to avoid crashing. I'm not sure about this, as it's just a theory, but let me know if there's ground in it.

**Comment by duncanspumpkin** [comment]
That's not quite how it works. We use a standard vector container so under flowing, over flowing wouldn't be happening. At the last moment it converts this and checks the limits so adding removing shouldn't cause issues

**Comment by Superjustinbros** [comment]
What's weird about this bug is some coasters/rides in some parks do not produce this error at all- they'll let you save it with any or all its scenery while others will throw up the error if you dare try to save the design with anything more than the bare naked coaster/ride.

**Comment by tombomp** [comment]
The bug occurs when the scenery x or y is >127. The problem appears to crop up on line 531 of TrackDesign.cpp - when x or y is at 128 in the tile inspector it's -128 in the scenery struct then the subtraction takes it to a number way outside bounds. I'm completely clueless as to how it's supposed to work and therefore how to fix it though.
`        CoordsXY sceneryMapPos{ scenery.x * 32 - gTrackPreviewOrigin.x, scenery.y * 32 - gTrackPreviewOrigin.y };
        CoordsXY rotatedSceneryMapPos = sceneryMapPos.Rotate(0 - _saveDirection);
        TileCoordsXY sceneryTilePos{ rotatedSceneryMapPos };

        if (sceneryTilePos.x > 127 || sceneryTilePos.y > 127 || sceneryTilePos.x < -126 || sceneryTilePos.y < -126)
        {
            return STR_TRACK_TOO_LARGE_OR_TOO_MUCH_SCENERY;
        }`

**Comment by duncanspumpkin** [comment]
Okay thanks for that. I'll fix it tomorrow night
