### ISSUE TITLE
Track Designs with missing path design(s) do not use alternate pathways

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#10614]
**OS:** Windows 7
**Version:** 0.2.4-466-gd1eb04195
**Commit/Build:** d1eb041

In earlier versions of OpenRCT2, if you had a track design that used a pathway that was not currently in the object list, it would change the pathway to another type (usually the grey tarmac/blue queue path) before placing the design down. Currently, attempting to place down a track design without the correct path enabled leads to no paths appearing when the ride is built.

![nopaths issue](https://user-images.githubusercontent.com/4167951/73089335-0228ac00-3ea4-11ea-8fcf-31ff22263ac8.png)
(the select track design window is from the Track Designs Manager, and to the right is the same track as it appears when placed down)

**Comment by tupaschoal** [comment]
Could you please test it on a newer version? Because 0.2.0 is a 2yr old version, so the bug might have been fixed.

**Comment by Superjustinbros** [comment]
Oops, I made it 2.0.x instead of 2.4.x, my bad.

**Comment by Gymnasiast** [comment]
Should have been fixed by https://github.com/OpenRCT2/OpenRCT2/pull/15563.
