### ISSUE TITLE
Paths are free when built on the ground

### ISSUE THREAD

**Issue by RoelerCoaster** [OpenRCT2/OpenRCT2#10629]
**OS:** Windows 10
**Version:** v0.2.4-484-g61893fab4
**Commit/Build:** 61893fa

Building any path (normal or queue) on flat ground does not cost you any money. (Screenshot 1)

The price does increase when building elevated paths or paths underground. (Screenshot 2)
Also deleting paths still gives you the expected 10 _currency_

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1.  Open a park
2.  Build a path on flat ground

**Screenshots / Video:**
![freepaths1](https://user-images.githubusercontent.com/5968886/73302610-2e7e5880-4215-11ea-91ff-407fa6459634.png)
![freepaths2](https://user-images.githubusercontent.com/5968886/73302789-81f0a680-4215-11ea-9b38-1d17fd2942c6.png)

**Comment by duncanspumpkin** [comment]
This will have been caused by my refactor of map is clear

**Comment by janisozaur** [comment]
Shouldn't this warrant a test?

**Comment by duncanspumpkin** [comment]
I was surprised it didn't trigger in the replay test.

**Comment by ZehMatt** [comment]
Money is not tested in replays but probably worth doing, right now it only tests the sprite hash.
