### ISSUE TITLE
AppImages are broken

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#10623]
Running the latest built AppImages on a system that does not have all the OpenRCT2 dependencies installed will result in an error such as: `error while loading shared libraries: libzip.so.4`.

This is caused by a bug in patchelf which is used internally by linuxdeploy to build the AppImages.

https://github.com/linuxdeploy/linuxdeploy/issues/120

**Comment by IntelOrca** [comment]
My current solution:
https://github.com/IntelOrca/OpenRCT2/commit/9dcb1a8db8154e29cf8c469c5be591ba58b09738

**Comment by Gymnasiast** [comment]
Fixed by https://github.com/OpenRCT2/OpenRCT2/pull/10957.
