### ISSUE TITLE
Game bugs out and crashes if you get too many stations via copying stations with the tile inspector

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#10631]
**OS:** Windows 10
**Version:** 0.2.4
**Commit/Build:** 550da84

You can copy a station with the tile inspector so that you have two station 1's, or two station 3's. When you right click on the copied station and go into build mode, the game makes that station its own station, giving it a number that hasn't been used yet. If you already have four stations there are no unused station numbers, so the game will bug out causing the colors of the ride to change and a whole load of station numbers to be added to the ride. You can't always manage to see that as the game now also has a high chance of crashing whenever you click on the dropdown menu, which is what happened in this video: https://www.youtube.com/watch?v=fLppoAehtXs

Here is a screenshot of the ride having 126 stations after that happened:
![image](https://user-images.githubusercontent.com/25930360/73313142-b589fb80-422a-11ea-9e8a-f9bb891ebb05.png)

**Comment by Gymnasiast** [comment]
Dropdowns can only show 128 options. Most likely, the station tiles it places have index 255 ("-1").
