### ISSUE TITLE
Remove floating objects

### ISSUE THREAD

**Issue by Richard-L** [OpenRCT2/OpenRCT2#10637]
Was certain I'd posted this before but could've been on the discord:
![image](https://user-images.githubusercontent.com/4934209/73488520-60c0bf00-43a9-11ea-9747-a62673419238.png)

Would it be possible to either hide all floating objects (balloons, ducks, waving money, ...?) like you would hide scenery/rides/supports, or to add a console command "remove_floating_objects" to do away with the current air traffic?

This would be very helpful for us content creators when using "Giant Screenshot".

Thanks for considering.

**Comment by ocalhoun6** [comment]
There already is a setting for turning on or off the waving money ... but the other parts of this could be useful.

**Comment by Gymnasiast** [comment]
@ocalhoun6 Not true. The only thing you can toggle is whether guest's purchases also trigger waving money. Building will _always_ create a money effect.

**Comment by Richard-L** [comment]
I think building isn't even that important for now. It's more something to go in conjunction with giant screenshot.

It'd be amazing if a potential "remove_floating_objects" console command would also have effect while the game is paused btw. Sometimes people time certain things to the moment when you open their park (ie explosions, or a coaster having just finished a lifthill to great you). Therefore we always take giant screenshots with the game paused.

**Comment by Gymnasiast** [comment]
Has now been added.
