### ISSUE TITLE
Yellow arrow seems to have Z issues when building certain things - for example the ride Escape Hatch.

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#1063]
Can't really take a picture of it, but just "make your own 6 flags" and go to build it, and in theory you should see it.

**Comment by duncanspumpkin** [comment]
Does this still happen?

**Comment by PFCKrutonium** [comment]
I will check shortly.

**Comment by PFCKrutonium** [comment]
Seems to be fixed.
