### ISSUE TITLE
Changing water in object selection is more glitchy than I remember (compared to vanilla)

### ISSUE THREAD

**Issue by Ryder17z** [OpenRCT2/OpenRCT2#10639]
**OS:** Windows 10
**Version:** 0.2.4 3f837f5 x64

![openrct2_2020-02-01_05-10-48](https://user-images.githubusercontent.com/2000703/73586697-4e31ad00-44b1-11ea-909c-a1e23253c102.png)

video: http://puu.sh/F5RjT/16b330d3db.mp4

**Comment by Superjustinbros** [comment]
I tested this out a few days ago- it takes a while for the selection to fully load into the game after closing the object selector.

**Comment by Gymnasiast** [comment]
> Changing water in object selection is more glitchy than I remember 

That's not a proper title. Please describe the problem in terms that don't require psychic powers.

Anyway, this bug seems to have been with us for a long time.

**Comment by Ryder17z** [comment]
> > Changing water in object selection is more glitchy than I remember
> 
> That's not a proper title. Please describe the problem in terms that don't require psychic powers.
> 
> Anyway, this bug seems to have been with us for a long time.

the change is instant in vanilla.

**Comment by Gymnasiast** [comment]
#11912 is a duplicate with a better description.
