### ISSUE TITLE
"Custom" Dragon Coaster object conflict appears to permanently affect my game

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#10644]
**OS:** Windows 7
**Version:** 0.2.4-485-g3f837f561
**Commit/Build:** 3f837f5

For some time now I have been coming across a severe issue which has seemingly damaged if not otherwise altered one of the default RCT2 vehicle designs. The vehicle in question is the Dragon Coaster for the Corkscrew Roller Coaster, which apparently conflicts with an object I downloaded two years back called "DKDRAGON".
![dragon coaster problems](https://user-images.githubusercontent.com/4167951/73602600-e6c53d00-4544-11ea-860c-89ce7966c241.png)
The Dragon Coaster vehicle that's part of Wacky Worlds is overwritten by the DKDRAGON.DAT file, resulting in the original WW object appearing as a completely blank
coaster. I've tried removing the DKDRAGON file then restarting the game- but that does not cause the original Wacky Worlds Dragon Coaster vehicle to return to its former, fixed state.

I have attached the offending object file. It was initially installed into the OpenRCT2 download folder, not in the folder containing the main RCT2 download and its own folders.
[DKDRAGON.zip](https://github.com/OpenRCT2/OpenRCT2/files/4143515/DKDRAGON.zip)

**Comment by X123M3-256** [comment]
I checked the DKDRAGON file, the name and checksum differ from the vanilla dragon coaster, and the expansion flag is not set, so the game should treat it as a custom object. If this object is in fact the cause of this issue, it would be quite strange. I don't have the expansions though so I can't attempt to replicate the bug.

**Comment by Superjustinbros** [comment]
![dragondatcontents](https://user-images.githubusercontent.com/4167951/73610970-0e4ef080-45ab-11ea-846c-bc6d1c94d15c.png)
Turns out there is a DRAGON.DAT file that I got back in 2013 in my main RCT2 folder.

**Comment by X123M3-256** [comment]
That looks like the original dragon object from the expansions. If it was overwritten with the DKDRAGON object the name would be different. Can you post the first 16 bytes (as hex)? According to the JSON file the first four bytes should be 10 FC BC 0C and the checksum should be 40 0D 85 B6 (these are stored in little endian order). If those match (and I can't see why they wouldn't), I don't know why the game isn't loading it. 

Are there any error messages printed to the terminal when starting the game?

**Comment by Superjustinbros** [comment]
I looked a bit more into this issue, Apparently there's something going on with a custom scenery object I have installed
![image](https://user-images.githubusercontent.com/4167951/73613010-35afb880-45bf-11ea-9752-79115048c840.png)
![image](https://user-images.githubusercontent.com/4167951/73613014-4bbd7900-45bf-11ea-8ddd-433735fee3db.png)
This seems to be caused by the file "DRAGON01.DAT", which I then removed from OpenRCT2 and yet the Dragon Coaster still displayed this scenery object instead of the coaster proper.
![image](https://user-images.githubusercontent.com/4167951/73613092-22511d00-45c0-11ea-88d7-1c142693ff0b.png)
I then removed another file from my game, "DRAGON.DAT", and the preview for the WW Dragon Coaster on the New Roller Coasters menu became blank, and the coaster is now 100% invisible with no sort of vehicle in sight.
![image](https://user-images.githubusercontent.com/4167951/73613146-cf2b9a00-45c0-11ea-800c-eaa47ad96cf5.png)

**Comment by X123M3-256** [comment]
What I think happened is that the DRAGON.DAT object file somehow got replaced by a scenery object of the same name. Looking at the notepad screenshot, the last two digits of the checksum are the ASCII characters NZ which is not what I would expect if this was the correct object.

Deleting DRAGON.DAT entirely will make the train invisible, because this is what OpenRCT2 does with expansion objects when you don't have the original DAT file. The JSON files contain all the information needed to load the object but not the actual sprites to draw it; those are loaded from DRAGON.DAT.

If you think the JSON object may be corrupted, you can download a new copy [here](https://github.com/OpenRCT2/objects/blob/master/objects/rct2ww/ride/rct2.ww.dragon.json), however, I think this is unlikely. I would try replacing DRAGON.DAT with the correct file from a fresh install.

**Comment by Superjustinbros** [comment]
It seems like the cause was indeed the DRAGON.DAT file and not the JSON as I thought.
I did a fresh install of RCT2 on another computer and then imported it into the files I use for my OpenRCT2 download and the game displayed the Dragon Coaster properly.
