### ISSUE TITLE
Android version needs to implement show message box

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#10666]
Needs implementing. We might get away with using a SDL message box, though a native Android one would be preferable.

Tagging @NuclearFej .

**Comment by NuclearFej** [comment]
Could you be more specific about what triggers the bug?

**Comment by Gymnasiast** [comment]
I was mistaken about it crashing.

In any case: if you do anything that causes OpenRCT2 to display a platform message box, like removing/renaming g2.dat, it won't show that box.

**Comment by NuclearFej** [comment]
I have run into that same bug - pressing the use system dialog button in the save as dialog, the app crashes.

**Comment by Gymnasiast** [comment]
That's not surprising, both functions are stubs.

**Comment by mrtnptrs** [comment]
> I have run into that same bug - pressing the use system dialog button in the save as dialog, the app crashes.

These and more bugs with the Android build are pointed out in the issue tracker, labeled with Android  :)

**Comment by Gymnasiast** [comment]
Implemented by #10817.
