### ISSUE TITLE
Duck-cheat tooltips has incorrect font style

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#10662]
**Version:** 0.2.4
**Commit/Build:** Every build since 7fa41bb82d26cf483964cb88d0038cfa42d08645

The tooltip that appears when hovering over the "Create Ducks" and the "Remove Ducks" buttons in the cheat window, uses a font style that does not match the other tooltips.
The tooltips themselves don't really explain what these buttons do (creating ducks could explain that they only spawn on the edge of the map and only if there is water for example). This could be improved too.

In `data/language/en-GB.txt` you'll have to add a new string for the tooltip. Tooltips are prefixed by `{SMALLFONT}{BLACK}`. You don't need to edit the other language files, that will get done in the [localisation repository ](https://github.com/OpenRCT2/Localisation)after this fix gets merged.

You'll also need to update the widget definition for the buttons in `src/openrct2-ui/windows/Cheats.cpp`. The tooltips are the last parameter in the initialization list.

**Comment by thversfelt** [comment]
On behalf of team 20 of the [Software Architecture](https://se.ewi.tudelft.nl/delftswa/index.html) course at the [TU Delft](https://www.tudelft.nl/en/), we will investigate this issue and try to fix it. In the course, students are divided into teams that each pick an open-source project, analyze it and try to contribute to it. The results for each team are reported in four essays that are then included in a book called _Delft Students on Software Architecture, DESOSA_ (check out last year's edition [here](https://se.ewi.tudelft.nl/desosa2019/)). My team, team 20, chose OpenRCT2 and so we are hoping to make some valueable contributions!

For now, we will be working on this issue. Cheers.

**Comment by daandeheij** [comment]
Some screenshots for clarification:

The first screenshot shows the correct font when doing a mouse hover over the button:

![bug_correct_behavior](https://imgur.com/G9Vz7KF.jpg)

When hovering over `Create Ducks` or `Remove Ducks`, an incorrect font is used in the tooltip as shown below:

![openrct2_wrong_font](https://imgur.com/4F9jeeK.jpg)

**Comment by thversfelt** [comment]
> 
> 
> **Before**
> Wrong tooltip font and not an informative tooltip:
> 
> ![image](https://user-images.githubusercontent.com/40113382/75770833-0e2c4700-5d49-11ea-89e6-ab0b8486f0f4.png)
> 
> **After**
> The `create ducks` tooltip:
> 
> ![image](https://user-images.githubusercontent.com/40113382/75770706-c3aaca80-5d48-11ea-9e6d-581e85c708ee.png)
> 
> The `remove ducks` tooltip:
> 
> ![image](https://user-images.githubusercontent.com/40113382/75770760-e2a95c80-5d48-11ea-82c1-9932fd4df37e.png)

We have fixed the issue and submitted a [pull request](https://github.com/OpenRCT2/OpenRCT2/pull/10861).
