### ISSUE TITLE
Windows Defender identifies installer as Trojan/Detplock

### ISSUE THREAD

**Issue by squinky86** [OpenRCT2/OpenRCT2#10670]
Windows 10
0.2.4
1a5bbdb

When I download the latest installer, Windows Defender determines that it is a severe threat.

![detplock](https://user-images.githubusercontent.com/24464454/74085891-679f9f80-4a43-11ea-9906-e2771ef059cf.png)

**Comment by Gymnasiast** [comment]
First question in the FAQ, and asked thousands of times before :/

https://github.com/OpenRCT2/OpenRCT2/wiki/FAQ-&-Common-Issues#why-does-my-virus-scanner-not-trust-openrct2
