### ISSUE TITLE
Track designs not saving correctly

### ISSUE THREAD

**Issue by DollyMixedUpWoman** [OpenRCT2/OpenRCT2#10687]
**OS:** Windows 10
**Version:** 0.2.4
**Commit/Build:** d645338

Track designs not saving. I built and saved a maze design. When I go to build the saved design it i missing pieces. I am charged only for the pieces the game has built and refunded accordingly when I delete the ride. I also tried to save a mine train track from a server which also saved only a few pieces. I have many tracks saved from 7/2/20 and older that are fine. Both tracks i've tried to save since have failed. The maze design allows peeps to get stuck but the mine train won't let me test as it is not a complete circuit.

- [Unknown] Reproducible in RCT2 (vanilla)?
- [No] Specific to multiplayer?

**Steps to reproduce:**
1. Build a tracked ride
2. Save track design
3. Try to build from saved track design

**Screenshots / Video:**
![2020-02-10](https://user-images.githubusercontent.com/33560724/74196666-9e4d0400-4c55-11ea-9e3e-5c3cd066b96e.png)
(Maze 8 and maze 12 are old designs. Maze 8 is the most recent one)

**Save game:**
Track file
[10 Maze - Copy.txt](https://github.com/OpenRCT2/OpenRCT2/files/4183393/10.Maze.-.Copy.txt)

**Comment by Gymnasiast** [comment]
You're on a release build. Please update to a recent develop build first and try again.

**Comment by DollyMixedUpWoman** [comment]
Thanks! I didn't even think to check, what a muppet. Keep up the good work!
