### ISSUE TITLE
Multithreading causes huge performance degrade on i9

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#10705]
**Processor:** i9-7980XE (18c/36t)

With one window open containing a viewport, and an average FPS of 200 on OpenGL. When enabling multithreading, FPS drops to 25.

This only happens unless there is more than one viewport open including the main viewport.

**Comment by James103** [comment]
a) What version of OpenRCT2 are you using and what OS are you using to test this on?
b) Does this bug occur with other high-end processors (such as i9-9900k)?

**Comment by ZehMatt** [comment]
Thats interesting, can you perhaps profile which functions affect this?

**Comment by IntelOrca** [comment]
It isn't my PC so I don't access to it that often. This is using latest develop (a0fb955).
I don't have access to any other high-end processors to confirm.

**Comment by ZehMatt** [comment]
My only assumption so far is that the high amount of threads kills the performance, its currently spawning as many threads as cores. Maybe we should limit it to a maximum of like 4 or 8

**Comment by IntelOrca** [comment]
Probably better to base it on the size of the game window.

**Comment by James103** [comment]
If @ZehMatt's assumption holds, would that mean that observed performance is proportional to single-core performance, but **inversely** proportional to number of cores (or simultaneous threads) in the processor, assuming multithreading is enabled? That would mean that an Intel Core i9-9900k might reach ~250 FPS with OpenGL, but would drop to as low as 50-60 FPS with multithreading enabled.

**Comment by ZehMatt** [comment]
> Probably better to base it on the size of the game window.

On 1920x1080 its 60 jobs, that would mean it entirely exhausts all cores. I'm not sure whats really going on without getting a hand on that configuration.
