### ISSUE TITLE
Rides are disappeared when it is built in multiplayer

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#10713]
**OS:** Windows 10
**Version:** 0.2.4
**Commit/Build:** 38907fd

Rides are disappears when build another rides. It doesn't matter it is a flat rides or track rides.
I think it is occured from 723f658. It is fine at df28bca

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**
1. Join any multiplayer server
2. Build any ride
3. Build another ride.

**Screenshots / Video:**

![d](https://user-images.githubusercontent.com/10726524/74600990-2e6acd80-50dc-11ea-9a0b-c75d6332d93a.gif)

**Comment by Broxzier** [comment]
This must be a very recent regression; just over a week ago it was working fine. I'll try to find the offending commit.
