### ISSUE TITLE
Corrupted Banner/Entrance text rendering with OpenGL.

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#10716]
In OpenGL the banner text is offset randomly or even randomly rotated, this only happens with OpenGL and multithreading turned off. With multithreading enabled the issue is even worse.

![2020-02-16_14-18-10](https://user-images.githubusercontent.com/5415177/74605299-2b191700-50c7-11ea-8e38-cdf4698a3481.gif)

**Comment by IntelOrca** [comment]
The banner drawing code definitely needs more attention. I expect it is too easy for the number of banner drawing structs to run out on a single frame and not thread safe.

**Comment by ZehMatt** [comment]
They have a mutex around them but I think the multithreading part just increases the odds of the actual issue triggering. When multithreading is off it flickers less but the rotating text doesn't quite go where it should be.

**Comment by Umdlye** [comment]
I'm looking at a really crowded park right now and experiencing this issue with all drawing engines, FWIW. Not sure if that changes anything.

**Comment by Richard-L** [comment]
Experienced the problem too yesterday for the first time on…

> OpenRCT2, v0.2.4-652-gf7151317b (f715131 on develop) provided by GitHub
> Windows (x86-64)

…with this park https://www.nedesigns.com/park/1294/virginia-key-resort-casino/

Problem is not apparent:
-Software Rendering / Multithreading = off
-Software Rendering (hardware display) / Multithreading = off

Problem is somewhat apparent:
-OpenGL / Multithreading = off

Problem is acutely apparent in all other combinations when Multithreading is turned on, even when the game is paused.

Vanilla RCT2:
![image](https://user-images.githubusercontent.com/4934209/76029026-02e93f00-5f34-11ea-80af-edfa53b49121.png)

OpenRCT2:
![image](https://user-images.githubusercontent.com/4934209/76029214-56f42380-5f34-11ea-94ae-2117e7f1540f.png)

In the direct overlay of these two images, you can also see a slight offset in the "N" and "D" of "NFL Scores" and "Dolphins" respectively.

**Comment by duncanspumpkin** [comment]
> They have a mutex around them but I think the multithreading part just increases the odds of the actual issue triggering. When multithreading is off it flickers less but the rotating text doesn't quite go where it should be.

The mutex isn't actually around the part that is being modified though. You would need to hold the mutex up until the banner has rendered. We are currently only holding it for initial setup. We then drop it so that any other thread can overwrite the data we readied.

**Comment by IntelOrca** [comment]
Only a limited number of banners can be drawn per frame I think. This is why giant screenshots have issues.

**Comment by duncanspumpkin** [comment]
Yeah as soon as you exhaust the 32 banners you start causing issues. Due to the way they work it's not at all easy to change. But maybe someone else knows better than me.

**Comment by IntelOrca** [comment]
Increase the limit for a start. 32 is tiny.

**Comment by duncanspumpkin** [comment]
Sadly can't do that easily as it's writing to a gfx sprite offset. Would need to find a large free section.

**Comment by janisozaur** [comment]
Can't do it in some side buffer?

**Comment by duncanspumpkin** [comment]
Would need to look at how the rendering works not sure how late we can leave it for updating the atlas's
