### ISSUE TITLE
Feature request: disasters

### ISSUE THREAD

**Issue by jessicajonesunitedkingdom** [OpenRCT2/OpenRCT2#10726]
I would like to request a feature: disasters. Comparable to simcity.
It could be turned on/off in settings (for each disaster).

* Earthquakes: random. It could destroy many rides at the same time. Much people will go home

* Tornadoes: random during thunderstorm weather.  It could destroy rides.

* Lightning strike: random during thunderstorm weather.  It could destroy rides.

* flood: random during heavy rain/thunderstorm weather. Tiles will convert to water randomly. If a ride has X tiles filled with water on which it was built, it's destroyed. It can also interrupt footpaths and queue lines with flooded tiles.

etc etc

Thanks for reading

**Comment by duncanspumpkin** [comment]
This doesn't really fit with the game at all. I don't think it would work.

**Comment by ocalhoun6** [comment]
It would have to be optional since it changes gameplay so much ... and I'm not really sure who would turn on such an option. I can't imagine there's many players who would _want_ the rides they create to randomly be destroyed from time to time.

**Comment by Umdlye** [comment]
I could see people enjoying stuff like lightning destroying things as a plug-in packed with custom scenarios.

**Comment by jessicajonesunitedkingdom** [comment]
Each disaster could be enabled or disabled. It adds a new challenge. 
It works in simcity so I don't see a reason why not in a park.
Now the game is too friendly because the weather just "shows up" but is more a graphical thing. There are not consequences of a thunderstorm for example. So the weather is not affecting the gameplay.
In real life this is not true and my feature could bring this to the gameplay to add an additional layer of realism.

Maybe there could also be introduced a warning system (also enabled/disabled) that gives warnings when the weather changes (e.g. lightning warning, flood warning, ...). 

Or even suggestions like: close the park temporarely during the thunderstorm (and people will go home during a thunderstorm, and return when the weather changes). 

Maybe: the warning system could give warnings to close certain rides during too dangerous weather. Rollercoasters during lightning of a thunderstorm, for example, could be closed.

Just to have fun :)

**Comment by AaronVanGeffen** [comment]
Personally, I don't think this should be a core feature of the game. As has been mentioned, it would change the balance of the game quite a bit. A plugin system is in the works, however. Perhaps you could convince somebody to write it a plugin for it, eventually.

**Comment by ZehMatt** [comment]
As the others mentioned it drifts too far from the game. This could be a good thing for the plugin system once that is completed.

**Comment by thenamelessone1** [comment]
What can change the nature of a man? This feature!
