### ISSUE TITLE
Android: version string missing

### ISSUE THREAD

**Issue by jessicajonesunitedkingdom** [OpenRCT2/OpenRCT2#10731]
**OS:** android 7.1
**Version:**  0.2.4
**Commit/Build:** 0c4623a

Hi

I test a lot of android versions but for some reason the version string is not written at the bottom left corner of the screen during the opening sequence. While in windows it's there.

Can a developer add the version string (currently 0c4623a) please in android?
There is only written: 

OpenRCT2, v0.2.4
Android (AArch64)

There is no way to see what version I have when I need to report bugs in android, unless I keep my apk file and read the version of the file name.

**Comment by AaronVanGeffen** [comment]
This is a duplicate of #6770. Yes, that's an old issue, but we have only recently been able to resume pushing Android builds. Please search before submitting a new issue, though.

**Comment by ZehMatt** [comment]
Given that you have opened quite a few duplicate issues please use the search to see if such report already exists.

**Comment by jessicajonesunitedkingdom** [comment]
you could fixit instead of closing it ...

**Comment by ZehMatt** [comment]
Its being closed because the issue is already known, if we have the means and time to fix it we will, meanwhile please try to avoid duplicate reports.

**Comment by jessicajonesunitedkingdom** [comment]
my apologies
