### ISSUE TITLE
help: default config.ini in android

### ISSUE THREAD

**Issue by jessicajonesunitedkingdom** [OpenRCT2/OpenRCT2#10734]
I accidently edited config.ini wrong and deleted some lines and do not know what default value was.

Of course the game crashes now at start up.

My question: if i completely delete config.ini, will openrct2 write a new default one in user data folder in android?

Same question for windows version.

thx

**Comment by janisozaur** [comment]
Yes, a new one with defaults will be created

**Comment by thenamelessone1** [comment]
Updated my journal!
