### ISSUE TITLE
Android: weather

### ISSUE THREAD

**Issue by thenamelessone1** [OpenRCT2/OpenRCT2#10749]
**OS:** android 7.1
**Version:** . 0.2.4
**Commit/Build:** 1272c0c

There is NO difference between sunny, partially cloudy and cloudy weather type in android when enabled using cheats window.

Is this normal? I remember rct2 having a slightly darker park map when weather was cloudy vs. sunny.
In openrct2 seems to be no difference, at least on android.

I still need to test in windows

Any thoughts?

**Comment by brettpenzer123** [comment]
The weather (Sunny, partially cloudy and cloudy) have no darkening effects

**Comment by Broxzier** [comment]
Only thunderstorms have a visual difference in the world. The other weather types affect the behaviour of the guests.
