### ISSUE TITLE
Faulty Mute Button State on Launch

### ISSUE THREAD

**Issue by Richard-L** [OpenRCT2/OpenRCT2#10752]
![image](https://user-images.githubusercontent.com/4934209/74975847-022ab600-5428-11ea-94bc-dcbf894da29b.png)

Quick small find:

Enable the mute button and activate it (game is muted):

![image](https://user-images.githubusercontent.com/4934209/74944435-55841080-53f6-11ea-9f23-00eef9dba36f.png)

Close the game and reopen. Sound is still muted, with the button unavailable on the title screen.

Open any park to see the mute button shows the game as "unmuted" incorrectly:

![image](https://user-images.githubusercontent.com/4934209/74944507-72204880-53f6-11ea-8497-c374c918f9e6.png)

Clicking the button will re-enable sound, and the button stays the same.

It should remember the correct "muted" state and show the button accordingly.

**Comment by AaronVanGeffen** [comment]
Please use the issue template. What version are you using and what platform are you?

**Comment by Richard-L** [comment]
Always latest develop via launcher.

Is there a console command copying your version to the clipboard to paste in here?

**Comment by janisozaur** [comment]
`./openrct2 --version`, just like about any other piece of software.

**Comment by Richard-L** [comment]
![image](https://user-images.githubusercontent.com/4934209/74975847-022ab600-5428-11ea-94bc-dcbf894da29b.png)

**Comment by thenamelessone1** [comment]
fuck you
