### ISSUE TITLE
question: umbrella colors

### ISSUE THREAD

**Issue by thenamelessone1** [OpenRCT2/OpenRCT2#10750]
Can somebody tell me all possible umbrella colors?
I saw red/white, blue/white, oranje/white and completely white.

I remember rct2 had only red/white. So ope'rct2 added more colors.

I saw 2 people have complete white umbrella.
I was wondering if this could be a bug and therefore I ask all colors.

Thx

**Comment by Superjustinbros** [comment]
If an umbrella is completely white, that means it's a "white" umbrella.
RCT(2)'s umbrellas only change three of the six segments of the umbrella, and all umbrella patters are white/(color).

**Comment by Gymnasiast** [comment]
> I remember rct2 had only red/white. So ope'rct2 added more colors.

Not true. Even RCT1 allows you to set the striped part to *any* colour that RCT supports, using the exact same colourpicker. If you had just opened the window of anything that sells umbrellas, you would have seen that.

At least put a bit of effort in before you ask stuff. You have been bombarding us with e-mails, issues and other messages. We don't have the time or energy to answer all of them, especially if it's easy to find the answer if you try.

**Comment by thenamelessone1** [comment]
If you write less bugs, I need to make less issues...

**Comment by thenamelessone1** [comment]
I mark this comment as "disruptive content" too: 

At least put a bit of effort in before you ask stuff. You have been bombarding us with e-mails, issues and other messages. We don't have the time or energy to answer all of them, especially if it's easy to find the answer if you try.

Updated my journal!

**Comment by thenamelessone1** [comment]
disruptive content:

At least put a bit of effort in before you ask stuff. You have been bombarding us with e-mails, issues and other messages. We don't have the time or energy to answer all of them, especially if it's easy to find the answer if you try.

**Comment by thenamelessone1** [comment]
This is off topic too:

At least put a bit of effort in before you ask stuff. You have been bombarding us with e-mails, issues and other messages. We don't have the time or energy to answer all of them, especially if it's easy to find the answer if you try.
