### ISSUE TITLE
Android: Rides default name is (Undefined String)

### ISSUE THREAD

**Issue by ghost** [OpenRCT2/OpenRCT2#10810]
hello

When choosing a new game in android, all attractions have no name. There is written undefined string and () around.

Am i missing a file??

**Comment by duncanspumpkin** [comment]
This has been reported before but the issue has been erased and it sounds like issues loading the language files.

Hang tight and eventually someone will investigate it.

**Comment by Gymnasiast** [comment]
Seems like #11436 is the same problem as this, but that one has a screenshot and was created by someone still present on Github. Closing this one instead.
