### ISSUE TITLE
Can place more than two peep spawns

### ISSUE THREAD

**Issue by Umdlye** [OpenRCT2/OpenRCT2#10822]
**OS:** Windows 10 (x64)
**Version:** 0.2.4-587-g86a79e742
**Commit/Build:** 86a79e7

I can place more than two peep spawns, they are all functional. Saving and reloading only keeps the first two as expected. When you place more than 8, the first one will disappear.

**Steps to reproduce:**
1. Place two peep spawns (in sandbox mode or scenario editor)
2. Place some more

![2020-02-22_23-29-57](https://user-images.githubusercontent.com/11657101/75100293-0b548800-55cc-11ea-8f90-91227f89d33f.gif)

**Comment by kylegarza21** [comment]
When attempting to reproduce this bug rather than the 'oldest' peep spawn being removed, the game crashed. I'll investigate.
