### ISSUE TITLE
RCT1 Theme Icons/Tabs

### ISSUE THREAD

**Issue by sta5is** [OpenRCT2/OpenRCT2#10827]
OS: Windows 10
Version: 0.2.4
Commit/Build: e2e7079

Can there be an option to replace the view and research funding tabs to use the ones used in RCT1 (see below)? I think it will be a nice addition to complete the look to have the RCT1 interface.

![view](https://user-images.githubusercontent.com/26368692/75103420-42687080-55af-11ea-905b-e65522a9992b.gif)

Instances where this icon appears:
Guest/Staff window
Ride/Stall window
Park window

![research_funding](https://user-images.githubusercontent.com/26368692/75103423-485e5180-55af-11ea-9506-511e6080107a.gif)

Instances where this icon appears:
Research Window
Finance Window (RCT2)

Perhaps the option can be featured here:
![rct1 icon option](https://user-images.githubusercontent.com/26368692/75103412-3381be00-55af-11ea-8050-fe19434c82b2.PNG)

**Comment by Gymnasiast** [comment]
I think this is too much effort for too little gain. There is also the issue of needing RCT1 sprites, which not everyone has loaded.

**Comment by IntelOrca** [comment]
Unless we do same thing as the traffic lights and have the sprites in g2.dat.

**Comment by Gymnasiast** [comment]
Yes, but then the rest still stands. Having the camera icon instead of the guest/ride/park icon does not add anything in terms of UX, AFAIC. And the "research funding" icon is too similar to what we currently have.
