### ISSUE TITLE
Multiplayer is incorrectly reporting which player built what

### ISSUE THREAD

**Issue by CorySanin** [OpenRCT2/OpenRCT2#10844]
**OS:** Client is Windows 10, server is Ubuntu 18.04.4 LTS, running latest openrct2-cli:develop docker container
**Version:** Develop
**Commit/Build:** 52d5995

With two users of the same group connected, OpenRCT2 will report the wrong player performing actions.

I think it can be most easily reproduced with prebuilt layouts.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**
1. Two users of the same user group connect to a multiplayer server
2. Build prebuilt rides and observe which player is doing what according to the server.

**Screenshots / Video:**
[video evidence](https://streamable.com/vrw1w) (Demo is the only player actually building anything in the video. But it says I'm doing it.)

**Save game:**
I don't believe a save is necessary, but I'll provide it later if it is.

**Comment by telk5093** [comment]
I think this is duplicated of mine, #10587

**Comment by CorySanin** [comment]
I think you're right. I'll close.
