### ISSUE TITLE
Finance charts horizontal lines

### ISSUE THREAD

**Issue by pRizz** [OpenRCT2/OpenRCT2#10858]
Feature request for adding horizontal lines to charts.

**Screenshots / Video:**
See PR https://github.com/OpenRCT2/OpenRCT2/pull/10851

**Comment by AaronVanGeffen** [comment]
There was no need to open an issue while there was already an active PR, but the thought is appreciated. :wink:

**Comment by pRizz** [comment]
Ok, I thought it was needed as a reference for the Changelog

**Comment by Gymnasiast** [comment]
If there was already an issue when the PR was created, we use that number. If there wasn't one already, we just take the number of the PR itself.
