### ISSUE TITLE
Scenario description shows up incorrectly

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#1086]
![scr69](https://cloud.githubusercontent.com/assets/1478678/7671339/84aa03ec-fccb-11e4-9cc7-85e70cdacc99.png)

Only seems to happen with Mythological - Animatronic film set, and then only the Dutch translation. Not sure whether it is in vanilla RCT2, since I only have the US English version of that.

**Comment by RollingStar** [comment]
For anyone trying to solve this, I don't see this text in the OpenRCT2/data/language/dutch.txt file. Maybe I'm missing it.

**Comment by Gymnasiast** [comment]
It's in a STEXxy.DAT file, like all original scenario descriptions. language.txt files only contain GUI strings.

**Comment by Gymnasiast** [comment]
A contributor checked the vanilla Dutch version and confirmed that it shows up in blue there as well. So it's not introduced by OpenRCT2.

Checking the STEX70.DAT with a hex editor reveals that it contains a 0x96 character, which might be a formatting code. In that case it isn't a bug in RCT2 or OpenRCT2 but a fault in the .DAT files, which we can't edit until we switch to our own format (because it would change the .DAT checksum).

**Comment by Gymnasiast** [comment]
Will be fixed when Localisation gets merged.
