### ISSUE TITLE
Add the ability to load loose (unpacked) sound files

### ISSUE THREAD

**Issue by Generalcamo** [OpenRCT2/OpenRCT2#10860]
Currently, sound files must be packed in CSS1.DAT. This is inconvienient for three reasons:

- It doesn't allow for easy modification and testing of sounds for the planned OpenSounds project
- No new sound files can be added as resources in the game
- The game cannot load sound files from RCT Classic, even if Ogg Vorbis support were added (see also #6570)

Support for _playing_ a loose sound is already supported, and can be seen [here](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2-ui/audio/FileAudioSource.cpp). This issue specifically deals with being able to have the engine load unpacked sounds in addition or instead of CSS1.DAT (support exists for loading two additional music files, but those are hardcoded and not suitable for this).

**Comment by Gymnasiast** [comment]
For ease of import, I think that we should use the [names that RCTC uses](https://github.com/OpenRCT2/OpenRCT2/wiki/CSS1.DAT#rctc-file-equivalents).

**Comment by Gymnasiast** [comment]
This has now been implemented. You can load both additional music and sound files, and OGG support has been added.
