### ISSUE TITLE
Crash upon opening .PARK (from resaved .SV6)

### ISSUE THREAD

**Issue by Richard-L** [OpenRCT2/OpenRCT2#10872]
Win7-x64.

Opened this park … https://www.nedesigns.com/park/42/el-encierro/

…with:
> OpenRCT2, v0.2.4-677-gb63fb9634 (b63fb96 on new-save-format) provided by GitHub
> Windows (x86-64)

…and saved it to a new file .PARK.

Close OpenRCT2 and reopen. Loading the .PARK file crashes the game for me in 9 out of 10 cases:

![image](https://user-images.githubusercontent.com/4934209/75932256-45991180-5e77-11ea-97f5-868df262608e.png)

More examples:
- https://www.nedesigns.com/park/751/horrific-hazard-aftermath/
- https://www.nedesigns.com/park/2401/h2h6-r3-hurricanes-avatar/
- https://www.nedesigns.com/park/2089/nedc-shock-2-49/
- https://www.nedesigns.com/park/1452/sentaya/
- https://www.nedesigns.com/park/158/busch-gardens-sydney/
- https://www.nedesigns.com/park/263/epica/
- https://www.nedesigns.com/park/950/outpost-prehistorica/

Curiously, in the 1 out of 10th case, the .PARK seems to open _if the respective SV6 was opened first_. Very hard to reproduce, and quite puzzling.

Another curious case: https://www.nedesigns.com/park/374/tir-na-nog/
^this one brings you back to the OpenRCT2 main title screen. Perhaps due to the filename?

Could any of this be related to: https://github.com/OpenRCT2/OpenRCT2/issues/8492 ?

I hope this is helpful, and thanks for looking into this.

**Comment by AaronVanGeffen** [comment]
Loads just fine for me on 425b05d011c26896ed99b6bd92214eb9af7a5fdd (current develop) on Linux. Can you reproduce this on develop, or is it specific to the 'new save format' branch?

**Comment by Gymnasiast** [comment]
`develop` does not even support .PARK files, so this is definitely specific to new-save-format.
