### ISSUE TITLE
Hyper-Twister displays "too high" instead of "too low"

### ISSUE THREAD

**Issue by Hummel95** [OpenRCT2/OpenRCT2#10871]
Windows 10, 64 Bit
v0.2.4
425b05d

I am constructing a custom Hyper-Twister roller coaster on the infernal views campaign map. When trying to build the track shown in the screenshot I receive the message "Can't construct this here... Too high !" though "Too low !" should be displayed.

![image](https://user-images.githubusercontent.com/15891478/75930055-2f279180-5e48-11ea-8d17-bafe6f972eb7.png)

- [?] Reproducible in RCT2 (vanilla)?
- [No] Specific to multiplayer?

**Save game:**
[Infernal Views.zip](https://github.com/OpenRCT2/OpenRCT2/files/4290003/Infernal.Views.zip)

**Comment by Hummel95** [comment]
I was able to reproduce the issue in the track designer with different elements:

Last element:
![image](https://user-images.githubusercontent.com/15891478/75983528-173f2480-5ebf-11ea-8c6c-3aca469164f0.png)


![image](https://user-images.githubusercontent.com/15891478/75983379-d7783d00-5ebe-11ea-8367-89d2c51cd310.png)

![image](https://user-images.githubusercontent.com/15891478/75983441-f2e34800-5ebe-11ea-998a-c75a8cb30493.png)

![image](https://user-images.githubusercontent.com/15891478/75983458-f7a7fc00-5ebe-11ea-826c-e1f76d9d23fd.png)

![image](https://user-images.githubusercontent.com/15891478/75983411-e8c14980-5ebe-11ea-953a-5c563ba00710.png)


Last element:
![image](https://user-images.githubusercontent.com/15891478/75983564-258d4080-5ebf-11ea-9a8a-17f6e7861deb.png)


![image](https://user-images.githubusercontent.com/15891478/75983485-05f61800-5ebf-11ea-9298-2fc3e9fc4a31.png)

![image](https://user-images.githubusercontent.com/15891478/75983498-0ee6e980-5ebf-11ea-8325-c34c5a1805c3.png)

Last element:
![image](https://user-images.githubusercontent.com/15891478/75983668-4d7ca400-5ebf-11ea-93ef-d4657cb0d8e1.png)

![image](https://user-images.githubusercontent.com/15891478/75983641-40f84b80-5ebf-11ea-8a2b-8696e6338dc5.png)

![image](https://user-images.githubusercontent.com/15891478/75983653-4786c300-5ebf-11ea-8b28-c48eea82b128.png)

![image](https://user-images.githubusercontent.com/15891478/75983686-58cfcf80-5ebf-11ea-8070-0420c0323e78.png)

![image](https://user-images.githubusercontent.com/15891478/75983702-5ff6dd80-5ebf-11ea-8555-1b763babba59.png)


Hope that helps!

**Comment by Gymnasiast** [comment]
Most likely an underflow.
