### ISSUE TITLE
Position of money animation is incorrect

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#10899]
**OS:** Windows 10
**Version:** 0.2.4
**Commit/Build:** bc3d87e

It seems that the money animation is positioned too upward.

**Screenshots / Video:**
![1](https://user-images.githubusercontent.com/10726524/76163666-805abc80-618b-11ea-8ccc-59dddd0909af.gif)

**Comment by tupaschoal** [comment]
Probably one of ours, @Gymnasiast ?

**Comment by Gymnasiast** [comment]
Afraid so...

**Comment by Gymnasiast** [comment]
Bisecting points to be13c1fc87eaee50c0425a843af6b89698cb8f59 as the first bad commit.
