### ISSUE TITLE
Graphic sprites are not animated

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#10894]
**OS:** Windows 10
**Version:** 0.2.4
**Commit/Build:** d64b73c

Graphic sprites are not animated or seems not to be updated.

**Steps to reproduce:**
1. Build any object which animates, such as a foundation.
2. Watch it.

**Screenshots / Video:**
![2](https://user-images.githubusercontent.com/10726524/76162140-ee988280-617d-11ea-8e73-988b7f431c7c.gif)
See that the Photo-section is always lighted-on, and the foundation does not animate occasionally

**Comment by AaronVanGeffen** [comment]
Could you help perhaps narrow this down to a certain commit?

**Comment by telk5093** [comment]
I think it will be hard since it has been a long time this issue occured unless there is a place where I can download old binaries.

**Comment by AaronVanGeffen** [comment]
Does it occur in [old releases](https://github.com/OpenRCT2/OpenRCT2/releases) as well? And is this an issue with just this save file, or any new scenario? (The number of allowed animations in-game is limited.)

**Comment by telk5093** [comment]
I've tested by OpenRCT2 default title sequence.

**0.2.4-release:**
![0 2 4](https://user-images.githubusercontent.com/10726524/76162432-1b01ce00-6181-11ea-8911-231628db1328.gif)

**0.2.3-release:**
![0 2 3](https://user-images.githubusercontent.com/10726524/76162437-22c17280-6181-11ea-9f7b-79b5ac2e4669.gif)


I have no idea that this issue is occured at just this save file.
But in my guess, this issue is related with the save file, since if I load a save file at 0.2.1 which is saved at 0.2.4 develop, this issue also occured.

**Comment by jensj12** [comment]
This is what my rusty memory tells me:

> This was already a problem in the second group park. Tracing back the dates leads to release 0.0.3 or 0.0.4. Nothing really you can do as player, the map animations list is simply corrupt or full.

**Comment by AaronVanGeffen** [comment]
I believe this was fixed by #21136. Could you confirm?
