### ISSUE TITLE
File browser 'date' column is too narrow

### ISSUE THREAD

**Issue by Umdlye** [OpenRCT2/OpenRCT2#10928]
**OS:** Windows 10
**Version:** 0.2.4
**Commit/Build:** 9b5e814

It doesn't fit most 2020 dates.
![openrct2_2020-03-14_14-14-08](https://user-images.githubusercontent.com/11657101/76682754-e5d10200-65fe-11ea-8ede-abfee3409238.png)

**Comment by AaronVanGeffen** [comment]
The width of this column is font-dependent, and so I initially reasoned, at the time, that taking the width of the widest date I could think of would be most appropriate. However, I made a mistake by taking October (10) as the 'widest' month, as indeed February (02) or March (03) are both wider. January (01) doesn't have this problem.

So, 2020 was a red herring. This comment illustrates the fix thusly:

```diff
-    // Generate a time object for a relatively wide time: 2000-10-20 00:00:00
+    // Generate a time object for a relatively wide time: 2000-02-20 00:00:00
```
