### ISSUE TITLE
Entrance/exit placement selection not updating properly

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/OpenRCT2#10933]
**OS:** Linux
**Version:** 0.2.4+
**Commit/Build:** 9b5e8140

The selection grid doesn't appear to be properly updated during entrance/exit placement, but this seems limited to certain rides, somehow.

Possibly linked to #10932.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Build a Ferris Wheel
2. Try placing the entrance
3. Notice how the selection doesn't appear in the right place

**Screenshots / Video:**
![Forest Frontiers 2020-03-15 00-12-37](https://user-images.githubusercontent.com/604665/76692087-d4651580-6651-11ea-8617-46f6d29d3692.png)
![Forest Frontiers 2020-03-15 00-12-39](https://user-images.githubusercontent.com/604665/76692088-d4fdac00-6651-11ea-9b05-09860219f361.png)
![Forest Frontiers 2020-03-15 00-12-41](https://user-images.githubusercontent.com/604665/76692089-d4fdac00-6651-11ea-88c0-44c0f792dcad.png)

**Comment by Broxzier** [comment]
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/2272?

**Comment by AaronVanGeffen** [comment]
Oh wow! I really thought this was a recent regression. Closing this one.
