### ISSUE TITLE
Missing toolbar memory with "Toolbar Visibility" toggle

### ISSUE THREAD

**Issue by Richard-L** [OpenRCT2/OpenRCT2#10940]
**OS:** Win7-x64
**Version:** v0.2.4-703-g18ebe73df (18ebe73 on develop) / Windows (x86-64)                                                         

When using "T" to toggle toolbar visibility on and off, OpenRCT2 _also_ closes all open windows. I think this is wrong. It should simply hide them. Another "T" press should bring everything back as it were: same windows, same sizes, same positions.

Slightly in reference to here:

> I think the original description for this issue was limited. When I originally discussed this with @IntelOrca the show/hide ui should really hide any open windows, and prevent the drawing of any new windows being drawn when the user presses the shortcut for that window (but it should still know it should open them, **so when the ui is shown again, those windows are there**)
_Originally posted by @mzmiric5 in https://github.com/OpenRCT2/OpenRCT2/issues/1402#issuecomment-115737640_

EDIT: this only seems to occur for select windows such as the scenery selector. Windows of staff people stay both in place and visible during the "T" toggle.

**Comment by tupaschoal** [comment]
The shortcut is for hiding toolbar and status bars, so I don't think it should hide/restore anything else, other than these two.

That being said, it doesn't closes most windows, but does close:
- "Clear Scenery"
- "Land"
- "Water"
- "Fences and Walls"

**Comment by Richard-L** [comment]
I see what you're saying. I do feel as if it would make sense for this to be a toggle to show/hide everything, as to my understanding the intention of this feature is to have a clear screen with nothing but RCT shown.

**Comment by duncanspumpkin** [comment]
The way this button works is that it closes the top toolbar window. There are other windows that are tied to the top toolbar due to the way the tools work (hence why land, water, ... close). We would need to completely rework this feature to not close the windows to change this.

**Comment by AaronVanGeffen** [comment]
The tools being cancelled will be fixed by #22411.
