### ISSUE TITLE
Ghost entrances appearing when attempting to place park entrances in sandbox mode

### ISSUE THREAD

**Issue by savoyt** [OpenRCT2/OpenRCT2#10951]
**OS:** Windows 10
**Version:** 0.2.4
**Commit/Build:** v0.2.4-713-gfd91c41a7(fd91c41 on develop) provided by GitHub
Windows (x86-64

Upon deleting and attempting to re-place a park entrance during normal gameplay (not scenario editor) using Sandbox Mode, there was no ghost preview when placing the entrance, and upon clicking an unusable ghost entrance was instead created floating above the ground. I believe I had zero clearances turned on when I did this. I could delete the ghost entrances using the tile inspector, but further entrances placed still only created ghosts. I attempted to recreate this on another map by fiddling with cheat settings and zero clearances but could not. I have attached a screenshot of the ghost entrances (I clicked a whole bunch of times because I'm stupid and didn't realize anything was happening) and the save file (changed to .txt).

**Screenshots / Video:**
![Icicle Worlds 2020-03-17 01-05-59](https://user-images.githubusercontent.com/62277397/76828413-e203d200-67ee-11ea-9467-f45c1e43bba1.png)

**Save game:**

[ghost_entrances.txt](https://github.com/OpenRCT2/OpenRCT2/files/4341799/ghost_entrances.txt)

**Comment by savoyt** [comment]
Okay, so I just downloaded the save file I uploaded (which I verified was producing the bug before I uploaded it) and now it is working as intended. Huh.

**Comment by Gymnasiast** [comment]
It isn't pointless. But if you'd be able to come with a set of steps to reproduce the problem, that would help us tremendously.

**Comment by savoyt** [comment]
Ok, I went back in and played around with the files I had. This save file is placing ghosts when I just checked it, although it appears to have placed a non-ghost entrance up with the ghosts (I have zero clearances turned on), but when I exited and re-loaded the save I ended up with two non-ghost entrances, still floating way up there. ghost_entrances2 s the file that I loaded that created the ghosts,  nonghost_entrances s the re-loaded file that has non ghost entrances. 

EDIT: Nevermind, the ghosts seem to be flickering in and out of existence in the second file, sometimes when you zoom out they're there, sometimes they aren't. 

ghost entrances:
![Icicle Worlds 2020-03-17 13-05-32](https://user-images.githubusercontent.com/62277397/76887708-a6015900-6850-11ea-8ecb-49dfeb8dffdd.png)

[ghost_entrances2.txt](https://github.com/OpenRCT2/OpenRCT2/files/4345049/ghost_entrances2.txt)


nonghost entrances:

![Icicle Worlds 2020-03-17 13-06-29](https://user-images.githubusercontent.com/62277397/76887781-c16c6400-6850-11ea-8129-9abba0e707b5.png)
[nonghost_entrances.txt](https://github.com/OpenRCT2/OpenRCT2/files/4345052/nonghost_entrances.txt)

**Comment by savoyt** [comment]
Okay, this is interesting. So I just discovered that I have two versions of Open installed, the current one (dcdc4f8) and an older install I forgot about and don't use (v.0.2.1-1020 (298c9f5). The entrances work as intended on the older version but NOT the current one. I must have opened the files in the older version by mistake last night, as it's currently working as expected on v0.2.1 but not v0.2.4

**Comment by duncanspumpkin** [comment]
When you load a save with ghosts we strip them out so thats why you never see them on loaded games.

**Comment by Gymnasiast** [comment]
@duncanspumpkin Once the terrain gets high enough, attempting to place an entrance will cause all sorts of weird problem. It doesn't happen with terrain at the default height in the scenario editor, but try it on a map with terrain and it's easy to reproduce.
