### ISSUE TITLE
Copy/Paste-ability of Input Strings

### ISSUE THREAD

**Issue by Richard-L** [OpenRCT2/OpenRCT2#10955]
OpenRCT2, v0.2.4-719-gdcdc4f829 (dcdc4f8 on develop) provided by GitHub
Windows (x86-64)

![Geauga Knockoff 2020-03-17 19-25-04](https://user-images.githubusercontent.com/4934209/76889228-86d0ee80-6885-11ea-86d0-579012b30fa7.png)

^would it mean much trouble to allow highlighting and copy/pasting functionality with CTRL+C/X/V?

Thank you.

**Comment by AaronVanGeffen** [comment]
Thank you, this is a good feature request. Unfortunately, it isn't trivial to add -- as of yet, text selection hasn't been implemented at all.

**Comment by IntelOrca** [comment]
Just to clarify, we already have paste (CTRL+V) support but no selection support which is needed for cut, delete, copy, and delete-and-paste.

**Comment by janisozaur** [comment]
We could try having ^C copy entire current buffer, before text selection is implemented

**Comment by daandeheij** [comment]
I'm working on a simple implementation now, as suggested by @janisozaur

**Comment by duncanspumpkin** [comment]
Implemented in #11013.
