### ISSUE TITLE
Use already created and saved coaster blue prints in MP

### ISSUE THREAD

**Issue by dkoether** [OpenRCT2/OpenRCT2#10959]
Hello everyone,

I'm curious why it is not possible to use already created and saved blue prints of roller coasters in the MP. Even the default blue prints of RCT 2 vanilla are not given. It will save a lot of time and its quite cool to present own creations and favorites to friends in MP.

Is this Feature already planned or are there any technical problems?

Thanks in advance and keep up the good work!

**Comment by AaronVanGeffen** [comment]
Thanks! If you use our develop builds instead of the 0.2.4 'release' version, you should have exactly this feature available to you already. :)

**Comment by dkoether** [comment]
Awesome! I will give it a try. Is there already a planned date for the next release?

Thank you!

**Comment by AaronVanGeffen** [comment]
We have no date set, but you can have a look at [the milestone](https://github.com/OpenRCT2/OpenRCT2/milestone/16) to see what needs to be addressed before we can do the release.

**Comment by dkoether** [comment]
Thank you :)
