### ISSUE TITLE
Problem connecting to Server

### ISSUE THREAD

**Issue by Justus1805** [OpenRCT2/OpenRCT2#10972]
**OS:** Windows 10
**Version:** 0.2.4
**Commit/Build:**a56a3fb

I created a server on a Ubuntun 18.04.
I'Ve installed the last Nightly, but cannot connect to the server because of wrong version.
I've installed different versions on my pc, but it doesn't work.

- [x ] Reproducible in RCT2 (vanilla)?

Connect to the server failed. Wrong Version
- [x ] Specific to multiplayer?

Thank you! :)

**Comment by AaronVanGeffen** [comment]
The nightly 'develop' version of OpenRCT2 is not compatible with the last 0.2.4 release. You have to either use the 0.2.4 release version on both Ubuntu and Windows, or use the develop version on both platforms.
