### ISSUE TITLE
Guest Count Intent Not Listened To

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#10993]
The guest count is meant to be redrawn whenever a guest leaves. It looks like when the intent system was implemented this was incorrectly handled. 

Within windowmanager.cpp the intent `INTENT_ACTION_UPDATE_GUEST_COUNT` needs to be handled by invalidating the bottom toolbar (gToolbarDirtyFlags), the guest list and the park window.

**Comment by daandeheij** [comment]
I'm currently looking into this
