### ISSUE TITLE
Enhancement request: return to normal speed when player wins scenario

### ISSUE THREAD

**Issue by Umdlye** [OpenRCT2/OpenRCT2#10997]
Having your peeps celebrate when you win a scenario is a pretty memorable feature, but when you change the game speed to get to the goal faster, the celebration goes by pretty quickly as well if you don't return to normal speed in time. I think it would be nice if the game speed automatically returned to normal when you win a scenario.

**Comment by Gymnasiast** [comment]
Has been implemented in #10998.
