### ISSUE TITLE
Company value overflows

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#11005]
**OS:** Windows 10
**Version:** 0.2.4
**Commit/Build:** 2a94632

I think it is not solvable until we have new save file format, but I'd like to issue here to notice to you.

**Steps to reproduce:**
1. Set money as ``$214,748,364.70``, which indicates ``INT_MAX``
2. See the finance window

**Screenshots / Video:**
![TELK PARK 2020-03-22 20-16-11](https://user-images.githubusercontent.com/10726524/77327765-00be1780-6d5f-11ea-8f76-ce70b1a0896f.png)

**Comment by Gymnasiast** [comment]
We could make it a 64-bit integer. That can be done right away, even if SV6 cannot represent its entire value.

**Comment by duncanspumpkin** [comment]
Is it actually possible to get to this value without cheating? I thought there was a cap preventing the value overflowing on an addition.

**Comment by Umdlye** [comment]
![2020-03-23_22-00-19](https://user-images.githubusercontent.com/11657101/77362789-d87bec00-6d51-11ea-93ac-6a3a4d946378.gif)

It seems to cap properly with little additions (shop sales) but when I build and open a ride it overflows.

**Comment by IntelOrca** [comment]
> Do note that it will always overflow at some point, though.

Not if we cap it, I think we have done that with park rating?

**Comment by thversfelt** [comment]
By casting the company value to a 64-bit integer, it can be checked for an overflow and then clamped if it is the case. I implemented this in #11012
