### ISSUE TITLE
Rides list shows both red and green light activated

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#11002]
**OS:** Ubuntu 20.04
**Version:** 0.2.4+
**Commit/Build:** https://github.com/OpenRCT2/OpenRCT2/commit/2a94632b32564426ebbddff318f3055718266d71

![afbeelding](https://user-images.githubusercontent.com/1478678/77311675-db022580-6d00-11ea-8eb4-9098aa63ec64.png)

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Build some food stalls.
2. Observe that the other categories now show the red and green light simultaneously.

**Comment by Broxzier** [comment]
For anyone unfamiliar with the lights (that includes me, I use the default flags), what is expected here? Both lights off, I assume?

**Comment by Umdlye** [comment]
Yes. When all rides in the tab are open, the green light is on. When they're all closed, the red light is on. When they're mixed open/closed, both lights are off. 

When none of the tabs have rides in them, all the lights are off as expected but when one or more tabs has a ride, the empty tabs will have both lights on (bug).
