### ISSUE TITLE
Third color on objects becoming black when saving

### ISSUE THREAD

**Issue by EtienneGL** [OpenRCT2/OpenRCT2#11027]
**OS:** Windows 7
**Version:** 0.2.5
**Commit/Build:** 4f6e77e and 302fe1c
Applies both on release and develop.

When we place a scenery object with a third color different from black, then save the game, then open the save, it becomes black.

- Reproducible in RCT2 (vanilla)? **No**
- Specific to multiplayer? **No**

**Steps to reproduce:**
1. Place a scenery object with a third color.
2. Save the game.
3. Open the save.

**Screenshots / Video:**
Before:
![image](https://user-images.githubusercontent.com/33940430/77506198-9b8c2400-6e3b-11ea-8869-e1af54c75cff.png)
After:
![image](https://user-images.githubusercontent.com/33940430/77506231-b1014e00-6e3b-11ea-8529-ca93188bde85.png)

**Save game:**
[test color.zip](https://github.com/OpenRCT2/OpenRCT2/files/4379258/test.color.zip)

**Comment by deurklink** [comment]
To devs: do you think there maybe could be a new release version after fixing this? I can see this affect a ton of savegames in the future..

**Comment by ocalhoun6** [comment]
I just tried loading the save game provided on an older version of OpenRCT2, and the third colors are indeed black. It's being saved that way, not just a display issue or a loading issue. So, yeah -- it's going to affect a lot of saved games.

**Comment by sumati13** [comment]
Addition: Changing the third colour of an already placed/coloured object from a save, and then saving, makes the save file ignore the change and revert to the old colour. 

It only becomes black when placing new ones.

**Comment by AaronVanGeffen** [comment]
This shows a real disadvantage of fewer people using the develop builds nowadays. I’m sorry this went unnoticed on our end. 

We should make a replay test for this to ensure it doesn’t happen again.

**Comment by Ziscor** [comment]
Addition: when changing colours on an already placed/re-coloured object from an old save file, and then saving, the save file ignores the change and the colour is reverted to what it was before.

It only goes black when placing new instances of the object.
