### ISSUE TITLE
Unable to build certain custom-build rollercoasters

### ISSUE THREAD

**Issue by Wulfke** [OpenRCT2/OpenRCT2#11028]
**OS:** Windows 10
**Version:** 0.2.4+
**Commit/Build:** 302fe1c

I'm unable to build certain custom-build rollercoasters. It seems limited to the Wooden Roller Coaster, Steel Twister and Vertical Drop Rollercoasters. 
I get no previews when trying to build these rides. When trying to build them I get error messages at random: either (1) no error message, (2) "can't construct this here no more stations allowed on this ride" (3) "can't construct this here... in the way" or (4) "can't construct this here".
This is irrespective of whether it has scenery or not, or turning scenery on or off when it does include some scenery.
Saving them again and replacing the original file does not work, neither does creating a new file.
It also seems quite random because it's not for all rides of these coaster types I create.

**Screenshots / Video:**
![no preview 1](https://user-images.githubusercontent.com/62643705/77523265-c7cc9280-6e85-11ea-8de0-4539d39b0a3e.JPG)
![no preview 2](https://user-images.githubusercontent.com/62643705/77523273-c9965600-6e85-11ea-9283-3dfb81db1d0c.JPG)

**Comment by AaronVanGeffen** [comment]
Could you add an example or two of such track designs? That should make it much easier for us to reproduce this.

**Comment by Wulfke** [comment]
> Could you add an example or two of such track designs? That should make it much easier for us to reproduce this.

How do I upload .td6 files?

**Comment by AaronVanGeffen** [comment]
A zip file will be accepted by GitHub. Thanks.

**Comment by Wulfke** [comment]
Here you go
[custom track issues.zip](https://github.com/OpenRCT2/OpenRCT2/files/4380400/custom.track.issues.zip)

**Comment by Gymnasiast** [comment]
The second one seems to run into the problem described here: https://github.com/OpenRCT2/OpenRCT2/issues/9472#issuecomment-509362491

**Comment by Gymnasiast** [comment]
It seems like they all have 4 stations and this is the same bug as #6123 and many others.

I have a fix here: https://github.com/OpenRCT2/OpenRCT2/pull/11031
