### ISSUE TITLE
"Quit to menu" and "Exit OpenRCT2" replaced by undefined or other strings

### ISSUE THREAD

**Issue by NoudL** [OpenRCT2/OpenRCT2#11032]
**OS:** Windows 10
**Version:** 0.2.5-14
**Commit/Build:** g766339d77 (766339d on develop)

When opening the "save menu" the text that should say "Quit to menu" and "Exit OpenRCT2" gets replaced by "(undefined string)" or other random text. 
Doesn't happen on the first map you open, but happens to every next map you open.

- [ no ] Reproducible in RCT2 (vanilla)?
- [ no ] Specific to multiplayer?

**Steps to reproduce:**
1.  Open a map
2.  Close said map
3.  Open another (or the same) map
4.  Click on the save menu in the top left corner.

**Screenshots / Video:**
[Screenshot 1](https://cdn.discordapp.com/attachments/689559763365003305/692363973932089454/unknown.png
)
[Screenshot 2](https://media.discordapp.net/attachments/689559763365003305/692364645645811802/unknown.png)

**Comment by Gymnasiast** [comment]
Which language is your game set to?

**Comment by NoudL** [comment]
English (UK)

**Comment by NoudL** [comment]
Hmm, I can't recreate it anymore. Could it have been an issue on my end only?

**Comment by Gymnasiast** [comment]
No, there has to be a bug. Biggest problem is finding out how to reproduce it.

**Comment by NoudL** [comment]
![afbeelding](https://user-images.githubusercontent.com/42575107/77543485-0e32e900-6ea8-11ea-9441-4d817628d2a2.png)
I'm not sure if seeing what text can be filled in will help locating the bug.

Also, this seems to be related:
![afbeelding](https://user-images.githubusercontent.com/42575107/77543418-f0658400-6ea7-11ea-83c5-3ee10f3175b6.png)

**Comment by NoudL** [comment]
My launcher just updated my game to 3f473ec and i cannot recreate it anymore, so it might have fixed it somehow?

**Comment by NoudL** [comment]
Nevermind it happened again. It doesn't seem to happen every time. I'm not really sure what i'm doing to trigger it

**Comment by NoudL** [comment]
![afbeelding](https://user-images.githubusercontent.com/42575107/77546628-6ec42500-6eac-11ea-88ed-ba14fb0bdfa3.png)
The cheat menu's tooltip also has the bug. Sorry if i'm spamming this issue

**Comment by Gymnasiast** [comment]
You don't need to post any more instances, no. 

I'm interested if someone else can reproduce this - with my Linux install, I can't.

**Comment by NoudL** [comment]
Looks like it only happens with recent save files. I tried it a bunch with old finished scenarios and it didn't happen. Then i started Bumbly Beach, saved it, loaded it from within the game and undefined strings showed up.

**Comment by Gymnasiast** [comment]
Could you update to https://github.com/OpenRCT2/OpenRCT2/commit/268e81c21baab50959ca4e00e7af4bd7679c7ee5 or newer and see if the issue persists?

**Comment by NoudL** [comment]
unfortunately i can't test it as the develop build download for windows seems to be broken/missing now. The launcher can't download it either

**Comment by Gymnasiast** [comment]
There was an outage on openrct2.org. That should now have been solved. Both the launcher and direct download should now result in a working install again.

**Comment by NoudL** [comment]
The wrong text bug is still happening in 9035ba2
