### ISSUE TITLE
x64 Develop builds starting from 8373fe6 are broken on Windows 10

### ISSUE THREAD

**Issue by NoudL** [OpenRCT2/OpenRCT2#11054]
**OS:** Windows 10
**Version:** 0.2.5
**Commit/Build:** starting from 8373fe6 

From this version on, both the .exe installer and the .zip files do not work on Windows 10. The .exe simply cannot be run. WinRAR and 7zip cannot unzip the Portable ZIP as they claim "it is not an archive".

Both the .exe and .zip file for 3f473ec (the version before 8373fe6 ) seem to be fine.

I have not checked for the x86 builds.

- [ no ] Reproducible in RCT2 (vanilla)?
- [ no ] Specific to multiplayer?

**Steps to reproduce:**
1. Download a Windows x64 Portable ZIP or installer from https://openrct2.org/downloads/develop/v0.2.5-8373fe6 or later versions. 
2. Try to run/unzip it.

**Comment by RoelerCoaster** [comment]
It looks like the file is not actually a zip-file, but a text file with a long json string like:
```json
{"file":{"type":"Buffer","data":[]}}
```
where `data` is a long array with numbers

**Comment by janisozaur** [comment]
I've tested the builds from github and they work fine. Nothing changed about how we upload the files, so it is not our problem, but .org instead. Please use our builds from github instead and file the issue with openrct2.org.

**Comment by Gymnasiast** [comment]
I should add that openrct2.org is a community-run website and not official. Though it's hardly surprising this isn't clear at all to the average user.

**Comment by Umdlye** [comment]
![Screenshot 2020-03-26 at 11 16 12](https://user-images.githubusercontent.com/11657101/77635683-39bedd80-6f53-11ea-9d10-664d5772d09f.png)

Especially not when it's listed as the main source of builds in the readme 😛

**Comment by janisozaur** [comment]
This should note be fixed on the other end too: https://gitter.im/OpenRCT2/OpenRCT2?at=5e7c89e3d4f4f71fc00da128

> I've removed the broken develop builds and hopefully fixed future builds. :)

**Comment by NoudL** [comment]
It's unfortunately not fixed. da2ba0b is still broken on OpenRCT2.org
Is https://github.com/Limetric/OpenRCT2.org the correct repository for OpenRCT2.org? I'll submit an issue there instead

**Comment by JarnoVgr** [comment]
I was made aware of this problem earlier this morning. It should be fixed for new builds. Please let me know if it'll still happen.

**Comment by JarnoVgr** [comment]
Resolved. This issue can be closed
