### ISSUE TITLE
Bumper boats gets stuck sometimes and no one can get off the ride

### ISSUE THREAD

**Issue by shuhaowu** [OpenRCT2/OpenRCT2#11058]
**OS:** Linux and Windows
**Version:** 0.2.4

Bumper boats gets stuck sometimes and no one can get off the ride.

- [ ] Reproducible in RCT2 (vanilla)? 
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Build a bumper boat
2. Wait

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/338100/77604126-a8774900-6f09-11ea-966c-c700a073014f.png)

**Comment by shuhaowu** [comment]
Also happens to Jet skis.

**Comment by ocalhoun6** [comment]
I'm fairly sure it happens occasionally with any vehicle type for the boat hire when the track isn't a complete circuit.

This is basically issue #866

**Comment by e-foley** [comment]
In my experience, this only happens when the back end of the station has track coming out of it. This affects vanilla as well.

**Comment by Gymnasiast** [comment]
I'm indeed considering this the same issue as #866.

**Comment by bourne2program** [comment]
Ugh really annoying. Should be simple to detect occurrence and solution can just be to move one inwards on track if none already there

<img width="428" alt="image" src="https://user-images.githubusercontent.com/132043779/235070190-a08c1d5e-186b-4581-8719-063ef2bdfc18.png">
