### ISSUE TITLE
Scenery window scrolling issue

### ISSUE THREAD

**Issue by Umdlye** [OpenRCT2/OpenRCT2#11063]
**OS:** Windows 10 (x64)
**Version:** 0.2.5
**Commit/Build:** da2ba0b

When you scroll down a long scenery tab, then switch to a different tab, the scroll position often persists. This can lead to a scenery tab appearing empty if the scroll position is below the last item in the tab.

This doesn't seem to happen all the time, but often enough to be an annoyance.

![2020-03-26_19-09-44](https://user-images.githubusercontent.com/11657101/77682005-81b32400-6f96-11ea-8f70-74db939acd80.gif)

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open scenery window
2. Open a scenery tab with a lot of items and scroll down
3. Switch to a different scenery tab, observe that it will scroll down to where you were in the previous tab

**Comment by IntelOrca** [comment]
I think this has been an issue for a long time, possibly vanilla bug - not sure.

**Comment by Umdlye** [comment]
I can reproduce it in the 0.2.4 release but not in vanilla.

**Comment by jeysbach** [comment]
I managed to fix this by adding the following to the code that's run when a tab is clicked:
```
// Reset scroll position if moving to another tab
if (gWindowSceneryActiveTabIndex != widgetIndex - WIDX_SCENERY_TAB_1)
{
    w->scrolls->v_top = 0;
}
```
However, this feels kinda hacky and I don't feel like I'm using the scrolls struct correctly by doing this.

**Comment by jeysbach** [comment]
I found another fix that works better and created a new PR for that.

**Comment by tupaschoal** [comment]
Ok, Just for reference, you can update the same PR in the future, there is no need to create a new one :)
