### ISSUE TITLE
Signs are crashing the game

### ISSUE THREAD

**Issue by oli414** [OpenRCT2/OpenRCT2#11076]
**OS:** Windows 10
**Version:** v0.2.5-36-gb70c5cefd
**Commit/Build:** b70c5ce

The signs on our multiplayer server got cleared due to a bug and now the signs cause a crash upon right clicking them, or having the tooltip shown for them.

In one of my single-player maps I get the same issue but only some signs.

This issue is similar to #4617, but this bug appeared as of yesterday so it is likely a new issue.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Load the save game
2. Find a sign and hover over it, or try to edit it.

**Dump file**
[f92aaced-2a45-48d8-980a-67ddd564386a(b70c5ce_x86-64).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/4392927/f92aaced-2a45-48d8-980a-67ddd564386a.b70c5ce_x86-64.dmp.gz)

**Save game:**
Multiplayer signs bug.
[MPS Signs Bug.txt](https://github.com/OpenRCT2/OpenRCT2/files/4392912/MPS.Signs.Bug.txt)

Singleplayer map, the sign for the rollercoaster in the western area causes a crash.
[SandboxPark6.txt](https://github.com/OpenRCT2/OpenRCT2/files/4392925/SandboxPark6.txt)

**Comment by duncanspumpkin** [comment]
We're these banners created in the bugged version of the game early this week? If it is those saves are broken.

**Comment by oli414** [comment]
Not created, but opened and saved. During that time

**Comment by duncanspumpkin** [comment]
Ah well the save is broken then nothing that can be done about that.

**Comment by Gymnasiast** [comment]
@duncanspumpkin I beg to differ. Broken banners should not crash the game, and solving those crashes helps a lot - certainly not a case of "nothing that can be done about that".

**Comment by duncanspumpkin** [comment]
I meant that the save is broken beyond repair. Yes the game shouldn't crash but the banners will be corrupted without easy repair from the previous bug.
