### ISSUE TITLE
SpriteListHead Refactor Peep / Staff

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#11075]
Really easy little refactor. We use the following macro to loop over all peeps:
```
FOR_ALL_PEEPS(sprite_index, peep) 
```
It basically does something similar to:
```
  for (spriteIndex = gSpriteListHead[SPRITE_LIST_PEEP]; spriteIndex != SPRITE_INDEX_NULL; spriteIndex = nextSpriteIndex)
        {
            auto peep = &(get_sprite(spriteIndex)->peep);
            nextSpriteIndex = peep->next;
```
But there are a number of cases in the codebase where we have just written out the whole big for loop again. This issue is to refactor all of those needless repeats to use the macro. There is also `FOR_ALL_GUESTS` and `FOR_ALL_STAFF` it should be pretty easy to work out when those macros can be used.

To get you started https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/actions/SetCheatAction.hpp#L688-L696 is an example of a `FOR_ALL_GUESTS` refactor location. Easiest way to find more is do a search for `gSpriteListHead[SPRITE_LIST_PEEP]`.

**Comment by TomasZilinek** [comment]
Hello, can I work on this? I chose your project for my course on college so you don't have to be afraid I will abandon this issue. :D

**Comment by duncanspumpkin** [comment]
Sure go ahead. I tried the other day to look see how many of these there were and there aren't actually that many. Maybe only 2-3 places that need modified.
