### ISSUE TITLE
Text in the debug console flashes with lightning.

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#1109]

**Comment by IntelOrca** [comment]
This won't be easy to fix as lightning sets the entire colour palette to white.

**Comment by mrtnptrs** [comment]
As the text at the debug console is white now, this issue isn't relevant anymore and can be closed. And additionally, this is a verry verry verry minor bug...

**Comment by Goddesen** [comment]
Minor or not, a bug is a bug.
Also this is still relevant: lightning makes the whole console flash. Additionally, there is colored text for errors, so the point about white text only doesn't hold.
