### ISSUE TITLE
Server is not online under 0.2.5

### ISSUE THREAD

**Issue by TonyLaV** [OpenRCT2/OpenRCT2#11101]
**OS:** [Windows 10]
**Version:** (0.2.5)

Hello,

when i host a server under 0.2.5 develop and release my server is not online and does not appear in https://servers.openrct2.io/

Nobody is able to connect to me. 

When i host a server under 0.2.4 my server is online and does appear in 
https://servers.openrct2.io/

I downloaded the versions here :
https://openrct2.org/downloads/releases/latest
https://openrct2.org/downloads/releases/v0.2.4

I used the launcher too.

- [ X ] Specific to multiplayer?

**Comment by janisozaur** [comment]
Can you check if any of builds for https://github.com/OpenRCT2/OpenRCT2/pull/10660 or https://github.com/OpenRCT2/OpenRCT2/pull/10654 (or one before them) are the start of this regression?

**Comment by janisozaur** [comment]
Also perhaps #10642. I attached the builds here, so they don't get lost.

[10660-openrct2-portable-Release-x64.zip](https://github.com/OpenRCT2/OpenRCT2/files/4397884/10660-openrct2-portable-Release-x64.zip)

[10654-openrct2-portable-Release-x64.zip](https://github.com/OpenRCT2/OpenRCT2/files/4397889/10654-openrct2-portable-Release-x64.zip)

[10642-openrct2-portable-Release-x64.zip](https://github.com/OpenRCT2/OpenRCT2/files/4397893/10642-openrct2-portable-Release-x64.zip)

**Comment by TonyLaV** [comment]
Ok i was able to test it now , with following results:

10642 - Server Online and visible under https://servers.openrct2.io/
10654 - Server not online and not visible under ""
10660 - Server appears on server list in OpenRCT2 after i quit the game, but no connection is possible and server is not visible under ""

**Comment by janisozaur** [comment]
@TonyLaV could you check a build from #11296?

**Comment by ZehMatt** [comment]
I'm unable to reproduce this 
![openrct2_0gEh6xKkIk](https://user-images.githubusercontent.com/5415177/88458538-1408fd00-ce8f-11ea-97b7-b00eff53f435.png)
