### ISSUE TITLE
"Show only tracked guests" button doesn't work

### ISSUE THREAD

**Issue by Umdlye** [OpenRCT2/OpenRCT2#11107]
**OS:** Windows 10 (x64)
**Version:** 0.2.5
**Commit/Build:** 2806104

The button in the guests window to only show tracked guests doesn't work any more. First occurs in 4016089.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Track some guests
2. Click the button

![2020-03-28_14-57-31](https://user-images.githubusercontent.com/11657101/77824722-13d93a80-7105-11ea-8847-dfee20a17688.gif)

**Comment by duncanspumpkin** [comment]
hmm I thought my fix this morning would have got that as well

**Comment by Umdlye** [comment]
Just noticed it starts working when the guest list updates.

**Comment by duncanspumpkin** [comment]
Ah well thats easy then. Its missing the call to refresh.

**Comment by Umdlye** [comment]
Same goes for the search button by the way.

**Comment by Umdlye** [comment]
This probably affects the "show these guests highlighted on map" option as well, it's supposed to make the guests blink red continuously but it only blinks once when a new guest arrives/leaves.

**Comment by duncanspumpkin** [comment]
Yeah it just needs the refresh then it will work the same as before.
