### ISSUE TITLE
Staff list issues

### ISSUE THREAD

**Issue by Umdlye** [OpenRCT2/OpenRCT2#11109]
**OS:** Windows 10 (x64)
**Version:** 0.2.5
**Commit/Build:** 2806104

The staff list seems to be sorted by hiring order instead of alphabetical order, and quick firing staff is quite broken. First occurs in e7d0043.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

![2020-03-28_15-48-59](https://user-images.githubusercontent.com/11657101/77825810-096e6f00-710c-11ea-9ff7-68a8ef4b0bf6.gif)

**Comment by duncanspumpkin** [comment]
Argh. I tested exactly this.

**Comment by duncanspumpkin** [comment]
So seems I was asleep whilst doing this change. Forgot to actually make the changes to the drawing code. If you clicked on a peep it was in the correct order. Fix incoming.
