### ISSUE TITLE
Guests Menu Filtering Very Broken

### ISSUE THREAD

**Issue by Dullstar** [OpenRCT2/OpenRCT2#11103]
OpenRCT2, v0.2.5-40-gb0737d5bd (b0737d5 on develop) provided by GitHub
Windows (x86-64)

The guest menu works properly when looking at either the list of guests and their thoughts/actions, or the summary of all guests' thoughts/actions. However, if you try to filter the list, for example, by clicking on a thought/action in the summary view or by accessing the guest list via the thoughts button on the Customer Information tab of a ride, unexpected behavior will occur. This unexpected behavior varies somewhat depending on whether or not the guest window has been filtered since it was last opened. If this is the first time the guest list has been filtered since the window was opened, it will display the list of all guests and their thoughts/actions. If the guest list was already filtered (which, since the player's inputs to filter the list are ignored, requires more unexpected behavior which I will explain shortly), then these guests will be the ones shown. While the guests that appear in the list are not the ones expected to appear based on the filtering, the text will be updated properly, e.g. from "All guests" to "Guests thinking "It's too crowded here"" or "Guests Walking."

The selected filtering will cycle also change seemingly randomly. I haven't identified much of a pattern, though if thoughts are selected, it will only filter by thoughts, while if actions are selected, it will only filter by actions. While this filtering shouldn't be happening, it does appear that the guests shown in the list correctly corresponds to whatever it updated the filtering to. The amount of time between filter changes shows no obvious patterns, but is definitely variable. Pausing the game will stop this from occurring, and it will resume as soon as the game is unpaused. Fast forwarding appears to make it happen more often.

Based on this behavior, the player's filtering commands appear to simply fail to update the displayed list of guests - since the guest menu defaults to showing all guests, that's probably why it shows all guests if no filtering has yet been applied, and continues showing the last filtering if some other filtering was already applied. This doesn't explain why the filtering keeps changing when the game is unpaused, however.

I would also like to note that this bug seems to be relatively recent, but I don't know exactly when it was introduced. Based on the file creation dates of my most recent save, on which it was working properly when I first started, the bug appears to have been introduced at some point between 2/23/2020 and 3/28/2020 (I wish I could be more specific, but I sometimes go a while between play sessions). I'm using the launcher set to the develop branch to keep the game up-to-date, in case that provides any helpful information as to what build it may have stopped working in.

- Not reproducible in RCT2 (vanilla)
- I only tested on single player.
- Doesn't occur in stable release v0.2.5 (4f6e77e)

**Steps to reproduce:**
Note that the behavior is slightly different depending on whether or not the game is paused. I'd recommend trying both when trying to reproduce. The exact outcome will also vary slightly if the guest window had been filtered since it was last opened (as noted above, the player trying to filter doesn't filter the list; it only enables it to be filtered through the filter changing bug described above).

OPTION 1:
1. Open the guest window if it is not open already.
2. Switch to the all guests (summary) tab
3. Select one of the options to filter the list of guests.
4. Observe the result.

OPTION 2:
1. Click on a ride to bring up its window
2. Switch to the customer information tab
3. Press the guest thoughts button.
4. Observe the result.

**Screenshots / Video:**
https://youtu.be/CRN0tzYtw-s

This issue affects both new and existing saves. Furthermore, these saves function normally if loaded in vanilla. One such save is attached: [Crazy Castle.zip](https://github.com/OpenRCT2/OpenRCT2/files/4396864/Crazy.Castle.zip)

**Comment by duncanspumpkin** [comment]
#11102 fixes this.

**Comment by Dullstar** [comment]
Ah, sorry, didn't see that when I was looking to see if this was a known issue.
