### ISSUE TITLE
Finance graph hover values are glitchy with software renderer

### ISSUE THREAD

**Issue by Umdlye** [OpenRCT2/OpenRCT2#11111]
**OS:** Windows 10 (x64)
**Version:** 0.2.5
**Commit/Build:** 2806104

![2020-03-28_16-22-54](https://user-images.githubusercontent.com/11657101/77826555-6b30d800-7110-11ea-84fe-c13908de09fe.gif)

This only happens with the software renderer, I don't have these issues with OpenGL.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Mouse your cursor over the finance graph while using software renderer

**Save game:**
[graph.zip](https://github.com/OpenRCT2/OpenRCT2/files/4397357/graph.zip)

**Comment by IntelOrca** [comment]
The window or control needs to be invalidated when the hints are moved.

**Comment by AaronVanGeffen** [comment]
Hmm, I didn't have any issues with the PR when I tested it using the software renderer. This looks like an invalidation error, though.  This is particularly interesting because windows are usually redrawn every frame.

**Comment by IntelOrca** [comment]
@AaronVanGeffen The inefficient ones are...

**Comment by Umdlye** [comment]
That would explain why nothing appears at all when no sprites are behind the window 😂

**Comment by AaronVanGeffen** [comment]
The way #10925 implemented this doesn't even touch the window code, so nothing is invalidated on its own.

@IntelOrca How should we go about this? We don't seem to have a mouse over event, do we? Should we add an `update` event for the finance tabs that invalidates them every tick? This seems a little wasteful.
