### ISSUE TITLE
Scenario Improvement: Handymen can create scenery

### ISSUE THREAD

**Issue by grahambilley** [OpenRCT2/OpenRCT2#11119]
**OS:** [Windows 10]
**Version:** [0.2.4]
**Commit/Build:** [d645338]

This is an enhancement request. I'm putting this here per request of Aaron van Geffen.

Give handymen the ability to create scenery. For example:

1. They walk on grass and afterwards a random tree/bush appears (similar to how they mow grass)
2. They walk on sand and a random piece of desert/egyptian scenery appears
3. They walk on tile next to water, and a random piece of water scenery appears in the water (fountains, etc)

Thank you,

**Comment by Gymnasiast** [comment]
Lovely stuff for a plugin ;)
