### ISSUE TITLE
Inconsistent Suggested Purchasing Sites

### ISSUE THREAD

**Issue by Zankoas** [OpenRCT2/OpenRCT2#11129]
Apologies if this isn't the right place to report this.

I've noticed that the quick start page on openrct2.org (https://openrct2.org/quickstart) offers up different suggestions for where to buy RCT2 than those on the quick start page on openrct2.io (https://openrct2.io/getting-started/index.html).

Both suggest GOG for those on Linux or macOS, but the former suggests G2A and Green Man Gaming for those on windows, with the latter suggesting steam. Both the G2A and Green Man Gaming suggestions are referral links.

This is both inconsistent, but also a strange choice of those to suggest. G2A status as a dubious grey market retailer is well documented:

https://www.engadget.com/2019-07-17-g2a-key-gift-game-developers-explained.html
https://techraptor.net/gaming/editorials/what-g2a-is-and-why-you-should-care
https://www.gamerevolution.com/features/12659-why-you-shouldnt-support-g2a-and-its-black-market-practices
https://www.eurogamer.net/articles/2017-02-03-controversial-pc-game-key-reseller-g2a-com-fights-fires-in-reddit-ama

Thus, I would suggest simply recommending steam on both. Steam is a more common and more trusted retailer and thus a more useful suggestion to make.

This would mean the loss of the referral revenue, but I am going to assume that isn't a lot otherwise both links would have been changed to the referral links.

I hope this is a useful suggestion, thanks for all your hard work!

**Comment by AaronVanGeffen** [comment]
OpenRCT2.org is a community-run website; our project has no control over it. I realise this is terribly confusing, but the project's official website is OpenRCT2.io.

This isn't to say your points are not valid, but please take it up with the kind people over at OpenRCT2.org. Thanks.

**Comment by Zankoas** [comment]
Done and done: https://forums.openrct2.org/topic/4919-removal-of-g2a-referral-link

Thanks for the clarification.

**Comment by janisozaur** [comment]
https://github.com/Limetric/OpenRCT2.org/pull/18

**Comment by Zankoas** [comment]
@janisozaur Oh wonderful, thank you!
