### ISSUE TITLE
Stop using c-style casts

### ISSUE THREAD

**Issue by tupaschoal** [OpenRCT2/OpenRCT2#11158]
Because OpenRCT2 historically used C, many places still use C-cast for doing stuff, but that's far from ideal, as it is generally more permissive than it should. The idea here is to remove all C-casts in the code in favour of one of the named casts: `static_cast`, `dynamic_cast`, `const_cast` or `reinterpret_cast`.

We can then easily evaluate the code to remove the most permissive ones, like `reinterpret_cast`, if applicable.

This is a lot of work, so it's recommended to break into multiple PRs inside each of these folders in `src`:

- [ ] openrct2
- [ ] openrct2-cli
- [x] openrct2-ui
- [x] openrct2-win

**Comment by ffrogman** [comment]
I think this is resolved. I can build with -Wold-style-cast. Maybe we should add this flag to prevent any C style casts from slipping in in the future?

**Comment by tupaschoal** [comment]
I think we have already (?)

**Comment by Lastorder-DC** [comment]
#11493

`-Wold-style-cast` is already enabled.

**Comment by tupaschoal** [comment]
Thanks for the check
