### ISSUE TITLE
git blame times out for .../src/openrct2/ride/Vehicle.cpp (and other files with >7,000-10,000 lines)

### ISSUE THREAD

**Issue by James103** [OpenRCT2/OpenRCT2#11167]
**Version:** 0.2.5
**Commit/Build:** f64ea65d03e89587c904f4bae067aeba50a672de

Using git blame on .../src/openrct2/ride/Vehicle.cpp (or any file with >7,000-10,000 lines) times out when done via the web interface. Smaller files work fine (such as .../src/openrct2/ride/Track.cpp or even .../src/openrct2/peep/Guest.cpp).

**Steps to reproduce:**
1. Navigate to OpenRCT2/OpenRCT2/blob/develop/src/openrct2/ride/Vehicle.cpp (or any file with >7,000-10,000 lines)
2. Run git blame
3. Git blame times out

**Screenshots / Video:**
URL: https://github.com/OpenRCT2/OpenRCT2/blame/develop/src/openrct2/ride/Vehicle.cpp
![image](https://user-images.githubusercontent.com/37945304/77972969-7aeb2080-72b8-11ea-8be9-c2ec528c9da4.png)

**Comment by IntelOrca** [comment]
Is this a suggestion to break up our source files into smaller ones? Because there is not much we can do about the GitHub interface.

**Comment by James103** [comment]
Possibly. As for `Vehicle.cpp` specifically, I think that the number and diversity of functions is enough to split into two different files. One file for the generic stuff that applies to most/all rides (`vehicle_update_crash`, `vehicle_update_departing`, and similar) and one file for the specialized stuff that each only apply to one or two rides (`vehicle_update_swinging`, `vehicle_update_ferris_wheel_rotating`, and similar).

**Comment by tupaschoal** [comment]
I actually contacted GitHub about the `blame` not loading, here is what they said

> Thanks for reaching out to GitHub Support, and sorry for the trouble.

> We're currently investigating similar reports regarding this issue, and I've added your report to our list.

> While we can't share a specific ETA just yet, we'll be sure to update you as soon as there's any news to share.

**Comment by James103** [comment]
GitHub updated the error message for git blame timeout, it now loads the page and says this:
![image](https://user-images.githubusercontent.com/37945304/78456885-2820b880-766c-11ea-957d-c6dd68979225.png)

**Comment by AaronVanGeffen** [comment]
I think we're open to splitting Vehicle.cpp into smaller files. However, we have other large files, like the (automatically generated) paint files for some of the larger coasters.

Regardless, I think GitHub timing out on the blame generation is something beyond our control — this is not limited to large files, anyway. If you're very keen on seeing who's responsible to a particular change, you can still clone the repo and check things out locally, of course.

**Comment by tupaschoal** [comment]
FYI, at least the blame seems fixed, I just tested and it worked.

**Comment by AaronVanGeffen** [comment]
Closing this ticket, then. In general, we're not opposed to splitting the larger files. If you're reading this and thinking: "I can do that!" — great! Please check with us on Discord before working on it to prevent disappointment, though.
