### ISSUE TITLE
Scenario editor crash

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#1119]
There seems to be a bug where Jungle, Snow and Ice, and Water scenery are automatically selected anytime you enter the Object Selection screen. This includes when the editor is first launched and when you go back to the Object Selection. If you are using a high amount of scenery, it is very common for the game to crash at the Invention List Setup. Some vanilla rides will also cause the game to crash if you try to open the scenario. Sometimes (I am not sure what causes this) adding or removing scenery, vanilla or custom will also cause the game to crash at the Invention page. Some custom scenery will cause the game to crash when trying to open the scenario. My method is to do one item at a time, save the scenario under a different save, open the scenario and pray there is no crash.

Source: http://www.reddit.com/r/openrct2/comments/36pexz/scenario_editor_crashesbugs/

**Comment by trigger-death** [comment]
That's a lotta crashes.

**Comment by rctdude2** [comment]
>There seems to be a bug where Jungle, Snow and Ice, and Water scenery are automatically selected anytime you enter the Object Selection screen. This includes when the editor is first launched and when you go back to the Object Selection.

I think this may be related to the map generation feature, which will use certain scenery from those groups for the generator in the second tab which will place trees.

As for the crash, I can't get it to trigger even if I select as many objects from each category as possible. Maybe it was just a corrupted object that they had?
