### ISSUE TITLE
No Wacky World in Scenario Builder

### ISSUE THREAD

**Issue by TonyLaV** [OpenRCT2/OpenRCT2#11198]
-->
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.2.5 and 0.2.4]

Hello, 

i cant select any Wacky World items when im creating a scenario. Nothing is selectable. There is nothing. In menu im able to start Wacky World scenarios and play them with no problems. When i select a savegame in scenariobuilder i still cant select any items which came with wacky worlds

**Steps to reproduce:**
1.  Start Scenario Builder

I also dowloaded demo to test it, it doesnt work either.

**Comment by AaronVanGeffen** [comment]
The RCT2 demo does not contain any of the WW or TT objects or scenarios. You will need a copy of the full game to play these.

**Comment by TonyLaV** [comment]
I have the full game , and the demo does contain WW and TT.

**Comment by TonyLaV** [comment]
![Unbenannt](https://user-images.githubusercontent.com/33175850/78113739-76318400-7400-11ea-824c-5fced17cbe08.png)

Heres the proof

**Comment by AaronVanGeffen** [comment]
Odd. Have the objects been turned off with the filter function, by any chance?
![Unnamed park 2020-04-01 10-46-52](https://user-images.githubusercontent.com/604665/78117603-235acb00-7406-11ea-8691-07c180132803.png)

**Comment by TonyLaV** [comment]
Yes , thats it. Thank you 👍
