### ISSUE TITLE
Cannot save parks with RCT2 DLC objects

### ISSUE THREAD

**Issue by VersionEins** [OpenRCT2/OpenRCT2#11208]
**OS:** Windows 10
**Version:** 0.2.5-81
**Commit/Build:** 08d38f3

I can't save the attached savegame when activating the option to export plug-in objects.

**Steps to reproduce:**
1. Load the save
2. Check "Export Plug-In Objects" in the options menu
3. Try to save the game

**Save game:**
[V1 380.zip](https://github.com/OpenRCT2/OpenRCT2/files/4419530/V1.380.zip)

**Comment by Gymnasiast** [comment]
Perhaps you have objects in your `object` folder that are broken. Can you provide a ZIP for us? (Since the file will probably be too big for Github, you might need to split it up into chunks of 10 MB, or provide a Dropbox or MEGA link or something like that.)

**Comment by VersionEins** [comment]
Here's the link:
https://drive.google.com/open?id=1tvkrobZaiwRrjgjzSlMDDwXa0fPG_ScM

It works fine with 2.4, btw.

**Comment by Umdlye** [comment]
It tries to export `PANDAGR.dat`, but in object selection it shows the `.parkobj` version.

```
VERBOSE: exporting object PANDAGR
ERROR[D:\a\OpenRCT2\OpenRCT2\src\openrct2\rct2\S6Exporter.cpp:1722 (scenario_save)]: Unable to save park: 'Header found in object file does not match object to pack.'
VERBOSE: show error, Save GameGame save failed!
```

This object conflict appears when starting the game:
```
Object conflict: 'C:\Users\Steph\Documents\OpenRCT2\bin\data\object\official\scenery_small\rct2.dlc.pandagr.parkobj'
               : 'C:\Users\Steph\Documents\OpenRCT2\object\PANDAGR.DAT'
```

The .dat object is in this zip: [PANDAGR.zip](https://github.com/OpenRCT2/OpenRCT2/files/4423020/PANDAGR.zip)

**Comment by Gymnasiast** [comment]
Hm, that makes sense. Thanks for finding that out, that helps a great deal.

**Comment by janisozaur** [comment]
Should this be included in `v0.2.6` milestone?

**Comment by Gymnasiast** [comment]
@janisozaur I have added it. It's not entirely a showstopper, but I think I might be able to fix it tomorrow.

**Comment by Umdlye** [comment]
Well, it does create a save despite the error, and the save is unusable (kicks you to the title screen). So I guess if you overwrite an old save with it, it's kind of a showstopper 😛

**Comment by Gymnasiast** [comment]
Good point. Well, it will go into 0.2.6 anyway.
