### ISSUE TITLE
Giga Coaster cable lift hill

### ISSUE THREAD

**Issue by TBloemink** [OpenRCT2/OpenRCT2#1122]
The Giga Coaster cable lift hill is a bit buggy. When the lift hill is used as a block brake (seperate exit&entrance station including 2 seperate block brakes), when going into test mode, the train is not hooked to the cable (i.e. the cable goes down, block brake waits for permission to go). The cable is going down for the train in the station to hook up to it, forgetting that there is a train at the top of the hill.

This bug causes the train at the top of the hill to fall down (duh, theres no cable attached) and crash into the train arriving at the station.

I hope I have explained it well enough

repro:
- create a giga coaster, seperate entrance and exit stations (with both having a block brake in front)
- make a 'cable lift hill'
- start testing

i myself have been able to reproduce the bug multiple times (using the now latest version)
![bug openrct giga coaster](https://cloud.githubusercontent.com/assets/1117643/7748505/830e6ac6-ffc5-11e4-8a67-37381dcf81a2.png) (in the picture the 'cable' is visible at the station, the train on the lift is actually coming down and yes, it crashed)

**Comment by rctdude2** [comment]
This seems to only happen when the front station is station 2 and the game thinks that that the block break between the two stations is the last block break section of the coaster and doesn't put a train there. Additionally, it seems that the game thinks that the top of the cable lift hill is a block section, which should never happen.

This bug also exists in the original RCT2.

**Comment by trigger-death** [comment]
This actually needs to be declared as an original bug.
Also if you put block breaks only between the entrance and exit station using the same setup. RCT2 will go into an infinite loop.

**Comment by Christipher** [comment]
There are still some ways around that bug - optimize the number of trains running on the coaster such that there would be no reason (other than the ride broke down) for the cable lift to stop... however, two stations could cause problems... and there is a one cable lift per ride limit (which is a general behavior)

**Comment by sapman1208** [comment]
I'm having an issue where the cable lift will be frozen somewhere on the lift hill and will not move after the ride has running fine for a few hours. I'm not sure if this is happening after a breakdown or not.

**Comment by sapman1208** [comment]
I just experienced the cable lift being stuck on the lift again even with an exit on the station before the cable lift. This bug seems to still happen whether there is an exit on the first station or not.

**Comment by Gymnasiast** [comment]
Here is a save to easily test with. You can check if the bug is fixed by double closing the roller coaster and putting it back into test mode.

[FF-crashcablelift.park.zip](https://github.com/user-attachments/files/18222895/FF-crashcablelift.park.zip)
