### ISSUE TITLE
Replay system cannot build tracked rides

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#11225]
**Version:** current `develop`
**Commit/Build:** 13a2f6740

The attached replay, submitted as an artifact of #11190, should build attached park, but none of the tracked rides are created. Instead, logs contain following:

```
WARNING[../src/openrct2/actions/RideSetStatus.hpp:66 (Query)]: Invalid game command for ride 1
WARNING[../src/openrct2-ui/../openrct2/actions/RideSetPriceAction.hpp:63 (Query)]: Invalid game command, ride_id = 1
WARNING[../src/openrct2-ui/../openrct2/actions/RideSetPriceAction.hpp:63 (Query)]: Invalid game command, ride_id = 1
WARNING[../src/openrct2-ui/../openrct2/actions/RideSetPriceAction.hpp:63 (Query)]: Invalid game command, ride_id = 1
WARNING[../src/openrct2-ui/../openrct2/actions/RideSetPriceAction.hpp:63 (Query)]: Invalid game command, ride_id = 1
WARNING[../src/openrct2-ui/../openrct2/actions/RideSetPriceAction.hpp:63 (Query)]: Invalid game command, ride_id = 1
```

[park_11225.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/4432594/park_11225.sv6.txt)
[replay_11225.sv6r.txt](https://github.com/OpenRCT2/OpenRCT2/files/4432595/replay_11225.sv6r.txt)

**Comment by janisozaur** [comment]
ping @ZehMatt @duncanspumpkin

**Comment by janisozaur** [comment]
I'd expect this to be a regression, perhaps from when prebuilts support was added to multiplayer?

Also, don't know how sprite checksum mismatch is reported, but I'm pretty sure missing half the park should trigger it, but there was nothing reported.

**Comment by janisozaur** [comment]
It's especially odd, as I did test it locally a few days ago and seemed to work fine. I only tested it on my local Linux machine with a very simple recording, though it did include building a tracked ride and it replayed correctly.

**Comment by duncanspumpkin** [comment]
Issue caused by flags not being passed down to the internal game actions of track design placement.

**Comment by duncanspumpkin** [comment]
It wont cause any issues apart from prevent replays recording correctly.
