### ISSUE TITLE
Seat rotation not imported correctly

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#11230]
**OS:** Ubuntu 20.04
**Version:** 0.2.5+
**Commit/Build:** 12ab701a0fc89e1e12a3724ebef164ae4c111172

Copied from https://forums.openrct2.org/topic/4869-4ds-now-broken-when-opening-saves/?tab=comments#comment-23904

 A little more research shows the bug appears in 0.2.3. Before them it wasn't present

A couple more examples of this bug in action taken from this park that was released a couple of years ago.

https://www.nedesigns.com/park/4198/laguna/

Since the release several of the rides no longer operate as they were designed.

version 0.1.2 - Cars on Mack-E-Motion coaster tilt on corners

![afbeelding](https://user-images.githubusercontent.com/1478678/78471152-659a4a00-772f-11ea-80d0-ac40083f4bd6.png)

version 0.2.5 - Cars no longer tilt and are locked to position

![afbeelding](https://user-images.githubusercontent.com/1478678/78471156-6d59ee80-772f-11ea-8821-5be184c01b8c.png)

version 0.1.2 - Cars on Ghost Train rotate to look at different scenes

![afbeelding](https://user-images.githubusercontent.com/1478678/78471160-78ad1a00-772f-11ea-9786-121fd2063a9e.png)

version 0.2.5 - Cars are locked to one position and all look the same way
![afbeelding](https://user-images.githubusercontent.com/1478678/78471163-806cbe80-772f-11ea-8bc0-bf8bd7db3b72.png)

**Comment by duncanspumpkin** [comment]
Ah this might explain a desync someone mentioned on gitter
