### ISSUE TITLE
Can't open a lot of scenarios and save games, loaded back to main menu upon trying

### ISSUE THREAD

**Issue by giraty** [OpenRCT2/OpenRCT2#11236]
**OS:**  Windows 10
**Version:** 0.2.5 develop
**Commit/Build:** Starting from 13a2f67, still persist until 53b9482 (time of writing)

Trouble trying open any scenarios except few (listed below), this includes RCT1 scenarios, several save game also failed to load, currently some of the multiplayer maps have no trouble loaded

Tested all RCT1 and RCT2 original and expansion packs scenarios.
RCT1 Original Scenarios:
Only Forest Frontiers loaded

RCT1 AA/CF and LL and real world scenarios:
None loaded

RCT2 Original Scenarios:
Amity Airfield,
Botany Breakers,
Extreme Heights,
Ghost Town
Only these loaded, none of real parks and other parks loaded

RCT2 Wacky Worlds:
North America Grand Canyon
North America Rollercoaster Heaven
Asia Japanese Coastal Reclaim
Only these failed to load

RCT2 Time Twisters:
Only Future World park failed to load

- [ ] Reproducible in RCT2 (vanilla)? No
- [ ] Specific to multiplayer? No

**Steps to reproduce:**
1. New game or select scenario
2. Click the scenario that listed fail to load
3. A few seconds waiting
4. Returned back to main menu without any warning

**Dump file**
None

**Screenshots / Video:**
https://youtu.be/1TUVyGlVztk

**Comment by Gymnasiast** [comment]
I cannot reproduce your issue.
Can you open `openrct2.com` and tell me if any messages appear in the console?

**Comment by giraty** [comment]
![Untitled](https://user-images.githubusercontent.com/8456673/78532252-162c4a80-7811-11ea-929e-40c0b33f0cbe.png)
There's this several lines that always appear everytime I tried to load scenarios that won't load
(The yen is backslash, currently I have my locale set to Japanese)

**Comment by Gymnasiast** [comment]
It looks like there is something wrong with your object files. How did you install OpenRCT2?

**Comment by giraty** [comment]
I always install using the portable zip, put them in RCT2 folder, and extracted the files there

**Comment by Gymnasiast** [comment]
That's not really the recommend way of installing. 

You might have some residual files then. Go to the `data` folder and remove all subfolders. Then, re-extract the portable ZIP.

**Comment by giraty** [comment]
Right, that solved the issue, it was just personal error then. Now even the a613ec3 works properly. I think the "delete subfolders on data folder" upon updating version should be mentioned now on the guidelines if some users install like how I do

**Comment by Gymnasiast** [comment]
We specifically recommend against mixing RCT2 and OpenRCT2, and just extracting a ZIP without removing the old version
