### ISSUE TITLE
rct_ride_entry_vehicle.pad_62 used for anything?

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#11244]
I am interested in modifying vehicle animations in certain ways for custom rides. For animation type 1, a change to the origin of the smoke particles is desirable. For animation type 6, changing the speed of the animation is desirable.

Looking in the vehicle entry struct `rct_ride_entry_vehicle`, it appears six bytes are unused, in `pad_62`. Is this the case? I want to use them to perform the aforementioned modifications.

**Comment by duncanspumpkin** [comment]
Anything with `pad_XX` in the name means it is unused but as we don't use this structure for json objects you don't need to find a pad_XX. Just create a new field in the json object and handle it on loading.

**Comment by spacek531** [comment]
I don't use JSON objects, since last I heard they don't get packed, there's no infrastructure to send them around, and the tool that X7123M3-256 wrote does not make JSON objects.

**Comment by duncanspumpkin** [comment]
You can't have a new field without using json objects.

**Comment by Gymnasiast** [comment]
@spacek531 You don't need a tool to create them, that's the whole point. You can edit JSON files by hand and include all the images as .PNGs.

Anyway, your points about them not getting packed or being available for autodownload do stand.
