### ISSUE TITLE
Text on scrolling banners disappears after saving the game

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#11258]
**OS:** Windows 10
**Version:** 0.2.5 - was already present in 0.2.4
**Commit/Build:** fdf9806

![image](https://user-images.githubusercontent.com/6469413/78975812-3f9ced00-7b15-11ea-984e-ee585919cfdf.png)

After saving, the banners in my megapark all lose their text. I also had this problem a few times but with the banners only keeping the first word or first character. I also saw this happen in some other parks.

1. Open attached save file
2. Change the banner text into something
3. Save the game
4. Reload, and watch the text on the banner disappear

**Save game:**

[Deurklink MegaPark.zip](https://github.com/OpenRCT2/OpenRCT2/files/4460598/Deurklink.MegaPark.zip)

**Comment by deurklink** [comment]
When i remove the banner and replace it with a new one, the problem is gone for the new banner. But I think at some point, the value for the banner gets overwritten somewhere and then the problem persists until I replace the banner again.

**Comment by AaronVanGeffen** [comment]
Had a quick look — here are only 84 banners in the park (out of 250), so it's not like the limit is being hit there.

**Comment by deurklink** [comment]
I got rid of this problem by removing all the banners and replacing them with new ones. But then after a few days the problem came back. I don't know what causes it.

**Comment by janisozaur** [comment]
Oh cool, it is not something odd with my own setup. I noticed this with recent replay parks as well. Sometimes the banner scrolled and other times it did not. A banner above the park entrance stopped scrolling in the main viewport, but was scrolling properly in the small one with park/ride details.

**Comment by janisozaur** [comment]
Regression from f539fdd79

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/0cbd7002902e91d5e5023a91aa87dd94332fc07b/src/openrct2/rct2/S6Exporter.cpp#L1625-L1632


```
auto rct2encoded = utf8_to_rct2("dfgdfgdfg");
// rct2encoded = { 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x02ffffff96, 0x0264, 0x0266, 0x0267, 0x0264, 0x0266, 0x0267, 0x0264, 0x0266, 0x0267 };
```

Also it seems that parks once broken stay broken and exhibit the problem slightly different.

**Comment by Richard-L** [comment]
I can confirm the same problem on:

OpenRCT2, v0.2.5-127-g0cbd70029 (0cbd700 on develop) provided by GitHub
Windows (x86-64)

It appears the problem has to do with how many times you save? I had 5 or so banners in my park each dating from different days. The "older" banners in the park showed the problem first: the fragments are cut off from the end of the text. So for example a banner was:

"You're my end and my beginning"

And after a number of saves I noticed it had become:

"You're my end an"

Initially started editing them and filled in the desired full string again, but the truncation continued to happen. Eventually the "younger" banners showed the problem too. The only temporary fix is to replace them as Deurklink mentioned, so you'll have a couple of saves where things are fine.

**Comment by Richard-L** [comment]
Another observation as I am reporting a banner related issue: 

If the default "Sign" string is not changed, even one save, close, and re-open of OpenRCT2 and the park, seems to remove the banner's content entirely.

**Comment by janisozaur** [comment]
Ah, well, it only gets encoded this way because the original is also odd:
```
ct2encoded.size() = 38

encoded = 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0xffffff96 0x73 0x64 0x66 0x73 0x64 0x66 0x73 
src = 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0xffffffc2 0xffffff96 0x73 0x64 0x66 0x73 0x64 0x66 0x73 
WARNING[../src/openrct2/rct2/S6Exporter.cpp:1296 (GetTruncatedRCT2String)]: The user string 'sdfsdfs' is too long for the S6 file format and has therefore been truncated.
```

```diff
diff --git a/src/openrct2/rct2/S6Exporter.cpp b/src/openrct2/rct2/S6Exporter.cpp
index 6b2ab8328..68be57c6e 100644
--- a/src/openrct2/rct2/S6Exporter.cpp
+++ b/src/openrct2/rct2/S6Exporter.cpp
@@ -1283,6 +1283,16 @@ static std::string GetTruncatedRCT2String(const std::string_view& src)
     auto rct2encoded = utf8_to_rct2(src);
     if (rct2encoded.size() > RCT12_USER_STRING_MAX_LENGTH - 1)
     {
+        printf("rct2encoded.size() = %zu\n", rct2encoded.size());
+        printf("\nencoded = ");
+        for (size_t i = 0; i < rct2encoded.size(); i++) {
+            printf("0x%02x ", rct2encoded[i]);
+        }
+        printf("\nsrc = ");
+        for (size_t i = 0; i < src.size(); i++) {
+            printf("0x%02x ", src[i]);
+        }
+        printf("\n");
         log_warning("The user string '%s' is too long for the S6 file format and has therefore been truncated.", std::string(src).c_str());
 
         rct2encoded.resize(RCT12_USER_STRING_MAX_LENGTH - 1);
```

In previous comment (https://github.com/OpenRCT2/OpenRCT2/issues/11258#issuecomment-612686216) I misplaced `%`: it was `printf("0x02%x "` instead of `printf("0x%02x "`, hence the odd `0x02` prefix.

**Comment by janisozaur** [comment]
The odd chars are colour codes, introduced in af5daaec7

`RCT12::RemoveFormatCodes`: https://github.com/OpenRCT2/OpenRCT2/blob/0cbd7002902e91d5e5023a91aa87dd94332fc07b/src/openrct2/rct12/RCT12.cpp#L485-L521 introduced in that commit doesn't really remove said format codes, I haven't yet checked why.

Saving such park will prepend the user string with format code over and over again never to remove them, eventually pushing out the actual data out of the buffer. The format codes are not displayed in the console and thus such bogus messages.

**Comment by brenoguim** [comment]
This function is applied on an RCT2 string right? Why is it checking for format code using utf8?

**Comment by brenoguim** [comment]
The function is expecting RCT12 string, but using `utf8_is_format_code` to check for the format code. Perhaps that is the problem?
