### ISSUE TITLE
Custom JSON object breaks saves

### ISSUE THREAD

**Issue by Umdlye** [OpenRCT2/OpenRCT2#11259]
**OS:** Windows 10 (x64)
**Version:** 0.2.5
**Commit/Build:** fdf9806

I created a custom JSON scenery group object following @Gymnasiast's instructions the other day and it works as expected, but it breaks saves it's included in regardless of export settings.

When exporting custom objects is enabled and the park is saved, saving aborts while giving the error `Header found in object file does not match object to pack.`: [save log.txt](https://github.com/OpenRCT2/OpenRCT2/files/4461493/save.log.txt)
The created save is in the attached .zip (export.sv6).

When exporting custom objects is disabled and the park is saved, the park appears to save normally. The created save is in the attached .zip (no export.sv6).
When you try to load this save it appears to export the object while loading, resulting in the same error: [load log.txt](https://github.com/OpenRCT2/OpenRCT2/files/4461507/load.log.txt)

This .zip has the object file and the two save files: [objectissue.zip](https://github.com/OpenRCT2/OpenRCT2/files/4461510/objectissue.zip)

This is the .json file used for the object:

```
{
    "id": "#UMDSCGT",
    "authors": ["Umdlye"],
    "version": "1.0",
	"originalId": "00000087|#UMDSCGT|00000000",
    "sourceGame": "custom",
    "objectType": "scenery_group",
    "properties": {
        "entries": ["TGE1", "GEOROOF2", "LAMP1"],
        "priority": 20
    },
    "images": [
        { "path": "images/0.png", "x": 0, "y": 0 },
        { "path": "images/1.png", "x": 0, "y": 0 } 
    ],
    "strings": {
        "name": {
            "en-GB": "Test group",
            "fr-FR": "Test group",
            "de-DE": "Test group",
            "es-ES": "Test group",
            "it-IT": "Test group",
            "nl-NL": "Test group",
            "sv-SE": "Test group",
            "ko-KR": "Test group",
            "zh-CN": "Test group",
            "zh-TW": "Test group",
            "pt-BR": "Test group",
            "cs-CZ": "Test group",
            "ja-JP": "Test group",
            "pl-PL": "Test group",
            "ru-RU": "Test group"
        }
    }
}
```

**Comment by duncanspumpkin** [comment]
That is expected behavior but it should be properly warned.

**Comment by Umdlye** [comment]
So custom JSON objects are not intended to be used with the .sv6 format at all, even if they're not exported? That seems a bit weird.

**Comment by duncanspumpkin** [comment]
I only know that they can't be packed into an sv6. Saving unpacked I'm not sure what the thought is

**Comment by IntelOrca** [comment]
@duncanspumpkin it should work, all the vanilla objects are JSON and don't cause an issue. It should export the entry according to how you have set "originalId" in the JSON.

**Comment by IntelOrca** [comment]
I have create a PR to stop it from trying to pack the object. I was not actually able to reproduce your problem when you turned off object export... that was working fine for me.
