### ISSUE TITLE
ride crashes debug builds

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#11256]
**OS:** e.g. Windows 10
**Version:** 0.2.0, DEBUG

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. open attached save file
2. open ride

[Test Mat Slide Crash.zip](https://github.com/OpenRCT2/OpenRCT2/files/4458674/Test.Mat.Slide.Crash.zip)

**Comment by janisozaur** [comment]
Does not happen anymore on current `develop`: fdf98060c

Feel free to reopen if you find it crashing in some builds.
