### ISSUE TITLE
Idea: Peep vacuum

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#11253]
It's great we have a cheat to make hundreds of peeps spawn, but it's much harder to get rid of peeps, unless you want ALL peeps gone. Maybe it's nice if we had a peep vacuum. Something like the scenery removal tool, but it removes peeps. Could also be great to get rid of peep jams.

When enabled the cursor turns into a vacuum cleaner icon and if you hold the mouse button peeps in the vicinity of your curser will be sucked in and removed from the map.

![peepvacuum](https://user-images.githubusercontent.com/19242088/78841527-dc6c6700-79fd-11ea-9c01-c4c198a66dc9.png)

**Comment by IntelOrca** [comment]
I really like the tool image! The plugin system will hopefully be merged soon, although I need to add a couple more APIs to allow creation of custom tools.

**Comment by thiebert** [comment]
I had a go at this. I used some of Oli414's code for selecting an area, but I plan to update it to work in the vicinity of the cursor instead, just ran out of time to do so tonight.

https://github.com/thiebert/openrct2-peep-vacuum
