### ISSUE TITLE
Graphical glitch with Giga coaster's cable lift hill

### ISSUE THREAD

**Issue by rctdude2** [OpenRCT2/OpenRCT2#1126]
![err](https://cloud.githubusercontent.com/assets/8041567/7755224/a79cc8ec-ffc0-11e4-9150-773ccdc47c3f.png)

The cable appears to be shifted off the center either to the left or the right of the track depending on what direction you're looking at it from.

**Comment by Gymnasiast** [comment]
Can't reproduce this with the current version. Does this still happen for you?

**Comment by Gymnasiast** [comment]
Closing this for now as I can't reproduce. If it still happens for you, please say so.

**Comment by duncanspumpkin** [comment]
I  made a change to the cable lift hill drawing code a little while back that could easily be what fixed this.
