### ISSUE TITLE
Elevator/Lift becomes completely unusable upon loading a saved game or starting a new game.

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#11261]
**OS:** Windows 10
**Version:** 0.2.5 - was already present in 0.2.4
**Commit/Build:** fdf9806

The Elevator/Lift currently suffers from a major bug where building one in a scenario, saving the game, and then loading said saved game results in the Elevator/Lift's station 2 (top station) now having an unusable entrance and exit because the game thinks that the station 1 (bottom station) entrance and exit are accidentally reused for the top station, removing the station fences at station 2 where the station 1 entrance and exit are. Subsequently, guests and staff cannot use the top station anymore because of this, effectively making the Elevator/Lift **_useless_** as the lift cabin goes into an infinite loop bouncing between stations, always unloading and loading at station 1. To even fix this (temporarily), I am forced to close the ride and rebuild the affected stations. I am able to click on station 1 but not station 2, which is still selectable in the View of ride/attraction tab. This bug is related to #10806, #10372, and #10509, the latter also containing a mention about the fence draw bug already present since 0.2.3.

This bug also affects every subsequent station on the Elevator/Lift and has been present in the game since v0.2.4.

- Reproducible in RCT2 (vanilla)? **No**
- Specific to multiplayer? **No**

**Steps to reproduce:**
1. Build an Elevator/Lift in any scenario that has it (e.g. Six Flags Magic Mountain, Africa - Oasis, Future - First Encounters). If it's not there, use object selection to add it in.
2. Build the Elevator/Lift like normal; build the bottom entry/exit platform as normal and then build the second entry/exit platform. You can repeat this twice up to a maximum of 4 entry/exit platforms/stations.
3. Test the ride and wait for its ratings to be calculated.
4. Save the game and then load the game. The stations should look glitched now.
5. This bug also occurs if you start a scenario that already has Elevators/Lifts as prebuilt rides (e.g. Africa - African Diamond Mine, Six Flags over Texas). It may even occur after an extended period of playtime.
6. Sometimes, rebuilding the ride may not reproduce the bug.

**Screenshots / Video:**
Before - with two stations
![Before - with two stations](https://user-images.githubusercontent.com/61885939/79005607-1c217480-7b0c-11ea-8967-236c70e0db11.png)
After - with two stations. Notice that the top station is now unusable and that there are misplaced fences on it.
![After - with two stations](https://user-images.githubusercontent.com/61885939/79005629-293e6380-7b0c-11ea-9f10-e5b92766f512.png)
Before - with four stations
![Before - with four stations](https://user-images.githubusercontent.com/61885939/79005658-36f3e900-7b0c-11ea-8491-7dbb4a8b4920.png)
After - with four stations. Notice that every station above station 1 (the bottommost station) is now unusable and has misplaced fences.
![After - with four stations](https://user-images.githubusercontent.com/61885939/79005671-3d826080-7b0c-11ea-886e-c8a41a7f2cf2.png)

**Save game:**
[Elevator bug.zip](https://github.com/OpenRCT2/OpenRCT2/files/4462374/Elevator.bug.zip)

**Comment by duncanspumpkin** [comment]
Closed as Duplicate
