### ISSUE TITLE
Android build doesn't work 

### ISSUE THREAD

**Issue by Jackthe3rd** [OpenRCT2/OpenRCT2#11266]
**OS**: [Android 8.0 (emui 8)]
**Version:** [0.2.5]
**Commit/Build:** [fdf9806]

Android build doesn't work

**Steps to reproduce:**
1. Launch the game
2. Try to launch anything

**Screenshots / Video:**
![Screenshot_20200411-130528](https://user-images.githubusercontent.com/58362788/79036763-a691d300-7bf5-11ea-8855-e1fcc9314885.jpg)
![Screenshot_20200411-130506](https://user-images.githubusercontent.com/58362788/79036766-a85b9680-7bf5-11ea-86ed-f39780b1b277.jpg)
![Screenshot_20200411-130457](https://user-images.githubusercontent.com/58362788/79036767-a8f42d00-7bf5-11ea-8763-3b42be76cebe.jpg)
![Screenshot_20200411-130440](https://user-images.githubusercontent.com/58362788/79036768-a98cc380-7bf5-11ea-97ff-ba081902067a.jpg)

**Comment by duncanspumpkin** [comment]
Looks like you dont have the assets installed correctly.
