### ISSUE TITLE
Notification for how many people died in an accident cannot be disabled

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#11272]
**OS:** [Windows 10]
**Version:** [0.2.5]
**Commit/Build:** [b5336fc]

I disabled all notifications on the different tabs that are available, but the message for how many people died in an accident still pops up every time.

![rideaccident](https://user-images.githubusercontent.com/6469413/79042172-bc06fd00-7bf5-11ea-8c07-4b5e86e4fe4d.png)

**Comment by AaronVanGeffen** [comment]
Shame on you for trying to cover up the deaths of innocent peeps! :wink:

**Comment by deurklink** [comment]
While we're at it, this message also just popped up :)
![image](https://user-images.githubusercontent.com/6469413/79043220-4b181300-7bfe-11ea-80c5-a9b8dcc5195b.png)

**Comment by AaronVanGeffen** [comment]
Thanks. I guess a more thorough investigation (inventorisation even) of missing items is in order, then.

**Comment by AaronVanGeffen** [comment]
Aside from the stuck/stalled vehicles, there are three more instances of unguarded notifications:

1) Failed scenario due to rating dropping below certain threshold. Other warnings are guarded.
2) Replay recording stopped
3) Replay recording completed

I think all three of these are desirable behaviour, anyway, so I'll just amend #11273 for the stuck vehicles only.

**Comment by pizza2004** [comment]
My only real question is how did you manage to kill so many people on _Mini Golf_?

**Comment by AaronVanGeffen** [comment]
It can be a very [dangerous](https://youtu.be/Y2DDqW8G8Q0) ride alright...

**Comment by Fred-1044276** [comment]
Speaking of notifications, is there really a way to disable the "Guests are getting lost or stuck" message?

**Comment by AaronVanGeffen** [comment]
I was under the impression that was covered by the 'Guest lost' option, but that doesn't appear to be used. Hmm!

**Comment by AaronVanGeffen** [comment]
> is there really a way to disable the "Guests are getting lost or stuck" message?

Yes, that is one of the message types covered by the 'guest warnings' option.
