### ISSUE TITLE
Crashes that kill only 1 peep create grammatically incorrect messages

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#11275]
OS: [Windows 10]
Version: [0.2.5]
Commit/Build: [b5336fc]

Noticed this on #11272's screenshot. 

Message says: "1 people have died in an accident on Mini Golf 1"
Grammatically correct version would be: "1 person has died in an accident on Mini Golf 1"

I'm not sure the effort/reward ratio is worth it on this one -- it might be a lot of trouble to add extra logic for the special case of only 1 death, _and_ I suspect you'd have to add another entry in the language files, not to mention propagating the change to other translations. And 1 death crashes probably aren't all that common in normal gameplay. But I thought it would be good to make note of this. Maybe someone can take a moment to tweak it when they're redoing the language files anyway or something.

![](https://user-images.githubusercontent.com/6469413/79042172-bc06fd00-7bf5-11ea-8c07-4b5e86e4fe4d.png)

- [ probably ] Reproducible in RCT2 (vanilla)?
- [ no ] Specific to multiplayer?

**Steps to reproduce:**
1. Build a ride with single-person vehicles that can crash (dinghy slide, mini suspended coaster, hacked mini golf, etc.)
2. Crash them and kill some guests

**Comment by AaronVanGeffen** [comment]
Personally, I don't think this is worth changing at this point, for the reasons you have already mentioned. Unfortunately, when a ride does crash in-game, more than one peep tends to die, after all.

**Comment by Gymnasiast** [comment]
The nice thing about Gettext (and, I suppose, most modern systems) is that it doesn't just allow for singular and plural, it also supports languages which use other systems entirely (Russian, for example, has _three_ forms).

Still though, I wouldn't necessarily be opposed to fixing it now. After all, that new localisation system might take a few months or even years.

**Comment by ocalhoun6** [comment]
> Unfortunately, when a ride does crash in-game, more than one peep tends to die, after all.

The most common occurrence in regular gameplay is probably from poorly designed dinghy slides. While that's not too common for an experienced player, I think it does probably happen fairly often with newer players.

**Comment by Gymnasiast** [comment]
Dinghies seat two riders, last time I checked.

**Comment by ocalhoun6** [comment]
Oh, lol, nevermind then.
