### ISSUE TITLE
hovered values in finance graphs very hard to read when overlapping timeline axis

### ISSUE THREAD

**Issue by cheweytoo** [OpenRCT2/OpenRCT2#11285]
**OS:** Linux x64
**Version:** dev
**Commit/Build:** 0cbd700

When the hovered value in a finance graph overlaps the timeline axis, it is very hard to read.
Some kind of background color/shading or repositioning would probably be helpful here.

- Reproducible in RCT2 (vanilla)?
No, its a new OpenRCT2 feature

- Specific to multiplayer?
No.

**Steps to reproduce:**
1. Have a very low-incline finance graph.
2. Hover over it.

**Screenshots / Video:**
![openRCT2_finance_hover](https://user-images.githubusercontent.com/29800630/79116716-85fa8200-7d89-11ea-864a-629aa65a23d5.png)

**Comment by AaronVanGeffen** [comment]
We could easily apply a white outline. However, I agree repositioning the value to be below the curve in such cases would probably be the better solution.

**Comment by pRizz** [comment]
@AaronVanGeffen Yes, I can give it a try

**Comment by cheweytoo** [comment]
Funnily enough, the screenshot here is from the same park as the one in https://github.com/OpenRCT2/OpenRCT2/pull/22414#issuecomment-2269946030

Thanks a lot, @mrmbernardi!
