### ISSUE TITLE
Tweak scream amount

### ISSUE THREAD

**Issue by Richard-L** [OpenRCT2/OpenRCT2#11293]
OpenRCT2, v0.2.5-127-g0cbd70029 (0cbd700 on develop) provided by GitHub
Windows 7 (x86-64)

Some ideas I had posted here: https://github.com/OpenRCT2/OpenRCT2/issues/11070#issuecomment-609507171

> Muting is a bad idea I agree, but the screaming should be tweaked. This has been brought up on both the RCF discord and in the project's new own server too:
> 
> > Making it so they don't scream over the slightest incline? Don't get me wrong, it's hilarious, but jesus christ they can get loud
> 
> The immediate parameters that would come to mind are:
> 
> * how long/deep is the drop (height difference)
> * how many peeps are on the train
> 
> So for example if the drop is very short, or not deep, and the train only has 4-6 peeps on it, the likelihood for a scream is 0-10%. And so forth...

Thanks for considering.

**Comment by duncanspumpkin** [comment]
Is this actually still an issue. We fixed the bug in the scream amount. All of these parameters are sort of taken into account as well

**Comment by annoyingdroid** [comment]
If that's the case then no problem. May want to go ahead and close the issue though

**Comment by duncanspumpkin** [comment]
Have a look into it and see what you think. The scream generation code isn't the easiest to follow. This issue was original created before the bug fix but perhaps there is still tweaking to the generation that should be done. I don't play with sound on so maybe I'm not the best to speak on this.

**Comment by Richard-L** [comment]
I think it's definitely much improved. [This park](https://www.nedesigns.com/park/4775/sommerrodelbahn-zullerhorn/) served as a decent example as it has single car coaster trains with a max of 2 peeps per train, and lots of small little drops where there would always be a scream which felt too much. Now it's much more downtoned.

Is something like the height difference of a drop a factor for scream likelihood right now? Could be worth considering. I can look for more example parks, or this could also just be closed.

**Comment by duncanspumpkin** [comment]
At present the vehicle has to be at a certain angle and speed to produce a scream. The number of guests on a ride effects the chance of a scream.

**Comment by duncanspumpkin** [comment]
You could also consider the g forces when creating a scream

**Comment by ocalhoun6** [comment]
> At present the vehicle has to be at a certain angle and speed to produce a scream. The number of guests on a ride effects the chance of a scream.

The number of guests on the ride, or the number of guests on that train?

Because if it's really the total number of peeps on the ride, that might explain why rides with lots of very small trains were causing an inordinate amount of screams. Because each train only has 2 peeps on it ... but if there's 50 peeps overall on the ride, that would skew such an equation toward making screams any time one of the small trains went down a small drop. And since there's lots of trains, drops are _very_ frequent.

**Comment by duncanspumpkin** [comment]
on the train sorry

**Comment by duncanspumpkin** [comment]
`totalNumPeeps >= static_cast<int32_t>(r % 16)`
`totalNumPeeps` is the amount on the train.
`(velocity >= 0x2C000)` speed of the train must be at least this
```
            if (vehicle2->vehicle_sprite_type < 1)
                continue;
            if (vehicle2->vehicle_sprite_type <= 4)
                goto produceScream;
            if (vehicle2->vehicle_sprite_type < 9)
                continue;
            if (vehicle2->vehicle_sprite_type <= 15)
                goto produceScream;
```
One of the vehicles on the train must be at a certain angle. `vehicle_sprite_type` is poorly named it is the angle of the vehicle.

**Comment by duncanspumpkin** [comment]
Rides can choose between 4 different types of screams one of them is no scream

**Comment by ZxBiohazardZx** [comment]
> `vehicle_sprite_type`

Should this not be refactored to that then? vehicle_angle_type 

assuming this is an ENUM not actual degrees?

**Comment by duncanspumpkin** [comment]
I did start trying to do that but it's an absolute pain. I can't remember now if it's this field but for many fields they are used differently depending on the type. Yes it's an enumeration of sorts not degrees. You can see how it works in our sister project openloco where i was more successful with renaming https://github.com/OpenLoco/OpenLoco/blob/bd6936c9f6eb34cd1b4ec5d04599a74d38a38c96/src/OpenLoco/Entities/Entity.h#L72

I would suggest we follow that naming convention i.e. pitch, yaw, roll.

**Comment by ZxBiohazardZx** [comment]
from the Discord. could be relevant:

https://github.com/Basssiiie/OpenRCT2-Unity/blob/unity3d/src/openrct2-unity/Assets/Scripts/Tracks/TrackFactory.cs#L279

**Comment by Gymnasiast** [comment]
Closing as the scream issue was fixed.

**Comment by jez9999** [comment]
I don't agree that this has been fixed, I still have to turn sound FX way down on many parks because of the damn guests screaming constantly on certain coasters.  I would vote for a configurable sounds system where you can just turn the sound off, or replace it with something less jarring.

**Comment by IntelOrca** [comment]
@jez9999 you can now do that with asset packs, they are already now available in develop.

**Comment by jez9999** [comment]
@IntelOrca Care to link one that quiets the screams?

**Comment by IntelOrca** [comment]
@jez9999 you will need to create one yourself or find someone to create one for you.

**Comment by jez9999** [comment]
OK, can you link some documentation on creating asset packs then?  I can't find much about it on Google.

**Comment by IntelOrca** [comment]
There isn't any documentation yet. The best example is here https://github.com/OpenRCT2/OpenSoundEffects/blob/master/openrct2.sound/openrct2.sound.json.

You have to create this json file and put it in a zip file with the assetpack extension. This then goes in your assetpack folder in the OpenRCT2 user content folder.

You might be able to get help with this on the Discord channel for open sound and music.

**Comment by jez9999** [comment]
I see that file seems to be for open source sound FX.  Is there eventually going to be a JSON file intended to give the original game's sound FX?

**Comment by IntelOrca** [comment]
@jez9999 that already exists:

https://github.com/OpenRCT2/objects/blob/master/objects/rct2/audio/rct2.audio.base.json
