### ISSUE TITLE
Unable to advertise server (500): Retry with ipv4 only.

### ISSUE THREAD

**Issue by Lapraniteon** [OpenRCT2/OpenRCT2#11298]
**OS:** Windows 7 Ultimate SP1
**Version:** OpenRCT2 0.2.5
**Commit/Build:** 4f6e77e

Whenever I try to start my OpenRCT2 server from the command line, I get this error. I think to solve it I have to force the server to host on ipv4? The server, however, still shows up locally. The issue also showed up in OpenRCT2 0.2.4.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**
1. Execute command _openrct2 host communitymultiplayer.sv6 --port 11753 --headless --password notactuallythepassword_

**Screenshots / Video:**
![18](https://user-images.githubusercontent.com/57918882/79324483-00550e80-7f10-11ea-8b65-330c5a573528.PNG)

**Save game:**
[communitymultiplayer.zip](https://github.com/OpenRCT2/OpenRCT2/files/4480414/communitymultiplayer.zip)

**Comment by janisozaur** [comment]
Can you try with a build from https://github.com/OpenRCT2/OpenRCT2/pull/11296?
