### ISSUE TITLE
OpenRCT2 doesn't work on Windows Vista anymore

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#11294]
**OS:** Windows Vista

We advertise Windows Vista support, but ever since https://github.com/OpenRCT2/OpenRCT2/pull/10642 it is not possible to launch due to new symbol `BCryptDeriveKeyPBKDF2` from WinNT6.1 now required.

The symbol is required from https://github.com/nih-at/libzip/blob/9bd28f945c383b9c014ac851d932ef3cb10c009f/lib/zip_crypto_win.c#L96 introduced in https://github.com/nih-at/libzip/commit/164097f934d6f113d585d44c825cff4db00ecf8e

**Comment by AaronVanGeffen** [comment]
They even have a define for it, just not taking Windows Vista into account:

https://github.com/nih-at/libzip/blob/9bd28f945c383b9c014ac851d932ef3cb10c009f/lib/zip_crypto_win.c#L83

**Comment by janisozaur** [comment]
A define wouldn't do us any good, it likely targets some latest Windows version.

**Comment by janisozaur** [comment]
https://github.com/microsoft/vcpkg/pull/10784 and https://github.com/mitzal/vcpkg/pull/1

**Comment by IntelOrca** [comment]
@janisozaur Looks like you're already on top of this 😃

**Comment by janisozaur** [comment]
That's as far as I will go. I will leave updating our libs to you.

**Comment by janisozaur** [comment]
https://github.com/microsoft/vcpkg/pull/10784 got merged
