### ISSUE TITLE
Suggestion: Add Powered Launch and Reverse-incline Launched Shuttle modes to Stand-up Roller Coaster

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#11300]
**OS:** Windows 10
**Version:** 0.2.5
**Commit/Build:** 174a480

In RCT1, the Steel Stand-up Roller Coaster has the reverse-incline launched shuttle and powered launch modes, which the Stand-up Roller Coaster doesn't have in RCT2 and OpenRCT2. This means, unless you have the "Show all operating modes" cheat on, building a stand-up coaster design from RCT1 that was constructed with either one of these operating modes wil result in an untestable track design due to the operating mode reverting to Continuous circuit mode in OpenRCT2, thus resulting in a "Track is not a complete circuit" message (that is, if the design in question wasn't already built as a complete circuit).

As reference, the Inverted Roller Coaster regained its powered launch mode back in 0.2.2 due to also having had said operating mode in RCT1. It has a minimum launch speed of 24km/h and a maximum launch speed of 96km/h, which the Steel Stand-up Roller Coaster also has in RCT1.

- Reproducible in RCT2 (vanilla)? **Yes**, as RCT2 vanilla doesn't have reverse-incline launched shuttle and powered launch modes for the Stand-up Roller Coaster either
- Specific to multiplayer? **No**

**Screenshots / Video:**
This is a screenshot of the stand-up coaster with the powered launch mode selected in RCT1.
![RollerCoaster Tycoon 4_15_2020 08_37_20](https://user-images.githubusercontent.com/61885939/79358286-dd1d6580-7ef5-11ea-9995-1759c999f269.png)
Here is what happens if you build a shuttle coaster-style stand-up coaster design from RCT1 in OpenRCT2 and try to test it.
![Test Park 2020-04-15 09-03-26](https://user-images.githubusercontent.com/61885939/79359937-10f98a80-7ef8-11ea-842b-518267bc901d.png)

**Comment by Fred-1044276** [comment]
@Gymnasiast Would you mind looking into this? Also, when the new save format comes, I expect that we will also be able to use the classic trains and vehicles from RCT1, including but not limited to the classic corkscrew coaster trains (which can go from 1 to 8 cars per train) and the 2-seater inverted coaster trains so that we don't have to fallback to the compact inverted coaster trains anymore. More RCT1 compatibility wouldn't hurt.

**Comment by Gymnasiast** [comment]
You can open a PR for this. It's quite easy to add operating modes to ride types.

As for the classic vehicles: the new save format has little to do with it, really. It's just that it's a hell of a job finding all the frame numbers and putting them in the correct order. But it would be possible now, and it's not terribly difficult to do from a technical point of view: copy the JSON file of the RCT2 counterpart, modify the flags that say which track pieces it can handle if needed (since RCT1 did not have sloped banked turns) and fill in the proper sprite IDs.

> More RCT1 compatibility wouldn't hurt.

It wouldn't. As mentioned above, you could help with that.

**Comment by Fred-1044276** [comment]
I know how to do a pull request (I've done at least one for the RCT2 WW and TT object fixes; it's still open), but what exactly is the file that I should edit to add the powered launch and reverse-incline launched shuttle modes to the stand-up coaster?

**Comment by Gymnasiast** [comment]
This table specifically: https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/ride/RideData.cpp#L995

**Comment by tupaschoal** [comment]
Solved by #11301
