### ISSUE TITLE
Ride that has never opened is shown as favorite ride of many guests

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#11315]
**OS:** [Windows 10]
**Version:** [0.2.5]
**Commit/Build:** [d342423]

From what I could see in a quick scan of the code, the guests favorite ride gets set when they exit a ride. This ride has never opened but is shown as the favorite ride of 74 guests.

![image](https://user-images.githubusercontent.com/6469413/79568371-0553c280-80b6-11ea-8608-ded5739b4497.png)

[_GuestFavoriteCount.zip](https://github.com/OpenRCT2/OpenRCT2/files/4492811/_GuestFavoriteCount.zip)

**Comment by deurklink** [comment]
It looks like the number stays at 74, even when I remove all guests from the park.

**Comment by Gymnasiast** [comment]
The only odd thing I have been able to find is that `ride_update_favourited_stat()` looks at all peeps, not just guests.

**Comment by deurklink** [comment]
Guess what happens when we add an employee to the park? The number increases by 1

**Comment by duncanspumpkin** [comment]
Staff hire new is not setting the value to null. Also we should fix the ride to only look at guests.

**Comment by James103** [comment]
Could it be that the ride you built has a ride ID that happens to be the same ID that staff set their favorite ride to on new hire?
