### ISSUE TITLE
Space rings change colors and show different sprites

### ISSUE THREAD

**Issue by RoelerCoaster** [OpenRCT2/OpenRCT2#11325]
**OS:** Windows 10
**Version:** v0.2.6-19-gc17127f65
**Commit/Build:** c17127f

When operating, space rings change color and sometimes show a copletely wrong sprite, such as a wall or another piece of decoration.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Build space rings
2. Watch them operate

**Screenshots / Video:**

![spacerings1](https://user-images.githubusercontent.com/5968886/79616763-19271500-8106-11ea-814f-9edbeabd5d0b.gif)

**Comment by Gymnasiast** [comment]
The colours seem to match the ones of the guests' clothes.

**Comment by Gymnasiast** [comment]
https://github.com/OpenRCT2/OpenRCT2/commit/fd69886350f24a8b0b6ce547d564f427b57c9db3#r38583374

**Comment by Gymnasiast** [comment]
@RoelerCoaster Can you try out #11338 ?
