### ISSUE TITLE
Empty / Blank scenario menu when loading RCT2 Triple Thrill using OCT2 on Mac

### ISSUE THREAD

**Issue by shishirm** [OpenRCT2/OpenRCT2#11329]
**OS:** Mac OSX 10.15.2
**Version:** Version 0.2.5 (174a48087)

When loading RCT2 Triple Thrill downloaded via Steam on my Mac via ORCT2, I am unable to get any of the default scenarios to show up. The screen is basically blank. I know all the assets exist as I can go into the scenario editor and I see all the rides there.

**Steps to reproduce:**
1. Open up ORCT2 on a Mac device. The original RCT2 was downloaded via the Steam console.

**Screenshots / Video:**
https://imgur.com/a/rNrKjK9

**Comment by tupaschoal** [comment]
- Is this the first time you try playing OpenRCT2? If not, what was the last time it worked?
- Have you tried doing "Verify integrity of game files" on the properties of the game on Steam?

**Comment by shishirm** [comment]
Turns out it was an incomplete download from Steam. I wasn't able to "Verify integrity of game files" as the file was not installed and only downloaded. But deleting the repo and re-downloading it seemed to do the trick.

Thank you so much for the suggestions!
