### ISSUE TITLE
Completely offline building for packaging

### ISSUE THREAD

**Issue by PureTryOut** [OpenRCT2/OpenRCT2#11339]
I'm the OpenRCT2 maintainer for Alpine Linux. Currently to build OpenRCT2 I have to provide the build system network access, seemingly to download some g2 thing? This isn't much of a problem because it is possible with a simple switch, but in an effort to make all our packages reproducible, we will have to turn off network access in the future. I'm trying to prepare at least the packages I maintain for that.

For GTest it was easy to just use `-DSYSTEM_GTEST=ON` and installing gtest, but I'm not sure why it still tries to download something for g2, it seems that is built already by the build system?

**Comment by janisozaur** [comment]
For g2 there is nothing to be downloaded and we exercise fully offline builds with launchpad PPA, you can find the build definition here: https://code.launchpad.net/~openrct2/+recipe/openrct2-nightly

**Comment by PureTryOut** [comment]
I... Don't understand the Launchpad UI at all... What can I do with that build definition? I don't see the commands being run for a build there anywhere?

**Comment by janisozaur** [comment]
Check https://github.com/OpenRCT2/OpenRCT2/pull/7189 and #7310

**Comment by PureTryOut** [comment]
But that's just downloading title-sequences and objects before you start, that's already happening and not what I meant.

Currently if I compile OpenRCT2 without network access I get the following:

```
CMake Error at cmake_install.cmake:52 (file):
  file DOWNLOAD HASH mismatch

    for file: [/home/bart/Git/alpine/aports/community/openrct2/src/OpenRCT2-0.2.6/build/testdata/replays/replays.zip]
      expected hash: [4a2cae6c6dbd54e8c0a892aa6327540f6f5108b1]
        actual hash: [da39a3ee5e6b4b0d3255bfef95601890afd80709]
             status: [6;"Couldn't resolve host name"]



ninja: job failed: cd /home/bart/Git/alpine/aports/community/openrct2/src/OpenRCT2-0.2.6/build && /usr/bin/cmake -P cmake_install.cmake
ninja: subcommand failed
```

**Comment by Gymnasiast** [comment]
Right, those are the replay tests. Those haven't got anything to do with `g2`.

I think it should be possible to disable those tests, though I'm not 100% sure.

**Comment by PureTryOut** [comment]
Well if I knew the test name, that would just be a `ctest -E "name of test"`, but the name doesn't seem to be mentioned.

`g2` was just a guess as it just finished something with it before.

**Comment by janisozaur** [comment]
@PureTryOut you're not populating the replays, that's why it is trying to download them.

**Comment by PureTryOut** [comment]
Well are there any instructions on how to do that?

**Comment by janisozaur** [comment]
No, we will welcome documentation fixes you provide.

**Comment by janisozaur** [comment]
But you can use the launchpad recipe contents as a reference. It nests the data in expected places then follows Debian build rules.
