### ISSUE TITLE
Sound issue in game and in menu

### ISSUE THREAD

**Issue by Duvelthehobbit** [OpenRCT2/OpenRCT2#11340]
**OS:**Windows 10
**Version:** 0.2.6-42 ge2be89648
**Commit/Build:** e2be896

The ingame sound/music does not work when the sliders in the sound options are fully to the right. This happened randomly but the bug is reproducible. Attached are videos of the issue.
**Steps to reproduce:**
1. Open game (and open a park)
2. open sound options
3. move slider.
4. If slider is not all the way to the right, no sound should play.

**Screenshots / Video:**
menu: https://youtu.be/VANwPm54z1E
in game: https://youtu.be/MOa-2_uIsIk

**Comment by duncanspumpkin** [comment]
@tupaschoal possibly another cast issue.

**Comment by tupaschoal** [comment]
I'm on it, bisecting...

**Comment by tupaschoal** [comment]
Culprit is #11136
