### ISSUE TITLE
Using remove all guests cheat freezes the game

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#11343]
**OS:** [Windows 10]
**Version:** [0.2.6]
**Commit/Build:** [3bf316e]

1. Use remove all guests cheat in any park
2. Game will freeze

**Comment by tupaschoal** [comment]
Ok, just for reference, there have to be guests in the park 😛

**Comment by duncanspumpkin** [comment]
Argh ffs I know the reason.

**Comment by duncanspumpkin** [comment]
I'll fix this in a sec.

**Comment by tupaschoal** [comment]
Culprit is https://github.com/OpenRCT2/OpenRCT2/commit/401504aff958b8a84fcea835613b8d7ae1e0ef3a, but you know that already, right @duncanspumpkin ?
