### ISSUE TITLE
Broken Russian language in android builds

### ISSUE THREAD

**Issue by Jackthe3rd** [OpenRCT2/OpenRCT2#11351]
**OS:** [Android 8 arm (emui 8)]
**Version:** [0.2.6]
**Commit/Build:** [2ef7741]

Russian language is a broken mess. It's half english and half broken

**Steps to reproduce:**
1. Open the game
2. Select Russian in language option
3. Enjoy

**Screenshots / Video:**
![Screenshot_20200419-130753](https://user-images.githubusercontent.com/58362788/79681133-b6d32f00-8241-11ea-8d93-b3d1f510719f.jpg)
![Screenshot_20200419-130806](https://user-images.githubusercontent.com/58362788/79681134-c05c9700-8241-11ea-96ee-75a8b3e7c877.jpg)
![Screenshot_20200419-130922](https://user-images.githubusercontent.com/58362788/79681135-c3578780-8241-11ea-80c3-d2e4e4639045.jpg)

**Comment by duncanspumpkin** [comment]
https://github.com/OpenRCT2/Localisation Russian is currently not maintained. If you feel up for it, it would be great if you could help contribute to the translation. If you do please check out the localisation project https://github.com/OpenRCT2/Localisation
