### ISSUE TITLE
Coding style causes undefined behavior

### ISSUE THREAD

**Issue by brenoguim** [OpenRCT2/OpenRCT2#11354]
The coding style wiki mentions this section:
 ```
/// Template parameters should be prefixed with `_T`, e.g. `_TFoo`
template<typename _TGenerator, typename _TSizeType = size_t>
void take(_TGenerator g, _TSizeType num)
{
}
```

Notice that all identifiers that start with underscore followed by a capitalized char (like `_T`) or identifiers that start with double underscores (`__t`) are reserved and cannot be used. They reserved these identifiers to be able to create macros in the standard library.
See: http://eel.is/c++draft/lex.name#3

So, some other options are:

1. Just use plain `TGenerator`. It's usually easily deducible by the context.
2. Place the underscore after the `T` like `T_Generator`
3. Place the underscore after the whole type name `TGenerator_`

**Comment by Gymnasiast** [comment]
Summoning @IntelOrca and @janisozaur .

**Comment by janisozaur** [comment]
The docs should obviously be updated.

**Comment by tupaschoal** [comment]
And what do we go with? Personally I like `TGenerator`, but would also take `T_Generator`. Not so fond of the last option

**Comment by janisozaur** [comment]
Oh I don't really care. TGen looks fine to me.

**Comment by tupaschoal** [comment]
@IntelOrca also voiced he uses `TGenerator`. I went ahead and updated the WIki.
@brenoguim feel free to update the code base if you feel like it :D
