### ISSUE TITLE
Shortcut key list - Wrong order on function Copy / Paste

### ISSUE THREAD

**Issue by WackedSwe** [OpenRCT2/OpenRCT2#11370]
So, I sat playing trying to copy using CTRL+C and CTRL+V, but they've been switched. 

If arranged as the picture it works. Not sure if it is a display issue or a switcharoo in the code that caused this. Was working as intended prior to:  0,2,6-113

![CopyPaste](https://user-images.githubusercontent.com/59372559/79724151-5696c880-82e7-11ea-9d2c-81f3746612fd.png)

**Comment by duncanspumpkin** [comment]
src/openrct2/interface/Window.h

Also defines the widx index. That should have been updated in https://github.com/OpenRCT2/OpenRCT2/pull/11358

This is an easy two line fix. But it's an example of poor layout of code that was a fudge at the time.

**Comment by WackedSwe** [comment]
Roger! =D
