### ISSUE TITLE
Discord-RPG update to GameSDK

### ISSUE THREAD

**Issue by flip111** [OpenRCT2/OpenRCT2#11380]
cmake tells me this
```
No discord-rpc detected, to enable clone discord-rpc to root directory: /home/flip111/programs/src/OpenRCT2
```

When i look at github for discord-rpg it says it's been deprecated. https://github.com/discord/discord-rpc

**Comment by Gymnasiast** [comment]
Discord GameSDK has a licence that is incompatible with the GPL, meaning we cannot _legally_ use it.

This is a problem for about every open source game that wants to use it, but Discord has ignored everyone who pointed that out.
