### ISSUE TITLE
Building a path through walls does not always remove the walls

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#11405]
**OS:** Ubuntu 20.04
**Version:** 0.2.6+
**Commit/Build:** cfd94d4fa54525b3402093d2dc1a83dcb58dde49

![afbeelding](https://user-images.githubusercontent.com/1478678/79997695-1fc4dc00-84ba-11ea-9346-ffdcea4b69ff.png)

![afbeelding](https://user-images.githubusercontent.com/1478678/79997740-29e6da80-84ba-11ea-823a-d61d5c8fdf43.png)

**Comment by tupaschoal** [comment]
Might this be an unwanted side effect of https://github.com/OpenRCT2/OpenRCT2/pull/11306 ?

**Comment by Gymnasiast** [comment]
Doubt it, but bisecting should provide the answer.
