### ISSUE TITLE
"Too high for supports" cheat

### ISSUE THREAD

**Issue by runelaenen** [OpenRCT2/OpenRCT2#1140]
Hi,

would it be possible to disable the 'too high for supports' errors?

Someone asked this on my forums.
https://openrct.net/forum/topic/14/too-high-for-supports#p103

Thanks,
Rune

**Comment by trigger-death** [comment]
It looks like this isn't possible yet, but once the ride construction window is further compiled it will be.

**Comment by IntelOrca** [comment]
Implemented in e068c586a1d8319be6f58160a4540ea21d1179de
