### ISSUE TITLE
Request for cheat so guests SPAWN with $1000

### ISSUE THREAD

**Issue by IceKnight366** [OpenRCT2/OpenRCT2#11413]
Windows 8
0.2.5

Can a cheat be added that allows all guests to _spawn with_ $1000 instead of only being able to give guests _who are already in the park_ $1000?  This is a very important cheat that allows people who like to play with park entry fee game styles the ability to build large parks and still make a profit.  Because a large park with 200 staff will cost an average or $13,000 a month, park entry fees need to be set at $650+ in order to make a profit.  Granted, this is dependent upon having a full park of 8,000 guests, meaning you have to wait for one guest to leave in order for the next guest to come into the park.  This entails that only 15-25 guests enter your park a month, which really hurts your income.  But even if you didn't have a full park 1) prices would still need to be at $350, and eventually your park would get full and have to go up to $650.

**Comment by ocalhoun6** [comment]
If you're going to be using cheats anyway, why not just give yourself some free money?

**Comment by IceKnight366** [comment]
> 
> 
> If you're going to be using cheats anyway, why not just give yourself some free money?

Why would I use cheats?  I don't _want_ to use cheats.  Nowhere did I say I wanted to.  Rather _have_ to use cheats because then I would always be in the red and couldn't progress the game fairly.  So ironically, the only way you can play entry fee games without cheating is by cheating.  Do you know another way around this?

**Comment by duncanspumpkin** [comment]
Would be doable as a plugin.

**Comment by Gymnasiast** [comment]
You can already change the amount that guests spawn with. Click the yellow shovel and select "Scenario options" and then go to the second tab, where you can change the amount of money that guests spawn with.

**Comment by IceKnight366** [comment]
> You can already change the amount that guests spawn with. Click the yellow shovel and select "Scenario options" and then go to the second tab, where you can change the amount of money that guests spawn with.

Thanks!  Huge help.  What about a way to freeze guest stats, like happiness?

**Comment by Gymnasiast** [comment]
That sounds like something that would best fit a plug-in. I wouldn't be surprised if someone would write one once the plug-in system is merged.
