### ISSUE TITLE
UI/Zoom improvements: (at mouse pointer & further)

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#1141]
I would like to have an option to zoom at mouse pointer instead of the in-center zoom.

~~Also an additional further zoom level would be really handy (2x current max zoom)~~

~~I would also like to see an option to scale UI elements, perhaps using values 1.0 - 4.0 with 0.25 per step with independent settings for tooltips, text and icons~~

**Comment by Gymnasiast** [comment]
Point 2 and 3 are already in the Issues. Point 1 isn't.

**Comment by dustinpaluch** [comment]
@Gymnasiast sorry, could you point me to the existing issue for point 3? I tried searching for various combinations of "scale UI" but couldn't find anything.

**Comment by duncanspumpkin** [comment]
#775 for closer zoom levels.

**Comment by Gymnasiast** [comment]
@dustinpaluch : Oh, that's odd. It's the most requested feature but apparently all of those requests were done via Gitter, Skype, Reddit, etc., since I can't find it in the issues.

**Comment by dustinpaluch** [comment]
@Gymnasiast would it be helpful to create an issue specifically for the most requested feature so we don't get any more duplicates?

**Comment by AaronVanGeffen** [comment]
I believe this has been resolved with #4146.
