### ISSUE TITLE
Possible misuse of comma operator

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/OpenRCT2#11414]
**OS:** macOS
**Version:** 0.2.6+
**Commit/Build:** c17127f65b854e3d1b2028b588dc05a4a9092f82

Xcode brings two instances of 'possible misuse of comma operator' to light. Both stem from  5ba5daca42b44aabc4803a7d3f89ae08e67d6fb5, but were not introduced by this commit:

```diff
-    while ((currentEntry = window_scenery_tab_entries[tabIndex][totalItems]),
-           currentEntry.EntryIndex != WINDOW_SCENERY_TAB_SELECTION_UNDEFINED)
+    while ((currentEntry = window_scenery_tab_entries[tabIndex][totalItems]), !currentEntry.IsUndefined())
```

```diff
     while ((currentSceneryGlobal = window_scenery_tab_entries[tabIndex][sceneryTabItemIndex]),
-           currentSceneryGlobal.EntryIndex != WINDOW_SCENERY_TAB_SELECTION_UNDEFINED)
+           !currentSceneryGlobal.IsUndefined())
```

I think the comma should indeed need be replaced with an `&&` operator in both cases. Thoughts?

**Comment by brenoguim** [comment]
I suspect this might actually be fine. I mean, if the comma is replaced by &&, then this implies that "currentEntry" must be both not zero and not "WINDOW_SCENERY_TAB_SELECTION_UNDEFINED".

What does "zero" mean in this context? Maybe if zero is the first "EntryIndex" that could be fine

**Comment by Gymnasiast** [comment]
Fixed by https://github.com/OpenRCT2/OpenRCT2/pull/12919.
