### ISSUE TITLE
Shortcut key for "Disable/Enable clearance checks"

### ISSUE THREAD

**Issue by Richard-L** [OpenRCT2/OpenRCT2#11422]
> OpenRCT2, v0.2.6-146-g619b06254 (619b062 on develop) provided by GitHub
> Windows 7 (x86-64)

This would be a total game changer for a lot of people building parks on NEDesigns.com where zero-ing clearances is 100% common practice.

Most people leave clearance checks disabled per se so as not having to re-enable them constantly. This leads to problems as you can imagine.

If it wouldn't mean too much trouble for someone to add shortcut-ability for this setting, it would mean _a lot_ to us. Thank you.

**Comment by janisozaur** [comment]
This can be used as reference: https://github.com/OpenRCT2/OpenRCT2/pull/10341

One caveat here is the option is only made accessible with debug/cheats enabled, but I'm not sure if this should still hold for a shortcut.

**Comment by janisozaur** [comment]
Somewhat related, do we already have some indication disabled clearances mode is on? Perhaps this should be also taken into account by displaying a chat-notification of mode change. @Richard-L what's your take on this?

**Comment by Richard-L** [comment]
@janisozaur yes you are very right on the notification, was also thinking about this later.

Back in the years when this cheat first became available via trainers, they would display custom notifications down in the middle of the screen with a beep:

"Clearance checks disabled/enabled".

I believe it was the same with 8cars for example.

I think they are still useful, and also available from a console command now.

Alternatively, since there is the multiplayer chat system now, this would also be a great place for notifications. Some hacks back in the day needed a combination of game pausing and zero clearancing, and while I'm not sure how valid they still are, I reckon the MP chat has the advantage that messages are immediately printed if the game is paused.

Another idea, perhaps in addition, might be to give the white sprite preview a different colour while clearance checks are disabled. Perhaps a reddish colour to signal the user should be careful.

**Comment by Umdlye** [comment]
A badge on the cheat toolbar button would be ideal IMO, similar to how the player count is displayed on the multiplayer toolbar button. It's persistent and unobtrusive.

**Comment by janisozaur** [comment]
@Umdlye this was my idea as well, for persistent notification that's good, but also change could be advertised properly

**Comment by thiebert** [comment]
I'd like to try to work on this, but I don't have immediate availability. If anyone wants to take it in the meantime, I won't be offended.

**Comment by michielbos** [comment]
I'd like to pick up this issue if nobody is currently working on it.
