### ISSUE TITLE
Incorrect scenery preview

### ISSUE THREAD

**Issue by Richard-L** [OpenRCT2/OpenRCT2#11428]
> OpenRCT2, v0.2.6-146-g619b06254 (619b062 on develop) provided by GitHub
> Windows 7 (x86-64)

![image](https://user-images.githubusercontent.com/4934209/80161138-b1723d80-85cf-11ea-81b0-98b7a190b5b7.png)
I know that this is an original bug. It only seems to occur on custom scenery. Likely this is a fault on the object creator software's side.

Like with objects that used to be non-exportable, is there something on OpenRCT2's side that can be done to properly display these previews?

Link to source park: https://www.nedesigns.com/park/4363/workbench-2019-by-dr-dirt/

Many thanks.

**Comment by duncanspumpkin** [comment]
Those objects haven't created there sprites correctly. Not much we can do about that. It would be hard to work out which ones needed special code. It would be considerably easier if someone just fixed the object.

**Comment by Richard-L** [comment]
@duncanspumpkin when you say "not correctly", what is the error? I'm afraid people are actively unaware.

**Comment by Gymnasiast** [comment]
This is what these objects include as "preview images", prerendered and all.

There is no way to fix this, except by creating a JSON object that uses `originalId` to override the old, broken one.
