### ISSUE TITLE
feature request: remove corrupt objects below objects being removed

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#11434]
Since they are invisible, corrupt objects can be somewhat tricky to manage. Currently, when an object is deleted, its corrupted object remains. The next time something is built on the tile and the object is higher in the stack than the corrupt object, that something turns invisible automatically, necessitating use of the tile inspector to get rid of it, which is not always the easiest thing if the land tile in question is much higher or much lower than the corrupt object that needs removing.

It would be nice if corrupt objects were removed when the object they are hiding is removed, perhaps with the exception of using the tile inspector.

**Comment by duncanspumpkin** [comment]
That would not be too easy to achieve. We also plan to remove the corrupt tile 'feature' with the new save format replacing it with a flag on the tile element. I feel this would be a lot of effort for not much gain.

**Comment by spacek531** [comment]
If the new save format removes corrupt objects then yes, probably not a lot to gain from this.

**Comment by Gymnasiast** [comment]
Duncan is correct. It will be replaced with an invisibility flag, which will be set on the appropriate elements when importing an SV6.
