### ISSUE TITLE
Scenario editor - Water missing preview

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#1143]
![no thumbnail](http://puu.sh/hXZAR/5adaa8dbc6.png)

Hovering over any item just adds the text; (no image)

I'm running vanilla rct2 but i recall this being fixed in one of the expansion packs.

**Comment by trigger-death** [comment]
This was never fixed in any of the expansion packs. It could be added to draw a water preview though.

**Comment by Gymnasiast** [comment]
Can confirm Robert's comment.
This could be marked 'enhancement' or something similar.

**Comment by Patrik356b** [comment]
trigger-death - i don't know but it does work in a version i have had before.

**Comment by IntelOrca** [comment]
A water preview would cause the map water colours to keep changing when you hover over a different item.

**Comment by Patrik356b** [comment]
@IntelOrca it does not, it just shows an icon, the same used for the water tool.

When i had RCT2 and the expansions on separate disks the water preview was working.
The same images can be found here: http://rct.wikia.com/wiki/Water

**Comment by IntelOrca** [comment]
Can you provide a screenshot as evidence?

From a technical point of view, it can't be done without all the water in the map changing colour when you hover over an item.

**Comment by Gymnasiast** [comment]
@Patrik356b. RCT2 did _not_ have water preview. Full stop. I have played the disk versions for 13 years.

**Comment by Patrik356b** [comment]
@IntelOrca Sure it can. all the fixed version did was slap an image into the preview area in the current window. it did not change anything outside.
As I no longer own the discs i can not provide a screenshot unless i come across the same version or a screenshot of it.

@Gymnasiast There has been a few different disc versions. I did have it.

I have been looking around but there very little screenshots at best of the object selection window.

**Comment by IntelOrca** [comment]
@Patrik356b What you are saying is just not technically possible. The game would never have been able to do that as the water type changes the game palette and it can't possible show more than 256 different colours at the same time.

**Comment by Patrik356b** [comment]
I clearly remember seeing this and i do have photographic memory so this just doesn't seem right to me.

**Comment by Gymnasiast** [comment]
In the (unlikely AFAIC) event you do find it, please do post a screenshot.
Otherwise we'll just consider this an enhancement, rather than a bugfix.

**Comment by IntelOrca** [comment]
This can be re-visited in the future when we have 32bpp graphics.
