### ISSUE TITLE
Android title sequence editor crash

### ISSUE THREAD

**Issue by CrossWayIstaken** [OpenRCT2/OpenRCT2#11443]
**OS:** [Android]
**Version:** [0.2.6]
**Commit/Build:** [baf6f15]

If you try to create new title sequence on android it most likely going to crash.

**Steps to reproduce:**
1. Open title sequence editor
2. Create a new sequence

**Screenshots / Video:**

![titleseqcrash (3)](https://user-images.githubusercontent.com/58362788/80247847-f7df9f00-8698-11ea-84ff-28e92706bef1.gif)

**Comment by YJSoft** [comment]
This can be closed since title sequence editor is now [plugin](https://github.com/OpenRCT2/title-sequence-editor)

**Comment by CrossWayIstaken** [comment]
Eh, last time I played android version plugins weren't available there

**Comment by YJSoft** [comment]
Plugins still not available since duktape is not ported to [openrct2-dependencies-android](https://github.com/OpenRCT2/openrct2-dependencies-android).(See #11499)

So at least android versions will not crash due to title editor.
