### ISSUE TITLE
Object selection window cut off object names

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#11455]
In the object selection window, objects and things have their names cut off as if there were a second column of information. This makes sense for rides, but not for other tabs. This makes selecting small scenery problematic for example, because the names are often long. I have to do my selection purely by hovering my cursor over all the objects and watching the image preview.

Using version 0.2.6 6c3c857 on windows 8.

**Comment by tupaschoal** [comment]
@Liampie can you please add the screenshot you showed on discord? It's very useful

**Comment by Liampie** [comment]
Surely!

![unknown](https://user-images.githubusercontent.com/19242088/80279297-f3e56880-86fc-11ea-93c6-c1da0d25eac6.png)
