### ISSUE TITLE
Ride with unsuitable track cannot be opened even with "Enable all drawable track pieces" cheat enabled.

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#11450]
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** c5d877f

As requested by @Gymnasiast on #10923, which allowed for testing of rides with unsuitable track pieces, I have opened this issue. This issue pertains hypercoasters and hyper-twisters with inversions being blocked from being openable even if the "Enable all drawable track pieces" cheat is active. The Ride.cpp file is missing a check for the "Enable all drawable track pieces" cheat in the code that determines whether or not a ride can be opened, but the code that determines whether or not a ride can be tested/simulated still has said cheat mentioned.

- Reproducible in RCT2 (vanilla)? **No**
- Specific to multiplayer? **No**

**Steps to reproduce:**
1.  Activate the "Enable all drawable track pieces" cheat.
2. Build a Hypercoaster or Hyper-Twister and include any inversion (e.g. vertical loop).
3. Attempt to open it. It should say "Can't open [ride name]... Track unsuitable for type of train" (will instead say "Track is not a complete circuit" if the track isn't already a complete circuit unless the Powered launch or Reverse-Incline launched shuttle modes are selected).
4. This can also be done by using "Show vehicles from other track types" and putting any of the Hyper-Twister train types on a coaster that has inversions.

**Screenshots / Video:**
![Harpy Gardens 2020-04-13 11-09-58](https://user-images.githubusercontent.com/61885939/80267405-9813d480-8655-11ea-9013-8c8a22e69b51.png)

**Save game:**
The following ZIP file includes a custom scenario and a corresponding saved game with the affected coaster.
[Harpy Gardens (hyper-twister fail).zip](https://github.com/OpenRCT2/OpenRCT2/files/4532128/Harpy.Gardens.hyper-twister.fail.zip)

**Comment by Gymnasiast** [comment]
To give a bit of context: #10923 made it possible to _test_ rides with suitable track pieces, but not open them, despite the PR name.
