### ISSUE TITLE
Broken entrance titles

### ISSUE THREAD

**Issue by invalidCards** [OpenRCT2/OpenRCT2#11469]
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** a3e7f09

A commit in the past ~24 hours has broken entrance titles (the rotating banner on the entrance building). They always show dashes in yellow, never changing colour or displaying the attraction name. Queue lines are not affected by this.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Load up a game on the latest commit
2. See that the entrance titles are just dashes.

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/842080/80304805-bc3bf680-87b8-11ea-9f84-8485212eb383.png)

**Save game:**
[Crazy Castle 3.txt](https://github.com/OpenRCT2/OpenRCT2/files/4535103/Crazy.Castle.3.txt)

**Comment by invalidCards** [comment]
Probably caused by the changes in 8936ce6

**Comment by tupaschoal** [comment]
I've bisected and the cause is actually @brenoguim 's a0619d04c
