### ISSUE TITLE
Implement FileWatcher for macOS

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#11473]
Currently the FileWatcher has an implementation for Windows and Linux but not macOS. This is required for plugin hot reloading which is very useful for plugin development.

Also required for #11439.

**Comment by umar-ahmed** [comment]
In lieu of this not being implemented yet for MacOS, is there a way to manually reload a specific plugin or all plugins without relaunching the game?

Wondering if it's as simple as exposing this function to the in-game console?

https://github.com/OpenRCT2/OpenRCT2/blob/73738bbdc8bc47122f62d0cfdad8a9d5d4d8cecd/src/openrct2/scripting/ScriptEngine.cpp#L756
