### ISSUE TITLE
Research funding dropdown not shown in finances window

### ISSUE THREAD

**Issue by rctdude2** [OpenRCT2/OpenRCT2#1148]
Left is research window, right is finances window
![scr8](https://cloud.githubusercontent.com/assets/8041567/7790797/d7943bbe-0260-11e5-9c82-24a88e35e390.png)

**Comment by duncanspumpkin** [comment]
Can't reproduce. They both use the same technique to hide the research dropdown so im a bit surprised by this.

**Comment by rctdude2** [comment]
It may have something to do with 8cars usage with the original game. I've only been able to get it to happen with saves where 8cars was used. I can get it to happen consistently with these two saves: http://highsense.x10.mx/content/other/save.zip

**Comment by danidoedel** [comment]
I could reproduce it this way: Load a park where everything is already researched, open these windows, load a park where something still can be researched and open again these two windows...

**Comment by Gymnasiast** [comment]
My guess is it was/is caused by memory corruption.

Can anyone still reproduce this? The code went through so many changes in those 2 years, it's likely to be "accidentally" solved.

**Comment by rctdude2** [comment]
Just checked with the v0.1.1 release, it is indeed fixed.
![image](https://user-images.githubusercontent.com/8041567/29421325-bf57c254-8342-11e7-8294-a700c24bc9a9.png)

**Comment by Gymnasiast** [comment]
Reportedly, this still happens occasionally. (Reported by Mako_0ne on Discord.)

**Comment by rctdude2** [comment]
I was just able to reproduce this on 6c3c857 (0.2.6 release). This did not happen if the first park is one with research and no money (e.g. Megaworld Park), with no research and no money (e.g. Asia - Great Wall from Wacky Worlds), or with no research and money (made a scenario to test this).
I think it straight up doesn't occur if the first was a scenario and not a save.

scenario with no research and money: [issue1148test.zip](https://github.com/OpenRCT2/OpenRCT2/files/4497148/issue1148test.zip)
1. open a _save_ with all research completed ([Unnamed park.zip](https://github.com/OpenRCT2/OpenRCT2/files/4497150/Unnamed.park.zip))
2. open finances window and switch to funding tab (dropdown is missing because all research is completed)
3. open research window and switch to funding tab (dropdown is also missing for same reason)
4. open a scenario or save with research still available (e.g. Forest Frontiers)
5. open finances window and switch to funding tab (dropdown is incorrectly missing)
6. open research window and switch to funding tab (dropdown is available because research still exists)
The dropdown in 5 remains missing until game restart.

**Comment by duncanspumpkin** [comment]
@rctdude2 thanks for those steps should be easy to fix sounds like a globally initialised variable.
