### ISSUE TITLE
Game crashes upon attempting to test a ride with empty stations (i.e. no entrances and exits)

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#11490]
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** af625f9

Just had this rare crash when building a flying roller coaster with a split station setup (a front loading station and a rear unloading station). Both stations were empty when I tried to test the ride to be prompted to place down entrances and exits, but before the "Can't test Flying Roller Coaster 1... Entrance not yet built" message even appeared, the game ended up crashing. I suspect that it could also happen with other error messages that prevent a ride from being opened (e.g. "Track is not a complete circuit").

- Reproducible in RCT2 (vanilla)? No
- Specific to multiplayer? No

**Steps to reproduce:**
1. Build a custom tracked ride.
2. Attempt to test it while the stations/docking platforms are empty.
3. If the game freezes after attempting to test the ride only to be prompted to place down entrances and exits ("Entrance not yet built"/"Exit not yet built"), the game will eventually crash.

**Dump file**
[393bac54-3f13-4099-a275-1028bfaf0607(af625f9_x86-64).dmp.zip](https://github.com/OpenRCT2/OpenRCT2/files/4537653/393bac54-3f13-4099-a275-1028bfaf0607.af625f9_x86-64.dmp.zip)

**Screenshots / Video:**
Below is a picture of the flying roller coaster I was building when the game crashed on me while trying to test it and get prompted to place down ride entrances and exits.
![Anaconda Jungle 2020-04-26 21-09-01](https://user-images.githubusercontent.com/61885939/80333374-aa7f4100-8802-11ea-9c44-f4df3cef9338.png)

**Comment by janisozaur** [comment]
There shouldn've been `.sv6r`  and `.sv6` files also created, can you upload them too?

**Comment by Fred-1044276** [comment]
Edited the original post to include a zip file with the sv6 and sv6r files also included.

**Comment by janisozaur** [comment]
[af625f9_11490.sv6r.txt](https://github.com/OpenRCT2/OpenRCT2/files/4537907/af625f9_11490.sv6r.txt)

@duncanspumpkin this one starts diverging quickly:
`Different sprite checksum at tick 601 (Replay Tick: 601) ; Saved: a41ab75d6bfcdf3a001345053849b879d67c4f3c, Current: 3f44ebc2ff9d8068fbc2368d088eb8df2aee46c9`

**Comment by duncanspumpkin** [comment]
https://github.com/OpenRCT2/OpenRCT2/issues/11500,
https://github.com/OpenRCT2/OpenRCT2/issues/11501

Looks like a bunch of these crashes are also from this.
