### ISSUE TITLE
Old console commands don't work at headless console since plugin system

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#11494]
**OS:** Ubuntu 18.04
**Version:** 0.2.6
**Commit/Build:** f9909e7

Old console command such as ``help``, ``save_park`` or ``exit`` don't work at headless console.

**Steps to reproduce:**
1. Run ``./openrct2-cli``
2. Type ``help`` or something

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/10726524/80345468-1c5b9700-88a4-11ea-8e84-6a25fde9f0ee.png)

**Comment by IntelOrca** [comment]
The old console commands are deprecated now and can only be executed in the in-game console. What I will do for now is provide a temporary JavaScript function to execute a legacy command until all commands are available in the plugin API.
