### ISSUE TITLE
Cant start up game on last develop

### ISSUE THREAD

**Issue by kanaiva** [OpenRCT2/OpenRCT2#11510]
**OS:** [e.g. Windows 7]
**Version:** [e.g. 0.2.6]
**Commit/Build:** [e.g. 06bbf5d]

When i user the launched to open the games latest developer mode I get an error message 
![unknown-36](https://user-images.githubusercontent.com/64433657/80406266-11b0fa00-88c4-11ea-896a-ad90051f22cd.png)

**Steps to reproduce:**
1. Just use the launcher
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by deurklink** [comment]
Several users on my discord experienced same problem on latest develop version.

**Comment by James103** [comment]
Error message in English: "Can't find access point of procedure GetSystemTimePreciseAsFileTime in DLL KERNAL32.dll" - maybe the DLL can't be found or reads as corrupt?

**Comment by AaronVanGeffen** [comment]
This is the result of the new plugin system using a Windows 8+ symbol. The plugin system depends on a library to interpret JavaScript.

We will investigate and try to solve this as soon as we can.

**Comment by janisozaur** [comment]
When fixing this please also remember to fix https://github.com/OpenRCT2/OpenRCT2/issues/11294
