### ISSUE TITLE
changing operation mode

### ISSUE THREAD

**Issue by bieryan** [OpenRCT2/OpenRCT2#11548]
**OS:** [windows 7]
**Version:** [ 0.2.6-366-]
**Commit/Build:** [e.g. g29fcdb539]  

when a ride is build. and you first change the track type or trains. you cant change the operation mode. as example if  you want a launched looping coaster on a flying coaster track. you need to first change it to launch mode. other wise it wont let you.

**Comment by deurklink** [comment]
What he is trying to say is that the "Show all operating modes" cheat does not allow you to change your ride operating mode to an operating mode it normally does not have anymore.
![image](https://user-images.githubusercontent.com/6469413/80725758-cd13a180-8b03-11ea-8acf-22c50723649f.png)
