### ISSUE TITLE
Crash on Opening (Linux)

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#1154]
http://pastebin.com/raw.php?i=DXP4qUuF
^Crash Dump

**Comment by LRFLEW** [comment]
From the dump, it looks like you're using Wine version 1.4.1, while the latest stable version is 1.6.2. It runs fine for me on Wine 1.6.2 on Mac OS X. I'd recommend trying the newer version to see if that fixes it.

**Comment by PFCKrutonium** [comment]
Kali doesn't seem to have it in the repo's, can you point me at a deb?

**Comment by IntelOrca** [comment]
Is this still an issue?

**Comment by PFCKrutonium** [comment]
No.
