### ISSUE TITLE
Support websocket for plugin

### ISSUE THREAD

**Issue by bnnu** [OpenRCT2/OpenRCT2#11555]
websocket can be used to implement twitch plugins.
(like add money if received donation)

**Comment by IntelOrca** [comment]
Not sure if websocket is the best way to go about this, certainly we will want some way of doing interprocess communication but to reduce security vulnerabilities it will likely be restricted to localhost TCP streams.

I am happy to discuss further in the discord plugin channel.

**Comment by IntelOrca** [comment]
TCP communication is now implemented.
