### ISSUE TITLE
OpenRCT2 does not build on Arch Linux

### ISSUE THREAD

**Issue by ccoors** [OpenRCT2/OpenRCT2#11550]
**OS:** Arch Linux x64
**Version:** 0.2.6
**Commit/Build:** 8798811561b71c7792ac38cd6c14580c2315582b

When building OpenRCT2 on Arch Linux a compilation error occurs:

```
[ 99%] Building CXX object CMakeFiles/openrct2.dir/src/openrct2-ui/windows/ViewClipping.cpp.o
[100%] Building CXX object CMakeFiles/openrct2.dir/src/openrct2-ui/windows/Viewport.cpp.o
[100%] Building CXX object CMakeFiles/openrct2.dir/src/openrct2-ui/windows/Water.cpp.o
[100%] Linking CXX executable openrct2
D.21324]’/home/ccoors/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2-ui/scripting/ScViewport.hpp: In member function ‘moveTo’:
/home/ccoors/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2-ui/scripting/ScViewport.hpp:302:21: error:  may be used uninitialized in this function [-Werror=maybe-uninitialized]
  302 |             return {};
      |                     ^
D.21324 + 4B]’/home/ccoors/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2-ui/scripting/ScViewport.hpp:302:21: error:  may be used uninitialized in this function [-Werror=maybe-uninitialized]
D.21324 + 8B]’/home/ccoors/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2-ui/scripting/ScViewport.hpp:302:21: error:  may be used uninitialized in this function [-Werror=maybe-uninitialized]
lto1: all warnings being treated as errors
lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/openrct2.dir/build.make:1864: openrct2] Error 1
make[1]: *** [CMakeFiles/Makefile2:251: CMakeFiles/openrct2.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Error making: openrct2-git
```
The error message is confusing as it does not contain the variable name.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Try to build the AUR package `openrct2-git`/try to build from source using `cmake .. && make`.

**Comment by AaronVanGeffen** [comment]
Current develop, 8798811561b71c7792ac38cd6c14580c2315582b, builds fine over here (on Arch Linux). Perhaps the problem has been solved in the mean time?

**Comment by MeindertKempe** [comment]
I am having the same issue, it doesn't happen if you remove `-DCMAKE_BUILD_TYPE=RelWithDebInfo` from the cmake arguments, if that helps.

**Comment by ccoors** [comment]
Indeed, a Debug Build works, a Release build does not.

**Comment by Ruedii** [comment]
Might be a flag issue with certain Arch setups.

Anyhow, if it doesn't happen in CLang, use CLang.  

I hate to be a CLang fanboy, but I seriously think CLang is now the better compiler.

**Comment by duncanspumpkin** [comment]
It's a bit of a strange one to error on. That is creating a null optional. Can you check to see if it builds if you were to change it to using the other syntax for a null optional `return std::nullopt`

**Comment by duncanspumpkin** [comment]
https://stackoverflow.com/questions/57964217/stdoptional-construct-empty-with-or-stdnullopt suggests it's a bug in gcc
