### ISSUE TITLE
Use ScreenCoordsXY on gfx_draw_string_left_wrapped

### ISSUE THREAD

**Issue by tupaschoal** [OpenRCT2/OpenRCT2#11562]
Create an overload of `gfx_draw_string_left_wrapped` on `\src\openrct2\drawing\Text.cpp` with the same name, but that takes a `const ScreenCoordsXY&` object instead of an `int32_t x` and and an `int32_t y` and replace the calls to the `{x ,y}` pair by the one using `ScreenCoordsXY`.

Don't try to do all calls at once, unless it doesn't occur a lot, as this might lead to a huge PR. When we stop using the old function, we can drop it entirely in favour of the `ScreenCoordsXY` alternative.

**Comment by sohiladwani** [comment]
Can I attempt to tackle this?

**Comment by tupaschoal** [comment]
Sure

**Comment by sohiladwani** [comment]
https://github.com/OpenRCT2/OpenRCT2/pull/11776

**Comment by TomasZilinek** [comment]
Guys are you working on this?

**Comment by tupaschoal** [comment]
No, go ahead

**Comment by TomasZilinek** [comment]
Ok, thanks. But I see that there are many calls of gfx_draw_string_left and gfx_draw_string_left_wrapped in the same functions. So I am going to do gfx_draw_string_left first and then this so that there will be no conflicts.

**Comment by tupaschoal** [comment]
Sounds sensible
