### ISSUE TITLE
Use ScreenCoordsXY on gfx_draw_string_right

### ISSUE THREAD

**Issue by tupaschoal** [OpenRCT2/OpenRCT2#11569]
Create an overload of `gfx_draw_string_right` on `\src\openrct2\drawing\Text.cpp` with the same name, but that takes a `const ScreenCoordsXY&` object instead of an `int32_t x` and and an `int32_t y` and replace the calls to the `{x ,y}` pair by the one using `ScreenCoordsXY`.

Don't try to do all calls at once, unless it doesn't occur a lot, as this might lead to a huge PR. When we stop using the old function, we can drop it entirely in favour of the `ScreenCoordsXY` alternative.

**Comment by Aryaman73** [comment]
Hey! I'd like to take this issue on. It's my first time contributing to OpenRCT2, so I was wondering if there were any documents other than [this one](https://github.com/OpenRCT2/OpenRCT2/blob/develop/CONTRIBUTING.md) about contributing to this project. (I couldn't find any details about building the code and testing it, in particular). 

 Awesome project btw 😄

**Comment by tupaschoal** [comment]
There are some things about compiling in our main readme:
https://github.com/OpenRCT2/OpenRCT2/blob/develop/readme.md#32-compiling-and-running

There are also links on our wiki such as [coding style](https://github.com/OpenRCT2/OpenRCT2/wiki/Coding-Style) and [Commit messages](https://github.com/OpenRCT2/OpenRCT2/wiki/Commit-Messages)

**Comment by Aryaman73** [comment]
@tupaschoal Thanks for the merge, and helping me out! What else needs to be done for this? I can't find any other calls to this function,

**Comment by tupaschoal** [comment]
Really? If none is calling the old function anymore, just delete it and submit a pr. It should fail to compile if there are users still

**Comment by Aryaman73** [comment]
Sorry, not sure what I did wrong earlier but you're right, there are definitely other calls to the function. As for fixing the other calls, the change should pretty much just include changing: 
 ` gfx_draw_string_right(dpi, stringId, nullptr, COLOUR_WHITE,  w->windowPos.x + w->width - 5, y );`
to this:
 ` gfx_draw_string_right(dpi, stringId, nullptr, COLOUR_WHITE, {w->windowPos.x + w->width - 5, y });`

Or is there more to it?

**Comment by duncanspumpkin** [comment]
That's pretty much all you need to change. In some places you might have a ScreencoordsXY already so you obviously wouldn't need to create one for that.

**Comment by Aryaman73** [comment]
Cool. The issue mentions that we shouldn't make all of the changes in one PR. I think there are around a dozen files which will need to be refactored, so how should we PR it? Create a PR for each file?

**Comment by duncanspumpkin** [comment]
That is just in case its one of the string functions that is used absolutely everywhere. If its just a dozen files then do a single PR.
