### ISSUE TITLE
Game speed slows while holding right mouse button.

### ISSUE THREAD

**Issue by cowan108** [OpenRCT2/OpenRCT2#1156]
The game speed slows down a little when holding the right mouse button. 
For whatever reason, I can't get the gif to load into this here comment. But here's the link to it: http://i.imgur.com/J0rCdZP.webm

The change of speed is most noticeable on the Enterprise.

**Comment by RollingStar** [comment]
I've noticed this when right clicking and then dragging, but didn't check on regular RCT2 to see if Open 2 was different.

**Comment by devnoname120** [comment]
I just checked it in `0.0.5.0 build 5699b9e`, but I couldn't reproduce this bug.
http://webmshare.com/1ONy3

@cowan108 Are you still able to reproduce it in the latest version?

**Comment by rwjuk** [comment]
Just tested this with the latest build (a7e6c6a) and was unable to reproduce the issue.
