### ISSUE TITLE
Use ScreenCoordsXY on draw_string_right_underline

### ISSUE THREAD

**Issue by tupaschoal** [OpenRCT2/OpenRCT2#11566]
Create an overload of `draw_string_right_underline` on `\src\openrct2\drawing\Text.cpp` with the same name, but that takes a `const ScreenCoordsXY&` object instead of an `int32_t x` and and an `int32_t y` and replace the calls to the `{x ,y}` pair by the one using `ScreenCoordsXY`.

Don't try to do all calls at once, unless it doesn't occur a lot, as this might lead to a huge PR. When we stop using the old function, we can drop it entirely in favour of the `ScreenCoordsXY` alternative.

**Comment by TomasZilinek** [comment]
May I do this? :D

**Comment by tupaschoal** [comment]
Sure

**Comment by TusharSariya** [comment]
made a PR
