### ISSUE TITLE
Use ScreenCoordsXY on gfx_draw_string_centred_clipped

### ISSUE THREAD

**Issue by tupaschoal** [OpenRCT2/OpenRCT2#11564]
Create an overload of `gfx_draw_string_centred_clipped` on `\src\openrct2\drawing\Text.cpp` with the same name, but that takes a `const ScreenCoordsXY&` object instead of an `int32_t x` and and an `int32_t y` and replace the calls to the `{x ,y}` pair by the one using `ScreenCoordsXY`.

Don't try to do all calls at once, unless it doesn't occur a lot, as this might lead to a huge PR. When we stop using the old function, we can drop it entirely in favour of the `ScreenCoordsXY` alternative.

**Comment by TusharSariya** [comment]
I can take this

**Comment by TomasZilinek** [comment]
@TusharSariya Are you still working on this? Because it is already 28 days since your last activity and I am interested in finishing this issue.

**Comment by tupaschoal** [comment]
He isn't @TomasZilinek , but I have a patch for this already

**Comment by TomasZilinek** [comment]
> He isn't @TomasZilinek , but I have a patch for this already

alright :D
