### ISSUE TITLE
No package 'duktape' found, CMake Error, A required package was not found, PKG_CHECK_MODULES

### ISSUE THREAD

**Issue by erikhuizinga** [OpenRCT2/OpenRCT2#11576]
**OS:** macOS
**Version:** 10.14.6
**Commit/Build:** output of `brew info openrct2`

```
openrct2: stable 0.2.6 (bottled), HEAD
Open source re-implementation of RollerCoaster Tycoon 2
https://openrct2.io/
/usr/local/Cellar/openrct2/HEAD-c5d877f_1 (2,169 files, 35.4MB)
  Built from source on 2020-04-25 at 17:35:14
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/openrct2.rb
==> Dependencies
Build: cmake, pkg-config
Required: freetype, icu4c, jansson, libpng, libzip, openssl@1.1, sdl2, sdl2_ttf, speexdsp
==> Requirements
Required: macOS >= 10.13
==> Options
--HEAD
	Install HEAD version
```

When I upgrade OpenRCT2 using Homebrew:

`brew update && brew upgrade openrct2 --fetch-HEAD`

Then the output is:

```
Updating Homebrew...
==> Upgrading 1 outdated package:
openrct2 HEAD-c5d877f_1 -> HEAD-158adfb_1
==> Upgrading openrct2 HEAD-c5d877f_1 -> HEAD-158adfb_1 
==> Cloning https://github.com/OpenRCT2/OpenRCT2.git
Updating /Users/erik.huizinga/Library/Caches/Homebrew/openrct2--git
==> Checking out branch develop
Already on 'develop'
Your branch is up to date with 'origin/develop'.
HEAD is now at 158adfba8 Merge pull request #11560 from tupaschoal/more-coordz
==> Downloading https://github.com/OpenRCT2/title-sequences/releases/download/v0.1.2c/title-sequences.zip
Already downloaded: /Users/erik.huizinga/Library/Caches/Homebrew/downloads/0214e6a3fb336e8419adf432bd4fdee7ce81e7ceddcb87b4d48ac6e03643830f--title-sequences.zip
==> Downloading https://github.com/OpenRCT2/objects/releases/download/v1.0.14/objects.zip
Already downloaded: /Users/erik.huizinga/Library/Caches/Homebrew/downloads/2f140327558be78cd904098b1a6bde9608669066373af7b8e95e5890e4f6be98--objects.zip
==> cmake ..
Last 15 lines from /Users/erik.huizinga/Library/Logs/Homebrew/openrct2/01.cmake:


Google benchmark not found, disabling support
-- Checking for module 'duktape'
--   No package 'duktape' found
CMake Error at /usr/local/Cellar/cmake/3.17.2/share/cmake/Modules/FindPkgConfig.cmake:467 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.17.2/share/cmake/Modules/FindPkgConfig.cmake:647 (_pkg_check_modules_internal)
  src/openrct2/CMakeLists.txt:107 (PKG_CHECK_MODULES)
  CMakeLists.txt:267 (include)


-- Configuring incomplete, errors occurred!
See also "/tmp/openrct2-20200501-63097-wim1sf/build/CMakeFiles/CMakeOutput.log".

READ THIS: https://docs.brew.sh/Troubleshooting


==> Checking for dependents of upgraded formulae...
==> No dependents found!
```

And the file `"/tmp/openrct2...."` doesn't exist when the Homebrew process exits, so I don't have more logs.

What is this `duktape` module/package that seems missing?

**Comment by janisozaur** [comment]
This is not https://github.com/Homebrew

Duktape is script engine.

**Comment by AaronVanGeffen** [comment]
@erikhuizinga You're missing a duktape package. Unfortunately, homebrew-core does not provide one, but there are a few formula available as part of some homebrew kegs. You could tap [gerbera/homebrew-gerbera](https://github.com/gerbera/homebrew-gerbera/blob/master/duktape.rb) to get their formula in your Homebrew, for example. Alternatively, you can compile your own.

**Comment by janisozaur** [comment]
@AaronVanGeffen why do you re-open not our bugs? They are downstream and this is not the place to file them. Having it reported here is pointless, as this is not going to get them fixed.

**Comment by Gymnasiast** [comment]
@AaronVanGeffen I think the readme (and possibly the wiki) need to be adjusted. The readme doesn't currently mention duktape as a dependency for macOS.

**Comment by AaronVanGeffen** [comment]
@Gymnasiast Agreed, but I also think we should try to get a `duktape` package into homebrew-core. It looks like there has only been one attempt before (https://github.com/Homebrew/homebrew-core/pull/28480) and that even almost made it in.

**Comment by AaronVanGeffen** [comment]
In the mean time, I have filed a PR over at https://github.com/Homebrew/homebrew-core/pull/54089.

**Comment by AaronVanGeffen** [comment]
The PR with Homebrew has been merged. However, our cmake set-up isn't automatically picking up the libraries it provides.

You can work around this by passing the relevant variables to `cmake`, or correct them manually using `ccmake` after the first invocation. To make all this easier, I have filed https://github.com/OpenRCT2/OpenRCT2/pull/11596 (WIP) to fix.
