### ISSUE TITLE
Scenery research issue with RCT1 parks

### ISSUE THREAD

**Issue by Mats37** [OpenRCT2/OpenRCT2#11588]
Something weird is happening with my game, I'm playing the Added Atractions scenarios, right now I'm with Pickle Park. When I started, I have the standard scenary, I save the game and when I load it later, I have a bunch of new scenary and I didn't resarch any.

Here is how I start the park
![Error](https://user-images.githubusercontent.com/43803872/80851711-b9e2fd80-8bf9-11ea-9ad4-cea8120d80bd.png)
This is after I load it
![Error 2](https://user-images.githubusercontent.com/43803872/80851715-c49d9280-8bf9-11ea-8832-b91513b1a319.png)
And here you can see I didn't resarch it
![Error 3](https://user-images.githubusercontent.com/43803872/80851744-fadb1200-8bf9-11ea-8a6e-62f894e3c202.png)

I'm using the latest one v0.2.6-4a8df6d
I run the game in Windows 10 64 bits

I leave the save file which I found the issue

[Mats 1 II-25.zip](https://github.com/OpenRCT2/OpenRCT2/files/4566840/Mats.1.II-25.zip)

**Comment by Mats37** [comment]
I've maked a video about the issue

[https://youtu.be/3Ieyydv0Ds0](url)

**Comment by tupaschoal** [comment]
I've bisected it and culprit is @Gymnasiast 's 70e287b07

**Comment by Fred-1044276** [comment]
I also have this issue with any park, not just RCT1 parks. Any park where you can research scenery, such as Mythological Madness.

**Comment by RoelerCoaster** [comment]
I noticed this same issue today while playing the Wacky World's scenario "Antarctica - Ecological Salvage", where the snow and ice theming was suddenly available after reloading a save game (it was not yet reasearched). This issue does not seem to be limited to RCT1 parks only.

**Comment by RoelerCoaster** [comment]
Did this at some point get fixed? It doesn't seem to be happening to me any more on v0.3.4.1 767dbfe

**Comment by Gymnasiast** [comment]
Cannot reproduce it either on 578d8ce24785a3b312d1d2c5e9f8a57ee2901a6e. Assuming it has been fixed.
