### ISSUE TITLE
Add support for setting block brake speed

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#11649]
https://github.com/OpenRCT2/OpenRCT2/pull/7737 attempted to implement a speed setting on the block brakes. This PR is abandoned and its implementation was not entirely up to scratch. The feature is still wanted, though.

Currently, block brakes always slow down to 6 km/h if they're open (and to 0 if they're closed). This could be changed to a higher speed. When doing this, also remove the ifdef for `NEW_BLOCK_BRAKES` and remove the bool in `apply_non_stop_block_brake()`, which is always true. The S6Importer will also need to be amended to set the speed of block brakes (which would otherwise be set to 0), and the TD6 Importer will also need adjusting.

**Comment by duncanspumpkin** [comment]
I see this as something that should be left to the new save format.
