### ISSUE TITLE
Keys in option 'Shortcut keys...' not translatable

### ISSUE THREAD

**Issue by danidoedel** [OpenRCT2/OpenRCT2#1164]
![2015-05-29 19_02_17-openrct2](https://cloud.githubusercontent.com/assets/10995998/7888049/ef867e16-0635-11e5-8053-91a06898c68c.png)

**Comment by Gymnasiast** [comment]
A clarification: some keyboards do translate buttons: on German keyboards, Ctrl is labeled Strg., for example. (On French keyboards, it isn't renamed, oddly enough.)

**Comment by Patrik356b** [comment]
Not so odd, keys aren't renamed on Swedish keyboards either.

**Comment by Gymnasiast** [comment]
@Patrick356: I said 'oddly enough' since France tends to have more language purism than many other countries.

**Comment by Gymnasiast** [comment]
Hm, the string _are_ in the language files. But not used, apparently.

**Comment by IntelOrca** [comment]
Requires changes to:
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/interface/keyboard_shortcut.c#L103

**Comment by Gymnasiast** [comment]
Fixed by https://github.com/OpenRCT2/OpenRCT2/pull/10147.
