### ISSUE TITLE
Memory dumps being generated every time the game is closed

### ISSUE THREAD

**Issue by Topodic** [OpenRCT2/OpenRCT2#11667]
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** e369c22

What it says on the tin. Anytime I close the game to desktop, be it on the title screen or in a park, a memory dump is generated. Obviously this isn't impacting gameplay or anything related to the game itself, but the dumps being ~12MB each can start using up disk space quickly if it isn't noticed.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open the game
2. Close the game

**Dump file**

[9f013a83-b0d2-4ccf-b5fa-8ad667c2c549(e369c22_x86-64).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/4596614/9f013a83-b0d2-4ccf-b5fa-8ad667c2c549.e369c22_x86-64.dmp.gz)

**Screenshots / Video:**

![18-51-46_explorer_1432](https://user-images.githubusercontent.com/43795565/81361803-35c6c500-9094-11ea-8b12-93cf1207d1ee.png)

**Save game:**

N/A

**Comment by Fred-1044276** [comment]
I've actually been noticing this since April 26, 2020.

**Comment by IntelOrca** [comment]
The .gz file you have attached can not be uncompressed. Can you try zipping one of the .dmp files manually and upload that?

**Comment by Topodic** [comment]
Ah, my bad. Gotcha.
[9f013a83-b0d2-4ccf-b5fa-8ad667c2c549.dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/4599324/9f013a83-b0d2-4ccf-b5fa-8ad667c2c549.dmp.gz)
