### ISSUE TITLE
Plugin API Request: Ability to change ride/track color and train/individual car color

### ISSUE THREAD

**Issue by kasamuel** [OpenRCT2/OpenRCT2#11664]
I'm writing a script to automate the building of scrolling signs using stacked wood coaster trains.
like this:
https://cdn.discordapp.com/attachments/689559763365003305/707301755179761688/2020-05-05_10-37-51.mp4

I would like the ability to automate the changing of train and track colors, more specifically the colors of individual cars.
With this added to the API I would be able to have text scrolling of unlimited length by dynamically changing the train colors of the cars that are not currently visible.

Thanks!!

**Comment by IntelOrca** [comment]
Oh wow, nice. I will add those fields to the ride and vehicle entity interface soon.

**Comment by IntelOrca** [comment]
Now implemented.
