### ISSUE TITLE
Spiral Roller coaster has chainlift available

### ISSUE THREAD

**Issue by cheweytoo** [OpenRCT2/OpenRCT2#11676]
**OS:** Linux x64
**Version:** tried every release from 0.2.6 back to 0.2.2

I currently cannot build spiral roller coasters with a curved lift any more:
![spiral_coaster_no_lift](https://user-images.githubusercontent.com/29800630/81454444-96d1c400-918c-11ea-82a5-093044e5dff6.png)

This used to be possible - I have a park containing an example, built without cheats or hacks:
![spiral_coaster_lift](https://user-images.githubusercontent.com/29800630/81454449-9f29ff00-918c-11ea-9eb8-b7b2ce53f2c2.png)

Building one of the preset designs containing a curved lift (e.g. "Percolator") still works.

I have tried all released versions back to 0.2.2, and the current dev version (49e062a), but didn't get the curved lifts back. The OpenRCT2 version used to build my custom design with curved lifts definitely is somewhere within that interval.

The only non-binary change to my OpenRCT2 environment between the time when I built that custom spiral coaster and now I can think of: A while ago, I extracted the RCT1 folder from a nearly two decade old backup and added it to my OpenRCT2 config.

To check if this might have triggered this problem, I moved `~/.config/OpenRCT2` to another location and configured OpenRCT2 from scratch again, omitting the RCT1 folder config – in vain.

Am I missing something?

- [ ] Reproducible in RCT2 (vanilla)?
Unsure, I only run Linux nowadays. Probably not.

- [ ] Specific to multiplayer?
No.

**Steps to reproduce:**
Really not sure.

**Comment by cheweytoo** [comment]
Oh dear. Scratch all of the above, its right there in "Special..." as "Cuved Lift Hill".

There's still an inconsistency in the build UI though: When building e.g. a Junior Coaster, the curved lift hills can be built without going into the "Special..." options just by starting a lift and clicking the "curve" button.

**Comment by Gymnasiast** [comment]
It works for me. Just make sure the last piece you build is flat, then just select "curved lift hill" from the "special" menu.

The only bug I could see was that the Spiral Roller Coaster has a chainlift, which it is not supposed to have.

**Comment by Gymnasiast** [comment]
> There's still an inconsistency in the build UI though: When building e.g. a Junior Coaster, the curved lift hills can be built without going into the "Special..." options just by starting a lift and clicking the "curve" button.

That's another type of curved lift hill. Tthe Junior RC's lift hill is much steeper.

**Comment by cheweytoo** [comment]
> That's another type of curved lift hill. The Junior RC's lift hill is much steeper.

Right. Sorry for the confusion.
Glad I could still report a bug, even if it is not the one I thought I reported ;-)

**Comment by Fred-1044276** [comment]
Personally, I would lock the regular chain lift hill behind "Enable all drawable track pieces".

After looking into the code, I also noticed that the mini roller coaster has had the spiral coaster's curved lift hill pieces as part of the MiniRollerCoaster.cpp file but they are otherwise not even usable for the mini coaster.

**Comment by Gymnasiast** [comment]
> After looking into the code, I also noticed that the mini roller coaster has had the spiral coaster's curved lift hill pieces as part of the MiniRollerCoaster.cpp file but they are otherwise not even usable for the mini coaster.

Check what the track paint function of the Spiral RC is set to...

**Comment by ekozie** [comment]
If I have an existing spiral coaster with regular lift hill, will it be broken in the new version?

**Comment by Gymnasiast** [comment]
@ekozie No, it will still work. It is also still possible to build them if you enable the "Show all track pieces" cheat. The only change is that the part cannot be built by default.
