### ISSUE TITLE
Add the OpenRCT2 icon to 'openrct2.exe'

### ISSUE THREAD

**Issue by danidoedel** [OpenRCT2/OpenRCT2#1168]

**Comment by janisozaur** [comment]
With Linux and OS X builds now depending on a fixed version of `openrct2.exe`, it probably needs to wait until we can ditch the exe.

**Comment by IntelOrca** [comment]
I'll look into updating the icon.

**Comment by janisozaur** [comment]
As the sections are now extracted, you can simply check their checksum pre- and post-change on travis.

Let me know if you need any help setting that up.

**Comment by IntelOrca** [comment]
I wasn't able to update the icon without breaking the game / crash on launch.
I think this will just have to wait for full implementation.

**Comment by PFCKrutonium** [comment]
I have previously tried changing the icon on the executable myself, something about changing the icon breaks the executable. It shouldn't, but it does.

**Comment by Patrik356b** [comment]
Inb4 drm complaint (:

Jokes aside; this is actually more seen than you might think. Maybe it's used somewhere in a yet to be decompiled function

**Comment by IntelOrca** [comment]
x64 builds have the icon and x86 build will follow when we no longer require rct2.exe.
