### ISSUE TITLE
Custom colors of train cars don't get saved past car 32

### ISSUE THREAD

**Issue by kasamuel** [OpenRCT2/OpenRCT2#11697]
Tested on newest dev and latest release.

Made a bunch of coasters with 81 train cars, only one train each.
Colored them a base color then started changing the color of individual cars to spell out words.
Everything was fine and dandy until I tested the save file, none of the colors had changed. All of the custom colors that I set past car 32 did not save. They all reset to the base color that I set before changing it to "custom colors for each car".

**Comment by AaronVanGeffen** [comment]
This is a limitation of the current save format. Unfortunately, it cannot be fixed for SV6 saves.

**Comment by Gymnasiast** [comment]
I wonder if we could fetch those colours from the vehicle entities.

**Comment by kasamuel** [comment]
This now works with NSF, and can be closed. thanks all!

**Comment by duncanspumpkin** [comment]
Yes it will work for the first 255 the rest will not work.
