### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by med1001** [OpenRCT2/OpenRCT2#11699]
I am using Ubuntu 18.04.4 LTS and  trying to build OpenRCT2
steps 
1- install dependencies
as in https://github.com/OpenRCT2/OpenRCT2/wiki/Building-OpenRCT2-on-Linux APT (Debian, Ubuntu)

sudo apt-get install --no-install-recommends -y cmake libsdl2-dev libicu-dev \
    gcc pkg-config libjansson-dev libspeex-dev libspeexdsp-dev libcurl4-openssl-dev \
    libcrypto++-dev libfontconfig1-dev libfreetype6-dev libpng-dev libssl-dev libzip-dev \
    build-essential make duktape-dev

2-compile
mkdir build && cd build
cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo
make

but make fails with these errors
![make errors](https://user-images.githubusercontent.com/26111211/81495620-79dee300-92a9-11ea-94b9-0189df737d68.png)
am i missing something for the build?
thank you.

**Comment by AaronVanGeffen** [comment]
You can compile without benchmarks enabled  (cmake -DDISABLE_GOOGLE_BENCHMARK=ON), which would resolve these errors. However, I think the default compiler toolchain on Ubuntu 18.04 is not up-to-date enough for OpenRCT2. You may run into other problems.

**Comment by janisozaur** [comment]
@med1001 don't post screenshots of text.

**Comment by med1001** [comment]
it works with benchmarks disabled. 
@janisozaur i will pay attention to this detail in the future.
Thank you.
