### ISSUE TITLE
[Plugin] OnTileChanged hook request

### ISSUE THREAD

**Issue by frutiemax** [OpenRCT2/OpenRCT2#11709]
While writing a plugin, I've encountered the need of knowing all the tiles affected by a game action.
![testTerritory2](https://user-images.githubusercontent.com/12629817/81510536-613def80-92e0-11ea-9c63-00b517e99928.gif)

For a script that override the game permissions, it is a must since a user could put the landscape land size tool to 100 and still be able to lower the land if the cursor is in the set land.

- Expose tiles affected in the game action base class (C++)
- Update the scripting api to access these tiles

**Comment by duncanspumpkin** [comment]
That would basically mean rethink of the whole game action design. It would be a very big undertaking. Not saying it wouldn't be useful just that it would not be easy at all.

**Comment by frutiemax** [comment]
This is strange, raising water seems to trigger per tile game actions, while terrain actions trigger a big action in the tile center. Perhaps the fix is to trigger only single tile game actions?

**Comment by frutiemax** [comment]
I might close this issue as extensions of GameActionResult in the plugin system might be more feasible and impact less the core of the game.

**Comment by duncanspumpkin** [comment]
I think my location valid hook pretty much fixed this anyway
