### ISSUE TITLE
Notification config for 'guest is lost' seems not working

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#11703]
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** c447cde

"Guest is lost" config at news message notification config seems not working.
Or, if it is affected to only a guest who is tracked, I think there should be another option to turn on/off the global guests' lost.

**Steps to reproduce:**
1. Uncheck "Guest is lost" at Nofitication config window
2. Open any map people lost.

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/10726524/81502468-22785b80-9319-11ea-816f-568000f9b766.png)

**Comment by AaronVanGeffen** [comment]
The lost guests (plural) warnings are part of the guest warnings setting. I think the "guest is lost" is only used for tracked guests.

Either way, I think the strings could use some clarification.

**Comment by Gymnasiast** [comment]
I remember IntelOrca including it as a joke about the bad old days of RCT1, which would show a warning for every single lost guest.

**Comment by telk5093** [comment]
+ Additional comment since I wrote wrong context:
Then it would be great if there exists to turn on/off global guests' losting msg :O
