### ISSUE TITLE
[Arch] Broken with icu-67

### ISSUE THREAD

**Issue by fosspill** [OpenRCT2/OpenRCT2#11710]
**OS:** Archlinux
**Error:** openrct2: error while loading shared libraries: libicuuc.so.65: cannot open shared object file: No such file or directory

After an update from icu-65 to icu-67 the game no longer starts.
Using: https://aur.archlinux.org/packages/openrct2/

Unsure about if this is the right place to post this, but I assume it's good to know regardless.

EDIT: Building it manually from stable source seems to resolve the issue. Presumably the aur package needs to be rebuilt.

**Comment by AaronVanGeffen** [comment]
Yes, you will need to rebuild your AUR packages when one of their dependencies has been updated. In this case, all that’s needed is a linker change, though, so that shouldn’t require a clean rebuild.

Either way, this is not a bug with OpenRCT2.
