### ISSUE TITLE
Lowering main volume less than half mutes block brake release sound effect

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#11741]
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** 0d0349f

~~Balloon exploding sounds (when I click flying balloons) are gone.~~
=> It was my mistake, balloon sound was TOO SMALL to hear.
~~Block break release sound is missing. Checked vanilla can sound it.~~
=> It was my mistake, too.

Make main volume less than half, then I can't hear block brake release sound effect.
I have no idea if it is just too small so I can't hear, or it is really zero-volumed in some reason.

**Step to reproduce:**
1. Make main volumne less than about half. (it is not exact value.)
1. Build some block-braked coaster, such as ``Siege Breaker`` of Spiral coaster.
1. Test it.

If it is not a bug, if its volume is just small, then I think it is rather strange that block brake/balloon's sound effect is too small comparing to other sound such as guest's wandering sounds.

**Comment by AaronVanGeffen** [comment]
Sounds like #8108? If you could help bisect this to a certain commit, that would be a big help in addressing this.

**Comment by telk5093** [comment]
Sorry the balloon's sound was too small. I've checked it is heard at f04f623.
But, block break release sound is not and checked that vanilla sounds correctly.

**Comment by telk5093** [comment]
I've checked pure config.ini and checked both sound effect works, sorry.
But make main volume less than half, I can't hear block break release sound.
(I have no idea if it is just too small, or it is zero-volumed)
