### ISSUE TITLE
Plug-in: Allow plug-ins to read and change scenario-related items (options, description, objective, etc)

### ISSUE THREAD

**Issue by James103** [OpenRCT2/OpenRCT2#11759]
**OS:** Win 10
**Version:** Since new plugin system
**Commit/Build:** da0ef7d3a42cbcd539cf40071fe4e4100c9de6af (assumed)

I would like it if plug-ins could read and change the following:
- All of the scenario options (not just the financials but also guests, restrictions, etc)
- The scenario description
- The scenario goal
- Win state (either incomplete, passed, or failed)
- Score (usually equal to company value at win time)
- Park revenue model (free entry/paid rides, paid entry/free rides, paid entry/paid rides)

Additionally, what if a plugin could watch for if you passed (or failed) a scenario so as to ...?
* Reward or penalize you in some way
* Change the scenario or map

This could allow for multi-objective scenarios, such as one where you have to first get 3,500 guests by year 3, then get $50,000 in ride ticket income per month. It could also allow for automatic scenario switching for multi-scenario runs, for example going through all of the RCT1 scenarios in a speedrun (which could resolve #7168).

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Look in the documentation (https://github.com/OpenRCT2/OpenRCT2/blob/da0ef7d3a42cbcd539cf40071fe4e4100c9de6af/distribution/openrct2.d.ts) for anything pertaining to scenario options, description, goal, or any other scenario-related items.

**Comment by mgovea** [comment]
It'd also be nice to know the scenario's price mode e.g.
- free admission, charge for rides
- charge for admission, free rides
- charge for both

**Comment by mgovea** [comment]
Does https://github.com/OpenRCT2/OpenRCT2/pull/12921 address this issue? I think it got most of it.

**Comment by duncanspumpkin** [comment]
Yeah I feel it does. I'll therefore close it. If you find it doesn't cover an item feel free to open a new issue as I feel all of these are accounted for.
