### ISSUE TITLE
Plugin: More plugin hook ideas

### ISSUE THREAD

**Issue by James103** [OpenRCT2/OpenRCT2#11773]
**OS:** Win 10
**Version:** Since new plugin system
**Commit/Build:** da0ef7d3a42cbcd539cf40071fe4e4100c9de6af (assumed)

There currently appears to be no way to subscribe to any of the following hooks, all of which could be useful in some way:
* Scenario objective check (useful for creating custom objectives)
* New guest spawns (useful to modify guest stats or deny the event for guest control)
* Park rating calculation (to modify the park rating formula)
* Park value calculation (to modify the park value formula)

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Look in the [documentation](https://github.com/OpenRCT2/OpenRCT2/blob/develop/distribution/openrct2.d.ts) for a way to subscribe to any of the above hooks.

**Comment by Ryder17z** [comment]
I'd also like to see a way to do _if condition X is met unlock/change Y_, example:

```
if(guests > 300) UnlockItem("Go-Karts"); // research item/theme
if(guests > 800) ConvertBuildRights2Land(AreaCoords);
if(guests > 1200) AllowDeconstruct("rideName"); // rides that can't be deleted or modified fully
if(CurrentLoanAmount == 0) GuestSpawnRate *= 1.25; // increase guest spawn rate by 25%
// psudo code, written on my phone 
```

**Comment by duncanspumpkin** [comment]
@Ryder17z you can do that at present just by checking every day. I don't see us adding hooks for all of those events.

**Comment by Ryder17z** [comment]
> 
> 
> @Ryder17z you can do that at present just by checking every day. I don't see us adding hooks for all of those events.

Oh. okay

**Comment by James103** [comment]
Moved to https://github.com/OpenRCT2/OpenRCT2/discussions/16480#discussioncomment-3020522 as feature requests go in Discussions. The "New guest spawns" hook was already implemented as `guest.generation` in https://github.com/OpenRCT2/OpenRCT2/pull/14107.
