### ISSUE TITLE
[Plugin] Viewport parameters don't appear to work

### ISSUE THREAD

**Issue by MegaMech** [OpenRCT2/OpenRCT2#11777]
The following viewport options don't seem to do anything. The methods such as moveTo do work.
I'm trying to get zoom to work. I think zoom should actually be a method so that it can be updated live without reopening the window.

```
interface Viewport {
        left: number;
        top: number;
        right: number;
        bottom: number;
        rotation: number;
        zoom: number;
        visibilityFlags: number;
```
Dev 2.6-15 compiled with PR#11712

my code:
```
var zoom = 0;
zoomIn() {
    zoom++;
}
Viewport = {
        left: 10,
        top: 10,
        right: 890,
        bottom: 835,
        rotation: 0,
        zoom: zoom,
        visibilityFlags: 0
    };
 viewPortWidget = {
        type: "viewport",
        x: 2,
        y: 16,
        width: 323,
        height: 482,
        name: "viewport",
        viewport: Viewport
    }
ui.openWindow({ 
...
widgets: [viewPortWidget, ...]
....

```

**Comment by IntelOrca** [comment]
does `window.findWidget('your-viewport-widget-name').viewport.zoom = 3` work?

**Comment by MegaMech** [comment]
Yes that works. I would suggest finding a way in the API to tell users that everything in that list needs to use findWidget().viewport

thanks.
