### ISSUE TITLE
[plugin] Unable to use sharedStorage

### ISSUE THREAD

**Issue by mgovea** [OpenRCT2/OpenRCT2#11796]
Whenever I try to use plugin configuration, I am unable to set a value. Whether I use `context.sharedStorage` or `context.configuration`, I always hit [this "Property does not exist." error](https://github.com/OpenRCT2/OpenRCT2/blob/7e7b15812dabe6977f3573b2a3f52b1737c5527c/src/openrct2/scripting/ScConfiguration.hpp#L224).

It looks like `_isUserConfig` is always `true`.

Am I doing something wrong?

**Comment by IntelOrca** [comment]
You need to construct the parent objects first if they haven't already got values.
E.g.

`context.sharedStorage.set("a", {});`
`context.sharedStorage.set("a.test", 2);`

The configuration storage is mostly incomplete right now.

**Comment by mgovea** [comment]
In my `config` file, I wrote this initialization function in order to replicate your instructions:
```
const namespace = 'MyPlugin';
// ...
const config = {
    initialize: function(): void {
        const entries = context.sharedStorage.getAll(namespace);
        if (!Object.getOwnPropertyNames(entries).length) {
            context.sharedStorage.set(namespace, {}); // This line errors.
        }
    }
    // ...
};
```
And when I call this function at the start of `main`, I get `Error: Property does not exist.`, just like in my O.P.

**Comment by mgovea** [comment]
Thanks @IntelOrca !
