### ISSUE TITLE
[UI] Text in dropdown box (at options) is floating out of box

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#11816]
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** 1020969

See "Screen mode" and "Drawing engine" at the screenshot below.

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/10726524/82922843-19dc8200-9fb5-11ea-9c17-fbd253a3eb3d.png)

**Comment by tupaschoal** [comment]
Culprit is https://github.com/OpenRCT2/OpenRCT2/commit/2cf95adc4b3dd12cbc8cb142bb8d6417cc7b445c
