### ISSUE TITLE
Park entrance graphical glitch

### ISSUE THREAD

**Issue by rd3k** [OpenRCT2/OpenRCT2#1181]
This happens regardless of whether guests are currently passing through it.

![screeny video 31 may 2015 01 14 58](https://cloud.githubusercontent.com/assets/935762/7899967/01ef7b86-0733-11e5-834c-babfbf777fbf.gif)

**Comment by duncanspumpkin** [comment]
I managed to reproduce this in the original game.

**Comment by rwjuk** [comment]
Couldn't replicate this on the latest build - tested multiple ground types across various scenarios.

**Comment by Gymnasiast** [comment]
I believe I still get this. I'd have to check for steps to reproduce though.

**Comment by rwjuk** [comment]
Hmm... if you can figure out the reproduction steps I'd be interested to see it. I tried various things but couldn't get it to happen!

**Comment by rd3k** [comment]
This issue makes the game literally unplayable for me.

Please do not resolve until there is broad community consensus that it has been sufficiently addressed.

**Comment by janisozaur** [comment]
@rd3k can you provide a way to reproduce?

**Comment by Gymnasiast** [comment]
Can't seem to produce this, even though there are tiny glitches aplenty.

**Comment by rik-smeets** [comment]
I can't reproduce this either, therefore closing this one.
