### ISSUE TITLE
Window tooltip contains "Window title" instead of inserting the window's title

### ISSUE THREAD

**Issue by mgovea** [OpenRCT2/OpenRCT2#11823]
Currently:
 - If you mouseover the title bar of any window, the tooltip says "Window title - Drag this to move window".

Expected:
 - The tooltip should insert the title, e.g. "Map - Drag this to move window".

This is the string number:
https://github.com/OpenRCT2/OpenRCT2/blob/b7606d52fa54fd7f0a64e1c74f81f46c3fe4a2a4/src/openrct2/localisation/StringIds.h#L260

And this is its English version, showing the hardcoded "Window title" instead of a parameter.
https://github.com/OpenRCT2/OpenRCT2/blob/b7606d52fa54fd7f0a64e1c74f81f46c3fe4a2a4/data/language/en-GB.txt#L233

The issue is also in other languages, but I am just using it as an example.

**Comment by AaronVanGeffen** [comment]
Just to clarify, you're filing this as a feature request, right?

**Comment by Gymnasiast** [comment]
I'm not sure what is supposed to be wrong here. After all, you're hovering over the window title and the tooltip explains what it is and what it can be used for.

**Comment by mgovea** [comment]
Huh. I guess I misinterpreted how it is supposed to work.
