### ISSUE TITLE
[UI] Disabled icons are not shown as disabled

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#11845]
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** bc5aac4

Disabled icons are not shown as disabled as you can see below.

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/10726524/83350349-7dc8c700-a376-11ea-8e99-1b406c1d89c9.png)

**Comment by tupaschoal** [comment]
Culprit is @IntelOrca 's d3f7ec484
