### ISSUE TITLE
OpenRCT2 not starting under XP x86 / x64

### ISSUE THREAD

**Issue by Parkmanager** [OpenRCT2/OpenRCT2#1184]
Message Window:
"The procedure entry point InitializeCriticalSectionEx could not be located in the dynamic link library KERNEL32.dll"

Last working build is b634

**Comment by IntelOrca** [comment]
Do you have Service Pack 3?

**Comment by Parkmanager** [comment]
SP2, it's the x64 version (SP3 is for x86 only)

**Comment by IntelOrca** [comment]
Hmm, I think the game would need to be compiled with the v120_xp platform set for this to work, although not sure why it worked previously, InitializeCriticalSectionEx gets called in fopen.

**Comment by Parkmanager** [comment]
I've just set up a system with xp x86 sp3 -> same error message.

**Comment by IntelOrca** [comment]
This might not be looked into until native builds are available.

**Comment by JarnoVgr** [comment]
Updating this because I get multiple reports of people who want to run it on XP. I'll try to do a v120_xp build soon.

**Comment by IntelOrca** [comment]
You should now be able to compile with v140_xp.

**Comment by IntelOrca** [comment]
Build servers will need to support this, a build for XP and a build for Vista / 7 / 8 / 10.

**Comment by JarnoVgr** [comment]
@IntelOrca I changed my build server to v140_xp. Yet the same issue keeps occuring.
Build with v140_xp: https://openrct2.com/download/1209

**Comment by IntelOrca** [comment]
Could you try compiling with **DISABLE_NETWORK**, **DISABLE_HTTP** and **DISABLE_TWITCH**.

**Comment by JarnoVgr** [comment]
Finally got around trying to build without network/http/twitch. But I can't get it compiled on v140_xp anymore (even on default settings). Too many linker problems while my paths seem to be setup correctly and v140 works fine. @IntelOrca could you try it for yourself to compile a v140_xp version?

Also, why isn't v140_xp the default like other projects have when they still want to support XP? Are there any downsides to it?

**Comment by janisozaur** [comment]
I suggested it somewhere else, but how about mingw builds?

**Comment by JarnoVgr** [comment]
Well, I think most devs develop using VS2015 and test everything they do. I know we have build tests for mingw, but it's still a risk sorta. Right?

**Comment by janisozaur** [comment]
risk? what risk?

**Comment by JarnoVgr** [comment]
Well I assume that mingw builds could give unexpected behaviour when devs mainly use VS2015 when on Windows. So that's why I'm asking if my assumption is correct.

**Comment by janisozaur** [comment]
If we were using some obscure compiler features, then perhaps yes. But mingw builds work just fine, this is what was used by default on Linux until recently. Right now we do have native gcc support, which isn't far away from mingw builds so there's that as well.

There are two places where the code is different, though, even if functionally equivalent:
* https://github.com/OpenRCT2/OpenRCT2/commit/9e621985464718327eb21637f8041eecacc7bd8c
* https://github.com/OpenRCT2/OpenRCT2/issues/1486 / https://github.com/OpenRCT2/OpenRCT2/commit/42691726fc3ca73eacab6417f0675c8ec9f94a29?w=1

Still, running with these two is better than not running at all, right?

**Comment by IntelOrca** [comment]
@JarnoVgr there must be downsides otherwise why would the non-XP toolset need to exist. I imagine the XP toolset uses older APIs which are now deprecated for Vista onwards.

I will try compiling myself on 140_xp - the reason I suggested disabling the network features is due to the dependencies probably also needing to be compiled with XP support - and the dependency build server doesn't support that yet.

**Comment by IntelOrca** [comment]
I have built OpenRCT2 supposedly with XP support, can someone try this on XP?

https://drive.google.com/file/d/0B5Z4DtDHrcpHWjEtSmxRU1JMSDA/view?usp=sharing

**Comment by JarnoVgr** [comment]
Works great on my XP SP3 vm. Could you supply instructions how to compile it for XP?

**Comment by IntelOrca** [comment]
Oh good, I will just commit my changes to the solution and projects.

**Comment by IntelOrca** [comment]
@JarnoVgr OK you should be able to use the "Release XP" configuration now.

**Comment by JarnoVgr** [comment]
Thanks! Will change my build server soon.

**Comment by IntelOrca** [comment]
Its worth trying it without disabling network, twitch etc. to see if that works too.

**Comment by osconnoisseur** [comment]
Is there any reason why you disabled networking for that build? The networking and multiplayer features work fine on Windows XP with the latest dev version compiled with MinGW. I haven't tested twitch integration, since I never use that.

**Comment by janisozaur** [comment]
Networking used to be something that broke XP builds, hence it was disabled. Then it was fixed, but perhaps the configuration was not updated to reflect that. Consult git history to see what happened.

**Comment by PFCKrutonium** [comment]
In any case, we should being producing XP Builds every so often.

**Comment by JarnoVgr** [comment]
@osconnoisseur MinGW 'always' worked. This bug only applies when building using Visual Studio.

**Comment by IntelOrca** [comment]
There are now MINGW XP builds available.
