### ISSUE TITLE
Close button colour of prompt windows do not match

### ISSUE THREAD

**Issue by danidoedel** [OpenRCT2/OpenRCT2#1185]
The close button should use the brighter red of the main window instead of the darker red of the titel bar.

![2015-05-31 10_43_13-openrct2](https://cloud.githubusercontent.com/assets/10995998/7901318/1cb82450-0782-11e5-8786-31ec990acdec.png)

**Comment by danidoedel** [comment]
Ah it looks like this is an original bug, if you guys see this as a bug ;)

**Comment by trigger-death** [comment]
What we could do is make the 'X' white when the close button is transparent. But that's about it.

**Comment by danidoedel** [comment]
If a white 'X' is looking good it's ok I think.

**Comment by Patrik356b** [comment]
That would be nice

On Sun, May 31, 2015 at 5:03 PM, danidoedel <notifications@github.com>
wrote:

> If a white 'X' is looking good it's ok I think.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IntelOrca/OpenRCT2/issues/1185#issuecomment-107201900>
> .
>



-- 
Best regards; Hexile
