### ISSUE TITLE
OpenRCT2 folder to be placed in .config under Linux

### ISSUE THREAD

**Issue by 97-109-107** [OpenRCT2/OpenRCT2#1188]
I tried searching for this but couldn't find anything relevant. Also, as far as I'm aware, this is not something that I can setup in Wine. 

It would be more conventional if under Linux OpenRCT2 would create/look for these locations instead
``/home/user/.config/OpenRCT2``
or
``/home/user/.OpenRCT2/``

**Comment by IntelOrca** [comment]
When OpenRCT2 no longer requires the original game and wine, it will use ```/home/user/.OpenRCT2/```

**Comment by Gymnasiast** [comment]
`/home/user/.config/OpenRCT2` would be better. It's the recommended location.

**Comment by IntelOrca** [comment]
But it isn't just configuration data that is stored. Scenarios, saved games and downloadable content is also stored here.

**Comment by Gymnasiast** [comment]
For such cases, `/home/user/.local/share/openrct2` would be better (with the files that come with the game residing in `/usr/share/games/openrct2`. Putting folders directly in `/home/user` isn't recommended. OpenTTD used to do it, but has now switched (on Debian-based at least) to `/home/user/.local/share/optenttd`

**Comment by IntelOrca** [comment]
Fair enough, I haven't had enough experience on unix to make this decision. If the convention is to place things in particular directories then that can be implemented.

**Comment by IntelOrca** [comment]
@janisozaur something you might like to look into.

**Comment by janisozaur** [comment]
I'll look into it, but it's not high on my list.

**Comment by janisozaur** [comment]
Implemented in #2196
