### ISSUE TITLE
Diacritics in custom scenario descriptions are badly encoded/decoded

### ISSUE THREAD

**Issue by rmnvgr** [OpenRCT2/OpenRCT2#11908]
**OS:** Fedora 32
**Version:** 0.2.6

**Steps to reproduce:**
1. Create a custom scenario
2. Use some diacritics in the scenario name and description, like é or à
3. Save the scenario
4. In the scenario selection window, the scenario name and description are badly displayed

**Screenshots / Video:**
The default description is already badly displayed:
![1](https://user-images.githubusercontent.com/66537460/84031957-df9cb880-a996-11ea-8ff5-09e720982419.jpg)

When entering the text, the text is displayed correctly:
![2](https://user-images.githubusercontent.com/66537460/84032007-f4794c00-a996-11ea-87f5-fc14c4524178.jpg)
![3](https://user-images.githubusercontent.com/66537460/84032016-f7743c80-a996-11ea-9a43-c29a92b07a19.jpg)

In the scenario selection window, the scenario name and description are badly displayed:
![4](https://user-images.githubusercontent.com/66537460/84032087-1246b100-a997-11ea-8417-a001e2ee56fe.jpg)

In the park window, the description is badly displayed but the park name is fine:
![5](https://user-images.githubusercontent.com/66537460/84032135-24c0ea80-a997-11ea-8060-dae62bb75f05.jpg)

It doesn't happen with original RCT and RCT2 scenarios:
![6](https://user-images.githubusercontent.com/66537460/84032163-31ddd980-a997-11ea-8a9b-01222c9ce295.jpg)

**Scenario file:**
[Vallée de l'île.zip](https://github.com/OpenRCT2/OpenRCT2/files/4745935/Vallee.de.l.ile.zip)

**Comment by AaronVanGeffen** [comment]
I believe this has been resolved with the new save format.

**Comment by rmnvgr** [comment]
Yes, the issue indeed doesn't appear anymore when creating a new scenario. Thank you!
