### ISSUE TITLE
Vista 32bit: entry point BCryptDeriveKeyPBKDF2 could not be located

### ISSUE THREAD

**Issue by arjanvlek** [OpenRCT2/OpenRCT2#11940]
**OS:** Windows Vista Business 32 bit
**Version:** 0.2.6
**Commit/Build:** 6c3c857 (that are the numbers after the version so I suppose that is the commit?)

The game is supposed to run on Vista but every time I open it this error pops up followed by a message that the main executable has stopped working. 

See the screenshot.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Install vanilla RCT2 then openrct2
2. Click openrct2 icon on the desktop 
3. See the error as in the screenshot 

**Dump file**

**Screenshots / Video:**

![openrct2](https://user-images.githubusercontent.com/10106652/84553262-f97e2880-ad13-11ea-9b1d-4dea567204b8.png)

**Save game:**

**Comment by James103** [comment]
@arjanvlek Are you really trying to run OpenRCT2 0.2.6 on Windows Vista? If so, this may be a possible clone or resurgence of #11294.

**Comment by IntelOrca** [comment]
Can you check the develop version?

**Comment by arjanvlek** [comment]
@James103 I’m doing a project with an old Sony VAIO UX UMPC from 2007 (YouTube video) and wanted to install some games on it. Since RCT2 / openrct2 are older and lightweight this was one of the games I were installing.

**Comment by AaronVanGeffen** [comment]
@arjanvlek If this is a resurgence of #11294, as @James103 suggests, you could try the 0.2.4 release. It should not have the issue. But please check whether a 'develop' build from after the 0.2.6 release presents the issue first.

**Comment by Gymnasiast** [comment]
#11294 was fixed *after* the 0.2.6 release. In general, you should ALWAYS try develop before reporting an error - lots of errors in releases are fixed shortly after.

**Comment by arjanvlek** [comment]
@Gymnasiast Thanks for letting me know. Cool that it is fixed nonetheless.

**Comment by Gymnasiast** [comment]
@arjanvlek Have you been able to try it? We have pre-built installers for `develop`, btw.
