### ISSUE TITLE
Banner text colors appear to be swapped between angles

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#11953]
**OS:** [Windows 10]
**Version:** [0.2.6]
**Commit/Build:** [3530a00]

On colorable banners the text in the lighter angle appears too dark, and the text in the darker angle looks too light. I think they need to be swapped.

Scrolling banners in vanilla RCT2:
![signvanilla](https://user-images.githubusercontent.com/6469413/84600106-65c56d00-ae77-11ea-8fb9-4e7d1ee00869.png)

Scrolling banners in OpenRCT2: 
![sign](https://user-images.githubusercontent.com/6469413/84600110-71189880-ae77-11ea-9fcc-16082b839a83.png)

**Comment by Gymnasiast** [comment]
Can you upload an affected save as well?

**Comment by deurklink** [comment]
Save file: 
[signtest.zip](https://github.com/OpenRCT2/OpenRCT2/files/4776984/signtest.zip)
