### ISSUE TITLE
Staff get caught in path loops and miss areas

### ISSUE THREAD

**Issue by joshuaboniface** [OpenRCT2/OpenRCT2#11957]
**OS:** Linux
**Version:** Master
**Commit/Build:** 1ea1d24f0015f2227b94b3c9c55bc4735cd78fc4

When setting fixed paths for Staff, especially Handymen, I've noticed that they sometimes get caught in loops. For instance, imagine a path has a TT shape - they will go down the first T, go back up it, hit the junction, turn left, hit the end of their path, turn back, then turn right down the first T again. I've noticed some Handymen do this 3 or 4 times, never hitting the second T or getting out of this loop, until I manually move them. It seems intermittent and random across the multiple maps I've played.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Create a Handyman.
2. Set it in an area shaped like TT.
3. Observe.

**Dump file**
N/A

**Screenshots / Video:**
N/A

**Save game:**
N/A

I'm sorry I don't have any of the dumps/screenshots/videos/saves, I kept just fixing them before remembering "hey, this is FLOSS I can submit an issue!", but I've noticed this happen fairly often if intermittently so hopefully someone else has seen it and can help corroborate! I don't know if this happens in vanilla RCT2, but I never noticed it in RCT1.

I wonder (just spittballing, I haven't checked the code) if there's some sort of fixed path selection that's causing this? Maybe a random left/right/straight at any junction would be a solution?

**Comment by duncanspumpkin** [comment]
Handymen do not do pathing they aimlessly wander. So this is expected. They will only do a bit of naive pathing to find a nearby sick.

**Comment by joshuaboniface** [comment]
That makes a lot of sense then, they'll aimlessly wander in circles then. Is there any sort of gameplay optimization around this (I'll admit I just picked RCT back up after many many years), or is this an enhancement that can be made? As mentioned I never noticed this sort of issue in RCT1, though maybe I just never noticed. It's only been since I started playing OpenRCT2 this past week that I noticed it.

**Comment by duncanspumpkin** [comment]
We do plan to improve the pathfinding. I'm not sure if handymen will be changed much though as they just about work fine.

**Comment by pineapplemachine** [comment]
In OpenRCT2-0.4.0-develop-c8df66f-windows-x64 I am often finding handymen or mechanics stuck walking back and forth endlessly between the same two tiles. The rest of a handyman's patrol zone becomes covered in vomit and trash, and then vandalized decorations. Mechanics become stuck in this loop while responding to a ride breakdown, and the breakdown never gets fixed until I manually intervene. It's very irritating and often hard to notice before it causes the park rating to tank. I don't think this problem has been solved!
