### ISSUE TITLE
Refactor Peep::OutsideOfPark

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#11963]
Peep::OutsideOfPark is a bool and should be converted to a bool.

**Comment by Jaswinder-Singh95** [comment]
Hi, I would like to do this

**Comment by Gymnasiast** [comment]
@Jaswinder-Singh95 Good! I have now assigned you. Let us know if you run into any problems. You can also ask questions on our Discord, if you like.

**Comment by TomasZilinek** [comment]
@Jaswinder-Singh95 Are you still working on this?

**Comment by TomasZilinek** [comment]
@Gymnasiast It is apparent that @Jaswinder-Singh95 has abandoned this issue. May I try to do it? :D

**Comment by Gymnasiast** [comment]
@TomasZilinek Sure, go ahead! :+1:
