### ISSUE TITLE
Maze height is higher than it should be

### ISSUE THREAD

**Issue by Derpercoaster** [OpenRCT2/OpenRCT2#11968]
OS: Windows 10
Version: 0.2.6
Build: I do not know.

Issue: The height of the hedge maze is a bit higher than it should be, which prevents other objects from being placed above it at the correct height.

To reproduce:

Simply build a maze, and try to make a path over it, 2 units higher than the maze itself (You can also build a prebuilt maze with paths going over it at 2 units higher than the maze itself.).

**Comment by Gymnasiast** [comment]
Guests sometimes jump up to peek over hedges. Building directly on top of the maze will just cause them to bump their heads.

**Comment by RFoxtea** [comment]
The "Crazy Castle" ride design that is shipped with the game includes elements that are placed 2 units above the base level of the attraction. Without enabling the "disable clearance checks" cheat it doesn't load in completely, lacking some vital path pieces.

![image](https://user-images.githubusercontent.com/62685776/85232390-d5e76c00-b3fe-11ea-8fed-976fd3ec4ffa.png)

Guests don't bump their heads at this height.

**Comment by Gymnasiast** [comment]
Right, so the clearance height is higher than 3 metres? That would indeed be a bug.

**Comment by Derpercoaster** [comment]
I would expect something in the original game files to be unaffected by in-game parameters (in such a way that it does not work properly). I knew it wasn't right.

**Comment by Gymnasiast** [comment]
Track element height is saved in the executable, not in the object files.

**Comment by C-Fergus** [comment]
The "Crazy Castle" ride design missing some queue pieces is reproducible on:

OS: Linux Mint 19.3 Cinnamon (Ubuntu 18.04)
Version: v0.2.6
Build: 6c3c857df on HEAD

**Comment by Gymnasiast** [comment]
Currently bisecting. The issue is not present in v0.2.0, but already present in v0.2.5.

**Comment by Gymnasiast** [comment]
Bug was introduced by 783ae13538f016cd99b8e49b8563865af9772d5c.

Ironically, the commit message read `This game action had been accidently assumed to be hard to do. Woops.`.

**Comment by C-Fergus** [comment]
Well found, odd that it was programmed with a specific clearance height constant for the maze as though the clearance height would be different for each ride. Would have thought the clearance height would be constant across all rides.

**Comment by Gymnasiast** [comment]
The game action used is specific to mazes, so we _know_ what the clearance height is. It indeed differs between ride types.
