### ISSUE TITLE
Plugins: ViewportWidget unable to be moved or resized

### ISSUE THREAD

**Issue by oli414** [OpenRCT2/OpenRCT2#11961]
**Version:** 0.2.6-885
**Commit/Build:** 1336e8a

The viewport widget from the plugin API does not function as expected when the position (x, y) or size (width, height) are updated after the creation of the window. The viewport stays in the same place, and keeps the same size.

```javascript
main() {
  var window = ui.openWindow({
    classification: "viewport-bug",
    title: "Viewport Bug",
    width: 112,
    height: 120,
    widgets: [{
      type: "viewport",
      name: "my-viewport"
      x: 6,
      y: 18,
      width: 100,
      height: 100
    }]
  });

  window.findWidget("viewport-bug").x = 56;
  window.findWidget("viewport-bug").width = 50;
}


registerPlugin({
    name: 'ViewportBug',
    version: '0.1',
    licence: "CC0",
    authors: ['Oli414'],
    type: 'local',
    main: main
});
```

And if I may expand upon that, the viewport widget is currently limited to a viewport per window. Any additional viewport widgets will be linked to the first one, and nothing will be displayed in the second viewport widget.

**Steps to reproduce:**
(Run the example code)
1. Create a window with a viewport widget.
2. Move, or resize the viewport widget.

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/2348094/84808887-9c32f180-b009-11ea-8e17-6c15f8430ca9.png)

**Comment by IntelOrca** [comment]
I think you said the dropdown and spinner widgets also doesn't move correctly. I will fix them all together.

**Comment by oli414** [comment]
Ah good point, I was just about to make a separate issue for that:
![image](https://user-images.githubusercontent.com/2348094/84899004-6264f800-b0a8-11ea-8999-b858674cefca.png)
