### ISSUE TITLE
Move remaining fields/arrays to RideTypeDescriptor

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#11964]
- [x] RideProperties - https://github.com/OpenRCT2/OpenRCT2/pull/11967
- [x] rideBonusValue - https://github.com/OpenRCT2/OpenRCT2/pull/11967
- [x] RideRatings - https://github.com/OpenRCT2/OpenRCT2/pull/11975
- [x] RideRatingsCalculateFuncTable - https://github.com/OpenRCT2/OpenRCT2/pull/11983
- [x] RideColourPresets - https://github.com/OpenRCT2/OpenRCT2/pull/11987
- [x] RideColourKey - https://github.com/OpenRCT2/OpenRCT2/pull/11996
- [x] Covered track piece availability - https://github.com/OpenRCT2/OpenRCT2/pull/11981
- [x] RideTypeEnumNames - https://github.com/OpenRCT2/OpenRCT2/pull/11999

Additionally:
- [x] Move RideTypeTrackPaintFunctionsOld to TestPaint.

**Comment by frutiemax** [comment]
I'll work on this if no one is.

**Comment by Gymnasiast** [comment]
Yeah, that's fine. I have left some comments on your PR already.

Also, we still need to take a decision on what to do with `RideTypeEnumNames`, so don't do that one yet.

**Comment by duncanspumpkin** [comment]
Great work!
