### ISSUE TITLE
Doors on prebuilt rides are sometimes deleted when the ride is placed

### ISSUE THREAD

**Issue by Derpercoaster** [OpenRCT2/OpenRCT2#12043]
OS: Windows 10
Version: 0.2.6
Build: I do not know

Issue: When placing rides that include track-doors (such as the ghost train), the doors are sometimes overridden by the ride itself. It mostly seems to occur when the track on either side is not a straight piece (which means both pieces need to be flat straight pieces, or the door won't load). I suspect that the game treats the door as a regular wall, and refuses to allow it to load since it is "in the way."

To reproduce: The easiest way to reproduce this is to just build the ghost train ride (assuming scenery is available for it), and some doors won't load in with the ride scenery.

**Comment by Gymnasiast** [comment]
Why did you delete the template? It is there for a reason.

**Comment by Derpercoaster** [comment]
Woops. I don't know what happened there. I think I was just too tired to notice. I have fixed it.

**Comment by duncanspumpkin** [comment]
Try again on the latest build we did correct something related to that relatively recently.

**Comment by Gymnasiast** [comment]
You can find the build in the title screen. It looks something like ab1c2d3.

**Comment by Broxzier** [comment]
@Derpercoaster Did you close this because it's not broken in the last builds?

**Comment by Derpercoaster** [comment]
> 
> 
> @Derpercoaster Did you close this because it's not broken in the last builds?

Sorry. I clicked that by accident.

**Comment by Gymnasiast** [comment]
You still need to specify the build. I asked you that a year ago and you still haven’t specified one. (Make sure it still occurs, it has been a year since you opened this.)

**Comment by Derpercoaster** [comment]
I checked and it no longer occurs. I think this issue can safely be closed.
