### ISSUE TITLE
Unify options for sprites.json and JSON object images

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#12045]
Currently, there are some naming differences in the fields, and some fields are only supported in one of the two. This needs to be unified.

|sprites.json|object JSON|
|---------------|-----------------|
|x_offset|x|
|y_offset|y|
|palette|?|
|forceBmp|-|
|-|format|

**Comment by spacek531** [comment]
I am willing to work on this after https://github.com/OpenRCT2/OpenRCT2/pull/16538

**Comment by Gymnasiast** [comment]
Has been done now.
