### ISSUE TITLE
Certain Ride/Attraction Icons use outdated images/sprites

### ISSUE THREAD

**Issue by Derpercoaster** [OpenRCT2/OpenRCT2#12042]
I suppose this technically isn't a bug, but I feel like I should bring this up. Some of the icons present in-game are from the first game rather than the second game and because of this, a few of them are outdated (for instance, the Bobsled Coaster uses its first-game icon, which shows sprites that are no longer in use/have been replaced).

**Comment by Gymnasiast** [comment]
Even though some icons where obviously created using Blackpool Pleasure Beach, they don't show old sprites. Here are the two for the Bobsleigh Coaster:

![afbeelding](https://user-images.githubusercontent.com/1478678/85526935-b329a300-b60a-11ea-924b-b92e58cd8c4a.png)

RCT1's icon on the left, RCT2's on the right.
