### ISSUE TITLE
Guests initial happiness number value in scenario options is misplaced or missing

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#12050]
**OS:** Windows
**Version:** 0.2.6
**Commit/Build:** f330a22

A new graphical bug I found several days ago. If you go to scenario options and select the Guests tab, you will see that the Guests initial happiness setting has its numerical value missing from its respective box, but dragging down the screen with right click will reveal said missing numerical value, but misplaced and duplicated several times. I could not find this bug in the 0.2.6 stable release.

- Reproducible in RCT2 (vanilla)? **No, as this bug does not exist in vanilla.**
- Specific to multiplayer? **No**

**Steps to reproduce:**
1. Open up either a scenario or the Scenario Editor.
2. Open up the scenario options window, then select the second tab, "Options - Guests".
3. You will see that the guests initial happiness value is missing. If you drag down the screen with the right mouse button, you will eventually see the guests initial happiness value appear, but outside of the box it is supposed to be in and duplicated. Scrolling back up will remove the duplicate numbers from view.

**Screenshot:**
![Way Over The Edge 2020-06-24 08-36-53](https://user-images.githubusercontent.com/61885939/85586802-13621a00-b5f6-11ea-90b1-b9dda68c472a.png)
As you can see here, this scenario has the guests set to 70% initial happiness but the 70% has been duplicated and displaced from its box multiple times.

**Comment by tupaschoal** [comment]
@TomasZilinek can you please bisect to see if this has to do with our recent coords changes?

**Comment by TomasZilinek** [comment]
@tupaschoal Indeed a mistake was made. We changed

```
screenCoords = { w->windowPos.x + w->widgets[WIDX_GUEST_INITIAL_HAPPINESS].left + 1,
                 w->windowPos.y + w->widgets[WIDX_GUEST_INITIAL_HAPPINESS].top };

```
into

```
screenCoords = w->windowPos + ScreenCoordsXY{ w->widgets[WIDX_GUEST_INITIAL_HAPPINESS].left + 1,
                                              w->windowPos.y + w->widgets[WIDX_GUEST_INITIAL_HAPPINESS].top };
```
`w->windowPos.y` is redundant

**Comment by tupaschoal** [comment]
Thanks for verifying so quickly! Can you please submit a PR fixing it?

**Comment by TomasZilinek** [comment]
Sure
