### ISSUE TITLE
Pre-build ride minimap shows entrance and exit at incorrect location

### ISSUE THREAD

**Issue by Basssiiie** [OpenRCT2/OpenRCT2#12065]
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** d4a35c5

When building pre-build rides, the entrance and exit are sometimes either far away from the correct position, or not shown at all, on the little map in the top left corner.

Some rides seem to still have the entrance and exit on the map. Some in correct location, some not, and on other rides it's gone (probably outside of view/window bounds?).

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Screenshots / Video:**
This is the Cobra pre-build ride, from the Corkscrew Roller Coaster.
![openrct2-incorrect-entrance-on-map](https://user-images.githubusercontent.com/20048660/85920965-a3af9180-b878-11ea-963a-06257e27b798.png)

Another example of the Goliath Giga Coaster, where the minimap is showing track that doesn't even exist.
![openrct2-not-existing-track](https://user-images.githubusercontent.com/20048660/85921092-bf676780-b879-11ea-9414-36ef7acb988f.png)

**Comment by duncanspumpkin** [comment]
Likely a coords refactor mistake.

**Comment by duncanspumpkin** [comment]
This has been broken for quite some time by the looks of it.

**Comment by Basssiiie** [comment]
Hey @duncanspumpkin thank you for your quick fix! I just checked on version bdbf128 and the minimaps where the entrance+exits were missing, are fixed now. But the two problems in the pictures are still present. :) 

I noticed as well the track shown on the Goliath picture is actually its lifthill shifted to the center of the minimap. It seems to improperly shift the pixels within bounds of the map when they go out of bounds? It doesn't explain the shifted entrances on the Cobra though.

**Comment by duncanspumpkin** [comment]
So you actually have 3 bugs described here:

1. Entrance and exits for none circuit rides x/y coordinates are relative to the last track position instead of origin.
2. Entrance and exits for none circuit rides rotation is relative to the last track position instead of origin.
3. Track pieces that are diagonal do not update the x/y coordinate of the next track piece causing the drawing of the preview to be incorrect.
