### ISSUE TITLE
New shortcut key request: sloping walls

### ISSUE THREAD

**Issue by EmielRCT** [OpenRCT2/OpenRCT2#12078]
When making buildings, or support structures, slopeable objects are great to use, especially for NCSO builders. 

The tile inspector has a function to slope these walls, but it takes quite a bit of time to do them one by one. It would be great if there was a shortcut key to do that.

In this case, there would need to be three options for setting the shortcut keys:
- Flat
- Right side up
- Left side up

<img width="524" alt="tileinspector" src="https://user-images.githubusercontent.com/64599015/85993904-4db52800-b9f7-11ea-9c84-2da039429200.png">

**Comment by frutiemax** [comment]
How about one shortcut key that when you press multiple times in change the slope so pressing 2 times put it Left side up, 3 times put it back to flat. It could also remember the current slope chosen.

**Comment by jayjay300** [comment]
@frutiemax you ever get this working or does this issue still need to be worked on?

**Comment by fredriktegnell** [comment]
Taking this one on as my first issue.
