### ISSUE TITLE
Fully or partly missing grid while building or removing scenery

### ISSUE THREAD

**Issue by nepumax** [OpenRCT2/OpenRCT2#12079]
OpenRCT2, v0.2.6-1004-g972c28619 (972c286 on develop) provided by GitHub
Windows (x86-64)

When placing rides with scenery or when lowering land or removing scenery the grid vanishes partly or completely.
This hasn't been just since last version, but a few versions before.

In the screenshots I used the Clear Scenery tool, increased its size to 12 and just placed the cursor in the middle of the screen. As you can see, as I just turned the view the grid vanishes.

![Forest Frontiers  120-05-29 10-56-13](https://user-images.githubusercontent.com/2079937/85993811-2fe7c300-b9f7-11ea-8c7b-bf741d4846de.png)
![Forest Frontiers  120-05-29 10-56-18](https://user-images.githubusercontent.com/2079937/85993812-30805980-b9f7-11ea-9b21-232854e17e0f.png)
![Forest Frontiers  120-05-29 10-56-21](https://user-images.githubusercontent.com/2079937/85993816-31b18680-b9f7-11ea-877d-5f72d2e35b25.png)
![Forest Frontiers  120-05-29 10-56-24](https://user-images.githubusercontent.com/2079937/85993818-324a1d00-b9f7-11ea-8261-3e469744cc14.png)

**Comment by Gymnasiast** [comment]
Is this bug present in release 0.2.6?

**Comment by nepumax** [comment]
Nope. Works fine in 0.2.6 master release.

**Comment by Fred-1044276** [comment]
This bug also exists with the other tools that involve a selectable area size (e.g. buying land/construction rights, scenery scatter, landscaping). If I attempt to buy any land/construction rights, the highlighted owned land/construction rights areas also suffer from the same issue.
![Okinawa Coast II  120-05-29 08-21-51](https://user-images.githubusercontent.com/61885939/86024807-4e8f8f00-b9e2-11ea-8567-d85fa2e32f75.png)

**Comment by nepumax** [comment]
I've downloaded the last development builds and the bug exists since version 9d965cc.

The last version without the bug is d254219!

**Comment by nepumax** [comment]
This is great! Thank you, it really works.
