### ISSUE TITLE
Missing triple thrill pack scenarios?

### ISSUE THREAD

**Issue by Terryloader** [OpenRCT2/OpenRCT2#12081]
Previously downloaded rct2 and triple thrill pack from steam, played it, all great!
Heard about openrct2 so thought would give it a go, downloaded it but almost all triple thrill pack scenarios are missing, previously completed scenarios are missing and any scenarios I can’t click on just say ‘complete earlier scenario to unlock this scenario’???? But I had all these scenarios on my normal RCT2 so why are they now not available?

**Comment by duncanspumpkin** [comment]
We don't read the progress file from RCT2 so you will need to complete each scenario to unlock the next. Alternatively if that is not how you want to play go into the options and disable "Enable progressive unlocking"

**Comment by Terryloader** [comment]
Ahhh brilliant! Apologies as not massively clued up on that kind of thing.
Thank you kindly!
