### ISSUE TITLE
Commit message Lint shouldn't prevent build generation

### ISSUE THREAD

**Issue by tupaschoal** [OpenRCT2/OpenRCT2#12144]
When I introduced the commit message lint on the CI, I intended for it to be educational on the PR side, but occasionally we do push things that make it fail (such as when the squash merge adds the PR number at the end at this makes it exceed the allowed length).

That was a minor problem, as it would just show up as broken, but everything else would be alright. Now since #12108 it can actually prevent the other CIs from running, which is OK from a PR standpoint, but not so for the main develop stream, as preventing the build generation can mess up with launchers, I guess. Its own commit presented this behavior https://github.com/OpenRCT2/OpenRCT2/commit/8f77bd94e15c462c9d1c5a8c20aa5ec829d32def.

So I'm open to discussions, some alternatives I think of, but haven't looked in depth on how feasible each of them is:
1 - Not making the builds depend on the commit lint step
2 - Restricting the lint commit to be just on pull request, not on push

**Comment by duncanspumpkin** [comment]
Just make the builds not rely on commit lint
