### ISSUE TITLE
Use Coords for some Ride functions

### ISSUE THREAD

**Issue by tupaschoal** [OpenRCT2/OpenRCT2#12159]
There are some ride functions using individual individual `x`, `y`, ... parameters. The goal is to make them use one of our Coords objects.

Note: You can do all of the functions in all PR (seems small overall), but please do each of them into a different commit.

- `find_closest_mechanic` should receive a `const CoordsXY&` instead of `x` and  `y`
- `get_station_platform` should receive a `const CoordsXYRangedZ&` instead of `x`,`y`, `z` and `z_tolerance`
- `check_for_adjacent_station` should receive a `const CoordsXYZ&` instead of `x`,`y` and `z`

Functions are at `src\openrct2\ride\Ride.cpp`

**Comment by duncanspumpkin** [comment]
`check_for_adjacent_station` direction should not be combined into the function signature for that one. Keep it separate its not describing a tile.

**Comment by tupaschoal** [comment]
Alright, updated the description, thanks!
