### ISSUE TITLE
Use Coords for Staff functions

### ISSUE THREAD

**Issue by tupaschoal** [OpenRCT2/OpenRCT2#12162]
Some Staff functions still take individual `x` and `y` parameters. The goal is to make them use `CoordsXY`.

Note: You can do all of the functions in all PR (seems small overall), but please do each of them into a different commit.

- `staff_is_patrol_area_set` should receive a `const CoordsXY&` instead of `x`  and `y`.
- `staff_set_patrol_area` should receive a `const CoordsXY&` instead of `x`  and `y`.
- `staff_toggle_patrol_area` should receive a `const CoordsXY&` instead of `x`  and `y`.

Functions are at `src\openrct2\peep\Staff.cpp`

**Comment by Jimver** [comment]
I'm working on it!
