### ISSUE TITLE
Use Coords for Viewport functions

### ISSUE THREAD

**Issue by tupaschoal** [OpenRCT2/OpenRCT2#12160]
Some viewport functions still take individual `x` and `y` parameters. The goal is to make them use `ScreenCoordsXY`.

Note: You can do all of the functions in all PR (seems small overall), but please do each of them into a different commit.

- [x] - `viewport_move` should receive a `const ScreenCoordsXY&` instead of `x` and  `y`
- [x] - `is_sprite_interacted_with` should receive a `const ScreenCoordsXY&` instead of `x` and  `y`
- [x] - `viewport_coord_to_map_coord` should receive a `const ScreenCoordsXY&` instead of `x` and  `y`
- [x] - `viewport_redraw_after_shift` should receive a `const ScreenCoordsXY&` instead of `x` and  `y`
- [x] - `is_sprite_interacted_with_palette_set` should receive a `const ScreenCoordsXY&` instead of `x` and  `y`

Functions are at `src\openrct2\interface\Viewport.cpp`

**Comment by tupaschoal** [comment]
Done by #12216

**Comment by duncanspumpkin** [comment]
I'd like to also see this comment applied as part of this refactor https://github.com/OpenRCT2/OpenRCT2/commit/27734e29714ca5ee1b0aa6ed7befd78630c254fc#r40554133 it's just a little tidy up.

**Comment by duncanspumpkin** [comment]
Reopening to keep track of my above request.
