### ISSUE TITLE
Use Coords for Vehicle functions

### ISSUE THREAD

**Issue by tupaschoal** [OpenRCT2/OpenRCT2#12165]
Some Vehicle functions still take individual `x`, `y` and `z` parameters. The goal is to make them use `CoordsXYZ`.

Note: You can do all of the functions in all PR (seems small overall), but please do each of them into a different commit.

- `steam_particle_create` should receive a `const CoordsXYZ&` instead of `x`, `y` and `z`.
- `vehicle_check_collision` should receive a `const CoordsXYZ&` instead of `x`, `y` and `z`.
- `try_add_synchronised_station` should receive a `const CoordsXYZ&` instead of `x`, `y` and `z`.

Functions are at `src\openrct2\ride\Vehicle.cpp`

**Comment by heliobatimarqui** [comment]
Can I get this one?

**Comment by tupaschoal** [comment]
Sure

**Comment by heliobatimarqui** [comment]
I've submitted a PR.
