### ISSUE TITLE
Main map icon is rotated by 90 degrees to the right

### ISSUE THREAD

**Issue by chaitanyathengdi** [OpenRCT2/OpenRCT2#12200]
The main map icon on the top is rotated to the right:
![image](https://user-images.githubusercontent.com/14993220/87188737-fa06e080-c30c-11ea-8e0a-a99f6e6cd4ae.png)
This is not so on RCT1 or RCT2. Is this intentional?

**Comment by AaronVanGeffen** [comment]
Very intentional: #9154

**Comment by chaitanyathengdi** [comment]
Oh, so that's a yellow 'N' :P All these years I used to think that it was a red lighthouse... :D
That's an interesting feature.
