### ISSUE TITLE
Unable to run game if Windows user name contains CJK

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#12204]
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** a47ca9d

If Windows user name contains CJK, (or maybe futher...) the game is unable to run, without any error messages or any dump files.
And @duncanspumpkin said like this via Discord:
> What is the directory that user documents and Steam is in. The commit that made this not work was changing from a Windows api function to a std function. It might be something about the directory structure.

**Steps to reproduce:**
1. Set windows user name as CJK
2. run the game

**Dump file**
No dump files are generated.

**Screenshots / Video:**
![Test GIF](https://user-images.githubusercontent.com/10726524/87218142-fdd94800-c38a-11ea-9f24-f5ff4061be43.gif)
Above GIF is tested in Win10 x32, VMware. Left is ``C:\OpenRCT2`` and right is ``C:\Users\테스트\Documents``. Windows user name is ``테스트`` (means "test")
See that OpenRCT2 directory is not generated in Doc when I ran openrct2.exe, and a blank command window is popped up and disappeared soon.

+) I think maybe #12148 could be related to this since screenshots are stored at Doc/OpenRCT2/screenshot, and I've reported many similar issues from other korean users (who might be using their account name as korean) which of they can't take screenshots.

**Comment by AaronVanGeffen** [comment]
Related to #12077?

**Comment by telk5093** [comment]
Yes, I think so. And it is solved by https://github.com/duncanspumpkin/OpenRCT2/commit/bd1781c9b7ebb200b8f58e27258b8bbbf4e450b2
