### ISSUE TITLE
Most of graphics are displayed as stopped

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#12213]
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** 76e7bfb

![2](https://user-images.githubusercontent.com/10726524/87241031-dc935d00-c459-11ea-807c-185fe65a3347.gif)

Most of graphic is not rendered properly, it is shown as stopped.
Some of bottom area is animated sometimes.

However it is fine at title sequence. It happens only at loaded/multiplayer game.

This issue is occured from 76e7bfb. Its fine at b43ce35

**Comment by tupaschoal** [comment]
Bisecting is correct, thanks for doing it.
Rotating makes the issue go away, I noticed.

**Comment by Gymnasiast** [comment]
I wonder if the cause mentioned in https://github.com/OpenRCT2/OpenRCT2/commit/76e7bfbf785b56648f3ce6a024dbb61ba86043aa was the actual cause. Are we sure it's not a big/small coordinate mismatch?

**Comment by Basssiiie** [comment]
Another image:

![image](https://media.discordapp.net/attachments/691735032531779684/732252355831005354/unknown.png?width=911&height=658)

I got little knowledge of the paint code, but it seems it doesn't redraw any updates to the screen after opening the park UP UNTIL you zoom in/out or rotate the camera. Then the bug disappears until you load another park.
