### ISSUE TITLE
"Realer" names of guests

### ISSUE THREAD

**Issue by chaitanyathengdi** [OpenRCT2/OpenRCT2#12228]
Is there any work going on for showing actual 'real' names of guests?
If not, I'd like to contribute something in that direction.
In short, something like this would be pretty cool IMO:
![2020-07-13 16_57_22-OpenRCT2](https://user-images.githubusercontent.com/14993220/87300269-30ba4200-c52b-11ea-9499-f49cad25ec03.png)
I'm also thinking of implementing name-surname matching so that we don't have a lot of names like 'Abdul Hanson'(Muslim name and Christian surname).

**Comment by duncanspumpkin** [comment]
The way names work in the game is designed to be really simple to generate and store. Changing that will require more memory space and may have an impact on sorting. Will definitely require a new save format if every peep had a unique name string rather than the current system.

**Comment by chaitanyathengdi** [comment]
Not a unique name string; names could repeat like in the real world. Just that instead of an array of characters for initials, there'll be an array of surname strings.

**Comment by IntelOrca** [comment]
The plugin system for now can be used to rename guests to whatever you like. There will be a limit of the number of custom names you can have though until a new save format is introduced.

**Comment by chaitanyathengdi** [comment]
@IntelOrca Custom names meaning set from within the game using the tag button, right? But here I'm talking about autogenerated guest names.

**Comment by AaronVanGeffen** [comment]
Much as I like the Creevey brothers, I have to agree this is best left to plugins, at least for now.

Eventually, I would like to see the name lists as custom objects, much like how Locomotion (and OpenLoco) handles town names. But that can only be done after the new save format has been merged.

**Comment by IntelOrca** [comment]
@chaitanyathengdi no, you can have a plugin which randomly renames every guest to something (without tracking them). This then gives you the advantage of allowing many custom name dictionaries. So if you wanted a dictionary full of Harry Potter character names, you could do that without any changes to OpenRCT2 itself.

**Comment by chaitanyathengdi** [comment]
@IntelOrca Oh, I see. I wasn't aware you could do something like that...
