### ISSUE TITLE
Show proper warning when unsuccesfully trying to load a save

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#12229]
Currently, no warning is shown in the GUI when you try to load a save (or a scenario via the load/save window), only in the console. In cases like this, RCT2 would warn "file contains invalid data".

Additionally, when fixing this, it would be nice if loading renamed .sea files would have an error message of its own.

**Comment by IntelOrca** [comment]
Something I noticed as well is that if you start OpenRCT2 via command line with a file that it unsuccessfully opens, you just get a black soft locked screen.
