### ISSUE TITLE
Getting 'load failed' when opening in VS 2019 Community

### ISSUE THREAD

**Issue by chaitanyathengdi** [OpenRCT2/OpenRCT2#12227]
I'm getting a 'load failed' error when importing the project in Visual Studio for development:
![image](https://user-images.githubusercontent.com/14993220/87293878-8f2df300-c520-11ea-85be-00074b36d6ef.png)
I used the C++ template when installing.
Is there anything missing in my setup?

I'm opening this on my Win10 64 bit laptop.

**Comment by AaronVanGeffen** [comment]
Did you follow the [compilation instructions](https://github.com/OpenRCT2/OpenRCT2/wiki/Building-OpenRCT2-on-Windows) from our wiki?

**Comment by chaitanyathengdi** [comment]
I read that, but I'm thinking I'm stuck even before any of that came into picture; this is loading into VS for the first time.
I'm getting these errors:
![image](https://user-images.githubusercontent.com/14993220/87294453-7540e000-c521-11ea-8a0a-f279f9121104.png)

![image](https://user-images.githubusercontent.com/14993220/87294491-81c53880-c521-11ea-84ad-ca47c64b3398.png)

**Comment by chaitanyathengdi** [comment]
Solved it. Turns out I was missing some component files, which was causing this issue.
