### ISSUE TITLE
Make track_design_update_max_min_coordinates() return its updated value instead of using output parameters

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#12234]

**Comment by tupaschoal** [comment]
But it doesn't really use output parameters:
https://github.com/OpenRCT2/OpenRCT2/blob/e99f4a23c55f59002ef3ed9f72e5ff6cd4a1a0f2/src/openrct2/ride/TrackDesign.cpp#L855-L861

**Comment by Gymnasiast** [comment]
The function name and calls suggested it did. Should have taken a better look, I guess.
