### ISSUE TITLE
Expand usage of Coords objects for maze functions

### ISSUE THREAD

**Issue by tupaschoal** [OpenRCT2/OpenRCT2#12243]
Some Maze functions still take individual coordinate parameters. The goal is to make them use `CoordsXY*`.

Note: You can do all of the functions in all PR (seems small overall), but please do each of them into a different commit.

- [x] - `MazeRemoveTrack` should receive a `const CoordsXYZD&` instead of `x`, `y`, `z` and `direction` (`src\openrct2\actions\RideDemolishAction.hpp`).
- [ ] - `maze_set_track` should receive a `const CoordsXYZD&` instead of `x`, `y`, `z` and `direction` (`src\openrct2\actions\GameActionCompat.cpp`).
- [ ] - `MazeGetSegmentBit` should receive a `const CoordsXY&` instead of `x` and `y` (`src\openrct2\actions\MazeSetTrackAction.hpp`).

**Comment by duncanspumpkin** [comment]
Please take remember that any change to a GameAction will require a network version increment.

**Comment by tupaschoal** [comment]
Thanks for the reminder!

**Comment by GalBr** [comment]
Can I finish this issue?
