### ISSUE TITLE
Placing down or clicking on items in-game is now next to impossible

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#12257]
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** 821dc60

A recently introduced bug has made it next to impossible to click on rides, guests, park borders, etc.; place down scenery, footpaths, rides, etc.; or use any tool that involves an adjustable area size (e.g. scenery scatter, land and water tools). Attempting to place down or click on anything is now a matter of being very lucky with the click hitboxes. This bug essentially makes the game unplayable. I couldn't find this bug in the 0.2.6 stable release.

- Reproducible in RCT2 (vanilla)? **No**
- Specific to multiplayer? **No**

**Steps to reproduce:**
1. Start up the game and load up any scenario.
2. Try to place down a new ride, scenery object, or footpath or click on anything (e.g. guests, rides). You will now find it near impossible to even click on or place down anything. Tools that involve an adjustable area size (e.g. buying land and construction rights, scenery demolish, land and water tools) also become virtually unusable because of this. Constructing footpaths above ground and tracked rides still works normally, though, as does selecting rides and guests through the Rides and Guest list windows, respectively.

**Screenshots / Video:**
![Sea Skimmer Park 2020-07-13 17-45-09](https://user-images.githubusercontent.com/61885939/87368665-24d27e00-c533-11ea-8d35-5b882ade3a53.png)
As you can see here, I have struggled to place down the Large Elm Tree on this map. I have wildly circled my mouse cursor around the screen, and very rarely am I actually able to place down said object (or if it blocks me, then it should say "Can't position this here... [object name] in the way").

**Comment by frutiemax** [comment]
I'll bisect it.

**Comment by tupaschoal** [comment]
Culprit is 78e40f53589fcdd92956028afd9b116d065d8ae4

**Comment by frutiemax** [comment]
For some reason, the recursive call on is_sprite_interacted_with_palette_set won't work correctly when passing a ScreenCoordsXY...

**Comment by frutiemax** [comment]
When converting x and y parameters to a int32_t, it does the same bug as passing a ScreenCoordsXY.

**Comment by frutiemax** [comment]
So I've changed the painter x and y to use int32_t and removed the lower 16 bits truncation and it works properly now.
