### ISSUE TITLE
Shortcut keys window inaccessible on higher scaling settings

### ISSUE THREAD

**Issue by Keatzee** [OpenRCT2/OpenRCT2#12262]
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** 6c3c857

The Shortcut keys window opens off-screen and is therefore inaccessible on higher scaling settings.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Set "Window scale factor" in the options menu to a value higher than 1.0 (might depend on screen resolution; I have it set to 1.5 at a 1920x1080 resolution)
2. Open the Shortcut keys window from the Controls and Interface tab

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/18078273/87475907-8ce89900-c5f3-11ea-9e81-bcb65cf65a72.png)

**Comment by AaronVanGeffen** [comment]
The window spawning code should be changed such that a top and left coordinates cannot be negative, I think.

**Comment by IntelOrca** [comment]
This still occurs.

**Comment by DKarandikar** [comment]
Taking a look at this, looks like a simple enough change in ClampWindowToScreen from https://github.com/OpenRCT2/OpenRCT2/pull/12256/files#r454995094
