### ISSUE TITLE
Sandbox Mode Cheat not working?

### ISSUE THREAD

**Issue by StrangeAnomoly** [OpenRCT2/OpenRCT2#12260]
When sandbox mode is enabled during traditional game play, sandbox mode doesn't seem to do anything. 

Seems to be a regression. 

Version: v0.2.6-1157-gc8b66dd28
OS: Windows

![bug](https://user-images.githubusercontent.com/41911850/87429339-8b12db80-c5db-11ea-992c-eda1586584f9.png)

**Comment by Gymnasiast** [comment]
Cannot reproduce this. I can change land ownership and build outside the park borders no problem. Will need to know more, especially you mean by "doesn't seem to do anything".

**Comment by duncanspumpkin** [comment]
Could perhaps be the mouse interaction bug and not realising that everything was broken

**Comment by Gymnasiast** [comment]
@duncanspumpkin Not sure about that - they say they are on https://github.com/OpenRCT2/OpenRCT2/commit/c8b66dd2894b4a7fc3f6403139553bedb86d255f (the fix for that bug).

**Comment by StrangeAnomoly** [comment]
I'm an idiot I somehow forgot that the Park Map Icon has the sandbox tools on it; not the park entrance window.
