### ISSUE TITLE
[Bug] Zooming in void zone moves the camera at the wrong location

### ISSUE THREAD

**Issue by frutiemax** [OpenRCT2/OpenRCT2#12276]
Zooming in the void zone when dezoomed moves the camera at the incorrect location.

- Put ANY scale
- Open Create you six flags magic mountain scenario
- Zoom out
- Zoom in the void zone (black zone)

It will recenter the view at the wrong location.
This bug does not occurs in vanilla game.

EDIT- It's there in v0.2.3 and perhaps even before...

**Comment by AaronVanGeffen** [comment]
Duplicate of #11623

**Comment by frutiemax** [comment]
I'll try to bisect this.
