### ISSUE TITLE
OpenGL renderer causing artifacts

### ISSUE THREAD

**Issue by chaitanyathengdi** [OpenRCT2/OpenRCT2#12297]
I couldn't take a screenshot(only renders a black background and white box), so I'm attaching a phone snap.
The OpenGL renderer causes black boxes and trails when the view is scrolled or when guests move.
OS: Windows 10 Home x64
12 GB RAM
Intel UHD Graphics(does not happen on my Win7 PC with a GTX 970 graphics card)
Intel graphics info:
![image](https://user-images.githubusercontent.com/14993220/87772691-b564d300-c83f-11ea-95ee-8d95a5cf2c0c.png)

Build: latest develop build(`31efe32ade161d2493c77a2df54a2ea8c75d51d2`) also happens with stable v0.2.6
Does not happen with Software or Software(hardware rendered) display modes.
![IMG_20200717_144743179](https://user-images.githubusercontent.com/14993220/87771282-c7457680-c83d-11ea-9387-f9325e77aba9.jpg)
Similar: #8623

**Comment by chaitanyathengdi** [comment]
DxDiag log: https://pastebin.com/16wLnDb7

**Comment by ZehMatt** [comment]
Is this also happening if you leave it unscaled?

**Comment by chaitanyathengdi** [comment]
@ZehMatt Yes:
![image](https://user-images.githubusercontent.com/14993220/87821090-e1f30c00-c88c-11ea-990e-c2de168825c4.png)

**Comment by IntelOrca** [comment]
@ZehMatt I can produce this on my Surface Pro. Do you think it is due to too many primitives been drawn in one draw call?

**Comment by ZehMatt** [comment]
There are indeed some hardware restrictions regarding the size of a vertex buffer which varies. We have to query GL_MAX_ELEMENTS_VERTICES and not exceed that.
