### ISSUE TITLE
Don't assign Hide GUI keyboard shortcut by default

### ISSUE THREAD

**Issue by frutiemax** [OpenRCT2/OpenRCT2#12292]
So I've pressed the "t" button accidently, but there was no visual way to get it back without pressing "t" again. There should be a visual way/indication of making the GUI reappear.

**Comment by tupaschoal** [comment]
I'm labeling as discussion because I think some people will say that's the point

**Comment by duncanspumpkin** [comment]
If there was a box that showed for a few seconds or a message that printed for a few seconds it would be fine

**Comment by janisozaur** [comment]
I'm of the "that's the point" crowd, but using a chat like we do with the chat key when joining multiplayer would be fine in my opinion.

**Comment by ocalhoun6** [comment]
Or maybe don't have the shortcut key for hiding the GUI assigned by default?

That way, it would be pretty much impossible to do by accident.

**Comment by janisozaur** [comment]
I really like the simplicity of this @ocalhoun6 and would to see it done.

There's a technical problem, I think, with that approach as removing the default keybinding will only affect new users - as I believe we fully instantiate keybindings on first run, so removing the default value would not fix it for current users.
