### ISSUE TITLE
Hyper-Twister booster pieces can no longer be built even with cheats

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#12305]
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** 3389893

The recent build, which was created by #12007, removed ride groups and made all rides in those ride groups into their own ride types. The ride groups weren't the only thing removed, however. What that build also removed was the booster and launched lift hill pieces from the Hyper-Twister, which greatly disappointed me as these now can't be built even with the "Enable all drawable track pieces" cheat activated (both track pieces are curiously missing from the HyperTwister.h file; they're not even in the ExtraTrackPieces field, which currently only has the steep lift hill and holding brake for drop). I am mostly against using the "Allow arbitrary ride type changes" and "Show vehicles from other track types" cheats when I'm playing, although these cheats are currently the only workaround to this (which I'd rather not use). On the other hand, any Hyper-Twister designs that have been previously built with said track pieces still have them functioning perfectly fine. It's also currently still possible to build those track pieces on this coaster type in the stable release.

My request: add the booster and launched lift hill track pieces back to the Hyper-Twister. Preferably make them available by default for RCT1 parity (the Steel Twister Roller Coaster in RCT1 allows the use of those track pieces during construction regardless of the train type selected), although they can still at first be accessible with the "Enable all drawable track pieces" cheat active like before this build.

**Steps to reproduce:**
1. Build a Hyper-Twister, with the "Enable all drawable track pieces" cheat.
2. When building either flat track or a gentle slope up, select the "Special..." dropdown menu.
3. Even with said cheat on, neither the Booster nor the Launched lift hill are anywhere to be seen.
4. Which leads to a more cheaty workaround (a workaround that I usually don't like) - using more cheats, namely "Allow arbitrary ride type changes" and "Show vehicles from other track types".

**Screenshots / Video:**
![Test Park 2020-07-17 10-43-18](https://user-images.githubusercontent.com/61885939/87856869-dc221880-c8d6-11ea-8eeb-6967547730fe.png)
![Test Park 2020-07-17 10-45-30](https://user-images.githubusercontent.com/61885939/87856870-de847280-c8d6-11ea-90ea-34b55dd2959c.png)
![Test Park 2020-07-17 10-52-26](https://user-images.githubusercontent.com/61885939/87856907-328f5700-c8d7-11ea-9afa-e78399e7488f.png)
The top two images show that it's currently impossible to build the booster and launched lift hill track pieces on a Hyper-Twister even with the "Enable all drawable track pieces" cheat on. The third image shows an example of an RCT1 prebuilt design that uses the Hyper-Twister Trains (wide cars) (which are known as the Roller Coaster Train (Non-Looping) in RCT1) *and* the launched lift hill track piece together (which is u(1114)), as well as a custom design I made using boosters (shown on the right) way before the build.

![RollerCoaster Tycoon 7_18_2020 09_19_31](https://user-images.githubusercontent.com/61885939/87857045-7cc50800-c8d8-11ea-8e42-49ac4fe2b293.png)
This image shows a twister coaster I have built in RCT1 that uses the Roller Coaster Train (Non-Looping) (which, as previously noted above, corresponds to the Hyper-Twister Trains (wide cars) in RCT2) on a non-inverting track with launched lift hills and boosters. (Ignore the corkscrew coaster booster pieces in this screenshot, as proper twister coaster track pieces with boosters were never implemented in RCT1, only in RCTC and Open)

**Comment by Gymnasiast** [comment]
Was this lengthy post really necessary? All it would have taken was a single-line pull request. And I already explained to you why we diverged from how RCT1 handled it, so there's little point in asking yet again.
