### ISSUE TITLE
Finance/Research title text has gone

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#12315]
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** ee39bff

There is no title text in the finance and research windows.

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/10726524/87872459-c35b5500-c9f3-11ea-9fa3-f6ff35e66f01.png)

**Comment by AaronVanGeffen** [comment]
Looks to be a regression from 00461aedf34b49b263fac6d3a47747b9535dc7c7.
