### ISSUE TITLE
Colour tab of Pirate Ship shows the Suspended coaster's support

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#12314]
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** ee39bff

Colour tab of Pirate ship shows the suspended coaster's support, not a pirate ship's one.

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/10726524/87870968-b6386900-c9e7-11ea-94a5-0f91367c7374.png)

**Comment by Umdlye** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/ee39bff1b419fc09426f7eb88da76ef1bfbe5b5b/src/openrct2/ride/thrill/meta/SwingingShip.h#L53 should be `SET_FIELD(ColourPreview, { SPR_RIDE_DESIGN_PREVIEW_PIRATE_SHIP_TRACK, SPR_RIDE_DESIGN_PREVIEW_PIRATE_SHIP_SUPPORTS }),`

**Comment by AaronVanGeffen** [comment]
Sounds good, could you file a PR?

**Comment by Umdlye** [comment]
Someone less likely to screw things up than me should probably do the PR and make the ride's name match all around the code (`PirateShip.cpp`/`SwingingShip.h` etc.)
