### ISSUE TITLE
Game soft-locks when loading a save file via command line fails

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#12312]
Something I noticed as well is that if you start OpenRCT2 via command line with a file that it unsuccessfully opens, you just get a black soft locked screen.

_Originally posted by @IntelOrca in https://github.com/OpenRCT2/OpenRCT2/issues/12229#issuecomment-657631998_

**Comment by janisozaur** [comment]
I complained about the black screen years ago. What does "soft locked" mean, though?

**Comment by ZehMatt** [comment]
It means you can no longer interact with the game being able to do nothing.

**Comment by IntelOrca** [comment]
@janisozaur https://en.wiktionary.org/wiki/softlock

You may still be able to interact with the game, but it is impossible to advance. The game is stuck but it has not crashed and is still running through the game loop.
