### ISSUE TITLE
Attempting to access Scenario Editor crashes the game

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#12325]
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** 0a5b75e

Usually, the game crashes on me if I don't close the game quickly enough after exiting the Scenario Editor, but this time, the game managed to crash on me right upon starting up the Scenario Editor, which is unfortunate as I was planning to make a couple of new scenarios or revamp some of my existing scenarios this week. I haven't been able to get this crash on the stable build so far.

**Steps to reproduce:**
1. Start up the game.
2. Attempt to open up the Scenario Editor. If an error message appears on the screen, the game has crashed.

**Dump file**
[edfa01d2-3098-4fc9-86ee-d6470b6e7126.zip](https://github.com/OpenRCT2/OpenRCT2/files/4944820/edfa01d2-3098-4fc9-86ee-d6470b6e7126.zip)

**Comment by James103** [comment]
> Usually, the game crashes on me if I don't close the game quickly enough after exiting the Scenario Editor

Do you know of any issues relating to this statement?

**Comment by Broxzier** [comment]
Did you close this because the issue is resolved? The game should never crash, so if it was something wrong with your installation, it should be something we can catch instead.
