### ISSUE TITLE
Refactor widget definitions

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/OpenRCT2#12329]
We are currently in the process of refactoring the widget definitions for all widgets.  The old-style widget definitions read as follows:

```cpp
    { WWT_BUTTON,           1,  73,     83,     60, 69,     STR_DROPDOWN_GLYPH,     STR_NONE },                     // page dropdown button
    { WWT_DROPDOWN,         1,  120,    261,    59, 70,     0xFFFFFFFF,             STR_INFORMATION_TYPE_TIP },     // information type dropdown
    { WWT_BUTTON,           1,  250,    260,    60, 69,     STR_DROPDOWN_GLYPH,     STR_INFORMATION_TYPE_TIP },     // information type dropdown button
    { WWT_FLATBTN,          1,  273,    296,    46, 69,     SPR_MAP,                STR_SHOW_GUESTS_ON_MAP_TIP },   // map
    { WWT_FLATBTN,          1,  297,    320,    46, 69,     SPR_G2_SEARCH,          STR_GUESTS_FILTER_BY_NAME_TIP },// filter by name
```

The old parameter order is the same as the internal widget structure order: type, colour, left, right, top, bottom, content, and tooltip.

The new-style definitions change this to use a position (x, y) and dimensions (width, height) tuple instead, as follows:
```cpp
    MakeWidget({ 73, 60}, { 11,  10}, WWT_BUTTON,   1, STR_DROPDOWN_GLYPH                               ), // page dropdown button
    MakeWidget({120, 59}, {142,  12}, WWT_DROPDOWN, 1, 0xFFFFFFFF,         STR_INFORMATION_TYPE_TIP     ), // information type dropdown
    MakeWidget({250, 60}, { 11,  10}, WWT_BUTTON,   1, STR_DROPDOWN_GLYPH, STR_INFORMATION_TYPE_TIP     ), // information type dropdown button
    MakeWidget({273, 46}, { 24,  24}, WWT_FLATBTN,  1, SPR_MAP,            STR_SHOW_GUESTS_ON_MAP_TIP   ), // map
    MakeWidget({297, 46}, { 24,  24}, WWT_FLATBTN,  1, SPR_G2_SEARCH,      STR_GUESTS_FILTER_BY_NAME_TIP), // filter by name
```

However, we still have to go over all widget definitions manually. Not just to update the widget definitions, but also to verify the window is still behaving correctly!

Fortunately, the process is largely automated using [a Python script](https://gist.github.com/AaronVanGeffen/fb2e5bf4612ca157cd8a29c2e09c6820). **Please use this script if you want to work on this issue.**

## Instructions

What follows is a simplified step-by-step guide to updating one window.

1. Ensure you have a Python 3 interpreter at hand.
2. Download [the Python script](https://gist.github.com/AaronVanGeffen/fb2e5bf4612ca157cd8a29c2e09c6820) mentioned earlier.
3. Open the script in a text editor
4. Choose a window from the table below.
5. Open the window file in a text editor.
6. Copy one set of the window's widget definitions to the script's input parameter (`input` at the bottom).
7. Adjust the `env` parameter (environment) for any constants in the window file. (`WW` and `WH`, most of the time)
8. Run the script.
9. Copy the script's output back to the window, replacing the old definitions.
10. Remove any superfluous definitions from the widget (empty content and/or tooltip).
11. Repeat for any other set of widget definitions in the same file (e.g. other tabs).
11. Compile and test the window!
12. Commit and PR

We welcome you combining several windows into one PR. Particularly for the smaller windows, it is not worth the overhead of an individual PR.

## List of windows

The following is a list of all window files that require updating. When a window is being worked on or done, it will be indicated in the table below to prevent disappointment.

File                        | Status | PR#   
--------------------------- | ------ | ------
About.cpp                   |  done  | #12275 
Banner.cpp                  |  done  | #12340 
Changelog.cpp               |  done  | #12340 
Cheats.cpp                  |  done  | #12303 
ClearScenery.cpp            |  done  | #12219 
CustomCurrency.cpp          |  done  | #12340 
DebugPaint.cpp              |  done  | #12340 
DemolishRidePrompt.cpp      |  done  | #12340 
Dropdown.cpp                |  done  | #12354 
EditorBottomToolbar.cpp     |  done  | #12275 
EditorInventionsList.cpp    |  done  | #12275 
EditorMain.cpp              |  done  | #12354 
EditorObjectiveOptions.cpp  |        | 
EditorObjectSelection.cpp   |  done  | #12275 
EditorScenarioOptions.cpp   |  done  | #12354 
Error.cpp                   |  done  | #12275 
Finances.cpp                |  done  | #12275, #12340 
Footpath.cpp                |  done  | #12275 
GameBottomToolbar.cpp       |  done  | #12275 
Guest.cpp                   |  done  | #12354 
GuestList.cpp               |  done  | #12275 
InstallTrack.cpp            |  done  | #12354 
Land.cpp                    |  done  | #12219 
LandRights.cpp              |  done  | #12354
LoadSave.cpp                |  done  | #12354
Main.cpp                    |  done  | #12354
Map.cpp                     |  done  | #12354
MapGen.cpp                  |  done  | #12521
MapTooltip.cpp              |  done  | #12521
MazeConstruction.cpp        |  done  | #12521
Multiplayer.cpp             |  done  | #12521
MusicCredits.cpp            |  done  | #12521
Network.cpp                 |  done  | #12521
NetworkStatus.cpp           |  done  | #12275 
NewCampaign.cpp             |  done  | #12521
NewRide.cpp                 |  done  | #12521
News.cpp                    |  done  | #12275 
NewsOptions.cpp             |  done  | #12275 
ObjectLoadError.cpp         |  done  | #12521
Options.cpp                 |  done  | #12316 
Park.cpp                    |  done  | #12521
Player.cpp                  |  done  | #12275 
Research.cpp                |  done  | #12275 
Ride.cpp                    |  done  | #12521
RideConstruction.cpp        |  done  | #12320 
RideList.cpp                |  done  | #12320 
SavePrompt.cpp              |  done  | #12320, #12340 
Scenery.cpp                 |  done  | #12320 
SceneryScatter.cpp          |  done  | #12320 
ServerList.cpp              |  done  | #12320 
ServerStart.cpp             |  done  | #12320 
ShortcutKeyChange.cpp       |  done  | n/a
ShortcutKeys.cpp            |  done  | #12320 
Sign.cpp                    |  done  | #12521
Staff.cpp                   |  done  | #12521
StaffFirePrompt.cpp         |  done  | #12521
StaffList.cpp               |  done  | #12275 
TextInput.cpp               |  done  | #12503
Themes.cpp                  |  done  | #12503
TileInspector.cpp           | in progress | #12869
TitleCommandEditor.cpp      |  done  | #12503
TitleEditor.cpp             |  done  | #12503
TitleExit.cpp               |  done  | #12264 
TitleLogo.cpp               |  done  | #12264 
TitleMenu.cpp               |  done  | #12264 
TitleOptions.cpp            |  done  | #12275 
TitleScenarioSelect.cpp     |  done  | #12264 
Tooltip.cpp                 |  done  | #12264 
TopToolbar.cpp              |  done  | #12503
TrackDesignManage.cpp       |  done  | #12503
TrackDesignPlace.cpp        |  done  | #12503
TrackList.cpp               |  done  | #12503
ViewClipping.cpp            |  done  | #12503
Viewport.cpp                |  done  | #12503
Water.cpp                   |  done  | #12219

**Comment by tupaschoal** [comment]
I think this can be closed already, can't it @AaronVanGeffen ?

**Comment by AaronVanGeffen** [comment]
@tupaschoal No, @Broxzier hasn't finished the tile inspector window yet.

**Comment by AaronVanGeffen** [comment]
With #12869 in, I believe this is done.
