### ISSUE TITLE
Use CoordsXY in track_remove_station_element

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#12331]
Refactor `track_remove_station_element` to take a `const CoordsXYZD& ` instead of the individual components. Take care with the Z value as it is currently in the form of smallZ and CoordsXYZD take bigZ (`*COORDS_Z_STEP`). There are a number of loops that should be refactored to also use `CoordsXY` structures instead of `removeX/Y, stationX/Y0/1`. When doing this refactor do not do all of the changes in one commit. Split it up into a number of commits. One for changing the function signature and callers, one commit for changing `removeX/Y` so on and so on.

Please remember the commit style: https://github.com/OpenRCT2/OpenRCT2/wiki/Commit-Messages
And the coding style: https://github.com/OpenRCT2/OpenRCT2/wiki/Coding-Style

**Comment by ion232** [comment]
I'm going to work on this particular issue
