### ISSUE TITLE
Remove goto from footpath_chain_ride_queue

### ISSUE THREAD

**Issue by tupaschoal** [OpenRCT2/OpenRCT2#12335]
https://github.com/OpenRCT2/OpenRCT2/blob/d10b615eb33f6cd597340d83d68eaaa97c1a493e/src/openrct2/world/Footpath.cpp#L1093-L1100

**Comment by Ron4u** [comment]
https://github.com/OpenRCT2/OpenRCT2/pull/12343/commits/58e083e64e09c5477ec7ac193c0ecccf3b8a4ea9

**Comment by Ron4u** [comment]
i have a pull request for the same. please check.

**Comment by VinPT** [comment]
If no one minds, I would like to try to fix this one.

**Comment by tupaschoal** [comment]
Hello @VinPT , this is in review on #12344 , but it seems a bit abandoned, so you can do it. Do read the comments and diff there first to get some insight.

**Comment by VinPT** [comment]
ok thanks will do
