### ISSUE TITLE
Remove goto from DecideAndBuyItem

### ISSUE THREAD

**Issue by tupaschoal** [OpenRCT2/OpenRCT2#12337]
https://github.com/OpenRCT2/OpenRCT2/blob/d10b615eb33f6cd597340d83d68eaaa97c1a493e/src/openrct2/peep/Guest.cpp#L1541-L1551

**Comment by batorni** [comment]
I can pick this one up

**Comment by tupaschoal** [comment]
Go ahead

**Comment by rpstester** [comment]
@batorni @tupaschoal  is anyone still working on this issue?

**Comment by tupaschoal** [comment]
No, we closed the PR above for lack of activity. If you intend on picking this up, please give the comments in the PR a read before starting 😃

**Comment by rpstester** [comment]
It looks like all this needs is an else clause to avoid the " if ((shopItem != SHOP_ITEM_MAP)" clause, correct?  So 
if umbrella and raining
//do nothing
else if map and souvenir and no voucher...
end if
if no voucher...

**Comment by tupaschoal** [comment]
It isn't hard, but it's not that simple I'd say, note that there are two gotos in the function. My recommendation is doing it in a series of commits, which we can individually review, but squash later.
Extract one of the `goto` blocks into a function and call it where it used to be.
Extract the other
Merge if applicable

**Comment by rpstester** [comment]
How would you like it if I split the decide code from the buy code?  You know, so each function/method does one basic task.  Would that be outside the scope of this issue?

**Comment by tupaschoal** [comment]
As long as you do it in separate commits, so it becomes easier to review, it can be in the same PR. I mean, only one of your commits can be "Fix #....", but you can have some before and after to refactor the vicinity if it makes for a more readable code.
