### ISSUE TITLE
When loading an SV6 file, verify that park entrances are actually there

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#12355]
Currently, park entrances that have been removed without updating the gParkEntrances global will continue to take up a slot. Instead, verify each entrance is actually there when loading an SV6.

https://forums.openrct2.org/topic/5127-unable-to-deselect-park-entrance-%E2%80%93-but-none-on-map/?tab=comments#comment-24421

**Comment by 733737** [comment]
Is this bug still present? If so I am willing to take a crack at fixing it myself. How do I reproduce this particular issue?

**Comment by 733737** [comment]
when I deleted the park entrance using the tile inspector, the object selection no longer listed it as in use, so I assume this bug no longer applies

**Comment by tupaschoal** [comment]
Closing as fixed. Please reopen if it's still applicable @Gymnasiast !
