### ISSUE TITLE
Opening SC4 or SV4 centres viewport on void

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/OpenRCT2#12356]
**OS:** Arch Linux
**Version:** 0.2.6+
**Commit/Build:** 205fc3332bb70f62c8fc4c3d3d4de878d5646dcb

When I open an SC4 or SV4 file, the viewport is centred on the void instead of the position on file:

![Diamond Heights  120-06-22 22-08-23](https://user-images.githubusercontent.com/604665/88223523-e726d100-cc67-11ea-9ad5-902581dae5ea.png)

Zooming out reveals:

![Diamond Heights  120-06-22 22-08-27](https://user-images.githubusercontent.com/604665/88223527-e726d100-cc67-11ea-81e7-5679a04672e8.png)

**Comment by tupaschoal** [comment]
Maybe related to #12210 and #12213?
