### ISSUE TITLE
Weather Effects not Synchronized in Multiplayer

### ISSUE THREAD

**Issue by fraune** [OpenRCT2/OpenRCT2#12368]
**OS:** Windows 10 (x64) version 2004
**Version:** 0.2.6
**Commit/Build:** 6c3c857

Was playing multiplayer with one other person on Ivory Towers today (I was host), while we were chatting on the phone. After about a full year in game, we noticed that we weren't experiencing weather effects at the same time as each other. The person I was playing with said she saw that people were taking out their umbrellas and there was rain, and for me it was still sunny.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Save game:**
[Ivory Towers.zip](https://github.com/OpenRCT2/OpenRCT2/files/4970119/Ivory.Towers.zip)

I know it can be a bit difficult getting to the root of these kinds of issues. I'm new to this repo, so let me know if there's other info I can provide to help. Thanks!

**Comment by janisozaur** [comment]
The client must've received a "desync" message and ignored it. These are hard to find and I doubt the save provided alone would suffice for investigation, but we'll still try.

There is an option to gather additional data that would let us inspect this, I think it has to be enabled on both ends manually. @ZehMatt do you recall the option name?

**Comment by ZehMatt** [comment]
The setting to help us figure out the desync issue is called ```desync_debugging``` which can be found in config.ini, this has to be set to true by the host.

**Comment by fraune** [comment]
haha perfect i just found that. I assume the data dumps into the serverlogs directory? Does the client need to set this too?

**Comment by ZehMatt** [comment]
No, and once the client desyncs the client will have a report in "OpenRCT2\Desyncs"

**Comment by fraune** [comment]
Okay, I appreciate the advice. Next time I host again I can see if I can get her desync report(s) out of my own curiosity. I assume that desync debug data is pretty plentiful, since I always see a few dozen servers advertised. Would it actually be helpful for me to provide this extra info?

**Comment by duncanspumpkin** [comment]
Not many people supply the debug data to us. So please upload it. It's quite a detailed log of exactly what bits are different in all of the sprite data.

**Comment by fraune** [comment]
I'll make sure to upload the data next time we play and experience a desync.

**Comment by fraune** [comment]
I have a desync log file. I'm also interested to learn more context of how this type of log might be used to improve the multiplayer experience. For example, if a game save file or other information could supplement this information, maybe future dumps of this information could be more helpful.

[desync_18074237459153020737_193850.txt](https://github.com/OpenRCT2/OpenRCT2/files/5004983/desync_18074237459153020737_193850.txt)

**Comment by duncanspumpkin** [comment]
Looks like a desync of a couple vehicles.

**Comment by ZehMatt** [comment]
Have you used the simulate mode on any ride perhaps?

**Comment by fraune** [comment]
Absolutely, I use simulate mode for basically every custom track I build.

**Comment by ZehMatt** [comment]
I found a way to cause an instant desync, it appears the the simulation considers the ghost piece as a valid track piece even tho it can't advance, it yet tries to. The other player is not aware of this ghost piece and the train behaves differently.

**Comment by fraune** [comment]
I was able to replicate this method to cause a desync. I chose to build a Corkscrew RC and created the new ride with nothing but two station platforms pieces (long enough to fit the shortest train this ride supports–two cars), and enabled simulation mode. Like @ZehMatt said, this seems to be enough to consistently cause an immediate desync.
