### ISSUE TITLE
Enhancement: Editable ride ratings

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#1236]
Over on reddit a user has suggested it would be nice to be able to edit ride ratings (excitement, nausea, intensity) http://www.reddit.com/r/openrct2/comments/38q86q/request_editable_excitementnauseaintensity/

I suggest maybe creating an in game console command to do this.

**Comment by IntelOrca** [comment]
@duncanspumpkin "Ride ratings are only calculated on the first use after testing/opening..."
This is not true, the game will keep enumerating through every ride updating the ride ratings as the excitement can change based on surrounding scenery.

**Comment by duncanspumpkin** [comment]
Oh really didnt know that.

**Comment by Nubbie** [comment]
Implemented with #5259
