### ISSUE TITLE
Show Guest Purchases as Animation not working in Multiplayer

### ISSUE THREAD

**Issue by fraune** [OpenRCT2/OpenRCT2#12369]
**OS:** Windows 10 (x64) version 2004
**Version:** 0.2.6
**Commit/Build:** 6c3c857

I've been playing 0.2.6 Multiplayer with one other person semi-frequently lately (with me as host). I have noticed that on practically every scenario I play (RCTC, RCT2, custom), the animations for guest purchases don't show for me or the other player. We have both tried restarting the game, our computers, and toggling the checkbox in the options menu. As soon as I revert to single-player mode, all my purchases show as animations again. I first noticed it on the "Over the Falls" scenario, but the issue has been present ever since.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**
1. Start up a server
2. Choose new game or load an existing save (I'd suggest try starting a new scenario for Three Monkeys park or another park that already has a popular ride built and guests in the park so you can see it immediately)
3. The other user does not even need to connect, the issue is consistently apparent immediately after I start the server.

**Comment by duncanspumpkin** [comment]
It's disabled on purpose as it causes desyncs

**Comment by fraune** [comment]
I'll suggest in the short term, the box be greyed out and shown as unchecked when in multiplayer, to better indicate to the user that this feature is deliberately disabled.

**Comment by ocalhoun6** [comment]
@fraune Maybe also with a mouseover tooltip that explains why it's not greyed out. "Not available in multiplayer." or something. That would make it even more clear, less confusing.

**Comment by ZehMatt** [comment]
This was fixed.
