### ISSUE TITLE
Theme fails to change color of this window (the inside part)

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#1238]
![scr14](https://cloud.githubusercontent.com/assets/3945538/8020699/e7e9a1b2-0c50-11e5-9695-f9eed7831ba0.png)

**Comment by duncanspumpkin** [comment]
https://github.com/IntelOrca/OpenRCT2/blob/develop/src/windows/track_place.c#L117 requires modification to look up the back ground colour and memset to that.

**Comment by Gymnasiast** [comment]
I have been changing the number a few times (which indeed changes the colour) but I can't determine how its computed from the "normal" colours, which range from 0 through 31.

**Comment by IntelOrca** [comment]
look at widget_draw and find the a good colour map table to use.

**Comment by mrtnptrs** [comment]
I can confirm this bug still happens. Sorry, I know this is a bit useless comment, but I saw that @IntelOrca made a comment with probably the solution.
