### ISSUE TITLE
Refactor PeepItem to use strong enum

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#12395]

**Comment by danty178** [comment]
Hi everyone, it was my first contribute to the community, I'm not sure if I've pushed my commit to the right place. Please take account the my last commit and ignore the two others. I'm sorry for the inconvenience.

**Comment by tupaschoal** [comment]
@danty178 you pushed to your own fork, you now need to open a pull request to ours: 
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request
