### ISSUE TITLE
Refactor FILTER_PALETTE_ID to use strong enum

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#12403]

**Comment by Lukasz-Pe** [comment]
I'm working on it.
Commit 9fcf1c83867b95f4480ff992606860673809f73f[](https://github.com/Lukasz-Pe/OpenRCT2/commit/9fcf1c83867b95f4480ff992606860673809f73f).
I need to check all static casts to see which can be replaced with variable of enum type or EnumToFlag or otherwise reworked.
