### ISSUE TITLE
Zero Clearance shortcut

### ISSUE THREAD

**Issue by Belzebub** [OpenRCT2/OpenRCT2#1242]
Hi!
Is it possible to add a shortcut for Zero clearances in the future?
It's a feature you need quite often to build a park and a shortcut would help a lot!

Also are you planning to change the Zero clearance function to a total Zero Clearance function or keep it defined by tile?
Thanks for everything you do here!

**Comment by ThomasdenH** [comment]
Currently it is a irreversible kind of hack, it changes the effective height of objects to zero so they wont collide with new ones. In the future this function will work more elegantly as a toggle button by not checking whether an object will fit. So yeah, no permanent tile selection but a map wide toggle.

**Comment by Belzebub** [comment]
Thanks for the reply! Looking forward to the updated function, as it is very tedious to change to 8cars everytime you want to place something on paths or underwater for example...
Is it planned to add a shortcut to it, though? Also a shortcut for game speed would be very useful I think.

**Comment by PFCKrutonium** [comment]
Game speed can already be controlled using the "-" and "=" (Shares the key with +) beside your backspace.

**Comment by IntelOrca** [comment]
I will close this as it is now a toggle option from the toolbar. I will re-open it if people would still find a shortcut for that useful.
