### ISSUE TITLE
Refactor KeyboardShortcut to use strong enum

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#12460]

**Comment by frutiemax** [comment]
I'll work on this.

**Comment by autinerd** [comment]
A question to all enum refactorings: Shall we do every issue in its own pull request or is it possible to do several issues in one PR with one commit per issue?

**Comment by duncanspumpkin** [comment]
@autinerd if they are very small and localised then yes group them together but there tends to be quite a few things that need tweaked which lends itself to a single pr for each one.
