### ISSUE TITLE
Path check to g1.dat accidentally broken

### ISSUE THREAD

**Issue by autinerd** [OpenRCT2/OpenRCT2#12486]
**OS:** Linux
**Version:** 0.2.6
**Commit/Build:** 9db2aac3b

https://github.com/OpenRCT2/OpenRCT2/blob/ba10b8478961845efeeda6ff3b956d34b770c0b4/src/openrct2/cmdline/RootCommands.cpp#L370-L375

Currently the command `openrct2 set-rct2` fails if the path is valid. The `!` was deleted when the called function was changed, so I think it was accidentally.

**Comment by Gymnasiast** [comment]
Looks like you're right. Could you create a pull request for this?

**Comment by autinerd** [comment]
Of course! 😊
