### ISSUE TITLE
Remove extra SPRITE_INDEX_NULL check

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#12497]
There are a number of instances where the following occurs:

```
if (spriteIndex == SPRITE_INDEX_NULL)
    return / continue
auto entity = GetEntity<...>(spriteIndex);
if (entity == nullptr)
    return / continue
```
This is going to end up checking if the `spriteIndex == SPRITE_INDEX_NULL` twice as the GetEntity function also checks this and returns `nullptr`. Therefore it can be simplified to:
```
auto entity = GetEntity<...>(spriteIndex);
if (entity == nullptr)
    return / continue
```
Only perform this refactor for the `GetEntity` or `TryGetEntity` functions. Note: I'm halfway through a GET_VEHICLE to GetEntity refactor so there might be more after that is completed.

**Comment by Lukasz-Pe** [comment]
Hello!

I'd like to work on this. I'd appreciate a bit more info.

I have also looked on the code and found this function:
```
Staff* ride_get_mechanic(Ride* ride)
{
    if (ride->mechanic != SPRITE_INDEX_NULL)
    {
        auto peep = GetEntity<Peep>(ride->mechanic);
        if (peep != nullptr)
        {
            auto staff = peep->AsStaff();
            if (staff != nullptr && staff->IsMechanic())
                return staff;
        }
    }
    return nullptr;
}
```
and changed it to:
```
Staff* ride_get_mechanic(Ride* ride)
{
        auto peep = GetEntity<Peep>(ride->mechanic);
        if (peep != nullptr)
        {
            auto staff = peep->AsStaff();
            if (staff != nullptr && staff->IsMechanic())
                return staff;
        }
    return nullptr;
}
```

is this what you meant?

**Comment by IntelOrca** [comment]
Yeah, because `GetEntity` will return `nullptr` if you give it a value of `SPRITE_INDEX_NULL`.

**Comment by duncanspumpkin** [comment]
In that example you can even simplify it further as you want a staff member you can go straight to that with `GetEntity<Staff>` and it will return a `nullptr` if its not the right type and if its `SPRITE_INDEX_NULL`

```
auto staff = GetEntity<Staff>(ride->mechanic);
if (staff != nullptr && staff->IsMechanic())
{
    return staff;
}
return nullptr;
```

**Comment by Lukasz-Pe** [comment]
Thanks a lot!
I'll do it and get back when ready.
