### ISSUE TITLE
Preview ghost image of circus show doesn't rotate

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#12498]
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** c0a1370

The ghost preview image of circus show does not rotate. See details in below GIF.

**Steps to reproduce:**
1. Select Circus Show
2. Rotate it before build it

**Screenshots / Video:**
![z](https://user-images.githubusercontent.com/10726524/88545969-a9a2b900-d056-11ea-9b47-d6b3374ba235.gif)
(I rotate it by hotkey)

**Comment by tupaschoal** [comment]
A bug indeed, I went as far as `0.0.5` and it has always been there.

Note it does construct correctly

**Comment by Gymnasiast** [comment]
It is a vanilla bug.
