### ISSUE TITLE
Stores selling multiple items can only have the first products advertised

### ISSUE THREAD

**Issue by UTNerd24** [OpenRCT2/OpenRCT2#12505]
I decided to get back into OpenRCT2 after many years and I'm so happy to be back!
I was wondering if it is possible to make it so that stores selling both food and drink can have one or the other in marketing campaigns. As of the moment, you can only advertise the top-most item. E.G: If you advertise the contents of an "Art Deco Food Stall", You will only be able to advertise Beef Noodles. Essentially, the result of adding the feature should allow advertising for either Beef Noodles or Lemonade.

Hopefully that explains enough. If you do need more context or info, just say so. It's great to be back! Looking forward to hearing from you!

**Comment by ocalhoun6** [comment]
If you have an art deco food stall and a lemonade stall, then you do a marketing campaign on lemonade, can peeps use their free lemonade coupons at the art deco food stall?

If so, this should be as simple as adding a few extra items to that drop-down list in instances where there's a multi-item food/drink stall.

**Comment by ocalhoun6** [comment]
Okay, I did a little experimentation.

If you have a lemonade stall not connected to the path and an art deco food stall that is, start the marketing campaign for lemonade, and then make all guests thirsty, I found that guests were using their free lemonade coupons at the art deco food stall. It works. The drop-down list just needs more items in it.

**Comment by Gymnasiast** [comment]
I consider this a bug, so I have changed the title accordingly.
