### ISSUE TITLE
Linux - Custom Content Invisible

### ISSUE THREAD

**Issue by glenjimen** [OpenRCT2/OpenRCT2#12512]
OS: Ubuntu Linux, distro 18.04.4 LTS
Version: 0.2.6-develop-0\~1612-202007250152-g76b7c4e\~ubuntu18.04.1
Commit/Build: 1f3ea5091 on HEAD

   My problem is that 3rd party content is invisible in-game, and in the scenario editor.  I've downloaded and extracted several new rides, for example from The Amazing Earl.  Everything seems functional in-game, that is I can select and build paths or rides, but they all stay completely invisible.  There is even a miniature railway train-type that can be selected, and when it runs it makes little puffs of smoke as it travels down the track, but the locomotive and cars are invisible.  Guests on the ride also appear invisible.  Paths seems to function, if I place a new invisible path next to some dirt paths, you can see the dirt path becomes a 90 degree curve to connect. Guests are able to walk over the paths normally.  I've tried both develop and release, both setting result in the same game play. 

I do have the new .DAT files in /home/<username>/.config/OpenRCT2/object 

Does anyone know why the 3rd party content is not visible?

- [ NO] Reproducible in RCT2 (vanilla)?
- [ NO] Specific to multiplayer?

Steps to reproduce:
1.  Just open a park with custom content and try to build / place any of it.

![UmbuntuTestOpenRCT2](https://user-images.githubusercontent.com/51429904/88758906-6e6bbd00-d11e-11ea-98f3-e83d3f71bcf8.png)

**Comment by duncanspumpkin** [comment]
That's very odd. Do you get any error messages in the console? Have you tried running with the verbose switch?

**Comment by glenjimen** [comment]
I turned on the Verbose switch in the console and got this error multiple times for different objects: 

ERROR[../src/openrct2/object/ObjectFactory.cpp:234 (CreateObjectFromLegacyFile)]: Error: Unable to open '/home/gonzo/RCT2/ObjData/STEAMTRN.DAT' when processing object /home/gonzo/RCT2/ObjData/STEAMTRN.DAT
[rct2.ww.steamtrn] Warning (3): Unable to open '/home/gonzo/RCT2/ObjData/STEAMTRN.DAT'

The other objects that generated the same error are:
STEAMTRN.DAT
LONDONBS.DAT
SANFTRAM.DAT
SCHOOLBS.DAT
MYTHPATH.DAT
RANBPATH.DAT
JURRPATH.DAT
FUTRPAT2.DAT
MEDIPATH.DAT

I think every object that is being displayed invisibly is generating an error regardless of whether I built it in the park.  I only had one type of miniature railroad built, and every type in the scenario threw an error.

**Comment by duncanspumpkin** [comment]
And can you confirm those objects exist at those locations is looking at?

**Comment by glenjimen** [comment]
Oh wow.  Those .DAT files are not in the folder.  They don't appear to be anywhere on my PC.  Well this is embarrassing...

Wait a minute, how could OpenRCT2 offer those rides or footpaths as an option to be built in-game if they are not known to my PC?  Is there another folder or some master list where "installed" rides are kept?  

Thank you, duncanspumpkin.  I was looking for a completely different sort of problem.

**Comment by glenjimen** [comment]
I found some of the files under:
/use/share/openrct2/object/rct2tt/

They are all .json files.  Do these need to be converted to .DAT before they will work in-game?
Also, some of the files that caused errors above are not in this directory, where else could files be located?

**Comment by duncanspumpkin** [comment]
Looks like you are missing objects that should come with rct2. Did you perhaps install from cd or using the demo? Any content that comes from the base game is loaded differently to custom content (we provide a file so that servers can run without the base game but it doesn't have sprites they are still loaded from the .dat file). That includes the expansions so i suspect these objects are from the expansion which you don't have installed. The other possibility is you didn't install correctly. Solution is the same just get ahold of the objects from the rct2 install or wait a while until OpenGraphics completes recreating them.

**Comment by glenjimen** [comment]
I did install from the original CD, and I never had any of the expansions for RCT1 or RCT2.  

Okay, the problem is definitely on my end.  I'll track down those files, or just buy the expansions.  Thank you guys!  You really know your stuff!
