### ISSUE TITLE
Make PVS-Studio Fixes

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#12523]
Fix the issues identified by PVS Studio in the following post:

https://www.viva64.com/en/b/0749/

**Comment by vjavs** [comment]
I was playing with PVS-Studio, could I try this?

**Comment by janisozaur** [comment]
Sure, go ahead

**Comment by duncanspumpkin** [comment]
I had a quick look at all of the issues that were mentioned and none of them were easy to address.

**Comment by vjavs** [comment]
#### List of reported warnings (total of 8):

- [ ] 1. ObjectFactory.cpp:443: The exception was thrown without releasing the `result` pointer. A memory leak is possible.
- [ ] 2. Cheats.cpp:487: There are identical sub-expressions `(1ULL << WIDX_MONTH_BOX)` to the left and to the right of the `|` operator. 
- [ ] 3. RCT12.h:570, RCT12.h:259: It is odd that the `flags` field in derived class `RCT12BannerElement` overwrites field in base class `RCT12TileElementBase`. (Aka Variable shadowing)
- [ ] 4. ObservationTower.cpp:38: It is odd that the result of the `imageDirection / 8` statement is a part of the condition.
- [ ] 5. MouseInput.cpp:1118: An odd sequence of assignments of this kind: A = B; B = A.
- [ ] 6. Network.cpp:2085,2094: The `player` pointer was used unsafely after it was verified against `nullptr`.
- [ ] 7. ServerList.cpp:102: Expression `name == nullptr` is always false.
- [ ] 8. CustomListView.cpp:510: The `ColumnHeaderPressedCurrentState` variable was assigned the same value.

**Comment by duncanspumpkin** [comment]
Item 1 is hard to fix. Item 4 will need checking against the assembly so I just leaving it.

**Comment by vjavs** [comment]
Item 7 has already been refactored in 1b821c1

**Comment by vjavs** [comment]
I think Item 1 could be fixed with the same trick as in:
```
catch (const std::exception& e)
{
     log_error("Error: %s when processing object %s", e.what(), path);
     delete result;
     result = nullptr;
}
```
[ObjectFactory.cpp:L239](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/object/ObjectFactory.cpp#L239)

```
if (readContext.WasError())
{
   delete result;
   result = nullptr;
}
else
{
   result->SetSourceGames({ object_entry_get_source_game_legacy(entry) });
}
```
[ObjectFactory.cpp:L263](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/object/ObjectFactory.cpp#L263)

and:
```
catch (const std::exception& e)
{
   Console::Error::WriteLine("Unable to open or read '%s': %s", path.data(), e.what());

   delete result;
   result = nullptr;
}
return result;
```
[ObjectFactory.cpp:L386](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/object/ObjectFactory.cpp#L386)

By `delete result` before throwing the exception:
```
if (readContext.WasError())
{
   delete result;
   throw std::runtime_error("Object has errors");
}
```

**Comment by vjavs** [comment]
Fix 4 is binary OK [https://godbolt.org/z/GhvKTY](https://godbolt.org/z/GhvKTY)

**Comment by ZehMatt** [comment]
> I think Item 1 could be fixed with the same trick as in:
> 
> ```
> catch (const std::exception& e)
> {
>      log_error("Error: %s when processing object %s", e.what(), path);
>      delete result;
>      result = nullptr;
> }
> ```
> 
> [ObjectFactory.cpp:L239](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/object/ObjectFactory.cpp#L239)
> 
> ```
> if (readContext.WasError())
> {
>    delete result;
>    result = nullptr;
> }
> else
> {
>    result->SetSourceGames({ object_entry_get_source_game_legacy(entry) });
> }
> ```
> 
> [ObjectFactory.cpp:L263](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/object/ObjectFactory.cpp#L263)
> 
> and:
> 
> ```
> catch (const std::exception& e)
> {
>    Console::Error::WriteLine("Unable to open or read '%s': %s", path.data(), e.what());
> 
>    delete result;
>    result = nullptr;
> }
> return result;
> ```
> 
> [ObjectFactory.cpp:L386](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/object/ObjectFactory.cpp#L386)
> 
> By `delete result` before throwing the exception:
> 
> ```
> if (readContext.WasError())
> {
>    delete result;
>    throw std::runtime_error("Object has errors");
> }
> ```

Ideally we use std::unique_ptr, then this will be no longer a problem.

**Comment by vjavs** [comment]
Sure, unique_ptr is great. I can have a look at those raw pointers as well.

**Comment by duncanspumpkin** [comment]
I had a look at changing it to use unique_ptr and it was really complex. That was why I held off on doing it. To make it neat you have to change a lot of code.
