### ISSUE TITLE
Ride simulation causes desync because of ghost tracks.

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#12539]
Trains don't seem to ignore the ghost station and try to move onto the piece while constantly being shoved back and getting stuck on. The clients will desync because this ghost piece doesn't exist.

Host:
![8lEAY2sSU1](https://user-images.githubusercontent.com/5415177/89075545-c0ab1900-d37e-11ea-9e72-16c02ee3ee76.gif)

Client:
![e9MrVtXnqD](https://user-images.githubusercontent.com/5415177/89075559-c6a0fa00-d37e-11ea-855b-6e0a2b24f265.gif)

**Comment by James103** [comment]
Does this desync happen the other way around (where the client is the one with the ghost piece, not the host)?

**Comment by manuelVo** [comment]
PR #13252 will fix this issue.
