### ISSUE TITLE
Feature request: Sort the saved ride designs list in the same way as the saved games list and the staff list.

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#12533]
Currently the saved designs that start with a number are still ordered by the first digit instead of the full number, which causes 10 to be between 1 and 2 (see screenshot). The staff list and saved games list used to be sorted this way too, but they've been changed to consider the whole number instead of just the first digit. I think it'd be a nice change if the saved designs list was organized that way too.

![image](https://user-images.githubusercontent.com/25930360/89060628-a1eb5900-d363-11ea-9a33-cabc6adee965.png)

**Comment by erikhuizinga** [comment]
That must be a screenshot from https://www.youtube.com/watch?v=b-5aX2oLOgU. 😆
