### ISSUE TITLE
Scenario editor hangs when checking if park entrance path extends to map edge

### ISSUE THREAD

**Issue by NathanIkola** [OpenRCT2/OpenRCT2#12557]
**Summary:**
The `footpath_is_connected_to_map_edge_recurse` method in Footpath.cpp recurses for several minutes when there is a 2-tile wide path of length 15 and tiles are placed in certain configurations. It eventually terminates (on my machine it took roughly 7 minutes to begin responding again).

**Steps to reproduce:**
1. Launch the Scenario Editor and advance to the Landscape Editor screen.
2. Place a straight path of length 16, starting at the right side of the map extending parallel to the left side.
3. Place a second path of length 15 along the right side of the first path, again extending from the outermost tile of the map inward.
4. Place the park entrance connected to the first path of length 16.
5. Attempt to advance to the Invention List Set Up screen, the editor will hang for several minutes.

There are some other configurations that cause this issue, and it seems that the order in which the tiles are placed has a large effect on whether or not it hangs. As well, it does not hang if the second path is on the left side of the first path.

**Screenshot:**
![EditorHang](https://user-images.githubusercontent.com/52811935/89117160-8a3dce80-d450-11ea-9986-2204fafaf35f.PNG)

**Comment by James103** [comment]
I was able to reproduce this in OpenRCT2 0.2.6 stable (6c3c857) with the following steps:
1. Build a straight path of length 17 starting from the map edge.
2. One tile to the right of the straight path, build another straight path of length 15 running parallel to the first straight path starting from the map edge.
3. Place the park entrance at the end of the path with length 17.
4. Try advancing to the invention list setup page.
5. The editor will hang for a few seconds, making lots of verbose log entries and sounds corresponding to `LandSetRightsAction`.

**Comment by tupaschoal** [comment]
It worked fine on `0.2.1` but not `0.2.3`, I'll try to bisect it to the exact commit

**Comment by tupaschoal** [comment]
Surprise, @duncanspumpkin, looks like it appeared with e9e445837 ahahah
