### ISSUE TITLE
Grey rectangles appear under windows and menus

### ISSUE THREAD

**Issue by RoelerCoaster** [OpenRCT2/OpenRCT2#12552]
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** ddd21fa

When opening windows or menus a grey rectangle appears below the window or the menu, turning the game black and white in that area. The rectangle stays for a while after the window has been closed or when you move around the window.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open a window, like the options menu on the title screen
2. Observe the gray rectangles under the window.

**Screenshots / Video:**
![screen1](https://user-images.githubusercontent.com/5968886/89110219-d84ed400-d448-11ea-93be-3c989821eb94.png)

Moving a window around a bit leaves traces:
![screen2](https://user-images.githubusercontent.com/5968886/89110223-e13fa580-d448-11ea-84b5-bc4f39603ce1.png)

**Comment by AaronVanGeffen** [comment]
Regression of #12134?

**Comment by janisozaur** [comment]
@RoelerCoaster did only start happening recently? Can you provide a version where it started or an estimate of it?

**Comment by RoelerCoaster** [comment]
Very recently, I played the game yesterday and it was all fine, I only noticed it just when I updated and started the game again. I can try to go back to see if I can find the version where it start.

**Comment by RoelerCoaster** [comment]
bf08943 is fine for me, so my guess it is caused by #12134
