### ISSUE TITLE
Three coasters are not synchronized correctly, just among two of them

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#12561]
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** 733bc5

I was found this issue in Three Monkeys Park scenario which is well known as that there is nice three synchronized coasters.
These coasters were not synchronized correctly. Just two of them synchronized.

Since it was fine when I tested by four coasters, I think the synchronisation does not work properly if the number of coasters are odd number(3, 5, 7 ...).

**Steps to reproduce:**
1-1. Build three coasters to synchronize
1-2. Run them
2. Or, just open Three Monkeys Park scenario

**Screenshots / Video:**
![Incorrect synchronisation](https://user-images.githubusercontent.com/10726524/89125468-aeb1ad80-d519-11ea-8bbe-4c037401465e.gif)
All of three coasters' are synchronized.

**Comment by janisozaur** [comment]
Looks like a good candidate for replay tests

**Comment by tupaschoal** [comment]
Seems like I'm to blame here https://github.com/tupaschoal/OpenRCT2/commit/e5e70688
