### ISSUE TITLE
Giant screenshot keying

### ISSUE THREAD

**Issue by Belzebub** [OpenRCT2/OpenRCT2#1260]
Hi!

Maybe you know the giant aerials at New Element.
We used to stitch those together hand by hand with photoshop, so it's AWESOME to see a giant screenshot function - thanks a lot!
However we used an altered version of the G1.DAT so that the background is pink to key out the background more efficiently (because otherwise pixels on the map get marked as well). Would it be possible to change the standard rct grey/black-background to pink/something user defined or even save the giant screenshot image transparent already?

**Comment by duncanspumpkin** [comment]
I actually came across the code to do this today. Can probably get a solution for it tomorrow.

**Comment by Gymnasiast** [comment]
Since the screenshot format is PNG by default, saving it with transparency directly might indeed be possible. That would save you the extra step of taking out the pink.

**Comment by duncanspumpkin** [comment]
Hmm that might not be too easy. I know the sprite it assigns for drawing the background. My plan was to just upload a g2 version in pink and then link to that when in giant screenshot. It would be a bit harder to change the whole drawing code to also create a transparency mask.

**Comment by Gymnasiast** [comment]
Ah, I didn't know that (which is why I said 'might'). In that case pink will do, I think. :)

**Comment by duncanspumpkin** [comment]
Doh just realised this wont work at present. Some old code still accesses g1 so this will fail. I have to implement that first but its going to take a couple weeks to get the code ready for it.

**Comment by zsilencer** [comment]
just have to set height of the background element to 0 so it doesn't draw, and memset the screenshot buffer to 0 before drawing and make that the transparency key.

**Comment by duncanspumpkin** [comment]
@zsilencer ahh that does sound like a better approach.

**Comment by zsilencer** [comment]
so i put it in a branch
however, there is still the matter of some maps having custom scenery that looks like the background, giving the effect that the map is shaped.
a solution is needed for that

**Comment by Belzebub** [comment]
^We changed the black tiles with custom pink tiles and manually colored over the custom scenery like that. Not the fastest solution but it worked kinda well.

**Comment by zsilencer** [comment]
ok if you are able to change the black tiles with custom tiles that are colored with palette index 0 instead of pink, then the giant screenshot should make it transparent for you.  if you could test out my branch and see?

**Comment by Belzebub** [comment]
How can I test out your branch?

**Comment by zsilencer** [comment]
here is the built dll, just replace the existing one
http://wikisend.com/download/310948/openrct2.dll.zip

**Comment by Belzebub** [comment]
tried it replacing the dll (it's in the same folder as openrct2.exe, right?), but it didn't do anything different to the original one? No keying or transparency whatsoever.

**Comment by zsilencer** [comment]
are you building the game?  if so need to replace the dll in the build folder.

**Comment by Belzebub** [comment]
^Nope, I'm just a 'user' :)

**Comment by Nubbie** [comment]
Wonder if the feature should be a option

**Comment by Richard-L** [comment]
Can I comment to revisit and ask if enabling transparency for RCT2 background in giant screenshots is at all possible?

**Comment by Gymnasiast** [comment]
It's very likely to be possible, it's just that this is one request in the big pile of feature requests and bugs to address.

**Comment by Umdlye** [comment]
Implemented by #9334
