### ISSUE TITLE
Mechanics keep going out of bounds in Gravity Gardens

### ISSUE THREAD

**Issue by LossyDragon** [OpenRCT2/OpenRCT2#12617]
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** 6c3c857

Pardon if there is a duplicate issue of this, I've searched by some keywords and didn't find anything similar to this. 

While playing Gravity Gardens quickly, I have noticed a constant notification in the ticker board that my rides have not been repaired in a timely manner. Since my play through was mostly established to start running the game at Fast or Turbo speed, I left it while I work on something. Then I  noticed some of my mechanics were huddled in this corner stuck while trying to head to said ride that's broken. 

The first time around, I fired them all and respawned a fresh set... This worked for a bit. 
The second time around, I picked them up and moved the manually back to the nearest path... This also worked for a bit. 
The 3rd time around, might as well seek help at this point :)

One or up to half my mechanic fleet was stuck in this corner at times. 

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Play campaign of Gravity Gardens
2. Once park is establish to a point, run the speed either Fast or Turbo
3. Play the game? 😄 
4. One or more mechanics will teleport out of bounds. (Left map corner of the Entry Gate). 

**Dump file**

N/A

**Screenshots / Video:**

![NYVDjHM](https://user-images.githubusercontent.com/4994318/89725128-d3060200-d9d1-11ea-8625-0104356a01d8.png)

**Save game:**

[Gravity Gardens.zip](https://github.com/OpenRCT2/OpenRCT2/files/5046767/Gravity.Gardens.zip)

**Comment by AaronVanGeffen** [comment]
This has been resolved on develop since the 0.2.6 release.

**Comment by LossyDragon** [comment]
Thanks! I'll close this as a dupe since the PR was merged. I'll grab a nightly with the fix applied.
