### ISSUE TITLE
'Monthly Income from ride tickets' in Scenario Editor is removed when park is not free entry.

### ISSUE THREAD

**Issue by JMGates** [OpenRCT2/OpenRCT2#12611]
I ran into an interesting issue while creating a scenario where if you set the park to have a fee, then move onto the next section where you choose an objective, the "Achieve a monthly income from tickets of at least x" option is absent. If you set the park to free entry then it reappears.

More interestingly though, if you set park to free, then set that objective, you can then go back and set the park to have a non-zero fee but the aforementioned objective will stay selected when you go forward again to that menu.

Not sure if this is an oversight or intentional behavior, but it feels unnecessarily limiting either way and it could be discussed whether it should be changed or not.

**Comment by duncanspumpkin** [comment]
There is code that removes that option from the drop down. I don't quite know why you would want that option removed though. @Gymnasiast do you know anything about this?

**Comment by ocalhoun6** [comment]
It's probably based on the assumption that a park that charges admission would have free rides ... and that therefore a monthly income from ride tickets would be impossible, since you would have no ride ticket income at all (except maybe toilets?)

**Comment by Gymnasiast** [comment]
I think that @ocalhoun6 is correct here. It's a reasonable anti-footgun, but stemming from vanlla, it doesn't take into account that we now have three modes for park and ride fees.

I think it should instead check if money _can_ be charged for rides (there is a function for that) and only take it from the dropdown if you can't.
