### ISSUE TITLE
OpenGL - Cursor disappears when Flux activates in the evening, with Flux's "Software mouse cursor" option enabled

### ISSUE THREAD

**Issue by PlanetLotus** [OpenRCT2/OpenRCT2#12639]
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** 6c3c857

- [ ] Reproducible in RCT2 (vanilla)? Unsure / doubt it
- [ ] Specific to multiplayer? No

**Steps to reproduce:**
1. Install & run [Flux](https://justgetflux.com/)
2. Right click Flux in taskbar > Options and Smart Lighting > Enable "Software mouse cursor when needed"
3. When Flux is dimming the screen at night with this option enabled, this makes it so the cursor is invisible in OpenRCT2

I narrowed this repro specifically to this Flux option + the OpenGL drawing engine. Switching to either software option brings the cursor back, so does disabling the "Software mouse cursor" option.

This is incredibly niche so I don't expect it to be fixed, but I thought I'd report it in case it exposes a more general bug.

**Comment by duncanspumpkin** [comment]
Sounds like a flux bug

**Comment by Gymnasiast** [comment]
I expect it to be a f.lux bug too. Unless someone with more in-depth knowledge can point us to a specific bug in our code (or SDL’s), I don’t think there is much we can do here.
