### ISSUE TITLE
Sprite export corrupted

### ISSUE THREAD

**Issue by ThomasdenH** [OpenRCT2/OpenRCT2#1266]
There is an issue with sprite importing/exporting that has been there a while. The bottom of the image gets corrupted in some cases. To reproduce run the following commands:

    openrct2 sprite create g2.dat
    openrct2 sprite append g2.dat image.png -m 0
    openrct2 sprite export g2.dat 0 out.png

An image with which this bug appears is this one:
![Image](http://i.imgur.com/fGO8NGJ.png)
The result is as follows:
![Image, bugged](http://i.imgur.com/fGO8NGJ.png)
Funnily the image displays fine here, but clicking the link will display it bugged: http://i.imgur.com/fGO8NGJ.png

**Comment by Gymnasiast** [comment]
Is this still happening?

**Comment by ThomasdenH** [comment]
I'm not sure. Even both previews I uploaded display fine, so I think this can be closed.

**Comment by IntelOrca** [comment]
![image](https://cloud.githubusercontent.com/assets/1482259/12274734/325d118c-b964-11e5-9da5-46b708f5918a.png)

They just look like this for me.

**Comment by janisozaur** [comment]
Possibly fixed by https://github.com/OpenRCT2/OpenRCT2/commit/60f7d29c2e67b00fb415f26f6cc2e17344ef0b9e
