### ISSUE TITLE
[Sound] Constant Scream Noise near Roller Coaster.

### ISSUE THREAD

**Issue by MatheusArleson** [OpenRCT2/OpenRCT2#12692]
**OS:** Windows 10
**Version:** 0.2.6
**Commit/Build:** (6c3c857 on master) providded by GitHub

There a constant scream noise playing as soon as a Roller Coaster is built. 
This issue is isolated to ORCT2, loading the same save file on vanilla RCT2 **DOES NOT** produce the constant noise scream.

Already tried exit and run the game again, same issue happens,
Tried building different types of Roller Coasters, the same constant scream noise always happen, no matter the type or intensity of the ride.

I know that sound design of this game is not something very good (for today standards), but it should work the same as the vanilla game.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open application
2. Click on scenarion Crazy Castle
3. Build a Roller Coaster (e.g Wood Mouse, any ride)
4. Let Guests use the Coaster
5. Constant scream noise is playing near the ride.

**Save game:**
[Crazy Castle.zip](https://github.com/OpenRCT2/OpenRCT2/files/5078676/Crazy.Castle.zip)

**Comment by duncanspumpkin** [comment]
update to the latest version.

**Comment by MatheusArleson** [comment]
It is the latest version. What do you mean ?

**Comment by tupaschoal** [comment]
@MatheusArleson the 0.2.6 release is 4 months old, this bug has already been fixed on the develop stream and will not happen if you use it or use the next release, when it comes.

**Comment by MatheusArleson** [comment]
Thank you for the explanation. I'm using the develop branch version now, and the audio issue seems to be solved.

**Comment by duncanspumpkin** [comment]
Yeah sorry I was about to write a better response but got distracted.
