### ISSUE TITLE
Tooltip at ride's graph tab is not using a proper string

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#12691]
**OS:** All
**Version:** 0.2.6
**Commit/Build:** d988384

![image](https://user-images.githubusercontent.com/10726524/90306393-be60c700-df07-11ea-9244-9efa5ea77ea7.png)

Either ``STR_1233`` or ``STR_1234`` is used here, which is not reasonable for me.
I think this should be "Logging data from **car 1**", instead of **1 car** in english.

Furthermore, in my language Korean, I translated ``STR_1233: {COMMA16} train`` as "열차 {COMMA16}대", which means "(there is) "{COMMA16} train", since it is shown at here:
![image](https://user-images.githubusercontent.com/10726524/90306590-bd309980-df09-11ea-8e44-613130612fa5.png)

So tootip string ``STR_1422`` in korean becomes a meaning like: "Logging data from (there is) 1 train", which is nonsense for korean users.

I think we need a seperate string for graph's tooltip, such as ``Train {COMMA16}``, meaning "train (which it's number is) {COMMA16}", not referencing STR_1233.

**Comment by Gymnasiast** [comment]
I had noticed this bug at least a year ago and had forgotten to report it. Thanks!
