### ISSUE TITLE
Plugin API: find out if ride is broken or crashed

### ISSUE THREAD

**Issue by Sadret** [OpenRCT2/OpenRCT2#12702]
- add a field to `interface Ride` that indicates if the ride is currently broken (corresponds to `RIDE_LIFECYCLE_BROKEN_DOWN`)
- add a field to `interface Ride` that indicates if the ride is currently crashed (corresponds to `RIDE_LIFECYCLE_CRASHED`)

**Comment by IntelOrca** [comment]
Currently already available as `lifecycleFlags` on `Ride`.

**Comment by Sadret** [comment]
Wow, I completely missed that while looking through the openrct2.d.ts file.
Closing issue now.
