### ISSUE TITLE
Plugin API: interface RideType

### ISSUE THREAD

**Issue by Sadret** [OpenRCT2/OpenRCT2#12706]
- add an interface `RideType`
- add various fields to `interface RideType`, especially:
  - add a field to `interface RideType` that indicates if the ride has a track (corresponds to `RIDE_TYPE_FLAG_HAS_TRACK`)
  - add a field to `interface RideType` that indicates if the ride has data logging (corresponds to `RIDE_TYPE_FLAG_HAS_DATA_LOGGING`)
- add a method to query ride types by id

**Comment by autosysops** [comment]
would love to have this too. From what I see there is no way at the moment to get all the ridetypes within the API.

**Comment by IntelOrca** [comment]
Closing as #18669 tracks the same issue
