### ISSUE TITLE
Plugin API: Park / Scenario information

### ISSUE THREAD

**Issue by Sadret** [OpenRCT2/OpenRCT2#12703]
- add a field to `interface Park` that indicates if the park has the difficult guest generation enabled (corresponds to `PARK_FLAGS_DIFFICULT_GUEST_GENERATION`)
- add a field to `interface Park` that holds the objective for the number of guests (corresponds to `Scenario::gScenarioObjectiveNumGuests`

**Comment by IntelOrca** [comment]
These have been implemented
