### ISSUE TITLE
Make sound volume only control sound.

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#1270]
The sound volume slider controls both game sounds and ride music. It should just control the sound volume. I don't think there is a need for a master volume control as you can just set both the sound and music sliders to 0.

**Comment by Phyxion** [comment]
I agree, it's very strange that the sound slider also affects the ride music and that the music slider does almost nothing (I don't notice any changes at least).

**Comment by zsilencer** [comment]
So should the Sound slider be just for sound effects?  Another option would be a third slider for sound effects along with the master sound and music level.

**Comment by IntelOrca** [comment]
My preference is to have one slider for music and one slider for sound. I don't see the need of a master slider (its easy enough to just move both).

**Comment by zsilencer** [comment]
OK, another problem is right now the sound checkbox that goes with the slider also acts as a master sound control and is used as gConfigSound.sound bool in a lot of places so it would be confusing to have that still.  So the config value could be repurposed to mean only sound effects or a new effect config value could be made but then people would have no way to toggle the existing master sound config in the interface.

**Comment by IntelOrca** [comment]
@zsilencer I propose we rename gConfigSound to gConfigAudio and have sound_enabled and music_enabled.

**Comment by IntelOrca** [comment]
Because you can select none for title sequence music - I vote that disabling the music checkbox does not disable title sequence music - just ride music. In which case the option could be renamed to Ride Music.
