### ISSUE TITLE
Packaging OpenRCT2 0.3.0 for OpenBSD: title sequences not working?

### ISSUE THREAD

**Issue by ibara** [OpenRCT2/OpenRCT2#12716]
**OS:** OpenBSD
**Version:** 0.3.0

Hi team --

I'm in the process of making the OpenBSD package of OpenRCT2 0.3.0. The game works fine but the title sequences that play when the game is on the title screen no longer seem to work. I just get a black screen (menus work fine).

I have been getting the title sequences from here: https://github.com/OpenRCT2/title-sequences

Let me know if that's no longer where I should be getting the title sequences from, or if there's other info needed to help diagnose.

Thanks!

**Comment by tupaschoal** [comment]
Maybe it's related to this change https://github.com/rdbaris/OpenRCT2/commit/2a00293d88bb38e65040cde888842d9bf1e236ab?

**Comment by ibara** [comment]
That fixed things, thanks.

Interestingly, CMake installed the title sequences into share/openrct2/title without complaining, Perhaps that should be poisoned so others don't experience this.

**Comment by PureTryOut** [comment]
Huh, I had the same issue while packaging for Alpine Linux. CMake installed it to `/usr/share/openrct2/title` without me configuring anything for it, and I have to move it in packaging to the right directory.
How strange
