### ISSUE TITLE
test failure on Alpine Linux with 0.3.0

### ISSUE THREAD

**Issue by PureTryOut** [OpenRCT2/OpenRCT2#12719]
**OS:** Alpine Linux edge
**Version:** 0.3.0
**Commit/Build:** 135cc10

**Steps to reproduce:**
1. Build the game on an Alpine Linux system
2. Run tests

```
10/10 Test #10: play_tests .......................***Failed    0.02 sec
Running main() from gtest_main.cc
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from PlayTests
[ RUN      ] PlayTests.SecondGuestInQueueShouldNotRideIfNoFunds
ERROR[../src/openrct2/localisation/LanguagePack.cpp:95 (FromFile)]: Unable to open /language/en-GB.txt: Unable to open '/language/en-GB.txt'
ERROR[../src/openrct2/Context.cpp:388 (Initialise)]: Failed to open configured language: Unable to open language 8
ERROR[../src/openrct2/localisation/LanguagePack.cpp:95 (FromFile)]: Unable to open /language/en-GB.txt: Unable to open '/language/en-GB.txt'
FATAL[../src/openrct2/Context.cpp:395 (Initialise)]: Failed to open fallback language: Unable to open language 8
../test/tests/PlayTests.cpp:92: Failure
Expected: (context.get()) != (nullptr), actual: NULL vs nullptr
[  FAILED  ] PlayTests.SecondGuestInQueueShouldNotRideIfNoFunds (10 ms)
[ RUN      ] PlayTests.CarRideWithOneCarOnlyAcceptsTwoGuests
ERROR[../src/openrct2/localisation/LanguagePack.cpp:95 (FromFile)]: Unable to open /language/en-GB.txt: Unable to open '/language/en-GB.txt'
ERROR[../src/openrct2/Context.cpp:388 (Initialise)]: Failed to open configured language: Unable to open language 8
ERROR[../src/openrct2/localisation/LanguagePack.cpp:95 (FromFile)]: Unable to open /language/en-GB.txt: Unable to open '/language/en-GB.txt'
FATAL[../src/openrct2/Context.cpp:395 (Initialise)]: Failed to open fallback language: Unable to open language 8
../test/tests/PlayTests.cpp:153: Failure
Expected: (context.get()) != (nullptr), actual: NULL vs nullptr
[  FAILED  ] PlayTests.CarRideWithOneCarOnlyAcceptsTwoGuests (1 ms)
[----------] 2 tests from PlayTests (11 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (11 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] PlayTests.SecondGuestInQueueShouldNotRideIfNoFunds
[  FAILED  ] PlayTests.CarRideWithOneCarOnlyAcceptsTwoGuests

 2 FAILED TESTS
```

**Comment by AaronVanGeffen** [comment]
The errors suggest there may be something wrong with your setup. Has the `data` directory been symlinked into the build/bin dir?

**Comment by PureTryOut** [comment]
Well I just run the regular CMake commands, I'd assume that would do such things if it was required.

```
cmake -B build -G Ninja \
	-DCMAKE_BUILD_TYPE=None \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DCMAKE_INSTALL_LIBDIR=lib \
	-DWITH_TESTS=ON \
	-DDOWNLOAD_TITLE_SEQUENCES=OFF \
	-DDOWNLOAD_OBJECTS=OFF
ninja -C build
```

You can see the full build script I use [here](https://git.alpinelinux.org/aports/tree/community/openrct2/APKBUILD).

**Comment by janisozaur** [comment]
These are not the "regular" cmake commands: you're missing `install` target.

**Comment by PureTryOut** [comment]
As you can see in the full build script, I am running the install target, just in the `package()` function. However, that part is ran after running the tests.

From your comment I assume the symlink is being made in the `install` target, so it requires running that before the test? A bit annoying, I'll have to figure out how to make that work in our build system...

**Comment by IntelOrca** [comment]
@PureTryOut install won't do that, install will put the data in `./usr/share`, but the game I think only checks global install: `/usr/share`. I would like to put the symlink or copy step as part of the build or all target but @janisozaur is against it.

**Comment by PureTryOut** [comment]
Yeah ok, so `install` only does the usual things, good :wink: 

I can symlink it manually for now, but it being part of a CMake target would be great.

**Comment by PureTryOut** [comment]
Manually symlinking did the trick, thanks for the tips! Would love to see it be done by CMake eventually.
