### ISSUE TITLE
Paths made in scenario editor don't connect to the map edge

### ISSUE THREAD

**Issue by tombomp** [OpenRCT2/OpenRCT2#12728]
**OS:**  Windows 10
**Version:** develop
**Commit/Build:** 8d141fa

In the scenario editor drawing a path that should connect to the map edge no longer creates a connection. This means you can't make a valid peep spawn. It works fine in 0.3 so although I haven't bisected I'd assume it was introduced in #12366

- [no] Reproducible in RCT2 (vanilla)?
- [no] Specific to multiplayer?

**Steps to reproduce:**
1. Open scenario editor
2. Press button for landscape editor
3. Create a path on an edge square - it doesn't connect

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/43040194/90669587-c8593180-e249-11ea-8103-1f102819a912.png)

**Comment by mwnciau** [comment]
> I'd assume it was introduced in #12366 

Yep, just confirmed this.
