### ISSUE TITLE
[Feature] Allow binding mouse inputs in the "keyboard" shortcuts window.

### ISSUE THREAD

**Issue by awebeer256** [OpenRCT2/OpenRCT2#12739]
For example, mouse scrolling is hardcoded to the original game's zoom feature, but I want to be able to rebind it to changing the scale factor.

Specifically, I want "scroll up," "scroll down," and buttons numbering >= 3 to be rebind-able.

I think this would require allowing each action to have 2 different inputs bound to it, to maintain the default behaviour of both Page Up/Page Down and mouse scrolling *both* being bound to zooming. In my defence, that's standard practice for modern PC games.

**Comment by AaronVanGeffen** [comment]
@IntelOrca was musing about this the other day. I thought there was already an issue tracking this, but I can't find it.

**Comment by IntelOrca** [comment]
I think I only mentioned it in discord that it would be nice to be able to bind all mouse buttons, particularly the side nav buttons to rotate view.

**Comment by ocalhoun6** [comment]
And maybe adding support for side-scrolling?

**Comment by IntelOrca** [comment]
Resolved by #13848
