### ISSUE TITLE
"Year Built" bug in ride dialog upon loading scenarios from both RCT1 installation and RCT2. 

### ISSUE THREAD

**Issue by cudakid** [OpenRCT2/OpenRCT2#12764]
Windows 10
0.3.0
135cc10

This is my first post here, or on any forum like this, so I apologize if I am doing this incorrectly. 

I believe I have found a bug. 

When attempting to open RCT1 scenarios from my Steam installation of RollerCoaster Tycoon Deluxe within OpenRCT2 (I have pointed the program to the proper folder using the options menu), all of the scenarios appear to properly load.

However, in all RCT1 scenarios, the rides show as being built “this year”, regardless of how old they are supposed to be. This behavior does not happen when using vanilla RCT1 deluxe; the screenshots below are scenarios created from the same files in the RCT1 deluxe directory that the OpenRCT2 installation points to (see screenshot 1). 

It appears that the other statistics about the ride; number of total customers, lifetime profits, relability, last breakdown, etc., do load properly (you can see this by looking at the side-by-side screenshots of OpenRCT2 and RCT1 Deluxe (see screenshot 2).   

I have also noticed this behavior when loading scenarios from the RCT2 vanilla game. For example, in Rock ‘n’ Roll revival, when I load it in vanilla RCT2, it shows the ride “Jet Plane Coaster” was built “10 years ago”, but in OpenRCT2, it shows it being built “This Year" (see screenshot 3). 

It appears that this might well just be a visual bug; i.e., the number of years is not being properly reported to whatever shows it in the ride dialog, since the other historical stats are correct. 

But this has prevented me from playing scenarios like Crumbly Woods where the aged status of the rides is a major part of the challenge. Without knowing how old the rides are, it makes it more difficult to play. (see Screenshot 4; upon loading the park, all the rides sow as being built "This year")

The “built” counter does appear to properly increase as time progresses in-game. 

This is my first time ever reporting a bug for any game and I have very little programming experience (I do web development on the side and know CSS, HTML and Javascript but don't know much about actually writing applications) so if there is anything you need from me (saves, the sc4/sc6 files themselves, etc.) please let me know. 

**Screenshots / Video:**
Screenshot 1:

![screenshot 1](https://user-images.githubusercontent.com/70118045/90992575-b1cf1500-e57e-11ea-829b-2668d47700e2.png)
Screenshot 2:
![screenshot 2](https://user-images.githubusercontent.com/70118045/90992576-b4316f00-e57e-11ea-9299-7b602b5fcd2d.png)
Screenshot 3:
![screenshot 3](https://user-images.githubusercontent.com/70118045/90992578-b693c900-e57e-11ea-9fbe-482116e5bdf9.png)
Screenshot 4: 
![screenshot 4](https://user-images.githubusercontent.com/70118045/90992816-1474e080-e580-11ea-953e-e1771752028f.png)

**Comment by tupaschoal** [comment]
> This is my first post here, or on any forum like this, so I apologize if I am doing this incorrectly.

With the amount of information on how to reproduce it, you actually did better than most of us, really, thanks!

I can reproduce it using the "Rock'n'Roll Revival" park and I could confirm it's a regression introduced between releases 0.2.6 and 0.3.0. Will bisect and post here the results.

**Comment by Fred-1044276** [comment]
It isn't just RCT1 and RCT2 scenarios that are affected. Even all custom scenarios are affected too, including [Squalid Swamps](https://rctgo.com/downloads/view/squalid-swamps.20291) (shown below).
![5f20f1a757d08](https://user-images.githubusercontent.com/61885939/91107133-5c9c0d80-e629-11ea-8c75-1cbf7987317f.png)

As you can see here, the rides here are 19~21 years old, which adds to the very high difficulty of this scenario, but in OpenRCT2, they all magically revert back to "Built: This Year".

**Comment by cudakid** [comment]
> > This is my first post here, or on any forum like this, so I apologize if I am doing this incorrectly.
> 
> With the amount of information on how to reproduce it, you actually did better than most of us, really, thanks!
> 
> I can reproduce it using the "Rock'n'Roll Revival" park and I could confirm it's a regression introduced between releases 0.2.6 and 0.3.0. Will bisect and post here the results.

I appreciate it! I did the best I could with my limited knowledge. 

Yes, I played a created scenario yesterday and it happened with that also. 

I wonder if it’s just visual;

**Comment by cudakid** [comment]
> It isn't just RCT1 and RCT2 scenarios that are affected. Even all custom scenarios are affected too, including [Squalid Swamps](https://rctgo.com/downloads/view/squalid-swamps.20291) (shown below).
> ![5f20f1a757d08](https://user-images.githubusercontent.com/61885939/91107133-5c9c0d80-e629-11ea-8c75-1cbf7987317f.png)
> 
> As you can see here, the rides here are 19~21 years old, which adds to the very high difficulty of this scenario, but in OpenRCT2, they all magically revert back to "Built: This Year".

Yes. I also noticed it does it in other custom scenarios. 

However, when loading say, Crumbly Woods, rides are still very unreliable, break down, and guests won’t pay much for them.  

So I think this is an issue with the reading and or reporting of the actual “built” value rather than something “renewing” the rides upon loading the scenarios. 

I haven’t tried playing, letting a ride age, saving it, and then reopening it to see if this happens. 

Maybe it is an issue just with loading files created with and played by vanilla RCT? Although I assume by “custom scenario” that it was created in OpenRCT2

**Comment by tupaschoal** [comment]
I'm pretty sure the culprit is https://github.com/OpenRCT2/OpenRCT2/commit/f6fbd272ecfe2aa994690dfcfe8c2bae11809b1a

**Comment by cudakid** [comment]
> > This is my first post here, or on any forum like this, so I apologize if I am doing this incorrectly.
> 
> With the amount of information on how to reproduce it, you actually did better than most of us, really, thanks!
> 
> I can reproduce it using the "Rock'n'Roll Revival" park and I could confirm it's a regression introduced between releases 0.2.6 and 0.3.0. Will bisect and post here the results.

Thank you! I tried to follow the format the best I could! Glad you were able to reproduce it. Hopefully we can get to the bottom of this—because visual or otherwise, as the other comment says, it takes away from parks where the difficulty is in large part based on the aging rides.
