### ISSUE TITLE
Plugin: Mistake in API documentation

### ISSUE THREAD

**Issue by Sadret** [OpenRCT2/OpenRCT2#12776]
openrct2.d.ts mentions the following, regarding GameDate.monthsElapsed:

"The total number of months that have elapsed. This will equate to 16 on 1st March, Year 2. [...]"

This wrong, as a code inspection and multiple tests clearly show. The value actually starts with 0 (which makes more sense) and increases by 8 every year, resulting in a value of 8 in March, year 2.

Suggested edit:
"The total number of months that have elapsed. This will equate to 0 on 1st March, Year 1 and increase by 1 every month, i.e. by 8 every year. [...]"

**Comment by AaronVanGeffen** [comment]
Could you open a PR to address this? :slightly_smiling_face:
