### ISSUE TITLE
Scenery tab images missing

### ISSUE THREAD

**Issue by oli414** [OpenRCT2/OpenRCT2#12784]
**Version:** 0.3.0-53-g8b19d943a

![image](https://user-images.githubusercontent.com/2348094/91302802-503dbf00-e7a7-11ea-9f23-90b5915a2c44.png)

I'm suspecting #12671 to be the cause.

**Steps to reproduce:**
1. Open scenery menu
2. See that the tab images are missing

**Comment by AaronVanGeffen** [comment]
I'm sure I tested this… Will be able to investigate tonight, after work.
