### ISSUE TITLE
Add Excitement/Intensity/Nausea ratings to Rides view with sorting

### ISSUE THREAD

**Issue by kenperkins** [OpenRCT2/OpenRCT2#12793]
It would be really nice when using the Rides view that you could select Excitement, Intensity, or Nausea ratings as the view, with sorting for them.

![image](https://user-images.githubusercontent.com/730664/91508588-c831e500-e88c-11ea-8a6c-16a83bbc17d1.png)

**Comment by IntelOrca** [comment]
I had a branch awhile ago that turned this into a multiple column table with excitement, intensity and nausea all sortable.

**Comment by AaronVanGeffen** [comment]
I think @IntelOrca is referring to #9708

**Comment by hjort96** [comment]
Is this something I could implement when #15836 is approved? Or are you set on using the new window @IntelOrca has mentioned?

**Comment by Piperapk** [comment]
Had a go at it here #16655 as I saw that the window refactor of class RideList was done.
