### ISSUE TITLE
ScRide.hpp doesn't prevent plugins changing the price of free rides in pay to enter park scenarios

### ISSUE THREAD

**Issue by chess123mate** [OpenRCT2/OpenRCT2#12818]
**OS:** Windows 10
**Version:** 0.3.0-93-g26def8716 (26def87 on develop)

ScRide.hpp doesn't prevent plugins (such as Ride Price Manager) changing the price of free rides in pay to enter park scenarios. Though guests don't pay anything and the UI still claims the price for each ride is free, even a $1 entrance fee will generate "Your park entrance fee is too high!" messages!

The maximum park entrance fee that guests consider reasonable is calculated by Park::CalculateTotalRideValueForMoney, which values each open non-broken ride at (ride.value - ride.price[0]) * 2, if the value is greater than the price. Since the plugin puts the price at greater than the ride's value, all the rides end up generating $0 in this calculation!

Note that reloading the save with all plugins disabled doesn't fix anything.
**Save game:**
[Gentleman's Garden.txt](https://github.com/OpenRCT2/OpenRCT2/files/5146369/Gentleman.s.Garden.txt)
Scenario file: [Gentlemans Garden - Xedoh - Beginner.txt](https://github.com/OpenRCT2/OpenRCT2/files/5146456/Gentlemans.Garden.-.Xedoh.-.Beginner.txt)

**Comment by Fred-1044276** [comment]
I ended up getting the worst value park award. TWICE. Because of this issue. I only learned about the ScRide.hpp failing to stop plugins from changing the price of free rides in Pay to enter park / Free rides scenarios just now when you opened this issue, which forces me to disable the plugins entirely when doing such scenarios.

Oh, and you could have also uploaded an SV6 file with the corresponding SC6 file attached.

**Comment by duncanspumpkin** [comment]
It's for the plugin authors to address this.

**Comment by chess123mate** [comment]
> Oh, and you could have also uploaded an SV6 file with the corresponding SC6 file attached.

Added

> It's for the plugin authors to address this.

The guests aren't being charged and the UI states that the price is free, yet the guest generation probability calculations believe that the price is *not* free. No public interface should ever allow its users to put the system into an inconsistent state.

Possible fixes:
- When the scenario is "free rides", always ignore a ride's price (instead of only sometimes ignoring it). A plugin can therefore change the price, but it will have no effect unless the scenario type is changed. (Personally I think this option makes the most sense.)
- Ignore a plugin's attempt to change the price (or throwing an error or whatever is considered appropriate). This restores the assumption (that used to be true) that the ride price in these scenarios will always be 0.

I would hope that, if someone wanted a plugin to be able to set the price of all rides in an arbitrary park, the plugin would be expected to change the scenario mode to "pay for rides & park entry" (if in the "free rides" scenario mode) before its price assignments would have any effect.

**Comment by IntelOrca** [comment]
The code should already be ignoring price of rides if the park is set to no money or free rides. There may be cases where it doesn't, in which case it is a bug.

**Comment by mgovea** [comment]
> It's for the plugin authors to address this.

I'd love to. I even attempted to pre-empt this issue before releasing the plugin, but I can't read the admission price or the scenario rules yet. I requested the ability to read the scenario rules back in https://github.com/OpenRCT2/OpenRCT2/issues/11759

And I'd love to be able to dynamically set the admission price (with a user selected cap of course) when the scenario permits charging for admission.
