### ISSUE TITLE
OpenGL palette bug

### ISSUE THREAD

**Issue by EmielRCT** [OpenRCT2/OpenRCT2#12827]
When I switch between two drawing engines, Software and OpenGL, the colors in the palette shift, which causes objects to get another color than the one they originally had. I attached 4 pictures, 2 with Software and 2 with OpenGL as drawing engine. 

I'm on the latest develop, dafde53, on Windows X86-64.

It might be interesting to note that OpenGL never worked on my laptop (I saw something like 40 ferris wheels instead of 1 that was actually there), until I tried it again today. It does now eliminate most glitching the Software drawing engine had, but now it gives me this coloring issue. 

Regular coloring palette - Software drawing engine
<img width="89" alt="colorselection_softwaredrawing" src="https://user-images.githubusercontent.com/64599015/91732035-f4f53d80-eba7-11ea-85c5-79c1f96bb476.png">
Overview using that palette - Software drawing engine (park by Mekkit on DKMP)
<img width="720" alt="colorselection_softwaredrawing_map" src="https://user-images.githubusercontent.com/64599015/91732036-f58dd400-eba7-11ea-9817-9ffd01e56e77.png">

Shifted coloring palette - OpenGL drawing engine
<img width="90" alt="colorselection_opengl" src="https://user-images.githubusercontent.com/64599015/91732030-f32b7a00-eba7-11ea-88ac-c07ae9cb7a50.png">
Overview using that palette - OpenGL drawing engine 
<img width="716" alt="colorselection_opengl_map" src="https://user-images.githubusercontent.com/64599015/91732033-f45ca700-eba7-11ea-9b16-2de3de67084c.png">

I'm not here to promote the park, but if you want to download it:
https://drive.google.com/file/d/1SGMwur4jx5L8x4TbHOFLoRq1j7Xce5mu/view?usp=sharing

**Comment by James103** [comment]
Are you able to load this park in RCT2? If so, does it have the same issue? (I presume not.)

**Comment by AaronVanGeffen** [comment]
Interesting. What video card are you using (vendor, model, and make)? Driver version might be useful as well.

As you're on Windows: you can use `dxdiag` to easily obtain the info.

**Comment by EmielRCT** [comment]
I use the Intel UHD Graphics 620, with the driver 27.20.100.8673.

I'm not able to test it in RCT2 since I don't have the game installed

**Comment by AaronVanGeffen** [comment]
In that case, you may be experiencing the same issues as described in #6614

**Comment by AaronVanGeffen** [comment]
Resolved by #13211.
