### ISSUE TITLE
Title menu buttons not invalidating properly

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#12820]
**OS:** Windows 10
**Version:** 0.3.0
**Commit/Build:**  26def87

If a title sequence includes moving scenes, such as following certain coaster's car, then buttons in bottoms looks weird.
It seems that its bottom is clipped.

**Screenshots / Video:**
![2](https://user-images.githubusercontent.com/10726524/91660950-eb21fa80-eb13-11ea-9cd0-7ff33e3c95a0.gif)

**Comment by AaronVanGeffen** [comment]
Looks like an invalidation issue. I suspect this is a regression from #12347.
