### ISSUE TITLE
Show object rotation in Tile Inspector

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#12825]
When I was trying to fix the Chinese Dragon object, I had to hack this in. Would be nice if it was in there by default.

**Comment by Broxzier** [comment]
@hjort96 #12869 is now merged. Do you want to work on this?

**Comment by hjort96** [comment]
Yes, I'd like to work on this. I started working on another issue while waiting for #12869 to be merged, which isn't finished yet. If no one minds I'll work on both, otherwise someone else could do this.

**Comment by Gymnasiast** [comment]
We don’t mind, go ahead :)
