### ISSUE TITLE
Nonsensical guest thoughts

### ISSUE THREAD

**Issue by caseyjohnsonwv** [OpenRCT2/OpenRCT2#12857]
**OS:** Windows 10
**Version:** v0.3.0-129-g6345fe64d
**Commit/Build:** 6345fe6

In a freshly loaded Haunted Harbor (RCT1 scenario), peeps are thinking nonsensical things like "Fries Shop 1 looks too intense for me," and several guests are thinking "is a really good value" with no ride/shop name attached. Vanilla RCT1 and RCT2 do not appear to have these issues, but the same scenarios have nonsense thoughts in OpenRCT2. Alton Towers, for example, says "I want to get off Restroom 3" and "These fries from Restroom 4 are really good value." I think this has something to do with the way RCT1 scenarios are loaded, because I can't find any issues in RCT2 scenarios or saved games.

If I load Alton Towers in debug mode, I get warnings logged from the function `game_fix_save_vars` in `Game.cpp` where corrupted peeps are deleted while the scenario loads. It also says too many scenery groups are loaded... like 15 times.

- Reproducible in RCT2 (vanilla)? No.
- Specific to multiplayer? No.

**Steps to reproduce:**
1. Open the Haunted Harbor scenario (or any scenario with pre-built shops).
2. Pause the game.
3. Look at guests' thoughts.

**Screenshots / Video:**

I forgot to circle it, but a few h*rny guests are saying they "want to get off" as well.
![Nonsense Guest Thoughts](https://user-images.githubusercontent.com/33426783/92268709-ead98480-eeb0-11ea-9129-171ce21146e9.png)

**Comment by Fred-1044276** [comment]
I have also had guests think "Restroom 2 was great" and "Fried Rice Noodles 1" is a really good value on another RCT1 scenario.

**Comment by ocalhoun6** [comment]
You missed the best one of the bunch!
![Screenshot](https://user-images.githubusercontent.com/26573303/92284079-2460be80-eeb6-11ea-93db-2dff5937f97f.png)
