### ISSUE TITLE
A button to automatically fix all vandalism in the park AND charge you for it.

### ISSUE THREAD

**Issue by trigger-death** [OpenRCT2/OpenRCT2#1285]
So unlike the cheat this would be a major convenience button. Next to the button it should show the cost of replacing every broken path addition. It can either replace as much as you can afford, or output an error if you can't afford it.

As for where to put this, I'm not really sure. Maybe a new section in the finances window or something. Or a new sort-of tool window next to the other tool buttons on the top toolbar.

**Comment by sjoerddebruin** [comment]
The button is now available as a cheat, not sure if we should add it as a new game mechanism.

**Comment by Gymnasiast** [comment]
It was available as a cheat when trigger-death opened this. He even says so in the very first sentence.

**Comment by IntelOrca** [comment]
I am not fond of adding things like this, it just makes the game easy or boring. The cheats are really mostly for sandbox mode or testing.

**Comment by Patrik356b** [comment]
Does items that can be vandalised get damaged even if there is no path leading to them?

**Comment by IntelOrca** [comment]
No, a guest has to be near it and a security guard **not** out of sight.

**Comment by Broxzier** [comment]
I'd rather see them being repaired by the staff when they walk past.

**Comment by Gymnasiast** [comment]
@Broxzier That feature is planned.
Closing this as IntelOrca thinks it alters the gameplay too much.
