### ISSUE TITLE
All guests in the park show "N/A" as their favorite ride

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#12881]
**OS:** Windows 10
**Version:** 0.3.0
**Commit/Build:** 6ac23fb

An issue that I have only started noticing today is that every guest in the park, no matter how many rides they have ridden, will always show "N/A" as their favorite ride, even though the numbers of guest favorites for the rides always change. I have noticed this issue in every scenario I play, from RCT1 and RCT2 scenarios to custom ones.

**Steps to reproduce:**
1. Open up any scenario or saved game with many guests in it.
2. Click on a guest and check their rides tab.
3. You should see a list of rides and "N/A" as their favorite ride, even if they have gone on a lot of rides/attractions.

**Screenshots / Video:**
![Onyx Heights 2020-09-07 18-27-44](https://user-images.githubusercontent.com/61885939/92437051-e932e980-f15a-11ea-804f-52119453ad06.png)

**Comment by tupaschoal** [comment]
Can you provide a save with some playing time accrued so we can try bisecting it ?

**Comment by Fred-1044276** [comment]
Here's a [completed save with a lot of playtime accrued](https://drive.google.com/file/d/1f5gZZzGbtjqjNcmcUZsJt3DTphLb3bjn/view?usp=sharing). This is from after I completed the [Onyx Heights](https://drive.google.com/file/d/1QVabQAXqDvPolRAhzvl_Pcayf2mP2kKK/view?usp=sharing) scenario though.

**Comment by tupaschoal** [comment]
Thanks. This is a regression that happened between the 0.2.6 and 0.3.0 release. If needed I'll bisect it further.

**Comment by tupaschoal** [comment]
Culprit is 14a07359b
