### ISSUE TITLE
Mechanic Heading to Ride that isn't Broken

### ISSUE THREAD

**Issue by rpstester** [OpenRCT2/OpenRCT2#12895]
**OS:** Windows 10
**Version:** 0.3.0
**Commit/Build:** 11ebe78

I found some similar issues but not one quite like this.  I have mechanics called to fix a ride that is not broken down.  They are delayed in arriving, so I get a message that the ride still is not fixed.  (I suppose that message is generated by how long the mechanic is heading for the ride, not how long the ride has been broken down.) 

I guess in Alton Towers, due to the large size and twisted path layouts, this issue becomes more obvious.

- [ ] Reproducible in RCT2 (vanilla)? _no_
- [ ] Specific to multiplayer? _no_

**Steps to reproduce:**
1. Start Alton Towers
2. Fire all the mechanics and hire a few new ones (to remove patrol areas)
3. Set all rides to 10-min inspections, so mechanics are very busy
4. Wait and watch mechanics go to repair rides that aren't broken
5. Eventually, you'll get a message that a ride still is not fixed. You'll see that the mechanic is heading for a ride that isn't broken down. 
6. The mechanic visits the ride that is not broken down and does his repair routine.

**Dump file**

**Screenshots / Video:**

**Save game:**

I will try to capture it.

**Comment by rpstester** [comment]
Mechanic 6 is going to fix a ride that had just broken down and been fixed.
[AT Mech 6 Fix Ride.txt](https://github.com/OpenRCT2/OpenRCT2/files/5205385/AT.Mech.6.Fix.Ride.txt)

**Comment by rpstester** [comment]
Just got the message that River Rapids is still not fixed, yet it is running.
[AT River Rapids.txt](https://github.com/OpenRCT2/OpenRCT2/files/5205479/AT.River.Rapids.txt)

**Comment by ocalhoun6** [comment]
I'm getting this pretty frequently as well. Still happening on the current develop version.
And if the ride in question is a tracked ride, the mechanic often heads to a random spot on the track, walking cross-country, in order to fix the ride that isn't broken down.

[https://i.imgur.com/fyOxEaP.png](https://i.imgur.com/fyOxEaP.png)

**Comment by Ruedii** [comment]
Is this a UI issue where the mechanic not reporting for inspection is resulting in the same alert where the ride isn't fixed?

**Comment by adam-bloom** [comment]
This is a state machine issue, not a UI issue. I've opened PR #13389 with a potential fix (based on what I could piece together of these state machines). I've validated using the save file that I attached to #13344
