### ISSUE TITLE
Guest thoughts show up as guest actions or guest names instead

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#12901]
**OS:** Windows 10
**Version:** 0.3.0
**Commit/Build:** d8ffec0

Another newly introduced bug (a regression it looks like) breaks guest thoughts, causing them to appear either as guest actions or guest names. However, clicking on a guest and showing their recent thoughts still has their thoughts appear like normal (e.g. "Chairlift 1 was great", "Launched Freefall 1 looks too intense for me", "Great scenery!").

**Steps to reproduce:**
1. Click on any guest, open the Guests tab (press "G") and select Thoughts, or click on a ride's customer information tab and show guests' thoughts about that ride/attraction.
2. You will now see that every thought in the guest and guests list windows now appears as either the name of a guest or that guests' current action.

**Screenshots:**
![Coastal Castle 2020-09-10 15-17-27](https://user-images.githubusercontent.com/61885939/92815135-cbdb6680-f378-11ea-95e2-cb284872576d.png)
Rhonda D.'s thoughts still appear correctly in her thoughts window. However, there are two problems here:
- Corina S. is supposed to think "Trebuchet Ride 1 was great", but the guest list window instead shows her as having her own guest name as a thought (in bolded text).
- Sandra C. is supposed to think "I'm running out of cash!", but the thought wrongly shows up as "Watching Trebuchet Ride 1" instead in Sandra C.'s guest window.

**Comment by AaronVanGeffen** [comment]
Likely another regression from #12797.
