### ISSUE TITLE
Garbled/distorted date lines in file browser

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#12900]
**OS:** Windows 10
**Version:** 0.3.0
**Commit/Build:** d8ffec0

A new graphical bug causes the date lines in OpenRCT2's native file browser to be garbled/distorted, essentially making them unreadable. This does not happen with the system file browser, however.

**Steps to reproduce:**
1. Open any menu that uses the file browser (e.g. Load Game, Save Game As, Save Track Design)
2. Look at the Date column. Now you will see that the dates have become garbled and distorted.

**Screenshot:**
![Coastal Castle 2020-09-10 14-08-38](https://user-images.githubusercontent.com/61885939/92813782-bebd7800-f376-11ea-88aa-afffb4a42092.png)

**Comment by AaronVanGeffen** [comment]
Oh no. It looks like the date and time overlap, somehow...

Two questions:
1. Does the problem persist if you resize the window?
2. What language (locale) is your operating system set to?
