### ISSUE TITLE
Use RCT1 path types for original scenarios

### ISSUE THREAD

**Issue by sr1gh** [OpenRCT2/OpenRCT2#12915]
Some of the original scenarios use paths as scenery, and look strange with new path types. I attached two images comparing the paths in the "Future World" scenario.

![Future World RCT1](https://user-images.githubusercontent.com/45770511/93001777-77162800-f4ff-11ea-84cf-5ea59b0c3769.png)
![Future World 2020-09-12 13-11-43](https://user-images.githubusercontent.com/45770511/93001784-85644400-f4ff-11ea-91e1-3d12385953de.png)

**Comment by AaronVanGeffen** [comment]
This is certainly planned, but requires the new save format to do. #2253 is tracking this.
