### ISSUE TITLE
Mouse cursor missing in OpenGL (Borderless) Fullscreen

### ISSUE THREAD

**Issue by oli414** [OpenRCT2/OpenRCT2#12928]
**OS:** Windows 10
**Version:** v0.3.0-192
**Commit/Build:** f7348b1
**GPU:** GTX 1060

When I set the game to draw with OpenGL, and set the window type to fullscreen, or fullscreen (borderless window) my mouse cursor disappears in OpenRCT2

**Steps to reproduce:**
1. Set the game to draw with OpenGL and switch to one of the fullscreen display modes.

**Comment by oli414** [comment]
I have not been able to figure out if other people are experiencing this as well, so I'm opening this issue to start an investigation to figure out what the cause is.

**Comment by tupaschoal** [comment]
I couldn't reproduce

**Comment by oli414** [comment]
It has been working for me for the past two days, I was about to close this but I just opened to double check and the issue is back strangely enough.

**Comment by ZehMatt** [comment]
Are you running some sort of overlay program maybe? I had this issue in the past with other games when I had RivaTuner running

**Comment by oli414** [comment]
Oh welp, great timing (it's dark now), yep it is (I thought I had all the overlays ruled out earlier)

It's Flux that's causing it. During the day the issue isn't there since Flux hasn't kicked in yet.

I was using the software mouse cursor option from Flux to fix the mouse cursor from being unaffected by Flux in some other applications. Disabling this fixes the issue.
