### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Xeltron245** [OpenRCT2/OpenRCT2#12962]
This started happening this morning. Was playing fine two days ago but now I can't go into the options menu and I can't play a game for more than a few minutes.

[e2f2ef0b-8d2f-4975-990b-aa8fb4091426(c72f547_x86-64).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/5244585/e2f2ef0b-8d2f-4975-990b-aa8fb4091426.c72f547_x86-64.dmp.gz)

[e2f2ef0b-8d2f-4975-990b-aa8fb4091426.sv6.gz](https://github.com/OpenRCT2/OpenRCT2/files/5244588/e2f2ef0b-8d2f-4975-990b-aa8fb4091426.sv6.gz)

**Comment by AaronVanGeffen** [comment]
Your issue description is a bit lacking in detail, but I'm assuming you've run into #12945. This has since been fixed; you just have to update your game :)
