### ISSUE TITLE
Unable to build sloped walls or fences

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#12974]
**OS:** Windows 10
**Version:** 0.3.0
**Commit/Build:** 124161b

Sloped walls and fences (for fence and wall objects that support the ability to be built on a slope) now can no longer be built even if the "Disable clearance checks" cheat is disabled. I suspect this is yet another recently introduced regression.

**Steps to reproduce:**
1. Attempt to place down a fence or wall on a slope (e.g. Roman Column Wall).
2. It will block you from placing down the fence.

**Screenshot:**
![Hesperides Tree 2020-09-19 17-23-35](https://user-images.githubusercontent.com/61885939/93691651-eca06c00-fa9c-11ea-91fc-1f39c8dd8e2b.png)

**Comment by frutiemax** [comment]
```
git.exe bisect skip
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
1b821c10592c8cab05d47c518e9ee5f3242c5b94
5f17554c25a0057274ce6666ef511dfdfdbe6e11
651a2951a1807f693cf62a340b274719f33524ec
97b44a7181ab2f87a4cad475d981e140c479428d
0c58dfa1b331b27f40432929baa8736f072cc163
de9a16404b84aac711490357041fa5a0572e116b
12dfa74eef39572ce6eda5cfb5b4c8d672db3dcf
c655d47dd393ac28159d8f165208217ab72859ea
57a57b0c02789d6e0fff1335d66d1b003e194226
f1bcf200505816e20da7f465ca9896cdc2668fcd
2c92c652e2b90a66c01256a1e4ceaef451029637
324e94e6cea6463fef50e6de8bd13b7598a240b4
660c1379588a782ea70cb8fa9d188bd2a010e86a
We cannot bisect more!


git did not exit cleanly (exit code 2) (1546 ms @ 2020-09-19 9:57:28 PM)

```

There are a bunch of commits that couldn't be built due to the new json library...
