### ISSUE TITLE
Homebrew cmake / make install errors

### ISSUE THREAD

**Issue by erikhuizinga** [OpenRCT2/OpenRCT2#12978]
**OS:** MacOS 10.14.6 (18G6020)
**Version:** N/A (installation error)
**Commit/Build:** 4030d9050

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. `$ brew install --HEAD openrct2`
2. Output:

```
==> Downloading https://github.com/OpenRCT2/title-sequences/releases/download/v0.1.2c/title-sequences.zip
Already downloaded: ~/Library/Caches/Homebrew/downloads/0214e6a3fb336e8419adf432bd4fdee7ce81e7ceddcb87b4d48ac6e03643830f--title-sequences.zip
==> Downloading https://github.com/OpenRCT2/objects/releases/download/v1.0.16/objects.zip
Already downloaded: ~/Library/Caches/Homebrew/downloads/18c6c2a7ffd0735917f1bd0851b8c9eef783073d0976ce276e9dc02240569f99--objects.zip
==> Cloning https://github.com/OpenRCT2/OpenRCT2.git
Updating ~/Library/Caches/Homebrew/openrct2--git
==> Checking out branch develop
Already on 'develop'
Your branch is up to date with 'origin/develop'.
HEAD is now at 4030d9050 Fix #12974: unable to build fences on slopes (#12975)
==> cmake ..
==> make install
Last 15 lines from ~/Library/Logs/Homebrew/openrct2/02.make:
make[2]: *** [CMakeFiles/libopenrct2.dir/src/openrct2/FileClassifier.cpp.o] Error 1
1 error generated.
make[2]: *** [CMakeFiles/libopenrct2.dir/src/openrct2/GameStateSnapshots.cpp.o] Error 1
1 error generated.
make[2]: *** [CMakeFiles/libopenrct2.dir/src/openrct2/Editor.cpp.o] Error 1
1 error generated.
make[2]: *** [CMakeFiles/libopenrct2.dir/src/openrct2/Cheats.cpp.o] Error 1
1 error generated.
1 error generated.
make[2]: *** [CMakeFiles/libopenrct2.dir/src/openrct2/GameState.cpp.o] Error 1
1 error generated.
make[2]: *** [CMakeFiles/libopenrct2.dir/src/openrct2/Context.cpp.o] Error 1
make[2]: *** [CMakeFiles/libopenrct2.dir/src/openrct2/Game.cpp.o] Error 1
make[1]: *** [CMakeFiles/libopenrct2.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC.
```

I checked the common Homebrew troubleshooting guides, but it's too generic. This seems like a problem with the OpenRCT2 sources.

**Comment by janisozaur** [comment]
Can you provide full logs?

**Comment by AaronVanGeffen** [comment]
Perhaps the Homebrew formula needs to be updated to account for the switch to nlohmann-json? I don't think it's maintained by one of the team members. 

Does the problem go away if you install the relevant formula?

**Comment by erikhuizinga** [comment]
> Can you provide full logs?

How do I do that? What do you need?

> Perhaps the Homebrew formula needs to be updated to account for the switch to nlohmann-json? I don't think it's maintained by one of the team members.
> 
> Does the problem go away if you install the relevant formula?

Who maintains the `openrct2` formula? This issue might need to be issued with them (or in their repo, if any). Indeed, installing `nlohmann-json` fixes the issue. Just `brew install nlohmann-json` (installs v3.9.1) solves the issue.

Suggestions:

- Add `nlohmann-json` as a dependency of `openrct2` in the Homebrew formula.
- Add a CI step that builds PR commits using Homebrew, to verify that the PR still builds for users who, like me, just rely on some package installer / build system to do all the work for them.

**Comment by AaronVanGeffen** [comment]
I suppose I'll file a pull request with Homebrew.

**Comment by AaronVanGeffen** [comment]
I'm not sure who maintains this openrct2 formula. Did you use Homebrew Cask, i.e. [this formula](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/openrct2.rb), or another formula? Oddly enough, this cask doesn't specify any dependencies for building at all.

**Comment by AaronVanGeffen** [comment]
I am not sure who maintains the Homebrew formula. I'll file a PR with Homebrew to update the formula.

**Comment by AaronVanGeffen** [comment]
Has been addressed upstream.
