### ISSUE TITLE
Ghost Items Built By Plugin

### ISSUE THREAD

**Issue by tubbo** [OpenRCT2/OpenRCT2#12995]
**OS:** macOS for me, not sure what @RundesBalli is using
**Version:** v0.3.0
**Commit/Build:** <img width="332" alt="Screen Shot 2020-09-24 at 3 24 25 PM" src="https://user-images.githubusercontent.com/113026/94190395-09acb480-fe7a-11ea-94fe-34622e3e4152.png">

When building bins and benches using a plugin, certain paths will receive "ghost" items on them. These benches/bins are not possible to use, and guests will just breeze right by them, making that particular tile of path useless.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

I'm not sure if this is an actual OpenRCT2 bug, or whether it has something to do with the JS runtime causing some kind of race condition that causes this particular state, but I'm happy to help either investigate in Benchwarmer code or OpenRCT2 for a solution.

**Steps to reproduce:**

1. Download and install [Benchwarmer](https://github.com/tubbo/openrct2-benchwarmer)
2. Open any scenario with a lot of paths
3. Use Benchwarmer to place bins/benches
4. Observe some of those tiles having ghost items placed on them.

**Dump file**

N/A

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/113026/94190660-68722e00-fe7a-11ea-97f5-0af7899f6840.png)
![image](https://user-images.githubusercontent.com/113026/94190678-6c9e4b80-fe7a-11ea-8f85-d065f935ad09.png)

**Comment by RundesBalli** [comment]
I use the following version:
![grafik](https://user-images.githubusercontent.com/46271553/94191792-59a56e80-feae-11ea-8a78-28d30ec48ca0.png)
from:
![grafik](https://user-images.githubusercontent.com/46271553/94191858-7477e300-feae-11ea-8fd8-4387b281f341.png)

I have presented my previous research here:
https://github.com/tubbo/openrct2-benchwarmer/issues/11#issuecomment-685061002 (see the whole Issue!)

**Comment by ZehMatt** [comment]
I've had a quick look at the code and you should be using game actions to do this instead of modifying the additions variable directly, additionally the footpath has a ghost flag for additions which is probably not set correctly since you manually do it. You place objects by using FootpathSceneryPlaceAction

**Comment by duncanspumpkin** [comment]
Do we expose the ghost addition flag?

**Comment by tombomp** [comment]
You can set the ghost addition flag, Tile.isAdditionGhost, it's not listed in the typescript file though https://github.com/OpenRCT2/OpenRCT2/blob/a3c9a84ae110595c7de8d8a9b2c5f361e17d2724/src/openrct2/scripting/ScTile.hpp#L945

This is the function that setting the footpath addition by using the . property uses https://github.com/OpenRCT2/OpenRCT2/blob/a3c9a84ae110595c7de8d8a9b2c5f361e17d2724/src/openrct2/world/Footpath.cpp#L1558

**Comment by ZehMatt** [comment]
Even tho its exposed this should be a read-only in my opinion, if you want to modify things in the park it should be done using game actions, this also ensures the script will work multiplayer wise.

**Comment by tubbo** [comment]
@tombomp Setting `path.isAdditionGhost` fixed it for me. Thanks!

@ZehMatt I'll probably refactor the plugin in the future to place additions when you actually plop down footpaths, as right now it just does a mass build for all existing footpaths, and you're meant to run it over and over as you build new footpaths. This should reduce the amount of code to protect against things like over-building on the same path, being able to build on paths that you don't own, etc. With that refactor, I'll execute game actions to make this stuff happen rather than just modify the paths themselves. That's gonna take some work though, so I'm gonna go with just flipping the boolean right now.

**Comment by tubbo** [comment]
Thanks very much for the insights everyone!

**Comment by tubbo** [comment]
> FootpathSceneryPlaceAction

Do you happen to know the args for this one @ZehMatt? I can't find them in the type defs anywhere.

**Comment by tubbo** [comment]
> if you want to modify things in the park it should be done using game actions, this also ensures the script will work multiplayer wise.

I tried to do this, but I got an "Unknown Custom Action" error. Looking into it a bit more, it turns out that the ActionType I need ("footpathsceneryplace") is not available in v0.3.0 of OpenRCT2. So I guess I'm waiting for the update then to get these game actions working?

**Comment by duncanspumpkin** [comment]
All of the game actions you require are available in the develop branch.

**Comment by ocalhoun6** [comment]
But if he's planning on distributing this plugin to others who are still on the release branch, that might cause problems. Might have to wait for the next release before distributing the ideal solution.

**Comment by duncanspumpkin** [comment]
Next release is today (hopefully) so no need to wait that long.
