### ISSUE TITLE
[Feature] OpenTTD-like transparency options

### ISSUE THREAD

**Issue by knomepasi** [OpenRCT2/OpenRCT2#12990]
Currently transparency and see-throughness of different kinds of objects are handled by separate options available in the menu. You can also bind shortcut keys to them individually.

My suggestion is a new transparency options tool that handles the options for all of the different objects in one window.

Here's a screenshot of the OpenTTD transparency options window:
![openttd-transparency-options](https://user-images.githubusercontent.com/625415/94032212-6354a680-fdc8-11ea-88a0-9a5b3448b9c2.png)

The top row controls whether the object type is transparent or not (when pressed down, transparency is enabled)
The bottom row controls whether the objects are transparent or see-through when in the "transparent" mode. (Implementing this would be a bonus, not a hard requirement.)

Additionally, a shortcut key (X) is bound to toggle the transparency state for all objects contrary to OpenRCT2, where you currenyly have to hit the shortcut keys for each object group separately.

**Comment by IntelOrca** [comment]
The window can arguably just be a plugin, but we will need to implement the ability to enable / disable translucent and fully transparent for each visibility option.

**Comment by knomepasi** [comment]
Here's a Gist with a plugin that adds a simple transparency options window into the game.

**Comment by Gymnasiast** [comment]
Has been implemented.
