### ISSUE TITLE
Option to disable lightning Effect

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#1299]
A user on reddit has suggested it would be nice if we could disable the lightning effect. 

http://www.reddit.com/r/openrct2/comments/37vi1k/suggestions_for_openrct2/crs7u6n

**Comment by trigger-death** [comment]
This would actually be pretty useful, especially when the game is sped up.

**Comment by RollingStar** [comment]
Might be nice for people with [photosensitive epilepsy](https://en.wikipedia.org/wiki/Photosensitive_epilepsy).
