### ISSUE TITLE
Last player action is not truncated

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#13005]
![openrct2_2020-09-27_04-11-41](https://user-images.githubusercontent.com/5415177/94353258-a0929000-0077-11eb-894a-2cc94e8da42e.png)

Might as well arrange it properly maybe.

**Comment by James103** [comment]
What version (commit/build) was this screenshot taken from?

**Comment by ZehMatt** [comment]
develop branch

**Comment by AaronVanGeffen** [comment]
This looks like a regression from one of the recent DrawText refactors.
