### ISSUE TITLE
Console cursor doesn't follow actual cursor position

### ISSUE THREAD

**Issue by gsckoco** [OpenRCT2/OpenRCT2#13024]
**OS:** Ubuntu 20.04 and Windows 10
**Version:** 0.3.0 and 0.3.1
**Commit/Build:** Not sure.

Visual cursor doesn't follow cursor's actual position.

As far as I can tell, it only occurs in the console window, other text inputs such as the Park Name window has a working cursor.
**Steps to reproduce:**
1. Open debug console
2. Input a string, and move back through the string with arrow keys

**Screenshots / Video:**
https://youtu.be/AKAL3_Kj4YE

**Comment by gsckoco** [comment]
I'm going to have a shot at fixing this myself

**Comment by tupaschoal** [comment]
Closed via https://github.com/OpenRCT2/OpenRCT2/commit/2524e9201ac12cc3183667e53a2cf7d86667d52f
