### ISSUE TITLE
Modify rct_window_event_list::tooltip to return arguments

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#13035]
The `rct_window_event_list::tooltip` function currently returns a `string_id*` for its last parameter. It also passes back formatter arguments via the global variable `gCommonFormatArgs`. The `rct_window_event_list::tooltip` should instead return a `rct_string_id` and a `Formatter`. This reduces the usage of `gCommonFormatArgs` and its associated magic.

`std::pair<rct_string_id, Formatter> (*tooltip)(struct rct_window*, rct_widgetindex)`

**Comment by IntelOrca** [comment]
Should we add the string id to formatter or rather make a wrapper / union:
```
openrct2::string
    std::string
    rct_string_id, args (formatter)
```

Then use `openrct2::string` everywhere. Not suggesting we call it `openrct2::string`, just an example.

**Comment by duncanspumpkin** [comment]
That would be a good idea.

**Comment by puranjaymohan** [comment]
Hi I would like to work on this.
Thanks

**Comment by duncanspumpkin** [comment]
@puranjaymohan how are you getting on with this? I was looking at some other tooltip code and I've noticed a few issues that might clash with any work you might have done.

**Comment by puranjaymohan** [comment]
@duncanspumpkin I am having a hard time starting with contributing. Can you assign me a basic task and tell me the basic steps to start contributing.
Thanks

**Comment by duncanspumpkin** [comment]
Sure. I ended up doing this issue. It ended up a bit more involved than I was expecting. Such is often the case with refactors. I'll have a look and see if there is something that definitely wont try grow arms and legs.

**Comment by duncanspumpkin** [comment]
https://github.com/OpenRCT2/OpenRCT2/issues/12391 should be pretty simple it will be pretty similar to https://github.com/OpenRCT2/OpenRCT2/pull/12967
