### ISSUE TITLE
Preferred language dropdown is not populated correctly

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/OpenRCT2#13039]
**OS:** Linux
**Version:** 0.3.1
**Commit/Build:** b92328ce343688dbddfb8f55682133fb3744194f

Look at the gap where Polish is expected to be:

![Diamond Heights 2020-09-30 15-56-54](https://user-images.githubusercontent.com/604665/94695065-c351cc80-0335-11eb-869f-f9120e9e48bc.png)

**Comment by AaronVanGeffen** [comment]
I can't reproduce this on Windows, oddly enough. (Using a CI build of the same commit.)

**Comment by tupaschoal** [comment]
I couldn't reproduce with a local build on Windows either (commit 2063aea5e)

**Comment by AaronVanGeffen** [comment]
Issue persists with a clean rebuild on 2063aea5eff81da74c99dfd5215e3709df5f2d8c with GCC 10.2.0

@janisozaur Do you get the issue as well?

**Comment by keithstellyes** [comment]
Can't reproduce on latest 9681ea4ceaa3aff33e6c05d88e17371fea903b40 or 2063aea5eff81da74c99dfd5215e3709df5f2d8c, Linux GCC 9.3.0

**Comment by AaronVanGeffen** [comment]
It's no longer happening for me either. Very strange. I'll close this, then.

![Diamond Heights 2020-10-10 22-56-12](https://user-images.githubusercontent.com/604665/95664903-dc375a80-0b4b-11eb-9fe6-45b09f4543f7.png)
