### ISSUE TITLE
Software render: Tooltips / Text partially display incorrectly sometimes

### ISSUE THREAD

**Issue by Ryder17z** [OpenRCT2/OpenRCT2#13038]
**Windows** 8.1 **Version:** 0.3.1 0297d0b (x64)

This may be an artifact of interface scaling

- [ ] Reproducible in RCT2 (vanilla)?  untested, unlikely
- [ ] Specific to multiplayer?  No

**Steps to reproduce:**   Unknown

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/2000703/94640562-5f9cb480-02df-11eb-8424-14baea214052.png)

If it's not visible, zoom in on the tooltip. Random letters doesn't look quite right.

This doesn't happen with software render using hardware display

**Comment by janisozaur** [comment]
Using the combination of scale and renderer, works as intended - a limitation that won't be solved.

You're welcome to try software with hw display or OpenGL.

**Comment by Ryder17z** [comment]
> Using the combination of scale and renderer, works as intended - a limitation that won't be solved.
> 
> You're welcome to try software with hw display or OpenGL.

hwdisplay can not be recorded though and opengl has rendering problems

**Comment by IntelOrca** [comment]
@Ryder17z non-integer scales will result in this happening.

**Comment by Ryder17z** [comment]
> @Ryder17z non-integer scales will result in this happening.

Thanks for the explanation.
