### ISSUE TITLE
Track type normalising duplication in Game Actions

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#13047]
Many game actions contain this code:
```
        switch (_trackType)
        {
            case TRACK_ELEM_BEGIN_STATION:
            case TRACK_ELEM_MIDDLE_STATION:
                comparableTrackType = TRACK_ELEM_END_STATION;
        }
```

This should be put into a function. "NormaliseTrackType", for example.

**Comment by SGunner2014** [comment]
Mind if I attempt this?

**Comment by tupaschoal** [comment]
Go ahead!

**Comment by raacker** [comment]
@SGunner2014 Any update for this?

**Comment by duncanspumpkin** [comment]
This was attempted before but we came to the conclusion that there is a different helper function that should be used instead.

**Comment by duncanspumpkin** [comment]
See https://github.com/OpenRCT2/OpenRCT2/pull/13069

**Comment by shakthi124** [comment]
Hi, I put in a pull request for this here: https://github.com/OpenRCT2/OpenRCT2/pull/21553
