### ISSUE TITLE
Keyboard mute button interpreted as C shortcut key

### ISSUE THREAD

**Issue by adamcmain** [OpenRCT2/OpenRCT2#13048]
**OS:** Windows 10
**Version:**  0.3.1
**Commit/Build:**  d01dcea

Pushing the mute button my keyboard (not the key assigned to mute in game sound, but the actual master volume mute button) registers as the action to do whatever is assigned to the C key in game.   By default, it opens up the send chat message box.  However pressing the mute button while the chat window is open does NOT causing the character C to appear in the message text box.  

**Steps to reproduce:**
1.  Have a keyboard with a mute button (Dell sk-8135 for me)
2.  Press the C key on the keyboard
3.  Chat window opens
4.  Press C key multiple times to verify C is typed in the message text box.
5.  Press enter to send message
6.  Press mute button on the keyboard
7.  Chat window opens
8.  Press mute buttons multiple times.  Nothing shown in message text box.
9.  Press enter to close chat

**Comment by Gymnasiast** [comment]
Cannot reproduce on Linux. Might be a Windows-specific bug.

**Comment by AaronVanGeffen** [comment]
Might be related to using SDL scancodes instead of keycodes? (i.e. what #3908 tried to fix)

**Comment by Gymnasiast** [comment]
Also sounds related to https://github.com/OpenRCT2/OpenRCT2/issues/6246.

**Comment by Ryder17z** [comment]
Is that mute button stand-alone or do you have to press Fn+Mute for it to perform that action?

Because I can't reproduce it with Fn+Mute (that is F1 on my laptop) on Win 8.1

**Comment by adamcmain** [comment]
It's a standalone button.  

![image](https://user-images.githubusercontent.com/72170032/95277843-64e48c80-0814-11eb-977d-a99c04dba81f.png)

**Comment by Ryder17z** [comment]
Update: i somehow "updated" to a very old version of OpenRCT2.

Now on a few days old build; I can confirm this happens regardless of how the mute button is implemented on Windows, using Fn+F1 (laptop) and the standalone mute button on my corsair k95 yields the same result.

**Comment by ffrogman** [comment]
I see this bug on Windows 0.3.2 Release build as well. I have the same behavior where it opens the chat box, but does not actually type c in the chat box.

I have a standalone mute button on my keyboard. The issue also occurs on a keyboard with a fn + key to mute.

**Comment by IntelOrca** [comment]
Keyboard shortcuts have been re-worked in latest develop. Does this issue still occur for you?

**Comment by ffrogman** [comment]
Not resolved, but I do see a change. In my previous test months ago I filled at the STOP: A... list by pressing the buttons in the keybinding menu to see what the keybinding menu detected. 

Now when I use the keyboard audio buttons in the keybinding menu they show up describing the correct audio function. But when I use them in a multiplayer game they still seem to be acting as A, B, and C.

**Comment by IntelOrca** [comment]
> Does the key press handler behave differently in in-game panel different vs. having no in-game panels open?

No, and multiplayer shouldn't be any different from single player. I am unable to reproduce what you are seeing.

**Comment by ffrogman** [comment]
Oops I accidentally had the hot keys bound when I was testing in. After testing again with default hot keys I think this bug is resolved. Tested on "b179f6e on develop"
