### ISSUE TITLE
Simplify block sectioned comparisons

### ISSUE THREAD

**Issue by tupaschoal** [OpenRCT2/OpenRCT2#13046]
Lots of places in the code use the following comparison:
https://github.com/OpenRCT2/OpenRCT2/blob/47c72eaed3d9a14303dee5baa78f5772b63cd215/src/openrct2-ui/windows/Ride.cpp#L3826

But there is a simpler version which is a lot easier to read:
```c++
ride->IsBlockSectioned()
```

Please replace all the places in the code using the former for the latter

**Comment by SGunner2014** [comment]
@tupaschoal Can I have this assigned please?

**Comment by tupaschoal** [comment]
Sure, you can work on it
