### ISSUE TITLE
Build ride window shows "0 designs available" for all rides

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#13050]
**OS:** Windows 10
**Version:** 0.3.1
**Commit/Build:** 2063aea

A new bug occurs as a result of a regression which causes the build ride window to show "0 designs available" for all rides. However, it is still possible to place down prebuilt track designs normally.

**Steps to reproduce:**
1. While in any scenario or the Track Designer, open the build ride window.
2. Hover over any available ride type.
3. It will show the number of track designs available before immediately saying "0 designs available, or custom-designed layout"

**Screenshot:**
![Incense Coppice 2020-09-30 18-35-13](https://user-images.githubusercontent.com/61885939/94756331-1898d880-034c-11eb-8f74-56c6033914bf.png)

**Comment by tupaschoal** [comment]
This is a regression from @duncanspumpkin #13034

**Comment by duncanspumpkin** [comment]
Doh
