### ISSUE TITLE
Latest release Linux binaries have incorrect file extension

### ISSUE THREAD

**Issue by arjanvlek** [OpenRCT2/OpenRCT2#13062]
The Linux binaries of 0.3.1 have a file extension of  just `.gz` while they are actualy TARred files (you can't unzip these with `gunzip` and have to use `tar` to extract).

Therefore, the extension should be `.tar.gz`, not ` .gz`

**Comment by AaronVanGeffen** [comment]
I've downloaded the following two files from [the v0.3.1 release page](https://github.com/OpenRCT2/OpenRCT2/releases/tag/v0.3.1). They seem to be in order?
```
$ file OpenRCT2-0.3.1-linux-*
OpenRCT2-0.3.1-linux-i686.gz:   gzip compressed data, last modified: Sun Sep 27 21:12:35 2020, from Unix, original size modulo 2^32 24586240
OpenRCT2-0.3.1-linux-x86_64.gz: gzip compressed data, last modified: Sun Sep 27 21:12:45 2020, from Unix, original size modulo 2^32 72765440
```

**Comment by janisozaur** [comment]
@AaronVanGeffen that's correct, it's a tar that was gzipped. `file` will tell you correctly it's gzipped, but extract it and run `file` again on those.

**Comment by janisozaur** [comment]
Fixed.
