### ISSUE TITLE
Dialog for renaming conflicting track design crops text out

### ISSUE THREAD

**Issue by tupaschoal** [OpenRCT2/OpenRCT2#13083]
**OS:** Windows 10
**Version:** 0.3.1
**Commit/Build:** 7f963c490

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open Track Designs Manager
2. Click "Install new"
3. Select a design that is already installed
4. Click Install
5. Notice the rename box has the text cropped

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/6443427/94993533-190dbb00-0568-11eb-9d25-27c653be667d.png)

**Comment by aw20368** [comment]
MR submitted at #13124. Result of the change:

![ConflictingTrackDialog](https://user-images.githubusercontent.com/29646196/95404690-af810a00-08e3-11eb-8b4a-fe1aa4e9a0c1.png)
