### ISSUE TITLE
Fix code base misspelling

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#1308]
I keep forgetting to correct this mistake that @kevinburke pointed out.

https://github.com/IntelOrca/OpenRCT2/blob/develop/src/ride/ride.h#L388-L389
Should be `SEPARATE`.

If anyone else knows of spelling issues chuck them in here.

**Comment by Gymnasiast** [comment]
I'm not sure whether they're used in actual code as well, but I found several comments that said '(block )breaks' rather than '(block )brakes'.
