### ISSUE TITLE
Usage of ellipsis in string maps

### ISSUE THREAD

**Issue by tupaschoal** [OpenRCT2/OpenRCT2#13107]
Should have used an ellipsis here. (`…`)

_Originally posted by @Gymnasiast in https://github.com/OpenRCT2/OpenRCT2/pull/13066#discussion_r499177773_

After these 2 new strings are the only ones actually using the ellipsis `…` and not the three dots `...`, which have 83 occurrences. Unless you're copying and taking a close look, I guess you'll never really use the fist, due to it not being practical.

- What are the reasons for favoring the first over the latter, other than "it's the actual symbol"?
- Do we make everything use ellipsis then?

**Comment by Gymnasiast** [comment]
> What are the reasons for favouring the first over the latter, other than "it's the actual symbol"?

I would argue that alone is enough of a reason. But another reason is that it will wrap and ellipsise (yep…) correctly.

> Do we make everything use ellipsis then?

Yes, as far as I'm concerned. Can't think if a reason not to.
