### ISSUE TITLE
Underflow on height chart (Ride measurements)

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#13102]
**OS:** Ubuntu 20.04
**Version:** 0.3.1+
**Commit/Build:** a284119990bb94fad7aff97ee2cebccf511556b8

![afbeelding](https://user-images.githubusercontent.com/1478678/95118040-e15e6900-0749-11eb-8ba1-112c20099cc4.png)

**Comment by iking96** [comment]
I can try to look into this one this weekend! 📉
