### ISSUE TITLE
"OpenRCT2 needs files from the original RollerCoaster Tycoon 2..." string is hardcoded

### ISSUE THREAD

**Issue by keithstellyes** [OpenRCT2/OpenRCT2#13125]
The string in the dialog that pops up when the game asset directory isn't set, the string is currently hardcoded, should probably be localizable

Specifically, this string in `Config.cpp`,

> OpenRCT2 needs files from the original RollerCoaster Tycoon 2 in order to work.
> Please select the directory where you installed RollerCoaster Tycoon 2.

**Comment by tupaschoal** [comment]
Nice find! Actually I'd say all strings in `config_find_or_browse_install_directory` should be extracted out into `en-GB.txt` for Localisation,
https://github.com/OpenRCT2/OpenRCT2/blob/119bacdd44a0e954932b01d5ac3deaf882522d27/src/openrct2/config/Config.cpp#L797-L815

**Comment by keithstellyes** [comment]
I'll go ahead and pick this up since it's kinda related to the work I wanna do in #12307
