### ISSUE TITLE
-Wold-enable-old-style-cast has broken GCC-9 builds (probably others)

### ISSUE THREAD

**Issue by keithstellyes** [OpenRCT2/OpenRCT2#13148]
There's a few errors like

```
error: use of old-style cast to ‘struct paint_struct*’ [-Werror=old-style-cast]
   43 | [i].PaintStructs[j].basic.next_quadrant_ps == (paint_struct*)paint_struct_entries)
      |                                                              ^~~~~~~~~~~~~~~~~~~~
      |                                               ---------------
      |                                               reinterpret_cast<paint_struct*> (  )
```

Introduced by `f418acfe1951749d31754553c52c5904a19ba3e1`, I can make a PR real quick fixing that, but I'm surprised this made it past CI?

**Comment by duncanspumpkin** [comment]
Not sure why the CI isn't failing on this. Can you PR the reinterpret_cast

**Comment by keithstellyes** [comment]
Will do real quick

**Comment by Krutonium** [comment]
FWIW It's also broken for me on GCC 10.2.0

**Comment by AaronVanGeffen** [comment]
Compiles fine for me on GCC 10.2.0, oddly enough. But good to get rid of these remaining old-style casts, anyway, of course.

**Comment by AaronVanGeffen** [comment]
Some more breakage in `macos.mm`, which I'll file a PR for shortly.

**Comment by keithstellyes** [comment]
@AaronVanGeffen Just as an FYI, I do have a PR for some of them here: https://github.com/OpenRCT2/OpenRCT2/pull/13150

**Comment by AaronVanGeffen** [comment]
@keithstellyes Oddly enough, my compiler wasn't complaining about that file at all -- just macos.mm

**Comment by keithstellyes** [comment]
Closing since my PR was closed
