### ISSUE TITLE
Flowers don't get fed from nearby water source

### ISSUE THREAD

**Issue by sjoerddebruin** [OpenRCT2/OpenRCT2#1314]
If I remember correctly, it was possible to give flowers water by adding water under a attraction in case you add them around a attraction. This doesn't seem to work anymore, has the behavior changed?

**Comment by Gymnasiast** [comment]
This behaviour has never been in RCT1 or RCT2, unless I'm _very much_ mistaken (i.e. not having noticed it in 15 years of playing RCT1 and RCT2).

**Comment by ThomasdenH** [comment]
This would be a great function, but also one that will need to be possible to disable.

**Comment by PFCKrutonium** [comment]
Reminds me of Minecraft...

**Comment by kevjoe** [comment]
I can't say that I've ever seen this happen before in the game, but flowers do get watered by rain.
But placing them near water does seem to make them wither without rain.

**Comment by sjoerddebruin** [comment]
Hm, could convert this to a feature request then. I thought I've read something about it...
