### ISSUE TITLE
Vehicle tab tooltips show just "Max " or "Max 0  per train"

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#13151]
**OS:** Windows 10
**Version:** 0.3.1
**Commit/Build:** 0c3de1f

The vehicle details and options tab for ride windows now has a bug that makes it harder to know the maximum amount of trains and cars per train on a ride. Hovering over the train and cars per train counters will display tooltips that say "Max " and "Max 0  per train" respectively. I suspect this is another recently introduced regression.

**Steps to reproduce:**
1. Open up any ride, preferably either a roller coaster or a transport ride that can run multi-car trains (e.g. monorail).
2. Go to the vehicle tab (the one inbetween the overview and operating options tabs).
3. Hover over the train and the cars per train counters. It will say "Max " and "Max 0  per train" respectively.

**Screenshots / Video:**
![Test Park 2020-10-10 12-49-23](https://user-images.githubusercontent.com/61885939/95663853-74572480-0af7-11eb-8279-ec6cf4f82084.png)
![Test Park 2020-10-10 12-49-26](https://user-images.githubusercontent.com/61885939/95663854-7620e800-0af7-11eb-985f-820b969b5f36.png)

**Comment by pizza2004** [comment]
I can't see exactly what about it caused this, but this started happening in 61c8cbf.

**Comment by AaronVanGeffen** [comment]
A candidate might be #13137, which was merged today.

**Comment by pizza2004** [comment]
Yeah, that's the only commit from that pull request and the previous build doesn't have this issue.

**Comment by tupaschoal** [comment]
@duncanspumpkin is this the issue you were talking about on the PR or a new one?

**Comment by duncanspumpkin** [comment]
no that is something new. Looks like something was abusing the format args.

**Comment by duncanspumpkin** [comment]
cheats window 5585 (operating limits)
server list 5718 (network version)
ride 5922 5923 (this issue)

This is my list of windows that are doing things incorrectly. Notice they are all OpenRCT2 strings so looks like we didn't understand things correctly when implementing them. Not too hard to fix.

**Comment by pizza2004** [comment]
Line 2814 is where the Ride window starts trying to figure out how to output those strings.  I spent a while finding it earlier but I didn't know enough about how the strings worked to tell what part of it was wrong.

**Comment by duncanspumpkin** [comment]
@pizza2004 don't worry I have a fix coming in shortly. Its because these tabs should have a tooltip event but dont.
