### ISSUE TITLE
[UI] Search box's cursor position at the scenario editor

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#13158]
**OS:** Windows 10
**Version:** 0.3.1
**Commit/Build:** 9af7024

GIF shows everything about this issue ;)

**Steps to reproduce:**
1. Open Scenario Editor
2. Search anything

**Screenshots / Video:**
![what](https://user-images.githubusercontent.com/10726524/95671015-2a407280-0bcd-11eb-91e6-fdd7fc0b9f3e.gif)

**Comment by adamcmain** [comment]
This also happens on the Start Server dialogue.

![image](https://user-images.githubusercontent.com/72170032/96312983-59425400-0fd2-11eb-88fc-25e74664b93f.png)

**Comment by AaronVanGeffen** [comment]
I think all text input fields may be affected. See also #13027

**Comment by AaronVanGeffen** [comment]
Caused by 2857f9d276
