### ISSUE TITLE
Improve organisation of the cheats window

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/OpenRCT2#13160]
The past few days, I have been thinking about how to improve the cheats window. First, I would like to talk about the park cheats tab.

* First off, I think we should further categorise options, so they will be easier to find (back).  To this end, I propose we split off options from the 'general' frame into what I'm calling 'objective' options (name TBD). Likewise, I propose splitting off the buttons from 'staff' into a new 'maintenance' frame (name TBD).

* The 'Park parameters...' button has become superfluous, as the option is also present in the cheats menu. I propose we remove it.

* The 'Freeze weather' button acts as a toggle. I propose we turn it into a checkbox.

* We can group 'Water plants' with 'Plants do not age'. I don't feel they warrant their own group, but they can certainly be juxtaposed.

* The window is quite tall, but doesn't have to be: there is quite a bit of empty space. 

Below is a concrete proposal for what the park cheats tab could look like. (Old on the left, new on the right.)

I welcome any input.

![cheats_2_new](https://user-images.githubusercontent.com/604665/95675994-5ce16f80-0bbb-11eb-83c8-9682ddcc01cb.png)

**Comment by duncanspumpkin** [comment]
The code could also do with general splitting up into tabs in some of the functions

**Comment by knomepasi** [comment]
Could the weather dropdown be layout the same way as park rating forcing?

I would also swap the clear/mowed grass row with the litter/vandalism row, to keep the grass and plants next to each other.

**Comment by AaronVanGeffen** [comment]
> Could the weather dropdown be layout the same way as park rating forcing?

I would prefer not to, as -to me- that would suggest you could only change the weather if you force it to stay. In this, it is different from the park rating cheat.

> I would also swap the clear/mowed grass row with the litter/vandalism row, to keep the grass and plants next to each other.

Nice idea! I'll add that.

**Comment by ocalhoun6** [comment]
>as the option is also present in the cheats menu.

While we're on the subject of reorganizing things ... I've never really liked that there's a cheats menu _and_ a cheats window. Wouldn't it be nicer if all the cheats were in one place?

Obviously, some of these controls need to be in a window, so I'd propose ditching the cheats menu altogether and moving its options into the cheat window, integrating them into this organization as well. Maybe into a kind of a cheats 'home' tab in this window, so the items on that menu are some of the first things that pop up when you open the cheats window.

**Comment by knomepasi** [comment]
> > Could the weather dropdown be layout the same way as park rating forcing?
> 
> I would prefer not to, as -to me- that would suggest you could only change the weather if you force it to stay. In this, it is different from the park rating cheat.

Right, that's true. Then I would argue the "Force weather:" label is a bit misleading though (I  originally interpreted it in the way that you choose the weather type, then just enable/disable freezing with the checkbox as you suggested above) and should probably be something like "Change weather to"

**Comment by AaronVanGeffen** [comment]
> While we're on the subject of reorganizing things ... I've never really liked that there's a cheats menu and a cheats window. (For one thing, that can make it difficult to describe to newbies where various cheats are.) Wouldn't it be nicer if all the cheats were in one place?

@ocalhoun6 We introduced a menu for various reasons -- most of the options in the menu open different windows. The only exceptions are the toggles at the bottom, which have been moved there due to how often they are used. Sorry, bit this is unlikely to change. Not really in the scope I want to discuss here, either, to be honest.

> Right, that's true. Then I would argue the "Force weather:" label is a bit misleading though (I originally interpreted it in the way that you choose the weather type, then just enable/disable freezing with the checkbox as you suggested above) and should probably be something like "Change weather to"

@knomepasi This is a good point. I agree.

**Comment by ocalhoun6** [comment]
>@ocalhoun6 We introduced a menu for various reasons -- most of the options in the menu open different windows. The only exceptions are the toggles at the bottom, which have been moved there due to how often they are used. Sorry, bit this is unlikely to change. Not really in the scope I want to discuss here, either, to be honest.

For ease of use, maybe okay... I will admit there's got to be a lot of people very used to the way it is now and they'll probably be upset if it changes.

But maybe _all_ the options in the cheats menu should be in both places, instead of removing things from the cheats window that are in the cheats menu?

I don't know. It's just that I, for one, find a few regular clicks to be faster and less effort than click-hold-drag to select a menu item.

**Comment by AaronVanGeffen** [comment]
@ocalhoun6 If you'd really like to continue to press this, please file another for it. I would really like this issue to be about the layout of the park cheats tab only.

**Comment by ocalhoun6** [comment]
Heh, okay.

**Comment by knomepasi** [comment]
Since the strings are under review, I wonder whether "Mowed grass" should be "Mow (all) grass" as it's a one-time action, not a toggle.

**Comment by Gymnasiast** [comment]
@AaronVanGeffen I agree with the proposal. The only thing I would do differently is taking out "Goal: Have Fun!" entirely and instead add the "Objective Options" window to the Cheats menu.

**Comment by AaronVanGeffen** [comment]
My initial idea for the two checkboxes (plants and frozen weather) won't work as-is. Unfortunately, some of the translations of their captions are much wider than the English version. I therefore think we should keep them on their own lines instead, and maintain alignment on the left.

**Comment by LucaRed** [comment]
Translations length is already a problem: see `Eval. du parc` in your screenshot, which is the shortened version of "Evaluation du parc", which is also not a literal translation because it wouldn't fit.

I'm the mantainer of the Italian translation and I have the same problem: the correct translation for `Force park rating` would be `Forza la valutazione del parco`, which is way too long to fit in there.

Unfortunately, I don't have a nice solution for this problem (widening the window, maybe?).

**Comment by AaronVanGeffen** [comment]
Please continue any further discussion in #13186.
