### ISSUE TITLE
Duplicate cheat menu items into cheat window? (Or allow access to cheat menu through cheat window.)

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#13161]
I'd really like to see all the options from the cheats menu duplicated in the cheats window. So that they'd then be in both places.
'Scenario options' is already duplicated, available on both, although -- confusingly -- it has a different name in the cheats window: 'Park parameters'. (They should all definitely have the same name in both places.)
(And while we're at it, rename the 'Cheats' menu item on the cheats menu to 'All Cheats', which will help newbies figure it out if they happen to discover the menu before the window.)

Advantages:
- All the cheats will be in one place, making it easier to tell newbies where to find cheats and easier for newbies to explore the available cheats on their own.
- I find that a few normal clicks (for cheat window --> tab I want --> option I want) is easier than the click-->hold-->drag to right position-->release of selecting an item from the menu.
- Sometimes when I'm trying to open the cheats menu, I accidentally open the cheats window instead anyway.
- Some of the cheats menu items _really_ deserve to be organized in with the cheats window items. 'Disable support limits' is the most egregious example -- its absence from the ride cheats tab is awfully conspicuous. I've actually wasted time before looking through the long list of checkboxes in that tab looking for the one that disables support limits, only to come up missing it. Because, I mean, it should *obviously* be one of the ride cheats, right? It only affects rides! But where is it? ... On a _completely_ different menu, as it turns out. That's not very user-friendly, is it?

Disadvantages:
- Adds a little code complexity.
- More buttons and do-dads on the cheats widow.
- Could cause some slight confusion in newbies as to why things are duplicated. (Though the duplicated 'Park parameters' with a different name in each place is already _way_ more confusing.)

_Maybe_ that could eventually be expanded into phasing out the cheats menu entirely? I don't know. Maybe people have gotten too accustomed to it to give it up. Though a lot of the stuff that's been put on the menu in order to make it faster to access has shortcut keys assignable now, which is an even faster way to access it.

Maybe there could also be some subtle way to visually distinguish the various buttons on the cheats window between ones that directly commit actions (like 'Fix Vandalism') and ones that open another window (like 'Park parameters'). Just a subtle difference like different color or different border around the button, something like that. A lot of the downside to adding more things to the cheats window is that everything there looks the same -- that's part of what makes it hard to find things. Ooh -- or maybe greater use of icons within the cheats window? That would give another way to visually distinguish things, helping to mitigate the added complexity.

**Comment by Gymnasiast** [comment]
> Maybe there could also be some subtle way to visually distinguish the various buttons on the cheats window between ones that directly commit actions (like 'Fix Vandalism') and ones that open another window (like 'Park parameters'). 

There already is. `Park parameters...` has an ellipsis at the end, which is a convention that at least dates back to Windows 95 and most likely even further.

Regarding that button itself: the different names and duplication are indeed confusing. To solve this, I think it's best to just remove the "Park parameters..." button, like we already did for "Sandbox mode".

**Comment by ocalhoun6** [comment]
Ah, that's good to know.

I still think it's better to have the options in _both_ places, for the reasons above. You've got to consider approaching it like a newbie, rather than someone who's used to the way things are now.

_At least_ things like 'disable support limits' should be in both places. Maybe not the tile inspector or scenario options, but the things that turn on/off individual cheats should also be in the cheats window, I think.

**Comment by ocalhoun6** [comment]
(badly) mocked up the idea of having the cheats menu accessible from the cheats window:

![example](https://user-images.githubusercontent.com/26573303/95695184-a5fce800-0bea-11eb-98c7-bf52804425b9.png)

**Comment by Gymnasiast** [comment]
Four years on, I still think it’s better not to duplicate. As no other people have come forward, I’m closing this.
