### ISSUE TITLE
Broken dropdown menu in options for selecting rendering engine

### ISSUE THREAD

**Issue by Dakota5488** [OpenRCT2/OpenRCT2#13167]
**OS:** Arch Linux x86_64
**Version:** 0.3.1-134
**Commit/Build:** 2265938e9 on makepkg

The options menu has broken dropdown menus for choosing the rendering engine

- [ ] Reproducible in RCT2 (vanilla)?

**Screenshots / Video:**
![Screenshot from 2020-10-11 21-04-49](https://user-images.githubusercontent.com/64660029/95688986-3862b300-0c0e-11eb-9ad1-fa97ce330bd8.png)

**Comment by Gymnasiast** [comment]
Possibly caused by a refactor. @AaronVanGeffen ?
