### ISSUE TITLE
Same colour umbrellas/balloons/hats/shirts etc

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#1317]
I'd like a check box so that umbrellas/balloons/hats/shirts etc can be the same colour throughout the park. I can see this working like the set same price throughout the park option.
![colour](https://cloud.githubusercontent.com/assets/1381723/8137950/dfd5bcd4-113e-11e5-9d1e-853389d98fef.png)

**Comment by trigger-death** [comment]
I'll look into it. I'll need to see how the game handles stalls with two colourable items and if they can both have separate colours.
