### ISSUE TITLE
Construction Arrow Graphical Issue

### ISSUE THREAD

**Issue by steamroll** [OpenRCT2/OpenRCT2#13215]
**OS:** Windows 8.1
**Version:** 0.3.1
**Commit/Build:** 5ec5ece

While constructing track pieces and pathways sometimes the arrows will stay present after the track piece has been laid or deleted, even after the construction menu has been closed. 

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open Construction of any tracked ride
2. Add/Remove track pieces as normal part of ride building, multiple arrows will appear during building.

**Screenshots / Video:**
![Diamond Heights 2020-10-16 04-26-24](https://user-images.githubusercontent.com/5545659/96236633-4ac05200-0f6a-11eb-93c1-80d86e6d36d6.png)

Here are 3 more screenshots to better show what is happening:
![Diamond Heights 2020-10-16 04-50-27](https://user-images.githubusercontent.com/5545659/96237461-53fdee80-0f6b-11eb-9c54-ebf31a980af2.png)
![Diamond Heights 2020-10-16 04-50-44](https://user-images.githubusercontent.com/5545659/96237463-54968500-0f6b-11eb-9cb8-ec24754a6a93.png)
![Diamond Heights 2020-10-16 04-49-09](https://user-images.githubusercontent.com/5545659/96237464-552f1b80-0f6b-11eb-9ee7-7811c3fd6bb3.png)

**Save game:**
[Diamond Heights.zip](https://github.com/OpenRCT2/OpenRCT2/files/5390304/Diamond.Heights.zip)

**Comment by tupaschoal** [comment]
@mwnciau can you please investigate?

**Comment by duncanspumpkin** [comment]
Is this just an invalidation issue? I take it it would go away if something forced a refresh or you were using the OpenGL renderer.
