### ISSUE TITLE
Can't save the game

### ISSUE THREAD

**Issue by VersionEins** [OpenRCT2/OpenRCT2#13225]
**OS:** Windows 10
**Version:** 0.3.1
**Commit/Build:** 157-gd287653cb (d287653 on develop)

Anytime I want to save any save game the game just says "Can't save game" and saves an empty file.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Comment by duncanspumpkin** [comment]
Do you have OpenRCT2 installed into some exotic folder where you don't have permission to save?

**Comment by VersionEins** [comment]
> 
> 
> Do you have OpenRCT2 installed into some exotic folder where you don't have permission to save?

Nope. It's in the same folder as it has been for years and in which I saved games as recently as the 14th.

**Comment by AaronVanGeffen** [comment]
Trying to narrow this down… Does this still happen if you use the 0.3.1 release build, rather than this develop build?

**Comment by VersionEins** [comment]
I can save on release, no issues.

**Comment by Broxzier** [comment]
Does the path contain any special characters?

Could you try saving when running the game with the `--verbose` switch? Perhaps that gives us more information.

**Comment by Gymnasiast** [comment]
It is possible that Windows Defender's ransomware protection interferes. You might need to whitelist OpenRCT2.

**Comment by VersionEins** [comment]
> 
> 
> Does the path contain any special characters?
> 
> Could you try saving when running the game with the `--verbose` switch? Perhaps that gives us more information.

1. Nope
2. How would I do that?

> 
> 
> It is possible that Windows Defender's ransomware protection interferes. You might need to whitelist OpenRCT2.

Didn't even had it on (thanks for telling me it exists, though).

**Comment by Broxzier** [comment]
Open a command prompt (cmd) and browse (cd) to the folder where openrct2.com is located, then run `openrct2.com --verbose`. It'll open a black console window where information gets printed.

**Comment by VersionEins** [comment]
VERBOSE: packing 207 objects
VERBOSE: exporting object 1KRFWPFG
Encountered zero-sized chunk.
VERBOSE: Checking if file exists: C:\Users\steph\Documents\OpenRCT2\plugin.store.json
VERBOSE: scenario_save(C:\Users\steph\Documents\OpenRCT2\save\New Element\Xophe - Canyoneer2.sv6, SAVED GAME)
VERBOSE: packing 207 objects
VERBOSE: exporting object 1KRFWPFG
ERROR[D:\a\OpenRCT2\OpenRCT2\src\openrct2\rct2\S6Exporter.cpp:1730 (scenario_save)]: Unable to save park: 'Encountered zero-sized chunk.'
VERBOSE: show error, Save GameGame save failed!

**Comment by Broxzier** [comment]
Looks like there is an issue with exporting the objects. The one it breaks on is the "1K Rope Fence with a Gate". Try removing or reinstalling that object and try again: https://www.nedesigns.com/rct2-object/11882/1krfwpfg/

**Comment by VersionEins** [comment]
Okay, so it gets weirder. I have this object in the Object folder but can't find it in the scenery selection screen.

Is it possible that I have too many objects in my object folder?

**Comment by duncanspumpkin** [comment]
Quantity of objects is unlikely to make any difference.
