### ISSUE TITLE
Synchronise crash

### ISSUE THREAD

**Issue by Phanthalassa** [OpenRCT2/OpenRCT2#1322]
Every time I try to test coasters that have 'synchronise with adjacent station' box ticked, the game crashes. Game is fine if I first I pause the game, click test buttons for both coasters, then unpause the game - coasters are perfectly synchronised then, nothing wrong. Crash only happens when I happen to test one coaster that have synchronise setting on without pausing the game. Anyone else having same issue?

**Comment by Gymnasiast** [comment]
Yes, more people experience this issue. It was reported in #1178. 
It seems to be that the bug was already in unmodified RCT2. Because of this, OpenRCT2 will solve it, but it will probably take some time, since the bug isn't in OpenRCT2 code.

**Comment by IntelOrca** [comment]
I can't re-produce, is for a specific type of coaster?

**Comment by Christipher** [comment]
This is a duplicate report - however, I can attest that it is across the board on EVERY type of coaster... (look at #1178 ) where I had made a complaint in reddit on such an issue - It happens on the looping, reverse freefall, wooden, it is across the board.  It is however only apparent when both rides are in working order, what happens if a side breaks down is not problematic.

**Comment by Gymnasiast** [comment]
I can't seem to trigger the bug either. In fact, I have never got it since I started playing RCT2 in 2003. Which doesn't really make it easier.

**Comment by Phanthalassa** [comment]
Sorry for duplication, I only searched with a word 'synchronise' - didn't expect there to be one with 'synchronize'. I'm currently having this problem with Giga, floorless, and twister. Looping seems to be working fine though, strange..

I didn't have this synchronise crash when I played with Giga coasters on the original RCT2 few years ago, which was why I thought it's an OpenRCT2 problem...

**Comment by IntelOrca** [comment]
Could you provide a saved game with the coaster which when tested causes the crash?

**Comment by Phanthalassa** [comment]
Sure. Here it is: https://www.dropbox.com/s/l0mbbyycy2yex0n/katalan13.sv6?dl=0

Two giga coasters in screen will cause the game to crash once you test them. If it doesn't crash immediately, speed up a bit and it'll crash eventually.

**Comment by IntelOrca** [comment]
Okay, it seems to be crashing deep with in vehicle_update which hasn't had much attention yet - more specifically sub_6DE287 which is called from vehicle_update_waiting_to_depart.

I will keep this issue on record as it now has a saved game to test and close #1178.

**Comment by Christipher** [comment]
This is actually easy to duplicate - place any two coasters with stations side by side and have the coasters open at different times and that would cause you the bug right there... this can occur in any park and in the Coaster Designer - but knowing where this happening does help...

**Comment by IntelOrca** [comment]
Seems to be fixed now
