### ISSUE TITLE
Researching new ride type results in "New vehicle now available" message instead

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#13236]
**OS:** Windows 10
**Version:** 0.3.1
**Commit/Build:** 59d785e

I have noticed that in some scenarios, when a new ride type is researched, it does not even send me a message saying "New ride/attraction now available: [ride name]", but instead "New vehicle now available for [ride name]: [vehicle name]".

**EDIT (2020-10-19 18:12 PST):** tupaschoal has confirmed that the research window also shows the wrong info.

**Steps to reproduce:**
1. Load up the [scenario file shown in the screenshot below](https://drive.google.com/file/d/1Ky7mKdSILs3rCXrg2ibvEj7ya3e3Dhr1/view?usp=sharing) and wait until March 30, Year 1.
2. The Air Powered Vertical Coaster will be researched, but the game will think you've researched a new vehicle type instead of a new ride type. Researching the Looping Roller Coaster (which comes afterwards) still correctly results in the "New ride/attraction now available: Looping Roller Coaster" message though.
3. I have also been able to reproduce this by researching a new ride type, modifying the inventions list to move said ride type back to the "Items to invent during game" list, and then having said ride type be researched again. This can be done with any scenario, not just custom ones.

**Screenshots / Video:**
![Extreme Heights 2 2020-10-18 15-00-52](https://user-images.githubusercontent.com/61885939/96386902-473bef00-1153-11eb-90a5-44ef5456aef4.png)
Note that researching the Air Powered Vertical Coaster in the original Extreme Heights scenario still brings up the correct "New ride/attraction now available: Air Powered Vertical Coaster" message.

**Comment by tupaschoal** [comment]
You don't even have to wait for March 30th, when the researched stuff is defined in the research window it already shows the wrong info:
![image](https://user-images.githubusercontent.com/6443427/96525273-e85c9f80-1250-11eb-9aa4-f60dbc86e3d9.png)

I've bisected it with the releases and it's a regression from `v0.1.1` to `v0.1.2`

**Comment by Gymnasiast** [comment]
Changed the label. The `regression` label is meant for issues that have regressed since the last release, which this hasn't.

Also, note that this is not technically the same bug as the one in 0.1.2, even though the results are nearly identical.

**Comment by Fred-1044276** [comment]
![Funtopia 2020-11-02 10-08-22](https://user-images.githubusercontent.com/61885939/97903098-5f834080-1cf3-11eb-963e-49f7cc45c3e1.png)
Can confirm this bug also occurs on the RCT1 scenarios.
