### ISSUE TITLE
Vehicle weight sometimes wrong after using Remove All Guests cheat

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#13234]
**OS:** [Windows 10]
**Version:** [0.3.1]
**Commit/Build:** [d287653]

I sometimes noticed that after using the Remove All Guests cheat in my park (which I sometimes use when it gets too crowded), some rides would stall. It probably has too do with subtracting the guest weight from the trains when they get removed. I have tested this on a river rapids ride, and after filling it with guests several times and also using the cheat several times (with all boats filled, but sometimes also with half of the boats filled), after a few times some of the boats will not go up the hills anymore. Also after a few tries some of the empty boats would go up the hills with different speeds, indicating a weight difference.

[aaRiverRapidsWeight.zip](https://github.com/OpenRCT2/OpenRCT2/files/5397818/aaRiverRapidsWeight.zip)

After removing all guests, one boat is now slower than the others, which can most easily be seen on the lift hill, as it causes a blockage:
![image](https://user-images.githubusercontent.com/6469413/96374279-0a332500-1172-11eb-9549-a07bd7aeda46.png)

**Comment by keithstellyes** [comment]
Related to #13222?

**Comment by duncanspumpkin** [comment]
Yes i think it could well be related

**Comment by Bearbruh69** [comment]
After removing all guests in my park it causes a coaster of mine to valley eventhough the train can easily make the course without passengers. 
![valleyed coaster train](https://user-images.githubusercontent.com/75369079/106459287-ed58fe00-6491-11eb-9216-8f6b4685c422.png)

**Comment by andae23** [comment]
![temp](https://user-images.githubusercontent.com/49458202/106459612-65272880-6492-11eb-82b5-1117496fc563.png)
I have the same issue as well, I have a save file where every time I remove the guests around 5 rides crash or valley. I uploaded the image as an example. The issue seems pretty consistent and from what I can tell it mostly affects trains that are light to begin with.

**Comment by duncanspumpkin** [comment]
Are you using the latest version?

**Comment by andae23** [comment]
I'm always on the latest developer version

**Comment by deurklink** [comment]
I can confirm this bug is currently still in the game. I just used the remove all guests cheat on my Megapark, and several rides immediately stalled, and one boat on the log flume was suddenly much heavier and held up all the other boats on the lift hill.

**Comment by deurklink** [comment]
I did some testing in my Megapark, and found something interesting. To read out the mass of the vehicles, I am using Basssiiie's ride editor plugin.

Here's a ride which uses stand-up coaster trains. It's mostly empty, except for the last 2 seats. The front vehicles all have a mass of 730, and the last vehicle is slightly heavier because of the guests. Nothing strange, so far.
![image](https://user-images.githubusercontent.com/6469413/106498732-f8c31e00-64bf-11eb-98a0-cecef31f4fd6.png)
![image](https://user-images.githubusercontent.com/6469413/106498759-0082c280-64c0-11eb-8246-c3d658a548c8.png)

However, after I use the remove all guests cheat, all vehicles suddenly have a different (and significantly lower) mass, even the vehicles which did not contain any guests. It is almost as if it subtracts the weight of guests who were previously in this coaster, or guest weights from a different ride. 
![image](https://user-images.githubusercontent.com/6469413/106498921-36c04200-64c0-11eb-9f57-8ff04c974437.png)

For the log flume, all boats also have a different weight after using the cheat, with some even showing an overflow (which is why they crawl up the lift hill). 
![image](https://user-images.githubusercontent.com/6469413/106499010-55bed400-64c0-11eb-9f48-ebc3ded81ec4.png)

Here's my megapark, in case anyone wants to test this cheat in a park with tons of attractions.
[Deurklink MegaPark.zip](https://github.com/OpenRCT2/OpenRCT2/files/5905753/Deurklink.MegaPark.zip)

**Comment by deurklink** [comment]
While it is a lot better now, the issue does not seem completely fixed. I just tested this on the log flume in the megapark, and some of the boats still get their weight reduced. The empty weight of a log is 250, and some of the boats had their weight below this after using the remove all guests cheat. It looks like the weight of 1 guest was subtracted from it.

![image](https://user-images.githubusercontent.com/6469413/106738543-54a0ba80-6618-11eb-9aca-59262526cb66.png)

**Comment by deurklink** [comment]
I just tried using the remove all guests cheat again in my megapark, and I can confirm some vehicles had their mass values wrongly changed once again.. In the lazy river a boat got stuck which had its mass value changed to a lower value than an empty boat usually has.. Perhaps re-open this until it is definitively solved?

**Comment by Broxzier** [comment]
Are all vehicles affected, or only some? I suspect it may have something to do with the weight being subtracted for guest that haven't boarded yet.

**Comment by deurklink** [comment]
> Are all vehicles affected, or only some? I suspect it may have something to do with the weight being subtracted for guest that haven't boarded yet.

I just tried it once again in my Mega park, and in 12/20 boats on my log flume have a mass that's below 250 after using the cheat

**Comment by spacek531** [comment]
I can confirm this is still occurring. 
[Funtopia booster test.zip](https://github.com/OpenRCT2/OpenRCT2/files/13720989/Funtopia.booster.test.zip)

I paused the game right after opening the game then removed all peeps. Using the ride vehicle editor, I inspected the mass of each Grapevine train. Here are the weights before and after running the cheat. Car 1 is a zero car and excluded.

Before:
Car | Riders | Weight | Car | Riders | Weight
-|-|-|-
Train 1 Car 2 | 4 | 987 | Train 2 Car 2 | 4 | 1019
Train 1 Car 3 | 4 | 983 | Train 2 Car 3 | 4 | 975
Train 1 Car 4 | 0 | 740 | Train 2 Car 4 | 4 | 1005
Train 1 Car 5 | 2 | 834 | Train 2 Car 5 | 0 | 740
Train 1 Car 6 | 0 | 740 | Train 2 Car 6 | 0 | 740
Train 1 Car 7 | 0 | 740 | Train 2 Car 7 | 0 | 740
Train 1 Car 8 | 2 | 871 | Train 2 Car 8 | 2 | 871

After:
Car | Weight | Delta | Car | Weight | Delta
-|-|-|-
Train 1 Car 2 | 740 | -247 | Train 2 Car 2 | 740 | -279
Train 1 Car 3 | 740 | -243| Train 2 Car 3 | 740 | -235
Train 1 Car 4 | 740 | 0 | Train 2 Car 4 | 740 | -260
Train 1 Car 5 | 740 | -94 | Train 2 Car 5 | 515 | -225
Train 1 Car 6 | 668 | -72 | Train 2 Car 6 | 536 | -204
Train 1 Car 7 | 740 | 0 | Train 2 Car 7 | 740 | 0
Train 1 Car 8 | 740 | -131 | Train 2 Car 8 | 679 | -192

The expected weight values of empty cars is 740.

**Comment by deurklink** [comment]
Maybe a good temporary fix would be to only allow this cheat to remove guests that are not on a ride
