### ISSUE TITLE
Place ride entrance / exit tile glitch

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#1324]
When placing a ride entrance or ride exit, if the location is invalid the tiles where your next track piece would go gets highlighted. This can be reproduced by placing an entrance and then hovering the cursor for the ride exit over the ride entrance.

![image](https://cloud.githubusercontent.com/assets/1482259/8144014/e57bf6c6-11c0-11e5-9e77-aca00108df1b.png)

**Comment by duncanspumpkin** [comment]
Original Bug.
