### ISSUE TITLE
Rides with a length equal to the minimum scenario requirement aren't counted when checking for scenario completion

### ISSUE THREAD

**Issue by thyeggman** [OpenRCT2/OpenRCT2#13257]
**OS:** NA
**Version:** NA
**Commit/Build:** unkown

When doing scenarios with a "10 different coasters with given length" objective, the objective states explicitly that the minimum length is some number, but the code checks for rides with a length greater than that number ([offending check](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/scenario/Scenario.cpp#L870)).  Not sure what the original code intended, but there is a discrepancy between the stated goal and the actual goal.  Possibly original bug?

- [ ] Reproducible in RCT2 (vanilla)? - Unknown
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Build a roller coaster with length exactly equal to the required length and excitement above the requirement.
2. Build 9 more coasters with length greather than the required length and excitement above the requirement.
3. Observe the scenario does not complete.

**Screenshots / Video:**
https://youtu.be/fb1gLu4nXHQ?t=2755 (see corkscrew coaster 1 in the bottom left)

**Comment by James103** [comment]
The bug exists all the way from OpenRCT2 release version 0.0.2 / develop commit 999488d38c8bbbb41fe1ffd384a46f0952c534fb, and most likely even earlier.

**Comment by keithstellyes** [comment]
Wouldn't be the first fixed bug from the original, https://github.com/OpenRCT2/OpenRCT2/issues/13222 lol

**Comment by Gymnasiast** [comment]
It will be either a bug in our original implementation, or in vanilla.

@thyeggman Could you upload a scenario that fulfils the criteria you mentioned, so I can test in vanilla?

**Comment by thyeggman** [comment]
I'll try to put something together tonight, the video I linked is from someone else and I don't think they saved it
