### ISSUE TITLE
Marketing campaigns available in ride window

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#1325]
I've never found it intuitive selecting rides from a drop down list, for a marketing campaign. I think it would be easier if the option was available in the actual ride window like shown. 
![mar](https://cloud.githubusercontent.com/assets/1381723/8144159/9411cd78-11c6-11e5-8031-1548452c2c6c.png)

**Comment by Gymnasiast** [comment]
Adding too many buttons will clutter up the interface. The current approach has all the marketing stuff in one place, and in an intuitive place (the Finance window).

**Comment by kevjoe** [comment]
I'd vote against this and agree with Gymnasiast, this feels like it's too much on the toolbar and well... marketing is in a right place for me, in the finance. 
Promotions are a park thing in my opinion, and should be in the finance/park management area. Not on the individual rides.

**Comment by Patrik356b** [comment]
I agree with kevjoe & Gymnasiast

**Comment by tsunamistate** [comment]
I'd have to agree with Gymnasiast. Per-ride ad campaigns would be really tedious and introduce unnececary micromanagement. Plus, I'd say, for now, changes this drastic would change too much of a game and distract from main goal - reverse-engineering the game.
