### ISSUE TITLE
bug in plugin API: deleting key of sharedStorage not working

### ISSUE THREAD

**Issue by Sadret** [OpenRCT2/OpenRCT2#13266]
ScConfiguration.hpp L 254
`duk_del_prop_string(ctx, -1, key.c_str());`
is not working as intended and should be changed to
`duk_del_prop_lstring(ctx, -1, n.data(), n.size());`

**Comment by tupaschoal** [comment]
Care to elaborate what is the issue you're facing or how you came to this conclusion?

**Comment by Sadret** [comment]
`sharedStorage.set("namespace.key", undefined)` should delete the key if existent, but doesn't.
`duk_del_prop_string` expects the key as third argument, but in L254 as above, `key` corresponds to "namespace.key".
In L 239 this was already split up:
`auto [ns, n] = GetNamespaceAndKey(key);`
So, the method should be called with `n` as key.

**Comment by AaronVanGeffen** [comment]
Could you file a PR for the bug fix, then?
