### ISSUE TITLE
Scenery group research issues

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#13263]
**OS:** Windows 10
**Version:** 0.3.1
**Commit/Build:** 214f699

A regression bug has now made it impossible to select or deselect "Scenery & Themeing" from the research priority window even if scenery groups can be researched in the scenario. In addition, viewing scenery groups in the Inventions list wrongly shows "ALT +" as their research group.

**Steps to reproduce:**
1. Open the research window and open the tab that allows you to change research funding and priorities. You have to do this in a scenario where scenery groups can be researched (in this case, a custom scenario like the one shown below).
2. The "Scenery & Themeing" tab is now always grayed out.
3. Open the inventions list and hover over any scenery group.
4. You should see "ALT +" as said scenery group's research group.

**Screenshots:**
![Antediluvian Antics 2020-10-22 11-54-14](https://user-images.githubusercontent.com/61885939/96917543-e4ea3380-145d-11eb-9577-00e6aeb3c85e.png)
![Antediluvian Antics 2020-10-22 12-00-48](https://user-images.githubusercontent.com/61885939/96917859-3f838f80-145e-11eb-9c49-0cec7492e909.png)
These screenshots are from my scenario [Antediluvian Antics](https://drive.google.com/file/d/1IE3Ma6imQfn4WafCEPxy9167MONAEEDy/view?usp=sharing).

**Comment by aw20368** [comment]
Seems to be a recent regression. 26720eb34 does not have this issue on Crazy Castle.

**Comment by Fred-1044276** [comment]
![Arid Heights 2020-10-22 17-42-27](https://user-images.githubusercontent.com/61885939/96943787-f9462480-148d-11eb-97f3-42313565ea59.png)
Can also confirm that all scenarios with researchable scenery groups are affected.
