### ISSUE TITLE
Autosave Amount Limit is Ignored

### ISSUE THREAD

**Issue by RoboAtelier** [OpenRCT2/OpenRCT2#13282]
**OS:** [Windows 10, Linux Mint 19 MATE]
**Version:** [0.3.1-2]
**Commit/Build:** [4c39ee9]

This build is currently ignoring the autosave amount limit specified in the options menu/config.ini file.
I've only tested an autosave amount limit of up to 20, but the game creates an infinite amount of autosaves until there is no more space.

- [X] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Go into the options menu.
2. Specify any autosave frequency other than 'Never'.
3. Specify an autosave amount.
4. Start a server or scenario.
5. Wait for autosaves to be generated.

**Dump file**
N/A

**Screenshots / Video:**
![autosaves](https://user-images.githubusercontent.com/27904956/97091547-95953600-160a-11eb-9b1d-4708658b5f60.png)

**Save game:**
N/A

**Comment by keithstellyes** [comment]
Yeah this definitely seems to be an issue, looking into it
