### ISSUE TITLE
Litter and vomit sometimes not loading with RCT1 saved game or scenario

### ISSUE THREAD

**Issue by joeraz** [OpenRCT2/OpenRCT2#13289]
**OS:** Windows 10 (both x86 and x86-64 versions)
**Version:** Was able to reproduce in both 0.3.1 and the development build 0.3.1-199-g4c39ee9fb
**Commit/Build:** Was able to reproduce in both d01dcea and 4c39ee9

When I attempt to load an RCT1 scenario or saved game, there is an issue where sometimes litter and vomit on the paths does not load, and the paths are completely cleaned in game.  Though other times, the litter and vomit shows up on the paths just fine.  This is most prevalent in the Ivory Towers scenario, which starts with a large amount of litter and vomit already in the park, but I have seen this happen in other saved games/scenarios too, though this only happens with RCT1 scenarios/saves and not RCT2 scenarios.

It appears that it is more likely to load correctly when I try to load the scenario/saved game from in game, and usually fails to load the vomit if I try to load it from the main menu, but this does not appear to be a hard and fast rule.  As I was testing this with Ivory Towers, I noticed the vomit in Ivory Towers is most likely to load if I try to load the save/scenario from another version of Ivory Towers, and fails to load if I try to load it from, say, Bumbly Beach.  There's clearly more to it, but I'm not sure of the pattern.

Here is a video showing some of my testing with the issue: https://youtu.be/p_iv1SxdUVg - sorry if the video quality isn't excellent, but it should show the issue occurring.

Hope I've explained this well enough.

**Steps to reproduce:**
1. From the main menu, attempt to load the RCT1 scenario Ivory Towers - no vomit will appear on the paths.
2. Once in game, start a new game using the same scenario - the vomit will appear on the paths this time.

**Comment by tupaschoal** [comment]
Somehow this is a regression from Duncan's https://github.com/OpenRCT2/OpenRCT2/commit/2660df

**Comment by duncanspumpkin** [comment]
I'm not sure how it could be related to my change. I'll investigate but I need a save file to compare.

**Comment by tupaschoal** [comment]
I bisected it following what op said: just opening ivory towers from the main menu
