### ISSUE TITLE
Automatically remove all unused object entries.

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#1329]
For now, add a command to the console to remove all unused object entries.

**Comment by Liampie** [comment]
Problem with having this as a console feature is that you cannot use it for parks that you can't open due to missing scenery. I would still need to use an external program.

**Comment by rwjuk** [comment]
@Liampie Removing objects from parks you can't open will be added to the 'missing objects' window.

**Comment by Liampie** [comment]
Also removing them one by one/individually?

**Comment by oli414** [comment]
This issue can be closed as it has been implemented in #6324
