### ISSUE TITLE
Map window rendering cuts off pixels in corner of maps facing West & North

### ISSUE THREAD

**Issue by tellovishous** [OpenRCT2/OpenRCT2#13294]
**OS:** Windows 10
**Version:** 0.3.1
**Commit/Build:** d287653

I just noticed that when opening the map window, the map isn't centered properly and is positioned a little too far to the left or top when it's facing West or North respectively, which cuts off several pixels on the corner of the map. This seems to happen in vanilla RCT2 as well.

- [Yes] Reproducible in RCT2 (vanilla)?
- [No] Specific to multiplayer?

**Steps to reproduce:**
1. Load a scenario and view the map window.
2. The map will be positioned either too far left or too far up top depending on the rotation, which cuts off a bit of the corner view.

**Screenshots / Video:**

Forest Frontiers:
![image](https://user-images.githubusercontent.com/17260813/97095423-7bfcea00-161c-11eb-86f2-237198098aea.png)
Electric Fields:
![image](https://user-images.githubusercontent.com/17260813/97095540-0bef6380-161e-11eb-9478-397a14f28e22.png)

**Comment by tupaschoal** [comment]
Does happen in vanilla, so I'm marking it as an original bug

**Comment by Broxzier** [comment]
What if you rotate the view? It looks like in Electric Fields the top is cut off instead.

**Comment by tellovishous** [comment]
> What if you rotate the view? It looks like in Electric Fields the top is cut off instead.

Just looked at that again myself, and actually, it seems that _all maps_ will be cut off in the corner when the map is facing West & North, but East & South don't seem to be effected.
I'll update the title/description accordingly.

**Comment by Broxzier** [comment]
Just tested a bit more. On max map size, it'll always cut off the top and left corner, no matter the rotation. That also explains why it does only seem to be an issue for one corner. Simply moving the entire map a bit down and to the right probably fixes this already.

**Comment by tellovishous** [comment]
Also, I suppose this ties into issue #7248 as well
