### ISSUE TITLE
Prebuilt ride design ghost has no entrance or exit buildings

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#13306]
**OS:** Windows 10
**Version:** 0.3.1
**Commit/Build:** 03ef249

If you try to place down a prebuilt ride design anywhere where it can be built, its ride entrance and exit buildings will not show up. The station style it was saved with is still carried over though, and placing down the design is still possible without any major issue.

**Steps to reproduce:**
1. Select any prebuilt ride design for any ride type (e.g. Updraft for the Flying Roller Coaster).
2. Place it down anywhere where it can be built (assuming you have sufficient funds or if it was built with certain cheats, then either "Enable all drawable track pieces", "Allow chain lifts on all track pieces", "Disable clearance checks", or "Disable support limits").
3. You will now see that the entrance and exit buildings do not show up in the ride design's ghost, but they still show up correctly once the ride has actually been built.

**Screenshot:**
![Termite Excavation 2020-10-26 18-08-49](https://user-images.githubusercontent.com/61885939/97244720-ab475e80-17b6-11eb-81c1-b141613895eb.png)

**Comment by duncanspumpkin** [comment]
Will be caused by https://github.com/OpenRCT2/OpenRCT2/pull/13304/commits/c440dac6004a28cda3319c06966545808764f464 ghosts no longer update the station id's so entrances/exits will fail to place (in ghost mode)

**Comment by manuelVo** [comment]
I've just verified this. It's indeed a regression introduced by c440dac. Two solutions to remedy this I could think of are: 
* Prevent modification of the station by ghost tiles only when a simulation is running
* Allow modification of the station by ghosts only when a design is being placed.

Any thoughts?

**Comment by duncanspumpkin** [comment]
I was thinking we could just make ghost entrance/exits not care for station ids. Might just push the issue into something later though. Hmm. Try your solution and see how it looks.
