### ISSUE TITLE
Not all Corkscrew RC pieces shown with "Show all track pieces" on 

### ISSUE THREAD

**Issue by RQWorldblender** [OpenRCT2/OpenRCT2#13324]
**OS:** Ubuntu 20.04
**Version:** 0.3.1
**Commit/Build:** PPA, version 0.3.1-develop-0\~1993-202010300552-gbbf91d961\~ubuntu20.04.1

Just like #13029, except that this is now for the Corkscrew Roller Coaster. The flat to steep pieces that normally appear for the Hypercoaster no longer appear even with the "Show all track pieces" cheat enabled. The only way around this is to enable the "arbitrary ride types" cheat, and change a corkscrew roller coaster to a hypercoaster, in order to access these pieces.

**Steps to reproduce:**
1. Build any corkscrew roller coaster design, even a custom one.
2. Enable the "Show all track pieces" cheat. The flat to steep pieces are inaccessible, even with this cheat turned on.
3. The sign for this is that the steep buttons are not enabled when the selected piece (from custom design) is a flat piece.

**Comment by Fred-1044276** [comment]
The Hypercoaster also doesn't have the Corkscrew Roller Coaster boosters accessible anymore.
