### ISSUE TITLE
Crashed rides never become safe again

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#1333]
After building a ride which crashes a few times during testing, the ride remained "unsafe" after it was opened. So near to no peeps went on the ride with the thoughts _"I am not going on X, it isn't safe"_.

Not sure whether this is a peep issue or a ride issue, more likely a ride issue. But there aren't any identified fields in the ride struct which say anything about crashes. Ideally a ride that has undergone construction after crashing should reset its crash history (particularly if the crash history was only during testing and therefore not resulting in any fatalities).

**Comment by Gymnasiast** [comment]
Normally (i.e. in vanilla RCT2) people will eventually ride a crashed ride again, but it takes time. Of course, immediately resetting crash history if the crash occurred during testing (either in closed mode or test mode, with nobody in the crashed trains) does sound like an improvement.

**Comment by IntelOrca** [comment]
I sped up the game, even after 10 years they still wouldn't ride it,  I don't know if this is related to the number of crashes.

**Comment by Gymnasiast** [comment]
No, i don't think so. In vanilla RCT2, it would take a year or so, with some people even going on the ride after a few months.

**Comment by Phanthalassa** [comment]
I'm terrible at designing coasters and they crash every couple months. Still people go ride them as soon as I open it back up!

**Comment by Achilleshiel** [comment]
There is a function in the vanilla that after 2 or 3 crashes you need to edit the rollercoaster. But that's what I heard. I don't know the specifics about it, but i will investigate.

**Comment by rubdos** [comment]
I've noticed this issue yesterday too; a rubber boat ride that crashed during testing phase and nobody wants to ride it except for some extremely happy people that "risk their lives" (non sic, obvioulsy). They come out and said "boat ride was geweldig!" (was fantastic!).

**Comment by duncanspumpkin** [comment]
It wouldn't be hard to check which function has gone wrong just do a search on lifecycle flags and see where it should reset the has crashed bit.

**Comment by duncanspumpkin** [comment]
Issue is in `finance_pay_ride_upkeep()` there is a missing decrement on line 144 it should be:

`if (ride->last_crash_type != RIDE_CRASH_TYPE_NONE) ride->last_crash_type--;`

I also suggest we relabel `last_crash_type` to `crash_timeout` and change `RIDE_CRASH_TYPE...` to `RIDE_CRASH_TIMEOUT_...`.

**Comment by IntelOrca** [comment]
Doesn't that mean it gets reset on the next call to finance_pay_ride_upkeep?

**Comment by duncanspumpkin** [comment]
Finance pay upkeep is called once a month. A crash will therefore make peeps not ride a ride for 2 months if there were no casualties and 8 months if there were.
