### ISSUE TITLE
Mechanics called to fix just-fixed rides

### ISSUE THREAD

**Issue by adam-bloom** [OpenRCT2/OpenRCT2#13344]
**OS:** macOS
**Version:** 0.3.1
**Commit/Build:** d01dcea

When a mechanic is completing repair of a ride, there appears to be a transient state where the mechanic is no longer fixing the ride, yet the ride is not yet fixed. This calls another mechanic to fix the ride, while the original mechanic completes the repair and re-opens the ride. This leads to in-efficient use of staff, since mechanics are sent to fix rides that do not need to be fixed. I do not have vanilla RCT2 available - can someone test this out? I've attached a sample save file.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Load attached save file (or create any scenario with a broken ride and multiple mechanics)
2. Observe mechanic 1 completing repair of ride
3. Mechanic 2 will be paged as the ride is re-opening (this happens very quickly when using the attached save)
4. Mechanic 2 then goes to repair the functioning ride.

**Save game:**

[Mechanic_Example.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/5472828/Mechanic_Example.sv6.zip)

**Comment by rpstester** [comment]
FYI, I have the same problem in #12895

**Comment by tupaschoal** [comment]
Closing this one as duplicate then
