### ISSUE TITLE
footpath addition vs. footpath scenery

### ISSUE THREAD

**Issue by Sadret** [OpenRCT2/OpenRCT2#13346]
Benches, litter bins etc. are called "footpath additions" almost everywhere in the source code.
On the other hand, the corresponding game actions are called `FootpathScenery[Place|Remove]Action`.

I propose to change this, so that it is called "addition" everywhere. This would include changing the plugin API, which also uses e.g. `FootpathElement->addition` and `ObjectType "footpath_addition"` alongside `ActionType "footpathsceneryplace"` and `ActionType "footpathsceneryremove"`.

**Comment by Sadret** [comment]
If this suggestion gets approval, I would take care of the refactoring.

**Comment by IntelOrca** [comment]
I personally support this change.

**Comment by Gymnasiast** [comment]
Should not have gone in the changelog, as it is something that only matters to the developers and is not something that will affect the users.
