### ISSUE TITLE
Expose all TileElement data to plugin API

### ISSUE THREAD

**Issue by Sadret** [OpenRCT2/OpenRCT2#13384]
As of now, every `Tile` has an int8 data array that stores the data of all its `TileElement`s.
A lot of this data is already also accessible through fields in the respective `XyElement extends BaseTileElement` interfaces.

This issue demands to make all of the data available.

In some cases, parts of the data is used in different ways, depending on the situation.
E.g. for footpaths, `AdditionStatus `and `rideIndex` share the same memory.

In a lot of other cases, one int8 is split up bitwise for different uses.
E.g. `flags` consists of 4 bit for occupied quadrants, 1 bit for the ghost flag, 2 unused bits, and 1 bit for the last tile flag.

A complete list can be found [here (Google Spreadsheets)](https://docs.google.com/spreadsheets/d/1UqbZRRDDazb0tiR5BqVx5_CBLKYgRJ6Q0obEVId-zCk).

Now, I think there are a few general points to discuss here:

1. Should we expose every single of these fields?
2. For flags etc, should we add a field for every flag or one field with the combined value of all flags?
3. If the getter and setters transform the value before returning/setting, should we use the transformed value or the raw one?
E.g. `TileElementBase` stores the `base_height` as `value / COORDS_Z_STEP`. The current API uses the raw value in this case.
4. Should we include other fields, that do not corresponds to a getter/setter of some TileElement data?
E.g. `isHidden()` just does calculations that are also possible within the plugins.
`SurfaceElement` has readonly fields for `hasOwnership `and `hasConstructionRights` although there are no getters for that.

**Comment by Sadret** [comment]
This is currently my opinion:

1. Yes. For every field, sooner or later ther is a plugin developer who needs it.
2. One field for every flag. It is much more independent from the implementation, which might change with the new save file format. (Although this leads to roughly ten more fields in TrackElement)
3. Use the transformed values. As above, it is much more independent from the implementation.
4. No, I would keep this interface "pure". For the ownership flags, we could split them up like in no 2 and implement getters and setters.

**Comment by duncanspumpkin** [comment]
I would prefer that there is a getter and setter for each of the fields so it reflects how they are used in the rest of the codebase. We wont be changing the size of `TileElement` it has already been resized for future use.

**Comment by IntelOrca** [comment]
`isHidden` is planned to be a real flag once the new save format is available. It helps ensure plugins still work correctly after the transition.

**Comment by Sadret** [comment]
I'd like to suggest the following changes:

#### Add
TileElement.isGhost
Footpath.edges
Footpath.corners
Track.mazeEntry
Track.colourScheme
Track.getSeatRotation
Track.brakeBoosterSpeed (return actual brakeBoosterSpeed , i.e. the stored value times 2)
Track.isInverted
Track.hasCableLift
Wall.slope
Wall.primaryColour
Wall.secondaryColour
Wall.tertiaryColour
Wall.bannerIndex
LargeScenery.bannerIndex
LargeScenery.sequence
Banner.bannerIndex
Banner.direction

#### Change
TileElement.baseHeight (return actual baseHeight, i.e. the stored value times 8)
TileElement.clearanceHeight (return actual clearanceHeight , i.e. the stored value times 8)

#### Remove
Footpath.edgesAndCorners (split up into edges and corners)
Tile.data (covered by these changes)

#### Ignore
TileElement.isLastTile (technical)
Surface.hasTrackThatNeedsWater (technical)
Footpath.isSloped (covered by slopeDirection)
Footpath.hasQueueBanner (covered by queueBannerDirection)
Track.doorAState (unused)
Track.doorBState (unused)
Track.photoTimeout (technical)
Track.isHighlighted (technical)
Track.hasGreenLight (technical)
Track.blockBrakeClosed (technical)
Track.isIndestructible (technical)
SmallScenery.needsSupport (technical)
Wall.animation (technical)
Banner.allowedEdges (technical)

#### Remarks
- Banner.position will be merged into TileElement.direction, as it has the same semantics, especially in the corresponding place actions.
- Footpath.direction will now always be 0, as the direction is undefined for paths.
- The changes for baseHeight and clearanceHeight correspond to point number 3 in the first comment. WaterHeight already returns the correct value.
- It's debatable if fields that I decided are "technical" should really be excluded.
