### ISSUE TITLE
Add pause button to the Track Designer

### ISSUE THREAD

**Issue by visor841** [OpenRCT2/OpenRCT2#13398]
**OS:** [Kubuntu 20.04]
**Version:** [0.3.2]
**Commit/Build:** [cea5fab, release]

~~Would it be difficult to allow pausing in the Track Designer? I'm starting to make real world coasters, and sometimes I like to pause, to get a look at speed and such at specific moments. I can just make a blank scenario and use that, so this isn't really important, but I didn't seen any see any discussion about this here, so I thought I'd bring it up in case it was a simple addition. If this would be difficult to do, I'm fine with this issue being closed.~~

Update: I just changed the pause shortcut (I don't have a pause button on my keyboard), and can confirm that it works. So pausing does work, there's just no pause button in-game currently.

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open the Track Designer
2. Pick a ride and go to the next step
3. See that the pause button isn't there

**Comment by Gymnasiast** [comment]
Shouldn't be difficult. By the way, pressing the Pause button on the keyboard _might_ already work.

**Comment by visor841** [comment]
Ah, yes, that does work. I should have figured there was a shortcut and tried it, but I had just assumed that no pause button meant no pausing.
