### ISSUE TITLE
Peeps are sometimes a little bit *too* debunched.

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#13409]
**OS:** Kubuntu Linux 20.04
**Version:** ??? Version info still not showing up on Linux title screen -- updated as of this post
**Commit/Build:** ???

I'm a huge fan of  #12917, but it seems that things have gone a bit too far. In some cases, peeps are _so_ debunched that they walk completely off of the path. This sometimes even puts them on the wrong side of trash cans and guardrails.

This happens fairly rarely, but in even a moderately busy park, it's common enough that you can spot it happening frequently if you're looking for it. The screenshots below were all captured within a few minutes of each other in a park with only about 1000 guests in it.

Not that it isn't realistic to have some guests wandering outside the bounds of your paths, but I don't think this is the intended behavior. The peeps' viable path choices probably just need to be narrowed down a little bit.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open a fairly busy park.
2. Wait and watch for peeps walking next to the path instead of on the path.

**Screenshots / Video:**

![Quanahog Winter Games 2020-11-11 17-39-32](https://user-images.githubusercontent.com/26573303/98885404-d2ed2680-2446-11eb-95ed-e5c9dd99ce5f.png)
![Quanahog Winter Games 2020-11-11 17-40-09](https://user-images.githubusercontent.com/26573303/98885416-d7b1da80-2446-11eb-9345-1f43d6855491.png)
![Quanahog Winter Games 2020-11-11 17-40-59](https://user-images.githubusercontent.com/26573303/98885430-dbddf800-2446-11eb-9941-7536ef0aa723.png)
![Quanahog Winter Games 2020-11-11 17-41-04](https://user-images.githubusercontent.com/26573303/98885438-e00a1580-2446-11eb-9999-be8ee30d1336.png)
![Quanahog Winter Games 2020-11-11 17-41-13](https://user-images.githubusercontent.com/26573303/98885450-e4cec980-2446-11eb-807d-f62e289b56b3.png)

**Comment by ocalhoun6** [comment]
Example of peeps walking on the wrong side of benches:
![Quanahog Winter Games 2020-11-11 22-08-56](https://user-images.githubusercontent.com/26573303/98911563-a43c7380-2479-11eb-8889-431abeaf2271.png)

**Comment by tupaschoal** [comment]
Maybe @richard-fine wants to take a look?

**Comment by richard-fine** [comment]
Interesting...

**Comment by richard-fine** [comment]
I've got a feeling that this is actually a bug that was already there before, but was hidden by the old bunching-up behaviour... you can see in the first screen recording in #12917 that peeps will sometimes turn a corner in such a way that they are aligned with the very edge of the path, but the old behaviour meant they would correct after a few tiles so you wouldn't really see it. The new behaviour means they can keep walking that far out until they change direction again, making it more obvious.

I'll see what I can find...

**Comment by richard-fine** [comment]
@ocalhoun6 I've got what I think is a reasonable fix in #13415. I've run with it on bpb for a while and couldn't see any more offending peeps (though they were pretty tough for me to find before). If you're up for trying out the branch with your park to see if you can still see any problems, that'd be cool - otherwise I'll just go ahead and chase this through the PR process for the next release.

**Comment by ocalhoun6** [comment]
@richard-fine 

Yeah ... I don't really know how to download, build, and run different branches on linux. So go for it! From the sounds of what you wrote on the PR, it seems like it's just the fix that's needed.

**Comment by richard-fine** [comment]
No need to build it yourself, you can grab it from the CI run on my branch: https://github.com/OpenRCT2/OpenRCT2/actions/runs/362473120

(The tests fail right now but that's because I have to land another PR in a separate repo to update the replay files - it shouldn't prevent you from testing the change if you want to).

**Comment by tupaschoal** [comment]
Can you confirm it improes what you've reported @ocalhoun6 ?

**Comment by ocalhoun6** [comment]
Not really. Trying to install multiple versions on linux is a rabbit hole I don't really want to go down, and besides I'm pretty swamped with work right now and don't have time to mess with it.
I trust you guys, and I'm pretty sure this isn't a linux-specific bug, so anybody could test it.
