### ISSUE TITLE
Cannot put chain lift on covered dinghy slide track.

### ISSUE THREAD

**Issue by thiebert** [OpenRCT2/OpenRCT2#13407]
**OS:** Windows 10 
**Version:**  0.3.2
**Commit/Build:** d61e81b

**Explanation of the issue**
When constructing a ride using dinghy slide track, selecting either covered track or chain lift deselects the other option, even with the "Allow chain lifts on all track pieces" cheat enabled. It was previously possible to create such a piece (covered track with chain lift) in vanilla using 8cars, and is also possible to achieve this through the tile inspector, but not through the ride creation menu

**Steps to reproduce:**
1. Activate "Allow chain lifts on all track pieces" cheat
2. Build a dinghy slide
3. Select "covered" track
4. Select chain lift

**Comment by DKarandikar** [comment]
Given that this is achievable in the tile inspector, it looks like this should be mostly logic in windows/RideConstruction.cpp to make this work.

To make it work really nicely, we'd probably want some new sprites with the chain lift being visible going into the tunnel. 

I can take a look at just the ride construction logic for now.
