### ISSUE TITLE
Newly opened Go-Karts track shows the status message of: "Race won by" with the name blank.

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#13427]
**OS:** Kubuntu Linux 20.04
**Version:** ??? Version info still not showing up on Ubuntu title screen (see #12909) updated as of this post
**Commit/Build:** ???

The first time a Go-karts is opened, the status message at the bottom of the window says 'Race won by' and just leaves it at that. Seems like it would make more sense for it to say 'X guests on ride' or something to that effect or even just 'open' if the track has never been run and it's never been won by anyone, right?

Really minor thing, really, but it seems like it could be improved ... and *maybe* it wouldn't be difficult to do so?

- [ ? ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Build a complete go-karts track
2. Close the construction window (the ride window opens)
3. Open the ride (probably needs to be in the default race mode, not continuous circuit)
4. Ride status message now reads 'Race won by _______'

**Screenshots / Video:**
![Forest Frontiers 2020-11-16 22-04-26](https://user-images.githubusercontent.com/26573303/99352887-4a142780-2858-11eb-8441-24a0629992c8.png)

**Comment by duncanspumpkin** [comment]
This was touched very recently. So likely a regression.

**Comment by ffrogman** [comment]
I tested and this works in Windows 0.2.6 with the string "0 people on ride". It is broken in Windows 0.3.0 and 0.3.2.
