### ISSUE TITLE
Typo in OBJECTIVE_REPLAY_LOAN_AND_PARK_VALUE (should be OBJECTIVE_REPAY_LOAN_AND_PARK_VALUE)

### ISSUE THREAD

**Issue by James103** [OpenRCT2/OpenRCT2#13426]
**OS:** (Universal)
**Version:** 0.3.2
**Commit/Build:** 23871de

There is a typo in `OBJECTIVE_REPLAY_LOAN_AND_PARK_VALUE`, which should be `OBJECTIVE_REPAY_LOAN_AND_PARK_VALUE`. The issue is specific to the OpenRCT2 codebase only.

In human-readable form, it's like saying "**Replay** loan and achieve park value" instead of "**Repay** loan and achieve park value" (the latter is correct).

**Steps to reproduce:**
1. Search for `OBJECTIVE_REPLAY_LOAN_AND_PARK_VALUE`, and notice that there are some files that contain this term.
2. Search for `OBJECTIVE_REPAY_LOAN_AND_PARK_VALUE`, and notice that there are no results.

**Problematic files found:**
https://github.com/OpenRCT2/OpenRCT2/blob/0fb307c12e531725db2d564a667a09325c939bb5/src/openrct2/scripting/ScScenario.hpp#L38
https://github.com/OpenRCT2/OpenRCT2/blob/2015acd4c0e345094847a9c6481171306277d32c/src/openrct2-ui/windows/EditorObjectiveOptions.cpp#L347
https://github.com/OpenRCT2/OpenRCT2/blob/987a5f488de76b5d3003917ed4ed178e41c2731e/src/openrct2/scenario/Scenario.cpp#L297
https://github.com/OpenRCT2/OpenRCT2/blob/fc2773d68f5c910cc95e97160b8bd5ff8cc86255/src/openrct2/scenario/Scenario.h#L346
https://github.com/OpenRCT2/OpenRCT2/blob/4ff412dfe155c32664273d1b098d62c026a74c96/distribution/openrct2.d.ts#L1488
The above is the first result in each of the files that I was able to find. Please use the find string in text function to find other occurrences of the string.

**Comment by duncanspumpkin** [comment]
Could you make a pr fixing this.

**Comment by maksimdrachov** [comment]
Hi, 
I'm new to opensource, could I get assigned this one as an exercise?

**Comment by tupaschoal** [comment]
We don't use assignments much, but you can do it for sure!
