### ISSUE TITLE
macOS Big Sur Icon

### ISSUE THREAD

**Issue by mrleblanc101** [OpenRCT2/OpenRCT2#13436]
**OS:** macOS
**Version:** 11.0.1

Hi, macOS Big Sur has a new design for icons.
I found the SVG of the original icon, and made this alternate version for Big Sur.
If you want I can open a PR and replace the `.icns` file with this one and generate assets for all resolutions.

**Screenshots / Video:**

![App Icons - @2x](https://user-images.githubusercontent.com/17392251/99870049-009c4300-2b9e-11eb-9089-fa0b1b69da0b.png)
<img width="601" alt="Capture d’écran, le 2020-11-21 à 02 17 06" src="https://user-images.githubusercontent.com/17392251/99870245-b4ea9900-2b9f-11eb-87ad-fd20f0b91aaa.png">

**Comment by Gymnasiast** [comment]
Nice!

>  If you want I can open a PR and replace the .icns file with this one and generate assets for all resolutions.

Sounds like a good idea to me. Would it be possible to use it for Big Sur only? Otherwise, it's okay to apply to all macOS builds.

Could you also commit the modified SVG to the repository?

**Comment by mrleblanc101** [comment]
It's actually not possible.
Apple recommend using the new icon style on every version in the Human Interface Guideline.
I'll open the PR and reference this issue.
I'll also add the Sketch File I used to generate the assets.
It's Apple own App Icon Template.

**Comment by mrleblanc101** [comment]
I'll probably need some help figuring everything out.
I don't want to override current file as I don't want to modify the Windows icon.
Not sure how everything works, but mac apps use `.icns` and not `.ico` and I don't see it in the repo.
So should I just create a new folder and commit my macOS assets ?
Also, are the 4x4, and 8x8 icon really necessary ?
Apple template does not generate them, I could add them if needed.

**Comment by mrleblanc101** [comment]
Also I don't know if there is an issue with the SVG, but the colors seems off when I open the SVG or export my new icon, does anybody has the original Sketch/Illustrator file for the icon ?

**Comment by pizza2004** [comment]
Looks to me like you'll just have to add those files and change the build script in Xcode to copy them instead.  Stick all those PNGs and the svg into [resources/logo](https://github.com/OpenRCT2/OpenRCT2/tree/develop/resources/logo) and then under the Build Phases in the Xcode project there's one called Setup AppIcon the just would need the file names changed to point at your new ones instead of the old ones.  You can upload the svg as icon_mac.svg to differentiate it.

**Comment by mrleblanc101** [comment]
I was finally able to fix the colors, Sketch and Adobe XD really don't like that SVG file.
Now I'm waiting on Xcode to install, I open the PR probably this weekend.
![icon_512x512@2x](https://user-images.githubusercontent.com/17392251/100309377-bb4e8b80-2f78-11eb-998e-dca64a90ed49.png)

**Comment by mrleblanc101** [comment]
Here's the PR

**Comment by JaydenIrwin** [comment]
Great job! <3
