### ISSUE TITLE
Creating a scenario from a won save game can only create scenarios that have already been won.

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#13465]
OS: Kubuntu Linux 20.04
Version: ??? Version info still not showing up on Ubuntu title screen (see #12909) updated as of this post
Commit/Build: ???

I'm creating a scenario based on a saved game, but the save file has already been won for its own scenario goals. The problem is that no matter what settings I try to use or what I try to modify in the save game file, the new scenario that's created is always already won from the start, even though the scenario goals clearly haven't been met.

I've asked for help elsewhere looking for a possible way to un-win the scenario as a workaround for this problem, but it seems like it shouldn't be a problem in the first place. Whatever flag is listing the saved game as 'already won', should be automatically removed as part of the process of making a new scenario based on it.

- [ ? ] Reproducible in RCT2 (vanilla)?
- [ no ] Specific to multiplayer?

**Steps to reproduce:**
1. Create a saved game.
2. In the cheats window, click 'Win Scenario'.
3. Save the game.
4: Exit to menu.
5: Create a scenario based on a saved game.
6: Create a new scenario based on the save from step 3.
7: Load the new scenario.
8: No matter what you set the new scenario's goals to, it's already won the moment you load it.

**Screenshots / Video:**

![Purgatoria 2020-11-26 22-02-44](https://user-images.githubusercontent.com/26573303/100417441-cf0bf780-3035-11eb-8113-3df71eda5555.png)
(Listing the insane goal in a separate issue.)

**Comment by Mar-Koeh** [comment]
I see your trouble. Workaround for now: Manipulate the save game status via Javascript-API prior to saving.

**Comment by ocalhoun6** [comment]
@Mar-Koeh 
I'm working on that ... but it's not very easy.
https://www.reddit.com/r/rct/comments/k1vr89/is_there_a_way_to_unwin_a_scenario_in_openrct2_im/gds7e8n/
Only partial success so far.
It turns out that the part that asks you to enter your name into the scenario is separate from the part that lists the scenario as won or not, and it's also inherited by any scenario based on this saved game. Still trying to figure out how to change that part.

**Comment by ocalhoun6** [comment]
For the reference of anyone experiencing the same problem, here's the workaround -- here's how to un-win a scenario:

1: Start OpenRCT2 from the command line. (I used linux, but I presume it works the same on windows command line.)
2: Open the scenario you want to un-win.
3: Switch back to the command line window without closing OpenRCT2. It should now be an RCT command line, using commands from the plugin API.
4: Use the command `scenario.status = "inProgress"` -- this un-wins the scenario.
5: Use the command `park.setFlag("scenarioCompleteNameInput", false)` -- this removes the prompt to enter your name into the high scores.
6: Switch back to OpenRCT2. The scenario should now be back to normal!

**Comment by ocalhoun6** [comment]
Does anybody know which file the code for the 'convert saved game to scenario' function is in? I've been learning some C++, and I'm sure I'd make a mess of it, but it might be interesting to try and fix this myself.

It *should* be as simple as setting the flags mentioned in the previous post on this issue to the proper values while creating the new scenario, right? Because nobody would _want_ to make a scenario that's already won as soon as you open it...

**Comment by Mar-Koeh** [comment]
@ocalhoun6 There is a string `STR_3343`. [StringIds.h](https://github.com/OpenRCT2/OpenRCT2/blob/bd18bce3a712fd99cd2e8bc01c30ca1e2f6a343e/src/openrct2/localisation/StringIds.h it is defined as `STR_CONVERT_SAVED_GAME_TO_SCENARIO`. In [TitleMenu.cpp](https://github.com/OpenRCT2/OpenRCT2/blob/e54dc7e4667b72c3082a2e9699d732a88ce789ce/src/openrct2-ui/windows/TitleMenu.cpp) it is linked to `ConvertSaveToScenario` which has the callback `ConvertSaveToScenarioCallback`, both in [Editor.cpp](https://github.com/OpenRCT2/OpenRCT2/blob/6b1141b5a2636f1459d178f2d689275525c8ea7f/src/openrct2/Editor.cpp). Maybe, from there you can find where the flags are loaded.
