### ISSUE TITLE
PPA for Ubuntu 20.10

### ISSUE THREAD

**Issue by ajhinz** [OpenRCT2/OpenRCT2#13468]
Are there any plans to update the PPA to work with Ubuntu 20.10?

https://launchpad.net/~openrct2/+archive/ubuntu/nightly

**Comment by Gymnasiast** [comment]
I have just modified both the `master` and `nightly` series to build for Bionic, Focal, Groovy and Hirsute. It will take a bit until builds pop up, so I'm keeping this open until then.

**Comment by Gymnasiast** [comment]
According to https://launchpad.net/~openrct2/+archive/ubuntu/nightly/+packages , the first package for Groovy has now been built.
