### ISSUE TITLE
Add 'return' button on tracked ride pre-built designs dialog

### ISSUE THREAD

**Issue by Chicoria95** [OpenRCT2/OpenRCT2#1346]
Suppose that after you picked a coaster type, and had a look at the available pre-built designs, you may not be satisfied with any of them, and unwilling to build the ride yourself. Or maybe you tried fitting some of them in your park with no success. 
Next thing you have to do is close that dialog, open the ride building one, and click the coaster tab. This occurs quite often when I'm playing, and gets quite repetitive. A return button that would take me immediately to the coaster type tab (or transport/water ride/gentle ride tab, accordingly) would be a subtle but, I reckon, desirable improvement in gameplay, as long as it's not too much trouble to implement, of course.

**Comment by MaikelS11** [comment]
I tried to find a good place for the button.. is this something?
![Return button preview](http://maikelstuivenberg.nl/projects/OpenRCT2/Back-button-preview.png)

**Comment by AaronVanGeffen** [comment]
Personally, I'd rather see it in the top-left corner. Spanning the width of the track list, for example?

**Comment by IntelOrca** [comment]
Can't the close button just take you back to the new ride window?

**Comment by Gymnasiast** [comment]
Hm, I'd prefer Aaron's idea.

**Comment by pizza2004** [comment]
I like what IntelOrca said.  It seems simple and logical.  I can see it possibly being an issue if people like to open things and then just close them for some reason though.

**Comment by Gymnasiast** [comment]
The reason why I prefer a separate button is that it makes the GUI more predictable. People expect a close button to close a window and not to open another.

**Comment by pizza2004** [comment]
I'll admit, I mostly just lurk in the shadows and watch this projects every move without saying much, so my first response to your response was, "Yes, yes, discuss things!"

Anyway, no, you're right, it should definitely be a separate button.  It's bad form for a close button to do something different on one window than on all the others.

**Comment by MaikelS11** [comment]
I agree with @Gymnasiast. You'll expect from a close button that it will close your window, not to open the previous one.

We can also place this previous button next to the close button, so you can choose if you want to close the window or reopen the previous.
![back-button-preview-2](https://cloud.githubusercontent.com/assets/13018117/8397198/4c7b539a-1dc3-11e5-89e1-349f2fd81c80.png)

**Comment by Gymnasiast** [comment]
I think that putting a button above the left column with just text ("Back to ride selection"), that has the width of the left column would be a lot easier, especially for less tech-savvy users.

(Buttons in the window's title bar, like the close button, are meant to influence that particular window, not for going back.)

**Comment by MaikelS11** [comment]
Something like this?
![back-button-preview-3](https://cloud.githubusercontent.com/assets/13018117/8397420/e973f6a0-1dca-11e5-943b-6f75e1da5b92.png)

**Comment by Gymnasiast** [comment]
Yes, exactly. :)

Two small things:
- It does need a bit more space between the button and the list (I would say, as much as the button is high)
- It should read "Select another ride" (you put a space too many)

**Comment by duncanspumpkin** [comment]
This has now been added.
