### ISSUE TITLE
Excitement rating for 'complete 5 coasters' goal getting corrupted to 19,668.80

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#13466]
OS: Kubuntu Linux 20.04
Version: ??? Version info still not showing up on Ubuntu title screen (see #12909) updated as of this post
Commit/Build: ???

I'm trying to make a scenario with the 'complete 5 coasters' goal, but when I set the target excitement rating to 8.00, the scenario is created with a goal of 19,668.80 instead.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Attempt to create a new scenario with the goal of completing 5 coasters.
2. Load the new scenario.

**Screenshots / Video:**
![Purgatoria 2020-11-26 22-02-44](https://user-images.githubusercontent.com/26573303/100417441-cf0bf780-3035-11eb-8113-3df71eda5555.png)
(Listing the way it's already won even though the goal hasn't been met as a separate issue.)

**Comment by Gymnasiast** [comment]
Can you verify this is not the same bug as https://github.com/OpenRCT2/OpenRCT2/issues/13292 ?

**Comment by James103** [comment]
@ocalhoun6 Have you tried running `openrct2 --version` and posting the results here?

**Comment by ocalhoun6** [comment]
@Gymnasiast 
Actually, yes it _does_ look very very similar to that bug.
The only slight difference is that it doesn't have to be a "Pay to enter park / Free rides" scenario? This scenario was a "Free park entry / Pay per ride" type and is still experiencing the issue.

@James103 
Tried that ... and this is what I get as a result:
>OpenRCT2,  ( on , DEBUG)
>Linux (x86-64)

**Comment by ocalhoun6** [comment]
I've done some further testing, and this bug only seems to affect the display in the scenario goals (in the park window). Everywhere else, it displays normally and _behaves_ normally.

Showing correctly in objective selection while simultaneously wrong in park window:
![Purgatoria 2020-11-29 00-21-59](https://user-images.githubusercontent.com/26573303/100837524-b597f080-3425-11eb-8b57-8d685dc82428.png)

Completed the scenario with coasters with 8+ excitement, despite park window still showing absurdly high goal:
![Purgatoria 2020-12-01 22-22-14](https://user-images.githubusercontent.com/26573303/100837635-cea0a180-3425-11eb-8ddb-97f17fa3119e.png)

So all it seems to affect is the display in the park window. (That said, it's still important. When new players are playing this scenario, they need to know what the goal is if they're going to build coasters that meet that goal.)

----------------------------

For further testing, can someone with a working vanilla installation try to open this scenario and see what vanilla says the goal is? That should tell us whether it's being stored incorrectly in the file somewhere, or if it's _only_ a bug in the code that displays the scenario goal.

[Purgatoria 2.zip](https://github.com/OpenRCT2/OpenRCT2/files/5627430/Purgatoria.2.zip)
(Change file extension back to .sc6)

**Comment by Gymnasiast** [comment]
Vanilla just says "file contains invalid data".
