### ISSUE TITLE
Circus Default Price is Too High

### ISSUE THREAD

**Issue by rpstester** [OpenRCT2/OpenRCT2#13473]
**OS:** Windows 10
**Version:** 0.3.2 develop (and release)
**Commit/Build:** 79c6b22

In a free-entrance scenario, the Circus defaults to $1.50.  
However, guests will immediately say that it costs too much.
This did not used to be the case in vanilla; peeps would have paid it for a few months at least.

Some options:
- Lower the default price of Circus to $1.
- Boost the guests' valuation of the Circus
- Rework whatever has changed with a guest's valuation of a ride

Reproducible in RCT2 (vanilla)? _no_
Specific to multiplayer? _no_

**Steps to reproduce:**
1. Open an empty park with free-entrance and Circus available (Sherwood Forest, Volcania, or Crazy Castle)
2. If necessary, research the Circus, build it and open it
3. See that guests will say that they won't pay that much to ride (along with it's not exciting enough)

**Comment by ddevrien** [comment]
I did some digging what changed the guest's valuation of a ride, it can probably be traced back to https://github.com/OpenRCT2/OpenRCT2/commit/29db1389ce5adb1299b4f93c156e46a84ce2a232

So, in the original game, you used to get away with charging $6. The max you could get away with now is $1.2 for the circus. Lowering the default price to $1.2 makes the most sense I think?
