### ISSUE TITLE
Increase number of simultaneous music tracks.

### ISSUE THREAD

**Issue by yayachiken** [OpenRCT2/OpenRCT2#1349]
When playing with a large viewport (maximum windows size on a 1920x1080 screen), the music volume emitting from rides does not appear to be reasonable.

For example I had an autoscooter and a merry-go-round on the map which played different music. Even though the merry-go-round was centered on screen, I could only hear the autoscooter currently sitting at the edge of the viewport.

In fact, I was unable to get the merry-go-round to play no matter how I moved the viewport around. I could only hear it if I clicked on the merry-go-round and clicked on the ride symbol in its ride window (to select the sounds from near the merry-go-round).
Also, if I shut down the autoscooter, the merry-go-round music would immediately start playing at maximum volume.

When I reduced the viewport to its original size the merry-go-round played fine when I moved it in the viewport, so did the autoscooter (it was not possible to have them both on screen at the same time with the smaller viewport).

I can provide a savegame if you want.

Expected behaviour would be to hear a reasonable mixture of all the sounds originating in the viewport. Maybe as if the sound were received in the center, so the sounds from farther towards the edges would fade out more?

**Comment by zsilencer** [comment]
this is because a max of 2 ride musics can be played at any time.

**Comment by yayachiken** [comment]
Strange. These two rides were the only ones in the entire park that played music, so this maximum should not be an issue?

**Comment by zsilencer** [comment]
Hmm can you provide a save file so I can check it out

**Comment by yayachiken** [comment]
No problem, I made a screen to show how to set the viewport: Here only the autoscooter music is playing, even though clearly the merry-go-round is way more centered. You can also push the autoscooter out of the screen and still it would play.

![openrct2-screen](https://cloud.githubusercontent.com/assets/88805/8162551/572ae624-137e-11e5-9da3-1e95f1451e68.png)

https://dl.dropboxusercontent.com/u/45111925/Sherwood%20Forest.sv6

(Could you recommend a no hassle filehoster? Just in case the bug doesn't get solved soon, and I accidentally delete the save-file from my dropbox...)

**Comment by zsilencer** [comment]
I see what is happening.  The circus is the 3rd ride that has music (even though you can't set it to play or not), so it is using up one of the 2 max music tracks.  Try closing the circus and seeing the two rides being able to play.

**Comment by IntelOrca** [comment]
I take it that this behaviour / bug is the same as the original game?

**Comment by trigger-death** [comment]
@yayachiken Try opening this save up in RCT2 and seeing if there's a difference.

**Comment by yayachiken** [comment]
@trigger-death Sorry, I can't. Vanilla RCT2 stubbornly refuses to run on my Linux box, even though OpenRCT2 runs under Wine perfectly... :(

**Comment by trigger-death** [comment]
Can you send us the save then?

**Comment by yayachiken** [comment]
See my comment above with the screen shot, I provided a link to the save file via Dropbox.

**Comment by trigger-death** [comment]
Yep this seems to be an original bug.

**Comment by zsilencer** [comment]
i wouldn't even call it a bug either, just a limitation, which can be lifted to any maximum you want but requires recompile.

**Comment by Gymnasiast** [comment]
@yayachiken : For me, RCT2 works, but only if I set Wine to use a virtual desktop.

**Comment by yayachiken** [comment]
I just noticed that this is probably the same issue as #669

**Comment by Umdlye** [comment]
Implemented by #9915
