### ISSUE TITLE
Switching to vehicles tab in ride window closes construction window.

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#13496]
OS: Kubuntu Linux 20.04
Version: ??? Version info still not showing up on Ubuntu title screen (see #12909) updated as of this post
Commit/Build: ???

If you're building a ride, open that ride's window, and then click on the vehicles tab, it closes the ride construction window (for no discernible reason). None of the other tabs does this, only the vehicles tab, and it happens regardless of what the previously selected tab was. Tested it out with several different tracked rides ... may also happen with flat rides (for example, by clicking on the ride in the rides list while the construction window is still open to place an entrance). If you right-click on the ride, construction can be resumed while the vehicles tab is still open ... it's just an annoying glitch to have the window you're working with unexpectedly disappear.

Steps to reproduce:
1: Begin to construct any tracked ride, place at least one track piece.
2: Click on one of the already-constructed pieces to open the ride window.
3: In the ride window, click on the vehicles tab (second from left)
4: Ride construction window disappears.

![Purgatoria 2020-12-01 00-26-27](https://user-images.githubusercontent.com/26573303/100721426-2979c080-3374-11eb-917a-a1babae0433b.png)

**Comment by tupaschoal** [comment]
This is due to #3200 and technically follows vanilla behaviour, is it straying from it?

**Comment by ocalhoun6** [comment]
Seems like the real issue in #3200 is that it causes miscalculations in the vehicles? I don't think anybody is going to be upset that their construction window didn't close.

But yeah ... sounds like it might be more complicated than I thought. It would take some bug-hunting to find out what those vehicle miscalculations are, what causes them, and how to solve them _without_ closing the construction window. (Maybe similar bugs existed in vanilla and they plastered over them by using this same solution -- closing the construction window if you open the vehicles tab?)

For now, closing the construction window is definitely preferable to having problems with vehicle calculations.

**Comment by tupaschoal** [comment]
Ok, thanks for the investigation
