### ISSUE TITLE
c++ odr error fedora within compile

### ISSUE THREAD

**Issue by h3o66** [OpenRCT2/OpenRCT2#13498]
**OS:** [Fedora 32-rawhide]
**Version:** [ 0.3.2]
**Commit/Build:** [relase 0.3.2]

With the current build options for fedora the build fail with `C++ One Definition Rule` errors:
Reference:
https://en.cppreference.com/w/cpp/language/definition

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. build on fedora with default `-Werror=odr`
2. get the follwoing error from the compiler:
```
/builddir/build/BUILD/OpenRCT2-0.3.2/src/openrct2-ui/windows/News.cpp:28:6: error: type 'WINDOW_NEWS_WIDGET_IDX' violates the C++ One Definition Rule [-Werror=odr]
   28 | enum WINDOW_NEWS_WIDGET_IDX {
      |      ^
/builddir/build/BUILD/OpenRCT2-0.3.2/src/openrct2-ui/windows/NewsOptions.cpp:57:6: note: an enum with different value name is defined in another translation unit
   57 | enum WINDOW_NEWS_WIDGET_IDX {
      |      ^
/builddir/build/BUILD/OpenRCT2-0.3.2/src/openrct2-ui/windows/News.cpp:32:5: note: name 'WIDX_SETTINGS' differs from name 'WIDX_TAB_CONTENT_PANEL' defined in another translation unit
   32 |     WIDX_SETTINGS,
      |     ^
/builddir/build/BUILD/OpenRCT2-0.3.2/src/openrct2-ui/windows/NewsOptions.cpp:61:5: note: mismatching definition
   61 |     WIDX_TAB_CONTENT_PANEL,
      |     ^
/builddir/build/BUILD/OpenRCT2-0.3.2/src/openrct2-ui/windows/ClearScenery.cpp:20:6: error: type 'WINDOW_CLEAR_SCENERY_WIDGET_IDX' violates the C++ One Definition Rule [-Werror=odr]
   20 | enum WINDOW_CLEAR_SCENERY_WIDGET_IDX {
      |      ^
/builddir/build/BUILD/OpenRCT2-0.3.2/src/openrct2-ui/windows/SceneryScatter.cpp:18:6: note: an enum with different value name is defined in another translation unit
   18 | enum WINDOW_CLEAR_SCENERY_WIDGET_IDX
      |      ^
/builddir/build/BUILD/OpenRCT2-0.3.2/src/openrct2-ui/windows/ClearScenery.cpp:27:5: note: name 'WIDX_SMALL_SCENERY' differs from name 'WIDX_DENSITY' defined in another translation unit
   27 |     WIDX_SMALL_SCENERY,
      |     ^
/builddir/build/BUILD/OpenRCT2-0.3.2/src/openrct2-ui/windows/SceneryScatter.cpp:26:5: note: mismatching definition
   26 |     WIDX_DENSITY,
      |     ^
/builddir/build/BUILD/OpenRCT2-0.3.2/src/openrct2-ui/windows/StaffList.cpp:77:6: error: type 'WINDOW_STAFF_LIST_WIDGET_IDX' violates the C++ One Definition Rule [-Werror=odr]
   77 | enum WINDOW_STAFF_LIST_WIDGET_IDX {
      |      ^
/builddir/build/BUILD/OpenRCT2-0.3.2/src/openrct2-ui/windows/Themes.cpp:68:6: note: an enum with different value name is defined in another translation unit
   68 | enum WINDOW_STAFF_LIST_WIDGET_IDX {
      |      ^
/builddir/build/BUILD/OpenRCT2-0.3.2/src/openrct2-ui/windows/StaffList.cpp:78:5: note: name 'WIDX_STAFF_LIST_BACKGROUND' differs from name 'WIDX_THEMES_BACKGROUND' defined in another translation unit
   78 |     WIDX_STAFF_LIST_BACKGROUND,
      |     ^
/builddir/build/BUILD/OpenRCT2-0.3.2/src/openrct2-ui/windows/Themes.cpp:69:5: note: mismatching definition
   69 |     WIDX_THEMES_BACKGROUND,
      |     ^
/builddir/build/BUILD/OpenRCT2-0.3.2/src/openrct2-ui/windows/LandRights.cpp:28:6: error: type 'WINDOW_WATER_WIDGET_IDX' violates the C++ One Definition Rule [-Werror=odr]
   28 | enum WINDOW_WATER_WIDGET_IDX {
      |      ^
/builddir/build/BUILD/OpenRCT2-0.3.2/src/openrct2-ui/windows/TitleCommandEditor.cpp:53:6: note: an enum with different value name is defined in another translation unit
   53 | enum WINDOW_WATER_WIDGET_IDX {
      |      ^
/builddir/build/BUILD/OpenRCT2-0.3.2/src/openrct2-ui/windows/LandRights.cpp:32:5: note: name 'WIDX_PREVIEW' differs from name 'WIDX_COMMAND' defined in another translation unit
   32 |     WIDX_PREVIEW,
      |     ^
/builddir/build/BUILD/OpenRCT2-0.3.2/src/openrct2-ui/windows/TitleCommandEditor.cpp:57:5: note: mismatching definition
   57 |     WIDX_COMMAND,
      |     ^
lto1: all warnings being treated as errors
lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
```

I patched for this the json lib for fedora to get it build at all:

build on copr:
https://copr.fedorainfracloud.org/coprs/birkch/openrct2/build/1808827/

The sourcecode was not modified nor the compiler options.

**Comment by csunday95** [comment]
I also ran into this issue when trying to build on Ubuntu; what would be the general opinion on using scoped enums with specified base types (uint32_t etc)? There already exists some nice function templates in src/util/Util.h for more succinctly working with them as bit flags, array indices etc.  In general such a refactor would look like:

1) determine all the enums that have conflicting member names across translation units
2) switch those enums to scoped enums 
3) wherever values from that enum were used as integral types, use the above mentioned functions from Util.h to perform compile time casting

With scoped enums, we can retain the names exactly as they are, as you can have multiple identical scoped enums as long as they exist in different translation units.

**Comment by tupaschoal** [comment]
We've been working on a project to use as much as we can of `enum class` for some months now: https://github.com/OpenRCT2/OpenRCT2/projects/14

It's almost complete, but I know that an issue or two might have been closed without fixing because we thought it wouldn't be good at the time. We might want to do another sweep in the code looking for plain `enums` and opening more issues on that milestone.

**Comment by csunday95** [comment]
Okay, sounds good! To maybe save a tiny bit of searching, the files in `openrct2ui/windows/` directory in particular have a few bare enums with overlapping names.

**Comment by alercah** [comment]
Also encountered this on Debian bullseye. Might be a clang vs gcc thing.

**Comment by alercah** [comment]
As one might hope, `-Wno-error=odr` suppresses this and lets the build finish.

**Comment by h3o66** [comment]
Build works with the latest version 0.3.5.1 now.
This works for till fedora 35 for now:
https://copr.fedorainfracloud.org/coprs/birkch/openrct2/

**Comment by tupaschoal** [comment]
Nice, thanks for the feedback!

Closing the issue, then, feel free to reopen if it breaks again
