### ISSUE TITLE
Bad formatting of chat messages

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#13517]
**OS:** Windows 10
**Version:** [e.g. 0.3.2] 0.3.2
**Build:** e8611169a5eed155c90f1cfd42231e2b65ad801f

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

Sorry that it is not english in the screenshot below,
All chat messages are broken, since the new-format-string branch is merged, I think.

Also, It breaks scenario objective's date in Korean.
Please aware me if there is something I should change in Korean translation.

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/10726524/101240417-b0db8100-3732-11eb-9b01-b4c6b0b13727.png)

Hydro Hills, the date is broken. The right one is October, 3 but it is displayed as June, 7.
![image](https://user-images.githubusercontent.com/10726524/101240519-df595c00-3732-11eb-8fcd-0df6e40a1c8f.png)

**Comment by IntelOrca** [comment]
The problem with the date is a separate issue and is because you swap the month and year around on `STR_2736`. I am still thinking what the best way to solve this is.

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/101244988-26544b00-374d-11eb-88ee-b1e9854179b5.png)

How about this?
(The result of ``rides`` command in console)

**Comment by IntelOrca** [comment]
@telk5093 thanks, have fixed that too

**Comment by telk5093** [comment]
@IntelOrca It seems that server/chat logs have the same issue:
![image](https://user-images.githubusercontent.com/10726524/101274017-f608bd00-37dd-11eb-8a77-78eeebee6114.png)

**Comment by IntelOrca** [comment]
@telk5093 do you want those removed. Wasn't sure whether they might be helpful or not as players can type their own formatting tags.

**Comment by telk5093** [comment]
I think it should be removed whether players can type or not.
