### ISSUE TITLE
Cut height in Cut-away view window is missing

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#13550]
**OS:** Windows 10
**Version:** 0.3.2
**Commit/Build:** f4bd903

As you can see the screenshot below.

**Step to reproduce:**
 1. Set Height Labels setting as ``Units``, not Real values
 2. Open Cut away window

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/10726524/101446605-eff21800-3966-11eb-9539-b24bd89de116.png)

**Comment by Gymnasiast** [comment]
Also doesn't work when selecting Imperial measurements (it just displays `ft` and nothing else).
