### ISSUE TITLE
When clicking on the "Start a new game" button, the game either crashes or incorrectly classifies all scenarios as "completed by ???"

### ISSUE THREAD

**Issue by MimoDX2** [OpenRCT2/OpenRCT2#13559]
**OS:** Linux - Ubuntu MATE 20.10
**Version:** 0.3.2
**Commit/Build:** the command openrct2 -v gives me: "OpenRCT2,  ( on , DEBUG) Linux (x86-64)", no version, commit or build is shown. I'm using the Ubuntu PPA on the latest version.

**Explanation of the issue:**
When clicking on the "Start a new game" button, the game sometimes crashes with a "Segmentation fault (core dumped)" error in the terminal. Other times, it works normally, except for the fact that every scenario is marked as completed by "???" with the exception of scenarios completed by me.

**Steps to reproduce:**
1. Boot game
2. Click on "Start a new game" button (Results either crash or incorrect information)

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/73262333/101556734-4af13280-399a-11eb-9d7c-f447460b4cac.png)

**Comment by MimoDX2** [comment]
Accidentally pressed enter and posted issue with incomplete information, now all information is provided and the issue is open again.

**Comment by duncanspumpkin** [comment]
use the latest version of develop and this issue should be resolved.
