### ISSUE TITLE
Fail to build on Pi4/Buster

### ISSUE THREAD

**Issue by Exarkuniv** [OpenRCT2/OpenRCT2#13562]
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

trying to build this on a Pi4 and i get all the way to make and i get a failure 

**Steps to reproduce:**
1. git clone -b master --depth 1 --recursive https://github.com/OpenRCT2/OpenRCT2.git
2. cd OpenRCT2
3 mkdir build && cd build
4 cmake ../ -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Ofast -DNDEBUG -mcpu=cortex-a72"
5 make -j4

**Dump file**
https://pastebin.com/VsDs7DUd

**Comment by janisozaur** [comment]
Are you sure your nlohmann-json is sufficiently new?

**Comment by Exarkuniv** [comment]
i believe so. i did to a new install from nlohmann-json github. how can i check that it did install

**Comment by janisozaur** [comment]
Check the defines for version in the json.hpp file. I expect it is new enough, as our CIs have the latest release in them. Perhaps it is too _new_? Can you check with 3.9.1, latest release?

**Comment by Exarkuniv** [comment]
ok i found 2 different versions 

``/usr/include/nlohmann/json.hpp``  is 3.5.0

``/usr/local/include/nlohmann/json.hpp `` is 3.9.1

and of course the ones that are included in OpenRTC2
