### ISSUE TITLE
Food is not consumed

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#13565]
**OS:** Windows 10
**Version:** 0.3.2
**Commit/Build:** f09b14e

Guests do not get up from benches if they have foods.
I've checked some shop/trash related commits on the history, so I guess that food is not consumed or not transformed into a trash.

**Steps to reproduce:**
1. Build a shop
2. Make peep buy it
3. Watch the peep

**Screenshots / Video:**
It is **May 12th, 1 Year**, see that guests bought beef noodles and seated on the benches. Look at the ``Iain C`` especially.
![image](https://user-images.githubusercontent.com/10726524/101759840-70f31000-3b1d-11eb-873d-32e546547c08.png)

It is ``June 19th, 2 Year``, ``Iain C`` is still on the bench
![image](https://user-images.githubusercontent.com/10726524/101759896-849e7680-3b1d-11eb-8082-b64f951fab56.png)
![image](https://user-images.githubusercontent.com/10726524/101760101-c2030400-3b1d-11eb-83f9-71aad5f61650.png)

**Comment by telk5093** [comment]
More detailed report has been updated at #13567

**Comment by duncanspumpkin** [comment]
I'll close this one as the other is more detailed
