### ISSUE TITLE
Load game / Quit to the menu are not working in multiplayer

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#13566]
**OS:** Windows 10
**Version:** 0.3.2
**Commit/Build:** f09b14e

There is no response when I click ``Load Game`` or ``Quit to the menu`` in the Disket menu in multiplayer game.
It works in singleplayer game.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**
1. Join any server
2. Try to click ``Load Game`` or ``Quit to the menu``
2. No response

**Screenshots / Video:**
![a](https://user-images.githubusercontent.com/10726524/101761251-41450780-3b1f-11eb-9193-581be86905bb.gif)

**Comment by Broxzier** [comment]
Bisected this, and found that the offending commit is f09b14ef2b9126d8b81b38b48d41289424497031 (https://github.com/OpenRCT2/OpenRCT2/pull/13548).

**Comment by tupaschoal** [comment]
> Bisected this, and found that the offending commit is [f09b14e](https://github.com/OpenRCT2/OpenRCT2/commit/f09b14ef2b9126d8b81b38b48d41289424497031) (#13548).

Oh noes
