### ISSUE TITLE
Opening the Options Menu kills performance

### ISSUE THREAD

**Issue by Krutonium** [OpenRCT2/OpenRCT2#13581]
**OS:** Arch Linux
**Version:** 0.3.2-198
**Commit/Build:** 9ef493198

Opening the Options Menu, regardless of Rendering option, cause frame rates to drop to nearly 1/10th of expected performance.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Observe FPS
2. Open Options Menu
3. Observe again

**Comment by janisozaur** [comment]
I recall this has been discussed long ago somewhere, isn't this a duplicate maybe?

**Comment by Gymnasiast** [comment]
I thought the same, but could not find it.

**Comment by rmnvgr** [comment]
The same is happening to me since updating to 0.3.3 (Flatpak, Fedora 33).

As soon as I open the Options window, the log is filled with this entry in loop until I close the window:

```
VERBOSE: executing "which zenity 2> /dev/null"...
```

**Comment by Gymnasiast** [comment]
I have pushed a possible fix here: https://github.com/Gymnasiast/OpenRCT2/tree/fix/13581

Could you test if that solves the issue for you?

**Comment by rmnvgr** [comment]
Yes, that fixed it for me 👍
