### ISSUE TITLE
Text gets messed up whenever it needs to print a lowercase L

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#13597]
**OS:** [Windows 10]
**Version:** [0.3.2]
**Commit/Build:** [5b24a9a]

Text gets messed up whenever it needs to print a lowercase L, see screenshots:

![image](https://user-images.githubusercontent.com/6469413/102335131-cc932280-3f8f-11eb-9d2a-31eed4126cc8.png)
![image](https://user-images.githubusercontent.com/6469413/102335146-d157d680-3f8f-11eb-83ba-e878d675b261.png)
![image](https://user-images.githubusercontent.com/6469413/102335153-d61c8a80-3f8f-11eb-85f7-e0ee0745ccf9.png)

**Comment by Gymnasiast** [comment]
It also outright crashes when I use OpenGL mode.

**Comment by Sadret** [comment]
![image](https://user-images.githubusercontent.com/15895532/102339385-5d203180-3f95-11eb-970d-d82dbca9d89d.png)
Some image buttons are broken and the map menu is not showing at all.
