### ISSUE TITLE
Zero under decimal is not displayed

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#13611]
**OS:** Windows 10
**Version:** 0.3.2
**Commit/Build:** 150f243

Zero under decimal is not displayed in Ratings, Money and so on.
I've also noticed that Ride's profit is displayed as ``$0.`` if it has no profit at all.

However I can't reproduce it always.
It does not matter whether it is multiplayer or not.

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/10726524/102714276-d1016780-4310-11eb-8796-84df596e46dc.png)

**Comment by csunday95** [comment]
I've investigated this a bit, and it appears that the Formatting.cpp code incorrectly handles small values for fixed point display, e.g. a Nausea rating of 7 should be rendered as 0.07, but is instead shown as 0.7 as above. Will submit a PR soon.
