### ISSUE TITLE
[Plugin] Add support for patrol areas to Staff

### ISSUE THREAD

**Issue by saeltz** [OpenRCT2/OpenRCT2#13620]
Hi there,

thanks for the great work on OpenRCT2!

I thought about writing a plugin that makes staff more intelligent by assigning patrol areas automatically. Maybe instead the wages are increased (to pay some imaginary middle-management).

Therefore, in the scripting support I'd need the possibility to
- get patrol area for staff members (`Staff.getPatrolArea()`)
- set patrol area for staff members (`Staff.setPatrolArea(coords)`)
- (optional) set wages for staff members (`Staff.setWage(money)`)
- (optional) set "visibility" of full bins to a high number (imagine "smart bins" that signal when they are full)

Unfortunately, I don't know C++ myself, so I'd be happy for someone to take this over.

**Comment by csunday95** [comment]
At a minimum, there's already existing implementation for a `staffsetpatrolarea` action binding, which could be used in a plugin as such:

```js
context.executeAction("staffsetpatrolarea", {
    peep: peep.id,
    loc: locationData
}, function (result) {...handle result...});
```

However, this action is one of those suffering from #13615 , so in addition to adding bindings for the other actions you mention, the implementation of this action will need to be completed. After I've added the missing implementation, I can also add your additional requested actions.

**Comment by saeltz** [comment]
@csunday95 , thanks!
Now that https://github.com/OpenRCT2/OpenRCT2/pull/13616 is merged, is https://github.com/OpenRCT2/OpenRCT2/issues/13615 done?
If so, what's left to do for this issue?

**Comment by csunday95** [comment]
Its actually closed rather than merged, as I completely screwed up a rebase somehow, and didn't realize it until I made a real mess. Planning on pushing an amended PR tonight, then adding a couple simple actions should be a pretty quick job.

**Comment by csunday95** [comment]
@saeltz I have created PR #13654 for getting the patrol area of a particular staff member. There is already an action accessible via the scripting engine for setting the patrol areas ( `StaffSetPatrolAreaAction` ). Adding an additional action for assigning wages should be simple, but I'm not quite sure what you mean by changing the visibility of the full bins.

**Comment by saeltz** [comment]
@csunday95, thanks for your work on this!
Forget about the bins. This is enough for a first version of the plugin.
