### ISSUE TITLE
No sound after opening OpenRCT2, works after reselecting audio device

### ISSUE THREAD

**Issue by sjoerddebruin** [OpenRCT2/OpenRCT2#1362]
Using Wine on OS X. This doesn't happen always.

**Comment by Gymnasiast** [comment]
Also happens using Wine on Ubuntu.

**Comment by Gymnasiast** [comment]
This seems to have gone in the meantime, at least on my system. Do you still get the bug?

**Comment by sjoerddebruin** [comment]
Seems fixed now.
