### ISSUE TITLE
Only show water rides on their own tab

### ISSUE THREAD

**Issue by sjoerddebruin** [OpenRCT2/OpenRCT2#1363]
It always annoyed me that some water rides also show up in the tab with gentle rides. Adding a option to hide them on other tabs would make the window with rides cleaner for some people. This could also be a setting.

**Comment by IntelOrca** [comment]
You can specify up to two ride categories. These are in the actual object files, yes you could hide the second category - but that might not always be the one the user wants hidden.

**Comment by Christipher** [comment]
also - some water rides are better off not being hidden from their categories (i.e. Digney Slides, Water Coaster, Splash Boats, and River Rapids) (and I'll candidly admit now that I can't make good toboggan-style rides of any sort (I always have a tendency for one to crash somehow...))
