### ISSUE TITLE
Refactor Sprite Compiler

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#13637]
The sprite compiler function `sprite build` is inefficient with the way it builds a new g2.dat file. As this function is run every time we compile on the CI's. It may reduce compile times by improving it. See this link for more info on the sprite compiler: https://github.com/OpenRCT2/OpenRCT2/wiki/Sprite-compiler

The problem with the sprite build is that it opens adds an image and finally saves the g2.dat file for each individual image. Instead it should add all of the images and then save. There is no reason for it to open the g2.dat file. This should just be a case of reordering the loop located at: https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/CmdlineSprite.cpp#L602

Have a look at the part before as well. I think there should only ultimately be one save for the whole function. Don't forget to test the result as its easy to forget (Self Doh! https://github.com/OpenRCT2/OpenRCT2/issues/13597)

**Comment by IntelOrca** [comment]
The output g2.dat file should always be the same each run unless the images are changed or re-ordered so we can have a simple checksum test to ensure g2.dat is created correctly.

**Comment by csunday95** [comment]
I can take a look at this if somebody isn't planning to already

**Comment by duncanspumpkin** [comment]
Feel free

**Comment by csunday95** [comment]
are there any existing unit tests I'm not seeing? or should I generate some new ones

**Comment by duncanspumpkin** [comment]
Sure generate some. You could probably checksum the result it should be deterministic. We pretty rarely add new sprites. Have a look at how the g2.dat is generated on the ci.
