### ISSUE TITLE
Freezing when hovering over ride type in Select Objects

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#13645]
**OS:** Windows 10
**Version:** 0.3.2 using software render
**Commit/Build:** 9901f9b from issue #13613 

When using the object in this repository https://github.com/OpenRCT2/objects/pull/135 the game freezes for a moment when hovering over the object in the Select Objects list. This can make it hard to click on since the mouse has a tendency to jump over it. Once the object is selected, I have no freezing issues using the object. This occurs in both uncompressed and .parkobj form. I use a symlink (Junction in windows parlance) from the objects folder to the folder the object is contained in.

**Comment by X123M3-256** [comment]
I have also experienced this issue when testing JSON objects.

**Comment by spacek531** [comment]
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/15547
