### ISSUE TITLE
Game crashes after a while

### ISSUE THREAD

**Issue by JappyNE** [OpenRCT2/OpenRCT2#13641]
System: Windows 10
Version: 0.3.2
Commit: 17fe4bd

![Error](https://user-images.githubusercontent.com/40169350/103035624-005de180-4568-11eb-9e02-f53dcc05af3d.PNG)

[SFWoD.zip](https://github.com/OpenRCT2/OpenRCT2/files/5737064/SFWoD.zip)

**Comment by James103** [comment]
Are you able to reproduce this crash? If so, how?

**Comment by duncanspumpkin** [comment]
did you upload the crash?

**Comment by JappyNE** [comment]
> Are you able to reproduce this crash? If so, how?

Reproduce? Well it keeps happening when opening the save, that's as far as I got?



> did you upload the crash?

I added the ZIP with the dump file and save, that what you mean?

**Comment by James103** [comment]
Make sure to read the following text:
> We would like to upload the crash dump for automated analysis, do you agree?

Make sure to answer Yes (Ja) to the above question.

**Comment by JappyNE** [comment]
I did that when the crash pop-up came up, but then it told me it couldn't do it and wanted me to upload it manually.

**Comment by Gymnasiast** [comment]
#13642 :-)
