### ISSUE TITLE
Cut-away view shows 6,551.1 ft when going below 0 ft

### ISSUE THREAD

**Issue by andrewsarnold** [OpenRCT2/OpenRCT2#13644]
**OS:** Windows 10
**Version:** 0.3.2-252-gf9e90ed84
**Commit/Build:** f9e90ed

When selecting a cut-away height less than 0 ft, the displayed value underflows and shows 6,551.1 ft (then 6,548.6 ft, then 6,546.1 ft, etc.)

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open cut-away view
2. Ensure the display is set to distance instead of units
3. Set the slider / value to less than 0.0 ft

**Screenshots / Video:**

![Screenshot](https://user-images.githubusercontent.com/5436387/103045026-e2d14d80-4550-11eb-895a-a2c6c0f11011.png)

**Comment by andrewsarnold** [comment]
Possibly related: The same thing seems to be happening to the temperature readout.

![Temp](https://cdn.discordapp.com/attachments/691735032531779684/791676704183025674/unknown.png)

**Comment by James103** [comment]
@andrewsarnold Can you try looking at the numbers at the bottom of the ride altitude graph? If you see something like "65533 m", "65526 m", etc, then this may be related to #13102.

**Comment by andrewsarnold** [comment]
Yep, that is underflowing for me as well. The altitude values on the track itself are correct, though (-5ft, -10ft, etc.).

![image](https://user-images.githubusercontent.com/5436387/103096711-e3122d00-45d2-11eb-88fe-e50bd717f219.png)
