### ISSUE TITLE
System libdiscord RPC

### ISSUE THREAD

**Issue by Mailaender** [OpenRCT2/OpenRCT2#13650]
It would be great if the cmake system could detect https://build.opensuse.org/package/show/games/discord-rpc instead of trying to download stuff from the internet, which is not allowed in such build environments.

**Comment by janisozaur** [comment]
I don't think we're downloading anything from the internet for discord, at least the build system doesn't. It detects discord-rpc which is already present. That still sounds like a nice addition to detect the system one, but given discord-rpc was implemented back in the day when it was still supported and there weren't ready packages, I think this will depend on a PR by someone from outside of the team. Would you like to contribute such code @Mailaender ?

**Comment by Mailaender** [comment]
It seems you currently rely on a manually patched version:
https://github.com/OpenRCT2/OpenRCT2/blob/c36ec5c5cebe2093396256259485d87d31529468/scripts/linux/install.sh#L102

Looks like that needs to get upstreamed first.

**Comment by Mailaender** [comment]
Nevermind, you already did https://github.com/discord/discord-rpc/pull/179 and it is integrated in version 3.4.0.
