### ISSUE TITLE
No Music anywhere in game, css music files are present.

### ISSUE THREAD

**Issue by ioogithub** [OpenRCT2/OpenRCT2#13660]
**OS:** KDE Neon 5.20.3
**Version:** OpenRTC2, v0.3.2
**Commit/Build:**  cea5fab on HEAD

There is no music in the game, either in the menu screen or on the rides. I have verified that the music slider is all the way to the right in options.

The /data folder contains css3 - css46 and the files are playable with VLC.

**Steps to reproduce:**
1. Open RTC2
2. Listen for Music

**Comment by James103** [comment]
Firstly, you should be spelling "OpenRCT2" as "OpenRCT2", not "OpenRTC2". Secondly, did you actually make sure that you copied your RCT2 installation correctly and made sure that all of the files are in the correct spots?

**Comment by Gymnasiast** [comment]
What is the extension of the CSS3 - CSS46 files? Is it .ogg, by any chance? Also, you should have CSS1.DAT and CSS2.DAT.

I suspect you might have used RCT Classic as an asset source, but if you answer above question, I can tell for sure.

**Comment by Gymnasiast** [comment]
Since OP has not answer for 6 months, considering this answered.
