### ISSUE TITLE
Turning off hardware display freezes game

### ISSUE THREAD

**Issue by sjoerddebruin** [OpenRCT2/OpenRCT2#1373]
Sound keeps playing but you're unable to play anymore. No error is shown.

**Comment by Gymnasiast** [comment]
Cannot reproduce this on Ubuntu with OpenRCT2 running through Wine. Might be just an OS X issue.

**Comment by Phasedetect** [comment]
This happens to me as well, also on OSX. It doesn't crash the game for me, the graphics just freeze until I check the box again.

**Comment by SlipperyPete** [comment]
On window's, same as Phasdetect, Graphics freeze up if I click the box to untick it, resolves when i click the box again.

**Comment by sjoerddebruin** [comment]
Also not working on my Windows installation.

**Comment by Gymnasiast** [comment]
Might be a hardware or driver issue. What are the specifications of your OS X computer and Windows computer (if that's a different one)?

**Comment by sjoerddebruin** [comment]
I think I have this iMac: http://www.everymac.com/systems/apple/imac/specs/imac-core-i7-2.93-27-inch-aluminum-mid-2010-specs.html

My parents PC (where I'm working on atm) contains this:
![naamloos2](https://cloud.githubusercontent.com/assets/5605979/8363914/a4d8fee0-1b82-11e5-9fd9-59a03688a005.png)

**Comment by Phasedetect** [comment]
MacBookPro9,1, Running Yosemite.

**Comment by Phasedetect** [comment]
Could it be the NVIDIA graphics? We have that in common...

**Comment by Gymnasiast** [comment]
I'm not sure. I have NVIDIA hardware and it works for me. And @sjoerddebruin 's iMac has AMD graphics and _is_ affected.

**Comment by Phasedetect** [comment]
Would an in-depth debug from either of us help? I don't have a debugger set up as per [the wiki](https://github.com/OpenRCT2/OpenRCT2/wiki/Debugging-OpenRCT2-on-OSX) but I could to try to get it going.

**Comment by Gymnasiast** [comment]
Is this still happening?

**Comment by janisozaur** [comment]
We've changed Linux & OS X to require a restart before this change gets into effect – we only apply it when initially creating the window. @IntelOrca rejected this for Windows. See https://github.com/OpenRCT2/OpenRCT2/pull/2038

**Comment by sjoerddebruin** [comment]
Not sure if this is still happening. I used to run OpenRCT2 inside Wine, but now I use the version for OS X.

**Comment by Gymnasiast** [comment]
Wine is not a supported configuration anymore. If it works on Windows and OS X, using the versions intended for those OS's, this bug is solved.

**Comment by sjoerddebruin** [comment]
I'm pretty sure this is fixed now, please reopen if someone encounters it again.
