### ISSUE TITLE
Refactor window to class: About

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#13748]
See #13737 for more details.

**Comment by kimjcalvin** [comment]
Hey @IntelOrca  anything to be aware of before I start this?

**Comment by IntelOrca** [comment]
Nope, this should be a straight forward window I believe.

**Comment by melsonGit** [comment]
Does this still need to be worked on? If so, I'll happily have a crack at it.

**Comment by Broxzier** [comment]
@melsonGit We haven't had any update from @kimjcalvin for 10 months, so it's safe to say you can work on this.

**Comment by duncanspumpkin** [comment]
@melsonGit just to warn you I'm about to modify the about.cpp file suggest holding off until #15956 is merged unless you have already implemented it.

**Comment by vkhashimoto** [comment]
Hey @melsonGit, are you currently working on this?

**Comment by duncanspumpkin** [comment]
@vkhashimoto I've not seen any PR submitted so feel free to implement it.

**Comment by melsonGit** [comment]
> Hey @melsonGit, are you currently working on this?

> @vkhashimoto I've not seen any PR submitted so feel free to implement it.

Made little to no progress, spent more time getting around the code space, plus life got in the way. Apologies for not updating.

**Comment by vkhashimoto** [comment]
> Made little to no progress, spent more time getting around the code space, plus life got in the way. Apologies for not updating.

No problems for me, if you want to keep the task, let us know and I'll get another task.

**Comment by melsonGit** [comment]
> > Made little to no progress, spent more time getting around the code space, plus life got in the way. Apologies for not updating.
> 
> No problems for me, if you want to keep the task, let us know and I'll get another task.

It's all yours, I currently don't have much free time to implement anything.
