### ISSUE TITLE
Coloring vehicles in a train not always possible

### ISSUE THREAD

**Issue by EmielRCT** [OpenRCT2/OpenRCT2#13746]
When making a train of vehicles that should usually not be in a train (for example Steeplechase vehicles, Virginia Reel Tubs or 6-seater Bobsleighs) using the 'disable vehicle limits' cheat you can not change the colors per car, only per train. 

It would be a useful fix if you could change the colors per vehicle, just like the vehicles that can regularly be in a train have. 

<img width="729" alt="1" src="https://user-images.githubusercontent.com/64599015/104123575-4084d880-534c-11eb-8dd1-a90cf114e94f.png">

**Comment by sjoerddebruin** [comment]
Seems to work properly now, maybe it was fixed with #22703.

**Comment by tupaschoal** [comment]
Dunno, as far as I tested it was fixed a while ago
