### ISSUE TITLE
Guests and staff get stuck on edges of path or stalls

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#13755]
**OS:** Windows 10
**Version:** 0.3.2
**Commit/Build:** 60d1e94

Guests and staff now have a high chance of getting trapped on the edges of footpaths, at the entrances of stalls, or sometimes even while exiting rides. Attached below is a zip file with the scenario and save game attached. This bug can make scenarios much harder or sometimes even outright impossible to complete.

**Steps to reproduce:**
1. Open up the attached save file (the scenario it is assigned to is also available in the zip file)
2. Let it play for a few seconds or minutes
3. You will see guests and staff members stuck in place, mainly on edges of the footpath or by stall entrances. Some of them are also stuck in place off the paths.

**Screenshots / Video:**
![Test Park 2021-01-10 14-37-46](https://user-images.githubusercontent.com/61885939/104137579-c2780000-5352-11eb-92a4-709a2229755e.png)
The first picture has guests stuck at the edges of footpaths or stall entrances, sometimes even getting stuck on tiles of land that don't have a footpath in them. Closing the stalls will free the guests.
![Test Park 2021-01-10 14-40-18](https://user-images.githubusercontent.com/61885939/104137581-c4da5a00-5352-11eb-99ca-ae5f662740c5.png)
The second picture has guests stuck inside the observation tower's station. They can be moved with the pincer tool.

**Save game:**
[pathfinding bugs.zip](https://github.com/OpenRCT2/OpenRCT2/files/5793437/pathfinding.bugs.zip)

**Comment by duncanspumpkin** [comment]
https://github.com/OpenRCT2/OpenRCT2/pull/13698 caused this. Will cause crashes/corruption if fast forward is used. Fix is modifying context.cpp with the following.
```
            if (_variableFrame != useVariableFrame)
            {
                _lastTick = 0;
                _variableFrame = useVariableFrame;
                auto& tweener = EntityTweener::Get();
                tweener.Restore();
                tweener.Reset();
            }
 ```
