### ISSUE TITLE
Cheat menu's No Money Error

### ISSUE THREAD

**Issue by CamdenShadowWolf** [OpenRCT2/OpenRCT2#13758]
**OS:** Windows 10
**Commit/Build:** v0.3.2-373-ge2021fcbc

Looks like a routine fix; the Cheat Menu's "No Money" option is out of wack.
![image](https://user-images.githubusercontent.com/77296291/104225816-df750780-5414-11eb-9601-765b051774fb.png)
![image](https://user-images.githubusercontent.com/77296291/104225840-e865d900-5414-11eb-8968-898273eabe5c.png)

**Comment by Gymnasiast** [comment]
Took me too long to see, but the tick in the box is missing.

Also: the appropriate tab is not selected.

@IntelOrca
