### ISSUE TITLE
Refactor window to class: Changelog

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#13765]
See #13737 for more details.

**Comment by NBurley93** [comment]
I'm working on this one. Making good progress, but held up a bit when trying to define a window personality, is there an API in the base window class that allows us to define class members before OnOpen() is called?

**Comment by IntelOrca** [comment]
Now sure what you mean by define class members.

**Comment by NBurley93** [comment]
What I mean is that I currently pass the personality value for the changelog window via a static variable that is changed whenever `window_changelog_open` is called, but I want to see if there's a better way of passing that value to the window when OnOpen is called. Though looking at the code, this might not be possible.

**Comment by IntelOrca** [comment]
I understand now.

Yeah, you can not pass arguments to the new window during creation.

For the guest list window, I call a method after creation to change the view of the window:
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2-ui/windows/GuestList.cpp#L970

So you could call a method called SetPersonality(...) after creating it.
