### ISSUE TITLE
Pathfinding error

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#1377]
When a guest, coming from the bottom right corner, wants to leave the park, you would expect him to go straight on, towards the park exit. However, every guest approaching the light brown path tile from the bottom right corner seems only be able to turn left, making them lost and unhappy. When I remove the red path tile, pathfinding works correctly and guests wanting to leave the park walk straight towards the park exit.

The issue is also in vanilla RCT2.

![scr5](https://cloud.githubusercontent.com/assets/1478678/8212021/b306b71a-1519-11e5-9510-3159a6a2eb4f.png)

The save is here:
https://www.dropbox.com/s/tbr2fszyrqy9clr/Europa%20-%20Europees%20Cultureel%20Fes.sv6?dl=0

**Comment by IntelOrca** [comment]
Interesting, I would expect them to turn right if not straight on.

**Comment by Nubbie** [comment]
I wonder if anything has to do with the original 'Death Trap' bug too
Especially when they are leaving the park
#3261

**Comment by Gymnasiast** [comment]
This also looks solved by #4221 :+1:
