### ISSUE TITLE
Refactor window to class: Multiplayer

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#13782]
See #13737 for more details.

**Comment by dizzyj** [comment]
I am new to open source projects, but I would like to get started on this.

**Comment by tupaschoal** [comment]
Sure, give it a go. Let us know on discord or here if you need help!

**Comment by tupaschoal** [comment]
I've started working on this one, since I didn't see any branch on your repor @dizzyj and there hasn't been any activity for the past month.
