### ISSUE TITLE
Refactor window to class: MusicCredits

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#13783]
See #13737 for more details.

**Comment by thamara** [comment]
It looks like MusicCredits was deleted. :)

**Comment by thamara** [comment]
Revision that removed the file: https://github.com/OpenRCT2/OpenRCT2/commit/ab186128825a2ca0ffad22a1f7c7a2a922d3b96c

**Comment by tupaschoal** [comment]
Indeed, thanks!

**Comment by karst** [comment]
I imagine that these were moved to parkobj equivalents with the introduction of ridemusic objects. 
The trivia is currently only viewable in the object selector, though it would be nice to have these visible in the the music selction screen (see #17385 for my mockup for that)
