### ISSUE TITLE
Refactor window to class: Ride

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#13795]
See #13737 for more details.

**Comment by tupaschoal** [comment]
Branch of `develop`, we rarely branch off from the `master` (which I think is what you meant from `releases`?)

**Comment by leoleotte** [comment]
I'm going to take this one.

**Comment by tupaschoal** [comment]
Up for grabs again

**Comment by toadkarter** [comment]
I can have a go at this one too.

**Comment by duncanspumpkin** [comment]
okay good luck. This is very complex.
