### ISSUE TITLE
Refactor window to class: Research

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#13794]
See #13737 for more details.

**Comment by HaNaK0** [comment]
I'm starting work on this

**Comment by duncanspumpkin** [comment]
Good luck

**Comment by lalip** [comment]
The PR that closed this involves #13769 instead

**Comment by cheekerz** [comment]
I have picked this up. I had a question regarding conventions. Research.cpp methods mostly have comments on them that look like they reference the original RCT2 code (see below). When refactoring and changing these methods, do we want to try to preserve the comments?

`/**
 *
 *  rct2: 0x006B6B38
 */
static void WindowResearchDevelopmentMouseup(WindowBase* w, WidgetIndex widgetIndex)`
