### ISSUE TITLE
Refactor window to class: TileInspector

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#13808]
See #13737 for more details.

**Comment by zuczek4793** [comment]
I'd like to do this task (unless it is about to be removed?)

**Comment by IntelOrca** [comment]
@zuczek4793 you are welcome to do this one

**Comment by Broxzier** [comment]
@zuczek4793 If there is anything that isn't clear, shoot me a message on Discord.

**Comment by tupaschoal** [comment]
Moved back to TODO, since there was no progress reported.

**Comment by zuczek4793** [comment]
Last I heard, changes to this were merged not too long ago

    On Wednesday, October 12, 2022 at 07:25:04 AM CDT, Tulio Leao ***@***.***> wrote:  
 
 


Moved back to TODO, since there was no progress reported.

**Comment by tupaschoal** [comment]
Ah, thank @zuczek4793 , I just trusted the PR would have mentioned this issue, but didn't check, thanks :)
