### ISSUE TITLE
Refactor window to class: ShortcutKeys

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#13804]
See #13737 for more details.

**Comment by nparshook** [comment]
Based off of [this](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2-ui/windows/ShortcutKeys.cpp#L156) I think this ticket has already been completed. Likewise for [#13803](https://github.com/OpenRCT2/OpenRCT2/issues/13803), based off of the code [here.](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2-ui/windows/ShortcutKeys.cpp#L67)

**Comment by Broxzier** [comment]
Yup, should've been closed when https://github.com/OpenRCT2/OpenRCT2/pull/13848 got merged.
