### ISSUE TITLE
Refactor window to class: Water

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#13815]
See #13737 for more details.

**Comment by ankushduacodes** [comment]
Hi @IntelOrca, I am new to the repo and new to C++. I know basic OOP constructs like classes, Could you guide me through this issue. I am very enthusiastic to be part of OpenRCT2 and to learn intermediate C++ along with these type of contributions.

Thank you!..

**Comment by IntelOrca** [comment]
Have a look at the changes in the following pull requests: #13756 and #13819
These are good examples to copy when doing the water window.

**Comment by sstream17** [comment]
I just started browsing the good first issue label and came across this issue. It looks like the work has been finished in #13974

**Comment by IntelOrca** [comment]
@sstream17 you're right, thanks for notifying us
