### ISSUE TITLE
Refactor window to class: TrackDesignPlace

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#13811]
See #13737 for more details.

**Comment by 94794** [comment]
Started working on it. Got stuck at `OnOpen()` method as the `WindowTrackPlaceOpen(const track_design_file_ref* tdFileRef)` needs the **_tdFileRef_** parameter for `_trackDesign = TrackDesignImport(tdFileRef->path)`.

37478a24ae24fb87c0ea233036501cc24f5a4a2e is what I've done until now.

How shoud I do it?

**Comment by tupaschoal** [comment]
Done by https://github.com/OpenRCT2/OpenRCT2/pull/16669
