### ISSUE TITLE
Game crash when spamming explode

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#1382]
You can aggravate it by using this map

![crash sample](https://cloud.githubusercontent.com/assets/3945538/8219974/23a5b62c-151c-11e5-804f-ae294c146cb7.png)

(It's actually a SV6)

Click Washroom Max, wait 5 seconds, and spam the explode button. The game should crash shortly thereafter.

**Comment by Gymnasiast** [comment]
Is this still happening?

**Comment by PFCKrutonium** [comment]
It does indeed seem to be fixed now.
