### ISSUE TITLE
Certain sounds play at max volume, irrespective of sound volume

### ISSUE THREAD

**Issue by rctdude2** [OpenRCT2/OpenRCT2#1384]
The following sounds are all playing at max volume and are ignoring the sound volume in options:
- Peep laughing
- Cash sounds
- Launched freefall launch sound
- Water splash
- Puking/coughing sound
- Break engage/release sound

**Comment by IntelOrca** [comment]
These are sounds that are triggered by original code that haven't been implemented in OpenRCT2 yet.
