### ISSUE TITLE
Separating Booster and SpinningControlToggle OpenRCT2-side

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#13845]
Right now, boosters and spinning control toggles exist as a single piece that has different behavior based on ride type. With the recent change to make TrackElement.trackType a 16 bit integer, it is possible to start adding new pieces OpenRCT2-side.

A flag can be added to the RTD to import spinning control toggle pieces and booster pieces as separate trackTypes and export them as the same trackType. This allows the myriad of checks made by OpenRCT2 to separate the behaviors of the same piece to be simplified.

The only potential issue is when using cheats users may assume they can use spinning control toggles and boosters on the same ride since they will no longer be the same piece with different behavior (after importing from SV6), although I have never heard of anyone asking for both to be present on one ride.

**Comment by Gymnasiast** [comment]
This is something that I planned, but it takes a bit more work. You need to make sure that a track_type_t is used throughout. Currently there are still lots of places that use uint8_t.

**Comment by spacek531** [comment]
I started a branch off #13825 to see what it's like and a bit more work is a bit of an understatement, I think.

**Comment by spacek531** [comment]
I just discovered the vehicle track_type/track_direction union. I tried to separate this union but failed miserably. Until it's separated or the value is changed from 16 bit to 32 bit, track types will be limited to 14 bits (for a total of 16384 unique track types)

**Comment by spacek531** [comment]
The PR was forked from another branch with an open PR, which was a mistake, and grew considerably in lines changed due to a lot of formatting changes which were unnecessary. I'm going to start over and force push over the branch once I'm satisfied with the new changes.

**Comment by spacek531** [comment]
Should be obvious - this PR is in reference to this issue https://github.com/OpenRCT2/OpenRCT2/pull/13857
