### ISSUE TITLE
When i try to open the game, it crashes

### ISSUE THREAD

**Issue by LopesdeMirandaa** [OpenRCT2/OpenRCT2#1386]
I try to open the openrct2.exe but it appears a command box saying that it cannot finf G1.exe
![it could](https://cloud.githubusercontent.com/assets/12944726/8222239/b67da91a-153e-11e5-8a3d-bdc8f7b62dcf.png)

**Comment by LopesdeMirandaa** [comment]
Does it work with Triple Thrill Pack? If it doenst i know what's the issue.

**Comment by PFCKrutonium** [comment]
Use this: https://openrct.net/download

**Comment by rd3k** [comment]
Please refer to these instructions rather than attempting to run openrct2.exe: https://github.com/IntelOrca/OpenRCT2#2-downloading-the-game--building-the-source-code

**Comment by PFCKrutonium** [comment]
@rd3k if I am not mistaken, he is using https://www.youtube.com/watch?v=s3k2rULhrEI as reference, which is why I suggested what I did.

**Comment by IntelOrca** [comment]
Looks like you download the source code zip from GitHub. Try the launcher from https://openrct.net/download.
