### ISSUE TITLE
crashing during loading a save game

### ISSUE THREAD

**Issue by TyandorX** [OpenRCT2/OpenRCT2#13860]
When I try to open any savegame it crashes. Scenarios work for a short time.
See log below (edit, changed it to a Wetransfer):

https://we.tl/t-gZvXoJveDu

**Comment by duncanspumpkin** [comment]
Did you upload the dump? You have deleted all of the form please readd all of the information that you have not provided.

**Comment by TyandorX** [comment]
> 
> 
> Did you upload the dump? You have deleted all of the form please readd all of the information that you have not provided.

Uploaded it, please let me know if I'm missing something. I only have very basic understanding of programming.

**Comment by Gymnasiast** [comment]
When you create an issue here, you get a form to fill in. You just deleted the whole form. It is there for a reason. Please restore it.

**Comment by TyandorX** [comment]
Problem was solved by removing one plug-in is seems, so this issue can be closed. Have another problem with a ride that crashes the game when trying to open it, but I'll make a new issue for that.

**Comment by duncanspumpkin** [comment]
What plugin was it?

**Comment by TyandorX** [comment]
It was Stuffcounter.

btw on the other issue, it is not creating a dump, mainly because it just 'hangs' I think. I have to alt-F4 / ctrlaltdel. For some reason I can open the ride on my laptop without crashing. It is not a recent issue though.
