### ISSUE TITLE
My OpenRCT2 crashed

### ISSUE THREAD

**Issue by zacharyhub** [OpenRCT2/OpenRCT2#13885]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.3.2]
**Commit/Build:** [e.g. 426e106]

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**
[c43a2739-7d5c-4ff6-826b-eb7586566ad9.sv6.gz](https://github.com/OpenRCT2/OpenRCT2/files/5845382/c43a2739-7d5c-4ff6-826b-eb7586566ad9.sv6.gz)

**Screenshots / Video:**
![Unnamed park  121-00-20 16-27-33](https://user-images.githubusercontent.com/8335233/105243382-f9ad9480-5b3c-11eb-8dde-937d7e152f4b.png)

**Save game:**

**Comment by janisozaur** [comment]
Outdated build, no dump
