### ISSUE TITLE
Backtick looks like quotation mark

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#13889]
**OS:** GNU/Linux
**Version:** 0.3.1 (develop)
**Commit/Build:** 3de233c79

- [ ] Reproducible in RCT2 (vanilla)? I don't know.
- [ ] Specific to multiplayer? No.

**Steps to reproduce:**
1. Open a window in which you can enter text, e.g. editing the name of a ride
2. Type in the backtick character (ASCII 0x60)

The backtick will look like a opening double quotation mark instead of a backtick.

**Comment by Gymnasiast** [comment]
That's why we asked the translators to replace them, so we can make the backtick look like an actual backtick.

See also https://github.com/OpenRCT2/OpenRCT2/issues/13318 .
