### ISSUE TITLE
Gibberish under "current in development"

### ISSUE THREAD

**Issue by sjoerddebruin** [OpenRCT2/OpenRCT2#1388]
![fe2bd832ff7b7a53c7a3420872898260](https://cloud.githubusercontent.com/assets/5605979/8228674/ed63c866-15b0-11e5-8328-541a68fb0aff.png)

**Comment by duncanspumpkin** [comment]
Is this happening on all parks? Can you provide a save? Which version are you running 0.0.2 pre release or develop?

**Comment by sjoerddebruin** [comment]
Hm, I can't replicate it anymore. I'm running the develop build, playing Millennium Mines. It was the Looping Roller Coaster, not sure what happened.

**Comment by Gymnasiast** [comment]
It seems to have to do with rides that don't have the RIDE_ENTRY_FLAG_SEPARATE_RIDE or RIDE_ENTRY_FLAG_SEPARATE_RIDE_NAME set, like the Wooden Roller Coaster trains.
