### ISSUE TITLE
OpenRCT2 crashed while opened Scenery editor

### ISSUE THREAD

**Issue by zacharyhub** [OpenRCT2/OpenRCT2#13884]
![OpenRCT2 crashed](https://user-images.githubusercontent.com/8335233/105231632-2d84bc00-5b35-11eb-9665-21cc1473cc6e.PNG)
My OpenRCT2 just crashed.

**Comment by James103** [comment]
Did you upload the dump? If so, can you link it here? (It may be in a separate issue)

**Comment by zacharyhub** [comment]
> Did you upload the dump? If so, can you link it here? (It may be in a separate issue)

https://github.com/OpenRCT2/OpenRCT2/issues/13885

**Comment by janisozaur** [comment]
Outdated build, no dump
