### ISSUE TITLE
Graphical glitches when building from MS Visual Studios 19

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#13887]
When building form my MS Visual Studios 19 environment, in either debug or release target, I get numerous graphical glitches above light sand land tiles:
![image](https://user-images.githubusercontent.com/3454156/105320253-d0abf480-5b7a-11eb-9e5b-d9eece54cb24.png)

`Running bisect took me to these commits:
There are only 'skip'ped commits left to test.
The first bad commit could be any of:`
bafafa6805ae62ad0845be43d129155a68a0d11a
6df36127b4c83ba07632dd1c253ada883dd192b7
`We cannot bisect more!`

The testing procedure I used was:
Start at main menu
Open a new game of Six Flags over Holland
Move the camera to the NW (relative to the camera) until it reaches Goliath

**Comment by spacek531** [comment]
Some say that building g2 is the issue. I think it's not the issue.
![image](https://user-images.githubusercontent.com/3454156/105327698-115c3b80-5b84-11eb-8b94-47f555a4dc8e.png)

**Comment by IntelOrca** [comment]
Make sure you are using the latest version of all the JSON objects.

**Comment by spacek531** [comment]
That fixed it, thanks!
