### ISSUE TITLE
Feature request: park entrance price warnings

### ISSUE THREAD

**Issue by galfisk** [OpenRCT2/OpenRCT2#13898]
Most RCT1 scenarios are meant to be played with a combination of park entrance and ride fees. In the original RCT1, unless you have the entrance price set to free, the game will show a notification if the guests think that the entrance price is too low or too high. OpenRCT2 doesn't appear to do this.

**Comment by Broxzier** [comment]
RCT2 does do this as well. Make sure you have that type of news message enabled.

With OpenRCT2 you can unlock both prices, and guests will only pay 1/4th (IIRC) of the price for ride tickets if they a park entry fee.

**Comment by galfisk** [comment]
Strange. I have all notification types enabled, but I'm unable to provoke the "fee too low" message, even with an entrance price of 1 kr, a park rating now at 880, and 8 popular rides, out of which two were rollercoasters. I was able to get the "fee too high" warning though.

**Comment by Broxzier** [comment]
Right, there is no warning for a too low parking fee, only for when it's too high. This feature can be added very easily by a plug-in.

**Comment by ocalhoun6** [comment]
@galfisk 
It's not an explicitly 'fee too low' message, but there should be a message that says something about peeps thinking the entry price is a really good value ... which is a little hint that it could be higher.

**Comment by galfisk** [comment]
The actual alert message is, in yellow, screenshot: [https://i.redd.it/0tudqaamas411.png](url)
"Guests are commenting that your park entrance fee is very cheap
Perhaps you could increase the entrance fee to make more money"
And it's quite a useful feature of RCT1. This message is not in OpenRCT2, but the entrance fee too high message is at STR_2813.

**Comment by ocalhoun6** [comment]
I could swear I'd seen that message in OpenRCT2 at some point...
