### ISSUE TITLE
OpenRCT2 crashed after I clicked Scenery Editor

### ISSUE THREAD

**Issue by zacharyhub** [OpenRCT2/OpenRCT2#13891]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.3.2]
**Commit/Build:** [e.g. 426e106]

I was playing OpenRCT2 and I decided to go to Scenery Editor, but after i click that, It crashed.

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**
It won't let me to put that dump file.

**Screenshots / Video:**
![Unnamed park  121-00-21 11-27-52](https://user-images.githubusercontent.com/8335233/105380775-472d0e80-5bdc-11eb-8090-7d3f4c27f027.png)

**Save game:**
It won't let me to put that save file.

**Comment by James103** [comment]
Can you try zipping the save file (and possible dump files) and posting it here?

**Comment by duncanspumpkin** [comment]
This is an ancient build. Update to the latest version.
