### ISSUE TITLE
Block brakes do not animate

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#13894]
I was pawing through a g1 dump and I noticed the wooden coaster has sprites for closed and open block brakes. Considering that in the code only one ride has calls to `BlockBrakeClosed()` (the junior coaster) and I recall RCT2 having animated block brakes, I think this is a regression.

for example:

Wooden coaster even direction block brake open: 23757
Wooden coaster odd direction block brake open: 23758
Wooden coaster even direction block brake closed: 23759
Wooden coaster odd direction block brake closed: 23780

Reimplementing these sprites should be simple since they all follow the same pattern as outlined above.

4D coaster station block brakes start at 15812
4D coaster block brakes start at 16220
4D coaster inverted block brakes start at 26551
Corkscrew block brakes start at 16232
LIM Launched block brakes start at 15020
Bobsled block brakes start at 14586
Steel wild mouse block brakes start at 16904
B&M block brakes start at 17150
Inverted wild mouse block brakes start at 17030 - maybe
Giga coaster block brakes start at 18076
Giga coaster front side block brakes start at 18080
Mini coaster block brakes start at 18742
Mine train coaster block brakes start at 20060
Wooden coaster block brakes start at 23757
Standup coaster block brakes start at 25571
Junior Coaster block brakes start at 28193

Suspended swinging coaster block brakes absent
Vekoma SLC block brakes absent
B&M inverted block brakes absent
Single rail suspended coaster block brakes absent
Wooden wild mouse block brakes absent
Steeplechase block brakes absent

**Comment by duncanspumpkin** [comment]
The junior coaster was one of the only ones that were implemented by hand. The rest were implemented by test paint. It's easy enough to check if test paint accounted for block brake position.

**Comment by duncanspumpkin** [comment]
I don't see anything in test paint for the block brake open closed. So looks like it was missed.

**Comment by Gymnasiast** [comment]
- [ ] 4D coaster station block brakes start at 15812
- [ ] 4D coaster block brakes start at 16220
- [ ] 4D coaster inverted block brakes start at 26551
- [ ] Corkscrew block brakes start at 16232
- [ ] LIM Launched block brakes start at 15020
- [ ] Bobsled block brakes start at 14586
- [ ] Steel wild mouse block brakes start at 16904
- [ ] B&M block brakes start at 17150
- [ ] Inverted wild mouse block brakes start at 17030 - maybe
- [ ] Giga coaster block brakes start at 18076
- [ ] Giga coaster front side block brakes start at 18080
- [ ] Mini coaster block brakes start at 18742
- [ ] Mine train coaster block brakes start at 20060
- [ ] Wooden coaster block brakes start at 23757
- [ ] Standup coaster block brakes start at 25571
- [x] Junior Coaster block brakes start at 28193
