### ISSUE TITLE
Newly placed ride exits are unusable unless removed and replaced

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#13903]
**OS:** Windows 10
**Version:** 0.3.2
**Commit/Build:** 54578a0

Building a custom ride becomes a bit annoying with a new issue where placing down a ride exit still does not allow you to test or open the ride. The ride's station will not register that the exit building is actually there, as the station's fence will still be drawn where the exit is (which is where the fence shouldn't be drawn at all). This also results in the ride being able to have multiple ride exit buildings, only one of which actually becomes usable. The ride exit becomes usable again once you remove it and replace it multiple times.

**Steps to reproduce:**
1. Build a new custom ride (can be a flat ride or a tracked ride)
2. Try to place down the ride exit
3. You will now see that the ride's station will claim that it has "no exit" even though it is there.
4. The ride exit can only be forced to register if you remove and replace it multiple times.

**Screenshots / Video:**
![Zenith Stacks 2021-01-22 11-56-47](https://user-images.githubusercontent.com/61885939/105539272-647bde80-5ca9-11eb-95c9-5c4541ae1a28.png)
![Zenith Stacks 2021-01-22 12-01-12](https://user-images.githubusercontent.com/61885939/105539789-14e9e280-5caa-11eb-8bf2-72b52a438ccb.png)

**Comment by duncanspumpkin** [comment]
https://github.com/OpenRCT2/OpenRCT2/pull/13822 Likely caused this. @ZehMatt

**Comment by spacek531** [comment]
I can recreate this with the following:
1. Build any track from scratch. Place entrance huts
2. Test the ride. Ride works fine
3. Enter construction of the ride
4. Delete one piece
5. Test the ride. Ride asks to place entrance huts
