### ISSUE TITLE
Issues with the Swedish translation

### ISSUE THREAD

**Issue by galfisk** [OpenRCT2/OpenRCT2#13900]
**OS:** Windows 10
**Version:** 0.3.2
**Commit/Build:** cea5fab

Here are some issue I've noticed with the Swedish translation:
"Spiral slide" is not translated. It should be "Spiralrutchkana" or "Spiralkana".
The translation for "Use vertical sync" is too long, and covers up the checkbox and text for multithreading.
Several other translations are just slightly too long for their windows. I can find and list those I find if you like.
"Disable screensaver and monitor power saving" is not translated.
"Random title sequence" has not been translated. Should be "Slumpmässig titelsekvens".
Many terms in the "shortcut keys" window are not translated: "Toggle clearance checks", "Increase (and decrease) scale factor" and all but the first of the "Tile inspector" ones.
One thing that has been translated shouldn't have been: "Added Attractions" is the name of the first expansion for RCT1, and should not be translated to "Tillagda attraktioner".
The translations of the "Build your own" park titles are inconsistant, and in one case, gramatically wrong. "Bygg din egna" would work for all of them.

If you start a park, choose "New game" and change the game language while the new game scren is up, the park names which have translations stay their previous language. If you start a park in one language, and then chage language, the park description stays in the old language, while the mission description changes.

I'm interested in contributing to the completeness of the Swedish translation if it's needed.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
See above.

**Dump file**
none

**Screenshots / Video:**
none, can provide if needed

**Save game:**
none

**Comment by Gymnasiast** [comment]
Translations are maintained here: https://github.com/OpenRCT2/Localisation
There are two files: one for the interface and scenarios, and one for the objects.
