### ISSUE TITLE
Develop SV6 crash Release

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#13905]
**OS:** Windows 10
**Version:** 0.3.2
**Commit/Build:** 6034cef

A save made in the Develop version of the game will crash Release version of OpenRCT2.

Test procedure: 
1. Start OpenRCT2 Develop Version
2. Begin a new game of Six Flags Holland
3. Export park
4. Start OpenRCT2 Release Version
5. Import park
6. game crash

Some slightly-newer versions of Develop don't crash on import, but all entities are frozen. New entities like closing a roller coaster and opening it again are not frozen.

**Comment by duncanspumpkin** [comment]
argh this will be my entity rebuild failing.
