### ISSUE TITLE
Dome park no longer renders dome correctly

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#13912]
**Version:** 0.3.2
**Commit/Build:** develop

Broken in 0.3.2+:
![openrct2_2021-01-23_00-12-4553a959da67e3725e5](https://user-images.githubusercontent.com/5415177/105554479-1c43d700-5d10-11eb-85cf-225bda4b11ba.png)

Working in 0.3.1:
![openrct2_2021-03-13_09-57-30b157fb33745139980](https://user-images.githubusercontent.com/5415177/111023598-9cb6b800-83e2-11eb-868f-c7d60d92972c.png)

Park
[dome-export.zip](https://github.com/OpenRCT2/OpenRCT2/files/6134362/dome-export.zip)

**Comment by janisozaur** [comment]
Caused by 711dd00cdec4b4ce1479364e031c6b16222298a6

**Comment by Gymnasiast** [comment]
You mean [this one](https://www.nedesigns.com/park/3324/h2h7-r1-circus-circus-adventuredome-atlantic-city/download/) ? Seems to work for me.

**Comment by Gymnasiast** [comment]
Closing because I cannot reproduce it, but feel free to reopen if I missed something.

**Comment by ZehMatt** [comment]
> Closing because I cannot reproduce it, but feel free to reopen if I missed something.

This is not the park shown in the screenshot. I've attached the park that is broken, and it is still broken.

**Comment by ZehMatt** [comment]
NSF branch seems to have this fixed, still present on develop.
