### ISSUE TITLE
Erroneous "Exit not yet built" error allows building multiple unusable exits

### ISSUE THREAD

**Issue by Soninmyeyes** [OpenRCT2/OpenRCT2#13919]
![No Exit](https://user-images.githubusercontent.com/40150885/105564044-70d65a80-5cee-11eb-93ff-6ceaa1118c44.png)
Recently, I've occasionally been getting an "Exit not yet built" error when trying to test or run new rides that already have exits. When this happens, adding an exit doesn't remove the first one, but usually, once I have added a new exit and manually removed the original one, I am then able to test and run the ride as normal.

On one occasion, as shown in the screenshot, replacing the original exit did not solve the "Exit not yet built" error, and on experimentation, I found that I was able to add even more exits. Deleting the ride and starting over did not solve the issue; nor did saving the scenario, returning to the menu, and re-opening the scenario. However, after restarting OpenRCT2, I was able to open the saved scenario file and build and open the ride.

Version: OpenRCT2, v.0.3.2-429-gbc20efb3d (bc20efb on develop)
OS: Windows 10

**Comment by ZehMatt** [comment]
This should be fixed in the latest develop branch
