### ISSUE TITLE
Setting indestructible for all sequence pieces in track element

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#13918]
Is there any reason to/not to set the indestructible flag for all sequence pieces in a track element?

I'm considering making diagonal brakes and block brakes, and I want to know if there's anything good/bad with writing the brake flag to the entire sequence or just sequence 0 in the implementation and in the tile sequence.

**Comment by Gymnasiast** [comment]
I would recommend setting the flag on all pieces in the sequence.

**Comment by spacek531** [comment]
I don't know why this is under issues instead of questions, but I came to the same conclusion.

**Comment by Gymnasiast** [comment]
It predates our use of GitHub Discussions.
