### ISSUE TITLE
Can't delete or edit rides with maximum station count

### ISSUE THREAD

**Issue by andrewsarnold** [OpenRCT2/OpenRCT2#13916]
**OS:** Windows 10
**Version:** 0.3.2-434-g73275b311
**Commit/Build:** 73275b3

In the attached park, I have three car rides (all outside the park). They each have 4 stations. If I try to delete them, or do construction work on them, the game will crash.

The game does *not* crash if I try to edit any other ride, including other rides outside the park.

An attempt to load this park from the Release branch caused an immediate crash.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Start a brand-new park
2. Enable sandbox mode
3. Build a complete circuit car ride with the maximum number of stations (4), and close the construction window
4. Attempt to demolish the ride, or remove pieces of the track
5. Crash

*or*
1. Load attached sv6 file
2. Attempt to delete ride "_Parked cars"

**Dump file:**
[7defdfc7-aa30-4c02-adbb-2ac5d6d48905(73275b3_x86-64).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/5859161/7defdfc7-aa30-4c02-adbb-2ac5d6d48905.73275b3_x86-64.dmp.gz)

**Save game:**
[save_file.zip](https://github.com/OpenRCT2/OpenRCT2/files/5859172/save_file.zip)

**Comment by James103** [comment]
To be more exact, in OpenRCT2 release 0.3.2, loading the attached savegame while paused does not immediately crash, but simulating the next game tick with that savegame crashes.

**Dump file:**
[873bcda1-ad44-4a05-a4da-6550e6b558fc.zip](https://github.com/OpenRCT2/OpenRCT2/files/5859186/873bcda1-ad44-4a05-a4da-6550e6b558fc.zip)

**Comment by andrewsarnold** [comment]
Trying to debug this on my own; looks like it's crashing somewhere within `ride_clear_entrance_location` (in Ride.cpp). The rides that make the game crash all have multiple stations; I can't tell which of the stations it crashes on.

**Comment by andrewsarnold** [comment]
I started a brand-new sandbox park and built a car ride outside the park boundaries, with multiple stations. Trying to delete that one caused the game to crash, too. So it doesn't seem to be any issue caused by the original sv6 I provided.

**Comment by andrewsarnold** [comment]
Some more debugging reveals that it's car rides with 4 stations specifically that cause the crash. **If I update the code so that `MAX_STATIONS` in Ride.h is `8` instead of `4`, the game will not crash.**

**Comment by Fred-1044276** [comment]
I can also confirm that the game will freeze/crash if you try to build a ride with 4 stations. It doesn't have to be a car ride. I tested this with a hyper-twister roller coaster by attempting to place down this [particular track design (Extreme income no inversions.td6)](https://drive.google.com/file/d/1dw1WEaZyACUkWqr_7iRqcTdICQFUcH8n/view?usp=sharing) and the game just froze/crashed on me.

**Comment by duncanspumpkin** [comment]
@ZehMatt possibly related to fixed vector refactor
