### ISSUE TITLE
View options independent of windows

### ISSUE THREAD

**Issue by Phasedetect** [OpenRCT2/OpenRCT2#1392]
If the scenery, ride construction, or path window is closed, it turns off all active view options. It would be great if the view option toggles weren't tied to windows.

**Comment by IntelOrca** [comment]
How should the game determine whether to turn them off or not. Usually this is helpful as closing the tool window means you have finished your work and no longer need the view options. Maybe a lock item on the view menu?

**Comment by sjoerddebruin** [comment]
OpenTTD has a button to pin windows, to be sure they can't be closed. Seems relevant in combination with the snapping feature.

**Comment by IntelOrca** [comment]
@sjoerddebruin I think window pinning is unrelated to this issue. I do want to add window pinning but it would be easier to do that once our window system has been redesigned so that the window head is consistent and uses the same code for every window type.

**Comment by Phasedetect** [comment]
Where I find it bothersome is when I have more than one of those specific windows open at once. If I'm building a coaster, I usually have see-through scenery enabled. If I open the path tool make a path from the entrance/exit to the main path, and then close that window to go back to coaster building, it disengages see-through scenery, even though I still wanted it and was just taking a second to build a quick path.

**Comment by vzybilly** [comment]
When one of those windows open, mark the ones that are already active then don't turn those off when the window closes. thusly only turning off the new options since that window has been around. this idea should help for the issue.

**Comment by Phasedetect** [comment]
@vzybilly That would help the issue a bit, but I think it'd just be easier to unlink the two entirely.

**Comment by vzybilly** [comment]
I do agree that both work, I'm just thinking that there was a reason behind it resetting the view filters when the window is closed. it can go either way, I was just adding in a way that could keep the functionality while removing the more 'edge' cases...

**Comment by IntelOrca** [comment]
Will be resolved by #1734.
