### ISSUE TITLE
Clients do not run server plugins

### ISSUE THREAD

**Issue by PhasecoreX** [OpenRCT2/OpenRCT2#13933]
**OS:** Manjaro Linux
**Version:** 0.3.2 (stable) and 0.3.2-437 (latest)
**Commit/Build:** cea5fab (stable) and eb52391 (latest)

Maybe I'm just doing something wrong, but based on https://github.com/OpenRCT2/OpenRCT2/blob/develop/distribution/scripting.md, remote plugins should automatically be uploaded to all connecting users so that every user is running the same code on the same ticks (and thus avoiding network desyncs). I'm also assuming that would include the plugins config as well. However it seems that this plugin uploading process doesn't work?

For example: https://github.com/OpenRCT2/plugin-samples/blob/master/subscriptions.js. Although for this example the network desync error does not occur, the cash on the server and the cash on connected clients day by day gets further and further out of sync. Other plugins (such as the ride-price-manager) do more modifications which eventually leads to network desyncs.

I assumed that since the `park.cash += 100;` was within a day subscription, all clients would get the plugin and run this code on each day. Even running OpenRCT2 from the terminal and adding some console.logs to the script doesn't show the plugin even running on the clients, only the server.

I also tried this with a headless OpenRCT2 server, still doesn't send the remote scripts to the clients. The headless server does load all of the local plugins for some reason though; that might be another bug, or I might not understand what local means.

I love the idea of plugins, and I have some ideas for ones I want to write. I just would like to have them work when I host parks for friends :)

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**
1. Put the https://github.com/OpenRCT2/plugin-samples/blob/master/subscriptions.js file in the OpenRCT2 plugin folder
2. (optional) change `park.cash += 100;` to something larger, so the difference is more noticeable.
3. (optional) remove `daySubscription.dispose();`, so that we always add cash no matter what for testing.
4. Run a server, notice your cash go up every in game day.
5. Have a client connect, notice that their cash isn't going up, presumably since they aren't running the plugin.

**Save game:**
None, just start a new scenario. Not save specific.

**Comment by IntelOrca** [comment]
@PhasecoreX thanks for reporting this. Could you try the latest develop build and see if it works now?

**Comment by PhasecoreX** [comment]
@IntelOrca Yes, it seems like the client is now running the remote plugins! This opens up two other issues that I can see at the moment though:

1. If the client and server have mismatched `plugin.store.json`, both client and server will be running the same code, but might be doing slightly different things based on settings. For example, [Ride Price Manager](https://github.com/mgovea/openrct2-ride-price-manager/blob/c09cb204fe17fe2ce7b603fb968f7f52ca728987/src/ridePriceFunctions.ts#L55) by default will have a [0% "lazy tax"](https://github.com/mgovea/openrct2-ride-price-manager/blob/c09cb204fe17fe2ce7b603fb968f7f52ca728987/src/config.ts#L15), with an option on the frontend to set this to a higher tax. If the server has this set to 5%, the joining clients will still be at the default 0%, causing a difference in ride prices and a network desync. Maybe the client needs to have the servers `plugin.store.json` loaded temporarily and read-only while connected?

2. It seems like when the server loads a scenario with clients connected, or when a client reconnects from the multiplayer menu when desynced, none of the plugins load. When they first join the server, all plugins load just fine though, just this reconnection removes them.

Let me know if you want these as new issues, or if it's okay to leave here as part of this issue. Regardless thank you for working on this!

**Comment by IntelOrca** [comment]
@PhasecoreX

1. `plugin.store.json` is local storage for the client. When writing multiplayer plugins you can not assume this to be the same. Transmitting it automatically wouldn't be a good idea as it could be very large and not all of it useful to the clients. It may also contain sensitive information for the same or different plugin. Use custom game actions instead to transmit data.

2. Could you raise a separate issue for this? I think the intention is that the plugins stay loaded when changing park. This should apply to both single player and multiplayer.

**Comment by PhasecoreX** [comment]
@IntelOrca 

1. Yes that does make sense, however I think it defeats the purpose of having configurable options for a plugin then, at least in a multiplayer server. [Ride Inspection Manager](https://github.com/aelindeman/openrct2-ride-inspection-manager/blob/9c97bf22f59be25d3335aa478e2385aed3af12eb/src/config.ts#L46) is disabled by default, so I think that makes it completely useless as a [remote](https://github.com/aelindeman/openrct2-ride-inspection-manager/blob/9c97bf22f59be25d3335aa478e2385aed3af12eb/src/index.ts#L21) plugin.

Do you have an example of custom game actions for transmitting data? I thought you meant `context.executeAction()`, but that doesn't seem to work either (they way I am using it, which is executed based on a config value).

2. Yes I will make one now.

**Comment by IntelOrca** [comment]
@PhasecoreX Most plugins haven't been written to be multiplayer compatible. So that doesn't surprise me. I am not sure if all plugin developers correctly set local / remote.

Here is an example of a custom game action:
https://github.com/Gymnasiast/everything-must-die/blob/master/everything-must-die.js

You do use `context.executeAction` and you pass whatever data you like.

If you want to discuss plugins more with me and other plugin develops, please join the discord chat:
https://discord.com/invite/DxsQAnv `#plugin`
