### ISSUE TITLE
Bigger Window buttons for higher DPI screens.

### ISSUE THREAD

**Issue by hemmofa** [OpenRCT2/OpenRCT2#1393]
I play OpenRCT2 on my Windows Tablet (Acer Iconia W4) and it runs amazingly well, especially since the RCT1-style start/stop ride buttons were implemented (so i don't have to do a dragging mouseclick to go into ride testing mode). 

One of the few things that is still annoying during gameplay is the fact that the close-window buttons are hard to reach. Could it be possible to have an option to make the close-window button (and therefore i think the whole titlebar) a bit bigger, to the size of most other ingame buttons and tabs?

Also, small side question, if this is easy answerable: How far is the decompiling progress of the original rct2 exe? 1%? 10%? 50%? I kind of expect it between 10 and 30% or something.

**Comment by Gymnasiast** [comment]
Bigger GUI buttons, for devices like tablets or hi-res screens is among the most frequently requested features. It will probably take some time until this is implemented, however. It's more complicated than just enlarging the title bar.

About the decompilation: it's roughly at 60%: https://docs.google.com/spreadsheets/d/1pu-NZk27pUPsmdEpYU3ZpEQpbKmT1YaDRmKvd41RMZA/edit?pli=1#gid=1577664071

**Comment by webhawk** [comment]
Awesome to hear about the statistics! 
But then you can close this issue in that case. Apparently I have failed to properly look through the issues/feature requests.

**Comment by Gymnasiast** [comment]
Yeah, the progress is very nice indeed. :)
You can close the issue yourself. There is a button below.

**Comment by webhawk** [comment]
Will do. Thanks!

**Comment by IntelOrca** [comment]
I think we should just have an issue for this so that more aren't added in the future. This is different from closer zoom levels.

**Comment by webhawk** [comment]
It was really meant as something different from closer zoom levels. I want that as well, but saw an open issue for that already. Keep up the good work!

**Comment by Gymnasiast** [comment]
Yeah, I agree it's clearer this way than the remark in #775.

**Comment by AaronVanGeffen** [comment]
We have window scaling available nowadays, and there are other issues proposing to split the rendering of UI and viewports. Can this be closed?

**Comment by hemmofa** [comment]
What I love about this project is getting e-mails with updates to issues/questions even 3 years later. It shows the developers really care to a large extent. Combined with the fact (or well, assumption) that this is all voluntary work for you, it makes my heart beat faster.

**Comment by hemmofa** [comment]
Unfortunately, the tablet mentioned in the issue has since then been stolen, but if window enlargement has been added, this issue can be closed.
