### ISSUE TITLE
Fail and warn user when saving TD6 with track types > 256

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#13949]
From looking at the TD6 format, I think that all the room to store new track pieces is used up, aside from very special cases like the spinning control toggle. 

There should be a warning and fail the export if a track type is > 256 (Spinning Control Toggle).

(There's still a small amount of room to fit certain new track pieces in SV6)

**Comment by duncanspumpkin** [comment]
No, work should instead be made on makeing a new track design format.

**Comment by spacek531** [comment]
It looks like it's as simple as returning a false value in https://github.com/OpenRCT2/OpenRCT2/blob/45fd8e8d05e77269770590feff8103aff2668861/src/openrct2/rct2/T6Exporter.cpp#L48
