### ISSUE TITLE
Blank rides in scenario editor when using RCT2 assets without expansion packs

### ISSUE THREAD

**Issue by galfisk** [OpenRCT2/OpenRCT2#13954]
**OS:** Windows 10
**Version:** 0.3.2
**Commit/Build:** c1a1f8f

When using the RCT2 files which don't include the expansion packs, it's still possible to select expansion pack rides in the scenario editor, but there's no thumbnail. When playing the scenario, it's possible to place the rides, but the trains will be invisible on tracked rides, and only the platform will be invisible on other rides.
It'd be better if they didn't show up in the editor at all, unless the required expansion packs were installed.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Download and install RCT2 vanilla ISO from archive.org: https://archive.org/details/RollerCoasterTycoon2_201903
2. Install OpenRCT2
3. Open scenario editor and select available rides from the expansions, such as the double-deck carousel. Notice that there is no picture for it.
4. Put it in the inventions list, save the scenario, and start playing it
5. Build the double-deck carousel. Notie that it has no picture in the build menu either. It'll still be built and take guests, but only the platform underneath shows up
To fix it:
6. Install the expansion packs (also found on archive.org)
7. Restart OpenRCT2. Now the double-deck carousel and other rides show up as intended

**Dump file**

**Screenshots / Video:**

![Namnlös park 2021-01-26 09-03-06](https://user-images.githubusercontent.com/31153158/105817252-a5c80300-5fb5-11eb-9258-cbda4cea28ad.png)

**Save game:**

**Comment by Broxzier** [comment]
You must have enabled the filter for Expansion content. Tick these off and they won't appear in the object selection.

![Unnamed park 2021-01-26 09-12-51](https://user-images.githubusercontent.com/9705046/105818188-e1170180-5fb6-11eb-8353-d7e308989657.png)

**Comment by duncanspumpkin** [comment]
Also we won't support people who do not purchase the game. I've removed all references to pirated content.

**Comment by galfisk** [comment]
Fair solution, though I think it'd be better if non-available content didn't show up looking buggy in the first place. I did buy the games ages ago, but the discs are somewhere in storage.

**Comment by duncanspumpkin** [comment]
The reason it shows at all is because the game can be run headless without the rct2 graphics assets. It would make for some annoying code accounting for if the graphics were there or just the json object.

**Comment by galfisk** [comment]
I see, sounds like a reasonable compromise then.

**Comment by ocalhoun6** [comment]
Maybe the game could show a little pop-up warning when trying to load assets and failing to do so?
