### ISSUE TITLE
Scenario editor not handling Swedish characters correctly

### ISSUE THREAD

**Issue by galfisk** [OpenRCT2/OpenRCT2#13955]
**OS:** Windows 10
**Version:** 0.3.2
**Commit/Build:** c1a1f8f

In the scenario editor, when using the Swedish language, the default park name is "Namnlös park", and the default park/scenario details are "Inga detaljer ännu". If I save the scenario with this text, it'll show up horribly garbled in the scenario list, as seen in the screenshot. Extra spaces and wrong symbols show up after the umlauted letters.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Switch language to Swedish
2. Create a scenario in the editor
3. Have the letter ö or ä in park name or details
4. Save the scenario and then find it in the scenario list

**Dump file**

**Screenshots / Video:**

![Skärmbild (19)](https://user-images.githubusercontent.com/31153158/105818307-0a379200-5fb7-11eb-95ff-bb7080a648a8.png)

**Save game:**

**Comment by Ryder17z** [comment]
this should apply to the letter å as well.

**Comment by Gymnasiast** [comment]
This is likely fixed in v0.4.0. Things to test:

- [ ] Creating a scenario in OpenRCT2 and checking if they appear correctly
- [ ] Creating a scenario in vanilla RCT2 and checking if they appear correctly in OpenRCT2’s list

**Comment by Gymnasiast** [comment]
Tested this with a newly created scenario in OpenRCT2 and one imported from RCT2. Both now appear correctly. Sadly, we cannot do much about scenarios that were created up until the NSF was merged.
