### ISSUE TITLE
Assertion failed: Peep Ridesubstate should be LeaveEntrance

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#13958]
**OS:** [e.g. Windows 10]
**Version:** [0.3.2]
**Commit/Build:** [8c5cd61]

My server keeps crashing (usually after several hours) with the following message:
![image](https://user-images.githubusercontent.com/6469413/105869149-35da6c80-5ff7-11eb-847b-5813517e71e2.png)

Here's a save file where it will happen a minute or so after you open it (speed up the game a bit to make it happen faster). Removing all guests from the park will temporarily stop it from happening.
[autosave_2021-01-26_16-43-13.zip](https://github.com/OpenRCT2/OpenRCT2/files/5874470/autosave_2021-01-26_16-43-13.zip)

**Comment by James103** [comment]
Where can I find the palette `DKWTRSWR` so that I can test the savegame?

**Comment by deurklink** [comment]
> Where can I find the palette `DKWTRSWR` so that I can test the savegame?

Here it is,
[DKWTRSWR.zip](https://github.com/OpenRCT2/OpenRCT2/files/5874969/DKWTRSWR.zip)

**Comment by James103** [comment]
The save file requires the latest `develop` version of OpenRCT2 to load, it does not load in release 0.3.2 or earlier.

**Comment by deurklink** [comment]
> The save file requires the latest `develop` version of OpenRCT2 to load, it does not load in release 0.3.2 or earlier.

Yes, I have indicated the build with which I have this issue. Testing this save file on the release version won't help anyone much.

**Comment by deurklink** [comment]
After testing from @duncanspumpkin and joellarsson (discord name) it was found that a queue which clipped through an entrance and an exit most likely caused this issue. After rebuilding the queue so it no longer clipped through the entrance and exit, the game stopped crashing. 

![image](https://user-images.githubusercontent.com/6469413/106177996-84277100-6199-11eb-93a5-c3f854b3da10.png)

@duncanspumpkin commented on Discord that he plans on making a fix for this.
