### ISSUE TITLE
Display where a track design is located inside the track selector

### ISSUE THREAD

**Issue by Ryder17z** [OpenRCT2/OpenRCT2#13967]
As my collection of tracks has grown substantially, I've moved custom tracks into different subfolders of OpenRCT2/track/ to make it easier to sort them.

I would like to have the path added at the bottom of the window, similar to how the scenario selector lists the paths.

![image](https://user-images.githubusercontent.com/2000703/106329499-d0e67700-6281-11eb-90a1-362edd80c7d0.png)

**Comment by kimjcalvin** [comment]
@Ryder17z by scenario selector do you mean 'Load Game' window from the title screen? For 'Start a new game' -> 'Select scenario for new game' , I don't see the path list.

**Comment by Ryder17z** [comment]
@kimjcalvin 
![https://user-images.githubusercontent.com/10726524/39252015-a9ef89a2-48df-11e8-82d0-9e14652f6c12.png](https://user-images.githubusercontent.com/10726524/39252015-a9ef89a2-48df-11e8-82d0-9e14652f6c12.png)

I don't know why it's removed currently and i'm not a fan of that change

**Comment by CorySanin** [comment]
It's not removed. It's at the bottom of the window. It's partially covered up by the park information window.

**Comment by Ryder17z** [comment]
> It's not removed. It's at the bottom of the window. It's partially covered up by the park information window.

you misunderstood me. I mean I don't see it in version d26590c (latest found on flathub)

**Comment by IntelOrca** [comment]
You need to have debug options enabled in settings for it to show.

**Comment by kimjcalvin** [comment]
Ok will start working on this issue thanks guys

**Comment by Ryder17z** [comment]
I wasn't aware of it being only visible when debug tools are enabled.
