### ISSUE TITLE
Some spinning wild mouse designs can't be built or take forever to calculate stats

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#13976]
**OS:** Windows 10
**Version:** 0.3.2
**Commit/Build:** 2d6da75

Some spinning wild mouse designs, namely Dizzymouse, can't be built anymore. In addition, the spinning wild mouse now fails to get its stats calculated, which can block the stat calculation of other rides in the park.

**Steps to reproduce:**
1. Attempt to build the design Dizzymouse and it should block you with a message saying "Can't construct this here... in the way".
2. Build a custom spinning wild mouse design and complete it. Its stats will no longer be able to be calculated.

**Screenshots / Video:**
![Wacky Waikiki 2 2021-01-31 11-58-34](https://user-images.githubusercontent.com/61885939/106396382-61c16d80-63bc-11eb-96b9-111883613bfa.png)
![Wacky Waikiki 2 2021-01-31 12-00-26](https://user-images.githubusercontent.com/61885939/106396384-62f29a80-63bc-11eb-80a8-874f286ca212.png)
The stats for this spinning wild mouse now take forever to calculate. Even if I removed the spinning control toggle section, its stats still would never be calculated.

**Comment by Gymnasiast** [comment]
Fixed by https://github.com/OpenRCT2/OpenRCT2/pull/13977.
