### ISSUE TITLE
OpenGL: Track preview window, flip/rotate button do not update the thumbnail

### ISSUE THREAD

**Issue by Ryder17z** [OpenRCT2/OpenRCT2#13986]
~~is it an openGL issue ?~~ (the ghost will update accordingly)
it is an openGL issue.

Version: db4841c

**Comment by Gymnasiast** [comment]
> is it an openGL issue ? (the ghost will update accordingly)

Well, you can easily test that yourself: do you have the same issue when using the game in software rendering mode?

**Comment by Ryder17z** [comment]
I currently don't have access to the game.

**Comment by Ryder17z** [comment]
While visiting another city for a work project, my laptop charger decided to die. I've just found a replacement charger and rechecked the issue. It only applies to OpenGL.
