### ISSUE TITLE
Separate window for displaying object load failures

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#1399]
It would be nice if we could display to the user as a OpenRCT2 window all of the objects that have failed to load and any extra info about them (exapansion, checksum failure, object type). At present set_load_objects_fail_reason is the function used for setting the single line message.

**Comment by Gymnasiast** [comment]
It might be a nice addition if one could copy-and-paste the text from the window, or alternatively save it to a text file for easier searching - manually typing again or diving into log files is a bit tedious if you have to find missing objects.

**Comment by IntelOrca** [comment]
Possibly also add the ability to remove all usages or an object or swap with another. But they could be console commands.

**Comment by duncanspumpkin** [comment]
When implementing add the too many images object error message as well #1473.
