### ISSUE TITLE
Guest thoughts summarized shows long list of blank rows with "0" at the end of each row

### ISSUE THREAD

**Issue by sr1gh** [OpenRCT2/OpenRCT2#13992]
OS: Windows 7
Version: 0.3.2
Commit/Build: 9d3f3fa

The summarized view of the guest thoughts window shows lots of blank rows with (0) at the end.

Screenshot:
![Diamond Heights 2021-02-04 08-50-37](https://user-images.githubusercontent.com/45770511/106902664-17473600-66c7-11eb-8007-ccb8b9433814.png)

**Comment by duncanspumpkin** [comment]
Urgh:
```
        // Remove up to MaxGroups
        _groups.resize(MaxGroups);
```
should have been:
```
        // Remove up to MaxGroups
       if (_groups.size() > MaxGroups)
       {
            _groups.resize(MaxGroups);
       }
```
