### ISSUE TITLE
Refactor Velocity Literals to use `_mph`

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#14010]
In our sister project I introduced the `_mph` literal for speeds https://github.com/OpenLoco/OpenLoco/pull/736
I'm almost definitely the underlying units are the same in OpenRCT2. Therefore we should bring in the same changes. First add the string literal code. Then find all of the velocity literals in the vehicle code.

Its quite easy to do just convert the literal to hex so `393216` = `0x60000` in hex then you drop the 4 `0`'s to get `0x6` which is the speed in `6.0_mph`

https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/ride/Vehicle.cpp#L5651
```
        if (velocity > -0x2C000)
            return OpenRCT2::Audio::SoundId::Null;
```
becomes
```
        if (velocity > -2.75_mph)
            return OpenRCT2::Audio::SoundId::Null;
```

You can use static_asserts to confirm that the values are identical `static_assert(2.75_mph == 0x2C000);`

**Comment by michiboo** [comment]
Hi Can I have a go at this issue?

**Comment by duncanspumpkin** [comment]
Sure go ahead.

**Comment by michiboo** [comment]
@duncanspumpkin  which file should I add string literal code to? I can't find a file similar to Types.hpp

**Comment by duncanspumpkin** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/common.h would probably be the best location. We have placed the money equivalents of this in there. Tbh we could probably do with changing the money macros to use a literal like this as well.

**Comment by duncanspumpkin** [comment]
@michiboo i did a bit more experimenting and i think my code can be slightly improved to provide higher precession. Might be useful for some literals that are harder to represent like 0.33333.

```
// Note: Only valid for 5 decimal places.
        constexpr uint32_t operator"" _mph(long double speedMph)
        {
            uint32_t wholeNumber = speedMph;
            uint64_t fraction = (speedMph - wholeNumber) * 100000;
            return wholeNumber << 16 | ((fraction << 16) / 100000);
        }
```

**Comment by michiboo** [comment]
@duncanspumpkin I have some problem trying to build it on ubuntu , is there a build guide somewhere?

**Comment by duncanspumpkin** [comment]
https://github.com/OpenRCT2/OpenRCT2/wiki/Building-OpenRCT2-on-Linux is our guide. @janisozaur can help you out if you provide information on what the issue is but please follow the guide first.

**Comment by michiboo** [comment]
@janisozaur  Hi i got this error when trying make 
/home/oem/Desktop/github/OpenRCT2/src/openrct2/actions/../core/../core/../object/../core/JsonFwd.hpp:12:10: fatal error: nlohmann/json_fwd.hpp: No such file or directory
 #include <nlohmann/json_fwd.hpp>

I had tried sudo apt install  nlohmann-json-dev already.

Can you please help?

**Comment by janisozaur** [comment]
You're using outdated version of the package. We require at least 3.6 (if memory serves me right)

**Comment by kaushikroychowdhury** [comment]
Can I give it a try for this issue ?
@duncanspumpkin

**Comment by duncanspumpkin** [comment]
Sure. OpenLoco has a great example of this https://github.com/OpenLoco/OpenLoco/blob/master/src/OpenLoco/Speed.hpp we've been using it for quite a while now with no noticable issues. Strongly suggest pretty much copying Speed.hpp and modifying it to follow the coding style of OpenRCT2.

**Comment by sohamroy19** [comment]
Replacing `-0x2C000` in `if (velocity > -0x2C000)` with `-2.75_mph`, as per your example, gives the error C4146: unary minus operator applied to unsigned type, result still unsigned
All comparisons give warnings like the warning C4018: '>': signed/unsigned mismatch

Should the `_mph` code be implemented as `int32_t` instead, or is there any other solution?

**Comment by duncanspumpkin** [comment]
If you look at my final code for OpenLoco I made it a signed value for speed.

**Comment by alexdt1982** [comment]
Is this issue still open? If so can I have a go at this?

**Comment by rzhao271** [comment]
I'd like to take this task

**Comment by rzhao271** [comment]
Considering that https://github.com/OpenRCT2/OpenRCT2/pull/18327 has been merged, as well as the discussion in that PR, do we still want to keep this issue open?
