### ISSUE TITLE
Text input window errors

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#14017]
**OS:** Windows 10
**Version:** 0.3.2
**Commit/Build:** 17f4f3a

Text input windows now look incomplete due to a mistake in a recent refactor. The buttons and the rest of the text input window graphics are missing, although the bar with the input and the text above it remain. Pressing ESC on the keyboard doesn't close the text input window either. These issues occur regardless of the UI theme selected.

**Steps to reproduce:**
1. While in gameplay, perform an action that will bring up a text input window (e.g. renaming a ride/staff member/guest, setting a ride's price, etc.)
2. The text input window will now look like the one in the screenshot below

**Screenshot:**
![Extraterrestrial Extravaganza 2 2021-02-07 19-40-13](https://user-images.githubusercontent.com/61885939/107173435-a2048b00-697c-11eb-80d4-319884d6600e.png)

**Comment by IntelOrca** [comment]
Sorry, I only tested the change in my plugin branch where I had some core changes to the Window class.
