### ISSUE TITLE
Park Crashes whilst saving.

### ISSUE THREAD

**Issue by StrangeAnomoly** [OpenRCT2/OpenRCT2#14042]
**OS:**Windows 10
**Version:** [0.3.2]
**Commit/Build:** [f75a48d]

**Steps to reproduce:**
1. Load attracted File
2. Attempt to save, Game crashes and auto closes.

**Save game:**

[Funtime Fiasco.zip](https://github.com/OpenRCT2/OpenRCT2/files/5954659/Funtime.Fiasco.zip)

**Comment by Fred-1044276** [comment]
It happens even if you start a new game.

**Comment by StrangeAnomoly** [comment]
Are you asking if I save it as a fresh save, does it crash?

**Comment by Fred-1044276** [comment]
It does crash. I can confirm (#14041).

**Comment by StrangeAnomoly** [comment]
Oh ok. That's annoying.

**Comment by Gymnasiast** [comment]
```
Thread 1 "openrct2" received signal SIGSEGV, Segmentation fault.
0x0000555555683043 in WidgetIsVisible (w=0x0, widgetIndex=-1)
    at /home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2-ui/interface/Widget.cpp:861
861	    return w->widgets[widgetIndex].IsVisible();
```

Perhaps related to one your recent PRs, @IntelOrca ?

**Comment by IntelOrca** [comment]
Sorry, missing a nullptr check.
