### ISSUE TITLE
"Disconnected: Connection closed" 

### ISSUE THREAD

**Issue by Visne** [OpenRCT2/OpenRCT2#14044]
**OS:** Windows 10
**Version:** v0.3.2-537
**Commit/Build:** f75a48d
**Commit/Build:** c0ab9e8 (same issue on both)

When I host a server my friends cannot join me. I cannot join my own server locally either. We get "Disconnected: Connection closed" after filling in the password. I have port forwarded correctly, and when I disable my firewall it still happens. Without a password the error instantly appears. Server logs are completely empty.

- [x] Specific to multiplayer?

**Steps to reproduce:**
1. Start server with port 11753, advertise on, passworded
2. Try joining, fill in password

I expect you cannot reproduce this.

**Comment by IntelOrca** [comment]
Are you all on the same version of OpenRCT2?

**Comment by Visne** [comment]
> 
> 
> Are you all on the same version / commit of OpenRCT2?

Yes, we first all tried c0ab9e8, then we all upgraded to f75a48d and it still didn't work.

**Comment by IntelOrca** [comment]
What park are you hosting on the server? Have you tried a vanilla park from the game, like Electric Fields scenario?

**Comment by Visne** [comment]
I was hosting the prehistoric asteroid crater scenario. Other scenarios also didn't seem to work.

**Comment by IntelOrca** [comment]
Try doing the following things locally on separate command lines locally:
```
openrct2 host park.sc6 --address 127.0.0.1
openrct2 join 127.0.0.1
```

You will need to navigate to your openrct2 install directory before you run those commands and replace park.sc6 with a full path to a scenario you want to open.

**Comment by Gymnasiast** [comment]
Closing as OP has not replied for > 3 weeks. (Can be reopened if OP returns.)
