### ISSUE TITLE
Hide rides sharing same track/type in scenario editor 

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#1405]
One of my main bug bears with rct2 was the amount of rides that actually were all the same ride. This is a particular problem in the scenario editor with the endless car/boat twister rides etc. I think an option to hide rides sharing the same track under a generic name like car ride, boat ride twister etc, then give the user the option to pick which ones they want, with a list on the left.
![untitled-15](https://cloud.githubusercontent.com/assets/1381723/8266984/83a5f00e-1743-11e5-9119-119ddac5be37.png)

**Comment by ThomasdenH** [comment]
Similar to #1363 for the rides selection window.

**Comment by IntelOrca** [comment]
Is this still an issue now that you can sort by ride type?

**Comment by Gymnasiast** [comment]
Closing this as we now have the capability to sort by track type.
