### ISSUE TITLE
Game crashes upon starting a newly created custom scenario

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#14076]
**OS:** Windows 10
**Version:** 0.3.2
**Commit/Build:** 14cca95

I created a new scenario just now and whenever I try to open it, the game immediately crashes. I would assume that even base game scenarios will also crash the game, thus making the game unplayable. I did not even get the park objective/info window to pop up upon loading the scenario.

The scenario I created in question has two park entrance paths, one on each side of the park, thus leading to two guest spawn points and two park entrances. I did not use any custom objects or plugins to create the scenario.

**Steps to reproduce:**
1. Open the attached scenario file below in the current develop build
2. The game will crash once the scenario loads

**Dump file:**
[66e578db-70bb-4ba9-8f50-98a257ae5a9d(14cca95_x86-64).zip](https://github.com/OpenRCT2/OpenRCT2/files/5968086/66e578db-70bb-4ba9-8f50-98a257ae5a9d.14cca95_x86-64.zip)

**Screenshot:**
![Elasmosaurus Pool 2021-02-11 11-55-22](https://user-images.githubusercontent.com/61885939/107691939-fa7ba700-6c60-11eb-8f3a-9f29d28190de.png)
This screenshot was automatically generated when the game crashed. I did set the scenario to have money enabled, but the bottom toolbar doesn't show money. As you can see here, the park objective/info window that normally pops up when you start up a scenario did not appear.

**Scenario:**
[Elasmosaurus Pool.zip](https://github.com/OpenRCT2/OpenRCT2/files/5968091/Elasmosaurus.Pool.zip)

**Comment by duncanspumpkin** [comment]
Crash caused by a plugin.
