### ISSUE TITLE
OpenRCT2 draws supports where vanilla wouldn't.

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#14089]
I investigated a little more about this bug: https://github.com/OpenRCT2/OpenRCT2/issues/8601 For reasons unknown to me, that issue was closed with the issue persisting.

OpenRCT seems to be inconsistent with small scenery and support blocking. Some small scenery with the same dimensions as other small scenery, and no other differences as far as I can see in the RCT2 Object Editor, behaves differently.

XXBBCL01 completely blocks a support in vanilla - in OpenRCT, a support will draw on that tile until it hits the object - like most base blocks that come with the game. This one is supposed to block supports completely though, like for example ROOF11.DAT/roof11.json.

This is as far as I can see... Can someone take it from here and find a cure for this?

A savegame that can be used for reference: https://www.nedesigns.com/park/3527/six-flags-great-north/ No steel supports should be showing anywhere in this save.

Using v0.3.2-488 (2a0604386 on HEAD)
Mac OS Catalina 10.15.7, but it may as well be windows 8.

**Comment by Gymnasiast** [comment]
#8601 has **not** been closed. Please post your new findings there.
