### ISSUE TITLE
 The Ladybird train uses the first vehicle type for all the vehicles in the train.

### ISSUE THREAD

**Issue by sr1gh** [OpenRCT2/OpenRCT2#14090]
OS: Windows 7, Windows 10
Version: 0.3.2
Commit/Build: 6e20f41

The Ladybird train uses the first vehicle type (with 4 wheels) for all the vehicles in the train instead of using the smaller 2 wheel versions for the cars behind the first one.

Screenshots:
![Forest Frontiers 2021-02-13 15-30-48](https://user-images.githubusercontent.com/45770511/107861044-276ebc00-6e11-11eb-911f-729ee19c9afd.png)
![Forest Frontiers 2021-02-13 15-19-55](https://user-images.githubusercontent.com/45770511/107861099-6dc41b00-6e11-11eb-9102-d8686120529d.png)
![Diamond Heights 2021-02-13 15-23-37](https://user-images.githubusercontent.com/45770511/107861102-71f03880-6e11-11eb-95ae-3aec907ff471.png)
![SCR1](https://user-images.githubusercontent.com/45770511/107861109-7f0d2780-6e11-11eb-819a-bcd4310ab222.png)

**Comment by Gymnasiast** [comment]
It only does this in parks imported from RCT1. It does this because RCT1 made no difference between these cars. Any junior RC you build after importing will have the correct configuration.
