### ISSUE TITLE
Holding down [-][+] buttons does not decrease/increase num. of circuit

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#14095]
**OS:** Windows 10
**Version:** 0.3.2
**Commit/Build:** 6e20f41

![](https://user-images.githubusercontent.com/10726524/107879290-45284800-6f1b-11eb-8912-1ce3f2c3759a.gif)

There is [-][+] buttons in the ride configuration tab which can adjust integer values, such as Launch speed, chain speed, number of circuit.
Hold to click the left mouse button to the [-][+] widget buttons decreases/increases the values for Launch speed and chain speed, but not for **Number of circuit**.

**Comment by IntelOrca** [comment]
Needs correct flag set in `hold_down_widgets`.

**Comment by Gymnasiast** [comment]
In the longer run, I think that every spinner/stepper should automatically have this. This does require a widget refactor though, so we'll get to that in 2029, then.
