### ISSUE TITLE
Loading a Save then starting a new game causes there to be two bottom bars

### ISSUE THREAD

**Issue by Krutonium** [OpenRCT2/OpenRCT2#14112]
**OS:** Arch Linux
**Version:** 0.3.2-560
**Commit/Build:** 0532ebab7

If you load a save, then Floppy -> New Game and pick a park, the UI will be hidden, except for the bar across the bottom. At that point if you toggle the UI using `T`, it will show all of the UI and it's functional, but the bar at the bottom will become less transparent as there is in fact 2 bars at the same place.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Load a Save
2. Load a New Game

**Dump file**

**Screenshots / Video:**
![1](https://user-images.githubusercontent.com/3945538/108176535-27e8aa80-70d0-11eb-885f-692cfb27ca22.png)
![2](https://user-images.githubusercontent.com/3945538/108176538-28814100-70d0-11eb-83fe-55b29aa24449.png)
![3](https://user-images.githubusercontent.com/3945538/108176540-28814100-70d0-11eb-9c2a-c7f709887b1c.png)

**Save game:**

[Crazy Castle.txt](https://github.com/OpenRCT2/OpenRCT2/files/5994282/Crazy.Castle.txt)

**Comment by Fred-1044276** [comment]
Sometimes if I do this, it also results in some severe graphical corruption in the scenario.

**Comment by Gymnasiast** [comment]
Bisecting points to d2a97ab43cb331b84bbe29cfc8a3fbd8dd49d913.

**Comment by Gymnasiast** [comment]
Could you test if #14116 solves this issue for you?
