### ISSUE TITLE
Scenario fail to load properly

### ISSUE THREAD

**Issue by EtienneGL** [OpenRCT2/OpenRCT2#14111]
**OS:** [Windows 10]
**Version:** [0.3.2]
**Commit/Build:** [426e106]

When we open a scenario (RCT2, RCT1, expansions or custom), the screen freezes and the scenario objective is not displayed. I tried to replicate it after removing any plug-ins and unlinking my RCT1 installation, it still happens.

In my case, I am able to click on icons and do stuff while the screen is frozen, for example closing the game. However, **Fred-104 (# 0035 on Discord)** says it also happens to him, however the game crashes when he clicks on the screen instead of still running.

- Reproducible in RCT2 (vanilla)? **No**
- Specific to multiplayer? **No**

**Steps to reproduce:**
1. Open the game
2. Open any scenario.

**Comment by Fred-1044276** [comment]
The crash actually occurred because of plugins that I used (#14076). I have observed it happen whenever I start up the scenario and the park information window does not even appear at all (normally, it appears as soon as you start up a new scenario from the scenario selector).

**Comment by EtienneGL** [comment]
Update: when I load a new scenario from a game in progress instead of the title screen, it works. However, it appears to do weird stuff right at the start like closing the scenario objective window or hiding the toolbars.

**Comment by Fred-1044276** [comment]
It's not just that. It sometimes even outright refuses to hide UI elements.

**Comment by Gymnasiast** [comment]
Could you test if #14116 solves this issue for you?

**Comment by EtienneGL** [comment]
> Could you test if #14116 solves this issue for you?

Idk how to test that. Can you PM me about it on Discord? I'm in the OpenRCT2 server.

**Comment by EtienneGL** [comment]
Managed to test it, and it solves the issue.
