### ISSUE TITLE
Switch drive in load/save window

### ISSUE THREAD

**Issue by ThomasdenH** [OpenRCT2/OpenRCT2#1412]
Currently the load save window is fixed to the same drive as OpenRCT2. It would be good to be able to change that. Drives could be enumerated with the enumerate_directories function when passed an empty path or it could be a separate function.

**Comment by AaronVanGeffen** [comment]
When designing a solution to this, you might want to take into account that only Windows uses drive letters; OS X and Linux use the UNIX root file system approach.
