### ISSUE TITLE
Shortcut-Bindings for map movement don't work with alphabetical keys anymore

### ISSUE THREAD

**Issue by MaximilianBottin** [OpenRCT2/OpenRCT2#14138]
**OS:** Windows 10
**Version:** 0.3.2
**Commit/Build:** c9ca066 on develop

I had my shortcut keys for map movement to wasd for easy of use. However those keystrokes aren't recognized anymore for map movement in this version of the game. Only keys like up, down, left, right and the numblock keys can be used (as far as I've tried them out) if I set any alphabetical key from the keyboard no action will be performed after pressing the assigned key.

**Steps to reproduce:**
1.  Open the settings panel to set the shortcuts for map movement to any alphabetical keys (like w for up, a for left, s for down and d for right)
2. The shortcut keys will be set, however nothing happens when pressing those keys

**Comment by IntelOrca** [comment]
Thanks, I will merge this issue with #14140.
