### ISSUE TITLE
Attractions in my Own Scenaios can´t be used

### ISSUE THREAD

**Issue by LukasDO665** [OpenRCT2/OpenRCT2#14143]
Hello,
I need help! I started to use OpenRTC2 and i created an scenario. And when you create an scneraio you can choose which attractions you want to use. But after i created and saved the scenario I wanted to play it. But after I wanted to build some rides i see only the half of my choosen rides. The Majority of the rides are added from OpenRTC2, but there are also rides from Rollercoaster that can´t be used or are not showen up.
Please Fix this!

**Comment by telk5093** [comment]
Did you move up the selected rides in the invention list window? Upside is invented list and downside is a list that should be invented during the game.

**Comment by LukasDO665** [comment]
Yes

**Comment by LukasDO665** [comment]
I moved all up

**Comment by Gymnasiast** [comment]
Please upload your save, and tell us which rides you cannot see.

**Comment by LukasDO665** [comment]
Should i send you a save of the landscape or the finished scenario file?

**Comment by Gymnasiast** [comment]
The finished scenario file. If you put it in a ZIP, you can attach it to a comment here.

**Comment by LukasDO665** [comment]
[Lukas Funland mit Geld V3.zip](https://github.com/OpenRCT2/OpenRCT2/files/6021140/Lukas.Funland.mit.Geld.V3.zip)

**Comment by LukasDO665** [comment]
i send you the list of the rides later. It is too much to send it fast

**Comment by Gymnasiast** [comment]
You don't necessarily need to list all of them, if there are so many. You can just list a few (e.g. 3 to 5).

**Comment by LukasDO665** [comment]
All the hires for exaple jetskis, boats and so on. And the Coaster fromt the OpenRTC2 who are added

**Comment by LukasDO665** [comment]
for example the B&M Coasters

**Comment by IntelOrca** [comment]
@LukasDO665 if you build a boat hire, then click the vehicle tab, does it list jet skis and other vehicles?

**Comment by LukasDO665** [comment]
thx and what about the b&m wing coaster?

**Comment by LukasDO665** [comment]
yea now it list jetskis and others :)

**Comment by Gymnasiast** [comment]
@LukasDO665 The B&M Wing coaster is most likely listed under "Twister Roller Coaster".

**Comment by LukasDO665** [comment]
i didn´t see it there :(

**Comment by Gymnasiast** [comment]
Good! By the way, you can see what vehicles are grouped under a ride type by hovering it: 

![afbeelding](https://user-images.githubusercontent.com/1478678/108754063-c4360580-7545-11eb-8eb3-f1e3da14353f.png)

It will show them on the bottom, labelled "Available vehicles".
