### ISSUE TITLE
It is a trend of DMCA-blocking of free software competing the proprietary one in their closed ecosystem. You are one of the next targets.

### ISSUE THREAD

**Issue by KOLANICH** [OpenRCT2/OpenRCT2#14154]
https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md
https://github.com/github/dmca/blob/master/2021/02/2021-02-19-take-two.md

**Comment by duncanspumpkin** [comment]
Please don't spam our issue tracker keep to a single issue.

**Comment by KOLANICH** [comment]
It's a bit different issue trackers of a bit different orgs (you are subscribed to both). Anyway, now I am sure that the both orgs are notified about what is going on.

 I'm sorry for the disturbance.
