### ISSUE TITLE
Curved wall seems to be treated as tree in scenario editor

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#14155]
**OS:** Windows 10
**Version:** 0.3.2
**Commit/Build:** 18e8690

``Curved wall`` is placed everywhere in the scenario editor.
I didn't check the object's detailed spec but I think it is considered as a tree object.
But as I know, there are many objects that is treated as a tree even it is not look like a tree.
So I'm not sure it is solvable currently, but I write an issue since it seems that there is no such reported one.

**Steps to reproduce:**
1. Open scenario editor
2. Click "Forward to Next Step:" without (un)checking any items in Object selection window
3. Click [Map generation] button
4. Be sure that ``Place tree`` is checked.
5. Generate the map

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/10726524/108872056-23c30c80-763d-11eb-9749-87b92d39efa6.png)

**Comment by Gymnasiast** [comment]
>  But as I know, there are many objects that is treated as a tree even it is not look like a tree.

That is true for DAT objects, but everything in JSON objects (which includes all vanilla objects) has an explicit flag to say whether it is a tree or not. But the map generator uses a hardcoded list of trees anyway, so it's not that.

**Comment by Gymnasiast** [comment]
I cannot reproduce this bug. Are you using a build from .org/.io or did you build yourself?

**Comment by andrewsarnold** [comment]
I'm getting a very similar issue, but with a different scenery piece.

1. Open scenario editor
2. Go to "load landscape" and open workbench file (attached)
3. Open Map Generation, and select second or third tab
4. Check "Place trees"
5. When generated, some trees and also a bunch of Art Deco Inverted Corner Section pieces are placed
[Workbench.zip](https://github.com/OpenRCT2/OpenRCT2/files/6571186/Workbench.zip)

**Comment by Gymnasiast** [comment]
I have managed to reproduce this. Basically, it things object #0 is a tree, whatever is put there. By default, it’s the Aleppo Pine Tree, which is much less conspicuous.
