### ISSUE TITLE
Right and down arrow swapped

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#14184]
**OS: Windows 8** [e.g. Windows 10]
**Version: 0.3.2** [e.g. 0.3.2]
**Commit/Build: 693gce11d1eb2 (ce11d1e)** [e.g. 426e106]

In game, the right and down arrows are swapped. Pressing down moves the view right. Pressing right moves the view down.

**Steps to reproduce:**
1. Open game
2. Press right or down arrow

**Comment by IntelOrca** [comment]
I can not reproduce this. Can you please check your keyboard shortcuts and what they are set to?

**Comment by IntelOrca** [comment]
This was caused by the legacy shortcut import list being in an incorrect order. I have fixed it now, but you may need to now reset your keyboard shortcuts to fix it or manually correct the those specific bindings.

**Comment by Liampie** [comment]
Alright, thank you! I just manually fixed them and will tell others with the same problem to do the same if I hear about it again. :)
