### ISSUE TITLE
Creating new folder in save menu crashes game

### ISSUE THREAD

**Issue by Duvelthehobbit** [OpenRCT2/OpenRCT2#14198]
windows 10
v0.3.2-695-g314faa69c
314faa6

The issue is when you try and make a new folder in the save menu, the game crashes.

**Steps to reproduce:**
1. Go to the save game dropdown menu in game
2. Press the new folder button in game
3. The game crashes.

**Comment by James103** [comment]
Do you have the crash dump files? If you have them, can you please upload them here?
Alternatively, if you uploaded them to Backtrace, can you link the corresponding issue here?

**Comment by Duvelthehobbit** [comment]
Where do I find the crash dump files. I cannot find them in my Openrct2 folders.

**Comment by James103** [comment]
Can you reproduce this crash? (save game > press new folder button)
If so, when you get the crash window popup, can you click "Yes" to upload the files to Backtrace?

**Comment by Duvelthehobbit** [comment]
The crash is definitely reproducible. I do not get any window when it crashes. The game freezes and then closes.

**Comment by IntelOrca** [comment]
Crash dumps are saved in your OpenRCT2 user directory (Documents\OpenRCT2).
Find the latest .dmp file you have, zip it and then you can upload it here.

**Comment by jensj12** [comment]
[SaveDialogCrash.zip](https://github.com/OpenRCT2/OpenRCT2/files/6057386/SaveDialogCrash.zip)
Same problem has been reported [on the forums](https://forums.openrct2.org/topic/5537-crash-discovered/) and I followed those steps closely to create this dump (create new folder while saving track design).

**Comment by Duvelthehobbit** [comment]
I found it. I know why I couldn't find it. I was looking in the wrong place. I was expecting it to be in a log folder or something similar.
[1425c7f7-bb6a-4439-a46e-f9af2eb88a2d(314faa6_x86-64).zip](https://github.com/OpenRCT2/OpenRCT2/files/6057399/1425c7f7-bb6a-4439-a46e-f9af2eb88a2d.314faa6_x86-64.zip)

**Comment by Fred-1044276** [comment]
Do you have any plugins installed? They could be partly causing the crash.

**Comment by Duvelthehobbit** [comment]
no plug-ins installed. would have mentioned it in my original comment if I did.
