### ISSUE TITLE
Text on some windows sticks out of window and gets left behind on terrain

### ISSUE THREAD

**Issue by gbodLUL** [OpenRCT2/OpenRCT2#14206]
the words "queue time" being left behind
![image](https://user-images.githubusercontent.com/75824166/109437522-680a3000-79e2-11eb-8280-cb2a97276785.png)
game version 
![image](https://user-images.githubusercontent.com/75824166/109437540-7e17f080-79e2-11eb-8f21-c2cc628bd743.png)

**Comment by Fred-1044276** [comment]
I was gonna report on it, but you beat me to it. Anyway this bug is yet another likely regression.

**Comment by Gymnasiast** [comment]
Next time, do not remove the fields from the template. ESPECIALLY not the commit/build field. These are there for a reason.
