### ISSUE TITLE
TD4 imported>  colour bug.

### ISSUE THREAD

**Issue by Horsti12** [OpenRCT2/OpenRCT2#1420]
When you import a TD4 file in RCT2 than the track colour is in the TD4 file correct.
The colour is also correct in the preview window, before you build a ride.
When you build that ride than sometimes the colour changes in a other one.
I tested it and this wasn't so in the original RCT2

**Comment by Gymnasiast** [comment]
An example of a TD4 not imported correctly is the Steel Twister 1 design, which comes with RCT1.
It can also be downloaded here: https://drive.google.com/file/d/0BzdfIT8snZiGeDBHeWdzVnBQMjQ/view?usp=sharing

RCT1 preview:
![schermafdruk van 2015-06-22 10 31 57](https://cloud.githubusercontent.com/assets/1478678/8278229/22b396a6-18ca-11e5-83be-ce1197b78e10.png)

Built in RCT1:
![schermafdruk van 2015-06-22 10 33 19](https://cloud.githubusercontent.com/assets/1478678/8278233/276e6acc-18ca-11e5-9767-20197faeaa35.png)

OpenRCT2 preview:
![scr1](https://cloud.githubusercontent.com/assets/1478678/8278251/35825cc2-18ca-11e5-95a6-317e4e338583.png)

Built in OpenRCT2:
![scr7](https://cloud.githubusercontent.com/assets/1478678/8278269/47665060-18ca-11e5-96ab-da1a16274964.png)

**Comment by duncanspumpkin** [comment]
Is this a track from the expansion packs? The .TD4 format was modified for the expansions.
