### ISSUE TITLE
Multi-line notification messages show incorrect font in second line

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#14212]
**OS:** Windows 10
**Version:**  0.3.2
**Commit/Build:** c98746c

Any notification messages that show up with two lines (e.g. "New ride/attraction now available: Looping Roller Coaster", "20 tile maze has no path leading from its exit! Construct a path from the ride exit") show the bottom line in a different font from before.

**Steps to reproduce:**
1. Start up a new game or load a saved game in any scenario
2. Produce a notification message with two lines (i.e. research a new ride/attraction, open a ride that has no entrance/exit paths, have the park rating drop below 700 in scenarios where keeping it above 700 is required)
3. The second line of the notification message will be shown in a different font

**Screenshots:**
![Mirage Madness 2 2021-03-01 16-19-23](https://user-images.githubusercontent.com/61885939/109594654-091ee680-7ac8-11eb-868e-19bd7fc1c885.png)
![Mirage Madness 2 2021-03-01 19-12-54](https://user-images.githubusercontent.com/61885939/109594658-0ae8aa00-7ac8-11eb-93bc-e93f414b1a8e.png)

**Comment by YJSoft** [comment]
Possible duplication of #14135

**Comment by Gymnasiast** [comment]
@YJSoft No, that's another issue. This one is caused by https://github.com/OpenRCT2/OpenRCT2/pull/14189 , while #14135 predates that.

**Comment by Gymnasiast** [comment]
The DrawText calls in `https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2-ui/windows/News.cpp#L219` need to be amended to specify the small font.

Also, does this also affect the news ticker, or just the News window?

**Comment by Fred-1044276** [comment]
It affects both the news ticker and news window.
