### ISSUE TITLE
Add the volume button (ear icon) to the top line (as seen in RCT1)

### ISSUE THREAD

**Issue by Horsti12** [OpenRCT2/OpenRCT2#1421]
It would be great when you could add the ear icon to the top line to mute the game very fast and turn the sound on very fast.

**Comment by AaronVanGeffen** [comment]
I'd personally like to have a keyboard shortcut to do this. Not sure about the button, although that could be added as an option too, I guess.

**Comment by Horsti12** [comment]
![rct1 features for rct2](https://cloud.githubusercontent.com/assets/12634026/8279490/61581ba6-18d5-11e5-89c4-a76f30dabaf1.png)
I marked it with a blue arrow.

**Comment by IntelOrca** [comment]
I am against this, you can change it in options. Its not very common for games to have a mute button.
You can pause the game or minimise the game to mute if you need to listen to something in the background temporarily.

**Comment by pizza2004** [comment]
Eh, I would love it to be possible, but I'd hardly say it's necessary at all.  It was nice to be able to just mute the game if someone came in or something, without having to pause it, but at the same time it seems Chris didn't think it necessary.

I think a keyboard shortcut should be added, possibly with no default key, that you can use to mute and unmute the game.  That's a fair compromise.

**Comment by IntelOrca** [comment]
@pizza2004 why not just use the OS mute?

**Comment by pizza2004** [comment]
Yeah, that's always an option, but you might have notification sounds or other types of things you still want to be able to hear when you're muting the game.  I know I'd never personally want to mute the whole computer just to mute the game, or alternatively have to open the options and page through tabs to find it.  This is the kind of game where the casual player just leaves in running without paying close attention, and sometimes the sound is just really obnoxious.

**Comment by Patrik356b** [comment]
There is a per-application volume setting on Windows since 7 and probably
Vista too. I think there was a third party tool to get this feature on XP
as well.

And I think a mute button is unnecessary. However, a key setting might be a
nice idea, I.e. ctrl+m

**Comment by Nubbie** [comment]
Pull request #3359 closes this as it adds a mute shortcut to the game

**Comment by PFCKrutonium** [comment]
Personally I would love to have that old button back, if only as an option like Cheats and Debug.

**Comment by Horsti12** [comment]
Thanks for adding a shortcut, but a button is much easier because for people who not use shortcuts often don't know where to find them. I takes for more than a minute to find the menu were I can find all the shortcuts. A button is much easier, but the shortcut is also nice :D

**Comment by Horsti12** [comment]
I still want to see it in the game :)

**Comment by IntelOrca** [comment]
I am happy for someone to implement this now as its a highly requested feature.

**Comment by Horsti12** [comment]
Thanks for adding the mute button to openrct2
This issue can now be closed :)
