### ISSUE TITLE
When saving a screenshot or giant screenshot, place picture data on clipboard for immediate pasting to places like discord.

### ISSUE THREAD

**Issue by Zageron** [OpenRCT2/OpenRCT2#14226]
Would be very useful to be able to paste photo from the screenshot tool directly into places like github and discord.

Currently: Browse to file on disk, drag-and-drop.

**Comment by ocalhoun6** [comment]
Maybe this would be better as a plugin?

For other users, having the game overwrite their clipboard content might be unexpected and unwanted. I could imagine it being reported as a bug after going into effect.

**Comment by duncanspumpkin** [comment]
Agreed that this should be a plug-in and not part of the base game
