### ISSUE TITLE
Move the Gridlines on Land from the "options" menu to the "view options" menu

### ISSUE THREAD

**Issue by Horsti12** [OpenRCT2/OpenRCT2#1422]
Please move the "gridlines on land" from the "options" menu to the "view options" menu to have all view options on the same place.

**Comment by Horsti12** [comment]
![gridlines on landscape](https://cloud.githubusercontent.com/assets/12634026/8889593/a43ef258-32e0-11e5-89eb-cdb477945ba7.png)
Here is a picture for it.

**Comment by Gymnasiast** [comment]
I am not in favour of this. It gets turned on automatically when it's useful, and it's toggleable for the handful of people who want them permanently visible.

I am starting to sound like a broken record, but well: there is no point emulating every aspect of RCT1 just for the sake of it. This isn't remotely useful. You seem to consider RCT1's approach automatically superior to RCT2's, but I disagree, and I'm quite sure that applies to most contributors here.

**Comment by Patrik356b** [comment]
I agree with @Gymnasiast
