### ISSUE TITLE
Scenario names for the intro background screen

### ISSUE THREAD

**Issue by lode** [OpenRCT2/OpenRCT2#14234]
Is there a way to know which scenario is shown in the background on the intro screen when starting? I would love such an option since I'm often looking for inspiration of which scenario to play and when I see something that I like I'd like to play that one.

I also found https://github.com/OpenRCT2/OpenRCT2/issues/3207 which could help with choosing a scenario. But if that is still complex (the latest comment there was quite old) I can imagine adding a label with the scenario name in the intro screen is an easier one?

**Comment by duncanspumpkin** [comment]
The parks in the title screen aren't scenarios for most of them unless you mean the rct2 title screen.

**Comment by IntelOrca** [comment]
The RCT2 title screen is just one scenario. The RCT1 title screen however has a scene from most of the non-empty park scenarios. With some of the changes I am doing at the moment, a plugin could theoretically display this information on the title screen.

**Comment by jensj12** [comment]
You can open the title sequence editor (accessible through options) to see what scenarios and saves are used. You can even load the parks from there (including those from the OpenRCT2 sequence).

**Comment by lode** [comment]
Thanks for the input!
