### ISSUE TITLE
Park crashes after a few seconds

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#14239]
**OS:** windows 8
**Version:** 0.3.2]
**Commit/Build:** cea5fab

The following park crashes within seconds of opening the savegame. The park used to work before.

Download link for savegame:
https://www.nedesigns.com/park/3324/h2h7-r1-circus-circus-adventuredome-atlantic-city/download/

**Steps to reproduce:**
1. Open savegame
2. Wait

edit: I was still on latest release version I realised, but after I update my game the problem persists.

**Comment by James103** [comment]
The game crashes after exactly 638 ticks after loading the savegame. The dump is at #14240.

**Comment by Gymnasiast** [comment]
This is caused by a large scenery object that points to an invalid index - basically, what I was talking about the other day on Discord.
