### ISSUE TITLE
Recen Messages on the top bar and the bottom bar [RCT1]

### ISSUE THREAD

**Issue by Horsti12** [OpenRCT2/OpenRCT2#1423]
Please make a option to add the "recent messages" to the top bar like the option to add the research and the finances.
It is located in the original RCT on the right side, the last button.
Please also make a option to add the "recent messages" on the bottom of the page between the guests and the date. (Currently it only appears when you go t a new messages.

Plese make this only as a option!

Thanks!

**Comment by AaronVanGeffen** [comment]
Currently, you can use a keyboard shortcut ('M' by default) to open the list of recent messages. I'm not sure a button would add much value, but that's not up to me to decide.

**Comment by Gymnasiast** [comment]
Having a button in the toolbar as an option (like finance) would be ok, but I don't see the point in reintroducing the useless grey area on the bottom of the screen, even as an option.

**Comment by Horsti12** [comment]
Sometimes you are in RCT2 a little bit slow when you want to open the new message and than you click on nothing.
In RCT1 you than also come to the recent messages.

I just want that I can make that OpenRCT2 look like RCT1 , because I'm so a big fan of RCT1 :D

**Comment by Horsti12** [comment]
![rct1 features for rct2](https://cloud.githubusercontent.com/assets/12634026/8279490/61581ba6-18d5-11e5-89c4-a76f30dabaf1.png)
I marked it with a green and orange arrow.

**Comment by Vijfhoek** [comment]
Fairly sure you can see the recent messages by clicking on the date, so I
don't see the added value of the button and the bar.

**Comment by Horsti12** [comment]
I know that but it's not RCT1 Style :P

**Comment by Vijfhoek** [comment]
...that's because this is RCT2, why would you make a newer game like an
older game when there aren't any advantages to it?

**Comment by Horsti12** [comment]
It would be just as a option, nothing more.
I prefer the original style a little bit more.
OpenRCT2 also already a RCT1 and RCT2 combination instead of only RCT1.
Only some little changes and OpenRCt2 can look like the original RCT1

**Comment by Horsti12** [comment]
Not yet closed, because the bottom button isn't there yet and btw thanks for add it to the top bar.

**Comment by Gymnasiast** [comment]
Look, most of us don't see the point of having a useless grey bar at the bottom of the screen just for the sake of imitating RCT1. It isn't remotely useful.

**Comment by Horsti12** [comment]
it would be just as a option.
I more used the big grey bar instead of the button on the top bar.
Sometimes it's  little bit anoying when you click on the news and than it go away and than you click on nothing.
In rct1 you clicked then on the news button and than you saw the latest news.

I not thing that this is need a lot of work and it would be just a option.

**Comment by AaronVanGeffen** [comment]
Which is why you now have the option to either click the button in the top bar, or press a hotkey.
