### ISSUE TITLE
Allow more than 64 widgets per window

### ISSUE THREAD

**Issue by Sadret** [OpenRCT2/OpenRCT2#14235]
Currently, only 64 widgets per window are fully supported. After adding more widgets to a window, enabling and disabling of widgets starts to make problems.
This issue asks to fix that.

**Comment by IntelOrca** [comment]
This is a general restriction with the window system rather than plugins.

**Comment by tupaschoal** [comment]
We should probably prevent plugins from going over in the meantime, no?
