### ISSUE TITLE
Ability to exceed Max Staff in rct1 scenarios

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#14247]
**OS:** unknown
**Version:** unknown
**Commit/Build:** unknown

I've seen a report from a few days ago in a discord channel that you can exceed 200 staff on rct1 scenarios. This was on a develop version from 1 week ago. Will try get more info from the user.

>hmMM apparently if I load an RCT1 scenario I could get more than 200 staffs... but nuber varies. Diamond Heights gives me 204, Alton and Blackpool gives me 209...
>so the pattern is, the max staffs on the RCT1 parks is: the amount of staffs that's already there + 200
**Steps to reproduce:**
1. 
2.

**Comment by James103** [comment]
From my testing:

**OS**: Windows 10
**Version**: 0.3.2
**Commit/Build**: b179f6e

When loading an RCT1 scenario, the effective max number of staff appears to be equal to the number of staff in the RCT1 scenario, plus 200. This likely means that the number of staff (the number used to check against the limit of 200) is set to 0 if you load an RCT1 scenario, regardless of the actual number of staff.

To reproduce:
1. Load any RCT1 scenario with staff. For example, Diamond Heights with 4 staff.
2. Hire 196 more staff (if you loaded Diamond Heights), or enough to get you to 200 total staff.
3. Hire some more staff. The extra staff will be successfully added, until you get to (200 + initial staff count) staff.

**Comment by Gymnasiast** [comment]
@James103 All of that was already in the opening post...

**Comment by giraty** [comment]
> I've seen a report from a few days ago in a discord channel that you can exceed 200 staff on rct1 scenarios. This was on a develop version from 1 week ago. Will try get more info from the user.

That was me. Bit late from myself to report but here you go.
**OS**: Windows 10
**Version**: 0.3.2
**Commit/Build**: [8e414a9]

> From my testing:
> 
> When loading an RCT1 scenario, the effective max number of staff appears to be equal to the number of staff in the RCT1 scenario, plus 200. This likely means that the number of staff (the number used to check against the limit of 200) is set to 0 if you load an RCT1 scenario, regardless of the actual number of staff.
> 
> To reproduce:
> 
> 1. Load any RCT1 scenario with staff. For example, Diamond Heights with 4 staff.
> 2. Hire 196 more staff (if you loaded Diamond Heights), or enough to get you to 200 total staff.
> 3. Hire some more staff. The extra staff will be successfully added, until you get to (200 + initial staff count) staff.

What James103 wrote is what exactly happened, same reproduce steps. 
Here is my save file of Alton Towers with 233 staffs.
![unknown](https://user-images.githubusercontent.com/8456673/110229790-8621e400-7f3e-11eb-9412-b4a79f90fb6a.png)

I haven't tried what would exactly happen if a park with >200 guest keep being played would act, though bugs and error is expected.

[https://cdn.discordapp.com/attachments/518645544239890433/817987850539892756/Alton_Towers_233staffs.sv6](url)

**Comment by Gymnasiast** [comment]
The problem is that the mechanism relies on gStaffModes to contain correct information, but this is not correctly imported from SV4 files. I have created a fix, but this will only work in new saves. To fix old affected saves, you need to sack all staff and rehire them.
