### ISSUE TITLE
Replace font size formatting tokens with adjusted DrawText calls

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#14253]
These were mostly made obsolete by https://github.com/OpenRCT2/OpenRCT2/pull/14189 .

This includes the tokens in the translation files and the support for these tokens in our 

However, some of the places that call these strings need to be adjusted to instead pass a FontSpriteBase parameter.

**Comment by geoff-B** [comment]
I will give this one a go.

**Comment by Gymnasiast** [comment]
Great!

You _might_ run into problems with guest thoughts, though. But let me know if that's the case.

**Comment by geoff-B** [comment]
@Gymnasiast You were right, removing SMALLFONT in the localization files makes all the thoughts become medium font size.

**Comment by Gymnasiast** [comment]
That's expected, you will need to modify some calls:

> However, some of the places that call these strings need to be adjusted to instead pass a FontSpriteBase parameter.

**Comment by geoff-B** [comment]
TO DO:

- [ ] Graph labels (STR_RIDE_STATS, STR_FINANCES_FINANCIAL_GRAPH)
- [ ] STR_STRING_TOOLTIP
- [ ] STR_SMALL_WINDOW_COLOUR_2_STRINGID (5138)

**Comment by geoff-B** [comment]
Pretty much done with all of them, except for some unused strings listed above that I don't know what to do with, and some non-standard cases:

Non-universal {SMALLFONT} calls (i.e. not used for all languages):

- [ ] STR_FIRE_STAFF_ID = 1711 (Russian) - **Crashes when {smallfont} is removed**
  ![image](https://user-images.githubusercontent.com/38046772/110274567-54376e80-7f8c-11eb-8794-0b6fbb9ff3be.png)

**Comment by geoff-B** [comment]
@Gymnasiast What should be done with those two Russian strings and the strings that are not used in the code (1926, 2681 and 5301)?

**Comment by Gymnasiast** [comment]
The Russian strings needed to use {WINDOW_COLOUR_1} instead of {SMALLFONT}. I just corrected that in the Localisation repository.

For the other strings: strings 1926 and 2681 can be removed, but I'd like to restore 5301. However, you can safely take off the {SMALLFONT}{BLACK} parts of that.
