### ISSUE TITLE
[Plugin] Cannot modify the coordinate and size of the viewport

### ISSUE THREAD

**Issue by nExmond** [OpenRCT2/OpenRCT2#14264]
**OS:** Windows 10
**Version:** 0.3.2
**Commit/Build:** 212a0c1

The coordinate and size of the viewport are not updated. In the 03d6771 commit-based build, the coordinate and size of the viewport widget and viewport are updated, but in the latest commit-based build, nothing happens

The coordinates and size of the current viewport are calculated using the coordinates and size of the viewport widget.
```
//Corrected incorrectly entered attribute name.
//x -> left, y -> top, width -> left, height -> right
{
  //...
  left: ViewportWidget.x,
  top: ViewportWidget.y,
  right: ViewportWidget.x + ViewportWidget.width,
  bottom: ViewportWidget.y + ViewportWidget.height,
  //...
}
```
It seems that the display method of the viewport has changed since CustomWidget was added.

**Steps to reproduce:**
1. Add a viewport to window and show.
2. Change the position and size of the viewport.

**Screenshots / Video:**
Before changing the coordinate and size of the viewport
![Viewport_0_v0 3 2-664-g03d6771cc (03d6771 on develop)](https://user-images.githubusercontent.com/33048431/110243373-6ff74080-7f9d-11eb-8b52-549978eaf719.png)
03d6771 | After changing the coordinate and size of the viewport
![Viewport_1_v0 3 2-664-g03d6771cc (03d6771 on develop)](https://user-images.githubusercontent.com/33048431/110243370-6ec61380-7f9d-11eb-93c4-3fd4b459c443.png)
212a0c1| **After changing the coordinate and size of the viewport**
![Viewport_1_v0 3 2-754-g212a0c1e4 (212a0c1 on develop)](https://user-images.githubusercontent.com/33048431/110243372-6f5eaa00-7f9d-11eb-96d1-ced634e0c4ee.png)

**Comment by IntelOrca** [comment]
Can you upload your test plugin script please?

**Comment by nExmond** [comment]
You can test it here. https://github.com/nExmond/openrct2-stack-ui/tree/temp/test

**Comment by nExmond** [comment]
> Can you upload your test plugin script please?
You can test it here. https://github.com/nExmond/openrct2-stack-ui/tree/temp/test

**Comment by nExmond** [comment]
> Can you upload your test plugin script please?

You can test it here. https://github.com/nExmond/openrct2-stack-ui/tree/temp/test
