### ISSUE TITLE
Title logo render problems

### ISSUE THREAD

**Issue by Phyxion** [OpenRCT2/OpenRCT2#1426]
This only happens with the first scene/background, as soon as it switches to another scene/background it does render correctly. This is at 1440p resolution.

![Bug](http://i.imgur.com/pvC8X5G.jpg)

**Comment by PFCKrutonium** [comment]
I want to say it may be related to #1400

**Comment by IntelOrca** [comment]
Does this still happen?

**Comment by Phyxion** [comment]
Just tried the latest build and I cannot reproduce it anymore.
