### ISSUE TITLE
Bottom of cheat window gets stuck when zoomed out

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#1428]
Open any scenario zoom all the way out open the cheat window and move the camera up. You will notice that the bottom of the window get stuck.
![screen shot 06-22-15 at 05 48 pm](https://cloud.githubusercontent.com/assets/1381723/8287365/45d6f7e4-1907-11e5-850f-a738c3084e61.PNG)

**Comment by Phasedetect** [comment]
It's not just when the view is zoomed all the way out, it has happened to me sporadically for a while now.

**Comment by chrismilne300** [comment]
Ah yeah same here, I've never noticed until I zoomed out

**Comment by Gymnasiast** [comment]
Seems to be solved by #1441.
