### ISSUE TITLE
Allow using early scenario completion in multiplayer

### ISSUE THREAD

**Issue by MaximilianBottin** [OpenRCT2/OpenRCT2#14296]
**OS:** Windows 10
**Version:** 0.3.2 develop
**Commit/Build:** f0dc28e

When playing a game in multiplayer, the option "allow early scenario completion",
doesn't work as expected.
It's turned on for me and all of my friends playing with me and despite that it won't trigger the scenario completion.

- [x ] Specific to multiplayer?

**Steps to reproduce:**
1. Launch OpenRCT2 on two different machines
2. Activate "allow early scenario completion" in the Options-Menu on both of these machines
3. Start a server on one of the machines (Forest Frontiers would be a prime candidate) and let the other one join
4. Reach the goal of the scenario before the deadline and wait for the day to advance to the next one

**Comment by duncanspumpkin** [comment]
I mean it was purposely disabled. Its not that it doesn't work.

**Comment by MaximilianBottin** [comment]
Very true, I think I should have rephrased my issue a bit. 

Because I follow the github commits and discord community I know that the feature got turned off (Which was my main motivation for implementing a solution where it's not necessary to turn the feature off completely).

My intention when opening the issue (and why I phrased it like a bug) was because a newcomer who just downloaded the game, would probably be confused that the option exists, works in singleplayer but not in Multiplayer.
There is no disclaimer about the option only working in singleplayer when toggling the setting or a tooltip that explains how this setting behaves in multiplayer.

**Comment by IntelOrca** [comment]
@MaximilianBottin that's fine. Thank you for taking the time to investigate and submit a pull request to resolve it.

**Comment by Margen67** [comment]
#14225
