### ISSUE TITLE
Peeps refuse to enter the park if "No Money" cheat active.

### ISSUE THREAD

**Issue by Phasedetect** [OpenRCT2/OpenRCT2#1430]
To recreate:

-Open a scenario
-In "Park Parameters" cheat, activate the checkbox for "No Money"
-Use the cheat "Open Park" (park defaults to closed once no money is selected)

**Comment by ramonschriks** [comment]
vv

**Comment by ThomasdenH** [comment]
Could this be due to the way peeps calculate whether the entrance fee is reasonable?

**Comment by Gymnasiast** [comment]
It might be that the prices are still set and somehow checked (I vaguely remember something in the documentation of 8 cars per trainer saying that much).

**Comment by IntelOrca** [comment]
Please provide a saved game where this is apparent.

**Comment by Gymnasiast** [comment]
Open Six Flags Belgium, click Cheats -> Park -> Park parameters and click the box for No money.
Then wait for new guests or simply click Large Tram. The guests will refuse to enter the park.

**Comment by sjoerddebruin** [comment]
Yup, that would be it. If you do that, maybe a confirmation pop-up would be handy then. So people know that their existing values will be changed.

**Comment by IntelOrca** [comment]
sub_693C9E needs to be reversed to have guests ignore park entrance fee if no money is active.

**Comment by Gymnasiast** [comment]
There's probably more than just the entrance fee. I think the ride and shop prices might trigger the same bug.

**Comment by IntelOrca** [comment]
Yes, I think its in the same function. Its a core peep function, a lot of logic lies in this - it would be a nice one to have reversed at some point.
