### ISSUE TITLE
Track design can be placed even if scenery is outside of park boundaries

### ISSUE THREAD

**Issue by frutiemax** [OpenRCT2/OpenRCT2#14311]
Windows 10
0.3.3
Commit cd9873a78de5191d9440608b70448f04f344464d

The track design can be placed even if some scenery is out of the park boundaries. When the track design is placed, any scenery outside of the park will not be put in place.

![bug2](https://user-images.githubusercontent.com/12629817/111051989-2c7d5600-8425-11eb-9201-35f8b8f190fe.PNG)

**Comment by duncanspumpkin** [comment]
Yes this is a feature.
