### ISSUE TITLE
Crash if try to rename Air Powered Vertical Coaster in CJK

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#14315]
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** 72b6160

When I try to rename Air Powered Vertical Coaster(``에어 파워드 버티컬 코스터``) in CJK language, it crashes.
Maybe @AaronVanGeffen can reproduce it.

It is possible if I (1) change language into English, (2) rename it (3) and re-change into Korean again

**Steps to reproduce:**
1. Change language into CJK, in my case, Korean.
2. Build an Air Powered Vertical Coaster as default name
3. Check that its name is default one (eg. ``에어 파워드 버티컬 코스터 1`` in Korean)
3. Try to rename it

**Comment by Lastorder-DC** [comment]
Overflow occurs inside of `gfx_wrap_string`
https://github.com/OpenRCT2/OpenRCT2/blob/2c3c014f14bf71bb164fb39b3479770af92d5129/src/openrct2/drawing/Drawing.String.cpp#L191

**Comment by Gymnasiast** [comment]
It doesn't crash for me, it freezes.

Also, my debugger points to Drawing.String.cpp:843 instead of 191.

**Comment by Gymnasiast** [comment]
The problem might be that it tries to truncate the string to 32 bytes in TextInput.cpp:
```
    void SetText(std::string_view text, size_t maxLength)
    {
        _buffer = text;
        _buffer.resize(maxLength);
        _maxInputLength = maxLength;
        gTextInput = context_start_text_input(_buffer.data(), maxLength);
    }
```

But by doing so, it lands in the middle of a UTF-8 sequence. (EC 8A A4 gets truncated to EC 8A).
