### ISSUE TITLE
Enable continuous circuit mode for Inverted Shuttle and Inverted Vertical Shuttle

### ISSUE THREAD

**Issue by Phasedetect** [OpenRCT2/OpenRCT2#1431]
Not sure how hard this is, but would be nice eventually.

**Comment by Gymnasiast** [comment]
It's incredibly easy, actually. It's a matter of editing a table. I will do that unless there is a good reason not to.
I know what the 'Inverted Vertical Shuttle' is, but what do you mean with 'Inverted shuttle'?

**Comment by Phasedetect** [comment]
Inverted Shuttle is the one that has forward and backwards facing seats.

**Comment by Phasedetect** [comment]
![screen shot 2015-06-22 at 14 47 36](https://cloud.githubusercontent.com/assets/7439907/8289956/ac0d19d6-18ed-11e5-84c0-991b8c63f44d.JPG)

**Comment by Phasedetect** [comment]
The one hangup I could potentially see is that they lack block brakes, because they never were meant to do continuous circuit. If one put them in the same track type as Compact Inverted coaster, then they might be able to be easily implemented.

**Comment by PFCKrutonium** [comment]
Cheats or Options, there is an option to do that ;)

**Comment by Phasedetect** [comment]
@PFCKrutonium Ah, so I see that the three share a ride type. I'm looking in ride_data.c, but the only one I can find in there is Compact Inverted Coaster, not the other two. Would I have to add them to the list, or am I missing something?

**Comment by Gymnasiast** [comment]
Have you checked 'Show all vehicles sharing a track/type' in the Options window?

**Comment by Phasedetect** [comment]
I have that checked. The issue is that if you change the vehicle type, the ride mode options change. Compact Inverted Coaster only has continuous circuit and block section, and the other two vehicle types only have reverse inclined.

**Comment by Gymnasiast** [comment]
Hm, I have investigated, and it looks like both shuttle types override the default modes (which they can, provided it's more restrictive than the default). I'm currently working on a way to make rollercoaster building more RCT1-like, in which I'll include ride modes.

**Comment by Christipher** [comment]
you mind showing a picture with all three side-by-side - this would actually help us figure out what exactly is going on - it could actually be something simple or it might be as complex as having to draw new sprites.... I need some better visuals.  Also, mind showing a pic of the compact inverted coaster track in the middle, and the inverted shuttles on either end of the compact inverted coaster track?  This would actually help in determining what needs to be done...

**Comment by Gymnasiast** [comment]
@Christipher : What you're saying has nothing to do with the issue. We already know what's going on. It's a matter of finding the responsible code.

**Comment by Gymnasiast** [comment]
The point is that the vehicles can set some flags that specify that some operating modes must be hidden. I adjusted the 'Show all operating modes' cheat to ignore those flags when it's turned on.

In short: you will be able to use continuous circuit on the inverted shuttle once #2247 is merged.
