### ISSUE TITLE
Track Design Manager window can be closed to allow for glitchy land modifications in the background map

### ISSUE THREAD

**Issue by Basssiiie** [OpenRCT2/OpenRCT2#14316]
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** 7793f4c

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open the Track Design Manager (not the Track Designer) under the Toolbox.
2. Exit out of the window.
3. Do weird things like land modifications on the background map.
4. There's also a button for paths, but it refuses to open any path window.

**Screenshots / Video:**
![Unnamed park 2021-03-14 13-57-45](https://user-images.githubusercontent.com/20048660/111069634-42932100-84ce-11eb-9a2a-ee7bc81ded5a.png)
![Unnamed park 2021-03-14 13-55-41](https://user-images.githubusercontent.com/20048660/111069635-44f57b00-84ce-11eb-8be1-61c7abab6347.png)

**Comment by Broxzier** [comment]
Closing the window should bring you back to the main menu.
