### ISSUE TITLE
Track files installed in Gameroot/Tracks show up twice

### ISSUE THREAD

**Issue by Tahvohck** [OpenRCT2/OpenRCT2#14314]
**OS:** Windows 10
**Version:** 0.3.2
**Commit/Build:** 245c967

Track designs installed in `gameroot/Tracks` show up in the design picker (all iterations) twice. At first I thought this might be related to the issues I had in #14284 but testing shows this is reproducible even with brand new designs.

**Steps to reproduce:**
1.  Save a new track design to `customcontent/track`
2. Relocate the track file to `gameroot/Tracks`
3. Restart the game.
4. Load the track Designs manager and select the relevant ride type.

**Comment by duncanspumpkin** [comment]
Your steps to reproduce consist of duplicating a file and then the issue is that the file is duplicated. Not sure what you would expect to happen.

**Comment by Tahvohck** [comment]
I said "relocate", not "copy". The file gets removed from the custom content folder during the process.

**Comment by Tahvohck** [comment]
Closing this. I don't know WHY it was happening with the GOG installer version, but I've confirmed it doesn't happen when using the offline installer and innoextract, which is good enough for me to consider it "Not OpenRTC2's fault".
