### ISSUE TITLE
Glitched graphics

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#14319]
**OS:** Windows 7
**Version:** 0.3.3-13-4ac3fd4
**Commit/Build:** 4ac3fd4

![image](https://user-images.githubusercontent.com/4167951/111193210-4f784900-8590-11eb-9e61-3d53f868846f.png)
![image](https://user-images.githubusercontent.com/4167951/111208119-c0276180-85a0-11eb-8fae-7ec7e737aa7a.png)

For the past few updates I've seen cavalcades of glitched graphics scattered about the occasional multiplayer game (especially in station platforms) and in this case scenarios from the original RCT1's expansion packs.

Any way to resolve this? Or is this something internal with the game?

**Comment by Fred-1044276** [comment]
v0.0.0? Shouldn't you be on v0.3.3 by now?

**Comment by Superjustinbros** [comment]
> v0.0.0? Shouldn't you be on v0.3.3 by now?

Yes, I goofed and typed it with all 0's. It should now be corrected.

**Comment by Gymnasiast** [comment]
I think your issue is having a csg1i.dat and csg1.dat in your RCT1 folder that are mismatched. Can you provide the file sizes of both?

Also: do you, by any chance, also have crashes like these: https://github.com/OpenRCT2/OpenRCT2/issues/14329 ? (And is your home directory `C:\Users\user`?)

**Comment by Superjustinbros** [comment]
I checked; csg1i.dat is 1,093 kb and Csg1.dat is 22,622 kb.
And yes those are the crashes I have been experiencing.

**Comment by Gymnasiast** [comment]
Ah yeah, that's the problem: your CSG1.DAT should be about 39 MB, not 22. You probably combined a CSG1.DAT from the base game with the CSG1i.DAT from Loopy Landscapes.

Copy the CSG1.DAT from LL to your RCT1 folder and your problem (and crashes) should be solved.
