### ISSUE TITLE
Sandbox mode reducing map size causes game to freeze

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#1432]
Enable sandbox mode and keep reducing the map size eventual the game will freeze, on some levels it freezes after the first click
![screen shot 06-22-15 at 06 47 pm](https://cloud.githubusercontent.com/assets/1381723/8288661/7ca1e3da-190f-11e5-8279-d529556fe27d.PNG)

**Comment by Phasedetect** [comment]
Not surprising, that function really messes with the map in ways that probably aren't compatible with normal play mode.

**Comment by Gymnasiast** [comment]
Exactly. That's also why it's turned off when you exit OpenRCT2. RCT2 was never designed to handle these kinds of things, and you can break your game with it.

However, I do think it should be fixed anyway, though it might take some time, considering the reasons I mentioned

**Comment by rctdude2** [comment]
It may have something to do with scenery that would end up partially in the void. Increasing the map size works fine, this only occurs when decreasing map size.

In "Africa - Victoria Falls" (the scenario in OP's screenshot), if you go directly right when you first load the scenario, the tree at the edge is both inside and outside the park, and is also at the map boundary (meaning if you decrease the map size, it would technically be partially in the void.).

It should also be noted that if you open the scenario mentioned above in the original game and use 8cars to own all land (under the Park menu), the crash still happens even though the tree is fully in the park's ownership. This makes me think that it has to do with the scenery object being partially in the map and partially in the void.

A possible fix would be to forcibly delete any large, multiblock scenery objects when resizing the map (in a similar fashion to what the scenario editor does, as park ownership is ignored there and there is no issue with resizing). Rides and attractions should be taken into account as well (possibly just prohibit the map from being resized down so the attraction can't be partially in the void).

(Apologies for the long comment, I wanted to be thorough.)

**Comment by IntelOrca** [comment]
Does it crash if you do this in the scenario editor? I remember handling large scenery objects in the map resize function.

**Comment by rctdude2** [comment]
Nope, it works just fine in the scenario editor (which was why I recommended making it work like that where it just deletes the object that would be in the void).

**Comment by IntelOrca** [comment]
OK, its crashing deep within original code... although that is only because 0x0068D6B4 hasn't been reversed yet. Otherwise the functions that its getting stuck in have already been reversed.

**Comment by FlukiestEmperor** [comment]
The goto statement in sub_68AE2A() in map.c causes an infinite loop

https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/world/map.c#L4189

**Comment by Gymnasiast** [comment]
It seems not to crash when I remove the large objects on the edge of the map first.

**Comment by gDanix** [comment]
I'm currently working on this. Probably this evening I'll have a fix for this issue
