### ISSUE TITLE
Guest blocking ride entrance after ride price changed to be unaffordable

### ISSUE THREAD

**Issue by galfisk** [OpenRCT2/OpenRCT2#14337]
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** 3f65f28

When a guest is waiting at the entrance for another guest, at a ride that takes 2 people per vehicle, and while he waits the ride price changes to something he can't afford, he'll turn around but not leave the station, continuously check his wallet, and "I can't afford [ride name]" will flicker in his "recent thoughts". The guest will prevent others from entering the ride.

I first saw this when using the plugin "Ride price manager" on 0.3.3, but as described seen below, it can be reproduced without the plugin. I never encountered the isue using the plugin on 0.3.2 during many hours of play, but twice on 0.3.3 within ~10 hours, so it's probably new.

- [ ] Reproducible in RCT2 (vanilla)? 
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Start a new level
2. Set initial cash to something low in order to get poor guests in
3. Build a boat hire or dinghy ride (issue confirmed on these two, but probably works for ghost train, car ride and others), and set a low ticket price
4. Wait until one guest stands inside the station, awaiting another in order to fill up a vehicle/boat
5. Change ride price to something this guest can no longer afford
6. Wait a bit, issue doesn't crop up immediately. I don't know if it's triggered by a rich guest wanting to get on, by a time delay, or something else, but it started within a minute for me in the saved file

**Screenshots / Video:**
![Ride price bug](https://user-images.githubusercontent.com/31153158/111371425-ab7ac480-8699-11eb-89e0-30beb85189e6.png)

**Save game:**
[Ride price bug.zip](https://github.com/OpenRCT2/OpenRCT2/files/6151872/Ride.price.bug.zip)

**Comment by Fred-1044276** [comment]
Does this happen with stalls as well?

**Comment by galfisk** [comment]
I don't think it can, since people don't stop there for any length of time. I don't know how I would time such a test.

**Comment by Fred-1044276** [comment]
I meant just shops and stalls in general

**Comment by galfisk** [comment]
I don't know how you'd trigger the issue in a shop or stall, since guests don't spend any appreciable amount of time there.
It could possibly work on bathrooms, but I haven't tested.
