### ISSUE TITLE
Peep spawn point does not get set using sandbox mode.

### ISSUE THREAD

**Issue by Phasedetect** [OpenRCT2/OpenRCT2#1433]
Setting new peep generation points does not work during normal play mode.

**Comment by clxe** [comment]
Turns out that you can _unset_ spawn points in sandbox mode, just not set them.

Also, I now have a park that only has one spawn point, which leads into a piece of scenery. It's lonely.

**Comment by Gymnasiast** [comment]
In the current version you can set them, but they aren't visible.

**Comment by Patrik356b** [comment]
They should be visible in sandbox mode I think.

**Comment by duncanspumpkin** [comment]
Can't be easily done until the surface drawing functions are done.
