### ISSUE TITLE
join_server uses default_port from config

### ISSUE THREAD

**Issue by CorySanin** [OpenRCT2/OpenRCT2#14330]
**OS:** Windows 10 / Manjaro Linux
**Version:** 0.3.3
**Commit/Build:** 4ac3fd4

The config property `default_port` does exactly what the name implies and changes the default port to use when no port is specified when connecting. It's also the default port used when starting up a multiplayer server. I don't believe the former is what the user would expect. So while I admit that this is probably a case of being a feature not a bug, I would still like to propose a change to its use.

I discovered this functionality not by looking through the config file or the codebase, but by failing to connect to a local server that I added to my server list. I was perplexed as to why I could connect to it using the local discovery entry in the browser, but not the server I entered manually. Then I opened the Start Server window and realized that the last server I ran was on a port other than 11753. Only then did I finally realize that the server port is the same port used for connecting to hosts that don't have a port specified.

Joining a server without a port specified should always default to 11753. `default_port` should only be used when spinning up a server.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**
1. Start a server on the standard port 11753
2. On a separate client, change the default_port to something else (this can be done through the Start Server screen)
3. On this second client, add the server to the server browser without specifying a port
4. Try to connect

**Comment by IntelOrca** [comment]
@CorySanin thanks, I would say this is a bug too. Could you submit a pull request?
