### ISSUE TITLE
Crash when typing too long ride/stall name

### ISSUE THREAD

**Issue by MaximilianBottin** [OpenRCT2/OpenRCT2#14353]
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** a018787

When trying to change the name of a ride/stall the game will crash if the name gets too long.
The crash occurs the moment the letter a letter is typed.
For example when naming a ride "Lorem Ipsum Lorem Ipsum " the game will crash the moment
I try to moment I type the 'L' of the next Lorem.

However, it won't happen with some rides or stalls like the classic mini coaster (sorry I had to improvie the translation I only know the german name "Klassiche Miniachterbahn")

**Steps to reproduce:**
1.  Start a new game in the electric fields scenario
2. Change the name of the Balloon Stall if enough letters are typed in the game will crash

**Dump file**
[556a97fd-da55-4991-976f-eb5faaaff7b4(a018787_x86-64).zip](https://github.com/OpenRCT2/OpenRCT2/files/6172243/556a97fd-da55-4991-976f-eb5faaaff7b4.a018787_x86-64.zip)

**Comment by duncanspumpkin** [comment]
Did this happen before https://github.com/OpenRCT2/OpenRCT2/commit/0957542503f425b7b61aabbc4894afc7205bab1d

**Comment by MaximilianBottin** [comment]
I just tried the same steps with the parent commit which was https://github.com/OpenRCT2/OpenRCT2/commit/645685de1862d9f555eae82faefbc04f2850ae0b

It worked with this parent commit but the game crashed with the https://github.com/OpenRCT2/OpenRCT2/commit/0957542503f425b7b61aabbc4894afc7205bab1d commit
