### ISSUE TITLE
Add a 'Follow Train / Guest' function

### ISSUE THREAD

**Issue by fjack125** [OpenRCT2/OpenRCT2#14370]
In Roller Coaster Tycoon Classic, there is a feature to follow the train the user has selected in the ride window. The main viewpoint then focusses on the train itself and also informs the user on what the coaster train is doing (such as 'Departing Station', 'Travelling at' etc.) as well as the ride's current speed.

This feature has been added to OpenRCT's sibling project OpenLoco, which could make implementing the code a bit easier.

Main Features:

- Implement the feature for the main viewpoint to follow a select coaster train.
- Potentially add the feature to be able to follow peeps on the main viewpoint?
- Potentially add the feature to have the train / guest's information at the bottom of the screen?

**Comment by ocalhoun6** [comment]
The title screen seems to already be able to do this, so maybe you could borrow some code from there.

**Comment by jensj12** [comment]
Possible duplicates: #7682 and #9711.

**Comment by X123M3-256** [comment]
@ocalhoun6 You can actually open the title sequence editor window in game via the options window, and you can then the use the follow sprite feature. So as far as I can tell, this feature is already implemented, it just needs an easier way to access it.

**Comment by SevenChords** [comment]
any update on if/when an easier way for this will be implemented? the title screen editor is afterall quite a few steps for something that would be nice to have easy access for
