### ISSUE TITLE
Save games from development 0.3.2+ crashing when loading

### ISSUE THREAD

**Issue by Oricuss** [OpenRCT2/OpenRCT2#14378]
**OS:** [Windows 10]
**Version:** [0.3.3]
**Commit/Build:** [ccfa22c]

One of my completed parks and two of my ongoing parks have started crashing my game when I try to load them.

I have narrowed down the timeframe of when the problem began to sometime in 0.3.2+ development prior to the release of 0.3.3 on stable. I was working on two of these parks off and on up until sometime before January 7th, 2021. That is when I noticed the crashing. I am the type of player that will binge build for a couple days then take a few weeks off. So the crashes were likely triggered by a change around Christmas. Only one of these parks had a hybrid coaster in it. None of them have Raptors. There is a lot of CSS and custom tracked rides, however I have tested those rides and the hybrid coaster in other parks on the latest build and do not get crashes when loading. However these parks still crash on the latest build.

One interesting thing of note I found while troubleshooting. If I load the parks directly from clicking on the save file with OpenRCT2 closed. It loads into the park such that you can see a frozen screen of the last camera position and hear all the audio playing appropriately as if all the pieces are functioning in the background just fine. Ride sounds, guest screams, money transactions, ducks, etc.

Also related to the above discovery, I also noticed that when the game crashes but has managed to load the last camera location and play the audio. It also saves a screenshot for some reason. So I put quite a few of those in the screenshots area.

I would be more than happy to test out old development builds so we can narrow down the window of the change and figure out what exactly is causing this, but I can't find any from more than 10 days ago. If this is a known bug that is not going to be fixed, would someone be willing to pass me some old develop builds from prior to Christmas 2020 to try, so I can at least save some of my designs that I'm really proud of and grab some more screenshots? 

- [ Yes ] Reproducible in RCT2 (vanilla)?
- [ No ] Specific to multiplayer?

**Steps to reproduce:**
1. Open the park with any method including vanilla

**Dump file**

Amity Airfield
[28aa59db-6636-47c9-8bf9-30b86d580069(6a11dbf_x86-64).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/6186385/28aa59db-6636-47c9-8bf9-30b86d580069.6a11dbf_x86-64.dmp.gz)

Foxfire Hills (custom mega park)
[db0e375d-e72d-4621-94ef-4c28f774a2c9(6a11dbf_x86-64).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/6186386/db0e375d-e72d-4621-94ef-4c28f774a2c9.6a11dbf_x86-64.dmp.gz)

Infernal Views
[4a0438ff-621d-40d5-9ba6-660a7b5e3967(6a11dbf_x86-64).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/6186390/4a0438ff-621d-40d5-9ba6-660a7b5e3967.6a11dbf_x86-64.dmp.gz)

**Screenshots / Video:**

### **Amity Airfield**
Screenshot saved automatically when game crashes
![Amity Airfield Crash Screenshot](https://user-images.githubusercontent.com/54409340/112083500-8a184d80-8b5d-11eb-8d2b-3400a3472366.png)

Last Known Full park picture
![Amity Airfield Final](https://user-images.githubusercontent.com/54409340/112085461-f2b4f980-8b60-11eb-9b4a-66390b2c6047.png)

### **Infernal Views**
Screenshot saved automatically when game crashes
![Infernal Views Crash Screenshot](https://user-images.githubusercontent.com/54409340/112083532-9a302d00-8b5d-11eb-81bb-4c7ad15acba6.png)

Last Known Picture
![Infernal Views Last Known Picture](https://user-images.githubusercontent.com/54409340/112084945-06139500-8b60-11eb-86c0-7bd8f69fa63a.png)

Last Known Giant Screenshot
![Infernal Views Last Known Full Park](https://user-images.githubusercontent.com/54409340/112084965-0dd33980-8b60-11eb-83dc-b38ca2fec319.png)

### **Foxfire Hills Mega Park**
Screenshot saved automatically when game crashes
![Foxfire Hills Crash Screenshot](https://user-images.githubusercontent.com/54409340/112083592-b764fb80-8b5d-11eb-8c3d-bedfb42bd24b.png)

Last Known Large Scale Screenshot
![Foxfire Hills Last Known Large Scale Shot](https://user-images.githubusercontent.com/54409340/112084994-175ca180-8b60-11eb-9ecf-84b18c11fc03.png)

Last Known Giant Screenshot
![Foxfire Hills 2020-12-23 20-05-14](https://user-images.githubusercontent.com/54409340/112085056-32c7ac80-8b60-11eb-8c25-2e338774ec36.png)

This is the screenshot I found of the earliest crash, This is how I found the date it started happening.
![Foxfire Hills 2021-01-07 17-11-51](https://user-images.githubusercontent.com/54409340/112085349-be413d80-8b60-11eb-8716-df8aa418c171.png)

**Save game:**
[Foxfire Hills.zip](https://github.com/OpenRCT2/OpenRCT2/files/6186392/Foxfire.Hills.zip)
[Infernal Views.zip](https://github.com/OpenRCT2/OpenRCT2/files/6186394/Infernal.Views.zip)

The save file for Amity Airfield is too large for github even when zipped, so I uploaded it to my dropbox.
https://www.dropbox.com/s/6f9fz8huaqy8hdq/Amity%20Airfield%20for%20OpenRCT2%20Devs.zip?dl=0

**Comment by James103** [comment]
Did you upload any of those crashes to Backtrace? If so, which Github issues (if any) are those crashes related to?

**Comment by Oricuss** [comment]
Thank you. I will give that a try and report back.

**Comment by Gymnasiast** [comment]
I have tried all three saves on 040a3eb144f0b625569b8ce89157e49f7837e95a , using Linux and experienced no crashes.

> If this is a known bug that is not going to be fixed, would someone be willing to pass me some old develop builds from prior to Christmas 2020 to try, so I can at least save some of my designs that I'm really proud of and grab some more screenshots?

Our policy is that OpenRCT2 should *never* crash, but handle damaged saves and objects gracefully.

I can't really do much with the dmp files, as I'm inexperienced with them - I typically check Backtrace, which also provides symbols and the line in which the crash happened. So I'd like to try and find them in Backtrace. To that end, could you tell my what your Windows username is?

**Comment by Oricuss** [comment]
That got it, thank you! I didn't even think of checking the plugins since I only used a couple. The culprit is "Stuff Counter" by Willbycraft. I went and downloaded the latest version just in case I had an older version and yep, this plugin still causes the crashes even on a fresh download. How should I go about informing them about the issue?

**Comment by duncanspumpkin** [comment]
Yes stuff counter has a lot of issues with it. I think he knows about that though.

**Comment by duncanspumpkin** [comment]
You can report issues to the creators repo https://github.com/Willbycraft/StuffCounter

**Comment by ocalhoun6** [comment]
Is there any way to sandbox plugins better, so they're less able to crash the whole application?

Or maybe something to detect when a crash has occurred during a plugin hook, which would set a flag on the next startup, asking the player, "A plugin seems to be causing OpenRCT2 to malfunction. Disable plugins?"

Or, I guess, at the very least, when installing a new plugin, display a message like, "Some plugins are unstable and may cause OpenRCT2 to crash. If you are experiencing crashes, try disabling your plugins."

**Comment by duncanspumpkin** [comment]
If you see the above #14259 this is the issue tracking changing how we compile duktape so that it doesn't crash the game.
