### ISSUE TITLE
Plugin API Documentation guest.generation incorrect args

### ISSUE THREAD

**Issue by oli414** [OpenRCT2/OpenRCT2#14406]
The plugin API for the guest.generation event states that the argument is `id : number` while it should instead be an event object containing the property `id : number`

https://github.com/OpenRCT2/OpenRCT2/blob/177b5e1b0837a8d14c259068ef471925d342c2e3/distribution/openrct2.d.ts#L261

**Comment by IntelOrca** [comment]
Fixed in f4c30ba63a
