### ISSUE TITLE
Queue path don't connect properly to normal paths

### ISSUE THREAD

**Issue by MeshPL** [OpenRCT2/OpenRCT2#14419]
When building a queue path with "build a path on the ground" tool, several issues are encountered, most often the queue path does not connect to the normal path properly. Sometimes hovering near the queue path with a "build a path on the ground" tool fixes the issue, sometimes some manipulation with building and rebuilding or building over an existing path is required. The issue may arrise when a queue path is deleted. The issue seems to exist with "build a tunnel or aboveground path" tool as well.

![Screenshot_3068](https://user-images.githubusercontent.com/9781767/113360825-d24c2280-934a-11eb-9146-bedbfda9dd75.png)

**Comment by Gymnasiast** [comment]
Fixed by https://github.com/OpenRCT2/OpenRCT2/commit/b65f12f1cfd26834f5cf6b616c6aec18bd265ab7.
