### ISSUE TITLE
Abstract ride entrances do not show scrolling text.

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#1442]
![image](https://cloud.githubusercontent.com/assets/1482259/8320668/d02b1376-1a15-11e5-902c-a1e4255a1019.png)

**Comment by rctdude2** [comment]
For me, this happens, but it also depends on what rotation I'm viewing the entrance banner at. Sometimes it'll show the text, sometimes it'll flash but display it, and sometimes it'll not show up at all.

**Comment by duncanspumpkin** [comment]
Most likely a bug in my new drawing code for entrances. Will look at it shortly.
