### ISSUE TITLE
Move backtrace issues to another repository, maybe OpenRCT2/BacktraceIssues

### ISSUE THREAD

**Issue by ppizarror** [OpenRCT2/OpenRCT2#14424]
First, thanks for your work, I've been using OpenRCT2 for ages now and wasted thousands of hours mastering my parks.

I've seen that the vast majority of the opened issues rely on the backtrace bot. What if these issues are moved to another repo within the same organization? That contributes to clearing the issues tab and focusing the attention on more specific user-made issues.

Greetings from 🆑

**Comment by Gymnasiast** [comment]
The Backtrace issues do not really bother us. They represent crashes that people suffer from, so they are not really different from manually created ones. For the average user, random crashes are probably much _worse_ than incorrect behaviour, so they are way too important to set aside like this.

If we were to move anything out of the issue tracker, it would most likely be feature requests. At the moment, all three feature request labels combined represent 351 open issues, which is a lot more than Backtrace has ever had.

**Comment by IntelOrca** [comment]
Most of the backtrace issues are duplicates or too old, we just need to improve our triage of them so there aren't so many.

**Comment by tupaschoal** [comment]
You can always filter by excluding the backtrace label (just click on the backtrace label then add a minus before it)
![image](https://user-images.githubusercontent.com/6443427/113458818-f743a280-93e9-11eb-9cf7-5380feee8568.png)

https://github.com/OpenRCT2/OpenRCT2/issues?q=is%3Aissue+is%3Aopen+-label%3Abacktrace.io+
