### ISSUE TITLE
Research ride improvements

### ISSUE THREAD

**Issue by solumg** [OpenRCT2/OpenRCT2#1443]
In RCT1 you could choose to research ride improvements for that particular scenario. I don't know about everyone else but i liked this feature. It could make a old ride new and exciting again.

**Comment by Gymnasiast** [comment]
Personally I found it a very strange feature: it lead to situations where corkscrews were possible, but looping weren't. The set-up of RCT2, with a lot of information in the .DAT files (which we can't edit, at least not currently), also makes it quite complicated.

**Comment by solumg** [comment]
I see. Well maybe sometime in the future as an option perhaps.
