### ISSUE TITLE
Windows Xp error

### ISSUE THREAD

**Issue by dimaspaf14** [OpenRCT2/OpenRCT2#14441]
**OS:** Windows Xp Sp3
**Version:** 0.3.3
**Commit/Build:** idk what is this

Installer run correctly but the game has no icon and cant run because it says "openrct2.exe is not a valid Win32 application."

- [x] Reproducible in RCT2 (vanilla)? Yes
- [ ] Specific to multiplayer? No

**Steps to reproduce:**
1. Install the 32bit version
2. Then run the game and see the error

**Dump file**
(no dump file, the game isnt running)

**Screenshots / Video:**
![IMG_20210405_152853](https://user-images.githubusercontent.com/71385492/113554527-a9b27a00-9623-11eb-97cc-7f3b65c72dfb.jpg)

**Save game:**
(Also no save game)

**Comment by duncanspumpkin** [comment]
We do not support Windows XP. Please update to a supported platform. 

@janisozaur occasionally produces Windows XP builds but unsure if there has been one recently.

**Comment by dimaspaf14** [comment]
I also have windows 7 but i hate lags :( , most of my game run smoothly on my xp

**Comment by Lastorder-DC** [comment]
Although WinNT 5.1(=XP) Builds are available [here](https://github.com/OpenRCT2/OpenRCT2/runs/2261523077), you'll need mingw dlls to run that binary.

**Comment by duncanspumpkin** [comment]
Windows xp builds will most likely be less performant compared to the newer versions as it's 32bit
