### ISSUE TITLE
[Android] Unable to close the options window

### ISSUE THREAD

**Issue by adammw** [OpenRCT2/OpenRCT2#14468]
**OS:** Android 11, Samsung OneUI 3.1
**Version:** 0.3.3
**Commit/Build:** Unable to find

Unable to close the options window. Other windows close fine. Tried increasing UI scale in case it was a small hit target, but the hover for 'close window' shows so I'm pretty sure I'm getting the right hit target.

**Steps to reproduce:**
1. Open the options window on Android
2. Attempt to close the window

**Screenshots / Video:**
![Screenshot_20210413-180601_OpenRCT2](https://user-images.githubusercontent.com/153219/114518969-40fe7980-9c83-11eb-816f-9ca062277823.png)

**Comment by James103** [comment]
Have you tried attaching the output for `openrct2 --version` for the build/commit that you reproduced this on?

**Comment by SilkyPantsDan** [comment]
I'm having the same issue using the latest available build - it doesn't appear to print the commit or build

![Screenshot_20210509-161750_OpenRCT2](https://user-images.githubusercontent.com/738172/117563046-6182ed80-b0e2-11eb-90d6-387c15021a15.jpg)
