### ISSUE TITLE
Loading a save crashes my game

### ISSUE THREAD

**Issue by That-Human-Being** [OpenRCT2/OpenRCT2#14473]
**OS:** Windows 10
**Version:** 0.3.3-188
**Commit/Build:** 3188865313485c02acb56abaf125a3380e967185

Trying to load any of my saves from previous versions of OpenRCT2 will result in a game crash

❓ Reproducible in RCT2 (vanilla)?
❌ Specific to multiplayer?

**Steps to reproduce:**
1. Run a save file 

**Dump file**
[8c35f668-ce18-492c-9cbe-a358a8a568e4(3188865_x86-64).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/6311174/8c35f668-ce18-492c-9cbe-a358a8a568e4.3188865_x86-64.dmp.gz)

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/81326222/114720126-5b753900-9cfd-11eb-8152-1545e47fa1ec.png)

**Save game:**
[save.zip](https://github.com/OpenRCT2/OpenRCT2/files/6311182/save.zip)

**Comment by Gymnasiast** [comment]
Both files load up correctly for me as of c0eade9c88ec95882a20bf1959b5c8d69248371b . Assuming it has been fixed.
