### ISSUE TITLE
Map size isn't synced in multiplayer

### ISSUE THREAD

**Issue by Margen67** [OpenRCT2/OpenRCT2#14474]
**Version:** 0.3.3
**Commit/Build:** https://github.com/OpenRCT2/OpenRCT2/commit/b24cdff0fb2ad1db4dffb304a3f6cd22976b29d2

Setting the map size while sandbox mode is on in multiplayer leads to a desync.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**
1. Create a server.
2. Enable Sandbox mode.
3. Change map size.
4. Map size won't sync. (if you're the host players will have to rejoin)

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/3462541/114768128-2f10eb00-9d04-11eb-983c-4ac7966d0b81.png)

**Comment by Broxzier** [comment]
Are cheating and sandbox permissions split? This would otherwise make it very easy to completely vandalize a map when cheats are enabled.

**Comment by ZehMatt** [comment]
> Are cheating and sandbox permissions split? This would otherwise make it very easy to completely vandalize a map when cheats are enabled.

I suspect it bypasses game actions, I will check this later.

**Comment by frutiemax** [comment]
Is this resolved yet?

**Comment by duncanspumpkin** [comment]
No i don't think anyone has got round to adding the game action for this.

**Comment by frutiemax** [comment]
I've done an attempt but I think it is breaking the game too much. If you start a server on an existing park, decrease the map size, the game will stall as it tries to remove elements from the game... I'm not too sure how to fix this.
