### ISSUE TITLE
[Plugin] Setting ``isHidden=true`` for a vertical ride does not work properly

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#14493]
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** bbf33b6

I was trying to make a plugin that hides a certain ride and I found this issue.
When I try to set ``isHidden`` property into ``true`` via console, some elements is not hidden properly since corrupted element is positioned in a wrong order.
If new-save-file foramt will be implemented, this will not be an issue.

**Steps to reproduce:**
1. Run OpenRCT2 with console (in Windows, run ``openrct2.com``)
2. Build ``Escape Hatch`` preset of Launched Freefall at ``x=4, y=4`` tiles
3. Open the Tile Inspector window and select the (4, 4) tile. Note that the last element's index is 17.
4. In console, run ``map.getTile(4, 4).getElement(17).isHidden = true``
5. The corrupted element is inserted at index ``4``, not ``16``.

**Screenshots / Video:**
![1](https://user-images.githubusercontent.com/10726524/115147673-0fc4e580-a097-11eb-9d00-38533bc4c663.gif)

**Comment by Gymnasiast** [comment]
This error will go away once the new save format is there, which uses a property to hide elements instead of corrupt elements. Keeping this open until then (or until someone fixes it before the new save format is here).

**Comment by Broxzier** [comment]
I think the bug here is that it's hiding the wrong element. The 17th element is the top one, but it places the corrupt element under the 5th. It does take the base height of the top one, though.

**Comment by Broxzier** [comment]
This has to do with the insertion base height of 255 not being correct anymore. `tile_element_insert` now takes a `CoordsXYZ` which I think uses big coords. The base height of 255 was used to guarantee that the corrupt element was placed at the end of the tile list, but now with big coords that's only at 1/8th of the max height. Multiplying by `COORDS_Z_STEP` probably fixes this.
