### ISSUE TITLE
Coding Feature / Bug Prevention:  Explicitly declare Integer to be INT32NE except where explicitly declared otherwise.

### ISSUE THREAD

**Issue by Ruedii** [OpenRCT2/OpenRCT2#14508]
We should explicitly declare generic INT variables to be 32bit Native Endian Integer (INT32NE) except where explicitly declared otherwise.  This will prevent many compiler specific or platform specific behavior bugs.  

This should be able to be done in standard compiler directives.

**Comment by Broxzier** [comment]
We already generally use `int32_t` and similar types with fixed sizes and Two's Complements support to specify their types explicitly. Not counting testpaint and third-party source files in the repo (where in some cases a standard primitive is even required), there are only a handful of instances where `int` is used.
