### ISSUE TITLE
Enable save button without testing ride

### ISSUE THREAD

**Issue by sjoerddebruin** [OpenRCT2/OpenRCT2#1450]
I don't know if this is possible. But if you want to build a correct ride and want to save it, you'll always need to test it before the save button becomes enabled. For some rides, that seems redundant.

**Comment by Gymnasiast** [comment]
It has to write excitement/intensity/nausea values to the track designs, so it should have those calculated first. And the excitement value is greatly influenced by the surroundings, so not something you can really guess. I'd say you'd have to be a bit more patient. ;)

**Comment by KC-7** [comment]
Perhaps we could write in E/I/N values ourselves?
