### ISSUE TITLE
Show staff while hiding peeps/guests

### ISSUE THREAD

**Issue by Margen67** [OpenRCT2/OpenRCT2#14513]
From https://www.reddit.com/r/openrct2/comments/foei2y/openrct2_v025_released/fnjwox2/:
> I want to hide the guests only and show the staff. I really like to pop in and see where they are working and if they are near the ride that needs fixing or path to clean.

**Comment by ocalhoun6** [comment]
The 'highlight path issues' view mode already does great for this if you want to look at where handymen and security guards are.

Maybe this view mode could also show mechanics and entertainers, so it would be useful for monitoring all staff types?

**Comment by Broxzier** [comment]
Alternatively you can open the staff list along with the map window to show all your staff's locations on the map.

**Comment by seifer7** [comment]
I am working on this.

**Comment by KatieZeldaKat** [comment]
This issue seems to have been fixed a while ago and is still working in the latest version. This issue should probably be closed.
