### ISSUE TITLE
Allow selecting all music when "Unlock operating limits" is on

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#14511]
Currently, the merry-go-round can only select the fairground organ style, while other rides can select everything but the fairground organ style. We should extend the "Unlock operating limits" cheat to allow selecting all music.

**Comment by Broxzier** [comment]
Nice idea. Maybe this could even be used to make stalls play music as well. I think I've got that working before, but it required some fiddling with the ride type properties in order to actually have them play the music.
