### ISSUE TITLE
Supports visibile for large objects

### ISSUE THREAD

**Issue by Golaith123** [OpenRCT2/OpenRCT2#14530]
![The Good Death 2021-04-26 08-28-37](https://user-images.githubusercontent.com/9442821/116011711-b4cc5900-a669-11eb-9505-1dc926bbc1ec.png)

![Drowned 2021-04-26 08-28-22](https://user-images.githubusercontent.com/9442821/116011715-b5fd8600-a669-11eb-9ce1-72f7ced2a166.png) 
![Uploading Drowned 2021-04-26 08-28-13.png

As you can see I'm always stuck with black supports for large objects. Am playing on the latest version, this has been in every version I have ever installed

**Comment by Gymnasiast** [comment]
Do NOT remove the template. It is there for a reason. Especially important here is whether it happens in vanilla RCT2 and uploading the save.

**Comment by Gymnasiast** [comment]
Since you refused to fix above issue and haven’t even bothered to upload an affected save, we have no other choice but to close it.

Provide us with the info we’re asking for if you really want your issue fixed.

**Comment by Golaith123** [comment]
Oh sorry lol. It was a bad object that didn't remove supports properly

**Comment by Gymnasiast** [comment]
OK, please just close the issue next time. It keeps our bug tracker tidy.
