### ISSUE TITLE
Set random ride or stall for marketing campaign

### ISSUE THREAD

**Issue by sjoerddebruin** [OpenRCT2/OpenRCT2#1453]

**Comment by mrtnptrs** [comment]
Really doubt if anyone would like/use this feature ever as most people probably just want to start a marketing campaign for a specific ride. Why else would you start a marketing campaign for a ride? If it was up to me, I would close this one. What do the others think?

**Comment by Gymnasiast** [comment]
Hm, I don't think it would really add much. I wouldn't object to a PR, but this has gone one year without one.
