### ISSUE TITLE
No more forced breakdowns in the latest development version

### ISSUE THREAD

**Issue by bieryan** [OpenRCT2/OpenRCT2#14542]
In the lates version of openrct the option for forced break downs is gone.

**Comment by Fred-1044276** [comment]
First off, you are not providing us enough information. Second off, you deleted the placeholders provided with the blank bug report template that you weren't supposed to delete (OS, Version, Commit/Build, Explanation of the issue, Steps to reproduce, Screenshots / Video).

**Comment by Fred-1044276** [comment]
With my comment, you need to input the following information:

**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** 6c65105
