### ISSUE TITLE
Hide "voucher for free food or drink" when the park doesn't contain any stalls

### ISSUE THREAD

**Issue by sjoerddebruin** [OpenRCT2/OpenRCT2#1454]
It's weird that it's showing up in the marketing campaign window when there's nothing to select.

**Comment by Patrik356b** [comment]
Why hide and not "gray them out" ?.

**Comment by IntelOrca** [comment]
Why "grey them out" and not hide them?

**Comment by daihakken** [comment]
I believe that gray them out will be a bad ux experience.

**Comment by Patrik356b** [comment]
"Graying out" is the term were an option is still visible but can not be selected. In vanillia rct, this is when the color of an option matches the background but is a fair bit darker

**Comment by daihakken** [comment]
For me, this will be another "Vehicle Type" drop box which you can still click if only 1 vehicle is available for that ride, it's unnecessary to give up the "hide" to make them greyed out.

**Comment by vzybilly** [comment]
to me, hiding would mean that there will never be the option in the current state of the program (not game, program) graying it out would appear to me as if I need to unlock or *do something* first, like build one... that's what it would feel like to me, gray for the game can do but I just don't have the option right now and hidden from the game can't do and I don't have the option...

**Comment by Patrik356b** [comment]
ah, i see.
