### ISSUE TITLE
roller coaster randomly fail to get up hill that it made before

### ISSUE THREAD

**Issue by andrewq99** [OpenRCT2/OpenRCT2#14550]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.3.3]
**Commit/Build:** 1aec320

bunch of rollercoaster that i have put down randomly fail 

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. i put rollercoaster down
2. then it work for a while than it randomly stop working

**Dump file**

**Screenshots / Video:**
![aa](https://user-images.githubusercontent.com/39251943/116773225-359ca380-aa22-11eb-892a-e4bbf1219e6d.jpg)

**Save game:**

**Comment by Fred-1044276** [comment]
Two things:

1. You didn't provide the saved game where this issue happened.
2. Deep Freeze (top-mid-right) has an issue with the vertical loop clearances in recent versions of OpenRCT2.

**Comment by duncanspumpkin** [comment]
You've not stated what build you are using provide the commit hash and fill in the template correctly.

**Comment by andrewq99** [comment]
i am using 1aec320

**Comment by andrewq99** [comment]
https://openrct2.org/downloads/develop/v0.3.3-1aec320

**Comment by Gymnasiast** [comment]
Please also provide an affected save.

**Comment by andrewq99** [comment]
[New ZIP Other File (VLC).zip](https://github.com/OpenRCT2/OpenRCT2/files/6409636/New.ZIP.Other.File.VLC.zip)

**Comment by andrewq99** [comment]
all rollercoaster in this save file fail overtime

**Comment by Broxzier** [comment]
The mass of guests affects the physics of the trains. When the minimum speed over a hill doesn't have enough threshold to make it over a hill, it may fail when the heavier guests are sitting to one side of the train.

**Comment by andrewq99** [comment]
i did not have his issue with the gusts being to heavy in old Version

**Comment by jensj12** [comment]
It appears that, in that save, vehicle 7 of C2 Creaky Dips is just exceptionally slow and stalls in a dangerous position. Did you use the 'remove guests' cheat? (and when, there were fixes in February, see #13234)

**Comment by Gymnasiast** [comment]
I’m going with @jensj12 's explanation here.
