### ISSUE TITLE
Chain lift is enabled to downward slopes

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#14551]
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** 6c65105

Chain lift is enabled to downward slopes even though allowing chain lifts on all track pieces is not enabled.

**Steps to reproduce:**
1. Check that ``Allow chain lifts on all track pieces`` cheat is disabled
2. Build a coaster and go up
3. Select downward slope, then you can check that chain lift button is still enabled.

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/10726524/116774151-9a451600-aa95-11eb-8f30-b19965cfe702.png)

**Comment by Gymnasiast** [comment]
Not a bug. You need it for the reverse incline launch mode.

**Comment by Broxzier** [comment]
Normally when going from straight to downwards slope, the chain lift gets automatically disabled. Telk probably means that that does not happen anymore.

**Comment by Gymnasiast** [comment]
Just tried that. Chain lift does get turned off automatically when selecting downward slope, just as it should.
