### ISSUE TITLE
Automatic resync at network desynchronization

### ISSUE THREAD

**Issue by FlightMS** [OpenRCT2/OpenRCT2#14563]
It should be possible to enable an automatic resync when a network desynchronization occurs. Otherwise you have to leave and rejoin the server.

As alternative a resync button would be nice.

**Comment by YJSoft** [comment]
Only way to resync is to download whole map again(which is not different from reconnect)

**Comment by YJSoft** [comment]
Also, I should mention that similar suggestions are already vetoed(see #2695, #3134, #5512)
