### ISSUE TITLE
[bug] error when joining server

### ISSUE THREAD

**Issue by nlacombe42** [OpenRCT2/OpenRCT2#14587]
### Server
**OS:** `Ubuntu 20.04.2 LTS (5.4.0-1042-gcp #45-Ubuntu x86_64)`
**Version:** `OpenRCT2, v0.3.3 (, DEBUG) Linux (x86-64)`
**Commit/Build:** installed from ppa. i can see this in package metadata: `Version: 0.3.3-develop-0~2443-202104040054-g9b2c94648~ubuntu20.04.1`

### Client
**OS:** `Manjaro Linux 21.0.3 (5.10.32-1-MANJARO #1 x86_64)`
**Version:** `OpenRCT2, v0.3.3 Linux (x86-64)`
**Commit/Build:** could not find this info, but the arch/manjaro package metadata says `Version               : 0.3.3-3`, package name `openrct2`

started an openrct2 server on ubuntu in gce and tried to connect to it from my manjaro laptop.
every time i try to connect to the server it fails.

- n/a Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**
1. on server add ppa and instlal package `openrct2`, then run command `openrct2-cli host ./orct2-nlacombe-test.sv6 --port 11753`
2. on client install `openrct2` pacakge and either try to connect with the gui app or just run `openrct2-cli join PUBLIC_IP`

if I run the server and try to connect from a client on the same computer (tried for both server and client) it works (using the cli).
i used netcat to test that the port/ip was open and relaying data correctly and my netcat test passed.

**Save game:**
[orct2-nlacombe-test.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/6445024/orct2-nlacombe-test.sv6.zip)

error in server logs:
```
VERBOSE: Client 207.236.123.18 heartbeat
VERBOSE: Signature verification ok. Hash 00224610dd335b8c276b8f53e6d1994e6392a875
ERROR[/build/openrct2-bJ3TlJ/openrct2-0.3.3-develop-0~2443-202104040054/src/openrct2/network/NetworkBase.cpp:2607 (Server_Handle_AUTH)]: Unknown failure (3) while authenticating client
```

**Comment by ZehMatt** [comment]
The 3 means actually NetworkAuth::BadVersion, you might have a different server/client version. Client and server have to match. This error case should be probably handled properly.

**Comment by nlacombe42** [comment]
> The 3 means actually NetworkAuth::BadVersion, you might have a different server/client version. Client and server have to match. This error case should be probably handled properly.

thanks! yes the error message should be clearer 😛

based on what you said i assume that my server version (ubuntu ppa) must be a "nightly" version and that is why it does not work with the manajro/arch version.

any idea how to get a non-nightly version for ubuntu? so that my server version matches my client version.

> Edit: I just looked, the client should show some error message actually.

with the version for server and client specified in my op, i do not get an error in the client logs for the cli :
```
$ openrct2-cli join PUBLIC_IP
INFO[/build/openrct2/src/OpenRCT2-0.3.3/src/openrct2/network/NetworkBase.cpp:255 (BeginClient)]: Connecting to 34.95.22.124:11753
openrct2 $
```

with the gui i see this unhelpful error (public ip removed from screenshot)
![Screenshot_20210508_175940-mod](https://user-images.githubusercontent.com/2486370/117555130-89af1580-b02a-11eb-94e8-fe6e67ce65a9.png)

**Comment by Gymnasiast** [comment]
Because the bug/confusing wording was resolved, and this is a bugtracker, not a place for asking questions. Those belong on Discussions, Reddit, Discord or the openrct2.org community forums.

It was also a question that is already answered in the manual: https://docs.openrct2.io/en/latest/installing/installing-on-linux-bsd.html#ubuntu-linux-mint-and-derivatives
