### ISSUE TITLE
Can't see where are the vehicules

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#14593]
windows 10
Test update

We can't see the vehicule cam here. it'S still at the view cam

no, it's wasn't a vanilla issue or older Open RCT2 versions issue
also not a multiplayer only

**Steps to reproduce:**
1. Build any rides
2. Open/test/similate it
3. Done!

**Comment by tupaschoal** [comment]
If you can provide on what specific commit you're running, that can greatly help us
