### ISSUE TITLE
Can't get more than few objects (scenery), because the windows is actually limited to a maximum.

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#14592]
Windows 10
0.3.3-13 (testing new save file)

not reproductible on vanilla (have older limits)
not specific to multiplayer

**Steps to reproduce:**
1. get about all rct2 scenery
2. get a single custom
3. done! you have the bug
4. (Not a step, but to add on), i think there was a limit of objects in a window back in the days

**Comment by Margen67** [comment]
Issues with the new save format belong here: https://github.com/OpenRCT2/OpenRCT2/pull/10664
