### ISSUE TITLE
Importing an old save makes the game claim the scenario has been beaten with a very low company 

### ISSUE THREAD

**Issue by RealRexen** [OpenRCT2/OpenRCT2#14608]
Windows 10
0.3.3 new save format
Commit/Build:*16c10f6

![Central Plains 2021-05-09 17-00-28](https://user-images.githubusercontent.com/18408903/117591395-20daa280-b0e9-11eb-8e70-0c13cbbf96db.png)

save file 
[Central Plains3.txt](https://github.com/OpenRCT2/OpenRCT2/files/6448666/Central.Plains3.txt)
Didnt see this issue listed so I figure I'll file a report

**Comment by James103** [comment]
> 0.3.3 new save format

This issue should go in the comments of https://github.com/OpenRCT2/OpenRCT2/pull/10664. Quoting from the reddit post:
> If the bug only occurs with the new save format test build, report it in a comment on https://github.com/OpenRCT2/OpenRCT2/pull/10664. Put a checkbox in front of every bug you find - we will check them as we fix your issues.
