### ISSUE TITLE
"Remove Guests" prevents guests from entering rides.

### ISSUE THREAD

**Issue by Phasedetect** [OpenRCT2/OpenRCT2#1462]
If you remove the guests from the park with the cheat they enter queue lines, walk all the way to the front, and then turn right back around.

To duplicate:
- Open Six Flags Belgium
- Remove guests
- Turn all rides back on
- Send in a bunch of trams
- Hyper speed

At first it looks like they will enter rides normally, but then they start refusing to enter them.

Rides built after the cheat was used operate normally.

**Comment by duncanspumpkin** [comment]
Caused by the ride queue thinking that there is a peep at it. Suggest changing cheat to reset the `ride->first_peep_in_queue[ 0 through to 3]` to `0xFFFF` after deleting all peeps.

**Comment by Gymnasiast** [comment]
I'm working on it, so you can assign it to me. Since I'll have to wait until the startup crash bug has been solved, expect the solution tomorrow.
