### ISSUE TITLE
RCT1 Theme Inaccuracies & About OpenRCT2 window color cannot be changed by themes.

### ISSUE THREAD

**Issue by ZeeMajora** [OpenRCT2/OpenRCT2#14638]
There are some inaccuracies with the RCT1 theme.

The map window is gray in rct1
The track design selection window is dark brown in rct1
The about window is dark brown in rct1

Also updating the extra viewport window to be gray for consistency with the rct1 gray map window would likely be a good idea as it uses the rct2 map window color and is under the map tab.

Additionally the "About OpenRCT2" window cannot have it's color changed by themes.
So making it changable by themes would be required to implement the rct1 color for the about window.

![rct1themedifferences](https://user-images.githubusercontent.com/42477864/118046162-f1c16c80-b346-11eb-8258-9421f2ca5f31.png)
![openrct2inaccuracies](https://user-images.githubusercontent.com/42477864/118046186-fa19a780-b346-11eb-88e2-afe1ae986a11.png)

**Comment by Gymnasiast** [comment]
The windows for shortcut keys (and the miniwindow for changing it) should also be brown.

**Comment by ZeeMajora** [comment]
I checked it and it is actually brown in openrct2's rct1 theme, Both the shortcut key list and the key changing mini window.
![DeepinScreenshot_openrct2_20210513105508](https://user-images.githubusercontent.com/42477864/118143782-b623b280-b3d9-11eb-9bae-1e93af7c8033.png)
