### ISSUE TITLE
Rollercoaster  [BUG]

### ISSUE THREAD

**Issue by Horsti12** [OpenRCT2/OpenRCT2#1465]
This Bug only happend one time yet
This bug happends when you want to build a RCT2 pre installed design.
No rct2 original design of any Rollercoaster work and all show the same tracks.
The Design "Loop-the-Loop" has no picture and all numbers are zero.

All the other designs (Circulator, Ipulsive, Loop-the-Loop and Multidiver) didn't show any information, so it's a window WITHOUT any text.

I can't make a screenshot, because the screenshot function also not work.
I don't know what's wrong with my OpenRCT2 xDDD

Edit.
It happends to every track!!!!!

**Comment by rctdude2** [comment]
Works for me. Make sure your OpenRCT2 is up-to-date.

**Comment by Horsti12** [comment]
My OpenRCT2 is always up-to-date.
I update it 3-4 times a day.

**Comment by PFCKrutonium** [comment]
If your on Windows 8 or newer, press Windows + Print Screen. It should take a screenshot of your screen.
