### ISSUE TITLE
Changelog/Music window color incorrect in RCT1 theme & Music acknowledgments cannot be themed

### ISSUE THREAD

**Issue by ZeeMajora** [OpenRCT2/OpenRCT2#14655]
I question whether or not i'm digging too deep or not digging deep enough with these window colors, Oh well.
The changelog, while not present in rct1 still should probably match the about openrct2 window's new rct1 color.
Additionally the music acknowledgments window is also brown in rct1 and it cannot currently be themed.

![DeepinScreenshot_explorer exe_20210514081300](https://user-images.githubusercontent.com/42477864/118269064-3c003600-b48c-11eb-9ec3-404227b6e31e.png)

![DeepinScreenshot_openrct2_20210514080520](https://user-images.githubusercontent.com/42477864/118269107-49b5bb80-b48c-11eb-9e3c-04a954c45caa.png)

**Comment by Gymnasiast** [comment]
The music acknowledgements window will be removed in due course, so I didn’t bother.
You can create a pull request for the changelog if you like.
