### ISSUE TITLE
Landscape editor issues

### ISSUE THREAD

**Issue by ridetester101** [OpenRCT2/OpenRCT2#14663]
**OS:** [Windows 10]
**Version:** [0.3.3]
**Commit/Build:** [16c10f6]

Issue with early stage landscape editor and saving landscape files: Two issues noted if selecting more items than previous limits and big map:

Have a theory as to cause that may need error message and similar catch and corrects see below

1. If you've used the advanced tab and selected lots of scenery, 2043 small in my test for example, some of it shows blanks in the scrolldown for scenery selection in the editor, possibly as it is trying to dump it all in the question mark misc tab, may need to split into multiple misc tabs if it cannot handle close to max items not selected from categories
2. seems to be a problem with early landscape saves- I had got to point of placing entrance and entry path with spawn point and small bit of owned land- I was testing this very point, loading up the landscape files everything is lost-it just defaults back to the smaller map and default selected scenery etc, nothing placed on the map. File size looks like data is there 52215kb but it cannot bring it up for some reason- if you cannot replicate I could send the file over, also it is saving parks as .park.sc6 so that's what I can send if you need to take a look 

- [ ] Reproducible in RCT2 (vanilla)? No due to testing out limit cap exceeding (but could test out failing to path to map edge)
- [ ] Specific to multiplayer? Not applicable as landscape editor issue

**Steps to reproduce:**
1. Select lots of stuff above previous but within new limits in scenario editor
2. See if it will keep hold of those selections and a basic park without doing the full landscape, park and scenario design just the basics of entrance, path and initially owned land- try this with and without the path going to the map edge as this may be the mistake I made with a bigger map size- literally just dawned on me that after many hours of option choices I was a bit burnt out so missed that I probably hadn't put the path all the way to the map edge which I think is maybe the problem- it may now fail to give you the warnings that your entrance is broken and you need to fix it before saving, so maybe some way where saves that are incomplete in this way still work for landscape saves and if needs be they prompt you for any fixes needed where entrance is wrong etc as you cannot do it in one go if you're working with thousands of scenery choices- so a way to save at any point, even whilst not having made all the scenery choices and not even doing any landscaping would be good i.e. where it will still load an unfinished map and let you stop and pick up at any point, even whilst in object selection. Hence it just saves whatever you have done thus far.
3. I was trying map size of 512 x 512 base height 7

**Comment by ridetester101** [comment]
Totally new to this, think I put first bit in wrong place:

Issue with early stage landscape editor and saving landscape files: Two issues noted if selecting more items than previous limits and big map:

Have a theory as to cause that may need error message and similar catch and corrects see below

1. If you've used the advanced tab and selected lots of scenery, 2043 small in my test for example, some of it shows blanks in the scrolldown for scenery selection in the editor, possibly as it is trying to dump it all in the question mark misc tab, may need to split into multiple misc tabs if it cannot handle close to max items not selected from categories
2. seems to be a problem with early landscape saves- I had got to point of placing entrance and entry path with spawn point and small bit of owned land- I was testing this very point, loading up the landscape files everything is lost-it just defaults back to the smaller map and default selected scenery etc, nothing placed on the map. File size looks like data is there 52215kb but it cannot bring it up for some reason- if you cannot replicate I could send the file over, also it is saving parks as .park.sc6 so that's what I can send if you need to take a look

**Comment by James103** [comment]
> **Commit/Build:** [[16c10f6](https://github.com/OpenRCT2/OpenRCT2/commit/16c10f6820952e1528cb748f3125775c9902f741)]

Can you reproduce this issue in the develop branch? If not, can you please make a comment about this issue in #10664?

**Comment by ridetester101** [comment]
I'm brand new to github so shall just double check what I need to do where- thanks

**Comment by ridetester101** [comment]
Thanks James

**Comment by Gymnasiast** [comment]
Closing this as the correct place is indeed the #10664 PR.
