### ISSUE TITLE
Rendering & Screenshot Issues When Using Massive .park Savefiles

### ISSUE THREAD

**Issue by ColsonThePCMechanic** [OpenRCT2/OpenRCT2#14678]
**OS:** Archlabs Linux
**Version:** Kernel Linux 5.12.3-zen1-1-zen x86_64
**Commit/Build:** OpenRCT2, v0.3.3-165 (975ed665f on makepkg) - launched with .park testing appimage

When I attempt to make a screenshot of my large map, the outputted screenshots will not accurately render the entire park.  When using software rendering engine, a large blank square will be removed from the bottom of the screenshot, while the rest of the image will be heavily pixelated.  When using the OpenGL engine, a massive .png is created but only has a translucent background with no objects rendered in the photo.

![OpenGL screenshot of map](https://user-images.githubusercontent.com/84006238/118388326-93abb800-b5d8-11eb-99cb-73458882fe2f.png)

![Software rendering screenshot of map](https://user-images.githubusercontent.com/84006238/118388343-b50ca400-b5d8-11eb-8730-270e9d31788e.png)

- Reproducible in RCT2 (vanilla)? No

- Specific to multiplayer? No

**Steps to reproduce:**
1. Open a .park savefile with a 999x999 map size and 1,000,000+ elements in the map.
2. Attempt to take a screenshot of the whole map, or zoom out completely and look around the map.

**Save game (.park):**

[savegame.zip](https://github.com/OpenRCT2/OpenRCT2/files/6488797/savegame.zip)

**Comment by duncanspumpkin** [comment]
Write all new save format issues in the new save format pr
