### ISSUE TITLE
Recent Messages only shows at most 6 or 7 notifications once opened

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#14674]
**OS:** Windows 10
**Version:** 0.3.3+
**Commit/Build:** 0123a3d

If any time you open the Recent Messages window, as soon as you get the seventh, eighth, or so notification while in a scenario, only the first 6 or 7 will show up although the seventh/eighth notification and all later ones will correctly still show up in the message bar at the bottom of the screen. This bug was first observed in the .park test build but I have confirmed that it also happens in develop. This bug can be annoying as it can hide important notifications (e.g. park rating warnings, awards, newly researched ride/scenery).

**Steps to reproduce:**
1. Open any scenario or save file (can be the one attached below).
2. Open the Recent Messages window at least once.
3. Generate at least 6 or 7 notifications (can be done by drowning 7 guests/staff members or crashing 7 rides). Only the first 6/7 notifications received since opening Recent Messages will show up.

**Screenshots:**
![Carmine Calderas 2021-05-15 14-59-41](https://user-images.githubusercontent.com/61885939/118379412-042de700-b58f-11eb-8688-5e67085c9308.png)
![Carmine Calderas 2021-05-15 14-59-44](https://user-images.githubusercontent.com/61885939/118379413-05f7aa80-b58f-11eb-9d18-5677aa6b2902.png)
As you can see, in the first screenshot, Reverse Freefall Coaster 1 has just broken down. However, the game only recorded all notifications up to the seventh one, which was the Wooden Wild Mouse being researched on June 26th, Year 1. So, clicking on the "Reverse Freefall Coaster 1 has broken down" message did not send it to Recent Messages because it was beyond the first 7 notifications after I opened up Recent Messages at the start of the scenario. Note that I did not disable any of the notification types.

**Save game:**
[Carmine Calderas.zip](https://github.com/OpenRCT2/OpenRCT2/files/6488333/Carmine.Calderas.zip)
Attached is a .zip file containing the scenario I was playing when I spotted this bug, along with the save file. The SV6 was saved on October 4th, Year 1, the date that the Reverse Freefall Coaster 1 breakdown pictured above took place.

**Comment by worstje** [comment]
As a new user who discovered OpenRCT the other day and wanted to enjoy a childhood classic with some scenario play, this has been the only bug that actually left me frustrated. (Everything else are just minor annoyances I can live with.) It would be nice if this issue could get the love it deserves before the next release because this has high visibility, especially to new/returning players who are bound to open the message window more than practiced players.

**Comment by Pikanet128** [comment]
I just had this happen in crumbly woods
if i saved and loaded it didn't fix 
but if i save full quit the game and then reload there all back so at least i have a workaround in the mean time
hopefully this will get fixed as its anoying

**Comment by felipeek** [comment]
Same issue happening for me

**Comment by csm10495** [comment]
I'm seeing this too :/

**Comment by Legotown55** [comment]
When will this bug me mended
