### ISSUE TITLE
[Plugin] Per-save plugin storage

### ISSUE THREAD

**Issue by rctdude2** [OpenRCT2/OpenRCT2#14676]
(I looked through existing issues and didn't find an existing issue or reference, sorry if I missed something.)

Now that the new save format is in testing and closer to being implemented, I wanted to add a feature request for adding per-save plugin storage. I'd like to be able to store settings for specific parks, and the current sharedStorage a) isn't conducive to saving per-park data, because there isn't a unique identifier (that I know of; I've seen a plugin use the park name, which isn't a constant and would clash with other saves), and even if it did, b) promotes orphaned data by separating park-specific information from the park itself and increasing the plugin.store.js file size with many saves.

This per-save storage would be in two parts:
1. "Global" storage that applies to the whole park. This could be used for defaults or settings/data that apply to the whole park.
2. Per-ride storage. This would be for data that applies to a specific ride (this _could_ be stored in global by using the ride.id, however if the ride is deleted the stored data would be useless).

As a real-world example, I have an automatic price manager that I use to set ideal prices to maximize scam- uh, _convincing_ my guests into parting with their money. One of the settings is setting ride prices to either the value price (most guests will pay and think "x is really good value"), the expensive price (most guests will pay before thinking "I'm not paying that much to go on x"), or halfway in-between. In many scenarios, typically this would just be set to expensive and left alone, since you can add ATMs and guests will continue to gleefully withdraw from their bank account. However, if you have a scenario with no ATMs and a park goal of x number of guests (read: RCT1 scenarios), you're better off using the value price so guests will stay in the park longer.

What I'd like to do is make my plugin save the settings per-save, that way I can switch between saves and have it set the proper settings for that park without accidentally blowing away the settings in another save. This would also help prevent modifying settings in new scenarios that price things differently from how I usually want them, and provide a way of keeping track of if the user has done something with the plugin for that park (for example, setting defaults for the park).

**Comment by Ryder17z** [comment]
AdvancedTrack could also benefit from this

**Comment by James103** [comment]
The new save format could not only allow storing plugin data, but also plugin code, allowing custom scenarios to have custom challenge plugins, whereby, for example (these are just some ideas),

* You have to achieve a park value of £100,000 by October, Year 3 BUT your park value is limited to at most 101 times your park rating (implying a park rating requirement of 991).
* You have to get 4,000 guests in your park with park rating >= 700 BUT you fail if your bank balance goes below zero AND every guest takes $0.10 from your bank balance and adds it to their bank balance every in-game day.
* You have to build 10 coasters each with minimum excitement rating >= 16.00 BUT every 100 park rating reduces the required excitement rating by 1.00, down to a minimum of 7.01 at 999 park rating.
* A very long scenario where every year, there is a new goal to complete BUT also a new limitation that you have to follow. Reach October, Year 10, complete all goals, and satisfy all limitations to pass the scenario. Failure to complete the goal and follow the limitation by the end of the corresponding year fails the scenario.

**Comment by Ryder17z** [comment]
Another fun thing that might be possible is having a plugin that once you reach 800 guests enables land/build rights (owned/purchasable) 
Or you could have a plugin that affects the research que. Like if you have a park value over 100.000 euros, you unlock a new ride (e.g. Looping Coaster) (either directly or by research later)
