### ISSUE TITLE
Broken Following Train Camera? 

### ISSUE THREAD

**Issue by KevsterW21** [OpenRCT2/OpenRCT2#14683]
Windows 10
V0.3.3 New Save Test Version

So ive just been playing on the new test version & just wondered whether this "Follow train" camera issue is known to not work.  Any other version of either RCT or OpenRCT this has worked. 

![Openrct2 Screenshot 2021 05 17 - 03 40 47 21](https://user-images.githubusercontent.com/84298950/118425938-296f4200-b6c2-11eb-9029-aa5b906d4df1.png)

**Comment by YJSoft** [comment]
All issues with new save format should go to #10664

**Comment by tupaschoal** [comment]
Closing, please do as advised by @YJSoft . Thanks
