### ISSUE TITLE
Crash after adding RCT1 folder in options

### ISSUE THREAD

**Issue by AlessandroL89** [OpenRCT2/OpenRCT2#14685]
**OS:** [Windows 10]
**Version:** [0.3.3]
**Commit/Build:** [3f65f28]

After adding RCT1 (& loopy landscape) to the option of open RCT2 the game crashes at restart.
**Steps to reproduce:**
1. Install RCT2 + extensions
2. Install RCT1 + extensions
3. Copy both (RCT1) data folders from CD.
4. Select RCT1 folder in Open RCT2
5. After restart crash

Removing the RCT1 folder from config.ini solve the issue (menu appears).

[c238b54a-e9a3-43e2-b44b-5395670987a6(3f65f28_x86-64).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/6491118/c238b54a-e9a3-43e2-b44b-5395670987a6.3f65f28_x86-64.dmp.gz)

**Dump file**
Attached

**Screenshots / Video:**
Game crashes before main menu appearance.

**Save game:**
None

**Comment by Gymnasiast** [comment]
You are using a release version of OpenRCT2. Can you check if it also happens on a `develop` build?

**Comment by AlessandroL89** [comment]
Hello,

Thanks for your answer.
I installed the develop build.
It refuse to add the RCT1 installation stating that the version I have is not supported.
I attach the RCT1 window stating I have the Loopy landscape add on installed.
<img width="481" alt="RCT1" src="https://user-images.githubusercontent.com/84303466/118616931-6f133400-b7c2-11eb-98e5-66d632d1ba99.PNG">

**Comment by Gymnasiast** [comment]
Can you give me the exact error message that OpenRCT2 displays?

**Comment by AlessandroL89** [comment]
The error is:
"The specified path contains a RollerCoaster Tycoon 1 installation but this version is not suitable.
OpenRCT2 needs a Loopy Landscapes or RCT Deluxe install in order to use RollerCoaster Tycoon 1 assets."
I also tried to reinstall RCT 1 + LL and after copying some files from the Data folder (as asked by OpenRCT2) RCT 1 crash at launch with an Access Violation (Error Location: Unknown).

**Comment by Gymnasiast** [comment]
Can you give me the file sizes of csg1i.dat and csg1.dat in your RCT1 folder?

**Comment by AlessandroL89** [comment]
csg1i.dat 613.840 bytes 
CRC32: DEB6F7FF
MD5: 229E7A7D7B9A6D1CB7DE10A474378D12
SHA-1: 4D780FCB994D65FC95D7753AEE40F4A5A92BF7DA

csg1.dat 41.402.869 bytes
CRC32: F56FAA5B
MD5: 70FB4D862FC96973566F5388E2AD5C1E
SHA-1: 858866A820A22153AD029C810D3C543AB5130AF1

**Comment by Gymnasiast** [comment]
You combined a csg1i.dat file from the RCT1 base game with a csg1.dat from Loopy Landscapes. Please copy csg1i.dat from a Loopy Landscapes disc to your RCT1 folder.

**Comment by AlessandroL89** [comment]
Thanks, I was able to add the path.
In the develop build no crash at restart (I even tried to launch Forrest Frontier without any issue.
