### ISSUE TITLE
Prebuild Error

### ISSUE THREAD

**Issue by CamdenShadowWolf** [OpenRCT2/OpenRCT2#14688]
**OS:** [e.g. Windows 10]
**Version:** v0.3.3 
Commit/Build: 16c10f6 "on refs/pull/10664/merge"

This prebuild features the "general" setting of scenery.
However, I assume this error has to do with the new path support system.

![image](https://user-images.githubusercontent.com/77296291/118521913-788c9580-b709-11eb-9a22-2014868cbb9d.png)

EDIT: problem solved.  I realize I missed a bit of scenery after reselecting the default scenery.  Now if I can delete this when I get more familiar with this website...

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Comment by YJSoft** [comment]
All issues with new save format should go to #10664 (If not reproducible with develop version)

**Comment by tupaschoal** [comment]
Closing as per comment and edit of OP.
