### ISSUE TITLE
incorrect error message during construction

### ISSUE THREAD

**Issue by Ryder17z** [OpenRCT2/OpenRCT2#14708]
**OS:** Linux x64
**Version:** 0.3.3
**Commit/Build:** stable version

![image](https://user-images.githubusercontent.com/2000703/119033178-37b4ab00-b9ad-11eb-80f5-ea181940cac0.png)

- [ ] Reproducible in RCT2 (vanilla)? untested
- [ ] Specific to multiplayer? no

[Gemini City (copy).sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/6518261/Gemini.City.copy.sv6.txt)

**Comment by Ryder17z** [comment]
Ah, I didn't notice that. But the error message is wrong so i'd say it's still a bug.

**Comment by Fred-1044276** [comment]
Upon looking at it again, the real issue is that the game does not tell you "Not enough cash - requires $#####" when you try to place down a prebuilt track design that you don't have enough money for.

**Comment by Gymnasiast** [comment]
Seems to be fixed now.
