### ISSUE TITLE
Add field to JSON object to allow already-paletted images

### ISSUE THREAD

**Issue by zrowny** [OpenRCT2/OpenRCT2#14709]
Currently, when a JSON object references PNGimages to use in the game, `ParseImages()` in ImageTable.cpp _always_ tells the ImageImporter to expand the image to 32-bit depth and then convert it into the OpenRCT2 palette. It would be much better if there was a way to specify that you've already put the images into the correct palette format. We should add a flag called `keepPalette` (or similar) to the JSON image entries to tell OpenRCT2 that the image is already paletted, and there's no need to waste effort re-converting it, and potentially mess up the colors.

Once I test this a bit more I can get a PR in to change this.

**Comment by Gymnasiast** [comment]
Doesn't `"palette": "keep"` work for you? It works for the command line sprites (g1.dat/g2.dat), but we might need to add it to the JSON object sprite definitions too.

**Comment by zrowny** [comment]
It looks like that's just for building the g1/g2.dat sprite files (and not for appending an image to them, which also forces reading in PNG32 mode for some reason, but that's probably less important).

For JSON objects you can specify `"format": "raw"`, which is the same thing as setting `"forceBmp": true` for the sprite file (I'd argue that those should be changed to match), but that's separate from how the images are imported.

**Comment by duncanspumpkin** [comment]
Has been implemented
