### ISSUE TITLE
construction works despite being in "red numbers"

### ISSUE THREAD

**Issue by SevenChords** [OpenRCT2/OpenRCT2#14724]
**OS:** MacOS 10.15.7
**Commit/Build:** 9a76224

I got into negative balance (hired too many staff), but i was still able to build new rides.
This obviously shouldn't be the case.
Active Plugins:
Ride Price manager
Soft guest gap calculator
(i did a second test with the plugins removed, the bug still occured)

- [ ] Reproducible in RCT2 (vanilla)? -> can't test, but probably not
- [ ] Specific to multiplayer? -> no

**Steps to reproduce:**
1. get your balance to be negative
2. build a ride/shop

**Video:**

https://youtu.be/uPD8gGnVATg

**Save game:**

[Evergreen Gardens.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/6528437/Evergreen.Gardens.sv6.zip)

**Comment by James103** [comment]
Likely caused by 38c7a70025e7cd2054ea04c66a4bd68ffb7de4a1
From my testing:
* Bug exists in commit 38c7a70025e7cd2054ea04c66a4bd68ffb7de4a1
* Bug does not exist in previous commit 236c80fea121541d105aa16501afccb46b5b166c

**Comment by SevenChords** [comment]
also applies to advertising, you can start any advertising campaign without being checked if you have enough money
