### ISSUE TITLE
Allowed to build with negative money

### ISSUE THREAD

**Issue by adam-bloom** [OpenRCT2/OpenRCT2#14730]
**OS:** macOS
**Version:** 0.3.3-207
**Commit/Build:** 9a76224a2

The latest develop builds let you continue to build when you run out of money. The screenshot here shows a new ride that I started building without adequate funds. Previously, you'd be blocked from building and forced to increase your loan first.

<img width="503" alt="Screen Shot 2021-05-23 at 2 27 09 PM" src="https://user-images.githubusercontent.com/3771193/119275548-01587500-bbd3-11eb-8fec-e91a9991c8de.png">

This is likely a regression introduced by #14711.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Comment by James103** [comment]
Same issue as #14724, fixed by #14726

**Comment by adam-bloom** [comment]
Whoops, missed that. Thanks @James103. Closing this.
