### ISSUE TITLE
Add Too many images object selection error message

### ISSUE THREAD

**Issue by ghost** [OpenRCT2/OpenRCT2#1473]
If you pick a new ride or scenery in object selection, it doesn't get added to the game and just reverts when you open up object selection again.

**Comment by duncanspumpkin** [comment]
Working fine for me. Are you reliably able to reproduce this? Is it only on one save?

**Comment by Phasedetect** [comment]
Yep, it's an issue with the individual save. I don't know what would have caused the function to not work on it though...

**Comment by duncanspumpkin** [comment]
Can you upload the save i will take a look if you still have it.

**Comment by Phasedetect** [comment]
Here it is:

https://www.dropbox.com/s/bq7kr67l1i2w8wi/Barony%20Bridge%20-%20Expanded.sv6?dl=0

**Comment by duncanspumpkin** [comment]
This save doesn't allow any more objects as the total number of images is being reached. I'm going to change this to a request to change the error message so that people know why it is failing.

**Comment by duncanspumpkin** [comment]
I think the best approach after reading this section of code is to implement it as part of #1399 therefore I'm removing this from the milestone and it will be done later.

**Comment by duncanspumpkin** [comment]
This has since been resolved
