### ISSUE TITLE
[.park format] Scenery objects' "sceneryGroup" property not being recognized correctly

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#14736]
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** 0e13808 on refs/pull/10664/merge

Much like with the last two issues I originally reported in #10664, I created a new separate issue page for this one. This issue involves scenery objects that have a "sceneryGroup" property (e.g. the trees in the Creepy Themeing, the Stone Bench in the Egyptian Themeing). Current .park test builds fail to make the "sceneryGroup" flag work correctly, which results in something like path additions from other scenery groups not appearing in Signs and Items for Footpaths once the objects' original scenery groups have been selected.

**Steps to reproduce:**
1. Add any scenery object that has a "sceneryGroup" flag (e.g. the Stone Bench from the Egyptian Themeing) and see that it correctly appears in the Signs and Items for Footpaths default scenery group.
2. Add the scenery group that said scenery object originally comes from (e.g. Egyptian Themeing). Once you do that, the Stone Bench will no longer be in the Signs and Items for Footpaths default scenery group, instead only appearing in Egyptian Themeing.

**Screenshots:**
![Animatronic Antics 2 2021-05-21 10-38-33](https://user-images.githubusercontent.com/61885939/119385752-72ebfe00-bc7b-11eb-8ea6-a29e9289d734.png)
![Animatronic Antics 2 2021-05-21 10-38-38](https://user-images.githubusercontent.com/61885939/119385756-741d2b00-bc7b-11eb-949a-754ba27bc4a6.png)
As you can see, in these pictures, the Stone Bench, Lamp, and Egyptian Style Sign from the Egyptian Themeing do not show up in Signs and Items for Footpaths at all, only in Egyptian Themeing, even though their "sceneryGroup" flags dictate them to also appear in Signs and Items for Footpaths (rct2.scenery_group.scgpathx).

**Comment by Gymnasiast** [comment]
Has now been fixed.

**Comment by SevenChords** [comment]
still happening in 4c1ab8d on developement
