### ISSUE TITLE
Incorrect end dates for park value goal scenarios

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#14735]
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** 0e13808 on refs/pull/10664/merge

On the .park test builds, any scenario that has the "Park value at a given date" objective will have a much different end date from what it actually has, often also resulting in the end month not being October. Example: Diamond Heights with $200,000 park value at the end of **September, Year 4** instead of **October, Year 3**. This happens both in the scenario selector window and when you actually load up the scenario. Both SC6 and SC4 files are affected. This issue is again a result of an error made when importing SC6 and SC4 files.

**Steps to reproduce:**
1. Start up the game and open the scenario selector window.
2. Select any scenario that has a park value goal with an end date. Alternatively, load up an SV6 file of said scenario.
3. The incorrect end date will show in the park information window's objective tab or on the scenario selector window in the .park test build.

**Screenshots / Video:**
![Six Flags Magic Mountain 2021-05-21 11-13-58](https://user-images.githubusercontent.com/61885939/119384193-2e5f6300-bc79-11eb-9917-34b07ab1804b.png)
![Six Flags Magic Mountain 2021-05-21 11-14-39](https://user-images.githubusercontent.com/61885939/119384202-30292680-bc79-11eb-8881-8d11622fd236.png)
![Diamond Heights 2021-05-24 10-05-33](https://user-images.githubusercontent.com/61885939/119384575-c4938900-bc79-11eb-890e-1e25eae4bae0.png)
In the first screenshot, the highlighted scenario (Hamipterus Ponds) is claimed to have an end date of **June, Year 11**, which is not what I set it to. In the second screenshot, I have the same scenario highlighted in the current develop and release builds, and it correctly shows an October, Year 3 end date. In the third screenshot, I have started a new game in Diamond Heights, and it wrongly shows an end date of September, Year 4.

**Comment by IntelOrca** [comment]
This requires a fix to all languages (depending on string arg order). I have only applied fix to `en-GB` in branch.

**Comment by Gymnasiast** [comment]
Should be fixed as of https://github.com/OpenRCT2/OpenRCT2/commit/86f91585d2ce877ebc0e2945084ee003a231a861.
