### ISSUE TITLE
[2021 .Park Format] Guest complaining about getting off the wrong ride

### ISSUE THREAD

**Issue by sfisher923** [OpenRCT2/OpenRCT2#14732]
So i had a coaster Valley due to how RNG Brakes are and a Full load (96 people which are 3 trains with 32 each) were complaining about a coaster with nearly empty trains since i was busy with another part of the park  (Didn't have the ride name issue .sv6 files)

![Bug Report 2](https://user-images.githubusercontent.com/80093217/119376562-17753c80-bc8a-11eb-825b-a761ce52f91f.png)

(Arbitrary Ride Types was enabled but it wasn't for the affected rides)

**Comment by Fred-1044276** [comment]
Because this involves the new save format, can you please report this issue in #10664?

**Comment by James103** [comment]
> Because this involves the new save format, can you please report this issue in #10664?

This does not apply because of https://github.com/OpenRCT2/OpenRCT2/pull/10664#issuecomment-846944967:

> **To everyone: since this issue has become hard to go through, we are changing the way bugs are reported. You should now simply create an issue as you would for a regular bug, making sure to mention it is in the new-save-format branch.**

**Comment by IntelOrca** [comment]
I think this is already fixed.

**Comment by sfisher923** [comment]
Thanks wasn't sure since it was challenging finding particular bugs in 10664
