### ISSUE TITLE
[.park format] Custom currency exchange rate error

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#14742]
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** 5f030df on refs/pull/10664/merge

In the current .park format test builds, changing to custom currency brings up the usual window where you can specify and make your own custom currency. However, the exchange rate is shown to be a lot bigger than normal. I suspect this is related to currency 64.

**Steps to reproduce:**
1. Open the Options window and change currency to "Custom currency"
2. The exchange rate box in the custom currency window will show a wildly inflated number instead of the number you previously set

**Screenshot:**
![Fred's Workbench 2021 2021-05-25 09-12-48](https://user-images.githubusercontent.com/61885939/119533896-2b2cab80-bd3b-11eb-9180-12f70438aa6e.png)
The exchange rate I use for custom currency is 10, but here it's shown to be a lot bigger than normal.

**Comment by ZehMatt** [comment]
This should be fixed with the commit https://github.com/OpenRCT2/OpenRCT2/pull/10664/commits/426d9d264df9eaf842dddbd69ba45b576f52ff8e

Please leave a comment if the problem still persists.
