### ISSUE TITLE
NSF: Ride window does not follow the selected car

### ISSUE THREAD

**Issue by Ryder17z** [OpenRCT2/OpenRCT2#14748]
![image](https://user-images.githubusercontent.com/2000703/119611680-4a8b0d80-bdfb-11eb-9751-3d0a0fbca7a8.png)

version: AppImage x64-64

**Comment by ZehMatt** [comment]
Please provide a save file

**Comment by ZehMatt** [comment]
I can't reproduce this, works on my end
![image](https://user-images.githubusercontent.com/5415177/119654747-70330980-be31-11eb-8d3b-87e5cb322853.png)

Please try the latest commit, if it still exists let me know.

**Comment by ZehMatt** [comment]
I don't think you are on the latest version

**Comment by Ryder17z** [comment]
> I don't think you are on the latest version

oh. AppImage zip file says 7th may.
I'm currently unable to compile openrct2 because I have some update packages that are suddenly conflicting.

I'll try compiling on windows because that bin is from the same date.

**Comment by ZehMatt** [comment]
You can always pick up the artifacts you don't have to build it by the way.

**Comment by Ryder17z** [comment]
sorry, but where is the install location on linux? (arch/manjaro)

**Comment by Ryder17z** [comment]
tried compiling from source 2-3 hours ago and it is successful but does not run (windows x64)

**Comment by Ryder17z** [comment]
It is indeed fixed.
