### ISSUE TITLE
NSF: Virginia Reel; ride track/supports z-fighting

### ISSUE THREAD

**Issue by Ryder17z** [OpenRCT2/OpenRCT2#14749]
![image](https://user-images.githubusercontent.com/2000703/119612206-e87ed800-bdfb-11eb-818d-67f4c8d11f8a.png)

This only happens at the two closest zoom levels. 
Version: AppImage x86-64

**Comment by James103** [comment]
Do you have a save file to reproduce this using? If so, can you please post it here?

**Comment by Fred-1044276** [comment]
Doesn't this also happen with any ride type that uses the wooden/lattice supports?

**Comment by Ryder17z** [comment]
> Doesn't this also happen with any ride type that uses the wooden/lattice supports?

I'm not aware of any other rides that this occurs on. Also it is limited to a certain rotation.

[yada yada NSF.park.zip](https://github.com/OpenRCT2/OpenRCT2/files/6548361/yada.yada.NSF.park.zip)

**Comment by ZehMatt** [comment]
Have you checked that this is also not happening on develop?

**Comment by Ryder17z** [comment]
> Have you checked that this is also not happening on develop?

I cannot reproduce it on develop.

**Comment by Ryder17z** [comment]
seems fixed
