### ISSUE TITLE
[.park format] Mechanics ignoring Ride IDs above 255

### ISSUE THREAD

**Issue by sfisher923** [OpenRCT2/OpenRCT2#14745]
Steps to produce

 1)Build 256+ Rides/Stalls
 2)Have the Rides with an ID above 255 breakdown
![Bug Report 3.zip](https://github.com/OpenRCT2/OpenRCT2/files/6544146/Bug.Report.3.zip)

In the Save there are 3 Broken Rides a Looping Coaster a Floorless Coaster and a Corkscrew Coaster

.The Looping Coaster - Ride ID 256
.The Corkscrew Coaster - Ride ID 255
.The Floorless Coaster  - Ride ID 075

(Edit Updated Save with matching description)

**Comment by ZehMatt** [comment]
I'm unable to load this save file, are you on the latest commit?

**Comment by sfisher923** [comment]
Oops Sorry

**Comment by YJSoft** [comment]
You can download latest Artifacts based on 6e60996 [here](https://github.com/OpenRCT2/OpenRCT2/actions/runs/872462617)

**Comment by sfisher923** [comment]
Hopefully the New Save works
