### ISSUE TITLE
Clicking scenery with eyedropper tool causes insta-crash.

### ISSUE THREAD

**Issue by StrangeAnomoly** [OpenRCT2/OpenRCT2#14756]
**OS:** [Windows 10]
**Version:** [v0.3.3]
**Commit/Build:** [16c10f6]
[New Save Format]

Clicking scenery with eyedropper tool causes insta-crash.

- [ X ] Reproducible in RCT2 (vanilla)?
- [ X ] Specific to multiplayer?

**Comment by Gymnasiast** [comment]
You’re on an ancient build. This has been reported hundreds of times and has been fixed last weekend.
