### ISSUE TITLE
Latest New Save Format Build appears to be corrupted for me.

### ISSUE THREAD

**Issue by StrangeAnomoly** [OpenRCT2/OpenRCT2#14759]
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** a9cO3e3
[New Save Format] 

Seems the latest build of the new save format is corrupted for me for some reason. Keeps saying "Error loading objects for park". Even when Download All is selected and the park is reopened it gives the same error.

I've downloaded the build twice and this happens every time

**Screenshots / Video:**
![OpenIssue](https://user-images.githubusercontent.com/41911850/119836193-6ffe4100-bef9-11eb-9c90-77b959561611.PNG)

**Comment by James103** [comment]
1. Did you link your RCT2 and RCT1 installations to OpenRCT2?
2. Have you verified the integrity (i.e. re-downloaded/re-installed if necessary) of your RCT2 and RCT1 installations?
3. Does the latest [develop](https://openrct2.org/downloads/develop/latest) build of OpenRCT2 start up and load the title parks properly?

**Comment by X123M3-256** [comment]
It looks like your JSON objects are either missing or out of date.

**Comment by StrangeAnomoly** [comment]
for more context 
![DevOpe](https://user-images.githubusercontent.com/41911850/119840959-5101ae00-befd-11eb-9a66-bd7dd56b25a2.PNG)

Develop is on the left.
Open is on the right.

**Comment by StrangeAnomoly** [comment]
Ok this is weird. I've download an earlier build of the new save format and I don't have the problem anymore.
![NewWork](https://user-images.githubusercontent.com/41911850/119841754-fddc2b00-befd-11eb-973f-f2906dff486b.PNG)

**Comment by StrangeAnomoly** [comment]
Here's the missing files when I try to open leafy Lake
rct2.ride.ptct1
rct2.ride.arrsw1
rct2.ride.batfl
rct2.ride.mono1
rct2.ride.mono2
rct2.ride.rboat
rct2.ride.nrl
rct2.ride.ding1
rct2.ride.obs1
rct2.ride.amt1
rct2.ride.clift1
rct2.ride.rcr
rct2.ride.kart1
rct2.ride.rapboat
rct2.ride.lfb1
rct2.ride.dodg1
rct2.ride.mgr1
rct2.ride.fwh1
rct2.ride.hhbuild
rct2.ride.icecr1
rct2.ride.drnks
rct2.ride.chpsh
rct2.ride.hmaze
rct2.ride.infok
rct2.ride.hskelt
rct2.ride.bboat
rct2.ride.balln
rct2.ride.cndyf
rct2.ride.cboat
rct2.ride.rckc
rct2.ride.burgb
rct2.ride.popcs
rct2.ride.pizzs
rct2.footpath_banner.bn1
rct2.footpath_banner.bn2
rct2.footpath_banner.bn3
rct2.footpath_banner.bn4
rct2.footpath_banner.bn5
rct2.footpath_banner.bn6
rct2.footpath_banner.bn7
rct2.footpath_banner.bn8
rct2.footpath_banner.bn9
rct2.footpath_item.bench1
rct2.terrain_surface.grass
rct2.terrain_surface.sand
rct2.terrain_surface.dirt
rct2.terrain_surface.rock
rct2.terrain_surface.martian
rct2.terrain_surface.chequerboard
rct2.terrain_surface.grass_clumps
rct2.terrain_surface.ice
rct2.terrain_surface.grid_red
rct2.terrain_surface.grid_yellow
rct2.terrain_surface.grid_purple
rct2.terrain_surface.grid_green
rct2.terrain_surface.sand_red
rct2.terrain_surface.sand_brown
rct1aa.terrain_surface.roof_red
rct1ll.terrain_surface.roof_grey
rct1ll.terrain_surface.rust
rct1ll.terrain_surface.wood
rct2.terrain_edge.rock
rct2.terrain_edge.wood_red
rct2.terrain_edge.wood_black
rct2.terrain_edge.ice
rct1.terrain_edge.brick
rct1.terrain_edge.iron
rct1aa.terrain_edge.grey
rct1aa.terrain_edge.yellow
rct1aa.terrain_edge.red
rct1ll.terrain_edge.purple
rct1ll.terrain_edge.green
rct1ll.terrain_edge.stone_brown
rct1ll.terrain_edge.stone_grey
rct1ll.terrain_edge.skyscraper_a
rct1ll.terrain_edge.skyscraper_b
rct2.station.canvas_tent
rct2.station.castle_grey
rct2.station.castle_brown

**Comment by IntelOrca** [comment]
@StrangeAnomoly when you download the latest NSF build, do you get the portable one and extract it to a new clean empty folder?

**Comment by StrangeAnomoly** [comment]
@IntelOrca No I didn't. I did the auto install.

**Comment by IntelOrca** [comment]
@StrangeAnomoly can you try the portable zip, extracting to a clean folder and run the openrct2.exe that is in that?

**Comment by StrangeAnomoly** [comment]
@IntelOrca It works now. That's strange.

**Comment by Gymnasiast** [comment]
It's not strange at all. You didn't properly install it and mixed old and new files.
