### ISSUE TITLE
[new save file format] Path/Railing is ignored in multiplayer in some scenarios in multiplayer

### ISSUE THREAD

**Issue by tymondouglas** [OpenRCT2/OpenRCT2#14757]
**OS:** Windows 10
**Version:** 0.3.3 - Removing limits build
**Commit/Build:** 5f030df

Path/Railing is ignored in multiplayer, the first type of path/railing is always used instead.
Can reproduce consistently on Arid Heights and on other scenarios, doesn't seems to affect RCT1 scenarios.

- [ ] Reproducible in RCT2 (vanilla)?
- [X] Specific to multiplayer?

**Steps to reproduce:**
1. Start a server ( doesn't matter the type of server )
2. Build an elevated path

**Screenshots / Video:**

First type of path / railing selected, works fine
![image](https://user-images.githubusercontent.com/84814396/119754145-6aabe280-be76-11eb-817d-647f7cd7c124.png)
Different type of path / railing selected, correct type shows up on the preview, but when you place it reverts to the first type.
![image](https://user-images.githubusercontent.com/84814396/119754194-81ead000-be76-11eb-9fa1-96d64c0aa535.png)

**Save game:**
Scenario used to test
[Park Sorrow.zip](https://github.com/OpenRCT2/OpenRCT2/files/6550621/Park.Sorrow.zip)

**Comment by tymondouglas** [comment]
I created a video demonstrating the issue. On Forest Frontiers i can change the path but not the railing, i guess it is because the wooden railing allows for other types of paths.
On Arid Heights i can't change neither. It stays stuck on the black path on black railings/supports.
https://www.youtube.com/watch?v=M3iPFf3unv4

**Comment by TheClaudeQC** [comment]
it's also do it in singleplayer. I tested it out

**Comment by IntelOrca** [comment]
Resolved
