### ISSUE TITLE
saving and loading a park unlocks all unlockable scenery

### ISSUE THREAD

**Issue by SevenChords** [OpenRCT2/OpenRCT2#14774]
**OS:** macOS 10.15.7
**Commit/Build:** 4c1ab8d

upon starting a new scenario, if you save it and then load that saved game, all unlockable scenery for that scenario is instantly unlocked

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. open a new scenario that has scenery that can be unlocked using research
2. save the game
3. load the save file

**Screenshots / Video:**

https://youtu.be/eRv9BC--Gm0

**Comment by Fred-1044276** [comment]
Accessing the invention list locks the researchable scenery again. However, I made a scenario a while back which always had this issue persistent, and I will assume it is a data file bug.
