### ISSUE TITLE
signs appearing in the wrong scenery groups

### ISSUE THREAD

**Issue by SevenChords** [OpenRCT2/OpenRCT2#14773]
**OS:** macOS 10.15.7
**Commit/Build:** 4c1ab8d

Only the default style sign appears in the scenery group with the footpath items, every other style of that sign only appears in its respective theme group, if that one hasn't been researched it appears in miscellaneous objects. This appears to happen with any object that is included in 2 different scenery groups in vanilla RCT.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. open game, start new park, check scenery groups (example: fun fortress)

**Screenshots / Video:**

<img width="641" alt="Screenshot 2021-05-28 at 16 57 33" src="https://user-images.githubusercontent.com/31819497/120013678-520c0b80-bfe1-11eb-8fa9-1fc490cc0ce3.png">
<img width="631" alt="Screenshot 2021-05-28 at 16 57 42" src="https://user-images.githubusercontent.com/31819497/120013689-56382900-bfe1-11eb-8f78-08d95b450332.png">

**Comment by Gymnasiast** [comment]
Cannot reproduce as of c9731a8ba92450ea2f5098799344544b7aa541c9.
