### ISSUE TITLE
broken values for park objectives

### ISSUE THREAD

**Issue by justin3031** [OpenRCT2/OpenRCT2#14790]
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** 16c10f6

- [no] Reproducible in RCT2 (vanilla)?
- [no] Specific to multiplayer?

**Steps to reproduce:**
1. make a scenario in the editor
2. for park objective choose: park value, repay loan and achieve park value, monthly profit from food/merchandise

**Screenshots / Video:**
![broken_numbers](https://user-images.githubusercontent.com/85035899/120096067-a9b58e80-c129-11eb-84af-0b6b943c3eed.png)

**Comment by duncanspumpkin** [comment]
Has been resolved.
