### ISSUE TITLE
[.park format] No in-game sound if view is in certain rotations on huge maps

### ISSUE THREAD

**Issue by Fred-1044276** [OpenRCT2/OpenRCT2#14798]
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** fe939ec on new-save-format

If the view is rotated to face either east or west (denoted by the map icon's compass pointing right or left), then no in-game sound aside from the UI can be heard. Currently not sure if this is caused by an antivirus, but I don't think an antivirus should cause this issue to occur. I have only managed to trigger this issue on maps with a park size larger than 254x254 because I tried to replicate this issue on an SC6 like [European Extravaganza 2](https://drive.google.com/file/d/1NccE15n1hovmgKgXLePH4QaOLHpB40Q4/view?usp=sharing) and the issue did not occur whatsoever.

**Steps to reproduce:**
1. Open any scenario or park with a map size larger than 254x254
2. Build a few rides and let them test
3. Rotate the view to face either east or west

**Video:**
[Video showcasing the bug](https://youtu.be/p2_IZSbwGEI)
In the video, you can see that the sound works perfectly fine (we can hear the hyper-twister trains rolling through the track), but as soon as the view is rotated to either west or east, the sound disappears.

**Save game:**
[Fred's Workbench 2021 (999x999)](https://drive.google.com/file/d/1SbCehqL9O86CKsranQSFd2-Iyhq5CMZb/view?usp=sharing)
The .park file is where I got the issue to occur. I started noticing it while messing around with the RCT2 junior coaster default pre-built track designs.

**Comment by duncanspumpkin** [comment]
Confirmed that it happens. Best technique is to put a coaster in the top left corner of a 999x999 map i.e. at around 999,999 suspect the issue is with VehicleSoundParams as it has some int16_t x,y coordinates. I can't work out how best to change them though @IntelOrca any ideas.

**Comment by Fred-1044276** [comment]
I'd also like to clarify that ride music doesn't get affected.
