### ISSUE TITLE
Guest can't sit down in benches

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#14792]
Windows 10
Dev. Build (the accesseble one in 16th may 2021)

Guest can't sit down for odd reasons in this version, i don't know if there been newer version, fixing this one.

Not receateble in Vanilla
No, also not specific to multiplayer

**Steps to reproduce:**
1. get benches in paths
2. let guest have food
3. Done

**Dump file**

**Screenshots / Video:**
![Bac à sable 2021-05-30 09-22-40](https://user-images.githubusercontent.com/83843734/120105998-4af01500-c129-11eb-9081-0456f8292b8a.png) -->

**Comment by TheClaudeQC** [comment]
for odd reason, now they do, as i maybe removed the scenery

**Comment by TheClaudeQC** [comment]
So, when having scenery, they can't sit down.

**Comment by Gymnasiast** [comment]
List the commit/build properly, please. We ask it for a reason.

**Comment by Gymnasiast** [comment]
Since you refused to list the commit, I have no other option that to close this. If you want an issue fixed, provide the information we ask for.
