### ISSUE TITLE
[.park Format] Can place banner but can't make it a "No Entry" 

### ISSUE THREAD

**Issue by sfisher923** [OpenRCT2/OpenRCT2#14793]
Version: 0.3.3
Commit/Build: debbc03 (May 26th 2021)

I'm playing a park and I have some banners for things like Ride Exits but I added and ran across a blank error message when trying to make a new one "No Entry" (Leaning towards a differences in Limits for No Entry Signs vs Banners themselves as my best guess)

**Steps to reproduce:**
1. Place Banners 
2. Set them to "No Entry" until a blank error appear

**Screenshot**
![Bug Report 4](https://user-images.githubusercontent.com/80093217/120110318-f9e91c80-c13a-11eb-8828-2257914a6984.jpg)
**Save game:**
[Bug Report 4.zip](https://github.com/OpenRCT2/OpenRCT2/files/6566435/Bug.Report.4.zip)

**Comment by duncanspumpkin** [comment]
I cant reproduce this when creating new banners on your save. The save in question has banner id 232 so below the old limit anyway. Looks to be a mistake when creating the banner.

**Comment by sfisher923** [comment]
Okay

**Comment by IntelOrca** [comment]
I can not reproduce this with a new new park.

**Comment by sfisher923** [comment]
Want me to close it then

**Comment by IntelOrca** [comment]
@sfisher923 if you get it again, we can re-open.
