### ISSUE TITLE
isBanner scenery wall flag should be renamed to isDoubleSided

### ISSUE THREAD

**Issue by ZeeMajora** [OpenRCT2/OpenRCT2#14804]
This flag makes a scenery wall double sided, It does not make it a banner by itself.
So it should be renamed as it's current name is confusing and inaccurate.
Example of a double sided wall that uses isBanner: https://github.com/OpenRCT2/objects/blob/master/objects/rct2/scenery_wall/rct2.scenery_wall.walltxgt.json

**Comment by duncanspumpkin** [comment]
Suspect it will need to be split into two flags most likely.

**Comment by KirilAngelov** [comment]
Hello, can I try this one? It will be my first issue and some information where to change this will be great.

**Comment by duncanspumpkin** [comment]
@KirilAngelov this will need a bit of investigation to explore all users of the flag in the code to determine if it is being used for two separate features before being renamed.

**Comment by duncanspumpkin** [comment]
I've confirmed that it is only being used incorrectly. Rename it in src/openrct2/world/scenery.h WALL_SCENERY_IS_BANNER.
Its mistakenly used in tileinspector.cpp just remove all of:
```
                const auto wallEntry = tileElement->AsWall()->GetEntry();
                if (wallEntry != nullptr && wallEntry->wall.flags & WALL_SCENERY_IS_BANNER)
                {
```
You will also need to adjust WallObject.cpp to add isDoubleSided as an additional flag. Will look a bit of a mess as you need to keep isBanner for backwards compatibility for now.

**Comment by KirilAngelov** [comment]
I can't seem to find the code snippet in TileInspector.cpp even using search.

**Comment by duncanspumpkin** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/fd4a798cfb508c667d1b52c0c5852b80f17c890d/src/openrct2-ui/windows/TileInspector.cpp#L2099
