### ISSUE TITLE
Guests can't follow the path or drawn into void at the park entrance if the path is sloped

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#14814]
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** 425f968

I think there were similar issues like this so I have no idea whether it is a duplicated one.

If the path right after the park entrance is sloped upward, some guests can't follow the path or they are drawn into the void.
If I try this on the other blank map, then guests can't follow the path.

**Steps to reproduce:**
1. Download the scenario: [Secret garden.zip](https://github.com/OpenRCT2/OpenRCT2/files/6593436/Secret.garden.zip)
2. Hide landscape & rides & scenaries to see peeps well (click hotkey: H, V, 3, 5)
3. Click 'Large Tram' Cheat to spawn many guests
4. See that guests are drawning into the void.

**Screenshots / Video:**
In the 'Secret garden' map:
![1](https://user-images.githubusercontent.com/10726524/120689124-bb5ab580-c4de-11eb-9430-0118fccb22be.gif)

Tries on the other blank map:
![2](https://user-images.githubusercontent.com/10726524/120690039-b0eceb80-c4df-11eb-997a-2d87f30bf029.gif)

**Save game:**
[Secret garden.zip](https://github.com/OpenRCT2/OpenRCT2/files/6593436/Secret.garden.zip) (originally from https://rctsc.telk.kr/download?no=849)

**Comment by duncanspumpkin** [comment]
This is a duplicate. Its quite hard for this to be changed due to how peeps enter the park

**Comment by YJSoft** [comment]
#14486

**Comment by telk5093** [comment]
Then let's keep tracking on #14486 :)
