### ISSUE TITLE
Some train can't be fully recolored in the new save build

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#14823]
Windows 10
0.3.3
New save files build (may 16th)

Well, some trains misses some colors mods. I using this one since the 2 last versions of the new save files are unstable in my taste. Older scenario corrupted or removed (worser in the last one, as even my sandbox wasn't accesible).

No, it's was possible to change the color
No, i was in singleplayer

**Steps to reproduce:**
1. Get a tramway or a horse train
2. check color
3. done!

**Screenshots / Video:**

**Comment by Gymnasiast** [comment]
You didn’t specify the commit, as WE ASKED YOU SEVERAL TIMES NOW. You didn’t add a screenshot. You didn’t upload an affected save. You have about the vaguest description humanly possible. And you still expect us to understand the problem here?!

**Comment by TheClaudeQC** [comment]
hum, i throuth it was there, i add the link, i think it need a more specific screenshot

**Comment by TheClaudeQC** [comment]
Oh, welp, it's fixed on the new one. i was using an older one (tramway train rn)
