### ISSUE TITLE
Opening this .PARK file will drop you back to the title screen after a short blip

### ISSUE THREAD

**Issue by bigshootergill** [OpenRCT2/OpenRCT2#14822]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.3.3]
**Commit/Build:** [e.g. 426e106]

After the first release of the new save format, I saved one of my recent parks in the PARK format. However when I just tried to open it with the latest update, the PARK file won't open. The file is in the next commend in this thread, it wasn't visibly attached in this comment.

Edit Michael: it prints `Value is incompatible with internal type.` to the console.

**Steps to reproduce:**
1. Try to open the PARK file I attached in the ZIP

**Comment by bigshootergill** [comment]
[CoQQ PARK File.zip](https://github.com/OpenRCT2/OpenRCT2/files/6602463/CoQQ.PARK.File.zip)

**Comment by Gymnasiast** [comment]
You didn’t specify the commit (which the form asks you to), and you didn’t say what the error was - we need the exact text of the error, or even a screenshot in a pinch. Please provide that info, especially the error text.

**Comment by bigshootergill** [comment]
Sorry, first time posting in Github. I didn't include that because was no error text. When I tried to open the park, the title screen blips for a split second and then just stays on the title screen.

~ bsg ~


________________________________

**Comment by Gymnasiast** [comment]
Ah, I understand. That in itself is certainly worth mentioning.

**Comment by IntelOrca** [comment]
Now fixed

**Comment by Gymnasiast** [comment]
https://github.com/OpenRCT2/OpenRCT2/pull/10664/commits/620b4040216d6dadf1240107be2feea32deb79aa
