### ISSUE TITLE
Can't open .park files in new build.

### ISSUE THREAD

**Issue by esojka** [OpenRCT2/OpenRCT2#14827]
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** 4f52231

After installing new interim build of new save file branch, can't open any older .park files.  

 

- [ ] Reproducible in RCT2 (vanilla)? No since .park files aren't supported in that version
- [ ] Specific to multiplayer? unsure

**Steps to reproduce:**
1. On title screen, click "Continue playing a saved game"
2. Choose a .park file created in a previous build
3. The park doesn't load and returns to the title screen.  No error or other message is displayed.  

**Save game:**

**Comment by duncanspumpkin** [comment]
Although we do try to support the older park files we don't guarantee it atm until we do the final release.

**Comment by esojka** [comment]
fair enough.  It's beta software and all that.  Should there be a message or other indication that the format has changed and might not be supported?

**Comment by duncanspumpkin** [comment]
We have hopefully fixed the bug that caused it not to be supported so the next version you test should be able to recover that save.

**Comment by Gymnasiast** [comment]
I have updated the links in the document: https://docs.google.com/document/d/1ehVshVp2EGCMS50UdgOq7OrPrHwFAZ3xm4g6dNGlpNY

Please try it with the build listed there.

**Comment by esojka** [comment]
I can open the file now.  I'll test further with this build;  this issue can be closed.   Thanks for the response!
