### ISSUE TITLE
[Experimental] OpenRCT2 Portable: Parks fail to load if installed in alternate directory

### ISSUE THREAD

**Issue by imbw267** [OpenRCT2/OpenRCT2#14829]
**OS:** Windows 10
**Version:** v0.3.3
**Commit/Build:** 4f5231

Experimental build fails to load parks.  Main title screen is blank due to failing to load park.

Attempting to open a "Forest Frontiers" scenario has the following objects fail to load:

rct2.ride.ptct1
rct2.ride.arrsw1
rct2.ride.mono1
rct2.ride.mono2
rct2.ride.rboat
rct2.ride.nrl
rct2.ride.ding1
rct2.ride.obs1
rct2.ride.clift1
rct2.ride.rcr
rct2.ride.lfb1
rct2.ride.dodg1
rct2.ride.mgr1
rct2.ride.fwh1
rct2.ride.hhbuild
rct2.ride.hskelt
rct2.ride.drnks
rct2.ride.burgb
rct2.ride.icecr1
rct2.ride.infok
rct2.ride.hmaze
rct2.ride.chpsh
rct2.ride.balln
rct2.ride.cndyf
rct2.ride.popcs
rct2.ride.pizzs
rct2.footpath_banner.bn1
rct2.footpath_banner.bn2
rct2.footpath_banner.bn3
rct2.footpath_banner.bn4
rct2.footpath_banner.bn5
rct2.footpath_banner.bn6
rct2.footpath_banner.bn7
rct2.footpath_banner.bn8
rct2.footpath_banner.bn9
rct2.footpath_item.bench1
rct2.terrain_surface.grass
rct2.terrain_surface.sand
rct2.terrain_surface.dirt
rct2.terrain_surface.rock
rct2.terrain_surface.martian
rct2.terrain_surface.chequerboard
rct2.terrain_surface.grass_clumps
rct2.terrain_surface.ice
rct2.terrain_surface.grid_red
rct2.terrain_surface.grid_yellow
rct2.terrain_surface.grid_purple
rct2.terrain_surface.grid_green
rct2.terrain_surface.sand_red
rct2.terrain_surface.sand_brown
rct1aa.terrain_surface.roof_red
rct1ll.terrain_surface.roof_grey
rct1ll.terrain_surface.rust
rct1ll.terrain_surface.wood
rct2.terrain_edge.rock
rct2.terrain_edge.wood_red
rct2.terrain_edge.wood_black
rct2.terrain_edge.ice
rct1.terrain_edge.brick
rct1.terrain_edge.iron
rct1aa.terrain_edge.grey
rct1aa.terrain_edge.yellow
rct1aa.terrain_edge.red
rct1ll.terrain_edge.purple
rct1ll.terrain_edge.green
rct1ll.terrain_edge.stone_brown
rct1ll.terrain_edge.stone_grey
rct1ll.terrain_edge.skyscraper_a
rct1ll.terrain_edge.skyscraper_b
rct2.station.canvas_tent
rct2.station.castle_grey
rct2.station.castle_brown

- [No] Reproducible in RCT2 (vanilla)?
- [No] Specific to multiplayer?

**Steps to reproduce:**
1. Install OpenRCT2 [v0.3.3 stable] in ~\Documents\OpenRCT2
2. Install Experimental OpenRCT2 Portable EXE in an alternate folder [**NOT** ~\Documents\OpenRCT2]
3.  Open Experimental OpenRCT2 Portable EXE file
4.  Attempt to load RCT1 scenario "Forest Frontiers"

**Dump file**
No Dump File created.

**Screenshots / Video:**

Directory where Portable Version was installed:
![portable_install](https://user-images.githubusercontent.com/25447160/120907227-d6880b00-c62d-11eb-82a0-f931409fbfad.PNG)

Visual artifacts on Title screen due to park load failure:
![Failure_to_load_Forest_Frontiers](https://user-images.githubusercontent.com/25447160/120907195-8dd05200-c62d-11eb-8346-111e9576f2ed.png)

**Save game:**
No Save Game Required, RCT1 installation from GOG or Steam recommended.

**Comment by imbw267** [comment]
Track Designer is working properly, so it is able to reference RCT2 objects/install directory correctly.

**Comment by Gymnasiast** [comment]
Does this still occur?

**Comment by imbw267** [comment]
Portable works fine as as a standalone on build 0.4.15
It pulls data from ~\Documents\OpenRCT2 concerning object loading, making the folder (~\Documents\OpenRCT2) if it doesn't exist.
Hiding the original ~\Documents\OpenRCT2 forces it to reload the original RCT2 path and campaign progress
Consider the issue closed
