### ISSUE TITLE
Clicking "Locate this on Main view" while following a train/car moves the camera to 1,1

### ISSUE THREAD

**Issue by Grootie** [OpenRCT2/OpenRCT2#14826]
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** 4f52231

When clicking the "Locate this on Main view" while following a train/car the camera centers to tile 1,1.
The button works fine for overall view/station.

**Steps to reproduce:**
1.  Click on any ride with a train/car
2.  Select a train/car to view in the ride inspector
3.  Click the "Locate this on Main view" button

**Screenshots / Video:**

https://www.youtube.com/watch?v=d7PxYMS0xGg

**Comment by duncanspumpkin** [comment]
Fixed in latest build
