### ISSUE TITLE
"Map elements limit has been reached" with an almost empty map

### ISSUE THREAD

**Issue by CamdenShadowWolf** [OpenRCT2/OpenRCT2#14848]
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** 072772a [Develop]

![image](https://user-images.githubusercontent.com/77296291/121210033-59d17880-c849-11eb-8bc7-422f14cad358.png)

I am currently in a personal test park.
It appears to be a counting issue of some kind, probably something's forgetting to remove the count when it happens.
I recall having an error similar to this last month, where there were "too many banners" despite the fact that I didn't have more than 10 of them on my test park.

**Comment by Gymnasiast** [comment]
Caused by https://github.com/OpenRCT2/OpenRCT2/commit/072772af7bb81298fa2844da1763b66223218e6a. 
@duncanspumpkin

**Comment by duncanspumpkin** [comment]
Can you provide a save for this as i can't reproduce it on my end.

**Comment by CamdenShadowWolf** [comment]
> 
> 
> Can you provide a save for this as i can't reproduce it on my end.

I tried to replicate the problem myself by recreating the ride, even deleting some stuff like before, but no luck here as well.  It's as if the problem fixed itself.  Odd as it sounds.  If I encounter this issue again, I'll be sure to save and share ASAP.

**Comment by duncanspumpkin** [comment]
When you save the tile elements get reorganised and any fragmentation will get filled. I suspect what has happened is that for some reason it has not reorganised after hitting the limit. Normally when you hit the limit it will automatically reorganise and recheck that there is enough space without you noticing.
