### ISSUE TITLE
[Plug-in] Subscribing to a non-existing event crashes game

### ISSUE THREAD

**Issue by oli414** [OpenRCT2/OpenRCT2#14853]
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** 072772a

Plugins that subscribe to an event that doesn't exist (or isn't available in the current version of the game) cause a crash.
This should be handled as a JS error or warning, or at most a plugin crash. Instead of causing the game to crash as a whole.

**Steps to reproduce:**
1. install the following plugin:
```
var main = function () {
    context.subscribe("not.existing", function (e) {
        console.log("Bug");
    });
};

registerPlugin({
    name: 'DebugPlugin',
    version: '1.0',
    licence: 'MIT',
    authors: ['Oli414'],
    type: 'local',
    main: main
});
```
2. Load a park

**Dump file**
[9069eefb-7212-417f-8ab7-e58e1143d754(072772a_x86-64).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/6618674/9069eefb-7212-417f-8ab7-e58e1143d754.072772a_x86-64.dmp.gz)

**Comment by tupaschoal** [comment]
Probably has to do with how `duk` macros behave on `Release`, as on debug builds it handles the error gracefully.

**Comment by oli414** [comment]
Aha that'd make sense. It should probably just throw a JS error, it's not a critical failure

**Comment by James103** [comment]
The game still crashes when attempting the above steps.
### Operating System
Windows 10, 64 bit

### OpenRCT2 build
OpenRCT2, v0.3.4.1 (5087e77) provided by GitHub
Windows (x86-64)

### Dump files
[0b71444c-e5ae-47ca-8d81-99e6e33fa14e(5087e77_x86-64).zip](https://github.com/OpenRCT2/OpenRCT2/files/7026469/0b71444c-e5ae-47ca-8d81-99e6e33fa14e.5087e77_x86-64.zip)
[7b5d9d67-d7a0-4480-a3a2-b5d32c5cf764(5087e77_x86-64).zip](https://github.com/OpenRCT2/OpenRCT2/files/7026470/7b5d9d67-d7a0-4480-a3a2-b5d32c5cf764.5087e77_x86-64.zip)

**Comment by oli414** [comment]
The issue is currently still open, so no fix has been made yet I'm afraid.

**Comment by ZehMatt** [comment]
The crash comes from calling duk_error which uses longjmp and then ends up in std::function destructor crashing, there is something wrong with the unwinding I think.

**Comment by IntelOrca** [comment]
Relevant: https://github.com/OpenRCT2/OpenRCT2/issues/14259
If duktape is compiled to throw exception instead of longjmp, this issue would be resolved.

**Comment by ZehMatt** [comment]
> Relevant: #14259
> If duktape is compiled to throw exception instead of longjmp, this issue would be resolved.

Could you do that? I looked into the library thing but I wasn't sure on how I would go on about it.

**Comment by IntelOrca** [comment]
@ZehMatt the plan was for it to be part of libsawyer, but incorporating that is a big job.

**Comment by ZehMatt** [comment]
> @ZehMatt the plan was for it to be part of libsawyer, but incorporating that is a big job.

What has scripting to do with libsawyer? It would be generally better if it wouldn't be a single library, monolithic components are bad. So no upgrade until this library?

**Comment by ZehMatt** [comment]
Still happening even with exceptions enabled instead of setjmp
