### ISSUE TITLE
Cannot paste elements or insert corrupt elements in Tile Inspector

### ISSUE THREAD

**Issue by Basssiiie** [OpenRCT2/OpenRCT2#14854]
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** 072772a

Pasting tile elements after copying them in the Tile Inspector causes blank error to appear and paste not happening. The same occurs with inserting corrupt element.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open Tile Inspector.
2. Copy an element.
3. Paste an element.

or
1. Open Tile Inspector.
2. Insert a corrupt element on any tile.

**Screenshots / Video:**

https://user-images.githubusercontent.com/20048660/121250509-15c09100-c8a6-11eb-9e1f-62ed92ca2922.mp4

**Comment by ZxBiohazardZx** [comment]
Issue is double !! in the @duncanspumpkin Commit https://github.com/OpenRCT2/OpenRCT2/commit/92cc559cf3683956e76854855bec05b4d63dea23


![image](https://user-images.githubusercontent.com/601070/121252273-178b5400-c8a8-11eb-84a8-f69fcaeaa425.png)
