### ISSUE TITLE
Cannot open original save windows when compiling on Linux/Cmake

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#1486]
When you try to save a track design in the Roller Coaster Designer or click 'Open new window' on the load/save window, the game should open a Windows load/save dialogue window. But it doesn't; nothing happens.

**Comment by MaikelS11** [comment]
Did you use Windows? Or Linux (wine)?
It works well on Windows here.. (with the latest develop version)

**Comment by Gymnasiast** [comment]
I run the game via Wine on Ubuntu 14.04. It did work until recently, though.

**Comment by Gymnasiast** [comment]
I found the cause: it doesn't work when you compile with Cmake.

**Comment by janisozaur** [comment]
The cause is wrong window handle when calling out to `GetOpenFileNameW` in when `type == 1`.

I verified this by checking `GetLastError` before and after that call, after the call it returned `ERROR_INVALID_WINDOW_HANDLE`.

On my local linux (arch, wine-1.7.51, mingw 5.2.0), HWND returned from `windows_get_window_handle` is `0x2009e00`

I have no idea what a valid handle should look like.

**Comment by janisozaur** [comment]
It appears SDL is not recognizing the subsys being used, it's none of the available values:

```
			// success
	const char *subsystem = "an unknown system!";
	switch(wmInfo.subsystem) {
		case SDL_SYSWM_UNKNOWN:   break;
		case SDL_SYSWM_WINDOWS:   subsystem = "Microsoft Windows(TM)";  break;
		case SDL_SYSWM_X11:       subsystem = "X Window System";        break;
	#if SDL_VERSION_ATLEAST(2, 0, 3)
		case SDL_SYSWM_WINRT:     subsystem = "WinRT";                  break;
	#endif
		case SDL_SYSWM_DIRECTFB:  subsystem = "DirectFB";               break;
		case SDL_SYSWM_COCOA:     subsystem = "Apple OS X";             break;
		case SDL_SYSWM_UIKIT:     subsystem = "UIKit";                  break;
	#if SDL_VERSION_ATLEAST(2, 0, 2)
		case SDL_SYSWM_WAYLAND:   subsystem = "Wayland";                break;
		case SDL_SYSWM_MIR:       subsystem = "Mir";                    break;
	#endif
	#if SDL_VERSION_ATLEAST(2, 0, 4)
		case SDL_SYSWM_ANDROID:   subsystem = "Android";                break;
	#endif
	}
	log_warning("subsystem %s, %d", subsystem, wmInfo.subsystem);
```

`subsystem an unknown system!, 493`

**Comment by janisozaur** [comment]
Verifying further with winspy++ utility (still via wine), it appears that:
* `windows_get_window_handle` returns `0x100b400`
* winspy++ reports `0x000100B4`

This seems consistent across couple of runs, so a workaround could be implemented.

**Comment by janisozaur** [comment]
There's likely still a bug in here, just got a window where I couldn't trigger save file dialog.
HWND values:
* SDL: `0x301c000`
* after twisting: `0x10300c0
* winspy: `0x000301C0`

**Comment by janisozaur** [comment]
what's worrying is that it looks like nibbles are out of order instead of just bytes.

**Comment by janisozaur** [comment]
Some testing values:
sdl -> winspy, all hex
a012600 -> 000A0126
b016c00 -> 000B016C
c011e00 -> 000C011E
d017600 -> 000D0176
e017000 -> 000E0170
f012600 -> 000F0126
10016c00 -> 0010016C
19012600 -> 01190126
1a016200 -> 011A0162

later on I noticed wine reports the same in of stubs, it looks like so, for the last entry:
`fixme:win:RegisterTouchWindow (0x11a0162 00000003): stub`

It gets weird in last cases from the list, where does the additional `1` come from?

So this happens on linux, how about mingw binaries on windows?

**Comment by vzybilly** [comment]
I get the feeling a pointer is off by one... but looking at the lists, I see byte[ABCD] -> byte[DABC]. But the unknown 01 in the last two make me think that it's doing something like pointer -> (pointer - 1[byte]).

What do y'all think? is there a way we could print out the pointers and see? I don't know C or C++ so I'm not much help here (Assembly and Scala programmer here...)

**Comment by janisozaur** [comment]
Yes, after getting some sleep and looking at it agaian, there's probabaly jest an off by one error. This could perhaps be affecting whole structure, as the subsys is wrong as well with an unknown value. I can't look at it right now, maybe later today.
