### ISSUE TITLE
Scenario completion status broken

### ISSUE THREAD

**Issue by Phyxion** [OpenRCT2/OpenRCT2#1487]
I finished "Prehistoric - After the Asteroid" and got the notification to enter the name because I won with 144k. However, this scenario doesn't show up as completed in the Scenario selector as completed (unlike the very first scenario).

**Comment by Phyxion** [comment]
I tried this again and I think I know what happened, the Prehistoric - After the Asteroid doesn't show as completed but the "Six Flags Magic Mountain" map does.

![untitled](https://cloud.githubusercontent.com/assets/7643972/8393508/b917361a-1d12-11e5-9342-fff527cfaf95.png)

**Comment by Phyxion** [comment]
Any update on this?

**Comment by duncanspumpkin** [comment]
I can't personally reproduce this so its hard to work out whats wrong.

**Comment by Phyxion** [comment]
Would a save game help?

**Comment by duncanspumpkin** [comment]
if it reliably reproduces the bug then yeah that will be very helpful.

**Comment by Phyxion** [comment]
This is my profile with this bug. You can open "Crater CarnageR2" and wait for a few seconds before the park is completed.
[Download](https://www.dropbox.com/s/ywr1azjulc5g3ij/OpenRCT2.zip?dl=0).

**Comment by Phyxion** [comment]
Did the profile and save help? I just tried the latest dev build and it still has this problem.

**Comment by IntelOrca** [comment]
I keep checking the source code for winning and I can't see why it sometimes does not work.

**Comment by Phyxion** [comment]
I have it all the time with the above profile and save, it never works and I've stopped playing because of it :(

**Comment by IntelOrca** [comment]
I'll investigate this.

**Comment by IntelOrca** [comment]
@Phyxion Thank you for the saved game. I think I have found out what the problem is and fixed it. Scenarios that were started in OpenRCT2 were not having their scenario file names attached to the saved games. Your current saved games won't work but any games you save from a newly loaded scenario should now work.
