### ISSUE TITLE
[New Save Format] Cannot edit signs and banners in MP if the server is headless.

### ISSUE THREAD

**Issue by tymondouglas** [OpenRCT2/OpenRCT2#14874]
**OS:** Windows 10
**Version:** 0.3.3 New Save Format Round 2
**Commit/Build:** 4f52231

Cannot edit banners and signs in multiplayer if the server is headless.

- [ ] Reproducible in RCT2 (vanilla)?
- [X] Specific to multiplayer?

**Steps to reproduce:**
1. Start Multiplayer Server as headless.
2. Join your own server
3. Place a Banner/Sign
4. Try to edit it

**Screenshots / Video:**
https://www.youtube.com/watch?v=ng21kOKbD-k

**Server Console Logs**:

- Try to set no entry
ERROR[D:\a\OpenRCT2\OpenRCT2\src\openrct2\actions\BannerSetStyleAction.cpp:52 (BannerSetStyleAction::Query)]: Invalid banner index: index = 13
- Try to edit text
WARNING[D:\a\OpenRCT2\OpenRCT2\src\openrct2\actions\BannerSetNameAction.cpp:50 (BannerSetNameAction::Query)]: Invalid banner id, banner id = 13

**Comment by ZehMatt** [comment]
I can not reproduce this issue so its probably fixed, if the issue persists please let us know.
