### ISSUE TITLE
[.park format] Junior/Water Coaster on-ride photo section incorrect drawing on ground

### ISSUE THREAD

**Issue by SpartanFrederic104** [OpenRCT2/OpenRCT2#14891]
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** 1901dc6 on refs/pull/10664/merge

Building a junior/classic mini/water coaster with an on-ride photo section that is directly on ground level causes the track piece to not be drawn correctly. The base and roots of the camera and smiley face posts are partly hidden by the ground.

**Steps to reproduce:**
1. Build any junior/classic mini/water coaster with an on-ride photo section (e.g. [Junior 6 excitement.td6](https://drive.google.com/file/d/1qOhgU1fip-xz4TbgaHV6zGNFGSNkBnrP/view?usp=sharing))
2. Have the on-ride photo section be directly on ground level
3. You can see that it does not render/draw correctly

**Screenshots:**
![Fred's Workbench 2021 2021-06-12 12-57-54](https://user-images.githubusercontent.com/61885939/121788024-ccf72980-cb7e-11eb-8edb-ef9aaf459147.png)
![Test Park 2021-06-12 13-03-00](https://user-images.githubusercontent.com/61885939/121788026-ce285680-cb7e-11eb-9794-36e76ff9ff9a.png)
Top screenshot is a modified Chocolate Log with an on-ride photo section on the .park format build, bottom screenshot is the same design on the current develop and release builds.

**Comment by Gymnasiast** [comment]
This bug appears to be fixed as of current `develop`, could you check?
