### ISSUE TITLE
Refactor use of overflow in Ride.cpp

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#14918]
This code relies on an overflow:
https://github.com/OpenRCT2/OpenRCT2/blob/9383fcef410aa6a94e3ad07a8da4a2eba41fbdb8/src/openrct2-ui/windows/Ride.cpp#L1603-L1612

There are multiple occurrences like this, all of them should be changed.

This is prone to errors when things like either type or max value change.

**Comment by SaadRehmanCS** [comment]
Is this issue being worked on? I would like to try it.

**Comment by duncanspumpkin** [comment]
I'm reopening this as I'm confident that there are more instances of incrementing/decrementing to null in the codebase. Perhaps there isn't and this issue can be closed again after confirming.
