### ISSUE TITLE
Clearance of the Cash Machine is too low

### ISSUE THREAD

**Issue by Krutonium** [OpenRCT2/OpenRCT2#1491]
![leafier lake - github](https://cloud.githubusercontent.com/assets/3945538/8381348/25a358f6-1bf9-11e5-9666-37020804c668.png)
![scr20](https://cloud.githubusercontent.com/assets/3945538/8381357/33ab7776-1bf9-11e5-832a-e2d01cffe3cd.png)

First "Image" is SV6

No clearance cheats were used, only speed hacks for the coasters.

**Comment by duncanspumpkin** [comment]
No clearance cheats break the drawing. This is a known bug and will be fixed when the ride construction window is finished.

**Comment by Gymnasiast** [comment]
He explicitly said that he didn't use them.

**Comment by duncanspumpkin** [comment]
Hmm I thought he said "No clearance cheat" used. But I guess that could also mean no "clearance cheat" used.

**Comment by IntelOrca** [comment]
Is it really possible to build the coaster track that close to the cash machine?

**Comment by duncanspumpkin** [comment]
I actually just checked this is an original bug. It shouldn't let you build that close.

**Comment by RollingStar** [comment]
How should this be fixed? If that red coaster in the screenshot can't be built through the Cash Machine, the coaster layout would have to change. Changing this behavior could break compatibility with existing layouts.

**Comment by duncanspumpkin** [comment]
We can just change the clearances for the red coaster track part. Its possible the clearances for the cash machine is broken but I think thats unlikely.

**Comment by duncanspumpkin** [comment]
![cashmachine](https://cloud.githubusercontent.com/assets/1277401/8390961/aebd7df4-1ca5-11e5-833d-5e3e93c7cb4f.PNG)

**Comment by Gymnasiast** [comment]
I have the impression shop heights are hardcoded in RCT2. It seems like all food and drinks stalls are 6 metres high, even those that visibly take less space - the burger bar for example, which should clearly take 3 metres.

**Comment by IntelOrca** [comment]
Maybe that is the problem... the cash machine art is too high compared with any other shop.

**Comment by Patrik356b** [comment]
Not only the cash machine, there are a few others that do this in vanilla/gog rct2 i recall.

**Comment by Gymnasiast** [comment]
Apart from custom stalls that go massively outside the regular bounds, I don’t think so. The Cash Machine just has its height set too low, but its bounding box seems to be correct. It would be easy to fix.
