### ISSUE TITLE
Attempting to build rides or stalls in obstructed areas shows no auto-elevate behavior

### ISSUE THREAD

**Issue by SpartanFrederic104** [OpenRCT2/OpenRCT2#14920]
**OS:** Windows 10
**Version:** 0.3.3
**Commit/Build:** 9383fce

Placing down any flat/custom-built track rides or stalls in obstructed areas (i.e. occupied by other rides, footpath, construction rights, or large scenery) will prevent the ride's ghost from appearing and show a cost of $0. Additionally, the behavior that automatically elevates the ride when attempting to build it on obstructed land sometimes no longer works, forcing the player to manually elevate the ride with the Shift key.

**Steps to reproduce:**
1. Select any flat ride or stall
2. As soon as you place it down anywhere where an obstruction will force it to be built higher or even prevent it from being built due to being too high for supports (i.e. attempting to build a Merry-Go-Round on a footpath), it will no longer show a ghost of the ride being constructed and now shows a cost of $0
3. The ghost will only show up if you use the Shift or Ctrl keys to manually elevate the ride

**Screenshots:**
![Corkscrew Follies 2021-06-18 10-28-56](https://user-images.githubusercontent.com/61885939/122597471-4203ac80-d020-11eb-97bd-1b7ecd63f77f.png)

**Comment by Fred-1044276** [comment]
Almost a month in and still no fix to the issue as of 517935e.

**Comment by Broxzier** [comment]
@Fred-1044276 That's the beauty of open-source software; you can create the fix yourself and we'll gladly add it to the main project!

**Comment by Broxzier** [comment]
Using git bisect I found that 474e00d48b779b10f4c88e1337a22b4c061340da is the first bad commit. https://github.com/OpenRCT2/OpenRCT2/pull/14889

**Comment by Broxzier** [comment]
Looks like this has already been fixed on develop. The problem was that the result of `MapCanConstructWithClearAt` was returned from `TrackPlaceAction` instead of a `TrackPlaceActionResult`, which the ghost placement code then expected.

e06f9c3ee70f492b7403d31a5038e34934bc8ffd seemed to have fixed this.
