### ISSUE TITLE
Ride design selection window freezes when game is paused.

### ISSUE THREAD

**Issue by Phasedetect** [OpenRCT2/OpenRCT2#1493]
The highlighted mouseover of the name of the track design does not change when the game is paused.

**Comment by MaikelS11** [comment]
This is a bug that also occurs in the original RCT. 
Solution for the highlight problem is not to difficult (remove an if statement) but will cause an other problem (no preview image)

**Comment by Phasedetect** [comment]
Was this already a documented issue?

**Comment by Gymnasiast** [comment]
No, although that isn't really strange, since in vanilla RCT2, almost all of the GUI stops in pause mode as well. So it isn't really a bug, more a design decision. But in OpenRCT2, the GUI does keep responding in pause mode, so changing this would be in line with that as well.
