### ISSUE TITLE
Screen moving when i move my cursor to the edge of the screen

### ISSUE THREAD

**Issue by Gucci13111** [OpenRCT2/OpenRCT2#14941]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.3.3]
**Commit/Build:** [e.g. 426e106]

In regular open RCT 2, i do not like the fact that my screen moves when i point my mouse to the screen edge, is there an option to remove it or what?

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by duncanspumpkin** [comment]
Yes there is. Please look at the options
