### ISSUE TITLE
Drop height stat requirement for the log flume is wrong

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#14945]
In OpenRCT2 the log flume needs a drop of at least 1 meter (1 unit) to prevent its stats from being cut in half, but in RCT2 vanilla and RCT classic this is 4 meters (3 units).

This line https://github.com/OpenRCT2/OpenRCT2/blob/35ba7346694f41b4e0c8d84129a4d2bf80a5ae11/src/openrct2/ride/RideRatings.cpp#L2628
Needs to be "ride_ratings_apply_highest_drop_height_penalty(&ratings, ride, 6, 2, 2, 2);"
instead of "ride_ratings_apply_highest_drop_height_penalty(&ratings, ride, 2, 2, 2, 2);"

I don't know for how long this has been in the game, but at least since 0.1.0.

**Comment by Broxzier** [comment]
@duncanspumpkin is this easy to verify in the original executable?

**Comment by duncanspumpkin** [comment]
![image](https://user-images.githubusercontent.com/1277401/123536317-80d0eb00-d721-11eb-8972-e813c998c767.png)
Yes looks like that should be a 6 and not a 2. 
Offset 0x117 is the highest drop height. `jae` means jump if greater or equal to. i.e in this case jump over applying the penalty (SHR divide by 2) if the highest drop height is >= 6.
https://github.com/OpenRCT2/OpenRCT2/blob/35ba7346694f41b4e0c8d84129a4d2bf80a5ae11/src/openrct2/rct2/RCT2.h#L200
