### ISSUE TITLE
Rowing boats not returning to station

### ISSUE THREAD

**Issue by jamtraks** [OpenRCT2/OpenRCT2#14940]
**Windows 10 64-bit** [e.g. Windows 10]
**Version:** 0.3.3
**Commit/Build:**35ba734

Not that it's all that big of a deal for me as i barely play openrct2 any more, but i figured i would mention a particular issue in a park of mine. I have a rowing boats ride in this park, and the boats will not return to the station. I am pretty sure they did return to the station about 1 or 2 years ago, before a particular update of which i am not sure of, but ever since a particular update it seems that the boats have stopped returning to the station, and the riders are thinking "i want to get off of rowing boats". I am not sure if there is something i could do to fix the issue in-game, or if there is a glitch in the game code, but i have tried opening and closing the ride and i have tried a few other things, and this  did not fix the issue.
I do have six boats for the ride and only 5 docking spaces, but even when i reduce the boats to 5 or add one docking space i still have the issue.
**Steps to reproduce:**
1. Open park and observe rowing boats ride behavior
2. 
Screenshot:
![Crazy Castle By JoshMarsilio 2021-06-22 18-07-11](https://user-images.githubusercontent.com/17103908/123005865-cdfd3780-d384-11eb-8cf1-cc85908fdd15.png)

Save File:
[Crazy Castle By Josh Marsilio 4.17.txt.zip](https://github.com/OpenRCT2/OpenRCT2/files/6697630/Crazy.Castle.By.Josh.Marsilio.4.17.txt.zip)

**Comment by Gymnasiast** [comment]
This is just bad pathfinding. The issue is also in vanilla RCT2.
It has been reported here: https://github.com/OpenRCT2/OpenRCT2/issues/866
