### ISSUE TITLE
[new-save-format] Footpath placement error

### ISSUE THREAD

**Issue by namitgpta** [OpenRCT2/OpenRCT2#14950]
**OS:** [Windows 10 Pro]
**Version:** [0.3.3 999daa9]
**Commit/Build:** [I don't know may be 999daa9]

I was playing some scenario in new-save-format OpenRCT2. Initially all was good, footpaths were placed correctly. But after some time, when placing footpaths, their placement is now very weird. 2 consecutive paths are joined together but we can't make a long line of footpaths. Its a very severe error. This error occurs only when you place footpaths on (along) the edges of the map.

- [This error is only specific to new-save-format build] Reproducible in RCT2 (vanilla)?
- [No] Specific to multiplayer?

**Steps to reproduce:**
1. Play any scenario for some time.
2. Then after some time like 1-2 hrs, try to place footpaths on the edges of the map, their placement will not be correct, we cannot form a straight line of footpaths, they are grouped in pairs. See the screenshot attached.

**Dump file**

**Screenshots / Video:**

https://youtu.be/gLSDs4Qx9rA

**Save game:**

[AntParktica.zip](https://github.com/OpenRCT2/OpenRCT2/files/6716544/AntParktica.zip)

**Comment by duncanspumpkin** [comment]
Are you sure this is related to the new save format. When you are at the map edge it defaults to connecting out to the void as its only meant to be used for peep spawns.

**Comment by namitgpta** [comment]
You can see in the Youtube video, that earlier (some 1-2 hours back) I was able to place footpaths along the edge of the map without any problem, but after that now when I try to place footpaths even on those positions where they were earlier placed correctly, they are now placed incorrectly.
So I dont think it defaults to connecting for peep spawns because earlier some time that was not the case.

**Comment by Gymnasiast** [comment]
It seems that there are two things at play:
1. You’re placing queues, not regular footpaths.
2. You (most likely) have sandbox mode on, which tries to connect paths to the edge.

As such, it seems to me it is working as intended.
