### ISSUE TITLE
How and where can i see the raw main code for this game? 

### ISSUE THREAD

**Issue by jamtraks** [OpenRCT2/OpenRCT2#14979]
how and where do i view the main code for openrct2?
-->windows 10 64-bit
N/A
Assuming i might want to edit code for openrct, where do i start, and what do i view to see the raw and major code for the game? Do i need a special software to view and edit the code? I would like to at least, be able to view the code and maybe learn how the code influences the game, and how it makes the game work.
N/A
So far i have had zero experience in coding except for making some music and art on my computer, which wasn't exactly coding, but, well it was kind of.

**Comment by harrysbird** [comment]
You will need Git for desktop, Visual studio. And Openrct2 is programmed in C++

**Comment by jamtraks** [comment]
Okay i installed git desktop, and visual studio. Is there a simple explanation now, of how i view the game code? I see many options now can you explain...?

**Comment by ocalhoun6** [comment]
If you've never done any coding before, you'll probably want to start learning with smaller, simpler projects before trying to tackle something as big and complicated as OpenRCT2.

Search for "C++ tutorials" online. That'll be a good start to learn the basics.

**Comment by jamtraks** [comment]
Okay thankyou, though i would like to just look at the code and how it looks. I feel if i could look through what the code looks like i might learn a lot that way. So, how do i load the code lines from openrct into the git desktop or into the visual studio desktop? Could you give me a simple step by step explanation? I just want to look at them.

**Comment by YJSoft** [comment]
If you just want to ask questions, you can ask at [official discord server](https://discord.gg/ZXZd8D8)(linked at main page) since issues are really not for general questions.

**Comment by tupaschoal** [comment]
You don't need to set-up GitHub Desktop to do it, you can browse directly on the website: https://github.com/OpenRCT2/OpenRCT2/find/develop

If you still want to do it, this is how you [clone using github desktop](https://www.makeuseof.com/tag/clone-repository-using-github-desktop/#:~:text=From%20the%20front%20page%20of,like%20to%20clone%20it%20to.). Other than that, please use the channels on discord like @YJSoft suggested

**Comment by Broxzier** [comment]
If you plan to just look at the code, you can browse it here online, or download this project as a ZIP from the [main page](https://github.com/OpenRCT2/OpenRCT2):
![image](https://user-images.githubusercontent.com/9705046/124272395-f16f7180-db3e-11eb-9469-87142d771bb3.png)

The source files are located in the [src folder](https://github.com/OpenRCT2/OpenRCT2/tree/develop/src).

**Comment by jamtraks** [comment]
... is there a software that will allow me to view the .dat files directly from my: infogrames interactive/rct2/data folder that is on my computer?
When i try to open them with the visual studio desktop i get the message: "this code is written in binary, would you like to view it anyway?" and then the code lines are indecipherable.

**Comment by YJSoft** [comment]
Please ask questions at discord channel. Github issues are **NOT** for general questions.
