### ISSUE TITLE
Allow the camera to be rotate anti-clockwise and clockwise 

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#1498]
![roation](https://cloud.githubusercontent.com/assets/1381723/8391754/7d312b94-1cc5-11e5-8550-fcb62b5a671d.png)

**Comment by Phasedetect** [comment]
Pretty sure the world would be thrown out of balance if this one were to happen.

**Comment by duncanspumpkin** [comment]
Its been brought up a few times before but I couldn't find an issue about it. This wouldn't take much effort to create all that is required is making a new icon for the anti-clockwise rotation and putting in a minimal amount of code into top_toolbar.

**Comment by RollingStar** [comment]
I'm against this. It would clutter up the UI. See for example the iOS photo cropping / rotate tool; it only goes in one direction. It simplifies the UI and thus the user experience is better.

**Comment by rd3k** [comment]
Does having both a zoom in and a zoom out button clutters the UI?

**Comment by vzybilly** [comment]
Zoom is different than rotation, just one direction of rotation would be simpler for the UI but... we could probably unstack all the buttons on the toolbars and still have room.

I would say to add the option to add the button.

**Comment by Gymnasiast** [comment]
Changing it into a dropdown that automatically takes the first option when the user clicks it without dragging won't clutter up the UI. If it is implemented this way, nobody has to change his/her workflow if they like the old behaviour: just click it to rotate clockwise, as it always did. We did the same with the Map button in OpenRCT2, by the way: it can also open the Map generator if you click and drag.

**Comment by Gymnasiast** [comment]
Implemented by #1579, can be closed.
