### ISSUE TITLE
Port to UWP/APPX for Xbox One/Series Consoles Dev Mode

### ISSUE THREAD

**Issue by danprice142** [OpenRCT2/OpenRCT2#14988]
Would be great to see this happen, now that a lot of xbox users are using Dev Mode RetroArch for classic games it makes sense for a port, could bring in many new users.

**Comment by danprice142** [comment]
OpenGL version to high for xbox

**Comment by duncanspumpkin** [comment]
Just because the OpenGL version is too high doesn't mean you couldn't just use the software renderer. But eitherway the general idea with ports is for the community to make them and submit the patches to upstream not the other way round.
