### ISSUE TITLE
Feature Request: Get Ride Stats Before Completing the Ride

### ISSUE THREAD

**Issue by Thamesx2** [OpenRCT2/OpenRCT2#14989]
As a player I want to know the stats of the ride I am currently in the process of building so that I can make adjustments as I go and not spend time completing something that is too high/low for a specific metric.

Example use case: I am building a coaster and spend a good hour or so on something I think is awesome, only to find out after I complete and test it that it is too extreme and I need to make some changes. The thing is I don’t know which area of the track I need to change and I spent considerable time editing terrain to complete the ride that may have been for naught. If I could run the blue flag and see how my train goes through the coaster it would be really good to see how fast and how many Gs it encountered up to that point.

An alternative, which seems a tad more complex, would be able to select an area of the track and see the stats for that sections. The user could select the start and endpoint and get the metrics back. This will allow you, for example, to not have to guess when trying to lessen some areas with extreme Gs and fix the ones you know causes the problem.

**Comment by duncanspumpkin** [comment]
This would destroy the challenge and balance of the game.
