### ISSUE TITLE
Game crash scrolling through Misc scenery

### ISSUE THREAD

**Issue by rctcool0** [OpenRCT2/OpenRCT2#15006]
**OS:** Windows 10 (x86-64)
**Version:** V0.3.3
**Commit/Build:** 999daa9 on new-save-format

A crash occurs when scrolling through a long list of scenery. Specifically, it looks like the maximum image limit in Image.cpp does not match the new limits on the new save file format:
"ERROR[D:\a\OpenRCT2\OpenRCT2\src\openrct2\drawing\Image.cpp:200 (gfx_object_allocate_images)]: Reached maximum image limit."
[log.txt](https://github.com/OpenRCT2/OpenRCT2/files/6812496/log.txt)

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open the Gigabench.park file.
2. Open Scenery tab, click on the "?", and scroll down until the game crashes.

**Screenshots / Video:**
N/A, nothing abnormal visually.

**Save game:**
https://1drv.ms/u/s!AiQ_uynOpJhHhu4LauA1guhy1RlAMw?e=2vnAeD
Fair warning, park is 100mb and includes a MASSIVE amount of scenery.

**Comment by Gymnasiast** [comment]
The error happens in this line in TextureCache.cpp:
```C++
    return _atlases.back().Allocate(imageWidth, imageHeight);
```
It calls Allocate, but there are no free slots available.
