### ISSUE TITLE
Game won't finish on Ghost Town scenario, despite meeting the victory conditions

### ISSUE THREAD

**Issue by chardy888** [OpenRCT2/OpenRCT2#15012]
**OS:** Windows 10
**Version:** 0.3.3

In this save in Ghost Town, I have 10 coasters of different types with sufficient length and excitement to meet the scenario win condition. However, the game will not let me win.

The issues appears to be that it is not counting the Corkscrew Coaster since deleting it and building another type results in victory.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Load the Save, and note that it meets the condition to win the scenario.
2. Delete the Corkscrew Coaster and build another coaster that meets the criteria for victory and you will win. (I built another lunar launcher and changed the cars so it counted as another coaster type)

**Screenshots / Video:**

https://i.redd.it/g5jsnlyqs4b71.jpg
Note: This screenshot was taken in an earlier version, but I updated it after taking the screenshot and the issue persisted.

**Save game:**
[Ghost Town.txt](https://github.com/OpenRCT2/OpenRCT2/files/6826137/Ghost.Town.txt)

**Comment by QuantumKittens** [comment]
For me it works with your savegame and I win as soon as I open the corkscrew coaster instead of having it in test mode (which does not count).

**Comment by chardy888** [comment]
Oh, that's my bad then. Updating the game must have fixed it (since the issue was overlapping coaster types) but I totally missed that the coaster was in test mode. Sorry about that!
