### ISSUE TITLE
Moving large scenery items through other scenery while having zero clearance and ctrl on crashes the game.

### ISSUE THREAD

**Issue by RandomEngineDesigner** [OpenRCT2/OpenRCT2#15028]
**OS:** [Windows 10]
**Version:** [0.3.4]
**Commit/Build:** [e0daac9]

If you move a large scenery object with zero clearance through a different object while holding ctrl it crashes the game. This doesn't happen always but it happens relatively often (had it happen 5 times within 10 minutes). It mostly happened when I also had ctrl on to keep the object on a certain height but it may have also happened without having ctrl on.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Take any large scenery object (For me it always happened with 2x2 objects but not sure if the size is relevant.
2. Click control
3. Drag it around for a bit through other scenery items, sometimes you may have to switch objects a couple of times. It may take up to 5 minutes for something to happen.
4. Sometimes the game will just randomly crash.

**Save game:**
I do not have a particular save file where this happened, but I was able to reproduce this bug in multiple different save files. Also different save files which were from different parks.

Hope this is enough information for you guys to fix this issue. Thanks in advance.

**Comment by duncanspumpkin** [comment]
i'm unable to reproduce this from a 10minutes of trying a few different saves. Could you provide a save also is this on a map which is near the max tile limit or anything like that?

**Comment by RandomEngineDesigner** [comment]
Here is a video demonstrating the effect:
https://www.youtube.com/watch?v=FBC-0Tkxu6k the crash happens at the 1:46 mark.

A bit of extra information:
- I was playing in windowed mode.
- I am not sure if the disable weather effects had anything to do with it, but I had it on for good measure.
- I have been able to reproduce it on any map. I was for example able to reproduce it on both the maps that can be downloaded here: https://www.nedesigns.com/topic/39556/h2h9-round-robin-r5m3-tile-inspectors-vs-cereal-killers/

**Comment by duncanspumpkin** [comment]
That video gives me the impression it's hitting the fragmented tile element limit.

**Comment by RandomEngineDesigner** [comment]
I am not 100% sure what that is, but just wanted to note:
- This also happens even when not moving around erratically.
- It also happens on parks/tiles where there isn't a lot of content. It is not necessarily on parks that are filled with objects where this happens.

**Comment by James103** [comment]
> * It also happens on parks/tiles where there isn't a lot of content. It is not necessarily on parks that are filled with objects where this happens.

Do you have an example of such a park? If so, can you please post a save of that park here?

**Comment by RandomEngineDesigner** [comment]
I don't have a program to create a zip file. But see this video:
https://www.youtube.com/watch?v=Y2l13hioM90

This park literally has almost nothing going on. And for me it happens on literally any park, regardless of the amount of content. I do realise I am again moving erratically, but even when just building normally and slowly this happens quite often. The only reason I was moving eratically now was to speed it up a bit, although I have also had it happen after literally the first time I try to place an object, it seems to be completely random and it only happens with large scenery objects.
