### ISSUE TITLE
Desynced clients can erroneously close rides

### ISSUE THREAD

**Issue by Margen67** [OpenRCT2/OpenRCT2#15025]
**OS:** Windows 11
**Version:** 0.3.4
**Commit/Build:** a39ee0c

When a client is desynced in such a way that the ride can't be opened (eg incomplete circuit) the desynced client will close the ride.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**
1. Increase the map size (as the server host)
2. Build the coaster outside of the original map edge (again, as server host)
3. Try to open the rollercoaster

**Dump file**

**Screenshots / Video:**
Desynced via map size (desynced client is in the background):
https://user-images.githubusercontent.com/3462541/126165456-ceec7de6-3283-4bb8-ac9f-7fd2507d305e.mp4
The desynced client can't do anything without permissions:
https://user-images.githubusercontent.com/3462541/126166490-be319a95-04e5-40f1-9cb2-ec57ee83de3c.mp4

**Save game:**

**Comment by duncanspumpkin** [comment]
As soon as you desync commands will be undeterministic this is expected behaviour. The solution is to prevent desyncs
