### ISSUE TITLE
Launched Lift Hill crash

### ISSUE THREAD

**Issue by Phanthalassa** [OpenRCT2/OpenRCT2#1504]
![image](https://cloud.githubusercontent.com/assets/4860519/8395462/d511e2a2-1d3f-11e5-8901-e9623fd01e85.png)
That particular launched lift hill (pointed by a cursor) will crash the game once I right click on it or move to it through construction. I can still remove it by rapidly demolishing tracks around it, but thought you guys would want to take a look at it. 

Link to Save: https://www.dropbox.com/s/nvcgez9nvyl6mo8/Helcaraxe%20World%2035.sv6?dl=0

**Comment by duncanspumpkin** [comment]
Possibly an original bug. Can someone with the original cd installation test this file. We can fix it for openRCT2 but I'm wondering if its only GOG that has this fixed.

**Comment by Gymnasiast** [comment]
I just tested it with the disk version, with WW and TT. It crashes with an Error Trapper.

**Comment by Christipher** [comment]
can you demolish the full ride without a crash?

**Comment by Gymnasiast** [comment]
@Christipher : That's not relevant. It's a bug that always occurs if a piece of launched lift is the first/last piece of track and then right-clicked, and solved in the GOG version but present in the disk version. And something OpenRCT2 will fix (eventually).

**Comment by IntelOrca** [comment]
I can't remember if I fixed this or not...

**Comment by Gymnasiast** [comment]
No, it's still there. I just tested it.

**Comment by IntelOrca** [comment]
OK, it is fixed by copying a certain data array from RCT2 into OpenRCT2, but I forget which one. I think its the one that specifies which default track piece comes before and after another.
