### ISSUE TITLE
The letter L is being replaced by a weird symbol?

### ISSUE THREAD

**Issue by JoshuaCrotts** [OpenRCT2/OpenRCT2#15062]
**OS:** [e.g. Android 11]
**Version:** [e.g. 0.3.4]
**Commit/Build:** [e.g. 935e5b2]

The letter L is being replaced by an odd character that looks like an H with an downward-facing parenthesis over top.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Just open the game and look at any word that has an L in it.

**Screenshots / Video:**
![221614604_604649047578829_4625947182703216890_n](https://user-images.githubusercontent.com/18061804/126728798-0bfd2f0b-bf91-4a09-94ed-503d4fcd310e.png)

**Comment by duncanspumpkin** [comment]
Your g2.dat file is out of date. Did you compile this yourself? You need to update your openrct2 data files.
