### ISSUE TITLE
Special track piece is shown twice

### ISSUE THREAD

**Issue by danidoedel** [OpenRCT2/OpenRCT2#1506]
Compact Inverted Coaster:
![2015-06-28 13_15_46-openrct2](https://cloud.githubusercontent.com/assets/10995998/8396109/2903c210-1d98-11e5-9681-d667dbb743de.png)
I think it should be like this:
![2015-06-28 13_20_50-openrct2](https://cloud.githubusercontent.com/assets/10995998/8396117/8ba9b280-1d98-11e5-935b-8d2230f30b1e.png)

**Comment by IntelOrca** [comment]
Does this happen in the original game?

**Comment by Gymnasiast** [comment]
Tested it. It doesn't.

**Comment by IntelOrca** [comment]
Well currently it represents left helix and right helix... So can a compact coaster have small helixes?

**Comment by danidoedel** [comment]
No, it can't... I just checked the original game.

**Comment by IntelOrca** [comment]
What does the dropdown look like in the original game?

**Comment by danidoedel** [comment]
Like this:
![1](https://cloud.githubusercontent.com/assets/10995998/8396283/07a8001a-1da0-11e5-944b-7348dd069797.png)

**Comment by IntelOrca** [comment]
OK thanks, I will look into it.
