### ISSUE TITLE
Can't place scenery or modify landscape in this park

### ISSUE THREAD

**Issue by RoninMastaFX** [OpenRCT2/OpenRCT2#15074]
**OS:** Gentoo Linux x86_64 (64-bit)
**Version:** 0.3.4 (happens in 0.3.3 as well)
**Commit/Build:** e0daac9

So, this is an old bug that I've had for the past year with this specific scenario...I expect it's likely corruption, but I'll see what y'all say and think before I write it in stone (which would be a shame, lot of hard work put in this one!)

Here's the problem, actually 2 of 'em: First off, I can't place any new scenery anywhere (but I can remove old scenery!), and secondly I can't modify the landscape at all, both of these issues apply inside and outside the park boundaries. I can however still place paths, shops, rides, in fact as you can see I've already started an expansion of the park a bit, but I'm constrained to these two issues. Like I said earlier, I lean highly save game corruption...I need to do some testing with a vanilla RCT2 perhaps and see if I have this issue there as well (for inside the park).

The scenario is fully playable, and I've "blocked off" the new parts of the park to visitors with No Entry signs.

- [ ] Reproducible in RCT2 (vanilla)? Untested
- [ ] Specific to multiplayer? No

**Steps to reproduce:**
1. Load Scenario
2. Try to either: Place any scenery in or outside of the park boundary ***OR*** lower and raise any land

**Screenshots / Video:**
![ModifyingLand](https://user-images.githubusercontent.com/3757396/126837031-6a732f90-6d9b-4ce4-be9c-053735a7e1cb.png)
![PlacingScenery](https://user-images.githubusercontent.com/3757396/126837034-14828ea8-0cbb-4991-bc62-2d3fb643bdeb.png)

**Save game:**
[RMFX Diamond Heights.txt](https://github.com/OpenRCT2/OpenRCT2/files/6871023/RMFX.Diamond.Heights.txt)

**Comment by RoninMastaFX** [comment]
Forgot to mention in the initial post: you'll need a CUSTOM1 file for the music for one of the roller coasters, here's mine (rename the TXT file extension to WAV):
[CUSTOM1.TXT](https://github.com/OpenRCT2/OpenRCT2/files/6871147/CUSTOM1.TXT)

**Comment by duncanspumpkin** [comment]
Your save has indeed been corrupted. The map size is incorrect for some reason it thinks it is 15 tiles wide.

**Comment by duncanspumpkin** [comment]
You can fix it by making the map bigger then smaller and the value will get populated correctly. You will need to enable sandbox mode to be able to do that.

**Comment by RoninMastaFX** [comment]
Thank you so much Duncan, you're awesome! LOL, I'll donate a bit of money (if it's allowed) to this project later on for helping me out! =) I'll close this bug report now.
