### ISSUE TITLE
openrct2-ui\input\ShortcutManager.cpp(112,56): error C2065: 'IPlatformEnvironment': undeclared identifier

### ISSUE THREAD

**Issue by tofuninja** [OpenRCT2/OpenRCT2#15088]
Win 10
commit#c887a049d25747032e8ae06abfe3e05fe1f23e04

Grabbed the latest and tried to build on windows... was easy to fix just add the namespace OpenRCT2:: which makes it really strange that something like this was even an issue... 

Build FAILED.

"C:\Users\snuff\Documents\GitHub\OpenRCT2\openrct2.proj" (build target) (1) ->
"C:\Users\snuff\Documents\GitHub\OpenRCT2\openrct2.sln" (Build target) (2) ->
"C:\Users\snuff\Documents\GitHub\OpenRCT2\src\openrct2-ui\libopenrct2ui.vcxproj" (default target) (4) ->
(ClCompile target) ->
  C:\Users\snuff\Documents\GitHub\OpenRCT2\src\openrct2-ui\input\ShortcutManager.cpp(112,56): error C2065: 'IPlatformEnvironment': undeclared identifier [C:\Users\snuff\Documents\GitHub\OpenRCT2\src\openrct2-ui\libopenrct2ui.vcxproj]
  C:\Users\snuff\Documents\GitHub\OpenRCT2\src\openrct2-ui\input\ShortcutManager.cpp(112,45): error C2923: 'std::shared_ptr': 'IPlatformEnvironment' is not a valid template type argument for parameter '_Ty' [C:\Users\snuff\Documents\GitHub\OpenRCT2\src\openrct2-ui\libopenrct2ui.vcxproj]
  C:\Users\snuff\Documents\GitHub\OpenRCT2\src\openrct2-ui\input\ShortcutManager.cpp(112,82): error C2955: 'std::shared_ptr': use of class template requires template argument list [C:\Users\snuff\Documents\GitHub\OpenRCT2\src\openrct2-ui\libopenrct2ui.vcxproj]
  C:\Users\snuff\Documents\GitHub\OpenRCT2\src\openrct2-ui\input\ShortcutManager.cpp(112,79): error C2955: 'std::shared_ptr': use of class template requires template argument list [C:\Users\snuff\Documents\GitHub\OpenRCT2\src\openrct2-ui\libopenrct2ui.vcxproj]
  C:\Users\snuff\Documents\GitHub\OpenRCT2\src\openrct2-ui\input\ShortcutManager.cpp(113,5): error C2955: 'std::shared_ptr': use of class template requires template argument list [C:\Users\snuff\Documents\GitHub\OpenRCT2\src\openrct2-ui\libopenrct2ui.vcxproj]
  C:\Users\snuff\Documents\GitHub\OpenRCT2\src\openrct2-ui\input\ShortcutManager.cpp(113,5): error C2511: 'OpenRCT2::Ui::ShortcutManager::ShortcutManager(const std::shared_ptr &)': overloaded member function not found in 'OpenRCT2::Ui::ShortcutManager' [C:\Users\snuff\Documents\GitHub\OpenRCT2\src\openrct2-ui\libopenrct2ui.vcxproj]
  C:\Users\snuff\Documents\GitHub\OpenRCT2\src\openrct2-ui\input\ShortcutManager.cpp(114,1): error C2550: 'OpenRCT2::Ui::ShortcutManager::{ctor}': constructor initializer lists are only allowed on constructor definitions [C:\Users\snuff\Documents\GitHub\OpenRCT2\src\openrct2-ui\libopenrct2ui.vcxproj]
  C:\Users\snuff\Documents\GitHub\OpenRCT2\src\openrct2-ui\input\ShortcutManager.cpp(115,5): error C2352: 'OpenRCT2::Ui::ShortcutManager::RegisterDefaultShortcuts': illegal call of non-static member function [C:\Users\snuff\Documents\GitHub\OpenRCT2\src\openrct2-ui\libopenrct2ui.vcxproj]

    0 Warning(s)
    8 Error(s)

**Comment by duncanspumpkin** [comment]
Have you updated to the latest version of VS? The ci is passing fine suggesting a problem on your end

**Comment by Broxzier** [comment]
Just tried to reproduce this with a new system on a checkout of the same commit, and I got no errors. Did you follow the [build instructions](https://github.com/OpenRCT2/OpenRCT2#windows-1) in the read-me?

The exact command that I used from the developer command prompt is `msbuild openrct2.proj /t:build /p:configuration=Debug /p:platform=x64`.

**Comment by duncanspumpkin** [comment]
I think from reading discord it turned out their msvc was out of date.

**Comment by Broxzier** [comment]
Then this can be closed.
