### ISSUE TITLE
Possible to advertise rides in park without actually having any rides.

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#1510]
Make sure you actually have no rides in your park

Select 'vouchers for free rides on a particular ride'

Double click on the '(not selected)' drop down

![screen shot 06-28-15 at 06 46 pm](https://cloud.githubusercontent.com/assets/1381723/8397519/6d2d7340-1dc6-11e5-8faf-859b4c8b9cec.PNG)

Then click start marketing 

![screen shot 06-28-15 at 06 44 pm](https://cloud.githubusercontent.com/assets/1381723/8397518/645f885c-1dc6-11e5-9ada-4a1c0421f3e8.PNG)

**Comment by chrismilne300** [comment]
Just found out you can advertise for free rides in shops, and advertise nothing for free food or drink. 
To do this just double click on the drop down box.
![screen shot 07-08-15 at 05 22 pm 001](https://cloud.githubusercontent.com/assets/1381723/8575926/82235738-2596-11e5-815f-3dfc9d00cee2.PNG)
![screen shot 07-08-15 at 05 22 pm](https://cloud.githubusercontent.com/assets/1381723/8575927/8229d00e-2596-11e5-9231-d67e8d41ac80.PNG)
![screen shot 07-08-15 at 05 23 pm](https://cloud.githubusercontent.com/assets/1381723/8575928/822b7d00-2596-11e5-83c6-410ad91ea0a6.PNG)

**Comment by wolfblake** [comment]
I know there was a pull request to fix this, but this bug is still in the newest build. Can we look into rebasing the pull request and fix this?
