### ISSUE TITLE
An error occured, a image have failed to load

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#15115]
**OS:** Windows 10
**Version:** Beta version (June update)
**Commit/Build:** 

well, i was playing on a map i made, but the custom palette seem to have bugged out, i can't remove it anymore.

- [ ] Reproducible in RCT2 (vanilla)? NO
- [ ] Specific to multiplayer? NO

**Steps to reproduce:**
1. get to the park provided
2. try to change the palette
3. get the error as mentionned

**Comment by TheClaudeQC** [comment]
[https://drive.google.com/file/d/1utmKNPfMDiqAiq_2hj0QuXDgMybb7B_O/view?usp=sharing](url)
[https://drive.google.com/file/d/1kNpehyOLWwGr8BX_pUmWwPtgtI9LEbmM/view?usp=sharing](url)

There is the links that dosen't appear

**Comment by duncanspumpkin** [comment]
Beta version isn't a version number. Is this on the nsf?

**Comment by Gymnasiast** [comment]
We have asked you dozens of times to **fill in the form correctly**, most importantly the build hash, and you **keep** refusing to do so. This is getting incredibly tedious. If you keep refusing to listen, you will be banned.

**Comment by TheClaudeQC** [comment]
> Beta version isn't a version number. Is this on the nsf?

hum, i mean, the devlop build whit the extended limits

**Comment by TheClaudeQC** [comment]
> We have asked you dozens of times to **fill in the form correctly**, most importantly the build hash, and you **keep** refusing to do so. This is getting incredibly tedious. If you keep refusing to listen, you will be banned.

please, i just wanted to show them, but everytime, it feel something not there, i just misunderstand the bug report's elements, like, it's ain't on another web site, that we only to link the "game that happened", the expalination and how? And telling if you did refresh/restart the game if it was random or there everytime and maybe, more games you/someone else experience the same bug.

**Comment by IntelOrca** [comment]
@TheClaudeQC 

All you need to do is write the text that you see in the bottom left corner of the title screen:

![image](https://user-images.githubusercontent.com/1482259/127366669-b7bbf9c3-247f-4e53-847e-94829df08cc4.png)

**Comment by Gymnasiast** [comment]
> > We have asked you dozens of times to **fill in the form correctly**, most importantly the build hash, and you **keep** refusing to do so. This is getting incredibly tedious. If you keep refusing to listen, you will be banned.
> 
> please, i just wanted to show them, but everytime, it feel something not there, i just misunderstand the bug report's elements, like, it's ain't on another web site, that we only to link the "game that happened", the expalination and how? And telling if you did refresh/restart the game if it was random or there everytime and maybe, more games you/someone else experience the same bug.

I have no idea what you’re even trying to say. I don’t expect perfect English, certainly not from a non-native speaker, but you provide almost no information, and what you do say is hard to understand.

If your point is “why do I have to give you this information?”, then the answer is simple: because we **need** it. Otherwise we would not be asking for it. If you want us to fix your issues, you have to make it possible.

**Comment by Gymnasiast** [comment]
I tried loading up your save and changing the palette. Works fine for me on both develop and the new-save-format branch (commit e52668cc2fcbbaf3692bcabf4ca4563703ffc7a7). Since you didn’t provide more information to go on, even after asking you to, that’s all we can do.

**Comment by TheClaudeQC** [comment]
i will try to send a video of it if i can have acces to
