### ISSUE TITLE
Very strange bug

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#1511]
Start a new game in crazy castle.

Just leave the game running for a while (2-5mins) 

The camera will move for no reason and guests will be randomly placed through out the map.

![screen shot 06-28-15 at 07 02 pm](https://cloud.githubusercontent.com/assets/1381723/8397570/6679ef90-1dc8-11e5-9f79-de7d107e73fe.PNG)

Sometimes my game crashes, other times guests can't walk on paths and the guest count doesn’t match the actual amount of guests in the park. Sometimes as well the banner above the entrance will stop moving.

![screen shot 06-28-15 at 06 55 pm](https://cloud.githubusercontent.com/assets/1381723/8397571/71aa8190-1dc8-11e5-89e9-cdb0f20d08bf.PNG)

The edge of the map seems to glitch out too.

![screen shot 06-28-15 at 07 02 pm 001](https://cloud.githubusercontent.com/assets/1381723/8397581/e11b9e56-1dc8-11e5-897d-c942f8029430.PNG)

**Comment by IntelOrca** [comment]
Does this happen after ed41c2b9956e0342a8f9705fe80e0116809ce66d ?

**Comment by chrismilne300** [comment]
Sorry I don't know, I'm using 0.0.3 build 886 if that helps. Also i've tried doing this a number of times and something else has happened.
![screen shot 06-28-15 at 07 14 pm](https://cloud.githubusercontent.com/assets/1381723/8397628/4cea3a38-1dca-11e5-851a-7f34362d688e.PNG)
I've never touched the land just left it running the camera also keeping moving to the bottom left when zoomed in

**Comment by rctdude2** [comment]
@IntelOrca Seems like it works fine after that commit (OpenRCT2.com build 888).

**Comment by duncanspumpkin** [comment]
Yup that will be my map element change messing up. Hopefully fixed in https://github.com/OpenRCT2/OpenRCT2/commit/ed41c2b9956e0342a8f9705fe80e0116809ce66d

**Comment by chrismilne300** [comment]
Just updated to build 888 and it seems a bit better however it seems to be linked with animated scenery  such as the active volcano vent 
![screen shot 06-28-15 at 07 29 pm](https://cloud.githubusercontent.com/assets/1381723/8397691/458d26c2-1dcc-11e5-971d-00394b44ca1a.PNG)
