### ISSUE TITLE
Very strange land issue

### ISSUE THREAD

**Issue by hypocube** [OpenRCT2/OpenRCT2#1512]
I'm playing sherwood forest and suddenly land shot up into the sky into spires of death that made all the rides in its deadly area of effect crash (including the mini golf). 
![landspires](https://cloud.githubusercontent.com/assets/13089397/8397714/5d44e0c0-1d9a-11e5-93f5-0b7b0df40b77.png)

I recently made a square path out of the wooden path (basically a copy of the path around the minigolf) and then started editing it by removing bits. Then the land rose up and tarnished my park rating by killing everyone on the log flume. While I was trying to take a fully zoomed out screenshot, another death spire shot across the map and crashed the game. It looks like the death spires shot up on the new paths I made but they appeared in other places too. 

![landspires](https://cloud.githubusercontent.com/assets/13089397/8397733/eae86258-1d9a-11e5-812a-c7bce5502ea7.png)

**Comment by duncanspumpkin** [comment]
Yup i broke it on the latest patch see #1511
