### ISSUE TITLE
Quarter tile scenery not being removed consistently when building a track or path through it if there are multiple scenery items on the tile.

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#15138]
**OS:** Kubuntu linux 20.04
**Version:** 0.3.4.1
**Commit/Build:** Unknown develop. See #12909 

Lately, I've been seeing that quarter-tile scenery items are sometimes not removed when I build a path or track through them. _Sometimes_ it's removed, but some get missed. It happens pretty consistently (see screenshot below). There doesn't seem to be any pattern to which scenery items get missed.

- [ no ] Reproducible in RCT2 (vanilla)?
- [ no ] Specific to multiplayer?

**Steps to reproduce:**
1. Build quarter-tile scenery, preferably a lot of it -- Edit: there must be at least two scenery items per tile for this to happen.
2. Build a path or ride track through the scenery
3. Some will be removed, but you'll probably see that some of the scenery that should be removed stays where it is.

**Screenshots / Video:**
![Forest Frontiers 2021-07-30 11-27-28](https://user-images.githubusercontent.com/26573303/127696811-58e47933-4097-49aa-8009-1a4a595c7733.png)

**Comment by ocalhoun6** [comment]
Did a little more investigation ... there _are_ patterns emerging. _Most_ of the time, it's removing only 2/4 of the quarter-tile scenery objects on the tile, leaving opposite corners in place ... but not always the same two corners.

![Forest Frontiers 2021-07-31 18-20-06](https://user-images.githubusercontent.com/26573303/127756175-9d974012-8bf6-4949-b4dd-1acd8f6f2646.png)

**Comment by ocalhoun6** [comment]
Some more experiments:

One scenery item per tile:
![Forest Frontiers 2021-07-31 18-29-06](https://user-images.githubusercontent.com/26573303/127756388-e1daccfd-0dff-4655-a136-4a5cf299f3a2.png)

![Forest Frontiers 2021-07-31 18-29-32](https://user-images.githubusercontent.com/26573303/127756393-aff92e3d-8950-4933-a82f-c7e7b4b9fd2b.png)
All scenery items were removed successfully!

Two scenery items per tile:
![Forest Frontiers 2021-07-31 18-30-35](https://user-images.githubusercontent.com/26573303/127756418-98b70e04-11e1-4211-ade6-3066f2f2ab28.png)
![Forest Frontiers 2021-07-31 18-30-54](https://user-images.githubusercontent.com/26573303/127756420-92f0f6e2-1a2a-4d43-b1e9-5e9e3094c9a0.png)
1/2 of the scenery items were removed.

Three scenery items per tile:
![Forest Frontiers 2021-07-31 18-32-39](https://user-images.githubusercontent.com/26573303/127756434-cc63694c-f4e7-4efc-9ace-d4c7d6decfa2.png)
![Forest Frontiers 2021-07-31 18-32-59](https://user-images.githubusercontent.com/26573303/127756438-0cdd96ee-aea1-4789-a5fe-0ce5efbc94e4.png)
2/3 of the scenery items were removed in every case!

Four scenery items per tile:
![Forest Frontiers 2021-07-31 18-34-09](https://user-images.githubusercontent.com/26573303/127756456-069cbc2d-83ba-41cf-aadc-94d6c2122557.png)
![Forest Frontiers 2021-07-31 18-34-15](https://user-images.githubusercontent.com/26573303/127756463-87e3264b-1a00-46ec-8932-cbe3f1b34d34.png)
2/4 -- consistent with previous results.

In light of how it only happens if _multiple_ scenery items are on the tile, I'll change the title of this issue to reflect that.

I seem to remember some PRs lately that were refactoring while loops? It wouldn't happen to be that one of those while loops was in the code that removes scenery items in the way of paths/tracks, would it? This _does_ kind of look like a loop that's supposed to run through 4 iterations but is only running through 2 iterations.

**Comment by ocalhoun6** [comment]
Trying diagonal pairs, since that's what it usually leaves behind:
![Forest Frontiers 2021-07-31 18-49-21](https://user-images.githubusercontent.com/26573303/127756600-78235c90-d547-4346-8a87-2339f213dba4.png)
![Forest Frontiers 2021-07-31 18-49-45](https://user-images.githubusercontent.com/26573303/127756603-75e77964-0195-4dc0-92c2-367a0b293a76.png)
Huh... Same as every other pair of two -- 1/2 removed. I thought I was about to really be onto something with this one ... but no, the results are consistent with all the other tries where there were 2 scenery items per tile.

**Comment by ocalhoun6** [comment]
Looked through the recent PRs, and I suspect this is caused by one of these two: #14889 or #14815 

Or at least, those two seem to touch things that might be causing this. They're both quite a bit too complex for me to make heads or tails of, though. But I suspect a small accident in one of those PRs is what's causing this issue.

**Comment by Broxzier** [comment]
I suspected that this has to do with the order of the elements, and can confirm that that is the case. If multiple objects collide, it removes the first, then skips the next. So if there are 4 elements on the tile that it collides with, it will remove the 1st and 3rd scenery element, leaving two. If you build through it again, it will remove the 1st, leaving one.

I have not yet confirmed this in the code, but I suspect that it's simply a matter of changing the way elements get iterated over in the collision check.
