### ISSUE TITLE
Incorrect plural form for last inspection time

### ISSUE THREAD

**Issue by danidoedel** [OpenRCT2/OpenRCT2#1513]
![2015-06-28 21_13_37-openrct2](https://cloud.githubusercontent.com/assets/10995998/8397877/fe2d7f2a-1dda-11e5-81d6-34d29d4c5c4f.png)
Should be "1 minute"

**Comment by duncanspumpkin** [comment]
Was this in vanilla RCT2?

**Comment by danidoedel** [comment]
Yeah same in the original game

**Comment by duncanspumpkin** [comment]
Okay it can be fixed but it wont be high on the list of things to do.

**Comment by danidoedel** [comment]
Sure, no problem.
