### ISSUE TITLE
Scenery ghost not removed when dragging on Android

### ISSUE THREAD

**Issue by lnoorman** [OpenRCT2/OpenRCT2#15145]
Haven't done this before, please help me out if I'm doing something wrong.

**OS:** [Android]
**Version:** [0.3.4.1]
While placing scenery such as trees, plants, flowers etcetera, you will get a preview of what the scenery will look like. If you drag your finger over the screen, the preview will stay present and will only dissapear when you restart your game (save/load park). If a mouse is used on Android, it will happen when you drag the mouse around.

[ ] Reproducible in RCT2 (vanilla)?
[ ] Specific to multiplayer?

**Steps to reproduce:**
1. open scenery and pick any tree/flower
2. drag your finger over the map while you've chosen any tree/flower
3. bug apears, preview of scenery wont disapear

![Screenshot_20210731-222411_OpenRCT2](https://user-images.githubusercontent.com/88252316/127751861-2e7ec76f-7937-430a-86cd-2adeaec438dc.jpg)

![Screenshot_20210731-222411_OpenRCT2](https://user-images.githubusercontent.com/88252316/127751831-93a5f632-866f-4a12-8a6b-b432b6e44d4f.jpg)

**Comment by Gymnasiast** [comment]
>  Specific to multiplayer? No idea as multiplayer is unavailable in Android.

Since the bug happens in single player, it is _obviously_ not _specific_ to multiplayer.

**Comment by lnoorman** [comment]
> > Specific to multiplayer? No idea as multiplayer is unavailable in Android.
> 
> Since the bug happens in single player, it is _obviously_ not _specific_ to multiplayer.

Thank you for correcting me and adding the labels, I couldn't find that.
