### ISSUE TITLE
Track Designs Manager delete confirmation window doesn't display properly

### ISSUE THREAD

**Issue by seifer7** [OpenRCT2/OpenRCT2#15148]
**OS:** [e.g. Windows 10]
**Version:** 0.3.4.1
**Commit/Build:** 5087e77

The "Delete Confirmation" window in the Track Designs Manager doesn't display properly.
The "Delete Confirmation" window title is the name of the Ride, whereas in the RCT2 the title is "Delete File"
The "Delete Confirmation" window title goes blank if you close the previous window asking if you want to Delete or Rename the ride. In ORCT2 the title stays as "Delete File"

I think the "Delete Confirmation" window title should be "Delete File" (like RCT2,) and when you close the previous window I think the "Delete Confirmation" window should close with it (unlike RCT2.)

- [no] Reproducible in RCT2 (vanilla)?
- [no] Specific to multiplayer?

**Steps to reproduce:**
1. Open Track Designs Manager
2. Select a ride that has pre-made tracks
3. Click the name of a track
4. Click the "Delete" button
5. (Notice the window does not render properly)
6. (Notice the window title is the Ride name, should be "Delete File")
7. Close the previous window that contains the "Rename" and "Delete" buttons
8. (Notice the "Delete Confirmation" window now has no title)

**RCT2 (vanilla) - Window asking to Rename or Delete, and Delete Confirmation window**
![RCT2 (vanilla) - Window asking to Rename or Delete, and Delete Confirmation window](https://user-images.githubusercontent.com/13601073/127762302-f06a1dbf-d345-4977-a4b7-a9459ee37869.png)

**OpenRCT2 - Window asking to Rename or Delete, and Delete Confirmation window**
![Window asking to Rename or Delete, and Delete Confirmation window](https://user-images.githubusercontent.com/13601073/127762230-f45c9d38-87c1-4961-b62b-857ef895e3bd.png)

**OpenRCT2 - Delete Confirmation window after closing previous window (notice title has gone blank)**
![Delete Confirmation window after closing previous window (notice title has gone blank)](https://user-images.githubusercontent.com/13601073/127762265-5140ac62-2145-46d4-b68c-dd882d8379ca.png)

**Comment by seifer7** [comment]
Working on this.

Question, do we want the "Delete Confirmation" (or, more precisely "Delete File") window to close automatically if you close the "Rename / Delete" window?
I think that would be expected behaviour (though, RCT2 vanilla just leaves it open as an orphaned window.)

**Comment by seifer7** [comment]
Just checked and the "Rename" window automatically closes when you close the previous (Rename / Delete choice) window, so I'll make the "Delete Confirmation" window act the same.

**Comment by duncanspumpkin** [comment]
Does anyone actually use the track design manager? It always seemed rubbish.

**Comment by seifer7** [comment]
> Does anyone actually use the track design manager? It always seemed rubbish.

Without using the file system, isn't it the only way to rename and delete track designs?
Nevertheless, I have made a pull request to fix this.
