### ISSUE TITLE
Android language bug

### ISSUE THREAD

**Issue by lnoorman** [OpenRCT2/OpenRCT2#15152]
**OS:** Android
**Version:**  0.3.4.1

When updated  to version 0.3.4.1, the letter 'l' and 'j' are replaced by the letter G. This is shown in the screenshot. 

**Steps to reproduce:**
1. Update to the 0.3.4.1 version.
2. Check options or start a game. Confirmed that it happens with English (UK) and Dutch.

**Screenshots / Video:**
![Screenshot_20210801-112804_OpenRCT2](https://user-images.githubusercontent.com/88252316/127766192-132dbcfc-166d-4c01-a59a-096f8163aff1.jpg)
![Screenshot_20210801-112815_OpenRCT2](https://user-images.githubusercontent.com/88252316/127766199-ed65b97f-fb46-4272-b258-fd5688bbc66a.jpg)

**Comment by Gymnasiast** [comment]
You added the wrong g2.dat. Most likely, you’re using one from v0.3.3 or earlier with OpenRCT2 v0.3.4.

**Comment by lnoorman** [comment]
Thanks for clarifying. Annette can I find the updated g2.dat?

**Comment by duncanspumpkin** [comment]
You need to get it from your installation files for that version.

**Comment by Gymnasiast** [comment]
@duncanspumpkin It works a bit differently on Android.

The best way to get them is to download the portable Windows version counterpart, and extract the files from `data/` to `/sdcard/openrct2`. Before doing so, empty `/sdcard/openrct2` for good measure.

**Comment by lnoorman** [comment]
I found it,  thank you!  Works like a charm
