### ISSUE TITLE
More realistic multi-dimensional coaster

### ISSUE THREAD

**Issue by Phasedetect** [OpenRCT2/OpenRCT2#1517]
Seeing [this](http://www.reddit.com/r/rct/comments/3bfoh1/2_multidimensional_roller_coaster/) made me think that it would be a great addition to ORCT2. The rating of a multi-dimensional coaster could be affected by the pitch of the riders. Really far off in the distance, but now there is a record of it.

**Comment by RollingStar** [comment]
>There aren't 'physics' for it in real life... There's actually a second set of offset rails that move up and down relative to the main rails to move a cam go rotate the seats. So it actually is controlled by the ride design and not physics.

**Comment by mrtnptrs** [comment]
What is the real idea of this enhancement report? @Phasedetect Realistic/actual seat rotation and that it is correctly taken into account regarding the scores of the ride? Maybe explain it a bit more?

**Comment by Gymnasiast** [comment]
As @RollingStar pointed out, X(2) uses a second set of rails, which is represented by the "Seat rotation" control. I would consider that a realistic enough representation.
