### ISSUE TITLE
.Park Format: Installing .park version after installing version 0.3.4.1 causes game assets to be missing, resulting in unplayable scenarios and graphical bugs

### ISSUE THREAD

**Issue by Derpercoaster** [OpenRCT2/OpenRCT2#15179]
OS: Windows 10
Version: .park format
Build: unsure
Issue:
I was using the .park format, and decided to update the game because it said there was an update available. I didn't know it would update over the .park format as I believed that version was separate from the regular versions (it isnt apparently). When I realized this, I redownloaded the .park version and reinstalled it.

After doing this, I loaded the game and was met with a black title screen (aka no assets were loaded other than music). The buttons to select scenarios, load saves, etc. were all present, but loading a scenario just brought up a window saying files were missing. I clicked the button to download them, but after this completed attempting to load same scenario as before just brought up the error yet again (oddly, loading one of my custon scenarios did not have this issue even though vanilla assets were used in making it).

The graphical issues I mentioned in the title are weird to explain. Simply put, if you drag a window around, move the camera view etc., the texture of said window or anything else on screen just "duplicate" in a weird freezeframe fashion (ie dragging the window just duplicates its texture behind it, similar to that bug in older version of windows).

Vanilla issue: No
Multiplayer-Specific: No

To reproduce:
1. Install .park version
2. Update to 0.3.4.1
3. Update back to .park format
4. The bug should occur. Black title screen (apparent lack of textures) with visible buttons. Attempting to load scenario results in error saying files are missing. Downloading the files does nothing.

**Comment by duncanspumpkin** [comment]
You need to keep separate installations for the nsf and regular.

**Comment by IntelOrca** [comment]
When you unpack a portable version of OpenRCT2, make sure you extract it to an empty directory, not over the top of an existing one.
