### ISSUE TITLE
Demolishing a ride keeps construction open

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#15199]
### Operating System

*

### OpenRCT2 build

0.3.4.1

### Describe the issue

The ride construction stays open when a ride is demolished with the ride window.

### Steps to reproduce

1. Place any ride
2. Open the ride window while still in construction.
3. Demolish the ride, the construction stays open but no ride exists anymore.

**Comment by Broxzier** [comment]
Unable to reproduce with the steps provided. Tried with flat rides, tracked rides, with and without entrance/exit built, and in multiplayer from both the server and client side, but the ride construction window always closes properly.

**Comment by ZehMatt** [comment]
I don't know how I got into this state, I was testing out things for #15197 and somehow ended up with an unusable ride construction window. I'm also having trouble reproducing it now.

**Comment by seifer7** [comment]
Confirmed, this bug does occur on latest build.

Steps to reproduce:
1. Place a flat ride
2. Place either: no exit/entrance, or ONE (either entrance or exit)
2. Right-click the placed flat ride
3. Press demolish button
4. Construction window stays open but can't construct anything.

**Comment by Broxzier** [comment]
@seifer7 The bug you describe is https://github.com/OpenRCT2/OpenRCT2/issues/15197. This one is about the _ride window_ staying open, not the _ride construction window_. The ride gets demolished from the ride window, not removed with the bulldozer button from the ride construction window.

**Comment by seifer7** [comment]
I'm not sure exactly what this bug is describing.

Is it unwanted that the Ride window stays open after demolishing the ride? (you can re-place the ride and it will use the existing Ride window, however the Ride Window Viewport doesn't update to the new location.)

Or is it unwanted that the Construction window stays open after demolishing the ride? (again, if the bug on #15197 is fixed you'd be able to re-place the ride so the Construction window is still useful.)

Either way, I can reproduce this bug (Ride Window & Construction Window stays open.)

**Comment by seifer7** [comment]
Steps to reproduce:
1. Place a ride of any type
2. Place either: no exit/entrance, or ONE (either entrance or exit)
3. Right-click the ride
4. Left-click the ride (opens the Ride window)
5. Click the demolish button in the **CONSTRUCTION** window

At this point, the Ride window and Construction window stay open.

**Comment by ZehMatt** [comment]
There is probably a misconception of what a ride is, for lets say the Merry Go Round, the piece you place is technically speaking a track piece and not the "ride". A ride in this game is just a unique identifier that will have track pieces associated, so most things you see are actually track pieces. So without a valid ride the ride construction can not work, demolishing the track piece is something different from demolishing the entire ride.
