### ISSUE TITLE
in-game bug report button

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#15195]
### Describe the feature

To make reporting bugs more accessible to the players and to help them provide the information that we need, we could introduce a way of opening the issue report page easily from within the game. That way they don't have to go looking for how to report bugs, and we're able to automatically fill the OS and build information. This can be done by constructing a URL like this:
[https:\/\/github.com/OpenRCT2/OpenRCT2/issues/new?labels=bug&template=bug_report.yaml&**operating_system=Windows+10+x64**&**openrct2_build=automatically+filled+version+info**](https://github.com/OpenRCT2/OpenRCT2/issues/new?labels=bug&template=bug_report.yaml&operating_system=Windows+10+x64&openrct2_build=automatically+filled+version+info)

The new button could be located in the about window, or as an item in the dropdown menu from the top toolbar.

### Feature type

Quality of life

**Comment by Broxzier** [comment]
Creating a fully-fledged form in-game that supports all the markup and file attachments that you can use here will be way out of scope for this. Players will need a GitHub account to report things already, and if they want to see something fixed they'll probably sign up.

While we don't have any anonymous issue submission system in place, immediately opening the link to a pre-filled form is still better than letting them enter a form in-game that redirects them here when done, only for them to see they need to create an account or log in like some software like GitExtensions do, is a better design choice in my opinion.

**Comment by ocalhoun6** [comment]
> Creating a fully-fledged form in-game that supports all the markup and file attachments that you can use here will be way out of scope for this.

lol, yeah. We don't even have support for the full compliment of keyboard symbols in the in-game fonts, do we? That's part of what's preventing #13471 from being done.
