### ISSUE TITLE
Right-clicking flatride and bulldozing while having hut placement selected causes ride construction window to 'freeze'

### ISSUE THREAD

**Issue by danielmeinert** [OpenRCT2/OpenRCT2#15197]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (5087e77) provided by GitHub

### Describe the issue

After having placed a flatride the cursor automatically switches to the hut placement of the ride. When I now right-click the ride again and delete it (e.g. to relocate it) the cursor is still in the hut placement mode and you cannot place the ride anymore making the ride construction window not working anymore and you have to reload by selecting the flat in the ride selection again.

### Steps to reproduce

1. place flatride
2. right click flatride
3. press demolish button
4. cannot place ride again

### Attachments

![grafik](https://user-images.githubusercontent.com/39702411/128903794-0da899f4-8c01-42c8-adc0-35b88c5c8f76.png)

![grafik](https://user-images.githubusercontent.com/39702411/128903827-6e49587b-8b5a-43c0-9aa4-b3ebbd9c5e53.png)

**Comment by seanmajorpayne** [comment]
Working on this.
