### ISSUE TITLE
"See-through rides" doesn't affect all rides

### ISSUE THREAD

**Issue by ghost** [OpenRCT2/OpenRCT2#1519]
For example, carousels don't have any transparency, which defeats the point of the view option. I am pretty sure that any model (sprite?) that includes guests is not included.

**Comment by duncanspumpkin** [comment]
Can you provide an image of what is wrong. Also I take it this is a OpenRCT2 issue and isn't in vanilla RCT2?

**Comment by Phasedetect** [comment]
This is the ride when it is closed:
![screen shot 2015-06-29 at 10 54 44](https://cloud.githubusercontent.com/assets/7439907/8410680/b46df324-1e4d-11e5-91ce-ee54a547bb98.JPG)
This is the ride when it is testing/open:
![screen shot 2015-06-29 at 10 54 50](https://cloud.githubusercontent.com/assets/7439907/8410687/c2e4467e-1e4d-11e5-9b25-b6be5b5b221a.JPG)

Tested and the behavior is from vanilla. I wouldn't call it a bug per se, I think CS did it intentionally.

**Comment by marijnvdwerf** [comment]
"vehicles" on flat rides are drawn using `VIEWPORT_INTERACTION_ITEM_SPRITE`, whereas the other parts of the ride are drawn as `VIEWPORT_INTERACTION_ITEM_RIDE`. Only the latter type is made invisible

https://github.com/OpenRCT2/OpenRCT2/blob/4be4ed19a30bb110b7cbbf770ae5cbcc5e5d580f/src/paint/paint.c#L926

https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/ride/gentle/merry_go_round.c#L48

**Comment by IntelOrca** [comment]
I believe its because its treated like a vehicle. So presumably we want to make vehicles see-through too when this option is enabled.

**Comment by jensj12** [comment]
I'd say make flat ride vehicles invisible, and leave tracked ride vehicles as-is. I love being able to see a coaster train move with everything else disabled, in fact, I even use it sometimes to see where it's going when there's no other way to see the track.

**Comment by seifer7** [comment]
I'm working on this and #2478 (Enhanced transparency/visibility options)
