### ISSUE TITLE
Demolishing stalls sometimes causes the game to crash

### ISSUE THREAD

**Issue by evynhh** [OpenRCT2/OpenRCT2#15193]
### Operating System

Linux (x86-64)

### OpenRCT2 build

OpenRCT2, v0.3.4.1-141 (3ed2f8e98 on makepkg)

### Describe the issue

Some stalls, when demolished, cause the game to crash, most notably the Drink Stall and Information Kiosk.

### Steps to reproduce

1. Place Drink Stall/Information Kiosk
2. Delete the kiosk
3. Game crashes

### Attachments

https://user-images.githubusercontent.com/46719718/128779462-be933c00-0dea-4340-912c-3b946527c0a0.mp4

**Comment by janisozaur** [comment]
Any chance you can provide stack trace?

**Comment by ZehMatt** [comment]
I'm unable to reproduce the issue, do you have plugins installed by any chance? Also it would help if you can provide the save file if it only affects the specific park.

**Comment by evynhh** [comment]
> Any chance you can provide stack trace?

How would I do that? 

> I'm unable to reproduce the issue, do you have plugins installed by any chance? Also it would help if you can provide the save file if it only affects the specific park.

I don't have any plugins installed (I didn't even know they existed, lol), but [here](https://cdn.discordapp.com/attachments/714259318064545803/875034878788403280/The_Totally_Serious_Park.sv6) is the save file. Information Kiosk 1 is one of the culprits here.

**Comment by ZehMatt** [comment]
It does indeed crash, thanks for the save. The culprit is actually not the kiosk but the peeps

**Comment by evynhh** [comment]
> `coredumpctl list`, find the offending crash, then `coredumpctl info <pid>`

Grabbed the [stack trace](https://pastebin.com/GpaUs5aw)

**Comment by janisozaur** [comment]
```
                #0  0x00007fcb5e86ed22 raise (libc.so.6 + 0x3cd22)
                #1  0x00007fcb5e858862 abort (libc.so.6 + 0x26862)
                #2  0x00005610a895a30f n/a (openrct2 + 0x25830f)
                #3  0x00005610a895a75c n/a (openrct2 + 0x25875c)
                #4  0x00005610a89359b2 n/a (openrct2 + 0x2339b2)
                #5  0x00005610a8936167 n/a (openrct2 + 0x234167)
                #6  0x00005610a89377e4 n/a (openrct2 + 0x2357e4)
                #7  0x00005610a87f572b n/a (openrct2 + 0xf372b)
                #8  0x00005610a89131d8 n/a (openrct2 + 0x2111d8)
                #9  0x00005610a8902609 n/a (openrct2 + 0x200609)
                #10 0x00005610a890873a n/a (openrct2 + 0x20673a)
                #11 0x00005610a8909919 n/a (openrct2 + 0x207919)
                #12 0x00005610a87bc1ce n/a (openrct2 + 0xba1ce)
                #13 0x00007fcb5e859b25 __libc_start_main (libc.so.6 + 0x27b25)
                #14 0x00005610a87e199e n/a (openrct2 + 0xdf99e)
```
Not very useful without the symbols. It could be recompiled again and use symbols from such build, but not necessary as Matt has found the crash already via save.

If you're using https://aur.archlinux.org/packages/openrct2-git/, consider modifying it to append `options=(debug !strip)`. Thanks anyway.
