### ISSUE TITLE
Some text characters replaced with others

### ISSUE THREAD

**Issue by potatoes979** [OpenRCT2/OpenRCT2#15196]
### Operating System

Windows 10 64 bit

### OpenRCT2 build

OpenRCT2 v0.3.4.1

### Describe the issue

All the text in the game has this weird bug where the character L is replaced with a Z with a line over it. (and J with a U with a dot over it) 
ex.
![bug](https://user-images.githubusercontent.com/88733161/128898194-20c4eb22-39af-418d-9f88-e60b1a21bd3a.PNG)

### Steps to reproduce

I just opened the game and it was like this (it was after updating to v0.3.4.1, latest version as of today)

### Attachments

![scenarios](https://user-images.githubusercontent.com/88733161/128898976-f75412bf-4562-410f-8d77-752e346f5012.PNG)
scenario select screen

**Comment by duncanspumpkin** [comment]
Your installation is out of date. Update your g2.dat file.

**Comment by potatoes979** [comment]
thanks I was using an old shortcut haha
