### ISSUE TITLE
Opening a 3D cinema underground crashes game

### ISSUE THREAD

**Issue by JarnoVgr** [OpenRCT2/OpenRCT2#1521]
How to reproduce:
1. Build a 3D cinema underground (with entrance and exit)
2. Open attraction
3. Le Crash.

Works fine in original.

**Comment by chrismilne300** [comment]
Putting any ride underground seems to crash the game

**Comment by duncanspumpkin** [comment]
Its crashing in a vanilla function so might need more implementation in order to work out the cause.

**Comment by duncanspumpkin** [comment]
I think this is fixed in my latest commit https://github.com/OpenRCT2/OpenRCT2/commit/66430b41db89b672f6a250c8e4e7d0bc8f0377a7 can someone confirm.
