### ISSUE TITLE
Some senarios show the incorrect park name and description when loaded

### ISSUE THREAD

**Issue by RoelerCoaster** [OpenRCT2/OpenRCT2#15225]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (767dbfe on develop) provided by GitHub

### Describe the issue

When loading some scenarios scenario selection window seems to change the park name to "Six Flags Magic Mountain" and when the park is loaded the description of the scenario "Six Flags Magic Mountain" is shown instead of the correct one. The objective remains correct. Also, the park name and the description is correct in the scenario selection window, the incorrect text is only shown once the scenario is loaded.

It doesn't seem to be happening on all of the parks. I haven't tested all of the scenarios, but some scenarios on which this seems to happen:
- Africa - Victoria falls
- Asia - Maharaja Palace
- South America - Rain Forest Plateau
- Rock 'n Roll - Flower Power
- Prehistoric - Stone Age
- Build your own Six Flags Magic mountain (only the description is incorrect)

Some examples where it doesn't seem to happen:
- As far as I can tell: any of the base RCT2 beginner, intermediate or expert scenario's 
- Asia - Great Wall of China Tourism Enhancement
- North America - Rollercoaster Heaven

I cannot seem to deduce a pattern from this which parks are affected and which are not.

### Steps to reproduce

1. Start a new game using one of the problematic scenarios, for example Africa - Victoria falls
2. Observe the text in the park-window that opens
3. Title/park name is incorrect
4. Description is incorrect
5. Objective is correct

### Attachments

![Six Flags Magic Mountain 2021-08-15 22-19-13](https://user-images.githubusercontent.com/5968886/129491628-42c351cf-c297-42c1-9f3d-f2145f7cb070.png)

**Comment by seifer7** [comment]
I've identified the bug and will open a pull request shortly.
