### ISSUE TITLE
Patrol Area selector not showing

### ISSUE THREAD

**Issue by CamdenCornwall** [OpenRCT2/OpenRCT2#15240]
This is on an android build of openrtc2 running on a Chromebook.
Running version 0.3.4.1

The grey selector is not visible when selecting patrol areas for any of the staff. The blue selected areas do show though.

**Comment by Gymnasiast** [comment]
We have a nice, easy-to-use bug reporting form, why didn’t you use that? This report contains almost no information, not even the commit/build or a screenshot or something.

**Comment by CamdenCornwall** [comment]
Oh I see now, under the Problems, Bugs and Feedback. Sorry for my ignorance, I'm learning.

**Comment by Gymnasiast** [comment]
I see you posted on the forums, but your topic is hidden? Did you do that yourself? Has your issue been solved now?

**Comment by CamdenCornwall** [comment]
I hid it. I realized that it wasn't really a bug. That's the way the game
has always been. And I feel I've made enough of a fool of myself so I
closed it. Sorry to have bothered you and wasted your time.

**Comment by Gymnasiast** [comment]
> And I feel I've made enough of a fool of myself so I closed it. Sorry to have bothered you and wasted your time.

There is no reason to say that. I don’t expect people to understand everything the first time round. You stayed polite. You did not make a fool of yourself.

(I have had people who *actually* did, throwing tantrums when we took out a minor feature that caused a lot of side effects, or when we didn’t fix their issue within a day(!).)

Don’t be reluctant to come ask for help again if you need it. When in doubt, asking on the forums or on our Discord is the best approach.
