### ISSUE TITLE
Improper toolbar buttons in Scenario Editor

### ISSUE THREAD

**Issue by sta5is** [OpenRCT2/OpenRCT2#15257]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (9511104 on develop) provided by GitHub

### Describe the issue

In the Scenario Editor, the chat toolbar button is present even though it is not a multiplayer session. Furthermore, the zoom toolbar buttons are present even if unchecked in the options.

![scenario editor chat zoom](https://user-images.githubusercontent.com/26368692/130334731-e7d94f9b-2b48-45a5-8453-2def03db23d3.PNG)

### Steps to reproduce

1. Open the scenario editor
2. If the chat toolbar button is checked in the options, the button for it will be present even though multiplayer cannot be used in this environment. If the zoom toolbar buttons are unchecked in the options, they will be present regardless

**Comment by sta5is** [comment]
Same issues also in the Track Designer

![image](https://user-images.githubusercontent.com/26368692/130334883-fc4d7fff-6660-4dd9-8b32-e4ce8d733da8.png)

**Comment by seanmajorpayne** [comment]
I will work on this if no one else has started :)

**Comment by seanmajorpayne** [comment]
PR is up with a fix.
