### ISSUE TITLE
Strange "Can't construct this here..." when placing rides higher than ground

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#1525]
When placing shops/stations higher than ground, a "Can't construct this here..." message will be appeared, however, when you try few times more, the shops/stations will be built in the same place.  I also tried to build shops higher than ground in two different scenarios, and the bug showed up almost every time. FYI, I have tested in the some builds in the 88x-898 range from OpenRCT2.com.

The video of showing this bug and the save of reproducing this bug are attached below:
https://drive.google.com/file/d/0B2_12DbzmFxYajB2dTlSdXM1aEk/view?usp=sharing
https://drive.google.com/file/d/0B2_12DbzmFxYSHRFTHdFOGpYNjg/view?usp=sharing

**Comment by daihakken** [comment]
I also tried to repeat the same procedure in vanilla RCT2, and I cannot reproduce the bug in it.

**Comment by duncanspumpkin** [comment]
That was a tough to track down bug thanks for the challenge.
