### ISSUE TITLE
New wall objects placed in 8de2965 contains "banner text" info

### ISSUE THREAD

**Issue by sta5is** [OpenRCT2/OpenRCT2#15255]
### Operating System

Windows 10

### OpenRCT2 build

v0.3.4.1 (8de2965 on develop)

### Describe the issue

Placing any size of wall objects in 8de2965 shows banner text info when the object placed is not a banner.
![banner text wall object](https://user-images.githubusercontent.com/26368692/130326137-b579f622-cb10-48c5-8f57-5ecbfdb92374.PNG)

The info for another wall object on the same tile placed before 8de2965 properly shows "not a banner"
![banner text wall object2](https://user-images.githubusercontent.com/26368692/130326139-2c6cc055-ddf3-42bb-84d6-a2160ac5437d.PNG)

### Steps to reproduce

1. Place wall objects in 8de2965
2. Tile Inspector info shows "banner text" where there should not be any

### Attachments

Affected save can be provided via private message because the park is being built for an ongoing competition

**Comment by ZehMatt** [comment]
I'm unable to reproduce this bug, the commit in question also does not modify any code that would lead to such results. Is there anything specific I have to do in order to reproduce this? Placing any wall does not give me a banner info.

**Comment by Gymnasiast** [comment]
Can you DM me the save via Discord?

**Comment by ZehMatt** [comment]
I managed to reproduce the bug, after placing a few normal signs I noticed that the wall started to say "Sign" as banner text.

**Comment by ZehMatt** [comment]
All walls have the banner index 0 which is a valid index, I think we want the default to be a non-valid index?

**Comment by sta5is** [comment]
@Gymnasiast Just saw your message, sorry. It seems as though you guys figured it out so would you still want the affect save for further investigation? Thank you and @ZehMatt for fixing this! Keep up the great work

**Comment by ZehMatt** [comment]
> @Gymnasiast Just saw your message, sorry. It seems as though you guys figured it out so would you still want the affect save for further investigation? Thank you and @ZehMatt for fixing this! Keep up the great work

I don't think he'll need the save anymore.

**Comment by Gymnasiast** [comment]
That is correct, yes.
