### ISSUE TITLE
Large scenery objects rendered incorrectly

### ISSUE THREAD

**Issue by sta5is** [OpenRCT2/OpenRCT2#15259]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (9511104 on develop) provided by GitHub

### Describe the issue

Large single tile objects have rendering issues when placed:

![large scenery render issue](https://user-images.githubusercontent.com/26368692/130337143-04e14399-bbe5-40cc-b84b-d1ac8624e9e4.gif)

Tile Inspector info of the object used above:
![large scenery info](https://user-images.githubusercontent.com/26368692/130337174-ec7988e4-c862-4a83-a8e9-bb83878b1406.PNG)

This issue seems to occur after 7b3258b17effa180d7553ed28954edb0ed240a96

### Steps to reproduce

1. Build large single tile scenery objects. Either placed on surface level or elevated
2. Observe rendering issues

### Attachments

Affected save can be provided via private message because the park is being built for an ongoing competition

**Comment by ZehMatt** [comment]
Would be so kind to provide a save file, you can DM me on Discord if you don't want to make it public. I'm having issues reproducing this.
