### ISSUE TITLE
Refurbishing rides adds to Park Value

### ISSUE THREAD

**Issue by Namington** [OpenRCT2/OpenRCT2#15263]
### Operating System

Windows 11, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.4.1

### Describe the issue

When using the refurbish function on a ride, your park value increases by an amount equal to the base value of the ride. There are often subsequent fluctuations in park value.

### Steps to reproduce

1. Have any ride which can be refurbished.
2. Use the refurbish function on an eligible ride.
3. Observe change in Park Value

### Attachments
![park value](https://user-images.githubusercontent.com/89354966/130366357-790f0fca-2fa4-4356-b275-79279ec38da6.png)
The massive spike in park value is the first time I used the refurbish function. Nothing new was constructed in the park in that period. I only realized beacuse $500k park value was the goal on that park, and last I'd seen my park value was ~$370k, but I suddenly won without adding to the park in any way.

**Comment by spacek531** [comment]
the refurbish feature is a 1-click way to completely rebuild the ride. It doesn't actually rebuild the ride, but it does the same thing as if it was completely rebuilt. The park value uses ride age as a factor, so a ride going from many years old to brand new would make a bump in park value.

**Comment by ZehMatt** [comment]
As explained above this is to be expected.

**Comment by Namington** [comment]
> the refurbish feature is a 1-click way to completely rebuild the ride. It doesn't actually rebuild the ride, but it does the same thing as if it was completely rebuilt. The park value uses ride age as a factor, so a ride going from many years old to brand new would make a bump in park value.

Except that it increases the park value by the full value of the ride in question, no matter the age of the ride. If the ride is at 99% reliability, it has the same impact as if the ride is at 30%. You could theoretically build a single ride, and refurbish it every time it becomes available until you reach whatever park value that you wish. 

Of course, that being said, bug or no, this doesn't really impact gameplay in general. I'll try to examine the behavior further and find out if there's more going on than is immediately apparent, as I've observed wild fluctuations in park values on the heels of refurbishing rides. Maybe the spike in park value corrects itself at some interval?

**Comment by ZehMatt** [comment]
> > the refurbish feature is a 1-click way to completely rebuild the ride. It doesn't actually rebuild the ride, but it does the same thing as if it was completely rebuilt. The park value uses ride age as a factor, so a ride going from many years old to brand new would make a bump in park value.
> 
> Except that it increases the park value by the full value of the ride in question, no matter the age of the ride. If the ride is at 99% reliability, it has the same impact as if the ride is at 30%. You could theoretically build a single ride, and refurbish it every time it becomes available until you reach whatever park value that you wish.
> 
> Of course, that being said, bug or no, this doesn't really impact gameplay in general. I'll try to examine the behavior further and find out if there's more going on than is immediately apparent, as I've observed wild fluctuations in park values on the heels of refurbishing rides. Maybe the spike in park value corrects itself at some interval?

Refurbish is equivalent to demolishing and placing the same ride at the same position again, so you could raise your park value by basically manually doing this.

**Comment by Namington** [comment]
I could not reproduce the issue I believed to exist under controlled conditions. I clearly have misinterpreted my experience. Thanks for taking the time to respond.
