### ISSUE TITLE
"Enter selection size" prompt displays wrong values

### ISSUE THREAD

**Issue by sta5is** [OpenRCT2/OpenRCT2#15271]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (e48dd2d on develop) provided by GitHub

### Describe the issue

The prompt that allows input between 1 to 64 displays incorrect values.

![selection size](https://user-images.githubusercontent.com/26368692/130579062-943008ef-4f3d-4081-976c-f219b7756b60.PNG)

### Steps to reproduce

1. Open any window that has size selection option (landscaping, water tool, clear tool, scatter tool, land purchase mode, and map size)
2. Click on the size selection to open prompt that allows inputting values between 1 to 64
3. Notice underflow/overflow values

**Comment by Broxzier** [comment]
Looks like a formatting issue.
