### ISSUE TITLE
Scenario description missing when loading a park from a save file

### ISSUE THREAD

**Issue by RoelerCoaster** [OpenRCT2/OpenRCT2#15274]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (201a94f on develop) provided by GitHub

### Describe the issue

After loading a save file (.sv6), when you open the Park Information window, the scenario description appears to be missing. The objective is still displayed normally.

### Steps to reproduce

1. Start a new scenario
2. Open the Park Information window and see that the scenario description is present
3. Save the park
4. Load the save file
5. Open the Park Information window again and see that the scenario description is now missing

### Attachments

![Crazy Castle 2021-08-24 18-30-09](https://user-images.githubusercontent.com/5968886/130662507-724f9170-b047-44ff-80c2-a3784ed9dfe4.png)

**Comment by seifer7** [comment]
I haven't looked into this yet but I'm assuming it's related to Issue #15225 Pull #15229 
Will look into it when I get a chance.
