### ISSUE TITLE
[RCT Scenario Import] attractions name is already given

### ISSUE THREAD

**Issue by Horsti12** [OpenRCT2/OpenRCT2#1528]
When you import a RCT Saved game into the Scenario editor which have originally attractions has some mistakes.
The game imports the Save game without the Attractions which isn't the bug, but the new park knows the name of the original attractions, what means that you can't name a attractions like in the original save game which you imported in RCT2. I hope you understand what you mean.

**Comment by IntelOrca** [comment]
I think this is because the user string list in the saved game / scenario is not being cleared.

**Comment by Horsti12** [comment]
This would be also important for the RCT1 importing scenario thing. @Gymnasiast

**Comment by Gymnasiast** [comment]
I thought this bug was solved in OpenRCT2, but I would have to look at it. Behaviour might also differ between `develop` and `rct1-import`, and within the latter, between importing as landscape and importing with rides and all.

**Comment by Horsti12** [comment]
I think this is already fixed. I tested it in one park and it  worked.

**Comment by IntelOrca** [comment]
Yea, hopefully this shouldn't be a problem now as the S4 importer doesn't do a straight copy of the user strings. It instead allocates user strings on a per ride / banner / park name basis.
