### ISSUE TITLE
"Failed to create the dump" on all crashes since release 0.3.4.1

### ISSUE THREAD

**Issue by James103** [OpenRCT2/OpenRCT2#15299]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OS: Windows (x86-64)
OpenRCT2, v0.3.4.1 (de85a17 on develop) provided by GitHub
OpenRCT2, v0.3.4.1 (233b1e9 on develop) provided by GitHub

### Describe the issue

When the game crashes **for any reason** (not just because of #15298, it outputs the following error:
`Failed to create the dump. Please file an issue with OpenRCT2 on GitHub and provide latest save, and provide information about what you did before the crash occurred.`
This means no crash dumps can be produced from recent develop builds. Why does this occur, and how can it be fixed?

Note that this does not occur in release 0.3.4.1 using the same reproduction steps and operating system.

### Steps to reproduce

1. Open the game.
2. Somehow crash the game (such as by running console command `dereference`, or `assert`).
3. Notice that no crash dumps are produced.

**Comment by IntelOrca** [comment]
@James103 do you have a `crash` sub directory in your OpenRCT2 user directory? If you don't, try creating one and see if that fixes the issue. The code is supposed to automatically create this folder though.

**Comment by James103** [comment]
I tried crashing the game (by both running `dereference` in console and by running `map.getAllEntities("guest")`) while the `crash` folder is existing, and also crashing the game without the `crash` folder.
With the `crash` folder, the game crashes, no dumps are created, and the "Failed to create the dump" error is generated.
Without the `crash` folder, the game crashes, the `crash` folder is created, but no dumps are created, and the "Failed to create the dump" error is generated.

### OpenRCT2 build
OpenRCT2, v0.3.4.1 (371478d on develop) provided by GitHub
Windows (x86-64)

**Comment by CookiePLMonster** [comment]
Please test with #15532.

**Comment by James103** [comment]
Can confirm that the issue is fixed in 483dea452c491c01c92befb13b60cbb5cc00c1de with #15532 applied.
