### ISSUE TITLE
`map.getEntity(id)` crashes the game if its argument is not a number (e.g. '{}' or 'true')

### ISSUE THREAD

**Issue by James103** [OpenRCT2/OpenRCT2#15300]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (5087e77 and 371478d on develop) provided by GitHub

### Describe the issue

Running any of the following crashes the game:
* `map.getEntity({})`
* `map.getEntity(true)`
* `map.getEntity("1")`
* `map.getEntity(null)`

Edit: Also happens with e.g. `map.getRide({})`, `map.getRide("1")` as well.

### Steps to reproduce

1. Run OpenRCT2, version 0.3.4.1 or later.
2. Run any of the above lines of code as a plug-in or in the console.

### Attachments

Crash dumps:
[de706a7e-f1ac-4ca5-9ac4-4e835bfabafd(5087e77_x86-64).zip](https://github.com/OpenRCT2/OpenRCT2/files/7069453/de706a7e-f1ac-4ca5-9ac4-4e835bfabafd.5087e77_x86-64.zip)
[4c54eecd-cb78-4c2f-895c-3c88436fdc42(5087e77_x86-64).zip](https://github.com/OpenRCT2/OpenRCT2/files/7069379/4c54eecd-cb78-4c2f-895c-3c88436fdc42.5087e77_x86-64.zip)
[aa879591-458e-4a0a-af5a-230d20445062(5087e77_x86-64).zip](https://github.com/OpenRCT2/OpenRCT2/files/7069380/aa879591-458e-4a0a-af5a-230d20445062.5087e77_x86-64.zip)
[add7ea5d-97fc-4adc-af2a-004234c8ea38(5087e77_x86-64).dmp.zip](https://github.com/OpenRCT2/OpenRCT2/files/7069381/add7ea5d-97fc-4adc-af2a-004234c8ea38.5087e77_x86-64.dmp.zip)
Example crashing plugin:
[Crashing plugin (0.3.4.1).zip](https://github.com/OpenRCT2/OpenRCT2/files/7069382/Crashing.plugin.zip)

**Comment by Broxzier** [comment]
Closing as this is just another example of the duktape exceptions not working in release builds.
