### ISSUE TITLE
Dinghy boat is visible through large enclosed turns

### ISSUE THREAD

**Issue by RoelerCoaster** [OpenRCT2/OpenRCT2#15306]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (cba52b2 on develop) provided by GitHub

### Describe the issue

On a dinghy slide, the boat should not be visible if it goes through an enclosed piece of track. However, when the boat goes through a large turn, it becomes visible even if the track is enclosed. All other pieces of enclosed track appear to work properly.

I though that it may be a renderer issue, but it happens on both the software renderer and OpenGL.

### Steps to reproduce

1. Build a dinghy slide with an enclosed large turn
2. Observe the boat as it goes through the turn.

See the attached gif for an example.

### Attachments

![dinghy](https://user-images.githubusercontent.com/5968886/131252015-df46103a-528c-4849-ad4f-10909ea02ea8.gif)

**Comment by ZehMatt** [comment]
Would you be so kind to check if this happens on a older version such as v0.3.3?

**Comment by RoelerCoaster** [comment]
I have tried the release versions of 0.3.3, 0.3.4 and 0.3.4.1, on none of them it happens.

I tried some of the past few develop versions, the first version on which it seems to happen is:

OpenRCT2, v0.3.4.1 (7b3258b on develop) provided by GitHub

**Comment by ZehMatt** [comment]
I suspected as much, thanks i'll have a look.
