### ISSUE TITLE
Clicking on Object Selection Cheat Freezes the Game

### ISSUE THREAD

**Issue by EtienneGL** [OpenRCT2/OpenRCT2#15319]
### Operating System

Windows 8

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (0be5850 on develop) provided by GitHub

### Describe the issue

When I click on the cheat "Object selection", it simply makes the game freeze. The game doesn't respond anymore.

### Steps to reproduce

1. Open any park or scenario.
2. Click on the cheat icon.
3. Select "Object selection"

### Attachments

![image](https://user-images.githubusercontent.com/33940430/131604618-b007ff34-365c-4e0a-84bd-484e9d6f487d.png)

**Comment by EtienneGL** [comment]
Update: the Object selection window opened after a while, but it took a few minutes, which is quite long.

**Comment by sta5is** [comment]
This also happens when opening the Invention List window as of v0.3.4.1 (b2d0b54 on develop)

**Comment by duncanspumpkin** [comment]
I am unable to reproduce this with either the invention list or object selection. Opened Six Flags Belgium.

**Comment by ZehMatt** [comment]
What is the file size of ```%HOMEPATH%\Documents\OpenRCT2\objects.idx``` ?

**Comment by EtienneGL** [comment]
> What is the file size of `%HOMEPATH%\Documents\OpenRCT2\objects.idx` ?

570 Kb

**Comment by Broxzier** [comment]
I was able to reproduce this, it seems to only happen to release builds. By bisecting, I found that this is the offending commit: bcba227430f0b669077c6ddac769a945177d2321, Add footpath surface and railings objects from NSF.

**Comment by ZehMatt** [comment]
This is out of bounds stuff, object_entry_group_counts doesn't have the entry for the new footpath things so it reads an arbitrary value and loops that much.
