### ISSUE TITLE
Railing displayed on wooden coaster improperly

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#15328]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (b2d0b54 on develop) provided by GitHub

### Describe the issue

Wood coaster station head has railing peeking through. Occurs with and without station.

![image](https://user-images.githubusercontent.com/3454156/131779242-ceaa6c05-3556-4f9b-ad21-684d5e30b7b9.png)

### Steps to reproduce

1. Build wooden coaster station
2. Railing on the far side is displayed improperly

**Comment by Broxzier** [comment]
> OpenRCT2, v0.3.4.1 (, DEBUG)

Looks like a local test build. Could you provide the commit hash you were on?

**Comment by spacek531** [comment]
It also occurs on develop OpenRCT2, v0.3.4.1 (b2d0b54 on develop) provided by GitHub

**Comment by ZehMatt** [comment]
I checked with the vanilla game

![image](https://user-images.githubusercontent.com/5415177/132012247-a50c6d7e-1f0b-4624-adbb-7a866cf2dd03.png)

Nothing we introduced.

**Comment by spacek531** [comment]
I never noticed it before, weird.

**Comment by TheClaudeQC** [comment]
yep, i seen this bug since i first build a wooden coaster in RCT2 Vanilla, 2.01.043 I think, this have occured since a long time and like, nobody suspected it. Weird.

**Comment by Gymnasiast** [comment]
Interestingly, this was fixed in RCT Classic: https://github.com/OpenRCT2/OpenRCT2/issues/4909#issuecomment-269000747
