### ISSUE TITLE
[NSF] No entry signs crash

### ISSUE THREAD

**Issue by Triptych366** [OpenRCT2/OpenRCT2#15325]
### Operating System

Windows 7, 64-bit

### OpenRCT2 build

Open RCT2, v0.3.3

### Describe the issue

On the newest version of the new save format, clicking the "no entry" on the regular/standard signs, does not activate the no entry mode.  I tried with multiple signs in multiple angles on one park.  No matter how many times I clicked the red minus sign (no entry), it would not activate.  I then went to delete the sign(s) and the game crashed (froze).

### Area(s) with issue?

Building the game

### Steps to reproduce

1. Place a standard sign.
2. Press the no entry symbol.
3. Delete the sign.

### Attachments

N/A

**Comment by duncanspumpkin** [comment]
Which build. Please state the commit hash.

**Comment by Broxzier** [comment]
999daa9 was from the second round of testing the New Save Format. Needs checking to see if this bug is still there.

**Comment by ZehMatt** [comment]
![image](https://user-images.githubusercontent.com/5415177/134567680-b97934a7-3aa2-4ce1-b983-c6061b36b08d.png)

I can't reproduce this, deleting banners also doesn't crash the game for me. If this issue persists please let us know.
