### ISSUE TITLE
Fallback language system for .DAT files

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#1533]
Anyone with a sizeable collection of custom .DAT files will probably have a few where the author only put a description in the fields for his/her own language, leaving all the others blank.
It would be nice if OpenRCT2 could try other translations if it can't find one in the user's language (falling back to UK English, US English and then all other languages, for example).

If someone needs an offending file, I have one (which has only US English filled in).

**Comment by duncanspumpkin** [comment]
Upload the file. From looking at `object_get_localised_text` the order is as follows: localised text, english uk, 1st string in table. So not quite sure why your file turns up nothing.

**Comment by Gymnasiast** [comment]
https://www.dropbox.com/s/1h2mzt8cdblt5mn/KIDSDINO.DAT?dl=1

**Comment by duncanspumpkin** [comment]
Yup for that file he has put a space for the uk english name so it mess's up the defaults. I'm going to make it so that it checks if the string is a space and if it is ignore it.
