### ISSUE TITLE
Console spam after running bpb1000ticks

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#15371]
### Operating System

Windows 10

### OpenRCT2 build

85fcc8325

### Describe the issue

After bpb1000ticks finishes comparing, after a minute or two this spam appears:

![image](https://user-images.githubusercontent.com/3454156/132463463-cc4dbb2b-9b27-4358-adc1-faf1116f36f2.png)

I ran Evergreen Gardens for a few minutes and the spam didn't appear, but I may not have run it long enough.

### Steps to reproduce

1. 
2. 
3.

**Comment by duncanspumpkin** [comment]
That would be the music object. Your parent commit is 454eabe. @Gymnasiast could you have a look.

**Comment by spacek531** [comment]
[Six Flags circus.zip](https://github.com/OpenRCT2/OpenRCT2/files/7157640/Six.Flags.circus.zip)

I think it's related to the circus because this park with just a circus loads with the spam

**Comment by Gymnasiast** [comment]
This should have been fixed as of https://github.com/OpenRCT2/OpenRCT2/commit/2f2e8b4c483c0dd6d7a74269830bcb6b93d549ed . Could you check?

**Comment by spacek531** [comment]
Tested using 5087e77 using bpb1000ticks 0.3.4.1-0. I did not see any of the above pictured console spam.

**Comment by Gymnasiast** [comment]
Of course it won’t happen on 5087e77, that’s a commit from before the issue was introduced. I need you to test with a _develop_ build.

**Comment by spacek531** [comment]
My launcher was set to release on accident. OpenRCT2, v0.3.4.1 (427bb7b on develop) provided by GitHub doesn't create the spam during or after bpb1000ticks 0.3.4.1-8.
