### ISSUE TITLE
Entrances and exit get immediately removed after placing both

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#15375]
### Operating System

Windows 10 x64

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (a399108 on develop) provided by GitHub

### Describe the issue

When building a tracked ride, placing the entrance and exit works, but once you have placed them both they get removed.

### Steps to reproduce

1. Start building any tracked ride (I picked car ride)
2. Build at least one station
3. Place the entrance and exit
4. Observe how they immediately get removed

**Comment by Broxzier** [comment]
Bisecting shows this was introduces with dba4518d118a74244fbd5170fbf39e9dcfa3e345.

**Comment by Broxzier** [comment]
After some more inspecting, I found that the placement of entrances only works for one direction. Two others get immediately removed, and the other makes the entrances have the wrong direction, causing issues with pathing.

**Comment by spacek531** [comment]
I'll take a look
