### ISSUE TITLE
Disappearing bottom HUD

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#1537]
Disappearing bottom HUD while selecting a save game to load while "about-to-win" scenario is running and triggers the winning condition.

https://www.reddit.com/r/openrct2/comments/3bxcek/latest_developer_build_bugs_003_908_incomplete/

**Comment by daihakken** [comment]
The disappearance also appeared once in my corrupted "Vertigo Views", while I was trying to save when ride constructions, path constructions, finance, scenery, invention windows were opened.

**Comment by duncanspumpkin** [comment]
Fix found. Issue was caused by window order being changed.
