### ISSUE TITLE
Elements on western corner seem cut off when looking from the east

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#15376]
### Operating System

Windows 10 x64

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (a399108 on develop) provided by GitHub

### Describe the issue

Elements near the upper corner seem to be cut off when looking from the east. All parks I've checked seem affected by this bug, also online servers, so this is unlikely to be corruption.

![Mega Park  2021-09-08 19-12-46](https://user-images.githubusercontent.com/9705046/132554545-475a89bc-ef4f-4f4a-bfea-e365ac06ffcc.png)
![Leafy Lake 2021-09-08 19-10-34](https://user-images.githubusercontent.com/9705046/132554548-9b1e3a86-f8b3-4f2b-9b6c-f130516fc7c7.png)
![Diamond Heights 2021-09-08 19-10-05](https://user-images.githubusercontent.com/9705046/132554549-db37929d-58a3-4b7f-b1f8-5b3ff2fec6c4.png)
![Dynamite Dunes 2021-09-08 19-09-16](https://user-images.githubusercontent.com/9705046/132554551-f2bd3c60-6c31-4f7f-bd1f-508db7e165d8.png)

### Steps to reproduce

1. Open any map
2. Rotate the map so that you look from the east (current_rotataion=1)
3. Move the camera up to the upper corner of the map

**Comment by ZehMatt** [comment]
I cant reproduce this on my end somehow at least not with debug builds, I'll see if release makes any difference.

**Comment by pytty** [comment]
I can reproduce this on any map and save

**Comment by jensj12** [comment]
![Happy park (sb) 2021-09-10 09-17-36](https://user-images.githubusercontent.com/13868449/132815364-78abdd92-52de-4dbb-a5dc-2766bb2128e8.png)
Issue is still present in version e284147 though not in all parks, so I've attached a save: 
[Sandbox1.txt](https://github.com/OpenRCT2/OpenRCT2/files/7141945/Sandbox1.txt)
