### ISSUE TITLE
Entrence didn'T wanted to connect

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#15386]
### Operating System

Windows10 32-bit

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (a399108 on develop) provided by GitHub

### Describe the issue

well, i build an entrence and it can't connect, but right before, i could connect them. it's only when i build a second coaster that happened.

Well, i think the bug occured when someone joined, but i also think it's random, since it only did whit the twister coaster.

### Area(s) with issue?

This bug is specific to multiplayer

### Steps to reproduce

1. Have someone joining
2. Try to build a new coaster
3. and then it's will normally (as i guess) not connect any entry/exits

**Comment by TheClaudeQC** [comment]
![Jungly Mountain 2021-09-09 15-15-54](https://user-images.githubusercontent.com/83843734/132748843-dc6661d2-4bb6-4c0a-b1be-94c85cf6da8d.png)
the smaller palm tree is the ones where is the station 5 pieces in total since 1 of them is above the station
the bigger ones are the exit and entrence

**Comment by spacek531** [comment]
Have you updated your game to the latest version? This bug existed for about 1 day and was patched.

**Comment by Broxzier** [comment]
a3991085be756b3ec14c3b16a2a6554a26b26335 is from before the fix was merged. Update the fane and it will be fixed. You'll have to replace entrances and exits for affected attractions.

**Comment by TheClaudeQC** [comment]
@Broxzier is the fix is the same version, because the multiplayer map is on 3.4.1-8

**Comment by TheClaudeQC** [comment]
and it actually did in a very specific place

**Comment by Broxzier** [comment]
> @Broxzier is the fix is the same version, because the multiplayer map is on 3.4.1-8

Probably, the network version was not increased for the fix, but something else may have increased it in the meantime.

> and it actually did in a very specific place

I'm not following what you're trying to say.

**Comment by TheClaudeQC** [comment]
> i'm not following what you're trying to say

Well, it's happening on the X=94 89<Y<96 while trying to place at X=93 and X=95 the entrence on a max sized map

**Comment by Broxzier** [comment]
OK, but try with the latest build to see if it still happens.

**Comment by TheClaudeQC** [comment]
> OK, but try with the latest build to see if it still happens.

nope, i tryed and it'S fixed

**Comment by TheClaudeQC** [comment]
but, where is the conner black bug issue, because i found out it'S every conner, while looking at it on the opposite angle of it
