### ISSUE TITLE
Hotkeys for tile inspector height swapped/broken

### ISSUE THREAD

**Issue by thingsontracks** [OpenRCT2/OpenRCT2#15393]
### Operating System

Windows 10, 64 Bit

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (e75c3458 on develop) provided by GitHub

### Describe the issue

Hello,
when selecting an objet with the tile inspector the hotkey for raising the element does nothing and the hotkey for lowering the element raises it instead.
This bug does not occur in the regular release or developement versions.

### Steps to reproduce

1. Select any object (surface, scenery or track) with ctrl+left click
2. Press the hotkey for "Tile Inspector: increase element heigth" or "Tile Inspector: decrease element heigth"
3. Increasing doesn't do anything. Decreasing increases the height instead

**Comment by Gymnasiast** [comment]
I can’t find that commit and I find your “ This bug does not occur in the regular release or developement versions.” also quite confusing. Are you talking about a New Save Format test build, or ... ?
