### ISSUE TITLE
Visual corruption on a horizontal line when looking south to north

### ISSUE THREAD

**Issue by jensj12** [OpenRCT2/OpenRCT2#15390]
### Operating System

Windows 10, 64bit

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (e284147 on develop) provided by GitHub

### Describe the issue

There's a horizontal line of visual corruption through the entire map. On that line land height marks are not present and just above that line track height marks are not displayed. It happens about 256 tiles down from the top.
Originally reported on the [forum](https://forums.openrct2.org/topic/5677-drawing-glitch-in-one-area-of-park/)

### Steps to reproduce

1. Open any map that is at least 128x128.
2. Set rotation to look from south to north.
3. Look around, it might be easier to find with (track or land) height marks on, or on maps with large bodies of water (like alcatraz)

### Attachments

![Happy park 2021-09-10 09-14-03](https://user-images.githubusercontent.com/13868449/132817541-9d68160f-8ee7-4237-93d2-1d77ef8d09fd.png)
![Hook Panorama 2021-09-10 09-12-38](https://user-images.githubusercontent.com/13868449/132817543-9b67b697-6880-4844-b57e-241d85988f10.png)

**Comment by duncanspumpkin** [comment]
@ZehMatt more bucket issues?
