### ISSUE TITLE
Clearing large scenery with the clear scenery tool is profitable.

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#1539]
Clearing large scenery with the clear scenery tool is profitable.

https://www.reddit.com/r/openrct2/comments/3bxcek/latest_developer_build_bugs_003_908_incomplete/

**Comment by warp-10** [comment]
The tool is repeatedly adding the removal cost for each tile comprising a large element.

My first thought is to somehow tag scenery entries that its already accounted for, then to reset the tags afterward.

**Comment by duncanspumpkin** [comment]
I was thinking maybe only count the removal cost for index 0 of the large element. Would need to have a little think how this would work though.

**Comment by warp-10** [comment]
I should have added that the cost depends on the number of tiles inside the tool region (calls game_command_remove_large_scenery once per tile within the region). I have an idea that will work, which I'll try when I wake up...

**Comment by mzmiric5** [comment]
I think this issue happens when refunding individual buildings as well, like you can keep on building and selling the same building and the refund increases by the refund ammount each time without resetting

**Comment by warp-10** [comment]
A thought just occurred to me: The tool will break if you have multiple large scenery items stacked on top of one another. The only solution is to dynamically allocate the memo table as entries are being added. A goal for the refactor after everything has been reversed might be to add utility flags to scenery entries; this would eliminate the need for a memo table in this case.

As for buildings: AFAICT, nothing in map.c touches rides/shops/etc.., so that would be another bug. This bug specifically concerns large scenery items.

**Comment by duncanspumpkin** [comment]
@warp-10 the building/ride bug was something i introduced the other day. Don't worry about it its already been fixed. I have a new idea for how to do the removal price. Again its hacky. Make a backup of the map elements, delete the large scenery every time you go to work out price, revert backup of map elements. This way you can calculate the value correctly.

**Comment by warp-10** [comment]
That also works, though I would prefer to avoid modifying the map in that way just for a scenery removal tool. Since this is a completely new feature, I would suggest waiting for a fully independent release before adding too many more things (too much stuff is still going through vanilla code as it is).

I can go wither way on this one, though just modifying what I've proposed to dynamically re-size the table as needed (very, very infrequent) would be much easier (a few seconds of work).

**Comment by IntelOrca** [comment]
Why can't you just only include the cost for the tile with sequence 0 like @duncanspumpkin suggested earlier?

**Comment by duncanspumpkin** [comment]
because of the way the scenery is destructed you might not have sequence 0 in your selection.

**Comment by IntelOrca** [comment]
It must delete tile sequence 0 somehow, whether its in your selection or not right?

**Comment by duncanspumpkin** [comment]
You can't do it like that because the cost is always the price on the first run through the function where sequence 0 is not removed. Does the broken flag ever get used by large scenery? Perhaps we can hijack the flag to indicate that a large scenery item has been counted?

**Comment by IntelOrca** [comment]
Not if we stop nesting the other game commands in the clear function and instead write code for the multiple scenery to deal with by only accounting cost for sequence 0.

**Comment by warp-10** [comment]
@IntelOrca If flags are doable, then I'd prefer going that route. The result would just be a two phase process: Accumulate cost (set flags to avoid duplicates), then reset flags or remove items (depending on what the tool is doing).

**Comment by duncanspumpkin** [comment]
I'm just going to write out the problem in full so that we are all on the same page.

Assume we have a selection area as below. Bold represents selected squares.

    |   |   |   |   
---|---|---|---|---
   | LS0 | LS1 | SF | SF
   | LS2 | **LS3** | **SF** | SF
   | LS4 | **LS5** | **SF** | SF

LSX = Large Scenery, sequence X
SF = Surface element only.

When the function goes to work out the cost for removing everything selected it will iterate accross every selected tile. LS3 is hit first and returns a cost of £50. The next tile is surface and returns £0. Then LS5 is hit and returns £50. Then surface is hit and returns £0. The total estimated removal price is summed to £100 even though LS3 and LS5 are in the same scenery item. This value is then displayed on the clear scenery window.

Next the user clicks and the function runs again. This time with the APPLY flag set. The scenery clear selection game command is first run with the flag unset to check that it is possible to complete the command. This runs identically as before and returns £100. It then runs with the APPLY flag set and returns £50 since the large scenery was removed during the LS3 tile. The game command function then takes the larger of the two values and processes a fee of £100.

If we were to only calculate the value on SF0 then the estimate function returns 0 since SF0 is not in the selection (even though it will be removed). When it is in apply mode it would return £50 since SF0 is part of the removal code. So that will be wrong for estimating the price but correct when run.

What #1544 does is every time a large scenery item is encountered in the clear function it checks a table to see if that type has already been counted. If it has been counted returns 0 else adds it to the list and returns £50. The problem with this is multiple large scenery of the same type will be ignored. Possibly could be improved by using the coordinates of SF0 as its index.

The proposed flag version would set a flag on the map elements have been marked for removal by the large scenery function. Then when the flag is hit again it would be ignored when calculating price. The issue with this is we then need to run a function after calculating the value to undo the flag. This would need to be run after the first run of the APPLY version of clear scenery is run (if that makes sense). Issues with this is we are unsure if there is a free map element flag for this use.

Anyone have another idea?

**Comment by IntelOrca** [comment]
Nope, so here's my suggestion:
1. For each tile, for each element and large scenery siblings: clear flag.
2. For each tile where flag is not set, set flag and accumulate cost, if large scenery, set flag for siblings.

This will then get the right cost for the pre-remove cycle. There is no need to do anything with flags for the remove cycle.

**Comment by warp-10** [comment]
@duncanspumpkin The memo table in #1544 is keyed with the address of each item's element-0 - this is unique per element. I've already tested this with multiple identical large items
