### ISSUE TITLE
Refactor is_sprite_interacted_with to avoid copies of the palette

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#15409]
First copy:
https://github.com/OpenRCT2/OpenRCT2/blob/6ffb03dde011bbde089facbde7369f7205710386/src/openrct2/interface/Viewport.cpp#L1606

Second copy:
https://github.com/OpenRCT2/OpenRCT2/blob/6ffb03dde011bbde089facbde7369f7205710386/src/openrct2/interface/Viewport.cpp#L1616

Third copy:
https://github.com/OpenRCT2/OpenRCT2/blob/6ffb03dde011bbde089facbde7369f7205710386/src/openrct2/interface/Viewport.cpp#L1618

No copy should be happening here.

**Comment by kaushikroychowdhury** [comment]
Hello, I want to work on it. Please assign me with this issue and tell me How can I fix this issue. I am new.
Thank you best Regards

**Comment by kaushikroychowdhury** [comment]
Okay I got it. I am working on it.

**Comment by kaushikroychowdhury** [comment]
PaletteMap::GetDefault()
GetPaletteMapForColour(index)

Is this two Function return same value ?
