### ISSUE TITLE
Develop console help does not provide much information

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#1540]
https://www.reddit.com/r/openrct2/comments/3bxcek/latest_developer_build_bugs_003_908_incomplete/

The above user could not work out how to hide the console because of this.

**Comment by mzmiric5** [comment]
Should probably include the help messages for each individual command (or a command description) next to each listed command

**Comment by marijnvdwerf** [comment]
I'm curious. Is there a reason why the debug console isn't a normal floating window?

**Comment by duncanspumpkin** [comment]
There hasn't been anyone asking about the console for some time so I think the help must be adequate now.
