### ISSUE TITLE
cant open files in develop, shows files but with missing scenery in release

### ISSUE THREAD

**Issue by ricardowordo** [OpenRCT2/OpenRCT2#15420]
### Operating System

windows 10

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (2f2e8b4 on develop) provided by GitHub

### Describe the issue

i was playing on the develop version placing scenery with the scenery manager plugin when the game created ghost scenery, it then crashed with the message: failed to save dump file. i then tried it with the release version (OpenRCT2, v0.3.4.1 (5087e77) provided by GitHub) it opened but it removed any scenery in the park and also removed the ride vehicles. when i closed it it said the message again
[Ricardowordo_stage9.zip](https://github.com/OpenRCT2/OpenRCT2/files/7178369/Ricardowordo_stage9.zip)

### Steps to reproduce

1.  
2. 
3. 
![image](https://user-images.githubusercontent.com/51166489/133627494-8514afe8-e043-44bb-892e-2d53828de0b5.png)
![image](https://user-images.githubusercontent.com/51166489/133627534-dceaafaf-eba8-4023-8171-14cdd096066c.png)

### Attachments

[Ricardowordo_stage9.zip](https://github.com/OpenRCT2/OpenRCT2/files/7178371/Ricardowordo_stage9.zip)
[autosave_2021-09-16_14-41-38.zip](https://github.com/OpenRCT2/OpenRCT2/files/7178375/autosave_2021-09-16_14-41-38.zip)

**Comment by Broxzier** [comment]
This was fixed and merged to develop [45 minutes ago](https://github.com/OpenRCT2/OpenRCT2/pull/15419), make sure you're on the latest version.
