### ISSUE TITLE
Ride window viewport is partially grey

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#15439]
### Operating System

Ubuntu 20.04

### OpenRCT2 build

v0.3.4.1+ - d3f7660a46453af38c255c01d58d14edf94f1ee2

### Describe the issue

When clicking a ride, the viewport initially shows as partially grey. When selecting another view, this goes away.

### Steps to reproduce

1. Open a park with rides, e.g. Electric Fields
2. Click any ride, for example the station of the Boat Hire.
3. Observe part of the viewport is missing

### Attachments

![afbeelding](https://user-images.githubusercontent.com/1478678/133941112-a4cba38e-55c9-4796-80b4-a0acbb0a26a7.png)

**Comment by duncanspumpkin** [comment]
Suspect it's due to how I changed the ride viewport invalidation. Will need to add a tiny bit of code to the resize event

**Comment by duncanspumpkin** [comment]
So it seems ride windows unlike all other windows with a viewport do not have resize code in their resize function. How odd that they would be designed differently. I'm just going to add the resize code as the previous way it worked was a bit wasteful and unintuitive.
