### ISSUE TITLE
Toilets made out of wooden support for the grey path?

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#15432]
### Operating System

Windows10 32-bit

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (9112044 on develop) provided by GitHub

### Describe the issue

well, i just found this in the [shop] slidder of avaiable rides

### Area(s) with issue?

Building the game

### Steps to reproduce

1. Get the last version (i know that didn't happened in the last develop before this one)
2. go to shop folder in [scenario editor] or [scenario moddifications]
3. get toilet whit random sprites

### Attachments

![Parc sans nom 2021-09-18 15-28-19](https://user-images.githubusercontent.com/83843734/133906483-786b8020-24c0-4c92-875f-4102620e07c7.png)

**Comment by TheClaudeQC** [comment]
and it also seem to sell random foods/drinks/souvenirs stocks

**Comment by Gymnasiast** [comment]
Your objects folder contains objects it shouldn’t. Most likely, you tried out the new save format build and then switched back to a regular 0.3.4.1 release build.

Uninstall OpenRCT2 completely, then reinstall it and see if the issue persists.

**Comment by TheClaudeQC** [comment]
but, i don't wanna lose all my stuff i made myself and other's elements

**Comment by Gymnasiast** [comment]
You won’t lose your stuff. Uninstalling OpenRCT2 will not remove content you created yourself or objects you downloaded.

**Comment by TheClaudeQC** [comment]
ok

**Comment by Gymnasiast** [comment]
Since we haven’t heard back from you, I’m assuming your issue has now been solved.
