### ISSUE TITLE
[NSF] .Park files no longer opening

### ISSUE THREAD

**Issue by StrangeAnomoly** [OpenRCT2/OpenRCT2#15447]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT v0.3.4.1(4f6af6f/pull1064/merge)

### Describe the issue

I can no longer access .park files. Whenever I try to open them it immediately cuts back to the title screen.

### Area(s) with issue?

New Save Format (NSF)

**Comment by sfisher923** [comment]
Mostly getting the same outcome (Only had luck 1 park that had stuff placed out of 28) with the same OS (Windows 10 x64)

**Comment by duncanspumpkin** [comment]
How can we investigate your issue if you don't provide a save file?

**Comment by sfisher923** [comment]
Not the original poster but Here are some of my affected saves from Public Build 2
[Tsundereland.zip](https://github.com/OpenRCT2/OpenRCT2/files/7219677/Tsundereland.zip) - Opens fine on my end
[Bug Report 5.zip](https://github.com/OpenRCT2/OpenRCT2/files/7219686/Bug.Report.5.zip) - Affected
[Magic Park 1.zip](https://github.com/OpenRCT2/OpenRCT2/files/7219708/Magic.Park.1.zip) - Affected

s

**Comment by duncanspumpkin** [comment]
f265135 closes this (tested Magic Park1)
