### ISSUE TITLE
Huge amount of lag in magic mountain six flags (full builded one)

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#15448]
### Operating System

Windows10 32-bit

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (9112044 on develop) provided by GitHub

### Describe the issue

i have a lot of lag whit this park, only having 4 fps, while in vanilla RCT2, it was working fine

### Area(s) with issue?

None

### Steps to reproduce

1. get into magic mountain six flags
2. LAAAAGGGGGG
3. That's it, just lag when you enter this park

### Attachments

https://drive.google.com/file/d/1EKOlm0hNciGNIj3IQ6SAJZOnKcM9Mogv/view?usp=sharing

https://user-images.githubusercontent.com/9705046/134021961-6b6d108d-abaa-4e76-963b-62f4ad3c47d0.mp4

**Comment by TheClaudeQC** [comment]
https://drive.google.com/file/d/1ENUbQz5eaTh9erltRCKBxr4fQUhZttAe/view?usp=sharing is in the Vanilla

**Comment by IntelOrca** [comment]
Is this something that has just started happening or has it always been 4 fps since you started playing OpenRCT2? Do older releases have this issue for you?

**Comment by TheClaudeQC** [comment]
since i started playing in open rct2, (about mars 2021), i am on a laptop

**Comment by TheClaudeQC** [comment]
and trying to get in the first version just instant crash me, i can't go back

**Comment by ZehMatt** [comment]
If you provide a save file we would be able to look into it

**Comment by TheClaudeQC** [comment]
> If you provide a save file we would be able to look into it

well, it's the park "magic mountain six flags" in the "real park" of RCT2

> Edit: I just noticed you specified your OS Version as `Windows10 32-bit`, if your CPU is capable of 64 bit you should update, you are holding yourself back performance wise.

Maybe it is, i gonna try

**Comment by TheClaudeQC** [comment]
i tryied in 64 bit, everything still work the same, same normal fps in empty maps, lot of lag in six flags in the "real parks"

**Comment by ZehMatt** [comment]
Are you building the game yourself or are you using artifacts/releases from us?

**Comment by TheClaudeQC** [comment]
well, i just put this option because it's only happening in Open RCT2.
I take the releases that's it

yes, i have few but it didn'T afect my fps at all, in my sandbox map, it still showing about the same amount of FPS

**Comment by ZehMatt** [comment]
I just tested the park and I don't see any of the issues.

1080p software renderer:
![openrct2_2021-09-20_19-10-25ca69be3c5a62a0647](https://user-images.githubusercontent.com/5415177/134036405-857f8f46-20f8-4296-a2bc-9f930887624d.png)

1080p opengl renderer:
![openrct2_2021-09-20_19-10-36c50ddd026e870f108](https://user-images.githubusercontent.com/5415177/134036466-d7f681b5-fd4c-47bf-985e-cdfb2ccc6a5d.png)

Also which renderer are you using? For laptops it might better to stick to software rendering.

**Comment by TheClaudeQC** [comment]
i am on full screen (whiteout borders)

**Comment by TheClaudeQC** [comment]
i gonna link another video (a youtube one to really see the difference here)

**Comment by Broxzier** [comment]
What are your computer's specs? And do you have any plug-ins installed?

**Comment by TheClaudeQC** [comment]
> What are your computer's specs?

I have a Aspire 3, whit an intel core I3 10th gen, running on windows 11, (the bug was also recuring on windows 10).

>  And do you have any plug-ins instaled

I have, but those don't affect my fps, i still have the same fps whit i have none and when i have like 13 or something.

**Comment by TheClaudeQC** [comment]
ok, i don'T know what happened, but whit latest build, it get fixed somehow.
