### ISSUE TITLE
[NSF] Some .park saves won't load in latest merge (4f6af6f)

### ISSUE THREAD

**Issue by HookerHeels** [OpenRCT2/OpenRCT2#15443]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (4f6af6f on refs/pull/10664/merge) provided by GitHub

### Describe the issue

I have a park I have been working on for a while. I make saves as I go, and number them. I am currently on save 13.2.

The latest merge with the save format won't load past save 11.0.   Even 11.1, which adds 10 more small scenery and 3 more large scenery. (as to what pieces I added, damned if I know) won't load. I even removed the buildings and rides I placed down between v11.0 and v11.1, **_not the items from being selected_**, but no luck.  

In the last version of the new save format, **_0.3.3_** both 11.0 and 11.1-13.2 load just fine. I'm not a programmer, so I might be completely wrong, but my assumption is the new version either doesn't like the objects I added, or doesn't like the item count. (540 small to 550 small, 226 large to 229 large.)  I've zipped saves **11**, **11.1** and **11.1 removed additions ** Hope this helps.

https://www.mediafire.com/file/3m9x8fqq9qosg6u/ORCT2_save_issues.zip/file (link because it won't allow them to upload here?)

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Attempt to load latest save file.
2. Sends back to main menu,
3. ???

**Comment by Broxzier** [comment]
[Galaxia 11.zip](https://github.com/OpenRCT2/OpenRCT2/files/7194004/Galaxia.11.zip)
[Galaxia 11.1 removed additions.park.zip](https://github.com/OpenRCT2/OpenRCT2/files/7194006/Galaxia.11.1.removed.additions.park.zip)
[Galaxia 11.1.park.zip](https://github.com/OpenRCT2/OpenRCT2/files/7194007/Galaxia.11.1.park.zip)

**Comment by Gymnasiast** [comment]
As of `fad6adf809c816c8a84fb8ac6f4917b749dccbca`, this park appears to load again on the NSF branch. But attempting to load the first park did crash the game for me until I switched to OpenGL mode. That’s an issue in itself.

**Comment by Gymnasiast** [comment]
Also tried the other three - all of them load correctly (tested with 9eeb22da5e8bf57ffce37bb741dc5d2e4145087a).

**Comment by HookerHeels** [comment]
Indeed, fully working for me as well. Good job ORCT2 team.
