### ISSUE TITLE
Track already don't change

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#15467]
### Operating System

Windows10 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (1feac16 on develop) provided by GitHub

### Describe the issue

well, when changing whit another ride type whit the "allow arbritary ride track changes" cheat (when few track piece was placed, it dosen't change, keeping as the type they where

### Steps to reproduce

1. get any ride to build
2. build few track pieces
3. change the track type
4. all already placed track isn't changed (realoading a park fix it)

### Attachments

![image](https://user-images.githubusercontent.com/83843734/134847754-3576bf15-2b12-4a8f-a697-0ba252888dd0.png)

Giga coaster whit few LIM coaster track pieces

![image](https://user-images.githubusercontent.com/83843734/134847766-941bac95-6b1c-4708-bbb6-44951e74bc83.png)

LIM coaster station vs Looping coaster stating

![image](https://user-images.githubusercontent.com/83843734/134847784-eeb57267-a9cd-4a13-be88-64ced6d4d819.png)

LIM coaster station whit looping coaster tracks and single rail coaster inverting track

**Comment by duncanspumpkin** [comment]
Has already been fixed
