### ISSUE TITLE
Demolishing a $300 shop will refund you $1725.

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#1548]
![1](https://cloud.githubusercontent.com/assets/13048125/8511933/dbd0d5f6-235e-11e5-857d-ae85e1e487a9.jpg)
![2](https://cloud.githubusercontent.com/assets/13048125/8511932/dbc00e2e-235e-11e5-92de-acb199cc87cc.jpg)

build tested: b921, and I've reproduced the bug on various scenarios.

**Comment by duncanspumpkin** [comment]
Are you sure its not there to encourage healthier foods? 

I'll fix it shortly I think I know the cause.
