### ISSUE TITLE
When exporting SV6 to RCT2, map animations do not animate correctly

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#15487]
### Operating System

Ubuntu 20.04

### OpenRCT2 build

https://github.com/OpenRCT2/OpenRCT2/commit/cce3bb1845581182c6ad22b171d83006261a62a4

### Describe the issue

When opening an SV6 file created by OpenRCT2 in vanilla RCT2, the ride banners do not animate correctly. They get stuck. Most likely, this is due to map animations export not working correctly.

### Steps to reproduce

1. Save a park with at least one ride
2. Open this park in vanilla RCT2
3. Take a look at the ride banners

**Comment by Gymnasiast** [comment]
Sounds very likely - RCT2 just reads them from the save.

**Comment by duncanspumpkin** [comment]
Probably the height being wrong https://github.com/OpenRCT2/OpenRCT2/blob/e5f9282a36a612f8dde729b61579c4cb7fc3cf21/src/openrct2/rct2/S6Exporter.cpp#L1766
