### ISSUE TITLE
Game Crashes When Opening Scenario Editor

### ISSUE THREAD

**Issue by bkalish18** [OpenRCT2/OpenRCT2#15480]
### Operating System

Mac OS 15.17

### OpenRCT2 build

OpenRCT2,  (4f6af6f on HEAD)

### Describe the issue

Game crashes when opening scenario editor on Mac 

### Steps to reproduce

1. 
2. 
3.

**Comment by Gymnasiast** [comment]
1. This only happens on the new save format test build, which you did not mention.
2. It has already been fixed
