### ISSUE TITLE
Building track designs freezes the game

### ISSUE THREAD

**Issue by ipatix** [OpenRCT2/OpenRCT2#1552]
So there seems to be another heavy bug in the most recent dev-builds. When building track designs in the park, it'll make the game freeze with the following error message:
"ERROR[..\src\ride\track.c:4078 (track_remove)]: Track map element part not found"

I tested it with the following park and ride (although it seems to happen with other parks and rides too!):
https://dl.dropboxusercontent.com/u/28573353/OpenRCT2/Saves/Sandbox.sv6
https://dl.dropboxusercontent.com/u/28573353/RCT/Sandy%20Storm.TD6

**Comment by duncanspumpkin** [comment]
Which ride type is the track for just to save me searching.

**Comment by ipatix** [comment]
It's a wooden rollercoaster.

**Comment by duncanspumpkin** [comment]
Hmm this will take a little while to fix.
