### ISSUE TITLE
'Side Brace-style' Supports Incorrectly Treated as Scenery

### ISSUE THREAD

**Issue by avenged110** [OpenRCT2/OpenRCT2#15525]
I didn't see anything for this, but I'm very new to actively using this project, so please let me know if there are any issues or if you're already aware.

The 'side brace-style' supports (circled in screenshot) are treated as scenery instead of supports. i.e. Selecting "Invisible Supports" doesn't hide these pieces while selecting "See-through Scenery" does.

Using version 0.3.4.1 on a Windows 10 VM with an imported RCT1 project.

Side note: I've not been able to reproduce this issue, but on several occasions, deleting a ride did not remove these pieces, at least graphically. Placing a new ride was not obstructed by these vestigial structures, it just resulted in an overlapping graphical glitch which I didn't remember to get a screenshot of.

![Screen Shot 2021-10-03 at 1 30 30 AM](https://user-images.githubusercontent.com/19438529/135768588-13d72831-1d1f-4f8c-ab16-319b8a14d3d4.png)

**Comment by duncanspumpkin** [comment]
Those are scenery though not supports. Supports are purely the auto generated ones made by coasters.

**Comment by avenged110** [comment]
Please forgive my ignorance here, but what could be the purpose of that? Is that something that even can be corrected? (Assuming there was a desire to.) Because that feels like an issue.

**Comment by duncanspumpkin** [comment]
I could be wrong as i can't remember every flag but scenery doesn't have a flag indicating that it represents a type of support so we would have no way to know.

**Comment by avenged110** [comment]
Ok, fair enough. Just leave me on record hoping for a fix on the off-chance there ever ends up being a way to do so.

**Comment by duncanspumpkin** [comment]
It's pretty much impossible. Someone could go through and add a new flag to all vanilla objects (something we have done in the past for other features) but afaik most support objects were made by the community and we can't add extra info to them so they would display incorrectly.

**Comment by Gymnasiast** [comment]
The thing here is: they are scenery and purely decorative. You can remove them, add them in every place you want, etcetera. There really is nothing that makes them behave as something else than scenery. They are just there to provide the user with a way to make their coasters a bit more realistic.

**Comment by Gymnasiast** [comment]
Unrelated, but why are you running OpenRCT2 in a virtual machine? There is a native macOS version available.

**Comment by avenged110** [comment]
Because I exclusively use OS X 10.9 for which support was dropped around 0.2.4. And if it has to be virtualized anyway, (as much as I despise it) there seem to be fewer graphical glitches with Windows than OS X. That said, I haven't yet tested it with ORCT2 directly – something I plan to do in the future.

**Comment by ocalhoun6** [comment]
> Ok, fair enough. Just leave me on record hoping for a fix on the off-chance there ever ends up being a way to do so.

Just wanted to add: I'm really not sure it would even be desirable to 'fix' this.

Because while adding it to coaster supports is *one* use for this scenery object, lots of people also use it in actual scenery that has nothing to do with rides whatsoever.

Here's a park of mine that uses the same scenery object for purely scenery purposes, not as a coaster support at all:
![Tumbledown Faire 2021-10-03 15-48-17](https://user-images.githubusercontent.com/26573303/135774102-d35d9be3-5dd1-4b31-b550-c48639dccae0.png)

**Comment by avenged110** [comment]
> Because while adding it to coaster supports is _one_ use for this scenery object, lots of people also use it in actual scenery that has nothing to do with rides whatsoever.

Having only ever played RCT1, I don't remember ever having seen those pieces, so when I very recently moved my save to ORCT2, I legitimately had no idea that was a thing. This has been rather enlightening; thanks for sharing.

**Comment by Gymnasiast** [comment]
> Having only ever played RCT1, I don't remember ever having seen those pieces, so when I very recently moved my save to ORCT2, I legitimately had no idea that was a thing.

That makes sense, RCT1 did not provide a way for placing scenery in the air and used terrain for making buildings, so it didn’t have any construction-related scenery, only decorative.
