### ISSUE TITLE
Libduktape not found

### ISSUE THREAD

**Issue by sfisher923** [OpenRCT2/OpenRCT2#15522]
### Operating System

Linux Mint 20.2 Cinnamon 64 bit

### OpenRCT2 build

openrct2_0.3.4.1 "Nightly" on Launchpad

### Describe the issue

Not sure If i'm doing things wrong or what (Just got Linux 6 hours ago)

I'm getting "openrct2: error while loading shared libraries: libduktape.so.205: cannot open shared object file: No such file or directory" after using "sudo add-apt-repository ppa:openrct2/nightly" and running OpenRCT2 as root

### Area(s) with issue?

Building the game

### Steps to reproduce

1. Run Terminal as Root
2. sudo add-apt-repository ppa:openrct2/nightly
3. 
![Screenshot from 2021-10-03 02-42-42](https://user-images.githubusercontent.com/80093217/135743156-a62478e5-a886-4a5f-bea5-0f3ef9f4ee47.png)

(Also Yes my user name was your due to a 2 day struggle with this laptop)

**Comment by sfisher923** [comment]
Solved

**Comment by Gymnasiast** [comment]
It might help others if you say how.

**Comment by sfisher923** [comment]
In terminal

sudo apt-get install libduktape205

Enter the root password

**Comment by Gymnasiast** [comment]
Hm, that should automatically be installed if you install openrct2 from Launchpad. I’ll have to check why it doesn’t do that.

**Comment by Gymnasiast** [comment]
The launchpad build does list libduktape205 as a dependency (which will get it installed automatically), so I wonder whether you actually installed the PPA version, or whether you simply used a .tar.gz build. Considering you’re new to Linux, I think it’s the latter. As such, I’ll consider the issue solved.

If you have any more problems, you can always ask us on Discord.
