### ISSUE TITLE
Deleting stalls refunds more money than it should

### ISSUE THREAD

**Issue by ipatix** [OpenRCT2/OpenRCT2#1553]
Currently, tearing down various stalls refunds more money (> $1000) than it should.
Here is an example with a restroom:

![scr10](https://cloud.githubusercontent.com/assets/8502545/8512732/cfa8e272-2350-11e5-9ab2-27df96167c52.png)

**Comment by duncanspumpkin** [comment]
Are you running the very latest build. I fixed the issue to do with stall prices earlier today.

**Comment by ipatix** [comment]
Mhm, weird, I though I'd run the latest version. I'll recompile the latest one myself rather then using the openrct.net launcher.

**Comment by ipatix** [comment]
Yup, just checked it and it's fixed now ;)
Think this issue can be closed then.
