### ISSUE TITLE
Improve wiki documentation

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#1555]
There have been quite a few people on reddit and such asking the same questions. Someone needs to write a step by step process for accessing the cheats, developer tools, object_selection and whatever else we implement.

**Comment by Phasedetect** [comment]
I'm going to search the subreddits and gitter for old questions, but if there are any that specifically jump to mind as needing to be addressed, let me know.

**Comment by Phasedetect** [comment]
The cheats page (where I think most of the problems lie) has been made [here](https://github.com/OpenRCT2/OpenRCT2/wiki/Cheats-Menu).

**Comment by LRFLEW** [comment]
I slightly edited the cheats wiki page to improve the description of the EXPLODE!!! cheat.

**Comment by Phasedetect** [comment]
[Console](https://github.com/OpenRCT2/OpenRCT2/wiki/Console) and [Sandbox Mode](https://github.com/OpenRCT2/OpenRCT2/wiki/Sandbox-Mode) have been added. The former needs completing of commands I didn't know the use of.

**Comment by duncanspumpkin** [comment]
Can we add a step by step process with pictures for how to enable developer tools and also the cheats window button.

**Comment by Phasedetect** [comment]
[FAQ & Common Issues](https://github.com/OpenRCT2/OpenRCT2/wiki/FAQ-&-Common-Issues) Started and [Console Documentation](https://github.com/OpenRCT2/OpenRCT2/wiki/Console) improved.
