### ISSUE TITLE
Clear Tool issues

### ISSUE THREAD

**Issue by sta5is** [OpenRCT2/OpenRCT2#15585]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (c04249f on develop)

### Describe the issue

The Clear tool as of c04249f looks like this:
![clear tool 1](https://user-images.githubusercontent.com/26368692/137574416-fb2828b7-9d13-4b44-b941-4f715cd814d3.PNG)

Here's how it looks previously:
![clear tool 2](https://user-images.githubusercontent.com/26368692/137574420-cdd2f19f-b7c4-4c37-9c54-ca72430b5132.PNG)

The issues are as follow:
- The window spawns on the left side of the screen instead of the right side
- The size selection widget displays a size of -1 (the original "mountain tool") instead of the usual 2
- The small scenery selection is not pressed by default (but functions as if it is selected)

### Steps to reproduce

1. Click on the clear tool

**Comment by duncanspumpkin** [comment]
Regression from https://github.com/OpenRCT2/OpenRCT2/pull/15481
