### ISSUE TITLE
Mixed ride entrance/exit/station styles

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#15597]
### Describe the feature

This requires the New Save Format.

Currently, a ride can only have one style which affects the appearance of all its stations, entrances and exits: `Ride::entrance_style`.

It would be nicer to have the tile elements themselves state which style they have instead of storing one style per ride. That way you can have more interesting designs with for example a canvas entrance, abstract exit, and a space station.

### Feature type

Quality of life

**Comment by James103** [comment]
> Ah, so you wouldn't be able to mix and match station styles within the same station then, right? (Like having half the station space themed and then the second half abstract themed.) That's the part that was really boggling me as to how you'd make a user-friendly UI for it.

Would you still be able to do that with the Tile Inspector though? For example, you could use the Tile Inspector to set the station style of the 1st through 4th tiles of the 3rd station to a different style (such as Space), whereas the rest of the station is Abstract style.

**Comment by duncanspumpkin** [comment]
No we have already used up all the space.

**Comment by IntelOrca** [comment]
Does ride type need to be two bytes? We haven't even used half of the available numbers yet.

**Comment by duncanspumpkin** [comment]
> Entrance style can also easily fit in one byte.
> 
> I find it a little concerning that data is so limited or not flexible enough to add more. I guess that the data of each element still has to have the same size. In that case, data that gets frequently used should be part of the element, and other data could be stored elsewhere, fetched by some unique ID that the elements then have when needed (much like components in ECS).

Yes that is what i think we will need to do. Move anything that is for drawing (i.e. not required for logic and accessed super often) to a separate component much like we have with banners.

And no ride type doesnt atm need to be 2 bytes it was done like that for potential future projects.
