### ISSUE TITLE
Cannot relocate a shop properly

### ISSUE THREAD

**Issue by andy55699** [OpenRCT2/OpenRCT2#15602]
### Operating System

Windows 10,64-bit

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (eba2041 on develop) 

### Describe the issue

I encounter a bug when rebuilding/relocateing a stall/shop. The stall/shop cannot be demolished in the first step and I can only choose a new location to build the stall. However the original shop stays. Therefore 2 identical shops are built. When I demolish the new shop, the old shop is also demolished.

### Area(s) with issue?

Building the game

### Steps to reproduce

1. Build a stall/shop
2. Rebuild/relocate the stall/shop

![1](https://user-images.githubusercontent.com/92691705/137642893-42c10f77-7638-4b31-8e1e-eeac67314944.png)
![2](https://user-images.githubusercontent.com/92691705/137642896-73836e71-2f06-46c4-aa67-ea83423abe8a.png)
![3](https://user-images.githubusercontent.com/92691705/137642897-536985ef-e55b-44a6-8462-67175520e1aa.png)
![4](https://user-images.githubusercontent.com/92691705/137642899-97e04625-3bc0-4352-acd2-7be0d6b2c726.png)
![5](https://user-images.githubusercontent.com/92691705/137642901-333d3ecb-7deb-4f78-aca5-06596123275b.png)
![6](https://user-images.githubusercontent.com/92691705/137642902-bbee4943-0386-48fb-aa15-9d23d66a5671.png)

### Attachments

1. Build a stall.
2. Relocate the stall

Please find the saved file of the park here. Thank you!
[Shop bug.zip](https://github.com/OpenRCT2/OpenRCT2/files/7360768/Shop.bug.zip)
.

**Comment by andy55699** [comment]
How do I upload the saved file of the park? The file type of it is not supported here in the textbox.

**Comment by duncanspumpkin** [comment]
just change the extension to .txt or something else or zip it.

**Comment by Gymnasiast** [comment]
@seanmajorpayne Have you been able to take a look/find something yet? If you need longer, I might revert your commit for the v0.3.5 release, so we can ship it.

**Comment by seanmajorpayne** [comment]
I started a new job this week, so probably can't touch this until this
weekend.

**Comment by Gymnasiast** [comment]
@seanmajorpayne Ok, no worries. Since I plan to release v0.3.5 on Saturday, I will just revert your change for the release. Would be wonderful if you have time this weekend, but no harm done if you don’t.

**Comment by Gymnasiast** [comment]
I might just have a proper fix. Stay tuned.

**Comment by andy55699** [comment]
Dankjewel Michael!
