### ISSUE TITLE
Adding a "Give Money to Guests" cheat.

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#1567]
I found that the original RCT game did not contain an ATM. Therefore, playing some Vanilla RCT scenarios is frustrating, especially when the guests saying that they are running out of cash, and roaming through the paths until they leave the park. I don't want to open sandbox mode to add the ATMs, would it be a good cheat to add it into the cheats window?

**Comment by IntelOrca** [comment]
You can use the object selection window in the game. However currently it forces everything to be invented and isn't completely stable yet.

**Comment by Gymnasiast** [comment]
Adding a cheat to give guests a load of money is on my list.

**Comment by Horsti12** [comment]
But the problem with the object selection is that it will give you everything which is selected, even the things which you have to research.

**Comment by Gymnasiast** [comment]
IntelOrca already said that. Also, the ATM was only a remark, he only asked for a cheat.
