### ISSUE TITLE
Make cheats window layout more user-friendly

### ISSUE THREAD

**Issue by Phasedetect** [OpenRCT2/OpenRCT2#1568]
The cheats window, and in particular the guest tab, could be better organized. Right now, the buttons at the bottom of that tab, starting with "Give all guests:" is confusing, as is the "Preferred intensity" button. The park cheats could also use a layout cleaning to keep them intuitive. If needed, I can make a mockup of ideas.

**Comment by Phasedetect** [comment]
Also, the buttons should either be in title caps or they should only have the first letter of the first word capitalized, but not both like we have now.

**Comment by Gymnasiast** [comment]
Ride intensity and how guests react to it is one of most basic RCT mechanics there is. If you don't understand it, the Preferred Intensity buttons may be confusing. The Cheats window expects the user to know the basic game mechanics he/she wants to influence using a cheat.

**Comment by austinjb555** [comment]
The current options for preferred intensity are <15 and >1. I think this is confusing to everyone...
![scr4](https://cloud.githubusercontent.com/assets/12687508/8586849/a0be2f30-25c1-11e5-97a5-b93813d91aa2.png)

**Comment by Gymnasiast** [comment]
\*sigh\* It is confusing if you don't understand the most basic game mechanic. The cheat window is intended for people who have at least a vague idea of they are doing.

But fine, I'll look into the descriptions and some other things.
@IntelOrca or @duncanspumpkin , could one you assign this bug to me?

**Comment by duncanspumpkin** [comment]
@Gymnasiast the assignment feature of github doesn't work too good (I can't assign you for example only members of the repo). But I'll merge your change when needed.
