### ISSUE TITLE
Lots of Artifacting when You use drag-to-top method of maximizing

### ISSUE THREAD

**Issue by thyeggman** [OpenRCT2/OpenRCT2#1572]
Here's an image of what I saw:

http://imgur.com/xjiRa5P

It happened only when I used the drag-to-top method of mazimizing.  I'm on windows 8.

**Comment by IntelOrca** [comment]
Do you have uncapped FPS on?

**Comment by zsilencer** [comment]
Can you try the latest version now and see if this is still happening

**Comment by IntelOrca** [comment]
I still get this when I right-click drag the map around with uncapped FPS on. It is because I now update the viewport positions in the main game loop to fix the issue with viewports that follow sprites.

**Comment by zsilencer** [comment]
Can you try testing this one, let me know if there are still any issues

**Comment by IntelOrca** [comment]
@zsilencer That fixes it.

**Comment by thyeggman** [comment]
Thanks for the fix, I will take a look at it this evening.  Didn't have a
chance today to test it out.
