### ISSUE TITLE
Queue line building issues

### ISSUE THREAD

**Issue by austinjb555** [OpenRCT2/OpenRCT2#1573]
When building a queue line from an entrance, I can't build up a slope because the overhead sign stays at the bottom and the rest of the path is just regular (but queue style) pathway. 
![scr3](https://cloud.githubusercontent.com/assets/12687508/8586759/a4786664-25c0-11e5-960a-a07d2ae8cb35.png)

**Comment by duncanspumpkin** [comment]
Can someone confirm if this is still happening after the https://github.com/OpenRCT2/OpenRCT2/commit/7377de004976137def827d93b15c7acf49e95984 fix?

**Comment by daihakken** [comment]
Fixed proof:
![capture](https://cloud.githubusercontent.com/assets/13048125/8618247/d13e4888-273e-11e5-807f-f97de3396617.PNG)
build tested: b953 from OpenRCT2.com
