### ISSUE TITLE
"Station not long enough" while it can be opened and tested in vanilla game.

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#1575]
![NotlongEnough](https://cloud.githubusercontent.com/assets/13048125/8587523/d2964fec-262f-11e5-9f2e-e8f959036a68.PNG)

**Comment by runelaenen** [comment]
@daihakken I can't reproduce the bug. Which scenario are you playing? Could you maybe upload a save-file?

**Comment by duncanspumpkin** [comment]
@runelaenen the code for doing station length for chair lifts is something i worked on, on the weekend. I should be able to work out the issue.

**Comment by runelaenen** [comment]
Ah okay

**Comment by duncanspumpkin** [comment]
I've tried a few different layouts and I can't work out whats happening can you provide a save.

**Comment by chrismilne300** [comment]
Easy way to reproduce the bug is starting new game in Rainbow Summit close chair lift  1 and try to reopen it.

**Comment by daihakken** [comment]
Close and reopen existing chairlifts will reproduce this bug.
