### ISSUE TITLE
RCT1 paths are very glitchy if RCT1 is not linked

### ISSUE THREAD

**Issue by daand12** [OpenRCT2/OpenRCT2#15830]
### Operating System

WIndows 11 Home x64

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (0c9511c on refs/pull/10664/merge) provided by GitHub

### Describe the issue

When trying to create a waiting line for rides, it glitches out and showing something different.

Haven't tried it out with the regular version of OpenRCT2, this version is the test build.

Have confirmed this glitch on my Desktop with Windows 10 Pro x64 and my laptop using Windows 11 Home x64

### Area(s) with issue?

Building the game

### Steps to reproduce

1.  Create new map with the Test Build version ( New save file format )
2. Create a ride and try to create a new Que path for guests
2. 
3. 

### Attachments

![Naamloos](https://user-images.githubusercontent.com/36038914/139557464-148c92f3-1df6-4e82-990b-a49195663b5e.png)

**Comment by Gymnasiast** [comment]
Most likely, you selected a path from RCT1 without having linked OpenRCT2 to RCT1. Can you check the source game of the selected queue?

**Comment by Gymnasiast** [comment]
Speaking with the OP via Discord DMs, I established it is indeed caused by accidentally checking the RCT1 blue queue.

It does beg the question: should we have a fallback mechanism for users without RCT1?

**Comment by ZehMatt** [comment]
> It does beg the question: should we have a fallback mechanism for users without RCT1?

Its better than having something weird show up in my opinion.

**Comment by Gymnasiast** [comment]
I guess we should implement that mechanism during object load, rather than having it do it while drawing? (Am I right in assuming that the latter would be bad for performance?)

**Comment by ZehMatt** [comment]
We can probably check during the placement if the surface/railings object needs to use a substitute.

**Comment by ocalhoun6** [comment]
Maybe there should be some kind of warning pop-up when you first load a scenario that includes RCT1 objects and you don't have RCT1 linked? (Maybe even with a button that will take them to the options menu to link RCT1, for convenience and to help people who might not be sure how.) Or at least a generic 'This scenario contains objects that were not found on your device, which could lead to missing scenery, paths, or rides in your landscape. Load scenario anyway?' kind of message.

A fallback option is also good to have (as opposed to just refusing to load the scenario) but I think some kid of warning message might be good, so people will know why the path they're building doesn't look *quite* like the one they selected to build.

**Comment by duncanspumpkin** [comment]
The fallback for every other object is that it doesn't display anything. The same should apply here. The vast majority of players won't have rct1 linked so it should really have additional warnings around it though.

**Comment by Gymnasiast** [comment]
This has since been fixed.
