### ISSUE TITLE
Track Design Manager crashes game after clicking "Select another ride"

### ISSUE THREAD

**Issue by sta5is** [OpenRCT2/OpenRCT2#15831]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (0e892e9 on develop) provided by GitHub

### Describe the issue

In the Track Design Manager, after making a ride selection, clicking on "Select another ride" closes the game without displaying any error messages.

### Steps to reproduce

1. Go to Track Design Manager under the Toolbox in the main menu
2. Select any ride
3. Click on "Select another ride" button located at the top of the window

**Comment by Gymnasiast** [comment]
Ah, that may explain some of the crash reports we were getting!

The fix is simple: this button should not be there in the Track Designs Manager, so it just needs a couple of lines of code to disable it.

**Comment by Lucius6** [comment]
It also happens when clicking on the x to close the ride desing viewer window.

**Comment by Gymnasiast** [comment]
@Lucius6 That issue was already reported earlier. No matter though, I have PRs outstanding to fix both of them.
