### ISSUE TITLE
Tile Inspector inconsistent text colour

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#15844]
### Operating System

Windows 10 x64

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (af78bbb on develop) provided by GitHub

### Describe the issue

This bug is mostly noticeable using a custom theme where the secondary colour is set to something dark.

### Steps to reproduce

1. Open the tile inspector
2. Select a couple different element
3. Observe how the text colour of some of the details and properties is coloured differently

### Attachments

![image](https://user-images.githubusercontent.com/9705046/139748436-a67d3c1f-2a68-4675-b702-7fb7b93a6b08.png)

**Comment by chrhaase** [comment]
Hi, I'd like to look at this bug!

**Comment by tupaschoal** [comment]
Alright
