### ISSUE TITLE
Scenario objectives only allow a maximum of 5000 guests.

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#15849]
For NSF we should probably either uncap the limit or have it to a fixed percentage of maximum entities. 5k is 50% for the current entity limit.

https://github.com/OpenRCT2/OpenRCT2/blob/8158956f18af5ab729ef804c5a8c44b60be8f99b/src/openrct2-ui/windows/EditorObjectiveOptions.cpp#L506

**Comment by Gymnasiast** [comment]
Sure, we should increase it at some point, although I disagree it should be on the milestone. There is enough scope creep with the NSF as it is and it can easily be done later on.

Also note that the limit of 5000 is not an SV6 limit, but an interface limitation - vanilla RCT2 can also handle higher limits.
