### ISSUE TITLE
Crash to desktop loading certain save files

### ISSUE THREAD

**Issue by ToffeeSurprise** [OpenRCT2/OpenRCT2#15847]
### Operating System

Windows 10 x64

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (0c9511c on refs/pull/10664/merge), Win 10 x86-64

### Describe the issue

Loading the attached save file results in a crash to desktop in latest OpenRCT2 save format dev build. Unsure exactly what build this started occurring, but I have loaded the file successfully in OpenRCT2 previously. Possible issue with custom scenery in latest builds?

### Steps to reproduce

1. Attempt to load attached save file from Mike Robbins (Swiss Alpine Village Resort)
2. This will result in an exception and crash to desktop

100% repo.

### Attachments

[Swiss Alpine Village Resort -  Mike Robbins.zip](https://github.com/OpenRCT2/OpenRCT2/files/7462512/Swiss.Alpine.Village.Resort.-.Mike.Robbins.zip)

**Comment by Gymnasiast** [comment]
We need a commit/build, I’m afraid. Also, there is no such version as v0.4.3 (yet).

**Comment by ToffeeSurprise** [comment]
Apologies, version is 0.3.4.1.

Specifically the game identifies it as:

OpenRCT2, v0.3.4.1 (0c9511c on refs/pull/10664/merge), Win 10 x86-64

Hope that's sufficient?

**Comment by Gymnasiast** [comment]
Yeah, that’s what I needed, could you update the first post with that information?

**Comment by ToffeeSurprise** [comment]
Done, thanks for confirming and apologies again for missing that out first time.

**Comment by Gymnasiast** [comment]
Irritatingly, it only appears to crash when _not_ loading it via a debugger :-/

**Comment by IntelOrca** [comment]
fixed
