### ISSUE TITLE
Joanne Barton and Emma Garrell name cheats only work partially

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#15858]
### Operating System

Windows 10 64 bit

### OpenRCT2 build

efa40b1

### Describe the issue

A guest named Joanne Barton is supposed to get pizza and give guests are her pizza and a guest named Emma Garrell is supposed to get purple clothes and give guests are her purple clothes.

In both cases they do give the effect to guests around them, but they don't get the effect themselves.

### Steps to reproduce

1. 
2. 
3.

**Comment by duncanspumpkin** [comment]
Just checking the assembly against this and the following cheats should apply to themselves:
PEEP_FLAGS_PURPLE, PEEP_FLAGS_PIZZA
And the following should not apply to themselves:
PEEP_FLAGS_CONTAGIOUS, PEEP_FLAGS_ICE_CREAM
