### ISSUE TITLE
Placing a Flat Ride and demolishing it without placing the Entrance/Exit makes it impossible to place the ride

### ISSUE THREAD

**Issue by Derpercoaster** [OpenRCT2/OpenRCT2#15853]
### Operating System

Windows 10, 64 Bit

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (5087e77) provided by GitHub

### Describe the issue

If you place a flat ride and demolish it before placing the entrance and exit, the ride placement indicator (the white grid) shows the wrong size, and you can't place anything You have to close the ride placement window and open a new one to properly start over.

### Steps to reproduce

1. Place any flat ride (do not place the exit or entrance)
2. Demolish the ride but keep the window open.
3. Try to place the ride again. The mouse will show the incorrect size of the ride's footprint and won't let anything be placed.

### Attachments

![Forest Frontiers 2021-11-03 16-31-43](https://user-images.githubusercontent.com/60452987/140195914-bb9ed6f7-d2b0-4bd0-bf8d-63d253ca1a91.png)
**Ride built**

![Forest Frontiers 2021-11-03 16-31-48](https://user-images.githubusercontent.com/60452987/140195917-7417e05c-59ef-41a3-a87b-3eaf83b0e77f.png)
**Ride being demolished**

![Forest Frontiers 2021-11-03 16-31-51](https://user-images.githubusercontent.com/60452987/140195918-ee9bf099-e6e1-4564-963b-53d989350a94.png)
**Attempting to place ride after demolishing it. The mouse shows the incorrect size and refuses to place anything**

**Comment by Gymnasiast** [comment]
Has been fixed weeks ago. Please test with a recent `develop` version, not a 3 month old release version.
