### ISSUE TITLE
Guest name easter egg "Katie Smith" doesn't work

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#15851]
### Operating System

Windows 10 64 bit

### OpenRCT2 build

8b724cd

### Describe the issue

A guest named "Katie Smith" is supposed to frequently jump, but it seems to have no effect. It works fine in vanilla.

### Steps to reproduce

1. 
2. 
3.

**Comment by duncanspumpkin** [comment]
The code for it is all there. Not sure why it wouldn't work. Your labelling a peep that is free pathing and not currently busy performing another action?

**Comment by LordMarcel** [comment]
I have named several guests in several different parks, even an empty one. I've also tried restarting the game and it hasn't worked a single time.

When I tried it in Classic the guest starting jumping immediately so it is basically impossible to miss it.
