### ISSUE TITLE
Trying to build anything causes CTD

### ISSUE THREAD

**Issue by austinjb555** [OpenRCT2/OpenRCT2#1586]
Build 951, Windows 7. I can't build anything in any park.

**Comment by daihakken** [comment]
can confirm this, same build, Windows 10 build 10159.

**Comment by PFCKrutonium** [comment]
@daihakken Your a couple builds behind mate - 10166 is out.

**Comment by daihakken** [comment]
I was referring to OP - same game build, different windows, which can show that it is not an OS-depend bug.

**Comment by PFCKrutonium** [comment]
Ah, good point. I completely missed that XD

**Comment by daihakken** [comment]
The problem seems to be fixed @ the latest build, thanks @IntelOrca !
