### ISSUE TITLE
JJ instead of LL

### ISSUE THREAD

**Issue by x7ype** [OpenRCT2/OpenRCT2#15863]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

v0.3.5 “MY - BRAIN - HURTS!”

### Describe the issue

The L letters have become Js. 

### Steps to reproduce

1. Start game
2. All letters L are J now
3. 

### Attachments

![bubmjy](https://user-images.githubusercontent.com/73121822/140608817-3194d05d-86da-4ad3-811b-a22278e95195.jpg)

**Comment by duncanspumpkin** [comment]
Your g2.dat is out of date. Fix that and your letters will be fixed.
