### ISSUE TITLE
macOS arm64 release build for v0.3.5 incorrectly codesigned

### ISSUE THREAD

**Issue by dshusta** [OpenRCT2/OpenRCT2#15879]
### Operating System

macOS Monterey 12.0.1 on an 2021 M1 Mac Mini

### OpenRCT2 build

OpenRCT2, v0.3.5 (b9bc8d0 on HEAD)

### Describe the issue

On the OpenRCT2 releases page https://openrct2.org/downloads/releases/latest, the `OpenRCT2-0.3.5-macos-arm.zip` build contains an application with a malformed codesignature. This causes macOS Gatekeeper to refuse to open it no matter what.

This is not the same as the typical dialog for _unsigned_ applications. It's somehow is a situation where the app was signed with some signature and then the contents were modified (violating the signature).

|Opening Universal Binary or Intel application by double click (works as expected) |Opening Universal Binary or Intel application by right-click -> Open (works as expected) |Opening arm64 application|
|-|-|-|
|![Developer cannot be verified](https://user-images.githubusercontent.com/5932868/140802025-546d729b-6a2a-4065-a50d-71dd709feab3.png)|![Are you sure you want to open?](https://user-images.githubusercontent.com/5932868/140802028-5b764e31-ae0e-4dbf-921c-dc7a39d7e1c1.png)|![Damaged and cannot be opened](https://user-images.githubusercontent.com/5932868/140802261-837b609b-f6c3-4051-9f86-db1b5e421d6e.png)|

The sha256 for my downloaded file matches that listed on the [releases page](https://openrct2.org/downloads/releases/latest).
```
➜ shasum -a 256 OpenRCT2-0.3.5-macos-arm.zip
a6238e8a4061af8f3a368e7647170af570fd488656c91381d892b0f506f70e13  OpenRCT2-0.3.5-macos-arm.zip
```
The codesign verification notes `code or signature have been modified` for only the arm build.
```
➜ codesign -d --verify --verbose=4 OpenRCT2\ x86.app
OpenRCT2 x86.app: code object is not signed at all
In architecture: x86_64

➜ codesign -d --verify --verbose=4 OpenRCT2\ arm.app
OpenRCT2 arm.app: invalid signature (code or signature have been modified)
In architecture: arm64

➜ codesign -d --verify --verbose=4 OpenRCT2\ universal.app 
OpenRCT2 universal.app: code object is not signed at all
```

### Aside about dev build
Building locally from `b9bc8d0` works fine, at least following the [wiki instructions](https://github.com/OpenRCT2/OpenRCT2/wiki/Building-OpenRCT2-on-macOS-using-CMake#building-openrct2) (using MacOS Monterey 12.0.1 with Xcode 13.1)

```
➜  build git:(b9bc8d060) codesign -d --verify --verbose=4 OpenRCT2.app
OpenRCT2.app: code has no resources but signature indicates they must be present
```
It builds an arm64 non-universal build that doesn't prompt for macOS GateKeeper. Weird.

## Proposed solution:
Anyway I think the most straightforward approach would be to **only offer the universal build and not offer the arm64-specific app** on the releases page. OpenRCT2.app is almost entirely assets and so the filesize savings for having an architecture-specific binary slice are pretty negligible. 

I think I saw in some thread there was a concern about minimum supported macos version for a universal build that necessitates continuing to offer a x86 build. If this isn't a concern anymore then no need to offer the x86 build either.

### Codesigning what

I've been poking around the build system scripts and the [ci build log](https://github.com/OpenRCT2/OpenRCT2/runs/4125518596) trying to investigate why the arm64 build would be malformed at all. I'm not seeing anything obvious, although this stuff is not really my skillset. If someone knows offhand where specifically to investigate, I might be able to take up taking a look, if decision really is to offer a arm64-specific build.

### 3.5.0 runs real good on Apple Silicon
Just as an aside, I want to **thank all the devs** who put in this work to support Apple Silicon on MacOS 👏  🎊 . Playing around with it, it really does seem like it's showing a ~60% performance improvement compared with running the app in x86 Rosetta mode. Good job!

### Area(s) with issue?

Building the game

### Steps to reproduce

1. Download `OpenRCT2-0.3.5-macos-arm.zip` from [latest releases](https://openrct2.org/downloads/releases/latest)
2. Unzip and attempt to open

Expected:
1. idealistic best case: opens automatically with macOS Gatekeeper approval (this sounds like a can of worms with GPL licensing, and is way out of scope of this ticket)
2. Realistic case: warning about unknown developer, requiring `right click -> Open` to open, as it's been in the past.

**Comment by Gymnasiast** [comment]
Summoning @adam-bloom .

**Comment by Gymnasiast** [comment]
If the universal build works fine, we can indeed just drop the arm build. I wasn’t quite sure as I don’t have anything to test it on, so I added all three to the release.

**Comment by adam-bloom** [comment]
Well…that’s…odd. None of these are signed, but the standalone arm64 build is not different in any way that it should report invalid signature. @Gymnasiast i think the official release should only be the universal build. That’s the official artifact. The platform specific builds are intermediate artifacts used in the universal build step, so they do need to exist in CI.

@dshusta glad to hear about the performance gains!

**Comment by Gymnasiast** [comment]
OK, I removed the ARM build. I did leave the x86 build up, if only because it might be linked to by openrct2.io (which we control) and openrct2.org (which we don’t, at least not directly). I will have to sort that out, but at last that one works.

> : opens automatically with macOS Gatekeeper approval (this sounds like a can of worms with GPL licensing, and is way out of scope of this ticket)

I don’t see why it would violate the GPL, unless I have missed something. For us, the biggest reason is not wanting to spend a considerable sum of money on a certificate from Apple to get the app signed and notarised. If there is a way to do this for free I would be all ears.

**Comment by dshusta** [comment]
The arm64 code signing thing _might_ be related to https://mjtsai.com/blog/2020/08/19/apple-silicon-macs-to-require-signed-code/ (although I would think that would also apply to universal builds…)

With the arm build, it seems like I can apply a [generic `ad hoc` codesign](https://eclecticlight.co/2019/01/17/code-signing-for-the-concerned-3-signing-an-app/) to the app with `codesign --force --deep -s - OpenRCT2\ arm.app` — doing this allows it to open with the `Right Click -> Open` approach. 
It uh, has a warning at launch `Unable to load g2.dat` and random image assets are missing… it's weird.

Anyway the universal build is likely the right approach anyway.

---

The GPL stuff is way above my pay grade, and having a hard time finding an authoritative answer one way or another. There's something murmuring about how apple's notarization restricts the distribution of the software in a license-violating way, but other murmuring seems to be unconcerned about that. 

The $100 annual fee is a genuine annoyance. And I don't know how y'all self-organize but you'd sorta need to have one person make an apple id and signing certs and keep them secret (?) or something (?). I'm sure you've put much more thought into it. Hope that someday Apple makes this less silly.

**Comment by adam-bloom** [comment]
The arm64 build does not currently have a g2.dat, so it’s not usable on its own. The reason for that is that you need to be able to run an executable to build that, and our CI agents are Intel. Since the goal was universal build anyways, I didn’t worry about it…but all the more reason to remove that release. If you build locally on arm64, it should handle g2.dat though (unless cmake is being invoked with rosetta).

**Comment by dshusta** [comment]
Alright, since the build is removed and no one can accidentally download a non-functional release, I'll close the ticket

**Comment by akcorp2003** [comment]
Curious to know if there are plans to support Apple Silicon in the future?

**Comment by adam-bloom** [comment]
> Curious to know if there are plans to support Apple Silicon in the future?

@akcorp2003 it is currently supported! Via the macOS universal build artifact (which should now be the default macOS release if downloading from the website). This issue was just due to come confusion over which build artifact should have been released.

**Comment by akcorp2003** [comment]
> > Curious to know if there are plans to support Apple Silicon in the future?
> 
> @akcorp2003 it is currently supported! Via the macOS universal build artifact (which should now be the default macOS release if downloading from the website). This issue was just due to come confusion over which build artifact should have 

Oh cool! Do we know that the performance gains on a Universal build are pretty similar to what @dshusta described?been released.
