### ISSUE TITLE
Ride rating bug

### ISSUE THREAD

**Issue by windflower0212** [OpenRCT2/OpenRCT2#15881]
### Operating System

window 10 64 bit

### OpenRCT2 build

OpenRCT2, v0.3.5 (b9bc8d0) provided by GitHub

### Describe the issue

after update 0.3.5, ride rating don't come out (after test, after open)
![FREE PARK 2021-11-10 03-34-17](https://user-images.githubusercontent.com/94009974/140984852-b178069e-e0b9-4e1d-a5d5-c68e944c80b4.png)
![FREE PARK 2021-11-10 03-34-32](https://user-images.githubusercontent.com/94009974/140984861-c680142e-13f1-47db-9980-fb0bfdb4cf4a.png)

### Area(s) with issue?

Building the game

### Steps to reproduce

1. 
2. 
3. 
![FREE PARK 2021-11-10 03-34-17](https://user-images.githubusercontent.com/94009974/140984789-8e3bed2a-4235-4ba1-8ca9-5ff163b4ee15.png)
![FREE PARK 2021-11-10 03-34-32](https://user-images.githubusercontent.com/94009974/140984795-0a041cdf-d47f-4a3b-8efc-7ac0559d29f0.png)

### Attachments

![FREE PARK 2021-11-10 03-34-17](https://user-images.githubusercontent.com/94009974/140984027-4ce944bc-91a0-43df-b523-5fd4397f5dd1.png)
![FREE PARK 2021-11-10 03-34-32](https://user-images.githubusercontent.com/94009974/140984029-a348d818-df23-46ca-ba12-71a67d9171a0.png)

**Comment by duncanspumpkin** [comment]
Do you have an uncompleted track. Ride ratings stop calculating if any track with an incomplete track is awaiting ratings
