### ISSUE TITLE
All scenery groups are missing when loading this save on NSF

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#15882]
### Operating System

Ubuntu 20.04

### OpenRCT2 build

OpenRCT2, v0.3.5-14 (9e5e3ea68 on new-save-format, DEBUG)

### Describe the issue

All scenery groups are missing if you open this scenario on the NSF branch. It works correctly on develop.

Develop:
![afbeelding](https://user-images.githubusercontent.com/1478678/141003377-8825825e-aae0-47d7-9be9-9717923b59a3.png)

NSF:
![afbeelding](https://user-images.githubusercontent.com/1478678/141003285-05f40a04-345c-4539-965f-4b1f3ac88e4b.png)

### Steps to reproduce

1. Open the attached scenario
2. Open the Theming window

### Attachments

[De Efteling 2004.SC6.zip](https://github.com/OpenRCT2/OpenRCT2/files/7507937/De.Efteling.2004.SC6.zip)

**Comment by Gymnasiast** [comment]
Using cheats, it seems that all scenery groups are set as uninvented - enabling the "Ignore research status" cheat makes them show up.

**Comment by duncanspumpkin** [comment]
Fixed in a0e787a
