### ISSUE TITLE
Graphic glitches on FreeBSD make the game unusable

### ISSUE THREAD

**Issue by pkubaj** [OpenRCT2/OpenRCT2#15894]
### Operating System

FreeBSD, amd64

### OpenRCT2 build

OpenRCT2, v0.3.5

### Describe the issue

The game starts, but there are severe glitches that make the game unusable. Object files are not found (even though they are present) and moving windows causes another glitches.

Console output:
pkubaj@KGPE-D16:$~$ openrct2
Importing legacy shortcuts...
[PATHASH ] Object not found.
[TARMACB ] Object not found.
[PATHCRZY] Object not found.
[PATHDIRT] Object not found.
[TARMACG ] Object not found.
[PATHSPCE] Object not found.
[TARMAC  ] Object not found.
  PATHASH not found
  TARMACB not found
  PATHCRZY not found
  PATHDIRT not found
  TARMACG not found
  PATHSPCE not found
  TARMAC not found
openrct2 $ __cxa_thread_call_dtors: dtr 0x3c2340 from unloaded dso, skipping
                                                                            __cxa_thread_call_dtors: dtr 0x3c2340 from unloaded dso, skipping
                                                                                                                                             __cxa_thread_call_dtors: dtr 0x3c2340 from unloaded dso, skipping
                                                     __cxa_thread_call_dtors: dtr 0x3c2340 from unloaded dso, skipping

Similar bug was also reported for Bitcoin here https://github.com/bitcoin/bitcoin/issues/16055, also affecting FreeBSD.

### Area(s) with issue?

The bug also exists in RCT2 (vanilla)

### Steps to reproduce

Start the game.

### Attachments

![image](https://user-images.githubusercontent.com/4457924/141314520-14cc8f44-9594-4c17-ac22-4db9744c1ec2.png)
![image](https://user-images.githubusercontent.com/4457924/141314555-545cd490-a12a-4cbe-887a-17a585e32dd2.png)

**Comment by duncanspumpkin** [comment]
You have not linked your rct2 install correctly and it is missing all of the object files. Install rct2 files and this will be corrected.

**Comment by pkubaj** [comment]
What do you mean by linking? The binary is linked:
```
pkubaj@KGPE-D16:$~$ file /usr/local/bin/openrct2
/usr/local/bin/openrct2: ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), dynamically linked, interpreter /libexec/ld-elf.so.1, for FreeBSD 13.0 (1300139), FreeBSD-style, stripped
```

I have RCT2 extracted in ~/.rct2/app:
```
pkubaj@KGPE-D16:$~$ ls .rct2/app/
__support                 goggame-1207658957.ico    Landscapes                readme.txt
Data                      goggame-1207658957.info   manual.pdf                Scenarios
goggame-1207658957.dll    goggame-1207658957.script ObjData                   Tracks
goggame-1207658957.hashdb goggame.sdb               RCT2.EXE                  webcache.zip
```

And all the data files in /usr/local/share/openrct2:
```
pkubaj@KGPE-D16:$~$ ls /usr/local/share/openrct2/*
/usr/local/share/openrct2/g2.dat

/usr/local/share/openrct2/language:
ar-EG.txt cs-CZ.txt de-DE.txt en-US.txt es-ES.txt fr-FR.txt it-IT.txt ko-KR.txt nl-NL.txt pt-BR.txt sv-SE.txt vi-VN.txt zh-TW.txt
ca-ES.txt da-DK.txt en-GB.txt eo-OO.txt fi-FI.txt hu-HU.txt ja-JP.txt nb-NO.txt pl-PL.txt ru-RU.txt tr-TR.txt zh-CN.txt

/usr/local/share/openrct2/object:
official rct1     rct2     rct2tt   rct2ww

/usr/local/share/openrct2/shaders:
applypalette.frag      applytransparency.frag drawline.frag          drawrect.frag
applypalette.vert      applytransparency.vert drawline.vert          drawrect.vert

/usr/local/share/openrct2/title:
rct1     rct1aa   rct1aall rct2     v0.0.2   v0.0.3   v0.0.4   v0.0.5   v0.1.0   v0.1.2
```

To be extra sure, I started the game with `openrct2 --rct2-data-path=~/.rct2/app --openrct2-data-path=/usr/local/share/openrct2/`, but that doesn't help.

**Comment by James103** [comment]
Can you please post the `config.ini` that you are using?

**Comment by pkubaj** [comment]
```
[general]
always_show_gridlines = false
autosave = 1
autosave_amount = 10
confirmation_prompt = false
currency_format = USD
custom_currency_rate = 10
custom_currency_affix = SUFFIX
custom_currency_symbol = "Ctm"
edge_scrolling = true
edge_scrolling_speed = 12
fullscreen_mode = 0
fullscreen_height = 2160
fullscreen_width = 3840
rct1_path = ""
game_path = "/usr/home/pkubaj/.rct2/app"
landscape_smoothing = true
language = en-US
measurement_format = IMPERIAL
play_intro = false
save_plugin_data = true
debugging_tools = false
show_height_as_units = false
temperature_format = FAHRENHEIT
window_height = 2138
window_snap_proximity = 5
window_width = 3838
default_display = 0
drawing_engine = SOFTWARE
uncap_fps = false
use_vsync = true
date_format = MM/DD/YY
auto_staff = true
handymen_mow_default = false
default_inspection_interval = 2
last_run_version = "0.3.5"
invert_viewport_drag = false
load_save_sort = NAME_ASCENDING
minimize_fullscreen_focus_loss = true
disable_screensaver = true
day_night_cycle = false
enable_light_fx = false
enable_light_fx_for_vehicles = false
upper_case_banners = false
disable_lightning_effect = false
allow_loading_with_incorrect_checksum = true
steam_overlay_pause = true
window_scale = 1.000000
scale_quality = SMOOTH_NEAREST_NEIGHBOUR
show_fps = false
multi_threading = false
trap_cursor = false
auto_open_shops = false
scenario_select_mode = 1
scenario_unlocking_enabled = true
scenario_hide_mega_park = true
last_game_directory = ""
last_landscape_directory = ""
last_scenario_directory = ""
last_track_directory = ""
use_native_browse_dialog = false
window_limit = 64
zoom_to_cursor = true
render_weather_effects = true
render_weather_gloom = true
show_guest_purchases = false
show_real_names_of_guests = true
allow_early_completion = false
virtual_floor_style = GLASSY
transparent_screenshot = true
transparent_water = true
last_version_check_time = 1636661759

[interface]
toolbar_show_finances = true
toolbar_show_research = true
toolbar_show_cheats = false
toolbar_show_news = false
toolbar_show_mute = false
toolbar_show_chat = false
toolbar_show_zoom = true
console_small_font = false
current_theme = "*RCT2"
current_title_sequence = "*OPENRCT2"
random_title_sequence = false
object_selection_filter_flags = 16383
scenarioselect_last_tab = 0

[sound]
audio_device = ""
master_sound = true
master_volume = 100
title_music = 2
sound = true
sound_volume = 100
ride_music = true
ride_music_volume = 100
audio_focus = false

[network]
player_name = "pkubaj"
default_port = 11753
listen_address = ""
default_password = ""
stay_connected = true
advertise = true
advertise_address = ""
maxplayers = 16
server_name = "Server"
server_description = ""
server_greeting = ""
master_server_url = ""
provider_name = ""
provider_email = ""
provider_website = ""
known_keys_only = false
log_chat = false
log_server_actions = false
pause_server_if_no_clients = false
desync_debugging = false

[notifications]
park_award = true
park_marketing_campaign_finished = true
park_warnings = true
park_rating_warnings = true
ride_broken_down = true
ride_crashed = true
ride_casualties = true
ride_warnings = true
ride_researched = true
ride_stalled_vehicles = true
guest_warnings = true
guest_left_park = true
guest_queuing_for_ride = true
guest_on_ride = true
guest_left_ride = true
guest_bought_item = true
guest_used_facility = true
guest_died = true

[font]
file_name = ""
font_name = ""
x_offset = 0
y_offset = 1
size_tiny = 1
size_small = 0
size_medium = 0
size_big = 0
height_tiny = 0
height_small = 0
height_medium = 0
height_big = 0
enable_hinting = true
hinting_threshold = 0

[plugin]
enable_hot_reloading = false
allowed_hosts = ""
```

**Comment by pkubaj** [comment]
It's mostly the default config.ini, as I have removed .config/OpenRCT2 to start clean.

**Comment by janisozaur** [comment]
In the bitcoin bug you reported, it is claimed the `thread_local` is buggy. The finding of that bug is dated 2018, so perhaps it is fixed already, but can you possibly check if removing those fixes your issue? I recall two places: one for loading objects (quite old) and one for software drawing (fairly recent), but there might be more.

**Comment by janisozaur** [comment]
Discussion where the bug was found: https://groups.google.com/g/bsdmailinglist/c/22ncTZAbDp4/m/Dii_pII5AwAJ?pli=1

**Comment by Gymnasiast** [comment]
You are using a `release` or `develop` version of OpenRCT2 with objects intended for the NSF branch. This is given away by the path it complains about missing paths, which are done differently in the NSF.

How did you install OpenRCT2 and how did you install the objects?

**Comment by pkubaj** [comment]
@Gymnasiast 
OK, I did not know that. I just downloaded the last objects release and put that in the data directory. The reason I can't allow it to be downloaded during the compilation is that FreeBSD's package builders specifically disable network access during package build and any necessary distfiles have to be fetched prior to that. I'm actually OpenRCT2's maintainer for FreeBSD.

Should I try with objects 1.0.21, as mentioned here https://github.com/OpenRCT2/OpenRCT2/blob/develop/CMakeLists.txt#L64 ?

**Comment by janisozaur** [comment]
Yes, correct versions are required

**Comment by Gymnasiast** [comment]
@pkubaj Yes, you need 1.0.21 for `develop`, indeed.

**Comment by pkubaj** [comment]
OK, then if I make a suggestion, please release the new OpenRCT2 versions along with the required objects. Releasing newer objects as tagged releases suggests that I can just take it and use it with the latest OpenRCT2 version. While I'm sure most users building on their own won't notice it, this is important for package maintainers, since I'm pretty sure that builders on other systems also can't access network, unless at distfile fetching stage.

**Comment by IntelOrca** [comment]
@pkubaj this is a rare occasion, this does not normally happen. It is because we are gearing up for the new save format, which is a complicated change to the game.
