### ISSUE TITLE
Game crash after 1-2 min of loading one file

### ISSUE THREAD

**Issue by RCTjunkie** [OpenRCT2/OpenRCT2#15908]
### Operating System

Win 10 64 bit 21H1

### OpenRCT2 build

OpenRCT2 v0.3.5, 0.3.4

### Describe the issue

Game crashes each time it tries to load a specific scenario save file. Doesn't happen with version 0.3.3 or earlier, but all versions after sees crash/corruption

### Steps to reproduce

1. Open game 
2.  Load custom Dusty Desert File
3. Play around for a few minutes

### Attachments

[f42877c7-38c1-456f-8e06-ab95f654dffd(b9bc8d0_x86-64).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/7532919/f42877c7-38c1-456f-8e06-ab95f654dffd.b9bc8d0_x86-64.dmp.gz)

**Comment by James103** [comment]
Did you mean to say "OpenRCT2 0.3.5, 0.3.4, 0.3.3" instead of "OpenRCT2 3.0.5, 3.0.4, 3.0.3" respectively?

**Comment by RCTjunkie** [comment]
> Did you mean to say "OpenRCT2 0.3.5, 0.3.4, 0.3.3" instead of "OpenRCT2 3.0.5, 3.0.4, 3.0.3" respectively?

Yes, apologies for the confusion. Updated

**Comment by Gymnasiast** [comment]
If it crashes on a specific save, then you must also upload that.

**Comment by RCTjunkie** [comment]
[Dusty Desert_ZZZZV.zip](https://github.com/OpenRCT2/OpenRCT2/files/7536131/Dusty.Desert_ZZZZV.zip)
