### ISSUE TITLE
Game will not load after save.

### ISSUE THREAD

**Issue by Pikanet128** [OpenRCT2/OpenRCT2#15923]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5 (b9bc8d0) provided by GitHub

### Describe the issue

When loading "Mothball Mountain4.sv6" it keeps crashing

"Mothball Mountain.sv6" is from an auto save after initial crash.
And the only thing I had done was reopen the go karts after changing to race mode and saved, this loaded again.
But when I try to edit the underground que-line (which is too long) and save. Now it crashes on load. See attempts 3&4.

### Steps to reproduce

1. Load game
2. Change 1 que path to a regular path around the middle of the underground que line for the go carts.
3. save game
4. try to load game but crashes

### Attachments

[save.zip](https://github.com/OpenRCT2/OpenRCT2/files/7551976/save.zip)

**Comment by ZehMatt** [comment]
I can not reproduce the crash on the develop branch, could you try the latest build and see if it still happens?

**Comment by Pikanet128** [comment]
After a bit of messing around removing plugins one at a time I found the culprit.
blame "StuffCounter.js"

**Comment by Pikanet128** [comment]
After a bit of messing around removing plugins one at a time I found the culprit.
blame "StuffCounter.js"
