### ISSUE TITLE
Cleanup TrackDesignSave flag code

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#15934]
These two blocks of code are identical, and are using hardcoded masks and offsets.

https://github.com/OpenRCT2/OpenRCT2/blob/4a8af923a3b766527dac5dbcaa25c18444595403/src/openrct2/ride/TrackDesignSave.cpp#L374-L380

https://github.com/OpenRCT2/OpenRCT2/blob/4a8af923a3b766527dac5dbcaa25c18444595403/src/openrct2/ride/TrackDesignSave.cpp#L554-L560

These flags are compared to `TrackDesignSceneryElement::flags`. It does not match `PathElement`'s flags.

It would be cleaner to introduce a function that builds up the flags for paths, and to use constants rather than hardcoded numbers.

**Comment by Gymnasiast** [comment]
Has since been refactored.
