### ISSUE TITLE
Guest path finding bug

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#1593]
Start a new game in Six Flags Belgium.
Close all rides shops and the park
Fast-forward until you have about 60-70 guests left 
You will notice that guests seem to be stuck next to the Turbine. They will walk up to the flowers and start heading back towards the Turbine

**Comment by rctdude2** [comment]
No, that's just "normal" guest pathfinding behavior. It would be nice to see better pathfinding in the future, including using transport rides properly.

**Comment by Gymnasiast** [comment]
It _is_ good to know what kinds of glitches the current pathfinding has, namely to see if an experimental new algorithm solves it. SF Belgium is especially handy, since everyone should have it.

**Comment by Nubbie** [comment]
I wonder if anything has to do with the original 'Death Trap' bug too
Especially when they are leaving the park
#3261

**Comment by duncanspumpkin** [comment]
Likely now fixed.

**Comment by zaxcav** [comment]
I've just tested this with the latest pathfinding improvements in PR #4527 and can confirm that the issue no longer exists.
It's possible the previous improvements had already fixed it, but I see no need to test the older improvements separately.
