### ISSUE TITLE
OpenRCT2 disregarding CJK fonts

### ISSUE THREAD

**Issue by YJSoft** [OpenRCT2/OpenRCT2#15932]
### Operating System

Ubuntu 20.04 on Windows 10 (WSL2)

### OpenRCT2 build

OpenRCT2, v0.3.5-75 (4e8916cff on develop)

### Describe the issue

OpenRCT2 is disregarding installed cjk fonts.

- `Gulim` -> substitute `Noto Sans CJK KR` ignored(which is expected)
- `Nanum Gothic` -> substitute `나눔고딕` ignored
- `Malgun Gothic` -> substitute `맑은 고딕` ignored

So OpenRCT2 will not find any fonts avaliable, and will fallback to bitmap font(which will result ??)

Although there are similar issue #13232, but since OpenRCT2 is ignoring installed fonts(because of translated name) I opened this issue.

### Steps to reproduce

1. Install Ubuntu 20.04 with korean locale
2. Install OpenRCT2
3. Try to open OpenRCT2

### Attachments

```
VERBOSE: Looking for font Gulim with FontConfig.
VERBOSE: FontConfig provided substitute font Noto Sans CJK KR -- disregarding.
VERBOSE: Unable to load font 'Gulim'
VERBOSE: Unable to load TrueType font 'Gulim' -- trying the next font in the family.
VERBOSE: Looking for font Nanum Gothic with FontConfig.
VERBOSE: FontConfig provided substitute font 나눔고딕 -- disregarding.
VERBOSE: Unable to load font 'Nanum Gothic'
VERBOSE: Unable to load TrueType font 'Nanum Gothic' -- trying the next font in the family.
VERBOSE: Looking for font Malgun Gothic with FontConfig.
VERBOSE: FontConfig provided substitute font 맑은 고딕 -- disregarding.
VERBOSE: Unable to load font 'Malgun Gothic'
VERBOSE: Unable to load TrueType font 'Malgun Gothic' -- trying the next font in the family.
VERBOSE: Unable to initialise any of the preferred TrueType fonts -- falling back to sans serif fonts.
VERBOSE: Looking for font Arial Unicode MS with FontConfig.
VERBOSE: FontConfig provided substitute font Noto Sans CJK JP -- disregarding.
VERBOSE: Unable to load font 'Arial Unicode MS'
VERBOSE: Unable to load TrueType font 'Arial Unicode MS' -- trying the next font in the family.
VERBOSE: Looking for font Arial with FontConfig.
VERBOSE: FontConfig provided substitute font Liberation Sans -- disregarding.
VERBOSE: Unable to load font 'Arial'
VERBOSE: Unable to load TrueType font 'Arial' -- trying the next font in the family.
VERBOSE: Unable to initialise any of the preferred TrueType fonts -- falling back to sprite font.
```

**Comment by Lastorder-DC** [comment]
![image](https://user-images.githubusercontent.com/18280396/175801010-b470a1b1-f5b8-4251-b3c2-fe34bdd93d06.png)

Still not fixed.

OpenRCT2 0.4.0 f77611dcd2a1d148f56c7fb4daf05deee116a571
On Lubuntu 20.04 64bit

**Comment by ricoazzurro** [comment]
#13232

**Comment by Lastorder-DC** [comment]
#13232 is about fontconfig ignoring fontconfig suggestions(which has valid reasons), but this issue is about fontconfig ignoring exact same font due to localized name.

**Comment by ricoazzurro** [comment]
my workaround,
edit config.ini, change [font] options according to fc-list,

[font]
file_name = "/usr/share/fonts/foo.font.ttc"
font_name = "translated name like 맑은 고딕"
x_offset = 0
y_offset = -2
size_tiny = 12
size_small = 12
size_medium = 12
size_big = 12
height_tiny = 12
height_small = 12
height_medium = 12
height_big = 12
enable_hinting = true
hinting_threshold = 0

**Comment by Richard-L** [comment]
Same on windows. It will look like this:
![image](https://user-images.githubusercontent.com/4934209/186255370-2bad2898-c444-4020-aa57-0661bc778505.png)
In this case the scenario "Leafy Lake" had been entered in Hangul: 나뭇잎 호수

**Comment by YJSoft** [comment]
Still not fixed although almost 2 years passed...

```
VERBOSE: Looking for font Gulim with FontConfig.
VERBOSE: FontConfig provided substitute font 굴림 -- disregarding.
VERBOSE: Unable to load font 'Gulim'
VERBOSE: Unable to load TrueType font 'Gulim' -- trying the next font in the family.
VERBOSE: Looking for font Nanum Gothic with FontConfig.
VERBOSE: FontConfig provided substitute font Noto Sans CJK JP -- disregarding.
VERBOSE: Unable to load font 'Nanum Gothic'
VERBOSE: Unable to load TrueType font 'Nanum Gothic' -- trying the next font in the family.
VERBOSE: Looking for font Malgun Gothic with FontConfig.
VERBOSE: FontConfig provided substitute font Noto Sans CJK KR -- disregarding.
VERBOSE: Unable to load font 'Malgun Gothic'
VERBOSE: Unable to load TrueType font 'Malgun Gothic' -- trying the next font in the family.
VERBOSE: Unable to initialise any of the preferred TrueType fonts -- falling back to sans serif fonts.
VERBOSE: Looking for font Arial Unicode MS with FontConfig.
VERBOSE: FontConfig provided substitute font Noto Sans CJK JP -- disregarding.
VERBOSE: Unable to load font 'Arial Unicode MS'
VERBOSE: Unable to load TrueType font 'Arial Unicode MS' -- trying the next font in the family.
VERBOSE: Looking for font Arial with FontConfig.
VERBOSE: FontConfig provided substitute font Liberation Sans -- disregarding.
VERBOSE: Unable to load font 'Arial'
VERBOSE: Unable to load TrueType font 'Arial' -- trying the next font in the family.
VERBOSE: Unable to initialise any of the preferred TrueType fonts -- falling back to sprite font.
```

**Comment by YJSoft** [comment]
I'm just going to close this one since general fontconfig problem can be tracked from #13232, And I just decided to fork project and use my own build, rather than waiting for this issue fixed.

**Comment by YJSoft** [comment]
Although 58863c6bc6c6d4d055ba0081d6a36cd0c6cdbf63 fixes some of problem, It's not right fix since It still can choose invalid font.

```
VERBOSE: Looking for font Nanum Gothic with FontConfig.
VERBOSE: FontConfig provided substitute font Noto Sans CJK JP -- disregarding.
VERBOSE: Unable to load font 'Nanum Gothic'
VERBOSE: Unable to load TrueType font 'Nanum Gothic' -- trying the next font in the family.
```

In above case, FontConfig choose `Noto Sans CJK JP` as substitute for `Nanum Gothic` which is invalid(It should be `Noto Sans CJK KR`)

I think most easy fix is just add substitutable font names for all fonts registered, since I don't have much time for implement so...

**Comment by RuboGubo** [comment]
Yeah this is still an issue to this day.
