### ISSUE TITLE
Error "can't remove this" when removing a turned pirate ship via the ride construction window

### ISSUE THREAD

**Issue by ferrybig** [OpenRCT2/OpenRCT2#15947]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5 (c9c6172 on develop) provided by GitHub

### Describe the issue

Trying to remove a rotateds pirate ship results in a error "can't remove this", causing an invalid game state where the game thinks you remove the pirate ship, but it is still in the world.

If you don't spot this error, you can then place the pirate ship down again, and it gets quite confusing as the rest of the code only expects a pirate ship ride to only have 1 building

### Steps to reproduce

1. Load a new game
2. Select the pirate ship in the building menu
3. Press the rotate button (https://i.imgur.com/FQNjEWj.png)
4. Place the rotated pirate ship in the game (https://i.imgur.com/bJ0tTJ6.png)
5. Press right click to select it
6. Press the destroy button ( https://i.imgur.com/qgpA9ax.png)

Observe the bug: 
![image](https://user-images.githubusercontent.com/1576684/142777111-531658e0-302d-4545-bd21-a2df91d8a7cf.png)

The game now allows you to place it down again, while it is still present in the world, leading to all other "can't happen" state bugs

**Comment by James103** [comment]
Version: OpenRCT2, v0.3.5.1 (61c67af) provided by GitHub

I can reliably reproduce this, up to three times over for a single ride. Each extra building placed counts as a seperate station.
The following warning is printed to the console when the bug occurs:
```
WARNING[D:\a\OpenRCT2\OpenRCT2\src\openrct2\actions\TrackRemoveAction.cpp:113 (TrackRemoveAction::Query)]: Track Element not found. x = 1632, y = 1408, z = 96, d = 0, seq = 0.
```
