### ISSUE TITLE
Terrain generation doesn't work on the area above 148x148 on scenario generator

### ISSUE THREAD

**Issue by nofootlongs900** [OpenRCT2/OpenRCT2#15949]
### Operating System

Mac OSx

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (cbf922f on develop)

### Describe the issue

https://user-images.githubusercontent.com/94809264/142782834-4270277a-b717-453c-94f8-34d3237e94df.mov

### Steps to reproduce

1. 
2. 
3.

**Comment by James103** [comment]
Version: OpenRCT2, v0.3.5.1 (61c67af) provided by GitHub

I just tested on the above version, and you have to set the target map size inside the Map Generation window, as shown below:
![image](https://user-images.githubusercontent.com/37945304/142783595-125f99eb-b114-497e-bad1-cd854481409e.png)

The map size set in the "Map" window will be overridden by the size in the "Map Generation" window when "Generate" is clicked.
