### ISSUE TITLE
 Built 2 "stations" for pirate ship by accident?

### ISSUE THREAD

**Issue by xzyxzy** [OpenRCT2/OpenRCT2#15960]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5 (b9bc8d0) provided by GitHub

### Describe the issue

Was trying to build pirate ship, built it, entrance, but when I tried to build exit there was no usable space left, I clicked at some busy spot (landscape issue), got message about landscape, tried to remove ship, got error that it can't be removed and got suggested to build second pirate ship which I successfully did as displayed in this screenshot.

### Steps to reproduce

As described above.

### Attachments

[2 pirate ship is this a bug.zip](https://github.com/OpenRCT2/OpenRCT2/files/7580169/2.pirate.ship.is.this.a.bug.zip)
![2021-11-22-15-20-04_openrct2](https://user-images.githubusercontent.com/3988825/142846008-876fae72-d21e-460c-9c34-ec4b3c5a7b99.png)

**Comment by James103** [comment]
See: #15947
Did you get any warnings in the console while doing this? If so, can you list them?

**Comment by xzyxzy** [comment]
Console? I don't have any console window.

**Comment by James103** [comment]
Start `openrct2.com` instead of `openrct2.exe` to get a console window for OpenRCT2.

**Comment by xzyxzy** [comment]
> See: #15947 Did you get any warnings in the console while doing this? If so, can you list them?

WARNING[D:\a\OpenRCT2\OpenRCT2\src\openrct2\actions\RideEntranceExitRemoveAction.cpp:103 (RideEntranceExitRemoveAction::Query)]: Track Element not found. x = 1216, y = 3360, ride = 8, station = 2

**Comment by xzyxzy** [comment]
[4pirateships1attraction.zip](https://github.com/OpenRCT2/OpenRCT2/files/7581929/4pirateships1attraction.zip)
![openrct2 com_2021-11-22_19-34-52](https://user-images.githubusercontent.com/3988825/142879920-da6bc191-9221-4562-923a-ed397530a4bc.png)
