### ISSUE TITLE
Black Screen on Title Menu even after Reinstall on Linux

### ISSUE THREAD

**Issue by sfisher923** [OpenRCT2/OpenRCT2#15964]
### Operating System

Linux Mint 20.2 Cinnamon (64 Bit)

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (, DEBUG)

### Describe the issue

Having a Black Screen on load with the music playing

### Steps to reproduce

1. Do a Reinstall using the Software Manager
2. Launch the game
3. 

### Attachments

[Terminal Outputs.zip](https://github.com/OpenRCT2/OpenRCT2/files/7583091/Terminal.Outputs.zip)
Screenshot from the affected build
![Bug Report 5](https://user-images.githubusercontent.com/80093217/142906704-1eab9518-5e5f-4a30-b723-03daef7ad262.png)
Screenshot from the last seprate NSF Build for comparison
![NSF Round 3 title](https://user-images.githubusercontent.com/80093217/142906811-1386c3f6-f22a-4c3a-a5a3-b55995ef88e4.png)

**Comment by duncanspumpkin** [comment]
This happens if you load with object files from before the nsf was merged. You need to clean your install and remove the old object files.

**Comment by sfisher923** [comment]
Did that

I noticed my read write permissions for files being set to "---" on every folder in that directory so it might be a OS thing and trying a Restoration
