### ISSUE TITLE
Void Land Surface Texture not Working Correctly

### ISSUE THREAD

**Issue by saxman1089** [OpenRCT2/OpenRCT2#15977]
### Operating System

Windows 11, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (23491c8 on develop) provided by GitHub

### Describe the issue

I tried to use the new "void" surface texture option. When I selected it in the object selector, it showed up in the land tool window successfully. However, when I clicked on it to use it, the surface I was using as shown in the land tool window changed to one of the tiled roof textures (I have my RCT1 installation linked), and when I painted with it, it was changing the surfaces to brown dirt, not the void texture OR the tiled roof textures.

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Select void surface texture in the object selection window.
2. Try to select it within the land tool window.
3. Find it selected something else.
4. Paint land with the selection, and find it painted a land surface that was neither the void surface or the one it showed up as.

**Comment by James103** [comment]
What exact commit do you mean by "Latest develop version"? Have you tested on 9a32dd9 yet?

**Comment by saxman1089** [comment]
> What exact commit do you mean by "Latest develop version"? Have you tested on [9a32dd9](https://github.com/OpenRCT2/OpenRCT2/commit/9a32dd90eb3097df554bff63c62d9db2ff5ecb6f) yet?

As I said in my issue description, I am at work and don't know exactly which version it was, and I would try to update later to provide the exact version.

**Comment by duncanspumpkin** [comment]
Had you by chance loaded a ton of objects in this save. Specifically ride objects? I think the image allocater has one or two issues that occur when loading a lot of images.

**Comment by saxman1089** [comment]
Okay, I updated the version in my original issue now that I had a chance to check it out: 

OpenRCT2, v0.3.5.1 (23491c8 on develop) provided by GitHub

**Comment by saxman1089** [comment]
> Had you by chance loaded a ton of objects in this save. Specifically ride objects? I think the image allocater has one or two issues that occur when loading a lot of images.

I've got a few custom ride types, but not an exorbitant amount. I also don't have a ton of object selected (still below the vanilla limits for small and large objects and walls). I deselected all of the custom rides I could, saved, quit OpenRCT2, and restarted, and I still get the same issue.

**Comment by danielmeinert** [comment]
I'd like to reiterate on this bug. When I open the scenario editor and add to the default selection just the void land texture (to not go over the image limit?) the following happens when trying to place it. I also made other new surface textures parkobj and they show the same behaviour. 

![Animation](https://user-images.githubusercontent.com/39702411/144712390-03871142-8503-447a-9889-eef509f6c994.gif)


Currently on 
OpenRCT2, v0.3.5.1 (459c0d6 on develop) provided by GitHub 
Windows 10 64 bit

**Comment by duncanspumpkin** [comment]
@danielmeinert i take it you do not have RCT1 linked? Currently you need either rct1 linked or you need to unload some other surface textures otherwise it will trigger the RCT1 fallback code when it tries to draw any surface past the first 13.

**Comment by danielmeinert** [comment]
No I don't have. Will it be possible to have more textures loaded on a map in the future?

**Comment by duncanspumpkin** [comment]
Yes it's being worked on. Need to change one or two things to prevent graphical issues before we can remove this fallback code.

**Comment by Gymnasiast** [comment]
Fixed by #16127.
