### ISSUE TITLE
Ride ratings don't calculate and calculate wrong

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#1597]

**Comment by Gymnasiast** [comment]
I noticed that ratings often (or perhaps always) eventually show up, but that they take extraordinarily long, and seem to take multiple test runs to calculate.

**Comment by IntelOrca** [comment]
It is related to my implementation of proximity scoring. I have fixed the long delay of getting a rating, but I am still trying to fix it from giving the wrong rating.
