### ISSUE TITLE
Rides get built underground when clearance checks disabled

### ISSUE THREAD

**Issue by Phasedetect** [OpenRCT2/OpenRCT2#1598]
Replicate: Build your own six flags, disable clearance checks. Place a flat ride or coaster, it gets built 2 units below ground. This can be avoided by using the shift key, but it still deviates from expected behavior.

![clipped rides](https://cloud.githubusercontent.com/assets/7439907/8654555/f6cccf4a-2958-11e5-9f6f-d5e85ae0b0e0.JPG)

Also of note: when a ride is built half-underground with this method, trying to build an entrance to it causes a crash.

**Comment by duncanspumpkin** [comment]
This is a known issue that I'm not sure what would be the best solution. The way the game works is it tries placing at just below surface height then increments and tries again. With disabled clearance it always succeeds.

**Comment by Phasedetect** [comment]
Is the inability to construct entrances/exits at all times a related bug?

Recreate: Disable clearance checks, build ride (using shift key to build on ground level), then place entrance and exit.

**Comment by IntelOrca** [comment]
@duncanspumpkin Perhaps for now, start the check from surface level if disable clearance is enabled.
