### ISSUE TITLE
Nothing but UI being rendered

### ISSUE THREAD

**Issue by MaxMallon** [OpenRCT2/OpenRCT2#15987]
### Operating System

Windows 10, 64bit

### OpenRCT2 build

OpenRCT2-0.3.5.1-develop-6e839bd-windows-x64

### Describe the issue

When starting up the game, the UI loads fine and the music plays, but the background is entirely black.
When opening a save or scenario, I'm greeted with a blue window saying "Error loading objects for park", listing a bunch of files that seem to be the default ground types, such as  "rct2.terrain_surface.rock", and "rct2.terrain_edge.wood", but also the ones from RCT1. The game returns to the menu. 
(BTW: the blackness is not updated, so all the windows leave trails if you move them around, and 'stay' if you close them.)
To at least start somewhere, I tried looking if the location of the RCT1 files had maybe been reset, clicking the button in the menu caused the game to instantly close without any message or anything. 

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Open the game, that's it.

### Attachments

![RIP1](https://user-images.githubusercontent.com/22072563/143280789-a72c945e-d760-454e-81b3-c3cc733dc09f.png)
![RIP2](https://user-images.githubusercontent.com/22072563/143280793-a18f0042-3ee8-498f-96f5-ef67bfb2a773.png)

**Comment by duncanspumpkin** [comment]
This happens if you mix the install files from the develop branch and the master branch. Just fully uninstall the game and reinstall it. (When I say fully uninstall you can keep your user files I mean purely your OpenRCT2 installation files).

**Comment by MaxMallon** [comment]
Ooh, that did the trick! Thanks!
