### ISSUE TITLE
NSF park won't load after update

### ISSUE THREAD

**Issue by daand12** [OpenRCT2/OpenRCT2#15981]
### Operating System

Windows 10 Pro 64-bit

### OpenRCT2 build

OpenRCT2 v0.3.51 (9a32dd9 on Develop )

### Describe the issue

Updated the game from the launcher today and tried to load my .park save file 
Now it won't load my park and it doesn't display any error message, but it's full of custom rides / stalls and some scenery.
I don't think this matters at all as it worked on a previous version which is available on Github during testing.

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Download the save here http://gofile.me/6LHnx/tCqsOmc2V
2. Use the exact same build as reported in here
2. Try at least on two pc's
3.

**Comment by karst** [comment]
I can confirm this with two of my test parks aswell. One from the first NSF public test build was working just fine, but the one saved in the third public test build do not want to load anymore. 
Older build: https://cdn.discordapp.com/attachments/691735032531779684/912116165336240148/Purr_Bay_-_older_build_.park (Still loads)
Later build: https://cdn.discordapp.com/attachments/691735032531779684/912116166883946496/Purr_Bay_-_later_build.park
SV6: https://cdn.discordapp.com/attachments/691735032531779684/912139791796174948/Purr_Bay.sv6
Necessary assets: https://cdn.discordapp.com/attachments/691735032531779684/912123482375094302/object.zip

**Comment by Gymnasiast** [comment]
We’ll take a look, but the saves from the test builds were not guaranteed to load later on. They were test builds for that reason. Only now it’s been merged do we guarantee backwards compatibility.

**Comment by karst** [comment]
Absolutely, it's personally why I created those .parks in the first place. To get to testing :)

**Comment by duncanspumpkin** [comment]
@daand12 's save is crashing on staff entities. Its a version 4 save.
