### ISSUE TITLE
Park size maximum is 999 but maximum input accepted is 998

### ISSUE THREAD

**Issue by oli414** [OpenRCT2/OpenRCT2#15998]
### OpenRCT2 build

OpenRCT2, v0.3.5.1 (2b4eaab on develop)

### Describe the issue

I noticed a lot of people saying that the new maximum park size is 999x999, but in game you can only make the spinner in the map view window go up to 998.

janisozaur pointed me to the source code to correct me saying that the size was 998 instead of 999, but it looks like it is intended to be 999:
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/world/Map.h#L25-L27

### Steps to reproduce

1. Open a park in sandbox mode
2. Increase the park size to 999
3. The maximum value of the spinner is 998 instead of 999

**Comment by oli414** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/83b911b193b1f461832a8024dea83cebe93d52ed/src/openrct2-ui/windows/Map.cpp#L659
The value gets clamped to a maximum of MAXIMUM_MAP_SIZE_TECHNICAL 

But in the game action that the value is passed on to, MAXIMUM_MAP_SIZE_TECHNICAL, and anything above, triggers an error:
https://github.com/OpenRCT2/OpenRCT2/blob/83b911b193b1f461832a8024dea83cebe93d52ed/src/openrct2/actions/ChangeMapSizeAction.cpp#L36

**Comment by IntelOrca** [comment]
> I assume it's 999, as in, 999x999 tiles that a user can built on.

Yes it is 999x999 which equals 1001 x 1001 for gMapSize.
