### ISSUE TITLE
Make object selection filters persistent

### ISSUE THREAD

**Issue by Phasedetect** [OpenRCT2/OpenRCT2#1599]
I almost always hide WW/TT rides in the object selection dialog, and it would be nice if the window remembered the filter states from the last time so that I didn't have to deselect them every time. Persistent even when quitting / launching the game would be even better, but on a per-launch basis would still be good.

**Comment by chrismilne300** [comment]
I think it should be made optional in the options. Something like make object selection filters persistent.

**Comment by IntelOrca** [comment]
Adding an option to the settings window for whether it should save a dropdown would be overkill IMO.
