### ISSUE TITLE
Segfault when opening ride statistics for huge ride in NSF

### ISSUE THREAD

**Issue by patrikndv** [OpenRCT2/OpenRCT2#16002]
### Operating System

Linux (x86-64)

### OpenRCT2 build

OpenRCT2, v0.3.5.1-54 (2b4eaab5d on develop, DEBUG)

### Describe the issue

When opening the statistics tab in the monorail ride in the attached park the game crashes with a segmentation fault. Presumably it's because the ride is humongous with 36 stations and 108 trains. Statistics for normal-sized rides work fine.

### Steps to reproduce

1. Open the attached park
2. Click on the monorail ride
3. Click on the statistics (measurements and test results) tab
4. The game crashes

### Attachments

[Big Monorail Stats Segfault.park.zip](https://github.com/OpenRCT2/OpenRCT2/files/7605076/Big.Monorail.Stats.Segfault.park.zip)

**Comment by frutiemax** [comment]
I fear this won't show up correctly in the window...
