### ISSUE TITLE
Issue with saving track design with scenery

### ISSUE THREAD

**Issue by TSElephant** [OpenRCT2/OpenRCT2#16019]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (7b3afe9 on develop) provided by GitHub

### Describe the issue

In a custom park that I'm building, tracks can't seem to be saved with any scenery. Tracks on their own save just fine, but once I include a single piece of scenery or path, I get the error message, "Can't save track design... ride is too large, contains too many elements, or scenery is too spread out." I've tried other parks that I have saved, and they seem unaffected. This bug is only present in the .park file I've included.

The easiest way to reproduce this bug is by trying to save the ride "Aperture Science Transport," and selecting nearby scenery.

[The Custom Sandbox.zip](https://github.com/OpenRCT2/OpenRCT2/files/7610297/The.Custom.Sandbox.zip)

### Steps to reproduce

1. Open "The Custom Sandbox" .park file.
2. Choose a ride at random.
3. Select "save track design with scenery."
4. Select one piece of scenery or path, or click "select nearby scenery."
5. Click "save."
6. Observe error message and weep.

**Comment by andyjamesduncan** [comment]
Having a similar problem with a new Mac Download of Version '0.3.5.1'. There are no error messages, and everything seems to save fine, when saving rides with scenery, it's just that I never see the scenery of paths again when I try to load the saved ride. This happens both 'in-game' and in 'Track Designer'. In the attached screenshot, the ride that I've saved with scenery and without any apparent errors is at the bottom of the screen. At the top of the screen is what I get back when I load the 'saved' ride. 
<img width="1344" alt="Screenshot 2021-11-28 at 12 47 38" src="https://user-images.githubusercontent.com/10495387/143729994-792bc8bd-7774-4b95-88ac-97ad46973666.png">
.

**Comment by TSElephant** [comment]
I've just performed 2 additional tests.

I saved my park as a scenario, then opened that scenario. The problem persisted.

I have also uninstalled and reinstalled OpenRCT2, and the problem persists.

I hope that might be helpful.

**Comment by TSElephant** [comment]
As a final test, I've created a new scenario from scratch, with a smaller area and only one ride.

[Pure Conjecture Bug.zip](https://github.com/OpenRCT2/OpenRCT2/files/7616350/Pure.Conjecture.Bug.zip)

Still having the same problem. That single micro-coaster won't save if you include a single tile of queue path.

Not really sure what to do. This really kills my motivation to play. If I just knew how to avoid it, that would be enough for me.

**Comment by Gymnasiast** [comment]
We merged some fixes, could you try it with a recent develop build?

**Comment by Gymnasiast** [comment]
Closing as there has been no reply for 2 years.
