### ISSUE TITLE
lost scenery, paths, rides

### ISSUE THREAD

**Issue by crystaldragon637** [OpenRCT2/OpenRCT2#16012]
### Operating System

windows 11 64 bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (61c67af) provided by GitHub

### Describe the issue

I downloaded the new dev a couple of days ago and it wouldn't load rct2. So I uninstalled the file and then reinstalled it. worked ok. I made a new park and started it ok. I went back in the next day and the buildings were gone and half the objects. The rides were all blank (no Pictures).Then I got the next dev file and nothing all my scenery, paths, everything was gone.
I went back to the last normal file and still nothing.

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. I put a screenshot of forest frontiers I tried to play but there are no objects 
2. also of the two windows with no scenery or rides
3. 

### Attachments

![Forest Frontiers 2021-11-26 22-11-29](https://user-images.githubusercontent.com/90950173/143587629-3478586f-7408-4743-bcb3-9d58f94fb95c.png)
![Forest Frontiers 2021-11-27 00-38-22](https://user-images.githubusercontent.com/90950173/143589491-3e1ca552-90f3-441b-a474-37347706ac6f.png)

**Comment by ZehMatt** [comment]
Please provide the save file.

**Comment by Broxzier** [comment]
In the last screenshot you can see the banner text of the middle park entrance element, so the elements are there. Somehow only the sprites don't show up.

https://github.com/OpenRCT2/OpenRCT2/commit/61c67afc667bfee8a6c3b180e98e84e87f442550 is from the last release. Did you remove the object files from NSF before installing this version?

**Comment by crystaldragon637** [comment]
sorry just saw this. a couple of the other guys helped me on discord and we
got it fixed

Lisa
