### ISSUE TITLE
UI intermittent when large number of scenery exists in custom scenario

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#16010]
### Operating System

Windows 11 Insider Beta Branch

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (56e78d5 on develop) provided by GitHub

### Describe the issue

I made a custom scenario near the upper limits of the new save format. The game flickers like in other issues listed but in addition there are also missing ride preview images. It may be because of too many custom types of trains selected for that ride. I also run at 5120x2160 and the game used to work fine but now is crashing constantly.

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Play a scenario with 998x998 and tons of custom scenery
2. Play at very high resolution
3. See if all ride types are rendered or if they flicker

### Attachments

![2021-11-25 (9)](https://user-images.githubusercontent.com/94884086/143516683-c838f83c-9121-4ccd-85af-23d02875c77a.png)
![2021-11-25 (11)](https://user-images.githubusercontent.com/94884086/143516900-b3e21a29-5bd5-4c22-b850-feda4960126a.png)
![2021-11-25 (12)](https://user-images.githubusercontent.com/94884086/143516901-b54fbeef-d292-45dc-89a9-484c80b8f6d7.png)
![2021-11-25 (13)](https://user-images.githubusercontent.com/94884086/143516902-9c47f622-d81b-485f-8991-44d6a80f59d1.png)
![2021-11-25 (14)](https://user-images.githubusercontent.com/94884086/143516903-e72b7e7a-4a81-4407-bda5-b810696384b3.png)
![2021-11-25 (15)](https://user-images.githubusercontent.com/94884086/143516904-d606c596-5d50-46ec-a10d-b39c95b03e70.png)
![2021-11-25 (16)](https://user-images.githubusercontent.com/94884086/143516905-10811593-1208-4e55-a6d3-d136e0d4d58d.png)

**Comment by duncanspumpkin** [comment]
You are almost definitely hitting the image limit

**Comment by 733737** [comment]
i didnt know there was an image limit. is that because of the variables being integers? would floats not work?

**Comment by ZehMatt** [comment]
> i didnt know there was an image limit. is that because of the variables being integers? would floats not work?

Its has no more bits available for more images, its an integer and floats would have less space. Its something we want to fix and will eventually work on, its not as easy as it seems.

**Comment by 733737** [comment]
if it is a known issue, I am not concerned with it. I am okay with it not being fixed right away.

**Comment by Gymnasiast** [comment]
@733737 We merged a commit today that increases the image limit. Could you test if this solves the problem for you?

**Comment by 733737** [comment]
yes it is fixed
