### ISSUE TITLE
Uncap FPS significantly reduces performance

### ISSUE THREAD

**Issue by Rock48** [OpenRCT2/OpenRCT2#1602]
I was testing the "Uncap FPS" checkbox to see what my roller coasters would look like on my 144Hz monitor and I noticed that in situations where there's a lot of stuff going on, checking that box will significantly reduce performance. Here's a gif showing the framerate as I turn it on and off.

![image](http://i.imgur.com/zu1q1vb.gif)

**Comment by IntelOrca** [comment]
What is the size of your window / resolution?

**Comment by zsilencer** [comment]
maybe you can do a side by side recording showing the same areas

**Comment by Rock48** [comment]
@IntelOrca 1920x1080
@zsilencer Fraps just being open makes the game run at like 15fps for some reason, might want to look into that as well.

**Comment by IntelOrca** [comment]
The game should run at the same play speed, but it might look more choppy where there is lots of stuff to redraw. This is limited by your CPU clock speed. It should run smoother if your window or resolution is smaller.

**Comment by Rock48** [comment]
@IntelOrca That isn't the issue I'm showing here-- I'm well aware that the game may run at a lower FPS when using a higher resolution (Though it really shouldn't with my i7-3770S and GTX 980 Ti but w/e) The issue is that it runs at a lower framerate when I uncap the FPS in the settings, if I leave it capped it goes higher.

**Comment by zsilencer** [comment]
if you aren't even getting 40fps normally then uncapped will not do anything to improve that, and of course there is some overhead in tweening sprites and invalidating them.

**Comment by IntelOrca** [comment]
Multiple cores or a graphics card won't improve the speed it draws at as its entirely software rendered. Only a faster single core clock speed on the processor.

I expect the way you are measuring the FPS is not actually measuring it in the correct way, simply due to the fact that it is not rendering the graphics like most games would particularly if you have hardware display on.

**Comment by Rock48** [comment]
Clearly it *is* using the GPU at some point here-- Idle my gpu utilization is at 0-1%, when I open OpenRCT2 the utilization rises to ~5%. To measure framerate I'm using MSI Afterburner which internally uses Rivatuner. 

And in that gif (difficult to show as gyazo only allows for 6-seconds) it does hit 40FPS with the FPS cap on, but it drops down to ~25 when I turn off the FPS cap.

I also understand that there will be an exponential amount of overhead as the framerate increases but it still doesn't explain why the framerate is so unstable and drops so low when the FPS cap is turned off.

I'm not a simpleton, I know how software renderers work, and it doesn't make sense that when uncapped the framerate drops.

**Comment by IntelOrca** [comment]
The GPU is only used when hardware display is on. All the game does is channel pixel data through the GPU so that the game can be captured more easily or to support steam overlay which hooks onto DirectX or OpenGL.

Ideally we would want the actual game to be rendered by the GPU itself, but that is a long way away. Does the game run noticeably smoother with hardware display off and without running any performance measurement software or capturing software?

**Comment by Rock48** [comment]
The only performance measuring tool that hurts it is fraps, but that's a terrible program anyway.

**Comment by Patrik356b** [comment]
@Rock48 it's not terrible but there are better options out there.

**Comment by PFCKrutonium** [comment]
MSI Afterburner comes with a good performance monitoring tool...

**Comment by Rock48** [comment]
@PFCKrutonium I used MSI Afterburner there.

**Comment by rustinlee** [comment]
@Rock48 My favorite workflow for this sort of thing is to use [Open Broadcaster Software](https://obsproject.com/) to record a 60 (or in your case 144) FPS .MP4. I imagine you'll need to set the bitrate veeery high (4096 kb/s or something) to get a good 144Hz capture but we'll be able to see exactly what's going on. There's options for encoders which primarily use GPU.

**Comment by rustinlee** [comment]
Anyway, I was [unable to replicate](http://srv.rustin.me/devel/uncap%20fps.mp4) choppiness or slowdowns with uncap FPS. Tried toggling hardware display off and on within the game and launching with the two different settings. Pardon the giant filesize, I wanted to make sure I got the full FPS.

This video is 600x480 for the sake of filesize but I tried it at 1600x900 as well.

**Comment by PFCKrutonium** [comment]
@rustinlee It actually happens to me on my Core2Quad System, but not on my i7 list.

**Comment by rustinlee** [comment]
I probably should have thought to mention my specs. This was done on an i5-3570K.
