### ISSUE TITLE
Go-Carts default to multi-car trains with cheats, which get stuck

### ISSUE THREAD

**Issue by josepher44** [OpenRCT2/OpenRCT2#16026]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (28c821f on develop) provided by GitHub

### Describe the issue

With the DIsable Vehicle Limits cheat enabled, the go-cart ride defaults to 32 cars and 12 cars per train, which is an unusual configuration that breaks the ride. 

If you add more than 1 car per train to the go-cart, the cars behind the lead car will randomly change lanes instead of following the lead car, and frequently clip into each other causing the entire train to hang up on itself, leaving the guests indefinitely stuck on the ride. 

It should probably default to a more standard configuration. I'm not sure if it was intended that you could have multiple car trains on the go-cart, but it would be very cool if this worked properly, you could get "train racing" effects -- I wouldn't want this option simply removed, just fixed and not used as a default case

### Steps to reproduce

1. Build a go-cart ride
2. Enable "Disable vehicle limits" cheat
3. Increase the cars per train count greater than 1 (I tested this with 5, but imagine it would happen with lower counts
4. Open the ride

### Attachments

![image](https://user-images.githubusercontent.com/29904858/143664601-2d39eb80-c9c2-4831-af30-644e2e607b69.png)

**Comment by spacek531** [comment]
The cheat is marked as unstable because you can make configurations that don't work, just like this. The issue with some cars not receiving drivers also occurs with 2-seater cars.

**Comment by sjoerddebruin** [comment]
Was solved with #16744 as indicated above.
