### ISSUE TITLE
Can't start multiplayer server on Ubuntu 20.04.3

### ISSUE THREAD

**Issue by skyace65** [OpenRCT2/OpenRCT2#16032]
### Operating System

Ubuntu 20.04.3 LTS

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (, DEBUG) Linux (x86-64)

### Describe the issue

I'm unable to start a multiplayer server on Linode with Ubuntu for OpenRCT2. I've followed the exact instructions on the wiki page for multiplayer and this happens when I try and start the server.

```
root@localhost:/home# openrct2 host /home/21458 --port 11753 --headless
For security reasons, it is not recommended to run OpenRCT2 with elevated permissions.
[STEX916 ] Unable to export object.
[TARMAC  ] Object not found.
[TARMACB ] Object not found.
[PATHSPCE] Object not found.
[PATHDIRT] Object not found.
[ROAD    ] Object not found.
[PATHCRZY] Object not found.
[PATHASH ] Object not found.
openrct2 $ 
```

There are two maps I've tried starting this with, both of these give the exact same issue:
https://rctgo.com/downloads/view/paradise-pier.21458
https://rctgo.com/downloads/view/botany-breakers-finished.21397

### Area(s) with issue?

This bug is specific to multiplayer

### Steps to reproduce

1. Create a linode server for Ubuntu 20.04.3
2. `apt-get update` and `apt-get upgrade` the server
3. add the official OpenRCT2 release PPA (https://launchpad.net/~openrct2/+archive/ubuntu/master?field.series_filter=focal) and `apt-get update`
4. `apt-get install openrct2`
5. download one of the multiplayer maps with wget to the home folder
6. run the following command `openrct2 host /home/21458 --port 11753 --headless`

**Comment by Lastorder-DC** [comment]
Try [nightly build](https://launchpad.net/~openrct2/+archive/ubuntu/nightly). It's already fixed by #15975
Also this issue is duplicate of #15974

**Comment by Lastorder-DC** [comment]
Try [nightly build](https://launchpad.net/~openrct2/+archive/ubuntu/nightly)(develop branch)
bugs might already fixed at develop branch.

**Comment by skyace65** [comment]
> Try [nightly build](https://launchpad.net/~openrct2/+archive/ubuntu/nightly)(develop branch) bugs might already fixed at develop branch.

Just tried using nightly and it's working. I'll close this issue
