### ISSUE TITLE
path images in scenario editing

### ISSUE THREAD

**Issue by pjmk1** [OpenRCT2/OpenRCT2#16048]
### Operating System

Mac OS 10.14.6

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (15ee72a on develop)

### Describe the issue

by selecting the non standard pathtypes it shows totally different images (also by placing them)

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. creating new senario
2. selecting/hovering the non standard path types

### Attachments

<img width="987" alt="Schermafbeelding 2021-11-28 om 13 45 31" src="https://user-images.githubusercontent.com/95171833/143768405-7fa46381-f9ee-42e2-b9d7-99b329f3733f.png">

**Comment by Gymnasiast** [comment]
You’re trying to select RCT1 paths without having RCT1 loaded. That’s not going to work.

**Comment by Gymnasiast** [comment]
We have now introduced fallbacks for these kinds of objects, so your issue should now be solved.
