### ISSUE TITLE
Missing Terrain Tiles (Save Format Update)

### ISSUE THREAD

**Issue by ShyBay** [OpenRCT2/OpenRCT2#16042]
### Operating System

Windows 10 64 bit

### OpenRCT2 build

OpenRCT2-0.3.5.1-develop-15ee72a-windows-x64

### Describe the issue

Any Indev versions that I try to install are missing files that render the game unusable. Trying to start or load any scenario will fail with a screen appearing saying that assets are missing (mostly terrain files). The title screen also comes up being blank. Downgrading to the latest release or any Indev version which does not have the save format update works.

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Start the game.
2. Try to load a scenario or save file.
3. 

### Attachments

![Screenshot_91](https://user-images.githubusercontent.com/95152860/143725574-574cde4f-75b5-43c4-8e89-c5c14e97c492.png)

**Comment by duncanspumpkin** [comment]
You have not installed the game correctly. Uninstall fully and then install. You can't have files from old version and files from the new version otherwise this will happen

**Comment by ShyBay** [comment]
> You have not installed the game correctly. Uninstall fully and then install. You can't have files from old version and files from the new version otherwise this will happen

Solved. Thank you.
