### ISSUE TITLE
Screen doesn't look normal on start screen!

### ISSUE THREAD

**Issue by tylere661** [OpenRCT2/OpenRCT2#16043]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (28c821f on develop) provided by GitHub

### Describe the issue

![Unnamed park 2021-11-27 23-46-54](https://user-images.githubusercontent.com/91767481/143730031-bb105908-7944-4f89-8e5d-7a51e7608e84.png)
![Unnamed park 2021-11-27 23-46-44](https://user-images.githubusercontent.com/91767481/143730036-972f65f1-0790-4629-af4e-078deb3ac0d7.png)
The screen doesn't look normal at the startup screen and and on the edge of the screen!

### Area(s) with issue?

Building the game

### Steps to reproduce

1. 
![Unnamed park 2021-11-27 23-46-44](https://user-images.githubusercontent.com/91767481/143730071-729345d6-b894-4c6c-9202-bcc8cf0c0859.png)

2. 
![Unnamed park 2021-11-27 23-46-54](https://user-images.githubusercontent.com/91767481/143730075-23117093-9aac-4feb-b296-35189cf2777f.png)

3. 

### Attachments

![Unnamed park 2021-11-27 23-46-44](https://user-images.githubusercontent.com/91767481/143730086-4d54087d-6d29-48ac-b1d5-d48e1f6dc44d.png)
![Unnamed park 2021-11-27 23-46-54](https://user-images.githubusercontent.com/91767481/143730087-2c118a6f-f435-456c-9af2-b4fbe0c89b29.png)

**Comment by Gymnasiast** [comment]
Your installation is broken. Please uninstall OpenRCT2 and then reinstall it. Your saves and progress should not be affected.

**Comment by Gymnasiast** [comment]
Since there has been no reply, assuming your question has been answered.
