### ISSUE TITLE
AppImages are broken/outdated

### ISSUE THREAD

**Issue by LordGaav** [OpenRCT2/OpenRCT2#16047]
### Operating System

Ubuntu 20.04 (AppImage uses 18.04 dependencies)

### OpenRCT2 build

OpenRCT2, v0.3.5.1

## Issue and debugging
I ran into an issue using the ParkRatingInspector plugin. After a bit of debugging, it seems that plugin uses a function (`Number.parseInt`), and support for that function was introduced in Duktape 2.3 .

When running the game from the latest stable AppImage (0.3.5.1), an error is logged about `Number` being undefined. This seems to indicate that the AppImage is shipping an outdated version of Duktape. For my initial bugreport on the ParkRatingInspector plugin, see: https://github.com/Basssiiie/OpenRCT2-ParkRatingInspector/issues/15 .

Debugging this was a bit daunting, because `scripts/linux/build-appimage-docker.sh` mentions `openrct2/openrct2:ubuntu_amd64` as build image, but the Github Actions mention `openrct2/openrct2-build:latest` . When I run that last image and check which version of Duktape is installed, it shows:

```
# cat /etc/issue
Ubuntu 18.04.5 LTS \n \l
# dpkg -l | grep duktape
ii  duktape-dev                     2.2.0-3                             amd64        embeddable Javascript engine, development files
ii  libduktape202:amd64             2.2.0-3                             amd64        embeddable Javascript engine, library
```

Whereas on my up-to-date workstation, it shows:
```
$ cat /etc/issue
Ubuntu 20.04.3 LTS \n \l
$ dpkg -l | grep duktape
ii  duktape-dev                                2.5.0-1                                         amd64        embeddable Javascript engine, development files
ii  libduktape205:amd64                        2.5.0-1                                         amd64        embeddable Javascript engine, library
```

## Possible solution?
It looks to me that the AppImage should be generated using the latest LTS version of Ubuntu. This should not cause any problems, and because all dependencies get bundled the newer version of Duktape will also be available on older versions of Ubuntu.

Note: the tarball download also does not run on Ubuntu 20.04, because it expects the Duktape version from Ubuntu 18.04 (and other dependencies):
```
$ ./openrct2
./openrct2: error while loading shared libraries: libduktape.so.202: cannot open shared object file: No such file or directory
$ ldd openrct2 | grep "not found"
        libduktape.so.202 => not found
        libduktape.so.202 => not found
        libicuuc.so.60 => not found
        libzip.so.4 => not found
```

## Workaround for now
The only way for me to run OpenRCT2 with the plugins I want on Ubuntu 20.04 is to build it myself, or running the nightly build PPA (with potential for broken releases).

### Area(s) with issue?

Building the game

### Steps to reproduce

1.  Download latest available AppImage (0.3.5.1).
2.  Download ParkRatingInspector plugin https://github.com/Basssiiie/OpenRCT2-ParkRatingInspector/releases/tag/v0.2
3.  Run game.
4. Try to open ParkRatingInspector dialog.
5. Note the error in the console:
```
[ParkRatingInspector] TypeError: undefined not callable (property 'parseInt' of [object Function])
```

**Comment by Gymnasiast** [comment]
Will be solved by https://github.com/OpenRCT2/OpenRCT2/issues/14259 .
