### ISSUE TITLE
Objects appear as green triangles

### ISSUE THREAD

**Issue by JbartRCT** [OpenRCT2/OpenRCT2#16057]
### Operating System

Windows-10, 64 and 84 bits

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (7037524 on develop) provided by GitHub

### Describe the issue

Hello, I have tried to play Open RCT2, but a lot of the objects are appearing as green triangle sprites, including objects already a part of the original RCT2, so it is not just custom objects. How do I go about correcting this issue?

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Screenshot taken of current park
2. 
3. 
![Legacy World 2021-11-28 23-10-22](https://user-images.githubusercontent.com/95201467/143807684-e7aadb43-c972-4a72-8a81-2a8e72779f92.png)

### Attachments

![Legacy World 2021-11-28 23-10-22](https://user-images.githubusercontent.com/95201467/143807769-54563d58-1d73-4b27-8a5d-edd608f99707.png)

**Comment by duncanspumpkin** [comment]
Is this an rct1 park or using rct1 features?

**Comment by Gymnasiast** [comment]
It is, there is a purple-with-grey-tiles thing on the right which uses RCT1 land. But that also shows the RCT1 assets load correctly. (Unloaded RCT1 assets cause massive graphic disruption, not just a few green squares).

@JbartRCT Did you select a lot of objects?

**Comment by JbartRCT** [comment]
Hello,

I selected quite a few objects, but did not select more than half of the new allotted amount for the new save format. I did select some custom items as well. 

Jonathan

**Comment by Gymnasiast** [comment]
Unfortunately, the engine has a limit on how much images it can handle at the same time. This limit is reached way before you max out all the slots and could in fact be reached even when the SV6 limits were still in place. We are working on changing our engine to handle more images, but that is a large job.

**Comment by JbartRCT** [comment]
That makes sense. I’ll make sure to check less items and see if that helps. Will definitely follow-up, but thank you for letting me know. Keep up the amazing job on this project. This was one of my first computer games as a kid, and now you’ve made it such a better experience. 

Sincerely,

Jonathan

**Comment by Gymnasiast** [comment]
@JbartRCT We merged a commit today that increases the image limit. Could you test if this solves the problem for you?

**Comment by JbartRCT** [comment]
It does! I am able to add several more objects without trouble. 

Thank you so much! Keep up the awesome job. 

Jonathan
