### ISSUE TITLE
Entrances and exits for flat rides don't connect to footpaths

### ISSUE THREAD

**Issue by LRFLEW** [OpenRCT2/OpenRCT2#1605]
Basically the title. It's likely something that has been changed recently. Possibly from the fix for #1601?

![scr2](https://cloud.githubusercontent.com/assets/607715/8663121/f0c6338c-298c-11e5-8896-947499c778c5.png)

**Comment by LRFLEW** [comment]
This issue isn't fixed for me, just changed. 
![scr6](https://cloud.githubusercontent.com/assets/607715/8665176/912c3bfa-29a6-11e5-8d8f-a400f547eb31.png)

**Comment by daihakken** [comment]
Can confirm that it's not fixed.
