### ISSUE TITLE
Saving scenery with track design is saved in the wrong location

### ISSUE THREAD

**Issue by Cens0rs** [OpenRCT2/OpenRCT2#16075]
### Operating System

Windows 10 64 bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (61c67af) provided by GitHub

### Describe the issue

Saving a track design with Scenery included does not save the scenery next to the ride. In fact it saves the scenery incredibly far away on master. It still happens on develop if you do it on the old save format in an old save(.SV6). Oddly you can still reproduce this bug after you convert it to .park. On a completely new save on new save format, you cant save track designs with scenery at all as an error appears but that is a separate issue documented here: #16019

![Screenshot_525](https://user-images.githubusercontent.com/33385351/143985670-e2d81b9b-2bdd-414e-b7d0-c7f4031560a9.png)

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Build a track design. (Tested with Launched Freefall)
2. save with scenery
3. if old save format, then go to saved ride in ride menu and observe scenery far away from ride
3b. if NSF, observe error that says "too much scenery or too far away" (#16019 )

### Attachments

![Screenshot_522](https://user-images.githubusercontent.com/33385351/143986107-38eedf37-7bc0-4c95-9a90-609ceaafea92.png)
![Screenshot_523](https://user-images.githubusercontent.com/33385351/143986113-e8dd9383-0612-4902-9958-cf5394dfb151.png)
![Screenshot_526](https://user-images.githubusercontent.com/33385351/143986124-debf2979-426b-4e5b-9e7c-5836c37bc30b.png)
![Screenshot_524](https://user-images.githubusercontent.com/33385351/143986141-620c31d8-aac1-4cee-995c-e6becbcc41a0.png)

**Comment by Cens0rs** [comment]
NSF was tested with v0.3.5.1-15ee72a

**Comment by duncanspumpkin** [comment]
Was the original ride located at a position outside of the old map size. I.e. is it further than 256 tiles. I can see that we don't handle scenery located at an x or y >256.

**Comment by Cens0rs** [comment]
@duncanspumpkin to answer your original question to help diagnose #16019 I'm not sure. There is a good chance as it is a custom scenario that is 999x999.
