### ISSUE TITLE
Tile inspector hotkeys mapped incorrectly

### ISSUE THREAD

**Issue by fidwell** [OpenRCT2/OpenRCT2#16083]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (fb9d02c on develop) provided by GitHub

### Describe the issue

Basically #15928 happened again. Probably due to reorganizing the Tile Inspector widgets when the "invisible" button was removed.

### Steps to reproduce

1. Assign hotkeys to the tile inspector.
2. Open the TI and attempt to use the hotkeys.
3. Hotkeys don't do anything or perform the wrong action.

**Comment by Broxzier** [comment]
Whoops, my bad. Shows how much I use those hotkeys myself.
