### ISSUE TITLE
Entrances/Exits of flat rides disappeared after quitting the construction window

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#1608]
![1](https://cloud.githubusercontent.com/assets/13048125/8665684/4d11068a-2a19-11e5-9bc0-e09fc2a514cd.PNG)
![2](https://cloud.githubusercontent.com/assets/13048125/8665683/4d0b3bba-2a19-11e5-82e2-3820f96e45e4.PNG)

build tested: [b990](https://openrct2.com/download/990) from openrct2.com

**Comment by duncanspumpkin** [comment]
Duplicate of #1603.
