### ISSUE TITLE
Paths texture invisible in latest develop build.

### ISSUE THREAD

**Issue by P0rtal-guy** [OpenRCT2/OpenRCT2#16090]
### Operating System

Windows 10 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (79b12d2 on develop) provided by GitHub

### Describe the issue

Paths are invisible in the newest develop version.
![Forest Frontiers 2021-12-01 22-06-56](https://user-images.githubusercontent.com/79942024/144350716-2e2575d2-7b6b-471c-8429-d7272fc65e5d.png)
 

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Open a rct1 map that uses rct1 paths
2. draw a path THAT IS NOT THE REGULAR ASPHALT PATH.
3. open an rct1 map and see all the path invisibl
![Dynamite Dunes 2021-12-01 22-10-42](https://user-images.githubusercontent.com/79942024/144350909-5587ed51-3017-4143-87cf-b6aa72700277.png)
e

**Comment by duncanspumpkin** [comment]
That is expected behaviour if you do not have rct1 linked.
