### ISSUE TITLE
Build fails on s390x ("error Unknown endianness!")

### ISSUE THREAD

**Issue by gibmat** [OpenRCT2/OpenRCT2#16096]
### Operating System

Debian sid, s390x

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (also very likely v0.3.5.1)

### Describe the issue

OpenRCT2 was just accepted into the Debian archive today (yay!) and is hitting the various builders (https://buildd.debian.org/status/package.php?p=openrct2) The s390x build is failing with the following error:

```
[  0%] Building CXX object CMakeFiles/libopenrct2.dir/src/openrct2/CmdlineSprite.cpp.o
/usr/bin/c++ -DOPENGL_NO_LINK -DUSE_BENCHMARK -D__WARN_SUGGEST_FINAL_METHODS__ -D__WARN_SUGGEST_FINAL_TYPES__ -I/<<PKGBUILDDIR>> -I/<<PKGBUILDDIR>>/libopenrct2 -isystem /usr/include/freetype2 -isystem /usr/include/libpng16 -isystem /usr/include/uuid -isystem /<<PKGBUILDDIR>>/src/openrct2/../thirdparty -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2 -fstrict-overflow -fstrict-aliasing -Werror -Wundef -Wmissing-declarations -Winit-self -Wall -Wextra -Wshadow -Wno-unknown-pragmas -Wno-missing-braces -Wno-comment -Wnonnull -Wno-unused-parameter -DDEBUG=0 -fPIC -Wsuggest-override -Wduplicated-cond -Wnon-virtual-dtor -Wduplicated-branches -Wrestrict -Wmissing-field-initializers -Wlogical-op -Wold-style-cast -Wunused-const-variable=1 -Wno-clobbered -Wredundant-decls -Wnull-dereference -Wsuggest-final-types -Wsuggest-final-methods -Wignored-qualifiers -Wstrict-overflow=1 -D__ENABLE_LIGHTFX__ -DENABLE_SCRIPTING -std=gnu++17 -MD -MT CMakeFiles/libopenrct2.dir/src/openrct2/Cheats.cpp.o -MF CMakeFiles/libopenrct2.dir/src/openrct2/Cheats.cpp.o.d -o CMakeFiles/libopenrct2.dir/src/openrct2/Cheats.cpp.o -c /<<PKGBUILDDIR>>/src/openrct2/Cheats.cpp
/usr/bin/c++ -DOPENGL_NO_LINK -DUSE_BENCHMARK -D__WARN_SUGGEST_FINAL_METHODS__ -D__WARN_SUGGEST_FINAL_TYPES__ -I/<<PKGBUILDDIR>> -I/<<PKGBUILDDIR>>/libopenrct2 -isystem /usr/include/freetype2 -isystem /usr/include/libpng16 -isystem /usr/include/uuid -isystem /<<PKGBUILDDIR>>/src/openrct2/../thirdparty -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2 -fstrict-overflow -fstrict-aliasing -Werror -Wundef -Wmissing-declarations -Winit-self -Wall -Wextra -Wshadow -Wno-unknown-pragmas -Wno-missing-braces -Wno-comment -Wnonnull -Wno-unused-parameter -DDEBUG=0 -fPIC -Wsuggest-override -Wduplicated-cond -Wnon-virtual-dtor -Wduplicated-branches -Wrestrict -Wmissing-field-initializers -Wlogical-op -Wold-style-cast -Wunused-const-variable=1 -Wno-clobbered -Wredundant-decls -Wnull-dereference -Wsuggest-final-types -Wsuggest-final-methods -Wignored-qualifiers -Wstrict-overflow=1 -D__ENABLE_LIGHTFX__ -DENABLE_SCRIPTING -std=gnu++17 -MD -MT CMakeFiles/libopenrct2.dir/src/openrct2/CmdlineSprite.cpp.o -MF CMakeFiles/libopenrct2.dir/src/openrct2/CmdlineSprite.cpp.o.d -o CMakeFiles/libopenrct2.dir/src/openrct2/CmdlineSprite.cpp.o -c /<<PKGBUILDDIR>>/src/openrct2/CmdlineSprite.cpp
In file included from /<<PKGBUILDDIR>>/src/openrct2/Cheats.h:13,
                 from /<<PKGBUILDDIR>>/src/openrct2/Cheats.cpp:10:
/<<PKGBUILDDIR>>/src/openrct2/common.h:96:10: error: #error Unknown endianness!
   96 | #        error Unknown endianness!
      |          ^~~~~
In file included from /<<PKGBUILDDIR>>/src/openrct2/CmdlineSprite.h:13,
                 from /<<PKGBUILDDIR>>/src/openrct2/CmdlineSprite.cpp:10:
/<<PKGBUILDDIR>>/src/openrct2/common.h:96:10: error: #error Unknown endianness!
   96 | #        error Unknown endianness!
      |          ^~~~~
```

 (Full log available at https://buildd.debian.org/status/fetch.php?pkg=openrct2&arch=s390x&ver=0.3.4.1%2Bds-1&stamp=1638473733&raw=0)

Unfortunately I don't have access to a porter box for s390x, but based on the macros in that header, I'm guessing that if some logic were added to handle big-endian systems the build would succeed.

(An upload of v0.3.5.1 is pending, but I expect the same failure.)

### Area(s) with issue?

Building the game

### Steps to reproduce

1. Try to build on a big-endian system

**Comment by janisozaur** [comment]
While we technically can fix this issue, be aware due to scarcity of such systems, big endian platforms are not supported.

What's your use case for this platform, are you going to submit patches to improve BE support? Is anyone going to actually use it? Without those I fear compiling OpenRCT2 for s390x is just a waste of cycles.

**Comment by janisozaur** [comment]
Or in other words: I would rather disable support for s390x than work on fixing that compilation issue. Do you know how we can achieve that?

**Comment by ZehMatt** [comment]
I think the idea is to not support BE architectures in the long run, we would need to start adding bswap everywhere when it comes to I/O. We sort of support in the code here and there but we decided to not follow this any further a while back. @IntelOrca what do you think?

**Comment by IntelOrca** [comment]
We would first need a CI and good way to test and develop on BE, before we can start fixing issues.

**Comment by Krutonium** [comment]
> We would first need a CI and good way to test and develop on BE, before we can start fixing issues.

I could easily set up an old PowerBook on Linux, a BE system, and provide SSH access if that would help with this.

**Comment by janisozaur** [comment]
Still, however much I like porting stuff, I don't see a compelling reason to pursue this - no user reports indicate BE platforms being used to play OpenRCT2. I would still rather explicitly mark BE as unsupported, at least until more users convince us otherwise.

**Comment by janisozaur** [comment]
Also, as mentioned in chat earlier, this has to take into account upcoming migration to C++20: https://github.com/OpenRCT2/OpenRCT2/issues/15501

**Comment by gibmat** [comment]
> While we technically can fix this issue, be aware due to scarcity of such systems, big endian platforms are not supported.
>
> What's your use case for this platform, are you going to submit patches to improve BE support? Is anyone going to actually use it? Without those I fear compiling OpenRCT2 for s390x is just a waste of cycles.

Fair enough; big-endian systems certainly aren't as common these days. s390x is one of Debian's [officially supported architectures](https://wiki.debian.org/SupportedArchitectures), so it would be nice if openrct2 was available to be built for it, but I also understand the desire to focus on systems that are being used. I can disable the build for that architecture and add a note to the package's documentation that big-endian systems are currently unsupported.

> I could easily set up an old PowerBook on Linux, a BE system, and provide SSH access if that would help with this.

Thanks for the offer; for now consensus seems to be that big-endian systems aren't supported, so I won't take you up on that.

I think for now I'll close this bug report, but if we ever get to a point where big-endian systems are supported, I'll be very happy to re-enable that build for Debian packaging!

**Comment by pkubaj** [comment]
Note that there are other systems that support BE. While I doubt anyone plays openrct2 on s390x, ppc and ppc64 is widely available and big-endian.
It's also supported by FreeBSD, OpenBSD, Void and Gentoo.

**Comment by ZehMatt** [comment]
> Note that there are other systems that support BE. While I doubt anyone plays openrct2 on s390x, ppc and ppc64 is widely available and big-endian. ppc and ppc64 are supported by FreeBSD, OpenBSD, Void and Gentoo.

Its out of the question if such systems exist or not, someone has to maintain the code and also the CI needs to somehow support this platform/architecture.

**Comment by pkubaj** [comment]
Travis apparently supports s390x: https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z
I see no mention of ppc64 and ppc, though, but I suppose that if things work on s390x, they will also work on ppc64 and ppc.
