### ISSUE TITLE
Game freezing at regular intervals

### ISSUE THREAD

**Issue by shplim** [OpenRCT2/OpenRCT2#16108]
### Operating System

Windows 10 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (5f9d03e on develop) provided by GitHub

### Describe the issue

Landscape size 999x999, land owned by park ~99.999%. No rides or scenery have been placed, grass is automatically cut. Only one (default) park entrance

Game seems to freeze for 3-4 seconds every 12-13 seconds. It might have something to do with the grass cutting as, on some tests, in the land not owned by the park, the grass starts to get messier to a certain point, the game freezes, and then it resets back to nicely cut grass

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Make a 999x999 park with land totally owned (and with only the Streamlined Monorail selected extra to the default rides available)
2. Add a park entrance (default) right at the edge of the park with one tile unowned to allow visitors to enter the map
3. Save map
4. Play map

**Comment by oli414** [comment]
> grass is automatically cut

What plugin are you using?

**Comment by shplim** [comment]
Ahhhh, yes I'm using plugins... sorry, it's been a while. I've removed it and it works properly now.
Just in case it helps, I was using 'mow_grass_daily', though I can't remember where I got it from

Thanks
________________________________

**Comment by oli414** [comment]
Cool, in that case, make sure to open an issue on this page:
https://github.com/RGBrewer/OpenRCT2-Mow-Grass/issues

I'm closing this issue as it is not a issue with OpenRCT2 itself.
