### ISSUE TITLE
Coasters crash even when test crashes disabled

### ISSUE THREAD

**Issue by Phasedetect** [OpenRCT2/OpenRCT2#1610]
Replicate: Build any incomplete coaster, put it into test mode, let the first train roll out of the station, then close the ride. The train will crash, presumably because the ride is no longer in test mode.

**Comment by sjoerddebruin** [comment]
That is expected behaviour it seems.

**Comment by Phasedetect** [comment]
@sjoerddebruin I agree that it makes sense why it happens. But I think that if the expectation was that the train won't crash if test crashes are disabled, and the train pulled out of the station in test mode, then it shouldn't crash at all during that run.

**Comment by duncanspumpkin** [comment]
This will be addressed when vehicle update has been implemented. Don't expect that until after 0.0.3.

**Comment by janisozaur** [comment]
`requires more implementation` should be removed with vehicle update now merged. And it should probably get `bug` label.

**Comment by duncanspumpkin** [comment]
This is no longer possible with the ghost trains.
