### ISSUE TITLE
Park Crashes on Opening

### ISSUE THREAD

**Issue by SquirreIKiller** [OpenRCT2/OpenRCT2#16112]
### Operating System

Windows 11, 64-bit

### OpenRCT2 build

Latest develop build

### Describe the issue

Downloaded park crashes shortly after loading.

### Steps to reproduce

1. Open Park
2. Wait

### Attachments

[200425-rct2-collabo-geauga_ocean_city (2).zip](https://github.com/OpenRCT2/OpenRCT2/files/7653231/200425-rct2-collabo-geauga_ocean_city.2.zip)

**Comment by Gymnasiast** [comment]
“Latest develop build” is not acceptable as a build number, I’m afraid. We need an actual number. It can be copied from the “About OpenRCT2” window.

**Comment by SquirreIKiller** [comment]
I rewrote the issue with the proper build this time.

**Comment by Gymnasiast** [comment]
Next time, please edit the issue - don’t close it and then open a new one.
