### ISSUE TITLE
Cannot open .PARK saves from during development

### ISSUE THREAD

**Issue by DDRJake** [OpenRCT2/OpenRCT2#16125]
### Operating System

Windows 10, 64 Bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1(ac0ee43 on develop)

### Describe the issue

I have a .park savegame I was playing during the test development of the new save format for OpenRCT2.  As of the late November release of the new savegame format version, I have not been able to load this save.

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Download and extract the attached .PARK save files
2. attempt to launch any of them from the title screen of OpenRCT2
3. Notice that the map fails to load, and you are returned to the title screen

### Attachments

[OpoenRCT2 unloadable saves.zip](https://github.com/OpenRCT2/OpenRCT2/files/7655818/OpoenRCT2.unloadable.saves.zip)

**Comment by Gymnasiast** [comment]
We warned that saves created with the test versions might not be readable with the version that eventually got merged on 21 November. Nevertheless, a team member might still take a look, although we can not guarantee anything.

**Comment by spacek531** [comment]
Is this issue still relevant?

**Comment by DDRJake** [comment]
Definitely not.
________________________________
