### ISSUE TITLE
Track Placement Desync Of Ride Type

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#16123]
### Operating System

Windows 10, 64bit

### OpenRCT2 build

unknown presumably ac0ee43

### Describe the issue

In multiplayer when one player is placing track and another is placing a track design the player placing tracks ride type will change to the track designs ride type. I've not verified this myself only had this reported to me.

### Area(s) with issue?

This bug is specific to multiplayer

### Steps to reproduce

1. Multiplayer game with 2+ players
2. One player in track construction mode.
3. One player in track design placement mode.
4. Track design player places design.
5. Track construction player has incorrect track.

**Comment by fidwell** [comment]
I think this is the same bug as #13997
