### ISSUE TITLE
 Cannot build the saved pre-built with scenery (doesn't show any scenery)

### ISSUE THREAD

**Issue by andy55699** [OpenRCT2/OpenRCT2#16131]
### Operating System

Windows 10,64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (61c67af) provided by GitHub

### Describe the issue

When saving a ride with scenery, I cannot reproduce/ build the saved pre-built with scenery ( that it doesn't show any scenery).

### Area(s) with issue?

Building the game

### Steps to reproduce

1. Save a ride with scenery
2. Cannot build the saved pre-built with scenery (doesn't show any scenery)

### Attachments

![ii](https://user-images.githubusercontent.com/92691705/144754140-cfb26bca-d860-4cdb-a9b7-a384fef3dc2c.png)
![iii](https://user-images.githubusercontent.com/92691705/144754143-5966120a-13fe-4a89-b476-e642c7e23f43.png)
![iv](https://user-images.githubusercontent.com/92691705/144754144-2b431527-c1db-446e-8d00-abc6ee87a8ed.png)
![vi](https://user-images.githubusercontent.com/92691705/144754146-e6552707-4336-4cb4-91b7-0a6f2e3d6739.png)

**Comment by Cens0rs** [comment]
This is fixed in develop.
