### ISSUE TITLE
Issue with text characters

### ISSUE THREAD

**Issue by GuidingKeyblade** [OpenRCT2/OpenRCT2#16143]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.3.4.1 (5087e77) provided by GitHub

### Describe the issue

There's an issue with text characters being incorrect. Lowercase L is replaced with a j, and lowercase j is replaced with some sort of currency symbol. There may be other text characters that are incorrect, but these are the ones I have found.

### Steps to reproduce

This just started right after I updated the game, I have no idea what caused it.

### Attachments

![OpenRCT2 12_6_2021 6_08_22 PM](https://user-images.githubusercontent.com/95659719/144937971-77e496e9-5128-46ab-9fe6-5bbd11801871.png)

**Comment by Gymnasiast** [comment]
Your g2.dat file is mismatched. You need to download or build one that matches your OpenRCT2 version.

(Btw, notecthat v0.3.4.1 is not the most recent release. That would be v0.3.5.1.)
