### ISSUE TITLE
Refactor all bound_box calls to use the same structure

### ISSUE THREAD

**Issue by frutiemax** [OpenRCT2/OpenRCT2#16146]
There are many places where a bound_box is declared for flat rides, i.e. `swinging_ship_bound_box`, `rct_crooked_house_bound_box`, etc. To avoid code duplication, a `BoundBoxXY` structure should be declared with `CoordsXY Offset` and `CoordsXY Length` fields.

**Comment by kiwi515** [comment]
Hello! I am a college student looking to contribute to open source software for a school project. Could I work on this and issue #14093 if they are both open still? They both seem to have progress but seem to be currently stalled.

Thanks in advance

**Comment by tupaschoal** [comment]
Those are a bit stale, yeah, but they seem to not have many issues, other than rebasing and solve merge conflicts. I'll try to get to them in the next few days, if you can look for other issues in the meantime, it would be great

**Comment by tupaschoal** [comment]
The money32 one definitely seems like we can get it going from the already open PR. I couldn't look at the other one yet, but my recommendation still stands, to look into other issues.
