### ISSUE TITLE
Queues from two different rides can connect together

### ISSUE THREAD

**Issue by LRFLEW** [OpenRCT2/OpenRCT2#1614]
If you put the queues in the right location, you can place a queue block that connects to both ride's queues and causes strange behavior.

![scr8](https://cloud.githubusercontent.com/assets/607715/8682223/693c0978-2a31-11e5-9889-6dcf6e033cba.png)
![scr9](https://cloud.githubusercontent.com/assets/607715/8682225/6afa9b80-2a31-11e5-9cdb-449fcf3ffe8c.png)

I'm reporting this because this issue interacts with #1615 strangely. I have tested this in the original version, and it is an original bug.

**Comment by Gymnasiast** [comment]
Not a bug. It's invalid queue placement from the user. How is the game supposed to handle that "correctly"?

**Comment by IntelOrca** [comment]
I suppose he is expecting it to not merge two queues of different rides.

**Comment by Gymnasiast** [comment]
Yes, but this behaviour is expected, as queues aren't meant to be connected like this. Any other behaviour is equally valid or invalid.

**Comment by RollingStar** [comment]
>Not a bug. It's invalid queue placement from the user. How is the game supposed to handle that "correctly"?

There's no good way to handle this, but maybe this would be better:

![image](https://cloud.githubusercontent.com/assets/4810902/8707528/444bc24c-2b04-11e5-8dba-bc061d7c111e.png)

Those middle tiles would be regular path tiles, just like how you can place a queue path not near any ride and have guests walk over it normally. Might have to remove the fence graphics on those three squares.

**Comment by AaronVanGeffen** [comment]
That seems really counter-intuitive to me. More importantly, how do you suppose guests get in line?

**Comment by IntelOrca** [comment]
I think it should not merge the two queue lines, their edges will not connect.

**Comment by Patrik356b** [comment]
@IntelOrca Agreed

**Comment by Christipher** [comment]
honestly I would like to see the queues able to split at that point (make it such that when the queues do that it creates that initially but then when that path from the mid point is done that the path splits up and then you have a ride that can use multiple queues (those queues will also move twice as fast until you get to the splitter)

**Comment by PFCKrutonium** [comment]
So basically you could do one queue for one ride, or, many queues for one ride?

**Comment by Gymnasiast** [comment]
I think he means the kind of queue that racing roller coasters have: one queue that at same point splits up between the two stations.

**Comment by PFCKrutonium** [comment]
So basically this?
![scr24](https://cloud.githubusercontent.com/assets/3945538/8738395/ba174e9e-2bfc-11e5-9de3-067f667d5885.png)

**Comment by Christipher** [comment]
in a way, yeah, where the junction would be is where you would have the connection between the two paths.  At the same time however I would not use it for any other purpose (i.e. the one above would be a blatant abuse of it, in reality those would have separate queues).

**Comment by vzybilly** [comment]
I could really see it being useful for racing rides... where the two are the same ride but different entrances, I would see it as an amazing thing for that. though, mostly unknown... maybe we could do a tips and tricks page or something... it would need to be in-game for it though...

**Comment by IntelOrca** [comment]
This queue split feature would have to wait until after we can change structures. Although this might be possible with not too much work for a racing roller coaster where both stations are the same ride.

**Comment by LRFLEW** [comment]
Issue #1724 had the same source as this one, and the fix for it resolved this issue as well. I'm closing this issue as it appears to be resolved.
