### ISSUE TITLE
Declare a BoundBoxXYZ structure

### ISSUE THREAD

**Issue by frutiemax** [OpenRCT2/OpenRCT2#16152]
In many functions, a bound box is described by an offset and length as function parameters (see `PaintAddImageAsChild`). I suggest to declare a `BoundBoxXYZ` structure with `CoordsXYZ Offset` and `CoordsXYZ Length` fields and use it in the places needed.

**Comment by Iikorni** [comment]
Should this involve collapsing/refactoring out some of the redundant overrides of functions like `PaintAddImageAsChild`? (e.g. the override where all the offsets and bounding box parameters are listed component-wise as integers (`Paint.h:297`))

**Comment by duncanspumpkin** [comment]
> Should this involve collapsing/refactoring out some of the redundant overrides of functions like `PaintAddImageAsChild`? (e.g. the override where all the offsets and bounding box parameters are listed component-wise as integers (`Paint.h:297`))

There is already an issue for that and a regex that needs run that will fix the whole codebase.

**Comment by Gymnasiast** [comment]
As far as I can see, this is finished.
