### ISSUE TITLE
Paint issue on Swinging Ship

### ISSUE THREAD

**Issue by DejaVu2001** [OpenRCT2/OpenRCT2#16155]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

[v0.3.5.1-bb35adc](https://github.com/OpenRCT2/OpenRCT2/commit/bb35adc5b8c38efe885889822e4aea3aba3e2e37)

### Describe the issue

Since updating to v0.3.5.1-bb35adc, the paint colors are no longer showing correctly on the Swinging Ship ride. Both the ship and the supports are colored the ship colors and the support color only impacts the fence color on the platform

### Steps to reproduce

1. Build Swinging Ship
2. Paint ship and supports different colors
3. Ship and supports are painted ship colors. Support color does nothing

### Attachments

![PaintBug](https://user-images.githubusercontent.com/20479466/145201796-42018c29-400a-4a85-a04d-49a2b5c8ac2e.jpg)

**Comment by Gymnasiast** [comment]
Summoning @IntelOrca .
