### ISSUE TITLE
Assertion Fail (with park file to reproduce =D)

### ISSUE THREAD

**Issue by MaxMallon** [OpenRCT2/OpenRCT2#16170]
### Operating System

Windows 10, 64bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (6e839bd on develop) provided by GitHub

### Describe the issue

An assertion popped up.
I wasn't doing anything, though the park I had loaded does contain a lot of trippy rides.
It didn't crash right away in the park though, only after like a minute after loading it.
It is reproducable, I tried it a few times, it crashes every single time, a bit after the rain stops. 

![Knipsel](https://user-images.githubusercontent.com/22072563/145480275-2ac37e63-8c99-4241-bc68-c5217ea56fb3.PNG)
 

### Steps to reproduce

1.  Open park
2. Wait ~30 seconds or so

### Attachments

[Painful hairpin.zip](https://github.com/OpenRCT2/OpenRCT2/files/7688648/Painful.hairpin.zip)

**Comment by James103** [comment]
To be more exact, the game crashes during the 783rd tick after loading the park.
Version: 0.3.5.1
Commit: 2d1af0e
Dump files: [12ed8925-d53a-49b0-bf49-486e2196aedb(2d1af0e_x86-64).zip](https://github.com/OpenRCT2/OpenRCT2/files/7695931/12ed8925-d53a-49b0-bf49-486e2196aedb.2d1af0e_x86-64.zip)

**Comment by csm10495** [comment]
This is caused by the merry-go-round with multiple entrances. I don't think that ride type is intended to support multiple entrances.

The guest who causes the crash is Eve W. They walk into one of the extra entrances.
