### ISSUE TITLE
Slow loading of soundfile freezes the game

### ISSUE THREAD

**Issue by Zombaya** [OpenRCT2/OpenRCT2#1617]
While opening my freshlybuild bumpercars ride, my game froze for 1 second.

I believe this was because my game is located on my HDD, which wasn't spinning because everything it needed was allready loaded and nothing was using my drive.  I think this froze the whole game as it tried to load the soundfile for the bumpercars ride which plays by default.

**Comment by IntelOrca** [comment]
It will stream the music from your disc, which is buffered in the process. Is the fact that it only froze for a second a big deal?

**Comment by Zombaya** [comment]
In my opinion it's not a big deal, since the game continued to function correctly afterwards.  

It's just something I noticed as strange behaviour. (Although it isn't that strange considering the age of the game)

**Comment by spacek531** [comment]
Has the changes to OpenRCT2's sound objects improved this experience?

**Comment by Zombaya** [comment]
I'm afraid I no longer have openRCT2 installed, nor regularly use a system with a HDD anymore so I'm not able to provide feedback around this.

**Comment by ZehMatt** [comment]
Considering how old this report is and no other complaints came in I assume this is fixed.
