### ISSUE TITLE
Tile inspector cannot make park fences invisible

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#16189]
### Operating System

Windows 11 Beta Insider

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (ceb49e0 on develop) provided by GitHub

### Describe the issue

When making a custom park I am trying to theme the park as void. The park fences cannot be hidden with the invisible tile selector.

### Steps to reproduce

1. Use a scenario with unowned land
2. Try to make the element invisible
3. Unowned land fences are part of the surface properties so they can only produce corrupted tiles when removed.

### Attachments

![2021-12-11 (2)](https://user-images.githubusercontent.com/94884086/145691615-3e528c01-d187-49a1-bb18-c53ed1e72232.jpg)
![2021-12-11 (1)](https://user-images.githubusercontent.com/94884086/145691619-f664a7d9-e818-46c4-a17a-a156cb6e94c8.jpg)

**Comment by Gymnasiast** [comment]
The option is right there in the Tile Inspector:

![afbeelding](https://user-images.githubusercontent.com/1478678/145693710-99c3730e-8b16-4684-83c7-6239626d53f9.png)

**Comment by 733737** [comment]
Sorry, I have legibility issues with my custom theme and scaling issues with 4k. I will make sure to be more diligent next time
