### ISSUE TITLE
make custom bitset

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#16198]
Regarding expanding the track groups field past 64 bits:

Apparently std::bitset is pretty shit, I looked up the documentation and only a single constructor has the constexpr keyword. We should probably build our own bitset in this case, fortunately that is rather easy to do.

_Originally posted by @ZehMatt in https://github.com/OpenRCT2/OpenRCT2/pull/16172#discussion_r767187978_

**Comment by spacek531** [comment]
Some food for thought

https://github.com/OpenRCT2/OpenRCT2/pull/16172/files/fddce7ec464aad7e702c56f17f37cb93a19f4a08#diff-6b352e47975b2b843c42863abe17579316bb6f101e0a296c2e2c36f93899f61c

**Comment by duncanspumpkin** [comment]
https://github.com/TheAssemblyArmada/Thyme/pull/387 this was a custom bitset used on Thyme that is built ontop of std::bitset. I'm not suggesting we copy it but it shows perhaps one way of doing it.

**Comment by spacek531** [comment]
Of all the bitset wrappers, that is one of them.

It appears that it will suffer from using `bitset<N>::set` which is *not* constexpr and therefore cannot be used, as far as my own experiments show.

**Comment by ZehMatt** [comment]
I started a bitset implementation a while ago, I'll see if I can get it done today.

**Comment by spacek531** [comment]
Will you be able to set bits higher than 64 at compile time with your implementation? Or will the rtds be reconfigured to be evaluated at runtime?

or is there a third option I don't know about to force non-constexpr functions to be evaluated during compilation?

**Comment by ZehMatt** [comment]
> Will you be able to set bits higher than 64 at compile time with your implementation? Or will the rtds be reconfigured to be evaluated at runtime?
> 
> or is there a third option I don't know about to force non-constexpr functions to be evaluated during compilation?

Yes that works, here is what I've got so far:
https://gist.github.com/ZehMatt/8d7ad140cc22a99449b33a43f8fa9c0f

**Comment by spacek531** [comment]
> Will you be able to set bits higher than 64 at compile time with your implementation?

> Yes that works, here is what I've got so far: https://gist.github.com/ZehMatt/8d7ad140cc22a99449b33a43f8fa9c0f

Where does this test occur? I don't see it.

**Comment by ZehMatt** [comment]
No where, I have to create PR first. I typically don't code the things directly in OpenRCT2 as its much easier to test and re-iterate on, unless I really have to.

**Comment by spacek531** [comment]
> directly in OpenRCT2

What are you talking about? All I want to know is if your bitset implementation can set bit 0x100000 in the initializer during compile time. Where does OpenRCT2 come into this?

**Comment by ZehMatt** [comment]
I already answered that.

**Comment by spacek531** [comment]
Good luck on your PR. I hope it works, because it didn't for me!
