### ISSUE TITLE
All awards show up as the "worst value park" award

### ISSUE THREAD

**Issue by ciscodisco1** [OpenRCT2/OpenRCT2#16197]
### Operating System

Windows 10 64bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (b83f7c3 on develop) provided by GitHub

### Describe the issue

I got 3 awards, but in the awards screen they all show up as the worst value park.

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Get awards
2. Check awards screen

### Attachments

![Coaster Dreams 2021-12-12 01-47-47](https://user-images.githubusercontent.com/31996583/145696376-90c1c049-ce29-42cd-8575-93a8947c44d4.png)

**Comment by IntelOrca** [comment]
@duncanspumpkin this might be related to the vector change.

**Comment by youngwii2** [comment]
I too have noticed this bug; at first I thought that this is why guests have been leaving the park.

This caused me to lower prices in the hopes that I would not get the worst value park award again, but I now feel reassured knowing that this seems to be a bug.

**Comment by duncanspumpkin** [comment]
Hmm how odd. The vector change was really quite simple but perhaps some arguments got swapped
