### ISSUE TITLE
Can't place any path

### ISSUE THREAD

**Issue by austinjb555** [OpenRCT2/OpenRCT2#1619]
![scr5](https://cloud.githubusercontent.com/assets/12687508/8688872/19c91dac-2a6f-11e5-86fb-a5373a664dfe.png)
Both buttons on the bottom of the footpath window depress when clicked but do not stay depressed once the mouse button is released.

**Comment by duncanspumpkin** [comment]
Any steps to reproduce?

**Comment by IntelOrca** [comment]
I can't reproduce this.

**Comment by Gymnasiast** [comment]
I vaguely recall something like this in an old build, so I guess it will be something like that.

**Comment by austinjb555** [comment]
It actually has resolved itself. I wasn't doing anything out of the ordinary, just building rides, and it wouldn't let me build path. It resolved when I closed the window and reloaded OpenRCT2.

**Comment by Gymnasiast** [comment]
Just had this again. It also affected the Clear Scenery tool. I'm not sure how to reproduce it yet, though.

**Comment by sjoerddebruin** [comment]
I've also had this issue, don't know what causes it.

**Comment by IntelOrca** [comment]
A similar issue, possible the same same is caused by placing the Splash Mine log flume track. The queue path is not completed connected.

**Comment by PFCKrutonium** [comment]
I had this happen about 20 minutes ago, and I have no idea how to re-produce.

**Comment by austinjb555** [comment]
I agree. This is happening randomly and resolving itself when you reload the scenario.

**Comment by jensj12** [comment]
It has happened to me a few times too. Fixed by building a station section of a new coaster with entrance and exit. After that it worked again. Last time it happened was after removing a ride entrance, but that doesn't reproduce it. It affects every tool that lets you place something (as far as I've tested), but not the build entrace/exit tool.

**Comment by Bouncer** [comment]
I've also had this bug occur many times. I think it is related to the fact that when you select the "bridge and tunnel footpath" button in the "Footpaths" window, the button gets deselected after constructing a path. However, I've not been able to reproduce the bug.

**Comment by IntelOrca** [comment]
We won't get any closer to fixing this until there we know the set of steps necessary to reproduce this reliably.

**Comment by PFCKrutonium** [comment]
I've been streaming a lot lately @IntelOrca - if I have it occur while on Stream I'll upload the Stream to YouTube and link it here for you guys to analyse.

**Comment by duncanspumpkin** [comment]
Has anyone been able to reproduce this recently?

**Comment by PFCKrutonium** [comment]
I had it happen a couple weeks ago, but I havn't had it happen in a while now.

**Comment by Broxzier** [comment]
I had this happen yesterday, and within only a minute of gameplay. I haven't been able to reproduce this yet though. All I remember is picking up someone, zooming out and moving the view around, and while having the person still picked up opening a tool.

**Comment by IntelOrca** [comment]
Just happened to me for the first time. Literally just went straight into scenario editor and tried to own some land.

**Observation:** It displays the map size label when trying to own land. Usually this gets hidden.

![image](https://cloud.githubusercontent.com/assets/1482259/11942464/a7dc955a-a82e-11e5-9c4c-71cde6f3160e.png)

**Comment by duncanspumpkin** [comment]
Yup can confirm. Technique to reproduce is open a window with a scroll bar click on scroll bar. Open a tool window. It will now be broken. To fix click on the main part of the scrollable window.

**Comment by IntelOrca** [comment]
AND FIXED!

**Comment by LinusU** [comment]
Awesome :clap: :clap:
