### ISSUE TITLE
Wooden supports for scenery are not drawn

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#16206]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

0.3.5.1 0a31d92

### Describe the issue

If you place scenery, wooden supports are not drawn
![image](https://user-images.githubusercontent.com/6469413/145725000-d49dd498-00ee-4d89-83e7-addcfafe37b1.png)

![image](https://user-images.githubusercontent.com/6469413/145725003-dae07aac-c6cd-49e0-ab81-5d34ca122b81.png)

![image](https://user-images.githubusercontent.com/6469413/145725040-79cde30b-24d9-49ad-9ba1-c16c0ce12d7e.png)

### Steps to reproduce

1.

**Comment by youngwii2** [comment]
Not sure if it is related, but I am also experiencing invisible supports with ride entrances/exits:

![Sandbox 2021-12-12 22-19-59](https://user-images.githubusercontent.com/52364182/145747272-c2375ed2-ead3-41fa-a2fc-31e33c203345.png)
