### ISSUE TITLE
Invisible entrance/exits render as tiny land sprites

### ISSUE THREAD

**Issue by Basssiiie** [OpenRCT2/OpenRCT2#16204]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (0a31d92 on develop) provided by GitHub

### Describe the issue

Invisible ride entrance/exits are not invisible, but are rendered as tiny grass sprites. 

### Steps to reproduce

1. Create a ride.
2. Switch entrance/exits to "no entrance" or "no entrance, no platform"
3. Admire the grass sprites.

### Attachments

![image](https://user-images.githubusercontent.com/20048660/145713641-a1ab2f56-a7d8-4641-8ce5-b43065d25522.png)

**Comment by ZehMatt** [comment]
Probably a regression of ImageId refactor
