### ISSUE TITLE
UX: couldn't figure out how to quit console

### ISSUE THREAD

**Issue by kevinburke** [OpenRCT2/OpenRCT2#1622]
I opened the console but I couldn't figure out how to get it to close, ending up quitting the game. 

I tried quitting it the same way you would quit most unix repl's - by trying `quit`, `exit`, and pressing `ctrl+d` (which usually sends a SIGQUIT to the running process). Unfortunately none of these worked. I ended up killing it by quitting the game.

Additionally it would be nice to have a small prompt about what to try if you are new. Here is an example:

<img src="https://api.monosnap.com/rpc/file/download?id=BZGU6uNZk3CIq8JTccuL9Kg0LhVYSb" />

**Comment by RollingStar** [comment]
I've done exactly this, but I can't get my version of the game to compile.

console.c: Print helpful information when console is first opened.

    void console_init()
    {
    	_consoleInitialised = true;
    	console_writeline(OPENRCT2_NAME " " OPENRCT2_VERSION);
    	console_writeline("");
    	console_writeline("Type hide and press Enter to hide this console, or type help and press Enter for more options.");
    	console_write_prompt();
    	console_writeline("");
    }

I avoid mentioning [SDL_SCANCODE_GRAVE](http://www.libsdl.org/tmp/SDL/include/SDL_scancode.h) (opens console) because it is mapped to different keys on different keyboards.

>Located in the top left corner (on both ANSI and ISO keyboards). Produces GRAVE ACCENT and TILDE in a US Windows layout and in US and UK Mac layouts on ANSI keyboards, GRAVE ACCENT and NOT SIGN in a UK Windows layout, SECTION SIGN and PLUS-MINUS SIGN in US and UK Mac layouts on ISO keyboards, SECTION SIGN and DEGREE SIGN in a Swiss German layout (Mac: only on ISO keyboards), CIRCUMFLEX ACCENT and DEGREE SIGN in a German layout (Mac: only on ISO keyboards), SUPERSCRIPT TWO and TILDE in a French Windows layout, COMMERCIAL AT and NUMBER SIGN in a French Mac layout on ISO keyboards, and LESS-THAN SIGN and GREATER-THAN SIGN in a Swiss German, German, or French Mac layout on ANSI keyboards.

**Comment by Patrik356b** [comment]
@Gymnasiast These special keys are the worst, it took me a long time to find out how to open debug/console window using the tilde key on a Scandinavian keyboard

**Comment by Gymnasiast** [comment]
@Patrik356b : There is no need anymore to use the keys, as both opening and closing the console can now be done by other means.
