### ISSUE TITLE
Rides buildable outside park on Factory Capers

### ISSUE THREAD

**Issue by lonemadman** [OpenRCT2/OpenRCT2#16229]
### Operating System

Windows 10, x64

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (cb6d741 on develop) provided by GitHub

### Describe the issue

It is possible to build flat rides outside of the park boundary on Factory Capers.

It is (correctly) not allowing path, scenery or landscaping to be placed outside the boundary.

No mods or edits made to OpenRCT2 - just a normal game.

### Steps to reproduce

1. Start new Factory Capers scenario 
2. It is possible to place rides outside of the park

Save file can be found here: https://1drv.ms/u/s!AgFsj6Ud307ij9t82G6ZSIfPjBewbQ?e=dc8bEm

### Attachments

![image](https://user-images.githubusercontent.com/96085994/145890484-3db269b1-6ac2-4e23-af78-38b8d7dfa7d8.png)

**Comment by duncanspumpkin** [comment]
Just to confirm are you doing this without the sandbox cheat enabled?

**Comment by lonemadman** [comment]
Sorry, correct - no cheats enabled

**Comment by Gymnasiast** [comment]
Works as intended - this scenario has construction rights in that area.
