### ISSUE TITLE
CTD when opening the prebuilt ride menu (Might have been reported in the Gitbot reports but I'm not sure)

### ISSUE THREAD

**Issue by sfisher923** [OpenRCT2/OpenRCT2#16232]
### Operating System

Linux Mint Cinnamon 20.2 "Uma" x64

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (, DEBUG) - Latest Nightly Build on Dev 

### Describe the issue

I open the Prebuilt Menu while working on my DKMP Secret Santa gift and the game freezes for a minute and crashes with 

"openrct2: /build/openrct2-IU8I58/openrct2-0.3.5.1-develop-0~3020-202112132017/src/openrct2/drawing/Drawing.cpp:70: uint8_t PaletteMap::Blend(uint8_t, uint8_t) const: Assertion `src != 0 && (src - 1) < _numMaps' failed.
                                                                     Aborted (core dumped)" as the Terminal Output

### Steps to reproduce

1. Open up a Scenario
2. Pick a Ride with Prebuilts
3. Crash

**Comment by duncanspumpkin** [comment]
Issue has been resolved.

In future please include the actual commit in the OpenRCT2 build detail. "Latest Nightly Build" means nothing.

**Comment by sfisher923** [comment]
My bad (Didn't know how to narrow down the version)

**Comment by janisozaur** [comment]
Launchpad builders sadly don't embed proper version info. You can extract the version from package instead.

**Comment by sfisher923** [comment]
Thanks will remember that next time
