### ISSUE TITLE
Incorrect station style shown in Track Design preview

### ISSUE THREAD

**Issue by Ian-Polito** [OpenRCT2/OpenRCT2#16234]
### Operating System

Linux (x86-64)

### OpenRCT2 build

OpenRCT2, v0.3.5.1

### Describe the issue

When selecting a track design, the preview shows the plain station style instead of the actual station style the ride was saved with. This only affects track designs using the Canvas Tent, Castle (Gray), and Castle (Brown) station styles.

### Steps to reproduce

1. Open Ride Building Menu
2. Select a track design
3. Check the preview for the ride

The following track designs that come with RCT2 can be used to check this:
Mouse Towers (Wooden Wild Mouse prebuilt that has Castle (Brown) station style)
Deja Vu (Compact Inverted Coaster prebuilt that has Canvas Tent station style)
Steel Squeak (Steel Wild Mouse prebuilt that has Castle (Gray) station style)

### Attachments

![Screenshot from 2021-12-13 20-51-12](https://user-images.githubusercontent.com/8570274/145919703-8c8fd4a2-3e6b-45fb-8dac-ce43e0847820.png)

**Comment by duncanspumpkin** [comment]
What commit was this on. I've checked on 35d4410fb5f and cannot reproduce this using the `Mouse Towers ` track design.

**Comment by Ian-Polito** [comment]
> What commit was this on. I've checked on [35d4410](https://github.com/OpenRCT2/OpenRCT2/commit/35d4410fb5f4860950745e41e0248ee609ead40f) and cannot reproduce this using the `Mouse Towers ` track design.

How can I tell which commit this is on? I'm using the AppImage release

**Comment by duncanspumpkin** [comment]
Does it not state it in the bottom left of the startup screen. 
![image](https://user-images.githubusercontent.com/1277401/145958254-30b29b30-a00b-4015-b0e2-5974c309d468.png)
It doesn't show on my setup as I'm building it in dev enviroment but this is where it would be.

**Comment by Ian-Polito** [comment]
![Screenshot from 2021-12-14 16-39-50](https://user-images.githubusercontent.com/8570274/146083668-d89a5045-a789-43c0-9649-c37af0fcf1b7.png)
No, it does not say there. It doesnt say in the 0.3.5 version I have installed from the distro's repos either.

**Comment by Gymnasiast** [comment]
Cannot reproduce this either, using 3faa0ebc4bd51e818e149966bdbe5275d95191cc. Could you try a recent `develop` build, @Ian-Polito ?

**Comment by Ian-Polito** [comment]
My bad, i just checked on develop (f23e843a2) I'll close the issue.
