### ISSUE TITLE
Linux Mint 17.2: Loading library libwinpthread-1.dll failed

### ISSUE THREAD

**Issue by RollingStar** [OpenRCT2/OpenRCT2#1626]
I'm encountering the same issue that KamilSJaron encountered in #585.

I'm using Linux Mint MATE 17.2 x64 ([full log](http://pastebin.com/hXk32Fhf)). I think I have the DLL (I downloaded it separately), but *I don't know where it should go*. I've used clean.sh, install.sh, and build.sh several times.

Downloading a precompiled build and loading the EXE with Wine works fine. My own compiled version does not.

    wine openrct2.exe
    err:module:import_dll Loading library libwinpthread-1.dll (which is needed by L"F:\\openrct2.dll") failed (error c000007b).
    err:module:import_dll Library openrct2.dll (which is needed by L"F:\\openrct2.exe") not found
    err:module:LdrInitializeThunk Main exe initialization for L"F:\\openrct2.exe" failed, status c0000135

Based on [build.sh](https://github.com/OpenRCT2/OpenRCT2/blob/develop/build.sh), it looks like my computer isn't getting to the end of build.sh. The final section,

    if [[ -t 1 ]]; then
        echo -e "\nDone! Run OpenRCT2 by typing:\n\n\033[95mwine openrct2.exe\n\033[0m"
    else
        ech    o -e "\nDone! Run OpenRCT2 by typing:\n\nwine openrct2.exe\n"
    fi

does not seem to be triggered (see log above).

**Comment by mzmiric5** [comment]
the echo doesn't get reached because we actually run openrct2.exe before it to generate g2.dat as part of the build process. Have you ran the clean.sh and install.sh before running build.sh ? There is no need for you to have that dll in the actual game folder since we are linking to it statically and it's shipped with mingw32 that we build with. This is the same issue that @Gymnasiast had and we literally updated the build system specifically for this issue to link statically to it. This is why I'm asking if you ran the clean and install scripts since that will make sure you have everything properly set up for it to build

**Comment by waylon531** [comment]
I had the same problem on arch linux. The package from the AUR worked fine but downloading and compiling it myself didn't. Creating a symbolic link to libwinpthread-1.dll in the directory with openrct2.exe made it work.

**Comment by mzmiric5** [comment]
@waylon531 yeah i guess that is sort of a solution, but there should really be no need to do that because of how we wrote the build. @RollingStar i still don't know if you ran clean and install, and also what was the output you got from the install script

**Comment by RollingStar** [comment]
@mzmiric5 as the [log in my original post shows](http://pastebin.com/hXk32Fhf), I ran clean.sh twice (both times with me trying and failing to log the console output to a text document). The log does not show the 5-15 times I ran clean, install, and build on the same machine in various attempts to get the game to build correctly.

**Comment by RollingStar** [comment]
I tried a fresh install in my "Music" folder, just to prove I wasn't getting weird old files that were conflicting or something. I also downloaded a fresh ZIP from the site, today, rather than work from an older ZIP, in case the problem had already been fixed.

One can search for

    Music/2015-07-29-open2 $ bash clean.sh

To see the start of me running clean, install, and build. And I run build_g2 for good measure, just in case that affects it. Other than that it's the same as what I already did in the first post of this issue.

The full log of me doing all this, including my initial errors, is [here](http://pastebin.com/zWq0rGcr).

Clean.sh:
```
andy@marienbad ~/Music/2015-07-29-open2 $ bash clean.sh
 
sudo rm -rf /usr/local/cross-tools/i686-w64-mingw32
sudo rm -rf /usr/local/cross-tools/orcalibs
sudo rm -rf /usr/local/cross-tools/orctlibs
rm -rf .cache
rm -rf build
```
Install.sh:
```
andy@marienbad ~/Music/2015-07-29-open2 $ bash install.sh
Linux
Reading package lists... Done
Building dependency tree   
[abridged...]
-rwxr-xr-x  1 root root  103 Jul 29 19:12 i686-w64-mingw32-pkg-config
#!/bin/sh
export PKG_CONFIG_LIBDIR=/usr/local/cross-tools/i686-w64-mingw32/lib/pkgconfig
pkg-config $@
```
Build.sh:
```
andy@marienbad ~/Music/2015-07-29-open2 $ bash build.sh
New libraries need to be downloaded, the script might ask you for sudo access password
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2047k  100 2047k    0     0   914k      0  0:00:02  0:00:02 --:--:--  915k
~/Music/2015-07-29-open2/.cache/orctlibs ~/Music/2015-07-29-open2
[abridged...]
Linking CXX shared library openrct2.dll
[100%] Built target openrct2
~/Music/2015-07-29-open2
Building: data/g2.dat
```
