### ISSUE TITLE
Track designs with paths do not connect them correctly

### ISSUE THREAD

**Issue by Toomix** [OpenRCT2/OpenRCT2#16276]
### Operating System

Windows 10 Pro 20H2, x64

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (25cb49f on develop) provided by GitHub

### Describe the issue

When I build some track design which includes paths, they are not connected properly to the others and I have to "overbuild" them manually. It happens everywhere - right in the design and when I place whole design next to the existing path.

### Steps to reproduce

1. Select rollercoaster design with paths included (Rolling Thunder (Track1) etc.)
2. Place it (missing signs for entrance on queue path)
![2021-12-19 18_14_54-OpenRCT2](https://user-images.githubusercontent.com/26710343/146684337-8ab3193d-6dbd-4ff4-b9e1-0e3bf3f75338.png)

Badly connected exit path
![2021-12-19 18_15_22-OpenRCT2](https://user-images.githubusercontent.com/26710343/146684339-4ad6af9d-6d82-49a9-a78a-bf6c74987fa2.png)

Path overbuilded manually - OK
![2021-12-19 18_15_34-OpenRCT2](https://user-images.githubusercontent.com/26710343/146684340-3729a0dc-8299-4a43-ae6d-6d529f988bbd.png)

**Comment by 733737** [comment]
i believe this bug exists in rct2 vanilla

**Comment by LordMarcel** [comment]
It does not exist in vanilla, it only started happening in the current development versions as it does not happen in the 0.3.5.1 release version. This also happens for me on every saved ride that has path.

**Comment by GalBr** [comment]
I bisected the commits and found that this first bad commit is: fdfd9b47601830534e694aa08443bf2c45a65dce
I'll try to investigate what exactly broke it in this commit, but maybe @duncanspumpkin will find it faster as they created it.

**Comment by duncanspumpkin** [comment]
```auto* pathElement = map_get_path_element_at({ mapCoord.x / 32, mapCoord.y / 32, z });``` that's where the bug is. Should be dividing z.

**Comment by GalBr** [comment]
Good find! Would you like to open a PR for it or should I do it?

**Comment by duncanspumpkin** [comment]
Feel free to submit assuming it fixes it. (Then I can review and approve) I looked this up on my phone at the time so obvs didn't compile or test. Remember to bump the network version as well.

**Comment by duncanspumpkin** [comment]
Well you were too slow. I've submitted a PR.
