### ISSUE TITLE
NSF build saves parks as .sv6 instead of .park when "use system file browser" is selected from save window

### ISSUE THREAD

**Issue by Xtreme97-RCT** [OpenRCT2/OpenRCT2#16287]
### Operating System

Windows 10 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (ee62962 on develop)

### Describe the issue

When using a new save format build (ie. develop build past v0.3.5.1) and selecting "use system file browser" when saving the game, the resulting save will be .sv6 format instead of .park format which it should be. Even if you type .park at the end of the file name it will create a .sv6 file.

Example:
Here, Test_01 is saved using the OpenRCT2 file window and Test_02 is saved after selecting "use system file browser". The Test_02 file can still be opened fine by OpenRCT2, but won't open in a pre-NSF build (such as v0.3.5.1 release) and very likely won't open in vanilla if the old limits are broken.

![image](https://user-images.githubusercontent.com/64152940/146837555-eee43a0c-1bed-4961-bfd2-06bde31fa169.png)

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Create a new save game.
2. Click "use system file browser" in the save window.
3. Save the game and view the file in a browser to see extension and file format.

**Comment by Richard-L** [comment]
Can reproduce this.

Also happens when you use the console's "save_park" command.

Users not on develop will report the resulting SV6 unreadable of course.

**Comment by duncanspumpkin** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/cc22b584fd472b03a7d966914c90d573e753931a/src/openrct2-ui/windows/LoadSave.cpp#L352

https://github.com/OpenRCT2/OpenRCT2/blob/27cbb6c6aeb769c6b1c7e0efb937404499444777/src/openrct2/interface/InteractiveConsole.cpp#L1370
