### ISSUE TITLE
Starting Loop (crash) on MacOS

### ISSUE THREAD

**Issue by Unfaehig** [OpenRCT2/OpenRCT2#16286]
### Operating System

MacOS

### OpenRCT2 build

v0.3.5.1

### Describe the issue

If you try to start the last version v0.3.5.1 on MacOS (M1) you run into a loop, asking for permissions to access the document folder. You directly get the same permissions popup if you click ok, again and again. The only way to exit is to hard kill the application.
All pervious builts worked like a charm on same machine. Guess it's a corupt compile.

Thanks

### Area(s) with issue?

Building the game

### Steps to reproduce

1. Download v03.5.1 macos universal built
2. Start and allow execution of unknow applications
3. try to allow permissions to access document folder

**Comment by adam-bloom** [comment]
Hi @Unfaehig,
I'm not able to reproduce this. Can you clarify the exact build you downloaded (include the hash please). Also, what version of macOS are you running? I just tried both latest release (61c67af) and develop (3faa0eb) on macOS 12.1 - neither prompted me for Documents folder access. In System Preferences, Security and Privacy, you'll find a "Files and Folders" permission section - I haven't granted OpenRCT2 any permissions.

The default location for saves on macOS is not in the documents folder. Have you placed the application or required files in your documents folder? I suspect that may be related to what you're seeing. I just tried to save in my Documents folder (which I had not previously done) - when I navigated to Documents in the Save file browser, I got the prompt you described, but permission was granted on the first time and I was able to complete the save, as well as load it. The System Preferences pane I described above now shows this access has been granted. 
<img width="450" alt="image" src="https://user-images.githubusercontent.com/3771193/147855801-9bb38761-1463-4747-ac6e-3451fb1da4d1.png">

**Comment by kstutz01** [comment]
I believe I've found the issue.   If a previous attempt to set the path was done with the launcher tool or a prior version then the new OpenRCT2 app has trouble accessing the RCT2 resource location.  
Quick work-around:  Go to your RCT2 folder where your resource files are for the real game and rename the folder.  Then the next time OpenRCT2 is launched, it will request the game folder again and will function correctly.

I'm guessing there is a command line option or an old file that could also be deleted but I couldn't find it.  The renaming of the resource game folder worked.

**Comment by AaronVanGeffen** [comment]
Going to assume this has been fixed.
