### ISSUE TITLE
Building custom maze design crashes the game

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#1629]
How to reproduce: Open a fresh "Electric Fields", Start building, Select "Build Custom Design" after choosing Maze will crash instantly.
Build Tested: b1007 from OpenRCT2.com

edit: tested in my save of another scenario, it still crashes.

**Comment by duncanspumpkin** [comment]
I've started work on getting the mazes working again. See my maze branch. Still requires more work.

**Comment by daihakken** [comment]
Thanks, but I don't have compilers in my computer, so I must wait for your commits merged into develop branch to test.
