### ISSUE TITLE
Title sequence editor does not allow adding .park files

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#16292]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

0.3.5.1 ee62962

### Describe the issue

When you have opened the title sequence editor and try to add a .park file, it will not put the file in the list. It does still work for .sv6 files.

### Steps to reproduce

1. Open Title sequence editor
2. Make new title sequence
3. Try to add a .park file to the list - it will fail

**Comment by Gymnasiast** [comment]
The title sequence editor should preferably use the same extensions list as the Load game dialog. That way, if we add another in the future, this won’t happen again.
