### ISSUE TITLE
Ride wrongly reports that it requires 1x1 block to build

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#16311]
### Operating System

Windows 11 Beta Insider

### OpenRCT2 build

f65e12f

### Describe the issue

The ride clearly takes more than 1x1 tile. All other rides in ride construction report normally. I did build it on a server online.

### Steps to reproduce

1. Try to build track
2. track works perfectly
3. Menu said 1x1 tiles required

### Attachments

[733737_Spyrail.zip](https://github.com/OpenRCT2/OpenRCT2/files/7776295/733737_Spyrail.zip)

**Comment by 733737** [comment]
It happened again.
[733737 Hyper-Twister.zip](https://github.com/OpenRCT2/OpenRCT2/files/7776341/733737.Hyper-Twister.zip)

**Comment by 733737** [comment]
I built a ride on a vanilla scenario with no cheats and it happened when I saved a ride. :(

**Comment by Fred-1044276** [comment]
I already reported this issue at #16060.

**Comment by 733737** [comment]
ok
