### ISSUE TITLE
Price for every rides are always starting at "Free"

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#1633]
Stable:
![1007](https://cloud.githubusercontent.com/assets/13048125/8722465/935076dc-2bf7-11e5-8c92-f41ac3df861d.PNG)
b1007 fron OpenRCT2.com:
![1007-2](https://cloud.githubusercontent.com/assets/13048125/8722466/935386f6-2bf7-11e5-833e-b587c5ed6fbc.PNG)

**Comment by Gymnasiast** [comment]
What is your park entry price set to?

**Comment by daihakken** [comment]
@Gymnasiast playing Electric Fields, which the park admission is free. (This situation was also appeared in my 'corrupted' save of Vertigo Views, which the park admission is also free.)
