### ISSUE TITLE
'SnowyPark.sv6' link referenced in manpages and help output is broken

### ISSUE THREAD

**Issue by gibmat** [OpenRCT2/OpenRCT2#16365]
### Operating System

N/A

### OpenRCT2 build

Current develop branch

### Describe the issue

The manpage (`distribution/man/openrct2.6`) and help output (`src/openrct2/cmdline/RootCommands.cpp`) both reference a link that no longer exists: https://openrct2.io/files/SnowyPark.sv6. If possible, a new saved park should be posted and those two files updated, otherwise those examples should be removed so users don't see a broken example.

### Steps to reproduce

N/A

**Comment by duncanspumpkin** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/d7f5995bfd939837bfd56c00de9ff692bc8ec4ac/src/openrct2/cmdline/RootCommands.cpp#L153

**Comment by nkellogg2** [comment]
Can I try and tackle this as a first issue? It seems quite straightforward, just posting a new park to the site and changing the links in these files to point to that?
