### ISSUE TITLE
parkobj scenery groups cannot include .DAT scenery

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#16363]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.3.5.1 d7f5995

### Describe the issue

Xtreme97 was trying to make a parkobj scenery group and include DATs in it, but was having problems. We found the OriginalID of a DAT he wanted to add and added it to the list of objects, but it didn't work.

I looked in the source code and this is what I could surmise:

When loading parkobj scenery groups, the `_items` vector is populated with the `ObjectEntryDescriptor::ObjectEntryDescriptor(std::string_view newIdentifier)` constructor, which sets the generation type to `ObjectGeneration::JSON` for all entries in the parkobj.

`SceneryGroupObject::UpdateEntryIndexes` calls `IObjectRepository::FindObject` which uses the generation type to determine how to find the object, by entry or by identifier.

Because all `ObjectEntryDescriptors` are initialized as JSON, it is not possible to add a DAT to parkobj scenery groups.

I think this is what is happening, but if I am wrong and there is a way to include DATs in parkobj scenery groups, it would be helpful to know how.

### Steps to reproduce

1. 
2. 
3.

**Comment by Gymnasiast** [comment]
> I think this is what is happening, but if I am wrong and there is a way to include DATs in parkobj scenery groups, it would be helpful to know how.

You are correct.

**Comment by spacek531** [comment]
I think a possible way to add this functionality is to define DATs as json dictionaries like so:
```json
"entries": [
{ "originalId": "0A188C81|BALL4    |85044EF8"}
]
```

This avoids having to parse the string to determine the object type, which I assume was why this was not implemented.
