### ISSUE TITLE
Typo in English (UK)

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#1637]
Since en-gb is not in localisation project... I have to open a issue ticket here:

https://github.com/OpenRCT2/OpenRCT2/blob/develop/data/language/english_uk.txt#L1784

"Tigre costume" should be "Tiger costume".

**Comment by Gymnasiast** [comment]
It's not wrong _per se_, just a quite old-fashioned spelling of tiger. But I'll change it. :)

**Comment by daihakken** [comment]
I didn't know it, thank you for your clarification!
