### ISSUE TITLE
game crashed

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#16370]
### Operating System

Windows 11 Beta Insider

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (d7f5995 on develop) provided by GitHub

### Describe the issue

I pushed a key and the game crashed
[debug_replay.zip](https://github.com/OpenRCT2/OpenRCT2/files/7800147/debug_replay.zip)

### Steps to reproduce

1. 
2. 
3.

**Comment by James103** [comment]
Do you have the full crash files? If so, can you please upload them and also give the steps to reproduce?
Try running the automatic Backtrace upload of the crash if possible (click "Yes" when it prompts "We would like to upload this crash to Backtrace, do you agree?").

**Comment by Gymnasiast** [comment]
Also, you’re running on a beta build of Windows. Unless you can reproduce this crash on a build that has actually been released, it’s not something we can do anything with.

**Comment by 733737** [comment]
i am not sure how to use backtrace.io
