### ISSUE TITLE
Benches show up in "Miscellanous Objects" group, instead of "Signs and Items for Footpaths"

### ISSUE THREAD

**Issue by Holek** [OpenRCT2/OpenRCT2#16383]
![image](https://user-images.githubusercontent.com/339861/148300162-1c2c0874-2fe3-4642-b773-3420f2033d06.png)

This issue seems to be happening in v0.3.5.1 (61c67af). I was searching for an issue before posting, but couldn't find anything.

**Comment by Gymnasiast** [comment]
Could you test if this also occurs on a recent `develop` build?

Also, please use the bug report form next time, that makes it a lot easier for us.

**Comment by Holek** [comment]
Will do next time I see a bug, thanks!

It works on current `develop`: 7fff8fa, will close the issue.
It's just weird that a bug like that showed up in a release version.

**Comment by Broxzier** [comment]
I'm guessing that you were somehow using objects from the development branch with the release build.
