### ISSUE TITLE
Certain preloaded designs cannot be placed due to clearance checks

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#16393]
### Operating System

Windows 7 (x86-64)

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (2e9e549 on develop) provided by GitHub

### Describe the issue

In older versions of OpenRCT2, including the vanilla version, I was able to place down the preloaded "Bumble Bee" track design, but as of now, attempting to place them gives an error message saying the design I'm trying to place is "in the way" of itself.

I don't have the vanilla game set up at the time being but I recall being able to place the track with no error popups there, considering it was a pre-loaded track design.

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Make sure collision checks are enabled.
2. Locate a track design, preferably one that's pre-loaded with the game.
3. Pick a track design that does not display an image and attempt to place it in the scenario (preferably on flat ground).

**Comment by duncanspumpkin** [comment]
#13336
