### ISSUE TITLE
[Bug & Feature Request] `--version` flag ignores `host` command & doesn't show network sub-version

### ISSUE THREAD

**Issue by lilkingjr1** [OpenRCT2/OpenRCT2#16394]
### Operating System

[Linux (x86-64)] debian:bullseye-slim & Ubuntu 20.4 LTS

### OpenRCT2 build

OpenRCT2-cli, v0.3.5.1 (11ac4ad on HEAD)

### Bug (Low Priority)
I wanted the OpenRCT2 version to be printed every time I start my dedicated server (for verbose clarity), but using the `--version` flag in tandem with the `host` command just runs prints the version and seemingly skips the `host` command, closing the app.

Current workaround is to simply change my startup command to `./openrct2-cli --version && ./openrct2-cli host save.sv6`, but it would be convenient to shorten it to one app call.
___
### Feature Request (Medium Priority)
`--version` currently only shows the main version number on the CLI version of the app (ex. "OpenRCT2, v0.3.5.1"), and does not print the build/branch (ie. "(####### on develop)") or the network sub-version (ie. "v0.3.5.1 **-9**"). It would be helpful for debugging to add this information to the flag's output.

### Area(s) with issue?

This bug is specific to multiplayer

### Steps to reproduce

1. Run `./openrct2-cli host save.sv6 --version`
2. Only the version gets printed
3. App closes without starting the server

### Attachments

![Capture](https://user-images.githubusercontent.com/4533989/148629940-bb1abff5-205b-4a66-b950-a29f627d0667.PNG)

**Comment by janisozaur** [comment]
I strongly disagree with this request. No program I know of does `--version` and then execute any other action. The purpose of `--version` is universally to know version of given program so it is a lightweight path that only prints version _and exits_. See some links gather from searching for `version "and exit"`:
  - https://jestjs.io/docs/cli#--version
  - https://github.com/Kitware/CMake/blob/859241d2bbaae83f06c44bc21ab0dbd38725a3fc/Help/manual/OPTIONS_HELP.txt#L8-L9
  - https://github.com/vim/vim/blob/c54f347d63bcca97ead673d01ac6b59914bb04e5/src/install-sh#L99

By extending your logic to have `--version` support execution of other commands it would mean an invocation of `openrct2 --version park.sv6` would open such park and so `openrct2 --version` would open the client in its default state. This is no-go.

---

It does indeed make sense to also display network version in the banner, I will add that, but please file a separate ticket for each issue, makes tracking them easier.

**Comment by ocalhoun6** [comment]
Maybe make it a different command line argument? Like `--network-version`, which would do basically the same thing: print the network version and then exit.

-----

Or just have it output the version and network version by default as the first few lines of output when running from the command line.

The version information is one of the first things you see when starting from the GUI (in the startup screen), so it makes sense to mirror that in the command line.

**Comment by lilkingjr1** [comment]
> The purpose of --version is universally to know version of given program so it is a lightweight path that only prints version and exits.

I can agree with this, and I ultimately think `version` should print and exit. However, I was under the impression that flags in command-line apps typically can be stacked and switched over for whatever that app's core function is, performing additional actions that are "related" to that core function (ie. `curl -sSLO` is simply grabbing a stream of data, with extra steps on top). And for apps that have multiple functions (or "commands" in the case of OpenRCT2), I would expect the syntax to typically be: `MyApp <one single command> <one or more flags pertaining to that command>`.

But this is only what I've always encountered in the wild, and I have no sources to state it's a good standard. So, it's just a personal note that I think `--version` should be moved from a flag to a `version` command if it performs one action and closes the program; could even have have a `--network` or `--verbose` flag to print extra data. But I know this change would cause a lot of regression for people who know it as `--version` for something so little, so it's not a big deal and I'll close this issue.

I'll also create a separate feature request for the network version addition to the `--version` command.

**Comment by janisozaur** [comment]
I'm going to reopen this to track printing network version with that argument

**Comment by janisozaur** [comment]
Oh, i haven't noticed you filed https://github.com/OpenRCT2/OpenRCT2/discussions/16408 for that - thanks. In that case closing this.
