### ISSUE TITLE
Plain ride entrance stations show as abstract

### ISSUE THREAD

**Issue by mgrabov** [OpenRCT2/OpenRCT2#1641]
![scr1](https://cloud.githubusercontent.com/assets/13057640/8754198/c2305286-2c8f-11e5-85dd-da068355af9f.png)

**Comment by IntelOrca** [comment]
I can't reproduce...

**Comment by Gymnasiast** [comment]
I can, at least on the rct1-import branch.

**Comment by IntelOrca** [comment]
Can you provide me with steps on develop using a normal scenario? I tried the RC designer with the steel twister coaster, and I couldn't reproduce.

**Comment by Gymnasiast** [comment]
Six Flags Magic Mountain, Flashback. Though the behaviour is the exact opposite.

**Comment by mgrabov** [comment]
Yep all fixed now, Thanks
