### ISSUE TITLE
Some functions use 16bit window flags

### ISSUE THREAD

**Issue by erikjanp** [OpenRCT2/OpenRCT2#16428]
### Operating System

Linux

### OpenRCT2 build

v0.3.5.1

### Describe the issue

Some functions use 16bit window flags as input. This is a problem because there are more than 16 window flags.
Patch can be found here:
https://forums.openrct2.org/applications/core/interface/file/attachment.php?id=8957&key=ba47d202744f10c9c36870ab74bcf1aa

### Steps to reproduce

1. try to close all non-centre screen windows with window_close_all_except_flags(WF_CENTRE_SCREEN)
2. 
3.

**Comment by ZehMatt** [comment]
Any reason to why you submitted an issue with a patch file instead of doing a PR?

**Comment by Margen67** [comment]
> Any reason to why you submitted an issue with a patch file instead of doing a PR?

They did this for all 4 of their issues.

**Comment by Broxzier** [comment]
Closing this, as we don't accept patches. Just submit a PR, like you have been told on the forums and here on GitHub.
