### ISSUE TITLE
The notification settings window is not themable

### ISSUE THREAD

**Issue by erikjanp** [OpenRCT2/OpenRCT2#16429]
### Operating System

Linux

### OpenRCT2 build

v0.3.5.1

### Describe the issue

Almost all windows in OpenRCT2 are themable, but the notification settings window is not in the list.
Patch to add this window to the list can be found here:
https://forums.openrct2.org/applications/core/interface/file/attachment.php?id=8958&key=de335fd1ed78789cc0b74a211c7eb290

### Steps to reproduce

1. Try to theme the notification settings window
2. Search the list of themable windows
3. Feel sad because this window is not in the list

**Comment by Broxzier** [comment]
Another patch. Just like your other issues, submit a PR instead.
