### ISSUE TITLE
Unavailable track is buildable and vice versa

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#16448]
### Operating System

Windows 10, 64bit

### OpenRCT2 build

f2f47aa

### Describe the issue

Building coaster works incorrectly since 0.3.5.1-10, especially since 0.3.5-11.

1. Helix curve is not able to be built
2. Tracks which are able to be built even though it should be unavailable in the coaster, such as 1x1 curved track in Corkscrew Coaster, and tracks which should be available is unavailable, such as 3x3 upward curve in Corkscrew Coaster
3. Special tracks are not cleared after building previous rides.

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Build some coasters, like Corkscrew coaster
2. Select 30 degree upward/downward slope track
3. Select middle size Right/left curve button
4. Or try to build a helix up/downward curves
c.f. Build by using hotkeys will significantly shows this issue.

### Attachments

https://clips.twitch.tv/FrigidRepleteTildeGingerPower-8n-9hMxZhdarEta5
(You can see that it tries to build unavailable/invisible track for Classic Mini Coaster and the helix curves are disabled in the construction window)

**Comment by Gymnasiast** [comment]
Most likely caused by https://github.com/OpenRCT2/OpenRCT2/pull/16172.

**Comment by spacek531** [comment]
f2f47aa is older than the bugfix ef77f9c2c11ddb66459161e4a3b7a9f53fbe330b

**Comment by telk5093** [comment]
> @telk5093 does this still happen if you update to the latest develop?

It seems fine, thanks :)

**Comment by Gymnasiast** [comment]
@telk5093 Are all the things in your issue now fixed? If so, please close it. Otherwise, please specify what is still broken.

**Comment by telk5093** [comment]
Checked again for 85a1e96 and it is all fine, I'll close this issue, thanks.
