### ISSUE TITLE
Viewport doesn't close when switching tabs

### ISSUE THREAD

**Issue by Manticore-007** [OpenRCT2/OpenRCT2#16449]
### Operating System

Windows 10 64 bit

### OpenRCT2 build

OpenRCT2 v0.3.5.1(ef77f9c on develop)

### Describe the issue

![viewport](https://user-images.githubusercontent.com/71702374/149662195-56263d64-59cf-440c-95c2-a6e19eb1eae5.gif)

When putting a viewportwidget in a tab, it stays open on the other tabs. It doesn't close until you close the window.

### Steps to reproduce

![viewport](https://user-images.githubusercontent.com/71702374/149662292-e53d7c1e-b8e4-4953-9297-124a3deaf5c9.gif)

See my PeepEditor plugin for the issue.

**Comment by Gymnasiast** [comment]
@IntelOrca
