### ISSUE TITLE
Name for saving new save file is always using 'autosave'

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#1645]
![capture](https://cloud.githubusercontent.com/assets/13048125/8765520/a31a0ad2-2e41-11e5-958e-6d9eaa8c637e.PNG)

I think this can be fixed by using the park name, rather using the last save's name...

**Comment by duncanspumpkin** [comment]
I thought this had already been fixed?

**Comment by daihakken** [comment]
@duncanspumpkin nah, it hadn't been fixed. Tested in [b1021](https://openrct2.com/download/1021) from OpenRCT2.com

**Comment by vzybilly** [comment]
Maybe a better way would be <save Name>.autosave.<save extension> and have no user periods for the same name, allowing the actual save name to be gotten from the save file with ease... and when there is a save prompt than just trim the name down to the first period and have that in the prompt...

**Comment by zsilencer** [comment]
let me know if you are still experiencing this
