### ISSUE TITLE
Missing vehicle type

### ISSUE THREAD

**Issue by rosarian** [OpenRCT2/OpenRCT2#16470]
### Operating System

Windows 11, 64 bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (61c67af) provided by GitHub

### Describe the issue

Vehicle type 47 (RCT1) Steel Twister Roller Coaster Train (Non-Looping) is missing from the Twister RC list of filters as well as the lists of tracks.  Sample track files enclosed.
[NonLoopingTracks.zip](https://github.com/OpenRCT2/OpenRCT2/files/7899027/NonLoopingTracks.zip)
.

### Steps to reproduce

1. Track Designer doesn't offer the choice of Steel Twister Roller Coaster Train (Non-Looping) under Twister RC
2. Scenarios the allow Twister RC from RCT1 don't list any tracks that have Steel Twister Roller Coaster Train (Non-Looping)
3. 

### Attachments

[NonLoopingTracks.zip](https://github.com/OpenRCT2/OpenRCT2/files/7899137/NonLoopingTracks.zip)

**Comment by Gymnasiast** [comment]
1. Missing RCT1 features/vehicles are not bugs, they are feature requests.
2. The train _is_ present, but all non-looping twister trains are grouped under “Hyper-Twister”. That’s also where all track designs made with this train are:
![afbeelding](https://user-images.githubusercontent.com/1478678/150192113-3459b71f-9b74-4b59-a3a2-9d96005d82a6.png)

**Comment by Gymnasiast** [comment]
Since there hasn’t been a reply, I’m going to assume this answers your question.
