### ISSUE TITLE
Signs not displaying non-English characters such as Å, Ä, Ö, á, é etc.

### ISSUE THREAD

**Issue by Csikasz** [OpenRCT2/OpenRCT2#16479]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (d97ecdd on develop) provided by GitHub

### Describe the issue

In the NSF, signs do not display non-English correctly. They seem to get mapped to different characters:
![image](https://user-images.githubusercontent.com/83851186/150423538-9de8515b-76c1-437b-be29-a839c9dede51.png)

This used to work just fine pre-NSF:
![image](https://user-images.githubusercontent.com/83851186/150423958-caea839d-c4fe-4712-9759-9dcbc4570374.png)

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Place sign
2. Try writing non-English character
3. Check what you actually get:

![image](https://user-images.githubusercontent.com/83851186/150423586-c008ca6b-d102-47a5-a3e9-81cd8f81d6eb.png)

**Comment by GalBr** [comment]
4288589f11538ddf6b314b5d4872a46719f5f11c is the first bad commit.
I'm trying to debug the banner text painting code but I'm not familiar with the code enough yet. I think it has something to do with getting the wrong glyph for non-english characters.  Maybe @IntelOrca can help, as they did the refactor.

**Comment by GalBr** [comment]
I found the bug:
https://github.com/OpenRCT2/OpenRCT2/blob/b3bae9429c5d4a1db7ee847f1cd02fd834558d28/src/openrct2/paint/tile_element/Paint.LargeScenery.cpp#L126-L151
Line 127: `glyph.image_offset` is `uint8_t`, so our local variable is that too.
Before the refactor, the local variable was `uint32_t`.
Line 135 can cause an overflow: The image_offset for Ä, for example, is 73. So 73 * 4 = 292, which is being turned into 36.
I'll fix it by explicitly making glyphOffset a `uint32_t` variable, as before the refactor.
