### ISSUE TITLE
Guests not showing on one side of a pirate ship ride if there are more than two people on it

### ISSUE THREAD

**Issue by Stever1009** [OpenRCT2/OpenRCT2#16485]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (85a1e96 on develop) provided by GitHub

### Describe the issue

If there are more than two people on a pirate ship ride, only one side of ship shows at least two guests while the other side looks completely empty even though there are supposed to be more guests on that side.

### Steps to reproduce

1. Put your mouse on a pirate ship ride to see how many guests are riding it.
2. If it says there are more than two people riding it, only one side of ship shows at least two guests while the other side looks completely empty even though there are supposed to be more guests on that side.

### Attachments

![pirateshipbug](https://user-images.githubusercontent.com/7691194/150655967-5160711e-1bac-4052-a4da-9656ee887c09.jpg)

**Comment by Gymnasiast** [comment]
Can confirm.
