### ISSUE TITLE
Testing any hyper twister roller coaster causes CTD

### ISSUE THREAD

**Issue by austinjb555** [OpenRCT2/OpenRCT2#1650]
<a href=http://www.filedropper.com/sixflagsgreatadventureopenrct222><img src=http://www.filedropper.com/download_button.png width=127 height=145 border=0/></a><br /><div style=font-size:9px;font-family:Arial, Helvetica, sans-serif;width:127px;font-color:#44a854;> <a href=http://www.filedropper.com >file storage</a></div>

Here's the save if anyone wants to look. However, it happens on any scenario. I'm on build 1025 but it has been happening from maybe 1020 or earlier,

**Comment by daihakken** [comment]
I can confirmed that it only happens when playing in scenarios; doesn't affect Roller Coaster Designer.
