### ISSUE TITLE
Garbled up accentuated characters in objective screen after save loading 

### ISSUE THREAD

**Issue by pchesneau** [OpenRCT2/OpenRCT2#16501]
### Operating System

Windows 10 21H2 x64

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (61c67af) provided by GitHub

### Describe the issue

After loading a saved game (.sv6) , accentuated characters are garbled up in the "objective details" window of the park (when using language with accentuated characters)

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1.  Switch OpenRCT 2 to a language with special chars. (I'm using french language)
2. Start any scenario. Note that in the selection screen, Display is fine (see attachement) 
3. Check the objective Screen (Park/objective) . Display is fine.
3. Save the newly started game, then reload it, 
4. Now check the objective screen, all special chars are garbled up. (see attachement).

### Attachments

![Garbled_up_objectives](https://user-images.githubusercontent.com/9027327/150873649-a0fbaead-b632-4816-8a5c-6db641ac7989.png)
![selection_screen](https://user-images.githubusercontent.com/9027327/150873650-d9a250b3-b56b-4ee1-a533-048d391c6470.png)

**Comment by Gymnasiast** [comment]
This looks like this issue: https://github.com/OpenRCT2/OpenRCT2/issues/13955

Please install the latest develop build and see if the issue persists. (**Always** do this if you’re running into problems, they are often solved in `develop`).

**Comment by pchesneau** [comment]
Hello! 
Thank you for your feedback. Indeed it is solved in latest develop build. I'll close this issue.
