### ISSUE TITLE
Failed to load language file

### ISSUE THREAD

**Issue by AdityaMH** [OpenRCT2/OpenRCT2#16507]
### Operating System

Android 10

### OpenRCT2 build

0.3.5.1

### Describe the issue

"Failed to load languages.
Your installation may be damaged."

from first place

### Area(s) with issue?

The bug also exists in RCT2 (vanilla)

### Steps to reproduce

Just install, then crash

**Comment by YJSoft** [comment]
You'll need three things to run OpenRCT on android. check [wiki page](https://github.com/OpenRCT2/OpenRCT2/wiki/Android) for details.
Also, please do **NOT** select `The bug also exists in RCT2 (vanilla)` if It's not related to original game.
