### ISSUE TITLE
Demolishing a $32 track will give you $392.

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#1651]
![capture](https://cloud.githubusercontent.com/assets/13048125/8773271/89d7204a-2f05-11e5-9630-f55c830b7ce5.PNG)

build tested: [b1025](https://openrct2.com/download/1025) from OpenRCT2.com

edit: demolishing curve track, which cost $10x, will refund $1xxx

**Comment by duncanspumpkin** [comment]
Is it because its underground? Can you run a test to see. I'll fix this when i get home if no one else gets there first.

**Comment by daihakken** [comment]
@duncanspumpkin Yep, underground only.
