### ISSUE TITLE
Odd issues with auto-HDR enabled

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#16512]
### Operating System

Windows 11 Beta Insider

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (9f74c70 on develop) provided by GitHub

### Describe the issue

within the last week or two I have noticed more of the white screen and flickering, unfortunately it cannot be described in a screenshot and I don't know if I want to share a video of it... What happens is sometimes the game crashes on exit, other times the game flickers and the screen turns white when launching or exiting, also when alt tabbing. Printscreen also still doesn't work in OpenGL which is required for auto-HDR

### Steps to reproduce

1. Use Windows 11 auto HDR
2. launch or exit the game
3. the white screen shows up consistently and more often in the last week or two

**Comment by janisozaur** [comment]
Can you check if you have lightfx enabled and if turning it off affects your results?
![unknown.png](https://user-images.githubusercontent.com/550290/151176449-cef41b56-3ec5-49f1-94eb-14ca6b40bc75.png)

**Comment by 733737** [comment]
i never use it since it strains my eyes

**Comment by 733737** [comment]
isn't that for hardware accelerated software renderer anyway?

**Comment by 733737** [comment]
the issue may have resolved itself unexpectedly
