### ISSUE TITLE
rct1 legacy pathing on a slope with railing misaligned

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#16526]
### Operating System

Windows 11 Beta Insider

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (149b164 on develop) provided by GitHub

### Describe the issue

since the legacy railings and paths were added to the game, the sloped pathing and railings misalign constantly. This happens most with checkered pathing (I used grey and green)

### Steps to reproduce

1.  enable rct1 legacy railings and paths manually in object selection (specifically checkered)
2.  build upwards (downwards)
![gitt](https://user-images.githubusercontent.com/94884086/151495117-687da45e-6f46-431e-80d3-741e130a469e.png)
 sloped path
3. path is thoroughly and consistently bugged through multiple parks

**Comment by spacek531** [comment]
what should it look like?

**Comment by 733737** [comment]
i think it is balustrade and i would like the railing to connect to the railing next to it. Balustrade to balustrade, the space path is unrelated

**Comment by spacek531** [comment]
can you take a screenshot of it in roller coaster tycoon so we can see if it's changed?

**Comment by spacek531** [comment]
This appears to be an issue with the sprite itself. I do not expect OpenRCT will do anything about it.

**Comment by 733737** [comment]
could you do a sprite offset?

**Comment by spacek531** [comment]
There's no point because the sprites are the problem, not where they are

**Comment by 733737** [comment]
I don't feel that this is going anywhere, thanks for the discussion
