### ISSUE TITLE
vertical drop coaster does not draw train when using inline twist

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#16523]
### Operating System

Windows 11 Beta Insider

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (149b164 on develop) provided by GitHub

### Describe the issue

[githubthispark77.zip](https://github.com/OpenRCT2/OpenRCT2/files/7955859/githubthispark77.zip)
![New Save 40x40 Bench 2022-01-28 00-04-06](https://user-images.githubusercontent.com/94884086/151490653-d7f36221-86a9-4f6f-bb41-b975fe7c692a.png)

I think it should use sprites from barrel roll

### Steps to reproduce

1. merge vertical drop with flying coaster
2. add inline twist
3. vertical drop coaster will disappear and clip briefly (clipping is fine since it's not the same track type)

**Comment by duncanspumpkin** [comment]
Coasters without sprites for certain track elements will draw the next nearest or failing that nothing. I wouldn't want to try change the logic that handles this.
