### ISSUE TITLE
Peeps showing "Heading for " without ride name

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#1653]
IAmTheWorldLeader on reddit has noticed that some peeps do not have the correct state messages. This requires confirmation and also if required a fix.

https://www.reddit.com/r/openrct2/comments/3dxzs9/anybody_else_getting_guest_that_say_heading_for/

**Comment by IntelOrca** [comment]
I can't reproduce, even if I demolish the ride that a guest is heading to.

**Comment by duncanspumpkin** [comment]
The save that this was affecting still generates new heading for blank messages even when i have a breakpoint on every setter function. Either way though the bug is not very prevalent any more if you play the scenario eventually it falls to about 1-5 people with no valid ride index. I could add a check on heading for to make sure the ride index is valid if we wanted though.

**Comment by duncanspumpkin** [comment]
I ran the save for even longer and it will fall to 0 then stop. I think whatever caused this is fixed.
