### ISSUE TITLE
Entering construction mode unblocks all paths

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#16535]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (7234016 on develop) provided by GitHub

### Describe the issue

Paths that are flagged as blocked (by a miniature railway train) become unflagged when any ride enters construction mode

### Steps to reproduce

1. Build a miniature railway that crosses a path
2. When peeps freeze when the blocked flag is set, right-click on a different ride to enter construction mode
3. All peeps who were frozen become unfrozen

expected behavior: only paths intersecting the edited ride are unblocked

**Comment by ZehMatt** [comment]
The issue is probably within ```ride_clear_blocked_tiles``` not checking what ride the track belongs to before clearing the flag.
