### ISSUE TITLE
Can't Remove This error when removing track pieces

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#16534]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (7234016 on develop) provided by GitHub

### Describe the issue

When removing some track pieces, the track ghost is removed while the track piece is not removed, and an error message appears. This bug is new within roughly 2 months ago.

### Steps to reproduce

1. Build a roller coaster with a station, TurnLeftEighthToDiag, and a TurnLeftEighthToOrthogonal
2. Remove the track elements clicking the destroy button in the ride construction window

Bisecting points the blame at this commit: df5c4dd91c8b811fb8127a3a4e770e82b801e314

### Attachments

![openrct2_2022-01-28_18-40-34](https://user-images.githubusercontent.com/3454156/151644126-a20c3edc-2436-4822-bc93-218a97044f16.png)
![openrct2_2022-01-28_18-40-40](https://user-images.githubusercontent.com/3454156/151644128-c5edf9d4-4b80-43b2-bfb5-6518054573a2.png)

**Comment by Fred-1044276** [comment]
This error is especially annoying when I want to remove track pieces in reverse direction.

**Comment by Gymnasiast** [comment]
I think this was accidentally introduced by https://github.com/OpenRCT2/OpenRCT2/pull/16441.
@GalBr Could you look into this?

**Comment by GalBr** [comment]
As @Gymnasiast says. while working on a fix for a different bug I noticed a change I made caused this and fixed it back then. I'll look into it to see what I missed.
