### ISSUE TITLE
Footpath 5 feet off the ground "connects" to the path on the ground

### ISSUE THREAD

**Issue by austinjb555** [OpenRCT2/OpenRCT2#1654]
And behaves in the old way the paths used to, even though it's not supposed to connect.
![scr6](https://cloud.githubusercontent.com/assets/12687508/8790806/1fd55e58-2f20-11e5-9c2d-0083b6ada385.png)
![scr7](https://cloud.githubusercontent.com/assets/12687508/8790807/20a9a37a-2f20-11e5-8e92-122c8d012dd7.png)

**Comment by daihakken** [comment]
did you try the new builds? Seems that it was fixed in the newer builds.

**Comment by duncanspumpkin** [comment]
@LRFLEW looks to be a bug in your code. Its not checking to make sure that paths are slopped in the correct direction.

**Comment by LRFLEW** [comment]
Oops. Must have missed something when I copy-pasted that code from `footpath_remove_edges_at`. I'll take a look at this and submit a fix.

**Comment by LRFLEW** [comment]
After further investigation, it looks like this issue is unrelated #1615, as the connection appears to happen before `footpath_disconnect_queue_from_path` is able to perform any action. I'll continue to look into this issue, but it may take a little while to find the problem.
