### ISSUE TITLE
G2 sprites after 2190 do not exist

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#16560]
### Operating System

Windows 10

### OpenRCT2 build

45debeeb3f540b290b8691d17d7f8eb0272fdb27

### Describe the issue

There is a threshold for number of sprites in G2, the threshold is 2190 sprites or sprite index 2189. After this, sprites are not drawn by OpenRCT2 and are treated as if they do not exist.

To demonstrate, I added 16 copies of the logo sprite to the end of G2. I built G2, and modified the main menu screen to draw one of the copies. The 12th copy (sprite 1289) draws, but the 13th copy (sprite 1290) does not draw. The sprites are packed in G2 correctly because `sprite exportall` exports the copies.

### Steps to reproduce

1. Checkout [8aac8f0713a2bb205beaf55cab118eded8675a6c](https://github.com/spacek531/OpenRCT2/tree/sprite-count-issue)
2. Build G2
3. Load game
4. OpenRCT2 logo is not visible
5. change the ` + 12` to `+ 11`
6. OpenRCT2 logo is visible

Use case: I am working on a PR that requires more than 12 custom sprites

**Comment by Gymnasiast** [comment]
I can’t tell exactly why it would be limited like that, but that image is at index 29357+2910 = 32267, which is _near_ the int16_t maximum of 32767 (exactly 500 away).

**Comment by spacek531** [comment]
Are int16_t used anywhere near sprites? I assumed everything wrt them would be unsigned.

**Comment by Gymnasiast** [comment]
It might just be a coincidence.

By the way, I cannot reproduce the issue from the code you provided. Even changing the sprite to `SPR_G2_FAKELOGOS_START + 15` still makes it show up:

![image](https://user-images.githubusercontent.com/1478678/153678220-e7ad8542-0e48-4ffc-9953-6b651ba6a321.png)

**Comment by spacek531** [comment]
Now I cannot recreate it either. Very frustrating, it lost me several hours of implementing sprites.

**Comment by spacek531** [comment]
It is happening again, but with a different offset. Instead of failing after the 12th sprite, it's failing after the 46th sprite. I still have no idea why it happens or what triggers it.

**Comment by spacek531** [comment]
I found the problem related to the missing 47th and 48th sprites, but another problem continues: scrolling text is corrupted somehow:

https://user-images.githubusercontent.com/3454156/153701437-7845ef1e-c8de-4d86-b1b0-688290b3f1b1.mp4

**Comment by spacek531** [comment]
Closing because this doesn't seem to be an issue any more.
