### ISSUE TITLE
Ducks/birds always spawn at the edge of the old map limits, and nowhere else

### ISSUE THREAD

**Issue by Basssiiie** [OpenRCT2/OpenRCT2#16565]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (6d0bb48 on develop) provided by GitHub

### Describe the issue

Ducks always spawn at the edge of the old map limit, so at either 0 or 255 tiles out on either X or Y.

**The bug**
If the map is smaller than 256, they spawn far out in the void and slowly fly to the map.
If the map is bigger than 256, they spawn over land and if the map is 999 you'll rarely find them in the far corners of the map.

**The potential solution**
Use the actual boundaries of the map to determine where birds spawn.

**The cause**
Probably around [here](https://github.com/OpenRCT2/OpenRCT2/blob/6d0bb48b68a2f35676ef4246ae4165bf242232cd/src/openrct2/entity/Duck.cpp#L303-L317). Might be a good first issue for anyone who wanna pick it up. :)

### Area(s) with issue?

The bug also exists in RCT2 (vanilla)

### Steps to reproduce

1. Create a 999x999 map.
2. Go 255 tiles out from 0,0.
3. Spawn a buttload of ducks with the "Create Ducks" cheat.
4. See your army spawn at the 255 tile line.

**Comment by ZehMatt** [comment]
Best to fix this after #16259 is merged. There are hardcoded constants currently which is the old map size.

**Comment by ZehMatt** [comment]
Now with https://github.com/OpenRCT2/OpenRCT2/pull/16259 merged this can be done.

**Comment by zuczek4793** [comment]
Mind if I take this? I am an undergrad student doing this for a project where we need to contribute to a project.

**Comment by tupaschoal** [comment]
Sure

**Comment by zuczek4793** [comment]
No, I'm in the states.
