### ISSUE TITLE
Staff statistics overflow

### ISSUE THREAD

**Issue by fidwell** [OpenRCT2/OpenRCT2#16561]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (45debee on develop) provided by GitHub

### Describe the issue

The "lawns mown" (presumably other staff statistics) will overflow to a negative number after enough lawns have been mown. (At the very least, maybe this should be an unsigned value?)

![image](https://user-images.githubusercontent.com/5436387/151735140-3548cd55-a0c6-41df-b3fe-f04e3ae91a64.png)

### Steps to reproduce

1. Hire handyman and set to only mow lawns.
2. Wait a very long time.
3. Eventually, the lawns mown statistic will overflow.

**Comment by Gymnasiast** [comment]
Please upload an affected save.

**Comment by fidwell** [comment]
Here is our save. Check the stats for handyman "Terry".

[gigapark.zip](https://github.com/OpenRCT2/OpenRCT2/files/8008964/gigapark.zip)
