### ISSUE TITLE
Game crashes upon exiting while park file open

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#16568]
### Operating System

Windows 11 Beta Insider

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (8064ef2 on develop) provided by GitHub

### Describe the issue

the last couple days, the game has been crashing a lot, exclusively when exiting the game, but not every time

### Steps to reproduce

1. play game like normal for a while
2. exit game
3. the game will stop responding if you exit from a park, but not from the main menu

**Comment by ZehMatt** [comment]
Is this no longer happening or why did you close the issue?

**Comment by 733737** [comment]
it stopped happening the next day

**Comment by 733737** [comment]
issue's back for some reason, please look into this
