### ISSUE TITLE
new land surface types show incorrectly in software mode

### ISSUE THREAD

**Issue by Mmmmulder** [OpenRCT2/OpenRCT2#16577]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (5157b57 on develop) provided by GitHub

### Describe the issue

I was testing out Tolsimir's new land surface types, and noticed they show up incorrectly on software mode. In openGL they show correctly

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. 
![software](https://user-images.githubusercontent.com/77336136/152381080-7e128658-f587-48d2-8ed4-6e1e2c6e0f33.jpg)

2. 
![openGL](https://user-images.githubusercontent.com/77336136/152381102-e3edb48a-374c-49aa-9187-478a2c653a5d.jpg)

3. 
![thing2](https://user-images.githubusercontent.com/77336136/152381109-0cd9967f-b295-4150-8417-5a074c77c609.gif)

### Attachments

![software](https://user-images.githubusercontent.com/77336136/152380913-66664960-2872-4b1b-aa61-7b86d6a0a72b.jpg)
![openGL](https://user-images.githubusercontent.com/77336136/152380937-402b1e2c-7ec6-4118-8115-981f1d030d8c.jpg)
![thing2](https://user-images.githubusercontent.com/77336136/152380957-ce835404-0474-4e9e-b426-3b86daaeb1d8.gif)
[tols land test.zip](https://github.com/OpenRCT2/OpenRCT2/files/7996186/tols.land.test.zip)

**Comment by duncanspumpkin** [comment]
Is this just an invalidation issue

**Comment by IntelOrca** [comment]
> Is this just an invalidation issue

I doubt it. 

I would question whether the new terrain object ever worked. Perhaps it was only tested in OpenGL. It could be something to do with the zoom offset.

**Comment by Ruedii** [comment]
Is there a reason we should keep the old software renderer?

**Comment by duncanspumpkin** [comment]
That is completely unrelated to this issue and the answer is no. You are basically asking to break compatibility for a whole host of platforms that don't have opengl.

**Comment by spacek531** [comment]
This only occurs in software mode when "landscape smoothing" is turned off

**Comment by spacek531** [comment]
I figured out the problem, the six graphics used to smooth the edges must be saved as bmp, not rle. Tolsimir did not set this (and how could he know, really, there are no tools to determine this and no examples) and he also set the offset to <-32,0> instead of <0,0>
