### ISSUE TITLE
Crash Placing Saved Track Designs Due to OOB Read on Research.cpp:554

### ISSUE THREAD

**Issue by voidstarcpp** [OpenRCT2/OpenRCT2#16572]
### Operating System

Ubuntu

### OpenRCT2 build

v0.3.5.1

### Describe the issue

This index into a global array will be OOB when `rideEntryIndex` is `OBJECT_ENTRY_INDEX_NULL`, defined to be `0xFFFF`:

![Screenshot_2022-02-02_17-26-17](https://user-images.githubusercontent.com/98924160/152255164-58d0fdbf-66f5-4c22-9a15-489e2a026e4e.png)

Here is the bad index register at the time of the crash:

![Screenshot_2022-02-02_17-49-03](https://user-images.githubusercontent.com/98924160/152257096-2d9ddd5a-2ee4-4a90-86d6-d133c72b9566.png)

`ride_entry_is_invented(...)` gets called by the `TrackDesignAction` command class in two places, `::Query()` and `::Execute()`. In both locations is this bizarre code:

![Screenshot_2022-02-02_17-53-16](https://user-images.githubusercontent.com/98924160/152257650-4c52725e-0370-4eda-9dba-11e92bbb019b.png)

In fact, the code _only_ calls the is_invented function with null entry indexes. It then does nothing with information other than ... set the index to null, again. Maybe this fallback check was only supposed to happen if the index was _not_ null? I fixed my own build by just commenting out the redundant check in both member functions.

The null value only appears for certain combinations of coasters and scenarios, possibly due to differences in what objects are loaded in by scenario. I haven't looked into this further.

Reproducing the OOB value is easy (drop a bounds check assertion there and start placing coasters). Reproducing the crash is difficult due to the plurality of compile and run-time factors that affect your memory mapping and thus whether or not this offset will trigger a fault. My single player game has been crashing consistently for months now, which prompted me to find the cause.

I believe this may also be the cause of #16264, however I've never used multiplayer and do not know if this issue affects other connected clients in the manner so described. I recall seeing other reports of saved designs causing crashes as well and this bug may be the reason why.

### Steps to reproduce

1. `assert( rideEntryIndex < MAX_RIDE_OBJECTS )` in `ride_entry_is_invented(...)`
2. Load the Woodstock map and select a saved Corkscrew Coaster design. The assert will fire as soon as your mouse hovers over the game area, where the track preview should appear. I believe it is necessary that the saved design's ride vehicle type not be available in the current scenario.
3. OpenRCT2 has crashed!

**Comment by ZehMatt** [comment]
Thanks for the highly detailed report, this is a very welcome thing 👍 I'll look into it if no one else comes before me.

**Comment by Gymnasiast** [comment]
I checked the `if (entryIndex == OBJECT_ENTRY_INDEX_NULL)` bit (which I changed) and I’m certain it is a refactor error and that it indeed should have read `if (entryIndex == OBJECT_ENTRY_INDEX_NULL)`.
