### ISSUE TITLE
Translate in-game console help text

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#16582]
Currently, the help text (`Type 'help' for a list of available commands. Type 'hide' to hide the console.`) is untranslatable. It should be added to the language files and then retrieved using `language_get_string()`. Additionally, the straight/typewriter quotes should be replaced with ‘ and ’.

**Comment by 94794** [comment]
Hello,

Would https://github.com/94794/OpenRCT2/commit/0f0a343e21a0f4d0723e0a76dc1fe0b0df367bae do it?

**Comment by Gymnasiast** [comment]
It looks good, although I think InGameConsole.cpp will also need an import for StringIds.h. Have you been able to test it?

**Comment by 94794** [comment]
Fixed the import.
I couldn't test it in game, only the function call.
Made a draft PR. Hope it's ok.

**Comment by 94794** [comment]
Looks like the creation of InGameConsole is happening before the creation of the context instance. Therefore the usage of `language_get_string()` at the creation of InGameConsole will break when trying to retrieve de localisation service.

Is there anything to do?

**Comment by Gymnasiast** [comment]
You are correct, but I’m a bit puzzled why it creates the InGameConsole so soon. That will require investigation, but that’s really not something you want to pick up if you’re new to our codebase :-P

I think we should put this PR on hold until I have time to look into it, or another team member does.

**Comment by Gymnasiast** [comment]
@94794 Took a look myself, the solution was to delay writing the introductory text until the console was actually opened for the fist time. I now created a pull request for that.
