### ISSUE TITLE
Crash when I open the attached RCT2 save made in vanilla RCT2

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#1658]
As soon as I open this save, which was made using the vanilla RCT2, OpenRCT2 crashes. Visual Studio 2015 sais the following about this: Exception thrown at 0x5E0642A4 (openrct2.dll) in openrct2.exe: 0xC0000005: Access violation reading location 0x000285BF.

This is the save (please ignore the silly names, I play this game with my sister for fun :) ): https://drive.google.com/file/d/0Bwc5O5IR0pMpMWcwckV6eGhfZUE/view?usp=sharing

**Comment by mrtnptrs** [comment]
Someone has been drinking too much coffee :) You fixed this one really really fast! :+1:

**Comment by IntelOrca** [comment]
Its much easier to fix bugs such as this one when it crashes in our OpenRCT2 C code.
