### ISSUE TITLE
Add strings for UI scale and autosave count

### ISSUE THREAD

**Issue by AtkinsSJ** [OpenRCT2/OpenRCT2#16590]
Discovered while working on #16558, the Options window code misuses a couple of other string IDs to format the "Window scale factor" (as a number with 2 decimal places) and "Autosave amount" (as a positive integer). Ideally both would either have unique strings defined, or some general-purpose number-formatting ones.

**Comment by Gymnasiast** [comment]
I would say the latter, there is nothing special about the string that ties it to objectives. So it will be just a rename to something more descriptive/general.
