### ISSUE TITLE
Game crashed when rotating the last station piece 180 degrees

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#16603]
### Operating System

Windows 11 Beta Insider

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (6d229eb on develop) provided by GitHub

### Describe the issue

I was building a twister coaster in continuous circuit blocked section mode that was an incomplete circuit and I went to rotate the last station piece near the end of the ride twice and the game froze and crashed

### Steps to reproduce

1. build a partial twister coaster and change it to continuous circuit block sectioned mode
2. rotate station piece nearest the end of the ride twice with tile inspector
3. game should crash

**Comment by Gymnasiast** [comment]
That’s all? No need to be in construction mode or have a ghost train on the track?

**Comment by 733737** [comment]
I had the ride window open, the ride was closed and not under construction

**Comment by Gymnasiast** [comment]
I cannot reproduce the crash. You have have to prepare a save file that easily triggers the bug.

**Comment by 733737** [comment]
I can see if I can replicate it, but the ride I was building was lost, it may have been a fluke. If I can replicate this bug I will post it.
