### ISSUE TITLE
Object placement resets underground view

### ISSUE THREAD

**Issue by Phasedetect** [OpenRCT2/OpenRCT2#1660]
Rep: Open a scenario, toggle underground view, open the path tool. Moving the path tool cursor to a new tile resets underground view to off. Also happens with scenery place tool and the build ride tool.

**Comment by IntelOrca** [comment]
This is original and expected behaviour - I suggested being able to lock the view settings in #1392.

**Comment by Phasedetect** [comment]
Well I'll be damned. I can't believe I haven't ever noticed this behavior before, but you're right.

**Comment by IntelOrca** [comment]
Will be resolved by #1734.
