### ISSUE TITLE
Erasing the last track piece of a ride resets the track placement's direction

### ISSUE THREAD

**Issue by Phasedetect** [OpenRCT2/OpenRCT2#1661]
Rep: Build a coaster, and before placing the first track section, rotate the piece 90º. Build one piece of station, and then erase that piece. The rotation of the track will have reverted to the original direction.

**Comment by duncanspumpkin** [comment]
I'm pretty sure thats the same behavior in vanilla RCT2. I'm not saying its what it should be but that is the reason why this happens.

**Comment by IntelOrca** [comment]
The next selected track placement is always based on its previous track piece (if it exists).

**Comment by Phasedetect** [comment]
I checked, and it is not vanilla behavior. In vanilla, the game remembers the direction of the last track piece when it is deleted.
