### ISSUE TITLE
Several errors during running a save: Trying to access elements out of range

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#1662]
I get the following errors at the CMD-window during running this save (https://github.com/OpenRCT2/OpenRCT2/issues/1658) for a time. This especially happens when you speed up the game; it seems to just happen random, but there should be a reason that causes it. The longer you play, the more of these errors I get.

This is a screenshot of the cmd-window during running OpenRCT2 with the above save:
![2015-07-22_22-45-13](https://cloud.githubusercontent.com/assets/4948213/8836865/aaa2ae24-30c3-11e5-8a92-0e0dd69b51f7.jpg)

**Comment by duncanspumpkin** [comment]
Nothing really to worry about. Thats just one of our new protection features to stop invalid memory access. It crashes if its not handled correctly. Since its not crashing its handling it fine.

**Comment by IntelOrca** [comment]
@duncanspumpkin Its technically an assertion, a warning to show that the code is trying to do something it shouldn't be. Unless this is due a hacked park, this shouldn't happen.

**Comment by duncanspumpkin** [comment]
There are quite a few functions that dont do a bounds check before calling map_get_first_element_at. If any of them were to be called at the edge then it can easily trigger this message.

**Comment by IntelOrca** [comment]
At peep.c:1091, sound_play_panned is being called with a position of 0x8000, because the above if statement is not correctly comparing sign.

So I figured setting SPRITE_LOCATION_NULL to ((sint16)0x8000) would fix it, but it made it crash instantly on game load in sprite_move... I don't know why.

**Comment by duncanspumpkin** [comment]
Did you change both lines? 1094 as well?

**Comment by IntelOrca** [comment]
I tried to change SPRITE_LOCATION_NULL so it was globally fixed for any comparisons that used SPRITE_LOCATION_NULL.

**Comment by duncanspumpkin** [comment]
News item casts peep->x to uint16 so that comparison will fail. window_park_init_viewport will also fail it expects uint16. I'm sure there are lots of others. We really should go through and consistenly make it uint16 or sint16.

**Comment by IntelOrca** [comment]
I guess we should make a new typedef for map coordinate which is a sint16, since 8192 is the max position anyway and we want to allow for negative numbers when checking for map bounds etc.
