### ISSUE TITLE
Default supports for Large Scenery objects don't render correctly

### ISSUE THREAD

**Issue by danielmeinert** [OpenRCT2/OpenRCT2#16623]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (29083f4 on develop) provided by GitHub

### Describe the issue

The title says it. For LS, the default supports below are rendered complete black with some flickering pixels on the boundary. SS seems to work normally.

![grafik](https://user-images.githubusercontent.com/39702411/153478575-b9397b30-b6d4-4aad-a130-161a02b8eb8d.png)

### Steps to reproduce

1.  Build raised LS object

**Comment by Gymnasiast** [comment]
This might have been caused by the recent-ish ImageId refactor. Has this bug been in the game since around the start of the new year?

**Comment by danielmeinert** [comment]
I would say so roughly. I would say that I surely haven't noticed it before that.
