### ISSUE TITLE
No grid selected when using land tool after construction window opened.

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#1664]
After constructing a coaster, opening a land tool will not have grid selected.
![untitled-1](https://cloud.githubusercontent.com/assets/13048125/8843914/823d9cd6-3141-11e5-8acd-24f4c1d4f6fd.jpg)

**Comment by IntelOrca** [comment]
I can't reproduce this.

**Comment by daihakken** [comment]
^ I can't reproduce this either now. Maybe It got fixed by utf8(?)
