### ISSUE TITLE
Refactor gStaffDrawPatrolAreas into two variables

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#16651]
gStaffDrawPatrolAreas is holding two things, the entity id in 0x7FFF and one bit 0x8000 is used to determine if its the staff list or not, so its best to split them.

_Originally posted by @ZehMatt in https://github.com/OpenRCT2/OpenRCT2/pull/16640#discussion_r805396567_

**Comment by Gymnasiast** [comment]
It looks like this was addressed in https://github.com/OpenRCT2/OpenRCT2/pull/16740, with the "statistics" now put into `_consolidatedPatrolArea`.
