### ISSUE TITLE
"Show recent messages" is bugged

### ISSUE THREAD

**Issue by VidDaP** [OpenRCT2/OpenRCT2#16663]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (61c67af) provided by GitHub

### Describe the issue

Whenever I click on the "show recent messages" button it shows any messages I received up to that point. But when I do the same later, no more message will be added, just the once that were received before opening said window for the first time are saved there.

### Steps to reproduce

1. Click the "show recent messages" button
2. Let time progress
3. Open the window again (or let it stay open) -> no more messages get added there

**Comment by James103** [comment]
This was fixed in cb83d8ff056948f0a67dc1484ea6803339711e39. Can you please update to the [latest develop version](https://openrct2.org/downloads/develop/latest)?
