### ISSUE TITLE
Supports on a left inline-twist (exiting left) on a B&M track seem to have 2 instread of 1

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#16674]
### Operating System

Windows11 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (6c3a417 on develop) provided by GitHub

### Describe the issue

Well, it seem it not only draw the normal support of a inline twist of ther flying coaster, but also the support that a barrel roll the twister have at the same time.

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Get the twister
2. enable all drawable tracks
3. build a left inline twist (exiting one)
4. Two supports will be there

### Attachments

![Parc sans nom 2022-02-15 17-27-51](https://user-images.githubusercontent.com/83843734/154160641-92787150-be3e-4e86-b950-4ee42002be7e.png)

**Comment by Gymnasiast** [comment]
Tagging @karst (who added this code).

**Comment by karst** [comment]
Oh, that's so odd. I came across it before while testing but I couldn't reproduce it. I'll look into it
