### ISSUE TITLE
Servers disappear from master server list

### ISSUE THREAD

**Issue by fidwell** [OpenRCT2/OpenRCT2#16675]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (6c3a417 on develop) provided by GitHub

### Describe the issue

I recently upgraded my servers to the latest, which is network version 17. When I start them, they correctly appear in the master list at https://servers.openrct2.io/, and remote clients can connect. However they disappear from the list after a minute or so. The Docker logs do not show any errors when this happens.

This is happening with both headless Docker servers, and a GUI server. I am using a third-party DNS provider, so my `advertise_address` in my config.ini files are set to use it, but it has not been a problem in the past. Players can still connect to the servers by manually pasting in the address in the server browser, and I can still connect to the server by using my home network's internal IP.

### Area(s) with issue?

This bug is specific to multiplayer

### Steps to reproduce

1. Start a multiplayer server with network version 17.
2. The server appears in the [master list](https://servers.openrct2.io/).
3. Wait a minute or two.
4. Refresh the master list; the server has disappeared.

**Comment by ZehMatt** [comment]
Did you assign the DNS address at ```advertise_address```? If thats the case you are doing it wrong, that should be your public ip address and not the IP address of the DNS

**Comment by CorySanin** [comment]
@ZehMatt I have `advertise_address` blank and I experience the symptoms in the issue. Is this a required field now?

**Comment by ZehMatt** [comment]
Not that I'm aware

**Comment by CorySanin** [comment]
Filling it in made no difference. I declare this a valid defect!

**Comment by ZehMatt** [comment]
I can confirm that something is wrong with the latest develop version. I'll see if I can figure out whats up

**Comment by fidwell** [comment]
> Did you assign the DNS address at `advertise_address`? If thats the case you are doing it wrong, that should be your public ip address and not the IP address of the DNS

Sorry for the late reply, but yeah my `advertise_address` is set to `fidwell.duckdns.org` which is basically just a wrapper of sorts for my public IP. I've been using DuckDNS for about 3 weeks now and haven't had any issues until yesterday.

**Comment by ZehMatt** [comment]
The server seems to respond following sending a heartbeat:
```
{"status":500,"message":"invalid token"}
```

**Comment by ZehMatt** [comment]
This issue appeared with #16259 because it sends the master server the map size of x,y where previously this has been a single number. The master server needs to be updated

**Comment by fidwell** [comment]
That's a wild side effect! Makes sense though. Glad it wasn't just me going crazy

**Comment by IntelOrca** [comment]
Should be resolved now.

**Comment by fidwell** [comment]
Verified! Thanks so much!
