### ISSUE TITLE
Many JS plugins, placing rides, and main Options menu crashes game on MacOS latest

### ISSUE THREAD

**Issue by ltsSmitty** [OpenRCT2/OpenRCT2#16678]
### Operating System

MacOS 11.6.1

### OpenRCT2 build

~~Latest dev as of 2/14 - not certain since app crashes when opening Options~~
b22ac05

### Describe the issue

App crashes on MacOS with segmentation fault 11 when trying to do various things, such as placing flat rides, opening most plugins, and opening the `Options` menu from the title page. Here are 6 crash reports for different rides and the `Options` menu crash

[Recording of it in action](https://share.getcloudapp.com/WnuqPJOG)

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Open the game
2. Select  options (top-right)
3. Observe instant crash

### Attachments

[Archive.zip](https://github.com/OpenRCT2/OpenRCT2/files/8083610/Archive.zip)

**Comment by James103** [comment]
Commit from video: b22ac05
I was able to get the commit by playing the video in slow motion and copying it from the bottom left corner where the output of `openrct2 --version` is displayed.

**Comment by Gymnasiast** [comment]
There is also an easier way: go to `About OpenRCT2` and click the button to copy the version string.

**Comment by ltsSmitty** [comment]
> opening most plugins

Yes, js plugins. I opened the issue at first because IntelOrca asked me to test if my new JS plugin works with more than 64 widgets on the new build, so i tried it. The first thing I tried was opening my plugin, which crashed. After that I started doing other things, such as placing a merry go round, which caused a crash. Then I tried opening the Options menu, which crashed.

So my title reflects the order of things that I tried, and seeing the app crash on the Options menu made me realize that is likely non-js-plugin related and probably more significant

**Comment by IntelOrca** [comment]
@ltsSmitty are you building OpenRCT2 yourself, or is this from openrct2.org?

**Comment by ltsSmitty** [comment]
ah, this was downloaded from openrct2.org. do i need to build myself?

**Comment by ltsSmitty** [comment]
Plugin folder deactivated, app still crashes

**Comment by Gymnasiast** [comment]
Looking at the crash reports, it seems they all crash in WidgetDraw, which does not do a lot of interesting stuff, except for retrieving an element from an array without bounds checking. I’m going to prepare a possible fix.

**Comment by Gymnasiast** [comment]
Can you try this build: https://github.com/OpenRCT2/OpenRCT2/suites/5351495962/artifacts/167481782

And if it crashes, please include the report. The crash might have “moved”.

**Comment by IntelOrca** [comment]
It would be good to know why, when this started happening. The fix @Gymnasiast has done just hides the problem. @ltsSmitty are you able to work out when it started crashing by downloading old builds?

**Comment by ltsSmitty** [comment]
I've gone through the oldest dev build [v0.3.5.1-866ad2c] on the downloads list, and the issue still occurs. I'm unable to build myself. But I am totally happy to try as many versions as are provided to me. can move chat to discord (Smitty#5288 or in #development) if that's easier.

**Comment by ltsSmitty** [comment]
hmm. i'm going through the [binaries](https://github.com/Limetric/OpenRCT2-binaries/releases) and it appears it's only the latest that crashes. I checked out 4 other releases and they all play fine. I triple checked that latest is the only one to crash, and it is. hopefully that helps!

ffe67ff33e223e644d1208bc3a7dd93b27b5e0be crashes
ff909cc28654d27691794de6c3385f4e9cd1e3fe plays fine
fea0a1480fc8d61d6f1d5e57c5459502e598b527 plays fine
fea0a1480fc8d61d6f1d5e57c5459502e598b527 plays fine
e503603018a7c48eea0d4cf12a80b887e5aa3dd4 plays fine

**Comment by Gymnasiast** [comment]
@ltsSmitty It seems you’re on an x86-bases Mac, is that correct? What is the model?

@adam-bloom Can you reproduce these crashes?

**Comment by adam-bloom** [comment]
@Gymnasiast I went digging in discord to find the last user who reported this - and it was a segfault in `WidgetDraw`. I don't quite understand the scenario needed to cause these out of bounds conditions (and haven't been able to reproduce it), but let me know (here or Discord) if you've got an easy way to cause this and I can test as well. Since your linked PR addresses the `WidgetDraw` segfault, I'd vote that's good to merge and should address this.

https://discord.com/channels/264137540670324737/875468371884380210/940415736147505183 has the stack trace, but I'll paste it here as well:
```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000000010ea
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [41803]

VM Regions Near 0x10ea:
--> 
    __TEXT                      10ad35000-10aecd000    [ 1632K] r-x/r-x SM=COW  /Users/*/Desktop/OpenRCT2.app/Contents/MacOS/OpenRCT2

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   io.openrct2.OpenRCT2          	0x000000010ad7eecf WidgetDraw(rct_drawpixelinfo*, rct_window*, short) + 4447
1   io.openrct2.OpenRCT2          	0x000000010ad82607 WindowDrawWidgets(rct_window*, rct_drawpixelinfo*) + 343
2   io.openrct2.OpenRCT2          	0x000000010ae5b115 WindowRideConstructionPaint(rct_window*, rct_drawpixelinfo*) + 69
3   libopenrct2.dylib             	0x000000010b10eadb window_draw_core(rct_drawpixelinfo*, rct_window*, int, int, int, int) + 811
4   libopenrct2.dylib             	0x000000010b10b9cf window_visit_each(std::__1::function<void (rct_window*)>) + 95
5   libopenrct2.dylib             	0x000000010b110367 window_draw_all(rct_drawpixelinfo*, int, int, int, int) + 135
6   libopenrct2.dylib             	0x000000010b1a6948 OpenRCT2::Paint::Painter::Paint(OpenRCT2::Drawing::IDrawingEngine&) + 88
7   libopenrct2.dylib             	0x000000010afe6f32 OpenRCT2::Context::Draw() + 66
8   libopenrct2.dylib             	0x000000010afe6c87 OpenRCT2::Context::RunVariableFrame(float) + 295
9   libopenrct2.dylib             	0x000000010afe6ae3 OpenRCT2::Context::RunFrame() + 307
10  libopenrct2.dylib             	0x000000010afe6338 OpenRCT2::Context::RunGameLoop() + 120
11  libopenrct2.dylib             	0x000000010afe5a06 OpenRCT2::Context::Launch() + 1206
12  libopenrct2.dylib             	0x000000010afe0f61 OpenRCT2::Context::RunOpenRCT2(int, char const**) + 33
13  io.openrct2.OpenRCT2          	0x000000010ad3e773 main + 179
14  libdyld.dylib                 	0x00007fff204a7f3d start + 1
```
