### ISSUE TITLE
unnecessary local variable in openrct2-ui/windows/RideConstruction.cpp

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#16688]
The properties variable appears unused. Plan of action for removing it?

https://github.com/OpenRCT2/OpenRCT2/blob/795144662acb89ff7b36f43946533441c7bb37d3/src/openrct2-ui/windows/RideConstruction.cpp#L3401-L3411

**Comment by ZehMatt** [comment]
That style of variable declaration is generally discouraged in C++, this just means this function requires a general overhaul 🙃
