### ISSUE TITLE
Rotodrop car bug

### ISSUE THREAD

**Issue by Legotown55** [OpenRCT2/OpenRCT2#16706]
### Operating System

Windows 10 64 bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (d870892 on develop) provided by GitHub

### Describe the issue

When you build a rotodrop tower and save the game and go back into that game the totodrop car has vanished

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Build a rotodrop tower and open it
2. Save the game
3. then go back into the game

**Comment by spacek531** [comment]
good: OpenRCT2, v0.3.5.1 (05b80ac on develop) provided by GitHub

also good: OpenRCT2, v0.3.5.1 (f211750 on develop) provided by GitHub

**Comment by scaryghosty** [comment]
tested following instructions with same OS, build v0.4.0 (meaning new save format in effect), bug did not trigger. seems rectified.

**Comment by Broxzier** [comment]
Thanks for confirming. Closing this since the OP hasn't responded in 3 months.
