### ISSUE TITLE
Litter and vomit are not added to paths when there is already a large amount present

### ISSUE THREAD

**Issue by sr1gh** [OpenRCT2/OpenRCT2#16737]
There seems to be a limit on how much litter and vomit can be present in the park, and once the limit is reached, no more is added and if a guest vomits, the vomit disappears.

**Comment by duncanspumpkin** [comment]
There is no limit on the number of litter on a single tile. (litter and vomit are both litter). There is a limit on total litter in the park though, 500.

**Comment by ocalhoun6** [comment]
Maybe the total litter limit should be raised, to bring it in line with the other raised limits in the NSF?

**Comment by duncanspumpkin** [comment]
Feel free to open a discussion on the topic. The limit is very easily modified but I would want others opinions before any changes

**Comment by ocalhoun6** [comment]
#16739
