### ISSUE TITLE
CMAKE CXXFLAGS are unsupported 

### ISSUE THREAD

**Issue by That-Human-Being** [OpenRCT2/OpenRCT2#16748]
### Operating System

Windows 10 64-Bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (f211750 on develop) provided by GitHub

### Describe the issue

When I go to generate a makefile cmake gives this message but successfully generates a makefile
```
Unsupported CXXFLAG: -Wmissing-variable-declarations
Unsupported CXXFLAG: -Wunreachable-code-break
Unsupported CXXFLAG: -Wrange-loop-analysis
Unsupported CXXFLAG: -Wtautological-unsigned-zero-compare
```

### Area(s) with issue?

Building the game

### Steps to reproduce

1. cmake  -DDISABLE_HTTP:BOOL="1" -DDISABLE_IPO:BOOL="0" -DDISABLE_NETWORK:BOOL="1" .. -g "mingw makefiles"

**Comment by Gymnasiast** [comment]
Which version of GCC do you use?

**Comment by IntelOrca** [comment]
This is information rather than a warning or bug. It just means the compiler you are using doesn't support those flags. It won't prevent the game from building.

**Comment by That-Human-Being** [comment]
Oh, Ok thanks
