### ISSUE TITLE
Building queue into exit possible

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#16753]
### Operating System

Windows 11 Beta Insider

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (d219a99 on develop) provided by GitHub

### Describe the issue

This issue has existed for over 20 years, could you fix it?

### Area(s) with issue?

The bug also exists in RCT2 (vanilla)

### Steps to reproduce

1. Build ride
2. build queue line starting from entrance
3. connect to exit
[Githubbug.zip](https://github.com/OpenRCT2/OpenRCT2/files/8192641/Githubbug.zip)
![ertg](https://user-images.githubusercontent.com/94884086/156925015-0c6210d5-14f1-453f-b79d-72d91714390e.png)

**Comment by duncanspumpkin** [comment]
What do you see as the solution? Is this actually an issue

**Comment by 733737** [comment]
the solution could be when the ghost of the path is drawn, not automatically conect the (in this case) northwest edge

**Comment by Broxzier** [comment]
This whole scenario is nonsense, so I don't really consider this a bug. It's perfectly fine to use queue paths as normal paths, so also to have them connect to exits.

**Comment by Lastorder-DC** [comment]
1. This is not a bug
2. You can always fix this situation by replace last queue path with regular path.

**Comment by 733737** [comment]
how is this not a bug?

**Comment by Broxzier** [comment]
There is no logical reason to build a queue in front of the exit, except for using a queue as the exit path in which case the queue _should_ connect, so there is no reason to change the current behaviour.
