### ISSUE TITLE
Options to select the marquee style

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#1676]
Just came up an idea that it might be good if the game can let players to select the marquee style, i.e. ALL UPPERCASE (RCT1 Style) or Both lower and upper case (RCT2 Style).
edit: If this feature isn't something that requires only few lines to change, just ignore it right now :P
![untitled-1](https://cloud.githubusercontent.com/assets/13048125/8888913/de12c5cc-32f4-11e5-988a-619ea05e90f6.jpg)
![untitled-2](https://cloud.githubusercontent.com/assets/13048125/8888914/de1a3f32-32f4-11e5-9583-a5fca09553d2.jpg)

**Comment by Gymnasiast** [comment]
Yeah, I would like to have it as well. I think RCT1's marquees are easier to read. Also, numbers were displayed in an easier-to-read 7-segment style.

**Comment by duncanspumpkin** [comment]
If you modify the viewport banner paint setup function this could easily be added. It wouldn't work on paths at the moment though as they haven't been implemented.

**Comment by Gymnasiast** [comment]
Implemented, so this issue can be closed.
