### ISSUE TITLE
kubuntu and Windows 10 cross play seem to have alot of desyncs

### ISSUE THREAD

**Issue by Shadowblitz16** [OpenRCT2/OpenRCT2#16782]
### Operating System

Kubuntu 20.04

### OpenRCT2 build

stable v0.3.5.1 and latest dev

### Describe the issue

It seems there are cross play desyncs. 
I can't confirm but my friend is on windows 10 and I'm on kubuntu and we can't even play for 10 seconds before he gets disconnected.

We both have stay connected after desync's and I even tried to play on my server as a separate instance from the host.
Nothing seems to work and the game currently as far as networking goes is completely unplayable.

If noone connects and I play on my own server alone I can get like 10-20 mins of play before I get desync but I never get disconnected.

### Area(s) with issue?

This bug is specific to multiplayer

### Steps to reproduce

1. Run version 0.3.5.1 on both kubuntu 20.04 and windows 10 (latest as of posting)
2. Use a seperate instance of the game as server only and scroll to the corner of the map
3. Simulate some latancy between the kubuntu server and client instance and the windows 10 client instance
4. try do to anything

This might also be a issue with the gog and stream versions.
Also I have roller coaster tycoon deluxe and he doesn't but we both have roller coaster tycoon 2 triple thrill pack.

### Attachments

I would but idk how to debug or where logs are stored on both our sides.

**Comment by Shadowblitz16** [comment]
So I have successfully gotten around this problem with rebooting my router.
This is kinda why reliable ordered networking is needed, so the game can guarantee packets are not missed and the game does not desync

**Comment by ZehMatt** [comment]
Game already uses TCP for networking which is reliable, desyncs happen for other reasons.
