### ISSUE TITLE
cannot build entrance here, too high

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#16785]
### Operating System

Windows 11 Beta Insider

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (1c781a8 on develop) provided by GitHub

### Describe the issue

can't build entrance or exit on station at 590ft

### Steps to reproduce

1. build station at 590 ft
2. try to place entrance
3. error message produced

### Attachments

![issue](https://user-images.githubusercontent.com/94884086/158039079-f71c41eb-bafe-40f3-ab1c-d9d0fe589eb9.png)
[bug report.zip](https://github.com/OpenRCT2/OpenRCT2/files/8238714/bug.report.zip)

**Comment by ocalhoun6** [comment]
This is probably happening because you're near the height limit of the game. The track can be placed because it's only 2 units high, but the exit is 3 units high, and the entrance is at least 4. That puts the top of the entrance/exits above the height limit of the game.

It's already giving you a descriptive error about why you can't do this ... I don't know what else you expect it to do.

**Comment by 733737** [comment]
I want the station to not be buildable then

**Comment by ocalhoun6** [comment]
Then you still have a problem in the edge case of a station 3 units below the height limit. An exit-only station could work at that height, but a station with an entrance would _not_ work at that height. And the game has no way to know which type of station you're building until you actually place the entrance/exit buildings.

(Also, why prevent people from, say, building decorative/trackitecture station pieces at that height?)

**Comment by 733737** [comment]
how about you change entrance and exits to disable collision detection

**Comment by 733737** [comment]
[bug report with no entrance or exit still error.zip](https://github.com/OpenRCT2/OpenRCT2/files/8238766/bug.report.with.no.entrance.or.exit.still.error.zip)

**Comment by 733737** [comment]
[exit vanishes when station or exit is lowered or raised with ti.zip](https://github.com/OpenRCT2/OpenRCT2/files/8238774/exit.vanishes.when.station.or.exit.is.lowered.or.raised.with.ti.zip)

**Comment by 733737** [comment]
it says can't raise element here invalid clearance

**Comment by duncanspumpkin** [comment]
As stated by @ocalhoun6 you are at the height limit you cannot build at that height as the clearance is too high. This is not a bug it is a limitation of the engine and no overriding it with a cheat would not be sensible as this is not just a limitation of the tile element but one of the fundamental limits of the engine.
