### ISSUE TITLE
Openrct2 uses wrong file dialog when you try to selected rct2 assets for the first time.

### ISSUE THREAD

**Issue by Shadowblitz16** [OpenRCT2/OpenRCT2#16804]
### Operating System

KDE neon

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (61c67af on HEAD)
Linux (x86-64)

### Describe the issue

The description can be found here.. https://github.com/OpenRCT2/OpenRCT2/discussions/16803

Basicly the gog option opens the correct file dialog while the first option opens what seems to be a very old gtk dialog that doesn't even work.

### Steps to reproduce

1. Fresh install of openrct2 via master ppa on kde neon
2. Select ok when the popup says you need to select your rct2 install
3. Select the first option
4. See that it opens a ugly, non functional file dialog
5. Repeat step 1 and 2
6. This time choose gog option
7. See that it opens a qt window that works

### Attachments

![image](https://user-images.githubusercontent.com/2453707/158531731-6ae9c25e-8925-4228-83f4-7c9252b438e2.png)
![image](https://user-images.githubusercontent.com/2453707/158531822-f9999b85-14af-4989-bff5-b796f4885de3.png)

**Comment by duncanspumpkin** [comment]
You have not specified the hash of the build can you verify this against the latest develop build as there have been tweaks to some of this area.

**Comment by Shadowblitz16** [comment]
> You will need to compile it yourself to check as ppa's don't compile it correctly.

wait what?! the ppa's don't compile it correctly? why? can't this be fixed?

**Comment by duncanspumpkin** [comment]
Its a long standing issue with the ppa that it doesn't add the commit hash information who knows what else it doesn't bother to do. Feel free to try correct it.

**Comment by Shadowblitz16** [comment]
so by modifying the launch command and waiting I get...
```
OpenRCT2, v0.3.5.1 (61c67af on HEAD)
Linux (x86-64)
```

**Comment by duncanspumpkin** [comment]
Okay so thats years out of date try reproduce it on develop.

**Comment by Shadowblitz16** [comment]
> Okay so thats years out of date try reproduce it on develop.

these are the ppa's listed there is no develop
```
Please choose from the following available PPAs:
 * 'experimental':  experimental
 * 'jansson':  jansson
 * 'master':  OpenRCT2 release versions
 * 'nightly':  OpenRCT2 nightly builds
 * 'pre-release':  pre-release
```

**Comment by janisozaur** [comment]
> Also these are the ppa's listed. There is no develop


Indeed, that's because launchpad only offers building automatically once per day or scheduling a build manually. `develop` is whatever is current at this branch, it can change several times a day.
