### ISSUE TITLE
Building design as multiplayer head uses incorrect vehicle if multiple vehicle types available

### ISSUE THREAD

**Issue by Shadowblitz16** [OpenRCT2/OpenRCT2#16808]
### Operating System

KDE Neon

### OpenRCT2 build

v0.3.4.1

### Describe the issue
Building track designs uses the wrong vehicle in multiplayer environments with rides that have multiple vehicles available

### Area(s) with issue?

OpenRCT2 multiplayer

### Steps to reproduce

1. load multiplayer server from main menu using electric fields
2. build raving rockets design
3. coaster uses automobile cars instead of rocket cars as it should

### Attachments

https://cdn.discordapp.com/attachments/691736850980667514/954220482473914378/unknown.png
https://cdn.discordapp.com/attachments/691736850980667514/954220696869957692/unknown.png
https://cdn.discordapp.com/attachments/691736850980667514/954221138693726238/unknown.png
https://cdn.discordapp.com/attachments/691736850980667514/954221938870464592/unknown.png
https://cdn.discordapp.com/attachments/691736850980667514/954224506417840128/unknown.png
https://cdn.discordapp.com/attachments/691736850980667514/954225164428656690/unknown.png)

**Comment by spacek531** [comment]
Was it using the rockets car or a different car?

**Comment by Shadowblitz16** [comment]
I didn't change the cars so whatever it came with

**Comment by spacek531** [comment]
'Whatever it came with' is not necessarily the cars it is meant to have, which are determined by the scenario. There is a warning about using the wrong cars when building a design. So, the question still remains.

**Comment by Shadowblitz16** [comment]
I was on the second beginner level of openrct2, the farm one.
I just built it and tested it and it didn't work.

**Comment by spacek531** [comment]
It works fine for me. Please take a picture of the issue happening.

**Comment by Shadowblitz16** [comment]
oh! are speed values different in multiplayer?
I was the host so I shouldn't be getting any dsync

**Comment by Shadowblitz16** [comment]
@spacek531 yep I can reproduce it in multiplayer.
![image](https://user-images.githubusercontent.com/2453707/158740980-fb1b7e61-1ddc-4c44-98dc-7d6d4b25ddc7.png)

**Comment by spacek531** [comment]
That ride is made for rocket cars, not automobiles. Can you test other blueprints with other ride types that have multiple trains, like wooden coasters?

**Comment by Shadowblitz16** [comment]
@spacek531 I don't really want to test but if I come across another incompatible train type I can post it here.

**Comment by duncanspumpkin** [comment]
As @spacek531 said this isn't a bug if you haven't built the track design with the ride object that it was designed for then you can't guarantee that it will work. That is why the warning message is displayed saying that it might perform differently.

**Comment by Shadowblitz16** [comment]
@duncanspumpkin so I confirmed this with Spacek on discord

here are a few pictures of me testing it with him. 
https://cdn.discordapp.com/attachments/691736850980667514/954220482473914378/unknown.png
https://cdn.discordapp.com/attachments/691736850980667514/954220696869957692/unknown.png
https://cdn.discordapp.com/attachments/691736850980667514/954221138693726238/unknown.png
https://cdn.discordapp.com/attachments/691736850980667514/954221938870464592/unknown.png
https://cdn.discordapp.com/attachments/691736850980667514/954224506417840128/unknown.png
https://cdn.discordapp.com/attachments/691736850980667514/954225164428656690/unknown.png

**Comment by spacek531** [comment]
I can reproduce this bug

**Comment by duncanspumpkin** [comment]
I tested this a good bit and there is a potential issue caused by mistakes with the NSF that could potentially cause the incorrect vehicle to be chosen.
