### ISSUE TITLE
Staff walk outside intended patrol area

### ISSUE THREAD

**Issue by fidwell** [OpenRCT2/OpenRCT2#16815]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (9ef7a4c on develop)

### Describe the issue

When setting staff patrol area, they will walk on the tiles adjacent to the patrol area, but are not included in it. After reaching the center of that tile, they will turn around and walk back to the patrol area.

I would have expected that the peep remains on the single tile, sort of like if you drop a peep on a single tile of path---they can't leave it whatsoever.

### Area(s) with issue?

Granular patrol area, which I guess is a NSF thing

### Steps to reproduce

1. Hire a staff member
2. Set their patrol area to a single tile and place the peep on it (preferably an all-grass or all-path area)
3. The peep will walk to one of the four adjacent tiles; when it reaches one, it will turn around and walk back to the patrol area.

It will continue to do this until its patrol area changes or it is manually moved.

**Comment by duncanspumpkin** [comment]
This is expected behaviour for single tile. Peeps must have a tile to walk to when you pen them in to a single tile they will not listen to patrol area boundaries. This matches vanilla behaviour and would be incredibly hard to change without just freezing the staff.
