### ISSUE TITLE
sprite exportalldat prints illegal backslashes

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#16821]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.3.5.1 d7f5995

### Describe the issue

When using `sprite exportalldat`, the json output uses backslashes for path instead of forward slashes, which is illegal in json, it means that users using the offsets provided by the game must manually convert the backslashes to forward slashes before using them in a parkobj json.

### Steps to reproduce

1. export sprite of dat
2. observe backslash

**Comment by Gymnasiast** [comment]
Windows-only bug.
