### ISSUE TITLE
Fallback mechanism for multiplayer does not warn user when substituting different vehicle

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#16820]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.3.5.1 d219a99

### Describe the issue

When building a track design in multiplayer and the game substitutes a car for the original, no warning is given for the substituted car, as occurs when the car a design requires is not available.

### Steps to reproduce

1. Open multiplayer server with Electric Fields, build Black Widow wooden roller coaster design
2. No warning 
3. Open single player Electric Fields, build Black Widow wooden roller coaster design
4. Warning

**Comment by spacek531** [comment]
I posted this bug report, now I cannot reproduce. Funky.

**Comment by duncanspumpkin** [comment]
I corrected it early today. It wasn't actually a bug in the warning it was the fact that the vehicle object wasn't getting serialised.

**Comment by spacek531** [comment]
I was not experiencing the warning when the game chose the default object because of improper serialization, which is why I made the bug report. I can't reproduce it now on the same build.
