### ISSUE TITLE
Scenery window crashes when remember scenery item is out of bounds

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#16829]
### Operating System

Windows 11

### OpenRCT2 build

ea435f936173f0346e0c58e633d013ddae316cb6

### Describe the issue

The game crashes when opening the scenery window, when the remembered scenery item is an out of bounds entry index.

### Steps to reproduce

1. Open Electric Fields.
2. Select the last candy scenery item in the scenery window.
3. Open Leafy Lake.
4. Open the scenery window.

**Comment by Broxzier** [comment]
This seems to have been fixed already by this commit: a8eb6f21a26dfd23f23d8f5678aa6f17935ff59b
