### ISSUE TITLE
[Select rides by track type (like in RCT1) Monorail wrong picture

### ISSUE THREAD

**Issue by Horsti12** [OpenRCT2/OpenRCT2#1683]
The Monorail shows in OpenRCT2 the wrong picture compared to RCT1.

In RCT1 it shows the "Small Monorail Cars" while in OpenRCT2 it shows the "Streamlined Monorail Trains".
Please change the default Monorail picture to "Small Monorail Cars"

![rct1 style monorail wrong icon](https://cloud.githubusercontent.com/assets/12634026/8893057/7ae327b8-337f-11e5-9d59-909bb8ba63a3.png)

**Comment by duncanspumpkin** [comment]
The steamlined monorail looks much more like what you would expect a monorail to look like. 
https://www.google.co.uk/search?q=monorail&safe=off&es_sm=122&source=lnms&tbm=isch&sa=X&ved=0CAcQ_AUoAWoVChMI9oCJ1q74xgIVlAjbCh2fBQAP&biw=1920&bih=955

Not a single picture looks like the RCT1 version. I say no point changing it to a less used type.

**Comment by daihakken** [comment]
For me, I don't think the pictures should be exactly the same as RCT1, as some ride types (notably Wooden and Looping) have different designs in RCT2, so it would be quite unnecessary to do so.

**Comment by Gymnasiast** [comment]
What @duncanspumpkin says is largely the reason why I chose the Streamlined Cars as the default picture in the first place. And I have explained that to you before. It does get a bit annoying that you keep arguing, even when everybody else disagrees - and in many more issues than this one.

**Comment by daihakken** [comment]
IMO it is really unnecessary right now,  and will add some extra burden to developers. but it might be a good idea when in future, every code has been reverse-engineered, and started to import the RCT1 style rides (if there are any other than wooden & looping RC) into OpenRCT2.

**Comment by Horsti12** [comment]
Ah ok then please close the issue :D CLOSED!
