### ISSUE TITLE
Support rectangular heightmaps

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#16840]
With [support for rectangular maps](https://github.com/OpenRCT2/OpenRCT2/pull/16259) added to the game, the requirement for heightmaps to be square is no longer necessary.

https://github.com/OpenRCT2/OpenRCT2/blob/5edc5617152bf360015120dfd6eaf7595b19d6ee/src/openrct2/world/MapGen.cpp#L662-L667

The code below the above check relies on the assumption that the width and height match. This needs to be refactored slightly. Some changes to the related functions might be necessary, though most already threat width and height separately.

https://github.com/OpenRCT2/OpenRCT2/blob/5edc5617152bf360015120dfd6eaf7595b19d6ee/src/openrct2/world/MapGen.cpp#L773

**Comment by ArLough** [comment]
take

**Comment by ArLough** [comment]
Hi, I'm new to contributing and I'd like to take this issue. Is there anything else I should do to take the issue?

**Comment by Broxzier** [comment]
@ArLough nope, that's all you have to do. For questions you can ask either here or on Discord. Good luck!

**Comment by ArLough** [comment]
Hi @Broxzier, I was wondering if you would like me to remove the error checking entirely or substitute it with a different error check that takes rectangular maps into consideration? If the latter, what would you like the error checking to look like?

**Comment by Broxzier** [comment]
Hey @ArLough, the checks are not necessary anymore, so the strings can be removed.

**Comment by tupaschoal** [comment]
For anyone reading, this is up for grabs again. It might be worth looking into the comments of the  PR linked above for insight
