### ISSUE TITLE
Multiple scenery items underflow on their bulldoze prize

### ISSUE THREAD

**Issue by liny-odell** [OpenRCT2/OpenRCT2#16857]
### Operating System

Debian 10 on chrome os 99

### OpenRCT2 build

OpenRCT2, v0.3.5.1-776 (4cdd9bd81 on develop)

### Describe the issue

Title says it all.

### Steps to reproduce

Open "Canary Mines" from RCT1 CF and try to remove any of the following and observe the following screenshot.
Mine junk piles
Wall Support structures

### Attachments

![image](https://user-images.githubusercontent.com/7400549/159635642-0e2241b6-a2e3-431a-a9ca-31808b610e07.png)

**Comment by liny-odell** [comment]
Tested a random selection of parts from the walls tab and most i landed on had the issue.

**Comment by tupaschoal** [comment]
@duncanspumpkin sounds like #16846 didn't go as planned

**Comment by duncanspumpkin** [comment]
Yup someone wrote the json code wrong.

**Comment by tupaschoal** [comment]
Closed by
