### ISSUE TITLE
Soft Toy doesn't change color

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#16869]
### Operating System

Windows 11 Insider

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (0e607ed on develop) provided by GitHub

### Describe the issue

When you place a soft toy stand for a soft dinosaur toy, changing the color of the item has no effect, the item stays purple

### Steps to reproduce

1. place soft toy stand
2. try to change color
3. color doesn't change in preview window

### Attachments

[softtoybug.zip](https://github.com/OpenRCT2/OpenRCT2/files/8341306/softtoybug.zip)
![asXsd](https://user-images.githubusercontent.com/94884086/159913842-b33df468-a733-4f2c-8f72-f440a46b3ba7.png)

**Comment by IntelOrca** [comment]
Which custom object is this?

**Comment by oli414** [comment]
It's rct2tt.ride.softoyst.json from Time Twister @IntelOrca

**Comment by 733737** [comment]
not custom

**Comment by IntelOrca** [comment]
Not sure what to do about this. Soft toys are not shop items that can be coloured. However the colour still controls the colour of the tile element, which in this case is not colourable.

I think we will need to allow ride objects (shops in particular) to set flags to say whether they can be coloured or not.

**Comment by Gymnasiast** [comment]
Shops _can_ set a flag that indicates they cannot be recoloured, but Frontier forgot to set it on this stall. I just pushed a fix for this to the objects repository. We will need to do an objects release before this fix ends up in the game, though.

**Comment by spacek531** [comment]
Doesn't RCT1 show the stall itself instead of the sale item, or am I mis-remembering?

**Comment by spacek531** [comment]
Doesn't RCT1 show the stall itself instead of the sale item, or am I mis-remembering?

**Comment by Gymnasiast** [comment]
It does.
