### ISSUE TITLE
Refactor `window_editor_object_selection_select_object` to return a message

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#16867]
`window_editor_object_selection_select_object` currently returns its success through a bool and also the global `gGameCommandErrorText`. It should be refactored to return a `GameAction::Result` to remove the use of the global.

**Comment by Nekoral** [comment]
Could i try this as a first issue ?

**Comment by Broxzier** [comment]
Sure, go ahead! If you have any questions about the code, you can ask for help either here or on Discord.
