### ISSUE TITLE
TrackElementDescriptor::Price refactor

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#16879]
Whilst investigating #16877 I noticed that the `TrackElementDescriptor::Price` is incorrect. Its a price modifier not an actual price its used to work out the price using the following calc (RideTrackPrice * TED::Price) / 65536. 

Therefore the units of `TrackElementDescriptor::Price` should be changed to `uint32_t` and the name changed to `PriceModifier` and a comment added stating that it should be used as above.

**Comment by norisa118** [comment]
I would like to take this issue please !! Can I be assigned?

**Comment by duncanspumpkin** [comment]
Great, go for it.
