### ISSUE TITLE
readme.txt file has incorrect information.

### ISSUE THREAD

**Issue by Galbi3000** [OpenRCT2/OpenRCT2#16880]
On line 104 of the distribution\readme.txt file it states that the file to edit for changing the paths to RCT1/RCT2 is openrct2.cfg when it should be config.ini!

There is also a minor typo on line 84, 'of' should be 'off'. 🙂

**Comment by janisozaur** [comment]
i encourage you to submit a fix yourself: 
![Screenshot_2022-03-26-00-17-32-97_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/550290/160213751-03519cbd-80a4-4374-9cbc-4c0d52dd7c5e.jpg)

**Comment by tupaschoal** [comment]
Thanks for reporting @Galbi3000 ! README/txt files are pretty easy to change and submit a PR, you can do it straight from the GH interface, wanna give it a try?

**Comment by 733737** [comment]
I submitted one since I am trying to learn how to do it myself (#16883)
