### ISSUE TITLE
Got segfault after adding in a lot of objects in the object selection

### ISSUE THREAD

**Issue by WalterHuober** [OpenRCT2/OpenRCT2#16886]
1. My OS is Manjaro.
2.   The build of OpenRCT2 I was running is v0.3.5.1-669(https://github.com/OpenRCT2/OpenRCT2/commit/9b1c915f4d98d6c891170a59364cbde367f80469 on makepkg). The crash also happens on OpenRCT2, v0.3.5.1-523 (29083f4cb2 on makepkg), and on the release version. 
3.   Edit: To reproduce it, open a park, open the object selection, select a specific custom scenery group: The DKMP's 'RCC colour objects'. It says: Warning to many objects selected. Then click on the close button of the object selection and the game crashes.
4.   The crash folder is empty. The only info I got was in the command line where it printed "openrct2 $ Speicherzugriffsfehler (Speicherabzug geschrieben)" read segfault.

**Comment by tupaschoal** [comment]
@Walter-SonyAI please use the issue template we provide, it gives use the necessary information to investigate the issue.

**Comment by James103** [comment]
At the very least,
1. What OS are you running?
2. What build of OpenRCT2 are you running? (You can see the version by running openrct2 --version or copy it from the About window. Open the "Disk and game options" menu (floppy disk on the top toolbar), choose "About 'OpenRCT2'" and click the copy button next to the version information)
3. Are you able to reproduce this issue? If so, can you please list the steps to reproduce?
4. Do you have any crash files generated in your OpenRCT2 user directory's `crash` folder? If so, please attach them here.

**Comment by Walter-SonyAI** [comment]
1. My OS is Manjaro. 
2. The build of OpenRCT2 I was running is v0.3.5.1-669(9b1c915f4d on makepkg).
3. To reproduce it, open a park, e.g. forest frontiers, open the object selection, select everything all scenery groups from RCT1, Loopy Landscape, Added Attractions, RCT2, Time Twisters, Wacky Worlds, and the recolorable custom versions of these scenery groups from the DKMP community, after that, select all possible paths, all landtypes, the invisible start platform and the few other scenery elements that are not included yet. Then I click close on the object selection and the game crashes. 
4. The crash folder is empty. The only info I got was in the command line where it printed "openrct2 $ Speicherzugriffsfehler (Speicherabzug geschrieben)" read segfault.

**Comment by Gymnasiast** [comment]
Still suffering from this issue?
