### ISSUE TITLE
weird water coaster sprite duplication bug

### ISSUE THREAD

**Issue by pGore33p** [OpenRCT2/OpenRCT2#16890]
### Operating System

Windows 10 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (76c5217 on develop) provided by GitHub

### Describe the issue

for some reason whenever the water coaster goes into turns, it kind of... duplicates? its hard to explain. the screenshot shall make it clearer.

### Area(s) with issue?

New Save Format (NSF), Building the game

### Steps to reproduce

1. look at a water coaster operating.

### Attachments

![image](https://user-images.githubusercontent.com/10586092/160343204-2aa8ef08-7b7e-4c76-a8d0-52eb0327e038.png)

**Comment by pGore33p** [comment]
![image](https://user-images.githubusercontent.com/10586092/160391257-4e648c86-a9f8-44fb-8705-dea5a478c2f7.png)
same actually applies to the splash boats

**Comment by 733737** [comment]
i noticed this a few days ago and thought it was a hacked ride

**Comment by Broxzier** [comment]
git bisect shows that 8aafab2a70eadb462cbd523783beb670913d19b0 is the first bad commit.

**Comment by duncanspumpkin** [comment]
> git bisect shows that [8aafab2](https://github.com/OpenRCT2/OpenRCT2/commit/8aafab2a70eadb462cbd523783beb670913d19b0) is the first bad commit.

Yes that looks suspect it should have become variant not split now you've an awkward bit of state.

**Comment by duncanspumpkin** [comment]
I've looked at it for a while and I don't even see the point of `void vehicle_visual_splash_boats_or_water_coaster` existing. Thats the function causing the issues. I can't see why its causing the issue though as it looks like it would be caused in vanilla.
