### ISSUE TITLE
Modular Objective System

### ISSUE THREAD

**Issue by MaxMallon** [OpenRCT2/OpenRCT2#16899]
The system designed is more flexible and powerful than the original the concept from the original discussion. 

### Discussed in https://github.com/OpenRCT2/OpenRCT2/discussions/16457

<div type='discussions-op-text'>

<sup>Originally posted by **MaxMallon** January 17, 2022</sup>
I think scenario goals are in need for improvement. Rather than a list like now, I think it'd be cool to see a number of checkmarks to combine different goal flags.
For example, rather than just "x number people, with rating 600, at end of year y", OR "X number of people without dropping rating below 700"
Have all the different subgoals be sepperately selectable:

Number of people:  0-60000
Park Value: 0-999999999
Due Date: none, 0-999
Minimal Park Rating: 0-999 
Park Rating must be maintained: Yes, No
Monthly Ride Ticket Sales: 0-1000000
Monthly Shop Income: 0-1000000
Number of coasters: 0-255
Minimal Length of Coasters: 0-10000
Minimal Excitement of Coasters: 0-10
Loan must be repayed: Yes, No

Basically have it be possible for some crazy difficult scenario where you gotta have like 4000 guests at the park at the end of year 4, never having the park rating drop below 900, having 10 coasters of at least 9 excitement, with the loan repayed, and a shop income of 20000 or more in one month. Stuff like that. 

Of course, simply adding more subgoals than what makes up the current selection would be great too, think of things like

Build x number of waterrides, with or without a certain excitement
Make x money from photo section sales
Receive x number of positive awards
Fail scenario upon receiving a negative award
Fail scenario upon going into the red (negative money)

Also perhaps it would be nice to have early-scenario completion be selectable as intended or not with an additional such flag. Some scenarios get harder as the time goes by, and thus get easier with early scenario completion on. It could be worded as "Achieve goal before the end of year 5", vs "Achieve the goal AT the end of year 5". 
</div
[Open RCT2 Modular Objective System v1 Design Document.pdf](https://github.com/OpenRCT2/OpenRCT2/files/8366093/Open.RCT2.Modular.Objective.System.v1.Design.Document.pdf)
>

**Comment by 733737** [comment]
this is not a bug

**Comment by MaxMallon** [comment]
I know this is not a bug, I didn't mark it as a bug. But shouldn't you open an 'issue' when you're making a new feature too?

**Comment by Gymnasiast** [comment]
> I know this is not a bug, I didn't mark it as a bug. But shouldn't you open an 'issue' when you're making a new feature too?

No. That’s what you did in the 2000s when you had no such thing as a pull request. Back then, you opened an issue with a patch attached.
