### ISSUE TITLE
Defender Smart Screen in windows now blocks installer

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#16894]
### Operating System

Windows 11 Beta Insider

### OpenRCT2 build

660b03f

### Describe the issue

this build (660b03f) now microsoft defender smart screen blocks it from running

### Steps to reproduce

1. download this build 
2. have smart screen enabled
3. says app is unsafe

**Comment by Legotown55** [comment]
Somewon contactet microsoft

**Comment by Gymnasiast** [comment]
The best thing you can do in this case, is explicitly mark the executable as safe and hope that MS gets the message if enough people do so. Unfortunately, what Defender decides to block is outside our control.

**Comment by Broxzier** [comment]
One way to get trusted by Windows' smart screen is signing our executables using a EV Code Signing Certificate, but those don't come cheap.
