### ISSUE TITLE
Multiple users reporting sprite, object, and saved game corruption

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#16892]
### Operating System

Windows 11 Insider

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (2b371db on develop) provided by GitHub

### Describe the issue

Major issue with sprite corruption reports widespread amongst multiple players with new update

### Steps to reproduce

1. update to OpenRCT2, v0.3.5.1 (2b371db on develop) provided by GitHub
2. load saved game
3. sprite corruption and issues loading save games due to object corruption

**Comment by Gymnasiast** [comment]
Caused by https://github.com/OpenRCT2/OpenRCT2/pull/16882.

Reverted in https://github.com/OpenRCT2/OpenRCT2/commit/bd7ac0bace468ba46457452a7a7239d49ddfcef1.
