### ISSUE TITLE
Coaster Vehicles that were grouped in Vanilla RCT2 are not unlocked correctly except for the first entry when starting a new game

### ISSUE THREAD

**Issue by blackhand1001** [OpenRCT2/OpenRCT2#16926]
### Operating System

Windows 10 64 bit

### OpenRCT2 build

v0.3.5.1-5c4675a

### Describe the issue

Since the rides were grouped by track type across the board the vanilla track types that already had grouped trains (Wooden Coaster, Suspended Swinging etc) only load a single of the traintypes by default. I believe the original scenario files only stored the first train type. If you look at the invention order after you load the scenario these additional trains all seem to be put at the end of the list.  You can test this by starting a new game on Gravity gardens. The wooden coaster only has the normal 4 bench trains unlocked despite the fact that the ride placed on the map uses articulated trains. If you load this same scenario in vanilla rct2 the articulated trains are available as expected. 

If you look at my screenshot you can see all the vanilla grouped track types at the end of the invention list 

### Steps to reproduce

1. Open Scenario Gravity Gardens
2. Open the invention list and looked at the bottom of the list
3. You will see all the vanilla grouped vehicles at the end of the invention list.
4. The Wooden Coaster preplaced on the map uses articulated trains but if you go into the vehicle settings and try to select a vehicle type only the 4 bench trains are available. 

### Attachments

![grouped tracks](https://user-images.githubusercontent.com/5246342/161634607-683f14a8-80a3-4fa5-bc61-80f2cbbdf43d.png)

**Comment by blackhand1001** [comment]
There's code that was supposed to handle this issue but it no longer works. Probably because it now populates those missing vehicle types into the invention list at the end. I am trying to locate where it is doing this. 

`           // RCT2 made non-separated vehicles available at once, by removing all but one from research.
            // To ensure old files keep working, look for ride entries not in research, and make them available as well.
            for (int32_t i = 0; i < MAX_RIDE_OBJECTS; i++)
            {
                if (!seenRideEntry[i])
                {
                    rct_ride_entry* rideEntry2 = get_ride_entry(i);
                    if (rideEntry2 != nullptr)
                    {
                        for (uint8_t j = 0; j < RCT2::ObjectLimits::MaxRideTypesPerRideEntry; j++)
                        {
                            if (rideEntry2->ride_type[j] == base_ride_type)
                            {
                                ride_entry_set_invented(i);
                                break;
                            }
                        }
                    }
                }
            }`

**Comment by Fred-1044276** [comment]
![Extraterastrial Park 2022-04-04 16-22-01](https://user-images.githubusercontent.com/61885939/161648237-dbefbba8-b407-480f-934c-6914a5d0dcbe.png)
It seems custom scenarios made in RCT2 vanilla are affected as well. Extraterrestrial Park from the VJ Scenario Pack has this issue.
Can you test if this bug also affects RCT1 scenarios?

**Comment by blackhand1001** [comment]
It doesn't happen when starting a game from an SC4 (RCT1) file. However if you open the ones from Rollercoaster Tycoon Classic (.sea file) it happens on those which makes sense since those are based on sc6 not sc4.

**Comment by blackhand1001** [comment]
@Gymnasiast @duncanspumpkin @IntelOrca Mind taking a look at this?

**Comment by blackhand1001** [comment]
This is still broken. It affects the wooden coaster, suspended coaster, mini coaster and anything else that unlocked multiple train types as a group in RCT2.
