### ISSUE TITLE
Rename `rct_vehicle_entry.car_visual` to `rct_vehicle_entry.PaintStyle`

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#16933]
rct_ride_entry_vehicle.car_visual is an enumeration of the paint code used to paint the vehicle. "Car visual" does not speak to this reality. I think "PaintMode" or "DrawMode" is a better representation of this value.

**Comment by duncanspumpkin** [comment]
I was thinking paint style or just style. It's the naming I'm using for openlocos equivalent.

**Comment by spacek531** [comment]
I prefer Paint Style then, because it has to do with the paint code.

**Comment by navitux** [comment]
Hi, Is this issue open ?
I'd like to resolve it

**Comment by Broxzier** [comment]
Hi @navitux, feel free to work on this.

**Comment by navitux** [comment]
I'll do, thanks

**Comment by navitux** [comment]
Hi, I had worked on this issue  but: How Can I submit the changes and/or a new branch??

**Comment by spacek531** [comment]
It looks like you do not have a fork of the repository here on Github yet. You will need to create a fork, then you can push the changes to the fork in a commit, then you can create a pull request which gets reviewed, then it can get merged.

**Comment by navitux** [comment]
> It looks like you do not have a fork of the repository here on Github yet. You will need to create a fork, then you can push the changes to the fork, then you can create a pull request which gets reviewed, then it can get merged.

alright, I'll do so, thanks

**Comment by navitux** [comment]
Hi @spacek531 I had submit a pull request

**Comment by navitux** [comment]
Hi,  Does my pull request fulfill the requirements?

**Comment by spacek531** [comment]
It looks fine to me. It will probably be a few hours before the OpenRCT2 developers take a look.

**Comment by navitux** [comment]
alright, thanks
