### ISSUE TITLE
TD4 Import [Ropey Rapids.TD4] River Rapids colour bug.

### ISSUE THREAD

**Issue by Horsti12** [OpenRCT2/OpenRCT2#1695]
When I import the Ropey Rapids.TD4 in OpenRCt2 than it has a colour bug on the boats.

![](http://i.imgur.com/NeYh92i.png)
In RCT1 they were Black/Red while there are now in OpenRCt2 Green/Red

TD4 file:
https://drive.google.com/file/d/0BzdfIT8snZiGdGJzYklFTUtGTW8/view?usp=sharing

**Comment by duncanspumpkin** [comment]
What happens in vanilla RCT2?

**Comment by Gymnasiast** [comment]
Vanilla RCT2 has the same bug.
