### ISSUE TITLE
L's are replaced with non english letters

### ISSUE THREAD

**Issue by 5percentWasTaken** [OpenRCT2/OpenRCT2#16966]
### Operating System

Android 12

### OpenRCT2 build

0.3.3

### Describe the issue

Happens in later versions as well, but with diferent cherecters

### Steps to reproduce

1. Open up a scenario 
2. Navigate to a track with an "l" in it
3. Congratulations 

### Attachments

![Screenshot_20220410-110355_OpenRCT2](https://user-images.githubusercontent.com/83603702/162626147-984071be-fd54-4050-86d0-1a205931807e.jpg)

**Comment by janisozaur** [comment]
You have not updated the game properly across builds. Make sure your g2.dat is up to date.

**Comment by ocalhoun6** [comment]
Since this problem keeps recurring for different people, I do think it would be a good idea to check the g2.dat version on startup and show a (non-fatal) error if it doesn't match the OpenRCT2 version.

It can't be *that* resource-intensive or code-intensive to check the version number of a single file that's already being loaded anyway, can it?

**Comment by spacek531** [comment]
@ocalhoun6 https://github.com/OpenRCT2/OpenRCT2/issues/16662

**Comment by janisozaur** [comment]
We discussed that in the team and plan to eventually implement such check. The idea is simple: have a hard coded value of expected sprites, compare with count in g2, report if mismatched.  I'm not sure if an issue for that already exists, feel free to search for one and for it if it didn't exist yet. Also PRs welcome.

**Comment by duncanspumpkin** [comment]
Amusingly the error message might not display correctly due to said missing sprites.

**Comment by spacek531** [comment]
It would be necessary to avoid the character 'ƶ' in the error message
