### ISSUE TITLE
Please don't use `sudo` on OS X

### ISSUE THREAD

**Issue by LinusU** [OpenRCT2/OpenRCT2#1696]
When using `brew`, `/usr/local` is owned by the current user, not by `root:wheel`. Please don't use sudo in this folder, or for that matter anywhere since I don't think it's needed.

Is there anyone that still uses MacPorts and do you need to support it? If we can drop that and stick to `brew`, we could install `mingw` via `brew` directly [using this tap](https://github.com/cosmo0920/homebrew-mingw_w64).

We could then [use a `Brewfile`](https://github.com/Homebrew/homebrew-bundle) to list all of our dependencies, so that everything required for getting started on OS X should be a `brew bundle`.

I think that this is much better than trying to download and force insert tarballs into global paths.

**Comment by kevinburke** [comment]
yep agreed... another option is to use `test -x [filename|dirname]` to check whether it's readable/writable as regular user & try that before calling sudo.

**Comment by LRFLEW** [comment]
Why does this have the OS X tag? OS X is now primarily using Xcode and avoiding the scripts with sudo in them. Even so, looking at the linux scripts (as they could be used on OS X), the code with sudo only affects wine-based builds (for the "cross_tools").

**Comment by LinusU** [comment]
I personally prefer cmake over Xcode and I don't think that there is any reason to not continue to improve that path as long as it doesn't impact anything else in a negative way.

I think it has the OS X tag since on Linux you need to be root to write to `/usr/local`, but on OS X that folder is owned by the user and you should thus not be root or you will screw up the permissions.

**Comment by LRFLEW** [comment]
@LinusU I understand still wanting to use CMake (though it's not good for making release version), and I also want to continue supporting it. The thing is, there doesn't seem to be a case where it's really being used. I will look into it, though.

**Comment by LinusU** [comment]
Thanks, I think that situation has improved since I opened this issue. Seems like it's only used for crosstools these days...
