### ISSUE TITLE
Small scenery ghosts can be deleted

### ISSUE THREAD

**Issue by oli414** [OpenRCT2/OpenRCT2#16974]
### OpenRCT2 build

OpenRCT2, v0.3.5.1 (4596105 on develop)

### Describe the issue

You can delete the small scenery ghost by right-clicking on them.

When placing any type of object, you see a white ghostly representation of the object you're placing. Normally you would not be able to destroy this, as the object is automatically removed when you move the cursor, or close the building menu.
See wall pieces, large scenery, or rides for reference.

### Steps to reproduce

1. Select a small scenery object in the scenery window
2. Hover over a tile, but don't place the object
3. Right click on the white ghost version of the object
4. The scenery object is destroyed

**Comment by scaryghosty** [comment]
hey oli. i was going to try and avoid asking any questions but ive been scouring the relevant code and i can't find anything unusual that would be causing this. has this ever been an issue before (that you know of)? and, do you have any ideas what the issue might be? i've checked all the simple things like flags being set properly and attributes being calculated correctly... i've turned up nothing

**Comment by oli414** [comment]
Hi @scaryghosty, fitting username!

Have a look at the difference between these two:

https://github.com/OpenRCT2/OpenRCT2/blob/83b911b193b1f461832a8024dea83cebe93d52ed/src/openrct2/actions/WallRemoveAction.cpp#L104

https://github.com/OpenRCT2/OpenRCT2/blob/ba8690d970946ae4ca1ad06b7d0fcd8fd49c1582/src/openrct2/actions/SmallSceneryRemoveAction.cpp#L145

**Comment by scaryghosty** [comment]
thanks for getting back to me. so i actually saw that difference in SmallSceneryRemoveAction.cpp, but i also checked against the same function for specifically large scenery (which, just a reminder for those reading, does not suffer from this issue) and the large scenery uses the exact same logic as the small scenery in the equivalent line. but, i think you might be onto something anyway. i will do some builds and get back to this thread eventually.

ps: lol, i guess my name is oddly fitting for this

**Comment by Broxzier** [comment]
I don't think the actions are wrong, but rather them being called at all. I suspect that this has something to do with the added viewport flags for hiding vegetation. When right-clicking, the game essentially renders a 1x1 pixel of the game to find what element you clicked, and this normally should skip ghost elements. For vegetation, this doesn't seem to be the case.

**Comment by scaryghosty** [comment]
> Hi @scaryghosty, fitting username!
> 
> Have a look at the difference between these two:
> 
> https://github.com/OpenRCT2/OpenRCT2/blob/83b911b193b1f461832a8024dea83cebe93d52ed/src/openrct2/actions/WallRemoveAction.cpp#L104
> 
> https://github.com/OpenRCT2/OpenRCT2/blob/ba8690d970946ae4ca1ad06b7d0fcd8fd49c1582/src/openrct2/actions/SmallSceneryRemoveAction.cpp#L145
> 
> All scenery types except for small scenery handles this properly, so try to figure out what's different about them. I suspect the line I linked might be the culprit.

so, i changed the logic on the small scenery check there; it is now `if ((isGhost && sceneryElement->IsGhost()) == false)` (note the added parentheses, which alter the logic) . it solves only half of the problem. when trying to delete the ghost, the user will now receive this message:
![1](https://user-images.githubusercontent.com/1565947/165171452-4f2733e5-c836-41a7-af20-27cd38e069b4.png)

the problem is that, the game is still classifying these ghost objects as real objects in some way, providing descriptions on hover (the proper behavior is to not have this for ghosts):
![2](https://user-images.githubusercontent.com/1565947/165171895-3bed098b-e6ea-4d3d-9f16-50b6289d716f.png)

to be frank, i figured from the beginning before even commenting here that this is an issue with how the ghost objects are being generated, or at least partially.

**Comment by oli414** [comment]
Hm interesting, yeah I think Brox's theory about this being related to the paint is correct. In which case this is not as trivial as I thought.

I did spot something interesting in `Paint.SmallScenery.cpp`
https://github.com/OpenRCT2/OpenRCT2/blob/fc2ed95641eca0ce60e0a0ae596983f120edea1c/src/openrct2/paint/tile_element/Paint.SmallScenery.cpp#L350
The interaction type is being set to none. However, [PaintSmallSceneryBody immediately resets that value](https://github.com/OpenRCT2/OpenRCT2/blob/fc2ed95641eca0ce60e0a0ae596983f120edea1c/src/openrct2/paint/tile_element/Paint.SmallScenery.cpp#L112).

Wouldn't surprise me if removing that last line fixes the issue.

**Comment by scaryghosty** [comment]
sorry for double commit... i had to remake the branch after already committing a change to it. anyway, here is the PR that addresses the issue: https://github.com/OpenRCT2/OpenRCT2/pull/17062 (there is only 1 commit associated with this PR, despite the above)
