### ISSUE TITLE
The bank is saying I can't increase my loan twice

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#16982]
### Operating System

Windows 11, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (18882d1 on develop) provided by GitHub

### Describe the issue

Well, as I try to increase the loan, but failed to do so because i reach the max, somehow, the game have twice the string "The bank prohibited to give more loan" or something like that

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Get in any park
2. Max the loan
3. Try to increase it again
4. Thing is said twice (However, I'm not sure if it is a French only bug)

### Attachments

![Double String questionmark](https://user-images.githubusercontent.com/83843734/163541382-bd4c8741-a1be-43dc-a589-7f7a067fc876.png)

**Comment by csm10495** [comment]
Yeah this appears to be a localization issue. 

French:
```
STR_1918    :Impossible d’emprunter d’avantage ! La banque refuse d’augmenter votre emprunt !
STR_2365    :La banque refuse d’augmenter votre emprunt !
```

English (GB)
```
STR_1918    :Can’t borrow any more money!
STR_2365    :The bank refuses to increase your loan!
```

I think it should be: 

French:
```
STR_1918    :Impossible d’emprunter d’avantage !
STR_2365    :La banque refuse d’augmenter votre emprunt !
```

**Comment by csm10495** [comment]
pr opened: https://github.com/OpenRCT2/Localisation/pull/2307
