### ISSUE TITLE
Unable to set patrol area for 1st staff member in park

### ISSUE THREAD

**Issue by reillywalker195** [OpenRCT2/OpenRCT2#17005]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

v0.3.5.1 (031b4db on develop) provided by GitHub

### Describe the issue

The first staff member hired in a park that does not already have staff (e.g., Amity Airfield) will not be able to have his patrol area set. His Patrol Area button will appear stuck in the pressed-in position. Clicking on the button reveals the drop-down menu the button normally has, but it is not functional.

### Steps to reproduce

1. Start a new game in a park without staff.
2. Hire three staff members of each type, starting with handymen. The Patrol Area button is stuck for Handyman 1 but none of the others.
3. Fire Handyman 1.
4. Hire another handyman and notice the same Patrol Area button issue as with the original Handyman 1.
5. Fire and rehire all staff, starting with mechanics. Mechanic 1 has the same Patrol Area button issue as the first two staff Handyman 1. The current Handyman 1 does _not_ have this issue.
6. Fire Mechanic 1 and hire a fourth security guard. Security Guard 4 has the same Patrol Area button issue as Mechanic 1 and the first two staff named Handyman 1.

**Comment by James103** [comment]
Do you get the same issue if you start a new game in a park with staff, then fire all staff and hire some more?
To reproduce:
1. Start a new game in a park with staff.
2. Fire all staff.
3. Follow steps 1-6 in the original post and take note whether the bug occurs there.

**Comment by csunday95** [comment]
definitely able to reproduce this in scenarios with zero starting guests (e.g. Trinity Islands) on latest develop code. @James103 did you still want to look into this? otherwise I can take a look

**Comment by scaryghosty** [comment]
interestingly, if you load up a scenario with no guests or staff, like Amity Airfields, and wait for a guest to appear, this bug is no longer triggered... makes me wonder if loading up a scenario with guest(s) and no staff (Evergreen Gardens) and waiting for all guests to leave, triggers this.
