### ISSUE TITLE
Loading SV6 saves with money disabled starts with it enabled

### ISSUE THREAD

**Issue by CorySanin** [OpenRCT2/OpenRCT2#17009]
### Operating System

Linux, Manjaro

### OpenRCT2 build

OpenRCT2, v0.3.5.1 (2653aOc97 on develop, DEBUG)

### Describe the issue

Loading a SV6 save that has money disabled will re-enable money. I haven't tested with the new .park format.

### Steps to reproduce

1. `openrct2 https://gitlab.com/sanin.dev/ffa-tycoon/-/raw/master/parks/Arid%20Heights_free_old.sv6`
2. Notice money is enabled.

**Comment by James103** [comment]
Can reproduce in c8d00a4, but not in 4835481.
Caused by #16958.

**Comment by Gymnasiast** [comment]
Yeah, I suspected it was that PR. It doesn’t properly check for scenario status.
