### ISSUE TITLE
"File version" and "Product version" are both incorrect for OpenRCT2 executable

### ISSUE THREAD

**Issue by James103** [OpenRCT2/OpenRCT2#17019]
### Operating System

Windows

### OpenRCT2 build

Since dd0649dfed9a67e0c2ab330741042ee71ecfc212

### Describe the issue

In a screenshot posted in #17018, it is shown that the File Version is `0.0.0.0` and the Product Version is `0.0.0.0-00000000`.
These appear to be dummy placeholders, to be replaced with the actual version numbers at release time (though the developers haven't gotten around to keeping that up).

This appears to be hardcoded since June 2019, as shown below:
https://github.com/OpenRCT2/OpenRCT2/blob/adfd1b797cfef942d23af1b0c2f73adbfc92972a/resources/version.h#L1-L2

### Steps to reproduce

1. Navigate to the directory where your OpenRCT2 installation is at.
2. Inspect the properties for `openrct2.exe`.
3. Notice that File Version is `0.0.0.0` and Product Version is `0.0.0.0-00000000`.

**Comment by Broxzier** [comment]
`scripts/build` seems to have some logic in place already.

https://github.com/OpenRCT2/OpenRCT2/blob/93d13552a968f6945c829e3ee4a744aafc6896e1/scripts/build#L14-L23

https://github.com/OpenRCT2/OpenRCT2/releases/tag/v0.2.3 seems to be the first release that had this data properly embedded. https://github.com/OpenRCT2/OpenRCT2/releases/tag/v0.2.5 is the first to have the placeholders embedded instead. We likely moved to GitHub Actions between v0.2.4 and v0.2.5.

**Comment by Broxzier** [comment]
Upon some further inspection, it looks like there is an error when `git describe` gets used. In the logs this can be seen: `fatal: No names found, cannot describe anything.`

**Comment by James103** [comment]
Fixed by #17019.

**Comment by Broxzier** [comment]
This issue is once again present in the [v0.4.1 release](https://github.com/OpenRCT2/OpenRCT2/releases/v0.4.1).

**Comment by James103** [comment]
> This issue is once again present in the [v0.4.1 release](https://github.com/OpenRCT2/OpenRCT2/releases/v0.4.1).

Not on the latest develop version ce95b58d5e112832809337fa5d7b4a8d816be006 though.
(the exact version tested was `OpenRCT2-0.4.1-develop-ce95b58-windows-x64`)
