### ISSUE TITLE
rckc not available as mini coaster

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#17026]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2 3.5.1 develop 5ecb7a6c6ab71d21f9251a5b4665414944d87bf4

### Describe the issue

The OpenRCT2-modified rct2.ride.rckc ride does not appear in the Mini Roller Coaster category. The expected behavior is rct2.ride.rckc is offered as both Classic and Mini Roller Coaster types.

### Steps to reproduce

1. Open Object Selection window
2. Mini Roller Coaster rocket cars not present

### Attachments

![image](https://user-images.githubusercontent.com/3454156/164349473-430e66d1-b0e1-4cfc-b3a8-0e3d3b0c97d4.png)

**Comment by TheClaudeQC** [comment]
isn't the rocket being the classic mini-steal coaster and not the mini-coaster

**Comment by spacek531** [comment]
That's a change OpenRCT2 made, it should not remove the original entry though, AFAIK

**Comment by TheClaudeQC** [comment]
i think why they put the classic instread is that not a single other train exist on that track, and yet, they wanted to keep it for the mini-coaster of rct2 too, so get the classic and get both the RCT1 and RCT2 rockets, which explain why youn can add up to 3 vehicules per train on the mini-coaster

**Comment by Gymnasiast** [comment]
No longer happens now that we reverted that hack.
