### ISSUE TITLE
Remove `Pad_62` from `rct_ride_entry_vehicle`

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#17041]
Pad_62 in rct_ride_entry_vehicle doesn't seem to serve a purpose; the struct doesn't have an assertion guarding its size. Is there any reason to keep it?

**Comment by duncanspumpkin** [comment]
No reason, almost all the padding should be removed throughout the code base apart from like tile elements.

**Comment by Gymnasiast** [comment]
Fixed in 673ec0fa1025a0f1770fbca393fad19facb3571c.
