### ISSUE TITLE
Original Bug with Enterance in Sherwood Forest

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#1705]
The banner is a straight edged banner, not a "Fabric" banner, but the banner displays as if it is a "Fabric" banner - Bends down in the center, when it should move directly across instead.

**Comment by Gymnasiast** [comment]
Seems to be a bug in the .DAT file.
Problem is in every park with a Dark Age entrance.

**Comment by PFCKrutonium** [comment]
Fair enough, so I guess a "Change at a much later date."

**Comment by Gymnasiast** [comment]
Yes, namely when we switch to our own format and can put corrections in the import code.

**Comment by Horsti12** [comment]
This should be labeled then as a data file bug.
