### ISSUE TITLE
Invisible button for vegetation does not work

### ISSUE THREAD

**Issue by marcinkunert** [OpenRCT2/OpenRCT2#17050]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.3.5.1-906-gdaeaa98 (daeaa98 on develop) provided by GitHub

### Describe the issue

See-through works as expected, but invisible does not work at all.

https://user-images.githubusercontent.com/2963232/165075225-f527056d-bd9e-4bd7-a262-5e12254d68e5.mp4

Related to #16797

### Steps to reproduce

1. Start game
2. Go to transparency options
3. Press invisible button for vegetation as shown in video

**Comment by James103** [comment]
Have you tried pressing both the see-through AND invisible buttons at the same time?
(The button with the sprite describing what to hide is the the 'see-through' button, while the eye-glyph immediately below it is the 'invisible' toggle)

**Comment by Broxzier** [comment]
This is a design choice/oversight that I first mentioned in the implementation PR too ([4th point](https://github.com/OpenRCT2/OpenRCT2/pull/16797#pullrequestreview-910876203)). Pressing the eye button should enable the transparency flag when it's not enabled already. Alternatively, the eye button should be disabled when the button above it is not pressed.
