### ISSUE TITLE
NSF: Objective: Build 10 coasters (without length requirement) doesn't trigger.

### ISSUE THREAD

**Issue by Ryder17z** [OpenRCT2/OpenRCT2#17063]
### Operating System

Manjaro Linux 21.2.6

### OpenRCT2 build

OpenRCT2, v0.3.5.1

### Describe the issue

Savegame that should have triggered: [Mini Park - goal not triggering.park.zip](https://github.com/OpenRCT2/OpenRCT2/files/8559404/Mini.Park.-.goal.not.triggering.park.zip)
Scenario: [Mini Park.park.zip](https://github.com/OpenRCT2/OpenRCT2/files/8559409/Mini.Park.park.zip)

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Make or load a scenario with the goal "Build 10 Coasters" (without length requirement)
2. Start scenario, make some changes, save the current park
3. Convert saved park to scenario
4. Play scenario and the goal doesn't trigger.

**Comment by rctdude2** [comment]
Open Bobsled Coaster 1.
