### ISSUE TITLE
Corrupt ride window when trains have more than 144 cars

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#17073]
This is likely the source of many crash reports that have to do with the ride window's events. When there are more than 144 cars, `WindowRideVehicleScrollpaint` writes out of bounds, overwriting other static fields (most likely the others in `Ride.cpp` though).

The static array:
https://github.com/OpenRCT2/OpenRCT2/blob/85baa6f7ca55bb5745dec0514b9854234f51b161/src/openrct2-ui/windows/Ride.cpp#L2906

Used in this loop, which may loop more than 144 times for cheated trains:
https://github.com/OpenRCT2/OpenRCT2/blob/85baa6f7ca55bb5745dec0514b9854234f51b161/src/openrct2-ui/windows/Ride.cpp#L2932-L2934

Writing out of bounds here:
https://github.com/OpenRCT2/OpenRCT2/blob/85baa6f7ca55bb5745dec0514b9854234f51b161/src/openrct2-ui/windows/Ride.cpp#L2971-L2974

Making sure the array is longer than the maximum number of vehicles may fix this, though since trains can have invisible cars, I'm not entirely sure the actual number can still be higher than 255.

**Comment by Gymnasiast** [comment]
Do we have any idea where the 144 comes from?

**Comment by Broxzier** [comment]
It was added 8 years ago 8355bf6a616d781088c2fc21caf7f0a4eac6111b, likely taken from the original game. I can't think of any vehicles from the original games that support that many cars per train. Chris Sawyer may simply have picked this size to be sure it would be enough.

**Comment by Gymnasiast** [comment]
> I can't think of any vehicles from the original games that support that many cars per train

The number of cars per train seems irrelevant here, it loops over the trains, not the individual cars per train.

**Comment by Broxzier** [comment]
Exactly the opposite, the number of trains is irrelevant, the number of cars is. It loops over the cars for each vehicle to draw the full train in the scroll view widget. At the beginning of the vehicle loop, it stores a pointer to this list in `nextSpriteToDraw`, then in the loop inside the vehicle loop, it uses the value and increments the pointer with each car.

**Comment by Gymnasiast** [comment]
Then why does it loop over `ride->num_vehicles`, which contains the number of _trains_?

**Comment by Broxzier** [comment]
Because it draws the cars for every train, and reuses the array for each train.

> At the beginning of the vehicle loop, it stores a pointer to this list in nextSpriteToDraw, then **in the loop inside the vehicle loop**, it uses the value and increments the pointer with each car.

https://github.com/OpenRCT2/OpenRCT2/blob/85baa6f7ca55bb5745dec0514b9854234f51b161/src/openrct2-ui/windows/Ride.cpp#L2939

FWIW I've already got a PR ready that fixes the crashes: https://github.com/OpenRCT2/OpenRCT2/pull/17074
