### ISSUE TITLE
Default price of park maps is too high

### ISSUE THREAD

**Issue by sjoerddebruin** [OpenRCT2/OpenRCT2#1709]
Somehow the default price of park maps changed to 2.50, a amount that guests will complain about.

**Comment by daihakken** [comment]
The price in vanilla game is 0.6, i think it got messed up with the price of umbrella, which is exactly 2.5.

**Comment by duncanspumpkin** [comment]
Probably a bug in https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/ride/ride.c#L4961-L5001
