### ISSUE TITLE
Changing Map Size does not invalidate park size

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#17104]
### Operating System

Win10

### OpenRCT2 build

5659d43

### Describe the issue

Whilst reviewing #16934 I noticed this issue. When you change the map size using the map window the park size in the park window does not get invalidated and will show the incorrect size until the update event every 1000 ticks.

This is super easy to fix just add a `park_calculate_size();` to `GameActions::Result ChangeMapSizeAction::Execute() const`

### Steps to reproduce

1. Open park window on the park statistics tab
2. Open map window and enable sandbox mode.
3. Decrease/Increase the map size.
4. Notice that the park window is not updating.

**Comment by hobyr** [comment]
Hello, I'd like to try and fix this bug.
I reproduced the steps and confirm the existence of the bug.

Please let me know if I can work on it.

**Comment by duncanspumpkin** [comment]
Go for it.

**Comment by hobyr** [comment]
Seems to work after I added the line. How should I proceed next for review by the dev team?

**Comment by duncanspumpkin** [comment]
You need to make a pull request with the change.
