### ISSUE TITLE
Chairlift only allows one car

### ISSUE THREAD

**Issue by renecatharsis** [OpenRCT2/OpenRCT2#17111]
### Operating System

Windows 11, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.0 (c6302a1 on master) provided by GitHub

### Describe the issue

Chairlift no. 2 in the attached save file only allows one car to be configured even though both stations should allow at least up to 18 in space. Gymnasiast on Discord was kind enough to take a look at it already and provided the workaround of removing both stations and re-building them in a specific order: https://discord.com/channels/264137540670324737/875468371884380210/970039670425661440

"Hm, you hit a bug, it seems. We’ll have to investigate.

There is a workaround: demolish both stations. Then first rebuild the station near the Launched Freefall, followed by the one near the water slide."

### Steps to reproduce

1. Open attached save file
2. Check car configuration of Chairlift no. 2

### Attachments

[evergreen_gardens_charlift.zip](https://github.com/OpenRCT2/OpenRCT2/files/8597662/evergreen_gardens_charlift.zip)

**Comment by duncanspumpkin** [comment]
This is a duplicate. Chairlifts must be built one directional if you build them backwards the calculations for station length fail. https://github.com/OpenRCT2/OpenRCT2/issues/2216
