### ISSUE TITLE
Update readme / elsewhere to show Visual Studio 2022

### ISSUE THREAD

**Issue by csunday95** [OpenRCT2/OpenRCT2#17112]
### Operating System

Windows 

### OpenRCT2 build

latest develop

### Describe the issue

The current readme instructions for building on windows tell the reader to use VS2019, but 2022 is the latest community edition. Most developers appear to use VS2022 already, so the guides should be updated to prevent confusion.

### Area(s) with issue?

Building the game

### Steps to reproduce

read the readme

**Comment by janisozaur** [comment]
Can you submit a PR to fix that? It would also be great if we had a check for VS version, as we had reports 2019 no longer compiles the project.

**Comment by IntelOrca** [comment]
@janisozaur I think it was because the VS 2019 was not up to date.

**Comment by csunday95** [comment]
at least for me I was able to get VS2019 and 2022 to both compile the project with full cleans in between
