### ISSUE TITLE
Able to sell ghosts of scenery for money in multiplayer

### ISSUE THREAD

**Issue by Notloc** [OpenRCT2/OpenRCT2#17125]
### Operating System

Windows 10, 64bit

### OpenRCT2 build

OpenRCT2, v0.4.0

### Describe the issue

By opening the scenery placement tool and hovering a ghost of a piece of scenery on a tile, I am able to sell the ghost and receive money.

### Steps to reproduce

1. Host Server through game
2. Open the scenery placement tool and prepare to place an object
3. Right click the ghost to sell it

**Comment by Lastorder-DC** [comment]
Possible duplicate of  #17062

**Comment by Notloc** [comment]
Yea its a dupe of #16974 
I tried searching before creating, but my keywords always included 'money' or 'sell', so I missed it.
