### ISSUE TITLE
CTD when sequence directory is empty

### ISSUE THREAD

**Issue by csunday95** [OpenRCT2/OpenRCT2#17133]
### Operating System

Windows 10

### OpenRCT2 build

latest develop

### Describe the issue

If the sequence directory is empty, openrct2 will crash on windows builds due to a divide by zero. This occurs inside TitleScreen.cpp when attempting to randomly select a title sequence. This shouldn't really affect anything under normal conditions, but might as well add a check so a more graceful exit occurs. 

### Steps to reproduce

1. Clear the `sequence` directory that openrct2 uses to load title sequences. While developing on windows this is <project dir>/bin/data/sequence
2. attempt to run openrct2.exe

**Comment by James103** [comment]
On my system, if no title sequences are available, I just get a black screen that does not redraw. Tested on 0.4.0 release and develop version 90d3914.
