### ISSUE TITLE
Backup autosave before overwriting

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#1713]
It seems that someone's game crashed while performing the autosave. Because it overwrites the last autosave file, it meant that the autosave file became corrupt.
https://www.reddit.com/r/openrct2/comments/3f7zcw/cant_load_autosave_help/

Therefore the autosave file should be backed up first before it is overwritten with the new autosave, just in case it fails.

**Comment by PFCKrutonium** [comment]
So autosave.sv6.bak then
