### ISSUE TITLE
Selling unplaced scenery objects

### ISSUE THREAD

**Issue by ys3d** [OpenRCT2/OpenRCT2#17160]
### Operating System

Windows 10, 64 Bit

### OpenRCT2 build

OpenRCT2, v0.4.0 (c6302a1 on master) provided by GitHub

### Describe the issue

It is possible to sell unplaced scenery objects by right-clicking the preview-sprite. As far as we can see, this only happens with one tile large objects, but we don't know for sure yet.

### Steps to reproduce

1. Select a scenery object
2. Right-click on the gray preview-sprite
3. The game will sell the "object" an give you the money

### Attachments

https://user-images.githubusercontent.com/50729918/167106622-4d43bd7b-e3ab-4cde-80c2-1f0fef5d58ff.mp4

**Comment by Broxzier** [comment]
Thanks for the report. This has already been fixed on develop.
