### ISSUE TITLE
Constantly asking for document folder access after updating

### ISSUE THREAD

**Issue by itsnandy** [OpenRCT2/OpenRCT2#17162]
### Operating System

macOS 12.3.1

### OpenRCT2 build

0.4.0

### Describe the issue

Was on version 0.3.5.1 I believe and everything seemed to be working fine. Saw there was an update today for 0.4.0 so I downloaded and replaced the app with the new version. Now it's constantly asking me to get access to the documents folder. Doesn't matter if I say yes or even give it full disk access. Keeps prompting for access and can't get game to load. 

### Steps to reproduce

Unsure if this is a new bug in v0.4.0 but just trying to boot up the game and issue happens instantly.

**Comment by janisozaur** [comment]
Can you explain what you mean? Is it asking you to provide RCT2 assets path? Does it update the game_path in config.ini? What happens when you decline the request? What do you mean by 'constantly' - is it the only thing it does? Does that happen with older version as well?

**Comment by itsnandy** [comment]
I've included a screenshot of the prompt. Declining the request doesn't do anything, it just continues to prompt access. Constantly as in if I load the app it would prompt and no matter which option I choose it would prompt again. I tried reverting back a version and didn't help.
<img width="372" alt="Screen Shot 2022-05-08 at 12 10 51 PM" src="https://user-images.githubusercontent.com/50352448/167305070-35bbda0d-4370-4b13-9f4c-20d4a0b82370.png">

**Comment by IntelOrca** [comment]
@itsnandy have you recently updated your OS?

**Comment by itsnandy** [comment]
@IntelOrca Not recently, currently on 12.3.1

**Comment by James103** [comment]
Have you tried running the following command in a terminal?

`codesign -s - --deep /Applications/OpenRCT2.app` (replace the path with the actual path to the app bundle containing your OpenRCT2 installation)

Source of command: https://github.com/qbittorrent/qBittorrent/issues/16728

**Comment by itsnandy** [comment]
Thank you! @James103
