### ISSUE TITLE
Miniature Railroad trains are getting stuck

### ISSUE THREAD

**Issue by sjoerddebruin** [OpenRCT2/OpenRCT2#1717]
After some time, the trains of the Miniature Railroad are getting stuck for no reason. The attraction is not broken.

![schermafdruk 2015-08-02 16 56 31](https://cloud.githubusercontent.com/assets/5605979/9026677/a23a8a5a-3937-11e5-8a69-d0a9c0cc0687.png)

**Comment by sjoerddebruin** [comment]
It seems to happen if the ride just had a safety cut-out. The trains are still thinking the ride is broken. A save file: https://www.dropbox.com/s/6stfms8alh606tr/Frightmare%20Hills.sv6?dl=0

**Comment by sjoerddebruin** [comment]
After more testing: it happens on all tracked rides.

**Comment by daihakken** [comment]
@duncanspumpkin I think it should be the original bug, experienced few times in Dinghy Slides before started playing OpenRCT2

**Comment by duncanspumpkin** [comment]
I don't think this still happens. The save after reseting the ride I can't get to reproduce the error.

**Comment by duncanspumpkin** [comment]
Actually I can reproduce it if you use the fix ride dropdown that was added to fix the safety cut out.

**Comment by duncanspumpkin** [comment]
@sjoerddebruin im not sure if this was the issue but was the only problem the fact that fix ride didn't work with safety cut out? I've fixed it now in the pre-release so I think that was the problem so I'm closing this.
