### ISSUE TITLE
Red wooden fence marked as hidden in RCT1 scenarios

### ISSUE THREAD

**Issue by ZeeMaji** [OpenRCT2/OpenRCT2#17194]
### Operating System

Linux (OpenSUSE Tumbleweed)

### OpenRCT2 build

OpenRCT2, v0.4.0

### Describe the issue

The red wooden fence (rct1.scenery_wall.wooden_fence_red) is marked as hidden when importing RCT1 scenarios despite it not being hidden in RCT1 itself.
The object is still being enabled as enabling the sandbox mode cheat will show it in the scenery tool.

### Steps to reproduce

1. Open an RCT1 scenario with the red wooden fence (eg: Forest Frontiers)
2. Check fences scenery group
3. Red wooden fence is hidden when it should be available

### Attachments

![rct1fence](https://user-images.githubusercontent.com/42477864/167877545-d280a895-eabc-4f32-ad19-45eeda1a302d.png)
![missingfence](https://user-images.githubusercontent.com/42477864/167877563-d1c6d433-1e29-464a-bb55-c84fec3578a3.png)
![fencebox](https://user-images.githubusercontent.com/42477864/167878349-b8f8f906-21cf-47fe-a0b0-1b27125f9097.png)

**Comment by guljam** [comment]
번역 방법
텍스트 번역
원본 텍스트
meonjeo naneun i munjeleul haegyeolhaessseubnida. "rct2.scenery_group.scgfence.json"pail-ui entriesbaeyeol-an-e "rct1.scenery_wall.wooden_fence_red"leul chugahamyeondoebnida. RCT1sinaliona SV4leul lodeuhalttae red fencega fence moglog-e natanabnida. RCT2sinaliona SV6eul lodeuhalttaeneun natanaji anhseubnida.(museun wonliinji moleugessseubnida.) hajiman myeoch gaji munjega issseubnida 1. obeujegteuleul seontaegchang-eul yeol-eoseo Fences and wallshangmog-eul haejehago dasi seontaeghamyeon red fencega jadongjeog-eulo seontaegdoeeo issseubnida. red fenceneun RCT2ui gibon obeujegteuga animeulo yaggan munjelago saeng-gaghajiman, jag-eun munjeleul heoyonghandamyeon maeu gandanhan bangbeob-i doel su issseubnida. 2. 1beon-ui jag-eun munjeleul haegyeolhagi wihaeseo, EditorObjectSelection.cppeseo pung-gyeong geulub-eul seontaeghalttae peulleihaneun sinalioga RCT1 ttoneun RCT2inji pandanhaeseo red fenceleul chuga haljimalji gyeoljeonghamyeondoejiman, jag-eun obeujegteu hanaleul wihaeseo kodeuleul byeongyeonghaneun geos-eun joh-eun bangbeob-i aningeos gatseubnida. 3. jungdaehan munjelo rct2.scenery_group.scgfence.jsonpail-eun geim-eul bildeuhanhu binpoldeoe saengseongdoemeulo i pail-eul PRhal su eobs-seubnida XD gajang dansunhan haegyeolbeob-eun obeujegteu seontaegchang-eulo red fenceleulsudong-eulo seontaeghaneun geos-ilago saeng-gaghabnida. haha jom deo sillyeog-issneun peulogeulaemeoga haegyeolhalsu-issgileul balabnida
자세히
746 / 5,000
번역 결과
First I solved this problem.

In the entries array of the "rct2.scenery_group.scgfence.json" file
Just add "rct1.scenery_wall.wooden_fence_red"

When loading the RCT1 scenario or SV4, the red fence appears in the fence list.
It doesn't appear when loading RCT2 scenario or SV6. (I don't know how it works.)

but there are some problems

1. Open the object selection window, uncheck the 'Fences and walls' item, and select it again to automatically select the red fence.
The red fence is not a default object in RCT2, so I think it's a bit of a problem, but if you allow for a small problem it can be a very simple method.

2. To solve the first small problem, in EditorObjectSelection.cpp, when selecting a group of landscapes, you need to determine whether the scenario you are playing is RCT1 or RCT2 and decide whether to add a red fence or not, but changing the code for one small object is not It doesn't seem like a good way.

3. As a serious problem, the rct2.scenery_group.scgfence.json file is created in the bin folder after the game is built.
so It cannot be added to the source code. 
so I can't make a pull request

I think the simplest solution is to manually select the red fence with the object selection window. haha

I hope a more skilled programmer can solve it.

**Comment by ZeeMajora** [comment]
> It doesn't appear when loading RCT2 scenario or SV6. (I don't know how it works.)

The red wooden fence is an rct1 only scenery wall, it alongside a few other static colored wooden fences were turned into a recolorable wooden fence in rct2.
However the coloring of this recolorable fence in rct2 is not the same as the rct1 fences even when set to their closest colors so in openrct2 the red one was reintroduced.
The red wooden fence probably should not be included in the rct2 fences scenery group json and it should only be imported when loading rct1 parks.
