### ISSUE TITLE
Lowercase "L" is broken on develop

### ISSUE THREAD

**Issue by liny-odell** [OpenRCT2/OpenRCT2#17193]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.4.0 (built from 01a0f0f)

### Describe the issue

![image](https://user-images.githubusercontent.com/7400549/167819624-f2bb41d0-d102-4d7b-8228-3aa3003f4f43.png)

### Steps to reproduce

Open the program

**Comment by Gymnasiast** [comment]
Your g2.dat is mismatched. This is caused by not updating OpenRCT2 properly.

**Comment by liny-odell** [comment]
Maybe the line "Once you have ran msbuild once, further development can be done within Visual Studio by opening openrct2.sln." should be removed or changed on https://github.com/OpenRCT2/OpenRCT2/wiki/Building-OpenRCT2-on-Windows as I think this is what is causing the problem as I did not run the msbuild steps. As soon as I ran them and re-open the game it works fine.

**Comment by Broxzier** [comment]
Added to the notes that you might have to update your dependencies using the msbuild command when weird things show up.
