### ISSUE TITLE
"Boat Ride 1" appeared as "Ride 1" in news items

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#1719]
![sss](https://cloud.githubusercontent.com/assets/13048125/9036073/85033c96-3a10-11e5-8a59-ba4dc6f755d8.PNG)
Build Tested, b1074&1063 from OpenRCT2.com

**Comment by IntelOrca** [comment]
Might be because some break downs are still called from original code.

**Comment by Gymnasiast** [comment]
I think that is the cause, yes. Vanilla RCT2 only had strings for rides with switchable trains, all others had 'Ride' as their name.

**Comment by IntelOrca** [comment]
Does this only happen when the RCT1 ride selection feature is on?

**Comment by Gymnasiast** [comment]
Probably, otherwise the ride in the screenshot wouldn't use the generic name 'Boat Ride' but 'Bumper Boats' instead.

**Comment by Gymnasiast** [comment]
This bug is either already fixed or will be fixed when the responsible code is implemented.

@daihakken : Have you experienced this bug lately?

**Comment by duncanspumpkin** [comment]
This doesn't happen any more for boat rides at least.

**Comment by duncanspumpkin** [comment]
Not reproducible any more presumed fixed.
