### ISSUE TITLE
Vehicle Selection Stuck at "1 train" or Fewer Trains than that in the Stable build

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#1720]
Stable:
![blob](https://cloud.githubusercontent.com/assets/13048125/9036301/e3c9fb82-3a12-11e5-9f0b-3901105425cf.png)
Develop: [b1063 (ea130a6) &1074 (c389228)]
![blob 1](https://cloud.githubusercontent.com/assets/13048125/9036302/e3f42574-3a12-11e5-9862-70cca5f92ba0.png)

**Comment by Gymnasiast** [comment]
I had this as well at some point. If I recall correctly, it was especially not correctly updating the number of possible trains (e.g. when you add extra block sections). I would have to test it though.

**Comment by IntelOrca** [comment]
Can you provide a saved game or steps to reproduce?

**Comment by daihakken** [comment]
@IntelOrca sure, https://openrct.net/cloud/uploads/a23b00e98c08bf45d35680717fa228d6.sv6

**Comment by jensj12** [comment]
I noticed that it always calculated the maximum number of trains using the maximum train lenght instead of the chosen number of cars. It does not correctly update when changing the amount of cars per train. It does put them all on the track when going to test mode.

**Comment by Ext3h** [comment]
I could still reproduce the bug in 93484c7956324c6b4589b0929aa914a10dc9f1e7

As long as the dialog remains opened while editing the track, newly added block sections are correctly counted in the settings tab, but don't allow to add additional trains until the whole window is closed and re-opened.

If the train length was above the smallest block size, lowering it accordingly doesn't allow it either to increase the number of trans directly. The windows needs to re-opened in this case as well.

it only works as expected when increasing the train length after lowering the train count.
