### ISSUE TITLE
#16308: Missing colon in changelog

### ISSUE THREAD

**Issue by James103** [OpenRCT2/OpenRCT2#17201]
### Operating System

Windows 10

### OpenRCT2 build

07520ce0baecefac04aac21fbed5e7fc07bb3307

### Describe the issue

The changelog entry that was added in #16843 is missing a colon and has two consecutive space characters.
The current form is as follows:
https://github.com/OpenRCT2/OpenRCT2/blob/07520ce0baecefac04aac21fbed5e7fc07bb3307/distribution/changelog.txt#L92

The correct form is:
```
 - Fix: [#16308] Crash when trying to place down a ride on Android.
```
(a colon then a space, not two consecutive space characters)

Discovered while reporting #17200

### Steps to reproduce

1. Open the source code for OpenRCT2.
2. Check `distribution/changelog.txt`
3. Notice the error on line 92 of the file.

**Comment by Gymnasiast** [comment]
You can open a pull request quite easily for this sort of thing. Anyway, thanks for reporting.
