### ISSUE TITLE
#17197: Format error in changelog

### ISSUE THREAD

**Issue by James103** [OpenRCT2/OpenRCT2#17200]
### Operating System

Windows 10

### OpenRCT2 build

5ccf04b2e58463bf964e81e206a38d8cb9ad0127

### Describe the issue

The changelog entry that was added in #17197 is formatted differently compared to the other changelog entries.
More specifically,
https://github.com/OpenRCT2/OpenRCT2/blob/5ccf04b2e58463bf964e81e206a38d8cb9ad0127/distribution/changelog.txt#L20

should be
```
 - Fix: [#17197] Segfault when extracting files from the GOG installer. 
```

to fit in line with the other entries.

### Steps to reproduce

1. Open the source code for OpenRCT2.
2. Check `distribution/changelog.txt`
3. Notice the error on line 20 of the file.

**Comment by Broxzier** [comment]
Thanks for the report, this was my bad. Fixed on develop now.
