### ISSUE TITLE
Some minor issues with cursors

### ISSUE THREAD

**Issue by guljam** [OpenRCT2/OpenRCT2#17221]
### Operating System

windows 11

### OpenRCT2 build

Openrct2, v0.4.0-122-g4adca3b (develop)

### Describe the issue

It's not particularly disruptive to gameplay.
This difference provides a heterogeneous feeling compared to the vanilla game.

### Steps to reproduce

1. Enable cursor hints and compare with vanilla RCT2.
2. Activate the object ghost and compare it to vanilla RCT2.
3. Activate the terrain tool and compare it to vanilla RCT2.

### Attachments

![van1](https://user-images.githubusercontent.com/15816034/168559354-0cbbcb36-b081-4faa-a4e1-d43b0f5ad6c1.gif)
This is vanilla RCT2.
The hint disappears when scroll with right-click.

![open1](https://user-images.githubusercontent.com/15816034/168560222-6db4d48a-b87c-454e-8397-6f19e38164ba.gif)
In Openrct2, the cursor disappears, but the hint doesn't disappear.

![van2](https://user-images.githubusercontent.com/15816034/168560735-d20d8acf-8f7e-4e21-a6c1-e2ac449b0d5c.gif)
In vanilla RCT2, object ghosts no longer follow the cursor when scrolling with right-click.

![open2](https://user-images.githubusercontent.com/15816034/168560968-5eec98f2-d1ab-4cbb-a7f5-f4b79fc10fd0.gif)
In openrct2, the cursor follows the ghost.

![vancursor](https://user-images.githubusercontent.com/15816034/168561068-46297ba7-81b5-47a5-b760-fe32046252d6.gif)
In vanilla RCT2, the cursor position is exactly the same when editing terrain(This is the same for water tools).

![opencursor](https://user-images.githubusercontent.com/15816034/168561774-d64203b5-34aa-45b4-bfc6-0585a743f276.gif)
In Openrct2, the cursor is slightly off to the right.

**Comment by karst** [comment]
Can you edit version to the exact commit you were using?  You can find this on the lower left corner of the title screen.

**Comment by guljam** [comment]
@karst ok

**Comment by telk5093** [comment]
Quite nice observation!

**Comment by toimine** [comment]
I actually like those behaviours, it could be a setting somewhere to switch between the two

**Comment by guljam** [comment]
@toimine I agree with you that it can checks location in real time, but
I want it to feel like vanilla RCT2
I'm editing the code, hope this is accepted :P
