### ISSUE TITLE
Rename G1_FLAG_BMP to G1_FLAG_HAS_TRANSPARENCY

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#17229]
`G1_FLAG_BMP` has the wrong name its the inverse of its name it is used to indicate that the sprite has transparency and will require blending with the background to produce the end result. The vast majority of images have this flag set.

**Comment by IntelOrca** [comment]
Same change needs applying to https://github.com/intelorca/libsawyer

**Comment by Rinzii** [comment]
I can take this issue just assign me please ^^

**Comment by tupaschoal** [comment]
We don't do issue assignment, but feel free to do it.
