### ISSUE TITLE
Path Finding problem when peeps leaving the Haunted House.

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#1723]
**Existed** since the stable build. 
Stable: 
![Stable](https://farm1.staticflickr.com/520/20086349608_7877fc6319_o.png)
Vanilla:
![Vanilla](https://farm1.staticflickr.com/406/20086302820_a3cd841e20_o.png)

**Comment by IntelOrca** [comment]
Can you provide a saved game?

**Comment by daihakken** [comment]
yes, sure:
https://openrct.net/cloud/uploads/4e489eb4d2fd467748b053d8f3f8a66a.SV6

**Comment by sjoerddebruin** [comment]
Yup, can confirm this.

**Comment by IntelOrca** [comment]
Might have to wait for @duncanspumpkin - he knows more about how all the peep ride sub states work.

**Comment by daihakken** [comment]
@IntelOrca It's not a major bug and only affect aesthetically, it can wait ;)
