### ISSUE TITLE
Different floor types when selected (vanilla rct2 floors)

### ISSUE THREAD

**Issue by Bermdebom** [OpenRCT2/OpenRCT2#17268]
### Operating System

Windows 11, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.0 (c6302a1 on master) provided by GitHub

### Describe the issue

When selecting floor types, different textures apear than selected. For instance when I select sand, rock or checkerboard will apear to be applied to the park. I now use void in the menu when I want to use sand. But sadly not all the floortypes can be selected this way, I cant place sand (brown) and sand (grey) in the parks now. I havent selected a non-rct2 vanilla floor but it appers in the menu's. 

### Area(s) with issue?

New Save Format (NSF), Building the game

### Steps to reproduce

1. 
2. 
3. 
![Schermopname (62)](https://user-images.githubusercontent.com/106036450/169716242-f0c910eb-112f-4d4e-8069-d505a84af9db.png)

**Comment by duncanspumpkin** [comment]
If you select rct1 terrain styles without rct1 linked fallback sprites will be used.

**Comment by Bermdebom** [comment]
Thanks for the explanation Duncan! Can I fix this problem by editing the park with the scenario editor by deselecting the rct1 floors?

**Comment by Broxzier** [comment]
Yes, that'd work. Alternatively you can enable the sandbox mode cheat, and edit the park file directly (no need for scenario editor).

**Comment by Bermdebom** [comment]
> Yes, that'd work. Alternatively you can enable the sandbox mode cheat, and edit the park file directly (no need for scenario editor).

thankyou I will try! (and make some awesome terraforming!)
