### ISSUE TITLE
Spiral slide sprite not loaded correctly

### ISSUE THREAD

**Issue by Z-Master** [OpenRCT2/OpenRCT2#17260]
Hello,

Here are my version informations :
OpenRCT2, v0.4.0 (, DEBUG)

I'm playing in French on Linux Mint 20.3, I use the latest dev version on the PPA.

I've noticed this issue with the spiral slide, it seems the sprite isn't loaded correctly, either it's invisible like in Forest Frontier, or it loads the wrong data, like in the other screenshot (I believe it's a RCT2 scenario, maybe that explains the difference?)

It's a graphical glitch, the slide seems to work fine.

![image](https://user-images.githubusercontent.com/7031047/169665749-e1ecaf5d-7278-4cc3-8b78-c938f8675bd2.png)
![image](https://user-images.githubusercontent.com/7031047/169665964-1e016773-9f5a-44bf-aa3d-a4a719d469cb.png)

Thanks!

**Comment by Gymnasiast** [comment]
Darn, I forgot the objects for the PPA :/

**Comment by Z-Master** [comment]
I just updated and it works now!
