### ISSUE TITLE
RollerCoaster Tycoon 1 Title screen music not playing

### ISSUE THREAD

**Issue by karst** [OpenRCT2/OpenRCT2#17276]
### Operating System

Windows 10, 64 Bit

### OpenRCT2 build

OpenRCT2, v0.4.0-154-ge90ebb3 (e90ebb3 on develop) provided by GitHub

### Describe the issue

Since the merge of the new audio dependencies the RCT1 title menu music doesn't play anymore.

### Steps to reproduce

1. Download & Install ge90ebb3
2. Make sure RCT1 is installed and its path is selected.
3. Go to options
4. Go to music & sound
5. Set title screen music to RollerCoaster Tycoon 1
6. No music is playing.

**Comment by rctdude2** [comment]
Confirmed with **_Steam version_** of RCT1.

n.b. css17.dat is under `RCTdeluxe_install/Data` in the Steam version. The PR removed the check for finding it under there, but didn't seem to add it back. The only checks I could find left are for CSG1I.DAT and mp.dat:

https://github.com/OpenRCT2/OpenRCT2/blob/e90ebb38cee37ae048dbb228f4f578b2bf1f653c/src/openrct2/config/Config.cpp#L966-L975

https://github.com/OpenRCT2/OpenRCT2/blob/e90ebb38cee37ae048dbb228f4f578b2bf1f653c/src/openrct2/scenario/ScenarioRepository.cpp#L506-L524

css17.dat check was here:
https://github.com/OpenRCT2/OpenRCT2/blob/697fa7c4368347a764fd34f81e8b08fda97b01ff/src/openrct2/Context.cpp#L336-L354
