### ISSUE TITLE
Steel Wild Mouse name and description are displayed for new Alpine coaster

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#17286]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.0-166-g502f06a (502f06a on develop) provided by GitHub

### Describe the issue

The name and description of the new Alpine coaster vehicle show up as "Steel Wild Mouse".

### Steps to reproduce

1. Start Forest Frontiers
2. Open the object selection
3. Search for Alpine Coaster -> The vehicle will show up as "Steel Wild Mouse"
4. Open the ride window -> Here it shows the description of the Steel Wild Mouse too.

### Attachments

![Forest Frontiers 2022-05-26 23-51-29](https://user-images.githubusercontent.com/9705046/170586278-a60e9b49-b989-41b8-ae93-d092f57c1103.png)

**Comment by Broxzier** [comment]
Looks like this is from ALPCSTS0.DAT, so probably not the official object?

**Comment by X123M3-256** [comment]
This isn't a bug, that alpine coaster vehicle was made long before the track and is set to the steel wild mouse track. It's the same as the old RMC object that was set to use the wooden track by default, you need to use the new version (the one from the PR) if you want it to show up on the correct track.

I'm not sure if they intend on merging that vehicle or not, if they don't then I'll upload the .parkobj somewhere.

**Comment by Broxzier** [comment]
Yeah, that's what I figured. I jumped too fast to conclusions, thinking that the object PR was merged along with the coaster type.
