### ISSUE TITLE
Wide scrolling signs getting stuck

### ISSUE THREAD

**Issue by ipatix** [OpenRCT2/OpenRCT2#1729]
There seems to be an issue with scrolling signs (2 blocks wide) where one side occasionally get's stuck while the other side keeps scrolling:

![scr14](https://cloud.githubusercontent.com/assets/8502545/9072050/2b27e6ba-3af9-11e5-8091-61446a8f6def.png)

**Comment by daihakken** [comment]
tested and cannot reproduce it, may you upload the save?

**Comment by ipatix** [comment]
There we go:

It might be a little tricky to reproduce that bug. If the bug doesn't show up, just nudge the camera by a few pixels and it might occur. Eventually takes a few seconds to reproduce.

https://dl.dropboxusercontent.com/u/28573353/OpenRCT2/Saves/Sandbox.sv6

**Comment by mrtnptrs** [comment]
I can reproduce this visual bug, so the "investigate" label can be removed and replaced by "bug". @Gymnasiast

**Comment by tupaschoal** [comment]
Provided save is not accessible anymore and I can't reproduce it. Please reopen if you can!

**Comment by ipatix** [comment]
I still have the save file. Interestingly enough it now crashes the game 2dfef7f
[Sandbox.zip](https://github.com/OpenRCT2/OpenRCT2/files/5339921/Sandbox.zip)

**Comment by tupaschoal** [comment]
Thanks for providing the save though! I ran it for 3 in game years and didn't see any issue as well :)
