### ISSUE TITLE
Right-clicking certain scenery while in build mode causes sell cost of some items to be added or subtracted to money pool.

### ISSUE THREAD

**Issue by Lieutenant-Debaser** [OpenRCT2/OpenRCT2#17296]
**OS:** Debian GNU/Linux, Release 11 64-bit (amd64 x86-64 Kernel)
**Version:** OpenRCT2, Release v0.4.0 (Linux x86-64) App Image, Provided via ![Releases](https://github.com/OpenRCT2/OpenRCT2/releases)
**Commit/Build:** c6302a1

**Issue Summary:**
When in build mode for scenery with a decoration selected and ready to be built, on an empty tile one can right-click instead and have the resale value of the item added to their money pool instead (e.g. the Roman Temple will "sell" for $50, even though the player does not have one to sell). Once a specific tile has had the glitch occur on it, the cursor must be moved to another tile before this will occur again. Rapid gain of money can be accomplished by moving mouse around screen in scenery build mode and rapidly right-clicking.

**Reproducible in RCT2 Vanilla:** Unknown
**Reproducible in Multiplayer:** Unknown

**Steps to Reproduce Glitch:**
<ol>
  <li>Open the tab to build scenery and decorations and select a decoration (I've found mainly the Roman Temple and Canvas Roof are the best).</li>
  <li>Hover over the center of a tile and quickly right-click to "sell" the item. One must quick click enough so as to not activate the "right-click to pan" camera mode.</li>
  <li>The sell value of the item will appear as if it was actually sold, and the item's sell value will be added to player's money pool.</li>
</ol>

**Additional Details:**
<ul>
  <li>The only map so far that I have tried this glitch on has been on the "Dusty Dunes" scenario map from RCT: DE (taken from the Steam release).</li>
  <li>I do have cheats enabled, and am using the "Build While Paused" cheat. Glitch functions whether the game is paused or not.</li>
  <li>It seems item behavior can vary. Some items (such as roof and the temple) add their sell value to your money pool. Other items (such as gardens) subtract their sell value from the money pool. Even still, the glitch may not work with some items (including trees and shrubs).</li>
</ul>

This is the mode I was in when encountering this glitch:
![BuildMode](https://user-images.githubusercontent.com/74188205/170826107-cafe5e3d-6f13-4be6-9ce3-95c3cae81976.png)

Save File Attached:
[DynamiteDunesPossibleGlitch.zip](https://github.com/OpenRCT2/OpenRCT2/files/8791143/DynamiteDunesPossibleGlitch.zip)

_If the this issue has already been documented, please feel free to close this report. I could not find anything in the active issues pertaining to it._

**Comment by Broxzier** [comment]
Thanks for reporting this bug. It has already been fixed on develop.
