### ISSUE TITLE
missing tracks

### ISSUE THREAD

**Issue by nightNylad** [OpenRCT2/OpenRCT2#17308]
### Operating System

windows 10

### OpenRCT2 build

OpenRCT2, v0.4.0-181-g9a4492c (9a4492c on develop) provided by GitHub

### Describe the issue

well im trying to make a wooden coaster and i noticed that the stage coach cart was not there on the select screen in design a track mode i am pretty sure i linked my rct2 thrillpack to open rct2 but i changed from manual download of updates to the launcher though i think the issue was on the other one as well would you know why i can`t pick these also i don`t have a problem with the rct1 parks i linked because there still in my list of parks on openrct2 launcher

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. 
2. 
3.

**Comment by karst** [comment]
![image](https://user-images.githubusercontent.com/1516893/171260078-f7348398-620b-4cc2-a13d-29b103f3637b.png)

I can find them just fine. Do you have Wacky Worlds disabled in the Filters of the Track Designer's ride type selection by any chance?

![image](https://user-images.githubusercontent.com/1516893/171261260-89ac8520-aca1-4de0-865d-3796462b03c3.png)

**Comment by Gymnasiast** [comment]
Assuming this answer the question, as there has been no reply for a month.

**Comment by nightNylad** [comment]
Hello no this  is not the answer I have fixed it my self I would have to go look around to tell you the fix if you want but thanks for the thought  Sent from Mail for Windows From: Michael SteenbeekSent: Sunday, 3 July 2022 4:54 AMTo: OpenRCT2/OpenRCT2Cc: nightNylad; AuthorSubject: Re: [OpenRCT2/OpenRCT2] missing tracks (Issue #17308) Assuming this answer the question, as there has been no reply for a month.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by nightNylad** [comment]
No it was ticked the picture box was blank and when place would be invisable I have fixed this now so thanks anyways Sent from Mail for Windows I can find them just fine. Do you have Wacky Worlds disabled in the Filters of the Track Designer's ride type selection by any chance?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
