### ISSUE TITLE
Reversed reversible vehicles not imported properly when loading RCT1 parks.

### ISSUE THREAD

**Issue by ZeeMajora** [OpenRCT2/OpenRCT2#17310]
### Operating System

Linux (OpenSUSE Tumbleweed)

### OpenRCT2 build

OpenRCT2, v0.4.0

### Describe the issue

Reversed vehicles from the log flume, reverser coaster, heartline twister coaster, etc are not imported properly from RCT1 parks.
This is most easily testable with the valhalla log flume from black pool pleasure beach.

### Steps to reproduce

1. Open up the rct1 version of black pool pleasure beach and pause immediately
2. Go over to the valhalla log flume and unpause
3. The train coming out of the tunnel in the screenshots should be reversed, but it is not.

### Attachments

RCT1
![valhalla](https://user-images.githubusercontent.com/42477864/171327600-02df35f7-5fe7-4508-9ada-979a841f338b.png)
OpenRCT2
![DeepinScreenshot_select-area_20220601002636](https://user-images.githubusercontent.com/42477864/171327603-d80faf54-349f-4afa-933b-70f77ea7d4be.png)

**Comment by Gymnasiast** [comment]
Could you prepare an RCT1 save that contains just reversible rides, and where all rides have at least one vehicle in the reversed state?

**Comment by ZeeMajora** [comment]
Sure thing, here is an RCT1 save with (hopefully) all of the reversible rides with their trains in the reversed state.

[reverse-test.SV4.tar.gz](https://github.com/OpenRCT2/OpenRCT2/files/8812739/reverse-test.SV4.tar.gz)

**Comment by spacek531** [comment]
Does this also affect the flying coaster when it's in flying state?

**Comment by ZeeMajora** [comment]
I tested that one as well, it seems to import fine when it is in it's flying state.
