### ISSUE TITLE
Guests refuse to Queue for Reverse Freefall Coaster 1.

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#1731]
https://openrct.net/cloud/uploads/2fbb85a28ef691c4d61e6910f4d6972a.sv6

I've emptied the queue by closing the ride and the issue continued.

**Comment by daihakken** [comment]
@PFCKrutonium replace the entrance fix it.

**Comment by IntelOrca** [comment]
Right now, I am debugging why it has doesn't get ride ratings.

**Comment by daihakken** [comment]
@IntelOrca It should be #1630. Most modes rather than Continuous/Flat Rides would not show the rating.

**Comment by IntelOrca** [comment]
When the ratings are calculated, the peeps still do not queue properly. I check the ride's entrance position and it is correct - so I am not sure what is going on or how it ended up in this state.

**Comment by daihakken** [comment]
@IntelOrca try to replace the entrance, and they will queue.

**Comment by IntelOrca** [comment]
@daihakken That's all very well, but it would be good to figure out why this happened in the first place.

**Comment by mrtnptrs** [comment]
Could someone provice the save file if he still has it, so I can check if this bug still occurs?

**Comment by Broxzier** [comment]
@mrtnptrs: There's a saved game with this issue here: https://github.com/OpenRCT2/OpenRCT2/issues/2345

I haven't seen this happen in a long time.
