### ISSUE TITLE
Everything becomes blurry when changing zoom factor in OpenGL renderer

### ISSUE THREAD

**Issue by hornta** [OpenRCT2/OpenRCT2#17339]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.0 (c6302a1 on master) provided by GitHub

### Describe the issue

Using the OpenGL renderer, everything becomes blurry when changing zoom factor from 1 -> 1.25(or something above 1) -> 1.

### Steps to reproduce

- Enter OpenGL renderer
- Increase zoom factor from 1 to something else
- Decrease zoom factor back to 1
- Notice how everything becomes blurry as in my image:

Crisp image after changing zoom to 1.25
![image](https://user-images.githubusercontent.com/4553604/172069484-90b62e65-eb5b-483e-b18e-5a869700895c.png)

Blurry after reverting it back to 1:
![image](https://user-images.githubusercontent.com/4553604/172069496-f17ac031-4334-4dca-a83f-09dc0054867c.png)

**Comment by IntelOrca** [comment]
Your 1.25 zoom is not as crisp as it should be.
Do you get this when using other renderers like software?

Have you tried window mode and resizing the window to different positions. Wondering whether it is caused by an odd width or height window.

**Comment by hornta** [comment]
> Your 1.25 zoom is not as crisp as it should be.

Yea this may be true, maybe because 1.25 is not aligning correctly, but it's way worse than the latter image so something isn't reverting back correctly.

**Comment by oli414** [comment]
This appears to only happen for the OpenGL renderer.

Going from 0.75 to 1.0 still has the same issue but the effect appears to be less severe.

**Comment by duncanspumpkin** [comment]
Could you try https://github.com/OpenRCT2/OpenRCT2/pull/17598 as I've not been able reproduce the issue.
