### ISSUE TITLE
The ride will be still available to invent after "Select Rides like RCT1" enabled

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#1733]
![image](https://cloud.githubusercontent.com/assets/13048125/9085097/68377bfc-3bac-11e5-9953-b301390f92a8.png)

It is kind of waste of money, maybe disabling the vehicle type before it got invented, or disabling all vehicle type to invent after enabled the setting.

**Comment by Gymnasiast** [comment]
Which scenario is this?

**Comment by daihakken** [comment]
Leafy Lake, but this 'bug' occurs in every scenario when RCT1 ride type enabled.

**Comment by daihakken** [comment]
I think this bug can be fixed in either way: disable not invented vehicle types, or disable vehicle types in the invention list.

**Comment by Gymnasiast** [comment]
I just investigated. The problem seems to be that RCT1 selection makes all the Boat Ride vehicles available at the beginning, due to the way vanilla RCT2 handles ride types with multiple vehicles in invention (making them all available at once).

**Comment by daihakken** [comment]
Interesting, is that an original bug?

**Comment by AaronVanGeffen** [comment]
Well, RCT1-style selection wasn't in the original game, so …
