### ISSUE TITLE
Alpine coaster don't work in ride editor

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#17344]
### Operating System

Windows 11, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.0-196-ge9c749d (e9c749d on develop) provided by GitHub

### Describe the issue

Well, trains will never depart as it need guests to make the ride go

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. go to ride editor
2. select the alpine coaster whit X's vehicules
3. build it as intended
4. open it up
5. got the trains stuck at station forever

### Attachments

![Parc sans nom 2022-06-06 11-00-21](https://user-images.githubusercontent.com/83843734/172187447-43d0d41f-b122-4f19-a3a3-05e21fc8ea5a.png)
![Parc sans nom 2022-06-06 11-00-19](https://user-images.githubusercontent.com/83843734/172187464-c3e471ae-e99f-41e5-a47f-eca00f675457.png)

**Comment by duncanspumpkin** [comment]
This is expected behaviour. The cars need peeps to control them without the peeps it can't operate.

**Comment by X123M3-256** [comment]
The other tracked rides which can't work without guests (the go karts and monorail cycles) aren't shown in the track designer, presumably for this reason, so I'm not sure why the alpine coaster is - there must be a separate flag to have it hidden that I missed.

**Comment by X123M3-256** [comment]
I don't necessarily think that it would be a bad idea to change the behaviour of that flag so that the ride can operate without riders in the track designer, or make it so that a track design can be saved without having to be tested first, because I don't really see why you shouldn't be able to use those rides in the track designer just because they require guests to operate.

**Comment by X123M3-256** [comment]
> `RIDE_TYPE_FLAG_SHOW_IN_TRACK_DESIGNER` is the flag you could remove from the alpine coaster to remove it (its included by `RIDE_TYPE_FLAGS_COMMON_COASTER_NON_ALT`)

Indeed it is, and there's a few other flags that includes that weren't meant to be enabled, I'll submit a PR to fix it.
