### ISSUE TITLE
failed to load file contains invalid data, OpenRCT2 Classic

### ISSUE THREAD

**Issue by magnog0** [OpenRCT2/OpenRCT2#17341]
### Operating System

Windows 10 64bit

### OpenRCT2 build

OpenRCT2 0.0.7

### Describe the issue

when i load the game  in RCT2 i try to start a new game/scenario i get error  "failed to load files contains invalid data"

[image](img https://i.ibb.co/j8WTDx8/Untitled.png[](url))

all the .SEA files from classic folder were copied to the correct  subfolder, as well as

All of the *.pob files to ObjData
All of the *.td6 files to Tracks

please help :)

### Area(s) with issue?

The bug also exists in RCT2 (vanilla)

### Steps to reproduce

1. 
2. 
3. 

### Attachments

![Untitled](https://user-images.githubusercontent.com/106936342/172076417-e06a6386-04ec-45c3-b3fa-1423af1001e2.png)

**Comment by ZeeMajora** [comment]
To add to this, this seems to be related to checksums as i managed to replicate this by disabling the "Allow loading files with incorrect checksums" option.
![DeepinScreenshot_openrct2_20220606070905](https://user-images.githubusercontent.com/42477864/172149776-8e6abe0c-4abf-4491-88cb-ca15a375840d.png)

Enabling the option allows the .sea scenarios to load.
![DeepinScreenshot_openrct2_20220606071021](https://user-images.githubusercontent.com/42477864/172149924-a84b36e6-fa13-44aa-a12c-c4c7814b1280.png)

**Comment by Gymnasiast** [comment]
You specified the wrong version of OpenRCT2. As you can see in the screenshot (bottom left), you are running a develop build in the v0.4.0 range. 0.0.7 is an ancient version. You likely specified the launcher version. Please keep this in mind for the next time.

We will look into this error. In the meantime, please follow Majora’s advice for a workaround.

**Comment by CloudyMcDowd** [comment]
I have also run into this issue, since re-installing the game (OpenRCT2-0.4.4-windows-installer-x64). Earlier saves (prior to 6th May 23) load okay, but not after that.
I would like to try Allow loading files with incorrect checksum, but that option does not appear for me:
![image](https://github.com/OpenRCT2/OpenRCT2/assets/129379829/2bd27f91-2e47-4d86-9760-e9784be27dd4).
Help with either issue would be appreciated!
