### ISSUE TITLE
Scenario Builder: Selecting ice crashes the game

### ISSUE THREAD

**Issue by Codefreak64** [OpenRCT2/OpenRCT2#17340]
### Operating System

Windows 64 bit

### OpenRCT2 build

Open RCT2, v0.4.0(c6302a1 on master)

### Describe the issue

Trying to make an Ice theme Scenario in the Scenario creator can result in game crashing when picking the Ice ground Top

### Steps to reproduce

1. Go to scenario creator
2. Only pick ATM machine for starting out rides (not sure if it matters but it might be  a cause of it)
3. Enable advance picking and limit ground to Ice sides and Ice top (Top specifically)
4. Try to generate land with any option (trying to pick the ice top will show as blank)
5. Generating terrain with full Ice (sides and top) will result in either of these actions
A. Kalidescoping menus (major visual glitch when moving around)
B. Crashing the game (which is very bad)

### Attachments

All file that the game logged are detailed here
[RCT2 Scenario Crash.zip](https://github.com/OpenRCT2/OpenRCT2/files/8840884/RCT2.Scenario.Crash.zip)

**Comment by Broxzier** [comment]
Can you try this on develop? I think I've already fixed this one.

**Comment by Broxzier** [comment]
Fixes by https://github.com/OpenRCT2/OpenRCT2/pull/17212.

Can't test it myself right now, so would like confirmation if you're able to test it on develop.
