### ISSUE TITLE
Undefined String

### ISSUE THREAD

**Issue by Breadwinka** [OpenRCT2/OpenRCT2#1735]
Length of time shows undefined string latest build 1092.

![image](https://cloud.githubusercontent.com/assets/13487931/9094574/a40f066c-3b80-11e5-811b-20557673e087.png)

**Comment by IntelOrca** [comment]
This has already been fixed. Its a problem with English (US), but I have also corrected the fallback mechanism which is in build 1093.

**Comment by Breadwinka** [comment]
Awesome.
