### ISSUE TITLE
UI Bug 

### ISSUE THREAD

**Issue by R0YR** [OpenRCT2/OpenRCT2#17355]
### Operating System

Windows 10, 64Bit

### OpenRCT2 build

OpenRCT2, v0.4.0-203-gbde81c1 (bde81c1 on develop) provided by GitHub

### Describe the issue

UI Bug - Ingame - shows a part of the map instead of the normal UI
I've tried other saves - changes nothing

![New Project 2022-06-07 15-07-56](https://user-images.githubusercontent.com/46133094/172389543-4be40ba1-6efa-4737-a292-f9b502fdf4b9.png)

See Attachment

### Steps to reproduce

1. Load in to a savegame
2. -
3. -

### Attachments

![New Project 2022-06-07 15-07-56](https://user-images.githubusercontent.com/46133094/172388813-413bd4a0-841d-4109-9c05-345f2405fadd.png)

**Comment by Broxzier** [comment]
Thanks for the report. This should be by https://github.com/OpenRCT2/OpenRCT2/pull/17354, but all developers are currently afk. Can you verify if the build from that PR fixes it?

**Comment by R0YR** [comment]
Yeah will do

**Comment by ZHSimon** [comment]
Also encountering this issue - without the spoons to spare to build from the PR. To add a little extra detail - it seems that it's displaying the top slice of the loading screen. 
![image](https://user-images.githubusercontent.com/3298651/172394201-9db37ea0-fddf-49e3-89be-b844fbb0d125.png)

**Comment by guljam** [comment]
Same bug appeared when I updated my tooltip branch to upstream latest build.

**Comment by R0YR** [comment]
Problem solved with the newest build!
