### ISSUE TITLE
Linux Mint can't save screenshot

### ISSUE THREAD

**Issue by seankeykong** [OpenRCT2/OpenRCT2#17374]
### Operating System

Linux Mint 20.3

### OpenRCT2 build

OpenRCT2, v0.4.0 (, DEBUG)

### Describe the issue

I'm trying to save a screenshot, it says file 'Forest Frontiers...' saved to disk, but I don't see a screenshots folder anywhere.  Searching file system didn't seem to yield anything.

### Steps to reproduce

1. Run OpenRCT2
2. Begin scenario from main menu
3. Click Giant Screenshot
4. Message pops up saying 'Screenshot saved to disk as ... (file name)
5. Look for saved file, but cannot locate

**Comment by duncanspumpkin** [comment]
Please fill in the template correctly with the commit. Your other issue suggests that you are running an out of date version so please update as well.

**Comment by James103** [comment]
What do you get when you run `openrct2 --version`?

**Comment by seankeykong** [comment]
$ openrct2 --version
OpenRCT2, v0.4.0 (, DEBUG)
Linux (x86-64)
Network version: 0.4.0-1
Plugin API version: 55
Current park file version: 12
Minimum park file version: 1

**Comment by Broxzier** [comment]
In the title screen, click the red toolbox and choose "Open custom content folder". That should open the folder containing the screenshot folder.

**Comment by seankeykong** [comment]
@Broxzier oh man I feel ridiculous, it's in .config/OpenRCT2, I just wasn't showing hidden folders.  Thank you!

**Comment by ocalhoun6** [comment]
Though maybe, come to think of it, a directory within a hidden folder is maybe not the best place to have the default screenshot save location in linux?

Maybe instead create the directory ~/OpenRCT2 Screenshots/ and place it in there the first time a user creates a screenshot?

**Comment by seankeykong** [comment]
Do you mean that for me, or for the developers?

**Comment by ocalhoun6** [comment]
For the devs.
