### ISSUE TITLE
Linux Mint Toolbar glitch

### ISSUE THREAD

**Issue by seankeykong** [OpenRCT2/OpenRCT2#17373]
When starting scenario from main menu, the toolbar is clipped by the last frame of the menu screen
![ForestFrontiers](https://user-images.githubusercontent.com/29061747/173160708-7e1af9da-79ac-4086-aee2-860a23c6522b.png)
.

**Comment by duncanspumpkin** [comment]
That issue has already been fixed it was a bug in a singular commit for a few hours.
