### ISSUE TITLE
Linux Mint no audio

### ISSUE THREAD

**Issue by seankeykong** [OpenRCT2/OpenRCT2#17375]
### Operating System

Linux Mint 20.3

### OpenRCT2 build

OpenRCT2, v0.4.0 (, DEBUG)

### Describe the issue

I cannot hear any audio from the game.  The output is recognized, and correct.  The volume is up.  The css.dat files exist in the OpenRCT2 app/Data folder.

I had brought this up in discord and reddit, and Gymnasiast responded swiftly there.  He pushed an update with updated objects.  I updated on my end, but it doesn't seem like the issue is resolved.

### Steps to reproduce

1. Install on Linux Mint 20.3
2. Run game
3. Listen for audio

**Comment by Broxzier** [comment]
Audio objects were missing in the PPA. Do you still experience this issue after updating?

**Comment by seankeykong** [comment]
I ran apt-get update and upgrade, I saw openrct2 as part of that but I still didn't hear anything when running the game.  Maybe I missed something?
