### ISSUE TITLE
Canvas Tent station style inconsistent coloring between color scheme tab and actual ride coloring

### ISSUE THREAD

**Issue by SpartanFrederic104** [OpenRCT2/OpenRCT2#17383]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.0-239-gd76a215 (d76a215 on develop) provided by GitHub

### Describe the issue

In the ride paint window, the Canvas Tent station style shows an inconsistent color from the actual ride it is used on:
![Fred's Workbench 2022-06-13 12-57-44](https://user-images.githubusercontent.com/61885939/173435021-36d24b1e-c988-4cfd-8608-f9ae6361335c.png)

As you can see here, I have painted Mini Roller Coaster 1 to the colors of saturated red, yellow, and black. It also has the Canvas Tent station style selected, and the station also correctly features saturated red and yellow coloring for both the station cover and entrance/exit buildings. However, the ride window's color scheme options tab shows the Canvas Tent ride entrance with an incorrect color: the first color is always bright pink regardless of the ride's selected primary color, while the second color correctly matches what is selected on the ride. The Abstract station style does not have this issue.
![Fred's Workbench 2022-06-13 13-03-25](https://user-images.githubusercontent.com/61885939/173435582-b2e0aeb8-f33a-41a5-b594-dced64c5afe3.png)

### Steps to reproduce

1. Select any ride while in game
2. Open the color scheme options tab on any ride and select the Canvas Tent station style
3. Change the primary and secondary colors of the ride and watch as the actual ride gets recolored, but the ride window does not change the Canvas Tent ride entrance's primary color to anything other than bright pink

**Comment by duncanspumpkin** [comment]
This line is incorrect in windows/ride.cpp
`auto imageTemplate = ImageId(trackColour.main, trackColour.additional);`

It should be:
`auto imageTemplate = ImageId(0, trackColour.main, trackColour.additional);`

I think that is the issue.
