### ISSUE TITLE
Air Powered Vertical Coaster stat penalty is wrong

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#17381]
### Operating System

Windows 10 64 bit

### OpenRCT2 build

0.4.0 9c79681

### Describe the issue

When the Air Powered Vertical Drop coaster fails to make the stat requirement of having a drop at least 25 meters it gets its excitement divided by 4 in vanilla and Classic, but only by 2 in OpenRCT2. This has been a bug since at least v0.2.0.

### Steps to reproduce

1. 
2. 
3. 

### Attachments

OpenRCT2:
![Six Flags 2022-06-13 14-15-57](https://user-images.githubusercontent.com/25930360/173353885-528ff60d-279f-48d2-a17a-d5227c8d81e7.png)

Vanilla:
![Screenshot_684](https://user-images.githubusercontent.com/25930360/173354051-c13e269e-f91d-4c10-b7b1-2661f629d97c.png)

**Comment by duncanspumpkin** [comment]
![image](https://user-images.githubusercontent.com/1277401/173393391-d7089a99-b58f-405e-a7bd-1ce75b7bb542.png)
Checked against asm and it was a /4 not a /2.
