### ISSUE TITLE
Graphical enchancement: Add 'light' sprites (during thunderstorms)

### ISSUE THREAD

**Issue by DoctorWaffles** [OpenRCT2/OpenRCT2#1739]
(I've written this topic on the openRCT2 community forum, which can be found [here](https://openrct2.com/community/topic/19/graphical-enchancement-add-light-sprites-during-thunderstorms))
As my love is starting to grow for this project, I'd like to share some of my thoughts on this project. I'm aware that graphical chances might not be the most important, but as a visual artist myself I'd love to see a slightly more dynamic appearance.

I was wondering if it would be possible to add lighting sprites to the game, for example adding 'halos' around the lampposts to simulate lighting during thunderstorms. This is quite easy in all modern game engines, but I have no knowledge on the RCT2 engine whatsoever. I assume this could also be done by replacing the model during thunderstorm, but I think this will be terrible for performance (to replace x amount of lampposts during thunderstorms and remove them once the thunderstorms are gone)

To visualize my idea (poorly done, but you'll get the idea)
![](https://i.imgur.com/tg9mpFD.png)

Perhaps this idea could be used on other objects, the lampposts just popped up in my mind first. I can understand if this idea is not worth the work.

Cheers

**Comment by Patrik356b** [comment]
I like whats in the picture, though this should only be visible at certain zoom levels.

And the way I would do this is apply an extra layer, only for the illumination points and render it ontop of the other layers. And to improve performance: we would only affect the items within a certain range of the current veiwport.

**Comment by Gymnasiast** [comment]
It's certainly a nice idea.
It will take full implementation and switching to our own object format to accommodate the extra data though, so it will take some time unfortunately.

**Comment by IntelOrca** [comment]
This will require 32-bit rendering for proper additive blending effect and correct Z sorting. This theoretically can be done now as all the paint functions are finished, and could therefore be edited to draw to an RGB surface.

**Comment by IntelOrca** [comment]
See #3798
