### ISSUE TITLE
Six-seater Hyper-Twister Trains focuses ride window camera on Car 2 rather than Car 1

### ISSUE THREAD

**Issue by SpartanFrederic104** [OpenRCT2/OpenRCT2#17394]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.0-241-g13db5a7 (13db5a7 on develop) provided by GitHub

### Describe the issue

On Hyper-Twister coasters that use the six-seater trains, clicking on any train on the ride will bring up the ride window, but the ride window's camera will focus on Car 2 rather than the frontmost Car 1 (or the first non-empty car) like it should on any other vehicle/ride type. I tested this on both the Hyper-Twister coaster type and a Giga Coaster with the Hyper-Twister Trains selected. The Floorless Twister Trains for the Twister Roller Coaster do not have this issue despite having a similar build to the six-seater Hyper-Twister Trains where all cars are identical (save for an additional empty tail car on the latter). The screenshot below has Car 2 recolored to white while all other cars are colored red.

Additionally, the paint tab is also affected since it shows the coloring of Car 2 instead of Car 1. I just found out the reason for this issue occurring is that the ride object file has a `tabCar` field that should not even be there in the first place.

This issue also has existed since RCT2 vanilla.

EDIT: If you feel that this issue report belongs in the [objects](https://github.com/OpenRCT2/objects) repository, please feel free to move it there.
![Fred's Workbench 2022-06-16 16-46-22](https://user-images.githubusercontent.com/61885939/174195919-c5054410-ec64-4eb2-9b86-d01f3bb8c237.png)

### Area(s) with issue?

The bug also exists in RCT2 (vanilla)

### Steps to reproduce

1. Build any Hyper-Twister with the six-seater trains (alternatively you can find prebuilts with these trains in Six Flags Magic Mountain or Six Flags over Texas)
2. Open or test it
3. Click on any train to focus on it in the ride window and you will see that the camera focuses on Car 2 instead of Car 1

**Comment by Gymnasiast** [comment]
Object fix has been merged, keeping this issue open until the objects have been synced.
