### ISSUE TITLE
String::Format_VA memory leaks

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#17405]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.0-174-gc8df66f (c8df66f on develop) provided by GitHub

### Describe the issue

The implementation of `String::Format_VA` (mostly called from the `String::Format` overload without the buffer argument) allocates space for the string, and it's up to the user to free this (`Memory::Free`). This is however rarely done, instead it is mostly used as an argument for assignment to a `std::string`.

https://github.com/OpenRCT2/OpenRCT2/blob/13db5a771bd7f4ee4ff95bfd7ba4fcb365053467/src/openrct2/core/String.cpp#L355-L406

Since almost all cases use `std::string` already, the best approach would be to return a `std::string` or a `u8string` here.

### Area(s) with issue?

Building the game

**Comment by SaumyaBhushan** [comment]
I would like to take this.
