### ISSUE TITLE
freeing a default proprty value will cause a segfault

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#1740]
In `config_open`:
1. `config_read_properties` finds a section, say `[interface]`. `*currentSection` gets assigned to one of `_sectionDefinitions`.
2. `config_read_properties` reads a string that has a default value provided, say `current_theme`. Exact line read from config is `current_theme = "*RCT2"`.
3. `config_get_property_name_value` assigns all correct values
4. `config_get_property_def` finds property `current_theme` from `_interfaceDefinitions`, assigns this value to `property`
5. `config_set_property` finds `property->type` to be `CONFIG_VALUE_TYPE_STRING`
6. `SafeFree(destValue->value_string);` but `destValue->value_string` **was allocated on stack**: `gConfigInterface[6].default_value.value_string` as taken from https://github.com/OpenRCT2/OpenRCT2/blob/d228d1391801d59456b6aadab15d115fdbccf1f2/src/config.c#L199

**Comment by IntelOrca** [comment]
```void config_set_defaults()``` needs to copy the default string value to new memory for string properties.
