### ISSUE TITLE
Umlauted words not showing up correctly

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#1742]
This is mci.sv6, one of the title sequence scenarios:
![scr68](https://cloud.githubusercontent.com/assets/1478678/9138545/cf690ccc-3d24-11e5-8039-4e9f6335d0c7.png)

And this group in the scenario editor (should read 'Blöcke'):
![scr67](https://cloud.githubusercontent.com/assets/1478678/9138555/deebb6f4-3d24-11e5-8ae7-51b6b2931f02.png)

**Comment by IntelOrca** [comment]
Does it still do this after deleting plugin.dat?

**Comment by Gymnasiast** [comment]
Removing plugin.dat solves the scenery group problem, but not the scenario description (first screenshot).

**Comment by IntelOrca** [comment]
:+1: I'll look into it.

**Comment by danidoedel** [comment]
I think that does only happen to savegames which were saved before utf8 change...

**Comment by Gymnasiast** [comment]
@danidoedel : OpenRCT2 still uses SC6/SV6 and thus CP1252. This is an error with converting CP1252 to UTF-8.

**Comment by danidoedel** [comment]
That's why it shows the correct words with umlauts if I save now and reload... okay

**Comment by Gymnasiast** [comment]
@danidoedel : It should show the correct umlauts directly, not only after a save-and-reload.

**Comment by danidoedel** [comment]
It does, but not for the savegames saved before utf8 changes were implemented.

**Comment by Gymnasiast** [comment]
@danidoedel : Which is an error, as I have been trying to explain. The scenarios are encoded correctly and read correct in RCT2 and OpenRCT2 before the UTF-8 change. What OpenRCT2 does _now_ with saving/loading is what's wrong.

**Comment by danidoedel** [comment]
Please tell me where I said this is not an issue :D and what I just tried to clarify is that this does only happen to games which where saved before the utf8 changes were done and not to games which were started or saved now after these changes... just as a hint for IntelOrca......

**Comment by Gymnasiast** [comment]
![scr130](https://cloud.githubusercontent.com/assets/1478678/11019659/b2661008-8602-11e5-8e82-75f2b87a5988.png)

Another example. `Azi?` should show up as `Azië` and `ge?pireerd` should show up as `geïnspireerd`.

**Comment by marijnvdwerf** [comment]
Azië shows up correctly in the latest build. Is this fixed?

**Comment by Gymnasiast** [comment]
No, the description of mci.sv6 still shows up incorrectly. The same applies to 3D signs.

**Comment by marijnvdwerf** [comment]
The description doesn't seem to get put through `rct2_to_utf8`. Perhaps that's the issue?

**Comment by Gymnasiast** [comment]
Possibly, yes.

**Comment by marijnvdwerf** [comment]
Hmm... It seems that only news items and custom objects are currently processed. Not really sure how @IntelOrca wants to tackle this.
