### ISSUE TITLE
Suggestion: Rebrand v0.4.0 as v1.0.0

### ISSUE THREAD

**Issue by chaitanyathengdi** [OpenRCT2/OpenRCT2#17437]
`v0.0.1` i.e. the initial commit was created in 2014 - over 8 years ago.

With the long-anticipated `v0.4.0` with the new save format finally out, maybe it's time to mark it as a "completed" release?

the `v.0.*` naming makes it look as if this is an alpha release or something.

**Comment by Lastorder-DC** [comment]
1. Check [Roadmap](https://github.com/OpenRCT2/OpenRCT2/wiki/Roadmap). 1.0 requires Replacement of RCT2 assets(which is not released yet)
2. Issues are not for suggestion(New issue page clearly suggests that you should use discussions for that)
