### ISSUE TITLE
Text on banners skips sometimes when set to all upper case in Options

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#1744]
This bug popped up _before_ the UTF-8 merge(!)

When you turn on the option to display all banners in upper case, the text on some banners skips. It depends on the angle and banner text though.

**Comment by IntelOrca** [comment]
Yes, this is because you convert it to upper-case when drawing it but not when its measuring the width of the string to calculate the amount it needs to scroll by before repeating.
