### ISSUE TITLE
(Android Version) Language files are not found, please fix.

### ISSUE THREAD

**Issue by tunderwood89** [OpenRCT2/OpenRCT2#17446]
### Operating System

FireOS and Bluestacks

### OpenRCT2 build

OpenRCT2-0.4.0-android-arm

### Describe the issue

Whenever I start the game, it comes up with

> Failed to load language file!
> Your installation may be damaged.
>                       OK

on both Bluestacks and FireOS (if you've no idea what I'm talking about, go here: [https://www.amazon.co.uk/Fire-7-Tablet---Blue---16-GB/dp/B07JQP283L/ref=asc_df_B07JQP283L/?tag=googshopuk-21&linkCode=df0&hvadid=256003151755&hvpos=&hvnetw=g&hvrand=5314584030916908218&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1006665&hvtargid=pla-764940955897&psc=1&th=1&psc=1](url)
Please fix,
tunderwood89

### Steps to reproduce

1. Open Android version on your phone or Bluestacks.
2. That's it.

### Attachments

![BlueStacks 25_06_2022 18_01_12](https://user-images.githubusercontent.com/108191238/175783531-9fbf5b28-6437-4a03-a037-0951961261f8.png)

**Comment by duncanspumpkin** [comment]
You need to do some manual work when using the Android version to put files in the correct location. It looks like you have not done that. https://github.com/OpenRCT2/OpenRCT2/wiki/Android
