### ISSUE TITLE
"openrct2.dll" blocked by virus scan

### ISSUE THREAD

**Issue by woubuc** [OpenRCT2/OpenRCT2#1746]
I just downloaded the latest dev build (1106) but I cannot start the game because my AVG antivirus is blocking the file "openrct2.dll" and thus doesn't let me launch the exe.

The previous build I played was 1064, which worked fine. I don't know when exactly between the two builds this problem was introduced.

**Comment by rctdude2** [comment]
It appears to be a false positive triggered by AVG's heuristics. [It doesn't trigger any other AV.](https://www.virustotal.com/en/file/85beb45ab053a6e00ecfced497e071ac9a384f71b666e956137899ff29d0fb32/analysis/1438990611/)

**Comment by JarnoVgr** [comment]
Build 1074 (clean): https://www.virustotal.com/en/file/3d41c9023a0e19d9a0af7362b3a7e60d1dbea6b71a265ff552396bca42083bd3/analysis/
Build 1080 (false positive): https://www.virustotal.com/en/file/dadc2e291492c07baab52124a86d61ddf1a6e1f4465d4a775d5ce98c4962094c/analysis/

Changes between both builds: https://github.com/OpenRCT2/OpenRCT2/compare/c389228141e0d4e1042fa06fd819602a4924395e...2419c6629e4d8cf277416ea5f406aee754cf3186

It's probably related to the Visual Studio upgrade.

**Comment by Breadwinka** [comment]
Build 1150 (clean):
https://www.virustotal.com/en/file/a7d76787a8e73399e8954235d7650fa3c6ae81a50acdbb490d1623090ffb1a9c/analysis/1439935870/
