### ISSUE TITLE
Queue Banner Not Rendered when Railings set to invisible

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#17473]
### Operating System

Windows 11 Pro

### OpenRCT2 build

OpenRCT2, v0.4.0-283-g7345dd5 (7345dd5 on develop) provided by GitHub

### Describe the issue

When you set railings to invisible, the queue line banner does not display

### Steps to reproduce

1. In path tool set railing to invisible
2. Connect ride entrance to path
3. There is no banner once connected

### Attachments

![Fidwell's Sandbox 2022-06-29 15-36-21](https://user-images.githubusercontent.com/94884086/176522555-08bc8d5a-d2c0-4cb5-a162-e56e47a48b70.png)

**Comment by ocalhoun6** [comment]
Maybe this is the desired behavior for no railings?

**Comment by Gymnasiast** [comment]
This is indeed intended behaviour.
