### ISSUE TITLE
Game crashes when you deselect certain objects in scenario editor

### ISSUE THREAD

**Issue by Yggdrasill** [OpenRCT2/OpenRCT2#1747]
I have been working on creating a scenario lately, and when I try to go back to change available rides and some other objects, it crashes. This seems to be specific to things such as the 3D Cinema, but the Air Powered Vertical Coaster is not affected. New maps also do not have this problem, so it seems to be specific to the attached scenario file. I've tried to save and load new maps to reproduce the issue without the scenario file, but it doesn't happen then. 

Wine stacktrace: https://pastee.org/smwn
The scenario file: http://a.pomf.cat/wzslyu.sc6

**Comment by janisozaur** [comment]
Tested, works fine now. Probably another case solved by #2177
