### ISSUE TITLE
Positive Vertical G Value over 7 not rendered in Red on Vertical Drop Coaster

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#17474]
### Operating System

Windows 11 Pro

### OpenRCT2 build

OpenRCT2, v0.4.0-283-g7345dd5 (7345dd5 on develop) provided by GitHub

### Describe the issue

G forces over 7 G's on positive vertical G's on Vertical Drop Coaster not listed as penalty, even though it makes high intensity

### Steps to reproduce

1. Build Vertical Drop Coaster with very high positive vertical g's
2. Test Ride
3. It will not turn red even with very high positive vertical g's
![Fidwell's Sandbox 2022-06-29 15-35-21](https://user-images.githubusercontent.com/94884086/176524750-628acdb2-e055-4b50-83f8-238af05aa21a.png)

**Comment by duncanspumpkin** [comment]
This was purposely changed in https://github.com/OpenRCT2/OpenRCT2/pull/16915
