### ISSUE TITLE
pre-built paths placed outside of park boundaries in Dark Age - Castle

### ISSUE THREAD

**Issue by HtotheTML** [OpenRCT2/OpenRCT2#17489]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.0-298-g05f1007 (05f1007 on develop) provided by GitHub

### Describe the issue

some of the pre-built path that runs along the castle wall is placed outside of the park boundaries. if you're deleting pre-built paths and scenery, this leads to some awkwardly placed path tiles that you cannot seem to get rid of.
![image](https://user-images.githubusercontent.com/108596959/177019781-8e87c4ca-b085-4101-827e-c84204fd7037.png)
![image](https://user-images.githubusercontent.com/108596959/177019792-2b9036b9-d324-48c3-a3b0-51b526db7b18.png)

### Area(s) with issue?

The bug also exists in RCT2 (vanilla)

### Steps to reproduce

1. 
2. 
3.

**Comment by Gymnasiast** [comment]
Yes, that sounds a lot like the expansions.

**Comment by HtotheTML** [comment]
This has been fixed in #19657.
