### ISSUE TITLE
Unreadable chunks and checksum failures everywhere

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#1748]
Just like the title says.

![rct2checkfail](https://cloud.githubusercontent.com/assets/4167951/9151235/99b3321a-3dc9-11e5-82a2-ba1c0d902738.png)

I dunno what could be causing this; even though OpenRCT2 has had no problem loading stuff from custom scenarios before., and now it's treating every file that isn't considered RCT2-native to be corrupt.

**Comment by Gymnasiast** [comment]
If you look in the top screenshot, you'll notice that every scenario it can't load starts with ._
That might a temporary file/technical file of some sort, and not a valid scenario. So the errors in that one are expected. Set your Explorer to show hidden files, remove them, and the errors should disappear.

**Comment by Superjustinbros** [comment]
I removed all the ones that could be shown; yet it still shows the OSX folders and tries to load them.

**Comment by janisozaur** [comment]
@Superjustinbros do you still have this issue?

**Comment by Superjustinbros** [comment]
For now, there doesn't seem to be anything major; I can run the game just fine even if the status window gives me "Potential Mismatch in file numbers" every time I load it up. Perhaps since I managed to remove the offending OS X stuff.

**Comment by janisozaur** [comment]
Object loading code has been reworked since this was filed.
