### ISSUE TITLE
Rainbow Footpath graphics glitch

### ISSUE THREAD

**Issue by runelaenen** [OpenRCT2/OpenRCT2#1749]
Hey guys,

I noticed a problem with how OpenRCT2 (currently on development version 0.0.3 build A615) reads the Rainbow Footpath from Time Twister incorrectly - adds black stuff on the railings where there isn't any.

Here's how it looks in regular RCT2:
![Image of Yaktocat](http://i.imgur.com/0qCJ2xz.png)

And here's how it is in OpenRCT2:
![Image of Yaktocat](http://i.imgur.com/SLkpZNs.png)

Original topic: https://openrct.net/forum/topic/133/last/rainbow-footpath-graphics-glitch

**Comment by daihakken** [comment]
The vanilla RCT2 screenshot isn't correct, let me upload the proper one:
![image](https://cloud.githubusercontent.com/assets/13048125/9155994/309fce2a-3efd-11e5-99a8-dce691b1fa57.png)

**Comment by runelaenen** [comment]
"Also noticed that in the Pause button in OpenRCT2, you can see black pixels which are not displayed in RCT2 (except, apparently, for faulty screenshots). The palette is surely 8-bit, and one of the colours is assigned as a null."
https://openrct.net/forum/topic/133/last/rainbow-footpath-graphics-glitch#p383

**Comment by e-foley** [comment]
For what it's worth, even Chris Sawyer's website shows black pixels in the pause button of old [RCT2 screenshots](http://www.chrissawyergames.com/feature5.htm).  What has to change about the method of capturing in order for the image to appear correctly?
