### ISSUE TITLE
Particular save crashes after a minute or so

### ISSUE THREAD

**Issue by fidwell** [OpenRCT2/OpenRCT2#17490]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.0-288-g9c595cc (9c595cc on develop) provided by GitHub

### Describe the issue

The game crashes with this particular save for no apparent reason. No logs appear in the console (when running with openrct2.com), and no crash dump is created.

### Steps to reproduce

1. Open attached save (mps6.park).
2. Wait for a minute or so.
3. Game will crash.

### Attachments

[mps6.zip](https://github.com/OpenRCT2/OpenRCT2/files/9034069/mps6.zip)

**Comment by James103** [comment]
To be more specific, in OpenRCT2, v0.4.0-299-gc5871b4 (c5871b4 on develop) provided by GitHub, the attached save hangs (not crashes) during the 1295th tick after loading the park (`.\openrct2 simulate mps6.park 1294` completes, but `.\openrct2 simulate mps6.park 1295` does not complete).

**Comment by duncanspumpkin** [comment]
Great thanks for narrowing it down to a specific tick

**Comment by fidwell** [comment]
Yeah that's a better way of describing it. Running locally, the game hangs. When I hosted this file in multiplayer, the client would get disconnected and the server would be removed from the master list; trying to connect again results in a message that just says "Disconnected:". Rebooting the Docker container works fine, but of course wouldn't actually "fix" anything.

**Comment by fidwell** [comment]
Digging a little further, I think it's caused by a specific ride --- a maze called "luck check". Deleting it causes the hang. If I close and use the construction tool to remove the track, it still persists in the game, even though all the track is gone.

**Comment by James103** [comment]
Also, using a script to print the current `date.ticksElapsed` every tick,
* Loading the game, `date.ticksElapsed` is around 1,574,531.
* If no action is taken (besides optional fast-forward), the game hangs at tick 1,575,823 of the park.
* Deleting all rides as quickly as possible allows the game to run beyond that tick. However, the game may still crash or hang when deleting one of the mazes.

**Comment by fidwell** [comment]
I think the culprit is a ride called "Long Logs", the enormous log flume at the back of the park. If you close it, the game won't hang. Weirdly, the peeps seems to exit the ride from its entrance instead of its exit.

**Comment by fidwell** [comment]
Closing stale issue
