### ISSUE TITLE
the text is WILD

### ISSUE THREAD

**Issue by mynameiskrysta** [OpenRCT2/OpenRCT2#17509]
### Operating System

Windows 10 Pro

### OpenRCT2 build

OpenRCT2, v0.4.0 (c6302a1 on master) provided by GitHub

### Describe the issue

some of the letters are replaced with non-english characters 

### Steps to reproduce

1. run rct2
2. ????
3. Profit

### Attachments

![Screenshot (13)](https://user-images.githubusercontent.com/104466722/177400062-5b6c268a-bb67-43d3-aa00-436ea72ec4ff.png)

**Comment by Gymnasiast** [comment]
Indeed. Easiest way to fix is to uninstall, then reinstall OpenRCT2. (Do not remove the Documents\\OpenRCT2 folder!)

**Comment by Broxzier** [comment]
This seems to happen mostly when players apply an update while the game is still running. Make sure to fully close your game before updating.
