### ISSUE TITLE
Crash when deleting a ride after loading the save

### ISSUE THREAD

**Issue by JustinKuli** [OpenRCT2/OpenRCT2#17504]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.1 (be518f4) provided by GitHub

### Describe the issue

After clicking "Demolish" on the dialog window to remove a ride, the cursor changes to Zzzzz for a second and then the game closes unexpectedly. This only seems to happen if removing the ride is one of the first actions you take after loading the save: if I load the game and create another ride, then I can delete any rides without issues.

So far, I've only recreated this issue while deleting pre-built designs that I've placed "on top" of other pre built design's exits and paths (see the save file or screenshot for a better explanation).

I marked this as an issue with the New Save Format, because it only happens after loading, and I haven't been able to recreate it in vanilla RCT2.

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Start a scenario.
2. Create a pre-built maze.
3. Create another pre-built maze, overlapping the previous, so that it is stacked on top of the first one's exit and some path.
4. Save the game.
5. (optional) delete either of the mazes, notice the game doesn't crash
6. Load the game
7. Delete either of the mazes.

### Attachments

Save file: 
[crash-recreation.zip](https://github.com/OpenRCT2/OpenRCT2/files/9042113/crash-recreation.zip)

Screenshot: 
![setup](https://user-images.githubusercontent.com/44813129/177219236-dd475e0f-de49-4148-a590-e8bde98f20c7.PNG)

**Comment by Broxzier** [comment]
This has been an issue for a while, easy to fix but difficult to test. Thanks for providing steps to reliably reproduce this issue, this greatly helps.

**Comment by janisozaur** [comment]
@JustinKuli when it crashed, it should have produced memory dump and park replay files, `<GUID>.dmp` and `<GUID>.parkrep`. can you upload them as well?

**Comment by JustinKuli** [comment]
@janisozaur I didn't see either of those files under my OpenRCT2 folder, maybe I'm looking in the wrong place though? In particular, I know the `crash` folder is empty

**Comment by James103** [comment]
Can reproduce in OpenRCT2, v0.4.0-299-gc5871b4 (c5871b4 on develop) provided by GitHub, which is earlier than the version originally reported.

Verbose logs when the game crashes:
```
VERBOSE: Trying to access element outside of range
VERBOSE: Trying to access element outside of range
VERBOSE: [sp] Tick: 3105, GA: MazeSetTrackAction (00000027) (_networkId = 00000000; _flags = 00000001; _playerId = 4294967295; _loc = CoordsXYZD(x = 1792, y = 1568, z = 256, direction = 0); _loc.direction = 00; _initialPlacement = false; _rideIndex = Id(1); _mode = 02; ) OK
VERBOSE: [sp] Tick: 3105, GA: MazeSetTrackAction (00000027) (_networkId = 00000000; _flags = 00000001; _playerId = 4294967295; _loc = CoordsXYZD(x = 1792, y = 1584, z = 256, direction = 1); _loc.direction = 01; _initialPlacement = false; _rideIndex = Id(1); _mode = 02; ) OK
VERBOSE: [sp] Tick: 3105, GA: MazeSetTrackAction (00000027) (_networkId = 00000000; _flags = 00000001; _playerId = 4294967295; _loc = CoordsXYZD(x = 1808, y = 1584, z = 256, direction = 2); _loc.direction = 02; _initialPlacement = false; _rideIndex = Id(1); _mode = 02; ) OK
VERBOSE: [sp] Tick: 3105, GA: MazeSetTrackAction (00000027) (_networkId = 00000000; _flags = 00000001; _playerId = 4294967295; _loc = CoordsXYZD(x = 1808, y = 1568, z = 256, direction = 3); _loc.direction = 03; _initialPlacement = false; _rideIndex = Id(1); _mode = 02; ) OK
```

**Comment by Broxzier** [comment]
No crash dump is required, the steps provided cause it consistently. I suspect it has to do with tile elements getting reordered and moved to an other place in memory while deleting the maze pieces, causing the crash.
