### ISSUE TITLE
Mainmenu - Music from RCT1 is not playing anymore

### ISSUE THREAD

**Issue by iMax1994** [OpenRCT2/OpenRCT2#17513]
### Operating System

MacOS 12.4

### OpenRCT2 build

OpenRCT2, v0.4.1 (be518f4 on HEAD)

### Describe the issue

Before i could play the Game with the Music from RCT1 - i just needed to get the file css17.dat from RCT1 and copy it to RCT2/data/ - i needed to rename it to file css50.dat

With the new update - it cannot find or work with the data css50.dat - and dosen't play the music. 

### Steps to reproduce

1. With v0.4.0 i could put the Music from RCT1 to the file - and change it to css50.dat
2. Update to v0.4.1
3. It won't do anything with the file css50.dat
4. Just the Background noise appears - no music / i can only set up to "no music" or "RCT2" 

### Attachments

<img width="557" alt="Bildschirmfoto 2022-07-06 um 5 59 04 PM" src="https://user-images.githubusercontent.com/108822099/177594364-9dbc5e2b-4a75-4dde-9ff8-e6cf2d1c4adb.png">

**Comment by Gymnasiast** [comment]
Did you manage to set that up, by the way?
