### ISSUE TITLE
Free Ride Tickets campaign's penalty is wrong

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#17527]
### Operating System

Windows 10 64 bit

### OpenRCT2 build

3d16bca

### Describe the issue

The free ride tickets advertisement campaign should be 8 times less effective when the ride ticket price of the targeted ride is below €3.00, but currently that only happens when it's below €0.30.

It was still correct when Deurklink wrote his guide on guest generation:
![image](https://user-images.githubusercontent.com/25930360/178027985-4c81ae64-f19a-494b-9e84-6c26f04b08cf.png)

Now the limit is only €0.30:
![image](https://user-images.githubusercontent.com/25930360/178028097-144c448f-4e64-46ba-a401-ae11a34c2b1f.png)

### Steps to reproduce

1. Build a park with 1 ride in a pay-per-ride scenario.
2. Trap the guests in the park to get the park rating to 0 and wait until you have more than 120 guests in the park. This reduces the natural guest generation to pretty much zero.
3.  Run the free ride tickets campaign, vary the ticket price of the ride, and see when the guest generation penalty from too low a ticket price kicks in.

**Comment by rctdude2** [comment]
~Aren't those originally 0.40/0.60/0.30? I thought money values were /10 (4 -> 0.40, 40 -> 4.00, 400 -> 40.00).~

So park entry is multiples of dollars, meaning that `park_get_entrance_fee()` presumably returns dollars. But rides are multiples of 0.10 (and in plugins, 3 would denote 0.30, while 30 means 3.00), so isn't that actually 0.30? 3.00 doesn't make since because it would exclude most flat rides.

**Comment by LordMarcel** [comment]
I did a test in Classic (which should be the same as vanilla) and the guest generation suddenly died down when I lowered the price to €2.90. I suppose it could be a coincidence, I'll do some more testing later if it's still needed then.

I think €0.30 doesn't make sense as that's pretty much nothing. You can charge more than €3.00 for a lot of flat rides, but it also makes sense that an advertisement for free merry go round tickets in a theme park that also has big coasters doesn't have much effect.

That all doesn't really matter though, whatever it originally was is what it should be in OpenRCT2.

**Comment by rctdude2** [comment]
> but it also makes sense that an advertisement for free merry go round tickets in a theme park that also has big coasters doesn't have much effect

Maybe it's just a _really good_ merry-go-round. 😉 

> That all doesn't really matter though, whatever it originally was is what it should be in OpenRCT2.

Ideally, it would be the same as vanilla. This should probably be verified against the original.

**Comment by LordMarcel** [comment]
I just did a proper test in vanilla and I was indeed wrong, caused by my mediocre understanding of the code combined with a coincidence during a test that playing into my conformation bias.

I'll delete this thread now.
