### ISSUE TITLE
Network desync when placing rollercoasters with scenery since 0.4.1

### ISSUE THREAD

**Issue by skye** [OpenRCT2/OpenRCT2#17535]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

v0.4.1

### Describe the issue

When playing with 2-player multiplayer, it appears that when building any rollercoaster with scenery, the scenery and paths get messed up. It's a bit hard to explain, so I attached some screenshots. I'm not 100% sure that scenery is the issue here, but there was no issue with Woodchip, which doesn't have scenery. The rollercoaster appears correctly for the player that built it, but incorrectly for the other player. We usually get network desync errors but not every time.

We verified this is a new breakage as of 0.4.1; 0.4.0 seems to work correctly.

### Area(s) with issue?

This bug is specific to multiplayer

### Steps to reproduce

1. Start multiplayer OpenRCT2 4.1.0
2. Create Crazy Castle park
3. Build "wooden wild mouse" coaster > "Mouse Towers"
4. Coaster will look fine for user that built it, but not for other multiplayer user

### Attachments

Correct behavior with 0.4.0:

![rct_good](https://user-images.githubusercontent.com/88808/178188595-32cd51cd-6d99-4fa5-a189-c7c1c7bafb84.png)

Incorrect behavior with 0.4.1:

![rct2_bad](https://user-images.githubusercontent.com/88808/178188080-04db4d29-8ae9-425b-9ac1-2473bcb345ff.png)

**Comment by PhasecoreX** [comment]
From what I can tell, the host is able to place rides with scenery correctly. It won't cause a desync, and it shows up correctly to the client. The client, on the other hand, cannot place rides with scenery, it appears like the above images, and it will always cause a desync. It's almost like the ride is being rotated correctly, but the scenery doesn't rotate to match it.

**Comment by Broxzier** [comment]
From the screenshots it looks like all scenery and paths are rotated incorrectly, but placed correctly relative to each other.

**Comment by lalip** [comment]
Since it's still reproducible in the current build (`59c31e8`), I went bisecting by artifacts and found the earliest build exhibiting this bug to be 16585ec. The [relevant artifacts](https://github.com/OpenRCT2/OpenRCT2/actions/runs/2323726395) will expire in ~2 days in case anybody wants them
