### ISSUE TITLE
Missing audio when specifying --rct2-data-path

### ISSUE THREAD

**Issue by DanKorell** [OpenRCT2/OpenRCT2#17533]
### Operating System

Windows 10 Home, 64 bit, 21H1

### OpenRCT2 build

OpenRCT2 0.4.1 Windows Portable x64

### Describe the issue

When I boot up the game it is completely quiet, no menu music. Then when I load a park, the only sounds are the ride music. There are no sounds of guests, rides, anything else.

When I use the stable releases of 0.3.5, 0.3.5.1, and 0.4.0, it all works fine. But as soon as I use the 0.4.1 release, the sound issue comes back. So I don't believe that it is my data files, otherwise the previous versions would be affected too, and they aren't, it's just the latest stable release.

Note that I keep my game data files in separate folders, so that it is a tidier setup and so that when a new version of OpenRCT2 comes out, all I have to do is replace the OpenRCT2 files. I keep four main folders next to each other as follows:

OpenRCT2  -  this contains the OpenRCT2 files
RCT1Data  -  this holds the data files from RCT1
RCT2Data  -  this holds the data files from RCT2
UserData  -  this holds the user data files, like settings, saved games, scenarios, etc.

So to run OpenRCT2, I use a batch file that calls the executable and points it at the various data folders.

START OpenRCT2\openrct2.exe --user-data-path=UserData --openrct2-data-path=OpenRCT2\data --rct1-data-path=RCT1Data --rct2-data-path=RCT2Data
EXIT

I've seen some other people post about sounds issues, but they all seem to be from a few years back and all are resolved.

### Steps to reproduce

1. Extract the files from the latest release (0.4.1).
2. Provide the RCT1 and RCT2 data files in separate folders.
3. Call the OpenRCT2 executable with a batch script pointing to the various data folders.
4. No error message is received, but the only sounds that play are the ride music. No menu music, no guest sounds, no ride sounds, etc.
5. Restore a previous version of OpenRCT2 (e.g. 0.3.5, 0.3.5.1, 0.4.0) and load it up as above and it works fine again.

**Comment by DanKorell** [comment]
Just tried the 0.4.1 Windows 32-bit version, and the development version, OpenRCT2-0.4.1-develop-95bcca3-windows-x64, and both also have the missing sounds. As soon as I roll back to 0.4.0 it works again.

**Comment by James103** [comment]
Have you tried any of the develop commits in-between (of which there's a dozen)? Since 0.4.0 release fails to reproduce this for you while commit 95bcca3 reproduces this, then it's probably caused by any of the commits in-between.

**Comment by DanKorell** [comment]
I've just tried all of these development builds and all were affected.

OpenRCT2-0.4.0-develop-bbc706d-windows-x64.zip
OpenRCT2-0.4.0-develop-ae09128-windows-win32.zip
OpenRCT2-0.4.0-develop-5d896c6-windows-x64.zip
OpenRCT2-0.4.0-develop-ac7331f-windows-x64.zip
OpenRCT2-0.4.0-develop-e39fd92-windows-x64.zip

Then I put stable 0.4.0 back in and it's fine again.

**Comment by DanKorell** [comment]
Okay, I've managed to find a repository of development versions that goes back years, not just the latest 30 builds. This is what I've found:

b0ffa9d   11/06/2022   Broken
a0f5493   08/06/2022   Broken
15581b5   28/05/2022   Broken
e90ebb3   24/05/2022   Broken
697fa7c   23/05/2022   Working
5349e6f   22/05/2022   Working
9971ca1   14/05/2022   Working
3acec45   14/05/2022   Working

So the issue is between 697fa7c and e90ebb3.

**Comment by James103** [comment]
According to https://github.com/godotengine/godot/compare/afdae67cc381bb340da2e864279da6b836804b7f...2c11e6d9efc42370a8d7537eaff8b1ea78a283e5, this issue may be caused by https://github.com/OpenRCT2/OpenRCT2/pull/17188.

**Comment by DanKorell** [comment]
Yep, I'd spotted the new audio objects mentioned in e90ebb3. I've not seen anyone else posting about issues, though. Could it be this in conjunction with how I've separated all the folders and reference them via the command line arguments, and somehow it's not picking up the audio objects?

**Comment by DanKorell** [comment]
It looks like it is indeed due to my calling of the data files via command line arguments. If I instead just run the following:

START OpenRCT2\openrct2.exe --user-data-path=UserData --openrct2-data-path=OpenRCT2\data
EXIT

I.e. not specifying the RCT1 and RCT2 data paths ( --rct1-data-path=RCT1Data --rct2-data-path=RCT2Data ), then I get a prompt to locate the RCT2 data path and then it boots up with the audio working.

The difference is then that it is writing the data paths into my config.ini as follows:

rct1_path = "E:\\Games\\OpenRCT2\\RCT1Data"
game_path = "E:\\Games\\OpenRCT2\\RCT2Data"

But before, it was leaving these empty and taking the paths from my command line arguments. For some reason, with the paths specified via the command line arguments, the audio doesn't work.

**Comment by IntelOrca** [comment]
I am struggling to reproduce this, the only thing I was able to find was that the dropdown for selecting the title music does not show RCT1 title music when using a command line path for RCT1 data.

Can you run the game with `--verbose` and upload the output here?

One possible reason you might not get sound is that the JSON objects that come with OpenRCT2 are not up to date.

**Comment by DanKorell** [comment]
When I use the command line arguments to specify the RCT1+2 data folders, I still get the dropdown options for the title music, but no music plays. As soon as I remove the `--rct1-data-path=RCT1Data --rct2-data-path=RCT2Data` command line arguments, it works fine again.

Note that I have OpenRCT2 in it's own folder, which is alongside my RCT1Data, RCT2Data, and UserData folders. Hence my batch file in full is:

```
START OpenRCT2\openrct2.exe --user-data-path=UserData --openrct2-data-path=OpenRCT2\data --rct1-data-path=RCT1Data --rct2-data-path=RCT2Data
EXIT
```

I've tried adding `--verbose > log.txt` to the command line arguments but all I'm getting is an empty log.txt file. Even when I don't use the `--rct1-data-path=RCT1Data --rct2-data-path=RCT2Data` and it uses the locations from the config.ini instead, in which case the music and sounds then work, the log.txt remains empty.

So really, the title for this bug ought to be renamed to: missing music and sound effects when specifying `--rct1-data-path` and `--rct2-data-path` as command line arguments.

**Comment by DanKorell** [comment]
Actually, you are right about the dropdown options for the title music. When I remove the RCT1+2 data locations from the config.ini, and launch the game with the `--rct1-data-path=RCT1Data --rct2-data-path=RCT2Data` arguments, the options menu for the title music doesn't show RCT1, only RCT2, though I get no music at all in the menu regardless.

When the RCT1+2 data locations are present in the config.ini, then the RCT1 music option shows up in the dropdown, regardless of whether or not I launch the game with the `--rct1-data-path=RCT1Data --rct2-data-path=RCT2Data` arguments.

The only way I get the music and sounds is if I have the RCT1+2 data folders specified within my config.ini and _don't_ use the `--rct1-data-path=RCT1Data --rct2-data-path=RCT2Data` arguments.

**Comment by DanKorell** [comment]
It seems I'm not the only one who gets blank log files.
https://forums.openrct2.org/topic/5860-game-does-not-launch/?do=findComment&comment=26969

**Comment by janisozaur** [comment]
This is because Windows drops output of processes that target Windows subsystem. Use the other binary, which targets console subsystem.

**Comment by DanKorell** [comment]
Okay, finally managed to get a log.txt generated.

Using a batch file still resulted in an empty log file, even using the openrct2.com binary, though I could switch windows and see the output in the command window, it just wasn't saving to the file. So to get the output I had to start the command prompt separately, within my working folder, and run this command: `OpenRCT2\openrct2.com --user-data-path=UserData --openrct2-data-path=OpenRCT2\data --rct1-data-path=RCT1Data --rct2-data-path=RCT2Data --verbose > log.txt`

I've attached the output. [log.txt](https://github.com/OpenRCT2/OpenRCT2/files/9172281/log.txt)

**Comment by IntelOrca** [comment]
Could you try providing full paths (instead of relative paths) as your parameters? So each parameter value should begin with `E:\` etc.

**Comment by DanKorell** [comment]
Using the full paths, instead of relative paths, works. Though the reason I use relative paths is because this is a portable installation, and I'd not had an issue using relative paths until I updated.

**Comment by IntelOrca** [comment]
I know but trying that has now narrowed down the problem considerably, so thanks.

**Comment by DanKorell** [comment]
I just noticed that using full paths still doesn't add RCT1 music to that title music dropdown. That dropdown only seems to be working fully if the paths are in the config.ini.

**Comment by IntelOrca** [comment]
> I just noticed that using full paths still doesn't add RCT1 music to that title music dropdown. That dropdown only seems to be working fully if the paths are in the config.ini.

I know why that is.
