### ISSUE TITLE
Stalls will autorotate towards paths outside of the park

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#17542]
### Operating System

Ubuntu 22.04

### OpenRCT2 build

OpenRCT2, v0.4.1-3 (312ad3e3ce on refactor/initialise-g1, DEBUG)

### Describe the issue

Title should be self-explanatory.

![afbeelding](https://user-images.githubusercontent.com/1478678/178483792-3df6fb69-dd42-4c99-ac17-736623d087dc.png)

Originally reported here: https://forums.openrct2.org/topic/5916-stalls-auto-orienting-themselves-to-paths-outside-my-park/

An important thing to keep in mind when fixing this is paths with construction rights. There might be a helper method for this sort of thing - if not, it’s a good idea to create one.

### Steps to reproduce

1. Try placing a stall near the border, e.g. on Roaring Twenties - Skyscrapers.
2. It will auto-orient itself towards the pavement outside of the park.

**Comment by Broxzier** [comment]
This should only be a few line changes. Sloped paths where no sideways connection is possible are already excluded for instance, so checking for land ownership should be done in a similar fashion.

For reference, this PR implemented the auto-rotate behaviour: #7411

**Comment by Gymnasiast** [comment]
This is a bug, so please do not remove that label. It should clearly not autorotate that way. I’m not entirely sure about this being a `good first issue` either, it might be easy for someone who knows the codebase, which is not what the label is for (it’s for stuff that is easy for people unfamiliar with the code base).

**Comment by IntelOrca** [comment]
It sounds like a good first issue to me. A simple is in park check call to eliminate a direction.
