### ISSUE TITLE
closing window during CustomWidget.onDraw crashes the game

### ISSUE THREAD

**Issue by Sadret** [OpenRCT2/OpenRCT2#17551]
If a window containing a `CustomWidget` is programmatically closed during the execution of that widget's `onDraw` method, the game crashes without error.

**Comment by James103** [comment]
1. On what exact commit/build did you reproduce this on?
2. Can you please post a full minimal reproduction plugin script so others can easily test?

**Comment by Sadret** [comment]
1. current dev (213696e)
2. maybe later

**Comment by Gymnasiast** [comment]
This is no way to file a bug report. If the issue is still there, please file a proper one and include the test file.

**Comment by StephanSpengler** [comment]
Yeah you are right. If you find an issue that accurately describes how to reproduce a bug, you should close it because it does not use the correct form. Also, don't bother to just ask for details or improvements.

**Comment by Sadret** [comment]
Yeah, you are right. If you find an issue that accurately describes an issue, but that does not use the correct form, you should just close it. Also, don't bother asking for additional information or improvements.

**Comment by ZehMatt** [comment]
I believe I fixed that.

**Comment by Gymnasiast** [comment]
> Yeah, you are right. If you find an issue that accurately describes an issue, but that does not use the correct form, you should just close it. Also, don't bother asking for additional information or improvements.

This is **well** out of order. Especially since you **were** asked for additional information in the form of a test plugin and never provided one.
