### ISSUE TITLE
Tooltips not fully displayed

### ISSUE THREAD

**Issue by ffafe5** [OpenRCT2/OpenRCT2#17563]
### Operating System

Windows 10 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.1-27-g2a58719 (2a58719 on develop) provided by GitHub

### Describe the issue

![image](https://user-images.githubusercontent.com/50899032/179456857-6639e49d-586b-4d49-bc04-9479404293ee.png)

### Steps to reproduce

1. 
2. 
3.

**Comment by ZehMatt** [comment]
Can't reproduce this, probably fixed. Leave a comment if this still happens.

**Comment by ffafe5** [comment]
Whether or not this is reproducible, or indeed fixed, it shall haunt my dreams forevermore. Nary a day goes by that I do not quiver against the memory of these untipped tools.
