### ISSUE TITLE
Dirty visuals to the extreme

### ISSUE THREAD

**Issue by ffafe5** [OpenRCT2/OpenRCT2#17564]
### Operating System

Windows 10 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.1-27-g2a58719 (2a58719 on develop) provided by GitHub

### Describe the issue

![image](https://user-images.githubusercontent.com/50899032/179457407-78d45113-1504-4fdf-805f-cecbf7c13a90.png)

### Steps to reproduce

1. 
2. 
3.

**Comment by janisozaur** [comment]
What drawing engine is that?

**Comment by Gymnasiast** [comment]
Closing as they additionally requested information has not been provided for 6 weeks.

**Comment by ffafe5** [comment]
Sorry not sure. I was switching between them all at the time and couldn't
reproduce it after restarting the game. Ditto for the other issue I posted
