### ISSUE TITLE
Map and tracking toggle drawn in the same place.

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#1756]
Introduced by #1753. Clicking a status (like Walking) in the list will get you this:

![scr71](https://cloud.githubusercontent.com/assets/1478678/9170680/47b6f012-3f65-11e5-97ab-e23cda5d9ee3.png)

**Comment by AaronVanGeffen** [comment]
Just to clarify: it opens the park window instead of the window for the guest in question?

**Comment by Gymnasiast** [comment]
No, it draws two buttons over each other: the map button and the 'toggle tracking' button (i).

**Comment by LRFLEW** [comment]
It may be due to the code that handles resizing the window. I'll have a look at it.
