### ISSUE TITLE
Mute audio when tabbing out

### ISSUE THREAD

**Issue by runelaenen** [OpenRCT2/OpenRCT2#1758]
==> https://openrct.net/forum/topic/136/last/mute-audio-when-tabbing-out
~ Newgoods

Hi everyone!

I don't know if this is something you can already do in OpenRCT (I've only had it for a few hours), but I was curious if it could be possible to mute audio upon tabbing out. I listen to videos in the background, and I'd like to be able to hear what happens when I tab out.

**Comment by medsouz** [comment]
I'm attempting to add this, do you think it should be configurable in the options menu?

**Comment by Gymnasiast** [comment]
@medsouz : Yes, I think so.

**Comment by Patrik356b** [comment]
i'd also like to see this as optional
