### ISSUE TITLE
Screenshots not working on Mac OS Monterey

### ISSUE THREAD

**Issue by ecruteur** [OpenRCT2/OpenRCT2#17589]
### Operating System

MacOS Monterey (12.4)

### OpenRCT2 build

v0.4.0, v0.4.1, v0.4.1-71ad3af

### Describe the issue

When I use the in-game Screenshot function, I hear the sound (or see the confirmation popup when I use Giant Screenshot) but I cannot find the screenshots anywhere on my system. This was not an issue for me running v0.4.0 on Mac OS Catalina, but since I've updated to Monterey this is a problem that I also was able to replicate even downgrading to v0.4.0. 

### Steps to reproduce

1. run OpenRCT2 on Mac OS Monterey
2. use the Screenshot or Giant Screenshot function
3. check the disk to see if or where the screenshot was written

**Comment by janisozaur** [comment]
Any logs?

**Comment by ecruteur** [comment]
hi there! how can I provide logs for you? @janisozaur

**Comment by janisozaur** [comment]
They get printed to stdout - launch the game, try doing the thing, grab the logs and post them here

**Comment by ecruteur** [comment]
I apologize, I'm pretty green with this. how do I access stdout? if it's too difficult to explain don't worry about it.

**Comment by janisozaur** [comment]
You would usually launch a program and redirect any output it has to a file, e.g. `/path/to/openrct2 > log`

**Comment by Gymnasiast** [comment]
You should at least explain they need to launch via the Terminal. That is not at all obvious, and you know that full well.

Anyway, @ecruteur It’s likely you’re not looking in the correct folder. Have you tried using the red toolbox in the title screen -> Open custom content folder -> `screenshot`. That’s where OpenRCT2 normally saves its screenshots.

**Comment by ecruteur** [comment]
@Gymnasiast thank you so much, the screenshots were right there in the folder! I appreciate it. It’s odd that Finder won’t turn them up when it used to, but now it seems like that’s a Finder issue and not an OpenRCT2 one. thank you!

**Comment by Gymnasiast** [comment]
You’re welcome :-)
It’s not so much a Finder issue - the files reside in a path that is normally hidden from view. We are considering saving them in the Pictures folder, though: https://github.com/OpenRCT2/OpenRCT2/issues/6233
