### ISSUE TITLE
Package 'flac', required by 'virtual:world', not found

### ISSUE THREAD

**Issue by Gnomesenpai** [OpenRCT2/OpenRCT2#17588]
### Operating System

Fedora 36 Workstation

### OpenRCT2 build

#17582

### Describe the issue

Un-met dependancies with no instruction on how to get them.

Attempted to dnf install flac however this did not satisfy the requirement. instructions followed from website

-- Checking for module 'flac'
--   Package 'flac', required by 'virtual:world', not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:603 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:825 (_pkg_check_modules_internal)
  src/openrct2-ui/CMakeLists.txt:27 (PKG_CHECK_MODULES)
  CMakeLists.txt:368 (include)

### Steps to reproduce

1. install from website instructions on Fedora 36 Workstation
2. installation fails
3. profit?

**Comment by janisozaur** [comment]
@Gnomesenpai can you submit PR?

**Comment by janisozaur** [comment]
you are probably looking for `flac-devel` package

**Comment by Mark-C-Hall** [comment]
I just had the same issue. Wanted to say that installing flac-devel worked. I also had to install one more additional dependency: vorbisfile. I found a download at [this](https://fedora.pkgs.org/36/fedora-x86_64/libvorbis-devel-1.3.7-5.fc36.x86_64.rpm.html) site for Fedora 36. After installing these two, I was able run the Cmake command successfully.

**Comment by janisozaur** [comment]
@Gnomesenpai @Mark-C-Hall can you guys please submit PR to add those packages to instructions?

**Comment by Mark-C-Hall** [comment]
@janisozaur I submitted a change to the [wiki](https://github.com/OpenRCT2/OpenRCT2/wiki/Building-OpenRCT2-on-Linux) for Linux installation, I am not sure what to change in the main repo to warrant a PR.
