### ISSUE TITLE
Undefined Symbol when running `openrct2`

### ISSUE THREAD

**Issue by Sir-Photch** [OpenRCT2/OpenRCT2#17590]
### Operating System

Arch Linux

### OpenRCT2 build

0.4.1-1

### Describe the issue

openrct2 does not launch, and running it in the console yields:

```console
$ openrct2 --version
openrct2: symbol lookup error: openrct2: undefined symbol: _ZN9benchmark10InitializeEPiPPc
```

This is a fresh unconfigured install, on an up to date Archlinux.
The dependencies that came with it are:
- benchmark-1.6.2-1
- gtest-1.12.1-1
- libzip-1.9.2-1
- openrct2-0.4.1-1

### Steps to reproduce

1. install openrct2 with `paru -S openrct2`
2. ???
3. won't launch

**Comment by janisozaur** [comment]
Sounds like your system is misconfigured somehow. Perhaps compiled with an older version of benchmark than you are trying to run with. Can you try reinstalling `benchmark` and then `openrct2`?

**Comment by Sir-Photch** [comment]
okay so reinstalling the libraries did not help.
Downgrading to `benchmark-1.6.1-2` worked for me though; This version seems to contain that symbol.

**Comment by ryanmichaelmcclure** [comment]
> okay so reinstalling the libraries did not help. Downgrading to `benchmark-1.6.1-2` worked for me though; This version seems to contain that symbol.
> 
> If anyone else stumbles across this: the package `downgrade` from the AUR works for this.

You saved me a lot of banging my head on the wall. Thanks!!!
