### ISSUE TITLE
openrct2 won't start in archlinux with benchmark 1.6.2-1

### ISSUE THREAD

**Issue by overdetermined** [OpenRCT2/OpenRCT2#17596]
### Operating System

archlinux

### OpenRCT2 build

0.4.1-1

### Describe the issue

I am trying to install and use openrct2 for the first time on archlinux. However when running openrct2 i get the following error:

`openrct2: symbol lookup error: openrct2: undefined symbol: _ZN9benchmark10InitializeEPiPPc`

I believe it could be because of the benchmark package which is slightly newer then the newest openrct2 package:

```
Name            : benchmark
Version         : 1.6.2-1
Description     : A microbenchmark support library
Architecture    : x86_64
URL             : https://github.com/google/benchmark
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : gcc-libs
Optional Deps   : None
Required By     : openrct2
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 492.85 KiB
Packager        : Massimiliano Torromeo <mtorromeo@archlinux.org>
Build Date      : Tue 19 Jul 2022 03:03:04 PM CEST
Install Date    : Sat 23 Jul 2022 05:37:53 AM CEST
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

```
Name            : openrct2
Version         : 0.4.1-1
Description     : Open source re-implementation of Roller Coaster Tycoon 2 (requires full copy of the game)
Architecture    : x86_64
URL             : https://openrct2.io
Licenses        : GPL3
Groups          : None
Provides        : None
Depends On      : hicolor-icon-theme  sdl2  curl  speexdsp  fontconfig  libpng  openssl  libzip  icu  duktape  benchmark  flac  libvorbis  gtest
Optional Deps   : zenity: System dialog box support (GNOME/GTK) [installed]
                  kdialog: System dialog box support (KDE)
                  alsa-lib: ALSA audio driver [installed]
                  libpulse: PulseAudio audio driver [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 44.95 MiB
Packager        : Jelle van der Waa <jelle@archlinux.org>
Build Date      : Sun 17 Jul 2022 01:39:09 PM CEST
Install Date    : Sat 23 Jul 2022 05:37:53 AM CEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

### Steps to reproduce

1. install openrct2 on archlinux
2. run openrct2
3. console returns error

**Comment by 0x24authorname** [comment]
I'm experiencing the same issue. However, downgrading to `benchmark-1.6.1-2` fixed the problem immediately, so I can confirm your suspicions.

**Comment by overdetermined** [comment]
Thanks for the feedback. Unfortunately, I did not get around to test this myself... i got caught up trying to build benchmark from source instead of just downloading the previous version from:

`https://archive.archlinux.org/packages/b/benchmark/`

and then running

`sudo pacman -U benchmark-1.6.1-2-x86_64.pkg.tar.zst`

Also apologies for posting this here. I would say this is more of an issue with benchmark introducing a breaking change without adhering to semantic versioning.
