### ISSUE TITLE
Scenario Editor Randomly Raising Land

### ISSUE THREAD

**Issue by xperia64** [OpenRCT2/OpenRCT2#1761]
When I finish editing the terrain of a scenario and go to the "Set Up Invention List" step, random chunks of land outside my park boundaries may raise up on the edges outside the park, and it always seems to happen on top of footpaths. This only happens with certain landscapes I've edited, and does not happen in the original game. I was able to save my landscape, load it in RCT2, and finish it up fine from there.

Here is my scenario file: https://db.tt/UqBUzE7T
Press the "Set Up Invention List" button, and scroll up and to the right.

**Comment by ipatix** [comment]
Just wanted to say that I can confirm this issue.
