### ISSUE TITLE
All small scenery pieces are offset by 1 pixel in height from where they should be

### ISSUE THREAD

**Issue by Xtreme97-RCT** [OpenRCT2/OpenRCT2#17616]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.1-49-g3f56a0e (3f56a0e on develop) provided by GitHub

### Describe the issue

Several users have noticed that all small scenery pieces are now lowered by 1 pixel from their original positions, in all rotations. This is most noticeable with pieces that lie flat on the base of a 1/4 tile like so:

![image](https://user-images.githubusercontent.com/64152940/181106524-b38b1832-db11-487f-98cc-b026d85feeca.png)
![image](https://user-images.githubusercontent.com/64152940/181106932-16b65577-ecb4-4393-bc03-ce722821c52e.png)

The full tile square here is a large scenery piece, and the 1/4 tile pieces are small scenery. The 1/4 pieces should be flush against the edge of the large tile, but are 1 pixel lower.

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Build a small scenery piece
2. Note position relative to equivalent large scenery pieces
3.

**Comment by Broxzier** [comment]
Very likely a regression from https://github.com/OpenRCT2/OpenRCT2/pull/17343

**Comment by duncanspumpkin** [comment]
This change was made on purpose.

**Comment by spacek531** [comment]
> This change was made on purpose.
So if users want to view parks without gaps in the scenery, they must use Release 0.4.1 or earlier?

**Comment by duncanspumpkin** [comment]
> > This change was made on purpose.
> 
> So if users want to view parks without gaps in the scenery, they must use Release 0.4.1 or earlier?

Or we have to revert that pr. @Sadret

**Comment by ocalhoun6** [comment]
#17343 was about fixing the way things appear on sloped ground.

Is it not possible to change it so that it _only_ applies to sloped ground, not to flat ground?

**Comment by Broxzier** [comment]
The new behaviour is cleaner, but should definitely match the old behaviour for when on flat parts of a surface. This may be as simple as subtracting 1 from the result.

**Comment by Sadret** [comment]
Looking through #17343 again, there seems to be no change in the behavior for flat surfaces.
I'll investigate further.

**Comment by duncanspumpkin** [comment]
> Looking through #17343 again, there seems to be no change in the behavior for flat surfaces. I'll investigate further.

Its the change to the `SceneryQuadrantOffsets` i suggest reverting that.

**Comment by Sadret** [comment]
> > Looking through #17343 again, there seems to be no change in the behavior for flat surfaces. I'll investigate further.
> 
> Its the change to the `SceneryQuadrantOffsets` i suggest reverting that.

This will change the scenery placement though. E.g. quarter tile scenery on slopes will be at the wrong height again. So we need to do more than that.

I would rather change https://github.com/OpenRCT2/OpenRCT2/blob/176c2f1e5706951faa640e398891364a618a2f5d/src/openrct2/paint/tile_element/Paint.SmallScenery.cpp#L161-L162
to subtract 1 and add a comment about how this is to maintain compatibility with existing quarter tile custom scenery.

**Comment by duncanspumpkin** [comment]
I would do it the other way round put the +1 back into the scenery placement and revert the +1 from the `SceneryQuadrantOffsets`

**Comment by Sadret** [comment]
Why? Especially, how would you justify (i.e. by a comment in `SmallSceneryPlaceAction`) why we add one to the offset?

I argue that `SceneryQuadrantOffsets` now contains the values how they should be.

**Comment by duncanspumpkin** [comment]
> Why? Especially, how would you justify (i.e. by a comment in `SmallSceneryPlaceAction`) why we add one to the offset?
> 
> I argue that `SceneryQuadrantOffsets` now contains the values how they should be.

As it then matches vanilla as close as possible but it ultimately doesn't matter much.
