### ISSUE TITLE
Crash dumps are no longer made like before and not uploaded to backtrace

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#17632]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.1 Release (be518f4) provided by GitHub

### Describe the issue

When the game crashes, it used to create a crash dump, save file, screenshot, copy of the config, and ask the player to automatically upload them to Backtrace for inspection. This no longer happens. Instead, crash dumps now appear in `%localappdata%\CrashDumps`, and without the other files.

### Steps to reproduce

1. Start the game
2. Force a game crash by running the `dereference` game command
3. Observe how the game just quits with no message, and check `%localappdata%\CrashDumps`

**Comment by janisozaur** [comment]
First thing to check is builds that had dependency updates: https://github.com/OpenRCT2/Dependencies/releases cf https://github.com/OpenRCT2/OpenRCT2/blob/34a7421b980df2ee396337ee456fac48ded48f0e/openrct2.proj#L40-L45

Perhaps a possible cause could be https://github.com/OpenRCT2/OpenRCT2/pull/16887 which modified things related to breakpad.
