### ISSUE TITLE
Upside Down Special Element list doubles up on names

### ISSUE THREAD

**Issue by karst** [OpenRCT2/OpenRCT2#17639]
### Operating System

Windows 10, 64 Bit 

### OpenRCT2 build

OpenRCT2, v0.4.1-70-g5f9b0da (5f9b0da on develop) provided by GitHub

### Describe the issue

![image](https://user-images.githubusercontent.com/1516893/181796092-19c54421-61f3-4b55-9aa4-bd41e21e69a3.png)
The special element list currently double ups on all elements from upside down. Found out about this while testing the new elements, but I tested this in latest build and it occurs there aswell.

### Steps to reproduce

1. Build a special element that makes the ride go upside down (like a half corkscrew).
2. Switch it to a half loop, but before clicking it look at the list, You will notice that the corkscrew and half loop are double in that list aswell aswell as any other element that comes from upside down.

**Comment by jazzysoggy** [comment]
This issue seems to be reproducible in RCT2 as well, or at least the one coming from GOG.
![Untitled](https://user-images.githubusercontent.com/39224097/182009522-eefcef0e-a93e-4509-932d-f52518b72843.png)

**Comment by Gymnasiast** [comment]
Also affects vanilla.
