### ISSUE TITLE
Grid won't re-enable after buying Construction Rights

### ISSUE THREAD

**Issue by FlashOneOneTwo** [OpenRCT2/OpenRCT2#17657]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.1-82-g889293f (889293f on develop) provided by GitHub

### Describe the issue

Similar to the staff patrol issue, when you start to buy construction rights, the grid disables and won't re-enable after.

### Area(s) with issue?

Building the game

### Steps to reproduce

1. Open the buy new land/construction rights window.
2. Switch to buying construction rights.
3. The grid will be disabled and re-enabled.

**Comment by Broxzier** [comment]
This may be a regression. Does this happen on release too?

**Comment by jazzysoggy** [comment]
On which map did you encounter this issue? And could you give a picture of this happening?

**Comment by FlashOneOneTwo** [comment]
It happens in the release build too. It happens on any map when I switch from buying new land to construction rights; the grid gets disabled and won't come back until turned on again in the options. It's not game-breaking or anything, just something I noticed
![Example 1](https://user-images.githubusercontent.com/108739238/182437595-f970ebf2-d7bf-45c2-a328-251c109e1c47.PNG)
![Example 2](https://user-images.githubusercontent.com/108739238/182437619-5f9df00d-dc0d-4eb4-80e9-0c7a28778801.PNG)
.
