### ISSUE TITLE
land tool causes terrain edge corruption

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#17666]
### Operating System

Windows 11 Pro

### OpenRCT2 build

OpenRCT2, v0.4.1-97-g281cf13 (281cf13 on develop) provided by GitHub

### Describe the issue

when making my own bench, I was using the land tool and for some reason all of my edges became corrupt
[buggithub.zip](https://github.com/OpenRCT2/OpenRCT2/files/9230351/buggithub.zip)

### Steps to reproduce

In order to reproduce this issue, you may need to change land types or use void surface on outer tile of map / water

**Comment by Broxzier** [comment]
Please provide actual steps to reproduce this, or this will be near impossible to find the cause of.

**Comment by 733737** [comment]
make entire edge tile along map void and lower to lowest height, then raise water along map edge, then raise land along mag edge and lower water along map edge

**Comment by Broxzier** [comment]
I don't see any corruption.

![March_bench 2022-08-16 21-12-44](https://user-images.githubusercontent.com/9705046/184963014-d4a73dba-3f37-4b1f-b272-96230f83ec4c.png)

![Unnamed park 2022-08-16 21-10-54](https://user-images.githubusercontent.com/9705046/184962570-13185c79-98bc-4a54-ae97-89f78e611c82.png)

A screenshot or something would help to know what looks wrong to you.

**Comment by 733737** [comment]
it only occurs when terrain edge void is used in conjunction with surface void and water

**Comment by Broxzier** [comment]
![Unnamed park 2022-08-16 23-22-43](https://user-images.githubusercontent.com/9705046/184987609-130363ee-fccc-491e-95ab-39242065112b.png)

You mean like this?

**Comment by 733737** [comment]
In order to reproduce the issue, you must lower the land height to -30ft on the outermost tiles of the map. It will then have a 10-20% chance to cause a visual glitch similar to accidental terrain surface deletion, except it will occur vertically

**Comment by Broxzier** [comment]
Once again, please provide the exact step to trigger this. It's very unlikely to have only a chance of happening. Also add some screenshot to show what we're actually looking for.

**Comment by 733737** [comment]
![March_bench 2022-08-21 16-30-20](https://user-images.githubusercontent.com/94884086/185809710-33012253-1ca4-4348-a2c1-414d20500ddb.png)
[landcorruption.zip](https://github.com/OpenRCT2/OpenRCT2/files/9389899/landcorruption.zip)

I discovered that it occurs when you make the outermost edge and surface void, then raise water over land, then you MUST use mountain creation tool to cause corruption

**Comment by 733737** [comment]
and it does NOT persist thru saved games, I've known this for months

**Comment by 733737** [comment]
I ran into this issue again today, so it still persists in the latest game build

**Comment by 733737** [comment]
image taken by another player
![Schermopname_169](https://user-images.githubusercontent.com/94884086/190321569-54957eda-e190-4013-917e-491f8f380b4d.png)

**Comment by 733737** [comment]
<img width="425" alt="Screenshot_2023-08-06_at_22 27 50" src="https://github.com/OpenRCT2/OpenRCT2/assets/94884086/490e3b8f-3b54-415f-9e88-63fc66b04963">
still occurs in latest build when using mountain tool on edge of map

**Comment by Broxzier** [comment]
Alright, so after trying to reproduce this once again, I was able to by enabling the cheat that disables clearance checks, and lowering the neighbouring ground to the lowest possible level. These are critical details for this issue.

**Comment by 733737** [comment]
I probably overlooked that since I only use clearance checks when I build underground, so when I play the game I perpetually have them disabled. Thanks for your extra effort!
