### ISSUE TITLE
New track elements don't allow to be saved

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#17683]
### Operating System

Windows 11, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.1-119-gfd54e96 (fd54e96 on develop) provided by GitHub

### Describe the issue

Well, this bug happen when using the medium half-loop, large corkscrew or zero G rolls

### Steps to reproduce

1. Build a single rail or a hybrid
2. build any new track pieces
3. try to save it
4. can't save it

### Attachments

![BUG 2022-07-02](https://user-images.githubusercontent.com/83843734/182488055-97a540c7-1635-45ea-bc0c-ccfdf61e4f3c.png)

Traduction (not perfect)

Can't save the track...
The track have elements that can't be saved in the preview files.

**Comment by IntelOrca** [comment]
You can't save new track pieces or mixed footpaths yet until we have a new track design format (NTDF)

**Comment by X123M3-256** [comment]
This isn't a bug, the error message tells you exactly what the issue is.

**Comment by karst** [comment]
This error message was added in #17499 and was intended to prevent this bug report, it works as intended currently as above mentioned. I don't know French well enough so I have no clue if it gives a clear enough statement for it.

**Comment by Gymnasiast** [comment]
The French message seems clear enough to me. The French translator also seems to be quite involved, so I’m quite sure he came up with a proper translation.

In any case, this works as intended.
