### ISSUE TITLE
Selecting any staff from the staff list always shows security guard 1

### ISSUE THREAD

**Issue by Frytag** [OpenRCT2/OpenRCT2#17701]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.4.1 (be518f4) provided by GitHub

### Describe the issue

Park has multible handymen, mechanics, security guards and entertainers. No matter which one of them I select from the staff menu, the small view window that opens says it shows the selected staff member but always follows "security guard 1". (see screenshot)
![Show view of staff member](https://user-images.githubusercontent.com/110566316/182699651-96a091b9-d72e-41c4-8844-d24ab02fd24a.png)

When I try to locate the nearest mechanic from a ride menu, I get the same result:
![Locate nearest mechanic](https://user-images.githubusercontent.com/110566316/182701628-f868ca9d-c971-48db-9723-99e9d6ca78b7.png)

When I click "Locate this on Main View" in the staff member window, the game centers on "security gurad 1"
![Locate this on Main View](https://user-images.githubusercontent.com/110566316/182702481-e71007ad-0097-45ad-b87a-3dfc4a604c25.png)

When I click "Follow this on Main View" in the staff member window, the game centers on the correct staff member.
![Follow this on Main View](https://user-images.githubusercontent.com/110566316/182702835-14f88349-9103-4fc7-a2da-7ec33f5b6227.png)

Once I click "Move this person to a new loaction" and then place the staff member, the bug is gone, but only for that specifc staff member and only until you close the window again.
![grafik](https://user-images.githubusercontent.com/110566316/182704199-9ac1572a-06a9-47ad-81b6-f56531be7b21.png)

Moving security guard 1 around doesn't change anything.

Fireing security guard 1 is the only way to get rid of the bug permanently.
Rehireing a new security guard by the same name does not bring the bug back.

### Steps to reproduce

The bug us present in the attached safe file.
1. Open the attached safe file.
2. Open the staff menu and select any of the staff. (Handyman, Mechanic, Security Guard or Entertainer)
3. The staff being followed is security guard 1

(The plugins Benchwarmer and Ride Price Manager were used in this scenario.)

### Attachments

[Jomanda Gardens_final.zip](https://github.com/OpenRCT2/OpenRCT2/files/9254551/Jomanda.Gardens_final.zip)

**Comment by Broxzier** [comment]
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/17503, already fixed on develop.
