### ISSUE TITLE
Unable to change sign to "Do not enter" on latest multiplayer build. 

### ISSUE THREAD

**Issue by Joris-Driessen** [OpenRCT2/OpenRCT2#17706]
**Operating System**

Windows 10

**OpenRCT2 build**

0.4.1-128gfe9e609

**Describe the issue**

It is not possible to use the "Do no  enter" function directly placing a sign over a pathway in a multiplayer server. Clicking on the icon just shows the clicked_on animation. Leaving the server and logging on to it solves the problem. This bug was found on the multiplayer server of RC&F.

**Steps to reproduce**

1. Log onto a multiplayer server.
2. Build a piece of path for the sign.
3. Press the "Do not enter" icon. 
4. Log out of the multiplayer server.
5. Log back into the multiplayer server. 
6. Right click the sign.
7. Press the "Do not enter" icon. 

**Edit:** I just tried it on another server. There the sign functioned fine. Tried it again on the RC&F server and didn't work. There was another person logged onto the RC&F server so it might be an issue with multiple users on a server, or the way the server is hosted.

**Comment by AaronVanGeffen** [comment]
Is this still an issue today?
