### ISSUE TITLE
Objets missing and Wall Terrain Colour

### ISSUE THREAD

**Issue by R3V13** [OpenRCT2/OpenRCT2#17714]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.4.1 (be518f4) provided by GitHub

### Describe the issue

Having created a new scenario, when selecting all the available objects, later in the game not all of them are shown, for example what I have missed are those with a North American theme... It also does not allow you to apply the color to the walls when you raise the terrain

### Area(s) with issue?

Building the game

### Steps to reproduce

1. Create a new scenario
2. Select all of the objets avaible in the game
3. Start that scenario as a game
4. Some theme objetcs are missing, for example the TNT boxes and some walls

### Attachments

![Terra Mitica 2022-08-05 18-32-28](https://user-images.githubusercontent.com/110686487/183121596-f0db7e3e-9041-4918-a55a-aa08ebd12384.png)
![Terra Mitica 2022-08-05 18-32-40](https://user-images.githubusercontent.com/110686487/183121601-d67170b9-c7ee-4057-be0d-7b8007850885.png)

**Comment by duncanspumpkin** [comment]
There is a limit on how many scenery tabs you can have atm. Have you checked the misc scenery tab for your items.

**Comment by Gymnasiast** [comment]
Since there has been no reply for a month, closing this.

The terrain wall thing is most likely caused because you don’t have RCT1 installed.
