### ISSUE TITLE
Track elements are listed twice when building backwards

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#17735]
### Operating System

Windows 10, 64 bit, build 19044

### OpenRCT2 build

OpenRCT2, v0.4.1-143-g5249ae1 (5249ae1 on develop) provided by GitHub

### Describe the issue

Very related to https://github.com/OpenRCT2/OpenRCT2/issues/17639

When building a coaster with inversions backwards, track elements that go from flat to inverted will be listed twice. See attached screenshot for an example.

### Steps to reproduce

1. Start Build your own Six Flags
2. Partially build an inverted coaster with a half loop or any other inversion
3. Remove the inversion backwards
4. Open the special track elements list

### Attachments

![Six Flags 2022-08-06 11-49-01](https://user-images.githubusercontent.com/9705046/183243866-0b82bc13-c01c-4c94-b868-b6ccd8ddb6cf.png)

**Comment by 733737** [comment]
this was fixed a while ago
