### ISSUE TITLE
String for Special List says "Block brakes" instead of "Block Brakes"

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#17730]
### Operating System

Windows 11 Pro

### OpenRCT2 build

OpenRCT2, v0.4.1-142-g7136b08 (7136b08 on develop) provided by GitHub

### Describe the issue

![wasdadwadwawddawadw](https://user-images.githubusercontent.com/94884086/183242767-fcdd8d8f-1213-4126-b12d-df7e5be2a6db.png)
In the image you can clearly see "Brakes" and all other elements denoted with all first letters capitalized, for consistency; I believe the block brakes string should be changed to match the formatting of the other elements to "Block Brakes"

### Steps to reproduce

Try to build special element on any coaster

**Comment by Gymnasiast** [comment]
Inconsistencies like these are not bugs.

**Comment by 733737** [comment]
ok I'll keep that in mind

**Comment by Gymnasiast** [comment]
You can still open issues for them, it’s just that they’re not classified as _bugs_. ;-)

**Comment by Gymnasiast** [comment]
I took a look, but there are loads of strings that are not all in Title Caps. "Station platform", "Helix up", "Water splash" and several others. As such, I don’t think this is really something to single out as a bug/inconsistency.
