### ISSUE TITLE
Pathfinding bug

### ISSUE THREAD

**Issue by EnnuiBo** [OpenRCT2/OpenRCT2#1774]
I had posted this on the subreddit before I found this place, but  I had an issue where I would start a Magic Mountain new game, and when I would use the cheat Give Maps, after a while a lot of guests would start flocking to one area of the park ( http://i.imgur.com/Hqe3DQ0.jpg ) and would never leave, they get locked into an endless "Heading for Psyclone' 

https://www.dropbox.com/s/ntctbkepropuhhz/Pathfinding%20Bug%20replication.sv6?dl=0 Here is a save file for an example, it started on build 621 and I'm running build 630 right now

**Comment by Patrik356b** [comment]
Most likely a duplicate: https://github.com/OpenRCT2/OpenRCT2/issues/1703

**Comment by IntelOrca** [comment]
Does this still happen?

**Comment by Nubbie** [comment]
@IntelOrca 
Tested this 3 times, all of the times, all of the people walking to Psyclone chose a different route
The AI code has been changed so much this problem on this specific save doesn't seem to be fixed
