### ISSUE TITLE
Unable to edit prices for rides and shops

### ISSUE THREAD

**Issue by CDB-Man** [OpenRCT2/OpenRCT2#17746]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.4.1-154-g980e3cb (980e3cb on develop) provided by GitHub

### Describe the issue

Prices cannot be edited for all rides and shops, but only for the 1st price entry on the pricing screen.  The 2nd price entry is editable.  For the 1st entry, the price cannot be edited by both using the buttons, or by clicking on the price and typing in a new value using the dialogue box.

### Steps to reproduce

**See screenshot, see also save file in comment [#2](https://github.com/OpenRCT2/OpenRCT2/issues/17746#issuecomment-1207298572).**

The Cape Canaveral launched freefall has 1 editable price on the price tab, this cannot be edited.  Pressing + or - signs a click is registered (the button graphic changes colour to show it was clicked) but the price does not change.  If you click on the price and edit it using the dialogue, after you press OK the updated price does not reflect.

For the Woodchip coaster, the admission price similarly cannot be edited.  However, this pricing tab as a 2nd editable price, the price of the on ride photo.  The on ride photo price can be edited without issue.

The info kiosk has similar behaviour -- the map price cannot be edited (it's the 1st price on display) but the umbrella price can be modified no issues (it's the 2nd price on display).

The park entrance price can be edited without issue.

### Attachments

![image](https://user-images.githubusercontent.com/14037303/183267658-f8c3dcc0-42e5-49de-a280-345da9f046f6.png)

**Comment by CDB-Man** [comment]
UPDATE: issue only occurs on games loaded from a save file.

1. If I start a new game in Forest Frontiers and build a ride, no issue.
2. If I build a new ride in a save file, cannot edit the price.

 The screenshot earlier is from a save file for Ivory Towers, and Cape Canaveral was a newly built ride in the save file.
Attached the save file.

[Ivory Towers.zip](https://github.com/OpenRCT2/OpenRCT2/files/9275907/Ivory.Towers.zip)

**Comment by CDB-Man** [comment]
UPDATE: it looks like the prices to my toilets are being modified... instead of Cape Canaveral and Woodchip...

**Comment by Stefan6421** [comment]
Same issue here regarding shop prices. What I have seen is that the prices will do that only when the box "same price throughout park" is checked the first time. If you skip that, there are no issues.

**Comment by SpartanFrederic104** [comment]
I cannot seem to reproduce this. I started up a new game in Sherwood Forest and I was able to change the prices of the rides just fine.

**Comment by CDB-Man** [comment]
> I cannot seem to reproduce this. Any exact steps to do so? This seems to have been caused by a refactor.

@SpartanFrederic104 the error does not seem to occur on new games (see comment #2).  Download my Ivory Towers save file and you'll be able to replicate the error.

**Comment by fidwell** [comment]
I was able to reproduce this today in a fresh multiplayer game I started in Six Flags Belgium.

**Comment by Gymnasiast** [comment]
Looking through recent history, my first suspect is https://github.com/OpenRCT2/OpenRCT2/commit/a44ddd5adc5b9a8a3743f559a1e013b8b5305262.

**Comment by Gymnasiast** [comment]
A fix is pending in https://github.com/OpenRCT2/OpenRCT2/pull/17765 . Could you all try this out?

**Comment by fidwell** [comment]
That seems to have done the trick. Thanks!

**Comment by VillainFan42** [comment]
A friend of mine noticed this bug. When you click on the option for any stall, it locks the price of all of your rides so you can’t change them, and it sets the price of EVERY stall, regardless of type, to that price. Including bathrooms.
