### ISSUE TITLE
Slash in "new file" dialog when saving ride design creates a subfolder

### ISSUE THREAD

**Issue by sudofox** [OpenRCT2/OpenRCT2#17763]
### Operating System

Manjaro Linux (rolling release)

### OpenRCT2 build

v0.4.1

### Describe the issue

I tried to save a variant of a ride design with an added photo section, so I named it "Shorty Corkscrew w/ Photo".

A folder called `Shorty Corkscrew w` was created containing a file called `  Photo.td6`

Perhaps filenames should be sanitized here? I wasn't really thinking when I typed in the ride name

### Steps to reproduce

Already included in preceding section

**Comment by James103** [comment]
Also occurs when saving a park.

To reproduce, open OpenRCT2, v0.4.1-155-g9e1b24d (9e1b24d on develop) provided by GitHub and save a park with a file name of `a/b`. A folder named `a` will be created if it doesn't exist and the file `b.park` will be created in that folder.

**Comment by CorySanin** [comment]
This doesn't seem like a bug to me. I wouldn't expect GIMP to sanitize/escape a slash in a filename, same goes for OpenRCT2. Just my two cents.

**Comment by James103** [comment]
The system file dialog used by many programs on Windows 10, 64-bit to determine where to save a file will error with "The file name is not valid" if the file name contains slashes.

**Comment by ocalhoun6** [comment]
> This doesn't seem like a bug to me. I wouldn't expect GIMP to sanitize/escape a slash in a filename, same goes for OpenRCT2. Just my two cents.

But GIMP is a professional-level tool that can assume more competence from its users. And it's also a program that will often be used to save multiple different versions of a file, perhaps in multiple different directories, by many of its users.

In a game, I don't think that should be as easily assumed that people would know what the slash in the filename will do. And also, I think most users of the game don't have many (if any) subfolders for save files.

-------

Just tried this in GIMP, actually.

It works, but only if the subfolder already exists. If the subfolder does not exist, you get this:
![Screenshot_20220810_101815](https://user-images.githubusercontent.com/26573303/183976649-ac124df3-edf4-4655-a09c-4824b569d92f.png)

So if OP tried to replicate the original bug in GIMP, it wouldn't happen -- he'd get an error message saying that the folder doesn't exist. Which would prevent the problem in almost all cases. _Then_ the only issue with someone accidentally referencing a subfolder with a slash in the filename would be in the very unlikely case that they just happen to already have a subfolder with that name. But if people _want_ to use a slash in the filename to reference subfolders, they can still do so ... as long as they create the folder first.

I'd say that GIMP's compromise here is probably the best choice. If there's a slash in the filename, then check to see if the directory exists. If it exists, save the file there, using the rest of the filename after the slash. If the directory doesn't exist, give an error message.

**Comment by CorySanin** [comment]
> The system file dialog used by many programs on Windows 10, 64-bit to determine where to save a file will error with "The file name is not valid" if the file name contains slashes.

Then maybe that's what OpenRCT2 should do. I'm on board with that.

> So if OP tried to replicate the original bug in GIMP, it wouldn't happen -- he'd get an error message saying that the folder doesn't exist. (It does not create the directory for you.) Which would prevent the problem in almost all cases.

I am surprised by this. However, my point that it doesn't try to somehow encode slashes as part of the filename is still true.

> I'd say that GIMP's compromise here is probably the best choice. If there's a slash in the filename, then check to see if the directory exists. If it exists, save the file there, using the rest of the filename after the slash. If the directory doesn't exist, give an error message. (Though maybe a more user-friendly error message would be better. "Invalid file name" would do nicely.)

I'm in agreement that to cause less confusion, the save dialog shouldn't be capable of making new folders. This may be considered a bug and the solution is to error out, not to try to encode the filename.
