### ISSUE TITLE
Uncapping FPS garbles Intro / EDIT: also with uncapped FPS off (?)

### ISSUE THREAD

**Issue by ipatix** [OpenRCT2/OpenRCT2#1776]
Just a quick shot of the issue:
![screenshot 112 openrct2](https://cloud.githubusercontent.com/assets/8502545/9240790/d2609b12-416a-11e5-8fe2-e1c4a45082ff.png)

Uncapping FPS causes graphical glitches in the intro. You can see parts of the final titlescreen through the black background. Also, as you can see in the image above, the colors get mixed up a little and the border of the RCT logo looks very weird.

**Comment by Gymnasiast** [comment]
The intro is also glitchy with Uncapped FPS off, with the Chris Sawyer and RCT2 logos flickering wildly.

**Comment by ipatix** [comment]
Oh, okay. I did a quick test with capped FPS and didn't have issues but I might have clicked it away too quickly.

**Comment by mrtnptrs** [comment]
You see issues with uncapped FPS on and off, but you see different issues...

**Comment by Gymnasiast** [comment]
Exactly. With uncapped FPS off it's mostly issues with flickering.
