### ISSUE TITLE
Colour preset RNG is biased

### ISSUE THREAD

**Issue by karst** [OpenRCT2/OpenRCT2#17784]
### Operating System

Windows 10, 64 Bit 

### OpenRCT2 build

OpenRCT2, v0.4.1-165-gbe52f64 (be52f64 on develop) provided by GitHub

### Describe the issue

It seems like rides cycle through colors once and then favour one colour over any other. I found this out while adding more presets to a ride, which wouldnt load as it was stuck on the same colour.

![image](https://user-images.githubusercontent.com/1516893/184199358-2401c034-f04b-4dc0-aa8c-9f4aa42c4487.png)

### Steps to reproduce

1. Choose a ride type
2. Build it
3. Repeat
4. Eventually you will notice it will only select a single colour and no others.

**Comment by SpartanFrederic104** [comment]
This is especially noticeable on ride types with only two track/ride color presets, namely the Vertical Drop Roller Coaster, Mini Suspended Coaster, and Mine Train Coaster.

**Comment by karst** [comment]
I feel there might be another issue going on than just a broken RNG. The entire `ColourPresets` field is broken. I have completely deleted the old colours for the flying coaster just to try and replace them with the new presets I created. And these were the ones that placed down 
![image](https://user-images.githubusercontent.com/1516893/184277611-e671b77d-cc5e-4099-8107-06327e157a81.png)

These are the old colours. I don't know where it draws these colours from now, but it's certainly not the `ColourPresets` field.

**Comment by karst** [comment]
> I feel there might be another issue going on than just a broken RNG. The entire `ColourPresets` field is broken. I have completely deleted the old colours for the flying coaster just to try and replace them with the new presets I created. And these were the ones that placed down ![image](https://user-images.githubusercontent.com/1516893/184277611-e671b77d-cc5e-4099-8107-06327e157a81.png)
> 
> These are the old colours. I don't know where it draws these colours from now, but it's certainly not the `ColourPresets` field.

I think i figured out what I did wrong here. The ride might start as inverted but i think it pulls the presets off the non-inverted portion of the track which comes first.
