### ISSUE TITLE
The entire `ColourPresets` field is broken

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#17795]
"I feel there might be another issue going on than just a broken RNG. The entire `ColourPresets` field is broken. I have completely deleted the old colours for the flying coaster just to try and replace them with the new presets I created. And these were the ones that placed down 
![image](https://user-images.githubusercontent.com/1516893/184277611-e671b77d-cc5e-4099-8107-06327e157a81.png)

These are the old colours. I don't know where it draws these colours from now, but it's certainly not the `ColourPresets` field. "

Originally posted by @karst in https://github.com/OpenRCT2/OpenRCT2/issues/17784#issuecomment-1212685671

**Comment by IntelOrca** [comment]
I can not reproduce this

**Comment by Gymnasiast** [comment]
Cannot reproduce either.

**Comment by karst** [comment]
You are correct. I used the secondary field on the flying coaster (for the inverted part) as  my test in that image. The secondary field doesn't seem to do anything for this and might just be redundant code, but I cannot tell you this with certainty. Editing the primary field did work just fine for me,
