### ISSUE TITLE
Bug: Rides edited through Cheating break down instantly [VIDEO INCLUDED]

### ISSUE THREAD

**Issue by UTNerd24** [OpenRCT2/OpenRCT2#1780]
So I noticed something strange recently while playing OpenRCT2. If I edit a ride with cheats on (eg: launch speed) It's Reliability will almost immediatley drop to 0 and break down constantly.
My guess is that either the game is trying to calculate an invalid script, or there is some sort of anti-cheat mechanism hidden in the game's code. This has occurred to me in the past too, when I used 8Cars to change the trains on a rollercoaster in the original version.

https://www.youtube.com/watch?v=b0QJ1q87YHg

**Comment by IntelOrca** [comment]
May be related to this:
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/ride/ride_ratings.c#L635

**Comment by duncanspumpkin** [comment]
Its to do with how the reliability is calculated. `static void ride_ratings_check_valid_configuration(int rideIndex)` from `ride/ride_ratings.c` has a check to make sure you are not exceeding the max speed.

**Comment by UTNerd24** [comment]
So it IS Anti-Cheat? If so, is there a way around this? Like, an Ideal top speed or something?

Im not very good with understanding coding, Im just here to let people know about bugs and ways this great project can be improved.

**Comment by Gymnasiast** [comment]
Something to note: I removed the responsible method in OpenRCT2, but the original RCT2 subroutine is still called by original RCT2 code, which will keep influencing reliability until all original code calling it (directly or indirectly) is implemented.

**Comment by IntelOrca** [comment]
@Gymnasiast I don't think so.

**Comment by Gymnasiast** [comment]
After some extra testing, I think you're right - see Gitter why.

**Comment by UTNerd24** [comment]
Thanks for the help!
