### ISSUE TITLE
Steam Overlay doesn't pause game with box ticked

### ISSUE THREAD

**Issue by karst** [OpenRCT2/OpenRCT2#17816]
### Operating System

Windows 10, 64 Bit 

### OpenRCT2 build

OpenRCT2, v0.4.1-182-ga07daae (a07daae on develop) provided by GitHub

### Describe the issue

When launching OpenRCT2 through steam (non steam game, or in my case I replaced RCT2.EXE with Ted's launcher) when opening steam overlay with the `Pause game when Steam overlay is open` doesn't actually pause the game. 
![image](https://user-images.githubusercontent.com/1516893/184517286-4616ddfa-e74e-4a1b-85ac-e99ff61ff2d1.png)
It'd be nice to have this feature working (again, idk if it ever did) or if not this button should be removed entirely.

### Steps to reproduce

1. Open game through Steam
2. Tick box `Pause game when Staem overlay is open` in the options menu.
3. Open a game that's running the simulation
4. Open steam overlay (by default Shift+Tab)
5. The game doesn't pause

**Comment by jazzysoggy** [comment]
Are you using OpenGL Drawing Engine or Software with Hardware Display?

Since it seems like OpenGL doesn't have check implemented to check if the Steam Overlay is active, while the Software with Hardware Display does.

**Comment by karst** [comment]
I'm using opengl indeed
