### ISSUE TITLE
Roller Coaster brakes

### ISSUE THREAD

**Issue by Rybread0912** [OpenRCT2/OpenRCT2#17818]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.4.1-186-g3750052 (3750052 on develop) provided by GitHub

### Describe the issue

Cant decrease or increase roller coaster brake speed.

### Area(s) with issue?

The bug also exists in RCT2 (vanilla)

### Steps to reproduce

 Build roller coaster track (any type) 
Under special track: "brakes"
Unable to increase or decrease brake speed

**Comment by drocca1992** [comment]
I have the same issue. Just started today, Saturday August 13, 2022.

**Comment by lalip** [comment]
appears to be introduced by 49215a5
