### ISSUE TITLE
Ride name shows up in place of "Special..." dropdown menu on ride construction window

### ISSUE THREAD

**Issue by SpartanFrederic104** [OpenRCT2/OpenRCT2#17815]
### Operating System

Windows 11 Home, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.1-185-g53f7a20 (53f7a20 on develop) provided by GitHub

### Describe the issue

When building any tracked/tower ride (except for the Maze), the ride's name will show up in place of "Special..." in the ride construction window. In the screenshot below, "Flying Roller Coaster 1" shows up instead of "Special..." or any selected special track element while I was building the flying coaster.
![Fred's Workbench 2022-08-13 17-01-27](https://user-images.githubusercontent.com/61885939/184517249-c01acb4f-6180-47c8-a4b0-f5d0c9f33eb7.png)

### Steps to reproduce

1. Start construction of any tracked/tower ride type
2. Place down the station anywhere on the map
3. You will notice the ride's name where the special track element dropdown menu is, replacing "Special..."

**Comment by Gymnasiast** [comment]
Oh, that’s annoying, I must have overlooked this while working on https://github.com/OpenRCT2/OpenRCT2/pull/17805.
