### ISSUE TITLE
Can't build this here, invalid height! When placing flat rides on multiplayer

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#17829]
### Operating System

Windows 11 Pro

### OpenRCT2 build

OpenRCT2, v0.4.1-189-g354df90 (354df90 on develop) provided by GitHub

### Describe the issue

When building flat rides on flat ground next to path in multiplayer, it says "cannot build here invalid height" then it causes network desyncs and disconnects, and blocks placing other flat rides in same location, to demonstrate here is a twitch vod : https://www.twitch.tv/videos/1562149730   fast forward to the last half hour of the vod

### Area(s) with issue?

This bug is specific to multiplayer

### Steps to reproduce

play multiplayer, try to place a lot of flat rides, it will say "can't build this here, invalid height" and cause network desyncs and disconnects

**Comment by Gymnasiast** [comment]
This error message pops up when you use the cheat for building at invalid heights. Please don’t enable cheats if you don’t know what they do.
