### ISSUE TITLE
Unexplained Catastrophic System Failure when alt tabbing game

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#17825]
### Operating System

Windows 11 Pro

### OpenRCT2 build

OpenRCT2, v0.4.1-189-g354df90 (354df90 on develop) provided by GitHub

### Describe the issue

Was Playing a park I have been working on for months, I pressed alt tab in game and my entire windows system suddenly froze and I had to force my computer to power off. I was in game and had tile inspector open but was not clicking on anything, no in game actions. Also audio was glitching from OpenRCT2, and I turned my monitor off and it would not come back on. No crash log was generated

### Steps to reproduce

I don't know how you would reproduce this bug

**Comment by tupaschoal** [comment]
Honestly it is hard to tell whether this was even an openrct2 failure or a system failure

**Comment by ocalhoun6** [comment]
In theory, the OS should be able to survive anything OpenRCT2 does without the entire OS crashing.

But given that it's Windows 11 ... who knows?

**Comment by 733737** [comment]
it happened right when I pressed alt tab in the game

**Comment by ocalhoun6** [comment]
Can you get it to happen again by alt tabbing?

**Comment by karst** [comment]
What graphics card and cpu are you using?

**Comment by Broxzier** [comment]
Sounds like a graphics card failure. Perhaps it became too hot? Try enabling v-sync if you haven't already.

**Comment by 733737** [comment]
I have determined the issue is with my OS and not OpenRCT2
