### ISSUE TITLE
PARKOBJ file doesn't want to be recognized, even when following the tutorial.

### ISSUE THREAD

**Issue by randomsomeone69** [OpenRCT2/OpenRCT2#17846]
### Operating System

Windows Vista SP2 x64

### OpenRCT2 build

OpenRCT2, v0.4.1 (be518f4) provided by GitHub

### Describe the issue

When I add the PARKOBJ file on the object folder, it doesn't work.

### Steps to reproduce

1: convert a file to WAV, OGG and/or FLAC. 
2: put it in a zip file with the options.json
3: reaname the exten of the file with parkobj, then drag it into the object folder
4: start the game

**Comment by IntelOrca** [comment]
> 2: put it in a zip file with the options.json

It should be `object.json`

Please upload the object so we can see what the problem is.

**Comment by randomsomeone69** [comment]
[Clément.music.2-09 Nokonoko Theme (mkart).zip](https://github.com/OpenRCT2/OpenRCT2/files/9358976/Clement.music.2-09.Nokonoko.Theme.mkart.zip)

Hers's one of the objects that I've tried to get into the game.

**Comment by Gymnasiast** [comment]
Your JSON is not valid. It’s missing both the starting `{` of the structure, as well as the closing `}` of the `name` object.

**Comment by Gymnasiast** [comment]
Here is a fixed version. Make sure to remove the `.zip` postfix and you should be able to use it.

[clement.music.nokonoko_theme.parkobj.zip](https://github.com/OpenRCT2/OpenRCT2/files/9366004/clement.music.nokonoko_theme.parkobj.zip)

**Comment by randomsomeone69** [comment]
It works! Thanks you!
