### ISSUE TITLE
Can't reopen any park files.

### ISSUE THREAD

**Issue by Corporalcretin95** [OpenRCT2/OpenRCT2#17840]
I can't reopen any previously saved games, come up with error message "Main executable for openrct2 has stopped working" and then closes the game.

**Comment by James103** [comment]
Can you please post the output from `openrct2 --version`?

**Comment by Kuhnovic** [comment]
Please include one or more files that you can't open so we can try to reproduce the issue

**Comment by Broxzier** [comment]
Use the bug issue form to file bug reports. We're lacking a lot of useful information now.

**Comment by Broxzier** [comment]
Closing this, as OP still hasn't responded.
