### ISSUE TITLE
Items in Invention List sometimes end up in the wrong place after moving

### ISSUE THREAD

**Issue by lalip** [OpenRCT2/OpenRCT2#17854]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.1-198-g4fcdafc (4fcdafc on develop) provided by GitHub

### Describe the issue

As mentioned in #17836

In the invention list window:
- Dragging an item to a higher position in its list: results are as expected.
- Tapping the top half of an item: nothing changes, as expected.
- Tapping the bottom half of an item: **it swaps places with the item below**
- Dragging an item to a lower position in its list: **it ends up one place lower than expected**
- Dragging an item across to the other list: results are as expected.

### Steps to reproduce

1. Open the scenario editor, advance to Invention List Set Up
2. Move items to various places, including dropping them where they already are
3. Observe whether the above list holds

### Attachments

![gif](https://user-images.githubusercontent.com/25644992/185287381-eaf3c056-2e1e-46b7-bccc-0c7b627a7661.gif)

PS. you can also see #17853 in the above attachment

**Comment by Broxzier** [comment]
Why did you file this as two separate issues?

**Comment by lalip** [comment]
This one has to do with items ending up in a location other than what the hand and horizontal bar suggest under certain conditions, which sounds to me more like a logic bug than a graphical one. The other issue is a purely visual one in the text that's being dragged around.
I think I should have picked a different item for the gif too.

**Comment by beam41** [comment]
I think I can fix this, I will work on it.

**Comment by Broxzier** [comment]
Sure thing @beam41

**Comment by raacker** [comment]
Ooops, I think I had to mention that I was working on this

**Comment by beam41** [comment]
Oh, can I see the commit. I will close it for you if it better.

**Comment by raacker** [comment]
@beam41 I'm very sorry about that! I better ask maintainers to get assigned. 

Yeah I've been trying to find the actual problem around it and I had some fixes with your approach but basically beforeItem gets mutated after removing item from the both lists.

**Comment by beam41** [comment]
Ok, I close mine now. @raacker

**Comment by beam41** [comment]
My fixes I not that good any way lol, I test your code and it work perfectly :)

**Comment by raacker** [comment]
@beam41 lol thank you though. I should've get assign on this issue first before hopping into
