### ISSUE TITLE
Invention name tears while being dragged

### ISSUE THREAD

**Issue by lalip** [OpenRCT2/OpenRCT2#17853]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.1-198-g4fcdafc (4fcdafc on develop) provided by GitHub

### Describe the issue

As mentioned in #17836

In the invention list window, while dragging an item with a vehicle type, the name of the vehicle will tear and leave a chunk of it behind. It appears as though there's a bounding box for drawing purposes that's snapping horizontally to some kind of grid, and potentially isn't long enough to cover all of its text.
Once it hovers past the middle of another item, the entire window gets redrawn, thus clearing the artifacts.

Occasionally it will display just fine, no clue why.

Items that aren't split by vehicle type are unaffected.

### Steps to reproduce

1. Open the scenario editor, advance to Invention List Set Up
3. Find an item that specifies a vehicle type and drag it around

### Attachments

![gif](https://user-images.githubusercontent.com/25644992/185285900-ab61de91-f3c4-4b9b-bde6-d27c6e49da4e.gif)

**Comment by duncanspumpkin** [comment]
Most likely the window for the invention drag is the wrong size

**Comment by raacker** [comment]
Hi! I was just hopping into this issue to fix and already found the exact problem.

DragWindow invalidates only when the Cursor is on the exact invention item. Which means DragWindow does not redraw if the mouse cursor is in between each items. 

I just wanted to double check it is okay to redraw the window every tick(I'm sure it's fine!). If it is, will create a PR :)

![1](https://user-images.githubusercontent.com/12020398/193752979-261aa018-6f59-4e6f-8e6e-a2377c2eb470.gif)

Just a one question about related issue with this. It seems like Window's pick up starting position feels jumpy depends on item's text size and where I click. Mostly, if I click the end of the item, it just move the whole window to the end.  For me the natural behavior would be set the start position where the cursor clicked. What do you guys think?

![2](https://user-images.githubusercontent.com/12020398/193753670-27bba247-e2a5-434a-8cf3-bf635bed30f9.gif)

**Comment by tupaschoal** [comment]
> I just wanted to double check it is okay to redraw the window every tick(I'm sure it's fine!). If it is, will create a PR :)

It sounds ok.

> What do you guys think?

I think less "jumpy" would be better too

**Comment by raacker** [comment]
@tupaschoal Thanks for the input.

About the jumpy problem, do you think it is better be a separate issue?

**Comment by tupaschoal** [comment]
I do

**Comment by raacker** [comment]
Sure, creating one now using the gif I captured.
