### ISSUE TITLE
Generic/Path scenery tab missing

### ISSUE THREAD

**Issue by austinjb555** [OpenRCT2/OpenRCT2#1786]
I was using 1061, but went to the latest build 1127, and went back. I noticed this at 1127 and when I downgraded back to 1061 it was still missing. Is this a bug or did I change a setting on accident? There isn't a tab for the path scenery, like benches, trash bins, etc.
![scr14](https://cloud.githubusercontent.com/assets/12687508/9284269/71d1abee-42a8-11e5-9fc6-6660ef61952e.png)

**Comment by IntelOrca** [comment]
Could you upload the saved game with this issue?

**Comment by austinjb555** [comment]
http://www.filedropper.com/sixflagshavefun

**Comment by IntelOrca** [comment]
Saved game no longer available.
