### ISSUE TITLE
Wrong Soft Guest Cap at start of new game

### ISSUE THREAD

**Issue by Sadret** [OpenRCT2/OpenRCT2#17866]
Issue originally described here:
https://github.com/Sadret/openrct2-soft-guest-cap-calculator/issues/4#issuecomment-1181201315

> For the soft guest cap being wrong when you start a new scenario:
> 
> 1. Create a new scenario in the scenario editor
> 2. Start a new game in that newly created scenario
> 3. If done correctly the soft guest count notification should be wrong despite no rides or stalls being present in the park
> 
> I can reproduce this in both the current v0.4.1 release and the v0.4.1-154-g980e3cb ([OpenRCT2/OpenRCT2@980e3cb](https://github.com/OpenRCT2/OpenRCT2/commit/980e3cbc4ce5834036d1c9b03fe81765b0ca0e1b) on develop) builds.

I can reproduce this behaviour. The API reports the wrong value for roughly one day, then calculates the correct one. So the problem is not with the plugin, but with the actual SGC. (Build: https://github.com/OpenRCT2/OpenRCT2/commit/564a902b5fb0d79814c7adc1b4c12ac2d4ae6728)

**Comment by Sadret** [comment]
Possibly similar to https://github.com/OpenRCT2/OpenRCT2/issues/12775

**Comment by duncanspumpkin** [comment]
Again why is this a mistake. This is just an internal value unless you are saying it differs from vanilla there is no issue here.

**Comment by Sadret** [comment]
This is clearly a mistake because the API reports a positive SGC while it should clearly be zero, as there are no rides or stalls present.

**Comment by duncanspumpkin** [comment]
This is because the global variable isn't generated until ~13 seconds into the game. So it will just output garbage. Should probably init it to zero.
