### ISSUE TITLE
Being unable to launch the game after swpping my CPU.

### ISSUE THREAD

**Issue by randomsomeone69** [OpenRCT2/OpenRCT2#17861]
### Operating System

Windows Vista SP2

### OpenRCT2 build

OpenRCT2, v0.4.1 (be518f4) provided by GitHub

### Describe the issue

When I wanted to continue my savefile on my Windows Vista VM, the game crashed instantly. 

If you thing this is a joke, this isn't.

### Steps to reproduce

1. Play the game with an older Intel CPU. (example : Intel Core i5 2320)
2. Swap with an newer CPU. (example: Intel Core i5 10400F)
3. Start the VM and launch the game.

**Comment by James103** [comment]
1. What host OS are you running?
2. Does this occur with the latest develop version? If so, can you please upload/attach the resulting crash files if any?
3. What other changes did you make to your system, besides swapping the CPU?
4. Does the problem persist when restoring the system to its previous configuration with the 2nd gen CPU?

**Comment by Broxzier** [comment]
The little support for Windows Vista that we had was dropped recently. Either use an old version that worked, or use an OS that isn't outdated.
