### ISSUE TITLE
Wrong Calculation of Soft Guest Cap

### ISSUE THREAD

**Issue by Sadret** [OpenRCT2/OpenRCT2#17865]
Issue originally described here:
https://github.com/Sadret/openrct2-soft-guest-cap-calculator/issues/4#issuecomment-1180908639

> Reproduction Steps for the varying reported soft guest caps when harder guest generation is enabled:
> 
> - Start a new game of Alpine Adventures. The chairlift you start with contributes 55 to the soft guest count.
> - Increase your loan to $20,000 and build the Woodchip wooden coaster prebuild in the park.
> - Put Woodchip in Test Mode. After the stats are done calculating, a notification is sent saying the soft guest count is 265.
> - Open Woodchip. You should receive a notification saying the soft guest count is 370.
> 
> I am able to reproduce this bug in both the current OpenRCT2 release (V0.4.1) and the latest develop build the OpenRCT2 installer gave me at the time of me writing this post.

I ran the scenario as described in the issue, but without opening the coaster. API reported SGC of 265. I then fast forwarded and easily reached 265 guests with no ads. So the problem is not with the plugin, but with the actual SGC. (Build: 564a902)

**Comment by Sadret** [comment]
`Park::CalculateSuggestedMaxGuests` does not check for the ride to be opened in the difficult guest generation loop.

**Comment by duncanspumpkin** [comment]
What makes you think this is a mistake?

**Comment by Sadret** [comment]
tbh I wasn't sure but why should closed rides increase the SGC?

**Comment by duncanspumpkin** [comment]
![image](https://user-images.githubusercontent.com/1277401/185765534-be94e5a1-00af-4af1-a2f9-bad47ba048dc.png)
looks like it was a mistake in our implementation. Status is at offset 0x49. Second loop is meant to also check for only open.

**Comment by Sadret** [comment]
There is a todo `CalculateSuggestedMaxGuests`
https://github.com/OpenRCT2/OpenRCT2/blob/0bfc151ab9b8dd39b077b96505c895c55d88a09e/src/openrct2/world/Park.cpp#L552
Is it okay if I do the refactoring together with the fix of the issue?
