### ISSUE TITLE
Bug: Browsing list of tracked rides occasionally initiates game-breaking bug [VIDEO INCLUDED]

### ISSUE THREAD

**Issue by UTNerd24** [OpenRCT2/OpenRCT2#1788]
https://www.youtube.com/watch?v=V_yHqicILb0
Note my number of saved designs.

This bug is somewhat of a Priority, as It can break a majority of gameplay.

Sometimes, when you are browsing tracked rides, the number of saved designs gets locked on a certain number and all displays of saved designs are blank.

From there, starting a new game will crash the game.
I don't know exactly what causes it, but fixing it will greatly stabilize the project's performance.

Best of luck!

**Comment by duncanspumpkin** [comment]
Is this happening still?

**Comment by Gymnasiast** [comment]
Might have been solved with #2441.

**Comment by duncanspumpkin** [comment]
@Gymnasiast seriously doubt that. I think it will be caused by overrunning a buffer. I think we can redo the the track list and it will probably fix it

**Comment by Gymnasiast** [comment]
Is this still happening?

**Comment by UTNerd24** [comment]
Nope. Its been long fixed
