### ISSUE TITLE
Game crashed - told to manually post crash dump files here

### ISSUE THREAD

**Issue by woofa6** [OpenRCT2/OpenRCT2#17891]
### Operating System

Windows 11. 64 bit operating system

### OpenRCT2 build

OpenRCT2, v0.4.1-215-g09253f0 (09253f0 on develop) provided by GitHub

### Describe the issue

Was simply playing on one of my saved games, and while building a dueling wooden roller coaster, the game crashed. Received an error message telling me to manually post the crash dump file on GitHub.

(I am not able to upload all the crash dump files as their file types are not supported)

### Steps to reproduce

Have been unable to trigger the crash again, I was building a dueling wooden coaster and the game suddenly crashed.
![Uploading Screenshot (7).png…]()

### Attachments

[552c8cf7-ed9c-4f41-82bb-57c1548dd2fc(09253f0_x86-64).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/9417096/552c8cf7-ed9c-4f41-82bb-57c1548dd2fc.09253f0_x86-64.dmp.gz)

**Comment by James103** [comment]
1. Can you please re-upload the screenshot? It looks like the original upload didn't complete.
2. Can you please ZIP all of the crash files and upload the resulting ZIP here? If the ZIP is too big (25 MB or more), you may need to upload to an external service and post a link to the file.

**Comment by janisozaur** [comment]
Uploaded as #17894

**Comment by Broxzier** [comment]
Closing this as the crash report is closed now. If this still happens, please reopen this issue and provide additional information.
