### ISSUE TITLE
guests recoil from tile edge on path OUTSIDE park, unable to leave or enter

### ISSUE THREAD

**Issue by cheweytoo** [OpenRCT2/OpenRCT2#17897]
### Operating System

Ubuntu Linux 20.04.04

### OpenRCT2 build

develop 83e4277

### Describe the issue

See attached park (not a zip, just renamed to attach), it is kind of a minimal case: Guests leaving cannot leave the map, guests arriving don't enter the park.

They behave as if encountering a "no entry" sign on the edge of the tile in both directions.

The issue does NOT occur with exactly the same savegame file in 0.4.1 release. I have first noticed the issue in 83e4277, but am not sure how far back it goes.

I have not been able to reproduce this behaviour "from scratch".

### Steps to reproduce

1. open attached park
2. watch guests stuck right outside the entrance/not coming in

### Attachments

[no_one_enters_no_one_leaves.park.zip](https://github.com/OpenRCT2/OpenRCT2/files/9425934/no_one_enters_no_one_leaves.park.zip)

**Comment by cheweytoo** [comment]
short screen recording:

https://user-images.githubusercontent.com/29800630/186707561-9093244b-1260-4c98-a2f4-8b7ef1a3ca57.mp4

**Comment by Gymnasiast** [comment]
When I load that file, it works without issue. Do you have any plugins installed? If so, please uninstall them (temporarily) and see if the issue persists.

**Comment by cheweytoo** [comment]
Oooh, I forgot about the plugins, sorry.

I renamed the plugin directory (and verified none of the plugins' menus show up in the UI): No change, my guests still recoil.

I just went through some of the older dev builds:

Issue already exists in 3e378e9, f9bb5b2, 6aabe38 and adc51ad (49215a5 and older from https://openrct2.org/downloads/develop fail to launch). Is there a way to get to even older dev builds? I'd be happy to do additional bisecting.

**Comment by karst** [comment]
the park wont open for me, and the video wont load either. But I am curious if it is the same issue I ran into. I don't know if this is the case. If you have a path that goes up by two units in a location that has construction rights it counts as park property. I originally had that issue here. 
![image](https://user-images.githubusercontent.com/1516893/186792108-b409556c-74bf-4992-a8a3-f3f9610c838f.png)

**Comment by lalip** [comment]
It's one of the scenarios from vanilla RCT2, so I imagine it's not the same issue.

The video wouldn't play for me either for some reason, so I messed about with ffmpeg until it did:
https://user-images.githubusercontent.com/25644992/186797351-61adbf1b-f7e1-4fa9-be2d-e6f9e45c2241.mp4

@cheweytoo you can get them from the Actions tab in this repository; here's a shortcut to [only those from the develop branch](https://github.com/OpenRCT2/OpenRCT2/actions/workflows/ci.yml?query=branch%3Adevelop). If you want one from a specific commit you can get there through the ✔️ or ❌ beside its title, too. In pull requests they show up as _checks_.

**Comment by Gymnasiast** [comment]
@karst The ".zip" is not a zip (even though my archiver happily extracted _something_ from it), you need to change the extension to .park.

**Comment by cheweytoo** [comment]
> @cheweytoo you can get them from the Actions tab in this repository; here's a shortcut to [only those from the develop branch](https://github.com/OpenRCT2/OpenRCT2/actions/workflows/ci.yml?query=branch%3Adevelop).

Ah, thank you! I'm going through them right now.

**Comment by karst** [comment]
> @karst The ".zip" is not a zip (even though my archiver happily extracted _something_ from it), you need to change the extension to .park.

Oh i see, yea it works then, there was a .park file inside which was confusing me.


The issue is Indeed that this tile 
![image](https://user-images.githubusercontent.com/1516893/186998325-a620842f-29c7-46f1-a867-37a9fc2c9da1.png)
has construction rights owned. You need to remove that and then the peeps can leave just fine.

[![Image from Gyazo](https://i.gyazo.com/93550c0472e34e62abeb6954af700c2e.gif)](https://gyazo.com/93550c0472e34e62abeb6954af700c2e)

**Comment by cheweytoo** [comment]
Found it :-)

Last good: 7399163
First bad: 43bc0b0

**Comment by lalip** [comment]
Well, I guess all the above works out then! There's a change in the first bad build that stands out to me. Commit f0777e5 wasn't supposed to change behaviour, right?

```diff
- loc.z - LAND_HEIGHT_STEP >  surfaceElement->GetBaseZ()
+ loc.z                    >= surfaceElement->GetBaseZ() + ConstructionRightsClearanceSmall
```

Note:

- `LAND_HEIGHT_STEP` = 16
- `ConstructionRightsClearanceSmall` = 3
- `ConstructionRightsClearanceBig` = 24

If `loc.z - surfaceElement->GetBaseZ()` is guaranteed to be a multiple of 8 I assume the latter was supposed to be used here

Now... would this be the actual cause, or does it only expose a corner case? I just reproduced this with the "own all land" cheat which I imagine OP also used; the end result does not change with which build I do it with. I'm curious as to why it's specifically that tile, too.

**Comment by cheweytoo** [comment]
That was quick, thank you!

**Comment by Gymnasiast** [comment]
You’re welcome, it was a lot easier since you did the bisecting and lalip pointed out the mistake. ;-)
