### ISSUE TITLE
Instant desync after loading a map

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#1789]
https://drive.google.com/file/d/0B2_12DbzmFxYZ2F2b0VtRDVyekU/view?usp=sharing

The video shows everything. (Please ignore the crash, it's because i used the mini game to launch OpenRCT2 in the VM.)

**Comment by IntelOrca** [comment]
Multiplayer is not ready yet for this very reason.

**Comment by daihakken** [comment]
fixed by 9746bcc
