### ISSUE TITLE
Peep keeps walking stuck in midair

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#17890]
### Operating System

Windows 11 Pro

### OpenRCT2 build

OpenRCT2, v0.4.1-214-g8ae01be (8ae01be on develop) provided by GitHub

### Describe the issue

Peep at some point trapped walking indefinitely in midair

### Steps to reproduce

Uncertain

### Attachments

[walkingpeepgithub.zip](https://github.com/OpenRCT2/OpenRCT2/files/9412842/walkingpeepgithub.zip)
![Gun 2022-08-24 00-32-23](https://user-images.githubusercontent.com/94884086/186329979-70bd16b2-e348-45e9-b4ea-c23ce394f445.png)

**Comment by Broxzier** [comment]
I guess there was a peep spawn at that position before. There may have not been a path, causing them to be floating right there, and now the tile he's on is owned. If you place a path under him, and make the tile unowned, he will walk again.

![image](https://user-images.githubusercontent.com/9705046/233860342-0bda7719-38d1-4eb6-a210-fd612c545b60.png)

**Comment by Broxzier** [comment]
Since this is not something you can normally trigger without using tools that are not available during normal gameplay (sandbox mode, changing land ownership while there are guests), I'm inclined to just close this issue.
