### ISSUE TITLE
[Feature Request]RCT2:MG Support

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#1790]
Right now, the RCT2:Mini Game(RCT2:MG, the demo from Infogrames) can launch OpenRCT2 successfully with some missing objects messages (after fc844b5 only).
![image](https://cloud.githubusercontent.com/assets/13048125/9289051/407f0e22-4395-11e5-99da-407bc0ed2e3f.png)
However, the scenarios bundled with RCT2:MG will not open at all, showing:
```
ERROR[..\src\scenario.c:117 (scenario_load)]: failed to load scenario, invalid checksum
```

Removing the checksum (*which is a bad idea?*), or adding an exception to RCT2:MG will solve the problem, and people can enjoy OpenRCT2 for free, like corsixTH.

Edit: the scenarios doesn't work @ vanilla game either.

**Comment by medsouz** [comment]
Maybe we could add a check to see if RCT2:MG is running and if it is disable the checksum?

**Comment by Gymnasiast** [comment]
OpenRCT2 does not need or use RCT2.EXE. It contains its own modified version of it.
Anyway, I'll look into this issue soon. Not sure yet what the best course of action is though.

**Comment by Gymnasiast** [comment]
As it seems, the Mini Game scenarios are essentially damaged. I think I'll introduce an option (off by default) to allow loading of damaged saves/scenarios.

**Comment by daihakken** [comment]
@Gymnasiast I think it is modified by purpose, some essential objects were taken out in the Mini Game.

**Comment by Gymnasiast** [comment]
@daihakken : Which ones?

**Comment by daihakken** [comment]
I loaded "Electric FIelds", and 4x4 is missing.

**Comment by duncanspumpkin** [comment]
I expect the checksum generation and checking is different for the mini game. Probably to prevent people from using it to play the full game for free.

**Comment by Superjustinbros** [comment]
This is exactly what I get in my copy of Open RCT2. It's super-annoying since there appears to be no way to fix it (as it's not good with telling you what files/scenarios are broken).

**Comment by Gymnasiast** [comment]
Haven't you bothered to read this issue properly? This is about the mini game having (deliberately) incorrect checksums. Broken or missing objects are another thing entirely.
Also, there is a pull request to allow loading with incorrect checksums.
