### ISSUE TITLE
miniature railway cars' gray line turns invisible when steam puffing

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#17901]
### Operating System

Windows 11 Pro

### OpenRCT2 build

OpenRCT2, v0.4.1-216-g83e4277 (83e4277 on develop) provided by GitHub

### Describe the issue

During the smoke puffing animation frames, the gray line disappears from the american style steam trains
[Githubtrainbug.zip](https://github.com/OpenRCT2/OpenRCT2/files/9429509/Githubtrainbug.zip)

### Area(s) with issue?

The bug also exists in RCT2 (vanilla)

### Steps to reproduce

build american style steam train vehicle miniature railway track and open the ride
![Github Park 2022-08-25 23-17-31](https://user-images.githubusercontent.com/94884086/186810759-8867d8c5-22b8-4976-a83b-2ab498b57ee1.png)

**Comment by spacek531** [comment]
The rain changes the palette. There also are not spokes on the train wheels?

**Comment by 733737** [comment]
doesn't need rain to occur, occurs when it's sunny. It's called a "bogie"

**Comment by spacek531** [comment]
I study and collect trains. I know them very well. I don't know what you are trying to call a bogie.
