### ISSUE TITLE
Vertical land textures not showing.

### ISSUE THREAD

**Issue by Drunkllama92** [OpenRCT2/OpenRCT2#17912]
### Operating System

Mac 

### OpenRCT2 build

OpenRCT2, v0.4.1 (26825a7 on develop)

### Describe the issue

Some vertical land pieces are not showing in my game anymore.  I've made plenty of parks using custom vertical land pieces but now the only walls that are loading are Dirt, Ice, Black Wood, and Red Wood.  Not sure exactly when the others stopped appearing.

### Steps to reproduce

I can still see the other types of vertical land in object selector but when I go to use them in game they appear as dirt.

**Comment by Broxzier** [comment]
Is your RCT1 installation still linked in the options menu? Dirt is the fallback type for players without RCT1 installed.

**Comment by Gymnasiast** [comment]
That has to be it. The four sides that are still working are the ones from RCT2, the rest are all from RCT1.

**Comment by Drunkllama92** [comment]
That must be it. I don't have a rct 1 game linked to it. Only rct2. Strange that it worked before and stopped working now.
