### ISSUE TITLE
Paths with non-ascii characters fail.

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#1791]
Someone reported the game not being able to write the config file due to their user name containing a unicode character. I thought I catered for this when switching to UTF-8, but obviously not.

**Comment by Gymnasiast** [comment]
Has this been fixed by https://github.com/OpenRCT2/OpenRCT2/commit/bea74ee261420f12e0cf1254e22e55f3d2a94c32 ?

**Comment by IntelOrca** [comment]
I think so, I have had confirmation from Reddit.
