### ISSUE TITLE
Getting this message when I try to open a saved park

### ISSUE THREAD

**Issue by brslowey** [OpenRCT2/OpenRCT2#17953]
### Operating System

Windows 11

### OpenRCT2 build

OpenRCT2 v0.4.1-260-g6268197 (6268197 on develop)

### Describe the issue

Trying to open this saved game from a custom scenario but keep getting this message. Also can't start a new scenario from said custom scenario.

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

Try opening the park

### Attachments

![IMG_2304](https://user-images.githubusercontent.com/70527216/188256913-a4cab57c-9b7c-4265-8b25-b87389ecec49.jpg)
[github.txt](https://github.com/OpenRCT2/OpenRCT2/files/9481840/github.txt)

**Comment by James103** [comment]
Do you have the crash files (especially the dump and save)? If so, can you please post them here?

**Comment by Gymnasiast** [comment]
Closing as the dumps have not been uploaded.
