### ISSUE TITLE
command-line(s), not working? portable, not working?

### ISSUE THREAD

**Issue by eladkarako** [OpenRCT2/OpenRCT2#17956]
### Operating System

w10 x64

### OpenRCT2 build

provided in description.

### Describe the issue

https://github.com/OpenRCT2/OpenRCT2/blob/e1c2a8b74f7b997aab41e16b12129019e4f2432c/src/openrct2/cmdline/RootCommands.cpp#L65-L85

tries some such as --h -h --help -h (version, user-data-path, ...)  

doesn't seems to do anything,  
is there any command-line support?

also,  
I'm using OpenRCT2-0.4.1-windows-portable-x64.zip

from https://github.com/OpenRCT2/OpenRCT2/releases/tag/v0.4.1

but it still writes every data into the documents folder,  
I've tried moving it to the same folder as the exe,  
I've tried the command line switch for the data folders,  
and it just ignores it and re-create the data folder in the documents again.  

is this a bug or not..?  

also,  
is there a more stable version you know to be working properly  

### Steps to reproduce

provided above.

**Comment by eladkarako** [comment]
went back up to 3.5, no command line switches reaction at all

**Comment by janisozaur** [comment]
Works just fine for me using wine:
```
$ WINEPREFIX=~/wine64 WINEARCH=win64 wine openrct2.com --version
OpenRCT2, v0.4.1 (be518f4) provided by GitHub
Windows (x86-64)
Network version: 0.4.1-0
Plugin API version: 57
Current park file version: 13
Minimum park file version: 12
```

**Comment by Broxzier** [comment]
Works fine on Windows 10 x64 too.

```
PS C:\Users\Me\Documents\OpenRCT2\bin> .\openrct2.com --version
OpenRCT2, v0.4.1-258-gb6ceb1a (b6ceb1a on develop) provided by GitHub
Windows (x86-64)
Network version: 0.4.1-11
Plugin API version: 58
Current park file version: 14
Minimum park file version: 14
With breakpad support enabled
```

Make sure to use the openrct2.com file for stdout, otherwise you simply won't see any output.

**Comment by eladkarako** [comment]
oh I see, you are using `.com`,  
well that explains  

https://user-images.githubusercontent.com/415238/188288205-62361571-c9a4-4a69-885a-f8c0fdc2f54d.mp4

and now that I come to check the subsystem,  
<img width="365" alt="2022-09-04_003043" src="https://user-images.githubusercontent.com/415238/188288282-24569241-728c-4f65-9b38-ea9a79386eb3.png">

I can see that it isn't set to be console,  
meaning the OS won't assign a pipe to it.  

so it makes sense that it won't show anything,  
but should I also use the `.com` with arguments?

why wouldn't the exe be able to launch (w/o a console, that's fine!)  
using the data switches? normal exe shouldn't have issue accepting argument,  
it doesn't require a console.. (try running notepad with a text file as an argument).

does it means I need to use the `.com` to launch the game every-time I want to use argument with it?  

`.com` files are so unappealing (at least for me),  
it immediately reminds me of Win3.11 16 bit applications,  
and the fact that `.com` applications were 64KB limited,  

they are still used today,  
commonly for trojans you get along with t0rrents...

so I automatically ignore those.  

<hr/>

I think I'll just change the subsystem of `openrct2.exe`  
using `editbin.exe /NOLOGO "/SUBSYSTEM:CONSOLE" "openrct2.exe"`  
and deal with the additional console window.  

<hr/>

<img width="917" alt="2022-09-04_004702" src="https://user-images.githubusercontent.com/415238/188288605-bd1a7295-3e57-45f0-9395-55b7ca34d4c9.png">

exe as console sub system works fine,  
I did discover a little not-related bug I think..  

```txt
Importing legacy shortcuts...
ERROR[D:\a\OpenRCT2\OpenRCT2\src\openrct2\Context.cpp:350 (OpenRCT2::Context::Initialise)]: Failed to open configured language: id was undefined
openrct2 $
```

but for me its all good..

<hr/>


if there isn't any plan on allowing arguments using with the `exe` as well,  
you can mark this issue as invalid or wontfix and close it.

thanks for the information.

**Comment by IntelOrca** [comment]
@eladkarako .COM is just an extension. The reason we use it, is because it has higher precedence than .EXE by default (see `%PATHEXT%`) when you invoke `openrct2` on the command line.

`.\openrct2 --version` will therefore work.

**Comment by lalip** [comment]
To add to the above, the sole difference between both files in terms of content is the subsystem itself. As far as I can tell, at least:
```
C:\Users\ale\Documents\OpenRCT2\bin\openrct2>fc /b openrct2.exe openrct2.com
Comparing files openrct2.exe and OPENRCT2.COM
00000170: 5F 60
00000174: 02 03
```

**Comment by eladkarako** [comment]
you are not mistaken about the execution order.

you can just keep it subsystem console, build one exe,  
and if an argument `--show-console` (for example) hasn't provided,  
you hide the console windows afterwards,  
using `GetConsoleWindow` (`kernel32`) and `ShowWindow` with `SW_HIDE` (`user32`).

or build a dynamic lib with most (15MB) of the logic and assets,  
and two 100kb exe, one `openrtc.exe` and once `openrtcw.exe`,  
that is the norm, and a better practice (think "java.exe and javaw.exe")  

it will also cut your upload weight in half,  
and prevent redundant copy of 15MB file just for the sake of sub-system.
