### ISSUE TITLE
TTF support for Korean and Cyrillic needed.

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#1795]
A Korean translation is already in the game files, and a Russian translation is being prepared. OpenRCT2 will need TTF support for it.

**Comment by IntelOrca** [comment]
What do you mean by TTF support?

**Comment by Gymnasiast** [comment]
Well, you added support for Traditional and Simplified Chinese by specifying TTFs to use. As Korean and  Russian don't use the Latin alphabet, I reckoned support should be added in the same way.

**Comment by IntelOrca** [comment]
Yes you add font definitions which say which font to use for each size and what point size and offset adjustments. But I don't know which font is best for a particular language.

**Comment by daihakken** [comment]
@telk5093 Please suggest a Korean font for language support in-game :-P

**Comment by telk5093** [comment]
@daihakken gulim.ttc may be suitable. This font, named 'Gulim' is used since RCT1 and 2.

**Comment by telk5093** [comment]
I found it from "language.c".
Maybe this will be great, but I'm not sure what each numbers means.
I think the first columns are sizes, but others are unknown for me.

static TTFFontSetDescriptor TTFFontGulim = {{
	{ "gulim.ttc",		9,		-1,		-3,		6,		NULL },
	{ "gulim.ttc",		11,		1,		-1,		14,		NULL },
	{ "gulim.ttc",		12,		1,		-2,		14,		NULL },
	{ "gulim.ttc",		13,		1,		0,		20,		NULL },
}};

**Comment by IntelOrca** [comment]
@Gymnasiast Do you want to PR this language descriptor and enable Korean?
I think you will need to currently use ENGLISH_UK for object files as I am unable to workout what codepage RCT2 uses for Korean. Might just be better to leave it as English until I add the support for object string translation.

Russian can also be added even though the strings aren't complete yet.

**Comment by Gymnasiast** [comment]
Yes. I'll ask the Russian contributor to suggest a TTF font to use for Russian.

**Comment by Gymnasiast** [comment]
I got an answer: Arial will work, as will Times New Roman. I think Arial will be easier to read, and it's in every Windows version from 3.1.

**Comment by IntelOrca** [comment]
I would go for Arial as its sans-serif.

**Comment by Gymnasiast** [comment]
I don't think this issue should be closed yet, as we haven't added support for Russian yet.

**Comment by IntelOrca** [comment]
I thought you were adding Arial?

**Comment by Gymnasiast** [comment]
... I though you were O_o

Anyway, I'll try, but I haven't had much success in adding or testing font definitions.

**Comment by IntelOrca** [comment]
It should be very easy to do, particularly for you... PM me if you have any issues.
