### ISSUE TITLE
Launcher doesn't start dev-version

### ISSUE THREAD

**Issue by DarkestOfAll** [OpenRCT2/OpenRCT2#17951]
### Operating System

Win 10, 64 bit

### OpenRCT2 build

Launcher vers. 0.0.7 x64 

### Describe the issue

The launcher doesn't load the game as dev-version is selected. Only loads release. Play button stays geryed out.

### Area(s) with issue?

Building the game

### Steps to reproduce

1. Start the launcher w dev-version selected (or switch to dev in the options)
2. See the result.

**Comment by Broxzier** [comment]
The launcher is not officially part of this project. The launcher you use has had this problem for years, and it depends on the builds getting pushed to openrct2.org (not official either).

You can try to use this launcher instead, which downloads the builds directly from GitHub: https://github.com/IntelOrca/OpenLauncher
