### ISSUE TITLE
[UTF-8/Unicode] letters other than a-z and extended Cyrillic (ó) are shown as "?", bug? or by design? 

### ISSUE THREAD

**Issue by eladkarako** [OpenRCT2/OpenRCT2#17957]
### Operating System

w10

### OpenRCT2 build

0.4.1 (2022-07-04)

### Describe the issue

trying to enter anything than English characters just shows `?` instead.  

is there a way to mod the font (or bitmap for characters) used in the game?  
I was trying to enter a currency symbol that isn't present,  
some Japanese, Arabic, Hebrew, and Chinese (copying from Google translate).  

<hr/>

note:  

I've also successfully patched the exe with a manifest that has codepage explicitly set to UTF-8, but it made no difference.  

is there any use of fonts at all or is it a bitmap with some characters mapping like in actual old dos games?

<hr/>

just for reference.  

(I especially recommend the GDI variation for those whom get tiny UI in large screens).  
 
[0.4.1_2022-07-04_patched_with_various_manifest_variations.zip](https://github.com/OpenRCT2/OpenRCT2/files/9483184/0.4.1_2022-07-04_patched_with_various_manifest_variations.zip)

<img  src="https://user-images.githubusercontent.com/415238/188283865-ea5b179a-137a-46e5-a5e6-4c44b1f690bc.png">

### Steps to reproduce

- use AutoHotKey to send Unicode key.  
- copy characters from Google translate in other languages.  
- add keyboard in Windows.

all shown as `?`

### Attachments

<img width="270" alt="2022-09-03_214114" src="https://user-images.githubusercontent.com/415238/188284066-cc64f1ac-2c17-4467-9797-45d3dfcc8906.png">

**Comment by ocalhoun6** [comment]
OpenRCT2 _should_ already have support for almost any language's characters:
![rctbug2 png c65e705101a71ac3f8d282bd6c3cba53](https://user-images.githubusercontent.com/26573303/188287127-451ba9b0-a0ed-4782-96b9-4fbbff1a4bb8.png)
The question is: why isn't it working for your installation of it?

**Comment by eladkarako** [comment]
I'm entering it in the "free text" input box under custom currency.  
might be related?

I've tried 3 most recent releases,  
all "portable win64 zip",  
might this be related?  

or there might be a difference with multi-language view  
in a label, which might be read and stored in a wide char Unicode,  
and the variable that stores the value for an input box..
?

or a Window thing..

I'm out of guesses..

**Comment by Gymnasiast** [comment]
There are tens of thousands of possible glyphs, our sprite font can’t possibly carry them all.

For scripts other than Latin or Cyrillic, we use TTF fonts. These will only be used if you select a language that uses them, though.

**Comment by eladkarako** [comment]
I see,  
so sprite as base, 
and ttf as fallback.  

so it won't be possible to enter Japanese (for example) characters,  
until I'll change the entire UI to Japanese?  
..which will trigger loading up some ttf files
(have I understood it correctly?)

may I control which ttf-fonts will be used?  
or perhaps may I pre-load ttf-files such as the massive Unicode Arial,  
or Noto fonts?

<hr/>

and since I prefer English UI,  
may I work-around it by adding locally a Japanese translation that is basically a copy of English, but will still trigger loading of Japanese ttf files,  
is there an entry in the txt language file for that?
