### ISSUE TITLE
console shows 'ERROR[D:\a\OpenRCT2\OpenRCT2\src\openrct2\Context.cpp:350 (OpenRCT2::Context::Initialise)]: Failed to open configured language: id was undefined'

### ISSUE THREAD

**Issue by eladkarako** [OpenRCT2/OpenRCT2#17960]
### Operating System

Windows 10 amd64

### OpenRCT2 build

OpenRCT2, v0.4.1 (be518f4) provided by GitHub

### Describe the issue

console shows:  

```txt
Importing legacy shortcuts...
ERROR[D:\a\OpenRCT2\OpenRCT2\src\openrct2\Context.cpp:350 (OpenRCT2::Context::Initialise)]: Failed to open configured language: id was undefined
```

when running `.com` .  

game runs fine (English UI, defaults) though,  
and end with exit code 0.

not sure to what it is related but it might be the cause to some language issues.  

<hr/>

to be clear,  
I'm not running the game from D:\,  
nor I have the Documents or anything in that path.  

I have no idea why this path is written in the output.  

### Steps to reproduce

(specified above)

### Attachments

(none)

**Comment by IntelOrca** [comment]
We have had some people hit this before, and we haven't managed to figure out why yet.

The path that is written out is just the source code path which is useful for developers to track where the error is logged.

**Comment by eladkarako** [comment]
thanks, I'll reopen it if I'll manage to find out more information.

**Comment by dd123-a** [comment]
Has the problem been resolved
