### ISSUE TITLE
Sprites don't show up on two sides of the view-clip selection

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#17964]
### Operating System

Windows 10, 64 bit, build 19044

### OpenRCT2 build

OpenRCT2, v0.4.1-273-g8709b78 (8709b78 on develop) provided by GitHub

### Describe the issue

Most noticeable when selecting just one tile where lots of guests walk.

### Steps to reproduce

1. Have a park with lots of guests
2. Open view-clipping
3. Select an area, some of the corners cutting through it
4. Notice how guests that are within the selection still disappear when they are on two of the edge tiles of the selection

### Attachments

All 4 tiles in this screenshot have guests on them, yet only one tile shows guests:

![RC F_ Magic Kingdom 2022-09-04 17-16-10](https://user-images.githubusercontent.com/9705046/188320853-b3c39723-1e29-4699-aadf-76f70012152a.png)

**Comment by kevinochoa8266** [comment]
This is my first open-source contribution. How can I help?

**Comment by Broxzier** [comment]
Check out the project, compile it locally, and then find out where entities get clipped. The globals `gClipSelectionA` and `gClipSelectionB` are used for horizontal clipping, and likely used in the drawing function for entities checks them, but that logic is not correct. Or perhaps it's so that the `gClipSelectionA`/`B` value itself is not set correctly. Try to find out what the exact cause is first.

**Comment by ebstalk** [comment]
Is this issue still open if so can I submit my fix?
