### ISSUE TITLE
Marketing campaigns can't be started after Finance window tab has been on Research

### ISSUE THREAD

**Issue by rik-smeets** [OpenRCT2/OpenRCT2#17963]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.1 (latest build from develop branch)

### Describe the issue

After the 'Research' tab has been opened in the finance window, some marketing campaigns can't be started anymore. 

### Steps to reproduce

1. Start a new campaign with marketing campaigns available, for example RCT2's Gravity Gardens.
2. Open the Finance window and go to the _Marketing_ tab. 
    - Note that all campaign buttons are clickable: the 'start new campaign' detail window will open as expected.
4. Switch to the _Research_ tab.
5. Go back to the _Marketing_ tab.
6. Try to start all campaigns. Note that some campaign buttons can't be clicked.

I noticed that the window's `Mouse` events aren't triggered at all anymore when pressing these buttons.

**Comment by stai1** [comment]
I tried reproducing this and found a bit more information with some more steps.

1. Follow the steps to reproduce for Gravity Gardens and observe that only "Vouchers for free entry to the park" and "Advertising campaign for the park" are clickable. Note that in the research tab, "Roller Coasters" can be toggled, and it at approximately the same location as "Advertising campaign for the park" in the window.
2. With cheats enabled, open Inventions list and move all coasters to the top.
3. Do steps 2-5 in the issue description again and observe that "Roller Coasters" can't be toggled (no more to research) and "Advertising campaign for the park" can no longer be clicked.

I'm guessing that whether the research item can be clicked determines whether the campaign at the same location can be clicked.

**Comment by Broxzier** [comment]
Probably the disabled widgets are not set correctly when switching between tabs. The research tab has a few checkboxes that are inactive since there is no research, and this overrides the state of the marketing tab once opened.

Somewhat related: The group boxes in the marketing and research tabs are interactable. When clicking on them, you hear the clicking sound.
