### ISSUE TITLE
Queue lines of prebuilt designs mess up existing queue lines if dragged through them.

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#17980]
### Operating System

Windows 10 64 bit

### OpenRCT2 build

90b6cdb

### Describe the issue

When building a saved design that includes a queue line, the game doesn't check if another queue line is already in the place of the queue line of the design being placed:
![image](https://user-images.githubusercontent.com/25930360/188648617-a934f11f-faea-4121-8a60-7a149c563837.png)

I know not too long ago a change has been made so that you that normal path in saved designs can be built through existing normal path, but the same should not be true for queue lines, as there is almost never a reason to overlap them.

In addition, the existing queue lines that the ghost queue is dragged through get all messed up and disconnected, see this video:
https://www.youtube.com/watch?v=A8j2r2OBdtI

### Steps to reproduce

Build a ride with a queue line
Drag the queue line of a saved design through it

**Comment by IntelOrca** [comment]
This would cause desync issues too

**Comment by Gymnasiast** [comment]
Could you add this track design?

**Comment by LordMarcel** [comment]
Sorry for the late response. Here is the track file.

[Monorail 1.zip](https://github.com/OpenRCT2/OpenRCT2/files/9570143/Monorail.1.zip)
