### ISSUE TITLE
Building on Arch Linux requires more packages

### ISSUE THREAD

**Issue by rockybulwinkle** [OpenRCT2/OpenRCT2#17993]
On a fresh pacstrap'd chroot, I need to install more packages than listed here for Arch Linux: https://github.com/OpenRCT2/OpenRCT2/wiki/Building-OpenRCT2-on-Linux

I needed to install, in addition to the ones listed, cmake, ninja, flac, and libvorbis.

Sorry for not using a template, none of the ones provided addressed an issue with building.

**Comment by janisozaur** [comment]
Just update the wiki

**Comment by Gymnasiast** [comment]
It’s not a matter of “just” updating the wiki - there is also the openrct2.io and openrct2.org sites that need an update.

**Comment by Krutonium** [comment]
Isn't `cmake` at least part of `base-devel`?

**Comment by Gymnasiast** [comment]
Updated the wiki. Contrary to what I said earlier, this info is only on the wiki.

**Comment by rockybulwinkle** [comment]
> Isn't `cmake` at least part of `base-devel`?

Nope, see: https://archlinux.org/groups/x86_64/base-devel/

**Comment by rockybulwinkle** [comment]
It still requires base-devel. I retried with a freshly pacstrapped root with only base+the packages listed and it fails.

Technically gcc and gcc-libs are included directly in base-devel. ICU is included indirectly (base->gettext->libxml2->icu), but probably better explicit than implicit when the dependencies are that deep.

I'd suggest the package/group list to be: base-devel sdl2 curl nlohmann-json speexdsp fontconfig libpng openssl libzip icu cmake ninja flac libvorbis

I've gone ahead and updated it with that list.

It says in the wiki that this is tested continuously with a dockerfile. Do we need to update that as well? I don't see where the docker for building in arch is defined.

**Comment by janisozaur** [comment]
The dockerfile used to be part of this repo, then I think it was moved to https://github.com/OpenRCT2/openrct2-docker-build and then dropped. We have no arch builds currently in CI. Feel free to remove that info from wiki
