### ISSUE TITLE
Virginia Reel doesn't show sloped tracks (construction)

### ISSUE THREAD

**Issue by Manticore-007** [OpenRCT2/OpenRCT2#17992]
### Operating System

Windows 10 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.1-304-g4f0f660 (4f0f660 on develop)

### Describe the issue

The construction menu of the Virginia Reel doesn't show the sloped track pieces.

### Steps to reproduce

1. Open construction on new Virigina Reel
2. No sloped pieces available

### Attachments

![Virginia Reel construction sloped pieces](https://user-images.githubusercontent.com/71702374/189211266-6f505977-94ae-4e4c-b0d4-1f1b5795e6a0.png)

**Comment by Manticore-007** [comment]
It also applies to the river rapids, another member told me

**Comment by spacek531** [comment]
River rapids and virginia reel rides do not have their sprite groups filled out because they use custom paint code. This causes issues with @Gymnasiast's recent PR

**Comment by jensj12** [comment]
Issue is not fixed, but made worse (for both Virginia Reel and River Rapids):
![image](https://user-images.githubusercontent.com/13868449/189490462-1ff74368-4e3f-4d0e-bfcd-ec09934273e0.png)
Can't build anything other than station pieces and rapids.
Game version ce95b58.

**Comment by Manticore-007** [comment]
on OpenRCT2, v0.4.1-305-gce95b58 (ce95b58 on develop) it works for me

![image](https://user-images.githubusercontent.com/71702374/189490776-56040436-3334-47d9-83b3-cd209326c83c.png)

**Comment by jensj12** [comment]
I've reported the issue here because someone on the forums had this issue (and I verified on my machine): https://forums.openrct2.org/topic/6051-cant-build-river-rapids/
I can build all pieces if I allow building all drawable track pieces.

**Comment by Manticore-007** [comment]
Ah, that is correct. If I turn it off, I have the same issue!

**Comment by jensj12** [comment]
Issue also seems to occur on the chair lift: https://forums.openrct2.org/topic/6052-chairlift-unable-to-build-updown-slope/

**Comment by spacek531** [comment]
Bobsled coaster can't build banked turns either

**Comment by Broxzier** [comment]
#18012 did not fix the banked turns issue.

**Comment by ocalhoun6** [comment]
Still experiencing this issue on the chairlift.
