### ISSUE TITLE
River rapids vehicles glitch/sprites get cut off

### ISSUE THREAD

**Issue by Basssiiie** [OpenRCT2/OpenRCT2#18007]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.1-305-gce95b58 (ce95b58 on develop) provided by GitHub

### Describe the issue

In the latest develop the rapid river vehicles glitch out and their sprites seem to be cut off in columns, which is especially noticeable if one vehicle goes down a slope (moving fast across the screen).

- It also happens to the expansion variants of the river rapids vehicles.
- It happens in both OpenGL and Software Renderer.

### Steps to reproduce

1. Place down a river rapids ride.
2. Test or open it.
3. Watch the vehicle sprites glitch.

### Attachments

https://user-images.githubusercontent.com/20048660/189524195-ab3b337a-df71-4ad8-acb9-23ae97eaa85e.mp4

**Comment by karst** [comment]
Can you check if #17316 fixes this?

**Comment by Basssiiie** [comment]
@karst I can confirm builds from #17316 do not have this bug. The PR seems older, is it rebased recently to ensure this is not a very recently introduced issue?

**Comment by karst** [comment]
I have just updated it for you. Can you try again?

**Comment by karst** [comment]
I just tested and it's not related to eachother (my pr fixes track errors while this issue is related to vehicles). 
It's probably caused by the same issue that makes the river rapids and virginia reel's slopes, as this issue is also present on the Virginia Reel. 
Oddly enough this does not break existing rides.

**Comment by karst** [comment]
Introduced by #17994
