### ISSUE TITLE
Verticulator roller coaster

### ISSUE THREAD

**Issue by Disneyworld7502** [OpenRCT2/OpenRCT2#18015]
### Operating System

Windows 10. 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.0 (c6302a1 on master) provided by GitHub

### Describe the issue

When you place the ride it automatically has 8 cars per train. But when the ride starts with that it wont complete a lap because the train is too long. it will crash into another train. The coaster will work correctly if you shorten the train to 4 cars per train. 

### Area(s) with issue?

The bug also exists in RCT2 (vanilla)

### Steps to reproduce

1. Open up any park.
2. Click on Hyper Twist Coaster
3. Build preset of Verticulator
4. Then click on the train tab(second from the right) and you will see the trains are set to 8 cars per train when they need to be 4.

### Attachments

[](url)

**Comment by SpartanFrederic104** [comment]
That only happens if you use the six-seater trains. If you use the regular four-seater wide trains, the ride works perfectly at 8/9 cars per train.

**Comment by Gymnasiast** [comment]
I checked it and this is indeed the result of falling back to a different train, which the game does warn you about.
