### ISSUE TITLE
"Deja Vu" bug makes game unplayable

### ISSUE THREAD

**Issue by medsouz** [OpenRCT2/OpenRCT2#1802]
>> Hi, I've been trying to do the Alcatraz scenario twice now and I'm a stickler for detail. I got the park looking all nice, but when I click on the Inverted Vertical Shuttle, then exit out without building anything, all of the pre-made rollercoasters in the menus are named "Deja Vu", the preview is invisible, there are no stats and the rides are unplaceable. The first time this happened it reverted both the autosave and my manual save to September Year 1 even though I was well into Year 3 at that point. Anyone else have this issue?

[Source](https://openrct.net/forum/topic/150/last/deja-vu-bug-makes-game-unplayable)

**Comment by IntelOrca** [comment]
Can anyone reproduce this?

**Comment by Patrik356b** [comment]
I tried to but can't get anything like this...

> It's mentioned it could be caused by character support:
> Could be the OpenRCT2's lack of non-ASCII character support is screwing around with every string that comes after Deja Vu and then some game coding as a side-effect?

**Comment by daihakken** [comment]
Tested on 0.0.4 (stable), and I can't reproduce this one.
