### ISSUE TITLE
Confused error message: "Park is v14 and requires at least v14"

### ISSUE THREAD

**Issue by cheweytoo** [OpenRCT2/OpenRCT2#18024]
### Operating System

Ubuntu Linux 20.04.5

### OpenRCT2 build

OpenRCT2 0.4.1 release, AppImage

### Describe the issue

Trying to check the issue from #18023 with its attached park in 0.4.1 release results in a slightly confused and confusing error message complaining that 14 is not at least 14:
![14vs14](https://user-images.githubusercontent.com/29800630/190030121-9e072933-4b57-490f-9518-1401c5202b6a.png)
```
Error: Incompatible Park Version
This park was saved in a later version of OpenRCT2.
Park is v14 and requires at least v14.
```

### Steps to reproduce

- Try to open park from #18023 in 0.4.1 release
- get error message

**Comment by IntelOrca** [comment]
Yeah it isn't worded well. It is basically saying that you need a game that supports a minimum park version of v14.

**Comment by cheweytoo** [comment]
Ooooh. _\*cough\*_, I've consistently read it wrong the whole time, as "you have v14, but need v14". I don't know how I managed to do that, sorry.

Still, isn't the current wording pretty redundant then? Are there actual cases where those numbers can be different, so that a park is v<N>, but only requires v<N-x> to run?

It would probably still be useful to add "…but you only have v<Y>." or something like that, but I'm hereby withdrawing this as an actual bug report. Feel free to close it.

**Comment by Broxzier** [comment]
Yes, some changes are perfectly backwards-compatible, so then an older version of the game can load newer .park file versions.

It would indeed make more sense to show the minimum version needed and the maximum version the current build can open.

> Error: Incompatible Park Version
> This park was saved in a later version of OpenRCT2. Support for Park at least v321 is needed. Your current versions can open parks up to v123.

**Comment by goodspark** [comment]
Running into this as well.
The latest release is 0.4.1 and the --version output says it supports up to v13. How does v14 exist and how can I load a save game with that format?

**Comment by karst** [comment]
are you on the latest development build?

**Comment by cheweytoo** [comment]
It's the version of the current devolpement builds: https://openrct2.org/downloads/develop/latest

**Comment by goodspark** [comment]
Ah OK. Thanks!
