### ISSUE TITLE
Favorited servers don't get their online status updated.

### ISSUE THREAD

**Issue by jvgoch** [OpenRCT2/OpenRCT2#18035]
### Operating System

Windows 11

### OpenRCT2 build

OpenRCT2, v0.4.1-310-ga1be5de (a1be5de on develop) provided by GitHub

### Describe the issue

When you add a server to your favorites the online status is not updated/shown when fetching servers. So information like network version, online status and the amount of online players is missing.
The screenshot below shows the top of my Server List with a newly favorited server and the fetched version below it. I tried this with multiple servers and got the same result.
![image](https://user-images.githubusercontent.com/78982569/190672294-9d62cff2-bbe5-484a-babc-7afbd1048558.png)

### Area(s) with issue?

This bug is specific to multiplayer

### Steps to reproduce

1. Add server to favorites
2. Click "Fetch Servers" or close and reopen server menu
3. No online status shown

**Comment by beam41** [comment]
@Broxzier I manage to fix this issue, can I work on this?

The image below I favorited Deurklink server.
![image](https://user-images.githubusercontent.com/1791353/190904319-64cfe531-1883-4557-b226-1dfc9c0015ff.png)

**Comment by Broxzier** [comment]
@beam41 Of course, please create a pull request with your fix.
