### ISSUE TITLE
Plugin: width and height of custom window not changeable via script

### ISSUE THREAD

**Issue by Sadret** [OpenRCT2/OpenRCT2#18059]
Problem: A custom window that is not resizable by the user (by dragging the bottom right corner), is also not resizable by the script. Attempting to change the `width` and `height` properties has no effect.

Note: If the window is resizable, everything works as expected.

Cause: When opening a custom window, there are optional parameters `minHeight` and `maxHeight`. If they are specified, the window will be resizable. Otherwise, those values will internally be set to whatever `height` is. In this case, when the window's height is changed by the script, it will be trimmed to fit into the range `[minHeight, maxHeight]`, i.e. the attempted change has no effect. Same for `width`.

Solution: If the window is not resizable, `minHeight` and `maxHeight` should either be adjusted or ignored.

Build: OpenRCT2, v0.4.1-312-gd263464 (d263464 on develop)

**Comment by IntelOrca** [comment]
I think this is the same for internal code as well. Any non-resizable window must have both the min/max and current size changed for it to work.
