### ISSUE TITLE
Underground entrance shows through terrain walls. 

### ISSUE THREAD

**Issue by Snaid1** [OpenRCT2/OpenRCT2#18069]
When building a ride entrance underground and the terrain is raised just to fit the entrance, the entrance becomes visible through the terrain vertical faces. I am on the latest Development build as of writing this.

![image](https://user-images.githubusercontent.com/23465479/191533868-3713557b-c969-45a9-b5ab-9d648aa06166.png)
![image](https://user-images.githubusercontent.com/23465479/191533939-670b5637-f2c2-452f-a2f5-bad76ebc42cc.png)
![image](https://user-images.githubusercontent.com/23465479/191534362-13272602-d3e3-4bfc-be24-c83c0c337e21.png)
![image](https://user-images.githubusercontent.com/23465479/191534432-213583d5-4eca-41c2-9147-952922b3cb20.png)

Steps to Reproduce:
- Build a station
- raise terrain where you want to build the entrance
- build entrance
- see issue

**Comment by Gymnasiast** [comment]
Please use the provided bug report template, it’s there for a good reason.

**Comment by Snaid1** [comment]
I apologize. I didn't know there was a bug report template and didn't notice the "report a bug on github" menu option before. I will close this and reopen it using the template.

**Comment by Snaid1** [comment]
reopened using proper bug report template https://github.com/OpenRCT2/OpenRCT2/issues/18070
