### ISSUE TITLE
Persistent object filter from Scenario Editor

### ISSUE THREAD

**Issue by Robaa** [OpenRCT2/OpenRCT2#1806]
Applying a filter in the Object Selection window of the Scenario Editor (e.g. pick only Wacky Worlds objects), causes the same filter to be applied in the Roller Coaster Designer and Track Designs Manager.
Solution: reset the filter when the Scenario Edtior closes?

**Comment by IntelOrca** [comment]
This filter is saved in the config and persistent on purpose.
