### ISSUE TITLE
Buggy

### ISSUE THREAD

**Issue by kspears013** [OpenRCT2/OpenRCT2#18075]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.4.1-312-gd263464 (d263464 on develop) provided by GitHub

### Describe the issue

I keep having issues with the signs and scrolling popping up in random places and unable to be removed. When I try to remove or click on one, it either crashes the game or doesn't respond at all.

### Steps to reproduce

1. right click on banner
2. game crashes

**Comment by Gymnasiast** [comment]
Please upload an affected save, and change the bug report title to something more descriptive.

**Comment by Gymnasiast** [comment]
Closing as the necessary data has not been provided in 3 months.
