### ISSUE TITLE
Underground entrance/exit shows through terrain walls.

### ISSUE THREAD

**Issue by Snaid1** [OpenRCT2/OpenRCT2#18070]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.1-318-g8d08c13 (8d08c13 on develop) provided by GitHub

### Describe the issue

When building a ride entrance underground and the terrain is raised just to fit the entrance, the entrance becomes visible through the terrain vertical faces. I am on the latest Development build as of writing this.

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Build a station
2. Raise terrain where you want to build the entrance
3. Build entrance
4. see issue

### Attachments

![image](https://user-images.githubusercontent.com/23465479/191560666-0683c6f0-ea31-48e2-aa85-9df4548419bd.png)
![image](https://user-images.githubusercontent.com/23465479/191560683-b0e1c597-49c5-45b2-9ab1-fd18819278b3.png)
![image](https://user-images.githubusercontent.com/23465479/191560699-cdeb4566-0906-4b74-9467-56e1c412dd38.png)
![image](https://user-images.githubusercontent.com/23465479/191560727-76b56034-5269-4971-8e70-efe88a366fa0.png)

**Comment by karst** [comment]
Same goes for toilets and some stalls i believe
