### ISSUE TITLE
invisible paths for RCT2 scenarios

### ISSUE THREAD

**Issue by eaglesnation** [OpenRCT2/OpenRCT2#18079]
### Operating System

windows

### OpenRCT2 build

OpenRCT2, v0.4.1-9-g55b97bf (55b97bf on develop) provided by GitHub

### Describe the issue

all rct2 sceanrios have invisible pathways.. how can i fix this

### Steps to reproduce

1. open any rct2 sceanrios and bam invisible pathways
2. other sceanrios whether they are custom or rct1(packs) are fine and showing the pathway

**Comment by Gymnasiast** [comment]
You most likely have a broken RCT2 install. I would try reinstalling it. Also make sure that the RCT2 .DAT files are only in ObjData - do not add them to `Documents\OpenRCT2\object`.
