### ISSUE TITLE
Feature: List of useful features/enhancements for future releases

### ISSUE THREAD

**Issue by UTNerd24** [OpenRCT2/OpenRCT2#1808]
I hope this is allowed, but I have recently thought of a number of features and enhancements that could highly benefit OpenRCT2.

~~Park Inspector/Park Critic: When a new game is started, he spawns in front of the park entrance. He will ride untested rides and upon getting off, he will broadcast the test results of said ride via the alert box in the bottom middle. He will also broadcast if a vandal is present, he will tell the player with a message along the lines of "[GUEST NAME] Is causing property damage!"~~

Classic Trains: Allow the use of Rollercoaster Tycoon Deluxe trains as a type of car. Most likely for custom scenarios. Example: The Steel Train, the one with the black triangle at the front.

Anti-Crash Physics: Rollercoasters such as the Side Friction Coaster and Bobsled will not fly off the track when going over a sharp climb, and will no crash from taking turns too quickly. Should that be Debug or Cheat?

~~Track Merging: Ability to combine tracks to form one Rollercoaster. The alternative could be to make a RCT2 version of RCT3's Extended Coaster.~~

Guest Control: Might be good for Multiplayer. When checked, The selected guest can be moved with WASD.

Objective Warnings: When the date of your objective is getting close, a notification will appear. EG: "In 1 month's/week's time, your objective will be evaluated."

Thats all I have for now. I hope some of these will be taken into consideration. I love Rollercoaster Tycoon, and I want to do my best to contribute.
Thank you!

**Comment by Gymnasiast** [comment]
I dislike that park inspector idea. It's one of the more annoying things in RCT3, and not that useful either. Also, the idea of RCT1 and RCT2 is that the player should be keeping an eye on things themselves. That's also why I dislike objective warnings.

**Comment by daihakken** [comment]
I remember that classic trains, track merging are in the long term plan. And I agree to @Gymnasiast about the Park Inspector&Warnings, which are very intrusive.

**Comment by UTNerd24** [comment]
Yeah... In Hindsight, the Inspector and warnings are kinda a bad idea. The challenge of RCT2 is really not knowing exactly how long you have been playing.

**Comment by Phasedetect** [comment]
I like the idea of disabling crash physics as a debug for things like dinghy slides and slide friction coasters.

**Comment by Patrik356b** [comment]
Classic trains. *wants*

**Comment by Superjustinbros** [comment]
I am not in support of a park inspector either. Though the task of identifying a vandal is on the loose to the player would be a semi-decent idea if it was incorporated into the task of a security guard. Plus disabling crashes for coaster "trains" that realistically wouldn't explode in reality.
And by "classic trains", it'd be better if the classic trains for a ride were selectable in the ride management windows, with the classic designs always available for selection if the default car design is available.

**Comment by Gymnasiast** [comment]
When a security guard walks past a peep with the 'vandal' flag, it will remove that flag. That's why they are present in RCT.

**Comment by Gymnasiast** [comment]
There is a separate issue for the Classic Trains. The other features haven’t really gotten much traction. They may be proposed again, but we want to keep the bug tracker a bit tidy.
