### ISSUE TITLE
stalls cloned via tile inspector copy&paste are a single stall instance internally, have one merged set of stats

### ISSUE THREAD

**Issue by cheweytoo** [OpenRCT2/OpenRCT2#18092]
### Operating System

Ubuntu Linux 20.04.5

### OpenRCT2 build

6c6ea16 develop, AppImage

### Describe the issue

Building many of one type of stall is way faster using the tile inspector's copy&paste.

This however leads to one logical stall sharing all pasted locations:
- Clicking on any of the stalls opens the same stats window
- One set of stats is shared by all stalls
- There is only a single stall in the rides list

![multistall](https://user-images.githubusercontent.com/29800630/192118298-9e9da052-b88a-4841-878f-13f53027f54d.png)

The stalls all work as expected serving customers.

### Steps to reproduce

- Use tile inspector to clone stall via copy&past
- All those stalls will be the same specific stall instance internally

Park containing examples attached.
[cloned_stalls_share_stats.zip](https://github.com/OpenRCT2/OpenRCT2/files/9639557/cloned_stalls_share_stats.zip)

**Comment by Gymnasiast** [comment]
This is not a bug, it’s literally what you told it to do.

**Comment by cheweytoo** [comment]
Oh, ok then. I thought I remembered a similar issue where not assigning an individual instance was considered wrong.

From a user's perpective, this point could be made here as well though: I expected to _copy_ a stall, not "hardlink" it. Pretty much like the copy&paste paradigm works usually.

**Comment by ocalhoun6** [comment]
Sometimes you _want_ it to be hardlinked, though.

A) If you're in a park with near the maximum number of rides, you can cheat a bit by copying stalls like this, that way you only need one of each stall, which frees up more ride slots for actual rides. (Not as much of an issue in NSF, but still.)

B) Hardlinking ride station pieces like this allows you to synchronize two ride stations, regardless of their positions in the park, which you couldn't otherwise do. 'Fixing' this issue would make it impossible to do that anymore.

**Comment by Gymnasiast** [comment]
> Oh, ok then. I thought I remembered a similar issue where not assigning an individual instance was considered wrong.
> 
> From a user's perpective, this point could be made here as well though: I expected to _copy_ a stall, not "hardlink" it. Pretty much like the copy&paste paradigm works usually.

For a regular copy and paste or blueprint function, yes, but not for the Tile Inspector. You’re copying and pasting tile elements here, which get copied with all their data. The Tile Inspector is also a tool that is hidden by default for a good reason.
