### ISSUE TITLE
Extras Category for New Game doesn't work when sorting by difficulty

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#18108]
### Operating System

Windows 11 Pro

### OpenRCT2 build

OpenRCT2, v0.4.1-356-g61d74ea (61d74ea on develop) provided by GitHub

### Describe the issue

https://github.com/OpenRCT2/OpenRCT2/commit/a3b7ac5a90847af664eb760e6086004a29b1b73e doesn't work when scenarios are sorted by difficulty

<img width="1919" alt="2022-09-26 (1)" src="https://user-images.githubusercontent.com/94884086/192191852-ba953aeb-c82a-4a21-b0a6-1f7916d8cfda.png">

### Steps to reproduce

Try to start a new game with scenarios sorted by difficulty

**Comment by Gymnasiast** [comment]
Sorting by difficulty isn’t used that much and it was too much effort to modify the code accordingly.
