### ISSUE TITLE
Server name in Discord rich presence include format string, makes server name super long

### ISSUE THREAD

**Issue by beam41** [OpenRCT2/OpenRCT2#18109]
### Operating System

Windows 11 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.1-350-gcf6de24 (cf6de24 on develop) provided by GitHub

### Describe the issue

This is not a bug, but an enhancement.

When you join server which use format string to spice up their server name, the discord rich presence will include those string like raw data make the server name too long to discord to display, even though server name might be short.

![image](https://user-images.githubusercontent.com/1791353/192246120-82d42d8d-d533-49b6-9fe5-e8a37e53bd6a.png)
![image](https://user-images.githubusercontent.com/1791353/192245980-67f6629f-a3f0-4823-90f3-b4e845d3c312.png)

I think I can fix this by filter out all {}. Is this method ok?

### Steps to reproduce

1. join server with formatted server name like Deurklink's server
2. Look at rich presence on discord
3. On the last line it will show the server name with {.....}

**Comment by IntelOrca** [comment]
I think there are already some helper functions to remove formatting codes from a string.

**Comment by beam41** [comment]
If you mean `FmtString::WithoutFormatTokens` it removes `{}` from escape string too (and I don't know if I can modify it, I mean it does exactly what its name is)
![image](https://user-images.githubusercontent.com/1791353/192943333-fbfa5b01-b18c-428b-9cee-80028d4705d3.png)

Anyways, I will work on this myself.
