### ISSUE TITLE
Mechanic will inspect lift/boat hire even though it cannot break down.

### ISSUE THREAD

**Issue by beam41** [OpenRCT2/OpenRCT2#18121]
### Operating System

Windows 11 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.1-361-ga8073f6 (a8073f6 on develop) provided by GitHub

### Describe the issue

In original rct2 and openrct2 mechanic does ignore the ride that cannot break down like crooked house.

However, they still inspect lift and boat hire (rowing boats, swans, and canoes boat hire cannot break).

![Screenshot (1)](https://user-images.githubusercontent.com/1791353/192594102-5ecf3eb4-8063-4b98-ac06-0141dc58a0d7.png)
In original rct2

![Screenshot 2022-09-28 000411](https://user-images.githubusercontent.com/1791353/192594169-c8cb77ac-5e3d-4793-a782-508d4b27a939.png)
In openrct2

I suspect that because lift and boat hire have breakdown type, the mechanic will inspect them, but they do not check if the ride can actually break.

### Area(s) with issue?

The bug also exists in RCT2 (vanilla)

### Steps to reproduce

1. has a park with enough mechanic to inspect all ride and unbreakable ride with lift and boat hire (rowing boats, swans, and canoes)
2. Run the park for very long time
3. check the ride that cannot break ([Marcel has video for them](https://youtu.be/fdvb175KQZM?t=108))
4. All unbreakable ride will have very high time since last inspection, except lift and boat hire which has time within inspection range.

### Attachments

My park use in testing
[Testbreak.zip](https://github.com/OpenRCT2/OpenRCT2/files/9658476/Testbreak.zip)

**Comment by Gymnasiast** [comment]
The lift can most certainly break down, and so can Boat Hire, although only if it’s using motorised boats (Bumper Boats, Jet Skis).

**Comment by beam41** [comment]
@Gymnasiast and I think that means we have to check if we have to check if ride need inspection base on vehicle type, but it might not worth fixing, I understand why you close.

I never seen lift break without cheat tho.

**Comment by Gymnasiast** [comment]
I did some digging and found this out: while the Lift ride can break down, its vehicle, for a reason I don’t understand, set a flag that prevents them.

I can’t say I understand it, seems like an error to me.

**Comment by beam41** [comment]
[As Marcel said in his video.](https://www.youtube.com/watch?v=fdvb175KQZM&t=178s) If it can breakdown, we need mechanic at the top if path not connects to the below, but he also points out it might be a bug.

Maybe Chris Sawyer make lift breakdown like other ride first, then realized that the problem could happen. So he decided to kinda band aid fix by set flag to never break.

**Comment by beam41** [comment]
I change the check from `ride->GetRideTypeDescriptor().AvailableBreakdowns == 0` to `!ride->CanBreakDown()` and it fix the issue and work fine even when I force breakdown using cheat

![image](https://user-images.githubusercontent.com/1791353/193399659-4feb5eb9-e8df-4875-b02e-5d459ac6a7bb.png)

Should I make the pull request for this now?

**Comment by Gymnasiast** [comment]
@beam41 Yes, that seems sensible to me.

**Comment by beam41** [comment]
Ok, might set Inspection never and make it grayed out as well.
