### ISSUE TITLE
Underground on-ride photo section partially clips through adjacent terrain edge.

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#18134]
### Operating System

Ubuntu 20.04 LTS

### OpenRCT2 build

Unknown -- #12909

### Describe the issue

Basically, the screenshot explains it all:
![Forest Frontiers 2022-09-28 10-07-45](https://user-images.githubusercontent.com/26573303/192846468-8e031aff-ebeb-498d-a7b2-116829690e74.png)
The on-ride photo section of the vertical drop coaster on the right partially clips through the cliff edge it's next to.

### Steps to reproduce

1: build an on-ride photo section for a B&M track coaster underground, next to a cliff face.

**Comment by rik-smeets** [comment]
I'll pick this one up, have fixed some instances of this already and will continue working on it tomorrow.
