### ISSUE TITLE
When using show vehicles from other track types cheat, vehicle type is cut off at certain scales

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#18132]
### Operating System

Windows 11 Pro

### OpenRCT2 build

OpenRCT2, v0.4.1-365-ga0dd6a3 (a0dd6a3 on develop) provided by GitHub

### Describe the issue

<img width="1923" alt="2022-09-28 (16)" src="https://user-images.githubusercontent.com/94884086/192844079-83854611-1eaf-4073-96e1-c73c45a6147e.png">
When using only official objects with show vehicles from other track types cheat on, not all vehicles are present on screen. Proposed change: alter list so that it is taller instead of wider

### Steps to reproduce

go to change vehicle type with cheat turned on

**Comment by ocalhoun6** [comment]
This may be dependent upon your screen resolution and your scale factor. Resolution seems quite high in this case, but maybe your scale factor is a little excessive?

**Comment by jensj12** [comment]
Even when making it taller, it will still eventually run out of space (think about smaller screens and/or higher scale factor). For a proper, future-proof solution it needs to be scrollable (and maybe even searchable) (and preferably show the normally valid ones on top, but that's another discussion).
