### ISSUE TITLE
Bug: Guests feign vomiting

### ISSUE THREAD

**Issue by UTNerd24** [OpenRCT2/OpenRCT2#1815]
So recently, I've noticed my guests be sick, but not leaving any vomit behind. The result is a plague of coughing. I'm not sure if this is a graphical error or something wrong with the guests, but I would appreciate it if it was addressed.

**Comment by duncanspumpkin** [comment]
Is this when there is already a ton of vomit on the ground? There is a limit to how many sprites can be created.

**Comment by UTNerd24** [comment]
Strangely enough, no. I have plenty of Handymen applied to patrol areas. So I dunno whats causing the problem...

**Comment by duncanspumpkin** [comment]
Hmm the only thing I can think of is it running out of sprite ids. Is this only in one save, has that save been used for a long time?

**Comment by UTNerd24** [comment]
Not sure. I usually play for long periods of time. Eitherway, For all I know, my handymen might be working well.
