### ISSUE TITLE
Height marks on land do not appear

### ISSUE THREAD

**Issue by SpartanFrederic104** [OpenRCT2/OpenRCT2#18174]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.1-383-g20333c3 (20333c3 on develop) provided by GitHub

### Describe the issue

![Rollercoaster Heaven 2 2022-10-02 09-59-40](https://user-images.githubusercontent.com/61885939/193466531-9023794b-6aec-4bfe-acc7-c376a4056122.png)
Toggling height marks on land does not show height marks on land. Height marks on ride tracks and footpaths still show up like normal though.

### Steps to reproduce

1. Start a new game or load a saved game in any scenario
2. Toggle height marks on land (hotkey: 8)
3. No height marks appear on land surfaces

**Comment by Gymnasiast** [comment]
Might have been caused by one of my recent refactors.
