### ISSUE TITLE
Can't save.....

### ISSUE THREAD

**Issue by Cowscrazy** [OpenRCT2/OpenRCT2#18172]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.4.1-310-ga1be5de (a1be5de on develop) provided by GitHub

### Describe the issue

After a few 5-10 minutes of gameplay I can no longer save the game.  This is getting super frustrating and I feel like I'm being ignored on Discord about this issue.  Please tell me its not just me.  

### Steps to reproduce

All I do is play the game normally for 10-20mins  sometimes more.. sometimes less.  Time feels random

Try to save and get the error.

**Comment by karst** [comment]
Probably the same issue as #17664

**Comment by Gymnasiast** [comment]
This issue is literally at the top of issue tracker and you didn’t bother to read it. You also barely gave any information, not even a screenshot of the issue, just a vague summary. If you want us to make an effort, start by doing it yourself.

**Comment by Cowscrazy** [comment]
> This issue is literally at the top of issue tracker and you didn’t bother to read it. You also barely gave any information, not even a screenshot of the issue, just a vague summary. If you want us to make an effort, start by doing it yourself.

Wow its a wonder this place is so popular.  First time posting on this and I get chewed out.  Very welcoming community you have here.

**Comment by Gymnasiast** [comment]
TIL expecting people to put a minimal amount of effort is unwelcoming.
