### ISSUE TITLE
Can't build on the servers whit a multiplayer plug-in

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#18176]
### Operating System

Windows 11, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.1-384-g85c9746 (85c9746 on develop) provided by GitHub

### Describe the issue

so, whenever I try to build a ride, game says no. I don't know why but it happens

### Steps to reproduce

1. go in any develop FFA multiplayer server whit the said plug-in
2. try build a ride
3. the ride will not have your name on it
4. build it
5. [error] this ride doesn't belong to you and track ghost dissapear

### Attachments

![Suburban Trials 2022-10-02 17-37-55](https://user-images.githubusercontent.com/83843734/193477427-c6df7d65-ddee-4511-91e3-b26ecba255f7.png)
![Suburban Trials 2022-10-02 17-37-51](https://user-images.githubusercontent.com/83843734/193477430-705ab093-4637-4c55-80dc-9ed0c9b03dd4.png)
![Suburban Trials 2022-10-02 17-37-47](https://user-images.githubusercontent.com/83843734/193477434-a5d6c084-da5a-49b2-8acc-77ef87aa458b.png)

**Comment by Gymnasiast** [comment]
This makes no sense - **which plug-in are you even talking about**?!
Also, the game never says “no”, it shows an error message, which you have to provide.

And finally, almost every server sets new players as spectators by default and requires an admin to give you permissions.
