### ISSUE TITLE
Track preview is rotated 180 degrees

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#1817]
![scr72](https://cloud.githubusercontent.com/assets/1478678/9331797/a4aade2a-45c1-11e5-843d-f3ecdc6171a4.png)

![scr74](https://cloud.githubusercontent.com/assets/1478678/9331798/a5695ae4-45c1-11e5-859b-4442dd7663d1.png)

**Comment by duncanspumpkin** [comment]
The preview is drawn at rotation 0. Since you are viewing from rotation 2 when you place it, it will be rotated 180.

**Comment by Gymnasiast** [comment]
Does that matter? When you're placing the track, you expect it to be rotated the same way as on the preview, whether it is logical from a technical view or not.

**Comment by duncanspumpkin** [comment]
Feel free to change it in the placement code. The track preview should stay how it is but the placement could be changed

**Comment by Gymnasiast** [comment]
Yeah, that seems the best solution. I'll try to take this on myself.
