### ISSUE TITLE
notification bar

### ISSUE THREAD

**Issue by Tramcoaster** [OpenRCT2/OpenRCT2#18218]
### Operating System

Windows 10 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.2-8-g99e13e0 (99e13e0 on develop) provided by GitHub

### Describe the issue

you can't click away the notification bar.(it's annoying)

### Steps to reproduce

every notification you get in your park

### Attachments

https://user-images.githubusercontent.com/108947550/194173148-2b585e29-33fd-4fdc-a5b9-2861b5db54a7.mp4

**Comment by rik-smeets** [comment]
Duplicate of #18064.
