### ISSUE TITLE
Game keeps crashing while trying to load saved scenario. 

### ISSUE THREAD

**Issue by kspears013** [OpenRCT2/OpenRCT2#18233]
### Operating System

Windows 11 Lenovo

### OpenRCT2 build

OpenRCT2 version 4.2

### Describe the issue

Every time I work on a created scenario, save it, and go back to open it in the game's dialog menu, it crashes when I select the very game. I've Been trying all of the updates and everything and I'm not sure if this is because of the certain scenery files saved or rides being updated, but I hope this gets fixed because I don't want to keep losing my progress on these parks. Thank you!

### Area(s) with issue?

Opening game files

### Steps to reproduce

1. Click on Saved Games
2. Click on park file
3. Game crashes for some reason

### Attachments

Video files are too large, but I hope it is self-explanatory.

**Comment by James103** [comment]
Do you get any crash dumps from this? If so, can you please upload them?
Also, can you please share the park file (ZIP it first) if possible?

**Comment by kspears013** [comment]
where can i upload it where its not too large?

**Comment by James103** [comment]
Try Google Drive, Dropbox, or a similar file-hosting service.

**Comment by kspears013** [comment]
gotcha, will send in a few

**Comment by kspears013** [comment]
you guys have a gmail account?

**Comment by kspears013** [comment]
https://mail.google.com/mail/u/0?ui=2&ik=5fcb29b8aa&attid=0.1&permmsgid=msg-a:r3664567221987397186&th=183b056f7c465ada&view=att&disp=safe&realattid=f_l8xvy7o80
https://doc-0k-80-docs.googleusercontent.com/docs/securesc/c5q1pjsuedu07i7j6ghrchk9pitlkgtb/l9vs8utaecr0dl7po468u4sacan9qomr/1665110775000/03833705507784081747/03833705507784081747/14lMWHd99nlxZUOU6JLzW-cgWq3_MKOwu?e=download&authuser=0
https://doc-00-80-docs.googleusercontent.com/docs/securesc/c5q1pjsuedu07i7j6ghrchk9pitlkgtb/h9h7g7nsmo6bve7pf3ln304rpsl4josj/1665110850000/03833705507784081747/03833705507784081747/1YhN3oh11WUzM48EATKc7SIlwXkncFUAz?e=download&authuser=0
https://doc-14-80-docs.googleusercontent.com/docs/securesc/c5q1pjsuedu07i7j6ghrchk9pitlkgtb/p3kpao2oifl2rmq81dj72inliiun4a9t/1665110775000/03833705507784081747/03833705507784081747/1Y8mC84xABuqoa8aII8JB_rLft0TbCoL0?e=download&authuser=0
https://doc-04-80-docs.googleusercontent.com/docs/securesc/c5q1pjsuedu07i7j6ghrchk9pitlkgtb/629orgamqn2fubogvngdq65140fhbm35/1665110775000/03833705507784081747/03833705507784081747/1P_DiVYWhYOLbHF48s9PxdnkpHAVvN_9H?e=download&authuser=0
https://doc-14-80-docs.googleusercontent.com/docs/securesc/c5q1pjsuedu07i7j6ghrchk9pitlkgtb/nsclff24a81hvsvf881ulrl48o98j1o6/1665110775000/03833705507784081747/03833705507784081747/1Cd1s1uL4KJOyLvuF3FgTcdD6ki3gwym9?e=download&authuser=0

**Comment by Gymnasiast** [comment]
Do you get a dialog asking if you want to upload a crash report? And if so, do you click Yes?

**Comment by Gymnasiast** [comment]
Also, putting the saves into attachments on Gmail and sharing the link is not going to work I’m afraid. You can upload to Google Drive and use the Share button.

**Comment by kspears013** [comment]
I understand, and I've pressed the Yes button on there before. The game seems to be working fine now. I do appreciate your time and help. :)
