### ISSUE TITLE
Invention DragWindow's starting position is inconsistent 

### ISSUE THREAD

**Issue by raacker** [OpenRCT2/OpenRCT2#18244]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.2 - latest, 9fe568a on develop

### Describe the issue

As you can see from the below attachment, window position of the Drag is not consistent and feels unnatural.
 

### Steps to reproduce

1. Open the scenario editor and advance to Invention List Setup
2. Choose one of the item from the list and try grabbing it from different cursor positions.

### Attachments

![193753670-27bba247-e2a5-434a-8cf3-bf635bed30f9](https://user-images.githubusercontent.com/12020398/194632324-0eb5e129-ae66-4efc-9b85-ab7704407c31.gif)

**Comment by raacker** [comment]
I will try fixing it tonight.

Just a one silly question, I really couldn't generate the cool build version message from "openrct2 --version" like 

OpenRCT2, v0.4.1-198-g4fcdafc ([4fcdafc](https://github.com/OpenRCT2/OpenRCT2/commit/4fcdafc0f48e4640446843ba6d345680e41a0d52) on develop) provided by GitHub

How did you do that?! 🤔

**Comment by raacker** [comment]
@tupaschoal 

![6](https://user-images.githubusercontent.com/12020398/194695115-dbc80414-2d13-4632-8a53-ecf4d3870c01.gif)

It feels a lot more natural, I like it. But not sure it is really that necessary?

I need to pass Editor's Window position and ScrollSize to set widget pos and size properly.

**Comment by Broxzier** [comment]
@raacker The version information is set by our CI jobs, so if you use a build from GitHub, it should have the same version info. Builds that you make locally will look differently. Check out Version.cpp.

**Comment by tupaschoal** [comment]
> @tupaschoal
> 
> It feels a lot more natural, I like it. But not sure it is really that necessary?
> 
> I need to pass Editor's Window position and ScrollSize to set widget pos and size properly.

If you have the code ready, but have questions of its applicability, you can open a PR and have us discuss there.

**Comment by raacker** [comment]
@Broxzier Thanks! I will look into it. 

@tupaschoal OK, Just finished polishing and created a PR 👍
