### ISSUE TITLE
Request: Windows Unaffected by Day/Night cycle

### ISSUE THREAD

**Issue by UTNerd24** [OpenRCT2/OpenRCT2#1827]
Is it possible to prevent the Day/Night cycle from dimming in-game windows? Since the windows dim as well as everything else, it just looks like the game's gamma is being lowered-raised. Thanks!~

**Comment by IntelOrca** [comment]
its not possible

**Comment by mrtnptrs** [comment]
Also not possible when all code is decompiled?

**Comment by duncanspumpkin** [comment]
Not possible until we completely overhaul the way everything is rendered.

**Comment by IntelOrca** [comment]
When we render directly to a 32 bit surface and can selectively modify viewport sections of the screen.
