### ISSUE TITLE
Ride color selections not appearing.

### ISSUE THREAD

**Issue by Killerduck0213** [OpenRCT2/OpenRCT2#18290]
### Operating System

Windows 10 64-bit.

### OpenRCT2 build

OpenRCT2, v0.4.2-55-g6fe1987 (6fe1987 on develop) provided by GitHub

### Describe the issue

The windows for ride color selection show a black square where the selected colors should be. The selection menu still appears normally. This is happening on all rides in all parks I've tried it on. I'll attach one of my park files as well as a screenshot of my graphics settings in case that helps.
![image](https://user-images.githubusercontent.com/115522200/194998682-d967015d-114c-4684-ba4d-ba9f55076919.png)
![image](https://user-images.githubusercontent.com/115522200/194999536-919ec4d8-4569-4d6c-b293-52f3f226eb1b.png)
![image](https://user-images.githubusercontent.com/115522200/194999602-b26b28a3-3076-4aab-9533-3bc2694fdc01.png)

### Steps to reproduce

1. Open attached file.
2. Select any ride with color customization.

### Attachments

[Wycker Woods.zip](https://github.com/OpenRCT2/OpenRCT2/files/9751161/Wycker.Woods.zip)

**Comment by duncanspumpkin** [comment]
Likely image id refactor mistake
