### ISSUE TITLE
Move Translate3DTo2DWithZ from Map.h into Location.hpp

### ISSUE THREAD

**Issue by tupaschoal** [OpenRCT2/OpenRCT2#18305]
The following function is misplaced on `Map.h`. It should instead be on `Location.hpp`, if it isn't already

https://github.com/OpenRCT2/OpenRCT2/blob/406b73d9048301810f915b57cff2f0e40146a79e/src/openrct2/world/Map.h#L259
https://github.com/OpenRCT2/OpenRCT2/blob/406b73d9048301810f915b57cff2f0e40146a79e/src/openrct2/world/Map.cpp#L1826-L1836

**Comment by duncanspumpkin** [comment]
I don't think it should be in location.hpp. it should be in map but location would also be inappropriate. This is really a viewport function (which is another busy header so perhaps even there is wrong)

**Comment by karstenvanf** [comment]
Hello. I'm going to take on this issue as part of a software engineering project for a university class that I am a part of. I already read the contributing guidelines, is there anything else that I should keep in mind when working on this project?

Thank you!
