### ISSUE TITLE
Refactor window to class: GameBottomToolbar

### ISSUE THREAD

**Issue by tupaschoal** [OpenRCT2/OpenRCT2#18316]
Refers to file: https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2-ui/windows/GameBottomToolbar.cpp
See #13737 for more details on how to accomplish the task.

**Comment by qwzhaox** [comment]
I'd like to work on this!

**Comment by tupaschoal** [comment]
Sure

**Comment by qwzhaox** [comment]
Did I mess something up? I realized the format of my commit messages were wrong so I edited them, but now the pull request says I have 151 commits when I only made 2...
