### ISSUE TITLE
Refactor window to class: TopToolbar

### ISSUE THREAD

**Issue by tupaschoal** [OpenRCT2/OpenRCT2#18326]
Refers to file: https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2-ui/windows/TopToolbar.cpp
See #13737 for more details on how to accomplish the task.

**Comment by johnpatek** [comment]
I am currently working on a branch to address this issue.

**Comment by tupaschoal** [comment]
Ok, thanks for letting us know!
