### ISSUE TITLE
Can't build anything if land is too low

### ISSUE THREAD

**Issue by wolfblake** [OpenRCT2/OpenRCT2#1833]
I don't know if this is an original bug, but it is annoying that you can't build a ride or shop if the elevation is too low. 
![bug](https://cloud.githubusercontent.com/assets/5151086/9417799/e710f5d8-4814-11e5-93b4-b31e68094e7d.jpg)

**Comment by Gymnasiast** [comment]
It's an original _limit_. There is likely to be a good reason for it, although OpenRCT2 can probably take it out at some point (after switching away from SV6/SC6, possibly).
