### ISSUE TITLE
Extremely unreliable instillation

### ISSUE THREAD

**Issue by CSEverett** [OpenRCT2/OpenRCT2#18344]
### Operating System

Windows 7 64 bit

### OpenRCT2 build

4.2 release 32 bit

### Describe the issue

I'm having massive issues with my instillation. About 80% of the time it works fine, but upon loading a save file about every third time the game goes to the main screen, I get the error message attached, after which the game crashes (crash report attached). Not only that, but I occasionally have massive UI issues where all the windows go blank and as you drag them they leaves pieces of themselves behind. (like when windows is really screwed up.).

The files attached below is the only one gethub supports.

### Steps to reproduce

About 1/4th of the time you load a save, but never the first time.

### Attachments

[98dfe312-1df6-40ec-a7db-e64a35ccab05(8ceea45_x86).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/9792509/98dfe312-1df6-40ec-a7db-e64a35ccab05.8ceea45_x86.dmp.gz)

**Comment by CSEverett** [comment]
![Screen Shot 10-15-22 at 10 38 AM](https://user-images.githubusercontent.com/89952921/195995635-74c7e5bf-f577-4805-84e8-2f23c2ffc8ac.PNG)

**Comment by James103** [comment]
> Operating System: Windows 7 64 bit
> OpenRCT2 build: 4.2 release 32 bit

Since your OS is a 64-bit system, could you please try re-installing with a 64-bit build?

**Comment by Broxzier** [comment]
> The files attached below is the only one gethub supports.

You can always zip files up, then GitHub will allow any file.

It tries to reallocate exactly 256MB, which is quite a significant amount (especially for a x86 build), though for saved games it could make sense. With "every third time", do you mean it happens after loading 3 (different) saves in the same session?

> I occasionally have massive UI issues where all the windows go blank and as you drag them they leaves pieces of themselves behind. (like when windows is really screwed up.).

This makes me think you have the experimental OpenGL lighting option enabled. Try disabling that and see if it still happens.

**Comment by CSEverett** [comment]
Turns out that changing to a 64 bit installation as suggested fixed all the problems. In the past I've used whichever one seemed to work better, but I suppose it's 74 bit from now on.

**Comment by CSEverett** [comment]
Re:Broxzier - Judging from what you posted, I suspect the sheer number of custom scenery items was a major contributor, since there were certainty a ton of them.
