### ISSUE TITLE
Overwrite alert does not show when save name have different case on Windows 

### ISSUE THREAD

**Issue by beam41** [OpenRCT2/OpenRCT2#18354]
### Operating System

Windows 11, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.2 (8ceea45) provided by GitHub

### Describe the issue

On operating system like Windows file name like `aaa.park` and `AAA.park` is the same file.

But when you already have save names `aaa.park` and you input `AAA.park` in the save dialog it will overwrite `aaa.park` on the windows without overwrite alert shown

### Steps to reproduce

1. Play openrct2 on Windows
2. save game with name like `aaa.park`
3. start different park and save with name like `AAA.park`
4. no overwrite dialog show but `aaa.park` will be overwrite

**Comment by beam41** [comment]
System file dialog has similar problem aswell

If you save without extension it will not show overwrite alert
![image](https://user-images.githubusercontent.com/1791353/196028073-008fe370-650f-486d-92c7-eeaa38e8b858.png)

When I save without extension on Google Chrome it does show overwrite alert. So I think this is openrct2 bug.

**Comment by CookiePLMonster** [comment]
> If you save without extension it will not show overwrite alert

This should be fixed in the latest dev.
