### ISSUE TITLE
Track merging not working properly

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#1836]
Merging tracks will cause a lot of ghosts segment, and deleting track segments that overlap with other track will often remove the wrong segment. Many times the merge doesn't function and will crash the train.

Most of this behaviour seems to have started relatively recently.

**Comment by IntelOrca** [comment]
Track merging isn't actually a feature of the game, so I don't know what "working properly" actually means.

**Comment by Gymnasiast** [comment]
You can't build the overlapping segments, which is required for merging.

**Comment by IntelOrca** [comment]
Could you determine which commit stopped this from working?

**Comment by duncanspumpkin** [comment]
Works fine for me. Not sure if it was fixed or what.

**Comment by duncanspumpkin** [comment]
I think this is back to working fine so im closing this.
