### ISSUE TITLE
Mini Golf doesn't render Special E track's tunnel correctly

### ISSUE THREAD

**Issue by biggitjes** [OpenRCT2/OpenRCT2#18379]
### Operating System

windows 10 x64

### OpenRCT2 build

0.4.1

### Describe the issue

when I was building a Mini Golf and was underground. I have found that when you build element E it giltched. if you want to go after that right

### Steps to reproduce

start building mini golf use path to go underground and com out using element E

### Attachments

![open rct 2 fail](https://user-images.githubusercontent.com/116159944/196656210-069ac26e-d0f7-467a-8f87-85885e730881.png)

**Comment by Gymnasiast** [comment]
Next time, please make sure to properly specify _how_ it glitches exactly, specify the build number, and try the latest `develop` build first - there are usually lots of bugfixes between a release and `develop`, never mind an older release like yours.

Anyway, yes: the tunnel not rendering _is_ a bug that we’d like to see reported.

**Comment by raacker** [comment]
![image](https://user-images.githubusercontent.com/12020398/196874611-e8ca5fc1-df0e-4a6b-a6c4-460dc7c8c09e.png)

Happens for Special D as well

[minigolf_special.zip](https://github.com/OpenRCT2/OpenRCT2/files/9827004/minigolf_special.zip)

**Comment by raacker** [comment]
@Gymnasiast Hi,

I got a patch for the Special E track's tunnel issue but I think MiniGolf has other issues with Special D, E which renders the track beside the high ground.

![capture](https://user-images.githubusercontent.com/12020398/196880088-d09841fb-657e-481d-bcd5-741df86b7af4.PNG)

Do you think this bug should be merged into this issue as well?

**Comment by Gymnasiast** [comment]
@raacker I created a separate issue for that: https://github.com/OpenRCT2/OpenRCT2/issues/18423
