### ISSUE TITLE
Flying coaster cannot build large half loops or quarter loops when building backwards

### ISSUE THREAD

**Issue by dannystrayer** [OpenRCT2/OpenRCT2#18378]
### Operating System

MacOS

### OpenRCT2 build

OpenRCT2, v0.4.2 (c80bd45 on develop)

### Describe the issue

When attempting to build in the backwards direction on the flying roller coaster the following track pieces do not show up in the Special drop down menu:

- Quarter loop
- Large inside half loop
- Small inside half loop
- Large outside half loop
- Inline twist
- Vertical track piece 

There might be more but that is all I could pinpoint

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

Begin building a flying coaster
Attempt to build backwards
None of those track pieces are available

**Comment by Gymnasiast** [comment]
This is a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/17882.
