### ISSUE TITLE
Guests low on cash do not leave

### ISSUE THREAD

**Issue by ThornTSC** [OpenRCT2/OpenRCT2#1841]
Guests that can no longer afford rides, food, or drink (and presumably bathrooms, although I have not tested this) never decide to leave the park, causing overcrowding and eventually getting angry. This would not happen in unmodified RCT2 and, until recently, did not happen in OpenRCT2. Develop builds from about the last week or so seem to have introduced the issue—as the issue takes game time to become  noticeable, I cannot pinpoint the exact build that introduced the problem, as I was always updating to the latest.

http://1drv.ms/1LvXKdP has a ZIP of four save files for RCT1 parks in RCT2, all of which are pay-per-ride. This eventually leaves guests with no money for rides, food, or drink. I included two parks in which the problem is readily apparent as well as two parks that I can confirm have the problem if they run unattended for a year despite not having the problem before. Checking the number of guests thinking "I'm hungry" with the game sped up is enough to see the issue in action, and the earliest of those guests to enter the park are out of money in most cases.

![image](https://cloud.githubusercontent.com/assets/13948969/9447384/0ded0938-4a65-11e5-870d-e4500bd8042a.png)

![image](https://cloud.githubusercontent.com/assets/13948969/9447408/31d14c74-4a65-11e5-9991-5b338a8ee4bd.png)

**Comment by ryanbowden** [comment]
I have found this where guest never leave, In the one I am seeing I think it because none of my guest get tired..... Ever. 

Maybe the cheats have cause it to go wrong. If you need me to post my park as well to help find the issue let me know.

**Comment by ThornTSC** [comment]
I can safely say that cheats were not in use when I encountered the issue. It happens during normal scenario play.

**Comment by computernewb** [comment]
This seems to be a problem in my park as well. There are a lot of guests who have no money left for food, drinks, etc, but they never leave. This is causing overcrowding, and I fear it may cause my park rating to go down because of anger. Do you still have this problem?

I have not used any cheats during my game at all.
