### ISSUE TITLE
Game menu title sequence displays stationary sprites

### ISSUE THREAD

**Issue by J-PIE-314** [OpenRCT2/OpenRCT2#18448]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.2 (8ceea45) provided by GitHub

### Describe the issue

After quitting to the main menu stationary sprites appear on screen. This seems to be an issue after quitting saves of RCT1 games. This issue appears over multiple title sequences.

### Area(s) with issue?

New Save Format (NSF)

### Steps to reproduce

1. Open the attached save file.
2. Quit to menu.

![Screenshot 2022-10-26 001](https://user-images.githubusercontent.com/80489909/198086414-2a8bcd88-2d4c-47d2-a291-fa1d7d29d561.png)

3. Residual sprites stay on screen. The floating log flume (below) is not a residual sprite from the saved park (Grand Glacier).

![Screenshot 2022-10-26 003](https://user-images.githubusercontent.com/80489909/198088051-f8362a37-e620-465d-a58c-24345ac92944.png)

### Attachments

[theme bug.zip](https://github.com/OpenRCT2/OpenRCT2/files/9872122/theme.bug.zip)

**Comment by Gymnasiast** [comment]
Does not seem to occur as of v0.4.10, so closing this issue. Let us know if it persists.

**Comment by 733737** [comment]
I believe there was a pr that addressed this
