### ISSUE TITLE
Crash when opening up new flat-ride while launch tower construction window is open

### ISSUE THREAD

**Issue by martinhalldin** [OpenRCT2/OpenRCT2#1844]
Extremely specific I know but I've checked multiple times and it's a persisting bug. Every time I tried to place down a ride (the topspin ride even more specifically) while the construction window for launch tower was open; the game crashes. Would love to see a fix for this because I'm tired of going "fuuuuuuck" whenever I try to build something. (Autosave is a life saver though, thank you for that feature)

I'm using v0.0.3-develop build 1171.

**Comment by Gymnasiast** [comment]
Hm, it sounds as if you have two construction windows open: one for the launch tower and one for the top spin. Is that correct?
(If so, that the bug, as the game should only allow one construction window to be open at a time.)

**Comment by martinhalldin** [comment]
That's correct, having two construction windows open at the same time crashes the game. Just wondering (and to see if it's a global bug or just a one time thing) does this happen to you too?

**Comment by Gymnasiast** [comment]
Yes, it crashes for me as well.

**Comment by Gymnasiast** [comment]
I'm working on this.
