### ISSUE TITLE
About window looks glitchy when sprites move behind it

### ISSUE THREAD

**Issue by J-PIE-314** [OpenRCT2/OpenRCT2#18443]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.2 (8ceea45) provided by GitHub

### Describe the issue

The middle of the about window looks glitchy when movable sprites are behind it (i.e. peeps, vehicles, etc.). This bug only occurs on the OpenRCT2 tab.

### Steps to reproduce

1. Open a park
2. Under the "Disk and game options" menu (top left) choose "About 'OpenRCT2'"
3. Relocate the view of the park to a spot where a sprite is moving. If the sprite is behind the middle of the about window, words will flicker and sometimes disappear.

![Screenshot5 2022-10-25](https://user-images.githubusercontent.com/80489909/197927886-c5cfc4df-0760-40d5-b425-ebd3d4301aa7.png)

**Comment by duncanspumpkin** [comment]
this usually happens when the window size is not set correctly.

**Comment by rik-smeets** [comment]
I can't reproduce this issue, can you supply a save where this happens?

**Comment by Broxzier** [comment]
Does this only happen with the About window? There are some reports of experimental lighting causing windows to have these issues.

**Comment by rik-smeets** [comment]
I still can't reproduce it: I tried dragging the window around and used different screen modes / scaling factors / drawing engines.

What screen mode and (if full screen) resolution are you using? And how about the window scale factor and drawing engine?

**Comment by rik-smeets** [comment]
Thanks, I managed to reproduce the issue now. I'll take a look at it later :-)

**Comment by rik-smeets** [comment]
I can't reproduce this anymore. There have been some changes to the About window (adding the contributors), so perhaps it's been resolved indirectly.

If not, feel free to re-open.
