### ISSUE TITLE
Highlight path issues does not show railings on paths with a bench, lamp, or queue line TV.

### ISSUE THREAD

**Issue by J-PIE-314** [OpenRCT2/OpenRCT2#18459]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.2 (8ceea45) provided by GitHub

### Describe the issue

When highlighting path issues, railings are not visible if the path has any bench, lamp or queue line TV on it.

### Steps to reproduce

1. Open any park with flat paths with railings (Six Flags Great Adventure for example).
2. Turn on "Highlight path issues" via the visibility tab on the top of the screen.
3. Open the scenery window tab.
4. Use the appearing options box to select a bench, lamp, or queue line TV.

![Screenshot 2022-10-28 002](https://user-images.githubusercontent.com/80489909/198742388-34077424-86c9-41a4-bc53-896d8cb453b6.png)

5. Place any bench on a flat path with railings, place a lamp on any path with railings, or place a queue line TV on any queue line with railings.

![Screenshot 2022-10-28 003](https://user-images.githubusercontent.com/80489909/198742417-5676a952-f53e-4903-9395-025304c3d1d9.png)

### Attachments

_None_

**Comment by ocalhoun6** [comment]
There are also some gaps in the queue line's railing. Is that intentionally built without railings, or is it from queue line TVs or lamps or something?

**Comment by Broxzier** [comment]
Makes some sense, bins are handled differently. They don't only show up when vandalized, but show up when they're full too.
