### ISSUE TITLE
"Error loading objects for park" for RCT1 scenarios

### ISSUE THREAD

**Issue by MrCantaloupe** [OpenRCT2/OpenRCT2#18461]
### Operating System

Ubuntu 20.04 (Kubuntu distribution)

### OpenRCT2 build

OpenRCT2, v0.4.2 (, DEBUG)  (Linux nightly build using Launchpad ppa)

### Describe the issue

Sometime after the restoration of some RCT1 "classic" features I have not been able to load RCT1 scenarios any more.  The error "Error loading objects for park" appears and seems to be linked to the particular RCT1 names for trains?
Below is an example of the error dialog for Forest Frontiers.  Note the names of the "missing or corrupt" objects "steel_rc_trains" and "wooden_rc_trains".

- ![image](https://user-images.githubusercontent.com/7056104/198811154-66451426-0f29-46b6-901c-161a3751059a.png)

### Area(s) with issue?

Unknown

### Steps to reproduce

1. Open any RCT1 scenario, such as Forest Frontiers.  (Both expansions are affected as well.)
2. The park fails to load and the "Error loading objects for park" dialog pops up, always referring to missing objects such as "rct1.ride.inverted_trains".

### Attachments
Forest Frontiers
![image](https://user-images.githubusercontent.com/7056104/198812374-bedfa19e-b4d0-4bd4-a9d0-f489c099b387.png)
Three Monkeys Park (Corkscrew Follies)
![image](https://user-images.githubusercontent.com/7056104/198812523-142bbcdf-7acf-4e10-adb5-08a0b5df924b.png)
Arid Heights (Loopy Landscapes)
![image](https://user-images.githubusercontent.com/7056104/198812564-ac1bb3d6-6ab4-40a2-b9d8-fe2d32ee2e15.png)

**Comment by MrCantaloupe** [comment]
This is still occurring as of build
0.4.2-develop-0~3913-202211181233-ga8499f501~ubuntu20.04.1
(according to launchpad).

For reference, the "Download all" button in the above dialogs lifts a brief popup saying it's downloading the files but the problem persists, even after restarting the game.

I have also attempted to copy a friend's "data" folder into /home/.config/OpenRCT2 (which appears to be the directory it reads this information from on his Windows installation) but this hasn't worked either.  There is normally no "data" folder there.

**Comment by ppielorz** [comment]
I confirm the same behaviour on Zorin OS 16.2 (Ubuntu 20.04.1). Clean installation using guide from quickstart, both RCT and RCT2 versions from Steam.

**Comment by MrCantaloupe** [comment]
This issue appears to have been fixed by this post (2022 Dec 09), somewhere between versions
0.4.2-develop-0~3934-202211300832-g752eec116~ubuntu20.04.1
and
0.4.2-develop-0~3951-202212090347-g2d101a521~ubuntu20.04.1

For reference, the issue appears to have been that the ride objects in the "data" folder (directory /usr/share/openrct2/object/rct1/ride in Linux) were not correctly updated with the new RCT1 objects.

I'm closing this bug report for now; thanks to whoever fixed it!  🎉
