### ISSUE TITLE
Windows 10 OpenRCT2 Crash

### ISSUE THREAD

**Issue by LewisTehMinerz** [OpenRCT2/OpenRCT2#1846]
OpenRCT2 crashes on startup on Windows 10 with latest build. It spams this line in the console:

ERROR[..\src\object.c:160 (object_load)]: Object Load failed due to no items installed check.

(Using portable ZIP)

**Comment by Gymnasiast** [comment]
Do have RCT2 installed?

**Comment by LewisTehMinerz** [comment]
No. That's why I got OpenRCT2.

**Comment by Gymnasiast** [comment]
You need several RCT2 files in order for OpenRCT2 to work. These are listed here: https://github.com/OpenRCT2/OpenRCT2/wiki/Required-RCT2-files

**Comment by LewisTehMinerz** [comment]
How do I get these files?

**Comment by daihakken** [comment]
You can use the completely *free* RCT2:MG to run the game, the details in the link that @Gymnasiast posted.

**Comment by IntelOrca** [comment]
Ideally though you would either already own the game somewhere, on CD perhaps or buy it from GOG or Steam. Once you have those files, keep them somewhere safe. If you have a CD - you don't need to actually install it - just grab the files.

**Comment by IntelOrca** [comment]
I thought the game checked g1.dat first...? Which it uses to determine whether your install path is correct.

**Comment by triggerk** [comment]
Same issue here:

(3aec.15ec): Access violation - code c0000005 (!!! second chance !!!)
*** ERROR: Module load completed but symbols could not be loaded for C:\Program Files (x86)\OpenRCT2\openrct2.exe
*** WARNING: Unable to verify checksum for C:\Program Files (x86)\OpenRCT2\openrct2.dll
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for C:\Program Files (x86)\OpenRCT2\openrct2.dll - 
eax=00000000 ebx=00000000 ecx=00000002 edx=00000070 esi=00f7e050 edi=009ac128
eip=006e44de esp=000dfa0c ebp=ffffffff iopl=0         nv up ei pl nz na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00210206
openrct2+0x2e44de:
006e44de f6450910        test    byte ptr [ebp+9],10h       ss:002b:00000008=??
0:000> kv
ChildEBP RetAddr  Args to Child              
WARNING: Stack unwind information not available. Following frames may be wrong.
000dfa08 0ffcf4db 006e44b0 000dfa30 05400040 openrct2+0x2e44de
000dfa30 0fff45e5 00000000 00000002 00000070 openrct2_ffb0000+0x1f4db
000dfa68 0fff48b1 00000040 0fff4af4 009ac130 openrct2_ffb0000+0x445e5
000dfa70 0fff4af4 009ac130 0325b7ac 009ac132 openrct2_ffb0000+0x448b1
000dfaa0 0fff529e 014234bc fffffb1c fffffd46 openrct2_ffb0000+0x44af4
00000000 00000000 00000000 00000000 00000000 openrct2_ffb0000+0x4529e
0:000> !analyze -v
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************


FAULTING_IP: 
openrct2+2e44de
006e44de f6450910        test    byte ptr [ebp+9],10h

EXCEPTION_RECORD:  ffffffff -- (.exr 0xffffffffffffffff)
ExceptionAddress: 006e44de (openrct2+0x002e44de)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 00000000
   Parameter[1]: 00000008
Attempt to read from address 00000008

CONTEXT:  00000000 -- (.cxr 0x0;r)
eax=00000000 ebx=00000000 ecx=00000002 edx=00000070 esi=00f7e050 edi=009ac128
eip=006e44de esp=000dfa0c ebp=ffffffff iopl=0         nv up ei pl nz na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00210206
openrct2+0x2e44de:
006e44de f6450910        test    byte ptr [ebp+9],10h       ss:002b:00000008=??

FAULTING_THREAD:  000015ec

DEFAULT_BUCKET_ID:  NULL_CLASS_PTR_READ

PROCESS_NAME:  openrct2.exe

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_PARAMETER1:  00000000

EXCEPTION_PARAMETER2:  00000008

READ_ADDRESS:  00000008 

FOLLOWUP_IP: 
openrct2+2e44de
006e44de f6450910        test    byte ptr [ebp+9],10h

NTGLOBALFLAG:  400

APPLICATION_VERIFIER_FLAGS:  0

APP:  openrct2.exe

ANALYSIS_VERSION: 6.3.9600.17336 (debuggers(dbg).150226-1500) x86fre

PRIMARY_PROBLEM_CLASS:  NULL_CLASS_PTR_READ

BUGCHECK_STR:  APPLICATION_FAULT_NULL_CLASS_PTR_READ

LAST_CONTROL_TRANSFER:  from 0ffcf4db to 006e44de

STACK_TEXT:  
WARNING: Stack unwind information not available. Following frames may be wrong.
000dfa08 0ffcf4db 006e44b0 000dfa30 05400040 openrct2+0x2e44de
000dfa30 0fff45e5 00000000 00000002 00000070 openrct2_ffb0000+0x1f4db
000dfa68 0fff48b1 00000040 0fff4af4 009ac130 openrct2_ffb0000+0x445e5
000dfa70 0fff4af4 009ac130 0325b7ac 009ac132 openrct2_ffb0000+0x448b1
000dfaa0 0fff529e 014234bc fffffb1c fffffd46 openrct2_ffb0000+0x44af4
00000000 00000000 00000000 00000000 00000000 openrct2_ffb0000+0x4529e


STACK_COMMAND:  .cxr 0x0 ; kb

SYMBOL_STACK_INDEX:  0

SYMBOL_NAME:  openrct2+2e44de

FOLLOWUP_NAME:  MachineOwner

MODULE_NAME: openrct2

IMAGE_NAME:  openrct2.exe

DEBUG_FLR_IMAGE_TIMESTAMP:  504d6947

FAILURE_BUCKET_ID:  NULL_CLASS_PTR_READ_c0000005_openrct2.exe!Unknown

BUCKET_ID:  APPLICATION_FAULT_NULL_CLASS_PTR_READ_openrct2+2e44de

ANALYSIS_SOURCE:  UM

FAILURE_ID_HASH_STRING:  um:null_class_ptr_read_c0000005_openrct2.exe!unknown

FAILURE_ID_HASH:  {d22c01e3-fd74-a75c-f82f-552bd8e46592}

Followup: MachineOwner
---------

0:000>

**Comment by Joshwoo69** [comment]
did you run in administrator?

**Comment by triggerk** [comment]
nope, but either way it gives the same crash

**Comment by Joshwoo69** [comment]
@triggerk a bit confused about the log here... looks like a access violation.

**Comment by Gymnasiast** [comment]
Er, no. Program Files can be read and executed by non-admin users. Only changing the files in there is not possible for a non-admin, but we're nowhere near that yet. And running programs that shouldn't need it as Administrator is a security risk anyway.

**Comment by IntelOrca** [comment]
@triggerk where did you download OpenRCT2 from, do you have the exact link or build?

**Comment by triggerk** [comment]
i built it myself from the repo,

```
Using the debug version, I could see where it crashes:
0:000> kp
ChildEBP RetAddr  
WARNING: Stack unwind information not available. Following frames may be wrong.
000df900 526a137b image00400000+0x2e44de
000df928 526cbf82 openrct2!RCT2_CALLPROC_X(int address = 0n33669120, int _eax = 0n235831296, int _ebx = 0n269361172, int _ecx = 0n16252982, int _edx = 0n302944009, int _esi = 0n37749126, int _edi = 0n235798528, int _ebp = 0n536985600)+0x2b [c:\users\edgar\desktop\openrct2-develop\src\addresses.c @ 28]
000df968 526cc251 openrct2!sub_68B3FB(int x = <Value unavailable error>, int y = <Value unavailable error>)+0x2b2 [c:\users\edgar\desktop\openrct2-develop\src\interface\viewport.c @ 1855]
000df970 526cc494 openrct2!map_element_paint_setup(int x = <Value unavailable error>, int y = <Value unavailable error>)+0x91 [c:\users\edgar\desktop\openrct2-develop\src\interface\viewport.c @ 1980]
000df9a0 526ccc4e openrct2!viewport_paint_setup(void)+0x234 [c:\users\edgar\desktop\openrct2-develop\src\interface\viewport.c @ 2057]
000df9b8 526ca45d openrct2!viewport_paint(struct rct_viewport * viewport = <Value unavailable error>, struct rct_drawpixelinfo * dpi = 0x000dfa30, int left = 0n-1252, int top = 0n-798, int right = <Value unavailable error>, int bottom = 0n-698)+0x28e [c:\users\edgar\desktop\openrct2-develop\src\interface\viewport.c @ 2364]
000df9e8 5273a869 openrct2!viewport_render(struct rct_drawpixelinfo * dpi = 0x000dfa30, struct rct_viewport * viewport = 0x014234bc, int left = 0n-1252, int top = 0n338, int right = 0n-924, int bottom = 0n-698)+0xdd [c:\users\edgar\desktop\openrct2-develop\src\interface\viewport.c @ 735]
000dfa00 526d296f openrct2!window_editor_main_paint(struct rct_window * w = 0x01420078, struct rct_drawpixelinfo * dpi = 0x000dfa30)+0x29 [c:\users\edgar\desktop\openrct2-develop\src\windows\editor_main.c @ 99]
(Inline) -------- openrct2!window_event_paint_call+0x11 [c:\users\edgar\desktop\openrct2-develop\src\interface\window.c @ 1981]
000dfa40 526bc468 openrct2!window_draw(struct rct_window * w = 0x01420078, int left = 0n196, int top = 0n338, int right = 0n524, int bottom = 0n438)+0x1ef [c:\users\edgar\desktop\openrct2-develop\src\interface\window.c @ 1547]
000dfa60 526c9db7 openrct2!gfx_redraw_screen_rect(short left = 0n196, short top = <Value unavailable error>, short right = 0n524, short bottom = 0n438)+0xd8 [c:\users\edgar\desktop\openrct2-develop\src\drawing\drawing.c @ 347]
000dfa98 526c9fb0 openrct2!sub_6E7F34(struct rct_window * w = 0x01420078, struct rct_viewport * viewport = 0x014234bc, short x_diff = 0n1088, short y_diff = 0n4991)+0xa7 [c:\users\edgar\desktop\openrct2-develop\src\interface\viewport.c @ 472]
000dfad0 526ca2d7 openrct2!sub_6E7DE1(short x = 0n-1448, short y = 0n-1136, struct rct_window * w = 0x01420078, struct rct_viewport * viewport = 0x014234bc)+0x1b0 [c:\users\edgar\desktop\openrct2-develop\src\interface\viewport.c @ 548]
000dfb00 526b6ef5 openrct2!viewport_update_position(struct rct_window * window = 0x01420078)+0x297 [c:\users\edgar\desktop\openrct2-develop\src\interface\viewport.c @ 674]
000dfb18 526b70a2 openrct2!title_set_location(int x = 0n240, int y = 0n1328)+0x65 [c:\users\edgar\desktop\openrct2-develop\src\title.c @ 248]
000dfc68 526b7545 openrct2!title_do_next_script_opcode(void)+0x122 [c:\users\edgar\desktop\openrct2-develop\src\title.c @ 456]
000dfc70 526b7984 openrct2!title_update_showcase(void)+0x25 [c:\users\edgar\desktop\openrct2-develop\src\title.c @ 473]
000dfc90 526b6b47 openrct2!title_refresh_sequence(void)+0x1f4 [c:\users\edgar\desktop\openrct2-develop\src\title.c @ 791]
(Inline) -------- openrct2!title_init_showcase+0x5 [c:\users\edgar\desktop\openrct2-develop\src\title.c @ 171]
000dfca0 526b2652 openrct2!title_load(void)+0x1f7 [c:\users\edgar\desktop\openrct2-develop\src\title.c @ 136]
000dfcb0 526b039d openrct2!rct2_init(void)+0x202 [c:\users\edgar\desktop\openrct2-develop\src\rct2.c @ 189]
000dfed8 526b0495 openrct2!openrct2_initialise(void)+0x2bd [c:\users\edgar\desktop\openrct2-develop\src\openrct2.c @ 238]
000dfedc 526fa99d openrct2!openrct2_launch(void)+0x5 [c:\users\edgar\desktop\openrct2-develop\src\openrct2.c @ 266]
000dfee0 004069e4 openrct2!StartOpenRCT(struct HINSTANCE__ * hInstance = <Value unavailable error>, struct HINSTANCE__ * hPrevInstance = 0x00000000, char * lpCmdLine = 0x016b3d1e "", int nCmdShow = 0n10)+0x5d [c:\users\edgar\desktop\openrct2-develop\src\platform\windows.c @ 102]
000dff80 768c38f4 image00400000+0x69e4
000dff94 77075e13 KERNEL32!BaseThreadInitThunk+0x24
000dffdc 77075dde ntdll!__RtlUserThreadStart+0x2f
000dffec 00000000 ntdll!_RtlUserThreadStart+0x1b
```
