### ISSUE TITLE
"Selected only" object Selection filters is active in track design manager, and cannot be toggled

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#18467]
### Operating System

Windows 10 x64

### OpenRCT2 build

OpenRCT2 v0.4.2-109-g2aa46a7 (2aa46a7 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

No rides are listed when this filter is enabled. This filter cannot be changed, and it makes no sense for the track design manager, so it should be ignored.

### Steps to reproduce

1. Open any park or the scenario editor
2. Tick the filter "Selected only"
3. Open the track design manager
4. Notice how no rides are listed

**Comment by ilaiyengar** [comment]
Hi! I am a first time contributor and would love to work on this. Can I be assigned on this issue?

**Comment by kurbus** [comment]
@Broxzier if ilaiyengar isn't going to PR this, can I be assigned to it?

**Comment by Broxzier** [comment]
Sure, go ahead. I haven't seen any activity from @ilaiyengar yet.

**Comment by kurbus** [comment]
> Sure, go ahead. I haven't seen any activity from @ilaiyengar yet.

I'll try my best

**Comment by Broxzier** [comment]
Good luck! If you get stuck or have any questions, you can ask for help here or on Discord.

**Comment by kurbus** [comment]
i can't find where this is handled, if anyone else wants to try and fix this before I do you're welcome to, I'm still gonna try though

**Comment by mdbckrtn** [comment]
I have a fix for this and will open a PR momentarily @kurbus
