### ISSUE TITLE
Land rights window issues

### ISSUE THREAD

**Issue by DaNicolas** [OpenRCT2/OpenRCT2#18469]
### Operating System

Ubuntu Linux 20.04

### OpenRCT2 build

OpenRCT2, v0.4.2 (, DEBUG)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

In a scenario where one can purchase construction rights, the plots available for purchase should only be highlighted when the relevant window ("buy land/construction rights") is open.
Indeed, these plots get highlighted when I open the relevant window. However, when I close this window, the available plots with construction rights remain highlighted indefinitely.

### Steps to reproduce

1. Start a scenario where one can purchase construction rights (e.g. Dusty Greens)
2. Click on the park entrance and on the "buy land/construction rights" button. This will mark plots available for purchase with a sign.
3. After closing the "buy land/construction rights", the markers for the construction rights remain visible.

Only solution I found so far was to save and quit the game (to main menu) and then load again.

### Attachments

![Dusty Greens 2022-10-30 01-04-50](https://user-images.githubusercontent.com/74460486/198856008-4853c815-e68c-4290-9790-9854a0b36c25.png)

**Comment by rik-smeets** [comment]
I can't reproduce this issue on the current develop branch anymore. Could you verify if this issue still occurs, and if so, update the `Steps to reproduce`?

**Comment by rik-smeets** [comment]
Other than the markers remaining visible indefinitely, some other bugs would occur: you could not select the type of rights to buy for example, even if both types were still available.
