### ISSUE TITLE
Crash in Scenario Editor

### ISSUE THREAD

**Issue by runelaenen** [OpenRCT2/OpenRCT2#1848]
https://openrct.net/forum/topic/169/last/crash-in-scenario-editor

I have a problem. Every time I try to make my own scenario, the game crashes. It can crash while selecting items, while terraforming or while placing paths. I'm playig in the stable version and I tried to switch, but it crashs every time.

Happens in both dev and stable version.

**Comment by runelaenen** [comment]
Another user has problems with the scenario editor.
https://openrct.net/forum/topic/199/crashes-in-scenario-editor

**Comment by IntelOrca** [comment]
@runelaenen Please make a separate issue in future as I have just fixed the second one but not the first one.

**Comment by runelaenen** [comment]
Ah I thought it may've been the same problem. I'll do that next time.

**Comment by janisozaur** [comment]
Haven't seen scenario editor crash in a long time, most probably fixed with #2177
