### ISSUE TITLE
Latest Dev Builds Keep Crashing on MacOS

### ISSUE THREAD

**Issue by SavvyAdam** [OpenRCT2/OpenRCT2#18481]
The last few dev builds for MacOS crash whenever the game launches at about 10 seconds. 
I tried the following builds and they all crashed: 

v0.4.2-b2ae5b1 
v0.4.2-6faddd9 
v0.4.2-787acb9 
v0.4.2-49e4496 
v0.4.2-582863e 
v0.4.2-3656ddf 
v0.4.2-9b4cdb9 
v0.4.2-133f435 
v0.4.2-0647d12 
v0.4.2-f7364fe 
v0.4.2-2aa46a7
v0.4.2-96b08ca 
v0.4.2-6319e8b 
v0.4.2-cf9ec0b 
v0.4.2-38d5793 
v0.4.2-a6c0776 
v0.4.2-93cdfbf 
v0.4.2-23a8914

The latest stable dev build I can get to work is v0.4.2-3f3c759

**Comment by SavvyAdam** [comment]
@janisozaur Can you advise as to how one does a "stack trace"

**Comment by janisozaur** [comment]
Macos usually provides those when a program crashes like this:

![mac-crashing-3_1580397317.png](https://user-images.githubusercontent.com/550290/199309241-56a16a4a-2d94-489e-82e5-d8b9bdec490a.png)

**Comment by janisozaur** [comment]
Great, thanks

**Comment by astraylife1** [comment]
I can verify this has been happening to me as well. My stack trace is attached here:
https://forums.openrct2.org/topic/6107-game-crashes-upon-opening/#comment-27607

**Comment by janisozaur** [comment]
Judging purely by stack trace this is https://github.com/OpenRCT2/OpenRCT2/blob/96b08ca801cbfc44fd8d435d0c4a6f79b208a48f/src/openrct2-ui/windows/Tooltip.cpp#L143 where there is no sequence point between arguments and right-most args consume a move-from left-most `tooltipWindow`

**Comment by janisozaur** [comment]
@astraylife1 @SavvyAdam GitHub should soon have a build available for https://github.com/OpenRCT2/OpenRCT2/pull/18483, can you please verify if that fixes your issue? The build should be available for download through https://github.com/OpenRCT2/OpenRCT2/actions/runs/3373426933 in several minutes.

**Comment by SavvyAdam** [comment]
@janisozaur just downloaded the build from the link above. 
That seems to have done trick.  Game is running as it should. 
Thanks for the quick turn around on this
