### ISSUE TITLE
Game crashes after pressing 'PLAY' on most recent dev build

### ISSUE THREAD

**Issue by Ulvenwood** [OpenRCT2/OpenRCT2#18496]
### Operating System

Windows 10

### OpenRCT2 build

v0.4.2-5451b15 DEV build, using launcher

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Error occurs immediately after pressing the play butting using the launcher with the latest dev build. [v0.4.2-5451b15](https://openrct2.org/downloads/develop/latest)

### Steps to reproduce

1. Start the launcher. 
2. Press play

### Attachments

![errorscreen](https://user-images.githubusercontent.com/111505704/199582366-15a72dea-add9-495a-b8fd-d6a0f720026b.jpg)

**Comment by Lastorder-DC** [comment]
If you clicked "Yes", No need to open new issue since backtrace already created one(if not reported before)
If you clicked "No", You should upload dump files(should created at `Documents\OpenRCT2` Folder) to debug.

**Comment by Gymnasiast** [comment]
Do you still have this issue?
