### ISSUE TITLE
"allow abritery track changes" will often crash the game

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#18507]
### Operating System

Windows 11, 64-Bits

### OpenRCT2 build

OpenRCT2, v0.4.2-122-gb2ae5b1 (b2ae5b1 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

so, you simply want to make a giga coaster train to be on a looping, you need said cheat to do so, but for some reasons, this version make this cheat, often crash the game.

### Steps to reproduce

1. Go to any parks/plays
2. Build a ride
3. Try to activate "abritary track changes" cheat
4. crash will often occurs here

### Attachments

https://youtu.be/f2jebq5e_LY

will be accessible when online

**Comment by TheClaudeQC** [comment]
https://youtu.be/4zIs5Htsaoo

here's a time it actually do it

**Comment by Gymnasiast** [comment]
I cannot reproduce this. Since the bug report is 16 months old, I am assuming this bug (if it was one) has been fixed.
