### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by Kcronige** [OpenRCT2/OpenRCT2#18543]
### Operating System

Windows 10 86 bit

### OpenRCT2 build

"C:\Users\Kevin\OneDrive\Desktop\OpenRCT2-0.4.2-develop-6faddd9-windows-win32"

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

There is an issue with lag whenever I view a list of closed rides. After around 30 or more rides are built and have closed as their status, there is lag that is alternating cycle from, normal then lag, normal then lag, and so on until the rides list is closed or if all the rides are open.

### Steps to reproduce

1. I open the ride list
2. If all rides are closed, then lag starts. 
3. 3. If all rides are open, its fine. 
4. #18524 #"C:\Users\Kevin\OneDrive\Documents\OpenRCT2\screenshot\Kevin's Park 2022-11-08 20-04-41.png"

**Comment by karst** [comment]
Could you download [Speccy](https://www.ccleaner.com/speccy/download/standard) and show a screenshot on what your hardware is? Would you also be able to zip up your park and upload it to here (or if it's over 25mb upload it to dropbox, google drive, one drive or mediafire, then drop the link here). 

Your screenshot isn't uploaded correctly. Could you drag and drop the screenshot in the comment bar?

**Comment by James103** [comment]
> Could you download [Speccy](https://www.ccleaner.com/speccy/download/standard)

You should not need a freemium/paid software like this to get information on the CPU.
Another way to get system information is as follows:
1. Run `dxdiag` from the terminal.
2. Wait for the progress bar to finish.
3. Click "Save All Information".
4. Attach the resulting `DxDiag.txt` file here.

**Comment by Gymnasiast** [comment]
Closing as the requested information was not provided.
