### ISSUE TITLE
cannot add bench/bin/lamp to invisible footpath

### ISSUE THREAD

**Issue by cheweytoo** [OpenRCT2/OpenRCT2#18547]
### Operating System

Ubuntu Linux 20.04.5

### OpenRCT2 build

afd0346 develop, AppImage

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Benches/bins/lamps/etc. cannot be built on invisible paths (the official ones, from openrct2.footpath_surface.invisible.json ):

https://user-images.githubusercontent.com/29800630/201068602-bec4b69e-78bc-43c0-bcfa-b3c2af683ba6.mp4

Building visible paths, accessorising those, and then changing them to invisible does keep the accessories.

_Almost_ the same goes for TVs on invisible queues:

https://user-images.githubusercontent.com/29800630/201069215-3d85300c-a08d-4159-bdac-c7df043f16de.mp4

When the mouse pointer touches the invisible queue's visible railing, the "build ghost" shows up and the TV can be built.

I'm guessing that a path's "builduponability" depends on visible pixels being touched by the mouse pointer? So this might not be an easy fix at all, if ever…

### Steps to reproduce

- build invisible path
- try adding a bench/bin/etc. to it

**Comment by karst** [comment]
The "hitbox" of anything in RCT is based of the displayed pixels. Since the invisible path has no pixels there's nothing to click on. Temporary solution is to first place a different path and then overwrite it with invisible path. A more permanent solution could be making the invisible path into a ghost of tarmac while having path objects selected or when having the tile inspector hovering over it

**Comment by cheweytoo** [comment]
That's what I deduced, yeah.

Since some kind of transparency is already there (glass, water), might it be possible to make the invisible paths juuuuust short of completely transparent? That could make them de-facto invisible, but still give them displayed pixels to be clicked.

**Comment by 733737** [comment]
currently invisible paths are simply corrupt elements, my pr introduces fully transparent paths, but it could beodified with dev interest

**Comment by karst** [comment]
I am pretty sure the invis footpaths are using empty image paths.  
![image](https://user-images.githubusercontent.com/1516893/201197828-4eb73f5f-239c-42ce-9114-5dd51c27ff2e.png)

**Comment by 733737** [comment]
i didn't realize there was a difference

**Comment by cheweytoo** [comment]
> The "hitbox" of anything in RCT is based of the displayed pixels.

There seem to be occasional exceptions in both directions to that rule:
- In "Highlight path issues" mode, guests are invisible, but their names still show up if the mouse pointer hovers where a guest is: 
![cg](https://user-images.githubusercontent.com/29800630/201940279-4d49dab8-b29a-4eaa-8fe1-a88a1b7797b3.png)

- In the normal game view, paths are ignored in favour of rides under or behind them: 
![rr1](https://user-images.githubusercontent.com/29800630/201940575-9684f8b2-470d-4c77-8d5f-ec639e1ace88.png)

I have no idea if any of this is helpful in maybe making invisible paths accessible to benches after all though.

**Comment by spacek531** [comment]
![image](https://user-images.githubusercontent.com/3454156/223571342-33dc68d3-3fbf-4ec0-82f5-6e5a745188fa.png)

You can build path additions on invisible path by hovering over the height marker when "height marks on paths" is enabled.

**Comment by cheweytoo** [comment]
> You can interact with the path height marker when "height marks on paths" is enabled.

Ooooh, nice find! That's very helpful, thanks!


> It would be possible to make height markers appear on invisible paths when trying to place a path addition or in path building mode. Is this desirable?

I'd say so. On the other hand, from an "easy to understand UI" perspective, it would not really be very obvious that the reason for height markers randomly showing up is to be helpful with path additions.

Maybe make invisble paths just slightly visible during path addition building, so there's a hitbox there to be hit?

**Comment by Broxzier** [comment]
> Maybe make invisble paths just slightly visible during path addition building, so there's a hitbox there to be hit?

Sounds like a good UX change. Could you make a feature suggestion for this?

**Comment by spacek531** [comment]
> > Maybe make invisble paths just slightly visible during path addition building, so there's a hitbox there to be hit?
> 
> Sounds like a good UX change. Could you make a feature suggestion for this?

Way ahead of you 😎 https://github.com/OpenRCT2/OpenRCT2/discussions/19599
