### ISSUE TITLE
Upgoing and downcoming inversion track elements are listed seperately

### ISSUE THREAD

**Issue by joflashstudios** [OpenRCT2/OpenRCT2#1854]
This may be part of a larger issues - the track dialog doesn't seem to have an idea of context - it will let me try to select any track element at any time. (For example, a corkscrew while on a right-banked uphill segment.)

![scr4](https://cloud.githubusercontent.com/assets/7459309/9525482/30953af4-4cdc-11e5-9b8c-9a1035eb55ee.png)

Note the duplicate entries - those are the different up and down variants of the inversions.

**Comment by Gymnasiast** [comment]
A probably related thing is that it allows one to select helixes when the banking is incorrect.

**Comment by LRFLEW** [comment]
This sounds similar to #1873. It's likely that a recent change to the construction window broke a number of things.
