### ISSUE TITLE
"Road" Path can go through water but gets no tunnel entrance

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#1855]
So for some reason you can go through water using the road path, other paths returns an error saying that you cannot build paths underwater.

![](http://puu.sh/jRMXP/8f99512c43.png)

I haven't tested this in a scenario or the original game yet

**Comment by Gymnasiast** [comment]
Cannot reproduce this. Could you provide more information and/or an affected save?

**Comment by Patrik356b** [comment]
Saving crashed the game and i'm unable to reproduce

On Mon, Aug 31, 2015 at 5:09 PM, Michael Steenbeek <notifications@github.com
> wrote:

> Cannot reproduce this. Could you provide more information and/or an
> affected save?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenRCT2/OpenRCT2/issues/1855#issuecomment-136401111>.
>



-- 
Best regards; Hexile

**Comment by Gymnasiast** [comment]
Hm, there seems to be some sort of corruption in the Scenario Editor. It might be related to #1848 and #1761.

**Comment by Patrik356b** [comment]
This may have had something to do with clearance check cheat. (i did use the disable cheat while doing that landscape but i dunno if i turned it off before this happened.

Would be really nice if we could have glassy tunnels for building tracks and paths underwater, but not essential.
