### ISSUE TITLE
"identify employee" click on existing patrol area sets additional patrol area

### ISSUE THREAD

**Issue by cheweytoo** [OpenRCT2/OpenRCT2#18561]
### Operating System

Ubuntu Linux 20.04.5

### OpenRCT2 build

e0bff8e develop, AppImage

### Base game

RollerCoaster Tycoon 2

### Describe the issue

When "show areas patrolled" is active, clicking on a grey patrol area tile to identify the associated employee  will – while indeed identifying the employee – immediately expand that employee's patrol area by a default 4×4 block with the same click:

https://user-images.githubusercontent.com/29800630/201476278-aecb43ce-89da-4eb6-83e5-ee33b1b8382f.mp4

I went through older releases: This issue first showed up in v0.4.0 (where apparently that same click creates _another_ non-contiguous 1×1 patrol area in a seemingly random location in addition to the unwanted 4×4), so it might be NSF related.

### Steps to reproduce

- have employee with set patrol area
- use "show areas patrolled" in employee UI
- click on grey patrol highlight tile to identify associated employee
- employee gets selected AND gets an additional 4×4 patrol area

**Comment by cheweytoo** [comment]
Fixed by https://github.com/OpenRCT2/OpenRCT2/pull/18329 – Thanks!

**Comment by tupaschoal** [comment]
Thanks for verifying!
