### ISSUE TITLE
Park from #8340 can no longer be opened

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#18576]
### Operating System

Any

### OpenRCT2 build

0.4.0

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Park attached to issue #8340 can no longer be loaded correctly ever since v0.4.0. It used to load without any issues in v0.3.5.1, the previous release.

https://github.com/OpenRCT2/OpenRCT2/files/2647348/park_performance_8340.sv6.gz

### Steps to reproduce

Try loading the park, observe failure and `This tile element type cannot be converted directly!` getting printed out in logs

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/8439499004cea345a1a469c0df61c86f245c6acf/src/openrct2/rct12/RCT12.h#L293

**Comment by janisozaur** [comment]
#18577 explains the offending element is of type 11

**Comment by janisozaur** [comment]
It seems this park requires having RCT1 linked, which I haven't set up.

Naively ignoring that element makes the park load, but I haven't investigated how broken it is or how different it looks from v0.3.5.1 - would appreciate some advice around this. @Gymnasiast can you take a look?

```diff
diff --git a/src/openrct2/rct2/S6Importer.cpp b/src/openrct2/rct2/S6Importer.cpp
index 18e539914..1aa5e802b 100644
--- a/src/openrct2/rct2/S6Importer.cpp
+++ b/src/openrct2/rct2/S6Importer.cpp
@@ -1328,7 +1328,14 @@ namespace RCT2
         void ImportTileElement(TileElement* dst, const RCT12TileElement* src, bool invisible)
         {
             const auto rct12Type = src->GetType();
-            dst->ClearAs(ToOpenRCT2TileElementType(rct12Type));
+            try
+            {
+                dst->ClearAs(ToOpenRCT2TileElementType(rct12Type));
+            }
+            catch (...)
+            {
+                return;
+            }
             dst->SetDirection(src->GetDirection());
             dst->SetBaseZ(src->base_height * COORDS_Z_STEP);
             dst->SetClearanceZ(src->clearance_height * COORDS_Z_STEP);
```

**Comment by 733737** [comment]
I cannot load the park, and I have RCT1 linked
