### ISSUE TITLE
Bug: As of latest build, I cannot add any more custom tracks

### ISSUE THREAD

**Issue by UTNerd24** [OpenRCT2/OpenRCT2#1857]
This might be somewhat of I priority, but I recently updated my Build to 1179, and downloaded a few custom Rollercoaster Tracks, but upon launch I get this error in the console: ERROR[..\src\ride\track.c:290 <track_list_cache_save>]: Failed to save C:/Users/████████/Documents/OpenRCT2/tracks.idx

ERROR[..\src\ride\track.c:460 <track_load_list>]: Track list failed to save.

Do I perchance have the files in the wrong directory? Is there a saved design limit? I have 1023 saved designs by the way. Help is appreciated!

**Comment by IntelOrca** [comment]
Does it still happen if you delete C:/Users/████████/Documents/OpenRCT2/tracks.idx?

**Comment by Gymnasiast** [comment]
How many tracks can tracks.idx actually handle?

**Comment by IntelOrca** [comment]
Possibly 1000, but I am not sure why.
@UTNerd24 Could you perhaps try temporarily removing 24 of your tracks from your tracks folder to see if it fixes it?

**Comment by UTNerd24** [comment]
Deleting my tracks.idx fixed it! Thank you!

**Comment by jensj12** [comment]
Had the same issue today after saving one custom coaster, game crashed completely after clicking a coaster to go to the choose design menu. I have 475 saved tracks.
