### ISSUE TITLE
RCT2 title sequence crashes at some transition on Wine

### ISSUE THREAD

**Issue by s0r00t** [OpenRCT2/OpenRCT2#1858]
When using the RCT2 intro, at some transition (after [this](http://i.imgur.com/KN9Dj1l.jpg) zone of the park), the game crashes : 
```
wine: Unhandled page fault on read access to 0x00000000 at address 0x1003ac7e (thread 0009), starting debugger...
```
[Wine debugger's output is here.](http://ix.io/kwG)

**Comment by Gymnasiast** [comment]
The intro is horribly broken in many ways, and disabled by default for this reason.

**Comment by s0r00t** [comment]
Should I close this issue, or keep it for the whole intro problems?

**Comment by Gymnasiast** [comment]
Oh wait, you mean the _title sequence_, not the intro. (The intro is the scrolling Infogrames and Chris Sawyer logo.)
Keep this open I'd say. I vaguely remember this bug, although I'm not quite sure whether it has been reported properly earlier.

**Comment by IntelOrca** [comment]
Most likely related to restarting the title sequence seeing as that park is the last one.

**Comment by s0r00t** [comment]
I'll try when I'll be able to compile ORCT2 under Arch.

**Comment by IntelOrca** [comment]
@s0r00t try this:
https://openrct2.com/download/latest/develop

**Comment by s0r00t** [comment]
Is fixed in develop indeed. Closing.
