### ISSUE TITLE
Game crashes when opening save

### ISSUE THREAD

**Issue by Julienscpfan11111** [OpenRCT2/OpenRCT2#18604]
### Operating System

Windows 11 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.2-178-g0d16c63 (0d16c63 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

hello I am new to this stuff I recently built a park and saved it but when I open it up a few hours later the game crashes and gives this error please help. I am running OpenRCT2, v0.4.2-178-g0d16c63 (0d16c63 on develop) provided by GitHub

### Steps to reproduce

1. Open the park save
2. the game crashes and gives the error

### Attachments

![crash](https://user-images.githubusercontent.com/118357200/202171994-ce214131-9d3e-49aa-bf23-72d903b82299.jpg) 
https://drive.google.com/drive/folders/1sRIE9u5UEk3ChlUWwXZZXUSrkkweswGP?usp=sharing the dump files
https://drive.google.com/file/d/1XgBJ4ClRs0hHFExtO_f69GcOvx9TKQhD/view?usp=sharing the save file

**Comment by Gymnasiast** [comment]
Why did you close this?

**Comment by MrStanMan** [comment]
@Gymnasiast It seems to have been fixed according to this reddit post https://www.reddit.com/r/openrct2/comments/ywqiei/comment/iwohv5f/?utm_source=share&utm_medium=web2x&context=3
