### ISSUE TITLE
Guests won't leave when low on cash

### ISSUE THREAD

**Issue by CascadeBeta** [OpenRCT2/OpenRCT2#1861]
For whatever reason, when guests are low on cash in a park, they won't leave. Since they can no longer purchase food/ride rides, they tank your park rating.

It was also reported on the subreddit here: https://www.reddit.com/r/openrct2/comments/3i3m2i/bug_report_guests_low_on_cash_do_not_leave/

**Comment by pizza2004** [comment]
It was also reported on this bug tracker here: https://github.com/OpenRCT2/OpenRCT2/issues/1841

**Comment by IntelOrca** [comment]
Duplicate of #1841
