### ISSUE TITLE
Request: Cheat to make guests ignore ride/merchandise prices.

### ISSUE THREAD

**Issue by UTNerd24** [OpenRCT2/OpenRCT2#1862]
I have a feeling this cheat would cause a bit of protest, but eh, those 1x3 $1 mazes need a break at some point!

Feel free to negotiate this one.

**Comment by Gymnasiast** [comment]
Just put your game into 'No money' mode.

**Comment by s0r00t** [comment]
Do you want for guests to have unlimited money or someting like IntelOrca suggested?

**Comment by Gymnasiast** [comment]
I don't think it can be interpreted as anything else than what IntelOrca said. Anyway, it would a require load of exceptions for something that isn't really useful considering we have the No money mode.

**Comment by IntelOrca** [comment]
Yes, it doesn't make sense to make very minor adjustments to make the game's finances easier rather than just switching off money or cheating for money.
