### ISSUE TITLE
Application crashes when opening Options menu

### ISSUE THREAD

**Issue by lochermichael** [OpenRCT2/OpenRCT2#18623]
### Operating System

macOS 11.5.2

### OpenRCT2 build

openRCT2, v0.4.2 (8ceea45 on HEAD), macOS (AArch64)

### Base game

RollerCoaster Tycoon 2

### Describe the issue

If I access the Options menu either from the main menu or in-game, the application hard crashes and closes. If I manually enable Rosetta, such that it shows macOS (x86-64), the issue disappears.

### Steps to reproduce

1. Open the game
2. Click on the Options menu

### Attachments

[error log.txt](https://github.com/OpenRCT2/OpenRCT2/files/10045631/error.log.txt)

**Comment by GiantMolecularCloud** [comment]
Can confirm: Bug persists in v0.4.5 and is fixed by enabling Rosetta manually.

**Comment by Gymnasiast** [comment]
Does this still persist on v0.4.10?

**Comment by lochermichael** [comment]
Seems like it fixed it!
