### ISSUE TITLE
spurious message "Bomb Car has broken down" for non-broken down Flying Saucer ride

### ISSUE THREAD

**Issue by cheweytoo** [OpenRCT2/OpenRCT2#18680]
### Operating System

Ubuntu Linux 20.04.5

### OpenRCT2 build

4281914 develop, AppImage

### Base game

RollerCoaster Tycoon 2

### Describe the issue

I just received the park message "Bomb Car has broken down":

![bomb_car](https://user-images.githubusercontent.com/29800630/204032719-ed5d0777-6703-4e0f-8037-67e0f6000221.png)

There is no "Bomb Car" ride in this park.

Clicking on the ride icon in the message opens the ride properties for the creatively named "Chinese Dragonhead Ride 1" - _which apparently isn't even broken down_.

- It is _not_ the ride's name
- It is _not_ the ride's type (it's a "Flying Saucers" ride)
- I am reasonably certain to never have named any ride ever "Bomb Car" (I don't usually name rides at all)
- "Bomb" is nowhere to be found in the game's binary (at least according to `bless`)
- "Bomb" is nowhere to be found in the saved park (I unzipped it – `grep -a` then finds all kinds of ride names and sign labels in it) _except once_ for this weird message
- "Bomb" is nowhere to be found in plugins or elsewhere in the game's config dir
- "Bomb" is nowhere to be found in either game code or localisation repo (at least according to github's search)

So… what the "Bomb"?

### Steps to reproduce

I honestly have no idea.

I attached the cleaned up park with only the one ride left in it. See message history there.

### Attachments

[bomb_car_has_broken_down.zip](https://github.com/OpenRCT2/OpenRCT2/files/10094511/bomb_car_has_broken_down.zip)

**Comment by cheweytoo** [comment]
Just because I seem to remember very rarely getting holdover messages from a previously loaded different park just after loading a new one, I unzipped all title sequence parks and `grep`ed for "Bomb" in those: No result in any of them.

**Comment by James103** [comment]
> I unzipped all title sequence parks and `grep`ed

Did you do the same with all other parks you have saved? It's possible one of them may have had that term.

**Comment by cheweytoo** [comment]
Not yet. Since I had no other park loaded after starting ORCT2, I consider those unlikely.

But I'm still planning to do it for completeness' sake. Annoyingly, my command line `unzip` doesn't like the .park files, so I have to use a GUI version, with several clicks per park, which gets boring fast. I'm going to look for a CLI tool that works.

**Comment by ocalhoun6** [comment]
Or possibly a multiplayer park you joined in the past?

**Comment by cheweytoo** [comment]
I've never even clicked the multiplayer button, so: No :-)

**Comment by Gymnasiast** [comment]
This is most likely caused by the news messages not being properly cleared before a new game is imported. I have seen similar issues.

**Comment by cheweytoo** [comment]
I'm closing this: I've never seen this happen again for the last two years.

Maybe I'll manage to reproduce it if it ever reoccurs, but I'd just file a new issue then.
