### ISSUE TITLE
Construction rights cannot be viewed after all are purchased

### ISSUE THREAD

**Issue by jez9999** [OpenRCT2/OpenRCT2#18696]
### Operating System

Windows 10 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.2 (8ceea45) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Once all construction rights have been purchased, there is no longer any way to actually view the tiles you have construction rights for, because the construction rights button gets disabled.  There should be an additional "view construction rights" button in the land rights dialog to view purchased construction rights.  On a map like Urban Park, for instance, it becomes very tricky to build when you bought all the construction rights but can't see which tiles you're actually allowed to construct over/under.

### Steps to reproduce

1. Open Land Rights dialog.
2. Purchase all construction rights.
3. Close and open Land Rights dialog again.  Construction rights cannot be viewed.

**Comment by Gymnasiast** [comment]
This bug does _not_ exist in the original game, so I removed that from your description.

**Comment by jez9999** [comment]
It's been a while since I played the original actually, but how does the original display construction rights when they're all purchased?  I thought it had the same behaviour.
