### ISSUE TITLE
The corkscrew coaster is classified as a RCT2 ride, despite actually being an RCT1 ride

### ISSUE THREAD

**Issue by Derpercoaster** [OpenRCT2/OpenRCT2#18705]
### Operating System

Windows 10

### OpenRCT2 build

0.4.2 (8ceea45)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

The corkscrew rollercoaster is classified as a RCT2 ride in the item selection screen(in scenario editor/track designer), despite being present in RCT1 as well. 

### Steps to reproduce

1. Go to the scenario editor (specifically the ride selection tab), or track designer
2. Ensure all rides are deselected
3. In the filter tab, select only RCT1, CF, and LL, and leave all others unchecked
4. The corkscrew rollercoaster will not be in the ride selection list, even though it should be, as it was in RCT1

**Comment by spacek531** [comment]
There is currently a PR open to implement the RCT1 corkscrew coaster as a separate ride.

**Comment by Derpercoaster** [comment]
I was hoping so, given the trains are distinct enough. I'm surprised making the "classic" rides took as long as it did, although i don't know what was required to do so, since i can't code.

**Comment by Gymnasiast** [comment]
As the design was changed in RCT2, not listing the vehicle in RCT1 is correct and not a bug. Do note that the window lists vehicles and not ride types.
