### ISSUE TITLE
changing title sequence changes map

### ISSUE THREAD

**Issue by Kuro-Maii** [OpenRCT2/OpenRCT2#1870]
when in a park/scenario and changing the title sequence from the options menu it will give you the park that the title sequence should show as if you are playing that park.

to reproduces:
* start any scenario
* open the options
* go to miscellaneous
* change the title sequence
* done

All unsaved progress will be lost.
The first time I encountered this the game crashed when I switched the title sequence strait away for the second time.
A stack trace is available of the crash if desired. As it is about 200 lines long I did not fancy posting it in here.

**Comment by s0r00t** [comment]
This does not happens with RCT2's title sequence, and I don't have any other title sequence to test.

**Comment by IntelOrca** [comment]
```bool title_refresh_sequence()``` should first check if the current screen is title, and if it isn't just return.

**Comment by Gymnasiast** [comment]
I'll do that.
