### ISSUE TITLE
Alpine Coaster uphill helix enabled in special elements menu.

### ISSUE THREAD

**Issue by Sadret** [OpenRCT2/OpenRCT2#18720]
See attached image. While the buttons are correctly disabled, in the special elements menu you can still select (and then build) the uphill helixes. Same for building backwards.

Build: recent develop ([050f3f8](https://github.com/OpenRCT2/OpenRCT2/commit/050f3f85a4482070aeb2a584cde6b5c7a80ac581))

![image](https://user-images.githubusercontent.com/15895532/204525845-c383dd2d-1d5f-4e60-9520-650b43bced8c.png)

**Comment by karst** [comment]
I really think forward and backward building should be united. The inverted controls don't feel good at all and we keep on running in backwards building exclusive bugs.

**Comment by spacek531** [comment]
How does backwards building relate? Sadret said it happened both forwards and backwards.

**Comment by karst** [comment]
oh hold on i think i read it wrong. What often happens is that elements are either not showing up when going backwards or they are showing up double. Probably digressing in my mind again ^^;

**Comment by X123M3-256** [comment]
@spacek531 There's two bugs - the upward helices are still accessible from the special menu at all times, and also when building backwards, it disables the downward helix button instead of the upward one.
