### ISSUE TITLE
Lift Chains on Steep Hills shouldn't work but does.

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#1873]
![scr18](https://cloud.githubusercontent.com/assets/3945538/9623576/c1ef8ad0-5110-11e5-8b1b-62c72deb8c2d.png)
![scr19](https://cloud.githubusercontent.com/assets/3945538/9623577/c1f72588-5110-11e5-8730-a1abd69c3106.png)

If this could be kept as a cheat, that would be awesome... :)

**Comment by PFCKrutonium** [comment]
To achieve this, do the following:

![scr23](https://cloud.githubusercontent.com/assets/3945538/9623753/206f6f7e-5113-11e5-88c3-8b3cb80738cc.png)
![scr24](https://cloud.githubusercontent.com/assets/3945538/9623754/2071d6ec-5113-11e5-844d-1619b5f18cbb.png)
![scr25](https://cloud.githubusercontent.com/assets/3945538/9623755/2071ef1a-5113-11e5-8ad0-d2a4d32cc62a.png)
![scr26](https://cloud.githubusercontent.com/assets/3945538/9623756/2076e3a8-5113-11e5-8b2a-d576fba765e5.png)
![scr27](https://cloud.githubusercontent.com/assets/3945538/9623757/2077d1a0-5113-11e5-898d-a5a3693eada3.png)

**Comment by PFCKrutonium** [comment]
After a bit of testing, it seems to apply to other coasters as well.

**Comment by sjoerddebruin** [comment]
The same also seems to applies for banked tracks.

**Comment by LRFLEW** [comment]
I've made #1882 to resolve this issue. However, the cheat to allow players to do this intentionally may need to wait. On some pieces (such as turns and special pieces), the chain lift appears to be deactivating itself in undecompiled code. I'll do more investigating, but it's possible that the cheat will need to wait on more decompiling.

**Comment by sjoerddebruin** [comment]
A example for the thing I've described yesterday; https://www.dropbox.com/s/l5x10kzctpn5vqm/Schermafdruk%202015-09-03%2017.18.36.png?dl=0
