### ISSUE TITLE
Hide paths

### ISSUE THREAD

**Issue by runelaenen** [OpenRCT2/OpenRCT2#1874]
On the OpenRCT.net forums someone asked to be able to hide paths (in the same way you can hide scenery or rides)
You can find the post here: https://openrct.net/forum/topic/184/automatic-vandalism-maintenance#p593

**Comment by Gymnasiast** [comment]
As in: make them see-through temporarily.

RCT1 used a 'dotted pattern' for paths when you had underground view on.

**Comment by artao** [comment]
Good god yes!!
This is a feature I've wished for over and over again.

**Comment by marijnvdwerf** [comment]
Isn't this fixed by #4290?

**Comment by Gymnasiast** [comment]
It is, yes.
