### ISSUE TITLE
Overcrowding doesn't influence park rating

### ISSUE THREAD

**Issue by youssefdetovernickr** [OpenRCT2/OpenRCT2#1875]
I'm not sure if this is intended, but my park had somewhere near 999 rating, but the guests were complaining that it's really crowded.. It didn't seem to influence the park rating though.

**Comment by IntelOrca** [comment]
Park rating is based on total guest happiness, ride quality and amount of (not new) litter.

**Comment by youssefdetovernickr** [comment]
Well I'll close this up then
