### ISSUE TITLE
Camera prices do not add up to the profit per hour + income of that coaster.

### ISSUE THREAD

**Issue by youssefdetovernickr** [OpenRCT2/OpenRCT2#1877]
At each coaster you can see some statistics per ride in the "income and price" tab. You can change the price of that ride there too. If you've added a camera which takes photos, the people can buy the photos from you. However these do not add up to the "profit per hour" and "income", but they do on the "total profit".

You can test this by setting your ride price to $0.00 / Free, and then add an action camera. Your total profit of that ride goes up, but not the profit per hour and the "income"

**Comment by Gymnasiast** [comment]
Original bug.
