### ISSUE TITLE
Add G1 icons to IconNames.hpp and openrct2.d.ts

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#18829]
#18675 added names for g2 icons, but g1 icons should be added too, to make them easier to use.

**Comment by Harry-Hopkinson** [comment]
I would like to work on this issue. Should I add them all in one PR or should I split them up into multiple?

**Comment by Gymnasiast** [comment]
You can do all of them in one PR, it’s only going to touch a few files anyway.
