### ISSUE TITLE
Game hangs when loading a v0.4.2 save file after upgrading to v0.4.3

### ISSUE THREAD

**Issue by mide** [OpenRCT2/OpenRCT2#18858]
### Operating System

macOS 13.0 (22A380) (M1 Pro)

### OpenRCT2 build

OpenRCT2, v0.4.3 (285e0fc)

### Base game

RollerCoaster Tycoon Classic

### Area(s) with this issue?

This bug is specific to multiplayer, This issue has to do with park objects and/or asset packs

### Describe the issue

We had started a multiplayer game of _Karts & Coasters_ using `v0.4.2`. When we got the notice to upgrade to `v0.4.3`, we did and then this savefile started having significant stability issues. It's now progressed to the point where it ~~crashes~~ hangs shortly after loading. Tested on M1 Pro and Intel MacBook Pro laptops.

✨ **Thanks!** ✨

[Karts & Coasters.park.zip](https://github.com/OpenRCT2/OpenRCT2/files/10242026/Karts.Coasters.park.zip)

### Steps to reproduce

Load the savefile. Once it crashes, it completely locks up. I am happy to provide any additional information to help debug.

**Comment by James103** [comment]
The game hangs during the 522nd tick after loading the attached save file in 285e0fc (bisected with `openrct2 simulate`).

The verbose output stops completely when the game hangs.

**Comment by mide** [comment]
Another data point: We started a new game of _Mel's World_ and it's been perfectly stable. This save does not straddle versions, it's exclusively `v0.4.3`.

**Comment by janisozaur** [comment]
There are conflicting reports in this bug: does it crash or hang? In case of former, please provide stack trace (those that get reported by the OS).

**Comment by mide** [comment]
I have corrected the title to reflect the actual state; it does not crash. The executable continues to run (and music like the Merry-Go-Round continues to play). The game becomes non-responsive and the CPU does increase. 

<img width="896" alt="Screenshot 2022-12-20 at 7 27 14 PM" src="https://user-images.githubusercontent.com/546518/208792873-607ceb30-768b-4182-8838-0f8658465b4a.png">

<img width="1172" alt="Screenshot 2022-12-20 at 7 37 51 PM" src="https://user-images.githubusercontent.com/546518/208793674-73765b9d-e739-4456-b248-334197380f11.png">

I loaded with my system CPU monitor open and I've taken note of the various points of interest:
1. Started OpenRCT2
2. Loaded the troublesome save file from the main body of this PR.
3. Game enters it's hung state, becomes non-responsive. 
4. I exit the game by killing it via "Force Quit".

**Comment by ZehMatt** [comment]
The cause of this issue that the one of the queues have some bad data on peeps which ends up being recursive:
Peep[1239].GuestNextInQueue = 1448
Peep[1448].GuestNextInQueue = 1247
Peep[1247].GuestNextInQueue = 778
Peep[778].GuestNextInQueue = 0
Peep[0].GuestNextInQueue = 1239 -> Starts over here

The ride in question has ride id 26, its the wild mouse, not sure what corrupted this but you should be able to break the issue by removing the queue for that ride temporarily.

**Comment by mide** [comment]
Closing this because enough time has passed that I no longer can recall the complete context around this issue. Thanks for the detailed help @ZehMatt!
