### ISSUE TITLE
Track previews missing for TD6 files, but not for TD4

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#1886]

**Comment by IntelOrca** [comment]
Can you add more information?

**Comment by jensj12** [comment]
Is it that RCT2 simply doesn't need an extra file with the preview? RCT1 only stored the track data in the TD4 file and required an extra file for the preview. RCT2 automatically generates the preview when you view the design inside the design picker.

**Comment by Gymnasiast** [comment]
No, it's not that. RCT2 did not use the TP4 file that RCT1, it generated a preview from the TD4 (and TD6) files themselves.

**Comment by Gymnasiast** [comment]
It seems this big is only triggered with the game in pause mode:

TD6:
![scr105](https://cloud.githubusercontent.com/assets/1478678/9720878/25e6dbca-5593-11e5-967e-b51a90fce30b.png)

TD4:
![scr106](https://cloud.githubusercontent.com/assets/1478678/9720879/26a6b936-5593-11e5-92c4-f91bdfb1cbbd.png)

**Comment by IntelOrca** [comment]
How can the track list show TD4s? Surely its a TD4 that has been converted to a TD6?

**Comment by Gymnasiast** [comment]
No, it's TD4. RCT2 has always been capable if reading them directly. Note the absence of some data, like the required space, and the absence of an entrance and exit.

**Comment by IntelOrca** [comment]
Eh, right ok... that's weird.

**Comment by IntelOrca** [comment]
OK - the problem was that place entrance / exit didn't check for the allow paused flag and TD4's don't have entrance or exit positions.
