### ISSUE TITLE
L glitch and title card on game screen

### ISSUE THREAD

**Issue by Sophkat** [OpenRCT2/OpenRCT2#18873]
### Operating System

Windows 10, 64

### OpenRCT2 build

v0.4.3

### Base game

RollerCoaster Tycoon Classic

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

"L"s are appearing are "*"
The Title screen logo isnt on the title screen, when moving screen the picture drags

### Steps to reproduce

open game

![Diamond Heights 2022-12-17 16-38-14](https://user-images.githubusercontent.com/120841603/208266862-f2e1a756-3af3-418f-b6b1-d2a3c88b4c09.png)

### Attachments

![Diamond Heights 2022-12-17 16-38-14](https://user-images.githubusercontent.com/120841603/208266872-87a8074b-1bfb-4446-8611-983754626255.png)
![Diamond Heights 2022-12-17 16-38-58](https://user-images.githubusercontent.com/120841603/208266898-78404bd7-b0a8-4f6c-86eb-86545f9ab756.png)

**Comment by spacek531** [comment]
This occurs when the game is improperly updated. When manually updating, all the contents of the download must replace the old versions.
