### ISSUE TITLE
responding mechanic blocked at level crossing by train arriving at station, train never gets fixed

### ISSUE THREAD

**Issue by cheweytoo** [OpenRCT2/OpenRCT2#18895]
### Operating System

Ubuntu Linux 20.04.5

### OpenRCT2 build

 db41864 develop, AppImage

### Base game

RollerCoaster Tycoon 2

### Describe the issue

A mechanic responding to a broken down Miniature Railway can get blocked by a train on a level crossing directly adjacent to a station:

![mechanic_stuck_at_level_crossing](https://user-images.githubusercontent.com/29800630/208565124-f71e1c99-c90e-44ca-8107-23962d7fad38.png)

This means that the mechanic never gets to the railway, the railway never gets fixed, and the level crossing accumulates an ever increasing amount of guests.

I seem to remember that mechanics are supposed to always walk over a level crossing, even if there's a train on it, to prevent exactly the situation that happened here.

There might be a connection with #18490.

### Steps to reproduce

Have a level crossing right next to a Miniature Railway station, a mechanic on the wrong side of the tracks, and a well timed breakdown.

I managed to reproduce it after about five forced breakdowns: The attached park has a mechanic in the stuck state.

### Attachments

[mechanic_stuck_at_level_crossing.zip](https://github.com/OpenRCT2/OpenRCT2/files/10264182/mechanic_stuck_at_level_crossing.zip)

**Comment by ocalhoun6** [comment]
They're supposed to walk over blocked crossings only in this exact situation, to prevent this exact problem.

For some reason, though, it isn't happening in this case. Maybe because of the multiple trains? Or because the one blocking the track is partially inside the station?

Is it possible that the mechanic was stopped at this crossing *before* the ride broke down, and then the ride broke down while he was still waiting at the crossing?

**Comment by cheweytoo** [comment]
> Is it possible that the mechanic was stopped at this crossing _before_ the ride broke down, and then the ride broke down while he was still waiting at the crossing?

No, I watched the mechanic being called walk in there.

It indeed seems to depend on a specific position/state of the arriving train: It can't be _too_ far into the station yet, or the mechanic will walk through it. Same with "not yet far enough into the station". I haven't figured out the exact specifics yet.
