### ISSUE TITLE
years

### ISSUE THREAD

**Issue by Timbit1992** [OpenRCT2/OpenRCT2#18893]
### Operating System

windows 11  64 bit

### OpenRCT2 build

Main executable for OpenRCT2

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error, This issue has to do with park objects and/or asset packs

### Describe the issue

example an object to get 1500 people in 4 years. i save the game and then a few days later i go on to load the game and then it says that i fail my objective because its been  years. so i dont know how it leaped from 3 years to 65 years. once the game is saved it should resume where you left off which it didnt

### Steps to reproduce

![Screenshot 2022-12-19 155846](https://user-images.githubusercontent.com/121068130/208551354-123f238e-2978-464f-9865-6f132ade2b96.png)

### Attachments

![Screenshot 2022-12-19 155846](https://user-images.githubusercontent.com/121068130/208550863-a5ae60b0-48cd-4cdf-b8e5-b4ab0881d1a6.png)

**Comment by Gymnasiast** [comment]
Main executable for OpenRCT2 is not a valid build number. Please fill it in. The form even outlines clearly what it looks like, and the "About OpenRCT2" even provides a button to copy it.
The title "years" is not adequate. Please put something actually descriptive.

We’ll also need a better set of steps to reproduce. Preferably a new save that you made it, say, year 3, that then opens up in year 65.

We need this information to solve your problem, hence why the form ask for it.

**Comment by Timbit1992** [comment]
It’s hard for me to explain it but when I was doing the objective to complete a task within 3 years. So I saved the game and closed the games. A few weeks later i turn on my game and load it, it shows that I failed my objective because it’s year 65. Then I try to do the update… once that was done I try to reload it but it came out to a different map

Sent from my iPhone

On Dec 20, 2022, at 6:10 AM, Michael Steenbeek ***@***.***> wrote:

﻿

Main executable for OpenRCT2 is not a valid build number. Please fill it in. The form even outlines clearly what it looks like, and the "About OpenRCT2" even provides a button to copy it.
The title "years" is not adequate. Please put something actually descriptive.

We’ll also need a better set of steps to reproduce. Preferably a new save that you made it, say, year 3, that then opens up in year 65.

We need this information to solve your problem, hence why the form ask for it.
