### ISSUE TITLE
Theming bug

### ISSUE THREAD

**Issue by HarryDudE64** [OpenRCT2/OpenRCT2#18905]
### Operating System

Windows 10 64x

### OpenRCT2 build

OpenRCT2  0.0.7-a862fbd

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

The Ride Construction Theme doesn't not save, I change the color to black and It changes back to the original brown color

### Steps to reproduce

1. Change Ride Construction Taskbar color to black 
2. Goes to make a ride
3. Taskbar color is brown

### Attachments

![RCT2 bug](https://user-images.githubusercontent.com/121202207/209017181-81e19d2a-0cfb-4748-ab36-d8700bc61f36.jpg)

**Comment by spacek531** [comment]
did you set your current theme to that theme?

**Comment by TheClaudeQC** [comment]
I also experienced this bug!
