### ISSUE TITLE
OpenRCT2's audio object is being exported with .parks

### ISSUE THREAD

**Issue by ZeeMajora** [OpenRCT2/OpenRCT2#18904]
### Operating System

Linux (OpenSUSE Tumbleweed)

### OpenRCT2 build

OpenRCT2, v0.4.3

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

OpenRCT2's audio object (openrct2.audio.additional.parkobj) is being exported with .park files, i noticed this when i opened a park on an install without the audio object present and afterwards the RMC coasters had audio for some reason. After that i checked my objects folder and the openrct2 audio object was extracted there.

### Steps to reproduce

Temporarily remove openrct2.audio.additional.parkobj from your openrct2 installation.
Open the attached park file.
Examine your objects folder, the openrct2 audio object should have been extracted there.

### Attachments

[Forest Frontiersaudiotest.park.tar.gz](https://github.com/OpenRCT2/OpenRCT2/files/10275937/Forest.Frontiersaudiotest.park.tar.gz)

![Screenshot_select-area_20221221032959](https://user-images.githubusercontent.com/42477864/208857523-2deba9e8-9cda-428b-b521-eea62fe648dd.png)

**Comment by duncanspumpkin** [comment]
Caused by object being openrct2 and not official.

https://github.com/OpenRCT2/OpenSoundEffects/blob/master/openrct2.audio.additional/object.json#L8

https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/object/ObjectFactory.cpp#L230
