### ISSUE TITLE
Peeps won't use umbrellas when given them via the cheat if it's raining

### ISSUE THREAD

**Issue by Enzemo** [OpenRCT2/OpenRCT2#1890]
As the title says, if it's raining and you use the cheat to give your peeps umbrellas, they won't use them. They have them, but they won't use them. 

I tried using force thunder too, but they still wouldn't use them. I'm not sure if it's visual, or if the guest's happiness is being affected

**Comment by Gymnasiast** [comment]
Actually, it seems that people put their umbrellas _away_ when it starts raining. Even if you haven't used the cheat.
