### ISSUE TITLE
Visibility of mini golf's station railings depends on view direction

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#18911]
### Operating System

Ubuntu 20.04

### OpenRCT2 build

Uknown #12909

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

Normally, the station platform of the mini golf draws railings on both sides. But, of course, you need a gap in the railings where the entrance and exit are.

But this isn't working quite right. When viewed from two angles, *both* sides of the station platform are missing the railings. When viewed from the other two angles, both sides do have the railings.

Like this:
![Octagon Park 2022-12-21 19-22-00](https://user-images.githubusercontent.com/26573303/209049101-a9b141d0-0356-47c4-a9df-1509ef86f80e.png)
![Octagon Park 2022-12-21 19-21-58](https://user-images.githubusercontent.com/26573303/209049104-e0eeb7d2-179a-41c6-a4a0-0fea3c1df7a3.png)
![Octagon Park 2022-12-21 19-21-57](https://user-images.githubusercontent.com/26573303/209049106-ff35fcab-8724-446e-bfb6-2c14e2bed8f4.png)
![Octagon Park 2022-12-21 19-21-54](https://user-images.githubusercontent.com/26573303/209049108-94b22e40-ddee-4d95-bcca-7714addce0c8.png)

The issue becomes more obvious if you use the 'no entrance' station type:
![Octagon Park 2022-12-21 19-22-14](https://user-images.githubusercontent.com/26573303/209049166-56695739-47b8-4e61-97d8-78c26785ea7b.png)
![Octagon Park 2022-12-21 19-22-13](https://user-images.githubusercontent.com/26573303/209049171-e6cb7de2-717f-4807-984f-bb43b369dd8c.png)
![Octagon Park 2022-12-21 19-22-12](https://user-images.githubusercontent.com/26573303/209049175-864aa3d2-e015-49d5-b9cf-27ba4cddcd44.png)
![Octagon Park 2022-12-21 19-22-11](https://user-images.githubusercontent.com/26573303/209049179-0ae42e9e-b7ee-4091-ab97-011342218a33.png)

To be done correctly, it should *always* omit the railing on the side the entrance or exit is on, and *never* omit the railing on the side across from the entrance/exit.

I think this is a pretty old bug, because I remember having seen oddities in the mini golf station railings for quite a while ... but only recently realized that it actually depends on the view direction, which means it's *definitely* a drawing bug.

### Steps to reproduce

1: Build a mini golf station platform at least 3 tiles long, and place the entrance and exit on the same side of it (not across from each other).
2: (Optional) set the station to 'no entrance' style for better visibility.
3: Rotate the view and pay attention to the railings on the station platform.

**Comment by Gymnasiast** [comment]
Have you been able to check this in vanilla?

**Comment by ocalhoun6** [comment]
No ... I've never gotten vanilla working properly.

**Comment by tupaschoal** [comment]
I tested it on Vanilla and it seems to work just fine:
![SCR2](https://user-images.githubusercontent.com/6443427/209984038-55260aaa-487c-4472-ad95-96e9aea125e3.JPG)
![SCR3](https://user-images.githubusercontent.com/6443427/209984043-1c824f64-faff-402a-87e1-a4cec6cbf1ef.JPG)
![SCR4](https://user-images.githubusercontent.com/6443427/209984044-99e369ff-1c44-4346-9b7c-769c3f141a1f.JPG)
![SCR5](https://user-images.githubusercontent.com/6443427/209984046-056867c3-6820-45ed-8a16-5f16e7d672ca.jpg)
