### ISSUE TITLE
Custom Stalls [feature request]

### ISSUE THREAD

**Issue by runelaenen** [OpenRCT2/OpenRCT2#1894]
I do not know how possible it would be, if at all. Or whether it's actually been done (Feel free to refer me to a link if it has) but a custom stall, no unlike the ones in RCT3 would be a great addition I feel. As much as I like the sprite work for the stalls currently in the game, sometimes just a counter would be nice - much like those in RCT3 where you can choose what the stall sells. Even if it was a much simpler design like the tent-versions of the Lemonade and Candy apple stalls.

https://openrct.net/forum/topic/203/last/custom-stalls

**Comment by IntelOrca** [comment]
You can already make custom stalls, some custom stalls look like vending machines. The only thing you can't do is have custom food / drink / toy items. As they are built in to the game from peep flags to special sprites and plenty of strings to localise.
