### ISSUE TITLE
Clicking Vehicle tab on a Reverser Coaster crashes game

### ISSUE THREAD

**Issue by DejaVu2001** [OpenRCT2/OpenRCT2#18952]
### Operating System

Windows 10

### OpenRCT2 build

v0.4.3-279675b

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Clicking the Vehicle tab on the Ride window for a Reverser Coaster will cause the game to freeze and crash. This issue is limited to the Reverser Coaster track. Putting Reverser cars on other coasters is fine. Additionally, the crash will also occur if you build a different type of coaster, change track type to Reverser Coaster and then click the Vehicle tab

### Steps to reproduce

1. Build Reverser Roller Coaster.
2. Open Ride Window
3. Click Vehicle tab

**Comment by autofire372** [comment]
I'm on the same version, and I could not reproduce this. Do you have custom vehicles for the Reverser installed, perhaps?

**Comment by DejaVu2001** [comment]
Nope, it's the standard Reverser. And again, it is 100% track based, regardless of vehicle type. For example, I can build a Corkscrew coaster with corkscrew trains, and if I change the track type to Reverser and click the vehicle tab the game crashes

**Comment by ocalhoun6** [comment]
Do you have any plugins installed?

**Comment by DejaVu2001** [comment]
Sorry about the delayed response as I was out of town, but I removed all plugins and the crash still occurs

**Comment by spacek531** [comment]
I cannot recreate this on OpenRCT2, v0.4.3-23-g1a761d0 (1a761d0 on develop) provided by GitHub
![image](https://user-images.githubusercontent.com/3454156/210293503-19e42114-d3fa-46e7-9ff0-29393513c54f.png)
