### ISSUE TITLE
Crash when building a new ride

### ISSUE THREAD

**Issue by Gator96100** [OpenRCT2/OpenRCT2#1895]
When I try to place a prebuild ride in multiplayer all other clients crash.
This only happens after you have played some time, when I create a new save it will take a few minutes before this error appears.
With the save that I uploaded this error should be easy to reproduce.
I tried to debug it, but I don't have the time to come up with a fix.
What I got so far is that the ride_set_vehicle_colours_to_random_preset function tries to read a protected/unallocated memory address when trying to access the vehicle_preset_list.
http://www.mediafire.com/download/k1axnmjm0av4k3l/save.sv6

**Comment by PoLoMoTo** [comment]
This happens for me in multiplayer, it seems that the first time it crashes and all subsequent attempts do not register on other clients.

**Comment by RobinFlikkema** [comment]
Also happening here, using Windows 10 on a core i7.

**Comment by duncanspumpkin** [comment]
Fixed in the pre-release. 9be6fb7925f35214d0ef2aefd17583bc3765bcce, 41d4de75a4f13081e38b070fe4e3f77ef197e1b8, 98eb9fda24ea9f8af6641f37dd2896f911c2b54a
