### ISSUE TITLE
Create 60 degree lift sprites for the Wooden RC

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#18975]
These pieces have been remarkable in that they were enabled in RCT1 and (IIRC) vanilla RCT2, but never had proper sprites - RCT1 had ugly, early-beta sprites and RCT2 just used non-lift sprites.

@karst Do you want to take a stab at this?

**Comment by karst** [comment]
Yea I'll see how much I can fix about the RCT1's woodie sprites, and while i am at it i'll probably also fix the same pieces for the ultra twister.

**Comment by Gymnasiast** [comment]
I was thinking that just creating the sprites from the non-lift ones would probably yield a better result.

**Comment by karst** [comment]
I'll probably end up doing that though the rct1 textures will give an easy baseline
