### ISSUE TITLE
Game allows starting new game without prompting for save

### ISSUE THREAD

**Issue by tupaschoal** [OpenRCT2/OpenRCT2#18971]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

v0.4.3

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Describe the issue

If you're playing a park for a while and try to quit the game or load another park, the game nicely asks you if you don't want to save first. If you instead go directly for "new game", it just straight jumps into the new park without asking anything.

### Steps to reproduce

1. Open any park
2. Use hyper speed for a couple seconds to trigger the save fallback
3. Open the menu and request new game on a new park

**Comment by nehemiah-negussie** [comment]
I'd like to take on this bug if possible

**Comment by nehemiah-negussie** [comment]
https://github.com/OpenRCT2/OpenRCT2/pull/19046
