### ISSUE TITLE
Broken translation in korean

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#1898]
The red box is broken strings. I think it occurs since those don't use utf-8.
Is it fixible at now? (Of course I don't think so untill openrct2 becomes independent from the original rct2)

![Error in korean](http://file.telk.kr/rct/img/err_in_korean.png)

**Comment by IntelOrca** [comment]
Please don't combine two issues into one. Use a separate one for the date issue.

**Comment by IntelOrca** [comment]
Can you explain what you mean by broken?

**Comment by telk5093** [comment]
Sorry, I will split it.

Figuratively speeking, something like this:
Right: This is an test string. (Has means)
Broken: Jwha hy ow sltq smwenz. (No means)

Maybe I think that broken string does not support utf-8, but I'm not sure. (It seems that euc-kr)

**Comment by IntelOrca** [comment]
So are all ride names, descriptions, capacities, scenario names and scenario details nonsensical?

**Comment by telk5093** [comment]
For example, belows are broken:
1) Ferris wheel, Hedge maze, Twist, Shop & Stalls's name and descriptions
2) Scenario names and details
3) Scenary item names and window title

But not all of ride names are broken. (Wooden Rollercoaster's name and desc. is not broken)

**Comment by IntelOrca** [comment]
Yep... as I thought, I don't know what codepage RCT2 uses for Korean. So I don't know how to convert the DAT file strings correctly.

However I am nearly finished with my language-dat branch which will allow you to translate all the DAT strings. In the mean time, I will make it use the English strings for objects.

**Comment by IntelOrca** [comment]
Using object and scenario string overrides, this issue can be solved.

**Comment by telk5093** [comment]
Great. Would you mind if I ask you how to do it?

**Comment by IntelOrca** [comment]
Have a look at https://github.com/OpenRCT2/Localisation/blob/master/data/language/dutch.txt as an example.

All the strings for objects are available here:
https://github.com/OpenRCT2/Localisation/wiki/List-of-.DAT-strings

**Comment by telk5093** [comment]
Thanks a lot! :)
