### ISSUE TITLE
Multiplayer servers with more than 63kb worth of remote plugins crash all connecting clients

### ISSUE THREAD

**Issue by Basssiiie** [OpenRCT2/OpenRCT2#18986]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.3-41-gd7c51a0 (d7c51a0 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Remote plugins are distributed by the multiplayer server to any client that joins the server. When a server has more than  60-65kb worth of remote plugins, it does not fit inside the single TCP packet anymore that is used to transmit the plugins, and it crashes any newly connecting client on joining the server.

The crash specifically occurs on [this line](https://github.com/OpenRCT2/OpenRCT2/blob/0ce84204b73c5865053f50af0739ecbb97a105ec/src/openrct2/network/NetworkBase.cpp#L2391), where `packet.Read()` will return `NULL` on arrival of the packet.

Ideally, the plugin packet that big should be split up into multiple packets if necessary.

Thank you for your time.

### Steps to reproduce

1. Create one or more remote plugins that are bigger than 65kb in total size.
2. Start a server with these plugins.
3. Join this server with a client.
4. Experience the game crashing.

**Comment by Gymnasiast** [comment]
In a way, these are two bugs: the game shouldn’t crash in the first place.

**Comment by Basssiiie** [comment]
Actually after further testing; if a server has multiple plugins, all plugins will be send in a single TCP packet so the total sum of plugin sizes cannot exceed ~65kb. So a server with 3 plugins of just 25kb each will still crash, because the total amount will be 75kb.

**Comment by Basssiiie** [comment]
> In a way, these are two bugs: the game shouldn’t crash in the first place.

Bug 1 is that >65kb worth of plugins crash connecting clients. What is bug 2?

**Comment by Gymnasiast** [comment]
Bug 2 is that it cannot accept >65 kB worth of plug-ins.

**Comment by IntelOrca** [comment]
@Basssiiie I think @Gymnasiast is just trying to say that we should first stop it from crashing and instead throw an error like... can't send script file, too large (bug 1). Then actually enable large scripts to be sent (bug 2 / enhancement?). Although both might be fixed together.

**Comment by Gymnasiast** [comment]
That is indeed what I was trying to say. I have no issue with fixing them together by the way, I posted it to outline the problem more clearly.
