### ISSUE TITLE
After enabling master volume, the title music does not start

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#18994]
### Operating System

Ubuntu 22.04

### OpenRCT2 build

4b113987812eb1d3ec3e312b1962159427d731bd

### Base game

RollerCoaster Tycoon 2

### Describe the issue

When you’re in the main menu and you enable the master volume, the sound effects will start but the title music will not.

### Steps to reproduce

See previous section.

**Comment by karst** [comment]
I can reproduce this on Windows 10 64-bit too.

**Comment by Gymnasiast** [comment]
It’s probably very easy to fix, there is code to start ride music and sound effects when the master volume is enabled, it’s probably just a matter of adding one line, possibly guarded by an if (if necessary).
