### ISSUE TITLE
Create `isCompatibilityObject` flag

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#18997]
This is intended for broken objects that are necessary for backwards compatibility. The user will only be able to _de_select them.

Examples:
- The legacy custom music objects - the user should create proper objects that can be bundled with the park
- The ToonTowner brick base block, which lacks the "allowSupports" flag that all base blocks should have. We cannot add it as some parks rely on it. But we can create a replacement object and flag the old, broken one.

**Comment by Broxzier** [comment]
> The ToonTowner brick base block, which lacks the "allowSupports" flag that all base blocks should have. We cannot add it as some parks rely on it. But we can create a replacement object and flag the old, broken one.

Are you talking about the official object? So there would be two versions then, one that blocks and one that does not block supports? What if someone wants to keep using the support-blocking version, should they use an invisible support blocker instead?

**Comment by Gymnasiast** [comment]
> Are you talking about the official object? 

Yep.

> So there would be two versions then, one that blocks and one that does not block supports? 

Exactly. One of those (the broken one) would normally be hidden, unless it was already selected.

> What if someone wants to keep using the support-blocking version, should they use an invisible support blocker instead?

That’s one of the possibilities, yeah, and much better way of doing it too. In the case of this object though, there are hundreds of objects that could be used in the same way, especially since this way of support block generally puts the scenery underground.
