### ISSUE TITLE
Invalid comparison of cur_track_entry_index

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#1902]
`cur_track_entry_index` from `src/ride/track.c`, line 341, is declared as `uint8`, however, it is being compared with explicit value `1000` in line 373, which is too large to fit in `uint8`.

@IntelOrca [says](https://github.com/OpenRCT2/OpenRCT2/pull/1896#discussion_r38875393) this routine might need checking & some cleaning up.

**Comment by IntelOrca** [comment]
This can be tested by creating over 255 track designs for the same ride.

**Comment by janisozaur** [comment]
There's no need, as the comparison is always false. Other things might come up, though.

**Comment by IntelOrca** [comment]
I mean to prove the issue...

**Comment by janisozaur** [comment]
No longer valid as of 755485f
