### ISSUE TITLE
Check if the Steam Overlay is Active on the process, and handle accordingly.

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#1903]
For example, in Portal , if you press Shift+Tab, it will pause the game.

**Comment by IntelOrca** [comment]
Is this possible to do without the Steam API?

**Comment by Phyxion** [comment]
@IntelOrca No, for this the Steamworks SDK is pretty much required.

**Comment by PFCKrutonium** [comment]
We could just always assume it is active, and Shift+Tab pauses the game (And UnPauses it?)

**Comment by Phyxion** [comment]
That's a terrible idea as many people have the steam overlay on other key combinations (me included).

**Comment by PFCKrutonium** [comment]
True, but I am just shooting for Idea's. There must be a way to test for the UI.

**Comment by Phyxion** [comment]
Yes, with the Steamworks SDK. It's easy to implement but it does require the Steamworks redistributables to be shipped, which is not allowed I think unless you have permission to use Steamworks.

**Comment by PFCKrutonium** [comment]
I mean other than using the Steamworks SDK.

**Comment by Phyxion** [comment]
I don't think so. It's probably easier to bind the pause button to the steam overlay combination.

**Comment by PFCKrutonium** [comment]
Which is what I just suggested 11 minutes ago...

**Comment by Phyxion** [comment]
I mean for you to change the shortkey yourself in OpenRCT2 options. If you meant that before than it wasn't clear :)

**Comment by PFCKrutonium** [comment]
Fair enough... It would still need a code modification, since you would need to bind 2 keys to pause...

**Comment by Phyxion** [comment]
Nope, you can already bind two keys to pause ;)

**Comment by PFCKrutonium** [comment]
Can we? I've never tried.

**Comment by Phyxion** [comment]
Yes. Just press two at once and it'll stick just fine.

**Comment by duncanspumpkin** [comment]
Implemented in #2012
