### ISSUE TITLE
[0baacb2] Crash on startup

### ISSUE THREAD

**Issue by trzejos** [OpenRCT2/OpenRCT2#19038]
### Operating System

Windows 11 64-bit

### OpenRCT2 build

OpenRCT2-0.4.3-develop-0baacb2-windows-x64

### Base game

RollerCoaster Tycoon 2

### Describe the issue

OpenRCT2 crashes on start before the title sequence. I've tried with a fresh install of openrct2. The title music plays after selecting your RCT2 installation directory and immediately after the crash happens. Using the 815d349 (previous commit) develop build works fine.

### Steps to reproduce

1. Start the game
2. Crash happens

### Attachments

![image](https://user-images.githubusercontent.com/3720978/210474405-5f6f6d22-fc1d-43c7-96bd-9e89d3859c33.png)
[crash.zip](https://github.com/OpenRCT2/OpenRCT2/files/10341076/crash.zip)

**Comment by Julienscpfan11111** [comment]
I also have the same problem too it appears the version might be broken

**Comment by trzejos** [comment]
Still bugged in 855fe5f

**Comment by 733737** [comment]
game crashes for me also

**Comment by trzejos** [comment]
Fixed in build 6441e64
