### ISSUE TITLE
Game crashes at startup

### ISSUE THREAD

**Issue by Julienscpfan11111** [OpenRCT2/OpenRCT2#19042]
### Operating System

Windows 11 64-bit

### OpenRCT2 build

OpenRCT2 v0.4.3-855fe5f (0baacb2 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

I recently updated to that version and when starting the game it crashes it works fine before this version I don't know what happened please help

### Steps to reproduce

1. Launch OpenRCT2
2. The game crashes instead of starting up

### Attachments

![Screenshot 2023-01-04 120842](https://user-images.githubusercontent.com/118357200/210483686-cbf2bc75-ce6c-4074-9b03-600a115875f0.jpg)

**Comment by TheClaudeQC** [comment]
OpenRCT2-0.4.3-develop-855fe5f have also the issue

**Comment by TheClaudeQC** [comment]
can confirm, crash happened

[Hello.zip](https://github.com/OpenRCT2/OpenRCT2/files/10341451/Hello.zip)

**Comment by Julienscpfan11111** [comment]
everyone probably has this issue so maybe it is a problem on their end lets wait until they fix it

**Comment by Derpercoaster** [comment]
Confirmed for me as well. I'm bored now.

**Comment by Julienscpfan11111** [comment]
it appears this has been fixed
