### ISSUE TITLE
Selecting "Build Custom Design" when building a maze fails to open construction window

### ISSUE THREAD

**Issue by Derpercoaster** [OpenRCT2/OpenRCT2#19053]
### Operating System

WIndows 10

### OpenRCT2 build

OpenRCT2, v0.4.3-70-gc202fd3 (c202fd3 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Selecting "build custom design" when trying to build a maze will fail to open the construction window, meaning custom mazes are impossible at the moment.

### Steps to reproduce

1. Open the new ride tool
2. Select maze
3. Select "build custom design"
4. Construction window fails to open

**Comment by tupaschoal** [comment]
Culprit is #19036
