### ISSUE TITLE
Scrolling doesn't work anymore

### ISSUE THREAD

**Issue by Hypo74** [OpenRCT2/OpenRCT2#19076]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.4.3-85-g6017983 (6017983 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

Issues building the game

### Describe the issue

Hi !

Since the last version of openRCT2, I cannot scroll anymore to increase prices or loan.
![openrct2_nVccQeT5fn](https://user-images.githubusercontent.com/122159876/211152372-894bac27-7faa-48eb-ba72-18753611396d.png)
I used to be able to put my mouse on the amout and scroll to increase/decrease.
This also happens with shops, and basically any prizes.

### Steps to reproduce

1. Open any park
2. Try to increase/decrease loan or a shop's price by scrolling with your mouse. It won't work, but it used to work.

**Comment by Sadret** [comment]
I have the same issue.

**Comment by Broxzier** [comment]
Does it work on other spinners, for example a ride's entry fee, or is it just this spinner that is broken?

**Comment by Sadret** [comment]
I've checked a few spinners and none of them works. The area spinners (size selection for e.g. the land or water tool) that have a similar effect but different design have no issue though.

**Comment by tupaschoal** [comment]
I've bisected and found the issue on #18931
