### ISSUE TITLE
differing release version tag leads to update loop in winget

### ISSUE THREAD

**Issue by markusdd** [OpenRCT2/OpenRCT2#19072]
### Operating System

Windows 11 

### OpenRCT2 build

0.4.3master-285e0fc

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Describe the issue

OpenRCT2 keeps being offered as an avilable update during `winget upgrade --all` as the version key put into the registry differs from the one advertised in Github releases.

### Steps to reproduce

install openrct2 on windows (latest version) and run `winget upgrade --all`.

It will be always marked for update as there is a version mismatch between what is put in the registry and what is advertised here on github (see pic below)

### Attachments

![grafik](https://user-images.githubusercontent.com/25175069/211144863-aeac6c1d-46ec-4577-bea7-18747680c52c.png)

**Comment by markusdd** [comment]
I can try to create a PR to fix this but someone needs to point me to where this is handled, not much experience with creating windows installers and registry entries.

**Comment by janisozaur** [comment]
You want https://github.com/microsoft/winget-pkgs/tree/master/manifests/o/OpenRCT2/OpenRCT2, not us

**Comment by markusdd** [comment]
ok that is confusing, but helpful^^
