### ISSUE TITLE
When loading a vanilla RCT2 save in OpenRCT2, the recent message list behaves incorrectly

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#1909]
When loading a vanilla RCT2 save in OpenRCT2, a new message will simply overwrite the last one in the list, rather than shifting up the entire list and placing the message under it.

![scr112](https://cloud.githubusercontent.com/assets/1478678/9769446/8e05e956-572a-11e5-9c64-dd2c0520bac2.png)
![scr113](https://cloud.githubusercontent.com/assets/1478678/9769448/8e08034e-572a-11e5-8a22-e47de455a2d4.png)
![scr114](https://cloud.githubusercontent.com/assets/1478678/9769458/9d3b10d6-572a-11e5-800c-64508215df48.png)

**Comment by IntelOrca** [comment]
Could you upload a saved game in vanilla with saved messages?

**Comment by Gymnasiast** [comment]
https://www.dropbox.com/s/69cwxj9k9bp0n2j/White%20Water%20Park.SV6?dl=0

**Comment by Kuro-Maii** [comment]
I have seen this occur in ORCT2 0.0.3-build 1193 (5ABB923). I started the "Botany Breakers" park from the "Challenging Parks" tab and was looking at the messages today after loading form a safe. they where all the same with exception of the last, just like the pictures in this issue.
