### ISSUE TITLE
search filters do not update when last character removed from text box

### ISSUE THREAD

**Issue by trzejos** [OpenRCT2/OpenRCT2#19112]
### Operating System

Windows 11 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.3-101-g97c6b8c (97c6b8c on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

When filtering objects in the Object Selection window and tracks in the Track List window, the applied filter is not updated when the text box is updated to an empty string. It may affect other interfaces as well, but I confirmed that it is in the Object Selection window and Track List window for sure.

### Steps to reproduce

1. Open the Object Selection window
2. Enter a single character filter (a good one for demonstration is "q" when in the roller coaster rides tab)
3. Observe that items have been filtered out of the list
4. Press backspace to set your filter string to a blank string
5. Observe that items are still filtered out, even though no text is in the filter text box

### Attachments

![image](https://user-images.githubusercontent.com/3720978/211671266-77e1e9bf-f7d7-4476-9f73-290dcd2c0d98.png)

**Comment by zzril** [comment]
I could reproduce this in the currently latest commit (9c6032bb36e2de8d2e065efdf509def3323cfa47) in the ObjectSelectionWindow in the TrackDesigner. Entering "z" in the filter works fine (reduces the coasters shown to 3 in my installation), but then deleting that letter does not reset the filter. Clicking the "Clear" button instead works fine.

---

The method that is executed when we input/remove a character in the text input field is:  
https://github.com/OpenRCT2/OpenRCT2/blob/9c6032bb36e2de8d2e065efdf509def3323cfa47/src/openrct2-ui/windows/EditorObjectSelection.cpp#L794-L813

When instead clicking the "Clear" button (using the mouse), this gets executed:  
https://github.com/OpenRCT2/OpenRCT2/blob/9c6032bb36e2de8d2e065efdf509def3323cfa47/src/openrct2-ui/windows/EditorObjectSelection.cpp#L421-L427

---

It seems the first `if` check in the `OnTextInput` method is wrong. If `text.empty()` is true, we do not want to return, but reset the filter.  
Removing the `|| text.empty()` part from the condition worked for me (creating a PR for this right now).  
Alternatively, one could refactor the code to have a dedicated `ResetFilter` method that is called both when using the mouse click as well as when removing the last character in the filter string.

**Comment by trzejos** [comment]
I took a look for all instances of `WindowWidgetType::TextBox` in the ui code. The merged PR only addressed the object selection window. Other windows with the same bug include:
- ServerStart (Port, Name, Description, Greeting, and Password text boxes)
- ServerList (Player Name text box)
- TrackList (Search filter text box)
