### ISSUE TITLE
Problems with my Six Flags World of Owl City project.

### ISSUE THREAD

**Issue by MemesRCT** [OpenRCT2/OpenRCT2#19159]
I tried to open my massive theme park project called "Six Flags World of Owl City" but the file refused to load due to invalid data. I can see why I saved the game earlier but ended up crashing it. That issue I'm having doesn't make any sense.
![Failed to load](https://user-images.githubusercontent.com/109612213/212583624-e0e79098-ffdb-4d73-bb73-ee433aa70a7a.jpg)

**Comment by James103** [comment]
1. Can you please zip the park file then attach the resulting zip?
2. What OpenRCT2 version and OS are you running?

**Comment by MemesRCT** [comment]
[Six Flags World of Owl City.zip](https://github.com/OpenRCT2/OpenRCT2/files/10422023/Six.Flags.World.of.Owl.City.zip)

**Comment by James103** [comment]
The game is refusing to load the park file because it is empty (0 bytes).
You can try restoring from a backup or older save if you have one.

**Comment by MemesRCT** [comment]
Nope. I don't have a backup or older save.

**Comment by MemesRCT** [comment]
But I tried to restore the older version but there's none.

**Comment by MemesRCT** [comment]
There we go. I got it fixed.

**Comment by ocalhoun6** [comment]
> There we go. I got it fixed.

For the benefit of anyone else who might have the same problem in the future, how did you fix it?
