### ISSUE TITLE
Bug - Entrance built but still recognized as "not yet built"

### ISSUE THREAD

**Issue by andy55699** [OpenRCT2/OpenRCT2#19152]
### Operating System

windows 8 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.2 (8ceea45) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs, Issues building the game

### Describe the issue

Entrance has been built but the ride cannot be opened and it said "entrance not yet built".

 

Attached please find the park file and image. Thanks!

### Steps to reproduce

Entrance has been built but the ride cannot be opened and it said "entrance not yet built".

 

Attached please find the park file and image. Thanks!

### Attachments

[Bug - Great Wall of China.zip](https://github.com/OpenRCT2/OpenRCT2/files/10420674/Bug.-.Great.Wall.of.China.zip)
![image png b9b0926e5bf8b492fc059c0c473f1bbc](https://user-images.githubusercontent.com/92691705/212554098-fe7dd289-9bd5-433b-affc-b78590ef06fd.png)

**Comment by ocalhoun6** [comment]
Seems like the signs on the entrance building and queue end are using Chinese characters, while the name of the ride in the ride window and all the other text on the screen is English... Maybe that has something to do with it?

**Comment by SendyTheEndless** [comment]
I am having this problem, too. I can confirm, old save files do not have any problems, but starting a new game frequently won't let me test or open rides, complaining that the exit hasn't been built. I am using the latest build, same as the OP.

**Comment by andy55699** [comment]
> Seems like the signs on the entrance building and queue end are using Chinese characters, while the name of the ride in the ride window and all the other text on the screen is English... Maybe that has something to do with it?

Nope coz I have also tested it with full English interface. 

And it's actually a normal situation in non-Latin language interfaces that the signs on the entrance building, queue end and ride window  are using different character

**Comment by nathan-stanton** [comment]
> I am having this problem, too. I can confirm, old save files do not have any problems, but starting a new game frequently won't let me test or open rides, complaining that the exit hasn't been built. I am using the latest build, same as the OP. EDIT: Also, maze construction quits as soon as it starts.
> 
> EDIT: Trying to add a pic. Scuse me, I'm new here! ![Openbug](https://user-images.githubusercontent.com/122756617/212572770-3b34192c-90b7-4001-96d9-cc80c000cd82.jpg)

Just to share I'm having the same issue.

**Comment by jensj12** [comment]
For the rollercoasters, please check whether it has the correct number of stations. See #5244.

**Comment by nathan-stanton** [comment]
Yeah, it's a basic circuit with no block breaks. Just the one station
required, with an entrance, yet the entrance isn't recognised.

**Comment by cseepe** [comment]
I'm also having the same issue; details, save file, and screenshot are in https://github.com/OpenRCT2/OpenRCT2/issues/5244#issuecomment-1513732237

(Posted details in #5244 since it's older and still Open, and adding this comment here in #19152 since it has the most recent activity)

**Comment by ZehMatt** [comment]
> Okay, got some reliable steps to reproduce, as well as a video showing those steps result in a "ghost" station:
> 
> 1. From main menu, start new game, Roaring Twenties - Prison Island
> 2. Close pop-up, find a clearing in the map, open New Ride dialog, select Looping Roller Coaster, build Custom Design
> 3. Place 5 station tiles
> 4. Click Simulate
> 5. Switch to straight, upward, lift hill track
> 6. Place two tiles
> 7. Use the bulldozer button to remove the two tiles
> 8. Close the edit ride dialog box
> 9. Right-click on the frontmost station tile to go back to edit ride mode
> 10. Add one more station tile
> 11. Close the edit ride dialog box
> 12. Check the View tab of the manage ride dialog box
>     a. Observe the drop-down menu now lists two stations
> 13. Add an Entrance and Exit to the station
> 14. Attempt to Test/Open the ride
>     a. Observe you get the message, "Can't test Looping Roller Coaster 1... Entrance not yet built"
> 15. Try completing the track, removing and rebuilding the station, etc., but you'll never be able to Test/Open that ride
> 
> [Alcatraz-BrokenStation2.zip](https://github.com/OpenRCT2/OpenRCT2/files/11336488/Alcatraz-BrokenStation2.zip)
> 
>  NewScenario_CreatingBrokenStation.mp4

Thanks for the detailed steps, I will try to find some time to look into it.

**Comment by ZehMatt** [comment]
Didn't realize this is a duplicate also, see #5244
