### ISSUE TITLE
Linux Appimage: 0.4.3. Audio Objects Not Found

### ISSUE THREAD

**Issue by FifoIronton** [OpenRCT2/OpenRCT2#19160]
### Operating System

Linux (x86-64bit) (tested on Arch and Ubuntu)

### OpenRCT2 build

OpenRCT2, v0.4.3

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

Upon starting the appimage, I see the following error text:
```
user@computer:~/orct2$ ./OpenRCT2-0.4.3-linux-x86_64.AppImage 
Importing legacy shortcuts...
object index out of date
Building object index (2221 items)
Finished building object index in 0.76 seconds.
Object conflict: '/tmp/.mount_OpenRC5MIgYK/usr/bin/../share/openrct2/object/rct2/audio/rct2.audio.base.json'
               : '/tmp/.mount_OpenRC5MIgYK/usr/bin/../share/openrct2/object/rct2/audio/rct2.audio.base.rctc.json'
1 object conflicts found.
```

Upon trying to load a map using these assets, I am immediately sent back to the launcher, with the following error text:
```
[openrct2.music.acid] Object not found.
[openrct2.music.dodgems] Object not found.
[openrct2.music.galaxy] Object not found.
```

I have not tested the most recent nightly release, there is no nightly appimage.

May be related to https://github.com/OpenRCT2/OpenMusic/pull/18 https://github.com/OpenRCT2/OpenMusic/pull/14 https://github.com/OpenRCT2/OpenMusic/pull/15

### Steps to reproduce

1. Download official appimage from [here](https://github.com/OpenRCT2/OpenRCT2/releases/download/v0.4.3/OpenRCT2-0.4.3-linux-x86_64.AppImage)
2. Open scenario editor
3. Select "Load Landscape" and select the attached park file. This park works fine for my friends on Windows

### Attachments

[World.park.zip](https://github.com/OpenRCT2/OpenRCT2/files/10422064/World.park.zip)

**Comment by Gymnasiast** [comment]
The first issue (that doesn’t actually cause problems) affects every build, the latter is indeed a bug in the AppImage.

**Comment by FifoIronton** [comment]
Just built from `develop` and found the same issue. Going to dig a little more
