### ISSUE TITLE
Unable to click ride vehicle or operating tab in track designer

### ISSUE THREAD

**Issue by MisterSchmidt** [OpenRCT2/OpenRCT2#1917]
Yesterday I'd made some tracks in the track designer and wasn't able to click the "Vehicle Details tab" and "Operating option tab" of those rides EXCEPT after clicking the "Colour Scheme tab" first.

I sadly wasn't able to re-create this bug today.

**Comment by Gymnasiast** [comment]
This is usually some sort of corruption of memory. It's hard to find and it's likely this bug is gone in the meantime.
