### ISSUE TITLE
Crackling Audio

### ISSUE THREAD

**Issue by TapDancer36** [OpenRCT2/OpenRCT2#19180]
### Operating System

Windows 11 64 bit

### OpenRCT2 build

OpenRTC v0.4.0 and up

### Base game

RollerCoaster Tycoon 2

### Describe the issue

In openrct version 0.4.0 all the way up to the newest release of 0.4.3 I've had an audio crackling problem. It did not exist in version 3.5.1 and below. When I start up the game the entire audio from the music to the sound effects crackle and sound slowed down.  I've looked into the config file and the settings and no matter what I have done it has not done a thing to alter it.

### Steps to reproduce

The Bug triggered from updating to the newest version of OpenRTC. Any version prior to 0.4.0 has not had the issue

### Attachments

[OpenRCT2 Buggy Video.zip](https://github.com/OpenRCT2/OpenRCT2/files/10430819/OpenRCT2.Buggy.Video.zip)
Two videos showcasing the audio glitch on both the Title Screen and one of my saves

**Comment by ZehMatt** [comment]
What audio format do you have set on your audio device? I'm talking about this window:
![image](https://user-images.githubusercontent.com/5415177/220476559-9c186111-448f-4040-8579-d33d5b26731f.png)

**Comment by Broxzier** [comment]
On inspecting the audio, it seems there are gaps every couple milliseconds. Notice all the flat parts:

![image](https://user-images.githubusercontent.com/9705046/220568022-a2757ff7-c2cb-4c93-9593-90d2c8f5c395.png)

When cutting these all out (manually), the audio seems fine.

**Comment by TapDancer36** [comment]
After running into the issue in another game (Gears of War 5) one solution I saw there was to reinstall the sound drivers I was using. After doing so I booted up the newest version of OpenRCT2 and it was working fine! As for why it happened? I have no idea.

**Comment by ZehMatt** [comment]
> After running into the issue in another game (Gears of War 5) one solution I saw there was to reinstall the sound drivers I was using. After doing so I booted up the newest version of OpenRCT2 and it was working fine! As for why it happened? I have no idea.

Glad you managed to solve the issue.

**Comment by Bilge** [comment]
I have this issue also.
