### ISSUE TITLE
Pressed state of floor/wall buttons in land window not reset upon texture selection

### ISSUE THREAD

**Issue by trzejos** [OpenRCT2/OpenRCT2#19212]
### Operating System

Windows 11 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.3-157-gf14d1e3 (f14d1e3 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

When selecting a floor/wall texture in the land window, the button remains pressed even after the selection is made and the dropdown disappears. They only reset to the unpressed state if the currently selected texture is reselected or if the land window is closed and reopened. This behavior is unexpected given that texture selection is not a toggleable option like mountain/paint mode are. The image displayed on the button changing is enough to demonstrate that a selection has been made.

### Steps to reproduce

1. Open the land window (either in game or in scenario editor)
2. Change either the floor or wall texture
3. Observe that the floor/wall button is stuck in a pressed state

### Attachments

![image](https://user-images.githubusercontent.com/3720978/213144072-b8e6a73d-7153-48c1-9935-39b835869238.png)

**Comment by Broxzier** [comment]
But it is a toggleable option, they just also have a dropdown to choose a style unlike the slope and paint buttons. The terrain style and edge style will only change when the surface-button and edges-button are pressed, respectively.

**Comment by trzejos** [comment]
mind blown
