### ISSUE TITLE
.park scenarios don't complete properly

### ISSUE THREAD

**Issue by autofire372** [OpenRCT2/OpenRCT2#19243]
### Operating System

EndeavourOS

### OpenRCT2 build

OpenRCT2, v0.4.3-180 (cf9aad788 on develop)

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Completing a .park scenario doesn't allow the player to register their name, thus it is never marked as completed on the scenario list.

### Steps to reproduce

1. Extract contents of attached zip file to OpenRCT2's data directory (contains  an easily completed .park scenario and a save from just before completion) 
2. Start OpenRCT2, and open the save "Test Park0"
3. Save starts paused; unpause and let the scenario auto-complete

### Attachments

[TestPark.zip](https://github.com/OpenRCT2/OpenRCT2/files/10472541/TestPark.zip)

**Comment by SpartanFrederic104** [comment]
This also happens with .park versions of .sc6 scenarios, except this time the .sc6 scenario is the one that gets marked as completed.

**Comment by MarHelmer** [comment]
Just chiming in to say that this issue is not resolved.  I have many custom scenarios (Fred's scenario pack!) and only the .SC6 scenarios register completion.  All .PARK scenarios fail to register completion.
