### ISSUE TITLE
"Unknown custom action" popup during play and assertion failure upon exit

### ISSUE THREAD

**Issue by AnonTheMoose** [OpenRCT2/OpenRCT2#19250]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.3-184-ge09f27d (e09f27d on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Periodic "Unknown custom action" popup, "Assertion failed, 5 images were not freed" error on exit

### Steps to reproduce

1. Begin new game or open any saved game
2. "Unknown custom action" popup occurs every few seconds of play
3. Game crashes when exiting OpenRCT2

### Attachments

[0c6082eb-408e-48a5-a792-b8a3b75949fc(4281914_x86-64).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/10473136/0c6082eb-408e-48a5-a792-b8a3b75949fc.4281914_x86-64.dmp.gz)
![Screenshot 2023-01-21 164001](https://user-images.githubusercontent.com/108583978/213888080-8d72e396-76b3-4a62-82ee-7901002fed51.png)
![Screenshot 2023-01-21 164017](https://user-images.githubusercontent.com/108583978/213888094-e2ba87b0-83d9-4880-b95b-12cb527cced5.png)
![Screenshot 2023-01-21 164033](https://user-images.githubusercontent.com/108583978/213888101-aad0a248-02df-4c0d-a590-f80e41f03bb9.png)

**Comment by James103** [comment]
Do you have any plug-ins enabled? If so, can you please try disabling them (e.g. by renaming the `plugin` folder)?

**Comment by AnonTheMoose** [comment]
I have several plugins. I will try renaming the folder and see if it works.
Before I started playing, I added a music PARKOBJ using GOES Music Creator. I have added music files manually before with no issue, but the problem first occured when I used GOES. However, when I deleted the added PARKOBJ file, the issue persisted.

**Comment by AnonTheMoose** [comment]
Tried after renaming the plugin folder. "Unknown custom action" error stopped, but "Assertion failure" upon exit still occurs.

**Comment by AnonTheMoose** [comment]
![Screenshot 2023-01-21 164853](https://user-images.githubusercontent.com/108583978/213888276-f0876c30-4b97-41e7-8ee7-c1b49c901e4d.png)

**Comment by trzejos** [comment]
This is the assertion failure I get in the debug log (on ba39d7be5)
```
An assertion failed, please report this to the OpenRCT2 developers.
Version: OpenRCT2, v0.4.3 (, DEBUG)
5 images were not freed
openrct2 $ Assertion failed: false, file D:\projects\OpenRCT2\src\openrct2\core\Guard.cpp, line 159
```

**Comment by trzejos** [comment]
Looks like this was introduced in 09b1074d083e3afd3ea97eb7e5613553acbdd87c
