### ISSUE TITLE
Gameplay occasionally stutters at a steady pace

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#19269]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.4.3-200-g538b87e

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

While playing today, I noticed that RCT2 would suddenly freeze and unfreeze every couple of seconds. Audio would continue to play, though the game would be unresponsive and inputs wouldn't be recognized.

### Steps to reproduce

1. Open the game
2. Watch the demo or start a new game- notice the occasional pauses on screen and moments where mouse/keyboard inputs do not register.

**Comment by ZehMatt** [comment]
What renderer are you using? Also does this happen while you just wait around without moving the camera or does this primarily happen when you move the view? Also some hardware information would be helpful, like do you run your OS on an SSD/NVMe?

**Comment by Superjustinbros** [comment]
It happens at all times.
As for hardware, here's what I'm running the game with:

Processor: 12th Gen Intel(R) Core(TM) i9-12900K   3.20 GHz
RAM: 32GB installed
System type: 64-bit operating system, x64-based processor

I haven't checked yet but I assume it is SSD.

**Comment by ZehMatt** [comment]
Are the freezes happening within a specific interval or is it randomly happening? Also do you have any plugins installed? If you do then try disabling all of them.

**Comment by Superjustinbros** [comment]
> Are the freezes happening within a specific interval or is it randomly happening? Also do you have any plugins installed? If you do then try disabling all of them.

It happens within a specific interval, I counted every 4 seconds or so. As for plugins I do not have any installed and de-checked the game's preinstalled asset packs.

I should note that a few weeks ago on this same PC, I was not running into this issue, and I have no idea what I could have done or updated on my PC that would have affected OpenRCT2.

**Comment by ocalhoun6** [comment]
When's the last time you restarted your PC? Sometimes stuff like that can happen if it hasn't been rebooted in a long time.

**Comment by ZehMatt** [comment]
I've tried to reproduce this on my end and I don't see any stutters, as the previous commenter pointed out this might be due to your environment and not a specific issue to OpenRCT2.

**Comment by Superjustinbros** [comment]
Turns out it was an issue with a controller that I had connected into my computer via USB- an 8Bitdo Pro 2 controller to be exact. I unplugged it and everything returned to normal.

**Comment by ZehMatt** [comment]
Glad you figured it out
