### ISSUE TITLE
Potential memory leak in src/openrct2/core/Zip.cpp

### ISSUE THREAD

**Issue by icy17** [OpenRCT2/OpenRCT2#19279]
Potential memory leak in [Zip.cpp](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/core/Zip.cpp#L170) line 170. Calling zip_source_buffer() without calling zip_source_free() to free the memory will cause a memory leak. [Doc](https://libzip.org/documentation/zip_source.html) says "[zip_source_free(3)](https://libzip.org/documentation/zip_source_free.html) only needs to be called when these functions ([zip_add, zip_replace](https://libzip.org/documentation/zip_add.html)) return an error."
![image](https://user-images.githubusercontent.com/39425646/214765750-c312fde9-9555-49ea-8b95-29c35f8906f7.png)

**Comment by IntelOrca** [comment]
@icy17 are you able to fix this and create a pull request?
