### ISSUE TITLE
Switching to Dutch crashes the game

### ISSUE THREAD

**Issue by runelaenen** [OpenRCT2/OpenRCT2#1928]
https://openrct.net/forum/topic/212/i-think-the-last-development-build-cant-be-launched

It only happens when starting to or switching to Dutch.
@Gymnasiast, I guess you might know more about this?

**Comment by Gymnasiast** [comment]
Look, I have already said I don't get the issue; OpenRCT2 opens fine, using self-compiled or OpenRCT2.com builds.

**Comment by runelaenen** [comment]
It doesn't work with a openrct2.com build. I've tested that first before opening the issue to be sure.

**Comment by JarnoVgr** [comment]
Can confirm this bug (tested installer and ZIP buildno. 1233) on native Windows.

**Comment by JarnoVgr** [comment]
Bug is introduced in build 1223 actually: https://openrct2.com/download/1223
Changes in this build: https://github.com/OpenRCT2/OpenRCT2/compare/72b153115b5e3e38b0df78b1df81c2769d342cf9...85bbdde056fd0c905ab509baf11ab3e5910d668b

**Comment by Gymnasiast** [comment]
Works for me. Tried it with an OpenRCT2.com build, an OpenRCT.net build and an own build. Seems to be affecting Windows only. I would say the bug is elsewhere and only triggered by dutch.txt using recently added capabilities.

**Comment by JarnoVgr** [comment]
Just a guess: newline problems in dutch.txt?

**Comment by Gymnasiast** [comment]
I doubt that. I have edited the file in the same way as I did before.

**Comment by JarnoVgr** [comment]
It must be something related to the dutch.txt since that was the only change between the 2 builds. 

Addition of the DAT translations is probably it. (still just a guess though)

**Comment by Gymnasiast** [comment]
My guess is that the file is merely triggering a bug in OpenRCT2's new translations capabilities. I doubt the file _itself_ is at fault.

**Comment by runelaenen** [comment]
Why is it only affecting dutch.txt then? :/

**Comment by JarnoVgr** [comment]
Well that is a thing for sure Gymaniast, especially because it's only triggered on Windows. Says more about the implementation indeed.

**Comment by Gymnasiast** [comment]
@Rune: Because Dutch is the only language to use the system extensively, not counting one entry in English? I have explained that *two* times now. Pay attention.

**Comment by IntelOrca** [comment]
I get the error, and I have done before but only occasionally - but now it seems deterministic. There is an error when trying to reallocate a memory block - probably because something is writing to out of bounds memory.
