### ISSUE TITLE
Opening a tracked Boat Hire will crash the game

### ISSUE THREAD

**Issue by Sarsey** [OpenRCT2/OpenRCT2#1934]
When I open a Boat Hire with tracks all the way round, it crashes the game. without tracks it's just fine.

**Comment by ianelletson** [comment]
Can confirm. Just happened to me and came to github to see if it was known.

**Comment by janisozaur** [comment]
Can you provide steps to reproduce?

**Comment by Patrik356b** [comment]
Build a boat hire with a complete track
![crash](http://puu.sh/kd96c/cfffd77860.png)

Opening a tracked boat hire where the track is not complete works just fine:
![ok](http://puu.sh/kd8Vk/da6cda5f9a.png)

**Comment by janisozaur** [comment]
Close fixed by #1945
