### ISSUE TITLE
Unplayable OpenRCT2 game crashes on startup

### ISSUE THREAD

**Issue by Julienscpfan11111** [OpenRCT2/OpenRCT2#19361]
### Operating System

Windows 11 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.3-241-g1dfbb5f (1dfbb5f on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

This happened last time but it is happening again the game crashes at startup

### Steps to reproduce

1 Open the game
2 The game crashes

### Attachments

<img width="902" alt="image" src="https://user-images.githubusercontent.com/118357200/218231815-4eca0041-8111-4e35-a8d7-3ae6a85d8e23.png">

**Comment by Julienscpfan11111** [comment]
here is the crash dump https://drive.google.com/drive/folders/1sRIE9u5UEk3ChlUWwXZZXUSrkkweswGP?usp=sharing

**Comment by James103** [comment]
Try placing these files (in the attached ZIP) into the `sequence` folder in your OpenRCT2 directory.
If this prevents the crash, this issue is most likely a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/19353.
[sequence.zip](https://github.com/OpenRCT2/OpenRCT2/files/10712324/sequence.zip)

**Comment by Julienscpfan11111** [comment]
Should I place the crash files on the sequence.zip folder?

**Comment by Julienscpfan11111** [comment]
What files shall I place in the sequence folder?

**Comment by Julienscpfan11111** [comment]
Do I place the files in the crash folder into the sequence folder?

**Comment by Julienscpfan11111** [comment]
this has been fixed with the new dev build
