### ISSUE TITLE
Non-host in multiplayer cannot build two track pieces in a row

### ISSUE THREAD

**Issue by michiel2304** [OpenRCT2/OpenRCT2#1939]
When, as a non host player in a multiplayer game you cannot build more then 1 track piece in a row. You have to right click on the last track piece to be able to place a track piece again.

**Comment by Gymnasiast** [comment]
Can confirm.

**Comment by pizza2004** [comment]
Yeah, my friend has been complaining about this one for a bit.  It's by far the biggest hurdle for it being playable to him it seems.

**Comment by LetsRepaintIt** [comment]
Same here. It doesn't work properly, you have to keep on clicking.

**Comment by code-mc** [comment]
Same here, right clicking last build track piece is a working but tedious solution haha.
