### ISSUE TITLE
invisible paths still cause random sprites to appear

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#19398]
The invisible pathing feature still causes random sprites to appear upon loading a save game. My proposal is to replace these objects with a transparent footpath object, instead of a corrupt element there would be a footpath but it would use transparency so it would still be invisible. I am currently working on implementing this

**Comment by 733737** [comment]
whichever way it is addressed, I will be happy. I have also been told by others that they share your sentiment that it is better to address the root cause than to implement a workaround. At the same time, I feel that my method would guarantee a glitch free experience even after the cause is fixed, for peace of mind, while adding almost nothing to the download size of the game.

**Comment by spacek531** [comment]
> ![unknown](https://user-images.githubusercontent.com/94884086/192944639-840afb6b-4a57-4d37-999d-0e3cef40d5d9.png)

Can you send me this park file @733737

**Comment by 733737** [comment]
sadly, that was posted months ago on discord by another user, I don't have that parkfile

**Comment by spacek531** [comment]
Repro steps for this bug, provided by another user using Windows 7 and OpenRCT2, v0.4.3-313-g0da9693 (0da9693 on develop) provided by GitHub

1. select the OpenRCT2 official invisible path (not queue)
2. build a 3x3 path island
3. the middle path has a bad sprite

![image](https://user-images.githubusercontent.com/3454156/222634389-3946a374-d2f1-4093-be47-6feee6704b91.png)

**Comment by spacek531** [comment]
Did the object download get updated too? People are reporting this still happens.
