### ISSUE TITLE
Footpath Railing not Exporting with save game

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#19430]
### Operating System

Windows 11 Pro

### OpenRCT2 build

OpenRCT2, v0.4.3-281-gf526510 (f526510 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Custom Footpath Railing not exported with save game

### Steps to reproduce

It is important to note that the object in question is wrongly described as "openrct2 official" in the json. If it is intended behaviour to block exporting of official objects through save games, then please close this issue promptly.

### Attachments

![image](https://user-images.githubusercontent.com/94884086/219829196-df1dbce0-4c62-48b5-a636-466fdef1bd1e.png)

**Comment by karst** [comment]
This works as intended.
openrct2 official objects will not be exported with the park as they get included when downloading the game taking up unnecessary space.

**Comment by Gymnasiast** [comment]
Indeed, if you create your own objects, make sure not to mark them as official. Make sure the source game is either set to `"custom"` or left out altogether (in which case it will default to "custom"). This is one of the reasons why.
