### ISSUE TITLE
Placing Handyman/Security Guard/Mechanic In Multiplayer Causes Crash

### ISSUE THREAD

**Issue by PoLoMoTo** [OpenRCT2/OpenRCT2#1943]
Placing a new worker in Multiplayer causes the game to crash the first time, subsequently it does work, albeit buggy.

**Comment by pizza2004** [comment]
I don't know if #1967 is related to this at all or not, but it does seem like this mainly only happened on the client side and not the server side, from what I remember when my friend was playing with me.  It could be that this has changed since the last time we played Multiplayer together though.

**Comment by PoLoMoTo** [comment]
That issue is definitely related as it does seem that in addition to the client crashing the first time even after you are able to place the worker the server doesn't seem to actually recognize it.  Another thing to note is that when the worker does get placed the window with the camera on him is actually on a random peep and the title bar is the name of the peep not the mechanic if that makes sense.

**Comment by IntelOrca** [comment]
These symptoms are more likely just because its desynchronised. The bug is the game desynchronises (with stay_connected off) when you try to place staff or pick up anyone.

**Comment by FlukiestEmperor** [comment]
Adding to what @PoLoMoTo said, if there are no guests in the park, it will just bring up a blank guest window and trying to move it will crash the game.

![bug](https://cloud.githubusercontent.com/assets/1393110/10871839/d8ddca18-80b8-11e5-9b0e-5380be501e6f.PNG)

Also, placing new staff no longer causes the game to crash. Instead, if either the client or server tries to place staff, the change is not reflected on any other client. This means that the server is the only one who is actually able to place staff properly.
