### ISSUE TITLE
Remove Unused Objects does not remove Footpath Railing Selection

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#19434]
### Operating System

Windows 11 Pro

### OpenRCT2 build

OpenRCT2, v0.4.3-281-gf526510 (f526510 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

using remove_unused_objects did not remove my invisible footpath railings although sadret's scenery manager plugin found zero instances of it in park and when I went to object selection, I only had to uncheck it in order to remove it from my park

**Comment by Gymnasiast** [comment]
This is a bug. The command hasn’t been updated to handle the new object types we introduced.
