### ISSUE TITLE
There are hardcoded values which should be constants in `EditorObjectiveOptions.cpp`

### ISSUE THREAD

**Issue by James103** [OpenRCT2/OpenRCT2#19455]
### Operating System

Windows

### OpenRCT2 build

4e45c0176c40fae8034e2dba47b6422f8a43780a

### Base game

RollerCoaster Tycoon 2

### Describe the issue

There are several hardcoded values which could be moved to constants in `EditorObjectiveOptions.cpp`.

Constant name: `ObjectiveMaxCurrency`
https://github.com/OpenRCT2/OpenRCT2/blob/4e45c0176c40fae8034e2dba47b6422f8a43780a/src/openrct2-ui/windows/EditorObjectiveOptions.cpp#L437
https://github.com/OpenRCT2/OpenRCT2/blob/4e45c0176c40fae8034e2dba47b6422f8a43780a/src/openrct2-ui/windows/EditorObjectiveOptions.cpp#L448

Constant name: `ObjectiveMaxLength`
https://github.com/OpenRCT2/OpenRCT2/blob/4e45c0176c40fae8034e2dba47b6422f8a43780a/src/openrct2-ui/windows/EditorObjectiveOptions.cpp#L459

Constant name: `ObjectiveMaxExcitement`
https://github.com/OpenRCT2/OpenRCT2/blob/4e45c0176c40fae8034e2dba47b6422f8a43780a/src/openrct2-ui/windows/EditorObjectiveOptions.cpp#L470

Constant name: `ObjectiveMaxGuests`
Will be taken care of in https://github.com/OpenRCT2/OpenRCT2/pull/19454

---

Constant name: `ObjectiveMinCurrency`
https://github.com/OpenRCT2/OpenRCT2/blob/4e45c0176c40fae8034e2dba47b6422f8a43780a/src/openrct2-ui/windows/EditorObjectiveOptions.cpp#L501
https://github.com/OpenRCT2/OpenRCT2/blob/4e45c0176c40fae8034e2dba47b6422f8a43780a/src/openrct2-ui/windows/EditorObjectiveOptions.cpp#L512

Constant name: `ObjectiveMinLength`
https://github.com/OpenRCT2/OpenRCT2/blob/4e45c0176c40fae8034e2dba47b6422f8a43780a/src/openrct2-ui/windows/EditorObjectiveOptions.cpp#L523

Constant name: `ObjectiveMinExcitement`
https://github.com/OpenRCT2/OpenRCT2/blob/4e45c0176c40fae8034e2dba47b6422f8a43780a/src/openrct2-ui/windows/EditorObjectiveOptions.cpp#L534

Constant name: `ObjectiveMinGuests`
https://github.com/OpenRCT2/OpenRCT2/blob/4e45c0176c40fae8034e2dba47b6422f8a43780a/src/openrct2-ui/windows/EditorObjectiveOptions.cpp#L545

---

Constant name: `ObjectiveMaxYear`
https://github.com/OpenRCT2/OpenRCT2/blob/4e45c0176c40fae8034e2dba47b6422f8a43780a/src/openrct2-ui/windows/EditorObjectiveOptions.cpp#L560

Constant name: `ObjectiveMinYear`
https://github.com/OpenRCT2/OpenRCT2/blob/4e45c0176c40fae8034e2dba47b6422f8a43780a/src/openrct2-ui/windows/EditorObjectiveOptions.cpp#L573

### Steps to reproduce

Read https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2-ui/windows/EditorObjectiveOptions.cpp and notice the above values are hardcoded and not pulled from constants defined near the top of the file.

### Attachments

Originally found whilst reviewing https://github.com/OpenRCT2/OpenRCT2/pull/19454

**Comment by Gymnasiast** [comment]
This could be combined with creating a game action for setting the objective. This is not a requirement, however.

**Comment by knoxy5467** [comment]
This should be complete now

**Comment by toadkarter** [comment]
Is this something that is still needed, in which case I can have a look at implementing? As far as I can see only `MaxObjectiveGuests` uses a constexpr at the top of the file.

**Comment by tupaschoal** [comment]
> Is this something that is still needed, in which case I can have a look at implementing? As far as I can see only `MaxObjectiveGuests` uses a constexpr at the top of the file.

It is still needed @toadkarter. @knoxy5467 made a PR #19579 but it went stale, there's not a lot left to do, I suggest you pick up from there.

**Comment by toadkarter** [comment]
> > Is this something that is still needed, in which case I can have a look at implementing? As far as I can see only `MaxObjectiveGuests` uses a constexpr at the top of the file.
> 
> It is still needed @toadkarter. @knoxy5467 made a PR #19579 but it went stale, there's not a lot left to do, I suggest you pick up from there.

Lovely, thanks! I will give this a whirl shortly.
