### ISSUE TITLE
Compilation fails without internet access, breaking PPA builds

### ISSUE THREAD

**Issue by qwertychouskie** [OpenRCT2/OpenRCT2#19466]
https://github.com/OpenRCT2/OpenRCT2/pull/19247 breaks compilation on systems without full internet access, including the PPA builds (https://code.launchpad.net/~openrct2/+recipe/openrct2-nightly), as Launchpad doesn't allow build runners full Internet access. A graceful fallback in the event of no Internet access during compilation should be added.

**Comment by 733737** [comment]
please use the issue template going forward

**Comment by qwertychouskie** [comment]
My inbox keeps getting flooded with build failure notifications from Launchpad, hopefully this can be resolved soon :)

**Comment by janisozaur** [comment]
same - i'll try addressing this soon (tomorrow/Monday). This will probably require updating the [other repository](https://github.com/janisozaur/openrct2-objects) with unpacked objects and ensuring the recipe overlay is synced.

**Comment by janisozaur** [comment]
created https://github.com/janisozaur/openrct2-openmusic and extracted data from https://github.com/OpenRCT2/OpenMusic/releases/tag/v1.0.1, created https://code.launchpad.net/~openrct2/openrct2/+git/openrct2-openmusic as import of the github repository, updated recipe to nest those objects as well.

In theory this should be sufficient to address this issue, but cannot confirm due to github->launchpad import not getting executed right now. The import is "scheduled to run as soon as possible".

**Comment by qwertychouskie** [comment]
Now building the source package is broken:
```
gitbuildrecipe.recipe.TargetAlreadyExists: /home/buildd/build-RECIPEBRANCHBUILD-3503894/chroot-autobuild/home/buildd/work/tree/recipe/data/ already exists, but has no .git directory.
```
It seems like there is some sort of conflict layering the repositories?

**Comment by janisozaur** [comment]
Finally, this is fixed.

For future reference:
1. created new repository with all the assets combined: https://github.com/janisozaur/openrct2-unpacked-data
2. the assets are in format directly embeddable in `data/` (read: no top-level `data/` directory in said repo)
3. created launchpad import of said repository: https://code.launchpad.net/~openrct2/openrct2/+git/openrct2-unpacked-assets
4. modified recipe to migrate from `nest` to `merge`
5. implemented https://github.com/OpenRCT2/OpenRCT2/pull/19542

The recipe as it looks currently:
```
# git-build-recipe format 0.4 deb-version {debupstream}-0~{revno}-{time}-g{git-commit}
lp:openrct2 develop
merge unpacked lp:~openrct2/openrct2/+git/openrct2-unpacked-assets main
```
