### ISSUE TITLE
Can't increase loan when having a debt of more than 1000

### ISSUE THREAD

**Issue by MASHzj** [OpenRCT2/OpenRCT2#19475]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.4.3-286-gef25274 (ef25274 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

When I try to increase my loan (by clicking on the plus-button), the message "Can't pay back loan! Not enough cash available!" pops up when I have a cash debt of more than €1000. When below 1000, it works fine. This is the same message when trying to lower my loan (minus-button). I assume that the game checks in both cases if the cash amount after the action is positive, while this should only happen when trying to lower the loan. Increasing the loan should only be impossible when the maximum loan is reached.

### Steps to reproduce

1. Get a debt of more than 1000 (easy to accomplish in one of the RCT1 real parks, or with cheats)
2. Go to your financial summary
3. Click on the "+"-button next to the loan

### Attachments

![2023-02-23](https://user-images.githubusercontent.com/121574637/221045679-effa747e-5174-42c7-bde8-2a56ac6feb64.png)

**Comment by Gymnasiast** [comment]
I’ll look into this.
