### ISSUE TITLE
Maze walls being modified by maze entrances/exits

### ISSUE THREAD

**Issue by kiwipxl** [OpenRCT2/OpenRCT2#1947]
There seems to be an issue when mazes are being built. The first one is when an entrance or an exit is placed down, the maze walls are modified (which you can see in the images below). I don't know if this is in the original RCT, but it seems to cause peeps to get stuck in walls at the entrance.

Here's an example of a test maze.
![orct_maze_bug1](https://cloud.githubusercontent.com/assets/4355075/9981275/76aba9f0-5ffc-11e5-954b-61a0d5af1f1b.png)

An exit is then added (the walls are modified automatically).
![orct_maze_bug2](https://cloud.githubusercontent.com/assets/4355075/9981277/88bafba0-5ffc-11e5-815e-f90c619d181e.png)

When you hover an entrance or exit near a maze like such...
![orct_maze_bug3](https://cloud.githubusercontent.com/assets/4355075/9981280/8f28139c-5ffc-11e5-9115-8b951b3e3e22.png)

It also modifies the wall. Peeps then walk into the walls and get stuck.
![orct_maze_bug4](https://cloud.githubusercontent.com/assets/4355075/9981281/92eeebb8-5ffc-11e5-9482-8bfd7f331b45.png)

Here's also an image of peeps getting stuck in the walls at the entrance. I think they sometimes spawn there and sometimes just walk into it.
![orct_maze_bug5](https://cloud.githubusercontent.com/assets/4355075/9981282/95840f34-5ffc-11e5-8f8e-bccc5760cde9.png)

Sorry if these are two different issues, they just seem to be related. Please notify me if you'd like me to separate them.

**Comment by Patrik356b** [comment]
outer walls shouldn't be removed also.
