### ISSUE TITLE
Non-host can't change ride fees

### ISSUE THREAD

**Issue by code-mc** [OpenRCT2/OpenRCT2#1948]
[MULTIPLAYER]

When in multiplayer a non-host player attempts to change a ride's admission fee, the game spits out a ~~"Can't rename ride/attraction"~~ error based on the last action and for the host it displays ~~"Can't open"~~ also just an error based on last action.

**Comment by pizza2004** [comment]
It gives a different error ever time based on what the last action each player did I believe.  I can definitely confirm this bug.
