### ISSUE TITLE
RCT1 fence gate walls not imported properly if they were placed on slopes.

### ISSUE THREAD

**Issue by ZeeMaji** [OpenRCT2/OpenRCT2#19494]
### Operating System

Linux (OpenSUSE Tumbleweed)

### OpenRCT2 build

OpenRCT2, v0.4.3

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error, This issue has to do with park objects and/or asset packs

### Describe the issue

RCT1 allowed you to place the gate variants of walls on slopes, it would just show the non-gate versions of the sprites.
With the sole exception of the creepy wall's gate variant which has completely unique slope sprites that don't seem to be in RCT2.
RCT2 however implemented a flag that allows walls to not be placeable on slopes and thus the duplicate sloped sprites were removed from the gate varients of walls.
However this is an issue as if you load an RCT1 park in OpenRCT2 that has any gate wall variants placed on slopes they will be invisible.

### Steps to reproduce

1. Open the attached sv4 file
2. The fence gate walls are invisible rather than using the non-gate version's sprites

### Attachments

RCT1:
![Screenshot_select-area_20230226035122](https://user-images.githubusercontent.com/42477864/221401171-51347bb0-48c0-46bf-940b-ecbab8a917f8.png)
OpenRCT2:
![Screenshot_select-area_20230226035137](https://user-images.githubusercontent.com/42477864/221401172-e2efb404-e208-48bf-b199-32f851fb1856.png)
Save:
[gatesRCTOA  Acres.SV4.tar.gz](https://github.com/OpenRCT2/OpenRCT2/files/10833301/gatesRCTOA.Acres.SV4.tar.gz)

**Comment by Gymnasiast** [comment]
Adding references to the missing images is easy, what I'm not sure about is whether we should enable the user to place them on a slope or not. Perhaps a team member could weigh in here.

**Comment by ZeeMajora** [comment]
Isn't the slopes placing flag needed for the images to display properly? If not then it'd probably make sense to just leave it disabled as they only need to display properly when loading rct1 parks so not being able to place them on slopes afterwards is fine.
The tricky one is the creepy gate, as it has images that are completely unique to RCT1. I even checked the RCT2 dat for it and they're not there.
Perhaps that is compatibility object territory?

**Comment by 733737** [comment]
why can't we change rct2 to allow these fences to be sloped? I am sure many people would be happy to use more sloped fences, especially for the diagonal angled fence trick.

**Comment by ZeeMajora** [comment]
Like i said, the only one with unique graphics is the creepy gate fence, the rest are just completely identical to their non-gate counterparts when placed on slopes.

**Comment by 733737** [comment]
so you are saying that the creepy sloped gate is the only candidate for import as an official object, since the other gates aren't unique and add nothing other than metadata?
