### ISSUE TITLE
Coaster Data not generated like issue https://github.com/OpenRCT2/OpenRCT2/issues/4695

### ISSUE THREAD

**Issue by knuddelz** [OpenRCT2/OpenRCT2#19528]
### Operating System

Windows 10 64bit

### OpenRCT2 build

RCT2

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

The bug also exists in the original game (RCT2/RCTC)

### Describe the issue

S: Windows 10

Can't seem to get test results on anything I build since this morning on the latest version (https://github.com/OpenRCT2/OpenRCT2/commit/7005d5dca1785701126e7810f670b7ada33d25ef).

Some rides that have been testing in this save have test results, and others refuse to show results. In the cast of coasters, the excitement/intensity/nausea doesn't appear.

Only noticed in single player so far.

### Steps to reproduce

Coaster Gleismeer is not runing properly

**Comment by knuddelz** [comment]
[Extreme Höhen.zip](https://github.com/OpenRCT2/OpenRCT2/files/10858784/Extreme.Hohen.zip)

**Comment by Gymnasiast** [comment]
"RCT3" is not a valid OpenRCT2 build. Please fill in this information.

**Comment by knuddelz** [comment]
sorry for the wrong kind of linking, demolishing does not help or an removal.

**Comment by sjoerddebruin** [comment]
Fixed with #19683, confirmed with save file.
