### ISSUE TITLE
Hiring more than 32767 of a single staff causes negative numbers on staff screen

### ISSUE THREAD

**Issue by KingCatto** [OpenRCT2/OpenRCT2#19545]
### Operating System

Windows 11 pro 64bit

### OpenRCT2 build

OpenRCT2, v0.4.3-344-ga018cb1 (a018cb1 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

after hiring 32768 of a single staff type it overflows into negatives. 
![image](https://user-images.githubusercontent.com/14980812/222774748-50f8d330-e195-487a-b5f8-c0a7d8f77962.png)

### Steps to reproduce

Open the park file attached for quicker to reproduce.

1. hire 32768 staff
2. observe number under staff screen

### Attachments

[Forest Frontiers HOLY STAFF.zip](https://github.com/OpenRCT2/OpenRCT2/files/10884189/Forest.Frontiers.HOLY.STAFF.zip)

**Comment by KingCatto** [comment]
also another side effect of this you cannot scroll after it reaches that negative number.

**Comment by ZehMatt** [comment]
I believe the scroll issue should have been fixed, maybe there is something else that lingers as int16_t, as for the wrong text thats probably the wrong string format in the localisation again.
