### ISSUE TITLE
Can't build pre-build design outside park when sandbox mode is enabled.

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#1954]
Should be possible to build a track completely or partially outside the park if sandbox mode is enabled.
Placing it outside the park with disable clearance checks crashes the game.

**Comment by duncanspumpkin** [comment]
Caused by tracks with paths. This is happening because GAME_COMMAND_18 is not implemented. The function is very similar to footpath_place_real but with some difference.
