### ISSUE TITLE
"No entrance" ride option causes save to crash in original game

### ISSUE THREAD

**Issue by SyndicateApps** [OpenRCT2/OpenRCT2#1958]
The new option for no ride entrances is amazing but unfortunately you can't open it in vanilla RCT2. I tested a few rides and scenarios so it should be easy to duplicate. 

I know that certain functions will eventually make OpenRCT saves incompatible with the original game, but as far as I know this is the first option that actually causes this issue. 

I still need the trainers for placing diagonal path with map object manipulation so if there's any way to make the "no entrance" option backwards compatible (or make MOM a higher priority) I would love to help.

**Comment by Gymnasiast** [comment]
Hm, would it be possible to change to feature to actually do the same as 8 cars does when making the station invisible, @IntelOrca ?

**Comment by SyndicateApps** [comment]
That's exactly what I was thinking, perhaps it would be possible to make it perform the same steps using a built-in track piece and support blocker but that would require the use of MOM. Very curious about how it's currently being done

**Comment by IntelOrca** [comment]
Rather than OpenRCT2 implementing 8Cars MOM, it would be better to get the exact requirements of the player. MOM might be a way of doing what they want to do, but we could provide a much nicer solution.

With regards to no entrance / exit, I am aware it won't work in the original game - unfortunately there isn't a straightforward solution. I don't want to do the hack 8cars does with map elements because that causes other problems. Without a way of knowing whether the player wants to save a file with RCT2 compatibility we can't do an automatic conversion. So I'd just suggest changing the entrances after you have completed your park for now.

**Comment by duncanspumpkin** [comment]
This was discussed when the feature was added. I agree with @IntelOrca I don't like the idea of doing the corrupt map element trick for the sake of backwards compatibility.

**Comment by SyndicateApps** [comment]
If there was one feature worth breaking saves it would probably be this, but I still think maintaining backwards compatibility is important. At least until enough little things are integrated that players have little reason to use the original game. At this point that list is pretty small for me, I just discovered you can place diagonal path correctly with OpenRCT's zero clearances (won't align correctly in rct2 without MOM) so all that's really left in terms of terms of missing trainer options is major ride hacks and small stuff like making the border fence invisible. That might not be important to the casual player but those releasing their parks on NE or Reddit contests will want people to be able to open their saves in rct2 until more of the community switches over.

Since it wouldn't be practical to automatically create two saves, what if there was an option in the dropdown menu to "export compatible save" which would set all ride entrances to plain and reverse any future changes that aren't compatible with the main game. The entrances would be visible again but at least you could theme around them and still use the trainers without saving all ride buildings until the end.

**Comment by Patrik356b** [comment]
Yes, that'd be great @SyndicateApps

**Comment by PFCKrutonium** [comment]
>set all ride entrances to plain

I think better would be just the ones that are not valid ;)

**Comment by IntelOrca** [comment]
Well I would prefer people to just not use that feature if they want backwards compatible saves.

**Comment by PFCKrutonium** [comment]
To be fair, @IntelOrca , they may not have initially intended to share the park. It should be an option, if possible.

**Comment by Gymnasiast** [comment]
Considering there are many novice users who can barely get OpenRCT2 to run, it's quite a bit of a stretch to expect them to know what features will break SV6 compatibility with RCT2 - especially since there is no warning whatsoever.

**Comment by SyndicateApps** [comment]
I actually wouldn't have noticed it wasn't compatible until much later in my build if it wasn't for trying to change the train type in 8cars after removing the entrances. A dialog box warning after choosing that option would definitely be nice

**Comment by Gymnasiast** [comment]
We have added a remark that says (OpenRCT2 only!).
