### ISSUE TITLE
Guests spawn with huge amount of cash (develop build)

### ISSUE THREAD

**Issue by AndyTWF** [OpenRCT2/OpenRCT2#19586]
### Operating System

Windows 10 64 Bit

### OpenRCT2 build

OpenRCT2, v0.4.3-360-gc1e5fda (c1e5fda on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

I started a playthrough of Haunted Harbour a few days ago (and continued today) - and I've got a number of guests spawning with £429,496,789.60 in cash. This is in addition to guests spawning with the usual 60, 70, 80 and 90.

Not that I'm complaining (maybe they'll stay longer and I can figure out a way to make them always buy an umbrella every time it rains) :P

### Steps to reproduce

Unsure, I just started a new game.

### Attachments

![Haunted Harbour 2023-03-06 21-27-28](https://user-images.githubusercontent.com/6977297/223235696-0fa883b3-3631-4b33-a956-c31911ee8c4e.png)

**Comment by janisozaur** [comment]
Good find, thanks!
