### ISSUE TITLE
Request: Real-time autosave

### ISSUE THREAD

**Issue by SyndicateApps** [OpenRCT2/OpenRCT2#1960]
With the option to allow building in pause mode, I can sometimes go hours without any time passing in game. It would be really nice if the autosave was based on real time (minutes) rather than game days. 

It should operate similar to the way it does now when the game isn't paused since 1 year (at normal speed) is equivalent to 1 hour in real life. This would also help at faster speeds since most of the current options would save every few seconds.

The current 5 autosave options are:
Every week
Every 2 weeks
Every month 
Every 4 months
Every year

The real-time options could be:
Every minute (6 days)
Every 5 minutes (month)
Every 15 minutes (3 months)
Every 30 minutes (6 months)
Every hour (year)

**Comment by ianelletson** [comment]
This is a great idea for auto-save and much more palatable to a new user.

**Comment by ryanbowden** [comment]
Agreed, that should be changed to real times, as when you play in fast forward, it saves a lot of times.

**Comment by Overv** [comment]
How about this?

![](http://i.imgur.com/j2Y6TLb.png)

**Comment by SyndicateApps** [comment]
That looks perfect! Great job @Overv
