### ISSUE TITLE
Trying to hire staff on a server crashes game

### ISSUE THREAD

**Issue by Ling1375401** [OpenRCT2/OpenRCT2#19601]
### Operating System

Windows 11, 64-bit

### OpenRCT2 build

Develop v0.4.3-cdb2c39

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is specific to multiplayer

### Describe the issue

This bug is affecting both mine and my wife's PC, both on Windows 11 64-bit. If either one of us tries to hire staff on a server, the game crashes. The same happens if I join someone else's server and attempt to hire staff - my game crashes. It does not crash the server, only the client who tried to hire staff. I have not exhaustively tested every single develop build but it has occurred on 3~4 different ones over the last few weeks, every time we've tried pulling the latest.

All park files seem to be affected, no dependence on RCT1 or custom rides or objects. We do both have RCT1 linked to our games, however.

It works fine on Release v0.4.3 and Release v0.4.2.

[crash.zip](https://github.com/OpenRCT2/OpenRCT2/files/10926888/crash.zip)

### Steps to reproduce

Host or join a server using any develop build.
Try to hire any member of staff.

**Comment by ZehMatt** [comment]
This bug is only triggered when "Automatically place staff" is turned off, looking into it.
