### ISSUE TITLE
“This object is currently in use” doesn't apply to paths

### ISSUE THREAD

**Issue by clxe** [OpenRCT2/OpenRCT2#1964]
In the Scenario editor, when a park gate of any style is already in the scenario, you cannot deselect that gate style until you remove all instances of the gate.

However, the same doesn't apply to paths, and when you _do_ deselect a style of path that is already in the scenario, the game crashes.

**Comment by Gymnasiast** [comment]
Fixed by #2177. (Tested with SF Belgium.)
