### ISSUE TITLE
Staff counter in staff window does not show up string when not in English

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#19656]
In the Staff window, at the bottom there is the number of staff shown. In English it says something like “15 handymen”.

However, in German, it only shows the number, e.g. “15”.

I believe this is a mistake in the translation file (rather than OpenRCT2) but unfortunately, I don't know which is the offending string that needs to be corrected. I have not found it yet. Can someone help me out here, please?

**Comment by tupaschoal** [comment]
PT-BR:
![image](https://user-images.githubusercontent.com/6443427/225770576-a2e1e9b3-b202-4588-b90e-ed53321296c5.png)

EN:
![image](https://user-images.githubusercontent.com/6443427/225770620-018f6779-241b-4de9-9bd9-b7ac2c8a24a0.png)

**Comment by tupaschoal** [comment]
(Actually I think this is due to https://github.com/OpenRCT2/Localisation/pull/2592, so it probably will be fine today after the Localisation repo gets merged)

**Comment by Gymnasiast** [comment]
Appears to work correctly as of 198aa59480c7a0d8f8efbf99aae6c31426c8e7c3.

**Comment by tupaschoal** [comment]
Thanks for checking!
