### ISSUE TITLE
Guests and Staff fail to properly synchronize in multiplayer

### ISSUE THREAD

**Issue by pizza2004** [OpenRCT2/OpenRCT2#1967]
When adding new staff both players must place the staff and they will not synchronize at all.  I'm not as certain this happens with guests, but a slight difference in the total number of guests on each machine seems to support this.

**Comment by pizza2004** [comment]
I don't know whether to create a separate ticket for this, but it seems like the synchronization of rides breaking down and maintenance is also off, possibly because of the issues with unsynchronized guests and staff?  I'm not really sure what's causing it.  I'm just excited to see more tightly linked and controlled multiplayer.  Even if it does mean we lose our hilariously broken error messages. :D

**Comment by IntelOrca** [comment]
Do you have the stay_connected flag on?

**Comment by pizza2004** [comment]
I don't know what that is.  The only way I've been able to get it to run is to just start it up and start a server from in game and then have my friend join from in game.  I don't even know where I'd put that tag, and to be honest the last time we tried the latest version of the game would kick him from the game when he tried to do almost any action at all and we had to use an older version to get it to work.

**Comment by IntelOrca** [comment]
Please read https://github.com/OpenRCT2/OpenRCT2/wiki/Multiplayer

Make sure you use the latest version from now on.

It will by default kick clients that desynchronise, however you can edit config.ini to stop it from disconnecting... however the games will remain desynchronised which is why you get all the problems you describe. This is the basis of most of the problems with multiplayer at the moment.

**Comment by pizza2004** [comment]
Alright, well, yeah, I knew that more or less, I just figured it would be good to have an issue in here specifically about the desynchronization, so that it's easier to see what the bugs are that we have in the game.

**Comment by IntelOrca** [comment]
I will close this then for the issues #1943 and new #1968.
