### ISSUE TITLE
Multiplayer desynchronises without any player input.

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#1968]
This is the first desynchronise issue that should be properly investigated. Something unrelated to player actions is causing a desync. The length of time a client will stay connected for varies but seems to be shorter for parks containing a lot of stuff - its likely some kind of game logic is using client specific state to determine its logic or something is not being initialised properly.

**Comment by michiel2304** [comment]
Would it be possible to have a reconnect button on the top of the screen, so that you dont have to exit and reload you wanna catch up to the host. Then you could just press a button every 10 or 20 minutes and be synced up again.

**Comment by duncanspumpkin** [comment]
I think the idea @michiel2304 is to fix the bug causing the desyncs.

**Comment by vzybilly** [comment]
I think this might be able to help find what's causing the desync. if we
still have all the data on the client then the reconnect could see what all
has changed, outputting the info...

**Comment by renatoi** [comment]
One thing that might cause the issue is the climate/weather. It seems the weather is chosen at random distribution and the weather on clients are usually not synced with the server. This could cause peeps to not go to particular rides if it's raining and starting a chain of synchronization issues.

**Comment by janisozaur** [comment]
@renatoi the weather is handled properly. You can only get different weather once you get desynced, but that will not cause a desync.

**Comment by zsilencer** [comment]
i no longer get these after fixing some of the desync issues ive found and lots of testing.  anyone able to get it to desync with no input still?

**Comment by janisozaur** [comment]
@zsilencer yes, they still happen. Have you found their cause yet or do you need some help investigating?

**Comment by IntelOrca** [comment]
@zsilencer There is definitely an improvement, I can go into various servers and it takes several minutes usually before it desyncs... before it was almost instant after joining. Of course that doesn't mean it hasn't desynced immediately, just that it takes longer for the game to notice (longer for srand to desync).

**Comment by Rodbourn** [comment]
My wife and I play on a LAN with the screens right next to each other.  Dropping a staff member causes an instant desync, if that helps at all.  It's to the point where the game is mostly synced except for when placing staff.  When we need staff we just plan for her to reconnect after I drop them down.  On her client she never sees them placed.

**Comment by duncanspumpkin** [comment]
Staff is a known issue. Can't be resolved until the other desync issues are solved

**Comment by IntelOrca** [comment]
Fixed by 306cf2383c37987db4b4b0c51ec4b2aaf59c9b21

**Comment by zsilencer** [comment]
i still receive a desync

**Comment by janisozaur** [comment]
@zsilencer without any interaction?

**Comment by zsilencer** [comment]
Yeah try running a map with things in it at 16x speed for like an hour it will desync still with no input

**Comment by IntelOrca** [comment]
I ran MM for two hours and I didn't get a desync.

**Comment by janisozaur** [comment]
I'll keep looking then

**Comment by janisozaur** [comment]
@zsilencer can you send a map you used for testing and post relevant info? how many clients, if you rejoined, your system etc?

**Comment by zsilencer** [comment]
[Retropolis Park.SV6.txt](https://github.com/OpenRCT2/OpenRCT2/files/380399/Retropolis.Park.SV6.txt)
OK heres the map I used, I comment out some code in top_toolbar.c so you can set hyperspeed in multiplayer.  Host a game and join with 1 client on the same computer and then set hyperspeed on both of them.  Just leave it running for a while and you should eventually see desync.
