### ISSUE TITLE
Replays will not work correctly when show_guest_purchases = true is set.

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#19694]
The setting seems to influence replays to be unusable, even when the replay is recorded locally with the setting enabled and then tested on the same machine. This might be due to the fact that in headless it probably skips creating the money effect even when the setting is enabled, this is just a guess and needs some more investigation.

**Comment by janisozaur** [comment]
I noticed the purchase _sometimes_ gets shown in title sequence parks. They probably shouldn't.

**Comment by ZehMatt** [comment]
> I noticed the purchase _sometimes_ gets shown in title sequence parks. They probably shouldn't.

That should be at least an easy fix, replays and network play have the issue of entity slots being taken by money where other users or the server wouldn't with this option turned off. Ideally the money effect is not stored in the entity registry but rather in a separate thing for effects. For the title sequence we can just check for the screen flags.
