### ISSUE TITLE
"Forbid tree removal" restriction doesn't forbid removal of large scenery tree items

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#19722]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT v0.4.3

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

The bug also exists in the original game (RCT2/RCTC)

### Describe the issue

In RCT2 vanilla the 'forbid tree removal' restriction was implemented wonky and just disabled removing any small scenery item taller than about 4 units. 

This was mostly fixed years ago, but you can still remove any trees that are larger than 1x1 tile, aka large tree scenery items.

### Steps to reproduce

Open a scenario with the tree removal restriction.
Build a large tree scenery item.
Try to remove it.

**Comment by nehemiah-negussie** [comment]
Im looking into fixing this but I'm not sure how to reproduce the tree removal restriction? Do you have to already have a scenario with it and open that file or is there an easier way to recreate this?

**Comment by duncanspumpkin** [comment]
> Im looking into fixing this but I'm not sure how to reproduce the tree removal restriction? Do you have to already have a scenario with it and open that file or is there an easier way to recreate this?

Its in the scenario options.

**Comment by duncanspumpkin** [comment]
Have a look at L79 of SmallSceneryRemoveAction.cpp you'll need to make the same code in LargeSceneryRemoveAction.cpp

**Comment by nehemiah-negussie** [comment]
I appreciate your help but I still can't find it unfortunately

**Comment by ZehMatt** [comment]
> I appreciate your help but I still can't find it unfortunately

https://github.com/OpenRCT2/OpenRCT2/blob/470d02572d6cba8179e8e79c2a86f14afd1fd0df/src/openrct2/actions/SmallSceneryRemoveAction.cpp#L79-L88
