### ISSUE TITLE
"Favorite ride of X guests" is stored as a signed 16-bit integer, not unsigned.

### ISSUE THREAD

**Issue by James103** [OpenRCT2/OpenRCT2#19733]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.3-387-ga982d15 (a982d15 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

When X exceeds 32768 in "Favorite ride of X guests" on the ride information, it appears to roll over into the negatives.
For example, in a screenshot posted on Discord, a ride has "Favorite ride of -20,540 guests" when it is actually the favorite ride of 44,996 guests.

### Steps to reproduce

1. Create a ride with 255 stations optimized for maximum throughput.
2. Have 60k guests in the park, queueing for or on the same ride.
3. Eventually, when the throughput (guests per hour) is in the high hundred thousands (or a million), X in "Favorite ride of X guests" will appear negative.

### Attachments

Originally found in https://discord.com/channels/601789725090643968/601794846658789377/1089449502735335494
Savegame: [Throughput_1mil.zip](https://github.com/OpenRCT2/OpenRCT2/files/11133052/Throughput_1mil.zip) (check "Customer Information" on Hyper Twister 1 to see the negative value in "Favorite ride of X guests")

**Comment by Broxzier** [comment]
Sounds like a good first issue. The variable that stores this should be of the same type as the type of the max guest limit. The park load code may need to be changed to account for the size difference, so the park file version also needs to be incremented.

**Comment by gordonscottkolb** [comment]
I am new to open source projects, but I would like to get started on this.

**Comment by Broxzier** [comment]
Good luck, @gordonscottkolb! If you have any questions, you can ask for help on Discord.

**Comment by gordonscottkolb** [comment]
@Raedism you may pursue it! Thanks!
