### ISSUE TITLE
Ride Names occasionally change themselves

### ISSUE THREAD

**Issue by UTNerd24** [OpenRCT2/OpenRCT2#1973]
I've noticed while playing a scenario, some of my rides names are getting cut off.
For example, A Rollercoaster I named "Sea Snake" changed itself to "Sea " about an hour later on its own.

Im uncertain on what is causing this but its a little irritating having to constantly rename my rides.

**Comment by IntelOrca** [comment]
Has anyone experienced this recently?

**Comment by PFCKrutonium** [comment]
TBH I have never noticed this, but then I often don't rename my rides.

**Comment by janisozaur** [comment]
@UTNerd24 do you recall if you have opened object selection window in game? Or does this still happen to you?

**Comment by UTNerd24** [comment]
It seems that the bug still persists in the current build, however its much less frequent.

**Comment by janisozaur** [comment]
Is there any message in the log on such occasions?

**Comment by IntelOrca** [comment]
Without reliable steps to reproduce, this is unlikely to get fixed.
