### ISSUE TITLE
Error in network.cpp

### ISSUE THREAD

**Issue by JarnoVgr** [OpenRCT2/OpenRCT2#1975]
Windows builds fail with the following error:
(ClCompile target) -> 
..\src\network\network.cpp(1109): error C2664: 'PCSTR inet_ntop(INT,PVOID,PSTR,size_t)': cannot convert argument 2 from 'const void *' to 'PVOID' [C:\OpenRCT2\svn\trunk\projects\openrct2.vcxproj]

Error is introduced in following changeset: https://github.com/OpenRCT2/OpenRCT2/compare/f15ba8ed0ff5860b0751c485c2831dc602fe5c62...c93c1c738a81f3120a6c32e22694ed2eaa2fbcbb

**Comment by IntelOrca** [comment]
AppVeyor succeeds: https://ci.appveyor.com/project/IntelOrca/openrct2

What version of msbuild, Visual Studio etc. are you running?

**Comment by PFCKrutonium** [comment]
My builds are also failing at this point - Visual Studio 2015 with all the trimmings.

**Comment by janisozaur** [comment]
Yes, that was picked up by travis' mingw builds on this commit: c93c1c738a81f3120a

**Comment by janisozaur** [comment]
accompanying build: https://travis-ci.org/OpenRCT2/OpenRCT2/builds/82008326

**Comment by PureTryOut** [comment]
On Arch Linux, build also fails in network.cpp:
```
/tmp/yaourt-tmp-****/aur-openrct2-git/src/openrct2-git/src/network/network.cpp: In member function ‘bool Network::BeginClient(const char*, short unsigned int)’:
/tmp/yaourt-tmp-****/aur-openrct2-git/src/openrct2-git/src/network/network.cpp:347:58: error: ‘inet_pton’ was not declared in this scope
  if (inet_pton(AF_INET, address, &server_address.sin_addr) != 1) {
                                                          ^
/tmp/yaourt-tmp-****/aur-openrct2-git/src/openrct2-git/src/network/network.cpp: In function ‘bool network_get_address(char*, size_t, const char*)’:
/tmp/yaourt-tmp-****/aur-openrct2-git/src/openrct2-git/src/network/network.cpp:1109:81: error: ‘inet_ntop’ was not declared in this scope
   return inet_ntop(AF_INET, (const void*)&ipv4SockAddr->sin_addr, dst, dstLength) != NULL;
```
