### ISSUE TITLE
No message when path is not connected to ride exit and is therefore unreachable for mechanics

### ISSUE THREAD

**Issue by Yoronex** [OpenRCT2/OpenRCT2#19767]
### Operating System

Windows 10 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.4 (9e4918c) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

When there is no path placed next to the exit of a ride, the player will get a message that they should fix this. However, when you place a fence next to the exit and place a path in that same tile, guests can walk through the fence to exit the ride just fine, but mechanics are unable to reach the ride and walk in circles around your park. The player gets no alert that the exit is unreachable. Even when you remove the fence, the path is still not connected to the exit, making the issue even harder to find.

The ride will never be fixed and the player will get messages continuously that the ride is still broken down, without any clear reason why.

In my opinion, the expected behaviour would either be a message that the ride exit is not connected to a path, no mechanic getting a call (because no mechanic can reach the ride) or mechanics being able to walk through the fence (or missing piece of path) as well, just like guests.

### Steps to reproduce

1. Create a new park
2. Place a ride (for example the dodgegems) and a mechanic in your park
3. Place a fence directly behind the exit of the ride, with a path connecting to the rest of your park. 
4. Open the ride and wait for it to break down
5. The mechanic will get a call to fix the ride, but he is unable to reach the ride, walking around in circles.

When you remove the fence, the path does not automatically connect to the ride exit. Therefore, the mechanic is still unable to reach the ride.

### Attachments

![Screenshot_166](https://user-images.githubusercontent.com/38660000/228476619-964f6726-9abb-45f8-b252-21471d94f17f.png)
![Screenshot_167](https://user-images.githubusercontent.com/38660000/228476639-672ea603-2e4b-439a-95d7-b1f1b5655d8f.png)

**Comment by ocalhoun6** [comment]
Don't we already have a warning message for this?

Let me do a little testing here...

Aha -- here I think I have the root of the problem!

If there is no path in front of the exit at all, you correctly get a warning message that the exit is not connected to a path:

![Dragon’s Cove 2023-03-29 17-57-59](https://user-images.githubusercontent.com/26573303/228701167-268f5e27-5582-4a90-9cba-82202d494f90.png)

But if there's a path in front of the exit -- even if it's not actually connected -- no warning occurs:

![Dragon’s Cove 2023-03-29 17-59-53](https://user-images.githubusercontent.com/26573303/228701212-3002c428-38bf-43f6-ac5f-7c62c349975c.png)

------------------------

So I think the solution here is that this warning message needs to check whether a path is *connected* to the ride exit, not just if a path is *present* at the ride exit.
