### ISSUE TITLE
Month/Day/Year date mode showing ride names instead of the date

### ISSUE THREAD

**Issue by rob356** [OpenRCT2/OpenRCT2#1976]
The in-game date is showing the wrong month and a ride type in Month/Day/Year mode, instead of the normal date. See my screenshot.

![wrong-date-orct2](https://cloud.githubusercontent.com/assets/794548/10119734/adda6db6-646c-11e5-9907-2f87ca168d02.PNG)

This does not happen with the other date formats. I am using v0.0.3-develop build A807 (a046633)

**Comment by Gymnasiast** [comment]
That's a fault in the US English translation file, not in the code.

**Comment by rob356** [comment]
OK, I've switched my game to UK English and the problem has been solved. Since the fix is already in the localization repo I'll just close this.
