### ISSUE TITLE
Duck quacks aren't synchronized on server

### ISSUE THREAD

**Issue by mitchellcairns** [OpenRCT2/OpenRCT2#19775]
### Operating System

Windows 11

### OpenRCT2 build

OpenRCT2, v0.4.3 (285e0fc on master)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is specific to multiplayer

### Describe the issue

When in multiplayer, clicking on the duck produces a quack locally, but not for other players. 

### Steps to reproduce

1. Open a new park in multiplayer. 
2. Have a client join the map.
3. Click on a duck on either the client or server.
4. Boom. Observe the lack of quack! 

### Attachments

![image](https://user-images.githubusercontent.com/17264919/228729526-38206350-d7c5-4a1d-8d91-7ad91059380d.png)

**Comment by duncanspumpkin** [comment]
That is as per design.
