### ISSUE TITLE
Can't resize save/load window anymore

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#19801]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT v0.4.4

### Base game

RollerCoaster Tycoon 2

### Describe the issue

You used to be able to resize the save and load window by dragging the bottom right corner, but since some development version you can't anymore. It works in 0.4.3 but not in 0.4.4.

### Steps to reproduce

Load or save park
Try to resize the window by dragging the bottom right corner

**Comment by tupaschoal** [comment]
Interesting, and while it still worked in v0.4.3, if you resized it to be smaller than its starting height, it would show a blank window background.
