### ISSUE TITLE
Improve "Unknown custom action" tooltip error

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#19816]
As a user, the source of the error message is unknown as many do not know about how plugins work. The error message should be revisited to specify that the error relates to plugins, or should specify which plugin it pertains to. For plugin names, the error could use the name the author defined when registering the plugin.

**Comment by janisozaur** [comment]
That's a great issue report! I think it can provide a great tour of the code for someone unfamiliar with the project and has just enough complexity to not be daunting, yet fulfilling when done.
