### ISSUE TITLE
Screen stays black after minimizing and returning to the game

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#19811]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2 0.4.4 90599d9

### Base game

RollerCoaster Tycoon 2

### Describe the issue

After minimizing the game and returning to it, the screen stays black.
Settings:
![image](https://user-images.githubusercontent.com/6469413/229520607-170879aa-7813-4e0b-8471-3395f9aaa22b.png)

### Steps to reproduce

Set game to fullscreen (borderless)
Set game renderer to Software (Hardware displ......)
Minimize game
Return to game - screen is now black

**Comment by Broxzier** [comment]
This is likely a regression from #19790, because of the newer SDL version.

**Comment by ZehMatt** [comment]
> This is likely a regression from #19790, because of the newer SDL version.

Indeed is, the window starts out black now also, I'll have a look and see what can be done.
