### ISSUE TITLE
error messages

### ISSUE THREAD

**Issue by Tramcoaster** [OpenRCT2/OpenRCT2#19815]
### Operating System

Wndows 10 

### OpenRCT2 build

OpenRCT2, v0.4.4 (9e4918c) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

all rct2 and rct1 maps. i keep getting that error. and I don't know what's up. so i just use the old version.

### Steps to reproduce

I don't know what's up. if i play in a rct2 folder or rct1 folder then i steets get this error.

### Attachments

![Gravity Gardens 2023-04-03 19-35-36](https://user-images.githubusercontent.com/108947550/229585492-a8243d9c-c437-4792-b08b-f7567430e5b5.png)

**Comment by ZehMatt** [comment]
This is caused by one of the plugins you installed, nothing we can do about.

**Comment by spacek531** [comment]
Could this error message be improved? e.g. "Plugin: Unknown custom action" or "<plugin name>: Unknown custom action"?

**Comment by ZehMatt** [comment]
> Could this error message be improved? e.g. "Plugin: Unknown custom action" or "<plugin name>: Unknown custom action"?

Sounds like a good idea, mind opening a new issue?

**Comment by spacek531** [comment]
https://github.com/OpenRCT2/OpenRCT2/issues/19816
