### ISSUE TITLE
text overlapping each other when playing in Chinese language

### ISSUE THREAD

**Issue by leninmo1917** [OpenRCT2/OpenRCT2#19829]
### Operating System

Windows 11, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.4-47-g81fd7b6 (81fd7b6 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

There is an issue with text overlapping each other when i changed the language option in Chinese(Traditional). i usually find this problem on lines where it show price to build item, and showing stats in the states menus.

### Steps to reproduce

1. Change language mode to Chinese (Traditional)
2. build ride
3. open stats menu
4. text overlapping

### Attachments

![螢幕擷取畫面 2023-04-05 124651](https://user-images.githubusercontent.com/129925666/229983486-731a94f4-8c3b-4143-84d8-2c05fd8828f3.png)
![螢幕擷取畫面 2023-04-05 124335](https://user-images.githubusercontent.com/129925666/229983499-a576650a-8344-44af-905e-b8259250866d.png)
![螢幕擷取畫面 2023-04-05 124519](https://user-images.githubusercontent.com/129925666/229983510-55039540-0423-49f4-b333-253642d44d13.png)
![螢幕擷取畫面 2023-04-05 124557](https://user-images.githubusercontent.com/129925666/229983516-621f60d5-117d-4ea1-b418-ac975b83dfe6.png)
![螢幕擷取畫面 2023-04-05 124631](https://user-images.githubusercontent.com/129925666/229983525-a97464aa-0155-4de1-a7de-4ae074db9a52.png)

**Comment by telk5093** [comment]
Are you using OpenGL? How about change the Drawing engine from ``OpenGL`` to ``Hardware`` or ``Hardware (Software)`` in the config?

**Comment by leninmo1917** [comment]
Yes, i am using OpenGL. There is seems no issue after changing drawing engine to hardwear/hardware(software) in the config.
