### ISSUE TITLE
MacOs tests running without OpenMusic

### ISSUE THREAD

**Issue by karst** [OpenRCT2/OpenRCT2#19827]
### Operating System

CI / macOS (x64) using CMake

### OpenRCT2 build

PR 19785 (Built on v0.4.4-81fd7b6)

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Describe the issue

#19785 is failing because OpenMusic isn't loaded in with tests

### Steps to reproduce

Check the PR

**Comment by karst** [comment]
@duncanspumpkin i noticed that the PR is now no longer failing. Was this issue fixed with the most recent push to that PR, or has it been fixed on develop?

**Comment by ZehMatt** [comment]
It was probably fixed by the cmake PR that I recently merged
