### ISSUE TITLE
Scenery search 

### ISSUE THREAD

**Issue by esojka** [OpenRCT2/OpenRCT2#19832]
### Operating System

Windows 10 x64

### OpenRCT2 build

v0.4.4-81fd7b6

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Using the new search feature in the scenery tab.  After adding scenery objects via the Cheat menu, I try to add scenery to the map.  

The search field doesn't seem to find all relevant items based on the in-game description of the object.  

### Steps to reproduce

In the scenery tab: 
Click on a scenery group tab ("Signs And Items For Footpaths") and search for "sign":
![SignsAndItemsForFootpaths](https://user-images.githubusercontent.com/83920002/230099249-00244a1c-7334-4038-a815-62153862ac68.png)

Then click on the "All Scenery" group tab and search for the same:
![AllScenery](https://user-images.githubusercontent.com/83920002/230099250-eb03c19d-eefb-4817-8496-da42b4301886.png)

Search results are different.  Note the scrollbar in each screenshot - all found items are displayed.

I do have lots of objects in the Object folder that I've collected over the years.  I'm not sure if there are too many for the index to capture?

**Comment by karst** [comment]
@trzejos

**Comment by ocalhoun6** [comment]
Isn't this  ... working as intended?

When you have a scenery group selected, the search bar searches within that scenery group only. (This can still be useful for scenery groups that have a lot of items in one group.)

If you want to search all scenery items, then you'd select the 'all scenery' tab before searching.

**Comment by esojka** [comment]
@ocalhoun6 I saw you commented - the second screenshot should show the same results as the first plus all of the results that would have appeared in the other tabs?  

The Starbucks sign (2nd ss, 2nd row, 2nd column) shouldn't appear in the first ss, since it's not listed in that scenery group.  

The path sign with the Mickey Mouse ears (1st screenshot, 3rd row, 3rd column) should appear in the second screenshot, but does not.

**Comment by trzejos** [comment]
Do you know if you see the same behavior with sandbox mode turned on and off @esojka

**Comment by trzejos** [comment]
After doing some testing this doesn't seem caused by the search function at all, but the all scenery tab is missing a few select items such as the other signs.

**Comment by esojka** [comment]
Thanks.  Let me know if there is anything else I can help with troubleshooting.
