### ISSUE TITLE
Cannot protect rides in the mode "make a savefile into a scenario"

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#19839]
### Operating System

Windows 11, 64-Bits

### OpenRCT2 build

OpenRCT2, v0.4.4-52-g28252bc (28252bc on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

so, whenever you try to protect a ride whit a save to change that save to a new scenario, it frezze and crashes entirely

### Steps to reproduce

1. get yourself any save whit rides to be able to have protection on them
2. go to "convert save to scenario"
3. select the save
4. after save open, go to the ride icon (protection)
5. frezze and crash

**Comment by Broxzier** [comment]
This is a regression from https://github.com/OpenRCT2/OpenRCT2/pull/19789. The `OnScrollDraw` function keeps calling itself recursively.
