### ISSUE TITLE
Research not functioning

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#1984]
From reddit.

> Hi, I've run into a weird situation where my research and development isn't actually researching and developing anything... It's a custom scenario I've made (I used all 128 slots for rides if that matters but not all were marked as available on game-start) and it seems the R&D isn't working. There are rides that are within the scenario (I can see them if I load the scenario up in the editor) but not getting researched.
> Anyone seen this before?

> I downloaded the stable build from the website (0.0.2). I tried loading the save into normal RCT2 and R&D also seems broken there so many it's not an OpenRCT issue specifically. (I also tried the debugging console in Open to access the inventions list and drag the remaining items over, didn't do anything but maybe it's not supposed to work like that in game-mode anyway).
> I've uploaded the scenario and my current savegame to Dropbox if you'd like to take a look.
> Thanks for any help you can offer. If you've no idea, I can always re-edit the scenario to include all of the things at the start and then make a new game, I haven't done much in the save.

I've had a quick look and research hasn't been properly edited since 0.0.2 so it should be present in 0.0.3 as well. 
https://www.reddit.com/r/openrct2/comments/3mqmam/research_not_functioning_in_custom_scenario/

**Comment by duncanspumpkin** [comment]
There is something definitely odd with this one. I can't open the object selection window when this save is loaded without crashing due to accessing invalid objects.

**Comment by Ali1331** [comment]
Hi, just an update on this. I loaded the save in OpenRCT2 just now, used the debug console to open object_selection (to test your crash), found the Mine Train Coaster, unticked and ticked it and then opened the inventions list and made sure everything was marked as 'researched', closed that and opened up ride creation and it and all the other missing rides were there. Not sure what happened to fix it to be honest.

I've added the fixed save file to the dropbox folder (there are a few game additions as well, where I've added rides and things) in case you can notice a difference.

**Comment by janisozaur** [comment]
That sounds like something that could be fixed by https://github.com/OpenRCT2/OpenRCT2/pull/2177

**Comment by duncanspumpkin** [comment]
Yeah I was thinking it might be related. I was going to check to see if it had any custom paths in use.

**Comment by duncanspumpkin** [comment]
I think this is fixed now. The reasearch list was corrupted some how and didn't have the missing items. You can fix the save by opening the object selection window and closing it again. The scenario save works fine apart from the fact its a no money scenario and you can't research in no money.

**Comment by Gymnasiast** [comment]
You can research in no money scenarios actually, just not increase funding.

**Comment by duncanspumpkin** [comment]
How do you set the funding though?

**Comment by Gymnasiast** [comment]
You can't. It's fixed on normal funding. (Or quite possibly whatever level it was set to when the player put the scenario into No money mode, which usually happens in the Scenario Editor, so it's stuck on the default level.)

**Comment by IntelOrca** [comment]
I have always commented on this in the past because before we added the R&D window (separate from money) you couldn't even change the research priorities on no money scenarios.

I think it should just automatically set the funding to maximum.
