### ISSUE TITLE
New music won't show up anywhere in OpenRCT2

### ISSUE THREAD

**Issue by garthriot** [OpenRCT2/OpenRCT2#19847]
### Operating System

Windows 10, 63-bit

### OpenRCT2 build

 OpenRCT2 v0.4.4

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

Prior to most recent download, I never had issues with putting in my own music. But since the most recent download, anything I try to add into the game won't show up. Any music I added prior is still there, and I haven't changed my process for putting new music  in the game (adding a .parkobj file with .wav and .json in the object folder). It just doesn't work with anything I try to add into it now.

### Steps to reproduce

1. Run through process to add new music into the game (adding a .parkobj file with a .wav and object.json in the object folder)
2. Open the game and go into any park
3. Open Object Selection
4. Go into advanced and go to music
5. The music doesn't show up

https://steamcommunity.com/sharedfiles/filedetails/?id=2661796657
This is where I learned the process and it always works, until now at least.

### Attachments

![object folder](https://user-images.githubusercontent.com/130040692/230316417-5ccec58a-5a30-4e70-86c2-aea3a236cb92.jpg)
![file](https://user-images.githubusercontent.com/130040692/230316421-2ec1d75f-2720-45af-96e2-3d3aa21da290.jpg)

**Comment by Broxzier** [comment]
Sounds like you may have disabled the "custom objects" filter in the object selection window. Make sure that one is enabled.

**Comment by Broxzier** [comment]
Since you closed this issue, I assume that it's fixed now. Do you know what the problem was?

**Comment by garthriot** [comment]
Yes I had to update my WinRar program
