### ISSUE TITLE
Simulation flag changes color in scenarios with red water

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#19858]
Summary: The simulation flag isn't all-blue in scenarios with red water.

Operating System: GNU/Linux

OpenRCT2 build: 39790779bbf208f80a52f7a68228778280b6ff22

Base game: RCT2

Area(s) with this issue?
- Graphics

Steps to reproduce:
1. Play a scenario with red water
2. Build a ride

Expected: The simulation flag in the ride building window is all-blue
Actual: The simulation flag is partially red

I guess this is because of the red water color. Because this bug does not happen with normal water scenarios.

**Comment by TheClaudeQC** [comment]
same will happens whit any non blue water palettes. A good example is my Blackthing:
![Six Flags 2023-04-08 15-03-16](https://user-images.githubusercontent.com/83843734/230738506-a0634553-f66c-4317-ab50-d6570372dee2.png)

or if you don't have any custom colours, Acid green is also a example (far more brighter and a bit greenish):
![Six Flags 2023-04-08 15-04-35](https://user-images.githubusercontent.com/83843734/230738577-542d0ca8-bf34-43e3-984b-94e87f750307.png)

even the pink water (Official rct2 have same issue):
![Six Flags 2023-04-08 15-05-45](https://user-images.githubusercontent.com/83843734/230738609-c81e6240-6f17-4def-8225-b6cb572c96b6.png)
