### ISSUE TITLE
Landscaping tool not indicating corners when choosing where to raise or lower land

### ISSUE THREAD

**Issue by HtotheTML** [OpenRCT2/OpenRCT2#19853]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.3-414-g4bf35b2 (4bf35b2 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

When using the landscaping tool, the square indicating what part of the land is being raised always displays the full tile, rather than showing the corners.

### Steps to reproduce

1. Open OpenRCT2
2. Begin any scenario
3. Use the landscaping tool

### Attachments

![image](https://user-images.githubusercontent.com/108596959/230440557-5dc85abf-0c17-402f-b1ed-901d6e9897fd.png)

**Comment by beam41** [comment]
I found that this start to happen on 3979077

**Comment by ZehMatt** [comment]
@kyphii could you have a look please?

**Comment by kyphii** [comment]
I bisected the cause to f1063a7. This commit shuffled around the palette IDs, which should have been safe provided all the references to palette IDs use those enum values. My guess is there's a magic number somewhere, but I need to do a bit more digging to find it. If anyone knows which palette ID(s) it is, or where the code is that handles it, that'd be helpful.

**Comment by duncanspumpkin** [comment]
Probably this bit here. https://github.com/OpenRCT2/OpenRCT2/blob/993da08fb983f340b99583a6bc46252f9a94e6a6/src/openrct2/paint/tile_element/Paint.Surface.cpp#L1223
