### ISSUE TITLE
Error when building a Docker image of the game

### ISSUE THREAD

**Issue by Pwirby** [OpenRCT2/OpenRCT2#19850]
### Operating System

Windows 11

### OpenRCT2 build

OpenRCT2, v0.4.4-develop build 9e4918c provided by GitHub Windows (x86-64)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

Issues building the game

### Describe the issue

I tried using the dockerfile from [there](https://github.com/OpenRCT2/openrct2-docker/blob/master/0.4.3/cli/Dockerfile) changing the ENV OPENRCT2_REF v0.4.3 to v0.4.4 in order to have openrct2 in a container but when building it I have this error :
<img width="1280" alt="222" src="https://user-images.githubusercontent.com/19155997/230364775-04dc9c8f-4528-4a49-b1cb-6acb9f19a574.png">
Resulting in the build not finishing.
Apparently from this stackoverflow post https://stackoverflow.com/a/62783627/21034757 it seems the parameter with a default value should be put last or removed.

### Steps to reproduce

1. Download dockerfile from [there](https://github.com/OpenRCT2/openrct2-docker/blob/master/0.4.3/cli/Dockerfile)
2. Change the environment variable line 10 : ENV OPENRCT2_REF v0.4.3 to get latest version -> ENV OPENRCT2_REF v0.4.4 to get latest version
3. Try and build the image

### Attachments

<img width="1280" alt="Capture d'écran 2023-04-05 164459" src="https://user-images.githubusercontent.com/19155997/230365930-54c263ce-a579-42dd-a225-4bcb190fb004.png">

**Comment by duncanspumpkin** [comment]
Please fill out the template correctly. You are clearly on some Linux version. We haven't created a 0.4.4 docker file yet until then you can just build it through the normal means.

**Comment by janisozaur** [comment]
I wouldn't dismiss this, the error makes sense and the code in question is present on current `develop`.

https://github.com/OpenRCT2/OpenRCT2/blob/39790779bbf208f80a52f7a68228778280b6ff22/src/openrct2-ui/windows/LoadSave.cpp#L1062

https://github.com/OpenRCT2/OpenRCT2/blob/39790779bbf208f80a52f7a68228778280b6ff22/src/openrct2/interface/Window.h#L590
