### ISSUE TITLE
Extra drops counted on hybrid coaster diagonal track

### ISSUE THREAD

**Issue by zalazarbiggins** [OpenRCT2/OpenRCT2#19860]
### Operating System

macOS Ventura 13.2.1

### OpenRCT2 build

v0.4.4 (5462c28 on develop) macOS (AArch64) 

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Describe the issue

I downloaded the latest developer build and modified a coaster with updated diagonal track. There are only 15 drops on the ride, but 26 are being counted. 

Also, ride chart is resetting after 30 seconds, and ratings are shown at this time even though a complete circuit has not been made. 

### Steps to reproduce

Preview the ride stats. I've increased the speed a bit, but I haven't added any hills, but you can see in the screenshot that there are 11 additional hills.

If you're going to preview the ride, at least do it right and start this: https://www.youtube.com/watch?v=FDnKIFPnHrc right as the train first leaves the station with a full train to sync correctly. 

### Attachments

<img width="887" alt="Screenshot 2023-04-07 at 2 25 23 AM" src="https://user-images.githubusercontent.com/125212699/230554621-98516042-cbd6-4bf0-aab5-be938a5127af.png">
<img width="889" alt="Screenshot 2023-04-07 at 2 25 05 AM" src="https://user-images.githubusercontent.com/125212699/230554622-0d6360f7-cde2-416c-bcc5-3c2934b6a8a7.png">
<img width="619" alt="Screenshot 2023-04-07 at 2 22 25 AM" src="https://user-images.githubusercontent.com/125212699/230554625-a52b24da-f2e6-4d5b-96c2-fb41a72e3c75.png">

**Comment by jacobjhagen** [comment]
**Park files**
Original with 15 drops: https://www.dropbox.com/s/rdo9tuqnlr910eq/Zalazar_15drops.park?dl=0 
Updated with diagonal track, 26 drops: https://www.dropbox.com/s/m6vyepks7xoo8hv/Zalazar_26drops.park?dl=0

**Comment by janisozaur** [comment]
[Zalazar_15drops_no_objects.park.txt](https://github.com/OpenRCT2/OpenRCT2/files/11176680/Zalazar_15drops_no_objects.park.txt)

**Comment by jacobjhagen** [comment]
[Diagnal Track Drop Bugs.park.txt](https://github.com/OpenRCT2/OpenRCT2/files/11305332/Diagnal.Track.Drop.Bugs.park.txt)

Adding the park where I've been trying to understand the diagonal slope bug. Hope this is helpful.

Additional note:
- Diagonal slopes going upward only get counted as a drop if the end on a diagonal. If they end on a 90 degree piece it will get counted as a drop.

**Comment by jacobjhagen** [comment]
I got around some drop penalties by merging the coaster with a giga, in which lots of drops do not come with a penalty. 

What I'm noticing is there is one scream (the one with only one person screaming) tied to the horizontal drop—and the game will attempt to keep up by playing them in a row.

E.g. The drop contains two diagonal sloped curves: this scream will happen twice, the second coming after the first audio bite loop has completed. 

This has resulted in a very annoying coaster where this singular scream is constantly being played on loop because I have three trains running. 

Oh, additional this scream happens if the train is going UP or down a diagonal slope. 😬

**Comment by zzril** [comment]
For the screaming part, we already have these 2 issues:
* #9534 (screams cut-off on steep diagonal drops and restarting in the valley at the end of the drop), which will be fixed by #19797.
* #19780 (screams loop when the drop is longer than the scream takes to play), although I don't know if there's any progress on this one so far.

Afaik, these 2 things (drop counting for the ride stats and guest screaming behaviour) are not directly related.  
The screaming logic uses a value in the Vehicle class that encodes its current slope/angle, whereas the drop counting logic checks a flag on the track element.
Might be worth refactoring it to use the same logic for both things, though.

**Comment by zzril** [comment]
Alright, looks like the new gentle-sloped wide-curves don't have the `TRACK_ELEM_FLAG_DOWN` set. So, the drop counting logic in `UpdateMeasurements` in `Vehicle.cpp` thinks the drop ends at the curve, and a new one starts right after.

**Comment by zzril** [comment]
This looks fishy:

Definition of `TrackCoordinates` array in [TrackData.cpp](https://github.com/OpenRCT2/OpenRCT2/blob/afcd70a8fd8bf387c5211495057e0a199a44ca6e/src/openrct2/ride/TrackData.cpp#L314-L321):
```cpp
        { 0, 7, 0, 48, -64, -32 }, // TrackElemType::LeftEighthToDiagUp25          
        { 0, 4, 0, 48, -64, 32 },  // TrackElemType::RightEighthToDiagUp25        
        { 0, 7, 0,-48, -64, -32 }, // TrackElemType::LeftEighthToDiagDown25       
        { 0, 4, 0,-48, -64, 32 },  // TrackElemType::RightEighthToDiagDown25      
        { 4, 0, 0, 48, -64, 32 },  // TrackElemType::LeftEighthToOrthogonalUp25   
        { 4, 1, 0, 48, -32, 64 },  // TrackElemType::RightEighthToOrthogonalUp25  
        { 4, 0, 0,-48, -64, 32 },  // TrackElemType::LeftEighthToOrthogonalDown25 
        { 4, 1, 0,-48, -32, 64 },  // TrackElemType::RightEighthToOrthogonalDown25 
```

Definition of `TrackFlags` array in [TrackData.cpp](https://github.com/OpenRCT2/OpenRCT2/blob/afcd70a8fd8bf387c5211495057e0a199a44ca6e/src/openrct2/ride/TrackData.cpp#L6228-L6235):
```cpp
    /* TrackElemType::LeftEighthToDiagUp25                          */   TRACK_ELEM_FLAG_TURN_LEFT  | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_UP   | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL | TRACK_ELEM_FLAG_CURVE_ALLOWS_LIFT,
    /* TrackElemType::RightEighthToDiagUp25                         */   TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_UP   | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL | TRACK_ELEM_FLAG_CURVE_ALLOWS_LIFT,
    /* TrackElemType::LeftEighthToDiagDown25                        */   TRACK_ELEM_FLAG_TURN_LEFT  | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_UP   | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL | TRACK_ELEM_FLAG_CURVE_ALLOWS_LIFT,
    /* TrackElemType::RightEighthToDiagDown25                       */   TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_UP   | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL | TRACK_ELEM_FLAG_CURVE_ALLOWS_LIFT,
    /* TrackElemType::LeftEighthToOrthogonalUp25                    */   TRACK_ELEM_FLAG_TURN_LEFT  | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL | TRACK_ELEM_FLAG_CURVE_ALLOWS_LIFT,
    /* TrackElemType::RightEighthToOrthogonalUp25                   */   TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL | TRACK_ELEM_FLAG_CURVE_ALLOWS_LIFT,
    /* TrackElemType::LeftEighthToOrthogonalDown25                  */   TRACK_ELEM_FLAG_TURN_LEFT  | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL | TRACK_ELEM_FLAG_CURVE_ALLOWS_LIFT,
    /* TrackElemType::RightEighthToOrthogonalDown25                 */   TRACK_ELEM_FLAG_TURN_RIGHT | TRACK_ELEM_FLAG_TURN_SLOPED | TRACK_ELEM_FLAG_DOWN | TRACK_ELEM_FLAG_STARTS_AT_HALF_HEIGHT | TRACK_ELEM_FLAG_ALLOW_LIFT_HILL | TRACK_ELEM_FLAG_CURVE_ALLOWS_LIFT,
```

Two of the down ones miss the `TRACK_ELEM_FLAG_DOWN`, while two of the upwards ones accidentally got it.

**Comment by zzril** [comment]
Same mistake later on for the banked versions.

When changing these, the drops are indeed counted correctly. Tested / verified on the coaster in the picture above, plus one with lots of upgoing wide-curves (some of which are also incorrectly counted as drops previously).

(See my PR.)
