### ISSUE TITLE
No working sound

### ISSUE THREAD

**Issue by HaasJona** [OpenRCT2/OpenRCT2#1986]
Running OpenRCT2 on Fedora Linux using wine I get no audio output at all. Switching the audio device in the settings causes the application to hang indefinitely and not respond anymore. The original RCT2 executable plays sound fine (using wine as well), so it's probably not an issue with the wine configuration.

Edit: I tried both the latest stable build and the latest devel build from https://openrct2.com/download and they both show the same behaviour.

**Comment by zsilencer** [comment]
does the native build work

**Comment by HaasJona** [comment]
Which native build? Can you provide a link or instructions? 

I tried building it myself but while it builds an openrct2 executable the openrct2.dll isn't created anywhere by the build process so it fails to run afterwards.

**Comment by IntelOrca** [comment]
Its possible that this is a Wine bug, a SDL2 bug, or a SDL2 + Wine bug.

**Comment by zsilencer** [comment]
You should be able to build it natively on linux, it was a recent commit.  Try that out and see what happens.  Wine causes a lot of issues in linux.

**Comment by janisozaur** [comment]
When you do that, you can also provide a list of package names required to build openrct on fedora, together with a command to install them :)

**Comment by HaasJona** [comment]
Okay, i managed to create a native linux build and the sound works fine. :smiley: The graphics are completely messed up and right-click-scrolling doesn't work, though, but I used the latest devel version so some breakage is probably expected.

I can provide the commands for building and installing dependencies. Should I just insert them here?

**Comment by janisozaur** [comment]
yes please

**Comment by HaasJona** [comment]
Basically I installed the dependencies:

    sudo dnf install jansson-devel jansson-devel.i686 SDL2_ttf-devel SDL2_ttf-devel.i686 speex-devel speex-devel.i686 libcurl-devel libcurl-devel.i686 glibc-devel glibc-devel.i686 mingw32-gcc-c++ gcc gcc-c++ cmake

and then i ran

    bash build.sh

which tries to run apt-get but it doesn't work and it is simply ignored.

It seems weird that I seem to need both the .i686 as well as the usual .x64 devel packages and I'm not sure why. I'm also not sure why you would need mingw for a native build but otherwise I git error messages.

After that just copy and paste the RCT2 installation into the build dir and also some other files like the "data/g2.dat" and the "language" dir. And then you should be able to run it. I had to rename "Data" to "data", too, because linux is case sensitive and windows is not and the GOG RCT2 had uppercase folder names.

**Comment by duncanspumpkin** [comment]
Are you still having issues with sound?

**Comment by HaasJona** [comment]
Running the windows build in wine still has some problems with sound but the native Linux build is completely fine. I'm closing this for now.
