### ISSUE TITLE
parkinfo command does not work

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#19862]
### Operating System

linux

### OpenRCT2 build

ce4ca96b2 (current develop)

### Base game

RollerCoaster Tycoon 2

### Describe the issue

OpenRCT2 has `parkinfo` cli command, which doesn't work - exits with non-zero status and doesn't report any errors

### Steps to reproduce

launch `./openrct2 parkinfo somefile.park`

### Attachments

I tested that on park from #19860: https://github.com/OpenRCT2/OpenRCT2/files/11176701/Zalazar_26drops_no_objects.park.txt

**Comment by equinoxmatt** [comment]
At the risk of sounding silly - I thought the parkinfo command was used like this:

```./openrct2 parkinfo objects somefile.park```

**Comment by ZehMatt** [comment]
> 

That is actually correct, the current command line code is such a mess and none of those commands actually have any data that would show a proper help format, its all up to having the command handle errors and report them afterwards. Gonna close this as its more of general CLI issue.
