### ISSUE TITLE
Base land type selection 

### ISSUE THREAD

**Issue by rcthorizons** [OpenRCT2/OpenRCT2#19866]
### Operating System

macOS Mojave 10.14.6

### OpenRCT2 build

0.4.4

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

After adding or removing surface types, the land type selector doesn`t let me select all types, or it selects wrong types (see video)

### Steps to reproduce

1. Open any new game
2. add or remove surface types
3. change base land style in game

### Attachments

https://user-images.githubusercontent.com/130150409/230600811-4c60a1e7-99fa-4357-b8f3-5b806a61efdd.mov

**Comment by 733737** [comment]
possibly related to https://github.com/OpenRCT2/OpenRCT2/issues/18583

**Comment by karst** [comment]
I have had this issue since the nsf beta, thought it was fixed since but apparently it hasn't. Issue is that the terrain objects don't update properly.
