### ISSUE TITLE
Make new colours compatible with UI themes

### ISSUE THREAD

**Issue by kyphii** [OpenRCT2/OpenRCT2#19870]
Creating some issues for new colors follow-up so anyone can take them up.

UI Themes don't currently support the new colors, as the UI theme data structure stores some flags in the upper bits of the color fields. These will need to be refactored out. Currently there's a workaround to map the new colors to base game colors until this can be done.

An open question is how we'll be able to handle saved UI themes that have this flags setup, as there isn't a versioning system in place for UI themes.

**Comment by IntelOrca** [comment]
If you add a version number, then you can assume no version number means version 1.
