### ISSUE TITLE
If trees and shrubbery aren't avaliable, they can still be placed with prebuilt design

### ISSUE THREAD

**Issue by ATN-Antronach** [OpenRCT2/OpenRCT2#19878]
### Operating System

WIndows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.4-63-gce4ca96 (ce4ca96 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

The title speaks for itself, if the scenery groups "Trees" and "Shrubs and Ornaments" are not available, but prebuilt rides can still place them as if they were unlocked.

### Steps to reproduce

You can check this by disabling those two scenery groups and try to build anything that uses stuff from there, like the Inverted Hairpin Coaster "Hawksnest" or the Looping Roller Coaster "Bumble Bee."

### Attachments

![Mad Matrix 2023-04-07 22-55-45](https://user-images.githubusercontent.com/66718095/230705905-1e96ef7c-3a94-4e2a-995c-3523deeceef7.png)

**Comment by TheClaudeQC** [comment]
this thing can also extend to the ice and snow theming, where you have it, but not reaserched in "Build your own six flags", you can still use it anyways, this also happens in vanilla rct2
