### ISSUE TITLE
Bugged/Unavailable track pieces on Hybrid Coaster

### ISSUE THREAD

**Issue by admawby** [OpenRCT2/OpenRCT2#19900]
### Operating System

MacOS Ventura 13.3.1

### OpenRCT2 build

OpenRCT2, v.4.4 (417f104 on develop)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

When building a custom Hybrid Coaster, there are several unavailable special track pieces. 
![image](https://user-images.githubusercontent.com/4250422/231046495-61ba755b-2bbd-418f-8e30-71eec9318148.png)

### Steps to reproduce

1. Open any game.
2. Start building a custom Hybrid Coaster.
3. Attempt to build special track pieces.

**Comment by duncanspumpkin** [comment]
I'm not sure what you mean the screenshot shows a situation which only has a couple valid special track elements. I don't see any that are unexpectedly disabled

**Comment by spacek531** [comment]
![image](https://user-images.githubusercontent.com/3454156/231080897-dd139b71-6184-44d0-9138-6ca27e26d264.png)

I thought someone else reported this but I don't see it... the new track pieces PR added these entries to the special element dropdown.

**Comment by spacek531** [comment]
Yes, the track elements should not be in that list.

**Comment by kyphii** [comment]
![image](https://user-images.githubusercontent.com/8711258/231276742-66f8e92e-680e-4a0f-9235-b4b0a13ecc67.png)

It's also present on the Single Rail.

**Comment by admawby** [comment]
Ok! Thanks for confirming.

**Comment by spacek531** [comment]
why did you close this? it's still outstanding
