### ISSUE TITLE
Pathing Bug

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#1991]
https://openrct.net/cloud/uploads/9e16d8ee5cf4acc4888f7bcb28cfc279.sv6

There are a pile of people on that path, walking back and fourth, using their maps to turn around.

**Comment by Christipher** [comment]
This appears to be extremely related to issue #1703 or is a duplicate of this issue...

**Comment by PFCKrutonium** [comment]
It very well could be, but it is a lot less extreme, and I fixed it with no-entry signs in my save.

**Comment by mrtnptrs** [comment]
Could you re-upload that or a similair save file for testing purposes?

**Comment by duncanspumpkin** [comment]
Probably fixed
