### ISSUE TITLE
New Update Graphical Glitches

### ISSUE THREAD

**Issue by mynameiskrysta** [OpenRCT2/OpenRCT2#19917]
### Operating System

windows 10

### OpenRCT2 build

OpenRCT2 0.4.4

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

"L"s appear as random vowels with accent marks on them, and some track pieces (notably large flat to steep pieces) appear broken and scattered

### Steps to reproduce

- Open RCT2 0.4.4
- open any settings window or in-game text
- Make coaster with large straight to steep slope piece or large corkscrew

### Attachments

![Screenshot (14)](https://user-images.githubusercontent.com/104466722/231910670-eaa4c873-ba77-4d53-9556-d418c72abff2.png)
![Screenshot (15)](https://user-images.githubusercontent.com/104466722/231910673-5fa1fa69-38cf-4bf3-bdcd-148c3f38e7d4.png)

**Comment by ocalhoun6** [comment]
The text corruption (and maybe the other corruption as well) is due to a botched update. If you do a fresh install of OpenRCT2 (you can keep all your saved data) then this should all be fixed.

**Comment by duncanspumpkin** [comment]
As above you have only partially installed the newer version. There will even have been a warning every time you open the game saying this as well.
