### ISSUE TITLE
Felicity Anderson Cheat can crash the game, as well as blocking queues

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#1992]
https://openrct.net/cloud/uploads/122814c6ef15ea772741a5ce76b6a807.sv6

In this case, the peep is holding up the line, by making someone puke repeatedly (puke loop). If you try to move the peep (either one) the game will crash shortly thereafter. The only way around this is the remove all peeps cheat.

**Comment by RollingStar** [comment]
Does this happen in the original?

**Comment by PFCKrutonium** [comment]
Not sure, I can't load it in vanilla due to the go-kart's entrance being invisible.

**Comment by PFCKrutonium** [comment]
I fixed the go-karts issue and loaded it in vanilla, the game crashes far quicker with an access violation.
