### ISSUE TITLE
Port to Nintendo 3DS

### ISSUE THREAD

**Issue by Rinnegatamante** [OpenRCT2/OpenRCT2#1994]
I was wondering if OpenRCT2 is still dependant to RCT2 binary cause i'm interested on trying to port your project to 3DS console.

**Comment by pizza2004** [comment]
Yes, it  still is, from everything I've seen.  It doesn't even natively run on Linux or OS X yet.  However, I've seen people starting work on making more code run natively on both of those systems, so you might have some luck with porting what they have so far, but don't expect it to be perfect!

**Comment by PFCKrutonium** [comment]
Yes, but there has been work - I forget who, but there has been a successful (it booted, not playable) linux build... Though that was trickery really, the exe was converted to an elf.

**Comment by janisozaur** [comment]
Can you please stop saying that exe was converted to an elf? No elves were involved in the process.

I ported the build process, created some hooks to set up memory properly and created a completely new ELF binary, although still depending on *code* (and some data) from original PE file.

Right now it is somewhat playable, but not to the point where you would enjoy it.

Can you outline the road to 3DS compatibility?

**Comment by duncanspumpkin** [comment]
Yes it still depends on the RCT2 binary. It will be like that for quite some time until every function is implemented and all data has been recreated.

**Comment by PFCKrutonium** [comment]
(I thought that was what happens - ignore me)

**Comment by RollingStar** [comment]
Resolution would be my concern.
* Top screen: 400 x 240 pixels
* Bottom screen: 320 x 240 pixels
=172,800 pixels

The minimum RCT2 resolution (normal RCT2) is 640 x 480, or 307,200 pixels. Then there's the issue of controls.

The 3DS CPU: Dual-Core ARM11 MPCore, single-core ARM9

Requirements for RCT2:
Min RAM Size 64 MB
Min Hard Drive Space 120 MB
Additional Requirements 4x CD-ROM, sound card
Min Processor Speed: Pentium II at 300 MHz

**Comment by janisozaur** [comment]
Please rename the issue to something indicating porting 3DS.

Is sdl available for 3ds? You can start porting the game as it is now, i guess it might be a long way until it fully runs. For the time being, you can drop all assembly inlines and start with what is available now, it should be plenty enough.

Regarding UI: i don't know usual UX on this platform, but how about creating all UI on the clickable screen and rendering content on the other one?

**Comment by janisozaur** [comment]
There's no port of SDL2 to Nintendo 3DS.

**Comment by Xeddius** [comment]
There is now a port of sdl2 to 3DS.
https://github.com/xerpi/SDL-3DS

**Comment by Rhlp-Engineering** [comment]
any updates on this?

**Comment by Basssiiie** [comment]
AFAIK none of the developers are actively pursuing this, so feel free to look into it yourself. I cannot promise whether anything will be merged with the main repository, but you can always maintain a fork for it.
