### ISSUE TITLE
Mine train block brake supports drawn incorrectly

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#19950]
### Operating System

Windows 10 64-bit

### OpenRCT2 build

OpenRCT2 v0.4.5 5c34d1d7b94847c2ed3862f3b29146cada17f323

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

Mine train block brakes draw supports in direction 0/2 in all directions.

### Steps to reproduce

1. Build a mine train coaster with a block brake
2. Rotate the camera

### Attachments

![image](https://user-images.githubusercontent.com/3454156/232272648-b84bddd7-3bf8-4199-88c1-b0f6ecef2a98.png)

**Comment by Gymnasiast** [comment]
I’ll take this one.
