### ISSUE TITLE
Wrong Error message when raising land: "Too low!"

### ISSUE THREAD

**Issue by loeppenberg** [OpenRCT2/OpenRCT2#20007]
### Operating System

Windows 11, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.4-167-g8f0db4c (8f0db4c on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

This is a development issue

### Describe the issue

The new land height limit of 254 leads to a misleading error message when trying to raise land above the new limit (second picture).

![image](https://user-images.githubusercontent.com/61902845/233649496-10eaeecd-686a-4394-bd49-d75c04beb173.png)
![image](https://user-images.githubusercontent.com/61902845/233649516-c3513ba5-651d-4aad-b399-e0e0c66e4347.png)

Bug in:
LandRaiseAction.cpp. Lines: 112 - 115
`            if (newSlope & SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT)
            {
                height += 2;
            }`

With SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT Flag set, the uint8_t height gets incremented by two. this will overflow from a 256 to a 0, which then leads to the wrong error message later in the LandSetHeightAction.

I'm new to c++. This fixes it for me:
`            if (newSlope & SURFACE_STYLE_FLAG_RAISE_OR_LOWER_BASE_HEIGHT)
            {
                height += 2;
                if (height == 0)
                    height = 255;
            }`
            
But I assume that changing the uint8_t to something else would be the proper solution here, so I'm leaving this without a PR for now.

### Steps to reproduce

Try to raise land above the new land height limit.

**Comment by beam41** [comment]
I would suggest this code which is a bit easier to understand,
```c++
if (height + 2 > UINT8_MAX)
{
    height = UINT8_MAX;
}
else
{
    height += 2;
}
```
speed is insignificant anyway.
