### ISSUE TITLE
Shop runnning costs are unknown

### ISSUE THREAD

**Issue by dmlfan928** [OpenRCT2/OpenRCT2#20018]
### Operating System

Windows 10 64 Bit

### OpenRCT2 build

OpenRCT2, v0.4.4-181-gcdccb21 (cdccb21 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

All shops and stalls do not have a running cost. It displays as unknown and no running cost is charged. I have attached a screenshot from a large park showing all costs for food stalls are "unknown."  Also a park with just 2 stalls and all other expenses such as research and loan cleared and the financial window showing only the construction costs of the stalls.

### Steps to reproduce

1. Open a stall in a park that has money
2. Wait a few moments until a running cost would normally be calculated
3. no cost is then calculated

### Attachments

![Baseball Szn 2023-04-22 09-37-25](https://user-images.githubusercontent.com/95002694/233788609-d6d2d893-8de0-47be-a9d5-343e416c5e1b.png)
![Forest Frontiers 2023-04-22 09-43-03](https://user-images.githubusercontent.com/95002694/233788618-cc7b2922-94be-4c3e-af32-e04fa91c84f4.png)

**Comment by MASHzj** [comment]
I also saw that profit per hour in the ride overview is not shown, at least with newly placed stalls. For older stalls in savegames it still does.

**Comment by MASHzj** [comment]
Just tested it, seems indeed that running costs are not calculated for newly placed stalls, and thus no profit per hour. Total profit still shows, but is too high because running cost is not taken into account.
