### ISSUE TITLE
Looping coaster whit the reverse train option make the wrong sound

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#20027]
### Operating System

Windows 11, 64-Bits

### OpenRCT2 build

OpenRCT2, v0.4.4-168-g6dfc622 (6dfc622 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

It seem that the looping coaster dose the wrong sound when going reverse (dosen't happens foward or whit another ride/train whit same sounds as the looping normally do), it seem to replicate a way slower chainlift sound, when going backward.

### Steps to reproduce

1. Open any parks
2. Choose the looping coaster (the rct2 as it is the tested one as I report it)
3. build a bit of track going, and slowly gaining speed
4. reverse the train
5. let it go (bug will happen)

**Comment by kyphii** [comment]
Huh, that's a bizarre association. Will take a look.

**Comment by karst** [comment]
Perhaps it thinks it's going in negative speed in the audio code

**Comment by kyphii** [comment]
The vehicle reversal doesn't impact the speed, it just affects the train sprites. It seems like friction_sound_id is getting set to SoundId::LiftClassic somehow.

**Comment by karst** [comment]
That's even more odd. Some bugs are unexplainable, probably was already there but was activated through this new setting

**Comment by kyphii** [comment]
Two possibilities I can think of:
- The code is doing something weird with the flags - CarIsReversed is flag 16, so if it's casting to a uint16_t or something it would be converted into flag 0 (OnLiftHill). If that's the case it should affect all coaster types though
- The RTD for the Looping RC got messed up somehow
