### ISSUE TITLE
Unusable surface styles after using remove_unused_objects

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#20041]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.4-181-gcdccb21 (cdccb21 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Yesterday I used the `remove_unused_objects` in-game command to make a park file smaller, but then ran into the issue where only the first two surface styles could be used. Any style after would appear in the dropdown, but show up empty once selected, and when trying to use it, it resulted in an error.

Saving and reloading the park did not fix this.

This may be fixed by https://github.com/OpenRCT2/OpenRCT2/pull/20035 already, but I cannot test this right now.

### Steps to reproduce

1. Open a park with multiple surface styles
2. Use some of them, not all
3. Use the in-game command `remove_unused_objects`
4. Try to use one of the later surface styles

**Comment by duncanspumpkin** [comment]
Almost definitely fixed by #20035

**Comment by Broxzier** [comment]
I've verified that this is indeed fixed on develop now.
