### ISSUE TITLE
Park.postMessage in openrct2.d.ts API not working in multiplayer

### ISSUE THREAD

**Issue by KatieZeldaKat** [OpenRCT2/OpenRCT2#20051]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.4 (9e4918c) provided by GitHub

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

This bug is specific to multiplayer

### Describe the issue

Plugins using the API function `Park.postMessage` are not having the messages sent through when playing in multiplayer, even when no other players are in the server. I have used the Soft Guest Cap Calculator as an example, but multiple plugins which would normally be able to post messages to the player in single player cannot do so in multiplayer.

### Steps to reproduce

- The simplest way to test would be to use the [Soft Guest Cap Calculator Plugin](https://github.com/Sadret/openrct2-soft-guest-cap-calculator/releases/latest) (also attached below).
- In a multiplayer world, open the plugin window and press the button to notify
  - This will not post a message, whereas if you go into single player, it will work

### Attachments

[openrct2-soft-guest-cap-calculator-2.0.2.zip](https://github.com/OpenRCT2/OpenRCT2/files/11328956/openrct2-soft-guest-cap-calculator-2.0.2.zip)

**Comment by mrmagic2020** [comment]
Experienced the same issue on macOS. All the code after calling `park.postMessage` is not executed as well.

**Comment by ZehMatt** [comment]
This is not actually a bug, if you want the message to appear for everyone this has to be executed in a custom game action as this function has no network logic and its not supposed to have any.
