### ISSUE TITLE
Windows ARM64 builds are missing g2.dat 

### ISSUE THREAD

**Issue by sungaila** [OpenRCT2/OpenRCT2#20067]
### Operating System

Windows 11 Version 22H2 arm64

### OpenRCT2 build

OpenRCT2, v0.4.4 (9e4918c) provided by GitHub

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

This is a development issue

### Describe the issue

Both [OpenRCT2-0.4.4-windows-installer-arm64.exe](https://github.com/OpenRCT2/OpenRCT2/releases/download/v0.4.4/OpenRCT2-0.4.4-windows-installer-arm64.exe) and [OpenRCT2-0.4.4-windows-portable-arm64.zip](https://github.com/OpenRCT2/OpenRCT2/releases/download/v0.4.4/OpenRCT2-0.4.4-windows-portable-arm64.zip) do not contain the g2.dat file.

Starting OpenRCT2 will show the error message "Unable to load g2.dat" and the game launches in a corrupted state.

Copying this file from the Windows x64 build fixes this issue.

### Steps to reproduce

1. Download and install either the Installer or Portable version of the Windows ARM64 build
2. Launch the game
3. Notice the "Unable to load g2.dat" message

### Attachments

![image](https://user-images.githubusercontent.com/12021771/234994990-dec53d68-7b0b-4291-ab74-588a7e7f0d59.png)

**Comment by ZehMatt** [comment]
Why did you close the issue? Is this fixed in 0.4.5?

**Comment by sungaila** [comment]
It was fixed for 0.4.4 and @janisozaur is aware of this issue. Afaik he has to make some manual steps to include the g2.dat into the arm64 MSI file, but this might need a separate issue.
