### ISSUE TITLE
Path placement errors in RCT1 & 2 Scenarios

### ISSUE THREAD

**Issue by HtotheTML** [OpenRCT2/OpenRCT2#20070]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.4-208-g74c1f5a (74c1f5a on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

The bug also exists in the original game (RCT2/RCTC)

### Describe the issue

A number of maps in RCT1 and RCT2 have errors in path placement, either missing path pieces or inconsistencies in things like mismatched queue placement.

Iceberg Islands has a mismatched queue path at the bobsled ride

Alton Towers has two missing path pieces in the fort area

Blackpool Pleasure Beach has mismatched railing on part of the tarmac footpath near Drinks Stall 2

African Diamond Mine has an incomplete queue line for the diamond ride, that also uses 2 different queue types

Rollercoaster Heaven has a broken underground pathway near station 2 of the eastern tram line, and Drinks Stall 2 has no path leading to it.

If any new issues with footpaths are discovered, myself or others can add them here.

### Steps to reproduce

1. Open Specified Scenarios
2. View the observed location in-game

### Attachments

Iceberg Islands
![image](https://user-images.githubusercontent.com/108596959/235015023-c5d8aee3-1583-4d24-bc87-83dbbf1984e3.png)

Alton Towers
![image](https://user-images.githubusercontent.com/108596959/235015167-86ea8a32-6168-4f28-8d33-8e5c98498d2a.png)
![image](https://user-images.githubusercontent.com/108596959/235015274-252c2bff-00a4-4527-b04b-caf172049cb6.png)

Blackpool Pleasure Beach
![image](https://user-images.githubusercontent.com/108596959/235015506-517d78ee-5117-4fa1-aad3-f760a138b38f.png)

African Diamond Mine
![image](https://user-images.githubusercontent.com/108596959/235015852-1e16571d-5e75-49ca-b139-c797523bbafc.png)

Rollercoaster Heaven
![image](https://user-images.githubusercontent.com/108596959/235016140-93c6a94b-2ba3-4666-a580-77c87cf408b9.png)
![image](https://user-images.githubusercontent.com/108596959/235016271-d88436f9-3d2a-49e7-99af-fee279bba8b2.png)

**Comment by MASHzj** [comment]
I'm not sure if we should consider the last one an error. It could also be seen as a problem that the player should solve, along with a lot of pathing problems in the whole city area of Rollercoaster Heaven.

**Comment by HtotheTML** [comment]
That makes enough sense; I figured I'd mention it since it was already in the same map as the actual broken path. Said underground broken path can also only be viewed via cutaway view, so you wouldn't realize there's a problem there most of the time.

**Comment by HtotheTML** [comment]
Here's another one in Africa - Oasis (the path doesn't connect to the monorail entrance)
![image](https://github.com/OpenRCT2/OpenRCT2/assets/108596959/3790e806-bc6b-4296-8468-231e833466ea)

**Comment by MASHzj** [comment]
> Here's another one in Africa - Oasis (the path doesn't connect to the monorail entrance) ![image](https://private-user-images.githubusercontent.com/108596959/301098239-3790e806-bc6b-4296-8468-231e833466ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTQzOTQsIm5iZiI6MTcwNjY5NDA5NCwicGF0aCI6Ii8xMDg1OTY5NTkvMzAxMDk4MjM5LTM3OTBlODA2LWJjNmItNDI5Ni04NDY4LTIzMWU4MzM0NjZlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQwOTQxMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jM2Y4YTg0MzM0ZmNlYzdkODA1ZGVjNjJjN2EwNjU1NjliMjRjODg0MTUzNjQwNDNmMDYzMmQyYjgzNjI0ODRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SIapMzh8LpapRyEgbto1RcygYzaJKtk0hqWIiv0khk4)

Also for that one it shouldn't be fixed imo. It's easy to spot so I see this as something the player should fix.

**Comment by HtotheTML** [comment]
> Also for that one it shouldn't be fixed imo. It's easy to spot so I see this as something the player should fix.
I'm not so sure about that, as the RCT Classic version of this scenario fixed that missing path issue.
