### ISSUE TITLE
Terrain tool cannot use terrain surfaces/edges if you have too many enabled.

### ISSUE THREAD

**Issue by ZeeMaji** [OpenRCT2/OpenRCT2#20083]
### Operating System

Linux (OpenSUSE Tumbleweed)

### OpenRCT2 build

OpenRCT2, v0.4.4 appimage from https://github.com/OpenRCT2/OpenRCT2/actions/runs/4826898672

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

When enabling more than 32 terrain surfaces or 16 terrain edges, the respective terrains after the 32nd/16th surface/edge become unusable by the terrain tool.
This only affects the terrain tool, they can still be selected in the map generation window and work fine from what i can tell.

### Steps to reproduce

1. Open the attached park
2. Try using the 33rd terrain surface or 17th terrain edge
3. It will give you a "Can't change land type..." error when trying to use them.

### Attachments

Note that this park will export a bunch of terrain surfaces and a terrain edge to your objects folder.
[Terrain test land.park.tar.gz](https://github.com/OpenRCT2/OpenRCT2/files/11358023/Terrain.test.land.park.tar.gz)

**Comment by Gymnasiast** [comment]
Commenting so that I can be assigned.
