### ISSUE TITLE
title screen logo not going away

### ISSUE THREAD

**Issue by LordUngarr** [OpenRCT2/OpenRCT2#20080]
### Operating System

windows 10

### OpenRCT2 build

OpenRCT2, v0.4.1 (be518f4) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

open RCT logo in the top left doesnt go away and smears 

### Steps to reproduce

just start any game and move the camera around

### Attachments

![image](https://user-images.githubusercontent.com/54385412/235272171-50507628-dda0-4a0b-8993-a8449022a8a6.png)

**Comment by MASHzj** [comment]
Is there a reason you still use 0.4.1?

**Comment by Gymnasiast** [comment]
Mismatched g2.dat. Please reinstall OpenRCT2.
