### ISSUE TITLE
Right click scrolling doesn't work

### ISSUE THREAD

**Issue by hypocube** [OpenRCT2/OpenRCT2#2009]
Soon after I got a bunch of workbenches (custom scenery and all that) I started up a saved game and it's very difficult to move around via holding right-click. I've uninstalled/reinstalled rct2, removing all the scenery, but scrolling still doesn't work well. It's not completely out, but it's unusable. It works less when scrolling into high-traffic areas with lots of guests and rides.

**Comment by zsilencer** [comment]
Is this on windows, linux?  Did this start happening recently?

**Comment by UTNerd24** [comment]
Its happening to me too. The game's framerate remains fine, but Scrolling is almost 1FPS.
Very confusing

**Comment by IntelOrca** [comment]
I can't reproduce this. Please state the exact versions and platforms of the game you are using.

**Comment by UTNerd24** [comment]
Currently using 1287.

**Comment by IntelOrca** [comment]
@UTNerd24 platform, OS?

**Comment by UTNerd24** [comment]
Windows 8.1

**Comment by HaasJona** [comment]
I can reproduce this on Linux, too.

Simple steps to reproduce:
- Load a save with some stuff going on on screen
- Right click scrolling should be relatively smooth
- Open some large extra viewports
- Try right click scrolling again

Not the game runs still smooth for me, but right click scrolling is almost impossible

**Comment by HaasJona** [comment]
I don't know why, but I can work around this issue by increasing a number in input.c:

```
--- src/input.c	(revision 3cd51f6aa5a5695631e43e9c8a89cea73815274e)
+++ src/input.c	(revision )
@@ -435,7 +435,7 @@
 		RCT2_GLOBAL(RCT2_ADDRESS_INPUT_STATE, uint8) = INPUT_STATE_RESET;
 	} else if (dx != 0 || dy != 0) {
 		if (!(w->flags & (1 << 2))) {
-			RCT2_GLOBAL(0x009DE540, sint16) = 1000;
+			RCT2_GLOBAL(0x009DE540, sint16) = 1000000;
 			dx <<= viewport->zoom + 1;
 			dy <<= viewport->zoom + 1;
 			if (gConfigGeneral.invert_viewport_drag){
```

and then right click scrolling becomes super smooth. On the other hand, if I decrease that number, it becomes super slow.

**Comment by zsilencer** [comment]
seems to happen with uncap fps on

**Comment by hypocube** [comment]
^ same, turning off uncapped fps fixed it.

I have a Windows 10 PC and I can't find the exact version I have for OpenRCT, but I do have dev builds enabled.
