### ISSUE TITLE
Server list window scroll is glitched when server list is empty

### ISSUE THREAD

**Issue by frutiemax** [OpenRCT2/OpenRCT2#20096]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2 fe219281ec6b66e3a47c67125c939bc1f01d1274

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

When the server list is first opened, the scroll is glitched. This only works in OpenGL mode. My graphic card is a Nvdia GTX 1060.

![image](https://user-images.githubusercontent.com/12629817/235329289-51631133-95e5-41e2-9164-c37e819a0835.png)

### Steps to reproduce

1. Start OpenRCT2 in OpenGL mode
3. Click on Play with other players

**Comment by ZehMatt** [comment]
I noticed this as well, its probably from one of my refactors allowing more than 32k entries for scrolling, I suspect this one is simply a uninitialized variable, opening the window twice seems to correct it so I'm probably not far off with the assumption.

**Comment by 733737** [comment]
I can confirm this issue cropped up for me recently, and didn't exist a couple months ago
