### ISSUE TITLE
[Plugin] Some network APIs use player index and group index

### ISSUE THREAD

**Issue by Basssiiie** [OpenRCT2/OpenRCT2#20104]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.4-212-gfe21928 (fe21928 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is specific to multiplayer

### Describe the issue

The plugin API regarding network objects, like players and groups, mixes up the ids and the indexes and there is not really a consistent usage. This becomes especially problematic for plugins that run in long running servers, where users come and go and groups may be created/deleted. Id's stay the same but indices change over time.

Specifically:

- Functions like `getGroup()`, `getPlayer()` etc all take indices ([see here](https://github.com/OpenRCT2/OpenRCT2/blob/fe219281ec6b66e3a47c67125c939bc1f01d1274/distribution/openrct2.d.ts#L2900C4-L2903))
- Interfaces like [`Player`](https://github.com/OpenRCT2/OpenRCT2/blob/fe219281ec6b66e3a47c67125c939bc1f01d1274/distribution/openrct2.d.ts#L2916-L2917) and [`PlayerGroup`](https://github.com/OpenRCT2/OpenRCT2/blob/fe219281ec6b66e3a47c67125c939bc1f01d1274/distribution/openrct2.d.ts#L2927-L2928) only exposes ids,
- Event args also only pass ids, as far as I'm aware.

### Steps to reproduce

This can go wrong in the following situation:
1. Player 0 joins with irrelevant permissions at index 0.
2. Player 1 joins with Spectator permission at index 1.
3. Player 2 joins with Admin permission at index 2.
4. Player 0 leaves the server.
5. Player 1 moves to index 0 and player 2 moves to index 1.
6. Player 1 does a plugin action that should be blocked by permissions.
7. Plugin checks the permission through `network.getPlayer(playerId)` where `playerId` is 1.
8. `network.getPlayer(playerId)` actually returns player information about Player 2 (who is at index 1), which is the wrong player.

And the same issue exists for groups because the next step is `network.getGroup(player.group)` which may return yet another group.

**Comment by ZehMatt** [comment]
The API should only expose the player id and never the index, only the player id is stable across the network also.
