### ISSUE TITLE
Portable installation isn't portable.

### ISSUE THREAD

**Issue by Jayesk** [OpenRCT2/OpenRCT2#20107]
### Operating System

Windows 10 64-bit

### OpenRCT2 build

v0.4.4

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

This is a development issue

### Describe the issue

The portable installation seems to not differ at all from the normal one and still saves game data in the Documents folder defeating the purpose of it being portable.

FYI. You can fix this by:
1. Making a shortcut of OpenRCT2.exe
2. Adding "--user-data-path=.data" to the end of the launch options in the Shortcut properties.

### Steps to reproduce

1. Install/Unzip the v0.4.4 portable version for Windows 64x
2. Watch game not save progress to the game folder and instead save it in the normal Documents folder.

**Comment by ZehMatt** [comment]
Portable just means it doesn't have the installer. You could create a batch file that always launches it with the extra command line, its unlikely we are going to change this behavior, closing this issue.
