### ISSUE TITLE
On-ride photos seem gone

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#20145]
### Operating System

Windows 11, 64-Bits

### OpenRCT2 build

OpenRCT2, v0.4.4-230-g61d820e (61d820e on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

it seem that in the most recent developpe, the On-Ride Photo is entirely gone, it didn't happened in my previously used version (check some other bugs for information)

### Steps to reproduce

1. Open any parks
2. Build a coaster that do normally have access to the On-Ride Photo Section
3. Check on the special elements
4. Reasult below

### Attachments

![Capture d’écran 2023-05-07 083709](https://user-images.githubusercontent.com/83843734/236678237-2d2e3365-d434-4447-84da-4c675062fd47.png)

**Comment by karst** [comment]
@spacek531

**Comment by cheweytoo** [comment]
I can reproduce this.

Last good: 1917a0b
First bad: 61d820e
