### ISSUE TITLE
"Show FPS" will stay visible when hiding toolbar.

### ISSUE THREAD

**Issue by karst** [OpenRCT2/OpenRCT2#20157]
### Operating System

Windows 10, 64 Bit

### OpenRCT2 build

OpenRCT2, v0.4.5 (76ca840) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

When "Show FPS" is selected in the options menu and hiding the Toolbar (Default shortcut is "T") the FPS counter will stay visible.

Current behaviour: All toolbars hide, except for the FPS counter.
Expected behaviour: This will hide together with the other toolbars.

### Steps to reproduce

1. Make sure to have "Show FPS" enabled.
2. Press the shortcut to hide toolbar (Default "T")
3. All of your toolbar will disappear, except for the FPS counter.

### Attachments

![image](https://user-images.githubusercontent.com/1516893/236843337-36531a42-71d0-413a-bacc-08139610812d.png)

**Comment by ZehMatt** [comment]
It's not part of the toolbar, that is rendered directly onto the screen buffer.

**Comment by karst** [comment]
It doesn't feel logical how on the title screen it does hide 
![image](https://user-images.githubusercontent.com/1516893/236851896-d7cd9302-fc9c-4414-ad63-6493e088c0eb.png)
but not 
![image](https://user-images.githubusercontent.com/1516893/236851946-394bbc03-1888-4737-8d36-7289209b89a9.png)

For making a quick screenshot I think it's a lot more sensical to have it disappear with the hide toolbar shortcut rather than having to go into the options menu before allowing to make this screenshot.

**Comment by ZehMatt** [comment]
That version info is only drawn when you are in the title screen no where else and its not a widget either. Both of those texts are just overlays and aren't part of the actual UI system so we can't really tie them together like you want. The FPS info just like any other overlay tool would do it.
