### ISSUE TITLE
Switching to hardware acceleration doesn't work on Linux

### ISSUE THREAD

**Issue by HaasJona** [OpenRCT2/OpenRCT2#2015]
The following line in shared.c
```
			gRenderer = SDL_CreateRenderer(gWindow, -1, SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
```
on Linux returns nil and SDL_GetError returns

    SDL_CreateRenderer Renderer already associated with window

which causes the game to crash if enabling hardware acceleration in the Options dialog.

Apparently you're not allowed to use https://wiki.libsdl.org/SDL_GetWindowSurface together with https://wiki.libsdl.org/SDL_CreateRenderer

**Comment by janisozaur** [comment]
You mentioned in #2015 that it helps in debugging of this problem, can you say a bit more?

**Comment by HaasJona** [comment]
With #2015 it outputs the error message "SDL_CreateRenderer Renderer already associated with window", previously it did just segfault.

If you google this error message you will find that it's caused by using SDL_CreateRenderer on a window where previously SDL_GetWindowSurface has been called which seems to be illegal. Not sure why this behaves different on Windows and Linux.

**Comment by HaasJona** [comment]
Note that hardware acceleration generally works fine if you edit

    hardware_display = true

in config.ini.

It's just the switching at runtime that seems to be problematic. Maybe we need to recreate the window. Or just ask the user to restart after changing this setting.

**Comment by HaasJona** [comment]
@IntelOrca can you look at this? I think applying the change only after a restart is the right solution and I could write a patch for that. Or do you have a better idea?

**Comment by janisozaur** [comment]
Does it happen on Windows as well? I don't recall @IntelOrca having a Linux set up.

**Comment by HaasJona** [comment]
No, for some reason it doesn't crash on Windows. But according to the documentation it probably should crash. I have not much experience with SDL, though, so I would like to hear some other opinion about this issue.

**Comment by IntelOrca** [comment]
Its not easy for me to investigate this without creating a VM to host linux.

**Comment by HaasJona** [comment]
Hmm. Are you okay with me writing a patch that only applies the change after a restart then? Or I could try to make it in a way that it tries to switch at runtime and if that fails it gets applied the next start. But that seems wrong as switching at runtime really seems to be unsupported by the sdl api.

**Comment by IntelOrca** [comment]
If it its unsupported then prompting the user to restart the game is your only option. Most games do this anyway usually just for convenience of video and texture initialisation.

**Comment by HaasJona** [comment]
I can try recreating the window only. But if that's not easily possible restarting might be the better and cleaner solution. Some things like steam integration might not work properly of the window is destroyed and recreated.

**Comment by HaasJona** [comment]
I tried recreating the window but after switching from hardware to non-hardware display the screen didn't update anymore. Also it seemed messy. I created #2038 to ask the user to restart until we have a better solution.

**Comment by IntelOrca** [comment]
OK - we can prompt a restart for now and let someone else try to re-create the window.
