### ISSUE TITLE
Guests who land outside park are trapped on tile they landed on

### ISSUE THREAD

**Issue by moosehadley** [OpenRCT2/OpenRCT2#20169]
### Operating System

Fedora 38

### OpenRCT2 build

OpenRCT2, v0.4.4 (9e4918c on HEAD, DEBUG)

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Describe the issue

Guests who fall outside of the park will be permanently stuck on whatever tile they land on, and treated as if they are still inside the park. For example, if you delete a path where you have construction rights while guests are standing on it.

Even guests who land on a valid path outside the park will be trapped on the tile they landed on.

This is probably the same root issue encountered by #17562, however, the proposed fix does not solve this particular issue.

### Steps to reproduce

1. Play Dusty Greens
2. Wait until some guests are standing on the bridge between the two sections of the park
3. Delete the bridge
4. Observe as guests fall and become stuck 

### Attachments

![Screenshot from 2023-05-09 18-14-44](https://github.com/OpenRCT2/OpenRCT2/assets/7897563/ec18c8ec-f7a8-49ad-8852-5799acbf9aa4)
![Screenshot from 2023-05-09 18-16-05](https://github.com/OpenRCT2/OpenRCT2/assets/7897563/d9dfc376-5604-4353-9bb0-ec4d7261cc9c)

**Comment by ocalhoun6** [comment]
Hm... what would a fix to this even do with the guests?

The three things I can think of:

A) Have them fall through the ground and into the void, where they'll eventually disappear.

B) Have them immediately teleport to a park entrance, walking inward as if they just entered the park. (Though, of course, without paying for entry again.)

C) Use the same algorithm for automatically placing staff: teleport the wayward guest instantly to the location of another random guest in the park.

All three of these will still look really weird when they happen, but at least the stuck guests wouldn't be a problem.

**Comment by moosehadley** [comment]
In my personal opinion, B and C are both good options. Leaning towards C if I had to pick one.

I think the proposed solution to #17562 should remain (not allowing exits to be placed along the edge of a park) as fixing this issue with solutions B or C would allow players to 'cheat' by simply placing ride exits along the edge of the park and not bothering with exit paths.

**Comment by ocalhoun6** [comment]
Any scenario with construction rights could still allow the cheat from #17562 to work. Just build the ride exit in the construction rights area, above unowned land.

**Comment by ZehMatt** [comment]
I don't think this is really a problem, if they fall onto such tiles you can just pick them up and throw them back into your park, this is not something that needs automatic fixing as there is already a way to correct it.
