### ISSUE TITLE
Park rating litter penalty is applied wrong

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#20209]
### Operating System

Windows 10

### OpenRCT2 build

0.3.5 release

### Base game

RollerCoaster Tycoon 2

### Describe the issue

The litter penalty for the park rating is applied incorrectly from version 0.3.5 onwards.

I made two identical scenarios, one with a litter penalty of 452, and one with all litter removed (done while paused so it has no other effects).

Here is a table with the park ratings in 0.3.4 and 0.3.5
![image](https://github.com/OpenRCT2/OpenRCT2/assets/25930360/079bf1be-3b8c-470e-bf33-34429259194f)

I checked a bunch of standard scenarios and got these rating differences: 
![image](https://github.com/OpenRCT2/OpenRCT2/assets/25930360/c9ca1421-f9f5-4863-9b4c-5ba19383c5f2)

I also checked vanilla and all ratings were identical to 0.3.4.

The two identical scenarios (with and without litter) are attached.

### Steps to reproduce

Load the scenarios in both versions, check the park ratings, and see what the litter penalty is with the park rating inspector plugin (only possible in 0.3.5 and later).

### Attachments

[Litter penalty scenarios.zip](https://github.com/OpenRCT2/OpenRCT2/files/11477165/Litter.penalty.scenarios.zip)

**Comment by ZehMatt** [comment]
Interesting, I'll have a look later today.

**Comment by ZehMatt** [comment]
I see that this was also my doing, so I guess this doesn't really count as a bug then since we fixed an original bug that leads to this.
