### ISSUE TITLE
package 'jansson' not found

### ISSUE THREAD

**Issue by amspady20** [OpenRCT2/OpenRCT2#2022]
~/Downloads/OpenRCT2-develop/.cache/orctlibs ~/Downloads/OpenRCT2-develop
~/Downloads/OpenRCT2-develop
./install.sh: line 198: sha256sum: command not found
Downloaded library with sha256sum: 
~/Downloads/OpenRCT2-develop/build ~/Downloads/OpenRCT2-develop
OPENRCT2_CMAKE_OPTS =
-- checking for module 'jansson'
--   package 'jansson' not found
CMake Error at /usr/local/Cellar/cmake/3.3.2/share/cmake/Modules/FindPkgConfig.cmake:340 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.3.2/share/cmake/Modules/FindPkgConfig.cmake:502 (_pkg_check_modules_internal)
  CMakeLists.txt:37 (PKG_CHECK_MODULES)

-- Configuring incomplete, errors occurred!
See also "/Users/kevinspady/Downloads/OpenRCT2-develop/build/CMakeFiles/CMakeOutput.log".

**Comment by janisozaur** [comment]
That's no way to report an issue.

Install the package.

If you have to file an issue for a missing package, please stay with automated builds for the moment.

**Comment by HaasJona** [comment]
Install the package jansson-devel or something like that depending on you linux distro. You will probably other packages, too. If you have problems with that, wait until the build scripts and documentations are more complete.

**Comment by amspady20** [comment]
Sorry about that.  I am using a Mac.

**Comment by janisozaur** [comment]
subscribe yourself to https://github.com/OpenRCT2/OpenRCT2/pull/2017 and https://github.com/OpenRCT2/OpenRCT2/pull/1993 (possibly more to come) and stick with automated builds for now.
