### ISSUE TITLE
New title theme crackly audio on linux appimage

### ISSUE THREAD

**Issue by ZeeMaji** [OpenRCT2/OpenRCT2#20223]
### Operating System

Linux (OpenSUSE Tumbleweed)

### OpenRCT2 build

OpenRCT2, v0.4.5 (latest actions build)

### Base game

RollerCoaster Tycoon 2

### Describe the issue

The new title theme has crackly/popping audio, at least on the linux appimage. I'm not sure about other versions.

### Steps to reproduce

1. Download and run the latest appimage from the actions builds
2. The new title theme has crackly/popping audio

**Comment by ZehMatt** [comment]
I've played around a bit with the parameters for the audio and nothing really helps to eliminate the cracking entirely, this might be a fundamental issue with SDL/Speex

**Comment by rik-smeets** [comment]
On my Windows machine, the change introduced in #20223 severely worsened the cracking. Therefore I'm reopening this issue.

Increasing the sampling rate to `8192` seems to fix the issue, i.e. upping the sampling rate instead of reducing it. But that doesn't sound like the way to go for other platforms?

**Comment by ZehMatt** [comment]
> On my Windows machine, the change introduced in #20223 severely worsened the cracking. Therefore I'm reopening this issue.
> 
> Increasing the sampling rate to `8192` seems to fix the issue, i.e. upping the sampling rate instead of reducing it. But that doesn't sound like the way to go for other platforms?

Yeah I tried bumping it up quite a bit while a single audio source plays nicely such as the title music a park with tons of rides with music it starts having hard gaps and loud cracks, I'm more quite convinced that this problem comes from SDL, @duncanspumpkin wants to change it to OpenAL eventually.

**Comment by rik-smeets** [comment]
It's just that the crackling on the title screen is currently so bad that we should fix that before the next release. If necessary with a workaround like only upping the sampling rate at the title screen or something for the time being.

**Comment by rik-smeets** [comment]
After a rebuild the issue seems to be gone for me. As you said it probably isn't perfect but it's certainly acceptable. I'll close this one again, false alarm.

**Comment by cheweytoo** [comment]
Uh - have you listened to my recoding in https://github.com/OpenRCT2/OpenRCT2/issues/20223#issuecomment-1553671023 ? It's _bad_.

**Comment by ZehMatt** [comment]
Lets keep this open as there is definitely some cracking and popping, I'll try to further investigate this, however some basic google research showed that we are not alone on this issue, it also seems to affect linux users more heavily than windows users. The only fix might be to change to OpenAL.

**Comment by ocalhoun6** [comment]
Just updated to the latest develop on Linux, and now I have *no* theme music whatsoever! I only hear the background sounds of the title sequence parks, peep screams and ride sounds, etc.

**Comment by ZehMatt** [comment]
@cheweytoo can you check what the latest develop commit sounds like?

**Comment by cheweytoo** [comment]
Absolutely fine here with the b9382ae AppImage build:

https://github.com/OpenRCT2/OpenRCT2/assets/29800630/53dc2d4b-fcb9-4e99-98fb-90a352380b1a

**Comment by ZehMatt** [comment]
> Absolutely fine here with the [b9382ae](https://github.com/OpenRCT2/OpenRCT2/commit/b9382ae9fc938a08bed947b0688b83de45ddc508) AppImage build:
> 
>  b9382ae_no_more_crackling.mp4

Thanks, closing this issue as resolved.
