### ISSUE TITLE
RCTC Booster sprites have offsets located in CPP rather than `sprites.json`

### ISSUE THREAD

**Issue by karst** [OpenRCT2/OpenRCT2#20227]
![image](https://github.com/OpenRCT2/OpenRCT2/assets/1516893/fb3e26d8-18fd-4610-82ce-3f8d529dce8b)

The sprites from both Intamin sprites and the B&M sprites are still located in in CPP/HPP rather than in the sprites.h.

This issue should be a good first issue.

**Comment by Gymnasiast** [comment]
Implemented by https://github.com/OpenRCT2/OpenRCT2/pull/21218.

**Comment by hschantz** [comment]
Hi, I'm a student working on this issue as part of a course contribution assignment. I plan to open a PR in the next few weeks. Happy to coordinate if anyone else is working on this.

**Comment by Lastorder-DC** [comment]
> Implemented by [#21218](https://github.com/OpenRCT2/OpenRCT2/pull/21218).

@hschantz It's already fixed.
