### ISSUE TITLE
Blizzard/Heavy Snow/Snow don't make guests open umbrellas

### ISSUE THREAD

**Issue by cheweytoo** [OpenRCT2/OpenRCT2#20240]
### Operating System

Ubuntu Linux 22.04.2

### OpenRCT2 build

AppImage develop 551a681

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Guests don't open their umbrellas in "solid water" weather, i.e. snow/heavy snow/blizzard:

![blizzard_nobrella](https://github.com/OpenRCT2/OpenRCT2/assets/29800630/6d35963d-35da-4f22-9b96-36b079e87614)

I'd understand not using umbrellas in "snow", it looks pretty light. But "heavy snow" and "blizzard" definitely are umbrella-worthy.

### Steps to reproduce

1. Have guests with umbrellas
2. Use cheat to switch weather to snow/heavy snow/blizzard
3. Watch guests not open umbrellas

**Comment by ocalhoun6** [comment]
I have never once in my life seen anyone use an umbrella in a snowstorm, no matter how heavy the snow.

And in a proper blizzard, there would be to much wind for an umbrella to be of any use whatsoever, anyway.

**Comment by cheweytoo** [comment]
Then you've never seen me in a snowstorm ;-) – seriously, umbrellas are pretty useful against big wet snowflakes.

For blizzards, you have a point. It's best to not be outside at all in that case anyway – I'm not sure how to map that to park guest behaviour…

**Comment by AaronVanGeffen** [comment]
I think this should be addressed, indeed. Surely parks in cold climates wouldn't sell flimsy umbrellas, right? ;)

**Comment by cheweytoo** [comment]
I'm sure guests would refuse to pay those outrageous prices for flimsy ones.

**Comment by cheweytoo** [comment]
Fixed with https://github.com/OpenRCT2/OpenRCT2/pull/21986 - thanks!
