### ISSUE TITLE
Miss matched g2.dat size

### ISSUE THREAD

**Issue by foxwg** [OpenRCT2/OpenRCT2#20251]
I updated to the 4.5 and am now getting an error saying 
Miss matched g2.dat size
expected: 3263
actual: 3715
g2.sat may be installed improperly.

I then receive a warning that there will be graphics glitches if I continue. 

![image_2023-05-19_190040696](https://github.com/OpenRCT2/OpenRCT2/assets/134093065/ff0e9f87-e7c3-4805-ba1a-35b656396bbd)

**Comment by duncanspumpkin** [comment]
You need to install it correctly or you will get this issue. Don't just copy the exe file it needs all its assets.

**Comment by foxwg** [comment]
So you need the installer, portable,  and symbols? I had only used the exe file in the past and it worked fine, hence the confusion.

**Comment by foxwg** [comment]
![image](https://github.com/OpenRCT2/OpenRCT2/assets/134093065/4901c81e-09ef-4d40-bb1f-f879fdac5441)

**Comment by foxwg** [comment]
How do you install it correctly then? I have the 3 downloads together and run them all but am getting errors.

**Comment by duncanspumpkin** [comment]
The symbols are for developers. All you need is the installer or the portable version. Portable version you just unzip and run. Installer you just run and follow the install.

**Comment by 733737** [comment]
we really need to have a downloads page that recognizes your operating system, then offers that build with a link that says "see additional builds"

**Comment by foxwg** [comment]
> The symbols are for developers. All you need is the installer or the portable version. Portable version you just unzip and run. Installer you just run and follow the install.

You had told me that you need more than just the installer (exe). I downloaded that and updated using that - then I got the error of the g2.dat size.  I then tried updating with the portable, but that doesn't solve the problem. 

This process is not clear. There needs to be better (aka actual) instructions for these updates.

**Comment by karst** [comment]
Please make sure to uninstall the game and reinstall it, or delete g2.dat and reinstall it.

**Comment by foxwg** [comment]
> Please make sure to uninstall the game and reinstall it, or delete g2.dat and reinstall it.

Thank you!
