### ISSUE TITLE
Guests during intro sequence fail to load when exiting to main menu from large park

### ISSUE THREAD

**Issue by Phosphorus551** [OpenRCT2/OpenRCT2#20250]
### Operating System

Windows 11 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.5-36-g7caf400

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

Guests in the first park of the intro sequence fail to load correctly when exiting from any saved park with more than ~4000 guests. When exiting a park with a guest count in excess of around 5500+, no guests outside rides load correctly, and those that do are sometimes stuck on random tiles near the top of the screen, looping their walking animation, sitting animation, or map animation. The error is corrected upon loading the second park in the sequence. It does not persist when the intro loops back to the first park again.

This is sometimes accompanied with a crash shortly after, however this is inconsistent.

Note that this bug is not seemingly tied to any specific park, as it happens when exiting from any save file.
https://github.com/OpenRCT2/OpenRCT2/assets/134081940/08765446-326d-405c-97cb-156a4391d360

### Steps to reproduce

1. Open a park with more than 4000 guests. I recommend more than 5500, as the issue is significantly easier to notice by this point.
2. Exit to main menu.
3. Observe.

**Comment by youngwii2** [comment]
On v0.4.5-41-gb9382ae (b9382ae on develop), I am experiencing this same glitch after loading a park with around 3000 guests and returning to the main menu.
