### ISSUE TITLE
commit 5b117ce - game crash with Laydown Coaster

### ISSUE THREAD

**Issue by cheweytoo** [OpenRCT2/OpenRCT2#20253]
### Operating System

Ubuntu Linux 22.04.2

### OpenRCT2 build

5b117ce develop AppImage

### Base game

RollerCoaster Tycoon 2

### Describe the issue

I see a crash as soon as a Laydown Coaster gets in the viewport. The only message in the console is "`Segmentation fault (core dumped)`". Plugins are disabled.

I've reduced it to an empty park with only a Laydown Coaster.

Last good: 946e57b
First bad: 5b117ce

The crash seems to happen as soon as one of the coaster's inversions is visible. I'll try to figure out which one exactly it is.

### Steps to reproduce

- use build 5b117ce or newer
- open attached park and move viewport around to get the coaster in view
- game crash

### Attachments

[game_crash_on_lay_down_inversion_visibility.zip](https://github.com/OpenRCT2/OpenRCT2/files/11520222/game_crash_on_lay_down_inversion_visibility.zip)

**Comment by cheweytoo** [comment]
Clicking on the coaster in the ride list, regardless of viewport view: Instant crash.

**Comment by cheweytoo** [comment]
Found it - It's the forward half loop:

![crash_inversion](https://github.com/OpenRCT2/OpenRCT2/assets/29800630/86cfe581-2927-4df4-847b-e713f3fb0177)

…which I can't seem to be able to build any more‽


Minimal crashing park:
[forward_half_loop_game_crash.zip](https://github.com/OpenRCT2/OpenRCT2/files/11520458/forward_half_loop_game_crash.zip)

**Comment by cheweytoo** [comment]
And just for github's automatic crosslinking, this is the offending commit's PR: https://github.com/OpenRCT2/OpenRCT2/pull/20078

**Comment by ZehMatt** [comment]
@Gymnasiast mind looking into this?

**Comment by Gymnasiast** [comment]
Sure, can you assign me?

**Comment by cheweytoo** [comment]
This still happens in develop 0a3573e.

Is there any way I can help with this? I'm afraid my C++ is very rusty…

**Comment by Gymnasiast** [comment]
Not really no, it should be easy for someone familiar with track drawing code, but hard otherwise. There are other people who could do this, but I was assigned since I made the offending commit in the first place. It’s just that I haven’t been motivated much to work on OpenRCT2 in the last weeks/months due to circumstances.

**Comment by cheweytoo** [comment]
Fix confirmed using develop build 6aa7e91. Thank you!
