### ISSUE TITLE
Crash with placing park entrances in scenario editor

### ISSUE THREAD

**Issue by ccfreak2k** [OpenRCT2/OpenRCT2#2025]
The bug seems to occur when the game tries to place a ghost entrance at what is otherwise an invalid location. I can trigger it by:

1. Entering the scenario editor and skipping to the Landscape Editor step
2. Picking the park entrance tool
3. Zooming all the way out (perhaps not necessary) and wiggling the cursor across the top left map edge (I did it near the top corner, but it may not matter).

An error is printed by `world/map.c:166` with an element out of range message.

Consider the following call stack:

    > openrct2.dll!map_get_first_element_at(int x, int y) Line 167
      openrct2.dll!map_get_surface_element_at(int x, int y) Line 240
      openrct2.dll!map_is_location_in_park(int x, int y) Line 843
      openrct2.dll!update_park_fences(int x, int y) Line 759
      openrct2.dll!place_park_entrance(int flags, short x, short y, short z, unsigned char direction) Line 4292
      openrct2.dll!game_command_place_park_entrance(int * eax, int * ebx, int * ecx, int * edx, int * esi, int * edi, int * ebp) Line 4338
      openrct2.dll!game_do_command_p(int command, int * eax, int * ebx, int * ecx, int * edx, int * esi, int * edi, int * ebp) Line 500
      openrct2.dll!game_do_command(int eax, int ebx, int ecx, int edx, int esi, int edi, int ebp) Line 419
      openrct2.dll!park_place_ghost_entrance(int x, int y, int z, int direction) Line 1185
      openrct2.dll!window_map_place_park_entrance_tool_update(int x, int y) Line 1215
      [deeper frames omitted]

At `window_map_place_park_entrance_tool_update()`, `y` starts out as `0x40`.
At `place_park_entrance()`,`y` is modified once (at `world/map.c:4264`) and is `0x20`; it's subtracted by 32 (`0x20`) when it's passed to the next callee
At `update_park_fences()`, `y` is subtracted by 32 and passed to the next callee; this causes an underflow and is passed as `0xFFFFFFE0`
`map_is_location_in_park()` divides it by 32 and passes it (from my testing this causes it to become `0xFFFFFFFF` for a reason that I don't understand yet but is probably just how unsigned math works on the x86).
`map_get_surface_element_at()` checks it and finds it to be out of bounds and returns `NULL`. The caller tries to dereference it and gets an access violation.

My understanding of this code is incomplete, nor did I ever really use the scenario editor much as a kid, so I couldn't say whether this is expected behavior. The immediate fix to suppress the crash would be to insert a null check at `world/map.c:844`; this would cause it to fall through with the "land not owned by park" message, which is superfluous when "placing" a ghost structure, but it would at least allow the game to continue.

I'd be more than happy to submit this as a pull request, but I'd like to bring it up as an issue instead in case there's a better way to address it.

**Comment by duncanspumpkin** [comment]
Bah I implemented that last night. I'll just fix it right now.
