### ISSUE TITLE
Assertion Error when quitting OpenRCT2 after using Track Design Manager

### ISSUE THREAD

**Issue by joeraz** [OpenRCT2/OpenRCT2#20255]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.4.5-36-g7caf400 (7caf400 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

I get an "Assertion Failed" error in OpenRCT2 when I try to quit the program after using the Track Design Manager.  A screenshot of the error is attached (the number of images that the message says were not freed varies each time, and is higher if I used the Track Design Manager more before trying to quit).

### Steps to reproduce

1. Open the Track Design Manager.
2. Select any ride.
3. Quit OpenRCT2 - the assertion error will appear.  From my experience, the error will still appear if I close the ride selection window, return to the title screen, or even start a game before quitting.
4. Selecting Retry or Ignore will cause the game to quit correctly.  Selecting Abort will crash OpenRCT2.

### Attachments

![OpenRCT2AssertionFailed](https://github.com/OpenRCT2/OpenRCT2/assets/2691813/de8a387d-466e-4051-b12b-038175c85071)

**Comment by zzril** [comment]
Some testing shows that for each coaster type, there is a fix number of images that are not freed for each time the respective coaster type had been selected. Vehicle types don't matter.

The number does not seem to depend on the number of pre-built designs. (For example, for the Corkscrew 4471 images are not freed and for the Wooden Coaster 2163 images are not freed.)  
That makes me wonder whether it's some off-by-one error, related to manually adding the `Build custom design` option to the preview list when opening it from a park or the track designer as opposed to the track designs manager. Just a guess at this point, though.
