### ISSUE TITLE
"Random" title music could still attempt to play RCT1 after it gets deselected

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#20262]
### Operating System

Windows 10 x64

### OpenRCT2 build

OpenRCT2, v0.4.5 (76ca840) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

If the player then removes the link to RCT1 after having set the title music to random, there's a chance that the game attempts to play the RCT1 theme. Choosing the random title theme was only available when RCT1 was linked, so not really something players would do, but now with the official title sequence added, the random option is available even when RCT1 is not linked. Players are more likely to bump into this issue now.

### Steps to reproduce

1. Link RCT1 in the options window
2. Select "Random" title music
3. Restart the game (a few times)
4. Notice silence - the game must've picked the RCT1 title music which is not available.

**Comment by karst** [comment]
was this present before the new theme was added? If yes the changelog entry is valid, otherwise, if introduced with the new theme that changelog entry can be removed.

**Comment by Broxzier** [comment]
Yes, https://github.com/OpenRCT2/OpenRCT2/commit/76ca8400cade0c6de5b47a7e44d405d56f278a83is the release commit.

**Comment by karst** [comment]
okay good!
