### ISSUE TITLE
Bug: Some Pre-Built Wild-Mouse designs cannot be built due to being "Too steep for lift hill"

### ISSUE THREAD

**Issue by UTNerd24** [OpenRCT2/OpenRCT2#2027]
This only just happened to me in the latest build. Wild Mouse rides are able to have steep chain lifts, but for some reason, when I go to view the pre-built designs, some of the appear invisible. When I click on the invisible design, It cannot be constructed by any means because it is apparently "Too Steep for lift hill"
I find this confusing as the lifts were literally no different to the other designs. I haven't checked yet, but it might be possible that other types of Rollercoasters have been effected.

So whats going on here?

**Comment by pizza2004** [comment]
My guess would be it has something to do with #1873.  I haven't noticed anything else lately that would have caused it in the merges and issues, but for some reason GitHub doesn't have any method by which I can get emails about all commits directly made by contributors (IntelOrca and duncanspumpkin) so it could be something else they've done that would fly under my radar because of this gap in GitHub functionality.

**Comment by janisozaur** [comment]
@UTNerd24 I understand it used to work for you in the past? Can you find which version was the last working one & the first broken one?

Please state your system as well.

**Comment by UTNerd24** [comment]
To be perfectly honest I don't know what version was working last. This program is updated so often I lose track.

But my OS is Windows 8.1

**Comment by janisozaur** [comment]
Can you provide clear steps to reproduce this then? I was able to build "Cheesy mouse" just fine a moment ago. I also haven't seen any (nor understand what you mean exactly) invisible designs.

**Comment by UTNerd24** [comment]
It's strange really. I've been using Track i've downloaded from the internet. Im unsure how to explain it in a way that you all would understand. Sorry.

**Comment by Patrik356b** [comment]
Does building steep hill lift work by the way? (building a custom track)

**Comment by duncanspumpkin** [comment]
Can you provide the .TD6 files for the tracks that are failing.

**Comment by Gymnasiast** [comment]
I think it might be related to #1788, actually.

**Comment by Gymnasiast** [comment]
@IntelOrca Have you actually tested this?

**Comment by IntelOrca** [comment]
I am assuming it is the usual problem, the track design has track which is too steep for the ride type which can be fixed by turning off support limits.
