### ISSUE TITLE
Bug: SIGNS

### ISSUE THREAD

**Issue by UTNerd24** [OpenRCT2/OpenRCT2#2028]
It seems that a Majority of this game's bugs are caused by signs.
If you add a ride with a sign near a neighboring ride, The sign will change into the name of the ride next to it.
Most of the time, If there is more than one sign and you attempt to select one, It will select a completely Different sign. Meaning that if you try to delete them, It will leave at least one sign remaining that is un-deletable. Earlier I made an issue that Ride names were shortening themselves. I'm pretty sure the Signs are the reason for this.
And when I try to delete one remaining sign, It will select something in the corner of the map, and possibly crash.

I hope this can be resolved, then I will literally have no more bugs to report. For a while anyway.

**Comment by HaasJona** [comment]
Which signs exactly? Signs above paths, scrolling signs or 3D signs? I have experienced some weirdness with signs, but without clear steps to reproduce this has been very difficult to debug.

To make helpful bug reports, try to describe each step required to reproduce the problem. And upload savegames and saved designs if needed.

**Comment by duncanspumpkin** [comment]
I can't reproduce this at all. I've tried building lots of 3D signs, lots of footpath signs destroyed and built lots of rides.

**Comment by IntelOrca** [comment]
This sort of thing can be caused by a corrupt saved game.
