### ISSUE TITLE
Low heartline twister coaster excitement ratings

### ISSUE THREAD

**Issue by e-foley** [OpenRCT2/OpenRCT2#2031]
I suspect this is a bug in the original game.  It's extremely difficult to create a heartline twister coaster with reasonable excitement ratings.  This is due to a number of reasons.  Some of them clearly aren't bugs:

1. The excitement base rating of 1.40 is the lowest of all coasters.
2. With only one car per train, the coasters can't get a train length bonus.
3. With no turns, the coasters can't get any lateral-g benefits.

But the single biggest heartline twister killer is suspiciously buglike:  assuming that `RIDE_ENTRY_FLAG_11` is set for the heartline twister, then `ride_ratings_apply_adjustments()` in ride_ratings.c (see [here](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/ride/ride_ratings.c#L776)) not only removes the airtime bonus, but goes so far as to apply an airtime *penalty*.  The questionable code is below:

```
if (rideEntry->flags & RIDE_ENTRY_FLAG_11) {
    if (totalAirTime >= 96) {
        totalAirTime -= 96;
        ratings->excitement -= totalAirTime / 8;
        ratings->nausea += totalAirTime / 16;
    }
} else {
    ratings->excitement += totalAirTime / 8;
    ratings->nausea += totalAirTime / 16;
}
```

The reason this is suspicious is that it's the only place in the entire ride_ratings.c file where a quantity is expressly subtracted from the excitement rating.  This makes it possible for the heartline twister coaster to end up with a negative excitement rating, as [this reddit topic](https://www.reddit.com/r/rct/comments/3n9jyv/2_this_heartline_is_so_bad_it_has_negative/) shows.

Having a penalty sort of makes sense because it discourages players from making very slow heartline twists and reaping the benefits.  That said, I suspect the penalty was meant to stack with the bonus, not replace it entirely.  This would make the code more like the following.

```
ratings->nausea += totalAirTime / 16;
if (rideEntry->flags & RIDE_ENTRY_FLAG_11) {
    totalAirTime = min(totalAirTime, 96);
}
ratings->excitement += totalAirTime / 8;
```

That way, the airtime bonus still exists, but it caps after a certain amount of time.  (It may not be the most efficient way to write it, but it gets the point across.)

This is one of those cases where the correct behavior is a little ambiguous, but this change makes a lot of intuitive sense.  Note that other rides with a lot of airtime also have low excitement base scores, like the reverse freefall coaster at 2.00, but these rides apparently aren't subject to the some airtime penalty.

What do you all think?

Thanks for reading.

**Comment by duncanspumpkin** [comment]
I would rather not make any changes to the balance of the game until full implementation but there is nothing to say we can't look at this again in the future.

**Comment by HaasJona** [comment]
I agree with the proposed change but I wonder if we should wait until the game is fully decompiled first before making non-essential tweaks.

On the other hand, one could argue that this is clearly a bug as a negative or [underflowing](http://i.imgur.com/NIGCm.png) excitement rating is clearly not supposed to happen.

**Comment by PFCKrutonium** [comment]
@HaasJona Where can I get that TD6?

**Comment by IntelOrca** [comment]
We can definitely fix the underflow.

**Comment by HaasJona** [comment]
This is a screenshot from the original rct2. Not sure if openrct2 still underflows. But it shouldn't get negative either.

**Comment by Gymnasiast** [comment]
@HaasJona : OpenRCT2 shows a negative value when it gets below 0.00.

**Comment by PFCKrutonium** [comment]
I just tried it in Vanilla and Open - I copied the track exactly, and got -0.44 (High) Excitement in Open, and 655 (for a split second, then 0.11) in Vanilla.

**Comment by IntelOrca** [comment]
@PFCKrutonium Can you upload the TD6?

**Comment by PFCKrutonium** [comment]
https://files.gitter.im/OpenRCT2/OpenRCT2/non-dev/zdN9/Underflow.TD6

**Comment by Gymnasiast** [comment]
Closing since it has been fixed - it's even in stable!
