### ISSUE TITLE
Options window not drawing properly

### ISSUE THREAD

**Issue by mrmbernardi** [OpenRCT2/OpenRCT2#20312]
### Operating System

Pop OS x86_64 6.2.6-76060206-generic

### OpenRCT2 build

OpenRCT2, v0.4.5 (66ae20b47 on develop, DEBUG)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

The options window is not redrawing properly, see the video.

[Video](https://github.com/OpenRCT2/OpenRCT2/assets/7877312/9f3a7685-57c8-4a70-a2b6-74fa8acf3095)

### Steps to reproduce

1. Open the options window (either in game or on the main menu)
2. Do anything with it.

**Comment by Broxzier** [comment]
Pretty sure that this is a regression from https://github.com/OpenRCT2/OpenRCT2/pull/20176

**Comment by mrmbernardi** [comment]
The cause is this change:

https://github.com/OpenRCT2/OpenRCT2/pull/20176/commits/3d2a91ba79a3c49cfbdad5be25e13746f27c5d91#diff-901d9e8dcef0368d6fe787f03e5799e6b9e2567c6420fb87faa2e06a36867d51L667

Looks like it may affect other windows

**Comment by mrmbernardi** [comment]
The updating of the window when you actually hit the button also seems to be a bit dodgy. See the following example where the window has two close buttons:

![Screenshot from 2023-06-06 21-09-41](https://github.com/OpenRCT2/OpenRCT2/assets/7877312/f6ca34c3-d4a4-4b52-b27e-4434ac43e057)

**Comment by mrmbernardi** [comment]
The updating of the window when the button is hit also seems to be a bit dodgy. In the following video you can see times where there's two close buttons or no button at all.

[Screencast from 06-06-23 21:11:12.webm](https://github.com/OpenRCT2/OpenRCT2/assets/7877312/09efc57a-7aa7-4e29-97ed-4efc0dc77b34)
