### ISSUE TITLE
Hotkey for scenery picker not working when re-paint tool is selected

### ISSUE THREAD

**Issue by Mmmmulder** [OpenRCT2/OpenRCT2#20338]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.5-66-g90b65cd (90b65cd on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

When the re-paint tool for scenery is selected, the shortcut key for the scenery picker doesn't react and re-paint tool stays selected.

### Steps to reproduce

1. select re-paint tool in the scenery window
2. press shortcut key for scenery picker

**Comment by Ziscor** [comment]
Please excuse the bump. Making it so the hotkey works there would be really good to have, as it's a very common situation while playing.

**Comment by simonrshepherd** [comment]
This is actually one I've seen a ton playing the game! Appreciate you guys a ton for all the openrct2 work, this would be a great bug to fix if you guys have the time!
