### ISSUE TITLE
Rendering issue in options menu

### ISSUE THREAD

**Issue by hlabrand** [OpenRCT2/OpenRCT2#20343]
### Operating System

Linux 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.5 (, DEBUG)

### Base game

RollerCoaster Tycoon Classic

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

When opening the options menu, the height of the window is sometimes too high / not trimmed to the available options.

This remains like this until something else needs to be rendered, for example a moving train from the roller coaster under the menu, at which point some parts of the box (but not all of it) are correctly trimmed.

See first and second screenshot before the coaster's train goes down the track, and after.

Another, more inconsistent rendering issue (on the color of some parts of the box) appears on some tabs. This is the third screenshot.

In case that changes anything, i'm at 2x scale.

### Steps to reproduce

Open the options menu, move it above a rollercoaster with a moving train. If bug doesn't trigger, try changing tabs a few times.

### Attachments

![Bumbly Beach 1](https://github.com/OpenRCT2/OpenRCT2/assets/1617462/209acb43-2f9e-433e-88cb-9b55e7a3cccb)
![Bumbly Beach 2](https://github.com/OpenRCT2/OpenRCT2/assets/1617462/10a13813-0078-47a2-a68d-c0d2440ee95a)
![Bumbly Beach 3](https://github.com/OpenRCT2/OpenRCT2/assets/1617462/97e73a3a-25d5-40f5-92a8-330a6a39f9c9)

**Comment by ZehMatt** [comment]
Duplicate, see #20312
