### ISSUE TITLE
something is double into the track list if you build 

### ISSUE THREAD

**Issue by Realsteel89** [OpenRCT2/OpenRCT2#20342]
### Operating System

Windows 10 64 bit

### OpenRCT2 build

latest develop build

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

delete one into the code list

### Steps to reproduce

the large half loop left is double into the track list

### Attachments

![image](https://github.com/OpenRCT2/OpenRCT2/assets/77458610/5489cc08-2cc5-4a53-8cb2-dd771155216d)

**Comment by zzril** [comment]
Not sure on which commit and coaster the OP got this, but I managed to recreate this on currently latest develop (ed875a1273d6558359cbf0cd6aca2e7f83f82e35) for the twister coaster.

![double](https://github.com/OpenRCT2/OpenRCT2/assets/84280965/3c013c67-5d21-47ab-b76e-52f52ae910eb)

**Comment by zzril** [comment]
In [src/openrct2/ride/Track.h](https://github.com/OpenRCT2/OpenRCT2/blob/ed875a1273d6558359cbf0cd6aca2e7f83f82e35/src/openrct2/ride/Track.h#L455-L458):
```cpp
namespace TrackElemType
{
// [...]
    constexpr track_type_t LeftLargeHalfLoopUp = 183;
    constexpr track_type_t RightLargeHalfLoopUp = 184;
    constexpr track_type_t RightLargeHalfLoopDown = 185;
    constexpr track_type_t LeftLargeHalfLoopDown = 186;
```

In [src/openrct2-ui/ride/Construction.h](https://github.com/OpenRCT2/OpenRCT2/blob/ed875a1273d6558359cbf0cd6aca2e7f83f82e35/src/openrct2-ui/ride/Construction.h#L72-L75):
```cpp
/**
 * Order of special track elements dropdown. Elements with the same name string must be sequential or they show up twice.
 */
constexpr std::array DropdownOrder = {
// [...]
    TrackElemType::LeftLargeHalfLoopUp,
    TrackElemType::LeftLargeHalfLoopDown,
    TrackElemType::RightLargeHalfLoopUp,
    TrackElemType::RightLargeHalfLoopDown,
```

**Comment by zzril** [comment]
Changing the order in `src/openrct2-ui/ride/Construction.h` like this seems to work, although I don't understand why:
```cpp
TrackElemType::LeftLargeHalfLoopUp,
TrackElemType::RightLargeHalfLoopDown,
TrackElemType::RightLargeHalfLoopUp,
TrackElemType::LeftLargeHalfLoopDown,

```

**Comment by zzril** [comment]
The `DropdownOrder` array was introduced with 61d820e614b0d31907b71fc73e7e6cd73c1dede7 on `develop` (between release v0.4.4 and v0.4.5) and with it the bug.

**Comment by zzril** [comment]
Alright, I think I got it.

The naming of the `TrackElemType` constants in [https://github.com/OpenRCT2/OpenRCT2/blob/ed875a1273d6558359cbf0cd6aca2e7f83f82e35/src/openrct2/ride/Track.h#L455-L458](src/openrct2/ride/Track.h) is wrong:
```cpp
namespace TrackElemType
{
// [...]
    constexpr track_type_t LeftCorkscrewUp = 58;
    constexpr track_type_t RightCorkscrewUp = 59;
    constexpr track_type_t LeftCorkscrewDown = 60;
    constexpr track_type_t RightCorkscrewDown = 61;
// [...]
    constexpr track_type_t LeftLargeHalfLoopUp = 183;
    constexpr track_type_t RightLargeHalfLoopUp = 184;
    constexpr track_type_t RightLargeHalfLoopDown = 185;
    constexpr track_type_t LeftLargeHalfLoopDown = 186;
// [...]
    constexpr track_type_t LeftMediumHalfLoopUp = 271;
    constexpr track_type_t RightMediumHalfLoopUp = 272;
    constexpr track_type_t LeftMediumHalfLoopDown = 273;
    constexpr track_type_t RightMediumHalfLoopDown = 274;
```
What is defined above as the `RightLargeHalfLoopDown` is in fact a left large half loop down. (Which is, confusingly, the piece that completes a loop that was started with a `RightLargeHalfLoopUp.` But that's a naming convention that has been consistent throughout the game for inverting pieces that also come with a direction change (i.e. loops and corkscrews, but not inline twists).)

Code that does not refer to these elements by name, but just to the constant directly (either explicitely or implicitely, by using the enum values as array indices) - such as the `_trackCoordinates` array cited above - works as expected. The end user doesn't see the incorrect variable name that was used in the source code (unless checking in a debugger).

Code that refers to the elements by name must stick to the incorrect naming.

The above cited solution
```cpp
TrackElemType::LeftLargeHalfLoopUp,
TrackElemType::RightLargeHalfLoopDown,
TrackElemType::RightLargeHalfLoopUp,
TrackElemType::LeftLargeHalfLoopDown,
```
in fact boils down to:
```cpp
183,
185,
184,
186
```

which is the same numeric order as for the Medium loops:
```cpp
    TrackElemType::LeftMediumHalfLoopUp,
    TrackElemType::LeftMediumHalfLoopDown,
    TrackElemType::RightMediumHalfLoopUp,
    TrackElemType::RightMediumHalfLoopDown,
```
or - in numbers:
```cpp
271,
273,
272,
274
```

So, it makes sense that that solution produces the correct behaviour.

**Comment by spacek531** [comment]
Nice sleuthing. I had forgotten about that quirk of naming.
