### ISSUE TITLE
Meta: git workflow

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#2034]
This is more a discussion rather than a particular issue.

Right now the project is said to use gitflow workflow. This seems pretty consistent and nice, however it has a side effect of "breaking" `git describe`.

Even with `git describe --tags`, you can only get as close as `v0.0.1-4642-g1dbe19e` which is not very informative, but would be useful for identifying builds especially those from `develop` branch.

Is it possible to alter the workflow to fix this? Perhaps by merging released tags back to develop? Or tagging the development branches with a "dev" version of release tag?

**Comment by janisozaur** [comment]
https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow#release seems to have that covered by merging the released tag into development, just once. This should do the trick quite well.

**Comment by duncanspumpkin** [comment]
I had a read through that and I don't see where they merge the tagged release into develop. I see them merging the release branch into both but master and develop but I thought it was only tagged when it was merged to master.

**Comment by janisozaur** [comment]
> Once it's ready to ship, the release gets merged into master and tagged with a version number. In addition, it should be merged back into develop, which may have progressed since the release was initiated.

**Comment by IntelOrca** [comment]
That's referring only to the changes made on the release branch. It doesn't actually do
```
git checkout develop
git merge master
```

**Comment by IntelOrca** [comment]
@janisozaur Why not just do:
```
git describe --tags master
```

**Comment by janisozaur** [comment]
```
$ git describe --tags master
fatal: Not a valid object name master
$ git describe --tags origin/master
v0.0.2
```
It provides no information how far are you from from tag mentioned and moreover: no commit information whatsoever.

**Comment by IntelOrca** [comment]
Well it doesn't do that if you checkout master either.

**Comment by IntelOrca** [comment]
Is that actually related to master not being merged into develop?

**Comment by janisozaur** [comment]
yes. However, as you mentioned
```
git checkout develop
git merge release-0.0.2
```
This should provide nice description like (made up now): `v0.0.2-123-gabcdef1`

**Comment by janisozaur** [comment]
> Is that actually related to master not being merged into develop?

Exactly

**Comment by IntelOrca** [comment]
@janisozaur is this a big deal for you? Can't looking at a nice GUI of the network satisfy your needs?

**Comment by duncanspumpkin** [comment]
@IntelOrca I'd say do it from 0.0.3 on wards.

**Comment by janisozaur** [comment]
It sort of is. I'd like to create packaged versions of openrct, it would be a requirement for proper versioning of these.

**Comment by IntelOrca** [comment]
How does GitHub manage then?

**Comment by IntelOrca** [comment]
Also, we don't plan to actually tag anything on develop, so why isn't showing all the tags for master enough for this packaging to work?

**Comment by janisozaur** [comment]
> How does GitHub manage then?
Manage what exactly?

GitHub only shows tagged releases. This would be useful for daily/timed builds, where you could at least know on which version is it based. Also useful for properly reporting versions in other automated builds (like the ones from openrct.net).

It shouldn't really affect any other flow, just that you could get meaningful version information even on feature/development/testing branches, but the problem is that right now tags are not merged back to `develop`, so you can only reach `v0.0.1`, the initial commit.

For builds from `master` you would use just the version number.

**Comment by janisozaur** [comment]
Furthermore: I can see you almost do it already, see https://github.com/OpenRCT2/OpenRCT2/commit/c6b7ab2

Just that you missed to include the tagged commit and merged `v0.0.2^2` instead of `v0.0.2` which is the root cause for this thread.

**Comment by IntelOrca** [comment]
So is this is a fundamental flaw with git workflow or are we just doing the git workflow wrong?

**Comment by janisozaur** [comment]
I think there was something wrong with the way that particular release was
done. Github also seems to be somewhat contradicting itself as to where is
the tag really defined. If you look at commit preceding v0.0.2, the 8c…
one, it seems to have the tag on it, but then when you go to releases/tags
page, it lists v0.0.2 as b… (sorry, writing from memory). I can only guess
that what happened was perhaps you tagged the version locally, then made
additional commit to master merging the tag and pre-release and from
github's webui you created a release, which moved the tag away from
develop. This is only my guess.

If the tag were not moved (again, I guess), the merge back to develop would
be as dictated by gitflow and not having "repercussions" (I can't find a
better word here) now.

With v0.0.3, can I ask you to double check that the merge back to develop
is OK?

**Comment by IntelOrca** [comment]
I can't remember, I thought I would of merged to master first then tagged that merge commit.

**Comment by IntelOrca** [comment]
@janisozaur I did exactly as they described, I merged the release branch into develop rather than merging the master branch into develop.

![image](https://cloud.githubusercontent.com/assets/1482259/11070609/81dc2d0e-87d4-11e5-9bac-bc6e089d5a4c.png)

**Comment by janisozaur** [comment]
```
$ git describe --tags                        
v0.0.3-13-g396e6f8
```

Great job!

**Comment by duncanspumpkin** [comment]
I ended up not doing it exactly as per git workflow. It was in this order

merge pre-release to master
tag master
merge master to develop
