### ISSUE TITLE
Tertiary color not working on small scenery

### ISSUE THREAD

**Issue by Mmmmulder** [OpenRCT2/OpenRCT2#20356]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.5-71-g4a471a3 (4a471a3 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

Remappable tertiary color on small scenery is not possible to recolor.
It changes color in the scenery preview window, but when it's placed on the map, the color shows as black and it's not possible to recolor it.

### Steps to reproduce

1. select a small scenery parkobj with 3 remaps available
2. change color to something other than black before placing on map
3. try to recolor with re-paint tool after placing on map

### Attachments

![Screenshot_1](https://github.com/OpenRCT2/OpenRCT2/assets/77336136/45240ffe-bae6-4878-ad8b-916f9c87f926)
[acefanatic02.scenery_small.standing_sign_a.zip](https://github.com/OpenRCT2/OpenRCT2/files/11665865/acefanatic02.scenery_small.standing_sign_a.zip)

**Comment by Mmmmulder** [comment]
this issue don't seem to happen in release version 0.4.5

**Comment by SixFrags** [comment]
I hope this is fixed soon.

**Comment by Gymnasiast** [comment]
It looks like the code can _draw_ a third colour, but it looks like the action does not properly serialise the third colour.
