### ISSUE TITLE
Add a Guest Counter reset console command

### ISSUE THREAD

**Issue by JarnoVgr** [OpenRCT2/OpenRCT2#2035]
In the following save game the guest counter never goes below a certain number: https://openrct2.com/community/uploads/files/1441960333179-six-flags-magic-mountain6_2.sv6

This issue also happens on vanilla RCT2 and was most likely introduced by using trainers. Maybe a 'Peep Reset' console command can be made in OpenRCT2 to fix this issue?

=====
Posting on behalf of TsooJ: https://openrct2.com/community/topic/54/got-a-question-about-user-count

**Comment by HaasJona** [comment]
I think broken save games are better fixed by a more robust save game format after rewrite is complete. We probably can't implement workarounds for all the possible breakage with the current format.

**Comment by JarnoVgr** [comment]
I don't think we'll have a new save game format anytime soon. So as a temporary solution this could be implemented, if it's not too much work.

**Comment by duncanspumpkin** [comment]
I was thinking it would be implemented as a generic set guest counter x command.

**Comment by JarnoVgr** [comment]
Why is there even a static guest counter in the save file? I assume all peeps are stored, so it would be possible to just count those right?

**Comment by HaasJona** [comment]
Performance reasons probably. But I agree that the correct solution probably is to just count the peeps and not to implement crazy workarounds or console commands. I will look at your save file.

**Comment by IntelOrca** [comment]
One idea is to just update the counter when you load a saved game by counting the guests. There are many things which are cached in the saved game only to be instantly updated when you load the park. Park rating for example... but its convenient for any program wanting to just view the details of a saved game.
