### ISSUE TITLE
Integer overflow issue with the "Add/Set Money" cheat

### ISSUE THREAD

**Issue by AustinTSchaffer** [OpenRCT2/OpenRCT2#20364]
### Operating System

Linux 5.19.0-43-generic x86_64 GNU/Linux (64-bit Ubuntu)

### OpenRCT2 build

OpenRCT2, v0.4.5-78 (aec9cd730 on develop, DEBUG)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

The "Add/Set Money" controls in the "Financial cheats" menu appears to be experiencing an `int32` overflow issue. If you set the value to `214748364.80`, the menu overflows the value back down to `-214748364.80`, before adjusting the park's total cash.

It looks like the Cheats menu is using the correct data type ([`_moneySpinnerValue` is a `money64`](https://github.com/OpenRCT2/OpenRCT2/blob/aec9cd730683e68faea3d479de13c64a517492fc/src/openrct2-ui/windows/Cheats.cpp#L363)). It appears that the issue is happening when the Cheats menu invokes [`CheatsSet(CheatType::AddMoney, _moneySpinnerValue);`](https://github.com/OpenRCT2/OpenRCT2/blob/aec9cd730683e68faea3d479de13c64a517492fc/src/openrct2-ui/windows/Cheats.cpp#L718) or [`CheatsSet(CheatType::SetMoney, _moneySpinnerValue);`](https://github.com/OpenRCT2/OpenRCT2/blob/aec9cd730683e68faea3d479de13c64a517492fc/src/openrct2-ui/windows/Cheats.cpp#L792)

Relevant files:
- `src/openrct2-ui/windows/Cheats.cpp`
- `src/openrct2/actions/CheatSetAction.cpp`

Thanks for reading! Let me know if there's anything else I can do to help with this one. I have some C/C++ experience, but I'm pretty unfamiliar with the codebase, so I don't really understand how all of this hooks into the base game.

### Steps to reproduce

1. Open the Cheats menu.
2. Navigate to the Financial Cheats tab.
3. Set the input to `214748364.70` and select Add or Set. Notice that it appears to be working normally.
4. Set the input to `214748364.80` and select Add or Set. Notice how the game interprets the value as `-214748364.80`.

![image](https://github.com/OpenRCT2/OpenRCT2/assets/16184219/d86d071c-5b8a-491e-ba87-2a7a536d54a4)

![image](https://github.com/OpenRCT2/OpenRCT2/assets/16184219/75f102f0-9b93-4af8-a3d2-2c6da67c15e0)

**Comment by ZehMatt** [comment]
Please always fill in the actual commit, is this on the latest develop branch or just the 0.4.5 release? If its the release also test the latest development branch.

**Comment by AustinTSchaffer** [comment]
I managed to build the project off the `develop` branch and confirmed that the bug is still present. I updated the version info on this ticket as well as on https://github.com/OpenRCT2/OpenRCT2/issues/20365.

**Comment by ZehMatt** [comment]
> I managed to build the project off the `develop` branch and confirmed that the bug is still present. I updated the version info on this ticket as well as on #20365.

Thanks, also confirmed it from my end.
