### ISSUE TITLE
Currupted saved landscape files

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#2037]
Steps to reproduce:

1. Open Scenario Editor
2. Don't do anything, just save the landscape
3. Restart OpenRCT2 (or maybe load another map first, I haven't tried that)
4. Open the Scenario Editor again
5. Open the landscape you just saved

After loading the map I was unable to move the view over the map completely, just like when you try to move against the invisible edges of the map, as if the entire map has an offset.

On addition when you want to buy land it looks like in this screenshot:

![btfqztk 1](https://cloud.githubusercontent.com/assets/9705046/10341669/f7b9298e-6d15-11e5-93a0-1a6f6199f5b5.png)

It also generates the following warning:
<tt>ERROR[..\src\world\map.c:166 (map_get_first_element_at)]: Trying to access element outside of range</tt>

Edit: On the map interface you can also see that the view does not match the highlighted area.
Edit 2: It feels like the top-left corner is the actual focus point of the camera when zooming in and out.

**Comment by Broxzier** [comment]
It seems to be working in the latest build. Has it been fixed?

**Comment by PFCKrutonium** [comment]
If it's working, it may have been fixed inadvertently.

**Comment by desertspider** [comment]
Not fixed, Got the same problem. Probably same problem as #2068 .

**Comment by desertspider** [comment]
Ok, i found a way to reproduce the bug, and fix the save.

Reproduce bug:
1. Create new scenario.
2. Go to step 2.
3. Zoom out
4. Save
5. Load same scenario
6. Grid is broken. (mountain tool, buy land tool)

To fix the the corrupted save:
7. zoom al the way in
8. save
9. Load save
10. fixed!

So; when loading a save which was not zoomed in all the way. the camera goes to the right bottom of the original location where the camera was when saved.
