### ISSUE TITLE
Plugin/custom windows are missing the left border in the title bar

### ISSUE THREAD

**Issue by Basssiiie** [OpenRCT2/OpenRCT2#20417]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.5-86-gdad2d80 (dad2d80 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

In the most recent develop it seems that the left border of the title bar has disappeared for plugin windows/custom windows. Regular game windows are unaffected by this issue.

![image](https://github.com/OpenRCT2/OpenRCT2/assets/20048660/26a8d60f-8cc3-446d-953c-e4d0a56871ad)

Here's how it looks like with the "window buttons on the left" option enabled, where the issue is also visible:

![image](https://github.com/OpenRCT2/OpenRCT2/assets/20048660/8ce3b051-85de-4d0c-8af2-80e16eb94eaa)

On Discord the issue was suspected to be related to the recent addition of this option in #20176.

### Steps to reproduce

1. Download a plugin with a window.
2. Open the window.
3. Spot the missing border on the left side.

**Comment by Gymnasiast** [comment]
I think this might be the result of these windows being initialised as 0 × 0 windows and then resized. Normally, the title bar would start at 1, but this is beyond the initial limits of that window. It might be better to initialise them as something like 50×50 and then resize.

The odd sizing nature of this window caused me problems when I refactored the `×` button code.
