### ISSUE TITLE
All "L" characters displays as "ᴎ" with a line over it

### ISSUE THREAD

**Issue by ethanaobrien** [OpenRCT2/OpenRCT2#20416]
### Operating System

Android 13

### OpenRCT2 build

v0.4.5

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

All "L" characters displays as "ᴎ" with a line over it. Not much more to add then that.

I have a samsung galaxy S23 (base model), running Android 13.

### Steps to reproduce

1. Open the game.
2. Open a window with an "l"

### Attachments

![Screenshot_20230618_091552_OpenRCT2](https://github.com/OpenRCT2/OpenRCT2/assets/77750390/1ab4654c-e376-49a8-99f4-798c1b04059c)
![Screenshot_20230618_091507_OpenRCT2](https://github.com/OpenRCT2/OpenRCT2/assets/77750390/4d3a4210-0f8f-4866-8c91-0ec9295b2a24)
![Screenshot_20230618_090952_OpenRCT2](https://github.com/OpenRCT2/OpenRCT2/assets/77750390/28de9e33-74c4-409f-bdbd-2a391a066a8c)

**Comment by Basssiiie** [comment]
Your G2 (OpenRCT2 data file) is from a different version of OpenRCT2 than the APK. 

Make sure you download the OpenRCT2 data files for the exact same version as the APK. Even if they're from slightly different commits, they may already cause this exact issue.

See: https://github.com/OpenRCT2/OpenRCT2/wiki/Android

**Comment by ZehMatt** [comment]
See previous comment, not a bug.

**Comment by ethanaobrien** [comment]
@ZehMatt @Basssiiie 

This is a fresh install, and those were the instructions I followed. I'm using the stable version, so shouldn't all those be the same commit? To test, I deleted my openrct2 data directory, and downloaded a new one directly from the downloads page, and copied the files over, all on my phone, and this does not solve the issue. 

I also tried opening the app without the g2.dat at all, and somehow it still worked, but instead of all the "l"s displaying as another character, they just didn't show at all.

Are the stable builds from different commits? Which one should I download to take assets from?

**Comment by ZehMatt** [comment]
If the game runs without the g2.dat then your installation is probably not correct as it can not run without this file so there has to be another copy somewhere.

**Comment by ethanaobrien** [comment]
@ZehMatt 

Where else would it be if this is on android? When the file isn't present It gives me this error message (screenshot below) but when I click ok it still launches. 

![Screenshot_20230618_095049_OpenRCT2.jpg](https://github.com/OpenRCT2/OpenRCT2/assets/77750390/a065de64-5240-46c9-8241-f9d606cc18b5)

**Comment by Basssiiie** [comment]
@ethanaobrien If you'd like the release then the g2.dat must also be from the same release (and not from a develop version). Releases with the same number should already be from the same commit. Maybe you have another g2.dat somewhere else on your phone?

For example:
- Take the v0.4.5 release APK: https://github.com/OpenRCT2/OpenRCT2/releases/download/v0.4.5/OpenRCT2-0.4.5-android-arm.apk
- Take the v0.4.5 release data files from here: https://github.com/OpenRCT2/OpenRCT2/releases/download/v0.4.5/OpenRCT2-0.4.5-windows-portable-win32.zip

**Comment by ethanaobrien** [comment]
I managed to fix it. I did have the correct files downloaded, but I only had `game_path` set, not `rct1_path`. Setting `rct1_path` and `game_path` to the same thing fixed the issue.

Sorry for the trouble and time. Thank you for your help!
