### ISSUE TITLE
Guests are entering queue and almost immediately are pissed off about being in the queue for so long.

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#2042]
https://files.gitter.im/OpenRCT2/OpenRCT2/non-dev/5n6W/Queue.sv6

**Comment by HaasJona** [comment]
I can reproduce this.

peep->days_in_queue seems to contain reasonable values, like from 0-10.

peep->time_in_queue however usually contains huge values in the range of 62000 ~ 65000 that seem quite like an underflow is happening somewhere. But in the decompiled code I can see nothing suspicious. This also happens with fresh guests after clearing all guests from the park.

**Comment by duncanspumpkin** [comment]
This is an original bug and it is caused by having entertainers.

To fix this bug we need to do some more implemenation of the peep code. Specifically 0x006BF926->0x006c05ae->0x006c086d

**Comment by StickGuySeven** [comment]
@duncanspumpkin is this fixed yet?

**Comment by duncanspumpkin** [comment]
I think it was but I can't remember

**Comment by HaasJona** [comment]
Doesn't look like it's fixed. But should be easy now as the code is decompiled.

Just need to make sure there is no underflow here:

https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/peep/staff.c#L1243

**Comment by PFCKrutonium** [comment]
RIP this bug.
