### ISSUE TITLE
Multiplayer Bug: When building a Rollercoaster, Paint colors will be different, causing a desync.

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#2043]
![screenshot 23](https://cloud.githubusercontent.com/assets/3945538/10354056/37078a2c-6d2a-11e5-89db-4f89719dc9aa.png)

**Comment by pizza2004** [comment]
Is this the reason why I often see a desync any time my friend tries to build a ride, /especially/ a rollercoaster?  It just seems virtually unplayable without the desync kicking turned off.

**Comment by IntelOrca** [comment]
@PFCKrutonium I hope you mean that it actually triggers the first desync (message pops up).

Yes ride creation definitely has some ND issues, but its also because the ride track previewer is using game commands, or not using game commands but using scenario_rand. Definite problem there.

**Comment by PFCKrutonium** [comment]
Ye, it triggers a Desync.

**Comment by duncanspumpkin** [comment]
Fixed in the pre-release.
