### ISSUE TITLE
Cannot cycle through trains/views by single-clicking into dropdown menu in main ride window

### ISSUE THREAD

**Issue by zzril** [OpenRCT2/OpenRCT2#20433]
### Operating System

Linux (probably irrelevant)

### OpenRCT2 build

latest develop (97427743a4ace9f16ebd913ed418d524cb6bc9d9)
Update: Bug occurs first in ce1695fab84e8be09df98686fff2cd057cb5ec2a

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

In the main view of the ride window, it used to be possible to cycle through all possible views (different trains, stations, "overall view") just by clicking once into the dropdown menu. (I.e., one single click would simply jump to the next view.)

Currently, this is not possible anymore.
(Instead, one has to now actually open/use the dropdown menu by holding the mouse button, moving the cursor to the desired view and then releasing it.)

### Steps to reproduce

Open any park with at least one tracked ride.
Single-click into the "overall view" / "train 1" / "train 2" / etc dropdown and notice that nothing happens. (Don't open the menu by holding the mouse button, just click and release immediately.)

### Attachments

![menu0](https://github.com/OpenRCT2/OpenRCT2/assets/84280965/4ed6e1ac-ae6b-494d-9e3a-797607a1b05e)
![menu1](https://github.com/OpenRCT2/OpenRCT2/assets/84280965/842c0ce7-2093-44b6-8eb5-5c0d3e29e8f1)
(This is the menu I'm talking about.)

**Comment by duncanspumpkin** [comment]
I recently refactored the window. So that will be the commit that broke it.

**Comment by duncanspumpkin** [comment]
Well this is annoying i know why its broken but I'm not sure how much would break from fixing it. The problem is https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/interface/Window.cpp#L1453 which hides the no selection dropdown event. We need to go through and verify every single drop down event before removing that if.
