### ISSUE TITLE
Introduce window method to resize spinner/stepper

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#20430]
This currently involves modifying three widgets manually. Putting this in a method of its own not only makes the code cleaner, it also makes it feasible to draw them bigger when using OpenRCT2 on touch devices.

ResizeFrame() / ResizeFrameWithPage() can be used for inspiration.

**Comment by Broxzier** [comment]
Ideally, spinners and other multi-widget windows elements are standalone widgets on their own. This will make it easier to have a consistent layout too. Moving to a member function to resize the separate widgets sure is a step in the right direction.

**Comment by Gymnasiast** [comment]
That sounds like a good idea. I guess the complicating factor is handling button events. Currently it just listens for the - and + buttons and modifies the value accordingly. I’m not sure how to pull that off with a single widget, but maybe someone has ideas.

**Comment by mrmbernardi** [comment]
Do you have an example of a window that resizes the spinner widget by widget so I can have something to work on?

**Comment by spacek531** [comment]
ride construction brake speed I believe does that

**Comment by Gymnasiast** [comment]
Fixed by https://github.com/OpenRCT2/OpenRCT2/pull/20545.
