### ISSUE TITLE
Some shortkeys do not work if the buttons on the top are not visible

### ISSUE THREAD

**Issue by nisage** [OpenRCT2/OpenRCT2#20448]
### Operating System

Windows 10 64

### OpenRCT2 build

OpenRCT2, v0.4.5 (76ca840) provided by GitHub

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

This is a development issue

### Describe the issue

I seted all the shortcuts but some of them do not work if the menu bar on the top are not visible. For exemple, the shortcut to make path do not work but when I press the shortcut to show the buttons this start to work again. The shortcut to deal with water same thing. 

### Steps to reproduce

1. Hide all the buttons on the screen
2. Try to execute the shortcut to make roads/paths

**Comment by AaronVanGeffen** [comment]
Has been resolved by #22411, which was merged for the latest release.
