### ISSUE TITLE
Tile inspector does not invalidate highlighted object on close

### ISSUE THREAD

**Issue by mrmbernardi** [OpenRCT2/OpenRCT2#20481]
### Operating System

Linux

### OpenRCT2 build

OpenRCT2, v0.4.5-107 (97427743a on develop, DEBUG)

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Please see the video.

[output.webm](https://github.com/OpenRCT2/OpenRCT2/assets/7877312/c6aeb671-05ed-487b-bbff-21501fcd8224)

### Steps to reproduce

1. Highlight something with the tile inspector.
2. Close the tile inspector window somehow (e.g. with backspace) with the mouse over selection somewhere far away from the previously highlighted object.

**Comment by aramk-hub** [comment]
Hi, I'm new to open source contributing so I just wanted to make sure, it seems like this issue was resolved correct?

**Comment by ZehMatt** [comment]
When it has commits assigned then its most likely being worked on already.
