### ISSUE TITLE
Compact Inverted Coaster no longer has relaxed stat requirements if it has inversions

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#20496]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT v0.4.5

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

The Compact Inverted is supposed to have its requirement for the drop height nullified if it has at least one inversion, but as of v0.4.5 that's no longer the case.

I believe this line should say true instead of false: https://github.com/OpenRCT2/OpenRCT2/blob/d40102aa9ded9d8ef6d5e434d9dcde959ced44dc/src/openrct2/ride/coaster/meta/CompactInvertedCoaster.h#L62C11-L62C11

### Steps to reproduce

Build the attached ride design both in version 0.4.4 and 0.4.5 and see how the stats are halved in 0.4.5. 

### Attachments

[Inverted Vertical Shuttle cheap.zip](https://github.com/OpenRCT2/OpenRCT2/files/11880582/Inverted.Vertical.Shuttle.cheap.zip)

**Comment by aramk-hub** [comment]
Hi, can I claim this? I'm new to open source contribution and this seems like a simple fix.
