### ISSUE TITLE
Options window doesn't properly resize when switching tabs

### ISSUE THREAD

**Issue by zzril** [OpenRCT2/OpenRCT2#20491]
### Operating System

Linux

### OpenRCT2 build

3b7975f4a06abf2e11178041cc85477c73b01a60 (latest develop)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

This has started only a few days ago.

In the options window, when switching tabs, the window does not get properly resized.
When switching to a tab that requires a smaller window, a blue rectangle is left on the lower part.
When switching to a tab that requires a larger size, the background in the lower part is not properly drawn.

### Steps to reproduce

1. Open Track Designer (for more stable background)
2. Open Options window
3. Switch tabs to `Controls and Interface` (lower part lacks background)
4. Switch to `Audio` (looks normal now)
5. Switch to `Display` tab (middle part lacks background, empty blue rectangle below)
6. Close window (blue rectangle remains)

Do not move the mouse to the edge of the screen, that forces everything to be redrawn correctly.

### Attachments

![glitch-0](https://github.com/OpenRCT2/OpenRCT2/assets/84280965/9a608a20-1879-45ce-aac6-50a6c87728da)
![glitch-1](https://github.com/OpenRCT2/OpenRCT2/assets/84280965/020ecaa2-6d58-4a14-b481-8fa4ae1cc651)
![glitch-2](https://github.com/OpenRCT2/OpenRCT2/assets/84280965/74d1921a-7b39-4199-9b54-c6dc59175c22)
![glitch-3](https://github.com/OpenRCT2/OpenRCT2/assets/84280965/0a3a6517-fe31-4eac-aad7-ef99da696a31)
![glitch-4](https://github.com/OpenRCT2/OpenRCT2/assets/84280965/b0a6a3b4-fa16-46d2-b391-1f075b96120e)

**Comment by zzril** [comment]
Possibly a duplicate of #20312, though I though I've only seen this happening since the recent window refactor.

**Comment by ZehMatt** [comment]
> Possibly a duplicate of #20312, though I thought I've only seen this happening since the recent window refactor.

Same issue.
