### ISSUE TITLE
Peeps only throw up when walking along one axis

### ISSUE THREAD

**Issue by clamburger** [OpenRCT2/OpenRCT2#2049]
Here's an interesting one.

**RCT2:**
![scr1](https://cloud.githubusercontent.com/assets/1396298/10416068/eb48bd3c-7048-11e5-9187-b3a08b4063f2.png)

**OpenRCT2:**
![scr1](https://cloud.githubusercontent.com/assets/1396298/10416069/faa2671a-7048-11e5-9191-8537d3326cfd.png)

Built from source using latest develop. Camera rotation does not affect the direction that peeps throw up in.

**Comment by HaasJona** [comment]
Confirmed. In OpenRCT2 guests only puke when going in positive/negative X direction.

**Comment by duncanspumpkin** [comment]
I can't reproduce this can someone provide a save with this happening

**Comment by HaasJona** [comment]
This can be easily reproduced in any save if you just change the code so peeps always throw up. For example:

```
Index: src/peep/peep.c
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/peep/peep.c	(revision 6c84b06fbd5224a66354b090cc7104f842f7c33a)
+++ src/peep/peep.c	(revision )
@@ -650,11 +650,11 @@
 			peep->bathroom--;
 		}
 
-		if (peep->state == PEEP_STATE_WALKING &&
+		if (true || peep->state == PEEP_STATE_WALKING &&
 			peep->nausea_growth_rate >= 128){
 
-			if ((scenario_rand() & 0xFF) <= (uint8)((peep->nausea - 128) / 2)){
-				if (peep->action >= PEEP_ACTION_NONE_1){
+			if (true || (scenario_rand() & 0xFF) <= (uint8)((peep->nausea - 128) / 2)){
+				if (true || peep->action >= PEEP_ACTION_NONE_1){
 					peep->action = PEEP_ACTION_THROW_UP;
 					peep->action_frame = 0;
 					peep->action_sprite_image_offset = 0;
```
