### ISSUE TITLE
Tile inspector does not invalidate stuff in general

### ISSUE THREAD

**Issue by mrmbernardi** [OpenRCT2/OpenRCT2#20503]
### Operating System

Linux

### OpenRCT2 build

OpenRCT2, v0.4.5-107 (97427743a on develop, DEBUG)

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Apologies for the bad name but in this one video I've caught the tile inspector not invalidating a track piece after changing it, and also not updating its window state properly. 

When I use the inspector to add a chain lift to a track, the track isn't redrawn and the checkbox I used also desynchronises until its forced to redraw by panning the screen. See the video. Please use sound to hear when I make the clicks.

[ti.webm](https://github.com/OpenRCT2/OpenRCT2/assets/7877312/bbfc6dc9-a17f-4128-b30e-2193b05affa6)

### Steps to reproduce

Use the tile inspector like I do in the video.

**Comment by ZehMatt** [comment]
Fixed by #20591
