### ISSUE TITLE
Cannot turn on Allow Special Color Schemes

### ISSUE THREAD

**Issue by astraylife1** [OpenRCT2/OpenRCT2#20500]
### Operating System

MacOS

### OpenRCT2 build

OpenRCT2, v0.4.5 (cf7c486 on develop)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

Just updated to the new development build and I no longer can turn on Allow Special Colour Schemes under the Cheats menu. For parks where this is already turned on, if I turn it off, I no longer can turn it back on.

No error is given. It shows a red text box with no text inside.

### Steps to reproduce

Open cheats menu
Try to select Allow Special Colors

**Comment by ZehMatt** [comment]
Regression from #20474, now it validates the parameters and some things are missing or have the wrong parameter range.
