### ISSUE TITLE
Splitting queue line path

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#2051]
When placing an entrance or exit for an attraction aligned with a queue line path, the path will stay connected with the two tiles it was already connected to but also to the entrance.

1. Build a path like this: http://i.imgur.com/sfqwvHC.png
2. Place the entrance: http://i.imgur.com/JlbDTvU.png

After having played a with with it for some time, it seems like the queuing in line works for both sides. Also guests can take change direction and "wait in line" while they are walking the wrong way (http://i.imgur.com/i4dosks.png).
As soon as there is a line of people waiting, the path that the they are queuing from  works fine, and the other people from the other line will start walking instead once they reach the entrance.

**Comment by IntelOrca** [comment]
For those that are confused, the queue path is still there but is a three way connection. There are no sprites for queue junctions which is why the queue path looks like its disappeared.
