### ISSUE TITLE
Ghosts without clearance replaces objects

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#2053]
When placing a ride or coaster while having the clearance checks disabled, the parts of this ride that are at the same position will be overridden by the ghost, causing a "ride" crash when you move your ghost away again.

This video should explain it more clearly: http://youtu.be/4Xl0AGdTDg4

It only works when you have clearance checks disabled, not during normal gameplay.

**Comment by IntelOrca** [comment]
That's quite amusing.
I think this can be fixed by my making the track placement only remove ghost pieces.

**Comment by Patrik356b** [comment]
i lol'd at the video, but I thought the game would crash tho, judging from the posted text

**Comment by Broxzier** [comment]
Whoops, could've been more clear that it's an in-game crash.

**Comment by mrtnptrs** [comment]
Sadly, this bug got less amusing: the game crashes now when doing these steps (using wooden coaster). Using commit 
42029c0

Dump: https://github.com/OpenRCT2/OpenRCT2/pull/3081

Hopefully you can fix this bug, using the information from the dump file.
