### ISSUE TITLE
Attempting to landscape while constructing coaster causes gridlines to disappear

### ISSUE THREAD

**Issue by zornor** [OpenRCT2/OpenRCT2#2058]
Started playing 0.0.3 build 1311 (1629c75), was making a Junior Roller Coaster on Bumbly Beach and used the landscaping tool to move some earth, with the RC's construction menu open. Then the gridlines/cursor for the landscaping tool just disappeared, preventing me from making any landscape changes. I managed to get it to happen again once, after restarting the game. Unfortunately, I can't seem to reproduce it anymore, but it happened while I was replacing parts of my ride. Reloading a save also fixes it. I had not encountered this glitch on previous builds.

**Comment by Patrik356b** [comment]
I have encountered this on an old build

**Comment by duncanspumpkin** [comment]
This is a known bug but I don't think anyone has a reliable way of reproducing it

**Comment by duncanspumpkin** [comment]
Duplicate of #1619.
