### ISSUE TITLE
parkinfo objects crashing

### ISSUE THREAD

**Issue by Richard-L** [OpenRCT2/OpenRCT2#20599]
### Operating System

Win11 x64

### OpenRCT2 build

OpenRCT2, v0.4.5-204-ga7881a5 (a7881a5 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

ORCT2 crashes upon using the parkinfo command with "objects", quoting "Mixed install detected." and several object conflicts.

### Steps to reproduce

1. Save any scenario into a new .park
2. Run "openrct2.com parkinfo objects <save>" on the file

**Comment by Richard-L** [comment]
It seems to work on another computer. Any clue as to what might be wrong with my setup that the "mixed install" message should appear?

**Comment by ocalhoun6** [comment]
This usually happens because something went wrong during an update.

Did you update OpenRCT2 lately, and how did you do it?

**Comment by Richard-L** [comment]
Thanks for getting back. I typically update via the "old" launcher which is set to develop.

Letting it switch to release doesn't help with the problem though.

Should I redo my entire ORCT2 setup?

**Comment by ocalhoun6** [comment]
Yeah, that launcher tends to cause problems sometimes. If you reinstall OpenRCT2, this will be fixed. (And, ideally, no longer using the old launcher.)


You don't have to lose any saved games or game progress, though. Make a backup of the OpenRCT2 data folders before reinstalling, being sure to save anything you care about.

**Comment by Richard-L** [comment]
Thanks @ocalhoun6 . A fresh install seems to have fixed it.

Before I close this, there's still a mention of one object conflict in parkinfo's output:

```
\Documents\OpenRCT2\bin\data\object\rct2\audio\rct2.audio.base.json'
\Documents\OpenRCT2\bin\data\object\rct2\audio\rct2.audio.base.rctc.json'
```
Is this normal, or do I need to delete one?

**Comment by ZehMatt** [comment]
> Thanks @ocalhoun6 . A fresh install seems to have fixed it.
> 
> Before I close this, there's still a mention of one object conflict in parkinfo's output:
> 
> ```
> \Documents\OpenRCT2\bin\data\object\rct2\audio\rct2.audio.base.json'
> \Documents\OpenRCT2\bin\data\object\rct2\audio\rct2.audio.base.rctc.json'
> ```
> 
> Is this normal, or do I need to delete one?

This is normal, you can safely ignore that.

**Comment by Richard-L** [comment]
Thanks. Will close this.

If you're inclined, I'd love to know why it reports a conflict.

**Comment by ZehMatt** [comment]
> Thanks. Will close this.
> 
> If you're inclined, I'd love to know why it reports a conflict.

It's a false warning, we install the two objects with identical ids so it can fallback to when one of the content sources is missing, there is no real conflict here, its just being unfortunately logged as one. One of the things we have to re-work at some point.
