### ISSUE TITLE
`Save this` popup when attempting to quit track designer

### ISSUE THREAD

**Issue by zzril** [OpenRCT2/OpenRCT2#20616]
### Operating System

Linux

### OpenRCT2 build

8c0a931403e87b86ee4a2bf212fc7efe70e8e5a1 (latest develop)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

In the track designer, when attempting to quit the game or go back to main manu, a diaglog sometimes pops up asking me to `Save this be...`.
It has only the `save` and `cancel` option, the former one ending the game without any apparent side effect (game didn't appear to actually save anything), and the latter one bringing me back to track designer.

Possibly this is just a string error and the button should rather say sthg like `quit anyway`?

---

I could so far not exactly figure out when this happens and when not, but building larger coasters and changing the train settings (number of trains, reversing them) seems to make it more likely.

The steps described below in `Steps to reproduce` always lead to the dialog popping up.

### Steps to reproduce

1. Open track designer
2. In ride type selection, select Corkscrew Coaster (RCT2)
3. Proceed to track designer
4. Build Great American Scream Machine
5. Go to vehicle details tab and select `Reversed Trains` (or, alternatively, reduce number of trains to 2)
6. Test the ride and wait until stats are calculated
7. Try to quit the game
8. Popup appears asking you to save

### Attachments

![save-popup](https://github.com/OpenRCT2/OpenRCT2/assets/84280965/54f3de2b-4587-4ae4-adb9-3da3ccb037c4)

**Comment by zzril** [comment]
From reading the code in [SavePrompt.cpp](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2-ui/windows/SavePrompt.cpp) and checking with `gdb`, it seems that the popup is intended, but the button shows the wrong text (should be `STR_OK`).

At the beginning of `SavePromptWindow::OnOpen`, we check for track designer or track manager (which have no "save" option):  
```cpp
        if (gScreenFlags & (SCREEN_FLAGS_TRACK_DESIGNER | SCREEN_FLAGS_TRACK_MANAGER))
        {
            widgets = _quitPromptWidgets;
        }
```
`_quitPromptWidgets` being defined a few lines above:  
```cpp
static Widget _quitPromptWidgets[] = {
    WINDOW_SHIM_WHITE(STR_QUIT_GAME_PROMPT_TITLE, WW_QUIT, WH_QUIT),
    MakeWidget({ 8, 19}, {78, 14}, WindowWidgetType::Button, WindowColour::Primary, STR_OK    ), // ok
    MakeWidget({91, 19}, {78, 14}, WindowWidgetType::Button, WindowColour::Primary, STR_CANCEL), // cancel
    WIDGETS_END,
};```
This seems to set up the intended behaviour, with `STR_OK` rather than `STR_SAVE_BEFORE_QUITTING` or `STR_SAVE_BEFORE_QUITTING_2`.  
If I understand correctly, the first line is a macro that makes up multiple entries, so the `STR_OK` widget ends up at array index 3?  
Anyway, a problem seems to be that that array is global and writable...

At the end of `OnOpen`, we do this:  
```cpp
        widgets[WIDX_LABEL].text = window_save_prompt_labels[EnumValue(_promptMode)][1];
```
Effecting overwriting the global `_quitPromptWidgets[3]` with a value taken from `window_save_prompt_labels`, which are defined as:  
```cpp
static constexpr StringId window_save_prompt_labels[][2] = {
    { STR_LOAD_GAME_PROMPT_TITLE,   STR_SAVE_BEFORE_LOADING },
    { STR_QUIT_GAME_PROMPT_TITLE,   STR_SAVE_BEFORE_QUITTING },
    { STR_QUIT_GAME_2_PROMPT_TITLE, STR_SAVE_BEFORE_QUITTING_2 },
    { STR_NEW_GAME,                 STR_SAVE_BEFORE_QUITTING },
};
```
  
`_promptMode` at this point is `SaveBeforeQuit` (=1, see [Window.h](https://github.com/OpenRCT2/OpenRCT2/blob/ce0cc9fc84c5f7aa3fe16ec2695c7a1c3448bee1/src/openrct2/interface/Window.h#L399-L406)), so we end up choosing `STR_SAVE_BEFORE_QUITTING` and write that into `widgets[WIDX_LABEL]`, which a) gives us the wrong string in the current window to-be-created, and b) overwrites the `STR_OK` in the global `_quitPromptWidgets`.

---

Not sure how this should best be done.  
My guess is that in the pure "quit" prompt (that we get in the track designer / track manager; with no option to save anything), we should not set `widgets[WIDX_TITLE].text` or `widgets[WIDX_LABEL].text` at all - all values are already taken correctly from `_quitPromptWidgets`. Only in the "save" prompt (park, scenario editor), we need to make some further modifications to the window, such as setting the title specific to where we are (game, scenario editor).  
In any case, however, we probably do not want to write to the local `widgets` array directly as that points to either the global `_quitPromptWidgets` or the global `_savePromptWidgets`. My guess is that for the save prompt, we need to make a local copy first. And I guess we should also declare the globals constant then?

**Comment by tupaschoal** [comment]
Nice investigation. That window was refactored a few versions ago, on PR #18335, can you check if v0.4.2 shows the same behavior?

**Comment by zzril** [comment]
The button correctly says `OK` both before and after the merge of the PR linked by you.

PR #20572 introduced the incorrect string. In 0a3573ec67c4992e5d119ea75de454a651c5e70c (right before the merge of that PR), it still says `OK`, then in ea3508b22ca0af8a9f43666691fd7f4033b72e22 (merge commit of PR #20572 ) it says `Save this be...`

Merely restoring the old behaviour (button says `OK`) should be possible by just skipping these last two lines from [OnOpen](https://github.com/OpenRCT2/OpenRCT2/blob/0e5c82e2d4c774cd6b98a4b21b460cbd41aa6355/src/openrct2-ui/windows/SavePrompt.cpp#L120-L121) if we're in the track designer / manager:
```cpp
        widgets[WIDX_TITLE].text = stringId;
        widgets[WIDX_LABEL].text = window_save_prompt_labels[EnumValue(_promptMode)][1];
```
Will try that out in a moment.

Thinking more about this, however, it would probably make sense to change the title of the window as well. It says `Quit Game` (that wasn't changed by any of the linked PRs), but that's kind of misleading as we're merely quitting the track designer, not the whole game.  
*That*, however, may require some further work as it means we cannot make use of the global `_quitPromptWidgets` anymore. (Or, at least, we would need to hack in the specific title (quit game / track designer / track manager) as we do in the other case with the "save" prompt.)
