### ISSUE TITLE
OpenRCT2 Logo is overlapping the display

### ISSUE THREAD

**Issue by A500000** [OpenRCT2/OpenRCT2#20629]
### Operating System

Windows 10 64 bit

### OpenRCT2 build

OpenRCT2 v0.4.0 (c6302a1)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

the openRCT2 logo is overlapping the top left-hand side of my display and it wont go away.

### Steps to reproduce

open the selected file
look in the top left corner

### Attachments

[examplePark.zip](https://github.com/OpenRCT2/OpenRCT2/files/12084997/examplePark.zip)
![Unnamed park 2023-07-18 10-49-31](https://github.com/OpenRCT2/OpenRCT2/assets/80475825/8d947a0c-6bd5-4b6e-bdf4-7e645a1d1ece)

**Comment by ZehMatt** [comment]
You are using a quite old version, please check if this happens on the latest one.

**Comment by Gymnasiast** [comment]
Caused by mismatching g2.dat
