### ISSUE TITLE
IME window not positioned correctly

### ISSUE THREAD

**Issue by mrmbernardi** [OpenRCT2/OpenRCT2#20631]
### Operating System

Any

### OpenRCT2 build

OpenRCT2, v0.4.5-229 (ce86aa029 on develop, DEBUG)

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Describe the issue

The IME window is not properly positioned with the text box you're editing.

See: https://github.com/OpenRCT2/OpenRCT2/blob/ce86aa029fa20beaa00d6cf6070d3bea6a625bb9/src/openrct2-ui/TextComposition.cpp#L41

### Steps to reproduce

1. Open a text box
2. Type with an IME

**Comment by pcabaniss** [comment]
Id like to give this one a go.

**Comment by wstagg** [comment]
I would like to pick this up but I am not sure how to replicate it?

**Comment by mrmbernardi** [comment]
> I would like to pick this up but I am not sure how to replicate it?

Set your keyboard settings to type with a language that uses an IME (e.g. Chinese or Japanese) and then start typing in any text box in the game.

**Comment by wstagg** [comment]
Okay, thank you. I will check it out

**Comment by wstagg** [comment]
![Screenshot 2023-09-14 at 23 39 14](https://github.com/OpenRCT2/OpenRCT2/assets/103323985/89dd8b87-fc15-464e-bd1a-891789e30fcc)

Which of these is the issue?

**Comment by wstagg** [comment]
![Screenshot 2023-09-14 at 23 39 14](https://github.com/OpenRCT2/OpenRCT2/assets/103323985/3a1ccd9b-5c7b-4070-aac7-37819cd84f57)

Which of these is the issue? 

Thanks

**Comment by mrmbernardi** [comment]
The main issue is the box in the top left not being next to the text box, but on second thought both of them are. Perhaps we should remove the black box if the menu for the user's IME is properly working.

**Comment by wstagg** [comment]
Yeah I think the small box with the question marks should go. Would you like me to remove this?

**Comment by mrmbernardi** [comment]
Yes. With the IME suggestion box working properly there's no need for it. It also looks like it doesn't work anyway.

**Comment by c-pg-vega** [comment]
Hi has this issue been resolved?

**Comment by wstagg** [comment]
> Hi has this issue been resolved?

I am currently working on it
