### ISSUE TITLE
Swinging inverter ship animation broken

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#2063]
Seems to happen in every scenario, with all types of swinging inverter ship (i.e. including custom content).

![scr124](https://cloud.githubusercontent.com/assets/1478678/10514628/2be351dc-734f-11e5-91d3-808c574f5727.png)

**Comment by xperia64** [comment]
A similar issue occurs with Top Spin. The arms rotate and the cars rotate, but the cars remain at the bottom of the ride unattached from the arm.

**Comment by duncanspumpkin** [comment]
I can't reproduce this 
![swinginginverter](https://cloud.githubusercontent.com/assets/1277401/10563688/99d2907a-758b-11e5-9558-6f82b45bcc60.PNG)

**Comment by PFCKrutonium** [comment]
![scr35](https://cloud.githubusercontent.com/assets/3945538/10563692/3ec14696-7562-11e5-8c42-d368ff0fc26d.png)
Also can not confirm.

**Comment by warmwaffles** [comment]
@Gymnasiast can you provide a save for this?

**Comment by xperia64** [comment]
@Gymnasiast are you running this on Linux? I just checked that the similar Top Spin issue doesn't occur on Windows.

**Comment by Gymnasiast** [comment]
Yes, I am running on Linux. And it happens in _every_ park for me. Opening Six Flags Holland shows a broken Excalibur, a Top Spin, exhibiting the behaviour @xperia64 described in his comment.

**Comment by IntelOrca** [comment]
@Gymnasiast wine or native?

**Comment by Gymnasiast** [comment]
Native.

**Comment by duncanspumpkin** [comment]
Must be a bug in viewport_track_paint_setup 0x006C4794

**Comment by IntelOrca** [comment]
@Gymnasiast does it happen if you use wine on a build from openrct2.com?

**Comment by HaasJona** [comment]
Not Gymnasiast, but I get the following situation:
- Native Linux build has the broken animations
- Original RCT2 on Wine has fine animations
- Latest OpenRCT2 on Wine has fine animations but is otherwise completely broken (when loading Six Flags Holland all rides and guests are missing, sound quality is very bad)

**Comment by Gymnasiast** [comment]
Latest OpenRCT2 build from openrct2.com on Wine has correct animations.

(And also correct rides and guests, unlike @HaasJona. Did you select 'Build your own Six Flags Holland' by accident?)

**Comment by HaasJona** [comment]
Yes I did select the wrong scenario. My bad.

**Comment by warmwaffles** [comment]
![screenshot_2015-10-19_11-28-58](https://cloud.githubusercontent.com/assets/303133/10583787/a49aeaec-7654-11e5-925e-d1a1a8428a90.png)

Yes this is happening in linux running natively off of the develop branch.

**Comment by janisozaur** [comment]
Linux code is incomplete and can differ slightly from Windows' build. See especially these shims: https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/addresses.h#L40

They are used a couple of times in the sources, they could be the reason.

**Comment by duncanspumpkin** [comment]
I'm trying to implement the drawing functions for the top spin. Hopefully that will reveal where the discrepancy lies.
