### ISSUE TITLE
Closing a ride/stall construction window in pause mode when nothing is built creates non-existent ride/stall

### ISSUE THREAD

**Issue by Derpercoaster** [OpenRCT2/OpenRCT2#20659]
### Operating System

Windows 10 64bit

### OpenRCT2 build

OpenRCT2, v0.4.5-226-g19118de (19118de on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

If you close a ride/stall construction window when the game is paused, and you haven't built anything yet, the game will incorrectly assume the ride/stall has been built. This can be easily noticed if you go into the "attractions in park" window and try to open them all at once, as the game will tell you "can't open stall- not yet constructed!" or "can't open ride- no station platform!"

This issue can be resolved completely by exiting and re-entering the scenario via a saved game, so it doesn't break much. Also, you are still able to built a ride/stall with the same exact name as the broken ride/stall, but the game will still insist the broken one still exists.

### Steps to reproduce

1. Pause the game. Ensure "building while paused" cheat is NOT active.
2. Open the "build new attraction" window and select any ride (custom design) or stall.
3. Once the ride/stall has been selected, close the construction window. An error saying you can't build while paused will appear, even though nothing was built/attempted to be built.
4. The game has now incorrectly logged the unbuilt object as built. 

### Attachments

https://github.com/OpenRCT2/OpenRCT2/assets/60452987/c8c17c3b-adc4-43a4-a02c-ea2bedc5b008

**Comment by Derpercoaster** [comment]
Feel free to edit the title if its too unwieldy. I can't think of a shorter one that gets the point across.

**Comment by mrmbernardi** [comment]
I was able to reproduce this on develop.
