### ISSUE TITLE
Title sequence sounds play forever when joining a multiplayer game.

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#2066]
When joining a multiplayer game as a roller coaster train was descending a hill, the friction sound kept playing forever even after the the game connected to the server.

**Comment by janisozaur** [comment]
Is it still valid?

**Comment by Broxzier** [comment]
For paused games, yes.
It's very likely related to an original bug that makes the sounds keep playing when you press pause while loading a park. The music keeps playing too.

**Comment by janisozaur** [comment]
Is it still valid?

**Comment by Broxzier** [comment]
Both the friction and music bug don't seem to happen in 4c67ef1.

**Comment by IntelOrca** [comment]
I'll reopen if I counter this again.
