### ISSUE TITLE
nao fico conectada 

### ISSUE THREAD

**Issue by Jhe-Scrunch** [OpenRCT2/OpenRCT2#20675]
### Operating System

windos 11 64x exe 

### OpenRCT2 build

OpenRCT2, v0.4.5-227-g4349688 (4349688 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

oi boa tarde eu estou tentando jogar multiplayer  so que nao consigo ficar neim 15 seg ativa e desconecta do jogo on, ai nao posso fazer mais nada no parque estou ajudando a criar 
antes dessa atualização estava jogando de boa nao desconectava fácil assim, quando ficava muito tempo parado ele descontava mais agora ele neim da fica para jogar
open rct para parques multiplayer nao esta dando para jogar por causa disso eu gosto muito desse jogo mais ra muito foda, eu tenho que ficar saindo e entrando td hr isso e muito chato, nao esta aguentando neim15seg quando entra no multiplayer 
espero que possa rever isso e arruma o mais rápido por favo 
obrigada 

### Steps to reproduce

entra no parque 
começa a montar qualquer coisa que eu queira 
ai desconecta 

### Attachments

![image](https://github.com/OpenRCT2/OpenRCT2/assets/141200903/b174794f-f155-4090-9295-88d1dc40dcb8)

**Comment by brenoguim** [comment]
Translation:

Hi! Good afternoon.
I'm trying to play in "multiplayer" mode, but it doesn't last for even 15 seconds and disconnects, then I can't do anything in the park I'm contributing.
Before this update I it worked fine and didn't disconnect that easily. When I stayed still for a long time it disconnected, but now I can't even play.
I really like this game, but it's hard to play like this. I have to leave and enter the game repeatedly and it's really annoying. It can't stay online for even 15 seconds when it's in multiplayer mode.
I hope this can be investigated and fixed as soon as possible, please!
Thank you!

**Comment by ZehMatt** [comment]
I'm unable to reproduce this issue.

**Comment by Jhe-Scrunch** [comment]
tentei mandar o video mas fica fl que e muito grande e nao da para
enviar para vcs
esta muito dificil tem hr que neim dá pra conectar que já cai como eu faço
para arrumar isso eu quero jogar :(
obrigada pela atenção


Em qua., 2 de ago. de 2023 às 18:56, Matthias Moninger <
***@***.***> escreveu:

**Comment by brenoguim** [comment]
Tenta colocar o vídeo no YouTube e postar o link aqui.

**Comment by Jhe-Scrunch** [comment]
okok assim que eu colocar eu ja mando pra vcs


Em qui., 3 de ago. de 2023 às 09:30, Matthias Moninger <
***@***.***> escreveu:

**Comment by Gymnasiast** [comment]
Without a desync replay or anything else to go on, I’m afraid we cannot investigate this issue.
