### ISSUE TITLE
Maze construction not ghosted properly

### ISSUE THREAD

**Issue by mrmbernardi** [OpenRCT2/OpenRCT2#20672]
### Operating System

Linux

### OpenRCT2 build

OpenRCT2, v0.4.5-107 (97427743a on develop, DEBUG)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

Note the green sections that should probably be translucent white.

![image](https://github.com/OpenRCT2/OpenRCT2/assets/7877312/f10af86d-7ea7-440b-9870-db147c70e98e)

### Steps to reproduce

Try to construct a maze

**Comment by ZehMatt** [comment]
Fixed by #20746
