### ISSUE TITLE
Android: game crashes at launch

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#20679]
### Operating System

Android 13 (S23+)

### OpenRCT2 build

v0.4.5-ae273ab

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

Game crashes on opening when on Samsung S23+, fully updated. The game has full permissions btw, checked. I've tested, the lastest stable version, v0.4.5, and with that version it opens without crashes and prompts you to add the RCT2 data files and afterwards runs fine. So, it is an issue that was caused by a recent regression in OpenRCT2.

### Steps to reproduce

1. Install the OpenRCT2 App.
2. Copy Data folder content from the PC-version of OpenRCT2 to "Internal storage\openrct2" (according to wiki page instructions)
3. Copied RCT2 files to "Internal storage\rct2", again according to instructions.
4. Start the App.
5. Low-resolution logo of the game appears shortly, goes into landscape mode and then crashes, not even the "openrct2-user" folder gets created.

### Attachments

Nothing, as not even a log is created

**Comment by jruhlman09** [comment]
Having exact same issue using v0.4.5 release on S22+ android 13.

**Comment by mrtnptrs** [comment]
> Having exact same issue using v0.4.5 release on S22+ android 13.

You meant the latest stable release or the latest develop version?

**Comment by janisozaur** [comment]
Fixed in https://github.com/OpenRCT2/OpenRCT2/pull/20894

**Comment by Lister-O-Smeg** [comment]
This issue exactly describes my issue, steps to replicate, symptoms and the lack of a user folder after the crash.
Motorola moto edge 20. Android 13.

**Comment by James103** [comment]
> This issue exactly describes my issue, steps to replicate, symptoms and the lack of a user folder after the crash. Motorola moto edge 20. Android 13.

What OpenRCT2 version did you reproduce this on (include the exact commit if possible)?

**Comment by Lister-O-Smeg** [comment]
Quick response, I edited that info into my post while you were writing. It's the latest stable version on the website. V0. 4.6

**Comment by janisozaur** [comment]
`develop` is fixed now, it will take a while for the next release

**Comment by Lister-O-Smeg** [comment]
Got it working on the developer version. Interestingly I don't have a text editor on my phone so had to add one to edit the config ini with the path to the rct2 folder. The game started just fine after that. However I uninstalled the text editor and the game broke, just got a black screen on launch. Reinstalled quick edit app and the game worked again. Weird.
