### ISSUE TITLE
Mousing over paths when placing minature railway track removes path accessories

### ISSUE THREAD

**Issue by Derpercoaster** [OpenRCT2/OpenRCT2#20684]
### Operating System

Windows 10 64bit

### OpenRCT2 build

OpenRCT2, v0.4.5-229-gae273ab (ae273ab on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

When placing straight level miniature railway track to start building the ride, moving the mouse over paths with path scenery (benches, bins etc) removes them from the path, even if you don't place the track down.

### Steps to reproduce

1. Select the minature railway and choose "custom design"
2. Move the mouse over a path (with a path item on it) that would create a level crossing
3. the item will vanish from the path, even though nothing was built

### Attachments

https://github.com/OpenRCT2/OpenRCT2/assets/60452987/d167129d-5cca-4ce8-8a63-846c6a10726f

**Comment by Derpercoaster** [comment]
For some reason, the mp4 I included is not displaying for me. I can submit it on the discord if needed.

**Comment by mrtnptrs** [comment]
> For some reason, the mp4 I included is not displaying for me. I can submit it on the discord if needed.

It is for me, so wouldn't worry about it :)

**Comment by ZehMatt** [comment]
Caused by #10519
