### ISSUE TITLE
Mountain tool causes rendering issues

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#2068]
Dunno if this is already known, but it's on the latest stable build. (originates from #2050)

![img](http://puu.sh/kLCTY/c700236013.png)

This happens when switching back and forth between the mountain tool and the normal tool after a while...

Moving around will fix this, maybe rotating the view would as well.

**Comment by desertspider** [comment]
For me, this bug only happens only in the scenario editor when i load a scenario save. When creating a new scenario, there are no rendering issues. This also happens with the tool to buy land. Its like the viewport is smaller.

**Comment by duncanspumpkin** [comment]
I can't reproduce this.

**Comment by desertspider** [comment]
@duncanspumpkin
Can you reproduce  #2037 ? Probably the same bug.

**Comment by Patrik356b** [comment]
This does not occur on in a new landscape, but it does still happen with this landscape file:
http://www.mediafire.com/download/n6eagq5ngmr75mk/Riley's+Forest.sc6

**Comment by duncanspumpkin** [comment]
Still can't reproduce this even on your file.

**Comment by Patrik356b** [comment]
Unable to reproduce this anymore, closing.
