### ISSUE TITLE
The game hangs when I try to name a sign.

### ISSUE THREAD

**Issue by SeonAntti** [OpenRCT2/OpenRCT2#20707]
### Operating System

Windows 11

### OpenRCT2 build

OpenRCT2, v0.4.5-202-g0a3573e (0a3573e on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

The game hangs every time I try to name a particular sign.

### Steps to reproduce

When I place a sign near the rollercoaster and click the nametag icon, the game hangs. The problematic signs are the black vertical ones against the castle towers.

### Attachments

[Alpine Adventures.zip](https://github.com/OpenRCT2/OpenRCT2/files/12329404/Alpine.Adventures.zip)

**Comment by ZehMatt** [comment]
Try the latest develop version, this should be fixed.

**Comment by SeonAntti** [comment]
I upgraded to the latest develop version. It works now, thank you!
However not sure if it's a glitch or not but the sign that I try to name does not display the Japanese scripts, only latin letters.
Some other types of signs do display the Japanese scripts as well.

**Comment by ZehMatt** [comment]
> I upgraded to the latest develop version. It works now, thank you! However not sure if it's a glitch or not but the sign that I try to name does not display the Japanese scripts, only latin letters. Some other types of signs do display the Japanese scripts as well.

This seems like a different issue, I will close this one. Feel free to create a new report regarding language issue.
