### ISSUE TITLE
Wooden Wild Mouse ratings are calculated incorrectly

### ISSUE THREAD

**Issue by clamburger** [OpenRCT2/OpenRCT2#2070]
Loading the same [save game](https://u.pomf.io/ntqmzn.sv6) in both RCT2 and OpenRCT2 shows drastically different ratings for the same ride.

The RCT2 ratings shown below are the closest to what the track preview says. You can download the track [here](https://u.pomf.io/ukicrx.TD6).

**RCT2:**
![scr2](https://cloud.githubusercontent.com/assets/1396298/10540643/28956a0c-744d-11e5-882c-04c9e352de31.png)

**OpenRCT2:**
![scr4](https://cloud.githubusercontent.com/assets/1396298/10540966/7ec7564e-7450-11e5-880d-2e620cd854fa.png)

Not sure if this is related to #2064.

**Comment by clamburger** [comment]
It looks like some sort of off-by-one error, as the binary representations of the numbers are very similar.

322: 101000010
393: 110001001
228: 011100100

644: 1010000100
787: 1100010011
457: 0111001001

Also, this doesn't just affect loaded games. Starting a new park and building Mouse Box will have the same incorrect ratings.

**Comment by janisozaur** [comment]
would be useful to have both screens in same units (metric vs imperial)

**Comment by duncanspumpkin** [comment]
@IntelOrca wrote test scripts for the ride rating. I expect that will turn up some information about this.

**Comment by clamburger** [comment]
@janisozaur Whoops, didn't notice. Have updated it now.

Did a bit more testing, it doesn't seem to affect all rides. Building a different Wooden Wild Mouse (Cheesy Mice) had the same issue, but an Inverted Hairpin Coaster (Hawksnest) and Suspended Swinging Coaster (Swither) did *not* experience the issue (stats are identical between OpenRCT2 and original)

**Comment by IntelOrca** [comment]
So its likely to be a cause with just the wild mouse coaster type?

**Comment by clamburger** [comment]
Tested about 75% of the coaster types and none of the others have exhibited the issue, apart from the Wooden Wild Mine Ride which is just a variant.

**Comment by e-foley** [comment]
The rating system tends to apply penalties (g-forces too extreme, too few drops, too short a drop height, etc.) by dividing the ratings in half... Could it be that the original is applying some penalty that OpenRCT2 is not?

**Comment by duncanspumpkin** [comment]
Fixed in the pre release.
