### ISSUE TITLE
Build text copied over viewport in the title screen

### ISSUE THREAD

**Issue by mrmbernardi** [OpenRCT2/OpenRCT2#20739]
### Operating System

Windows 10 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.5 (76ca840) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

See the bottom left.
![Untitled](https://github.com/OpenRCT2/OpenRCT2/assets/7877312/24ecc525-8bbd-41bb-824d-cda95c87d6d3)

### Steps to reproduce

This is only noticeable when the title screen is panning to follow a vehicle.

1. Open title screen
2. Wait for the view to follow a vehicle

**Comment by ZehMatt** [comment]
If I had to guess it's probably drawn later on-top of everything so this needs invalidation like the FPS counter does it.
