### ISSUE TITLE
Some wrongly categorised items in the rct1 set (no expations only)

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#20758]
### Operating System

Windows 11, 64-Bits

### OpenRCT2 build

OpenRCT2, v0.4.5-275-g0dda9ed (0dda9ed on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

So, whenever you specifically say to only the no-dlc rct1 items only, these 6 items (5 small and a wall) get wrongly categorised in it.

### Steps to reproduce

1. Go to scenario editor or the selection of object in a park
2. only enable the rct1 checkmark (not the dlcs)
3. you will have 2 candy pieces (candy theme [Not the wonderland theme]), the lilypad-flower thing (pagoda theme), the 2 circular castle towers (Medieval theme [accessible No-dlc rct2]) and the Jurassic small wall piece (The Jurassic theme accessible in no dlc rct2)

### Attachments

![Wrongly Categorised small objects](https://github.com/OpenRCT2/OpenRCT2/assets/83843734/dc8565df-019b-45e3-8366-7be395b7e98f)
![Parc sans nom 2023-09-03 00-16-20](https://github.com/OpenRCT2/OpenRCT2/assets/83843734/103f3377-0e3f-4ad6-9ebf-7fcf82a20457)

**Comment by TheClaudeQC** [comment]
I forgot to add that the rct2 concrete toilet is also included in the rct1 no-dlc's list

**Comment by MASHzj** [comment]
The RCT1 toilet has a different colour of windows than RCT2's.

**Comment by Gymnasiast** [comment]
This is because objects need manual changes to mark them as RCT1. This has been done for rides, paths and probably scenery groups, but not for individual objects.

It is easy, though tedious, to fix, even if you don’t have much in the way of coding skills. You need to fork the `objects` repository, modify the `sourceGame` variables of the objects and create a pull request.

**Comment by TheClaudeQC** [comment]
>It is easy, though tedious, to fix, even if you don’t have much in the way of coding skills. You need to fork the objects repository, modify the sourceGame variables of the objects and create a pull request.

I have done the changes in my own, but where it should land?

**Comment by TheClaudeQC** [comment]
Ok, I have done the edits for the wrong ones, but then I noticed the doorway variant of the fences that was also not avaiable in rct1 w/o dlc's

**Comment by Gymnasiast** [comment]
The doorway variants were in RCT1, but you couldn’t build them yourself. You can see them in the Bumbly Beach scenario.
