### ISSUE TITLE
Eyedropper functionality for scenery repainting

### ISSUE THREAD

**Issue by zornor** [OpenRCT2/OpenRCT2#2078]
I'd love some kind of eyedropper functionality while working with scenery. My ideal implementation would be: while the re-paint brush is selected, right-clicking on a piece of scenery with colour data would change your current palette to its colours. If the 2nd or 3rd colours are not used, then those colours are not used. Any thoughts?

**Comment by IntelOrca** [comment]
#5304:
> A common tool found in most creative programs is a sampler tool that copies already placed color/texture so more of the same thing can be placed again. I think a similar tool for scenery placement will be very useful.
>
> How it can work:
In the scenery selection menu, select the sampler button. Possible button placement and icon:
>
> ![sampler placement example](https://cloud.githubusercontent.com/assets/26368692/23837457/e4bc6dde-0745-11e7-8bf3-03d891e30ff3.PNG)
>
> Preferably a keyboard shortcut is assigned for this tool. Perhaps the key 'x' because, by default, it is not in use and conveniently next to the default shortcut for rotate ('z' key).
>
> The cursor changes to eye dropper/picker icon and left-clicking on already placed scenery object on the map will deactivate the tool and change the current selected construction object to that that was copied earlier with the same color (if applicable) and the same rotation (if applicable).
>
> The scenery menu should also jump to the appropriate tab where that object belongs and have that object selected as well.
>
> The user can deactivate the tool by left-clicking on the button again similar to when deactivating the paint brush tool.

**Comment by Broxzier** [comment]
I think it would be nice if this tool would _also_ select the object that you clicked on, so that the tool can be used to quickly find an object in the scenery window by clicking on it in the map.

**Comment by christophski** [comment]
Could something like shift + click select scenery object. It could get annoying if you're trying to select a colour and your scenery object changes.

**Comment by Broxzier** [comment]
In Photoshop and similar programs you pick a colour by holding down Alt, and perhaps the two can be combined in a similar fashion under the same tool/button.
![image](https://cloud.githubusercontent.com/assets/9705046/24008404/d0f7ce04-0a71-11e7-9846-43737aba3457.png)
Then of course with different icons, and possible a tooltip to indicate Atl + Click can be used as well.

The button can not be placed at that position at all though, normally the colour buttons are taking up that space.

**Comment by Gymnasiast** [comment]
Indeed implemented by #5305.
