### ISSUE TITLE
Certain windows cause offset text to appear

### ISSUE THREAD

**Issue by e-foley** [OpenRCT2/OpenRCT2#2079]
![openrct2_tooltip_small](https://cloud.githubusercontent.com/assets/6338134/10562617/063d4b32-751a-11e5-9959-cf0df92191b4.png)

Tested in build 1327.

1. Move the camera such that some scenery is at the top-left of your window. (Not required, but makes the demonstration easier.)
2. Open the scenery window.
3. Hover your cursor over the top-left item in the scenery window.  Text will appear that corresponds to the top-left item in the main viewport.

It seems that the cursor reference is off: it's treating the relative-to-window position as the relative-to-viewport position.  

This issue also happens with the map window (assuming some construction mode is active).

I see this in both 1920 x 1080 resolution and 1280 x 720 resolution.  It does not seem to occur in vanilla.

**Comment by e-foley** [comment]
Forgot to mention, I'm using build 1327.

**Comment by Gymnasiast** [comment]
Confirmed.
