### ISSUE TITLE
Infinite-money parks don't show "guests' favorite" option in rides window

### ISSUE THREAD

**Issue by e-foley** [OpenRCT2/OpenRCT2#2080]
![no_profit_vanilla](https://cloud.githubusercontent.com/assets/6338134/10563014/3c8a4016-752c-11e5-89e8-00d6a00822e0.png)
RCT2

![profit_open](https://cloud.githubusercontent.com/assets/6338134/10563013/3c89d428-752c-11e5-8b55-700e8bdddb13.png)
OpenRCT2

In the original game, the "Profit" heading is hidden in scenarios that don't use money.  In build 1327 of OpenRCT2, the "Profit" heading is still visible, but "guests' favorite" isn't.

**Comment by jensj12** [comment]
This bug has been re-introduced. Playing on a275649, I can't access the 'guests favorite' option in scenario's without money (I can in scenario's with money).

**Comment by IntelOrca** [comment]
@jensj12 thanks for informing us, it should be fixed now in 8494eb9ff3e7402d504beeb97b2a5a71065956e4
