### ISSUE TITLE
Music object files missing (LINUX, Nightly PPA)

### ISSUE THREAD

**Issue by MrCantaloupe** [OpenRCT2/OpenRCT2#20805]
### Operating System

Linux (Kubuntu 22.04 LTS)

### OpenRCT2 build

OpenRCT2, v0.4.6 (, DEBUG) [probably gb2c6cf036]
(Nightly PPA, for *buntu 22.04 Jammy)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

Some of the newer music assets appear to be missing from /usr/share/openrct2/object/official/music, specifically the OpenRCT2 title theme and "mystic".  (See attachment below.)

This is probably why I'm observing the following two problems:

1. The new title music fails to load, playing only silence.
2. Attempting to load any park for which the music file "mystic" is referenced results in a "Error loading objects for park" error dialog, noting that the object "openrct2.music.mystic.parkobj" is missing or corrupt.

### Steps to reproduce

1. Load the game.
2. If the "OpenRCT2" title screen music is selected to play, the music is silent.

1. Attempt to load a park.
2. "Error loading objects for park" dialog box opens, indicating that the object "openrct2.music.mystic.parkobj" is missing or corrupt.

### Attachments

Relevant screenshot of "/usr/share/openrct2/object/official/music"
Notice that the objects "openrct2.audio.title.parkobj" and "openrct2.music.mystic.parkobj" are not present.
![image](https://github.com/OpenRCT2/OpenRCT2/assets/7056104/9ae714d6-3112-4791-bf2e-0176c01b38aa)

**Comment by duncanspumpkin** [comment]
How did you get openrct2? Did you build it yourself? Downloading all the objects is part of the normal build steps it suggests you haven't built the game correctly.

**Comment by MrCantaloupe** [comment]
> How did you get openrct2? Did you build it yourself? Downloading all the objects is part of the normal build steps it suggests you haven't built the game correctly.

Nightly PPA build for Linux.

There have been problems in the past with OpenRCT2-specific assets not being correctly added to the nightly build.  (e.g. https://github.com/OpenRCT2/OpenRCT2/issues/19432)  I suspect that's what's happened here too.

**Comment by WhoAmI24601** [comment]
Having the same issue with the nightly PPA Build. It's not letting me open any scenarios from GOG for RCT1 or RCT 2 and the OpenRCT2 title music doesn't play (the RCT1 and RCT2 title music play just fine). It's a bit weird that there's not a repository for stable builds for Ubuntu?

OpenRCT2, v0.4.6 (, DEBUG)
Linux Mint 20.3 (Ubuntu 20.04)

**Comment by twalk126** [comment]
Has anyone been able to fix the issue yet? I was able to download the needed files but I can't add them to the folder containing the rest of the music.

**Comment by janisozaur** [comment]
I've submitted an update to relevant repositories. Launchpad is currently building the package, it should be available in ~15 minutes. Once it's up, can you test if this is fixed?

**Comment by twalk126** [comment]
Did not work unfortunately, I have just opted to use the app image.

**Comment by WhoAmI24601** [comment]
The update fixed this for me, thanks!

**Comment by MrCantaloupe** [comment]
I just updated using the nightly PPA about thirty minutes ago and the update appears to have solved the problem on my end.  Thank you, @janisozaur, I'll be closing this issue.

(P.S. @twalk126, if you have the files you need you can place the relevant music files in the correct spot by using sudo and mv, e.g.:
`sudo mv openrct2.audio.title.parkobj /usr/share/openrct2/object/official/music`
Hope that helps!)

**Comment by DiegoAnas** [comment]
I'm having the same issue again with the nightly PPA , this time with file music.rock4
OpenRCT2, v0.4.6 (, DEBUG)
Ubuntu 22.04 Jammy (Version: 0.4.7-develop-0~874-202312100217-g4b0b2a48f~ubuntu22.04.1)

**Comment by janisozaur** [comment]
Should be fixed now/in a moment
