### ISSUE TITLE
OpenRCT2 installer flagged by Avast antivirus

### ISSUE THREAD

**Issue by JAnon-dot-gov** [OpenRCT2/OpenRCT2#20829]
### Operating System

Windows 10 (64-bit)

### OpenRCT2 build

OpenRCT2 0.4.6

### Problem

Apparently the installer gets flagged by Avast before it even finishes downloading.

Why is this happening?

**Comment by telk5093** [comment]
It is a false positive I think and it is not a bug.

**Comment by duncanspumpkin** [comment]
Nothing we can do. Best to remove Avast or just tell it to not remove the file.
