### ISSUE TITLE
opening the app get crash

### ISSUE THREAD

**Issue by islam2hamy** [OpenRCT2/OpenRCT2#20823]
### Operating System

android 13

### OpenRCT2 build

0.4.6

### Base game

RollerCoaster Tycoon 2

### Describe the issue

opening the app get crash
system language : ar

### Steps to reproduce

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Redmi/tapas_global/tapas:13/TKQ1.221114.001/V14.0.14.0.TMTMIXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2023-09-28 19:57:53.783963614+0300
Process uptime: 2s
ZygotePid: 1654968826
Cmdline: io.openrct2
pid: 18184, tid: 18184, name: io.openrct2  >>> io.openrct2 <<<
uid: 10344
tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: 'JNI DETECTED ERROR IN APPLICATION: java_object == null
    in call to GetObjectClass
    from java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.Class)'
    x0  0000000000000000  x1  0000000000004708  x2  0000000000000006  x3  0000007fdd304460
    x4  5151441f43445342  x5  5151441f43445342  x6  5151441f43445342  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  00000076b1a95cb0  x10 0000000000000001  x11 00000076b1b0a7c8
    x12 00000076ba4bb430  x13 0000000009488cb0  x14 0000000009488b70  x15 0000000000000000
    x16 00000076b1b75a80  x17 00000076b1b4e450  x18 000000758fec3940  x19 0000000000004708
    x20 0000000000004708  x21 00000000ffffffff  x22 0000000000000058  x23 0000000000000000
    x24 00000076180bfa4b  x25 0000000000000001  x26 0000000000000000  x27 0000000000000058
    x28 0000007618c16000  x29 0000007fdd3044e0
    lr  00000076b1afb748  sp  0000007fdd304440  pc  00000076b1afb774  pst 0000000000000000
backtrace:
      #00 pc 000000000008d774  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: 449f781894033dce6346794a1ee593e0)
      #01 pc 00000000007910cc  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1380) (BuildId: 3cd43dfd934282c944e52afdac5120fb)
      #02 pc 00000000000357d0  /apex/com.google.mainline.primary.libs@340817060/lib64/libbase.so/5cbcb48dc4a1ceb71422e6e07e9f12bb952b969b1d4789234c07c3b6241482a6f3a09733800aa23496f3dcd787dd1ded12735fe6dc5b3049d050d96b769bc049/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_0::__invoke(char const*)+80) (BuildId: 9facd15119941cde449a7a03cf8ba918)
      #03 pc 0000000000034d58  /apex/com.google.mainline.primary.libs@340817060/lib64/libbase.so/5cbcb48dc4a1ceb71422e6e07e9f12bb952b969b1d4789234c07c3b6241482a6f3a09733800aa23496f3dcd787dd1ded12735fe6dc5b3049d050d96b769bc049/libbase.so (android::base::LogMessage::~LogMessage()+352) (BuildId: 9facd15119941cde449a7a03cf8ba918)
      #04 pc 00000000003f0704  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+3460) (BuildId: 3cd43dfd934282c944e52afdac5120fb)
      #05 pc 0000000000692b74  /apex/com.android.art/lib64/libart.so (art::JNI<false>::GetObjectClass(_JNIEnv*, _jobject*)+444) (BuildId: 3cd43dfd934282c944e52afdac5120fb)
      #06 pc 00000000005f5384  /data/app/~~skMTiHFWSRQHDNKvM7qf1w==/io.openrct2-v9cD-yPG317wk3qE2tU4yg==/lib/arm64/libopenrct2.so (BuildId: d74287828ca91779f2c7ba1071c01bfe9db2e763)
      #07 pc 00000000005f60c4  /data/app/~~skMTiHFWSRQHDNKvM7qf1w==/io.openrct2-v9cD-yPG317wk3qE2tU4yg==/lib/arm64/libopenrct2.so (BuildId: d74287828ca91779f2c7ba1071c01bfe9db2e763)
      #08 pc 0000000000052b28  /apex/com.android.runtime/bin/linker64 (__dl__ZN6soinfo17call_constructorsEv+752) (BuildId: 4ce809828d81242cd810344a2a168dfa)
      #09 pc 000000000003d0f4  /apex/com.android.runtime/bin/linker64 (__dl__Z9do_dlopenPKciPK17android_dlextinfoPKv+2000) (BuildId: 4ce809828d81242cd810344a2a168dfa)
      #10 pc 00000000000380fc  /apex/com.android.runtime/bin/linker64 (__loader_android_dlopen_ext+84) (BuildId: 4ce809828d81242cd810344a2a168dfa)
      #11 pc 000000000000110c  /apex/com.android.runtime/lib64/bionic/libdl.so (android_dlopen_ext+20) (BuildId: c3485a51b95e45a16eaf027ef6a211fb)
      #12 pc 000000000001da24  /apex/com.android.art/lib64/libnativeloader.so (android::NativeLoaderNamespace::Load(char const*) const+184) (BuildId: 6a311242b7ed5eeb144f6566b584b5f9)
      #13 pc 000000000000de18  /apex/com.android.art/lib64/libnativeloader.so (OpenNativeLibraryInNamespace+68) (BuildId: 6a311242b7ed5eeb144f6566b584b5f9)
      #14 pc 000000000000d550  /apex/com.android.art/lib64/libnativeloader.so (OpenNativeLibrary+132) (BuildId: 6a311242b7ed5eeb144f6566b584b5f9)
      #15 pc 00000000004f6a88  /apex/com.android.art/lib64/libart.so (art::JavaVMExt::LoadNativeLibrary(_JNIEnv*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, _jobject*, _jclass*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)+668) (BuildId: 3cd43dfd934282c944e52afdac5120fb)
      #16 pc 00000000000051c0  /apex/com.android.art/lib64/libopenjdkjvm.so (JVM_NativeLoad+412) (BuildId: d113bdf2e41e1487cc3a16a5e5c091c5)
      #17 pc 000000000032195c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (art_jni_trampoline+156)
      #18 pc 00000000003558e8  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.lang.Runtime.loadLibrary0+328)
      #19 pc 0000000000356ae0  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.lang.Runtime.loadLibrary0+368)
      #20 pc 000000000035a51c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (java.lang.System.loadLibrary+92)
      #21 pc 0000000000589d98  /apex/com.android.art/lib64/libart.so (nterp_helper+152) (BuildId: 3cd43dfd934282c944e52afdac5120fb)
      #22 pc 0000000000162ba0  /data/app/~~skMTiHFWSRQHDNKvM7qf1w==/io.openrct2-v9cD-yPG317wk3qE2tU4yg==/oat/arm64/base.vdex (org.libsdl.app.SDLActivity.loadLibraries+20)
      #23 pc 000000000058ac54  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 3cd43dfd934282c944e52afdac5120fb)
      #24 pc 0000000000162c5a  /data/app/~~skMTiHFWSRQHDNKvM7qf1w==/io.openrct2-v9cD-yPG317wk3qE2tU4yg==/oat/arm64/base.vdex (org.libsdl.app.SDLActivity.onCreate+154)
      #25 pc 0000000000935e68  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.Activity.performCreate+1304)
      #26 pc 0000000000677850  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.Instrumentation.callActivityOnCreate+80)
      #27 pc 000000000076a854  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread.performLaunchActivity+3780)
      #28 pc 00000000007746b4  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread.handleLaunchActivity+1556)
      #29 pc 0000000000942a7c  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.servertransaction.LaunchActivityItem.execute+476)
      #30 pc 00000000006b0a94  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.servertransaction.TransactionExecutor.executeCallbacks+580)
      #31 pc 00000000006b07d4  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.servertransaction.TransactionExecutor.execute+740)
      #32 pc 00000000007517d8  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread$H.handleMessage+1320)
      #33 pc 00000000009fd558  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Handler.dispatchMessage+168)
      #34 pc 0000000000a00f18  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Looper.loopOnce+1048)
      #35 pc 0000000000a00a58  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Looper.loop+1112)
      #36 pc 00000000007683ac  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.app.ActivityThread.main+1660)
      #37 pc 0000000000360880  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+640) (BuildId: 3cd43dfd934282c944e52afdac5120fb)
      #38 pc 000000000026a904  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+780) (BuildId: 3cd43dfd934282c944e52afdac5120fb)
      #39 pc 000000000026a5e8  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*) (.__uniq.165753521025965369065708152063621506277)+32) (BuildId: 3cd43dfd934282c944e52afdac5120fb)
      #40 pc 00000000003276a8  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (art_jni_trampoline+120)
      #41 pc 0000000000c07e28  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+136)
      #42 pc 0000000000c125a8  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (com.android.internal.os.ZygoteInit.main+3368)
      #43 pc 0000000000360880  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+640) (BuildId: 3cd43dfd934282c944e52afdac5120fb)
      #44 pc 00000000004944cc  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+516) (BuildId: 3cd43dfd934282c944e52afdac5120fb)
      #45 pc 0000000000553530  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+112) (BuildId: 3cd43dfd934282c944e52afdac5120fb)
      #46 pc 00000000000c2c04  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+124) (BuildId: 14737e064bd646d6d6dae0899db31611)
      #47 pc 00000000000cfbe4  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+924) (BuildId: 14737e064bd646d6d6dae0899db31611)
      #48 pc 0000000000002610  /system/bin/app_process64 (main+1464) (BuildId: 0392f54b3dffeef9b6cad14b6f0bdd45)
      #49 pc 00000000000859b8  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+100) (BuildId: 449f781894033dce6346794a1ee593e0)

**Comment by janisozaur** [comment]
Do you have the [required files](https://github.com/OpenRCT2/OpenRCT2/wiki/Android) set up? Do previous versions work?

**Comment by islam2hamy** [comment]
sorry , it is my fault
i didn't know about the required files
ok , i will try that later
thank you

**Comment by thecannons** [comment]
I installed properly on Pixel 6 Pro and 0.4.6 stable as of 10/3/2023 just doesn't work or display any errors (it doesn't even create the user directory or config.ini which I created manually from desktop and it still didnt work) . I then installed 0.4.5 openrct2 desktop files and 0.4.5 apk and it worked immediately.
