### ISSUE TITLE
Display author field on ride overview window

### ISSUE THREAD

**Issue by karst** [OpenRCT2/OpenRCT2#20831]
A good first issue feature requests that people have been asking for. Thisone comes from https://github.com/OpenRCT2/OpenRCT2/discussions/17459.

Currently people are crediting themselves in the titles of rides, which causes a lot of clutter. That's what the author field is for.
The author field is displaying on the object selector, but is not displayed on the ride overview window.

Keep in mind that DAT files do not have an author field, so when selected should also not display this statistic.

**Comment by fredriktegnell** [comment]
I'll go ahead and take this issue! 
Is my picture below a correct idea of how this should look (ignore content, size and color of text)? Like, is that the correct window and tab on the window?
![author](https://github.com/OpenRCT2/OpenRCT2/assets/8687318/d3f23a94-87fb-4701-885a-d99f48b7f324)

**Comment by karst** [comment]
No it should be in the ride selector menu 
![image](https://github.com/OpenRCT2/OpenRCT2/assets/1516893/1193110a-e7e9-46d2-baa1-e3adaf6bbea8)

I apologize for not making that clearer

**Comment by fredriktegnell** [comment]
> No it should be in the ride selector menu ![image](https://user-images.githubusercontent.com/1516893/273976185-1193110a-e7e9-46d2-baa1-e3adaf6bbea8.png)
> 
> I apologize for not making that clearer

What do you think of this?
![authors](https://github.com/OpenRCT2/OpenRCT2/assets/8687318/ebb7c2c3-18ec-4e32-93c9-dfd2246bdc53)

**Comment by karst** [comment]
That's perfect! How does it look with the no money cheat on?

**Comment by fredriktegnell** [comment]
What do you mean? Here is another picture of one with a different author:
![authors2](https://github.com/OpenRCT2/OpenRCT2/assets/8687318/058a8f5c-9cea-4ac5-b7b9-eb5d33c2ec6d)

**Comment by karst** [comment]
When selecting the no money in the cheat menu prices will not be shown

**Comment by fredriktegnell** [comment]
Oh, here:
![authors3](https://github.com/OpenRCT2/OpenRCT2/assets/8687318/2436fd44-3b4d-480e-8f8a-95b351e6d9cc)

**Comment by karst** [comment]
Looks good to me

**Comment by fredriktegnell** [comment]
So should I push up my code to my branch but not create a PR or how do I proceed?

**Comment by Gymnasiast** [comment]
As per team chat discussion, closing this. The grouping feature makes this information incorrect (since authors are vehicle-bound), the information is already in the Object Selection and not of much value to the average player (it may even hurt immersion).
