### ISSUE TITLE
Display author field on scenery window

### ISSUE THREAD

**Issue by karst** [OpenRCT2/OpenRCT2#20830]
First of a batch of good first issue feature requests that people have been asking for. Thisone comes from #17459.

Currently people are crediting themselves in the titles of scenery, which causes a lot of clutter. That's what the author field is for.
The author field is displaying on the object selector, but is not displayed on the scenery window.

Keep in mind that DAT files do not have an author field, so when selected should also not display this statistic.

**Comment by cpparnell** [comment]
I would like to work on this!

**Comment by fredriktegnell** [comment]
Figured i might as well take this one on as well. Two questions before I start:
1. Is this the correct window?
2. Where do you want the text, in the center between the scenery name and cost or right next to cost?
![authors4](https://github.com/OpenRCT2/OpenRCT2/assets/8687318/b3e2ab13-c333-4f1f-9712-d9f0129ff88f)

**Comment by karst** [comment]
It's the correct window. I think it might be nicer if the window would be made slightly larger and have the author listed below the scenery name.

**Comment by ocalhoun6** [comment]
Or maybe just to the right of the scenery name, in a different (and less visible) font color. Gray, maybe?\

Though I guess that might run into problems if you have a scenery item with a very long name *and* the creator's name is also very long.

**Comment by karst** [comment]
> Though I guess that might run into problems if you have a scenery item with a very long name _and_ the creator's name is also very long.

Yea that essentially, it could cause quite the clutter. Better of using a new line.

**Comment by fredriktegnell** [comment]
This is my version at the moment, what do you guys think?
![plural](https://github.com/OpenRCT2/OpenRCT2/assets/8687318/44890f05-9268-473f-b181-d07df34340d4)
![singular](https://github.com/OpenRCT2/OpenRCT2/assets/8687318/2fbd290d-d2e8-4a25-98b3-1e55207526f3)
