### ISSUE TITLE
Switching tabs in Rides/Attractions menu can reveal "Profit" heading even when "no money" flag is set

### ISSUE THREAD

**Issue by e-foley** [OpenRCT2/OpenRCT2#2085]
This is a minor bug in the original game.

In a scenario with the "no money" flag set, do the following.
1. Enter the Rides/Attractions menu
2. Use the dropdown menu to select "Reliability" or any option below it
3. Switch tabs (to view either shops/stalls or facilities)
4. You'll notice that the new tab shows the "Profit" heading even though it's not directly select-able.
5. Switching back to the Rides tab, you'll notice that it too shows "Profit"

**Comment by Gymnasiast** [comment]
Does this still happen with the current development version? A PR was merged today that should solve this.

**Comment by e-foley** [comment]
It does still happen as of 0.0.3 build 1333. I only discovered issue #2080 (the one that was fixed today) because I was looking for the bug I described here.  The recent merge was an improvement in that it made OpenRCT2 act authentically to the original, but it turns out that the original RCT2 had a bug in this menu which is now faithfully affecting OpenRCT2.

**Comment by IntelOrca** [comment]
I made it just go back to "status" since there is no reason why profit should be chosen as the fallback.
