### ISSUE TITLE
Diagonal brakes don't build in Multiplayer

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#20863]
### Operating System

Windows 11, 64-Bits

### OpenRCT2 build

OpenRCT2, v0.4.6-96-gf773adc (f773adc on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is specific to multiplayer

### Describe the issue

Apparently, Building diagonal brakes don't properly build them.

### Steps to reproduce

1. Open a multiplayer server
2. Try a coaster whit the diagonal brakes
3. try to build one of them
4. doesn't properly build

### Attachments

![Train Panic 2023-10-09 21-38-23](https://github.com/OpenRCT2/OpenRCT2/assets/83843734/e11787ff-057b-487d-bd0e-2ec50d78bbcf)

Before building the ride

![Train Panic 2023-10-09 21-38-26](https://github.com/OpenRCT2/OpenRCT2/assets/83843734/a7d70d44-57b4-4ac1-946a-cb79f98aa39a)

Resaults...

**Comment by karst** [comment]
@spacek531

**Comment by spacek531** [comment]
I don't have any way to test this

**Comment by pactonal** [comment]
I can build and test with a server

**Comment by pactonal** [comment]
So I was able to build some diagonal brake sections on a locally hosted server on my own PC. 
![image](https://github.com/OpenRCT2/OpenRCT2/assets/13206094/644ea3c0-65e6-45ec-b315-3395d134b631)

I did however experience client crashes a few seconds after connecting to a world running on an Ubuntu server.  Both sides are running clean builds so I'm not sure what was happening there.

**Comment by TheClaudeQC** [comment]
> So I was able to build some diagonal brake sections on a locally hosted server on my own PC. ![image](https://user-images.githubusercontent.com/13206094/274039497-644ea3c0-65e6-45ec-b315-3395d134b631.png)
> 
> I did however experience client crashes a few seconds after connecting to a world running on an Ubuntu server. Both sides are running clean builds so I'm not sure what was happening there.

It happened in the "Multiplayer plug-in servers", those that prevent other player to edit rides from other

**Comment by TheClaudeQC** [comment]
> It happened in the "Multiplayer plug-in servers", those that prevent other player to edit rides from other
> 
> Edit: "[FFA] FFA-Tycoon.com - Develop"

Join the server I added as the edit

**Comment by pactonal** [comment]
Rebuilt with MSYS on Windows and was able to connect to server running on Linux without issues this time.  Again, no problems building diagonal brake tracks.
![image](https://github.com/OpenRCT2/OpenRCT2/assets/13206094/f7e538a5-2077-4b59-afc1-7892b91edc89)
Are you sure this isn't a problem with the plugins that are running on the server?  I don't think this is a problem with the game.

**Comment by TheClaudeQC** [comment]
> Rebuilt with MSYS on Windows and was able to connect to server running on Linux without issues this time. Again, no problems building diagonal brake tracks. ![image](https://user-images.githubusercontent.com/13206094/274049721-f7e538a5-2077-4b59-afc1-7892b91edc89.png) Are you sure this isn't a problem with the plugins that are running on the server? I don't think this is a problem with the game.

Might be

**Comment by spacek531** [comment]
Deurklink is reporting no issues with diagonal brakes and block brakes on his server.

**Comment by deurklink** [comment]
Was the network version increased? I think the people who have this issue may be playing on a server that doesn't have the diagonal brakes update yet

**Comment by TheClaudeQC** [comment]
> Was the network version increased? I think the people who have this issue may be playing on a server that doesn't have the diagonal brakes update yet

maybe that's why, as I have access to them, but didn't build on the server I said about the issue

**Comment by TheClaudeQC** [comment]
> > Was the network version increased? I think the people who have this issue may be playing on a server that doesn't have the diagonal brakes update yet
> 
> maybe that's why, as I have access to them, but didn't build on the server I said about the issue

I don't seem to find the last time a Multiplayer version happened

**Comment by TheClaudeQC** [comment]
> > > Was the network version increased? I think the people who have this issue may be playing on a server that doesn't have the diagonal brakes update yet
> > 
> > 
> > maybe that's why, as I have access to them, but didn't build on the server I said about the issue
> 
> I don't seem to find the last time a Multiplayer version happened

I found from where it was 0.4.6-5, it is the develop e17bca3 and never got changed, so either from this develop version or the last one, being b9c7637

**Comment by TheClaudeQC** [comment]
I also noticed a support bug whit the brakes,

They don't properly render when there is diagonal brakes, but normal diagonals don't suddently block entirely the supports

And also a bug when building them (and any wooden track pieces whit support [always the case when going down whit miniature railway "both ways"]) backwards

**Comment by CorySanin** [comment]
@deurklink  got it, the ffa-tycoon develop servers only update when the network version changes. The server is now running a more recent build. This issue can likely be closed.
