### ISSUE TITLE
Replace `monorail_diag_blocked_segments` with `DiagBlockedSegments`

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#20881]
Both contain exactly the same data.

**Comment by Abhinav-CHD** [comment]
Hey I'd like to work on this issue

**Comment by Gymnasiast** [comment]
Go for it! Compilation instructions are in the readme, and if you need help, you can ask on our Discord (in the #development channel).

**Comment by Xata** [comment]
Hello! I confirmed on the Discord that I can attempt to tackle this issue. Would just like to confirm on GitHub too before I make the PR.

**Comment by tupaschoal** [comment]
Sure, go ahead

**Comment by Xata** [comment]
I've updated Monorail.cpp to use DiagBlockedSegments. I created a pull request. I'd like to get feedback on it if possible.
