### ISSUE TITLE
Possible regression in multiplayer entrance types

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#20889]
### Operating System

Windows 11 Pro

### OpenRCT2 build

OpenRCT2, v0.4.6-99-gc2fe9ef (c2fe9ef on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is specific to multiplayer

### Describe the issue

![Sandbox 10 2023-10-15 18-17-29](https://github.com/OpenRCT2/OpenRCT2/assets/94884086/7b27c742-60b3-40f7-bb4a-cf8fd997b94a)

### Steps to reproduce

Just load a server and try building a ride. This has been happening quite frequently in recent days.

**Comment by duncanspumpkin** [comment]
Provide information on what the issue is. There is nothing in this post that states what the issue it.
