### ISSUE TITLE
Speeding up playback of replay no longer possible

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#20885]
### Operating System

Windows 10

### OpenRCT2 build

0.4.6 88608e0

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

I use replays to record footage for my videos where I build a park, so you don't see the UI (I block the camera moving to each action in my build). After I updated my replay build I noticed I can no longer increase the game speed (looks like it has been turned into a game action. This will no longer allow me to record footage of the replay for my time-lapses at an acceptable speed since they're often more than an hour long.
Is there a way to bring the game speed control back in a replay?

### Steps to reproduce

Record a replay
Play back replay
While playing back, Try speeding up the game (the button or hotkey doesn't work)

**Comment by deurklink** [comment]
This is one most likely the culprit https://github.com/OpenRCT2/OpenRCT2/pull/20825

**Comment by deurklink** [comment]
I commented out some lines in GameAction.cpp which allows me to use game commands again while replaying a replay.
Doing this allows me to speed up the replay again (and as a bonus, it also allows me to unpause a replay if I accidentally recorded a pause command)

![image](https://github.com/OpenRCT2/OpenRCT2/assets/6469413/2816937c-80f6-4181-aff3-ed3e20bf181f)

**Comment by ZehMatt** [comment]
I think certain game actions shouldn't be recorded in the replays anyway, setting speed and pause/unpause would be one of them.
