### ISSUE TITLE
Failed check for valid placement of scenery objects on water tiles, and water scenery objects on non-water tiles

### ISSUE THREAD

**Issue by CDB-Man** [OpenRCT2/OpenRCT2#20927]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.4.6-117-gdaf03e4 (daf03e4 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon Classic

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

As seen in the screenshot below, certain scenery objects are not properly being checked for valid placement on or off water.

1. I was able to place shrubs and fountain statues on water tiles.
2. I was able to place bulrushes and fountain jets on dry land
3. I was able to use SHIFT to place a fountain in mid-air

### Steps to reproduce

1. Open any new park, for example Forest Frontiers
2. Create water tiles
3. Attempt to place shrubs or fountain statues on the water -- it will work
4. Attempt to place bulrushes or water jet fountains on land -- it will work
5. SHIFT to raise and place a water fountain on land in the air -- it will work
6. Attempt to place a standard tree from the trees tab into the water -- it will **not** work

### Attachments

![image](https://github.com/OpenRCT2/OpenRCT2/assets/14037303/23de3f0e-4f6d-4349-8795-3df0a9aec70e)

**Comment by 733737** [comment]
This is not a bug. This is intended behaviour. It will not be changed
