### ISSUE TITLE
MacOS x64 artifact uploaded after tests

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#20933]
### Operating System

MacOS target

### OpenRCT2 build

OpenRCT2 develop

### Base game

RollerCoaster Tycoon Classic

### Area(s) with this issue?

This is a development issue

### Describe the issue

The MacOS CI target is set up to run tests before it uploads artifacts. This means if the tests fail, artifacts are not uploaded. Some OpenRCT2 mac users users like to test builds before hand and builds that fail tests (for any reason even legitimate) will not have the option except to build from source.

### Steps to reproduce

1. Push a commit to a PR where the game builds on MacOS x64 but fails replays
2. MacOS x64 artifacts are not uploaded.

**Comment by janisozaur** [comment]
Sounds easy enough, do you want to implement this change?

I'm trying to think of what could go wrong, the thing that comes to mind is if github still advertises the artifacts in case of job failure? We'll have to see. If this is implemented for one system, others should be modified in similar way.

**Comment by spacek531** [comment]
Other builds upload artifacts before running tests, so in the event of a tests failure the artifact is still available to download. I will try to make the changes.
