### ISSUE TITLE
Add "remove park fences" as a button in the Cheats window

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#20942]
https://github.com/OpenRCT2/OpenRCT2/pull/20922 added this cheat, which was previously only a console command (which also didn’t work in multiplayer).

It is desired to have a button in the Cheats window, to make this cheat more accessible. This button could be placed next to "own all land", since they have adjacent purposes - often, people want to own all land and not have border fences. (Placing it there will require shifting some of the buttons around.)

**Comment by Gymnasiast** [comment]
Implemented in #20922.

**Comment by lewyche** [comment]
Since Gymnasiast mentioned on discord that he was okay with someone else picking it up, I'm going to try making this feature.
