### ISSUE TITLE
Car ride dispatches 2 vehicles at once

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#20955]
### Operating System

Windows 10 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.6-96-gf773adc (f773adc on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

A car ride, built as pictured, double-dispatches vehicles starting at the second lap: the station light will turn green, then a vehicle will depart, but the next vehicle follows so closely that it can leave the station before the lights turn red.

I do not know if it is an original bug.

### Steps to reproduce

1. Build a car ride as pictured below
2. Test the car ride
3. Starting on the second lap, two vehicles will dispatch in close succession

### Attachments

![image](https://github.com/OpenRCT2/OpenRCT2/assets/3454156/f6ed75bf-8b42-471f-94fe-bf912c936e77)

**Comment by jensj12** [comment]
Duplicates: #17077 and #4192
