### ISSUE TITLE
OpenRCT2 cannot find files from RCTC from Steam - Could not find \Data\g1.dat at this path

### ISSUE THREAD

**Issue by afarah1** [OpenRCT2/OpenRCT2#20965]
### Operating System

Windows 

### OpenRCT2 build

OpenRCT2-0.4.6-windows-installer-x64.exe

### Base game

RollerCoaster Tycoon Classic

### Area(s) with this issue?

This is a development issue

### Describe the issue

I've installed RCT classic from Steam and ensured it's playable. I then installed OpenRCT 2 from the downloads section of the website, `OpenRCT2-0.4.6-windows-installer-x64.exe`. It installed successfully. When trying to launch it, it asks for the game files:

![image](https://github.com/OpenRCT2/OpenRCT2/assets/3854807/f34cc602-19e4-4edd-9327-2dfe94b9508a)

I tried using both `D:\SteamLibrary\steamapps\common\RollerCoaster Tycoon Deluxe` and `D:\SteamLibrary\steamapps\common\RollerCoaster Tycoon Deluxe\RCTdeluxe_install`, both of which have a `Data` folder, to no avail:

![image](https://github.com/OpenRCT2/OpenRCT2/assets/3854807/25605cd9-8f79-4e73-b12b-0b808d8868be)

I have found [this closed issue](https://github.com/OpenRCT2/OpenRCT2/issues/6570) which says using the then latest build works, but the build I'm using is newer than that.

PS: I have OpenRCT2 in C:\ and RCTC on D:\, not sure if it matters. Also, `openrct2.exe --version` doesn't return anything on Windows.

### Steps to reproduce

1. Install RCTC from Steam
2. Launch RCTC from Steam to verify it's playable
3. Install OpenRCT2-0.4.6-windows-installer-x64.exe
4. Launch openrct2, it asks for the game files from RCTC
5. Select the Steam install folder
6. It doesn't work

**Comment by Gymnasiast** [comment]
You tried pointing it to a folder called "RollerCoaster Tycoon Deluxe", which is not the same as "RCT Classic". The former is RCT1+expansions, the latter is based on RCT2.
