### ISSUE TITLE
Possible to remove scenery outside of the park area

### ISSUE THREAD

**Issue by FlightMS** [OpenRCT2/OpenRCT2#20976]
### Operating System

Windows 11 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.6 (b40b5da) provided by GitHub

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

For example, in the park scenario "Inca Lost City" it's possible to remove scenery, which is outside of the park area. Maybe this is also in other park scenarios. But it's NOT possible to remove trees for anyway.

### Steps to reproduce

1. Start "Inca Lost City"
2. Try to remove scenery which is outside of the area

### Attachments

![Screenshot 2023-11-15 233959](https://github.com/OpenRCT2/OpenRCT2/assets/82420268/0a6481e0-b3cb-4a5c-94db-d0a3091d91c3)

**Comment by MASHzj** [comment]
Can you also remove scenery closer to the ground? If not, I think it's because that area has construction rights which allows building (and thus removing) at least 2 units above ground.

**Comment by FlightMS** [comment]
@MASHzj yes, you're right. The message appears, but I can't remove scenery direct from the ground because it's not park area. A bit unusual, but from this point it makes sense.

**Comment by Gymnasiast** [comment]
It is a limitation of the engine. Ownership of tiles not saved in every tile element, rather it is saved in the surface element of every tile, and with construction rights, everything underground or >= 3 metres above ground is considered to be owned by the park.

Even when this is changed (as room has been reserved for this kind of thing), that will only fix it for new parks - we’ll still need to import old parks this way for backwards compatibility reasons.
