### ISSUE TITLE
Name glitch between Burger Bar and Ferris Wheel

### ISSUE THREAD

**Issue by zornor** [OpenRCT2/OpenRCT2#2098]
![screenshot](http://i.imgur.com/0hhhfa7.png)

I opened my park, played with it a bit, only to find later that my Ferris Wheel had been named "Burger Bar 1". I messed around with the names of both of them, which seemed to result in either one adopting the name of the other, or one having no name and being unrenameable.

* Moving the Burger Bar elsewhere did nothing to fix it.
* Deleting the Burger Bar resulted in the Ferris Wheel having no name and being unrenameable.
* Rebuilding a Burger Bar resulted in the Ferris Wheel being renamed Burger Bar 1 and then the whole thing started again.
* Building a second Burger Bar did not appear to influence anything.
* Deleting the first Burger Bar made the second Burger Bar into the crazy name-stealing stall.
* Deleting and rebuilding the Ferris Wheel resulted in the name change.
* Building a second set of Ferris Wheel and Burger Bar did not do anything weird (yet).
* Building a Ferris Wheel and Burger Bar on a brand new map resulted in nothing weird (yet).

I'd love to check if this happens in vanilla RCT2 but I can't get it to run properly.

The location of either object did not appear to influence anything.

I'm on build 1346 (67cf149).

**Comment by IntelOrca** [comment]
Somehow the two rides were sharing the same user string reference. Can you give more information about how, when and in what game, you created the park and added the ride and shop?

**Comment by zornor** [comment]
[This is the earliest save available in which it occured](http://puu.sh/kSRWe/d63d22a344.sv6) (pardon the very mature filename)

I made the Ferris Wheel (which should be named Nino) a fair while before the Burger Bar, but I can't say exactly how long or when. I may have even made them on separate builds, since I usually just grab the latest one before I start playing. Not sure if it occurred on previous builds, for that matter, because I wasn't paying much attention to the name of the Burger Bar.

**Comment by ryanbowden** [comment]
Wait thinking about this i think i also saw this with ice scream stall, where the customers were outputing string like the shop was a ride.

**Comment by IntelOrca** [comment]
We haven't had reports of this in a very long time, so I will assume that what ever caused this is now fixed.
