### ISSUE TITLE
Create patch system for fixing vanilla scenario mishaps 

### ISSUE THREAD

**Issue by tupaschoal** [OpenRCT2/OpenRCT2#20983]
As seen and extended on #19657, we have a lot of code in place to fix small errors on the vanilla scenarios. It is not ideal because it is code that is difficult to read and maintain, ideally we should have a patch system where each scenario upon loading would apply its respective patch, so that it is easier to maintain and monitor.

**Comment by ZehMatt** [comment]
Something to note is that we should be careful about picking the data format, something like json probably comes to mind but its not really user friendly for this purpose, json in general is not human friendly and its purpose is serialization, at the same time I would like to avoid reinventing the wheel too, so we should probably come to an agreement what the patch format looks like. Ideally the user doesn't have to even poke around in the data format and we instead provide a system to compare park A to park B and generate the data.

**Comment by Gymnasiast** [comment]
@tupaschoal I think this can be closed, now that you implemented it.

**Comment by tupaschoal** [comment]
Indeed, thanks for letting me know!
