### ISSUE TITLE
Floating Info booth

### ISSUE THREAD

**Issue by anarchopossum** [OpenRCT2/OpenRCT2#20999]
### Operating System

Mac OS 14.0

### OpenRCT2 build

0.4.6

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

Placed a InfoBooth Near a ride, and it ended up in the sky. The customers can't access it either.

### Steps to reproduce

1. Add a log ride
2. Add a Info Booth near a bend
3. booth should be in the sky

### Attachments

<img width="1741" alt="Screenshot 2023-11-20 at 11 18 02 PM" src="https://github.com/OpenRCT2/OpenRCT2/assets/92814289/cd6a721c-ab6d-4ada-96c7-4ad608a66257">

**Comment by ZehMatt** [comment]
It's not a bug, that is what the game does when there is a footpath.
