### ISSUE TITLE
Ride music not playing

### ISSUE THREAD

**Issue by goose0324** [OpenRCT2/OpenRCT2#21005]
### Operating System

windows 10

### OpenRCT2 build

open rct

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Ride music not playing on rides

### Steps to reproduce

Good morning sorry to bother you guys I am trying to get my  ride music playing  but its not working

**Comment by karst** [comment]
Hi Goose, as I stated previously, this isn't a bug. For troubleshooting please ask on our [discord](https://discord.gg/Kah5kAES) or [forums](https://forums.openrct2.org/).
Please do not open another bug report without filling in the form correctly.
When reporting a bug give us all details we need to reproduce a bug.
