### ISSUE TITLE
ride music  not playing

### ISSUE THREAD

**Issue by goose0324** [OpenRCT2/OpenRCT2#21003]
### Operating System

windows 10

### OpenRCT2 build

OpenRCT2, v0.4.6 (b40b5da) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

music not playing on rides

### Steps to reproduce

 music not playing on rides

### Attachments

not working

**Comment by Gymnasiast** [comment]
As long as you refuse to give any information or even fill in the form properly, you cannot expect us to help with your issue. It’s very unlikely you’re encountering a bug anyway - this belongs in the Discussions or on the forums (on Discord or on openrct2.org).
