### ISSUE TITLE
Editing ride stats doesn't affect price guests are willing to pay (but does affect park rating)

### ISSUE THREAD

**Issue by dylansan** [OpenRCT2/OpenRCT2#21022]
### Operating System

WIndows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.6-168-g4361827 (4361827 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

This issue is related to the [Ride Vehicle Editor](https://openrct2plugins.org/plugin/MDEwOlJlcG9zaXRvcnkzMTI2MjQ1MjY=/OpenRCT2-RideVehicleEditor) plugin, but I do not think the plugin is the source of the bug. When the stats of a ride are edited, some values like park rating are correctly affected (e.g. average ride excitement/intensity). However, the price that guests are willing to pay does not appear to change.

Because some things are calculated as expected, I am wondering if the price calculation is somehow calling a different version of the ride stats than the ones modified by the plugin.

### Steps to reproduce

Example Test
1. In an empty park, create a Merry Go Round, and set the rotations to 4. Stats: 0.88/0.35/0.50
2. Guests are willing to pay $1.20, but no more, as expected.
3. [Park Rating Inspector](https://openrct2plugins.org/plugin/MDEwOlJlcG9zaXRvcnkzOTY0NTM0NjA=/OpenRCT2-ParkRatingInspector) reflects average ride excitement: 0.88, and average intensity: 0.32
4. Use RVE to set stats to 0.05/0.05/0.05.
5. Park Rating Inspector shows average excitement/intensity of 0.
6. Guests continue to pay $1.20. They should not be willing to pay anything.

### Attachments

Attached park has a carousel and wooden coaster. Guests are willing to pay over $13 for the 0.05/0.05/0.05 coaster. Many of the guests "want to go on something more thrilling", but those who do ride it pay the price based on the original stats.

I have loaded this save with all plugins removed and it still behaves as described.
[Ride Price Bug.zip](https://github.com/OpenRCT2/OpenRCT2/files/13482254/Ride.Price.Bug.zip)

**Comment by ocalhoun6** [comment]
Maybe the maximum price is a separate value, stored separately, and not modified by changing the ride stats?

That would make sense from a performance standpoint. Rather than have every guest who encounters the ride trigger their own price calculation, the guest could just refer to the ride's max ticket price number. So instead of a whole calculation to determine if the ride is too expensive or not, it just has to compare two numbers.

------

If so, the solution would be either:

A) Expose the max ticket price variable to plugins, and then modify the plugin so that it will then set the max price according to the new stats when stats are changed, or

B) Have OpenRCT2 watch for plugin-directed stat changes and when one is detected, update the max price variable according to the new stats.

**Comment by dylansan** [comment]
I am only one person, but I am part of that overlap. I'd like to be able to use hacked rides in scenarios and not get an unreasonable advantage from high prices (particularly while using ride price manager). I typically adjust stats down, not up, due to certain ride types and vehicles giving much better stats than the thing I'm recreating.

But I also agree it's not a huge issue.

**Comment by Basssiiie** [comment]
> ... and let the plugin mimic the calculation for when the stats are modified.

@ZehMatt Do you mean that the Price Manager plugin should account for custom stats, or that the Ride Vehicle Editor should recalculate the ride value whenever it changes the stats?

**Comment by ZehMatt** [comment]
> > ... and let the plugin mimic the calculation for when the stats are modified.
> 
> @ZehMatt Do you mean that the Price Manager plugin should account for custom stats, or that the Ride Vehicle Editor should recalculate the ride value whenever it changes the stats?

Would be best if the Ride Vehicle Editor does that as that's the one modifying the stats. The function is not too complicated,
see https://github.com/OpenRCT2/OpenRCT2/blob/ee5055a422dca3d8de7a8a9b61e2d65da6f3ccd9/src/openrct2/ride/RideRatings.cpp#L1098-L1189

**Comment by Basssiiie** [comment]
@ZehMatt IMHO I think that's not a good idea, as it would lead to potentially buggy inconsistencies and unnecessary code duplication across all plugins that do something with modifying ratings. Furthermore, plugins cannot see whether OpenRCT2 has been compiled with the original rating table or the new one. 

If this function is such a simple function to replicate, what is the performance issue, and why not call it whenever a plugin modifies any of the ratings? Or if that's too much, I'd prefer to just have a plugin api function where I can call this internal function instead whenever my plugin has updated the ratings. I don't think it's a good idea to mimic OpenRCT2 behaviour if OpenRCT2 does it perfectly already by itself, and I wouldn't recommend it to any other plugin developers either, unless they want to do custom stuff with such calculations.

**Comment by ZehMatt** [comment]
> @ZehMatt IMHO I think that's not a good idea, as it would lead to potentially buggy inconsistencies and unnecessary code duplication across all plugins that do something with modifying ratings. Furthermore, plugins cannot see whether OpenRCT2 has been compiled with the original rating table or the new one.
> 
> If this function is such a simple function to replicate, what is the performance issue, and why not call it whenever a plugin modifies any of the ratings? Or if that's too much, I'd prefer to just have a plugin api function where I can call this internal function instead whenever my plugin has updated the ratings. I don't think it's a good idea to mimic OpenRCT2 behaviour if OpenRCT2 does it perfectly already by itself, and I wouldn't recommend it to any other plugin developers either, unless they want to do custom stuff with such calculations.

Well if people modify the ride stats they shouldn't really expect the ride value to change on its own, I was thinking more of a button in the plugin something like "Recalculate Ride Value". We could probably expose the function to the scripting system but this shouldn't happen whenever someone modifies the stats as its potentially expensive.
