### ISSUE TITLE
Unable to build walls underground in a sloped tile with clearance checks off.

### ISSUE THREAD

**Issue by MaxMallon** [OpenRCT2/OpenRCT2#21045]
### Operating System

Win 11

### OpenRCT2 build

Latest Dev (4-12-2023)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

With zero clearance checks disabled you should be able to build anything anywhere. Building walls underground works fine, unless the surface is slanted. Then for some reason you cannot place the wall. An error pops up, but it disappears 1 frame later and I cannot read it.

### Steps to reproduce

Make a slanted surface tile.
Turn off zero clearance
Attempt to place wall underground

**Comment by J-PIE-314** [comment]
This has been fixed.

![image of success](https://github.com/user-attachments/assets/6862f965-12fe-4b09-99a5-500873eac9e0)
