### ISSUE TITLE
Water Coaster does not have sprites for diagonal Brakes and Block Brakes, but allows them to be built

### ISSUE THREAD

**Issue by GigaG11** [OpenRCT2/OpenRCT2#21074]
### Operating System

Windows 10 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.6-180-g4b0b2a4 (4b0b2a4 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

![image](https://github.com/OpenRCT2/OpenRCT2/assets/13384601/ea0fa27c-fd5b-41c0-abff-86dee4652d76)
![image](https://github.com/OpenRCT2/OpenRCT2/assets/13384601/842da78c-d0ec-4e53-a89d-0e38ea140d8d)

The Water Coaster does not have sprites for diagonal block brakes but allows building them. While the Junior Coaster with similar track sprites does, the brakes on the two styles are different. (Classic Mini also acts like Junior)

However, in other situations where this is the case, and one coaster has diagonal brakes and one does not, the coaster does not allow you to build diagonal brakes. For instance, the Looping Coaster allows diagonal brakes but the LIM Launched Coaster does not. The Junior Coaster/Classic Mini allows building them, and the Water Coaster does too, but only the Junior Coaster and Classic Mini have sprites for the brakes, while it renders as invisible track for the Water Coaster.

### Steps to reproduce

1. Build a Water Coaster.
2. Build Diagonal Brakes or Block Brakes
3. The brakes will be functional but invisible.

**Comment by karst** [comment]
I think line 497 of `WaterCoaster.cpp` should have `return nullptr;` replaced with `return GetTrackPaintFunctionJuniorRC(int32_t trackType);`

This will also allow a bunch of lines to be reduced from that cpp file. 

That refactor (and bug fix) should not be in the way of #21009 which also touches the WaterCoaster's code, though. So I will let @Gymnasiast look at this.
