### ISSUE TITLE
Screenshots lost background transparency

### ISSUE THREAD

**Issue by cheweytoo** [OpenRCT2/OpenRCT2#21089]
### Operating System

Ubuntu Linux 22.04.3

### OpenRCT2 build

573ab04 develop

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

The PNG background in screenshots (at least the giant ones) for the "void" outside the park used to be transparent. It's now the solid color #172323.

This change must have happened some time after 2023-02-08 (I have screenshots with transparency from then).

A repo-wide search for "172323" only finds some unrelated svg files.

I tried to bisect builds to find the commit that made the change, but github-provided builds unfortunately aren't available further back than 3a3cd18 (crashes on screenshotting), and e94dc57 already has the solid color.

No commits in `Screenshot.cpp`'s history after the cutoff date jump out to me as the obvious culprit, but maybe 16c5c1b does something that loses the transparency somehow? Or maybe it happens somewhere else entirely…

### Steps to reproduce

- export giant screenshot
- "void" background in PNG is #172323 instead of transparent

**Comment by Broxzier** [comment]
Do you perhaps have the transparant background option disabled in the options window?

**Comment by cheweytoo** [comment]
Oh dear. Yes, that was it. I did not know there was an option for that, so I didn't look for it… no idea how that got toggled.

Sorry about the bugspam, and thank you!

**Comment by Broxzier** [comment]
No worries! Glad that it's now resolved for you.
