### ISSUE TITLE
The downwards medium right turns have rendering issues on the junior like types

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#21106]
### Operating System

Windows 11, 64-bits

### OpenRCT2 build

OpenRCT2, v0.4.6-202-g689d16b (689d16b on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

This image describe exactly the problem

![Diamond Heights 2023-12-23 01-12-12](https://github.com/OpenRCT2/OpenRCT2/assets/83843734/037a249c-623b-4651-a70e-7214dbcce809)

### Steps to reproduce

Just open any park whit a classic-mini, junior or water coaster whit a medium sloped right turn and the issue is visible straight away

**Comment by Gymnasiast** [comment]
Likely introduced by https://github.com/OpenRCT2/OpenRCT2/pull/21099.
