### ISSUE TITLE
Monorail-rental crashes game.

### ISSUE THREAD

**Issue by webhawk** [OpenRCT2/OpenRCT2#2110]
So i found out about the cheat "Show trains meant for other track types" (I play the game in Dutch, so it might be different in English) was making a monorail rental so peeps could rent a monorail to sail the deadly seas of forrest frontiers, but it crashed the game after a few seconds after the first car was rented.

![image](https://cloud.githubusercontent.com/assets/7838707/10701365/71e23cfa-79c3-11e5-9e56-c50b97f6882e.png)
This was the frame it froze on when crashed.

It did not crash when it had a closed track-circuit, so it might have something to do with when the code decides it wants to return to the station or something.

Rental for rollercoaster cars is obviously something that originally wasn't supposed to be able to do with the game, so it's not a surprise it doesn't work properly. Just wanted to inform you, so i can continue hoping that one day my visitors will be able to sail their own monorail in WebHawks Monorail Park of Many Monorails!

![image](https://cloud.githubusercontent.com/assets/7838707/10701697/51268906-79c5-11e5-87e7-584c006a23ad.png)

**Comment by AlexMedia** [comment]
[ 👍 Like ]

**Comment by duncanspumpkin** [comment]
Will require modifications to vehicle update.

**Comment by IntelOrca** [comment]
We might need a warning message then if you try to enable the ability to use any vehicle type.

**Comment by janisozaur** [comment]
With vehicle update now done, this code is now available and `requires more implementation` label should be removed.

It can cause #2587 as well.
