### ISSUE TITLE
Network Desync when placing non-rotatable scenery

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#2111]
I've done some network tests with a friend of mine, and can say that I've found 2 causes of a desync that I am 100% sure about:

1. When you're about to place scenery that cannot be rotated, and isn't a fence or path decoration, just something you place on a tile, or 1/4 tile. The ghost probably uses scenario_rand.
2. When opening the track-design interface for rides. For this one I don't know, since a random value doesn't make sense for just the interface.

Sometimes the clients get kicked when placing new rides on the server, though I'm not entirely sure what is causing this (could be related to #2043, I'll do some more tests for this tomorrow).

**Comment by IntelOrca** [comment]
```sub_6E1F34``` which is called when using the scenery window contains two uses of scenario_rand() which cause this issue.
