### ISSUE TITLE
Transparency options window not synchronised

### ISSUE THREAD

**Issue by mrmbernardi** [OpenRCT2/OpenRCT2#21123]
### Operating System

Linux

### OpenRCT2 build

OpenRCT2, v0.4.6-223 (a4d11d82e on develop, DEBUG)

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Describe the issue

The options in the transparency options window are not synchronised with the actual state used to render the game.

### Steps to reproduce

1. Open the transparency options window and make everything transparent
2. Open and close the build scenery window by clicking on the button in the top toolbar twice.

The transparency window will now still say everything is transparent when it isn't. 

It also appears to remember this wrong state when you close and reopen the game.

**Comment by Opi-Txm** [comment]
I'd work on this issue.

**Comment by cheweytoo** [comment]
Now it always starts with everything set to transparent, even after a reset in game:

![alltrans](https://github.com/user-attachments/assets/facbf1a6-32ce-41e4-a9ce-4e7671a44ec1)

**Comment by tupaschoal** [comment]
Even changing the options in config.ini to false?

**Comment by cheweytoo** [comment]
> Even changing the options in config.ini to false?

No, that works. So is the issue is that toggling those settings in game does not modify them in the config.ini?

**Comment by cheweytoo** [comment]
…and should those settings even apply to the startup screen?

**Comment by tupaschoal** [comment]
Modifying them in game should modify them in the config.ini, but we only sabe the invisible ones, not the hidden/see through.

Should not affect the title screen, I guess, but I can see how it does.

**Comment by sjoerddebruin** [comment]
Invisible supports was pre-selected when I opened the game for the first time after updating.

**Comment by tubbo** [comment]
@sjoerddebruin this was happening to me too, made an issue about it here: #22691. think i know what happened too so might be able to fix it tonight.
