### ISSUE TITLE
Incorrect ride name is displayed on entrance building sign

### ISSUE THREAD

**Issue by mamarley** [OpenRCT2/OpenRCT2#21134]
### Operating System

Linux x86-64

### OpenRCT2 build

OpenRCT2, v0.4.6

### Base game

RollerCoaster Tycoon 2

### Describe the issue

I was trying to build Alpengeist from BGW in OpenRCT2 and I noticed after saving, closing OpenRCT2, and reloading, that the name of the ride as displayed on the entrance building keeps flipping back and forth between "Alpengeist" (as it should be) and "Snake River Falls".  The latter name has never been used for any ride in this park.  The issue only affects the entrance building and not the queue sign.  I attached a screenshot demonstrating the issue and the park in which I noticed the problem.

### Steps to reproduce

Load the park from the attached archive in OpenRCT2 0.4.6 and note the behavior of the sign on the entrance building of the roller coaster.

### Attachments

[Alpengeist Test.tar.gz](https://github.com/OpenRCT2/OpenRCT2/files/13801467/Alpengeist.Test.tar.gz)
![Ride Test Park 2023-12-31 10-03-37](https://github.com/OpenRCT2/OpenRCT2/assets/1039758/67daa8a4-3032-4eb0-a9a5-810bd46662b5)

**Comment by Gymnasiast** [comment]
We’ll need to know your build, can you provide that?

**Comment by mamarley** [comment]
It was the build from the Ubuntu official repository.  I tried but was unable to determine the build number or git revision.  That said, I hadn't noticed that 0.4.7 had been released already.  I upgraded and the problem seems to have been fixed already.  Sorry for the bother.
