### ISSUE TITLE
[Plugin] `context.setTimeout()` crashes debug builds with read access violations

### ISSUE THREAD

**Issue by Basssiiie** [OpenRCT2/OpenRCT2#21158]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.7, 296e8cd

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

Using `context.setTimeout()` seems to crash debug builds with read access violations in certain cases, making debugging impossible in combination with plugins that use this API.

### Steps to reproduce

1. Get a plugin that uses `context.setTimeout()`, like [Sadret's Tetris plugin](https://openrct2plugins.org/plugin/R_kgDOLBRY8A/openrct2-rctris)
2. Start a debug build.
3. Start a Tetris game with the plugin.
4. Experience the read access violation crash within a second or two.

### Attachments

A screenshot of the crash in Visual Studio. Things that might be of note are the stack trace and the locals. It seems to crash in shared_ptr internal code when incrementing refs? In the locals window, the `_Uses` = `???` and it stayed like that even when I inspected the specific fields.

![image](https://github.com/OpenRCT2/OpenRCT2/assets/20048660/d5a0ac00-c85b-4cb9-b7ad-4b07102b99c1)

**Comment by ZehMatt** [comment]
The issue is that during iteration it adds a new interval which invalidates the vector and since it holds a reference that memory is no longer valid then.

**Comment by Basssiiie** [comment]
Thank you for the quick investigation and fix. 😄
