### ISSUE TITLE
Some game actions return `STR_NONE` in the `GameActions::Result`, which makes an empty error message box and prevents plugins from showing a custom error

### ISSUE THREAD

**Issue by pfroud** [OpenRCT2/OpenRCT2#21159]
### Operating System

Windows 10 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.7 (0e8d46e) provided by GitHub

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

This is a development issue

### Describe the issue

For example in [StaffFireAction](https://github.com/OpenRCT2/OpenRCT2/blob/296e8cdb1685f01aa9183f1cec17d5e712de57e4/src/openrct2/actions/StaffFireAction.cpp#L64), here's what happens if you try to fire a staff ID which doesn't exist:

```C++
LOG_ERROR("Invalid spriteId. spriteId = %u", _spriteId);
return GameActions::Result(GameActions::Status::InvalidParameters, STR_NONE, STR_NONE);
```

The game automatically shows a error box for the unsuccessful action, but since the title and message are both empty the box is empty. Then calling `ui.showError` in a plugin does not work!

In StringIds.h I didn't find a generic "invalid" message. Should we add one??

### Steps to reproduce

(1) Add this plugin:

```javascript
registerPlugin({
    name: 'Error message example',
    version: '1.0',
    authors: ['pfroud'],
    type: 'remote',
    licence: "MIT",
    targetApiVersion: 81,
    main: function () {
        ui.registerMenuItem("Fire handyman with ID 0", function () {
            const args = {
                id: 0
            };
            const callback = function (result) {
                console.log("Result from trying to fire handyman with ID 0:")
                console.log("Error number:  " + result.error);
                console.log("Error title:   " + result.errorTitle);
                console.log("Error message: " + result.errorMessage);
                if (result.error !== 0) {
                    ui.showError("my error title", "my error message");
                }
            };
            context.executeAction("stafffire", args, callback);
        });
    }
});
```

(2) Load a scenario with no staff. Click the map icon in the top bar and click the plugin's item.

The GUI only shows an empty red error message box:

<img src="https://github.com/OpenRCT2/OpenRCT2/assets/9056906/f2422dd5-ea70-410e-a2ca-f34755569909" alt="empty red error box" width="300">

The log window shows:

```
ERROR[D:\a\OpenRCT2\OpenRCT2\src\openrct2\actions\StaffFireAction.cpp:48 (StaffFireAction::Query)]: Invalid spriteId. spriteId = 0
'Result from trying to fire handyman with ID 0:'
'Error number:  1'
'Error title:   '
'Error message: '
```

**Comment by ZehMatt** [comment]
Also related #15782
