### ISSUE TITLE
[Plugin] Segfault When Creating Entities

### ISSUE THREAD

**Issue by Crazycolbster** [OpenRCT2/OpenRCT2#21171]
### Operating System

Linux

### OpenRCT2 build

OpenRCT2, v0.4.7 (, DEBUG)

### Base game

RollerCoaster Tycoon 2

### Describe the issue

There appears to be a limit to how many times map.createEntity() can be called in a tick. Around 300 will cause the game to hang, followed by a segmentation fault.

### Steps to reproduce

Run the following code in any park:
`for(let i = 0; i < 500; i++){
         map.createEntity("balloon",{x: 0,y: 0,z: 0})
}`

My code that caused this specifically was 
`function explodeFurries(){
    var staff_list = map.getAllEntities("staff");
    for (let i = 0; i < staff_list.length; i++){
        if(staff_list[i].staffType == "entertainer"){
            console.log(staff_list[i].patrolArea.tiles.length);
            if (!staff_list[i].patrolArea.tiles.length){
                let x = staff_list[i].x;
                let y = staff_list[i].y;
                let z = staff_list[i].z;
                staff_list[i].remove();
                map.createEntity("balloon",{x,y,z});`
With over 300 entertainers in the park, this will crash the game, giving the following error:
`WARNING[./src/openrct2/entity/EntityRegistry.cpp:437 (EntitySpatialRemove)]: Bad sprite spatial index. Rebuilding the spatial index...`

Pastebin of core dump:
https://termbin.com/ah94

**Comment by ZehMatt** [comment]
There is a limit to how many effects/misc entities can be created, you are most likely hitting the limits but it shouldn't crash.

**Comment by ZehMatt** [comment]
I've checked and it is indeed limited to 300, balloons count as misc/effect entities.
