### ISSUE TITLE
Some hotkeys don't work when toolbars are hidden

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#21175]
### Operating System

Windows 10

### OpenRCT2 build

v0.4.7 1d8dc11

### Base game

RollerCoaster Tycoon 2

### Describe the issue

When the toolbars are hidden all my hotkeys work fine, except the ones for opening the path build menu, opening the scenery build menu, and pausing the game. It's not the specific keys that are the problem, as when I bind both the ride build and path build menu to the same key, both get opened when the toolbars are visible, but only the ride one gets opened when the toolbars are hidden.

That has been present in OpenRCT2 since at least v0.2.0.

### Steps to reproduce

Set a hotkey for one of the three aformentioned actions, hide the toolbars, and press the hotkey.

**Comment by Harry-Hopkinson** [comment]
List of full hotkeys that do not work when the toolbar is hidden

- [ ] Pause Game
- [ ] Open Scenery Picker
- [ ] Send Message (But requires toolbar to be shown)
- [ ] Adjust land
- [ ] Adjust water
- [ ] Clear scenery
- [ ] Build scenery
- [ ] Build paths

**Comment by AaronVanGeffen** [comment]
This can be handled after (or as part of?) #22411.
