### ISSUE TITLE
[Linux i386] Game crashes on scenario load

### ISSUE THREAD

**Issue by PureTryOut** [OpenRCT2/OpenRCT2#2117]
Currently the game crashes (for me) whenever trying to load any scenario (both saves or new ones).
The following comes up
```
WARNING[/tmp/yaourt-tmp-bart/aur-openrct2-git/src/openrct2-git/src/interface/window.c:2426 (textinput_cancel)]: there should be something called here (0x0040701D)
zsh: segmentation fault (core dumped)  openrct2
```

Running Arch Linux, with the latest git build installed from the AUR.

**Comment by janisozaur** [comment]
Hey,
my first hunch would be missing required files. They are a bit hardcoded for now, be sure to check https://github.com/OpenRCT2/OpenRCT2/wiki/Installation-on-Linux#putting-assets-in-proper-places

For reference, my build dir looks like this:
```
/home/janisozaur/workspace/OpenRCT2/build-native
├── CMakeCache.txt
├── CMakeFiles
├── cmake_install.cmake
├── data -> ../data
├── Data -> /home/janisozaur/games/Rollercoaster Tycoon 2/Data
├── Makefile
├── ObjData -> /home/janisozaur/games/Rollercoaster Tycoon 2/ObjData
├── openrct2.exe -> ../openrct2.exe
├── Saved Games -> /home/janisozaur/games/Rollercoaster Tycoon 2/Saved Games
├── Scenarios -> /home/janisozaur/games/Rollercoaster Tycoon 2/Scenarios
└── Tracks -> /home/janisozaur/games/Rollercoaster Tycoon 2/Tracks
```

**Comment by PureTryOut** [comment]
The only folder I seem to be missing is "data" (the not capitalized one). I do recall having it in the past though, I might have removed it when cleaning up from the Wine version I did a week ago.

What should that folder contain? Can I just extract it from the CD or do I need to install it first and copy it off there?

**Comment by janisozaur** [comment]
as pointed out above and in the listing provided, it should contain https://github.com/OpenRCT2/OpenRCT2/tree/develop/data

**Comment by PureTryOut** [comment]
Found out AUR installs the required files to /usr/share/openrct2. This folder does in fact contain a "data" (not capitalized) folder with contents. Basically I have all the required files in place.

**Comment by janisozaur** [comment]
Please provide GDB backtrace, otherwise I don't have enough information. Feel free to ping me on gitter as well.

**Comment by PureTryOut** [comment]
I would love too if I knew how. I guess I have to run `gdb /usr/share/openrct2`, but does not do much.
I get `Reading symbols from /usr/share/openrct2/openrct2...(no debugging symbols found)...done.' and then I can enter commands which I know nothing about.

A quick guide on what to do would be great.

Also, I do not have Gitter, but am reachable on Tox or even the IRC (Snoonet I guess) for that matter.

**Comment by IntelOrca** [comment]
@PureTryOut Gitter uses your GitHub account, just go on the gitter site.
https://gitter.im/OpenRCT2/OpenRCT2

**Comment by janisozaur** [comment]
Have makepkg rebuild your package with `debug` enabled and `strip` disabled, then run `gdb $(which openrct2)`, in gdb use commands:
```
r
bt
```

openrct has the path to `openrct2.exe` hardcoded for the moment, possibly you're using wrong cwd.

**Comment by PureTryOut** [comment]
$(which openrct2) returns `/usr/bin/openrct2`, but that is only a script launching the executable located in `/usr/share/openrct2/` with `$@` as arguments. GDB complains if it is running a script.

Just a note, I just build it myself by cloning from Github, and it managed to run a scenario 1 time. I quit back to menu, tried loading again, and it segfaulted again.

Do note, I'm still pretty new to this all, and a big noob, so just presume I know nothing you guys tell me.
How exactly do I change the USE flags on an AUR package? I know how to change PKGBUILDS, but don't know where to put the USE flags.

**Comment by janisozaur** [comment]
https://wiki.archlinux.org/index.php/Makepkg

if you can build it from github, it will be a better option for now, as I mentioned earlier, some paths are hardcoded and not yet conforming to where you would ideally have them.

use `cmake ../ -DCMAKE_BUILD_TYPE=Debug` to compile in debug mode (I think it's default, but I'm not sure), then `make`. Refer to https://github.com/OpenRCT2/OpenRCT2/issues/2117#issuecomment-150854060 for expected files' layout.

**Comment by PureTryOut** [comment]
Result when crashing from gdb:
```
Program received signal SIGSEGV, Segmentation fault.
0x08176da0 in gfx_bmp_sprite_to_buffer (palette_pointer=0x0, unknown_pointer=0x0, source_pointer=0x0, 
    dest_pointer=0xe69c3454 '\211' <repeats 22 times>, "\213\207\213\210\212\212\f\016\020\021", 'C' <repeats 14 times>, "\r\016\020\021\212\212\214\207\213\207", '\211' <repeats 26 times>, "\213\207\027````\030aa\031a\227\223\225\225\225\225\n9\r\017\021\022\022\021\021\017\r6\n\225\225\225\225\225\225\225\225\225\227\223\227\223\225\225\225\225\225\225\225\225\226\225\225\225\224\225\225\225\225\224\224\225\225\225\225\225\225\225\227\223\227\223\225\225\225\225\225\225\225\225\225\225\n\254\253\252\253\253\253\252\251\253\256\260\260\n\225\225\227\223\227\223\225\225lk..k......k"..., 
    source_image=0x8308d78, dest_dpi=0xffffd6b4, height=2, width=8, image_type=0) at /home/bart/openrct2-git/src/drawing/sprite.c:211
211					*dest_pointer = *source_pointer;
(gdb) bt
#0  0x08176da0 in gfx_bmp_sprite_to_buffer (palette_pointer=0x0, unknown_pointer=0x0, source_pointer=0x0, 
    dest_pointer=0xe69c3454 '\211' <repeats 22 times>, "\213\207\213\210\212\212\f\016\020\021", 'C' <repeats 14 times>, "\r\016\020\021\212\212\214\207\213\207", '\211' <repeats 26 times>, "\213\207\027````\030aa\031a\227\223\225\225\225\225\n9\r\017\021\022\022\021\021\017\r6\n\225\225\225\225\225\225\225\225\225\227\223\227\223\225\225\225\225\225\225\225\225\226\225\225\225\224\225\225\225\225\224\224\225\225\225\225\225\225\225\227\223\227\223\225\225\225\225\225\225\225\225\225\225\n\254\253\252\253\253\253\252\251\253\256\260\260\n\225\225\227\223\227\223\225\225lk..k......k"..., 
    source_image=0x8308d78, dest_dpi=0xffffd6b4, height=2, width=8, image_type=0) at /home/bart/openrct2-git/src/drawing/sprite.c:211
#1  0x081778a0 in gfx_draw_sprite_palette_set (dpi=0xffffd6b4, image_id=324290, x=36, y=3, palette_pointer=0x0, unknown_pointer=0x0) at /home/bart/openrct2-git/src/drawing/sprite.c:618
#2  0x0817747b in gfx_draw_sprite (dpi=0xffffd6b4, image_id=324290, x=36, y=3, tertiary_colour=0) at /home/bart/openrct2-git/src/drawing/sprite.c:464
#3  0x0814b8f3 in window_top_toolbar_paint (w=0x1420eb8, dpi=0xffffd6b4) at /home/bart/openrct2-git/src/windows/top_toolbar.c:789
#4  0x080e3fd9 in window_event_paint_call (w=0x1420eb8, dpi=0xffffd6b4) at /home/bart/openrct2-git/src/interface/window.c:1989
#5  0x080e31b6 in window_draw (w=0x1420078, left=0, top=0, right=128, bottom=144) at /home/bart/openrct2-git/src/interface/window.c:1555
#6  0x0817839d in gfx_redraw_screen_rect (left=0, top=0, right=128, bottom=144) at /home/bart/openrct2-git/src/drawing/drawing.c:325
#7  0x0817823c in gfx_draw_dirty_blocks (x=0, y=0, columns=2, rows=18) at /home/bart/openrct2-git/src/drawing/drawing.c:294
#8  0x081780f4 in gfx_draw_all_dirty_blocks () at /home/bart/openrct2-git/src/drawing/drawing.c:270
#9  0x080e05fc in window_update_all () at /home/bart/openrct2-git/src/interface/window.c:179
#10 0x081147dd in rct2_draw () at /home/bart/openrct2-git/src/rct2.c:243
#11 0x0817ea97 in openrct2_loop () at /home/bart/openrct2-git/src/openrct2.c:432
#12 0x0817e4f7 in openrct2_launch () at /home/bart/openrct2-git/src/openrct2.c:298
#13 0x080b22ca in main (argc=1, argv=0xffffd904) at /home/bart/openrct2-git/src/platform/linux.c:54
```

**Comment by PureTryOut** [comment]
So in the end it appeared to be some kind of corrupt file. I installed a clean copy of RCT2 in a VM, copied the files over, replacing the ones I already used in the native Linux build, and now it doesn't crash anymore.

Thanks for your help @janisozaur, as you gave me the idea of having corrupt files!
