### ISSUE TITLE
Ride from issue #8202 does not calulate stats

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#21180]
### Operating System

Windows 11 Pro

### OpenRCT2 build

OpenRCT2, v0.4.7-22-gce0cc9f (ce0cc9f on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

The ride in the save file does not produce EIN stats in issue #8202 

### Steps to reproduce

download save file and test the ride

**Comment by ZehMatt** [comment]
Rides like this can't currently calculate the stats. A ride like this did block other rides from calculating their stats before I allowed multiple stats to be done in parallel. I somewhat doubt that we will ever get to compute stats for rides like this, there is also probably already an issue open for this specific problem.
