### ISSUE TITLE
Scenario description for Inca Lost City is inconsistent between the scenario select screen and in-game.

### ISSUE THREAD

**Issue by HtotheTML** [OpenRCT2/OpenRCT2#21211]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.7-48-gece7601 (ece7601 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error, This is a development issue

### Describe the issue

A recent change was made to Inca Lost City's scenario description to remove the bit about height restrictions, since there are no such restrictions in it. The change applied correctly to the description within the scenario itself, but not on the scenario select screen.

Is the text for the scenario select screen located somewhere else?

### Steps to reproduce

1. Open Inca Lost City
2. Open the scenario select window
3. Mouseover Inca Lost City

### Attachments

![image](https://github.com/OpenRCT2/OpenRCT2/assets/108596959/190c3cca-06f5-4acf-9df3-d1351e14c01c)

**Comment by Gymnasiast** [comment]
This is just cached data hanging around. If you remove `scenarios.idx`, a rebuild will be triggered.
