### ISSUE TITLE
Scenarios Created using OpenRCT2 have the staff colors defaulted all to red.

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#2122]
If I am not mistaken, this was not the case in RCT2.

**Comment by Patrik356b** [comment]
i don't think vanillia rct2 does this with mechanics, but it often uses red for janitors

**Comment by PFCKrutonium** [comment]
Yah, Janitors are red, Mechanics Blue, and Guards Yellow.
