### ISSUE TITLE
OpenRCT2 Release PPA does not contain builds for Ubuntu 23.10 or 24.04

### ISSUE THREAD

**Issue by qwertychouskie** [OpenRCT2/OpenRCT2#21222]
### Operating System

Ubuntu 23.10

### OpenRCT2 build

N/A

### Base game

RollerCoaster Tycoon 2

### Describe the issue

The OpenRCT2 Release PPA (https://launchpad.net/~openrct2/+archive/ubuntu/master) does not contain builds for Ubuntu 23.10 or 24.04, meaning trying to add the PPA on these versions results in an error.

(Also, the builds for 22.10, 18.04, and 16.04 can be removed as they are old versions of OpenRCT2 for EOL distros.)

### Steps to reproduce

Attempt to add the PPA on Ubuntu 23.10 or 24.04

**Comment by Gymnasiast** [comment]
Fixed. Build of the v0.4.7 release are now available for both 23.10 and 24.04.
