### ISSUE TITLE
Expose guests' items to the Plugin API

### ISSUE THREAD

**Issue by RickHuizing** [OpenRCT2/OpenRCT2#21235]
The items a guest has bought are not yet exposed. Adding this feature can help with writing plugins.

**Comment by tupaschoal** [comment]
Wasn't this tackled by #21062?

**Comment by RickHuizing** [comment]
Haha I feel silly, I looked for a similar _open_ issue and am on an older version of the game.

**Comment by RickHuizing** [comment]
Who would've though this was done 12h ago
