### ISSUE TITLE
New ride type: Blimp / Zeppelin Ride

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#2124]
Basically an untracked autonomous gentle ride flying around the park area that is owned and/or have the building rights for.

Think of it as a flying observation tower. (thus would get slightly higher ratings than a standard observation tower)

It will generate an approximate path to go around your park, while trying to avoid getting closer than 10 units from the park edge and automatically tries to ignore dead-ends smaller than 10x10 units.
(Only exception is when the station is near/in/at a dead-end/edge where it will take a hairpin turn if necessary to continue the loop)

Preferably with the add-on to use a "patrol path", kinda like how we tell staff where to patrol.

http://bullfrogproductions.wikia.com/wiki/Jurassic_Tours

**Comment by PFCKrutonium** [comment]
I like this idea, but it is one of those things that won't be possible until we move to our own format - plus we would need to make sprites.

**Comment by Patrik356b** [comment]
That does not surprise me though.

**Comment by HaasJona** [comment]
I think that's something, that could be made using mods or some NewGRF-like thing in the far future, but I don't think new rides should be added to the main game.
