### ISSUE TITLE
Message alert sound effect plays in roller coaster designer

### ISSUE THREAD

**Issue by e-foley** [OpenRCT2/OpenRCT2#2125]
This is a bug in the original game that also affects OpenRCT2 as of build 1358.

Create a roller coaster in the roller coaster designer that has a runtime of over 5 minutes, like this one:
![long_boring](https://cloud.githubusercontent.com/assets/6338134/10714302/81435e34-7aa6-11e5-896a-43198ebfdc79.png)
(Track file is available [here](https://dl.dropboxusercontent.com/u/10663130/OpenRCT2/Long%20and%20Boring.TD6).)

Test the ride.  After a little over five minutes have elapsed, you'll here the message alert sound effect, presumably intended to warn you that Train 1 hasn't reached the station yet and could be stuck or stalled, etc.  This is a bug because there's no way for you to actually read the message in this mode, so the game is alerting you to nothing in particular.

**Comment by Christipher** [comment]
I suspect that this is more of a logic fallacy - this sound also occurs when your coaster crashes in the coaster designer (and thus I suspect the message should appear then, so those messages should be appearing... I don't know, so don't completely take my word for it as there could be multiple interpretations of this).

**Comment by Gymnasiast** [comment]
@Christipher : The game normally shows a message when a coaster crashes, which includes a sound. It just needs an extra check to only play that sound effect when in normal game mode (or not to generate messages at all, which from the user's perspective is the same thing).
