### ISSUE TITLE
Multi-tile mountain landscaping prices

### ISSUE THREAD

**Issue by e-foley** [OpenRCT2/OpenRCT2#2127]
Raising a mountain with a one-tile-square selection costs $80.  Considering that nine tiles are affected, one might think the cost should be closer to $20*9 = $180, but Chris Sawyer's landscaping service offers a discount.  (If I recall correctly, this is consistent with RCT1.)

![1 tile mountain](https://cloud.githubusercontent.com/assets/6338134/10714404/eb701bc6-7aab-11e5-8cfc-b64ff1b094cd.png)

With OpenRCT2, we can build mountains that have larger plateaus.  A mountain with a top two tiles square costs $320 to form.  Seeing as 16 tiles are affected, $20 \* 16 = $320 sounds like it's about the right price to pay.

![2 tile mountain](https://cloud.githubusercontent.com/assets/6338134/10714414/249c9668-7aac-11e5-853d-addf639926f5.png)

By the time we reach a 3x3 mountain, the cost is $720.  25 tiles are affected, so we'd expect to pay closer to $20*25 = $500.  That said, some of the tiles would have taken two $20 operations to form, so it's about right regardless.

![3 tile mountain](https://cloud.githubusercontent.com/assets/6338134/10714438/973d9848-7aac-11e5-977b-17b236ec456c.png)

A 4x4 mountain costs $1,280 to start, which is well above the $20 \* 36 = $720 we might expect to pay for it.  This is the turning point:  we could have built the same shape for less money using the standard tools.

![4 tile mountain](https://cloud.githubusercontent.com/assets/6338134/10714441/bb0d9d04-7aac-11e5-8274-bff002bb9171.png)

It doesn't get better from here.  Starting a 64x64 mountain costs $327,680, which is way above the estimated $87,120.

It seems that the mountain tool is very naive in its pricing:  it simply multiplies the one-tile price by the number of tiles in the selection.  This isn't really the best way to go about it because it overcounts redundant land-moving operations.  I propose we change the pricing scheme to evaluate how much money it would cost if tiles were moved manually and use that value instead of the naive multiplication.

**Comment by HaasJona** [comment]
On the other hand, the mountain tool is way too cheap sometimes. 
![bildschirmfoto von 2015-10-25 12-41-21](https://cloud.githubusercontent.com/assets/4310707/10715392/bc090cc0-7b15-11e5-973d-a380fe1c2102.png)

Creating the mountain on the picture only costs $800, while with single tile operations, this would cost more than 20 times as much.

**Comment by e-foley** [comment]
Interesting, @HaasJona.  If the same pricing is true in RCT1, maybe we should be working around that rather than the cost of single-tile operations that I proposed.

**Comment by HaasJona** [comment]
Rct1 mountain tool pricing is the same. The dollar values don't make sense at all. I don't think we should emulate it.

**Comment by jensj12** [comment]
To make it even more complicated (but consistent and fair in all cases), I'd vote for $5 per quarter tile raised, even for the normal land tool. Would keep the first step for single-tile mountain tool at $80 and the normal single tile tool at $20, but offers a discount when raising only a quarter of the tile (the $20 price tag felt never fair to me) and gives a good formula for multi-step mountain tile operations.

**Comment by HaasJona** [comment]
That's a very good idea. But if we want to preserve compatibility for now I could also live with the manual quarter tile tool still costing 20$ as long as the mountain tool costs the more reasonable 5$ per quarter tile operation. We could imagine getting a discount because we keep the land flat, not requiring support structures and so on.

**Comment by jensj12** [comment]
I found a way to make the single-tile mountain tool cost 101 times more than $80 (or more if I wanted to):
![mountaintoolcost](https://cloud.githubusercontent.com/assets/13868449/18035949/e8e63202-6d60-11e6-9938-46278bc2fc1f.jpg)
I'm working on fixing this.
