### ISSUE TITLE
Can't build (un)banking slope turns with RCT1 vehicles.

### ISSUE THREAD

**Issue by ZeeMaji** [OpenRCT2/OpenRCT2#21286]
### Operating System

Linux (OpenSUSE Tumbleweed)

### OpenRCT2 build

OpenRCT2, v0.4.7

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

While finishing up the RCT1 vehicles, i noticed that i could not build the (un)banking slope turns with the RCT1 vehicles even though they have sprites for these elements. ("slopes12Banked22": 16, in object json)

Vertical drop coaster vehicle object to test with can be found here.
https://github.com/spacek531/RCT1Vehicles/tree/master/objects/rct1/ride/rct1.ride.vertical_drop_trains

### Steps to reproduce

1. Download and install the RCT1 vertical drop train object if you don't already have it
2. Select it in a park while ensuring that it's the only vertical drop coaster train enabled
3. Try to build an (un)banking slope turn.
4. Can't build an (un)banking slope turn.

### Attachments

Current behavior, (un)banking slope turn not available even though the vehicle has sprites for it.
![Screenshot_select-area_20240127202339](https://github.com/OpenRCT2/OpenRCT2/assets/42477864/9c140684-88da-4fc2-9ed5-b8ff5d6f1a17)

What it should look like, forcibly enabling it with the enable all track pieces cheat.
![Screenshot_select-area_20240127202352](https://github.com/OpenRCT2/OpenRCT2/assets/42477864/2ba8f469-2b38-4028-bcf0-bcf1aa79eba7)

**Comment by Gymnasiast** [comment]
Culprit is https://github.com/OpenRCT2/OpenRCT2/blob/f2862861ce53b765180292f7ac6ab404300ee7e2/src/openrct2/ride/Ride.cpp#L4818

This currently requires banked sloped sprites. It should be changes to require unbanked sloped sprites + banked unsloped sprites instead.
