### ISSUE TITLE
Letters sticking out of the Map window

### ISSUE THREAD

**Issue by Opi-Txm** [OpenRCT2/OpenRCT2#21289]
### Operating System

Windows 11 Pro,  64-bit

### OpenRCT2 build

OpenRCT2, v0.4.7

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

The "Info, Kiosk" string in some languages is too long and does not fit the window.
Also when you move the screen by moving the cursor to the edge of the screen while having the "Info, Kiosk" tag outside of the window, it would print out the letters outside a lot of times and looks buggy.

![スクリーンショット 2024-01-28 124856](https://github.com/OpenRCT2/OpenRCT2/assets/106656898/a9eff951-c61a-4e0f-8f15-6536290eaf19)
![スクリーンショット 2024-01-28 124920](https://github.com/OpenRCT2/OpenRCT2/assets/106656898/da8034d0-dbe8-4be3-a6ed-7bbdc55b599a)

### Steps to reproduce

1. Change the language to one of the following: Català, Español, Français, Français (CA), Japanese, Português
2. Open a park.
3. Click on the map option in the top toolbar and show the map.
4. Change the tab inside to "Show rides and stalls on map".

**Comment by mrmbernardi** [comment]
I would bet that the characters falling off the window onto the map are due to the dirty region not encompassing the drawn string. This might have the same cause as the text going off the window, or not.

**Comment by mrmbernardi** [comment]
Its even more egregious in Catalan where the text from one row runs into the next.

![image](https://github.com/OpenRCT2/OpenRCT2/assets/7877312/ccb0a604-65ca-4294-8ba8-9e063f7895ad)
