### ISSUE TITLE
OpenRCT2 tab in the About window not respecting the github link for TTF fonts

### ISSUE THREAD

**Issue by Opi-Txm** [OpenRCT2/OpenRCT2#21288]
### Operating System

Windows 11 Pro,  64-bit

### OpenRCT2 build

OpenRCT2, v0.4.7

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

For languages such as Japanese and Korean that uses TTF fonts, text in the OpenRCT2 tab in the About window in the main screen does not open up space for the github link and writes the link over the text.

### Steps to reproduce

1. Open the game
2. Change the language to Japanese
3. Click on the OpenRCT2 logo at the top left

### Attachments

![Japanese](https://github.com/OpenRCT2/OpenRCT2/assets/106656898/f4840561-5422-42c5-8d9d-220ce9ac71b8)
![Korean](https://github.com/OpenRCT2/OpenRCT2/assets/106656898/3056b53c-5079-481b-9e8b-2aafe7d0f197)

**Comment by Gymnasiast** [comment]
This is most likely caused by the text drawing assuming a specific height for each section, rather than checking the return value of the call to DrawTextWrapped().
