### ISSUE TITLE
Misleading messages when building out of park bounds

### ISSUE THREAD

**Issue by e-foley** [OpenRCT2/OpenRCT2#2129]
This is an issue that is partially original and partially new to OpenRCT2.

Try building a flat ride whose footprint is partially inside and partially outside the park's boundaries.  If the selection cursor itself is inside the park bounds, you'll receive a "Too high for supports!" message in both OpenRCT2 and Vanilla where it would make more sense to be told you're building on land you don't own:

**OpenRCT2 and Vanilla**
![high_for_supports](https://cloud.githubusercontent.com/assets/6338134/10714617/1bdd362e-7ab4-11e5-9a5b-6fcff52e7d34.png)

If the selection cursor itself is outside the park boundaries, you'll get different results in OpenRCT2 and vanilla:

**OpenRCT2**
![no_message](https://cloud.githubusercontent.com/assets/6338134/10714622/5d1e4e5c-7ab4-11e5-91a8-67f6cf19d5f4.png)

**Vanilla**
![land_not_owned_vanilla](https://cloud.githubusercontent.com/assets/6338134/10714625/b6fc1350-7ab4-11e5-95ef-20aff5125a9b.png)

OpenRCT2's message should be altered to match the original's in this case.

Thanks for tolerating all the original bug reports I'm sending.  I just want to cover all the quirks I remember from RCT2 before I forget them. :)

**Comment by duncanspumpkin** [comment]
No problem putting up lots of original bugs, they can all be looked at eventually.

**Comment by Overv** [comment]
I'm looking into this right now.

**Comment by duncanspumpkin** [comment]
Fixed by #2147
