### ISSUE TITLE
Saving a created scenario

### ISSUE THREAD

**Issue by Psmith7990** [OpenRCT2/OpenRCT2#21294]
### Operating System

Windows 11, 64

### OpenRCT2 build

OpenRCT2, v0.4.7-89-gdb2a8af (db2a8af on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

i was trying to create a scenario and completed the landscape portion of the process, but it seems like i can't set where my guests enter the map as it's not letting me go on to the invention list setup.

### Steps to reproduce

since i can't upload the landscape file, i can't give you any steps except to try to create a scenario.

### Attachments

unfortunately, i can't upload the landscape file and screenshots wouldn't do any good as the error message i get isn't visible long enough for me to even read a single word

**Comment by HtotheTML** [comment]
By default placing a piece of pathway at the edge of the map should create a guest spawn point, but if you want to manually set it, click on the button with a guest sprite on it in the map window.
![image](https://github.com/OpenRCT2/OpenRCT2/assets/108596959/35494941-c13d-4cf4-9237-2b437f0cef2c)

**Comment by Psmith7990** [comment]
I had already done that.  What I found out after going back into the landscape is that the sprite generation point has to be out side the park boundary. I had to move the park boundary off the edge of the map by one tile on that side of the map.  That allowed me to place the generation points (yes, two).

**Comment by HtotheTML** [comment]
Nice! were you able to get the matter all resolved, then?

**Comment by Psmith7990** [comment]
I did!
As long as there is at least a single row of unowned tiles along the map edge where the sprite generation point(s) is (are), that should be good to go.
