### ISSUE TITLE
Virtual floor for building scenery at non-ground level not properly invalidated when moving cursor while releasing shift key

### ISSUE THREAD

**Issue by zzril** [OpenRCT2/OpenRCT2#21318]
### Operating System

Linux

### OpenRCT2 build

8abda17cb3bb204a2394eb7311c221f0e69a2c46

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

When building scenery above the ground via pressing the shift key, the blue "virtual floor" that is displayed at the height the scenery would be built at is not properly invalidated after the shift key has been released.  
More precisely, if the cursor is moved *while* releasing the shift key, parts of the floor will remain visible.  
As usual, invalidation / redrawing can be forced by hovering over the affected areas.

![release-up](https://github.com/OpenRCT2/OpenRCT2/assets/84280965/59f32968-9fd5-4bf7-9a84-6a16ea381c21)

### Steps to reproduce

1. Start any scenario or track designer
2. Select "build scenery" and then some basic block
3. Move cursor at middle or lower part of screen, somewhere above flat land
4. Press shift and hold it ("virtual floor" gets displayed)
5. Move cursor up and release shift during the movement (parts of "virtual floor" remain visible)

**Comment by sungaila** [comment]
Can confirm, this happens on my Windows machine as well. Looks like it is related to the software renderer as I couldn't reproduce it with OpenGL at all.

![image](https://github.com/OpenRCT2/OpenRCT2/assets/12021771/3c7e585f-26be-43a3-9cf8-dbc7e9c099b6)

**Comment by ZehMatt** [comment]
> Can confirm, this happens on my Windows machine as well. Looks like it is related to the software renderer as I couldn't reproduce it with OpenGL at all.
> 
> ![image](https://private-user-images.githubusercontent.com/12021771/303779760-3c7e585f-26be-43a3-9cf8-dbc7e9c099b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1MTUxNDcsIm5iZiI6MTcwNzUxNDg0NywicGF0aCI6Ii8xMjAyMTc3MS8zMDM3Nzk3NjAtM2M3ZTU4NWYtMjZiZS00M2EzLTljZjgtZGJjN2U5YzA5OWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDIxNDA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyNjQwNmRiZjgxNjM3NDY3M2Y0MmJiMDk3Mzg4N2QxNjg2NmE1Y2VmYzZmYzQ3MDZmOGY5Zjg5ZDdiYTE4NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KU3nILap0VzYtboRO4K1n6tNv76N5oKqbrveZvuWf24)

The reason this doesn't show up in OpenGL is that Software has a mechanism for invalidating certain regions to be redrawn where OpenGL redraws the entire visible space each frame. There is somewhere some invalidation call missing.
