### ISSUE TITLE
Track Designer allows proceeding to track designer step without any vehicle/attraction selected

### ISSUE THREAD

**Issue by zzril** [OpenRCT2/OpenRCT2#21317]
### Operating System

Linux

### OpenRCT2 build

8abda17cb3bb204a2394eb7311c221f0e69a2c46

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

In the track designer, before allowing the player to proceed from the initial "object selection" step to the actual "track designer" step, the game usually checks if the player has selected at least one vehicle / attraction, and forbids proceeding to the next step otherwise.  
This check is not executed when proceeding to the track designer step by simply closing the object selection window.  
This is somewhat inconsistent.

### Steps to reproduce

1. From main menu, start track designer
2. Proceed to next step without selecting any objects
3. Observe error message
4. Close object selection window
5. Observe that you have de facto proceeded to track designer step

**Comment by Harry-Hopkinson** [comment]
I would like to work on this issue, what should happen when the object selection window is closed? Should it take the user back to the main menu.

**Comment by zzril** [comment]
> I would like to work on this issue, what should happen when the object selection window is closed? Should it take the user back to the main menu?

I think proceeding to the actual track design step is fine.  
It should just do it in the same way as when clickling the "next" button in the [bottom toolbar](https://github.com/OpenRCT2/OpenRCT2/blob/8abda17cb3bb204a2394eb7311c221f0e69a2c46/src/openrct2-ui/windows/EditorBottomToolbar.cpp#L206-L220). I. e. run `CheckObjectSelection()` first and `FinishObjectSelection()` only if that succeeded. And also open the ride construction window then.

---

I have noticed the same in the scenario editor btw. [Closing](https://github.com/OpenRCT2/OpenRCT2/blob/8abda17cb3bb204a2394eb7311c221f0e69a2c46/src/openrct2-ui/windows/EditorObjectSelection.cpp#L355-L367) the object selection window allows you to proceed to the landscape editor in an "invalid state", e. g. with no entrance selected.  
(The landscape editor then gives you an option to place an invisible park entrance that guests will not be able to walk through.)

Again, proceeding to the next editor step is fine here, but it should happen in the same way as when doing it via the "next" button.

---

Ideally, closing the object selection window (and thereby proceeding to the next scenario editor / track designer step) should also be possible by pressing backspace.  
Currently, pressing backspace closes and immediately re-opens the window in the track designer, while simply nothing happens when doing so in the scenario editor.

**Comment by Harry-Hopkinson** [comment]
Does it look good how it is implemented in the PR. If the user tries to close the track designer window without an object selected they get the same error message that they would if they attempted to close using the next button on the toolbar. The same functionality also works in the Track Designer manager where it will not allow the user to close without selecting an object.

**Comment by zzril** [comment]
> The same functionality also works in the Track Designer manager where it will not allow the user to close without selecting an object.

The track designs manager works differently as it doesn't even have the bottom toolbar. Selecting a single object / ride type, immediately jumps to the "next stage" where you can choose a specific design for that ride type to rename / delete.  
Simply going back to menu in case the window is closed makes sense here imo.

---

The behavior also seems to be different when attempting to close the window via the backspace hotkey. When doing so, nothing happens in the scenario editor whereas the window is immediately re-opened in the track designer / track designs manager.

**Comment by Harry-Hopkinson** [comment]
Ok I changed it now so that it does not impact the Track design manager so it defaults to the title screen when closing the object selection window.
