### ISSUE TITLE
Path destroyed by hovering n

### ISSUE THREAD

**Issue by bobtheblueberry** [OpenRCT2/OpenRCT2#21337]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.4.8 (05efdb2) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

When two paths are on the same tile at different heights, the top path can be destroyed by hovering a new ride ghost track with saved path scenery.
![stage1](https://github.com/OpenRCT2/OpenRCT2/assets/611025/aae09227-bb4a-434e-9fab-10f1947a879a)
![stage2](https://github.com/OpenRCT2/OpenRCT2/assets/611025/72fb2c2b-9219-4c80-9bf1-1a8854a08b56)

### Steps to reproduce

Starting from the ground, build a stairs going upward. Place one path tile under the stairs at the lowest possible point of the stairs. Start to build a new ride with saved path, such as the _Stand-up Roller Coaster_ track _Red Baron_ with saved path. When the ghost path is placed over the path tile with two paths, the upper path will disappear.

### Attachments

[Red Baron.zip](https://github.com/OpenRCT2/OpenRCT2/files/14174030/Red.Baron.zip)
[path_bug.zip](https://github.com/OpenRCT2/OpenRCT2/files/14174031/path_bug.zip)

**Comment by ZehMatt** [comment]
Same issue as #21219, closing as duplicate.
