### ISSUE TITLE
Map Size is off by 2

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#2133]
This is an original bug, but I couldn't find an issue about it, only someone mentioning it in #1162.

When setting the map size, the amount of tiles is off by 2. Setting it to 15x15 for example will actually generate a map of 13x13 (and with the offset of  land you can own it only leaves 11x11).

![Screenshot](http://i.imgur.com/swcrXMg.png)

**Comment by IntelOrca** [comment]
This is because the there is a hidden border of tiles around the map with a base height of 0, presumably so that the vertical faces on the edge of the map are drawn correctly.

**Comment by Gymnasiast** [comment]
Still, that is a technical detail regular users should not worry about. In practical terms, that map is 13x13.

**Comment by IntelOrca** [comment]
Just subtract 2x2 from the spinner then.

**Comment by Gymnasiast** [comment]
Yes, that was what I was thinking too.

**Comment by IntelOrca** [comment]
This should also include the text input window and the map generator window.
