### ISSUE TITLE
Tooltip text in Color Chooser jumps

### ISSUE THREAD

**Issue by bobtheblueberry** [OpenRCT2/OpenRCT2#21330]
### Operating System

Window 10

### OpenRCT2 build

OpenRCT2, v0.4.8 (05efdb2) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

When choosing a color in the color chooser, the tooltip text displaying the color's name flashes and jumps around on the screen. The tooltip briefly appears in the correct location, then flickers and is displayed where the mouse was clicked instead of the hovering position of the cursor.

### Steps to reproduce

Build a new attraction, change a color option in "Color scheme options".

### Attachments

![scr1](https://github.com/OpenRCT2/OpenRCT2/assets/611025/58c3e438-ab15-41c4-84df-359362a582f9)

**Comment by bobtheblueberry** [comment]
This may be similar to #21329

**Comment by cheweytoo** [comment]
You were faster than me :-)

Video:

https://github.com/OpenRCT2/OpenRCT2/assets/29800630/6aa104d8-363d-407d-a7b2-374d0ad38bad

First with click-and-hold (keeping the left mouse button pressed), then with click-and-hover (left mouse button released after opening the color picker).

This is in the Linux AppImage build 08fbdd1.

**Comment by tupaschoal** [comment]
Likely a regression from #21192, what do you think @ZehMatt ?

**Comment by ZehMatt** [comment]
Hm maybe, I'll look into it when I've got some spare time.
