### ISSUE TITLE
Incorrect brake speed applied to Mini Coaster

### ISSUE THREAD

**Issue by formlesstree4** [OpenRCT2/OpenRCT2#2134]
Track File: https://www.dropbox.com/s/wdcedyhi4ni6gvf/Space%20Simulator.TD6?dl=0

The brakes are supposed to first slow to 18mph, then, to 9mph. However, the game doesn't seem to always respect that. I've watched several test runs of the above track file slow the car anywhere from 4mph to 9mph as its actual speed. This did not used to happen.

I am on build 1363 and I'll be testing other types out.

**Comment by e-foley** [comment]
Tested the same track on vanilla, replacing the brake sections just to make sure the brake speed didn't get corrupted between versions.  I note that the cars braked to the following values...

4, 4, 3, 7, 3, 6, 6, 7, 4, 4, 4, 4, 4, 6, 6, 4, 4, 7 [mph]

You say it "did not used to happen," but the original RCT2 seems to display the same behavior you're seeing in OpenRCT2.  The brake values have always been a little off for short trains, I've noticed... With this particular coaster, it tends to cause cars to "bunch up" after the brake section and eventually bounce off each other.

**Comment by Gymnasiast** [comment]
I'm not sure this can be called a bug then. It might very well be intended behaviour. It's not like real life brakes will always yield a speed that's exactly the same down to 1 mph.

**Comment by IntelOrca** [comment]
We can't investigate this until we have implemented vehicle_update, currently its all using the original code so I would be surprised if this behaviour was different from the original game.

**Comment by formlesstree4** [comment]
> Tested the same track on vanilla, replacing the brake sections just to make sure the brake speed didn't get corrupted between versions. I note that the cars braked to the following values...

I thought perhaps it wasn't an issue in vanilla. It would seem I'm not remembering correctly! My apologies for misleading.
