### ISSUE TITLE
Create constant for GameState_t::ParkRatingHistory 

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#21346]
Currently GameState_t::ParkRatingHistory has a hardcoded size of 32. This could be replaced with a constant.

**Comment by InsigMath** [comment]
Is this still available? I wouldn't mind trying this

**Comment by Gymnasiast** [comment]
It is, yes.

**Comment by InsigMath** [comment]
So doing a quick look at this method for GameState_t, I see this:

![image](https://github.com/OpenRCT2/OpenRCT2/assets/2395535/768c1a72-c2be-4e9f-88db-91129de0a2c5)

Isn't this a constant for that method or am I misunderstanding which ParkHistory value you are talking about or what you mean by a constant.

**Comment by InsigMath** [comment]
Or what you guys want is an enum instead of the number 32?

**Comment by Gymnasiast** [comment]
My apologies, this has indeed already been done (in https://github.com/OpenRCT2/OpenRCT2/pull/21665 ), but this issue was left open by mistake.
