### ISSUE TITLE
New ride/attraction now available button yields interesting results

### ISSUE THREAD

**Issue by formlesstree4** [OpenRCT2/OpenRCT2#2135]
Save File: https://www.dropbox.com/s/ayq8kecwym7fz7a/Bumbly%20Beach.sv6?dl=0

If you go to the "Recent Messages" window and press the blue new ride button for the "Mini Roller Coaster", the Rides & Attractions dialog appears with no content and the menu title as "Traveling at ##mph" where the pound symbols are replaced with various random numbers.

Button in question:
http://puu.sh/kXYfK/831ee1d1e1.png

What happens when you click the button:
http://puu.sh/kXYi9/b40bd1c187.png

Please note that the Junior Roller Coaster button is perfectly fine. If you keep the save file loaded long enough, Go Karts will get researched. That button is not glitched either.

**Comment by e-foley** [comment]
Confirmed, but I note this only happens if you have the "Select Rides by Track Type" option on.

**Comment by Gymnasiast** [comment]
Seems to be a broken save. I cannot reproduce this in a clean scenario, even with 'Select by track type' on.

**Comment by formlesstree4** [comment]
@Gymnasiast I'm sad that it's a broken save. :( I literally started the game, saved it, and that happened.

**Comment by IntelOrca** [comment]
@formlesstree4 I'll try to investigate this later.

**Comment by Gymnasiast** [comment]
@formlesstree4 : If the save was broken by OpenRCT2, that still means there is a bug. We just need to determine where the cause of the bug lies. :)

**Comment by janisozaur** [comment]
This is working in 755485f
