### ISSUE TITLE
openrct2 Android bug?

### ISSUE THREAD

**Issue by ducl137** [OpenRCT2/OpenRCT2#21364]
### Operating System

 Android 

### OpenRCT2 build

OpenRCT2, v0.4.8-11-g6e49a25 (6e49a25 on develop) provided by GitHub

### Base game

openrct2

### Describe the issue

From version 0.4.7 to version 0.4.8, it does not enter the scenario and it says there is no object data file.
I don't know if my file is the problem or a bug

### Steps to reproduce

![KakaoTalk_20240210_105129775](https://github.com/OpenRCT2/OpenRCT2/assets/120288316/5c23c5dd-1a28-49a8-8a92-f3ffd3a1962a)

### Attachments

![KakaoTalk_20240210_105129775](https://github.com/OpenRCT2/OpenRCT2/assets/120288316/38b60f42-c32d-4609-ad7e-27448a6dbc14)

**Comment by ducl137** [comment]
> ### Operating System
> Android
> 
> ### OpenRCT2 build
> OpenRCT2, v0.4.8-11-g6e49a25 ([6e49a25](https://github.com/OpenRCT2/OpenRCT2/commit/6e49a25a7b4a9451bd22db75b52e2c976e4a7c9d) on develop) provided by GitHub
> 
> ### Base game
> openrct2
> 
> ### Area(s) with this issue?
> _No response_
> 
> ### Describe the issue
> From version 0.4.7 to version 0.4.8, it does not enter the scenario and it says there is no object data file. I don't know if my file is the problem or a bug
> 
> ### Steps to reproduce
> ![KakaoTalk_20240210_105129775](https://private-user-images.githubusercontent.com/120288316/303808745-5c23c5dd-1a28-49a8-8a92-f3ffd3a1962a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NjA4NzAsIm5iZiI6MTcwNzU2MDU3MCwicGF0aCI6Ii8xMjAyODgzMTYvMzAzODA4NzQ1LTVjMjNjNWRkLTFhMjgtNDlhOC04YTkyLWYzZmZkM2ExOTYyYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMFQxMDIyNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZWNlNDFjOTU4ODYyZTgzYWZhNzFkOGQwMTkwZThjZTBjNjlhYzJkOTc2ZjQ5MzE4NzM5Y2NkMjYzYjVjZTM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZWC-oZ40bHrcaxvTkpPT9BiNFYtPEu2Z4yBCl05OYJg)
> 
> ### Attachments
> ![KakaoTalk_20240210_105129775](https://private-user-images.githubusercontent.com/120288316/303808754-38b60f42-c32d-4609-ad7e-27448a6dbc14.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NjA4NzAsIm5iZiI6MTcwNzU2MDU3MCwicGF0aCI6Ii8xMjAyODgzMTYvMzAzODA4NzU0LTM4YjYwZjQyLWMzMmQtNDYwOS1hZDdlLTI3NDQ4YTZkYmMxNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMFQxMDIyNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2JjZmFkYTc3YjZjOTRlY2Q2ZTg4ZWQ2ZDIyMmI3YWQ2MGMxYWY1NmVjYmJiZjEzZjFkZGNkZmYwYmZjZTJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vTKGYqH-FXsd8ObZHvuGHzu5hHDwLhM_UBa6ioeS4VE)

**Comment by Gymnasiast** [comment]
It sounds like your objects are out of date, i.e. you have an .apk that is newer than the objects you used.

**Comment by ducl137** [comment]
0.4.8 Even if I install the developer version, I get the same error.

**Comment by Gymnasiast** [comment]
Which exact source did you use for the objects?

**Comment by ducl137** [comment]
> 사용할 수 있는 소스/다운로드를 사용할 수 있습니까?

That's right

**Comment by ducl137** [comment]
> 사용할 수 있는 소스/다운로드를 사용할 수 있습니까?

I think so
