### ISSUE TITLE
Glitched Scenery Window?

### ISSUE THREAD

**Issue by formlesstree4** [OpenRCT2/OpenRCT2#2136]
Save File: https://www.dropbox.com/s/ayq8kecwym7fz7a/Bumbly%20Beach.sv6?dl=0
(This is the same save file in #2135 )

If you open the Scenery Window, there is a "Miscellaneous Objects" section that has a mislabeled tool tip. I'm not sure i'm supposed to even see this. It does look like pieces of scenery that would belong in groups if they were available.

Screenshot: http://puu.sh/kXYoa/6ef297a2d9.png

**Comment by e-foley** [comment]
Confirmed.  This seems to be specific to OpenRCT2 since opening the file in vanilla causes the tooltip to read "Miscellaneous Objects" as expected.
