### ISSUE TITLE
Multiple Enterance Types Selected

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#2138]
https://openrct.net/cloud/uploads/98f7a672b75bcfa348fd240049e7eb56.sv6

![doubleselection](https://cloud.githubusercontent.com/assets/3945538/10738544/47480966-7bee-11e5-9039-f5ef38ec4828.png)

**Comment by PFCKrutonium** [comment]
Upon loading the map it seems like it fixed itself...

**Comment by duncanspumpkin** [comment]
It will be caused by the change in dropdown code last week

**Comment by duncanspumpkin** [comment]
Fixed in #2176
