### ISSUE TITLE
Multiplayer: Crash when others build ride parts that were ghosts when they joined

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#2140]
When a player joins a game while someone who is already in the game has a ghost for a ride ready to be placed, the player will crash as soon as this part is placed.

![Screenshot](http://i.imgur.com/m1G6wrz.png)

Step by step:

1. Start a server (Host)
2. (Optional) Join the server in another instance (Client 1)
3. Pick any ride and keep its ghost ready to be placed (on Host or Client 1)
4. Join the server with another instance (Client 2)
5. Place the first part of the ride

Anyone who joined before the ride was picked will have no issues, but the one who joined while the ride was about to be placed will crash. No extra verbose output is being printed to the console before it crashes.

**Comment by Broxzier** [comment]
In VS I get the following error:
Exception thrown at 0x0F0C35B6 (openrct2.dll) in openrct2.exe: 0xC0000005: Access violation reading location 0x00000004.

It breaks on line 1410 in file viewport.c

**Comment by janisozaur** [comment]
I'm not able to reproduce it.

**Comment by IntelOrca** [comment]
I think I fixed this not long ago, but lets see if @Broxzier can reproduce it first.

**Comment by Broxzier** [comment]
Confirmed, it's working as expected now.
