### ISSUE TITLE
Dropdowns don't properly handle trains with new minimum length

### ISSUE THREAD

**Issue by e-foley** [OpenRCT2/OpenRCT2#2142]
This is an OpenRCT2-exclusive bug tested in build 1365.

1. Build a monorail that is at least four station platform tiles long.
2. Change the vehicle type to "Streamlined Monorail Trains."
3. Set the train length to 2 cars per train.
4. Switch back to "Retro-style Monorail Trains."

The train will appear to be two cars long in the preview, and clicking the dropdown menu reveals that the option for 2 cars per train isn't even available normally.

That said, testing the ride places three cars per train regardless:

![scr19](https://cloud.githubusercontent.com/assets/6338134/10750069/454130ee-7c2e-11e5-9b3d-d50c771246a3.png)

This behavior does not happen in the original RCT2.

**Comment by duncanspumpkin** [comment]
Is this still happening?

**Comment by e-foley** [comment]
You betcha.

**Comment by ajanes3** [comment]
Also experiencing this. Can't have more than two cars per train on the monorail.
