### ISSUE TITLE
Guest Objective Overflows when reaching past 32,750

### ISSUE THREAD

**Issue by BetterSkatez** [OpenRCT2/OpenRCT2#21434]
### Operating System

Windows 10, Windows 11, 64-Bit

### OpenRCT2 build

OpenRCT2

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

When the guest objective goes past 32,750, it overflows and rolls back to -32,736 as any number past 32,768
 (the signed 16-bit integer limit)![Overflow](https://github.com/OpenRCT2/OpenRCT2/assets/160580786/74dd1f32-14c9-401b-800d-5a4dbe203ab6)

### Steps to reproduce

1. Open Scenario Editor
2. Make the objective certain guests in the park
3. Put the input above 32,768 guests

**Comment by Gymnasiast** [comment]
Probably best to just format numbers like these as 64-bit integers throughout and be done with it, like we did with money.

**Comment by jan-kelemen** [comment]
PR which fixes the issue, https://github.com/OpenRCT2/OpenRCT2/pull/21518, I can fix the other translations as well if the solution is ok.
