### ISSUE TITLE
Latest Windows Update breaks all sound in game

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#21451]
### Operating System

Windows 11 Pro Insider Preview Canary

### OpenRCT2 build

OpenRCT2, v0.4.8-114-g7797db1 (7797db1 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

After updating windows in the Insider Preview Canary channel today there is no audio in OpenRCT2

### Steps to reproduce

Update to Windows Insider Preview Canary. There is no sound in OpenRCT2 now.

**Comment by Gymnasiast** [comment]
Closing this as it is a bug in a beta version of Windows. If it makes its way to a regular update, we might have to get on it.
