### ISSUE TITLE
Abnormal & inconsistent running costs for certain rides or buildings depending on park/scenario

### ISSUE THREAD

**Issue by rondadams** [OpenRCT2/OpenRCT2#21484]
### Operating System

All

### OpenRCT2 build

v0.4.8 

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

Reported on Reddit: https://www.reddit.com/r/openrct2/comments/1b1r4ih/comment/ksmh0tr/

Finished the Katie's World scenario (an RCT1 scenario) a few days ago and was checking various stats for my rides and stalls before moving on to the next scenario, when I discovered this:

https://i.imgur.com/l21ppBS.jpg

Running cost for Restroom 4 is $80/hr, which is not the standard running cost for a restroom.

Here's three save files from the park.

[June, Year 1](https://drive.google.com/file/d/1AvZeqLHrE9mlm2usRB8SydfX43zIwuW_/view)
[April, Year 3](https://drive.google.com/file/d/1b_jehwnagPGs0RZcwLaD7YNOurp-y5LV/view)
[March, Year 4](https://drive.google.com/file/d/1zKRUI_VoNJ-S1ArKiW6IGVyG7CgA6zgW/view)

All three show Restroom 4 with a running cost of $80/hr.

I posted a thread about it in [r/rct](https://www.reddit.com/r/rct/), and got the following comments:

Confirmed by --[u/grumpyfan](https://www.reddit.com/user/grumpyfan/)
I downloaded your files and played with it a bit and couldn’t find anything wrong with it. I added another bathroom directly across and the running cost was $-49.60. I even deleted it and added it back, and it came back as Restroom 4 and then cost jumped again. I also opened the tile inspector but didn’t see anything different than the one I built directly across. It’s REALLY odd! Hopefully someone who knows the behind the scenes of the game more will chime in. I’m real invested now.

Also, --[u/ffsffs1](https://www.reddit.com/user/ffsffs1/)
Seems to be a bug. In my most recent Gravity Gardens save my "Toilets 4" also has a running cost of $80.00 per hour. Starting up Dusty Greens, I built 4 restrooms and while "Toilets 4" had a normal run cost, while "Toilets 3" had a run cost of $68.80 (instead of $49.60). In Factory Capers, it is the 5th restroom. I tested this 4-5 times in both maps using different locations. Meanwhile, in Crazy Castle I found no anomalies.

Moreover, in Dusty Greens if I build a ride first, the 2nd restroom will be the one that costs $68.80. If I build 2 rides first, then the first restroom will have the abnormal run cost. If I build 3 space rings, the 3rd space rings costs more than the first two. Same thing happens building 3 top spins, or 3 information kiosks. Building coasters seem to kill this pattern. For whatever reason, sometimes the nth ride/shop is guaranteed to have abnormal running costs.

All these were in openRCT2 btw.

### Steps to reproduce

1. Open Katie's World scenario. 
2. Build 4 Restrooms. 
4th restroom has an abnormal running cost of $80, compared to the others that have $49.60. 
![ORCT2RR4](https://github.com/OpenRCT2/OpenRCT2/assets/14861727/09f59c36-72c8-4928-8256-84a07e53f8db)

**Comment by janisozaur** [comment]
That sounds like something we could add a test for

**Comment by ZehMatt** [comment]
Definitely, I'm surprised that our existing ride rating tests didn't include that given its one of the things it actually calculates.
