### ISSUE TITLE
Automatically set double pixel scale for double density displays

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#21494]
As suggested by @AaronVanGeffen

**Comment by AaronVanGeffen** [comment]
I was going to file an issue for this, but thanks

**Comment by karstenvanf** [comment]
@InsigMath Are you still working on this? If not, I would like to take a crack at it. It seems like a solution would work in a similar vein to #6991 .

**Comment by InsigMath** [comment]
@karstenvanf yeah go for it! If you think you have a solution then I don't mind you implementing it.
