### ISSUE TITLE
Scenery being hidden after saving & reloading

### ISSUE THREAD

**Issue by ZeeMaji** [OpenRCT2/OpenRCT2#21496]
### Operating System

Linux (OpenSUSE Tumbleweed)

### OpenRCT2 build

OpenRCT2 Actions build 8119042284

### Base game

RollerCoaster Tycoon 2

### Describe the issue

When saving & reloading an RCT1 park, scenery items that aren't enabled by a scenery group directly (eg: jumping fountains, some walls, creepy trees in some parks) will be marked as hidden. Bizarrely, the ignore research status cheat shows them instead of the sandbox mode cheat even though the sandbox mode cheat is supposed to reveal hidden scenery items.

This can be easily observed in blackpool pleasure beach with the jumping fountains and many other scenery pieces.

### Steps to reproduce

1. Open BPB from RCT1
2. Save and reload
3. Various scenery pieces will now be hidden behind the ignore research cheat.

### Attachments

BPB paths additions group

Before reloading:
![Screenshot_select-area_20240301200534](https://github.com/OpenRCT2/OpenRCT2/assets/42477864/c385c856-ef11-40c1-bc89-3fc65da32c5f)

After reloading, no jumping fountains:
![Screenshot_select-area_20240301200546](https://github.com/OpenRCT2/OpenRCT2/assets/42477864/dc06470b-50b8-4a5c-aa55-f2673da7e2c2)

**Comment by Gymnasiast** [comment]
Some additional information: they are not marked as restricted. There is likely a bug in the code of the window that hides them by accident.

**Comment by MASHzj** [comment]
Shouldn't creepy trees be hidden when you don't have the creepy theme available, just like the mine objects in Forest Frontiers or the houses in Bumbly Beach? I think they are hidden in that case in vanilla RCT1, but I can't test it for sure.

**Comment by TheClaudeQC** [comment]
> Shouldn't creepy trees be hidden when you don't have the creepy theme available, just like the mine objects in Forest Frontiers or the houses in Bumbly Beach? I think they are hidden in that case in vanilla RCT1, but I can't test it for sure.

Yes, they are hidden in RCT1

**Comment by Gymnasiast** [comment]
Removed the RCT1 label as we also get reports about non-RCT1 scenarios.
