### ISSUE TITLE
When building a rollercoaster, attempting to use the advanced path makes the path tool attempt to continue building the rollercoaster.

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#2151]
![scr32](https://cloud.githubusercontent.com/assets/3945538/10805174/38819c02-7da2-11e5-97f4-f9cd72b3f5c0.png)

**Comment by raidcookie** [comment]
I've also noticed that, when building two coasters at the same time and switching between the coasters using right-click instead of accessing the build mode via the ride window, the build mode will switch to a completely unrelated ride.

**Comment by duncanspumpkin** [comment]
I don't really know what to do about this. What do we want to happen. I don't want to make it annoying to use the footpath tool and the ride construction windows at the same time.

**Comment by IntelOrca** [comment]
I can't reproduce this.

**Comment by duncanspumpkin** [comment]
I think this is the issue:
![2151](https://cloud.githubusercontent.com/assets/1277401/10894443/97f64360-81a6-11e5-9c14-7b73398d40ac.PNG)
As you can see it doesn't gracefully handle the two windows constructing in the same area.

**Comment by IntelOrca** [comment]
Err, well not a big deal in my opinion. I guess you could call the re-query selected ride piece when you place a path so that it changes from a ghost to just highlighted tiles if you do place the path where the ghost track piece is.

**Comment by duncanspumpkin** [comment]
Reopening since I didn't mean to merge the fix so early.

**Comment by IntelOrca** [comment]
Yeah always write "fix partially" or "potential fix **for** ###"

**Comment by duncanspumpkin** [comment]
I got mixed up with my other branch. :(
