### ISSUE TITLE
Banked diagonal incline support glitch

### ISSUE THREAD

**Issue by zalazarbiggins** [OpenRCT2/OpenRCT2#21533]
### Operating System

macOS Sonoma 14.3.1

### OpenRCT2 build

v0.4.9 (a172405 on HEAD)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

Supports are appearing above the track on banked diagonal inclines.

### Steps to reproduce

It doesn't seem to affect all of these pieces, but they all seem to glitch when a train travels over that section of the track.

### Attachments

<img width="845" alt="Screenshot 2024-03-05 at 11 44 51 PM" src="https://github.com/OpenRCT2/OpenRCT2/assets/125212699/90f69e35-4825-451a-bad6-a312307b2479">
<img width="592" alt="Screenshot 2024-03-05 at 11 43 42 PM" src="https://github.com/OpenRCT2/OpenRCT2/assets/125212699/0838998b-c0eb-4425-8fc5-47b77bf675a8">

**Comment by zalazarbiggins** [comment]
<img width="845" alt="Screenshot 2024-03-05 at 11 44 51 PM" src="https://github.com/OpenRCT2/OpenRCT2/assets/125212699/c6edf997-8006-4336-837d-e80599c06d67">

This one didn't come through.

**Comment by zalazarbiggins** [comment]
https://github.com/OpenRCT2/OpenRCT2/assets/125212699/8e0e7c96-aaca-457b-bebf-1d1c55732a1d

**Comment by zalazarbiggins** [comment]
https://github.com/OpenRCT2/OpenRCT2/assets/125212699/ba4867d0-15f6-42c6-8108-81cee3cd06b4

**Comment by zalazarbiggins** [comment]
<img width="708" alt="Screenshot 2024-03-06 at 12 17 05 AM" src="https://github.com/OpenRCT2/OpenRCT2/assets/125212699/a35c07ad-6bfc-45f5-87a7-b47e05035f07">

This one decided to pop out on one angle, and it wasn't when I was taking screen grabs earlier.

**Comment by MrBrightside711** [comment]
I am having the same issue
