### ISSUE TITLE
The Ride Music "Acid" & "Techno" are the same audio track (sounds the same)

### ISSUE THREAD

**Issue by 9robin3** [OpenRCT2/OpenRCT2#21557]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.4.9 (a172405) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

When building a new ride and going to the music tab > check play music, and select music track, and selecting acid, then techno or the other way around, they sound the same. The same music track is played despite being displayed as different options for music track to play. 

### Steps to reproduce

1. Build any ride
2. Go to the muisc tab
3. Check the "Play music" checkbox
4. Open the drop down menu to select music track to play for the ride
5. Select either "Acid" or "Techno"
6. Open the ride
7. Enable in-game music and unmute your speakers on the machine your using
8. Edit the ride, go to the music tab again
9. Select the other selection from step 5 (if you selected "Acid" here, select "techno", or vice-versa)
10. Listen to the newly selected music track to play.
11. They sound the same/ use the same aduio track, despite being displayed as different options, and are expected to use different audio track assets

### Attachments

![2](https://github.com/OpenRCT2/OpenRCT2/assets/10880238/0b4b9b93-949e-4577-a992-ddc7f4cf74a5)

**Comment by karst** [comment]
Hi Robin,
you have selected Asset Pack "OpenRCT2 Music (Alternative)" in the options menu. 
Please make sure you have unchecked this asset pack.
If you need any help, please let us know in this thread or on discord.

![image](https://github.com/OpenRCT2/OpenRCT2/assets/1516893/13ba3e7d-bdfa-4072-9c83-68748ee0442b)
