### ISSUE TITLE
Not All Ride Pictures Are Avaliable. Some Thumbnails of rodes are empty/not visible/showing up

### ISSUE THREAD

**Issue by 9robin3** [OpenRCT2/OpenRCT2#21556]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.4.9 (a172405) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

![image](https://github.com/OpenRCT2/OpenRCT2/assets/10880238/72286d3b-e50f-4e21-b5c7-f046429672c3)
When building a new water ride, sometimes the thumbnail pictures of a few rides wont show up, or be empty/not visible. This happens when opening the build rides menu, but it also happens (is not changed/resolved) when hovering over partocular rides. 

### Steps to reproduce

1. Open the build rides menu
2. Go to build new water rides.
3. Thumbnails of the following rides wont show up/ is empty/not visible: * Log Fume Crocodile Boats,, River Rapids - Oak Barrels, Submarine Ride - Hippo Submarines & Killer whale submarines, and a few others

### Attachments

![1](https://github.com/OpenRCT2/OpenRCT2/assets/10880238/846333d0-7349-49d4-a999-a921c508b507)

**Comment by Gymnasiast** [comment]
All vehicles you mentioned are those from Wacky Worlds and Time Twister. Most likely, you don’t have those expansions installed.
