### ISSUE TITLE
Giant screenshots are cropped weirdly

### ISSUE THREAD

**Issue by fidwell** [OpenRCT2/OpenRCT2#21565]
### Operating System

Windows 11, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.9-50-gd0592e0 (d0592e0 on develop)

### Base game

RollerCoaster Tycoon 2

### Describe the issue

In recent develop versions, giant screenshots are oddly cropped and rotated. This issue is not present in the current 0.4.9 release version.

### Steps to reproduce

Take a giant screenshot in any park.

### Attachments

Here is an example with Blackpool Pleasure Beach.

What the game looked like as I took the screenshot:
![image](https://github.com/OpenRCT2/OpenRCT2/assets/5436387/14d85297-3a16-47d4-b838-b20949240c5e)

The resulting image:
![Blackpool Pleasure Beach 2024-03-09 21-15-26](https://github.com/OpenRCT2/OpenRCT2/assets/5436387/da97158e-3045-4983-8efb-e50f30f69feb)

**Comment by duncanspumpkin** [comment]
@ZehMatt probably related to your pr

**Comment by ZehMatt** [comment]
> @ZehMatt probably related to your pr

Possible, I look into it when I get some time.
