### ISSUE TITLE
Remove unneeded function name Window

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#21569]
Now that windows are all under the OpenRCT2::Ui::Windows namespace there is no need to keep Window in the function name.

https://github.com/OpenRCT2/OpenRCT2/blob/7a60e7f2e09e002c13765380636e108cd2249a08/src/openrct2-ui/windows/Window.h#L40

So all of these Open functions should have Window removed from them.
I.e. `WindowAboutOpen` becomes `AboutOpen`

**Comment by CoryfY** [comment]
First time contributing, I can take a look at this.

**Comment by duncanspumpkin** [comment]
Great, have fun.
