### ISSUE TITLE
Video Freeze

### ISSUE THREAD

**Issue by FlukiestEmperor** [OpenRCT2/OpenRCT2#2158]
#2109 Introduced a bug where the video freezes.

How to reproduce - Only tested this on Windows

Have the game in windowed mode
Maximize the game if it's not already
Minimize the game
Click somewhere to focus on another window other than RCT2
Go back to RCT2, the video is frozen. 

It can be fixed by un-maximizing and remaximizing

**Comment by IntelOrca** [comment]
This looks like a bug with SDL2, the window has SDL_WINDOW_MINIMIZED set when you restore a maximized window.

**Comment by IntelOrca** [comment]
Another case:
https://www.reddit.com/r/openrct2/comments/3v9lu2/bug_black_screen_when_i_tab_out_and_come_back/

It might be best to just pull the optimisation that stopped it drawing the game when the window was minimised.

**Comment by IntelOrca** [comment]
I tried reverting #2109 but it only fixed this issue when hardware display was off. This makes me think that the same bug is causing hardware display to freeze purely due to SDL2 code.

I really can't find a solution to this for hardware display - it could be out of our hands.

**Comment by duncanspumpkin** [comment]
@IntelOrca there are two bits of code you need to change to revert #2109 . you only reverted one probably

**Comment by IntelOrca** [comment]
@duncanspumpkin That would have been nice... but I was literally debugging the code that calls SDL2 render - and it was not updating the frame.

**Comment by duncanspumpkin** [comment]
@IntelOrca could we check the window state directly instead https://msdn.microsoft.com/en-us/library/windows/desktop/ms633518(v=vs.85).aspx

**Comment by IntelOrca** [comment]
For non-hardware display. But it looks like SDL2 is doing this in its own rendering code - we can't bypass that.

**Comment by IntelOrca** [comment]
Fixed in pre-release-0.0.3.1.
