### ISSUE TITLE
Incorrect parameters in guest goals in the "new game" scenario picker window

### ISSUE THREAD

**Issue by James103** [OpenRCT2/OpenRCT2#21604]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.9-80-g2181f1b (2181f1b on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Goals that mention "to have at least X guests" have X being off by a multiple of 65536.
Furthermore, if any such goals have a due date, that date is rendered incorrectly.

### Steps to reproduce

1. Open the "Select scenario for new game" window.
2. Scroll through and hover over each scenario.
3. Notice for goals which mention "to have at least X guests", the value of X is incorrect. Furthermore, a subset of these goals that have a due date have an incorrect date.

### Attachments

Original message: https://discord.com/channels/264137540670324737/691736850980667514/1218027412726612009

**Comment by ZehMatt** [comment]
This is because of #21518, now with the data type changed we can't simply use int32_t as that will break some other localisation entries, have to update all of objective localisation entries to support the now bigger type.

**Comment by Gymnasiast** [comment]
I checked and this also affects en-GB, so this does not seem to be a localisation issue.
