### ISSUE TITLE
Sometimes unable to build a footpath

### ISSUE THREAD

**Issue by FlukiestEmperor** [OpenRCT2/OpenRCT2#2163]
In multiplayer (have not tested single player) it is sometimes not possible to build a footpath anywhere.

Sometimes it only affects the client, and sometimes it affects both the client and server.

I'm am unsure what causes this, it only happened a few times after several hours of playing.

Restarting the server or re-logging in with the client will fix the problem.

**Comment by jacon500** [comment]
I've had the same thing occasionally occur in single-player, so it does not affect only multiplayer.

**Comment by IntelOrca** [comment]
Is this a duplicate of #1619?

**Comment by FlukiestEmperor** [comment]
This is most likely a duplicate. I did not pay attention to the button not staying depressed, but it sounds like the same thing.
