### ISSUE TITLE
Peeps drawn on top of entrances and exits

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#2164]
In the last few builds I've noticed that peeps are being drawn in front of entrances when they are behind them (where do I check the version number I'm running?).

![Screenshot](http://i.imgur.com/FdOuBcK.png)

**Comment by Gymnasiast** [comment]
Introduced by https://github.com/OpenRCT2/OpenRCT2/commit/54dd6cac15be37e2bb7fa3847548443aeffb1184

**Comment by duncanspumpkin** [comment]
I know the cause and I'm trying to fix it but I've been busy recently. If its critical I have a temporary fix that reverts the paint setup code function sub_98197C to vanilla code that fixes the issue.

**Comment by Gymnasiast** [comment]
I wouldn't say it's critical, as it is just cosmetic, and doesn't interfere with the gameplay.
