### ISSUE TITLE
tool

### ISSUE THREAD

**Issue by Coasterhacker** [OpenRCT2/OpenRCT2#21661]
### Operating System

windows 10 64

### OpenRCT2 build

OpenRCT2, v0.4.9-87-g5a70fd9 (5a70fd9 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

if you open the tool and multiply then you will see a transparent window

### Steps to reproduce

if you want multiple decorations tool

### Attachments

![Unnamed park{POP16}{POP16} 2024-03-23 23-28-33](https://github.com/OpenRCT2/OpenRCT2/assets/155395270/f1a08488-aea3-4332-84e0-b22508d20143)

**Comment by Harry-Hopkinson** [comment]
This appears to have been fixed in https://github.com/OpenRCT2/OpenRCT2/pull/21649 - try updating OpenRCT2 to the latest development version.

**Comment by Gymnasiast** [comment]
It has been fixed already, indeed.
