### ISSUE TITLE
MacOSX - Not remembering fullscreen window option, always opens in windowed mode after closing.

### ISSUE THREAD

**Issue by dma1989** [OpenRCT2/OpenRCT2#21696]
### Operating System

OSX

### OpenRCT2 build

OpenRCT2, v0.4.9 (a172405 on HEAD)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

OSX app always opens in windowed mode.

Even if the 'fullscreen' or 'fullscreen (borderless window)' options are selected and then closed, it will always open in windowed mode when starting the game again.

Even going into the config.ini file when the game is closed and changing the "fullscreen_mode" property to 1 or 2 doesn't resolve the issue. It still opens in windowed mode because the game changes the property back to 0 when the game is opened.

### Steps to reproduce

**Option 1:**
- Open OpenRCT2 on Mac OSX
- Select 'Options'
- Change 'Screen mode' to either 'full screen' or 'fullscreen (borderless window)'
- Close the game (either through the 'Exit' icon in the bottom right of the screen, or by pressing Cmd + Q)
- Reopen the game
- It will have reopened in windowed mode again

**Option 2:**
- Ensure OpenRCT2 is closed
- Open Finder and navigate to USERFOLDER > Library > Application Support > OpenRCT2
- Open the config.ini file in TextEdit
- The 'fullscreen_mode' property will be set to zero. (The text will appear as _fullscreen_mode = 0_)
- Change this to _fullscreen_mode = 1_ for 'full screen' or _fullscreen_mode = 2_ for 'fullscreen (borderless window)'
- Save config.ini and close TextEdit
- Open OpenRCT2
- It will have reopened in windowed mode again

**Comment by ayvaak** [comment]
Working on this!

**Comment by ayvaak** [comment]
It looks like there's a bit of code in UIContext.cpp (starting on line 765) that's hard-coding Mac to open in windowed mode. Issue #4022 was a problem with the cursor, but removing the code saves the fullscreen preference and doesn't seem to cause any cursor bugs to happen anymore. MichaelJBerk also [commented on Issue #4022](https://github.com/OpenRCT2/OpenRCT2/issues/4022#issuecomment-1797370386) that the workaround doesn't seem to be necessary in November 2023. 

Should I go ahead and remove this bit of code, and make a commit? I'll also ask about this in the Discord. 

<img width="774" alt="Screen Shot 2024-04-20 at 2 40 49 PM" src="https://github.com/OpenRCT2/OpenRCT2/assets/60326357/36ffa5a1-eba9-49e2-98a7-6f93201d8780">
