### ISSUE TITLE
Large Scenery - can't remove this... Unknown Type

### ISSUE THREAD

**Issue by Manticore-007** [OpenRCT2/OpenRCT2#21695]
### Operating System

Windows 11 64 bit

### OpenRCT2 build

v0.4.9-d8ba574 develop

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

When you try to remove a large scenery object, you will get the error "can't remove this... Unknown Type". 

### Steps to reproduce

1. place large scenery object
2. try to delete/remove object
3. error shows

### Attachments

![image](https://github.com/OpenRCT2/OpenRCT2/assets/71702374/06c0e599-4977-4e9b-adf5-edaef15f0fa5)

**Comment by Basssiiie** [comment]
Probably related, large scenery ghost elements are not removed while dragging around a track design with large scenery elements.

![image](https://github.com/OpenRCT2/OpenRCT2/assets/20048660/dafc5cf0-5d0a-48c7-89a2-b9fbfebfdb16)
![image](https://github.com/OpenRCT2/OpenRCT2/assets/20048660/238b332b-391c-43bc-86cf-8f7c86bb5c76)

**Comment by Gymnasiast** [comment]
Most likely the result of a mistake in https://github.com/OpenRCT2/OpenRCT2/pull/21581.
Release blocker.
