### ISSUE TITLE
Clear Scenery

### ISSUE THREAD

**Issue by Coasterhacker** [OpenRCT2/OpenRCT2#21706]
### Operating System

windows 10 64

### OpenRCT2 build

OpenRCT2, v0.4.9-185-g27e43b3 (27e43b3 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

If you accidentally put it down, you can't take it away. it used to be possible.

### Steps to reproduce

you can't do anything to take it away. you're stuck with that building.

### Attachments

![Six Flags Magic Mountain 2024-04-01 22-16-59](https://github.com/OpenRCT2/OpenRCT2/assets/155395270/14f7ae96-f526-429b-aad2-72331a86e884)

**Comment by duncanspumpkin** [comment]
Update, this issue is now fixed.
