### ISSUE TITLE
Goals for guest count in scenarios is in the millions

### ISSUE THREAD

**Issue by mindlessmarbles** [OpenRCT2/OpenRCT2#21719]
### Operating System

Windows 11, 64bit 

### OpenRCT2 build

OpenRCT2 v0.4.10

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

This is a development issue

### Describe the issue

Every time I load a scenario, the goal number of guests is impossible. Ex: Loaded Evergreen Gardens, the objective is the following:

“To have at least 2,032,616 guests in your park at the end of March, Year 1, with a rating of at least 600.”

### Steps to reproduce

1. Launch new scenario
2. Objective should have inflated number

### Attachments

![IMG_9179](https://github.com/OpenRCT2/OpenRCT2/assets/165967487/8f59c2c2-571e-4707-a490-dd02e446738d)

**Comment by Gymnasiast** [comment]
Two possibilities:
1. your scenario cache is outdated
2. your updated the executable, but not the language files.

You can trigger a scenario cache rebuild by switching language (e.g. from US English to UK English) and restarting the game. The second possibility involves reinstalling OpenRCT2.
