### ISSUE TITLE
Rides previously set to the ride type "Unknown Ride (38)" now display as Multi-dimension coaster track

### ISSUE THREAD

**Issue by Xtreme97-RCT** [OpenRCT2/OpenRCT2#21731]
### Operating System

Windows 11 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.10-13-ga38039f (a38039f on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error, This is a development issue

### Describe the issue

Issue is currently present in recent develop builds of 0.4.10 but not present in release.

Using the park Otter's Magic Kingdom (https://www.nedesigns.com/park/5910/otters-magic-kingdom/) as an example:
![image](https://github.com/OpenRCT2/OpenRCT2/assets/64152940/cc5acac0-99a8-49d2-8f16-33b506f9b51e)

Additionally, there are now also two instances of Multi-dimension Coaster in the ride type list:
![image](https://github.com/OpenRCT2/OpenRCT2/assets/64152940/4d23f822-4a33-4479-8189-4d99f3b96727)

### Steps to reproduce

1. Open a map that has previously used the ride type "Unknown Ride (38)" to make a ride invisible.
2. Ride now displays as multi-dimension coaster track rather than invisible, which breaks any park that previously used this ride type to make a ride invisible.

**Comment by Gymnasiast** [comment]
Could you test this build: https://github.com/OpenRCT2/OpenRCT2/actions/runs/8583762332/artifacts/1391095720
to check if that works for you? If possible, can you also test a few other instances that use Unknown Ride (38)?

**Comment by Manticore-007** [comment]
> Could you test this build: https://github.com/OpenRCT2/OpenRCT2/actions/runs/8583762332/artifacts/1391095720 to check if that works for you? If possible, can you also test a few other instances that use Unknown Ride (38)?

The park mentioned in #21744 looks okay now.
Another park where I know the issue occured, is also okay with the build above.

**Comment by Gymnasiast** [comment]
@Manticore-007 Nice, could you also leave that comment on the PR? That helps getting it merged quickly.

**Comment by Xtreme97-RCT** [comment]
> Could you test this build: https://github.com/OpenRCT2/OpenRCT2/actions/runs/8583762332/artifacts/1391095720 to check if that works for you? If possible, can you also test a few other instances that use Unknown Ride (38)?

Yeah, this build has fixed the issue with the park I was testing. Have also tested with another map that I know had the issue (Gladsheim from H2H9: https://www.nedesigns.com/park/5338/gladsheim/) and that also works as expected now with the track being invisible.
