### ISSUE TITLE
Flying, lay down, and multi dimension coasters show up twice in arbitrary ride type drop down menu

### ISSUE THREAD

**Issue by astraylife1** [OpenRCT2/OpenRCT2#21746]
### Operating System

MacOS

### OpenRCT2 build

OpenRCT2, v0.4.10 (a38039f on develop)

### Base game

RollerCoaster Tycoon 2

### Describe the issue

When arbitrary ride type changes cheat is turned on, the drop down list in a ride window shows Lay Down Coaster, Flying Coaster, and Multi-Dimension Coaster twice

### Steps to reproduce

Turn arbitrary ride type cheat on
Open ride window and select drop down

**Comment by Gymnasiast** [comment]
You’re trying my patience now. Please follow the directions we give, and look if a problem has been reported first. Ask if needed.

https://github.com/OpenRCT2/OpenRCT2/pull/21737#issuecomment-2041556033
