### ISSUE TITLE
"Error loading objects for park" for RCT1 scenarios

### ISSUE THREAD

**Issue by RundesBalli** [OpenRCT2/OpenRCT2#21742]
### Operating System

LinuxMint 5.15.0-101-generic #111-Ubuntu SMP Tue Mar 5 20:16:58 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux / bookworm/sid

### OpenRCT2 build

OpenRCT2, v0.4.10 (, DEBUG); Linux (x86-64); Network version: 0.4.10-0; Plugin API version: 84; Current park file version: 33; Minimum park file version: 33; Breakpad support disabled

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

The same issue as described in https://github.com/OpenRCT2/OpenRCT2/issues/18461 and https://github.com/OpenRCT2/OpenRCT2/issues/19432 and https://github.com/OpenRCT2/OpenRCT2/issues/20805 occurs again.

I've got the nightly version from the PPA.

When I click on "download all", it seems that it downloads everything, but it has no effect.

Forrest Frontiers:
![grafik](https://github.com/OpenRCT2/OpenRCT2/assets/46271553/84474999-4f89-4a73-b5c8-13aa32d5b77f)

Haunted Harbour:
![grafik](https://github.com/OpenRCT2/OpenRCT2/assets/46271553/d06b3b49-ebaa-4762-a3b9-880f9025748c)

Razor Rocks:
![grafik](https://github.com/OpenRCT2/OpenRCT2/assets/46271553/98de67f6-c3bc-4962-8458-09606d4bcf63)

Every scenario from "RollerCoaster Tycoon 1", "Loopy Landscapes" and "Added attractions" is affected by this.

### Steps to reproduce

See screenshots above.

### Attachments

See screenshots above.

**Comment by Estebastien** [comment]
Same issue, with apparently same missing objects. (Ubuntu 22, OpenRCT2, v0.4.10 (, DEBUG); Linux (x86-64);)

**Comment by Gymnasiast** [comment]
I pushed the updated objects to the appropriate repository. The next build (due in ~3 hours) should contain them.

**Comment by RundesBalli** [comment]
In addition: maybe you can show an error message, when the files can not be downloaded. Currently there is no error message, unfortunaly.

**Comment by harvito** [comment]
the only one for me is rct1.ride.stand_up_trains, which I noticed was in the changelog
![SS 2024-04-28 16-59-44](https://github.com/OpenRCT2/OpenRCT2/assets/14914822/377df963-5784-46ae-ae8b-61957a39895f)
Download all didn't change anything

**Comment by Gymnasiast** [comment]
@RundesBalli @Estebastien Did last night’s update fix the problem for you?

**Comment by Gymnasiast** [comment]
@Estebastien Are you on `nightly` or `release`/`master`? I only fixed the former, the latter should be fixed with the v0.4.11 release.

**Comment by RundesBalli** [comment]
> @RundesBalli @Estebastien Did last night’s update fix the problem for you?

I've just updated (nightly release) and tried. Works perfectly fine. Thank you!

I will let the issue open, until @Estebastien's issue has been resolved.

**Comment by Estebastien** [comment]
Working also after another update! (Somehow the previous update was too early?) Thank you a lot !

**Comment by harvito** [comment]
Mine's all good with 4.0.11, thanks!
