### ISSUE TITLE
custom log flume vehicles for steep slopes make coaster sounds

### ISSUE THREAD

**Issue by cheweytoo** [OpenRCT2/OpenRCT2#21761]
### Operating System

Ubuntu Linux 22.04.4

### OpenRCT2 build

develop 828eb0e, Linux AppImage

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Might actually be an issue with the custom object and not OpenRCT2 itself. But I've seen those custom log flume logs recommended by the devs, so maybe it's still something to be looked into.

It took me a while to track down the source of the weird rumbling in one of my big parks: Turns out the custom log flume logs for steep slopes make coaster train sounds!

See attached park: "Loud Flume" using the custom logs is loud and makes the wrong sounds compared to "Quiet Flume", which uses the vanilla RCT logs.

I've also attached the custom object by Realsteel89. I can't seem to be able to find a download source, but the file's timestamp on my drive is 2023-05-04, shortly after the steep log flume track became available.

### Steps to reproduce

- build log flume using logs from realsteel.ride.log_flume.parkobj
- ride makes coaster sounds while running

### Attachments

[log_flume_sound.park.zip](https://github.com/OpenRCT2/OpenRCT2/files/14920614/log_flume_sound.park.zip)
[realsteel.ride.log_flume.parkobj.zip](https://github.com/OpenRCT2/OpenRCT2/files/14920615/realsteel.ride.log_flume.parkobj.zip)

**Comment by Gymnasiast** [comment]
This is a bug with the object. It is missing several properties it should have. And it’s still a _custom_ object, even if Karst might have recommended it.

**Comment by Gymnasiast** [comment]
Our criteria for official inclusion is that it matches Simon Foster’s drawing style. And in this particular case, we’d want something that looks exactly like the vanilla boats. This is an early object by Realsteel, I have seen his drawing style improve considerably, so maybe this can be achieved.

The metadata fixes for the object are rather more straightforward. Realsteel needs to compare the properties of his object with those of the official ones and add/modify as needed. A diff tool will greatly help here. (If needed, I can lend him a hand.)

**Comment by Realsteel89** [comment]
yes if the car goes official i will change it its an false entry in the ride json
