### ISSUE TITLE
Not able to build RCT1 prebuilds for classic stand-up coaster

### ISSUE THREAD

**Issue by TheAceOfInsanity** [OpenRCT2/OpenRCT2#21766]
### Operating System

Windows 10 x86-64

### OpenRCT2 build

OpenRCT2, v0.4.10(e55d761)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

I was building with the classic stand-up coaster and noticed that it didn't have any prebuilt designs. The RCT1 stand-up coaster prebuilds should be compatible with the classic stand-up coaster but they are not. I was also going to write about a problem I had with building the RCT1 stand-up coaster designs for the RCT2 stand-up coaster where the prebuilds were there but no preview picture was there and you would get an error message if you tried to build them, but I just tested it again before writing this and they work now for some reason.

### Steps to reproduce

1. Click on Build new ride/attraction button.  2. Click on the rollercoaster section.  3. Click on the Classic Stand-up coaster.  4. See if any prebuilds show up and if they don't then the bug is still there :)

**Comment by Gymnasiast** [comment]
It’s likely this is just a matter of rebuilding the tracks cache. So let’s try that first.

In the title screen, click the red toolbox -> Open custom content folder -> delete tracks.idx. Then restart OpenRCT2.

**Comment by Gymnasiast** [comment]
I take it that solved your problem?

**Comment by TheAceOfInsanity** [comment]
Yes sir that worked thanks. I forgot to comment before closing the issue
because it worked but didn't feel like reopening it to reply and then close
again
