### ISSUE TITLE
Unable to download missing objects from api.openrct2.io when building from source

### ISSUE THREAD

**Issue by Doggermelon** [OpenRCT2/OpenRCT2#21775]
### Operating System

Artix Linux x86_64

### OpenRCT2 build

v0.4.10-21 (4e7d5d987 on develop, DEBUG)

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs, This is a development issue

### Describe the issue

Following the manual build instructions for [Running [OpenRCT] from the build directory](https://github.com/OpenRCT2/OpenRCT2/wiki/Building-OpenRCT2-on-Linux#running-it-from-the-build-directory) doesn't result in a complete/correct data directory. OpenRCT2 tries to remedy this at runtime by downloading the missing files from the internet, but the files don't exist at the location it's looking. I considered adding this issue to the https://github.com/OpenRCT2/objects repo as it seems to be responsible for populating the `data/object/official` folder (with a missing `music` folder inside of it being the root cause), but I decided to create this here as the code specifically tries to use the referenced URL. 

See https://github.com/OpenRCT2/OpenRCT2/blob/246f1f30b92f8624900212f5f9b237e71bebf6f6/src/openrct2-ui/windows/ObjectLoadError.cpp#L37
and https://github.com/OpenRCT2/OpenRCT2/blob/246f1f30b92f8624900212f5f9b237e71bebf6f6/src/openrct2-ui/windows/ObjectLoadError.cpp#L214-L217

This issue is similar to #21110 and #20805.

### Workaround
A simple workaround is to download a full release of OpenRCT2 and steal the data directory from there.

#### P.S.
 I can make another issue, but the optional step of adding title sequences uses the wrong directory; it says to put https://github.com/OpenRCT2/title-sequences/releases into `$build/data/title` when it should be `$build/data/sequence` instead.

### Steps to reproduce

1. Install the build requirements.
2. Clone the repo.
3. Make the `build` directory and change directories into it.
4. Invoke `cmake ..`
5. Invoke `make`.
6. Copy `data` from the root into `build`.
7. Invoke `make g2`.
8. Copy `g2.dat` into `data`.
9. Download and extract the latest (1.4.3) of https://github.com/OpenRCT2/objects/releases into `data/object`.
10. Launch OpenRCT2.
11. Point it towards an RCT or RCT2 install if you have not done so already.
12. Try to start a scenario.
13. Observe the "Error loading objects for park" dialog noting missing objects:
> openrct2.music.galaxy
> openrct2.music.acid
> openrct2.music.dodgems
> openrct2.music.blizzard
> openrct2.music.extraterrestrial
> openrct2.music.fairground2
> openrct2.music.ragtime2
> openrct2.music.prehistoric
> openrct2.music.mystic
> openrct2.music.rock4
14. Click the "Download all" button.
15. Observe while OpenRCT2 tries to download the files and logs to the console:
>   openrct2.music.galaxy not found
>   openrct2.music.acid not found
>   openrct2.music.dodgems not found
>   openrct2.music.blizzard not found
>   openrct2.music.extraterrestrial not found
>   openrct2.music.fairground2 not found
>   openrct2.music.ragtime2 not found
>   openrct2.music.prehistoric not found
>   openrct2.music.mystic not found
>   openrct2.music.rock4 not found
16. Observe the problem persists when trying to start a scenario again.

**Comment by Gymnasiast** [comment]
The objects missing from the install might be bug, the instructions for that might be faulty, but the game not downloading them from the object server is very much correct. It would put the objects in the user folder, where they will conflict if the game is properly installed later on.
