### ISSUE TITLE
Use standard apostrophes and quotations in source code

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#21780]
Is there a reason why these UTF-8 characters are used in source? They do not play nice with visual studios and/or git bash. It's a constant headache stamping out these unwanted hunks. This is specifically regarding .cpp and .h files, not localization files.

![image](https://github.com/OpenRCT2/OpenRCT2/assets/3454156/78e29b55-00f5-472c-ab4b-ccb3c478d0ae)

Is there a standard for these characters in source? Can I change them to standard when I encounter them? Should I make a PR to replace all of them with standard?

**Comment by Gymnasiast** [comment]
It’s 2024, anything that doesn’t support UTF-8 can go do in a fire for all I care.

**Comment by spacek531** [comment]
Someone on stackoverflow suggested this settings change in VS. 
![image](https://github.com/OpenRCT2/OpenRCT2/assets/3454156/c5e1e26b-cb14-48a7-bafe-327fb57da3b7)

It's hard to disprove a negative but I'll know when it doesn't work.

**Comment by Gymnasiast** [comment]
Assuming it has been solved, then.
