### ISSUE TITLE
Park from 2022 does not load in latest build

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#21809]
### Operating System

Windows 11 Pro Insider Preview Canary

### OpenRCT2 build

OpenRCT2, v0.4.10-31-ga6e1124 (a6e1124 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

[unknownissue.zip](https://github.com/OpenRCT2/OpenRCT2/files/14973002/unknownissue.zip)

### Steps to reproduce

try to open the park, it does not open

**Comment by janisozaur** [comment]
Is it solved?

**Comment by James103** [comment]
> Is it solved?

No; the park file in the ZIP attached to the original post is 0 bytes. Can you please re-upload the park if possible?

**Comment by 733737** [comment]
the park file I found is zero bytes, that is why it does not load  hence this issue is closed
