### ISSUE TITLE
sv6 autosaves are retained indefinitely

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#21815]
### Operating System

Windows 11 Pro Insider Preview Canary

### OpenRCT2 build

OpenRCT2, v0.4.10-31-ga6e1124 (a6e1124 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

sv6 autosaves are retained indefinitely in the autosave folder

### Steps to reproduce

if you have sv6 autosaves they will simply remain in the autosave folder
![autosaveconundrum](https://github.com/OpenRCT2/OpenRCT2/assets/94884086/b9a5f93a-0e70-4d84-b16e-c9cbc74c2e0c)

**Comment by duncanspumpkin** [comment]
That is expected behaviour.
