### ISSUE TITLE
Scenario editor shows {POP16}{POP16} for some reason

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#21829]
### Operating System

Windows 11 Pro Insider Preview Canary

### OpenRCT2 build

OpenRCT2, v0.4.10-36-gb64ec76 (b64ec76 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Scenario editor shows {POP16}{POP16}

### Steps to reproduce

create a new scenario in the scenario editor
![Unnamed park{POP16}{POP16} 2024-04-16 22-28-01](https://github.com/OpenRCT2/OpenRCT2/assets/94884086/6cdda0cd-89cd-46e5-9826-e6e70cfb83b0)

**Comment by TheClaudeQC** [comment]
![image](https://github.com/OpenRCT2/OpenRCT2/assets/83843734/38294401-8b06-4c16-b9fc-2a12b5bb7b44)
Hum, guess this bug returned in recent updates

**Comment by Gymnasiast** [comment]
@TheClaudeQC It isn’t, it’s just that French has not been updated yet.
