### ISSUE TITLE
Feature request: Allow using the executable's directory to store user files for portable installation

### ISSUE THREAD

**Issue by osconnoisseur** [OpenRCT2/OpenRCT2#2182]
The current behavior is that platform_get_user_directory() returns a subdirectory of the user's home, and OpenRCT2 uses this path to store all of the user's files and saved games. This is usually "C:\Users\<username>\OpenRCT2" or "C:\Documents and Settings\<username>\OpenRCT2" on Windows and "/home/<username/.config/OpenRCT2" on Linux. I think it would be a nice idea to first check to see if config.ini is in the executable's directory, and if it is, set a flag and have platform_get_user_directory() return the executable's directory so that all of the user's files are stored locally. If it is not, just have platform_get_user_directory() do its current behavior and return the subdirectory of the user's home.

By doing this, a user can simply place config.ini in the same directory of OpenRCT.exe to make it portable. Normal installations using the installer won't have config.ini in the executable's directory, and so OpenRCT would work just like it does currently.

**Comment by osconnoisseur** [comment]
I've added a few lines of code and implemented this for myself if anyone is interested.

**Comment by Gymnasiast** [comment]
User settings, like config.ini, are not supposed to be in the directory of OpenRCT2 itself. RCT2 does this and it created all sorts of problems with permissions. It is also incompatible with multi-user, and it created additional complexity.

**Comment by janisozaur** [comment]
Many programs do accept a path to config file/dir, I vote +1 on this, although not in the way it is mentioned.

A `--config=path/to/config` seems like a good option to me.

See also #1188

**Comment by IntelOrca** [comment]
@Gymnasiast I think its more in the situation of having it on a portable flash drive.

**Comment by Gymnasiast** [comment]
Hm, well, I'm not going to object then. At least there is a proper use case for this.

**Comment by osconnoisseur** [comment]
Yes, this is strictly meant to be for installation on a flash drive or if the user wants everything in some local directory that he has full read write permissions for. The typical user 
wouldn't do this. Specifying the directory on the command line would be another possibility, though I'd have to launch the program from a script to do that.

**Comment by IntelOrca** [comment]
I think both the order of precedence should be:
* --config <path>
* ```$openrct2_home/config.ini``` **OR** ```%OPENRCT2_HOME%\config.ini```
* ```config.ini``` present in same directory as openrct2 binary (not sure how you get this on unix, I don't think it should check working directory)
* ```$home/.config/.OpenRCT2/config.ini``` **OR** ```%USERPROFILE%\Documents\OpenRCT2\config.ini```
* ```$home/.OpenRCT2/config.ini``` **OR** ```%APPDATA%\OpenRCT2\config.ini```

**Comment by osconnoisseur** [comment]
I don't really like the idea of using an environment variable for the user data. Having both the config file and the user data directory as command line parameters would be more consistent. The fourth and fifth ones are quite unnecessary as OpenRCT2 automatically creates the directory if it doesn't exist. It should really only need to look in one directory. Just putting my two cents in.

**Comment by janisozaur** [comment]
I think that @IntelOrca meant to indicate where the config files would exist rather than relying on env variables. There are OS-specific functions and ways which provide paths for storing such configs, e.g. [SHGetKnownFolderPath](https://msdn.microsoft.com/en-us/library/windows/desktop/bb762188%28v=vs.85%29.aspx).

Personally, I'd like `~/.config/OpenRCT2` on Linux and `--config-path=XXX` for whatever other option you may have. I don't have much experience with Windows these days, but I think the same would be valid on that platform.

**Comment by IntelOrca** [comment]
I was suggesting an order of all potential places, the user can decide which one they want to use.

**Comment by devnoname120** [comment]
@IntelOrca I think that `config.ini` should be second in your list, otherwise if OpenRct2 is installed on the computer, and the user wants to run it from his USB key only, it will not behave as expected.

**Comment by IntelOrca** [comment]
Hmm, well its unlikely for the user to use an environment variable for the directory - so if they do - i don't know if there intention is to have the override all others.

**Comment by devnoname120** [comment]
OK. Do we even have an use case for this? I feel like we are about to introduce many complicated rules thay will not be used.

**Comment by IntelOrca** [comment]
OpenRCT2 servers might want to use environment variables in their scripts.

**Comment by pizza2004** [comment]
I would personally just vote that it checks the current directory for all necessary files before it goes to check the other places.  Portable installation of a game like this is very appealing.

**Comment by RobertWHurst** [comment]
As a software engineer that works on server systems, the spec @IntelOrca described makes the most sense to me.

**Comment by osconnoisseur** [comment]
When we say config path, do we mean the path returned by platform_get_user_directory(), which also holds the user's files (landscape, save, scores.dat, tracks.idx, etc.), or a totally different directory for holding just the config.ini file? I don't really see much use for putting it in a different directory. My original idea was to use the presence of config.ini in the program's directory as a flag that tells the program to store data in its own directory. If it's there, use the program's directory. If it's not there, use the default directory. It is very much possible to run Unix/Linux programs portably from a flash drive by statically linking them, but running stuff from removable media isn't nearly as common as it is in the Windows world.

Ultimately, the decision depends on how much control users will want over what directory their game files are located in. Personally, I'm just fine with only being able to use the C:\Users\<Username>\Documents\OpenRCT2 directory that is used now or the executable's directory. What does everyone else think? Are there any use cases that require specifying other directories via command line or environment variable?

**Comment by pizza2004** [comment]
I would assume the reason that running programs portably on Linux is far less common because your own Linux machine is the only machine you will most likely run into.  Most users don't care which directory the files are in, and the ones that do almost certainly know how to make static links or aliases or shortcuts to just make the program jump to that location without the program needing to know about it.

I vote what osconnoisseur said.  If it finds the config files locally it runs portably, searching for all necessary RCT2 files in an RCT2 folder contained within the OpenRCT2 folder, and storing all appropriate files in the appropriately named folders within OpenRCT2.  Other than this, I don't see the need to change anything in particular.  Alternatively, we could offer a separate portable download that does this, for the people that actually care, in order to keep implementation simple.

**Comment by Gymnasiast** [comment]
@pizza2004 : Offering two downloads does _not_ make implementation simpler. Quite the contrary.

**Comment by IntelOrca** [comment]
I don't think we need to allow for the config file to be in a different place to the OpenRCT2 home directory (as it shall now be called). But I can see people wanting to separate their home directory from the OpenRCT2 install directory. Take this for example:
```
flash_drive/
    OpenRCT2/
        data/
            g1.dat
            g2.dat
            css1.dat
            etc.
        objdata/
            balln.dat
        scenarios/
            crazy castle.sc6
        tracks/
            woodchip.td6
        openrct2.exe
        sdl2.dll
    OpenRCT2_Home/
        landscapes/
        objdata/
            myride.dat
            myroof.dat
        save/
        scenarios/
            myscenario.sc6
        screenshots/
        tracks/
            mytrack.td6
        config.ini
```

Here its obvious what is the vanilla base data and what is the user data. Its also easy to update OpenRCT2 and safer as you are unlikely to overwrite your own stuff. If the config.ini is always in the home directory - that means its better for config.ini to not be in the OpenRCT2 directory.

**Comment by pizza2004** [comment]
@Gymnasiast Okay fine, I just meant that we could just have some #ifdef functions that trigger whether it's portable or regular, and then the code wouldn't have to try to find a bunch of different things when it's on the portable version.

**Comment by IntelOrca** [comment]
@pizza2004 We know what you meant. But it would not be a good idea to have to versions of the game. Each build server would have to make two versions each time and there would be a higher amount of maintenance required in terms of knowing what version people were running for bug reports and what version people need to specifically have for a particular task. Its just much more convenient if the same executable works for both use cases and its not going to be particularly expensive to check a few paths.

**Comment by pizza2004** [comment]
@IntelOrca No I get that, I'm just saying it's a rather common practice to offer a separate portable version of the program, and was suggesting maybe we should do that as well.  I understand that it isn't actually easier from the standpoint of builds and maintenance and such.

**Comment by osconnoisseur** [comment]
I agree with IntelOrca in that releasing a separate version of the program for portable flash drives is not a good idea. 

@IntelOrca That seems reasonable. What if we just use a single command-line parameter to specify the OpenRCT2 home directory? Shortcut links can pass command-line parameters to programs, so one could use that instead of a batch file. For the situation above, the program would simply be launched with `OpenRCT2\openrct2.exe --home=OpenRCT2_home`. I think this would require minimal added code, since all it needs to do is specify what directory platform_get_user_directory() should return.

Inheriting files from other directories can confuse the user. He might see a file in the dialog and wonder where it could possibly be if not on his flash drive. It's quite easy to browse to C:\Users\Public or wherever you want, anyway.

**Comment by IntelOrca** [comment]
For unix and linux users here... what is preferred?
```--home=/path/to/home``` or
```--home /path/to/home``` ?

**Comment by osconnoisseur** [comment]
`--home=/path/to/home` is what's normally done for Linux programs, especially GNU software.

**Comment by janisozaur** [comment]
I'd say the latter, `--home /path/to/home` but we usually support both, although `--home` (name of the option) looks a bit strange to me. I'd rather expect `--config-home`, `--config-path` or some such…

**Comment by janisozaur** [comment]
http://linux.die.net/man/3/getopt_long
```
A long option may take a parameter, of the form --arg=param or --arg param.
```

**Comment by IntelOrca** [comment]
@janisozaur as pointed out above, its not just config, its the user data

**Comment by osconnoisseur** [comment]
Well, for a lot of options, there is a long format and a short format. For example, `ls --width=20` is equivalent to `ls -w 20`. The long format uses two dashes and an equal sign, whereas the short format uses one dash and a space.

**Comment by janisozaur** [comment]
I'm fine with anything, as long as it's consistent and clearly communicated. There's only one thing which you should not do: provide long options with single dash. But it's already done this way, so just keep it up as is.

@IntelOrca in that case `--data`, `--data-path` would be something I'd expect. It's just my personal opinion that `--home` looks strange, but I'm fine with it really.

**Comment by HaasJona** [comment]
--home is confusing because home means something specific and different on Linux. I agree with --data or something like that. 
Am 03.11.2015 8:26 nachm. schrieb janisozaur <notifications@github.com>:I'm fine with anything, as long as it's consistent and clearly communicated. There's only one thing which you should not do: provide long options with single dash. But it's already done this way, so just keep it up as is.

@IntelOrca in that case --data, --data-path would be something I'd expect. It's just my personal opinion that --home looks strange, but I'm fine with it really.

**Comment by IntelOrca** [comment]
```--user-data```?

**Comment by janisozaur** [comment]
perfect
