### ISSUE TITLE
Inconsistent title screen scene position

### ISSUE THREAD

**Issue by e-foley** [OpenRCT2/OpenRCT2#2187]
Tested in 1396.

When I boot up, my screen looks like this:
![startup](https://cloud.githubusercontent.com/assets/6338134/10901415/b55d25d0-81a2-11e5-89c2-9bda6d69e883.png)

But when I start a scenario and exit to title screen, the screen looks like this:
![return_to_title](https://cloud.githubusercontent.com/assets/6338134/10901417/c852328e-81a2-11e5-9993-0eb72a52c182.png)

The other scenes in the intro demo don't seem to be affected.  I run 1920 x 1080 resolution, should that be relevant.

**Comment by IntelOrca** [comment]
OK after some investigation, the issue is with fullscreen resolution on startup.

When the game starts, it must have a smaller window size which it centres the title sequence to before going fullscreen which changes the window size and therefore results in the title sequence offset.
