### ISSUE TITLE
Opening "Object Selection" closes all other windows

### ISSUE THREAD

**Issue by luotiansha** [OpenRCT2/OpenRCT2#21890]
### Operating System

macOS 14.2

### OpenRCT2 build

OpenRCT2, v0.4.10 (e55d761 on HEAD), macOS (AArch64)

### Base game

RollerCoaster Tycoon 2

### Describe the issue

When opening the "Object Selection" window, all other windows are forced to be closed. No other cheat windows has this issue.

### Steps to reproduce

see video

### Attachments

https://github.com/OpenRCT2/OpenRCT2/assets/77926812/6c00011c-d6ec-4462-84dc-c65e297a23eb

**Comment by Gymnasiast** [comment]
This is not a bug, but deliberate behaviour. The object selection affects a lot of other things, so it’s safer to just close those window to avoid trouble.
