### ISSUE TITLE
Modifying path corners via tile inspector does weird things

### ISSUE THREAD

**Issue by cheweytoo** [OpenRCT2/OpenRCT2#21904]
### Operating System

Ubuntu Linux 22.04.4

### OpenRCT2 build

af46ff5 develop, Linux AppImage

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Using the tile inspector's "connected edges" checkboxes to modify a path's corners does weird and unexpected things to path corners _**not**_ being edited.

In some cases, checking a corner makes other filled corners disappear in the rendering (depite being set as filled), and
some combinations of corners and edges are never rendered as expected:

https://github.com/OpenRCT2/OpenRCT2/assets/29800630/cca6f61e-cfa5-4047-89d9-c3b18dd0f15a

### Steps to reproduce

- Build a path tile
- Use tile inspector's "connected edges" on that tile to set combinations of edges and corners
- Some combinations will turn out to be impossible to get rendered as set

**Comment by Gymnasiast** [comment]
We discussed this in the team and concluded that it is not something that we want to restrict. The Tile Inspector is a hacking tool, changing it might break legitimate hacks, and it’s not like something really breaks because of it.
