### ISSUE TITLE
Daily build on the website can't be extracted properly on linux

### ISSUE THREAD

**Issue by heilla** [OpenRCT2/OpenRCT2#2191]
When extracting the build from the website and opening it with the default zip program on linux mint, the structure isn't taken over properly. The GIT page had to be used to get the propper zip.

On the left is the build from https://openrct.net/download on the right is the GIT zip.

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.1
DISTRIB_CODENAME=rebecca
DISTRIB_DESCRIPTION="Linux Mint 17.1 Rebecca"
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.3 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"

![schermafdruk van 2015-11-03 19 38 37](https://cloud.githubusercontent.com/assets/2901706/10917749/a2f932ba-8262-11e5-9f40-099c00dc9b15.png)

**Comment by IntelOrca** [comment]
openrct.net builds are managed by @runelaenen and @PFCKrutonium and are not directly maintained via this repo. I suggest contacting them about this issue.

**Comment by heilla** [comment]
Thank you for the info. Issue will be closed.

**Comment by janisozaur** [comment]
In case you don't know, we also have native linux builds available. There are instructions how to build on wiki.

You can also pull a build from travis itself, see my `transfer` branch.

**Comment by PFCKrutonium** [comment]
Hmmm... I will look at a way to make this work properly.
