### ISSUE TITLE
Title screens plays during gameplay?

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#21921]
### Operating System

Windows 11, 64-bits

### OpenRCT2 build

OpenRCT2, v0.4.10-107-g9266a6f (9266a6f on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

So, I was going into the ride editor when suddently, the park rotated without any reasons at first, but then, the SFMM appeared on top of the map. And might have just deleted my random giga coaster.

### Steps to reproduce

1. Open OpenRCT2
2. Go on ride editor
3. Build a ride or 2
4. everything will go crazy

### Attachments

I can't attach, as 10MB is way too small for showing the bug in action

**Comment by TheClaudeQC** [comment]
Adding to the bug report, if you choose a park to play, the bug isn't there

**Comment by TheClaudeQC** [comment]
![Six Flags Magic Mountain 2024-04-28 09-33-52](https://github.com/OpenRCT2/OpenRCT2/assets/83843734/50f6aafb-23f4-4ebd-90e0-7ba4b2ce1f0a)
![Six Flags Magic Mountain 2024-04-28 09-34-02](https://github.com/OpenRCT2/OpenRCT2/assets/83843734/57b3d22e-496b-4767-a1b5-5a05f07ef840)

Here's the view after a minute or so

**Comment by cheweytoo** [comment]
I've reproduced this in 9266a6f.

No need to do anything here: I just start Track Designer and wait 15-30(?) seconds. The times I have to wait differ quite a bit. Does it maybe coincide with the title animation's view changes? Is that still running in the background?

It also does interesting things to the menu bar.

In this video, I don't do _anything_ after starting the track designer. Title screen stuff appears at about second 24:
https://github.com/OpenRCT2/OpenRCT2/assets/29800630/2438e095-2a51-4ebf-9a4d-9da76c263bec

**Comment by cheweytoo** [comment]
I just realised that the entries in the ride selector's "Ride / Vehicle" column in my video are extremely fishy as well.

**Comment by Moe-Kitsune** [comment]
Can confirm that this also affects the scenario editor

**Comment by AaronVanGeffen** [comment]
A fix for this issue has been proposed in #21943. If you like, you can try a build from [this page](https://github.com/OpenRCT2/OpenRCT2/actions/runs/8902169404?pr=21943#artifacts).

**Comment by cheweytoo** [comment]
> A fix for this issue has been proposed in #21943.

I can confirm that this fixes the initial issue for me.

So I guess the "Random custom scenery objects show up as ride vehicles in Object Selector" thing is a separate issue? That still happens here.

**Comment by Gymnasiast** [comment]
> So I guess the "Random custom scenery objects show up as ride vehicles in Object Selector" thing is a separate issue? That still happens here.

Quite sure it is, yes. Please create a separate issue for that and we’ll look into it.
