### ISSUE TITLE
Handymen is not inclusive Handyperson would be better

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#21935]
### Operating System

Windows 11 Pro

### OpenRCT2 build

0.4.10

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

The bug also exists in the original game (RCT2/RCTC)

### Describe the issue

It would be a more modern and inclusive term to call handymen handyperson(s) or change name to janitors

### Steps to reproduce

play openrct2

**Comment by Gymnasiast** [comment]
This belongs in Discussions. It isn’t a bug.
