### ISSUE TITLE
Track Designer interferes with background from main menu

### ISSUE THREAD

**Issue by DavidBlain2626** [OpenRCT2/OpenRCT2#21949]
### Operating System

Windows 10 Home

### OpenRCT2 build

OpenRCT2, v0.4.10-124-g575cd75 (575cd75 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

A few seconds after I opened the Track Designer, the background of the Track Designer was replaced with the main menu background along with the ground texture missing. After selecting a coaster, I clicked the "Forward to Next Step: Track Designer" button and nothing happened. In order to get out of the Track Designer menu, I had to close the game. The attachment is from after I have selected the coaster and it opened the in-game track list. 

### Steps to reproduce

1. Open the Track Designer. 
2. Wait for the background to change without ground texture
3. Select a coaster
4. Click the "Forward to Next Step: Track Designer" button. 
5. To get out of the Track Designer, close the game.

### Attachments

![image](https://github.com/OpenRCT2/OpenRCT2/assets/166532924/4363fb44-2e62-463a-8421-35b003d065b1)

**Comment by Gymnasiast** [comment]
Fixed by https://github.com/OpenRCT2/OpenRCT2/commit/8973e35ba1eae363985cdfa6a5f4d36870dea7cc , please update.

**Comment by DavidBlain2626** [comment]
Thank you! Everything works fine now.
