### ISSUE TITLE
Rides in object selector are shown with custom scenery objects instead of vehicles

### ISSUE THREAD

**Issue by cheweytoo** [OpenRCT2/OpenRCT2#21954]
### Operating System

Ubuntu Linux 22.04.4

### OpenRCT2 build

339a572 develop, Linux AppImage

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

If custom objects are used, some of them show up as vehicles for rides in the object selector:

https://github.com/OpenRCT2/OpenRCT2/assets/29800630/72caecfb-c16f-485f-a872-8dc5e8e1d650

Plugins are disabled.

I've attached several of the objects showing up in this video.

### Steps to reproduce

- have custom objects
- look at rides in object selector

Filtering by "custom" makes them easier to spot.

### Attachments

[custom_objects_showing_as_ride_vehicles.zip](https://github.com/OpenRCT2/OpenRCT2/files/15180404/custom_objects_showing_as_ride_vehicles.zip)

**Comment by cheweytoo** [comment]
I checked all the way back to 2271585 (oldest build still available on github): It happens there already.

**Comment by ZeeMaji** [comment]
From what i can tell of the webm, the objects showcased here are actual vehicle objects. There exists a lot of custom vehicles that are meant to be used for custom hacked rides that are only decorational, basically trackitecture but with vehicles instead.

So this is not an error, it's just these are some unorthodox objects meant for advanced sandbox play.

**Comment by spacek531** [comment]
I happen to have made two of the rides listed, Kite Skiiers and Ferris Wheel. None of these are scenery, they are all ride vehicles that resemble scenery.

**Comment by cheweytoo** [comment]
Oh, ok then.

Since I'm moderately sure not to have added those to my objects folder myself, I guess opening opening parks made by others made me "catch" those? There's probably no way to filter/hide those unorthodox vehicles, since they are just vehicles to the game, right?

**Comment by Gymnasiast** [comment]
Yes, loading a park will install all the bundled objects. Apart from deleting them or changing the filters to hide custom objects, there is no way of hiding them.
