### ISSUE TITLE
Linux framework?

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#2195]
Right now there are some hardcoded paths for Linux builds and I just wanted to get it done. It's fine for the moment, but ideally we'd like to be nice and user friendly and possibly ask about game directory with some sort of directory chooser, like windows build does.

This cannot, at least easily, be done without any framework, so I'd like to ask:
- Would we need a framework?
- Would we have enough features to justify the use of one?
- Should we just report to `stderr` that files were not found and let user figure out a way to provide valid path?
- If we do use framework, which one?

I think OpenTTD does this entirely in their content manager and they provide some initial files inside the package, but we're far from that point.

I'd rather not introduce any big dependency just for this dialog box, and my gut says @IntelOrca is with me on this one.

It would be somewhat unclean, but perhaps we could use [dialog](http://linux.die.net/man/1/dialog) or [zenity](http://linux.die.net/man/1/zenity) (and [screens](http://www.tecmint.com/zenity-creates-graphical-gtk-dialog-boxes-in-command-line-and-shell-scripts/)) with `system()` call?

**Comment by Gymnasiast** [comment]
I think GTK+ would be the best choice (at least for now), as it can be used from C and is very likely to be installed on most user's computers.

**Comment by AaronVanGeffen** [comment]
Maybe I'm mistaken, but I was under the impression that the file browsing dialog screens were going away altogether at some point? I thought the 'browse' button was left for debugging purposes, in case the new browser window was malfunctioning.

Either way, I'd rather not introduce a dependency on GTK+. While it is very popular and integrates well in most desktops, I'd rather we opted for something leaner.

**Comment by Gymnasiast** [comment]
GTK+ dialogs (and i'd image, QT dialogs) are designed to handle quite a variety of use cases and edge cases. Examples of those are files in hidden folders or mounted remotely over GVFS (which is technically also possible to access via /var/run/user/<uid>/gvfs/, but that's user hostile).

Considering RCT1 and RCT2 call OS file dialogs on Windows without any issue, I would say that GTK+ should be more than lean enough to use.

**Comment by IntelOrca** [comment]
I think its worth keeping the common open file dialog on Windows for users that want that experience. We can improve how it is current displayed because at the moment its a button that isn't even aligned to the window properly and has a non-intuitive label. Perhaps we can have a option to have the native dialog open by default, if its disabled then it opens the in-game window with a button to open the native dialog.

Windows and OSX provide a common API for this, so this thread is for what should be used in Linux. And I assume something like GTK+ is very easy to add to the build process right?

**Comment by Gymnasiast** [comment]
Yes, adding it should be simple, as it is in the repositories of every Linux distribution that has a GUI.

An example: https://developer.gnome.org/gtk3/stable/GtkFileChooserDialog.html

**Comment by Thaodan** [comment]
Not every Linux user uses GTK, it would be nice if someday the game data would be free like in OpenTTD. Before OpenTTD had free files their just asked to copy the files to gamedir (/usr/share/openttd usual on Linux or BSD). So I think its a better job for a packager to notify the user to push game data to the gamedir (the package in the Arch AUR already does some kind of this).

**Comment by IntelOrca** [comment]
@Thaodan The GTK UI for browsing the directory of the RCT2 install files can be compiled with the game only if the system has GTK installed - otherwise it will fall back to telling the user where to copy files to.

**Comment by Gymnasiast** [comment]
Almost addressed with Zenity and Kdialog - it only needs a feedback to a SDL message telling the user to copy the files/edit `config.ini`.

**Comment by IntelOrca** [comment]
Where are we with this?

**Comment by Gymnasiast** [comment]
In the state where we were when I wrote my comment on 23 March.

**Comment by Gymnasiast** [comment]
Why did you close this? I don't remember the last bit being solved.

**Comment by IntelOrca** [comment]
I don't understand.

**Comment by Gymnasiast** [comment]
If you don't understand, why did you close it in the first place?

Uninstall (or rename) Kdialog and Zenity and remove your config. Now try to start the game. After it asks you to select a directory it should display a dialog, which it can't do for lack of Kdialog and Zenity. At this point it should warn the user about this. That bit is still missing. If it wasn't I'd have closed this.

**Comment by IntelOrca** [comment]
Doesn't it warn them on the command line?

**Comment by Gymnasiast** [comment]
It does, which is _not_ sufficient.

**Comment by IntelOrca** [comment]
Replaced with #5784
