### ISSUE TITLE
gcc 14 include issue on 0.4.11

### ISSUE THREAD

**Issue by h3o66** [OpenRCT2/OpenRCT2#21976]
### Operating System

Fedora 40

### OpenRCT2 build

v0.4.11

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

when buildung with fedora 40 and gcc 14 there seem to be a issue regarding a include in src/openrct2/core/FileWatcher.cpp

this seems to be related to the commit 
https://github.com/OpenRCT2/OpenRCT2/commit/7b12667ddb15f5b45c12d9c551a1c7ee4037cf85

to fix this, i did need to add back 
```
#include <algorithm>
```

### Steps to reproduce

build openrct2 on fedora 40 

example:
https://copr.fedorainfracloud.org/coprs/birkch/openrct2/build/7420850/

snippet from build fail:
```
/builddir/build/BUILD/OpenRCT2-0.4.11/src/openrct2/core/FileWatcher.cpp
/builddir/build/BUILD/OpenRCT2-0.4.11/src/openrct2/core/FileWatcher.cpp: In member function â€˜void FileWatcher::WatchDirectory()â€™:
/builddir/build/BUILD/OpenRCT2-0.4.11/src/openrct2/core/FileWatcher.cpp:235:48: error: â€˜find_ifâ€™ is not a member of â€˜stdâ€™; did you mean â€˜findâ€™?
  235 |                         auto findResult = std::find_if(
      |                                                ^~~~~~~
```

I made the dumb fix  https://github.com/h3o66/OpenRCT2/commit/ab067e45460d9b8619344b814f2fe21f0a5d5cb9 for now, but not sure if this is a bug here or more gcc / compiler related

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/pull/21977
