### ISSUE TITLE
more rct2 global vars

### ISSUE THREAD

**Issue by kevinburke** [OpenRCT2/OpenRCT2#22]
0xf44078 is a count of the current possible ride configurations

0xf440a0 stores an index into ride_configuration_string_ids. ride_configuration_string_ids only stores information about track piece names.

0xf440b2 stores the previous track piece's slope
so does 0xf440b7, I believe but I'm not sure what is the difference between these two.

0xf440b3 stores previous track bank
0xf440b6 stores previous track bank as well.

0xf440a7 is an index to the current ride; this is frequently multiplied by 0x260 and used to index into `rides`.

**Comment by IntelOrca** [comment]
These variables are now implemented as part of ride construction.
