### ISSUE TITLE
OpenRCT2 does not allow image updates for `WindowWidgetType::ImgBtn`

### ISSUE THREAD

**Issue by mrmagic2020** [OpenRCT2/OpenRCT2#22007]
### Operating System

macOS 14.4.1 (23E224)

### OpenRCT2 build

OpenRCT2, v0.4.11 (893392d98 on develop, DEBUG)

### Base game

RollerCoaster Tycoon Classic

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

OpenRCT2 only allows button image updates for `WindowWidgetType::FlatBtn` but not `WindowWidgetType::ImgBtn`.
Seen here: https://github.com/OpenRCT2/OpenRCT2/blob/ba9c84f8354e63b354a66a7d01b7438c1dad4983/src/openrct2-ui/scripting/ScWidget.hpp#L502-L524

### Steps to reproduce

1. Using Basssiiie's [FlexUI](https://github.com/Basssiiie/OpenRCT2-FlexUI), create a button widget with properties `border = true`, `image=compute(<store-containing-sprite-id>, value => return value)`, and an `onClick` callback function that changes the sprite ID on each click.
2. Load the plugin and click the button. The image does not update.
3. Close and reopen the window. Now the image is updated.
4. Change `border` to `false`. Now the image updates on each click.

**Comment by Basssiiie** [comment]
To add to this. It's not necessary to use FlexUI to reproduce the bug. You can also make a vanilla button widget with `border: true`, and then attempt to update it with `findWidget("my-button").image = 5000;`. 🙂 Furthermore, getting the image id will also always return 0 for buttons with a border.
