### ISSUE TITLE
Camera jumps when Alt-Tabbing

### ISSUE THREAD

**Issue by hiandbye7** [OpenRCT2/OpenRCT2#2200]
When Alt-Tabbing the game in Fullscreen mode and Borderless Window mode the camera resets or has reset when coming back to it. Always to the same point of the map, regardless of camera rotation. Doesn't happen during window mode.

**Comment by IntelOrca** [comment]
That is probably due to my title screen fix last night, I will fix tonight.

**Comment by IntelOrca** [comment]
If someone would like to fix this now, all you need to do is wrap the fix location function in a "if screen & title_screen condition"
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/title.c#L252
