### ISSUE TITLE
Rotating view coutner-clockwise crashes game at one angle

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#2201]
I didn't check the code, just noticed it while playing.

**Comment by raidcookie** [comment]
Can confirm on latest build. Exception 0xc0000005 at 0x0200002f.

**Comment by HaasJona** [comment]
Confirmed.

It crashed inside undecompiled 0x66062C which is called from sub_68B3FB

**Comment by janisozaur** [comment]
Can you find which commit introduced regression?

On Wed, Nov 4, 2015 at 12:37 PM, HaasJona <notifications@github.com> wrote:

> Confirmed.
>
> It crashed inside undecompiled 0x66062C which is called from sub_68B3FB
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenRCT2/OpenRCT2/issues/2201#issuecomment-153694668>.
>



-- 
Michal Janiszewski

**Comment by HaasJona** [comment]
It way caused by https://github.com/OpenRCT2/OpenRCT2/commit/c0e2a5c7beea46ef6c92e5765c253f142b8b5e38, see my pull request.
