### ISSUE TITLE
Minimap does not display correctly in certain scenarios

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#22027]
### Operating System

Windows 10 64 Bits

### OpenRCT2 build

OpenRCT2, v0.4.11-67-g0e24569 (0e24569 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

A portion of the map does not appear when opening the map window in certain scenarios. The bug is not present in v0.4.11 so this might be a regression from #21981.

### Steps to reproduce

1. Open a scenario like for example Rio Carnival or After the Asteroid
2. Open the map window (see screenshots)

### Attachments

![Crater Carnage 2024-05-12 17-38-22](https://github.com/OpenRCT2/OpenRCT2/assets/28242696/8142849f-6214-4adc-b636-81fb3a3926f9)
![Sugarloaf Shores 2024-05-12 17-38-45](https://github.com/OpenRCT2/OpenRCT2/assets/28242696/c1ba5c54-3fc2-4b96-a17d-7f12f91431e4)

**Comment by AaronVanGeffen** [comment]
Interesting. This only seems to happen with the software renderer:
<img width="1512" alt="Screenshot 2024-05-13 at 09 53 43" src="https://github.com/OpenRCT2/OpenRCT2/assets/604665/08bdc301-d92a-4a56-83cf-7d99bc8557cc">

OpenGL is fine, for a change:
<img width="1512" alt="Screenshot 2024-05-13 at 09 53 45" src="https://github.com/OpenRCT2/OpenRCT2/assets/604665/0baf3e1e-5697-4361-b436-2474958f1e55">
