### ISSUE TITLE
OpenRCT2 won't build with GCC 14

### ISSUE THREAD

**Issue by solarisfire** [OpenRCT2/OpenRCT2#22029]
### Operating System

Arch Linux

### OpenRCT2 build

0.4.11.r77.g6df16c7946-1

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

When GCC14 is installed and used to compile OpenRCT2, the code will not build.

It will throw errors like:

<pre>/usr/bin/c++ -DDOCDIR=\"/usr/share/doc/openrct2\" -DOPENGL_NO_LINK -D_FILE_OFFSET_BITS=64 -D__ENABLE_DISCORD__ -I/home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/DISCORDRPC_PROCESS_INCLUDES -I/home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2/../thirdparty/duktape -I/home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/libopenrct2 -isystem /usr/include/freetype2 -isystem /usr/include/libpng16 -isystem /usr/include/harfbuzz -isystem /usr/include/glib-2.0 -isystem /usr/lib/glib-2.0/include -isystem /usr/include/sysprof-6 -isystem /home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2/../thirdparty -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -Wno-error=maybe-uninitialized  -Wno-error=restrict  -Wno-error=null-dereference  -Wno-error=stringop-overflow -fstrict-overflow -fstrict-aliasing -Werror -Wundef -Wmissing-declarations -Winit-self -Wall -Wextra -Wshadow -Wno-unknown-pragmas -Wno-missing-braces -Wno-comment -Wnonnull -Wno-unused-parameter -Wno-attributes -DDEBUG=0 -fno-char8_t -Wno-deprecated-declarations -O2 -g -DNDEBUG -std=gnu++20 -fPIC -Wsuggest-override -Wduplicated-cond -Wnon-virtual-dtor -Wduplicated-branches -Wrestrict -Wmissing-field-initializers -Wlogical-op -Wold-style-cast -Wunused-const-variable=1 -Wno-clobbered -Wredundant-decls -Wnull-dereference -Wignored-qualifiers -Wstrict-overflow=1 -DENABLE_SCRIPTING -pthread -MD -MT CMakeFiles/libopenrct2.dir/src/openrct2/actions/GameActionRegistry.cpp.o -MF CMakeFiles/libopenrct2.dir/src/openrct2/actions/GameActionRegistry.cpp.o.d -o CMakeFiles/libopenrct2.dir/src/openrct2/actions/GameActionRegistry.cpp.o -c /home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2/actions/GameActionRegistry.cpp
/home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2/actions/../ride/../paint/Paint.h:76:33: error: no matching function for call to ‘max(<brace-enclosed initializer list>)’
/home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2/actions/../ride/../paint/Paint.h:76:114: error: template argument 2 is invalid
/home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2/actions/../ride/../paint/Paint.h:76:10: error: ‘<expression error>’ in namespace ‘std’ does not name a type
/home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2/actions/../ride/../paint/Paint.h:81:52: error: ‘data’ was not declared in this scope
/home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2/actions/../ride/../paint/Paint.h:87:60: error: ‘data’ was not declared in this scope
/home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2/actions/../ride/../paint/Paint.h:93:58: error: ‘data’ was not declared in this scope
/home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2/actions/../ride/../paint/Paint.h:98:34: error: static assertion failed
/home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2/actions/../ride/../paint/Paint.h:99:34: error: static assertion failed
/home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2/actions/../ride/../paint/Paint.h:100:34: error: static assertion failed
FAILED: CMakeFiles/libopenrct2.dir/src/openrct2/actions/LandSmoothAction.cpp.o 
/usr/bin/c++ -DDOCDIR=\"/usr/share/doc/openrct2\" -DOPENGL_NO_LINK -D_FILE_OFFSET_BITS=64 -D__ENABLE_DISCORD__ -I/home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/DISCORDRPC_PROCESS_INCLUDES -I/home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2/../thirdparty/duktape -I/home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/libopenrct2 -isystem /usr/include/freetype2 -isystem /usr/include/libpng16 -isystem /usr/include/harfbuzz -isystem /usr/include/glib-2.0 -isystem /usr/lib/glib-2.0/include -isystem /usr/include/sysprof-6 -isystem /home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2/../thirdparty -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -Wno-error=maybe-uninitialized  -Wno-error=restrict  -Wno-error=null-dereference  -Wno-error=stringop-overflow -fstrict-overflow -fstrict-aliasing -Werror -Wundef -Wmissing-declarations -Winit-self -Wall -Wextra -Wshadow -Wno-unknown-pragmas -Wno-missing-braces -Wno-comment -Wnonnull -Wno-unused-parameter -Wno-attributes -DDEBUG=0 -fno-char8_t -Wno-deprecated-declarations -O2 -g -DNDEBUG -std=gnu++20 -fPIC -Wsuggest-override -Wduplicated-cond -Wnon-virtual-dtor -Wduplicated-branches -Wrestrict -Wmissing-field-initializers -Wlogical-op -Wold-style-cast -Wunused-const-variable=1 -Wno-clobbered -Wredundant-decls -Wnull-dereference -Wignored-qualifiers -Wstrict-overflow=1 -DENABLE_SCRIPTING -pthread -MD -MT CMakeFiles/libopenrct2.dir/src/openrct2/actions/LandSmoothAction.cpp.o -MF CMakeFiles/libopenrct2.dir/src/openrct2/actions/LandSmoothAction.cpp.o.d -o CMakeFiles/libopenrct2.dir/src/openrct2/actions/LandSmoothAction.cpp.o -c /home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2/actions/LandSmoothAction.cpp
/home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2/actions/../ride/../paint/Paint.h:76:33: error: no matching function for call to ‘max(<brace-enclosed initializer list>)’
/home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2/actions/../ride/../paint/Paint.h:76:114: error: template argument 2 is invalid
/home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2/actions/../ride/../paint/Paint.h:76:10: error: ‘<expression error>’ in namespace ‘std’ does not name a type
/home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2/actions/../ride/../paint/Paint.h:81:52: error: ‘data’ was not declared in this scope
/home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2/actions/../ride/../paint/Paint.h:87:60: error: ‘data’ was not declared in this scope
/home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2/actions/../ride/../paint/Paint.h:93:58: error: ‘data’ was not declared in this scope
/home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2/actions/../ride/../paint/Paint.h:98:34: error: static assertion failed
/home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2/actions/../ride/../paint/Paint.h:99:34: error: static assertion failed
/home/solarisfire/.cache/yay/openrct2-git/src/openrct2-git/src/openrct2/actions/../ride/../paint/Paint.h:100:34: error: static assertion failed
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().</pre> 

### Steps to reproduce

Install GCC14.
Try and build OpenRCT2.

**Comment by Gymnasiast** [comment]
Caused by Paint.h using `std::max()`, which is defined in `<algorithm>` and no longer included.
