### ISSUE TITLE
Unable To Connect To Elevated Exit

### ISSUE THREAD

**Issue by jcurbaniak** [OpenRCT2/OpenRCT2#22037]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.11 (18d2b5e) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

When there is an elevated exit for a ride, there does not seem to be any way to connect a footpath to it.   Slope options on Path menu are all grayed out.

### Steps to reproduce

1.  Add a ride with a elevated exit.
2. Attempt to connect a ground level footpath to it.
[OpenRCT2 Problem.docx](https://github.com/OpenRCT2/OpenRCT2/files/15322311/OpenRCT2.Problem.docx)
[OpenRCT2 Footpath Menu.docx](https://github.com/OpenRCT2/OpenRCT2/files/15322313/OpenRCT2.Footpath.Menu.docx)

**Comment by Gymnasiast** [comment]
Please add images to the issue directly, rather than putting them in a Word document.

**Comment by jcurbaniak** [comment]
![image](https://github.com/OpenRCT2/OpenRCT2/assets/134623850/f39dfaed-8139-4be3-940c-9fcc71ea1ee3)
![image](https://github.com/OpenRCT2/OpenRCT2/assets/134623850/27989573-0e1f-4f4f-8df5-53d22addfdd4)

Ok.  I figured it out.

**Comment by cheweytoo** [comment]
Your game window seems to not be high enough. There are two buttons on the bottom of the path building tool window, one of which enables the mode you're looking for:

![orct2pathmenu](https://github.com/OpenRCT2/OpenRCT2/assets/29800630/78888b12-a946-4ab6-9751-9b529d569dbf)

The game's UI looks unusually large compared to your Windows task bar – do you use a zoom setting much larger than 1 within OpenRCT2?

**Comment by jcurbaniak** [comment]
OK.   Thanks a bunch!!   I had the Windows scale factor set to 3.00.  Set it down to 1.50 and I can see the whole Path panel now.

 

Jerry Urbaniak
