### ISSUE TITLE
Guests will take pictures of photogenic ghost objects

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#22045]
This is a source of desyncs, besides just being incorrect.

**Comment by duncanspumpkin** [comment]
Is this different to the logic that makes them stop and watch rides being built (which uses ghost objects to indicate that).

**Comment by duncanspumpkin** [comment]
Checked the code and no it is not this is the same code. This is the expected behaviour and is desync free we check for network mode before choosing things to look at.

**Comment by Gymnasiast** [comment]
It is still a bug that they take photos of objects that haven’t even been placed.

**Comment by duncanspumpkin** [comment]
> It is still a bug that they take photos of objects that haven’t even been placed.

That is the whole idea of the feature. They watch and take photos of the user building the park.

**Comment by ZehMatt** [comment]
I'm fairly sure we guard this feature behind the network mode, in multiplayer games guests should not take any pictures unless there is somewhere some line that doesn't have the check.

**Comment by Gymnasiast** [comment]
Well, all right then.
