### ISSUE TITLE
no ingame sound since 8b51112

### ISSUE THREAD

**Issue by cheweytoo** [OpenRCT2/OpenRCT2#22051]
### Operating System

Ubuntu Linux 22.04.4

### OpenRCT2 build

8b51112 develop, Linux AppImage

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

Since 8b51112, I have no sound at all in a game (didn't test music). The title screen plays music, but has no ambient game sounds.

f4156e9 is still fine.

### Steps to reproduce

- Use build 8b51112 or newer
- no game sounds

**Comment by cheweytoo** [comment]
Tested enabled music on several rides: Ride music still works.

**Comment by AaronVanGeffen** [comment]
Thanks for reporting the issue. It's a bit late at night for me, but I intend to get this sorted out quickly, tomorrow.

**Comment by KyuuGryphon** [comment]
Windows 10 Pro here, can confirm. No ambient sound effects and no UI sounds, either - just the title screen music and the ride music in-game.

**Comment by F1Filter** [comment]
Can confirm for MacOS (V11.7) version as well.  Music only, no ride or UI sounds.

**Comment by AaronVanGeffen** [comment]
Thanks for checking in to confirm. A fix for the issue was filed last night, and is just pending review: #22053.
