### ISSUE TITLE
OpenRCT2 crashes upon exit

### ISSUE THREAD

**Issue by jcurbaniak** [OpenRCT2/OpenRCT2#22056]
### Operating System

Windows 10, 6 bit

### OpenRCT2 build

OpenRCT2, v0.4.11 (18d2b5e) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

Upon exit from OpenRCT2 there is a crash.   I thought it might be some plug-ins I added today, but removed them and problem continues.   What documentation do you need from me?
![image](https://github.com/OpenRCT2/OpenRCT2/assets/134623850/7f4b89e3-4377-4dd8-b699-71087a86d1da)

### Steps to reproduce

1.  Load a Saved Game.
2. Use direct exit from OpenRCT2.
3. Crash occurs.

### Attachments

![image](https://github.com/OpenRCT2/OpenRCT2/assets/134623850/4ad621f9-93b0-4842-993f-958abdd5dd6f)

**Comment by janisozaur** [comment]
When it crashes, when the dialog is still displayed, can you create a dump and attach it here? https://support.kaspersky.com/common/diagnostics/12401

**Comment by jcurbaniak** [comment]
Hmmm…today after 2 attempts NO CRASH.   Will continue to test.

 

Jerry Urbaniak

**Comment by jcurbaniak** [comment]
OK.  Got a dump today.  

 

Link to Dropbox

 

https://www.dropbox.com/scl/fi/x7bfkcpihmalbt7ak72if/openrct2.DMP?rlkey=2jw0whtnmppvt3qmcavj60k7p <https://www.dropbox.com/scl/fi/x7bfkcpihmalbt7ak72if/openrct2.DMP?rlkey=2jw0whtnmppvt3qmcavj60k7p&st=x15er5bb&dl=0> &st=x15er5bb&dl=0 

 

Jerry Urbaniak

**Comment by jcurbaniak** [comment]
This is not a consistent problem.  Not every exit crashes.  Even so not a showstopper as the game is still playable.

**Comment by CookiePLMonster** [comment]
Does it happen on all saved games, or only a specific park?

**Comment by jcurbaniak** [comment]
It is irritatingly random.  Different parks.   Sometimes with a park with many rides or just a few.

 

No pattern that I can see.

 

Sometimes my sound driver is corrupted and I have to reboot to regain sound.

 

Jerry Urbaniak

**Comment by CookiePLMonster** [comment]
Do you have any plugins installed at all? From what I can see, it is a crash in the scripting interface.

**Comment by jcurbaniak** [comment]
Yes.  

 

These are my plugins.

 



 

The only one I really depend on is benchwarmer.

 

Should I remove them one at a time?  Or maybe remove all and add back in one at a time?

 

Jerry Urbaniak

**Comment by CookiePLMonster** [comment]
> Yes. These are my plugins. The only one I really depend on is benchwarmer.

Your list is missing from the reply.

**Comment by 733737** [comment]
email attachment images dont show up on github.

**Comment by jcurbaniak** [comment]
Here is the plugin list again.

![plugins](https://github.com/user-attachments/assets/7646456d-bc34-4882-9680-0becb4610a5c)

Jerry U.

**Comment by CookiePLMonster** [comment]
Thanks! To make it simpler to investigate, could you upload your entire `plugin` directory? If you pack all those files into a .zip file, it will be possible to just drag and drop that archive in here on GitHub.

**Comment by jcurbaniak** [comment]
As requested
[RCT2 Plugins.zip](https://github.com/user-attachments/files/16197277/RCT2.Plugins.zip)

**Comment by CookiePLMonster** [comment]
I tried reproducing the crash several times with these plugins and the strictest memory checks I can enable, to no success - are you still encountering this crash on 0.4.12?

**Comment by jcurbaniak** [comment]
I will monitor.   Thanks for all of you interest and  help with this issue.

 

Jerry Urbaniak

**Comment by jcurbaniak** [comment]
Just got crash under 0.4.12.  Dump file too big to attached (even zipped). 

Can be found on Dropbox at this link:  

https://www.dropbox.com/scl/fi/xkbhyai285pbk5nl5on9j/Dump.zip?rlkey=w38m4pweltsfsqg7bv34h4okn&st=1615avhz&dl=0

**Comment by CookiePLMonster** [comment]
I reproduced the crash by doing the following:
1. Make sure replays are recorded - by default dev versions don't record them, that's why I struggled to repro the crash!
2. Start a new map where you can alter the water level.
3. Lower or raise the level.
4. Alt+F4 from the game.
5. Observe a crash as the `SetWaterLevel` game action destructs.

I'll keep investigating, but I just wanted to leave those instructions here.

**Comment by CookiePLMonster** [comment]
Check https://github.com/OpenRCT2/OpenRCT2/pull/22293 for a fix.

**Comment by jcurbaniak** [comment]
I am not sure how to install the fix if it is ready.

 

Jerry U.

**Comment by CookiePLMonster** [comment]
For now you should just wait for the next stable release that'll include the fix. This crash is "harmless" and cannot damage your save data or anything.

**Comment by jcurbaniak** [comment]
Thanks so very much for your support with this issue.

 

Jerry Urbaniak
