### ISSUE TITLE
Flat diagonal Hybrid Coaster track draws in incorrect colour

### ISSUE THREAD

**Issue by Basssiiie** [OpenRCT2/OpenRCT2#22063]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.11-111-g2217d40 (2217d40 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

The flat diagonal track piece for the Hybrid Coaster draws the side bars in the wrong colour. The issue happens in all placement rotations and viewing rotations.

Other similar track pieces, like banked pieces, brakes, and block brakes look fine.

### Steps to reproduce

1. Build a flat diagonal track piece for the Hybrid Coaster.
2. Make sure the track and supports are of different colours.

### Attachments

![image](https://github.com/OpenRCT2/OpenRCT2/assets/20048660/ce91d688-0c01-4e76-aea1-f637c1e40756)

![image](https://github.com/OpenRCT2/OpenRCT2/assets/20048660/d827c93c-daa6-4edc-815e-ea879583614e)

![image](https://github.com/OpenRCT2/OpenRCT2/assets/20048660/ec0792ab-f295-45b2-bc3a-6dfe25c6fe72)

![image](https://github.com/OpenRCT2/OpenRCT2/assets/20048660/378c95a5-0b71-4d3d-a1a7-f11cf76adaf3)

![image](https://github.com/OpenRCT2/OpenRCT2/assets/20048660/7630e634-7947-4d40-8a43-275fff50dbe5)

**Comment by AaronVanGeffen** [comment]
The sprites themselves look like they have both remap colours. It seems `HybridRC::TrackDiagFlat` may need to be adjusted. Perhaps `HybridRC::TrackDiagBrakes` can help act as reference.

**Comment by Gymnasiast** [comment]
Probably caused by a recent refactor to that function. Need to figure out how to fix it without just reverting.
