### ISSUE TITLE
New ideas for ORCT

### ISSUE THREAD

**Issue by hytacker** [OpenRCT2/OpenRCT2#2206]
Hee guys, (sorry for typos english isn't my native language)

I know its not the time to really get into this part of production yet, but since i cannot contribute to the current stage (I dont have any experience in programing) and really want to participate because I really like what you guys are doing. I came up with the following:

Awards:
In RCT2 you could win awards for being the best in this or that. Though its a cool feature it didn't really gave you anything. Let's say you win the award for safest park in the country. Would it be cool to earn a discount on new mechanics or earn a free month of wages. At least something that will benefit you. For every award you get you can think of something nice to give. This could add a lot of fun to the game.

Fanatic groups of peeps:
In real life there are people that travel around the world in groups to find the most badass rollercoasters to ride in them. Now I thought that mayby it would be cool if you constructed a rollercoaster with a excitement rating over a 9 or so that a group of people would enter your park (all dressed the same!) and go straight for your badass rollercoaster. You can implement this same principle for all sorts of attractions. like go karts or ride in a car. 

Mountain tool:
In one of the rtc1 additions there where some mountain tool options that where not included in rct2 because rct2 had the options of building scenery. But if I remember it correctly you could give the side of a hill the colour yellow and red and these also changed the apperance of an attraction going in the side of a mountian. They where round instead of square. Could you guys bring this back?

Eye dropper:
For example: you brought down a piece of land, now scenery on top of it gets deleted. (This has to disapear btw) it is very annoying to search for one or two scenery objects to replace it. An eye drop option would make this much, much easier and would speed up a building process in general.

Handyman:
Handymans could use some updates as well. How they orientate their selves around paths and towards litter. Besides that they should be able to fix vandelism. I know you guys already have some cheats to help this, but i mean actually seeing a handyman fix a bench. I can also remember a feature that chis saywer had in the original plans for rtc. And that was a handyman taking a lunch break. There's a change there might be something left in de game that shows this. How cool would it be to add this.

Tour guide:
An additional employee that walks around and accumulates peeps that will bring a buch of people from one place to another and in the mean time stops and pretends it is giving some information. This will bring the happiness up. This could also be implemented as an attraction maybe.

Mobile salesman.
An additional employee that walks around and sells for example balloons, souvenirs or icecream.

Medic:
An additional employee. There are benches and emergency posts for peeps to go to. To lower there nausia. But they will only do so when there nausia has reached a certain point. These workers will reduce lets say 20-25% percent of nausia when he/she is helping a peep. They help peeps that have a nausia rating higher than 10%.

Original peep codes:
Some cheat codes that where put in the game made some of the guests do some unique stuff. Like taking photographs and making paintings. There might be some cool ways to implement these features in the game without having them to activate threw cheat codes. The michael schumacher cheat code that let a person to drive really fast would be al cool option to use for a fanatic group of peeps when you have build a go karts attraction that has a high excitement rating. 

The amazing earl:
This guy had made alot of mods for rollercoaster tycoon 2. All of his creations look like they where made by chris saywer. The blend in perfectly. These could be used to expand the options of attractions. Here's a link: http://rct.wikia.com/wiki/The_Amazing_Earl 

Peeps:
I would like to see that peeps would enjoy the scenery more than they did originaly. By not alone giving them a bigger variety in thoughts about this. But also incorporate a game mechanic that lets a peep be picky in wich attraction he wants to go in based on the scenery that ride has to offer. There are no graphics for girls or for other races in the game. I dont know if you guys are planning to improve rtc up to that extant. but it would be awesome! If some of the peeps would prefer to walk in groups or lets say with there family that would be cool. A bigger variety in appearance. Like peeps having backpacks, already whearing glasses or applauding when there's a new ride available (only peeps that are close to the new ride)

Random events:
Planes flying over, personal messages from peeps that you follow, having peeps ask for the completion of a particular ride. fulfilling this need will boost some stats, accidents that can happen during rides that lowers happines, peeps finding money, peeps finding items raises their happines, peeps finding their solmates and stay together. 20% higher chance of this happening on the swans ride ( oehw,, romantic)
peeps sharing money or giving stuff, peeps saying funny stuff like: I think I left my oven on, at home. peeps that steal stuff which a guard can prevent, more wild life (fish, birds), peeps that request you to plant them somewhere else. A peep on drugs haha doing crazy stuff.
And many more you name it. All of this wil help to create a more dynamic wolrd.

Achievements:
All these achievements can be completed in the campaign or in a continuous park. They can only be completed one time. 

click on a duck
pop a balloon
drown a peep
a crashed coaster
build your first attraction
build your first rollercoaster
have a peep enter an attraction for the 10th time
have an excitement/intensity/nausia rating above 5, 10 and so on..
build 10, 20, 30 attractions
more than 5 rollercoasters
more than 10, 20, 30 staffmembers
placed an amount of ground/water
I could go on forever on this.. 

New attractions:
I know this would be alot of work to do properly but here's a list of attraction I thought off.

Indoor sky dive
Heli ride (actualy flyes around the park)
Plane ride (also really flyes, They could take off at the same airport)
Parachut drop with landing spot (on ground or on roofs)
Ferry ride
bus thats able to drive across footpaths.
Shooting stall
Water walkers (these big floating balls where you can climb into)
Game corner
Casino
Another type of cinema
Open theater
Slingshot
A play ground (with al kinds of different playground equipment, expandable)
minature railway with multiple platforms
paragliding
mazes with additional objects like a watch tower

Since there is a day and night cycle. Maybe it would be cool to add hotels and/or camping sites which alot of themeparks have. and restaurants. 

And additional things like fireworks, lighting, things to add on waiting lines (To ease the waiting), music boxes, custom music, scenery that benefits the experience of rides and coasters, a crossing point for footpaths and trains and so, having a clear and separete option to play a continuous game, a click and drag option for scenery no more single clicking fences please.

I can think of way more but I am done for it for now. Let me know if you guys think if there's some usefull stuff in this all. I've been busy on this for a whill now. I've one of you thought about something more let it be know in the comments.

Greets,

Hytacker.

I've included a screenshot from my best park. no mods

![scr1](https://cloud.githubusercontent.com/assets/15657920/10953037/15e65ab2-8346-11e5-85ee-9331accd601c.png)

**Comment by IntelOrca** [comment]
Awards do do something, positive awards attract more guests to your park, negative ones do the opposite.

**Comment by Gymnasiast** [comment]
I'm sorry to say, but this is the wrong way to open an issue. It has several unrelated ideas mashed together. Also, whether some things are actually improvements depends very much on opinion. With all these idea together, discussion becames impossible.

While I won't go in-depth on most suggestios, I will say a thing about The Amazing Earl: he has done wonderful things, but his created _don't_ blend in perfectly. His graphic style does not meet Simon Foster's (though it is usually better than Frontier's WW and TT graphic styles).

I think the best course of action is discussing this on the OpenRCT.net forum. That will give you a far better feedback and discussion.

**Comment by hytacker** [comment]
alright i will copy past this on to Openrct.net. I dont know i've you would prefer this deleted on this site, but it's fine by me if it doesn't fit in.

**Comment by janisozaur** [comment]
Please file an issue here on github for each idea you have, this will allow for some discussion regarding it. It's hard to do when they're all lumped together like here.

**Comment by IntelOrca** [comment]
The issue tracker isn't really for discussions this broad and its not something we can tick off easily. It would be better if your ideas were split up into individual issues. For example the eye dropper ideas has been suggested before, I can't remember if there is an issue for it yet.

**Comment by hytacker** [comment]
Yes okay, I will split these ideas up into individual issues. I simply didn't had the knowledge on how to post this properly. Sorry for that. I really appreciate the quick responses. And I want you to know that the things you guys are doing here with rct2 is something really special. Alot of effort has to be put in this project. I've always been a die hard fan of the rollercoaster tycoon series that chris sawyer had made. You all are making a dream come true! And if by change some of the ideas i brought up here make there way in the final game it would be an absolute privilege. Keep up the good work!

**Comment by pizza2004** [comment]
I have something to say in general about the ideas.  Namely, much of what makes RCT fun is simplicity.  There aren't a lot of things to keep track of, unless you want them to be, and the game doesn't feel like it's overly random, and therefore hard to predict how things will go.  Doing the same things brings the same results.  I feel like many of these suggestions would be significant changes to the flow and balance of the game.  I wouldn't mind a NewGRF type system that could add these sorts of things, but putting just about any of them (except the scenery eyedropper or clone tool or whatever you want it to be) into the base game seems like it would be against the idea of the project.

He mentions a few things that have already been brought up in other places that seem like they wouldn't impact the gameplay too much though, but I don't know what's been said before.  Namely, I like the idea of some dynamic lighting that can occur if day/night cycle is enabled, or it starts to rain, which has an issue already #1739.  I like click and drag tool for scenery, but I'm not sure it has an issue specifically.  I like adding mountain and tunnel things that were in RCT, but that's one of the things mentioned in some documentation somewhere as a possibility already.  And custom music, which I know has been discussed before, in #1783.

I also have to say that I'm generally opposed to the idea of adding variety in race and gender to the peeps, as that just seems like a cosmetic change that adds no real benefit to gameplay.  More than that, I'm vehemently opposed to achievements, as every game seems to have some sort of need to have them these days, and they add no real point to gameplay whatsoever.

So I guess what I have to say is, any 'additions' to gameplay, like new staff or rides, probably shouldn't even have issues created for them, as that's not the scope of the project, as much as it would be up to individual content creators, and any modifications or new features, like AI changes in peeps or new GUI to handle various tasks should have issues created for them separately, in order to allow for better discussion of each one.

Sorry if this comment is bothersome, I just figured I'd put in my two sense on the suggestions overall.

**Comment by Patrik356b** [comment]
Flying/plane ride already suggested #2124

**Comment by Gymnasiast** [comment]
Closing this, then, as @hytacker will split it up.

Some things you shouldn't open an issue for as they are already reported/planned/implemented:
- Flying/plane ride (#2124, as notified by Patrik356b)
- Missing land types and sides from RCT1 (planned as missing RCT1 feature)
- Miniature railway with more platforms (planned, as well as more changes, like actual level crossings, switches and such).
- Scenery that benefits the experience of rides and coasters (it already works that way in RCT2!)
- Eye dropper
- Handymen fixing vandalism

In general, I agree with @pizza2004 that the game still retain the spirit and feel of RCT1 and 2, and not every idea fits into this. However, I'm not going to comment on them now, I will wait for the individual issues.
