### ISSUE TITLE
FPS counter copied over main viewport

### ISSUE THREAD

**Issue by J-PIE-314** [OpenRCT2/OpenRCT2#22066]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.11-133-g06e2363 (06e2363 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

When moving the main view, the FPS counter is copied on-screen.

This issue appears after the UI toolbar is centered—a feature introduced in #21989.
This issue is reminiscent of #20739.

### Steps to reproduce

1. Open any park.
2. Ensure that the FPS counter is active and the UI toolbar is centered.
3. Use the arrow keys on your keyboard to move the main view and observe the issue.

### Attachments

![centered ui issue](https://github.com/OpenRCT2/OpenRCT2/assets/80489909/3c5facf8-2195-48f3-b296-39792c035fae)

**Comment by duncanspumpkin** [comment]
See PR #21989 i've put a line note where the invalidation code needs to be updated.
