### ISSUE TITLE
Hover Car Vehicle bug for Car Ride

### ISSUE THREAD

**Issue by marscrystalpower** [OpenRCT2/OpenRCT2#22073]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.11-137-gbbb5b92 (bbb5b92 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

The bug also exists in the original game (RCT2/RCTC)

### Describe the issue

Small bug that, as far as I can tell, exists in both the base game and OpenRCT2. The Hover Car vehicles for the Car Ride say that each car has a capacity of 2 guests, but in reality each car can only carry 1 guest. Screenshots are attached for proof. From what the in-game graphics look like, they indeed only carry 1 guest much like the Pickup Truck and Racing Car vehicles.

### Steps to reproduce

1. Build a Car Ride with the Hover Car vehicles from Time Twister
2. Go under the "Vehicle details and options" tab
3. View the ride capacity, compared to how many guests actually board each vehicle

### Attachments

![HoverCar1](https://github.com/OpenRCT2/OpenRCT2/assets/170404619/6093ce90-6a51-48e2-b80e-498c6d6932e3)
![HoverCar2](https://github.com/OpenRCT2/OpenRCT2/assets/170404619/b9fb0fa5-06d0-494c-afbd-9f94a00d89f5)

**Comment by mrmagic2020** [comment]
This issue was addressed two weeks ago here: https://github.com/OpenRCT2/objects/issues/331. Turned out the intended capacity was 1 per car.

**Comment by Gymnasiast** [comment]
We still need to do an object sync (which we will do before the next release), which is why the fix hasn’t hit develop builds yet.
