### ISSUE TITLE
When creating custom themes, certain colors cannot be used for buttons or windows.

### ISSUE THREAD

**Issue by Derpercoaster** [OpenRCT2/OpenRCT2#22081]
### Operating System

Windows 10 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.11-137-gbbb5b92 (bbb5b92 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

When creating a custom theme in options (or when modifying an existing one), some colors cannot be selected when coloring windows and buttons. The colors that cannot be selected mostly seem to be the newly added colors, but some new colors are accepted.

### Steps to reproduce

1. Create a custom theme
2. Try changing theme colors
3. Some colors, when selected, will switch to the most similar vanilla color instead of being accepted.

**Comment by Gymnasiast** [comment]
This is a duplicate of #19870. And there is even a PR pending.

**Comment by Derpercoaster** [comment]
I looked around and didn't find that issue, I guess I didn't look well enough, my bad.
