### ISSUE TITLE
Optimise object loading

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#2208]
When the game loads a new map, it takes 1-5 seconds to load and begin rendering, which causes the game to pause in the mean time. Would it be possible to Preload the map into a buffer that would let us swap it in much quicker?

**Comment by IntelOrca** [comment]
eh. the time is mostly taken loading the objects. And that part is messy and inefficiently and really out of our control until we are able to change the object list data structures.

**Comment by PFCKrutonium** [comment]
Ah, fair enough. Would you like me to close it or would you prefer to label it and let it sit in the bug tracker till we can do something about it?

**Comment by PFCKrutonium** [comment]
IIRC this has been done for the most part - Correct @IntelOrca ?
