### ISSUE TITLE
(up) no longer works in open/save dialogs.

### ISSUE THREAD

**Issue by osconnoisseur** [OpenRCT2/OpenRCT2#2210]
Just found another bug! When browsing files in the in-game open/save dialogs, clicking (up) does nothing. This worked in earlier builds (1385, for example).

**Comment by PFCKrutonium** [comment]
Confirmed.

**Comment by Gymnasiast** [comment]
It must have happened in the last few days, as it still worked in a version I compiled on 1 November.

**Comment by osconnoisseur** [comment]
a0909a2 and 45bfdad we

**Comment by osconnoisseur** [comment]
a0909a2 and 45bfdad were the last two commits that touched loadsave.c, so I'd guess it's probably something in one of them.
