### ISSUE TITLE
Mousewheel behavior is the opposite of v0.4.11 for certain tools

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#22102]
### Operating System

Windows 10 64 Bits

### OpenRCT2 build

OpenRCT2, v0.4.11-151-g15837e7 (15837e7 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

Mousewheel down increases the selection size of the land tool, water tool, remove scenery and patrol selection but still works properly with money values. 
Perhaps a regression from #22060 @AaronVanGeffen ?

### Steps to reproduce

1. Open land tool
2. Use mousewheel to scroll up or down

**Comment by AaronVanGeffen** [comment]
Interesting. Yes, this sounds like a regression. I'll look into it.

**Comment by AaronVanGeffen** [comment]
Ah, it's because in OpenLoco, the widget order is [decrease, increase] for both the tools and stepper widgets. For OpenRCT2, the widget order is [decrease, increase] for the tools, but [increase, decrease] for the spinner widgets, though. Unfortunately, I generalised it for OpenRCT2 as well.
