### ISSUE TITLE
Missing Rides

### ISSUE THREAD

**Issue by jcurbaniak** [OpenRCT2/OpenRCT2#22105]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.11 (18d2b5e) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

Some downloaded tracks in C:\Users\Jerry New\Documents\OpenRCT2\track do not appear in the Object Selection menu.   For example Caesars Palace.td6   I have checked  "Ignore Research Status".  What am I doing incorrectly?

### Steps to reproduce

1. Start OpenRCT2 saved game.
2. Access Object Selection drop down item.
3. "Caesars Palace" does not appear in any ride group.

**Comment by jcurbaniak** [comment]
![image](https://github.com/OpenRCT2/OpenRCT2/assets/134623850/a427a868-f44e-45be-8398-192d34df8596)

**Comment by jcurbaniak** [comment]
![image](https://github.com/OpenRCT2/OpenRCT2/assets/134623850/f3a98d98-2524-4f21-8022-d2a8203804af)

**Comment by HtotheTML** [comment]
Track designs are not viewed on the object selection screen. Instead, they are shown in the track designs menu that pops up when you go to build a ride.

If you know what ride type the track design is for, select the ride type, then go to build that same ride. The track designs menu should pop up with a list of saved track designs.

Alternatively, you can go to the ride designs manager from the main menu and sift through track designs that way.

**Comment by jcurbaniak** [comment]
Thanks for the quick response.

 

Well, Track Designs Manager does not show Caesars Palace:

 



 

Caesars Palace is also not on Track Designer window:

 



 

 

But I DID find it when attempting to build a new coaster:

 



 

I have to ask what are all the U(nnnn) coasters?   Did the track uploader not properly name their coaster?

 

Jerry Urbaniak

**Comment by 733737** [comment]
please close the issue, as there is no bug

**Comment by jcurbaniak** [comment]
I did find Caesars Palace in Track Designer Manager.  I needed to click to go down another level.  That does not work with Track Designer but I am not sure how this panel is used.

**Comment by HtotheTML** [comment]
The u(####) rides are user created track designs that were included with Rollercoaster Tycoon Deluxe. Their actual names were chosen not to be displayed, likely because they would run into copyright or rating issues with what certain designs were called by their original creators.

**Comment by HtotheTML** [comment]
> I did find Caesars Palace in Track Designer Manager. I needed to click to go down another level. That does not work with Track Designer but I am not sure how this panel is used.
Track Designs manager is used for renaming and deleting ride designs from your library without having to go all the way into file explorer and doing it there. 

In Track Designer, you add all of the ride types you want to use, then practice building with them. After you select what ride types you want to build with and continuing to the next step via the button on the bottom right of the screen, it should open a window for building a new ride. Simply click on one of the ride pictures and it should bring up a similar window to what you saw in Track Designs Manager.
