### ISSUE TITLE
preloader scene reads as "normal" GameMode in API

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#22119]
### Operating System

Windows 10 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.11-141-gce626b6 (ce626b6 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

When loading, the game reports it is ingame ("normal") when it is actually loading.

### Steps to reproduce

```js
registerPlugin({
    name: "Simple Intransient",
    version: "1.0",
    authors: ["spacek"],
    type: "intransient",
    license: "MIT",
    minApiVersion: 88,
    main: function() { console.log("context.mode",context.mode);}
});

```

'context.mode' 'normal'

**Comment by mrmagic2020** [comment]
Do we need a new `SCREEN_FLAG` or simply set it to an existing flag?
