### ISSUE TITLE
Solo guest scream incorrectly loops on long downwards sections of track

### ISSUE THREAD

**Issue by Phosphorus551** [OpenRCT2/OpenRCT2#22112]
### Operating System

Windows 11

### OpenRCT2 build

OpenRCT2 v0.4.11 (18d2b5e)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs, This is a development issue

### Describe the issue

The solo guest scream unique to twister type coasters + the single rail coaster in the base game seems to loop on long enough sections of downwards slope. See the attached video. 

https://github.com/OpenRCT2/OpenRCT2/assets/134081940/7a1a6d41-444b-491c-9c8a-509639a4bbb8

### Steps to reproduce

The example video uses a non-vanilla train on the coaster, however this can also be observed on rides such as Goliath in Roller Coaster Tycoon 2's Six Flags Magic Mountain scenario. Simply open the scenario and observe the trains until the specific scream is triggered on a long enough hill. 

https://github.com/OpenRCT2/OpenRCT2/assets/134081940/8cd90df9-5f26-48ce-a9fd-4a235c358410

**Comment by deurklink** [comment]
Duplicate issue: https://github.com/OpenRCT2/OpenRCT2/issues/19780
But good that it's brought to attention again ;)
