### ISSUE TITLE
Stuck Guests

### ISSUE THREAD

**Issue by jcurbaniak** [OpenRCT2/OpenRCT2#22132]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.11 (18d2b5e) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

I have a group of guests that are stuck in one place.  I have built a path for them to move and even closed the park but they remain stuck.  What can I do to correct this problem?   I have tried to pick them up one at a time but that is taking forever.

### Steps to reproduce

1.  See attachment with stuck guests in red circle

I tried to also attach the PARK file but that file type is NOT SUPPORTED according to message received.

### Attachments

![Stuck Guests](https://github.com/OpenRCT2/OpenRCT2/assets/134623850/fa873f6d-3089-4759-955f-81b6724bcd61)

**Comment by deurklink** [comment]
You can upload the park file by zipping it first

**Comment by jcurbaniak** [comment]
Thanks!

 

Jerry U.

**Comment by deurklink** [comment]
For some reason these guests have a weird pathfind goal. When I set other guests to Leaving Park using the peep editor plugin, they will pathfind to the park entrance without issue. 
![image](https://github.com/OpenRCT2/OpenRCT2/assets/6469413/4ac41b94-3d98-4e9b-8da6-bac48902b764)

**Comment by deurklink** [comment]
I have found the issue, the guests are stuck on a piece of path that is suspended in the air, above the path that you see. Remove the path which the guests are standing on and they will fall down to the ground again. Here you can see the path piece with the guests made invisible 
![image](https://github.com/OpenRCT2/OpenRCT2/assets/6469413/aaf5721c-fc80-4c36-aac1-af5cb3dba244)
Here you can see the guests fall down when I remove the path piece:
![image](https://github.com/OpenRCT2/OpenRCT2/assets/6469413/cc1f212d-b145-4d5c-8f22-3041d2e30473)

This should allow you to free them.

**Comment by jcurbaniak** [comment]
Thank you so very much.   I have no idea how that happened.   Clearly NOT a bug.

 

Jerry U.
