### ISSUE TITLE
Error loading objects - rct1.ride.stand_up_trains

### ISSUE THREAD

**Issue by suikunkun** [OpenRCT2/OpenRCT2#22130]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.11 (18d2b5e) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

When I try to open certain RCT1 scenarios, I get an error window:
"Error loading objects for park
The file could not be loaded as some of the objects referenced in it are missing or corrupt. A list of these objects is given below."
Only one object is listed: rct1.ride.stand_up_trains.
Clicking the "Download all" button doesn't seem to fix the issue. 

See the attached screenshot. What to do?

### Steps to reproduce

1. Open game
2. Open an RCT1 scenario (presumably one that has the stand-up trains)

### Attachments

![openrct2 standup](https://github.com/OpenRCT2/OpenRCT2/assets/12559681/a126251a-5e53-4337-9cbd-65e3069da9a7)

**Comment by Gymnasiast** [comment]
You have a broken install. Please uninstall OpenRCT2 and then reinstall it again.

**Comment by suikunkun** [comment]
Hi @Gymnasiast. It worked! I probably should've tried earlier. Thanks for your help & have a good weekend.
