### ISSUE TITLE
Ride time is incorrect for extremely low speeds

### ISSUE THREAD

**Issue by astraylife1** [OpenRCT2/OpenRCT2#22133]
### Operating System

MacOS

### OpenRCT2 build

OpenRCT2, v0.4.11 (7c9b27f on develop)

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Using the Ride Vehicle Editor plugin, it is possible to set powered vehicles' max speed anywhere from 1 to 255 units. When setting vehicles to max speed to 1 or 2 units (1mph or less than 3kmh) the vehicles crawl so slowly that when returning to the station, the game registers the ride time as 1 second regardless of actual length. I tried recreating this with a normal vehicle in powered launch mode set to 0mph but the vehicle will still move faster than this threshold and register accurate ride time. It seems that in these extremely low speeds (units 1 and 2), the game just doesn't count the ride time but will if its at least 3 units of speed.

### Steps to reproduce

Set powered vehicle max speed to 1 or 2 units in the Ride Vehicle Editor plugin and test ride.
Ride time will read 1 second.

### Attachments

<img width="1521" alt="speed issue" src="https://github.com/OpenRCT2/OpenRCT2/assets/98492730/ebf185df-f8b7-4079-a1bb-19fb0dd314a4">

**Comment by lewyche** [comment]
Which turns out is more accurate, since the average speed is less than 1 km/h.

**Comment by ZehMatt** [comment]
This could be potentially be improved by using fixed point integers, money already does it.
