### ISSUE TITLE
Incorporate 'some' cheat code sprites/mechanics in base game

### ISSUE THREAD

**Issue by hytacker** [OpenRCT2/OpenRCT2#2213]
Some cheat codes had the ability to let peeps do certain things. Now some of these sprites where simple stuff. Waving, taking pictures and painting art for example. Other sprites like jumping and giving applause take place when a peep enjoyed a ride or you completed your objective. Maybe it's an idea to incorporate these sprites in the base game. Let these momentes happen more often. Every peep could be able to take a picture or wave some of the times. Or on a more rare occasion paint art. Giving aplause could also be added when you completed a new attraction. 

A comparable but more drastic idea is to have 'special' guests coming into your park that own the unique mechanics of some of these cheat codes. Like the micheal schumacher and tony day cheat code. (peep that goes faster in a go kart, and a peep that's always hungy)

I know the special guest idea would change the original game and there for isn't relevant for the base game. But incorporating some of the already excisting sprites and mechanics to the peeps (that now go lost) in the base game would, if you asked me created a bit more of a fun to see, lively world. 

In regards of the new ideas for ORTC #2206 post. I will only re-post the ideas that have a chance to be added in the base game. All other ideas will come at a later date if the time is ready.

**Comment by pizza2004** [comment]
I don't think it would be game breaking at all to make it so there's a small chance that any peep could do a few of the special behaviors, like taking pictures or going fast on a ride, although I do think it would be better to have some of them stay special, like painting, as it seems weird to me that any peep could just paint something.

**Comment by HaasJona** [comment]
If all peeps or random peeps would do these actions randomly, that would reduce the value of winning the game or using the special codes. It's a lot of fun sometimes to rename guests and watch them. But if all guests do these things, it's nothing special anymore.

The only additions in peep behaviour I see for the foreseeable future is the addition of new cheat codes/sprites related to OpenRCT2. For example give a peep special behaviour if you name him "Ted John" or something like that.

**Comment by hytacker** [comment]
Yes I understand. I wasn't implying to add actions that could influence the way of winning an objective. But there are some sprites and mechanics in the game right now that are not being used. But can be used in a way that enhaces the livelyness. Without them having a direct influence towards objective's.
