### ISSUE TITLE
Not Able To Access Second Custom Music File

### ISSUE THREAD

**Issue by jcurbaniak** [OpenRCT2/OpenRCT2#22146]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.11 (18d2b5e) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

Even though there are 2 different custom music files in the OBJDATA folder for RCT2;

![image](https://github.com/OpenRCT2/OpenRCT2/assets/134623850/3fec990c-eb72-4a8b-a9cd-a83f6d1bbeca)

When music is selected for a ride only 1 appears as "legacy Custom Music 1:

![image](https://github.com/OpenRCT2/OpenRCT2/assets/134623850/081c707c-9f6f-43e5-8d8e-54e207a222de)

Am I doing something incorrectly?  Thanks in advance.

### Steps to reproduce

1.  Add 2 Custom Music wav files to OBJDATA folder in RCT2 .
2. Start OPENRCT2 and load a park.
3. Click on a ride in the park and select the music tab.
4. Only 1 Custom Music option appears in the drop down list.

**Comment by Gymnasiast** [comment]
OpenRCT2 gained support for new music objects in 2021, and so the old method has been deprecated as it had numerous drawbacks.

The new method is to create a music object (which can easily be done with https://goes.rctspace.com/music ) and to add that to your park using the Object Selection window. This new method allows for more than 2 custom styles and also different styles per park. The music styles will also be exported with the save, just like any other object.

**Comment by jcurbaniak** [comment]
OK, thanks for the help.

 

But this is not working for me.

 

Here is my GOES entry

 



 

 

I placed the result in the OBJECT folder for OPENRCT2.

 



 

But when I run OPENRCT2 the item is not found in the music tab:

 



 

I expected to see Let There Be Drums style.

 

I used Audacity to convert the MP3 file to OGG.

 

Jerry Urbaniak

**Comment by 733737** [comment]
you have to go to oblect selection then advanced then music then check the box next to your music object first in any park you want to use it

**Comment by Gymnasiast** [comment]
@jcurbaniak It looks like you tried to include images, but these probably do not work over e-mail - try uploading them via the GitHub website instead. I would also take a look at 73’s comment - you indeed have to make the object available first. (We are planning on making this easier.)

**Comment by jcurbaniak** [comment]
YES!!  That worked, thanks!!

 

Jerry U.

**Comment by jcurbaniak** [comment]
YES!! That worked.   Thanks a lot!

 

Jerry U.

**Comment by Gymnasiast** [comment]
Good to hear!

I’ll mark the issue as "resolved" then.
