### ISSUE TITLE
helix hitbox too small - allows intersecting tracks

### ISSUE THREAD

**Issue by cheweytoo** [OpenRCT2/OpenRCT2#22169]
### Operating System

Ubuntu Linux 22.04.4

### OpenRCT2 build

2fbfaf2 develop Linux AppImage

### Base game

RollerCoaster Tycoon 2

### Describe the issue

At least some of the helix hitboxes are too small, and allow the building of intersecting tracks without any cheats:

![helix_hitbox_issue](https://github.com/OpenRCT2/OpenRCT2/assets/29800630/22044912-f557-4b8a-a827-b89d6d637f90)

See attached park.

I'm not sure at all if this is a new issue, I haven't done any testing with older builds yet.

### Steps to reproduce

- build corkscrew coaster with helix
- build curve crossing one height unit over high side of helix
- intersecting track gets built without warning

### Attachments

[helix_hitbox_issue.park.zip](https://github.com/user-attachments/files/15846692/helix_hitbox_issue.park.zip)

**Comment by cheweytoo** [comment]
It's not just the corkscrew coaster. I've reproduced it with bobsleigh coaster and wooden coaster as well.

Updated attached park.

**Comment by Gymnasiast** [comment]
This is not easy to fix helices also have to stack. I seem to remember an earlier fix that did more harm than good.

**Comment by cheweytoo** [comment]
I hadn't found that one before, but this issue is probably a duplicate of #16659

**Comment by Gymnasiast** [comment]
Looks like it yeah, closing as duplicate.
