### ISSUE TITLE
Wrong (brown) bridge color

### ISSUE THREAD

**Issue by dezza** [OpenRCT2/OpenRCT2#22177]
### Operating System

Windows 11 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.11 (18d2b5e) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

<img width="285" alt="wrong_bridge_color" src="https://github.com/OpenRCT2/OpenRCT2/assets/402927/e41f0ee9-cd9d-4bd9-90f2-aa79c33caeef">

I believe this bridge is the wrong color, it should be brown like it is shown in-game.

### Steps to reproduce

Open game, open "Factory Capers" scenario.

### Attachments

<img width="285" alt="wrong_bridge_color" src="https://github.com/OpenRCT2/OpenRCT2/assets/402927/70bfecae-80ba-4b64-aea4-1a759021e57d">

**Comment by 733737** [comment]
the bottom square shows the railing style which is independent of the path style.

**Comment by dezza** [comment]
> the bottom square shows the railing style which is independent of the path style.

but you see the bridge is dark brown in-game shown in the same flat position.

I never remember this bridge being the wrong color in the original game, it looked like it does here in-game.

**Comment by 733737** [comment]
The picture is of a railing by itself

**Comment by cheweytoo** [comment]
To state it explicitly: You're building a _combination_ of the selected dark path on top of the selected railing. A "naked" railing without a path cannot be built.

**Comment by 733737** [comment]
thats just how the railing system was implemented
