### ISSUE TITLE
Refactor PTD_OPERATION_ to strong enum

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#22179]
Change these into an enum class called TrackPlaceOperation, with all members being named in `lowerCamelCase`.

`PTD_OPERATION_FLAG_IS_REPLAY` should no longer be shoehorned in - that needs replacing with a bool.

**Comment by mrmagic2020** [comment]
Hey @IeuanHorton, are you still working on this?
