### ISSUE TITLE
"Export plug-in options with saved games" not working

### ISSUE THREAD

**Issue by ndragortt** [OpenRCT2/OpenRCT2#2217]
Correct me if I'm wrong, but is this option supposed to allow you to open saved games that contain object data that's currently not installed on your computer? If so, I've never had any success with opening any saved games containing additional object data. I just get the red error box saying that the saved game cannot be opened due to certain object files not found. Not sure if you guys are still working on this one, but I figured I'd report it. Thanks!

**Comment by janisozaur** [comment]
can you provide such a savegame for testing purposes? If you happen to know what objects were added specifically, can you also name them?

**Comment by ndragortt** [comment]
There are multiple saved games that I've attempted to open but here's one
I'll use as an example. (attached) The exact error message reads
"MWB-PLP4/O554F509827960DB" (it's hard to make out which ones are 0's or
O's). Thanks for looking into this!

**Comment by janisozaur** [comment]
It doesn't look like there's attachment present

**Comment by ndragortt** [comment]
Oops sorry, github doesn't support the file type. Would you like me to email it to you?

**Comment by janisozaur** [comment]
Can you rather post it somewhere? I'd suggest transfer.sh, but it has a limit of 14 days. I've seen people use mediafire, I think, perhaps you could use that?

**Comment by ndragortt** [comment]
Here's a mediafire link I just created:

https://www.mediafire.com/?x44reaxzl6l9oto

**Comment by duncanspumpkin** [comment]
@ndragortt your description of the function is wrong. It means it saves the objects into the save. So the person who gave you that save did not tick that box and therefore the objects are missing. (There are also some objects made with one of the old community tool that are broken and do not normally save properly into a save)
