### ISSUE TITLE
Sorting rides by intensity or nausea is incorrect when value "not yet known" but had a previous rating

### ISSUE THREAD

**Issue by astraylife1** [OpenRCT2/OpenRCT2#22185]
### Operating System

MacOS

### OpenRCT2 build

OpenRCT2, v0.4.11 (71a8eee on develop)

### Base game

RollerCoaster Tycoon 2

### Describe the issue

If you have a ride that received ratings, but then you go and edit the ride so that the stats are not calculated again, the ride does not sort correctly in the Ride/Attractions list. When sorting by excitement the ride drops to the bottom of the list with a value "Not Yet Known". But for intensity and nausea sorting, the ride maintains its original place from the previous calculated stats but displays "not yet known". The ride should drop to the bottom of the list but this does not happen for intensity and nausea.

### Steps to reproduce

Change lift speed for existing coaster
Sort by intensity or nausea in the ride list
Ride fails to drop to the bottom of the list

### Attachments

<img width="575" alt="rides" src="https://github.com/OpenRCT2/OpenRCT2/assets/98492730/412114ec-5c9d-459f-b095-a815ed6d4b71">

**Comment by lewyche** [comment]
I managed to recreate this issue on windows. I'm going to try to fix it.
