### ISSUE TITLE
scenario goals are wrong

### ISSUE THREAD

**Issue by tom-brouhon** [OpenRCT2/OpenRCT2#22186]
### Operating System

windows 11, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.8 (05efdb2) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

The bug also exists in the original game (RCT2/RCTC)

### Describe the issue

scenario goals are changed & unbeatable

### Steps to reproduce

1) select scenario
2) already lost the game

### Attachments

![Schermafbeelding 2024-06-23 113206](https://github.com/OpenRCT2/OpenRCT2/assets/173602672/894ea10d-254e-464a-a1d0-418415d2c3eb)

**Comment by tom-brouhon** [comment]
Multiple scenario's have the same issue
![Schermafbeelding 2024-06-23 114114](https://github.com/OpenRCT2/OpenRCT2/assets/173602672/ca2967b1-6a7e-46f5-841f-710c96fe104d)

**Comment by James103** [comment]
Have you tried updating to the latest release or develop and then opening a scenario?

**Comment by Gymnasiast** [comment]
**Always** update to the newest develop (not release, despite what James says, **develop**) and then test before reporting. You are several versions behind.
