### ISSUE TITLE
large water edit cursor disappears when overshooting some park edges

### ISSUE THREAD

**Issue by cheweytoo** [OpenRCT2/OpenRCT2#22209]
### Operating System

Ubuntu Linux 22.04.4

### OpenRCT2 build

a0f5d09 develop Linux AppImage

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

For two of the four park edges, a large water edit cursor will disappear as soon as it overshoots that edge by more than one tile:

https://github.com/OpenRCT2/OpenRCT2/assets/29800630/1ba1865f-4cae-4cb3-8db7-9aaff59fbcd3

This is independent of zoom level, and seems to be specific to the water cursor only.

### Steps to reproduce

- enable large water cursor
- move it so that it overshoots a park edge
- on two of the four edges, cursor will disappear as soon as the overshoot is _more_ than one tile

**Comment by MASHzj** [comment]
It is at the two edges where one coordinate is 0. So the cursor probably can't handle negative coordinates.

**Comment by cheweytoo** [comment]
Yay for easier coast-on-edge building – thanks!
