### ISSUE TITLE
Korean texts are incorrectly shown in some tooltips

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#2221]
Some long tooltips are displayed wrong in korean. For instance,
correct one(english): This is a tooltip of long options that blah blah texts. You may translate it.
incorrect one(korean): This is a tooltip of (newline) blah texts. You may translate (newline) This can be changed by blah blah

Precisely speaking, not all tooltip texts are shown in the tooltip box in korean.
And some not related texts are also displayed together.

This issue occurs for some tooltips, not for all.

Sample image:
![Tooltip text](http://file.telk.kr/rct/img/err_in_korean_03.png)

**Comment by zzoru** [comment]
It seems that utf8's small font not work on Korean, i am checking this now, but i don't have a lot of time to do.

**Comment by telk5093** [comment]
Add: I think the length of translated string is the reason why this issue occurs.
If the translated strings are too long, then this issue occurs.
It doesn't if I shorten the translated string.

**Comment by Gymnasiast** [comment]
Does it help if you insert {NEWLINE} at places where it's cut off?

**Comment by telk5093** [comment]
Oh, it works.
Do you have any idea how much bytes can be stored in a one line?

**Comment by IntelOrca** [comment]
It depends on the font size, it limits the width of the tooltip to 196 pixels. This is just original behaviour, no improvements have been done in the way of tooltips.

**Comment by telk5093** [comment]
I think it will be great to develop the fitted tooltip box as the length of tooltip someday :)
