### ISSUE TITLE
Blocked By Brakes On Test Run

### ISSUE THREAD

**Issue by jcurbaniak** [OpenRCT2/OpenRCT2#22212]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.11 (18d2b5e) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

On a test run for "Tempest" a downloaded bobsled coaster with three block sections, the test run fails immediately with "Blocked By Brakes" as the first car reaches the top of the lift.   There are just 3 trains with 1 car each.  I do not seem to be able to reset the test mode with a close and test recycle.  I have taken a screenshot.

### Steps to reproduce

1.  Build or download a ride with block sections.
2.  Start a Test run.

### Attachments

![Blocked by Brakes](https://github.com/OpenRCT2/OpenRCT2/assets/134623850/d10d1e29-03bc-4ba9-9b99-569abd07629b)

**Comment by mrmagic2020** [comment]
I can't seem to reproduce this bug. Are you sure the vehicles aren't just temporarily blocked by the brakes? Could you attach the ride design as well?

**Comment by jcurbaniak** [comment]
Maybe just a bad design?  I did not alter the track in any way.

 

Also here are my settings.

 

The ride is “frozen”.   Close does not do anything.   Test does not do anything as the cars remain stuck in place.

 

Jerry Urbaniak

**Comment by jcurbaniak** [comment]
I have some more information on the Tempest ride.    

 

With a Test of a single car there is no brake stoppage, but the car never completes the track as it gets stuck moving back and forth in the lower portion of the ride.

 

Apparently not enough momentum.

 

With a Test of 2 cars the second car is stopped by brakes at the top of the lift.

 

In short, this ride DOES NOT WORK. 

 

I would say do not spend anymore time on it.

 

Jerry Urbaniak

 

From: ***@***.*** ***@***.***> 
Sent: Sunday, June 30, 2024 9:16 AM
To: 'OpenRCT2/OpenRCT2' ***@***.***>
Subject: RE: [OpenRCT2/OpenRCT2] Blocked By Brakes On Test Run (Issue #22212)

 

Maybe just a bad design?  I did not alter the track in any way.

 

Also here are my settings.

 

The ride is “frozen”.   Close does not do anything.   Test does not do anything as the cars remain stuck in place.

 

Jerry Urbaniak

**Comment by cheweytoo** [comment]
> a bobsled coaster with three block sections […] There are just 3 trains with 1 car each.

@jcurbaniak: There's your problem: A coster with N block sections can have at most N-1 trains: A train will only continue into a block section that _**does not**_ already contain a train. If there's a train in every block section, none of the trains can move beyond the block brake at the end of their section.

**Comment by jcurbaniak** [comment]
Test also fails with only 2 trains.

 

The second train stops at the top of the lift.

 

With one train the test never completes.    It gets stuck in the lower portion of the ride going back and forth.

 

I have deleted the Tempest ride from my park.
