### ISSUE TITLE
Delayed staff menu

### ISSUE THREAD

**Issue by forgetfulhermitcrab** [OpenRCT2/OpenRCT2#22222]
### Operating System

windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.11 (18d2b5e) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

Whenever I select a tab in the staff drop down menu, it delays showing all staff in the tab by around 1 second unless I hover over the staff in the menu, wait a second, or click another tab. If I click another tab, the bug persists but just shows the previous tabs staff for a second. 

Attached is a video of my issue, where you can see the physical delays.

### Steps to reproduce

1. Select the staff dropdown menu.
2. While you have hired workers, select another tab.
3. The staff will visually be different then the menu that is selected.

### Attachments

https://github.com/OpenRCT2/OpenRCT2/assets/107830256/3d22e300-90e2-45b7-8081-988bd9d79a84

**Comment by mrmbernardi** [comment]
Likely window invalidation code.
