### ISSUE TITLE
Scroll bar scales wrong in -1x-1 sized park

### ISSUE THREAD

**Issue by MaxMallon** [OpenRCT2/OpenRCT2#22225]
### Operating System

Win 11

### OpenRCT2 build

Latest Dev (4-12-2023)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

I edited the safe file to create a park that displays as -1x-1 in the map. In doing so I noticed the scrollbar was broken. This might be due to some other issue, and hence the bug report here. 

### Steps to reproduce

Open park, see map, see scroll bar

### Attachments

[-1x-1ParkNoCS.zip](https://github.com/user-attachments/files/16110051/-1x-1ParkNoCS.zip)

**Comment by MaxMallon** [comment]
Someone pointed out that it didn't happen for them. Upon testing, it appears to only happen in OpenGL mode, not Software mode.

**Comment by 733737** [comment]
I apologize for creating the issue before you

**Comment by Gymnasiast** [comment]
Discussion has revealed that most team members prefer clamping the map size to 1×1 during import.
