### ISSUE TITLE
Log Flume with 1.27 nausea makes every guest sick

### ISSUE THREAD

**Issue by mynameiskrysta** [OpenRCT2/OpenRCT2#22245]
### Operating System

Windows 10 Pro

### OpenRCT2 build

OpenRCT2, v0.4.12 (1b5ff88) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Every guest after riding a log flume with 1.27 nausea has 100% nausea

### Steps to reproduce

1. Load Hydro Hills scenario, 2. recreate log flume in place. I'm not sure if that actually will recreate it or if this is a more specific glitch than that

### Attachments

![Hydro Hills 2024-07-07 21-23-30](https://github.com/OpenRCT2/OpenRCT2/assets/104466722/6b3f84a8-1bca-4acb-8bce-a5bcd4bba3c8)

**Comment by mrmbernardi** [comment]
It's better if you could attach the game save file.

**Comment by mynameiskrysta** [comment]
So I redid the flume after I submitted that, and it turned out all log
flumes that I made had the same effect, so I used the cheat to set guests’
nausea to min so I could continue playing. I don’t think there’s a way to
undo it, would attaching the save file still work?

**Comment by mrmbernardi** [comment]
Definitely, the first step for us is to open up the game exactly as you have it.

**Comment by beesman93** [comment]
Recreated on v0.4.12 (1b5ff88) - save file is attached in the zip:

[Hydro Hills Nausea Bug.zip](https://github.com/user-attachments/files/16201863/Hydro.Hills.Nausea.Bug.zip)

Opened park, build Logger's Revange preset log fume ride, did advertisments, sped up the game for couple weeks - all who've been on the ride feel very sick - bizzare bug indeed.

![20240713124937_1](https://github.com/user-attachments/assets/142b075c-4952-466b-9a5e-8fc23de5d0c3)

**Comment by beesman93** [comment]
And another save before the first guest enters a ride:
[Hydro Hills Nausea Bug before guests ride.zip](https://github.com/user-attachments/files/16201893/Hydro.Hills.Nausea.Bug.before.guests.ride.zip)
there is something even weirder going on; when you let the game run from this save, all guests on the ride are getting sick as we established, but even weirder - I noticed **guests are getting sick even in the queue** - guests that didn't ride any rides yet - so it's not residual nausea from riding the log fume before that.
And after a while the nausea bug goes away - little after the point where the log fume gets the nausea rating but not exactly at that point.

**Comment by beesman93** [comment]
[Coaster Canyon Nausea Log Fume.zip](https://github.com/user-attachments/files/16201923/Coaster.Canyon.Nausea.Log.Fume.zip)
And recreated on Coaster Canyon - so it's not Hydro Hills specific

**Comment by beesman93** [comment]
[Bumbly Beach 2y test nausea bug.zip](https://github.com/user-attachments/files/16201931/Bumbly.Beach.2y.test.nausea.bug.zip)

And lastly tested on old bumbly beach save that was already in late year 2 - with custom Log Fume, bug also present:
![image](https://github.com/user-attachments/assets/efcb5040-2047-4c40-a22e-ffc0681210d8)

In conclusion:

- Any guest riding Log Fume ride (custom, prebuild - doesn't matter) before it gets its ratings is getting nausea at very fast rate
- It is not map specific
- It is not only at the beginning of a scenario
- Seems easy to replicate - build any log fume, open it, watch guests getting sick before first log makes it around the ride.

**Comment by beesman93** [comment]
Will test further in the evening - maybe testing an older version of OpenRCT to figure out if it was always broken or was broken by some changes, seems like that would be easiest way to pinpoint it if that's the case.
Anyway will try to find the bug and attempt a fix if I can, if someone else is already looking into it feel free to stop me or give pointers if you have theories why/when it could go wrong.

**Comment by beesman93** [comment]
Oh yeah...
`nausea = kRideRatingUndefined;`
...
`constexpr ride_rating kRideRatingUndefined = 0xFFFFu;`

so indeed #22199 change is the reason basically:

Any untested ride and ride which gets it's ratings reset is now Nausea rating 65535 :)
I suggest to revert this change until we make a better fix, putting rides on the list correctly without affecting gameplay mechanic.
