### ISSUE TITLE
Change mountain tool to ignore higher surrounding tiles

### ISSUE THREAD

**Issue by runelaenen** [OpenRCT2/OpenRCT2#2225]
https://openrct.net/forum/topic/632/last/smoothing-landscape

Hi everyone,
The mountain tool is a nice addon but when I use it like
the pictures below then something strange happens :(

1) http://i.imgur.com/KELaRNH.png
2) http://imgur.com/cPy3gpB

So maybe make an checkbox or button or something
that ignores the edges of higher plateau/land.

**Comment by e-foley** [comment]
I just confirmed that this behavior is consistent with the original RCT2.  It's really hard to say what the land ought to do in this situation.

**Comment by HaasJona** [comment]
Related to #2127. I guess we "just" need to rewrite the mountain tool. In this case, I think the following should happen:

![bildschirmfoto von 2015-11-07 21-45-16](https://cloud.githubusercontent.com/assets/4310707/11017219/f7dab4fa-8598-11e5-9b58-657118224a3a.png)

We could also create a tool that smooths vertical surfaces.

**Comment by e-foley** [comment]
Would we be able to give this issue a more precise title to differentiate it from #2068, #2127, and #2229?

**Comment by zornor** [comment]
It's probably worth noting that this also happens to tiles below your target tile; i.e. you lower a tile on a higher plateau and some tiles below will become jagged like OP's second picture.
