### ISSUE TITLE
Blizzard/Heavy Snow has guests open umbrellas 

### ISSUE THREAD

**Issue by thegreatprophetzarquon** [OpenRCT2/OpenRCT2#22261]
### Operating System

Windows 11

### OpenRCT2 build

OpenRCT2, v0.4.12 (1b5ff88) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

In game

### Describe the issue

Snowy weather effects have been introduced to OpenRCT2 and the [latest version](https://github.com/OpenRCT2/OpenRCT2/pull/21986) makes guests buy and use umbrellas when there is heavy snow and blizzard weather, just like rain,

As a midwesterner who lives in a place with snowy winters, I agree with the comment on the [original issue](https://github.com/OpenRCT2/OpenRCT2/issues/20240) that prompted this change: I have never seen anyone open an umbrella in the snow at all. Umbrellas primarily protect against getting wet, and while I can see how they might be useful if the flakes are wet and sticky, in practice (when outfitted with winter clothing) no one does this, certainly not en mass as implemented. In a blizzard, they would be especially useless in the wind.

This change should be reverted. (More realistic behavior would be snow prompting ski masks and winter hat sales, but the hats in RCT are not a good analog for this).

### Steps to reproduce

1. Switch weather to heavy snow/blizzard
2. Watch guests open and purchase umbrellas like weird pod people.

**Comment by lewyche** [comment]
Maybe the alteration label would be a better label for this issue?

**Comment by AaronVanGeffen** [comment]
It is a bit questionable for a blizzard, I agree. Arguably, the use of umbrellas during a thunderstorm is questionable as well. However, I stand by it being fine for (light) snow.

**Comment by thegreatprophetzarquon** [comment]
It's not so much that people _couldn't_ use an umbrella in light snow, it's that they don't. At all. Do you live in a snowy region where they do this? This just doesn't happen in the US. The rain behavior in RCT is based on need: they will pay anything for an an umbrella in a rainstorm as it's incredibly useful. Heavy rain in a real park would prompt similar behavior. No one is ever going to pay hefty prices for an umbrella to use when it's snowing.

**Comment by 733737** [comment]
I really don't think this is a major gamebreaking issue

**Comment by AaronVanGeffen** [comment]
> It's not so much that people couldn't use an umbrella in light snow, it's that they don't. At all. Do you live in a snowy region where they do this?

Well, this is an entirely arbitrary anecdote, but *I* have used an umbrella in snowy weather. It makes a surprising difference!

**Comment by thegreatprophetzarquon** [comment]
I'm sure it does make a difference; sounds very pleasant. But it underscores that this would not be expected mass behavior in a park. I've lived my whole life in the snow and you would be the first I'd known to do this.

**Comment by cheweytoo** [comment]
> It's not so much that people _couldn't_ use an umbrella in light snow, it's that they don't. At all. Do you live in a snowy region where they do this?

Yes, I do live in a snowy region where pretty much everybody uses umbrellas when it snows. Umbrellas keep stuff falling from above from hitting you, regardless of the stuff's state of matter.

But then, I'm also the reason this has been changed in OpenRCT2: https://github.com/OpenRCT2/OpenRCT2/issues/20240

**Comment by thegreatprophetzarquon** [comment]
Where do you live, may I ask? I don't doubt it, but I've never seen it in the US.

**Comment by cheweytoo** [comment]
> Where do you live, may I ask?

Not in the US :-)

Adding "umbrella" to the search term is biasing the results of course, but still:
https://www.google.com/search?q=people+snowing+umbrella+london&udm=2
https://www.google.com/search?q=people+snowing+umbrella+paris&udm=2
https://www.google.com/search?q=people+snowing+umbrella+berlin&udm=2
https://www.google.com/search?q=people+snowing+umbrella+helsinki&udm=2

And then there's this guy complaining about _Canadians_ using umbrellas in the snow, with pictures:
https://dailyhive.com/vancouver/opinion-umbrellas-for-snow-vancouver

Also, for once, quora is slightly useful:
https://www.quora.com/Why-do-people-use-umbrellas-when-it-rains-but-not-when-it-snows

Regarding OpenRCT2, I have no strong opinion either way (although I _am_ pro-umbrella, obviously), but I think there's enough real-world precedent.

**Comment by thegreatprophetzarquon** [comment]
If anyone who lives in the UK (I think following the country of origin makes sense) chimes in that this would be a common enough behavior there (and we do have photos, so I think it could be the case), then I'd be satisfied. It's still utterly alien to me, the US is definitely in the same camp as the Vancouver article you linked.
