### ISSUE TITLE
Switching track type doesn't keep the UI pressed

### ISSUE THREAD

**Issue by karst** [OpenRCT2/OpenRCT2#22265]
### Operating System

Windows 10, 64-Bit

### OpenRCT2 build

OpenRCT2, v0.4.12-4-g376e749 (376e749 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Describe the issue

Probably introduced recently with turning covered pieces into their own track type instead of a track element.
When you are building a dingy slide/water coaster, the UI doesn't have the chosen track type pressed. 
In RCT2 it does have the chosen track type pressed permanently.

### Steps to reproduce

1. Build a dingy slide
2. Switch the track type from open to covered or visa versa. 
3. Watch how the chosen button doesn't stay visually selected.

**Comment by lewyche** [comment]
Looks like changing `pressed_widgets` to `pressedWidgets` solves the issue, but im going to do a bit a more testing before making a PR.
(https://github.com/OpenRCT2/OpenRCT2/blob/3467760ef80dae2941c59ad6367f257167dee204/src/openrct2-ui/windows/RideConstruction.cpp#L2106C1-L2114C1)
