### ISSUE TITLE
zoomed-out view leads to extremely high CPU load in OpenGL mode

### ISSUE THREAD

**Issue by cheweytoo** [OpenRCT2/OpenRCT2#22271]
### Operating System

Ubuntu Linux 22.04.4

### OpenRCT2 build

0b01120 develop, Linux AppImage

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

Just zooming out fully leads to very high CPU load (basically four fully saturated cores) when using OpenGL render mode:

https://github.com/OpenRCT2/OpenRCT2/assets/29800630/6d37fa46-1fd7-4ec0-bcbc-24533d0403c7

- This does not happen in non-OpenGL modes
- This happens with a completely empty park (see attachment)
- It is almost independent of park size: With a tiny 45×45 park, CPU load is maybe 10% lower than with a 500×500 park
- This happens even when the game is paused
- It scales very slightly with the "window scale factor" setting: It's already high with a factor of 1.0, but higher scale factors mean higher CPU loads – it seems to hit a ceiling at a scale factor of about 1.75 though.
- It depends on window size: Smaller game windows have noticeably lower (but still insanely high for "doing nothing" in an empty park) loads.

Having actual park content has no influence: Even fully zoomed out Imagination Megapark (255×255) has a lower CPU load than the empty 500×500 park.

I went through some old releases:
- This issue is not yet present in version 0.4.5.
- This issue _is_ present in version 0.4.6.

### Steps to reproduce

Open attached park using OpenGL render mode and with a large-ish game window.

### Attachments

[empty_500.park.zip](https://github.com/user-attachments/files/16177037/empty_500.park.zip)

**Comment by ZehMatt** [comment]
I think 0.4.6 turns on multi-threading by default now, while it increases CPU load you should see an increase in FPS as well, its best to enable vsync to keep it at screen refresh rate.

**Comment by cheweytoo** [comment]
Good point. Vsync has been enabled for all my tests.

I turned on the fps display, all tests with the empty 500×500 park:

In version 0.4.5, I get ~7-9 fps fully zoomed out in OpenGL mode (with one CPU core at 100%), 40fps in software mode.
In version 0.4.6+, I get ~13-16 fps fully zoomed out in OpenGL mode (with 4 CPU cores at 100%), 40fps in software mode.

Is this just OpenGL being really, really CPU hungry?

**Comment by James103** [comment]
1. Have you tried this without multithreading?
2. What is the make and model of the CPU and any GPUs you have on the computer you are testing on?
3. Do you get significantly higher GPU usage with OpenGL renderer compared to "Software (hardware display)"?

My testing on ae9ebe9 with a fully zoomed out Forest Frontiers park at scenario start shows the following:
* With the software (hardware display) renderer, OpenRCT2 is responsible for about 5-10% CPU usage and 16% GPU usage.
* With the OpenGL renderer, OpenRCT2 is responsible for around 40-45% CPU usage and 30-35% GPU usage.
* CPU: Intel i5-9400F, 2.90 GHz base clock
* GPU: Nvidia GTX 1660

Disabling multithreading:
* Has almost no effect on CPU/GPU usage or FPS with the software (hardware display) renderer.
* Reduces both CPU and GPU usage to around 20-30% with OpenGL renderer, but reduces FPS to around 40 (out of 60).

**Comment by cheweytoo** [comment]
1. Without multithreading, the OpenGL fps drop from ~16 to 8.
2. Intel i7-6700 with no external GPU, so Intel HD Graphics 530
3. No. Funnily enough, "software (hardware display)" has a slightly higher GPU load percentage of ~44-46% vs. OpenGL 42-44%, and a _much_ higher clockrate of ~900MHz vs. OpenGL at 650-700MHz. (numbers via intel_gpu_top)

Disabling multithreading
- drops OpenGL-mode CPU load from 400% to ~100% (and GPU load to ~25%)
- reduces "software (hardware display)" CPU load from about 100% to ~75%, has no effect at all on GPU load (~46%), fps stay at 40.

With all of that, I'm leaning towards "OpenGL on Intel graphics stinks".

**Comment by ZehMatt** [comment]
This is a somewhat known problem that OpenGL doesn't do too well on larger maps as it doesn't support invalidation like the software renderer, I've tried to implement it but there are some puzzling issues that I never quite figured out.

**Comment by cheweytoo** [comment]
So: Not a bug as such, but just annoying?

**Comment by ZehMatt** [comment]
> So: Not a bug as such, but just annoying?

Well not exactly a bug but its also not ideal, it works a lot better with a dedicated GPUs but for integrated ones its really pushing it, so I'll be closing this.
