### ISSUE TITLE
Starting land- or water-moving operations off map causes strange behavior when cursor returns to map

### ISSUE THREAD

**Issue by e-foley** [OpenRCT2/OpenRCT2#2228]
This is another bug that afflicts both the original RCT2 as well as OpenRCT2 (tested in build 1421).
1. Open either the land tool or the water tool.
2. Click and hold on the black void off the map.
3. While still holding the mouse, bring the cursor to land you own.

You'll notice as you drag the mouse around that the tool tries to be in its cursor mode and landscape-modification mode simultaneously.  You can create really ugly designs like this if you want to:

![scr24](https://cloud.githubusercontent.com/assets/6338134/11017349/18275508-8551-11e5-930b-02db877e8432.png)

**Comment by Broxzier** [comment]
The same thing happens when you're zoomed out and hover the cursor over a pixel that doesn't hit any tiles. I actually use this trick to randomize mountains easily.

**Comment by tupaschoal** [comment]
This was fixed between v0.2.6 and v0.3.0, likely by #11179, so closing as resolved
