### ISSUE TITLE
Opening .sv6 files by double clicking them in windows often fails

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#22294]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2 0.4.12-2

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

If Windows is set to use OpenRCT2.exe to open .sv6 files, it often fails and will tell you some objects are missing. It most likely has to do with the new loading sequence. When opening OpenRCT2 first and then loading .sv6 files from within, it will succeed.

![image](https://github.com/user-attachments/assets/c184948a-8265-479b-a2e3-e52e38601a20)

### Steps to reproduce

Set OpenRCT2.exe as default program for opening .sv6 files in Windows.
Double-click an .sv6 file in windows.

**Comment by James103** [comment]
Do you get similar "missing objects" behavior when you use the terminal to run `openrct2` and tell it to load the relevant save file?
For example: `.\openrct2 save.sv6`, where `save.sv6` is the full path to the save file you're trying to load.

I can't reproduce the behavior from the command line on ae9ebe9, 4356ae4, and the 0.4.12 release.

**Comment by ZehMatt** [comment]
Tagging @AaronVanGeffen

**Comment by deurklink** [comment]
> Do you get similar "missing objects" behavior when you use the terminal to run `openrct2` and tell it to load the relevant save file? For example: `.\openrct2 save.sv6`, where `save.sv6` is the full path to the save file you're trying to load.
> 
> I can't reproduce the behavior from the command line on [ae9ebe9](https://github.com/OpenRCT2/OpenRCT2/commit/ae9ebe97d4567cfd42392084822337b8436b3e05), [4356ae4](https://github.com/OpenRCT2/OpenRCT2/commit/4356ae4f5efedbcfc908399786c94c860e49fed5), and the 0.4.12 release.

When I open through command line interface I don't get any issues, it's only when I double-click the .sv6 file.

**Comment by AaronVanGeffen** [comment]
Oh no, I thought we'd fixed this. Was this fine before #22230?

**Comment by deurklink** [comment]
It turns out .sv6 files on my computer were associated with an older build of OpenRCT2, and Windows was pretty persistent in continuing to link to that old location, even if I set it to use the newer build for opening .sv6 files.. Only removing the other executable and then making a new association finally helped. I'll close the issue, as it was something on my PC!

It works perfectly fine again!
