### ISSUE TITLE
Mountain tool only charges for scenery removed at cursor

### ISSUE THREAD

**Issue by e-foley** [OpenRCT2/OpenRCT2#2229]
Yes, more issues with the mountain tool...

If using the mountain tool causes scenery to be removed, you'll only be charged/refunded for the scenery at the mountain tool's cursor.  I'm not sure if this is consistent with RCT1 or not.  I tested this in OpenRCT2 build 1421.

![trees](https://cloud.githubusercontent.com/assets/6338134/11017427/6bd95276-8553-11e5-9596-1d9f561fe705.png)
![trees_after_mountain](https://cloud.githubusercontent.com/assets/6338134/11017428/6d1d097a-8553-11e5-8f5a-f0bd41c1de89.png)
![trees_2](https://cloud.githubusercontent.com/assets/6338134/11017429/6e8efade-8553-11e5-8d5d-575b1764410a.png)
![trees_after_mountain_2](https://cloud.githubusercontent.com/assets/6338134/11017430/70edda48-8553-11e5-91c3-8b197a6fe979.png)

**Comment by HaasJona** [comment]
RCT1 mountain tool ignores tiles with scenery on them
