### ISSUE TITLE
Bug with the Reliability and Down-Time Bars

### ISSUE THREAD

**Issue by 60trainhunter** [OpenRCT2/OpenRCT2#22292]
### Operating System

Windows 11

### OpenRCT2 build

OpenRCT2 v0.4.12-4356ae4 develop

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

Bug with the Reliability and Down-Time Bars. The Bars show incorrect data for some reason. I don't know if anyone else gets this or not.

### Steps to reproduce

Go to ANY Park that already has rides already prebuilt in them. Check the rides' Reliability and Down-Time Bars. The main park that i see this bug in is Crumbly Woods with Older Rides. Take Note of Mean Squeak in screenshot.

### Attachments

![Crumbly Woods 2024-07-13 22-11-34](https://github.com/user-attachments/assets/3ccab1f4-c018-4152-a23a-f7964a827a8c)

**Comment by beesman93** [comment]
A little testing suggests to me it breaks only when multiple rides inspection windows are opened, even for new rides the bars jump all over the place - specially visible when opening a new window to that tab or closing one, all others get messed up.

**Comment by ZehMatt** [comment]
I suspect this has to do with the fact that every widget definition is shared for multiple windows so they all share the same state. The reason it works mostly fine is that each window has an `onPrepareDraw` which is called prior to drawing the window which updates the data on the widgets. So if you are interested in working on this that's where I would start.

**Comment by beesman93** [comment]
> I suspect this has to do with the fact that every widget definition is shared for multiple windows so they all share the same state. The reason it works mostly fine is that each window has an `onPrepareDraw` which is called prior to drawing the window which updates the data on the widgets. So if you are interested in working on this that's where I would start.

Yeah I digged around there but it's little too complex to learn the in and outs of it, sadly not much time today - attempted to onPreprareDraw after new progbar vals are set and debug to see the chain of events, but didn't resolve the issue, and I think the fix will have to be done very carefully to not hinder performance (even if it would be performance only when maintenance tab(s) are open.

So if nobody works on it this week, I will try next weekend.

**Comment by tmatale** [comment]
Doing some research on this and it appears this is true for other instances of progress bars as well. For example, if you click on the guests information tab that shows the guests' needs, it draw the progress bars incorrectly if more than one guest window is open.

**Comment by tmatale** [comment]
I added a PR for this issue: #22399
