### ISSUE TITLE
Assertion failed in v0.4.12 on Windows ARM64

### ISSUE THREAD

**Issue by h1v9** [OpenRCT2/OpenRCT2#22297]
### Operating System

Windows 11 Arm64

### OpenRCT2 build

v0.4.12 from releases on website

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs, This is a development issue

### Describe the issue

![openrct2_UCNRB5s2wh](https://github.com/user-attachments/assets/58099d3d-42eb-4438-9314-aace00941f05)

Fastest way to reproduce the issue is to wait in the main menu with OpenRCT2 intro.
I was able to see the issue appear when the game loads PKEMM.dat, from verbose mode.
Whatever action you choose in the dialog more and more assertion error "Tried getting entity XXXX" keep appearing.

v0.4.11 works without any issue

PC is a Lenovo Yoga 7x with Snapdragon X elite

### Steps to reproduce

1. Start the game
2. Wait in the main menu

**Comment by James103** [comment]
Can you please try reproducing this from the [latest develop](https://openrct2.org/downloads/develop/latest)?

**Comment by Vadhvis** [comment]
![WindowsTerminal_hmjLywBW4e](https://github.com/user-attachments/assets/6bb5c57e-00dd-4788-b9b3-f3f66403092d)

Problem persists with the latest develop
I also had to get g2.dat from the X64 build as it was missing from Arm64 zip

**Comment by Coasterfreak212** [comment]
Wanted to report that I have experienced this same issue. It occurs both in the latest Develop and the base. I'm using the Steam version of RCT2 instead of GOG. Also X Elite, the Surface Pro 11.

**Comment by Coasterfreak212** [comment]
Sorry for the double post, but just wanted to report that the issue has seemed to have gone away so far on build 0.4.14! At least, I was able to do a full cycle of the intro without it crashing endlessly with assertion failed.

Not sure if it was something in the new build or if an update on the Surface Pro/Snapdragon X Elite addressed it.
