### ISSUE TITLE
Game crash when switching from "Software" to "Software (Hardware display)"

### ISSUE THREAD

**Issue by Basssiiie** [OpenRCT2/OpenRCT2#22316]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.12-60-g461b4b9 (461b4b9 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

My game crashes when I switch from the "Software" to the "Software (Hardware display)" drawing engine.

I get the following output in my stdout:
```
WARNING[D:\a\OpenRCT2\OpenRCT2\src\openrct2-ui\drawing\engines\HardwareDisplayDrawingEngine.cpp:103 (HardwareDisplayDrawingEngine::Resize)]: HWDisplayDrawingEngine::Resize error: Parameter 'renderer' is invalid
```
The second attempt also generated a crash with dump, along side more warnings and errors (probably because of the first warning):
```
WARNING[D:\a\OpenRCT2\OpenRCT2\src\openrct2\core\Imaging.cpp:55 (Imaging::PngWarning)]: Image width is zero in IHDR
WARNING[D:\a\OpenRCT2\OpenRCT2\src\openrct2\core\Imaging.cpp:55 (Imaging::PngWarning)]: Image height is zero in IHDR
ERROR[D:\a\OpenRCT2\OpenRCT2\src\openrct2\core\Imaging.cpp:60 (Imaging::PngError)]: Invalid IHDR data
openrct2 $ libpng error: Invalid IHDR data
ERROR[D:\a\OpenRCT2\OpenRCT2\src\openrct2\interface\Screenshot.cpp:73 (WriteDpiToFile)]: Unable to write png: PNG ERROR
```

### Steps to reproduce

1. Open Options.
2. Select "Software" drawing engine.
3. Select "Software (Hardware Display)" drawing engine.
4. Crash.

Surprisingly enough everything works fine if I switch from OpenGL to "Software (Hardware Display)".

### Attachments

[crash.zip](https://github.com/user-attachments/files/16255428/crash.zip)

**Comment by cheweytoo** [comment]
This seems to be OS-specific: I see no crash with the Linux AppImage build, from 3467760 develop.
