### ISSUE TITLE
Incorrect tooltips on nonstandard water colors

### ISSUE THREAD

**Issue by e-foley** [OpenRCT2/OpenRCT2#2231]
Tested in build 1421.  I assume it's not easy to change the tooltips based on water color, so maybe calling them something like "dark water" and "light water" would be the most general fix?

![totally_teal](https://cloud.githubusercontent.com/assets/6338134/11017579/a25ebe9e-8558-11e5-9af3-b8e031fe07df.png)
![totally_aquamarine](https://cloud.githubusercontent.com/assets/6338134/11017583/be0bae5e-8558-11e5-8ba8-53525ea5ebea.png)

Also, are tooltips on colors a feature that's new to OpenRCT2?  I can't get them to show in the original game.

**Comment by Gymnasiast** [comment]
They're introduced by OpenRCT2. Since water is an object, I would prefer using 'dark water' and 'light water', since that doesn't require hard coding.

**Comment by osconnoisseur** [comment]
Would it be possible for the water color setting to only change the color of the water, and not do a global palette swap like it appears to be doing currently?

**Comment by Gymnasiast** [comment]
@osconnoisseur : I think it does this in order to properly change all water colours, including those in scenery and rides. Like this:

![scr129](https://cloud.githubusercontent.com/assets/1478678/11019579/03b13882-8600-11e5-8acf-d5502d518d41.png)
