### ISSUE TITLE
Game crashes when printing ui in console while tool is active

### ISSUE THREAD

**Issue by Sadret** [OpenRCT2/OpenRCT2#22339]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.12-76-g58e4a50 (58e4a50 on develop)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

The game crashes when printing `ui` or `ui.tool` in the console while a tool is active. The tool can be custom or non-custom. It is not an issue with `ui.tileSelection`: the game does not crash when no tool is active but there is a tile selection, and the game does crash when there is a tool active that does not use tile selection.

### Steps to reproduce

1. run OpenRCT2 from console
2. start a scenario and activate a tool (tested: land tool, scenery colour brush, footpath tool, custom tool)
3. type `ui` or `ui.tool` in the console (from which you ran the game) and press enter

### Attachments

[80337211-0d91-4552-9992-83148ef3361c(76b5565_x86-64).dmp.gz](https://github.com/user-attachments/files/16310166/80337211-0d91-4552-9992-83148ef3361c.76b5565_x86-64.dmp.gz)

**Comment by mrmbernardi** [comment]
I can't reproduce it. DO you have more info about your setup?

![image](https://github.com/user-attachments/assets/d025c388-dbcd-4c25-8911-756c2c1e7b4b)

**Comment by cheweytoo** [comment]
Additional data point: No crash either with the Linux AppImage build of 58e4a50.

**Comment by Sadret** [comment]
Not the in-game console, but the one you started the game from.

**Comment by cheweytoo** [comment]
> Not the in-game console, but the one you started the game from.

Oh!

Well – No crash either:

```
openrct2 $ ui
{ height: 1185,
  width: 1945,
  windows: 6,
  mainViewport: 
   { left: 6548,
     top: -96,
     right: 8493,
     bottom: 1089,
     rotation: 3,
     zoom: 0,
     visibilityFlags: 1056965760,
     getCentrePosition: [Native Function],
     moveTo: [Native Function],
     scrollTo: [Native Function] },
  tileSelection: 
   { range: null,
     tiles: [] },
  tool: null,
  imageManager: 
   { getPredefinedRange: [Native Function],
     getAvailableAllocationRanges: [Native Function],
     allocate: [Native Function],
     free: [Native Function],
     getImageInfo: [Native Function],
     getPixelData: [Native Function],
     setPixelData: [Native Function],
     draw: [Native Function] },
  openWindow: [Native Function],
  closeWindows: [Native Function],
  closeAllWindows: [Native Function],
  getWindow: [Native Function],
  showError: [Native Function],
  showTextInput: [Native Function],
  showFileBrowse: [Native Function],
  showScenarioSelect: [Native Function],
  activateTool: [Native Function],
  registerMenuItem: [Native Function],
  registerToolboxMenuItem: [Native Function],
  registerShortcut: [Native Function] }
```

**Comment by Sadret** [comment]
Weird, I can still reproduce. Did you start a scenario?

**Comment by Sadret** [comment]
I found out that it is because of a plugin that I am currently developing. I am investigating further.

**Comment by Sadret** [comment]
More precise, the game crashes when printing `ui` or `ui.tool` while a tool (custom or non-custom) is active. It seems to crash with any tool, in particular it is not an issue with `ui.tileSelection`.
I'm updating the description.
