### ISSUE TITLE
Don't show (new file) option in save dialog when displaying Windows drive letters

### ISSUE THREAD

**Issue by osconnoisseur** [OpenRCT2/OpenRCT2#2233]
On Windows, when clicking "(up)" as far as you go in the save dialog, you get a list of the drive letters. Since this is not a folder, and you can't save anything here, there's no reason to have a "(new file)" option in the list that does nothing.
![openrct2_new_file](https://cloud.githubusercontent.com/assets/15527244/11018264/7fe4a89a-8587-11e5-8490-6f8d9a1db081.png)

**Comment by janisozaur** [comment]
Weird, there's already code to handle that:
https://github.com/OpenRCT2/OpenRCT2/blob/b929a27595b75d56d29818eaa8c4af22fd13ba55/src/windows/loadsave.c#L649

**Comment by Gymnasiast** [comment]
@janisozaur : This is odd. The line pointed to is followed by
```includeNewItem = false;```
But somehow that doesn't work.

**Comment by janisozaur** [comment]
Perhaps it doesn't really enter this block.
