### ISSUE TITLE
Progress bar screen doesn't handle resizing

### ISSUE THREAD

**Issue by mrmbernardi** [OpenRCT2/OpenRCT2#22348]
### Operating System

Arch Linux

### OpenRCT2 build

OpenRCT2, v0.4.12

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Describe the issue

If the game is resized to a different size from the last time it was closed, the progress bar screen will not handle this correctly and leave part of the frame buffer uninitialised.

Note that the progress bar will still update itself while leaving the uninitialised parts on screen.

### Steps to reproduce

1. Close the game with a small window size.
2. Open the game and resize the window bigger (in my case, a window manager automatically sets the size to fill the space available on startup so this happens immediately)

### Attachments

![frame005](https://github.com/user-attachments/assets/e5d791d7-a3ad-4a2f-8025-a6d9d6dca1a6)

**Comment by AaronVanGeffen** [comment]
Interesting bug -- looks like I didn't take this into account! OpenLoco has the same issue, amusingly.
