### ISSUE TITLE
Crash on rotating view anti-clockwise

### ISSUE THREAD

**Issue by zornor** [OpenRCT2/OpenRCT2#2235]
Whenever the view is at a certain angle (the top-most tile is 1,1) and the view is rotated anti-clockwise (by hotkey) the game crashes in build 1423 (15f6f9b).

EDIT: this did not happen yesterday, so it's likely caused by a version from the past 24 hours.

**Comment by e-foley** [comment]
Related to #2201 and #2202, perhaps?
