### ISSUE TITLE
Server doesn't advertise, gives errors

### ISSUE THREAD

**Issue by JarnoVgr** [OpenRCT2/OpenRCT2#2236]
My public server doesn't advertise when using headless mode (might also be the case when not using headless).

Server gives following errors: http://i.imgur.com/35auPIa.png

**Comment by JarnoVgr** [comment]
Tried with build 1427: OpenRCT2 headless now crashes the app without showing any info.

**Comment by IntelOrca** [comment]
There is a problem with the master server, it currently being sorted out.
Headless does not crash for me, others seem to be running a server successfully with headless (just failing to advertise atm).
