### ISSUE TITLE
Alpine Coaster uses multiple tunnel entrance types

### ISSUE THREAD

**Issue by cheweytoo** [OpenRCT2/OpenRCT2#22389]
### Operating System

Ubuntu Linux 22.04.4

### OpenRCT2 build

06bb987 develop, Linux AppImage

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

I'm moderately sure that this is not intentional, since tunnel entrances for fully sloped tracks are round as well: The Alpine Coaster uses round tunnel entrances – _except_ for the flat-to-down piece when entering a tunnel, and the up-to-flat when exiting, where the tunnel entrance is the big square one.

![alpine_tunnels](https://github.com/user-attachments/assets/30bc89cd-624d-4386-9ec4-4e3603bce5ee)

See attached park.

### Steps to reproduce

- build Alpine Coaster with flat-to-down or up-to-flat piece to start/end a tunnel
- get square tunnel entrance

### Attachments

[alpine_tunnels.zip](https://github.com/user-attachments/files/16392888/alpine_tunnels.zip)

**Comment by lewyche** [comment]
Looks like the part of the code causing the issue is here:

https://github.com/OpenRCT2/OpenRCT2/blob/b02d461b02a65f5be85ef915c4c6dabc5c5d578e/src/openrct2/ride/coaster/AlpineCoaster.cpp#L358C1-L365C10

`TunnelType::_14` should be changed to something else.

**Comment by Gymnasiast** [comment]
Likely related to https://github.com/OpenRCT2/OpenRCT2/issues/22101 .
