### ISSUE TITLE
invisible glass over water isn't

### ISSUE THREAD

**Issue by cheweytoo** [OpenRCT2/OpenRCT2#22380]
### Operating System

Ubuntu Linux 22.04.5

### OpenRCT2 build

06bb987 develop, Linux AppImage

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

Placing a scenery item containing glass that has been assigned the special colour "invisible" over water makes that glass pulse visibly with the "water cycle":

https://github.com/user-attachments/assets/0014d526-3973-46d1-b6d3-873c70c9fd3d

See attached park.

### Steps to reproduce

- select scenery item with glass
- colour glass as "invisible"
- place scenery item so that water is visible through glass

### Attachments

[visible_invisible_glass.zip](https://github.com/user-attachments/files/16383939/visible_invisible_glass.zip)

**Comment by 733737** [comment]
the community is using this effect for scifi style parks. How does this negatively impact gameplay to justify it being removed? It is only currently being done intentionally.

**Comment by Gymnasiast** [comment]
> The community is using this effect for scifi style parks. (...)  It is only currently being done intentionally.

This, to me, is enough reason to keep it as it currently is.

**Comment by cheweytoo** [comment]
Would a solution maybe be to introduce a "shimmer" colour that behaves like invisible does now, and make invisible actually invisible?

Having no alternative to shimmering non-invisibility makes "invisible" a bit of a misnomer right now.

Not sure how to do this in a backward-compatible way, but wasn't this done before like "don't affect exitsing parks, but use fixed behaviour for new ones"?

**Comment by Gymnasiast** [comment]
It might be possible, but I don’t think the trade-off is worth it. It’s not just the import stuff, but also the fact that extra changes are needed in glass handling and handling colour.
