### ISSUE TITLE
When "Upper-Case text in banners" is selected, banners skip a part of the text

### ISSUE THREAD

**Issue by raidcookie** [OpenRCT2/OpenRCT2#2238]
Something I've only seen happen when the upper-case option is selected. Not really a major issue, but I wanted to mention it anyway.

Example: http://i.imgur.com/Gk9roo8.gifv

**Comment by Gymnasiast** [comment]
Yes, I noticed this too. A commit by IntelOrca, a weeks ago, decreased the problem but did not make it completely disappear.

**Comment by raidcookie** [comment]
It also only seems to happen on rides, the placeable banners run smoothly.

**Comment by mrtnptrs** [comment]
I can't reproduce this anymore using the latest build. So, I think this got fixed with the UTF-changes and can be closed. But could someone else check this to make sure I'm not wrong?

**Comment by Gymnasiast** [comment]
I doubt it has anything to do with the UTF-8 changes, but it does seem to be gone. I'll therefore consider this bug solved.

**Comment by duncanspumpkin** [comment]
Yes this bug was fixed by finishing the path paint
