### ISSUE TITLE
The letter L

### ISSUE THREAD

**Issue by rdrty1** [OpenRCT2/OpenRCT2#22403]
### Operating System

windows 11

### OpenRCT2 build

OpenRCT2, v0.4.7 (0e8d46e) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

the letter l automatically becomes a u with a symbol above it

### Steps to reproduce

Open game and type an l

### Attachments

<img width="1280" alt="Screenshot 2024-07-28 151330" src="https://github.com/user-attachments/assets/1378cbc9-23ed-41d1-a895-7266f9fb9075">

**Comment by Gymnasiast** [comment]
This is not a bug. You have a mixed install, combining the .exe of one version with a g2.dat of the other. Please reinstall OpenRCT2.
