### ISSUE TITLE
Giant Screenshot is not pixel perfect in resolution

### ISSUE THREAD

**Issue by Jirachi6774** [OpenRCT2/OpenRCT2#22413]
### Operating System

Windows 11, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.12-115-ge5f897e (e5f897e on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

The screenshot feature button to make a screenshot of the park (Giant Screenshot) does not have a pixel perfect resolution of the park.
Rollercoaster Tycoon Classic has a feature called "Full Park Screenshot" which makes a screenshot of the whole park, you can then view the image and zoom in and view it as if you're looking at the park in-game, RCTC makes pixel perfect screenshots of the whole park in full quality.

### Steps to reproduce

1. Open a random large sized _(in tiles)_ park
![image](https://github.com/user-attachments/assets/ee3b5d8c-0604-4976-b2bd-a02d0e6a8500)
2. Click on the Floppy Disk
![image](https://github.com/user-attachments/assets/f75df408-114e-4d1c-b885-ae287f544a8d)
3. Click on Giant Screenshot
![image](https://github.com/user-attachments/assets/bb7fdb2b-4871-4c65-931e-5d117afb09bb)
4. View the screenshot and zoom in on it
5. You'll see the resolution is not perfect the more you zoom

### Attachments

Giant Screenshot made in OpenRCT2 using the Giant Screenshot
![Giant Screenshot in OpenRCT2](https://github.com/user-attachments/assets/137145fa-9a9f-422c-961b-9386373be528)

Giant Screenshot made in RCTC using the Full Park Screenshot
[image](https://dl.dropboxusercontent.com/s/2433fk68was00n5/EntireParkScreenshot%281%29.png) _(GitHub doesn't allow +10 MB images)_

**Comment by mrmbernardi** [comment]
Is the problem here that the colours are all weird or is that just some mod you have and the problem is something else?

**Comment by Jirachi6774** [comment]
The colors are just the Water Color which changes the color palette, which is a mod yes.
The main problem is the resolution of the screenshot not being made in full quality.

I provided two examples, one in OpenRCT2 and another in RCTC, RCTC you can zoom in and it'll show the full quality view of the park, viewing the OpenRCT2 one will not as OpenRCT2 makes a much lower quality version of the screenshot.

**Comment by mrmbernardi** [comment]
I can't reproduce this. I took a screenshot of the Six Flags over Texas park in OpenRCT2 and I got a full size image.
I've attached cropped out sections of both screenshots below for comparison.

OpenRCT2:
![screenshot-2024-07-30_05:00:46](https://github.com/user-attachments/assets/cabba622-94df-4fc5-bbe5-78f6a03cb1a4)
Your screenshot:
![screenshot-2024-07-30_05:00:40](https://github.com/user-attachments/assets/d232934e-3ddc-4e43-bc2c-81cf8e4b0275)

**Comment by duncanspumpkin** [comment]
Are you taking the screen shot at the closest zoom?

**Comment by Jirachi6774** [comment]
Screenshot file the game makes when using the Giant Screenshot option

**Comment by Jirachi6774** [comment]
Here is a screenshot viewing the RCTC giant screenshot image file:
![image](https://github.com/user-attachments/assets/eb27f9d9-12be-40b2-8e2f-c2f7cd0294ff)

And this is what the same view looks like but viewed in the giant screenshot made by OpenRCT2:
![image](https://github.com/user-attachments/assets/8d97b7a5-b343-420a-826a-49b855e697c2)

**Comment by duncanspumpkin** [comment]
It looks like you are taking the screenshot whilst zoomed out. You need to zoom in before taking the giant screenshot.

**Comment by Jirachi6774** [comment]
WOW! You're correct!

**Comment by Jirachi6774** [comment]
Thank you very much! ❤️
I thought this was a bug but it seems I have to be zoomed in while in the park and then make the Giant Screenshot.
