### ISSUE TITLE
Water tool grid is one tile too small for even sizes

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#22416]
### Operating System

Windows 10, x64 build 19045

### OpenRCT2 build

OpenRCT2, v0.4.12-115-ge5f897e (e5f897e on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

For even tool sizes, the preview grid shows one row/column too little.
At size 2, it shows a 1x1 selection.
At size 4, it shows a 3x3 selection.
At size 6, it shows a 5x5 selection.
etc...

![Six Flags Holland 2024-07-29 22-10-10](https://github.com/user-attachments/assets/9c3bbc60-321b-4173-9138-119e7ae05140)

### Steps to reproduce

1. Open any scenario
2. Open the water tool
3. Try different sizes

**Comment by brynpttrsn** [comment]
Looks like this bug was introduced in #22256
