### ISSUE TITLE
Clear Scenery window closes when you open it

### ISSUE THREAD

**Issue by ATN-Antronach** [OpenRCT2/OpenRCT2#22439]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.12-140-g30e890c (30e890c on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

The Clear Scenery window closes itself after opening

### Steps to reproduce

Just open the Clear Scenery window, and it should close immediately.

**Comment by chrisceska** [comment]
![openrct2-scenerybug](https://github.com/user-attachments/assets/61748374-a4c2-42b3-b7e9-922e3e14d692)

**Comment by duncanspumpkin** [comment]
@AaronVanGeffen possibly related to your changes.
