### ISSUE TITLE
Linux version looks for fonts in Windows path

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#2244]
When using a language that uses a TTF font on Linux, OpenRCT2 will only find it when it is in its own folder, and using a `C:\Windows\Fonts` prefix.

Like this:
![schermafdruk van 2015-11-08 12-52-38](https://cloud.githubusercontent.com/assets/1478678/11020186/dc33b164-8617-11e5-816c-c34ebba6d89e.png)

It should instead look in the regular font folders, and not see `C:\Windows\Fonts` as a prefix.

**Comment by IntelOrca** [comment]
What are the regular font folders in Linux? Is there a function to retrieve that?

**Comment by Gymnasiast** [comment]
There are multiple:
- `/usr/share/fonts` and all its subfolders
- `~/.fonts` (user font folder)

I'm not sure of a function to retrieve it, perhaps SDL has one?

**Comment by janisozaur** [comment]
There's `fontconfig` or some other utility that handles that kind of thing, perhaps it sets some variable. I don't know yet, but I'll look into that.

**Comment by HaasJona** [comment]
You can't expect the user to have for example Arial (or pretty much any font) installed on Linux. If we need a specific font, better supply it ourselves (use an open source alternative if necessary) and then we don't have to worry about the directory.

**Comment by IntelOrca** [comment]
@HaasJona we will not be distributing fonts, we will just write the required fonts in the docs and how to change it to use an alternative in the config if necessary.

**Comment by ccfreak2k** [comment]
On Windows, you'll probably be better off following %windir%\fonts. I'm not sure if there's a separate env var for the font folder itself (there doesn't seem to be one on my system).

In Linux it looks like you'll be relying on [fontconfig](https://wiki.freedesktop.org/www/Software/fontconfig/) as mentioned previously. It's designed for this exact purpose.

**Comment by Patrik356b** [comment]
@IntelOrca ORCT2 could come with some royalty free font or such. Just an idea.

**Comment by Gymnasiast** [comment]
Has been fixed by @AaronVanGeffen.
