### ISSUE TITLE
Bulldozer cursor dissapears after clicking

### ISSUE THREAD

**Issue by J-PIE-314** [OpenRCT2/OpenRCT2#22480]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.13-10-gb637bcb (b637bcb on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

The nice new bulldozer cursor icon (introduced in #22466) reverts to the generic crosshairs cursor after clicking.

### Steps to reproduce

1. Open any park
2. Open the clear scenery tab
3. Observe the bulldozer cursor changing to the crosshairs cursor after clicking in the viewport.

**Comment by AaronVanGeffen** [comment]
Argh, I forgot to update the `OnToolDown`, `OnToolDrag`, `OnToolUp` to use the new cursor as well. I've only updated `ToggleClearSceneryWindow` to use the new one.
