### ISSUE TITLE
When it is raining, if you look into the void and take a screenshot, the rain hangs around.

### ISSUE THREAD

**Issue by Krutonium** [OpenRCT2/OpenRCT2#2249]
![scr41](https://cloud.githubusercontent.com/assets/3945538/11020884/bd2172b8-85fc-11e5-9a05-bb4c163e75ef.png)

**Comment by Gymnasiast** [comment]
Doesn't it always do that, whetheryou take a screenshot or not? Also, I think this is vanilla behaviour.

**Comment by IntelOrca** [comment]
@Gymnasiast when you take a screenshot, a lot of the rain drops freeze and stay there until you move the viewport around.

**Comment by Gymnasiast** [comment]
Ah, thanks. I misinterpreted that.

**Comment by mrtnptrs** [comment]
I can't reproduce this issue, could someone check and close it if I'm right?

**Comment by Goddesen** [comment]
I cannot reproduce this on `425fc73` on linux.

**Comment by sutternalt** [comment]
I also could not reproduce this on 0fb307c on Windows 10 x64.

**Comment by Gymnasiast** [comment]
Can not reproduce it either.
