### ISSUE TITLE
Themes window: Add a tooltip to the checkbox explaining what they’re for

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#22494]
(Transparancy, if you didn’t know.)

**Comment by lewyche** [comment]
I can try to work on this issue!

**Comment by Gymnasiast** [comment]
I discussed this a bit in the Discord chat, and came up with a better solution: listing the colour beneath each other, and putting the checkbox next to each colour, with a label instead of just a tooltip. Do you think you can pull this off?

**Comment by lewyche** [comment]
I'll try my best.

**Comment by AaronVanGeffen** [comment]
> I discussed this a bit in the Discord chat, and came up with a better solution: listing the colour beneath each other, and putting the checkbox next to each colour, with a label instead of just a tooltip. Do you think you can pull this off?

Hmm, I don't think that's a better approach, personally. The label would be the same for all checkboxes, right? I think a tooltip is all that's needed.
