### ISSUE TITLE
Change type of SPR_NONE to ImageIndex

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#22509]
This will make it unsigned, just like the rest, and should hopefully allow us to get rid of some casts.

(cc @AaronVanGeffen )

**Comment by AaronVanGeffen** [comment]
Personally, I would prefer to see some more changes to the sprite ID constants. What I have in mind is the following:

- [ ] Move the `ImageIndex` type declaration to its own header, e.g. `ImageIndexType.h` (Analogous to what we did for `StringId` in `StringIdType.h`)
- [ ] This header could also contain the equivalent of `SPR_NONE`, declared as ImageIndex type, e.g. `kSpriteIdNull`. Existing references to `SPR_NONE` should be replaced.
- [ ] All other sprite indices and enums should be of the `ImageIndex` type as well.

**Comment by Gymnasiast** [comment]
I guess that no longer makes it a "good-first-issue", right?

**Comment by scaryghosty** [comment]
peeking at this

**Comment by scaryghosty** [comment]
in my forked branch i have completed the first two tasks... i notice the mention of removing unnecessary casts. would you like me to rectify the casts which utilize kSpriteIdNull via this issue?

**Comment by scaryghosty** [comment]
please ignore the stupid mistakes lol... i can refork and rebranch and do it all correctly _the first time_ if desired.

**Comment by scaryghosty** [comment]
PR above
