### ISSUE TITLE
Virtual floor no longer appears when holding SHIFT to raise track

### ISSUE THREAD

**Issue by SebinNyshkim** [OpenRCT2/OpenRCT2#22520]
### Operating System

Linux

### OpenRCT2 build

OpenRCT2, v0.4.13 (caacd4d on HEAD)

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

When using SHIFT to raise objects (flat rides, stalls, etc.) the virtual floor no longer appears in order give the player immediate visual feedback whether or not the object is going to be placed at the same height as other objects around its vicinity, e.g. paths.

### Steps to reproduce

1. open any scenario
2. open the build a ride window
3. select a flat ride or stall
4. hold SHIFT to raise it, the virtual floor does not appear

### Attachments

Here I'm building a stall above water using SHIFT to raise it a couple units, but no virtual floor appears while holding SHIFT

![Woodworm Park 2024-08-09 18-08-13](https://github.com/user-attachments/assets/f8e5b84d-f4a2-41b9-95cf-c0382e8d6cf5)

**Comment by Gymnasiast** [comment]
If you open the Options window and go to tab second tab, what is the option for "virtual floor" set to?

**Comment by ZehMatt** [comment]
After some testing, it appears to be specific to rides, works fine for footpath and scenery.

**Comment by SebinNyshkim** [comment]
@Gymnasiast The setting is set to "Glassy (translucent)"

**Comment by XpressCS** [comment]
Also experiencing the same issue. Can confirm it appears to be specific to rides and shops/stalls. Scenery and footpath it works fine.

**Comment by duncanspumpkin** [comment]
Might be related to @AaronVanGeffen refactoring

**Comment by AaronVanGeffen** [comment]
Most likely. I'll investigate.
