### ISSUE TITLE
Paths should be decoupled from their railings

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#2253]
I was told in RCT1 you can select different types of paths and combine them with different types of railings, which is not something we support in OpenRCT2 yet. It's not quite possible until fully reversed.

**Comment by janisozaur** [comment]
https://openrct.net/forum/topic/59/RCT1+Features+in+OpenRCT2

**Comment by IntelOrca** [comment]
We would need to increase map element size to do this.

**Comment by Gymnasiast** [comment]
To update: in the meantime, the drawing code has been separated.

With the new save format, there will be two object types: path surfaces (regular path _or_ queue) and path railings.

PR's:
- https://github.com/OpenRCT2/OpenRCT2/pull/8541 (splits drawing)
- https://github.com/OpenRCT2/OpenRCT2/pull/8615 (puts decision to draw paths over supports into the tile element)
- https://github.com/OpenRCT2/OpenRCT2/pull/8617 (splits the path object into surfaces and railings)

Stuff left to do:
- Split surface objects to be either a regular path or a queue (not really feasible until the new save format comes along)
- Ability to load path surface and path railing objects directly (as opposed to creating at load time from "integrated" footpath objects)
- A way to correctly import old footpath objects, possibly having them point to a path surface, queue and railing entry.
