### ISSUE TITLE
win32 CI builds do not use optimised BitScanForward

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#22537]
When building OpenRCT2 on the CI, the following message is printed a few times:

> Falling back to iterative bitscan forward, consider using intrinsics

I expect this to be a misconfiguration, seeing as it has been available in MSVC for a long time.

**Comment by Gymnasiast** [comment]
Tagging @ZehMatt

**Comment by duncanspumpkin** [comment]
Well that's because there isn't an intrinsic for it. https://learn.microsoft.com/en-us/cpp/intrinsics/bitscanforward-bitscanforward64?view=msvc-170 You've only got one for x64.

**Comment by ZehMatt** [comment]
> Well that's because there isn't an intrinsic for it. https://learn.microsoft.com/en-us/cpp/intrinsics/bitscanforward-bitscanforward64?view=msvc-170 You've only got one for x64.

On x86 (32 bit) you should still get _BitScanForward but not _BitScanForward64, might be good to improve the message to see if it just hits the 64 bit version of it.
