### ISSUE TITLE
Main viewport sliding along map edges is inconsistent 

### ISSUE THREAD

**Issue by kmdreko** [OpenRCT2/OpenRCT2#2254]
When moving into a map edge, sometimes the viewport slides along the edge (as I would expect), but will not slide on some edges depending on the rotation. It also may slide faster on some edges. Where it doesn't slide seems semi-dependent on zoom level

Seems to be an original bug

**Comment by kmdreko** [comment]
Different but same theme as issue #996

**Comment by mrtnptrs** [comment]
It is directly related to #996 So, couldn't we close this bug report and add the information to #996?
