### ISSUE TITLE
undo/redo last action button + hotkey

### ISSUE THREAD

**Issue by hytacker** [OpenRCT2/OpenRCT2#2256]
I always felt the need for such a button

![undo_redo](https://cloud.githubusercontent.com/assets/15657920/11023684/3f74e334-8680-11e5-90f2-9dc1612edd15.jpg)

**Comment by Patrik356b** [comment]
preferably also a history list like in paint.net (but you know, in rct
style)




On Mon, Nov 9, 2015 at 1:24 AM, hytacker <notifications@github.com> wrote:

> I always felt the need for such a button
>
> [image: undo_redo]
> <https://cloud.githubusercontent.com/assets/15657920/11023684/3f74e334-8680-11e5-90f2-9dc1612edd15.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenRCT2/OpenRCT2/issues/2256>.
>



-- 
Best regards; Hexile

**Comment by Patrik356b** [comment]
Preferably with a history window, like in paint.net but with rct style:
![img](http://puu.sh/leCAO/739127b857.png)

**Comment by Gymnasiast** [comment]
Has been considered earlier, but will not be implemented because it makes the game way too easy.

**Comment by IntelOrca** [comment]
To give a more technical reason than @Gymnasiast, undo stacks are very difficult to implement particularly in a real-time environment. And there are many issues to overcome such as multiplayer.

**Comment by Richard-L** [comment]
So perhaps just for single player? I think this is a quite vital feature as people treat RCT as a design tool essentially. You should be able to undo something you find you don't like.

**Comment by Gymnasiast** [comment]
RCT (and thus OpenRCT2) is not a design tool, it is a theme park simulator. And even though we have taken many extra features on board, we have to make sure it stays a good and fun theme park simulator. It's impossible to cater for everyone's desires, but easy to cater for no one's in the long run. And on top of that: the code should stay maintainable.
