### ISSUE TITLE
Move buidling button

### ISSUE THREAD

**Issue by hytacker** [OpenRCT2/OpenRCT2#2257]
If you miss click an attraction/object or later on find out that you want your attration some where else because of scenery. You don't need to sells it and rebuy it. 

Tycoon games that where released after rct had a button like that. Zoo tycoon for example
![download](https://cloud.githubusercontent.com/assets/15657920/11023747/cbead2be-8681-11e5-9122-c3fa83e98a3f.png)

**Comment by Gymnasiast** [comment]
You can already move flat rides and shops. For Roller Coasters this isn't terribly realistic and make the game too easy, IMO.

**Comment by osconnoisseur** [comment]
I think some cut/copy/paste functionality for scenery would be a good solution for this.

**Comment by Gymnasiast** [comment]
@osconnoisseur : _That_ idea already planned by IntelOrca

**Comment by osconnoisseur** [comment]
I know. That's sort of why I mentioned it.

**Comment by Gymnasiast** [comment]
Closing issue because of my first comment and because the functionality discussed has its own issue: #1926.
