### ISSUE TITLE
Include acid water icon (scenario editor)

### ISSUE THREAD

**Issue by hytacker** [OpenRCT2/OpenRCT2#2258]
when selecting acid (green) water in scenario editor there was no icon for this type of water (it never was)

![acid_green_water_rct2_icon](https://cloud.githubusercontent.com/assets/15657920/11023801/d7da266e-8682-11e5-9055-a16ac83f17f5.png)

**Comment by Gymnasiast** [comment]
There is no preview for any type of water due to a lack of embedded preview.

**Comment by Gymnasiast** [comment]
Duplicate of #1143.
