### ISSUE TITLE
Select multiple water types in one game

### ISSUE THREAD

**Issue by hytacker** [OpenRCT2/OpenRCT2#2259]
When creating a custom scenario you can only select one type of water
![green_water_rct2_icon png](https://cloud.githubusercontent.com/assets/15657920/11023849/c0b321f6-8683-11e5-8eb8-6aefecf1171b.png)
![acid_green_water_rct2_icon](https://cloud.githubusercontent.com/assets/15657920/11023851/c28c6e24-8683-11e5-89c5-2d1b7bf82939.png)
![natural_water_rct2_icon png](https://cloud.githubusercontent.com/assets/15657920/11023854/cb4a9284-8683-11e5-8c94-6a5e1675a325.png)
![orange_water_rct2_icon png](https://cloud.githubusercontent.com/assets/15657920/11023859/ddfa7e94-8683-11e5-9f97-49d11381f0be.png)

**Comment by Gymnasiast** [comment]
How do you imagine it should work?

**Comment by IntelOrca** [comment]
Water colour is implemented by setting a set of colours in the game palette. We can't add more water colours simultaneously until we go at least 32-bit.

**Comment by hytacker** [comment]
@Gymnasiast Select, while in game your water tool. Then select water type and then place the water the way you want it.

![water optie](https://cloud.githubusercontent.com/assets/15657920/11037774/e1b0a0b4-86ff-11e5-976e-d90470debc5b.png)

**Comment by Broxzier** [comment]
I'm not sure if that would work, since these 'water styles' are actually colour pallets for the entire game. Perhaps it would work if you can set which style to use for each tile, just like how you select the land types, but then it should also affect all map elements on that tile.

**Comment by duncanspumpkin** [comment]
@Broxzier nah it still wouldn't work the palettes are read so far down the drawing code chain that there would be no way to know the map element that produced it. It would require extensive work to change that. For such a small feature it would require ridiculous amounts of work.

**Comment by Patrik356b** [comment]
How about add it like the terrain painting, as it's different between
horizontal and vertical textures

**Comment by IntelOrca** [comment]
As I pointed out, its not possible because water is implemented with a reserved segment of the game palette.

**Comment by Christipher** [comment]
it should also be noted - what should happen should a water ride go into that area from another area?
