### ISSUE TITLE
Investigate if .sea files are being loaded twice

### ISSUE THREAD

**Issue by tupaschoal** [OpenRCT2/OpenRCT2#22597]
When doing #21189, I noticed the patch algorithm seemingly running twice in a row for `.sea`, which would indicate that they are being loaded twice. Task here is to investigate if this is the case and, if it is, whether it can be fixed to a single one.

**Comment by Gymnasiast** [comment]
Has this not been fixed by https://github.com/OpenRCT2/OpenRCT2/pull/22305 ?

**Comment by tupaschoal** [comment]
I'm not sure, at the time I only noticed the double loading with `.sea` files, which was weird.

**Comment by tupaschoal** [comment]
I did a bit of investigating and indeed it seem fixed!
