### ISSUE TITLE
Increase decrease moutian/water tool size with scroll wheel

### ISSUE THREAD

**Issue by hytacker** [OpenRCT2/OpenRCT2#2260]
hover above the the little squares and scroll to adjust tool size 

this works maybe a bit quicker then typing the size

**Comment by Patrik356b** [comment]
Yes

**Comment by PFCKrutonium** [comment]
This would be a major usability increase. Perhaps also clicking the third wheel to toggle hills?

**Comment by pizza2004** [comment]
@PFCKrutonium That would be very kind of you.  Third wheels rarely get much action.

**Comment by pizza2004** [comment]
It's a good suggestion.  I don't see any reason why it would be a bad inclusion.

**Comment by PFCKrutonium** [comment]
I meant the mouse wheel, but I suppose the third wheel gets even less action XD

**Comment by Patrik356b** [comment]
3rd wheel?. i don't even have a horizontal scroll wheel on my mouse, only
hz scroll buttons, and not even this is common.

On Mon, Nov 9, 2015 at 5:31 AM, Krutonium <notifications@github.com> wrote:

> I meant the mouse wheel, but I suppose the third wheel gets even less
> action XD
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenRCT2/OpenRCT2/issues/2260#issuecomment-154918086>.
>



-- 
Best regards; Hexile

**Comment by pizza2004** [comment]
Well, I said it as a joke, and I believe he too got that.  The 'third wheel' is the third person in a group of three, where the other two are a couple, meaning the third person is kinda unnecessary and left out.  I'm relatively certain it refers to bikes somehow.

**Comment by Patrik356b** [comment]
doh, should've realized that old joke

**Comment by IntelOrca** [comment]
Theoretically this could apply to any kind of spinner control.

**Comment by PFCKrutonium** [comment]
Even my steering wheel?
![amazed-face](https://cloud.githubusercontent.com/assets/3945538/11050355/26e18be0-8713-11e5-99e6-de3e2423df57.jpg)
