### ISSUE TITLE
Ride entrance and exit building can no longer be removed (but can still be moved)

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#22611]
### Operating System

Windows 10 64 bit

### OpenRCT2 build

v.0.4.13-9f0125b

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

When you recolate a ride entrance or exit building it disappears if you double right click on it twice. However, as of v.0.4.13-9f0125b (17 days ago) that no longer works, and you cannot remove an existing ride entrance or exit building anymore. You can still move it, but cannot remove it.

See video for difference in behaviour: https://www.youtube.com/watch?v=G1jA98AEv7c

### Steps to reproduce

See video

**Comment by AaronVanGeffen** [comment]
9f0125b (#22488) just tackles the finance charts. I think it's likely to be due to 03bc1e5707489eac2403de62d2c393297dc8799d (#22430), which was merged just prior.
