### ISSUE TITLE
the ORIGINAL_RATINGS flag

### ISSUE THREAD

**Issue by ghost** [OpenRCT2/OpenRCT2#22614]
### Operating System

10

### OpenRCT2 build

v0.4.0 (c6302a1 on master)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

The bug also exists in the original game (RCT2/RCTC)

### Describe the issue

I've searched the entire Internet for days on how to actually activate the ORIGINAL_RATINGS flag. 

I hate the OpenRCT2 nerfed ride pricing calculation, and I want to bring back the vanilla RCT2 version so that I can benefit more from the original pricing. However, after having done extensive research on how to get it back, I hit a wall everywhere.

I can see people online mentioning that it is no problem whatsoever, and that it's possible to go back to vanilla RCT2 pricing simply by enabling the ORIGINAL_RATINGS flag.

BUT HOW??? When it comes to enabling that mentioned flag, I have no idea what to do now. There is absolutely no guide on this matter on the web, and I found nothing that mentions how to activate that flag. I tried everything I could think of. I checked all the file folders, I tested the debugging tools numerous times, I double checked all options, cheats and the config.ini file. Nothing.

Is that supposed to be a bug then? Is that impossible? Please, I need to know how to activate that flag. I really want to use the vanilla RCT2 ride pricing.

Thank you in advance.

### Steps to reproduce

The option as of itself is very hard to find. It maybe be either a bug that made it vanish or something else.

**Comment by duncanspumpkin** [comment]
It's a compile definition that you enable. So you need to compile openrct2 yourself with that defined. Not sure if many/any do that so it might be broken and not work.

**Comment by romantyke** [comment]
> It's a compile definition that you enable. So you need to compile openrct2 yourself with that defined. Not sure if many/any do that so it might be broken and not work.

Yes. After a lot of reading into the matter, I have figured that part out. But when it comes to actual compiling, it can be quite tricky. I am rather good with stuff like Python and CMD and such due to self learning their use by myself for other kind of situations (other video games).

But this one here is very complicated to me, and this is due to incomplete archives and guides. Unless I can get a detailed and step by step guide on how to compile the game myself, it would be nigh impossible for me to accomplish such a thing. Python had guides all over the web for all kinds of subjects, and that's how I managed to learn how to use and control it for many purposes. And again, this was due to my stubbornness at trying to get my way with the games I wanted to control.

Sadly, I don't think I'll find a detailed guide on how to compile OpenRCT2 myself. The official pages are indeed giving a compiling guide, but steps are skipped there and it lets me have to figure those steps out by myself. This is frustrating, especially when I know I can learn how to do things like that.

**Comment by duncanspumpkin** [comment]
If you are on Windows install: 

Visual Studio 2022 (Enterprise / Professional / Community (Free))
Desktop development with C++

Check out the repository, this can be done using GitHub Desktop or other tools

Open a new Developer Command Prompt for VS 2022

Navigate to the repository (e.g. cd C:\GitHub\OpenRCT2)

To build the x64 version, use `msbuild openrct2.proj /t:build /p:platform=x64`

After you have built it once from the developer prompt you can do everything else from within visual studio just open the openrct2.sln file. To change the ratings you'll need to find the ratings file and at the top of the file add `#define ORIGINAL_RATINGS` then recompile.

**Comment by romantyke** [comment]
> https://github.com/OpenRCT2/OpenRCT2?tab=readme-ov-file#windows
> 
> If you are on Windows install:
> 
> Visual Studio 2022 (Enterprise / Professional / Community (Free)) Desktop development with C++
> 
> Check out the repository, this can be done using GitHub Desktop or other tools
> 
> Open a new Developer Command Prompt for VS 2022
> 
> Navigate to the repository (e.g. cd C:\GitHub\OpenRCT2)
> 
> To build the x64 version, use `msbuild openrct2.proj /t:build /p:platform=x64`
> 
> After you have built it once from the developer prompt you can do everything else from within visual studio just open the openrct2.sln file. To change the ratings you'll need to find the ratings file and at the top of the file add `#define ORIGINAL_RATINGS` then recompile.

Yes I've managed to go all the way to the part where I can build the x64 version. But no luck. I couldn't manage how to create a new command prompt with Visual Studios or it's possible I am not doing this the right way. I think I'm skipping some important part here. The Github repository part was a piece of cake. It's the building part and the VS Command Prompt part that chokes me.

**Comment by romantyke** [comment]
I have been made aware that the newest version of OpenRCT2 has implemented a new cheat which makes guests ignore it completely. I don,t like to use cheats in this game but in the worst case scenario, I will update the game and use that function.

**Comment by duncanspumpkin** [comment]
> > https://github.com/OpenRCT2/OpenRCT2?tab=readme-ov-file#windows
> > If you are on Windows install:
> > Visual Studio 2022 (Enterprise / Professional / Community (Free)) Desktop development with C++
> > Check out the repository, this can be done using GitHub Desktop or other tools
> > Open a new Developer Command Prompt for VS 2022
> > Navigate to the repository (e.g. cd C:\GitHub\OpenRCT2)
> > To build the x64 version, use `msbuild openrct2.proj /t:build /p:platform=x64`
> > After you have built it once from the developer prompt you can do everything else from within visual studio just open the openrct2.sln file. To change the ratings you'll need to find the ratings file and at the top of the file add `#define ORIGINAL_RATINGS` then recompile.
> 
> Yes I've managed to go all the way to the part where I can build the x64 version. But no luck. I couldn't manage how to create a new command prompt with Visual Studios or it's possible I am not doing this the right way. I think I'm skipping some important part here. The Github repository part was a piece of cake. It's the building part and the VS Command Prompt part that chokes me.

You type into the start menu "developer command prompt" and it will be one of the first options.

**Comment by romantyke** [comment]
Yes. I already know how to access that. I was using DOS back in the 90s to access my games and programs. That was before Windows systems had actual modern desktops like we have nowadays. The use is basically the same. It,s very similar. Maybe that was why learning how to use Python wasn't that hard.

No, the issue I'm having is that the command line I am supposed to write results in a error. The prompt doesn't recognise the command line and that means I have messed up something along the way. This is giving me a headache.

Sigh... Oh well.. I think I'll just give up... this is getting ridiculous. After fifteen days researching on this issue.

The latest OpenRCT2 update is offering a new cheat which allows guests to completely ignore prices, and this may well be what I need. Talk about a coincidence -- It was released right at the time I was starting to look into this entire thing.

I plan to take a break and then test that out once the stable version is released.

**Comment by janisozaur** [comment]
Why can't you just use our CI? E.g. https://github.com/OpenRCT2/OpenRCT2/pull/22624

**Comment by romantyke** [comment]
> Why can't you just use our CI? E.g. #22624

I wasn't even aware of this. Can you please elaborate?

**Comment by duncanspumpkin** [comment]
> > Why can't you just use our CI? E.g. #22624
> 
> I wasn't even aware of this. Can you please elaborate?

It is possible to just make your changes on GitHub and get the GitHubs CI servers to build your changes. After the ci completes you can download the build artifacts which will be the modified executable. That way you don't need to have a developer environment installed locally. It will be slower than doing things locally but if for some reason you are incapable of setting up an environment it is a nice stop gap (e.g Windows devs confirming changes work on Linux and vice versa).

**Comment by romantyke** [comment]
> > > Why can't you just use our CI? E.g. #22624
> > 
> > 
> > I wasn't even aware of this. Can you please elaborate?
> 
> It is possible to just make your changes on GitHub and get the GitHubs CI servers to build your changes. After the ci completes you can download the build artifacts which will be the modified executable. That way you don't need to have a developer environment installed locally. It will be slower than doing things locally but if for some reason you are incapable of setting up an environment it is a nice stop gap (e.g Windows devs confirming changes work on Linux and vice versa).

That does sounds like a sound solution.

Please can you show me how I can do that? Any help would be greatly appreciated.

**Comment by janisozaur** [comment]
I already have: #22624 (and fixed a bug that prevented it from working: #22625)

**Comment by romantyke** [comment]
> I already have: #22624 (and fixed a bug that prevented it from working: #22625)

What am I supposed to do there? I don,t understand. All I see is a bunch of log and people talking about me.

**Comment by romantyke** [comment]
Please guys, I really don't want to be a problem. It's okay if I pass on having this issue resolved. I am well aware that OpenRCT2 is a huge project as of itself and its workers can't afford to waste their time teaching about coding with beginners like me. I am very new to Github and I feel like an outsider. As far as I am concerned, I do not want to get in you guys' way. You have better stuff to do than teach an old man like me how to navigate this website. So I'll call of this whole mess and won't be a misfortune upon you anymore. Gymnasiast is right. I have to stand aside. Please close this topic and move on.

**Comment by Harry-Hopkinson** [comment]
@romantyke Checkout this [PR](https://github.com/OpenRCT2/OpenRCT2/pull/22630), wait for the CI to finish and then click on this [link](https://github.com/OpenRCT2/OpenRCT2/actions/runs/10555826006?pr=22630)

**Comment by romantyke** [comment]
> @romantyke Checkout this [PR](https://github.com/OpenRCT2/OpenRCT2/pull/22630), wait for the CI to finish and then click on this [link](https://github.com/OpenRCT2/OpenRCT2/actions/runs/10555826006?pr=22630)

Ok I will thanks

**Comment by Harry-Hopkinson** [comment]
And then click on the corresponding windows build - I am guessing OpenRCT2-Windows-x64

**Comment by romantyke** [comment]
> And then click on the corresponding windows build - I am presuming OpenRCT2-Windows-x64

Got it. Thank you.

**Comment by Harry-Hopkinson** [comment]
It is ready now - click on this [link](https://github.com/OpenRCT2/OpenRCT2/actions/runs/10555826006?pr=22630) scroll down to the Artifacts header and click on OpenRCT2-Windows-x64

**Comment by romantyke** [comment]
> It is ready now - click on this [link](https://github.com/OpenRCT2/OpenRCT2/actions/runs/10555826006?pr=22630) scroll down to the Artifacts header and click on OpenRCT2-Windows-x64

Yes I got it now. It,s downloading. Thanks.

**Comment by Harry-Hopkinson** [comment]
Is it working?

**Comment by romantyke** [comment]
> Is it working?

Yes.

**Comment by Harry-Hopkinson** [comment]
This can likely be closed now.
