### ISSUE TITLE
An Assertion Failed: Failed to reallocate [8 characters]

### ISSUE THREAD

**Issue by coastercrab** [OpenRCT2/OpenRCT2#22623]
### Operating System

Windows 7 Ultimate 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.13-152-g4cfc173 (4cfc173 on develop)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

A crash during "checking object files" progress bar (sometimes up to 1782 objects, 1589 objects, 1599 etc.). I thought it became instant, but turns out the window just goes blank with a white box until you switch back into it now.
Crash opens 8 error message windows simultaneously, similar to this one, same message but different (memory location?) and size is 576460752303423488 bytes (except 1 message with 288230376151711744 bytes]. The memory locations (if that's what the 8 characters are) are always different and are sometimes just the number 0 once.
![Error](https://github.com/user-attachments/assets/f75d8d15-55c0-4660-9e59-ecd8221b5675)

### Steps to reproduce

Open the game. I wish there was more to it so I could make it easier for you.

### Attachments

[c292760e-1132-4994-ad41-5faa21c9deeb(4cfc173_x86-64).dmp.gz](https://github.com/user-attachments/files/16736771/c292760e-1132-4994-ad41-5faa21c9deeb.4cfc173_x86-64.dmp.gz)

**Comment by Gymnasiast** [comment]
Also affects this user: https://www.reddit.com/r/openrct2/comments/1f2t0hs/latest_develop_load_errors/

**Comment by Gymnasiast** [comment]
Could you try this build: https://github.com/Gymnasiast/OpenRCT2/actions/runs/10646310726/artifacts/1877947454
**Required you to be logged into GitHub, or it will 404.**
