### ISSUE TITLE
Raising/lowering land does not take "Disable support limits" into account

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#2264]
It will still display "Supports for the track above cannot be extended any further", even when _raising_ the land (which it shouldn't do, even with "Disable support limits" off).

**Comment by IntelOrca** [comment]
@osconnoisseur appears to be working on the function responsible for this:
https://github.com/osconnoisseur/OpenRCT2/commit/c79fec82a9bcd39e528dbc2e236599f3a7064b45

**Comment by osconnoisseur** [comment]
Yes, I'm currently decompiling the rest of map_set_land_height(). I'll take a look at this.

**Comment by osconnoisseur** [comment]
I've found the relevant code and fixed this in my branch. This issue will be fixed once it gets merged.
