### ISSUE TITLE
Don't recommend Fedora Linux COPR package

### ISSUE THREAD

**Issue by Tiagoquix** [OpenRCT2/OpenRCT2#22649]
In the Readme file, there is:

> Fedora 28 i386/amd64: [openrct2](https://copr.fedorainfracloud.org/coprs/nauticalnexus/openrct2/)

However, this package has not been updated for 4 years. Latest version of that COPR is 0.2.5.

I suggest not to recommend this COPR anymore and instead focus on the Flatpak version, which works flawlessly.

**Comment by janisozaur** [comment]
Sure, can you submit a PR?
