### ISSUE TITLE
Custom Fonts

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#2269]
I would love to be able to use any font I want in the game.

**Comment by IntelOrca** [comment]
Why?

Yes its planned for TTF fonts to be changed in case you don't have the default.

**Comment by PFCKrutonium** [comment]
Lets say for example I wanted everything in Comic Sans. Horrible Font Choice, but I would love to have that option.

**Comment by IntelOrca** [comment]
Now implemented.
