### ISSUE TITLE
Rides, Vegetation, and Path are invisible upon starting new game

### ISSUE THREAD

**Issue by tubbo** [OpenRCT2/OpenRCT2#22691]
### Operating System

macOS Sonoma 14.14.1

### OpenRCT2 build

OpenRCT2, v0.4.14 (18492da on HEAD)

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

When starting any new scenario with the latest OpenRCT2, all paths/rides/vegetation is set to invisible by default. This was not happening in v0.4.13 as I had just been playing it (and can probably reproduce that "sunny day" scenario if necessary) before downloading the latest version to try it out.

### Steps to reproduce

1. Start any new game
2. Observe paths/rides/vegetation hidden by default

### Attachments

https://github.com/user-attachments/assets/3b7a9e7c-1fef-4aec-ac0d-3aa323310178

**Comment by sjoerddebruin** [comment]
Known issue, see https://github.com/OpenRCT2/OpenRCT2/discussions/22681#discussioncomment-10530527.
