### ISSUE TITLE
Porting OpenRCT2 to Windows on ARM32 (Windows 10 15035)

### ISSUE THREAD

**Issue by RetroSoftwareRepository** [OpenRCT2/OpenRCT2#22706]
Just thought I'd ask about this considering it's compiled for Windows ARM64

**Comment by janisozaur** [comment]
I'm the author of arm64 port. I have no interest in porting to arm32, but would accept code fixes for that. CI job for that platform is questionable, as it would take a lot of time for a platform that has fewer users than windows 5.1. Can you name some hardware that uses arm32 version?

**Comment by Gymnasiast** [comment]
As far as I understand (from reading BetaWiki) no released version of Windows 10 supports 32-bit ARM, only one specific development build (the 15035 you mentioned in the title).

I agree with janisozaur that we’ll accept patches (within reason), if you are willing to maintain it. I should also warn that we cannot guarantee our codebase will remain compatible.

**Comment by RetroSoftwareRepository** [comment]
Surface RT and Surface 2 both unofficially run said build of Windows 10 (15035)
________________________________

**Comment by Gymnasiast** [comment]
I trust we answered your question: we won’t add support ourselves, but we will accept patches if somebody wants to maintain.
