### ISSUE TITLE
Car ride allows adjusting colours of both cars and vehicles

### ISSUE THREAD

**Issue by sjoerddebruin** [OpenRCT2/OpenRCT2#22702]
### Operating System

MacOS 14.5

### OpenRCT2 build

OpenRCT2, v0.4.14 (a45d701 on develop)

### Base game

RollerCoaster Tycoon 2

### Describe the issue

While watching Marcel's stream today he noticed that the car ride allows you to edit the colours of vehicles as well, this option shows two invisible vehicles and one visible. The option should not be visible in normal gameplay. Other tracked rides seem fine as far as I can tell.

### Steps to reproduce

1. Build a car ride
2. Navigate to the colour scheme tab
3. Click the vehicle dropdown

### Attachments

![image](https://github.com/user-attachments/assets/509c72bd-9962-479d-b6e2-cbe5d649f785)

**Comment by Gymnasiast** [comment]
I think something similar is also a problem on the Junior RC.

We should probably have some sort of flag to hide a car from the window. Simply blocking all ‘zero cars’ won’t work as some of them are visible and should be recolourable, like the locomotive and tender from the Miniature Railway.

**Comment by sjoerddebruin** [comment]
Just found #2614 indeed, perhaps change that one in a general bug.

**Comment by Gymnasiast** [comment]
Ok, I’m going to do that and close this one as duplicate.
