### ISSUE TITLE
Creating a banner on the client in multiplayer brings up an invalid window

### ISSUE THREAD

**Issue by FlukiestEmperor** [OpenRCT2/OpenRCT2#2271]
Creating a banner pulls up an invalid window upon creation on the client side. Closing it out and right clicking on the banner will pull up the correct window

![invalid_banner](https://cloud.githubusercontent.com/assets/1393110/11056180/a52ca26a-8744-11e5-9ec0-075ff3ae0083.PNG)

**Comment by zsilencer** [comment]
i fixed this in #2783
