### ISSUE TITLE
Anything set to invisible in transparency options loads up any park with those selected objects invisible by default (supports, trees, paths, etc.)

### ISSUE THREAD

**Issue by terrytek12** [OpenRCT2/OpenRCT2#22729]
### Operating System

Windows 10 64 bit

### OpenRCT2 build

openrct2 version 0.4.14 18492da 

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

(preface by saying in the transparency options menu where i can edit the visibility of objects in see thru/invisible mode i have supports and scenery set to invisible when i hit the invisible supports/scenery hotkey, see thru for paths and trees/gardens)

With every park I load, whether it's a new scenario, a saved park, or a multiplayer server, the objects that I have selected as "turn invisible" with my hotkey somehow load up in the park as invisible instead of visible when I first load into the park. 

### Steps to reproduce

1. Toggle see thru mode or invisible mode using hotkey or option in toolbar.
2. Go into transparency options menu.
3. Switch from "see thru" mode to "invisible" mode if not toggled already.
4. Load into a new scenario/save/server and notice results.

**Comment by Gymnasiast** [comment]
This is a long story, but was caused by misinterpretation of unclear code and an attempt to fix it. We’ll fix it for the next release, but it needs some untangling.
