### ISSUE TITLE
"Force park rating" cheat doesn't reset when opening a different park

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#22726]
### Operating System

Windows 10

### OpenRCT2 build

v0.4.0 and newer

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

When the new save format was introduced, the cheats saved with the park, and when you open up a new scenario they all turn off again. However, this doesn't happen with the "force park rating" cheat, that one stays on when you load a saved game or open up a new scenario.

### Steps to reproduce

1. Turn on the force park rating cheat
2. Load up a different park
3. Check the cheat menu

**Comment by 733737** [comment]
Force Park Rating also does not persist through saving and loading a game. When you load a game that had this cheat enabled, the park rating will return to being calculated.

**Comment by XWeiJ** [comment]
So basically someone forgot to add this particular cheat to the save file? Do you mind if I try to tackle this? It seems like a hopefully not too difficult problem for a beginner like me to fix.
