### ISSUE TITLE
Linux builds missing on https://openrct2.io/download/develop

### ISSUE THREAD

**Issue by cheweytoo** [OpenRCT2/OpenRCT2#22737]
### Operating System

N/A

### OpenRCT2 build

N/A

### Base game

N/A

### Describe the issue

There are no Linux builds on https://openrct2.io/download/develop - despite there being successful builds from the CI runs.

### Steps to reproduce

- go to https://openrct2.io/download/develop
- find no Linux builds

**Comment by Gymnasiast** [comment]
I was originally going to close this issue as we are not responsible for .org. But I noticed that .io had the same problem.

**Comment by cheweytoo** [comment]
Ah, sorry. I'll point my dev-build auto downloader the right way from now on then.

**Comment by janisozaur** [comment]
They've grown too large. With current upload method there is a cap of 100MB, which we hit. I looked into that some years ago (https://github.com/OpenRCT2/OpenRCT2/pull/19582) and if I recall correctly, there is another way of uploading stuff that has higher limits (250MB? no limits?), but would have to dig to find it once again.
