### ISSUE TITLE
{BLACK} appears in the console when using custom theme

### ISSUE THREAD

**Issue by 733737** [OpenRCT2/OpenRCT2#22742]
### Operating System

Windows 11 Pro Insider Preview Canary

### OpenRCT2 build

OpenRCT2, v0.4.14-50-g4f8dd9e (4f8dd9e on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

when you use console, it says {BLACK} for no reason when you use my custom theme

### Steps to reproduce
copy my theme to themes folder
in game select my theme in options menu
open the console

### Attachments
[Purplink.json](https://github.com/user-attachments/files/17069523/Purplink.json)

_No response_

**Comment by J-PIE-314** [comment]
I was not able to reproduce this bug on the latest develop version of OpenRCT2 for Windows 10, 64-bit. Is this bug still occurring on your end? How are you using the console (as mentioned in **Describe the issue**)?

**Comment by 733737** [comment]
Every time I open the console the word {BLACK} is there and the cursor is offset. It has not been fixed.

**Comment by 733737** [comment]
It does not appear in the default theme.

**Comment by 733737** [comment]
![console](https://github.com/user-attachments/assets/97e083b2-a923-4fc7-8942-9a81be57d0f1)

**Comment by J-PIE-314** [comment]
Refreshing the OpenRCT2 directory has removed bugs from my game in the past. Hopefully it will do the same for you. 🙂

**Comment by 733737** [comment]
@mrmbernardi this seems like something you could fix

**Comment by 733737** [comment]
I just verified as of the latest build this issue still occurs with the Purplink theme listed for download.

**Comment by mrmbernardi** [comment]
The issue is more complicated than it seems as it appears to be the result of a deficiency in the formatting code. I'll try and come up with a fix.
