### ISSUE TITLE
Multiplayer sometimes crashes when setting staff patrol area

### ISSUE THREAD

**Issue by FlukiestEmperor** [OpenRCT2/OpenRCT2#2275]
If the server sets the patrol area, it can sometimes crash the client.

If the client sets the patrol area, it can sometimes crash the server.

For me it has crashed a few different places when testing

1) in sub_6A8B12 on map_element_get_type(mapElement)

2) in map_update_tiles() on map_get_surface_element_at(x, y)

3) In memcpy.asm

**Comment by jackinloadup** [comment]
Maybe related or maybe another issue entirely. Adding new staff members on one client works but the other client wont have staff member placed.

**Comment by jackinloadup** [comment]
Ah the issue I reported above is handled by #1943

**Comment by IntelOrca** [comment]
Yes there are a number of reasons why peep place / pickup does not work. It is going to require more multiplayer specific logic that was never in the original game.

**Comment by IntelOrca** [comment]
Probably fixed.
