### ISSUE TITLE
Load/save dialog does not show symbolic links

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#2277]
This makes it impossible to load files from hidden folders, among other things.

**Comment by IntelOrca** [comment]
Symbol links seem to work fine in Windows, so I assume this is only a bug on Linux.

**Comment by janisozaur** [comment]
yes, it's linux-specific. We check for `DT_DIR` but should really support more, perhaps just adding `DT_LNK` is enough.
