### ISSUE TITLE
Shift Map API Plugin re-orders track supports in Tile Inspector, randomly.

### ISSUE THREAD

**Issue by tbarford** [OpenRCT2/OpenRCT2#22780]
### Operating System

Win 11 64 bit

### OpenRCT2 build

OpenRCT2-0.4.14-17-g14f9296 develop

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

When using the map shift plugin to resize the map, if there are track set below surface in the tile inspector, they are (seemingly randomly) reordered. I reproduced this on a fresh save to demonstrate. 

These Supports set under surface
![image](https://github.com/user-attachments/assets/30dc35c1-f0b2-41a0-9c32-23421292af18)

Map shifted, these supports re-ordered
![image](https://github.com/user-attachments/assets/29d1edc9-742f-42ee-bc4b-5137a6a3f9b1)

Before and after save file attached.
[map-shift-supports_reorder-bug.zip](https://github.com/user-attachments/files/17027726/map-shift-supports_reorder-bug.zip)

### Steps to reproduce

Build a coaster. Move some sections of the coaster under surface, using the tile inspector. Use Map shift plugin to resize map.

**Comment by tbarford** [comment]
@fidwell I wasn't sure if there was somewhere specific I could open the issue, so I opened it here. Love, therty.

**Comment by Gymnasiast** [comment]
I’m honestly not sure if we can fix this (or should attempt to). It’s quite a fiddly operation.

**Comment by tbarford** [comment]
Yep I know that it just calls the API, that's why I titled it as such, but figured I should include fidwell.

**Comment by tbarford** [comment]
Oh daaaaaamn - that makes sense.... so even if you only shrink by an even number it will still get 'reordered' as you move 'through' the odd number reorder - the track pieces are being fully redrawn.... wow. @Gymnasiast will the new support drawing refactor effect this again?

**Comment by Gymnasiast** [comment]
No worries, I prefer a false alarm to an unreported bug. You can close your own issues, by the way.

I have vague plans to add a tile element flag to block supports, but that is a long way off - I also want to use it to improve RCT1 import, which puts supports on more pieces than RCT2 does.
