### ISSUE TITLE
Mini roller coaster paint code triggers assertion

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#22796]
### Operating System

Windows 10 64-bit

### OpenRCT2 build

eb664a2960f7c3029f3314ee5186273cec9cbcb6

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

https://github.com/OpenRCT2/OpenRCT2/blame/eb664a2960f7c3029f3314ee5186273cec9cbcb6/src/openrct2/paint/track/coaster/MiniRollerCoaster.cpp#L5284C12-L5286C41

This code triggers an assertion because the direction argument is greater than or equal to kNumOrthogonalDirections, which fails the assertion check in RotateMetalSupportGraphic.
```cpp
            MetalBSupportsPaintSetupRotated(
                session, supportType.metal, MetalSupportPlace::LeftCorner, (direction & 1) ? 42 : 38, direction, height,
                session.SupportColours);
```
```cpp
static inline MetalSupportGraphic RotateMetalSupportGraphic(MetalSupportType supportType, Direction direction)
{
    assert(direction < kNumOrthogonalDirections);
    return kMetalSupportGraphicRotated[EnumValue(supportType)][direction];
}
```

@Gymnasiast can you take a look at this?

### Steps to reproduce

1. Run the game with assertions enabled
2. Build a mini roller coaster diagonal steep slope piece

**Comment by Gymnasiast** [comment]
From the looks of it, I switched around the `special` and `direction` parameters there.
