### ISSUE TITLE
Reused "real" names for staff

### ISSUE THREAD

**Issue by sta5is** [OpenRCT2/OpenRCT2#22809]
### Operating System

Windows 11, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.14-59-g4b44f4f (4b44f4f on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

As requested by @AaronVanGeffen for issue tracking:

The issue concerns the "show real name" options. When enabled:

1) The same names are reused for different types of staff. For instance, the first handyman will be named Bernard C. and the first mechanic is also named the same. This also applies to the security guard and entertainer staff. Subsequently, the next name, Lindsey C. is used for all the second staff of each type.

2) The same names are always used. First staff is always named Bernard, second is Lindsey, third is Cynthia, and etc. I tested with different scenarios and the names used are in that same ordered. Would it be possible to assign their names more randomly?

### Steps to reproduce

1. Enable show real name of staff in options
2. Hire any staff type
3. Hire a different staff type
4. Observe their assigned names and notice they are the same

**Comment by andreaxhearts** [comment]
Hmm, I didn't realize names weren't random. Yes, each staff type starts with the first hire being a different name compared to the other, but the names _are in an ordered list._

Maybe it could be a new option. I dunno. makes sense to me...
Well hey, there's a plugin idea for someone to make.
