### ISSUE TITLE
Waiting 7 seconds in title sequences makes the sequence stop

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#2284]
If you tell the script to wait 7 seconds, it will get stuck and not move on. You will look at that frame for ever and ever, until you change the script to use any number other than 7 seconds.

I have a feeling that having 7 as a coordinate also makes bad things happen, but I don't have concrete evidence.

Discovered in build A988 (fb6a90a)

**Comment by Overv** [comment]
Yes, any command with 7 as last parameter stops the script because of [this line](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/title.c#L442) (`TITLE_SCRIPT_END = 7`).
