### ISSUE TITLE
Ride editor have a bug of "selecting guests/staff name" on it, despite being not available in the tab for the game

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#22863]
### Operating System

Windows 11, 64-Bits

### OpenRCT2 build

OpenRCT2, v0.4.14-156-gd4dc626 (d4dc626 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Since OpenRCT2, v0.4.14-156-gd4dc626 (d4dc626 on develop), this bug happened for some reason on the ride editor...

### Steps to reproduce

1. Open Ride Editor
2. Select everything
3. Click on "Next... conception of coasters"
4. Error saying "no peeps names option selected" with an never visble tab in the selector in the Ride Editor

### Attachments

https://github.com/user-attachments/assets/867d7eaa-1d9e-4f94-998c-9338b4ab99d9

**Comment by Gymnasiast** [comment]
@AaronVanGeffen
