### ISSUE TITLE
Develop build (Linux) not working

### ISSUE THREAD

**Issue by j3nesis87** [OpenRCT2/OpenRCT2#22868]
### Operating System

Linux Mint 22

### OpenRCT2 build

OpenRCT2 v0.4.14-585214f develop

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Describe the issue

Nightly build (https://github.com/OpenRCT2/OpenRCT2/commit/585214f3d2c5c6504817cb959ac870e508182308) is not working.

Since ORCT2 updated overnight, I can't get it to work. I have tried reinstalling it, reinstalling RCT1 and 2 (from GOG installers using Wine), but it still does not work. I get a glitchy main menu with the music playing, the windows all persist (they don't close) and I get errors when trying to open a park. 

v0.4.13 (from Master https://launchpad.net/~openrct2/+archive/ubuntu/master) _does_ work.

(Please move this to correct area if 'Issues' is wrong.)

### Steps to reproduce

1. Update to latest ORCT2 Nightly (https://openrct2.org/downloads/develop/latest)
2. Run ORCT2, cannot get further

### Attachments

![Screenshotfrom2024-09-3012-48-05 png f5077ea3dd2a875b511fcd0a00c2dc41](https://github.com/user-attachments/assets/bb996a3a-f02a-4d41-969a-c6e718afad60)
![Screenshotfrom2024-09-3012-43-00 png 827d984f1c60d912b8538e631fcdb530](https://github.com/user-attachments/assets/f8185e46-eec8-42d6-880e-00c0c38252c6)

**Comment by janisozaur** [comment]
Which version are you using? Portable, AppImage or some other? Can you post logs?

**Comment by j3nesis87** [comment]
The one you get from this:

https://openrct2.org/quickstart/install/linux/debian-ubuntu-mint

Sorry, I'm fairly new to Linux. 

How would I activate logging, and where are the logs kept?

**Comment by janisozaur** [comment]
We'll check up on that. ping @qwertychouskie just in case

**Comment by Gymnasiast** [comment]
@janisozaur I need to update the Launchpad objects. That’s why I assigned myself.

**Comment by janisozaur** [comment]
Ah, I see. Thanks

**Comment by Gymnasiast** [comment]
I pushed an update, which should hopefully mean that the PPA builds should be fixed in ~2 days.

**Comment by qwertychouskie** [comment]
I just triggered a manual import and build, the fixed version should be available in a matter of minutes.

**Comment by qwertychouskie** [comment]
The fixed build is published, this issue can be closed.

**Comment by Gymnasiast** [comment]
Thanks!
