### ISSUE TITLE
Refactor tile elements into separate units

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#22875]
Code around tile elements is heavily fragmented, the goal should be to separate all the various elements into their respective unit. As an example, PathElement is mostly implemented in Footpath.cpp and some other places. It should be rather world/elements/FootpathElement(.h|.cpp). Additionally there should be no complex logic other than various getter/setter to make the access to various bit packed fields easier, something like FootpathElement::Update should not exist and instead have this functionality implemented in Footpath.cpp under namespace World::Footpath::Update receiving the path element as the argument. By doing this we have clear separation of concern, in OpenLoco we have it structured like that as well and it makes discovery and navigation lot easier.

The todo list:
- [ ] SurfaceElement, world/elements/SurfaceElement.cpp ;  world/elements/SurfaceElement.h
- [ ] FootpathElement, world/elements/FootpathElement.cpp ;  world/elements/FootpathElement.h
- [x] TrackElement, world/elements/TrackElement.cpp ;  world/elements/TrackElement.h
- [ ] SmallSceneryElement, world/elements/SmallSceneryElement.cpp ;  world/elements/SmallSceneryElement.h
- [ ] LargeSceneryElement, world/elements/LargeSceneryElement.cpp ;  world/elements/LargeSceneryElement.h
- [x] EntranceElement, world/elements/EntranceElement.cpp ;  world/elements/EntranceElement.h
- [x] WallElement, world/elements/WallElement.cpp ;  world/elements/WallElement.h
- [x] BannerElement, world/elements/BannerElement.cpp ;  world/elements/BannerElement.h

We should also probably move TileElement.cpp under world/elements. 

**Please DO NOT start working on this, lets first see if we all agree on this.**

**Comment by Gymnasiast** [comment]
That sounds lovely, I have wanted this for a long time, but never managed to untangle the TileElement.h spaghetti.

I have already done `EntranceElement.cpp` a while ago. However, this is in the `tile_element` subdirectory, rather than `elements`. That directory would have my preference over `elements`, but apart from that I’m fully behind this. :+1:

**Comment by ZehMatt** [comment]
> That sounds lovely, I have wanted this for a long time, but never managed to untangle the TileElement.h spaghetti.
> 
> I have already done `EntranceElement.cpp` a while ago. However, this is in the `tile_element` subdirectory, rather than `elements`. That directory would have my preference over `elements`, but apart from that I’m fully behind this. 👍

No strong opinion about the folder name, however I would put emphasis on keeping the name small so there is less to type and less to read.

**Comment by Gymnasiast** [comment]
Let’s see what others say, then.

**Comment by tupaschoal** [comment]
I'm all in favour too and am with Hielke, if the folder already mentions elements, the files themselves inside it won't need to repeat themselves.

**Comment by Gymnasiast** [comment]
They will have too. because files named Track.cpp, Entrance.cpp etc. already exist elsewhere, and PCH cannot handle two files with the same name, even if they’re in different folders.

**Comment by ZehMatt** [comment]
> They will have to. because files named Track.cpp, Entrance.cpp etc. already exist elsewhere, and PCH cannot handle two files with the same name, even if they’re in different folders.

Yeah its one of the unfortunate C++ things, we don't have to necessarily put them in a sub folder I would be fine if its just in world, at least the code gets nicer.

**Comment by duncanspumpkin** [comment]
LargeScenery.cpp is already only for the element so just a rename required there.
