### ISSUE TITLE
Lift stations bug

### ISSUE THREAD

**Issue by Remonvdwal** [OpenRCT2/OpenRCT2#22876]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.14 (c53404d on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

The bug also exists in the original game (RCT2/RCTC)

### Describe the issue

When building a lift, i am only able to place an entrance and exit on floor station. You can see in the picture that the placement of entrance/exit at the bottom station affect the station on the higher floor. Problem might have to do with the fact that the stations have no unique index. I don't know whether this have always been the case for the lift ride.

### Steps to reproduce

1. Open park
1 Build lift ride with 2 stations
2 Build entrance and exist on both stories

### Attachments

![Funland 2024-10-01 14-10-21](https://github.com/user-attachments/assets/d8777e16-5c10-444e-9ca7-29214fdf4a68)
![Funland 2024-10-01 14-14-02](https://github.com/user-attachments/assets/36b6f59f-c565-423a-8221-b9b0a133f7f6)

**Comment by mrmbernardi** [comment]
The Six flags over Texas map from default RCT2 has an elevator with an overlapping entry (or exit, I forget). I thought this must be a regression so I booted up RCT2 and sure enough building exits and entryways on the upper floors worked fine.

![image](https://github.com/user-attachments/assets/6ce0d43b-621c-4da7-b1d0-35e849b9b62f)

**Comment by mrmbernardi** [comment]
I just tested the latest release and its also still possible. This appears to be a regression on the develop branch.

**Comment by Gymnasiast** [comment]
Bisecting points to 5f92d1920b1f1817b8ddfff9a87b0517cdc113a7 as the first bad commit. Looking through it, I have some ideas where it could reside.
