### ISSUE TITLE
Corrupted track design when saving Corkscrew Roller Coaster in reverse incline mode

### ISSUE THREAD

**Issue by FlukiestEmperor** [OpenRCT2/OpenRCT2#2288]
The simplest way to test this it so go into the roller coaster designer, select the corckscrew roller coaster, place down the Cobra track design, test it then save it.

This picture shows the original Cobra and the Cobra after I saved the design with a different name then placed it back down from the track list. It's missing most of the station and the backwards chain lift.

![capture](https://cloud.githubusercontent.com/assets/1393110/11099157/5eb0481a-886f-11e5-832d-a11ff366b658.PNG)

This will happen if you create your own design from scratch, and will happen in scenario mode. Just as long as you save the track with the mode of Reversed-Incline launched shuttle mode.

**Comment by duncanspumpkin** [comment]
Yeah it happens with any coaster that doesn't do a complete circuit as far as i remember.

**Comment by Gymnasiast** [comment]
Yeah, I think so. #1834 reports the same problem with the Shuttle Loop.

**Comment by duncanspumpkin** [comment]
Fixed in the pre-release for 0.0.3
