### ISSUE TITLE
Options under the "Eye" button cannot be turned off for saved games

### ISSUE THREAD

**Issue by jcurbaniak** [OpenRCT2/OpenRCT2#22894]
### Operating System

Windows 10 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.14 (18492da) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

When one or more options are turned on during gameplay for the "eye" button and even if subsequently turned off before a Save Game, the options return when the Load Game is used.

### Steps to reproduce

1. Turn on an option with the "eye" button such see through supports.
2. Run the game for a bit
3. Turn off the "eye" button options.
4. Save the game.
5. Load the same game.
6. The "eye' options are back on in the reloaded game.

**Comment by Gymnasiast** [comment]
Works as intended. These are not saved in the .park file

**Comment by jcurbaniak** [comment]
Quite inconvenient I have to say. Once turned on they have to be turned off every time the game is loaded.

**Comment by sjoerddebruin** [comment]
I think your description was maybe a bit vague, but this is the transparency issue that has been fixed in develop and will be included in the release in a few days.

**Comment by jcurbaniak** [comment]
I described it the best I know how.   What was vague?
