### ISSUE TITLE
Cannot alter footpath with Own All Land cheat on

### ISSUE THREAD

**Issue by jcurbaniak** [OpenRCT2/OpenRCT2#22904]
### Operating System

Windows 10, 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.14 (18492da) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

When the "Own All Land" Cheat is turned on, a footpath outside the original park boundary cannot be altered.   Get message "Land Not Owned By Park".

### Steps to reproduce

1. Turn on "Own All Land" Cheat for a park
2. Attempt to alter a footpath outside the original park boundary.

### Attachments

![Image](https://github.com/user-attachments/assets/3adb0a66-6daa-4c63-866c-121fb9c7874b)

**Comment by MASHzj** [comment]
The footpath to the entrance normally remains outside the park. Did you hide park fences?

**Comment by jcurbaniak** [comment]
Yes, I did.

**Comment by MASHzj** [comment]
Then it's normal behaviour.

**Comment by 733737** [comment]
Own all land does not break the entrance pathing. This is not a bug. Use sandbox mode to edit the pathing or own the land, plus set a new guest spawn point.

**Comment by jcurbaniak** [comment]
So I guess “OWN ALL LAND” does not really mean that?

 

Jerry Urbaniak

**Comment by 733737** [comment]
If you literally own all the land, it would break the park entrance. Sandbox mode is for remaking the park entrance.
