### ISSUE TITLE
Moving camera when scrolling in and out

### ISSUE THREAD

**Issue by AtomicSnails** [OpenRCT2/OpenRCT2#22918]
### Operating System

Windows 11 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.15 (c7c8fad822) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

Issue with zooming and and out using both scroll wheel and in game button. When zooming in or out of view on any zoom angle, camera location moves to the left (Amount of zoom on initial zoom in or out effects how much movement there is) Attempted reenabling and disabling "zoom moves to cursor" and has no change. issue occurring on all maps local or multiplayer, previously existed or new park

### Steps to reproduce

1 Open any park or start a new park
2 Zoom in or out on view
3 camera moves to left regardless of isometric orientation

**Comment by Gymnasiast** [comment]
@mrmbernardi
