### ISSUE TITLE
GIF Recording

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#2293]
I think it would be handy for OpenRCT2 to have an in-game animated gif encoder. This would make it easy for players to record short videos of the game either to demonstrate bugs or their creations.

This could be implemented by having a shortcut key for starting / ending a recording. When the recording is started, the game will keep writing each game frame to a gif file until the end recording shortcut key is pressed.

* Starting and ending the recording could be the same shortcut key.
* The gif frame size would always be the size of the window, like screenshots. You can already press T to hide the toolbars.
* GIF has a 256 colour palette so the quality should be lossless.

This looks like a nice small library that would do the job well:
https://github.com/ginsweater/gif-h

**Comment by adrian17** [comment]
Opinion: I'm not sure if leaving users to use dedicated tools isn't a better choice - especially if some of them allow just as easy recording of .mp4 files, which can have sound, better quality (although that indeed doesn't matter here) and, most importantly, are 1-2 orders of magnitude smaller.

**Comment by janisozaur** [comment]
If such a tool would come to be, I'd argue that a red `● REC` overlay sign would be very useful feedback for the user, especially in case when you clicked some key and it triggered recording without you knowing it.

**Comment by vzybilly** [comment]
this whole thing would be quite nifty. I can't run recording software on my
computer because of some issue that affects pretty much all of them... I
think it was my video card but that's off topic, main point, if this gets
implemented then I could finally get non screen shots of the game

**Comment by IntelOrca** [comment]
@adrian17 the arguments for this are that it works on all platforms and produces GIFs which are small yet lossless. They won't skip any frames because the game has control of the recording. If the player wanted sound then yes - they use 3rd party software, the intention for this is to quickly capture some footage to stick on github or reddit either as a bug report or a coaster run.

**Comment by Patrik356b** [comment]
Would be nice to have

On Thu, Nov 12, 2015 at 7:06 PM, Ted John <notifications@github.com> wrote:

> @adrian17 <https://github.com/adrian17> the arguments for this are that
> it works on all platforms and produces GIFs which are small yet lossless.
> They won't skip any frames because the game has control of the recording.
> If the player wanted sound then yes - they use 3rd party software, the
> intention for this is to quickly capture some footage to stick on github or
> reddit either as a bug report or a coaster run.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenRCT2/OpenRCT2/issues/2293#issuecomment-156186299>.
>



-- 
Best regards; Hexile

**Comment by raidcookie** [comment]
It would definitely be nice to have an ingame tool for making GIFs. Probably something like [LICEcap](http://www.cockos.com/licecap/), where you can adjust the size of the footage by resizing the actual tool.

**Comment by RollingStar** [comment]
WebM, or MP4/MKV (x264) would be good as well. GIF is a decrepit file format *older than RCT1*. A lossless 256 color MKV is going to be smaller and faster-loading than a GIF.

**Comment by IntelOrca** [comment]
@RollingStar gif is more widely supported and simpler to implement. WebM or MP4 encoders would require large library dependencies.

**Comment by IntelOrca** [comment]
I spiked this awhile ago and I don't think its worth it. I'll leave the branch on my fork.
