### ISSUE TITLE
Recreate the Required RCT2 Files page in the wiki

### ISSUE THREAD

**Issue by R3Ked** [OpenRCT2/OpenRCT2#22954]
I want to play this but don't know how to get it to work with RCT Classic. All the answers I find online redirect me to that page, but it's deleted. I do have a copy of RCT2 somewhere, but I'd have to find it as well as a disc drive for my PC.

**Comment by Gymnasiast** [comment]
That information was completely outdated. Linking to RCT Classic now works the same as it does for RCT2.

Instead, please follow the documentation on installing OpenRCT2: https://docs.openrct2.io/en/latest/installing/index.html
