### ISSUE TITLE
Missing brown dirt path in Six Flags Magic Mountain scenarios

### ISSUE THREAD

**Issue by J-PIE-314** [OpenRCT2/OpenRCT2#22972]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.15 (af7a2de72c on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

The bug also exists in the original game (RCT2/RCTC)

### Describe the issue

There is a brown dirt path missing in both the "Six Flags Magic Mountain" and "Build your own Six Flags Magic Mountain" scenario. The missing path causes guests to get lost. This issue is present in vanilla RCT2 as well.

### Steps to reproduce

None needed, you can always view this issue by loading the aforementioned scenarios and looking in the middle of the map near the ride: "The Escape".

### Attachments

OpenRCT2:

![Image](https://github.com/user-attachments/assets/c7bbf3be-1c66-4db7-b88a-79c2d1c51b7f)

Vanilla RCT2:

![Image](https://github.com/user-attachments/assets/be19ed49-77d8-4880-9715-dc1abd808379)

**Comment by alexpalade** [comment]
I tried to fix this, but park patches cannot modify path tiles, if I'm not mistaken (it's my first contact with the repo). I know you made a similar observation in another issue. Perhaps this must wait until the patch system gets this functionality.

It can be seen here, the function ApplyTileFixes only handles tiles of type "track": https://github.com/OpenRCT2/OpenRCT2/blob/0669eba3b27d3383468d8a7912ea35f8dd3fbb99/src/openrct2/rct12/ScenarioPatcher.cpp#L316
