### ISSUE TITLE
.sea verison of Tycoon Park does not show up under scenario list anymore

### ISSUE THREAD

**Issue by ZeeMaji** [OpenRCT2/OpenRCT2#23009]
### Operating System

Linux (Fedora 40)

### OpenRCT2 build

OpenRCT2, v0.4.15

### Base game

RollerCoaster Tycoon 2

### Describe the issue

I use a custom installation of RCT2 which is optimized and has all official RCT content within it, included in this build is the unmodified .sea version of Tycoon Park from RCT Classic.
However Tycoon Park no longer shows up under the extras tab, i can still directly open the scenario file just fine with the file loading menu so it's not corrupt.

This may possibly be affecting other .sea scenarios as well but i don't have a full installation of RCTC on hand to test with presently.

### Steps to reproduce

1. Add tycoon park.sea from RCTC to your RCT2 installation or openrct2 user folder's scenarios folder. Or alternatively switch to RCTC as your base game assets.
2. Delete scenarios.idx to ensure a new scenario index generates.
3. Launch the game, go to the extras tab, tycoon park is not there despite being present in the scenarios folder.

### Attachments

![Image](https://github.com/user-attachments/assets/d2cde7b9-2e4c-48a0-85a5-5771f5738d81)

**Comment by sjoerddebruin** [comment]
Feels like the changes in #22644 are the cause of this, using an artifact of the commit before does show the scenario. @AaronVanGeffen, see the above.

**Comment by AaronVanGeffen** [comment]
Ah, I think this must affect all .sea scenarios, then, not just Tycoon Park. Yikes.

**Comment by AaronVanGeffen** [comment]
Urgh, yeah, it using the S6Importer would fail for .sea files. Consider:
```cpp
        ParkLoadResult Load(const u8string& path) override
        {
            const auto extension = Path::GetExtension(path);
            if (String::IEquals(extension, ".sc6"))
            {
                return LoadScenario(path);
            }
            if (String::IEquals(extension, ".sv6"))
            {
                return LoadSavedGame(path);
            }

            throw std::runtime_error("Invalid RCT2 park extension.");
        }
```

**Comment by AaronVanGeffen** [comment]
Could you test if #23013 fixes the issue? I don't have any .sea files at hand to test with.
