### ISSUE TITLE
Language fallback does not always work when game is set to some languages

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#2301]
![scr85](https://cloud.githubusercontent.com/assets/1478678/11163337/5d135976-8acb-11e5-813a-d27868add535.png)

Happens with Russian, Hungarian, Polish, Spanish, Swedish and Italian.

**Comment by janisozaur** [comment]
What OS?

**Comment by Gymnasiast** [comment]
All my errors are on Linux. (Ubuntu 15.10 AMD64 to be precise).

**Comment by danidoedel** [comment]
Same on Windows...

**Comment by duncanspumpkin** [comment]
Fixed on the pre-release.

**Comment by Gymnasiast** [comment]
:+1:
