### ISSUE TITLE
Scenery Glitch

### ISSUE THREAD

**Issue by BreDanMan** [OpenRCT2/OpenRCT2#23023]
### Operating System

64-bit operating system, x64-based processor

### OpenRCT2 build

OpenRCT2, v0.4.15 (236f4afbd7 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

Only recently when i try to place larger scenery objects (such as the windmill or castle tower pieces) i get a prompt that says the following: "Can't position this here... Can't build underwater!" even though i am on flat land plots and other items can sit on ground level in the same spot perfectly fine. If i do place the problem scenery items, i have to press the shift key and place them significantly higher that ground height. (typical about 5-10 block heights above.) really hoping this can be fixed so i don't have to give up my park that i have already worked hours on.

Anything helps!

### Steps to reproduce

1. select a piece of scenery
2. try to place scenery on an even flat grass surface
3. prompt appears (Can't position this here... Can't build underwater!)
4. press shift key and raise mouse 
5. place scenery where you are able to at a higher point

**Comment by duncanspumpkin** [comment]
I can't reproduce this at all. ![Image](https://github.com/user-attachments/assets/34ef86c8-e028-473a-851b-bd4614e3e4a9)
Are you sure you don't have some plugins enabled that are breaking it?

**Comment by duncanspumpkin** [comment]
Actually never mind i see what is wrong this has been broken for a long time but only now showing due to having the correct types.
