### ISSUE TITLE
Map generator allows map sizes out of range

### ISSUE THREAD

**Issue by DCMeGaMaxX** [OpenRCT2/OpenRCT2#23048]
### Operating System

Windows 10 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.15 (c7c8fad822)

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Normally when resizing the map if you enter a value that is less than 3 or greater than 999, the game will automatically change the value you entered to the highest or lowest allowed. In the map generator window however, it accepts any value between 9,999 and -9,999 and any map size over 1,000 appears extremely glitchy.

(This issue does NOT affect the map resize options in the map window)

### Steps to reproduce

1. Open the scenario editor
2. In the first tab of the map generator window, enter a map size that is either less than 3 or greater than 999 (Can be a negative number)
3. Click the "generate" button when done

### Attachments

![Image](https://github.com/user-attachments/assets/326b4dde-2413-4ca2-b47c-d99ca702168e)
![Image](https://github.com/user-attachments/assets/ddf1a918-4e68-4db8-9e1f-2567402d642e)
![Image](https://github.com/user-attachments/assets/fddca982-aabd-460c-b7e7-ab9ca079ce3d)

**Comment by Gymnasiast** [comment]
When testing the PR, I tried so hard to break it :')

![Image](https://github.com/user-attachments/assets/99ea8c2c-05dc-4585-bbc0-468c846e5f28)
