### ISSUE TITLE
Slope up/down speed inconsistency with mismatched vehicles & track

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#2306]
So for the fun of it, i tried various mismatching of tracks and vehicles using that cheat.

* Double Decker observation tower on rail tracks: works but can not go uphill. Downhill not tested.
* Steam train on giga/steel roller coaster track: downhill speed will match track type, uphill speed will match vehicle type
* Free fall observation tower: works just fine

This should be considered as a low priority issue.

**Comment by Gymnasiast** [comment]
This is expected. IMO this is a `wontfix`, as "fixing" these hacks would litter the code base.

**Comment by Patrik356b** [comment]
Afaik, the only required change would be to overide this type vehicle behavior according to the track.

**Comment by Gymnasiast** [comment]
It's a lot more complicated than that, otherwise I wouldn't say I'm against "fixing" it.

**Comment by Patrik356b** [comment]
I see, nevermind then.
