### ISSUE TITLE
opening window screen: some rides have missing parts

### ISSUE THREAD

**Issue by ghost** [OpenRCT2/OpenRCT2#23111]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.4.15 (c7c8fad822) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

If you start openrct2 and look at the parks that are shown, some rides have missing parts.

Here you see something in the air without any rails (see red) :) It's moving correctly but the rails are not drawn.

![Image](https://github.com/user-attachments/assets/dbcbc618-2b5b-4b10-9832-9bebecccb10e)

### Steps to reproduce

1. run openrct2
2. look at the parks being shown
3.  some rides have missing parts.

**Comment by fidwell** [comment]
This is not a bug. It is possible to build rides with invisible track on purpose, and that is what was done here.

**Comment by X123M3-256** [comment]
> did this exist in the original game too?

Sort of but not in the same way. You could make track invisible by changing the ride type to crooked house, however, not all track pieces would work with this method - the game would crash if you used the wrong ones.

There was another way to make stuff invisible using a corrupt map element which was also a dangerous hack that would often crash the game.

OpenRCT2 makes it a proper feature, you can make any map element invisible. It has so many uses I won't try to list them all, but think of things like shoestring flat rides, car rides used as road traffic, etc.

**Comment by 733737** [comment]
under cheats menu there is an option for tile inspector. Select the tile, then the track element, and uncheck the eye. Alternatively in the cheats menu you can enable extra paint colors, then in ride color schemes set the track to invisible. To use thi to make only part of the track invisible, telect alternative color scheme 1 in the dropdown, then select invisible color, then paint the track rith the paintbrush.
