### ISSUE TITLE
TT's Cradle of civilization scenario shows up under other parks untranslated.

### ISSUE THREAD

**Issue by ZeeMaji** [OpenRCT2/OpenRCT2#23112]
### Operating System

Linux (Fedora 40)

### OpenRCT2 build

Appimage Build https://github.com/OpenRCT2/OpenRCT2/commit/0158c344e7eed11b6e4ec6ae186e5a2905258c1a

### Base game

RollerCoaster Tycoon 2

### Describe the issue

The TT scenario cradle of civilization is showing up under the other parks tab with no translations being applied after refreshing my scenarios.idx.

### Steps to reproduce

1. Download one of the latest develop builds
2. Delete scenarios.idx from your openrct2 documents folder so it regenerates on next launch
3. Launch the develop build, open the scenarios window and cradle of civilization will be in the other parks tab instead of the TT tab and it won't be translated.

### Attachments

![Image](https://github.com/user-attachments/assets/c118c63e-fe12-494f-a0b5-ee88762774e5)

**Comment by AaronVanGeffen** [comment]
Considering we normalise `Civilization` to `Civilisation`, I wonder if this has to do with UK/US differences... I imagine this to be a regression from #23070, but I don't know why.

**Comment by Gymnasiast** [comment]
It was a regression from one of my PRs which did some string handling fixes.
