### ISSUE TITLE
zooming in on the map causes distortion and looks like mine craft after the new update

### ISSUE THREAD

**Issue by jk2493** [OpenRCT2/OpenRCT2#23110]
### Operating System

windows 10, 64bit

### OpenRCT2 build

OpenRCT2,v0.4.15(c7c8fad822) provided by GitHub 

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

I am having issues with the zoom feature, it was working fine before I updated it. when I zoom in on the map now, it shows bad pixels, almost looking like mind craft game. I will attach images on what it looks like. I hope to get this fixed. maybe installed the update wrong? I don't this that is the issue. any help on this would be greatly appreciated.

### Steps to reproduce

1. open game
2. load a game
3. zoom in on the map

### Attachments

![Image](https://github.com/user-attachments/assets/0dd8c71a-f59f-4a17-bb42-32562220e8fd)
![Image](https://github.com/user-attachments/assets/30bfa974-46ef-4894-84cf-34a7458b7b43)

**Comment by Gymnasiast** [comment]
You just zoomed in too much. We added two extra zoom levels, which will enlarge the pixel. Just zoom back out to the regular "1x" zoom and it will look like it did before.

**Comment by jk2493** [comment]
thank you. i really thought something was wrong.

**Comment by Gymnasiast** [comment]
No worries.
