### ISSUE TITLE
LSM Launch Coaster Max Speed Incorrect

### ISSUE THREAD

**Issue by zViper25** [OpenRCT2/OpenRCT2#23133]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2 v0.4.15 (9be7b89d8f on develop)

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

This is a development issue

### Describe the issue

I love the work done for the new LSM Launch Coaster coaster type but I've discovered that the max booster speed for the LSM Launch Coaster is set to the Twister Coaster's max of **67mph (107kph)** rather than the max boost speed of **134mph (215kph)** for the Giga Coaster, which seems unintended, especially since the coasters that the LSM Launch Coaster is based on regularly has launch speeds of well over 67mph (107kph) - notably Maverick at Cedar Point with its second launch being **72mph (115kph)**. Without the increase, it feels as though you're limited to using the Giga Coaster coaster type without all the cool new sprites that were added for the LSM Launch coaster.

_(I'm sorry in advance if this is considered a feature request!)_

### Steps to reproduce

1. Open Object Selection
2. Select LSM Launch Coaster coaster type
3. Open build ride window
4. Construct a LSM Launch Coaster with a station piece
5. Open special track pieces tab and select booster
6. Hold "+" button on boost speed prompt, it should max out at 67mph (107kph).
7. Repeat steps 1-5 but for Giga Coaster coaster type
8. Hold "+" button on boost speed prompt, it should max out at 134mph (215kph).

### Attachments

See video for example
https://youtu.be/JNf5MowXkUw

_Note: Yes I'm aware that the Giga Coaster needs a longer booster track to reach the 134mph max speed but this video is more so focused on the LSM Launch Coaster not being able to reach a higher top speed than 67mph on its launch compared to the Giga Coaster._

**Comment by karst** [comment]
This is intentional, I might want to bump the maximum speed if it allows in the future to around 130kmh. The acceleration is the same as the giga coaster on the other hand, but it's more useful for this ride to have more control over the speed. Otherwise you go in twice the steps, while most these rides will be close to the ground.
