### ISSUE TITLE
Giga Coaster Yellow Taxi vehicles render incorrectly on banked turns

### ISSUE THREAD

**Issue by 1111132123** [OpenRCT2/OpenRCT2#23142]
### Operating System

win10 64bit

### OpenRCT2 build

OpenRCT2, v0.4.16 (c1082a3d6c on master) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

The bug also exists in the original game (RCT2/RCTC)

### Describe the issue

I've found a bug with the Yellow Taxi vehicles on the Giga Coaster. When the Yellow Taxi vehicles pass through banked turns, they do not render correctly. The graphics for the vehicles remain the same as when they pass through unbanked turns, meaning they do not tilt appropriately for the banked angle. As a result, the vehicles appear as if they are floating or not properly aligned with the track, leading to an unrealistic visual experience.

### Steps to reproduce

1. Build a Giga Coaster that includes both banked and unbanked turns.
2. Select the Yellow Taxi vehicles for the coaster.
3. Observe how the vehicles do not tilt in accordance with the banked turns, rendering them as if they are on unbanked turns.

### Attachments

![Image](https://github.com/user-attachments/assets/c88e4c67-81d1-4562-aa73-cb26b6dfe95d)
![Image](https://github.com/user-attachments/assets/c4c6eae9-85e3-4894-b9b6-1c05b8328094)

**Comment by 733737** [comment]
This is not a bug. The trains were not designed for banked slopes and cannot be changed because we do not have access to the original models used.

**Comment by Gymnasiast** [comment]
This is a bug that we unfortunately cannot do much about, for reasons that 73 and Frederic have already mentioned. OpenRCT2 already handles this type a little bit more gracefully than vanilla does, as it disables the banked turns if it’s the only vehicle available.
