### ISSUE TITLE
Deleting tile make game unable to load

### ISSUE THREAD

**Issue by Vetador** [OpenRCT2/OpenRCT2#23153]
### Operating System

windows 10

### OpenRCT2 build

OpenRCT2 0.4.16

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

When I delete a tile using show tile inspector, the tile can't be brough back and when saving and loading the game, it show "load game failed to low, file contains invalid data"

Also when I deleted the tile, it appeared a new tile that is 255 block high and I can't lower it below 248 or around that.

### Steps to reproduce

Open show tile inspector, delete a tile completely. Save, and load the game.

**Comment by janisozaur** [comment]
Does it matter which time you delete? In which scenario?

**Comment by Vetador** [comment]
> Does it matter which time you delete? In which scenario?

I did it in a custom scenario with a 999x999 map.

**Comment by Gymnasiast** [comment]
Please attach an affected save.
