### ISSUE TITLE
Long text for scenario name

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#2316]
There is "Great Wall of China Tourism Enhancement" scenario in original RCT2, but I cannot input this string fully at scenario editor. (It becomes "Great Wall of China Tourism Enh". maybe it is max 32 letter.)
Don't you think it must be longer?

**Comment by Overv** [comment]
Confirmed, internally the limit is 64.

**Comment by telk5093** [comment]
Nice :+1:
