### ISSUE TITLE
crash while building the new LSM coaster

### ISSUE THREAD

**Issue by Pectacq** [OpenRCT2/OpenRCT2#23173]
### Operating System

windows 11 x64

### OpenRCT2 build

OpenRCT2, v0.4.16 (c1082a3d6c on master) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

When i want to build the game freezes and i have to force quit it via task manager

### Steps to reproduce

Just select the lsm coaster from the coastermenu

**Comment by fidwell** [comment]
I'm not seeing the same behavior on a fresh install of the portable Windows x64 version. I wonder if your installation did not work completely. What steps did you take to install the game? If you uninstall and reinstall completely, do you still have this issue?
