### ISSUE TITLE
B&M Large Half Loop pieces not rendering on older saves

### ISSUE THREAD

**Issue by Xtreme97-RCT** [OpenRCT2/OpenRCT2#23189]
### Operating System

Windows 11, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.16 (fd90afeb46 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

After upgrading to the latest develop build with the new B&M track pieces, loading older save games (both .park and .sv6) causes the Large Half Loop pieces on existing coasters to not render. Building a new coaster does render the track piece.

Example of Kumba:
<https://www.nedesigns.com/park/1536/kumba/>
![Image](https://github.com/user-attachments/assets/5e0f238d-f0c1-4178-a0b2-4b8cd8248f8f)

The pieces have been made invisible judging by Tile Inspector.
![Image](https://github.com/user-attachments/assets/70c8be7d-1788-496c-bc0b-049e9463c758)

### Steps to reproduce

1. Open an old save with a twister roller coaster built before upgrading to this develop version, featuring large half loops.
2. Notice the loop pieces don't render. Tile Inspector shows that the pieces are there but have been made invisible.

**Comment by karst** [comment]
They've been turned invisible by import code. I just sent out a patch #23188

**Comment by Xtreme97-RCT** [comment]
> They've been turned invisible by import code. I just sent out a patch [#23188](https://github.com/OpenRCT2/OpenRCT2/pull/23188)

Thank you!
