### ISSUE TITLE
Search not finding everything

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#2319]
For example when you type "Loop" you'd expect it to find the Looping Coaster.

![Looping Coaster not found](http://i.imgur.com/3HrQ28c.png)

**Comment by IntelOrca** [comment]
Search doesn't search the ride type column, only the ride / vehicle column. Thus this is a feature request.

**Comment by Broxzier** [comment]
Ah, I had no idea. From a design perspective that means it's not clear to the end-user, and from the user perspective it looked like a bug.

**Comment by IntelOrca** [comment]
The ride type column was added after the search feature, if it had been implemented the other way round it would have been obvious at the time.

**Comment by Broxzier** [comment]
That makes perfect sense and now I know I see it works perfectly fine, I just wanted to let you know that it felt like it wasn't before.
