### ISSUE TITLE
Scenario Step Needed in Scenario Editor Finish Building 5 Roller Coasters

### ISSUE THREAD

**Issue by 60trainhunter** [OpenRCT2/OpenRCT2#23203]
### Operating System

Windows 11

### OpenRCT2 build

v0.4.16

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

This is a development issue, The bug also exists in the original game (RCT2/RCTC)

### Describe the issue

EXTRA STEP NEEDED to Set up the 5 Partially Built Roller Coasters and it's MISSING. It wont let you Save the Scenario till those are built.

### Steps to reproduce

Step 1 Start Scenario Editor Step 2 Select at least 10 Roller Coasters object selection 5 MUST be in Preinvented. Step 3 Set up Map. Step 4 Skip to Objective Selection Select Objective Finish Building 5 Roller Coasters. Step 5 Try to Save Scenario.

### Attachments

![Image](https://github.com/user-attachments/assets/0ec485c0-d863-455a-9b81-c435c44dab7b)

**Comment by Gymnasiast** [comment]
This is not the correct workflow. Rather, you create a scenario, partially build up the 5 roller coasters in question, and then use the "convert saved game to scenario" feature to create the final one, which will also make sure you cannot remove any of the pre-existing coasters.
