### ISSUE TITLE
Guests causing frequent multiplayer desyncs when Uncap FPS is enabled

### ISSUE THREAD

**Issue by ATMarcks** [OpenRCT2/OpenRCT2#23206]
### Operating System

Windows 11, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.16 (c1082a3d6c on master) provided by GitHub | Windows (x86-64)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is specific to multiplayer

### Describe the issue

I am experiencing frequent desyncs on multiplayer between headful clients with the uncapped FPS setting turned on. The problem appears to have been introduced in either v0.4.15 or v0.4.16, as I started experiencing this issue after upgrading from v0.4.14 to v0.4.16. It seems to be easily reproducible locally and over WAN play with someone else on their own machine and instance. I haven't tried to reproduce the issue using a headless server.

I've attached multiple desync logs. `Sprite modifications (Guest)` `Peep::Destination` seems to consistently be the culprit, and the more guests in the park the more quickly a desync occurs. ~~Potentially related to https://github.com/OpenRCT2/OpenRCT2/pull/22774~~

### Steps to reproduce

1. Start two headful instances of OpenRCT2 on Windows 11 64-bit (haven't tried other operating systems)
2. On the title screen, open the options and turn on Uncapped FPS on both instances
3. Start a server on one instance. Scenario doesn't seem to matter, but higher guest counts appear to cause more frequent desyncs, so a park with many guests is recommended
4. Join the server on the second instance
5. Wait a couple minutes. A desync occurs usually within seconds, but it can be a few minutes before a desync happens, especially if guest count is low

### Attachments

[desync_18075594017391500126_360847.txt](https://github.com/user-attachments/files/17769648/desync_18075594017391500126_360847.txt)
[desync_18075594017602187103_361689.txt](https://github.com/user-attachments/files/17769647/desync_18075594017602187103_361689.txt)
[desync_18075594017855695807_362702.txt](https://github.com/user-attachments/files/17769649/desync_18075594017855695807_362702.txt)
[desync_18075594026386875899_368265.txt](https://github.com/user-attachments/files/17769644/desync_18075594026386875899_368265.txt)
[desync_18075594027365513287_369637.txt](https://github.com/user-attachments/files/17769646/desync_18075594027365513287_369637.txt)
[desync_18075594016505780343_362935.txt](https://github.com/user-attachments/files/17769645/desync_18075594016505780343_362935.txt)

**Comment by ZehMatt** [comment]
It is very unlikely that desyncs happens because of uncap FPS or the new zoom levels, the render state is local to client and doesn't modify the game state. Do you have any plugins installed?

**Comment by ATMarcks** [comment]
@ZehMatt I do not have any plugins installed. I get a desync 95% of the time in under 30s if I follow my reproduction steps with a park that has 1,500 guests.

To make sure, I've just stood up a server and connected a client to it (both with Uncap FPS settings off) twice, left them up for 10 minutes each time, and didn't experience a desync. I also did a fresh install of OpenRCT2 on a machine that's never had it installed before and I'm able to reproduce the issue there as well, though I'm using the same set of RCT2 game files.

**Comment by ZehMatt** [comment]
Interesting, I will have to look into that, this might be my doing with #22836
