### ISSUE TITLE
Game crash after opening the inventions list

### ISSUE THREAD

**Issue by danidoedel** [OpenRCT2/OpenRCT2#2320]
Load a title sequence park like mci.sv6 and open the inventions list. The game will crash immediately or after closing the window.

**Comment by Broxzier** [comment]
Confirmed on latest build. Accessing deleted memory (0xffffffff) in `research_finish_item` (research.c).

**Comment by IntelOrca** [comment]
See https://github.com/OpenRCT2/OpenRCT2/blob/develop/CONTRIBUTING.md#reporting-bugs
> Please state which version of the game you are running and where you downloaded it from, e.g. openrct2.com develop 0.0.3 build 1255 (ec25b2f).

**Comment by mrtnptrs** [comment]
No game crash happens anymore and mci.sv6 isn't used anymore for the title sequence. Maybe the savegame was corrupted? I think this issue can be closed.

**Comment by danidoedel** [comment]
mci.sv6 is still crashing with 425fc73979da9cccd7d101fc45a716625d3f898f, but yeah maybe it's just corrupted. I attached a dump file if someone still want to have a look into this.

[mci-dump.txt](https://github.com/OpenRCT2/OpenRCT2/files/321816/mci-dump.txt)
(change .txt to .zip... not sure why zip didn't work)

**Comment by Patrik356b** [comment]
It's a restriction of github

**Comment by danidoedel** [comment]
@Patrik356b What kind of restriction? Others can upload zip without any problems...

**Comment by Patrik356b** [comment]
Nevermind. I just had some trouble the same thing a while ago
