### ISSUE TITLE
Classic wooden coaster's boosters can't be built

### ISSUE THREAD

**Issue by ZeeMaji** [OpenRCT2/OpenRCT2#23210]
### Operating System

Linux (Fedora 40)

### OpenRCT2 build

OpenRCT2, v0.4.16

### Base game

RollerCoaster Tycoon 2

### Describe the issue

The classic wooden coaster can draw the boosters from the wooden coaster and has booster data set to make them functional, but they're not available with the drawable track pieces cheat. They should be made available with the cheat enabled.

### Steps to reproduce

1. Enable the show all drawable track pieces cheat.
2. Try to build a classic wooden roller coaster with boosters, you can't.

**Comment by SpartanFrederic104** [comment]
Checking the ``.extraTrackGroups`` field in line 26 of [src/openrct2/ride/rtd/coaster/ClassicWoodenRollerCoaster.h](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/ride/rtd/coaster/ClassicWoodenRollerCoaster.h) reveals that the classic wooden coaster in fact doesn't even have any cheat-unlockable track pieces. However, lines 34 and 35 have the ``.BoosterSettings`` and ``.LegacyBoosterSettings`` fields, respectively, with both being set to ``{ 0, 68 }``. This is the same booster settings for the RCT2 wooden coaster.

**Comment by ZeeMaji** [comment]
The piece is fully functional if you use ride type changes to build them, it just needs to be added to the extra track pieces group.

The coloring style is handled fine already.

![Image](https://github.com/user-attachments/assets/f91987a1-c3ba-4f9b-a059-5349cca18162)

For the booster settings i would just leave them as is, i don't see a reason to change them.

I'll likely fix this myself in the coming days, i just made this as a reminder so it wouldn't get lost as it's a pretty obscure thing.
