### ISSUE TITLE
Default scenery tabs disappear when changing inventions list ingame

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#2324]
If you change any one thing about the inventions list except "move all to top", it will make all the default scenery tabs disappear.

Happens in 62863db

**Comment by liny-odell** [comment]
I have found a way to recover the tabs. Converting the save file to a scenario seems to bring them back.

**Comment by Gymnasiast** [comment]
Another fix is opening and then closing Object Selection.
