### ISSUE TITLE
Wrong error when placing under track loops

### ISSUE THREAD

**Issue by RogoDarius** [OpenRCT2/OpenRCT2#23266]
### Operating System

Windows 10

### OpenRCT2 build

OpenRCT2, v0.4.16 (c1082a3d6c on master) provided by GitHub

### Base game

RollerCoaster Tycoon Classic

### Describe the issue

Placing buildings and rides too close to a loop or corkscrew piece of a rollercoaster shows an error saying that the supports would be too high, not that the placement is blocked.

### Steps to reproduce

1. Build a corkscrew or loop track piece
2. Attempt to build something under it

### Attachments

![Image](https://github.com/user-attachments/assets/1dad572a-49f6-47cd-9057-80709c2583be)
![Image](https://github.com/user-attachments/assets/5e2004b7-9c91-4abf-bb2d-9819b9c1ceb4)

**Comment by MASHzj** [comment]
That's because it tried to build it above the track.

**Comment by RogoDarius** [comment]
The preview for building above track appears in other places, but specifically in these places under sections of coasters, it doesn't show.
(The supports for shops could go high enough to go over the track pieces.)

**Comment by MASHzj** [comment]
A preview is only shown if it's possible to build on that place.

**Comment by RogoDarius** [comment]
Ah you're right - I just checked it with holding shift 👍
