### ISSUE TITLE
No Entry Signs are ignored. 

### ISSUE THREAD

**Issue by thegreatpl** [OpenRCT2/OpenRCT2#2327]
Just watched guests walk merrily through a no entry sign. Tested with both no change to sign content and to the sign having had text changed. Nope, still refuse to acknowledge the signs existence. 

Build is the latest from the openRCT2.com site. Build 1462. Fresh install. Only got RCT2 installed, and from disk. 

Scenario is a custom made one, made with this build.

**Comment by osconnoisseur** [comment]
Confirmed.

**Comment by duncanspumpkin** [comment]
331d75e was only for signs not for banners. I'll try work out whats up tonight.

**Comment by duncanspumpkin** [comment]
Fixed on the prerelease. It was accidently corrupting the surface element instead of setting the no entry status.
