### ISSUE TITLE
Console reports wrong money when set to very negative number

### ISSUE THREAD

**Issue by Meerkov** [OpenRCT2/OpenRCT2#23286]
### Operating System

Windows 11

### OpenRCT2 build

v 0.4.16

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

Use the console command
`set money -92999990866648780.8`

However, the console reports
`money 1145528628.-80`

The actual money is not the value reported. This is probably a 64 bit vs 32 bit conversion issue.

### Steps to reproduce

See description

**Comment by James103** [comment]
I can reproduce the incorrect reported value in OpenRCT2, v0.4.16 (ac775ae984 on develop) provided by GitHub.
![Image](https://github.com/user-attachments/assets/77e2c87c-2844-47c0-8ac0-0d166228ef54)
