### ISSUE TITLE
Include SignPath as sponsors in the download page

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#23280]
As per https://signpath.org/terms and #23236 we should include note about SignPath being a sponsor in our download page, https://openrct2.io/

The note should read:

> Free code signing provided by [SignPath.io](https://about.signpath.io/), certificate by [SignPath Foundation](https://signpath.org/)

and include the links

**Comment by Gymnasiast** [comment]
This information was added, but only shown on builds that are actually signed with it. It will become visible with today’s release.
