### ISSUE TITLE
Entrance and exit still remained after demolishing attraction (in pause mode)

### ISSUE THREAD

**Issue by hytacker** [OpenRCT2/OpenRCT2#2329]
I demolished lift in pause mode. The entrance and exit still remained. I seleced the entrance and click the demolish button again and the game crashed. I tested if other attractions also had the same problem but it didn't happend to them.
![scr24](https://cloud.githubusercontent.com/assets/15657920/11222655/faf14822-8d6b-11e5-9819-ca1f4639bd03.png)

**Comment by IntelOrca** [comment]
I can't reproduce this.

**Comment by janisozaur** [comment]
Cannot reproduce in a675192
