### ISSUE TITLE
Stat windows in the prebuild selection is wrong (especially the airtime)

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#23310]
### Operating System

Windows 11, 64-Bits

### OpenRCT2 build

OpenRCT2, v0.4.16 (a87341888a on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Apparently, the stats between the prebuild menu and the stat result windows aren't telling the same stats, but especially the airtime

![Image](https://github.com/user-attachments/assets/ae0af085-d69d-4956-b578-077762520cce)

So, this is what is happening, the airtime of the prebuild selection windows says it have 63,66 seconds of airtime, yet the coaster produce less than one second in the stat windows of the ride view, and this is the worst differential of all the stats.

### Steps to reproduce

1. Build any Classic Twister Wooden Coaster (the one I realised the bug)
2. Make sure there's a bit of airtime
3. Save it
4. It will then show in the prebuild window with a massive amount of it when it didn't in the stat window when placed

**Comment by TheClaudeQC** [comment]
Apparantly, it is worst than I thought

Any rides build since maybe the introduction of the CTWRC, there's an airtime bug on the prebuild window

**Comment by SpartanFrederic104** [comment]
I already reported this issue in #23221.

**Comment by ZehMatt** [comment]
> I already reported this issue in [#23221](https://github.com/OpenRCT2/OpenRCT2/issues/23221).
