### ISSUE TITLE
Background colors

### ISSUE THREAD

**Issue by JarnoVgr** [OpenRCT2/OpenRCT2#2332]
"I'm new here, and I honestly have no idea if this is possible, or if this is the right place to post this, but I think it would be cool if you could change the background color, maybe just to like white or something? A small change like that can really have a big effect on the atmosphere of a project, and I just think it would be cool to include."

~~Original post by tropiuskin:  https://openrct2.com/community/topic/93/background-colors~~ (dead link)

**Comment by duncanspumpkin** [comment]
Yeah it could be done we looked at it before all of the code for drawing the blank background has been done `viewport_blank_tiles_paint_setup`. At present it will display image 3123. You could change this to a tile that has a pre chosen colour.

**Comment by PFCKrutonium** [comment]
If I may ask, how were those parks I have seen before with the image backdrop done?

**Comment by Nubbie** [comment]
#1260 related

**Comment by hubbyist** [comment]
Llink in the original post is broken and giving unsecure connection error.

**Comment by Gymnasiast** [comment]
@hubbyist Yeah, that link points a defunct forum (there used to be two and they merged).

**Comment by hubbyist** [comment]
Editing OP to reflect this may be helpful, because it has also a redirection loop of some sort. This may cause misunderstandings.

**Comment by hubbyist** [comment]
Or better correct redirection of com domain. Is it good to open an issue about it in this repo? OpenRCT2.WebUI repo is better?

**Comment by Gymnasiast** [comment]
Neither is appropriate. .COM does not exist any more, it is .ORG now, and it's run by @JarnoVgr and not by us.

**Comment by duncanspumpkin** [comment]
#9334 fixed this of sorts.
