### ISSUE TITLE
Tiled paths getting replaced by tarmac paths

### ISSUE THREAD

**Issue by lnoorman** [OpenRCT2/OpenRCT2#23346]
### Operating System

Android version 14 (One UI 6.1.1)

### OpenRCT2 build

OpenRCT2, v0.4.16

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

OS: [Android]
Version: [0.4.16]
While placing paths, the tiled paths aren't working. When selected, the menu will display the chosen tile. But whenever you try to place the tile, it will replace the tile with a tarmac coloured path automatically

The game is being played on a Samsung Tab S9+

![Image](https://github.com/user-attachments/assets/da555078-e473-457e-9139-568cb6c4b106)
![Image](https://github.com/user-attachments/assets/367005f3-1889-4dc5-9b60-89463cfcaf79)

### Steps to reproduce

1. open paths
2. select footpath 'tile (tiled, grey tile, green tile, red tile)
3. bug apears, tile gets replaced by tarmac paths of the same colour.

**Comment by Gymnasiast** [comment]
This is not a bug. You are playing a save that includes RCT1 paths, but you don’t have RCT1 linked, so OpenRCT2 has to fall back to something.

You can fix this by copying the files from RCT1 to your Android device to `/sdcard/rct1`. You may then need to modify the config.ini file, as I don’t think the Android version includes a file picker.

**Comment by lnoorman** [comment]
Oh wow, I'm sorry. I had no idea.

As it looks now, I've got everything on my internal memory. I don't have a rct1 folder, but I do have a rct2 folder. Containing rct deluxe. Anything I can change?

**Comment by Gymnasiast** [comment]
I don’t quite understand. Do you mean that you put the "RCT Deluxe" (which is RCT1 plus expansions) in the "rct2" folder, in addition to the files that were already there?

You should have two folders in the root of your internal storage:
"rct2", containing the files of RCT2 (e.g. the RCT2 Triple Thrill Pack),
"rct1", containing the files of RCT1 plus its expansions (e.g. RCT + Loopy Landscapes, or RCT Deluxe)

**Comment by lnoorman** [comment]
I tried to move the files into the rct1 folder and edited the configuration.ini, but the issue is still there. I can access all the rct1 scenario's though

![Image](https://github.com/user-attachments/assets/2039873d-059b-4cfd-9c67-2f38e46df074)

**Comment by lnoorman** [comment]
In my RCT1 folder are now the following folders:
- data
- scenarios
- tracks

I extracted these folders from the RCT 1 Deluxe version from GOG. Am I still missing something?

**Comment by Gymnasiast** [comment]
Does the `Data` folder contain the following two files:
- CSG1i.DAT
- CSG1.DAT or CSG1.1
?

And you could open Opties -> Last tab and check what it says under "Locatie RCT1-bestanden"? Does it show a path there?

**Comment by lnoorman** [comment]
The data folder does contain CSG1.DAT. the other two are not present. 
In the options, the location is storage/emulated/0/rct1/
I think its linked correctly, because I can play the scenarios from the original game

**Comment by Gymnasiast** [comment]
You’re missing csg1i.dat, which is required to load the graphics. Look for that file in your GOG build and copy it to the `Data` folder.

**Comment by lnoorman** [comment]
I think I've used my childhood cd to compile all the files. I'll buy the GOG version tomorrow. Thank you for the replies and all the help!

**Comment by Gymnasiast** [comment]
> I think I've used my childhood cd to compile all the files. I'll buy the GOG version tomorrow. Thank you for the replies and all the help!

It is present on the Loopy Landscapes or RCT Deluxe CD if you have that

**Comment by lnoorman** [comment]
Yes, I found it. It's working now. Thank you very much for your kind help!
