### ISSUE TITLE
Price for changing land terrain appears outside of land window

### ISSUE THREAD

**Issue by osconnoisseur** [OpenRCT2/OpenRCT2#2335]
The height of land window needs to be extended a bit to make the text fit inside.
![scr7](https://cloud.githubusercontent.com/assets/15527244/11231694/e05ef586-8d70-11e5-80c6-18f49c434a3b.png)

**Comment by Overv** [comment]
I can't reproduce this. The window looks like this for me in the latest build (b1a6836):

http://i.imgur.com/wWVyZ0a.png

**Comment by osconnoisseur** [comment]
In the original RCT2, there is a space below the two terrain buttons to fit the price of changing terrain.

**Comment by duncanspumpkin** [comment]
Fixed in the pre release.
