### ISSUE TITLE
Odd graphical behaviour when placing footpaths near a fence/wall

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#2337]
It looks like the wrong sprite is being chosen when placing a footpath near a fence with another path behind it. It also changes when 'replacing' a footpath.

![animated gif](http://i.imgur.com/zrkQLjX.gif)

In the original game it looks like this, and doesn't change when 'replacing' a tile:
![scr](http://i.imgur.com/tJ2n1nN.png)

Tested on b1a6836a2f0f3f7b5f71d33240bcd398519597ce, but I remember seeing this issue months ago too.

**Comment by IntelOrca** [comment]
I noticed this a few days ago - it looks like a bug in the path join code.

**Comment by duncanspumpkin** [comment]
Oh man was that an annoying bug. Issue was caused by the code that checks nearby tiles connecting. I was searching for a bit of code that was clearing the extra corners but actually due to the graphics its an invalid object and its actually got too many corners. Fixed in the pre-release.
