### ISSUE TITLE
Broadcast server to LAN

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#2339]
Source:
https://www.reddit.com/r/openrct2/comments/3ta95l/could_someone_tell_me_how_to_run_multiplayer/

A lot of old games used to broadcast the local address of the host on the local area network. Server lists would automatically listen to broadcast messages and show LAN servers.

~~I believe this can only be done for IPv4.~~
IPv4: Broadcast protocol
IPv6: Multicast protocol

**Comment by Smeat** [comment]
I don't really know much about networking, but I think for IPv6 you could use the FF02::1 multicast address.

https://www.iana.org/assignments/ipv6-multicast-addresses/ipv6-multicast-addresses.xhtml

**Comment by PFCKrutonium** [comment]
Minecraft Does this, and it rarely works as well as expected. We need to make sure OpenRCT2 punches temp holes in the firewall on all computers.

**Comment by samdroid-apps** [comment]
One way that I've seen things do it on linux is using Avahai (mDNS).  According to the avahai zeroconf viewer tool, there are both chat and chromecasts broadcasting their presence on the lan right now.

I've only ever use avahai way up the abstraction layer (via telepathy salut, where I just asked it for a list of other people on the network).  I also don't know if mDNS is supported on windows, but just some food for thought.

**Comment by janisozaur** [comment]
I's called "avahi", not "avahai" (just leaving a comment so it's easier to find this issue).

**Comment by janisozaur** [comment]
Should this be closed now?
