### ISSUE TITLE
Classic wooden twister roller coaster track designs from RCT1 do not import correctly

### ISSUE THREAD

**Issue by HtotheTML** [OpenRCT2/OpenRCT2#23402]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.17 (8d645c6316 on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

The new classic wooden twister roller coaster does not appear to properly load its associated track designs from RCT1.
![Image](https://github.com/user-attachments/assets/dc719c00-5d8e-4ddf-b77c-36596d9b37d3)

Instead they still appear under the RCT2 wooden coaster, but are now unbuildable.
![Image](https://github.com/user-attachments/assets/794e66f0-0e6a-469b-8f0f-a78dd36d12dd)
![Image](https://github.com/user-attachments/assets/e67f3dbb-f116-4c37-b7b2-77804fe1d61e)

### Steps to reproduce

1. Open ORCT2 with RCT1 linked to it
2. Open track designer
3. Add Classic Wooden Twister Roller Coaster & RCT2's Wooden Roller Coaster
4. look for "u(0105)," "u(0166)," "u(0237)," "Wood Twister 1," or "Wood Twister 2" on both rides' designs list
5. Attempt to build any of those ride designs

**Comment by HtotheTML** [comment]
I removed the tracks.idx file. That fixed the issue.

**Comment by MASHzj** [comment]
> I removed the tracks.idx file. That fixed the issue.

Do we all have to do that to get the correct behaviour?
