### ISSUE TITLE
linux mint with gog installer: Could not find /Data/g1.dat at this path.

### ISSUE THREAD

**Issue by RobertHeim** [OpenRCT2/OpenRCT2#23417]
### Operating System

LinuxMint 21.2 Cinnemon
Cinnamon 5.8.4
Kernel: 5.15.0-126-generic x86_64 bits

### OpenRCT2 build

v0.4.13

### Base game

RollerCoaster Tycoon 2

### Describe the issue

Cannot install because "Could not find /Data/g1.dat at this path." when using gog.com  files on linux mint.

### Steps to reproduce

Here is what I did:

#### 1. Installed OpenRCT2
```
sudo add-apt-repository ppa:openrct2/master
sudo apt update
sudo apt install openrct2
sudo apt install innoextract
```

```
openrct2 --version
OpenRCT2, v0.4.13 (, DEBUG)
Linux (x86-64)
Network version: 0.4.13-0
Plugin API version: 97
Current park file version: 34
Minimum park file version: 33
Breakpad support disabled
```
#### 2. Downloded GOG RCT2 offline installer
I just bought https://www.gog.com/de/game/rollercoaster_tycoon_2 and downloaded the two offline installer files to the same folder:
```
setup_rollercoaster_tycoon_2_triple_thrill_pack_2.01.043_wacky_worlds_patch_(76932).exe
setup_rollercoaster_tycoon_2_triple_thrill_pack_2.01.043_wacky_worlds_patch_(76932)-1.bin
```

#### 3. try to run/install
* Run `openrct2`
* Select "I have the GOG installer [...]"
* select the exe file from step 2
* Confirm "This may take a few minutes

#### Error: Could not find /Data/g1.dat at this path.
It shows a dialog:

> Could not find /Data/g1.dat at this path.

What can I do?

**Comment by janisozaur** [comment]
As a manual workaround, you can extract the files manually: `innoextract setup_rollercoaster_tycoon_2_triple_thrill_pack_2.01.043_wacky_worlds_patch_(76932).exe`, then select the `app` directory for where the data is. Obviously, you can move it before selecting.

**Comment by RobertHeim** [comment]
I extracted the data manually, but I keep getting the same dialog and error message when selecting `I have a RollerCoaster Tycoon 2 or ... installed already` and then the `app` folder.

What worked is selecting the root folder where I extracted the files.
