### ISSUE TITLE
error loading objects in park

### ISSUE THREAD

**Issue by beaniemachine09** [OpenRCT2/OpenRCT2#23416]
### Operating System

windows 10 64 bit

### OpenRCT2 build

OpenRCT2, v0.4.17 (60dc190e1b) provided by GitHub

### Base game

RollerCoaster Tycoon Classic, RollerCoaster Tycoon 2

### Area(s) with this issue?

This issue has to do with park objects and/or asset packs

### Describe the issue

![Image](https://github.com/user-attachments/assets/d11b13ec-e647-4b0e-b249-07bcb9fb137c)

When attempting to open most scenarios in rct classic corkscrew follies and loopy landscapes this error appears. Some scenarios such as iceberg islands and whispering cliffs do not have this error but all other scenarios do not work. this does not happen in my RCT classic base game.

### Steps to reproduce

1. open openrct2
2. start new game
3. click corkscrew follies
4. click three monkeys park
5. error message appears

### Attachments

![Image](https://github.com/user-attachments/assets/4a85b2bd-4c39-478c-b9c9-088cf6cc07e6)

**Comment by MASHzj** [comment]
This seems to be caused by the recent addition of the RCT1 wooden Twister coaster

**Comment by Gymnasiast** [comment]
It looks like you updated the executable, but didn’t update the objects. Please reinstall OpenRCT2.
