### ISSUE TITLE
Guests and staff can dissapear or freeze while walking.

### ISSUE THREAD

**Issue by TheClaudeQC** [OpenRCT2/OpenRCT2#23426]
### Operating System

Windows 11

### OpenRCT2 build

OpenRCT2, v0.4.17 (92dac978dc on develop) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is specific to multiplayer, This bug is a graphical glitch or error

### Describe the issue

Some guests/staff will glitch by freezing or vanishing from the screen (playing original frame limit on Software redering)

### Steps to reproduce

1. Make the game to run on 40 fps (no unforced fps speed) with the Sofeware rendering on
2. Play on a multiplayer server (like the FFA Tycoon ones)
3. check in an area with guests
4. see the bug happening

### Attachments

![Image](https://github.com/user-attachments/assets/cbd21530-25cc-4a2f-a39b-5ab93cc5e557)

**Comment by ZehMatt** [comment]
The cause is the same as #23376 and just got fixed.
