### ISSUE TITLE
Guests walk away when reaching the end of the queue line

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#2345]
The two rides _Twist-Er_ (Twister) and _Sky Voyage_ (Observation Tower) are broken in the attached park after someone build for his turn. Guests enter the queue line and their status is saying so as well, but once they reach the entrance instead of entering they turn around and walk away. In the saved game before this happened the observation tower was working just fine, and the Twister wasn't there yet. The builder didn't notice it himself, and doesn't seem to know what may have caused it. It looks like many things have been build with clearance checks disabled, I suspect this might have something to do with it.

**V2.11** (bugged): https://openrct.net/cc/share/88/Community+Park+V2.11.SV6
**V2.10**: https://openrct.net/cc/share/89/Community+Park+V2.10.SV6

I'll try to find a way to reproduce this, I hope the saved game file will give a clue to someone.

**Comment by Gymnasiast** [comment]
Try double closing both rides.

**Comment by Broxzier** [comment]
I did that and it doesn't solve the issue. Placing the entrances again does though. I also found out that when placing them while the game is paused the game will crash when the first guest in line reaches the entrance.

**Comment by IntelOrca** [comment]
I think this is a duplicate of #1731.

**Comment by Broxzier** [comment]
Closing, as this hasn't happened anymore for a long time.
