### ISSUE TITLE
Allow enable / disabling of news message notification types

### ISSUE THREAD

**Issue by joflashstudios** [OpenRCT2/OpenRCT2#2346]
I looked through the issue history and couldn't find one on this:

I can't remember the last time I saw a notification that a ride had broken down and thought to myself, "wow! That's useful information! I will do something about that!" No - a ride breaking down is not noteworthy.

Furthermore, in anything other than a small park, the notification queue just gets spammed with these. A new ride was unlocked? I want to know about that. A ride "still hasn't been fixed?" I want to know about that. Guests are complaining about the disgusting state of the paths in my park? I want to know about that. Etc.

The problem is that when the notifications are so rarely notworthy, I don't even notice the messages I care about, because I'm getting so many breakdown notifications. (In my current park one every 10 seconds or so.) If I open the notification history, I have only one non-breakdown notification, because they happen so much more often than anything else.

Breakdown notifications aren't useful information. Is it possible to add a way to turn them off?

**Comment by Gymnasiast** [comment]
If this gets implemented, it would be best to add settings for every type of message, in a similar way OpenTTD handles it.

**Comment by janisozaur** [comment]
That should be fairly easy to implement. Should we have "Low-hanging fruit" label so newcomers can have some tickets to tinker with for starters?

**Comment by IntelOrca** [comment]
I will change this to notification management. I have seen other requests to disable various peep tracking notifications too. Perhaps we could add the "guest ### is lost and can't find the park entrance" notification back for the full RCT1 experience!

**Comment by PFCKrutonium** [comment]
That would actually be a very useful notification, because if it is happening a lot, you know you have an issue.

**Comment by Gymnasiast** [comment]
If that's happening a lot, you get the message "Guests are getting lost or stuck". That was not taken out in RCT2. (Getting the message for every single guest is bloody irritating, I'm actually glad that was taken out of RCT2, reintroducing it would be bonkers as far as I'm concerned.)

**Comment by PFCKrutonium** [comment]
...Good Point.
