### ISSUE TITLE
Guest sprites on water coaster boat and other vehicles don't render properly.

### ISSUE THREAD

**Issue by ZeeMaji** [OpenRCT2/OpenRCT2#23471]
### Operating System

Linux (Fedora 40)

### OpenRCT2 build

Actions Build AppImage (https://github.com/OpenRCT2/OpenRCT2/actions/runs/12473776407)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

The guest sprites on the water coaster boats don't seem to render properly anymore, they're cut off and flicker in and out of existence.

### Steps to reproduce

1. Look at any water coaster boat with guests
2. Observe the sprite glitching

### Attachments

![Image](https://github.com/user-attachments/assets/a1f41f4c-0002-40f6-8492-be1fbc8fbbb2)
![Image](https://github.com/user-attachments/assets/3cf730b9-76e7-4625-a7f9-c83183c5600e)

**Comment by ZeeMaji** [comment]
Upon looking further, it affects other vehicles too like the six seater bobsleds and splash boats.
![Image](https://github.com/user-attachments/assets/cb8d66b7-45ee-4754-9514-e2470cf60d08)
![Image](https://github.com/user-attachments/assets/3b590023-4154-4b79-9178-f4ce32ea2f7d)

**Comment by ZeeMaji** [comment]
This seems to be affecting nearly every vehicle with more than one set of guest sprites, the first set renders correctly but all of the ones after it glitch badly.

**Comment by ZehMatt** [comment]
Could this be again related to procedurally computing their bounding box for invalidation @AaronVanGeffen ?

**Comment by AaronVanGeffen** [comment]
These would be vehicle sprites, not peep animation sprites, so it can't be due to the recent changes. That said, the peep animation algorithm is based on the inference code used for vehicle objects. Large sprites might not fit in the 100x100 quadrants allotted for them:

https://github.com/OpenRCT2/OpenRCT2/blob/51bf885cdacc3a092f4b372889b987c97a33cae9/src/openrct2/ride/CarEntry.cpp#L47-L64
