### ISSUE TITLE
Water sparkles not animating properly anymore + they glow in rain

### ISSUE THREAD

**Issue by ZeeMaji** [OpenRCT2/OpenRCT2#23470]
### Operating System

Linux (Fedora 40)

### OpenRCT2 build

Actions Build AppImage (https://github.com/OpenRCT2/OpenRCT2/actions/runs/12435608126)

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

The water sparkles don't seem to properly animate anymore, they appear to be frozen and they also glow in the rain.

### Steps to reproduce

1. Open any park with water or water tracked rides.
2. Look at the water, the sparkles are frozen.

### Attachments

Release 0.4.17
![Image](https://github.com/user-attachments/assets/c455681a-da0c-4830-8564-969e748d7f6e)

Develop from Actions Build 12435608126
![Image](https://github.com/user-attachments/assets/5e60ebe2-5e40-436c-a9e4-ad888896ba88)

**Comment by Gymnasiast** [comment]
This should have been fixed earlier today, could you check with an up-to-date build?

**Comment by ZeeMaji** [comment]
Ah you are correct, i guess both the builds i was testing were just slightly outdated enough to not have the fix from earlier today. Closing.
