### ISSUE TITLE
Ride vehicles are not visible on the same tick that a ride is opened or tested

### ISSUE THREAD

**Issue by stai1** [OpenRCT2/OpenRCT2#23496]
### Operating System

Windows 10, 64-bit

### OpenRCT2 build

OpenRCT2, v0.4.16 (c1082a3d6c on master) provided by GitHub

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This bug is a graphical glitch or error

### Describe the issue

On the tick that a ride is first opened or tested, the vehicles are created but invisible. Only on the next tick are the vehicles visible. This exists in v0.4.16 and v0.4.17. In vanilla and pre-v0.4.16, vehicles are visible on the same tick when the ride is opened or tested.

I suspect that this is related to another bug that occurs only in the same versions: https://github.com/OpenRCT2/OpenRCT2/issues/23289#issuecomment-2564816651

### Steps to reproduce

1. Build a tracked ride.
2. Pause the game.
3. Open or test the ride.
4. Observe that the ride's vehicles have not appeared, but that they exist in the view dropdown (as below)
  ![Image](https://github.com/user-attachments/assets/6f4dbc62-c535-4594-83dc-76f2846d435b)
5. Advance 1 tick.
6. Observe that the ride vehicles are now visible.

This also occurs for dodgems (bumper cars) and flying saucers.
![Image](https://github.com/user-attachments/assets/11d4fb23-7202-4fda-95f6-9255ad42e07b)

**Comment by ZehMatt** [comment]
This is due to UI and game logic being separate now. I'm not sure I would call this a bug as I don't see any negative effects that for would matter in ordinary game play.
