### ISSUE TITLE
New precipitation: Snow

### ISSUE THREAD

**Issue by Wolfscopez** [OpenRCT2/OpenRCT2#2350]
This is supposed to be a feature which could be added when the game is decoded 100% and things are being added but what about adding snow as weather?

Snow would be used on maps which are arctic themed, it would appear at a similar rate to rain but in arctic maps, it would also potentially prompt guests to buy scarves or sweaters from stalls allowing more opportunities of profit, though that would require sprite-work and adding a new temperature meter on guests.

It's just a suggestion though so shoot it down if it's too difficult to implement in the future.

**Comment by gavin1337** [comment]
couldn't scarves/sweaters be treated as umbrellas, and bought mostly when it's raining (or in this case, snowing)
that would be a lot simpler than any internal temperature meter. Just have it sell like any other accessory (shirt, etc.) and then have the code treat it similar to umbrellas during the weather, couldn't be that difficult.

**Comment by HaasJona** [comment]
Also the game already makes shop items more valuable depending on climate. On a cold map you can take more money for hot chocolate than in a desert.

**Comment by IntelOrca** [comment]
Interestingly enough there is already a climate sprite that shows in the bottom right for snow / frost. So that would fit nicely with this.

**Comment by Nubbie** [comment]
It's now being worked on in: #3576

**Comment by jessicajonesunitedkingdom** [comment]
Is anybody interested in implementing this?

My idea was explained here, including screenshots from other developer:

https://github.com/OpenRCT2/OpenRCT2/issues/10717

**Comment by brettpenzer123** [comment]
Yes.

Umbrellas?
![ezgif com-optimize (1)](https://user-images.githubusercontent.com/10356800/74798300-50737400-52c5-11ea-9451-7848fb99b43d.gif)

Or not?
![ezgif com-optimize (2)](https://user-images.githubusercontent.com/10356800/74798397-96c8d300-52c5-11ea-8d73-74cc8728e3e5.gif)

**Comment by thenamelessone1** [comment]
I think umbrellas are nice for this weather.

If I remember correctly, the first snow implementation had a different angle in which the snowflakes fall down or am i wrong?

**Comment by thenamelessone1** [comment]
I personally like the angle of the snowflakes of the old screenshot better then this new one (but that's just personal taste)

What do you think Brett?

**Comment by thenamelessone1** [comment]
I found somewhere this:

https://imgur.com/BX7wqwu

It seems to be a mod, but I don't know where to download it.
I like the idea of snow covered tiles. When snowing stops, the tiles slowly return to grass.

Are you planning to make this too?

**Comment by brettpenzer123** [comment]
So just a quick update. Here is how the snow looks now.

Snow - 2 Drops
![ezgif com-video-to-gif (5)](https://user-images.githubusercontent.com/10356800/74902538-47a2a100-539e-11ea-88df-9ed43944000e.gif)

Heavy Snow - 4 Drops
![ezgif com-video-to-gif (6)](https://user-images.githubusercontent.com/10356800/74902554-51c49f80-539e-11ea-9a6d-280cbe782c01.gif)

Blizzard - 4 Drops / White Overlay
![ezgif com-video-to-gif (8)](https://user-images.githubusercontent.com/10356800/74902564-55f0bd00-539e-11ea-8dcb-c3f92c1298eb.gif)

I know blizzard at this point has a white overlay to all the menus, I'm just testing to see if it's worth adding in. I believe it may obstruct the gameplay itself having a permanent transparent white over the top unless I turn down the level of brightness.

What are thoughts?

**Comment by brettpenzer123** [comment]
The gif for blizzard doesn't look good since I've had to optimize them under 10MB. Here is a link for the video https://drive.google.com/open?id=1Ton4rbrZGtSVJ8lXQBJtMdOgJzVrM_K-

**Comment by Krutonium** [comment]
For the Heavy Snow you should remove the lightning effect - Not that a blizzard doesn't have it, but it's extremely rare to see it because snow be like that. 

As for the white overlay, if you solve that it would also solve the day/night cycle issues regarding the menus as well, which might encourage more work on making that look better (working lights as such).

**Comment by ocalhoun6** [comment]
It still seems kind of odd to have umbrellas out during the snow. I know it makes sense that if you were already carrying an umbrella and it happened to start snowing, you'd probably use it ... but in real life, people using umbrellas in the snow doesn't seem to happen often. Of course, there are [exceptions]([url](https://www.jamestownsun.com/incoming/article2604119.ece/alternates/BASE_LANDSCAPE/3077343%2B2017-01-08T020539Z_2_LYNXMPED0700V_RTROPTP_3_USA-WEATHER.JPG)), but [for the most part](https://videos.usatoday.net/Brightcove2/29906170001/2016/01/29906170001_4711620576001_thumb-Wochit101253156.jpg?pubId=29906170001), you don't see people using umbrellas in the snow.

**Comment by brettpenzer123** [comment]
> For the Heavy Snow you should remove the lightning effect - Not that a blizzard doesn't have it, but it's extremely rare to see it because snow be like that.
> 
> As for the white overlay, if you solve that it would also solve the day/night cycle issues regarding the menus as well, which might encourage more work on making that look better (working lights as such).

The heavy snow doesn't have a lightning effect it is using a darkening effect bit like how heavy rain is but it seems the gif is that fast it looks like it's flashing. Please see video for more evidence on that - https://drive.google.com/open?id=1UjT7bDXEgECqLtZyuYREHiRWvmqWD2kF

Yeah, didn't know there was any day/night issues but I'll look into that another time.

**Comment by brettpenzer123** [comment]
> It still seems kind of odd to have umbrellas out during the snow. I know it makes sense that if you were already carrying an umbrella and it happened to start snowing, you'd probably use it ... but in real life, people using umbrellas in the snow doesn't seem to happen often. Of course, there are [exceptions](https://www.jamestownsun.com/incoming/article2604119.ece/alternates/BASE_LANDSCAPE/3077343%2B2017-01-08T020539Z_2_LYNXMPED0700V_RTROPTP_3_USA-WEATHER.JPG), but [for the most part](https://videos.usatoday.net/Brightcove2/29906170001/2016/01/29906170001_4711620576001_thumb-Wochit101253156.jpg?pubId=29906170001), you don't see people using umbrellas in the snow.

Yeah, there isn't any real alternative in the game for the peep to use. Normally people would put on coats but sadly the game only features t-shirts as peep clothing maybe I could do something with that? that still looks like a long shot though so I either cut it or keep it.

**Comment by Richard-L** [comment]
To your attention, the snow realisation here https://www.nedesigns.com/park/4598/the-blizzard/

**Comment by ZehMatt** [comment]
I don't like the movement pattern honestly. Snow has way more air friction due to the shape and even a tiny bit of wind will affect it, this still looks more like rain than snow.

Example:
![DyvbNEF](https://user-images.githubusercontent.com/5415177/74953621-2a072300-5402-11ea-97b3-ea0e3ebdc104.gif)

**Comment by thenamelessone1** [comment]
I like the snow and heavy snow a lot. To me it really looks like snow. The speed and angle of the snowflakes makes it not feel like rain for me.
The heavy snow pattern I like too.

blizzard: I think much people won't like the overlay over GUI windows. 
Is there a way to only make an overlay on the actual park map area but not the whole screen?

Thx for your work. I like it a lot!

**Comment by thenamelessone1** [comment]
My ideas are:

1) the umbrellas could be used in heavy snow or blizzard (not needed in the lightest form of snow weather). Maybe new things could be added in the shops specific for snow like winter hats, ...
People will buy the hats when it's snowing.

2) you could add a sort of wind sound in heavy snow or blizzard and/or an adjustment to the sounds of the park that get muffled (like the music of the rides).

3) I think heavy snow or blizzard can exist as weather type. If thunderstorm can exist, then those 2 can certainly exist too. Somebody on the chat said a park is closed during heavy snow or blizzard but that makes no sense if weather type thunderstorm exists too. A park would be closes during thunderstorm too...

**Comment by brettpenzer123** [comment]
> To your attention, the snow realisation here https://www.nedesigns.com/park/4598/the-blizzard/

That looks amazing but the snow effect is static in that scene. In RCT2 the weather is drawn on top of the game so if you move the camera the weather doesn't adjust to the game world. Therefore I believe this is why the majority of the weather in RCT2 has a slightly tweaked X position.

I feel if the snow was that much over the top of the nature gameplay, it would obstruct the player's viewpoint.

**Comment by brettpenzer123** [comment]
> I don't like the movement pattern honestly. Snow has way more air friction due to the shape and even a tiny bit of wind will affect it, this still looks more like rain than snow.
> 
> Example:
> ![DyvbNEF](https://user-images.githubusercontent.com/5415177/74953621-2a072300-5402-11ea-97b3-ea0e3ebdc104.gif)

I did think about adjusting the snow as it was coming down which would give a sway effect although when two pixels overlap each other in the weather it becomes permanent to the screen. 

The only way I could fix this is the keep refreshing the entire screen and deleting all the pixels since the weather draws a pixel, recolours a pixel back to original pixel colour and so on.

**Comment by thenamelessone1** [comment]
I think Brett's snow fits PERFECTLY into the game.
The screenshot above is too much. It will make the game hard to play because snow is covering everything below it

**Comment by ZehMatt** [comment]
> > I don't like the movement pattern honestly. Snow has way more air friction due to the shape and even a tiny bit of wind will affect it, this still looks more like rain than snow.
> > Example:
> > ![DyvbNEF](https://user-images.githubusercontent.com/5415177/74953621-2a072300-5402-11ea-97b3-ea0e3ebdc104.gif)
> 
> I did think about adjusting the snow as it was coming down which would give a sway effect although when two pixels overlap each other in the weather it becomes permanent to the screen.
> 
> The only way I could fix this is the keep refreshing the entire screen and deleting all the pixels since the weather draws a pixel, recolours a pixel back to original pixel colour and so on.

You won't have this problem with the OpenGL renderer as it redraws every frame. I'm not exactly sure about the software issue, it would be better to have a open draft PR so I we can go over the code and test any changes instead of discussing this over the issue here.

**Comment by brettpenzer123** [comment]
> > > I don't like the movement pattern honestly. Snow has way more air friction due to the shape and even a tiny bit of wind will affect it, this still looks more like rain than snow.
> > > Example:
> > > ![DyvbNEF](https://user-images.githubusercontent.com/5415177/74953621-2a072300-5402-11ea-97b3-ea0e3ebdc104.gif)
> > 
> > 
> > I did think about adjusting the snow as it was coming down which would give a sway effect although when two pixels overlap each other in the weather it becomes permanent to the screen.
> > The only way I could fix this is the keep refreshing the entire screen and deleting all the pixels since the weather draws a pixel, recolours a pixel back to original pixel colour and so on.
> 
> You won't have this problem with the OpenGL renderer as it redraws every frame. I'm not exactly sure about the software issue, it would be better to have a open draft PR so we can go over the code and test any changes instead of discussing this over the issue here.

Yeah. I guess but that's experimental so it doesn't fix the issue of getting it to draw properly on all drawing engines..

**Comment by ZehMatt** [comment]
The rain renderer already stores every overwritten pixel, I'm not sure I see what the issue is?

**Comment by thenamelessone1** [comment]
put the snow up your ass

**Comment by brettpenzer123** [comment]
> put the snow up your ass

I take that as a homophobic comment. Please remove your comment and keep your opinions to yourself.

**Comment by AaronVanGeffen** [comment]
I'm sorry this happened. The user in question has since been banned from our GitHub. Tonight's spam was the final straw that broke the camel's back.

**Comment by pizza2004** [comment]
As far as umbrellas go I would just make it a small chance that anyone carrying an umbrella will pull theirs out, so only certain peeps will use umbrellas.  It gives them some character.

**Comment by Krutonium** [comment]
"It's too cold to go on... ... I want a hot chocolate!"
