### ISSUE TITLE
[Feature Request] Color Wheel

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#2354]
Color wheel for selecting colors. No idea if this is feasible, but it would be amazing.

**Comment by Patrik356b** [comment]
If it has brightness adjust, sure. Otherwise the standard rgb box would be okay

**Comment by PFCKrutonium** [comment]
I am thinking this https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/RGB_color_wheel_10.svg/2000px-RGB_color_wheel_10.svg.png

with it getting brighter towards the center.

I only worry this will break RCT2 Save Compatability

**Comment by Patrik356b** [comment]
It's going to break anyway afaik due to other custom features

**Comment by Gymnasiast** [comment]
How would that be an improvement? We have a delightfully simple dropdown at the moment. Why should we complicate things?

**Comment by PFCKrutonium** [comment]
Because instead of having ~20 colors, we could have 16,777,216 colors.

**Comment by IntelOrca** [comment]
@PFCKrutonium you are forgetting that we are tied to a 256 colour palette making this impossible. And yes this obviously would break save compatibility.

**Comment by PFCKrutonium** [comment]
True... Perhaps once we get all 32 bit color in the far future...
