### ISSUE TITLE
Hotkeys for clearing the input boxes

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#2355]
For example, I can use Ctrl+U to clear the input boxes in openttd.
I think some kind of similar hotkey is needed in openrct2 as well.

**Comment by osconnoisseur** [comment]
The original game uses native Windows dialog boxes and have the text initially highlighted, so you can simply hit backspace to clear the input box. It would be nice if our input boxes had that functionality.

**Comment by IntelOrca** [comment]
Usually CTRL+Backspace is suffice, but we need to implement that.
