### ISSUE TITLE
"Window scale factor" slider usability

### ISSUE THREAD

**Issue by zornor** [OpenRCT2/OpenRCT2#2356]
The ability to adjust the DPI of the window is fantastic. I adjust it, usually between 1.00 and 2.00, on a fairly regular basis. But as it is, it's a pain in the ass to adjust when the window moves away from the cursor whenever you click on it. Of course this is inevitable for the way the options window is set up. I have some ideas on how it could be solved.

1. Add a simple console command (set dpiscale x). This might already be in the game but I'm too much of an end-user to know that ;)
2. When adjusting the DPI via the slider, the window moves accordingly, placing itself under the cursor such that the cursor can immediately click again to continue adjust the scale appropriately. This could add the issue of (draggable parts of) the window getting nudged offscreen.
3. Like in Windows, when the slider is focused, pressing arrow keys adjusts the value.
4. Bindable hotkeys for adjusting it.
5. Just add an apply button!

**Comment by Patrik356b** [comment]
Another option is to only update when left mouse button is released. That would be a simple solution.

**Comment by janisozaur** [comment]
Wow, I didn't quite expect it to be so popular.

I think #4 would be easiest and quite effective solution

**Comment by duncanspumpkin** [comment]
The first idea is by far the easiest. Bindable hotkeys is far to excessive for an option that will be set once and then not pressed again. 2 isn't ridiculously hard to implement either. 3 would be hard to implement. 5 could work but we don't do it for anything else so I don't see why we should now.

**Comment by janisozaur** [comment]
How about adding `shift` modifier when clicking zoom buttons in the top toolbar?

**Comment by Gymnasiast** [comment]
We could implement both. I would be in favour of that actually.

**Comment by janisozaur** [comment]
I chose 0.25 step somewhat arbitrarily, mostly to let users know that the scale doesn't have to be an integer.

How about we change this step to be just 1.0 and if you want something else, you can edit `config.ini`?
Or have one spinner for integer and other spinner for fractional part?

![dpiscale](https://cloud.githubusercontent.com/assets/550290/11562845/c0024e98-99d0-11e5-89ac-ec26fc9ac204.png)

**Comment by Patrik356b** [comment]
I like the option with dual spinners

**Comment by Gymnasiast** [comment]
Dual spinners is not user-friendly. And .25 intervals are granular enough.
People who are very fussy about the factor are more likely to be advanced user anyway, and they can still edit the config.ini.

**Comment by zornor** [comment]
Thanks guys, console command works great :D

For those who stumble upon this thread and would like to try it, type:
set window_scale x
