### ISSUE TITLE
When testing an unfinished ride, pressing stop should remove the cars or move them to the station

### ISSUE THREAD

**Issue by Krutonium** [OpenRCT2/OpenRCT2#2357]
See title.

**Comment by Patrik356b** [comment]
Yes

**Comment by Gymnasiast** [comment]
I find myself frequently releasing one train, then putting the ride in stop mode. That would if this were to be changed.

**Comment by duncanspumpkin** [comment]
shouldn't be hard to change the set ride mode code to reset the ride if going from testing to closed with testing unfinshed on.

**Comment by jensj12** [comment]
Pressing stop twice already does this (which is very easy with RCT1 style traffic lights). Doing this with one click removes the option to release only one train (which is sometimes needed to evenly divide trains over multiple stations).

I can see it being helpful though if you have RCT2 style flags, no crashes during testing cheat disabled and a ride mode that doesn't require a complete track (or testing of unfinished rides enabled).

**Comment by Gymnasiast** [comment]
Well, exactly. Double close isn't that hard anyway, not even with RCT2 flags. (Which aren't very handy anyway, so if flags are the concern switching to traffic lights is a way better solution IMO.)

**Comment by IntelOrca** [comment]
I think we will make a 4th mode anyway like RCT3, so it will be:
* Stop (no trains, allow construction)
* Simulate (ghost trains, allow construction)
* Test (real trains, no construction)
* Open (real trains, no construction)

**Comment by Patrik356b** [comment]
I'd assume the simulation button would be blue. 
Reason is that it is unused and is a common color for "service" in real places, i.e. Factories

**Comment by IntelOrca** [comment]
![image](https://cloud.githubusercontent.com/assets/1482259/11320833/22ba2aaa-909f-11e5-97c6-da4ecc11349e.png)

**Comment by jensj12** [comment]
I'd go for the RCT3 solution. Changing the ride mode to testing while having the construction window open will make it go into simulation mode (which made sense to me in RCT3). Backdraw is that it won't work easily when building two or more coasters at the same time.
Having four flags is a good solution indeed, but I can't yet get my head around traffic lights with four lights.

**Comment by Gymnasiast** [comment]
How about red+amber to mark simulation then? (Click once to simulate, click twice to test?)

**Comment by osconnoisseur** [comment]
I agree with @jensj12. I think it's a good idea that if we implement features that are in RCT3 (like ghost testing rides), we make them behave like they do in RCT3 and keep it consistent.

**Comment by IntelOrca** [comment]
@osconnoisseur I don't see any reason to be consistent with RCT3.

**Comment by Patrik356b** [comment]
@intelocra yeah,  good picture

**Comment by e-foley** [comment]
Even the idea that you have to "close" an already closed ride to replace the trains always struck me as counterintuitive.  Perhaps we should consider improving that functionality as we address a better simulation tool—there may be an elegant solution that covers both.

**Comment by duncanspumpkin** [comment]
Closing as we now have the ghost train for this sort of testing.
