### ISSUE TITLE
Option to change "sync" piece for adjacent tracks

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#2358]
See title.

**Comment by Gymnasiast** [comment]
The plans are to allow the users to synchronise rides using some sort of GUI. Your proposed implementation is more difficult in both technical and usability terms.

**Comment by Patrik356b** [comment]
I didn't see any plans for such an option before. The way I was thinking of
doing it would be to set a flag (or some type of marker) on the sync
tile/piece and match adjacent tracks, maybe directly in the construction
window

**Comment by Patrik356b** [comment]
Any implementation to enable changing this would be fine by me
