### ISSUE TITLE
Placing staff down causes desync

### ISSUE THREAD

**Issue by EmblemCronius** [OpenRCT2/OpenRCT2#2359]
Bug found in: openrct2.com OpenRCT2 0.0.3 build 1475

Hiring staff itself does not cause an issue at all, it gets de-synced when one of us places the unit down.

We found that placing a unit down works normally on client that places it, but the change isn't posted to the other's client. Perhaps this is not implemented yet?

**Comment by janisozaur** [comment]
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/1943

**Comment by EmblemCronius** [comment]
My bad, didn't see that one.
