### ISSUE TITLE
Actual tunnels

### ISSUE THREAD

**Issue by Wimali** [OpenRCT2/OpenRCT2#2365]
It would be nice to have actual tunnels in the game, as was originally intended by Sawyer. I'm thinking of just a graphical change; tunnels the way they exist continue to  act the exact same way-- They just look more like a tunnel. Something like this: http://i.imgur.com/dxxE3mT.gif

**Comment by Christipher** [comment]
I'll write this for all of #2365 through #2368 - these are all epic type changes that change the entire dynamic of the game drastically - anything else more specific would occur in those threads... other ideas also exist within this realm, however, I know (from other threads) this will have to wait until all code is decompiled and translated before those issues can be looked into.

**Comment by Gymnasiast** [comment]
You duplicated your _own_ issues... have you forgotten you mentioned all of those in #663?

**Comment by IntelOrca** [comment]
Seems like this is possible just through scenery around the track. With the help of disable clearance checks perhaps.

**Comment by HaasJona** [comment]
We already have actual tunnels. The "tunnels" in the screenshot just look like pipes. In theory I guess these could be added to the game similar to how you can create open and closed sections for waterslides. But this would obviously be a huge amount of work for questionable value.

**Comment by osconnoisseur** [comment]
I like the scenery idea. Just do some custom scenery and make a tunnel piece that fits around the track.
