### ISSUE TITLE
Rusty Track

### ISSUE THREAD

**Issue by Wimali** [OpenRCT2/OpenRCT2#2366]
As rides deteriorate over time, the nice bright paint finish will peel off the steel track to reveal rusty and bare metal, and require re-painting. As originally intended (but later abandoned) by Chris Sawyer.

Example picture from the game's concept art here: http://i.imgur.com/aMcWHjC.gif

**Comment by Gymnasiast** [comment]
I find this irritating.

Also a duplicate of #663.

**Comment by Patrik356b** [comment]
This might be a mod later. I don't like it as a default thing

**Comment by Joshwoo69** [comment]
Yeah same as patrik.
