### ISSUE TITLE
Circular Entrance Buildings (and other shapes)

### ISSUE THREAD

**Issue by Wimali** [OpenRCT2/OpenRCT2#2367]
Back when Chris Sawyer was working on the original game, he wanted to create circular entrance buildings, including a circular name banner which scrolls around the top. At the time, there were too many problems with entrances of this shape, so they never made it into the final game. I think this would be (more) possible now to implement. Example pic from what Chris Sawyer intended: http://i.imgur.com/DlCgzRv.gif

Maybe some other sizes too-- Pyramid-like, cilinder,... or just any other shape, really.

**Comment by Wimali** [comment]
Another example of what's possible-- 

15 December 1997 
More experiments in ride entrance/exit design. In part 2, we saw some alternative designs for ride entrance/exits in the shape of round castle-like turrets, but the shape proved too much of a problem. These later tests were based on the existing square entrance/exit buildings, but with various changes. However, they were never finished.

http://i.imgur.com/RtatIkP.gif

**Comment by Gymnasiast** [comment]
Duplicate of #663.
Creating more entrances will probably be possible eventually, the shapes and designs are up to the users.
