### ISSUE TITLE
Giga coaster won't log data

### ISSUE THREAD

**Issue by hypocube** [OpenRCT2/OpenRCT2#2369]
I built a giga coaster that won't begin logging data. After testing it will show test results but it will not produce graphs on the data logging. 

Ride download link - http://www.mediafire.com/download/v8hqxaiugpjskjx/Spiraling_Phoenix.TD6

Has results
![](https://i.gyazo.com/da9f2b7a3572abaa2e99f677a3866c1d.png)

No data logging
![](https://i.gyazo.com/16e6b25a5ce6ce2a3f4b1c84dcf7dfb3.png)

**Comment by jensj12** [comment]
I can confirm this on another GigaCoaster I've built. Not sure if it happens with giga coasters only or if it happens with every giga, but it happens more than just once.

**Comment by hypocube** [comment]
It must have something to do with the cable lift hill because when I remove it then it starts to log data.

Also the game crashes when I right-click edit this coaster, which is synchronized with another coaster.

**Comment by Nubbie** [comment]
Commit 03299b9
Could not replicate this with ride, "Spiraling_Phoenix"

**Comment by Gymnasiast** [comment]
Cannot reproduce this on 5fb6c57a5d89e5c9f3920e42945271bd78bceba0. Appears to be fixed.
