### ISSUE TITLE
Add both Windows-1252 and UTF-8-compatible currency symbols.

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#2371]
In order to allow the Czech crown and South-Korean Won to show up correctly in UTF-8 languages, while not breaking languages that still use the bitmap font. (#2360 and #2262)

**Comment by IntelOrca** [comment]
Its not just bitmap, it will need the feature if a TTF font is used not containing the required glyph.

**Comment by Killermannvs** [comment]
Just to make sure, czech currency does not use any special symbol like euro (€).
Symbol is two glyphs (Kč):
http://www.fileformat.info/info/unicode/char/004b/index.htm
and
http://www.fileformat.info/info/unicode/char/10d/index.htm

Thx for helping.
