### ISSUE TITLE
[BUG] "Reset Crash Status" cheat not working

### ISSUE THREAD

**Issue by Enzemo** [OpenRCT2/OpenRCT2#2376]
As the title says. 

Air Powered Rollercoster 1 crashed because I turned off the test mode by accident (Was using no crashes cheat, but crashes still occur if the ride is off). The ride crashed, and for some reason, reset crash status won't work. I can't seem to get it to test anymore.

Coastercloud is in read-only, so download the attachment and change the filename to .sv6

Thanks
![crash status - look at air powered coster](https://cloud.githubusercontent.com/assets/11069930/11388268/3c4fcd1e-932c-11e5-9b9d-0919c09444a2.png)

**Comment by Gymnasiast** [comment]
Works as intended. You need to double close.
Reset crash status makes the game forget that a ride has ever been crashed, so the people will ride it again.

**Comment by IntelOrca** [comment]
@duncanspumpkin is / was / will work on a better solution to this workaround - but this will be for next release (0.0.4).
