### ISSUE TITLE
Scenery dots in map window are one pixel off

### ISSUE THREAD

**Issue by ghost** [OpenRCT2/OpenRCT2#2377]
Here I go nitpicking again! This also occurs in the original game.

In this picture, I am in the scenario editor and have placed a base block on the very corner of the map. However, in the map window, scenery items are always seen one pixel to the left of whatever tile they are on.
![scr4](https://cloud.githubusercontent.com/assets/15527244/11403591/2d9b3664-9363-11e5-8256-c7265a8247be.png)

**Comment by duncanspumpkin** [comment]
This is the same as the original and its not really a bug.

**Comment by osconnoisseur** [comment]
Hmm... It may have been intentional so that the scenery elements occupy the "off" pixels and don't cover up more important map elements.

**Comment by Gymnasiast** [comment]
Hm, that might be it. Not sure what to make of this.

**Comment by Patrik356b** [comment]
looks like it's off only on one side which makes it more odd...

**Comment by IntelOrca** [comment]
@Gymnasiast this is the same as the original so there is nothing to investigate per se. A discussion for alteration.

**Comment by osconnoisseur** [comment]
Has the code for plotting pixels on the map been decompiled yet? If it has, we can investigate this further and get an idea of what the original intent was.

**Comment by duncanspumpkin** [comment]
yes it has been implemented. Its in windows/map.c

**Comment by osconnoisseur** [comment]
Ok, I see how this works. map_window_get_pixel_colour_peep() is the relevant function here. Each so-called "dot" is really two pixels wide, hence why everything is uint16. Land that is not owned has the low-order (left) pixel set to 10 (a blackish color), giving it that dot-matrix look. If there's a scenery item on that tile, then the low-order pixel gets set to 0x63.

This whole file will probably need to be refactored to use separate uint8 values to be non endian-dependent.

**Comment by Nubbie** [comment]
Is it really a problem?
It seems to be off one pixel by one side, but feels a bit redundant as it's just a pixel

**Comment by Gymnasiast** [comment]
Well, it looks like it's intentional and there does not seem that people want it changed, so I'm closing this.
