### ISSUE TITLE
Map animations get corrupt

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#2381]
We have now had two reports where a user's saved game has become corrupt:
https://openrct2.org/forums/topic/675-assertion-failed/

I think in both cases, this occurred after building (possibly scenery) whilst in pause mode using the cheat to build in pause mode. When inspecting the two saved games where this happened, many of the map animations have invalid type values which is what causes the assertion.

It is quite severe as to fix the saved game, all the map animations have to be removed which then stops animated scenery and scrolling banners from working properly. We have no mechanism of restoring map animations.

**Comment by duncanspumpkin** [comment]
For some reason the max animations check has been removed from map_animation_create. That could be the cause of the issue. If you were to create >2000 animations then you would enter into memory used by the ride ratings. When in paused mode animations are never removed so its possible to get over 2000 animations if you spam a load of queues. I can't know for sure though.

**Comment by IntelOrca** [comment]
That sounds highly plausible... how did the limit check get removed?

**Comment by duncanspumpkin** [comment]
Yes this is the cause. This save has 3800 map animations!

**Comment by IntelOrca** [comment]
Most of the types of map animations are permanent, how is the limit being reached in pause mode and not unpaused mode?

**Comment by Broxzier** [comment]
So far I've seen it happen to 4 parks, two people who streamed, one of my own, and then the person who uploaded it yesterday. For all of these I'm 100% sure they build a lot in pause mode, though that doesn't mean it's what is causing this issue.

**Comment by duncanspumpkin** [comment]
In pause mode the `map_animation_invalidate_all` function is never called. That is the function that also removes invalid animations such as when you are building a queue and move the banner.

**Comment by IntelOrca** [comment]
Kinda related to #2375 then.

**Comment by Broxzier** [comment]
And ghosts, I just tested it and apparently these make a new animation for each tile you hover over. Reaching 2k wouldn't take too long in that case.

**Comment by IntelOrca** [comment]
I see... we need to do something about this then if in paused mode.

**Comment by duncanspumpkin** [comment]
It would be quite a bit of copy paste code but we could do a stripped down map_animation_invalidate_all to check for any invalid animations and remove them during pause mode.

**Comment by IntelOrca** [comment]
Hmm, perhaps it would be simpler just to run map_animation_invalidate_all... but add pause checks in the animations that actually change state of the map elements... which I think is only small scenery, on-ride photo and unknown wall.

**Comment by duncanspumpkin** [comment]
Okay that sounds the simplest suggestion I'll do it right now as i have the files open.

**Comment by IntelOrca** [comment]
Unknown wall can probably be renamed to door... although it might also be used for something else (not sure)

**Comment by duncanspumpkin** [comment]
#2375 was unreleated still trying to solve that one.
