### ISSUE TITLE
Testing a ride with a stretched out window leaves artifacts

### ISSUE THREAD

**Issue by hypocube** [OpenRCT2/OpenRCT2#2384]
If a ride is closed, window stretched out, then tested, the window will revert to default size and leave behind artifacts.

Edit: Better reproduction method: Click the ride to open window, stretch out the window, edit the ride, test the ride.

![](https://i.gyazo.com/8d981ddfb472d1aa3b817cf4ee6669c3.png)

**Comment by Gymnasiast** [comment]
Does this happen in the unmodified version of RCT2 as well?

**Comment by Broxzier** [comment]
I'm unable to reproduce this with these steps. What build are you using?

**Comment by hypocube** [comment]
More exact steps: Test the ride, select train 1, stretch the window out completely, close twice to reset the ride. I'll find out if it happens in vanilla when I get to a computer

**Comment by hypocube** [comment]
Trying it in vanilla RCT only uncentered Overall View

**Comment by IntelOrca** [comment]
@hypocube please state the version of the game you are using. It will say at the bottom left on the title screen.

**Comment by hypocube** [comment]
v.0.0.3-develop build A1028 (9b1e124)

**Comment by Broxzier** [comment]
![](http://i.imgur.com/FkG3wyD.png)

Turns out to be easy to reproduce.

1. Build a ride and open its window
2. Enlarge the ride window, and click test
3. Click the ride again

**Comment by mrtnptrs** [comment]
I can reproduce it, but it seems it does not occur in OpenGL mode.

**Comment by IntelOrca** [comment]
@Broxzier can you reproduce this still?

**Comment by Broxzier** [comment]
Yes, and I found an even easier way to reproduce it.

0. (optional) Pause the game to make it less likely that the screen gets invalidated
1. Enlarge ride window
2. Click ride again

**Comment by Broxzier** [comment]
With OpenGL it seems to happen too, but it's less visible. Only on top of the ride's window it gets drawn incorrectly:
![](http://i.imgur.com/edKZDLn.png)

**Comment by IntelOrca** [comment]
I still can't reproduce it.

**Comment by Broxzier** [comment]
This video might help: http://i.imgur.com/edKZDLn.png

**Comment by IntelOrca** [comment]
Can you send me the saved game you are using?

**Comment by Broxzier** [comment]
Sure, but it's not save-file specific. This works on any scenario. Tested on 548724a. This bug does not occur in RCT2.

[The OpenRCT Group Park 4.17.zip](https://github.com/OpenRCT2/OpenRCT2/files/504391/The.OpenRCT.Group.Park.4.17.zip)

**Comment by IntelOrca** [comment]
OK it was because I had the traffic lights UI.
