### ISSUE TITLE
Clicking the construction button in the ride window a second time will try to construct the first ride built

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#2395]
Steps to reproduce:

1. Build two rides, doesn't matter which, even stalls work.
2. Click on the second ride you built, and click Construct.
3. Click construct again.

Now the first ride / stall you built will be reconstructed instead of the ride for which the windows is meant.

Tested _pre-release-0.0.3 A1036 (launcher)_, _v0.0.2 stable build_, and on 207e8e80085644648e4fb3cab433c7defe43bd60.

**Comment by duncanspumpkin** [comment]
Fixed in the pre-release.
