### ISSUE TITLE
Complete Peep Update

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#2399]
Goal for 0.0.4 is to complete the peep update code and all peep ai.

**Comment by jackinloadup** [comment]
What is the goal of this task?

**Comment by duncanspumpkin** [comment]
There are still a few little bits of peep update code that have not been implemented. The ai for example for staff has not been done at all and the mechanic code has not been completed.

**Comment by marijnvdwerf** [comment]
Is there anything left for this after #2903 and #2880?

**Comment by duncanspumpkin** [comment]
There is one function left after those two. The one that chooses what a peep should look at.

**Comment by duncanspumpkin** [comment]
Peep update has now been fully implemented.
