### ISSUE TITLE
Ability to save rides that aren't complete/rated

### ISSUE THREAD

**Issue by raidcookie** [OpenRCT2/OpenRCT2#2404]
I wonder if it'd be possible to save track designs that aren't complete (as in, unable to complete a test run) or not yet rated. As someone who's often using track pieces as scenery, it'd come in handy to save presets.

**Comment by Gymnasiast** [comment]
There is a good reason why you can't save them: a track design has several statistics, like maximum/average speed, ratings, etc. that are not present on untested rides.

**Comment by duncanspumpkin** [comment]
@Gymnasiast there is nothing to stop you from leaving those fields blank though. I see no reason why this couldn't be done. For a track to save all track you want must be connected to the first station piece thats the only thing that might cause issues.

**Comment by IntelOrca** [comment]
Rather than trying to get this to work, we should just wait until we work on our new save scenery block preset feature.

**Comment by Gymnasiast** [comment]
Seems a better idea to me too, especially considering that the track pieces in question are used _as_ scenery.

What do we do with this issue, though? Close it?

**Comment by IntelOrca** [comment]
We have #2250 as our scenery saving issue... but that won't include track unless by that time we have made some way of having neutral (rideless) track.
