### ISSUE TITLE
All shops are rendered as if they are on supports

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#2405]
Note for example the 7UP machine in the screenshot. It's on solid ground, yet has the wooden support structure it would have when it was placed in the air.

![scr102](https://cloud.githubusercontent.com/assets/1478678/11477168/fe756580-9786-11e5-93a2-4b28e2f3dd94.png)

**Comment by duncanspumpkin** [comment]
Fixed in pre-release.
