### ISSUE TITLE
Move title sequences to different repo

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#2408]
Title sequences are updated each version. This will rapidly increase the repository size making it take longer to clone locally. These title sequences could be instead hosted in a different repository and downloaded directly from GitHub to the local main repository via a install script.

**Comment by AaronVanGeffen** [comment]
Why not make use of git submodules?

**Comment by janisozaur** [comment]
We already discussed that on gitter, they usually create more problems than they solve.

**Comment by janisozaur** [comment]
Personally, I have another argument against them: they would break automated PPA builds which I'm working on.

**Comment by marijnvdwerf** [comment]
What about [Git Large File Storage](https://github.com/blog/2069-git-large-file-storage-v1-0)?

**Comment by IntelOrca** [comment]
@marijnvdwerf I have tried it awhile ago, I am not sure really:
* It requires git clients to be capable of handling it.
* You are limited to 1GB in bandwidth! per month.

**Comment by PFCKrutonium** [comment]
Why not store them on a webserver can curl them when needed?

**Comment by spacek531** [comment]
How is progress on this? I would like to know so that I can make an appropriate pull request when I finish the sequence.

**Comment by janisozaur** [comment]
none

**Comment by janisozaur** [comment]
See also: https://github.com/OpenRCT2/OpenRCT2/issues/3355 which would be a pre-requisite.

**Comment by IntelOrca** [comment]
@janisozaur why?

**Comment by janisozaur** [comment]
Hmm, I must have thought of different thing, there was discussion once about pulling title sequence parks from RSS feed. I meant that.

**Comment by IntelOrca** [comment]
Waiting for #4792

**Comment by janisozaur** [comment]
Mark as fixed now?
