### ISSUE TITLE
Save user data in $XDG_DATA_HOME under Linux

### ISSUE THREAD

**Issue by Thaodan** [OpenRCT2/OpenRCT2#2410]
User data like saves should be in $XDG_DATA_HOME under linux not in ~/.config.
This extends #1188

**Comment by janisozaur** [comment]
it is there already.

```
$ tree ~/.config/OpenRCT2 
/home/janisozaur/.config/OpenRCT2
├── config.ini
├── config.ini~
├── landscape
├── plugin.dat
├── save
│   ├── 9e16d8ee5cf4acc4888f7bcb28cfc279.sv6
│   ├── autosave.sv6
│   ├── broken scenario.zip
│   ├── bug_1895.sv6
│   ├── multiplayer.sv6
│   ├── Over The Edge-klapaucjusz.sv6
│   ├── Over The Edge.sv6
│   ├── Pathfinding Bug replication2.sv6
│   └── Pathfinding Bug replication.sv6
├── scores.dat
├── screenshot
│   ├── SCR1_2x.png
│   ├── SCR1.png
│   ├── SCR1_xbrz.png
│   ├── SCR2.png
│   ├── SCR3.png
│   └── test.gif
├── servers.cfg
├── themes
├── title sequences
└── tracks.idx
```

**Comment by Thaodan** [comment]
Nope user data (not config!) still lies in $XDG_CONFIG_HOME/OpenRCT2 , data like saves should be in $XDG_DATA_HOME.

**Comment by janisozaur** [comment]
Yes, I made my comment too quick and realised I was wrong. I deleted that comment.

The directory for saves is not the best now and I agree that there must be a better place, `$XDG_DATA_HOME`, if available, should be used.

**Comment by Thaodan** [comment]
thanks, btw the plattform should be not just Linux, Windows and OS X have the same issues just for their respective dirs.

**Comment by IntelOrca** [comment]
@Thaodan can you elaborate as I don't see the similarity

**Comment by Thaodan** [comment]
Windows and OS X have dirs for user data too (I don't know if they seperate configs) and this data shouldn't be in the appdir.

**Comment by IntelOrca** [comment]
@Thaodan On Windows its stored in Documents/OpenRCT2...

**Comment by Gymnasiast** [comment]
I won't deny the current behaviour does not entirely match the XDG rules about user data. 
However, changing it does not solve anything besides ticking a box as far as I'm concerned, but it does make stuff more complicated for Linux users. For example, backing up your OpenRCT2 files. There is a reason why many programs (like Firefox) save their data under one folder.

For this reason, I'll veto it.
