### ISSUE TITLE
Linux: allow to save openrct2 in /usr/bin

### ISSUE THREAD

**Issue by Thaodan** [OpenRCT2/OpenRCT2#2411]
Like the title says: openrct2 should be able to lie in /usr/bin ($bindir) and not in  /usr/share ($datadir).

**Comment by janisozaur** [comment]
Can you contribute to https://github.com/OpenRCT2/OpenRCT2/pull/2285 ?

**Comment by janisozaur** [comment]
Installed https://aur.archlinux.org/packages/openrct2-git/ to test, this is now possible and working.
