### ISSUE TITLE
Unchecking "Music" checkbox in audio settings menu doesn't stop title screen music

### ISSUE THREAD

**Issue by e-foley** [OpenRCT2/OpenRCT2#2419]
Tested in build 1497.  From the title screen, open the options menu and navigate to the audio tab.  Uncheck "Music"  and observe that the title screen music continues playing.  The music slider itself still works as expected.

**Comment by IntelOrca** [comment]
Not sure if this was intentional or not when @zsilencer implemented these. It feels connected to #1270 which I think needs sorting out as well.

**Comment by Gymnasiast** [comment]
Should have been fixed by b46e45a.

**Comment by IntelOrca** [comment]
@Gymnasiast actually I changed the string to say Ride Music instead for the checkbox. You can turn off the title screen music using the title screen music selection dropdown.
