### ISSUE TITLE
Use ISO 639-1 for language files

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#2420]
All language files should be renamed after their correct ISO 639-1 language name. This can help language fallback by choosing the same language if the desired dialect / country is not available.

See:
https://msdn.microsoft.com/en-gb/library/ee825488(v=cs.20).aspx

**Comment by Gymnasiast** [comment]
Which of those do you mean? Those in the left column I hope? (zh-CHT and such?)

**Comment by IntelOrca** [comment]
yes, en-GB, en-US, zh-CHT

**Comment by Gymnasiast** [comment]
What about translations that are not supposed to be region specific? The Korean translation is for both South Korea and North Korea, the Dutch translation is for the entire Dutch language area (The Netherlands, Belgium, Suriname and the Caribbean Netherlands), the German translation is also for every German part. Do we use `ko`, `nl` and `de` for those?

**Comment by IntelOrca** [comment]
Usually in software, it will just pick one - the others will fall-back to what ever is there.

**Comment by Gymnasiast** [comment]
Oh, ok. In that case `ko-KR`, `nl-NL` and `de-DE` would fit best. (Although I'm very careful to make the Dutch translation work for at least The Netherlands and Belgium. In comparison with English, the regional varieties in Dutch are very minor, and there are no differences in spelling because that's controlled by the Taalunie (language union).)

**Comment by IntelOrca** [comment]
Yea, just choose the region its most accurate to, and other regions can use that. If they really want to have those minor differences they can submit a new one for their region.

**Comment by Gymnasiast** [comment]
In the case of Dutch, that's exactly what I want to avoid. It's a wasted effort in the case of Dutch as far as I'm concerned.

**Comment by IntelOrca** [comment]
Hopefully no one will want to do that then...

**Comment by telk5093** [comment]
Actually, Korean in South(표준어; Pyojuneo) and in North(문화어; Munhwaeo) have little differences even though it is understandable for each other.
Of course, You might know there is no one who can translate the game into Korean in DPRK ;)

**Comment by IntelOrca** [comment]
@telk5093 We aren't anything there aren't differences between regions, but a translation should be based on a single region rather than a hybrid. The region its based on is the region its named after. Then other regions can either use that version of the language or roll their own region specific version.

**Comment by dpk** [comment]
See [BCP 47,](https://tools.ietf.org/html/bcp47) an application of ISO language codes to computer purposes which is probably what you're looking for.

> German translation is also for every German part

If there's a "German (Switzerland)" (`de-CH`) option, all instances of 'ß' should be changed to 'ss'.
