### ISSUE TITLE
Change default zoom in/out keys

### ISSUE THREAD

**Issue by wolfblake** [OpenRCT2/OpenRCT2#2421]
The shortcut keys for zooming in and out should be switched.
![69](https://cloud.githubusercontent.com/assets/5151086/11528381/ec09e80a-98ab-11e5-9112-c5b983976a92.png)

**Comment by IntelOrca** [comment]
Why?

**Comment by Patrik356b** [comment]
I don't see the point when keys are used. Otherwise "invert zoom" is a good
option. In this case you can easily change this yourself by reassigning the
keys

On Wed, Dec 2, 2015 at 12:04 PM, Ted John <notifications@github.com> wrote:

> Why?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenRCT2/OpenRCT2/issues/2421#issuecomment-161261584>.
>



-- 
Best regards; Hexile

**Comment by wolfblake** [comment]
I feel like it would make more sense for Zoom to be page up, but ok if I have to manually change it I will.

**Comment by HaasJona** [comment]
Well, if you are in a helicopter above the park and you go up, everything gets smaller. If you go down, everything gets bigger. So I think the current key bindings make sense.

**Comment by osconnoisseur** [comment]
There's also the scroll wheel, which only takes a slide of the finger to zoom in and out.

**Comment by Gymnasiast** [comment]
As @HaasJona points out, going up equals zooming out. Change the keybinding on your own computer if you want to, that's why they are changeable.
