### ISSUE TITLE
Being able to place an entrance and exit at the same location.

### ISSUE THREAD

**Issue by AlexanderLaheij** [OpenRCT2/OpenRCT2#2422]
I am able to place an entrance and exit at the same location

**Comment by duncanspumpkin** [comment]
Is this with Zero Clearance on cause thats a feature not a bug. Please provide more information. Which build are you using?

**Comment by AlexanderLaheij** [comment]
Oops yeah that was the case, my mistake. I didn't realize the zero clearance tool worked like this.
