### ISSUE TITLE
Being able to have a rollercoaster track go through scenery without it being removed

### ISSUE THREAD

**Issue by AlexanderLaheij** [OpenRCT2/OpenRCT2#2423]
Being able to have a rollercoaster track go through scenery without it being removed

**Comment by duncanspumpkin** [comment]
Is this with zero clearance on? Which build? Any steps to reproduce. Any pictures.

**Comment by AlexanderLaheij** [comment]
again oops: Oops yeah that was the case, my mistake. I didn't realize the zero clearance tool worked like this.
