### ISSUE TITLE
Title sequence creation filename issue

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#2429]
Source:
https://www.reddit.com/r/openrct2/comments/3v6ory/title_sequence_cannot_load_park/

> Build A1049
> I'm having trouble with a park I want to use in a title sequence. I get the following errors when I make the title sequence play:

```
ERROR[..\src\scenario.c:216 (scenario load]: failed to find scenario file.
ERROR[..\src\title.c:399 (title_do_next_script_opcode)]: Failed to load: "C:\Users\Me\Documents\OpenRCT2\bin\data\title\rct2\Thrills and Chills Wonderland 2.C:\Users\Me\Documents\OpenRCT2\bin\data\title\rct2\T" for the title sequence.
```

> janisozaur: Have you tried renaming your park to not have space in the filename?
> raiser: the 4 other parks I have used in title sequences all have spaces in their names, and they still work. Nonetheless, I tried it and it did work.

**Comment by IntelOrca** [comment]
Given that there is a workaround, it is not necessary to fix for 0.0.3.1, however if fixed before that is release then it can go in.

**Comment by mrtnptrs** [comment]
Does this bug still occur after all the text changes of the last months? I'm not familiar with the title sequence editor, so it would take much time for me to reproduce the problem.

**Comment by AaronVanGeffen** [comment]
Given we use .parkseq zips nowadays, is this still relevant?

**Comment by tupaschoal** [comment]
Tried reproducing and couldn't (maybe because of Aaron's comment on `.parkseq`.
[Test Spaces.zip](https://github.com/OpenRCT2/OpenRCT2/files/5331085/Test.Spaces.zip)
