### ISSUE TITLE
Crash after removing ride with object selection

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#2432]
> So I started making a scenario going about it the usual way, picking a whole bunch of objects that I want to be in the park and then moving on to the landscape editor.

> I have pretty much finished all that I want to do with the landscape, but now if I go back to the object editor and deselect some rides (because I decided I wanted to take out the ability to make giant steel coasters), the second I click to go back to the landscape editor again the game stops responding and can't be brought back.

> I have also tried deselecting everything I want to, saving the scenario as a new test copy, and then opening that copy. Strangely, saving the scenario doesn't even record the changes I've made in the object editor, because everything is selected again.

https://openrct2.org/forums/topic/689-game-crashes-if-i-remove-a-ride-from-a-scenario-im-making/#comment-2214

I haven't been able to reproduce this myself so far.

**Comment by spacek531** [comment]
I have seen both but I have not yet found a cause.
