### ISSUE TITLE
Crash in Peep.c

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#2433]
![krutland](https://cloud.githubusercontent.com/assets/3945538/11579177/a6c3256e-99f9-11e5-9f0d-3752ce063813.png)
![crash](https://cloud.githubusercontent.com/assets/3945538/11579186/b699b12e-99f9-11e5-8603-4a146492d67a.PNG)

Krutland.png is the save file, it crashes about 4 seconds after loading.

**Comment by IntelOrca** [comment]
How many people are going to report this same bug???

**Comment by duncanspumpkin** [comment]
Yeah I'm going to reopen the issue until pre-release is merged.

**Comment by PFCKrutonium** [comment]
Yah, for things like this, perhaps leave it open till it is merged into the dev branch in the future... Otherwise searching won't find it.
