### ISSUE TITLE
Dropdown menus linger when toolbars are toggled

### ISSUE THREAD

**Issue by e-foley** [OpenRCT2/OpenRCT2#2434]
Tested in build 1499.

1. Click a button on the main toolbar that causes a dropdown list.
2. While the list is open, toggle the toolbar with the 'T' key.

You'll see the dropdown remain on the screen even though its options cannot be selected:
![scr40](https://cloud.githubusercontent.com/assets/6338134/11584394/82b02004-9a18-11e5-8ed5-66a0d57e079f.png)

**Comment by IntelOrca** [comment]
Fixed in pre-release-0.0.3.1.
