### ISSUE TITLE
Non-integer time amounts for title sequences

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#2438]
Currently, timing the cuts to the music is difficult because there is no way to get non-integer time increments. If floats or doubles were implemented as time increments for title sequences, cuts could not only be on the beat, but the title sequence could end at the exact same time as the music, preventing the music from drifting across the title sequence.

**Comment by Gymnasiast** [comment]
That point is moot, as OpenRCT2 allows switching between the RCT1 and RCT2 title screen music anyway.

**Comment by duncanspumpkin** [comment]
I think we should have an option to prefer a type of music for a sequence as well then.

**Comment by IntelOrca** [comment]
Perhaps there could be time constants that are different depending on what music track is selected.

**Comment by spacek531** [comment]
I think the timing should ultimately be de-linked from the music. Some cuts may be timed so that it follows a coaster and cuts on the beat, but if the tempo was changed then it would no longer do that. If sharing of title sequences ever becomes a widespread thing, you could say, "this title sequence works best with suchandsuch music," but it wouldn't become totally unwatchable if the music was changed.

**Comment by Broxzier** [comment]
@spacek531 I don't think duncanspumpkin means that the music should be switched, but that the title sequence can 'prefer' a song to be played. For example if you make your own title sequence, you'll be able to select Pirate Theme as startup song instead of the default.

**Comment by spacek531** [comment]
@Broxzier I was actually referring to IntelOrca's suggestion.

**Comment by IntelOrca** [comment]
Well, this wouldn't be hard to implement if anyone would like to volunteer.

**Comment by spacek531** [comment]
I'm working on getting a compiler so that I can pitch in.

**Comment by spacek531** [comment]
Some comments I made in the reddit about expansions to this idea:

> Calculate the overall elapsed time that the cut should happen on. It sacrifices a little bit of the visual > > synchronization for audio synchronization.
> 
> After loading, jump the simulation ahead the time taken for loading. Possibly a little more jarring > during the transition, but doesn't require overall elapsed time calculations.
> 
> Use the END command to signal to the title sequence manager that it wants to restart the title > sequence when the music next replays.

**Comment by zsilencer** [comment]
If you want to really have it accurate for the music then it would be best to use Mixer_Channel_GetOffset in the script, otherwise it's a combination of loading data and inconsistently timed ticks (mostly if uncap fps is off) that would cause drifting out of sync.

**Comment by Gymnasiast** [comment]
Title sequences switched to milliseconds, closing this bug.
