### ISSUE TITLE
GameSave crashes when rendering certian track piece

### ISSUE THREAD

**Issue by Double0negative** [OpenRCT2/OpenRCT2#2439]
In this save http://mc-sg.org/files/SuperParkCrash.sv6 there is a track piece on the ride "Corkscrew Roller Coaster 1" or "Looping Roller Coaster 1" that causes the game to crash when rendered.

**Comment by janisozaur** [comment]
Interesting. I can reproduce on Linux too.

**Comment by janisozaur** [comment]
It crashes somewhere in original code, I can get no stack trace.

**Comment by Broxzier** [comment]
Is crashes in vanilla rct2 as well.

**Comment by janisozaur** [comment]
@Double0negative can you provide more insight how this could get corrupted?

**Comment by duncanspumpkin** [comment]
Its track pieces on both rides causing the crash. Its trying to draw track parts that don't belong to the ride type. I've manage to delete the two offending rides if you want to keep playing @Double0negative

**Comment by Double0negative** [comment]
@janisozaur My friend was playing with me on multiplayer and desynced. He went to build Twister Coaster but because he was desynced the game thought he was building a corkscrew coaster on my end. He placed a track piece that Twister coasters have (Large half loop), but cork screw coasters dont have, and that seems to have corrupted the save, which @duncanspumpkin confirms.

Also, if you have a fixed save file, I would love to have that to keep playing.

**Comment by duncanspumpkin** [comment]
Ahh i can convert it back to twister coaster.

**Comment by duncanspumpkin** [comment]
http://www.filedropper.com/coastersavedsuperparkcrash That should be the save fixed.

**Comment by Double0negative** [comment]
Thank you very much, that worked.
