### ISSUE TITLE
Placing tracks with hacked operating modes revert the mode to default

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#2445]
...except when the "show all operating modes" cheat is enabled. This happens in vanilla RCT2 as well.

The GCI concept this coaster is a recreation of uses reverse incline launch, which is not one of the operating modes of woodies. When the design is placed, the placer has to enable cheats to select the operating type. If they have "show all operating modes" enabled when placing it, the coaster has the proper operating type. Saving and loading of parks does not have this problem.
![image](https://cloud.githubusercontent.com/assets/3454156/11617472/8178cce4-9c44-11e5-83f4-1be6634b1be2.png)

**Comment by Gymnasiast** [comment]
In addition to fixing the bug (which is anti-cheat code from RCT2 really): if real-life Wooden Roller Coasters can have reverse incline launch, I'd say OpenRCT2 should add that mode for Wooden RCs as well.

**Comment by IntelOrca** [comment]
I'd say its unlikely, realistically wooden roller coasters are very old roller coasters that wouldn't typically have more modern mechanics such as reverse lift hill and powered launch. If this mode was enabled for wooden RC then you might as well make all modes that work available for all coasters (bypassing what the object file says).

Or... you just keep the cheat which allows anyone that wants to do this, do this.

**Comment by Broxzier** [comment]
There are wooden coasters with similar mechanics. https://youtu.be/QBw9ZlCol2I

**Comment by Gymnasiast** [comment]
Wooden RCs are not realistically very old. The type has been around for a long time which is an entirely different thing. For example, all wooden roller coasters in The Netherlands are very new; most of them are even from the 21st century. Three examples: Joris en de Draak, 2011; Troy, 2007; Robin Hood, 2000.

In addition, spacek531 mentioned the coaster being a GCI concept.

**Comment by IntelOrca** [comment]
OK - maybe they are still built for retro / classic style purposes, which therefore wouldn't have the more modern operating modes.

**Comment by spacek531** [comment]
Broxzer's video shows that isn't the case any more. Lightning Rod is another counterpoint, but it's not totally applicable to this specific case.

It is my opinion that as progress marches on, more and more thrill rides will have these unusual operating modes, and it would be nice to include them in the ingame selection, but it isn't important in the short-term.

**Comment by IntelOrca** [comment]
Fair enough, I won't object to it the defaults being changed then - but that doesn't fix this issue.

**Comment by Gymnasiast** [comment]
Sure, but that's why I prefixed this idea with `In addition to fixing the bug ...`.

**Comment by IntelOrca** [comment]
Sure... lets just not get carried away.

**Comment by Gymnasiast** [comment]
Trust me, I won't. :P
