### ISSUE TITLE
OpenRCT2 on OSX

### ISSUE THREAD

**Issue by NielsJoormann** [OpenRCT2/OpenRCT2#2448]
Hey all!
Just saw this awesome project coming along somewhere and I decided to give it a try to install this on OSX. I downloaded and unzipped the master branch at https://github.com/OpenRCT2/OpenRCT2/tree/master. Then, I tried to follow the instructions at https://github.com/OpenRCT2/OpenRCT2/wiki/Building-OpenRCT2-on-OSX but I don't get past step 2: "Append /usr/local/mingw-w32-bin_i686-darwin/bin/ to your PATH variable. Do this by adding the line export PATH=/usr/local/mingw-w32-bin_i686-darwin/bin/:$PATH to your .bashrc, .bash_profile or /etc/bashrc." After step 1: " bash install.sh "  they do not show up, or is that not supposed to happen? Where can I find these .bashrc, .bash_profile or /etc/bashrc files? And how can I modify them? Any help would be great!

**Comment by janisozaur** [comment]
Since you're asking about some basic stuff, I'm going to assume you're not going to compile it from sources.

You may rather want to use [wine](https://www.winehq.org/) and install the windows build. They are available somewhere, just google.

**Comment by janisozaur** [comment]
See https://www.reddit.com/r/openrct2/comments/3wcr9j/native_os_x_support_just_got_merged/

@NielsJoormann if that answers your question, can you close this issue or if not, state the problem you face.
