### ISSUE TITLE
Attractions sometimes render through walls

### ISSUE THREAD

**Issue by joflashstudios** [OpenRCT2/OpenRCT2#2458]
The game sometimes renders underground attractions through walls, often flickering. This can include shops and stalls, ride entrances and exists, and at time ride vehicles. This may have something to do with clearances, as the problem tends to be worse if there is no free underground space above the attraction. I have also observed that this sometimes dispends on what ismoetric angle it is being viewed at.

![image](https://cloud.githubusercontent.com/assets/7459309/11719397/d36bbd7c-9f5a-11e5-9a3d-b99e290310b0.png)

In a somewhat related issue, there seems to be no unified standard for how to render shops that are underground but are accessed by a path above-ground. While ride enterences and exits render a two-tile high portion of themselves, shops either render nothing or a flickering, incosistant image of themselves.

![image](https://cloud.githubusercontent.com/assets/7459309/11719624/e6abec1c-9f5b-11e5-9451-206032d91486.png)

**Comment by IntelOrca** [comment]
Could you provide what version of the game you are using (shown on title screen) and whether any of this happens in the original game?

**Comment by spacek531** [comment]
I noticed this when I was recording my title sequence video. At 7:28 you can see some of the junior coaster being rendered in front of the terrain: https://youtu.be/ByDciXpRpok?t=448

I don't recall this happening before. The version is A1059.

**Comment by IntelOrca** [comment]
@spacek531 Please specify the entire version as A1059 is specific to a build server not this repository:
![image](https://cloud.githubusercontent.com/assets/1482259/11725680/caad9e4a-9f72-11e5-8ea4-abdb510c2b4a.png)

**Comment by spacek531** [comment]
I didn't notice that had been added, I will include it in the future.

**Comment by joflashstudios** [comment]
I'm using release 0.0.3, and yes this happens in vanilla, though it seems to a somewhat lesser extent.

**Comment by tupaschoal** [comment]
A very similar issue is linked above with steps to reproduce, which this issue doesn't, so I'll close it.
