### ISSUE TITLE
OS X build should have a proper icon

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#2463]
![kiii78t](https://cloud.githubusercontent.com/assets/550290/11744513/446a54fa-a011-11e5-9279-9e9ef95dc624.png)

We have no icon on OS X (see the 6th icon from right, the one with "exec"). We should use the ![flag logo](https://github.com/OpenRCT2/OpenRCT2/blob/develop/resources/logo/icon_flag.svg).

**Comment by AaronVanGeffen** [comment]
Going by memory here, but icons in OS X are handled through a bundling system -- basically, they require the binary to be placed in a directory ending in ".app", with the icons as separate files in an .icns directory within said .app.

**Comment by IntelOrca** [comment]
Should the repository contain the .icns files or should they be built by CI?

**Comment by LRFLEW** [comment]
I will be working on the .app bundle a little later today. It's not too difficult to construct it from scratch, so I should be able to put the necessary files into the distribution folder.

**Comment by LRFLEW** [comment]
> Should the repository contain the .icns files or should they be built by CI?

Well, we have an .ico file in the repository, so I don't see why not.

**Comment by janisozaur** [comment]
I have a question about aforementioned `.app` bundles, I understand it's a regular directory with some metadata file embedded? Will it include things like `data/title/`, `data/language/`, `data/g2.dat`?

It seems many users have problems with launching the build I have provided… which I find odd.

**Comment by LRFLEW** [comment]
Yes, it will include the `data` folder. I'm working on updating the code so that the contents can be put where they generally should be (in the `Resources` folder), but it will be a self-contained bundle.

**Comment by PFCKrutonium** [comment]
@janisozaur If the issue is that it won't let them open it, option-click (right click) and select open.

**Comment by janisozaur** [comment]
@PFCKrutonium can you post that on reddit? And perhaps mention that the app bundle is on the way?

**Comment by PFCKrutonium** [comment]
@janisozaur Anywhere in particular?

**Comment by janisozaur** [comment]
https://www.reddit.com/r/rct/comments/3wcvvi/open2_native_os_x_support_just_got_merged/cxvljt6 and https://www.reddit.com/r/openrct2/comments/3wcr9j/native_os_x_support_just_got_merged/cxvbm1b
