### ISSUE TITLE
OS X: platform_open_directory_browser and platform_show_messagebox should be implemented.

### ISSUE THREAD

**Issue by kkirby** [OpenRCT2/OpenRCT2#2471]
On OS X, the`platform_open_directory_browser` and  `platform_show_messagebox` should be implemented to provide the best user experience.

**Comment by kkirby** [comment]
I'm currently working on this.

**Comment by LRFLEW** [comment]
`platform_show_messagebox` could probably be implemented just using `SDL_ShowMessageBox`, which would also cover linux.

**Comment by kkirby** [comment]
Is there a version for file browser? Because that would clean things up quite nicely.

**Comment by LRFLEW** [comment]
Not that I know of, no.

**Comment by PFCKrutonium** [comment]
http://stackoverflow.com/questions/6145910/cross-platform-native-open-save-file-dialogs

Some Options

**Comment by kkirby** [comment]
https://github.com/mlabbe/nativefiledialog looks perfect. I'm going to go with that unless someone else has objections.

**Comment by PFCKrutonium** [comment]
That library does not support Windows XP - Could be an issue.

**Comment by IntelOrca** [comment]
Why can't you just call OSX SDK natively?

**Comment by LRFLEW** [comment]
@PFCKrutonium We can keep the native Windows code we have for now, as it seems to be working just fine. It's the Linux and OS X code that needs to be changed.

**Comment by kkirby** [comment]
@IntelOrca We can, but we're looking for a cross-platform solution.

**Comment by LRFLEW** [comment]
I could attempt to write it natively when I have a little more time in a few days. The main thing I'd be worried about is whether we can turn the `osx.c` file into an `osx.m` file (Objective-C fully supports C code, but is also required for some Cocoa interactions).

**Comment by PFCKrutonium** [comment]
@LRFLEW It was just something I noticed, not to worry.

**Comment by IntelOrca** [comment]
@kkirby its too small to require a cross platform library and we want to keep libraries to a minimum particularly for Windows as its convoluted. We have already written our own cross platform wrappers for other directory functions.

**Comment by kkirby** [comment]
@LRFLEW I already have it implemented using Objective-C and linking the C and Objective-C together. I just needed to clean up the code a little.
@IntelOrca Okay, that sounds good. I'll keep what I have and make a PR soon.

**Comment by IntelOrca** [comment]
I think its fine to use objective-c if necessary. @mzmiric5 also suggests using an xcode project for better OSX building.
