### ISSUE TITLE
Website doesn't list 0.0.3 features on https://openrct2.com/features

### ISSUE THREAD

**Issue by e-foley** [OpenRCT2/OpenRCT2#2475]
The current [Features](https://openrct2.com/features) page on the website lists only 0.0.2 features whereas 0.0.3 is now stable and released.

**Comment by AaronVanGeffen** [comment]
I believe the entire website is currently being reworked by @JarnoVgr and @runelaenen.

**Comment by Gymnasiast** [comment]
Indeed, and it's not an official OpenRCT2 page - OpenRCT2.website is the official page, with .NET, .COM and .ORG being semi-official. Bugs can be reported on Gitter or the OpenRCT2.org forums (for all three domains).
