### ISSUE TITLE
New save/load dialogue box doesn't properly remember last sorting

### ISSUE THREAD

**Issue by spongbros** [OpenRCT2/OpenRCT2#2477]
I sort my files in the save/load box by date, most recent at the top. When I open the dialogue, whether I'm saving or loading, it always displays the files in alphanumerical order (even though there is a visible down arrow next to the word Date) and I have to click on the Date column twice to sort it again.
Here's what it looks like when open (folder path blacked out by me):
![before](https://cloud.githubusercontent.com/assets/11759652/11768084/0ba25f96-a1ba-11e5-9da8-cb7f9a81edb1.png)
Here's what it looks like correctly sorted:
![after](https://cloud.githubusercontent.com/assets/11759652/11768085/19b50df4-a1ba-11e5-8a30-a67caf3edac3.png)
```OpenRCT2, v0.0.4-develop build A1080 (32a7947) provided by OpenRCT.net & Punfumblercraft.com```

**Comment by Gymnasiast** [comment]
Can confirm.
