### ISSUE TITLE
Cable Lift Hill doesn't work with unfinished tracks with "testing with unfinished tracks" enabled

### ISSUE THREAD

**Issue by kkirby** [OpenRCT2/OpenRCT2#2479]
Just as the title says, this is an extremely low priority bug. If you have "Testing with unfinished tracks" enabled, and you are testing a Giga Coaster that is unfinished, the cable lift hill doesn't activate.

**Comment by Nubbie** [comment]
Seems to be working on the Dev 0.0.5 build f6bfbb0
![picture](https://cloud.githubusercontent.com/assets/17282384/14705025/ed34eb82-07b7-11e6-80a2-7e8c5bbb0e01.png)

**Comment by IntelOrca** [comment]
"Testing with unfinished tracks" is only temporary until we implement #485. So I am not sure whether its worth fixing this or other problems such as not being able to test in block mode.

**Comment by duncanspumpkin** [comment]
#485 has been implemented closing this now.

**Comment by hawkerm** [comment]
I'm seeing the ghost train just be stuck at the bottom of the lift hill, so not sure if this original bug effects the ghost as well?

![image](https://user-images.githubusercontent.com/8959496/213107009-066d38cc-97eb-48a1-8cc2-52cc56763c56.png)
