### ISSUE TITLE
Cannot launch from NAS

### ISSUE THREAD

**Issue by LinusU** [OpenRCT2/OpenRCT2#2481]
On OS X the games crashes with "Invalid RCT2 installation path. Please correct in config.ini." when `game_path` is set to a mounted directory on a network attached storage. e.g. `/Volumes/linus' data/rct2`

**Comment by Gymnasiast** [comment]
Are you sure it isn't the apostrophe though? (Which would also be bug.)

**Comment by LinusU** [comment]
Tried by creating the folder `/tmp/linus' data` and it worked alright :+1:

**Comment by janisozaur** [comment]
How is NAS different to any other storage? Are you sure you have proper permissions set? This sounds like a problem in your setup rather then our code. Although I can't test it now, I'm confident it will work on Linux.

**Comment by janisozaur** [comment]
Just checked – it works perfectly fine. The problem must be on your end.

You can verify your copy against my shasums: https://transfer.sh/ZgsoK/shasums (that's the steam version)

**Comment by Gymnasiast** [comment]
It could still be an OS X issue. Though it might just as well be a rights issue.

**Comment by PFCKrutonium** [comment]
Just want to say, when I was initially trying to get this working, I had to rename my RCT2 folder so that the path had no spaces - could this be the issue here?

**Comment by LRFLEW** [comment]
I'm currently using a path that uses spaces in my installation on OS X and it's working fine.

**Comment by LinusU** [comment]
I have tried a local folder with both space and single quote in the name, that worked. When copying the files from the remote disk to my local disk it started working.

**Comment by Gymnasiast** [comment]
Have more OS X users tried to load a game from a NAS? And are you sure it is read/writable for normal users?

**Comment by LinusU** [comment]
It should be read/writable since I copied the files back and forth with my own user. I would love to get this confirmed by someone else, especially since it should "just work" and I cannot figure out why it doesn't...

**Comment by janisozaur** [comment]
can you launch `./openrct2 --verbose` and provide the log? For NAS and non-NAS launch would be best.

**Comment by LinusU** [comment]
I will take a look at doing that when I'm not at work :ok_hand:

**Comment by janisozaur** [comment]
@LinusU have you progressed this?

**Comment by LinusU** [comment]
Sorry, other things got in the way. I hope to do it this weekend...

**Comment by ecnepsnai** [comment]
Which protocol are you using?  (AFP, Samba, WebDAV, etc).

**Comment by LinusU** [comment]
Still haven't tried again, sorry about that. I *think* that is was Samba, but it *might* have been AFP. Pretty sure it's one of those though.

**Comment by Gymnasiast** [comment]
Could you provide an update on this?
