### ISSUE TITLE
Can't run install.sh properly.

### ISSUE THREAD

**Issue by pizza2004** [OpenRCT2/OpenRCT2#2482]
Whenever I try to run install.sh it just dies with this error while trying to build a universal version of libpng:

Undefined symbols for architecture x86_64:
  "_inflateReset2", referenced from:
      _png_inflate_claim in pngrutil.o
ld: symbol(s) not found for architecture x86_64

**Comment by Gymnasiast** [comment]
Platform?

**Comment by pizza2004** [comment]
If I don't specify it to be universal it builds just fine, but then I encounter other issues.  OS X.  I'm running a not yet merged version of install.sh which is supposed to make it install all the proper libraries for a native build.

**Comment by pizza2004** [comment]
I'm just confused, because I see everyone has managed to get it to build for some reason, and yet I keep having issues with just this single thing, even having the game fully build before getting angry at me for not having an i386 version of sdl2_ttf.

**Comment by pizza2004** [comment]
Last 15 lines from /Users/chad/Library/Logs/Homebrew/libpng/02.make:
clang -DHAVE_CONFIG_H -I.     -g -O2 -c -o contrib/libtests/pngvalid.o contrib/libtests/pngvalid.c
clang -DHAVE_CONFIG_H -I.     -g -O2 -c -o contrib/libtests/pngimage.o contrib/libtests/pngimage.c
/bin/sh ./libtool  --tag=CC   --mode=link clang  -g -O2 -no-undefined -export-dynamic -version-number 16:19:0   -export-symbols libpng.sym  -o libpng16.la -rpath /usr/local/Cellar/libpng/1.6.19/lib png.lo pngerror.lo pngget.lo pngmem.lo pngpread.lo pngread.lo pngrio.lo pngrtran.lo pngrutil.lo pngset.lo pngtrans.lo pngwio.lo pngwrite.lo pngwtran.lo pngwutil.lo    -lz 
/bin/sh ./libtool  --tag=CC   --mode=link clang  -g -O2   -o png-fix-itxt contrib/tools/png-fix-itxt.o  -lz 
libtool: link: sed 's|^|_|' < libpng.sym > .libs/libpng16-symbols.expsym
libtool: link: clang -dynamiclib  -o .libs/libpng16.16.dylib  .libs/png.o .libs/pngerror.o .libs/pngget.o .libs/pngmem.o .libs/pngpread.o .libs/pngread.o .libs/pngrio.o .libs/pngrtran.o .libs/pngrutil.o .libs/pngset.o .libs/pngtrans.o .libs/pngwio.o .libs/pngwrite.o .libs/pngwtran.o .libs/pngwutil.o   -lz  -g -O2   -install_name  /usr/local/Cellar/libpng/1.6.19/lib/libpng16.16.dylib -compatibility_version 36 -current_version 36.0 -Wl,-single_module -Wl,-exported_symbols_list,.libs/libpng16-symbols.expsym
Undefined symbols for architecture x86_64:
  "_inflateReset2", referenced from:
      _png_inflate_claim in pngrutil.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libpng16.la] Error 1
make[1]: *** Waiting for unfinished jobs....
libtool: link: clang -g -O2 -o png-fix-itxt contrib/tools/png-fix-itxt.o  -lz
make: *** [all] Error 2

**Comment by pizza2004** [comment]
Is it trying to find an older version of libpng or something?  Is that why there's an issue?

**Comment by pizza2004** [comment]
What I don't understand is why it's having an issue finding something for x86_64, when if I don't specify universal it builds as only x86_64 with no issues at all.

**Comment by Gymnasiast** [comment]
Stop double posting. Edit your messages.

**Comment by pizza2004** [comment]
Sorry about that.  You wouldn't happen to know anything about this though?

@LRFLEW and @kkirby and @LinusU I merged your 4 pull requests into my fork and then tried to build and this is the result.

**Comment by Gymnasiast** [comment]
I asked for the people working on the OS X build to look at your issue.

**Comment by LinusU** [comment]
@pizza2004 Can you try with the `install.sh` from #2469, it should work much better on OS X

**Comment by pizza2004** [comment]
I already merged #2466 #2469 #2472 and #2473 into my fork and am trying to build with all those.  This is happening to me when trying to run through that version of install.sh.

**Comment by IntelOrca** [comment]
We don't use libpng...

**Comment by janisozaur** [comment]
Have you had libpng installed before you ran the script? It may require some other options to force reinstall of libpng.

**Comment by janisozaur** [comment]
@IntelOrca but sdl2 or sdl2_TTF depends on it for osx

**Comment by IntelOrca** [comment]
ok

**Comment by pizza2004** [comment]
I've uninstalled, reinstalled, removed it, and been scouring the internet for solutions for a couple of hours now.  Found nothing useful, so I finally decided to create an issue on here.

The only thing I've found that might somehow be relevant is that people are saying something about it maybe being related to zlib or libz, but I've had no luck down that avenue so far, and I'm just wondering how everyone else on OS X managed to get sdl2_ttf to build properly.

**Comment by janisozaur** [comment]
Sdl2_TTF -> freetype -> libpng, to be exact. And I've seen some problems regarding it's installation due to it being so popular the systems holds on to it quite tight. I suppose forcing reinstall with --universal should solve that, but don't know brew options well enough.

**Comment by pizza2004** [comment]
Well, it says that sdl2_ttf also requires libpng, apart from just freetype requiring it, but no, even attempting to force a reinstall gives me the exact same error.  I never get the error unless I use --universal in the first place.  Just to be certain though, what command would I run to force a reinstall?

**Comment by janisozaur** [comment]
Sdl2_TTF does [not depend on libpng](/homebrew/blob/master/Library/Formula/sdl2_ttf.rb). Freetype [does](/homebrew/blob/master/Library/Formula/freetype.rb). I have no idea about the command line, but your problem is with brew, not with us.

**Comment by pizza2004** [comment]
Alright, I believe you then, it just lists libpng before freetype in the dependencies for sdl2_ttf.  I figured the problem could be with brew, but at the same time I have no idea where it's all happening, which is why I came here, because I know there are people who aren't having this issue, and I'm wanting to get perspectives to see what they think is causing it.

**Comment by IntelOrca** [comment]
I was originally going to make the TTF stuff optional and put guard blocks around all the TTF code, but I never got round to it.

**Comment by Gymnasiast** [comment]
I'm not sure if that's worth it though. Another ifdef to look out for and to test.

**Comment by janisozaur** [comment]
Agree with @Gymnasiast on this one. I think eventually we will replace all bitmap fonts with TTF?

**Comment by pizza2004** [comment]
Even the original bitmap font used in English?  I wouldn't want that personally, or at least I'd want the ability to run the game with the original font.

**Comment by IntelOrca** [comment]
@janisozaur eh, no I don't think you will every get that authentic font quality unless you keep the bitmap. The reason I suggest doing it is because its a dependency and like the HTTP and TWITCH stuff we have a way of disabling it for situations like this.

@Gymnasiast I don't think its worth making CI test all the different configurations...

**Comment by Gymnasiast** [comment]
@IntelOrca : What I fear is that at some point the non-TTF builds will break, and at some point the one guy who hasn't got TTF working and tries to compile without ends up with a broken build. I feel it's not worth it for a handful of configurations that aren't working _now_, to litter the entire code base for the foreseeable future.

**Comment by IntelOrca** [comment]
@Gymnasiast When we go C++, the code will be more object orientated, using interfaces the code won't look littered because things like TTF will be more plug-in/out so its simpler to guard it out the game.

**Comment by pizza2004** [comment]
Would there be any simple easy way to exclude the TTF stuff for now so I can get this to build properly?  I'm just really feeling frustrating going back and forth all over the place with no success whatsoever.

**Comment by kkirby** [comment]
@pizza2004 what version of OS X are you running and what are your machines specs? Did you install brew yourself awhile ago? Have you tried running 'brew update'? Or 'brew doctor'?

**Comment by pizza2004** [comment]
I did have issues with home-brew at first, but found ways to fix it, brew update does nothing, I'll run brew doctor.  I'm running 10.11.1.

**Comment by kkirby** [comment]
What issues?

**Comment by pizza2004** [comment]
```
Warning: /Library/Caches/Homebrew isn't writable.
This can happen if you run `brew install` or `brew fetch` as another user.
Homebrew caches downloaded files to this location.

You should probably change the ownership and permissions of /Library/Caches/Homebrew
back to your user account.
  sudo chown -R $(whoami) /Library/Caches/Homebrew

Warning: /usr/local/Cellar isn't writable.

You should probably change the ownership and permissions of /usr/local/Cellar
back to your user account.
  sudo chown -R $(whoami) /usr/local/Cellar

Warning: The /usr/local is not writable.

You should probably change the ownership and permissions of /usr/local
back to your user account.
  sudo chown -R $(whoami) /usr/local

Warning: Some directories in /usr/local/share/locale aren't writable.
This can happen if you "sudo make install" software that isn't managed
by Homebrew. If a brew tries to add locale information to one of these
directories, then the install will fail during the link step.

You should probably `sudo chown -R $(whoami)` them:
    /usr/local/share/locale/de
    /usr/local/share/locale/de/LC_MESSAGES
    /usr/local/share/locale/el
    /usr/local/share/locale/el/LC_MESSAGES
    /usr/local/share/locale/en
    /usr/local/share/locale/en/LC_MESSAGES
    /usr/local/share/locale/en_GB
    /usr/local/share/locale/en_GB/LC_MESSAGES
    /usr/local/share/locale/es
    /usr/local/share/locale/es/LC_MESSAGES
    /usr/local/share/locale/fr
    /usr/local/share/locale/fr/LC_MESSAGES
    /usr/local/share/locale/it
    /usr/local/share/locale/it/LC_MESSAGES
    /usr/local/share/locale/ja
    /usr/local/share/locale/ja/LC_MESSAGES
    /usr/local/share/locale/mal
    /usr/local/share/locale/mal/LC_MESSAGES
    /usr/local/share/locale/pl
    /usr/local/share/locale/pl/LC_MESSAGES
    /usr/local/share/locale/ru
    /usr/local/share/locale/ru/LC_MESSAGES
    /usr/local/share/locale/vi
    /usr/local/share/locale/vi/LC_MESSAGES
    /usr/local/share/locale/zh_CN
    /usr/local/share/locale/zh_CN/LC_MESSAGES
    /usr/local/share/locale/zh_TW
    /usr/local/share/locale/zh_TW/LC_MESSAGES

Warning: Some directories in /usr/local/share/man aren't writable.
This can happen if you "sudo make install" software that isn't managed
by Homebrew. If a brew tries to add locale information to one of these
directories, then the install will fail during the link step.

You should probably `sudo chown -R $(whoami)` them:
    /usr/local/share/man/man3
    /usr/local/share/man/man7

Warning: The /usr/local directory is not writable.
Even if this directory was writable when you installed Homebrew, other
software may change permissions on this directory. Some versions of the
"InstantOn" component of Airfoil are known to do this.

You should probably change the ownership and permissions of /usr/local
back to your user account.
  sudo chown -R $(whoami):admin /usr/local

Warning: gettext files detected at a system prefix
These files can cause compilation and link failures, especially if they
are compiled with improper architectures. Consider removing these files:
    /usr/local/lib/libintl.dylib

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libatk-1.0.0.2209.1.dylib
    /usr/local/lib/libfontforge.1.0.0.dylib
    /usr/local/lib/libgdk-x11-2.0.0.1200.0.dylib
    /usr/local/lib/libgdk_pixbuf-2.0.0.1200.0.dylib
    /usr/local/lib/libgdk_pixbuf_xlib-2.0.0.1200.0.dylib
    /usr/local/lib/libgdraw.4.0.7.dylib
    /usr/local/lib/libgio-2.0.0.0.0.dylib
    /usr/local/lib/libgioftp.1.0.0.dylib
    /usr/local/lib/libGLEW.1.5.4.dylib
    /usr/local/lib/libglib-2.0.0.1600.0.dylib
    /usr/local/lib/libgmodule-2.0.0.1600.0.dylib
    /usr/local/lib/libgobject-2.0.0.1600.0.dylib
    /usr/local/lib/libgthread-2.0.0.1600.0.dylib
    /usr/local/lib/libgtk-x11-2.0.0.1200.0.dylib
    /usr/local/lib/libgunicode.3.0.1.dylib
    /usr/local/lib/libgutils.1.0.3.dylib
    /usr/local/lib/libintl.8.0.2.dylib
    /usr/local/lib/libjpeg.62.dylib
    /usr/local/lib/libpango-1.0.0.2100.0.dylib
    /usr/local/lib/libpangocairo-1.0.0.2100.0.dylib
    /usr/local/lib/libpangoft2-1.0.0.2100.0.dylib
    /usr/local/lib/libpangox-1.0.0.2100.0.dylib
    /usr/local/lib/libpangoxft-1.0.0.2100.0.dylib
    /usr/local/lib/libportaudio.2.0.0.dylib
    /usr/local/lib/libz.1.2.5.dylib
    /usr/local/lib/libz.1.2.8.dylib
    /usr/local/lib/libz.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/fontforge/autowidth.h
    /usr/local/include/fontforge/baseviews.h
    /usr/local/include/fontforge/basics.h
    /usr/local/include/fontforge/bezctx_ff.h
    /usr/local/include/fontforge/bitmapcontrol.h
    /usr/local/include/fontforge/chardata.h
    /usr/local/include/fontforge/charset.h
    /usr/local/include/fontforge/config.h
    /usr/local/include/fontforge/configure-pfaedit.h
    /usr/local/include/fontforge/dynamic.h
    /usr/local/include/fontforge/edgelist.h
    /usr/local/include/fontforge/edgelist2.h
    /usr/local/include/fontforge/encoding.h
    /usr/local/include/fontforge/fffreetype.h
    /usr/local/include/fontforge/ffpython.h
    /usr/local/include/fontforge/fileutil.h
    /usr/local/include/fontforge/fontforgevw.h
    /usr/local/include/fontforge/fvmetrics.h
    /usr/local/include/fontforge/gdraw.h
    /usr/local/include/fontforge/gfile.h
    /usr/local/include/fontforge/ggadget.h
    /usr/local/include/fontforge/gicons.h
    /usr/local/include/fontforge/gimage.h
    /usr/local/include/fontforge/gio.h
    /usr/local/include/fontforge/gkeysym.h
    /usr/local/include/fontforge/gprogress.h
    /usr/local/include/fontforge/gresedit.h
    /usr/local/include/fontforge/gresource.h
    /usr/local/include/fontforge/groups.h
    /usr/local/include/fontforge/gwidget.h
    /usr/local/include/fontforge/gwwiconv.h
    /usr/local/include/fontforge/import.h
    /usr/local/include/fontforge/intl.h
    /usr/local/include/fontforge/libffstamp.h
    /usr/local/include/fontforge/lookups.h
    /usr/local/include/fontforge/mm.h
    /usr/local/include/fontforge/nonlineartrans.h
    /usr/local/include/fontforge/ofl.h
    /usr/local/include/fontforge/pfaedit.h
    /usr/local/include/fontforge/PfEd.h
    /usr/local/include/fontforge/plugins.h
    /usr/local/include/fontforge/prefpage.h
    /usr/local/include/fontforge/print.h
    /usr/local/include/fontforge/psfont.h
    /usr/local/include/fontforge/savefont.h
    /usr/local/include/fontforge/scriptfuncs.h
    /usr/local/include/fontforge/scripting.h
    /usr/local/include/fontforge/sd.h
    /usr/local/include/fontforge/search.h
    /usr/local/include/fontforge/sfd1.h
    /usr/local/include/fontforge/sflayoutP.h
    /usr/local/include/fontforge/splinefont.h
    /usr/local/include/fontforge/stemdb.h
    /usr/local/include/fontforge/ttf.h
    /usr/local/include/fontforge/ttfinstrs.h
    /usr/local/include/fontforge/uiinterface.h
    /usr/local/include/fontforge/unicoderange.h
    /usr/local/include/fontforge/ustring.h
    /usr/local/include/fontforge/utype.h
    /usr/local/include/ulockmgr.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
    /usr/local/lib/libatk-1.0.la
    /usr/local/lib/libfontforge.la
    /usr/local/lib/libgdk-x11-2.0.la
    /usr/local/lib/libgdk_pixbuf-2.0.la
    /usr/local/lib/libgdk_pixbuf_xlib-2.0.la
    /usr/local/lib/libgdraw.la
    /usr/local/lib/libgio-2.0.la
    /usr/local/lib/libgioftp.la
    /usr/local/lib/libglib-2.0.la
    /usr/local/lib/libgmodule-2.0.la
    /usr/local/lib/libgobject-2.0.la
    /usr/local/lib/libgthread-2.0.la
    /usr/local/lib/libgtk-x11-2.0.la
    /usr/local/lib/libgunicode.la
    /usr/local/lib/libgutils.la
    /usr/local/lib/libintl.la
    /usr/local/lib/libjpeg.la
    /usr/local/lib/libpango-1.0.la
    /usr/local/lib/libpangocairo-1.0.la
    /usr/local/lib/libpangoft2-1.0.la
    /usr/local/lib/libpangox-1.0.la
    /usr/local/lib/libpangoxft-1.0.la
    /usr/local/lib/libportaudio.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
    /usr/local/lib/pkgconfig/fontforge.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
    /usr/local/lib/libintl.a
    /usr/local/lib/libportaudio.a
    /usr/local/lib/libz.a

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
    echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
```

This is everything.

**Comment by pizza2004** [comment]
Oh, you mean what issues did I have with Homebrew.  I guess since I'd upgraded my OS since I installed it there were just some issues getting it to run at all.  I had to do a thing where I manually used git to pull down the latest version or something.

**Comment by kkirby** [comment]
Is that the output of doctor? If so, run the following:

`sudo chown -R $(whoami) /Library/Caches/Homebrew`
`sudo chown -R $(whoami):admin /usr/local`
`brew update`
`brew upgrade`

If that isn't the output of `doctor`, can you share it?

**Comment by pizza2004** [comment]
Yeah, that's the output of doctor.  I ran all those commands and now brew won't build at all.

**Comment by kkirby** [comment]
Reinstall brew.

**Comment by pizza2004** [comment]
This is the error it is giving me actually: Error: Permission denied - /Users/chad/Library/Logs/Homebrew/libpng/01.configure

So I ran a command to try to give myself ownership of the Library folder there and that still hasn't finished.  I'm doing all this on a 4 year old iMac with a 5200RPM HDD, so it's slow.

**Comment by kkirby** [comment]
Just remove the homebrew directory using `sudo rm -rf ~/Library/Logs/Homebrew` Make sure to type the command in correctly. If not, you could really screw something up.

**Comment by pizza2004** [comment]
Okay, now it's back to giving me the same exact issue, but I don't have to use sudo to run brew anymore at least!

**Comment by kkirby** [comment]
You were using sudo for homebrew? I dunno, I'd guess your homebrew installation is messed up. I don't know how you'd go about removing everything and reinstalling homebrew. You should look it up and give it a try. I won't be able to respond for awhile now, though. Good luck!

**Comment by pizza2004** [comment]
Okay, so it all worked perfectly fine on my friends machine, so I'm not sure what the issue is.

**Comment by pizza2004** [comment]
Hooray!  I fixed it finally!  I just had to delete the zlib libraries from a folder and the whole thing ran without any issues.  Thanks for all the help!
