### ISSUE TITLE
Remove Vertical Faces doesn't properly work under water.

### ISSUE THREAD

**Issue by pizza2004** [OpenRCT2/OpenRCT2#2485]
When using the remove vertical faces option from the menu, the vertical faces are not hidden if they are directly connected to water.  Picture included.  I believe this is an original bug, forgive me if it's been reported, I couldn't find it.

<img width="1440" alt="screen shot 2015-12-13 at 7 20 31 pm" src="https://cloud.githubusercontent.com/assets/1329261/11771526/e035a452-a1ce-11e5-9c24-1079c2856e75.png">

**Comment by LRFLEW** [comment]
Just tested it, it's an Original Bug (aka, it's in the original game, not just our version).

**Comment by pizza2004** [comment]
I just noticed that when you use Underground/Inside View you can see through the vertical faces of the water and if you press v to turn vertical faces on and off you can see the land's vertical faces appearing and disappearing still.  Perhaps water shouldn't have vertical faces?  Or maybe we should add a custom vertical water face.  I think that would look nice, to see the side of the water, implying that it doesn't just abruptly end there.
