### ISSUE TITLE
[0.0.4, 1527] Created scenarios not found under scenario selection

### ISSUE THREAD

**Issue by asyagelski** [OpenRCT2/OpenRCT2#2486]
After creating a scenario and placing it in the "Other Parks" category, it doesn't show up when starting a new game. Not tested with other categories.

**Comment by e-foley** [comment]
I can't reproduce this in build 1527... Are you sure you're writing something under "Scenario name" when you set the objective in the editor?

**Comment by asyagelski** [comment]
Sure am! I fill out the fields, select the objective and it won't save it.

**Comment by LRFLEW** [comment]
What OS are you running? This could be a platform-specific bug.

**Comment by asyagelski** [comment]
I'm running Windows 7 Home I believe. This was on my laptop. I tried the
exact same thing for my desktop and it wouldn't work either.

**Comment by IntelOrca** [comment]
It has probably saved the scenario in a compatibility directory.

**Comment by Gymnasiast** [comment]
I think @IntelOrca is right... have you tried to take ownership of your RCT2 folder and its subfolders (especially Scenarios and Tracks)?

**Comment by asyagelski** [comment]
I'm not sure if that's the problem.

I remade the scenario and saved it under "Real Parks" and it showed up. It
didn't when saved under "Other Parks".

**Comment by Horsti12** [comment]
I think this can be closed. Since other people not have the problem and this issue is more than 14 months old.
