### ISSUE TITLE
Snap Shops to Path

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#2493]
Automatically rotate shops to face paths automatically.

**Comment by e-foley** [comment]
And then information kiosks rotate wildly out of control and soar off into the heavens.

But actually, I would find this useful if it were an option.  There are definitely times where I want to build shops before paths but far more where I build the path first.

**Comment by vzybilly** [comment]
I know I would like this, I build eating runways, three wide paths with a
hole every other center to stop peeps from being derpy, also to give seats
and trashcans, but there are many times where I'm placing down 20+ shops
and I go back and forth on the sides which means for each shop I have to
rotate twice... worse if I double click...

**Comment by pizza2004** [comment]
I also support this feature, as long as it's optional, although I think it would be nice as a button toggle on the building interface rather than an option in the menu, and it wouldn't need to be stored in the config files.  This would also be nice for signs on paths and stuff like that.

**Comment by IntelOrca** [comment]
@PFCKrutonium You have duplicated your own feature request. #1675

**Comment by PFCKrutonium** [comment]
Shit, I didn't realise I already had. Sorry!

**Comment by vzybilly** [comment]
lol, side note, why haven't we gotten to this yet? I don't think it would
be *that* hard but I'm on email so I can't easily look at the other...
