### ISSUE TITLE
Use SI units for speed

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#2496]
Source:
https://www.reddit.com/r/openrct2/comments/3wsykn/is_there_an_option_to_show_speeds_in_ms/

Add another option to show speed in metres per second (m/s) alongside mph and kp/h.

**Comment by IntelOrca** [comment]
**A nice fast integer approximation:**
```m/s = (mph * 58594) << 17```

**Comment by PFCKrutonium** [comment]
Would it not be simpler to calculate m/s from km/h?

**Comment by Gymnasiast** [comment]
km/h is calculated from mph, so that would require two calculations. (Not to mention you have to divide km/h by 3.6 to get m/s.)

**Comment by IntelOrca** [comment]
Velocity seems to be internally stored as a factor of MPH. So converting to km/h first and then m/s would be two calculations as @Gymnasiast said which would been even less accurate.

**Comment by PFCKrutonium** [comment]
Fair enough - I assumed they were more separate on some level. Ignore me :+1:

**Comment by janisozaur** [comment]
> `m/s = (mph * 58594) >> 17`

Nice! The error is so small it's not noticeable.
