### ISSUE TITLE
Freeform path direction doesn't update when isometric angle is changed

### ISSUE THREAD

**Issue by joflashstudios** [OpenRCT2/OpenRCT2#2502]
![scr25](https://cloud.githubusercontent.com/assets/7459309/11844077/175aa5be-a40d-11e5-9eea-37f02b9bff68.png)

Rotated once yields this:

![scr26](https://cloud.githubusercontent.com/assets/7459309/11844080/1fb9e760-a40d-11e5-90f2-26bf62afc1f7.png)

**Comment by IntelOrca** [comment]
Did this used to change in vanilla?

**Comment by Gymnasiast** [comment]
Yes. 
(But even if it didn't, it would have been a bug we should solve, so not that important.)

**Comment by IntelOrca** [comment]
Then why is it a bug?
