### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by ptkato** [OpenRCT2/OpenRCT2#2504]
I dunno how to fix it, but I'm almost certain that this problem is in my end. Take a look:

    make
    [  1%] Building C object CMakeFiles/openrct2.dir/src/hook.c.o
    /home/ptkato/Documents/repositories/OpenRCT2/src/hook.c:24:23: fatal error: sys/mman.h: No such file or directory
      #include <sys/mman.h>
                           ^
    compilation terminated.
    CMakeFiles/openrct2.dir/build.make:54: recipe for target 'CMakeFiles/openrct2.dir/src/hook.c.o' failed
    make[2]: *** [CMakeFiles/openrct2.dir/src/hook.c.o] Error 1
    CMakeFiles/Makefile2:91: recipe for target 'CMakeFiles/openrct2.dir/all' failed
    make[1]: *** [CMakeFiles/openrct2.dir/all] Error 2
    Makefile:76: recipe for target 'all' failed
    make: *** [all] Error 2

I would like that someone to throw a light at it and lead the path to the solution.
I'm using Debian Jessie, by the way.

**Comment by Gymnasiast** [comment]
Did you make sure to install build-essential and all other build dependencies?

**Comment by ptkato** [comment]
Yeah, I think so.

**Comment by ptkato** [comment]
Yeah, I think so. Is there any problem in compiling with g++?

**Comment by janisozaur** [comment]
You haven't installed `gcc-multilib`

**Comment by ptkato** [comment]
You were right. I've installed the `gcc-multilib` and it went fine until 95%, then another error was thrown:

    [ 95%] Building CXX object CMakeFiles/openrct2.dir/src/localisation/LanguagePack.cpp.o
    In file included from /home/ptkato/Documents/repositories/OpenRCT2/src/localisation/../core/Exception.hpp:3:0,
                     from /home/ptkato/Documents/repositories/OpenRCT2/src/localisation/../core/IStream.hpp:4,
                     from /home/ptkato/Documents/repositories/OpenRCT2/src/localisation/../core/FileStream.hpp:5,
                     from /home/ptkato/Documents/repositories/OpenRCT2/src/localisation/LanguagePack.cpp:8:
    /usr/include/c++/4.9/exception:37:28: fatal error: bits/c++config.h: No such file or directory
     #include <bits/c++config.h>
                                ^
    compilation terminated.
    CMakeFiles/openrct2.dir/build.make:3596: recipe for target 'CMakeFiles/openrct2.dir/src/localisation/LanguagePack.cpp.o' failed
    make[2]: *** [CMakeFiles/openrct2.dir/src/localisation/LanguagePack.cpp.o] Error 1
    CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/openrct2.dir/all' failed
    make[1]: *** [CMakeFiles/openrct2.dir/all] Error 2
    Makefile:76: recipe for target 'all' failed
    make: *** [all] Error 2

I'm trying to compile the branch master.

**Comment by janisozaur** [comment]
now you're missing `g++-multilib`. Please just follow the setup guide I linked in previous post.

**Comment by ptkato** [comment]
Ok, I did through that guide several times and now I got other error and I don't think it's about missing packages (because I've installed everything in that guide).

    [ 96%] Building CXX object CMakeFiles/openrct2.dir/src/network/http.cpp.o
    In file included from /usr/include/curl/curl.h:35:0,
                     from /home/ptkato/Documents/repositories/OpenRCT2/src/network/http.cpp:17:
    /usr/include/curl/curlrules.h:143:41: error: size of array ‘__curl_rule_01__’ is negative
         [CurlchkszEQ(long, CURL_SIZEOF_LONG)];
                                             ^
    /usr/include/curl/curlrules.h:153:53: error: size of array ‘__curl_rule_02__’ is negative
         [CurlchkszEQ(curl_off_t, CURL_SIZEOF_CURL_OFF_T)];
                                                         ^
    CMakeFiles/openrct2.dir/build.make:3665: recipe for target 'CMakeFiles/openrct2.dir/src/network/http.cpp.o' failed
    make[2]: *** [CMakeFiles/openrct2.dir/src/network/http.cpp.o] Error 1
    CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/openrct2.dir/all' failed
    make[1]: *** [CMakeFiles/openrct2.dir/all] Error 2
    Makefile:76: recipe for target 'all' failed
    make: *** [all] Error 2

I appreciate you guys help until now.

**Comment by janisozaur** [comment]
There are few conflicting version of `curl-dev` package, at least on ubuntu. You probably have the wrong one.

Consult what travis does: https://github.com/OpenRCT2/OpenRCT2/blob/develop/install.sh#L170

If you find that the package name is wrong please update the wiki page.

**Comment by Lucki** [comment]
As a workaround you can disable the causing Twitch integration with `cmake -DDISABLE_HTTP_TWITCH=On $other_cmake_options` as described here: https://www.holarse-linuxgaming.de/wiki/openrct2

**Comment by janisozaur** [comment]
I have set up a temporary PPA, which you can use to get `openrct2` without needing to compile. https://code.launchpad.net/~janisozaur/+archive/ubuntu/rct2-deb

This will (hopefully) eventually get replaced with the real deal, but should be good enough for now. To use it, download the latest Linux release, extract `data/*` to `/usr/share/openrct2/` (so that there is `/usr/share/openrct2/g2.dat`) and it should all work.

**Comment by janisozaur** [comment]
It's set up to build automatically, so it should have a new build or two every day, provided there are new commits.

I'd really like you to test it, as I don't use debian and could use some feedback.

**Comment by vzybilly** [comment]
I'll see if I can test it about 12 hours from now... if I remember...

**Comment by janisozaur** [comment]
@ptkato is it still a problem? Can you close this issue now?

**Comment by ptkato** [comment]
Yes you can.
