### ISSUE TITLE
Garbage cans get full to fast.

### ISSUE THREAD

**Issue by remcooo96** [OpenRCT2/OpenRCT2#2511]
In openrct gargage cans are full after one piece of trash. So your paths will be lithered with trash.

**Comment by duncanspumpkin** [comment]
They get full after three pieces and there is also a rand in there as well so it should take about 5 pieces on average. Vanilla  rct2 had a bug preventing bins from filling at all.

**Comment by remcooo96** [comment]
Is 5 pieces per garbage can not extremely low? The average can is full in just 3 minutes. Maybe a way to extend this to 10 to 20 pieces? Much more realistic

**Comment by AaronVanGeffen** [comment]
This is a duplicate of #1860.

**Comment by remcooo96** [comment]
Thanks, but still no solution. Just because of this reason I am playing vanilla now.

**Comment by Gymnasiast** [comment]
As this is a duplicate of #1860, please move the discussion to there.
