### ISSUE TITLE
Mechanics get lost-ish

### ISSUE THREAD

**Issue by kkirby** [OpenRCT2/OpenRCT2#2514]
Mechanics fail to respond to broken down rides because they never make it to the ride, because they walk in circles. I've attached a video of the issue and an image of my path layout. I think this may be associated to #2499.

![](http://i.imgur.com/AnHKBE5.jpg)
[Video (Bad quality)](https://youtu.be/mn_ufrJeO1Q) [Original (Less bad, still bad)](https://mega.nz/#!INckxBYZ!hWoKVKmOnJKFXKsj7Bf9ghgy4OjTEnZhDnmtrkqaidc)

Platform: OS X
Version: Develop pulled last night

**Comment by janisozaur** [comment]
For reporting issues, can you rather embed images and share videos via YouTube/gfycat or some such? Keep in mind transfer.sh will purge the files after two weeks.

**Comment by janisozaur** [comment]
#2586 could be related.

**Comment by duncanspumpkin** [comment]
Probably fixed now.
