### ISSUE TITLE
Cheats do not synchronise in Multiplayer

### ISSUE THREAD

**Issue by oslerw** [OpenRCT2/OpenRCT2#2517]
When clicking the +5k cash button in the cheats menu, other players don't see the increase in money. Server is hosted locally by me, with a client connected over LAN.

Running stable 0.0.3 from https://openrct2.com/download

**Comment by PFCKrutonium** [comment]
None of the Cheats currently work in Multiplayer.

**Comment by Gymnasiast** [comment]
I think we should disable the entire cheats window and menu for multiplayer. This is not the first time this has been reported.

**Comment by oslerw** [comment]
What work would need to be done to make cheats multiplayer aware? I wasn't aware that they weren't supported, so I think disabling the menu or at least having a warning would be beneficial.

**Comment by IntelOrca** [comment]
@oslerw Given the number of cheats there are, it would be a lot of work to write multiplayer commands for them all. And I think its best to wait for that area to be "re-done" in a way that's easier to add more.

**Comment by vzybilly** [comment]
why not wrap all the cheats with a wrapper function that just calls the
cheats function, unless on multi, then it tells all clients and then calls
the function itself... making it like all the people did it at the same
time, effectively making it compatible with multi...

**Comment by Gymnasiast** [comment]
@vzybilly : Please read IntelOrca's comment. He just explained exactly why we can't "just" do that. (It's not the first time you have commented without understanding the technical side it.)

**Comment by pizza2004** [comment]
Why rewrite all the cheats to work for multiplayer when many of them should just work on multiplayer when things like money are properly synchronized later on.  I can imagine a few would need to be dealt with though, perhaps, like the checkboxes, depending on whether it matters if both players need to have it enabled if one person does.

**Comment by Gymnasiast** [comment]
@pizza2004 : Sigh... please let the actual coders do the explaining and implementing. You probably have good intentions with your comments, but they are not very helpful.

**Comment by IntelOrca** [comment]
@pizza2004 Money is not synchronised later on. Multiplayer works by clients sending all their actions to the server and waiting for the server to acknowledge and validate that action before performing it on the client at the same game tick as on the server. Right now all the cheats are just blocks of logic which are performed on button events - this would need to be completely changed to a mapping from command id to logic block using the same game command interface as the rest of the game.

**Comment by pizza2004** [comment]
Hmm, I guess that's probably the most effective way to handle multiplayer, but I still feel like there should probably be occasional checks of things to make sure they aren't somehow getting out of sync.

**Comment by duncanspumpkin** [comment]
@pizza2004 your suggestion would cause way more subtle issues/sync problems. The current setup makes it way more easy to notice issues because the problems manifest themselves so obviously.

**Comment by IntelOrca** [comment]
@pizza2004 There are! That is how it checks that there is a desynchronisation.

**Comment by pizza2004** [comment]
@IntelOrca Ah, okay, good!  I knew things were sent back and forth, but didn't know everything was run in game commands, so I figured things were synchronized at a different level.  Anyway, yeah, the cheats don't seem like a high priority for multiplayer when all of the guests and staff and money still desynchronizes constantly.
