### ISSUE TITLE
Translations are not applied on scenario editor

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#2522]
Translations are not applied on scenario editor, precisely object selection window.

**Comment by Gymnasiast** [comment]
Remove plugin.dat and restart OpenRCT2.

**Comment by telk5093** [comment]
Thank you and sorry :)

**Comment by AaronVanGeffen** [comment]
We get this question every so-and-so often, though. Maybe a notice should be added when changing languages? Or indeed, the choice to rebuild the cache when doing so. I appreciate it takes some time, so best not do it by default.

**Comment by telk5093** [comment]
I didn't realized there is Wiki page on Localization project.
It will be great that some FAQs or Wiki links are written in the very first page of the localization project.

**Comment by Gymnasiast** [comment]
@AaronVanGeffen : Sure, it's still a bug we need to fix. I even opened the issue for it: #1004. Not sure how easy that would be with all localisation changes we have had.

**Comment by Gymnasiast** [comment]
@telk5093 : It's not something specific for the Localisation repo, it's a bug on OpenRCT2 itself, which should simply be fixed. Removing plugin.dat is a workaround.

**Comment by Gymnasiast** [comment]
Closing as this bug is already reported as #1004.
