### ISSUE TITLE
Decimal point not displayed when using SI units

### ISSUE THREAD

**Issue by e-foley** [OpenRCT2/OpenRCT2#2523]
Decimal points aren't displayed in speeds when choosing SI units.  This must be related to the alterations in #2521.

I used build v0.0.4 b1553 on Windows 10, based off the GOG Triple Thrill Pack version of the game.

![fast_chairlift](https://cloud.githubusercontent.com/assets/6338134/11919834/cd30ca10-a711-11e5-8013-157fdf6409f9.png)

![fast_logs](https://cloud.githubusercontent.com/assets/6338134/11919836/d0f46454-a711-11e5-97b9-e63e094b509e.png)

I'm not sure why the PR would have been merged if it had obvious bugs; is it possible there's some platform-dependent behavior going on?

**Comment by Gymnasiast** [comment]
Is your game set to US English?

**Comment by e-foley** [comment]
Yes.  I see now that some languages place a decimal point while others do not.

**Comment by Gymnasiast** [comment]
Because US English has not been updated yet. Not an issue with the PR itself.

You should _always_ set the game to UK English first before submitting interface bugs like this one.

**Comment by e-foley** [comment]
OK, I'll do that moving forward.  Nederlands is the other language that doesn't currently have a decimal point.

**Comment by IntelOrca** [comment]
When SI was added, languages were updated to add the new string, but not all of them. When the decimal point was added, those languages haven't been updated and therefore use the old format, whilst the languages that were never updated in the first place fall back to English UK.

**Comment by Gymnasiast** [comment]
It was indeed only US English and Nederlands that were updated the day after the feature was first introduced, as I maintain those. The other languages fell back to UK English.

I actually updated NL tonight - a few minutes before I saw your issue, and had updating US English already planned.

**Comment by e-foley** [comment]
Thank you.  I now better understand how the language options affect the interface.
