### ISSUE TITLE
Launch speeds are allowed to exceed 255 mph when the appropriate cheat is selected

### ISSUE THREAD

**Issue by e-foley** [OpenRCT2/OpenRCT2#2524]
Build 1553. I can set this reverse freefall to use a launch speed way above the 255 mph implied by the cheat.  Other rides with a similar setting are affected the same way.

![whoa_belly](https://cloud.githubusercontent.com/assets/6338134/11919867/90d4f0a4-a712-11e5-8b54-18db7add69a8.png)

**Comment by Gymnasiast** [comment]
Was a matter of a dodgy description. The cheat allows the player to set the value all the way up to the internal value of 255, which is multiplied for the launch speed calcution. #2525 features an updated description for the cheat.
