### ISSUE TITLE
Time overflow when unlocking dodgems' operating limits

### ISSUE THREAD

**Issue by e-foley** [OpenRCT2/OpenRCT2#2529]
Build 1554.  If you unlock operating limits via cheats and change the ride time for the dodgems, the time will overflow upon exceeding 4:10 minutes.  If while this limit is exceeded you uncheck "unlock operating limits," you can't restore the time back to its proper range.

![dodgems_1](https://cloud.githubusercontent.com/assets/6338134/11921394/387352c2-a73d-11e5-881c-23c46d686dfc.png)

(Increase the time one more step...)

![dodgems_2](https://cloud.githubusercontent.com/assets/6338134/11921407/479ab27c-a73d-11e5-86f0-6e13e9e28d9f.png)

**Comment by Gymnasiast** [comment]
The spinner still seems to work correctly, but there seems to be an overflow with the formatting of the string.
