### ISSUE TITLE
Client crashes when building new Rides

### ISSUE THREAD

**Issue by Lucki** [OpenRCT2/OpenRCT2#2536]
There's a problem with distributing track designs over the network system.
When trying to build a new ride, the client which wants to build the ride crashes. Other clients and the server freeze in this time until the crashing client disconnects. This happens with every ride you can have/save/use a template.
Editing existing rides works without problems.

I'm on Archlinux, everything up to date. Last rebuild of openrct2 was at 8b9c4d1.
This also happens with other clients/servers on Ubuntu and Gentoo.

There's no terminal output at the server.
This is the terminal output of the crashing client:
~~~
ERROR[/home/lucki/yaourt/yaourt-tmp-lucki/aur-openrct2-git/src/openrct2-git/src/ride/track.c:545 (load_track_design)]: Track checksum failed.
ERROR[/home/lucki/yaourt/yaourt-tmp-lucki/aur-openrct2-git/src/openrct2-git/src/ride/track.c:2282 (track_get_info)]: Failed to load track:
~~~

**Comment by janisozaur** [comment]
Isn't it "we don't support track designs in multiplayer" bug?

**Comment by PFCKrutonium** [comment]
@janisozaur Yes

**Comment by Gymnasiast** [comment]
I thought track designs were not available at all in multiplayer? How can the OP have gotten this problem?

**Comment by IntelOrca** [comment]
@Lucki Could you describe the problem more clearly? Perhaps with a video or screenshot.

**Comment by Lucki** [comment]
@IntelOrca Video: https://youtu.be/49Sr_dMfBgw

Steps to reproduce:
* Start server
* Connect client
* Try to build a ride

**Comment by IntelOrca** [comment]
@Lucki thanks - that doesn't crash for Windows, but it does look like its not doing something right. I think I will make it bypass the design window altogether.
