### ISSUE TITLE
Cannot launch game (ObjectsData checksum issues)

### ISSUE THREAD

**Issue by WyRe** [OpenRCT2/OpenRCT2#2545]
Hi guys! I'm trying to play in Archlinux with a retail from steam, well, I've followed your instructions from:

https://github.com/OpenRCT2/OpenRCT2/wiki/Installation-on-Linux 

I've specify the right path to the downloaded folders and files from Steam (in game path inside 'config.ini', even also making symlinks of those folders to /usr/share/openrct2) but I'm getting errors with all files of ObjData folder, like this:

`............`
`..............................`
`............................................`
`ERROR[/home/wyre/AUR/openrct2/src/OpenRCT2-0.0.3.1/src/object.c:100 (object_load_file)]: Object Load failed due to checksum failure.`
`ERROR[/home/wyre/AUR/openrct2/src/OpenRCT2-0.0.3.1/src/object_list.c:743 (install_object_entry)]: Object Load File failed. Potentially corrupt file: STEEP2  `
`ERROR[/home/wyre/AUR/openrct2/src/OpenRCT2-0.0.3.1/src/util/sawyercoding.c:105 (sawyercoding_read_chunk)]: Unable to read chunk data!`
`ERROR[/home/wyre/AUR/openrct2/src/OpenRCT2-0.0.3.1/src/object.c:100 (object_load_file)]: Object Load failed due to checksum failure.`
`ERROR[/home/wyre/AUR/openrct2/src/OpenRCT2-0.0.3.1/src/object_list.c:743 (install_object_entry)]: Object Load File failed. Potentially corrupt file: STEX1   `
`ERROR[/home/wyre/AUR/openrct2/src/OpenRCT2-0.0.3.1/src/util/sawyercoding.c:105 (sawyercoding_read_chunk)]: Unable to read chunk data!`
`ERROR[/home/wyre/AUR/openrct2/src/OpenRCT2-0.0.3.1/src/object.c:100 (object_load_file)]: Object Load failed due to checksum failure.`
`ERROR[/home/wyre/AUR/openrct2/src/OpenRCT2-0.0.3.1/src/object_list.c:743 (install_object_entry)]: Object Load File failed. Potentially corrupt file: STEX10  `
`Violación de segmento (`core' generado) `

Someone has an idea what could be happening? It seems a issue with the checksums but how could I change the checksum of all of these files at the same time? As I'm on Archlinux I've installed openrct2 from AUR repositories:

https://aur.archlinux.org/packages/openrct2/

(with git version either works)

**Comment by janisozaur** [comment]
Your files seem broken, try redownloading them.

**Comment by WyRe** [comment]
Well... I think that I've downloaded the files properly; I have got these files in 
/home/wyre/.local/share/Steam/ubuntu12_32/steamapps/content/app_285330/depot_285331

![captura de pantalla de 2015-12-23 16-32-01](https://cloud.githubusercontent.com/assets/4059108/11979361/fe2c6a9c-a992-11e5-8739-bdffee7fce05.png)
I don't know if could I use these 

Data -> RCT2/Data
ObjData -> RCT2/ObjData
Scenarios -> RCT2/Scenarios
Tracks -> RCT2/Tracks
Landscapes -> RCT2/Landscapes 

Or should I install the Steam retail from that Install folder (where is located the setup.exe) and get from that installation these folders. Maybe could be why I'm using directly the Data, ObjData, Scenarios, etc, folders from just Steam client download?

**Comment by WyRe** [comment]
I'm ... I have reinstall the game from my Windows 7 partition (with setup.exe inside Install folder) to get from there these folders and now OpenRCT2 run properly, the most strange thing has been what Wine doesn't run setup.exe (even from PlayOnLinux) I cannot get an wine install of RCT2 ... So strange :( 

Nice adaptation of this fine game ;) I hope an OpenRCT3 in a future! :P

**Comment by PFCKrutonium** [comment]
I don't think OpenRCT3 is going to happen - the licence for it would disallow what we are doing. Have a good day!

**Comment by WyRe** [comment]
@PFCKrutonium u cannot use the official game data? :S It's a pity ... Maybe you could ask to Atari specifically xD
