### ISSUE TITLE
Program crashes when executing "exit" command from the console

### ISSUE THREAD

**Issue by ecnepsnai** [OpenRCT2/OpenRCT2#2550]
This might be intentional, but in build 1573 running the "exit" command from the console will cause the game to crash.  Attaching a debugger will show that [this line](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/interface/console.c#L1061) causes an uncaught exception so the return code for the program is negative.

**Comment by IntelOrca** [comment]
It is because of https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/interface/console.c#L1049
it will end up freeing a constant string.

**Comment by ecnepsnai** [comment]
So what is the intended action of the "exit" and "quit" action?  Because this makes it seems like it just closes the console.

```
// Aliases for hiding the console
	if(strcmp(argv[0],"quit") == 0 || strcmp(argv[0],"exit") == 0)
```

**Comment by IntelOrca** [comment]
They are just meant to be aliases, because there was for some reason a big issue with people not being able to close the console.

**Comment by Gymnasiast** [comment]
Also, they did work correctly when introduced, but some time ago changes were made to how OpenRCT2 handles argv and apparently it wasn't tested at the time.
