### ISSUE TITLE
Automatically Pause When No Clients Are Connected

### ISSUE THREAD

**Issue by pizza2004** [OpenRCT2/OpenRCT2#2552]
It would be great if there was some way to set the server so it paused when nobody was around.  I might look at the code later on to see if I can figure out how to do it myself, but I just thought I'd make an issue to see what other people think of the idea.

**Comment by Patrik356b** [comment]
+1

**Comment by Jargonius** [comment]
I was just thinking this would be awesome the other day!

**Comment by TycoonParadise** [comment]
Huge interest in this issue. Currently all 3 server we are hosting pull a constant 30% CPU, regardless if 15 people are connected, or none are. Resource consumption is the biggest concern in regards to this.
-Sweet T

**Comment by IntelOrca** [comment]
@TycoonParadise are these headless servers?

**Comment by TycoonParadise** [comment]
@IntelOrca Yes, all 3 headless, 30% out of 2 virtual CPUs @ 3.3GHz.

**Comment by tobiaskohlbau** [comment]
Solved by #6838
