### ISSUE TITLE
Password config on dedicated server

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#2554]
It needs the password config when opening dedicated(headless) server but I couldn't find it in config.ini.
It will be great to set up the password automatically when opening the headless server to prevent the terror on the map, or to avoiding foreigners.

ps. do you realize the recent builds are all failed?

**Comment by pizza2004** [comment]
They know about the failed builds, the build servers have to be updated.  Does it automatically advertise on a headless server then?  It should be possible to set both settings when launching a headless server, perhaps -password= and -advertise.

**Comment by telk5093** [comment]
I tried on the command window by typing this:
openrct2 --headless --password=test "(savefile path)"

But it returns "error: unknown option `--password=test`".
Single hyphen returns the same error.

Did I wrong?

**Comment by pizza2004** [comment]
Oh sorry, I didn't mean it was implemented, I was trying to say that it /should/ be possible, not that it is already.  I could have worded that better I suppose.

**Comment by telk5093** [comment]
I see. I'm sorry too because of the lack of my english ;)
I agree with your idea!

**Comment by janisozaur** [comment]
This issue should also cover joining a passworded server from cmdline.

**Comment by IntelOrca** [comment]
This has been implemented.

**Comment by masterxq** [comment]
I want to advertise my dedicated server.
Is this implemented? If can you tell me how?
Thanks for your great work!

**Comment by masterxq** [comment]
Its possible in the config.ini. This should be fine.
Sorry.
