### ISSUE TITLE
Game crash with lots of stacked peeps

### ISSUE THREAD

**Issue by jensj12** [OpenRCT2/OpenRCT2#2558]
To reproduce:
1. Open Community park V2.35 (from forum)
2. Look for the stacked peeps on one of the map sides (you'll notice some graphical glitches around them)
3. Enable sandbox mode
4. Set the map rotation as in the image (might not be needed, not sure)
5. Open the map and select set guest entry points
6. Fully zoom out with mouse wheel (It should crash now)
7. If it doesn't crash yet, zoom in and out a few times until it crashes.
I had it crash 3 times in a row doing it this way.
[Imgur](http://i.imgur.com/7KNBLzg.png)

**Comment by janisozaur** [comment]
Link to park, please?

**Comment by janisozaur** [comment]
@jensj12 can you please check if the dll from this build solves this problem for you: https://ci.appveyor.com/project/IntelOrca/openrct2-ject9/build/0.0.4.73/artifacts
