### ISSUE TITLE
Currency rates

### ISSUE THREAD

**Issue by Aroidzap** [OpenRCT2/OpenRCT2#2567]
Currency rates are now wrong:

now it is | should be | change in percent
--- | --- | ---
1 GBP == $1 | 1 GBP == $1.5 | +50%
1 GBP == 1 F | 1 GBP == 1.5 F | +50%
1 GBP == DM 1 | 1 GBP == DM 2.6 | +160%
1 GBP == 100 YEN | 1 GBP == 178.4 YEN | +78.4%
1 GBP == 1 Pts | 1 GBP == 224.9 Pts | +22390%
1 GBP == L 100 | 1 GBP == L 4.3 | -95.7%
1 GBP == fl. 1 | 1 GBP == fl. 3 | +200%
1 GBP == 1 kr. | 1 GBP == 12.5 kr. | +1150%
1 GBP == 1 EUR | 1 GBP == 1.4 EUR | +40%
1 GBP == W 1000 | 1 GBP == W 1727.4 | +72.74%
1 GBP == R 100 | 1 GBP == R 104.8 | +4.8%
1 GBP == 10 Kč | 1 GBP == 36.5 Kč | +265%

It is no problem to fix it, but question is, if it really should be fixed. So please tell what you think about it.

**Comment by HaasJona** [comment]
I'm not 100% sure but I guess the game only supports powers of 10 for the exchange factor. Which makes sense because you should get "round" values in other currencies. And the prices are relatively unrealistic anyway.

I think it would be okay to change Pts, L and kr. to the best matching power of 10 though.

**Comment by AaronVanGeffen** [comment]
To be honest, considering the values of the money in-game are already far from realistic, I doubt we really need to change it.

**Comment by IntelOrca** [comment]
They are the same as the original game for original currencies. They are deliberately only multiplied by powers of 10 to keep consistent rounding. Otherwise increasing prices on rides etc. would up by strange fractions.

**Comment by Aroidzap** [comment]
I'm from Czech Republic and if I fix currency rate (+256%), prices are a lot more realistic. I would vote for fixing this.

**Comment by IntelOrca** [comment]
Currencies can only be changed in factors of 10 for the reason I just said.

**Comment by Aroidzap** [comment]
but it's just weird :/ leaving it this way

**Comment by Aroidzap** [comment]
I don't care abou strange fractions. I think it is better to have weird fraction and more real price than fractions in power of 10.

If i want power 10 fractions, I will select GBP (don't care about price, care about fractions).
Otherwise I can select CZK (care about price, don't care about fractions).

**Comment by jensj12** [comment]
Wouldn't it be possible to multiply with any int number?
I'd vote for not changing any current currencies but adding 'Custom' in the currency list, which just gives an input box for the symbol and multiplier. Not something I'd use myself, as EUR is already realistic enough most of the time.

**Comment by HaasJona** [comment]
The prices won't get realistic even if you choose the correct exchange rate, so I don't really see the point. Also as I said, the formatting functions currently don't work properly for "weird" fractions. For example having an exchange rate of 1€ = 3GBP (which is incorrect, but just for demonstration) will result in 3 GBP values being displayed as the same € price and the game won't display cents automatically for that.

**Comment by Aroidzap** [comment]
Prices are not real, but are real at least for products in stalls and 300% change in price of hotdog or drink is significant.

**Comment by Aroidzap** [comment]
as @jensj12 said "EUR is already realistic enough most of the time." So if there will be no fix, noone will use other currencies and then they are redundant. So than tell me, why there was some currencies added to the game, at least Czech koruna I think. This make no sence and maybe non original currencies should be removed if not fixed.

**Comment by vzybilly** [comment]
the way I see it, if we fix this then fixing the price for everything in
the park would become more needed... under the argument of, "you fixed
that, why not finish the job? " kinda thing...

if we did fix it, I could see maybe adding in online updating that falls
back to most recent if it can't update. it would also keep the exchange
rates in a plain text file so people can "fix it " themselves...

I'd be OK with ditching all currency and just using a made up currency...
to me that sounds better than correct prices for stalls but wrong for
everything else...

**Comment by Aroidzap** [comment]
"RCT" currency is a good idea... but maybe lot of players will be angry for historic reasons. I think it was bad idea to touch this issue :D

**Comment by e-foley** [comment]
I agree with changing the conversion factor for Pts and kr. since they're the the only two currencies better represented by a new power of 10.  I would leave the others alone.

**Comment by telk5093** [comment]
I think that adding the "RCT currency" is a good idea, not replacing current existing currencies, like Simoleon in Simcity. Maybe players who prefer to use their own currency will not be angry if we just 'add' a new own RCT currency.

**Comment by Gymnasiast** [comment]
@telk5093 : I plan to introduce an option that allows players to define their own currency, including a custom exchange rate and sign.

**Comment by telk5093** [comment]
@Gymnasiast That's great XD

**Comment by Nubbie** [comment]
Might be fixed in #3952

**Comment by Gymnasiast** [comment]
@Nubbie It is, thanks.
