### ISSUE TITLE
Can not run with nvidia graphics instead of integrated

### ISSUE THREAD

**Issue by goto3** [OpenRCT2/OpenRCT2#2572]
With any release I can not run the game with my high performance nvidia graphics instead of integrated Intel.
Of course I am running it on a laptop.
I tried changing settings on nvidia control panel and nothing worked.
Great work from devs, This is my favourite game and this project is so important to me.
Thanks to all of you <3

**Comment by IntelOrca** [comment]
I can run with my laptop's dedicated nvidia card. Can you provide more information about what is failing?

Also, the using the dedicated graphics card will not improve the performance that much. All the rendering is software rendered.

**Comment by goto3** [comment]
I get 120 fps+ on quiet zones but 40 fps- on crowded zones. I don't know where is the problem, how to activate the dedicated graphics. Other games I change it on nvidia control panel but with openrct2 it does not work.
When you play the game, does it appears the nvidia try icon the openrct2.exe?
![sdsd](https://cloud.githubusercontent.com/assets/16456164/12012695/bc0fbf38-acdf-11e5-83b0-f09c7f177e91.png)

**Comment by IntelOrca** [comment]
It might do if you enable hardware display... But the only way of improving the performance on crowded areas is to use a processor with a faster clock speed.

**Comment by goto3** [comment]
:O it does but the performance decreases on low crowded areas :O mmmmmh so I have no chance on increase my fps with this laptop :( thanks for your help this project is amazing

Thanks again

**Comment by goto3** [comment]
My game crashes when I disable hardware display btw

**Comment by IntelOrca** [comment]
You won't have much chance improving performance altogether. The drawing implementation is severely limited.
