### ISSUE TITLE
Some things I find weird

### ISSUE THREAD

**Issue by goto3** [OpenRCT2/OpenRCT2#2574]
Why do benches breaks so much often? I realized I need a lot of security crew on my parks. This was less than half often on stock game. I've never put security on stock game. Even the trash bin gets broken really fast.

Another thing is that people tend to mess up the floor (vomit) with a higher rate.

These changes makes the objectives so much harder. I can't get a park with 2000 guests in less than 4 years even with marketing.
I've tryed to decorate more and not wasting money on useless attractions but it did not help.
I need a lot of handymen and security guard and that makes it so hard to make money.

On parks with free rides it is so hard to make money... I leave a savegame:
[Factory Capers.zip](https://github.com/OpenRCT2/OpenRCT2/files/72891/Factory.Capers.zip)

Another thing is that sometimes guests don't gain happiness when riding an attraction like a roller coaster, I've tested it with unhappy guests.

Thanks

**Comment by Gymnasiast** [comment]
I can't reproduce this, really. I'd need some hard evidence to believe this really is a bug, and not down to other factors.
