### ISSUE TITLE
Interest rate bugs

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#2577]
![image](https://cloud.githubusercontent.com/assets/10726524/12019748/b58e6938-adb7-11e5-8100-dc498b93fcc6.png)

#1.
It is possible to set a negative(precisely -1%) interest rate at Scenario editor.
And the loan interest gets positive, not negative.

#2.
Also, if you raise annual interest rate in Scenario options in debug menu, it is impossible to lower it.

**Comment by IntelOrca** [comment]
I can't reproduce the second issue.

**Comment by telk5093** [comment]
![image](https://cloud.githubusercontent.com/assets/10726524/12023308/90f73590-addb-11e5-9a83-ea7ad1f27622.png)

I think some certain savefile does. I cannot reproduce that in a new map, too.
I tested the saved file during multiplay.
Some saved game allows negative annual interests, and some disallows more than 0%.

I have also no idea where this issue occurs.

**Comment by IntelOrca** [comment]
Can you upload the save file?

**Comment by telk5093** [comment]
http://file.telk.kr/rct/misc/multi1_1.sv6
http://file.telk.kr/rct/misc/multi1_2.sv6
http://file.telk.kr/rct/misc/multi1_3.sv6
http://file.telk.kr/rct/misc/multi1_4.sv6

Here

**Comment by IntelOrca** [comment]
Thanks.

**Comment by telk5093** [comment]
Great. Thanks for fixes.
