### ISSUE TITLE
Chain lift doesn't restart6

### ISSUE THREAD

**Issue by a-can-o-beans** [OpenRCT2/OpenRCT2#2601]
I was playing openrct2 last night and messed with the "force breakdown" features. After forcing a safety cut-out on a coaster the train stops on the lift ( this is normal ) but after manually fixing the ride the lift doesnt restart.

**Comment by IntelOrca** [comment]
You do not need to create a new issue just because of a typo, you can edit the title and all your comments.

**Comment by a-can-o-beans** [comment]
My mistake..just created an account to report an issue and couldn't find an edit function. Sorry about that
