### ISSUE TITLE
Chain lift doesn't restart

### ISSUE THREAD

**Issue by a-can-o-beans** [OpenRCT2/OpenRCT2#2602]
I was playing openrct2 last night and messed with the "force breakdown" features. After forcing a safety cut-out on a coaster the train stops on the lift ( this is normal ) but after manually fixing the ride the lift doesnt restart.

**Comment by Gymnasiast** [comment]
I tried this, but can't reproduce it. Could you try to find a way that will _always_ trigger the issue?

**Comment by duncanspumpkin** [comment]
Is this any different to https://github.com/OpenRCT2/OpenRCT2/issues/1717

**Comment by a-can-o-beans** [comment]
Looks to be the same.

**Comment by duncanspumpkin** [comment]
@a-can-o-beans which version are you playing on? I fixed #1717 for the 0.0.3 release so if you are playing on an older one that would explain it.

**Comment by a-can-o-beans** [comment]
I just downloaded the newest build and it works now.
