### ISSUE TITLE
Rain rendered incorrectly in additional viewport

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#2607]
Using 47ca70b (current `develop`) on Linux.

![scr11](https://cloud.githubusercontent.com/assets/550290/12064167/6d69ffb2-afbc-11e5-90b0-de83f7d2b786.png)

To reproduce:
0. Enable cheats
1. Open any park
2. Use `Force thunder` cheat
3. Open additional viewport
4. Move viewport around, notice rain not moving together with new viewport.

Possibly related: Rain is not rendered in bottom and top areas (with toolbars)

**Comment by duncanspumpkin** [comment]
This is a known bug. Rain is done a bit oddly and is placed after toolbars are drawn so you end up with this. Personally I think rain could do with a complete rethink.

**Comment by IntelOrca** [comment]
The picture... isn't that just a case of it needing more available rain drop entries?

**Comment by Gymnasiast** [comment]
The 'extra viewport' feature is broken in more ways: it can't handle rotating either. I wonder whether anyone actually uses it anyway.

**Comment by IntelOrca** [comment]
@Gymnasiast

> I wonder whether anyone actually uses it anyway.

I don't think enough people know about it. I am sure some people would find it quite useful. It would be even **MORE** useful if it could handle independent rotations. That however is a large limitation since all game code refers to the same rotation variable.

> it can't handle rotating either

I assume you mean it doesn't correctly adjust location when you rotate.

**Comment by Broxzier** [comment]
Breaking the top and bottom toolbars into a left/right side could be a (hacky) workaround for the rain not being drawn in their areas. The `DrawRainWindow` function loops over all windows, and doesn't care about transparent backgrounds.
