### ISSUE TITLE
Korean letters inputing problem

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#2608]
It's hard to say, but I will try to explain to you.
First, you shall know that one korean letter is consist of three parts: initial + medial + final.
I must write at least two korean alphabet to write one letter such as "가"(ga), or three such as "감"(gam).

If I want to write 3 letters such as "가나다"(ga, na, da), I need to press six keys: ㄱ, ㅏ / ㄴ, ㅏ/ ㄷ, ㅏ
And the last letter (in this case, "다"(da).) is queueing in keyboard cursor to complete the whole one letter like this:
![image](https://cloud.githubusercontent.com/assets/10726524/12064534/a3e12baa-b008-11e5-99eb-253aa5731300.png) (The black backgrounded cursor)
But I cannot see that black cursor in OpenRCT2.

In shortly, last letter is on cursor queue but it doesn't appear on input boxes wherever input boxes are.
So I must hit another key (such as space or english letter, etc.) to dequeue the last letter which is in black backgrounded cursor.

Sorry for my short english to explain, I will explain more if you need more.

ps. Korea is now 10 p.m, Happy new year :)

**Comment by IntelOrca** [comment]
I will need to investigate this, IME editing is very tricky to get working properly. It doesn't help that SDL2 has some kind of bug which prevents the OS from displaying the character selection helper.

**Comment by telk5093** [comment]
Okay :D

**Comment by marijnvdwerf** [comment]
Would it be possible to position a system textview over the place where the custom textview would be?

**Comment by IntelOrca** [comment]
SDL2 should be doing that, but the code is not working. @marijnvdwerf Perhaps you could investigate.

**Comment by IntelOrca** [comment]
![image](https://cloud.githubusercontent.com/assets/737603/12380802/d3a7d61a-bd7b-11e5-8cb2-91d314d26830.png) ![image](https://cloud.githubusercontent.com/assets/737603/12380773/49707f2e-bd7b-11e5-9d93-fc17f9638bf5.png) ![image](https://cloud.githubusercontent.com/assets/737603/12380776/51f562ae-bd7b-11e5-8e78-676a2bf8df2c.png)

> For Latin languages, you can use accents for letters, like üïöëä. In Windows you can press the `"` key, and nothing will appear. When you press a vowel, it turns into the accented version. If you press space or another key, the regular symbol will appear. On a Mac `alt+e` is used to trigger the dead sequence. The difference between the two OS'es is that OS X actually indicates that such a sequence is taking place, by marking the symbol, whereas Windows just won't show it.

**Comment by marijnvdwerf** [comment]
The problem is in the rendering/handling. The `SDL_TEXTEDITING` is captured successfully, and the IME can be shown as well (though it'll need to positioned better). It seems that `window_text_input_paint` isn't being called.

**Comment by telk5093** [comment]
@kexplo Not applied in chat. (채팅에는 적용되지 않네요)
