### ISSUE TITLE
System wide install

### ISSUE THREAD

**Issue by Mailaender** [OpenRCT2/OpenRCT2#2612]
Compiling `openrct2` and copying it to `/usr/bin/` isn't enough, but it should be. The data folders shouldn't be hardcoded to `./data` which would then become `/usr/bin/data` then. According to FHS `/usr/share/openrct2` would be an appropriate place.

**Comment by janisozaur** [comment]
Please check with latest develop branch when you report issues. This is already solved.

https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/platform/linux.c#L116

**Comment by Mailaender** [comment]
I just didn't understand https://github.com/OpenRCT2/OpenRCT2/wiki/Building-OpenRCT2-on-Linux properly. Especially as `make install` is missing and the `openrct2.exe` wasn't build, but shipped in the tarball and the `build_g2.sh` wasn't documented ([fixed](https://github.com/OpenRCT2/OpenRCT2/wiki/Building-OpenRCT2-on-Linux/_compare/7f5b65d867358347f6cb1344c63304943478ffee...96cb34d928bdd31eae2525e623acaa8a37bc0cd9)).

**Comment by Mailaender** [comment]
A small wrapper script can already solve it: https://build.opensuse.org/request/show/351517
