### ISSUE TITLE
Glitchy rendering when there are a lot of peeps

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#2613]
There was a floating guest entry point in the attached park for a long time, causing lots of guests to exist on the same tile (7373 to be exact). For some reason this tile they are on is not rendered properly. The result looks very much like a black hole glitch (corrupt surface map element).

![](http://i.imgur.com/ptCbupN.png)
[Community Park V2.42.zip](https://github.com/OpenRCT2/OpenRCT2/files/75678/Community.Park.V2.42.zip)

**Comment by IntelOrca** [comment]
I think this is because there aren't enough available paint_structs for the tile... if its only when there are lots of peeps on the tile.

**Comment by PFCKrutonium** [comment]
I feel like I reported this way back before we broke the 1000s.

**Comment by raidcookie** [comment]
This also happens in Vanilla, IIRC.

**Comment by Nubbie** [comment]
Seems to be the same issue as [#1738](https://github.com/OpenRCT2/OpenRCT2/issues/1738)

**Comment by Gymnasiast** [comment]
@Nubbie I think you're right.
