### ISSUE TITLE
Junior Roller Coaster - Invisible First Vehicle

### ISSUE THREAD

**Issue by JoelColby** [OpenRCT2/OpenRCT2#2614]
Discovered this the other day (doing a quick search doesn't yield any similar reported issues). The Junior Roller Coaster appears to have the first vehicle missing.

Guests do not attempt to enter the first vehicle, though there appears to be a space at the station and you cannot modify the color of the first vehicle (as seen in this screenshot): http://i.imgur.com/bkbxi3D.png

**Comment by Gymnasiast** [comment]
I seem to remember this from vanilla, but I'm not sure. Could you test whether this issue is in vanilla RCT2 as well?

**Comment by JoelColby** [comment]
Ah yes, it would appear so. Sorry about that!

Looks like I played too much of the original RCT. This appears to be a minor glitch in the original RCT2. Closing this issue.

**Comment by pizza2004** [comment]
You don't need to close the issue, it's still a bug that needs fixing.  It's just necessary that it be known if it is a bug with the OpenRCT2 codebase or with the original game.

**Comment by IntelOrca** [comment]
@pizza2004 Its most likely just the object file, **not the code base**.

**Comment by pizza2004** [comment]
Ah, okay.  Still I just meant that it not being something the project did doesn't mean it shouldn't be fixed.  Any idea what would cause this specifically?  Just curious.

**Comment by X123M3-256** [comment]
@IntelOrca You're right - this is a bug in the data file. However, it's not the only file with such an issue. Lots of the game's rides contain additional "dummy" vehicles on the front and back of the car, that don't have sprites. I'm not exactly sure what they're for, but I think they're there to adjust spacing between trains (at least, I've used them for that purpose). Each object file has a count of zero cars, so these dummy vehicles don't show up in the listed train length.

What JoelColby has discovered is that these dummy vehicles **do** show up when you go to the vehicle painting menu. I've tested several other rides that I know have dummy vehicles, and it's the same across the board - all of them show up when you go to this menu.

**Comment by IntelOrca** [comment]
@X123M3-256 Hmm, I understand. I guess, we could hide vehicles with no sprites or (zero cars) from that paint dropdown.

**Comment by X123M3-256** [comment]
They do have sprites, they're just blank (i.e all transparent pixels). Usually the dummy car only has sprites for a single 32 frame rotation no matter the track style, because if the sprites are invisible it doesn't matter if it shows the wrong one.

**Comment by X123M3-256** [comment]
It seems I may have been wrong about this - I tried to make a train that consisted of only invisible cars, but it crashes the game. That suggests that invisible cars are somehow different to normal ones, and that could be used to distinguish them for the purpose of excluding them from the menu. I don't yet know exactly what the difference is - there may be a flag set or something. Using the invisible cars from my rides, which really are just a normal car with empty sprites, does not crash the game, so there must be something more to it.

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/87911421-9025ce00-caa6-11ea-8d17-cd067325932a.png)
Similar issue is occured at Splash Boat, too.

**Comment by spacek531** [comment]
> We should probably have some sort of flag to hide a car from the window. Simply blocking all ‘zero cars’ won’t work as some of them are visible and should be recolourable, like the locomotive and tender from the Miniature Railway.

I believe all invisible zero cars use paint type 0.
