### ISSUE TITLE
Feature for different names of autosaves.

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#2615]
I think autosave should be saved a different directory such as /save/autosave/ and should be named differently as the game time flows, for instance, autosave_(gametime).sv6 or autosave_(index).sv6 where index is between 0 to 10 (the way OpenTTD uses)

btw, may I ask a new feature here?

**Comment by Gymnasiast** [comment]
You can ask for new features, but try not to do it too often.

**Comment by atmaxinger** [comment]
This should be fixed by #2616

**Comment by telk5093** [comment]
Nice @atmaxinger :)
