### ISSUE TITLE
Game Crashes when saving in scenario editor

### ISSUE THREAD

**Issue by Chickenbreadlp** [OpenRCT2/OpenRCT2#2620]
I'm not quite sure what exactly the problem is, but as soon as I enter in a Park and/or a scenario name and then try to save the scenario or the landscape the game instantly crashes.
Saving the landscape goes well unless I entered in a Park Name and/or a scenario name.
It might help that I've setted the game language to german and RCT2 and Open RCT2 are both on a second Hard Drive but are in different folders.

**Comment by Broxzier** [comment]
Whoops, my bad, issue was caused by 63184052be386dc2c683bb225aa08bcf92394f61
