### ISSUE TITLE
Linux `make install` uses /usr/local/share/openrct2, but never looked in

### ISSUE THREAD

**Issue by oslerw** [OpenRCT2/OpenRCT2#2630]
Using Arch Linux, when I `make install`, it places things in `/usr/local/share/openrct2/`. However, it never actually looks in this directory. This causes the installed binary to quit with:

    ERROR[/home/william/tmp/openrct2/src/localisation/LanguagePack.cpp:40 (FromFile)]: Unable to open /language/english_uk.txt: Couldn't open /language/english_uk.txt
    ERROR[/home/william/tmp/openrct2/src/localisation/LanguagePack.cpp:40 (FromFile)]: Unable to open /language/english_us.txt: Couldn't open /language/english_us.txt
    ERROR[/home/william/tmp/openrct2/src/openrct2.c:221 (openrct2_initialise)]: Failed to open configured language...
    ERROR[/home/william/tmp/openrct2/src/localisation/LanguagePack.cpp:40 (FromFile)]: Unable to open /language/english_uk.txt: Couldn't open /language/english_uk.txt
    FATAL[/home/william/tmp/openrct2/src/openrct2.c:224 (openrct2_initialise)]: Failed to open fallback language...

The following change fixes things, but I'm not sure if this is the best way to fix it, since I'm not very familiar yet with the build system:

```patch
diff --git a/src/platform/linux.c b/src/platform/linux.c
index 98edb78..90fdee2 100644
--- a/src/platform/linux.c
+++ b/src/platform/linux.c
@@ -129,6 +129,7 @@ void platform_posix_sub_resolve_openrct_data_path(utf8 *out) {
 #endif // ORCT2_RESOURCE_DIR
 		"/var/lib/openrct2",
 		"/usr/share/openrct2",
+		"/usr/local/share/openrct2",
 	};
 	for (size_t i = 0; i < countof(searchLocations); i++)
 	{
```

I can submit a pull request if it would be helpful.

**Comment by Gymnasiast** [comment]
The problem would be better solved in that package, IMO. But I'm not sure who created it - it's not an official package in any case.

**Comment by Gymnasiast** [comment]
The preferred solution AFAIC is making it install to `/usr/share/openrct2`. @janisozaur is looking into it.

**Comment by HaasJona** [comment]
/local/ is the common prefix directory for self-compiled applications, so it should work, too. The directories without local should be used for packaged apps.

**Comment by Gymnasiast** [comment]
Hm, ok. In that case, @oslerw, could you create a PR for the change you mentioned?

**Comment by Gymnasiast** [comment]
Fixed by https://github.com/OpenRCT2/OpenRCT2/commit/60920a2d10719dd32723e36435c5d0ab5574992d
