### ISSUE TITLE
If a guest is in the bathroom and you set bathroom need to max, they never leave

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#2632]

**Comment by janisozaur** [comment]
Would *you* leave in this case? :P

**Comment by PFCKrutonium** [comment]
I mean, eventually, maybe.

**Comment by Broxzier** [comment]
Does the timing of setting it matter? When I just tried they would just leave like usually.

**Comment by mrtnptrs** [comment]
This only happens when you keep pressing on the bathroom need to be max, he will always stay at the bathroom, but if you only click on it once, he just leaves in 10 seconds when his bladder is empty :) So, this is not a bug and can be closed.

**Comment by Gymnasiast** [comment]
It's expected guests stay in the toilet if you keep refilling their bladders ;).
