### ISSUE TITLE
Game segfaults on Thorpe Park

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/OpenRCT2#2633]
The game segfaults when browsing through [Thorpe Park](http://www.nedesigns.com/park/3000/thorpe-park/), presumably because it has been modified to remove ride exits through the use of trainers.

I fired up `lldb` to investigate; this is the output:
```
Process 95336 stopped
* thread #1: tid = 0x800a30, 0x0005af1e openrct2`peep_update_ride_sub_state_7(peep=0x01149cbc) + 510 at peep.c:2389, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0005af1e openrct2`peep_update_ride_sub_state_7(peep=0x01149cbc) + 510 at peep.c:2389
   2386	
   2387			rct_map_element* map_element = ride_get_station_exit_element(ride, x, y, z);
   2388	
-> 2389			uint8 exit_direction = map_element->type & MAP_ELEMENT_DIRECTION_MASK;
   2390			exit_direction ^= (1 << 1);
   2391	
   2392			if (!(RCT2_ADDRESS(RCT2_ADDRESS_RIDE_FLAGS, uint32)[ride->type * 2] & RIDE_TYPE_FLAG_16)){

(lldb) print map_element
(rct_map_element *) $0 = 0x00000000
```

**Comment by janisozaur** [comment]
I've seen it before, in here: https://www.reddit.com/r/openrct2/comments/3y9r0m/another_helpless_bimbo_here_openrct_crashes_when/

**Comment by Gymnasiast** [comment]
Does it work in vanilla?

**Comment by duncanspumpkin** [comment]
Yeah it would work kind of. It would return something eventually for the direction

**Comment by janisozaur** [comment]
See #2629

**Comment by janisozaur** [comment]
#2629 eventually got the fix for that reverted, as I'm worried this could hide the bug.

See #2640 for this fix.
