### ISSUE TITLE
Shops & stalls can stack on each other

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#2636]
On Linux, using 047c029

Repro:
1. Open any map
2. Build new balloon stall
3. On the same tile, build new information kiosk.

Expected:
Can't build here

Actual:
Shops get stacked.

![stalls](https://cloud.githubusercontent.com/assets/550290/12080997/f3d71a50-b26c-11e5-8feb-add2a6f6abd7.png)

**Comment by IntelOrca** [comment]
Does it stack the shop in vanilla?

**Comment by janisozaur** [comment]
Just checked – yes, they stack.

**Comment by PFCKrutonium** [comment]
Wait, what?

**Comment by e-foley** [comment]
I don't see why we should change this behavior.  The game helps us out by finding a valid space for the entity we wish to place.  The same thing happens when one places shops and rides over pathways, sparing you the need to push the Shift key.

**Comment by pizza2004** [comment]
I don't know.  I feel like I've seen my friends accidentally placing shops up in the air thinking they were putting them connected to a path since the rotation didn't show it very clearly, and I think stacking like this could add to the confusion.  So I definitely think there's some merit to not stacking automatically.

**Comment by Gymnasiast** [comment]
I would prefer to keep the current behaviour.

**Comment by fbourigault** [comment]
This sounds like a bug! The shop viewport is showing the Balloon Stall and not the Information Kiosk. At least the viewport rendering should be fixed.

**Comment by janisozaur** [comment]
I didn't know it was original bug/feature. I just started playing a game and tried placing two shops, misclicked and saw that.

I reported because I feel it makes no sense to have shops stacked, especially when there is no support here and no path connected, it looks like the information kiosk is placed on the balloons. This seems really weird and I wouldn't expect something like that in real life. How would peeps even access such information kiosk?

That said, I don't have any strong opinion on this, so a voice from community is welcome.

**Comment by Gymnasiast** [comment]
The thing is that all rides autostack, and that the feature makes sense most of the time - like when the user tries to build a stall on terrain with building rights. I don't have a strong opinion on this, but I have a preference for keeping it as it is, as I think it's more consistent.

By the way, I do agree with fbourigault's comment about the viewport. That is indeed a bug, as far as I'm concerned.

**Comment by IntelOrca** [comment]
The viewport bug is something I have been noticing recently with all rides. It seems to not take account of Z.

**Comment by Overv** [comment]
The viewport bug happens because the used Z coordinate is looked up by (x, y) coordinate, which breaks when there are multiple elements there.

Also, the original game does render supports when shops are stacked:

![](http://i.imgur.com/v8Nmghm.png)

These are probably separate bugs.

**Comment by IntelOrca** [comment]
Yes that needs to be reported as a separate issue.
