### ISSUE TITLE
Use OpenRCT2 as Screensaver

### ISSUE THREAD

**Issue by ChrisOboe** [OpenRCT2/OpenRCT2#2637]
Hey openrct2 team,

I would love to use openrct2 as a screensaver. So that openrct2 just display different parks, like in the title sequence, without any user interaction at all. With Xorg you could even draw the screensaver-openrct2 to the root window, so openrct2 would be a living desktop wallpaper. I know this is a pretty strange feature request but i like the idea of viewing some nice parks when the pc does nothing. And it shouldn't be that hard to implement. 

I hope you like my idea too.
greetings,
chris

**Comment by Broxzier** [comment]
I like this idea. To keep things interesting I'd suggest randomizing the order of parks and maybe even locations.

**Comment by janisozaur** [comment]
I love this idea! I certainly would like to use it as a screensaver.

A quick brain dump:

* Would probably require changes to packaging
* We have title sequence that we (so far) change with every release, but wouldn't it get boring after a while? Perhaps a random title-sequence generator could be used (this would would have to take things like rides visible on screen, how interesting they are) which would use `*.sv6` files in a user-provided directory.
* You would want to use the same binary as the game itself, but with different `--user-data-path` set (see https://github.com/OpenRCT2/OpenRCT2/pull/2196)
* For a screensaver, OpenRCT2 can be quite resource-demanding, as we do all the rendering with original x86 assembly, without any SIMD support.

**Comment by janisozaur** [comment]
On Linux, is there anything blocking us from doing openrct2-screensaver? Isn't it as simple as setting our binary in options of your DE and making sure it starts in fullscreen?

Possible issue:
* We may have to enable demo-only mode, i.e. like the title screen, but with no overlay so user cannot click any buttons and the overlay doesn't obstruct anything from view. All input should be intercepted by the screensaver host anyway.

**Comment by ChrisOboe** [comment]
Afaik both in linux and windows a screensaver is a executable with special parameters. Thats easily possible now with just a wrapper script . Windows doesn't have a screensaver host afaik it just starts an executable, so openrct has to do alle the stuff like closing when the mouse move by itself. Also when used as root-window in Xorg you propably don't want to interact with the game.

**Comment by IntelOrca** [comment]
* Screen saver command line argument
  * Remove interface
  * Remove logo (static pixels do not save the screen)
  * Start fullscreen
  * Close on mouse or keyboard interaction
  * Disable music
* Screen saver options (separate WIN32 window or in-game?)
* Screen saver registration
* I made a basic random title sequence generator a long time ago - its still in the code base.

**Comment by PFCKrutonium** [comment]
On Windows, registering a screensaver is as simple as renaming the exe to scr.

**Comment by Broxzier** [comment]
When doing that, and double-clicking on it, the following error is printed to the console: `Error: /S does not exist`.

**Comment by PFCKrutonium** [comment]
When Windows launches a screensaver, it passes /S by default in order to launch the screen saver. I am fairly sure the switch for opening the config is /C.

**Comment by Patrik356b** [comment]
by default /c will open the options for the referenced screensaver
(mystify.scr which is on xp/vista/7/10 will show a message saying it has no config options)
