### ISSUE TITLE
New scenario window does not load correct description

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#2639]
The description shown is the one in the SC6 file, even though `english_uk.txt` calls the park in question "Mystic Mountain" throughout.

![scr146](https://cloud.githubusercontent.com/assets/1478678/12100758/2e3ad280-b331-11e5-9c89-ef6fb8671ef3.png)

**Comment by janisozaur** [comment]
the filename (as seen in the lower part of the window) is `Mothball Mountain.SC6` is this correct?

**Comment by Gymnasiast** [comment]
Yes, this is the American name for the scenario. The scenario correctly detects this (hence why it shows up as Mystic Mountain), but still loads the description from the SC6 file itself.

**Comment by janisozaur** [comment]
I just noticed something else, perhaps related.

Repro:
Open new scenario selector, highlight any item, notice park's description.
Open options switch to another language (Dutch <-> UK English work best as having most translations), highlight scenario again

Expected:
Translated description

Actual:
Description remains in the language loaded first.

**Comment by janisozaur** [comment]
![openrct2_083](https://cloud.githubusercontent.com/assets/550290/12101454/1f5841c2-b335-11e5-8780-a22ade6bc910.png)

![openrct2_082](https://cloud.githubusercontent.com/assets/550290/12101456/2108de0a-b335-11e5-99b0-87c0861c1b88.png)

The other strings get translated.

**Comment by IntelOrca** [comment]
I can't reproduce this:
![image](https://cloud.githubusercontent.com/assets/1482259/12102330/fbf57bda-b331-11e5-8893-e9ef4f8a3e07.png)

**Comment by IntelOrca** [comment]
Are you sure that its not the title that isn't updating properly?
Given that it says mothball mountain for US English in description but not title.
In English UK both title and description say Mystic Mountain.

**Comment by IntelOrca** [comment]
I think... this probably isn't a bug. English titles are stored in the binary which it will always use unless overridden by the language pack. Objects and scenarios never fallback to English UK... they instead keep their raw form.

**Comment by Gymnasiast** [comment]
Hm, I understand.

**Comment by IntelOrca** [comment]
This might need to be changed though when we do sc4.
