### ISSUE TITLE
Add feature to remove exit

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#2646]
Apparently people are using trainers to remove exits which is something that breaks OpenRCT2 (see #2640 #2633). We should add option to do that so we can support it properly.

**Comment by AaronVanGeffen** [comment]
Isn't that why @duncanspumpkin added the invisible entrance/exit style?

**Comment by IntelOrca** [comment]
@AaronVanGeffen hey, I added that.

**Comment by Gymnasiast** [comment]
Would removing the exit using the Tile Inspector count as 'supporting it properly'?

**Comment by Gymnasiast** [comment]
You can now delete the exit using the Tile Inspector and OpenRCT2 will handle this correctly.
