### ISSUE TITLE
Server does not validate client game commands

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#2650]
**This is a big deal (particularly in terms of hacking):**

When the server receives a game command, it sends it to the other clients without running it first to check if its valid. This means all the client that sent it gets a successful game command back whilst the server and all the other clients most likely error whilst processing the game command. This is obvious when you see the red error box due to another client's construction.

Easy to reproduce, if a client has disable support limits on, but not the server - the client will be able to build a high piece of track on their game but is not persisted on the server. The server gets an error box.

**Comment by janisozaur** [comment]
How do you envision this validation?

Something remotely similar to https://github.com/OpenRCT2/OpenRCT2/pull/2629 ?

**Comment by IntelOrca** [comment]
Quite simple, I am just going to make the server call do_game_command with APPLY flag set to false and see if it is successful.
