### ISSUE TITLE
Scenarioselectionwindow

### ISSUE THREAD

**Issue by Horsti12** [OpenRCT2/OpenRCT2#2653]
In my opinion you guys should rename Original DLC Parks to Extras like it was in RCT1 and move the Competion Land 1 & 2 to a new section under the Other Parks which is called Competions.
Panda World the official Scenario from Chris Sawyer should also be under the Extras section.
And the Mega Park from the RCT1 Tab should be also moved to Other Parks into the Extras section, because it was exactly how it was in RCT1. Important is that it has to be locked when you play with the locked mode.

-Extras-
Mega Park (locked)
Fort Anachronism
PC Player
PC Gaming World
gameplay
Panda World

-Competitions-
Competition Land 1
Competition Land 2

-Build your own...-
..
..
..

**Comment by Gymnasiast** [comment]
The goal of OpenRCT2 is not to make everything as it was in RCT1 as you seem to want, but just where that makes sense. I already explained to you that more tabs are not an option (there are more than enough already), especially when those contain just a few entries.

**Comment by Horsti12** [comment]
Than you not really understand what I mean. I not mean the tabs I mean the sections which are in the tabs.
When you sort by game than the sections are Beginner, Challeging and Expert.

I marked them red on my picture.
http://prntscr.com/9mkuv2

**Comment by IntelOrca** [comment]
What is wrong with Original DLC Parks? Its more descriptive than "Extras". And Mega Park was after Thunder Rock in RCT1 without expansion packs.

**Comment by Horsti12** [comment]
Mega Park is more a sandbox park and not a real scenario.  And when you talk about no addons than Fort Anachronism should also come under Added Attractions, because it was exactly how it was without the loopy landscape pack.
Panda World, a official Scenario from Chris Sawyer should also come into the same category as the other parks which are currently named "Original DLC Parks" because it make not sense to make a new category for just one Scenario. Competions were also seperate from Other parks in RCT1 with Addons, so it should come in it's own little section.

**Comment by IntelOrca** [comment]
For the purposes of locking, it doesn't seem as intuitive for Mega Park to not be under all the RCT1 scenarios.

@Gymnasiast and me discussed Competitions category but decided not to as there are only two scenarios.
