### ISSUE TITLE
Landscape / Water Tool is broken

### ISSUE THREAD

**Issue by atmaxinger** [OpenRCT2/OpenRCT2#2658]
The landscape and water tools seem to be broken as of today. At the beginning it does the exact opposite of what is should do.

This could be related to commit https://github.com/OpenRCT2/OpenRCT2/commit/f5db0a83e5795cc6e1137d7b8115a51c4d605105

Happens in multiplayer and single player.

![landscape bug](https://cloud.githubusercontent.com/assets/5960633/12146536/5e82e70c-b494-11e5-909d-cdbecf0ad8aa.gif)

**Comment by Broxzier** [comment]
It seems to remember the last location where you released the mouse, and next time you press it, it uses this position instantly to get the delta.
I'm not 100% sure, and cannot check at the moment, but I think this could be fixed by setting the location of the mouse when the mouse button is pressed.

**Comment by telk5093** [comment]
In my case, if I click the tile with opening landscaping tools, it starts lower the land even though the mouse cursor is not moving.

**Comment by atmaxinger** [comment]
https://github.com/OpenRCT2/OpenRCT2/commit/c181f18309f2be254060ffbfcb59b0ae33f7b7d8 seems to cause it.

**Comment by LinusU** [comment]
@IntelOrca Should we also remove the definitions of `RCT2_ADDRESS_CURSOR_DRAG_LAST_X` and `RCT2_ADDRESS_CURSOR_DRAG_LAST_Y` since they are no longer being used?

**Comment by IntelOrca** [comment]
I haven't been doing that for the same reason all the functions still have comments saying their original addresses.

**Comment by LinusU** [comment]
Cool, just checking :+1:
