### ISSUE TITLE
Suggestion: Adding "needs to unlock" tooltip/info in the description panel to the locked scenarios

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#2660]
As the title says, i think it should be similar to the one in RCT1, which provides a clearer understanding to the complete beginners.

edit: using the description panel in the right would be more concise.

**Comment by Gymnasiast** [comment]
Hm, it's more difficult than I anticipated. If anyone feels like picking it up, please do so.

**Comment by janisozaur** [comment]
Just some suggestions how else this could be done:

* Tooltip
* When debug tools are enabled, we display a filename in the bottom part of the scenario selection dialog, perhaps this could be used for such notification
* Prepending the scenario name with "needs unlocking"
