### ISSUE TITLE
Buying Land Ownership annoying error

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#2677]
When trying to buy land that you cannot buy, the tool prevents you from buying tiles that you can buy when you continue dragging. Personally I would prefer it to be more like the painting land tool. Buy the land that you can buy within the area, ignore land that you cannot buy.

**Comment by IntelOrca** [comment]
Yes, I did this with land raising / lowering near the edge of the map.

**Comment by Broxzier** [comment]
@IntelOrca: With "I did this" do you mean you added this behaviour for the land tool, or do you mean you already made it for buying land ownership?

**Comment by IntelOrca** [comment]
added behaviour

**Comment by Broxzier** [comment]
Then this could also be enhanced for the land tool, which now still generates an error when changing the height of partly owned land.

**Comment by rwjuk** [comment]
Fixed in #6610
