### ISSUE TITLE
Use OS native line endings for config.ini

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#2678]
Particularly a problem for Windows if you try to edit config.ini in notepad which can only read CRLF. So there should be a function called platform_get_line_ending() which returns ```"\r\n"``` for Windows, ```"\r"``` for OSX?, otherwise ```"\n"```.

Then config_save just needs to write out the result of the function for each line.

**Comment by atmaxinger** [comment]
OS X is also ```\n```

**Comment by Gymnasiast** [comment]
Indeed, `\r` was classic Mac OS. OS X uses the UNIX standard `\n`.

**Comment by IntelOrca** [comment]
Ah, cool.

**Comment by janisozaur** [comment]
You should just read a line, whatever the line endings are. This way you can share configs between systems.

Yes, I know the paths may not match, but they *can*, and all the other settings will.

For saving the file though, yes, a native line ending should be used.

**Comment by IntelOrca** [comment]
@janisozaur It already reads \n or \r as a line.

**Comment by janisozaur** [comment]
@IntelOrca :+1:
