### ISSUE TITLE
Immense negative balance when changing colour of ride

### ISSUE THREAD

**Issue by TheLightningStrikes** [OpenRCT2/OpenRCT2#2679]
This is my first bug report ever so sorry if it's messy!
I was in a multiplayer game, we loaded a save from a small while ago. (we just upgraded to the developers build haha)
I changed the base colour of the 3D Cinema from black to white which changed our balance negatively.

Sadly the uploading feature on GitHub isn't cooperating with me so here are some puush links:
http://puu.sh/mpyBV/7a44f2a0c5.sv6 (save)
http://puu.sh/mpEw8/2448ccfb21.png (screenshot of the negative balance after changing)
http://puu.sh/mpEzJ/a4d2c13261.png (screenshot of the finances)

Steps to reproduce:
1. Load the map into multiplayer
2. Click the 3D Cinema
3. Change the base colour of the cinema from black to white
4. Negative profit.

In singleplayer I was not able to recreate the issue.
Not sure if this happens when I change other colours too or if it's just 3D Cinema related or whatever.
Haven't tested those things yet.

I'm using OpenRCT2.com 0.0.4 build 1628.

**Comment by Gymnasiast** [comment]
To me, this looks like either
1) Memory corruption
2) Anti-cheat code from RCT2 playing up (it would make your balance negative if it detected money cheats).

**Comment by IntelOrca** [comment]
Its to do with my update to do_game_command, I need to investigate.
