### ISSUE TITLE
When lowering/raising land/water with clearance checks off, walls still get removed

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#2681]
I think when clearance checks are disabled, lowering/raising land/water should not remove objects that are in the way.
Changing this would make building sloped walls in the air a lot easier, for example.

**Comment by Gymnasiast** [comment]
By the way, I was looking into it myself, but couldn't find the responsible code - it doesn't seem to be in the `lower_land` function, for example.

**Comment by IntelOrca** [comment]
There is a common function for clearing checks and operations. Its used by track construction too for example.

**Comment by Broxzier** [comment]
Very nice. Without clearance checks walls will still get removed when lowering the ground, even though they will not have any collision then. Is this code also responsible for this?

**Comment by IntelOrca** [comment]
@Broxzier yes, but I assume the original behaviour is like this top stop floating tilted walls. But I don't know why you shouldn't have them when you can have floating straight walls.

**Comment by Broxzier** [comment]
I think the default behaviour should be to keep fences/walls where they are when lowering the ground, not only with clearance checks disabled, and possibly also when raising the ground, but not the part where the fences are on.
For example when raising a lane tile like this, only the two fences on the bottom should get removed by default:
![](http://i.imgur.com/VLvZczF.png)

**Comment by IntelOrca** [comment]
Sure, also we should allow lowering the land directly under a track piece or path.
