### ISSUE TITLE
One-click reconnect in multiplayer

### ISSUE THREAD

**Issue by devnoname120** [OpenRCT2/OpenRCT2#2695]
It would help a lot to add a reconnect button to the disconnected window.

**Comment by janisozaur** [comment]
I think there is some other underlying issue preventing this, in my (limited) testing, I was not able to reconnect at all without restarting the game.

Both of these could be solved at the same time.

**Comment by devnoname120** [comment]
In my testing, I could reconnect right after without problems (unless when the game crashed of course).

**Comment by JohannesHoffmann** [comment]
+1
i agree with devnoname120. We built a big park and every time we ran out of money we noticed the host has still 1.000 money left.
A reconnect helps but this takes to long, quit, open server list, find the server in the list and connect.
A simple reconnect would be so nice. I gues it makes only sense in the beta. In future versions the network code should be stable enough to make a reconnect unnessesary.
