### ISSUE TITLE
Reverse Freefall Coaster - No slow-down and no sound

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#2700]
Reverse Freefall Coasters:
* Don't slow down as they roll back to the station.
* Don't make any noise apart from when the car is at the peek of the ascent to the top.

Observable in Six Flags: Magic Mountain.

**Comment by Broxzier** [comment]
An issue that was posted on the forums might be related to the sound issue you describe: https://openrct2.org/forums/topic/768-sound-problem-004-build-1636/

**Comment by IntelOrca** [comment]
@Broxzier Yes it looks like the same issue, its when the train is going very fast that there is no friction noise.
