### ISSUE TITLE
Vehicle Update - Sudden Velocity Change on Crash

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#2701]
(With crash I mean a crashing ride, not the game crashing)

Build any coaster that will crash (I only tested it with looping and twisted coasters), and test it.

The following example moves from the track over the yellow axis, instead of with the last velocity each car had.
![Example](http://i.imgur.com/i5CH7Ce.png)

Using the build provided by the Launcher (1ddad61).

**Comment by Christipher** [comment]
that sounds like a violation of standard physics here... it should not be reversing like that (it should go forward in relation to it's initial velocity)

**Comment by duncanspumpkin** [comment]
It only happens on certain rotations as well.
