### ISSUE TITLE
Colour Scheme displays wrong text

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#2702]
While just playing I noticed that the text for colour schemes was off.

![screenshot](http://i.imgur.com/twyBXgv.png)

The number of seconds seems to change as well.

Using the build provided by the Launcher (1ddad61).

**Comment by duncanspumpkin** [comment]
Fixed by #2696 and f2b70b74aa3983f085ed6149f82d667854e7d89a.
