### ISSUE TITLE
OS X doesn't use default currency for locale

### ISSUE THREAD

**Issue by marijnvdwerf** [OpenRCT2/OpenRCT2#2705]
![image](https://cloud.githubusercontent.com/assets/737603/12253001/a27afafc-b8dc-11e5-9a76-e72476555ef4.png)

It seems that `currency_symbol` is expected to be `€`.

**Comment by LRFLEW** [comment]
I believe there's an Objective-C method of grabbing the locale stuff. I don't know if it would be better (or even different) from what we have in posix, but it's at least worth looking into.

**Comment by marijnvdwerf** [comment]
You're right. The Cocoa API does return the proper symbol.

![image](https://cloud.githubusercontent.com/assets/737603/12259366/7aa74682-b915-11e5-9094-9f1a78c187b8.png)

**Comment by LRFLEW** [comment]
Then we should put the "posix" method in the linux file and switch to the Objective-C method for OS X. I can write it, or if you already mostly have it, you can finish it up.

**Comment by marijnvdwerf** [comment]
Go ahead. I'm not particularly familiar with combining C and Objective-C.

**Comment by marijnvdwerf** [comment]
Wouldn't it make more sense to make a hash with supported currencies' ISO code and the enum value? That way you'd only need to split up the system currency code selection to two platforms.
