### ISSUE TITLE
Gee Hack (invisible Huts)

### ISSUE THREAD

**Issue by coasterbill** [OpenRCT2/OpenRCT2#2706]
When I gee hack it randomly decides when it wants to display it properly and when it wants to screw it up. I've attached a screenshot from normal RCT and an open RCT one with a maze and banner signs visible but with the lines a little further down (to the lower left) everything looks perfect...

![scr522](https://cloud.githubusercontent.com/assets/16659244/12253624/f54ecb6a-b8ae-11e5-96e6-5f79882014b2.jpg)
![scr522fuckedup](https://cloud.githubusercontent.com/assets/16659244/12253625/f557edbc-b8ae-11e5-95fc-f0fe6cd0ed28.jpg)

**Comment by PFCKrutonium** [comment]
@janisozaur Can the tile inspector be used to hide those?

**Comment by coasterbill** [comment]
I don't really know much about tile inspector. I just assumed that if it worked in RCT it would work in open RCT, when I mentioned this I was told to open a ticket. I would think if it displays properly in RCT it shouldn't require extra work in open RCT, right? Sorry I'm not overly informed on the project, this was my first time trying it.

**Comment by janisozaur** [comment]
What's a "gee hack"? Yes, tile inspector (actually the corrupted element) should be able to hide that.

**Comment by duncanspumpkin** [comment]
I think from having a read through new element Gee hack sounds like a corrupt map element hider. Most likely the order of elements is different in this one and can be fixed with tile inspector.

**Comment by IntelOrca** [comment]
@coasterbill could you provide a saved game?
