### ISSUE TITLE
Closed Rides don't display how many people are on it

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#2708]
This is something I found annoying in RCT2 as well. When you close a ride, for when you want to edit it for example, the ride window does not display how many people are on there. This would be helpful information, since if you forcefully close it the guest's happiness will drop a lot.

**Comment by Christipher** [comment]
I honestly think this should be open for discussion - do we want to change the behavior for a closed ride where you close it (i.e. the ride does not crash) or for a ride where you forcefully put the ride into test run mode?

**Comment by Broxzier** [comment]
It is not a chance in behaviour at all, all it does it changing the status text. Let's say you have a train track with 100 guests on it, and you want to change the location of one of its stations, then you close the ride, but as soon as you start building all guests will be forced outside. To prevent this you have to wait for all guests to leave, however the only way of knowing how many guests are on the ride is by checking it in the guest list.

So what I propose it simply changing the text from `Ridename (closed)`, to something like `Ridename (closed; 100 guests on ride)`.

**Comment by IntelOrca** [comment]
Surely you want to know how many guests are on it before you close it?

**Comment by Broxzier** [comment]
Before you close a ride you can already see how many people there are on a ride, by either hovering over it or by checking the ride's status. What I mean is that when you close a ride, it takes time for all guests to depart from the station, because the ride continues to run. I don't want to change the ride while there are still guests on it, but it doesn't show how many there on the ride are in its status.

**Comment by IntelOrca** [comment]
![image](https://cloud.githubusercontent.com/assets/1482259/12272618/5a4e95ae-b959-11e5-977d-df0fa8e8f85c.png)

How about showing on this tab?

**Comment by Broxzier** [comment]
@IntelOrca: I'm fine with that.

**Comment by IntelOrca** [comment]
@Broxzier me too, feel free to add that if no one else objects.

**Comment by Gymnasiast** [comment]
When you're on that tab, you can click the button for "Guests on this ride", which will tell you how many peeps are still on it.

**Comment by Broxzier** [comment]
@Gymnasiast: True, I was just thinking it would be easier to see by just hovering over the ride, just like how you can see it while the ride is still open.
