### ISSUE TITLE
Crashing Chairlift

### ISSUE THREAD

**Issue by BaryonQuark** [OpenRCT2/OpenRCT2#2710]
Chairlift crashes strangely when queue of carts is longer then station length.

Happens on default settings adjusted to max amount of carts (22) and max speed of chairlift, default scenario: lightning peaks. See also screenshot.

![pcfyqrf 1](https://cloud.githubusercontent.com/assets/16672983/12274680/4854ae84-b96c-11e5-9bcb-7580c5647389.png)

Develop build 1645

**Comment by duncanspumpkin** [comment]
This can be reproduced in the normal game if you disable the speed limit.

**Comment by Gymnasiast** [comment]
I don't think maxing out the speed limit to 410 km/h and still expecting no side effects is really justified. I'm not sure we should 'fix' this.

**Comment by Broxzier** [comment]
It sounds more like @BaryonQuark means this happens by setting the speed to the maximum allowed speed with the restrictions still enabled.

**Comment by Gymnasiast** [comment]
If it's set to just 14 km/h (the normal max speed) and still crashes, then I'd say we should fix it, of course.

**Comment by IntelOrca** [comment]
Or should we? How is it any different from having the speed too high on a launched freefall or making sure you add brakes to roller coasters before the station? This is just part of game balancing - you need to take account of the station design / layout when setting the speed otherwise crash.

**Comment by BaryonQuark** [comment]
It occured at a setting of 14kmh. Yet I also remember it happening at the lower setting of 9 kmh as I tried fiddling around with max speed and number of carts. I do invite you guys to reproduce it, it only requires the ingredients of (far) too many carts for the station length though also might be independent of any set speed...

**Comment by Broxzier** [comment]
Someone figured out [when this cash occurs exactly](https://openrct2.org/forums/topic/1126-chairlift-crash/#comment-5171). He made a screenshot displaying where they do, and where they do not crash:
![](https://openrct2.org/forums/uploads/monthly_2016_04/570b09e248dbf_chairliftfail.jpg.724b8f217cd9e1060d3061048c0dc861.jpg)
red cross = where it crashes
green circle = where it's working fine

It seems to be related to the position.

**Comment by duncanspumpkin** [comment]
@Broxzier can you throw together a quick example map that always reproduces this. Hopefully can get it fixed before 0.0.4.

**Comment by Broxzier** [comment]
@duncanspumpkin: MetallicaXP (forums) made this map: [chairlift fail.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/215391/chairlift.fail.sv6.txt)

**Comment by duncanspumpkin** [comment]
ty
