### ISSUE TITLE
Wooden Roller Coaster ratings incorrect/incorrect air time.

### ISSUE THREAD

**Issue by EternallySlaying** [OpenRCT2/OpenRCT2#2717]
Wooden roller coasters are for some reason improperly calculated. They get a huge amount of air time, which fluctuate wildly at the smallest of edits, sometimes by more than 50 seconds at the change of a single hill, and often more than the ride length. I've retested with other trains, and the only difference is in the train modifier. Versions noticed: 0.0.4 build 1644 to 0.0.4 build 1646 downloaded from openrct.com.

![Imgur](http://i.imgur.com/i6GESbw.png)

In regular RCT2, the air time is only about 5 seconds, and the Intensity is identical. The Excitement and Nausea are much lower, with excitement at 8.88 and nausea at 6.40. This also makes an interesting note in that air time in itself does not affect intensity at all.

[River Park For Bug.zip](https://github.com/OpenRCT2/OpenRCT2/files/89334/River.Park.For.Bug.zip)

**Comment by IntelOrca** [comment]
This is a bug with vehicle update (calculation of air time), not ride rating calculations (excitement, intensity, nausea).
