### ISSUE TITLE
Ground rendering issues

### ISSUE THREAD

**Issue by PhyxionNL** [OpenRCT2/OpenRCT2#2723]
This seems to happen mostly near underground area's but I've seen it happen on other places as well. Sometimes the ground renders above/through/behind an item.

You can see it happen here with the supports of the ride:
https://vid.me/F7J3

**Comment by IntelOrca** [comment]
We can't fix Z fighting yet.

**Comment by Phyxion** [comment]
Alright, thanks for the info :) I saw it happen mostly with the ground although there is some scenery with which this happens as well. This is probably all related to the same problem?

**Comment by marijnvdwerf** [comment]
@IntelOrca This is probably a bound-box issue, right?

**Comment by IntelOrca** [comment]
@marijnvdwerf can you explain it being non-deterministic?

**Comment by J-PIE-314** [comment]
Original poster's link now leads to a questionable website.

**Comment by tupaschoal** [comment]
The description itself is pretty vague. Do you remember it @Gymnasiast, or should we close it?

**Comment by J-PIE-314** [comment]
I did a search and `vid.me` links are in other comments and issues in this repository as well.

**Comment by J-PIE-314** [comment]
I did a search and found that links to that website are in other comments and issues in this repository as well.

**Comment by Gymnasiast** [comment]
I have no idea, I’m afraid. I’m closing this.
