### ISSUE TITLE
Virginia reel lift hill chain speed

### ISSUE THREAD

**Issue by Phyxion** [OpenRCT2/OpenRCT2#2725]
If you place it and check the speed it defaults to 8km/h, however, if you change this it becomes 6km/h and you can never set it back to 8km/h. I think I've seen this with some other rides as well.

To make this easy to check, add Wheely Reel design.

**Comment by Gymnasiast** [comment]
Checking in vanilla RCT2 shows it should default to 4 km/h, with the only other available speed being 6 km/h. The bug is that it defaults to the wrong speed in OpenRCT2.

**Comment by duncanspumpkin** [comment]
Okay sounds like the td6 has an artificially high value

**Comment by Gymnasiast** [comment]
I'm not sure this is something we should fix, though. The lift speed is part of a design, and has also been used to create boosters. I think it would be better if we don't "correct" it if it's too high or too low for a ride.

**Comment by IntelOrca** [comment]
I agree, out of range values in saved files will work in the game but will be capped to the default range if you try to change it. This is expected behaviour.

**Comment by Gymnasiast** [comment]
Ok, shall we label this as "wontfix" and close it?
