### ISSUE TITLE
Error in Multiplayer

### ISSUE THREAD

**Issue by Bobbaone** [OpenRCT2/OpenRCT2#2727]
This Errormessage came, after Connect to a Server:

![unbenannt](https://cloud.githubusercontent.com/assets/12818930/12334136/ae3f390c-baf8-11e5-8a44-f66812c62474.PNG)

**Comment by duncanspumpkin** [comment]
Your ride has become corrupt. Can you provide the save file and we can possibly fix it.

**Comment by IntelOrca** [comment]
Question is... how did it become corrupt?

**Comment by Broxzier** [comment]
@duncanspumpkin: How do you see which type a ride should be, and how do you fix them? (I haven't looked at any ride code in detail). There have been quite some parks becoming corrupt.

@IntelOrca: Right now people can access the object selection on a network but it only updates the entries locally. I suggest disabling this window when playing online, that way no new rides that do not exist on the server can be built.

**Comment by IntelOrca** [comment]
@Broxzier I agree.

I fix rides usually by commenting out the draw function or something so that it stops crashing. Then just demolish it in game and save.

**Comment by IntelOrca** [comment]
Closing as this issue is not helpful for finding the route cause.
