### ISSUE TITLE
Vandalism enhencements\suggestions + more

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#2737]
- CCTV object
  - prevents vandalism within a certain range, add more to increase the range (perhaps a 15x15 square with the cctv in the middle)
  - should be available as quarter-tile and path-object
- Popping other guests balloons
  - If this happens on screen, perhaps apply same effect as when a player pops a loose/floating baloon
  - slightly reduce guest happiness
  - maybe cheat or other option to pop the guests balloons
- ~~Making handymen go "fix"/clean toilets like mechanics fixes rides~~ maybe not

**Comment by Patrik356b** [comment]
Obviously a low priority for now if considerd

**Comment by Gymnasiast** [comment]
Please don't post multiple ideas in one issue next time. It's tedious to keep track of and to discuss.

- CCTV object: what you describe is exactly what we have the security guards for.
- Popping other guests' balloons: I have no strong feelings about this one, but with people being as small as they are, it might be difficult to select guests without accidentally popping their balloon.
- Making handymen go "fix"/clean toilets: that would require more handymen, which would mean the game balance would change as this costs more - and we already pay for cleaning of toilets with the fixed costs per hour. I don't think this would really be an improvement.

**Comment by Patrik356b** [comment]
Because they are somewhat related i did not want to split this.

- CCTV should be an optional addon/replacement so you could have guards in the most active area and CCTV in the outer parts for example
- Hence the "maybe"
- Maybe have them enter/exit these for the visual effect. (I haven't really looked into how the stalls work, excluding those that sell food/drink/umbrella)

**Comment by PFCKrutonium** [comment]
Popping a guests balloon vs clicking on them shouldn't be too hard imo.
