### ISSUE TITLE
Swinging Cars Animation Broken

### ISSUE THREAD

**Issue by EternallySlaying** [OpenRCT2/OpenRCT2#2740]
Noticed that swinging cars do not swing at all. I have noticed this for the Suspended Swinging, Mini Suspended Swinging, and Mini Flying Suspended Swinging. Version is 0.0.4 build 1657 for windows, downloaded using the launcher. Sorry for the multiple recent posts.

Notable in the screenshot with the train going up the curve on the right.
![Imgur](http://i.imgur.com/xjhFXrM.png)

**Comment by e-foley** [comment]
Confirmed.  Same thing happens with...

* Bobsleigh Coaster
* Flying Turns
* Water Slide

**Comment by janisozaur** [comment]
@EternallySlaying we have specifically disabled displaying build number in https://github.com/OpenRCT2/OpenRCT2/pull/2715 so when you report you would use something meaningful. I have to ask: where do you get these numbers from?

**Comment by EternallySlaying** [comment]
If I'm not looking at the wrong thing (using the title screen here).

"OpenRCT2, v0.0.4-develop build e69e384 provided by OpenRCT2.com"

While I understand that you may prefer the commit hash (which I only get now after looking at the thread you linked), I find it a bit confusing that you have the system I referenced here: https://openrct2.com/download, but seem to want something different. I have no problem with the commit hash, just maybe think of making that page reflect this system to avoid confusion. I'll try to remember to use the hash next time.

**Comment by Gymnasiast** [comment]
@EternallySlaying : OpenRCT2.com is not an official site and not "our system". Also, the site is in the process of being replaced with a new site, which will be official, so the current site can be a bit outdated.
