### ISSUE TITLE
Track Designs Manager crashes

### ISSUE THREAD

**Issue by e-foley** [OpenRCT2/OpenRCT2#2741]
Tested in Build 1657.  I simply start the Track Designs Manager, choose any ride, and I'm met with this message.

![assert_fail](https://cloud.githubusercontent.com/assets/6338134/12371368/470180bc-bbe6-11e5-9985-c4ab0fb1f5e5.png)

**Comment by janisozaur** [comment]
@e-foley we have specifically disabled displaying build number in https://github.com/OpenRCT2/OpenRCT2/pull/2715 so when you report you would use something meaningful. I have to ask: where do you get these numbers from?

**Comment by e-foley** [comment]
Until recently, you had been encouraging contributors to specify the build number.  Sorry for being slow to pick up the new scheme.  I checked and I think the hash you're looking for is e69e384.

**Comment by e-foley** [comment]
To answer your question, https://openrct2.com/download still lists the old-style build numbers.  I know openrct.com is not the official OpenRCT2 site, but it has the most convenient interface for casual bughunters like myself. (In fact, I have the page bookmarked.)

If the official OpenRCT2 website https://openrct2.website/ were more complete, I'd use that instead.
