### ISSUE TITLE
Scenario picker displays unlocalized path

### ISSUE THREAD

**Issue by marijnvdwerf** [OpenRCT2/OpenRCT2#2742]
Path segments like 'User' and 'Library' should be localised. Should probably also use an arrow for neatness.

```swift
let fileManager = NSFileManager.defaultManager()
fileManager.componentsToDisplayForPath("/Users/Marijn/Library/OpenRCT2/RCT2/Scenarios/Six Flags Holland.SC6");
// ["Macintosh HD", "Gebruikers", "Marijn", "Bibliotheek", "OpenRCT2", "RCT2", "Scenarios", "Six Flags Holland.SC6"]
```

![schermafbeelding 2016-01-16 om 15 19 22](https://cloud.githubusercontent.com/assets/737603/12372835/c962de38-bc64-11e5-8acb-b2308c10bd96.png)
![schermafbeelding 2016-01-16 om 15 20 57](https://cloud.githubusercontent.com/assets/737603/12372834/c95da04e-bc64-11e5-92a0-330923c2a6da.png)

**Comment by IntelOrca** [comment]
This is only shown if you have debugging tools. That is why its important to show the whole path as its used to see what directory its being loaded from.

**Comment by marijnvdwerf** [comment]
My bad. Non-issue then!
