### ISSUE TITLE
Add another date format

### ISSUE THREAD

**Issue by Phyxion** [OpenRCT2/OpenRCT2#2745]
Our date format is d-m-yyyy (or dd-mm-yyyy).

**Comment by IntelOrca** [comment]
Our?

**Comment by jensj12** [comment]
Day/month/year is already in the game (probably even the default setting). Using numbers for the month wouldn't work as well as you might hope as the game doesn't use full years (it'll jump from 10 to 3).

**Comment by Gymnasiast** [comment]
Indeed, and every language already has to support three useless (for that language) date formats anyway, due to the way the date system is implemented.

**Comment by Phyxion** [comment]
Woops, completely missed that it's there already, closing :)
