### ISSUE TITLE
Add coaster completion button

### ISSUE THREAD

**Issue by AZon8** [OpenRCT2/OpenRCT2#2746]
Have a button which will finish the roller coaster by connecting the two end points. 
It would require some path finding wizardry but would allow quicker coaster construction.

**Comment by Gymnasiast** [comment]
I don't like this idea very much, to be honest. It makes some sense in RCT3 and similar 3D coaster builders, where it's harder to get a clear view, but not in RCT2 with its isometric view and far fewer possible pieces. It also doesn't really fit within the feel of RCT2, IMO.

**Comment by IntelOrca** [comment]
This is incredibly hard to do:
* In RCT3 it was quite slow to complete the circuit.
* In RCT3 is wasn't particularly good.
* It would never produce results as good as a human.
* The ghost test mode is a better solution to testing out a coaster before its fully completed.
* Would require a really committed developer to work on it.

Saying that, there are already have been and still are attempts to procedurally generate an entire roller coaster.

**Comment by Patrik356b** [comment]
Most of the time RCT3 could not complete a track with multiple turns and banking missing as far as I have seen
