### ISSUE TITLE
Changing game language while playing causes ride names to be "(undefined string)"

### ISSUE THREAD

**Issue by marijnvdwerf** [OpenRCT2/OpenRCT2#2751]

**Comment by Overv** [comment]
What are the exact steps to reproduce this?

**Comment by marijnvdwerf** [comment]
- Open game with Dutch as language
- Start a new scenario
- Open ride construction window
- Select 'gentle rides' tab
- Open options window
- Change language to English
- Hover over ride icons. Some of them are now named '(undefined string)'

When changing from English to another language, the English name keeps on being used.

**Comment by Overv** [comment]
Ah right, I thought you were talking about the rides you already built. I'll look into it.
