### ISSUE TITLE
OS X: Platform save dialogs aren't localised

### ISSUE THREAD

**Issue by marijnvdwerf** [OpenRCT2/OpenRCT2#2758]
When opening a platform save dialog on OS X, the localisation doesn't match that of the game, but stays English instead. 

![image](https://cloud.githubusercontent.com/assets/737603/12380212/867c1544-bd6d-11e5-860c-7dd72c4d986b.png)

![schermafbeelding 2016-01-17 om 22 57 26](https://cloud.githubusercontent.com/assets/737603/12380221/b850989c-bd6d-11e5-9f3b-6f363484bf03.png)

**Comment by LRFLEW** [comment]
Wait, the language of the game? The save dialogue is handled by the OS, so it should match whatever the OS's language is. Is the OS set to english? If not, then there's a bug here.

I looked through the code, but couldn't see anything that would be affecting localization. There are three places this bug could be, and I need to know which of them the bug affects exactly. First is the save dialogue you showed, second is the equivalent open dialogue from loading a save, and third is the folder selection when the game path is not set in the config.ini file. Could you test all of these for me?

**Comment by pizza2004** [comment]
Do we not need to worry about having localization files in the app bundle for save dialogs and such?  I had thought perhaps that could be the issue, but I wasn't sure if that applied to stuff like canned save dialogs.

**Comment by marijnvdwerf** [comment]
The OS is set to Dutch, the game supports Dutch, so imho save dialogs etc should be in Dutch too.

**Comment by AaronVanGeffen** [comment]
From what I'm reading, we may need to bundle `lproj` files for each of the languages supported by the base game, otherwise OS X will not translate its system dialogues either.

**Comment by LRFLEW** [comment]
Found a really simple solution to this. The plist property `CFBundleAllowMixedLocalizations` tells the loaded frameworks (in this case, the AppKit framework that handles the dialogue) to use its own localization strings. This seems to fix the issue. I'll open a PR for it now.
