### ISSUE TITLE
Server selection UI doesn't match regular UI conventions

### ISSUE THREAD

**Issue by marijnvdwerf** [OpenRCT2/OpenRCT2#2760]
When clicking on a server in the server list, nothing seems to happen. After a while I realized that _while_ pressing an item, a dropdown menu appeared. This doesn't seem to match other in-game behavior.

Wouldn't it make more sense to make a click on the item start the joining process, and add a "open star/closed star" toggle on the left of the item for favouriting?

**Comment by IntelOrca** [comment]
This was originally how it was but then got changed to a dropdown.

**Comment by Broxzier** [comment]
I had the same issue as Marijn the first time I tried to join a server. Why was it changed?

**Comment by IntelOrca** [comment]
@Broxzier You'll have to ask @zsilencer

**Comment by zsilencer** [comment]
I think IntelOrca originally made the server list and it used to not fetch the remote list, you had to add a server manually, which stores them in a separate file.  The manually added servers were renamed to favorites because I didn't want to erase the existing code, and the dropdown was the simplest I could think of to add/remove them, similar to the kick player.  I suppose it could be made to work like the toolbar buttons, with a default action of joining.

**Comment by IntelOrca** [comment]
I also wanted a spectator mode (separate passwords (if any) for spectate / play), but that never got implemented.

**Comment by zsilencer** [comment]
Oh yeah, I am thinking we could implement a permission system, and disallow certain clients from doing any commands which would be like a spectator mode.  Could have an option to allow clients to not have to enter a password but they would be assigned to the spectator group, set specific boundaries where a permission group can build etc.

**Comment by IntelOrca** [comment]
Yes, we should probably just start with a simple spectator or no spectator then build up from that.

**Comment by janisozaur** [comment]
wouldn't spectator be something like simply drop `GAME_COMMAND_FLAG_APPLY` on server from given player ID and on client only execute commands coming from network when connected as spectator?

**Comment by IntelOrca** [comment]
It should ignore game commands altogether received from a spectator. That should be enough game logic wise.

For interface, we will need to make all the controls read only if in spectator mode.
