### ISSUE TITLE
Forcing uppercase for banners causes glitching

### ISSUE THREAD

**Issue by marijnvdwerf** [OpenRCT2/OpenRCT2#2762]
The entrances appear to be fine, but the banners over a path seem to be using the regular width to determine the number of frames needed. Causing the animation to reset too early.

**Comment by Gymnasiast** [comment]
Note: @IntelOrca attempted to fix it some months ago, which slightly decreased the problem.

**Comment by IntelOrca** [comment]
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/2238
