### ISSUE TITLE
Change the debugging tools dropdown to stay open on click

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#2768]
Currently, clicking the debugging tools dropdown will open the console. Since other items, like the tile inspector, are probably used as often, and since the console has its own shortcut, I would prefer if the dropdown stayed open, which would decrease the needed effort to select another option.

The change is trivial, and you can assign me if it's okay with you.

**Comment by IntelOrca** [comment]
I'd say further discussion is needed for this button. The editor windows are under this "debugging" button but I wouldn't really classify them as debugging.

I am not bothered whether the default item is changed or not, so its up to you.

**Comment by Gymnasiast** [comment]
I agree. The only reason I have debugging tools on is for easy access to Object Selection and the Tile Inspector. Moving them to the Cheats button might be a better idea. But perhaps other people have a better idea.

**Comment by IntelOrca** [comment]
Object selection should probably only be available in sandbox mode.
