### ISSUE TITLE
Rotate queue lines

### ISSUE THREAD

**Issue by Phyxion** [OpenRCT2/OpenRCT2#2773]
It would be nice if we could rotate the footpath queue lines (e.g., with Z) so we can decide where the entrance should be sticked to instead of having to remove the adjacent path first.

**Comment by Gymnasiast** [comment]
(Please hold back a bit with your suggestions. We have way to many already, and plenty of implementation and bug fixing still to do.)

**Comment by Phyxion** [comment]
I understand that it's a bit much perhaps but when I think of it I'd rather write it down than forget all about it.

**Comment by Gymnasiast** [comment]
Write it down in a document on your own computer then. That's what I do. This issue tracker is getting swamped with feature requests.

**Comment by Phyxion** [comment]
Alright, for next time :+1:

**Comment by Gymnasiast** [comment]
This is now possible with Broxzier's recent tile inspector improvements.
