### ISSUE TITLE
Staff areas not working in multiplayer

### ISSUE THREAD

**Issue by Phyxion** [OpenRCT2/OpenRCT2#2777]
They walk all over the place.

**Comment by duncanspumpkin** [comment]
This is a duplicate of #2275

**Comment by Phyxion** [comment]
Is it a duplicate? It might be related to the same but the one you referenced talks about crashes. I can see the area's assigned but the staff is just ignoring them.

**Comment by duncanspumpkin** [comment]
Its completely related once #2275 is fixed it will fix this.

**Comment by IntelOrca** [comment]
Basically anything to do with staff = not work in multiplayer. The whole code around staff and peep movement needs to be completely re-worked so its not necessary to have multiple issues about it.
