### ISSUE TITLE
Assertion failed in sawyercoding.c line 423

### ISSUE THREAD

**Issue by carlu93** [OpenRCT2/OpenRCT2#2778]
Playing Forest Frontiers the game crashed unexpected. This happened to me once. Don't know whether this occurs in this scenario only. 

Game Version is v0.0.4-develop build 64e17cc. This is my first Issue. I hope this is enough data for you :)

Edit: Just got it the second time when loading the savegame

[Forest Frontiers.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/96278/Forest.Frontiers.sv6.txt)
![assertfailed](https://cloud.githubusercontent.com/assets/16781908/12425752/96b1f518-bed6-11e5-96b1-845ff29b46dd.JPG)

**Comment by runelaenen** [comment]
There are a lot of cases of this reported in the last few hours.
https://openrct2.org/forums/topic/802-assertion-failed/
