### ISSUE TITLE
Description in the text input window not properly centered

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#2786]
Originally reported by @renansimoes in Localisation.
![portuguese-centered](http://s11.postimg.org/qbsy11f2r/SCR8.png)

**Comment by renansimoes** [comment]
Yes, I want to centralize the second line at 

STR_2792    :Por favor, insira o seu nome {NEWLINE}para a lista de cenário:

Maybe add a new tag for {NEWLINECENTERED} or {NEWLINE}{CENTER}, I don't know.
