### ISSUE TITLE
Servers crash on builds above 1677 when players join

### ISSUE THREAD

**Issue by gergy008** [OpenRCT2/OpenRCT2#2790]
(Playing on Windows 10)

After updating to 1677, servers will crash as soon as a player joins. This could be because players cannot receive the compressed maps that the higher builds provide, I do not know. This also means that players are unable to join servers that have a mismatched build.

I wish I had more information to give you but I am new to this. Let me know if you need anything!

**Comment by janisozaur** [comment]
It has been fixed, switch to official builds, as the builder you're using is broken.

**Comment by Gymnasiast** [comment]
Here is a link to what's currently the newest official build: https://ci.appveyor.com/api/buildjobs/7hfqdtwmevkqata5/artifacts/artifacts/openrct2.zip

We're working with the openrct2.com maintainer to fix those build as well. In the meantime, please update both your server and your clients to the build linked above.

**Comment by JarnoVgr** [comment]
Fixed. Can be closed.
