### ISSUE TITLE
Click on version hash to copy

### ISSUE THREAD

**Issue by devnoname120** [OpenRCT2/OpenRCT2#2794]
Since the build number is not longer displayed, users have to type the git hash when opening an issue. But this is tedious to do by hand, because the string is long and most users don't know that providing only the beginning is enough.

This is why I suggest that the hash in the main menu be clickable. It would prompt a confirmation box to make sure that the user indeed wants to copy it (so that his clipboard is not erased if he does not want to).

**Comment by marijnvdwerf** [comment]
Wouldn't a 'copy to clipboard' button (or even a tooltip) be more obvious than a random label which has a click action attached? That way you also don't need another confirmation prompt.

**Comment by devnoname120** [comment]
A tooltip when the mouse is hovering is what I had in mind. Honestly, I don't know if it would really be necessary to put a confirmation prompt, the chance that the user clicks on it by mistake is low, while it will be annoying for normal users to have a confirmation box prompting each time they want to copy the  number.
