### ISSUE TITLE
sv6 struct?

### ISSUE THREAD

**Issue by kevinburke** [OpenRCT2/OpenRCT2#28]
how well does the ride structure in rct2 match up to the data in tycoon technical depot? seeing this bit check for a giga coaster:

```
.text:006C5275     check_cable_lift_hill:                  ; CODE XREF: sub_6C511D+146j
.text:006C5275 01C                 cmp     bp, 7Bh ; '{'
.text:006C5279 01C                 jnz     short loc_6C528B
.text:006C527B 01C                 test    dword ptr [esi+1D0h], 10000h
.text:006C5285 01C                 jnz     one_cable_lift_per_ride
```

which would seem to check the 17th bit of 1D0 of the ride for a cable lift. I know this is the right place because the on ride photo check is in the 5th bit, same as the data in "Ride Structure", seems to match up with these bits from "Ride Structure" in technical depot:

> 002,3 : bit 0 = train(s) on track, bit 1 = tested; bit 2 = test in progress; bit 3 = don't show raw stats; bit 4 = pass through station without stopping; bit 5 = On-Ride photo; bit 6 = ?; bit 7 = broken down; bit 10 = crashed; bit 12 = ever been opened; bit 13 = play music; bit 14 = construction/demolition prohibited (indestructible ride); bit 15 = demolition prohibited (used when there are indestructible track pieces)

so maybe they moved all that data to 1D0 because they needed more bytes. here's the code for on ride photo

```
.text:006C525F     check_on_ride_photo:                    ; CODE XREF: sub_6C511D+135j
.text:006C525F 01C                 cmp     bp, 72h ; 'r'
.text:006C5263 01C                 jnz     short check_cable_lift_hill
.text:006C5265 01C                 test    dword ptr [esi+1D0h], 20h
.text:006C526F 01C                 jnz     one_on_ride_photo
```

either way, would be good to start putting together a wiki (or using the IDC file) to document this sort of thing.

**Comment by marcotc** [comment]
I tried playing with committing the IDA file locally and git is not happy with it.
It is a binary file with some plain text on it, but mostly binary. Git considers it binary and can't diff. Also, git will always store the whole thing again for every single change we do, which will make the repository quickly impractical to work with.
Github suggests using [Git Large File Storage (Git LFS)](https://help.github.com/articles/versioning-large-files/), which they support. This would keep only a "link" to the large file in the main repository, and keep the content somewhere else. Git LFS abstracts that from you, supporting regular git commands to work the file, it's all seamless.
Having it available easy would be of great benefit to everyone. Still, it's a binary file, very hard to code review, so I assume only "trusted" developers would would be allowed to commit it.

**Comment by JeroenSack** [comment]
If you open it you can see that it is not really a binary file, it is just a lot of plain text and I guess git reads it as binary just because it is larger than 5MB. I think we actually had a discussion about this in another place and I tried to make a application to split them in a smart way, but I never got really far with that. My idea was to split them in files of about 2.5MB and then when somethings gets added in between you those files would grow till they exceed 5MB at which point they would be split in two files of 2.5MB again.

**Comment by marcotc** [comment]
We might be talking about different files, my "openrct2.idb" is binary, here's the first line of it:
    IDA1  >   Cà%H Q    M€QÝÌ»ª     öðËÆÚS ¾‹ý,    KˆÖ²        à%
Anyway, for storing large files I have used Git LFS before and it does exactly what it advertises. Considering github supports it, I don't see any reason for us to create our own custom solution.

**Comment by JeroenSack** [comment]
Ok, the file I got from IntelOrca last time was an IDC file (one year ago, have not been active here for some time) which is only plain text, so this is the one I would put under source control.
