### ISSUE TITLE
Typing in certain characters causes strange text rendering.

### ISSUE THREAD

**Issue by LRFLEW** [OpenRCT2/OpenRCT2#2822]
From what I can tell, the problem is that entering any ASCII characters above 'z' (specifically '{', '|', '}', and '~') in most (all?) locations where you can type in the game causes problems with string rendering because the game considers them control characters. This has been noticed in multiplayer chat, ride renaming, and when entering a new name in the load-save dialogue.

**Comment by pizza2004** [comment]
I just tested this on a multiplayer server and it's very strange indeed.

**Comment by IntelOrca** [comment]
Similarly typing standard double quotes writes the end quotes. So even more intelligent logic is required to perhaps put start and end quotes automatically.

**Comment by Overv** [comment]
The non-quote characters should be fixed for all inputs with the same fix as #2892.

**Comment by tupaschoal** [comment]
Still happens on v0.3.1

**Comment by Gymnasiast** [comment]
Fixed by https://github.com/OpenRCT2/OpenRCT2/pull/16600 and https://github.com/OpenRCT2/OpenRCT2/pull/16580
