### ISSUE TITLE
Chairlift car stuck on end of first station

### ISSUE THREAD

**Issue by PureTryOut** [OpenRCT2/OpenRCT2#2827]
When running a chairlift, at some point on of the cars get stuck on the end of the very first station of the ride.

![Broken Chairlift screenshot](http://i.imgur.com/lrmhp5z.png)

I've attached a savefile. To get this behaviour again, close the ride and reset the cars. Then re-open or test the ride again.
[Trinity Islands.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/106721/Trinity.Islands.sv6.zip)

**Comment by Bobbaone** [comment]
If you Limit the Wagons to under 28, its working fine...

**Comment by PureTryOut** [comment]
Not for me. As long as one of the wagons has to rotate on the end of the station, that wagon breaks. No matter what amount of wagons you limit it to.

**Comment by Joshwoo69** [comment]
A possible splution os to make chains lifts have no collision / the end block has no collision with the fence.

**Comment by duncanspumpkin** [comment]
Man that took ages to work out. Found the solution eventually though.

**Comment by PureTryOut** [comment]
Good job, thanks man!

**Comment by Joshwoo69** [comment]
Woot!
