### ISSUE TITLE
Evergreen Gardens Maze Crash

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#2828]
Something is breaking in the GAME_COMMAND_SET_MAZE_TRACK code causing an infinite loop. See https://www.reddit.com/r/rct/comments/42uk7i/premade_maze_layouts_crashing_in_emerald_greens/ for more information on how to reproduce.

Reproduceable on e7545983f15cf56ca22a9e9b04510421842d7b0d
Doesn't happen in vanilla.

**Comment by marijnvdwerf** [comment]
I'm getting crashes with premade mazes in Six Flags Holland too. Freezes when moving the ghost to this area.

![image](https://cloud.githubusercontent.com/assets/737603/12639458/cefafb48-c5a4-11e5-9db3-931a0ad5e53a.png)

**Comment by duncanspumpkin** [comment]
Yeah i have a feeling its the code for placing the maze track is slight broken for when there is a collision. I expect it will go into an infinite loop if you try build a maze anywhere that has a certain type of collision.

**Comment by PureTryOut** [comment]
I was about to report this as well. For me it happened on Katie's Dreamland, so it's not scenario specific. It happens when trying to build a pre-made Maze while it collides with something.

**Comment by marijnvdwerf** [comment]
It happens by simply moving the ghost over there and not pressing anything,
right?
Op do 28 jan. 2016 om 14:55 schreef PureTryOut <notifications@github.com>

**Comment by PureTryOut** [comment]
Sorry, yes, by moving the ghost over a collision.

**Comment by marijnvdwerf** [comment]
Bug appears to be introduced in f8507ec93e8d9b5597923ccbdf92cef66d35fc39.

**Comment by marijnvdwerf** [comment]
@PureTryOut @duncanspumpkin Can either of you validate my fix?
