### ISSUE TITLE
Esc to close the most recent open window

### ISSUE THREAD

**Issue by Tgo1014** [OpenRCT2/OpenRCT2#2834]
Every time I place many shop's I must close each windows clicking on the "x" button.

Would be cool if the Esc button close the most recent open window I guess that that should help to close faster all the open windows.

**Comment by devnoname120** [comment]
The backspace key already allows one to close the most recently opened window.

But the way, it would be great to have "Del" as a hotkey for closing all windows, this would make it consistent with OpenTTD.

**Comment by IntelOrca** [comment]
Just change the shortcut in the shortcuts window. We won't change the defaults because most RCT players are familiar with the default settings.
