### ISSUE TITLE
Attraction entrance positioning affects customer throughput

### ISSUE THREAD

**Issue by marcotc** [OpenRCT2/OpenRCT2#2835]
Even small changes to the position of where the queue intersects with regular paths can have huge impact on ride attendance. See https://www.reddit.com/r/rct/comments/435h61/friendly_reminder_that_smart_attraction_entrance/ for reference.
I believe that this behaviour deserves at least some investigation.

**Comment by duncanspumpkin** [comment]
This is just how the ai works. The direction of travel is always favored if available.
