### ISSUE TITLE
Can't build down-to-level-sharp-turn-flat-to-banked track piece (build window error)

### ISSUE THREAD

**Issue by jensj12** [OpenRCT2/OpenRCT2#2838]
https://openrct2.org/forums/topic/846-track-building-inconsistency/

A piece that's available in vanilla can't be built in OpenRCT2. You can build the same piece level-to-up-sharp-turn-banked-to-flat or when building in reverse mode. Most likely an error in the build window (button not available when it should).

**Comment by Gymnasiast** [comment]
I seem to remember this also occurring in vanilla, with the piece in question only being available when building in reverse mode.

**Comment by Gymnasiast** [comment]
#3361 is a duplicate, but I'm closing this one as #3361 contains more information.
