### ISSUE TITLE
0.0.4 builds 1630+ crashing on WineHQ

### ISSUE THREAD

**Issue by xalalau** [OpenRCT2/OpenRCT2#2840]
0.0.4 Build 1629 is the latest playable version for me.
I'm on a Ubuntu 14.04.03 with PlayOnLinux + Wine 1.9.2-staging.

**Comment by PFCKrutonium** [comment]
Why not use the Native Linux Builds? https://openrct2.org/downloads/latest/develop

**Comment by xalalau** [comment]
Nice, I'm going to test it! I was downloading from here: https://openrct2.com/download = No Linux builds.

**Comment by PFCKrutonium** [comment]
.net and .com are merging in to .org, so that one will probably be going away sooner or later.

**Comment by xalalau** [comment]
Thank you! http://i.imgur.com/9tTazda.png (y)
Well, native >>>>>>> Wine, but I think that my report is still valid.
Anyway, this is a great project! I'm loving it!
