### ISSUE TITLE
Option to change language of default ride name

### ISSUE THREAD

**Issue by JarnoVgr** [OpenRCT2/OpenRCT2#2842]
I tend to play OpenRCT2 in Dutch, but always change the ride names to English. An option to set the language of default ride names would be appreciated.

**Comment by Gymnasiast** [comment]
I'm against introducing this. It's additional complexity for a feature that I wouldn't expect to see much (or even any) use besides the OP, and for something that does not take that much time.

**Comment by JarnoVgr** [comment]
I would also see this being required for group parks, since they have different default names per player (because of different languages). And how complex would this be?

**Comment by Gymnasiast** [comment]
By default, a looping roller coaster that has not been named should show up as Looping Roller Coaster 1 for an English client and as Stalen achtbaan 1 for a Dutch player, unless I'm very mistaken.

**Comment by IntelOrca** [comment]
@Gymnasiast that is correct, or at least that is the expected behaviour. The string ID is set to the string ID of the ride type - the value depends on the language.

**Comment by Gymnasiast** [comment]
I'm afraid this will be closed. The reasons for it are:
- Renaming a ride does not cause much extra work, so the benefit is very small
- It would mean additional complexity in loading an extra language just for the purposes of ride naming, as well as extra interface cluttering.
- Very few people seem to want this.
