### ISSUE TITLE
Multiplayer - Segfault when trying to load WW/TT scenario missing object

### ISSUE THREAD

**Issue by octaroot** [OpenRCT2/OpenRCT2#2843]
> Note: I originally posted this as a comment on issue #2670, but since it's closed and didn't get bumped, I created this new issue (sorry if that doesn't fit the workflow).

Original comment:
This is still a problem in multiplayer, I believe. My game has RCT2 objects only, no expansions - trying to connect to a multiplayer game (which includes these missing objets) causes a segfault.

I'm running my own build (commit  083ec35362f4d16c2bb816bc7f2538f67532ad5f) on Linux, but this also happens when running a Windows build under Wine (v0.0.4-develop build c79541a, OpenRCT.com).

**EDIT**: Expected behavior (according to me) is displaying an error message and returning to the main menu/network game selection (point is - the game not crashing). Current situation is very confusing to users, who don't have their console windows open, as the game just crashes without any messages.

```
$ ./openrct2 
WARNING[/tmp/openrct2/OpenRCT2/src/rct2.c:567 (get_system_info)]: Function get_system_info at /tmp/openrct2/OpenRCT2/src/rct2.c:567 is a stub.

WARNING[/tmp/openrct2/OpenRCT2/src/platform/shared.c:935 (platform_load_cursors)]: Function platform_load_cursors at /tmp/openrct2/OpenRCT2/src/platform/shared.c:935 is a stub.

WARNING[/tmp/openrct2/OpenRCT2/src/network/network.cpp:1695 (Client_Handle_MAP)]: Received zlib-compressed sv6 map
ERROR[/tmp/openrct2/OpenRCT2/src/object.c:171 (object_load_chunk)]: object not installed
ERROR[/tmp/openrct2/OpenRCT2/src/object_list.c:562 (object_read_and_load_entries)]: failed to load entry: CROCFLUM
ERROR[/tmp/openrct2/OpenRCT2/src/object.c:171 (object_load_chunk)]: object not installed
ERROR[/tmp/openrct2/OpenRCT2/src/object_list.c:562 (object_read_and_load_entries)]: failed to load entry: DIAMONDR
 < a couple more of these, you get the idea >
ERROR[/tmp/openrct2/OpenRCT2/src/object.c:171 (object_load_chunk)]: object not installed
ERROR[/tmp/openrct2/OpenRCT2/src/object_list.c:562 (object_read_and_load_entries)]: failed to load entry: MEDIPATH
Segmentation fault
``

**Comment by duncanspumpkin** [comment]
This is expected behaviour. We can't/shouldn't distribute the exapansion assets over the network. Admitedly a nicer error would be appropriate.

**Comment by octaroot** [comment]
Yes, I should have clarified that in my first comment - Expected behavior is displaying an error message and returning to the main menu/network game selection (point is - not crashing). Current situation is very confusing to users, who don't have their console windows open, as the game just crashes without any messages.

**Comment by rbozan** [comment]
#2246
