### ISSUE TITLE
Enable setting visibility flag on tracks once Possible

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#2846]
Perhaps a toggle in the build window that can be enabled in cheats?

**Comment by duncanspumpkin** [comment]
It would be a bit of a pain to implement this.

**Comment by IntelOrca** [comment]
Not to mention against our target implementation which would be to just set a visibility flag on the elements themselves.

**Comment by PFCKrutonium** [comment]
Hmmm, then perhaps I should rename this to "Enable setting visibility flag on tracks" so that it won't get lost.

**Comment by IntelOrca** [comment]
It will probably get lost amongst the 300 other feature requests.

**Comment by PFCKrutonium** [comment]
This has since been done via the Tile Editor, enabling placing invalid objects to cancel drawing.
