### ISSUE TITLE
Server list window: Tooltip shouldn't appear there

### ISSUE THREAD

**Issue by danidoedel** [OpenRCT2/OpenRCT2#2848]
![2016-01-31 12_12_04-openrct2](https://cloud.githubusercontent.com/assets/10995998/12701784/42fb264a-c815-11e5-8d40-ef0e57ee21c5.png)

The tooltip should only appear if you hover the traffic lights on the right.

Build: 43b723a411301921ee1c1cd9de0a6e3cab111e55

**Comment by janisozaur** [comment]
@danidoedel I agree with your point, but can't trigger it. Can you provide some more information how can I make the tooltip appear where you're showing?

**Comment by janisozaur** [comment]
Ah! Found it! There's one pixel tall line just above the first entry.
