### ISSUE TITLE
Theme window is glitchy

### ISSUE THREAD

**Issue by danidoedel** [OpenRCT2/OpenRCT2#2850]
![strange 2](https://cloud.githubusercontent.com/assets/10995998/12702265/a6f8cb80-c823-11e5-995c-408d9c2b58b4.png)

![strange 1](https://cloud.githubusercontent.com/assets/10995998/12702270/cfa1cbcc-c823-11e5-851a-638339d0a23d.png)

Build: 43b723a411301921ee1c1cd9de0a6e3cab111e55

**Comment by IntelOrca** [comment]
Does this only happen on title screen?

**Comment by danidoedel** [comment]
No, happens during a game too.

**Comment by Overv** [comment]
It also creates trails when dragging it around:

![](http://i.imgur.com/oCtVY22.png)

**Comment by IntelOrca** [comment]
![image](https://cloud.githubusercontent.com/assets/1482259/13558256/f970503c-e3f7-11e5-8ebe-0b47947b380e.png)

Selecting a colour dropdown near the top leaves a staff member sprite.
