### ISSUE TITLE
Missing field for entering "winners name"

### ISSUE THREAD

**Issue by carlu93** [OpenRCT2/OpenRCT2#2851]
![scr4](https://cloud.githubusercontent.com/assets/16781908/12702688/9f378600-c82f-11e5-9545-e76ada9349eb.png)
After winning the message box opens up, but i can't enter my name anywhere. The scenario dialog shows "???" as winner. 

Build: 43b723a

**Comment by Christipher** [comment]
This sometimes occurred in the original game with custom scenarios - this bug however in the original game was very rare...

**Comment by danidoedel** [comment]
You can enter your name only if you break your highscore (company value), but it should indeed not overwrite the old score then.

**Comment by mrtnptrs** [comment]
Now it always shows the option to enter your name, but also the second time you win the scenario and if you don't type in your name, the scenario dialog will show "???" as winner. But the second time, you shouldn't be able to enter a name indeedly and de name and score shouldn't be changed. Maybe the title of the bug report should be changed and reflecting this.

**Comment by IntelOrca** [comment]
Logic has changed since, a new bug can be opened if still an issue.

**Comment by Nubbie** [comment]
[Got reported on the forums ](https://openrct2.org/forums/topic/2275-cant-finish-scenario-no-putting-in-name-button/#comment-12515) when someone tried the `Stable 0.0.5` version which is before this got closed, re-open?

**Comment by IntelOrca** [comment]
I can't work out what causes this. I needs reliable steps.
