### ISSUE TITLE
groups file dedicated server

### ISSUE THREAD

**Issue by NL-skillz-NL** [OpenRCT2/OpenRCT2#2853]
ive manually added a groups.cfs into to directory and the game does actually recognize is. except that because the default = spectator i cant even add myself to user. can you code a groups.cfg or give me an idea how i should that way i can upload the code for implementation.

**Comment by Gymnasiast** [comment]
It's hard to understand what you mean precisely. If you're still faced by this issue, could you explain it more clearly? It's okay to do so in Dutch if that helps.

**Comment by IntelOrca** [comment]
I didn't see this before... group configurations are stored in binary, not ini. You can't easily edit them outside the game. And there is currently no way of remembering permissions, not until we have spoof protection which is planned.
