### ISSUE TITLE
Scenario path text overflows dialog when RCT1 font is selected in "Themes"

### ISSUE THREAD

**Issue by flk92** [OpenRCT2/OpenRCT2#2855]
If "RCT1 Scenario Selection Font" is checked in "Themes" with the debugging tools enabled, the path text can overflow the scenario selection dialog, causing a graphical glitch.

![text-overflow](https://cloud.githubusercontent.com/assets/1652132/12706970/86f02ea4-c874-11e5-8378-516d5286c188.png)

Edit: built from git branch 'develop', d86bf8f

**Comment by tisoalvarez** [comment]
Mr. bones is pleased.

**Comment by Christipher** [comment]
Noticing the tab presented all of the original Scenarios in RCT2 were initially unlocked - they had no Boolean to them... you could do them in any order you pleased...
