### ISSUE TITLE
[Feature Request] Require permission for placing a bunch of scenery items at random

### ISSUE THREAD

**Issue by wolfreak99** [OpenRCT2/OpenRCT2#2858]
The option in the scenery window where you can place alot of items at random should either be disabled or require permission to use.

http://imgur.com/es4e93K 
This is the server that pointed out this feature can be extremely abused.

A side request could be for a feature that allows you to remove scenery items or replace it with another chosen item. I'd add this portion myself but I have windows 7 and I am unable to install visual studio 2015 on it.

**Comment by IntelOrca** [comment]
Why are you unable to install VS2015?

**Comment by janisozaur** [comment]
This sounds very fuzzy, you can do the same kind of thing even without the random-placement tool, with manual placement of scenery or rides.

How about instead we have some sort of rate-limiting system, where the server will accept only X commands over Y ticks? That sounds much more doable and possibly alleviating this issue.

**Comment by wolfreak99** [comment]
@IntelOrca  I'm not sure why.. I know I am running a "borrowed" version of Windows 7 (properly cracked too), but I've had 2 installs of win7 and the first ones windows updates eventually broke and i'm not able to download updates. The one I am running now is, from what i recall, getting updates okay, but for some reason VS2015 just won't install, it'll say that I cancelled the install even though I didn't.
I am not all that literate in explaining how it doesn't install, so i just recorded a video of me attempting to install it and uploaded the log as well..  I'm  not sure how to private message on here so I'll paste it here.
https://vid.me/8pml

http://www.mediafire.com/download/w902o1albwaipwj/dd_vs_community_20160204085504.log

Dude if you could help me get this installed, that'd be amazing

**Comment by IntelOrca** [comment]
Umm ok I don't know why that is failing. Maybe you should just get Windows 10 legitimately and have a nice new clean OS. I am sure VS2015 will run then.

For now you can just only give trusted players the ability to place scenery. Otherwise you will just have to wait for a developer to implement this request.

**Comment by PFCKrutonium** [comment]
@wolfreak99 If you use RemoveWAT your not properly cracked. That is all I have to say on the situation.

**Comment by duncanspumpkin** [comment]
@PFCKrutonium i'd prefer we didn't discuss OS cracking on here.

**Comment by PFCKrutonium** [comment]
Understandable.

**Comment by wolfreak99** [comment]
the difference between manual placement and the random placement, is people wouldn't be as likely to randomly place stuff randomly one by one, and plus could be kicked quicker.

**Comment by Broxzier** [comment]
Update: This PR: #3241 seems to resolve to this issue.
