### ISSUE TITLE
Incorrect number of cars rendered

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#2879]
![screenshot 238](https://cloud.githubusercontent.com/assets/3945538/12795049/3a172178-ca86-11e5-998c-af20a7e048b7.png)

Seems to be limited to this type of coaster. Guests still ride it fine.

In this case, it was one train with one car, and one train with two cars.

**Comment by Gymnasiast** [comment]
Is the bug in vanilla?

**Comment by danidoedel** [comment]
No

**Comment by PFCKrutonium** [comment]
This is only in Open2

**Comment by danidoedel** [comment]
Yep and if you set the number of trains to 1, that train won't start moving.

**Comment by duncanspumpkin** [comment]
Can you check this if this is fixed as it sounds identical to #3052

**Comment by PFCKrutonium** [comment]
Last time I played MP (Less than a week ago) it was still an issue.

**Comment by danidoedel** [comment]
Fixed :+1:
