### ISSUE TITLE
Disable left/right hand curve buttons after steep drop and then the level piece

### ISSUE THREAD

**Issue by Phyxion** [OpenRCT2/OpenRCT2#2881]
**Vertical Drop Roller Coaster**

Select the level piece and it'll also enable the left/right hand curve. This shouldn't be selectable as this piece does not exist and is just the 'no roll' piece.
![scr11](https://cloud.githubusercontent.com/assets/7643972/12814532/f5fa0838-cb3f-11e5-959a-4e2d1e06a108.png)

(This is done correctly for the normal 'slope down' piece)

**Comment by e-foley** [comment]
This is an original bug, right?  If I recall, this was a big problem in the orignal RCT 1 because the game would let you place a turn afterward and count your ride as a complete circuit, but the vertical drop coaster would crash when testing at the interface between the drop and the corner.
