### ISSUE TITLE
Broken Scenarios and Unremovable plugin.dat

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#2884]
So today I decided to try playing OpenRCT2 again. However any attempt to boot it up results on me receiving this message:
![screen shot 2016-02-04 at 10 09 38 am](https://cloud.githubusercontent.com/assets/4167951/12819047/6e9e794a-cb27-11e5-905f-ff518c986bf8.png)
So I go into the Data folder of the RCT2 directory and promptly delete plugin.dat, however the message does not change.
The game still loads properly, however there is one scenario that refuses to start up: "Asia - Great Wall of China Tourism Enhancement", because apparently the files for it are missing in my copy.
![screen shot 2016-02-04 at 10 12 24 am](https://cloud.githubusercontent.com/assets/4167951/12819141/d8173498-cb27-11e5-952a-c96e2f461a40.png)

**Comment by IntelOrca** [comment]
plugin.dat is loaded from documents\OpenRCT2, not RCT2 data. Th other issue could be genuine too, maybe you don't have that required object.

**Comment by Superjustinbros** [comment]
Okay, removed the proper plugin.dat, but when I startup the game again the error comes back. Also when I do delete it, it points to an "Object load failure" from the file "RIDETESJ"

As for the missing object, I dunno how such a thing could happen, considering it's one of the default scenarios.
Heck I don't know what I could've done to accidentally remove such data from the game or make it unreadable by other means.

**Comment by IntelOrca** [comment]
Try deleting the RIDETESJ object.
Try reinstalling your game to get your missing DRAGON object back. That is if you really are missing it - check your objdata folder to see if it exists.

**Comment by Gymnasiast** [comment]
I have that RIDETESJ file as well. It has "Sky bucket cars" as its description.

**Comment by Superjustinbros** [comment]
Strangely, I have the "DRAGON" file installed and put into the correct folder; but the game for some reason doesn't recognize it.

As for RIDETESJ, I can't seem to locate it in any of my game's folders.

**Comment by Superjustinbros** [comment]
I got another error regarding one of the files added by Wacky Worlds.

The scenario "Europe - Renovation" crashes when i load it because like the DRAGON error above, it somehow is unable to read the BIGBEN file.

Odd considering how in the scenario folder, the two scenery categories that the two "Missing/Unreadable" objects are located it (the Asian and European themes, if I'm not mistaken) appear in the Scenario Editor's Object Selection menu (despite the European theming showing the "Too Many Objects Selected" error when checked even when no other theme that isn't auto-checked is selected).

**Comment by Superjustinbros** [comment]
The only idea I could have in regards to this would be if one of the many, many other DAT's I downloaded from these online save files somehow overwrote or have information that clashes with the Dragon and BigBen files.

**Comment by Gymnasiast** [comment]
Since this report, the system has been turned on its head. Could you verify this problem still exists?
