### ISSUE TITLE
Sign placed on queue that's not connected to an entrance

### ISSUE THREAD

**Issue by Phyxion** [OpenRCT2/OpenRCT2#2887]
Sorry for the long video, I discovered this while recording another bug.
It happens around 23 seconds and also another time later in the video.

I could not reproduce this on vanilla.

Video:
https://vid.me/geDP

![rct2bug1](https://cloud.githubusercontent.com/assets/7643972/12845900/72cb260c-cc09-11e5-9cd7-911fd1babd19.png)

[Ghost Town.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/119076/Ghost.Town.sv6.txt)

**Comment by duncanspumpkin** [comment]
Doesn't look to be a map invalidation issue looks to be a proper bug.

**Comment by danidoedel** [comment]
After zooming out and in again the entrance sign gets drawn correct. Maybe this helps:

![path](https://cloud.githubusercontent.com/assets/10995998/12848879/bb161aa8-cc1c-11e5-9726-ef083ce07341.gif)

**Comment by duncanspumpkin** [comment]
okay maybe it is a map invalidation bug.
