### ISSUE TITLE
Coaster shows up in Rides window even if it isn't built yet

### ISSUE THREAD

**Issue by Phyxion** [OpenRCT2/OpenRCT2#2888]
If you build a track with a predefined design, it'll show up in the Rides window when you haven't even built it yet. It'll show as 'Closed'.

**Comment by duncanspumpkin** [comment]
Yes that is how the game allocates a ride. We could improve the ride list to check for something else that would confirm it exists.

**Comment by IntelOrca** [comment]
This is expected behaviour, its also the same as when you build a custom track. The ride is in the ride list before you place the first track piece.

**Comment by Phyxion** [comment]
But it does not make sense from a user point of view.

**Comment by Nubbie** [comment]
Duplicate off #578?
