### ISSUE TITLE
Solution for long dropdowns

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#2889]
This is split off from #2403.

@IntelOrca's original comment:

> I think large dropdowns are a common problem. Particularly when you enable all vehicles for any ride. So maybe a generic window for selecting things from long lists complete with search feature?

@daihakken's original comment:

> Dropdown with scroll bar and type to locate feature would be also great to that.

**Comment by IntelOrca** [comment]
I find dropdowns with scrollbars somewhat user unfriendly as you can accidentally move your mouse off the dropdown causing to hide. Although with mouse scroll ability it can work reasonably well.

However should there be lets say 100 items, then not even a scrollable dropdown is a good idea. It would have to be a listbox of some kind and maybe the ability to search.

Another case we might have for this is when we have custom music. The player might have many music tracks which would be too many for the existing dropdown.

And lastly, another UX enhancement to these ideas are to have recently used. Often when you select something you will select it again soon (so recently used items at the top of a list are useful).

**Comment by Patrik356b** [comment]
Sometimes it could be useful to categorize the drop down menu into submenus. 

Anyhow searching in drop down menus would be great

**Comment by Gymnasiast** [comment]
I think the track list approach would work here. It already does everything we need: it allows the user to pick one item, and it supports scrolling.

**Comment by Gymnasiast** [comment]
Now #5975 is merged, I'm going to consider this solved.
