### ISSUE TITLE
idea: IRC integration.

### ISSUE THREAD

**Issue by FM1337** [OpenRCT2/OpenRCT2#2890]
This feature would be similar to the twitch intergration feature, but rather than connecting to twitch, it would connect to a specified irc network.

It would have a bot connect to a specified irc network and join a specified irc channel, and it fetch the user list in the channel and begin naming some guests after the users in the chat (like the twitch intergration does) and could also read chat messages as announcements (like the twitch intergration does) 

But where it would differ with the twitch intergration (possibly) is it would say announcements like Ride has broken down or Guest has died in the irc chat when it happens.

I know this is a lot to ask, but it's only a suggestion/idea maybe to consider adding in the future.

**Comment by PFCKrutonium** [comment]
I think that is a neat idea, but the issue I can see with that would be 
people spamming IRC channels with messages.

**Comment by FM1337** [comment]
"I think that is a neat idea, but the issue I can see with that would be
people spamming IRC channels with messages." 
To combat that, you could put in a rate limiter. 
Or if you're thinking that the chat messages said by people in the chat would be echoed by the bot, it could be set not to echo these messages.

**Comment by devnoname120** [comment]
Is there an actual use case to this?
I don't see how posting news about a park in a IRC channel would be useful. With Twitch, there is a stream of the game, so there is interaction with users and it makes sense, but I don't see how it would be useful for IRC.

**Comment by PFCKrutonium** [comment]
If I am not mistaken, some twitch streamers will sometimes have more 
than one chat - they will have the Twitch stream, but they will commonly 
have another chat too. Plus, there is more than just twitch out there, 
so being able to support IRC in general will allow compatibility with 
other streaming sites as long as they have an IRC interface for their chat.

**Comment by FM1337** [comment]
Plus this would also be helpful if you're hosting a server and you wanna see who connects while you're away.
