### ISSUE TITLE
Adding a tilde (~) at the end of a name causes some weirdness.

### ISSUE THREAD

**Issue by RaymondTracer** [OpenRCT2/OpenRCT2#2892]
Its hard to explain but it looks like it causes some temporary string corruption

Below are two examples, the "corruption" seems to happen when you're moused over something and you move the camera. It also happens in places like guest thoughts. 

![ss 2016-02-06 at 02 33 30](https://cloud.githubusercontent.com/assets/6290310/12864478/973cde46-ccdf-11e5-8df8-f903cde835cb.png)
![ss 2016-02-06 at 02 32 43](https://cloud.githubusercontent.com/assets/6290310/12864479/973ff950-ccdf-11e5-9738-a3ff58b0bbc7.png)

Here's a save file http://puu.sh/mXxoS/dca5484378.zip

and the version of OpenRCT2 I'm running is 0.0.4 build 1073 (a8eca93) from appveyor.com

**Comment by Overv** [comment]
Corruption occurs for any ASCII character with byte value 123 or higher (also `{`, `|` and `}`) because those are treated as format codes by `utf8_is_format_code`. The original game simply doesn't allow these characters in names by silently dropping them.

**Comment by chrismilne300** [comment]
![image](https://cloud.githubusercontent.com/assets/1381723/15099260/b42b1336-1548-11e6-909e-8c717ed900d8.png)
Still an issue on build fc6a589

**Comment by Overv** [comment]
Looking into this right now.

**Comment by chrismilne300** [comment]
I did load the save, but I also tried on a new game. While the game doesn't allow you to enter a ~ you can however copy and paste it, and while not displayed in the text box just click ok then it starts glitching as shown in my picture

**Comment by Overv** [comment]
I will add a more robust check.

**Comment by Overv** [comment]
Pull request #3560 should fix this once and for all.
