### ISSUE TITLE
Objectselection filter by also for RCT1, AA and LL

### ISSUE THREAD

**Issue by Horsti12** [OpenRCT2/OpenRCT2#2893]
It would be cool when you could also filter in the object selection for just RCT1, AA and LL things. Just to see what things got added with AA and LL. If you need help with it I could give you a list will all of the things + filenames if you want. For now it would be just enought to just do the Attraction sections, because the other lists are way to big to do it now.

![trmorva](https://cloud.githubusercontent.com/assets/12634026/12866271/eb4c445c-ccc8-11e5-8d4b-17fb7d7ece90.png)

**Comment by Superjustinbros** [comment]
Not a bad idea imo.

**Comment by Horsti12** [comment]
I created a list. If you also need the filename than I could also give you them. It's interesting that RCT2 not really added much new things compared to all other Addons. http://rct.wikia.com/wiki/The_Complete_Rides_List_RCT%2B_RCT2

**Comment by Horsti12** [comment]
You only have to tell me how it would work and than I could provide the list with the needed information.
