### ISSUE TITLE
Add rate limit for notifications

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#2895]
I know we have options to enable/disable notifications already, but how about adding a rate-limiting system?

Consider a "guest is lost" message, if happens more than X times in timeframe Y, you would only get one notification with added counter: "guest is lost (happened X times in last Y)"

**Comment by Gymnasiast** [comment]
There is no 'guest is lost' message. It was removed in vanilla RCT2 due to being irritating. The 'Guests are getting lost' message is intended to serve as a warning that many guests get lost.

**Comment by janisozaur** [comment]
yeah, sorry, it was just meant to serve as an example. Main culprit are messages coming from twitch integration.

**Comment by Gymnasiast** [comment]
If you get too many Twitch messages, it means that either:
- People in the chat are abusing !news.
- Too many Twitch guests are being followed.

In both cases disabling the respective options sounds a whole lot more effective. And we also have the notification settings for fine-grained control.

**Comment by janisozaur** [comment]
if you feel this issue is invalid, then feel free to close. If you think this is worth any more discussion, please apply the label.

**Comment by Gymnasiast** [comment]
I'm just trying to see whether there is anything I'm missing. I don't want to close issues too soon.

**Comment by PFCKrutonium** [comment]
This combined with #2896 would be ideal imo - only notify when a peep completes an action that the user assigned.
