### ISSUE TITLE
Commands to control twitch avatars

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#2896]
Each viewer of a stream, provided twitch integration is enabled, gets their own guest in park. It would be much more interactive, if viewers could control their avatars via twitch chat, at least to some extent.

Possible commands/ideas:
- Enter ride X
- Buy umbrella
- Leave park

**Comment by Joshwoo69** [comment]
!enterride (ridename)
!buy (item or food)
Note: provided that that park has it
!leave
my couple of suggestions for commands.

**Comment by PFCKrutonium** [comment]
!explode

**Comment by Joshwoo69** [comment]
Also add twitch irc bot if you want too (notify the person that XX ride / food / whatever cannot be sat or bought)

**Comment by Gymnasiast** [comment]
Closing this as we no longer have built-in Twitch integration.
(Now handled by the https://github.com/oli414/StreamIntegrationPlugin plugin)
