### ISSUE TITLE
Restarting a game in full-screen causes cursor issue

### ISSUE THREAD

**Issue by marijnvdwerf** [OpenRCT2/OpenRCT2#2899]
When you close the game while in full-screen mode and start it again, the game starts in windowed mode. The game offsets the cursor position somehow, causing the 'clicked position' to be about 30 pixels below the cursor tip.

Tested on OS X 10.11.3

**Comment by mrtnptrs** [comment]
Does this still happen after all the engine changes of the last few weeks and maybe 10.11.5 of OS X brings improvements to SDL support? I can't test this as I have no Mac.

**Comment by tupaschoal** [comment]
I can't reproduce this on a Windows machine. If anyone can on a MacOS, please reopen
