### ISSUE TITLE
Display estimated speed/gforces while building rides

### ISSUE THREAD

**Issue by cmg5461** [OpenRCT2/OpenRCT2#2906]
This would reduce a lot of iteration while building rides. It could be viewable in the cheats window perhaps.

**Comment by IntelOrca** [comment]
I think this goes against RCT's gameplay ethics.

**Comment by RaymondTracer** [comment]
So would anything else in the cheat window, I think it would be good to have it viewable in the cheat window.

**Comment by PFCKrutonium** [comment]
Or even just toggleable in the cheats Window.

**Comment by Gymnasiast** [comment]
I'm not wild about it either.

**Comment by cmg5461** [comment]
Even though this idea seems like it isn't what this game is about, whether you realize it or not, you are doing exactly what this tool could help. When building rides, I take an iterative process of tuning the speeds and gforces from start to finish. By having this data available (You don't need to use it if you don't want to), it would greatly reduce the time spent finding that ideal track placemennat for the ratings you're looking for. This is in no way there to make the game less challenging, as this data is freely available to those who wish to go through the hurdles of finding it. It would be much simpler to know the train will be at 10mph over a hill rather than just missing and rolling back. I understand it takes away from the novelty and nostalgia of the game, but just think about how much quicker you will be able to build rides.

**Comment by Phyxion** [comment]
I like this idea as well. This is especially useful for the scenarios where you need 7.00 excitement rating, only to discover that after a few minutes it takes to get this info that it onloy has 6.95 excitement.

**Comment by PFCKrutonium** [comment]
@Phyxion In that scenario you plop down trees and other scenery and end up with a 7.5.

**Comment by Phyxion** [comment]
Alright, too much excitement then as they are puking all over (and no scenery you can remove) :) Would still be a great feature to have.

**Comment by PFCKrutonium** [comment]
I think your looking for intensity.
