### ISSUE TITLE
Test rides without an entry/exit

### ISSUE THREAD

**Issue by devnoname120** [OpenRCT2/OpenRCT2#2908]
Not sure why this is made mandatory in vanilla.

**Comment by IntelOrca** [comment]
The same reason you can't test an incomplete ride or a ride with incompatible track pieces. Testing a ride means that it can also be opened.

**Comment by devnoname120** [comment]
Ok, maybe it could be added to the existing cheat since it falls in the unfinished ride category.

**Comment by HaasJona** [comment]
I would really like to be able to test rides RCT3-style in ghost mode (without crashing if the train hits a track end). This should be also possible without building entry/exit.

I think when fully implemented this should be a valid normal gameplay feature and not a cheat.

**Comment by IntelOrca** [comment]
@HaasJona there is already an issue for this:
https://github.com/OpenRCT2/OpenRCT2/issues/485

**Comment by HaasJona** [comment]
Yes. Just saying this is probably related. When the ghost trains stuff is fully implemented, it should probably work without entry/exit.

**Comment by IntelOrca** [comment]
@HaasJona not necessarily if there we have 4 buttons (closed, ghost test, test, open).

**Comment by Tgo1014** [comment]
I guess that the major problem with the test at multiplayer for now is the annoying bug that takes another player that was building to your coaster when you test it without finishing

**Comment by devnoname120** [comment]
@Tgo1014 Which version are you using? It should not happen now that cheats are synchronized.

**Comment by Tgo1014** [comment]
@devnoname120 I'm using the lastest version, but another person was complaing that that was happening when I was testing my track
Maybe because he wasnt using the latest version?

**Comment by IntelOrca** [comment]
@devnoname120 how is that related?

**Comment by devnoname120** [comment]
@IntelOrca You are right, if the cheat is disabled, and someone tests a completed ride that crashes, the ride window opens for every players.
But since @Tgo1014 said that he was testing an unfinished ride, I assumed that he was complaining about the cheat.

**Comment by IntelOrca** [comment]
@devnoname120 ok - well its nothing to do with the cheats. Its because the game command for opening a ride is not checking that the player is the player who did the command before scrolling to the track hole.

**Comment by duncanspumpkin** [comment]
#9222 kind of fixed this.
