### ISSUE TITLE
A way to limit trolling in multiplayer

### ISSUE THREAD

**Issue by ItsMikey420** [OpenRCT2/OpenRCT2#2920]
Hello everyone! I've been hosting a public server for the past week now and in that time I have found that a game can be ruined in seconds if a troll decides to mass place scenery objects or mass delete scenery and paths or use the terraform tool to level the landscape to nothing. (which also depletes your cash to nothing)

1. Fyi, I don't want to set a password for my server, I want anyone to be able to join 24/7.
2. I don't want to disable the terraform and water tools all together and ruin it for legit players
3. I don't moderate my games, I have a program I've made that handles map changes every few hours, hence why I don't want to disable some tools all together for the legit players as I'm not on there to give users rights to use those tools.

A fix for this could be:
 - In the user role settings an option to enable/disable mass placement of scenery objects
 - In the user role settings an option to to limit the amount of squares per click when using the delete tool
 - In the user role settings an option to to limit the amount of squares per click when using the terraform tool
 - In the user role settings an option to to limit the amount of squares per click when using the water tool

With these 4 features I and others who run Orct2 servers would be able to set these options for the delete, terraform and water tools down to 1 square at a time, making it impossible for a troll to ruin the map in seconds. Yes, they can still try but it will take a lot longer to do so and if an admin is playing they can be found, stopped and kicked quicker.

Has anyone else that's been hosting Orct2 servers have this problem?

I'd love to get some feedback about these features :D

**Comment by IntelOrca** [comment]
What exactly does your program do?

**Comment by ItsMikey420** [comment]
It's a very basic program but It mainly opens Orct2, and runs through 6 custom maps playing each map for 3 hours. I can also choose how many staff I want it to add, how much money to start off with, post server adverts in chat etc :)

**Comment by devnoname120** [comment]
I think that you can just have trusted moderators, who set users to a special group allowing them to do these actions, while the default group would only allow to build a ride, and other simple things. I think trollers leave the server quickly if they see that they don't have the necessary rights at the beginning.

#2873 would make it convenient, because even if the server crashes or clients rejoin, they would keep their authorizations.

Additionally, you could do frequent autosaves, and add a command to your program so that a moderator can load an older save (for recovering after a mess up).

**Comment by ItsMikey420** [comment]
@devnoname120 I would love to have moderators but you will find mods cant be online all the time, also that feature of saving authorizations is a good idea but it does not fix my problem with trolling and I have not been able to find a version with such a feature.

The auto saves method will not work at all, with it being all automated, if i set it up so it reloads an auto save every 10 minutes it would require everyone connected to rejoin the game again. Not to mention filling up my list of saved games with millions of autosaves.

Its not possible to code something like this (%loadauto x where x is the age of the save in minutes.) with what im using, If I wanted mods to be able to change maps like that id have to give them access to my VPS which I am not going to do.

The only real way of working around this problem is implementing:
1 Being able to enable/disable the delete tool for groups. (Seriously, right now people can destroy WHOLE maps in seconds)

2 Being able to limit the amount of squares per click when using the terraform, delete and water tools. (This way it stops trolls from being able to destroy maps in seconds if Im able to set it to 1 square per click)

**Comment by IntelOrca** [comment]
Closing as #3155 is planned to resolve this.
