### ISSUE TITLE
You guys are killing it

### ISSUE THREAD

**Issue by RobertWHurst** [OpenRCT2/OpenRCT2#2922]
I know this isn't exactly an issue, but I just wanted to say you guys are killing it. I've been watching the progress of this project and it's very exciting. You're all moving so fast and the code looks quite good for a decompilation project. Very impressive work all of you. Can't wait to see where you guys take this!
:beers:

**Comment by PFCKrutonium** [comment]
:coffee:

**Comment by carlu93** [comment]
+1 <3

**Comment by RollingStar** [comment]
[wontfix]
