### ISSUE TITLE
Reseting path type when a new client joins in multiplay

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#2931]
When I'm building path with opening the path window during multiplay, if a new client joins, then path type re-selected as the first one.

**Comment by IntelOrca** [comment]
Probably duplicate of #2912.

**Comment by telk5093** [comment]
I'm saying just when new client joins in **Multiplay**. Nevertheless, do you think that it is duplicate of #2912? If so, I feel sorry for duplicated issue posting.
