### ISSUE TITLE
Balloon pop sound missing

### ISSUE THREAD

**Issue by Phyxion** [OpenRCT2/OpenRCT2#2933]
In the vanilla version you hear a 'pop' sound when you click on them, this does not happen in OpenRCT2.

**Comment by duncanspumpkin** [comment]
I think it does play the sound its just its a bit quite.

**Comment by Phyxion** [comment]
I've cranked everything to max and I do not hear it.

**Comment by Gymnasiast** [comment]
It might have to do with too many sounds fighting for a place, although I have yet to test that.

**Comment by duncanspumpkin** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/world/balloon.c#L30 It's definitely in the code to pop.

**Comment by Phyxion** [comment]
@Gymnasiast I also don't hear it when I pop a balloon at the black end of the map and when it's completely silent.

**Comment by danidoedel** [comment]
Hmm I can hear the 'pop' sound...

**Comment by PFCKrutonium** [comment]
Try moving the balloon to the lower left hand corner of your screen when popping.

**Comment by Phyxion** [comment]
I still don't hear a pop sound. I can clearly hear it in vanilla, no matter where it's located.

**Comment by Phyxion** [comment]
I don't know if this is related but it's also a sound issue.

![scr2](https://cloud.githubusercontent.com/assets/7643972/13055637/c9ac7eee-d410-11e5-97b7-1f3077025fa1.png)
In RCT2 vanilla I hear the following:
- People laughing.
- Cash sounds.
- Sounds from circus.
- Music from Dodgems.
- One other music track but very soft (I think).
- Quack-quack when clicking on a duck.


![scr13](https://cloud.githubusercontent.com/assets/7643972/13055794/a67dbdd8-d411-11e5-8f0d-496dfdcbeb6a.png)
In OpenRCT2 I hear the following:
- Extremely soft cash sounds.
- Extremely soft people laughing.
- Music from merry go round that isn't even in view.
- Quack-quack when clicking on a duck (this is the same volume as in vanilla RCT2).

Save game:
[Rainbow Summit.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/131170/Rainbow.Summit.sv6.txt)


In the save game, just press enter two times to get the location of the screenshots.


I have both 'Sound' and 'Music' all the way to the max in the options. I also noticed that changing 'Sound' affects the volume of the music from the rides, this doesn't make much sense to me as I expected this to be people laughing, cash sounds, etc.

**Comment by duncanspumpkin** [comment]
Music means title music. Sound means everything else.

**Comment by Phyxion** [comment]
I change the music slider the volume of the ride music also changes.

**Comment by duncanspumpkin** [comment]
Hmm sounds suspicious.

**Comment by Gymnasiast** [comment]
AFAIK, the music slider controls just ride music, and not title music. I think Duncan got the two mixed up.

**Comment by zsilencer** [comment]
I can hear the balloons pop too.
No idea why the cash sounds would be soft, sounds the same to me.
There can only be 2 ride musics going at once, and for whatever reason original rct2 is deciding to update the circus first, versus openrct2 which is updating the merry go round first.
Still don't know about #1270, I always thought sound referred to anything you can hear, including music, maybe it is a country specific thing.

**Comment by IntelOrca** [comment]
@zsilencer That would be master volume. Besides that the problem is that you can't lower the sound effects volume but keep the music volume high. That is why it would be better just to make sound only control sound effects.

**Comment by Phyxion** [comment]
The sound/music sliders do not make sense to me, it's not at all what other games are doing.

@zsilencer  That might be but it doesn't make sense that I hear the merry go round even when it's not visible. What I hear in vanilla makes sense, what I hear in OpenRCT2 does not. Not that vanilla is always that great as you can sometimes hear very hard transitions in music but at least what you hear makes some sense.

**Comment by Nubbie** [comment]
Well, the pop seems to be implemented and working - the issue itself seems to be invalid
