### ISSUE TITLE
Clicking on a balloon sometimes moves the balloon

### ISSUE THREAD

**Issue by Phyxion** [OpenRCT2/OpenRCT2#2934]
This rarely happens and I do not know what is causing it. I've seen it happening on all maps. When you click on a balloon it'll go to the left or to the right but it doesn't pop. This does not happen on vanilla.

**Comment by Gymnasiast** [comment]
This does happen in vanilla and is intended behaviour

**Comment by Phyxion** [comment]
Hmm, I've never seen this happen in vanilla. Maybe I just click more balloons now :+1:
