### ISSUE TITLE
Construction window doesn't close automatically

### ISSUE THREAD

**Issue by danidoedel** [OpenRCT2/OpenRCT2#2935]
This issue is multiplayer only.

Building a shop or a flat ride doesn't close the construction window automatically after placing the shop or the entrance/exit.

![shop](https://cloud.githubusercontent.com/assets/10995998/13035019/4d7743e8-d345-11e5-98a2-82b352ae2e51.PNG)

Not sure if this is a known issue...

Build: c137ac41c0d8c091d3679745c3bdce7d62dc0c2b

**Comment by Overv** [comment]
I've also noticed that if you place a ride you don't automatically start placing an entrance. When you then place an entrance and an exit, it will put you back into entrance placing mode again and only after that will it automatically close the construction window.
