### ISSUE TITLE
Fatal launcher issues

### ISSUE THREAD

**Issue by Christipher** [OpenRCT2/OpenRCT2#2938]
hello,

I just recently downloaded OpenRCT2 files and somehow even though I am using a windows computer, the launcher and the OpenRCT2 cannot find my RCT2 version.  Is there any help for this?

This leads to fatal errors with launching the game

**Comment by janisozaur** [comment]
Hi, we are not responsible for the launcher.

Please report your issue with https://github.com/PFCKrutonium/OpenRCT2Launcher

**Comment by PFCKrutonium** [comment]
@Christipher Options -> Launcher -> Game Path -> Choose where RCT2 is installed.

**Comment by Christipher** [comment]
the launcher exactly is saying that it somehow is not installed even though I did install it... for some reason I'm not exactly sure what the issue is in this case...

**Comment by Gymnasiast** [comment]
Closing this as the problem should be reported in the repository janisozaur linked to.
