### ISSUE TITLE
Enter does not work on input window in title screen

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#2941]
As suggested here: https://openrct2.org/forums/topic/895-just-some-suggestions/#comment-3626
>Pressing Enter to accept a password input for servers would be great.

This should also work for other input fields, such as park name, ride names, guest names, tool sizes, file names, probably some others.

**Comment by IntelOrca** [comment]
The bug is actually just enter not working on title screen. Its disabled along with other keyboard shortcuts, therefore an exception should be made for input window.
