### ISSUE TITLE
The cost text is flickering and too small

### ISSUE THREAD

**Issue by Phyxion** [OpenRCT2/OpenRCT2#2954]
This does not always happen, see video (bottom right of the dialog):

https://vid.me/3ZS4

The flickering can't be seen on video but can be seen in game. The too small text can be seen though.

**Comment by Nubbie** [comment]
Video is deleted

**Comment by Nubbie** [comment]
@Phyxion 
Still experiencing this problem?
The "money effect" has been modified after this issue was opened
