### ISSUE TITLE
Glitched RollerCoaster in MP, It sells Balloons.

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#2955]
[Error 500.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/131622/Error.500.sv6.txt)
The ride is called Error 500, it's a roller coaster, but it thinks that it sells balloons.

**Comment by IntelOrca** [comment]
The saved game alone probably won't help us work out how it occurred.

**Comment by PFCKrutonium** [comment]
When I built the coaster, I never allowed any peeps to ride it - it was a joke, error 500. The server later crashed, and when it came back, this was the final state. I've witnessed similar things. where a water ride turns in to a different kind of coaster than was built or visible to any of the clients before the crash.

**Comment by IntelOrca** [comment]
@PFCKrutonium yes and I have been investigating the causes in #2924. One of causes I believe is when a player joins between select the ride to build and building the first track piece.

**Comment by notorioushaze** [comment]
We have no seen this issue over at /r/WhiskeyLand however we do get frequent corruptions where I have to roll back the server a few hours. I think this could be possible a similar issue.

**Comment by RaymondBakker** [comment]
I have run a server over 5 hours with #2924 fixes and it hasn't happend since then. So I suggest all of you here to download latest and see if it resolves this because I think this is a duplicate issue of #2924.

**Comment by janisozaur** [comment]
This must've been some desync, most likely fixed since. Re-open or file new issue if it occurs again.
