### ISSUE TITLE
Importing SC4 and SV4 as landscapes is broken

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#2958]
There are two issues here:
- The load landscape window does not show SC4 and SV4 files. Neither does the Zenity dialog (although that one, like the built-in Windows dialog, has a way of circumventing that.)
- When you manage to work around point 1, you get an error saying the file contains invalid data.

**Comment by IntelOrca** [comment]
Does it work if you try via command line?
```openrct2 edit park.sc4```
```openrct2 edit park.sv4```

**Comment by Gymnasiast** [comment]
Yes, both of those do work.

**Comment by Horsti12** [comment]
It seems that it still not work for more. My current OS is Windows 10 and I use the newest build.
![ssqsdkk](https://cloud.githubusercontent.com/assets/12634026/13202177/e9eac97a-d890-11e5-8d17-4e50ca0c55eb.png)
