### ISSUE TITLE
Object selection + invention list together.

### ISSUE THREAD

**Issue by Horsti12** [OpenRCT2/OpenRCT2#2965]
It would be cool when the object selection + invention list would be together in one window.
The current problem is that when you want to add a new ride to a park with the object selection, then it will unlock everything, also things which you normal have to research.

Currently you only can say in the object selection e.g. 3D Cinema is in the scenario available or not, while you can say in the invention list if it is research able or available. So both should be in just in one window
I got the inspiration from a tool for RCT1. (RCT Save Game Modifier)
![nvedsaz](https://cloud.githubusercontent.com/assets/12634026/13118151/2df6d96a-d5a3-11e5-8243-3b73e2c3a6e8.png)

So in OpenRCT2 it should look like this:
![a5sxdml 1](https://cloud.githubusercontent.com/assets/12634026/13118125/0cc8c5be-d5a3-11e5-9d2d-7b08621948c3.png)

Explanation of the colors
Green: available from the start
Orange: available after a research
Red: never available in the scenario

I hope you understand everything correctly.
Thanks!
-Horsti12

**Comment by Patrik356b** [comment]
Good idea,  but what about the order of research? 

As far as I know, the game will always follow the research order so that could be problematic

**Comment by Horsti12** [comment]
I didn't know that. Than it would be the best when the inventionlist will be in the future just for the order and not for something else. So like this:
![screenshot_2](https://cloud.githubusercontent.com/assets/12634026/13119611/5ac14d8e-d5aa-11e5-911f-f4db7315b46a.png)
I removed the "Item pre-invented at start of game:", because they are moved to the object selection.
Move all items to top and Move all items to bottom are also removed because the invention list is now just for the order and not more.

Random shuffle should be stay because it will randomly change the order and nothing more.

**Comment by Horsti12** [comment]
Edit.
![screenshot_3](https://cloud.githubusercontent.com/assets/12634026/13119850/6a58e760-d5ab-11e5-8cd9-633b20adc6fd.png)
Add the research button the object selection. You can change there the order of the rides/stalls.
+the random shuffle from the original inventionslist should be also added to this tab

**Comment by Gymnasiast** [comment]
We're open to interface improvements but this is quite intrusive, and will need more people in favour in order to go through. (As well as someone feeling like implementing it.)

**Comment by jensj12** [comment]
I agree that the RCT1 SGM was easier to use than RCT2, mainly because it had less attraction, but immediatly choosing if it's not used, researchable or available does make it easier (otherwise I'd have forgotten by the time I get to the inventions list).
Using a completely filled checkbox (that other programs use for 'only some in this submenu are selected') would work well too instead of adding traffic light colors. You could also just pre-load the inventions list with each attraction the correct section instead of a new tab.

**Comment by Patrik356b** [comment]
I find those checkboxes that's completely filled to be counter-intuitive. I prefer the traffic lights idea 

(because less != more)

**Comment by Gymnasiast** [comment]
The approach worked for RCT1 SGM because RCT1 had a fixed and limited set of rides and scenery. In OpenRCT2, this clutters the interface too much.
