### ISSUE TITLE
Notify users they are selecting wrong dir when asked for RCT2 path

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#2966]
During initial start, many users are selecting directory where OpenRCT2 got installed instead of their RCT2 installation. We should have a check for such case and let user know in big, bold letters they're selecting the wrong dir.

**Comment by IntelOrca** [comment]
This should go where call to ```rct2_startup_checks``` is, if it returns false.

**Comment by IntelOrca** [comment]
Implemented a while back.
