### ISSUE TITLE
One Boat Bug in OpenRCT2

### ISSUE THREAD

**Issue by birthdaybrian** [OpenRCT2/OpenRCT2#2972]
**OS: Windows 7 Home Premium SP1 x64** 
**Version:7725023** 
**Commit:Only one boat hire when building less stations.** 

When I build a boat hire in OpenRCT2 with less stations, the ride only gets one boat. Can anyone please fix this issue?

- [ ] Original bug?
- [x] Multiplayer?
- [x] In-Game

**Screenshots / Video:**
Video can be found here: http://1drv.ms/1TtdgKN

**Comment by ajanes3** [comment]
Can confirm. Is also happening to me.

**Comment by ajanes3** [comment]
Can I just say, wow, what a response. 21 minutes later, fixed! You guys are great.

**Comment by duncanspumpkin** [comment]
@ajanes3 i was refactoring this code and I thought I had introduced the bug in the past hour. Turns out I hadn't but that was the reason why it was so quickly fixed.
