### ISSUE TITLE
Enterprise Bug in OpenRCT2

### ISSUE THREAD

**Issue by birthdaybrian** [OpenRCT2/OpenRCT2#2973]
**OS:Windows 7 Home Premium SP1 x64** 
**Version:Latest Developer Build faf16a3** 
**Commit:Enterprise 1 Ride Bug** 

When people ride on my Enterprise 1 ride while playing multiplayer in OpenRCT2, there is a bug when people are riding, they move to the end of the map. Can any developer please fix this bug?
- [ ] Original bug?
- [x] Multiplayer?
- [x] In-Game

**Screenshots / Video:**
http://1drv.ms/1Tpe2Ht

**Comment by birthdaybrian** [comment]
The bug was later fixed when I checked on my Enterprise ride. People are on the ride. Although that the bug should be fixed.

**Comment by Gymnasiast** [comment]
Is this still happening?

**Comment by birthdaybrian** [comment]
@Gymnasiast I don't think this is happening anymore. I will let you know if this bug still happens.
