### ISSUE TITLE
Getting message that shops can't be found by people

### ISSUE THREAD

**Issue by WALUIGI96** [OpenRCT2/OpenRCT2#2984]
**OS:** Windows 10 Home
**Version:** 0.0.4.0 build 3583d60

Explanation of the issue...
I builded a chips shop on the water next to a path on the water, I'm sure that it's connected. People even buy stuff there. The same thing happened to a soda shop that is elevated next to an elevated path. But the strange thing is that I keep getting the message in the bottom: 'Chips shop can't be found, make a path to it.' (I play the game in Dutch, so excuse me for the bad translation.)

**Comment by IntelOrca** [comment]
Can you upload a saved game where this issue is occurring?

**Comment by moawkwrd** [comment]
Having the same issue here with the latest build, playing Dynamite Dunes from RCT1. Out of interest I loaded my Forest Frontiers save... same issue.

**Comment by WALUIGI96** [comment]
[Crazy Castle 20-2-16.txt](https://github.com/OpenRCT2/OpenRCT2/files/139318/Crazy.Castle.20-2-16.txt)
Here is the save file in .txt
