### ISSUE TITLE
Set console commands can be used in multiplayer

### ISSUE THREAD

**Issue by hkben** [OpenRCT2/OpenRCT2#2987]
**OS: Windows 7** 
**Version: 0.0.4.0 build caf8b45** 
- [ ] Original bug?
- [x] Multiplayer?

If you try to use **set** command in console , it cans affect the server even you don't have permission.

I have tried these:
- set park_open 0/1
- set money [money_value]
- set no_money 0/1

**Comment by IntelOrca** [comment]
Are you sure that it actually changes the server's game and not just the client?

**Comment by hkben** [comment]
Oh...yes. It just change the value on client side .

**Comment by Stevoisiak** [comment]
Appears to still be an issue in 0.0.5 commit 171c4f2
[Video](https://www.youtube.com/watch?v=xPczTY2sRhU)

**Comment by janisozaur** [comment]
I'm not sure it counts @stevoisiak. The client can only alter his view of the park, the server remains unchanged and no game commands are being sent to the server. In your video you show how a client can set `no_money`, but try depleting server's money – it should still prevent you from building any more.

**Comment by IntelOrca** [comment]
Yes, the bug is the fact that it lets you change it. The bug is not that it "bypasses permissions", this is prevented on the server side as anything is possible with your "open source" clone.

**Comment by ZehMatt** [comment]
This should be refactored to use the game actions instead

**Comment by Margen67** [comment]
This is missing the multiplayer tag.
