### ISSUE TITLE
Multiplayer window doesn't change title when tab changes

### ISSUE THREAD

**Issue by JarnoVgr** [OpenRCT2/OpenRCT2#2989]
Just want to point a minor annoyance in the multiplayer (player list) window. The title doesn't change when changing active tab. It keeps saying 'Multiplayer'. While most, if not all, other windows do change title based on their active tab.

**Comment by Nubbie** [comment]
Easy to implement - But don't know if it has to be changed
The "Options" window doesn't change with each tab, the name could be changed instead from "Multiplayer" to "Multiplayer settings"
