### ISSUE TITLE
Assertion failure for certain track pieces

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#2996]
**OS:** Windows 7
**Commit:** baffb37b349194c6ee190f4442956d46c7566bd1

Copied from: https://openrct2.org/forums/topic/932-instant-crash-when-building-a-downwards-slope-after-a-large-radius-corner/
>So I got this bug using version develop version baffb37, it is 100% reproducable. When making a coaster and making a large radius corner, the game will crash at the moment I select to build a downwards slope. No crash occurs when making an upwards slope or no slope at all. This happens for any type of roller coaster. I attached the crash window and a screenshot for an explanation. As I can see the referenced file (ride_construction.c) is adjusted in this version, so I guess this version introduced this bug. 

**Steps to reproduce:**
1. Build any coaster that has the very wide turn piece, the one that can go diagonal over the landscape
2. Build this track piece
3. Select the straight arrow, and click the track-down button

This assert is then triggered: https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/windows/ride_construction.c#L2660

![](https://openrct2.org/forums/uploads/monthly_2016_02/SCR1.thumb.png.b205edc5fc41c73fa71c34265c7c0ba6.png)

**Comment by jensj12** [comment]
Same thing happened again, but now with banked tracks: https://openrct2.org/forums/topic/951-bug-in-building-giga-coaster/
Building diagonal banked right to diagonal slope down causes the same assertion failure. Looking at the commit, this one probably caused it.

**Comment by marijnvdwerf** [comment]
@jensj12 The underlying issue is that those type of tracks actually don't exist, yet the old code doesn't check the banking for diagonal downward tracks.
