### ISSUE TITLE
Crash by segmentation fault 11 on OS X

### ISSUE THREAD

**Issue by minacle** [OpenRCT2/OpenRCT2#3003]
**OS:** OS X 10.11.3 (15D21)
**Version:** 0.0.4
**Commit:** 10dbcfe, current latest develop

Explanation of the issue...

- [ ] ?

**Steps to reproduce:**

1. Build.
2. Run.
3. …
4. ~~PROFIT!~~

**Screenshot:**

![Console](https://cloud.githubusercontent.com/assets/2531397/13317371/51ca71ca-dbf8-11e5-9d28-7982c7f8e4fa.png)

**[Crash Log](https://gist.github.com/minacle/b38633cab28c9ba48933)**

**Comment by janisozaur** [comment]
Well, the log states clearly: `Unable to load g2 graphics`.

Have you set up the `data/` directory correctly? https://github.com/OpenRCT2/OpenRCT2/wiki/Installation-on-Linux#openrct2-specific-files

**Comment by janisozaur** [comment]
Also, 10dbcfe is `develop`, not `master`.

**Comment by minacle** [comment]
> you haven't set up the data/ directory correctly, as seen in your screenshot.

Okay, so… where is problem?
![1](https://cloud.githubusercontent.com/assets/2531397/13319673/adbfa4a6-dc06-11e5-81ea-e3477a249ac5.png)
![2](https://cloud.githubusercontent.com/assets/2531397/13319706/fcf1e53e-dc06-11e5-8365-aabc88da605c.png)
![3](https://cloud.githubusercontent.com/assets/2531397/13319753/519b6ad8-dc07-11e5-9200-c2fa3ea1dbbc.png)

**Comment by IntelOrca** [comment]
your data folder that contains language and title should also contain g2.dat

**Comment by janisozaur** [comment]
`mv g2.dat data/`

**Comment by minacle** [comment]
> your data folder that contains language and title should also contain g2.dat

> mv g2.dat data/

I didn't know that. Thank you all.
