### ISSUE TITLE
Attempting to construct flat ride that isn't yet placed causes side effects

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#3008]
**OS:** Windows 10
**Version:** develop
**Commit:** 4a84a335155c76d45755ae1f7e20229bb13852cd

Clicking the construction button before a flat ride is constructed causes very alarming side effects.

- [ ] Original bug?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Select ride: merry-go-round, do not place it.
2. Open ride list, select the ride that you are building.
3. Click the construction button.
4. Observe side effects.

**Screenshots / Video:**
* [Video](https://github.com/OpenRCT2/OpenRCT2/files/147252/ride_construction_bug.zip)
* ![Screenshot](https://cloud.githubusercontent.com/assets/1482259/13333787/a7fe5432-dc00-11e5-86ad-ae03268d5e14.png)

**Comment by duncanspumpkin** [comment]
Best idea would be to make it unselectable during construction.

**Comment by IntelOrca** [comment]
@duncanspumpkin what do you mean?

**Comment by PFCKrutonium** [comment]
I'm thinking he is meaning either disable the construction button, or disable showing the ride in the ride list until it is actually built.

**Comment by IntelOrca** [comment]
Neither of those options are appropriate, it works in the original game so we need to fix the problem.

**Comment by cmdrf** [comment]
Maybe this is related to #578.

**Comment by IntelOrca** [comment]
@cmdrf its not because that is original game behaviour

**Comment by duncanspumpkin** [comment]
This doesn't happen in the original because the construction window closes and deletes the ride when the construction button is pressed. I suggest we make unplaced rides not show up in the ride list to prevent this issue.
