### ISSUE TITLE
When I save my scenario, the file's name does not include the file extension .sc6

### ISSUE THREAD

**Issue by birthdaybrian** [OpenRCT2/OpenRCT2#3010]
Hello, I made a scenario which has custom contents in-map. After I saved my scenario in the latest version of OpenRCT2, the file's name doesn't include the file extension .sc6 at the end of the file name. Can any developer please fix this bug?

**Comment by Gymnasiast** [comment]
Please provide more information, like your operating system.

**Comment by birthdaybrian** [comment]
I am running Windows 7 Home Premium SP1 x64 as I forgot to provide more information.

**Comment by PFCKrutonium** [comment]
What version of OpenRCT2?

**Comment by birthdaybrian** [comment]
3095ff6

**Comment by Broxzier** [comment]
@birthdaybrian If you mean that the extension isn't in the dialog when you save it, that's not a bug. It's hidden and gets added automatically, because the player doesn't need to know the extension at all. Your scenario should be visible in the scenario selector after having saved it.

**Comment by birthdaybrian** [comment]
@Broxzier Yes.

**Comment by Broxzier** [comment]
Confirmed that it doesn't add the .sv6 extension after saving it by default, even while the .sv6 type is selected in the windows system dialog. What would be the best approach to fix this, adding it to the string before opening the dialog, or adding it when saving the park?

**Comment by Richynator** [comment]
Fixed it by adding .sc6 at the end of the scenario name inside your Documents folder
