### ISSUE TITLE
Problem with Vehicle on the ride station.

### ISSUE THREAD

**Issue by Wirlie** [OpenRCT2/OpenRCT2#3011]
**OS:** Windows 10 (32 bits).
**Version:** 0.0.4
**Commit:** latest commit (adde88c).

- [ ] Original bug?
- [ ] Multiplayer?

**Explanation:**
_Trains does not move properly because these are bumping up and down while these are moving on the ride station.
It not happens on RCT2._

**Steps to reproduce / Video**
Please view this video: https://vid.me/1k89 (In this video you can reproduce and see the issue).

**Comment by Gymnasiast** [comment]
You mean that the trains seem to move with the restraints up, rather than down?

**Comment by Overv** [comment]
I think he's talking about the bumping up and down movement while the train is moving slowly.

**Comment by Wirlie** [comment]
oh sorry for the bad explanation! but, @Overv has said what is the problem.

**Comment by IntelOrca** [comment]
@Wirlie Does it happen if uncapped FPS is off?

**Comment by Wirlie** [comment]
@IntelOrca Yes, It also does happen when Uncapped FPS is off. (video: https://vid.me/hiwl)

**Comment by IntelOrca** [comment]
Oh I thought you meant bumping up and down in Z axis. Okay yeah, it keeps stopping and moving repeatedly as it moves to the end of the station.

**Comment by Wirlie** [comment]
@IntelOrca yup! I meant that.

**Comment by IntelOrca** [comment]
Yes, I'll mark it for 0.0.4
