### ISSUE TITLE
Crash in debug builds when switching between vehicle types

### ISSUE THREAD

**Issue by Overv** [OpenRCT2/OpenRCT2#3014]
**OS:** Windows 10 x64
**Version:** 0.04
**Commit:** adde88c

The game crashes when switching between vehicle types a couple of times.

- [ ] Original bug?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Build a Monorail with all 3 vehicle types
2. Switch vehicle type between "Streamlined" and "Retro"
3. Do this a couple of times (~5) and the game will crash

This crash only occurs in debug builds and happens somewhere around this line (the stack trace is kinda useless due to the vtables):

https://github.com/OpenRCT2/OpenRCT2/blob/adde88ca920253484b6847a494fbfb635226b5fc/src/windows/ride.c#L2764

From this line on a crash in `memcpy` is caused and it happens when drawing the first vehicle of a train for the preview.

**Comment by janisozaur** [comment]
Is there anything logged to stderr?

**Comment by Overv** [comment]
Nope, nothing.

**Comment by janisozaur** [comment]
```
diff --git a/src/drawing/sprite.c b/src/drawing/sprite.c
index f6f2e55..592f752 100644
--- a/src/drawing/sprite.c
+++ b/src/drawing/sprite.c
@@ -318,6 +318,8 @@ void FASTCALL gfx_draw_sprite(rct_drawpixelinfo *dpi, int image_id, int x, int y
 
 		uint32 primary_offset = palette_to_g1_offset[(image_id >> 19) & 0x1F];
 		uint32 secondary_offset = palette_to_g1_offset[(image_id >> 24) & 0x1F];
+		// countof(palette_to_g1_offset) == 144
+		assert(tertiary_colour < 144);
 		uint32 tertiary_offset = palette_to_g1_offset[tertiary_colour];
 
 		rct_g1_element* primary_colour = &g1Elements[primary_offset];
```

**Comment by Overv** [comment]
Yup, that assert is triggered. `tertiary_colour` is `0xcccccccc`.
