### ISSUE TITLE
Two objects failed to be exported with exporting enabled

### ISSUE THREAD

**Issue by birthdaybrian** [OpenRCT2/OpenRCT2#3022]
**Windows 7 Home Premium x64 SP1 with Windows 8.x UI** 
**Version:0.0.4-3 Developers build** 
**Commit: 10d25d9** 

Explanation of the issue...

Hey, when I created my server with custom contents, people couldn't join my server and I see people getting disconnected because of no data and/or connection is closed. This is because they are missing the object files needed for my park. I have export custom objects enabled in OpenRCT2 and I get errors in the command prompt which you can see in my screenshot. I have provided them the download link to the custom contents that are needed for my park. When will this bug be fixed?

- [ ] Original bug?
- [x] Multiplayer?

**Steps to reproduce:**
1. Join my server that has custom contents if you don't have these objects inserted in your objDATA folder.
2 OPTIONAL. Download and test out the scenario if you don't have the custom objects installed.
3. If you have these object files installed, load the scenario and check the command prompt.

**Screenshots / Video:**
![openrct2 object error](https://cloud.githubusercontent.com/assets/17324259/13366715/25856cf6-dcab-11e5-9dff-18b08fa8b8cb.png)

**Scenario**
[Build your own Six Flags park with mods.txt](https://github.com/OpenRCT2/OpenRCT2/files/149019/Build.your.own.Six.Flags.park.with.mods.txt)

**Comment by X123M3-256** [comment]
This is actually a bug in the tool used to create those custom objects. They have some nonzero bytes that the game zeroes when writing out the object, but the checksum is not updated, so when the objects are loaded you get a checksum mismatch.

I have just submitted a pull request to fix (or at least work around) the issue but I don't yet know if it'll be accepted.

**Comment by Gymnasiast** [comment]
The fix has been merged.
