### ISSUE TITLE
Remember custom servers / or a server file

### ISSUE THREAD

**Issue by katastic** [OpenRCT2/OpenRCT2#3031]
Playing on a private server is frustrating because every disconnect, you have to remember the exact server address and port.

Ideally, the game should either store servers you enter from the dialog into a file, or at least let you manually write a file to keep the servers and have OpenRCT enumerate private servers from it on start up.

An extension feature from this is: Remembering passwords for those servers. That requires a little debate. We could have it off by default, but let people manually add it to their config. But it's pretty doubtful that anyone is going to be writing trojans to grab OpenRCT passwords, and the liability is also, pretty minimal.

**Comment by IntelOrca** [comment]
This feature already exists, after adding your private server - click and hold the server in the list and select add to favourites.

**Comment by katastic** [comment]
Well, I'll be! Thanks.
