### ISSUE TITLE
The brown wall textures is different when you look from a other perspective.

### ISSUE THREAD

**Issue by Horsti12** [OpenRCT2/OpenRCT2#3037]
Newest Version, Windows 10
![screenshot_8](https://cloud.githubusercontent.com/assets/12634026/13379529/f1a9f72a-de27-11e5-83fb-432fbba0e1dc.png)
As you can see the wall has a wrong texture. This only happends on the brown wall as you can see on the picture. On the picture you also see all 4 perspectives and it only happends on the two pictures on the right.

**Comment by Gymnasiast** [comment]
The texture is the same, it's just very dark and is drawn using 256 colours.
