### ISSUE TITLE
Many sceneries like trees and gates are missing

### ISSUE THREAD

**Issue by birthdaybrian** [OpenRCT2/OpenRCT2#3042]
**OS: Windows 7 Home Premium x64 SP1 with Windows 8.x UI** 
**Version:0.0.0.4-4** 
**Commit:d778bc7** 

Explanation of the issue...
When I play OpenRCT2 in my server online, there is a bug with the sceneries. Default sceneries are missing in-game. People are also experiencing the same bug as I am experiencing. Can any developer please fix this bug?
- [ ] Original bug?
- [x] Multiplayer?

**Steps to reproduce:**
1.Go into the scenaries and check to see if you are expericing the same bug as me.

**Screenshots / Video:**
![scenary bug](https://cloud.githubusercontent.com/assets/17324259/13381411/9dae1c9e-de29-11e5-8aa3-6aade81b4da7.png)

**Comment by harrysbird** [comment]
you have too many objects selected in object selection list

**Comment by Patrik356b** [comment]
This is an original limitation because you do not want to run out of memory mid-game. OpenRCT2 will eventually increase this limit

**Comment by Gymnasiast** [comment]
@harrysbird @Patrik356b : Not true. RCT2 and OpenRCT2 don't let you deselect the default scenery groups, so something else must be the cause.

@birthdaybrian : We need more to solve this. Can you provide a save that exhibits this behaviour.

**Comment by IntelOrca** [comment]
@birthdaybrian are you absolutely sure this is directly related to multiplayer? What scenario are you using... did you make it yourself? Are the groups also missing in single player?

**Comment by IntelOrca** [comment]
BTW, similar or same issue: #2324

**Comment by duncanspumpkin** [comment]
Okay I've fixed #2324 can you check to see if that fixes your issue @birthdaybrian
