### ISSUE TITLE
An option to disable the scenery mass placement tool in user permissions

### ISSUE THREAD

**Issue by ItsMikey420** [OpenRCT2/OpenRCT2#3045]
Hey guys, I've been running a 24/7 server online and have been experiencing a bit of trouble with people using the scenery mass placement tool to spam the map with crap and ruin it for everyone.

I would like to note that I'm not keen on disabling the scenery for users all together and I'm not online all the time to enable permissions for users when they want to use scenery.

This problem could be solved by adding an option in the manage user groups to disable the scenery mass placement tool.

I'd love to hear back on peoples thoughts and ideas about this problem :D 

Cheers.

**Comment by Epxs** [comment]
Would love to see this implemented as well. Really frustrating how easy it is to grief by dumping scenery everywhere. 

Love the OpenRCT2 project!

**Comment by zsilencer** [comment]
This looks the same as issue #2920

**Comment by Gymnasiast** [comment]
It is related, though this one is more focused.

**Comment by IntelOrca** [comment]
This will require some infrastructure changes with the permissions system. Right now all you can block are entire game commands, not specific argument values of those game commands.
