### ISSUE TITLE
Chat and player names don't restrict format characters

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#3048]
Typing format codes into your player name or in the chat will cause problems. It would best for now just to remove them or convert the format characters into something else like ?. This should be done as the server receives player names and as the client sends chat messages. Lets allow clients to send coloured text for now (obviously not possible in the game, but can be done by bots).

- [ ] Original bug?
- [x] Multiplayer?

**Steps to reproduce:**
1. Use a | or } in your player name.
2. Use a | or } when sending a message.

**Comment by PFCKrutonium** [comment]
You could allow colored text to be sent in game, using the same method as Minecraft -

%5 = Yellow for example.

**Comment by IntelOrca** [comment]
I don't know if we want to encourage that.

**Comment by PFCKrutonium** [comment]
You could always make it a permissions thing
