### ISSUE TITLE
Flying Roller Coaster overlapping trains

### ISSUE THREAD

**Issue by jamesmp** [OpenRCT2/OpenRCT2#3052]
**OS:** Windows
**Version:** 0.0.4-develop
**Commit:** e2073d2

When a flying roller coaster is placed with any number of cars or trains, the train is shorter than requested and will overlap with other trains in the station, if there is more than one train, the others will force the first train out of the station, if there is only one train it will not move.

If the coaster is built in the latest stable version (0.0.3) it will function correctly when saved and opened in the latest development version until you attempt to change the train properties again.

- [ ] Original bug?
- [x] Multiplayer?

**Steps to reproduce:**
1. Enter Coaster designer mode and build a simple Flying Roller Coaster track
2. Set number of trains to 2 and number of cars per train to 4
3. Test or open the ride

**Screenshots / Video:**

[vidme Evidence Video](https://vid.me/Pvz1)

**Comment by Wirlie** [comment]
@IntelOrca, This issue is similar to #2879? If so, please mark as resolved.
