### ISSUE TITLE
Disconnected straight away when joining server

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#3057]
I think one cause of this is when joining a game containing objects the player does not have. The objects are sent with the map, but when the player has its object cache re-constructed - the connection to the server will timeout as re-constructing the object cache is a blocking function and multiplayer update is not asynchronous, therefore not able to ping back.

Of course once the player rebuilds the cache, they can reconnect to the server and they will not have to re-construct their cache this time thus getting into the game successfully.

**Comment by pizza2004** [comment]
Yes, I noticed exactly what you just described happening the other day when I was joining servers while doing some debugging.

**Comment by IntelOrca** [comment]
No longer a problem as the object cache is never reconstructed when loading a park.
