### ISSUE TITLE
Chairlift crashes

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#3060]
**OS:** Windows 10
**Version:** 0.0.4.0-develop
**Commit:** 36f7328

Explanation of the issue...

- [x] Original bug?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Build a chairlift
2. Car arrives at Station 2 and crashes just as it departs the station.

**Screenshots / Video:**
![image](https://cloud.githubusercontent.com/assets/10726524/13420818/aa961606-dfcc-11e5-8453-9c990e12f7c2.png)

**Save game:**

**Comment by IntelOrca** [comment]
Is this significantly different from #2710.

**Comment by telk5093** [comment]
@IntelOrca I have no idea.... It isn't affected by any speeds, not affected by numbers of cars.
If I use two ski-lift carts, it also crashed.

**Comment by Christipher** [comment]
looks like more information on #2710 - outside of that information it looks like a near duplicate of the issue at hand

**Comment by Stevoisiak** [comment]
Can you provide a save file? I'm having trouble reproducing this on my end.

**Comment by IntelOrca** [comment]
I think @duncanspumpkin fixed this for 0.0.4.

**Comment by Stevoisiak** [comment]
I can't tell if it's been fixed or not. I'm not able to recreate it on the older 36f7328 build either

**Comment by IntelOrca** [comment]
@Stevoisiak you need to check before 08de41bdd54b9aaa47e6bbf0f5b376dd92435253

**Comment by mrtnptrs** [comment]
@Stevoisiak Did you have any luck with reproducing this?

**Comment by Stevoisiak** [comment]
@mrtnptrs It's been a while since I looked at this. I don't think I was able to reproduce it.

**Comment by Gymnasiast** [comment]
I expect that https://github.com/OpenRCT2/OpenRCT2/commit/08de41bdd54b9aaa47e6bbf0f5b376dd92435253 has fixed it.
