### ISSUE TITLE
Backtick ` opens console when inputting text into chat or other things

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#3062]
When during inputting texts in chatting, if I type ~, then console window opens.
I think it must be prevented to type ~ in chat.

c.f. ~ is typped by SHIFT + backtick(`) in Korean keyboard

**Comment by IntelOrca** [comment]
Are you saying that typing ```~``` does not open the console window when the chat is not open?

**Comment by telk5093** [comment]
No, the opposite.
I can't type ~ because the console is opened by force if I type ~ in chat.

**Comment by IntelOrca** [comment]
OK understood, its actually just the backtick key that opens console. So we can disable that if there is currently a text input in focus.

However, you won't be able to use ~ anyway as that is unfortunately a format code. For technical reasons we can't resolve that until later.

**Comment by telk5093** [comment]
Okay.

**Comment by mrtnptrs** [comment]
Still happens and #3009 did not fix it.

**Comment by Patrik356b** [comment]
@IntelOrca a common technique is to use ~~ which would render one ~
