### ISSUE TITLE
[Title sequence] Mini Game

### ISSUE THREAD

**Issue by Horsti12** [OpenRCT2/OpenRCT2#3068]
Please also add the Mini Game title sequence to openrct2.
I worked on it months ago, but I not think that it is perfect, so it would be better when somebody could port the intro like somebody ported the rct1 sequence into rct2.

**Comment by Gymnasiast** [comment]
This is something for the community. We have support for creating your own title sequences. #3800 is concerned with adding support for loading scenarios.
