### ISSUE TITLE
Suggestion: Passengers of a Ferris wheel get on/off all at once

### ISSUE THREAD

**Issue by UTNerd24** [OpenRCT2/OpenRCT2#3072]
I know this kinda breaks the logic of the partially realistic loading/unloading procedures, but might I suggest an option to have guests board, exit a Ferris wheel all at once rather than two-by-two? Doing so will most likely decrease the likeliness of passengers complaining that the ride is too long.

**Comment by jensj12** [comment]
Something better came up in the discussion of #2183: Allow 1/16, 3/16, 5/16, 7/16, 9/16, 11/16, 13/16, and 15/16 rotations.

**Comment by Gymnasiast** [comment]
I agree that the Ferris Wheel rotations need a look at, but there's indeed #2183 for that, and also better methods that don't break reality. (RCT's inefficient method is not realistic either, btw.)
