### ISSUE TITLE
Korean IME input is not fully cancelled

### ISSUE THREAD

**Issue by YJSoft** [OpenRCT2/OpenRCT2#3080]
**OS: OSX 10.11** 
**Version: 0.0.4** 
**Commit: 9ef4af5** 

Explanation of the issue...
- [ ] Reproducable in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Input some korean charactor(do not close IME!)
2. Cancel input by deleteing all charactor in IME window
3. Inputing supposed to be cancelled, but some charactor will inputed

**Screenshots / Video:**
![2016-03-04 16_15_07](https://cloud.githubusercontent.com/assets/5893514/13520512/4ea94e62-e224-11e5-81bb-5ed22714ec44.gif)
https://www.youtube.com/watch?v=sdDUUra8xKI

**Comment by AaronVanGeffen** [comment]
I believe this was resolved by #6399. Feel free to reopen if the problem persists.
