### ISSUE TITLE
Price calculation wrong when building on trees

### ISSUE THREAD

**Issue by carlu93** [OpenRCT2/OpenRCT2#3082]
**OS: Windows 10** 
**Version: 0.0.4** 
**Commit: 9ef4af5** 

Explanation of the issue...

- [ ] Reproducable in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Try to build a Toilet or any other stall.
2. Hover with the ghost over a tree.
3. The price is always the initial price (225€) + 75€, not the initial price + plus the price for removing the tree.

**Screenshots / Video:**
Unfortunately I don't have a video or screenshot. I hope you'll understand what I tried to explain above.

**Save game:**
[Diamond Heights.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/159115/Diamond.Heights.sv6.txt)

This seems to be related to #3074...

**Comment by Gymnasiast** [comment]
Marking this as duplicate, but leaving it open. This has to be tested after a fix for #3074 is merged.

**Comment by Gymnasiast** [comment]
Confirmed fixed by #3079.
