### ISSUE TITLE
missing screenshot notification

### ISSUE THREAD

**Issue by ipatix** [OpenRCT2/OpenRCT2#3084]
**OS: Linux - Debian Sid** 
**Version: 0.0.4.0 build fc2d48d** 
**Commit: fc2d48d** 

Making Screenshots on the current Linux build doesn't seem to cause a red window popping up notifying a successful screenshot. Giant screenshots don't seem to be affected by that.
This is just a visual thing and even though there is no message, they get saved to disk.
Not sure if the Windows builds are currently affected.

- [ ] Reproducable in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Go into any game
2. Take a regular screenhot

**Screenshots / Video:**
Sorry, don't know how to record video on Linux, but I hope the explanation is good enough and taking a screenshot doesn't really make sense if I can't see what I expect to see.

**Save game:**
Issue is not park depended.

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/commit/4d6cce3caeae683cfe7fc2e7d6ee6c64ac1415e8

**Comment by ipatix** [comment]
In terms of consistency it'd make sense to do the same for the giant screenshots then.

**Comment by IntelOrca** [comment]
This was deliberately removed as the error box would show in the next screenshot if you take several in short amount of time.
