### ISSUE TITLE
3D Sign doesn't show latin characters.

### ISSUE THREAD

**Issue by Wirlie** [OpenRCT2/OpenRCT2#3086]
**OS:** Windows 10 (32 bits)
**Version:** 0.0.4
**Commit:** latest build

On RCT2 this doesn't happen.

- [ ] Reproducable in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Place a 3D Sign.
2. Change the text and write "ññ".
3. 3D Sign display "A A", but, if you click on the button "change text" the text input shown "ññ".

**Screenshots / Video:**
![Image](https://k61.kn3.net/D2EEDF0A3.png)

**Comment by IntelOrca** [comment]
I unfortunately do not know how to fix this.

**Comment by Gymnasiast** [comment]
3D signs and banners do not properly convert from RCT2's encoding to UTF-8, and vice versa. That's what's causing the issue. Characters in RCT2's encoding that are not ASCII are corrupted.

**Comment by IntelOrca** [comment]
@Gymnasiast I have also not implemented any TTF font support for 3D signs, I have no idea how they work or whether its even possible.

**Comment by raidcookie** [comment]
I guess the 3D signs are compositions of different Sprites? This is the only real reason I can think of apart from those signs not supporting UTF characters..

**Comment by Wirlie** [comment]
#3702 fixes this bug.
