### ISSUE TITLE
Korean words corrupted if over byte limit

### ISSUE THREAD

**Issue by YJSoft** [OpenRCT2/OpenRCT2#3091]
**OS: Windows 7** 
**Version: 0.0.4** 
**Commit: 2cd7f2d** 

Explanation of the issue...

- [ ] Reproducable in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Rename any park to '다이너마이트 모래언덕'
2. and park name will be '다이너마이트 모래언덀'(last word is corrupted)

because park name limit is 31 bytes and korean words are 2 bytes, last korean word will be cut(only first one byte is saved) and corrupted.

at original(vanilla), last words just cut off and saved like '다이너마이트 모래언'

**Screenshots / Video:**
![image](https://cloud.githubusercontent.com/assets/5893514/13544297/befefc64-e2b7-11e5-9a38-f3a2942a069a.png)
OpenRCT2 behavior

![image](https://cloud.githubusercontent.com/assets/5893514/13544325/0093c376-e2b8-11e5-8c4e-98f0c355c8cc.png)
vanilla behavior

**Save game:**
Change the file extension to .txt or package to a .zip so that it can be drag / dropped here...

**Comment by telk5093** [comment]
I think it must be extended that not only the length of scenario's name, but also ride's name which is caused by the same reason.

**Comment by YJSoft** [comment]
![image](https://cloud.githubusercontent.com/assets/5893514/13601603/a6356b04-e574-11e5-83a5-30823c289933.png)
default save file name is also corrupted if park's name is too long.

**Comment by janisozaur** [comment]
isn't it limited by the game's internal structures?

**Comment by Gymnasiast** [comment]
No, the problem is that OpenRCT2 limits strings to 31 bytes, thus messing up characters that take two bytes, like Korean.

**Comment by IntelOrca** [comment]
Yes, it needs to find the end of the last codepoint before where the null terminator will be written.

**Comment by Gymnasiast** [comment]
I also have the idea that OpenRCT2 cuts off a character too many, as it truncates the name of `Hex ... the Legend of theTowers` (sic) when importing from RCT1.
