### ISSUE TITLE
[Feature Request?] Ride Stat Cheat

### ISSUE THREAD

**Issue by RapleAQN** [OpenRCT2/OpenRCT2#3096]
I have played alot of RCT2 and abunch of times I've encountered weird issues / bugs where the game removed the ratings and made made them bad. I was thinking about a cheat that would make allowance of changing the ratings of the coaster possible

**Comment by danidoedel** [comment]
There is already a request to change ride ratings: #1236

**Comment by RapleAQN** [comment]
Oh my bad
