### ISSUE TITLE
Can't host a server when I port forwarded the port in my router

### ISSUE THREAD

**Issue by birthdaybrian** [OpenRCT2/OpenRCT2#3097]
**OS: Windows 7 Home Premium SP1 x64 with Windows 8.x UI** 
**Version:0.0.4-4** 
**Commit:bb7765f** 

Yesterday my modem went out when I was playing OpenRCT2 in my server and when I host my server when the port is port forwarded to my router, I get an error message saying "Unable to advertise" in the command prompt. I port forwarded the port in my router since January and now I keep getting this message when I host my server. Can any developer please fix this issue?

My router is an ARRIS Touchstone TG862G/CT which is a new router that I got back almost 4 months ago and is located in my basement where it gets flooded a little bit everytime when there is a flood warning and there is mold in the back except for the laundry room and the storage room. Waterproofers are supposed to come fix my basement in a few days. There is no XFINITY/Comcast maintenance currently.

- [ ] Reproducable in RCT2 (vanilla)?
- [x] Multiplayer?

Host a server with the port port forwarded to your router.

**Screenshots / Video:**
![portforward](https://cloud.githubusercontent.com/assets/17324259/13549692/3a6c6b90-e2d9-11e5-952e-ea7ad715ac5c.png)
![portforward2](https://cloud.githubusercontent.com/assets/17324259/13549704/a1ad37c6-e2d9-11e5-9bc2-f17bd323ceb5.png)

**Comment by IntelOrca** [comment]
This is not an issue with OpenRCT2, make sure that your firewall on your computer is not blocking the port or application.

**Comment by birthdaybrian** [comment]
@IntelOrca I have Norton Security Suite and I am trying to get the firewall to stop blocking the port. OpenRCT2 is allowed in firewall. How can I allow the port in Norton Security Suite firewall?

**Comment by janisozaur** [comment]
@birthdaybrian we are not your computer support service.

**Comment by birthdaybrian** [comment]
Good news. I just found that I had a different IPv4 address and I went to the router and changed the IPv4 address to the current one and that fixes my problem. It is not because of my firewall as I found out.

**Comment by pizza2004** [comment]
I was about to say, that sounded like an issue with IP.  There's an even better way to handle this situation, and the video on this page should give you a good idea of how to set it up so that the router will always assign the same IP to your computer when it connects: http://blog.airscapefans.com/archives/ip-address-reservation-on-xfinity-comcast-routers
