### ISSUE TITLE
Footpath doesn't connect to ride entrance and ride exit.

### ISSUE THREAD

**Issue by Wirlie** [OpenRCT2/OpenRCT2#3100]
**OS:** Windows 10 (32 bits)
**Version:** 0.0.4
**Commit:** latest build.

- [ ] Reproducable in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
~~- I do not know how to reproduce this.~~
It happens if your ride have multiple stations (how to reproduce? See this image)
![Image](https://k60.kn3.net/53188E04E.png)

**Video:**
This happens: https://vid.me/7fxf
This is expected:: https://vid.me/M1iK

**Save game:**
[Vistas Infernales.txt](https://github.com/OpenRCT2/OpenRCT2/files/160616/Vistas.Infernales.txt)

**Comment by Wirlie** [comment]
I have seen that the problem happens if the ride is built in the air, but, if it built on the ground this not happens.

**Comment by Wirlie** [comment]
This problem seems to be related to #2990 .... (Sorry, I did not realize).

**Comment by ipatix** [comment]
Yup, I've seen that before. I managed to workaround that by building the paths and then deleting and rebuilding the entrance/exit again (which is obviously not a permanent solution).

**Comment by LinusU** [comment]
I noticed this the other day as well. However, no matter how many times I rebuilt the path, and/or the entrance, I couldn't get it working...

**Comment by YJSoft** [comment]
This happens when building station 2's entrance/exit first on 816828b build.
https://vid.me/yING

**Comment by Wirlie** [comment]
Okay, the problem is still happening after reversing the change. 
@IntelOrca please, you can open this Issue again for for further review? I used the latest build at this moment (b8edcd5) but the problem still happening....

**Comment by Wirlie** [comment]
Okay, the problem is still happening.
@IntelOrca @duncanspumpkin please, you can open this Issue again for further review? I used the latest build at this moment (b8edcd5) but the problem still happening....
