### ISSUE TITLE
Using System Save Dialog while in Fullscreen Mode does not allow you to save

### ISSUE THREAD

**Issue by KyleRoss** [OpenRCT2/OpenRCT2#3101]
**OS:** Windows 10

When you are in fullscreen mode and use the system dialog to save, you are not able to save the game because the save dialog loses focus and clicking the "Save" button causes the game to minimize. The game screen also turns black so there is no way to get out of the save dialog or try to gain focus on it to actually save the game. While the save dialog is on top of the game window, clicking anything on it does not actually do anything except minimize the game (probably thinks that you are clicking outside of the full screen window). I am seeing this issue on the scenario editor but I'm sure it will happen elsewhere. I finished putting together a scenario and now I am unable to save it. It could be front ALT-tabbing out because I needed to change the permissions on my documents folder in order to save (not sure why my permissions changed), but definitely an issue.

I'd upload a screenshot but there isn't much for me to show.

**Comment by Broxzier** [comment]
Just tested it on 9b5d706. The in-game save dialog works just fine. When the system dialog opens, the game gets minimized, but saving is no problem either. After saving I had to manually focus on the game again. I don't know if it's possible to have the system dialog open on top of the game. I know RCT2 does this, but it is very broken (for me at least).
