### ISSUE TITLE
Implement rotating entrance and exit buildings

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#3106]
An oft-requested feature by power users. Feel free to pick it up, as I have limited time. (I do hope to get around to it, however.)

**Comment by IntelOrca** [comment]
I don't understand this feature request, can you explain?

**Comment by janisozaur** [comment]
I think it means this: http://www.themeparkreview.com/forum/viewtopic.php?p=1182839

**Comment by Gymnasiast** [comment]
Yes, that's it.

**Comment by devnoname120** [comment]
Maybe as a cheat? Or in the tile viewer? I wonder if it is a good idea to add as a default feature something that does not play well with current graphics.

**Comment by IntelOrca** [comment]
I can try adding a rotate button on the tile inspector.

**Comment by Broxzier** [comment]
It would be nice to not only allow this for entrances and exits, for but all map elements that can be rotated.
