### ISSUE TITLE
Number of sold items is reset after some time

### ISSUE THREAD

**Issue by danidoedel** [OpenRCT2/OpenRCT2#3107]
**OS:** Windows 10 x64
**Version:** 0.0.4-develop
**Commit:** e7d8841

Opening a save in vanilla doesn't bring back the old number.

- [ ] Reproducable in RCT2 (vanilla)?
- [ ] Multiplayer?

**GIF:**
![stall](https://cloud.githubusercontent.com/assets/10995998/13582579/5bc600c8-e4ad-11e5-817b-1c1b4694be2f.gif)

**Comment by Gymnasiast** [comment]
Also, there shouldn't be a queue time for shop, should there?

**Comment by danidoedel** [comment]
Oh yeah that's true... didn't notice that.
