### ISSUE TITLE
Saving track shows invalid extension in dialog

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#3112]
Taken from https://openrct2.org/forums/topic/996-/

> Saving a new ride design will open the standard windows dialog, but the file cannot be saved as it is. The name check seems to ignore the file extension that is hidden by the dialog and will just check the string value infront of the invisible .sv6 part. Saving will always fail until some random "normal" extension is typed in (.png, .jpg, ...).

**OS:** Windows 7, Windows 10
**Version:** 0.0.4.0
**Commit:** e7d8841 (reported), b8edcd5 (tested)

When you try to save a track, it shows up as ".TD?" in the system dialog.

**Comment by OrigamiPhoenix** [comment]
It's not a permanent fix, but you can still save files that function normally if you replace the ? in the bad .TD? ending with 6. You'll have an excess .TD6 in the file name, but you can rename the file to get rid of that if that bothers you.

**Comment by Gymnasiast** [comment]
Something to check in #3009.

**Comment by IntelOrca** [comment]
I think the problem here is that TD? should only be passed to an open dialog, not a save dialog. My new branch should be more explicit anyway, only allowing TD4 and TD6.

**Comment by Superjustinbros** [comment]
I do hope this gets fixed, because trying to edit the TD? into TD6 never works for me as it just says the file is still invalid for me.

**Comment by Gymnasiast** [comment]
@Superjustinbros : Please make the effort to search and read before you post. First you opened a duplicate issue and now you clearly haven't read the description of #3009. We are working on this issue.

**Comment by Superjustinbros** [comment]
@Gymnasiast Fine. :|
Sorry if it sounded like I was rushing you.
