### ISSUE TITLE
Scenery Offset For Saved Tracks

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#3113]
Taken from https://openrct2.org/forums/topic/996-/

> Trying to place a previously saved ride with scenery causes the scenery to be placed at wrong coordinates [[screenshot]](http://www2.pic-upload.de/img/29964092/screen2.png). Rides that have been saved in regular rtc2 are unaffected and work normal when placed in openrtc2.

**OS:** Windows 7, Windows 10
**Version:** 0.0.4.0
**Commit:** e7d8841 (reported), b8edcd5 (tested)

Scenery in a saved track file that has been made using OpenRCT2 has an offset. When I tested it myself the game crashed, maybe because it was so far out of the map. Saved tracks from Vanilla RCT2 work fine, so it has most likely to do with saving it.

**Steps to reproduce:**
1. Save and track with scenery.
2. Build the saved track.

![test](http://i.imgur.com/s9kzaxO.png)

**Comment by duncanspumpkin** [comment]
likely mistake made relatively recently as I tested all of this when i wrote it.

**Comment by hyperpeople** [comment]
I have this exact issue in v0.3.5.1(61c67af) 
![grafik](https://user-images.githubusercontent.com/95047399/143485653-840c20ef-b668-45fe-940f-253978191fc9.png)

**Comment by hyperpeople** [comment]
I have this exact issue in v0.3.5.1(61c67af) 
![grafik](https://user-images.githubusercontent.com/95047399/143485653-840c20ef-b668-45fe-940f-253978191fc9.png)

**Comment by Broxzier** [comment]
@hyperpeople please file a new issue for this.
