### ISSUE TITLE
Saving track design as a server kicks all clients out

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#3114]
**OS:** Windows (as seen on stream on twitch)
**Version:** 
**Commit:** somewhere between b6c8917b3ae2d49e1c65ccb8653353965d471196 and b8edcd5

When in multiplayer, as a server, saving track design causes all clients to disconnect. Probably the call to save (open save window) is blocking and causes to large a time gap in processing network.
- [ ] Reproducable in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Start multiplayer as a server, have clients join
2. Build a custom coaster
3. Test it
4. Save it

Clients will get disconnected.

**Comment by IntelOrca** [comment]
And presumably a client will get disconnected if they try to save a track design too. Same cause of #3057.

**Comment by ZehMatt** [comment]
Track designs now work in multiplayer
