### ISSUE TITLE
Not able to create Themes - Missing folder

### ISSUE THREAD

**Issue by Nubbiy** [OpenRCT2/OpenRCT2#3115]
**OS:Windows 7** 
**Version:0.0.4.0** 
**Commit:***b8edcd5* 

Explanation of the issue;
I couldn't create a new theme or duplicate the themes I had, when I checked in the console it said
_"ERROR[src\interface\Theme.cpp:453 <UITheme: :Fromfile>]: Unable to read theme C:\User\x\Documents\OpenRCT2\themes\RCT2test.json"_ 
With RCT2test.json being the newly duplicated file that can't be saved because it's missing its folder

It turns out that I was **MISSING** the "**themes**" folder in OpenRCT2 as it worked again after I made a new folder named after the missing one, is this a problem everyone has, that they have missing the "**Themes**" folder in "**Documents\OpenRCT2**"?

**Steps to reproduce:**
1. Delete the "themes" folder in "Documents\OpenRCT2"
2. Start the game and try to make a new theme

**How to fix:**
1. Make a new folder called "themes" in "Documents\OpenRCT2"
2. Start the game and try to make a new theme

**Comment by IntelOrca** [comment]
Where did it get "RCT2test" from? Is that a theme you previously created?

**Comment by Nubbiy** [comment]
Yeah, "RCT2test.json" is the filename/theme I created. Will edit that to make it more clear
