### ISSUE TITLE
CRASH: Right path + Golf hole A = Game crash/getting skipped

### ISSUE THREAD

**Issue by Nubbiy** [OpenRCT2/OpenRCT2#3117]
**OS:Windows 7** 
**Version:0.0.4.0** 
**Commit:ea05666** 

If you make a golf station and make a **RIGHT path** right afterwards, and after that **Golf hole A**, the game **crashes** when a guest gets to that hole or skips it entirely in rare cases.
If you make a **left path**, it's ok
If you make a **path forward first**, it's ok

It's JUST if you make a RIGHT turn and then Golf hole A (Just tested with Hole A)

- [?] Reproducable in RCT2 (vanilla)?
- [X] Multiplayer
- [X] Singleplayer

**Steps to reproduce:**
1. Make a golf station
2. Directly after that, make a RIGHT turn
3. Make a Golf Hole A
4. Finish the track and wait for a guest to reach hole 1

**Screenshots**
Screenshot: RED one crashes/Gets skipped by guests
Green tracks are ok
![red crashes](https://cloud.githubusercontent.com/assets/17282384/13638685/bb56fb30-e60d-11e5-937c-b96f22594a2c.png)

**Video:**
https://vid.me/H9op
THE VIDEO JUST SHOWS WHEN HE SKIPS IT, not a crash (Which happen to me before a ton of times)

**Comment by duncanspumpkin** [comment]
Will be caused by vehicle update.

**Comment by Nubbiy** [comment]
TESTED IT; STILL WORKS AND CAN BE USED TO CRASH SERVERS!

**Comment by Nubbiy** [comment]
Deleted it, just wanted to point it out as I had tried it out, the results vary, good thing "no-one" knows about this but this people might see this and abuse it, if you could hide the whole post, that would be good
