### ISSUE TITLE
Unable to change TypeFont in Japanese

### ISSUE THREAD

**Issue by RapleAQN** [OpenRCT2/OpenRCT2#3118]
**OS: Windows 7** 
**Version: 0.0.4** 
**Commit: ea05666**

Explanation of the issue...

- [ ] Reproducable in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Set the language to japanese in the settings
2. Gonna throw error that it's not able to change TypeFont

**Screenshots / Video:**
![problem](http://i.imgur.com/sP6YUwe.png)

**Save game:**
Change the file extension to .txt or package to a .zip so that it can be drag / dropped here...

**Comment by RapleAQN** [comment]
note: font is installed and other apps work good with jap

**Comment by IntelOrca** [comment]
Can you double check if ```C:\Windows\Fonts\msgothic_02.ttf``` exists?

**Comment by RapleAQN** [comment]
it is existing, i also tried installing other types of msgothic fonts, and my windows is in japanese language so should work

**Comment by BWBuchanan7** [comment]
I seemed to be having this same issue in 0.0.4 as well (though on Windows 8.1). I do have the MS Gothic font installed (as it came with Windows) but I realize that it's listed as "C:\WINDOWS\Fonts\MSGOTHIC.TTC" on my system.

Some poking around and msgothic_02.ttf doesn't appear to be available for download (at least that I can find) and attempting to rename MSGOTHIC.TTC to msgothic_02.ttf doesn't appear to work either.

I replaced instances of _msgothic_02.ttf_ (on lines 51-54) in src/localisation/language.cpp with _MSGOTHIC.TTC_ and it seems to be working fine for me now:

![2016-03-27 19_18_06-openrct2](https://cloud.githubusercontent.com/assets/9372264/14069016/abadf6d8-f450-11e5-82fd-b6fe95b79be3.png)

**Comment by AaronVanGeffen** [comment]
`MSGOTHIC.TTC` is an older version of the same font. The [newer version](https://www.microsoft.com/typography/fonts/font.aspx?FMID=2147) should ship with all new versions of Windows, but it probably only appears if you install the additional Japanese fonts through the Regional settings panel.

The situation is slightly better on Linux and OS X, but I would like there to be a better fallback mechanism for Windows, too...

**Comment by RapleAQN** [comment]
i should have the font installed since my system language is japanese and such so it shouldtn really be a problem
