### ISSUE TITLE
Minor issue with the financial window.

### ISSUE THREAD

**Issue by Wirlie** [OpenRCT2/OpenRCT2#3120]
**OS:**  Windows 10
**Version:** 0.0.4
**Commit:** latest build

~~I do not know if this is an issue or if it is part of OpenRCT2~~ (The cash does not appear in red if it is negative. See the screenshots).

**Edit:** Probably the line STR_2224 is used instead of STR_2225 if the cash have a negative value.

**Screenshots / Video:**
On RCT2:
![Image](http://oi65.tinypic.com/2e4i8ph.jpg)

On OpenRCT2
![Image](https://k60.kn3.net/9D7DC2477.png)

Thank you very much for your attention :)

**Comment by Nubbiy** [comment]
This should be easy to fix
All you need to do is use STR_2453 where it displays the money :p
_which is command; STR_2225    :{WINDOW_COLOUR_2}Cash: {RED}{CURRENCY2DP}_

If I understand it right, Im not a programmer so cant say :p

**Comment by Wirlie** [comment]
But.... but in the Spanish language the line STR_2225 already contains it.

    STR_2225    :{WINDOW_COLOUR_2}Efectivo: {RED}{CURRENCY2DP}

**Comment by Nubbiy** [comment]
I know, the thing is (I think) is that the script uses STR_**2224** instead of STR_2225 with Str_2224 being black color

**Comment by Wirlie** [comment]
Yup, I had not understood well your first answer haha, sorry :P

**Comment by Nubbiy** [comment]
I had written the wrong string so It's not ur fault, corrected it xOx
Hope someone fixes this :p
