### ISSUE TITLE
Ghost sign window shows when build sign twice

### ISSUE THREAD

**Issue by YJSoft** [OpenRCT2/OpenRCT2#3123]
**OS: OS X** 
**Version: 0.0.4** 
**Commit: d03c4de** 

Explanation of the issue...

- [ ] Reproducable in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Build sign twice(build sign where sign already exists)
2. Click on "No entry" button
3. Ghost sign window appears(cannot removed, but window can be closed)

**Screenshots / Video:**
https://vid.me/GymB

**Comment by Margen67** [comment]
Something similar happens in multiplayer happens when you hire staff.
![bug](https://cloud.githubusercontent.com/assets/3462541/13732858/bee4cbc8-e947-11e5-8c6a-7f00884b6a57.PNG)

**Comment by IntelOrca** [comment]
@Margen67 hiring staff is practically unsupported in multiplayer until we fix all the desync issues.
