### ISSUE TITLE
People are saying that Staff AI is considerably worse since the last stable

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#3125]
**OS: N/A** 
**Version: Since 0.0.3 at least.** 
**Commit: Inclusive?** 

Explanation of the issue...

- [ ] Reproducable in RCT2 (vanilla)?
- [x] Multiplayer? (Technically, yah...)

**Steps to reproduce:**
1. Place handyman 
2. Watch him be fairly useless, but still kinda work?

(Mostly in Streams and associated Chat's. Ask BlindiRL about it.)

**Comment by Wirlie** [comment]
I have the same problem, but, I don't know how to demonstrate this. The only solution I have found to this is to use the "patrols areas" with small areas.

**Comment by Wirlie** [comment]
Oh, I found a problem with Handyman AI.

Video: https://vid.me/J3Hr

**Comment by PFCKrutonium** [comment]
Yah, that pretty much shows what blind was experiencing - His handymen were also turning around after picking up puke, every time as far as I could tell.

**Comment by LRFLEW** [comment]
This might be related to #2499 as they both involve peeps making odd pathfinding decisions. However, since I know that the staff code was a recent decompile, it could be separate. I'll fix this issue if I find it while investigating the other one.

**Comment by Gymnasiast** [comment]
I'm not sure whether to put 'duplicate' on this bug, so I haven't done so.
Hopefully LRFLEW can figure it out, so we can ship a stable with pathfinding that isn't worse than it was in vanilla.

**Comment by audi0c0aster1** [comment]
Yep.  My paths are WAY dirtier now.  When I open a park in normal RCT (through steam) they work fine again

**Comment by IntelOrca** [comment]
@Wirlie do you have a saved game for that video you uploaded?

**Comment by LRFLEW** [comment]
@Wirlie I tried replicating what you saw (as it was the most clear-cut example I've seen so far) and couldn't get it to happen under an isolated instance. The closest I got was this (which is an original bug, AFAIK):
<img width="427" alt="screen shot 2016-03-15 at 2 11 35 pm" src="https://cloud.githubusercontent.com/assets/607715/13935550/e1f190b2-ef85-11e5-840c-feb847115bc0.png">

**Comment by Wirlie** [comment]
@LRFLEW @IntelOrca I think your problem was different to my problem because my problem still happens :(

Save game: 
[Vistas Infernales.txt](https://github.com/OpenRCT2/OpenRCT2/files/183362/Vistas.Infernales.txt)

**Comment by LRFLEW** [comment]
@Wirlie Don't open a new issue. I'll work on it from here.
