### ISSUE TITLE
Game can't find installation directory

### ISSUE THREAD

**Issue by defixje** [OpenRCT2/OpenRCT2#3127]
OS: Windows 7
Version: 0.0.4.0 build 3305bbd

When you start the game, the game asks for the installation directory. Even when you select the right directory it fails to start

Steps to reproduce:
1. start the game (version 0.0.4.0 build 3305bbd)

Screenshots:
![openrct2-error](https://cloud.githubusercontent.com/assets/1568058/13696455/bec2cae2-e766-11e5-9e57-c2edc9b37747.png)

**Comment by janisozaur** [comment]
What directory do you set? What are the contents of this directory?

**Comment by defixje** [comment]
I tried to set: C:\Program Files (x86)\OpenRCT2
![openrct2-structure](https://cloud.githubusercontent.com/assets/1568058/13696733/9fa9539a-e768-11e5-8fe7-d11cba4cef4c.png)

And: C:\Program Files (x86)\OpenRCT2\data
![openrct2-data-structure](https://cloud.githubusercontent.com/assets/1568058/13696767/c4586726-e768-11e5-80a3-c3bc18842db9.png)

**Comment by janisozaur** [comment]
That's your problem right there. You're selecting path to OpenRCT2, not RCT2.

**Comment by defixje** [comment]
Ah, so stupid! My bad! Thanks
