### ISSUE TITLE
Mechanic crosses station improperly during inspection / fix

### ISSUE THREAD

**Issue by Wirlie** [OpenRCT2/OpenRCT2#3130]
**OS:** Windows 10 (32 bits)
**Version:** 0.0.4
**Commit:** latest build

- [ ] ~~Reproducible in RCT2 (vanilla)?~~
- [ ] Multiplayer?

**Screenshots / Video:**
https://vid.me/jBYu

**Save game:**
[Vistas Infernales.txt](https://github.com/OpenRCT2/OpenRCT2/files/169721/Vistas.Infernales.txt)

**Comment by carlu93** [comment]
I can confirm this one. Experienced this yesterday too!

**Comment by Nubbiy** [comment]
Doesn't really affect the game that much but I understand he should stay on the same side when inspecting etc, don't remember how they acted in the vanilla :(

**Comment by Gymnasiast** [comment]
In vanilla they stayed on the side where they entered.

**Comment by Gymnasiast** [comment]
Fixed by #3161 (reportedly).
