### ISSUE TITLE
Localisation - Change "Disable land elevation" to "Paint Landscape"

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#3131]
**OS:Win 7** 
**Version:0.0.4.0** 
**Commit: dda036a** 

In the game, there is something called "Disable land elevation" which confused me as it didn't 'disable' anything, after it had taken me a while to figure it out, it painted the landscape without changing the height. I understand the *function* is to disable the land elevation so you just change the terrain but as a user, we don't see that, instead we consider it to be a paintbrush
 which represents painting stuff, a.k.a
"Paint Landscape"

How to fix:
**Change string;**
`STR_5127    :{SMALLFONT}{BLACK}Disable land elevation`
to
`STR_5127    :{SMALLFONT}{BLACK}Paint Landscape`

P.s; Said this before on Gitter to @Gymnasiast 

![paint](https://cloud.githubusercontent.com/assets/17282384/13714376/7e695052-e7ce-11e5-966f-cd58468c4bad.png)

**Comment by IntelOrca** [comment]
I think ```Paint tool``` might be a better tooltip for it.

**Comment by Gymnasiast** [comment]
I would prefer something along the lines of `While dragging, paint landscape instead of changing elevation`. Makes it clearer how it changes behaviour.

**Comment by Nubbiy** [comment]
@IntelOrca  Paint tool / Paint Landscape is what it does so both sounds right
@Gymnasiast  That sounds like a good description

Have more rants about the spellings/etc :p
For example; Disable Clearance Check (Will make a thread about it)

**Comment by Gymnasiast** [comment]
Since you considered my description good, I used it in 164d782.

**Comment by Nubbie** [comment]
@Gymnasiast It's a bit long for being a description in such a small window, but will still make an issue about this to all translators in [OpenRCT2/Localisation/issues](https://github.com/OpenRCT2/Localisation/issues)

**Comment by Gymnasiast** [comment]
It is a bit long, yes. But at least it's clear now what it does.
If you have an idea for a shorter string that is just as clear, please tell me. :)

**Comment by Nubbie** [comment]
@Gymnasiast The only thing I have is '`Paint Landscape`' or what IntelOrca said '`Paint tool`' but the description is also useful as it's more user friendly ^^
