### ISSUE TITLE
Invalid access to memory in `track_place`

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#3136]
It is possible to go over allocated memory when doing `game_command_place_track` for ride type = 255, `RIDE_TYPE_FLAG_FLAT_RIDE`.

https://github.com/OpenRCT2/OpenRCT2/blob/a3efbad/src/ride/track.c#L4889 -> https://github.com/OpenRCT2/OpenRCT2/blob/a3efbad/src/ride/track.c#L4454 -> https://github.com/OpenRCT2/OpenRCT2/blob/a3efbad/src/ride/track.c#L4053

Note:
`FlatRideTrackBlocks` defined here: https://github.com/OpenRCT2/OpenRCT2/blob/a3efbad/src/ride/track_data.h#L32, array of count 255
`TrackBlocks` defined here: https://github.com/OpenRCT2/OpenRCT2/blob/a3efbad/src/ride/track_data.h#L31, array of count 256

I'm not sure how to correct this, hence this issue. Should `FlatRideTrackBlocks` simply get one entry more?

**Comment by duncanspumpkin** [comment]
FlatRideTrackBlocks is just garbage info anyway for the invalid entries. You will see it overlaps the Track blocks entry 254 of flat is 208 of track. 253 of flat is 207 of track. So on so on.

**Comment by mrtnptrs** [comment]
Is this a real bug then? Or can we just close it?
