### ISSUE TITLE
Multiplayer Permissions should be Verified by the host before action is taken

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#3140]
**OS: All** 
**Version: All** 
**Commit: All** 

Explanation of the issue...

- [ ] Reproducable in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
> You will need [Cheat Engine](http://cheatengine.org/) for this: 
 [Cheat tables]( https://mega.nz/#F!pVYhSZbZ!zF_d57m2xNqQTWMdT7dJKw)

> After you've installed Cheat Engine open the cheat table, click the computer icon, then click openrct2.exe.

> After you join a server set the cheat's value you want to 1.

> This does not include Disable clearance checks as that doesn't do anything.

Source: https://www.reddit.com/r/openrct2/comments/4anv4m/tutorial_get_cheats_on_all_servers_even_without/

**Comment by IntelOrca** [comment]
Those cheat tables are only going to be valid for a particular build.

**Comment by IntelOrca** [comment]
The following cheats are unprotected:
```
gCheatsShowAllOperatingModes
gCheatsShowVehiclesFromOtherTrackTypes
gCheatsFastLiftHill
gCheatsDisableBrakesFailure
gCheatsDisableAllBreakdowns
gCheatsUnlockAllPrices
```

The rest will not not work, they would not persist on the server side.

**Comment by Margen67** [comment]
You can also own/disown land with Sandbox mode enabled even without cheat permissions.
And also remove, and create park entrances.
