### ISSUE TITLE
Freeze when fetching the server list

### ISSUE THREAD

**Issue by harrysbird** [OpenRCT2/OpenRCT2#3144]
**OS:**  Windows 10
**Version: fdead70** 
**Commit:**  Main Menu Screen Freeze

Explanation of the issue...

- [ ] Reproducable in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Load openrct2 game
2. Open multiplayer window / fetch servers

**Screenshots / Video:**
https://vid.me/zZPO

**Comment by Gymnasiast** [comment]
Does anyone else have this issue?

**Comment by janisozaur** [comment]
I think the important question here is happening because of server list or title screen? @harrysbird can you provide some insight?

**Comment by Nubbiy** [comment]
I have tried this with;
The launcher
A shortcut on the desktop
The game inside the OpenRCT2 folder 
**Nothing**

Note: Seem like it freezes on the video when it's suppose to load map "Netgrouppark.sv6" (The next map on the title sequence)

Tried to mess around with the map too:
If you remove it, the theme doesn't work and will just change to a different one
If you corrupt the file, the theme skips that map and keeps on playing normally

**Comment by harrysbird** [comment]
And it freeze if i clicked Fetch Servers

**Comment by Nubbiy** [comment]
Does it freeze if you change intro to Roller Coaster Tycoon 1?

**Comment by telk5093** [comment]
I think it freezes when the favorited server is offline.
(I had this issue once, so I unfavorited servers.)

**Comment by harrysbird** [comment]
My Current Theme: RCT1
Nubbiy: i changed it to rct1 and it still freeze

**Comment by IntelOrca** [comment]
@harrysbird just to be very clear... does it only freeze when you are on the multiplayer window?

**Comment by harrysbird** [comment]
yes

**Comment by Wirlie** [comment]
Today I have the same problem.

My game freezes for a long time, but after that, I get these messages in the console:

ERROR[src\network\http.cpp:152 (http_request_json)]: HTTP request failed: SSL connect error.
WARNING[src\windows\server_lisr.c:737 (fetch_servers_callback)]: Unable to connect to master server.

**Comment by Wirlie** [comment]
when I try to update the list of servers I get this message (debugging): 

Unhandled exception at 0x7714B659 (ntdll.dll) in openrct2.exe: 0xC0000005: Access violation reading location 0x091A2654.

**Comment by janisozaur** [comment]
Can you access https://servers.openrct2.website in a browser?

**Comment by janisozaur** [comment]
Do you certificate bundle from the repo?

**Comment by Wirlie** [comment]
Yes, I can access to https://servers.openrct2.website from my browser.

And... I do not know what you mean exactly. I have a file named "curl-ca-bundle.crt" on my repo, do you mean this?

**Comment by Wirlie** [comment]
I found a "solution", if you remove "servers.cfg" from the OpenRCT2 folder ("Documents\OpenRCT2") the problem is solved...

Probably the problem has to do with this.

**Comment by Wirlie** [comment]
[servers.txt](https://github.com/OpenRCT2/OpenRCT2/files/191079/servers.txt) (change the extension with ".cfg") I'm not sure if the problem can be reproduced, but I have attached the file.
