### ISSUE TITLE
Game is locked into saving track designs as "TD?"

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3145]
Ever since I downloaded this newer version of OpenRCT2, every time I try to go save a track design, it attempts to save it as a TD? instead of a TD6. And if I do change it to TD6, it says it's an "invalid" file type.

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/pull/3009

**Comment by Superjustinbros** [comment]
I don't really see how this helps the problem.

**Comment by janisozaur** [comment]
why don't you give 8b85030 a try?

**Comment by IntelOrca** [comment]
Duplicate of #3112
