### ISSUE TITLE
Korean strings saved strangely

### ISSUE THREAD

**Issue by YJSoft** [OpenRCT2/OpenRCT2#3146]
**OS: Windows 7** 
**Version: 0.0.4** 
**Commit: fdead70** 

Explanation of the issue...

- [ ] Reproducable in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Rename ride/shop/park names to `관람차`
2. Save and reload
3. Name will became `관`
4. This is one example of being cutted. look video below.

**Words causing cut(everything after this character will be cut):**
 * `관`
 * `가`

**Screenshots / Video:**
https://vid.me/Xady
all shop names are cutted. and even notifications are cutted. some are not effected though.

**Save game:**
[LL.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/180525/LL.sv6.txt)

**Comment by telk5093** [comment]
혹시 #3121 때문에 생긴 건 아닐까요?
그 이전엔 이런 이슈는 없었는데...

Isn't it caused by the pull request #3121?
There was no such issues before.

**Comment by YJSoft** [comment]
UTF8 Hex of `관` is `EA B4 80` and `가` is `EA B0 80`.
both are end with `80`

and since `utf8_is_codepoint_start` function returns true if hex is 0x80, last hex of `관` and `가` is reconiged as utf8 codepoint start.
https://github.com/OpenRCT2/OpenRCT2/blob/b694246fb5c5e83de81c59c202d268156f78e441/src/localisation/utf8.c#L70

**Comment by YJSoft** [comment]
@IntelOrca save file is currupted after cb9a4860f39707369508b5830842fc42d7090c6f
[LL_C.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/180785/LL_C.sv6.txt)
