### ISSUE TITLE
Save any file with korean would corrupt save file

### ISSUE THREAD

**Issue by YJSoft** [OpenRCT2/OpenRCT2#3151]
**OS: Windows** 
**Version: 0.0.4** 
**Commit: cb9a486** 

Explanation of the issue...

- [ ] Reproducable in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Save any file with korean
2. Load saved file
3. some ride/shop name will empty and game will crash
4. If pause, game will not crash, but ride names will not be changed.(if change, some other shop/ride name changed together)

**Save game:**
[LL_C.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/180816/LL_C.sv6.txt)

**Comment by IntelOrca** [comment]
@YJSoft Sorry about that, should be okay now.
