### ISSUE TITLE
Random Title Sequence

### ISSUE THREAD

**Issue by jloutsenhizer** [OpenRCT2/OpenRCT2#3154]
It'd be cool to randomly select title sequence just like how you can randomly select music for it.

**Comment by Nubbiy** [comment]
![title](https://cloud.githubusercontent.com/assets/17282384/13910424/479fbcb8-ef22-11e5-88ea-08d996f40d60.png)
You can, you can also make your own title sequence
Go to Options -> Miscellaneous -> Title Sequence
