### ISSUE TITLE
Crash at object selection screen

### ISSUE THREAD

**Issue by fromthere** [OpenRCT2/OpenRCT2#3156]
**OS: OS X** 
**Version: 0.0.4** 
**Commit: 78f87cd** 

Explanation of the issue...

- [ ] Reproducable in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open object select screen or go to coaster design mode
2. game crashes
3. below is console output
OpenRCT2(17391,0x329000) malloc: *** error for object 0xffffffff: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

```cpp
/**
 *
 *  rct2: 0x006A982D
 */
void object_free_scenario_text()
{
	if (RCT2_GLOBAL(RCT2_ADDRESS_SCENARIO_TEXT_TEMP_CHUNK, void*) != NULL) {
		free(RCT2_GLOBAL(RCT2_ADDRESS_SCENARIO_TEXT_TEMP_CHUNK, void*)); <- This
		RCT2_GLOBAL(RCT2_ADDRESS_SCENARIO_TEXT_TEMP_CHUNK, void*) = NULL;
	}
}
```

**Screenshots / Video:**
Drag / drop screenshots here. Use https://vid.me to upload video.

**Save game:**
Change the file extension to .txt or package to a .zip so that it can be drag / dropped here...

**Comment by fromthere** [comment]
I installed RCT2 at windows and copied all contents to my macbook.
if i disable free line, everything works fine.

**Comment by IntelOrca** [comment]
I can't reproduce this on Windows.

**Comment by fromthere** [comment]
Tested on 0.0.5-develop, 0af21afcc81c0aa2af22511c8a30f1478f3e10a2

1. Change language to non-english one(like korean) and close game
2. delete plugins.dat
3. load game
4. change language to english
5. since plugins.dat created with korean, now all objects are named ??
6. hover object/track design/etc
7. It works well on windows, but it crashes at OSX

**Comment by IntelOrca** [comment]
Probably not applicable any more.
