### ISSUE TITLE
Clicking X on the map downloading screen should cancel the connection

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#3158]
**OS: N/A (Tested on Arch)** 
**Version: 0.0.4** 
**Commit: 52c6824** 

Explanation of the issue...

- [ ] Reproducable in RCT2 (vanilla)?
- [X] Multiplayer?

**Steps to reproduce:**
1. Connect to a server
2. Try to stop

**Comment by Nubbiy** [comment]
Thought I already had reported this.. or it might just have been on the forums
Anyways, glad it's fixed :p
