### ISSUE TITLE
Land not owned by park issue when trying to build a roller coaster in Roller Coaster Designer

### ISSUE THREAD

**Issue by birthdaybrian** [OpenRCT2/OpenRCT2#3160]
**OS: Windows 7 Home Premium x64 SP1 with Windows 8.x UI** 
**Version:0.0.4-4** 
**Commit:79f2316** 

Hey developers. When I try to build a roller coaster in Roller Coaster Designer mode, I kept getting this message saying "Land not owned by park". There was also no park fences when I was in Roller Coaster Designer mode and when I came back to Roller Coaster Designer mode after enabling Sandbox mode, the park fences came back and I can finally build in Roller Coaster Designer. Can any developer please fix this issue?

**Steps to reproduce:**
1. Go into Roller Coaster Designer mode by click on the toolbox icon and hover to Roller Coaster Designer.
2. Pick any coasters that you want to build in Roller Coaster Designer.
3. Try build a roller coaster to see if you get this error message like me.
4. Check to see if there are park fences in Roller Coaster Designer.
5. Let me know if you are getting the same issue as me.

**Comment by duncanspumpkin** [comment]
Issue caused by a2fda29d924cced77dc20d21543518b9a979bad6. I was going to change how the track designer does its load but there are more than one function expecting this function to succeed `map_remove_out_of_range_elements` for example.

**Comment by IntelOrca** [comment]
I thought the land is pre-owned in the rollercoaster designer... I thought it sets all the land to owned when you start the designer. Perhaps there is another bug that is also causing this.

**Comment by birthdaybrian** [comment]
@IntelOrca In the Vanilla version of RollerCoaster Tycoon 2, land is pre-owned in Roller Coaster Designer.

**Comment by duncanspumpkin** [comment]
@intelorca it does preown the land but it uses the normal buy land command and that fails as it tries to buy the land before setting the screen flag to say it's in editor mode. My main issue is that there are other functions that don't expect your extra checks.

**Comment by IntelOrca** [comment]
@duncanspumpkin oh, right that makes sense. How annoying.
