### ISSUE TITLE
Renaming files in System Dialogue window crashes game

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3164]
**OS:** Windows 7

Earlier today I tried renaming a file in the system dialogue window accessed while Open RCT2 is running after selecting to save a game. After I renamed the file and hit enter, both the dialogue window and the game became unresponsive.

I cannot seem to replicate the issue, though it definitely happened during an online session.

**Comment by Nubbie** [comment]
This is a bit old now and there is no dump file nor more reports about it, maybe just were a one timer so it could be closed?
