### ISSUE TITLE
New peeps incorrectly enter first path tile

### ISSUE THREAD

**Issue by JarnoVgr** [OpenRCT2/OpenRCT2#3171]
**OS:** Win10 x64
**Version:** 0.0.4
**Commit:** 474f25c

Peeps who are about to enter the park incorrectly enter the first path tile. Happens in Amity Airfield. Didn't test other scenarios.
- [ ] Reproducable in RCT2 (vanilla)?
- [X] Multiplayer?

**Steps to reproduce:**
1. Start Amity Airfield scenario.
2. Look at entrance

**Screenshot (animated GIF):**
![2016-03-25_17-29-53](https://cloud.githubusercontent.com/assets/2751672/14048585/84a62314-f2af-11e5-94d4-ccba0133ae99.gif)

**Comment by marcovmun** [comment]
This is also when they leave an exit of a rollercoaster and they have to walk immediately left or right. I think that is almost the same bug.

**Comment by IntelOrca** [comment]
Does this happen in vanilla RCT2, with Amity Airfield?

**Comment by JarnoVgr** [comment]
I'm unable to test this in vanilla. Could anyone else do this? Thanks in advance.

**Comment by marcovmun** [comment]
This bug is also present in vanilla. My comment is also present in vanilla
