### ISSUE TITLE
Idea: Allow changing salary for faster walking/working staff

### ISSUE THREAD

**Issue by JarnoVgr** [OpenRCT2/OpenRCT2#3172]
I'm sure people will disagree with this idea. But I'll give it a shot anyways:

It would be fun to be able to change the salary of a staff group (handymen, mechanic etc.) to let them work faster, or even slower when the salary is less than the default salary for that group.

Could be implemented per staff member, or globally per group. I'm fine with one of them, or both.

**Comment by AaronVanGeffen** [comment]
This sounds like something that would probably make a great mod at some point.

**Comment by Gymnasiast** [comment]
As a mod, yes. It doesn't fit into the feel of RCT1/2 as far as I'm concerned, but what people will do with mods is up to them of course.

Incidentally, I am interested to see how many people actually like this feature of RCT3.

**Comment by PFCKrutonium** [comment]
It wasn't well implemented in RCT3, it was used more as a way to keep people from Quitting than for any real benefit as far as I could tell. However, I think OpenRCT2 as a mod, it would a) Make far more sense and b) not suck.

**Comment by Richard-L** [comment]
I'm against this as it breaks with the nature of a game. If you add a mod engine, maybe, but I think it's nice how the project stays true to the original game.

**Comment by Gymnasiast** [comment]
@Richard-L : Don't worry, I wouldn't want it directly in the game, and neither does IntelOrca. But as I said, what people do with mods is up to them.

**Comment by Patrik356b** [comment]
It doesn't make sense in RCT, it did in Theme Park World but that's a different game
