### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [OpenRCT2/OpenRCT2#3175]
I would like to point out that identifiers like "[`_ENTRANCE_H_`](https://github.com/OpenRCT2/OpenRCT2/blob/569fd7771c0a1799879c8c4501f2fac32e6af08d/src/world/entrance.h#L21)" and "[`_RCT2_H_`](https://github.com/OpenRCT2/OpenRCT2/blob/a99a2f0cf46102a441a0e260d9d9fa5e59b152eb/src/rct2.h#L21)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by IntelOrca** [comment]
Feel free to change these, but when we turn a file into C++ it will be using ```#pragma once```

**Comment by elfring** [comment]
How much do you care for [standard compliance](http://stackoverflow.com/questions/23696115/is-pragma-once-part-of-the-c11-standard/23699893#23699893 "Is #pragma once part of the C++11 standard?") of the affected source files?

**Comment by IntelOrca** [comment]
None if it means we can use very useful directives like ```#pragma once``` and ```#pragma region```

**Comment by janisozaur** [comment]
While I'm mostly on "stick with the standards" side usually, I think this pragma is very useful.

See also https://en.wikipedia.org/wiki/Pragma_once#Portability
