### ISSUE TITLE
Keyboard layout wrong in keyboard shortcuts

### ISSUE THREAD

**Issue by rvgr** [OpenRCT2/OpenRCT2#3177]
**OS:** MacOS 10.11.4
**Version:** 0.0.4

When settings keyboard shortcuts, if you have an AZERTY keyboard, it will display the QWERTY character.

For example, if you set a shortcut to A, it will be shown as Q. However it will work when pressing A.
- [ ] Reproducable in RCT2 (vanilla)?
- [ ] Multiplayer?

**Comment by mrtnptrs** [comment]
Does someone have an AZERTY keyboard and can reproduce this too?

**Comment by Goddesen** [comment]
This holds true for any non-qwerty keyboard layout (tested with colemak).
