### ISSUE TITLE
cmake complaining about cyclic dependencies

### ISSUE THREAD

**Issue by Joaz** [OpenRCT2/OpenRCT2#3182]
**OS:** Ubuntu
**Version:** Trusty
**Commit:** b436ac9bc6c56d4760ab1b48c2762b7081c7ff45

I'm having troubles getting OpenRTC2 to build. I've installed all dependencies (libpng16 and jansson 2.7 by source), now cmake is complaining about this:

$ cmake .
-- Configuring done
CMake Error: The inter-target dependency graph contains the following strongly connected component (cycle):
  "linkable_sections" of type UTILITY
    depends on "segfiles" (strong)
  "openrct2" of type EXECUTABLE
    depends on "linkable_sections" (strong)
    depends on "segfiles" (strong)
  "segfiles" of type UTILITY
    depends on "openrct2" (strong)
At least one of these targets is not a STATIC_LIBRARY.  Cyclic dependencies are allowed only among static libraries.
-- Build files have been written to: /home/jglauche/src/OpenRCT2

It says that it has written build files but it doesn't produce any build files. 

I have tried option static both ON and OFF. It doesn't make a difference. 

Any ideas to fix that?

**Comment by janisozaur** [comment]
We don't support building in-tree, you have to make a build dir.

**Comment by janisozaur** [comment]
Also, trusty is not supported very well. You'll need packages that may break or at least upset your dpkg.

**Comment by Joaz** [comment]
creating a build dir and doing 
cmake ../ 

does not fix the problem. 

I think I have dealt with the dependency packages (I'm running on x86_64 btw, and the precompiled 32 bit version is indeed quite hard to find all dependencies for on trusty).

**Comment by janisozaur** [comment]
1. We continuously test using exactly such setup, so I'm not sure what's different in your case. Perhaps you have something cached, `git clean -df` in toplevel should help with that
2. We have a PPA set up that automatically builds latest version of OpenRCT2, the builds happen once or twice a day: https://launchpad.net/~openrct2/+archive/ubuntu/nightly you may want to use that if you just want to use it (as opposed to building/hacking). Trusty is problematic, so as soon as Xenial becomes available (and proper libpng16, which debian folks have problems with), I'll make this the minimum.
3. We have travis set up to push the linux builds to the openrct2.org website, you can use that as well
4. If that still does not resolve your issue, you may want to get in on some more real-time action with us on https://gitter.im/OpenRCT2/OpenRCT2

**Comment by Joaz** [comment]
Actually, you were right. It's more of a hassle than I thought.

First, it seems that cmake isn't set up to figure all out requirements because it forces you to cross compile it.

- I had to install libc6-dev-i386.
- I had to install zlib1g-dev:i386, which basically removed all my build system (reinstalled build-essential and g++-4.8-multilib

Next, the 64-bit dev package of curl is acting up. 

 Building CXX object CMakeFiles/openrct2.dir/src/network/http.cpp.o
In file included from /usr/include/curl/curl.h:35:0,
                 from /home/jglauche/src/OpenRCT2/src/network/http.cpp:21:
/usr/include/curl/curlrules.h:143:41: error: size of array ‘__curl_rule_01__’ is negative
     [CurlchkszEQ(long, CURL_SIZEOF_LONG)];
                                         ^
/usr/include/curl/curlrules.h:153:53: error: size of array ‘__curl_rule_02__’ is negative
     [CurlchkszEQ(curl_off_t, CURL_SIZEOF_CURL_OFF_T)];

replacing it by the i386 package of libcurl4-openssl-dev fixed that.

Building works so far, the linker now complains that my self-build libraries are not compatible. Yes, I know. Gotta compile those for 32 bit.

Are there any big hurdles in compiling the whole thing in 64 bit..?

**Comment by janisozaur** [comment]
You can use `cmake -DDISABLE_HTTP_TWITCH=ON` as a workaround for curl woes.

We don't support 64 bit builds yet and we won't be able to for a while to come yet.

The biggest issue I've encountered when I tried using that on Trusty was installing `sdl2:i386` tried to remove half of the system.

A viable workaround would be using our docker images (see `.travis.yml`) which contain a barebone Arch, building it there and running from inside a container.

**Comment by janisozaur** [comment]
I've added a change now which will prevent user from such mistakes. It will close this issue, but feel free to re-open it if need be.

**Comment by Joaz** [comment]
Ok, giving up right now @ linking. The PPA is wonderful though!

That link PPA link should go to the documentation, either in the readme file or in the linux building wiki document linked there.

**Comment by janisozaur** [comment]
Good to hear that. I've never got around to updating the docs, would you do that?
