### ISSUE TITLE
Park not owned in Coaster Designer

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#3184]
**OS:** Windows
**Version:** 10
**Commit:** 474f25c

When trying to build a ride in the Coaster Designer, an error message is prompted about the land not being owned.

**Steps to reproduce:**
1. Open the Coaster Designer
2. Select any ride
3. Try to place a track or build one

**Comment by IntelOrca** [comment]
Already fixed in b436ac9bc6c56d4760ab1b48c2762b7081c7ff45
