### ISSUE TITLE
Crash When Selecting Track From Track Design Window On Ride Limit

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#3185]
**OS:** Windows
**Version:** 10
**Commit:** d690ee64239425db49960f6886eda5048812feaa

Picking a track from the Track Design Window when the ride limit has been reached results in an infinite loop. The following message is being spammed to the output: `Track map element part not found!` (https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/ride/track.c#L5056)

**Steps to reproduce:**
1. Load a park that hit the ride limit
2. Choose any ride that has track designs
3. Pick one

**Save game:**
You can use [this saved game](https://github.com/OpenRCT2/OpenRCT2/files/191033/Community.Park.V2.89.zip) as it has hit the ride limit already.

**Comment by Stevoisiak** [comment]
Recreated in 0.0.5, commit 171c4f2
[Video](https://www.youtube.com/watch?v=ZQmZx9dlWFw)

**Comment by Nubbie** [comment]
Could not reproduce it now, should have been fixed a while back

**Comment by Broxzier** [comment]
Confirmed that this does not happen anymore.
