### ISSUE TITLE
Show real names of guests toggles automatically

### ISSUE THREAD

**Issue by LinusU** [OpenRCT2/OpenRCT2#3187]
**OS:** OS X
**Version:** 0.0.4
**Commit:** e6ca13d

"Show 'real' names of guests" is toggled automatically back and forth while being on the title screen.

**Steps to reproduce:**
1. Stay on title screen
2. Open options
3. Observe the "Show 'real' names of guests" option

**Comment by IntelOrca** [comment]
The option is stored in the saved game.

**Comment by LinusU** [comment]
Hmm, but won't that mean that if I open the setting and select my preference, it might have been overwritten when I start a game?

Or should I only toggle it while in a game?

Ahh, so actually this option doesn't affect anything when being outside of a game? Maybe we could gray it out when not inside a game (i.e. at the title screen)?

**Comment by IntelOrca** [comment]
When you start a new scenario, it will use whatever the selected value currently is. The original game had this problem, but I suppose it was less obvious as it only had one title screen scenario. However that would keep resetting it back to real names.
