### ISSUE TITLE
Translation encoding problem.

### ISSUE THREAD

**Issue by fbourigault** [OpenRCT2/OpenRCT2#319]
I'm translation the language strings to french and I have problems with accents. French.txt is encoded as utf-8. Is it a code issue or should I change french.txt as something else ?

**Comment by s0r00t** [comment]
I have the same problem with French translation and French RCT2 : 
![Picture of the bug.](http://i.imgur.com/zrzVVnw.png)  
However, those are translations from the DAT files, they aren't in french.txt

**Comment by AaronVanGeffen** [comment]
Is the translation file you're using encoded properly, i.e. using UTF-8?

**Comment by Gymnasiast** [comment]
@AaronVanGeffen : It's the .DAT descriptions in plugin.dat not showing up correctly.

**Comment by Gymnasiast** [comment]
@s0r00t : Which part of the interface is that? And are you using stable or develop?
