### ISSUE TITLE
!news twitch command does not work

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#3191]
When a streamer has the option enabled, when `!news test` is typed into the stream's chat, OpenRCT2 replies that a message will soon be displayed (in chat), but the message never gets through to the bottom news bar.

This has been broken for a while now.

**Comment by PFCKrutonium** [comment]
It's been broken for a VERY long time afaik, BlindIRL hasn't been able to use it for... Basically since a while after it was implemented afaik.

**Comment by IntelOrca** [comment]
fixed in f955d03206c67e0661c1f9d1066167e0a82e0e54
