### ISSUE TITLE
RCT1 natively

### ISSUE THREAD

**Issue by Richard-L** [OpenRCT2/OpenRCT2#3194]
Rather than scenario being modelled after RCT1 and played in OpenRCT2, would you consider adding RCT1 natively?

Effectively have both games supported.

**Comment by PFCKrutonium** [comment]
That is a planned feature, but first we have to move to our own save format so that we can re-introduce the path types, terrain, and the rest.

**Comment by AaronVanGeffen** [comment]
Not all of it depends on using our custom file formats. Work on this is ongoing in the [rct1-import](https://github.com/OpenRCT2/OpenRCT2/tree/) branch.

**Comment by PFCKrutonium** [comment]
That is true, but it won't be a 1:1 import until we do.

**Comment by Gymnasiast** [comment]
This has been on the list for months, and I have indeed worked on it in the rct1-import branch. We will eventually add support for the missing features from RCT1, like the missing land types, and you will be able to import RCT1 scenarios and saves directly.
