### ISSUE TITLE
People bowling after coaster hit guests in RCT2

### ISSUE THREAD

**Issue by birthdaybrian** [OpenRCT2/OpenRCT2#3195]
This is like RollerCoaster Tycoon 3 when the coaster crashes to the paths, the coaster hits guests and they slide off the path. I remember seeing a video like that a long which the video can be found here: https://youtu.be/uQrC_C6SexI and recently when I was in a server, somebody tried to do the same thing but doesn't bowl guests after the coaster crashes. Can any developer please add this feature in the next version which is 0.0.5?

**Comment by PFCKrutonium** [comment]
That was never a feature in RCT or RCT2, and it would require new graphics. It would also require a pile of new code to handle coasters hitting peeps, and it just wouldn't be worth it imo. Maybe someday though.

**Comment by birthdaybrian** [comment]
@PFCKrutonium I know this feature did not appear in RCT1 and RCT2. And I agree that this will require new graphics.

**Comment by PFCKrutonium** [comment]
Additionally, *think of the peeps*! ;)

**Comment by Wirlie** [comment]
But, if this is implemented ... would not make sense that people die in a roller coaster accident (instead, people should die if the coaster hits them, but this would make the game more "sadistic").

I do not agree.

**Comment by Gymnasiast** [comment]
I disagree with this. People dying - and additionally: finding ways to kill them - is part of what makes classic RCT.

**Comment by Patrik356b** [comment]
Perhaps this could be a mod later
