### ISSUE TITLE
Can't raise water or land without deleting scenery / through a ride

### ISSUE THREAD

**Issue by phannG** [OpenRCT2/OpenRCT2#3196]
**OS:** Any dev branche
**Version:** ^
**Commit:** ^
Explained in this picture https://gyazo.com/23de30c3b378ac8242754da739bd725c, issue was also on a topic on nedesigns http://www.nedesigns.com/topic/32012/openrct-advantages-and-disadvantages/

Alternatively the waterraise trick through rides are also not possible.

All of this is possible with 8cars no clearance in RCT2.

**Comment by Gymnasiast** [comment]
A note: this should be allowed when the game is set to 'Disable clearance checks'.

**Comment by phannG** [comment]
Yea, land raising/lowering works with slanted fences and walls. But any other scenery item not. 

Same goes for water, lowering scenery into water works (but not with fences/walls). But raising water through scenery is not possible/or will remove scenery if its 1 unit above water.
