### ISSUE TITLE
Have a cake for our second birthday

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#3197]
https://github.com/OpenRCT2/OpenRCT2/commit/643db7ae017e04d13980031b449d747e3bf89c22, the initial commit, happened on `Wed Apr 2 00:31:55 2014 +0100`, which will be two years ago in just a few days. We should have cake :) :cake: :calendar: :fireworks: 

~~Instead of~~ In addition to cake we could also finally release 0.0.4 :)

**Comment by devnoname120** [comment]
Congratulations! :birthday: :tada:

**Comment by lopezloo** [comment]
:cookie: :cookie: :cookie:

**Comment by dlee13** [comment]
:cake: :fish_cake: :raised_hands: 

But it doesn't look like we'll be ready to release by then unless we push some things to 0.0.5 :open_mouth:

**Comment by Joshwoo69** [comment]
Implement a cake shop which sells openrct cakes... secret feature.

**Comment by IntelOrca** [comment]
Like this?

![OpenRCT2 cake](http://i.imgur.com/YN6sO1V.jpg)

**Comment by LinusU** [comment]
Wow!! That looks really good :+1:
