### ISSUE TITLE
Minor issue: "Build window" is not closed if you click on "vehicle options".

### ISSUE THREAD

**Issue by Wirlie** [OpenRCT2/OpenRCT2#3200]
**OS:** w10 (x86)
**Version:** 0.0.4
**Commit:** latest commit

On RCT2 the "build window" is closed if you click on the button "vehicle options" on the ride window, but, on OpenRCT2 it not happens. This bug generate a "miscalculation" with the number of cars (https://vid.me/t3kZ).
- [ ] ~~Reproducable in RCT2 (vanilla)?~~
- [ ] Multiplayer?

**Screenshots / Video:**
RCT2: https://vid.me/4SiH
OpenRCT2: https://vid.me/qiUm

**Comment by Christipher** [comment]
this appears on many finished rides as well - if you look closely at the looping roller coaster, it somehow cannot fit 7 cars in 6 station platforms yet it somehow never uses any portion of that last block.

**Comment by Wirlie** [comment]
@Christipher, that's exactly what I've seen in many roller coasters.

**Comment by Wirlie** [comment]
oh, I think I know what is the problem. On RCT2 the "build window" is closed if you click on "vehicle details and options" on the ride window, but, on OpenRCT2 it not happens ("build window" does not close if you click on "vehicle options") and this generate a miscalculation on the number of cars.

**Comment by Wirlie** [comment]
@Christipher What you've said is true, but this is a original bug from the vanilla game.

**Comment by Christipher** [comment]
yep - many rides suffer in varying degrees from this bug - some more than others (the only reason I bring up the looping roller coaster is that it is one of the more extreme examples of general calculation errors in gross - it naturally calculates incorrectly on longer trains).

**Comment by Gymnasiast** [comment]
@Christipher : Stay on-topic please. What you describe is another bug entirely.
