### ISSUE TITLE
Saves, Screenshots, ObjData - path management

### ISSUE THREAD

**Issue by Richard-L** [OpenRCT2/OpenRCT2#3201]
I've installed Open on two windows machines. One with the TTP Demo, the other with the game previously installed. In the first case, everything is sourced in the OpenRCT2 folder. The second case uses the RCT2 dir, as well as %userprofile%\Documents\OpenRCT2.

I don't want to mix the two. It be nice to allow a choice which destination is used. Eg "use default" or "RCT2Open folder".

**Comment by JarnoVgr** [comment]
Are you sure the first machine doesn't also use the Documents folder for user settings etc.?

**Comment by IntelOrca** [comment]
You can specify the user directory / config directory by command line.

**Comment by Richard-L** [comment]
Where can I find that? And don't you want to give people such option in the GUI?

Further on this, ORCT2 seems to build a library of all opened parks in %userprofile%\<user>\Documents\OpenRCT2\save

Can I turn this off and only have it read what I keep in <install-dir>\save ?

**Comment by janisozaur** [comment]
Just pass `--user-data-path=/your/user/path`. you can see all the options using `--help`

**Comment by Gymnasiast** [comment]
OpenRCT2 deliberately stores the data you create in the %userprofile%\Documents\OpenRCT2 folder (except for the saved track designs, but that is planned). Storing it in its own folder is bad design and discouraged since Windows NT 3.1 (and causing problems since Vista started enforcing this more).
