### ISSUE TITLE
Move away from Speex to Opus [Suggestion]

### ISSUE THREAD

**Issue by hcorion** [OpenRCT2/OpenRCT2#3202]
Currently SpeexDSP is a requirement of OpenRCT2. If you go to the speex website, http://www.speex.org/ It will tell you that 
> The Speex codec has been obsoleted by Opus.

and that 
> Opus is better than Speex in all aspects, users are encouraged to switch

I would like to suggest we move away from Speex and adopt Opus instead, being that it is newer, will receive bug fixes faster, is more frequently used, and is "better than Speex in all aspects".
I don't have any experience programming OpenRCT2, so I have no idea what this would include, but the entire audio portion (src/audio/) of OpenRCT2 is 4 files, so I assume it can't be that bad :P.

**Comment by harrysbird** [comment]
hcorion have you learn c++ and c#

**Comment by zsilencer** [comment]
we dont actually use the speex codec, only the resampler, which we are taking from speexdsp package and it is up to date. (opus-tools uses this as well)

**Comment by janisozaur** [comment]
Even though we don't use such codec now, this could be used as a base for our own format, so moving to opus might still prove to be a viable option.

**Comment by Gymnasiast** [comment]
Considering @zsilencer 's comment and the fact he wrote the audio layer and seems to know his stuff I'll close this.

**Comment by janisozaur** [comment]
> speexdsp package and it is up to date

No it is not. I found it when investigating some audio issue.

Windows is using speex 1.2rc1, which pre-dates a split to speex & speexdsp. There were some bugs fixed in the resampler, so I may update the library some time in the future, but if anyone wants to take it, then it's fine.
