### ISSUE TITLE
Can't right click to open track editor outside of owned land.

### ISSUE THREAD

**Issue by Michaelfonzolo** [OpenRCT2/OpenRCT2#3204]
**OS:** Windows 7
**Version:** 2.01.028

Not sure if an issue for this has already been opened or not, but if you select "Enable Sandbox Mode" then build a roller coaster outside the park boundaries, right clicking a piece of track outside owned land won't open the track editor.

**Steps to reproduce:**
1. Open any park.
2. Enable sandbox mode in the cheats.
3. Build a simple roller coaster that leaves the owned land boundaries.
4. Right click on a piece of track that is not on owned land.

**Comment by IntelOrca** [comment]
You need sandbox mode enabled to right click track because I didn't want to remove the original check for whether you own the land or not - it must have been there for a reason.
