### ISSUE TITLE
Unlimited Money Generation via Car Ride Construction

### ISSUE THREAD

**Issue by BWBuchanan7** [OpenRCT2/OpenRCT2#3206]
**OS:** Windows 8.1 64bit
**Version:** 0.0.4.0-beta
**Commit:** d07e471

While attempting to build a Car Ride I realized at certain (relative) elevations I am able to generate money rapidly by constructing and demolishing a Station Platform. This bug seems to be present on any scenario where the Car Ride is available (I tested this in Leafy Lake, Forest Frontiers, Crazy Castle and Electric Fields)

For example it will cost me (bear with me as I am using Yen as my currency) 3,000 to build a Station Platform but I will receive 3,100 on demolishing it. (That said I did try this with dollars and found I could spend $20 to build and would receive $21 when demolishing). Again, this only seems to work at certain elevations, here's the values I'm finding:

Elevation of Platform (units) | Cost to Build (Yen) | Funds Returned on Demolish (Yen)
------------ | ------------- | -------------
0 | 1,800 | 1,800
1 | 2,000 | 2,100
2 | 2,300 | 2,300
3 | 2,500 | 2,600
4 | 2,800 | 2,800
5 | 3,000 | 3,100 

I can't guarantee this isn't happening with other rides, but I certainly haven't noticed it with others.

- [ ] ~~Reproducable in RCT2 (vanilla)?~~ No.
- [ ] Multiplayer? Not tested.

**Screenshots / Video:**
![2016-03-31 13_26_58-openrct2](https://cloud.githubusercontent.com/assets/9372264/14188237/5f1b5c74-f744-11e5-918a-b7c038460b06.png)

![2016-03-31 13_27_06-openrct2](https://cloud.githubusercontent.com/assets/9372264/14188242/644db598-f744-11e5-9666-9dbf0501e1ef.png)

**Comment by IntelOrca** [comment]
Can someone check if this happens on vanilla RCT2?

**Comment by BWBuchanan7** [comment]
Had to boot up another PC to test this as my Windows 8 laptop does not seem to like vanilla RCT.

This does not occur in vanilla RCT2 as it charges the greater amount, resulting in a table like this (where I have bolded the valued that are different from OpenRCT2):

Elevation of Platform (units) | Cost to Build (Yen) | Funds Returned on Demolish (Yen)
------------ | ------------- | -------------
0 | 1,800 | 1,800
1 | **2,100** | 2,100
2 | 2,300 | 2,300
3 | **2,600** | 2,600
4 | 2,800 | 2,800
5 | **3,100** | 3,100

**Comment by janisozaur** [comment]
Nice find & report, thanks @BWBuchanan7!
