### ISSUE TITLE
Move autosaves to a subfolder of /save

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#3209]
When attempting to load a game the list is a bit littered due to the autosaves. It would be nice to have them in a subfolder of /save, so they're still easily accessible in case they're needed. (This is also how OpenTTD does it.)

**Comment by janisozaur** [comment]
Someone proposed to simply have a horizontal bar separating autosaves from the user-made ones, but I think perhaps the subdirectory is a better option.

**Comment by devnoname120** [comment]
I would prefer an horizontal bar. It is a bit annoying to always have to go inside the folder prior to loading an auto save.

**Comment by Richard-L** [comment]
I agree it's necessary to separate autosaves somehow.

**Comment by Patrik356b** [comment]
Preferably there would be a setting for this in the config file. I'd vote for autosaves in a subfolder as the default though

**Comment by Stevoisiak** [comment]
I'll second the idea of a subfolder.
