### ISSUE TITLE
Scenery window scrolls wrongly after selecting item

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3210]
**OS:** Windows 7

Explanation of the issue...

- [Unsure] Reproducable in RCT2 (vanilla)?
- [Occurs in both SP and MP] Multiplayer?

**Steps to reproduce:**
1. Select a scenery object on the last on one of the last rows.
2. Let the window auto-adjust itself, and when you scroll the cursor back over the  scenery window, it will crop wrong and at least one of more of the rows underneath the selected object would be blank.

**Screenshots / Video:**
![rct2 selectino problem](https://cloud.githubusercontent.com/assets/4167951/14211561/b9718fb4-f7fc-11e5-9cbc-e1344d4caef2.png)

**Comment by Gymnasiast** [comment]
I have had this bug plenty of times in vanilla, so marking as `original bug`.

**Comment by marcovmun** [comment]
I think that this commit solves the bug, This bug is very annoying when placing objects
