### ISSUE TITLE
Phantom vandalism

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#3213]
From discussion in https://openrct2.org/forums/topic/1082-idea-option-to-auto-remove-bencheslampslitter-bins-on-4-way-paths/

> As described [here](http://www.jumpjet.info/Classic-Games/Windows/RCT/Infrastructure/phantom/phantom.html), there is this term called "Phantom Vandalism" where after you place benches/lamps/litter bins on a path, then connect the path with the objects were so it connects to more paths on all sides, you can no longer see the object you placed, but it technically still exists and can be vandalized like any other path object. 

Verbatim of the linked page:

Phantom Vandalism
by Greg Wolking

Have you ever had problems with guests complaining about the vandalism in your park but no matter how closely you look, you can't see the broken object (bench, trashcan, or lamp) that they're complaining about? If so, you're the victim of "phantom vandalism", and it happens because of a quirk in the game. Here's how it works:

You start with a path segment that has an object (a bench in this example) on it:
![1](https://cloud.githubusercontent.com/assets/550290/14216817/1a9cd5ca-f84b-11e5-9fa8-b1a400dc8a5d.jpg)

You connect two other paths (or shops or ride entrances/exits) to your path, creating a 4-way intersection. The object disappears:
![2](https://cloud.githubusercontent.com/assets/550290/14216819/1cd4da72-f84b-11e5-9b9e-6598de24308a.jpg)

However, the object is still there, you just can't see it. If you remove one of the connecting path segments so that it's no longer a four-way intersection, the object reappears:
![3](https://cloud.githubusercontent.com/assets/550290/14216833/27f2c694-f84b-11e5-9388-b6db88751331.jpg)

The problem is that these hidden objects can be vandalized just like any other -- you can't see them, but your guests can! The only way to see these objects is to remove a path tile (or shop, etc.) to eliminate the four-way intersection. The broken object will then become visible so you can remove it.

However, removing path tiles, etc. to see where the vandalism is can be both expensive and time-consuming. Once you do find the offending object, it can also be very difficult to remove that object (especially in a crowded area) without clobbering a nearby scenery object, even the path tile itself, by mistake.

A much easier fix is to pay attention to where the guests are when they're complaining, then simply replace the path tiles at all four-way intersections within that vicinity. Choose the appropriate style from the path construction palette, then click on the offending tile to replace it. As long as you replace the tile with one of the same style, this won't cost you any money. Replacing a path tile automatically removes any objects on it, whether or not they're hidden by a four-way intersection.

There are exactly two ways to prevent this problem from happening at all. The first is to pay attention as you're building your paths, shops, and ride entrances/exits. If you see an object on the path at the spot where your construction would create a four-way intersection, remove the object before you create the intersection. (Again, this can be tough to see and do when you're working in a crowded area.). Alternatively, if you're using the elevated path tool to connect a new path to an existing one, build your new path right on through the intersection so that the tile at the intersection is replaced, automatically removing any object that may be on it.

The second is to use jumping fountains, if they're available in the current scenario. Unlike other objects, jumping fountains can be placed at four-way intersections and automatically replace any other object that may already be there. They also help to beautify your park and (perhaps best of all) cannot be vandalized.

**Comment by janisozaur** [comment]
Ideas put forward so far for alleviating this problem include:

* auto-removing affected scenery
* making affected scenery un-vandalizable.

**Comment by RollingStar** [comment]
@janisozaur 's second suggestion seems to fit the spirit of the game. It would be clunky and annoying to lose scenery objects forever just because you put a path next to them.

**Comment by Superjustinbros** [comment]
Yeah, I agree with the second idea more.

**Comment by Broxzier** [comment]
That was my idea of solving it too.

**Comment by IntelOrca** [comment]
What if you place the path after its already vandalised?

**Comment by Superjustinbros** [comment]
Suppose it could be auto-fixed?

**Comment by Broxzier** [comment]
Maybe removing would be better, as you basically lost its value already. Repairing it would costs just as much as placing a new one.

**Comment by Superjustinbros** [comment]
Seconded

**Comment by RollingStar** [comment]
@Broxzier, scenery costs the same no matter how many sides of the path it's placed on. Maybe as a park manager, you buy benches in packs of 4 but only put out as many as you need for the path? Then it makes sense to put a pristine bench on the same tile as vandalized ones, because that bench was just in storage.

Makes sense in-world, makes for better gameplay (constant prices, less micromanaging, player gets the bench they paid for every time).

**Comment by Gymnasiast** [comment]
I believe this was fixed in a PR somewhere last year.

**Comment by IntelOrca** [comment]
Let's close this then until it gets reported again.
