### ISSUE TITLE
Minor issue with translation.

### ISSUE THREAD

**Issue by Wirlie** [OpenRCT2/OpenRCT2#3218]
**OS:** w10
**Version:** 0.0.4
**Commit:** latest commit

Apparently, this translation is not translated from the Language file:

ScreenShot:
![scr16](https://cloud.githubusercontent.com/assets/7508197/14222733/8316afc8-f831-11e5-9551-c73665658215.png)

**Steps to reproduce:**

1. Change your language (try with differents languages, for example: Spanish):
2. Enter into the Track Designs Manager.
3. Select a ride with a track design.
4. Click on a track design.
5. A dialog box appears with two buttons (rename / delete).
6. Click on the delete button and see the "problem".

**Comment by janisozaur** [comment]
It shows a different dialog box for me: `rename`/`delete`.

![scr8](https://cloud.githubusercontent.com/assets/550290/14222820/b14bd3b6-f875-11e5-8791-d2e264d1fe53.png)

**Comment by Wirlie** [comment]
Click on the button "delete" (borrar) and see the problem. (sorry, I edited my issue, see "steps to reproduce").

**Comment by Wirlie** [comment]
okay... I found what is the problem... (STR_3357), I fixed this into the Localisation repository.
(Issue closed)
