### ISSUE TITLE
Glitched rendering

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#3222]
**OS:** Linux, 
**Commit:** f02238e

Originally reported in here: https://openrct2.org/forums/topic/1094-map-edge-bug/

Some tiles are glitched, especially near one of the map edges.

**Screenshots / Video:**
![openrct2_023](https://cloud.githubusercontent.com/assets/550290/14226347/126c0048-f8e0-11e5-872f-3f2491ca1ac5.png)

**Save game:**
[phyper46.sv6.gz.txt](https://github.com/OpenRCT2/OpenRCT2/files/200822/phyper46.sv6.gz.txt)

**Comment by IntelOrca** [comment]
Caused by the invisible tiles around the edge of the map, e.g. X = 0 not having a base and clearance height of 2.

Going into sandbox mode and increasing and then decreasing the map size fixes it.

**Comment by janisozaur** [comment]
Perhaps we could add some safeguard to prevent it? Or should I just close this one?

**Comment by Gymnasiast** [comment]
We could add a console function to fix it, if it has happened more than once.

**Comment by IntelOrca** [comment]
call ```map_remove_out_of_range_elements``` in ```game_fix_save_vars```.

**Comment by duncanspumpkin** [comment]
Probably caused by #3160 since map_remove_out_of_range_elements is currently broken.

**Comment by IntelOrca** [comment]
Calling ```map_remove_out_of_range_elements``` fixes this, so how can it be broken?

**Comment by duncanspumpkin** [comment]
Ah sorry ignore that. I thought it was being called as part of the init of a map. Eitherway `map_remove_out_of_range_elements` might fail in `game_fix_save_vars` as it may fail due to the elements not being owned.

**Comment by IntelOrca** [comment]
It supposed to remove elements that are outside the map (in the black), not the park. What's ownership got to do with anything?

**Comment by duncanspumpkin** [comment]
Ah disregard that it doesn't apply in this case.

**Comment by Broxzier** [comment]
> We could add a console function to fix it, if it has happened more than once.
Find out what is causing it would be better. The park's creator mentioned that it happened again after he played with it for a while. I've also seen this happen before where at least the first 14 map elements were made corrupt somehow.

**Comment by Liampie** [comment]
Here are my observations:

This happens when, while in sandbox mode, you use the mountain tool along the map edge. Only two edges of the map can be affected by this, namely the sides of the map that do not expand. As said before, it probably involves the row of invisible tiles outside the map. Those tiles are affected by the mountain tool, and the game doesn't render the parts that it thinks are underground. Hence why the glitches happen and they are shaped like your usual RCT mountain. 

I guess this glitch could be completely prevented if the invisible tiles outside the map (can we call them exo-tiles? Sounds awesome) are made immune to the mountain tool.

**Comment by PFCKrutonium** [comment]
_exo-tiles_... I like.

**Comment by Broxzier** [comment]
Using the mountain tool with clearance checks disabled and sandbox mode enabled reproduces this issue.

**Comment by Nubbie** [comment]
Commit 03299b9
Could not replicate
Seems to have been fixed;
https://github.com/Gymnasiast/OpenRCT2/commit/685e8a2e96f112b62923344e236ccda3976c869d
&
https://github.com/OpenRCT2/OpenRCT2/issues/3390#issuecomment-250261864
