### ISSUE TITLE
Invalid vehicle type warnings when placing any track design

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#3223]
**OS:** Windows 10
**Version:** 0.4.0
**Commit:** 5369111580ce5013dfef6401ffb91a73d92648a9

When moving the ghost of any track design around the map, the following message keeps getting logged.
```ERROR[...\src\ride\ride.c:7675 (ride_set_vehicles)]: Invalid vehicle type.```

**Steps to reproduce:**
1. Try to place any track design, like vintage cars.
2. Move the ghost of the design around the map and observe console.

**Comment by dlee13** [comment]
I noticed this bug before too, but I didn't make an issue report since I couldn't figure out how to reproduce it.
