### ISSUE TITLE
Huge batch of guests stuck in a park

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3228]
Earlier this evening I entered a server that had a bunch of guests lined up in a "V" pattern, and despite there being paths on the lower left, all the guests just kept walking back and fourth repeatedly to the point of exhaustion.

**Screenshots / Video:**
![scr1](https://cloud.githubusercontent.com/assets/4167951/14229961/679cf8b4-f913-11e5-99a6-9177172c4462.png)

**Save game:**
[Esrock April 2.zip](https://github.com/OpenRCT2/OpenRCT2/files/201118/Esrock.April.2.zip)

**Comment by fromthere** [comment]
see #2499

**Comment by duncanspumpkin** [comment]
Not a duplicate of #2499 as it can be reproduced in vanilla. Just a case of peeps being stupid.
