### ISSUE TITLE
Saving track design is blocking

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#3230]
**OS:** all
**Commit:** 842ae98

- [x] multiplayer

Saving track design is a blocking operation right now. It should rather be non-blocking, so saving a track design in multiplayer doesn't kick out all the clients (when done on server) or cause a disconnection (when done on a client).

As for UX: saving on a server could initiate a pause and send chat to clients stating "host paused the game".

**Comment by IntelOrca** [comment]
Isn't this a duplicate of #3114?

**Comment by janisozaur** [comment]
It is… and it's my report as well. Shame on me.
