### ISSUE TITLE
Guests refuse to "pay that much to go on [Ride]" in no money scenarios

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3238]
This was mostly a weird scenario that I encountered in one of the three-hour Br34k Gaming servers.

To put it simple, I was playing on a no-money scenario, and on a couple of mazes that I touched up, I noticed that no one would go on them because they "Wouldn't pay that much" despite there being no funds in the scenario whatsoever.
![screen shot 2016-04-03 at 10 36 35 pm](https://cloud.githubusercontent.com/assets/4167951/14237110/780f8880-f9ed-11e5-9f92-601f348fe5c5.png)
Notice the lack of a Money tab in the ride window.

**Comment by Gymnasiast** [comment]
This should only happen on no-money scenarios that started as a scenario with money, and got switched. When those mazes were built, was the game already in 'No money' mode?

**Comment by Superjustinbros** [comment]
From what I remember these servers always start with no money, but I believe the original scenarios featured money in their objective.

**Comment by Gymnasiast** [comment]
Yes, but did you build those mazes now, or were those there when the server was started?

**Comment by Superjustinbros** [comment]
The latter.

**Comment by Michaelfonzolo** [comment]
I've noticed this in a number of my own parks. Starting the game with money and then switching to 'No money' will cause guests to think the rides built before switching still cost money, and will react with thoughts like "I'm not paying that much to on [Ride]" regardless of there being no money. This can be replicated in any park that starts with money and has rides in it. 

This should really be marked as a bug.

**Comment by IntelOrca** [comment]
No easy way to solve this other than to go through all the ```ride->price``` and ```ride->price_secondary``` in peep.c and make sure it checks for no money flag. Some places do already check, but not all of them.

**Comment by Joshwoo69** [comment]
or when you switch.. set all the prices of the rides to be 0

**Comment by Gymnasiast** [comment]
I prefer Joshwoo69's solution actually: it avoids littering the code base with many checks for the No money flag.

**Comment by IntelOrca** [comment]
If you change all the prices to 0, then players can't change the money flag temporarily - which I expect will be a common use case.

**Comment by Joshwoo69** [comment]
yeah.. then you would have to keep the original price... like somehow...

**Comment by PFCKrutonium** [comment]
So two options then: Check for No Money Flag, or 0 all prices (and store them somehow).

It seems to me that checking for the flag would be easier to implement and less prone to bugs (outdated lists etc).

**Comment by Gymnasiast** [comment]
That will be a check for No Money flag, then, if we want to support that use case.
