### ISSUE TITLE
Ghost pieces on rides being constructed

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3239]
Due to a bug in Open RCT2, sometimes after a desync the game redirects you to an unfinished ride that someone hits the construction button on. While at most times you can simply close the windows, other times it'll leave a permanent "ghost piece" that is counted as part of the ride. No matter what, it cannot be removed, and you can even build around it.
![screen shot 2016-04-03 at 10 46 01 pm](https://cloud.githubusercontent.com/assets/4167951/14237223/d92f3db2-f9ee-11e5-9800-ef5a77325316.png)
This bug only happens in multiplayer.

**Comment by Juli199696** [comment]
I got this bug aswell in singleplayer, seems like it is a problem with zero clearance enabled.

**Comment by Broxzier** [comment]
@Juli199696 The zero clearance bug is something else though. I suspect in this case it's because the piece is actually built when someone has this ghost at that position.

**Comment by Juli199696** [comment]
Hm dont know it just happend in singleplayer too after i tried to merge tracks together and deleted them.

**Comment by duncanspumpkin** [comment]
This is not possible anymore. Feel free to reopen if its not the case.
