### ISSUE TITLE
Feature: De-bug tools + the map = changing map size

### ISSUE THREAD

**Issue by Nubbiy** [OpenRCT2/OpenRCT2#3244]
This is more of a feature for server owners and player alike, being able to change the size of the map with de-bugging tools on over on the 'Map' just like in the scenario editor.
Edit: Got it to work on my server but doesn't, as I know, always work?

- [ ] Reproducable in RCT2 (vanilla)?
- [X] Multiplayer?

**Screenshots / Video:**
![like so](https://cloud.githubusercontent.com/assets/17282384/14270748/8452f30c-faf1-11e5-8f56-3539a62ce30b.png)

**Comment by Gymnasiast** [comment]
Put your game in Sandbox mode, that will allow changing size.

**Comment by IntelOrca** [comment]
@Gymnasiast I don't think this works in multiplayer.

**Comment by Nubbiy** [comment]
@Gymnasiast - Thanks
@IntelOrca - Works in multiplayer
I figured it out and then saw this again, thanks for the support
This also works in multiplayer so I'm closing it

**Comment by Broxzier** [comment]
@Nubbiy: Are you sure it works in multiplayer, so not just on your local machine only?

**Comment by Nubbiy** [comment]
@broxzier Hosted a server with people and increased the map size to max, when people rejoined the map was bigger, so it's not just locally, especially when they built on the increased size 

Have no idea if players can do the same thing or if it's just the host who can change size

**Comment by Broxzier** [comment]
@Nubbiy: So it does NOT work in multiplayer. It's not synced the the other players. I just tested it myself, and it actually caused a crash on the server when I decreased the map size.

**Comment by IntelOrca** [comment]
@Nubbiy it only edits the map locally, so it will not synchronise to the clients from the host or to the host from the clients. New players that join will always get an up to date copy of the host's map. But that alone can't be considered "working in multiplayer".

**Comment by Nubbiy** [comment]
@Broxzier It **DOES** work in multiplayer.
IF the host increase/decrease the map size - All other clients joining will see the change (the once that are on the server will not see it before re-joining)

IF a local/joined player increase/decrease the map size - The other players WILL NOT see this change as only the player who changed it will

When it crashed for you, I think it got to a part of the map with scenariers/road/coasters as parts of it disappear which results in a crash (See video)
**Video:** https://vid.me/wwzX

I did this on a map (see screenshot) and all the other players places objects on the increased area
![test](https://cloud.githubusercontent.com/assets/17282384/14325835/6ef3931e-fc2b-11e5-9707-fb27352aed9b.png)

**Comment by Nubbiy** [comment]
@IntelOrca As the changes doesn't happen if not re-joined, then this doesn't work in multiplayer No

**Comment by Nubbie** [comment]
@Broxzier @IntelOrca 
UPDATE: on a server I was on, when de-synced, I saw new park entrences being added, are they suppose to sync but not map size?
