### ISSUE TITLE
De-bug tools for hosts + Being about to change re-searches

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#3245]
Using the de-bug tool is not available online which is understandable but still a bit of a shame that hosts can't use it, especially when they that's the only way to change re-searches etc
- [x] Multiplayer?

**Comment by Margen67** [comment]
By commenting this line out you can use the debug tools in multiplayer but it won't sync.
You will need to save then load, or have the player(s) rejoin.
https://github.com/OpenRCT2/OpenRCT2/blob/89584a38068fe77dd8cef96b9cf88bf4927398fa/src/windows/top_toolbar.c#L716

**Comment by Broxzier** [comment]
> you can use the debug tools in multiplayer but it won't sync.

Which is exactly why it's made unavailable in multiplayer. When players don't sync with you, they still have access to rides and scenery that you might not have selected anymore, causing the server to either crash, or place something else instead.

Debugiging tools will be synced eventually, enabling them now is just not safe.

**Comment by janisozaur** [comment]
For Tile inspector, I have created https://github.com/OpenRCT2/OpenRCT2/issues/5021 where I want to track its implementation.

**Comment by Margen67** [comment]
#5021 has been merged.
