### ISSUE TITLE
Problems with launching game first time

### ISSUE THREAD

**Issue by cookins** [OpenRCT2/OpenRCT2#3246]
**OS: win 7** 
**Version: 0.0.4.0 build a8efcef** 

After installing game, im launching game  and getting message:
"Unable to find RCT2 installation directory. Please select the directory where you installed RCT2!",
after selecting dir another error:
"Could not find F:\games\RCTData\g1.dat at this path" if taking another dir, then:
"Could not find F:\games\StalkerData\g1.dat at this path" - looks like it forgot to place "\" after install dir.... change of path in setup program with "\" or without not fix issue.

**Comment by Gymnasiast** [comment]
Where have you installed RCT2? (Yes, RCT2, not OpenRCT2.)

**Comment by JarnoVgr** [comment]
I've seen more reports of a missing trailing slash on first launch.

**Comment by Gymnasiast** [comment]
Oh, now I see it: `F:\games\RCTData\g1.dat` should be `F:\games\RCT\Data\g1.dat`.
Might be caused by #3009.

**Comment by janisozaur** [comment]
The trailing *back*slash is simply an issue with the format string. The file check is done properly.

The problem here is with @cookins not providing the data.

**Comment by duncanspumpkin** [comment]
@Gymnasiast probably caused by my change the other week a067113d52078eee610556f371c1025fbb25c62b.

**Comment by cookins** [comment]
what you mean where i installed? there is location where to...
the point is - that installer or game dont make another slash for install dir!

**Comment by cookins** [comment]
i download it from openrct site... from download page i downloaded setup last one and install it. and have such issue

**Comment by janisozaur** [comment]
@cookins where your Rollercoaster Tycoon 2 is installed?
