### ISSUE TITLE
Queue alignment is worse than RCT2

### ISSUE THREAD

**Issue by Wirlie** [OpenRCT2/OpenRCT2#3249]
**OS:** Win 10
**Version:** 0.0.4
**Commit:** latest build

- [ ] ~~Reproducible in RCT2 (vanilla)?~~
- [ ] Multiplayer?

Today I have seen this problem, this only happens if the queue line is not linear, straight to the point... these images show the problem:

**Screenshots / Video:**
Queue on RCT2 (all people are aligned):
![rct2](https://cloud.githubusercontent.com/assets/7508197/14305336/08befebc-fb81-11e5-8745-7acf1d1aa19e.png)

The same queue, on OpenRCT2 (people are aligned in a worst way):
![openrct2](https://cloud.githubusercontent.com/assets/7508197/14305345/1ce0b50c-fb81-11e5-9c62-024ed1833717.png)

Additionally, this problem at sometimes causes a bug (Vanilla bug): https://vid.me/ySCE ( [Save game](https://github.com/OpenRCT2/OpenRCT2/files/205779/Calamidades.en.el.canon.ISSUE.txt) )

PS: I'm not sure if I have written the title correctly ;P

**Comment by Gymnasiast** [comment]
>  I'm not sure if I write the title correctly ;P

Not completely. 'Worse' already means 'more bad', so 'more worse' is not correct English. But we understood you anyway. ^^

**Comment by Wirlie** [comment]
oh okay haha, thanks for your help ^-^

**Comment by PFCKrutonium** [comment]
Can someone clue me in to what the bug is? I'm not seeing it.

**Comment by marcovmun** [comment]
The problem is that people directly turn left or right when entering a tile where they have to turn, instead of walking first to the middle of the tile.

**Comment by duncanspumpkin** [comment]
Meh it's more natural. The code that does this is in peep update. There is possibly a rand which is slightly different but I hardly see a difference or care to change it.

**Comment by Gymnasiast** [comment]
If it's _just_ the placement, yes.

Anyway, the video @Wirlie posted is a problem that also affected vanilla RCT2: people joining queue lines, but walking past the queue, to the entrance and then turning around and going back. That was not introduced by OpenRCT2, as I have had that bug lots of times in vanilla.

**Comment by IntelOrca** [comment]
This issue is just about the alignment of guests in the queue. We should really fix this. I don't like changing the logic of something accidentally - it should be intentional with the changed part of the code clearly marked.

**Comment by duncanspumpkin** [comment]
okay i will look into it.

**Comment by duncanspumpkin** [comment]
Not sure if that will fix it. Please retest with my change.

**Comment by Wirlie** [comment]
I tested the changes and the problem still happening (Build 90dbefe)
![scr22](https://cloud.githubusercontent.com/assets/7508197/14329671/3a2d8316-fc02-11e5-82b7-b21bd9d8321a.png)

**Comment by daihakken** [comment]
AFAIK, this is a bug since the peep code was implemented into OpenRCT2

**Comment by IntelOrca** [comment]
@Wirlie could you now retest with cfecbed0038f9338f256b0168f7a520d5ad30cb0

**Comment by Wirlie** [comment]
Okay now I'm waiting the artifact of AppVeyor for test your change.

**Comment by Wirlie** [comment]
Test passed! 
![scr23](https://cloud.githubusercontent.com/assets/7508197/14396597/1fd0826e-fd9e-11e5-8ca0-1d75683719e4.png)

@duncanspumpkin @IntelOrca Thank you very much, you can close this issue :)
