### ISSUE TITLE
Feature: Adding a filter/sorting system to server listing (+Example pics)

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#3252]
Adding a filter to servers would be useful and help out when you're looking for a specific server or when you have too many servers sticking out in the list, like all the password protected servers

**Why?:** Cleans up the server listings, removes all the annoying password protected servers, more user friendly

The screenshots are just examples and not finished products 

**Filter to clear up some servers:**
![example 1](https://cloud.githubusercontent.com/assets/17282384/14316657/912bcbda-fc04-11e5-8564-e541b2f1c6ab.png)

After the filters have been added, the servers 'filtered' out are still there, but in the top in drop down lists
![example 2](https://cloud.githubusercontent.com/assets/17282384/14316656/91275e7e-fc04-11e5-9c3e-7832760f0f27.png)

**Comment by Superjustinbros** [comment]
I agree with this; what's the point of listing private servers if you can't entering them?

**Comment by Gymnasiast** [comment]
Because you enter the password on entering, and thus need to see them first?

Filtering is good, but it should keep showing all available servers.

**Comment by Nubbiy** [comment]
@Gymnasiast Isn't picture number 2 better then? To have a 'Password protected servers' drop down list? 
OR list all password protected servers in the bottom?

**Comment by Gymnasiast** [comment]
I'd say the following:
- Favourite servers on top of the list
- Then public servers
- Then private servers

With more fine-grained options in the filter options.

**Comment by Nubbie** [comment]
This was fixed in 6acbfa0 with Gymnasiast request
