### ISSUE TITLE
Feature: Being able to see stuff at a greater distance

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#3259]
When you're zooming out on a map, everything disappear, would be great on high end games to not overload the system with models etc to render but in this low-end game, there isn't much of a reason

You should be able to have a setting in the option where you can remove this function so you still can see people when you're maxed out zoomed, read texts etc

**Comment by IntelOrca** [comment]
Guests are far too small to see at the furthest zoom level. The pixels would likely just flash periodically and look horrible. This was a problem with #2857.

**Comment by Nubbie** [comment]
@IntelOrca What about all the rest like coaster details, decorations, banners etc

**Comment by Broxzier** [comment]
Zooming out is mostly meant so that you can have a overview of the park as a whole, not so spot individual objects. If you feel like objects should still be visible at this zoom level, you might want to increase the dpi scaling.
