### ISSUE TITLE
Feature: Revamped "Save" button

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3260]
I find it somewhat dumb that if you hit "Save" (mostly by accident in my case), it saves over whatever save file you had accessed/loaded last without warning, even if it wasn't a save for whatever game session that it used to contain.

Save should only auto-save if the player hadn't changed to a different park or save file (like most programs with such a feature do), otherwise it should work like Save As does on the first save after a switch.

**Comment by IntelOrca** [comment]
The game behaves exactly like any software application. If you load a file, then clicking save will overwrite the file you loaded. It only prompts you if you create a new file, and thus if you start a new scenario.

**Comment by Superjustinbros** [comment]
Well, in my case the Save function just saves over whatever file was saved/loaded under last even if the player loads a different save file.

**Comment by IntelOrca** [comment]
I don't understand, is that not what I just described?

**Comment by janisozaur** [comment]
@IntelOrca no:

Steps to repro:

1. `./openrct my_save1.sv6`
2. Select "save game", you will get a prompt, save as `my_new_save1.sv6`
3. Load a new game, `my_save2`
4. select `save game`

It will silently overwrite `my_new_save1.sv6`

**Comment by IntelOrca** [comment]
Do you have to open it by command line?

**Comment by janisozaur** [comment]
no idea, possibly not, it's just how i open saves

**Comment by IntelOrca** [comment]
I think that's an issue with command line only, because it doesn't offer you the prompt if you load a saved game from the title sequence.

**Comment by janisozaur** [comment]
I must've been mistaken and perhaps used two too similar parks and failed to recognise them. There is no problem of silently overwriting *different* saves in such way I described.

**Comment by AaronVanGeffen** [comment]
I believe this has already been addressed, now that we have both a 'Save' and a 'Save as' option.
