### ISSUE TITLE
Discussion - UDP Support for mass data to fix desyncs

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#3264]
_Quoted from **Deluxe** (No Github account)_

Track placement, guest spawn, money, terraforming are some of the things best over **TCP** as these things need to be synced up.

Things like guests positions, staff positions, ride positions are things that require a lot of updating.

Most game servers use **UDP** for this because it doesn't matter if a few steps are skipped (unlike money updates for example)

So it be great to have **UDP** support to fix the desync issue to keep important stuff synced up.

All source servers use **UDP**
For example all source games (TF2, L4D2, GMOD) use **UDP** for the things that need rapid updating and when it doesn't matter if a few packets are dropped.

It's the same reason you see players _skipping_ in high ping servers.

**Comment by Joshwoo69** [comment]
probably a okay idea. I am fine. but to think of it... it is kinda bandwith heavy :/

**Comment by PFCKrutonium** [comment]
afaik the reason TCP is used is because, at this moment, there is no unimportant data - anything missing can and likely will lead to state desyncs.

**Comment by duncanspumpkin** [comment]
Not required

**Comment by duncanspumpkin** [comment]
We don't need UDP as we don't need to send peep positions.

**Comment by IntelOrca** [comment]
Can people please stop saying we should use UDP...

**Comment by Nubbie** [comment]
The TCP seems to be clogged up with so much data it ends up with, for example, money being different for each player that it becomes ridiculous. (+2 m for a user and -7 m as the host on servers) 
Wouldn't UDP be better for some functions or what are the reasons it's so looked down on?

**Comment by Gymnasiast** [comment]
Because with UDP, packets can easily arrive in the wrong order or not at all. The only advantage is lower overhead. TCP solves the mentioned problems at protocol level.

If money gets out of sync, I doubt that's down to TCP 'clogging up'.

Point is, people keep opening issues saying we should use UDP, without searching for previous issues. Explaining the same thing over and over again gets very old.

**Comment by Nubbie** [comment]
@Gymnasiast Thanks for the information
Tried searching for other UDP related issues but couldn't find one and that's why I created this one, really bad re-search from my part so I'm sorry about that

**Comment by Gymnasiast** [comment]
@Nubbie : Don't feel bad about this please. I know you're just trying to help.
