### ISSUE TITLE
Problem with Handyman AI (mow grass)

### ISSUE THREAD

**Issue by Wirlie** [OpenRCT2/OpenRCT2#3267]
**OS:** Windows 10
**Version:** 0.0.4
**Commit:** latest build

The Handyman of OpenRCT2 have problems to mow grass (on RCT2 this not happens).

- [ ] ~~Reproducible in RCT2 (vanilla)?~~
- [ ] Multiplayer?

**Screenshots / Video:**
Handyman - RCT2:
https://vid.me/Zbe1

Handyman - OpenRCT2:
https://vid.me/1Lf6

**Save game:**
I have attached the same save game that I used to make this issue: 
[Jardines Gravitatorios.txt](https://github.com/OpenRCT2/OpenRCT2/files/211085/Jardines.Gravitatorios.txt)

**Comment by duncanspumpkin** [comment]
Looks like grass length detection is incorrect

**Comment by Wirlie** [comment]
@duncanspumpkin thanks! I tested your change and it works, but, I have found another bug with your commit, please view this:

[Gif Link](http://i.imgur.com/KhMiBou.gifv)

I tested this with oldest builds of OpenRCT2 and this not happens, this only happens since commit b023d1a.
Sorry for my bad english and thanks for your patience.

**Comment by duncanspumpkin** [comment]
@Wirlie its not related to this bug. It something different. I can reproduce it in vanilla but its made worse by OpenRCT2 so I will go and fix it.

**Comment by duncanspumpkin** [comment]
@Wirlie okay ive fixed the grass growing issues. The behaviour is now identical to vanilla but it is still possible for a handyman to cut grass on a freshly placed new ride.

**Comment by Wirlie** [comment]
@duncanspumpkin oh sorry, you're right I had not realized that this could reproduce on the vanilla game. Thank you again! :)
