### ISSUE TITLE
Add scenery to paths as building them

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#3269]
It would save a lot of time if we had an option to add scenery to paths as we were building them, such as benches, bins, lamps or even fences. I'm not sure how easy it is to implement and have made a little mock up of what I imagine the UI would look like.
![untitled-21](https://cloud.githubusercontent.com/assets/1381723/14402934/35a3aefc-fe3b-11e5-8090-14ecd33684c5.png)

I hope this better explains my idea

**Comment by Broxzier** [comment]
This has been requested before, and personally I am against this feature. Fences wouldn't work when the player wants to build paths that are wiser than one tile. Path bits is new, but I wouldn't use this myself ever, since placing a lot of the same bits after each other doesn't make much sense.

There are plans for improving the way of building paths and fences/walls, which I think would be much nicer for building such paths.

**Comment by Nubbie** [comment]
I don't know if I should approve or disapprove this, it's a interesting idea and could be useful, but how much is it really going to be used? Maybe it's a start on something bigger

**Comment by PFCKrutonium** [comment]
I don't think fences make any sense here, but perhaps those buttons could add a path ornament every X tiles? A bench every A, Garbage every B, and Lamp every C?

**Comment by daihakken** [comment]
It would come handy if it would implement like @PFCKrutonium said.

**Comment by Patrik356b** [comment]
@broxzier if there was a different button layout it would be fine. I have some ideas for a different button layout

**Comment by fromthere** [comment]
![openttd_drag](https://cloud.githubusercontent.com/assets/10338434/14550793/bb92e422-0306-11e6-9c8f-9b08728868d4.gif)
OpenTTD's drag to build signal function(for reference)

**Comment by Patrik356b** [comment]
I support the above suggestion

**Comment by Horsti12** [comment]
Yes this would be very good :D

**Comment by Gymnasiast** [comment]
This is not something we will implement directly, but something we want our plug-in system to be capable of supporting, hence the label.

**Comment by Patrik356b** [comment]
Would be nice if you could set the spacing between the different items; benches, trashcans, lamp posts

**Comment by AaronVanGeffen** [comment]
For what it's worth, I thought I remembered a PR implementing this before — indeed, #4986 aimed to tackle this, but was ultimately rejected for the same reason.

**Comment by Gymnasiast** [comment]
No, it wasn't merged because it's a welcome addition for some people and unnecessary clutter or a departure from RCT for others. That's what I said on the other PR.

**Comment by Ryder17z** [comment]
> Yes this would be very good :D

related: Benchwarmer plugin is somewhat useful for this kind of thing.
