### ISSUE TITLE
Minor issue with a function mode - Wooden Roller Coaster

### ISSUE THREAD

**Issue by Wirlie** [OpenRCT2/OpenRCT2#3274]
**OS:** Windows 10
**Version:** 0.0.4
**Commit:** latest commit

***
**Explanation:**

The Wooden Roller Coaster have an extra function mode on OpenRCT2 ("Reverse-Incline launched shuttle mode"), but on RCT2 this coaster do not have this mode.

I'm not sure if this is an improvement or if this is a bug.

***

- [ ] ~~Reproducible in RCT2 (vanilla)?~~
- [ ] Multiplayer?

***

**Screenshots / Video:**

**RCT2:**
(Sorry, I don't have the game into the English version)
Ride function modes in this screenshot:

1. Continuous circuit mode.
2. Continuous circuit block sectioned mode.

![rct2](https://cloud.githubusercontent.com/assets/7508197/14408373/1508dc80-feb8-11e5-81bd-fe6393d63233.png)

***

**OpenRCT2:**
![openrct2](https://cloud.githubusercontent.com/assets/7508197/14408400/0ecbef50-feb9-11e5-891e-9a54972d1bea.png)

**Comment by Wirlie** [comment]
Another bug related to this, but this is a original bug:

![originalbug](https://cloud.githubusercontent.com/assets/7508197/14408502/602b1bf6-febd-11e5-98a3-61afcfd51870.png)

In this screenshot, the button to add a chain lift should not be enabled.

**Comment by IntelOrca** [comment]
The mode was added by request, I think there might be another issue for the chain lift problem but not sure.

**Comment by Gymnasiast** [comment]
Both are intended behaviour.
- The mode was added by request. Based on a real-life concept by Great Coasters International
- Chain lift on steep slopes downs is correct behaviour: it's used by the Reverse-incline launch mode. See the Cobra in the Six Flags Belgium scenario, for example. (Which is a Vekoma Boomerang.)

**Comment by IntelOrca** [comment]
We enabled reverse-incline, but that doesn't mean we have to enable chain lift on steep slopes. It was intended that Wooden RCs can't support that which is why there are no sprites.

**Comment by Wirlie** [comment]
okay thanks for your information :)
