### ISSUE TITLE
Multiplayer: Manage groups problem.

### ISSUE THREAD

**Issue by Wirlie** [OpenRCT2/OpenRCT2#3276]
**OS:** Windows 10
**Version:** 0.0.4
**Commit:** latest commit

I have problems to manage groups in multiplayer, please view the video for see the problem.

- [ ] Reproducible in RCT2 (vanilla)?
- [X] Multiplayer?

**Screenshots / Video:**
https://vid.me/sBco

Apparently, this always try to edit the Admin group but not the Selected group. I'm not sure if this problem only happens for me or for all.

**Comment by IntelOrca** [comment]
You are changing the wrong dropdown. The top dropdown is the default group not the selected group for permission editing.

I get confused by this as well, and the only way I can think of fixing the UX confusion is to move the default group dropdown to a different page.

**Comment by Wirlie** [comment]
haha ops! you're right xP sorry for the inconvenience, thanks!
