### ISSUE TITLE
Launched Freefall ride ratings are fixed for Downward Launch

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#3282]
Launched Freefall intensity and nausea ratings are fixed regardless of how high the ride is when the mode is set to "Downward Launch".

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

Source: https://www.youtube.com/watch?v=vOG9qfO316o

**Comment by e-foley** [comment]
Good idea;  I think the Roto-Drop analogy is sound.  Did Whoa Bellys allow downward launches in RCT1?  If they did, we might consider comparing the two rides side-by-side to see how similar their ratings are.  Between this and #2361, it really seems like the "downward launch" mode was only half-implemented in RCT2.

**Comment by IntelOrca** [comment]
@e-foley it appears so, or was not tested properly (most likely overlooked during development). One idea I have in the future is to allow the roto-drop mode for Launched Freefall. Basically it would just slowly move to the top and then fall without any launch. This is similar to some real rides which are a hybrid between roto-drop and launched freefall (no launch and no rotation).
