### ISSUE TITLE
Interfaces behind console still usable

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#3289]
**OS:** Windows 10
**Version:** 0.0.4
**Commit:** 8e247c3

The console renders a completely black box on top of the UI, but the UI still responds to clicks.
I think it's nice to keep accepting input for the game behind it, and make the black box transparent instead.

**Steps to reproduce:**
(0. Have debugging enabled)
1. Press ` (or whichever key your language keyboard layout uses) to open the in-game console
2. Click any of the toolbar buttons

**Comment by janisozaur** [comment]
I'm not sure we can afford making it transparent right now, remember we have limited colour palette available.

**Comment by Broxzier** [comment]
Just a quick test, but transparency seems to work fine: 

![](http://i.imgur.com/xFAvNHY.png)

**Comment by janisozaur** [comment]
This is interesting, how did you do that?

**Comment by Broxzier** [comment]
I found this line: https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/interface/window.c#L1646

**Comment by Broxzier** [comment]
I kinda like the coloured ones better, here's some more:
http://www.broxzier.com/files/ShareX/2016-04-12_20-01-17.mp4

**Comment by janisozaur** [comment]
I must admit I did not realise we can do such things.

**Comment by Broxzier** [comment]
I think scenery with glass works the same way. It seems to replace the pixels behind it with a different row in the pallet, and shifts the brightness a little.

**Comment by janisozaur** [comment]
Right, that makes perfect sense. It is still all indexed, right? Or am I mistaken?

**Comment by Broxzier** [comment]
I can't tell for sure, but it looks like it, yes.

**Comment by Broxzier** [comment]
But does that solve the issue? Shouldn't mouse clicks behind the console be ignored, or is making the console transparent enough? I know other games still accept mouse input.
