### ISSUE TITLE
Close console button

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#3290]
**OS:** Windows 10
**Version:** 0.0.4
**Commit:** 8e247c3b06c811217c377fa3dad7a00f36ef5697

When a user accidentally opens the console by pressing the ` key, they do not always know how to close it. I've seen this happen in a stream, and had to tell them how to close it. A close button on the top-right corner would be nice for this.

**Steps to reproduce:**
(0. Have debugging enabled)
1. Open the console

**Comment by janisozaur** [comment]
The top-right corner placement contradicts your other issue: https://github.com/OpenRCT2/OpenRCT2/issues/3289

Toggling an in-game console with `` ` ``/`~` is a common key binding in many games. We go one step further and provide an initial prompt saying `Type 'hide' to hide the console`, or even two steps if you count support for `hide`, `quit` and `exit` commands doing exactly the same thing.

The user also has to explicitly enable debug tools, which implies he intends to do hacking/debugging, so in my opinion it is safe to expect from him he would be at least able to read said prompt.

That said I don't find that much harm in adding the close button, but don't you find it an overkill?

**Comment by IntelOrca** [comment]
It already tells you how to hide the console when you open it.

**Comment by Broxzier** [comment]
The streamer accidentally opened it by clicking on the Debug button, which he enabled to have access to the tile inspector, and at the time I didn't realize there was text about hiding it in the console already. It's true, it might be overkill. but you can never bee too clear for an user. Many people don't read at all while playing games.

**Comment by jensj12** [comment]
Having to type to close it is something that's been irritating me every time I open it (always accidentially). Most of the time I play mouse-only and it should be impossible to reach a situation where only a keyboard can help. Please do add a close button. Btw, I never knew ` toggles it, I thought it could only open the console.

**Comment by Gymnasiast** [comment]
Having Object Selection and Tile Inspector under debugging tools is something that needs looking at anyway.

**Comment by Broxzier** [comment]
Both of them don't seem like cheats to me. The Object Selection may be in the Research window.

**Comment by AaronVanGeffen** [comment]
I think they were declared cheats as objects are supposed to be preselected per scenario — the selection isn't supposed to be altered in-game.

**Comment by Gymnasiast** [comment]
They aren't under cheats. They're under debugging tools.

**Comment by janisozaur** [comment]
@Gymnasiast what do you suggest? That we move them under cheats menu?

Also: label `interface`

**Comment by Gymnasiast** [comment]
@janisozaur : That's a possibility.
Anyway, we're drifting. This one is about the console.

**Comment by Broxzier** [comment]
Closing, as you can now see and click through the console window, so also on the button that can close it.
