### ISSUE TITLE
Crash in server

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3296]
[RCT2 dump crash.zip](https://github.com/OpenRCT2/OpenRCT2/files/217899/RCT2.dump.crash.zip)

**Comment by janisozaur** [comment]
You have to provide us with your build ID as well.

**Comment by Superjustinbros** [comment]
You mean, like 6b72e5c?

**Comment by janisozaur** [comment]
yes, exactly. thanks.

**Comment by janisozaur** [comment]
[openrct2-symbols-6b72e5c.zip](https://github.com/OpenRCT2/OpenRCT2/files/217975/openrct2-symbols-6b72e5c.zip)

**Comment by IntelOrca** [comment]
Another corrupt track element / ride.
