### ISSUE TITLE
Crash upon attempting to hire a mechanic

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3300]
**OS:** Win 7
**Version:** V0.0.5-develop build
**Build ID:** 6b72e5c 
[Crash April 14th.zip](https://github.com/OpenRCT2/OpenRCT2/files/219369/Crash.April.14th.zip)

**Comment by janisozaur** [comment]
Artifacts: https://github.com/OpenRCT2/OpenRCT2/issues/3296#issuecomment-209648907

**Comment by IntelOrca** [comment]
I can't load this saved game, missing ```SCGMEDIV```

**Comment by janisozaur** [comment]
http://www.nedesigns.com/rct2-object/1992/scgmediv/

**Comment by Superjustinbros** [comment]
Yes, it was in multiplayer.

**Comment by IntelOrca** [comment]
Hiring staff is not supported in multiplayer.

**Comment by Superjustinbros** [comment]
Well, in my case it caused a crash, whereas other times and pretty much every other time beforehand  it'll bring up that "glitched guest" window.
