### ISSUE TITLE
Spiral Slide No Longer Allows Five Riders

### ISSUE THREAD

**Issue by ThornTSC** [OpenRCT2/OpenRCT2#3302]
**OS:** Windows 10 
**Version:** 0.0.5
**Commit:** 1237bca, but problem has existed for about a month and in 0.0.4

Spiral Slides no longer allow for five riders on the ride at once. Reloading saves with five riders from before this change occurred and lowering the number will prevent the player from allowing five players again.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Attempt to increase the "Max. people on ride" value on a Spiral Slide.

**Comment by duncanspumpkin** [comment]
Will be fixed in the pre-release.
