### ISSUE TITLE
Discussion: two-finger-tap to close a window

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#3304]
I got an idea: currently right-clicking on a window doesn't do anything, at least with the few windows I tried. I believe on touch-devices tapping with two fingers, would be mapped to right-clicking.

Perhaps we could use that to close the window, that way we would having to increase frame or button size.

Can someone with touch device comment on that?

**Comment by pizza2004** [comment]
I think it might depend on the device mostly.  Holding down for right click is another I've seen.

**Comment by AaronVanGeffen** [comment]
Bear in mind that this wouldn't necessarily work for windows with viewports in them, as you can (right-)click on objects within those viewports, too.

**Comment by janisozaur** [comment]
1. Doesn't have to map to right-clicking, as SDL supports touch events explicitly
2. You can right-click, but it doesn't yield any action: you cannot scroll around in them. We can possibly disable that.

**Comment by AaronVanGeffen** [comment]
> You can right-click, but it doesn't yield any action: you cannot scroll around in them. We can possibly disable that.

You can right-click on objects or track pieces in viewports to modify them -- it opens the relevant construction window.

**Comment by janisozaur** [comment]
That in turn begs the question: would you rather tap-and-hold with one finger to open the editor on precisely the piece you want or would you try dual-tapping on such piece? Since SDL supports touch events we can possibly handle both.

**Comment by Patrik356b** [comment]
Long press is more common though.

**Comment by marijnvdwerf** [comment]
Wouldn't the real solution be bigger touch targets? Neither two-finger-tapping nor long pressing make sense for closing something.
