### ISSUE TITLE
RCT2 sound is better than the sound of OpenRCT2

### ISSUE THREAD

**Issue by Wirlie** [OpenRCT2/OpenRCT2#3307]
**OS:** Windows 10
**Version:** 0.0.4
**Commit:** last commit (1237bcab264402dc69e95d03a9b1d3074798ba79, develop)

I have noticed that OpenRCT2 have difficulty to reproduce many sounds at the same area, while this doesn't happen on RCT2.

**_OpenRCT2 sound:_**
https://vid.me/FmIv

In this video, the Bumper Cars ride have problems to reproduce the music sound if many sounds already are reproduced at the same area.

**_RCT2 sound (at the same area):_**
https://vid.me/4O0G

On RCT2, this does not happens. The music of the Bumper Cars is reproduced correctly.

_Sorry for my bad english and thanks for your time._

****

**Save Game**
[Castillo Loco.txt](https://github.com/OpenRCT2/OpenRCT2/files/221305/Castillo.Loco.txt)

**Comment by fromthere** [comment]
I think you should write specific build hash like `7c62495`, not `latest build`.

**Comment by Wirlie** [comment]
Sure

**Comment by Wirlie** [comment]
Okay, I edited this to 1237bcab264402dc69e95d03a9b1d3074798ba79 (last commit of the develop branch)

**Comment by Gymnasiast** [comment]
Could it have something to do with https://github.com/OpenRCT2/OpenRCT2/issues/3229, perhaps?

**Comment by Wirlie** [comment]
mmm, this problem can be reproduced on Linux/OS X? I can't test this on these OS because I only have Windows.

**Comment by janisozaur** [comment]
> Could it have something to do with #3229, perhaps?

No, it's not related.

**Comment by debuggerEx** [comment]
Still not fixed!!! The sound is bad. :(

**Comment by fromthere** [comment]
@debuggerEx Please, open new issue with details. leaving comment to closed, old pr will not solve problem(if any)
