### ISSUE TITLE
Crash in 0.0.4

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#3316]
**OS:** windows
**Version:** 0.0.4 release
**Commit:** 1eb91cb

While watching a stream from `G Force` from NEdesigns, he downloaded a fresh release and launched it. He tried selecting a park, and then it crashed for him.

He was using RCT2 title screen and possibly had quite a few corrupt objects in his `ObjData/`

Dump is attached.

[001fd559-a02d-43a6-8395-073d0209eaed.dmp.zip](https://github.com/OpenRCT2/OpenRCT2/files/221933/001fd559-a02d-43a6-8395-073d0209eaed.dmp.zip)

[001fd559-a02d-43a6-8395-073d0209eaed.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/221941/001fd559-a02d-43a6-8395-073d0209eaed.sv6.zip)

[OpenRCT2-0.0.4.0-v0.0.4-windows-symbols.zip](https://github.com/OpenRCT2/OpenRCT2/files/221937/OpenRCT2-0.0.4.0-v0.0.4-windows-symbols.zip)

Edit: after a while he got it resolved by deleting some recently added objects.

**Comment by IntelOrca** [comment]
Access violation in ```language.cpp:object_get_localised_text``` when reading the string table of an object.

Possibly a faulty object, the save game says "Required Add-on" so I can't load it.

**Comment by janisozaur** [comment]
Most likely.

Could an object use the same ID as official (translated one) or however it selects the string and have different layout in memory?

Or perhaps not terminate some field correctly?

```
ERROR[/home/janisozaur/workspace/OpenRCT2/src/object.c:172 (object_load_chunk)]: object not installed
ERROR[/home/janisozaur/workspace/OpenRCT2/src/object_list.c:565 (object_read_and_load_entries)]: failed to load entry: R7®
```

Note weird characters at the end.

**Comment by IntelOrca** [comment]
Well it appears to be or the game thinks its a water object.

**Comment by GForceNE** [comment]
Hey guys, I've updated to the latest Dev Build and still get the same issue.
[OpenRCT2Errorbuild5.zip](https://github.com/OpenRCT2/OpenRCT2/files/222553/OpenRCT2Errorbuild5.zip)

I used to be able to get around it by backdating my game to stable 3.0 using the option to download only stable versions in the launcher.  However, now that I cannot download 3.0, the only way I can get my game to work is by deleting the objects it was attempting to add, which lets me play the game, but not open those parks.

A quick fix would be allowing the option to select the stable build in the launcher, or provide a DL link to version 3.0 on the site, otherwise its beyond me.

**Comment by GForceNE** [comment]
I've been able to bypass the issue by completely deleting all the custom objects in my object data folder.  It was probably a corrupt data causing a snag in the addition of new objects through OpenRCT as we suspected.  Not sure if this is a fixable issue, or one worth fixing for that matter, thanks for your help anyways.

Keep up the good work.

**Comment by janisozaur** [comment]
Can you pinpoint the faulty object and provide it to us?

**Comment by GForceNE** [comment]
I would, however, I have over 7000 custom objects in my data folder, so it could be any number of those, and testing each to find the corrupt one (or multiple) would take far more time than I have available.

**Comment by IntelOrca** [comment]
@GForceNE Send us all your water objects.

**Comment by janisozaur** [comment]
In addition, running `openrct2.exe --verbose` should provide more information on what's going on, it should help figure out the object we're after.

**Comment by GForceNE** [comment]
I've been able to narrow it down to two pallets by the name of "Blue Water" and "Nighttime rct2 (brighter yellow)".  As those are the two pallets I have on my normal RCT2 and not my OpenRCT2, so I'm 99% sure its one of those causing the issue.  Currently don't have the time to check each to find the .dat, or to replace my old object data folder to look at the verbose.  I feel like this is still a very isolated issue though, and it might not be 100% worth looking into.

Also, there is a slim possibility that the corrupt element wasn't installed in my regular RCT2 object data folder, and just Open, so it could be one outside of the two I mentioned.  However, again, I can't check unless I reinstall my old objdata folder, which I dont have time to do atm.  Maybe in a week or two I can.
