### ISSUE TITLE
Can't rotate pre-built rides

### ISSUE THREAD

**Issue by jensj12** [OpenRCT2/OpenRCT2#3321]
**OS:** Windows
**Version:** 0.0.5-develop
**Commit:** e5666f2

Pre-built rides can't be rotated. Mirror does work.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open build window and select a type with at least one available design
2. Select a pre-built ride to build (don't place it yet)
3. Click the rotate button
4. Nothing happens

**Comment by Broxzier** [comment]
In 681961eaeccab579bf62c8b7068b900b6634762f it's still working.
In 7b248f0079ae4b8dcd8405482dba3c77a9abb495 it's broken
