### ISSUE TITLE
Crash when saving park

### ISSUE THREAD

**Issue by X123M3-256** [OpenRCT2/OpenRCT2#3323]
**OS:** Windows 8
**Version:** 0.05-develop
**Commit:** e5666f2

Whenever I try to save this park, I get a crash. I have been playing around with it and might have corrupted something, but I thought I'd reverted all of that and I did not have this problem on my desktop, which is not running the latest build - so I suspect this is an issue introduced in the past week or so.

**Steps to reproduce:**
1. Open [this park](https://mega.nz/#!65xEyYbJ!eg-0-BRK0az7GGkMY_6pLBSmAPM16f73flkLvs598g4)
2. Go to File->Save (not Save As)

**Dump file**
[OpenRCT2.zip](https://github.com/OpenRCT2/OpenRCT2/files/222414/OpenRCT2.zip)

**Save game:**
[RedditAprilContest.zip](https://github.com/OpenRCT2/OpenRCT2/files/222416/RedditAprilContest.zip)

**Comment by janisozaur** [comment]
Symbols: 
[openrct2-symbols-e5666f2.zip](https://github.com/OpenRCT2/OpenRCT2/files/222421/openrct2-symbols-e5666f2.zip)

**Comment by Broxzier** [comment]
Crashes here: https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/interface/viewport.c#L1866
Called from `map_element_paint_setup`.

**Comment by Remaico** [comment]
I got the same problem. Does someone know how to fix?

**Comment by IntelOrca** [comment]
Guys, like 95% of these crashes in multiplayer are due to invalid track elements for a ride. It crashes when trying to draw them - the game in this state is useless. There is nothing we can do and we just can't work out how invalid track pieces are getting places in multiplayer.

**Comment by Remaico** [comment]
It's not that bad. I still can save my park. Hopefully there will be in the future something to fix this. 
![naamloos](https://cloud.githubusercontent.com/assets/18737614/14970866/07c90fbe-10cd-11e6-84b4-1b13c258971d.png)

**Comment by IntelOrca** [comment]
@Remaico if you could find a reliable way of causing multiplayer to crash, that would help as immensely.

**Comment by X123M3-256** [comment]
I don't think it's due to invalid track elements as it doesn't crash when loading the park but when saving - and the "Save As" button works fine. I'm also not using multiplayer, so that's probably a different issue.

**Comment by IntelOrca** [comment]
@X123M3-256 yeah, I was referring more to the other issues

**Comment by Remaico** [comment]
I got the same problem as you X123M3-256. 'Save as' in single player. Sometimes when I save my park things look a little bit weird. Like in the picture I posted yesterday.

**Comment by Broxzier** [comment]
I'm not sure if this is the exact same issue, but I experienced that saving itself was working fine, but the moment you unpause the game it crashes.

**Comment by PFCKrutonium** [comment]
@IntelOrca Would it be possible to make a build that records absolutely everything that happens? I could play an MP Game with my brother and see if I can cause it to crash... Or just host a public server.

**Comment by IntelOrca** [comment]
To some degree, @janisozaur has ideas for game recording.

**Comment by janisozaur** [comment]
Indeed, although this may take some time to materialise (I'm mostly busy with porting to x86-64 now) and I have yet to investigate feasibility of approach I'd like to take.
