### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by cwook** [OpenRCT2/OpenRCT2#3327]
**OS:** 
**Version:** 
**Commit:** 

Explanation of the issue...
Crashed on a multiplayer server. I was working with scenery.

- [no] Reproducible in RCT2 (vanilla)?
- [yes] Multiplayer?

**Steps to reproduce:**
N/A

**Dump file**
If you have a dump file, zip it and drag&drop it here.

**Screenshots / Video:**
Drag / drop screenshots here. Use https://vid.me to upload video.

**Save game:**
Change the file extension to .txt or package to a .zip so that it can be drag / dropped here...

**Comment by janisozaur** [comment]
@cwook you gave us basically no info. Can you provide anything?

**Comment by Superjustinbros** [comment]
In your Documents>Open RCT2 folder, there should've been two files generated around the same time; compile them into a .zip and upload them here, along with providing the build ID shown on Open RCT2's title screen.

**Comment by Stevoisiak** [comment]
Without further information, I think this should be safe to close
