### ISSUE TITLE
Adding kb/bytes to 'Downloading map ...' 

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#3328]
When you join a game in multiplayer, you of course need to download the map which is indicated by STR_5759, but it doesn't tell the player 'how much' it downloads
It could be bytes, kb, mb, TB, or meatballs

Just simply adding kb/byte (Obviously the correct value) would help people understand what the numbers mean

`STR_5759    :Downloading map ... ({INT32} / {INT32})` **`KB`**

**Comment by PFCKrutonium** [comment]
Downloading 377/780 Meatballs...
