### ISSUE TITLE
Adding support for OpenRCT2 - Tab on the website + Gitter chat (Community driven)

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#3329]
_For the people not scared off by that awful title that I tried to cram too much information to, just to make people interested..._

A lot of people in the community needs help about stuff, most commonly servers it seems. I see people asking in the wrong chats on Gitter or ask around on servers how to do X and Y, 
Why not make a new gitter chat so people can ask questions live driven by the community?

That means we have a tab on the OpenRCT2 website called 'Support' as they are connected to a Gitter's support chat _(which sadly requires a Github account which might not be ideal)_ so the community can help out by referring to the OpenRCT2 wiki or tell them step-by-step how to do X and Y.
Live.

Something that at least could be done is to link people to the wiki from the website

**Comment by JarnoVgr** [comment]
Could also create a 'Support' tab on the website that links to the help section on the forums.

**Comment by Nubbie** [comment]
@JarnoVgr Thought about that yesterday
A Support tab that shows the forum, the gitter chat and Github for reporting bugs

**Comment by Nubbie** [comment]
Here are some **examples:**

![support](https://cloud.githubusercontent.com/assets/17282384/15143115/5e0bc1b0-16a8-11e6-84e9-0a32c7fabd03.png)
**Front Page**


![geaswgaef](https://cloud.githubusercontent.com/assets/17282384/15143120/5facb01a-16a8-11e6-991d-ceb3fb27c572.png)
**On the support page**

**Comment by IntelOrca** [comment]
Isn't the problem usually that people ask questions that have already been asked before? Maybe there should be an FAQ.

**Comment by Gymnasiast** [comment]
Or link to the FAQ on our wiki.

**Comment by Nubbie** [comment]
I wouldn't say no to have a mail account off some sort or another solution that people can log into to help out

**Comment by JarnoVgr** [comment]
@Gymnasiast I personally see the github wiki mostly as a development-info wiki. Not sure how others think about it.

Anyways, I'm on this!
