### ISSUE TITLE
Speeding up numericupdown 

### ISSUE THREAD

**Issue by ToastHelmi** [OpenRCT2/OpenRCT2#3332]
it would be nice if the numericupdown was speeding up while being pressed

**Comment by Nubbie** [comment]
![leli](https://cloud.githubusercontent.com/assets/17282384/14590565/21ce5098-04fe-11e6-9421-dacac49d10d1.png)
I guess you mean like this?
You can change the shortcut key for speeding and decreasing the game speed in 'Shortcut keys...'

**Comment by janisozaur** [comment]
@Nubbie I think he means the delta, by which a spinner increases each time, should also increase over time you hold it clicked.

**Comment by IntelOrca** [comment]
Other alternatives to this are:
* CTRL or SHIFT clicking to increment / decrement in larger amounts.
* Clicking the number which pops up an text input box. (We already do this in a few places like land tool size)

**Comment by Nubbie** [comment]
@IntelOrca was JUST going to say about the text input box, would be a wonderful idea for times and speeds etc just like the terraform tool has for the size of the brush!
Just like with a generic: 'Insert the value here' textbox or something

**Comment by e-foley** [comment]
Another fairly common approach is clicking/holding on the number itself and moving the mouse up or down to cycle through numbers quickly.  (I think RCT 3 may have done this, but my memory's foggy.)

**Comment by Gymnasiast** [comment]
I think I prefer @IntelOrca 's method, especially in cases where you would have to hold down the button for a long time - setting up the money in a scenario springs to mind.

**Comment by janisozaur** [comment]
Scrolling (with mouse wheel) on spinner widgets should also execute the up/down action.

**Comment by IntelOrca** [comment]
CTRL click or SHIFT click or mouse wheel will be implemented when we re-write the UI engine.
