### ISSUE TITLE
Invalid highscores.dat files can cause crashes/hanging with no warnings

### ISSUE THREAD

**Issue by LRFLEW** [OpenRCT2/OpenRCT2#3333]
**OS:** All (Tested Windows and OS X)
**Version:** 0.0.4 Stable & 0.0.5 Develop
**Commit:** Tested on 24eaa0a

The highscores.dat file has a number indicating the number of entries and then the entries listed. If the number of entries indicated is greater than the number of entries in the file, then the program doesn't handle the issue gracefully. A user on Gitter reported that this issue caused the game to hang indefinitely on loading with Windows. My testing on OS X showed both crashes with EXC_BAD_ACCESS and indefinite hanging with increasing memory usage (depending on how I used breakpoints). The program really shouldn't have these sorts of catastrophic errors, even if the file corruption was user-error.
- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Replace (or add) the highscores.dat file in the OpenRCT2 Documents folder with the one linked below, or modify the file there (with a hex editor) to indicate 1 (or more) entries than are actually in the file.
2. Run the game and see that it doesn't launch.

**Example File**
[highscores.dat.zip](https://github.com/OpenRCT2/OpenRCT2/files/223095/highscores.dat.zip)

**Comment by LRFLEW** [comment]
I'm not sure that @janisozaur's PR fixed the entire issue, as incomplete names (aka, files that don't end with a null terminator) can still cause hanging (and even worse, constant memory allocation). When I have time, I'll PR a more robust solution.

**Comment by IntelOrca** [comment]
@LRFLEW can you check if any of this is still an issue?

**Comment by LRFLEW** [comment]
I haven't done complete testing on this, but this appears to have been resolved. Now that the high scores are parsed using the FileStream, which performs bounds checks, this should be fine. I'll close this now.
