### ISSUE TITLE
Anytimes crashes on multiplayer

### ISSUE THREAD

**Issue by MaksGITHUB1** [OpenRCT2/OpenRCT2#3338]
OS: Windows 10 (64-bit)
Version: 0.0.4-develop 1711

Also: that's been on march or february!

Info:
if i want play on multiplayer i go here and i searching for some best servers i joining when i joined my openrct2 crashed (you don't need help me, becuase it fixed) on newest versions

**Comment by duncanspumpkin** [comment]
0.0.4 develop is no longer supported. If this still occurs in stable or 0.0.5i can reopen. You also have not mentioned much information about what's wrong
