### ISSUE TITLE
Windows generated at bottom cropped off by bottom HUD

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3347]
![scr5](https://cloud.githubusercontent.com/assets/4167951/14647059/fbf14f7e-0629-11e6-8e95-96ad1d87df89.png)
Take note of the window for the "Wicked Woodie" ride and how it's generated just low enough that it's blocked off by the bottom HUD.

From what I remember, it's an oversight introduced in Open RCT2 as I never have seen anything similar happen in Vanilla. I'm also not sure if this error can occur based on the window size.

**Comment by Gymnasiast** [comment]
Issue is caused by ride windows having an incorrect height definition. It doesn't seem to happen with other window types.

**Comment by Broxzier** [comment]
I am unable to reproduce this. I tried by opening a lot of ride windows by clicking on them, and from the ride list. Can you provide the exact steps to to take to reproduce this?

The top and bottom toolbars are not blocking any windows:
![](http://i.imgur.com/wt0nQla.jpg)

**Comment by Gymnasiast** [comment]
@Broxzier Your window is slightly shorter as you don't have the traffic lights turned on. Justin and I both have, making the window a bit taller, causing the mentioned issue.
