### ISSUE TITLE
Assertion triggered while fixing surface tiles

### ISSUE THREAD

**Issue by Richard-L** [OpenRCT2/OpenRCT2#3352]
**OS:Win10 x64
**Version:004 stable

Upon opening this park: http://www.nedesigns.com/park/3336/nowton-thrill-park/

![image](https://cloud.githubusercontent.com/assets/4934209/14655999/62fd6fb2-0685-11e6-9ba9-574b04023abe.png)

Sorry if this has been reported before.

**Comment by IntelOrca** [comment]
It seems to be falling over on our routine that fixes corrupt tiles.
