### ISSUE TITLE
"Download and open park" command line option does not work

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#3355]
**OS:** Linux
**Version:** 0.0.5

```
$ ./openrct2 --help
(… snip …)
examples:
    openrct2 https://openrct2.website/files/SnowyPark.sv6    download and open a saved park
```

However, when trying to run such command (with proper URL) no park gets downloaded.

**Comment by IntelOrca** [comment]
I haven't implemented it yet, sorry for the misleading ```<uri>``` and example.

**Comment by janisozaur** [comment]
we already have `curl` integrated, should be easy enough.
