### ISSUE TITLE
Ride music bug.

### ISSUE THREAD

**Issue by Wirlie** [OpenRCT2/OpenRCT2#3367]
**OS:** Windows 10 (32 bits)
**Version:** 0.0.5
**Commit:** 407359e82b461381001cb63f208ec9e83f9ba8f6

I have problem with the ride music (please watch and listen the video). Apparently, this happens since the commit 7eb3a90 was merged into develop.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Screenshots / Video:**
https://vid.me/iiNg

**Comment by Broxzier** [comment]
Can you make a PR for this?

**Comment by Wirlie** [comment]
sure, I already made a PR for this.
