### ISSUE TITLE
Polish characters are wrongly mapped

### ISSUE THREAD

**Issue by marijnvdwerf** [OpenRCT2/OpenRCT2#3368]
If you paste the top row in the game, the characters below get drawn.

```
 ¢ Æ ÐØ×
ĄĆĘŃŁŚŻŹ

ÝÞæð÷øýþ
ąćęńłśżź
```

![image](https://cloud.githubusercontent.com/assets/737603/14712622/3160d566-07de-11e6-9e93-fcf343145037.png)

**Comment by Gymnasiast** [comment]
Possibly related to the following:
When you import Blackpool Pleasure Beach, the banner reading
`The Glôbe Theatre`
in RCT1 suddenly has
`The GlôĆĆ¥ Theatre`
as its name. Also, the cursor behaves very strangely - try moving it, it will sometimes underline multiple letters at once.

**Comment by Gymnasiast** [comment]
This is not fixed. It will still render stuff like ø wrong.

**Comment by IntelOrca** [comment]
@Gymnasiast does this require adding extra sprite font character images?

**Comment by Gymnasiast** [comment]
Yes.

**Comment by Gymnasiast** [comment]
I'm going to consider this fixed now. Polish characters are correctly mapped, Danish/Norwegian/Czech characters have been added. What remains are Icelandic letters (will be added once someone creates an Icelandic translation) and some other dust that would otherwise show up as `?` anyway.

**Comment by Gymnasiast** [comment]
Interestingly, these characters do show up correctly in RCT1:

![afbeelding](https://user-images.githubusercontent.com/1478678/183222810-44414fba-9438-4f1f-8002-47e9fd83e022.png)
