### ISSUE TITLE
Crashes on Startup

### ISSUE THREAD

**Issue by jkhero73** [OpenRCT2/OpenRCT2#3377]
**OS:Windows 10 (Laptop)** 
**Version:*0.0.5.0-develop-67a86fe* 
**Commit:67a86fe** 

Explanation of the issue...
So I opened it, and the game crashed.
Tried multiple times.
I used the windows installer.

Reproducible in RCT2 (vanilla)? - [No]
Multiplayer - [No]

To reproduce:**
1. Open
2. Crash

**Dump file**
[DMP File.zip](https://github.com/OpenRCT2/OpenRCT2/files/230936/DMP.File.zip)

**Screenshots / Video:**
Drag / drop screenshots here. Use https://vid.me to upload video.

**Save game:**
N/A, game crashes immediately.

**Comment by jkhero73** [comment]
Turns out I just had to use the launcher! I feel quite stupid now. =P

**Comment by jkhero73** [comment]
Of course, after closing it once, the launcher refuses to work.

**Comment by Gymnasiast** [comment]
The launcher is not part of our project, but made by the community. Problems can be discussed here: https://gitter.im/PFCKrutonium/OpenRCT2Launcher
