### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#3380]
We are supposed to follow some style guide eventually, but there are no rules just yet.

I'm not here to discuss the rules, but rather technical means of enforcing them.

I'd like to put forward an idea of integrating a code formatter into our process. There are quite a few possible options:
- `astyle` – http://astyle.sourceforge.net/
- `uncrustify` – http://uncrustify.sourceforge.net/
- `clang-format` – http://clang.llvm.org/docs/ClangFormat.html

These are just the most-well-known ones, I'm sure there are plenty more.

Out of these options I would strongly recommend to go with `clang-format`, for the most basic reason: it is compatible with patches. It can check and re-format just the change you're about to introduce, which allows for natural and gradual deployment of code style, minimising disruptiveness of the change.

**Comment by IntelOrca** [comment]
I don't think automatic formatting will work, there are just going to be so many exceptions and I really don't want to bloat the code with lots of ignore metadata. Although if the formatting is no so strict it might work. For example making sure there are no tabs would be fine.

**Comment by marijnvdwerf** [comment]
If there need to be lots of exceptions to a rule, said rule might not be a good one ;)

**Comment by Stevoisiak** [comment]
I'd be willing to go through and work on a mass replacement of tabs with spaces

**Comment by janisozaur** [comment]
That's a one-liner.
```bash
git ls-files -z src | xargs -0 -I {} bash -c "expand -t 4 {} | sponge {}"
```

**Comment by Stevoisiak** [comment]
Right, but I'd also need to check to make sure it doesn't break any vertical allignment

**Comment by janisozaur** [comment]
Why would it?

**Comment by Stevoisiak** [comment]
Nevermind. I was thinking of something else

**Comment by Broxzier** [comment]
I would like an automatic formatter, one with not too many rules so that it only breaks the flow, for example of how widgets are defined, one that just makes sure there are not too many lines, identification is right, braces after conditional statements, else on new lines. I like the suggestion @janisozaur make about clang only formatting the code that has changed.

**Comment by janisozaur** [comment]
I've been playing with clang-format lately, I think it would be a good addition **for new C++ code only***, as our C code is mixing styles in all the places and is manually aligned.

It would also align with @IntelOrca's intentions to enforce such rules only for incoming `cpp`/`hpp` files.

\*and the code currently in `core/`

**Comment by janisozaur** [comment]
http://llvm.org/pre-releases/win-snapshots/ClangFormat-r265934.vsix is the clang-format plugin for VS.

The file I came up with, for clang 3.7, which may be a bit older than this plugin, looks like:
```
---
BasedOnStyle: LLVM
AlignTrailingComments: 'true'
AllowShortFunctionsOnASingleLine: None
AllowShortIfStatementsOnASingleLine: 'true'
BreakBeforeBraces: Allman
ColumnLimit: '120'
IndentWidth: '4'
NamespaceIndentation: All
PointerAlignment: Middle

...
```

There is at least one new option in newer version, which we would like to use, `Align`-something.

To try it out yourself, paste the snippet above into `.clang-format` file in topdir, then execute: `git ls-files src | egrep \\.\(cpp\|hpp\)$ | xargs clang-format -style=file -i` or use the VS plugin I linked above, you may find http://stackoverflow.com/a/18801102 useful as well.

**Comment by Broxzier** [comment]
I've been playing with clang-format since you made this issue too (running it with visual studio every time the solution is built) and I'm very happy with the result. I keep finding little things that it changes though, so we better make sure the .clang-format file is completely as we like it before making use of it.

**Comment by janisozaur** [comment]
There's very helpful online configurator for clang available here: http://zed0.co.uk/clang-format-configurator/

**Comment by Broxzier** [comment]
Today formatting was brought up in the gitter chat, and I still think it would be nice to have. It can be set up in such a way that only _some_ changes will be made (think about spaced after `if`, new lines before `else`, opening brackets on new lines for functions).

**Comment by AaronVanGeffen** [comment]
We've since settled on clang-format. Closing this.
