### ISSUE TITLE
Explain what 'Advertise' means when creating a server

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#3382]
It's not the biggest issue in the whole world but still would like to hear comments about this before making a pull request adding a small description box for the button

It's more for new users that tries to create a server that might get confused what it means as 'Advertise' isn't (as I've experienced) the most commonly used word when describing that it will be shown in the multiplayer server list

 
**Solution:**
By explaining this option for the user by adding a description box that reads out:
                 "Show this server in the 'Server list' so anyone can find it"

_(If you have a better description, please tell me in the comments)_

 
The button in question is:
![image](https://cloud.githubusercontent.com/assets/17282384/14734448/cdaa8746-086a-11e6-93a3-cd9098989ce9.png)

**Comment by IntelOrca** [comment]
Easy fix is to just add a tooltip.

**Comment by Nubbie** [comment]
The only thing that stops me from making a pull request with this is:

- Knowing what I should write
- Knowing if it's really that useful / junk-code

**Comment by Patrik356b** [comment]
This function is usually called "Announce" so that would be a better word

**Comment by Nubbie** [comment]
@Patrik356b Think the word is a bit weird too, but it's been discussed in the merged [#3403](https://github.com/OpenRCT2/OpenRCT2/pull/3403) PR, keeping the word seems to be what we stick with, the description should now be enough :)

Men också, Tjenare ^^
