### ISSUE TITLE
Korean font's are conflict themselves

### ISSUE THREAD

**Issue by Darkttd** [OpenRCT2/OpenRCT2#3389]
Korean font's are conflict themselves at track information window.
Of course, we can read it. but it seems awkward.
I think It needs to reduce font size or spread line space.

vanilla:
![vanilla](https://cloud.githubusercontent.com/assets/6015765/14743804/634c73b8-08de-11e6-87ba-fbbf88446e56.png)

OpenRCT2:
![scr3](https://cloud.githubusercontent.com/assets/6015765/14743797/5be9e3d0-08de-11e6-98cd-b3634e9c6aeb.png)

**Comment by IntelOrca** [comment]
Will be fixed when we re-write the window system.

**Comment by daihakken** [comment]
I reported the similar scenario to Intel when he was implementing UTF8 into openrct2. Should I update this as an known issue in wiki Localisation page or not?

**Comment by IntelOrca** [comment]
If you like

**Comment by AaronVanGeffen** [comment]
Is this still an issue? I've changed many windows over the past few months to prevent text from overlapping in CJK languages.

**Comment by Darkttd** [comment]
@AaronVanGeffen In version 0.1.2-develop-9c84ae3, this issue resolved. thanks :)
