### ISSUE TITLE
mountain tool at map edge caused corrupted vertical map edge (vertical black hole)

### ISSUE THREAD

**Issue by FischNE** [OpenRCT2/OpenRCT2#3390]
**OS:** Windows 10
**Version:** ORCT2 0.4
**Commit:** 

Explanation of the issue...
During multiplayer one of the players on the server played around with the mountain tool near the map edge. Doing this the mountain tool apparently wanted to include non existing tiles OUTSIDE the actual map edge. Now there's a corrupted vertical wall on the map edge in the shape of a raised mountain tile with a slope to either wall. That corrupted map edge will repeatedly flicker with new images.

- [ ] Multiplayer? Happened in multiplayer while clearances were turned to 0.

**Steps to reproduce:**
1. I guess play around with the mountain tool at the map edge so wildly while disabling clearances that it messes up the edge. 

**Save game:**
For some reason my zip is unable to upload here. Maybe because it's many mb big. May I upload the file on a seperate hoster?

Would be incredible if someone could fix this for me.

**Comment by Nubbie** [comment]
I tried this out for myself in singleplayer

Is this what you mean?
![example picture](https://cloud.githubusercontent.com/assets/17282384/14748871/73bba02e-08bc-11e6-8255-256a43e97695.png)

**Steps to reproduce:**
1. Load a map and get the mountain tool
2. Turn off clearance check and enable sandbox mode
3. Change the height on the two walls that can't get expanded (when increasing the map size)
4. Watch the results 
 
 
**Extra info:**
- Could not replicate this on the two sides which you can expand, not even when you've expanded them fully (254x254 tiles)

**Comment by Broxzier** [comment]
To 'fix' parks affected by this, increase and then decrease the map size. Decreasing it will reset the map edges.

**Comment by FischNE** [comment]
That crashes the game for me.

**Comment by Nubbie** [comment]
@FischNE I think he ment that you increase the map 1 time and then decrease it 1 time, tried it and it works
If you decrease the map too much so it collides and removes something like a path, part of a coaster or scenery, it crashes

**Comment by jensj12** [comment]
Someone on the forums found another fix for those having trouble with this: https://openrct2.org/forums/topic/1219-terrain-map-edge-glitch-possible-fix/

**Comment by janisozaur** [comment]
Seems related: https://github.com/OpenRCT2/OpenRCT2/issues/3222

**Comment by duncanspumpkin** [comment]
No longer happens.
