### ISSUE TITLE
Fatal crash when title music is not found

### ISSUE THREAD

**Issue by dvolaart** [OpenRCT2/OpenRCT2#3393]
![openrct2_cmd](https://cloud.githubusercontent.com/assets/13031404/14754780/d552d890-08dd-11e6-8fdd-b107af59276c.png)
![crash](https://cloud.githubusercontent.com/assets/13031404/14754098/840ceeb6-08d9-11e6-913f-862515d841d2.png)
**OS: Windows 7 home premium
**Version: 0.0.5.0 
**Commit: f60f53d

Explanation of the issue...

- [Yes ] Reproducible in RCT2 (vanilla)?
- [No ] Multiplayer?

**Steps to reproduce:**
1. Start open RTC
[17cc622a-e0f0-43a9-9c42-69eabc643894.zip](https://github.com/OpenRCT2/OpenRCT2/files/232502/17cc622a-e0f0-43a9-9c42-69eabc643894.zip)

2. 

**Dump file**
If you have a dump file, zip it and drag&drop it here.

**Screenshots / Video:**
Drag / drop screenshots here. Use https://vid.me to upload video.

**Save game:**
Change the file extension to .txt or package to a .zip so that it can be drag / dropped here...

**Comment by janisozaur** [comment]
No use for `sv6`. Symbols: 
[openrct2-symbols-f60f53d.zip](https://github.com/OpenRCT2/OpenRCT2/files/232542/openrct2-symbols-f60f53d.zip)

**Comment by IntelOrca** [comment]
@dvolaart can you update to e9f755c9476b8dcb74245a69c350e3639848e4cb, #3385 might have fixed the issue.

**Comment by janisozaur** [comment]
He did, he updated with a screeshot above.

**Comment by IntelOrca** [comment]
Access violation in ```audio_start_title_music``` at
```c
gTitleMusicChannel = Mixer_Play_Music(pathId, MIXER_LOOP_INFINITE, true);
Mixer_Channel_SetGroup(gTitleMusicChannel, MIXER_GROUP_TITLE_MUSIC);
```

**Comment by IntelOrca** [comment]
@dvolaart What is your title music selection set to?

**Comment by dvolaart** [comment]
@IntelOrca how can i set it? because the game doesn't allow me to set anything. Must this be set in a config file?

**Comment by IntelOrca** [comment]
I am not asking you to set it, I am just asking what the value of it is.

**Comment by dvolaart** [comment]
i am sorry, where can i find this value?

**Comment by IntelOrca** [comment]
```Documents\OpenRCT2\config.ini```
Under ```[sound]```
Something like ```title_music = 1```

**Comment by dvolaart** [comment]
Ok, i am looking for a config file, i can't find one in the OpenRCT2 folder. i there another place?

**Comment by IntelOrca** [comment]
It should be located at the path I wrote above.

**Comment by dvolaart** [comment]
i found it:

[sound]
master_volume = 100
title_music = 2
sound = true
sound_volume = 100
ride_music = true
ride_music_volume = 100
audio_focus = false
audio_device = ""

**Comment by IntelOrca** [comment]
Change ```title_music``` to 0

**Comment by dvolaart** [comment]
It's working! many thanks..

**Comment by IntelOrca** [comment]
Good, the problem is that it can't find the title music file. Now we certainly need to prevent it from crashing when this happens, but can I ask what installation of RCT2 you are using?

**Comment by dvolaart** [comment]
I've installed this "version" on 2 laptops. One (Win8) it is just working and on the other (Win 7) i got this error. So i don't think it's the installation of RCT2.
