### ISSUE TITLE
Crash in multiplayer game

### ISSUE THREAD

**Issue by MysterX83** [OpenRCT2/OpenRCT2#3395]
**OS:** Windows 7 
**Version:** 0.0.5.0
**Commit:** b2566a7 

Explanation of the issue.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

Dump file:
[45f18449-4d22-469f-a922-e72dab9b4700.zip](https://github.com/OpenRCT2/OpenRCT2/files/232627/45f18449-4d22-469f-a922-e72dab9b4700.zip)

It happend when i bought a staff employee and whant to place him on the field.

Dump file 2:
[c8d1121a-a6cc-4ce9-845c-1cffb4d136c2.zip](https://github.com/OpenRCT2/OpenRCT2/files/232680/c8d1121a-a6cc-4ce9-845c-1cffb4d136c2.zip)

**Comment by IntelOrca** [comment]
@dvolaart can you please format your issues correctly, if you aren't going to put anything under those headings, just remove them. The jump link should go under the dump file heading at least.

**Comment by Superjustinbros** [comment]
Currently, attempting to hire any staff in Multiplayer will half the time result in an immediate crash. It's mostly a gamble for me whenever it works or not.

**Comment by fromthere** [comment]
`- [ ]` is **NOT** for Yes/No. It's checklist so you can check after creating issue or marking with `x` like `- [x]`

**Comment by IntelOrca** [comment]
Placing staff issues is a known cause of crashes, will be fixed when implemented.
