### ISSUE TITLE
Load/Save feature breaks during scenario construction

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3407]
I decided to make a workbench scenario only for all the save options to fail.
I tried using the system dialogue window and it refused to pull up.
Rebooting the game doesn't help; but oddly I can save the scenario as a saved game with no problems (at the cost of nothing saving the rides/attractions selected), only when I try to save it as a landscape or scenario does is refuse to cooperate.

[Sandbox 2016.zip](https://github.com/OpenRCT2/OpenRCT2/files/233016/Sandbox.2016.zip)

**Comment by Stevoisiak** [comment]
I was able to reproduce this on my end. Running 0.0.5 commit c40a4c3 on Windows 10. I've attached my crash dump and a video of the issue.

[187dae3e-85e9-487c-9455-66b92fadbe31.zip](https://github.com/OpenRCT2/OpenRCT2/files/233679/187dae3e-85e9-487c-9455-66b92fadbe31.zip)
[OpenRCT2 Issue #3407.zip](https://github.com/OpenRCT2/OpenRCT2/files/233681/OpenRCT2.Issue.3407.zip)

**Comment by Superjustinbros** [comment]
![scenariowontsavewindow](https://cloud.githubusercontent.com/assets/4167951/14859045/6e6cb902-0c70-11e6-9cec-739a92993151.png)
Using the above save that I made, I tried to save it as a scenario again in build bde0989, and the same problems still occur.

**Comment by Gymnasiast** [comment]
That save is probably corrupt due to that bug. It shouldn't happen on newly created ones.

**Comment by Superjustinbros** [comment]
Ah, I see.
Dunno how it'd be corrupted, though.

**Comment by Superjustinbros** [comment]
So I think I found a way to reproduce the error on my end; I tried making a brand new scenario in the scenario editor and did what I did last time: Leave the "minimum" attractions that get auto-checked when starting a new Scenario and check every single Time Twister and Wacky Worlds ride/attraction, excluding the variations of the Elevator, Bumper Cars, and Boat Hire, and attempt to save it.

**Comment by Nubbie** [comment]
[Dumpfile from Stevoisiak](https://github.com/OpenRCT2/OpenRCT2/issues/3407#issuecomment-214046615)
Commit c40a4c3

**Error message;**
Unhandled exception thrown: read access violation.
sprite_idx was 0x20E62BE.

**Call stack;**
```
>	openrct2.dll!sprite_move(short x, short y, short z=229, rct_sprite * sprite=0x010e64bc) Line 450	C
 	openrct2.dll!openrct2_loop(...) Line 420	C
 	openrct2.dll!openrct2_launch(...) Line 326	C
 	openrct2.dll!StartOpenRCT(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance=0x920a4253, char * lpCmdLine=0x00000000, int nCmdShow=0) Line 114	C
 	[External Code]	
```

**Autos;**
```
+		sprite	openrct2.exe!0x010e64bc (load symbols for additional information) {pad_00=0x010e64bc "" unknown={sprite_identifier=...} ...}	rct_sprite *
+		sprite->unknown	{sprite_identifier=0 '\0' misc_identifier=0 '\0' next_in_quadrant=65535 ...}	rct_unk_sprite
```

**Locals;**
```
		current_position	Variable is optimized away and not available.	
		new_position	7937	int
		new_x	Variable is optimized away and not available.	
		new_y	Variable is optimized away and not available.	
+		sprite	openrct2.exe!0x010e64bc (load symbols for additional information) {pad_00=0x010e64bc "" unknown={sprite_identifier=...} ...}	rct_sprite *
+		sprite_idx	0x020e62be {???}	unsigned short *
+		sprite2	0x020e62bc {pad_00=0x020e62bc <Error reading characters of string.> unknown={sprite_identifier=??? misc_identifier=...} ...}	rct_sprite *
		temp_sprite_idx	Variable is optimized away and not available.	
		x	Variable is optimized away and not available.	
		y	Variable is optimized away and not available.	
		z	229	short
```

**Comment by Gymnasiast** [comment]
@Nubbie Thanks for that, but that dump is a year and three months old. It does not reflect the current game status well.

@Superjustinbros There is a slash in your park name. That is an invalid character in (almost?) every file system. If I try to save your scenario without it, it works.
