### ISSUE TITLE
Bug: Subfolders not searched in 'game_path' folder for custom tracks

### ISSUE THREAD

**Issue by Stevoisiak** [OpenRCT2/OpenRCT2#3408]
**OS:** Windows 10
**Version:** 0.0.5 
**Commit:** c40a4c3 
- [x] Reproducible in RCT2 (vanilla)

When adding additional scenarios to OpenRCT2, such as the [RCT1 recreations pack](http://www.mediafire.com/download/3cw47sd2wt3hues/ExactRCT1Recreations.zip), it would be nice to be able to organize the game's scenarios into subfolders and still have them be detected by the game. This would allow users to keep downloaded scenario packs separate from each other, rather than having them all merged together in the same folder.

This would allow for folder structures such as the following example.

```
OpenRCT2/
   scenarios/
      rct1_recreations/
         *scenarios*
      rct2/
         *scenarios*
      rct2_bonus/
         *scenarios*
      sandbox_scenarios/
         *scenarios*
      vj_scenario_pack/
         *scenarios*
   tracks/
      rct2/
         *tracks*
      rctmart/
         mini_golf_pack/
            *tracks*
         ghostbuster_pack/
            *tracks*
      user/
         *tracks*
```

**Steps to reproduce:**
1. Download a custom scenario pack for RCT2
2. Place files in a subfolder in `scenarios`
3. Run game and check scenario list

**Comment by AaronVanGeffen** [comment]
The game already detects scenarios in subdirectories, so assume your issue is not with it not finding those scenarios, but with their presentation?

**Comment by Stevoisiak** [comment]
That's odd. It's not detecting them in subfolders on my machine
![screenshot 2016-04-23 11 55 50](https://cloud.githubusercontent.com/assets/1330770/14762516/6acbf50c-094a-11e6-9245-9b3e06db5eb8.png)

**Comment by AaronVanGeffen** [comment]
It should be looking for them in OpenRCT2's config directory, if I'm not mistaken.

**Comment by Stevoisiak** [comment]
Do you mean the user data folder?

**Comment by AaronVanGeffen** [comment]
The one in your user profile directory, yes. On Windows, it's probably located in the Documents folder. You'll want to make a `scenario` directory there, if it doesn't exist already.

**Comment by Stevoisiak** [comment]
Oh THAT explains the issue.
So by default, when searching for scenarios in the game data folder, RCT2 and OpenRCT2 look in the folder ``scenarios``. However, when looking through the user data folder, OpenRCT2 looks for ```scenario```. That's why putting my files in the user data folder never worked.

In addition, it looks like OpenRCT2 checks subfolders when searching the user scenarios directory, but not when searching the base game directory.

**Comment by AaronVanGeffen** [comment]
>  So by default, when searching for scenarios in the game data folder, RCT2 and OpenRCT2 look in the folder scenarios. However, when looking through the user data folder, OpenRCT2 looks for scenario. That's why putting my files in the user data folder never worked.

Yes, that is a bit confusing...

> In addition, it looks like OpenRCT2 checks subfolders when searching the user scenarios directory, but not when searching the base game directory.

It should, though. For both instances, the same procedure (`scenario_list_include`) is called.

**Comment by Stevoisiak** [comment]
In my initial setup, OpenRCT2 would load the scenarios if i put them in ```OpenRCT2/Scenarios```, but not if they were in ```OpenRCT2/Scenarios/rct2```

I should note that I'm using the launch argument ```--user-data-path=.\user``` so I can keep all of my save data portable and self-contained in my OpenRCT2 folder

**Comment by AaronVanGeffen** [comment]
Looking at [scenario_list.c](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/scenario_list.c#L55), you can see what's going on under the hood. If, as you say, scenarios aren't loaded recursively in the base game directory, I would consider that a bug.

**Comment by Stevoisiak** [comment]
@AaronVanGeffen I have my RCT2 directory set to be the same folder as OpenRCT2 with the necessary files copied over so I can run OpenRCT2 as a standalone program

**Comment by Stevoisiak** [comment]
I freshly installed and ran RCT2 on my drive, set ```game_path = "E:/OpenRCT2/RollerCoaster Tycoon 2/RollerCoaster Tycoon 2 Triple Thrill Pack"``` in config.ini, and made a subfolder for RCT1 maps in ```E:\OpenRCT2\RollerCoaster Tycoon 2\RollerCoaster Tycoon 2 Triple Thrill Pack\Scenarios\rct1_recreations```.

Same results. The custom scenarios were not loaded from the subfolder

**Comment by Stevoisiak** [comment]
Issue has been fixed by 45843ec

**Comment by Stevoisiak** [comment]
On closer inspection, it appears the issue was only fixed when loading scenarios from the game data folder. There still appears to be an issue when loading saved track designs

**Comment by IntelOrca** [comment]
@Stevoisiak tracks and objects is not a bug. I have not implemented multiple searching of those folders yet.

**Comment by IntelOrca** [comment]
I think I implemented this awhile ago.
