### ISSUE TITLE
Idea: Option to randomize Entertainers' costumes when placed

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3413]
A very minor feature, but I figured it wouldn't be too hard to implement.

Simply put, when you hire an Entertainer, they could be set to be generated with a random costume instead of always spawning as a Panda.

**Comment by devnoname120** [comment]
Related to the second suggestion of #1451.

> Add option for random entertainers

**Comment by Gymnasiast** [comment]
Has been implemented now.
