### ISSUE TITLE
Show SV4 games in the load/save dialog

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#3415]
Version:  44a92e3 

There are two issues regarding loading SV4 games:
- The built-in dialog does not show them
- ~~When using the native dialog, they are shown, but attempting to load them yields the error~~

```
Unable to load file..

```

~~(that includes the empty newline).~~

Edit 26 APR: Second error now solved, first one still present.

**Comment by IntelOrca** [comment]
> When using the native dialog, they are shown, but attempting to load them yields the error

May be operating system specific.

**Comment by AaronVanGeffen** [comment]
> When using the native dialog, they are shown, but attempting to load them yields the error

+1 from me on OS X. Importing using the command line works just fine, however.

On a somewhat related note, the scenario editor does not seem to call the new RCT1 import procedures yet.

**Comment by IntelOrca** [comment]
@AaronVanGeffen it does

**Comment by AaronVanGeffen** [comment]
@IntelOrca Open the Scenario Editor, first step. 'Load Landscape', system dialog window, select SV4 save file. Only the landscape is imported, not the rides. Do the same for SV6 and rides are imported as well.

**Comment by IntelOrca** [comment]
@AaronVanGeffen ah, that is a bug then, it should clear rides always - whatever you load just like in vanilla.

**Comment by Gymnasiast** [comment]
It loads correctly with CLI, yes. (I wouldn't have been able to carry out my improvements otherwise.)

**Comment by IntelOrca** [comment]
@Gymnasiast can you send me the SV6?

**Comment by Gymnasiast** [comment]
You mean the SV4? Here is one, but it happens with every single SV4.

[bpbtestbanner.sv4.txt](https://github.com/OpenRCT2/OpenRCT2/files/234438/bpbtestbanner.sv4.txt)

**Comment by Gymnasiast** [comment]
I get this error, btw:
```
VERBOSE: loading saved game, /home/michael/bpbtestbanner.sv4
ERROR[/home/michael/Dropbox/Aptana Studio 3 Workspace/OpenRCT2-4/src/game.c:745 (game_load_sv6)]: invalid checksum
VERBOSE: loading title
```
Even though it isn't an SV6, so that probably what goes wrong here.

**Comment by IntelOrca** [comment]
@Gymnasiast I think showing SV4s in the load dialog should be a separate issue and labeled as enhancement.

**Comment by Gymnasiast** [comment]
The load/save dialog now lists SV4 and SC4 files. (#4779)
