### ISSUE TITLE
RCT1 import: missing booster tracks

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/OpenRCT2#3416]
I recently dug up some very old RCT1 save games (dating back to November 1999!) so I've been eager to use the RCT1 import feature.

Importing this particular save, I noticed something peculiar with a Corkscrew Roller Coaster: it seems to be missing quite a few track pieces.

This is on OS X on cea0f30121b36352816265fb72e564b3d3d96fb0

![scr4](https://cloud.githubusercontent.com/assets/604665/14770412/6c17e39e-0a71-11e6-9a83-bfa5c3650156.png)

Interestingly, I can test the ride just fine:

![scr5](https://cloud.githubusercontent.com/assets/604665/14770413/6c1b28b0-0a71-11e6-9cd3-ac138b05c0bb.png)

It looks like it may be missing flat pieces? (If so, it looks like this particular design couldn't have worked, but that's besides the point.)

[Trinity Islands (RCT1 archive).zip](https://github.com/OpenRCT2/OpenRCT2/files/233659/Trinity.Islands.RCT1.archive.zip)

**Comment by jensj12** [comment]
It are the boost/turbo track pieces that were in RCT1 but not in RCT2 (like the flat to steep junior track pieces). Looking at the design, it really needed these boosts.

**Comment by duncanspumpkin** [comment]
Yes boosts are currently still not compatible. When we have finished the drawing functions it can be brought back in. Could possibly replace the image with the breaks image if we want a stop gap and then would have to make some modification to the vehicle code to boost the vehicle.

**Comment by IntelOrca** [comment]
I thought boost did exist for one or two coaster types in RCT2?

**Comment by Gymnasiast** [comment]
Launched lift hill did, but that is on a 25° incline. I have never seen RCT1 boosters anywhere in RCT2.

**Comment by IntelOrca** [comment]
Okay, at least there is some code we can base the boosts off then if we implement them.

**Comment by CybertronicToon** [comment]
Would the brakes image eventually be replaced with an image similar to the RCT1 image?

**Comment by Gymnasiast** [comment]
@CybertronicToon Yes.

**Comment by AaronVanGeffen** [comment]
This is tackled by #4963.

**Comment by Horsti12** [comment]
@AaronVanGeffen already said it. This is now possible since some days. So please close this!
