### ISSUE TITLE
Suggestion: Make separate folder for crash dumps

### ISSUE THREAD

**Issue by Stevoisiak** [OpenRCT2/OpenRCT2#3417]
**OS:**  Any
**Version:** 0.0.5
**Commit:** c40a4c3

As of now, crash dumps are saved directly into the root of the user data folder. This can cause unnecessary clutter if crash logs start to stack up, since they would only be needed when sending in bug reports.

I suggest saving crash dump files into a separate crash dump folder. Perhaps `*user_data_path*\dump`

**Steps to reproduce:**
1. Play OpenRCT2
2. Have it crash a few times

**Screenshots / Video:**

![openrct2_user_data_folder](https://cloud.githubusercontent.com/assets/1330770/14770697/afa6d86c-0a45-11e6-9cc8-abbdfc968908.PNG)
My user data folder for OpenRCT2

**Comment by IntelOrca** [comment]
This is deliberate as the crash dump will fail if the sub directory does not exist. The user can delete it between ensuring it exists and the crash dump being generated.

**Comment by kevdog3700** [comment]
I think this would be a great idea as I have about 20 crash dumps laying around and I think most people wont go around deleting files/folders from there openrct folder.

**Comment by DyXel** [comment]
What about the game crashing if the crash dump directory is not there?

Jokes aside, it would be great to have a separate directory, and as @kevdog3700 pointed out, we rarely would delete that directory (perhaps check it between crashes or startups?). Also we could use the same directory for debug logs...

**Comment by Stevoisiak** [comment]
The folder just be created on startup along with the other user directory folders

**Comment by IntelOrca** [comment]
@DyXel that is exactly what happened though when we first tested it. If the sub directory does not exist, no crash dump is created. And creating it on startup isn't full proof.

**Comment by jensj12** [comment]
How about moving crashdumps to a separate folder on startup?

**Comment by Nubbie** [comment]
I have right now 43 dumps that takes 200 mb together, I would love to just have it in a separate folder which makes it easier to clean.. OR.. have a max limit like 10 dumps before it overwrites itself (Just like auto-saves)

Ideas:

- Separate folder for dumps (also checks if the folder exist)
- A max limit for dumps before it overwrites the oldest one

**Comment by Wirlie** [comment]
I prefer the two ideas that you have suggested. :P

**Comment by Nubbie** [comment]
Had to delete dump files and saves created from them that took 1.7 GB manually as it blended in with the other stuff.. clustering the OpenRCT2 folder :U
