### ISSUE TITLE
Hotkey to toggle fullscreen

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#3421]
Idea came from: https://openrct2.org/forums/topic/1200-linux-f11-hotkey-fullscreen/

Being able to quickly switch between windowed and fullscreen mode would be nice. Most ideally a custom hotkey. Some like F11, some like Alt+Enter.

**Comment by IntelOrca** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/platform/shared.c#L586

Already implemented right?

**Comment by jensj12** [comment]
I couldn't find it in the 'Shortcut keys...' options menu.

**Comment by Broxzier** [comment]
Making is customizible would be nice.

**Comment by Nubbie** [comment]
This was closed in 1370166
