### ISSUE TITLE
Cannot build for XP(RegDeleteTreeA,RegDeleteTreeW problem)

### ISSUE THREAD

**Issue by Lastorder-DC** [OpenRCT2/OpenRCT2#3422]
XP Build is impossible after c51f9a8eccaf515f4efc52720d4b07991adcc852 because it uses `RegDeleteTreeA`,`RegDeleteTreeW` which only avaliable after vista.

since there's no "delete registry key tree" function in XP, so we should implement for XP or remove "file type association remove" on XP.(I think removing is more realistic idea)

**Comment by janisozaur** [comment]
Are you sure about that? I assume you have a machine with XP, can you check if this works: https://transfer.sh/2Jk9D/openrct2-4149bcd.dll ?

**Comment by IntelOrca** [comment]
What compiler are you using to build for XP? We have setup Travis to use mingw which compiles - I made sure of that by disabling the file association feature from MINGW compilation.

**Comment by Lastorder-DC** [comment]
I used VS2015 and v140_xp PlatformToolset. I searched and noticed compiling with VS2015 with XP results bad. Right now, It seems MINGW compile is only way to get XP build...

**Comment by IntelOrca** [comment]
The reason we don't support a VS configuration for XP is because it would require a special build of the dependencies too in XP.
