### ISSUE TITLE
Max. people on ride overflows when operating limit is unlocked

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#3424]
**OS:** Windows 10
**Version:** 0.0.5-develop
**Commit:** 4149bcd

When the operating limit unlock cheat is checked, max. people on ride overflows like this:
1 -> 2 -> ... -> 254 -> 255 -> 0 -> 1 -> ...
Please let me know if it is duplicated.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Enable the operating limit unlock cheat.
2. Set the Max. people on ride's value into 255
3. Increase it, then it becomes 0. When decrease in this case, it returns 255 back.
4. Increase again, then it becomes 1 and cannot return back.

**Comment by e-foley** [comment]
I wouldn't call it a duplicate, but this issue is very similar to #2529—the only difference being that it concerns a number of riders rather than a number of seconds.  I suspect that a smart solution will likely resolve both issues.

**Comment by Gymnasiast** [comment]
Is this on a maze?

**Comment by telk5093** [comment]
@Gymnasiast Both maze and Spiral Slide.

**Comment by Mijago** [comment]
Just a note: Maximum shoot-off-on-start-speed on coasters also overflows on 922km/h. But nevertheless that is enough speed.
