### ISSUE TITLE
Add Server improvment

### ISSUE THREAD

**Issue by AnderssonPeter** [OpenRCT2/OpenRCT2#3426]
**OS:** Windows 10
**Version:**  0.0.5.0
**Commit:** 15031b9

If i add a server to the server list with the Add Server button it would be nice if this was added to the top not the bottom, also it would be nice if it stayed there so i wouldn't have to add it each time i restart the game or leave and rejoin because of a desync.

- [ ] Reproducible in RCT2 (vanilla)?
- [X] Multiplayer?

**Steps to reproduce:**
1. Start game
2. Click `Play with other players`
3. Click `Add server`
4. Fill the dialog and click OK.

**Comment by IntelOrca** [comment]
Click and hold down on the server. This will open a dropdown with the option to save the server.
