### ISSUE TITLE
Game crashes when in the main menu after the map switches to Sprightly Park

### ISSUE THREAD

**Issue by birthdaybrian** [OpenRCT2/OpenRCT2#3428]
**OS: Windows 7 Home Premium SP1 x64 (Modified Theme)** 
**Version:0.0.5-6** 
**Commit: cea0f30** 

When I have OpenRCT2 opened and the title sequence is set to RCT/AA/LL and wen the map switches to Sprightly Park, the game crashes and you get a Visual Studio message like "gParkFlags & PARK_FLAG_NO_MONEY. Can any developer please fix that bug.

I couldn't upload the picture of the error due to an error while trying to upload the picture.
- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Launch OpenRCT2
2. Set the title sequence to RCT1/AA/LL
3. Wait until the title sequence gets to Sprightly Park.

**Comment by Gymnasiast** [comment]
I can't reproduce this. Your Sprightly Park SV6 might be corrupt.

**Comment by IntelOrca** [comment]
Are you getting an assert or a crash to desktop?

**Comment by janisozaur** [comment]
must be
```
src/peep/peep.c=8460=static void peep_spend_money(rct_peep *peep, money16 *peep_expend_type, money32 amount)
src/peep/peep.c:8462:   assert(!(gParkFlags & PARK_FLAGS_NO_MONEY));
```

**Comment by birthdaybrian** [comment]
@IntelOrca Crash to desktop.

**Comment by janisozaur** [comment]
Does not happen on b6525c2
