### ISSUE TITLE
Building wooden coaster and test/open it can freeze game

### ISSUE THREAD

**Issue by YJSoft** [OpenRCT2/OpenRCT2#3429]
**OS: OS X** 
**Version: 0.0.5** 
**Commit: 83acafe** 

Explanation of the issue...

- [x] Reproducible in RCT2 (vanilla)? - checked with OpenRCT2 save file
- [x] Multiplayer? - only effects client

**Steps to reproduce:**
1. Build wooden coaster like this
<img width="511" alt="Build wooden coaster like this(p shape) - step 1" src="https://cloud.githubusercontent.com/assets/5893514/14802519/57d26e92-0b8c-11e6-8350-3d5b46c2a9a1.png">
2. Disable clearance check and build like this(make circle) so coaster looks like P
<img width="516" alt="Build wooden coaster like this(p shape) - step 2" src="https://cloud.githubusercontent.com/assets/5893514/14802530/75e3392a-0b8c-11e6-8590-ee1df4bc28b9.png">
3. test or open ride and OpenRCT will freeze
4. This can reproduced on multiplay but no effect on server(only client will hang)

I think coaster complete check loops forever since there will be no dead end or connection to station end.

**Save game:**
[WoodenBug.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/235623/WoodenBug.sv6.txt)

**Comment by Nubbie** [comment]
Duplicate of issue [#2081](https://github.com/OpenRCT2/OpenRCT2/issues/2081)

**Comment by YJSoft** [comment]
Oops.

**Comment by Nubbie** [comment]
It's an old issue so it's alright, had seen it before here on Github and wanted to try it out :p
