### ISSUE TITLE
Track design crashes upon placement.

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3447]
[Snow Leopard.zip](https://github.com/OpenRCT2/OpenRCT2/files/240811/Snow.Leopard.zip)
This track design crashes when I try to place it with scenery. In not then it will simply place the scenery itself while the ride tracks disappear, requiring you place the same track without the scenery to get the proper effect.

**Comment by Nubbie** [comment]
Seems to be a 'LIM powered roller coaster' design
I could load it without scenery too, can't load it with scenery tho' as I seem to be missing them, did you use custom scenery too?
I can see 'ICECUBE' was used, but is there any custom things in it?

You maybe are missing that scenery too then, or it's just corrupted.

Don't think it's an issue with the game, more that specific ride

**Comment by Superjustinbros** [comment]
A lot of other track designs that I've made/saved recently encounter the same error; If they contain at least one scenery object (custom or not) when saved, and they're imported into a park that supports the scenery elements it has, it'll show up as blank on the track preview window even if it generates the full white ghost tracks when being hovered on the map itself, and once the design is placed, the tracks disappear.

**Comment by janisozaur** [comment]
@Superjustinbros we've refactored some code around track designs recently, can you check if your issue persists?

**Comment by Superjustinbros** [comment]
It seems as if this error has been- as far as I can see, fixed.
