### ISSUE TITLE
Random crash during gameplay

### ISSUE THREAD

**Issue by pdewit** [OpenRCT2/OpenRCT2#3448]
**OS:** Windows 10
**Version:** 0.0.5
**Commit:** cd7482b

The game randomly crashes whenever the save file is loaded.

**Steps to reproduce:**
1. Load save file
2. Crash!

**Dump file**
[a93ac6a0-859a-48da-a816-640395a58eaf.zip](https://github.com/OpenRCT2/OpenRCT2/files/241098/a93ac6a0-859a-48da-a816-640395a58eaf.zip)

**Save game:**
[a93ac6a0-859a-48da-a816-640395a58eaf.zip](https://github.com/OpenRCT2/OpenRCT2/files/241100/a93ac6a0-859a-48da-a816-640395a58eaf.zip)

**Comment by Nubbie** [comment]
@pdewit Wonder if your commits fixed this issue?

**Comment by pdewit** [comment]
@Nubbie it did fix the crash for me, but it's probably something else that causes the issue. This is just resolving the symptoms (and not what makes it crash/desync in the first place).

**Comment by janisozaur** [comment]
Does not crash on b6525c2
