### ISSUE TITLE
Allow 'Remove all guests' without closing rides

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#3453]

**Comment by Mijago** [comment]
Would it be enough to re-open the ride after the cheat has been used?
Of course, the states get lost, but then you do not have to re-open every single ride on your own.

**Comment by Gymnasiast** [comment]
Opening all rides at once is a matter of pressing a button in the Rides List. It's really about keeping the vehicles etc. exactly where they are.

**Comment by Gymnasiast** [comment]
This is now implemented.
