### ISSUE TITLE
Three Monkeys RCT1 Save 

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#3454]
**OS:** Windows 10
**Version:**0.0.5

When I try to load my RCT1 save of Three Monkeys it crashes the game. I've included the save game and dump files in the zip attached.

**Dump file & Save game:**

[Three Monkeys.zip](https://github.com/OpenRCT2/OpenRCT2/files/242927/Three.Monkeys.zip)

**Comment by PurpleMadness** [comment]
Seems to bug out when drawing the Looping Rollercoaster with index 38 in a callproc.

**Comment by janisozaur** [comment]
We don't use code from vanilla anymore, this does not happen anymore.
