### ISSUE TITLE
Disable terraforming height limit

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#3455]
As the title says, it would be nice if terraforming was not capped as it currently is. RCT2 save files are capable of handling higher terrain than the max, as evidenced by the NEDesigns park [Wasteland](http://www.nedesigns.com/project/95/wasteland/). It would be nice to have this increased terrain height as a feature and not have to go through outside tools. It is currently possible in OpenRCT2 to create terrain higher than the limit using the random terrain generation feature, so having the limit be disabled by a cheat is not optimal because the cheat button does not appear in the scenario editor.

**Comment by Gymnasiast** [comment]
It has to be investigated whether no side effects occur when doing this.
