### ISSUE TITLE
'No money' flag on RCT1 saves and scenarios not correctly imported

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#3459]
**OS:** Windows 10
**Version:** 0.0.5

If you load the Arid Heights SC4 file from RCT1, you start off with 0 money. Where as in the original scenario you have unlimited money. 

I've included my SC4 file 

[SC24.zip](https://github.com/OpenRCT2/OpenRCT2/files/243545/SC24.zip)

**Comment by Gymnasiast** [comment]
Noticed this problem as well with other saves and scenarios. I therefore changed the title to be more generic.
