### ISSUE TITLE
Add filter type to view only objects in use

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#3469]
The use case is determining if you have custom objects in use and what they are. I have thousands of custom scenery objects, and making sure that absolutely zero of them are in use by scrolling through the list and looking for the grey tickmark is incredibly tedious and impractical. That is why it would be nice to have a second filter type that shows all objects, unused objects, and used objects. For example, if I unchecked all filters except Custom and then filtered again by used objects, it will show me all custom objects in use.

**Comment by Superjustinbros** [comment]
I second this.

**Comment by Gymnasiast** [comment]
Showing only checked items (or showing them first) would probably work as well.

**Comment by janisozaur** [comment]
Showing them first could be a bit problematic: when do you sort the list? upon selection would lead to items jumping around in the list, while upon window opening would cause them to be out of order even after you've changed selection.

**Comment by Gymnasiast** [comment]
@janisozaur We can already sort by track ride or ride type, so adding a way to filter by checked status shouldn't really present problems, I think.

**Comment by IntelOrca** [comment]
Isn't it easier just to add a count at the bottom which displays how many items are currently showing and checked in the filtered list?

**Comment by chrismilne300** [comment]
@Gymnasiast that's how I see this working.
![fg](https://cloud.githubusercontent.com/assets/1381723/14951472/108e267e-1051-11e6-8463-daa384b816fd.jpg)

By adding another button the sorts the checked items as shown above

**Comment by Gymnasiast** [comment]
@chrismilne300 That is exactly what I was talking about. Though it would have to be applied to other kinds of objects as well, of course.

**Comment by janisozaur** [comment]
@chrismilne300 the button you presented is usually associated with select/deselect all, even if in the row with column headers.

**Comment by chrismilne300** [comment]
@janisozaur Your right, what about leaving the button blank until the user clicks it then, display either an up or down arrow depending on how the user wants it sorted.

I also think it might be a good idea to display the source game as an extra column so the user can sort by expansion, base game or custom? Or is that a bit over kill with the filers.

![screen shot 05-02-16 at 10 55 am](https://cloud.githubusercontent.com/assets/1381723/14952053/1a329242-1055-11e6-9b3b-2048a5399649.PNG)

**Comment by Gymnasiast** [comment]
:+1: for the first idea.
The second is indeed overkill; we have the filters for that.

**Comment by spacek531** [comment]
Here is how I see it working when not sorted by checked:
![image](https://cloud.githubusercontent.com/assets/3454156/14956872/d5e9afda-1036-11e6-9da2-bd12b3f5eca3.png)

**Comment by Gymnasiast** [comment]
I think this is sufficiently addressed now we have filters to select based on origin, and to show only selected items.
