### ISSUE TITLE
Floating Numbers while Paused Crash

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3479]
**OS:** Windows 7

Explanation of the issue...

If you pause the game then proceed to make a large amount of changes in a money-enabled scenario, enough to generate many of the floating money numbers, followed by unpausing the game, the game will abruptly crash.

**Steps to reproduce:**
1. Play on a scenario with money enabled
2. Pause the game and make sure construction while paused is enabled via Cheats
3. Build/remove stuff to generate many floating numbers.
4. Unpause the game.

Here's the save/dump I tested this on.
[Crash May 2.zip](https://github.com/OpenRCT2/OpenRCT2/files/246135/Crash.May.2.zip)

**Comment by chrismilne300** [comment]
I find it strange how the numbers are paused anyway, would me more sense if they just acted as normal even when the games paused.

**Comment by Superjustinbros** [comment]
Yeah.

**Comment by PurpleMadness** [comment]
It seems to crash in the same location as #3448. Perhaps related?
