### ISSUE TITLE
Landscape smoothing does not work for mixed terrain textures

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#3481]
**OS:** Windows 10
**Version:** 0.0.5-develop
**Commit:** 98bff69

Landscape smoothing does not work when enabled:
![](http://i.imgur.com/komKTfb.png)
Also tested on slopes.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Enable landscape smoothing
2. Paint some land with textures that are normally bleded

**Comment by IntelOrca** [comment]
Looks like this is only between different terrain types, it still seems to smooth it on the slopes.
