### ISSUE TITLE
Spectators are able to drown staff

### ISSUE THREAD

**Issue by supervarken** [OpenRCT2/OpenRCT2#3483]
**All OS's** 
**Pretty sure since staff naming is public** 

So when someone joins a server he can name staff, but also pick them up and place them somewhere else. Using this anyone, even spectators, can drown staff by putting them in water. Which is quite annoying if you're trying to get high ratings.

- [x] Only in multiplayer

**Steps to reproduce:**
1. Visit a random server
2. Press staff button
3. Press one of the park's staff
4. Press the move icon
5. Drop them in the water.

I hope someone can set the moving of staff only avaible if you have staff permissions.

**Comment by Nubbie** [comment]
Could not reproduce this
I could not change the name of the staff member as it just said: Access Denied

You CAN pick staff up and DROWN them tho, BUT, doing so will get you de-synced and ONLY drown the staff member on the client side.

**Comment by duncanspumpkin** [comment]
Staff movement doesn't work in multiplayer and will cause a desync. You can try grief all you like but the server won't accept a player doing that.
