### ISSUE TITLE
Idea: Teleport off-path guests/staff after 30 seconds

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3485]
This is something I'd implement to help combat guests that become 100% stupid with random movements the instant they go off of a path by you deleting the paths they're walking down or you dropping them off a path.

What occurs is if a guest or staff (that isn't a Handyman with watering gardens and/or mowing grass permissions) finds their way off a path, after 30 seconds they are automatically placed into a random path in the park, similar to the routine of auto-spawning staff when hiring them.

**Comment by Gymnasiast** [comment]
The player should not remove paths with guests or staff on them IMO.

**Comment by Nubbie** [comment]
Could see this more as a cheat where they teleport back to the nearest path if you push a button

**Comment by spacek531** [comment]
I'd rather that the RNG that decides peep direction when on ground is weighted towards making the peep go towards the park entrance.

**Comment by Superjustinbros** [comment]
@spacek531 I prefer this option, because to me it doesn't make sense that peeps instantly lose all sense of direction once they get dropped off a path.

@Gymnasiast There are a variety of reasons one would want to remove a path with a guest walking over them, like if they accidentally put down a certain path by mistake and the brain-dead AI decides to make the guest(s) walk onto them as you try to remove it (especially if its somewhere in a crowded area). It also becomes a problem if desync online occurs.

**Comment by jensj12** [comment]
Remember guests can walk over ghost paths, but can not enter them. Though removing paths that way takes a lot more time. A standard pahtfinding search with all ground tiles as 'path' and any path tile as goal would do fine (they can only look 13 tiles ahead of themselves in an open area, so they won't get super smart off-path), as well as a bias towards the entrance (though that may fail in some cases).

**Comment by Superjustinbros** [comment]
Especially if there's large bodies of water that the guests can accidentally run into and drown in.

**Comment by Superjustinbros** [comment]
Okay then, I think I'll just discard this for now, since not many seem to be in favor of it or some other way of helping peeps that get separated from pathways back on track due to player error or carelessness.

**Comment by pizza2004** [comment]
Personally I feel like peeps should just sort of scan around for the closest path and then head towards it.  I mean, you could easily make a kind of argument about being able to see a path from a distance if they wandered off/were taken off the path.  Perhaps you'd want some sort of limit as to how far away they could just hone in on the path and head back to it, but still, it seems like something that should be in the game.

**Comment by Superjustinbros** [comment]
You think so?

**Comment by pizza2004** [comment]
To be very clear, I think teleporting them back to a path is too far, but it just doesn't make any sense at all for guests to just bumble about in the middle of nowhere when they're close to a path.  I mean, perhaps make them bumble a little until they're turned towards a path, but as long as they're at least 10 tiles away from a path in front of them they should 100% of the time just head straight for it.  It's stupid to think otherwise (except maybe if the path is up a hill, but that seems like a difference in AI that would just be a hassle).

**Comment by Superjustinbros** [comment]
I see. Yeah being able to find a path and relocate themselves afterwords would make a lot more sense compared to losing all sense of direction the instant they find themselves on any surface that isn't a path.
