### ISSUE TITLE
Crash when setting staff patrol 

### ISSUE THREAD

**Issue by kevdog3700** [OpenRCT2/OpenRCT2#3487]
Windows 10
0.0.5.0-develop 
142c548

When i was placing staff in my park (by my red invert) and setting patrols for them the game crashed. happens with both handymen and mechanics. 

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Load the save game
2. Start placing staff and setting new patrol routes and wait for it to crash.
3. you may have to try placing in many areas and with many staff.

**Dump file**
[Dump.zip](https://github.com/OpenRCT2/OpenRCT2/files/247934/Dump.zip)

Video: https://vid.me/L2dE
(sorry about the low quality)

**Save game:**
Inside of dump.zip

**Comment by zsilencer** [comment]
I wasn't able to load the park, was missing "AUPS32" object, where did you get this?

**Comment by kevdog3700** [comment]
Try this save.
[Unnamed Adventure V4.zip](https://github.com/OpenRCT2/OpenRCT2/files/251063/Unnamed.Adventure.V4.zip)

**Comment by Wirlie** [comment]
Oh yes, I have the same issue :(

**Comment by Wirlie** [comment]
This can help:

My save game: (change ext)
[64e9f391-6a1b-4156-88d4-8d61e9b3f563.txt](https://github.com/OpenRCT2/OpenRCT2/files/253183/64e9f391-6a1b-4156-88d4-8d61e9b3f563.txt)

and the dmp file:
[DumpFile.zip](http://workgroupweb.skn1.com/DumpFile.zip)

**Comment by kevdog3700** [comment]
ok the zip has AUPS32 in it
[AUPS32.zip](https://github.com/OpenRCT2/OpenRCT2/files/253248/AUPS32.zip)

**Comment by zsilencer** [comment]
Can you try my fix and see if it is still happening for you?

**Comment by Wirlie** [comment]
For me, your fix works fine and I cannot get the crash :+1:

**Comment by Wirlie** [comment]
@kevdog3700 Can you confirm if the issue has been fixed? For me, the fix solves my problem.

**Comment by kevdog3700** [comment]
Its good I dont crash anymore thanks.
