### ISSUE TITLE
Online: Letting players change the map + load maps (Dedicated servers)

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#3489]
This would be more for people who wants to run dedicated servers - Letting player that aren't the host to change maps and load maps
**Why:**

  Perfect for people who want to run dedicated servers
  Perfect for admins on a server to revert a grief if the host is gone
 Less work for a host

 [X] Multiplayer

![letting players change map](https://cloud.githubusercontent.com/assets/17282384/15020683/7414947a-1223-11e6-999b-9ed5710a4048.png)

**Comment by duncanspumpkin** [comment]
This would require a ridiculous amount of work. We have no way to pass saves to the server.

**Comment by pizza2004** [comment]
It could always do all saving and loading directly from the server itself.  It would be much easier to just send a list of saves to the client to be selected from than to send a save to a server.  You could also start a new scenario from the scenarios that are on the server, and you could add a menu option to make the server save.

**Comment by Gymnasiast** [comment]
Probably too much work and complexity for what it improves.
