### ISSUE TITLE
Idea: Additional "Multiplayer" options in dropdown window

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3490]
These were a few things I was considering suggesting for some time, so here they are.

*Disconnect: Automatically disconnect from the server while still keeping the same map intact.
*Resync: Attempt to re-sync with the server so everything is up-to-date.

Both of these options would show a conformation window to conform if the player wants to disconnect/resync.

**Comment by duncanspumpkin** [comment]
https://github.com/OpenRCT2/OpenRCT2/pull/3153
