### ISSUE TITLE
Cannot change "Lift Hill Chain/Launch Speed" if over/under limit if limits are turned off

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3492]
If you have "Unlock Operating Limits" enabled and try to adjust either the Lift Hill Chain Speed or the Launch Speed of a coaster, they will display a red window and not adjust at all, as opposed to dropping to the maximum or rising to the minimum after one click as with changing the number of cars on a coaster.

**Comment by Nubbie** [comment]
Seems to be fixed in c8b8f0f
