### ISSUE TITLE
crash in multiplayer

### ISSUE THREAD

**Issue by FL0WL0W** [OpenRCT2/OpenRCT2#3496]
**OS:** Windows 10
**Version:** 0.0.5.0
**Commit:** 0a710d3

Explanation of the issue... crash

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer? in multiplayer

**Steps to reproduce:**
1. 
2. 

**Dump file**
[0d21e687-c2f3-4f4f-82dc-414c2749e183.zip](https://github.com/OpenRCT2/OpenRCT2/files/250150/0d21e687-c2f3-4f4f-82dc-414c2749e183.zip)

**Screenshots / Video:**
Drag / drop screenshots here. Use https://vid.me to upload video.

**Save game:**
Change the file extension to .txt or package to a .zip so that it can be drag / dropped here...

**Comment by duncanspumpkin** [comment]
You've provided literally no information

**Comment by IntelOrca** [comment]
Apart from a dump file and that it is multiplayer... this is most likely the invalid track element bug.
