### ISSUE TITLE
Junior Coaster missing trackpiece (RCT1 Import)

### ISSUE THREAD

**Issue by Horsti12** [OpenRCT2/OpenRCT2#3497]
**0.0.5.0 build d8068a4** 
 
**Steps to reproduce:**
1. Open Diamond Heights in RCT1 and save the game.
2. Open the save game from RCT1 and load it in OpenRCT2.

**Screenshots / Video:**
![rryke20](https://cloud.githubusercontent.com/assets/12634026/15043885/19d12eb6-12d1-11e6-8394-9932b6e30d90.png)

It only happends on this part of the rollercoaster. Also the save game is not broken, because everytime you save the game in rct1, it is wrong in openrct2

**Comment by fromthere** [comment]
> The drawing code for track has been hacked slightly to allow the Junior RollerCoaster to contain steep slopes. It borrows the steep slope from the Water Coaster ride, and will not draw anything for the flat to steep and steep to flat track pieces. This is for the sake of Diamond Heights.

see #3320. since RCT2's junior coaster doesn't have steep slope(RCT1 had it) it's not bug.(It just needs graphic) anyway this issue is needed for tracking, I guess.

**Comment by duncanspumpkin** [comment]
Will be taken care of in the Jr RC track paint pr.

**Comment by pizza2004** [comment]
So, I was just wondering, are we gonna make it so the game can load the graphics from RCT 1 and use them for stuff like this?
