### ISSUE TITLE
Guests can enter closed queue lines

### ISSUE THREAD

**Issue by jensj12** [OpenRCT2/OpenRCT2#3499]
**OS:** win10
**Version:** 0.0.5 develop
**Commit:** d8068a4

(this is the issue raised in the comments of #3271 )
If two queue lines from the same ride are on the opposite side of a path tile, guests can enter the queue without joining the queue, they'll walk to the end and back. Same for a queue and a shop. Two queue lines from different rides doesn't seem to trigger the issue.
I can't test anything in vanilla.

**Steps to reproduce:**
1. Open this save and watch

**Screenshots / Video:**
![scr104](https://cloud.githubusercontent.com/assets/13868449/15052745/64983a1a-12ff-11e6-8e5a-9c88e5916f81.png)

**Save game:**
[ClosedQueue.zip](https://github.com/OpenRCT2/OpenRCT2/files/250956/ClosedQueue.zip)

**Comment by Gymnasiast** [comment]
Does it affect vanilla as well?

**Comment by jensj12** [comment]
I can't test vanilla but it does happen in RCT1, so I suppose it's in vanilla too.

**Comment by Lastorder-DC** [comment]
![edited_scr1](https://cloud.githubusercontent.com/assets/18280396/15059232/2568e74c-135c-11e6-983a-059ab87c6e7f.png)
It affect vanilla too.

**Comment by PFCKrutonium** [comment]
They can also enter if the exit is too close to the entrance

**Comment by Lastorder-DC** [comment]
<img width="294" alt="2016-05-06 2 05 14" src="https://cloud.githubusercontent.com/assets/18280396/15064822/a944e12e-1393-11e6-937e-b8094bd24e0b.png">
If sign is built like this,

<img width="270" alt="2016-05-06 2 04 46" src="https://cloud.githubusercontent.com/assets/18280396/15064827/b609967a-1393-11e6-8bbc-e5dbefd16774.png">
guests will ignore signs and go through signs. I think this is related.

**Comment by Gymnasiast** [comment]
@Lastorder-DC The banner issue should only affect vanilla. Or does it affect OpenRCT2 as well?

**Comment by Lastorder-DC** [comment]
@Gymnasiast I tested with OpenRCT2 and it's happening.(a937a65)
