### ISSUE TITLE
Track previews for tall rides

### ISSUE THREAD

**Issue by campbelljc** [OpenRCT2/OpenRCT2#3502]
**Version:** 0.0.4
**Commit:** 1eb91cb21044cdd46ac957c956d2ae64255a6bfb

Issue:
In the track design manager, track designs that are long on one axis and small on the other (e.g. most Roto-Drop rides, reverse freefall coasters, etc.) don't show up well in the preview area. See attached for example track file (Roto-drop track).

Suggestion:
Alter zoom level for track previews if possible.
- [Yes] Reproducible in RCT2 (vanilla)

**Screenshots / Video:**
<img width="953" alt="screen shot 2016-05-05 at 8 50 31 pm" src="https://cloud.githubusercontent.com/assets/174064/15061436/43a6fd56-1303-11e6-9c6a-50ac3c9cf062.png">

[Inferno!.td6.zip](https://github.com/OpenRCT2/OpenRCT2/files/251406/Inferno.td6.zip)

**Comment by Patrik356b** [comment]
Even some vanilla wooden coaster track designs are too big to fully be shown in the preview
