### ISSUE TITLE
Crash In Multiplayer

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#3515]
**OS:** Windows 10
**Version:** 0.0.5

**Dump file**

[dumpfiles.zip](https://github.com/OpenRCT2/OpenRCT2/files/253488/dumpfiles.zip)

**Comment by janisozaur** [comment]
You have not provided build ID.

**Comment by chrismilne300** [comment]
@janisozaur Sorry build 355b163

**Comment by janisozaur** [comment]
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/3193
