### ISSUE TITLE
Multiplayer park appears and behaves differently for people in the same server

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#3516]
**OS:** Windows 8
**Version:** 0.0.5-develop build
**Commit:** 355b163

 I'm in a multiplayer session with someone, and even though we're in the same session the park appears different to us. In his version the paths to a stall (built through a wall) were unconnected and there was a peep jam forming, in my version everything was connected just fine and there was no peep jam. He then reconnected the paths. I saw the money things flying, indicating that he placed the paths, and while it fixed the issue for him it actually disconnected the paths for me. I guess this is why I found a lot of paths built through walls disconnected when I joined the server. 

- [ ] Reproducible in RCT2 (vanilla)?
- [X] Multiplayer?

**Comment by janisozaur** [comment]
Can you confirm if it happens *before* you get desynced?

**Comment by Liampie** [comment]
I can't pinpoint an exact moment that it happened. I might add, by the way, that the path-wall combinations that appeared different to us were built a few days ago and back then it didn't seem to cause any trouble/differences.

**Comment by IntelOrca** [comment]
@Liampie When you play multiplayer you will most likely get a message saying that the game has desynchronised. After this point, there will probably be a butterfly effect of differences. We have not yet found out all the reasons as to why the game desynchronises - and that is the bug, this is the symptoms.

**Comment by Liampie** [comment]
So if I connect all these paths BEFORE the game desynchronises, my changes are going to make it onto the savegame?

**Comment by janisozaur** [comment]
@Liampie yes. But keep in mind this does **not** imply the opposite: that once you get desynced, your changes will *not* make it onto savegame.

**Comment by IntelOrca** [comment]
@Liampie your changes should always appear on the server, providing that the server state actually permits it. One reason why it wouldn't is that the server doesn't have enough cash, but the client does.
