### ISSUE TITLE
Enhancement: Option to choose mono/stereo audio

### ISSUE THREAD

**Issue by Stevoisiak** [OpenRCT2/OpenRCT2#3518]
**OS:** All
**Version:** 0.0.5
**Commit:** fe826cd

In the audio options menu, there isn't any way to switch between mono or stereo sound. The option to play OpenRCT2 in mono audio could be a nice addition.

**Comment by IntelOrca** [comment]
Why would it be a nice addition? It was deliberately taken out.

**Comment by Stevoisiak** [comment]
Occasionally, I play with an earbud in one ear if I'm listening for a package delivery or a stove timer.

**Comment by IntelOrca** [comment]
Can't you set your OS sound to mono instead?

**Comment by Stevoisiak** [comment]
It's a shared PC, so I wouldn't want to alter audio options that affect the entire PC. I understand that it's a niche feature, but it is one I would appreciate having.

**Comment by PFCKrutonium** [comment]
In addition, changing the audio to Mono System Wide is a pita, at least imo.
