### ISSUE TITLE
Crash when using incorrect language setting in config.ini

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#3524]
**OS:** Windows 10
**Version:** 0.0.5-develop
**Commit:** fc74e50

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

After update (I don't know what commit exactly), OpenRCT2 crashes just after run.
I solved this issue by changing config.ini file like this:
``language = 0`` -> ``language = ko-KR``

I think it should have a compatibility for old settings.

**Dump file**
[af2f40e0-3bc8-4951-a0fd-9012fabc9ba0.zip](https://github.com/OpenRCT2/OpenRCT2/files/253827/af2f40e0-3bc8-4951-a0fd-9012fabc9ba0.zip)

**Comment by Gymnasiast** [comment]
It should certainly not crash in any case. It should fall back to English if the language is not recognised.

**Comment by telk5093** [comment]
But it has happened ... :(

**Comment by Gymnasiast** [comment]
Indeed, and we have to fix that.

**Comment by YJSoft** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/localisation/language.cpp#L159
fixed if changed to `return 0`

I think loading undefined language id should return 0, not 1(mean success)
