### ISSUE TITLE
Make vandalism

### ISSUE THREAD

**Issue by Lastorder-DC** [OpenRCT2/OpenRCT2#3526]
There's "Fix vandalism" cheat, but there's no "Make vandalism" cheat.
Of course, this cheat will not helpful, but as scenario maker, sometimes vandalism is needed to make scenario(vanilla scenario like Ivory Towers have vandalism in park)

so I think it would be good to have "Make vandalism" cheat.(or destroying objects?)

**Comment by Gymnasiast** [comment]
Implemented in the https://github.com/Gymnasiast/everything-must-die plug-in.
