### ISSUE TITLE
Cheat: allow chain lift on any part

### ISSUE THREAD

**Issue by BelgianGuyNE** [OpenRCT2/OpenRCT2#3533]
**OS:** 
**Version:** 
**Commit:** 

In rct vanilla we could use the track colour variations to change certain things with the 8cars trainer, like making merges and such, but in later versions we could also change the designated track variation to become a lift, this tool was called "toggle chain" and enabled us to make vertical and steep lifts on every coaster type, made it so we could make realistic launches on track types that didn't support the chain lift option in the building menu or could use any type of track to make a powered coaster. it'd be really cool to maybe add this feature to the ride menu in Openrct where we can adjust certain things like the toggle chain to track colour variations.
Maybe it'd also be a good addition to add a "toggle brakes" option so we could make slanted brake runs lik a lot coasters tend to have.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. recolour any part of a coaster with a secondary colour sheme in the ride menu
2. going into ride menu with 8cars 1.32
3. select the used colour variation and select toggle chain
4. click apply and cancel in 8cars, this resulted in making the coloured part a chain lift making vertical lifts and diagonal steep lifts possible

**Dump file**
If you have a dump file, zip it and drag&drop it here.

**Screenshots / Video:**
Drag / drop screenshots here. Use https://vid.me to upload video.

**Save game:**
Change the file extension to .txt or package to a .zip so that it can be drag / dropped here...

**Comment by janisozaur** [comment]
Please format properly – remove the irrelevant parts, which make this harder to read than it should be.

**Comment by brettpenzer123** [comment]
If you are requesting a feature that would like to be added there is no need to use the current format given when starting a new post. Just delete it all and start fresh.

**Comment by Gymnasiast** [comment]
This is very verbose for 'a feature that allows toggling chain on any part'. _How_ 8 cars per trainer does it is not very important, it's about _what_ you want to do.

By the way, 'toggle brakes' is impossible. Some hacked parks do have them, but employ some very advanced hacking (namely having one of the vehicles run on an invisible track that has brakes at the correct time) to do so. It will have to wait until we can add pieces.

**Comment by Liampie** [comment]
"to make vertical and steep lifts on every coaster type, made it so we could make realistic launches on track types that didn't support the chain lift option in the building menu or could use any type of track to make a powered coaster."

**Comment by X123M3-256** [comment]
@Gymnasiast You can technically do a shoestring hack in OpenRCT2 already, but it's awkward enough that I avoid doing it - you can't spawn a train split across multiple tracks, so you have to spawn one and then maneuver it over a system of switch tracks to split it apart.

@Liampie, if you want to make any ride powered, it might be better to target the vehicle structures than to set everything as chain lift (though the latter will still work fine). I haven't confirmed that this is definitely possible, but if it is then it would allow direct control over the acceleration, which the chain lift doesn't. (I think editing vehicle structures in general would be a useful feature, as it's something I do quite frequently now).

**Comment by Gymnasiast** [comment]
Implemented by #3818.
