### ISSUE TITLE
An option to enable/disable your error reporting dumps

### ISSUE THREAD

**Issue by ItsMikey420** [OpenRCT2/OpenRCT2#3535]
I'll keep this short and sweet.

I would like to see an option to enable/disable the error dumps that are created on a crash.

I run a couple of 24/7 servers for OpenRCT2 and have been having trouble recently with my server manager not being able to start the game back up when the game has crashed with an error dump.

Implementing this sooner rather than later would be great :)

On a side note as well, The OpenRCT2 file in my docs has become soo messy with all the error dumps. Maybe make an error file for the dumps to be put into to keep the file a bit cleaner??

**Comment by brettpenzer123** [comment]
This would be a nice option but whilst OpenRCT2 is still in development. I'd prefer it to stay without a toggle. If you cannot bare your folders filling up with dumps there are two simple methods. 

- make a .bat file in notepad and run it from your desktop to get rid of the files. Use /S before *.type to delete files in subfolders. Do not run from directory!

```c++
cd C:\Users\*User Name*\Documents\OpenRCT2 or your servers file path
del *.dmp
del *.sv6
```

- Use task scheduler to run on a loop whenever you prefer to automatically run script .bat file above.

**Comment by brettpenzer123** [comment]
If you would like to report the bug that is stopping you from starting the game up when it has crashed. Please fill out the information in the box that appears when you first click new issue and include any dump files that you have so we can look into the issue.

**Comment by ItsMikey420** [comment]
See this is a big problem i've been facing as a server owner (not just someone who hosts a rct2 game on his own pc for a couple of hours on the weekend, but hosts 4 different 24/7 OpenRCT2 servers among 2 VPS's) Every time i suggest a feature for the game I get instantly shot down by the "devs" I say that because i checked out your contributions brett and you only have 2 so far, You say "I'd prefer it to stay without a toggle" then please elaborate why so?

the idea for cleaning the Openrct2 my docs file with a .bat is just stupid stupid stupid. The best way to go about this is to simply have the dumps saved into Openrct2/Errors 
Need i say more?

its not a bug that's stopping my server manager from starting the game back up, its the fact that on crash it opens up the openrct2 my docs file and selects the dumps also has an error box popup saying the game has crashed with the options of abort, retry or cancel. I have everything automated on my VPS's to keep OpenRCT2 running, changing maps on time and handling autosaves on crashes so honestly I have 100% no need for the crash reporting at all.

~$50 is spent a month keeping our 2 VPS's and website up and running 24/7. I hate to be that guy but I honestly feel the devs should really be listening to people like myself that are investing their own time and money to keep the servers online for users to play on.

**Comment by Epxs** [comment]
I agree with Mikey in the sense that the problem is not just the fact that crash dumps exist, but the error messages and explorer process that gets opened is just not server friendly - or even user friendly. I don't need to be told every time it crashes how to report a bug, and because crashes are quite frequent with custom maps and objects it gets old quickly.

A toggle/user option would be a simple implementation. While cleaning up the dumps with a batch file is simple (or just make the folder read only) it does not fix the issue around the error message box and opening explorer processes. A launch argument like -NoDump or something to make the process close cleanly on crash would be optimal as the game can restart and autoload it's last save without a hitch. 

We understand it's crashed, we understand where the crashed dumps are located, don't force open those directories. The crashes are simple issues with some maps or index's out of range. Nothing worth reporting.

Brett, your cleanup is not a solution for us or even the main problem here.

We are at the point of compiling the latest with google breakpad disabled (if possible).

This is just feedback, use it as you wish.

**Comment by janisozaur** [comment]
We'll consider your feedback.

I have to ask though: why would you be running this on a Windows server? That's "~$50 a month" not well spent.

**Comment by Gymnasiast** [comment]
@ItsMikey420 Please do remember that brettpenzer123 is not a team member. His opinion is his own, not ours.

**Comment by IntelOrca** [comment]
Weren't we going to disable the message box and folder select when its in headless mode?

**Comment by PFCKrutonium** [comment]
I mean that would only make sense either way @IntelOrca

**Comment by Epxs** [comment]
@janisozaur @ItsMikey420  and myself enjoy the game but have had limited success with compiling on Ubuntu 15 and less success with automation of it(a few easy to sort issues getting it to compile, then kernel panics so we gave up on ubuntu ORCT2 for now). Don't take "$50 a month" too seriously as we use the hosts for other purposes too, ORCT2 is just what we are passionate about currently. This is a hobby. It's just personal preference. :)

We can interface a little better with the game when it is not in headless mode (Can't promote an admin in headless and sending chat alerts as to an upcoming restart etc is difficult/impossible), but we have been running both with success, just removed some of our own functionality. We are keen to see the centralized user accounts implemented as this will solve some of the issues we are trying to tackle.

We don't want to be demanding, this would just help us continue running a public server unattended and handle simple things like crashes, map rotation, auto loading last save on crash. I understand you don't entirely support this, thus it is just feedback. 

@janisozaur , @Gymnasiast ,@IntelOrca Thanks for maintaining such a great project, we all want to see it gain popularity as it really did resurrect such an old single player game.

**Comment by ItsMikey420** [comment]
Thanks for adding that fix! @janisozaur :D I have just made the changes to our server managers with the --silent-breakpad cmd and will test it out overnight on headless and non-headless. Doing this has cleared up A lot of problems we have been having with trying to keep our servers online so Thank you very much for helping to solve this problem right away.

**Comment by ItsMikey420** [comment]
Tested things out overnight with no error dumps being recorded so the silent breakpad command has fixed my problem! I will now close this issue. Thanks guys.
