### ISSUE TITLE
impossible to record certain park with screen capture software

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#3536]
**Windows 8.1** 
**Version: 0.0.5** 
**Commit: 9b5d706** 

Using: Bandicam, H264 - CPU, Full Size, 30.00fps, 100q, no audio. OpenRCT2 set to 1.00 scale with Hardware Rendering, Uncap FPS.

The TaCW.sv6 park is impossible to record at 1.00 scale. It simply records no pixels. So far it is limited to this park.

**Steps to reproduce:**
1. Record while TaCW.sv6 is on the screen (just wait for the snow park in the title sequence)
2. Verify that zero seconds of footage are captured

**Comment by janisozaur** [comment]
Isn't it the recording program's issue?

**Comment by pizza2004** [comment]
@janisozaur Not when we have a perfectly good Bug Tracker for everyone to dump even the smallest problem onto! :D

Don't worry I'm just kidding I'm not trying to say this shouldn't be here.

**Comment by Gymnasiast** [comment]
I think this is a Bandicam bug, not an OpenRCT2 one.

**Comment by spacek531** [comment]
Can anyone provide evidence that it isn't a general screen capture bug and limited only to bandicam?

**Comment by YJSoft** [comment]
Tested some capture software I know.
- Fraps : works fine
- oCam : works fine with H264 but warning is constantly printed at console while `TaCW.sv6`
- Bandicam : only works fine with H264 + quality 80 and warning printed just like oCam

**Comment by IntelOrca** [comment]
I can't see how we are doing anything wrong. Is it just not coping with the white colours or something?

**Comment by janisozaur** [comment]
In the original report there was a message coming from said program about `bitstream size is larger than Level limitation`. For this reason I think it's a spike in quality the encoder cannot handle, @YJSoft's investigation seems to point at the same thing.

**Comment by IntelOrca** [comment]
Seems strange, surely it should just insert a new keyframe if the whole scene changes... and if its a warning what does that mean? Does it still record the video?

**Comment by janisozaur** [comment]
@spacek531 minor thing, but do note: it is not "hardware *rednering*" but "hardware *display*".

**Comment by janisozaur** [comment]
Closing on assumption it is a problem with recording software, not us, see https://github.com/OpenRCT2/OpenRCT2/issues/3536#issuecomment-217815578.
