### ISSUE TITLE
A way to more easily see min/max cars per train

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#3537]
Written in the forums by Superjustinbros [(link)](https://openrct2.org/forums/topic/1245-show-limits-for-of-cars-per-train/)

>Before I begin, i should mention that this is very minor, so if it comes off more as a nitpick, I apologize.

>Before the update that added in the cheat that enabled the use of up to 255 cars on a train, I originally liked how you could easily tell the maximum limit of cars for the current ride without directly closing the ride and changing the number thanks to the drop down window system instead of the value-changing buttons.

>So I was thinking of a way you could show the limit or perhaps use drop downs when the cheat is off and value-changers is on?

Never thought off it but he's right, the drop down disappeared when we merged the '255 cars on a train', maybe add the drop down when the cheat is off?

![buttons](https://cloud.githubusercontent.com/assets/17282384/15103192/b2a0c014-15a8-11e6-8eee-66228523fbea.png)

**Comment by Gymnasiast** [comment]
A tooltip would do.

**Comment by Broxzier** [comment]
> My original idea for this was showing the default max number of trains/cars as a fraction alongside the current limit, so for example the image Nubble posted in GitHub would show each selection as 2/2 Trains and 6/6 Cars per Train. Going over the limit in the case of cars would only increase the first number while the second number remains at 6., while the Trains window drops in both numbers to show 1/1 once a certain number of cars have been passed.

So in short: Displaying it as "2/2 trains" and "6/7 cars per train" instead".

**Comment by Gymnasiast** [comment]
I don't find that terribly readable, to be honest.

**Comment by jensj12** [comment]
Solved by #4375, can be closed now.

**Comment by Nubbie** [comment]
Did that PR fix this issue? Can't test it out right now, someone else has to close it xc
