### ISSUE TITLE
Raise/lower support for the tile inspector

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#3539]
As the title says. This enables things like lowering the entrance or exit, or raising/lowering coaster pieces to height not normally possible.

**Comment by janisozaur** [comment]
I hear there's a lot of demand for such a feature, but the description is somewhat limited in suggesting a per-tile solution. I think a more general option would be welcome, it may call for some refactoring in tile inspector.

Possible options would include:
* Simple bulk operations: select an area (square/rectangular/tile-by-tile)
* As above, but with some filters: select an area, apply "only ride X"

With an option of above selected, apply whatever transformations you need.

**Comment by IntelOrca** [comment]
It looks like we will need to implement a multi select area. But with a multiple selection you are going to be more limited in what you can do. Each tile will have different elements on it, so you certainly can't make a change to individual elements, like making something in particular invisible for a whole area.

**Comment by spacek531** [comment]
A possible solution is to click each part instead of by-tile.
