### ISSUE TITLE
Idea: Option to change max station length between 12 and 32

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3547]
While probably not worth implementing, this was mostly something I felt like requesting incase there was someone that doesn't see much of a point in increasing the station limit since one of the more recent updates.

What this would do is make it so the user cannot build past a certain of number of station platform segments. This wouldn't prevent others in multiplayer who have the limit higher from being able to build their station platforms longer.

**Comment by Gymnasiast** [comment]
12 was an arbitrary limit that didn't serve much purpose. While not everyone may see the point, it shouldn't cause problems either. Because of this, I think it doesn't warrant an option.

**Comment by IntelOrca** [comment]
@Superjustinbros please don't suggest features just because someone may *theoretically* want it, we already have too many feature requests.

**Comment by Superjustinbros** [comment]
Alright.

**Comment by Patrik356b** [comment]
I would like to see this raised to 16. It would help when you want long dueling trains and the current limit is just below the desired limit. Increasing it further I see little point in doing.

**Comment by Gymnasiast** [comment]
@Patrik356b It has already been raised to 32.

**Comment by Superjustinbros** [comment]
Maybe it could help if in the construction window there was a counter telling you how many station platform blocks you currently have laid down for the highlighted station.

**Comment by Gymnasiast** [comment]
Frankly, I don't see the point in that, really. Classic RCT expects a bit of planning and thinking from the user.

**Comment by IntelOrca** [comment]
@Superjustinbros I think you are being theoretical again. Let's wait for someone to actually request that.

**Comment by Superjustinbros** [comment]
Okay.
I brought that up since not everyone is going to count how many squares a station takes, but if you say so.

**Comment by Patrik356b** [comment]
I agree with @Intelorca 

I didn't know the limit was increased as I haven't tried long stations yet in OpenRCT2 and never saw the limit mentioned before replying to this issue. 

Also: it annoys me that I can not edit my posts on mobile for whatever reason.
