### ISSUE TITLE
Mountain tool generates out-of-range errors

### ISSUE THREAD

**Issue by jensj12** [OpenRCT2/OpenRCT2#3549]
**OS:** win10
**Version:** 0.0.5 develop
**Commit:** 8d0481d

When hovering near the edge of the map with the mountain tool, the framerate drops and the command prompt window gets filled with errors (src\world\map.c:177 (map_get_first_element_at)) and warnings (src\world\map.c:2254 (smooth_land_tile)). Though I can live with the warnings, the framerate drop (4-5 fps) makes it nearly unplayable.

**Steps to reproduce:**
1. Open the land tool and enable the mountain tool
2. Hover the mouse near the edge of the map (only 2 sides give this error)

![image](https://cloud.githubusercontent.com/assets/13868449/15119209/1c418294-1610-11e6-80d1-ae26c43bf7d7.png)

**Comment by IntelOrca** [comment]
@janisozaur probably something you need to check.

**Comment by Broxzier** [comment]
```
WARNING[src\world\map.c:2259 (smooth_land_tile)]: Invalid coordinates for land smoothing, x = 8192, y = 1568
ERROR[src\world\map.c:184 (map_get_first_element_at)]: Trying to access element outside of range
```
It's triggered when the X or Y coordinate is > 127.
