### ISSUE TITLE
Crash: Assertion 'q->front' failed at pulsecore/queue.c:81, function pa_queue_push()

### ISSUE THREAD

**Issue by Mte90** [OpenRCT2/OpenRCT2#3553]
**OS**:_Debian Sid_
**Version**:_0.0.5.0-develop_ 
**Commit**:_8d0481d_ 
I use the multimedia button on my keyboard on linux that launch custom commands like change songs on VLC etc (use dbus).
When i press that key i get a crash of the game, in console i get:
`
Assertion 'q->front' failed at pulsecore/queue.c:81, function pa_queue_push(). Aborting.
`

**Steps to reproduce:**
1. Press the multimedia key

I don't know if it is possible to reproduce that problem but I get this error with different builds of the last days.

I cannot compile that game on my machine because I am on amd64 and when i try to install the library required remove some programs that i need.

**Comment by janisozaur** [comment]
I tried replicating your issue, but cannot.

If you used package from our PPA, they should be built with debug information available, so if you could install that, run openrct2 again until it crashes and dump it's core when this assertion gets hit.

You should be able to make your system dump core with `ulimit -c unlimited`.

**Comment by Gymnasiast** [comment]
If you look where that assertion happens, I think it's likely to be caused by Debian Sid being bleeding edge and thus shipping unstable versions of software.

**Comment by janisozaur** [comment]
pulseaudio seems to be at `8.0-2+b2` for amd64, 8.0 is current; sdl2 is at 2.0.4. This particular bug seems to have some references from over year ago.

Since we don't interact with PA directly, I'm assuming this is a bug in either PA or SDL2, they should not crash your program even on invalid input.

**Comment by Mte90** [comment]
I am not using the ppa version, I've tried again also with the other buttons and with the VLC command directly and this it is not happening anymore.
But before to write that ticket it is happened 4 times :-/

**Comment by janisozaur** [comment]
Do you get your builds from openrct2.org then? They have debug information embedded in them, so the steps I outlined should still apply, but you already have the debugging symbols.

There is nothing we can really do without that dump file.

**Comment by Mte90** [comment]
I am using the build from openrtc2.org, i try to get a crash again and with the command specified above i will try to get a dump :-)

**Comment by janisozaur** [comment]
I assume this was one-off, in external code, perhaps fixed upstream by now (there was PA 9.0 release in the meantime: https://www.freedesktop.org/wiki/Software/PulseAudio/)
