### ISSUE TITLE
Provide a notification when "disable clearance checks" is in effect

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#3555]
When building in a game, provide a (visual?) notification for players when "disable clearance checks" is in effect.

Especially useful for multiplayer, when only host can toggle this setting, as this can make unaware clients build unintended things.

**Comment by Ziscor** [comment]
This is especially important if someone was using the scenery cluster tool.

**Comment by jensj12** [comment]
A (more) visible notification for both 'disable clearance checks' and the cluster tool would be very welcome.

**Comment by Gymnasiast** [comment]
The current plan is to go with #3641 and make this local.

**Comment by janisozaur** [comment]
The two are not mutually exclusive, though and we've had reports of people doing something wrong because they forgot the had disable clearance checks turned on or off.

@Gymnasiast is that justification good enough to reopen?

**Comment by Gymnasiast** [comment]
Added by https://github.com/OpenRCT2/OpenRCT2/pull/11806.
