### ISSUE TITLE
Cannot build reversing section in wooden reverser coaster

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#3556]
**OS: 8.1** 
**Version: 0.5** 
**Commit: aa929e1** 

The Reverser (left) and Reverser (right) track pieces no longer show up in the special pieces list, despite being able to build prebuilt coasters with the track piece.

**Steps to reproduce:**
1. Build a Wooden Reverser Coaster
2. Try to build a Reverser piece

**Comment by fromthere** [comment]
problem is caused by aa929e1593e7a2adcc0c5886c2693c3e2ec407fa
@IntelOrca

**Comment by IntelOrca** [comment]
I was expecting some bugs to come from this, I will investigate later unless knows whats wrong.
