### ISSUE TITLE
Keyboard shortcut to close all windows

### ISSUE THREAD

**Issue by wousser** [OpenRCT2/OpenRCT2#3557]
Feature: Add a keyboard shortcut to close all open windows. Sometimes when adding a lot of staff, or having multiple windows open, it is troublesome to close them one by one. Adding a keyboard shortcut to close all windows saves time.

OpenTTD uses 'delete' as the keyboard shortcut to close all open windows.

**Comment by YJSoft** [comment]
![image](https://cloud.githubusercontent.com/assets/5893514/15133556/d51cabac-169e-11e6-9798-85daa04ed49d.png)
It's `Shift+Backspace`. look Options-Controls(gear icon)-Shortcut keys.
