### ISSUE TITLE
Loading saved game crashes

### ISSUE THREAD

**Issue by zsilencer** [OpenRCT2/OpenRCT2#3558]
**OS:** Windows
**Version:** develop
**Commit:** 8efdf4e9600f7412aa66f0d99bdd6f8102c71844

Explanation of the issue...
Game crashes when loading this save with new SV6 importer

**Save game:**
[Sherwood Forest.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/256805/Sherwood.Forest.sv6.txt)

**Comment by janisozaur** [comment]
There are more `map_elements` in it than `S6Importer` is prepared to handle.

https://github.com/OpenRCT2/OpenRCT2/pull/3528/files#diff-d14bd20aa930ec11ff33c54b8bf95883L774

https://github.com/OpenRCT2/OpenRCT2/blob/8efdf4e/src/world/map.h#L224

https://github.com/OpenRCT2/OpenRCT2/blob/8efdf4e/src/rct2/S6Importer.cpp#L132

https://github.com/OpenRCT2/OpenRCT2/blob/8efdf4e/src/scenario.h#L136

**Comment by janisozaur** [comment]
See #3559
