### ISSUE TITLE
Tunnels drawn incorrectly

### ISSUE THREAD

**Issue by jensj12** [OpenRCT2/OpenRCT2#3561]
**OS:** win10
**Version:** 0.0.5 develop
**Commit:** 8efdf4e

Tunnels should be raised 1 unit if the track entering it is not flat (if possible), allowing the track to be drawn inside the tunnel. This currently does not happen.
How it should be (screenshot from 15th april):
![scr87](https://cloud.githubusercontent.com/assets/13868449/15150787/ed9ffffa-16ce-11e6-88f7-507915571904.png)
What it looks like now:
![scr106](https://cloud.githubusercontent.com/assets/13868449/15150796/fa0365f2-16ce-11e6-8013-5b77c2772d7e.png)
Look at the tunnels on the right and top-left.

**Comment by Christipher** [comment]
I think code wise this dates to a bug in the original game...

**Comment by marijnvdwerf** [comment]
@Christipher Nope. I made a mistake in #3358 while decompiling the land edges (vertical parts), but I was really having trouble understanding the code, and I still can't see what I did wrong.

**Comment by duncanspumpkin** [comment]
I can't work out what track piece has been used in the image so i can't tell if this bug still happens.

**Comment by jensj12** [comment]
Anything that is not flat or vertical should be able reproduce this bug.

**Comment by IntelOrca** [comment]
@jensj12 can you upload the saved game for the above picture?

**Comment by duncanspumpkin** [comment]
@IntelOrca I was able to reproduce this just using a basic wooden coaster. The tunnels are still being drawn incorrectly.

**Comment by DonCuan** [comment]
![tunnels](https://cloud.githubusercontent.com/assets/2139850/19514414/b1e51a8c-95f3-11e6-9682-b966688f90d2.png)

Another side-by-side screenshot illustrating the issue. Left: RCT2, right: 96b796a
