### ISSUE TITLE
Available scenery mixed up when starting a new game

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#3562]
**OS:** Windows 10
**Version:** 0.0.5
**Commit:** 8efdf4e

1. Start a new game on crazy castle
2. Open the scenery window

Notice how there are objects in there that normally shouldn’t be available until later on? 

**Screenshots / Video:**
![screen shot 05-10-16 at 06 33 pm](https://cloud.githubusercontent.com/assets/1381723/15156298/396a47a6-16de-11e6-9f6b-09ae4cc39e0d.PNG)
![screen shot 05-10-16 at 06 01 pm](https://cloud.githubusercontent.com/assets/1381723/15156299/396a5340-16de-11e6-9472-3518ef1beb64.PNG)

**Comment by Gymnasiast** [comment]
Note the duplicated tabs.
