### ISSUE TITLE
Cars on diagonals with downward launch

### ISSUE THREAD

**Issue by RCTDaCool** [OpenRCT2/OpenRCT2#3566]
**OS:** Windows 8.1 
**Version:** v0.0.5-develop build 8efdf4e
**Commit:** 

Explanation of the issue...

When a coaster set in downward launch mode ends on a diagonal the cars will not face diagonally. 

- [ ] Reproducible in RCT2 (vanilla)?
In vanilla the cars will face diagonally.

**Steps to reproduce:**
1. Build a station and backwards out of it a 45° turn and some diagonal track
2. set the operating mode to downward launch and open and close the ride

**Screenshots 
![test](https://cloud.githubusercontent.com/assets/19309747/15187274/c8522c00-17a0-11e6-8280-48c9ab2de503.PNG)

**Comment by zsilencer** [comment]
I am unable to reproduce this by following your instructions.  Do you have a save game with this type of coaster.

**Comment by jensj12** [comment]
I did manage to reproduce it, don't forget to enable 'show all operating modes'. The trains are 'Waiting for passengers at station' with the restraints open, which doesn't have a diagonal sprite. As soon as they are closed the trains return to normal.

**Comment by zsilencer** [comment]
Still have no idea what you are talking about on how to get this to happen.

**Comment by zsilencer** [comment]
OK I finally got it, had to use a different type of coaster.
It looks like this is a really old bug, I tried a version of openrct2 from over a year ago and it still happens.

**Comment by IntelOrca** [comment]
If it happens on 0.0.2 it can't even be to do with vehicle-update.

**Comment by coltongit** [comment]
It could be possible to fix by making a new sprite for this particular purpose.

**Comment by jensj12** [comment]
There are no diagonal stations so there's very little use for that. Just using the normal sprite (with closed restraints) would work well in this case, and is consistent with opened restraints in turns (which show up as closed and with the train at the proper angle). You can check the latter by using a turn at the start instead of diagonal track (and now I think of it, a train longer than the station might also cause this visual bug).

**Comment by zsilencer** [comment]
When I open up the save game in the original, it appears normal, so something is different from very early in openrct2.

**Comment by duncanspumpkin** [comment]
It is possible that this could be a difference between the cd version and the gig/steam version

**Comment by zsilencer** [comment]
Yes you are right I just tried the cd version and it has the same bug
