### ISSUE TITLE
Scenario translation is not loaded at all

### ISSUE THREAD

**Issue by YJSoft** [OpenRCT2/OpenRCT2#3572]
**OS: Windows 10** 
**Version: 0.0.5** 
**Commit: 7c7dea8f00d44bfad56d594dd843d338da7bbc02** 

Korean translations is not loaded at all. it just shows broken EUC-KR Strings instead. deleting plugins.dat not solves problem.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Screenshots / Video:**
![image](https://cloud.githubusercontent.com/assets/5893514/15209923/c6620522-186e-11e6-9e73-1fede1c3e7d9.png)

**Comment by Gymnasiast** [comment]
Could it be related to #2611?

**Comment by YJSoft** [comment]
@Gymnasiast Nope. that's not related since this is original scenario.

**Comment by YJSoft** [comment]
language file and language loading is okay since there's no problem loading translation at new game window.
<img width="720" alt="2016-05-13 9 14 22" src="https://cloud.githubusercontent.com/assets/5893514/15247520/be04ac4a-194f-11e6-9372-98ecfc61dead.png">

**Comment by YJSoft** [comment]
If I change
```cpp
void S6Importer::LoadScenario(SDL_RWops *rw)
{
    sawyercoding_read_chunk_safe(rw, &_s6.header, sizeof(_s6.header));
    if (_s6.header.type != S6_TYPE_SCENARIO)
    {
        throw Exception("Data is not a scenario.");
    }

    sawyercoding_read_chunk_safe(rw, _s6.info, sizeof(_s6.info));
```

to
```cpp
void S6Importer::LoadScenario(SDL_RWops *rw)
{
    sawyercoding_read_chunk_safe(rw, &_s6.header, sizeof(_s6.header));
    if (_s6.header.type != S6_TYPE_SCENARIO)
    {
        throw Exception("Data is not a scenario.");
    }

    sawyercoding_read_chunk_safe(rw, _s6.info, sizeof(_s6.info));
    memcpy(s6Info,&_s6.info, sizeof(_s6.info));
```

and translation works. Since infomation is only saved to _s6.info(and currently `_s6.info` is only used at save) all other s6Info access with `0x0141F570` would fail due to empty value.

Before S6Importer.cpp it was saved to `0x0141F570` direct.

**Comment by IntelOrca** [comment]
@YJSoft thanks, your change is probably close enough to the fix, it just needs to be in the import function along with all the other data transfer from s6 to global variables.
