### ISSUE TITLE
Construction Redirection Bug

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3575]
I'm sure everyone's experienced this at some point while playing multiplayer, and I haven't noticed anyone mention this yet on GitHub (if I'm wrong feel free to correct me).

What happens is if you're just minding your own business and another player happens to start or resume constructing a ride, your game window suddenly flies over to the ride they're constructing with no warning.

**Comment by IntelOrca** [comment]
It happens when a player tries to open a ride and fails. When it fails it sets everyone's location to the disconnected track or the station with the missing ride exit / entrance etc. It requires a callback like construct new ride.

**Comment by Superjustinbros** [comment]
Thanks for the info. The error has been happening on my end since I started playing multiplayer last March.
