### ISSUE TITLE
CP1252 to UTF8 bug on highscore file

### ISSUE THREAD

**Issue by An-dz** [OpenRCT2/OpenRCT2#3587]
**OS: Windows 8.1 x64** 
**Version: 0.0.5** 
**Commit: feb140b** 

If you had already played the original game and had special characters in the name field for the highscore, when playing ORCT2 those are not converted to UTF8 and show weird characters instead.

The imported highscore is not changed and ORCT2 ends up reading it as UTF8 and so reads wrong characters. Subsequent highscores saved with ORCT2 are saved as UTF8.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Play the original game and win a scenario
2. When adding your name to the highscore add some special characters like á, ó, è
3. Install ORCT2 and run the game
4. Notice that the special characters are gone leaving artifacts in the string.

**Comment by Gymnasiast** [comment]
Special characters like á, ó and è are not in ASCII. RCT2 used CP1252 for them. Corrected title to reflect that.
