### ISSUE TITLE
1920's Racing Cars get stuck on turns

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3588]
While I was in the three hour Br3ak server, in one scenario that had 1920's Racing Cars, someone built a track and started it up, only to see the drivers get stuck on turns.
![scr1](https://cloud.githubusercontent.com/assets/4167951/15256116/f48cad90-190d-11e6-9aca-0970f8dc0714.png)
[stuck cars.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/263762/stuck.cars.sv6.zip)

**Comment by Gymnasiast** [comment]
I have encountered this bug in vanilla as well.

**Comment by Superjustinbros** [comment]
So what could be done to fix this? It mostly occurs when a vehicle tries to make an outside turn and another vehicle comes into the turn on the inside.

**Comment by Stevoisiak** [comment]
I've had this happen to me before as well.

Can the issue reliably be reproduced? For instance, if you closed and reopened the ride, would the cars get stuck in the same location?

**Comment by Superjustinbros** [comment]
Build a 1920's Racing Cars track, be sure to include a good number of vehicles and turns, and after enough time has passed, one of the cars will get stuck.

**Comment by ZeeMajora** [comment]
As of 0.4.0 this should be fixed for newly spawned 1920s racing cars as in our objects repo their vehicle size was reduced to a value that should no longer get stuck.

**Comment by Gymnasiast** [comment]
Quite right, closing this issue. I added it to the changelog as well.
