### ISSUE TITLE
Thousands suddenly appear and then they all disappear

### ISSUE THREAD

**Issue by kalamarioctopy** [OpenRCT2/OpenRCT2#3590]
Sometimes in the multiplayer, there appear suddenly thousands of people. They don't come in through the entrance, but they just appear. Sometimes they leave and sometimes everybody in the park disappears. It happens at random times.

**Comment by janisozaur** [comment]
Do you observe this as a host or as a client?

**Comment by IntelOrca** [comment]
The host is probably using cheats.

**Comment by kalamarioctopy** [comment]
I play it with a friend and it didn't matter if I was the host or if he was, it happened every time.

**Comment by IntelOrca** [comment]
@kalamarioctopy was your friend the only other player? Was your friend using cheats?
