### ISSUE TITLE
Park names from RCT1 no longer translated in game

### ISSUE THREAD

**Issue by rvgr** [OpenRCT2/OpenRCT2#3595]
**OS:** MacOS X
**Version:** 0.0.5
**Commit:** f62932a

Scenarios recreations from RCT1 no longer use STR_PARK from localisation file to translate the park name in a scenario.

In the scenario selection menu, park names are translated correctly using STR_SCNR.

**Screenshots / Video:**
From an old save (park name wasn't changed after the park was created):
![capture d ecran 2016-05-14 a 12 27 00](https://cloud.githubusercontent.com/assets/18069013/15267938/f6414e6c-19cf-11e6-97ae-ae59125a6de3.png)

Current build:
![capture d ecran 2016-05-14 a 12 27 26](https://cloud.githubusercontent.com/assets/18069013/15267939/fea7cf2c-19cf-11e6-9227-574be04dc88c.png)

**Comment by YJSoft** [comment]
Duplicate #3572
