### ISSUE TITLE
Saving parks with a dot in their name using the system dialogue not working

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#3596]
**OS:** Windows
**Version:** 0.0.5-develop
**Commit:** f62932a

When saving a park with a dot in the filename using the system dialog, the file lacks the `.sv6` extension.

**Steps to reproduce:**
1. Open any park and choose Save As...
2. Open system dialog
3. Choose any name with a dot in (e.g. `Leafy.Lake`) it and click save

Note: Adding `.sv6` manually is a workaround to get them to show up in the list.

**Comment by IntelOrca** [comment]
Can't reproduce.

**Comment by Broxzier** [comment]
Just did some more testing, apparently having a dot in the name causes the issue. I also noticed that the files are being created, they just lack the `.sv6` extension.

**Comment by IntelOrca** [comment]
Hmm, it always appends .sv6 for me when its not typed in the file dialog.

**Comment by Broxzier** [comment]
Even when there's a dot in the name?

**Comment by IntelOrca** [comment]
Oh I didn't realise that's what you mean. Yes if use a dot then it treats it as if you are forcing a different extension.
