### ISSUE TITLE
Crash in paint.c when a ride crashes

### ISSUE THREAD

**Issue by Harbinger619** [OpenRCT2/OpenRCT2#3601]
**OS:** Windows 10 64-bit
**Version:** v.0.0.5-develop
**Commit:** build 498e4b6

Explanation of the issue...
The crash effects produced when a ride crashes sometimes trigger a crash in Paint.c, see attached screenshot.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Cause a ride to crash. This can be easily accomplished by rotating a track segment via the tile inspector.
2. If the first crashed train/car does not trigger the error, wait for the second train/car. In my testing, it always crashed after the first or second train/car crash.

**Dump file**
I don't currently have a dump file for this issue. When I figure out how to create one, I'll upload it here.

**Screenshots / Video:**

![crash](https://cloud.githubusercontent.com/assets/10247767/15270866/04bbbe66-19ec-11e6-91b9-b1f0e94d37a2.png)

**Comment by janisozaur** [comment]
This is a crash on `assert()`, it will not generate a dump file. We put such checks in code to make sure everything is valid, otherwise you could end up with random garbage.

**Comment by zsilencer** [comment]
Not sure why he put assert((uint16) z_offset == (sint16) z_offset); it's obvious z_offset is signed so it should just be changed.

**Comment by duncanspumpkin** [comment]
Yes that check was in whilst we were working out the sign of the variables, can someone pr with those asserts in paint.c removed and check the function is using sint16 for the variable. I'm on holiday at the mo so can't make the change.
