### ISSUE TITLE
[Suggestion] Adding config.ini fallback mechanism

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#3607]
Would it be better that OpenRCT2 implement a fallback mechanism, which use the default setting if the config.ini is unreadable or corrupted, similar to the utf8 font fallback mechanism, to reduce game crashes? 

The reason I suggesting this is that I experienced a config.ini corruption few days ago by just opening different version of OpenRCT2, the game just crash itself immediately, it is quite annoying and I think that it should be better method to handle config (rather than crash when corrupted?)

**Comment by IntelOrca** [comment]
This already happens.

**Comment by Gymnasiast** [comment]
Still, we have had a bug not long ago when an incorrect language code would cause a crash. Even if there is currently a fallback system, it doesn't seem to always work properly.

**Comment by daihakken** [comment]
@intelorca Sorry I didn't know that, but the game still crashes when config.ini is incorrect or corrupted.

**Comment by IntelOrca** [comment]
Please upload the corrupted config

**Comment by daihakken** [comment]
[config.txt](https://github.com/OpenRCT2/OpenRCT2/files/264931/config.txt)
Seems that the game can correctly fallback to default setting now (which cannot few days ago), I think this can be closed (?)
