### ISSUE TITLE
Dinghy slide track is reversed

### ISSUE THREAD

**Issue by Nubebuster** [OpenRCT2/OpenRCT2#3618]
**OS:** Windows 10 upgraded from Windows 7
**Version:** 0.0.5.0
**Commit:** a3469cf

Explanation of the issue...
The chain lift in dinghy slide in multiplayer is reversed. The animation goes the wrong direction and the atraction can't start.
- [ ] Multiplayer?

**Steps to reproduce:**
1. Make a dinghy slide yourself in multiplayer
2. Create a chain track
You can see from the animation the track piece is reversed

**Screenshots / Video:**
Gif:
https://gyazo.com/8bf95da49b722187bfbcc49c62718216.gif

**Comment by Gymnasiast** [comment]
I can't reproduce this. It goes the correct way on my system.
It's probably caused or affected by refresh rates and FPS.

**Comment by X123M3-256** [comment]
When you say the ride won't start, does it fail with "Track is not a complete circuit"? That's what I'd expect to see if the track piece actually is reversed. Otherwise, what @Gymnasiast said.

**Comment by Broxzier** [comment]
Even in vanilla RCT2 you can see the animation as it going up and down, it's a matter of how you look at it. If that's what you mean, then I don't think this is really an issue, but mention it also does not start?

**Comment by Nubebuster** [comment]
Oh then it's not specifically the animation. But when I placed the built-in dinghy slide in singleplayer and then ran the map in multiplayer, the attraction didn't start. I don't know why it didn't start.

I was running the game at the normal 40fps so I must say the animation is broken anyway

**Comment by Patrik356b** [comment]
You probably mean 30 or 60 fps. 40 is a strange value

**Comment by Nubebuster** [comment]
40fps is what is default in the options

**Comment by janisozaur** [comment]
@Patrik356b game runs (or tries to run, if resources are scarce) at 40fps by default.
