### ISSUE TITLE
Bobsled coaster doesn't animate on turns correctly

### ISSUE THREAD

**Issue by mattgwise** [OpenRCT2/OpenRCT2#3619]
OS: Windows 10
Version: v0.0.5 build a3469cf

Explanation of the issue...
When building this coaster type, the trains do not bank the track, they simply remain flat as they go round corners. Same happens with dinghy slide.

**Comment by Wirlie** [comment]
The same problem happens with the Wooden Mine Coaster and the Wooden Wild Mouse Coaster (#3318, this seem to happen again in recent builds).
