### ISSUE TITLE
Default original track design for River Rafts is empty and crashes game

### ISSUE THREAD

**Issue by An-dz** [OpenRCT2/OpenRCT2#3623]
**OS: Windows 8.1 x64** 
**Version: 0.0.5** 
**Commit: 6df1b9a** 

The River Rafts attraction has a default design called Garden Explorer, if you try to build this track design on ORCT2 nothing is shown in the preview area and selecting it crashes the game. This works in vanilla. I did not try to create a custom track design to see what happens.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Create a map with River Rafts available (or use the save created by the dump below)
2. Try to build the "Garden Explorer" track design
3. The game crashes

**Dump file**
[dump.zip](https://github.com/OpenRCT2/OpenRCT2/files/265267/dump.zip)

**Screenshots / Video:**
![RCT2](https://cloud.githubusercontent.com/assets/2224730/15276793/9c9b6a10-1ac8-11e6-8846-d0443a5aac55.png)
![OpenRCT2](https://cloud.githubusercontent.com/assets/2224730/15276794/9c9e217e-1ac8-11e6-8927-cd07f6ff4c7a.png)

**Save game:**
[dumpSave.zip](https://github.com/OpenRCT2/OpenRCT2/files/265268/dumpSave.zip)

**Comment by janisozaur** [comment]
#0  0x018ad42c in window_track_list_select (w=0x31c2e60 <g_window_list+1216>, index=0) at /home/janisozaur/workspace/OpenRCT2/src/windows/track_list.c:200
#1  0x018a24c5 in window_track_list_scrollmousedown (w=0x31c2e60 <g_window_list+1216>, scrollIndex=0, x=115, y=13) at /home/janisozaur/workspace/OpenRCT2/src/windows/track_list.c:285
#2  0x01b14cea in window_event_scroll_mousedown_call (w=0x31c2e60 <g_window_list+1216>, scrollIndex=0, x=115, y=13) at /home/janisozaur/workspace/OpenRCT2/src/interface/window.c:1910
#3  0x022dc770 in input_scroll_begin (w=0x31c2e60 <g_window_list+1216>, widgetIndex=3, x=120, y=76) at /home/janisozaur/workspace/OpenRCT2/src/input.c:602
#4  0x022d6cc4 in input_widget_left (x=120, y=76, w=0x31c2e60 <g_window_list+1216>, widgetIndex=3) at /home/janisozaur/workspace/OpenRCT2/src/input.c:1027
#5  0x022c789c in game_handle_input_mouse (x=120, y=76, state=1) at /home/janisozaur/workspace/OpenRCT2/src/input.c:312
#6  0x022c6008 in game_handle_input () at /home/janisozaur/workspace/OpenRCT2/src/input.c:151
#7  0x023ba683 in game_update () at /home/janisozaur/workspace/OpenRCT2/src/game.c:343
#8  0x023cb14a in rct2_update () at /home/janisozaur/workspace/OpenRCT2/src/rct2.c:462
#9  0x023e2fe9 in openrct2_loop () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:392
#10 0x023df9b7 in openrct2_launch () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:322
#11 0x01ffbcbd in main (argc=2, argv=0xffffd324) at /home/janisozaur/workspace/OpenRCT2/src/platform/posix.c:60

**Comment by Wirlie** [comment]
I can reproduce this problem with all rides on the "select design" window:

![sin titulo](https://cloud.githubusercontent.com/assets/7508197/15279396/8780361c-1ae9-11e6-8c53-b8c5ddfeff38.png)

but, if you move the cursor at another element of the list this problem is solved:

![sin titulo](https://cloud.githubusercontent.com/assets/7508197/15279421/de332fa0-1ae9-11e6-9750-852baa9de2fc.png)

**Comment by coltongit** [comment]
This problem worsens when there is only one factory design, because there isn't another to so-called "fix" this problem, like for example, the go karts.

**Comment by daihakken** [comment]
This also happens when you try to build steeplechase, which also has only one design.
