### ISSUE TITLE
Suggestion: Change the color of the font used on the console.

### ISSUE THREAD

**Issue by Wirlie** [OpenRCT2/OpenRCT2#3626]
**OS:** windows 10 (32 bits)
**Version:** 0.0.5.0
**Commit:** latest commit (9ebb7f4)

![sin titulo](https://cloud.githubusercontent.com/assets/7508197/15278119/7860c2ec-1ad9-11e6-8d91-6760a5c70bec.png)

![sin titulo](https://cloud.githubusercontent.com/assets/7508197/15279707/e651371a-1aec-11e6-9ae4-b9f2077fa2e9.png)

The text is barely readable, would it be better to use the yellow color (or white) instead of the green color? yellow and white color contrasts the blue color, I think.

**Comment by Gymnasiast** [comment]
I agree. White would be best, I think.

**Comment by Patrik356b** [comment]
Go for the white

**Comment by Nubbie** [comment]
How about giving the font black lines around them? 
That makes them pop out more?
![possible fix](https://cloud.githubusercontent.com/assets/17282384/15327120/a67c0f2e-1c50-11e6-9b96-2b93777f7431.png)

**Comment by Nubbie** [comment]
Also, this is white text and I dont think it fits that well, nor makes it more clear
![white text](https://cloud.githubusercontent.com/assets/17282384/15327313/5793d102-1c51-11e6-8cd3-e0df6ac2139b.png)

**Comment by Gymnasiast** [comment]
I'd go for white with outline (black lines around them).

**Comment by janisozaur** [comment]
Can you check non-sprite fonts too?

**Comment by Nubbie** [comment]
Made a pull request so you guys can see how the code looks

**Comment by Nubbie** [comment]
I guess merged RP #3642  now fixes this

**Comment by Wirlie** [comment]
btw, thanks @Nubbie :)

**Comment by Nubbie** [comment]
Nothing to thank for :p
Had some issues with it too
