### ISSUE TITLE
Assertion failed.

### ISSUE THREAD

**Issue by Wirlie** [OpenRCT2/OpenRCT2#3628]
**OS:** Windows 10
**Version:** 0.0.5.0
**Commit:** 9ebb7f4

![sin titulo](https://cloud.githubusercontent.com/assets/7508197/15279209/5d2d621a-1ae7-11e6-89cf-c195983fabcd.png)

**Steps to reproduce:**
I don't know how to reproduce it.

**Console message:**
Localisation CALLPROC reached. Please contact a dev.

**Save game:**
[Jardines Gravitatorios.txt](https://github.com/OpenRCT2/OpenRCT2/files/265465/Jardines.Gravitatorios.txt)

**Comment by duncanspumpkin** [comment]
Any idea what you were doing when this happened. This bit of code makes no sense and we couldn't work out in regard situation it would ever get called.

**Comment by janisozaur** [comment]
@Wirlie please provide:
* your config.ini
* the exact language file you are using

**Comment by An-dz** [comment]
The exact same error just happened to me. I'm using the default British English.

What I did was to open the game, open the options from the top right button, open the intro sequence editor, choose the default RCT2 intro and after a few seconds the game crashed. I believe it was about to change the location in the sequence.

[config.txt](https://github.com/OpenRCT2/OpenRCT2/files/266130/config.txt)

**Comment by Wirlie** [comment]
@duncanspumpkin The problem is that I do not know how to reproduce it, I was waiting and suddenly the error occurred...

@An-dz Confirmed: I can reproduce the problem with your instructions, I hope that with this the developers can fix the bug.

@janisozaur 
I don't know if it is still required:
* [config.txt](https://github.com/OpenRCT2/OpenRCT2/files/266312/config.txt)
* Language: es-ES.txt (Spanish), I use the default file (the same of OpenRCT2/Localisation)

**Comment by Nubbie** [comment]
Another guy reported this on [Gitter Non Dev](https://gitter.im/OpenRCT2/OpenRCT2/non-dev)

**Comment by coltongit** [comment]
I'm using US English and this same error happened to me.

**Comment by IntelOrca** [comment]
Because paint_path has not been implemented yet, it still uses the old RCT2 string arguments array.
