### ISSUE TITLE
Wrong ride name at the queue sign.

### ISSUE THREAD

**Issue by Wirlie** [OpenRCT2/OpenRCT2#3634]
**OS:** Windows 10
**Version:** 0.0.5.0
**Commit:** latest commit (d4394c7)

Today I saw this bug:
![sin titulo](https://cloud.githubusercontent.com/assets/7508197/15295825/274a8062-1b58-11e6-90aa-9acb1d242d2e.png)

The queue sign display: "Torre de observación" (Observation Tower).
But the ride name is: "Montaña Rusa de Agua 1" (Water Coaster 1).
PS: I realized that the wrong ride name can change. (for example, in some times the queue sign displays "Puesto de bebida" (Drink Stall)).

At this another pic the queue sign display "Chairlift". But the ride name is: "Montaña Rusa Sacacorchos" (Corkscrew Roller Coaster).
![sin titulo](https://cloud.githubusercontent.com/assets/7508197/15296076/4ba9d308-1b59-11e6-9ea9-947dc8809fee.png).

_Sorry for my bad English._

**Save game:**
[Jardines Gravitatorios.txt](https://github.com/OpenRCT2/OpenRCT2/files/266498/Jardines.Gravitatorios.txt)

**Comment by jensj12** [comment]
Confirmed. Hoverig over the queue sign does show the correct ride name and the sign resets at the ride of the ride it belogs to (not the ride it shows, so you'll see it jumping).

**Comment by IntelOrca** [comment]
Same issue causing #3628
