### ISSUE TITLE
Crash loading park with missing Objects

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#3637]
**OS: Windows 10, Arch Linux** 
**Version:0.0.5 Develop** 
**Commit:eb19ca8 and later, as seen in the video (It updated between me crashing and recording the video example)** 

Explanation of the issue...

- [ ] Reproducible in RCT2 (vanilla)? (Unable to check - Does not run on my PC)
- [ ] Multiplayer?

**Steps to reproduce:**
1. Add park to the Game
2. Try to Open it.

**Dump file**
See Zip Below.

**Screenshots / Video:**
https://youtu.be/9YwmaNdFJkQ

**Save game:**
[Crash_With_Scenario.zip.txt](https://github.com/OpenRCT2/OpenRCT2/files/266851/Crash_With_Scenario.zip.txt)

This map was created using the Scenario Editor by BlindiRL.

**Comment by duncanspumpkin** [comment]
Fixed by #4024
