### ISSUE TITLE
Scrolling text signs don't load their text colour

### ISSUE THREAD

**Issue by An-dz** [OpenRCT2/OpenRCT2#3638]
**OS: Windows 8.1 x64** 
**Version: 0.0.5** 
**Commit: 680c33d** 

The scrolling text signs let you choose a text colour, but this text colour is not set when loading a game.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Place a scrolling text sign
2. Set a different colour for it
3. Save the game
4. Load the same game
5. Notice that the text colour is white but opening its options show the correct colour assigned

**Screenshots / Video:**
This screenshot shows step 5:
![scrollingtextcolour](https://cloud.githubusercontent.com/assets/2224730/15303699/72312478-1b8f-11e6-904b-e9d4d2409c3f.png)

**Comment by zsilencer** [comment]
this was caused by f22257056cce8d443b0b638d3d144d285c30a5d0

**Comment by Overv** [comment]
Should the user string sanitization be removed or should a special case be added for these?

**Comment by zsilencer** [comment]
im thinking it might work to allow the colour code format codes in the user strings loading
