### ISSUE TITLE
Crash Upon Reaching Main Menu

### ISSUE THREAD

**Issue by Ghosy** [OpenRCT2/OpenRCT2#3640]
**OS: Arch Linux(64-bit)** 
**Version: 0.0.4** 
**Commit: 1eb91cb** 

When the game is launched it will crash quickly after. If I launched the game with "openrct2 --headless" the game will run happily until stopped. If I launched the game with "openrct2 intor" the game will work up until it reaches the main menu or until a button is pressed and it skips to the main menu.

The original copy of RCT2 is from disc.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Start game with command "openrct2 --verbose"

**Dump file**
[dump.txt](https://github.com/OpenRCT2/OpenRCT2/files/267176/dump.txt)

**Screenshots / Video:**
N/A

**Save game:**
N/A

**Comment by janisozaur** [comment]
Intro was most likely broken at that point, as we only fixed it recently. Can you check if your problem persists in current builds?

**Comment by coltongit** [comment]
Yes, please check the latest dev build @Ghosy.

**Comment by Ghosy** [comment]
The latest dev build has fixed the issue.
