### ISSUE TITLE
Can't connect to friends servers or them to mine! Please Help!!

### ISSUE THREAD

**Issue by cdawgydawg** [OpenRCT2/OpenRCT2#3646]
**OS:** Windows 10
**Version:** 0.0.5-8
**Commit:** 

Explanation of the issue...
I have been trying to connect with my friends servers and them to mine and we can never see eachothers on the list. We have advertising checked and we have also searched it by using the hostname and their IP address and it will just bring it up with a maroon circle next to the name. I have done the correct port forwarding and still not working. Please help I have been trying everything for 2 days!

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Comment by Joshwoo69** [comment]
you didn't privide us ANY infomation that will help us. HOW CAN WE HELP YOU?

**Comment by cdawgydawg** [comment]
Idk how else to say it but to make it simple my friends and I cant join each others servers in open RCT2. Any suggestions?

**Comment by AaronVanGeffen** [comment]
What platform are you on, and what version and commit of OpenRCT2 are you using? You haven't filled out this information in the ticket, but it is paramount for us to be able to help you.

**Comment by cdawgydawg** [comment]
I updated the version and OS info but unsure on how to find the commit. Not to tech savvy.

**Comment by IntelOrca** [comment]
This isn't a bug so the version (although I assume its at least 0.0.4), commit ID etc. doesn't matter.

@cdawgydawg the process isn't different from any other server / client game. There must be something not setup correctly, either the router is not got an incoming port setup or you have a firewall on your computer blocking it.

**Comment by fromthere** [comment]
@cdawgydawg Go to http://www.yougetsignal.com/tools/open-ports/ and check your port(default is 11753)

<img width="502" alt="portopen" src="https://cloud.githubusercontent.com/assets/10338434/15451552/2f14ea5c-2004-11e6-953d-8d41040b53b0.png">
You should get above message(port opened) to multiplayer working. or nobody can connect to your game.

**Comment by cdawgydawg** [comment]
@fromthere Thank you that was helpful. I have set up the port forward for it and to even make sure i did it right my cousin who is a computer tech took control of my computer remotely and set it up himself and still didnt work. I just checked on the open port finder and it said that it was not open. What am i doing wrong?

**Comment by cdawgydawg** [comment]
I realized i never actually saved the changes when i added the OS and version but i updated it now. If someone could please help me figure out whats wrong that would be awesome.

**Comment by IntelOrca** [comment]
@cdawgydawg Its difficult to help you with this sort of thing as its purely an environment issue and not related to OpenRCT2. Perhaps try searching around other forums with your router model, OS etc.

**Comment by Joshwoo69** [comment]
*after calming myself down I am back*
okay looks like your port forwarding is not correct. may we have your router model?
oh. did you connect to your router : 192.168.0.1 (AFAIK)

**Comment by cdawgydawg** [comment]
Thanks for coming back. I appreciate it. 
I have Netgear and the model is WNDR3700v4
I have connected to it as far as i know.
@Joshwoo69

**Comment by fromthere** [comment]
I think [OpenRCT2 non-dev Gitter.im](https://gitter.im/OpenRCT2/OpenRCT2/non-dev?source=all-rooms-list) is much better place to talk since this issue is not related to OpenRCT2.

**Comment by Gymnasiast** [comment]
Either that or the openrct2.org forums.

**Comment by Joshwoo69** [comment]
@cdawgydawg [like for a bit of help](https://community.netgear.com/t5/Wireless-N-Routers/How-to-open-port-on-Netgear-WNDR3700v4/td-p/981549)
okay I think I will be out as port forwarding is not my faculty. :stuck_out_tongue:

**Comment by Nubbie** [comment]
@cdawgydawg Was a long time ago now, has the issue been solved? :smile:

**Comment by cdawgydawg** [comment]
@Nubbie Unfortunately I never figured it out. Never could get the port opened. Tried the normal ways to open it and have no idea what else to try

**Comment by Patrik356b** [comment]
@cdawgydawg did you try opening the port in the windows firewall?

And in your router, did you pick TCP or UDP for the portforwarding?
OpenRCT2 uses TCP so it's worth checking
