### ISSUE TITLE
Redudant "/" after ride time & ride length of single-station rides

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#3647]
**OS: Windows 10** 
**Version: 0.0.5** 
**Commit: 1fd2c1d** 

Seems that STR_1343/1346 are used while the game should be using STR_1342/1345 in single station ride. Affecting both sprite font and non-sprite font.
![image](https://cloud.githubusercontent.com/assets/13048125/15348291/14abc88a-1cfc-11e6-861d-a8b345766485.png)
![image](https://cloud.githubusercontent.com/assets/13048125/15348298/1e9d81bc-1cfc-11e6-9492-565dd9fbbdda.png)

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**
If you have a dump file, zip it and drag&drop it here.

**Screenshots / Video:**
Drag / drop screenshots here. Use https://vid.me to upload video.

**Save game:**
Change the file extension to .txt or package to a .zip so that it can be drag / dropped here...

**Comment by octaroot** [comment]
As #3654 has been merged, this can now be closed.
