### ISSUE TITLE
Invalid sprite on selecting some button

### ISSUE THREAD

**Issue by YJSoft** [OpenRCT2/OpenRCT2#3661]
**OS: OS X** 
**Version: 0.0.5** 
**Commit: 9e6df44** 

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Select some buttons like debug
2. wrong sprite shows(it is different by scenario)

**Screenshots / Video:**
<img width="140" alt="2016-05-19 2 19 13" src="https://cloud.githubusercontent.com/assets/5893514/15383283/e5f681f2-1dcc-11e6-9b00-8eccca9a5405.png">

**Comment by octaroot** [comment]
Introduced in 3bdc06dc25ceaa038410c5e90b198dff6ab8bf57, will check it ASAP
