### ISSUE TITLE
Different advertising for different 'guest intensities' (Like in RCT3)

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#3689]
This would easily be devoted but if you think about it, it might not be a bad idea.
In RCT3 you could advertise to different types of magazines, there is 'advertisement options' for kids, adults and teenagers. If this could be implemented, then it could be used to get guests with a specific intensity to fill out the park with more specific people.

For example if you have a lot of calm kids attractions, you might want to get more people who ride less intense rides, hence you advertise for kids

**Benefits:** 
- Get more people 'moving around in the park' 
- Know specifically what you should buy
- Get more different people who prefer different intensities

**Rough Concept:**
Kids Advertisement: 60 % of new guests prefer calmer rides
Collage Advertisement: 60 % of new guests prefer wilder rides
Adult Advertisement: A mix between the intensity for families, like 30 less intense, 30 intense, 40 random

**Comment by HaasJona** [comment]
I like the idea, but I wouldn't call it kids advertisement. A better wording might be "advertise in a family friendly magazine" or similar.

I hope we will sometime add real age groups like in rct 3 and then your suggestions would be confusing because advertising for kids wouldn't spawn mire kids but just low intensity guests.

**Comment by Nubbie** [comment]
Rough concept, the names need to be changed :p

You could:
* use a name fitting for the magazin like "tiny Tims adventure" 
* A description for the magazine like you said :)

**Comment by jensj12** [comment]
The preferred intensity of a guest [increases over time](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/peep/peep.c#L8747), unless the scenario is set to make peeps prefer less intense rides. Prefer less (or more) intense rides is a flag that can only be set for the entire park, not for an individual guest. This means the effect of a kids campaign will be very small. A campaign for more intense rides should work fine, though the same can be achieved by putting the intense and less intense rides on the correct spot in the park, so the preferred intensity has increased by the time guests reach the intense rides.
