### ISSUE TITLE
Boundary fences don't disappear off map edge

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3690]
As shown here.
![rct2 edge](https://cloud.githubusercontent.com/assets/4167951/15445046/9c582f5a-1ec6-11e6-8c2c-8a82de7a3189.png)
It occurred in wolffreak's server running Katie's Dreamland, and it was during online play.

**Comment by Gymnasiast** [comment]
I'd like to see it confirmed in our unmodified version. Wolfreak runs a modified build.

**Comment by Nubbie** [comment]
![not reproducable](https://cloud.githubusercontent.com/assets/17282384/15447391/69d02f6c-1f41-11e6-95ce-4a2a711940cf.png)
Could not reproduce it, might be a Wolfreak mod thing
Can you try this is the unmodified version as Gymnasiast said?

**Comment by Superjustinbros** [comment]
Yeah, I assume it's an issue with Wolffreak's servers only, now that you mention it.
