### ISSUE TITLE
Swamp goo animates faster compared to RCT2

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#3691]
**OS:** windows 10
**Version:** 0.0.5
**Commit:** 2eeb20c

Swamp goo animates faster in OpenRCT2 compared to RCT2. I've uploaded a video so you can see the difference. I know it's not a bug but it does in my view animate a bit to quick 

**Screenshots / Video:**
https://vid.me/sqSl - openrct2
https://vid.me/fnJO - RCT2

**Save game:**
[Frightmare Hills.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/275769/Frightmare.Hills.sv6.txt)

**Comment by janisozaur** [comment]
You have "uncap FPS" option turned on. Can you check if the issue persists if you turn it off?

**Comment by IntelOrca** [comment]
uncap FPS only affects sprites, I expect its a regression from drawing of small scenery.

**Comment by chrismilne300** [comment]
@janisozaur Yeah animation is still fast with uncap FPS off
