### ISSUE TITLE
Problen with saving scenery

### ISSUE THREAD

**Issue by dpitsch** [OpenRCT2/OpenRCT2#3695]
**OS:** windows7
**Version:** v0.0.5
**Commit:** c43e3ee

Explanation of the issue...When trying to save a ride and the "ADD SCENERY" button is pressed you get some scenery - it is not all grayed out like it is supposed to be. Upon selecting the scenery the items already "selected" don't show up when saving. If you select them, they go dark. Selecting them again doesn't help. When saving the ride only the items you selected are saved. Also as per the second pic extra items show up.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**
If you have a dump file, zip it and drag&drop it here.

**Screenshots / Video:**
![scr2](https://cloud.githubusercontent.com/assets/18489460/15448669/d926a3be-1f2d-11e6-8fe0-f180f66a8692.png)
![scr4](https://cloud.githubusercontent.com/assets/18489460/15448671/de18f782-1f2d-11e6-8f94-2299ae825dee.png)

Drag / drop screenshots here. Use https://vid.me to upload video.

**Save game:**
Change the file extension to .txt or package to a .zip so that it can be drag / dropped here...

**Comment by zsilencer** [comment]
I fixed this already but haven't made a pull request.

**Comment by Superjustinbros** [comment]
I downloaded build 1cd857a, and the issue still exists.

**Comment by zsilencer** [comment]
have you tried build #3702, it appears to work for me
