### ISSUE TITLE
Groups set to default names and were deleted in multiplayer

### ISSUE THREAD

**Issue by birthdaybrian** [OpenRCT2/OpenRCT2#3703]
**OS: Windows 7 Home Premium SP1 x64 with the Windows 8.x theme installed** 
**Version:0.0.5-8** 
**Commit:0d4ec74** 

Explanation of the issue...

Hey. I was hosting my server and when I was looking at my groups, the groups name has been set to default and there were many groups deleted.
- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Host a multiplayer server
2. Go into the players list and go to groups
3a. Check to see if the groups name has been changed to default
3b. Check groups.cfg to see if the groups name match the same one as your server's groups

**Dump file**
If you have a dump file, zip it and drag&drop it here.

**Screenshots / Video:**
Bug
![groupbug1](https://cloud.githubusercontent.com/assets/17324259/15451903/75bc9380-1fa8-11e6-94bd-885716411946.png)

My server's groups in Notepad++
![groupbug2](https://cloud.githubusercontent.com/assets/17324259/15451904/7752cde0-1fa8-11e6-89e1-45acabb1a9c4.png)

Here is the groups configuration file if you want to try out testing out the bug to see if you get the same problem as me.
[groups.cfg.txt](https://github.com/OpenRCT2/OpenRCT2/files/276168/groups.cfg.txt)

**Comment by zsilencer** [comment]
i think they switched to .json format so you will have to remake it

**Comment by birthdaybrian** [comment]
@zsilencer I did. I am hosting using wolfreak's build now.

**Comment by janisozaur** [comment]
As of #3687 groups are stored in json format. You have to redo them manually, there is no automated upgrade path.

Also, please don't report issues for modified builds to us, report them to wolfreak or whoever provides you with those builds.
