### ISSUE TITLE
Staffs go surface when entering blinking path

### ISSUE THREAD

**Issue by YJSoft** [OpenRCT2/OpenRCT2#3707]
**OS: OS X** 
**Version: 0.0.5** 
**Commit: 03b8a5b** 

Staffs go surface when entering blinking path. Guests are not effected since they just ignore blinking path.

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Build path underground
2. let staff go to blinking path and see the result

**Screenshots / Video:**
https://vid.me/689W

**Comment by Gymnasiast** [comment]
I think this is an original bug, as I remember it from either RCT1 or RCT2. Haven't checked yet, though.

**Comment by YJSoft** [comment]
@Gymnasiast Yes. It's original bug(checked on RCT2)

**Comment by duncanspumpkin** [comment]
Fixed by #4460
