### ISSUE TITLE
Having trouble placing scenery or paths underground when underneath path above ground.

### ISSUE THREAD

**Issue by cdawgydawg** [OpenRCT2/OpenRCT2#3710]
**OS:** Windows 10
**Version:** 0.0.5-8
**Commit:** 

Explanation of the issue...
A toggle button to see through paths above ground would be very helpful. I'm not sure how suggestions on this work but I really struggle when placing things underground that are underneath a path above ground. If i could toggle those paths on and off to see through it that would help tremendously.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Comment by Gymnasiast** [comment]
If you don't fill in parts of the template, please remove them.

Anyway: RCT1 made paths see-through (using a dotted pattern) when in underground made. We should introduce something similar, I'd say.

**Comment by cdawgydawg** [comment]
I'll start doing that my bad. 

And ya that would be awesome. It's made it really tough for me on more than a few occasions not being able to see below.

**Comment by zaxcav** [comment]
The paint clipping feature (for which PR #4673 provides the initial prototype) will also be able to be used for this purpose.

**Comment by Gymnasiast** [comment]
@zaxcav This issue was really about see-through paths. Those have been implemented, so I'll close this.
