### ISSUE TITLE
OpenRCT2 rapidly pausing and unpausing when (edge) scrolling

### ISSUE THREAD

**Issue by Animoticons** [OpenRCT2/OpenRCT2#3713]
**Windows 10** 
**0.0.5.0 build 01f4ddd (RCT2 Steam version is 2.01.028 (If that matters))** 

So everytime i edge scroll, the game starts to pause/unpause in rapid succession as long is it scrolls. Also happens when scrolling with the arrow keys. 
- Reproducible in RCT2 (vanilla)?
  No
- Multiplayer?
  Unknown, but happens most likely there as well.

**Steps to reproduce:**
1. Load any scenario
2. Enable the "Pause game when Steam overlay is open" option.

It seems that the "Pause game when Steam overlay is open" option is causing this. Disabling that fixes it.

I guess thats not very important for the moment but i thought i'd let you know.
Also thanks for this great project, love you guys ;)

**Comment by mrtnptrs** [comment]
And you're are sure this isn't just stutter?

**Comment by Animoticons** [comment]
No, the Play/Pause icon in the to right corner is rapidly flashing between Play/Pause too.

**Comment by janisozaur** [comment]
@Animoticons can you try latest builds?

**Comment by mrtnptrs** [comment]
I can't reproduce this using the latest build.

**Comment by vikusz** [comment]
Can confirm this issue in the latest  version (0.0.5.0 build acaa0d3).
Requirements: Enable pause on Steam overlay and
Software rendering (with HW....)

The issue is not reproducible in OpenGL rendering.
