### ISSUE TITLE
Assertion Failed when opening park

### ISSUE THREAD

**Issue by Rheel17** [OpenRCT2/OpenRCT2#3722]
Whenever I open this park: http://www.nedesigns.com/park/1490/legacies-themepark-europe I get an Assertion Failed error:

> Assertion Failed!
> 
> Program: F:\Program Files (x86)\OpenRCT2\openrct2.dll
> File: src\peep\peep.c
> Line: 8470
>
> Expression: !(gParkFlags & PARK_FLAGS_NO_MONEY)
>
> For information on how your program can cause an assertion
> failure, see the Visual C++ documentation on asserts
>
> (Press Retry to debug the application - JIT must be enabled)

This does not happen with other parks I downloaded

**Comment by IntelOrca** [comment]
This has already been fixed.
