### ISSUE TITLE
Building Soap box derby racers crashed game

### ISSUE THREAD

**Issue by Orijad** [OpenRCT2/OpenRCT2#3731]
*_OS: Windows 7 Ultimate SP1 X64
*_Version: OpenRCT2-0.0.5.0-develop-4afde28-windows
**Commit: 4afde28be31ffbbbddbbce7e77ec62d83f923edb

Explanation of the issue...
Where playing multiplayer over the Internet with a friend. I was host and started building Soap box derby racers when the game crashed, my firend was desyned when it happened and was not thrown out of game. 
- [X] Reproducible in RCT2 (vanilla)?
- [X] Multiplayer?

**Steps to reproduce:**
1. Run multiplayer Vanilla
2. Build Soap box derby racers

**Dump file**
[Build Soap box derby racers.zip](https://github.com/OpenRCT2/OpenRCT2/files/282603/Build.Soap.box.derby.racers.zip)

If you have a dump file, zip it and drag&drop it here.

**Screenshots / Video:**
none

**Save game:**
[Build Soap box derby racers.zip](https://github.com/OpenRCT2/OpenRCT2/files/282603/Build.Soap.box.derby.racers.zip)

**Comment by X123M3-256** [comment]
Did you use a track piece not available on that track type? There's been a bug recently where the construction window shows pieces that aren't actually available, and the game will crash if you build them.

**Comment by janisozaur** [comment]
@Nubbie can you check stack trace of this dump, please?

**Comment by janisozaur** [comment]
See #4752, but there might be more.

**Comment by Nubbie** [comment]
@janisozaur 
OP's dumpfile 5ac39403-1f8f-41e9-a45a-6c6ab4c34886(4afde28).dmp

**Error message;**
Unhandled exception at 0x00993E1C (openrct2.exe) in 5ac39403-1f8f-41e9-a45a-6c6ab4c34886(4afde28).dmp: 0xC0000005: Access violation writing location 0x0000000A.
(**missing symbol file OpenRCT2.exe which I even downloaded the same version from the site)**

**Call Stack;**
```
>	openrct2.exe!00993e1c()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for openrct2.exe]	
 	openrct2.dll!RCT2_CALLPROC_X(int address, int _eax, int _ebx, int _ecx, int _edx, int _esi, int _edi, int _ebp) Line 45	C
 	openrct2.dll!track_paint(unsigned char direction='\x3', int height=1024, rct_map_element * mapElement) Line 923	C
 	openrct2.dll!sub_68B3FB(int x, int y) Line 237	C
 	openrct2.dll!sub_68B2B7(int x, int y) Line 81	C
 	openrct2.dll!sub_6CBCE2(int rideIndex=12, int trackType=18, int trackDirection=0, int edx=0, int) Line 2368	C
 	openrct2.dll!window_ride_construction_draw_track_piece(rct_window * dpi=0x000cfcc0, rct_drawpixelinfo * rideIndex=12, int trackType=18, int trackDirection=0, int unknown=0, int width=158, int height=168, int) Line 2252	C
 	openrct2.dll!window_ride_construction_paint(rct_window * w=0x0fd1b1e0, rct_drawpixelinfo * dpi=0x000cfd00) Line 2157	C
 	openrct2.dll!window_draw(rct_window * w=0x0fd1ad20, int left=0, int top=0, int right=256, int bottom=448) Line 1543	C
 	openrct2.dll!gfx_redraw_screen_rect(short left=0, short top, short right, short bottom=448) Line 355	C
 	openrct2.dll!gfx_draw_dirty_blocks(int x=0, int y=0, int columns=2, int rows=7) Line 325	C
 	openrct2.dll!gfx_draw_all_dirty_blocks(...) Line 296	C
 	openrct2.dll!window_update_all(...) Line 161	C
 	openrct2.dll!rct2_draw(...) Line 284	C
 	openrct2.dll!openrct2_loop(...) Line 458	C
 	openrct2.dll!openrct2_launch(...) Line 324	C
 	openrct2.dll!StartOpenRCT(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance=0x00000000, char * lpCmdLine=0x002b351e, int nCmdShow=10) Line 109	C
 	openrct2.exe!004069e4()	Unknown
 	[External Code]	
 	ntdll.dll!77c49902()	Unknown
 	ntdll.dll!77c498d5()	Unknown
```

Tell me if I should give another shot with the symbol

**Comment by janisozaur** [comment]
@Nubbie no need.

This was in original paint setup code, does not happen anymore, so it's safe to close now.
