### ISSUE TITLE
Virginia Reel/Under Ground drawing bug 

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#3733]
**OS:** Windows 10
**Version:** 0.0.5
**Commit:** 4afde28

**Steps to reproduce:**
Load up my save of Whispering Cliffs in openRCT2 and look at the Virginia reel

**Screenshots / Video:**
OpenRCT2
![screen shot 05-25-16 at 07 44 pm](https://cloud.githubusercontent.com/assets/1381723/15552449/5765e640-22b2-11e6-8e79-6fcad93e297e.PNG)

RCT2

![screen shot 05-25-16 at 07 45 pm](https://cloud.githubusercontent.com/assets/1381723/15552458/610c7cc2-22b2-11e6-849b-7ce4bed3ba2a.PNG)

**Save game:**
[Whispering CliffsRCT2.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/282704/Whispering.CliffsRCT2.sv6.txt)
[Whispering CliffsRCT1.SV4.txt](https://github.com/OpenRCT2/OpenRCT2/files/282706/Whispering.CliffsRCT1.SV4.txt)

**Comment by Nubbie** [comment]
@marijnvdwerf 
Paint Setup bug
If you toggle between the original paint-setup and the 're-made one', this happens

**Comment by duncanspumpkin** [comment]
Fixed in https://github.com/OpenRCT2/OpenRCT2/commit/e373eeafa8acd4fd0bd4be83d3e089e5f3ee84b4
