### ISSUE TITLE
RCT1 Import money bug

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#3734]
**OS:** Windows 10
**Version:** 0.0.5
**Commit:** 4afde28

I've converted my save of Whispering Cliffs.SV4 into a .sv6 format using openRCT2  

**Steps to reproduce:**
Open my save of Whispering Cliffs.sv6 file in RCT2 after a while the money will turn to minus however much.

Do the same in OpenRCT2 and the money stays in the positives  

**Save game:**
[Whispering CliffsRCT2.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/282704/Whispering.CliffsRCT2.sv6.txt)
[Whispering CliffsRCT1.SV4.txt](https://github.com/OpenRCT2/OpenRCT2/files/282706/Whispering.CliffsRCT1.SV4.txt)

**Comment by IntelOrca** [comment]
Caused by the cheat detection checksum not being set.
