### ISSUE TITLE
The 'Close Park' cheat

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#3744]
Hello! I just hit 'close park' in the cheat window expecting it to close the park. Instead, it double closed all the rides as well, meaning a lot of hacks got reset and I'll have to redo them throughout the park. This is very annoying, so maybe it's a good idea to change the 'close park' text to something like 'close everything' to avoid confusion. I surely can't be the first or the last to make this mistake!

edit: 'Reset Park' might be the most accurate way to put it.

edit2: 'remove guests' also double closes all rides... I'm so confused.

**Comment by Broxzier** [comment]
This does not happen in f4690fb, and I don't remember it closing rides. Maybe you clicked "Remove all guests" instead?

**Comment by Gymnasiast** [comment]
You must have clicked 'Remove all guests', which does indeed "double close" the rides. That's a limitation reported it #3453 and one I want to get rid of, but haven't yet been able to. I'm also aware that it's less than ideal because many hacks are very delicate.

**Comment by Liampie** [comment]
I swear it was close park I used, but I can't replicate it so I guess you're right. Apologies for the confusion.
