### ISSUE TITLE
Problematic amount of staff/guest windows

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#3746]
OS: Windows 8
Version: latest

Clicking a guest in the guest list, or staff in the staff list, will make a window pop up with all the options for that peep or staffmember, as wel as a camera/view following them around. In the original RCT those windows popped up first in the corners, and once all corners were filled, elsewhere on the screen. There was also a cap of like 10 windows open at the same time; opening a new one would close another.

Now in OpenRCT, this cap seems to be gone, and sometimes new windows would pop up at the exact same spot as the previous window. As a result you can have dozens of windows open at the same time without you knowing it, because you can only see a single window. This slows down the computer horribly, a while ago I was worried my laptop would set itself on fire, and it struggled for five minutes until I managed to close some staff windows and make my laptop usable again. Has happened on more occasions, but you never notice unless it's too late.

I don't mind the lack of a cap, I think that's good. But maybe each new window should pop up in a different spot on the screen, like a bit lower to the right or something, stacking itself. I don't know how to explain it but it seems like the usual method of opening new windows on a windows computer.

**Comment by Gymnasiast** [comment]
There is a cap, by the way: it's 64, which is hard to hit in normal or even abnormal circumstances.

Having many viewports open slows the game down. For this reason another contributors opened a feature request asking for a way to lower the cap if the user wants to. That would also solve your heating issues.

As for windows being placed on top of each other: that's definitely a bug, they should be cascaded.

**Comment by Liampie** [comment]
Cascaded, that's the word I was looking for! Thanks for the reply. It's not urgent but I hope it gets fixed/added. :)

**Comment by janisozaur** [comment]
@Gymnasiast are you sure nobody is using overheating as a workflow? https://xkcd.com/1172/ ;)

**Comment by devnoname120** [comment]
Would it be possible not to render the viewport (or only the relevant part) of windows that are masked by another one above them?
This should fix most windows-related performance issues.

**Comment by Nubbie** [comment]
Is it fixed in #3993? :s

**Comment by mrtnptrs** [comment]
#3805 and #3993 fixed this.

**Comment by Gymnasiast** [comment]
Created #4252 for the problem of windows not being cascaded.
