### ISSUE TITLE
Problem saving new amount when changing money using console

### ISSUE THREAD

**Issue by Charlieep** [OpenRCT2/OpenRCT2#3748]
**OS:** Windows 10 & Windows 7
**Version:** 0.0.5.0
**Commit:** 8ee923f

Explanation of the issue...Using the console to change money doesn't save when turning saved game into a scenario.
- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1..Let's say you have built a scenario and put in $5,000,000.00 to start with (you forgot to select No Money). You have finished everything (rides, scenery, etc) and created and saved the landscape and scenario. Now you open the game build rides and scenery and are ready to save the game. Go to the console and type "Get Money 10000". The cash shows 10,000.00. Now save the game and select Convert Saved Game to Scenario and save. Next open the game and guess what your cash still shows $5,000,000.00. I haven't tried current_loan or max_loan. 
2. 

**Dump file**
If you have a dump file, zip it and drag&drop it here.

**Screenshots / Video:**
Drag / drop screenshots here. Use https://vid.me to upload video.

**Save game:**
Change the file extension to .txt or package to a .zip so that it can be drag / dropped here...

**Comment by duncanspumpkin** [comment]
Scenarios have a different variable you need to edit to change the amount of cash. Open up the scenario options window to change it.

**Comment by Charlieep** [comment]
Let's say your current cash is $32,280.00, how do you change it to $10.000.00? The scenario options window only allows changes in $500 increments.
