### ISSUE TITLE
Block Brake Issue when Run on Continous Non-block

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#3749]
https://openrct2.org/forums/topic/1306-block-brake-issue-when-run-on-continous-non-block/

giraty

> I recently notice something strange within OpenRCT2. I sometimes use block brakes on a continous circuit non-block brakes mode to "defy" the brakes failure. On the vanilla RCT2, the block brakes will simply brakes the train as normal with target 4 mph. But on my OpenRCT2 v0.0.4 I notice on continous non-block brakes mode, the block brakes will stop a train when there's a train located after the block brakes.
> 
> As you see in the picture, the next trains are held up by the block brakes even on the continous circuit which should only happened when continous with block sectioned is selected.
> 
> Regards.

**Comment by gDanix** [comment]
It's possible that the code handling block brakes isn't yet decompiled. I could not find any occurrence of VEHICLE_STATUS_STOPPED_BY_BLOCK_BRAKES other than https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/ride/vehicle.h#L288, which is only a declaration.

**Comment by duncanspumpkin** [comment]
No it's there me and Intel implemented it all. Look for the track elem for location in the code.

**Comment by gDanix** [comment]
AFAIK, [this code](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/ride/vehicle.c#L5447) is reached only when a train gets stopped in a block-brake track segment.

I have to investigate it deeply (and it's getting late), but it's probable that I'm going to find a solution for this.

**Comment by duncanspumpkin** [comment]
@gDanix issue is here but I'll let you try work it out before i post a fix https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/ride/vehicle.c#L5407
