### ISSUE TITLE
Adding "Disable Wilting of Plants" Cheat

### ISSUE THREAD

**Issue by Ziscor** [OpenRCT2/OpenRCT2#3754]
Since having employees in a Multiplayer park (and maintaining them) desyncs the game between the server and the client a lot (like when/after setting patrols) I see a lot of hosts choosing to remove employees altogether and disabling functions that employees would normally do through the cheats, namely Vandalism and Littering. However, there is another important function that an employee does (the handyman, specifically): **watering plants**. 

I'd like to request a feature to toggle the need to water plants. It's also a good feature to have when you want to make flowers at locations a handyman can't reach, but you want them to look perfect forever nonetheless instead of clicking the cheat "Water Plants" every once in a while.

**Comment by brettpenzer123** [comment]
It would be nice if the weather affected the game more then just sales. Rain should water your plants for you.

**Comment by IntelOrca** [comment]
@brettpenzer123 it does...

**Comment by brettpenzer123** [comment]
Like?

**Comment by JeroenDStout** [comment]
> It's also a good feature to have when you want to make flowers at locations a handyman can't reach

I have been thinking in general with handymen and grass/flowers that it may pay off to allow them to go through walls/over fences/through flowerbeds to do what they want to do. That way you _do_ need to arrange your staff properly (which I like for gameplay) but they can be expected to do it properly.

**Comment by Goddesen** [comment]
That could be an alright temporary ~~solution~~ helpful addition, but it doesn't solve the fact that handymen won't stray far off the path to water plants.

**Comment by JeroenDStout** [comment]
They could be altered to check farther off the path, though! The problem with mowing grass also is just that they do not actually _check_ there.

**Comment by Goddesen** [comment]
Wait, what? They don't? I had no idea. So much for all of my mow/water only handymen...

**Comment by JeroenDStout** [comment]
I think they could be patrolling and allowed off the paths, until they find grass (`peep_update_patrolling_find_grass`) and switch to mowing. I suppose this could be improved by the peep (when looking for grass) actively checking in the 4-5 tiles around him for a tile and heading there?

**Comment by janisozaur** [comment]
Done in #3768
