### ISSUE TITLE
Exiting cheats menu crashes game

### ISSUE THREAD

**Issue by Charlieep** [OpenRCT2/OpenRCT2#3769]
**OS:** Windows 10
**Version:** 0.0.5.0
**Commit:** 8db0933

Explanation of the issue...Upon exiting the cheats menu after making a change the game crashes.
This is something new it was not in build f56b033 but is in 8db0933. The older dmp was after changing the entrance, the second was after changing paths.
- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**
If you have a dump file, zip it and drag&drop it here.

**Screenshots / Video:**
Drag / drop screenshots here. Use https://vid.me to upload video.

**Save game:**
Change the file extension to .txt or package to a .zip so that it can be drag / dropped here...
[cheat exit issue.zip](https://github.com/OpenRCT2/OpenRCT2/files/288121/cheat.exit.issue.zip)

**Comment by Charlieep** [comment]
Apparently this is only a problem with this game that was sent to me by a "friend" because he was having trouble removing the existing scenery, paths. He didn't know how to replace the existing scenery tabs and wanted the invisible entrance replaced. After the first crash I used ParkDat to exchange the entrance. Here is the game file. Is the game corrupt?
[Game file.zip](https://github.com/OpenRCT2/OpenRCT2/files/288129/Game.file.zip)

**Comment by Nubbie** [comment]
**To** @Charlieep 
Seems to be something with the research/ object window that you can open with the de-bugging tools, might be some stuff you added/removed from them (Speculation)

----

**To devs**; This is what I got from the dump file 2068c087-4d19-4558-a6f0-8d7ca1d571d9(8db0933)

**Error Message;** 
Unhandled exception thrown: read access violation.
rideEntry was 0xFFFFFFFF.

```
>	openrct2.dll!research_finish_item(int entryIndex=72760) Line 194	C
 	openrct2.dll!sub_684AC3(...) Line 345	C
 	openrct2.dll!window_editor_object_selection_close(rct_window * w=0x5e97d0e0) Line 781	C
 	openrct2.dll!window_close(rct_window * window) Line 661	C
 	openrct2.dll!window_editor_object_selection_mouseup(rct_window * w=0x5e97d0e0, int widgetIndex=2) Line 898	C
 	openrct2.dll!input_state_widget_pressed(int x=974, int y=190, int state=2, int widgetIndex=2, rct_window * w=0x5e97d0e0, rct_widget * widget=0x5e8ee348) Line 1296	C
 	openrct2.dll!game_handle_input_mouse(int x=974, int y=190, int state=2) Line 337	C
 	openrct2.dll!game_handle_input(...) Line 151	C
 	openrct2.dll!game_update(...) Line 344	C
 	openrct2.dll!rct2_update(...) Line 463	C
 	openrct2.dll!openrct2_loop(...) Line 456	C
 	openrct2.dll!openrct2_launch(...) Line 324	C
 	openrct2.dll!StartOpenRCT(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance=0x00000000, char * lpCmdLine=0x01772e72, int nCmdShow=10) Line 109	C
 	openrct2.exe!004069e4()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for openrct2.exe]	
 	[External Code]	
```

**Autos;**
```
		WIDX_CLOSE	WIDX_CLOSE (2)	<unnamed-enum-WIDX_BACKGROUND>
-		window_research_page_enabled_widgets	0x5e8b29b0 {308, 130484}	unsigned int[2]
		[0]	308	unsigned int
		[1]	130484	unsigned int
```

Locals; 
```
		base_ride_type	28	int
		ebx	Variable is optimized away and not available.	
		entryIndex	72760	int
		i	Variable is optimized away and not available.	
+		rideEntry	0xffffffff {name=??? description=??? images_offset=??? ...}	rct_ride_entry *
		rideEntry2	Variable is optimized away and not available.	
		rideEntryIndex	Variable is optimized away and not available.	
		scenerySetEntry	Variable is optimized away and not available.	
		subSceneryEntryIndex	Variable is optimized away and not available.	

```

**Comment by stefan084** [comment]
just saying hi so I get updated if this gets fixed

**Comment by IntelOrca** [comment]
@stefan084 you can instead just press Subscribe under notifications on the right hand side.

**Comment by Nubbie** [comment]
@IntelOrca Told him he could do that too in another issue, anyways, I will try to be a 'fail safe' for him too when this gets merge to tell him 😄

**Comment by stefan084** [comment]
just curious since this is my first "crash" but how long do these issues usually take to fix? I guess I can go back to regular rct2 but it's kind of a letdown compared to this new one. also are you guys the one who made this game or do you just fix it when it breaks?

**Comment by IntelOrca** [comment]
@stefan084 you can just use an older version temporarily
http://openrct2.org/downloads

**Comment by stefan084** [comment]
ok but will my park still be there or will I have to start a new one? also where would I get an older version? thanks for any help

**Comment by Nubbie** [comment]
@stefan084 the saves will still be there and we didnt make RCT2 but most of us have contributed some to the project OpenRct2

**Comment by stefan084** [comment]
cool. where can I find older versions and how old will I need?

**Comment by Nubbie** [comment]
@stefan084 can find the downloads at https://openrct2.org/downloads
You could also play the stable version which doesn't crash as much etc

**Comment by stefan084** [comment]
well the oldest version is only 5 days old correct? tried that one and it didn't work either. i'll just study jiu jitsu for a bit. thanks anywho

**Comment by Nubbie** [comment]
Try the stable version

**Comment by stefan084** [comment]
wont let me open my saved park on the stable version

**Comment by Broxzier** [comment]
I just had a look with @stefan084 and was able to reproduce the issue with this park: https://files.gitter.im/stefan084/yhtw/STEF-WORLD-2-export.zip

When opening the park with verbose logging enabled, it prints out the following:

```
VERBOSE: [BMDIVE8 ] Warning: Image table size longer than expected.
VERBOSE: [SLDBODY ] Warning: Image table size longer than expected.
VERBOSE: [SLDTUBE2] Warning: Image table size longer than expected.
VERBOSE: [INTLSMT1] Warning: Image table size longer than expected.
VERBOSE: [INTWING ] Warning: Image table size longer than expected.
VERBOSE: [MACKMEGA] Warning: Image table size longer than expected.
VERBOSE: [SLDTUBE1] Warning: Image table size longer than expected.
VERBOSE: [LANDFT6 ] Warning: Image table size longer than expected.
VERBOSE: [1KMTXXRF] Warning: Image table size longer than expected.
VERBOSE: [LANDFT5 ] Warning: Image table size longer than expected.
VERBOSE: [LMPJNGL2] Warning: Image table size longer than expected.
VERBOSE: [KNGCODPA] Warning: Image table size longer than expected.
VERBOSE: [KNGCOLPA] Warning: Image table size longer than expected.
VERBOSE: [LMPJNGL1] Warning: Image table size longer than expected.
VERBOSE: [MGCBG5X5] Warning: Image table size longer than expected.
VERBOSE: [MVGRASS ] Warning: Image table size longer than expected.
VERBOSE: [MVJAGGED] Warning: Image table size longer than expected.
VERBOSE: [MVRCAVE ] Warning: Image table size longer than expected.
VERBOSE: [MVRFORM2] Warning: Image table size longer than expected.
VERBOSE: [MGBMT1X1] Warning: Image table size longer than expected.
VERBOSE: [XXBMTR01] Warning: Image table size longer than expected.
VERBOSE: [XXBMTR02] Warning: Image table size longer than expected.
VERBOSE: [XXBMTR03] Warning: Image table size longer than expected.
VERBOSE: [XXBMTR05] Warning: Image table size longer than expected.
VERBOSE: [XXBMTR08] Warning: Image table size longer than expected.
VERBOSE: [KLOTRCA2] Warning: Image table size longer than expected.
VERBOSE: [KLOTRCA3] Warning: Image table size longer than expected.
VERBOSE: [LMPTRE09] Warning: Image table size longer than expected.
VERBOSE: [LMPTRE10] Warning: Image table size longer than expected.
VERBOSE: [LMPTRE12] Warning: Image table size longer than expected.
VERBOSE: [LMPTRE13] Warning: Image table size longer than expected.
VERBOSE: [LOTRMT0O] Warning: Image table size longer than expected.
VERBOSE: [LOTRMT0S] Warning: Image table size longer than expected.
VERBOSE: [MGTOT2  ] Warning: Image table size longer than expected.
VERBOSE: [RSWR02MT] Warning: Image table size longer than expected.
VERBOSE: [RSWR03MT] Warning: Image table size longer than expected.
VERBOSE: [XXRFMT52] Warning: Image table size longer than expected.
VERBOSE: [1KMVGRAS] Warning: Image table size longer than expected.
VERBOSE: [BOULDJNG] Warning: Image table size longer than expected.
VERBOSE: [BOULDMTN] Warning: Image table size longer than expected.
VERBOSE: [COLROCK ] Warning: Image table size longer than expected.
VERBOSE: [MGCBG7X7] Warning: Image table size longer than expected.
VERBOSE: [IMTERBLC] Warning: Image table size shorter than expected.
VERBOSE: [IMTERBLB] Warning: Image table size shorter than expected.
```

It might have something to do with those files.

**Comment by Nubbie** [comment]
Crash tag?

**Comment by Nubbie** [comment]
Feels outdated as the crashed happened over a year ago and the cheat window has been modified plenty off times
