### ISSUE TITLE
Crash when kicking player

### ISSUE THREAD

**Issue by dVoCex** [OpenRCT2/OpenRCT2#3771]
**OS:** Windows 10 / debian Jessie
**Version:** 0.0.5.0
**Commit:** 8a427a2 and 1cdbd1e
openrct2.com develop 0.0.5.0 build  (8a427a2) windows installer and linux
openrct2.com develop 0.0.5.0 build  (1cdbd1e) windows installer and linux

Server crashes with "Segmentation fault" and without stacktrace. Connected clients also crashing at the same time. 

Server console:
```
someuser@somerandomserver:/usr/local/bin/openrct2# /usr/local/bin/openrct2/openrct2 host /etc/openrct2/server3/save/autosave_2016-05-29_08-13-45.sv6 --user-data-path=/tmp --headless
ERROR[/home/travis/build/OpenRCT2/OpenRCT2/src/network/network.cpp:792 (BeginServer)]: IPV6_V6ONLY failed. 92
Ready for clients...
Segmentation fault
```

**Steps to reproduce:**
Seems to be multiple causes? 
* Kick someone off the server (only server side crash)
* unknown? related to the save? (both crashing) (providing dumps)

**Dump file**
_8a427a2_ 
[e1ae6664-2a10-47d6-b10c-b664b137c1c6(8a427a2).zip](https://github.com/OpenRCT2/OpenRCT2/files/288254/e1ae6664-2a10-47d6-b10c-b664b137c1c6.8a427a2.zip)

_1cdbd1e_
[2a30869b-781b-4c08-92ec-dfc99bc914c5(1cdbd1e).zip](https://github.com/OpenRCT2/OpenRCT2/files/288257/2a30869b-781b-4c08-92ec-dfc99bc914c5.1cdbd1e.zip)

**Save game:**
**Client:**
_8a427a2_
[e1ae6664-2a10-47d6-b10c-b664b137c1c6.zip](https://github.com/OpenRCT2/OpenRCT2/files/288256/e1ae6664-2a10-47d6-b10c-b664b137c1c6.zip)

_1cdbd1e_
[2a30869b-781b-4c08-92ec-dfc99bc914c5.zip](https://github.com/OpenRCT2/OpenRCT2/files/288258/2a30869b-781b-4c08-92ec-dfc99bc914c5.zip)

**Server:**
[autosave_2016-05-29_08-13-45.zip](https://github.com/OpenRCT2/OpenRCT2/files/288260/autosave_2016-05-29_08-13-45.zip)

**Comment by Juli199696** [comment]
I still got the problem with the crash on kick. Today someone griefed the server and i tried to kick. End result was a crashed server. Still need some look into the netcode!
