### ISSUE TITLE
Ghost Clients on Multiplayer server

### ISSUE THREAD

**Issue by Juli199696** [OpenRCT2/OpenRCT2#3784]
**OS: Linux Debian Whezzy 64 Bit** 
**Version:Dev 0.0.5** 
**Commit: 649ea9c** 

Explanation of the issue...
Currently when a player tries to join a server and fail to download the map he stays connected as "Ghost client" with a 0 ping and cant be kicked. If you try to kick it the server can crash (Not every time) or just nothing happend and they dont get kicked. 
- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Currently known its on the Bkgames Creative Server which is hosted on linux and the Freebuild Autorestart Server which im hosting aswell on Linux.
If you try to connect and get disconnected or crash a gost client will be left on the server and fill up slots. If there many players (5-10) You can see some of them got a #2 at the end of name because there is a ghost client left.

**Dump file**

**Screenshots / Video:**
http://fs5.directupload.net/images/160531/2n6abxrx.png
**Save game:**

**Comment by Juli199696** [comment]
Current commit OpenRCT2-0.0.5.0-develop-af0f77e-linux.tar.gz
[img]http://g.recordit.co/lObav9SEQx.gif [/img]

**Comment by janisozaur** [comment]
Is this still a thing?

**Comment by Juli199696** [comment]
I haven't tried the latest versions. So i cant prove if it is gone or not. But my Linux Version is Debian 8 64 Bit and it was running on a Desktop envireorment.
