### ISSUE TITLE
Mountain tool does not raise land above 120 feet

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#3792]
**OS: 8.1** 
**Version: 5.0.0** 
**Commit: 67f1131**

The mountain tool will not raise other tiles above 120 feet.

![image](https://cloud.githubusercontent.com/assets/3454156/15698627/640d47bc-277b-11e6-9800-e9e4047cdd1d.png)

**Comment by Gymnasiast** [comment]
120 ft = +24 units or +36 m.
(Please use units next time or at least provide a conversion, most of the world and most of the developers here don't use Imperial.)
