### ISSUE TITLE
 Add support for loading any scenario in title sequences

### ISSUE THREAD

**Issue by wildgoosespeeder** [OpenRCT2/OpenRCT2#3800]
This is more of a feature request than a bug report, and a really trivial one at that. I was wondering if anyone could create a decent sequence for the default scenarios that come packaged with RCT2 Vanilla. What I found kind of disappointing was the opening sequence was just Six Flags Magic Mountain. I always felt that there should have been an opening sequence showcasing the other parks that have a good start to them.

The request:
- Title sequence for RCT2 scenarios
- Title sequence for WW scenarios
- Title sequence for TT scenarios

Also maybe someone can implement a feature to cycle through the other sequences so the main menu can be "fresh" instead of just the one selection in the options.

**Comment by Gymnasiast** [comment]
We have support for creating extra title sequences exactly for this like this. The only technical barrier is that you can't currently load every scenario, but support for that could be added.

When that support is added, people creating title sequences can just put them on openrct2.org.

**Comment by janisozaur** [comment]
Your request would be a better fit at https://www.reddit.com/r/openrct2/ or https://www.reddit.com/r/rct/

**Comment by Gymnasiast** [comment]
@janisozaur Except we do need support for loading any scenario, not just MM and RCT1 ones as it is currently.

**Comment by IntelOrca** [comment]
We can add support for loading any scenario from the scenario repository, but why should a custom title sequence for RCT2 be part of the game?

**Comment by Gymnasiast** [comment]
@IntelOrca Exactly my point, we have support for extra title sequences, and openrct2.org has the store for exactly this kind of requests.

I kept it open because we need to add support for loading any scenario from the scenario repository. I'll adjust the title.

**Comment by IntelOrca** [comment]
@Gymnasiast openrct2.org has a store?

**Comment by Gymnasiast** [comment]
@IntelOrca Wait, that was .NET. I'll ask the ORG people.

**Comment by wildgoosespeeder** [comment]
I once gave my thoughts on the Subreddits for something like this but the Redditors told me to post it here instead. I guess what I am asking is make the sequences I am requesting an official feature of OpenRCT2 instead of just community download or something. So the only hurdle to make this a plausibility is the inability to load *.SC6 files yet as only *.SV6 is allowed.

**Comment by janisozaur** [comment]
@wildgoosespeeder the part about providing support for loading any scenario and save is something we'll have to implement, I was not aware of this limitation.

Creating the actual sequence is left to the community, this is what I meant by my previous comment.

**Comment by wildgoosespeeder** [comment]
@janisozaur
Once the community does create the sequences I am requesting, can it be considered part of the build? That's what I'm hoping for.

**Comment by IntelOrca** [comment]
@wildgoosespeeder why does it need to be part of the build when you can download it? Same with scenarios, we don't distribute any, you just supply your own.

**Comment by wildgoosespeeder** [comment]
@IntelOrca 
Why include the OpenRCT2 sequence including files:

- achilleshiel.sv6
- alexfablelake.SV6
- bigfoot.sv6
- Cypress Grove Title.sv6
- gymnasiast1.sv6
- gymnasiast2.sv6
- Ill Paradise.sv6
- mci.sv6
- netgrouppark.sv6
- pfckrutonium1.sv6
- phann.sv6
- poke.sv6
- rid6.sv6
- script.txt
- TaCW.sv6
- Title Sequence Park 1.sv6

I guess a good reason to include the sequences I am requesting as part of the build is to showcase *.SC6 usability as part of the sequence. Makes a great example of the feature.

**Comment by duncanspumpkin** [comment]
We distribute the OpenRCT2 title sequence as its a nice little presentation to show that there is a new major build. As for TT and WW scenarios we can't distribute a title sequence for them as a large amount of people will not have the scenarios.

**Comment by wildgoosespeeder** [comment]
@duncanspumpkin Wouldn't the title sequence not load anything if attempted to be selected, kind of like how the RCT1 title sequences are? In case you are wondering, I don't know how to set that up so that way the RCT1 title sequences will run properly. When I select one of those title sequences, nothing happens and the previously working sequence is selected instead.

**Comment by Gymnasiast** [comment]
Support for loading *any* scenario has been added by https://github.com/OpenRCT2/OpenRCT2/pull/6598.

Creating a title sequence that utilises it is out of our scope.
