### ISSUE TITLE
Multiplayer Crash

### ISSUE THREAD

**Issue by WhenPenguinsAttack** [OpenRCT2/OpenRCT2#3804]
**OS: Windows 7
**Version: v. 0.0.5 develop build 9b705c5

Explanation of the issue: Game crashes when joining some multiplayer games

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Join multiplayer servers such as manofteal.com and Freebuild Realistic, Autosave, Restart
2. Game crashes

**Dump file**
[e98f573d-4727-44e5-b00f-85180b607a3c(9b705c5).zip](https://github.com/OpenRCT2/OpenRCT2/files/296840/e98f573d-4727-44e5-b00f-85180b607a3c.9b705c5.zip)

**Save game:**

[e98f573d-4727-44e5-b00f-85180b607a3c.txt](https://github.com/OpenRCT2/OpenRCT2/files/296841/e98f573d-4727-44e5-b00f-85180b607a3c.txt)

**Comment by WhenPenguinsAttack** [comment]
Noticed some weirdness- there's a message saying the game has crashed, but if you ignore it, you can still play the game.

**Comment by Juli199696** [comment]
Noticed the same yesterday. Btw. the Freebuild server got the server version i got from @janisozaur as there was no patch for the server crashes.

**Comment by Ziscor** [comment]
It seems that the game does not crash every time. Also, among the open servers I see right now (Including Whiskey Station #1) all of them can crash you.

**Comment by WhenPenguinsAttack** [comment]
If you ignore the message, go into a server, leave that server, and try to go to another server, the game crashes for real.

**Comment by Juli199696** [comment]
Some of the devs should test the newest dev build and try to create server and join it
