### ISSUE TITLE
Other Coaster Vehicle options not showing in Ride Window

### ISSUE THREAD

**Issue by Ziscor** [OpenRCT2/OpenRCT2#3806]
**OS:** Windows 7
**Version:** 0.0.5 develop build 7e291c3

Taken from: https://openrct2.org/forums/topic/1345-i-have-this-bug-that-doesnt-seem-to-resolve-at-all/#comment-7265

When other coaster vehicle types are enabled in game, the first (or default) one is the only one available. Sometimes the drop down bar is available, but there are no other options in it, and other times it's locked altogether.

**Steps to reproduce:**
1. Enable more than one vehicle type for a roller coaster.
2. Build said roller coaster and check for other vehicle types in the ride window. 

Or, you can just open up Build Your Own Six Flags Park and build the Wooden Roller Coaster. The vehicle type is locked at Articulated Roller Coaster Trains.

Apologies if this has been reported already, but could not find anything relating to this.

**Comment by jensj12** [comment]
Probably related to #3681 (the part I couldn't reproduce)

**Comment by Liampie** [comment]
I was about to make a similar post. In my park I can't select any other trains, but as far as I've checked with all the rides it only happens if the track is invisible.

**Comment by Gameinsky** [comment]
There's a small workaround for it, you can import a ride that uses the wanted vehicle. However if you accidentally change it you'll be locked out of it again.

I think I figured out the cause of the issue though, it's probably not related to #3681.
Rather to the list of all vehicle types. Once there's too many vehicles the list reaches the bottom of the screen on a 1x resolution scale and any vehicle that doesn't make in the list on screen is undetectable.

**Comment by Gymnasiast** [comment]
Quote of X123M3-256:
> It seems ride_entry_is_invented incorrectly returns false - if you force it to always return true you can select the other vehicle types.

The commit that changed this: https://github.com/OpenRCT2/OpenRCT2/commit/aa929e1593e7a2adcc0c5886c2693c3e2ec407fa

**Comment by Generalcamo** [comment]
The strange thing is that alternate vehicles from RCT1 mode (like the Twister Trains) CAN be seen and selected. I don't think there is a size limitation here.
