### ISSUE TITLE
Tooltip delay

### ISSUE THREAD

**Issue by Phyxion** [OpenRCT2/OpenRCT2#3809]
Currently the tooltips are appearing instantly, a (slight) delay should be a great improvement.

**Comment by Goddesen** [comment]
This seems reasonable, but I am personally against it. You don't want tooltips popping up all over the place when you're just moving your mouse around somewhat erratically. Make it an option, maybe let you set the exact timing yourself?

**Comment by IntelOrca** [comment]
there was a delay in the original game, so this is just a bug

**Comment by Phyxion** [comment]
Yeah, I thought there used to be a delay indeed :)

**Comment by duncanspumpkin** [comment]
Might help in locating the issue this is where tooltip timeouts were last mentioned https://github.com/trigger-death/OpenRCT2/commit/dc38087f07c287e74bd700db80e845a6c0cfa025
