### ISSUE TITLE
Cheat to prevent excitement penalty on multiple rides of same type

### ISSUE THREAD

**Issue by WhenPenguinsAttack** [OpenRCT2/OpenRCT2#3812]
There's a cheat to reset all ride aging, but none to prevent it in the first place.  This would be very useful to prevent having to toggle this every few years.  A cheat to remove the penalty on ride excitement if multiple rides of the same type are built would also be really useful, especially in multiplayer parks.

**Comment by spacek531** [comment]
How would the "remove penalty on ride type" work, specifically with the caveat that multiple of the ride type have to be built?

**Comment by Nubbie** [comment]
#5196 **implemented**

**Comment by Gymnasiast** [comment]
@Nubbie Not all of it.

**Comment by Nubbie** [comment]
@Gymnasiast Changing title could be good with the missing part 👍

**Comment by Gymnasiast** [comment]
This is the kind of stuff that should go into a plug-in.
