### ISSUE TITLE
 Flickering Text on Cheat Window

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#3817]
**OS:**  Windows 10
**Version:** 0.0.5
**Commit:** 4f6929e

'Never-ending marketing campaigns' text on the cheat window sometimes flickers when changing the weather 

**Steps to reproduce:**
1. Open Cheat window
2. Keep changing the weather, notice how the text 'Never-ending marketing campaigns'  flickers occasionally

You may need to change the game speed for it to work 

**Screenshots / Video:**
![screen shot 06-04-16 at 02 45 pm](https://cloud.githubusercontent.com/assets/1381723/15799877/477fde12-2a63-11e6-97fe-056d18bb242c.PNG)

**Comment by Gymnasiast** [comment]
Probably an error with the width of the box (half-width instead of full width).
