### ISSUE TITLE
Single Player Crash

### ISSUE THREAD

**Issue by GForceNE** [OpenRCT2/OpenRCT2#3826]
**OS:** [Windows 10]
**Version:** [0.0.5 build 876]
**Commit:** [3b8f98c]

**Steps to reproduce:**
1. [Scroll to edge of map near Red Looping Coaster]

**Description**
Crash happens randomly and always near the edge of the map behind the red looping coaster near the water ride.  

**Dump file**
[d93ddf56-e482-4508-baa0-b3ebf274ca36.zip](https://github.com/OpenRCT2/OpenRCT2/files/299140/d93ddf56-e482-4508-baa0-b3ebf274ca36.zip)

**Save game**
[WoF600.zip](https://github.com/OpenRCT2/OpenRCT2/files/299435/WoF600.zip)

**Comment by Nubbie** [comment]
Got this from d93ddf56-e482-4508-baa0-b3ebf274ca36(3b8f98c).dmp

```
#1 openrct2.dll! DrawRLESprite2<0,1>(const unsigned char * source_bits_pointer=0x07c41851, unsigned char * dest_bits_pointer, const unsigned char * dpi=0x009ac128, const rct_drawpixelinfo * source_y_start=1, int height=11, int source_x_start=0, int width=8, int) Line 65	
#2 openrct2.dll! gfx_rle_sprite_to_buffer(const unsigned char * source_bits_pointer, unsigned char * dest_bits_pointer, const unsigned char * palette_pointer=0x00000000, const rct_drawpixelinfo * dpi=0x009ac128, int image_type=0, int source_y_start=-1, int height=13, int source_x_start=0, int width=8) Line 203	
#3 openrct2.dll! gfx_draw_sprite_palette_set(rct_drawpixelinfo * dpi=0x009ac128, int image_id, int x=567, int y=-6021, unsigned char * palette_pointer=0x00000000, unsigned char * unknown_pointer=0x00000000) Line 546	
#4 openrct2.dll! gfx_draw_sprite(rct_drawpixelinfo * dpi=0x009ac128, int image_id, int x=567, int y=-6021, unsigned int tertiary_colour=0) Line 358	
#5 openrct2.dll! paint_quadrant_ps(...) Line 955	
#6 openrct2.dll! viewport_paint(rct_viewport * viewport, rct_drawpixelinfo * dpi=0x000dfb60, int left=498, int top=-6138, int right, int bottom=-5198) Line 793	
#7 openrct2.dll! viewport_render(rct_drawpixelinfo * dpi=0x000dfb60, rct_viewport * viewport=0x6a65d4e0, int left=498, int top=28, int right=1138, int bottom=-5198) Line 691	
#8 openrct2.dll! window_editor_main_paint(rct_window * w=0x6a64a2c0, rct_drawpixelinfo * dpi=0x000dfb60) Line 96	
#9 openrct2.dll! window_draw(rct_window * w=0x6a64a2c0, int left=0, int top=28, int right=320, int bottom=690) Line 1543	
#10 openrct2.dll! gfx_redraw_screen_rect(short left=0, short top, short right, short bottom=690) Line 355	
#11 openrct2.dll! sub_6E7FF3(rct_window * window, rct_viewport * viewport=0x6a65d4e0, int x=320, int y=180) Line 367	
#12 openrct2.dll! sub_6E7FF3(rct_window * window=0x6a64ac50, rct_viewport * viewport=0x6a65d4e0, int x=320, int y=180) Line 339	
#13 openrct2.dll! sub_6E7FF3(rct_window * window=0x6a64a788, rct_viewport * viewport=0x6a65d4e0, int x=320, int y=180) Line 343	
#14 openrct2.dll! sub_6E7F34(rct_window * w=0x6a64a2c0, rct_viewport * viewport=0x6a65d4e0, short x_diff=320, short y_diff=180) Line 430	
#15 openrct2.dll! sub_6E7DE1(short x=498, short y=-6578, rct_window * w=0x6a64a2c0, rct_viewport * viewport=0x6a65d4e0) Line 502	
#16 openrct2.dll! viewport_update_position(rct_window * window=0x6a64a2c0) Line 628	
#17 openrct2.dll! window_update_all(...) Line 161	
#18 openrct2.dll! rct2_draw(...) Line 284	
#19 openrct2.dll! openrct2_loop(...) Line 458	
#20 openrct2.dll! openrct2_launch(...) Line 324	
#21 openrct2.dll! StartOpenRCT(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance=0x00000000, char * lpCmdLine=0x017c3bb5, int nCmdShow=10) Line 109	
#22 openrct2.exe!004069e4()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for openrct2.exe]	
 	[External Code]	

```

**Comment by mrtnptrs** [comment]
This map got seriously hacked/manipulated, probably with the tile inspector or a trainer:

![2016-07-14_17-07-23](https://cloud.githubusercontent.com/assets/4948213/16844480/9e829578-49e5-11e6-90b2-d2632c494323.png)
![2016-07-14_17-08-00](https://cloud.githubusercontent.com/assets/4948213/16844481/9e894f58-49e5-11e6-8598-a85b8e8e2dcd.png)

**Comment by mrtnptrs** [comment]
Using the tile inspector, it seems that the normal path and ground at the off-map sections are actually covered by an object called "scenery more". Removing this element at a tile can show the normal ground or path. But I couldn't reproduce a crash. But @GForceNE where did you get this save file from or did you manipulate the map yourself? Do you know how that was done?

![2016-07-14_17-28-55](https://cloud.githubusercontent.com/assets/4948213/16845926/d276d04c-49ea-11e6-87dc-ab308f314a7c.png)

**Comment by janisozaur** [comment]
@mrtnptrs you will see @GForceNE is one of NEDesigns' higher-ups, his parks (or the ones he submits) will surely be hacked in all sorts of ways, we strive to support them as properly as we can.

**Comment by mrtnptrs** [comment]
@janisozaur Haha, sorry, didn't see that. Maybe @GForceNE could explain to us which hacks he used to create this map (and how the hacks work) if he made the map himself? Then we can specifically look at the cause IF the hacks caused the crash.

**Comment by GForceNE** [comment]
Yes, the "off map" areas are simply lowered land with custom scenery objects on top of them made to mimic the edge of the map.

I seem to also be unable to reproduce the error as well now, not sure what was the case here.  It was a roadblock to me on this save for a few days.  Seemingly has gone away now.

In terms of hacks used, nothing to extreme.  Just the classic, invisible huts hack really (using 8cars and MOM/edit rides menu).  Thanks for you help guys, I'm sure I'll have more issues to report in the future, some hacks on NE are just silly.
