### ISSUE TITLE
TD4 and TD6 in Multiplayer

### ISSUE THREAD

**Issue by wildgoosespeeder** [OpenRCT2/OpenRCT2#3827]
Is there a reason that multiplayer doesn't allow the construction of *.td4 and *.td6 files?

**Comment by janisozaur** [comment]
yes

**Comment by wildgoosespeeder** [comment]
@janisozaur 
Care to explain?

**Comment by IntelOrca** [comment]
@wildgoosespeeder its just not been implemented yet. It will require sending it to the server and the server sending it to all clients.

**Comment by wildgoosespeeder** [comment]
@IntelOrca 
I have a work-around idea for a temporary solution. How about interpreting the TD4 and TD6 data as building instructions in the construction window instead of the track design selection window? The idea is that the game takes control of the construction window and builds the track slowly. The server then can't tell if it is a human or the program building the track. That way pre-builds can still be built without the need to implement what you said.

**Comment by IntelOrca** [comment]
@wildgoosespeeder and what happens if someone else builds something in the way in between those instructions? I don't think its full-proof.

**Comment by wildgoosespeeder** [comment]
@IntelOrca 
This is true with anything multiplayer and not specific to automated building.

Steps:
1. Reserve land where the player is planning on building (the "ghost" track pieces and white squares that are overlaid on top of the ground)
2. The game is capable of checking for "too high for supports" or if something is in the way before placing the prebuild. Check for that.
3. Once #1 and #2 are free of obstruction, then start the construction window.
4. Once building finishes, free up locked tiles.

**Comment by fromthere** [comment]
@wildgoosespeeder If client send lands to reserve and do nothing, land would remain locked.
if server desides to unlock tile after some time period, it's possible lock is unlocked while building.

**Comment by wildgoosespeeder** [comment]
@fromthere 
The land reserve is temporary for as long as the construction window needs to be open. This isn't OpenTTD where you buy land you will likely never use. Players can't (and shouldn't) control this directly. This is to prevent other construction during your construction. Yes, this can be abused, but if you suspect player abuse, when you decide to deny privileges or kick them, that's when unlocking should occur.

**Comment by duncanspumpkin** [comment]
Your idea has changed a one function modification into a multi function change with many edge cases. It would be vastly more complex then coming up with a solution for sending tracks to the server.

**Comment by IntelOrca** [comment]
There is nothing difficult about send the TD6, it just hasn't been done yet.

**Comment by wildgoosespeeder** [comment]
@duncanspumpkin @IntelOrca 
I am a bit curious, is there any progress sending TD4 and TD6 data more directly than my proposed work-around method?

**Comment by IntelOrca** [comment]
@wildgoosespeeder we will implement it as some point in the future.
