### ISSUE TITLE
Flying Roller Coaster Building Freezes The Game With Certain Pieces

### ISSUE THREAD

**Issue by wildgoosespeeder** [OpenRCT2/OpenRCT2#3828]
**OS:** Windows 8.1 Pro (64-bit)
**Version:**  0.0.5.0 build 3b8f98c
**Commit:** N/A

Building a Flying Roller Coaster, some piece selections are bugged and causes the game to freeze. My guess is incompatible pieces.

- [x] **Reproducible in RCT2 (vanilla)?**
No.
- [x] **Multiplayer?**
Both single player and multiplayer.

**Steps to reproduce:**
1. Build starting from scratch (don't confuse this with the lay-down roller coaster).
2. Select in-line twist (there are two lefts and two rights by the way) or vertical loop.
3. Watch the game freeze.

**Dump file**
[52f9a826-28ca-45cd-9dee-a146f1092be1(3b8f98c).zip](https://github.com/OpenRCT2/OpenRCT2/files/299495/52f9a826-28ca-45cd-9dee-a146f1092be1.3b8f98c.zip)

**Screenshots / Video:**
N/A

**Save game:**
[52f9a826-28ca-45cd-9dee-a146f1092be1(3b8f98c).zip](https://github.com/OpenRCT2/OpenRCT2/files/299495/52f9a826-28ca-45cd-9dee-a146f1092be1.3b8f98c.zip)

**Comment by X123M3-256** [comment]
What pieces are you trying to build and are they actually available on the flying coaster? There's a known bug where the ride construction window shows pieces that are not available.

**Comment by wildgoosespeeder** [comment]
@X123M3-256 I think we are thinking of the same thing. Comparison:
![scr9](https://cloud.githubusercontent.com/assets/18543809/15808340/20d4fd96-2b3b-11e6-9b8a-3833761ae977.png)

**Comment by Wirlie** [comment]
Again, duplicate of #3564 (https://github.com/OpenRCT2/OpenRCT2/issues/3564#issuecomment-220119402)

**Comment by wildgoosespeeder** [comment]
OK, I duplicated this issue. I'll close and let someone tie in the related issue because I found that the Flying Coaster is affected.
