### ISSUE TITLE
Multiplayer - Tracked Rides Alternate Color Painting Doesn't Show Changes to Other Clients

### ISSUE THREAD

**Issue by wildgoosespeeder** [OpenRCT2/OpenRCT2#3832]
If this is a duplicate, sorry!

**OS:** Windows 8.1
**Version:** 0.0.5
**Commit:** 3dc4b601b8327082c5f5b022c4713d62ce2fa1a5

When painting pieces of a tracked ride an alternate color, this data doesn't get sent to the server and other clients connected.
- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Build a tracked ride in multiplayer
2. Define an alternate color scheme
3. Paint a piece of the tracked ride with the alternate color scheme
4. Others can't see the change but you can

**Dump file**
N/A

**Screenshots / Video:**
N/A

**Save game:**
N/A

**Comment by Generalcamo** [comment]
More info: If you join a server, paint the ride, disconnect from the server, and re-join the server, you also cannot see the alternate colors.

**Comment by Nubbie** [comment]
Wonder if it would be able to sync properly

**Comment by Emonadeo** [comment]
Came here to make aware that this issue is still present to date. Though it's not a major bug I think it's worth fixing.
