### ISSUE TITLE
Permission denied after saving multiplay map

### ISSUE THREAD

**Issue by YJSoft** [OpenRCT2/OpenRCT2#3833]
**OS:** Windows 7
**Version:** 0.0.5
**Commit:** 84334c1

Permission denied error messsage appears after saving multiplay map

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Try to save multiplay map
2. Permission denied error shows but save is done without any error

**Comment by YJSoft** [comment]
when save, command id 67 is sent to server. since there's no such id, server will return "No permission".

**Comment by duncanspumpkin** [comment]
@IntelOrca was this ever fixed.

**Comment by IntelOrca** [comment]
I don't remember, it was quite annoying so I am sure we would of heard more complains if it still happened. It can be re-opened if necessary.
