### ISSUE TITLE
Multiplayer Host Crashing Randomly Issue

### ISSUE THREAD

**Issue by kirano9** [OpenRCT2/OpenRCT2#3834]
**OS:** [Windows 7 Home Premium x64]
**Version:** [e.g. 0.0.5]
**Commit.** [3b8f98c]

- [ ] Reproducible in RCT2 (vanilla)? No
- [x] Multiplayer? Yes

**Steps to reproduce:**
Not sure what the cause is...

**Dump file**
[Dump File.zip](https://github.com/OpenRCT2/OpenRCT2/files/303327/Dump.File.zip)

**Save game:**
[Kiran and Mark SandBox - Copy.txt](https://github.com/OpenRCT2/OpenRCT2/files/303334/Kiran.and.Mark.SandBox.-.Copy.txt)

Issue is that at random points the game will crash out of the blue for the host. I cannot see a cause and there is no correlation into the times when the crash occurs. The program simply closes down and creates the dump file at random points when playing multiplayer with 1 friend.

**Comment by Nubbie** [comment]
**TO DEVS;**

**Error Message:**
Unhandled exception at 0xDD048B01 in 2e3f5cc8-bdb4-4e92-ac9e-68302f907285(3b8f98c).dmp: 0xC0000005: Access violation reading location 0xDD048B01.


**Call Stack;,**
```
 	dd048b01()	Unknown
 	[Frames below may be incorrect and/or missing]	
>	openrct2.dll!window_draw(rct_window * w=0x52c2a2c0, int left=0, int top, int right, int bottom) Line 1543	C
 	openrct2.dll!gfx_redraw_screen_rect(short left=0, short top, short right, short bottom=448) Line 355	C
 	openrct2.dll!gfx_draw_dirty_blocks(int x=0, int y=0, int columns=2, int rows=7) Line 325	C
 	openrct2.dll!gfx_draw_all_dirty_blocks(...) Line 296	C
 	openrct2.dll!window_update_all(...) Line 161	C
 	openrct2.dll!rct2_draw(...) Line 284	C
 	openrct2.dll!openrct2_loop(...) Line 458	C
 	openrct2.dll!openrct2_launch(...) Line 324	C
 	openrct2.dll!StartOpenRCT(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance=0x00000000, char * lpCmdLine=0x016b4f9f, int nCmdShow=1) Line 109	C
 	openrct2.exe!004069e4()	Unknown
 	[External Code]	
```

**Locals;**
```
		bottom	Error reading register value.	
		copy	Variable is optimized away and not available.	
		left	0	int
		overflow	0	int
		right	Error reading register value.	
		top	Error reading register value.	
+		v	0x52c26634 {openrct2.dll!rct_map_element _tempTrackMapElement} {event_handlers=0x89808f0a {close=??? ...} ...}	rct_window *
+		w	0x52c2a2c0 {openrct2.dll!rct_window g_window_list[64]} {event_handlers=0x52b9c558 {openrct2.dll!rct_window_event_list window_main_events} {...} ...}	rct_window *
```

**Comment by duncanspumpkin** [comment]
Game has been made considerably more robust since this build and the save does not crash so I'm going to close this.
