### ISSUE TITLE
Crash at boot.

### ISSUE THREAD

**Issue by mitchellcrazyeye** [OpenRCT2/OpenRCT2#3837]
**OS:** [Windows 10]
**Version:** [0.5.0]

I try to boot OpenRCT2, and it crashes at boot with this error message;
![error](https://cloud.githubusercontent.com/assets/19811106/15881886/36052c16-2cff-11e6-85dd-0b18e754b3b8.png)
EDIT: I have tried to use both the "Ignore" and "Retry" buttons. The ignore button just brings me to another error, and the retry just breaks it completely.
Before you ask me to verbose it, I did it already. No, it didn't come up with any details of an error. Just "VERBOSE: finished loading required objects"
If you need anymore details, Let me know.

**Comment by IntelOrca** [comment]
Could you try running `openrct2.exe <scenario path>`, preferably an official scenario like Crazy Castle.

When did this start happening? After a certain update?
What title sequence do you have set?
Are there any custom objects you added recently?

**Comment by mitchellcrazyeye** [comment]
1. I am new to this. I just downloaded the installer, and installed OpenRCT2. I was never able to open the program, so I did not add anything to it.
2. How do you run the sequence path? Like I said, I am new to this, and would really like an example to use.
"When did this start happening? After a certain update?" I was never able to get it to work.
"What title sequence do you have set?" What is a title sequence?
"Are there any custom objects you added recently?" Definitely not.

Again, I am open for any suggestions or ideas anyone may have.

**Comment by IntelOrca** [comment]
Like how you ran it with `--verbose`, you can tell it to open a park. Either by dragging a scenario or saved game over the executable in explorer or by passing it the path to the scenario / saved game file as the first argument on command line.

Where did you get RCT2 from? CD, Steam, GOG?
Have you installed custom objects in RCT2, or downloaded and played saved games from the internet?

**Comment by mitchellcrazyeye** [comment]
Can you please give me an example code to run. I don't know where the scenario and saved games are. I got RCT2 from the trial version from the website.Again, no. I didn't install any custom objects. No there is no dump files for any of the crashes

**Comment by IntelOrca** [comment]
@mitchellcrazyeye do you still get this issue?

**Comment by Nubbie** [comment]
@mitchellcrazyeye Still having this issue? :) 
_(or else this maybe should get closed)_

**Comment by mitchellcrazyeye** [comment]
Might be a good idea just to close it

**Comment by janisozaur** [comment]
Code has moved to https://github.com/OpenRCT2/OpenRCT2/blob/1f0adb95da2947ac87003a9bba6702ea559e8974/src/drawing/sprite.c#L524

I recall seeing it somewhere, but search returns nothing.

**Comment by Nubbie** [comment]
@janisozaur 
As the code is moved and Mitchellcrazyeye suggested it being closed, should we close it?
The code has been heavily modified since it opened
