### ISSUE TITLE
Chains can be set on stores if 'Allowing chain lifts for all pieces' is on

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#3839]
**OS:** Win 7 
**Version:** 0.0.5
**Commit:** [e.g. 628e263094444f1da1f9be9c30336bf209c70491]

When Pr #3818 got merged, you're able to put 'chains' on everything the build window touches, including stands and stores

**Screenshots / Video:**
![khghkgkhg](https://cloud.githubusercontent.com/assets/17282384/15898195/8d67014e-2d97-11e6-9a74-9a8ead17a0e0.png)

**Comment by janisozaur** [comment]
This s hilarious

**Comment by Goddesen** [comment]
Does this... do anything?

**Comment by Nubbie** [comment]
To my knowledge, no
