### ISSUE TITLE
Version number not up to date

### ISSUE THREAD

**Issue by wilfreddijksman** [OpenRCT2/OpenRCT2#3842]
**OS:** OS X 10.11.5 (15F34)
**Version:** 0.0.5-develop-426e106

The version number of the build is not filled in in the OS X menu bar: OpenRCT2 -> About OpenRCT2 and in file properties of the binary: OpenRCT2.app -> Show info -> Version

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
In the OS X menu bar:
1. OpenRCT2
2. About OpenRCT2
3. See version number in info window
In file properties of the binary:
1. Go to OpenRCT2.app
2. Right click: Show info
3. See version number in info window

**Screenshots / Video:**
![About window](https://cloud.githubusercontent.com/assets/1773594/15907793/e0e6ec2c-2dbe-11e6-9ec0-f2603d08aeec.png)
![File properties window](https://cloud.githubusercontent.com/assets/1773594/15907792/e0ae752c-2dbe-11e6-83f2-beb2ebcef314.png)

**Comment by Gymnasiast** [comment]
@LRFLEW Could you look into this?

**Comment by LRFLEW** [comment]
I know exactly what this is. In the Info.plist file, there's a place for the version number, which is what's accessed in these places. When I was originally making the .app bundle, I left this at its default value, as the game says what version it is itself, so it wasn't a high priority. If someone wants to edit and maintain the `CFBundleShortVersionString` and `CFBundleVersion` attributes in the Info.plist file, go ahead, but I personally don't consider this a bug.

**Comment by IntelOrca** [comment]
Can we not get the CI to generate or modify the Info.plist automatically?

**Comment by marijnvdwerf** [comment]
```
plutil -replace CFBundleShortVersionString -string "74780b3" ./distribution/osx/Info.plist 
plutil -replace CFBundleVersion -string "0.0.5-dev" ./distribution/osx/Info.plist
```

![image](https://cloud.githubusercontent.com/assets/737603/15915439/8a952750-2de9-11e6-9b81-718437c99b04.png)
![image](https://cloud.githubusercontent.com/assets/737603/15915445/9a8fb2e2-2de9-11e6-9b23-a4dc57230c2c.png)

**Comment by LRFLEW** [comment]
I'd actually flip those. Make `CFBundleShortVersionString` `0.0.5-dev` and CFBundleVersion `74780b3`. I think that's what intended with those parameters.

**Comment by Gymnasiast** [comment]
@LRFLEW @marijnvdwerf Could either of you pick this up when you have some free time? It's not terribly high priority but still something to fix.

**Comment by LRFLEW** [comment]
You know, with the code added to the Xcode project in #4194, it might be really simple to integrate this into the project itself. I'll take a look at this soon and see how feasible it is.

**Comment by duncanspumpkin** [comment]
@LRFLEW did this ever get fixed.

**Comment by marijnvdwerf** [comment]
Nope

**Comment by LRFLEW** [comment]
It's just be low-priority for me (and I would have marked this "Will Not Fix" if it were up to me 😜). I can set it as my next priority after #4490.

**Comment by LRFLEW** [comment]
Ok, real quick update on this: I have it half-working.

So using the command-line suggested by @marijnvdwerf and reusing the "Get Git Variables" build stage, I was able to get the `CFBundleVersion` parameter set to the git commit short hash. However, the `CFBundleShortVersionString` will be a bit more of a hassle. Specifically, there is nothing in the environment (as far as I know) that has the version number. I can add it, but it would be hardcoded, and would have to be incremented manually when the version number gets bumped. (Basically, any time the `OPENRCT2_VERSION` macro gets updated, the Info.plist file needs to be updated).

Any particular thoughts on this?
