### ISSUE TITLE
Being able to report bugs/issues from the OpenRCT2 website

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#3845]
Having a tab on the website so you can report bugs there would be easier to get more reports in as not many in the community probably has Github, would combine this with #3329 

This way you can have dropdown for OS, build etc and in the end, it just transforms it into pure text that can be posted by a user here on the issue tab on GitHub

**Pros:**
+More reports
+Easier to use for everyone
+No accounts
+Easier to find
+Correct fill out of the 'issue form'

**Cons:**
-More reports
-Someone has to post them on GitHub (if it isn't public so anyone can)

**Comment by janisozaur** [comment]
I'm against that. If the user is too lazy to report an issue back to us (we already keep tabs on openrct2.com, reddit and other places), they *should* deal with bugs.

**Comment by Gymnasiast** [comment]
There is a case to be made for extra instructions on ORG to guide people a bit. In the end I feel it's better if people report here directly, it makes it far easier for us to keep track of bugs and solve then.

I don't think people not reporting here is down to laziness. Some people are simply less computer proficient and calling them lazy is not correct IMO.

**Comment by IntelOrca** [comment]
The problem is that often people don't provide enough information or we need to ask them for more information. Therefore having them connected to the GitHub issue where they can respond and be notified is much better.

**Comment by Nubbie** [comment]
@janizaurus
Most players don't have a GitHub account in my experience as they are gamers and not programmers, information could be useful at least :)

@Gymnasiast
Would agree with info could be needed, this 'idea' could instead maybe convert into 
'Getting a support tab on the website with a information box telling people to report bugs and issues on GitHub' :)

@Intelorca
The forms would be fully filled, the problem is how you can't get additional information, GitHub probably would be the best way to deal with this :)

P.S: Thinking about changing this issue to be included in the other issue, thinking if it would be enough to just have:

Header: Found a bug?
Please report bugs on GitHub (link) with attached dumpfiles bla bla bla

_(On the phone)_

**Comment by Ziscor** [comment]
You could ask the admins over at the forums to make it so that any new topic on the Bugs, Problems and Feedback page is automatically notified to you, like having all developers' accounts there follow that topic instantly. Only certified developers only.

We'll ask them for extra information before you see the issue, like save files, dump log or more. It might at least ease the problems for you all.
