### ISSUE TITLE
Testing or opening (certain) rollercoaster causes game to hang

### ISSUE THREAD

**Issue by PureTryOut** [OpenRCT2/OpenRCT2#3846]
**OS:** (GNU/)Linux, both Arch Linux and Ubuntu 16.04
**Version:** 0.0.5-develop
**Commit/Build:** https://github.com/OpenRCT2/OpenRCT2/commit/27b3c71588ef583c8efc5adf4a5cfa10a145e893

When trying to test or open a suspended swinging coaster, the game hangs and forces me to quit the game. The rollercoaster has all valid track pieces, nothing that shouldn't belong there. This started happening about 2-3 weeks ago and still happens today (with the latest development build).

**Steps to reproduce:**
1. Load provided save
2. Test or open the built suspended swinging coaster

**Save game:**
[Sandbox.txt](https://github.com/OpenRCT2/OpenRCT2/files/307358/Sandbox.txt)

**Comment by jensj12** [comment]
It doesn't hang with just one train.

**Comment by PureTryOut** [comment]
Interesting, I had not tested it that far. You are right, it seems to work fine with just 1 train.
