### ISSUE TITLE
Filling in ride creators name automatically in multiplayer

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#3847]
Simple, but, know there is a limit off characters out there

All it needs to do is check the games network status and if it's multiplayer, fills in with the grey font the initials, first letters or whole name (if possible to fit)

![hgfghj](https://cloud.githubusercontent.com/assets/17282384/15940625/28587530-2e7d-11e6-8d58-2107fa7fb876.png)

**Comment by IntelOrca** [comment]
`Colossus (Track 1)` - Yeah, its not worth it IMO.

**Comment by IntelOrca** [comment]
Maybe in the future when we can attach some extra data to rides, we can have some author metadata.
