### ISSUE TITLE
Client crash when hiring certain staff in Multiplayer

### ISSUE THREAD

**Issue by raidcookie** [OpenRCT2/OpenRCT2#3848]
**OS:** Windows 7 x64
**Version:** 0.0.5-dev
**Commit/Build:** 1761907

After updating to yesterday's new multiplayer build, I get a crash whenever I want to hire staff as a client.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Join any multiplayer game as a client (preferrably as Super-User)
2. Hire a Mechanic or Entertainer

**Dump file**
[545099c4-92e3-4377-846b-5a84e0f6763b(1761907).zip](https://github.com/OpenRCT2/OpenRCT2/files/307617/545099c4-92e3-4377-846b-5a84e0f6763b.1761907.zip)

**Comment by Nubbie** [comment]
I presume it's after a de-sync? 
As hiring staff etc doesnt work after de-syncs as clients

**Comment by IntelOrca** [comment]
Moving and hiring staff and peeps is not yet supported in Multiplayer, see #1943.

**Comment by raidcookie** [comment]
Hmm, odd, it worked before though.

**Comment by IntelOrca** [comment]
Its not supported meaning, we aren't looking at fixing the issues at the moment. Thus you have to make to do with it being "buggy".
