### ISSUE TITLE
Background for chat + new line (Length limit before 'next row')

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#3849]
The chat can sometimes be hard to read, especially when you use snow texture, getting a grey background would help a lot (when the chat is open)

Another problem is that there isnt a length limit so you can type all the way to the edge of the screen, would recommend it goes to 'a new line', like Minecraft

rct_drawpixelinfo
_chatRight = 600;

Color: 
// Background
``gfx_fill_rect(dpi, _chatLeft, _chatTop, _chatRight, _chatBottom, 0x2000000 | 50);  # 0x2000000 | 50); ``= Transparent gray

**How it's now:** 
![pure text](https://cloud.githubusercontent.com/assets/17282384/15941827/29b71df0-2e82-11e6-935b-4f39c824ed6c.jpg)

**My suggestion:** 
![examples](https://cloud.githubusercontent.com/assets/17282384/15941832/2e5c067c-2e82-11e6-93d1-ec831cf97fac.png)

**Comment by Patrik356b** [comment]
It should split before the overflow of the next word by the standard delimiters such as (semi-) colon, dot and comma

**Comment by IntelOrca** [comment]
I agree with this, perhaps make a pull request for it?

**Comment by Nubbie** [comment]
Wish I could program

**Comment by IntelOrca** [comment]
@Nubbie you have found `gfx_fill_rect` etc. so that's a good start. Just prevail onwards.

**Comment by Nubbie** [comment]
@IntelOrca If I'm allowed to make a PR that will take some weeks to finish probs :p

**Comment by Patrik356b** [comment]
I'm not sure if it should split words using dashes, or not, i.e. "as-is"
