### ISSUE TITLE
Place path through object does not remove object on server

### ISSUE THREAD

**Issue by YJSoft** [OpenRCT2/OpenRCT2#3852]
**OS:** OS X
**Version:** 0.0.5
**Commit/Build:** 504e5e0

Place path through object only removes object on client side, not server side.
- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Screenshots / Video:**
1. Building path on server, watching on server(works fine)
   ![image](https://dl.dropboxusercontent.com/s/yt7njkrb3jmvifi/26D3EB42-BA0E-4F90-B1EE-C6C04B53E8A3-4382-00006E7162A94C98.gif?dl=0)
2. Building path on server, watching on client(object not deleted - reconnect solves problem)
   ![image](https://dl.dropboxusercontent.com/s/hfq41qzwkb9b2ru/98A3C180-1A5D-4C13-A4C5-F43626E99C1E-4382-00006E7FE578ACD4.gif?dl=0)
3. Building path on client without any permission, watching on client(although fence is removed, since client has no permission so there's no effect to server)
   ![image](https://dl.dropboxusercontent.com/s/l39h1ej647ceqah/19C22ACD-7078-45A3-9FCF-45769F93485E-4382-00006E8C977E0825.gif?dl=0)
4. Building path on client with permission, watching on client(looks fine, but after reconnect object is still there)
   ![image](https://dl.dropboxusercontent.com/s/xkq7ln5lokvcnt3/F10B9BF0-886B-4B29-98F1-E40B731F30B7-4382-00006E9D53433721.gif?dl=0)
5. Building path on client with permission, watching on server(result is same to 2.)
   ![image](https://dl.dropboxusercontent.com/s/qwfskp0gs73jjj0/828FB9ED-43DF-4F60-BF16-496702FC10B2-4382-00006EAD968DF569.gif?dl=0)

**Comment by janisozaur** [comment]
I have tested it on recent version (around abad7dd or a few commits earlier) and it doesn't seem to happen any more.

I'd like some independent confirmation this is really gone before closing though.

One thing that stood out to me and perhaps hid this bug, is that I could not build a path with the arrow buttons, but only by placing each path element explicitly with mouse cursor.

**Comment by Broxzier** [comment]
@janisozaur https://github.com/OpenRCT2/OpenRCT2/pull/5080 fixed this.

**Comment by janisozaur** [comment]
I'm not sure if the version I tested already had that in, would be worth checking

**Comment by IntelOrca** [comment]
@Broxzier the issue said nothing about disable clearance checks

**Comment by janisozaur** [comment]
There's also a park reproducing the issue attached in https://github.com/OpenRCT2/OpenRCT2/issues/5459#issuecomment-300583403

**Comment by rwjuk** [comment]
Interestingly, on macOS on the latest build I cannot replicate this. The client doesn't delete the fence and no desync occurs.
