### ISSUE TITLE
Unselectable tile bug

### ISSUE THREAD

**Issue by liny-odell** [OpenRCT2/OpenRCT2#3853]
**OS:** Windows 7
**Version:** 0.0.5-develop
**Commit/Build:** af0f77e

Using the tile inspector and inserting an invalid tile then lowering its order to below the surface makes the tile no longer selectable and produces a graphical glitch.

**Screenshots / Video:**
![openrct2 invalid tile glitch](https://cloud.githubusercontent.com/assets/7400549/15956153/53ad8a04-2e9b-11e6-81a7-9d07bb4af15f.png)

**Comment by Gymnasiast** [comment]
That's expected when you insert a corrupt tile: it makes the tile above it invisible.

**Comment by liny-odell** [comment]
I can understand that, but imo being un-selectable feels like a bug as there is now no way to remove it

**Comment by Gymnasiast** [comment]
Yes, the unselectable part needs looking at.

**Comment by liny-odell** [comment]
Or at the very least, prevent it from being moved below the ground maybe.

**Comment by IntelOrca** [comment]
Maybe it's overflowing, have you checked if its very high up in the air?

**Comment by liny-odell** [comment]
Zooming the view way out and rotating to be able to maybe see it shows nothing floating in the air that I can see. If wanted I can upload the save.

**Comment by duncanspumpkin** [comment]
Yes that is how the corrupted item works. You can't select it because nothing is drawn. With nothing drawn the function that works out if you clicked on something can't see anything.

**Comment by liny-odell** [comment]
I understand that this is supposed to be intended, but this also means that one can add graphical problems that can not be removed, kind of breaking the save.

**Comment by IntelOrca** [comment]
@Broxzier's new improvements to tile inspector allow you to move the currently selected tile with X, Y spinners. This should solve this issue when it gets merged.

**Comment by liny-odell** [comment]
Ah that's good to hear, can't wait till that happens.

**Comment by janisozaur** [comment]
One way to work around that would be to build something on that tile (think: coaster or path using the arrow buttons or large flat ride…) and then select the tile. While not ideal, this could allow you to fix it now.

**Comment by liny-odell** [comment]
Thanks for the suggestion, but unfortunately it didn't work, I'll just wait for the improved tile inspector to fix my save then.

**Comment by duncanspumpkin** [comment]
If you need your save fixed in the mean time it wouldn't be hard for any of the devs to change that one tile

**Comment by liny-odell** [comment]
Thanks for the offer but its more of a visual breakage, everything still works just fine.
