### ISSUE TITLE
Save Game causes Crash

### ISSUE THREAD

**Issue by GForceNE** [OpenRCT2/OpenRCT2#3856]
**OS:** [Windows 10]
**Version:** [0.0.5]
**Commit/Build:** [304d797/895]

[Save Game Causes Crash]

**Steps to reproduce:**
1. [Load Saved Game]

**Dump file**
[No dump file created]

**Save game:**
[[Southport Pleasure Beach.zip](https://github.com/OpenRCT2/OpenRCT2/files/310410/Southport.Pleasure.Beach.zip)]

**Comment by janisozaur** [comment]
Where do you get commit like 895 from?

**Comment by GForceNE** [comment]
895 is the build, 304d797 is the commit

**Comment by janisozaur** [comment]
Still, where you get this build version from?

**Comment by GForceNE** [comment]
Launcher, set to most recent.
