### ISSUE TITLE
Tree Sprite Glitch

### ISSUE THREAD

**Issue by chrismilne300** [OpenRCT2/OpenRCT2#3859]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 3266867

The bottom of the honey locust tree is missing in OpenRCT2 and it doesn’t place in the centre of the tiles anymore.

**Screenshots / Video:**
RCT2:
![screen shot 06-12-16 at 09 26 am](https://cloud.githubusercontent.com/assets/1381723/15990013/690ea86a-3080-11e6-9374-6f0a2c4cb686.PNG)

OpenRCT2:
![screen shot 06-12-16 at 09 28 am](https://cloud.githubusercontent.com/assets/1381723/15990014/7c2dddb2-3080-11e6-923b-13d3e2d8d4b8.PNG)

**Comment by chrismilne300** [comment]
After a bit more testing I've found the issue on a number of tree sprites 


RCT2:
![screen shot 06-12-16 at 09 46 am](https://cloud.githubusercontent.com/assets/1381723/15990146/c4e5518c-3082-11e6-9ca0-e92973431e63.PNG)

OpenRCT2:
![screen shot 06-12-16 at 09 45 am](https://cloud.githubusercontent.com/assets/1381723/15990142/b9c4b036-3082-11e6-90c0-74f96b791215.PNG)

SaveFile:
[Crazy Castle.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/310688/Crazy.Castle.sv6.txt)

**Comment by jensj12** [comment]
The problem is that the surface tile is drawn over it, the same happens with one of the big jungle trees.

**Comment by duncanspumpkin** [comment]
Yes will be caused by a bounding box mistake

**Comment by Nubbie** [comment]
Noticed it's not just for trees, found this building doing the same thing
![china](https://cloud.githubusercontent.com/assets/17282384/15992098/2108727c-30c5-11e6-9b1f-076d07e7edcc.png)

**Comment by IntelOrca** [comment]
I raised this in chat awhile a go, all large scenery objects suffer from this.
