### ISSUE TITLE
Crash when trying to pick openGL in the settings for rendering.

### ISSUE THREAD

**Issue by liny-odell** [OpenRCT2/OpenRCT2#3867]
**OS:** Windows 7
**Version:** 0.0.5-develop
**Commit/Build:** 79c8455

Instant crash when selecting openGL for rendering.
GPU is Intel HD3000 which has openGL up to 3.1

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1: launch OpenRCT2
2: Open prefs and pick openGL for rendering.
3: BOOM.

**Dump file**
Sorry for dropbox link but Github is saying that they dont support the file type (zip file) when it is a zip file. https://www.dropbox.com/s/91xhngr8l6bkz6b/0afebf5a-d436-4a08-9e5a-bb4997a0d1de%2879c8455%29.zip?dl=0

**Save game:**
Not sure if relevant as it was at the main menu but: https://www.dropbox.com/s/ymcy5epk532qndu/0afebf5a-d436-4a08-9e5a-bb4997a0d1de.zip?dl=0

**Comment by liny-odell** [comment]
The text in the command prompt output is:
Failed to load glActiveTexture.
Dump Path: C:\Users\USERNAME\Documents\OpenRCT2\
Dump File Path: C:\Users\USERNAME\Documents\OpenRCT2\02d7d93e-1915-4bd4-a603-eca21f
3548e5(79c8455).dmp
Dump Id: 02d7d93e-1915-4bd4-a603-eca21f3548e5
Version: 0.0.5
Commit: 79c8455

**Comment by IntelOrca** [comment]
The minimum OpenGL requirement is 3.3, however it shouldn't crash but instead fallback to software - so I will investigate this.

@janisozaur @LRFLEW OpenGL 3.1, is it worth trying to support that?

**Comment by janisozaur** [comment]
I tested briefly on Intel with 3.1 context (simply changed the minor version) and it worked, but I'm not sure if this is all correct, as GL 3.1 didn't have `Core Profile` just yet, only `full context` and `forward-compatible context` (https://en.wikipedia.org/wiki/OpenGL#OpenGL_3.1).

**Comment by janisozaur** [comment]
@liny-odell can you check if https://ci.appveyor.com/api/buildjobs/o3o2hel6jdyvg284/artifacts/artifacts/openrct2.zip works for you?

**Comment by liny-odell** [comment]
It works, no crash but has some artifacts and really slow FPS

I understand intel isnt the best for rendering, but I can get more FPS in newly released games so that low seems odd to me.

![openrct2 opengl rendering bug](https://cloud.githubusercontent.com/assets/7400549/16005629/16d34f90-311d-11e6-9edb-efce3c1db3f2.png)

**Comment by liny-odell** [comment]
Is the transparency of the buttons on the main menu intended in this case?

**Comment by Nubbie** [comment]
@liny-odell OpenGL has some problems and are in a really new state, the buttons that are transparent is one of the things
For a full list off the bugs; https://github.com/OpenRCT2/OpenRCT2/wiki/OpenGL-renderengine-issues

**Comment by IntelOrca** [comment]
@liny-odell Does it still crash for you when you try to select OpenGL in the latest version?

**Comment by Patrik356b** [comment]
@Nubbie they are transparent by default but not as much afaik.

**Comment by liny-odell** [comment]
@IntelOrca no, it does not anymore. One thing I may suggest is see if the previous setting can be remembered and switch back to that instead of defaulting to software only.
Tested on version 389ae72
