### ISSUE TITLE
Alt+tabbing in Linux makes RCT not fullscreen

### ISSUE THREAD

**Issue by rbozan** [OpenRCT2/OpenRCT2#3871]
**OS:** Arch Linux (Antergos)
**Version:** 0.0.5 (latest)
**Commit/Build:** 7a7813693c18933d7770eeb59c49e86a92c667d2

OpenRCT2 is moved downwards when you ALT + TAB back to OpenRCT2.

**Steps to reproduce:**
1. Start OpenRCT2 and make sure you are fullscreen.
2. ALT + TAB
3. Go back to OpenRCT2
4. Notice that the toolbar from GNOME at the top of the screen is still visible and OpenRCT2 is moved a little bit downwards.
5. Go to options, select windowed mode and then back to fullscreen. It's now fixed, until you execute step 2 + 3 again.

**Comment by IntelOrca** [comment]
Is this in our control or an SDL2 bug?

**Comment by w-flo** [comment]
This might actually be a Gnome/mutter bug: https://gitlab.gnome.org/GNOME/mutter/issues/397

I believe it was fixed at some point (in 2017?), but then there was a regression and it's probably broken again right now. At least for me.

As a workaround, I can use the windows (super) key to open the Gnome expose view, then switch between normal windows and the OpenRCT2 fullscreen window a few times and it eventually fixes itself.

**Comment by Gymnasiast** [comment]
Can no longer reproduce this with OpenRCT2 v0.3.4.1, on Ubuntu 20.04 running GNOME 3.36.8.
