### ISSUE TITLE
No sound in Linux

### ISSUE THREAD

**Issue by rbozan** [OpenRCT2/OpenRCT2#3872]
**OS:** Arch Linux (Antergos)
**Version:** 0.0.5
**Commit/Build:** 7a7813693c18933d7770eeb59c49e86a92c667d2

There's no audio output. I don't hear music, nor do I hear sound effects. I built OpenRCT2 from the AUR package [openrct2-git](https://aur.archlinux.org/packages/openrct2-git/).

The console outputs this:
> LSA lib dlmisc.c:254:(snd1_dlobj_cache_get) Cannot open shared library /usr/lib32/alsa-lib/libasound_module_pcm_pulse.so

Even though I have installed the correct package (lib32-alsa-plugins) and I can confirm libasound_module_pcm_pulse.so is in the correct directory.

![Directory](https://cloud.githubusercontent.com/assets/7997154/16016354/f45c3d04-319a-11e6-89fe-9cc4c5943abd.png)

**Steps to reproduce:**
1. Start OpenRCT2
2. Go to settings, and check if sound is enabled and volume is on max
3. Notice that the audio is not working.

**Comment by IntelOrca** [comment]
> [Fill in the placeholders below. Delete any headings and placeholders that you do not fill in. Delete this line as well]

Why did you not delete that line like it says?

**Comment by rbozan** [comment]
Was writing some more info, sorry ^^

**Comment by janisozaur** [comment]
Do you have `lib32-libpulse` installed?

**Comment by rbozan** [comment]
`Do you have lib32-libpulse installed?`
I did not have this installed, however after installing the sound worked. :+1:
