### ISSUE TITLE
Can't deselect 'nearby scenery'

### ISSUE THREAD

**Issue by jensj12** [OpenRCT2/OpenRCT2#3877]
**OS:** Windows 10
**Version:** 0.0.5-dev
**Commit/Build:** fc78901

Deselecting automatically selected scenery while saving  track design doesn't properly deselect them, they are still included in the track design.

Not reproducible in RCT2 (vanilla)

**Steps to reproduce:**
1. Save a track design with scenery
2. Click the 'select nearby scenery' button
3. Deselect some of the auto-selected scenery items
4. Save the track
5. Place the saved track design, which includes the pieces you've deselected

**Screenshots / Video:**
Clicked 'select nearby scenery'
![scr118](https://cloud.githubusercontent.com/assets/13868449/16040036/93639c2a-322d-11e6-982b-1d520a0b52a2.png)

Deselected some items and clicked save afterwards
![scr119](https://cloud.githubusercontent.com/assets/13868449/16040033/912edafa-322d-11e6-9489-47a02d00a41e.png)

Placing the saved track design
![scr120](https://cloud.githubusercontent.com/assets/13868449/16040031/8f6bc08e-322d-11e6-8088-1937135228b4.png)

**Comment by duncanspumpkin** [comment]
No longer happens in latest build
