### ISSUE TITLE
ObjData Folder - New Feature

### ISSUE THREAD

**Issue by wildgoosespeeder** [OpenRCT2/OpenRCT2#3879]
This is just a pet peeve of mine but I kind of want to keep the vanilla RCT2 installation untouched. Many multiplayer servers use custom content. One problem of OpenRCT2 is that it installs the custom objects in the vanilla RCT2 directory instead of some other directory. I was wondering if OpenRCT2 can be programmed to point to an additional directory so that way custom content can be installed separated from vanilla RCT2.

**Comment by IntelOrca** [comment]
This is planned.

**Comment by wildgoosespeeder** [comment]
@IntelOrca Is it possible now?

**Comment by IntelOrca** [comment]
No, but we have already done it with tracks and scenarios and saved games. We will eventually do objects. I have added it to:
https://github.com/OpenRCT2/OpenRCT2/wiki/Features-to-implement

**Comment by wildgoosespeeder** [comment]
OK, instead of automatic installation of the custom files into the separate directory, how about just check the additional directory. With that, I can manually move the files (such as using Windows Explorer) once installed and OpenRCT2.exe is terminated. Upon next loading of OpenRCT2.exe, it then rebuilds what it needs to rebuild before normal execution can begin.

**Comment by IntelOrca** [comment]
There is a lot of re-coding necessary to get it to look at different directories. We will do it at some point.
