### ISSUE TITLE
(General) OpenGL renderer issues

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#3880]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** f339bd6

~~You recently added an in-development OpenGL renderer. I, and you too, of course still see issues with this new renderer. Is it ok to provide you with a list of all the graphical errors I see, so there is one place where all the bugs are listed for the OpenGL renderer? Or do you say: this is so much work in progress that we don't need a list of bugs yet?~~

**The list with all known OpenGL renderengine bugs can be found here: https://github.com/OpenRCT2/OpenRCT2/wiki/OpenGL-renderengine-issues Do not report these issues again and if you find more OpenGL specific bugs, you can add them to the wikipage.**

**Comment by IntelOrca** [comment]
A wiki page would be better with checkboxes.

**Comment by mrtnptrs** [comment]
Well, my English isn't that good, but would you like me to make one?

**Comment by IntelOrca** [comment]
yes

**Comment by mrtnptrs** [comment]
Here is the new wiki page for OpenGL bus: https://github.com/OpenRCT2/OpenRCT2/wiki/OpenGL-renderengine-issues Isn't it better to keep this issue open, so people who want to report bugs about the OpenGL renderengine can easily find the list with bugs, so you will have less duplicates?

**Comment by Gymnasiast** [comment]
This has been reopened to hopefully catch some bugs.

**Comment by rwjuk** [comment]
Closing as we're now accepting OpenGL bugs as normal.
