### ISSUE TITLE
FPS changes too much/unstable

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#3881]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** f339bd6

**Steps to reproduce:**
1. Use the OpenGL renderengine (the software renderengine has this too, but much less severe).
2. Disable the FPS limit.
3. Show the FPS counter
4. You see rapidly between for example 167, 250, 33,2, 200 etc. As if it can't hold a steady FPS and constantly has a dropdown in FPS OR the FPS counter in inaccurate.

Even with the FPS limit on, the game doesn't seem to be able to hold a steady 40 FPS, as it rapidly changes between 37.0, 41.7, 40 etc. It seems like there is some generally stutter in the whole game with every renderengine. But the OpenGL renderengine (still in progress) is the most affected by this problem.

**Comment by IntelOrca** [comment]
Please add to the wiki as mentioned in #3880.
