### ISSUE TITLE
Banking on Compact Inverted Coaster makes the game crash

### ISSUE THREAD

**Issue by rbozan** [OpenRCT2/OpenRCT2#3882]
**OS:** Arch Linux
**Version:** 0.0.5
**Commit/Build:** 0bdff0af63192ab26db3409b62d76cc351da668b

Whenever you try to build a Compact Inverted Rollercoaster and you try to use banking while the rollercoaster is flat, the game crashes with a segmentation fault.

**Steps to reproduce:**
1. Create a Compact Inverted Rollercoaster
2. Create a station
3. Have a straight part, but with a banking to the left or right.
4. Game crashes

**Comment by Gymnasiast** [comment]
Do you mean 'banking'? A curve = een bocht.

**Comment by rbozan** [comment]
Yeah sorry, I ment banking, just didn't know the word :)

**Comment by Gymnasiast** [comment]
It does say so in the interface. Both in the English and in the Dutch translation.

**Comment by Wirlie** [comment]
Related to #3564?

**Comment by rbozan** [comment]
duplicate of #3564

**Comment by Wirlie** [comment]
I'm not sure if your problem is related to #3564 because I cannot reproduce your problem, for me, banking works fine with the Compact Inverted Coaster.

OS: Windows10, build: d0dead085af78a8e435439ea82be215ccdf6a872
