### ISSUE TITLE
Objects appear underwater when placed on water

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#3885]
Windows 8
v0.0.5-develop build 935114a

Objects that are zero clearanced by default (objects that are entirely flat) sometimes appear underwater when placed on the water surface. This is not the case in normal RCT.

I built a couple of such objects on a single tile and only the ones on the bottom quarter tile are showing correctly. When you rotate the view, the bottom quarter tile remains the only correctly drawn one.

http://i63.tinypic.com/a3du0l.png

**Comment by Ziscor** [comment]
Just for referencing, I'll link this here:
https://openrct2.org/forums/topic/1379-missing-dats/

**Comment by Nubbie** [comment]
A PR to fix this is now open: #3895
