### ISSUE TITLE
Sofware mode: screen tearing

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#3894]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 0ec2b00

Major screen tearing occurs when in software drawingengine mode and you move around the map. Software (through hardware) and OpenGL are not affected by this problem. I know this could be normal, but I think I only see this happening for the last month or so. So, maybe this is a recently introduced bug where VSYNC isn't turned on when software mode is enabled or isn't vsync even possible in software mode. Or am I just dumb and didn't I see this issue before and has it always been this way?

**Comment by Gymnasiast** [comment]
> ```[Fill in the placeholders below. Delete any headings and placeholders that you do not fill in. Delete this line as well]```
*cough*

**Comment by mrtnptrs** [comment]
You evil little bastard! :P

**Comment by IntelOrca** [comment]
I am not sure you can control VSync with software alone...

**Comment by Goddesen** [comment]
I am not exactly sure how SDL handles software rendering, and this may be tangential, but how is `SDL_CreateRenderer` without passing `SDL_RENDERER_ACCELERATED` not suitable for software rendering?

**Comment by mrtnptrs** [comment]
It happens with uncapped FPS on and off.

**Comment by IntelOrca** [comment]
@Goddesen Software rendering utilises the OS ability to set a palette for a window and can pass the pixels straight away, so there is less overhead. Although I think someone said this has little to no benefit for OSX, possibly Linux.

**Comment by mrtnptrs** [comment]
This seems to have been fixed by the new 368.81 Nvidia driver, as I see no screen tearing anymore and because one of the changes in the drive is: [365.10] Tearing occurs in windowed applications after an update to Release 364.xx drivers. [1763731]
