### ISSUE TITLE
Frozen thunderstorm climate disables lightning strikes

### ISSUE THREAD

**Issue by Goddesen** [OpenRCT2/OpenRCT2#3902]
**OS:** Linux
**Version:** `0.0.5`
**Commit/Build:** `425fc73`

Freezing climate to thunderstorm disables lightning strikes.

**Steps to reproduce:**
1. Force climate to thunderstorm (or wait).
2. Freeze climate
3. Wait...

**Comment by Nubbie** [comment]
Weird, GitHub didn't close this :p 
Fixed in fc9595d
