### ISSUE TITLE
Possible to build path in the air, without it's supports touching the ground

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#3903]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 425fc73

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Build a slope of path till it's high in the air.
2. Delete the first few path pieces and build a path at the ground right under the path in the air. You now see that all the supports dissapear and the path now floats in the air without any supports.

**Comment by Goddesen** [comment]
![Like this?](https://cloud.githubusercontent.com/assets/5515119/16171810/890c518c-3579-11e6-89b4-fa41db5ea23a.png)
This is perfectly standard behavior and not a bug.

**Comment by mrtnptrs** [comment]
Have you ever seen a path floating in the air in real life?

**Comment by Goddesen** [comment]
Supports for a path element are removed if there is any object underneath it, that's just how the game works. Whether or not it is realistic is irrelevant.
You could make this into a feature request maybe, but it is not a bug.

**Comment by mrtnptrs** [comment]
Ok, but do the developers think the same? When yes, you can close this pull request of course or add the enhancement label.

**Comment by jensj12** [comment]
Use the tile inspector to put the lower path element below the surface element and the supports should be visible again.

**Comment by mrtnptrs** [comment]
@jensj12 ok, that is a workaround, but isn't this standard behavior of RCT2 a bit odd?

**Comment by Gymnasiast** [comment]
It also happens with paths over scenery, or rides over scenery. Paths can also set a flag to allow support to be built over them(!). So it's intended behaviour, and indeed a bit odd, but I think attempting to do something about it will create more trouble than it's worth.

**Comment by mrtnptrs** [comment]
I thought about that too @Gymnasiast , but maybe you can give this lable the enhancement label and maybe you can look at this in a year or so if someone comes with a new idea?

**Comment by Gymnasiast** [comment]
I consider it more or less inherent to the design of RCT. RCT1 even contained the Micro Park scenery which actually required the player to use this magic gravity. So not sure we should 'solve' this.

**Comment by mrtnptrs** [comment]
You can close this one, I agree with your opnions, would be really hard to "fix" and not really neccesary as it restricts path building even more and so affects gameplay.
