### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by NINI1988** [OpenRCT2/OpenRCT2#3909]
**OS:** Windows 7
**Version:** 0.0.5.0-beta 97fedab

Game Crash

- Multiplayer

**Steps to reproduce:**
Want to connect to Multiplayer Game.
**Dump file**
[1a663687-e2b6-4e71-9b18-805a422644c6(97fedab).zip](https://github.com/OpenRCT2/OpenRCT2/files/322288/1a663687-e2b6-4e71-9b18-805a422644c6.97fedab.zip)

**Comment by Nubbie** [comment]
Please fill in the headers correctly and remove the headers not used
The bold letters are titles

E.g.; Version: 7b421c8

**Comment by mrtnptrs** [comment]
And what were you doing on both sides when the crash occured?

**Comment by wolfreak99** [comment]
https://ci.appveyor.com/project/IntelOrca/openrct2-ject9/build/0.0.5.3452/artifacts NINI, try downloading this and see if you can connect with this, or at least if it crashes. if it says "NULL_ID" let us know as well.

**Comment by mrtnptrs** [comment]
@wolfreak99 how can you know that your commit could have fixed this? You don't even know the commit number! The user doesn't even know why and how the crash happened. Crashes in multiplayer games can happen for many reasons. So, that the user doesn't get the crash when using your commit/pull request doesn't say anything in this case. So, why should @NINI1988 try this?

**Comment by wolfreak99** [comment]
This is a term called "troubleshooting". if he still crashes in my commit, then at the least, there's one thing gone. if he doesn't crash, then we know it's something to do with the issue my pull request attempts to address by creating an in game error..
That's why he should try it.

**Comment by mrtnptrs** [comment]
No, if the crash still happens, it could be coincidence and caused by another of the many multiplayer issues we have. If it doesn't happen anymore, it could just have been a bug which only happens rarely in only certain unique conditions. So, in both cases it doesn't say anything. You're only right if the issue happend always for the user when he did something specific and your pull request fixes it.

**Comment by wolfreak99** [comment]
if my pull request gets it, it will show a "null_id" rather than crashing. but i'm not about to argue with you. as i wasn't even talking to you. my pull request doesn't fix his problem. i'm looking into his problem now.

**Comment by mrtnptrs** [comment]
Oh, that's what you mean. Sorry, hopefully it works for the user then. That wasn't really clear from this sentence: "if it says "NULL_ID" let us know as well." Do you understand the confusion here?

**Comment by Gymnasiast** [comment]
The OP is not helped by you two fighting over the solution. @mrtnptrs please use a less inflammatory tone if someone leaves a comment that looks wrong to you.

**Comment by mrtnptrs** [comment]
@Gymnasiast I did not mean to upset him or anyone else of course. I just told what I was thinking, but indeed in a way which could make others angry or feel like they get attacked. Next time, I will look at this more carefully instead of blindly typing my thoughts here :) And most of the times I say someone is wrong, I'm the one who is wrong :) So, I still have some things to learn...

**Comment by Nubbie** [comment]
@NINI1988 

Could you run openrct2.exe from the command prompt and with --verbose as an argument?
This mean:

1. Open a command prompt
2. cd to the directory where openrct2.exe resides
3. openrct2.exe --verbose

Can you then right click and copy all the text and paste it in here? (or at least show a screenshot at the end of the text)
_(copied from Dev Gymnasiast)_

**Comment by Nubbie** [comment]
```
>	openrct2.dll!set_load_objects_fail_reason(...) Line 520	C
 	openrct2.dll!game_load_network(SDL_RWops * rw=0x03ed4500) Line 495	C++
 	openrct2.dll!Network::Client_Handle_MAP(NetworkConnection & connection={...}, NetworkPacket & packet={...}) Line 1613	C++
 	openrct2.dll!Network::ProcessPacket(NetworkConnection & connection={...}, NetworkPacket & packet={...}) Line 1247	C++
 	openrct2.dll!Network::ProcessConnection(NetworkConnection & connection={...}) Line 1205	C++
 	openrct2.dll!Network::UpdateClient() Line 479	C++
 	openrct2.dll!rct2_update(...) Line 450	C
 	openrct2.dll!openrct2_loop(...) Line 458	C
 	openrct2.dll!openrct2_launch(...) Line 328	C
 	openrct2.dll!StartOpenRCT(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance=0x00000000, char * lpCmdLine=0x01614431, int nCmdShow=1) Line 109	C
 	openrct2.exe!004069e4()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for openrct2.exe]	
 	[External Code]	
```

**Comment by Nubbie** [comment]
@NINI1988 Still having this issue?

**Comment by NINI1988** [comment]
I don't play RCT2 currently. I only want to contribute an error to the project.
 

    Matte A <notifications@github.com> schrieb am 18:22 Donnerstag, 11.August 2016:
 

 @NINI1988 Still having this issue?—

**Comment by Nubbie** [comment]
This might be expired then ;o
