### ISSUE TITLE
Allow colorization on uncolorable objects (Bench, etc)

### ISSUE THREAD

**Issue by Margen67** [OpenRCT2/OpenRCT2#3910]
Normally you can only color certain objects, but maybe it could be possible to force the object to have a different palette?

For example, making a Bench blue.

**Comment by IntelOrca** [comment]
You need to create new objects with your own modified / custom graphics to do this.

**Comment by Nubbie** [comment]
@Margen67 
There are some mods out there that can do that

**Comment by Margen67** [comment]
Which ones?
