### ISSUE TITLE
Game crashed today

### ISSUE THREAD

**Issue by satdav** [OpenRCT2/OpenRCT2#3913]
**OS:**  Windows 10 
**Version:** 0.0.5 
**Commit/Build:** he latest from the launcher

**Steps to reproduce:**
1. Was playing Magic Mountan and it crashed the full game 
2. the game crashed 

**Dump file**
[RCT2Open Crash 19th June 2016.zip](https://github.com/OpenRCT2/OpenRCT2/files/322455/RCT2Open.Crash.19th.June.2016.zip)

**Comment by janisozaur** [comment]
Please format the issues properly and provide proper commit.

**Comment by satdav** [comment]
is that better @janisozaur as I have fixed it

**Comment by janisozaur** [comment]
No. You still have not provided which commit are you using and you have malformed entry for it. There's lots of confusing and self-contradicting information in this report as well.

**Comment by IntelOrca** [comment]
@satdav The latest from the launcher isn't helpful as it changes very frequently, so can you instead write the version that you can see at the bottom left of the title screen.

**Comment by IntelOrca** [comment]
Opening the saved game causes a crash whilst trying to draw a vehicle, in `vehicle_sprite_57`.

@zsilencer do you have any ideas?

**Comment by satdav** [comment]
it just says version 0.0.4 powered by Appveyer at the bottom of mine the now

**Comment by IntelOrca** [comment]
![sghdfgsdfhdgs](https://cloud.githubusercontent.com/assets/17282384/16177361/937aff90-362a-11e6-874f-22f8b5eeacff.png)

**Comment by satdav** [comment]
Just got Openrct2 V0.0.4 Powed by AppVeyor

**Comment by IntelOrca** [comment]
If you are using 0.0.4, then that's fine, but you need to say 0.0.4, rather than "latest from launcher"

**Comment by IntelOrca** [comment]
@satdav what were you doing at the time that it crashed? Did you open a new ride or do any hacks? cheats?

**Comment by satdav** [comment]
@IntelOrca  I am sure I was opening a new ride a roller coaster or editing one 

I have not hacked the game lol

**Comment by IntelOrca** [comment]
I have closed the looping roller coaster that caused it. If you open it or test it, it will crash the game. I think this is because the mode is set to forward rotation. Did you set it to this mode?

[3913.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/322510/3913.sv6.txt)

**Comment by satdav** [comment]
It might of been me editing a grippa coaster

**Comment by Gymnasiast** [comment]
Setting a coaster to 'forward rotation' is hacking and not allowed unless you turn on a cheat which even warns you for things like this.
