### ISSUE TITLE
Game Crashes when Connecting To Multiplayer Server Zod Realism

### ISSUE THREAD

**Issue by WhenPenguinsAttack** [OpenRCT2/OpenRCT2#3916]
**OS:** Windows 7
**Version:** 0.0.5
**Commit/Build:** 22c0cc9

See title.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**

1.) Connect to said server.
2.) Game crashes.

**Dump file**
[c1c94b5e-4f24-4625-9ce5-c39c93256459(22c0cc9).zip](https://github.com/OpenRCT2/OpenRCT2/files/322560/c1c94b5e-4f24-4625-9ce5-c39c93256459.22c0cc9.zip)

**Save game:**
[c1c94b5e-4f24-4625-9ce5-c39c93256459.zip](https://github.com/OpenRCT2/OpenRCT2/files/322561/c1c94b5e-4f24-4625-9ce5-c39c93256459.zip)

**Comment by WhenPenguinsAttack** [comment]
Also, it seems that this is because of objects the game attempts to load.  I believe that said objects should be contained in the save file (since I have export custom DAT files on).

**Comment by ptkato** [comment]
I'm experiencing the same issue under Arch Linux, see #3918.

**Comment by Gymnasiast** [comment]
@ptkato Please don't open duplicate issues.

**Comment by michaelwang32** [comment]
I am experiencing the same problems as the OP

**Comment by michaelwang32** [comment]
https://drive.google.com/file/d/0Bz6WH10GYohPMDd0Z0w1M0VrdU0/view?usp=sharing
https://drive.google.com/file/d/0Bz6WH10GYohPdlQ3NmQtYzNqOUk/view?usp=sharing
https://drive.google.com/file/d/0Bz6WH10GYohPUnZPWUJ5NHlIeGs/view?usp=sharing

**Comment by Misterk267** [comment]
I have the same problem, exactly. Does anyone have a working solution, something that can at least get the game to start again?

**Comment by WhenPenguinsAttack** [comment]
The Zod server is still having issues.

Here's a dump file and save from another attempt to connect to it:

[131e60d9-fc59-4ffa-bd20-ff3da27348df.zip](https://github.com/OpenRCT2/OpenRCT2/files/331019/131e60d9-fc59-4ffa-bd20-ff3da27348df.zip)

@Misterk267  Delete all the newest DAT files (find them by sorting by date and selecting the ones from the date you started having the issue) in the ObjData folder in your RCT2 game (NOT the OpenRCT2 game).

**Comment by ptkato** [comment]
Wiping the ObjData folder didn't work. "Reinstalled" RCT2 and didn't work also. Then I did fallback to the stable version, 0.0.4.

Then reinstalled the git version and now it works fine. But it's not a practical fix.

**Comment by WhenPenguinsAttack** [comment]
@ ptkato  It might be that you have to delete this file, too:

%userprofile%\documents\OpenRCT2\plugin.dat

**Comment by Misterk267** [comment]
I've tried deleting all the recent objdata entries and plugin.dat, no results. The only solution I've found is what ptkato said in his previous reply.

**Comment by ptkato** [comment]
I'm Arch Linux, it's located at `.config/OpenRCT2/plugin.dat`. I've already fixed it, I'll try that next time it breaks.

**Comment by Nubbie** [comment]
```
>	openrct2.dll!object_chunk_load_image_directory(unsigned char * * chunk=0x000cf8a0) Line 478	C
 	openrct2.dll!object_type_large_scenery_load(void * objectEntry=0x34ba0020, unsigned int entryIndex=0, int * chunkSize) Line 1563	C
 	openrct2.dll!object_load(int type=2, void * objectEntry=0x34ba0020, unsigned int entryIndex=0, int * chunkSize=0x000cfa30) Line 2556	C
 	openrct2.dll!object_load_file(int groupIndex=-1, const rct_object_entry * entry, int * chunkSize=0x000cfa30, const rct_object_entry * installedObject=0x03f27d5e) Line 134	C
 	openrct2.dll!install_object_entry(rct_object_entry * entry=0x000cfa70, rct_object_entry * installed_entry=0x03f27d5e, const char * path, rct_object_filters * filter=0x000cfa54) Line 798	C
 	openrct2.dll!object_list_load(...) Line 349	C
 	openrct2.dll!rct2_init(...) Line 167	C
 	openrct2.dll!openrct2_initialise(...) Line 243	C
 	openrct2.dll!openrct2_launch(...) Line 271	C
 	openrct2.dll!StartOpenRCT(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance=0x00000000, char * lpCmdLine=0x001931dc, int nCmdShow=10) Line 109	C
 	openrct2.exe!004069e4()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for openrct2.exe]	
 	[External Code]	

```

**Comment by End3rp** [comment]
@ptkato Came here from #3949. Confused by re-installing the git version" so I tried re-installing from the website. Same crash happened. Could you clarify on what you meant by that?

**Comment by ptkato** [comment]
@End3rp, by git version, I meant the latest working build on git, got it [from here](https://aur.archlinux.org/packages/openrct2-git/).

**Comment by End3rp** [comment]
@ptkato through control panel?

**Comment by End3rp** [comment]
@ptkato uninstalled and installed stable version. Still confused by that website you gave me. Am I supposed to click on the "upstream URL" or "download snapshot"?

**Comment by Patrik356b** [comment]
@End3rp none. it doesn't apply to your OS.

**Comment by End3rp** [comment]
@Patrik356b derp.

@ptkato ok, I fell back to the stable version (after uninstalling OpenRCT2), then updated to the latest dev build, then cleared the ObjData folder. Ran it in verbose, gave me a crap ton of text, and then it worked. Thanks!

**Comment by Nubbie** [comment]
@End3rp You didn't have to uninstall OpenRCT2 but I'm glad it worked out!
The newest updates that most people use are the latest dev version, often gets added more features etc with them, you don't need to run it in Verbose anymore if it's fixed as verbose is just used for de-bugging as it tells you everything it loads before starting :)

**Comment by janisozaur** [comment]
Closing on behalf of https://github.com/OpenRCT2/OpenRCT2/pull/4024
