### ISSUE TITLE
BUG: It's GONE

### ISSUE THREAD

**Issue by TurtleShroom** [OpenRCT2/OpenRCT2#3917]
**OS:** Windows XII
**Version:** Launcher 0.0.5
**Commit/Build:** 934 (Hash: 22c0cc9)

- [N] Reproducible in RCT2 (vanilla)?
- [Y] Multi-player?
- [Y] Single player?

Unknown. I fired up the game, entered MP, and it was gone. I exited MP, closed the game, opened SP, and it was still gone. It still exists in the Object Selection Menu, and it doesn't work.

In addition, several animated Scenary items (including one vanilla, the Mechanical Theming's animated fire) stopped moving. 

**Screenshots / Video:**
![scr11](https://cloud.githubusercontent.com/assets/17663470/16180966/600dcb88-3661-11e6-9601-50ae8e81c31a.png)

**Save game:**
N/A. It has happened in several games.

**Comment by Wirlie** [comment]
Only I can reproduce the bug of the animated scenary.

This only happens with the latest build 22c0cc9 (PR #3897) I cannot reproduce this with the previous build: 7b421c8

**Comment by WhenPenguinsAttack** [comment]
What's "It"?

If you're talking about all buildable rides and stalls disappearing (as your screenshot suggests), I'm getting the same issue.  Going back to 0.0.4 stable fixes the issue for now, if you need to build offline.

**Comment by Wirlie** [comment]
Oh lol sorry for my last comment... I'm getting this bug :P I think that this bug should be have a high priority for a fix. 

And It is not necessary to going back to 0.0.4, you can download the previous build of the latest build: [build 7b421c8](https://openrct2.org/downloads/develop/7b421c8)

**Comment by Gymnasiast** [comment]
Please provide proper detail. It's hard to see what exactly is wrong here.

Quote WhenPenguinsAttack:
> What's "It"?
