### ISSUE TITLE
I chose 

### ISSUE THREAD

**Issue by BigBadAsh02** [OpenRCT2/OpenRCT2#3919]
[Fill in the placeholders below. Delete any headings and placeholders that you do not fill in. Delete this line as well]

**OS:** [Windows 7 home premium]
**Version:** []
**Commit/Build:** [e.g. 426e106]

[MY RCT2 directory folder was in steam anf after picking it it would crash on startup. I couldn't find any way to change it and after uninstalling and reinstalling it at least 5 times no progress was made. the game now looks for a folder in my documents now as seen in the picture. note my steam library is on a separate hard drive from my program files and the game was installed on it's own folder on my other hard drive.]

- [no ] Reproducible in RCT2 (vanilla)?
- [ no] Multiplayer?

**Steps to reproduce:**
1. [use the build made 6 hours before this message was posted.]
2. [have RCT2 installed on a seprate hard drive from your C: drive]
3. [install the game in it's wwn folder on that seprate hard drive.]
4. [chose the rollercoaster tycoon 2 folder in your steamapps folder under common (still under the same hard drive)]
5. [this shouldn't work so now try deleting the open rct folder and the start menu folder and reinstalling it]

**Dump file**
[]

**Screenshots / Video:**
[
![image](https://cloud.githubusercontent.com/assets/20037450/16184381/7ee939e6-3681-11e6-96d4-bc7bb55993df.png)
]

**Save game:**
[Change the file extension to .txt or package to a .zip so that it can be drag & dropped here...]

**Comment by Wirlie** [comment]
> [Fill in the placeholders below. Delete any headings and placeholders that you do not fill in. Delete this line as well]

:v 
And please format the issues properly and provide the proper commit.
You can find it at the main screen:
![img](https://cloud.githubusercontent.com/assets/17282384/16177361/937aff90-362a-11e6-874f-22f8b5eeacff.png)

**Comment by YJSoft** [comment]
And please title your issue correctly. "I chose" is not proper title for this issue.

**Comment by pizza2004** [comment]
The game won't launch so he can't see the version in the bottom left corner, but yeah this exact issue is why I copied my RCT2 files onto my main hard drive.  I had problems getting the game to run when it was on a different hard drive than RCT2.

**Comment by Wirlie** [comment]
@pizza2004 good point, I edited my comment.

**Comment by Gymnasiast** [comment]
Hm, I think it has more to do with the fact his path seems to contain `<` and `>`.

**Comment by janisozaur** [comment]
@Gymnasiast how do you know it does? Also, I don't think `<` and `>` are legal tokens in path name, Windows does not allow creation of such paths.

**Comment by IntelOrca** [comment]
The dump file would be helpful, can you upload it?

**Comment by Gymnasiast** [comment]
@janisozaur I don't, hence the 'I think'. The screenshot seems to suggest it uses `<` and `>`, but it could also be those are just blocky variants of `(` and `)`.

**Comment by IntelOrca** [comment]
@Gymnasiast they are normal brackets `()` and that's in the dump filename - after its crashed already.

**Comment by YJSoft** [comment]
![bracket](https://cloud.githubusercontent.com/assets/5893514/16189860/65810e8e-3717-11e6-93f4-6ffc75d756ef.PNG)
`() <>`

**Comment by Nubbie** [comment]
@BigBadAsh02 

Could you run openrct2.exe from the command prompt and with --verbose as an argument?
This mean:

1. Open a command prompt
2. cd to the directory where openrct2.exe resides
3. openrct2.exe --verbose

Can you then right click and copy all the text and paste it in here? (or at least show a screenshot at the end of the text)
_(copied from Dev Gymnasiast)_
