### ISSUE TITLE
Wrong units on tracks

### ISSUE THREAD

**Issue by Tobber98** [OpenRCT2/OpenRCT2#3923]
**OS:** Mac OS X 10.11.5
**Version:** 0.0.5
**Commit/Build:** c177cc7

**Explanation:** After Launcher installed the latest build the unit for tracks went from metres to feet, while height marks on land and path didn't change. Settings still shows metres though. Must have happened in one of the latest builds because the problem wasn't there yesterday.

**Comment by duncanspumpkin** [comment]
@janisozaur has removed the code that copied the height marker config. https://github.com/OpenRCT2/OpenRCT2/commit/39aaf851828e17ffece929c89828ef23849cd7aa
