### ISSUE TITLE
Compiling in Ubuntu 16.04

### ISSUE THREAD

**Issue by gDanix** [OpenRCT2/OpenRCT2#3928]
Hi all!

I'm trying to build OpenRCT (Lubuntu 16.04 x86), but CMake cannot find openssl>=1.0.0

This can be fixed just by installing libssl-dev, so I was thinking on editing the wiki to add this package to the `apt-get` command but, before doing so, I want to make sure I'm doing everything correct.

First, I called the `install.sh` script inside `scripts/linux` folder. Then, I installed all the packages listed in the [wiki](https://github.com/OpenRCT2/OpenRCT2/wiki/Building-OpenRCT2-on-Linux) following instructions under APT (Debian, Ubuntu) section.

And finally, executed the `build.sh` script inside `scripts/linux` folder, which gives me the error as you can see:
```
daniel@daniel-VirtualBox:~/git/OpenRCT2$ ./scripts/linux/build.sh 
~/git/OpenRCT2/build ~/git/OpenRCT2
OPENRCT2_CMAKE_OPTS =
-- The C compiler identification is GNU 5.3.1
-- The CXX compiler identification is GNU 5.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'openssl>=1.0.0'
--   
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  CMakeLists.txt:75 (PKG_CHECK_MODULES)


-- Configuring incomplete, errors occurred!
See also "/home/daniel/git/OpenRCT2/build/CMakeFiles/CMakeOutput.log".
```

After installing `libssl-dev` everything goes perfect.

**Comment by Gymnasiast** [comment]
You can add it, I have had to install it myself too.

**Comment by gDanix** [comment]
[Wiki](https://github.com/OpenRCT2/OpenRCT2/wiki/Building-OpenRCT2-on-Linux) edited.

The new solution (updated package list + scripts) have been successfully tested in i386 and amd64 architectures.
