### ISSUE TITLE
22c0cc9 causes all rides to disapear from ride selection window.

### ISSUE THREAD

**Issue by Rodbourn** [OpenRCT2/OpenRCT2#3932]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 22c0cc9

Loading a save created with the previous commit, 7b421c8, and all of the rides (researched and available by default) are unavailable.  Each tab was empty as if no rides were researched.  Was playing multiplayer, both clients on the same version and OS with the same issue.

- [no ] Reproducible in RCT2 (vanilla)?
- [yes ] Multiplayer?

**Steps to reproduce:**
1. Save a game with 7b421c8
2. Load a game with 22c0cc9
3. View available rides

**Dump file**
n/a

**Screenshots / Video:**

**Save game:**

**Comment by Gymnasiast** [comment]
Fixed by c177cc72e9c6a674bee56c57fef1f092224f5267. Please always update to the newest version before reporting.

**Comment by Rodbourn** [comment]
Thanks!  Sorry, didn't realize it had been fixed so quickly.  We update just before each session :)
