### ISSUE TITLE
Game crash on Giga-Bahn Lopping

### ISSUE THREAD

**Issue by Schlumpf9** [OpenRCT2/OpenRCT2#3933]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 644a36a

When building a Looping on Giga-Bahn the whole Game crashes.
I am playing on a self created Szenario. I wanted to test in other Szenarios and saw that you can't build a looping with Giga-Bahn there, so i don't know why i can build it in my map..?

- Singleplayer

**Steps to reproduce:**
1. Build a looping left or right

**Dump file**
[Dump.zip](https://github.com/OpenRCT2/OpenRCT2/files/323714/Dump.zip)

**Save game:**
see dump file

**Comment by jensj12** [comment]
This bug has been fixed very recently, but the fix only affects new games. That means the bug is still present in some saved games.
