### ISSUE TITLE
Crash upon loading scenario

### ISSUE THREAD

**Issue by Phasedetect** [OpenRCT2/OpenRCT2#3934]
**OS:** OS X 10.11.5
**Version:** 0.0.5 develop
**Commit/Build:** c487e12

For the last few builds, I have been unable to load up the attached save. The game just crashes.

Rename the file to .sv6 and open.

**Save game:**
[Rampaging River.zip](https://github.com/OpenRCT2/OpenRCT2/files/324645/Rampaging.River.zip)

**Comment by Tobber98** [comment]
Might have something to do with #3886. The attached file should be playable again, it was when I tested it. Perhaps some scenery or path is missing and if it wasn't already every ride is unlocked now, don't know if there's a way around that, but at least you can continue your save.
[Rampaging.River.zip](https://github.com/OpenRCT2/OpenRCT2/files/325753/Rampaging.River.zip)

**Comment by IntelOrca** [comment]
This saved game seems to have all zeros for several object entries. I would be surprised if that worked in vanilla RCT2 - nonetheless I have protected against it.
