### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#3941]
A window up in the left corner where it say 'Credits' and show the contribution file in a window

ROUGH CONCEPT

![rough concept](https://cloud.githubusercontent.com/assets/17282384/16307952/74979afc-3963-11e6-8484-8652fccd993b.jpg)

**Comment by telk5093** [comment]
What about including the credits when redesign the 'About OpenRCT2' window(↓) below of disket menu, rather than button?
![image](https://cloud.githubusercontent.com/assets/10726524/16309900/591207a8-39a5-11e6-9611-58ea8c151a59.png)

**Comment by Gymnasiast** [comment]
What @telk5093 says has always been the plan anyway.

**Comment by Nubbie** [comment]
@telk5093 Using that window would be perfect but is it necessary for it to clog up the 'Disket' menu?

**Comment by Nubbie** [comment]
How about a re-work with 3 tabs

- Original
- OpenRCT2
- Languages

**Comment by Gymnasiast** [comment]
No need for separating languages, as they easily fit within one block in the contributors file.
Also, we don't need full Infogrames credites, just the main people who worked on RCT2 - that are mentioned on the bottom of the contributors.md file anyway.

**Comment by Nubbie** [comment]
What about the button on the left corner on the start screen? 
Something I'm missing out? :o

**Comment by Gymnasiast** [comment]
I don't really understand what you mean.

**Comment by Nubbie** [comment]
![gawegwagwa](https://cloud.githubusercontent.com/assets/17282384/16318339/0fc48b40-398f-11e6-86c6-a18f0d342a93.png)

Just as a quick button to get into the right place, most games have it on the front for easy access and being able to 'forget' about it I presume so it doesn't pop up and clog any other menu

**Comment by Nubbie** [comment]
#6082 & #6098 related to issue - closing it to let those take over
