### ISSUE TITLE
Cannot play game

### ISSUE THREAD

**Issue by Susrussr** [OpenRCT2/OpenRCT2#3956]
https://openrct2.org/forums/topic/1409-help-cannot-play/

This link to to a forum that I wrote. I hope that one of you devs can fix my issue.

Thanks! :)

**Comment by Gymnasiast** [comment]
Please put your problem in the issue itself, rather than linking. We even provide an issue template to help you provide enough information, but you deleted it -,-.

**Comment by Nubbie** [comment]
@Susrussr​​​​​​​ Try to delete your 'plugins.dat' and try the latest version

**Comment by paintUSER** [comment]
actually,this is the same thing that is happening to me,
![capture](https://cloud.githubusercontent.com/assets/12258256/16427463/1f88cf06-3d76-11e6-8ef6-c918203b2485.PNG)

i also have a .dmp file to show(well,more than one):https://drive.google.com/open?id=0B75ugvK7PtTkaHVEeFJRT3BsbUk
