### ISSUE TITLE
Autosave Construction Freezing

### ISSUE THREAD

**Issue by OneKnightB** [OpenRCT2/OpenRCT2#3957]
**OS:** [Windows 10]
**Version:** [0.0.5.0-beta]

[Explanation of the issue...]
- Whenever I am placing a track (the ghost thing of it, not construction), I crash if it autosaves.
- Haven't checked multiplayer
- Not reproducible in vanilla as there is no autosave.
- Save is irrelevant

**Steps to reproduce:**
1. Select a premade track to place, but don't place.
2. Wait for autosave.

**Screenshots / Video:**
![image](https://cloud.githubusercontent.com/assets/20196484/16436334/af43f800-3d62-11e6-9e04-a947a2b78740.png) Small size because I can't get to the actual console, but it has to do with track removal though, and how some track element can't be found.

**Comment by Patrik356b** [comment]
try alt tab to switch to the console, the image linked is pretty useless

**Comment by OneKnightB** [comment]
Alt tab doesn't bring the console into focus, otherwise I would.

**Comment by janisozaur** [comment]
This is stupid. Don't post a screenshot of a log, simply provide the log.

**Comment by IntelOrca** [comment]
@janisozaur you can't focus the console once its crashed, only way is to pipe the output prior to running the game.

**Comment by janisozaur** [comment]
@IntelOrca you're stating my point for me.

According to the bug report it is reproducible on user's end, so you just restart while piping the output to a log.

**Comment by Nubbie** [comment]
@Phillor 
**Options -> Miscellaneous -> Autosave frequency: Never**
![fdhfhd](https://cloud.githubusercontent.com/assets/17282384/16455532/f4d534bc-3e14-11e6-867a-80f86950f5e7.png)

**Comment by Phillor** [comment]
@Nubbie 
The commit number where this bug is occurs is 89db25e

**Comment by Nubbie** [comment]
@Phillor Couldn't reproduce it myself with your version
Could you provide us a better screenshot or a copy of the log? 
But also, did it prove a dump file?

If so, please zip the dump file up and put it in here

**Comment by ThePsionic** [comment]
I had this problem as well (see #3974 w/ dump). Figure I'd mention here as the other one is a dupe.

**Comment by Phillor** [comment]
@Nubbie 
Couldn't reproduce it either yesterday. I definitely got another crash yesterday even with the autosave turned off. Was about to place a fountain and the game crashed. Unfortunately I don't have the time of the crash. As soon as the game crashes again I will provide the logs with the according time.

Or is it sufficient for you if I just provide the logs without the time where the crashes occured?

**Comment by ThePsionic** [comment]
Just got it randomly after 2 in-game years, with autosave turned off.

**Comment by Nubbie** [comment]
@Phillor The time isnt that useful
Would be better if you provided a dump file _(which often gets created when it crashes)_, logs or verbose :p

**Comment by Nubbie** [comment]
@OneKnightB & @Phillor 
Does this still occur?

**Comment by Gymnasiast** [comment]
Since there have been no answer since 2017 and the code is completely different, assuming this is no longer applicable.
