### ISSUE TITLE
Peeps endless walk along the same path and do not get closer to leaving the park.

### ISSUE THREAD

**Issue by rcthelp** [OpenRCT2/OpenRCT2#396]
Hello all. First time post on github, hope this is the correct place to post this.

I'm really excited about this project, especially if it gets rid of the bug that made we stop playing it as a 'game'. I notice that this bug isn't in the list on the githib page about this project.

There is a pathfinding bug in the peep AI where sometimes people go round and round and round in a very tight loop at some random place in your park. They get more and more unhappy, don't spend any money and drive down your park rating in a spectacular way because of 'I want to go home' 'I cannot find the park exit'  'I'm hungry' 'I'm thirsty'  'I need to go to the bathroom' type reasons.

I know it's a big ask, but if you guys could find the reasons for that, and fix it, it would be magnificent.

**Comment by Christipher** [comment]
This also happens to occur on flat land as well, elevation happens to not even be the problem, its simply a problem all around where people get lost like that even if all of the footpaths are on the same elevation...

**Comment by Littlemeister** [comment]
I always had this problem with RollerCoaster tycoon 2 as a kid, also my friends had the same problem. It often became a problem or "happened" when there was alot of geusts in the park, like 1000 peeps or more. This was the bug that made me stop playing this game, becouse there was not really any workaround the problem and often gamebreaking, or close to it. Is this problem fixed yet?

**Comment by Gymnasiast** [comment]
@Littlemeister: Unfortunately not, otherwise this issue would have been marked as Closed. Improving the AI is on our list.

**Comment by Nubbie** [comment]
I wonder if anything has to do with the original 'Death Trap' bug too
Especially when they are leaving the park
#3261

**Comment by rcthelp** [comment]
They may be linked, but I don't think it's the same bug. In the bug I have
documented above, the peeps get stuck BEFORE they want to go home. Because
they do get stuck and none of their needs to eat/drink/toilet/ride THEN
they want to find the exit. But when they do, they are already stuck anyway.

**Comment by duncanspumpkin** [comment]
Peep AI has been modified since this and issue probably no longer occurs.
