### ISSUE TITLE
Custom currency reverts to default when using non-sprite characters

### ISSUE THREAD

**Issue by marijnvdwerf** [OpenRCT2/OpenRCT2#3967]
**OS:** OS X 10.11.5
**Version:** 0.0.5
**Commit/Build:** c062961

If you use a special character not in the sprite font as your currency symbol (i.e. `Ƀ`), the currency symbol will reset to 'Ctm'. As soon as you change the game language to something else, the symbol works fine.

![image](https://cloud.githubusercontent.com/assets/737603/16540805/4859e76e-4071-11e6-8d30-05df886959b1.png)
![image](https://cloud.githubusercontent.com/assets/737603/16540808/5b809fe0-4071-11e6-85ce-e835e3ac950b.png)

**Comment by Goddesen** [comment]
This seems to me as *working as intended*. The currency symbol cannot be shown with the sprite font anyway, right? Maybe emit a warning when non-sprite symbols are selected?
