### ISSUE TITLE
Custom currency's gets reset when closing the game

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#3969]
**OS:** Windows 7
**Version:** 0.0.5
**Commit/Build:** c062961

The value resets to the default values when you close the game

**Steps to reproduce:**
1. Choose a custom currency and write a name etc for it
2. Save it and close the game
3. Restart the game and check it again
4. - The values should be back to the default settings as they don't seem to be saved to a config file

**Comment by gDanix** [comment]
This is because of [this](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/config.c#L479)
