### ISSUE TITLE
save game and scenario completed not working

### ISSUE THREAD

**Issue by dsmcgarry** [OpenRCT2/OpenRCT2#3971]
[i am using windows 10 and the stable version of openrct2 (0040 v004)
after finishing a scenario, i cannot save the game as it wont allow me to.
also when scenario complete and name entered, when moving onto another scenario, it is not showing 
that i have completed and therefore wont unlock new scenarios

this is what it says on the black screen that opens with the game. 

ERROR[src\config.c:556 (config_save)]: Unable to write to config file.
INFO[src\object_list.c:425 (object_list_cache_load)]: Object list cache version different... updating
ERROR[src\object_list.c:469 (object_list_cache_save)]: Failed to save C:\Users\Dave\Documents\OpenRCT2\plugin.dat
ERROR[src\config.c:556 (config_save)]: Unable to write to config file.
ERROR[src\config.c:556 (config_save)]: Unable to write to config file.
ERROR[src\config.c:556 (config_save)]: Unable to write to config file.
ERROR[src\config.c:556 (config_save)]: Unable to write to config file.
ERROR[src\config.c:556 (config_save)]: Unable to write to config file.
ERROR[src\config.c:556 (config_save)]: Unable to write to config file.
ERROR[src\config.c:556 (config_save)]: Unable to write to config file.
ERROR[src\config.c:556 (config_save)]: Unable to write to config file.
ERROR[src\config.c:556 (config_save)]: Unable to write to config file.
ERROR[src\config.c:556 (config_save)]: Unable to write to config file.
ERROR[src\config.c:556 (config_save)]: Unable to write to config file.

is there anything i can do or change that is not too complicated as i am not very savvy when it comes to code etc

thanks

**Comment by Nubbie** [comment]
@dsmcgarry Can you try to change the text to this (we have a template we often follow, easier to read and help etc) **and** try out the newest [dev version](https://openrct2.org/downloads/develop/latest)
Will see if I can reproduce this myself

Copy this to ur issues description:
```
**Operating System:** Windows 10
**Commit/Build:** stable 4.0.0

after finishing a scenario, i cannot save the game as it wont allow me to.
also when scenario complete and name entered, when moving onto another scenario, it is not showing 
that i have completed and therefore wont unlock new scenarios

**Reproducible in RCT2 (vanilla)?:** No
**Multiplayer affected?:** No
```

**Comment by dsmcgarry** [comment]
![error 2](https://cloud.githubusercontent.com/assets/20257548/16544932/e73614a4-410f-11e6-96e7-4b15249e8106.jpg)

**Comment by IntelOrca** [comment]
@dsmcgarry OpenRCT2 doesn't seem to have permission to write to your documents. Is there anything unusual about your system?

Try running OpenRCT2 as administrator.
