### ISSUE TITLE
Diagonal wall & triangle floor tile z sorting glitch

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#3972]
This might be a duplicate but anyway:

![horizontal bug](http://puu.sh/pO0oS/57df6ea7f1.jpg)
![vertical works](http://puu.sh/pO0qW/befd008704.jpg)

With the building facing vertical it looks fine, but not with the building facing horizontal (in 2d terms here/xy plane)

commit a9dbae6

**Comment by jensj12** [comment]
If you disabled clearance to be able to do that (looks like you did), it's been like that as long as I can remember. Same with a diagonal and normal wall on the same tile

**Comment by Patrik356b** [comment]
I did not build this. While the creator may have used that cheat, I have not seen this z sorting issue with the same scenery items in use in similar ways before in OpenRCT2.

**Comment by jensj12** [comment]
Look at the front row of walls in the first image, you can see the roof through the window. This is normally not possible. If you want to check, remove one of the triangular roof pieces and try to place it back.

**Comment by Patrik356b** [comment]
I did not notice that. I thought they were placed ontop
