### ISSUE TITLE
Game crashes with Zzzz cursor showing

### ISSUE THREAD

**Issue by ThePsionic** [OpenRCT2/OpenRCT2#3974]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 13ecd35

The game crashes fairly early on in the game, showing the Zzzz cursor. May be possible that autosaving doesn't work for some reason.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Do nothing
2. Watch your dreams die before your eyes

**Dump file**
[OpenRCT2_dump.zip](https://github.com/OpenRCT2/OpenRCT2/files/344962/OpenRCT2_dump.zip)

**Comment by mrtnptrs** [comment]
Dublicate of #3973

**Comment by Nubbie** [comment]
@ThePsionic Seems like this happens _maybe_ by a guest leaving a ride or with guests leaving rides, do you have any hacked rides in your park? Does it happen in every save?
**You can always try to remove all peeps with the cheat code and see if that works**

@mrtnptrs Not a dupe, think the 'zzz' cursor is something that pops up now when it crashes

----
-

To Devs; 
This is what I got from the dump file 63b2afd2-7076-452a-b5d6-a79785ea3d47(13ecd35).dmp

**Error message:**
Unhandled exception thrown: read access violation.
[peep was 0x1DE77BC.](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/windows/ride.c#L1111)

**Call stack:**
```
>	openrct2.dll!ride_remove_peeps(int rideIndex=1) Line 1111	C
 	openrct2.dll!ride_set_vehicles(unsigned char rideIndex='\x1', unsigned char setting, unsigned char value='\t', unsigned int flags=513, unsigned char ex='\0') Line 7760	C
 	openrct2.dll!game_command_set_ride_vehicles(int * eax=0x000dfd70, int * ebx=0x000dfd6c, int * ecx=0x000dfd58, int * edx, int * esi=0x000dfd5c, int * edi=0x000dfd60, int * ebp=0x000dfd64) Line 7814	C
 	openrct2.dll!game_do_command_p(int command=9, int * eax=0x000dfd70, int * ebx=0x000dfd6c, int * ecx=0x000dfd58, int * edx=0x000dfd68, int * esi=0x000dfd5c, int * edi=0x000dfd60, int * ebp=0x000dfd64) Line 524	C
 	openrct2.dll!place_track_design(short x, short y, short z=208, unsigned char flags='i', unsigned char * outRideIndex=0x000dfd9c) Line 1464	C
 	openrct2.dll!game_command_place_track_design(int * eax, int * ebx=0x000dfe04, int * ecx, int * edx=0x000dfe00, int * esi=0x000dfdfc, int * edi=0x000dfe18, int * ebp=0x000dfdf8) Line 1647	C
 	openrct2.dll!game_do_command_p(int command=48, int * eax=0x000dfe08, int * ebx=0x000dfe04, int * ecx=0x000dfe10, int * edx=0x000dfe00, int * esi=0x000dfdfc, int * edi=0x000dfe18, int * ebp=0x000dfdf8) Line 524	C
 	openrct2.dll!window_track_place_attempt_placement(rct_track_td6 * x, int y, int z=208, int bl, int cost=0x000dfe3c, int * rideIndex=0x000dfe34, unsigned char *) Line 438	C
 	openrct2.dll!window_track_place_toolupdate(rct_window * w=0x51ba7028, int widgetIndex=6, int x=1025, int y=279) Line 276	C
 	openrct2.dll!process_mouse_tool(int x=1025, int y=279) Line 1170	C
 	openrct2.dll!game_handle_input(...) Line 166	C
 	openrct2.dll!game_update(...) Line 345	C
 	openrct2.dll!rct2_update(...) Line 462	C
 	openrct2.dll!openrct2_loop(...) Line 456	C
 	openrct2.dll!openrct2_launch(...) Line 328	C
 	openrct2.dll!StartOpenRCT(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance=0x00000000, char * lpCmdLine=0x01522e19, int nCmdShow=10) Line 109	C
 	openrct2.exe!004069e4()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for openrct2.exe]	
 	[External Code]	
```

**Locals:** 
```
		exitDirection	16	int
		exitX	1540	int
		exitY	1584	int
		exitZ	210	int
		i	Variable is optimized away and not available.	
		mapElement	Variable is optimized away and not available.	
+		peep	0x01de77bc {sprite_identifier=??? var_01=??? next_in_quadrant=??? ...}	rct_peep *
+		ride	openrct2.exe!0x01362b58 (load symbols for additional information) {type=23 '\x17' subtype=9 '\t' pad_002=...}	rct_ride *
		rideIndex	1	int
		spriteIndex	Variable is optimized away and not available.	
		stationIndex	Variable is optimized away and not available.	
		x	Variable is optimized away and not available.	
		xy	Variable is optimized away and not available.	
		y	Variable is optimized away and not available.	
		z	Variable is optimized away and not available.	
```

**Comment by ThePsionic** [comment]
I've pinpointed it down to autosaving as previously stated in #3957, but I hope the dump helps nonetheless.

**Comment by Niels-NTG** [comment]
This isn't unique to Windows. The same happend to me (Mac OS 10.11.5, Version 0.0.5). Sadly I can't find the log files from this crash.

**Comment by IntelOrca** [comment]
@ThePsionic does this still happen?

**Comment by ThePsionic** [comment]
Nope, not for a while at least.

**Comment by darth-crunchus** [comment]
I hope it's okay that I'm commenting on this, but I just had this happen, only it didn't crash while playing (The 'Zzzz' cursor popped up for a split-second, then all seemed fine), rather it crashed as I clicked the Exit exit button.  On version 0.3.3 (build 517935e on develop)

**Comment by ocalhoun6** [comment]
I had the same thing happen yesterday while using the scenario editor and just trying to place a scenery item. (Luckily, I had saved the landscape immediately before this.) On Kubuntu linux.

Seems pretty random and never happened again.

**Comment by duncanspumpkin** [comment]
your issues are completely unrelated to this issue do not necro unrelated issues.

**Comment by IntelOrca** [comment]
The Zzzz cursor appears when doing intensive operations such as a tile optimisation, which may cause a brief freeze. It is perfectly normal and happens in the vanilla game. If it happens too frequently, that can be raised as a separate issue.
