### ISSUE TITLE
Spinning Wild Mouse not unlocked after research

### ISSUE THREAD

**Issue by ThePsionic** [OpenRCT2/OpenRCT2#3975]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 13ecd35

After the Spinning Wild Mouse is researched, it can not be built as it does not show up in the build menu.

**Steps to reproduce:**
1. Have researchers research the Spinning Wild Mouse
2. Note that it doesn't appear in the build menu

**Screenshots / Video:**
![scr2](https://cloud.githubusercontent.com/assets/842080/16544947/de13d4e8-4118-11e6-834f-98619351f8cf.png)
![scr3](https://cloud.githubusercontent.com/assets/842080/16544948/e02ab7b0-4118-11e6-93df-51e0bd5fadbb.png)

**Save game:**
[Crazy Castle.txt](https://github.com/OpenRCT2/OpenRCT2/files/344975/Crazy.Castle.txt)

**Comment by Goddesen** [comment]
It's right there, third from the left...

**Comment by ThePsionic** [comment]
Oops, my bad, it is simply called Wild Mouse in the menu. I'll be seeing myself out :P

**Comment by Goddesen** [comment]
Wait what..? This is me testing this right now:
![scr13](https://cloud.githubusercontent.com/assets/5515119/16546204/37c6dff6-4143-11e6-9033-2beb18aa4c89.png)
Is this different for you? In that case that may be a legitimate bug.

**Comment by IntelOrca** [comment]
![image](https://cloud.githubusercontent.com/assets/1482259/16546246/0716762a-413c-11e6-9959-cf12446d2057.png)

**Comment by ThePsionic** [comment]
^ That is exactly why I couldn't find it :P
