### ISSUE TITLE
Twitch tab flickering

### ISSUE THREAD

**Issue by danidoedel** [OpenRCT2/OpenRCT2#3978]
**OS:** Windows 10
**Version:**  0.0.5
**Commit/Build:** 13ecd35

I think the GIF is self-explaining :point_down:

**Video:**
![twitch_tab](https://cloud.githubusercontent.com/assets/10995998/16547086/a46c4042-4161-11e6-881e-0ab207469d87.gif)

**Comment by Nubbie** [comment]
Can not re-produce this

**Comment by mrtnptrs** [comment]
Can't reproduce it either. Can you reproduce this every time? When no, with which steps can you exactly reproduce it? Make sure to update your graphics driver to the latest version and check then if the issue is resolved.

**Comment by danidoedel** [comment]
Yep every time. Just drag the window around a bit.
I doubt that could be a driver issue as I think the graphics card doesn't render anything in software mode? Correct me if I'm wrong. I'm always running the latest version anyway.

**Comment by marijnvdwerf** [comment]
Taking this with me in #3977. In `windows/options.c:188` the endX is 10 pixels too much to the left.

**Comment by SijmenSchoon** [comment]
I have the same problem on OS X 10.11, commit f866e6fac2b88fb8f132469bc6ec68bfb25f504b, for what it's worth.

**Comment by danidoedel** [comment]
fixed (5204fb0)
