### ISSUE TITLE
Custom keybindings are not picked up

### ISSUE THREAD

**Issue by joepie91** [OpenRCT2/OpenRCT2#3982]
**OS:** openSUSE 13.1
**Version:** 0.0.4
**Commit/Build:** Stable

I have a custom keyboard mapping configured, mapping my Caps Lock to trigger a Backspace instead (`setxkbmap -option caps:backspace && xmodmap -e "clear Lock"`). However, this is not being registered by OpenRCT2, despite working fine in essentially every other game and application I use. The regular Backspace key works fine. 

The issue manifests throughout the game in all inputs I've tested. I don't have an original RCT2 installation set up (since I'm on Linux) and can't test it there.

**Steps to reproduce:**
1. Select an input or go to 'chat' mode in multiplayer
2. Type a character
3. Hit Caps Lock
4. _nothing happens_

**Comment by janisozaur** [comment]
@joepie91 looks like you're the perfect tester for https://github.com/OpenRCT2/OpenRCT2/pull/3908 :)

**Comment by Gymnasiast** [comment]
Indeed. The current set up uses scancodes - basically: it detects what button is pressed, not what is assigned to it. #3908 will change this, which should solve problems like this. If you can test it, please do so.

**Comment by Gymnasiast** [comment]
@joepie91 Could you test if this is still an issue with the current version of OpenRCT2?

**Comment by Gymnasiast** [comment]
This has been extensively reworked since 2016, and since there has been no message from OP, I’m closing this.
