### ISSUE TITLE
OpenRCT2 crash Multiplayer

### ISSUE THREAD

**Issue by joshbgosh10592** [OpenRCT2/OpenRCT2#3984]
**OS:** [Windows 7 x64]
**Version:** [0.0.5]
**Commit/Build:** [09863a4]
Server Crashed a few seconds after peeps explode cheat. Could have been something else causing the crash.
- [Probably not] Reproducible in RCT2 (vanilla)?
- [Yes] Multiplayer?

**Steps to reproduce:**
1. [Make peeps explode]
2. [Wait a few seconds. Might not be the cause, but that's what I did.

]

**Dump file**
[ed8c0f97-1f2e-4ce1-b961-875bfe89833a(09863a4).zip](https://github.com/OpenRCT2/OpenRCT2/files/346434/ed8c0f97-1f2e-4ce1-b961-875bfe89833a.09863a4.zip)

**Screenshots / Video:**
[Drag & drop screenshots here. Use https://vid.me to upload video.]

**Save game:**
[Fun3.zip](https://github.com/OpenRCT2/OpenRCT2/files/346435/Fun3.zip)

**Comment by Nubbie** [comment]
@joshbgosh10592 This could be from the peeps exploding, it can be a bit unstable with exploding peep if its spammed in multiplayer, might crash sometimes in my experience

----
-
To Devs: 

Error Message: 
Unhandled exception thrown: read access violation.
sprite_idx was 0x20E62BE.

Call Stack:
```
>	openrct2.dll!sprite_move(short x, short y, short z=0, rct_sprite * sprite=0x0117ffbc) Line 450	C
 	openrct2.dll!peep_update_ride_sub_state_5(rct_peep * peep=0x01249bbc) Line 2335	C
 	[External Code]	
 	openrct2.exe!006f09be()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for openrct2.exe]	
 	openrct2.exe!006c0075()	Unknown
 	openrct2.exe!005a4a7c()	Unknown
 	openrct2.exe!005a5494()	Unknown
 	openrct2.exe!005a4e90()	Unknown
 	openrct2.exe!005a4e58()	Unknown
 	openrct2.exe!005a52ba()	Unknown
```

Locals:
```
		current_position	Variable is optimized away and not available.	
		new_position	65536	int
		new_x	Variable is optimized away and not available.	
		new_y	Variable is optimized away and not available.	
+		sprite	openrct2.exe!0x0117ffbc (load symbols for additional information) {pad_00=0x0117ffbc "ÿ" unknown={sprite_identifier=...} ...}	rct_sprite *
+		sprite_idx	0x020e62be {???}	unsigned short *
+		sprite2	0x020e62bc {pad_00=0x020e62bc <Error reading characters of string.> unknown={sprite_identifier=??? misc_identifier=...} ...}	rct_sprite *
		temp_sprite_idx	Variable is optimized away and not available.	
		x	Variable is optimized away and not available.	
		y	Variable is optimized away and not available.	
		z	0	short
```

Autos 
```
+		&sprite2->unknown	0x020e62bc {sprite_identifier=??? misc_identifier=??? next_in_quadrant=??? ...}	rct_unk_sprite *
+		&sprite2->unknown.next_in_quadrant	0x020e62be {???}	unsigned short *
+		sprite	openrct2.exe!0x0117ffbc (load symbols for additional information) {pad_00=0x0117ffbc "ÿ" unknown={sprite_identifier=...} ...}	rct_sprite *
+		sprite2	0x020e62bc {pad_00=0x020e62bc <Error reading characters of string.> unknown={sprite_identifier=??? misc_identifier=...} ...}	rct_sprite *
+		sprite_idx	0x020e62be {???}	unsigned short *
```

**Comment by Nubbie** [comment]
Out of date/crash tag?

**Comment by Nubbie** [comment]
Is this crash still valid after a year?

**Comment by Nubbie** [comment]
Could not reproduce on commit 03299b9
And it's a 1 year old crash
