### ISSUE TITLE
HTTP request failed issue

### ISSUE THREAD

**Issue by birthdaybrian** [OpenRCT2/OpenRCT2#3988]
**OS: Windows 7 Home Premium x64 SP1 with Windows 8.1 UI**
**Version: 0.0.5-11**
**Commit/Build: f3786b3**

Hey guys. When I tried to play multiplayer, I get error messages in the console saying that HTTP request has failed which means that I couldn't connect to any server in OpenRCT2.

- [ ] Reproducible in RCT2 (vanilla)?
- [X] Multiplayer?

**Steps to reproduce:**
1. Launch OpenRCT2
2. Try to play multiplayer and see if you are able to reproduce this issue.

**Screenshots / Video:**
![httpbugrct](https://cloud.githubusercontent.com/assets/17324259/16568920/fb576282-41fd-11e6-8d47-80e30e02c65a.png)

**Comment by Patrik356b** [comment]
How is your network configuration on this computer?

**Comment by birthdaybrian** [comment]
@Patrik356b I am connected through XFINITY internet with LAN connection.

**Comment by IntelOrca** [comment]
If you do not have internet access then it will fail when trying to download the server list. Similarly if you advertise your server, it will fail to heatbeat. This should not prevent you from hosting or joining servers locally though.

**Comment by birthdaybrian** [comment]
Checked firewall in Norton Security Suite and found out that OpenRCT2 isn't blocked and is allow.

**Comment by birthdaybrian** [comment]
I already tried multiplayer in the stable build and still getting this message. I also tried to host a server and I am getting this message, cannot connect to master servers.

**Comment by PFCKrutonium** [comment]
Master Server is online, on the internet. You don't need it for local play, your issue is a firewall somewhere.

**Comment by birthdaybrian** [comment]
@PFCKrutonium My firewall in Norton allows OpenRCT2. I am wondering it's because of my router?

**Comment by birthdaybrian** [comment]
My router is a Arris TG862G-CT as I forgot to mention the router that I have.

**Comment by birthdaybrian** [comment]
I restarted my router and I still get this issue. I am going to try to get help on the OpenRCT2 forums to see if they can help me fix this issue.

**Comment by birthdaybrian** [comment]
I finally fixed this issue by moving the OpenRCT2 folder to my desktop and started OpenRCT2 fresh and I can now play multiplayer again. I found out that my old config file was corrupted.
