### ISSUE TITLE
Remember previous save/load location

### ISSUE THREAD

**Issue by ThePsionic** [OpenRCT2/OpenRCT2#3989]
I keep all my saves in my Dropbox folder so I can play them cross-computer, however the Open / Save dialogues always point to the OpenRCT2 saves folder by default. It would be nice if the last accessed folder could be remembered, so that I don't have to click through a ton of folders to get to my saves.

**Comment by SijmenSchoon** [comment]
I could take a look at this if you want

**Comment by janisozaur** [comment]
@ThePsionic you can symlink the save folder to one in dropbox.

**Comment by Patrik356b** [comment]
@janisozaur it doesn't completely solve this though

**Comment by SijmenSchoon** [comment]
I'm on it, finished it for loading saves, just gotta make it work for saving and scenarios too.

**Comment by SijmenSchoon** [comment]
This can be closed now!
