### ISSUE TITLE
'New in this build'

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#3991]
On the title screen, have a small window/box that pops up with the DEV build telling what's new from that build, either by taking the text from GitHubs merges (Like the website does) or have a small text document of some sort that we have to edit when we add new stuff

Useful for people who wants to see what's been added etc and it's 'more comforting' seeing it's moving forward

**Comment by mrtnptrs** [comment]
But the point is that most of the average users won't understand it and don't even know what a pull request is. :) I would vote "no" for this idea, but what do the others think?

**Comment by janisozaur** [comment]
This was discussed recently either here or on gitter and rejected. It'd be too tedious for us to provide a log of each and every entry, while it provides no useful information to the user if he is not familiar with the code. If you really want to know, you can use `git log`.
