### ISSUE TITLE
"Invalid vehicle type" and freeze when attempting to place Log Flume "Splash Mine".

### ISSUE THREAD

**Issue by CybertronicToon** [OpenRCT2/OpenRCT2#3992]
Windiws 8.1 U1 (6.3 build 9600)
0.0.5
build f3786b3

Attempting to place "splash mine" causes freezing, occasionally causes crash. Can be reproduced by hovering over, game will crash.

Console with text "invalid vehicle type":
https://i.sli.mg/bsxRus.png

Reproducible in RCT2 (vanilla)? No.
Multiplayer? No.

**Steps to reproduce:**
1. Go to any scenario
2. select log flume, select "splash mine", hover the cursor around for a bit.
3. the game will likely freeze, but occasionally, it will crash. The console may or may not say "invalid vehicle type"

**Dump file and save game**

[27a495b6-b2ac-408b-b14b-8bdf4b059643(b4886d5).zip](https://github.com/OpenRCT2/OpenRCT2/files/347127/27a495b6-b2ac-408b-b14b-8bdf4b059643.b4886d5.zip)

(save game reproduces crash)

**Screenshots / Video:**
![bsxrus](https://cloud.githubusercontent.com/assets/6559043/16574854/fef22044-4248-11e6-9138-439d2c3d9a4b.png)

(Screenshot of the first time I got the problem, game froze but didn't crash. Shows "invalid vehicle type")

**Comment by Nubbie** [comment]
Tried the game and got an error directly when I loaded the map

-
------
**To Devs**; This is what I got from OPs dump 

**Error message:**
Unhandled exception thrown: read access violation.
mapElement was nullptr.

**Call Stack:**
```
>	openrct2.dll!map_element_height(int x=1552, int y=1104) Line 425	C
 	openrct2.dll!game_command_place_scenery(int * eax, int * ebx=0x000cfcdc, int * ecx, int * edx, int * esi=0x000cfce8, int * edi, int * ebp) Line 2973	C
 	openrct2.dll!game_do_command_p(int command=15, int * eax=0x000cfcd8, int * ebx=0x000cfcdc, int * ecx=0x000cfce0, int * edx=0x000cfce4, int * esi=0x000cfce8, int * edi=0x000cfcec, int * ebp=0x000cfcf0) Line 487	C
 	openrct2.dll!track_design_place_scenery(rct_td6_scenery_element * scenery_start=0x08d2b87c, unsigned char originX=1632, int originY=1344, int originZ=208, int) Line 750	C
 	openrct2.dll!sub_6D01B3(rct_track_td6 * td6=0x05770c40, unsigned char bl, unsigned char rideIndex='\0', int x=1632, int y=1344, int z=208) Line 1283	C
 	openrct2.dll!place_track_design(short x=1632, short y=1344, short z=208, unsigned char flags='i', unsigned char * outRideIndex=0x000cfda4) Line 1451	C
 	openrct2.dll!game_command_place_track_design(int * eax, int * ebx=0x000cfe0c, int * ecx, int * edx=0x000cfe08, int * esi=0x000cfe04, int * edi=0x000cfe20, int * ebp=0x000cfe00) Line 1647	C
 	openrct2.dll!game_do_command_p(int command=48, int * eax=0x000cfe10, int * ebx=0x000cfe0c, int * ecx=0x000cfe18, int * edx=0x000cfe08, int * esi=0x000cfe04, int * edi=0x000cfe20, int * ebp=0x000cfe00) Line 524	C
 	openrct2.dll!window_track_place_attempt_placement(rct_track_td6 * x, int y, int z=208, int bl, int cost=0x000cfe44, int * rideIndex=0x000cfe3c, unsigned char *) Line 438	C
 	openrct2.dll!window_track_place_toolupdate(rct_window * w=0x5ace7028, int widgetIndex=6, int x=531, int y=355) Line 276	C
 	openrct2.dll!process_mouse_tool(int x=531, int y=355) Line 1170	C
 	openrct2.dll!game_handle_input(...) Line 166	C
 	openrct2.dll!game_update(...) Line 345	C
 	openrct2.dll!rct2_update(...) Line 462	C
 	openrct2.dll!openrct2_loop(...) Line 456	C
 	openrct2.dll!openrct2_launch(...) Line 328	C
 	openrct2.dll!StartOpenRCT(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance=0x00000000, char * lpCmdLine=0x01662e77, int nCmdShow=1) Line 109	C
 	openrct2.exe!004069e4()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for openrct2.exe]	
 	[External Code]	
```

**Locals;**
```
		height	Variable is optimized away and not available.	
-		mapElement	0x00000000 <NULL>	rct_map_element *
		type	<Unable to read memory>	
		flags	<Unable to read memory>	
		base_height	<Unable to read memory>	
		clearance_height	<Unable to read memory>	
+		properties	{surface={slope=??? terrain=??? grass_length=??? ...} path={type=??? additions=??? edges=??? ...} track=...}	rct_map_element_properties
		quad	Variable is optimized away and not available.	
		quad_extra	0 '\0'	char
		slope	Variable is optimized away and not available.	
		x	1552	int
		x_tile	Variable is optimized away and not available.	
		y	1104	int
		y_tile	Variable is optimized away and not available.	
```

**Comment by duncanspumpkin** [comment]
Retest after the latest commit. I think this is probably due to the map insert element corruption.

**Comment by janisozaur** [comment]
After https://github.com/OpenRCT2/OpenRCT2/pull/4129 the error is a bit more obvious:

> Tried getting sprite 20500

@duncanspumpkin do you want to investigate further or should this get closed?

**Comment by duncanspumpkin** [comment]
Are there any newer reports of the same issue. If its the map element corruption bug there is no way for us to test this save as the map elements are corrupted.

**Comment by janisozaur** [comment]
This seems to be the only report of its kind.
