### ISSUE TITLE
Monochromatic animated objects 

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#3999]
v0.0.5 6a5ecf0

I noticed that in one of my park all the animated flags objects had turned completely black. They're supposed to be blue with black poles. The pole and the flag are seperately colourable, but it takes the colour selected in the first custom colour slot and uses it as the second colour as well. Hence why the flag pole colour is now the flag's colour too. Other animated objects have this too, although I haven't tried it with animated walls yet.

**Comment by IntelOrca** [comment]
Can you upload screenshots and a park?

**Comment by Liampie** [comment]
![scr73](https://cloud.githubusercontent.com/assets/19242088/16649385/0957ac92-4439-11e6-8c48-a654a0678a45.png)


Note the selected colours and how they show differently in the scenery window and the actual placed object.

[Crazy Castle.zip](https://github.com/OpenRCT2/OpenRCT2/files/351854/Crazy.Castle.zip)
