### ISSUE TITLE
Bug in original Rollercoaster Designer

### ISSUE THREAD

**Issue by ghost** [OpenRCT2/OpenRCT2#400]
Test case. In Rollercoaster Designer, build a looping coaster to this specification:

Filename:   Spin Drier.TD6
Ride Type:  Looping Roller Coaster
Vehicle Type:   Looping rollercoaster trains (1 7-car train)
Operating Mode: Powered Launch Mode, speed 49 mph

1-10    10  Helix down left [R2](11 to 1)
11      Helix down left [R3](1 to 0)
12      Roll left to level (0)
13      On-ride photo section (0)
14      Level to up (0 to 1)
15      Vertical loop left (1 to 0)
16      Down to level (0)
17      Begin station (0)
18-21   4   Middle station (0)
22      End station (0)
23-25   3   Level (0)
26      Level to up (0 to 1)
27      Vertical loop right (1 to 0)
28      Down to level (0)
29      Level (0)
30      Level to up (0 to 1)
31      Up to up steep (1 to 3)
32-36   5   Up steep (3 to 23)

It looks like this

![spin drier](https://cloud.githubusercontent.com/assets/8623605/4140570/7dcdc3a4-33a6-11e4-9c9a-8ce0cdf94d80.png)

Set launch speed to 49mph. Test so you can then save.

Now in coaster designer try and plant another copy of the ride into the designer using your saved file.

Bug: It is 5 feet higher than the original and refuses to be lowered to zero height.

Further, if you place it in a park in a scenario, add a queue line, and 'save with scenery' a 2nd copy with the queue lines added 2 things happen with the copy.

1) You cannot see a preview picture when you select it to be added into a park from the coaster builder menu.
2) When you place it in the park, the queue lines that you saved with the ride are placed at the incorrect height and no longer join onto the entrance and exit.

**Comment by frutiemax** [comment]
Just for fun, I've recreated this roller coaster in the track designer, tried to save it, but I get the Can't save track design... Ride is too large, contains too many elements, or scenery is too spread out.

![bugRollerCoaster](https://user-images.githubusercontent.com/12629817/85203561-a4767f80-b2dc-11ea-9bce-d26ea50df9d1.PNG)

This is on v0.2.6 Master.

**Comment by frutiemax** [comment]
So I've analyzed this a bit, and I arrived to the conclusion that there is a problem when the first element on the roller coaster in the direction of the train is a small helix. When I add a straight segment, the roller coaster can save itself.
![smallHelixBug](https://user-images.githubusercontent.com/12629817/85205125-2a97c380-b2e7-11ea-9cf1-e9acd5257d9d.PNG)
