### ISSUE TITLE
Permissions/Group bug - not sticky to user's machine

### ISSUE THREAD

**Issue by joshbgosh10592** [OpenRCT2/OpenRCT2#4004]
When assigning a user to a group, if they log out and then back in as another name on the same server, the group they are assigned to is reset.

**OS:** Windows 7 x64
**Version:** 0.0.5
**Commit/Build:** 6c0d4c5

When assigning a user to a group, if they log out and then back in as another name on the same server, the group they are assigned to is reset. (Not sure where to put it, so I'll put the description in both places

- [No] Reproducible in RCT2 (vanilla)?
- [Yes] Multiplayer?

**Steps to reproduce:**
1. Log into a server
2. Have admin assign you a group
3. Disconnect and reconnect as a different name
4. Notice group is now the default group.

I can upload a video if required, but this is reproducible 100% of the time.

**Comment by janisozaur** [comment]
Works as intended. The assignment is not per machine, but per user key.

**Comment by joshbgosh10592** [comment]
I believe this should be re-evaluated. It allows spammers to be able to simply change their name and continue to cause trouble in parks.

**Comment by janisozaur** [comment]
That's why you should set default group as a one with limited permissions and only elevate permissions for trusted clients.

This is by design.

**Comment by joshbgosh10592** [comment]
Maybe so, but think of this case:
Someone logs in, and starts chatting obscenities. You set them to no chat group. They logout, and change their name. They are then allowed to chat again.
You can't set the default group to no chat, because then how will anyone request permissions? On my server, people are always asking for this. Multiple people would strongly feel this should be re-evaluated. We shouldn't have to whitelist our server, just because of one spammer.

**Comment by janisozaur** [comment]
There is simply no way we can implement "per machine" checks that you request.

**Comment by joshbgosh10592** [comment]
Just a suggestion, what if during the install process, a hash was generated and stored (only the first time this change would be implemented)? Then, that hash is used instead of the current hash value?

**Comment by janisozaur** [comment]
And how exactly would this be different?

**Comment by joshbgosh10592** [comment]
Because right now, I believe the hash is created when they connect to the server using their name. This way, the hash is based on the install, which cannot be easily changed, rather than a name that someone enters into a text field.
It would make it much more difficult to spam once that user/hash has been blocked.

**Comment by janisozaur** [comment]
Your suggestion is wrong on so many levels…

How do you envision the key creation takes place when user does not *install*, but simply launch the game?
How do you ensure the key is generated then and only then?
How do you prevent user from re-generating a key?
How do you let user transfer a key between his multiple machines, so he can maintain his identity?
How do you let user then generate a key *again* in case the first one got lost/removed/malformed/…?

And yet, it is still exactly the same as current process: user generates a key and uses it to authenticate himself on a server.

Please come back to us when you have found answers to all these questions.

**Comment by joshbgosh10592** [comment]
_How do you envision the key creation takes place when user does not install, but simply launch the game?:_ 
**Either when they install the update for OpenRCT2, or upon first launch of OpenRCT2.exe, if hash check fails (file doesn't exist/unreadable), then regen. This shouldn't happen, unless the user is tinkering with config files.**

_How do you ensure the key is generated then and only then?:_ 
**Store is in a config file. Most spammers, unless they also have a programming background, won't understand how files are called. Even if they are, this is to discourage, not block. Changing it could require closing the game completely, modifying the file, then relaunching it (similar to users.json/groups.json).**

_How do you prevent user from re-generating a key?:_ 
**This is to discourage, not completely block. Maybe make the hash file hidden to further discourage.**

_How do you let user transfer a key between his multiple machines, so he can maintain his identity?_
**If the users is that worried about it, copy the file. Not sure/never tried, does everything link to a  name? If so, anyone could just connect with an admin name and take over the server. If anything, this is even more of a push for this.**

_How do you let user then generate a key again in case the first one got lost/removed/malformed/…?_
**See above. It can regen, or have the "first launch" make a backup.** 

_And yet, it is still exactly the same as current process: user generates a key and uses it to authenticate himself on a server._ 
**Maybe so, but it's easily changed, which is the whole point to me bringing this up.**

I'm only trying to help push the game forward. I know a lot of admins, including myself, are getting very frustrated with the rise of spammers. I'm simply bringing up a possible solution.

**Comment by janisozaur** [comment]
> Either when they install the update for OpenRCT2, or upon first launch of OpenRCT2.exe, if hash check fails (file doesn't exist/unreadable), then regen. This shouldn't happen, unless the user is tinkering with config files.

So right there, in the very first point, you dismiss everything your *feature* suggestion is about.

**Comment by joshbgosh10592** [comment]
Look, just because you see a slight flaw in my proposal, doesn't mean it's complete garbage. Your current "authentication" method is seriously flawed. I'm proposing a better way, which makes spoofing your identify harder than modifying a simple text field.

**Comment by joshbgosh10592** [comment]
Besides, my proposal is about discouraging spoofing, not completely blocking it. Without actual authentication (with passwords) methods, I can't see how you could completely block it.

**Comment by janisozaur** [comment]
> just because you see a slight flaw in my proposal

This is not "slight flaw", this is you wanting to cover one issue (people being mean) with a plethora of other new problems. There will never be enough technical solutions to non-technical problems like this one.

> Your current "authentication" method is seriously flawed

It is not, you misunderstand its purpose. It is not to meant to filter out evil clients at will, but to promote the good ones and being able to identify them reliably.

If you feel so strongly about your suggestion, be my guest and please contribute it.

**Comment by Gymnasiast** [comment]
This is not getting anywhere. The drawbacks you mention are real, but no system is perfect, and the current system has been chosen for several reasons already explained by Janisozaur in detail. 

I'm therefore locking this issue.

**Comment by IntelOrca** [comment]
@joshbgosh10592 what you are asking requires a central authorisation server. The same thing we need to stop impersonation across severs.

#3155 was my original plan, but many users were against the idea of a central authorisation server. You can continue the discussion there though if you are for it.
