### ISSUE TITLE
Host with a certain cheat

### ISSUE THREAD

**Issue by HtHNightwolf** [OpenRCT2/OpenRCT2#4005]
Dear community. Once a day I have to restart my hosted openrct2 headless server.
I do that by chronjob. But every time I relogg everything is vandalized. Is there a way to start the server with "Deactivate Vandalism" checked?

**Comment by Nubbie** [comment]
@HtHNightwolf It's not possible to start a server with a certain cheat on sadly enough as all cheats gets reset to the default value which is off

**Comment by Patrik356b** [comment]
Cheats aren't synced (yet)

**Comment by janisozaur** [comment]
Yes they are

**Comment by duncanspumpkin** [comment]
@janisozaur this is about having cheats preset on servers not about sending the cheats over multiplayer.

**Comment by HtHNightwolf** [comment]
@Nubbie Can I edit the default value then in some .ini file?

**Comment by HtHNightwolf** [comment]
Bump.
Where is the default value of a cheat set?

**Comment by janisozaur** [comment]
It's hardcoded

**Comment by ZehMatt** [comment]
Can be solved with scripting now I believe.
