### ISSUE TITLE
Using right mouse button to scroll in lists moves list to the top

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#4010]
OS: GNU/Linux (Arch Linux)
Version: 0.4.0
Known in RCT2? I don't know.
Mutliplayer? N/A

If you use the right mouse button to scroll in windows (e.g. scrollable lists like in the staff menu, the map, and so on, mostly those windows have scroll bars), OpenRCT2 scrolls the list or map or whatever very quickly to the top only, no matter in which direction you are moving the mouse.

Edit: The scrolling happens as long as you hold down the mouse button. You don't need to move the mouse. Also, if you release the mouse button, you will see that the cursor has “jumped” somewhere above and left of the original position. Very strange.

**Comment by Wirlie** [comment]
You are using OpenRCT2 0.0.4? I've introduced a recently fix (0.0.5), Can you test the latest build?

**Comment by gDanix** [comment]
I can't confirm this bug on GNU/Linux (Ubuntu), commit [9efc0ca](https://github.com/OpenRCT2/OpenRCT2/commit/9efc0cab6a5c77a4bf47e67d8e84a39c4af6164e) (+1 small brake-block related fix)

Using the right button let me navigate the list in a 2D style (both horizontal and vertical).

**Comment by Wuzzy2** [comment]
Okay, right mouse button scrolling works fine as of 76b2621.
