### ISSUE TITLE
Allow user to choose between tracks included with the game and user track directory

### ISSUE THREAD

**Issue by SijmenSchoon** [OpenRCT2/OpenRCT2#4019]
**Version:** 0.0.5-develop
**Commit/Build:** e9bdad807944fc2d747c2a3714b98f0c8f0ba26b

Currently, the Default button in the track load/save directory window always points to the directory with tracks included with the games, leaving no easy way to browse to the user track directory.

It might be nice to have a dropdown menu appear when clicking on the Default button, allowing the user to choose between these two directories.

**Comment by marijnvdwerf** [comment]
Isn't the RCT2-tracks folder due to become immutable anyhow? /cc @IntelOrca

**Comment by SijmenSchoon** [comment]
Yeah, it probably makes more sense to default to the user track directory when saving, but there's still the problem of loading.

**Comment by IntelOrca** [comment]
The default should be the user directory.

**Comment by SijmenSchoon** [comment]
Alright, I'll create a PR after finishing #4018
