### ISSUE TITLE
Mac: Launching game, cursor off. Work around, full screen app, then restore to windowed

### ISSUE THREAD

**Issue by joshbgosh10592** [OpenRCT2/OpenRCT2#4022]
Lower priority, but, when launching the OpenRCT2 game, the game defaults to a large windowed view. While in this view, after launching, the cursor is off by about 3 inches.
Once you full screen (Green button), selection is normal, even if you switch game back to windowed view.

**OS:** [Mac OS X 10.11.5]
**Version:** 0.0.5
**Commit/Build:** 7d21e10 **NOTE: This does not appear on the main screen on the Mac version.**

When launching the OpenRCT2 game, the game defaults to a large windowed view. While in this view, after launching, the cursor is off by about 3 inches.
Once you full screen (Green button), selection is normal, even if you switch game back to windowed view.
- [n] Reproducible in RCT2 (vanilla)?
- [Y] Multiplayer?

**Steps to reproduce:**
1. Open game, 
2. Click on multiplayer and move cursor

**Screenshots / Video:**
(My coursor vanishes when taking a screenshot, but my coursor was hovering over "ManOfTeal.COM Nostalgic Park".
![screen shot 2016-07-09 at 12 19 22 pm](https://cloud.githubusercontent.com/assets/20283787/16708906/8b8f9dfe-45cf-11e6-892c-fa354e1c1cab.png)

**Comment by SijmenSchoon** [comment]
Yeah, I'm having this issue too, OS X 10.11.5

**Comment by joshbgosh10592** [comment]
It also appears that the text is slightly cut off at the top. Is that just me?

**Comment by raphaelsetin** [comment]
This issue is being addressed/investigated by me, in this new, open pull request I made #5385

**Comment by aidan-waite** [comment]
PR is up here: https://github.com/OpenRCT2/OpenRCT2/pull/13095

**Comment by MichaelJBerk** [comment]
I've been a bit annoyed that fullscreen preference isn't saved on MacOS, as a workaround for a cursor offset bug (See issue #4022 and PR #13095). However, after commenting out the workaround and testing it, I can't seem to recreate it anymore. 

I'm unsure as to what could have fixed the issue - it could be a buxfix in SDL2, or something in macOS - but it may make sense to evaluate whether or not this workaround should be kept
