### ISSUE TITLE
Mac: Unable to cheat on Mac OS

### ISSUE THREAD

**Issue by joshbgosh10592** [OpenRCT2/OpenRCT2#4023]
**OS:** Mac OS X 10.11.5 (Not in Wine)
**Version:** 0.0.5
**Commit/Build:** 7d21e10

When in OpenRCT2, both single player and Multiplayer, the cheat button is unavailable, even if user is admin/granted cheat permissions. Confirmed permissions are set by setting other users to another group/other things that only elevated users have permissions to do.

- [ ] Reproducible in RCT2 (vanilla)?
- [Both in and outside of] Multiplayer?

**Steps to reproduce:**
1. Spend a lot of money a buy a Mac
2. Install an awesome old school game called RCT2, then, OpenRCT2
3. Realize I'm just being a smartass, and open OpenRCT2 and attempt to cheat. Notice missing golden shovel.

**Screenshots / Video:**
![screen shot 2016-07-09 at 2 16 14 pm](https://cloud.githubusercontent.com/assets/20283787/16709502/834155a0-45e0-11e6-8c85-0d1b9f9a5cc6.png)

**Comment by Gymnasiast** [comment]
We figured that people who have enough money for Mac computers could easily buy everything themselves in the game. It's not a bug, it's a feature.

Nah, just go to the Options window and enable the cheat button. It's not actually Mac or multiplayer related.

**Comment by joshbgosh10592** [comment]
...Sorry... I forgot that's not default.
Can we file this under, "bug existed between chair and keyboard"?
Thanks!

**Comment by IntelOrca** [comment]
@joshbgosh10592 Yes... `non-bug`

**Comment by joshbgosh10592** [comment]
(Just a joke, I knew it was filed under non-bug, just think there should be a tag labeled that lol (Kidding, again))
Thanks!
