### ISSUE TITLE
Costs of land rights are no longer displayed while hovering a tile

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#4031]
**OS:** GNU/Linux (Arch Linux)
**Version:** 0.0.5-develop
**Commit/Build:** 59c3656

In version 0.0.4, the cost of buying land was displayed when you were hovering a buyable tile. This was very useful, but does not work anymore in said development version (see above) after 0.0.4. Plase re-introduce this feature, I am pretty sure it has been removed by accident since I see no reason at all to do so.

- Reproducible in RCT2 (vanilla)? I don't know.
- Multiplayer? N/A

**Steps to reproduce:**
1. Start any scenario with buyable tiles
2. Unpause
3. Hover a buyable tile and see if its cost is displayed in the land rights window

**Comment by Patrik356b** [comment]
Does it work for build rights?

**Comment by Wuzzy2** [comment]
No.

**Comment by Gymnasiast** [comment]
Would you care uploading a screenshot of this feature in 0.0.4?

**Comment by Wuzzy2** [comment]
Here:

![unbenannt](https://cloud.githubusercontent.com/assets/1675853/16716061/b48f6b30-46f1-11e6-9d7f-9a3a4c140b37.png)

Note the cursor is not shown in the screenshot.
