### ISSUE TITLE
Less confusing treatment of default title sequences in title sequence window

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#4035]
**OS:** GNU/Linux (Arch Linux)
**Version:** 0.0.5-develop
**Commit/Build:** 59c3656

- Reproducible in RCT2 (vanilla)? N/A
- Multiplayer? N/A

The way how default title sequences are treated in the options and title sequence window is a bit confusing and user-unfriendly. So I have some suggestions.

First, I want you to rename the first 3 options for clarity:

* “RollerCoaster Tycoon 1” → “RollerCoaster Tycoon”
* “RollerCoaster Tycoon 1 (AA)” → “Added Attractions / Corkscrew Follies”
* “RollerCoaster Tycoon 1 (AA + LL)” → “Loopy Landscapes”

I dropped the “RollerCoaster Tycoon” for the expansions because it would make the name too long and those who have the expansions are already aware. I am not sure why you called it “AA + LL” and not just “LL”. Does it mean that in RCT2 the title sequence does only play if the player has both expansion packs installed? Are there differences for the following combinations?:

* RCT + AA
* RCT + LL
* RCT + AA + LL

(I only know the difference between RCT without expansion packs and RCT + AA + LL. If RCT + LL and RCT + AA + LL are the same, I would use the name “Loopy Landscapes” only.)

Also should “gray out” (disable) each entry for which it couldn't find the neccessary files. Currently, you can seemingly select them but OpenRCT2 just reverts to the default if the files are missing, there is not even an error message, nothing.

Finally, I don't think it should be possible to “edit” these default title sequences in any way, instead the player is supposed to duplicate, then edit them. I don't know if OpenRCT2 even saves any edits to these sequences or just discards them, but in any case I think this would be not correct IMO.

Edit: For some reason, only the OpenRCT2, RCT2 and RCT + AA + LL title sequences can be “fake edited”, there is actually an error message when you try to edit RCT or RCT + AA.

**Comment by IntelOrca** [comment]
> Added Attractions / Corkscrew Follies

No need do this as it will change based on your language. en-GB will use 'Added Attractions' and en-US will use 'Corkscrew Follies'. Other language also do this respective of what was released in said relevant country.

As for un-abbreviating them, it would just get cropped in the drop down box making harder to see what's selected.

**Comment by Wuzzy2** [comment]
> As for un-abbreviating them, it would just get cropped in the drop down box making harder to see what's selected.

“Added Attractions”, “Corkscrew Follies” and “Loopy Landscapes” alone fit perfectly into the drop-down lists, I have tested it.
Also note even the longest name I suggested will *not* get cropped if you open the drop-down list in the options menu. Cropping only happens in the title sequence selection (and, sadly, in the unopened drop-down list). So this seems to be more an issue with the GUI.
But if we choose to also use the `en-US` strategy you suggested, we are probably fine, since everything fits. :-)

**Comment by IntelOrca** [comment]
> “Added Attractions”, “Corkscrew Follies” and “Loopy Landscapes” alone fit perfectly into the drop-down lists, I have tested it.

Only when its open... I am talking about when its not.

**Comment by Wuzzy2** [comment]
This is impossible. “RollerCoaster Tycoon 1” fits into the window, and the names “Loopy Landscapes”, “Added Attractions” and “Corkscrew Follies” are ALL shorter than that (in terms of actual space used by the font), and they fit in every imaginable way into the drop-down lists, even when it is selected. At least for me. Is it not the case for you?
If so, that's strange, because then the entry “RollerCoaster Tycoon 1” must also appear be cropped for you.
Which version/resolution are you using?
