### ISSUE TITLE
Track name renaming dialog does not allow names longer than 31 characters

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#4036]
**OS:** GNU/Linux (Arch Linux)
**Version:** 0.0.5-develop
**Commit/Build:** 59c3656

- Reproducible in RCT2 (vanilla)? I don't know, but as far I know it was not an issue in RCT.
- Multiplayer? N/A

It is not possible to enter a long track name when you want to rename a track. You cannot enter more than 31 characters, it is artificially limited.
If the track already had a longer name, the rename dialog automatically removes excess characters.

OpenRCT2 seems perfectly capable of saving and loading games which contain tracks with longer names. One way to easily this is to use the German version of OpenRCT2 and start to build a “Achterbahn mit Seitlicher Führung” (“Side Friction Roller Coaster” in English), the initial name will be “Achterbahn mit Seitlicher Führung 1” which is perfectly displayed and capable of being saved and loaded into a savegame. Only if you try to use the “rename” button you will “lose” characters.

**Comment by Gymnasiast** [comment]
That's because the initial name is not saved but directly loaded from the translation files and thus capable of having more than 31 characters.

**Comment by Wuzzy2** [comment]
Wait. So are the 31 characters for track names a hard limit which can not be overcome easily?

**Comment by IntelOrca** [comment]
I think the track name is just what ever you call the file.

**Comment by Wuzzy2** [comment]
I mean the name of tracks in savegames, not in files containing the track only.

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/ride/ride.c#L5520

**Comment by IntelOrca** [comment]
@Wuzzy2 if you are talking about ride names then yes there is a limit. There is a limit for any user string in SV6. The user string table... We can't change it until we move to our own format. And using non-ASCII characters will also reduce the maximum length further.

**Comment by Gymnasiast** [comment]
I have occasionally hit that limit. When we switch to our own format I think we should raise it, to 64 or something like that.
