### ISSUE TITLE
Text fields: Putting the cursor on a non-ASCII character makes it long

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#4037]
**OS:** GNU/Linux (Arch Linux)
**Version:** 0.0.5-develop
**Commit/Build:** 59c3656

- Reproducible in RCT2 (vanilla)? Probably not if it used the Windows dialog.
- Multiplayer? N/A

How to reproduce:
* Find any dialog with a text field (e.g. track renaming, renaming of theme, etc.)
* In the text field, only enter some non-ASCII or “foreign” characters like the German umlauts “ä”, “ö”, “ü”, “Ä”,“Ö” and “Ü”
* Now move the text cursor over each of the characters by pressing the left cursor key on your keyboard and see how the cursor looks like

Expected: The cursor blinks only below the current character
Actual: The cursor blinks below the current character plus it is much long than it is supposed to be, unless it is the first character. The cursor becomes longer the further “right” the character was

**Comment by IntelOrca** [comment]
UTF-8 issue, codepoints vs bytes.

**Comment by Patrik356b** [comment]
Happens on windows too. http://puu.sh/pWMci/1da1db8235.png
