### ISSUE TITLE
Incorrect quotation marks in German

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#4039]
**OS:** GNU/Linux (Arch Linux)
**Version:** 0.0.5-develop
**Commit/Build:** 59c3656
- Bug present in RCT2? Yes.
- Multiplayer? N/A

The quotation marks in the German localization are incorrect.

Like this:

> “Reale” Parks

Where it should be:

> „Reale“ Parks

I would normally post this to the localization repository but this can't be fixed by changing the German localization at the moment since this requires some characters which are not supported at the moment:
- Opening double quotation mark: „ (U+201E) (not supported)
- Closing double qutation mark: “ (U+201C) (supported)
- Opening single quotation mark: ‚ (U+201A) (not supported)
- Closing single quotation mark: ‘ (U+2018) (not supported)

Optional characters (optional in German in Germany, but used by a couple of other languages):
- Left guillemet: « (U+00AB) (supported)
- Right guillemet: » (U+00BB) (supported)
- Left single guillemet: ‹ (U+2039) (not supported)
- Right single guillemet: › (U+203A) (not supported)

So fixing this issue will involve adding support for the missing characters (step 1) and then update the localization files for German accordingly.
There are also a few other languages which use these characters, so it will be useful for these, too.

**Comment by Goddesen** [comment]
I was under the impression reverse guillemets were the most used quotation scheme for digital text - why not use these?

**Comment by danidoedel** [comment]
At least not in Germany ;) But they are used for printing (books etc.)

**Comment by Wuzzy2** [comment]
Guillemets are an accepted alternative for quotation marks in Germany, but still OpenRCT2 should support all quotation marks, not just for German but all other languages out there.

And yes, using guillemets would solve this problem at least for German.

**Comment by Gymnasiast** [comment]
I have created #4039 to add support for the missing German quotes.
The German translation would still have to be modified, but replacing the double quotes should be easy.
