### ISSUE TITLE
Consistent naming of the original games

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#4040]
This is a minor issue for me since it annoys me a little bit.

Throughout OpenRCT2, I think the original games RollerCoaster Tycoon and RollerCoaster Tycoon 2 should normally be written out if there is enough space and abbreviations should be avoided if possible (OpenRCT2 is not a forum or chat).
Also, drop the “1” in “RollerCoaster Tycoon 1” and “RCT1”, because the “1” is not part of the game name.
Instead of “RCT2”, use “RollerCoaster Tycoon 2” if you have the space.

It is okay to use the abbreviations “RCT” and “RCT2” for “RollerCoaster Tycoon” and “RollerCoaster Tycoon 2” if you are low on space or for development tools. In tooltips those names should generally be written in full.

Places where the game names appear:
* Names of title sequences
* Tooltip of the option which enables capital letters for ride banners
* Tooltip of title music selection in the options
* Default theme names
* Tooltip of option to sort rides by track type (it's okay to use “RCT” (not “RCT1”) in the option name itself)
* Tooltip of scenario sorting option
* Scenario of scenario unlocking
* Tooltip of handymen mow grass by default option
* Checkboxes in “Features” tab of theme editor (use “RCT” instead of “RCT1”, maybe add tooltips if you want to)
* Probably some other places I forgot, they might be found by searching for “RCT1” and “RCT2” and “RollerCoaster Tycoon 1”

**Comment by Nubbie** [comment]
You could make a PR about this too to 'fix' it, here is the file that you should edit:
https://github.com/OpenRCT2/OpenRCT2/blob/develop/data/language/en-GB.txt

I think it's better to keep everything consistent with 'RCT1/RCT2' instead of mixing it around

**Comment by Gymnasiast** [comment]
Completely pointless IMO. And we use a `1` to properly distinguish the first game in the series from the sequels. Dropping the `1` only makes all those strings more ambiguous.

**Comment by Wuzzy2** [comment]
How is it “pointless”?
And no, it is not ambigious. There is only one game called “RollerCoaster Tycoon”, and one game called “RollerCoaster Tycoon 2”. There is zero ambiguity here, even without the “1”. If I say “RCT” or “RollerCoaster Tycoon” it is clear that I don't mean number 2 or 3 or RollerCoaster Tycoon World and what other titles might exist.
Why not just stick to the original title? o_O

Whatever. But well, since you like to unilaterally rename games, then I will henceforth refer to OpenRCT2 as “OpenRCT2 1” to “properly” distinguish it from the future sequels OpenRCT2 2 and OpenRCT2 3. ;-)


Other opinions, please?

**Comment by Gymnasiast** [comment]
Do you honestly expect much goodwill from my part if you keep being so arrogant? Not only here, but in many other issue reports and feature requests as well.

**Comment by janisozaur** [comment]
@Wuzzy2, while your points have some merit, we prefer to clearly distinguish which game are we talking about in particular context, which is in line with most of our community. See https://www.reddit.com/r/rct

Had there been no RCT2, the original game would probably still be called just "RCT" but in their presence it may also mean the genre/3 games under the same title. You sound silly trying to call the project "OpenRCT2 1" now, but it may make sense when there's another project called "OpenRCT2 2" and to differentiate between them, you'd have to append "1" to our name.

I second the `wontfix` applied to this issue report.

**Comment by IntelOrca** [comment]
@Wuzzy2 is reporting that there is inconsistency. So I think we should always refer to RCT1 as either RCT1 or RollerCoaster Tycoon 1, abbreviating where appropriate (like for title sequence dropdown).

**Comment by Gymnasiast** [comment]
That's not what he says though. He wants us to drop the `1` in `RCT1`.

**Comment by IntelOrca** [comment]
> Checkboxes in “Features” tab of theme editor (use “RCT” instead of “RCT1”, maybe add tooltips if you want to)

**Comment by IntelOrca** [comment]
Okay, there is actually only one usage I can find of RCT on its own.

https://github.com/OpenRCT2/OpenRCT2/blob/develop/data/language/en-GB.txt#L3960

**Comment by Wuzzy2** [comment]
Whatever. Since you all seem to heavily insist on keeping the “1” in the name (even if its not *actually* part of the name and just redundant IMO), I just drop this issue. There are more important things to discuss.

And the “OpenRCT2 1” thing was just a very silly joke, of course. :P

**Comment by IntelOrca** [comment]
> There are more important things to discuss.

There definitely are, this is very trivial in comparison to the more important things that need doing. And controversial it seems.
