### ISSUE TITLE
Doubly written text in scenario options when using custom theme color

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#4041]
**OS:** GNU/Linux (Arch Linux)
**Version:** 0.0.5-develop
**Commit/Build:** 59c3656
- Reproducible in RCT2 (vanilla)? I don't know.
- Multiplayer? N/A

**Steps to reproduce:**
1. Start scenario editor
2. Go all the way until the step “Options Selection”
3. Click on the park options tab
4. Select “Pay to enter park”
5. Open the options window (game options, not scenario options)
6. Create a new theme by duplicating the RCT2 one
7. Select the new theme
8. Edit the theme: Choose a different color for the second color in the entry “Scenario Options” of the “Editors” tab
9. Now look at the drop down list you changed in step 4

Expected: The text looks normal and is readable
Actual: The text looks weird and is hard to read

This is how it looks like for me (using my custom theme):
https://i.imgur.com/XPDXUX4.png

Funny is, this bug seems _only_ to manifest for only some particular colors. For a few colors, including gray (i.e. the color used in the “RCT1” and “RCT2” themes), the bug is invisible.

If you look closely, it seems that the other text of this drop-down list is just “written over” the other one. You can easily see it when you switch between the drop-down list entries after following my steps.

**Comment by Horsti12** [comment]
This Bug still happends with the current version of OpenRCT2.

**Comment by tupaschoal** [comment]
Still happens in v0.3.1
