### ISSUE TITLE
Split Flying Turns and Bobsled Coaster

### ISSUE THREAD

**Issue by Generalcamo** [OpenRCT2/OpenRCT2#4044]
One of the things that bugged me about RCT2 is that the Flying Turns and Bobsleigh Coaster use the exact same track. Even though the Flying Turns coaster is a wooden coaster, not a steel coaster as depicted currently in-game. RCT3 did correctly depict the Flying Turns as a wooden-based roller coaster, and we could probably give the current bobsled coaster Wooden Supports instead of Steel Supports for a close approximation until new graphics are made.

However, could we split the two track types in OpenRCT2? Right now, in RCT1 mode, the two are lumped together, which might make doing such a thing as described above impossible.

**Comment by Gymnasiast** [comment]
Except that there are several roller coasters that actually use cars as depicted in Flying Turns, but on steel bobsleigh track. Two examples are Swiss Bob from the Efteling and the La Vibora.
Also, adding track types is not possible until we switch to our own format, and even then it's not very easy.

**Comment by IntelOrca** [comment]
We might be able to make it have wooden supports after we implement the drawing for it...

**Comment by X123M3-256** [comment]
> Right now, in RCT1 mode, the two are lumped together

That's because they're the same track type. The flying turns in RCT2 is mislabelled - it is actually an Intamin bobsled, a modern steel kind. There is no wooden flying turns in RCT2 and adding one would require adding a new track style, which can't be done just yet.

**Comment by IntelOrca** [comment]
You could probably get away with it by colouring the track brown and using wooden supports though.

**Comment by X123M3-256** [comment]
[Sure, that works](http://i.imgur.com/0HaYxWO.png)

**Comment by IntelOrca** [comment]
@X123M3-256 nice! Its probably not something we can do really until we have our own object format so that it can specify to use wood supports. On the other hand this would usually be done by have a completely separate ride type anyway seeing as track type is bound to ride type rather than object. (Although I don't think that should be the case anyway)

**Comment by Wuzzy2** [comment]
As far I know, those two attractions really *are* the same except for the cars, so merging them into one is justified.
And since there is no “wooden” variant of either one *yet*, I don't think it is justified at the moment to make them seperate again.

**Comment by Generalcamo** [comment]
This is more of a long-term thing, an eventual thing. Definitely not now, it isn't justified yet.

**Comment by Gymnasiast** [comment]
The current situation is that the six-person Intamin bobsleigh car, which was mislabelled as "Flying Turns" in RCT2, has now been renamed to simply "six-person bob" and grouped together with the Mack bobsleigh train. That addresses one of the issues.

Introducing proper wooden flying turns would mean adding a whole new roller coaster type, complete with all the necessary sprites. That is a wholly different issue, I'd say. For that reason, I'll close this issue. Feel free to open a new one for adding a proper wooden flying turns.

**Comment by X123M3-256** [comment]
@Gymnasiast That's great, it always bothered me that it was called flying turns while not being wooden and listed as a separate ride while the Giovanola hyper gets grouped with the B&M. Does this mean that if we did add an actual wooden flying turns, it could be called "Flying Turns"?

**Comment by Gymnasiast** [comment]
@X123M3-256 Yes, either that or perhaps "Wooden Bobsleigh".
