### ISSUE TITLE
Sorting rides by track type: Misleading research messages

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#4054]
**OS:** GNU/Linux (Parabola)
**Version:** 0.0.5-develop
**Commit/Build:** cc2d91a
- Reproducible in RCT2 (vanilla)? No.
- Multiplayer? N/A

The setting “Sort rides by track types” has usability problems and may make things actually even more confusing to the average non-developer player.

Problem: Misleading notification messages

**Steps to reproduce:**
1. Activate setting “sort rides by track type”
2. Research something which is lumped together
3. Read the notification message carefully

Example: If you research Spinning Wild Mouse, you won't find it in the attraction list (but as “Wild Mouse”). So the notification message just screwed you. ;-)
The example in general: Rides X and Y are merged and displayed as “X” in the build list. Player has ride X researched. Then researches compatible ride Y. Gets message that ride Y has been researched. Looks into build window but does not find Y, only X. Player may not now that Y is actually X since the names of X and Y are different.

The problem: The notification message might be technically correct, but the point of the setting is to pretend that two rides with different cars are really just the same ride and therefore only get 1 entry in the build ride list. The message suggests the player could find a new ride in a build list but this is not true. What the player actually has to do is to look in the car tab of existing rides.

Here is proof that this is a real usability problem, not just something I just imagine:
https://github.com/OpenRCT2/OpenRCT2/issues/3975

Long example:
Given that Wild Mouse and Spinning Wild Mouse are both considered the same ride (as “Wild Mouse”) when using this setting:
Assume you already have researched the “normal” Wild Mouse.
If you research “Spinning Wild Mouse”, you get the message that the spinning wild mouse has been researched but because of the setting, there never appears a ride of this name in the list. Instead, the old “Wild Mouse” is still there.

What actually happened? Well, technically, you have researched the spinning wild mouse, but from an user perspective things things are a bit different. Since the point of this setting is to pretend that the spinning wild mouse is actually the wild mouse with a different cart, the notification message seems to fail to “follow the spirit”.

What I suggest to fix this:
The notification message should be written in a way that (indirectly) points the user to the correct window using the correct (user-visible) names (not the real names).

In the original RCT it was possible to research explicitly for new track tiles and cars. In OpenRCT2 a similar message could be used in such a case.
In my spinning wild mouse / wild mouse example, the message could be along the lines of “New car for Wild Mouse available: Spinning Wild Mouse”. This message is better because it tells the player exactly where to look, namely, in the car options of existing (pseudo-)wild mouse rides, whereas the original message suggests to look in the attractions which is of course misleading.

The final question which remains is which message to display when a completely new ride/track (not just a “car” variant) has been researched. For example, if you have (internally) neither researched wild mouse and rotating wild mouse, then research either of them, the research message should claim you have researched wild mouse. Generally, the research message should show always pretend you researched the ride which will be displayed in the build window. So if you research rotating wild mouse, it should still say you researched wild mouse because it will be displayed as “wild mouse” in the build menu, not as “rotating wild mouse”.

**Comment by jensj12** [comment]
It aren't the notifications that are misleading, it's the build new ride window that's confusing. Perhaps show a list of all researched vehicle types when hovering over a ride?

**Comment by Wuzzy2** [comment]
Yes, the RCT2 build window is a serious downgrade to RCT because it has been dumbed down and conveys WAY less information. RCT had much more information, including the list of available vehicles. But this is a different topic IMO.
But even if the build window is changed, that doesn't make the current notification texts always true (think of my wild mouse example).

**Comment by Patrik356b** [comment]
@Wuzzy2 Go find a "rotating wild mouse" :+1:

**Comment by Wuzzy2** [comment]
Oh, sorry. It is actually called “Spinning Wild Mouse”. “Rotating Wild Mouse” was a bad translation by me.

**Comment by Gymnasiast** [comment]
Solved by 96a7a8ab508f09e3d0220ca6b363fa8ee8874201.
