### ISSUE TITLE
Sort rides by track type: Sorting rule is not really clear (inconsistent?)

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#4055]
**OS:** GNU/Linux (Parabola)
**Version:** 0.0.5-develop
**Commit/Build:** cc2d91a
- Reproducible in RCT2 (vanilla)? No.
- Multiplayer? N/A

I don't understand the logic under which some rides under the “Sort rides by track type” setting have been lumped together.

If I understand the _idea_ of the setting, then all rides with the _exact_ same track tiles (not more, not less) which _only_ differ by their car are allowed to be merged. Maybe there are some other criteria (I don't know). And rides with a different set of track tiles are supposed to be kept seperate. Is this correct so far?

If this is the idea of the setting, then there is at least one merged set of rides which violates it:
- Car ride (RCT cars) (no special tiles)
- Oldie cars (no special tiles)
- As far I know, other Time Twister and Wacky World variants of the classic car ride (none have special tiles)
- Monster Trucks (+steep hill, +logs)
- Chesire Cats (+tunnel)

All of these will be merged in OpenRCT2.
IMO this needs to be changed. IMO Monster Trucks and Chesire Cats need to be kept seperate from the rest and each other because they allow different tiles to be used. Especially monster trucks because this one really stands out for its steep hills.
This causes other problems than “just” weird usability. For example, it becomes possible to build a track with incompatible tiles under RCT2 rules (e.g. logs AND rotating tunnel) or use cars on incompatible tracks (like cats on steep hills, problematic because there are no proper images for that).

All other car rides can be merged since I haven't seen any special tiles.
So at the end, we would have 3 sets of car rides:
- Monster Trucks (own ride)
- Chesire Cats (own ride)
- Car ride, oldie cars, TT-style car rides, WW-style car rides

This was just _one_ example. There may be other rides which have been merged but shouldn't, but I don't know. If you are aware of any examples, please post here.

**Comment by jensj12** [comment]
The ride merging is based on the internal game structure.

I prefer the RCT1 method for this: if the track contains a piece the current vehicle can't use, don't allow testing/opening the ride and open the construction window with the first conflicting piece selected if the player tries to test/open it.
If no available vehicle can use a piece, don't show this piece at all in the construction window and hide ride designs that need this piece. It just needs an extra warning in the construction window to prevent logs+tunnels being used on the same ride.

**Comment by IntelOrca** [comment]
If you always enable all track pieces because some car type allows it, the player ends up building an entire track using e.g. steep slopes only to find out that they can't use them unless they select monster trucks.

I suggested one idea to @Gymnasiast which was to allow the player to select the car type between selecting the ride type and building the track.

**Comment by Gymnasiast** [comment]
I'm working on a system which should address these issues. It will separate Monster Trucks and other Car Ride vehicles again.

**Comment by Generalcamo** [comment]
> If you always enable all track pieces because some car type allows it, the player ends up building an entire track using e.g. steep slopes only to find out that they can't use them unless they select monster trucks.

I don't see how this is an issue? The Hypercoaster and Hyper-Twister coaster in RCT1 and OpenRCT2 (RCT1-Mode) doesn't allow for inversions, and doesn't really mention that either.

**Comment by Gymnasiast** [comment]
It is still irritating to find that out after you have built the track. Also, the Hyper-Twister cars at least contain code to block it from opening when you use inversions whereas (for example) a Cheshire Cats will happily open, only to glitch on the steep slopes (log bumps work fine but look a bit silly with Cheshire Cats ;) ).

**Comment by Patrik356b** [comment]
Though spinning tunnel isn't a problem for any other vehicle, except maybe the monster trucks.
