### ISSUE TITLE
Allowing more than 128 rides in scenarios

### ISSUE THREAD

**Issue by birthdaybrian** [OpenRCT2/OpenRCT2#4056]
Hey. I host my server everyday and sometimes people requests me to add more rides to my park, my park's rides list is full and I would like to add more rides to my park without removing unused ones. Can developers increase the maximum to like 200?

**Comment by Gymnasiast** [comment]
*Sigh*
https://github.com/OpenRCT2/OpenRCT2/wiki/Increasing-of-game-limits
