### ISSUE TITLE
Game Crash while Building Premade Roller Coaster

### ISSUE THREAD

**Issue by UnsaltedCashews** [OpenRCT2/OpenRCT2#4058]
OS:  Windows 10
Version: 0.0.5
Commit/Build: 21e5093

I was building a premade Floorless Roller Coaster, and while I was moving the ghost of the track to place it, the game froze and crashed. One thing I noticed is that the crash only occurred with premade roller coasters with lots of scenery included and only if I was rapidly moving the ghost through parts of the map with lots of trees, it didn't happen over areas which didn't have lots of trees. I'm not sure if this crash can be done if you move the ghost slowly.

- [ ] Reproducible in RCT2 (vanilla)? No
- [ ] Multiplayer? Not sure, haven't tried.

**Steps to reproduce:**
1. Take a premade roller coaster with lots of footpaths or scenery included, preferably a larger roller coaster.
2. Rapidly move it over any area with lots of trees. [Not sure if it works with different scenery]

[Dump.zip](https://github.com/OpenRCT2/OpenRCT2/files/358100/Dump.zip)

**Comment by Patrik356b** [comment]
Does it happen more or less on Crazy Castle? because i have a similar issue, but only on that. ( #3953 )

**Comment by UnsaltedCashews** [comment]
I managed to crash the game on Six Flags Great Adventure and on Fungus Woods so I don't think it has something to do with the map

**Comment by janisozaur** [comment]
It would be nice if someone could verify this with minidump, but I managed to reproduce a crash on https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/world/map.c#L410

**Comment by IntelOrca** [comment]
Null map element maybe? Location out of range?

**Comment by janisozaur** [comment]
Yeah, it was null, probably due to moving the ghost outside park boundaries. I haven't investigated, but there already is a check in line 399.

**Comment by IntelOrca** [comment]
It can always be null, like if there is no surface element... Although that seems unlikely for a vanilla map.

**Comment by duncanspumpkin** [comment]
Retest after the latest commit. I think this is probably due to the map insert element corruption.

**Comment by UnsaltedCashews** [comment]
I can't reproduce this bug anymore, so I think that commit fixed it, could someone else see if its fixed for them?

**Comment by mrtnptrs** [comment]
Yes, this was fixed.

**Comment by UnsaltedCashews** [comment]
Ah awesome thanks
