### ISSUE TITLE
Wrong error message when opening all rides with unfinished ride

### ISSUE THREAD

**Issue by YJSoft** [OpenRCT2/OpenRCT2#4061]
**OS:** OS X
**Version:** 0.0.5
**Commit/Build:** 6c702fb

"Can't rename park" error is raised opening all rides with unfinished ride.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**

Method 1
1. Open scenario `Europe - Renovation`(Wacky worlds)
2. Try to open all rides
3. Mini rollercoaster will highlighted, error message `Can't rename park` shows.

Method 2
1. Open any scenario
2. Build ride
3. Make sure ride is not openable.(missing enterance, unfinished track...)
4. Try to open all rides
5. Wrong error message like `Can't construct this here...' shows

**Screenshots / Video:**
<img width="531" alt="2016-07-12 2 19 41" src="https://cloud.githubusercontent.com/assets/5893514/16755863/bc696acc-483b-11e6-9090-3f0938d747e6.png">
<img width="977" alt="2016-07-12 2 19 25" src="https://cloud.githubusercontent.com/assets/5893514/16755862/bc666ffc-483b-11e6-8642-579f9a06b108.png">

**Comment by Nubbie** [comment]
To be fair.. You can't rename the park, nor construct anything in the coaster list :smile:

**Comment by SijmenSchoon** [comment]
Is this problem also present in #3977?
