### ISSUE TITLE
Update to newer version (a4223d9) breaks everything; reverting to previous build does not work

### ISSUE THREAD

**Issue by ebm9000** [OpenRCT2/OpenRCT2#4065]
OS: Windows 10 builds 10240 (1 PC) & 10586 (2 PCs)
Versions: 0.0.5 builds...
af2746e
a4223d9
6c702fb
9efc0ca
(probably others)

Hello. I updated my game to build a4223d9 today, and all of a sudden I can't join any game. When I first launch the game, I get this error in the command prompt window:
![rct2_1](https://cloud.githubusercontent.com/assets/20425429/16778538/7052bc46-483c-11e6-8171-968c6ad7fe09.PNG)

*sometimes, the Path conflicts don't show up

When I join a game, it throws two c++ errors like these:
![rct2_2](https://cloud.githubusercontent.com/assets/20425429/16778587/a787613a-483c-11e6-9cd0-e6b800f134aa.PNG)

*sometimes, it lists line 51 instead of line 38

Pressing ignore either crashes it, throws me back into the main menu with a "Disconnect message", or lets me in with a Connected Closed message (I am able to see what others were doing right as i tried to join). And now, even when removing every trace of the game, including the installer files themselves, no build will work, not even the one I was on before I updated (same errors)

![rct2_3](https://cloud.githubusercontent.com/assets/20425429/16778681/166cc0ea-483d-11e6-9d71-46c8c126e686.png)
Here, it complains of an ASJET file. I assume this is ASJET.dat? 

*NOTE: af2746e came out as I was troubleshooting the issue, and I tried that but to no avail (same errors)

I have:
1. Completely removed the game and all traces of such
2. Tried two different computers with the same 4 builds listed above
3. Tried it on Wine for Linux (not relevant to the issue)
4.Manually finding the files in question from older builds and replacing them in the corrupted build

What can be the problem here? Thank you.

**Comment by Gymnasiast** [comment]
Probably introduce by https://github.com/OpenRCT2/OpenRCT2/commit/dca816cfd394f7fff85f380370e18fce9435979a , which was a big refactor of the object list.

**Comment by janisozaur** [comment]
@ebm9000 can you upload your `ASJET.DAT`?

**Comment by IntelOrca** [comment]
@janisozaur they probably don't have it as it was unable to export it.

**Comment by mrtnptrs** [comment]
@ebm9000 Could you please upload your 'ASJET.DAT' as @janisozaur asked you a week ago. We also did some fixes for crashes recently, can you try to reproduce this problem using the latest OpenRCT2 version?

**Comment by ebm9000** [comment]
My apologies, as I responded directly to the email to reply but it never got here. This issue was solved a while ago, and me and janisozar talked on discord. Sorry for seeming ... Oh I don't know... Lazy.

**Comment by ebm9000** [comment]
Found out how to close this. :???
