### ISSUE TITLE
Assertion when trying to apply no-money cheat: save file corrupted?

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#4069]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 961f0f9

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Load one of the save files below (the one with "open" in the name was opened and saved by OpenRCT2)
2. Open the cheats screen.
3. Open Park parameters.
4. Check the no money checkbox.
5. Assertion error: 
![assertion](https://cloud.githubusercontent.com/assets/4948213/16812575/fdb9a332-492d-11e6-9202-4f644fa034be.png)

This problem did not occur with a few other saves I had lying around. But as the older ("non-open") saves are also having this assertion error when doing the steps above, the assertion error isn't caused by a saving game issue by OpenRCT2 in the past. Is there a real bug here or is the save file corrupted maybe?

**Save games:**
[Saved Games.zip](https://github.com/OpenRCT2/OpenRCT2/files/362042/Saved.Games.zip)
(For the Dutch fellows here: ignore the silly ride names and yes.... I hate my sister :P Who doesn't? ;))

**Comment by Gymnasiast** [comment]
This assertion should be removed. Many games imported from RCT2 call the 'spend money' routines in no_money mode, triggering this assertion.

**Comment by mrtnptrs** [comment]
@Gymnasiast So, there is no bug, but the assertion got triggerd by the wrong reason and failed?

**Comment by mrtnptrs** [comment]
Nicely and quickly fixed guys! :)
