### ISSUE TITLE
Pay to enter park / pay per ride suggestion and bug

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#4071]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 961f0f9

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Load a save game.
2. Make the entrance cost something.
3. Open the cheats screen.
4. Open Park parameters.
5. Change the way the park charges money to free park engry/pay per ride.
6. You see that the guests still have to pay the entry money you set at step 2, but that you can't change the amount anymore. As you choose to have free entrance I think it should reset the park entry to zero before freezing the amount. 

Same for rides when you set it to pay to enter park / free rides: You can now change the park entry price, but the ride costs are "frozen" and the guests are still charged for the rides. (this sounds to me like a bug, caused by being not able to change this for a save game in RCT2 vanilla and so not correctly implemented in OpenRCT2. Or was this intentional) 

These saves with entry and payed rides work correctly in RCT2 vanilla. So, this partially causes the "hybrid" parks from RCT1 to make a comeback into (Open)RCT2. Would it be possible for you to "fix" the above bug and implement a proper pay to enter park / pay per ride option from RCT1? Then all problems are solved and everyone can be happy again ;)

**Comment by IntelOrca** [comment]
Guests do not pay for the park entrance when money is disabled.

**Comment by mrtnptrs** [comment]
@IntelOrca Read good, they do when you set park entry before you switch to free entry. Try it yourself.

**Comment by IntelOrca** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/peep/peep.c#L7056

**Comment by mrtnptrs** [comment]
@IntelOrca What do you mean exactly? :)

**Comment by mrtnptrs** [comment]
You can re-open this issue @IntelOrca You now fixed the issue with the entry price, but not the one with the ride price. Because guests still pay when you set the park parameter to Free park entry / Pay per ride. You see the ride entry money "greyed" out at the money-tab of a ride.

Also, what do you think about the idea to bring back the pay to enter park / Pay per ride option back from RCT1 to OpenRCT2? @IntelOrca @duncanspumpkin @Gymnasiast

**Comment by Nubbie** [comment]
@mrtnptrs Do you mean the cheat 'Unlock all prices'?

**Comment by mrtnptrs** [comment]
@Nubbie Thanks, didn't see it, sorry. But the bug with the free, but not free rides still exist.

**Comment by IntelOrca** [comment]
Open a separate issue.

**Comment by mrtnptrs** [comment]
@IntelOrca Uhm... ok, but aren't these two bugs closely related to each other?: when you set one of them to free, you still have to pay the amount of money you charged before you made it free. Just want to be sure.
