### ISSUE TITLE
Add a '?' to the most common windows (UX, explain FAQ)

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#4074]
Adding a small square '?' with a set of strings inside it, either opening a window / being a tooltip for how you do the FAQ.
My suggestion to make the game more fool-proof would be 

-First time 'tutorial' for commonly used functions
-Tool tips that explain how you do difference things
-The question mark where it explains in strings how to do X & Y
-**Add** a question mark box which links to the **GitHub Wiki**

![hfgd](https://cloud.githubusercontent.com/assets/17282384/16819892/cb910f78-494e-11e6-8085-e0ac24c2bea3.png)

For example: As 'How do I start a server' is one really requested feature, why not link them to the wiki/make a window explaining it

**Comment by IntelOrca** [comment]
This is usually another button next to the X (close button).

**Comment by marijnvdwerf** [comment]
@IntelOrca Differs per platform. Also, if i remember correctly, the titlebarbutton on Windows triggers a question mark cursor, so that's something different.

![image](https://cloud.githubusercontent.com/assets/737603/16822347/0ea81f4c-495c-11e6-8599-f78d3312e491.png)

Also, I think it would be a better idea to make the interface itself more clear than to write documentation.

**Comment by IntelOrca** [comment]
What the question mark does depends on the program.

**Comment by Nubbie** [comment]
There are some ways this could be tackled tho, it's mostly as a helping hand to users
Depends on how viable it should be

**Comment by Nubbie** [comment]
My thought now would be a question mark for windows that prompts up a window saying 'This will take you to the OpenRCT2 wiki page for this window, Are you sure? [YES/CANCEL]

**Comment by AaronVanGeffen** [comment]
> Also, I think it would be a better idea to make the interface itself more clear than to write documentation.

:+1:

**Comment by marijnvdwerf** [comment]
@Nubbie The problem with the 'open documentation in browser' approach is that the documentation is _very_ likely to not get updated as much as the UI itself.

**Comment by Patrik356b** [comment]
Not to mention some might find it annoying (especially on slow machines, think EEE PC or anything with a very slow cpu)
