### ISSUE TITLE
Ride list doesn't update when a ride gets deleted when game is open

### ISSUE THREAD

**Issue by RealRexen** [OpenRCT2/OpenRCT2#4080]
Os: Windows 10
Version: 0.0.5
Build:fb456a8
If you delete a track design while in game. The list doesn't get update and shows just a blank ride. Not sure if causes a crash if chosen.

![2016-07-14 2](https://cloud.githubusercontent.com/assets/18408903/16843770/a8bb0fb4-49b0-11e6-8cf3-bfc7ce0abaf3.png)

**Comment by mrtnptrs** [comment]
@RealRexen Could you test for me if choosing the deleted ride will cause a crash? As the track files get analyzed during the startup of OpenRCT2, it's logical that it can't know it isn't on your PC anymore. Maybe it just gives you an error message box when you try to build it? Testing it now myself too! :)

**Comment by Nubbie** [comment]
I should act that way as the list gets refreshed once when you open it, if it cause a crash, then it's a problem that should be fixed (broken/missing tracks)

**Comment by RealRexen** [comment]
It doesn't cause a crash, click on it does nothing.

**Comment by mrtnptrs** [comment]
Then this issue can be closed I suppose? :)

**Comment by marijnvdwerf** [comment]
Or monitor the filesystem for changes and update accordingly.

**Comment by Nubbie** [comment]
Is it really that necessary as you dont often remove rides while In-game, it could be useful for 'clean ups' if you have 100 rides tho :p

**Comment by mrtnptrs** [comment]
@marijnvdwerf the more advanced way, but maybe not really neccesary as.... who deletes track-files while in-game? :)

**Comment by Patrik356b** [comment]
@Nubbie considering that the original already has a lot of tracks...

@marijnvdwerf there should just be a simple error message telling the file couldn't be found.

**Comment by Nubbie** [comment]
A message when about the ride not existing would be enough

**Comment by IntelOrca** [comment]
It will re-scan the tracks when you open the track list... but deleting a track when the window is already open will cause this - you can fix it just by re-opening the window.

I think this is very rare use case to warrant a file watcher.
