### ISSUE TITLE
Scrolling over non-scrollable areas causes other areas to scroll

### ISSUE THREAD

**Issue by marijnvdwerf** [OpenRCT2/OpenRCT2#4081]
**OS:** OS X El Capitan
**Version:** 0.0.5-develop
**Commit/Build:** 5204fb0

When scrolling while hovering over a non-scrollable window, the topmost scrollable window scrolls instead.

- [ ] Reproducible in RCT2 (vanilla)?

**Screenshots / Video:**
![image](https://cloud.githubusercontent.com/assets/737603/16848480/41fc36fe-49f6-11e6-8c76-8e0ee966129a.png)

![image](https://cloud.githubusercontent.com/assets/737603/16848484/4948d2be-49f6-11e6-9ea6-623720d3667c.png)
**Actual behavior:** Scrolling the orange area causes the ride window to scroll, green area the guest list and blue area zooms the viewport

![image](https://cloud.githubusercontent.com/assets/737603/16848487/4c473208-49f6-11e6-910e-001dbdb630c7.png)
**Expected behavior:** Only while hovering over scrollable content, should scrolling have effect.

**Comment by mrtnptrs** [comment]
Also reproducable on Windows here of course :)
