### ISSUE TITLE
Month names in graphs are written out in full and overlap

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#4087]
**OS:** GNU/Linux (Parabola)
**Version:** 0.0.5-develop
**Commit/Build:** 5204fb0

In the park and finance windows, whereever you see a graph (money graph, guest graph, park rating graph), the month names are currently overlapping (see screenshot). Maybe it's because the full month names are used instead of their 3-letter abreviations.

- Reproducible in RCT2 (vanilla)? Probably not.
- Multiplayer? N/A

Screenshot: https://i.imgur.com/ezQSBFA.png

**Comment by Wirlie** [comment]
@marijnvdwerf are you still working on this?
