### ISSUE TITLE
Graphical glitch with placing attraction entrance inside land

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#4088]
**OS:** GNU/Linux (Parabola)
**Version:** 0.0.5-develop
**Commit/Build:** 097c5b1

If an entrance is inside land, it may be almost entirely visible at the land edges if the the land is low.
- Reproducible in RCT2 (vanilla)? **Yes!**
- Multiplayer? N/A

**Steps to reproduce**
1. Build an attraction (you only need the platform)
2. Place an entrance in such a way that it is completely submerged into land. The land must be 4 units higher than the platform
3. Remove land around the entrance so the edges become visible
4. View the entrance from all directions

Expected: It does not look strange to look at the land where the entrance is placed. I shall only see the “front” and “back” parts of the entrance.
Result: I see almost the entire entrance through the edges of the land, which looks odd.

**Screenshots / Video**
![Screenshots showing entrances submerged into land](https://i.imgur.com/KCeVkFT.png)

Left screenshot: Land is 4 units higher than the twister.
Right screenshot: Land is 5 units higher.

**Notes**
Note 1: With the land being 5 units higher, or even more, the entrance may or may not disappear behind the land edge. Sometimes it starts to “blink” which looks very weird.
Note 2: The bug seems to manifest only when looking from a certain direction 
Note 3: This is an old bug I know (and hate) in RCT and RCT2.

**Comment by rik-smeets** [comment]
This issue has been resolved by #18266.
