### ISSUE TITLE
Possible to trick scenario height limit by lowering land below attraction

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#4089]
**OS:** GNU/Linux (Parabola)
**Version:** 0.0.5-develop
**Commit/Build:** 097c5b1

It's possible to defeat the height limit (not higher than tree height, seen in Rainbow Summit from RCT2) simply by lowering the land below an attraction.

- Reproducible in RCT2 (vanilla)? **Yes!**
- Multiplayer? N/A

**Steps to reproduce**
 1. Play a scenario where you are forbidden to build above tree height (e.g. Rainbow Summit from RCT2)
 2. Build some roller coaster which can be built high (e.g. wooden roller coaster) if you don't already have one
 3. Try to lower the land below any tile of the roller coaster as low as you can

Expected: Local authority prevents you from lowering the land at some point as this would make the roller coaster above tree height
Actual result: Local authority turns out to be no authority at all and lets you do it. ;-)

After doing this, you can check that the roller coaster is now indeed above tree height by removing the offending tile and trying to build it again. Now building it should be prevented again.

With this trick, you could build an entire roller coaster above tree height if you have enough money and patience, thus defeating the height limit.

**Comment by SijmenSchoon** [comment]
Could reproduce in vanilla RCT2

![scr1](https://cloud.githubusercontent.com/assets/345785/16867726/a93d0be0-4a73-11e6-8cc3-8fde13ae5b46.png)

**Comment by Gymnasiast** [comment]
Yes, it's possible, but it costs an incredible amount of money to do it (a bit like a bribe :P).

And trying to prevent it also presents one with a hard question: how? Preventing the lowering of terrain if it makes the track exceed the height limit will not prevent people from just keeping the terrain high, and thus not be very effective.

**Comment by Patrik356b** [comment]
I'm with @Gymnasiast on this one.

**Comment by Wuzzy2** [comment]
High cost is not an argument since money can be disabled as well.

The “How?” is actually very simple to answer: When lowering land, always check if the ride would go above tree height at this particular position. If this is the case, it is forbidden.
A similar thing happens if you try to lower land lower if it would make the ride itself higher than allowed.

I think the point of the restriction is that rides may not be placed to high above land. If you just raise the land, it's fine. Maybe this was intentional.

If we don't change anything, then we have a weird inconsistency: Building normally above high land is forbidden, but first raising the land, then building, then lowering the land again is okay. Both would have the same result, so either both should be allowed or both should be forbidden.
Your argument that my proposal has a drawback is invalid. The player could raise land to build higher in either case, not matter if changed or not.

Maybe this height restriction thing was kind of a minor design flaw. I remember it first appeared in Loopy Landscapes in a scenario where you *also* could not change the land. This made sense. But Rainbow Summit seems to be the only official scenario I know where you must not build above trees but you may change the land.

**Comment by Gymnasiast** [comment]
> The “How?” is actually very simple to answer: When lowering land, always check if the ride would go above tree height at this particular position. If this is the case, it is forbidden.
Which will still allow building above tree height by raising the land.

> Your argument that my proposal has a drawback is invalid.
The user will still be allowed to build above tree height, just not lower the land afterwards. That is a drawback.

**Comment by IntelOrca** [comment]
It feels like a bug, because if you try and lower land under a ride which has a maximum support height, e.g. monorail it forbids you.

**Comment by Gymnasiast** [comment]
Yes, but that's a different cup of tea compared to the tree height, as raising the land will allow for construction above it. Preventing the lowering of terrain will still get you a construction above tree height.

**Comment by IntelOrca** [comment]
This option is usually used in conjunction with prevention of altering land and removing trees of course.

**Comment by Patrik356b** [comment]
Essentially a flaw with the scenario options then?
