### ISSUE TITLE
Open RCT2 not allowing non game shortcuts to work

### ISSUE THREAD

**Issue by RealRexen** [OpenRCT2/OpenRCT2#4090]
Os: Windows 10
Version: 0.0.5
Build:fb456a8

Not sure if its a bug or a windows 10 issue but shortcuts to open the steam overlay or the windows game record doesn't work. I try other games and they work fine for both of the things listed.

**Comment by Patrik356b** [comment]
The overlay can be quite iffy sometimes

**Comment by IntelOrca** [comment]
Are you on Hardware Display mode?

**Comment by RealRexen** [comment]
The display is set to software mode.

**Comment by janisozaur** [comment]
The overlays don't work in software mode.

**Comment by mrtnptrs** [comment]
@RealRexen If you use the Software (hardware display) drawing engine, it should just work fine when you open OpenRCT2 from Steam. Does this work for you?

**Comment by RealRexen** [comment]
changing to software (hardware display) does nothing, opengl doesn't help either.

**Comment by Patrik356b** [comment]
Does it work for you in vanilla rct2?

**Comment by RealRexen** [comment]
I can't test that since my game disc is still in storage.

**Comment by RealRexen** [comment]
Somehow changing the steam skin I was using fixed the issue or it seems that way.
