### ISSUE TITLE
Main window doesn't happen/appear/whatever

### ISSUE THREAD

**Issue by somedude16** [OpenRCT2/OpenRCT2#4092]
**OS:** Windows 7
**Version:** 0.0.5
**Commit/Build:** b668533

**Explanation of the issue...**

- [ ] Multiplayer?
- [x] OpenRCT2 exclusive?

**Steps to reproduce:**
1. Boot up the game.

**Dump file**
Nope.

**Comment by Patrik356b** [comment]
if you alt-tab or use "Window -> Bring to front" in taskmanager, do you see it?

**Comment by mrtnptrs** [comment]
I see you were using a month old build to test OpenRCT2. Could you try what @Patrik356b said but also try the newest development version you can find here?: https://openrct2.org/downloads

**Comment by somedude16** [comment]
Updated to b668533, still happens

**Comment by AaronVanGeffen** [comment]
Is this the first time you're using OpenRCT2? If not, could you try deleting the game's config file found in `Documents\OpenRCT2`?

**Comment by IntelOrca** [comment]
It will also say a message in the black console window.

**Comment by mrtnptrs** [comment]
@somedude16 Do you have any answers for us?

**Comment by Gymnasiast** [comment]
Closing this due to the OP not replying.
