### ISSUE TITLE
PALETTE_TO_G1_OFFSET_COUNT error Visual C++ Runtime Library

### ISSUE THREAD

**Issue by birthdaybrian** [OpenRCT2/OpenRCT2#4093]
**OS: Windows 7 Home Premium SP1 x64** [e.g. Windows 10]
**Version: 0.0.5-11** [e.g. 0.0.5]
**Commit/Build: 6428e3e** [e.g. 426e106]

When I was playing OpenRCT2 multiplayer, I get this message when I was moving around. I have used cheats like clearing grass, watering the plants and others that don't crash the game.
- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

[crashed.zip](https://github.com/OpenRCT2/OpenRCT2/files/365224/crashed.zip)

**Comment by Patrik356b** [comment]
I'd suggest you clean up your post by removing the placeholders like [e.g. Windows 10]

**Comment by mrtnptrs** [comment]
Can't test the save file as I get the following errors:
```
[LOTR-MMP] Object not found.
[DPETZOOA] Object not found.
[LOTR-OBS] Object not found.
[DAMCDON ] Object not found.
[HPRDBURR] Object not found.
[LOTRMTP1] Object not found.
[PAT22MKY] Object not found.
[JATLPTHT] Object not found.
[patrctfa] Object not found.
[UNTITLED] Object not found.
```
Could you open the save file yourself, enable the "export plug-in objects with saved games" option at the options menu (Miscellaneous tab), save the file again and drop it here again? (if it doesn't crash for you befor you were able to save it again)
