### ISSUE TITLE
Hyper coaster: If track is at 45°, can't go directly from horizontal to steep hill

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#4094]
**OS:** GNU/Linux (Parabola)
**Version:** 0.0.5-develop
**Commit/Build:** 097c5b1
- Reproducible in RCT2 (vanilla)? I don't know.
- Multiplayer? N/A

**Steps to reproduce**
1. Build a hyper coaster
2. Build high
3. Add a curve piece (long radius) so the track goes at 45°
4. Now click on steep slope up or steep slope down
5. Look what happens

For me, the build button becomes disabled since there is apparently no piece for going from horizontal to steep hill directly. For comparison, when going along with the grid, you _can_ go from horizontal to steep hill with one piece.

Probably the steep hill buttons should be disabled if the track is going at 45° and has no slope at the moment. Unless the missing pieces are actually available but don't work for some reason.

This bug is not serious since it does not break gameplay in any way, it is just a minor oddity in the interface.

**Comment by X123M3-256** [comment]
There has never been a large diagonal flat-to-steep piece in the game. The steep slope button is enabled on flat diagonal pieces in spite of this (this is how it was in vanilla) - but I agree that it should probably be disabled because it implies you can build this piece.

**Comment by Gymnasiast** [comment]
Could either of you provide a screenshot?

**Comment by Wuzzy2** [comment]
This is what I mean:
![Screenshot of trying to place a 45° piece from horizontal to steep hill](https://i.imgur.com/OVq48As.png)

For comparison, this is how it looks like when going from flat to steep when going along the grid:
![Screenshot of trying to place a piece from flat to steep hill](https://i.imgur.com/Zf0Sbpn.png)

The easy way would (probably) to just disable the steep hill buttons when you are building flat at 45° (see 1st screenshot).

**Comment by Patrik356b** [comment]
There is at least 3 coasters that does this:
- Hyper Coaster
- Hyper-Twister Coaster
- Stand-Up Twister Coaster

Screenshot from vanilla: http://puu.sh/q2FwJ/1f79cc91a2.png
Any other design using the same track will have this isue

**Comment by Gymnasiast** [comment]
@Patrik356b The three (or technically, two) coasters you mentioned all have the 'steep slope with long base' part. That could very well the cause of this bug.
The logic of determining whether a button should be enabled or not is insanely complicated, so it's no wonder some bug worked their way in.

**Comment by Patrik356b** [comment]
@Gymnasiast I don't know if there are more that uses the same track and thought i should mention anything relevant.

**Comment by Gymnasiast** [comment]
What you mentioned was relevant. :)

**Comment by Christipher** [comment]
yeah, this affects more coasters than mentioned, this also affects the Twister roller coaster, giga coaster, and Floorless Roller Coaster

**Comment by X123M3-256** [comment]
The pieces that show in the ride construction window depend on the current allowed track pieces, so I'm pretty sure this issue will be present on everything that supports both diagonals and a steep to flat piece (except the vertical drop coaster, since that actually has a diagonal steep to flat, though it's smaller than the normal one).

**Comment by e-foley** [comment]
@X123M3-256, I just wanted to say... I thought I knew RCT well, but I never noticed that the vertical coaster allowed a steep-to-flat transition on a diagonal like that.  Thank you for teaching me something new. :)

**Comment by Gymnasiast** [comment]
Point is the following: the construction window enables the steep slope button when TRACK_SLOPE_STEEP or TRACK_SLOPE_STEEP_LONG is enabled for the ride type. This is good for regular flat-to-steep pieces, but not for those with a long base, as they don't have diagonal equivalents. The construction window should be modified to disable the steep slope buttons when in diagonal mode. Problem here is that quantum mechanics are easy compared to the spaghetti that is the construction window.
