### ISSUE TITLE
Not all messages in the message log are shown in the current language after language switch

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#4095]
**OS:** GNU/Linux (Parabola)
**Version:** 0.0.5-develop
**Commit/Build:** 097c5b1

After you switch the language, not all messages in the message log are displayed in the correct language.

- Reproducible in RCT2 (vanilla)? I don't know.
- Multiplayer? N/A

**Steps to reproduce**
 1. Play the game for a while and let some messages appear
 2. Switch the language in-game
 3. Let more messages appear
 4. Read the message log

Expected: All messages are now displayed in the correct language
Actual result: Only the messages after the language switch are shown in the correct language, earlier messages are displayed in the old language

This can't be fixed even after you restart OpenRCT2. :-(

**Comment by Gymnasiast** [comment]
Are you talking about the recent messages? These are saved as text and not as string ids, which makes translation old messages impossible. This approach allows for custom messages.

**Comment by IntelOrca** [comment]
When we have our own format................................

We can store non-custom messages using types and parameters to resolve this issue.

**Comment by Wuzzy2** [comment]
It's a design flaw then and certainly not a “non-bug”. No reason to close it so quickly.

And as IntelOrca said, there are probably ways to resolve this, even if it takes time to do so.

Luckily, people don't change languages too often so I can understand if you maybe flag this as “low priority” but not if you deny it is even a bug.

**Comment by duncanspumpkin** [comment]
But it would break custom messages any change in this behaviour.
