### ISSUE TITLE
Game crashing with scenery placement

### ISSUE THREAD

**Issue by DejaVu2001** [OpenRCT2/OpenRCT2#4096]
**OS:** Windows 7
**Version:** 0.0.5
**Commit/Build:** 2d24678

When attempting to place scenery while clearance checks are disabled, the game crashes. Sometimes, items around where you are working will disappear, then the game freezes. Other times, the game crashes to desktop and displays an error message

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Disable clearance checks
2. Attempt to place scenery

**Screenshots / Video:**
![or2](https://cloud.githubusercontent.com/assets/20479466/16885075/7aee546e-4a92-11e6-92ec-9d6fb0a242dd.jpg)
![orct2](https://cloud.githubusercontent.com/assets/20479466/16880647/da0daa06-4a7b-11e6-89da-5f76c3a6d8ab.jpg)

**Save game:**
[Great America 2016whiz.zip](https://github.com/OpenRCT2/OpenRCT2/files/366401/Great.America.2016whiz.zip)

**Comment by duncanspumpkin** [comment]
Something is very broken with the scenery placement code. You don't need to have clearance checks on to crash it.
