### ISSUE TITLE
Rotate clockwise or counter-clockwise?

### ISSUE THREAD

**Issue by Ionaru** [OpenRCT2/OpenRCT2#4102]
**OS:** Windows 10
**Version:** 0.0.4 Stable

When clicking the 'rotate 90 degrees clockwise' button in the top menu bar or pressing 'enter', it appears as if the camera spins 90 degrees counter-clockwise (The whole park/world spins 90 degrees clockwise to give this effect).
It would make more sense in my opinion to reverse this so the camera spins clockwise instead.

- Reproducible in RCT2 (vanilla)? Yep, this has bugged me since RCT1.

**Comment by Patrik356b** [comment]
Maybe something to put in the config file, i don't see this as a problem, but you do have point

**Comment by Goddesen** [comment]
I don't agree with altering this to be different than the standard RCT2 behavior, though I'm all for the config option.

**Comment by Gymnasiast** [comment]
And I'm against a config option for something so trivial.
