### ISSUE TITLE
pay to enter park / free rides: guests still get charged for rides if they previously were charged for it

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#4110]
At the request of @IntelOrca:

OS: Windows 10
Version: 0.0.5
Commit/Build: be4668e

 Reproducible in RCT2 (vanilla)?
 Multiplayer?
Steps to reproduce:
1. Load a save game.
2. Make a ride cost something. (make sure you're able to charge for rides)
3. Open the cheats screen.
4. Open Park parameters.
5. when you set the charging options to pay to enter park / free rides: You can now change the park entry price, but the ride costs are "frozen" and the guests are still charged for the rides. 

This is the same as #4071 , but then for rides.

**Comment by duncanspumpkin** [comment]
Yes this is required if people want parks with pay for entry and rides.

**Comment by mrtnptrs** [comment]
@duncanspumpkin Please look at #4071 and you see why this needs to be re-opened! When you set the mode on free rides, why should the game still charge the guests for the rides? The same thing was happening with the entry price when setting the mode to free entry/pay for rides: the guests still got charged for entering the park (same amount of money as before you made the entry "free") and @IntelOrca fixed that.

**Comment by duncanspumpkin** [comment]
But that is the other way round this requires breaking a feature everyone uses.

**Comment by mrtnptrs** [comment]
Well @duncanspumpkin , seems like IntelOrca fixed it. Will test the fix in a few minutes.
