### ISSUE TITLE
Window limit: inaccurate and closes some windows suddently

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#4111]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** be4668e

**Steps to reproduce (for example):**
1. Set the window limit to 8.
2. You can now only open 5 windows of different types or the same.
3. When you use a higher limit (for example: 9), you can maybe open one more window, but when you lower it back again to 8, the newly added window dissapears BUT a few seconds later a second window suddently closes too sometimes!

@wolfreak99 could maybe take a look at his window limit code again or another dev?

**Comment by IntelOrca** [comment]
There are at least 3 implicit windows: the main viewport, the top toolbar and bottom toolbar.

**Comment by Wirlie** [comment]
I think that these 3 implicit windows can be ignored using their `window class`?

**Comment by mrtnptrs** [comment]
@IntelOrca Isn't it a bit strange to count them as windows too, as they don't have a top bar etc.?

**Comment by IntelOrca** [comment]
@mrtnptrs I am just saying why it is 3 off.

**Comment by mrtnptrs** [comment]
@IntelOrca I understand that :) Couldn't you then just do a thing like this in the code?:
`windowCount = windowCount - 3`

Wouldn't that be the easiest "solution" an most user-friendly?

**Comment by IntelOrca** [comment]
Yes you could, but I didn't write the window limit feature.

**Comment by mrtnptrs** [comment]
I tried to make sense of it and tried it myself to "fix" this, but the code is too complicated for me.

**Comment by IntelOrca** [comment]
@mrtnptrs

> BUT a few seconds later a second window suddently closes too sometimes!

This will probably be your error box or tooltip box opening which again counts as a window.

**Comment by Patrik356b** [comment]
@Intelorca logically speaking, you should only be able have one tooltip and one error message show at the same time at most.

They should count as exceptions like the toolbars imho

**Comment by IntelOrca** [comment]
@Patrik356b yes, I agree... but this is just how it worked in RCT2 so it requires changing or...  a new window system which we will eventually do.

**Comment by Niels-NTG** [comment]
I've also noticed that when opening non-toolbar windows (Ride, Visitor, Employee, etc.) get placed in a corner of the screen. Starting with the top left, then top right, bottom left and bottom right. Any more windows get placed right on top of the bottom right window. I would be nicer if windows stacked properly like so:

![url](https://cloud.githubusercontent.com/assets/6061595/17049223/4140e510-4fec-11e6-80b9-22380356243a.jpg)

 Or even better: properly tiled next to each other.

Regardless, this is sort of a separate issue from the one discussed here. Mainly wanted to say that we should definitely look into how the windowing system in [OpenTTD](https://www.openttd.org/en/) (in case you're not familiar: OpenTTD is a project comparable with OpenRCT2) works. I personally think they nailed it when it comes to UI while not striding too far from the look and feel of the game it's based on.

**Comment by IntelOrca** [comment]
The window system tries to find an empty cell in a 2x6 grid to place the new window. This is for some windows, other windows have a fixed position on the screen and some appear in the centre.

**Comment by Niels-NTG** [comment]
Is this logic derived from the original game? I can see how this system works just fine on the predefined set of resolutions the original game had. But since OpenRCT2 resolution is completely flexible it might be better to rethink this. Perhaps this can be solved by dynamically adapting this grid you mentioned by the currently game resolution.

**Comment by IntelOrca** [comment]
> Is this logic derived from the original game?

Yes

**Comment by Gymnasiast** [comment]
Fixed by https://github.com/OpenRCT2/OpenRCT2/pull/4144.
