### ISSUE TITLE
Free rides: Income and profit calculated using old price

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#4113]
OS: Windows 10
Version: 0.0.5
Commit/Build: be4668e

1. Load a save game.
2. Make a ride cost something. (make sure you're able to charge for rides)
3. Open the cheats screen.
4. Open Park parameters.
5. when you set the charging options to pay to enter park / free rides: Guests don't pay no more when the rides are free, the money tab also show that the total profit gets lower, but strangely the income and profit are still above zero and go up and down sometimes (seems like the game caculates the profif and income with the amount of guest and the amoun of money the guest previously were charged for a ride). 

See the image below for proof: 

**Screenshots / Video:**
![2016-07-16_18-09-36](https://cloud.githubusercontent.com/assets/4948213/16895869/43264a32-4b82-11e6-88c5-da9d7b966ee7.png)

**Save game**
[ANMAopen.zip](https://github.com/OpenRCT2/OpenRCT2/files/368001/ANMAopen.zip)

**Comment by SijmenSchoon** [comment]
This should be fixable by adding this to the beginning of `ride_calculate_income_per_hour` (in src/ride/ride.c):
```c
if (!(gParkFlags & PARK_FLAGS_PARK_FREE_ENTRY))
		return MONEY(0, 00);
```

**Comment by mrtnptrs** [comment]
@SijmenSchoon Would you like to make a pull request for this then, as I'm really not familiar with the code at the moment.

**Comment by SijmenSchoon** [comment]
`PARK_FLAGS_PARK_FREE_ENTRY` is the only park flag related to paying for parks/rides

**Comment by mrtnptrs** [comment]
The same problem also occurs when you use the "no money"-park parameter. Does #4124 fix that problem too?
