### ISSUE TITLE
Guest drowned message gets less priority over other messages (broken down rides especially)

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#4119]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 964cf66

- [ ] Reproducible in RCT2 (vanilla)? (can't test this, as the below save is from a six flags scenario and so shows no death messages. Maybe if someone could provide me a save (non-six-flags!) with many rides and guests, I could test the behavior in vanilla RCT2.)
- [ ] Multiplayer?

**Steps to reproduce:**
1. Drown a guest.
2. Keep your eyes open and look at the bottom toolbar for the message about the guest that has been drowned.

You see that this message could come in with a huge delay: the message could take up to 50 seconds to appear. The game seems to put higher priority on broken down rides then drowned guests. Keep in mind, sometimes, when you are removing paths, guests can drown by accident. Shouldn't died guests be more important then a broken ride? When a ride crashes, the messages about the crash have no delay. As I don't know what the behavior in RCT2 vanilla is and if it's different from the OpenRCT2 behavior, I think you can mark this as "discussion."

**Save game:**
Good save to test with:
[ANMAopen.zip](https://github.com/OpenRCT2/OpenRCT2/files/367834/ANMAopen.zip)

**Comment by e-foley** [comment]
I always thought the messages were part of a queue and were shown in the order the events happened.  Is there more to it?

**Comment by IntelOrca** [comment]
Messages do not have priority, they are just a queued.

**Comment by mrtnptrs** [comment]
@IntelOrca Well, it really looks like that. I will take a look if you are right.
