### ISSUE TITLE
Different water color at the main menu title sequence when the MP-game had a different color of water

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#4123]
### Operating System: 
Windows 10

### Commit/Build: 
964cf66

### Steps to reproduce:
1. Open the Multiplayer game map, called Steam Tycoon 3. Find the server or load the save file below.
2. Exit to the main menu.

### Explanation of the issue:
All water at the main menu is purple now. It should of course be just blue. So, the water color should be reset after quitting a game. But when you load a save or start a new game from the main menu with the puple water. the water has it's original color back in the new game.

### Screenshots / Video:
![2016-07-17_18-25-09](https://cloud.githubusercontent.com/assets/4948213/16901728/d9cca200-4c4b-11e6-8cb6-adaad43c0359.png)

### Save game:
[steamtycoon3.zip](https://github.com/OpenRCT2/OpenRCT2/files/367981/steamtycoon3.zip)

**Comment by Nubbie** [comment]
Indeed as the last map changes the waters color and the title sequences maps are loaded maps

**Comment by mrtnptrs** [comment]
@Nubbie But shouldn't the water color get reset by every map it loads, so it gets the water color the map actually has?

**Comment by Nubbie** [comment]
Yeah presume its a bug then :S
