### ISSUE TITLE
Crash while placing a saved track

### ISSUE THREAD

**Issue by Harbinger619** [OpenRCT2/OpenRCT2#4125]
**OS:** Windows 10 64-bit
**Version:** 0.0.5
**Commit/Build:** 964cf66

Explanation of the issue:
I was trying to determine the best place for a previously-saved ride (go-karts in this case), and zoomed out for a better view of the area. The game crashed just after the view updated.

I managed to reproduce this twice, but only got one dump file out of it. The second time, the game just hung with the 'zzzz' cursor.

- [no] Reproducible in RCT2 (vanilla)?
- [n/a] Multiplayer?

**Steps to reproduce:**
1. Load a previously saved track design, but don't place it yet
2. zoom in or out with the camera via the scroll wheel, and move the ghost track around
3. repeat step two if needed

**Dump file**
[OpenRCT2_crashdump.zip](https://github.com/OpenRCT2/OpenRCT2/files/368005/OpenRCT2_crashdump.zip)

**Save game:**
Should be included in the zip file.

**Comment by mrtnptrs** [comment]
@Harbinger619 Can you reproduce this using a brand new game/scenario? So, can you reproduce it every time with different saves/games using the steps above? When I open the save, the game immediatly crashes for me.

**Comment by mrtnptrs** [comment]
I'm not sure the following is related to this issue, but using my own save I can confirm that when you zoom out 1 time and move around the map with the "ghost" of a pre-build ride to place it, the game crashes and the following error gets generated at the commandprompt: ERROR[src\world\map.c:190 (map_get_first_element_at)]: Trying to access element outside of range

Can you reproduce this too @Harbinger619 ? If not, I will make a new issue report myself.

The save and dump (4db876c):
[OpenRCT2.zip](https://github.com/OpenRCT2/OpenRCT2/files/368032/OpenRCT2.zip)

**Comment by Harbinger619** [comment]
@mrtnptrs Yes, I can reproduce the issue with a fresh park, by selecting a track and zooming in and out while moving the ghost ride. I used the 'Build your own Six Flags Park' and the same ride I was trying to build before. It's not always immediate like it was the first time, and it seems to hard lock the game rather than crash and create a dump.

Here's a fresh copy of the save game that actually loads, recovered from a backup. I also included the ride I was trying to build, in case that helps.
[Issue_4125_files.zip](https://github.com/OpenRCT2/OpenRCT2/files/368048/Issue_4125_files.zip)

**Comment by mrtnptrs** [comment]
@Harbinger619 Then we are indeed talking about the same issue.

**Comment by mrtnptrs** [comment]
And when zoomed in I get an even stranger issue: the game doesn't crash, but seems to be in an endless loop and producing tons of 'ERROR[src\ride\track.c:1265 (track_remove)]: Track map element part not found!' continiously at the commandprompt. But only got this once. Will try to reproduce it.

**Comment by Harbinger619** [comment]
@mrtnptrs Updated. Thanks for the feedback and the help reproducing this.

**Comment by mrtnptrs** [comment]
@IntelOrca this should be considered as a major bug as it can happen to EVERY user who tries to place a pre-build track. @Nubbie could you maybe read the last dump I provided here? Thanks is advance! @Harbinger619 thank you for reporting it to me. When I need more info, I will ask you again :)

**Comment by IntelOrca** [comment]
I can't reproduce this.

**Comment by mrtnptrs** [comment]
@IntelOrca try rides with tracks and different saves and move around much

**Comment by Patrik356b** [comment]
I think i have been having trouble with the same thing, but it only occurred on crazy castle #3953

**Comment by janisozaur** [comment]
There's something wrong with the included save file, I usually hit this: https://github.com/OpenRCT2/OpenRCT2/blob/4db876c184786b684d20eefa81feeb780d1ac937/src/peep/peep.c#L10686 other times the game spins infinitely in `game_fix_save_vars`, other times it segfaults somewhere…

**Comment by mrtnptrs** [comment]
@janisozaur This could be caused by the saves being from right when the crash occured, so, it's logical that you will get a crash. See attached save for a reliable save file to reproduce this: 
[ANMAopen.zip](https://github.com/OpenRCT2/OpenRCT2/files/368104/ANMAopen.zip)

**Comment by duncanspumpkin** [comment]
Retest after the latest commit. I think this is probably due to the map insert element corruption.

**Comment by mrtnptrs** [comment]
@duncanspumpkin Testing it now.
