### ISSUE TITLE
Refusing to use rct1 theme when setting is applied in launcher

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#4126]
I'm not sure what happened, but I can not get the "rct1 interface" setting applied to openrct via the launcher after some recent update.

**OS:** Win 8.1x64
**Commit/Build:** 4db876c

Solved after setting this in the game but strange occurrence.

**Comment by mrtnptrs** [comment]
@Patrik356b Are you using the launcher you can get from here?: https://github.com/LRFLEW/OpenRCT2Launcher/releases/tag/v0.0.5 

When the answer on the above question is a "yes": Also, @LRFLEW made the new launcher, so, it would be better to report it here: https://github.com/LRFLEW/OpenRCT2Launcher/issues and continue the discussion about this issue there, as it is really a launcher issue.

We had an old launcher, but it got retired and should not be used anymore, I don't even know if it still works.

**Comment by Patrik356b** [comment]
Your probably right, can't remember.
Looking at that repo and the folder contents i find Qt dlls which should prove your point.

Moving issue to that repo now
