### ISSUE TITLE
Rare bug: hyperspeed option dissapears

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#4130]
- Operating System: Windows 10

- Commit/Build: dd25cdc
[For example: 7b421c8. It can be found at the left bottom corner of the main menu or at the commandprompt window in case of a crash.]

- Reproducible in the original RCT2? (yes or no?): no
- Multiplayer affected? (yes or no?): no

This is a very very rare bug I encounter 5 or 6 times since I know OpenRCT2: I can use every speed option, except the hyper speed option as it is no in the dropdown (and if I remember correctly also no accessible by pressing the speed button.) I had this problem again a few days ago, but it dissapeard again suddently.

Did any of you have this problem too?

**Comment by IntelOrca** [comment]
Only available if you enable debug tools.

**Comment by mrtnptrs** [comment]
@IntelOrca That explains it, sorry :) I just always have the debug tools enabled, so, I only sometimes noticed the difference.
