### ISSUE TITLE
Guests getting stuck in OpenRCT2 but not in Vanilla

### ISSUE THREAD

**Issue by player49256** [OpenRCT2/OpenRCT2#4131]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** Around 3 days old build - July 15th

I know this has been reported before, but wanted to report with what i've tried and found so far, hopefully it can be to some help.

Guests seem to get stuck alot and seems to leave park at a fast rate
More details around all this and download to save file is here:
https://openrct2.org/forums/topic/1462-guest-count-plumit-whenever-i-open-my-park-in-openrct2/

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Visit link above and look at screenshots
2. Download save file in zippyshare link
3. Open savefile in both OpenRCT2 and Vanilla RCT2
4. Watch the diffrence in guest count, and how guests seem to get stuck in OpenRCT2

**Dump file**
No dump file

**Screenshots / Video:**
Alot of Screenshot links in forum topic
https://openrct2.org/forums/topic/1462-guest-count-plumit-whenever-i-open-my-park-in-openrct2/

**Save game:**
http://www70.zippyshare.com/v/g7rbgSWY/file.html

Sorry if i cannot provide exact build at the moment, will do as soon as i can.

**Comment by janisozaur** [comment]
> Commit/Build: Around 3 days old build - July 15th

This is not adequate. Please provide exact version.

**Comment by player49256** [comment]
> This is not adequate. Please provide exact version.
Sorry if i cannot provide exact build at the moment, will do as soon as i can.

**Comment by duncanspumpkin** [comment]
Put findings in the existing open issues

**Comment by player49256** [comment]
Posting this in https://github.com/OpenRCT2/OpenRCT2/issues/2499 , as this report is closed.

Thanks for the reply, and sorry for posting as new issue.
