### ISSUE TITLE
T-Shirt stalls charge for doughnuts

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#4132]
**OS:** Linux
**Commit/Build:** f6c8993

![zaznaczenie_132](https://cloud.githubusercontent.com/assets/550290/16926296/587a3c52-4d28-11e6-82b6-3b95e653a948.png)

**Steps to reproduce:**
1. Build T-Shirt stall
2. Check icon of first tab in red window
3. Check pricing of sold items

**Comment by Patrik356b** [comment]
lol. edible clothes then?

But the icons is vanilla behavior anyway:
![rct2-icons](https://cloud.githubusercontent.com/assets/2000703/16926878/0a78af36-4d2b-11e6-82a1-dc41a83590ee.png)

**Comment by Lastorder-DC** [comment]
I think problem introduced by recent string id cleanup since "Doughnut" price of T-Shirt Stall is not based on actual doughnut price.

**Comment by marijnvdwerf** [comment]
My mistake. Will be fixed in #4097.
