### ISSUE TITLE
Enhencement: add missing tracked rides to coaster designer

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#4135]
It's odd to find just 1 "water ride" which the dinghy ride in the list and gentle rides could be useful in here too.

i.e. Log Flume ride, monster trucks, etc

**Comment by mrtnptrs** [comment]
@Patrik356b sorry, but, I can't make any sense of your message. Could you make it clear for me what you mean exactly? :) You mean that only the dinghy ride is available in the coaster the designer, but the other water rides aren't?

**Comment by Patrik356b** [comment]
Exactly

**Comment by mrtnptrs** [comment]
And do you see any errors at the commandprompt when trying to find them in the coaster designer?

**Comment by mrtnptrs** [comment]
But isn't it perfectly normal for a **Rollercoaster** designer to not show gentle rides, stalls, shops and transport rides? But it should hide those tabs instead of showing them but containing nothing.

**Comment by Patrik356b** [comment]
It's useless for non-tracked rides so my point still stands.

The only difference is that the name of this function isn't working that well when adding gentle & water rides. But it would be beneficial to have them in here too.

**Comment by mrtnptrs** [comment]
@Patrik356b Then we have two things here:
-More tracked water and gentle rides could be added to the rollercoaster editor (up for discussion, but I agree with him.)
-Only one tab should be displayed, but multiple are displayed (or at least the tabs which contain nothing should be hidden). Bug.

**Comment by RealRexen** [comment]
Maybe rename it to Track Designer and add all the rides that have a custom track design. I mean why to I get to play a real scenario that has something that has a track design I want to design for? I mean sure I can make a sandbox scenario to help with but then you're limited to the amount rides you can have. And having a track designer would make it easier to design tracks because then you won't have to worry about some of the normal game play getting in the way.

**Comment by Horsti12** [comment]
This should be closed since there is another issue which is the same but with more information.
#4824

**Comment by Patrik356b** [comment]
The opposite just happened @Horsti12

**Comment by Gymnasiast** [comment]
The plan:
- Allow any tracked ride _that can be tested without guests_ in the RC Designer.
- Rename the RC Designer to Track Designer

**Comment by Gymnasiast** [comment]
Now implemented.
