### ISSUE TITLE
Can't exit game

### ISSUE THREAD

**Issue by Keatzee** [OpenRCT2/OpenRCT2#4136]
**OS:** Ubuntu MATE 16.04
**Version:** 0.0.5
**Commit/Build:** 0c180b8

Any attempts to exit the game, either through the exit button on the main menu or the "Exit OpenRCT2" menu button while in-game, are unresponsive and throw this error message:
`WARNING[/home/travis/build/OpenRCT2/OpenRCT2/src/windows/save_prompt.c:124 (window_save_prompt_open)]: Invalid save prompt mode 3`

The only way to close the window is by killing it. I don't know what commit might have caused this, as I'm returning to the game after a month of not starting it up, and it worked fine before then.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Start the game
2. Attempt to exit

**Dump file**
N/A

**Screenshots / Video:**
N/A

**Save game:**
N/A

Edit: Could it possibly be [this](https://github.com/OpenRCT2/OpenRCT2/commit/0c180b81713028f95f90b60a09e4369e4ef17b08#diff-9902bd60a2186db99dcfa4cc10b87dfeR124)? Not too familiar with the code base

**Comment by janisozaur** [comment]
what fun
