### ISSUE TITLE
Scrolling around the map is far from fluid

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#414]
When you now try to scroll around the map, you see it's less fluid then it was in RCT2. I think you noticed it already and maybe it's WIP, but I thought it wouldn't mind to mention it here.

**Comment by IntelOrca** [comment]
With uncapped FPS, viewport movement is very smooth - even when dragging.

**Comment by mrtnptrs** [comment]
No, with a park with over 2000 guests, the scrolling still awfully stutters. Even with hardware display and uncap fps enabled.

**Comment by zsilencer** [comment]
It used to be smooth, but the fix to #1572 caused it not to be again

**Comment by IntelOrca** [comment]
If its only slow when there are many guests (things to draw) that is a limit of how fast it can draw. We can't optimise that any further until the whole game is complete - and isn't directly related to scrolling.
