### ISSUE TITLE
No commit/build number in Mac version

### ISSUE THREAD

**Issue by joshbgosh10592** [OpenRCT2/OpenRCT2#4140]
**OS:** [Mac OS X 10.11.5]
**Version:** [0.0.5]
**Commit/Build:** [389ae72] (Pulling this from the Launcher, may be incorrect. However, this has been consistent with every update.

Mac version does not show build/commit number at bottom left corner. Makes reporting bugs with correct build number much more difficult.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Launch Mac Version
2. Observe bottom left corner.

**Screenshots / Video:**
![screen shot 2016-07-19 at 5 17 48 pm](https://cloud.githubusercontent.com/assets/20283787/16967097/7ea63720-4dd5-11e6-9770-31d892132bbe.png)

**Comment by Nubbie** [comment]
Are you running stable or developer version?

**Comment by joshbgosh10592** [comment]
Dev version, at least that's what's selected using the launcher (Branch: Develop)
I just recently started using the launcher on both my Windows (Server) and Mac (client), but this particular is only existing in the Mac version.

**Comment by marijnvdwerf** [comment]
Can someone with Linux verify whether it's also like this on Linux? I can only find occurences of `OPENRCT2_COMMIT_SHA1` in the powershell files.

**Comment by janisozaur** [comment]
No, it's not set up. I thought there was an issue for that, but there isn't.

Anyway, if someone is to do that, can they also make it so the version (and the lot) is actual variable and not a define only? Otherwise `version.h` will cause constant recompiles by getting invalidated on each commit.

**Comment by IntelOrca** [comment]
> Anyway, if someone is to do that, can they also make it so the version (and the lot) is actual variable and not a define only? Otherwise version.h will cause constant recompiles by getting invalidated on each commit.

For whoever does this, make sure you set the variables to the same macros, otherwise you will break the way Windows CI populates them. The variables can be called `gOpenRCT2CommitSha1` or something. Or make a version struct... `gVersion` with `CommitSHA1`.
