### ISSUE TITLE
Bigger arrows for value input boxes

### ISSUE THREAD

**Issue by Niels-NTG** [OpenRCT2/OpenRCT2#4143]
Rollercoaster Tycoon 2 is an phenomenal game in almost every way. Except the finicky UI. The UI definitely needs some work. Starting with those tiny 10 by 5 pixels sized buttons one uses to set the value of loans, entry fees, etc. I often still click the wrong up instead of down when changing a price and visa versa, especially with contemporary screen resolutions.

![schermafbeelding 2016-07-20 om 19 11 55 2](https://cloud.githubusercontent.com/assets/6061595/16997269/00dca672-4eb5-11e6-90da-d8ae33c74be9.png)

I like to propose a solution where both buttons are 10 by 10 pixels in size and take up the whole height of the input box. See the mockup below.

![schermafbeelding 2016-07-20 om 19 11 55](https://cloud.githubusercontent.com/assets/6061595/16997281/0a6a7d90-4eb5-11e6-99f5-65d8d7146c71.png)

Additionally I’ve designed a disabled (“greyed-out”) version of the arrow buttons, something not currently present in openRCT2. This is useful in situations where the value can’t be changed. The colour of the arrows for a disabled input box are the same as the dark part of the edge of the box itself.

**Comment by janisozaur** [comment]
I like this idea, but until we do some heavy refactor of UI code, this would mean manually going into each window, recalculating these buttons and applying changes for each of the spinners.

In other words: this will have to wait a while.

**Comment by Niels-NTG** [comment]
Ah yes, that explains why I couldn't really find it in the code. Then again, I'm not that experienced with C.

While you're refactoring that part of the codebase, I've a number of other ideas related to improving the UI. I will make separate issues for each of them.

**Comment by janisozaur** [comment]
Please do.

This is how it roughly works right now: https://github.com/OpenRCT2/OpenRCT2/blob/a6d0e69/src/windows/park.c#L123-L125

**Comment by marijnvdwerf** [comment]
The proposed solution doesn't match up with default Windows nor macOS controls, which makes it more difficult to use because it's foreign. Also, this solution looks rather similar to the dropdowns already used in the game, making it perhaps more confusing.

I'd suggest either bigger controls in general, which will likely also solve this problem (especially if you make the clickable area extend a bit outside the visible edges). Otherwise something like the examples below might make more sense, as they are distinctly different from dropdowns.

![image](https://cloud.githubusercontent.com/assets/737603/17000248/df449382-4ec1-11e6-8dfd-77586771e5af.png) ![image](https://cloud.githubusercontent.com/assets/737603/17000264/f471bf50-4ec1-11e6-86df-109a1bcf5c4d.png)

**Comment by Niels-NTG** [comment]
I can definitely see possible confusion with the dropdown menus. Here is a new mockup with this in mind:

![schermafbeelding 2016-07-20 om 19 11 55 3](https://cloud.githubusercontent.com/assets/6061595/17000946/400bf96e-4ec5-11e6-9366-087fe769ca4e.png)

**Comment by Nubbie** [comment]
@marijnvdwerf 
>Ideas to create powerful presentations (the documents name)

_Are you trying to slip in something subliminal for OP or just talking about yourself now?_ :smile: 

----
**No but for reals**, it would take a while to apply this for all windows, would make a bit more sense tho' as we actually have the size for it (the drop down lists often have a lot of empty space)

**Comment by Liampie** [comment]
I like how it currently is more than both of these proposals. Maybe these are easier to click but they're not as intuitive as the default up/down arrows. I think people are way more likely to press the wrong button with your proposed design.

But to be honest I've never had problems clicking these buttons. At least I can't recall it being an issue!

**Comment by e-foley** [comment]
We might also consider the RCT3-style "click the value and drag to change it" method.

**Comment by Niels-NTG** [comment]
Yes, I was thinking about that too. Didn't include it in my initial proposal because it might not fit RCT1/2 that wel. But it's worth trying. I will make a mockup tomorrow.

-----Oorspronkelijk bericht-----
Van: "Ed Foley" <notifications@github.com>
Verzonden: ‎20-‎7-‎2016 22:56
Aan: "OpenRCT2/OpenRCT2" <OpenRCT2@noreply.github.com>
CC: "Niels NTG" <NTG999@gmail.com>; "Author" <author@noreply.github.com>
Onderwerp: Re: [OpenRCT2/OpenRCT2] Bigger arrows for value input boxes (#4143)

We might also consider the RCT3-style "click the value and drag to change it" method.

**Comment by RealRexen** [comment]
Maybe have an option to toggle between default style, +,- next to each, or RCT3 style

**Comment by Niels-NTG** [comment]
> But to be honest I've never had problems clicking these buttons. At least I can't recall it being an issue!

If you use a mouse, yes. But is quite irritating when using a touchpad. OpenRCT2 is quite a relaxing game I play while laying on the couch or commuting to work. Those aren't places you want to carry around a mouse.

**Comment by Patrik356b** [comment]
touch screen is also quite awkward to work with

**Comment by Niels-NTG** [comment]
Indeed. I think the key to making this game more accessible for non-mouse input is to, like @marijnvdwerf already suggested, make some elements in the UI bigger. Not just making these arrow buttons bigger. Also some more margin between window borders and lines of text would be nice. The UI is currently way too densely packed with typography. I will attempt to make a mockup of how this could potentially look like before the end of the week.

**Comment by Margen67** [comment]
I wish all boxes like this would let you click them and type in the value

**Comment by Niels-NTG** [comment]
@Margen67 That seems like an obvious solution, I thought about it too. But if it was this obvious the original game would already have this input method. I think it was a deliberate choice to not let players type any value they want to make the game more accessible. The fixed increments by which you edit values forces players to guess the right prices by gut instead of finding the exact values to min-max everything.

**Comment by AaronVanGeffen** [comment]
This will be tackled by #7579.

**Comment by Niels-NTG** [comment]
@AaronVanGeffen I've just gave the latest build a try and I'm quite happy with the result. Consider this issue closed!
