### ISSUE TITLE
scenario_initial_cash  command seems to be missing

### ISSUE THREAD

**Issue by RealRexen** [OpenRCT2/OpenRCT2#4162]
the wiki page https://github.com/OpenRCT2/OpenRCT2/wiki/Console says scenario_initial_cash  is a command but yet the console says its not a valid command.

Build is 0.0.5 418eb06
![20160723172217_1](https://cloud.githubusercontent.com/assets/18408903/17080363/12ef82e8-50fa-11e6-94c6-3fabd142a642.jpg)

**Comment by janisozaur** [comment]
it's most likely an argument to `set`, can you check?

**Comment by Nubbie** [comment]
@RealRexen It's a set command so type in 'Set' before it

**Comment by RealRexen** [comment]
Ah thanks it works. The wiki didn't make it clear or something like that
