### ISSUE TITLE
Keep on crashing on OpenRCT2 0.0.5

### ISSUE THREAD

**Issue by BoomDuple** [OpenRCT2/OpenRCT2#4164]
**OS:** [Windows 7 SP1]
**Version:** [0.0.5]
**Commit/Build:** [55ec765]

I keep on crashing after installing OpenRCT2 on RCT2 and cant boot and leaves a dump file
Here is a dialog while starting up,
"Scanning 2190 objects...
1KHFRUIC Error: Bad image table.
1KHFRUIC Error; Unexpectedly reached end of file.
Error reading object: 'C:\Program Files (x86)\OpenRCT2\ObjData\1KHFRUIC.dat
ASFOUNT Error: Image table too large.
Dump Path: C:\Users\solo\Documents\OpenRCT2\
Dump File Path: C:\Users\solo\Documents\OpenRCT2\79c1d996-1c69-46ce-93b-7da6cc552ac8<55cec765>.dmp
Dump Id:79c1d996-1c69-46ce-93b-7da6cc552ac8
Version 0.0.5
Commit 55ec765"
Here is the file, zipped
(Github for some reason, glitched and i could not paste the file onto the text)
https://drive.google.com/open?id=0BwQrKTJI38x3d28wTWhEYVpHSUU

**Comment by mrtnptrs** [comment]
Please delete 1KHFRUIC.dat from C:\Program Files (x86)\OpenRCT2\ObjData\1KHFRUIC.dat and maybe also from ObjData folder of your RCT2 vanilla installation. We probably are dealing with a corrupted object file, which is causing the game to crash.
