### ISSUE TITLE
Refresh Ride ratings

### ISSUE THREAD

**Issue by RealRexen** [OpenRCT2/OpenRCT2#4168]
Sometimes I build a ride first test it, and look at the ratings. Then I built scenery around the ride. However because the ride already got its ratings when I first test it I would have to do something to the ride it self to cause it to reset the ratings such as change the vehicle or amount of trains/vehicle.  What I would like is a button that tells the game that the ride has been "updated" and needs to get new ratings.

**Comment by IntelOrca** [comment]
The game constantly loops over every ride updating its ratings, you don't need to force it to refresh.
