### ISSUE TITLE
No message box appearing after you made a screenshot in-game

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#4169]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 291667d

- [ ] Reproducible in RCT2 (vanilla)? (Vanilla RCT2 did it correctly)
- [ ] Multiplayer?

**Steps to reproduce:**
1. Make a screenshot in-game.
2. You see not red message box appear saying whether the screenshot was made or there was an error and what the file name of the screenshot is. When you make a giant screenshot, this works perfectly, but for normal screenshots, this doesn't work. And I can remember a long time ago, this worked perfectly in OpenrCT2

**Comment by IntelOrca** [comment]
I removed it because if you take several screenshots consecutively the error box from the last one appears in the screenshot.

**Comment by Niels-NTG** [comment]
A good sound effect and/or a subtle visual effect would be a better solution.

**Comment by mrtnptrs** [comment]
I agree with @Niels-NTG

**Comment by Niels-NTG** [comment]
You could trigger the lighting flash weather effect when taking a screenshot.

**Comment by mrtnptrs** [comment]
What do you think @IntelOrca ?

**Comment by IntelOrca** [comment]
I don't know

**Comment by Patrik356b** [comment]
maybe make yellow text like the floating price tag saying "saved screenshot xyz.png"

**Comment by mrtnptrs** [comment]
@Patrik356b not a good idea: the same reason as why @IntelOrca  removed the error box when you made a screenshot: you can see it in the next screenshot

**Comment by Patrik356b** [comment]
hence the maybe. I didn't know those would show up too on the screenshots

**Comment by Niels-NTG** [comment]
`audio_play_sound(SOUND_QUACK, 100, gScreenWidth / 2);`? 😉

**Comment by Niels-NTG** [comment]
Ok seriously…
`audio_play_sound(SOUND_WINDOW_OPEN, 100, gScreenWidth / 2);` feels actually quite fitting.

**Comment by Nubbie** [comment]
@Niels-NTG Did someone add it? :p

**Comment by Niels-NTG** [comment]
@nubbie, yes. I added the aforementioned sound effect in https://github.com/OpenRCT2/OpenRCT2/pull/4163
