### ISSUE TITLE
Time-lapse mode

### ISSUE THREAD

**Issue by Niels-NTG** [OpenRCT2/OpenRCT2#4170]
As a followup to https://github.com/OpenRCT2/OpenRCT2/pull/4163 I think it might be a cool idea to have an options that enables automatically taking a giant screenshot on a regular interval. Possibly each time an autosave occurs.

A timelapse series is stored in its own folder inside the default `screenshot` folder. This makes it easy to compile an timelapse animation in programs like Adobe Premiere, Apple Final Cut, etc.

**Comment by IntelOrca** [comment]
Perhaps when @janisozaur implements a scripting engine...
