### ISSUE TITLE
Tunnel path not rendering

### ISSUE THREAD

**Issue by ptkato** [OpenRCT2/OpenRCT2#4177]
**OS:**
Arch Linux
**Version:**
0.0.5
**Commit/Build:**
ae80ba4

I've built a path going through a wall, it made a tunnel, it's ok, but when I built another tunnel just next to it, the first one vanished, but the guests still go through.

![screenshot from 2016-07-25 20-43-27](https://cloud.githubusercontent.com/assets/10677806/17121537/d0f9de1c-52aa-11e6-89e0-340fd79142db.png)

The tunnel is located at the red line.

**Save game:**
[Six Flags.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/382745/Six.Flags.sv6.zip)

**Comment by mrtnptrs** [comment]
Could this be a duplicate or related to #3561?

**Comment by Gymnasiast** [comment]
I don't think so. I also think that #3561 is solved by now.

**Comment by duncanspumpkin** [comment]
Its not related. If its not drawing it tends to be the map element that makes the tunnel that is wrong (although that isn't always true). If the drawing is wrong (or malformed) it tends to be the surface drawing that is wrong.

**Comment by duncanspumpkin** [comment]
This has now been fixed probably by https://github.com/OpenRCT2/OpenRCT2/pull/4382
