### ISSUE TITLE
More than 2 rides not always synchronising properly

### ISSUE THREAD

**Issue by jensj12** [OpenRCT2/OpenRCT2#4178]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 67d4ff8

Reported on the OpenRCT2 forums: https://openrct2.org/forums/topic/1498-racing-3-rides-or-more-issue/
Even with 'Synchronise with adjacent stations' enabled, rides won't always synchronise properly.

**Steps to reproduce:**
1. Build multiple coasters next to each other and enable 'Synchronise with adjacent stations' on all of them
2. Test or open the rides, and watch the result

**Screenshots / Video:**
https://youtu.be/pW84xeS2EDk

**Comment by IntelOrca** [comment]
Does this also happen in vanilla?

**Comment by giraty** [comment]
Hi it's me who posted the issue on the forum and this is a sample savegame. Check the 5 racing coasters behind the park. Vanilla RCT2 can handle up to 9 racing coasters.

http://www.mediafire.com/download/hzqxq3rkxi8uzg8/Erode_Park_Sample.SV6

**Comment by IntelOrca** [comment]
@jensj12 could you check if 5a046ece6078bc7629250b3ee45acb683b785f53 fixed this?
