### ISSUE TITLE
Water of water rides gets renderd brown when behind the console window

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#4180]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** d8d39c1

**Steps to reproduce:**
1. Build a water ride.
2. Open the console.
3. Move the map in such a way that the water ride is behind the console window.
4. The water of the ride gets rendered brown. 

This only happens with water rides, not with normal water or water objects. I know this is a very minor visual bug, but it could also be a general issue with transparency in-game.

**Screenshots / Video:**
![2016-07-27_13-16-23](https://cloud.githubusercontent.com/assets/4948213/17174215/1a5b4efa-5400-11e6-9487-b29fc2d48f9c.png)
![2016-07-27_13-17-13](https://cloud.githubusercontent.com/assets/4948213/17174216/1a620e20-5400-11e6-9c40-3ee43a9ce9f4.png)

**Comment by IntelOrca** [comment]
Just the way the game palettes work. Water is dynamic colours and therefore has no corresponding coloured transform index.
