### ISSUE TITLE
Add cheat/option to set date

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#4184]
There should some way of setting scenario date.

One easy way to do that would be to add another console command: `set date XXX`. It may be useful to support `YYYY-MM-DD` and `#TICKS` formats.

**Comment by IntelOrca** [comment]
and `YYYY-MM-DD`?

**Comment by janisozaur** [comment]
That was a typo.

**Comment by IntelOrca** [comment]
and YYYY-MM as well?

**Comment by janisozaur** [comment]
I'd say no, you can always set `YYYY-MM-01` which would be equivalent to `YYYY-MM`.

**Comment by IntelOrca** [comment]
Unless you want it to keep the day the same, which means we can also do `YYYY` too.

**Comment by Patrik356b** [comment]
It would be useful if it could be used to just advance time too, like 5 months but I don't know what would be the best way to do it

**Comment by janisozaur** [comment]
Prefixing the date with either `+` or `-` could indicate relative change, like so: `+0000-05`

**Comment by Patrik356b** [comment]
good idea

**Comment by Ziscor** [comment]
Is this still being worked on? Having to fast-forward to your desired scenario date can become quite tedious and such a feature would be a great help. I've been told 8Cars had the feature to set a manual date too. Thank you!

**Comment by IntelOrca** [comment]
I can't remember why I assigned myself to this. It isn't currently being worked on.

**Comment by rwjuk** [comment]
Implemented in #6959.
