### ISSUE TITLE
64 bit builds should be working

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#4198]
Tracking issue for progress on getting 64 bit builds going. This primarily targets AMD64, but once done should also work on AArch64/LE and other architectures.

Possibly it can enable more performance gains. One thing worth keeping an eye on is optimisations now possible to `rct_map_element`, which is [8 bytes long](https://github.com/OpenRCT2/OpenRCT2/blob/9652f68/src/world/map.h#L114).

As of 2016-08-01 (9cf3419) Linux can properly build 64 bit versions and a job has been added to our Travis CI to make sure we don't regress. These builds can launch properly and load objects, but have issues rendering viewport, some(?) dropdowns don't work and they crash pretty soon after launch.

Once https://github.com/OpenRCT2/OpenRCT2/issues/3365 is closed, 64 bit build should be able to render pixel-perfectly compared to 32 bit builds

**Comment by janisozaur** [comment]
With https://github.com/OpenRCT2/OpenRCT2/pull/4191 it is possible to open in-game load window, load a game, join multiplayer and host a server all without a crash for significant period of time.

**Comment by janisozaur** [comment]
64-bit builds have two kinds of `-Werror` lifted:
* `-Wno-error=pointer-to-int-cast`
* `-Wno-error=int-to-pointer-cast`

Below are some collected stats (count of warnings):
* 2016-08-02 (63c74b4): 234

**Comment by janisozaur** [comment]
A little progress video based on current #4203: https://www.youtube.com/watch?v=uLY6jmHtKgg&feature=youtu.be

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/commit/f8e0d4b25b7c678bac64c53986979919f7e16b2f fixed dropdowns using `string_id == 0` as a separator

**Comment by marijnvdwerf** [comment]
`STR_EMPTY` imho is the wrong name for use in dropdowns. `DROPDOWN_SEPARATOR` or something along the lines would make more sense, as it doesn't render as an empty string.

**Comment by marijnvdwerf** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/0be54fbac3671d73ab4f143504de76cce18648ec/src/windows/dropdown.h#L22

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/pull/4228 makes 64 bit builds render correctly:

![openrct2_141](https://cloud.githubusercontent.com/assets/550290/17451677/ec242942-5b68-11e6-8327-666167869f1d.png)

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/pull/4244 enables (a bit incomplete) 64 bit builds on OS X.

<img width="1392" alt="screen-shot-2016-08-06-at-5 42 02-pm" src="https://cloud.githubusercontent.com/assets/550290/17460807/435401da-5c75-11e6-8c29-42eb9f63997d.png">

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/pull/4243 added x86-64 configuration to Visual Studio project. It can be used in similar manner as #4244, but it requires contribution of Windows version of `mmap`.

**Comment by janisozaur** [comment]
#4244 now includes code which can produce 64 bit version for Windows using mingw64 toolchain. There's a small issue, where I had to manually add `-liconv` to the final linking step.

![openrct2_win64](https://cloud.githubusercontent.com/assets/550290/17465012/b84aed7a-5ceb-11e6-9f6d-3d4ff12da2d2.png)

**Comment by AaronVanGeffen** [comment]
Am I correct in assuming at this stage we only link segment files from the original binary for data that is not integrated as of yet? The missing paint functions aren't being used at the moment, anyway — I'm assuming that's because they're for a different architecture?

**Comment by janisozaur** [comment]
We're interested in `.data` segment. It is getting extracted from original binary and emplaced to memory at some known, arbitrary location. Whatever is trying to use original's data, will simply get redirected to the new location, which is why https://github.com/OpenRCT2/OpenRCT2/pull/4236 is needed. All the integrated stuff comes from our own `.data` segment, even though there might still be a duplicate of it loaded to memory – we simply don't use it anymore.

**Comment by AaronVanGeffen** [comment]
That answers the first half of my question, thank you. The unimplemented functions cannot be used, then, I take it?

**Comment by janisozaur** [comment]
I don't use them. Whether they can be used is a whole other story… They can be used, but it would probably come at severe performance hit, work only on Linux and not really worth it, as https://github.com/OpenRCT2/OpenRCT2/issues/3365 is going forward ever so slowly.

**Comment by janisozaur** [comment]
Audio tab in options doesn't work and may crash the game, because I don't know how to fix these `set_format_arg`s: https://github.com/OpenRCT2/OpenRCT2/blob/6644902/src/windows/options.c#L1521-L1536

**Comment by IntelOrca** [comment]
@AaronVanGeffen no they can't be used, they are x86 instructions expecting 32-bit addresses. It just wouldn't work.

**Comment by janisozaur** [comment]
@IntelOrca yes, there are ways you could use them. You can switch between 32 and 64 bit mode on the fly.

**Comment by IntelOrca** [comment]
But you have put the data in a 64-bit address range...

**Comment by janisozaur** [comment]
yes. but `0x8a4000` is both in 32 bit and 64 bit range.

**Comment by IntelOrca** [comment]
@janisozaur any other crashes that you know of?

**Comment by janisozaur** [comment]
No, I don't think I know of any more crashes now – at least versus 32 bit build.
