### ISSUE TITLE
FPS decreases with track window

### ISSUE THREAD

**Issue by Azruine** [OpenRCT2/OpenRCT2#4213]
**OS: Window 10
**Version: 0.0.5
**Commit/Build: 69027a8

![fps1](https://cloud.githubusercontent.com/assets/6277538/17389191/e354d6b8-5a3c-11e6-8d02-0cdad80c30c4.png)
![fps2](https://cloud.githubusercontent.com/assets/6277538/17389190/e34ee1fe-5a3c-11e6-9a78-f34a5f09de28.png)

You can see FPS Counter at the top of the screenshot. It decreases to 10~20 whenever I open track window or something.

Sorry For my bad Eng :/

**Comment by IntelOrca** [comment]
It will decrease, the more viewports you have open. This is because it has to draw a whole different view from scratch per viewport.

**Comment by Wirlie** [comment]
I've tried to reproduce this problem and yes, I have this problem only with the ride window:
![cachon botanico 2016-08-04 10-58-55](https://cloud.githubusercontent.com/assets/7508197/17408878/8090cfaa-5a32-11e6-9e9f-22a02f5a81dc.png)
![calamidades en el canon 2016-08-04 10-55-07](https://cloud.githubusercontent.com/assets/7508197/17408823/5221f630-5a32-11e6-8c3e-b619fe695c78.png)
![calamidades en el canon 2016-08-04 10-54-38](https://cloud.githubusercontent.com/assets/7508197/17408825/5439623c-5a32-11e6-9ed3-22b57c42736a.png)

**Comment by Wirlie** [comment]
Issue introduced by #4176
