### ISSUE TITLE
Multiplayer, default group does not work correctly with group IDs

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#4215]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 0be54fbac3671d73ab4f143504de76cce18648ec

Default group is mixing up id and index in groups.json. It doesn't seem to work when set to an id that is much higher than the total number of groups.

**Example:**
[groups.json](https://github.com/OpenRCT2/OpenRCT2/files/402211/groups.json.txt)

Default group does not persist when set to "1-Chat Only"

**Comment by joshbgosh10592** [comment]
Seems to be intermittent. I never modified my file to place them in order, and on my next server launch after the last build (32fea99) the default group was set correctly. This happened before as well, as I mentioned in the chat.
