### ISSUE TITLE
Lastest developer branches not allowing for palette/color changes for certain rides

### ISSUE THREAD

**Issue by spawnraider** [OpenRCT2/OpenRCT2#4231]
I cannot change the color of certain things such as hats or balloons nor can I make color palette changes to rides such as spiral slides or maze. The changes simply don't take place. This is both in single player and multiplayer. I know that this problem appears sometime after build 0.0.5 8f25470. Can anyone else reproduce this? It happens on every map for me, new and old.

**Comment by duncanspumpkin** [comment]
Caused by https://github.com/OpenRCT2/OpenRCT2/commit/436809f778a9bfd3bf80ab26c7dcef74416b23e4 fix will just be a sec
