### ISSUE TITLE
Suggestion: Uninterrupted Land rights purchasing

### ISSUE THREAD

**Issue by UTNerd24** [OpenRCT2/OpenRCT2#4232]
So as of recent builds, if you attempt to freely "Spray" land rights, and your selection is even one block wider than the available land, a warning will pop up and halt the process until it is closed.

Is it possible to make it so that the message can be ignored and the player can continue buying land rights provided he or she has enough money? Only then will the action be halted.
Apologies if this topic has already been addressed.

**Comment by Margen67** [comment]
This happens with path placement as well. It's quite annoying.

**Comment by Nubbie** [comment]
The question is; Should this apply on all error messages that interrupt placement? (Setting to disable error tool tips from interrupting what you're doing)

**Comment by Nubbie** [comment]
Duplicate #2677
