### ISSUE TITLE
Some scenery dissapears while zooming out x2 or more

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#4237]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 680f7b7

- [ ] Reproducible in RCT2 (vanilla)?: No, I have tested this with vanilla RCT2 and the scenery didn't dissapear when zooming out. 
- [ ] Multiplayer?

**Steps to reproduce:**
1. Start a game with some wheels or flames from the mechanical theme, or just build this scenery (will test it later if it happens with more scenery.) 
2. Now zoom out twice (so, zoom out 2 factors)
3. The wheels and flames dissapear from the map, which didn't happen while zooming out in vanilla RCT2.

**Screenshots / Video:**
Vanilla RCT2:

![scr5](https://cloud.githubusercontent.com/assets/4948213/17457890/ddc2beda-5c04-11e6-9c75-14b83b1bca00.png)
![scr4](https://cloud.githubusercontent.com/assets/4948213/17457892/ddc88eb4-5c04-11e6-89f5-838fc8dfc56e.png)
![scr3](https://cloud.githubusercontent.com/assets/4948213/17457893/ddc9dfda-5c04-11e6-8ea4-3733fd3c1354.png)
![scr2](https://cloud.githubusercontent.com/assets/4948213/17457891/ddc74806-5c04-11e6-998b-83d3ee0cc8da.png)

OpenRCT2:

![six fingers 2016-08-06 18-22-29](https://cloud.githubusercontent.com/assets/4948213/17457917/02fa27ce-5c05-11e6-92e9-8147f18fadec.png)
![six fingers 2016-08-06 18-23-02](https://cloud.githubusercontent.com/assets/4948213/17457916/02f80372-5c05-11e6-8410-438f013a3cc3.png)
![six flags 2016-08-06 18-39-08](https://cloud.githubusercontent.com/assets/4948213/17457924/19bb0d3e-5c05-11e6-910d-02cd80451873.png)
![six flags 2016-08-06 18-39-15](https://cloud.githubusercontent.com/assets/4948213/17457925/19bc07f2-5c05-11e6-994a-b1d515a038f5.png)

**Comment by IntelOrca** [comment]
This is probably expected behaviour, same reason you can't see sprites are furthest zoom level.

**Comment by mrtnptrs** [comment]
@IntelOrca Please read it again: the behavior of this is different then vanilla RCT2, where all scenery didn't dissapear when zooming out.

**Comment by duncanspumpkin** [comment]
The flag is probably being used incorrectly in paint setup. I'll take a look tomorrow morning if no one fixes it before then
