### ISSUE TITLE
Banner font is black when using ttf font

### ISSUE THREAD

**Issue by YJSoft** [OpenRCT2/OpenRCT2#4251]
**OS:** OS X
**Version:** 0.0.5
**Commit/Build:** 0fbdcbe

Banner font is black when using ttf font.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Screenshots / Video:**
![2016-08-08 16-14-47](https://cloud.githubusercontent.com/assets/5893514/17472016/48fd2be8-5d83-11e6-9d0b-719aa08b7ef7.png)
Font is invisible as font's color and background color is almost same.

**Comment by Niels-NTG** [comment]
Slightly related: I presume we're aiming to convert every sprite-font to a ttf eventually? Better yet: use a single font with a wide range of characters covering all supported locales. We have the unicode standard now, unlike back when RCT1 first came out.

**Comment by IntelOrca** [comment]
> I presume we're aiming to convert every sprite-font to a ttf eventually?

No, we will always support sprite font, we can't replicate the look with TTF exactly.

> We have the unicode standard now, unlike back when RCT1 first came out.

Unicode was around before RCT1.

**Comment by YJSoft** [comment]
<img width="124" alt="2016-08-13 10 23 11" src="https://cloud.githubusercontent.com/assets/5893514/17640681/161a05a0-6140-11e6-9d40-e639cea4a24a.png">
There's no text color option at banner window. so this might be reason of this issue.

**Comment by YJSoft** [comment]
Nevermind, my mistake.

some text color works, but actual color is wrong.
<img width="134" alt="2016-08-13 10 27 39" src="https://cloud.githubusercontent.com/assets/5893514/17640704/b31dd606-6140-11e6-87fe-e1da6e293441.png">
<img width="124" alt="2016-08-13 10 27 51" src="https://cloud.githubusercontent.com/assets/5893514/17640706/b326b140-6140-11e6-9cf0-5ac50b0666cb.png">
<img width="131" alt="2016-08-13 10 28 02" src="https://cloud.githubusercontent.com/assets/5893514/17640705/b3209832-6140-11e6-85c6-8ba07a8f6d84.png">

**Comment by YJSoft** [comment]
#4199 introduced this issue.
