### ISSUE TITLE
Max window count is displayed wrong at the options screen

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#4254]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 53ec220

**Steps to reproduce:**
1. Start OpenRCT2
2. Open the options window.

The window limit count is now displayed standardly at 320 (which is the maximum) and can be lowered to 260 (the minimal). But when set to 320, the window limit count is 60 and when the window limit count is displayed as 260, the window count actually is 4.

So, it is only displayed wrong at the options menu. Even after deleting my confix file. 

Strangely 349684b seems to have caused this issue. I did not manage to find the cause of the bug to fix it myself. Maybe @wolfreak99 could take a look at this?

**Comment by Gymnasiast** [comment]
Should have been fixed by https://github.com/OpenRCT2/OpenRCT2/commit/498bab24c3dcb92f82f13efd082a0891494fbd9b
