### ISSUE TITLE
Linux Multiplayer SSL Issue?

### ISSUE THREAD

**Issue by Zebra1337** [OpenRCT2/OpenRCT2#4257]
**OS:** Fedora 24 Linux
**Version:** latest
**Commit/Build:** 79e755a

Hello, I successfully compiled OpenRCT2 on Fedora 24 with the lates OpenSSL. Only problem is, there seems to be some sort of certificate error when accessing the server browser in-game. 

ERROR[/home/alex/Documents/OpenRCT2/src/network/http.cpp:168 (http_request_json)]: HTTP request failed: Problem with the SSL CA cert (path? access rights?).
WARNING[/home/alex/Documents/OpenRCT2/src/windows/server_list.c:780 (fetch_servers_callback)]: Unable to connect to master server

My ca-certificates is installed and up to date.. been googling but not found a solution yet. 

Any ideas?

**Comment by janisozaur** [comment]
Make sure your curl is configured properly and is able to access https://servers.openrct2.website/

**Comment by Zebra1337** [comment]
curl works when trying it through command line:

http://i.imgur.com/sYXU7IT.png

**Comment by Zebra1337** [comment]
curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, true);

Setting that to false in http.cpp allows it to work, but obviously not very good from a security point of view. Perhaps my curl is looking in the wrong place.

Will look into this
