### ISSUE TITLE
Can't pop balloons

### ISSUE THREAD

**Issue by spawnraider** [OpenRCT2/OpenRCT2#4261]
Balloons can't be popped in single player or multiplayer. Nothing happens when you click on them.

**Comment by mrtnptrs** [comment]
@spawnraider Are you sure your problem isn't the same as this issue report?: #675

**Comment by spawnraider** [comment]
I don't think so since I see no response at all. No movement or popping.

**Comment by Gymnasiast** [comment]
Why did you remove the issue template? It isn't there for nothing. Please put it back and fill in the appropriate fields.

**Comment by zsilencer** [comment]
balloon popping was disabled in multiplayer because it causes desyncs but it should still work in single player.

**Comment by Nubbie** [comment]
Expired?

**Comment by Gymnasiast** [comment]
Can't reproduce it in single player, it's disabled deliberately in multiplayer and the OP has not responded to my requests. Closing this.

**Comment by Margen67** [comment]
Will it be re enabled if it doesn't cause a desync?

**Comment by duncanspumpkin** [comment]
It would require making a game command just for popping but yes if that was done it could be reenabled.
