### ISSUE TITLE
Sign bug

### ISSUE THREAD

**Issue by primebro** [OpenRCT2/OpenRCT2#4264]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** bb07785

Signs are "connected" to each other, if you delete one of them and scroll to the position where another one was, the game crashes. All signs look the same way and when you right-click on one, it shows the position of the "main" one.

**Steps to reproduce:**
1. just delete the sign or take away the paths they are on.

**Dump file**
[1309ce87-edeb-4ccd-9e25-bb365aad4e9b(bb07785).zip](https://github.com/OpenRCT2/OpenRCT2/files/413799/1309ce87-edeb-4ccd-9e25-bb365aad4e9b.bb07785.zip)

**Screenshots / Video:**

**Save game:**
[Prime Park FINAL v1.9 end.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/413800/Prime.Park.FINAL.v1.9.end.sv6.zip)

**Comment by mrtnptrs** [comment]
@primebro It would be better to report each bug you mentioned in a seperate bug report :)

**Comment by primebro** [comment]
@mrtnptrs done.

**Comment by duncanspumpkin** [comment]
Can not reproduce. I tried deleting every sign i could find and was not able to crash the game.

**Comment by IntelOrca** [comment]
Is anyone else able to reproduce?

**Comment by ThomasdenH** [comment]
I'm not able to reproduce this either.
