### ISSUE TITLE
Delete trackpiece bug

### ISSUE THREAD

**Issue by primebro** [OpenRCT2/OpenRCT2#4265]
**OS:** [e.g. Windows 10]
**Version:** 0.0.5
**Commit/Build:** bb07785

When you delete the "Ultimate" coaster the game crashes.
There is track piece that is untargetable. It is "isolated" in the middle of the coaster, just delete some scenery.

**Steps to reproduce:**
1. Delete the coaster (not piece by piece, just the whole one)

**Dump file**
there is no dumb file for this problem

**Screenshots / Video:**
http://imgur.com/a/mRSIt

**Save game:**
[Prime Park FINAL v1.9 end.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/413835/Prime.Park.FINAL.v1.9.end.sv6.zip)

**Comment by duncanspumpkin** [comment]
Park has a glitched coaster part that can only be created by messing with the tile inspector. I don't really know of a good way to solve this. Could force a delete on that track bit but im not sure if thats a great idea.
