### ISSUE TITLE
Ghost entrances when zero clearance is on

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#4267]
**OS:** Windows 7
**Version:** 0.0.5
**Commit/Build:** aa962b2

When having zero clearance on and placing down a entrance, it can mess up the entrance creating a unremovable ghost 

Reported on discord:

>Flint "Duck Mechanic" Webber - Today at 2:13 AM
yeaaah, and any body who works on the game could you make it so that cheats turn off when you go into the editor? that's what causes that

and forum:
https://openrct2.org/forums/topic/1546-list-of-ideas/#comment-9232

**Why is this a problem?**
* cheats can't be turned off in scenery editor which can mess up the map

----

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Turn on Sandbox mode + Zero Clearance 
2. Open up the map
3. Place down a entrance and see how it 'ghosts' out

**Screenshots / Video:**
https://vid.me/qi7f

**Comment by duncanspumpkin** [comment]
Fixed in #4492
