### ISSUE TITLE
List of guests on ride is empty for certain non-track rides

### ISSUE THREAD

**Issue by RQWorldblender** [OpenRCT2/OpenRCT2#4289]
**OS:** Ubuntu 16.04 (May apply to other operating systems)
**Version:** e.g. 0.0.5
**Commit/Build:** 07989e325fcad9c92144f3783a6e1fd348b64950, compiled from source

When checking out which guests are on a particular ride, the list is properly retrieved, except for the following rides:
- Crooked House
- Haunted House
- Circus
- Maze
- 3D Cinema

When one of those rides is built, the caption list of guests on that ride will display as "Guests In On [ride name]". After saving the scenario containing that ride, the caption will change to "Guests In On" and stop there, and the list of guests on that ride is not retrieved (Sometimes another string other than the ride name may appear after the latter string, such as a scenery group or a different ride name).
There may be other rides with this problem, but those are the only ones that I confirmed this problem for.

Reproducible in RCT2 (vanilla)? Unlikely; an earlier commit likely introduced this bug.

**Steps to reproduce (steps 1 - 2 do not need to be done if a scenario or saved game with one or more of the existing rides is loaded):**
1. Start a new scenario not containing one of the above rides, then build a new of one of those rides.
2. Open that ride's list of guests on ride.
3.Save the game, then load the game again.
4. Navigate to one of those rides, then open that ride's list of guests of ride again.

**Screenshots:**
![funtopia 2016-08-14 20-02-30](https://cloud.githubusercontent.com/assets/13372387/17653370/0f62acc4-625a-11e6-9ed5-d9d121726e13.png)
![blackpool pleasure beach 2016-08-14 19-59-17](https://cloud.githubusercontent.com/assets/13372387/17653357/e7215d1e-6259-11e6-81c7-b6686e84c8d7.png)
![heide-park 2016-08-14 20-00-03](https://cloud.githubusercontent.com/assets/13372387/17653358/e72298d2-6259-11e6-8f4d-fe868aa5f340.png)
![linkin park 2016-08-14 19-57-51](https://cloud.githubusercontent.com/assets/13372387/17653359/e722f6f6-6259-11e6-9393-ede3f3fe1d39.png)

**Comment by duncanspumpkin** [comment]
I cant reproduce on the latest builds can you double check this is still happening.

**Comment by RQWorldblender** [comment]
It seems like this bug has indeed been fixed in a recent commit. :)
