### ISSUE TITLE
Feature Request: Single-Player Zero Clearance Permission in Multiplayer

### ISSUE THREAD

**Issue by thyeggman** [OpenRCT2/OpenRCT2#4292]
Permit single players to be able to use zero clearance.  Perhaps add another user role to enable this.

I may take a stab at this at some point, but I don't know when I would get to it.

**Comment by joshbgosh10592** [comment]
Or, vice verse. Cheat is globally enabled, and a single user wants to turn it back on so they cannot collide.

**Comment by Margen67** [comment]
Fixed by #4483?

**Comment by Nubbie** [comment]
Duplicate #3641

**Comment by Gymnasiast** [comment]
Closing as (more-or-less a) duplicate of #3641.
