### ISSUE TITLE
Incorrect support drawing

### ISSUE THREAD

**Issue by Wirlie** [OpenRCT2/OpenRCT2#4296]
**OS:**Windows 10
**Version:** 0.0.5
**Commit/Build:**  b9a4ef8

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

![exceso extraterrestre 2016-08-16 10-24-27](https://cloud.githubusercontent.com/assets/7508197/17704891/0c40b390-639c-11e6-9dcf-78bf632bbc6b.png)

**Original drawing code:**
![exceso extraterrestre 2016-08-16 10-24-31](https://cloud.githubusercontent.com/assets/7508197/17704917/23567614-639c-11e6-9606-1402e2282bd6.png)

**Comment by duncanspumpkin** [comment]
yes its a known issue with metal support a.

**Comment by janisozaur** [comment]
```diff
diff --git a/src/paint/supports.c b/src/paint/supports.c
index c9f522a..b6a7504 100644
--- a/src/paint/supports.c
+++ b/src/paint/supports.c
@@ -521,6 +521,7 @@ bool metal_a_supports_paint_setup(int supportType, int segment, int special, int
                                        newSegment = esi[segment * 8];
                                        if (height <= gSupportSegments[newSegment].height) {
                                                esi += 72;
+                                               assert((uintptr_t)esi + (segment * 8) < (uintptr_t)_97AF32 + sizeof(_97AF32));
                                                newSegment = esi[segment * 8];
                                                return false;
                                        }
```

**Comment by marijnvdwerf** [comment]
@janisozaur That's not the problem. That branch returns false anyway.

**Comment by janisozaur** [comment]
It's _a_ problem nevertheless.
