### ISSUE TITLE
Junior Rollercoaster drawn issues

### ISSUE THREAD

**Issue by Wirlie** [OpenRCT2/OpenRCT2#4303]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:**  a874756

Junior Rollercoaster have problems to draw trains correctly with certain tracks. I'm not sure if this happens with other roller coasters.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Screenshots / Video:**
(Left: OpenRCT2 Drawing Code / Right: Original Drawing Code)
![o_bug_1](https://cloud.githubusercontent.com/assets/7508197/17766059/c805d986-64ee-11e6-9b2a-a54e97bd1ac6.png)
![o_bug_2](https://cloud.githubusercontent.com/assets/7508197/17766061/ca0a5bda-64ee-11e6-867b-8366b751a274.png)
![bug_3_](https://cloud.githubusercontent.com/assets/7508197/17766263/ddbfda82-64ef-11e6-9a95-c85d968d2c02.png)

**Comment by marijnvdwerf** [comment]
@Gymnasiast paint-setup tag as well

**Comment by duncanspumpkin** [comment]
Yeah this again is known I mucked up the banked turns draw bound boxes. I will get round to fixing it eventually.

**Comment by duncanspumpkin** [comment]
Fixed in #4370
