### ISSUE TITLE
Improve the chat improvement/coloring

### ISSUE THREAD

**Issue by joshbgosh10592** [OpenRCT2/OpenRCT2#4304]
This is to tweak some improvements from #3946 
While typing a new message, the text I'm typing will turn "disconnected" red, or "connected" green.
Interestingly enough, if you keep the message unsent long enough (while typing), it will sometimes turn normal white again.

Also, a suggestion, maybe have the ability to set colors to the usernames in the chat, based on group names? (I can throw this into a new issue request as well if you'd like)

**Screenshots / Video:**
![image](https://cloud.githubusercontent.com/assets/20283787/17808124/3581ecd2-65dc-11e6-8834-fc4283430bba.png)

**Comment by wolfreak99** [comment]
https://github.com/OpenRCT2/OpenRCT2/pull/4501 This will fix that. @IntelOrca could you check into my PR?

**Comment by joshbgosh10592** [comment]
Great! 
I just poked around at another post about the option to turn the background off (suggested by Nubbie on pull #3920 ), which sounds like a good idea. Some keep the chat window open while they're playing (on busy servers) but the background makes it hard to.
That being said, I personally really like the background, as it makes it much easier to read.
Just my $.02
