### ISSUE TITLE
New permission - Usage of unstable cheats

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#4305]
Right now, you can use the normal cheats that doesn't break the game and unstable cheats that can break the game in an instance
These should be seperated

Why:
Many people use dangerous cheats which crashes the game while still needing them for stuff like money etc

**Comment by joshbgosh10592** [comment]
I'd like this as well. I'd like to grant certain users to cheat, but leave the unstable disabled to everyone except me, and a few other moderators on my server.
