### ISSUE TITLE
Global Statistics [WIP]

### ISSUE THREAD

**Issue by thyeggman** [OpenRCT2/OpenRCT2#4306]
I'm going to have a stab at implementing global statistics.  I'm a big fan of statistics, so I want to make these pretty thorough.  The first implementation will probably just include raw numbers, but later on there may be derived numbers (e.g. Guest entry rate per hour of play time while park is open).

**Some points of discussion:**
- Statistics will need to be written to a file in the game folder.  What format should this file use?
- While playing, values will need to be saved.  What's the best way to do this so values will persist across different games?
- Would it be easier/more performant to update the file after closing a scenario or is it acceptable to update it after closing ORCT?

**Categories of statistics:**
- Gameplay (e.g. park management, land bought, staff hired, etc.)
- Ride Construction (e.g. number of pieces placed, total number of rides built/demolished, etc.)
- Guest (e.g. pictures taken, souvenirs bought, total amount of vomit, etc.)
- Scenery (e.g. number of pieces placed/deleted, most frequent pieces, etc.)
- Landscaping (e.g. money spent on landscaping, number of landscaping operations, etc.)
- Financial (e.g. total money earned, money spent divided into categories, park entrance fees, etc.)

I'm open to suggestion for individual statistics you'd like to see and for categories that I haven't come up with here.

**UI:**
I was thinking of adding an option to the save dropdown menu which opens a window.  Each of the categories will have its own tab.  It might be possible to update these in real time by adding current-game statistics to the ones that were read from the file.

If anyone has suggestions before I dive into this let me know.

**Comment by Charlieep** [comment]
Don't some of these already exist on the financial page - a running monthly stat for ticket sales, merchandise sales, landscaping charges, and the main popup shows total entries, etc.
Are you thinking of running totals or just a grand list at the conclusion of the scenario?

**Comment by thyeggman** [comment]
These would be running totals, across all scenarios, for as long as the file remains in the game folder.  For example, if your gross income during the entire course of a scenario was $500k, and then you completed another scenario with a gross income of $500k, then the stats page would display $1m.  Of course, as you completed more scenarios, the total would go up.

**Comment by Charlieep** [comment]
So you are looking at this not at each game but a running total of all scenarios you complete in one ORCT2 session.

**Comment by Charlieep** [comment]
Individual users or multiplayer?

**Comment by thyeggman** [comment]
No, not even one session, I'm talking about the sum total of all play sessions you do, for the life of the game.  Since the file would be stored on your computer, it would be per-user.  I'm not sure how it would work in multiplayer.  My goal would be to have it record only your actions, but capture all the data from the park as a whole.  E.g. if you build a ride, it would add to your "rides built" count, but not any other player's count; but if a ride not built by you earns $5, it would be added to your "total ride income" stat, as well as every other player's stat on the server.

**Comment by WhenPenguinsAttack** [comment]
May we get server statistics, too (running totals for both the current park and entire server) please?

**Comment by thyeggman** [comment]
Server statistics will probably not be in the scope of the work I'm doing right now, but it would be a good thing to implement.  Get back to me after I finish this :)

**Comment by RealRexen** [comment]
I think for the file format it should be something that can't be easily open in a text editor

**Comment by RollingStar** [comment]
I'm a big fan of statistics as well. One thing I didn't see in your list was number of times the game was launched. As for the format, TXT or CSV might work?

>I think for the file format it should be something that can't be easily open in a text editor

I completely disagree. It's going to be near-impossible to make a stat tracker in an open-source game that isn't easily manipulated and cheated if that's what a user wants to do. So why put obstacles in the way of someone who just wants to graph the data in Excel?

Although I sympathize with IntelOrca and would never expect people to implement or maintain code they despise, I do think some statistics gathering would be cool. Super Smash Bros. Melee and the TimeSplitters series have some great and obscure data. For example, number of watermelons smashed -- a trivial part of TimeSplitters, but they tracked it anyway.

**Comment by janisozaur** [comment]
Count of times OpenRCT2 crashed...

**Comment by Margen67** [comment]
or desynced

**Comment by janisozaur** [comment]
I was about to mentinon that as well. 👍
