### ISSUE TITLE
No Block Brakes MAC

### ISSUE THREAD

**Issue by Shaneyb118** [OpenRCT2/OpenRCT2#4321]
MAC
latest 0.0.0.5

no block brakes in coaster editor all coasters 

no screen shot needed as its a simple issue its on all maps and doesn't apply to pre built coasters but extra block brakes cannot be added

**Comment by Gymnasiast** [comment]
You removed the issue template. It isn't there for nothing. Please put it back and fill in the appropriate fields.

**Comment by duncanspumpkin** [comment]
Also just checked and block breaks are working fine.
