### ISSUE TITLE
No Option To Add Block brakes on MAC

### ISSUE THREAD

**Issue by Shaneyb118** [OpenRCT2/OpenRCT2#4322]
[Fill in the 
**OS:** MAC
**Version:** 0.0.0.5
**Commit/Build:** unknown don't know how to find it

[Explanation of the issue...]
- [ ] Reproducible in RCT2 (vanilla)? Yes the original rct2 and all the franchise has the option for a block brake on a coaster
- [ ] Multiplayer? Not known

**Steps to reproduce:**
1. [step 1] build a custom coaster
2. [step 2] try and add a special item, no option for a block brake

**Dump file**
N/A

**Screenshots / Video:**
Not needed all players know what a block brake is ? 

**Save game:**
I'm now typing this off my phone die to my original post with all the information being on there just without headers being unacceptable, this can be added tomorrow if it's really that important

**Comment by duncanspumpkin** [comment]
![worksfine](https://cloud.githubusercontent.com/assets/1277401/17869944/5381a870-68ad-11e6-8252-e3dfc5030527.PNG)
Can not reproduce.

**Comment by Shaneyb118** [comment]
It's not possible on senario on Mac

**Comment by Shaneyb118** [comment]
Will add a photo tomorrow when a custom coaster is built in a senario there is no option for block brakes on Mac

**Comment by Gymnasiast** [comment]
The commit number is in the title screen, on the lower. It consists of seven characters: an example is `7711ab8`

**Comment by YJSoft** [comment]
<img width="976" alt="2016-08-23 10 46 12" src="https://cloud.githubusercontent.com/assets/5893514/17877539/ef018844-691e-11e6-947f-6e9760cbf6cf.png">
Cannot reproduce on OSX(Mac).
build was 8ffe0fb.

please provide more information about your issue, not block brakes. Maybe taking screenshot of build window would be helpful.

**Comment by Shaneyb118** [comment]
Commit or build; 35ae769

**Comment by jensj12** [comment]
That's only 2 days old (assuming the last 9 is a 0), good enough. Can you post a screenshot showing that you can't add block brakes?

**Comment by joshbgosh10592** [comment]
Maybe it's a specific type of coaster? I just build a coaster with block brakes on my Mac build.
