### ISSUE TITLE
Automatic placing of staff always happens at park entrance

### ISSUE THREAD

**Issue by ThePsionic** [OpenRCT2/OpenRCT2#4324]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 8ffe0fb

In previous commits, staff that were placed with the auto-place feature on would be put on a random path in the park. I don't know since when, but all staff is now placed at the park entrance. Happens in any park, under any scenario.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Turn on the auto-place staff option
2. Place staff
3. ???
4. Profit

**Comment by fromthere** [comment]
Auto place position is based guest's position. so if there's no one in park, auto placing staff will result placing them to park entrance.

**Comment by Gymnasiast** [comment]
Auto place stuff deliberately puts a staff member next to a guest in order to avoid placing them on inaccessible paths. If there are no guests, the staff member will be placed in front of the entrance.

@ThePsionic Could you test if it happens when there are guests in your park?

**Comment by ThePsionic** [comment]
@Gymnasiast Yeah, with guests it works like expected. I didn't know how the automatic staff placement worked exactly, but now that it's cleared up it's a non-issue really :+1:

**Comment by Patrik356b** [comment]
@Gymnasiast I'd suggest adding the label help or information

**Comment by IntelOrca** [comment]
@ThePsionic this is somewhat a technical restriction, we don't know whether a path is accessible so park entrance or random guest is safest option. When we have a new path finding engine we might be able to improve the logic of this.

**Comment by Gymnasiast** [comment]
I doubt that is really needed to be honest, the current system works and is intelligent enough. If the park is empty it won't really matter that the staff are all placed at the entrance initially.
