### ISSUE TITLE
[Multiplayer] Severe desync/unintended land alteration with mountain tool use after update

### ISSUE THREAD

**Issue by ArcticX9** [OpenRCT2/OpenRCT2#4331]
Hello,
I was playing on a server last night following the update of the mountain tool. Whenever we were terraforming, things would not appear as intended after disconnecting and rejoining the server.

OS: Windows 10
Version: 0.0.5 build 1397939
Commit: 13979397debc46823434ba721dc1ffd62302c66b

Downgrading seems to resolve the issue.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. On multiplayer, terraform with the new mountain tool.
2. Leave and rejoin the server; land will not be positioned as it was when the server was left.

Screenshots / Video:
Didn't think to take a before screenshot; but here is what it looked like upon rejoining:

http://i.imgur.com/v0aDpwo.png

(Land was not raised as much as pictured, strange ridges noted)

http://i.imgur.com/HRq0vlQ.png

(One can see where the waterline used to be, and approximately how the beach was before rejoining the server. After rejoining, the land appeared to be lowered extensively.)

http://i.imgur.com/S6QyaYz.png

(The line along the shore in this image shows approximately where land was raised before leaving, with the area in front of the wooden roller coaster having been flat and above water level.)

**Comment by duncanspumpkin** [comment]
Issue caused by not incrementing the network version on modification of the game command.
