### ISSUE TITLE
Some SV4 files fail to load

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#4334]
**OS:** Ubuntu 16.04
**Version:** 0.0.5
**Commit/Build:** 65beeee

Some SV4 files fail to load with the game saying 'File contains invalid data' or outright crashing.
Output to stderr just before the crash or notification is as follows:

```
WARNING[/home/michael/Dropbox/Aptana Studio 3 Workspace/OpenRCT2-4/src/util/util.c:295 (safe_strcpy)]: Truncating string "WALLRH32" to 9 bytes.
ERROR[/home/michael/Dropbox/Aptana Studio 3 Workspace/OpenRCT2-4/src/rct1/S4Importer.cpp:757 (LoadObjects)]: Failed to load SCGURBAN.
```

Two parks that exhibit this behaviour:
- [Luna Park](http://www.nedesigns.com/park/3547/luna-park/)
- [Blackpool Pleasure Beach](https://github.com/OpenRCT2/OpenRCT2/files/440164/Blackpool.Pleasure.Beach.SV4.zip)

**Comment by Gymnasiast** [comment]
Further testing shows that the Blackpool Pleasure Beach did not cause a crash before this #4024 (https://github.com/OpenRCT2/OpenRCT2/commit/dca816cfd394f7fff85f380370e18fce9435979a)

**Comment by Gymnasiast** [comment]
It crashes because it attempt to load a rideEntry with the value `0xffffffff`. Putting a bit of code in to skip such ride entries will prevent a crash, but cause a broken state:

https://files.gitter.im/Gymnasiast/hSjn/thumb/Blackpool-Pleasure-Beach-2016-08-29-21-17-24.png

**Comment by duncanspumpkin** [comment]
Issue cause by multiple object entries of the same type `"PTCT1   "`. Anything that is loaded after this (and this is the 8th object loaded) will be referencing the wrong ride type. Will be a pain to fix.

**Comment by IntelOrca** [comment]
Do you mean that we have two RCT1 ride / vehicle types that map to the same RCT2 object?

**Comment by duncanspumpkin** [comment]
Yeah for some reason this map has multiple `"PTCT1"` entries.

**Comment by Gymnasiast** [comment]
`PTCT1` is the Wooden Roller Coaster train. But RCT1 also has a reversed WRC train, for which RCT2 has no direct equivalent, so this is changed to a regular one when importing. The same applies to the reversed Steel RC train, and also to some trains for which no direct equivalent exists.

The map is in the code and also [on this wiki page](https://github.com/OpenRCT2/OpenRCT2/wiki/RCT1-ride-and-vehicle-types-and-their-RCT2-equivalents#vehicles).

**Comment by IntelOrca** [comment]
I will look at this tonight, the issue is that rides are referencing the wrong ride entry, not that there are multiple ride entries that are the same object.

**Comment by IntelOrca** [comment]
When loading Luna Park, it runs out of map animation slots. It creates one for every single fence object, which looks like same behaviour as placing them in normal game... I am not entirely sure why or whether this is correct.

**Comment by Gymnasiast** [comment]
It does load correctly in RCT1, though.
