### ISSUE TITLE
Tile inspector window not wide enough

### ISSUE THREAD

**Issue by GForceNE** [OpenRCT2/OpenRCT2#4338]
**OS:** [e.g. Windows 10]
**Version:** [0.0.5]
**Commit/Build:** [All]

Tile inspector window not wide enough to display whole object title, not able to read object height or clearance height.

- [Yes] Multiplayer?

**Steps to reproduce:**
1. [Open Tile inspector with]

**Screenshots / Video:**
![bizarro 2016-08-27 17-45-04](https://cloud.githubusercontent.com/assets/18511011/18030274/22ae0070-6c7e-11e6-820b-4ce1c53cfcbf.png)

**Comment by Gymnasiast** [comment]
@Broxzier Something you could incorporate in your PR?

**Comment by Broxzier** [comment]
@Gymnasiast: I thought strings should be clamped in the live version already, will look at it tonight.

**Comment by IntelOrca** [comment]
Is this fixed now?

**Comment by Broxzier** [comment]
@IntelOrca: Yes: https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/windows/tile_inspector.c#L2138-L2139
