### ISSUE TITLE
x64: Supports for small and large scenery do not get rendered

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#4340]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 8cf7e87b5c88732608b7203567845320ec5270ee (x64)

Supports for small and large scenery do not get rendered in 64-bit builds.

**Screenshot:**
Left: x64
Right: Win32
![image](https://cloud.githubusercontent.com/assets/1482259/18030499/aa4b155a-6caf-11e6-9177-9d22585ff310.png)

**Comment by duncanspumpkin** [comment]
Won't that be because not all support draw functions are implemented

**Comment by IntelOrca** [comment]
Aren't they? I thought they were.

**Comment by Gymnasiast** [comment]
Path supports don't get rendered either.

**Comment by janisozaur** [comment]
Shall it be closed then?

**Comment by Gymnasiast** [comment]
It needs to be documented in https://github.com/OpenRCT2/OpenRCT2/issues/3365, I'd say.

**Comment by duncanspumpkin** [comment]
It would not be hard to implement the remaining functions. They are all based on functions we already have but with some modifications

**Comment by IntelOrca** [comment]
It will happen at some point, we don't need to remind ourselves.
