### ISSUE TITLE
x64 version crashes on ride window, station view

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#4342]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 831936d x64

**Steps to reproduce:**
1. Click on the entrance or exit of a random ride (just clicking on the ride itself does not trigger this)
2. The game crashes: the usual "openrct2_x64.exe has stopped working" The game does not produce a dump file when this happens.

This happens only with the x64 bit version.

**Comment by IntelOrca** [comment]
Clicking on the entrance automatically sets the ride window to show the station view which is the actual bug, can be produced by clicking ride then setting station view.

Thanks for pointing out that there is no dump file, I forgot to enable that for both 32-bit and 64-bit.
