### ISSUE TITLE
WARNING[src\ride\ride.c:6307 (game_command_demolish_ride)]: Invalid game command for ride

### ISSUE THREAD

**Issue by dcharkes** [OpenRCT2/OpenRCT2#4343]
**OS:** Windows 10
**Version:** 0.0.5.0-beta
**Commit:** 17b69d2

When I try to save a wooden rollercoaster track I sometimes get this error message:

`WARNING[src\ride\ride.c:6307 (game_command_demolish_ride)]: Invalid game command for ride 22`

The file is saved, but there is no picture in the ride preview screen.
Also, when you build the track the money is deducted but no track is built.

**Steps to reproduce:**
1. Open save game
2. Try to save the "Cannot save this Rollercoaster" rollercoaster

**Save game + erroneous rollercoaster:**
[Cannot Save this Rollercoaster.zip](https://github.com/OpenRCT2/OpenRCT2/files/441224/Cannot.Save.this.Rollercoaster.zip)

**Comment by Gymnasiast** [comment]
Please provide the commit number. It's not in the issue template for nothing. You can find it in the title screen.

**Comment by dcharkes** [comment]
Sorry, here is the commit number.

**Commit:** 17b69d2

Note that the error can also occur with other types of rollercoasters.

**Comment by Nubbie** [comment]
Commit: 03299b9
Could save it multiple times, with/without scenery, reloading the save, re-test it etc
Presume the glitch is fixed as the issue is old

**Comment by Gymnasiast** [comment]
Seems likely. The code has been converted to GameActions in the meantime as well.

Considering this solved. Please let us know if it isn't.
