### ISSUE TITLE
Crash upon opening rollercoaster tab

### ISSUE THREAD

**Issue by Tobber98** [OpenRCT2/OpenRCT2#4348]
**OS:** macOS (x86)
**Version:** 0.0.5 develop
**Commit/Build:** 4ee9c2c

If you open up de building window and click on the Rollercoaster Tab, the game crashes.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open save
2. Go to rollercoaster tab in build window

**Save game:**
[Park Crash.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/441980/Park.Crash.sv6.zip)

**Comment by Gymnasiast** [comment]
Only in this park or with every park you try?

**Comment by Tobber98** [comment]
Only in this park. It doesn't happen in other saved games, not even from the same scenario. It also doesn't happen when I start a new scenario.

**Comment by Tobber98** [comment]
It only happens when you have "Select ride by track type (like in RCT1)" on.
