### ISSUE TITLE
x64: Crash when placing roller coaster track designs

### ISSUE THREAD

**Issue by UnsaltedCashews** [OpenRCT2/OpenRCT2#4349]
**OS:**  Windows 10
**Version:** 0.05
**Commit/Build:** 8cb212d

- [ ] Reproducible in RCT2 (vanilla)? No
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open OpenRCT2, I found that none of the Roller Coasters rendered except for the Junior RC
2. Attempting to place a Roller Coaster results in a crash

**Dump file**
[Dump File.zip](https://github.com/OpenRCT2/OpenRCT2/files/442623/Dump.File.zip)

**Screenshots / Video:**
[8125a6f6-1958-4d26-a121-381dde9bafe1.zip](https://github.com/OpenRCT2/OpenRCT2/files/442627/8125a6f6-1958-4d26-a121-381dde9bafe1.zip)

![funtopia 2016-08-29 08-40-59](https://cloud.githubusercontent.com/assets/20407301/18055317/948edb3c-6dc4-11e6-9176-6cf7e9b9b078.png)
![six flags magic mountain 2016-08-29 08-41-08](https://cloud.githubusercontent.com/assets/20407301/18055318/94a74104-6dc4-11e6-87b8-ba60f38503e5.png)
![six flags magic mountain 2016-08-29 08-41-12](https://cloud.githubusercontent.com/assets/20407301/18055319/94a973b6-6dc4-11e6-8eb3-513380738654.png)
![six flags magic mountain 2016-08-29 08-41-27](https://cloud.githubusercontent.com/assets/20407301/18055320/94ae54da-6dc4-11e6-8bb8-25f496b97eab.png)
![six flags magic mountain 2016-08-29 08-41-35](https://cloud.githubusercontent.com/assets/20407301/18055321/94b1d6a0-6dc4-11e6-9416-39214928c925.png)

**Save game:**
[8125a6f6-1958-4d26-a121-381dde9bafe1.zip](https://github.com/OpenRCT2/OpenRCT2/files/442630/8125a6f6-1958-4d26-a121-381dde9bafe1.zip)

**Comment by jensj12** [comment]
Which game version are you playing? (32 or 64 bit)

**Comment by IntelOrca** [comment]
@UnsaltedCashews ride tracks are not visible in x64 as we have not yet implemented that part of the code. The crash when placing track designs is a bug though.

**Comment by UnsaltedCashews** [comment]
Ah okay, so just stick with the 32 bit builds then?

**Comment by IntelOrca** [comment]
@UnsaltedCashews up to you
