### ISSUE TITLE
Tracks not showing

### ISSUE THREAD

**Issue by mc-landin** [OpenRCT2/OpenRCT2#4352]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 66eed2b

Any version since the 0.0.5-13 version does not show any tracks for rides, except for the monorail. Issue is already present on the startup screen.

**Screenshots / Video:**
![knipsel](https://cloud.githubusercontent.com/assets/21316565/18061088/a4e011ec-6e21-11e6-805e-3caf56d067fa.PNG)

**Comment by janisozaur** [comment]
Switch to 32 bit build
