### ISSUE TITLE
Staff issues with hiring/setting roles

### ISSUE THREAD

**Issue by joshbgosh10592** [OpenRCT2/OpenRCT2#4356]
**OS:** Windows 7
**Version:** 0.0.5
**Commit/Build:** PENDING server disconnect

When hiring staff, intermittently for the server, and 100% of the time for at least one client, the staff will be hired, placed (if the auto place staff is enabled), but a window of a random guest will appear.
Might be related... when assigning a staff the role, the server receives "Invalid type of sprite 56 [or 100] for game command" message on the console.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Hire a Handyman
2. Observe Alesia F.'s guest window appear, but with the Staff properties. (Note, name might be different.

**Screenshots / Video:**
Hiring staff/random guest window:
![image](https://cloud.githubusercontent.com/assets/20283787/18094640/2f791012-6ea2-11e6-8e16-f5a14990f5a2.png)

Hire/patrol (might be both?):
![image](https://cloud.githubusercontent.com/assets/20283787/18094105/4c2cad56-6ea0-11e6-8714-0ec18b8ff04b.png)

Patrol:
![image](https://cloud.githubusercontent.com/assets/20283787/18094116/60484c3c-6ea0-11e6-9d6f-d869b825960a.png)

**Save game:**
[NoExpansions 8-30.zip](https://github.com/OpenRCT2/OpenRCT2/files/445237/NoExpansions.8-30.zip)

**Comment by duncanspumpkin** [comment]
Placing staff/peeps in multiplayer is currently broken.
