### ISSUE TITLE
Additional cheats

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#436]
There fare a few suggestions I have for cheats:
*Make all rides new and with 100% reliability
*Instantly repair all broken rides
*Mow All Grass
*Clean All Paths
*Repair all vandalism
*Water All Gardens
*Make All Guests have maximum happiness and energy
*Make All Guests have minimum/empty nausea, hunger, thirst, and bathroom.
*Give All Guests maps
*Auto-Purchase all land/construction rights for sale
*Max Park Rating
*Force park to be open (In the event of a "Don't let the park rating go below 700 at any time" objective failing)

**Comment by RollingStar** [comment]
Unlock all of a scenario's available research would be very helpful for testing. Sometimes it's hard to find an original (non-custom) scenario that has one or multiple rides available right from the start. I assume at least one trainer already has such a feature.
