### ISSUE TITLE
Loading track presets window crashes the game

### ISSUE THREAD

**Issue by addoyle** [OpenRCT2/OpenRCT2#4367]
OS: Mac OSX El Capitan
Version: 0.0.5.0
Commit/Build: 63ba739

Any time you try to create a ride that has preset track designs (most roller coasters, go karts, hedge maze, etc.), the game instantly crashes.

- [ ] Reproducible in RCT2 (vanilla): No
- [ ] Multiplayer: No

Steps to reproduce:
1. Using a Mac, start a new campaign
2. Go to build menu, choose any coaster or tracked ride (e.g. Go Karts) that has preset track designs
3. Game crashes

**Comment by janisozaur** [comment]
Can you provide stack trace?

**Comment by IntelOrca** [comment]
Is this 64-bit?

**Comment by addoyle** [comment]
IntelOrca - I'm using Mac OS X x86 (the only option for Mac)

**Comment by addoyle** [comment]
@janisozaur Attached is the dump file, although I'm not seeing a stack trace. Are there logs somewhere on the file system I could be looking
[openrct2-error-dump.txt](https://github.com/OpenRCT2/OpenRCT2/files/452101/openrct2-error-dump.txt)
 for?

**Comment by janisozaur** [comment]
@addoyle the file you provided contain stack trace. Below is the failed assertion:

```
Assertion failed: (bitsOffset < bitsSize), function SetDPI, file /Users/travis/build/OpenRCT2/OpenRCT2/src/drawing/engines/opengl/OpenGLDrawingEngine.cpp, line 974.

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x99f41572 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x91bf0654 pthread_kill + 101
2   libsystem_c.dylib             	0x93fc6c38 abort + 156
3   libsystem_c.dylib             	0x93f8eff9 __assert_rtn + 393
4   website.openrct2.OpenRCT2     	0x020efa30 OpenGLDrawingContext::SetDPI(rct_drawpixelinfo*) + 130
5   website.openrct2.OpenRCT2     	0x020f0a60 OpenGLDrawingEngine::GetDrawingContext(rct_drawpixelinfo*) + 22
6   website.openrct2.OpenRCT2     	0x021015d9 gfx_clear + 36
7   website.openrct2.OpenRCT2     	0x020aea0f viewport_paint + 537
8   website.openrct2.OpenRCT2     	0x02060d89 track_design_draw_preview + 1289
9   website.openrct2.OpenRCT2     	0x0201d43b window_track_list_paint + 288
10  website.openrct2.OpenRCT2     	0x0208f3f7 window_draw + 616
11  website.openrct2.OpenRCT2     	0x020d741c window_draw_all + 215
12  website.openrct2.OpenRCT2     	0x020f08ac OpenGLDrawingEngine::Draw() + 116
13  website.openrct2.OpenRCT2     	0x02101439 drawing_engine_draw + 26
14  website.openrct2.OpenRCT2     	0x020555c5 openrct2_launch + 866
15  website.openrct2.OpenRCT2     	0x0204a888 main + 41
16  website.openrct2.OpenRCT2     	0x02001785 start + 53
```

@addoyle right now OpenGL engine is still experimental, please switch to software rendering. Can you provide some more information regarding OpenGL on your system?

**Comment by addoyle** [comment]
Yes, OpenGL was enabled. When I switch it back to software rendering, the game operates as normal.

**Comment by duncanspumpkin** [comment]
OpenGL at present can't handle the drawing of the track previews.
