### ISSUE TITLE
Senario Creator Park Entrance Placement Ghost Glitch

### ISSUE THREAD

**Issue by aws0mizer** [OpenRCT2/OpenRCT2#4374]
![asd](https://cloud.githubusercontent.com/assets/20025302/18226418/38be9772-71d7-11e6-8b39-74fe54c71d2a.PNG)

Past few maps I have created have had this same issue. (Partly my fault for not disabling Zero Clearance outside Scenario Creator) But when placing more than 1 park entrance, it will become glitched and ghosts will remain wherever you placed the entrances. Upon reloading the scenario the ghost entrances are gone as if the entrance is already there when they are not, but when trying to place another park entrance it will tell you that no more can be built. Because of this, I only have 1 Park Entrance I was able to build, it will not allow me to build the other three. 

This problem could be avoided if the cheat menu were available in Scenario Creator so that you could enable/disable Zero Clearance cheat.

**Comment by aws0mizer** [comment]
![dvb](https://cloud.githubusercontent.com/assets/20025302/18227458/fbce7d20-71f2-11e6-8e9c-5325fa692011.PNG)

Adding to this, glitch also causes issues when I try to continue on to finish the map. Does not let me move on to the final steps. I'm not missing anything. I make maps all the time, It just does this when the entrances glitch this way.

**Comment by Margen67** [comment]
Maybe you could try removing it with the tile inspector.

**Comment by aws0mizer** [comment]
Already tried, tiles show they are clear with nothing built on them.

**Comment by Margen67** [comment]
Odd. I tried making a glitched park entrance ghost and I could remove it with the tile inspector.

Anyway, I think another solution would be to do cheats_reset() in the scenario editor.

For now comment out [this line](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/windows/top_toolbar.c#L670)

**Comment by Nubbie** [comment]
Same as #4374 ???
No idea if a 'cheats reset' would be good enough - better to fix the problem itself
