### ISSUE TITLE
x64: Crash when clicking audio device dropdown

### ISSUE THREAD

**Issue by birthdaybrian** [OpenRCT2/OpenRCT2#4379]
**OS: Windows 7 Home Premium SP1 x64**
**Version: 0.0.5-13**
**Commit/Build: bf16890**

Hey everyone. When I play OpenRCT2, I get no sound at all and when I tried to go into the settings for audio, the game crashes. My sound card is the Creative Sound Blaster Z and has the latest drivers installed.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

1. Launch OpenRCT2 with the latest version
2. Go into Options and go to the music settings
3. See if you are getting the same issue as I am

**Comment by janisozaur** [comment]
Are you using 64 bit version of openrct2?

**Comment by IntelOrca** [comment]
Please upload a crash dump

**Comment by birthdaybrian** [comment]
[dumpcrash.zip](https://github.com/OpenRCT2/OpenRCT2/files/454119/dumpcrash.zip)

**Comment by birthdaybrian** [comment]
@janisozaur Yes I am using the 64 bit version of OpenRCT2.

**Comment by IntelOrca** [comment]
I can reproduce, looks like its an issue with x64 only when selecting the audio dropdown.

**Comment by janisozaur** [comment]
@IntelOrca I mentioned this earlier to you, on gitter and in here: https://github.com/OpenRCT2/OpenRCT2/issues/4198#issuecomment-238106776
