### ISSUE TITLE
Invisible tracks

### ISSUE THREAD

**Issue by stefvanschie** [OpenRCT2/OpenRCT2#4384]
**OS:** Windows 7 Professional
**Version:** 0.0.5
**Commit/Build:** 426e106

I just downloaded OpenRCT2 to play with it. I installed it with the installer and ran the program. When I entered the game I saw that the tracks on the intro screens were missing. That isn't a huge deal, so I started to play on a server as well as a normal single player file. I noticed that all tracks were invisible. 

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer? I had issues with both

**Steps to reproduce:**
1. Install the game
2. Run the game
3. All the tracks are invisble

**Screenshots / Video:**
https://drive.google.com/open?id=0B0unLUNEgZjPVlJ0NjNpU2ZEcTA

**Comment by Gymnasiast** [comment]
You downloaded the 64-bit version, which is not intended for normal playing. You need to download the 32-bit version.

**Comment by IntelOrca** [comment]
> I noticed that all tracks were invisible.

Not all, You can see Junior RC, river rapids and river rafts.

**Comment by fromthere** [comment]
<img width="946" alt="2016-09-08 11 02 33" src="https://cloud.githubusercontent.com/assets/10338434/18334631/ca6ce8b0-75b3-11e6-8014-fac83b446695.png">
How about add explanation about 64bit builds at download page?

**Comment by PFCKrutonium** [comment]
I mean, it does say right in the screenshot you took, "Experimental and should be used for debugging only."

**Comment by Gymnasiast** [comment]
Yes, but this isn't the first report we got. It would be better to move them into their own section and mark them in a more obvious way. People who read carefully will see it, but unfortunately many people don't do so.

**Comment by Patrik356b** [comment]
I'd suggest just split this to x86 and x64 sections. This should make it
more obvious.

**Comment by marijnvdwerf** [comment]
Or just don't list them at all.

**Comment by IntelOrca** [comment]
@marijnvdwerf but then they wouldn't be tested

**Comment by marijnvdwerf** [comment]
@IntelOrca Why would the average user want to test an incomplete build though? 64-bit would be fine for hosting servers, but otherwise...
