### ISSUE TITLE
Wrong numbers in guests thoughts summary

### ISSUE THREAD

**Issue by Fernouille** [OpenRCT2/OpenRCT2#4385]
**OS:** Windows 7
**Version:** 0.0.5
**Commit/Build:** 163e314

The thoughts summary window shows overestimated numbers of guests having these thoughts (see screenshots below). By clicking on a thought I get the proper number and list of guests (e.g. 23 instead of 75 shown prior). This happened to me with every save so far. On the other hand, the actions summary seems to show correct numbers.
My wild guess is that the summary lists all the thoughts one guest had but I don't know how to verify this. It's very confusing nonetheless because I can't tell how trustworthy the summary is and I think it should only count the one most recent, relevant thought.
Having no idea where this come from, I've only tried to change the game language to english (I use french) with no difference.

In RCT2 (vanilla) the summary shows the correct numbers of guests thoughts and there is no discrepancy when I click on a specific thought (tested with the same save).

**Screenshots / Video:**
Example 1:
![thoughts summary issue 1](https://cloud.githubusercontent.com/assets/22076998/18352202/b9b5738c-75dd-11e6-842d-df13de28ea5e.png)

Example 2:
![thoughts summary issue 2](https://cloud.githubusercontent.com/assets/22076998/18352209/c1ec511a-75dd-11e6-9694-7db2f29d9435.png)

OpenRCT2 vs. RCT2:
![thoughts summary issue 3](https://cloud.githubusercontent.com/assets/22076998/18352213/c5659b1c-75dd-11e6-94bb-6a37d8d2bdca.png)

Hope I made myself clear enough and please excuse my broken english.

**Comment by IntelOrca** [comment]
Can you upload the saved game you used to test this?

**Comment by Fernouille** [comment]
Sure, here you go : https://www.dropbox.com/s/chwijm9f7ohn3hn/Course%20d%27hydravions3.sv6?dl=1

**Comment by Wirlie** [comment]
Additionally I've noticed that the thoughts groups some times show the actions of the guests, but, I'm not sure if this is related to this bug or if I need to open another issue.

![montanasauro 2016-09-08 10-38-18](https://cloud.githubusercontent.com/assets/7508197/18356075/f8c5501a-75b0-11e6-9d95-03f0eeb2b081.png)
