### ISSUE TITLE
Wrong animation - Merry Go Round

### ISSUE THREAD

**Issue by Wirlie** [OpenRCT2/OpenRCT2#4386]
**OS:** Windows 10
**Version:** 0.0.5 (32 bits)
**Commit/Build:** latest build (163e314)

Merry Go Round have a incorrect animation of the breakdown "Control failure".

- [ ] ~~Reproducible in RCT2 (vanilla)?~~
- [ ] Multiplayer?

**Steps to reproduce:**
1. Build and open a Merry Go Round.
2. Force a "control failure" breakdown, and see the problem.

**Screenshots / Video:**
https://vid.me/pIGT

**Comment by IntelOrca** [comment]
It also does not go back to the correct animation when a mechanic fixes it.
