### ISSUE TITLE
Park does not load in 64 bit build

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#4397]
**OS:** Linux
**Commit/Build:** f81c394

Park [mega-micro](https://github.com/OpenRCT2/OpenRCT2/files/111026/mega-micro.sv6.gz.txt) does not load in 64 bit build, while it works just fine in 32 bit one.

An error can be seen in x86-64 bit build, which is not present in x86 build:
```
[11      ] Object not found.
```

**Comment by IntelOrca** [comment]
Works fine for me for both x86 and x64.

**Comment by janisozaur** [comment]
Hmm, indeed, after another compilation and removing `11.DAT` from my object cache, it appears to work just fine.
