### ISSUE TITLE
"Dead code reached" when zoomed out with OGL renderer on Avilance Casual building park

### ISSUE THREAD

**Issue by Margen67** [OpenRCT2/OpenRCT2#4406]
**OS:** [Windows 10 x64]
**Version:** [0.0.5 32 bit]
**Commit/Build:** [2f8b307]

[The game only crashes if Abort is pressed.
Getting the error can be random.]

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Load map
2. Zoom out with software renderer(?)
3. Switch to OpenGL renderer

**Dump file**
[https://dl.dropboxusercontent.com/u/69103554/bb40aa22-4bc0-40f2-98e5-2c8f71fa4fd2(2f8b307).zip]

When trying to save manually with OGL renderer:
https://dl.dropboxusercontent.com/u/69103554/95341721-e2d1-42e7-8687-c126e02ca591(2f8b307).dmp.zip

**Screenshots / Video:**
[http://i.imgur.com/IzZMzwQ.png]

**Save game:**
[https://dl.dropboxusercontent.com/u/69103554/95341721-e2d1-42e7-8687-c126e02ca591.sv6.zip]
The game produces a blank save upon crashing.
If I try to save manually the game crashes with the OGL renderer.
After this crash however a save was made alongside the dump.
The saves made manually are blank.

**Comment by IntelOrca** [comment]
@duncanspumpkin So this is probably happening because some variable isn't initialised on OpenGL. I don't see otherwise why OpenGL would need to run this dead code but not software.

**Comment by Gymnasiast** [comment]
Does this still apply to the current state of the OpenGL renderer?

**Comment by duncanspumpkin** [comment]
This will no longer happen as the dead code has been removed. Opengl renderer is a bit broken at present
