### ISSUE TITLE
Ride construction window track preview broken

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#4407]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 64df46ba16d063ea96b2c9c35fa3671107ced51f

Some rides do now show a preview of the track piece in the ride construction window.

Wooden roller coaster doesn't work, Junior does, so probably some integration bug.

**Steps to reproduce:**
1. Open Electric Fields.
2. Build a wooden roller coaster.

**Screenshots / Video:**
![image](https://cloud.githubusercontent.com/assets/1482259/18414340/facc43f2-77bb-11e6-8b99-750c72bd2c54.png)

**Comment by Margen67** [comment]
Loops don't render either.
