### ISSUE TITLE
unable to get into servers

### ISSUE THREAD

**Issue by destroyerofcomedy** [OpenRCT2/OpenRCT2#4408]
OS- Windows 8
Version- v.0.0.5
Build- 4066009

Hi there. I seem to be having a problem getting into servers on multiplayer mode. Well, I can only get into one. But when I try to enter the rest I get this message "Unable to connect to server. Incorrect software version (Server using 0.0.5-13)" and I'm using 0.0.5-12, and I can't seem to update the software. Is there anyway that I can do this? Or do I have to simply get the latest version?

**Comment by YJSoft** [comment]
You should update your version. There's no other way.
