### ISSUE TITLE
Go Karts are all in the same colour

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#4415]
**Commit/Build:** b0a8fb0a7c771d35e51e9f422c50758beabe4162 

When you build a Go Karts track in vanilla, the karts will all have a different colour. In OpenRCT2, they will all have the same colour.

**Comment by duncanspumpkin** [comment]
I cant reproduce this

**Comment by Patrik356b** [comment]
More information?

**Comment by duncanspumpkin** [comment]
Caused by #4024. I'll have a fix up shortly.
