### ISSUE TITLE
Just fyi: sprites of steep side-friction track exists within the game

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#4418]
Found the sprites for steep side-friction track in RCT1. Including the transitions. I can't recall seeing them used in the game, anywhere. Could be useful later on?

edit: also upwards/downwards turns and steep track with chain lift for wooden coasters

edit2: similarly, more lifthill pieces for the stand-up coaster

**Comment by Gymnasiast** [comment]
Could you provide the addresses?

**Comment by Liampie** [comment]
I'm using the RCT Graphics Inspector so I can give you the index numbers of the sprites.

Side friction is 59713 onwards.
Wooden coaster starts at 64756
Stand-up starts at 66959

**Comment by Gymnasiast** [comment]
![image](https://files.gitter.im/OpenRCT2/OpenRCT2/non-dev/ooNW/59756.png)

**Comment by Gymnasiast** [comment]
![forest frontiers 2018-01-23 21-02-12](https://user-images.githubusercontent.com/1478678/35297902-b8a621d8-0080-11e8-9bec-097f11a79018.png)

Still need to do the diagonal ones.

**Comment by Patrik356b** [comment]
Very cool.

**Comment by Gymnasiast** [comment]
The steep slopes on the Side-Friction have now been implemented. Keeping this open for the other sprites.

**Comment by Gymnasiast** [comment]
Having taken a look at the other sprites, they don’t have the same style of chain lift, it being a lighter grey that doesn’t move. As such, I think we are better off creating our own so they can match the others.

**Comment by karst** [comment]
that shouldn't be too difficult to swap around in photoshop then.

**Comment by Gymnasiast** [comment]
You’re up for another month-long PR agonising over pixels and boundboxes? xD

**Comment by karst** [comment]
well since I now have the correct setup it should be alot easier to do, especially if the sprites already exist just with the wrong colors.

**Comment by Gymnasiast** [comment]
There might be some sprite fiddling involved too. Though hopefully no boundboxes, considering all the pieces will just be modified versions of existing track pieces.

I guess it’s probably best to create an issue per coaster type. Do you intend to do both the Wooden RC and Stand-Up RC, or just one of the two?

**Comment by karst** [comment]
It depends on how much work it'd take really, I'd prefer to do as many as possible
