### ISSUE TITLE
Save overwrite multiplayer

### ISSUE THREAD

**Issue by Tobber98** [OpenRCT2/OpenRCT2#4422]
**OS:** Mac OS X
**Version:** 0.0.5
**Commit/Build:** e.g. 73b7f3c

If you go to the menu from a saved game, open up a server and press save (not save as...), the server map overwrites your earlier played saved game. Learned this the hard way by losing over 20 years of in-game gameplay.

- [ ] Reproducible in RCT2 (vanilla)?
- [x ] Multiplayer?

**Steps to reproduce:**
1. Load a saved game
2. Go to main menu and open a multiplayer map
3. Press save
4. Try to load the save file you used for the first step

**Comment by IntelOrca** [comment]
> Go to main menu and open a multiplayer map

What do you mean by open a multiplayer map? Are you starting a server or joining one from the list?

**Comment by Tobber98** [comment]
Just joining one from the list.
