### ISSUE TITLE
MSVC builds kill host performance

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#4427]
**OS:** Linux + wine 1.9.18, Windows 7 Home Premium
**Commit/Build:** 0ed526b

MSVC builds configured in following way:
```ini
[general]
edge_scrolling = true
fullscreen_mode = 2
fullscreen_height = 2160
fullscreen_width = 3840
landscape_smoothing = true
language = en-GB
window_height = 1548
window_width = 2211
drawing_engine = SOFTWARE_HWD
uncap_fps = true
minimize_fullscreen_focus_loss = true
steam_overlay_pause = true
window_scale = 1.000
scale_quality = 1
use_nn_at_integer_scales = false
show_fps = true
trap_cursor = false
```
will kill performance of host to the point where you can only kill openrct2.

Linux or MinGW builds do not exhibit such behaviour.

Dlls tested:
* [MinGW](https://github.com/OpenRCT2/OpenRCT2/files/470591/openrct2-0ed526b-mingw.dll.zip)
* [MSVC](https://github.com/OpenRCT2/OpenRCT2/files/470594/openrct2-0ed526b-msvc.dll.zip)

**Comment by IntelOrca** [comment]
Fullscreen width and height do not make a difference when the mode is borderless window / fullscreen. What was the OP's original resolution?

I can't reproduce myself.

**Comment by janisozaur** [comment]
OP's:

> 
Screen mode: Fullscreen Borderless
Display Res: 1280x800
Window Scale: 1.00
Drawing Eng: Software+ Hardware Display
Scaling Quality: Nearest Neighbor
Unchecked: NN Scaling
Checked: Pause game
Checked: Uncap FPS
Checked: Show FPS
Checked: Minimize fullscreen

**Comment by IntelOrca** [comment]
I would say its more likely environment issue rather than compiler or OS...

**Comment by janisozaur** [comment]
May be an SDL bug

**Comment by LRFLEW** [comment]
```
drawing_engine = SOFTWARE_HWD
uncap_fps = true
```

This means that it's using "Hardware Display" and Uncapped FPS, right? This almost sounds to me like it could be an issue with the main thread not being preempted correctly. Perhaps adding a thread yield call would help (I'm not sure what the WinThreads call is, but in C++11, it would be `std::this_thread::yield()`)

**Comment by PFCKrutonium** [comment]
I just tested it (Can someone explain how to build it on Windows properly, now that the Powershell scripts don't work?)  and With or Without these settings, I got a solid 60FPS, which is actually better than other compilers.

**Comment by IntelOrca** [comment]
I can't reproduce
