### ISSUE TITLE
Assertion hit in gfx_draw_sprite_get_palette

### ISSUE THREAD

**Issue by spinba11** [OpenRCT2/OpenRCT2#4431]
**OS:** Win 10
**Version:** 0.0.5.0
**Commit/Build:** 0d982f0

After I start the game, load a save and scroll the mouse wheel or move the map around for a few seconds it crashes, screenshot plus savegame is attached.

**Screenshots / Video:**
![rct crash](https://cloud.githubusercontent.com/assets/20769227/18512464/2b90419c-7a81-11e6-8098-fb7bb1015928.png)

**Save game:**

[test.TXT](https://github.com/OpenRCT2/OpenRCT2/files/472025/test.TXT)

**Comment by duncanspumpkin** [comment]
Likely caused by a corrupted file as nothing should be able to send an invalid colour.

**Comment by IntelOrca** [comment]
@spinba11 Was this a multiplayer game?

The issue is that 'Jungle racers' has 252 (an invalid colour) for its vehicles' ternary colour. Changing the ride to monster trucks fixes it, and changing back to a vehicle type with only two colours does *not* reproduce the problem.

**Comment by spinba11** [comment]
Thank, How can I change it, I can't do it in game because it keeps crashing every time a view of it pops up.

**Comment by janisozaur** [comment]
@spinba11 `rides set type <ride id> <ride type>`

**Comment by spinba11** [comment]
I'm being stupid, where do I need to type that?

**Comment by IntelOrca** [comment]
@janisozaur its vehicle that needs changing

**Comment by IntelOrca** [comment]
@janisozaur its vehicle that needs changing

**Comment by spinba11** [comment]
I forget to say, it's not a multiplayer game.

**Comment by IntelOrca** [comment]
@spinba11 do you know what you did to Jungle racers to cause this?

**Comment by spinba11** [comment]
It started a few months ago, I don't think I did anything but I could be wrong.

**Comment by janisozaur** [comment]
Even though 0d982f0 predates refactor that introduced `gfx_draw_sprite_get_palette`, that assert is still left in code and #4467 is evidence it is still being hit in 843d865f01cc2c706e

**Comment by Chaosmeister** [comment]
I'm unable to reproduce any crash/assert.

**Comment by Nubbie** [comment]
Im unable to reproduce and crash while playing this savefile
commit 03299b9
