### ISSUE TITLE
Crash when sprite limit is reached

### ISSUE THREAD

**Issue by Trippeh** [OpenRCT2/OpenRCT2#4434]
**OS:** Windows 2012 Server R2
**Version:** 0.0.5.0
**Commit/Build:** 8ce693b

Server crashes when you press 'win scenario' in cheat menu.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. run server [server1.zip](https://github.com/OpenRCT2/OpenRCT2/files/473049/server1.zip)
2. open cheat menu
3. go to park tab
4. click win scenario
5. crash:
[4e2daf4c-1f6e-481e-b2cf-d129e3df0083.zip](https://github.com/OpenRCT2/OpenRCT2/files/473047/4e2daf4c-1f6e-481e-b2cf-d129e3df0083.zip)

**Comment by IntelOrca** [comment]
Looks like you hit the sprite limit:
![image](https://cloud.githubusercontent.com/assets/1482259/18528498/30995c42-7ac1-11e6-95e6-186e0fb828fa.png)

**Comment by IntelOrca** [comment]
`create_sprite` needs to be more robust.

**Comment by Trippeh** [comment]
Thx for helping me figure that out :+1:
