### ISSUE TITLE
"Track Design not usable on ground level" notification

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#444]
While browsing through the list of available track designs for a particular ride, in the event that there's a track design that cannot be made with every part on flat ground level (since most people like to make tracks that take advantage of raised/lowered terrain, i.e. Underground), the name of any designs categorized as "Not buildable at ground level" are labeled with red text instead of the standard black, including a prompt to delete the track design instantly without having to go through the Track Design Manager.

**Comment by Superjustinbros** [comment]
Dang, I forgot that I already opened an issue about this previously. My bad (.__.¡)

@rcthelp That sounds like a good workaround.

**Comment by rcthelp** [comment]
So now this AND the duplicate have been closed?

FWIW, Dr James Hughes (Doctor J on most RCT sites, and curator of
tid.rctspace.com) wrote me some code that reads a TD4/6 track file and
outputs a True/False about whether it can be built on flat land. Perhaps he
can be contacted for help with this feature? I don't have the source, only
a Linux executable binary.

**Comment by Gymnasiast** [comment]
@rcthelp : Yes, but the OP closed this issue himself. This one should have stayed open.

**Comment by Superjustinbros** [comment]
Yeah, I figured it would be redundant to have the same feature discussed over two topics.

**Comment by Gymnasiast** [comment]
Yes, but I already closed the newer one.
