### ISSUE TITLE
Mechanics do not forget what ride they were assigned to fix when moved to new location

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#445]
Per the title, currently if a Mechanic is picked up and relocated to another part of the park after being assigned to fix a certain ride, they will forget their assigned coaster and another Mechanic elsewhere will end up receiving the call to fix the coaster/ride.

**Comment by ThomasdenH** [comment]
There were ideas of making an 'Advanced settings' panel like in OpenTTD, I would definitely like to see this feature, but it should be optional.
