### ISSUE TITLE
[Regression] Paths from get_file_path are returning strings with backslashes on macOS and Linux

### ISSUE THREAD

**Issue by LRFLEW** [OpenRCT2/OpenRCT2#4453]
**OS:** macOS and Linux
**Version:** 0.0.5
**Commit/Build:** 23b5af6 (exact commit with regression)

`get_file_path` is returning strings with backslashes on the posix platforms, with is incorrect behavior. This is because the strings in `RCT2FilePaths` all use backslashes, and the commit 23b5af6 removed the code that was performing the slash conversion in favor of `safe_strcat_path`, which doesn't have the slash conversion.

I see two solutions: Either we modify `safe_strcat_path` to change backslashes into `platform_get_path_separator()`, or we use macro guards to have `RCT2FilePaths` use forward slashes on posix systems. (that, or we have all platforms use forward slashes in `RCT2FilePaths`, because all supported versions of Windows support that 😜)

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Load the game on macOS or Linux
2. ...
3. `FATAL[.../src/rct2.c:414 (check_file_path)]: Could not find file .../rct2/Data\g1.dat`

**Comment by LRFLEW** [comment]
A third solution would be to expand upon `platform_get_path_separator()` and create a macro that expands to a string literal of the separator. Using that, we can define `RCT2FilePaths` once using the macro.

So platform.h would have something like:
```
#ifdef __WINDOWS__
#define PATH_SEPARATOR_STR "\\"
#else
#define PATH_SEPARATOR_STR "/"
#endif
```

And rct2.c would then have:
```
const char * const RCT2FilePaths[PATH_ID_END] = {
	"Data" PATH_SEPARATOR_STR "g1.dat",
	"Data" PATH_SEPARATOR_STR "plugin.dat",
	"Data" PATH_SEPARATOR_STR "css1.dat",
        ...
};
```

**Comment by Gymnasiast** [comment]
If Windows supports forward slashes changing everything to forward slashes would probably yield the cleanest code.

**Comment by janisozaur** [comment]
Yeah, what @Gymnasiast said. We should simply drop `\\` and move to `/` everywhere.

**Comment by IntelOrca** [comment]
I didn't realise, I think @LRFLEW's approach with the compile time string concatenation is good enough.

**Comment by janisozaur** [comment]
@IntelOrca see https://github.com/OpenRCT2/OpenRCT2/pull/4454

https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx

> Note  File I/O functions in the Windows API convert "/" to "\" as part of converting the name to an NT-style name, except when using the "\\?\" prefix as detailed in the following sections.
