### ISSUE TITLE
Crash in window_sign_invalidate due to original bug

### ISSUE THREAD

**Issue by remcooo96** [OpenRCT2/OpenRCT2#4455]
Mac OSX
0.0.5
426e106
- [x] Reproducible in RCT2 (vanilla)? YES, tested

I have signs in my park that cannot be deleted. Al these "ghost signs" are connected, if I want to give one of them a new name, whatever sign I choose it always shows the same location in the little window (the place it shows doesn't even have a sign. When I change its name, all the names of the ghost signs adopt this name. In openrct even touching the signs lead to a crash, in vanilla just the above described happens.

I will add the dump file from macos and the savegame (some ghost signs are in the middle of the screen when you open it)

[crash report.zip](https://github.com/OpenRCT2/OpenRCT2/files/479591/crash.report.zip)
[Astoria10000.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/479592/Astoria10000.sv6.zip)

**Comment by janisozaur** [comment]
```
0   website.openrct2.OpenRCT2     	0x020bed83 window_sign_invalidate + 54
1   website.openrct2.OpenRCT2     	0x0208f598 window_draw + 518
2   website.openrct2.OpenRCT2     	0x020d677c window_draw_all + 215
3   website.openrct2.OpenRCT2     	0x0207740e SoftwareDrawingEngine::DrawDirtyBlocks(unsigned int, unsigned int, unsigned int, unsigned int) + 224
4   website.openrct2.OpenRCT2     	0x02076f2c SoftwareDrawingEngine::DrawAllDirtyBlocks() + 170
5   website.openrct2.OpenRCT2     	0x02076845 SoftwareDrawingEngine::Draw() + 131
6   website.openrct2.OpenRCT2     	0x0210079b drawing_engine_draw + 26
7   website.openrct2.OpenRCT2     	0x02054faf openrct2_launch + 972
8   website.openrct2.OpenRCT2     	0x0204a1fa main + 41
9   website.openrct2.OpenRCT2     	0x020011f5 start + 53
```

**Comment by remcooo96** [comment]
Okay thats probably the problem, but can you explain what it means. Im no programming wonder, sorry ;)

**Comment by janisozaur** [comment]
It means we know what the problem is, bringing us one step closer to solution. Making it not crash would probably be simple, but fixing such signs properly (so that you can actually delete it or change its value) may require some more effort.

**Comment by duncanspumpkin** [comment]
How did you create the ghost signs. There was a bug in vanilla that causes them but I fixed that for open

**Comment by remcooo96** [comment]
I have honestly no idea, I just started noticing them when I tried to delete one, which caused the game to crash. I know the roots of my savegame are made in vanilla and were then build further in Openrct.

**Comment by duncanspumpkin** [comment]
The bug that caused them in vanilla was when building two signs with same direction on different paths that share x y coordinates but different heights.

**Comment by remcooo96** [comment]
I think I indeed had two signs at different levels. I hope it is fixable. At least stopping the game from crashing would be big improvement :)

**Comment by schott12521** [comment]
I'm using the latest dev version and this occurs only if I beat a park in the Wacky Worlds section, it does not occur in any other parks.
