### ISSUE TITLE
Mechanics can fix vandalized items.

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#446]
Well, considering they are mechanics and they have a reputation for fixing stuff, I thought why not have a feature where they repair all vandalized path items they pass, just like how vandals destroy path items.

**Comment by Gymnasiast** [comment]
Has now been listed on https://github.com/OpenRCT2/OpenRCT2/wiki/Features-to-implement (with handymen rather than mechanics) so this will be closed.
