### ISSUE TITLE
Scenario conflicts

### ISSUE THREAD

**Issue by Charlieep** [OpenRCT2/OpenRCT2#4461]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.0.5]
**Commit/Build:** [e.g. 426e106]

[Explanation of the issue...]This is just 2 questions.
1. I am getting this message on the opening black screen - "Scenario conflict: 'c\users\charlie\documents\openrct2\scenario\185B - Tinted Shores.sc6' ignored because it is newer" 
I have a scenario with that name in both my OpenRCT2 scenario folder and in my RCT2 Scenarios folder. Both are the same file date and everything. The scenario was originally created in RCT2, then modified in OpenRCT2. Does this mean it is not looking at the OpenRCT2 file?
2. When opening the game I used to see a confirmation of the number of items in the dat folder and now is gone. I would like to see that brought back. It helps me to double check both ObjData folders.

**Comment by janisozaur** [comment]
Fix your for formatting

**Comment by IntelOrca** [comment]
> 1. I am getting this message on the opening black screen - "Scenario conflict: 'c\users\charlie\documents\openrct2\scenario\185B - Tinted Shores.sc6' ignored because it is newer" 
I have a scenario with that name in both my OpenRCT2 scenario folder and in my RCT2 Scenarios folder. Both are the same file date and everything. The scenario was originally created in RCT2, then modified in OpenRCT2. Does this mean it is not looking at the OpenRCT2 file?

It always uses the newer version, I suggest you clear out any custom scenarios, objects etc. from your RCT2 folder and move everything to the OpenRCT2 folder.

> 2. When opening the game I used to see a confirmation of the number of items in the dat folder and now is gone. I would like to see that brought back. It helps me to double check both ObjData folders.

That only appears when there are new, removed or changed objects.

**Comment by Charlieep** [comment]
Are you suggesting that I move all of my saved games, scenarios, landscapes and tracks to OpenRCT2 folders? What about ObjData?

**Comment by Broxzier** [comment]
Please review your issue and edit accordingly, The line at the top should explain what to do.

> _[Fill in the placeholders below. Delete any headings and placeholders that you do not fill in. Delete this line as well]_

**Comment by IntelOrca** [comment]
@Charlieep yes, but only files that do not come with RCT2.

**Comment by Charlieep** [comment]
I am sorry if I offended anyone. I didn't have a problem, just a question.
