### ISSUE TITLE
Multiple Corkscrew RC track sprites missing in build window

### ISSUE THREAD

**Issue by joshbgosh10592** [OpenRCT2/OpenRCT2#4462]
When building a Corkscrew RC, the inversion pieces while going down (half loop (down), corkscrew left/right (down) do not have the preview sprite in the building window.
Only the pieces going down is effected. If you build a half loop/corkscrew while going up, this is fine.
It does not appear to matter which orientation you are facing. This happens even if the piece to be built is valid (no ground clearance issues/ etc).
Building the piece process as normal.

***EDIT***
It seems like it's not just the Corkscrew RC, as I also got it to happen with the Compact Inverted RC as well.

**OS:** macOS X El Captain AND Windows 7 (Windows is the server in this example)
**Version:** 0.0.5
**Commit/Build:** 6496895 (Mac) and 8ffe9cd (Windows)

- [ ] Reproducible in RCT2 (vanilla)? (Unsure - unable to launch vanilla, but I doubt it)
- [ ] Multiplayer?

**Steps to reproduce:**
1. Build Corkscrew RC and set up so the next track piece will be a down facing inversion (half loop/corkscrew)
2. Observe the sprite missing in the build window, but it appears in the map.

**Screenshots / Video:**
(These were taking from my Mac, but the issue is exactly the same with the Windows as well.
![screen shot 2016-09-20 at 1 00 33 am](https://cloud.githubusercontent.com/assets/20283787/18658184/725bd2c0-7ece-11e6-950b-6d4344649486.png)
![screen shot 2016-09-20 at 1 06 49 am](https://cloud.githubusercontent.com/assets/20283787/18658193/893d142c-7ece-11e6-9c11-dec1c872333d.png)

![screen shot 2016-09-20 at 1 29 22 am](https://cloud.githubusercontent.com/assets/20283787/18658510/b4d0c7ca-7ed1-11e6-8fcf-40938e3c6d63.png)

**Comment by IntelOrca** [comment]
Bisecting...
