### ISSUE TITLE
Assertion hit in gfx_draw_sprite_get_palette

### ISSUE THREAD

**Issue by kenin0726** [OpenRCT2/OpenRCT2#4467]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 843d865 (same 0f0e9ce, 6496895)

[Explanation of the issue...]
- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. [step 1] load attached save game.
2. [step 2] when move to right side or zoom out 

**Dump file**
After a pop-up error occurs, the game is being terminated immediately.

**Screenshots / Video:**
![failed](https://cloud.githubusercontent.com/assets/17085696/18710074/36409322-803e-11e6-8d16-fad46aed9b15.JPG)
[Drag & drop screenshots here. Use https://vid.me to upload video.]

**Save game:**
[autosave_2016-09-21_20-50-57.zip](https://github.com/OpenRCT2/OpenRCT2/files/484910/autosave_2016-09-21_20-50-57.zip)

**Comment by Margen67** [comment]
Which renderer are you using?

**Comment by kenin0726** [comment]
i try software / software (hw accelated)
opengl is not displayed any text in my system (korean compatible issue?)

**Comment by duncanspumpkin** [comment]
There is a bug in the opengl renderer that can cause this. There shouldn't be issues with the software ones though.

**Comment by IntelOrca** [comment]
Its probably a vehicle with an invalid ternary colour... see #4431

**Comment by duncanspumpkin** [comment]
Yes it is another car ride with a tertiary colour of 0xFC.

**Comment by duncanspumpkin** [comment]
Was this map created on a multiplayer server?

**Comment by kenin0726** [comment]
no, it is single player map.

**Comment by janisozaur** [comment]
Duplicate of #4431
