### ISSUE TITLE
Boats at the Boat hire dock move on top of each other

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#4468]
**Commit/Build:** fae5ad9

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open any park that has a boat ride in it - an example is Electric Fields
2. See that every boat goes to the very front of the station, moving over other boats in the process, instead of moving behind the other boat.

**Screenshots / Video:**
![murky marsh 2016-09-19 22-35-56](https://cloud.githubusercontent.com/assets/1478678/18724287/39675c2c-803c-11e6-9f3a-9bb8acb58a4f.png)

**Comment by marijnvdwerf** [comment]
I assume this might've been introduced by #4442. Can you compare pre/post merge? (merge commit: 665f5e794bc7d408ca6bd6852956ead50ca3fe63)

**Comment by IntelOrca** [comment]
Bisecting this now...
