### ISSUE TITLE
TD4 files are not listed in the track design dialog

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#4469]
**Commit/Build:** fae5ad9

**Comment by IntelOrca** [comment]
Use install track design in the tracks manager.

**Comment by Gymnasiast** [comment]
RCT2 could directly read the TD4. I consider this a regression.

**Comment by IntelOrca** [comment]
Did it show up in the file browsing dialog?

**Comment by Gymnasiast** [comment]
Yes.
