### ISSUE TITLE
Bug: RC Trains stuck at station, "Waiting for passengers at station"

### ISSUE THREAD

**Issue by joshbgosh10592** [OpenRCT2/OpenRCT2#4470]
**OS:** Windows 7 (Server)/Mac OS El Capitan (Client)
**Version:**  0.0.5
**Commit/Build:** 5b01653 (Both client/server)

Multiple Roller Coasters have hung at the station in the "Waiting for passengers at station" status.

- [ ] Reproducible in RCT2 (vanilla)? I don't believe so.
- [x] Multiplayer? (and single player)

**Steps to reproduce:**
1. Build a coaster, open it, and let it run. Likely, it will eventually hang at the "Waiting for passengers at station" status, even though no settings should cause this (wait times, load, etc).

**Screenshots / Video:**
In this example, Powerdrive (Roy) is the hung coaster, however there were others (such as (MAR) Spectre WIP

**Save game:**
[Powerdrive stuck.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/486374/Powerdrive.stuck.sv6.zip)

**Comment by duncanspumpkin** [comment]
The really odd thing is if you close the ride and force the peeps off they start exploding.

**Comment by joshbgosh10592** [comment]
I wasn't sure if that was me or not, but yea, I noticed that as well.

**Comment by merkraybans** [comment]
Happened to me too. If you close the ride and change the number of trains or cars on a train (to make the trains disappear), then the peeps don't explode, in my experience.

**Comment by duncanspumpkin** [comment]
Okay i think ive worked this out. Someone has done the exploding peep cheat whilst the peeps are loading onto the ride. This causes the ride to think that there is still someone walking along the platform but no peep will come. I'm going to change the cheat to skip peeps that are walking along the platform

**Comment by duncanspumpkin** [comment]
It doesn't fix that save but at least it should prevent this from happening again.

**Comment by joshbgosh10592** [comment]
That makes sense. The peeps explode while walking along the station. The game still expects that peep to get into the train, but when it doesn't, it just hangs the ride because the peep never sat in the train.
I'm guessing #d6e13a3 is your fix? I'll update the server/my clients and hope it doesn't happen anymore.
Thanks Duncan!

**Comment by duncanspumpkin** [comment]
Yeah that was my fix. I didn't want to disable peeps exploding in the queue lines but when i tested i found that the explode command sometimes takes a little while to kick in so the queued peeps could end up on the ride causing the issue again. Oh well.
