### ISSUE TITLE
Assertion Failed

### ISSUE THREAD

**Issue by locopingvin** [OpenRCT2/OpenRCT2#4476]
**OS:** Windows 10
**Version:** 0.0.5 
**Commit/Build:** 4a0a93d

Error Message: Microsoft Visual C++ Runtime Library
Assertion Failed!
Program: C:\Program Files (x86)\OpenRCT2\openrct2.dll
File: src\drawing\engines\opengl\OpenGLDrawingEngine.cpp
Line: 1022
bitsOffset < bitsSize
For information on how your program can cause an assertion failure, see the Visual C++ documentation on Asserts.
(Press Retry to debug the application - JIT must be enabled)

- Not applicable to RCT Vanilla (OpenGL error).
- [ ] Multiplayer?

**Steps to reproduce:**
1. New Park: Crazy Castle
2. New Ride: Wooden Roller Coaster

**Screenshots / Video:**
Graphics settings are as follows:
![graphics](https://cloud.githubusercontent.com/assets/5263103/18803634/7e22f39a-81b7-11e6-9028-4427d51cae69.PNG)
Error Box:
![error](https://cloud.githubusercontent.com/assets/5263103/18803664/b236dfc0-81b7-11e6-8f4e-e50c0d305b28.PNG)

**Comment by IntelOrca** [comment]
@locopingvin I have prevented the game from crashing but right now we can't draw track previews in OpenGL.
