### ISSUE TITLE
Inappropriate "Land not owned by park" messages

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#4480]
I'm using the latest develop version and I've noticed that when I want to place an object where there is another object, or trying to build something underground that cannot be built underground, or whatever, the red error message window thing will say "Land not owned by park". So I guess a mix-up in error messages has occurred somewhere!

**Comment by IntelOrca** [comment]
Can't reproduce:
![image](https://cloud.githubusercontent.com/assets/1482259/18808422/17835e2e-825a-11e6-940b-5856bfec6e48.png)

Can you say the exact objects you are placing? And a screenshot?

**Comment by Gymnasiast** [comment]
Are you still on stable 0.0.4? If so, please upgrade to 0.0.5.

**Comment by janisozaur** [comment]
@Gymnasiast 

> I'm using the latest develop version

**Comment by Liampie** [comment]
Can't reproduce it now either, so I guess everyone got lucky and there's no more problem now. I'll keep an eye out though, next time it happens I'll be sure to get screenshots and stuff for a more complete bug report. I've been half-assing too many of my reports and things lately.

**Comment by Margen67** [comment]
If you try setting a player to Admin you get the error.
![wrongerror](https://cloud.githubusercontent.com/assets/3462541/18820838/dc075498-8355-11e6-92e5-d8790065612c.PNG)

**Comment by IntelOrca** [comment]
@Margen67 I noticed this too, its almost as if its the string that is displayed when an action has not explicitly set it before showing an error.

**Comment by Gymnasiast** [comment]
I recently had problems where the error you see when attempting to place track designs without sufficient funds not always contained that reason in the error message. Sometimes it would say I didn't have enough money, something it would just say 'Can't place this track design' without a reason. I haven't yet been able to consistently reproduce it.

**Comment by IntelOrca** [comment]
@Gymnasiast its likely based on what the last error was which did correctly set the reason.

**Comment by duncanspumpkin** [comment]
Yes there are quite a few errors that dont set the error message. Its been like this since vanilla.

**Comment by IntelOrca** [comment]
But it should clear the reason text before executing the game command.

**Comment by janisozaur** [comment]
Can we fix it all by pre-emptively clearing reason text before every command?

**Comment by Gymnasiast** [comment]
My problem is that placing a track design when you have insufficient money _sometimes_ yields an error with a reason, and sometimes does not. RCT2 consistently gives a reason in this particular case.

**Comment by IntelOrca** [comment]
> Can we fix it all by pre-emptively clearing reason text before every command?

We can't do that because most things set the command text to something before running the command.
