### ISSUE TITLE
--serverroot for headless instances please

### ISSUE THREAD

**Issue by Trippeh** [OpenRCT2/OpenRCT2#4489]
Is there a way to set a specific config file with commandline (when running headless instances)?
or have a different serverroot (OpenRCT2 folder in user document = current default)
this way autosaves from the different instances wont mix amongst eachother aswell for users.json and groups.json alike.
Also little sidenote on headless instances, this doesnt translate into a 'Dedicated Server: Yes' on your masterserver list. (eg: https://servers.openrct2.website/81021)

**Comment by AaronVanGeffen** [comment]
We already have `--user-data-path` to point OpenRCT2 to a specific config directory. Does that help?

For a complete list of all command line options, launch OpenRCT2 with `-h` or `--help`.

**Comment by Trippeh** [comment]
Love you guys haha really 👍
