### ISSUE TITLE
Provide tooltip for disabled price field

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#4493]
Parks can be either "pay per ride" or "pay per entrance", somewhat confusing new users. We should provide a tooltip for why is the price locked.

**Comment by Nubbie** [comment]
Like in when hoovering over the disabled option it would say;
"This park only allows payment from {PARK/ENTRENCE} (newline) You could enable both in cheats via the 'Unlock all prices' cheat"

**Comment by HaasJona** [comment]
Please don't reference cheats from normal gameplay tooltips. That would somewhat break the third wall.

**Comment by Nubbie** [comment]
The cheat is missed out almost always
