### ISSUE TITLE
Left and Right Audio Channels are Flipped

### ISSUE THREAD

**Issue by Phasedetect** [OpenRCT2/OpenRCT2#4495]
**OS:** MacOS 10.11 and 10.12
**Version:** 0.0.5
**Commit/Build:** 6b2082f

The left and right audio channels are inverted.

**Steps to reproduce:**
1. Open up BYO Six Flags
2. Place Merry-Go-Round
3. Move viewport to the left and right. Sound favors the right speaker as the ride moves to the left of the screen, and vice versa.

**Comment by IntelOrca** [comment]
I can't reproduce on Windows, so it could be SDL2 related.

**Comment by Patrik356b** [comment]
Might be a good idea to check on Linux tio

**Comment by lsmoura** [comment]
MacOS 10.12, OpenRCT 0.0.5 (binary downloaded). Can't reproduce this error, following the steps provided by OP.

Maybe OP's audio channels are inverted on the OS Settings?

**Comment by Nubbie** [comment]
Maybe just add a option to flip the audio channels for some reason could help

**Comment by rwjuk** [comment]
I am also unable to replicate this on either Linux or macOS with the latest build.

**Comment by Nubbie** [comment]
@Phasedetect 
Do you still experience this issue?
