### ISSUE TITLE
Feature: stopwatch with pause function

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#4498]
The idea for this feature is that the user can precisely control how far to go forwards in time. The feature serves a double purpose: it can be used as a stopwatch to time how long things take, and it can be used to move forward a specific amount of time. The feature will be very helpful to title sequence creators because they can experiment with having shots take different amounts of time without having to add those shots to the title sequence.

This image describes the functions of the feature:
![image](https://cloud.githubusercontent.com/assets/3454156/18935934/4b17b80c-8598-11e6-85fa-bf5256741259.png)

**Comment by AaronVanGeffen** [comment]
I'm a bit torn on this. On the one hand, I can definitely see it would have its uses. On the other, while it's a nice idea, we'd have to keep all game actions, or even intermediate game states, in memory, which would add up really quickly as there are 40 ticks every second.

A feature request for undo functionality was rejected for similar reasons: it's much more involved to "turn back time" in-game than just UI, I'm afraid.

**Comment by spacek531** [comment]
This isn't asking to turn back time: I get that it's a fool's quest to try and do that. This feature request is a stopwatch that can also pause the game.

**Comment by AaronVanGeffen** [comment]
Oh, I'm sorry, I should've read your proposal a little better. Yes, a timer-based pausing/unpausing feature should be fine, of course.
