### ISSUE TITLE
Music Slider Crash Issue

### ISSUE THREAD

**Issue by Razkel** [OpenRCT2/OpenRCT2#4499]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.0.5]
**Commit/Build:** [e.g. 426e106]

The game crashes on launch after adjusting the music.

- [ Yes] Reproducible in RCT2 (vanilla)?

**Steps to reproduce:**
1. Adjust Music Slider in Options
2. Launch Game

**Dump file**
[1feb4dac-d67c-4afa-899b-f3a6ba20836a.zip](https://github.com/OpenRCT2/OpenRCT2/files/499529/1feb4dac-d67c-4afa-899b-f3a6ba20836a.zip)

**Comment by Gymnasiast** [comment]
Could you provide your build number?

**Comment by IntelOrca** [comment]
The dump doesn't contain it in the filename so I imagine its 0.0.4 or an old develop build.

**Comment by Razkel** [comment]
I was using 0.0.4, but then my issue was solved when I started using the
dev builds.

**Comment by Gymnasiast** [comment]
Ok, good to hear.
