### ISSUE TITLE
Error messages aren't detailed

### ISSUE THREAD

**Issue by ThePsionic** [OpenRCT2/OpenRCT2#4502]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** d6e13a3

When building things without having enough money, the popup just says "Can't construct this here..." without detailed explanation.

- [ ] Reproducible in RCT2 (vanilla)? Unknown - unable to boot it up
- [ ] Multiplayer?

**Steps to reproduce:**
1. Suck at the game, have no money
2. Try to build toilets

**Screenshots / Video:**
![](http://i.imgur.com/coNE92k.png)

**Save game:**
[Panda Park.txt](https://github.com/OpenRCT2/OpenRCT2/files/501325/Panda.Park.txt)

**Comment by YJSoft** [comment]
maybe related to #4480
