### ISSUE TITLE
Bug: Rides set type doesn't work anymore.

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#4504]
A few days ago I reported about the "Land not owned by park" bug I encountered, and I know remember where I saw it repeatedly: when I try to change a track type using the console, I get the land not owned error whatever I do, and no track types have changed. I was using [these](http://www.nedesigns.com/topic/32012/openrct-advantages-and-disadvantages/page-17#entry697359) instructions. Apparantly something has changed and these instructions don't work anymore.

**Comment by janisozaur** [comment]
you need to enable this cheat in cheats

**Comment by Liampie** [comment]
Oh. That's new. What does that box do other than being able to change track types in the console?

**Comment by janisozaur** [comment]
It alters ride window and adds ride type selector to it. Ride type changes are synchronised in multiplayer now as well.

**Comment by janisozaur** [comment]
It should read "permission denied" which falls under https://github.com/OpenRCT2/OpenRCT2/issues/4480. I will close this now.
