### ISSUE TITLE
The happiness cheat does not clear the 'red-faced with anger' status

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#4505]
![example](https://i.redd.it/dv82caljjnox.png)

**Comment by duncanspumpkin** [comment]
That happiness cheat is to change the happiness not the flags. There should really be a separate cheat for changing the flags.

**Comment by Gymnasiast** [comment]
The combination of a full (or even half-full) happiness bar with a raging red face makes no sense at all.
