### ISSUE TITLE
Two dumps

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#4508]
The earlier dump was when loading Leafy Lake. The later dump happened while OpenRCT2 was idling on the title screen, out of focus.

Second error: ERROR[src\drawing\Image.cpp:129 (gfx_object_allocate_images)]: Reached maximum image limit.

[some dumps.zip](https://github.com/OpenRCT2/OpenRCT2/files/504009/some.dumps.zip)

version is acaa0d3

**Comment by janisozaur** [comment]
@spacek531 it's much easier for us to track if each bug has its own issue filed

**Comment by IntelOrca** [comment]
I did some fixes recently for images, your version pre-dates those fixes so see if you can reproduce it again with the latest version.

**Comment by spacek531** [comment]
The images crash, which I nailed down to happening when the title sequence restarted, doesn't happen any more. Thanks!
