### ISSUE TITLE
no hash at windows installers

### ISSUE THREAD

**Issue by bnnu** [OpenRCT2/OpenRCT2#4509]
**OS:** Windows 7
**Version:** 0.0.5
**Commit/Build:** acaa0d3

There's no information about build(commit hash, branch, ...) on windows installers.

Downloaded filename is `OpenRCT2-0.0.5.0--windows-win32.exe/zip`(must be `OpenRCT2-0.0.5.0-acaa0d3-windows-win32.exe/zip`) - see https://openrct2.org/downloads/develop/acaa0d3.

![cap 2016-10-01 15-06-13-900](https://cloud.githubusercontent.com/assets/13377456/19012178/9db14d2e-87e8-11e6-9608-478c1d7ba67f.png)
and there's no hash on installer too.

**Comment by janisozaur** [comment]
d6e13a3 was (last?) good

timing of this looks relevant: https://www.appveyor.com/updates/2016/09/26/

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/commit/a77c37f6807f085eabc832825057527817f27ed4
