### ISSUE TITLE
Crash, invalid scrolling mode for banner

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#4511]
This park crashed while I was scrolling across the two large Wooden Roller Coasters.

**OS:** Windows 7
**Version:** 0.0.5
**Commit/Build:** d6e13a3
[OpenRCT2CrashOct1.zip](https://github.com/OpenRCT2/OpenRCT2/files/504455/OpenRCT2CrashOct1.zip)

**Comment by IntelOrca** [comment]
Can you export the saved game with objects?

**Comment by IntelOrca** [comment]
There is a corrupted banner in the park.

**Comment by IntelOrca** [comment]
The object 'RSTNENTR' has an invalid value for scrolling mode.
