### ISSUE TITLE
null area at map edge

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#4512]
[image](https://cloud.githubusercontent.com/assets/3454156/19018045/0cb2c210-8808-11e6-8cb0-1e5b9b701393.png)

You can see I've moved the land tool window through this null area. I think it has something to do with larger sizes of mountain tool (i.e. 2x2 and above). I did it once before, months ago, so a current version hash is irrelevant.

[Null area park.zip](https://github.com/OpenRCT2/OpenRCT2/files/504738/Null.area.park.zip)

EDIT: using the map size function to decrease the map size removes null areas.

**Comment by Nubbie** [comment]
Relevant to: #3390 ?

**Comment by spacek531** [comment]
Whoops! Looks like I posted a duplicate then.

**Comment by rwjuk** [comment]
@spacek531 Can you retest this on the latest build and check if it still occurs? Thanks.

**Comment by spacek531** [comment]
Using 252555df and it's happening. It happens only on the side that is _not_ changed when you increase map size in sandbox mode with any size mountain dragger.
![image](https://user-images.githubusercontent.com/3454156/27758887-c68ccaf8-5dd4-11e7-91cb-1315b50c3ea1.png)

**Comment by IntelOrca** [comment]
@spacek531 Could you give instructions on how to reproduce this from startup? If I try going into the scenario editor and then using the mountain tool on all sides of the map, it doesn't happen.

**Comment by spacek531** [comment]
I'm editing this file (rename to sv6 on downloading):
![maple springs p3](https://user-images.githubusercontent.com/3454156/27765359-b0201b82-5e63-11e7-8bf3-72e56ed1ca2a.png)

On the corner of the map that has "Spacek" in yellow trees, any time the mountain tool manipulates a tile on the edge, it happens.

**Comment by IntelOrca** [comment]
@spacek531 Can you find a way of reproducing it without loading a saved game?

**Comment by spacek531** [comment]
Info for debuggers:

This happens consistently on maps that were created or imported in the 0.0.5 develop version. It may have happened in other releases, but I have not played OpenRCT2 between then and now.
