### ISSUE TITLE
Cannot join multiplayer server with umlaut in player name

### ISSUE THREAD

**Issue by manuelVo** [OpenRCT2/OpenRCT2#4513]
**OS:** Arch Linux
**Version:** 0.0.5
**Commit/Build:** d81bed5

When trying to join a muliplayer server while having an umlaut in the player name the connection gets stuck at `Authenticating`.

For exmple when trying to connect as `Stäbchenfsich` the console prints the following:

```
Generating key... This may take a while
Need to collect enough entropy from the system
VERBOSE: Key successfully generated
VERBOSE: New key of type 6, length 2048 generated successfully.
Key generated, saving private bits as /home/manuel/.config/OpenRCT2/keys/Stäbchenfisch.privkey
VERBOSE: adding subDirectory 'keys'
VERBOSE: outPath + subDirectory = '/home/manuel/.config/OpenRCT2/keys/'
VERBOSE: /home/manuel/.config/OpenRCT2/keys/
VERBOSE: saving key of length 887
VERBOSE: adding subDirectory 'keys'
VERBOSE: outPath + subDirectory = '/home/manuel/.config/OpenRCT2/keys/'
Key generated, saving public bits as /home/manuel/.config/OpenRCT2/keys/Stäbchenfisch-7c9a7861f77b4bc6746b1ff98917051b254886be.pubkey
VERBOSE: requesting token
VERBOSE: adding subDirectory 'keys'
VERBOSE: outPath + subDirectory = '/home/manuel/.config/OpenRCT2/keys/'
VERBOSE: file '/home/manuel/.config/OpenRCT2/keys/St' exists = 0
ERROR[/home/manuel/.cache/pacaur/openrct2-git/src/openrct2-git/src/network/network.cpp:1327 (Client_Handle_TOKEN)]: Key file (/home/manuel/.config/OpenRCT2/keys/Stäbchenfisch.privkey) was not found. Restart client to re-generate it.
```
Public and private key are generated fine (i can see them in the directory) however the game fails to load them after generation. The last `VERBOSE` line contains the path to the privkey but seems to get cut off at the umlaut when trying to load the key.

- [ ] Reproducible in RCT2 (vanilla)
- [x] Multiplayer

**Steps to reproduce:**
1. Set a player name with an umlaut
2. Try to join a server

**Comment by IntelOrca** [comment]
Just tried it on Windows, seems to work fine - so possible an issue with the Linux platform code.

**Comment by manuelVo** [comment]
I investigated a bit further and found out that the code fails here:

https://github.com/OpenRCT2/OpenRCT2/blob/f8145b6edc8abc4528fa9c96cc345b81432046f8/src/platform/posix.c#L129

For some reason when wcstombs reaches the umlaut it starts to output gibberish.
The buffer after executing wcstoms looks like this:
`/home/manuel/.config/OpenRCT2/keys/StËÓb÷\0 á÷(ßG\002\020ßG\002(ÏÿÿHäÖ÷(ßG\002(ßG\002ËÓb÷\0 á÷(J!\002\020ßG`

**Comment by IntelOrca** [comment]
I am surprised it needs to do this, I thought Linux used UTF-8 for its file IO functions.

**Comment by manuelVo** [comment]
I did a little more research on this. While most modern Linux distributions use UTF-8 there is no gurantee that all do it. Because of that the string has to be converted to the locale of the system.

There are 2 separate issues here:
1. Before `wcstombs` can be called with a non ascii string `setlocale(LC_CTYPE, "")` has to be called to initialize the locae using the systems environment variables. (apparently `setlocale(LC_ALL, "")` can be called as the second option as well). Doing so will prevent `wcstombs` from outputting gibberish.
2. `len` isn't calculated properly. `utf8_length` returns the number of actual characters in the string while the number of bytes output by `wcstombs` is required.
