### ISSUE TITLE
Toilet volume plays over rides music

### ISSUE THREAD

**Issue by SkrackStdusr** [OpenRCT2/OpenRCT2#4519]
**OS:** Ubuntu, Linux (16.04)
**Version:** 0.0.5
**Commit/Build:** 08eb1db

The volume of the toilets is too damn high! 
I placed a pair of toilets and their volume was so high, that rides noise got "overnoised?". Please add something to toggle toilets sound on/off or lower the sound output, or something.

**Steps to reproduce:**
1. Place toilets
2. Listen

//sorry for the whinyness

**Comment by Margen67** [comment]
Does this happen in vanilla RCT2?

**Comment by IntelOrca** [comment]
@Margen67 yes, we have already stopped it from playing on the title sequence. General consensus among community is that the sound is very annoying.

**Comment by Nubbie** [comment]
Wouldn't lowering the volume be enough?
Never heard a toilet in real life behind heard all the way 100 m in the sky, we don't hear the people drinking/eating so

**Comment by RollingStar** [comment]
You can patch the sound out yourself from css1.dat or dampen the volume. I've never done it but it should be possible.

https://github.com/OpenRCT2/OpenRCT2/wiki/Music-Cleanup

https://freerct.github.io/RCTTechDepot-Archive/css1dat.html

**Comment by HaasJona** [comment]
Relevant code is here: https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/peep/peep.c#L3899

I'd be fine with removing the sound completely (not only on the title screen) which should be easiest for now.

**Comment by Nubbie** [comment]
Presume a mute button for just the toilet sound would work

**Comment by HaasJona** [comment]
I guess there is no consensus to remove it completely. So what do we do? Make it a setting?

**Comment by duncanspumpkin** [comment]
Could just make it half the current volume

**Comment by Nubbie** [comment]
Maybe have a slider to lower special effects like 'coin sounds', toilet etc?

**Comment by AaronVanGeffen** [comment]
> Maybe have a slider to lower special effects like 'coin sounds', toilet etc?

I thought that was what the 'Sound effects' slider was supposed to be for?

**Comment by HaasJona** [comment]
"sound effects" is pretty much every sound except for ride music and similar ambience. Disabling that isn't really a solution to just mute the stupid toilet sound.

I could create a pr with a slider just for the toilet sound, not really sure if that's the right way, though.

**Comment by HaasJona** [comment]
Not sure if a slider is necessary, I created a pr with just a simple reduced sound volume (if I understand the math correctly, it should be reduced by a litle bit more than a half in volume)

**Comment by Gymnasiast** [comment]
Fixed by #4642.
