### ISSUE TITLE
Raise limits for multi-tile tools like Land, Clear Scenery, own/disown land, etc

### ISSUE THREAD

**Issue by Margen67** [OpenRCT2/OpenRCT2#4533]
**OS:** [All/Any]
**Version:** [0.0.5]
**Commit/Build:** [71d0861be131c2a710fbb7173f265d839dd715ac]

With tools like Clear Scenery and Land you can only go up to 64.
This limit should be raised since the map can be bigger than 64x64.
- [x] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
N/A

**Dump file**
[N/A]

**Screenshots / Video:**
[N/A]

**Save game:**
[N/A]

**Comment by Gymnasiast** [comment]
64 is plenty. Especially if you consider it used to be 7.

**Comment by wolfreak99** [comment]
If this were to be raised, I'd like some filter for servers that would cap the amount that is sent in to prevent extreme abuse on servers

**Comment by Margen67** [comment]
The point of raising the limits is to do these actions throughout the entire map instantly without moving your cursor around.

If griefing is a concern you can just cap the limit in multiplayer like wolfreak said.
