### ISSUE TITLE
Crash in track_list_load_designs (pre-#4679)

### ISSUE THREAD

**Issue by Arystina** [OpenRCT2/OpenRCT2#4542]
**OS:** Windows 7
**Version:** 0.0.5
**Commit/Build:** 41f026e

Explanation of the issue:
Game crashes after a few minutes in the track designs manager. Seems that missing modded vehicles was only part of the problem. Something else is still wrong. Seems to occur most frequently when sorting through a large list of coaster tracks and deleting them (please note the deleting part).

I did play a scenario. I didn't mess around too much with the coaster menus for fear of a crash happening, just quickly picked and grabbed a pre-made coaster without any browsing, but thankfully was able to play the scenario through without any crashes.

**Steps to reproduce:**
1. Install a very large amount of tracks.
2. Go into manager and start editing/deleting those tracks. Crash should occur after a few minutes, sometimes immediately after the first edit/delete.

**Zip File** (Includes 2 dumps, 2 saves, and a screenshot.)
[tracks manager still crashing.zip](https://github.com/OpenRCT2/OpenRCT2/files/512879/tracks.manager.still.crashing.zip)

**Comment by Nubbie** [comment]
Had problem loading one of the dump files, but the dumpfile I got was 93778aff-e51e-4ce4-890f-35e7b2a58d48(41f026e).dmp and here is some info

**New Title;** Crash in Track Manager by "rideEntry was 0xFFFFFFFF" ?

**Error Message;**
Unhandled exception thrown: read access violation.
rideEntry was 0xFFFFFFFF.

**Call Stack;**
```
>	openrct2.dll!track_list_load_designs(ride_list_item item={...}) Line 611	C
 	openrct2.dll!window_track_list_update(rct_window * w=0x58d785f0) Line 325	C
 	openrct2.dll!game_update(...) Line 312	C
 	openrct2.dll!rct2_update(...) Line 462	C
 	openrct2.dll!openrct2_loop(...) Line 466	C
 	openrct2.dll!openrct2_launch(...) Line 340	C
 	openrct2.dll!StartOpenRCT(HINSTANCE__ * hInstance=0x00400000, HINSTANCE__ * hPrevInstance=0x00000000, char * lpCmdLine=0x016439a7, int nCmdShow=1) Line 134	C
 	openrct2.exe!004069e4()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for openrct2.exe]	
 	[External Code]	
```

**Locals;**
```
+		entry	0x000cfe70 "X°\xe§7"	char[9]
-		entryPtr	0x00000000 <NULL>	const char *
			<Unable to read memory>	const char
-		item	{type=44 ',' entry_index=0 '\0' ride_type_and_entry=44 }	ride_list_item
		type	44 ','	unsigned char
		entry_index	0 '\0'	unsigned char
		ride_type_and_entry	44	unsigned short
+		rideEntry	0xffffffff {name=??? description=??? images_offset=??? ...}	rct_ride_entry *
```

**Autos;**
```
		RIDE_ENTRY_FLAG_SEPARATE_RIDE	RIDE_ENTRY_FLAG_SEPARATE_RIDE (8192)	<unnamed-enum-RIDE_ENTRY_FLAG_0>
+		entryPtr	0x00000000 <NULL>	const char *
+		item	{type=44 ',' entry_index=0 '\0' ride_type_and_entry=44 }	ride_list_item
		item.entry_index	0 '\0'	unsigned char
		item.type	44 ','	unsigned char
+		rideEntry	0xffffffff {name=??? description=??? images_offset=??? ...}	rct_ride_entry *
```

**Comment by janisozaur** [comment]
@Arystina any chance of you providing a zip of your track designs? Otherwise I would close it on grounds of https://github.com/OpenRCT2/OpenRCT2/pull/4679

**Comment by Gymnasiast** [comment]
With the code having been completely changed with #4679 and subsequent refactors, the chances of this bug still being present in this form are very slim. For this reason, I'll close this. If you still have this bug, please provide a new dump and I'll reopen this.
