### ISSUE TITLE
Explosion Cheat does not work with imported maps from RCT1

### ISSUE THREAD

**Issue by StickGuySeven** [OpenRCT2/OpenRCT2#4543]
**OS:** Windows 10 Pro 64-Bit
**Version:** 0.0.5
**Commit/Build:** 41f026e

The explosion cheat does not work on an imported RCT1 saved game scenario. It removes the guests but does not display the explosion.

**Steps to reproduce:**
1. Import a save from RCT1.
2. Let guests enter park or Large Tram.
3. Explosion Cheat
4. Observe

**Dump file**
Not a crash.

**Save game:**
[Leafy Lake.zip](https://github.com/OpenRCT2/OpenRCT2/files/512941/Leafy.Lake.zip)

**Comment by Gymnasiast** [comment]
I can't reproduce this. Not with your save, nor with one of my own. Is it possible you have your game set to the experimental OpenGL renderer?
