### ISSUE TITLE
Popcorn shown as pizza

### ISSUE THREAD

**Issue by AusterKordel** [OpenRCT2/OpenRCT2#4545]
**OS:** Windows 8.1
**Version:** 0.0.5
**Commit/Build:** 41f026e

If guests buy popcorn it looks like they are eating a pizza and fried chicken is looking like donuts.

**Comment by Liampie** [comment]
Sounds like molecular gastronomy tricks.

**Comment by YJSoft** [comment]
Vanila
![vanila](https://cloud.githubusercontent.com/assets/5893514/19207734/55ca1806-8d2e-11e6-861f-ad54915ee9b6.png)

OpenRCT2(89d672b)
![2016-10-07 08-08-18](https://cloud.githubusercontent.com/assets/5893514/19207762/a0203854-8d2e-11e6-85fb-a4c495c0a3ae.png)

Not all foods have own sprite.

**Comment by YJSoft** [comment]
Nevermind. forget it.

Looks like sprite issue.
