### ISSUE TITLE
Crash due to accessing invalid sprite in remove_peep_from_queue

### ISSUE THREAD

**Issue by remcooo96** [OpenRCT2/OpenRCT2#4553]
[Fill in the placeholders below. Delete any headings and placeholders that you do not fill in. Delete this line as well]

**OS:** MacOS 10.11.6
**Version:** [e.g. 0.0.5]
**Commit/Build:** [

Why is my game crashing when I try to place a wall or remove it here?
Probably a bug in my savegame but I dont know the cause.
I have a crash dump file.

[dumpfile.zip](https://github.com/OpenRCT2/OpenRCT2/files/516637/dumpfile.zip)

**Comment by janisozaur** [comment]
Which commit was it on?

**Comment by LRFLEW** [comment]
Just from what I can see from the data provided, it looks like the sprite limit in the park got reached. The line causing problems is [here](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/world/sprite.c#L43) from what I can gather from the stack trace. @remcooo96 Can you upload the save game that this is happening on? That could help us reproduce the issue.

**Comment by janisozaur** [comment]
@LRFLEW I think you may be wrong. See https://github.com/OpenRCT2/OpenRCT2/pull/4129/commits/381545aa2b2f6c7a6a61ea7009a8ccae160ac670

**Comment by remcooo96** [comment]
Actually the problem is solved by opening an autosave from 5 minutes earlier, I can still upload the savegame for you to check for bugs if you want or something.
