### ISSUE TITLE
Peep jams halfway to destination

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#4557]
After some AI issues got fixed recently I got really happy and worked on my park again. Since today however a new kind of peep jam has popped up, more mysterious in origin.

The problem is that guests heading for the wooden coaster and the ferris wheel get stuck in three random places. They won't even reach their destination if it's just straight path to get there. I marked the three peep jams and the destinations on the screenshot below.

![peepjams](https://cloud.githubusercontent.com/assets/19242088/19206880/5da92fa4-8cec-11e6-98b5-65be4b5a788c.png)

Savegame:

[Mysterious Peep Jams.zip](https://github.com/OpenRCT2/OpenRCT2/files/517190/Mysterious.Peep.Jams.zip)

Using version v0.0.5 a8a4c0d on Windows 8.

**Comment by mrtnptrs** [comment]
@zaxcav is quite an expert regarding the guest AI :)

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/files/512174/whiskey_s2_nogo64_2.sv6.zip, the park from #4537, also suffers from similar, if not the same, issue. See area around "Deco dive merge" coaster (crimson-yellow one to the right).

**Comment by Liampie** [comment]
It may have something to do with peeps not willing to cross ride track. Zero clearanced or not. When I deleted the train track in the screen above, the two leftmost peepjams dissolved. The peep jam on the right apparantly isn't heading for the woodie and ferris wheel, but the schwarzkopf and some food stalls elsewhere. I guess that removing the schwarzkopf track over the path will dissolve this peep jam.

**Comment by zaxcav** [comment]
Yes, the railway track placed with zero clearance on the path will definitely cause an issue there.
When the pathfinding is looking for paths on each tile, it's now aware of other map element types (it wasn't before) - the intent behind this is to look for ride entrances in preparation for adding transport rides to the pathfinding eventually.  But it does this in a way that is unfriendly to people using zero clearance.  This was not on purpose, so I'll revise the code.

Watch this space.

**Comment by zaxcav** [comment]
I've revised the code to handle map elements placed using zero clearance much better (better even than the original). I've done a super quick test and observed peeps successfully pathfinding across one of train tracks in the Mysterious Peep Jams park.
I want to run all my usual tests, to make sure I didn't break something else in the process of fixing this, before I submit a PR.
I should have time for that tomorrow.

**Comment by duncanspumpkin** [comment]
@zaxcav we will make a completely different ai in the future that handles transport. I wouldn't bother adding that before then

**Comment by zaxcav** [comment]
PR #4576 fixes these jams.
The path finding no longer stops as soon as it finds a path (or other map element of interest), so placing multiple paths at the same height or other uses of zero clearance should not glitch the path finding anymore.

**Comment by zaxcav** [comment]
@duncan Sure.
In that case, unless I've broken something with these fixes, I can leave the pathfinding as is for now and help out in other areas.
