### ISSUE TITLE
Flat rides have the same running cost

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#4560]
I was playing a scenario when I noticed that all the flat rides cost $49.60 per hour to run.

DirectPlay isn't installing, so I'm just relying on gut intuition to call this one.

7b9bfd6 on w10, playing solo

**Comment by mrtnptrs** [comment]
Download this and install it: https://www.microsoft.com/en-us/download/details.aspx?id=35 After you have done that, starting vanilla RCT2 should trigger the DirectPlay installation. Then you can test the behavior and report back to us. When that still doesn't work, try to activate DirectPlay manually after you did the above. See: https://cdn2.windowsforum.com/attachments/screenshot-36-png.29343/ and Google.

**Comment by AaronVanGeffen** [comment]
What does DirectPlay have to do with it? It [hasn't been a dependency](https://github.com/OpenRCT2/OpenRCT2/blob/63ce7170c674861db4bef56ecf24bf8d80ab6063/distribution/changelog.txt#L177) for quite a while.

**Comment by IntelOrca** [comment]
@AaronVanGeffen this is that vanilla can be run to check if this issue happens there too

**Comment by DonCuan** [comment]
@spacek531 
All flat rides costing $49.60 to run is not true – e.g. the Crooked House costs $28.80, Dodgems $108.80 and Flying Saucers $148.80 – but more importantly these operating costs have been consistent since RCT1 throughout RCT2 and OpenRCT2. So this is not a bug.

You could argue about rebalancing operating costs to make things more realistic, but the economy in the RCT series is highly abstracted anyway.

**Comment by spacek531** [comment]
@DonCuan I dunno... you tell me:
![image](https://cloud.githubusercontent.com/assets/3454156/19224654/15db3e16-8e3f-11e6-883a-291ace560401.png)

**Comment by DonCuan** [comment]
Most of them do cost $49.60/h, as do toilets and stalls. But I just gave you three counterexamples that don't.

**Comment by spacek531** [comment]
It was surprising to see them all cost the same. I coudn't get RCT2 to work on my computer, so I haven't been able to check. If it is what they cost in RCT2 then this isn't a bug.

**Comment by YJSoft** [comment]
![scr2](https://cloud.githubusercontent.com/assets/5893514/19252560/71deb318-8f80-11e6-8fc1-94c32bde2cf4.png)
Tested at vanilla RCT2. 

![scr3](https://cloud.githubusercontent.com/assets/5893514/19252592/901d3cb4-8f80-11e6-9ec0-e3bff5e80e5a.png)
Although three flat rides mentioned above(Crooked house, Dodgems, Flying Saucers) have different running cost, other flat rides have $49.60 as running cost.

**Comment by spacek531** [comment]
Closing the issue because it is not a bug.
