### ISSUE TITLE
OpenRCT2 unnecessarily removes walls when building tracked rides, even with clearance checks disabled

### ISSUE THREAD

**Issue by DonCuan** [OpenRCT2/OpenRCT2#4568]
When building next to a wall or fence, both vanilla and OpenRCT2 clear obstructing wall pieces. The difference is that OpenRCT2 is more radical about it.

Vanilla only removes adjacent walls when building a station platform, which doesn't allow any wall pieces in the same block or when passing through a wall.

OpenRCT2 also clears walls when building straight pieces (flat or sloped). It doesn't remove anything when building a sharp 1x1 turn next to the wall and only the first wall piece when building a 2x2 turn. This happens even when clearance checks are disabled with a cheat.

**Steps to reproduce:**
1. Open a scenario with prebuilt walls in both RCT2 and OpenRCT2. Crazy Castle works well.
2. Build a tracked ride such as Mini Helicopters on the inner side of the wall.
3. Compare results

**Comment by DonCuan** [comment]
On the other hand, OpenRCT2 clears less wall pieces when building a curve through a wall. RCT2 would have removed the next one as well:

!(https://cloud.githubusercontent.com/assets/2139850/19220728/8908e5b0-8e34-11e6-8078-77a5a2531738.png)

**Comment by Liampie** [comment]
Same problem with paths.

**Comment by DonCuan** [comment]
I didn't have any issue with the path tool deleting adjacent scenery when building parallel to the wall, in either mode.

It does delete the wall when going through it in bridge/tunnel mode, even with the clearance cheat, but that's not really what the issue is about.
