### ISSUE TITLE
Add twitch alternative: YouTube Gaming

### ISSUE THREAD

**Issue by buson94** [OpenRCT2/OpenRCT2#4570]
YouTube Gaming(https://gaming.youtube.com/) launched in Germany 2 months ago and i would like to stream there and also use the streaming features that OpenRCT2 currently has.

Please add this streaming plattform as alternative to twitch! :)

**Comment by fromthere** [comment]
[API Document for chat message list](https://developers.google.com/youtube/v3/live/docs/#LiveChatMessages)

**Comment by Joshwoo70** [comment]
if it really catches on like it takes off like a rocket and be like twitch.. i myslef mught xonsider it.

**Comment by AaronVanGeffen** [comment]
Is anyone using YouTube Gaming?

**Comment by Broxzier** [comment]
Apparently @buson94 is or would like to. And LetemcomeInit on YouTube has been streaming OpenRCT2 gameplay recently.

**Comment by IntelOrca** [comment]
This should wait for plug-in support which is when Twitch stuff will also be moved out.
