### ISSUE TITLE
Don't create a new autosave if nothing has changed

### ISSUE THREAD

**Issue by DonCuan** [OpenRCT2/OpenRCT2#4571]
I sometimes find myself leaving the game idle in pause mode, only to come back having all the autosave slots overwritten with the same save. Not very useful.

To prevent this, the game could check for idleness and not create an autosave if nothing has been done. ("nothing" _could_ include moving the viewport, if that's the only change)

I've noticed that autosave files from letting the game truly sit idle are bitwise identical. So the easiest way to implement this without extra checks would be to just compare hashes of the last autosave and not to create a new autosave file on a match.

**Comment by HaasJona** [comment]
A relatively simple solution might be to only autosave in paused mode when the "allow building while paused" cheat is active.

**Comment by janisozaur** [comment]
While this would cover many cases, there are many others that could be considered "change":
* picking up peeps
* hiring staff
* changing rides' state
* starting advertisement campaign
to name just a few.

The other way to do that could be taking sprites' checksum at one autosave, then compare it before doing another autosave, this would fit author's request precisely.
