### ISSUE TITLE
Crash when opening Rides dialog box

### ISSUE THREAD

**Issue by kingcailan** [OpenRCT2/OpenRCT2#4577]
**OS:** Windows 10 Pro Anniversary Update (64-bit, build 14393.222)
**Version:** 0.0.5
**Commit/Build:** b18f8d0

I was playing the game and I opened the rides menu. crashed, but thought nothing of it. Restarted, and I reloaded my save, opened the rides menu... crashed again. I then realized it's really easy to reproduce.

- Not reproducible in vanilla.
- Unable to test multiplayer.

**Steps to reproduce:**
1. Build any ride.
2. Open the Rides menu.
3. ???
4. Profit.

**Dump file**
[OpenRCT2.zip](https://github.com/OpenRCT2/OpenRCT2/files/518747/OpenRCT2.zip)

**Screenshots / Video:**
https://youtu.be/kpcxLLyJQK0

**Save game:**
Included in dump file zip.

**Comment by Zekka** [comment]
Can confirm this crash and that it only occurs on the latest build. (or, well, on a build that was released tonight after ~4:00 PM) Does not appear to occur if no rides exist.

**Comment by newton27** [comment]
Same here too.

**Comment by Nubbie** [comment]
The crash seems to come from the update 'https://openrct2.org/downloads/develop/fb46335'

@newton27 @Zekka @kingcailan Try this version https://openrct2.org/downloads/develop/211a0d7 (the one before that one)

**Comment by kingcailan** [comment]
I've confirmed after testing multiple other versions that it does only occur on build b18f8d0. Thanks for the tip everyone!

**Comment by Zekka** [comment]
I have not yet tested on another version, but if you guys haven't conclusively determined cause by tonight (it sounds like you have) I'll test then.

Thanks!

**Comment by janisozaur** [comment]
please keep the chatter to minimum.

`format_string_to_upper` passes uninitialised `left` to `format_string_part`, then to `format_append_string_n` which is then dereferenced and evaluated.

**Comment by ThaJay** [comment]
I'm on a fresh install of 0.0.5.0 build 2fca2ad
updated because of this crash, so I was on an older version before but I don't know which one. Anyway, same crash. When I open the rides menu all tabs are fine apart from the coasters tab. As soon as I click it the game crashes. 

Here are the logs.
[OpenRCT2.zip](https://github.com/OpenRCT2/OpenRCT2/files/662344/OpenRCT2.zip)

**Comment by janisozaur** [comment]
@ThaJay I doubt it's still the same one, can you open a new issue, please?
