### ISSUE TITLE
Junior Coaster diagonal flat-to-steep sprites missing

### ISSUE THREAD

**Issue by YoloSweggLord** [OpenRCT2/OpenRCT2#4584]
**OS:** Windows 10
**Version:** v0.0.5
**Commit/Build:** e70765c

Diagonal steep slope to flat pieces are now buildable for junior coasters. However, the track sprites do not show up. The coaster trains do not have a problem traversing these pieces. I saw that @Gymnasiast  made several topics on adding these sprites into g2.dat, so I do not know if this is an issue with the code not referencing the sprites or the g2.dat file not updating properly when a new build is downloaded. Please note I am using the launcher to automatically update the game.
edit: sorry, tagged the wrong person
- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Build a junior coaster.
2. On a diagonal, build a track piece going from flat to steep, or the other way around.

**Screenshots / Video:**
![spritereport1 1](https://cloud.githubusercontent.com/assets/19209095/19247659/3a957ba2-8efa-11e6-9e32-75dcbf2e2102.PNG)
![spritereport1 2](https://cloud.githubusercontent.com/assets/19209095/19247658/3a950028-8efa-11e6-8dcf-536a2fccb0b2.PNG)

**Comment by Gymnasiast** [comment]
No, it's just that the game lacks drawing code for those pieces. That was an oversight on my part.
