### ISSUE TITLE
OpenRCT2 not showing up in OBS

### ISSUE THREAD

**Issue by LY-Entertainment** [OpenRCT2/OpenRCT2#4588]
**OS:** [e.g. Windows 7]
**Version:** [e.g. 0.0.5]
**Commit/Build:** [6f95ba4]

I also tried this with an earlier version and thought updating would solve the issue and i have tried usual things-delete and recreate captures, restart game. In also noticed the flying coaster glitch but this seems to already been taken care of. If there is anything else i can do, dump it here.

**Comment by IntelOrca** [comment]
Have you set the renderer to software (hardware display) in options?

**Comment by kingcailan** [comment]
Using any hardware accelerated render option will change that. For OBS, I'd suggest OpenGL, but keep in mind that when you zoom out in OpenGL, it will slow your game down a ton.

**Comment by marijnvdwerf** [comment]
What about changing the default option to 'software (hardware display)'? That would also make it less ugly to use non-integer scales.
