### ISSUE TITLE
Supports for hanging rides are wrong

### ISSUE THREAD

**Issue by marijnvdwerf** [OpenRCT2/OpenRCT2#4591]
Decompiled:
![image](https://cloud.githubusercontent.com/assets/737603/19253426/40bb254e-8f4b-11e6-8be4-da454ca1767d.png)

Original:
![image](https://cloud.githubusercontent.com/assets/737603/19253433/4ed990ac-8f4b-11e6-8739-f82fd44cda1c.png)

The issue is that hanging rides block segments _before_ drawing supports.

**Comment by IntelOrca** [comment]
> The issue is that hanging rides block segments before drawing supports.

So all the ride paint code is wrong?

**Comment by marijnvdwerf** [comment]
Seems like it. Compare `mini_suspended_rc_track_flat` and `0x008AFE9C`. testpaint should probably be extended to included the state of gSupportSegments when comparing metal support calls.

**Comment by IntelOrca** [comment]
testpaint also needs to wrap the outer test loop with the inverted flag for multi-dimension coaster, flying and lay down

**Comment by Liampie** [comment]
Wooden coaster supports are also glitching now.

![de bedriegertjes 2016-10-11 15-40-47](https://cloud.githubusercontent.com/assets/19242088/19272527/38ac49c2-8fc9-11e6-83c7-dd2a68384d51.png)

**Comment by ArcticX9** [comment]
Also experiencing the wooden coaster supports issue and inversion/suspended coaster track support glitch both in singleplayer and multiplayer. It seems that any upside down track + diagonal wooden supports are affected.

**Comment by Broxzier** [comment]
Another hanging coaster that has support issues:
![image](https://cloud.githubusercontent.com/assets/9705046/22310359/4ec20cc2-e34f-11e6-9c68-97c9bf53e6ca.png)
For the suspense swinging coaster is only seems to apply to steep diagonal pieces. The non-diagonal steep pieces don't seem to have supports at all.

**Comment by marijnvdwerf** [comment]
@Broxzier Save file?

**Comment by Broxzier** [comment]
@marijnvdwerf: [Suspended Swinging Supports.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/731161/Suspended.Swinging.Supports.sv6.txt)

**Comment by duncanspumpkin** [comment]
Does the original part of this issue still occur. As far as i see hanging rides, wooden rollercoasters now draw correctly but the swinging coaster under #5148 still does not.

**Comment by Gymnasiast** [comment]
I just checked the rendering of the inverted, suspended swinging and mini suspended coasters in vanilla and OpenRCT2. They are now identical.
