### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by Gyoo** [OpenRCT2/OpenRCT2#4593]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 8cdfbf0

When I start the game, a white window opens and the game immediately crashes.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Use the config.ini file I've put in the dump below (It might be related to my game config)
2. Start the game

**Dump file**
[OpenRCT2.zip](https://github.com/OpenRCT2/OpenRCT2/files/521141/OpenRCT2.zip)

**Comment by BaryonQuark** [comment]
Affirmative here as well. Is i.m.h.o. related to the latest development commits. Yesterday all was working fine.

**Comment by Gyoo** [comment]
Alright then. I'll make sure to try it again in a few days after getting the new dev commits.

**Comment by janisozaur** [comment]
I'm not able to reproduce it, but I've made a well-looking fix, thanks @IntelOrca
