### ISSUE TITLE
Failed to build on MSVC 2015 Update 3, problem with file encoding

### ISSUE THREAD

**Issue by unclejimbo** [OpenRCT2/OpenRCT2#4596]
OS: Windows 10
Version: 0.0.5
Commit/Build:  b007aa9

Building generated an error and a warning:
1>f:\github\openrct2\src\platform\linux.c : error C2220: warning treated as error - no 'object' file generated
1>f:\github\openrct2\src\platform\linux.c : warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss

So I saved this file in Unicode (UTF-8 with signature) - Codepage 65001 format and everything compiled.

**Comment by janisozaur** [comment]
That sounds like a problem with your setup

**Comment by IntelOrca** [comment]
How did you checkout the source code? Perhaps your git config is wrong.

**Comment by unclejimbo** [comment]
It seems on line 249 of src/platform/linux.c
`// some commands may return a new-line terminated result, trim that…`
the last character, HORIZONTAL ELLIPSIS(…), is causing the problem.

This file is auto-detected as Western(Windows 1252) encoding. But I'm a Chinese so this character can't be represented by my system locale.

I could fix this problem by changing my default non-unicode program language to English, but it would be better to delete this character in order for other non-english/non-european users to compile by default.

**Comment by janisozaur** [comment]
```bash
$ file src/**/*.c | grep Unicode 
src/paint/map_element/surface.c:                   C source, UTF-8 Unicode text
src/platform/linux.c:                              C source, UTF-8 Unicode text
src/ride/track.c:                                  C source, UTF-8 Unicode text
```
File/line in question (so you can verify it displays in browser correctly): https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/platform/linux.c#L249

All of these files are properly encoded UTF-8 sources. We've had non-english, non-european contributors to the codebase and it never came up before, I believe the problem lies with your setup.

**Comment by IntelOrca** [comment]
If its just that ellipsis in a comment that is causing problems then I am fine for it to be removed

**Comment by AaronVanGeffen** [comment]
> Perhaps it needs to be UTF-8 with BOM.

One of the advantages of UTF-8 over UTF-16 and UTF-32 is that it doesn't need a BOM... You can still include one, I think, but that might cause more trouble than it potentially solves.

> If its just that ellipsis in a comment that is causing problems then I am fine for it to be removed.

That seems like the more sensible solution to me, too.

**Comment by unclejimbo** [comment]
Tried on another machine, Win10 system, same issue.
So I made a PR #4616 to delete it.
