### ISSUE TITLE
Assertion failed--visual c++ runtime library

### ISSUE THREAD

**Issue by pjmoy** [OpenRCT2/OpenRCT2#4604]
**OS:** W8.1
**Version:** 0.0.5
**Commit/Build:** 1526

 While I was browsing gentle rides, this error came up.
- [ ] Reproducible in RCT2 (vanilla)? unknown
- [ ] Multiplayer? Yes

**Steps to reproduce:**
1.  Run multiplayer and start server.
2.  browse gentle rides

**Screenshots / Video:**
[dropbox screen dump](https://www.dropbox.com/s/gp56blpk9g9hfsh/Screenshot%202016-10-11%2017.22.29.png?dl=0)

**Comment by pjmoy** [comment]
sorry, build 6cb9297

**Comment by Nubbie** [comment]
Could you provide the dumpfile from the crash? (if one got generated)

**Comment by janisozaur** [comment]
> Possibly a dupe of #4603

No, but I think there's already an issue about it.

**Comment by pjmoy** [comment]
No dump file that I can see; where would it be?

Just tell me what you want to see--I don't mind transcribing a screenshot if it helps.

**Comment by Nubbie** [comment]
Re-uploading pic for backup
![screenshot 2016-10-11 17 22 29](https://user-images.githubusercontent.com/17282384/28234370-2b04a99e-68ff-11e7-80a0-17d945d3d0d0.png)

**Comment by Nubbie** [comment]
No dumpfile, no savefile, seems like the issue might be dead
