### ISSUE TITLE
Water Rides Show Up in Water Rides Tab and Gentle Rides Tab

### ISSUE THREAD

**Issue by YoloSweggLord** [OpenRCT2/OpenRCT2#4608]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** dev build 0f695b3

In the object selection window and the build new ride/attraction window, water rides show up in both the water rides category and the gentle rides category. It's possible that it was always this way and I just never noticed it, but to my memory water rides were not included in the gentle rides category.

- Reproducible in RCT2 (vanilla)? IDK
- Multiplayer?

**Steps to reproduce:**
1. open either the object selection window or the build new ride window
2. water rides will appear in the gentle rides tab

**Screenshots / Video:**
![waterrides](https://cloud.githubusercontent.com/assets/19209095/19321229/2c6f4e48-9082-11e6-955c-90575cb36445.PNG)

**Comment by IntelOrca** [comment]
It will show a ride for every ride type the ride object specifies. Just like the new ride window.

**Comment by YoloSweggLord** [comment]
So, what you're saying is that I *was* mistaken about this, that they always were part of the gentle rides tab?
Oops, my bad.

**Comment by IntelOrca** [comment]
Well RCT2 didn't have ride category tabs for object selection. The ride window however exhibited the same behaviour.
