### ISSUE TITLE
Let mechanics fix destroyed props for money like a normal function (like fixing coasters)

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#4613]
https://openrct2.org/forums/topic/2098-fix-vandalism-at-cost/#comment-11224

**Comment by Gymnasiast** [comment]
The plan is to have handymen fix vandalised benched etc. (as they would in real life).
Closing this as the plan is already documented [on the wiki](https://github.com/OpenRCT2/OpenRCT2/wiki/Features-to-implement) (and has been put into issues multiple times anyway).
