### ISSUE TITLE
Guest/peep hover text not rendered on x64 build

### ISSUE THREAD

**Issue by Margen67** [OpenRCT2/OpenRCT2#4625]
**OS:** [Windows 10 x64]
**Version:** [0.0.5]
**Commit/Build:** [70c26b4]

When you hover your cursor over a guest/peep the text doesn't get rendered.
This doesn't happen in the 32 bit build.
It occurs on all parks, saves, scenarios, etc.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. (Not necessary, just makes it easier to reproduce) Click on guest/peep to open a window on them.
2. Hover your cursor over them and wait.
3. No text gets rendered.

**Dump file**
N/A

**Screenshots / Video:**
x64
http://i.imgur.com/kDt1X6V.png

x86/32 bit
http://i.imgur.com/o7PQbYP.png

**Save game:**
N/A

**Comment by RealRexen** [comment]
I'm gonna put this here but their carry items show no text also, was gonna open an issue for it but then I show this so I think it might be related 
![arid heights 2016-10-16 08-28-46](https://cloud.githubusercontent.com/assets/18408903/19417440/172c84e6-937b-11e6-8ca4-8c50c4cf3f80.png)

**Comment by Margen67** [comment]
That's odd. It only doesn't get rendered if it's next to an icon.
Carrying:
Nothing gets rendered fine and staff names do as well.
