### ISSUE TITLE
non-flat Queue line connections causes "heading-to-ride" stuck guests (can't find entrance)

### ISSUE THREAD

**Issue by MrMaestoso** [OpenRCT2/OpenRCT2#4626]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 70c26b4

I've been experiencing this bug for several days, but I finally discovered the culprit.  It is somewhat related to #4557  but I wasn't able to find another report here specifically for this.

When a Queue path approaches/connects to a normal path from a level up (and probably down) from the main path (i.e. not flat), guests will not be able to find it if "heading to".  The guests end up in an area somewhere in the park and get stuck in a "heading to 'ride'" loop.  Rebuilding the queue connection as a flat approach immediately fixes it.

This happens on the maps I've played so far, so it should be easily reproducible.  I'll check back in case more info is needed.  I also do not know if this is an original bug.

Also, sorry if there actually is an issue listed for this that I missed.  Thanks for y'all's hard work.

**Comment by zaxcav** [comment]
I'll look into it.
