### ISSUE TITLE
Empty ride preview

### ISSUE THREAD

**Issue by Gyoo** [OpenRCT2/OpenRCT2#4627]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 70c26b4

When I want to build a new coaster that has a list of saved rides, all the previews show nothing : neither the track preview nor the associated stats.
- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Load any map
2. Try to build a coaster with saved rides (Wooden Rollercoaster is a safe choice)
3. Witness the lack of preview

**Dump file**

**Screenshots / Video:**
![openrct2_2016-10-16_11-20-45](https://cloud.githubusercontent.com/assets/3592205/19416527/437c9eb0-9393-11e6-8d96-ffceb79d0aeb.png)

**Save game:**

Since it is not related to a save in particular, here's my config instead.
[config.txt](https://github.com/OpenRCT2/OpenRCT2/files/531675/config.txt)

**Comment by IntelOrca** [comment]
Don't use OpenGL

**Comment by Gyoo** [comment]
That works. It should probably still be fixed for OpenGL doesn't it ?

**Comment by IntelOrca** [comment]
It's a known issue that isn't trivial to solve at moment.

**Comment by Gyoo** [comment]
Alright then, thanks for your quick reply :)

**Comment by Nubbie** [comment]
@IntelOrca Close as it's a known bug?

**Comment by IntelOrca** [comment]
@Nubbie It's a known issue that isn't trivial to solve at moment.

**Comment by Nubbie** [comment]
https://github.com/OpenRCT2/OpenRCT2/wiki/OpenGL-renderengine-issues

**Comment by janisozaur** [comment]
@IntelOrca we could detect OpenGL and display a string "Preview unavailable with OpenGL" in that window.

**Comment by IntelOrca** [comment]
@janisozaur yes, someone is welcome to do that

**Comment by Nubbie** [comment]
There was a question about this on the forums, it should at least be marked with the 'OpenGL' lable
https://openrct2.org/forums/topic/2214-preview-of-tracks-is-missing/
