### ISSUE TITLE
Change autosave location

### ISSUE THREAD

**Issue by doeni0** [OpenRCT2/OpenRCT2#4628]
**OS:** [Windows 10]

Is it possible to change the autosave location ? By default, it is %userprofile%\documents\OpenRCT2. This is on my HDD. I'd like to have it on the SSD without changig the path of my complete documents folder.

**Comment by IntelOrca** [comment]
You can pass a command line argument to OpenRCT2:
`openrct2.exe --user-data-path D:\somewhere\OpenRCT2`

All user data will be there, e.g. custom tracks, scenarios, screenshots etc.

**Comment by Gymnasiast** [comment]
You can also symlink the folder to one on your SSD.

**Comment by doeni0** [comment]
That was fast, thank you.
