### ISSUE TITLE
Display Resolution Incorrectly Scaled

### ISSUE THREAD

**Issue by GForceNE** [OpenRCT2/OpenRCT2#4631]
**OS:** [Windows 10]
**Version:** [0.0.5]
**Commit/Build:** [5b9f790]

The resolution of the game is scaled down an incorrect.

- [No] Reproducible in RCT2 (vanilla)?
- [Yes] Multiplayer? 

**Steps to reproduce:**
1. Open Game

**Screenshots / Video:**
![image](http://i.imgur.com/qzy4Tbc.png?1)
Screen on right, is OpenRCT in incorrect resolution.  Screen on left, is the correct resolution of vanilla.
![image](https://cloud.githubusercontent.com/assets/18511011/19419572/600287f6-93a8-11e6-9755-d68d4d3c7d09.png)
Settings used

This issue occurred after updating to a new development build on 10/15/16, no settings were changed by me.  Resolution simply became scaled down and cannot be reverted.

**Comment by marijnvdwerf** [comment]
Can you post a screenshot of your windows display settings ([this screen](http://core0.staticworld.net/images/article/2015/07/settingscaling1-100598954-orig.png))?

**Comment by GForceNE** [comment]
![image](https://cloud.githubusercontent.com/assets/18511011/19419738/114e0320-93ac-11e6-8a28-9d59770ecdb4.png)

I did not change these settings to my knowledge.  Nothing else on my PC has been changed except for OpenRCT.

**Comment by marijnvdwerf** [comment]
Was just making sure that the display scale wasn't set to 100%.

@GForceNE A quick fix for you could be to change the OpenRCT2 settings.
Set 'Window scale factor' to 1.25, and set the 'Drawing Engine' to 'Software (Hardware Display)'

@janisozaur Now would probably be a good time to implement that `platform_get_default_scale` stuff, though imho a neater solution would be to apply the game-configured scale on top of the OS-wide display scale. Would work better with multiple displays with different scales.

**Comment by IntelOrca** [comment]
This is a non-bug, the game will always be 1:1 scale with your native resolution, regardless of the operating system's DPI setting. If you want to make it look bigger you increase the window scale factor or use traditional fullscreen with a lower resolution.

**Comment by GForceNE** [comment]
Thank you @marijnvdwerf that changed fixed my issue.
