### ISSUE TITLE
Flying roller coaster station bug

### ISSUE THREAD

**Issue by CameronW1** [OpenRCT2/OpenRCT2#4637]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** dd3db11

- [x] Reproducible in RCT2 (vanilla)? RCT2 on steam Crashes nonstop
- [x] Multiplayer? Both

**Steps to reproduce:**
1. Select Flying Roller Coaster
2. Build station -noticed incorrect track drawing
2a. You will notice that the track is incorrectly showing a Twister Roller Coaster track instead of a modified Inverted track.

**Screenshots / Video:**

![mozar s free4all 2016-10-17 23-24-50](https://cloud.githubusercontent.com/assets/18614161/19427342/a6ee18b2-9400-11e6-8873-6e6f4ddff45b.png)

**Comment by CameronW1** [comment]
Using the Track/ride changing cheat doesn't fix the bug either. Nor did reinstalling RCT2 and OpenRCT2.

**Comment by duncanspumpkin** [comment]
It's a paint setup bug. We recently implemented all of the painting and it seems we missed this rides station just hang tight and it will be fixed soon
