### ISSUE TITLE
Game crashes on loading save file

### ISSUE THREAD

**Issue by habahut** [OpenRCT2/OpenRCT2#4656]
**OS:** Windows 10
**Version:** .0.0.4 (stable)

- The save file crashes in the original RCT2 as well, though I created it using openRCT2.

**Steps to reproduce:**
1.  Open the save file
2. Zoom out will usually crash the game. It may take a minute or two of playing around and working on the unfinished coaster in progress on the screen at load.

**Dump file**
I don't know how to get the debug logs, if you tell me how I can produce them.

[Harbor One.zip](https://github.com/OpenRCT2/OpenRCT2/files/537889/Harbor.One.zip)
**Save game:**

**Comment by Nubbie** [comment]
Does crash in stable **but no in latest develop** 315c0e9

**Comment by IntelOrca** [comment]
I didn't see that it was stable, yeah ok then its probably a corrupt track or something.
