### ISSUE TITLE
Improve file save dialog

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#4658]
There are four text buttons in the load/save dialog. This looks a bit cluttered and doesn't fit the RCT theme. The text should be replaced with icons.

**Comment by AaronVanGeffen** [comment]
The window has been revamped since. Personally, I think it looks fine as-is. Do you agree?

**Comment by Gymnasiast** [comment]
Hm, the text-only buttons would still benefit from becoming icons, but it has improved indeed.
