### ISSUE TITLE
VSync

### ISSUE THREAD

**Issue by Nubebuster** [OpenRCT2/OpenRCT2#4665]
I noticed that the standard fps in OpenRCT is 40fps
When I go through the map it looks slightly stuttering.
My monitor supports 60 fps and running on 160 (uncapped fps) makes no sense.
Wouldn't it make sense if there was a vsync option?

**Comment by IntelOrca** [comment]
If you set your renderer to software (hardware display), you will get v-sync.

**Comment by RealRexen** [comment]
I may be wrong but doesn't V-sync cause fps drop?

**Comment by kingcailan** [comment]
V-sync locks the frames displayed by your game to your monitor's refresh rate, and forces your card to display them "in sync" with your monitor. It is meant to relieve stuttering and frame tearing. It SHOULDN'T decrease FPS below your refresh rate unless the "V-sync" implimentation is actually just a frame limit set by the game. The only downside of V-sync is some negligible input lag.
