### ISSUE TITLE
Handyman removes invisible guest produced by crash

### ISSUE THREAD

**Issue by ghost** [OpenRCT2/OpenRCT2#4670]
**OS:** Windows 7, GNU/Linux
**Version:** 0.0.5
**Commit/Build:** 2aac1dd
- [x] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

We were testing the handymen sweeping up litter with the Lisa Stirling cheat and the game crashed for the host.
The save that was produced from the crash contains an invisible guest who is able to be sweeped up by the handyman and is removed from the game.

**Steps to reproduce:**
1. Load the save and watch a handyman sweep the guest named LISA STIRLINg.

**Dump file**
[fc5a8931-cd6d-4897-9933-87c5a93e28f5(2aac1dd_x86).dmp.zip](https://github.com/OpenRCT2/OpenRCT2/files/544422/fc5a8931-cd6d-4897-9933-87c5a93e28f5.2aac1dd_x86.dmp.zip)
**Screenshots / Video:**
![crazy castle 2016-10-21 09-36-42](https://cloud.githubusercontent.com/assets/12518502/19600235/23fa79c6-9772-11e6-9b7b-1876b3a88d62.png)
![crazy castle 2016-10-21 09-37-00](https://cloud.githubusercontent.com/assets/12518502/19600233/23f079f8-9772-11e6-80c9-d37278f66f6b.png)
![crazy castle 2016-10-21 09-37-08](https://cloud.githubusercontent.com/assets/12518502/19600234/23f79d6e-9772-11e6-83f9-93af05c81876.png)

**Save game:**

[fc5a8931-cd6d-4897-9933-87c5a93e28f5.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/544421/fc5a8931-cd6d-4897-9933-87c5a93e28f5.sv6.zip)

**Comment by Nubbie** [comment]
Poor Lisa 😢 

Extracted from dumpfile fc5a8931-cd6d-4897-9933-87c5a93e28f5(2aac1dd_x86).dmp

**Error message;**
Unhandled exception thrown: read access violation.
sprite_idx was 0x26AC37A.

**Call stack;**
```
>	openrct2.exe!sprite_move(short x=-32768, short y=0, short z=0, rct_sprite * sprite=0x016cdf78) Line 530	C
 	openrct2.exe!peep_pickup(rct_peep * peep=0x016cdf78) Line 1895	C
 	openrct2.exe!peep_pickup_command(int peepnum, int x=0, int y=0, int z=0, int action=0, bool apply=true) Line 2029	C
 	openrct2.exe!game_command_pickup_guest(int * eax=0x0015f6c4, int * ebx=0x0015f6c0, int * ecx=0x0015f6d0, int * edx=0x0015f6d4, int * esi=0x0015f6d8, int * edi=0x0015f6dc, int * ebp=0x0015f6e0) Line 2039	C
 	openrct2.exe!game_do_command_p(int command=68, int * eax=0x0015f6c4, int * ebx=0x0015f6c0, int * ecx=0x0015f6d0, int * edx=0x0015f6d4, int * esi=0x0015f6d8, int * edi=0x0015f6dc, int * ebp=0x0015f6e0) Line 526	C
 	openrct2.exe!game_do_command(int eax=539, int ebx=-2147483647, int ecx=0, int edx=0, int esi=68, int edi=0, int ebp=0) Line 435	C
 	openrct2.exe!Network::Server_Handle_GAMECMD(NetworkConnection & connection, NetworkPacket & packet) Line 1656	C++
 	openrct2.exe!Network::ProcessPacket(NetworkConnection & connection, NetworkPacket & packet) Line 1171	C++
 	openrct2.exe!Network::ProcessConnection(NetworkConnection & connection) Line 1137	C++
 	openrct2.exe!Network::UpdateServer() Line 374	C++
 	openrct2.exe!rct2_update(...) Line 444	C
 	openrct2.exe!openrct2_loop(...) Line 416	C
 	openrct2.exe!openrct2_launch(...) Line 344	C
 	openrct2.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 74	C
```

**Autos;**
```
+		&sprite2->unknown	0x026ac378 {sprite_identifier=??? misc_identifier=??? next_in_quadrant=??? ...}	rct_unk_sprite *
+		&sprite2->unknown.next_in_quadrant	0x026ac37a {???}	unsigned short *
+		sprite	openrct2.exe!0x016cdf78 {pad_00=0x016cdf78 "ÿ" unknown={sprite_identifier=255 'ÿ' misc_identifier=0 '\0' ...} ...}	rct_sprite *
+		sprite2	0x026ac378 {pad_00=0x026ac378 <Error reading characters of string.> unknown={sprite_identifier=??? misc_identifier=...} ...}	rct_sprite *
+		sprite_idx	0x026ac37a {???}	unsigned short *
```

**Locals;**
```
		current_position	Variable is optimized away and not available.	
		new_position	65536	int
+		sprite	openrct2.exe!0x016cdf78 {pad_00=0x016cdf78 "ÿ" unknown={sprite_identifier=255 'ÿ' misc_identifier=0 '\0' ...} ...}	rct_sprite *
+		sprite_idx	0x026ac37a {???}	unsigned short *
+		sprite2	0x026ac378 {pad_00=0x026ac378 <Error reading characters of string.> unknown={sprite_identifier=??? misc_identifier=...} ...}	rct_sprite *
		temp_sprite_idx	Variable is optimized away and not available.	
		x	-32768	short
		y	0	short
		z	0	short
```

**Comment by Chaosmeister** [comment]
I'm unable to reproduce the crash.

**Comment by Gymnasiast** [comment]
As of https://github.com/OpenRCT2/OpenRCT2/commit/c0eade9c88ec95882a20bf1959b5c8d69248371b , the guest is no longer swept up. Whether the source of the corruption is solved is hard to tell, but it has been five years, so assuming it is.
