### ISSUE TITLE
Can not move Pre-invented rides to invented during the game in the scenario editor

### ISSUE THREAD

**Issue by BlackendSun** [OpenRCT2/OpenRCT2#4680]
**OS:** Windows 10
**Version:** 0.05
**Commit/Build:** 88ccfad (Seen in earlier builds)

You can't move any ride that is under Pre-invented. While you can move rides from the Invented during the game to the Pre-Invented, you can't move them back.
- [ ] Reproducible in RCT2 (vanilla)? No
- [ ] Multiplayer? No

**Steps to reproduce:**
1.  Open a new park in the Scenario Editor 
2. Go to the inventions list.
3. Try moving rides from the Pre-invented to the Invented during the game.

**Comment by Gymnasiast** [comment]
Not reproducible on a0fb955102b89f2104effc7552415a9a61d36593.
