### ISSUE TITLE
Mechanics won't stay in assigned area

### ISSUE THREAD

**Issue by Charlieep** [OpenRCT2/OpenRCT2#4682]
**OS:**windows 10]
**Version:** 0.0.0.5
**Commit/Build:** 91d4058

1. Mechanics do not stay within their assigned area. They will take a call when they are on the other side of the park and then take the long way around. 
2> If you have rotated the entrance and/or exit using the cheat, they will NOT enter and repair. They simply go up to the edge and turn around and leave with the "Heading for ...." still live.

- [ ] Reproducible in RCT2 (vanilla)? no

**Steps to reproduce:**
1. Place mechanic in assigned area and wait
2. 

[mechanics.zip](https://github.com/OpenRCT2/OpenRCT2/files/546071/mechanics.zip)

**Save game:**

**Comment by Gymnasiast** [comment]
Please provide more information: things like a screenshot, a description, a saved game.

This is not the first time we have asked you to properly fill in the issues. It's hard to help you this way and it's also getting really annoying.

**Comment by IntelOrca** [comment]
@Gymnasiast if you click edit, you'll see the information has been placed in a comment.

**Comment by Gymnasiast** [comment]
@IntelOrca Which I cannot consider 'properly filling in the issue'.

**Comment by IntelOrca** [comment]
@Gymnasiast I just thought I'd let you know

**Comment by Charlieep** [comment]
Here is a screenshot showing the ride, his assigned area and where he is!
![131b - venice river delta 2016-10-24 11-56-08](https://cloud.githubusercontent.com/assets/19598196/19655368/3986aa32-99e1-11e6-95a6-6fd1f5dd331e.png)

**Comment by Charlieep** [comment]
did not want to close this

**Comment by Charlieep** [comment]
did not want to close this
Here is a screen print showing the ride, the assigned area and where he currently is.

![131b - venice river delta 2016-10-24 11-56-08](https://cloud.githubusercontent.com/assets/19598196/19655486/b715ed0a-99e1-11e6-9e4e-f25ca97f3fb3.png)

**Comment by Charlieep** [comment]
Here is another game with the same problem. After doing some investigating the only thing these two have in common is both have had their entrances and exits rotated using the tile inspector and both have clearance checks enabled for a short period of time.
![186a - weeping willow woods 2016-10-24 16-40-44](https://cloud.githubusercontent.com/assets/19598196/19665121/1a9e839c-9a09-11e6-987e-3ff294b98531.png)
[mechanics2.zip](https://github.com/OpenRCT2/OpenRCT2/files/549083/mechanics2.zip)

**Comment by Charlieep** [comment]
Some additional info. The ride Purple Challenge (mechanics2) was a saved ride and placed with the exit path on the existing path. The ride functioned properly with peeps entering and exiting ok. After reading some discussion of the forum, I placed a NEW path on top of the one at the exit and the mechanic turned around went to the exit and repaired the ride. That exit is its normal state. These are the first two games I have played since September 28 and I don't remember having this problem before then. I know that when you rotate an entrance or exit you must place/replace the path tile directly in front. Hope this helps.

**Comment by zaxcav** [comment]
Regarding point #2: Rotated ride exits (and ride exits in general) can only be entered if the path is properly connected to the ride .
The old hack that sent the mechanic to the path next to the ride exit and then directed him into the exit regardless of the path connections has recently been removed from the pathfinding.  Now the mechanic is sent to the ride exit itself and needs the path to be properly connected. Either replace the path after rotating the ride exit, or manually connect the path using the tile inspector.

**Comment by Charlieep** [comment]
@zaxcav placing a new path on TOP of the existing path solved the problem of mechanics getting to the ride and I see you have opened an issue on staying within assigned areas, so I am going consider this closed.
