### ISSUE TITLE
Assertion failed!

### ISSUE THREAD

**Issue by jamtraks** [OpenRCT2/OpenRCT2#4684]
**windows vista 32-bit** 
**Version:** 
**build: 1592 Hash: 91d4058** 

When in a particular park of mine i attempt to use "object selection" to select and de-selct rides; mainly select _more_ rides. Within about 20 to 30 seconds of doing so the game crashes and gives me this message:

[ Assertion failed!
Program: C:\Users\Josh\Documents\Openrct2\bin\openrct2.exe
File:src\localisation\localisation.c
Line:1280

Expression:false

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled) ]
- [did not try in vanilla]
- [did not try in multiplayer]

**Steps to reproduce:**
1. 
2. 

**Dump file**
none

**Screenshots / Video:**
none

**Save game:**
none

**Comment by jamtraks** [comment]
For some reason i don't seem to be having this particular problem any more

**Comment by Margen67** [comment]
Why are you still using Windows Vista?

**Comment by jamtraks** [comment]
because i can't afford a new computer or even a new operating system at the moment. What do you suggest i upgrade to?

**Comment by jamtraks** [comment]
By the way i suddenly had this issue again just now.

**Comment by Gymnasiast** [comment]
@Margen67 Why someone still uses Vista is irrelevant. We support it, and it is technically very similar to Windows 7, 8 and 10. (The difference between Vista and 10 is smaller than the difference between XP and Vista.)
(@jamtraks Windows 8 and 10 are lighter than Vista, so your computer will probably be able to handle it. But it isn't necessary, as I just said)

Ok, now back on-topic please. @jamtraks , could you try to find a way to reliably reproduce this error?

**Comment by jamtraks** [comment]
It happens when i am scrolling up and down the list of objects after selecting "object selection". It sometimes happens, and sometimes doesn't but now, if it does, i just press "ignore" several times and the "assertion failure" window goes away, and i'm back to normal game play. While this is a bit annoying, hitting "ignore" several times does seem to fix the problem almost 99-100% of the time.

**Comment by janisozaur** [comment]
It does not fix the problem.

**Comment by jamtraks** [comment]
Was that a question or a statement?"it does not fix the problem"... Well what i'm saying is it does fix the problem. I have to press "ignore" ten times in a row, then the game screen shrinks and expands ten times in a row. I have to wait a few moments for it to go through this process. It's really inconvenient but it does get around the problem.

**Comment by mrtnptrs** [comment]
@jamtraks Shorter version of your last comment: "ignore" is a workaround, but doesn't fix the problem itself.

**Comment by IntelOrca** [comment]
@jamtraks it might be caused by a certain object in the object list, if you could find out which one - that would be useful.

We can stop the message from appearing altogether, but I am curious as to what is causing it - as its most likely a bug.

**Comment by janisozaur** [comment]
@IntelOrca change it to `openrct2_assert` to have it produce dump?

**Comment by IntelOrca** [comment]
@janisozaur it does, you just have to click retry.

**Comment by jamtraks** [comment]
I just tested the problem once more after my launcher updated my version of orct2. I am not noticing a problem yet...  I can tell you that i selected invisible pizza, invisible food, gopher game, depot circus souvenir, mv map stall, flying saucers...    Ahh ! but i see just resting the mouse on "firebolt broom vroom" seems to be triggering the error now. Also "butterbeer hangover". also "aragog's lair" from what i can tell it's only those three objects causing a problem and nothing else that i have... I don't have to select them to get the error, i get the error simply by resting the mouse on them to show their picture/description in the right side window, that's when the error occurs.

**Comment by jamtraks** [comment]
also "tumble bug peeps always on"

**Comment by jamtraks** [comment]
I just realized, i have only checked the rides/stalls for errors, i haven't checked any of the "advanced" objects like building objects scenery etc... i may try to do this if i have the time, but there's a chance that none of these will cause errors and there seem to be thousands.

**Comment by jamtraks** [comment]
is this bug exclusive to me and my operating system or are others experiencing the same problem? I ask this because you are suggesting i update my operating system.

**Comment by Gymnasiast** [comment]
@jamtraks No, your bug is **not** exclusive to your OS and even if it were, it would be a bug to fix. It was an irrelevant question from someone outside the team. 
And that is the final word on your OS version. I want to stay on-topic.

**Comment by tcek** [comment]
I'm experiencing the exact same problem my man. It's got to point for me that I can't choose any rides anymore. Within 5 seconds of being on Object Selection, I get the Assertion Failed! I posted my own issue as well, so hopefully something can be done. I love this game and I appreciate all the hard work the team has put in to make it even better - this bug however, is very annoying, lol. Thanks.
