### ISSUE TITLE
Too high for supports: Raging Rockets RCT1

### ISSUE THREAD

**Issue by Horsti12** [OpenRCT2/OpenRCT2#4686]
You can't place Raging Rocket.TD4 in a flat map because of the support limits.
**OS**: Windows 10 Pro
**Version:** v0.0.5-develop build 667dd52 Windows (x86)
- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Put the Raging Rocket.TD4 file into the tracks folder
2. Try to place it on a flat map. 
3. Too high for supports error will be on the screen

**How to fix this**
Extend the support limit from 16.5m to 20m as it was in RCT1. So that we can import every old track design from RCT1 which was higher than 16.5m

**Screenshots / Video:**
![six flags 2016-10-23 16-05-21](https://cloud.githubusercontent.com/assets/12634026/19626941/c7691326-993c-11e6-97ec-755dfb52ef54.png)

**Comment by AaronVanGeffen** [comment]
As a workaround, you can disable support limits through the cheats window.

**Comment by ZxBiohazardZx** [comment]
Can you reproduce this on vanilla RCT2? i believe there is a difference between some rides, the junior coaster had a few features on RCT1 that did not make it into RCT2 and RCT2 had some different parts that didnt exist in 1. My point is that the support limits might be correct given RCT2 but not consider RCT1 designs that required the extra height. Solution is mentioned by @AaronVanGeffen: disable support limit checks temporarily via cheats menu

**Comment by Gymnasiast** [comment]
No, that's not a solution. It's a workaround. We have stated the express goal of reintroducing cut RCT1 features to OpenRCT2, and this is no exception. The limit will be raised to what it was in RCT1.

**Comment by IntelOrca** [comment]
> The limit will be raised to what it was in RCT1.

Isn't the limit set by the DAT? Isn't it better to just allow track designs to place ignoring support limits?

**Comment by Gymnasiast** [comment]
@IntelOrca There is a max_height attribute for every track type: https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/ride/ride_data.h#L94 

By the way, ignoring support limits when placing a track design and raising it in the track type data isn't mutually exclusive. We could easily do both, as raising the limit also allows building Junior RCs at RCT1 heights from scratch.
