### ISSUE TITLE
Ride ratings not available

### ISSUE THREAD

**Issue by remcooo96** [OpenRCT2/OpenRCT2#4695]
OS: MacOS 10.12
Version: [e.g. 0.0.5]
Commit/Build: f349fbf

When I build a new ride or attraction, the ride ratings are not calculated, just the stats.
Despite that, the ratings could be calculated, enought guest did the ride to be able calculate.
I found a strange 'solution': by removing all guests in the park and reopening the ride, the ratings immediately pop up.

Maybe something with a sprite limit or something?
I've added my savegame, I built a test rollercoaster so you can see what happens when guests are removed from the park.

[Astoria100.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/547477/Astoria100.sv6.zip)

- [?] Reproducible in RCT2 (vanilla)?

**Comment by duncanspumpkin** [comment]
Ride ratings are not something that is calculated immediately after testing. Its done a few at a time every game loop to prevent slow downs. You likely have some ride that is blocking ride ratings from being calculated.

**Comment by remcooo96** [comment]
Every new ride I have built has the problem, rollercoasters, monorails, everything. Even tested one for 2 game years.

**Comment by IntelOrca** [comment]
Do you have any hacked rides? Any that have merged tracks or anything as this can cause one ride to block the rating calculator.

**Comment by remcooo96** [comment]
Just a hanging monorail with an extra long train (7 coaches). Beside that nothing.

**Comment by IntelOrca** [comment]
I'll take a look later

**Comment by remcooo96** [comment]
any ideas yet? :)

**Comment by IntelOrca** [comment]
It is stuck calculating the rating for `'t Melkhuysje`. Its just stuck in a loop and its because its getting confused with the vertical coaster.

I could fix this by limiting it to just tracks owned by the ride the rating is for... but that will break ratings from being calculated for every roller coaster that uses track merging with another.

I'd just delete that shop for now.

**Comment by remcooo96** [comment]
Thanks for your Help! I would never have discovered that this shop was the problem :)
