### ISSUE TITLE
Tile segments don't get blocked like in vanilla

### ISSUE THREAD

**Issue by GForceNE** [OpenRCT2/OpenRCT2#4698]
**OS:** [Windows 10]
**Version:** [0.0.5]
**Commit/Build:** [3d529ff]

Steel coaster supports do not correctly match the vanilla version.  Probably a result of object layering not being correct, but I'm not certain of this.
- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Certain parks built only in Vanilla do not have supports correctly rendered in Open, often times when there are other objects on the tile or track pieces on the tile that could have blocked the support in Vanilla.  (Bug exists on all the steel coasters on this map)
2. Bug also exists in multiple other parks, if you would like another example, let me know.  This is just the map where its most prominent.

**Screenshots / Video:**
Screenshot in OpenRCT
![image](https://cloud.githubusercontent.com/assets/18511011/19670747/bf0dd85a-9a37-11e6-80b9-58592fa3863f.png)
Screenshot in Vanilla
![image](https://cloud.githubusercontent.com/assets/18511011/19670762/e1f1135a-9a37-11e6-904f-1e22f21dc9d5.png)

**Save game:**

[Starpointe(SupportGlitch).zip](https://github.com/OpenRCT2/OpenRCT2/files/549471/Starpointe.SupportGlitch.zip)

**Comment by marijnvdwerf** [comment]
@duncanspumpkin Might be a bug in `scenery_paint`? There's a flower field in the bottom quarter segment, and a support gets attached to the bottom segment as well. Probably shouldn't be happening.
![image](https://cloud.githubusercontent.com/assets/737603/19681486/da440d3e-9aa9-11e6-8ff6-19deca670d19.png)

**Comment by GForceNE** [comment]
Hmm, I think its more a result of the track than the scenery on the tile.  If I delete the bush in vanilla the support doesn't appear.  Besides, there are supports on the tiles without any visible scenery objects below.

But, on some of the other coasters in the park it seems that there are supports appearing despite there being scenery objects on the tile.  Such as the floorless or impulse coasters.  Perhaps it's due to multiple things.

In the recent past this park rendered fine. Just seems that it recently had gone wrong.

**Comment by marijnvdwerf** [comment]
Some supports will change in shape a bit, because they were previously inconsistent (as in, the different angles showing different 3D behavior). But this seems a bit odd. Also, the tile inspector says there's a support-blocking object, so that might be the reason for it not changing stuff in Vanilla.

![image](https://cloud.githubusercontent.com/assets/737603/19689309/4274e87e-9acd-11e6-892f-83b334ab5e9a.png)

**Comment by GForceNE** [comment]
The support seems to be coming from the track that is below the support blocker, so I'd have to guess that there is some layering difference between the two versions that result in the difference?  Perhaps the support rendering priorities are different between the two games?

Sorry, probably won't be much help on why this issue is happening.  Just throwing stuff out there.

**Comment by GForceNE** [comment]
Here is another example, the red supports do not appear in vanilla.
![image](https://cloud.githubusercontent.com/assets/18511011/19706770/b337a894-9ae1-11e6-81e4-af1996fb8958.png)
[Westwinds(supportsbug).zip](https://github.com/OpenRCT2/OpenRCT2/files/551944/Westwinds.supportsbug.zip)

**Comment by GForceNE** [comment]
A different coaster type, but a similar issue:
![image](https://cloud.githubusercontent.com/assets/18511011/19872589/f2fb317c-9f90-11e6-9481-cf076c6c5e91.png)
The red supports should not appear, see the vanilla version:
http://www.nedesigns.com/park/1907/map/1684/voyager/

DL Link on this page:
http://www.nedesigns.com/park/1907/voyager/

Sorry for the overload of screens, but this is an important fix I think as it effects many many Vanilla park (and even some OpenRCT built parks).

**Comment by marijnvdwerf** [comment]
Still happens when original track drawing is used, so likely due to `scenery_paint`
