### ISSUE TITLE
Deleted tracks and other files

### ISSUE THREAD

**Issue by pballer7** [OpenRCT2/OpenRCT2#4705]
This is more of a computer issue, rather than an openrct2 issue. 

The other day I somehow reset the regular rct2.exe file and got rid of everything on it, by accident. Luckily, the scenarios and parks were saved on the OpenRCT2 game, but all my saved, custom-build roller coasters got deleted. Is there any way to restore some of the deleted data from RCT2?

**Comment by jamtraks** [comment]
i don't know is there?

**Comment by jamtraks** [comment]
*.*

**Comment by Nubbie** [comment]
@pballer7 
Do the things jamtraks said first

If that doesn't work, you could always download a program to recover deleted data like the free program I use, ['Recurva'](https://www.piriform.com/recuva) (Made by the people who made CCleaner)
Then just tell it to search for files with RCT2 extentions, for example .td6
