### ISSUE TITLE
confusion with launcher update

### ISSUE THREAD

**Issue by jamtraks** [OpenRCT2/OpenRCT2#4706]
**vista 32-bit:**
**0.0.5 launche v.6** [e.g. 0.0.5]
**na** 

My launcher was telling me "a new launcher (version 6) is available please download at github.com "address here"
-The page was not telling me weather i need to uninstall the current launcher first or not and i wish that your site would have simply stated that i don't have to worry about uninstalling, but it didn't. I was told at orct2.org that i _should_ uninstall first so i uninstalled the old launcher and reinstalled the new launcher. The update was also attempting to give me, with no option, the newer version of microsoft visual c++. I was not told by your page weather i should or needed to uninstall the current version of c++ first or not either. Soon after updating i encountered some unusual errors that may or may not have been related to the update, but in worry, i performed a system restore which mainly brought back my older version of c++. Things are working alright now but i am encountering more errors than usual in the orct2 software. I currently have both microsoft visual c++ (x86) - 14.0.23026 (524kb) and the newer, microsoft visual c++ - 14.0.24215 (x86) (808 kb) installed both. Is it okay or good too have both installed or should i only have the newer or older one?

**Comment by janisozaur** [comment]
This is not the place to report issues with launcher.

**Comment by Nubbie** [comment]
@jamtraks You can post this issue on the launchers page; https://github.com/LRFLEW/OpenRCT2Launcher/issues
