### ISSUE TITLE
Extension of errors im having

### ISSUE THREAD

**Issue by jamtraks** [OpenRCT2/OpenRCT2#4707]
os version: windows vista 32-bit
build:496 hash: 1eb91cb

-park will not open in vanilla

When i edit objects in this park of mine "extreme heights 1.52"  (play around for about five minutes or so), and then go to the ride "black magic" near my entrance, which is actually an altered "glowworm" which i renamed, the sign that says "black magic" changes to just say "sign". when i right click the sign to rename it to "black magic" i get a crash.

Update: -I've discovered a constant in this error. If I add an entryway or "do not enter" sign anywhere in this park of mine, the sign for "black magic" and only the sign for "black magic" changes to just "sign". If i right click this sign to rename it back to "black magic", i get a crash. This has happened every time i have tested this. But, if i erase the sign first, and then add an entry way/do not enter sign, and then add the "black magic" sign again there is no crash.

Park File:
[Extreme Heights By Josh Marsilio1.52.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/552586/Extreme.Heights.By.Josh.Marsilio1.52.sv6.zip)
dump file:
[f6dad69c-dc0e-4e9f-a2fe-6f9000cb0f18.zip](https://github.com/OpenRCT2/OpenRCT2/files/552590/f6dad69c-dc0e-4e9f-a2fe-6f9000cb0f18.zip)

**Comment by mrtnptrs** [comment]
Please mention the OS, version and build!!! Never just delete the issue template and start typing.

**Comment by IntelOrca** [comment]
@jamtraks please switch to the develop builds as the stable ones are very out of date now, many of the bugs you encounter are likely fixed.
