### ISSUE TITLE
"Escape Hatch" Launched Freefall design deletes paths during placement

### ISSUE THREAD

**Issue by DavidMaza** [OpenRCT2/OpenRCT2#4709]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 5699b9e

**Steps to reproduce:**
1.  When placing the "Escape Hatch" Launched Freefall design, paths are deleted.

**Screenshots / Video:**
https://vid.me/71PS

Only the mouse is being moved in the video. No keys on the keyboard are being pressed and the mouse isn't being clicked.

**Save game:**
[Park Maharaja.zip](https://github.com/OpenRCT2/OpenRCT2/files/553099/Park.Maharaja.zip)

Not using any plugins or modifications.

**Comment by IntelOrca** [comment]
Did you have 'disable clearance checks' on? I expect so since I can't reproduce it without that.

**Comment by DavidMaza** [comment]
I wasn't using using any cheats or the disable clearance checks option.

I only saw it using the Escape Hatch Launched Freefall design. It worked normally using a custom design or any other type of ride. 

I restarted my game a few times and was able to reproduce it fairly consistently. Sometimes it didn't start deleting paths immediately, but rather after 3 or 4 seconds of moving the cursor around.

**Comment by DavidMaza** [comment]
Also I was using OpenGL, if it makes a difference.

**Comment by IntelOrca** [comment]
I can't reproduce it unless I enable disable clearance checks. It will always just place the ride above the path.

**Comment by duncanspumpkin** [comment]
I can't reproduce this even with disabled clearance checks on. Can you reliably reproduce this every time, every save?

**Comment by DavidMaza** [comment]
I can reliably reproduce it in Park Maharaja with Open GL.

With Software Rendering or when in other parks, I cannot reproduce it.

**Comment by duncanspumpkin** [comment]
Thats very odd. OpenGL has no relation to this code that is breaking.

**Comment by DavidMaza** [comment]
Below is another video which shows the different results between OpenGL and Software rendering:

https://vid.me/pC5P

**Comment by rwjuk** [comment]
@DavidMaza Can you check whether this still occurs in the latest build? Thanks.

**Comment by DavidMaza** [comment]
I can still reproduce it in build d56dd24, but only in OpenGL mode.

**Comment by duncanspumpkin** [comment]
I am able to reproduce this in OpenGL. Its a very odd bug. It seems to be related to the fact that escape hatch track has path .dat's that are not available for this park.
