### ISSUE TITLE
preserved rides tab in the wrong tool?

### ISSUE THREAD

**Issue by RealRexen** [OpenRCT2/OpenRCT2#4713]
OS: Windows 10
Build: 81bb6cb
Shouldn't the preserved rides tab be in the convert save game to scenario tool and not the scenario editor?

![rexen s world 2016-10-27 20-27-40](https://cloud.githubusercontent.com/assets/18408903/19749879/b69a46fc-9bba-11e6-9eb4-5467ad9f999c.png)

**Comment by Gymnasiast** [comment]
Indeed, it should only be in the 'convert saved game to scenario' tool. (Which is technically the scenario editor in disguise.)

**Comment by IntelOrca** [comment]
Original bug I think

**Comment by Gymnasiast** [comment]
I doubt it. I used the scenario editor quite often back in the day and the preservation tab was only there when converting a saved game, not when creating a scenario.
