### ISSUE TITLE
Color of water changed when zooming

### ISSUE THREAD

**Issue by max95812** [OpenRCT2/OpenRCT2#4715]
**OS:** [Windows 10]
**Version:** [0.0.6 x64]
**Commit/Build:** [b32e2ea]

In the first screenshot the water looks normal, when I zoom out (screenshot 2), the color changed
- [x] Reproducable in single player
- [x] Multiplayer?

**Screenshots / Video:**

![parc1](https://cloud.githubusercontent.com/assets/14279719/19781273/e28cb73a-9c88-11e6-935c-505197dce27f.PNG)
![parc2](https://cloud.githubusercontent.com/assets/14279719/19781276/e4437532-9c88-11e6-9392-d885ba48fbf4.PNG)
https://youtu.be/lM9B_GkTgjs

**Save game:**

[parc.zip](https://github.com/OpenRCT2/OpenRCT2/files/556776/parc.zip)

**Comment by AaronVanGeffen** [comment]
Don't use the OpenGL renderer yet -- it's very experimental.

**Comment by max95812** [comment]
I see, this happens only when using OpenGL
