### ISSUE TITLE
Make a warning notification when selecting OpenGL

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#4716]
As players use it as it would be a regular rendering option when it's very experimental/""new""
And reports are made about specific issues about it that's already known

Wouldn't it be better to make a error window pop up warning about it being unstable/experimental/unstable/requires implementions

**Comment by Gymnasiast** [comment]
Agreed, we have had quite a few questions about it already.

**Comment by manuelVo** [comment]
How about just renaming the Option from `OpenGL` to `OpenGL (experimental)`? That way the early stage of development would be clarified without hassling the users who want to try it out by opening a window they have to close. Also that way the users would be reminded they are using an experimental setting every time they open the options screen. A popup which only shows up when changing the option might be forgotten fast.

**Comment by Nubbie** [comment]
Why not both? :)
As experimental could still continue spawning issues about it
