### ISSUE TITLE
Not all rides show up in preserved rides tab in the covert save game to scenario tool

### ISSUE THREAD

**Issue by RealRexen** [OpenRCT2/OpenRCT2#4724]
OS: Windows 10
Version:0.0.5
Commit/Build: 43ec7fe

Basically what the tool says, not all rides show up in preserved rides tab in the covert save game to scenario tool. The odd part is that its seems to favor just shops and stalls and sometimes doesn't show any of the other rides.

Case 1:
![rexen s world 2016-10-29 13-22-04](https://cloud.githubusercontent.com/assets/18408903/19833699/a4c19424-9e19-11e6-8e02-d04e6ad63336.png)
Case 2:
![rexen s world 2016-10-30 20-03-51](https://cloud.githubusercontent.com/assets/18408903/19833702/abf65946-9e19-11e6-974d-3f93e3c08ef8.png)

**Comment by IntelOrca** [comment]
Please provide a saved game
