### ISSUE TITLE
Full litter bins do not display in all directions

### ISSUE THREAD

**Issue by RQWorldblender** [OpenRCT2/OpenRCT2#4725]
**OS:** Ubuntu GNU/Linux 16.04 (though it might not matter what operating system this happens on)
**Version:** 0.0.5
**Commit/Build:** 66cd816922b220f51f4336a77d9066c00f390b08

When litter bins become full, they are properly marked as such, but display as full only in certain directions. In other directions, they are displayed as empty, but are still marked full.
- Unlikely to be reproducible in RCT2 (vanilla).
- An earlier commit likely introduced this bug, as this did not happen before.

**Steps to reproduce:**
1. Open any scenario or save file.
2. If the file does not contain any litter bins, add some.
3. If necessary, enable see-through rides and scenery and invisible guests to make the litter bins easier to see.
4. Wait for guests to fill them up.
5. Eventually, litter bins will become full, but they only display this correctly in some directions. They display as empty in other directions, but are still marked as full.
5. That can make it harder to know when litter will start appearing on footpaths.

**Screenshots:**
Save file from Time Twister expansion pack (Rock' n' Roll - Flower Power):
![woodstock 2016-10-30 14-12-16](https://cloud.githubusercontent.com/assets/13372387/19839148/eaf08806-9eaa-11e6-9ec8-0b34a6eb097f.png)
![woodstock 2016-10-30 14-12-20](https://cloud.githubusercontent.com/assets/13372387/19839146/eae91f44-9eaa-11e6-8d09-2f2b75e2c3b7.png)
![woodstock 2016-10-30 14-12-23](https://cloud.githubusercontent.com/assets/13372387/19839147/eae9b9fe-9eaa-11e6-9126-9c5a6736b7d5.png)
![woodstock 2016-10-30 14-12-26](https://cloud.githubusercontent.com/assets/13372387/19839145/eae8078a-9eaa-11e6-8dec-0ba16f64c8fe.png)

Scenario from base game (Six Flags Belgium):
![six flags belgium 2016-10-30 14-22-43](https://cloud.githubusercontent.com/assets/13372387/19839267/98a9bd72-9eac-11e6-8250-613b673d16e0.png)
![six flags belgium 2016-10-30 14-22-47](https://cloud.githubusercontent.com/assets/13372387/19839265/98a6e476-9eac-11e6-992f-1577011d44ed.png)
![six flags belgium 2016-10-30 14-22-50](https://cloud.githubusercontent.com/assets/13372387/19839281/c86224a0-9eac-11e6-83e3-07449b80ad12.png)
![six flags belgium 2016-10-30 14-22-54](https://cloud.githubusercontent.com/assets/13372387/19839268/98aa0eb2-9eac-11e6-842e-25c35940b8c1.png)

**Save game:**
[Woodstock.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/560672/Woodstock.sv6.txt)
(When loading this save file, you may have to wait a while before the litter bins actually fill up)

**Comment by Trippeh** [comment]
Also "no littering" doesn't stop guests from using the litter-bins.
