### ISSUE TITLE
random game crash with dump

### ISSUE THREAD

**Issue by cpufreak** [OpenRCT2/OpenRCT2#4726]
**OS:** Windows 10
**Version:** 0.0.5.0, 66cd816

basically, was just playing the game, was building a path over an area with construction rights, tried to then delete the path and then i got a game crash
- [ ] Reproducible in RCT2 (vanilla)? No
- [ ] Multiplayer? No

**Steps to reproduce:**
1.  build path over construction rights area
2. delete path

**Dump file**

[dump.zip](https://github.com/OpenRCT2/OpenRCT2/files/560726/dump.zip)

**Screenshots / Video:**
 wasn't recording at the time sadly

**Save game:**

[save.zip](https://github.com/OpenRCT2/OpenRCT2/files/560727/save.zip)

**Comment by RealRexen** [comment]
Please state an actual dev build version and game version so the devs have a better idea on what build your using as the game tends to get updated a lot and telling the devs the build is the latest is misleading

**Comment by cpufreak** [comment]
thank you. first time making a bug report so im sure to have screwed up
