### ISSUE TITLE
Enhancement/Idea: settings.ini file

### ISSUE THREAD

**Issue by player49256** [OpenRCT2/OpenRCT2#4734]
**OS:** Windows Vista - Windows 10
**Version:** 0.0.5
**Commit/Build:** 12bd31b

I would like to present the idea of an settings.ini/openrct2.ini file which has settings such as directory paths and other settings.

The reason for this is that you could make OpenRCT2 completely portable and play on any computer which has RCT2 installed. In my own case i have OpenRCT2 with all saves, etc on a Network share, but since OpenRCT2 hardcodes itself to documents and settings, it is hard to make it completely portable.

This way I could for example put OpenRCT2 and all RCT2 files on a USB stick and play on any computer i wanted.

To make sure that some who want computer specific settings with "Same copy" of OpenRCT2, there could be a registry flag which is simply "UseRegistrySettings" = 1 which OpenRCT2.exe checks on each launch.
If it is 1, it loads the settings from registry instead, and if set to 0, it loads from settings.ini.
This should be toggled by a checkbox inside Ingame options on each computer you play on.
Default should be 0 (Unchecked).

For those who is interested in such a solution now, you can use this script each time you launch OpenRCT2 (**USE AT YOUR OWN RISK!**)

MODERATOR, DELETE IF NECESSARY:

```
@echo off
Echo Launching game...
for /f "skip=2 tokens=2*" %%A in ('reg query "HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders" /v "Personal"') do set "UserDocs=%%B"
IF EXIST "%UserDocs%\OpenRCT2" move "%UserDocs%\OpenRCT2" "%UserDocs%\OpenRCT2_bak"
mklink /D "%UserDocs%\OpenRCT2" <path to OpenRCT2>"
"<path to OpenRCT2>\openrct2.exe"
```

Replace <path to OpenRCT2> with your own path, for example F:\OpenRCT2 or \\SERVER\NAS\OpenRCT2

This script checks if OpenRCT2 already exists in your Documents folder, and if needed renames it to OpenRCT2_bak (So no files gets lost).
Then it creates a Symlink which links Documents\OpenRCT2 to your specified location.
After that, it launches openrct2.exe

You can replace OpenRCT2.exe with the launcher instead.

**Comment by IntelOrca** [comment]
The game accepts a command line argument `--user-data-path` which you can give the directory containing the config.ini to use.

**Comment by player49256** [comment]
I see, so then this function is pretty mich already implemented? In that case, this can be closed.
