### ISSUE TITLE
Modifying land purchase in sandbox mode does not update land purchase button

### ISSUE THREAD

**Issue by fromthere** [OpenRCT2/OpenRCT2#4747]
**OS:** OS X
**Version:** 0.0.5
**Commit/Build:** b5630a5

Modifying land purchase in sandbox mode does not update land purchase button. if there's no land or build right to buy and adding more land to buy in sandbox mode does not update disable buttons. it occurs after #4701 merge.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open scenario that does not have land to buy
2. Turn sandbox mode on and make some land buyable
3. notice land purchase button is still disabled
4. save and reloading save does not fix problem

**Comment by Overv** [comment]
I messed up by forgetting to include a land rights recount call in the second game command that changes land rights. There's now a pull request in the queue that fixes the problem.
