### ISSUE TITLE
GFX Water sides drawn incorrectly.

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#475]
![watergraphicbug](https://cloud.githubusercontent.com/assets/1277401/4349281/f55e620e-41af-11e4-8374-bfdd6dde7af1.PNG)

As shown in the above picture.

**Comment by Gymnasiast** [comment]
Marijn asked me to also post the following bug here:

![screenshot](https://cloud.githubusercontent.com/assets/1478678/19533694/1b7e89cc-9641-11e6-93ac-f7f8ab5a79f3.png)

(The terrain under the water is as high as the column next to it.)

**Comment by Gymnasiast** [comment]
@duncanspumpkin Can you still reproduce this bug? I tried it, but didn't manage to reproduce it any more.

**Comment by duncanspumpkin** [comment]
No I can't reproduce this anymore. Not sure when it was fixed.
