### ISSUE TITLE
Great Wall of China - Guests are spawning at a point where you cannot enter

### ISSUE THREAD

**Issue by elcanadiano** [OpenRCT2/OpenRCT2#4760]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** c9a1ce5

In my Great Wall of China Save (from Wacky Worlds), there exist guests who are trying spawning and trying to enter a little to the right of the actual entrance. I'm not sure why this is.

- [N] Reproducible in RCT2 (vanilla)?
- [N] Multiplayer?

**Save game:**
[Great Wall of China.zip](https://github.com/OpenRCT2/OpenRCT2/files/573851/Great.Wall.of.China.zip)

**Comment by duncanspumpkin** [comment]
Known issue with the original badly made scenario. At least i remember this coming up before.

**Comment by elcanadiano** [comment]
Ahh, interesting. What is it that fundamentally was wrong about it?

**Comment by duncanspumpkin** [comment]
Well they put a peep spawn in the wrong place :)

**Comment by Margen67** [comment]
Then this issue should be closed.

**Comment by Christipher** [comment]
uh... couldn't we try to reverse engineer the spawn during all of these updates as well?  Like how hard is that going to be?

**Comment by ipatix** [comment]
Like, what would you reverse engineer? It's the scenarios fault and not the code's.

**Comment by duncanspumpkin** [comment]
Maybe at some point we will add something to auto fix the scenario but for now you can fix it yourself.

**Comment by PFCKrutonium** [comment]
(Enable Sandbox Mode, and click the map, move the spawn point)

**Comment by nummacway** [comment]
Just wanted to say that the same bug exists on the Rio de Janeiro map as well.

**Comment by Gymnasiast** [comment]
We already fix RCT1 scenarios with unpurchasable land tiles. Fixing RCT2 scenarios would be feasible.
