### ISSUE TITLE
Mirage Madness - Guests cannot find newly-built rides

### ISSUE THREAD

**Issue by elcanadiano** [OpenRCT2/OpenRCT2#4761]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** c268b51

In my Mirage Madness save, I built Viper, Woodchip, and a custom Go Karts stage in the Oasis side. I also made the path to the oasis above ground and it is possible to go there. However, a disproportionate amount of guests are saying, "I can't find XXX", where XXX is one of the three rides, and they are complaining that "It's too crowded here."

- [N] Reproducible in RCT2 (vanilla)?
- [N] Multiplayer?

**Save game:**
[Mirage Madness.zip](https://github.com/OpenRCT2/OpenRCT2/files/573860/Mirage.Madness.zip)

**Comment by sjoerddebruin** [comment]
Seems mostly solved 8 years later.
