### ISSUE TITLE
Assertion in localisation (format_string_part)

### ISSUE THREAD

**Issue by wolfreak99** [OpenRCT2/OpenRCT2#4762]
**OS:** Windows 10 (x86-64)
**Version:** 0.0.5-develop build c268b51 provided by AppVeyor

watch video for explanation. will answer any further questions, but i feel video points it out pretty well.

**Steps to reproduce:**
1.  Hover over scenario in scenario select.

**Screenshots / Video:**
https://vid.me/gkC8

*Save game:**
[CM36's Golden Desert.zip](https://github.com/OpenRCT2/OpenRCT2/files/573922/CM36.s.Golden.Desert.zip)

**Comment by IntelOrca** [comment]
The fix here may also be the fix for #4684, but we'll have to see.

**Comment by wolfreak99** [comment]
As far as this specific bug, you got it!
