### ISSUE TITLE
Main Menu music not playing

### ISSUE THREAD

**Issue by pinball409** [OpenRCT2/OpenRCT2#4771]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** Develop Branch - f8ea5bd

When changing the sound output the main menu music does not start again from the beginning or continue from when you changed the sound output.

I have also tested this while playing the game. If you change the sound output the music from rides just continues so no issue there.

**Steps to reproduce:**
1. Open 'OpenRCT2' launcher and launch game.
2. Open settings and click on the musical notes.
3. Change the sound output.

**Screenshots / Video:**
https://youtu.be/oQCbEd0oDx4

**Comment by Nubbie** [comment]
Isn't it just to restart all the sounds+music if you're on the titlescreen & the sound device is changed

**Comment by RealRexen** [comment]
The reason I think the music doesn't stop in-game when the sound device is change is because the game quickly plays the music again as if the music was changed or turn on. However the title screen may not have code to replay the music unless the music track itself is changed.
