### ISSUE TITLE
'View' option to hide No Entry signs (or path signs in general)? [Feature]

### ISSUE THREAD

**Issue by ts6815** [OpenRCT2/OpenRCT2#4772]
I love using No Entry signs to funnel my guests around (particularly from exit pathways) but they tend to wreck whatever theme I'm going for. Could there be an option implemented under View to hide them?

**Comment by IntelOrca** [comment]
Try concealing them with scenery, walls, roofs etc.

**Comment by Margen67** [comment]
Better yet use the tile inspector to add a corrupt element below the sign to hide it.

**Comment by Gymnasiast** [comment]
I think it's too much trouble for such an isolated use case. I would try @IntelOrca 's or @Margen67 's advice.
