### ISSUE TITLE
Saving boat ride tracks feature

### ISSUE THREAD

**Issue by tcek** [OpenRCT2/OpenRCT2#4773]
Would it be possible to save boat ride tracks like you can for coasters/mazes/car rides, etc. with scenery too as a feature please?

I made a swimming pool, took a while and used the crooked house track with it, so I could use the custom path below the water. I would love to be able to use this swimming pool with it's scenery in other parks I make. Thanks in advance.

**Screenshots
![t-zone 2016-11-08 06-34-35](https://cloud.githubusercontent.com/assets/21962525/20089369/637fc816-a57e-11e6-9897-b695a2ae29d9.png)
![t-zone 2016-11-08 06-34-52](https://cloud.githubusercontent.com/assets/21962525/20089373/682cf8f2-a57e-11e6-94eb-48fe6cc20545.png)

**Comment by Gymnasiast** [comment]
If you changed the ride type into a crooked house, it's not a boat ride any more. As far as I know, proper Boat Ride are saveable.

An alternative to making rides invisible using the Crooked House trick is to insert corrupt elements using the Tile Inspector.

**Comment by tcek** [comment]
Thanks, much appreciated.
