### ISSUE TITLE
[Feature Request] - Add users who join directly to the Users.Json

### ISSUE THREAD

**Issue by notorioushaze** [OpenRCT2/OpenRCT2#4774]
- [ X] Multiplayer?

**[Description]**
Currently, players who join at night when no staff are on can cause issues without the fear of getting banned to return another day.

**[How to Fix]**
Add players to the Users.Json as soon as they join rather than when their group is changed. This will allow server operators to ban users who are currently not online and might have caused issues when no one was around. This feature will work hand in hand with the new logging system in ticket #4273 

-Whiskeysim

**Comment by IntelOrca** [comment]
I don't see how this will help as they can just join again with a new name.

**Comment by notorioushaze** [comment]
I don't think you're understanding the request, and that's okay maybe I didn't explain it correctly.

**[How it is now]**
Player 1 Joins the server during a time where no staff are on. _[No access to group changes]_
Player 1 Starts spamming and causing a disturbance.
Player 1 Leaves and can return another day.

**[After the change]**
Player 1 Joins the server during a time where no staff are on. _[No access to group changes]_
*Player 1's key and name has been entered into the Users.Json when they joined and added to the default group*
Player 1 Starts spamming and causing a disturbance.
Player 1 Leaves
Player 2 reports the disturbance to staff.
Staff goes into the Users.Json and changes the users group to one which he can no longer speak while Player 1 is still offline.
Player 1 comes back to cause a disturbance to find out his key has been added to the banned group.

**Comment by Nubbie** [comment]
The thing is that the hash will be randomly generated again if the greifer changes his name after he have left the game and connect via a different name

**Comment by notorioushaze** [comment]
Man, we really need a way to curb the amount of attacks server operators receive. I don't really think you understand how many issues this causes.

You can close the feature request.
