### ISSUE TITLE
File name of screenshot that is taken at 00:xx is named wrong

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#4775]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** a934590

Name of screenshot that is taken in midnight (00:xx) has wrong name like below:

- [ ] Multiplayer?
- [ ] Reproducible in RCT2 (vanilla)?

**Steps to reproduce:**
1. Take a screenshot in midnight. For example, take screenshot at 2016-11-09 00:34
2. Then the screenshot's file name will be "(park name) 2016-11-**08** 00:34.png", not "(park name) 2016-11-**09** 00:34"

c.f. I'm using Asia/Seoul timezone in Windows 10 and system time is correct.

+ Add: it is named "2016-11-**08** 01:02" which is taken at 2016-11-09 01:02, too.
+ Add: So does 2 ~ 8 a.m's. I think it is concerned by timezone since korea uses UTC+9. It is named correctly after 9 a.m

**Comment by HaasJona** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/b568f002d4801435a6609f58aacf5fbdc4773706/src/platform/windows.c#L199

`GetSystemTime(&systime);` should probably be `GetLocalTime(&systime);`

**Comment by telk5093** [comment]
I pulled a request but I have no idea that I did correctly.
