### ISSUE TITLE
How do I enable Zero Clearance?

### ISSUE THREAD

**Issue by Mylork** [OpenRCT2/OpenRCT2#4800]
Where do I enable Zero Clearance?

**Comment by Nubbie** [comment]
@Mylork 
1. Enable 'Cheats' in Options > Controls and Interface > Cheats'
2. Load/start the map you want to play
3. Hold down the yellow shovel in the left corner and press the 'Disable clearence checks' cheat

![aefsg](https://cloud.githubusercontent.com/assets/17282384/20247429/58d80822-a9cc-11e6-867b-9d3aa46369fc.png)
