### ISSUE TITLE
Can no longer buy land in various scenarios?

### ISSUE THREAD

**Issue by elcanadiano** [OpenRCT2/OpenRCT2#4808]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** 7b34e71

The following is one example I know of directly from the back of my head.

I have an Antarctic - Ecological Salvage save and I recently revisited it. This save is an RCT2 Wacky Worlds expansion save and the premise is that you can buy land cheap and salvage the paths/scenery for profit. I played through and completed the save but recently when I revisited the save (for fun), I noticed I could no longer buy land even though I have sufficient funds and have not bought all the land. Is there a reason why?

**Save game:**
[Icy Adventures.zip](https://github.com/OpenRCT2/OpenRCT2/files/592902/Icy.Adventures.zip)

**Comment by Nubbie** [comment]
I presume the button is grayed out? 
There was a update #4701 where the button gets grayed out when no land is remained to buy
Might be a bug caused by that

**Comment by elcanadiano** [comment]
That could be it.

The button is grayed out but I'm certain I have not bought all the land available in the scenario.

If this is considered a duplicate we can always close it.

**Comment by Gymnasiast** [comment]
@Overv

**Comment by elcanadiano** [comment]
Thank you guys!
