### ISSUE TITLE
[Idea] The game should not close out of the ad/marketing voucher when the player lacks funds

### ISSUE THREAD

**Issue by RealRexen** [OpenRCT2/OpenRCT2#4810]
Okay let's say I want to start a new marketing campaign and go to set how many weeks it should last as seen below. 
![bashful beach 2016-11-15 16-44-53](https://cloud.githubusercontent.com/assets/18408903/20325533/129a0b66-ab53-11e6-8feb-df342559caea.png)
If you notice I lack the funds, if I hit okay the window just disappears with an error saying I lack funds. This gets annoying after a while since it keeps you from making changes to the marketing campaign, by keeping the window open and displaying the error the player can then make the changes needed (like lowing the amount of weeks) without having to reopen the voucher/campaign window. Makes no sense for this to be the only window that closes on an error.
Here's a screenshot of what happens when I hit "start this campaign" button:

![2016-11-15](https://cloud.githubusercontent.com/assets/18408903/20325755/f106d6b8-ab53-11e6-99dd-baa9e2eadb04.png)

**Comment by marijnvdwerf** [comment]
The button probably also should be disabled when it results in an error.

**Comment by IntelOrca** [comment]
@marijnvdwerf no, that isn't how any construction buttons work
