### ISSUE TITLE
[DISCUSSION] should string_ids.h be more consistent with the en-gb text?

### ISSUE THREAD

**Issue by wolfreak99** [OpenRCT2/OpenRCT2#4811]
For reference sake, I'm going to be using the following string_ids and their text definitions.
````
STR_STRING = 1170,
STR_BLACK_STRING = 1191,
STR_RED_OUTLINED_STRING = 1192,
STR_WINDOW_COLOUR_2_STRINGID = 1193,
STR_DEBUG_DROPDOWN_CONSOLE = 5312,

STR_1170    :{STRING}
STR_1191    :{BLACK}{STRINGID}
STR_1192    :{OUTLINE}{RED}{STRINGID}
STR_1193    :{WINDOW_COLOUR_2}{STRINGID}
STR_5312    :Show console
````
We have `STR_BLACK_STRING` and then `STR_WINDOW_COLOUR_2_STRINGID`, where both definitions use the `{STRINGID}` token. but `STR_STRING` uses `{STRING}`. I'm sure we can all agree that the way our current approach of using strings is a bit tedious when adding new strings*, so we may usually type "STR_" and use intellisense to see if anything already exists before adding a new string definition. when seeing `STR_BLACK_STRING` and `STR_WINDOW_COLOUR_2_STRINGID`, it sounds like it uses different tokens, when in reality, `STR_BLACK_STRING` actually uses a `STRINGID` token. Also, some lines of text could be used in multiple instances, such as the "Show console", we could have that in the keymappings window code along with the toolbars dropdown code, but `STR_DEBUG_DROPDOWN_CONSOLE` doesn't really fit well in the context of keymapping, and you may not even know "Show console" is already a thing, because "STR_SHOW_CONSOLE" yields no intellisense results so you assume that it's not in the file yet. 

I'm going to cut a bit to the chase, what I'm thinking we should do is have some more consistancy between the string_ids and en-gb files.. make string_ids reflect the en-gb definition, rather than making the string_id reflect the initial context the line is used in.. the only exceptions i see would be tooltips, but those are usually the same string_id name as the button only with "_TIP" at the ending. we don't need a `STR_SHOW_CONSOLE` and `STR_SHOWS_THE_CONSOLE_WINDOW`, when `STR_SHOW_CONSOLE_TIP` gives enough of a hint.

I'm not saying to go through and redo ALL of the string_ids, but I'm just thinking as we go on, if we add new string_ids, or recycle old string_ids, we should name it to reflect the en-gb text, rather than the context of the code. 

Opinions?

* = While I say the current string_ids approach is tedious for new definitions, for what it's worth the current approach is good enough so we don't need a new approach. the current one allows easy implementation, adding strings is straightforward, the text code isn't cluttered with duplicate strings everywhere, and allows more accurate translation than relying on some non-human-fluent translation bot or something.

**Comment by marijnvdwerf** [comment]
The actual good thing about the way strings are handled, is that the original game used different stringIds for different contexts.

The IDs should ultimately be generated, and the strings should probably be regrouped to have domains together, but I think it would be a bad thing to "use English as a base".
Imagine you were adding an on-screen keyboard with a `STR_SHIFT`. You'd might be tempted to use the same `STR_SHIFT` on a button for shifting a track piece.

Or `STR_PLAYER` for someone who's playing mini golf. Is that the same `STR_PLAYER` as in a networked game? Or the default value for the player name?

**Comment by IntelOrca** [comment]
> The actual good thing about the way strings are handled, is that the original game used different stringIds for different contexts.

That isn't a good thing necessarily. The context can often change the translation.

**Comment by marijnvdwerf** [comment]
@IntelOrca Which is the reason why it's a good thing that each context usually has its own ID, right?

**Comment by IntelOrca** [comment]
@marijnvdwerf I thought you said that it used same string IDs... sorry. There are quite a few that are shared though which probably shouldn't be.

**Comment by IntelOrca** [comment]
https://github.com/OpenTTD/OpenTTD/blob/master/src/lang/croatian.txt

**Comment by marijnvdwerf** [comment]
Meh. Imho a string file should at the very least have plural support.
Something like https://developer.android.com/samples/Timer/res/values/strings.html

And domains would be a nice idea as well.

```xml
<!-- ride.xml -->
<domain name="ride">
   <string name="windowTitle">Ride</string>
   <plurals name="guests">
        <item quantity="one">%d guest on ride.</item>
        <item quantity="other">%d guests on ride.</item>
    </plurals>
</domain>
```
```xml
<!-- misc.xml -->
<domain name="config">
   <string name="defaultPlayerName">Player</string>
</domain>
<domain name="currencies">
   <string name="eur">Euro</string>
   <string name="gbp">Pound sterling</string>
   <string name="usd">Dollar</string>
</domain>
```

**Comment by marijnvdwerf** [comment]
(Note there's also [gettext](https://en.wikipedia.org/wiki/Gettext), but I'm really not a fan on how it ties so strongly to the English localisation)

**Comment by IntelOrca** [comment]
The string ID names shouldn't reflect exactly what the en-gb says, particularly as some are far too long. Its better to describe what its for rather than what the text says.

**For example:**
`STR_RIDE_ERROR_STATION_MAX_REACHED: No more stations allowed on this ride`

**Comment by wolfreak99** [comment]
okay, so the portion of basing it off on what it's for is pretty much settled. what about the stringid vs string? i like the idea of plural support but that feels like the file would get really overwhelming, and really it could be just diverted by having them organized one after another, such as the plural coming right afterward, and then handling the decision of using plurals by "string = STR_SINGLE_GUEST_ON_RIDE + isPlural" or something of that sort.

**Comment by wolfreak99** [comment]
Also, for what it's worth, Parkitect also had issues with how to handle localisation, http://themeparkitect.tumblr.com/post/112147591472/translation-support-for-unity-games

**Comment by marijnvdwerf** [comment]
@wolfreak99 Not all languages have plurals like English.
Op do 17 nov. 2016 om 14:25 schreef wolfreak99 <notifications@github.com>
