### ISSUE TITLE
Invalid Data when loading scenario/save, even if you have the exact files

### ISSUE THREAD

**Issue by BlazingEmpireHD** [OpenRCT2/OpenRCT2#4815]
- [ ] Reproducible in RCT2 (vanilla)? Yes
- [ ] Multiplayer? Likely

**Steps to reproduce:**
1. Click on any save game you have
2. Try to play it

Game says invalid data. Not sure if this has been found yet. Pretty game breaking unless you have auto-saves on, will work with auto-saves.

**Dump file**
None

**Screenshots / Video:**
None

**Save game:**
None (all selected may be filled with information in the morning)

**Comment by janisozaur** [comment]
Does enabling option to "allow loading objects with incorrect checksums" fix that for you?

**Comment by Nubbie** [comment]
From forum topic; https://openrct2.org/forums/topic/2188-another-game-breaking-bug

Please do fill in the commit, OS etc here too

**Comment by Gymnasiast** [comment]
Why did you remove the OS and build hash fields? They're in the form for a very good reason. Please restore them and fill them in properly.
