### ISSUE TITLE
OpenRCT2 icon looks blurry on scaled screen on win10

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#4817]
**OS:** Windows 10
**Commit/Build:**  118ac9b

Icon of OpenRCT2 on display scaled to 125% looks blurry, even though we have better icons available.

**Steps to reproduce:**
1. Install Windows 10
2. Set display scaling to 125%
3. Observe how icon looks blurry

**Screenshots / Video:**

Icon of openrct2 against better looking firefox icon:
![openrct2_icon](https://cloud.githubusercontent.com/assets/550290/20462190/2ba16a0c-af16-11e6-846a-42ed46fef859.PNG)

![openrct2_icon_taskbar](https://cloud.githubusercontent.com/assets/550290/20462193/318604fa-af16-11e6-9282-d2b8ac87d829.PNG)

**Comment by IntelOrca** [comment]
Not sure how to fix this... The icon format contains all sizes of the PNGs from 8 to 256.

**Comment by janisozaur** [comment]
Does it contain 40x40 image too? https://msdn.microsoft.com/en-us/library/ms701681(v=vs.85).aspx

**Comment by IntelOrca** [comment]
no, I suppose it needs that then
