### ISSUE TITLE
Themed path signs are cheaper than regular path signs

### ISSUE THREAD

**Issue by RQWorldblender** [OpenRCT2/OpenRCT2#4820]
**OS:** Ubuntu 16.04 (it may not matter what operating system is used)
**Commit/Build:**  118ac9b (though it has been like this for the past 6 months, or more)

I see that when I open the scenery window, I may choose to place a path sign, but find something strange: themed scenery path signs are cheaper than standard path signs (the ones whose color can be changed). The former's price are 1/5th of the latter's, but in the original game, themed scenery path signs are supposed to be 1 1/5th more expensive to build than standard path signs.

**Steps to reproduce (currency will be in US dollars):**
1. Open the scenery window. 
2. Hover the mouse over the regular path sign. It costs $25 to build.
3. If other scenery is enabled, hover over any one of them. Any one of them costs only $5 to build. In the original game, any one of them costs $30 to build, making these unfairly cheaper to build than the regular signs.
4. That's the best I can remember, but if you think my memory is wrong, do tell me.

**Comment by IntelOrca** [comment]
Is this the same as the original game? Price is determined by the object DAT and we don't tend to go about fixing those.
