### ISSUE TITLE
More natural camera dragging

### ISSUE THREAD

**Issue by AndreasBackx** [OpenRCT2/OpenRCT2#4826]
Currently when dragging the camera with the right mouse button it does not move the cursor while moving the camera. The user expects the mouse to move together with the camera because you're holding the camera itself and dragging it somewhere. Currently the camera is moved, but the cursor is placed back where it originally was placed.

This could be implemented together with #2091, #3081 and perhaps together with macOS touchpad two finger dragging/scrolling to move the screen.

Because the controls of a game are essential to how the user experiences the game, I feel that a change like this would already immensely benefit the controls of the current game.

**Comment by IntelOrca** [comment]
The problem with this is when you move the camera more than the window size. The cursor would be moved outside the window, thus requiring the user to let go, move mouse back and drag again for long distance scrolling.

**Comment by marijnvdwerf** [comment]
@IntelOrca You also need to do that when you're using Google Maps. Plus if you have a physical mouse, you want to move your mouse back as well, which is more effort if you need to pick it up because the cursor didn't move. if you're using a trackpad, you will also reach physical boundaries and you also want to reposition your finger.

**Comment by IntelOrca** [comment]
Well by all means then but it most likely will have to be a setting as lots of people will prefer one over the other. The current way assumes you are dragging the viewport rather than the world.

**Comment by AndreasBackx** [comment]
I will give the implementation a shot, but I'm not promising anything. I'm currently quite busy too. I know where to start regarding the feature itself, are there any docs on how I add something to the settings menu?

**Comment by Broxzier** [comment]
@AndreasBackx just look at how other checkboxes are created. From memory (I'm on my phone)

1. Add one new string to en-GB.txt
2. Add the string ID to strings.h
3. Add a widget entry to the enumeration in options.h (WIDX_something)
4. Add a checkbox widget to options screen (list of values at the top in options.h
5. Enable the widget

**Comment by Broxzier** [comment]
(can't seem to edit comments on phone) 

After that look where the other checkboxes are being used by looking for WIDX_other-checkbox-widget
