### ISSUE TITLE
Single support is only draw over some path types

### ISSUE THREAD

**Issue by fromthere** [OpenRCT2/OpenRCT2#4833]
**OS:** macOS Sierra
**Version:** 0.0.5
**Commit/Build:** fc666e7

<img width="465" alt="2016-11-28 1 25 27" src="https://cloud.githubusercontent.com/assets/10338434/20656399/bdf1f7d2-b56f-11e6-8c32-a29f524e2795.png">

Single support is only draw over some path types.(paths have other types are supposed to have supports - download save file and change path to gray and all supports will drawn)

<img width="74" alt="2016-11-28 1 35 25" src="https://cloud.githubusercontent.com/assets/10338434/20656409/ea05c7ae-b56f-11e6-9c34-50254a8bd5a1.png">

If path's support is bar type, support will be not drawn(even path is not above ground).
<img width="78" alt="2016-11-28 1 35 38" src="https://cloud.githubusercontent.com/assets/10338434/20656418/15d171bc-b570-11e6-80b2-e56537104f2e.png">

but if path's support is block type, support will drown(only path is not above ground).

Custom paths are affected if their support is bar type. and it's reproducible on vanilla.

I'm sorry If this is duplicate(searched about supports but found nothing)

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Save game:**
[Monorail.SV6.zip](https://github.com/OpenRCT2/OpenRCT2/files/615389/Monorail.SV6.zip)

**Comment by Gymnasiast** [comment]
This is by design. Paths can set a flag to disallow supports being drawn.

**Comment by Broxzier** [comment]
Feature idea, perhaps we could add a checkbox in the path window to toggle this. All bits of a path element are already in use though.
