### ISSUE TITLE
Construction Marker For Placed Scenery Stays When Mouse Moved

### ISSUE THREAD

**Issue by M5000** [OpenRCT2/OpenRCT2#4838]
**OS:** [Microsoft Windows 10 Professional X64]
**Version:** [0.0.5.0]
**Commit/Build:** [a9eb93c]

When placing scenery, the construction marker (herein referred to as the ghost piece) appears to show you where you will be building and what it will look like. 
When mouse is moved, new ghost piece is generated in the new mouse position as normal, but, the old ghost piece remains.
Only way to remove stuck ghost pieces is to use the "Clear Scenery" function and remove them. 
Using white or translucent the following observations are made:

-White ghost pieces do not show placed objects when clicked (meaning object is "underneath" the ghost piece)
-Translucent ghost pieces show placed objects when clicked to place scenery but placed scenery is darker due to overlay.
-Placing ghost pieces in the same spot using translucent, the ghost piece gets darker, meaning the old one continues even if new ghost piece is generated in the same spot as an existing one.
-Clear scenery will clear both ghost pieces and and the selected scenery.
-Ghost pieces will behave normally for anything that is NOT a "placed" scenery piece, meaning:
 -Coasters/rides
 -Shops/stalls
 -Fences/walls ("edge bound" scenery)
 -Footpath items
-When a ghost piece of a moving object is placed (water fountain feature used for discovery) any existing ghost pieces nearby will animate along with it, leaving further ones frozen. Ghost pieces will re-animate if the cursor is moved back near them again. Range and pattern appear to be random/unpredictable.
-Appears to happen in all three drawing engines/render modes
-Did not happen in previous builds to my knowledge.

As a side note, my friend who uses an NVidia GTX 1070 did not experience the ghosting problem when connected as a client to my game as a server. I am using an AMD Radeon RX480. We both recently updated the game to 0.0.5.0 build a9eb93c after not updating for a few days. We have always downloaded from the main site, which appears to redirect to cdn.limetric.com

Seems to affect multiplayer and single player regardless.

I installed previous build 0.0.5.0-develop build 329c8b1 and issue did not appear to be present.

- [x] Multiplayer?

**Steps to reproduce:**
1. Start game
2. Open any map (presumably)
3. Go to scenery
4. Place something that either takes up 1 block, takes up 1/4 block, or multiple blocks. The clock garden was used in the screenshot example, but appears to carry over for any other similar items.
5. To clear ghost pieces, use clear scenery function. Ghost pieces are removed, but will regenerate next time scenery is attempted to be placed.

**Screenshots / Video:**
![clear peaks river 2016-11-29 20-18-29](https://cloud.githubusercontent.com/assets/24260591/20735915/49a0fc68-b671-11e6-813c-cec2a62a3df2.png)
![clear peaks river 2016-11-29 20-19-51](https://cloud.githubusercontent.com/assets/24260591/20735918/4bb450b8-b671-11e6-927e-0ac935b67cce.png)

**Save game:**

[Clear Peaks River_MP.txt](https://github.com/OpenRCT2/OpenRCT2/files/620691/Clear.Peaks.River_MP.txt)

**Comment by PopsiclePenguin** [comment]
I can confirm this happens with the GTX 1070 as well. In multiplayer or singleplayer, the ghost pieces remain. Only seems to happen with 1x1 scenery objects, larger objects dont leave the ghost objects behind.

**Comment by ArcticX9** [comment]
Might be related to Zero Clearances; noticed it too.

**Comment by Nubbie** [comment]
[There was a refractor in the code with "place scenery",](https://github.com/OpenRCT2/OpenRCT2/pull/4809) I presume it's from that something unexpected changed, you could try a version before that and see if it works. 
Like version [329c8b1](https://openrct2.org/downloads/develop/329c8b1)

**Comment by M5000** [comment]
Yes - That was one of the things I tried as listed above. I used the next most recent build 329c8b1 and the issue was no more, so it definitely seems isolated to this one build.
