### ISSUE TITLE
Custom scenario from previous version crashes game

### ISSUE THREAD

**Issue by tinnetju** [OpenRCT2/OpenRCT2#4839]
**OS:** [Windows 10 Pro 64bit]
**Version:** [0.0.5]
**Commit/Build:** [a9eb93c]

First of all, thanks for creating this mod and/or help making it better. Me and my friends already had countless of hours of fun and I'll do my best to spread the word.

I created a custom scenario which includes about 90% of all the unique rides and set all the settings so it's the most fun to play with friends, now when I try to create a game with the scenario or load the scenario in the scenario editor the game crashes and gives me the error: 
Kan dit bestand niet laden... Spel opslaan mislukt! Which translates to: Can't load this file... Saving game failed!

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Load the custom Scenario I made in a previous version (about 3 weeks ago)
[Custom scenario (Build=Develop) [Goal=1.000.000 park value, loan=500.000].zip](https://github.com/OpenRCT2/OpenRCT2/files/621335/Custom.scenario.Build.Develop.Goal.1.000.000.park.value.loan.500.000.zip)
2. The scenario editor thinks it loads at first but it doesn't really load anything as the selected attractions fail to load and it crashes right afterwards, the entire game crashes when you try to create a new game with it

**Dump file**
[OpenRCT2.zip](https://github.com/OpenRCT2/OpenRCT2/files/621325/OpenRCT2.zip)

**Screenshots / Video:**
[image](https://cloud.githubusercontent.com/assets/11628618/20745964/e90ed618-b6e3-11e6-916a-742155525f82.png)

**Save game:**
[OpenRCT2.zip](https://github.com/OpenRCT2/OpenRCT2/files/621325/OpenRCT2.zip)

**Comment by Nubbie** [comment]
To devs; 
What I got from the dumpfile

**Error message;**
Unhandled exception thrown: read access violation.
entry was 0xFFFFFFFFFFFFFFFF.

**Call stack;**
```
>	openrct2.exe!scenery_paint(unsigned char direction, int height=80, rct_map_element * mapElement=0x00007ff77255b588) Line 67	C
 	openrct2.exe!sub_68B3FB(int x=2464, int y=3936) Line 258	C
 	openrct2.exe!paint_generate_structs(rct_drawpixelinfo * dpi) Line 652	C
 	openrct2.exe!viewport_paint_column(rct_drawpixelinfo * dpi=0x000000cb76d9f9a0, unsigned int viewFlags=1152) Line 751	C
 	openrct2.exe!viewport_paint(rct_viewport * viewport, rct_drawpixelinfo * dpi, short left=-446, short top, short right=1474, short bottom=3023) Line 734	C
 	openrct2.exe!viewport_render(rct_drawpixelinfo * dpi=0x000000cb76d9fac0, rct_viewport * viewport, int left=0, int top=985, int right=1474, int bottom=3023) Line 664	C
 	openrct2.exe!window_editor_main_paint(rct_window * w, rct_drawpixelinfo * dpi) Line 96	C
 	openrct2.exe!window_draw_single(rct_drawpixelinfo * dpi, rct_window * w=0x00007ff7727d6a40, int left, int top, int right=1920, int bottom=1017) Line 1689	C
 	openrct2.exe!window_draw(rct_drawpixelinfo * dpi=0x000000cb76d9fb80, rct_window * w=0x00007ff7727d6a40, int left=0, int top=985, int right=1920, int bottom=1017) Line 1584	C
 	openrct2.exe!window_draw_all(rct_drawpixelinfo * dpi, short left, short top, short right, short bottom) Line 573	C
 	openrct2.exe!viewport_shift_pixels(rct_drawpixelinfo * dpi=0x00000207d4b3aa80, rct_window * w=0x00007ff7727d6a40, rct_viewport * viewport=0x00007ff7727eb600, short x_diff, short y_diff=-22) Line 399	C
 	openrct2.exe!viewport_move(short x, short y, rct_window * w=0x00007ff7727d6a40, rct_viewport * viewport=0x00007ff7727eb600) Line 479	C
 	openrct2.exe!viewport_update_position(rct_window * window=0x00007ff7727d6a40) Line 609	C
 	openrct2.exe!window_update_all_viewports(...) Line 154	C
 	openrct2.exe!SoftwareDrawingEngine::Draw() Line 393	C++
 	openrct2.exe!openrct2_loop(...) Line 442	C
 	openrct2.exe!openrct2_launch(...) Line 344	C
 	openrct2.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance=0x000000000000000a, char * lpCmdLine=0x0000000000000000, int nCmdShow=1995911168) Line 77	C
 	[External Code]	
 	ntdll.dll!00007ffb759dc5b4()	Unknown
```

**Locals;**
```
		ax	Variable is optimized away and not available.	
		baseImageid	0	int
		boxlength	Variable is optimized away and not available.	
		boxoffset	Variable is optimized away and not available.	
		direction	Variable is optimized away and not available.	
		dword_F64EB0	0	unsigned int
+		entry	0xffffffffffffffff {name=??? image=??? small_scenery={flags=??? height=??? tool_id=??? ...} ...}	rct_scenery_entry *
		esi	Variable is optimized away and not available.	
		height	80	int
		image_id	Variable is optimized away and not available.	
		image_id	Variable is optimized away and not available.	
		image_id	Variable is optimized away and not available.	
		image_id	Variable is optimized away and not available.	
		image_id	Variable is optimized away and not available.	
		image_id	Variable is optimized away and not available.	
+		mapElement	openrct2.exe!0x00007ff77255b588 {type=14 '\xe' flags=143 '' base_height=10 '\n' ...}	rct_map_element *
		minuteImageOffset	Variable is optimized away and not available.	
		supportHeight	Variable is optimized away and not available.	
		supportImageColourFlags	Variable is optimized away and not available.	
		timeImageBase	Variable is optimized away and not available.	
		x_offset	Variable is optimized away and not available.	
		y_offset	Variable is optimized away and not available.	
```

**Comment by Nubbie** [comment]
Another user on the forum reported about this issue, his dumpfile is close to this one
https://openrct2.org/forums/topic/2269-game-crash-on-loading-a-landscape/

**Comment by Gymnasiast** [comment]
The file in the opening post does not load for me because of missing objects. The file in the linked forum thread loads without issue for me. Which is expected, the code has changed a lot in 4.5 years. I will therefore assume the issue has been fixed in the meantime.
