### ISSUE TITLE
Supports rendered incorrectly when mixed with scenery

### ISSUE THREAD

**Issue by Forceu** [OpenRCT2/OpenRCT2#4849]
I hope this is not a duplicate, however I just noticed that the supports for the wooden roller coaster aren't rendered correctly if there is some scenery

**OS:** Ubuntu 16.04
**Version:** 0.0.5
**Commit/Build:** 1ae2ca5

**Screenshots / Video:**
https://youtu.be/ErlVGrUNl-0

To reproduce, build the "Black Widow" wooden roller coaster.

**Save game:**
[bugreport.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/628440/bugreport.sv6.zip)

**Comment by duncanspumpkin** [comment]
How does that video make it obvious what is wrong?

**Comment by Forceu** [comment]
Sorry, I didn't realize how hard to see it is without fullscreen and the youtube compression.
Pay attention to the first drop:

![screenshot from 2016-12-03 13-44-27](https://cloud.githubusercontent.com/assets/1593467/20859726/e681d68e-b95e-11e6-927b-d4c272c0d514.png)

**Comment by Nubbie** [comment]
Duplicate of #4643? 
Especially with the comment bellow
