### ISSUE TITLE
Add ghost train for testing while building mode (as seen in RCT3)

### ISSUE THREAD

**Issue by AngryHobo** [OpenRCT2/OpenRCT2#485]
I was thinking about different functions or enhancements you could make to the game so I thought, how about adding a testing during build mode like in RCT3 that shows a ghost train on the coaster just to make sure the ride can get over all the hills and loops. I know we've all had that time where we're finished building a perfect coaster except its not able to make it over all the obstacles.

**Comment by Gymnasiast** [comment]
Has been implemented recently, so this can be closed.

**Comment by IntelOrca** [comment]
Well... not to the same extent as RCT3. Once vehicle update is done, it might be possible to add the ghost vehicle.

**Comment by mrtnptrs** [comment]
Vehicle update is done now, so this would be possible now.

**Comment by Gymnasiast** [comment]
I doubt that. Drawing of most roller coasters and vehicles is still not implemented.

**Comment by devnoname120** [comment]
Can this be done now?

**Comment by janisozaur** [comment]
Probably, but someone has to do it and we are more concerned with getting release out the door.

**Comment by PFCKrutonium** [comment]
Basically, ask again when the release is out the door.

**Comment by IntelOrca** [comment]
Not possible until we have our own save format. It would need to be a vehicle with specific flag - a new flag which would be incompatible with RCT2.

**Comment by JohnEriksson00** [comment]
Does it really require a new save format? Isn't it possible to implement a train that continously rides the track (like testing does currently, although with the construction window closed) when you have the construction window open? You don't need to save this train, as the window closes (therefore removing the "ghost" train). Preventing crashes in testing mode is already in the game.

**Comment by duncanspumpkin** [comment]
Feel free to implement it but it would be a pain to do in the current code.
