### ISSUE TITLE
Russian language does not rellay apply the language

### ISSUE THREAD

**Issue by RealRexen** [OpenRCT2/OpenRCT2#4853]
OS:Windows 10
Version:0.0.5
Build: cbd64af

Basically choosing Russian does nothing expect affect the look of the font, game stays in English however. The game seems to act like the russian.txt file isn't there when it really it is and has strings and Russian text defined.
![untitled](https://cloud.githubusercontent.com/assets/18408903/20870414/c14cc07a-ba55-11e6-93a7-ebbe982e64db.jpg)

**Comment by AaronVanGeffen** [comment]
Unfortunately, this is not a bug: it just happens that very little has been translated into Russian so far. Out of the roughly 6000 strings that OpenRCT2 uses, only about 120 have been translated into Russian.

If you like, you can [help out](https://github.com/OpenRCT2/Localisation#contributing) by contributing to the translation, though.
