### ISSUE TITLE
Loading save file while "Save this before quitting?" dialog can cause infinite pause

### ISSUE THREAD

**Issue by Lastorder-DC** [OpenRCT2/OpenRCT2#4855]
**OS:** macOS
**Version:** 0.0.5
**Commit/Build:** 1dd2751

Loading save file while "Save this" dialog can cause infinite pause

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open save file(or start new scenario)
2. Open "Load game" dialog
3. after some time, selete "Quit to menu"
4. When message box shows, load save file by selecting file
5. Now game is infinitely paused(even title screen is now paused!)

**Screenshots / Video:**
https://www.youtube.com/watch?v=3H4LvdWn6vM

**Comment by tupaschoal** [comment]
I couldn't reproduce this in v0.3.1. Please reopen if you can
