### ISSUE TITLE
Headless: Assertion Failed!

### ISSUE THREAD

**Issue by Sweet-Tan** [OpenRCT2/OpenRCT2#4858]
**OS:** Windows 7 Pro x64
**Version:** 0.0.5
**Commit/Build:** 51fcfe3

Assertion Failed! Possible missing sprite. (Missed getting the screenshot, will next time!)

The OpenRCT Server affected is one of multiple running in the same Windows 7 VM on top of XenServer 6.5. They utilize the following arguments: --port --headless --console --verbose --user-data-path

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Dump file**
[549c9821-f0ea-407c-b7d7-5f45d373056d(51fcfe3_x86-64).zip](https://github.com/OpenRCT2/OpenRCT2/files/639501/549c9821-f0ea-407c-b7d7-5f45d373056d.51fcfe3_x86-64.zip)

**Save game:**
[549c9821-f0ea-407c-b7d7-5f45d373056d.zip](https://github.com/OpenRCT2/OpenRCT2/files/639503/549c9821-f0ea-407c-b7d7-5f45d373056d.zip)

**Comment by Nubbie** [comment]
Error message:
Unhandled exception at 0x000000013FDD9382 (openrct2.exe) in 549c9821-f0ea-407c-b7d7-5f45d373056d(51fcfe3_x86-64).dmp: 0xC0000005: Access violation writing location 0x0000000000000000.

Call stack;
```
>	openrct2.exe!Guard::Assert_VA(bool expression, const char * message=0x00000001406166a8, char * args=0x00000000001bf6e0) Line 91	C++
 	openrct2.exe!Guard::Assert(bool expression, const char * message=0x00000001406166a8, ...) Line 53	C++
 	openrct2.exe!viewport_create(rct_window * w=0x0000000140bc6f20, int x, int y, int width, int height=105, int zoom=0, int center_x=-1, int center_y=0, int center_z=0, char flags='À', short sprite=-1) Line 188	C
 	openrct2.exe!window_ride_init_viewport(rct_window * w=0x0000000140bc6f20) Line 1958	C
 	openrct2.exe!game_handle_input(...) Line 130	C
 	openrct2.exe!rct2_update(...) Line 473	C
 	openrct2.exe!openrct2_loop(...) Line 469	C
 	openrct2.exe!openrct2_launch(...) Line 344	C
 	openrct2.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance=0x000000000000000a, char * lpCmdLine=0x0000000000000000, int nCmdShow=0) Line 77	C
 	[External Code]	
```

Locals;
```
-		args	0x00000000001bf6e0 "ÿÿÿÿÿÿÿÿ\x1e\x1"	char *
			-1 'ÿ'	char
		bufend	Variable is optimized away and not available.	
+		buffer	0x00000000001bf410 "An assertion failed, please report this to the OpenRCT2 developers.\r\n\r\nVersion: OpenRCT2, v0.0.5-develop build 51fcfe3 provided by AppVeyor\r\nTried getting sprite 4294967295"	char[512]
		expression	Variable is optimized away and not available.	
-		message	0x00000001406166a8 "Tried getting sprite %u"	const char *
			84 'T'	const char
		result	3	int
+		version	0x00000000001bf610 "OpenRCT2, v0.0.5-develop build 51fcfe3 provided by AppVeyor"	char[128]
```
