### ISSUE TITLE
Desyncs when placing Scenery since refactor

### ISSUE THREAD

**Issue by carlu93** [OpenRCT2/OpenRCT2#4862]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:**  d1d6be0

Placing scenery causes desyncs. This might happen since the refactor of placing scenery got merged. I know that this wasn't happening before the refactor got merged. Unfortunately i have no more Information for you.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Place Scenery
2. Watch it desync

**Save game:**
[Desync.zip](https://github.com/OpenRCT2/OpenRCT2/files/643415/Desync.zip)

**Comment by zsilencer** [comment]
I don't think it's any different, if you don't have money off the money_effect will cause desync if your view is rotated different from the server because the velocity is different and will alter the sprite quadrant of other sprites.  This is a false positive from the sprite checksum though.

**Comment by janisozaur** [comment]
We skip money_effect when calculating checksum: https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/world/sprite.c#L192

How could it cause a false positive?

**Comment by IntelOrca** [comment]
How do we know that the `money_effect` doesn't desync the sprite IDs?

**Comment by zsilencer** [comment]
it will affect the next_in_quadrant of the sprites on the same tile which doesn't affect any game logic but does change the sprite checksum.  Another false positive is opening the staff list and the SPRITE_FLAGS_PEEP_FLASHING flag.

**Comment by Gymnasiast** [comment]
Does this bug still apply to the current state of the code?

**Comment by carlu93** [comment]
i can't answer that to be honest. I played Openrct2 on multiplayer some months ago and remember it happening! I haven't played multiplayer on the current state of code. Sorry. I saw some PRs going in about that case. Maybe we can just close this. I'll open another bug report if i can reproduce this on my next multiplayer game. Or someone else might have have some input about this!?
