### ISSUE TITLE
Offer an option to disable inhibiting the monitor power

### ISSUE THREAD

**Issue by RQWorldblender** [OpenRCT2/OpenRCT2#4865]
**OS:** Ubuntu 16.04 (could be for all operating systems
**Commit/Build:** d1d6be0b9316fd8a0322024b55ef5fbb0f3f7d7f

If the player leaves a computer with this game running for a while, upon reaching any specified screensaver times, the screensaver never seems to activate, which can cause a monitor to be left on for the entire time until the user comes to play again. It seems that this has been left here for the entire timeline of this game's development.

1.  Launch the program,
2.  Wait for the amount of time the screensaver or monitor power off activates.
3. The screensaver and/or the monitor turning itself off never seems to happen.

**Comment by IntelOrca** [comment]
Is this still the case if you minimise the game?

**Comment by RQWorldblender** [comment]
I can't remember, but it's still likely, because the setting if in effect for when the game is running at all.

**Comment by IntelOrca** [comment]
We do not explicitly prevent the monitor from standby in our code, so I don't know if this is an SDL2 problem or a problem with Ubuntu or just something you have to configure yourself.

**Comment by marijnvdwerf** [comment]
@IntelOrca What about https://wiki.libsdl.org/SDL_HINT_VIDEO_ALLOW_SCREENSAVER?

**Comment by RQWorldblender** [comment]
It looks like that SDL2 disables the screensaver by default, and there is likely no code here that ever deals with it.

**Comment by IntelOrca** [comment]
ok - fair enough

**Comment by Nubbie** [comment]
But wait, no game allows screensaver/sleep mode to be activated right?
Doesnt it make more sense to turn off the game?

**Comment by AaronVanGeffen** [comment]
> But wait, no game allows screensaver/sleep mode to be activated right?
> Doesnt it make more sense to turn off the game?

It would, to me — unless it's running as a (headed) server, I guess.

**Comment by Patrik356b** [comment]
A popular way to compensate for this "problem" is to roll an animation after a while, either in repeat or once and then repeat this "wait for input" timer again until any input is detected, like keypress, mouse.move, etc

If the animation is present at that point it would be cancelled and you return to the current game/menu

We could just roll the RCT intro every 15 minutes or something if it has been fixed for all display modes.

**Comment by ericneuman** [comment]
hi everyone!  Zombie thread resurrection .. I am seeing this in Mac OS X with the latest developer build whether OpenRCT2 is minimized or not.

It's a big deal for those of us with monitors that have burn-in risk like I do!

Any chance we could look at resolving soon?

**Comment by AaronVanGeffen** [comment]
It looks like this is a matter of applying [SDL_HINT_VIDEO_ALLOW_SCREENSAVER](https://wiki.libsdl.org/SDL_HINT_VIDEO_ALLOW_SCREENSAVER) in the right place, as mentioned before. If we do this, I would like it to be a proper option, though. Perhaps just "Suppress screensaver", enabled by default?

**Comment by ericneuman** [comment]
> It looks like this is a matter of applying [SDL_HINT_VIDEO_ALLOW_SCREENSAVER](https://wiki.libsdl.org/SDL_HINT_VIDEO_ALLOW_SCREENSAVER) in the right place, as mentioned before. If we do this, I would like it to be a proper option, though. Perhaps just "Suppress screensaver", enabled by default?

I'm great with that Aaron!  I am not picky on the implementation, just want to see it implemented somehow :).

Thanks so much!
