### ISSUE TITLE
Title Squence Editor Bug

### ISSUE THREAD

**Issue by RealRexen** [OpenRCT2/OpenRCT2#4869]
OS:Windows 10
Version:0.0.5
Build: bd02f14 x86

I'll just link to the reddit post I made. [https://redd.it/5hnuzk](https://redd.it/5hnuzk ) The only issue is I don't know how I caused the glitch to happen, I was mainly clicking on the skip button to go to the new part I added (the rotate part) and then it glitch the build text.

**Comment by marijnvdwerf** [comment]
@janisozaur @PFCKrutonium Looks familiar?

**Comment by Nubbie** [comment]
[Isnt this fixed?](https://github.com/OpenRCT2/OpenRCT2/pull/6606#issuecomment-341945443)

**Comment by AaronVanGeffen** [comment]
Yes, I backported it from that PR before that PR was merged. Thanks for pointing it out.
