### ISSUE TITLE
OpenRCT fails to launch if no .config folder exists in home directory

### ISSUE THREAD

**Issue by ipatix** [OpenRCT2/OpenRCT2#4874]
**OS:** Linux x86_64
**Version:** 0.0.5
**Commit/Build:** f3303b9

While setting up OpenRCT2 on my server I noticed that the game fails to start if there is no ".config" folder present in the users home directory on Linux:
`FATAL[/home/openrct/OpenRCT2/src/openrct2.c:116 (openrct2_initialise)]: Could not create user directory (do you have write access to your documents folder?)`
 Creating it manually workarounds that. I'm not too sure if that's 100% OpenRCT2s fault and if OpenRCT2 is allowed to rely on such an elemental directory but I felt like it might be a little improvable thing.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. See above

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by AaronVanGeffen** [comment]
Sounds as though the user running OpenRCT2 does not have write access to its home directory. Could you verify the permissions?

**Comment by janisozaur** [comment]
@AaronVanGeffen I think it's rather a bug in our code, I've seen it happen before. Our code does not handle recursive `mkdir`, so it fails to create `~/.config/OpenRCT2` in absence of `~/.config`/`$XDG_CONFIG_HOME`

**Comment by IntelOrca** [comment]
https://gist.github.com/JonathonReinhart/8c0d90191c38af2dcadb102c4e202950
