### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by tordenflesk** [OpenRCT2/OpenRCT2#4885]
W7SP1 x64
0.0.5.0
38fe149

Start OpenRCT2, crashes instantly,

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Run OpenRCT2.exe
2.  "profit
[cb99450f-33b2-498c-91fa-d57742aa543e(38fe149_x86-64).zip](https://github.com/OpenRCT2/OpenRCT2/files/657222/cb99450f-33b2-498c-91fa-d57742aa543e.38fe149_x86-64.zip)
"

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by Nubbie** [comment]
Will take a look at it

**Comment by IntelOrca** [comment]
The crash seems to stem from `c:\bbZero\plugins\bbLeanSkin\bbLeanSkinEng.dll`
Which looks like a third party application you have installed. This is probably what is causing your game to crash.

**Comment by janisozaur** [comment]
Nothing we can do about it, as it crashes in external code.
