### ISSUE TITLE
Assertion failed if no RCT2 directory selected on startup

### ISSUE THREAD

**Issue by Stevoisiak** [OpenRCT2/OpenRCT2#4893]
**OS:** Windows 7
**Version:** 0.0.5
**Commit/Build:** 77eea32

When starting up the 64-bit portable version of OpenRCT2 for the first time, if you click "cancel" when the game asks for your RCT2 directory, it will display "An assertion failed, please report this to the OpenRCT2 developers."

**Steps to reproduce:**
1. Run OpenRCT2 on a PC without RCT2 installed.
2. When the game asks for your RCT2 directory, click cancel.

**Comment by Gymnasiast** [comment]
Could you provide a screenshot of this assertion? The Windows build usually display where the assertion was made.

**Comment by Stevoisiak** [comment]
![Here's the assertion error](https://cloud.githubusercontent.com/assets/1330770/21440580/afe92f2a-c861-11e6-89e5-ab0033f309f8.png)

**Comment by CookieTC** [comment]
I was playing when my computer crashed and now when I try to open OpenRCT is says assertion failed! Expression source!=NULL, For information on how your program can cause an assertion failure see the Visual C ++ documentation on asserts. Please contact GitHub for RCT producers. How do I fix this? I really want to play again. I uninstalled both RCT2 the game and OPen RCT2 and it still says the same thing. I don't have another PC to do what is stated above.

**Comment by Nubbie** [comment]
@cookietc
Please open up a new issue if none exist or try contacting us on gitter for better support  https://gitter.im/OpenRCT2/OpenRCT2/non-dev

**Comment by IntelOrca** [comment]
@CookieTC could you try pressing abort when you hit the assertion, this should hopefully create a dump file you can send to us.

**Comment by CookieTC** [comment]
Yea I tried abort and it says failed to create dump please contact github
 :(

**Comment by janisozaur** [comment]
@CookieTC you should be able to create a dump using task manager, if you're on Windows.

**Comment by CookieTC** [comment]
I am on windows but the program does not show up in my task manager. And
when I hit abort nothing happens but the failed to create dump. So I guess
I'm just screwed lol

**Comment by janisozaur** [comment]
Launch it with `--console --verbose` and provide the logs
