### ISSUE TITLE
Title sequence camera should be able to follow a specific vehicle

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#4906]
This is already implemented in ride window when a vehicle is selected.

Here it can be seen in RCT:C title sequence: https://youtu.be/v6Xc8ehzm9k?t=22m20s

**Comment by Broxzier** [comment]
A while ago I was actually working on this, and on interpolation between two points. I'll try to make something this holiday.

**Comment by UltimaterRCT** [comment]
Hey, why not say add this feature in the actual game? That would be some sort of improvement!

**Comment by AaronVanGeffen** [comment]
Tagging #5930 for reference.

**Comment by AaronVanGeffen** [comment]
Implemented by #6606.
