### ISSUE TITLE
Invisible scenery tabs + object selector crash

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#4907]
Using the latest develop version on windows 8.

I was preparing to start a park, selecting objects. Every time I closed the object selector it crashed for some reason, but in the end after restarting the game and messing with the dump files numerous times I got the object selection that I wanted. Sadly, this is when suddenly all the custom scenery tabs disappeared. All it still showed were the default scenery tabs and the ?-tab. Going back into the object selector, apparantly all the scenery I selected in fact was still on the bench. Just invisible.

When opening the park in vanilla RCT, I can't see the tabs either. I'm 99.9% sure this is a problem spawned by OpenRCT though... Can you figure out what is going on, please?

[ERROR ERROR.zip](https://github.com/OpenRCT2/OpenRCT2/files/670060/ERROR.ERROR.zip)

**Comment by janisozaur** [comment]
"latest develop" is not a valid commit hash.

What does the zip contain?

**Comment by Nubbie** [comment]
@Liampie Please use the template when writing the issue, it makes it easier to help and read
Is the zip containing a dumpfile/save?

**Comment by Liampie** [comment]
v0.0.5 c44c93a

The zip contains a savegame.

**Comment by Nubbie** [comment]
@liampie you said that it crashed and gave out a dump file, could you post it here?
