### ISSUE TITLE
OpenRCT2 crashes immediately upon launching

### ISSUE THREAD

**Issue by matschou** [OpenRCT2/OpenRCT2#4908]
**OS:** macOS Sierra 10.12.1
**Commit/Build:** c44c93a

I just downloaded Openrct2 for mac and used [this](https://github.com/OpenRCT2/OpenRCT2/wiki/Installation-on-Linux#steam) guide to download Roller Coaster Tycoon 2: Triple Thrill Pack from Steam. I've placed the game from Steam and the Openrct2 app in the same folder (see screenshot), and selected the game folder as path when opening Openrct2. However, the game crashes immediately after launching. I hear a split second of the game's soundtrack and then get "OpenRCT2 quit unexpectedly".

I've attached a log file from launching with verbose and the problem report from the "OpenRCT2 quit unexpectedly" dialog.
[Problem report.txt](https://github.com/OpenRCT2/OpenRCT2/files/670099/Problem.report.txt)
[log.txt](https://github.com/OpenRCT2/OpenRCT2/files/670100/log.txt)
![screen shot 2016-12-23 at 01 18 38](https://cloud.githubusercontent.com/assets/7141884/21444452/c42fa756-c8ad-11e6-8abb-5ceb13029af3.png)

**Comment by marijnvdwerf** [comment]
Do the subfolders in `rct` actually have contents? The log file makes me think something went wrong with the Steam download, getting you an incomplete package.

**Comment by matschou** [comment]
Yes, all folders except Saved Games have content. However, there's only one file in landscapes. Could that be the problem?

**Comment by IntelOrca** [comment]
The log shows that its unable to find any objects.

**Comment by matschou** [comment]
Here are screenshots of each folder's content:
![tracks](https://cloud.githubusercontent.com/assets/7141884/21454667/9828d5ca-c91a-11e6-9654-dd4e79aeaf5d.png)
![scenarios](https://cloud.githubusercontent.com/assets/7141884/21454668/9858f21e-c91a-11e6-9a0c-4448c6534c11.png)
![saved games](https://cloud.githubusercontent.com/assets/7141884/21454670/985928ce-c91a-11e6-8d6e-b08633120813.png)
![objdata](https://cloud.githubusercontent.com/assets/7141884/21454671/98598ab2-c91a-11e6-863d-f43ccdc671a3.png)
![landscapes](https://cloud.githubusercontent.com/assets/7141884/21454669/985914c4-c91a-11e6-93e1-34ea3a882046.png)
![install](https://cloud.githubusercontent.com/assets/7141884/21454672/9859a862-c91a-11e6-9a39-5179d275dcfa.png)
![data](https://cloud.githubusercontent.com/assets/7141884/21454673/9859ef70-c91a-11e6-85bf-e17d713a3eb3.png)

**Comment by marijnvdwerf** [comment]
Can you do run the Steam download again? It seems it stopped halfway. Missing objects all seem to be starting with S, T or W. And your Scenarios folder also appears to be more empty than it should.

**Comment by matschou** [comment]
A new Steam download did the job. Thank you!
