### ISSUE TITLE
RCT Classic new sprites

### ISSUE THREAD

**Issue by marijnvdwerf** [OpenRCT2/OpenRCT2#4909]
- Two font sprites have been redesigned
- New tiny (banner/LED) font
- Three new filter palettes: (place/remove/edit ride?)
   ![4983](https://cloud.githubusercontent.com/assets/737603/21454090/eb75ddb8-c915-11e6-99d4-2540243c6b1e.gif)
   ![4984](https://cloud.githubusercontent.com/assets/737603/21454091/eb77090e-c915-11e6-8908-7142d36b5289.gif)
    ![4985](https://cloud.githubusercontent.com/assets/737603/21454092/eb77aac6-c915-11e6-8066-6868dfac0fd0.gif)
- New track pieces for the Steel Twister
    ![17189](https://cloud.githubusercontent.com/assets/737603/21454096/f71d8800-c915-11e6-8ce8-b1cf4caabd99.gif)
  ![17190](https://cloud.githubusercontent.com/assets/737603/21454097/f71f3d76-c915-11e6-8cb3-ec53fad5b4fe.gif)
- New track pieces for the Giga Coaster
  ![18121](https://cloud.githubusercontent.com/assets/737603/21454103/ffa99860-c915-11e6-83ef-c4aeadff93bd.gif)
  ![18122](https://cloud.githubusercontent.com/assets/737603/21454104/ffaa5dea-c915-11e6-9c56-7f65b0f2807c.gif)

- New wooden RC sprites (with additional empty sprites for the railing)
![23800](https://cloud.githubusercontent.com/assets/737603/21454111/0ad55a9e-c916-11e6-94c7-7c7a415c311d.gif)
![23801](https://cloud.githubusercontent.com/assets/737603/21454112/0ad61a38-c916-11e6-9296-63a5cd7cdf57.gif)
![23802](https://cloud.githubusercontent.com/assets/737603/21454114/0ad8f564-c916-11e6-8ed4-a10ab668c289.gif)
![23803](https://cloud.githubusercontent.com/assets/737603/21454113/0ad8b662-c916-11e6-8300-0c9d517064e6.gif)

- New track pieces for the Junior RC
  ![28244](https://cloud.githubusercontent.com/assets/737603/21454133/33585994-c916-11e6-862a-4353da3a941f.gif)
  ![28245](https://cloud.githubusercontent.com/assets/737603/21454132/3356dd3a-c916-11e6-9ca5-5142110781e7.gif)

- Some UI sprites:
![29343](https://cloud.githubusercontent.com/assets/737603/21454136/43467692-c916-11e6-9548-e786b8f915d5.gif)
![29344](https://cloud.githubusercontent.com/assets/737603/21454137/43479bc6-c916-11e6-939d-6d7901fe2e2c.gif)
![29345](https://cloud.githubusercontent.com/assets/737603/21454138/43495056-c916-11e6-8b55-885991f204c2.gif)
![29346](https://cloud.githubusercontent.com/assets/737603/21454139/4349d5b2-c916-11e6-9096-743e07e8d586.gif)
![29347](https://cloud.githubusercontent.com/assets/737603/21454140/434ac800-c916-11e6-826f-febffeba79b2.gif)
![29348](https://cloud.githubusercontent.com/assets/737603/21454141/434d2d98-c916-11e6-919c-5e9ebc82d2e8.gif)
![29349](https://cloud.githubusercontent.com/assets/737603/21454142/435d6820-c916-11e6-80ae-5d721ccd2761.gif)
![29350](https://cloud.githubusercontent.com/assets/737603/21454143/435ecba2-c916-11e6-9b8e-af32e7360e02.gif)
![29351](https://cloud.githubusercontent.com/assets/737603/21454144/435f44ba-c916-11e6-88e0-7f98e8af0e02.gif)
![29352](https://cloud.githubusercontent.com/assets/737603/21454145/43601264-c916-11e6-8263-85d14d81e5a4.gif)
![29353](https://cloud.githubusercontent.com/assets/737603/21454146/436140d0-c916-11e6-8da4-69155bf79720.gif)
![29354](https://cloud.githubusercontent.com/assets/737603/21454147/4362dfe4-c916-11e6-88b9-5d9a0c3592d0.gif)
![29355](https://cloud.githubusercontent.com/assets/737603/21454148/43726824-c916-11e6-8d7b-e3afc5a812a3.gif)
![29356](https://cloud.githubusercontent.com/assets/737603/21454149/43753572-c916-11e6-85c2-c95b840e60b6.gif)

**Comment by Gymnasiast** [comment]
What is new about the wooden RC sprites?

**Comment by marijnvdwerf** [comment]
![artboard 2](https://cloud.githubusercontent.com/assets/737603/21456287/3ce4f772-c927-11e6-95e3-1ca7e4f4a6a7.png)

They seem to be edited versions of `SPR_WOODEN_RC_BLOCK_BRAKES_SW_NE` and following sprites. (The originals are still in there. Except for the font, they're all additions)

**Comment by Gymnasiast** [comment]
Could anyone save a game or track that uses the new LIM pieces? It would help for reintroducing boosters (those from RCT1 and those from RCTC).

**Comment by marijnvdwerf** [comment]
The junior RC pieces seem to be based on `SPR_JUNIOR_RC_FLAT_CHAIN`  and `SPR_JUNIOR_RC_FLAT`


![27807](https://cloud.githubusercontent.com/assets/737603/21456750/a0c64e5a-c92a-11e6-8000-afc194094ac1.gif) ![27808](https://cloud.githubusercontent.com/assets/737603/21456749/a0c4ca8a-c92a-11e6-9743-0fab99606bbd.gif)

![27913](https://cloud.githubusercontent.com/assets/737603/21456696/5a77fd36-c92a-11e6-8e6e-e37c9c8242a2.gif) ![27914](https://cloud.githubusercontent.com/assets/737603/21456697/5a8dc922-c92a-11e6-9954-403651c2eb25.gif)

**Comment by PFCKrutonium** [comment]
@Gymnasiast I'll see what I can do... But I don't know if I can yet.

**Comment by marijnvdwerf** [comment]
Junior RC with booster piece

[Uploading Forest Frontiers jrc booster.sv6.zip…]()

**Comment by Jamaka2001** [comment]
@Gymnasiast Here is a BYOSixFlagsPark with both the Twister and Giga Coasters with LIM pieces. 
Link: http://www.mediafire.com/file/14enmqs02catpj9/Jamaka2001_LIM_Test.sv6

**Comment by Horsti12** [comment]
@marijnvdwerf How did you get the icons from the game?

**Comment by Gymnasiast** [comment]
@Jamaka2001 @marijnvdwerf Could you tell me what speed the booster pieces are set to?

**Comment by marijnvdwerf** [comment]
Junior RC: 32 km/h

**Comment by Gymnasiast** [comment]
I have put up a branch that restores boosters: https://github.com/Gymnasiast/OpenRCT2/tree/add-boosters

I'd like to hear from @Jamaka2001 (or anyone also who has RCTC and can load his park) what the launch speeds in his park are set to, so I can verify that the boosters are set correctly.

Some things I have observed:
- Boosters in RCTC and RCT1 use the same track element ID: 100. This is also used by the spinning control track that the Spinning Wild Mouse uses. My branch contains code to keep them apart, but it will need to properly look up the track it's running on.
- It looks like the brake speed divided by two is the (RCTC) launch speed, but again I would need verification.
- I have yet to test it with RCT1 style boosters. It might use the same brake-speed-to-launch-speed ratio, but there is no guarantee.

**Comment by Jamaka2001** [comment]
@Gymnasiast Apologies for the delay, was celebrating all day. Twister Coaster is 49 MPH and Giga Coaster is 89 MPH.

**Comment by Gymnasiast** [comment]
@Jamaka2001 Are you really sure about the Giga Coaster? It looks like it 39 or 40 MPH, not 89.

**Comment by Jamaka2001** [comment]
@Gymnasiast I'm sure I didn't build the launch section long enough but it is set to 89. http://imgur.com/JtPuR6f.png

**Comment by Gymnasiast** [comment]
It’s been six years, but it suddenly dawned upon me why those additional wooden rc block brake sprites are there. It’s to fix this issue:

![afbeelding](https://user-images.githubusercontent.com/1478678/184517524-b67bb7ab-1e57-4127-892d-4d1bd7f1351b.png)

**Comment by Gymnasiast** [comment]
We have now applied all relevant sprites. For the boosters, we went with custom ones, although this can be revisited if necessary.
