### ISSUE TITLE
Assertion Fail When Trying To Get On Multiplayer

### ISSUE THREAD

**Issue by ButterFlamingo** [OpenRCT2/OpenRCT2#4911]
**OS:** Widnows 10
**Version:** 0.0.5
**Commit/Build:** c44c93a

Sorry for forgetting this stuff earlier.

There are some online servers I try to join that just give me an Assertion Failure.

- [ ] Reproducible in RCT2 (vanilla)?
- [X] Multiplayer?

**Steps to reproduce:**
All I did is try to join a certain server. Nothing special.

**Screenshots / Video:**

![2016-12-22 19_10_49-microsoft visual c runtime library](https://cloud.githubusercontent.com/assets/24305712/21456281/eccc70bc-c8f4-11e6-8768-15a6b788b56c.png)
![2016-12-23 09_35_53-microsoft visual c runtime library](https://cloud.githubusercontent.com/assets/24305712/21456282/ecce38ac-c8f4-11e6-8dc9-99ec1352350f.png)

**Comment by Gymnasiast** [comment]
You didn't bother to fill in the fields. Please do so, we cannot help you otherwise.

**Comment by Nubbie** [comment]
@ButterFlamingo Please fill in what commit you are using but the screenshots are really helpful, thanks

**Comment by janisozaur** [comment]
@ButterFlamingo can you check if #4919 fixes it for you?

**Comment by Nubbie** [comment]
#4919 has been merged - this could be closed
