### ISSUE TITLE
server_greeting does not display

### ISSUE THREAD

**Issue by Sweet-Tan** [OpenRCT2/OpenRCT2#4913]
**OS:** Windows 7
**Version:** 0.0.5
**Commit/Build:** 35472fe

server_greeting does not display.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Enter string in server_greeting within config.ini
2. Start server
3. Connect to server, no greeting is displayed.

**Screenshots / Video:**
![capture](https://cloud.githubusercontent.com/assets/24423381/21463400/69e19288-c92e-11e6-9617-914f97265d25.PNG)

**Comment by telk5093** [comment]
I think only server can see the greeting message. Client-side can't see that.

**Comment by janisozaur** [comment]
If description of https://github.com/OpenRCT2/OpenRCT2/pull/4279 is to be believed, that's not the case. Also I cannot imagine what use would it be to only display this getting to the server itself.

**Comment by Ziscor** [comment]
After setting a greeting in the config.ini, it seems that that is the text that displays when you join _any_ server, not just when hosting your own.

**Comment by janisozaur** [comment]
This has been fixed in #5156
