### ISSUE TITLE
Can't get server to work

### ISSUE THREAD

**Issue by ButterFlamingo** [OpenRCT2/OpenRCT2#4914]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** c44c93a

I've port forwarded correctly. I've done everything. I *still* can't connect to the server. I'm not sure what to do. 

- [ ] Reproducible in RCT2 (vanilla)?
- [X] Multiplayer?

**Comment by Nubbie** [comment]
@ButterFlamingo Sorry for the late response but it's been much from everyone now this Christmas
You should try and start the server and use the website http://www.canyouseeme.org/ to see if the ports are opened correctly

**Comment by ButterFlamingo** [comment]
I got 'Connection Timed Out.'

**Comment by Nubbie** [comment]
@ButterFlamingo  You could try asking people on https://gitter.im/OpenRCT2/OpenRCT2/non-dev, might be a bit quicker
