### ISSUE TITLE
Allow maps bigger than 254x254

### ISSUE THREAD

**Issue by Margen67** [OpenRCT2/OpenRCT2#4933]
As of https://github.com/OpenRCT2/OpenRCT2/commit/20b1ce069f588b726ac969f598229fcd8f070c32 you cannot expand maps beyond 254x254.

**Comment by Nubbie** [comment]
It's planned to remove most restrictions but it's not possible without our own save format

**Comment by YoloSweggLord** [comment]
This restriction has always been in the game. It's been requested hundreds of times, we can't remove it until we switch to an independent save file format.

**Comment by YJSoft** [comment]
https://github.com/OpenRCT2/OpenRCT2/wiki/Increasing-of-game-limits

**Comment by KKLD** [comment]
The link says that removing the limit of "31 cars / trains per ride" is done but with the latest develop I cannot have more than 31 cars/trains for a ride. I can have up to 255 long trains but not more than 31 whole trains/cars/boats. Does this need a new save format or can this be done with the current one?

**Comment by duncanspumpkin** [comment]
@kkld that also requires a new save format
