### ISSUE TITLE
Server Greeting shows only for Host computer

### ISSUE THREAD

**Issue by Ziscor** [OpenRCT2/OpenRCT2#4934]
**OS:** Windows 7
**Multiplayer:** Yes

Not sure if this has always been this way and known about, but I don't see anywhere on GitHub acknowledging this.

**Steps to reproduce:**
1. Type some text in "server_greeting" in config.ini 
2. Host a server. 
3. The host can read the message as shown here: 
![1](https://cloud.githubusercontent.com/assets/18721353/21519347/63f453be-cd12-11e6-9e79-f01f00fd6445.PNG)
4. However, any joining user can not, as shown here:
![screen shot 2016-12-28 at 3 30 17 pm](https://cloud.githubusercontent.com/assets/18721353/21519411/bec5b1e8-cd12-11e6-8605-9a2ec60733f3.png)

Host was running 32-bit Windows 7 while the system with which I joined was running OS X, both of which were running the 0.0.5 Stable release.

**Comment by Ziscor** [comment]
My bad, I didn't see the just recently created issue by Sweet-Tan. Closing this. Sorry.

**Comment by janisozaur** [comment]
The other issue in question: https://github.com/OpenRCT2/OpenRCT2/issues/4913
