### ISSUE TITLE
Game crashes upon selecting objects in scenario editor

### ISSUE THREAD

**Issue by BigDirtyShitHog** [OpenRCT2/OpenRCT2#4944]
**OS:** Windows XP
**Version:** 0.0.6.0
**Commit/Build:** ae6ed29

Game crashes upon selecting objects in scenario editor.

**Steps to reproduce:**
1. Open scenario editor.
2. Click on the roller coasters tab.
3. Add all the coasters in the tab to the scenario.
4. Click on the transport ride tabs.

**Comment by Nubbie** [comment]
@BigDirtyShitHog 
If it crashed, did it create a dumpfile? And if so, can you post it here?

**Comment by jensj12** [comment]
I managed to reproduce this crash reliably:

1. (in any game) Open object selection
2. Enable advanced and go to walls/fences
3. Search for 'ball'
4. It will crash when typing the second 'l'

The game doesn't create a dump file.
![orctcrash6](https://cloud.githubusercontent.com/assets/13868449/21549992/73ece404-cdf6-11e6-995d-126b22611482.png)

**Comment by Nubbie** [comment]
Could not reproduce the crash - Custom objects?

**Comment by BigDirtyShitHog** [comment]
No custom objects, just the build of Open RCT2. I don't even know what half this stuff is Im still very new to ORCT2.
