### ISSUE TITLE
Assertion Fail

### ISSUE THREAD

**Issue by ButterFlamingo** [OpenRCT2/OpenRCT2#4948]
**OS:** Windows 10
**Version:** 0.0.6
**Commit/Build:** ae6ed29

Another Assertion Fail on Multiplayer

- [ ] Reproducible in RCT2 (vanilla)?
- [X] Multiplayer?

I was on a server when this showed up and my game crashed.

**Screenshots / Video:**
![2016-12-29 14_30_51-openrct2](https://cloud.githubusercontent.com/assets/24305712/21553043/e5607448-cdd3-11e6-8a91-f4529cedc168.png)

**Comment by janisozaur** [comment]
Without more information (save, dump) we cannot do anything about it.
