### ISSUE TITLE
Balloon jumps away from cursor when trying to pop it.

### ISSUE THREAD

**Issue by Jargonius** [OpenRCT2/OpenRCT2#4949]
Windows 10
0.0.6.0
develop-004395a

I was scrolled near the top where it was mostly black and when I tried to click the balloon it jumped slightly in either direction away from my cursor.  I was able to pop one lower on the map.

**Comment by Jargonius** [comment]
Oh.  Oops!

**Comment by Jargonius** [comment]
Do we want to make that a toggle in the options or is that just trivial?

**Comment by IntelOrca** [comment]
There are more important things to do right now, balloon poping has no value to gameplay and is just a gimmick.

**Comment by Jargonius** [comment]
Okay
