### ISSUE TITLE
Invalid Characters Used

### ISSUE THREAD

**Issue by GravityUnown** [OpenRCT2/OpenRCT2#4952]
**OS:** [Mac OS Sierra]
**Version:** [e.g. 0.0.6]
**Commit/Build:** 1805

I hadn't played OpenRCT2 in a while, so I opened it back up, and the launcher performed an update like usual. The problem I am experiencing right now is that some of my save files will not load and I get a red box upon clicking it saying "Invalid Characters Used." I'm not sure what exactly this means since they loaded perfectly fine in earlier builds of the game

**Steps to reproduce:**
1. Open the Game
2. Load a save file

**Comment by janisozaur** [comment]
1805 is not a valid commit. Also ulpoading said files would actually let us test it.

**Comment by GravityUnown** [comment]
You can actually disregard this entire issue tracker, the issue was that the game does not accept colons in save file names anymore for some reason, and by renaming the save file it loads properly again.

I sincerely apologize for not remembering to upload the save file. Also that number is what it read for the OpenRCT2 build when I opened up the launcher so I'm not sure what exactly the real number is.

**Comment by Gymnasiast** [comment]
The build hash is displayed in the title screen and consists of seven characters. An example would be a1b23c4.

**Comment by GravityUnown** [comment]
Oh so it's the hash number then. That probably should have been specified in the template when making a new topic here, to be honest.

**Comment by IntelOrca** [comment]
It gives you an example of what it should look like. It also says in contributing.md which it says to read at the top of the create issue page.
