### ISSUE TITLE
Vehicle previews for inverted/suspended vehicles glitchy

### ISSUE THREAD

**Issue by TwilightSlick** [OpenRCT2/OpenRCT2#4955]
**OS:** Windows 10 x64 (also occurs in Mac OS 10.12)
**Version:** 0.06
**Commit/Build:** 99a662f

There is a visual bug in the ride window for certain tracked rides, specifically those that have inverted or suspended vehicle types (e.g. Inverted Coaster, Suspended Swinging Coaster, Chairlift, Suspended Monorail, etc.) where the vehicle is underneath the track.

The vehicle tab icon should show the entire vehicle, but instead the vehicle tab icon shows only half of the vehicle, as if the point that the vehicle hangs onto the track is centered instead of the center of the vehicle itself.

This bug does not occur in vanilla, vanilla exhibits the correct behavior of the vehicle tab's icon, as shown in the screens.

**Steps to reproduce:**
1. Open the ride window of any tracked ride in which the vehicles are suspended underneath the track (any Inverted Coaster, Suspended Swinging Coaster, Chairlift, Suspended Monorail, etc.) NOTE: this bug does not occur on the Multi-Dimensional Coaster.
2.  Observe the icon of the vehicle tab in the ride window.

**Screenshots**
-Vanilla:
<img width="166" alt="scr1" src="https://cloud.githubusercontent.com/assets/20235887/21575555/dfc35f36-cedd-11e6-9254-71be16e5667a.png"> 
-OpenRCT2:
<img width="169" alt="six flags holland 2016-12-30 22-04-16" src="https://cloud.githubusercontent.com/assets/20235887/21575556/efc61d42-cedd-11e6-8588-300a495d23ab.png"> 

**

**Comment by rpstester** [comment]
#6199 is an example of this and probably a duplicate.

**Comment by Gymnasiast** [comment]
As of 3c1bdcd20140fcd3d374818b9defb80c12c39163 , this issue appears to be fixed.
