### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by pawelkondraciuk** [OpenRCT2/OpenRCT2#4957]
**OS:** OSX 10.11.6
**Version:** 0.0.6
**Commit/Build:** a10de67

Random crashes when playing first map not related with any save games. 

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Dump file**
[crash.txt](https://github.com/OpenRCT2/OpenRCT2/files/679585/crash.txt)

**Comment by janisozaur** [comment]
> `Assertion failed: (_windowNewRideCurrentTab < countof(_windowNewRideHighlightedItem)), function window_new_ride_scroll_to_focused_ride, file /Users/travis/build/OpenRCT2/OpenRCT2/src/windows/new_ride.c, line 394.`

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff8500df06 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff8bdbc4ec pthread_kill + 90
2   libsystem_c.dylib             	0x00007fff8fe7f6df abort + 129
3   libsystem_c.dylib             	0x00007fff8fe46dd8 __assert_rtn + 321
4   website.openrct2.OpenRCT2     	0x0000000100227b40 window_new_ride_scroll_to_focused_ride + 240
5   website.openrct2.OpenRCT2     	0x0000000100227935 window_new_ride_open + 211
6   website.openrct2.OpenRCT2     	0x00000001001f1922 game_handle_input + 134
7   website.openrct2.OpenRCT2     	0x00000001001f4ec5 rct2_update + 144
8   website.openrct2.OpenRCT2     	0x000000010012a463 openrct2_launch + 333
9   website.openrct2.OpenRCT2     	0x00000001000c40a6 main + 43
10  website.openrct2.OpenRCT2     	0x0000000100001184 start + 52
```

Guarded since https://github.com/OpenRCT2/OpenRCT2/commit/729ac135379122f5c8adcf4e30ef7a9985a20b18

**Comment by janisozaur** [comment]
Moved to #4958
