### ISSUE TITLE
Shouldn't need to use "sudo" everywhere in the install script

### ISSUE THREAD

**Issue by kevinburke** [OpenRCT2/OpenRCT2#496]
Homebrew sets up /usr/local so its readable and writable by your current user. This is part of the reason why it's a good package manager for OS X: no "Permission Denied" errors.

The current install script uses many calls to `sudo` which means files and directories get created as the root user. Sudo should not be used as liberally (or at all).

**Comment by IntelOrca** [comment]
Closing as replaced with duplicate issue #1696.
