### ISSUE TITLE
Game glitches when reaching the sprite limit

### ISSUE THREAD

**Issue by ccoors** [OpenRCT2/OpenRCT2#4973]
**OS:** Arch Linux
**Version:** 0.0.6
**Commit/Build:** 3e70ea9

When reaching the 10000 sprite limit (I guess, as my test had 9600 guests) the game sometimes shows graphical glitches. I attached a saved game which shows this behavior.

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Create a small park
2. Add as many guests as possible and prevent them from leaving
3. In some cases a graphical glitch occurs

The original game also shows this and may crash.

**Screenshots / Video:**
![unnamed park 2017-01-02 00-06-21](https://cloud.githubusercontent.com/assets/8963459/21593448/89dae3fa-d117-11e6-9705-64f91b43e33d.png)
![unnamed park 2017-01-02 00-06-20](https://cloud.githubusercontent.com/assets/8963459/21593446/86b215ae-d117-11e6-8471-4c96dfa2ce94.png)

**Save game:**
[Glitch.zip](https://github.com/OpenRCT2/OpenRCT2/files/681162/Glitch.zip)

**Comment by duncanspumpkin** [comment]
Ahh this is different to what i thought you were talking about this is already a known issue.

**Comment by duncanspumpkin** [comment]
https://github.com/OpenRCT2/OpenRCT2/issues/1738
