### ISSUE TITLE
Scenario completition: Can't enter name, no progress

### ISSUE THREAD

**Issue by nummacway** [OpenRCT2/OpenRCT2#4976]
**OS:** Windows 7
**Version:** 0,0,5 (release)

When I complete a scenario, the "enter name" button sometimes does not appear, even if this is my first attempt for that scenario (so it doesn't matter if I reached a new high score which I know would usually cause that button to not appear). I then have to reload a savegame several times until that button appears after a win. Without that button appearing, no new scenarios are unlocked either. This happened to me multiple times in multiple scenarios, yet it's random.

**Comment by Nubbie** [comment]
This has been reported before on [the forum ](https://openrct2.org/forums/topic/2275-cant-finish-scenario-no-putting-in-name-button/#comment-12572)and on Github #2851

**Comment by IntelOrca** [comment]
This has been fixed in the latest version, you will have to switch to the develop builds.

**Comment by provoaggie** [comment]
![cantentername](https://user-images.githubusercontent.com/4186219/33503372-b568edb6-d6a0-11e7-8ff6-9563eecb4ff0.png)

I'm having this issue again. I was on the current Stable build. I wanted to check if it was fixed so I switched to the Develop branch. I have my game saved 2 days prior to the scenario ending and have tried several times. Unfortunately it never let's me enter my name and as a result it never marks that I've completed the Scenario.

OS: Windows 10 64-Bit
Version: 0.1.2-develop build 1f456d3

**Comment by Gymnasiast** [comment]
@provoaggie Most WW / TT scenarios have an incorrectly set scenario name. Consider any save started before it was fixed broken.

**Comment by provoaggie** [comment]
I started the scenario yesterday with the current stable release. It should have been fixed prior to that. I'll try starting the scenario again with the current development branch as well but so far the stable branch save hasn't worked.
