### ISSUE TITLE
Remove magic numbers

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#4978]
The codebase contains many magic values at the moment. Those should be cleaned up, both for reasons of code readability and for easing the migration to our own file format in the future.

N.B.: many of these will require separate constants for importing/exporting to and from RCT1 and RCT2 and for use in OpenRCT2 itself.

The magic values are:
* - [x] Maximum number of stations (4) (occurrence in ride_ratings.c left)
* - [x] SPRITE_INDEX_NULL (A constant exists, but there are many occurrences that don't use it)
* - [ ] Maximum map size, at least for the S4 importer
* - [x] RCT1 walls - some are special cases - see ConvertWalls() ( https://github.com/OpenRCT2/OpenRCT2/pull/11222 )
* - [x] Maximum number of park entrances
* - [x] Metal support types
  * - [x] metal_a_supports_paint_setup()
  * - [x] metal_b_supports_paint_setup()
  * - [x] https://github.com/OpenRCT2/OpenRCT2/pull/5111#pullrequestreview-18108518 ( https://github.com/OpenRCT2/OpenRCT2/pull/11625 )
* - [x] Usage of 216 to mean TRACK_ELEM_BLOCK_BRAKE
* - [x] Top toolbar clearance: 28

**Comment by janisozaur** [comment]
`MAX_PATH` is defined in more than one place.
https://github.com/OpenRCT2/OpenRCT2/blob/4669756d3ee3281d66b94424d174c6658ae3aba1/src/scenario/ScenarioRepository.h#L22
The other one in platform directory. It should start getting defined to `PATH_MAX` on Linux.

**Comment by IntelOrca** [comment]
`PATH_MAX` can be typically 4096 bytes, is it possible that this exceeds the stack size limit for methods which define multiple paths on the stack?

**Comment by janisozaur** [comment]
```bash
$ ulimit -s
8192
```
8192 kbytes looks plenty.

**Comment by marijnvdwerf** [comment]
```
91: Number of ride types
256: Number of track types
```
