### ISSUE TITLE
Introduce the repair broken path scenery system from RCT Classic

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#4984]
Suggestion: introduce the repair system of any broken path scenery, caused by vandalism, from RCT Classic. With this system, you can click on the repair button at the path scenery "window" and all broken path scenery gets bright red, so you can easily see the broken benches, lamps and trash bins. This would make it much easier for users to manage vandalism with much larger parks. You could also say: why not just use the cheat to do this, but this would take the whole management feeling away.

Personally, I would activate this option by default: people can always choose not to click the repair button and just manually replace the path scenery. Also as @marijnvdwerf I think, didn't mention any new red sprites were added to RCTC to make this possible, I think they just did it by adjusting the color pallet of the path scenery to make it red?

Also, it seems like, unlike vanilla RCT2, you can repair the path scenery through this option for a discounted price. But correct me if I'm wrong.

**Comment by Gymnasiast** [comment]
Lighting up vandalism is within the classic-style gameplay IMO, and doesn't need to be optional.

**Comment by duncanspumpkin** [comment]
It would not be too hard to make the sprites render red. This is all very feasable

**Comment by marijnvdwerf** [comment]
Might be more interesting to implement the "vandalism highlights" as some kind of data layer, with vandalism being the first. Make everything render dark gray/white, except for interesting parts.

**Comment by mrtnptrs** [comment]
@marijnvdwerf Indeed, that would be even better. It could just use the invisible attractions, scenery etc. options.

**Comment by rwjuk** [comment]
Implemented in #6996.
