### ISSUE TITLE
Rising land from underwater while there are boats causes them to appear floating on land

### ISSUE THREAD

**Issue by ccoors** [OpenRCT2/OpenRCT2#4988]
**OS:** Arch Linux
**Version:** 0.0.6
**Commit/Build:** 67c2ab88495c09041c5b7dd9b27c49c17c21b93f

Raising the land under the water with boats or other 'free' water rides on it causes the boats to be floating on the land or inside the land.

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Start a game on electric fields
2. Raise the land under a boat of Rowing Boats 1

I'm not sure what should happen in that case. Maybe that error message "Ride ... is in the way".

**Screenshots / Video:**
![glitch](https://cloud.githubusercontent.com/assets/8963459/21649376/cf4946da-d2a1-11e6-90cd-1453871b4251.png)

**Comment by Gymnasiast** [comment]
I doubt there is a better way of handling this scenario.

**Comment by Nubbie** [comment]
Pretty much just two things that could be done

1. Telling the player it's in the way
2. Kicking them off the ride

**Comment by Patrik356b** [comment]
1. could be troublesome in certain cases
2. is probably a better solution

**Comment by Gymnasiast** [comment]
Hm, both of Nubbie's suggestions don't sound very easy to implement cleanly and reliably. I would say boats navigating on load isn't really a big deal and not worth adding too much complexity for. I'm happy to be proven wrong about this, but in the meantime I'm going to label this `wontfix` for the reasons I stated.
