### ISSUE TITLE
Removing duplicate rides/attractions

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#499]
I've brought this up previously, but it's a rather major issue.
![1412118636614](https://cloud.githubusercontent.com/assets/4167951/4485368/3d1e69aa-49ca-11e4-822f-fc91fad5b3ae.png)
Currently in my OpenRCT2 Object Data, for whichever reason several of the rides in the folder, despite having different filenames, both produce the exact same ride/attraction when loaded into the game. If there could be some way for OpenRCT2 to identify the newest of the two .DAT files producing the same ride/attraction and make it invisible, to avoid an error like below:

![screen shot 2014-10-01 at 8 34 03 pm](https://cloud.githubusercontent.com/assets/4167951/4485462/e135d19e-49cb-11e4-9b67-ad86658722a6.png)

**Comment by Gymnasiast** [comment]
Since this issue report, some bugs in original object detection have been fixed, filtering has been added and (using debugging tools) one can now see the filename of any duplicates left.

The content downloader is not related to this bugs.

For these reasons I'm closing this.
