### ISSUE TITLE
Helix track peices are available for Lay Down coaster

### ISSUE THREAD

**Issue by LeoStaley** [OpenRCT2/OpenRCT2#4991]
**OS:** [Windows 7]
**Version:** 0.0.5
**Commit/Build:** dunno

My My original reddit post was this: 

>## **Helix up and helix down don't render for Laying Down coaster when it is inverted. it'll still build and run on it, it's just flying on invisible track.**
>[Here's an album with screenshots.](http://imgur.com/a/xUt05). 
>I have v 0.0.5 installed, but the dev version, from like 2 days before the stable release. I can't figure out how to find the actual installed version. I'm dumb.

**X7123M3-256** replied with this:
>The lay-down coaster does not support helices on inverted track, so the bug is that the piece is available, not that it doesn't render.
>I'd suggest submitting an issue about it on[ here](https://github.com/OpenRCT2/OpenRCT2/issues)

I don't know if he's right. I just copied and pasted. Please forgive the overall shitiness of this post.

**Comment by IntelOrca** [comment]
Is it possible to build inverted helixes in vanilla RCT2?

**Comment by Gymnasiast** [comment]
No, it isn't. Just tested it.

**Comment by LeoStaley** [comment]
Well dammit, I want helixes in my inverted lay down coasters. they're better that way.

**Comment by Gymnasiast** [comment]
I still have to look into this. If there is nothing preventing me from it, I _might_ just add drawing code for them and solve it that way.
