### ISSUE TITLE
Able to remove entrance/exit of unedittable rides (such as in Volcania)

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#5003]
**OS:** Windows 10
**Version:** 0.0.6
**Commit/Build:** 73d1c6a

It is able to remove entrance/exit which is unedittable such as in Volcania scenario in LL
Sorry if it is duplicated.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Apply RCT1 scenario to OpenRCT2 and open Volcania scenario
2. Double click entrance/exit which is unedittable.
3. Entrance/exit is removed and occurs error if you try to re-put it.

**Comment by Gymnasiast** [comment]
Did you use an SV4 or SC4 file, or a SC6 or SV6 file?

**Comment by telk5093** [comment]
@Gymnasiast I used SC6 that is converted for RCT2
