### ISSUE TITLE
RCT 1 import people differences

### ISSUE THREAD

**Issue by ccoors** [OpenRCT2/OpenRCT2#5004]
**OS:** Arch Linux/Windows XP (for RCT 1)
**Version:** 0.0.6
**Commit/Build:** bd140e78fbce2928d097709d70e8a383336065e5

When importing a scenario from RCT 1, the people that are already in the park show some abnormalities.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open a RCT 1 scenario with guests already in it (for example sc1.sc4, Dynamite Dunes)
2. Some people, which haven't entered the park yet, are frozen
3. The people, that have already been in the park, have spent a ridiculous amount of time there

**Screenshots / Video:**
RCT1:
![rct1_timespent](https://cloud.githubusercontent.com/assets/8963459/21724752/ed0faf70-d435-11e6-81f4-98ab6c895c41.png)

OpenRCT2 (same guest, directly after starting the scenario):
![openrct2_1](https://cloud.githubusercontent.com/assets/8963459/21724776/fa813e26-d435-11e6-8cb3-5c93d00ba87e.png)

Video of frozen people:
![rct1](https://cloud.githubusercontent.com/assets/8963459/21724423/8ec1b126-d434-11e6-9e1c-970e0e5f680d.gif)

**Comment by Gymnasiast** [comment]
Could you upload your save?

**Comment by ccoors** [comment]
Isn't that a bit problematic, as it is basically just a scenario from RCT 1?

**Comment by Gymnasiast** [comment]
Oh, didn't read that properly. If just opening Dynamite Dunes is sufficient, then you don't have to upload anything.

**Comment by ccoors** [comment]
Well, if I could I would create an original RCT 1 scenario which shows this bug, but unfortunately RCT 1 didn't contain a scenario editor.

**Comment by Gymnasiast** [comment]
No, I own RCT1 and I have it running. That's sufficient to test.

**Comment by Christian-Seematter** [comment]
I just started Dynamite Dunes from the Scenario Folder in OpenRCT2 0.0.7 build 7005d5d on windows, and I do not have any people being stuck and not moving. The age issue is still there though.

![2017-02-23 13_58_12-openrct2](https://cloud.githubusercontent.com/assets/1957259/23260172/dbc3ae72-f9d0-11e6-8bec-9011e514cced.png)
