### ISSUE TITLE
Openrct2 Object Selection bug

### ISSUE THREAD

**Issue by xp4xbox** [OpenRCT2/OpenRCT2#5006]
Windows 7
v0.0.6
fa51d15

In the object selection, for example if you type roof and then type z or something that would leave the object selection blank, if you type in any other character including backspace the game crashes. It also crashes if you change tabs when the object selection is blank or try to close it. It is been happening recently for some reason and I don't recall it happening a few months ago.

- [no ] Reproducible in RCT2 (vanilla)?
- [both ] Multiplayer?

**Steps to reproduce:**
1. open object selection
2. type in random characters one at a time until nothing shows up in the object selection.
3. type any character, click on another tab or click on the X button, and the game will crash

**Screenshots / Video:**
https://vid.me/s0PW

**Comment by Nubbie** [comment]
Did it create a dumpfile? and if so, upload it here

**Comment by janisozaur** [comment]
Duplicate
