### ISSUE TITLE
Rating overflow bug (with cheating)

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#5009]
**OS:** Windows 10
**Version:** 0.0.6
**Commit/Build:** 73d1c6a

I doubt that this rating bug should be fixed even though this is occured by using many cheats, but I report it anyway.
Ratings overflow in a certain condition as you can see in the screenshot below.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Make a very long distance rollercoaster with power launched mode, maximum speed(922km/h). (chain all tracks if you can)
2. Check "Allow arbitrary ride type change" cheat.
3. Change the rollercoaster's type into Launched Freefall
4. Excitement rate returns over hundred, and others return negative rating with wrong rating strings

**Dump file**

**Screenshots / Video:**
![image](https://cloud.githubusercontent.com/assets/10726524/21739909/091e0b06-d4ec-11e6-8def-a3e37f0e8e1a.png)

**Save game:**
[12.zip](https://github.com/OpenRCT2/OpenRCT2/files/691305/12.zip)

**Comment by Gymnasiast** [comment]
Since it doesn't cause a crash and since it can only happen with very strange combinations, I agree with you it's not worth to fix it. (And it's sort-of fun to see it glitch like this :P)

**Comment by IntelOrca** [comment]
I am re-opening this because I think we still need to cap the ratings between the range we expect. As you can see the strings after the ratings are wrong due to them being negative. Things like this can cause crashes or unexpected behaviour.
