### ISSUE TITLE
No rides when importing the sandbox park from RCT1. (RCTOA Acres)

### ISSUE THREAD

**Issue by Horsti12** [OpenRCT2/OpenRCT2#5014]
In RCT there was an inofficial park called RCTOA Acres. It is a flat park where you have all rides available which were in rct1 (rct1+aa+ll). But when I import the park into openrct2 it has no rides (none selected in the object selection)

You can download the park [here](http://www.jumpjet.info/Classic-Games/Windows/RCT/Scenarios/rctoa.zip)
![screenshot_9](https://cloud.githubusercontent.com/assets/12634026/21745186/a2904dce-d525-11e6-8244-61a6a0dcf057.png)

**Comment by Gymnasiast** [comment]
This happens with more parks. If you import Ivory Towers the Canoes are not available, even though a boat hire with canoes is present in the park.
