### ISSUE TITLE
Tile inspector should be available in multiplayer

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#5021]
**Version:** 0.0.6-develop

Tile inspector, one of the prominent OpenRCT2 additions, calls all the functions directly to modify global game state. This makes it unusable for multiplayer, as it only affects client's local state.

It is currently hidden in multiplayer, but with recent emergence of high profile servers, especially https://nedesigns.com one, there is an interest in having this feature available for multiplayer as well.

This issue is meant to track progress of converting tile inspector from using direct calls to using our engine event loop based on `game_do_command` calls.

Things to do:

## Modify element

- [ ] common actions (not element specific)
  - [ ] rotate selected
  - [ ] copy (keep client-only)
  - [ ] change base height (take multiple tiles into account)
- [ ] surface
  - [ ] remove/restore park fences
  - [ ] toggle raised corner flag
  - [ ] toggle diagonal flag
- [ ] path
  - [ ] toggle connected edges and corners
  - [ ] toggle slope (missing, should be added)
- [ ] track
  - [ ] toggle chain lift (take multiple tiles into account)
- [ ] scenery
  - [ ] select quadrant location
  - [ ] toggle colliding quadrants
- [ ] entrance
- [ ] fence
  - [ ] change slope
- [ ] large scenery
- [ ] banner
  - [ ] toggle blocking paths
- [ ] corrupt elements
  - [ ] clamp to next element

## Modify tile

- [ ] insert corrupt
- [ ] remove element
- [ ] move up/down in the list
- [ ] sort
- [ ] paste (uncertain, if we can send an entire map element?)

**Comment by janisozaur** [comment]
I have assigned this to myself for now, as I will try spearheading the effort, but others are welcome to contribute too. Looking at you @Broxzier ;)

**Comment by Margen67** [comment]
Duplicate of #3245?

**Comment by janisozaur** [comment]
Part of it or a sub-issue. There are more debug tools than just TI.

**Comment by IntelOrca** [comment]
One way you could do this, is send the entire tile to the server which replaces the old one. It would reduce parameterising the game command to all the different things it needs to do.

**Comment by Broxzier** [comment]
@IntelOrca: For large elements (track pieces, large scenery) they cover multiple tiles. If more than one person is working on the same tile, their changes might be overwritten.

**Comment by IntelOrca** [comment]
> For large elements (track pieces, large scenery) they cover multiple tiles, so then multiple tiles will need to be sent over

I suppose you could send all of them, but I hadn't thought about this so maybe it's not such a good idea.

> Another issue with that is that when more than one person is working on the same tile, their changes might be overwritten.

I wouldn't worry about that - that's going to cause problems either way, they would only lose one or two changes anyway.

**Comment by janisozaur** [comment]
@Broxzier in case you are not familiar with our event loop, it goes roughly like this:

1. Player wants to perform some action
2. Player's client validates if it is a sane thing to do
3. If it is, the action gets sent over network to server for being enqueued (without executing it on the client)
4. Server starts processing input queue collected from all the clients, in particular the command sent by us
4. Server validates if the command is a sane thing to do *again* (never trust remote client)
5. If it performs the action successfully, it is registered and sent out to all connected clients
6. Server finishes processing of current game tick and all the clients get notified the simulation has moved on to new frame
7. All clients should have received the messages sent out by the server *in order* and start processing local queue of actions
8. Goto 1.

This skips some details, but provides a general idea of how it all works.

Yes, some changes may get overwritten if two users modify the same tile in a compatible way, but they would be overwritten atomically, so there's no danger of ending up in some state in between. It will be either player A's or player B's state.

However, until we do refactor of game commands, there's limited space in arguments and it might turn out better to perform what it does now, only from within game command handler.

**Comment by Nubbie** [comment]
How demanded is it?

**Comment by Broxzier** [comment]
@Nubbie Quote from janisozaur on gitter:
> nedesigns folks requested that as their #1 feature that's missing from MP

_"that"_ meaning this request

I'm curious to see where they ask for this.

**Comment by janisozaur** [comment]
I asked some people when I was connected to their server. Sadly, it was on another person's computer and I don't have the logs to prove.

**Comment by Nubbie** [comment]
Doesn't that always happen when someone ask for something? They always want more and more not thinking about the complications?
It's a feature people would say yes to but doesn't mean it would be used

**Comment by janisozaur** [comment]
This is a valid point, @Nubbie. I asked them this question: http://www.nedesigns.com/topic/32012/openrct-advantages-and-disadvantages/?p=713117

Getting TI in MP will be some work, but I think it is quite useful and I would like to see all our tools being available in MP just like in SP. At this point I'm willing to spend some time porting it and so does @Broxzier, so I see no reason why can't we just do it ;)

**Comment by janisozaur** [comment]
The responses so far from the thread:

> ^being able to use tile_inspector. I find it quite annoying having to delay my park, because I need to go into tile inspector to do something.

-- `nicman` http://www.nedesigns.com/topic/32012/openrct-advantages-and-disadvantages/?p=713118


> Multiplayer is just incredible, well done.

-- `Louis!` http://www.nedesigns.com/topic/32012/openrct-advantages-and-disadvantages/?p=713119

> The only thing missing from multiplayer is the tile inspector. Other than that, it's perfect.

-- `GammaZero` http://www.nedesigns.com/topic/32012/openrct-advantages-and-disadvantages/?p=713140

I asked for input from some more acknowledged members of their community, but so far it looks like TI missing is indeed a hurdle to them.

**Comment by Nubbie** [comment]
@janisozaur 
Lous quote doesn't say much about it and Nicman is more from multiplayer in general than NEdesign, but I get the point and if plausable, go for it :p

**Comment by janisozaur** [comment]
Implemented in #5110
