### ISSUE TITLE
Invalid window_limit setting can cause crash

### ISSUE THREAD

**Issue by Lastorder-DC** [OpenRCT2/OpenRCT2#5029]
**OS:** Windows 10
**Version:** 0.0.6
**Commit/Build:** 7c7b67f

Setting window_limit to 0(or can parsed to 0) by editing config.ini will cause immediate crash.
Setting window_limit to below 4(like 1) will cause crash when trying to open any window(new game, config window, etc)

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Comment by Nubbie** [comment]
Same happens if you overflow it with 256 of course
Check for that and return to default value?

**Comment by wolfreak99** [comment]
I will fix this tomorrow, @IntelOrca could you assign me to this so I can remember to look into it?

**Comment by IntelOrca** [comment]
@wolfreak99 GitHub only allows me to assign users with write access to the repository.
