### ISSUE TITLE
SV6 Export to RCTC

### ISSUE THREAD

**Issue by marizzz95** [OpenRCT2/OpenRCT2#5035]
I'm not sure if this has been looked into, but maybe this can help finding a way to export saves into RCTC, because right now that does not work.
Using the 'rct2-save-game-modifier.exe' - tool I can see exactly how the classic saves differ from the original. 
Not only the classic_flag is set at 0x07, but classic saves also have a different header signature.
![skizze](https://cloud.githubusercontent.com/assets/25037601/21821504/1dcc678e-d774-11e6-9e7b-8852f5ce4723.png)
Hope this helps.

**Comment by IntelOrca** [comment]
I don't think its worth it as we will soon move away from SV6 altogether.

**Comment by Gymnasiast** [comment]
Neither do I.
We will always support _importing_ SV6 files though.

**Comment by Invictaz** [comment]
@marizzz95 already found a way to import into RCTC yet?

**Comment by PFCKrutonium** [comment]
@Invictaz Afaik the game itself supports importing original parks via one of the DLC?

**Comment by Invictaz** [comment]
@Krutonium You need the toolbox add-on for this AFAIK which costs an additional which they re-released in 2019.
https://play.google.com/store/apps/details?id=com.atari.mobile.rctclassic&hl=nl
