### ISSUE TITLE
Remove -1 pointers

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#5037]
RCT2 used the value -1 instead of 0 for a lot of pointers to mean uninitialised. The most common being object entries. We now have a mixture which isn't good, we need to search and destroy all these -1s and use nullptr.

**Comment by janisozaur** [comment]
👍 👍 👍 👍 👍 

This was so painful when doing 64 bit build.

**Comment by janisozaur** [comment]
Actually, this confuses me a little.

One universal truth about hardware is that it can compare against 0 more efficiently than against anything else. How come -1 was chosen as *the* invalid value in a handwritten assembly?

**Comment by IntelOrca** [comment]
Ask Chris, he even used it for his own malloc function

**Comment by Gymnasiast** [comment]
Perhaps because 0 is a valid value in a lot of places (indices, etc.). I think CS didn't want to make it harder for himself than necessary.

**Comment by IntelOrca** [comment]
> One universal truth about hardware is that it can compare against 0 more efficiently than against anything else.

Maybe back in the day pre-RCT.

**Comment by Gymnasiast** [comment]
AFAICS, the -1 pointers are now all gone. So I guess this can be closed?
