### ISSUE TITLE
Make money fields clickable in order to type input

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#5038]
This is something that will have to wait until our new window system is here, as it's currently a pain in the behind.

#4879 introduced code to parse input.

**Comment by wolfreak99** [comment]
Hey if there is any specific fields that you want me to link the money_to_string and string_to_money to, i have no problem doing that. it'll be something fairly simple, as i've grasped the majority of the current ui code functionality. it'll be something small and simple for me to work on while i just take a break from all the big pull requests i do.

**Comment by Gymnasiast** [comment]
It's probably better to wait until the new window system is here, as the less code we have to port, the better. Also, the string_to_money function will need to be further tested, while the money_to_string function might be just replaced with format_currency. Those would need a look first.

**Comment by wolfreak99** [comment]
I noticed on some currencies the whole decimal is a bit awkward, but i wasn't able to find any variable or definition that always included conversion rates, the only exception was for the custom currency. format currency includes commas which i particularly didn't care for as it would make adding 0's lazily a bit awkward, though then again people would eventually get used to typing with commas. idk. how do you feel about commas showing up in the raw value shown?

**Comment by KatieZeldaKat** [comment]
This issue should probably be closed since the functionality has been implemented for a while now.
