### ISSUE TITLE
Money string in the cheats window changes colour

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#5040]
![image](https://files.gitter.im/OpenRCT2/team/FZ38/thumb/blob.png)

This issue can be triggered by changing the theme with this window open.
@wolfreak99 can you address this?

**Comment by wolfreak99** [comment]
I'm not really sure how i'd go about doing it. it also does the same thing to the misc tab with the park rating. i'm assuming somethings not working right with the update colour scheme function in invalidate, i'll see if i can't play around and get it to work.
