### ISSUE TITLE
__ENABLE_LIGHTFX__ as a BETA option in settings

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#5048]
Allowing players to test and use a feature that's placed in the game - Even tho it's in a bit off a 'freeze', it is a impressive beta feature to show off, even in its conditions

Just having a checkbox with a tick to toggle have it on/off would be enough with a clarification off it being a beta feature

**Comment by Gymnasiast** [comment]
It doesn't work like this, unfortunately. It's a compile-time thing, not run-time.

**Comment by Nubbie** [comment]
@Gymnasiast Indeed you need to do it while compiling, but implying this couldn't get compiled without the __ENABLE_LIGHTFX__  restriction and pushed on/off with a checkbox?

**Comment by Gymnasiast** [comment]
The reason it's a compile-time option in the first place is that the code can affect a lot of other stuff, even when the feature is not used.

**Comment by duncanspumpkin** [comment]
Its very tightly coupled at present so it has to be compile time only.

**Comment by IntelOrca** [comment]
> The reason it's a compile-time option in the first place is that the code can affect a lot of other stuff, even when the feature is not used.

Not really
