### ISSUE TITLE
Game Crashes When Trying To Select Groups In The Filter Menu In Object Selection

### ISSUE THREAD

**Issue by WhenPenguinsAttack** [OpenRCT2/OpenRCT2#5057]
**OS:** Windows 10
**Version:** 0.0.6
**Commit/Build:** ebf479d

Whenever I try and select groups (Rollercoaster Tycoon 2, Wacky Worlds, Custom, etc) in the filter menu in the object selection window, the game crashes.  It works when you're deselecting groups, but crashes the other way around.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open any game (but first noticed it with this saved game: https://openrct2.org/forums/topic/1508-group-park-4/?page=29#comment-12783 )
2. Go to the object selection menu.
3.) Try to select (not deselect) a group in the filter menu.

**Comment by janisozaur** [comment]
*Yet another* duplicate. Did you even try searching?

**Comment by Nubbie** [comment]
@janisozaur At the same time, it's a common issue nowadays it seems to duplicates will pop up eventually 😞
