### ISSUE TITLE
Path scenery behind small hills has wrong z-index

### ISSUE THREAD

**Issue by ccoors** [OpenRCT2/OpenRCT2#5064]
**OS:** Arch Linux
**Version:** 0.0.6
**Commit/Build:** f94daa08d

When placing path scenery directly behind a small hill, one can still see it. Happens in vanilla too.
Interestingly, for benches the behavior is correct, for all the other scenery it isn't.

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Build a path directly behind a slope
2. Place path scenery on that path

**Screenshots / Video:**
![bench](https://cloud.githubusercontent.com/assets/8963459/21927098/f90615c2-d984-11e6-8d7b-869074422c7c.png)
![lamp1](https://cloud.githubusercontent.com/assets/8963459/21927101/f91feb3c-d984-11e6-8d89-2ba707ffb871.png)
![lamp2](https://cloud.githubusercontent.com/assets/8963459/21927102/f9201864-d984-11e6-8e43-a5be84eb2657.png)
![litterbin](https://cloud.githubusercontent.com/assets/8963459/21927099/f9091a42-d984-11e6-96b9-5235b33fbac8.png)
![water](https://cloud.githubusercontent.com/assets/8963459/21927100/f90929d8-d984-11e6-918c-e50c3a8eab4a.png)

**Comment by marijnvdwerf** [comment]
Odd. It appears to depend on the half-hill.

![image](https://cloud.githubusercontent.com/assets/737603/21927288/b0d0bf72-d985-11e6-8f65-67ab5bbb6cf4.png)
![image](https://cloud.githubusercontent.com/assets/737603/21927293/b933edce-d985-11e6-8fd4-fb38a63d0a72.png)
