### ISSUE TITLE
Test Data isn't working

### ISSUE THREAD

**Issue by ghost** [OpenRCT2/OpenRCT2#5070]
**OS: Windows 10 Home x64**
**Version: 0.0.6-28 **
**Commit/Build: d886353**

Hey. I heard reports from people in my private server saying that test data in their coaster is broken after 5 or more minutes of their coaster finishing testing. Can anyone please fix this bug? This is very important.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Build a coaster
2. Check test data to see if you are getting the same issue for 5 or more minutes.

[githubsixflags.zip](https://github.com/OpenRCT2/OpenRCT2/files/705661/githubsixflags.zip)

**Comment by birthdaybrian** [comment]
I also provided a save so you can check out the issue yourself.

**Comment by Nubbie** [comment]
@birthdaybrian 
I didn't totally understand the issue with the information you provided but I presume you mean that some coasters gets stuck in 'Not yet avalible' when calculating their score?

The coasters are scored one at the time and sometimes it can get stuck on hacked rides, in this case, 
"**Station bypass track**" gets it stuck, **open up the build menu off the coaster/remove it** will fix the score on all the other rides

This was discussed before with the solution off letting more coasters get calculated the same time
