### ISSUE TITLE
Giga Coaster design name display wrong

### ISSUE THREAD

**Issue by ccoors** [OpenRCT2/OpenRCT2#5077]
**OS:** Arch Linux
**Version:** 0.0.6
**Commit/Build:** 307745dd868ddad49dc4d03443870511b89e78c0

When building a Giga Coaster, the name of a prebuilt coaster is displayed as "Goliath.1" instead of as "Goliath". I'm pretty sure this was correct once.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open a park with the Giga Coaster available (like Wacky Worlds ⇒ North America - Rollercoaster Heaven)
2. Build a new Giga Coaster

**Screenshots / Video:**
![design_name](https://cloud.githubusercontent.com/assets/8963459/21958594/00629ccc-dab2-11e6-9f8d-81003058dfff.png)

**Comment by Gymnasiast** [comment]
RCT2 contains two track designs called 'Goliath' and the files are named `Goliath.TD6` and `Goliath.1.TD6`.

**Comment by rwjuk** [comment]
I'm assuming the other Goliath is for a different type of coaster (I know you can tell which type by looking at the guts of the TD6, but I forget where the table listing all the values is...)? Should we handle this sort of thing with a special case? Although as I don't think you can encode a ride name in the TD6 (it just uses the file name) that would get messy quickly I think.

**Comment by Gymnasiast** [comment]
Goliath.TD6 is the Hyper-Twister in Six Flags Magic Mountain.
Goliath.1.TD6 is the Giga Coaster in Six Flags Holland.

RCT2 ignored everything after the first dot. I think we should replicate that behaviour, at least for TD4 and TD6 files. When we switch to our own format, there should be a field for the ride name.

**Comment by rwjuk** [comment]
Ahhhh I'm silly - I should've realised that this wasn't an original bug. In that case, yes, replicate the behaviour.
