### ISSUE TITLE
Placing rides or stalls with clearance checks disabled removes walls

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#5079]
See title. Small scenery and large scenery will not disappear when you place a ride or stall through it, but walls do disappear is if clearance checks were not disabled.

Using 0.0.6.0 build 7edf1e8 on Windows 8.

**Comment by Broxzier** [comment]
The same thing happens when building footpaths using bridge mode.

**Comment by Gymnasiast** [comment]
@Liampie or @Broxzier : Is this now fixed?

**Comment by Broxzier** [comment]
@Gymnasiast Yes, but paths will not be connected. On Nedesign Liampie said what would be prefered.

**Comment by Broxzier** [comment]
This can be closed.
