### ISSUE TITLE
No Custom/Saved rides in Multiplayer

### ISSUE THREAD

**Issue by Meekimoto** [OpenRCT2/OpenRCT2#5097]
**OS:** [e.g. Windows ]
**Version:** [openrct2]
**Commit/Build:** []

<How do I build/save/move custom coasters in Open RCT2 multiplayer?  when i click on coaster, just wants me to build a new one.>

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by Gymnasiast** [comment]
Building track designs in multiplayer is not currently possible for technical reasons. This might be addressed when we switch to our own save format.

**Comment by IntelOrca** [comment]
> This might be addressed when we switch to our own save format.

Its not related, I think it will require refactoring of game commands and track paint.
