### ISSUE TITLE
OpenGL: ride track preview not rendered

### ISSUE THREAD

**Issue by RapsayBos** [OpenRCT2/OpenRCT2#5103]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.0.6]
**Commit/Build:** [e.g. 426e106]

When enabled OpenGL renderer, the text in the menu for choosing rides doesn't show up.

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Set drawing engine to: "OpenGL (experimental)
2. Open a scenario
3. Open the New Rollercoasters menu
4. Open a rollercoaster, and thou shall see no text

**Screenshots / Video:**

![crazy castle 2017-01-22 15-50-56](https://cloud.githubusercontent.com/assets/16818099/22183296/c4a21c94-e0ba-11e6-96bb-bcf1d9c1259b.png)

**Save game:**

[Crazy Castle_issue.zip](https://github.com/OpenRCT2/OpenRCT2/files/722008/Crazy.Castle_issue.zip)

**Comment by Nubbie** [comment]
Do you mean a preview image?
[This has been reported before](https://github.com/OpenRCT2/OpenRCT2/issues/4627) and OpenGL is very experimental, so I suggest you use another way of drawing the game, like software

**Comment by Nubbie** [comment]
I would suggest the temporary fix off:
"@IntelOrca we could detect OpenGL and display a string "Preview unavailable with OpenGL" in that window"
Use a string like "This feature isn't available yet in OpenGL"
