### ISSUE TITLE
Ride music no longer works

### ISSUE THREAD

**Issue by xp4xbox** [OpenRCT2/OpenRCT2#5109]
**OS:** Windows 7
**Version:** 0.0.6
**Commit/Build:** 3437b26

I have noticed recently whenever I set the ride music, nothing plays.

- [no] Reproducible in RCT2 (vanilla)?
- [both] Multiplayer?

**Steps to reproduce:**
1. Open a ride and set the music
2. You should hear nothing playing

**Comment by Broxzier** [comment]
It works just fine for me. Check if you have Ride music enabled and the slider is not completely on the left in the options menu under the sound tab.

**Comment by xp4xbox** [comment]
Nevermind, it was because the option was not enabled.
