### ISSUE TITLE
Cut-Away view displays incorrect height units.

### ISSUE THREAD

**Issue by Phasedetect** [OpenRCT2/OpenRCT2#5112]
**Version:** 0.0.6
**Commit/Build:** 990b9b8

When display is set to units for height instead of actual values, the cut-away view still displays the cut height in real values (ft, m) instead of units.

[Screenshot](http://i.imgur.com/kQMasxh.png)

**Comment by zaxcav** [comment]
It does't know about the setting for Units vs Real Values ... since I've never used this myself.
I'll add this in.
