### ISSUE TITLE
Some crashes do not generate .dmp or .sv6 files

### ISSUE THREAD

**Issue by Sweet-Tan** [OpenRCT2/OpenRCT2#5117]
**OS:** Windows 7, 10 x64
**Version:** 0.0.6
**Commit/Build:** 7eac99c

Some crashes, like the one described below, do not generate a dump or save file on crash. This applies to the game running normal or headless. In headless verbose, there are no warnings or errors. The console remains open, but chat logs stop responding, and no new autosaves are generated. Note: Custom objects are in use.

**Steps to reproduce:**
1. Open game save or launch in headless
2. In the rides list, select "(Echo) Ghaelphia WIP"
3. Test the ride

**Screenshots / Video:**
![20170125_crash](https://cloud.githubusercontent.com/assets/24423381/22315252/41a87dba-e32b-11e6-86bb-2b0a20ffad05.PNG)
![20170125_crash2png](https://cloud.githubusercontent.com/assets/24423381/22315302/8ef98e60-e32b-11e6-98c3-ad360418aa8b.PNG)

**Save game:**
[bugged_s1_autosave_2017-01-25_13-07-33.zip](https://github.com/OpenRCT2/OpenRCT2/files/731271/bugged_s1_autosave_2017-01-25_13-07-33.zip)

**Comment by janisozaur** [comment]
That's because it is not a crash.

**Comment by IntelOrca** [comment]
> That's because it is not a crash.

What is it it then?

I don't know how to make it more reliable. Certainly any crashes that happen when freeing memory (delayed crash from writing out of bounds) seem to not be catched.

**Comment by Gymnasiast** [comment]
> > That's because it is not a crash.

> What is it it then?

It looks like an infinite loop to me.

**Comment by IntelOrca** [comment]
If it's an infinite loop then yes it can't be caught unless we add some timeout on another thread.

**Comment by janisozaur** [comment]
> unless we add some timeout on another thread.

I've been meaning to do a watchdog for a while now. I can take it.

**Comment by janisozaur** [comment]
@Sweet-Tan a workaround: 
https://blogs.msdn.microsoft.com/debugger/2009/12/30/what-is-a-dump-and-how-do-i-create-one/

especially this one: 
![clip_image015_2](https://cloud.githubusercontent.com/assets/550290/22325663/64b60f96-e3af-11e6-96e1-2c429fe3e98e.jpg)

**Comment by IntelOrca** [comment]
@janisozaur you would need to temporarily disable it around blocking routines, like Windows API calls (message boxes and file dialogs) and long tasks maybe an issue too - e.g. repository scanning.

**Comment by janisozaur** [comment]
Good points. I'm sure I would eventually get to realise that, but it's better to know it beforehand.

> Of course I eventually want to make repository scanning asynchronous with a progress update.

Of course. [We all do.](https://github.com/OpenRCT2/OpenRCT2/issues/3190)
