### ISSUE TITLE
I made the window size so big that i cant reach the button to make it smaller what do i do?

### ISSUE THREAD

**Issue by TBear2002** [OpenRCT2/OpenRCT2#5126]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.0.6]
**Commit/Build:** [e.g. 426e106]

in the options I made the widow size so big that I can't reach the button to make it smaller I 've tried different ways to fix it but I couldn't figure it out.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**

**Screenshots / Video:**

![openrct](https://cloud.githubusercontent.com/assets/25394900/22389121/1199d56e-e4b2-11e6-982f-86ef743e9fa5.PNG)

**Save game:**

**Comment by YoloSweggLord** [comment]
You can change the window scale factor in the config.ini folder in your OpenRCT2 directory.

**Comment by IntelOrca** [comment]
You can also open the console by pressing backtick `\`` and then typing:
`set window_scale 1`

**Comment by TBear2002** [comment]
How do i open the directory to reach the config.ini folder :(

**Comment by TBear2002** [comment]
also i pressed the ` button but its not doing anything

**Comment by AaronVanGeffen** [comment]
Go to Documents\OpenRCT2 in your user directory. The config.ini file should be there.

**Comment by TBear2002** [comment]
Omg tanks guys i ts working now :)
