### ISSUE TITLE
Disabling Http/Twitch doesn't hide the twitch configuration tab

### ISSUE THREAD

**Issue by jansegre** [OpenRCT2/OpenRCT2#5128]
**OS:** Linux
**Version:** 0.0.6 (also happens in 0.0.5)
**Commit/Build:** 661ebbd9970e0ae784d32b3e4bdc3cf99709c109
**Steps to reproduce:**
1. Compile with`-DDISABLE_HTTP_TWITCH=ON` 
2. Open the "Options" dialog, the "Twitch" tab is still there

Maybe this was by design, but I thought I should point that out.

---
Side note: I just want to say that this project is of very high quality and I'm impressed with the momentum it has gathered, congrats.

**Comment by grimpunch** [comment]
Shouldn't this be closed if the fix has been merged?
