### ISSUE TITLE
converting to scenario issue

### ISSUE THREAD

**Issue by Meekimoto** [OpenRCT2/OpenRCT2#5134]
**OS:** [e.g. Windows 7]
**Version:** [e.g. 0.0.5]
**Commit/Build:** [e.g. 84977fa]

- [ ] Reproducible in RCT2 (vanilla)? Didnt attempt
- [x] Multiplayer? yes  server map

**Steps to reproduce:**
1.  attemped to convert my server save gave to scenario editor, (wanted to add park exits) ..checked ride reservations ..converted to scenario..
2. open scenario editor, and map is totally blank, just paths.. like a previous save i had.  When I try to open it, Had similar issues in rollercoaster tycoon 1, When I tried Windows compatibility settings.  Corkscrew follies didnt like windows 7.  Switch back to win7 compatibility, and stuff re appears.  Keeps reverting to an old save and all your rides n scenery isnt there.  
**Dump file**

Worked before .. 

**Screenshots / Video:**

**Save game:**

**Comment by Gymnasiast** [comment]
Opening a scenario with the scenario editor the regular way will always wipe the rides. That's why the 'Convert saved game to scenario' exists in the first place.

Also, you're hardly understandable again. Fix your grammar and be more clear please.
