### ISSUE TITLE
cant figure out how to reach the config.ini folder

### ISSUE THREAD

**Issue by TBear2002** [OpenRCT2/OpenRCT2#5135]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.0.6]
**Commit/Build:** [e.g. 426e106]

i know that the config.ini folder is located somewhere in the directory folder but i don't know how to get to the directory.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by AaronVanGeffen** [comment]
No need to open a new ticket just for this; you asked the same question in #5126
