### ISSUE TITLE
PPA builds broken

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#5139]
**OS:** Ubuntu Linux
**Version:** 0.0.6

PPA builds are broken due to Launchad builders being disconnected from the internet and failing to download title sequences.

CMake should be modified to use a local cache or skip that step.

Brief searching through the internet shows up these could be viable solutions, there may be others too.
* https://crascit.com/2015/04/03/handling-binary-assets-and-test-data-with-cmake/
* https://cmake.org/cmake/help/v3.2/module/ExternalProject.html

**Comment by IntelOrca** [comment]
Did you say that this could be resolved using a new repository that has submodules of all the other repos?

**Comment by janisozaur** [comment]
If CMake can be made to use the pre-downloaded files from cache, yes. Which the links I provided are all about.

**Comment by gyates100895** [comment]
any progress on this? I have no problem recompiling every now and then to stay up to date but a ppa is much more user-friendly. Just an inquiry so feel free to ignore this comment.

**Comment by Gymnasiast** [comment]
@gyates100895 Does the launcher not work for you?
Anyway, there is no progress on this I'm afraid. Janisozaur does not want to look into this and I know next to nothing about it.

**Comment by gyates100895** [comment]
The launcher does not work for me. It throws an error I can not think of at this moment but I will update this comment later with it. The good news is that @janisozaur clarified over on the forum what I was doing wrong compiling, so this has fallen to the wayside again for me

**Comment by janisozaur** [comment]
With https://github.com/OpenRCT2/OpenRCT2/pull/7195 launchpad builds are re-enabled. The builds fail for Xenial (16.04) due to https://github.com/OpenRCT2/OpenRCT2/issues/7075 but it looks more and more like libpng12 issue. Due to the way packages are versioned there, it might take a while (about two commit to `develop`) to get back in sync, as I had to do some testing.
