### ISSUE TITLE
Headless server should not be counted as a player

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#5141]
**Version:** 0.0.7-develop

- [x] Multiplayer?

As the headless server has no way of interacting with the game other than performing actions sent to it by connected clients, it should not be counted as a player.

**Comment by Nubbie** [comment]
Remember you can connect to servers in headless mode too

**Comment by timotk** [comment]
@Nubbie What is the point of connecting to a server in headless mode?

**Comment by janisozaur** [comment]
@timotk it's quite an important feature, actually. I use it all the time.

**Comment by timotk** [comment]
@janisozaur What do you use it for?

**Comment by janisozaur** [comment]
Multiplayer tests.

Headless clients should still count, as players though.

**Comment by Margen67** [comment]
@Xkeeper0 Any chance of PRing this? https://github.com/Xkeeper0/OpenRCT2/commit/ff6e2d0b16323d68901465b9be8c08c0f2ecc8cc
