### ISSUE TITLE
Feature: Allow tile inspector to raise multiple items

### ISSUE THREAD

**Issue by xp4xbox** [OpenRCT2/OpenRCT2#5149]
It would be nice to have a feature in tile inspector were you can selected multiple items than use this:
![green tree park 2017-01-31 12-00-04](https://cloud.githubusercontent.com/assets/24964930/22475430/ef211314-e7ac-11e6-9541-4bc99cbe4f87.png)

To increase the height of the objects.

**Comment by Liampie** [comment]
xp4xbox's idea does not cover it, see #5822 to read about a function with a much larger scope, as the 8cars trainer offers.

**Comment by IntelOrca** [comment]
I would argue the terrain feature is something good as a script plug-in.
The tile inspector could have a way of selecting arbitrary tiles to include in the selection.
