### ISSUE TITLE
Can Build outside of park boundaries at Factory Capers

### ISSUE THREAD

**Issue by EthanZeigler** [OpenRCT2/OpenRCT2#5152]
**OS:** [OS X 10.11.6]
**Version:** [0.0.6]
**Commit/Build:** [a19b477]

It is possible to build outside the park boundaries at Factory Capers, back at the "parking lot".

(OS X, cannot test vanilla)
- [x] Multiplayer?

**Steps to reproduce:**
1. Build outside park near parking lot

**Screenshots / Video:**
<img width="1280" alt="screen shot 2017-01-31 at 7 57 02 pm" src="https://cloud.githubusercontent.com/assets/9123320/22491268/59654752-e7f0-11e6-8ea7-ee77b2d155ce.png">

**Save game:**
[Factory Capers.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/743616/Factory.Capers.sv6.zip)

**Comment by EthanZeigler** [comment]
Updated to v0.0.7 build 2008f4a and problem still exists.

**Comment by Lastorder-DC** [comment]
![factory caspers 2017-02-01 12-11-33](https://cloud.githubusercontent.com/assets/18280396/22494060/90630d66-e877-11e6-9602-801067ce9917.png)
There's build rights, so that's expected behavior(see #4748 about can't see owned build rights)

**Comment by Gymnasiast** [comment]
This is how construction rights are supposed to work.
