### ISSUE TITLE
Raising objects with Shift doesn't use current zoom level

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#5159]
**OS:** Windows 10 x64
**Version:** 0.0.7 (but really since forever)
**Commit/Build:** 5d20803

When holding shift and moving up in the air, the zoom level is not taken into consideration. The object will only be halfway the height when zoomed out once.

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Start building anything that can be raised, and have the ghost piece show up
2. Zoom out one or more levels
3. Hold shift and move the mouse up to raise the object
4. Notice how it won't be at the mouse's height

**Comment by ZehMatt** [comment]
I recall fixing this here: https://github.com/OpenRCT2/OpenRCT2/pull/7868
