### ISSUE TITLE
Adding benches/bins/lights quickly and effortlessly 

### ISSUE THREAD

**Issue by tcek** [OpenRCT2/OpenRCT2#5161]
A nice feature would be in the cheats menu where you can click a bench sign and it would automatically add a load of benches on paths around your park. If you want bins, then click the bin sign, etc. It would be less time consuming and very handy. Thanks.

Also, your entertainers/staff ID in console seems to have stopped working :(

**Comment by duncanspumpkin** [comment]
See https://github.com/OpenRCT2/OpenRCT2/pull/4986 I think thats a better idea than yours.

**Comment by tcek** [comment]
Yeah, his/her idea is definitely better. Would be great to see it implemented. Btw, do you know what happened with the entertainer costumes? I can't seem to change them in console anymore which was a new feature added recently I believe.

**Comment by RealRexen** [comment]
@tcek I think its best if you create a new ticket for the staff issue
