### ISSUE TITLE
Parks containing packed objects fail to open

### ISSUE THREAD

**Issue by autofire372** [OpenRCT2/OpenRCT2#5169]
**OS:** Linux Mint 18.1 x64
**Version:** 0.0.7 x64
**Commit/Build:** 3b02b05

The UCES scenarios (other than Cleveland's Luna Park) and Panda World refuse to open in OpenRCT2, spouting "Unable to load file... Game Save Failed!" messages and booting me back to the title screen. These scenarios open just fine in vanilla RCT2 running in Wine.

**Steps to reproduce:**
1. Install UCES to wherever you have RCT2's data installed (requires Wine)
2. Run OpenRCT2, and attempt to open any UCES scenario that isn't Cleveland's Luna Park.

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by autofire372** [comment]
As it happens, the parks now fail to load on Windows as well, when they definitely worked before.

**Comment by IntelOrca** [comment]
I am fixing this. The issue applies to any parks containing packed objects.
