### ISSUE TITLE
Failure to load a new scenario in OpenRCT2 multiplayer

### ISSUE THREAD

**Issue by birthdaybrian** [OpenRCT2/OpenRCT2#5170]
**OS: Windows 7 Home Premium SP1 x64**
**Version: 0.0.7-2**
**Commit/Build: 3b02b05**

Hello developers, when I tried to load a new scenario when starting my private server for friends only, I get this message saying "Unable to load file... Game save failed!". This map does have custom objects and this issue didn't happen when I loaded the original RCT1 and RCT2 maps along with the expansions for RCT2.

UPDATE: I just found out that "Unable to load file... Game save failed!" error message only occurs in maps with custom objects.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Load the scenario that I provided you the download link to.
2. See if you can reproduce the same issue as me.

[OpenRCT2 Park.zip](https://github.com/OpenRCT2/OpenRCT2/files/751876/OpenRCT2.Park.zip)

**Comment by YoloSweggLord** [comment]
A lot of other people seem to be having this problem as well. A few guys on the New Element discord were talking about it.

**Comment by birthdaybrian** [comment]
I saw that IntelOrca has fixed this issue and there was a duplicate of this issue which I forgot to look closely before posting.
