### ISSUE TITLE
No notification when objects are missing

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#5177]
**OS:** Ubuntu 16.04
**Version:** 0.0.7
**Commit/Build:** b21378b

If you open the following park, it won't load due to missing objects (it prints that to stdout in verbose mode), but it won't display a message telling the user so.
https://github.com/OpenRCT2/OpenRCT2/files/741918/autosave_2017-01-31_23-17-53.zip

**Comment by IntelOrca** [comment]
You do not have to be in verbose mode for it to display what objects are missing to stdout.
The fix is to implement #1399.

**Comment by Gymnasiast** [comment]
Reopening this. It's not a duplicate. It should display a message. #1399 describes a way to improve the message.

**Comment by Gymnasiast** [comment]
@rwjuk It would be best if the in-game window reported all missing objects. You could also go the whole hog and implement #1399, if you want to.

**Comment by rwjuk** [comment]
If I can, it makes sense to do the job fully and have the ability to pop up a window saying "can't do that, these objects are missing" - then that could be used for multiplayer too (i.e. you can't join this server because you don't have XYZ.DAT).

**Comment by Gymnasiast** [comment]
Obviously, a window saying "you're missing the following objects" is a solution to the bug. But #1399 contains a whole lot more ideas besides that.

**Comment by rwjuk** [comment]
@Gymnasiast I misread #1399, you're right. Still, I'll try to implement the other ideas as well.

**Comment by rwjuk** [comment]
Just FYI, I asked on gitter if people had any saves (particularly scenarios or RCT1 saves) with custom objects, to post them here for testing purposes.

**Comment by Gymnasiast** [comment]
RCT1 saves do not have custom objects. They're imported with only RCT2 equivalents.
