### ISSUE TITLE
Lighting effects can't be disabled in software mode

### ISSUE THREAD

**Issue by ccoors** [OpenRCT2/OpenRCT2#5178]
**OS:** Arch Linux
**Version:** 0.0.7
**Commit/Build:** b21378b7f53e5ab0f5a21d9e82c3d52d1b1b147c

The lighting effects are still applied even when the checkbox is disabled.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Change the Drawing Engine to Software (hardware display)
2. Restart the game
3. Enable day/night cycle and lighting effects
4. Switch the Drawing Engine back to Software
5. Restart the game
6. You'll notice that the checkbox for lighting effects is disabled and checked and that the game looks a bit as if the gamma setting is wrong

**Comment by HaasJona** [comment]
A related issue happens if enabling hardware display requires a restart (on Linux for example). The enabled state of the day-night-cycle checkbox doesn't properly update when changing the rendering method.

**Comment by AaronVanGeffen** [comment]
This is still happening on 01e14e10bbf93df3dbfc588ea63f72d4184093a6.

**Comment by tupaschoal** [comment]
Still happening on v0.3.1

**Comment by raacker** [comment]
I will try to get into this issue. I really love this day/night option though :)

**Comment by AaronVanGeffen** [comment]
@raacker Someone beat you to it, sorry: #13206
