### ISSUE TITLE
Ladybird wrong image when going down steep rails.

### ISSUE THREAD

**Issue by tlworks** [OpenRCT2/OpenRCT2#5182]
**OS:** Windows 7
**Version:** 0.0.7 Dev
**Commit/Build:** No idea, shows '#5137' being latest in the changelog.

Ladybird

- [Probably not, Untested] Reproducible in RCT2 (vanilla)?
- [Yes] Multiplayer?

**Steps to reproduce:**
1. Build a Ladybird coaster.
2. Add steep section.

**Dump file**
N/A but can be added if required.

**Screenshots / Video:**
https://i.gyazo.com/01e868520876847e52682800e420ad5f.png

**Save game:**
N/A but can be added if required.

**Comment by Gymnasiast** [comment]
The ladybird trains don't have images for steep slopes, as RCT2 doesn't allow them on the Junior Roller Coaster. Normally you shouldn't be able to place them, but you probably enabled the 'Sort rides by track type' option, which overrides that.

**Comment by Gymnasiast** [comment]
Select-by-track type now no longer enables all track pieces. There is also a bug in the data file, which is also reported in #5902. See that issue for more details.
