### ISSUE TITLE
Clicking on a Magic Carpet doesn't open the ride window

### ISSUE THREAD

**Issue by ccoors** [OpenRCT2/OpenRCT2#5188]
**OS:** Arch Linux
**Version:** 0.0.7
**Commit/Build:** b21378b7f53e5ab0f5a21d9e82c3d52d1b1b147c

Clicking on a Magic Carpet doesn't open the ride window. It can only be opened by clicking on the rides entry/exit.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Build a Magic Carpet
2. Click on it

**Comment by janisozaur** [comment]
I can select it just fine. My `config.ini`: https://ptpb.pw/MVwg

**Comment by marijnvdwerf** [comment]
@janisozaur Did you click on the basetile, or on the structure?

**Comment by janisozaur** [comment]
I'm not sure what you mean. I clicked on "flying carpet", not on the entrance and the ride window opened.

**Comment by marijnvdwerf** [comment]
@janisozaur The pink part is different from the green part. But only when it's not running
![image](https://cloud.githubusercontent.com/assets/737603/22704562/6f360832-ed68-11e6-8685-9daff5925ed2.png)
