### ISSUE TITLE
I created a coaster - testing it causes the game to freeze!

### ISSUE THREAD

**Issue by lukashoegh** [OpenRCT2/OpenRCT2#5192]
**OS:** Win 10
**Version:** 0.0.7
**Commit/Build:** 7cb9d10

I have created a Möbius coaster for a contest park I'm working on. I'm trying to run it with 4 trains, i.e. one in each station loading while 2 are running the track, so I've set it to Block sectioned mode. In my savegame's current state the game freezes as soon as you put the ride into test mode.

- [ ] Reproducible in RCT2 (vanilla)? no idea
- [ ] Multiplayer? dont know

**Steps to reproduce:**
1. Rename this file to .sv6 and load it up in your game.
[bugged coaster.txt](https://github.com/OpenRCT2/OpenRCT2/files/759279/bugged.coaster.txt)
(I uploaded a new version here: [new bugged coaster.txt](https://github.com/OpenRCT2/OpenRCT2/files/762332/new.bugged.coaster.txt))
2. Click the only ride in the park and test it.
3. Your game will crash.

**Comment by Moranic** [comment]
The savegame doesn't load at all in OpenRCT2 for me. Vanilla RCT2 can't load it with the following error message:

> Unable to load file...
> Missing object data, ID:
> GREPATHM/0554F509D1D2F583

**Comment by lukashoegh** [comment]
Looks like the custom scenery included in the scenario doesn't work in vanilla. I think that is "what you would expect". I don't know why the save doesn't work in your openrct2, I'll download the uploaded version and try to open it when I get home, maybe it got corrupted in the upload process.

**Comment by IntelOrca** [comment]
@lukashoegh did you enable `export plugin objects` in settings before you saved the park?

**Comment by lukashoegh** [comment]
The park is a part of this competition:

https://www.reddit.com/r/rollercoastercontests/comments/5qj21v/contest_february_contest/

I downloaded it from there, and did not add any custom scenery or change any settings compared to the original savegame. All I did was build a rollercoaster :)

**Comment by IntelOrca** [comment]
@lukashoegh when you re-save the game though, unless you have that option enabled it will not pack the custom objects. It's not too much of a problem as you can download the objects elsewhere but it's easier for those who don't have them load the park.

**Comment by lukashoegh** [comment]
Didn't realize that, sorry. I will upload a proper version of my savegame tonight when I get home.

**Comment by lukashoegh** [comment]
I enabled export plugin objects, so here is a new verison of the file.
[new bugged coaster.txt](https://github.com/OpenRCT2/OpenRCT2/files/762332/new.bugged.coaster.txt)

**Comment by lukashoegh** [comment]
Has anyone downloaded the file and tried it out?

**Comment by jensj12** [comment]
Duplicate of #3846. If a train has to start on a diagonal chainlift, the game crashes.

**Comment by lukashoegh** [comment]
Ah, interesting. Good to know what the cause is, thanks.
