### ISSUE TITLE
Can't change Entertainers Costumes in Show Console

### ISSUE THREAD

**Issue by tcek** [OpenRCT2/OpenRCT2#5195]
**OS:** Windows 10
**Version:** 0.0.7.0 
**Commit/Build:** build 54504cc

A new feature was added recently: - Feature: [#4901] Allow entertainers' costume changes even in absence of required scenery. It worked for a while, but has since stopped working. Any updates to get this feature back please? And would there be a way to add it into Cheats at all? Thanks. 

**Steps to reproduce:**
1. Get the feature working again
2. Add it into cheat mode to make it easier

**Comment by tcek** [comment]
So any idea if this feature is coming back?

**Comment by janisozaur** [comment]
I don't know of anything that would break the functionality here. I'd assume it still works.

Can you bisect to find where it stopped working?

**Comment by tcek** [comment]
Well it worked before, but suddenly it stopped unless of course I'm all of a sudden putting it into console incorrectly.

This is what I put into console:
"staff list" (to bring up staff ID's)
"staff set costume" (to bring up the list of costumes)

Then I put in (example):
"staff id 000 costume id 9" (for Sheriff)

It used to work, but maybe I'm all of a sudden putting it in incorrectly? 

Thanks for the help.

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/interface/console.c#L528

**Comment by tcek** [comment]
Thanks, I'll give it a go. :)

**Comment by tcek** [comment]
Nope, it didn't work. Oh well, it's no biggie, thanks for the help.

**Comment by janisozaur** [comment]
Are you sure? I just tested it and it works just fine for me.

**Comment by tcek** [comment]
Interesting, any ideas what you type in then to make it work?

Thanks in advance.

**Comment by janisozaur** [comment]
Just what the help says: `staff set costume <staff id> <costume id>` with appropriate IDs.

**Comment by tcek** [comment]
Awesome, thanks. I feel like an idiot, hahaha.

**Comment by janisozaur** [comment]
Can this be closed now?

**Comment by tcek** [comment]
Yup, sure. :)
