### ISSUE TITLE
View gets stuck at the positive Y edge of the world

### ISSUE THREAD

**Issue by oli414** [OpenRCT2/OpenRCT2#5204]
**OS:** Windows 10
**Version:** 0.0.7
**Commit/Build:** e717c36

When the view is moved towards the positive Y edge of the world the view will get stuck and the view will continuously be put back at the edge.

(To clarify: by positive Y edge I mean the edge of the world that can be found when going in the positive Y direction in world space)

**Steps to reproduce:**
1. Rotate the view so that the positive Y edge of the world is facing towards you.
2. Move the view to the edge of the world in the direction of positive Y.
3. Try to move away from the edge again.

To get away you have to zoom out and zoom in somewhere away from the edge.

**Screenshots / Video:**
Gyazo Gif showing the issue:
https://gyazo.com/93026914a3a23cf957bdc1e6cc8201c1

**Comment by Androgeos** [comment]
I believe this is a problem that also existed in vanilla RCT2 (and possibly RCT1 as well). I always found it quite easy to get stuck at the bottom of the Grand Canyon map due to the terrain height there.

It looks like a similar issue was raised as #996 and partially fixed in #2282.

**Comment by oli414** [comment]
Oops, wasn't aware of that issue. Tried to search for this issue but that one didn't come up. Guess this issue can be removed then.
