### ISSUE TITLE
All disabled tab appears by force

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#5206]
**OS:** Windows 10
**Version:** 0.0.7
**Commit/Build:** 477de18

All disabled tab appears by force, as a gray block box.
It does not have to appear and should be disappeared.

And was it intended that disabled tab is drawed just gray block like screenshot? (see zoom in button in main menu)

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Screenshots / Video:**
![image](https://cloud.githubusercontent.com/assets/10726524/22851190/8cf21102-f05d-11e6-9f3c-2e50fd7784cf.png)

**Comment by AaronVanGeffen** [comment]
This appears to be a direct consequence of #5138. I'll PR a fix in a bit. Sorry for the inconvenience.
