### ISSUE TITLE
Income and Costs and Customer Information Tabs Seen in Roller Coaster Designer

### ISSUE THREAD

**Issue by Androgeos** [OpenRCT2/OpenRCT2#5207]
**OS:** Windows 10
**Version:** 0.0.7
**Commit/Build:** 5f3fc80

The Income and Costs and Customer Information tabs are visible, but not selected and have no icon, in the Roller Coaster Designer in the latest builds. This is probably a recent oversight somewhere in the code.

This may be related to #5206 given the original title of that issue; if so, resolving #5206 should resolve this issue as well.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

# Steps to reproduce
1. Open the Roller Coaster Designer
2. Build a ride

# Screenshots
![2017-02-11 12-59-04](https://cloud.githubusercontent.com/assets/18898491/22851348/49b3c0fa-f05a-11e6-9f41-55249688c3f8.png)
![2017-02-11 12-59-07](https://cloud.githubusercontent.com/assets/18898491/22851349/4d82a232-f05a-11e6-97ef-b1b38a411c11.png)

The following is a screenshot from an earlier build that doesn't have this issue. The screenshot is dated 29 January 2017, so if it helps anyone looking into this issue, check the builds released after this date.
![2017-01-29 23-09-47](https://cloud.githubusercontent.com/assets/18898491/22851676/bcac569e-f064-11e6-940b-e6fa453b149c.png)

**Comment by AaronVanGeffen** [comment]
This appears to be a direct consequence of #5138. I'll PR a fix in a bit. Sorry for the inconvenience.
