### ISSUE TITLE
Default system dialog not accessible from saving landscape window

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#5210]
**OS:** Windows 10 x64
**Version:** 0.0.7
**Commit/Build:** 3a13311

**Steps to reproduce:**
1. Open the scenario editor
2. Go to Floppy > Save landscape
3. Click "Use system dialog window"

Result: A system dialog window does not open.

**Comment by grimpunch** [comment]
Can you check if this happens still after my changes to Linux.c were merged?

**Comment by Gymnasiast** [comment]
He is using Windows 10, so it's not likely that's the issue.

**Comment by Broxzier** [comment]
@grimpunch I can confirm your PR has not fixed this issue.

**Comment by Gymnasiast** [comment]
Cannot reproduce this on macOS.

Is this still an issue?

**Comment by Broxzier** [comment]
Yes, the issue still exists following the exact same steps. I can only test it on Windows 10.
