### ISSUE TITLE
Sign built with ride counts as ride name even if text is changed

### ISSUE THREAD

**Issue by ccoors** [OpenRCT2/OpenRCT2#5211]
**OS:** Arch Linux
**Version:** 0.0.7
**Commit/Build:** 5feaab2f8e202284d1545b2e2daf4f88147391f4

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Build a Giga Coaster with the design "Goliath.1" (for the name bug see #5077) with the included scenery.
2. The scenery contains a sign that says "Goliath.1"
3. Change the text on the sign to something else, in this example let's say "ABC"
4. Rename the roller coaster to "ABC"
5. The game claims that the name is already in use

**Screenshots / Video:**
![goliath_sign](https://cloud.githubusercontent.com/assets/8963459/22864206/7572a2c6-f14d-11e6-8a4c-06920b350330.png)

**Comment by rwjuk** [comment]
This isn't limited to this track, or even to prebuilt tracks in general.

If you place a sign in a park with rides, the sign automatically 'links' to the nearest ride and displays that ride's name. If you change the sign's text, and then go to change the ride to the same thing, you'll get the 'chosen name in use' error.

Interestingly, this does **not** happen in reverse. You can change the ride name and then the sign just fine.

I'm almost certain this is to do with the wrong flag being passed to user_string_allocate. Assuming we don't want this (rather odd) behaviour, I should have a pull request ready before long (famous last words...!)
