### ISSUE TITLE
Desync error on autoplace staff enabled

### ISSUE THREAD

**Issue by jackkiej** [OpenRCT2/OpenRCT2#5213]
**OS:** Fedora 25
**Commit/Build:** 5e812d5

When the `auto-staff=` true, you get a desync error everytime you hire a staff member.

**Comment by janisozaur** [comment]
Ping @ZehM4tt

**Comment by runfalk** [comment]
Host OS (with GUI): Linux Mint 18.3 (64-bit)
Client OS: Windows 10 (64-bit)

Desync happens with regardless of `auto-staff` setting. I can also trigger desync in clients by lifting a guest.

**Comment by ZehMatt** [comment]
I believe this was fixed except for the pickup part which is another issue.
