### ISSUE TITLE
Entrances and peep entry points being messed up in multiplayer

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#5216]
Windows 8
v0.0.7 13df54c

Two issues I guess. Both concerning the new New Element multiplayer server.

1) If I enable sandbox mode to move or place the park entrance, it does not register which path type I've used. For example when I place an entrance using crazy paving as the path type, it will show up as a dark sand for others, as well as when I rejoin the server. Note: dark sand is the first path type in the paths menu, selected by default when you open the menu for the first time.

2) Placing peep entry points do not register at all. It may work for you, but not for others and rejoining will reveal that the peep entry points that you placed are no where to be found.

- [ ] Reproducible in RCT2 (vanilla)?
- [X] Multiplayer?

**Comment by Margen67** [comment]
Peep spawns were fixed by #7047.

**Comment by duncanspumpkin** [comment]
Paths were also fixed just the other day.
