### ISSUE TITLE
Scale RCT1 park value objectives

### ISSUE THREAD

**Issue by RoelerCoaster** [OpenRCT2/OpenRCT2#5218]
**OS:** Windows 10
**Version:** e.g. 0.0.7
**Commit/Build:** 6f7d869

When opening a SC4 file in OpenRCT2 of a park using a park value objective, the goal-value is copied as-is. But because the park value calculation in RCT2 is different from RCT1, the objectives become much easier than they were in RCT1. Perhaps it would be an idea to somehow scale / recompute the goal-value to keep (more or less) the same difficulty.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
(As an example we open Diamond Heights)
1.  Open sc3.sc4 from RCT1 in OpenRCT2
2.  The goal is to get a park value of 20,000
3.  The current park value is 95,978, whereas it was 13,350.80 in RCT1.

**Comment by Christian-Seematter** [comment]
This solution does not really serve the inconsistency issues. Wouldn't it be better to have a compatibility mode for .sv4 files that calculates it the same way as RCT1? 

I tried loading my save games to unlock the scenarios from RCT1 in openRCT2 that I had just replayed in the last couple of days, but my savegames that passed the requirements in terms of park value do not pass in openRCT2.

![2017-02-23 14_36_10-openrct2](https://cloud.githubusercontent.com/assets/1957259/23261180/750d32ca-f9d5-11e6-8438-d7f4c810d7be.png)
