### ISSUE TITLE
Lighting effects not working as expected

### ISSUE THREAD

**Issue by andoruB** [OpenRCT2/OpenRCT2#5229]
**OS:** Debian Sid x86_64
**Version:** 0.0.7
**Commit/Build:** d40bbd7f5

Sorry if this is a known issue, if so, feel free to close/delete this issue. The lighting effects don't seem to be showing up properly. First of all, the light doesn't seem to show up in certain perspectives, but if you rotate the camera's angle, the lights are visible (see screenshot 1 and 2). Also, another peculiarity is that the lit areas "show through" the windows when overlapping them (see screenshot 3).
I'm not sure if this peculiarity is due to the IGP (Intel i5) I have, the driver for the IGP, or if this is somewhat expected, as the feature is experimental,

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Turn on the lighting effects in the settings
2. Change the perspective (rotation) of the game
3. Put windows over the lit areas in the rotations that the light does show up

**Screenshots / Video:**
No.1 - ![screenshot_2017-02-16_15-48-38](https://cloud.githubusercontent.com/assets/4868784/23032454/b3c4e3de-f474-11e6-9b90-6384d3a877fc.png)
No.2 - ![screenshot_2017-02-16_15-52-44](https://cloud.githubusercontent.com/assets/4868784/23032453/b3c4acac-f474-11e6-9389-7c77a857c018.png)
No.3 - ![screenshot_2017-02-16_15-52-44](https://cloud.githubusercontent.com/assets/4868784/23032532/ea31bbcc-f474-11e6-8834-ff42eb6e51a6.png)

**Comment by duncanspumpkin** [comment]
They have always been quite broken. Its a known issue. The original idea was we would fix it in the opengl code but that has taken a back seat until we finish refactoring.

**Comment by andoruB** [comment]
Alright, thanks for letting me know!
