### ISSUE TITLE
[Request] Add timestamp to chat messages

### ISSUE THREAD

**Issue by Margen67** [OpenRCT2/OpenRCT2#5231]
**OS:** 
**Version:** 
**Commit/Build:** 

Currently chat messages are not timestamped.
This would be useful to tell when messages were made, how long ago, etc.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Open chat

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by duncanspumpkin** [comment]
At least try to write a description of why you think it would be useful.

**Comment by IntelOrca** [comment]
I assume you mean in game? Chat messages are already timestamped in the logs.

**Comment by Margen67** [comment]
In game, yes.

**Comment by grimpunch** [comment]
I'll take a look at this over this weekend

**Comment by janisozaur** [comment]
Fixes in #5243
