### ISSUE TITLE
Park gives assertion fail error upon opening

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#5239]
**OS:** windows 8
**Version:** 0.0.7
**Commit/Build:**  f73aebe

See title and screen below.

![errorrrrrrgsf](https://cloud.githubusercontent.com/assets/19242088/23106707/a8c5f7fa-f6f1-11e6-8b3b-548008d1bc32.png)

Note that the park did open, in the background. Can't do anything though.

It's this park:
http://www.nedesigns.com/park/3517/scientifica/

**Comment by IntelOrca** [comment]
The assertion doesn't trigger for me.

**Comment by rwjuk** [comment]
Me neither. (linux x86_64)

**Comment by Nubbie** [comment]
Can't get it to crash on ff51d4a (0.1.1)

**Comment by Nubbie** [comment]
@Liampie 
Can't get it to crash on commit 03299b9
Still having this issue?
