### ISSUE TITLE
Objection Selection Assertion Failed Error in Micro Park

### ISSUE THREAD

**Issue by harrysbird** [OpenRCT2/OpenRCT2#5242]
**OS:** Windows 10
**Version:** 0.0.7
**Commit/Build:** f73aebe

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open Micro Park in Scenario Selector
2. Open Object Selection in Debug tools tabs and Assertion error will show up

**Screenshots / Video:**

![bug report](https://cloud.githubusercontent.com/assets/3393747/23106958/14c93554-f6aa-11e6-885d-a0cf8e056d41.png)

**Save game:**

[SC99.zip](https://github.com/OpenRCT2/OpenRCT2/files/788769/SC99.zip)

**Comment by wolfreak99** [comment]
I can't seem to reproduce the error, although I have a recreation of the Micro Park.. Would you by chance have the scenario file that causes this? You can find the filename in the scenario selector at the bottom if you have debug tools enabled.

**Comment by harrysbird** [comment]
Added Save game files

**Comment by rwjuk** [comment]
Can you obtain a fresh copy of that scenario from the RCT1 source files and re-test, as the copy I have doesn't produce the error. It may be down to file corruption of some sort.

**Comment by wolfreak99** [comment]
So upon tinkering around I discovered this error in my (obtained past the post i made in here) copy of the original rct1 micropark. I noticed that it did it on the RCT1 copy of micro park, but not the RCT2 recreation of micro park. So I did some testing..

https://pastebin.com/CFHPqF4L

From my end, it seems that any rct1 scenario with a park entrance that is not a tarmac path throws a failing assert. 
This is where the assert is.
https://github.com/OpenRCT2/OpenRCT2/blob/f5923dbe99657ccbafc2f11b2293b6fc75c38188/src/openrct2/windows/editor_object_selection.c#L599-L601

A possible workaround could be switching
```
type = iter.element->properties.entrance.path_type;
assert(type < object_entry_group_counts[OBJECT_TYPE_PATHS])
gEditorSelectedObjects[OBJECT_TYPE_PATHS][type] |= (1 << 0);
```
to
```
type = iter.element->properties.entrance.path_type;
if (type < object_entry_group_counts[OBJECT_TYPE_PATHS]) {
    gEditorSelectedObjects[OBJECT_TYPE_PATHS][type] |= (1 << 0);
} else if (is_not_rct1_scenario_file) {
    assert(type<object_entry_group_counts[OBJECT_TYPE_PATHS]);
}
```

This would just be a temporary workaround for now though.

**Comment by Gymnasiast** [comment]
Hm, it could be that the entrance path type index is directly copied from the S4, rather than it using the correct index.

Good work on investigating. Can you name more scenarios that fail?

**Comment by wolfreak99** [comment]
Outside of the pastebin link?

**Comment by Gymnasiast** [comment]
Oh, I'm stupid. I didn't look at the pastebin link. :/

**Comment by Gymnasiast** [comment]
The file in the first post appears corrupted. I cannot reproduce this with my own (RCT1) version of Micro Park, so I'll have to assume it is fixed.
