### ISSUE TITLE
can't open game

### ISSUE THREAD

**Issue by BelgianGuyNE** [OpenRCT2/OpenRCT2#5247]
i get the error "failed to reallocate 2c4b0040 (unsigned char) to have 0 bytes...
any help?

**OS:** win10
**Version:** newest
**Commit/Build:** [e.g. 426e106]

can't open the game

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**
can't create this sorry

**Screenshots / Video:**
http://nl.tinypic.com/r/e0floj/9
**Save game:**
none

**Comment by duncanspumpkin** [comment]
Fill out the form correctly. OS, Version, Build. When does it fail? Immediately on load? Have you been able to play before? There is a good reason we ask for the information.

**Comment by BelgianGuyNE** [comment]
immediatly on load, I'm on win10 I have been able to play before, call it a spontanuous event and I've tried multiple develop versions to get it to run... all gave the same kind of error but never the same number

**Comment by janisozaur** [comment]
Fix the report and provide us with data or we will close it as there is nothing we can do.

**Comment by duncanspumpkin** [comment]
Provide the dump as well.

**Comment by duncanspumpkin** [comment]
I've just noticed there is no protection in the reallocate function for a size 0 reallocation this could cause a corrupted .dat to crash the game.

**Comment by janisozaur** [comment]
@duncanspumpkin there's no need for protection from 0-sized buffer. As per [docs](http://en.cppreference.com/w/c/memory/realloc):

> If new_size is zero, the behavior is implementation defined (null pointer may be returned (in which case the old memory block may or may not be freed), or some non-null pointer may be returned that may not be used to access storage). 

we do the proper thing.

**Comment by duncanspumpkin** [comment]
Well it crashes on windows if you have a size zero buffer.

**Comment by duncanspumpkin** [comment]
Oh right i see what you mean. Yeah its crashing in our guard because its not being caught.

**Comment by duncanspumpkin** [comment]
@BelgianGuyNE we will need more information to know where its crashing the dump file should be able to provide that information.

**Comment by BelgianGuyNE** [comment]
where can I find the dump?

**Comment by janisozaur** [comment]
@BelgianGuyNE if it doesn't create a dump, create one yourself via task manager and *update the relevant information*.

**Comment by BelgianGuyNE** [comment]
http://nl.tinypic.com/r/e0floj/9

screen of the error I'm getting

**Comment by duncanspumpkin** [comment]
The other option is to work backwards with different versions and find out when it starts working. We can then take a good guess as to what changed in that version.

**Comment by janisozaur** [comment]
@BelgianGuyNE you still have provided no information. We need the commit hash and the dump.

**Comment by duncanspumpkin** [comment]
I have another idea on how to work out where its crashing. I'm going to make a new build that will output the location of the error into the error message. Give me 10min.

**Comment by BelgianGuyNE** [comment]
thanks!

**Comment by duncanspumpkin** [comment]
[guard.zip](https://github.com/OpenRCT2/OpenRCT2/files/797673/guard.zip)
Okay try this build. You will have to dump the files in the directory manually I haven't included the rest of the distribution files. Error message should now have the file name as well.

**Comment by BelgianGuyNE** [comment]
I tried it and nothing happens, also my openrct folder is completely empty I tried to uninstall and reinstall the game both vanilla and open but gives same errors

**Comment by duncanspumpkin** [comment]
I'm not sure what you mean. Did you use the .exe and .dll and place them in the install directory of an existing install?

**Comment by BelgianGuyNE** [comment]
ok console is working now.... it appears the game isn't loading the objectdata anymore...

**Comment by BelgianGuyNE** [comment]
all 4145 objdata files are not loading

**Comment by BelgianGuyNE** [comment]
failed to reallocate 2753020 (unsigned char) to have 0 bytes rct12\SawyerChunkReader
this is what the startup console gives at the end after failing to load the objectdata

**Comment by BelgianGuyNE** [comment]
am I better off just doing a clean format for this? like get a hard reset and get everything installed fresh with no backhistory?

**Comment by duncanspumpkin** [comment]
No, hang tight i have some more ideas.

**Comment by BelgianGuyNE** [comment]
thanks man, I really appreciate it
is this a connection between the vanilla data and such that is broken?

**Comment by BelgianGuyNE** [comment]
I get a bunch of dmp files on the partition drive that openrct is installed on... can these help?

**Comment by duncanspumpkin** [comment]
If you hit ignore on the guard screen does it output what file it was processing?

**Comment by BelgianGuyNE** [comment]
unable to read 'C:\Program Files (x86)\infogrames\Rollercoaster Tycoon 2\Ojbectdata\SUPPLEG3.DAT'

then continues to gives errors on the the rest of the datfiles

**Comment by BelgianGuyNE** [comment]
it appears the game can't find any objdata

**Comment by Broxzier** [comment]
Can you check if that file exists? Also check your `%appdata%\..\Local\VirtualStore\Program Files (x86)\infogrames\Rollercoaster Tycoon 2\` folder.

**Comment by BelgianGuyNE** [comment]
it is in the objdata folder...

**Comment by duncanspumpkin** [comment]
Its likely that one of your object files are corrupted. You could try the simple fix of moving every file that has been created after 2003 out of the objdata folder and the same for the OpenRCT2 object folder and seeing if it still crashes.

**Comment by BelgianGuyNE** [comment]
I replaced them all with a backup and it still gives the same error... think I might need to hard reset on my harddrive and start again with the objdata backup, still thanks for the effort guys!

**Comment by Broxzier** [comment]
Did you also remove them from the folder in Virtual Store?

**Comment by BelgianGuyNE** [comment]
no, don't know where that is...

**Comment by Broxzier** [comment]
Copy this in Windows Explorer's address bar `%appdata%\..\Local\VirtualStore\Program Files (x86)\infogrames\Rollercoaster Tycoon 2\`, it should open the RCT2 folder in virtual store if you have one.

**Comment by duncanspumpkin** [comment]
[guard.zip](https://github.com/OpenRCT2/OpenRCT2/files/797849/guard.zip)
I've updated my guard file so that it should correctly handle the zero length file. If its still crashing try that.

**Comment by BelgianGuyNE** [comment]
fixed!

**Comment by duncanspumpkin** [comment]
What did you do that eventually fixed it. Was it reverting to a backup of your objdata? Or was it using the latest .exe i provided?

**Comment by BelgianGuyNE** [comment]
I found out why openrct didn't get to the objedata,
I recently installed avast antivirus and it prevented openrct to acces the vanilla data files...
once I shut that one down it worked again...

**Comment by duncanspumpkin** [comment]
How odd. Antivirus software tends to be worse than the viruses they protect against.

**Comment by BelgianGuyNE** [comment]
having the same issue again.... newest version is installed

**Comment by Gymnasiast** [comment]
Uninstall Avast and switch to Windows Defender. It keeps its hands off stuff it shouldn't touch, unlike almost every other AV program.

**Comment by IntelOrca** [comment]
If it's because OpenRCT2 is trying to access Program Files, you could instead move your RCT2 installation to somewhere not forbidden by your anti-virus software.

**Comment by BelgianGuyNE** [comment]
so I need to reinstall rct2?

**Comment by rwjuk** [comment]
No, you just need to copy and paste the files from the RCT2 directory under Program Files to somewhere else (e.g. your Documents folder) and then point OpenRCT2 to this new location.

**Comment by BelgianGuyNE** [comment]
I reinstalled onto my D drive and it works!!!! thanks guys
