### ISSUE TITLE
Chainlift crashes if its height is over 85.5m(=57 units)

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#5248]
**OS:** Windows 10
**Version:** 0.0.7
**Commit/Build:** 7005d5d

Chainlift crashes if its height is over 85.5m(=57 units).
It is needed to disable support limit.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Disable support limit (by cheat)
2. Build charlift up to 85.5m(=57 unit)
3. It crashes the end of station that is at 85.5m

**Dump file**

**Screenshots / Video:**

**Save game:**
[chairlift crash.zip](https://github.com/OpenRCT2/OpenRCT2/files/793304/chairlift.crash.zip)
See Chairlift 1

**Comment by Gymnasiast** [comment]
This is likely suffering from the same problem as #5249.

**Comment by Gymnasiast** [comment]
Appears to be fixed (tested in a0fb955102b89f2104effc7552415a9a61d36593).
