### ISSUE TITLE
Ride entrance/exit may be built in the same position over 85.5m(=57 units)

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#5249]
**OS:** Windows 10
**Version:** 0.0.7
**Commit/Build:** 7005d5d

It is issued with #5248 together in korean community,
ride entrance/exit could be built in the same position if their height is over 85.5m (=57 unit).

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Disable support limit
2. Build any ride with height as 85.5m (=57 unit)
3. Then the clearance check of their entrance/exit isn't checked correctly. They could be built in the same position

**Dump file**

**Screenshots / Video:**
![image](https://cloud.githubusercontent.com/assets/10726524/23211218/5b668e34-f944-11e6-91c7-f0cb7f3d8dfd.png)

**Save game:**

**Comment by Gymnasiast** [comment]
IIRC, +57 units is internally represented as 128 or 130*. Now, if that number is represented as a signed 8-bit integer, the maximum value is 128. It will overflow if the game tries to increase it.

\* You get the number by adding 6 or 7 and multiplying it by 2.
