### ISSUE TITLE
Disconnected from server just before it loads?

### ISSUE THREAD

**Issue by mollyriann** [OpenRCT2/OpenRCT2#5251]
OS: Windows (x86-64)
Version:0.0.7
Commit/Build:7005d5d

Hi there. When I attempt to connect to a server, I'm often disconnected just before it loads - with the simple message of "disconnected".

- [x ] Multiplayer?

**Comment by mollyriann** [comment]
Oh, also - it's only with certain servers. Some work totally fine. Not sure if it's a bug with the new update.

**Comment by Nubbie** [comment]
Feels a bit like a dead track, does this still occur?

**Comment by janisozaur** [comment]
Yes, I experienced it occasionally, extremely annoying.

**Comment by ZehMatt** [comment]
I think I've fixed this by sending a keep-alive packet for when it took longer than expected to download the data.
