### ISSUE TITLE
'Conga Eel' is a misspelling of 'Conger Eel'

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#5252]
https://en.wikipedia.org/wiki/Conger

Another example of the lack of quality of Wacky Worlds.
This can be fixed by including another override, like we have done for the Condor Ride.

**Comment by Androgeos** [comment]
Since we're on the subject of data file bugs and wrong spellings, there's also [this stall](http://rct.wikia.com/wiki/Sujongkwa_Stall)...

**Comment by Gymnasiast** [comment]
That article is incorrect. Both 'Sujeonggwa' and 'Sujongkwa' are acceptable spellings, as Korean uses another writing system and there are mulitple ways of converting it in Latin script. (The same applies to Arabic, by the way).

Now, whether 'sujongkwa' is the _preferred_ spelling is another thing entirely.
