### ISSUE TITLE
RCT1 Park Value Inconsistency

### ISSUE THREAD

**Issue by Christian-Seematter** [OpenRCT2/OpenRCT2#5253]
**OS:** Windows 10
**Version:** 0.0.7
**Commit/Build:** 7005d5d

This solution in #5218 does not resolve the inconsistency issues. It be better to have a compatibility mode for .sv4 files that calculates it the same way as RCT1.

I tried loading my save games to unlock the scenarios from RCT1 in openRCT2 that I had just replayed in the last couple of days, but my savegames that passed the requirements in terms of park value do not pass in openRCT2.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Screenshots / Video:**
![2017-02-23 14_36_10-openrct2](https://cloud.githubusercontent.com/assets/1957259/23261180/750d32ca-f9d5-11e6-8438-d7f4c810d7be.png)

**Save game:**
If it's ok to post scenarios from RCT1 I'll gladly post the one in the screenshot here.

**Comment by Gymnasiast** [comment]
> It be better to have a compatibility mode for .sv4 files that calculates it the same way as RCT1.

Easier said than done.

>  If it's ok to post scenarios from RCT1 I'll gladly post the one in the screenshot here.

Um, yes, we'd need those. Especially if you have scenario that barely passes in RCT1.

**Comment by Christian-Seematter** [comment]
Is there somebody on the team who already knows about the differences on how they are calculated? If it does scale linearly, then a factor of 10 was just a bit to high. The ratio in #5218 was around 7.7 if I remember.

I'll attach the .sv4 tonight.

**Comment by duncanspumpkin** [comment]
@Christian-Seematter it would mean reimplementing RCT1 from almost scratch, it would be a massive undertaking.

**Comment by Christian-Seematter** [comment]
The other metrics already line up fine, don't they? Worst case scenario a tweak of the scaling factor we currently have set to 10 will make the old scenarios well playable again.

I'm not trying to push anything here. Just found this project and am excited about how far it's already gotten. You guys are doing a great job! Since there is a github label for "RCT1 Import" I concluded that that is one of the goals too.

**Comment by duncanspumpkin** [comment]
Yeah, by import we plan to support rct1 files but play them based on rct2 mechanics

**Comment by IntelOrca** [comment]
I think lowering the multiplier would be better.

**Comment by Gymnasiast** [comment]
I plan to lower the multiplier to 7.5. Based on the parks I have seen, it's a little bit lower than the "actual"* difference, but that at least allows parks that passed in RCT1 to also pass in OpenRCT2.

\* Put between quotes since the different mechanics mean that any value will be off for some parks, at least a small amount.
