### ISSUE TITLE
can't open game

### ISSUE THREAD

**Issue by BelgianGuyNE** [OpenRCT2/OpenRCT2#5255]
can't open game
**OS:** win 10
**Version:** newest
**Commit/Build:** [e.g. 426e106]

can't boot the game

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**
doesn't give dump file

**Screenshots / Video:**
http://nl.tinypic.com/r/e0floj/9
**Save game:**

**Comment by janisozaur** [comment]
Please do not post duplicates.
