### ISSUE TITLE
Deleting the sign after copy/pasting it will crash the game

### ISSUE THREAD

**Issue by xp4xbox** [OpenRCT2/OpenRCT2#5261]
OS: Windows 7
Version: 0.0.7
Build: f6f6d27

If you open up a park then build a sign and then copy and paste it onto another tile. Deleting either copied one or original one will cause the game to crash. It will still crash even if you dont use the tile inspector to delete the sign.

- [N/A ] Reproducible in RCT2 (vanilla)?
- [ both] Multiplayer?

**Steps to reproduce:**
1. Open up any park
2.  Build any sign on any path.
3. Open up tile inspector and click on the signs
4. Click Copy
5. Click Paste on any other tile
6. Delete either one of the signs, and the game will crash.

![untitled](https://cloud.githubusercontent.com/assets/24964930/23336818/f05afda2-fba8-11e6-9b3d-14f66533725f.png)

**Comment by Sweet-Tan** [comment]
.dmp and .sv6 regarding this issue
[ec8846b3-cbae-4fb1-9d58-3b4f9c776051.zip](https://github.com/OpenRCT2/OpenRCT2/files/801709/ec8846b3-cbae-4fb1-9d58-3b4f9c776051.zip)

**Comment by Gymnasiast** [comment]
@Broxzier Could you look into this?

**Comment by IntelOrca** [comment]
Its possible that this is caused by the banners sharing the same string ID. If a banner is copied, it needs to duplicate and use a new user string.

**Comment by duncanspumpkin** [comment]
Does it also duplicate the banner ID?

**Comment by Broxzier** [comment]
@duncanspumpkin The pasted element is an exact copy, no new string or banner ID will be assigned when placing one, nor will they be destroyed when [removing](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/world/tile_inspector.c#L146) them using the Tile Inspector.

**Comment by duncanspumpkin** [comment]
In some ways it's nice to keep the link and just modify the destruct to prevent the ID from being freed.

**Comment by Gymnasiast** [comment]
I think it would be better to just copy everything, that's what the user expects from copy-paste anyway.

**Comment by IntelOrca** [comment]
Yes there are too many side effects with sharing entities. If you select no entry on one banner, you don't want the copy to also be no entry. And the same for the text as well. We have already had previous RPIs where changing the string of one thing changes the string of something else that is unrelated.

**Comment by Broxzier** [comment]
It does not crash anymore, but the moment one gets deleted, all copies will disappear, and the moment you build a new one, they reappear with the style of the new banner. Shall we leave it as is, or make the delete function smarter (e.g. by checking if any map elements refer to the banner index)?

**Comment by IntelOrca** [comment]
It should copy the element and give it a new string ID.

**Comment by xp4xbox** [comment]
Extremely arbitrary, no longer crashes. Should I close this?

**Comment by Gymnasiast** [comment]
No. The behaviour is still not correct.
Also, bugs are rarely 'arbitrary'. Feature requests can be, but not bugs.
