### ISSUE TITLE
Entertainers and Queue TV's

### ISSUE THREAD

**Issue by coasterbill** [OpenRCT2/OpenRCT2#5265]
In vanilla, queue tvs and entertainers prevent peeps from leaving long lines but in Open this isn't the case at all. Neither of them seem to function at all and instead are just for looks. The Dr. J Object Editor even features a checkbox for "queue tv" since it's actually a functional object. These don't function at all in open.

**Comment by xp4xbox** [comment]
Please fill out the information using the proper format!

**Comment by duncanspumpkin** [comment]
They do function as i remember writing the code. Entertainers are broken in vanilla and can actually force peeps off a queue in certain situations.

**Comment by IntelOrca** [comment]
@coasterbill how have you proved that they don't work?

**Comment by Gymnasiast** [comment]
@duncanspumpkin It's possible you made a slight error when writing it.


@coasterbill Could you provide steps to reproduce this error, as well as the build hash (displayed in the title screen, looks like a12b34c)?

**Comment by coasterbill** [comment]
The build is listed as 1549467 on the lower left, is that the right number?

Starngely this isn't happening as often since upgrading to the new version the other day, it now only seems to apply to objects made with the Dr J Object Editor where you check the queue TV box but not the game default queue TV. It functions in Vanilla but not Open, but it won't impact a ton of people so I'll let you decide if you feel that it's an issue.

Reproducing it just requires building a ride with a wait time exceeding 10 minutes or so and putting these custom queue TV's on every tile of the queue. Even though the TV's are there, they'll still leave the line. That won't happen in Vanilla even if the line ends up being a few hours along.

You'll need to wait about 5-10 minutes and then you'll see guests start filing out of the lines in droves. If you open it in Vanilla, they'll pretty much never leave.

I've attached a .dat. If you use this in Vanilla it works flawlessly but in open it's completely ignored.

[CBQTV.zip](https://github.com/OpenRCT2/OpenRCT2/files/819006/CBQTV.zip)

**Comment by ensiform** [comment]
If it's a custom object, could it be that its simply not handled properly as a queue tv? Do the stock ones function correctly?

**Comment by coasterbill** [comment]
The stock ones didn't in the previous version but seem to work in the build mentioned above. The custom version works flawlessly in vanilla but is completely ignored in open. With vanilla, any custom path object where the "queue TV" checkbox is checked in Dr J's Object Editor functions as a queue TV. It's a nice feature since the stock queue TV's are ugly so you can make invisible ones, but at the same time it is a custom object so I'm not sure how far you want to go to correct it.

**Comment by duncanspumpkin** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/peep/peep.c#L1138-L1172

The code is all there and all queue TV's work the same.

**Comment by duncanspumpkin** [comment]
Okay seems like im talking bull. I didn't implement this part only made a small change. Anyway I've noticed a bug. https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/peep/peep.c#L1147 is wrong it should be `!footpath_element_path_scenery_is_ghost`.
