### ISSUE TITLE
Unable to open any saved parks

### ISSUE THREAD

**Issue by Faaas** [OpenRCT2/OpenRCT2#5267]
OS:Windows 7 (64)
Version: several

I am unable to open any saved games I have. It says: "Game save failed!"

This happens for all parks (not for multiplayer servers). Other users are unable to open my parks as well.

Happens with several versions (not in vanilla), like "0.0.7 build 4ea29bb"

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Comment by Faaas** [comment]
I opened my park in vanilla, saved it under a different name, and now it's working in open again.

**Comment by Gymnasiast** [comment]
Could you upload a park that fails to open?

**Comment by Faaas** [comment]
I tried but the extension wasn't correct.

**Comment by janisozaur** [comment]
rename it to `.txt`

**Comment by Faaas** [comment]
Doesn't work.

**Comment by Faaas** [comment]
But never mind. I found a way to make it work and I'm terrible with computers so it's okay. Just blame the magnetic field I somehow have around me.

**Comment by JohnEriksson00** [comment]
I also have an issue with "Game save failed".
Trying to open this save; 
[The Elements - Final 3.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/818523/The.Elements.-.Final.3.sv6.zip)
 from [this old Reddit post](https://www.reddit.com/r/rct/comments/3dgr9k/everyone_else_is_doing_it_so_why_not_i_i_call/).

I do have "Allowing loading object files with incorrect checksums" enabled, if that is important.

**Comment by janisozaur** [comment]
@JohnEriksson00 it says clearly in the log:
```
[tb-catbt] Object not found.
```
The park in question has been exported without required objects embedded.
