### ISSUE TITLE
Failed to create dump

### ISSUE THREAD

**Issue by TheRealIPGS** [OpenRCT2/OpenRCT2#5268]
**OS:** [Windows 10]
**Version:** [0.0.6 x64]
**Commit/Build:** [1935]

BTW, I'm using the launcher for this. When ever I try to play the game, it says it failed to create the dump. How do i fix this?

- [no] Reproducible in RCT2 (vanilla)?
- [no] Multiplayer?

**Comment by Sweet-Tan** [comment]
**OS:** Windows 7 x64, Windows 10 x64
**Version:** 0.0.7
**Commit/Build:** 7f48df2

When dump files are generated, they are saved to the root of the drive: C:\ D:\ E:\ etc. The .sv6 file is saved in the same directory as the OpenRCT executable. Some users do not have permission to save to this location.

**Screenshots / Video:**
![capture](https://cloud.githubusercontent.com/assets/24423381/23388740/9e2c0aee-fd29-11e6-9539-03b6275a1474.PNG)

**Comment by IntelOrca** [comment]
The dump files should be saved in the same location as the SV6.

**Comment by janisozaur** [comment]
We should probably migrate to crashpad at some point...

**Comment by Margen67** [comment]
#5342

**Comment by janisozaur** [comment]
Closing this in favour of #5342.
