### ISSUE TITLE
Keyboard shortcuts window isn't large enough (for some languages)

### ISSUE THREAD

**Issue by JoelTroch** [OpenRCT2/OpenRCT2#5271]
**OS:** Any
**Version:** 0.0.7
**Commit/Build:** 8167ff9678c6020983404f33d5627b87cb118fba

The "keyboard shortcuts" window is too small in terms of width size, this gives me problem when translating PR #5200 to French as even with a lot of abbreviations it starts to be painful to read the window's content due to overlapping. The screenshot below explains way better what I mean.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Change the game language to "French (France)"
2. Go to "Keyboard shortcuts" (Raccourcis clavier)
3. Scroll down until you see "Afficher/masquer fenêtre de débogage du dessin", if you bind a key there (or you already have one), it's gonna overlap thus making reading harder.

**Screenshots / Video:**
![Oopsie!!!](https://cloud.githubusercontent.com/assets/4483707/23544708/567e360a-fff8-11e6-9b6c-b5206a39e469.png)

**Comment by Gymnasiast** [comment]
We'll enlarge it a bit, we can spare the screen space in 2017. ;-)

**Comment by Margen67** [comment]
Can you also make it resizable?

**Comment by wolfreak99** [comment]
@gymnasiast I know you self assigned it, but could I do this? I really enjoy working with the window system.

**Comment by wolfreak99** [comment]
By me doing it I mean making it resizable.

**Comment by Gymnasiast** [comment]
Sure! I'm glad you want to pick it up.

**Comment by Gymnasiast** [comment]
@JoelTroch STR_2781 contains a MOVE_X instruction, followed by {195}. Try increasing that number. I'm currently working on making the window wider and resizable (building on wolfreak99's work).

**Comment by JoelTroch** [comment]
@Gymnasiast I tried the {MOVE_X} command with the following values: 64, 128 and 255. It doesn't help, sometimes it would make it look worse.

Here is an idea: me or @RobinBossart can **limit the damage** by changing the strings to use abbreviations and by doing a little sacrifice on the quality of the translation (in terms of grammar). Here are some examples:

`Construction de manège - Tourner à gauche` -> `Construct. manège - Tourner à gauche`
`Construction de manège - Utiliser la voie par défaut` -> `Construct. manège - Utiliser voie par défaut`
`Construction de manège` -> `Construct. manège - Basculer échelle`

I'll say it again that it **won't fix this issue entirely but limit the damage**.

If you are against the option above, then increasing the window's width and make it resizable is the only remaining option.

**Comment by Gymnasiast** [comment]
I'd prefer just giving the descriptions more room. 195 pixels makes sense for English and 640x480 screens, not so much for French or Dutch and the screens we use today. I'll look into it further. Don't change anything to the French translations just yet.

**Comment by Gymnasiast** [comment]
The window is now bigger and resizable. Languages can edit string 2781 to give the descriptions more space. I have already modified UK English, Dutch and French, but for some languages 195 pixels (the old value) will actually work better - Chinese and Korean spring to mind.
