### ISSUE TITLE
Door object animation is not playing 

### ISSUE THREAD

**Issue by Lastorder-DC** [OpenRCT2/OpenRCT2#5275]
**OS:** Windows 7
**Version:** 0.0.7
**Commit/Build:** a33752e

Door object animation is not playing(door opening sound is playing)

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Screenshots / Video:**
![door1](https://cloud.githubusercontent.com/assets/18280396/23578946/73349248-0125-11e7-94a8-97e662d42823.gif)
![door2](https://cloud.githubusercontent.com/assets/18280396/23578947/7338456e-0125-11e7-94b5-79a96e982d0b.gif)

**Comment by duncanspumpkin** [comment]
hmm probably due to my refactoring.
