### ISSUE TITLE
List of multiplayer desyncs/unimplemented features/etc

### ISSUE THREAD

**Issue by Margen67** [OpenRCT2/OpenRCT2#5280]
**OS:** N/A
**Version:** [0.0.7]
**Commit/Build:** [https://github.com/OpenRCT2/OpenRCT2/commit/6d2776da2bc05e83fb441c84aad80b44a5c800ab]

No saved track designs: #5097
Object selection: #2294 & #3245 (can still be opened with console)
Park parameters/scenario_options (from Cheats menu or console)
Set console command (money, etc)
Invention list (opened from console)
Force a breakdown debugging tool: #5199
Setting map size while sandbox mode is on
Path of park entrance and peep spawns (sandbox mode): #5216
Guests watch ghost rides/pieces: #5058

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
N/A

**Dump file**
N/A

**Screenshots / Video:**

**Save game:**
N/A

**Comment by duncanspumpkin** [comment]
This should have been put in the wiki it doesn't lend itself to an issue.

**Comment by Margen67** [comment]
@duncanspumpkin Where should I put it on the wiki?

**Comment by duncanspumpkin** [comment]
Create a multiplayer issues page the same as the open gl issues page assuming it doesn't exist already

**Comment by Margen67** [comment]
Should I create a new page for MP issues or add them to https://github.com/OpenRCT2/OpenRCT2/wiki/Multiplayer#de-synchronisation

**Comment by Margen67** [comment]
https://github.com/OpenRCT2/OpenRCT2/wiki/Multiplayer-issues 
https://github.com/OpenRCT2/OpenRCT2/wiki/Multiplayer#desynchronisation

Maybe a multiplayer tab can be added to https://github.com/OpenRCT2/OpenRCT2/wiki/Features-to-implement ?

**Comment by janisozaur** [comment]
many of the console commands do sync properly, contrary to what you say.

**Comment by Margen67** [comment]
The only variable that is synced is money. (as far as I know) 
All the other ones either desync the client or if done server-side require the player to rejoin.

**Comment by janisozaur** [comment]
no, (parts of) `rides` and `staff` should be synced. I think there are more that do. Basically all the commands that use our event pump `game_do_command` in https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/interface/console.c should all work. Read-only commands will obviously work as well.
