### ISSUE TITLE
Intro always plays even if play_intro = false

### ISSUE THREAD

**Issue by Margen67** [OpenRCT2/OpenRCT2#5285]
**OS:** Windows 10 Pro Insider Preview x64 (15048)
**Version:** 0.0.7 x64
**Commit/Build:** https://github.com/OpenRCT2/OpenRCT2/commit/2e37d6e427e045645968b102b0a7b332719c07d7

The intro always plays on startup no matter what.
Even if you go into config.ini and set play_intro = true to "false" and make it read only it doesn't do anything.
If config.ini isn't made read only it resets the option back to true.
Running as administrator doesn't do anything.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Start the game

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by duncanspumpkin** [comment]
I'm getting this as well and thought it might be too do with the config failing to read the new shortcut keys and this causes the config to fail to read the rest of the file. Can you try deleting config.ini and seeing if it still overwrites.

**Comment by Margen67** [comment]
@duncanspumpkin It doesn't happen if you delete the config.ini then start the game, and after you exit it saves play_intro = false like it's supposed to.

After starting the game with the same config.ini it starts playing the intro again.

**Comment by janisozaur** [comment]
Is it a regression from https://github.com/OpenRCT2/OpenRCT2/pull/5240? Can you check https://github.com/OpenRCT2/OpenRCT2/commit/867b4523d28df13f21f6273187dd56b699b30f2d?

**Comment by Margen67** [comment]
https://openrct2.org/downloads/develop/867b452 works fine.

**Comment by telk5093** [comment]
2e37d6e does not work for me even if I edit config.ini

**Comment by duncanspumpkin** [comment]
I know the cause. Give me one sec
