### ISSUE TITLE
Vandalism occurs much more often than in vanilla

### ISSUE THREAD

**Issue by andoruB** [OpenRCT2/OpenRCT2#5287]
**OS:** Debian Sid
**Version:** 0.0.7
**Commit/Build:** 8bd10df / 6d2776d (Git)

Vandalism occurs much more often than in vanilla, even with no visibly angry guests. Might be confirmation bias, or I was better at RCT in the past, but at least in my few plays in OpenRCT with different maps/scenarios, I noticed this annoyance.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Comment by duncanspumpkin** [comment]
Duplicate of #4539

**Comment by andoruB** [comment]
Sorry, did stumble on that thread upon searching for this bug, but I did not read in it's entirety.
