### ISSUE TITLE
Rides selected not appearing in game

### ISSUE THREAD

**Issue by ArcticX9** [OpenRCT2/OpenRCT2#5297]
OS: Windows 10 confirmed; unknown about others
Version: 0.0.7; possibly earlier
Commit/Build: Numerous builds have exhibited this issue; I'm not sure when it first appeared. I always use the latest development build, so the current build that the issue appears on is 812a37d. 

Issue Explanation
Lately it appears as though some rides selected during scenario or object selection do not appear in the build menu. In the attached file, the multi-dimension coaster is selected, but does not appear.

The issue can be remedied through the following:
"I have found a workaround for this; if you deselect the ride using object selection, exit out of object selection, go back into object selection and reselect it, it should show up. " - Quoted from my own post on NE about the same issue.

- [No] Reproducible in RCT2 (vanilla)?
- [No] Multiplayer?
[NE Workbench 2017 by Louis!.zip](https://github.com/OpenRCT2/OpenRCT2/files/834574/NE.Workbench.2017.by.Louis.zip)

**Comment by Margen67** [comment]
Are you sure the ride is in the pre-invented (top) tab of the invention list?

**Comment by ArcticX9** [comment]
Yup! Everything else is in order.

**Comment by Gymnasiast** [comment]
Could you provide steps to reliably reproduce this? Along the lines of "1) Load scenario x 2) check ride X in the object selection 3) verify it's not there".

**Comment by ArcticX9** [comment]
I don't know if it's possible to reliably reproduce; let me give it a shot here.

**Comment by ArcticX9** [comment]
If you want to see it happen, load the NE workbench 2017 file, check object selection (see if Multi-dimension is selected) then go back out of object selection to see if it is present.

**Comment by WhenPenguinsAttack** [comment]
I can confirm that this is happening with **both rides and objects** in the Group Park 5 file on the OpenRCT2 forums.

https://openrct2.org/forums/topic/2360-group-park-5/?page=19#comment-14118

[The OpenRCT2 Group Park 5.28.zip](https://github.com/OpenRCT2/OpenRCT2/files/880220/The.OpenRCT2.Group.Park.5.28.zip)

**Comment by Gymnasiast** [comment]
The OpenRCT2 Group Park has many objects on the ? tab. RCT2 and OpenRCT2 only support up to 128 objects per tab. This limitation will need to be lifted.

**Comment by Gymnasiast** [comment]
Neither the problem in @ArcticX9 's post, nor the one @WhenPenguinsAttack 's are still reproducible. Considering this solved.
