### ISSUE TITLE
Language won't change in certain places

### ISSUE THREAD

**Issue by jkapi** [OpenRCT2/OpenRCT2#5309]
**OS:** Windows 10
**Version:** 0.0.7
**Commit/Build:** dc848bb

When changing the language in the Roller Coaster Designer or Scenario Designer, the Ride/Vehicle part of the list won't change language.

- [ ] Reproducible in RCT2 (vanilla)? Won't start for me so can't confirm
- [ ] Multiplayer?

**Steps to reproduce:**
1. Change your language to another one, like Dutch.
2. Go to the Roller Coaster Designer
3. Go to options, and change the language to English for example.

**Screenshots / Video:**
![image](https://cloud.githubusercontent.com/assets/16419568/23969130/9c3f1570-09c5-11e7-90bd-8c938307bf56.png)

Also happens with Park Descriptions when changing the language when you're choosing a park.

**Comment by duncanspumpkin** [comment]
It's a known limitation. You need to rebuild your object cache to change the language fully

**Comment by IntelOrca** [comment]
The object cache will automatically regenerate if you change your language. You just need to go back to the title screen first or restart the game.
