### ISSUE TITLE
Custom News Notifications

### ISSUE THREAD

**Issue by ArcticX9** [OpenRCT2/OpenRCT2#5310]
A really common feature that is present in the 8cars trainer but absent in OpenRCT2 is the ability to add a custom ticker message. Many park builders use this to finish off a park with lore, information, or just a thanks for checking out the park.

This is a pretty minor addition, but it has been used **extensively** prior to Open, and I think including it would be another useful feature.

**Comment by ArcticX9** [comment]
For reference, this is the relevant feature in 8cars:

https://imgur.com/gallery/HUsSs

**Comment by xp4xbox** [comment]
[https://i.imgur.com/Ix4wzC8.png](url)

**Comment by Gymnasiast** [comment]
This was already planned, but it seems there was no issue created earlier. So we'll keep this one open.

**Comment by ensiform** [comment]
Is there a way to push custom text though? I thought most of the text and notifications rendering was shifted to localized strings.  Someone who has been with the project more can correct me if I'm wrong on that.  I just noticed it seemed more like that when digging into adding some strings.

**Comment by duncanspumpkin** [comment]
Yeah news is different. It would work fine. How do you think 8 cars did it. It's not too hard a feature to add. Probably suitable for a beginner

**Comment by Richard-L** [comment]
Happy to see this has been asked for, and I'd like to bump attention.

These messages are useful in different ways. Mostly to set the setting and provide a short caption to your work as people open your park. We've also used them to identify workbenches as part of contests held on NE, which they were creator for.

You pause the game, enter the custom message, and then save the park. This will give you the beep and message unrolling animation upon opening the park.

**Comment by IntelOrca** [comment]
I have implemented this already but only in plug-in form:
https://www.youtube.com/watch?v=jmjWzEhmDjk

I could possibly add it to the console for now.

**Comment by Richard-L** [comment]
The most fantastic bit about this is the 90% LL compatibility in this. Becoming very hard to spot differences to vanilla RCT1.

on topic: I believe via console would be perfectly fine. Please do consider.

**Comment by WackedSwe** [comment]
This can't be forgotten in the midst of everything. It brings a charm to a park if there are messages when opened by another player.  I too wish to see this working again =) !

**Comment by AaronVanGeffen** [comment]
A console command has already been added, about a month ago. Anything fancier should go into a plugin.

**Comment by IntelOrca** [comment]
This can be closed now. It is possible to make a user friendly window to post park messages of any kind using the plugin system. I am sure someone will make that soon.
