### ISSUE TITLE
Crashes after deselecting scenery then clicking scenery tab

### ISSUE THREAD

**Issue by tcek** [OpenRCT2/OpenRCT2#5311]
Windows 10
0.0.7
build 1876785

I deselect most scenery in Object Selection so I can make room for a specific custom scenery. When I click off object selection, then click the scenery tab to use my new scenery, the game crashes.

- [ ] Reproducible in RCT2 (vanilla)? Yes

**Steps to reproduce:**
1. When deselecting scenery, and selecting new scenery, clicking the scenery tab crashes the game.
2. Help solve this error/bug. 

It kept saying it failed to create a dump file. 

Save game here:

[Orange Hill Park.zip](https://github.com/OpenRCT2/OpenRCT2/files/848591/Orange.Hill.Park.zip)

**Comment by janisozaur** [comment]
I cannot reproduce this. Can you provide more details?

**Comment by ArcticX9** [comment]
Also happening on b5b602d with this specific save file; appears to only happen when closing the object selection window:

[Rampaging River.zip](https://github.com/OpenRCT2/OpenRCT2/files/871162/Rampaging.River.zip)

Possibly could be happening because of a certain ride or object?

**Comment by ArcticX9** [comment]
I've successfully narrowed down the issue I've been having here; it seems to crash when trying to close the object selection window with at least 61 rides/shops/stalls selected.

To reproduce:
1. Open the attached file
2. Select _any one ride_ such that the selected ride count hits 61 (or above)
3. Game should crash (It does for me consistently)

[RR_60glitch.zip](https://github.com/OpenRCT2/OpenRCT2/files/871213/RR_60glitch.zip)

**Comment by ArcticX9** [comment]
I've heard this happening to two other people now; but don't have their saves.

**Comment by Nubbie** [comment]
Could not re-produce on commit 34073e1

**Comment by Chaosmeister** [comment]
RR_60glitch.zip causes an infinte loop in 84eebb19

**Comment by Chaosmeister** [comment]
I'm unable to reproduce any crash after my fix.

**Comment by Gymnasiast** [comment]
Cannot reproduce this on 7b2ea2aae19879e83226e75897037d05bc4ab026 - neither with Orange Hill Park, nor with Rampaging River.
