### ISSUE TITLE
Unable to advertive: please contact te developers

### ISSUE THREAD

**Issue by glennmatth** [OpenRCT2/OpenRCT2#5312]
Ubuntu 16.04
0.0.6 stable
master-2005d68

Getting Error while hosting headless server.
Port is forwarded in ufw. Connect to direct ip works.

screenshot: http://glenn.dikkedocker.nl/dl/screen.png

- [X] Multiplayer?

**Steps to reproduce:**
1. Starting headless server.
2. error comes every 5 min

**Comment by Gymnasiast** [comment]
Could you try if the error is present in the current `develop` version?

**Comment by janisozaur** [comment]
do you have other proof your network is letting traffic through to the service?

**Comment by glennmatth** [comment]
The current develop version has the same error.
my start command : ./openrct2 host map.sv6 --port 11753 --headless --verbose

screen of ufw portforward: https://glenn.dikkedocker.nl/dl/ufw.png

**Comment by Margen67** [comment]
Try turning off any firewall(s) including your router's.

**Comment by glennmatth** [comment]
Its running on a VPS not at home. Will try firewall later.

What port does the advertise service use?

**Comment by Margen67** [comment]
11753. https://github.com/OpenRCT2/OpenRCT2/wiki/Multiplayer#starting-the-server

**Comment by Nubbie** [comment]
You can check open the server and try 'http://canyouseeme.org/' I presume to see if the port is correctly set up

**Comment by glennmatth** [comment]
Port is open i will leave in running for some time. connecting manually is possible and works. 
to test this enter glenn.dikkedocker.nl

**Comment by Nubbie** [comment]
@glennmatth 
Still experiencing problems?

**Comment by janisozaur** [comment]
Duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/4953
