### ISSUE TITLE
Right-click for anti-clockwise rotation

### ISSUE THREAD

**Issue by movabo** [OpenRCT2/OpenRCT2#5314]
As right click is not binded on this button this would be a nice little feature to make rotations easier.

**Comment by ensiform** [comment]
Shift+Enter is counter clockwise rotations to go along with enter afaik.

**Comment by movabo** [comment]
Yes it is, but imho it would be great to make it easier over the interface as well.

**Comment by rwjuk** [comment]
Is this a good idea from a 'principle of least surprise' standpoint? Right-clicking isn't really used in RCT except for editing/deleting things. As far as I know, right-clicking every other UI widget does nothing, and I'm not honestly sure we should start making it do something, particularly as there's already the drop-down for CCW rotation.

**Comment by Gymnasiast** [comment]
I'm not in favour of this. We already use Ctrl + click as an alternative in some places (like OpenTTD has done) and adding another way for something that isn't even useful is a bad idea IMO. Currently, you can already click and drag for rotating, do Shift + Return or even click the rotate button three times.

**Comment by wildgoosespeeder** [comment]
Oh, didn't realize this thread existed. Anyways, because people are split, how about an interface option rather than vetoing the idea altogether? Default is keeping it as it always had. Option 1 is right-clicking the button. Option 2 is two rotate buttons, as described in #5419. With this, more people are happy. I really don't like using keyboard shortcuts.

**Comment by Patrik356b** [comment]
@wildgoosespeeder
I agree

**Comment by Gymnasiast** [comment]
*Sigh* I'm going to start like a broken record.

It always seems to be people who never did some programming of OpenRCT2 who request features. And that's no coincidence: maintaining software is hard work, which non-programmers have no idea of. Everything you add adds complexity, but not on a linear scale. Rather, the amount of combinations is n! (that's n factorial, or n * (n-1) * (n-2) * ...). Sometimes, a feature is worth the added complexity, sometimes it's not. The problem with complexity is that it will cause more bugs and make things harder to solve. Take a look at the bug tracker and you will see we have way too many already.

In addition to that there is the problem that every user of OpenRCT2 will have different ideas. We cannot implement every wish or OpenRCT2 would become an unmaintainable, unplayable monstrosity. RCT1 and RCT2 were delightfully simple, and OpenRCT2 is already much more complex. I will keep hitting the brakes every time a feature is suggested that I feel is detrimental the experience overall. And yes, I have let a truckload of features through, even if I did not see the appeal.
