### ISSUE TITLE
Banners always spawn black

### ISSUE THREAD

**Issue by Margen67** [OpenRCT2/OpenRCT2#5316]
**OS:** Windows 10 x64
**Version:** 0.0.7
**Commit/Build:** https://github.com/OpenRCT2/OpenRCT2/commit/a59886e6b08f4c9140a5cde46da41826cd293653

Banners always spawn as black regardless of set color.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Place a banner

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by s0r00t** [comment]
Arch x64 here, I can confirm the bug (e85c627).

![Proof](https://i.imgur.com/GmrU8FJ.png)

**Comment by rwjuk** [comment]
I've submitted a pull request that fixes this.
