### ISSUE TITLE
Using the bulldozer tool on under-construction paths results in unlimited free money.

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#5318]
**OS:** [Windows 8.1]
**Version:** [?]
**Commit/Build:** [?]

Using the bulldozer tool on under-construction paths results in unlimited free money.

- [ No] Reproducible in RCT2 (vanilla)?
- [ No] Multiplayer?

**Steps to reproduce:**
1: Open up the path builder

2: Set it to the continuous mode (where it automatically suggests the next piece; the one you use to build elevated paths; where you don't have to click each square you want a path one by one)

3: Click anywhere you can build a path, so that the white (or transparent) about-to-be-built path piece appears

4: Open the bulldozer menu, and set it to destroy paths only

5: With the bulldozer tool, click on the not-built-yet path section

When you do that, you get the $10 for destroying the path ... even though it doesn't destroy the path, because the path isn't built yet. And if you hold it down, it just does it over and over again, in quick succession. Holding it down for just a few seconds will give you thousands.

**Comment by duncanspumpkin** [comment]
Three solutions. Either:

check for ghosts in L434 of footpath.c and return 0 for ghosts

Remove provisional items before calling clear function and replace them after completing function.

Do both as there are probably other ways of triggering this.

**Comment by Broxzier** [comment]
Two other solutions:
- Ignore ghosts
- Remove ghost without refunding money

**Comment by duncanspumpkin** [comment]
@Broxzier you just described my solutions again.

**Comment by Broxzier** [comment]
@duncanspumpkin I understood that would remove them, and restore them again afterwards. The function you refer to (`window_footpath_tooldown`) doesn't check for anything, so I don't understand what you mean by that. This issue would also be the case for other map elements, since the bulldozer tool does not check for ghosts.

In [this loop in map.c](https://github.com/OpenRCT2/OpenRCT2/blob/6ea78d6c01ef8b15c928e28e7304ecdcaeff8104/src/openrct2/world/map.c#L1256-L1327) a check can be added to skip ghosts, to fix it for the bulldozer tool (or any other tool that uses `map_clear_scenery`).

**Comment by duncanspumpkin** [comment]
Oh sorry i meant `world/footpath.c` not 'window/footpath.c' https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/world/footpath.c#L434

This only effects footpaths as you cant have any other tool and the bulldozer open at the same time. So I guess another solution would be to disable having the bulldozer and the footpath tool open at the same time.

**Comment by Broxzier** [comment]
Ah now I get what you mean. Returning a refund of $0 sounds like the best solution. Closing the footpath window can be annoying for the player.

**Comment by Margen67** [comment]
If you ignore ghosts with the "Clear Scenery/Landscape" tool then the only way to delete glitched zero-clearance paths in multiplayer would be to use the Tile Inspector.

**Comment by SWAGSLAYER** [comment]
The issue still appears in v0.2.3

**Comment by James103** [comment]
@SWAGSLAYER Do you mean "The issue still appears in v0.3.2"? 0.2.3 is an old version, and 0.3.2 is the latest version.

**Comment by Gymnasiast** [comment]
@James103 No, 0.3.3 is the latest version.

**Comment by SWAGSLAYER** [comment]
> @SWAGSLAYER Do you mean "The issue still appears in v0.3.2"? 0.2.3 is an old version, and 0.3.2 is the latest version.

![image](https://user-images.githubusercontent.com/8876250/113748751-8b2aac80-9711-11eb-86a0-c3b1e468ea94.png)
v0.2.3

**Comment by SWAGSLAYER** [comment]
Well I checked and on 0.3.3 it works, sorry for bringing this up.
