### ISSUE TITLE
Windows builds are not pushed to openrct2.org(again)

### ISSUE THREAD

**Issue by Lastorder-DC** [OpenRCT2/OpenRCT2#5320]
From [Build log](https://ci.appveyor.com/project/IntelOrca/openrct2-ject9/build/0.0.7.7556/job/97qgovvuyhvtnhut)
```
'curl.exe' is not recognized as an internal or external command, operable program or batch file.
```

Looks like `curl.exe` is missing from build environment.

**Comment by IntelOrca** [comment]
Issue explained here:
https://github.com/appveyor/ci/issues/1426

It should automatically be fixed in two days:
https://github.com/appveyor/ci/issues/1431
