### ISSUE TITLE
Ghost servers in public server list

### ISSUE THREAD

**Issue by Sweet-Tan** [OpenRCT2/OpenRCT2#5329]
**OS:** Windows 7
**Version:** 0.0.7
**Commit/Build:** 2ce4b51

Ghost servers are now present in the master server list. Presently at https://servers.openrct2.website/ you can see two instances of "Tycoon Paradise - Server 1" and "Tycoon Paradise - Server 2". The duplicate entries have different network versions, the older of which are no longer running. Shutting down the entire machine that hosts these servers still did not remove the old entries. Even more bizarre, the ghost entries have their Park Value, Cash, and Game Date fields updated regularly.

In-game, the server list will only show one entry, though sometimes it shows the old network version and users are unable to connect.

Note: We use scripts to update and restart our servers when a new network version is released. A full upgrade can take just a matter of seconds.

**Screenshots**
![capture](https://cloud.githubusercontent.com/assets/24423381/24371019/21414ab8-12ef-11e7-9f9d-4128ae58e98f.PNG)

**Comment by AaronVanGeffen** [comment]
Does this still happen?

**Comment by Gymnasiast** [comment]
Doesn't seem to happen as of 2020-09-01.
