### ISSUE TITLE
Signs not showing what was typed

### ISSUE THREAD

**Issue by logankitchen** [OpenRCT2/OpenRCT2#5334]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.0.7
**Commit/Build:** ea7f1f0

When typing a message into a sign, the sign does not show what was written. Sometimes it shows nothing, sometimes only one word or one letter, etc.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by Gymnasiast** [comment]
Can confirm.

Steps to reproduce:
1. Place a path banner.
2. Attempt to modify its text.
3. The banner will show blank text.

**Comment by duncanspumpkin** [comment]
Argh must have made a mistake when refactoring

**Comment by siomy11** [comment]
It shows the message you type as long as you reach the max characters allowed.
![rct2_banner](https://cloud.githubusercontent.com/assets/25238051/24665679/fb63f7b2-1912-11e7-9244-eacc24b6e1ce.jpg)
