### ISSUE TITLE
Scenery eyedropper hides the third colour picker

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#5338]
**OS:** Windows 10
**Version:** 0.0.7
**Commit/Build:** f0b8a51

Scenery eyedropper covers the third colour picker as you can see below.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Screenshots / Video:**
![image](https://cloud.githubusercontent.com/assets/10726524/24613349/0150fb7a-18c3-11e7-9088-8c33e508470d.png)

**Comment by Nubbie** [comment]
Is the claw the 'scenery eyedropper'?

**Comment by xp4xbox** [comment]
The GUI is also glitchy when there is only one row in the scenery menu:

![untit1led](https://cloud.githubusercontent.com/assets/24964930/24625421/fa6ad8f8-187c-11e7-8766-2face8717484.png)

**Comment by xp4xbox** [comment]
![image](https://cloud.githubusercontent.com/assets/24964930/25018355/102f8370-2055-11e7-9557-353bdd516788.png)

not quite fixed the problem
