### ISSUE TITLE
Change the "Scenery eyedropper" to a "eyedropper" icon

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#5339]
![0150fb7a-18c3-11e7-9088-8c33e508470d](https://cloud.githubusercontent.com/assets/17282384/24616063/59ffbbae-1890-11e7-827f-2072a0ade2f5.png)

The eyedropper tool is right now the claw used to pick up peeps for example, the 'standard' icon is usually a 'eyedropper' - [see comment on issue 2078 for more information](https://github.com/OpenRCT2/OpenRCT2/issues/2078#issuecomment-286061528)

**Comment by xp4xbox** [comment]
To keep all the icons in rct2 I would use the cross hair one instead. i think the claw is not accurate enough for small scenery objects:

**Comment by IntelOrca** [comment]
> "Would be super nice it it automatically rotated to the direction​ the object you selected was
Right now it just jumps to default"

Is that the case for all objects or just trees and fences?

**Comment by xp4xbox** [comment]
it would be the case for all objects expect non-rotatable ones like fences.

**Comment by IntelOrca** [comment]
Hmm, I do set rotation so I don't know why its not working:
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/windows/top_toolbar.c#L1027

**Comment by rwjuk** [comment]
@IntelOrca You didn't combine the result of map_element_get_direction() with get_current_rotation().

Something like this works for me:
`(get_current_rotation() + map_element_get_direction(mapElement)) & 3`

**Comment by IntelOrca** [comment]
@rwjuk could you make a PR for that?

**Comment by rwjuk** [comment]
@IntelOrca Will do. I was going to but wondered as it's such a small change whether you'd just want to make it yourself. Best to do it right though :+1:

**Comment by IntelOrca** [comment]
@rwjuk It will be awhile before I am at my computer again, so this will be quicker.

**Comment by rwjuk** [comment]
@IntelOrca Ahh, makes sense. Done! #5344

**Comment by YoloSweggLord** [comment]
>To keep all the icons in rct2 I would use the cross hair one instead. i think the claw is not accurate enough for small scenery objects.
>
I second this. While most vanilla/expansion scenery is large enough for the claw to be easily used, there are a lot of custom scenery objects that are just too small or thin to be easily selected with the claw.

**Comment by Nubbie** [comment]
Isnt it possible to use a dropper as icon - crosshair when selected?
(For easy recognission, the claw does a kinda good enough job, but eyedropper feels more widespread)

**Comment by Nubbie** [comment]
![eyedropper](https://user-images.githubusercontent.com/17282384/33144324-f332ab5e-cfbc-11e7-883a-68084134d4c6.png)
