### ISSUE TITLE
Six Flags Branding Suggestion

### ISSUE THREAD

**Issue by TurtleShroom** [OpenRCT2/OpenRCT2#5347]
**OS:** Windows VII
**Version:** Current
**Commit/Build:** Current

Good evening.

It is a honor to be a part of the "Open RCT2" Project. I have played your incarnation of RCT2 for a long time, and am loving every minute of it.

Early in this project, you removed the Six Flags branding, logo appearence, etc. from the game. I understand the point of doing this, but the branding was always really neat to me because of my love of Six Flags as a child.

Seeing the Park view for "Build Your Own Six Flags Park" without the Six Flags logo is just not the same to me.

Would it be possible to allow players the choice of enabling or disabling the branding? Giving customers as much choice as possible is always a good thing. I reccomend that you allow toggling of the easter eggs and other such removed trivialities for those who enjoy them.

Of course, the current version (it being removed) should be set as default.

Thank you.
-TURTLESHROOM

**Comment by Gymnasiast** [comment]
Most people despised the Six Flags branding.

But anyway, we don't want to carry advertising, much less free advertising. And even _if_ we wanted (which we don't) we don't even have permission to use the Six Flags logos.

So I'm afraid it's not coming back.

**Comment by IntelOrca** [comment]
When we have a new save format, we will allow custom metadata to be added to parks and rides containing information about their real life counterpart.

**Comment by Gymnasiast** [comment]
Indeed, yes, so a design could say it is from Six Flags Magic Mountain, but also from Alton Towers or the Efteling. There won't be logos, though.
