### ISSUE TITLE
SUGGESTION: Allowing Choice Locations of Open RCT2 Folders/"Use Vanilla locations"

### ISSUE THREAD

**Issue by TurtleShroom** [OpenRCT2/OpenRCT2#5348]
Good evening.

One of the few issues I have had with this game is that it creates a duplicate Open RCT2 folder in My Documents, where saved games, scenarios, and so on are stored. I absolutely loathe this feature, because it creates uneeded duplicity when I already have an "Infogrames Interactive" folder.

I try to manually merge everything that would normally be in the Vanilla locations back (the game loads perfectly), but it never really succeeds, and so my computer's hard drive is clogged up by the new folder.

Is there some way to ensure that my files are put in the Infrogrames section, and that the Open RCT2 folder is only used for explicitly Open RCT2 items? I am sick of having to merge them and would like to have them all in the folder I grew up having them in.

If this is not possible, could there be some way to allow players to have the choice of where to store each of their Open RCT2 folders, including a choice to use Vanilla folder locations, where applicable?

Naturally, the current settings would be the defaults, and my suggestions would be optional.

Thank you.
-TURTLESHROOM

**Comment by PFCKrutonium** [comment]
The reason that we do this, is that the way the game originally stored files has been completely unsupported since Vista. You are explicitly not allowed to write to program files without Administrator privileges, and the only exceptions are older applications with Compatibility stubs made by Microsoft - which still don't save there. They are silently re-directed to a folder that all users can access. While we could (and do, I believe with the right command line switches) allow selecting where to stick the OpenRCT2 folder, putting them in the original folder is generally out of the question.

**Comment by duncanspumpkin** [comment]
Yeah just use the command line switches if you want to write to the old folders

**Comment by PFCKrutonium** [comment]
(And run as Administrator)

**Comment by TurtleShroom** [comment]
I'm not asking for that to be changed, though I find it odd.

I'm suggesting that there be an option for those with Administrator privileges to use the Vanilla system.

I have no idea how or where the command line works. Is it Command Prompt or something else?

If someone could show me exactly what to type, that would help me a lot!

**Comment by Gymnasiast** [comment]
You could create symbolic links, to have the OpenRCT2 folders point to the original folders or the other way round.

Why do you want to keep your Infogrames Interactive folders, by the way? Do you want to keep running RCT2? You only need select files from RCT2 and you can place those anywhere on your hard disk, including in the OpenRCT2 if you want.

**Comment by TurtleShroom** [comment]
I want to keep it because of tradition and the reduction of duplicity. I run RCT2 as an Administrator already.

As for Symbolic Links, I have no idea how those work. What I do know is that I want all ORCT files and saved itens to physically be in the Infrogrames folder.

**Comment by IntelOrca** [comment]
1. In explorer, go to your OpenRCT2 directory, e.g. `C:\Users\{you}\Documents\OpenRCT2`
2. Back up your save folder if you have saves in it you want.
3. Then make sure you have no files or folders selected.
4. Click File -> Open command prompt -> Open command prompt as administrator.
5. Type `rmdir /S /Q save` and hit return.
6. Type `mklink /D save "C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\Saved Games"` and hit return.

**Comment by TurtleShroom** [comment]
Okay. Once I do that, how do I do the same for Tracks, Scenarios, Objects, and the rest of it?

**Comment by Gymnasiast** [comment]
```
OpenRCT2 folder	  | RCT2 folder
-------------------------------
save              | Saved Games
landscape         | Landscapes
scenario          | Scenarios
track             | Tracks
object            | ObjData
```

Repeat steps 5 and 6 that IntelOrca provided using the folder names above.
