### ISSUE TITLE
Booster is underpowered in OpenRCT2 (repost from Reddit)

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/OpenRCT2#5350]
I don't know if this should be identified as an issue here:
https://www.reddit.com/r/rct/comments/641uh7/15k_customers_per_hour_for_science/

LordMarcel:

> I have tried recreating it in openrct2, but the boosters tracks there don't accelerate it quick enough. They also look different (they look exactly like the brakes) so I assume the ones in classic are way stronger.

X7123M3-256:

> OpenRCT2 has LSM pieces on all the same rides RCTC does - he's not referring to the launched lift. However, the acceleration on the OpenRCT2 version is pathetically weak.

I don't own a copy of RCTC, but I can also feel that the booster track is somehow too weak and space-consuming (i.e. 20 booster pieces set as 67km/h can only boost a 4-car twister train to 52 km/h) to boost the roller coaster to the designated speed. Therefore, I decided to open this issue. Please close this if it is not appropriate to raise it in here.

**Comment by Gymnasiast** [comment]
Yes, this is the appropriate place to post issues like these. Thanks.

The acceleration value needs to be adjusted in order to make the boosters more useful.
Also, it needs to be separated from the launched lift hill acceleration value - currently those are shared, but since the Steel Twister has both the launched lift hill and boosters we cannot change one without affecting the others.

We already have sprites for the Giga and Steel Twister booster tracks, but they are not currently used. (It is planned, though).

**Comment by rwjuk** [comment]
From some brief experimenting, multiplying the acceleration value by 8 for booster track, i.e. changing line 7520 of ride/vehicle.c to

`vehicle->acceleration = RideProperties[ride->type].acceleration << 19; `
from 
`vehicle->acceleration = RideProperties[ride->type].acceleration << 16; `

leads to acceleration that is both useful and seems roughly consistent with the real-world performance of LIMs/LSMs.

This would solve the issue and leave launched lift hills unaffected with only a small change - would this be an acceptable solution or is this too hacky?

**Comment by Gymnasiast** [comment]
This would be too hacky, as it would also affect the Looping Roller Coaster and the Steel Corkscrew RC, which currently have 'correct' acceleration (i.e. the same as they had in RCT1). And it's not too difficult to just add an extra field.

**Comment by rwjuk** [comment]
Ahh, of course. I should avoid late-night experiments! Happy to add the extra field and submit a PR unless you plan to work on it yourself!

**Comment by Gymnasiast** [comment]
I have plenty to keep me occupied, so go ahead! :-)
Please also copy the current `acceleration` values to the new field and rename the current `acceleration` field to `powered_lift_acceleration`.

**Comment by daihakken** [comment]
Since #5354 is merged, I now close this issue.

**Comment by Lastorder-DC** [comment]
This was closed but added to TODO via automation.

@Gymnasiast

**Comment by Gymnasiast** [comment]
@Lastorder-DC That message is a bit confusing - I added it manually via the Projects view. Adding it to the view was intentional, but it should have gone in Done, not ToDo.

**Comment by Lastorder-DC** [comment]
![image](https://user-images.githubusercontent.com/18280396/102599387-c0aa8a80-4160-11eb-8fc1-0fdeac32fd7e.png)
Message says that this was added by automation. so I wrote that.

Sorry about my english, though

**Comment by Gymnasiast** [comment]
I meant to say that this message:

![](https://user-images.githubusercontent.com/18280396/102599387-c0aa8a80-4160-11eb-8fc1-0fdeac32fd7e.png)

was incorrect and confusing.

Your English is fine, I understood you completely.
