### ISSUE TITLE
"Assertion failed!" after guest with name 'Emma Garrell' exits/enters ride

### ISSUE THREAD

**Issue by Margen67** [OpenRCT2/OpenRCT2#5357]
**OS:** [Windows 10 Pro x64]
**Version:** [0.0.7]
**Commit/Build:** [https://github.com/OpenRCT2/OpenRCT2/commit/8198254b72d0afc74707d32a003eb519347ee814]

If a guest with the easter egg name "Emma Garrell" enters or exits a ride with trains on it the game keeps showing an "Assertion failed!" error.
This does not happen with flat rides like the Spiral Slide.

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Rename a guest to Emma Garrell.
2. Have them go on a ride with a track like Mini Golf.
3. Errors

**Dump file**
N/A

**Screenshots / Video:**
![1](https://cloud.githubusercontent.com/assets/3462541/24944565/aa3ca2ae-1f10-11e7-87b8-de80178ac93f.png)
![2](https://cloud.githubusercontent.com/assets/3462541/24944713/2b576edc-1f11-11e7-90d5-86bc4b7c08a6.png)

**Save game:**
[EGcrash.zip](https://github.com/OpenRCT2/OpenRCT2/files/915640/EGcrash.zip)

**Comment by rwjuk** [comment]
Do you get both of those dialog boxes? The one in the screenshot is different to the one on its own.

**Comment by Margen67** [comment]
@rwjuk I only get one of them at a time. It's random.

**Comment by siomy11** [comment]
Just reproduced this, I don't get any error message but it closes my game's window and doesn't seem like it saves any changes on the game. 
I renamed a guest to 'Emma Garrell' then made it go on the Goliath rollercoaster, as soon as the guest exist the ride it exits my game.
