### ISSUE TITLE
"Please select a valid RCT1 directory" error or booster sprites don't change when choosing RCT Deluxe (Steam) folder even after restarting

### ISSUE THREAD

**Issue by Margen67** [OpenRCT2/OpenRCT2#5359]
**OS:** Windows 10 x64 Pro
**Version:** 0.0.7
**Commit/Build:** https://github.com/OpenRCT2/OpenRCT2/commit/8198254b72d0afc74707d32a003eb519347ee814

If I choose my "RollerCoaster Tycoon Deluxe" folder (C:\Program Files (x86)\Steam\steamapps\common) as the path to RCT1 installation it gives me the error 'Please select a valid RCT1 directory.'
Choosing any folder within "RollerCoaster Tycoon Deluxe" except RCTdeluxe_install also results in an error.
But if I choose the RCTdeluxe_install folder boosters still use the brake sprites even after restarting.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Choose the RollerCoaster Tycoon Deluxe or RCTdeluxe_install as the RCT1 installation directory.
2. Notice the error or lack of sprite changes.

**Dump file**
N/A

**Screenshots / Video:**

**Save game:**

**Comment by Gymnasiast** [comment]
Please give a listing of your RollerCoaster Tycoon Deluxe\Data folder. There is inconsistent naming across RCT1 versions.

**Comment by Margen67** [comment]
@Gymnasiast
![listing](https://cloud.githubusercontent.com/assets/3462541/24969973/86481494-1f67-11e7-986b-8f9bf557f60f.png)

**Comment by Gymnasiast** [comment]
Ah, exactly as I suspected.

csg1.1 and csg1.dat are the same file.
In the CD version, it's called csg1.1 on the CD and csg1.dat on the disk.
In the GOG version, it's always called csg1.1.
In the Steam version, it's always called csg1.dat.

**Comment by Gymnasiast** [comment]
Please try again with the current develop.

**Comment by Margen67** [comment]
@Gymnasiast Now it lets me choose the right directory but the booster sprites stay the same.

**Comment by Gymnasiast** [comment]
Have you restarted between choosing a directory and trying your park?

**Comment by Margen67** [comment]
Yes.

**Comment by Gymnasiast** [comment]
You're missing csg1i.dat. Try to find it and copy it to the Data directory (where csg1.dat also resides). Also, please tell where you found that file.

**Comment by Margen67** [comment]
It's in RCTdeluxe_install\Data within the RollerCoaster Tycoon Deluxe folder.
C:\Program Files (x86)\Steam\steamapps\common\RollerCoaster Tycoon Deluxe\RCTdeluxe_install\Data

**Comment by Gymnasiast** [comment]
Does it work if you copy the file?
Also, can you give me a listing of `C:\Program Files (x86)\Steam\steamapps\common\RollerCoaster Tycoon Deluxe\RCTdeluxe_install\Data`?

**Comment by Margen67** [comment]
Yes.
![listing2](https://cloud.githubusercontent.com/assets/3462541/24977268/504f76b0-1f81-11e7-8a4e-8f1cae399256.png)

**Comment by Gymnasiast** [comment]
Thanks.

I now know what the situation is:
- The folder that would have worked without copying files was `RCTdeluxe_install`
- There was a problem in the code that prevented the sprites from loading. This was solved tonight.

Since we now found the correct directory and the sprite errors are solved, I'm going to close this issue.

**Comment by Margen67** [comment]
If I choose RCTdeluxe_install it does work.
But it doesn't seem very intuitive to have to choose that when it just says "RCT1 installation."
It should detect that folder automatically. If you choose the wrong directory (RollerCoaster Tycoon Deluxe) it silently fails. A new user would probably think the feature isn't working properly.
