### ISSUE TITLE
Root command prints nothing and runs game instead

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#5362]
**OS:** Windows 10
**Version:** 0.0.7
**Commit/Build:** ff350f3

There is no outputs when I run openrct2.exe via root command line in Windows Command Prompt, such as ``openrct2 help``
Do you think it is happened only to me, or it is a bug?

And I'm using x64.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Run windows command prompt
2. Move to OpenRCT2 installation directory
3. type ``openrct2 help`` or ``openrct2 version``, etc.
4. No outputs in prompt and the game is run instead.

**Dump file**

**Screenshots / Video:**
 * GIF Animated image:
![2017-04-14 044304 861](https://cloud.githubusercontent.com/assets/10726524/25021397/f864c8e0-20cc-11e7-9179-1945af598f33.gif)
(Sorry that it is not English)

**Comment by janisozaur** [comment]
It's `--help` and `--version`.

**Comment by Gymnasiast** [comment]
Should it not print something like `Unrecognised file or command`?
