### ISSUE TITLE
Console commands do not show output

### ISSUE THREAD

**Issue by RoelerCoaster** [OpenRCT2/OpenRCT2#5363]
**OS:** Windows 10
**Version:** 0.0.7
**Commit/Build:** ff350f3

Openrct2 does not seem to write anything to console output, especially for commands where output is expected.

**Steps to reproduce:**
1.  Open a command prompt
2.  Run a command that is expected to show output, like
`openrct2 --version`
or 
`openrct2 --help`
3. Nothing is shown in the console. 
On the other hand, running `openrct2 --version > test.txt` **does** give the expected output in the text file.

**Comment by janisozaur** [comment]
It's `openrct2`, with `2` at the end…

**Comment by RoelerCoaster** [comment]
I'm sorry, typo on my side, even with openrct2 it shows no output

**Comment by rwjuk** [comment]
Can you take a screenshot of the exact command you're running, and its output?

**Comment by RoelerCoaster** [comment]
![openrct2cmd](https://cloud.githubusercontent.com/assets/5968886/25024193/3ce02e22-209d-11e7-9fae-d9f590859aa3.png)

For the sake of it, I also tried Powershell, and strange enough I do get an output there if I put parentheses around the command:
![openrct2posh](https://cloud.githubusercontent.com/assets/5968886/25024229/5b1eb98a-209d-11e7-8b2e-f07ce40ffee0.png)

**Comment by IntelOrca** [comment]
For some reason openrct2.com is not a console application. I will have to look into this.

**Comment by IntelOrca** [comment]
@RoelerCoaster should be fixed now, thanks for pointing this out.
