### ISSUE TITLE
OpenRCT2 crashes when trying to add a greeting into a server

### ISSUE THREAD

**Issue by ALEEF02** [OpenRCT2/OpenRCT2#5365]
**OS:** Windows 10
**Version:** 0.0.7
**Commit/Build:** 2099

When trying to add a greeting to a server in the menu, the game crashes

- [ ] Reproducible in RCT2 (vanilla)?
- [✓] Multiplayer?

**Steps to reproduce:**
1. Open OpenRCT2
2. Click the multiplayer icon
3. Click "Start server"
4. Click the box next to "Server Greeting"
5. Crash

**Dump file**
Unable to create

**Screenshots / Video:**
![1](https://cloud.githubusercontent.com/assets/12904259/25028404/0dc673d2-2069-11e7-8acf-9468a5d38a2b.PNG)
![2](https://cloud.githubusercontent.com/assets/12904259/25028406/0dc7ac84-2069-11e7-92ce-13e3f342e962.PNG)
![3](https://cloud.githubusercontent.com/assets/12904259/25028405/0dc6ad02-2069-11e7-8d3c-6705b9ea28b7.PNG)
![4](https://cloud.githubusercontent.com/assets/12904259/25028407/0dc948e6-2069-11e7-80cc-10cc83b5652c.PNG)

**Comment by rwjuk** [comment]
I couldn't replicate this on the latest build (f07fb2d), but I _could_ on an older one. Could you download the latest build and retest?

**Comment by iam-Mai** [comment]
looks like the path can't find hotkeys.cfg so it throw null and the game crash
Btw, what is the hotkeys.cfg that GetPath call in KeyboardShortcuts.cpp? I can't find any of this name in my computer and I got the crash too

**Comment by ALEEF02** [comment]
I'll try downloading the latest version and see if the crash still happens in a few hours

**Comment by iam-Mai** [comment]
How about the safe_strcpy(wrapped_string, text_input, 512);?
All 512 should be changed to 1024?

**Comment by janisozaur** [comment]
Yeah, that's why we have defines for such things… I'll fix it in a moment.

**Comment by ALEEF02** [comment]
I feel great contributing to this amazing and awesome project. Great job to the makers and creators!
