### ISSUE TITLE
Scenery picker shows non-researched scenery group

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#5367]
1. Open Crazy Castle
2. Place a Halloween tree (one of the last trees in the tree scenery group)
3. Click scenery picker and click the placed tree.

The scenery picker currently picks the first scenery group that contains the item we are looking for rather than choosing a scenery group that is currently available to the player. If the scenery item can not be placed because no researched group contains it, then an error should pop up informing the player.

**Comment by ot5darva** [comment]
I assume your talking about these trees? The scenery group the trees belong is already available at the start of the scenario. Tested in regular RCT2.

![creepytree crazy castle vanillarct2](https://cloud.githubusercontent.com/assets/26368692/25069478/a03fa23c-2236-11e7-990f-2e24579ffa4e.PNG)

**Comment by Gymnasiast** [comment]
Tested it. As ot5darva already pointed out, the Creepy Theming is already available from the start.
In addition, I tested with SXOT, moving the Mine theming to 'to be invented' and tried picking a mine shift. This has the desired result of not picking it, as it isn't invented.
