### ISSUE TITLE
windows platform_get_locale_language function cannot recognize some language

### ISSUE THREAD

**Issue by Lastorder-DC** [OpenRCT2/OpenRCT2#5369]
**OS:** Windows 7
**Version:** 0.0.7
**Commit/Build:** 4a97d53

some language is missing from windows `platform_get_locale_language` function(and looks like this function is never modified since 0.0.3 release)

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Comment by telk5093** [comment]
It seems that there are no languages such as below:
```
Japanese (ja-JP)
Korean (ko-KR)
Czech (cs-CZ)
Brazil Portuguese (pt-BR)
Russian (ru-RU)
Chinese (zh-CN)
Chinese (zh-TW)
```
https://github.com/OpenRCT2/OpenRCT2/blob/299e6c8974b2b346db8f316fe3ebed110776e10e/src/openrct2/platform/windows.c#L827

**Comment by Gymnasiast** [comment]
I could add the missing three-letter codes to the function that @telk5093 pointed to.

However, is there no way to get proper ISO locale codes in Windows? Searching on the internet suggests there is, and we could probably clean things up if we share the code that converts these ISO locale codes into the appropriate language in OpenRCT2.
@IntelOrca

**Comment by IntelOrca** [comment]
It should be using `GetUserDefaultLangID`.

**Comment by 733737** [comment]
Hasn't this been fixed already?

**Comment by Gymnasiast** [comment]
It has yes, I believe that @CookiePLMonster fixed it.

**Comment by CookiePLMonster** [comment]
This function has been refactored big time, so it is indeed likely fixed.
