### ISSUE TITLE
Custom currency resets to British Pounds on restart

### ISSUE THREAD

**Issue by RoelerCoaster** [OpenRCT2/OpenRCT2#5371]
**OS:** Windows 10
**Version:**  0.0.7
**Commit/Build:** 4a97d53

When a custom currency (symbol) is set in the options, this setting is not kept when restarting the game.
Instead, British pounds (£) is selected.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Set a custom currency in the options.
2. Restart the game
3. The currency is now British pounds (£)

**Comment by janisozaur** [comment]
Sounds like a missing test case in our ini parser.
