### ISSUE TITLE
Improper "special" track pieces in car ride and river rapids

### ISSUE THREAD

**Issue by ot5darva** [OpenRCT2/OpenRCT2#5373]
OS: Windows 8.1
Version: 0.0.7
Commit/Build: 4a97d53

When constructing a car ride or a river rapids ride, there are elevator track pieces listed in the "special" track menu. It's not possible to select them.

- [no] Reproducible in RCT2 (vanilla)?
- [yes] Multiplayer?

1. Construct a custom car ride or river rapids ride
2. Hold down the "special..." track piece menu

Screenshots / Video:
![improper elevator pieces](https://cloud.githubusercontent.com/assets/26368692/25069400/66273094-2234-11e7-8abb-e4809a4303b2.png)

Save game:
[improper_elevator_pieces_in_menu.txt](https://github.com/OpenRCT2/OpenRCT2/files/924125/improper_elevator_pieces_in_menu.txt)

**Comment by ALEEF02** [comment]
A lot of "specials" issues tonight
