### ISSUE TITLE
Saved game keeps crashing shortly after loading

### ISSUE THREAD

**Issue by adamlpi** [OpenRCT2/OpenRCT2#5377]
**OS:** Windows

I load my (single player) saved game and approx. 10-15 seconds in to playing it crashes.

**Dump file**
[c21ee8de-ecbc-4569-9fa8-ea9d92a4887c.txt](https://github.com/OpenRCT2/OpenRCT2/files/925283/c21ee8de-ecbc-4569-9fa8-ea9d92a4887c.txt)

**Save game:**
[Pinderland -.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/925290/Pinderland.-.sv6.txt)

**Comment by janisozaur** [comment]
We need to know which build generated this crash.

**Comment by janisozaur** [comment]
Also, the provided file doesn't look like a valid minidump.

**Comment by adamlpi** [comment]
My apologies, I should not have inserted the minidump as when the game crashes I get a notification saying that the game cannot create a dump and to log the issue on GitHub.

OpenRCT2-0.0.6.0-windows-portable-x64 on Windows 10. I hope this is the info that you need and thank you for your help.

**Comment by duncanspumpkin** [comment]
@adamlpi we need the commit hash it would be in the form of e0764e3. Since its 0.0.6 you are using you could also try switching to the latest build and seeing if the problem still occurs.

**Comment by adamlpi** [comment]
@duncanspumpkin I have switched to the latest build 0.0.7 but the same issue occurred. If I have the right info for the commit hash, it is 44db9ce80cc334e2b9009b8cd852bd895ae5e61e

**Comment by rwjuk** [comment]
Crash is due to dereferencing a null pointer in `banner_paint()` in `paint/map_element/banner.c`, line 58.

`banner_scenery` isn't checked to make sure it's not null (as seems to be the case after other uses of `get_banner_entry()`). Not sure how an entry with type 255 ended up in `gBanners` though...

![2017-04-17-134956_278x129_scrot](https://cloud.githubusercontent.com/assets/16639257/25089355/d1830b42-2374-11e7-8d97-5e22568c11cc.png)

**Comment by adamlpi** [comment]
@rwjuk Thank you for confirming this. I am not entirely sure how to rectify this issue?

**Comment by IntelOrca** [comment]
@rwjuk This happens a lot particularly with hacked parks containing rides with null ride entries. I'd add the null check.

**Comment by rwjuk** [comment]
@IntelOrca On it now.

**Comment by adamlpi** [comment]
What do I need to do to fix this issue? I am not a program writer so do not understand all of this jargon! Sorry. I have upgraded to version 0.0.7 of the game but the issue is still occurring. I understand the issue to be linked to a banner in the park but I have no idea how to fix this. I cannot even delete the banner. Any help is much appreciated.

**Comment by rwjuk** [comment]
You need to update to the very latest version. What operating system (e.g. Windows, OS X) are you using?

**Comment by duncanspumpkin** [comment]
@adamlpi you will need to download the very latest build of 0.0.7 and it should fix the issue. I can patch the save if you would prefer to run the older version.

**Comment by duncanspumpkin** [comment]
You might also find using the launcher to be useful as it will keep you up to date with any future builds.

**Comment by adamlpi** [comment]
I have downloaded the latest build of 0.0.7; that is the version I am using now and fingers crossed, it hasn't crashed yet. Thank you so much guys!
