### ISSUE TITLE
Game crashes in scenario editor when scenery or pathing is clicked on

### ISSUE THREAD

**Issue by RCMatt** [OpenRCT2/OpenRCT2#5381]
**OS:**  Windows 10
**Version:** Latest Stable, 0.0.7

Making a scenario to build a park, made the landscape. When I went to add scenery it crashed as I clicked on the tab. I thought it might have been custom scenery I added in the invention list but when I clicked on the path tab it also crashed. When it crashed it said to post an issue here.

**Steps to reproduce:**
1. Click on scenery or pathing tab

**Save game:**

[2017park4.zip](https://github.com/OpenRCT2/OpenRCT2/files/926556/2017park4.zip)

**Comment by janisozaur** [comment]
Ok, this is fun. Somehow the scenario here doesn't have any path selected.

@RCMatt do you remember how have you managed to create such a scenario?

**Comment by xp4xbox** [comment]
This was an easy fix for me. All you have to do to fix it, is open up object selection and select then deselect a path object. Close the window, and everything works fine.

**Comment by Broxzier** [comment]
The tarmac footpath should always be selected. Did you use a third party program like ParkDat to change the object list?

**Comment by RCMatt** [comment]
Okay so I guess this is fixed, I did select all the objects and saved (hence why its 2017park4 and not 1) because it was crashing randomly. I do not know maybe if it because I selected custom objects but after I went back to the object select everything was deselected besides the defaults. After I went back to landscape and it worked fine. I don't know why but I guess I will make it work.
