### ISSUE TITLE
Addition of a pop up, when the game is paused.

### ISSUE THREAD

**Issue by pulkitraggarwal** [OpenRCT2/OpenRCT2#5390]
OS: MacOS Sierra 10.12.4
Version: 0.0.7

While I was playing the game, I realized that when the user pauses the game there is a lack of indication that the game is actually paused. I feel, it would be nice if a message was prompted to the user when the game is paused. 
This could have could have other implications such as modifying the options etc. 

Here is my modification to the pause buttons function. I have added a new window that would promt the user with a message "Game is paused".

Kindly, share your views about this feature. @IntelOrca 
Thanks.

![screen shot 2017-04-18 at 6 13 46 pm](https://cloud.githubusercontent.com/assets/19470853/25155517/6a3cd572-2463-11e7-968d-8c31450ed4f1.png)

**Comment by Gymnasiast** [comment]
It's odd that your dialog has 'RollerCoaster Tycoon 2' in the title. But that's not really the most important thing.

What is import is that the pause button appears pressed when the game is paused. It's clear enough, especially if you consider that the whole map grinds to a halt when the game is paused (unlike, say, SimCity). And if the player fails to pay attention to something as ludicrously simple as that, what hope does he have for the rest of the game?

**Comment by IntelOrca** [comment]
Most games do not have pause boxes unless its to prevent cheating (e.g. thinking time for a puzzle game) or to show a menu. Neither of these apply for this game.

**Comment by pulkitraggarwal** [comment]
Thanks for your input guys.

**Comment by ensiform** [comment]
Wouldn't at least an indicator with Red text that says paused would be good though?

**Comment by jensj12** [comment]
As Gymnasiast said, there are already enough indicators. All rides stop moving, guests no longer walk, the pause button is pressed, banners stop moving, ...
