### ISSUE TITLE
ESC Button to toggle Windowed Mode

### ISSUE THREAD

**Issue by raphaelsetin** [OpenRCT2/OpenRCT2#5392]
**OS:** macOS Sierra 10.12.4
**Version:** 0.0.7
**Commit/Build:** 9314b8b

I think this feature would be a good implementation to the game since the best way to "exit" fullscreen and go to it would be to press the green button on top (on a macbook). I saw that OpenRCT2 didn't use the ESC button for anything, so I though it would be a good idea to make it toggle the windowed mode back and forth.

- [X] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Press ESC button in windowed mode --> maximizes the screen
2. Press ESC button as well in maximized window --> sets the screen to window mode

**Screenshots / Video:** [no video nor screenshots]

**Save game:** [no save game]

**Comment by IntelOrca** [comment]
You can already use `ALT+ENTER`.

**Comment by Margen67** [comment]
Escape is already used for "cancel contruction mode" and toggle windowed mode can be rebound.

**Comment by raphaelsetin** [comment]
@IntelOrca But don't you think it would be better with ESC button, since it's more convenient? If so I could try to replace the ALT+ENTER for the ESC button instead.

**Comment by raphaelsetin** [comment]
@Margen67 @IntelOrca  Hummm, I see. Do you guys think it's totally unnecessary or should I go for it and change ESC to toggle windowed mode and maybe designate another button/hotkey for "cancel construction mode"?

**Comment by ensiform** [comment]
Alt+Enter is horrifically the most correct key combo to toggle Fullscreen for games.

**Comment by raphaelsetin** [comment]
Okk, that's fine! Thanks for the input on the issue btw @ensiform
