### ISSUE TITLE
Message Shortcut to New Rides Window for Ride Types Without Default Trainset Does Not Focus on Correct Ride Type

### ISSUE THREAD

**Issue by Androgeos** [OpenRCT2/OpenRCT2#5400]
**OS:** Windows 10
**Version:** 0.0.7
**Commit/Build:** e72542b

When a ride, without its default trainset available in the scenario, is researched, clicking on the blue icon in the message does not cause the New Rides window to focus on the correct ride type, instead apparently causing said window to focus on the Transport rides tab.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

# Steps to reproduce:
The following steps provided are just one way to trigger this glitch - you should be able to replicate it in most scenarios that make use of researchable rides using assets not available in vanilla RCT2. For example, I have been able to replicate the glitch with the Wooden Roller Coaster in the Time Twister scenario "Future - First Encounters".
**You need the data files from RollerCoaster Tycoon 2: Wacky Worlds in order to replicate the glitch via the steps below.**
1. Load the scenario "Australasia - Ayers Rock", OR load the save game attached. If you do the latter, skip the first sentence in Step 2.
2. Play the game normally until a message appears stating that the Junior Roller Coaster is available as a new ride/attraction. If this message disappears from your normal view, look for it in the Recent Messages window.
3. Click the blue icon in the message that states that the Junior Roller Coaster is available. Notice that, while the Build new ride/attraction window appears, it instead focuses on the Miniature Railway.
4. Compare the result in Step 3 to similar messages for other rides/attractions.

# Screenshots / Video:
https://www.youtube.com/watch?v=-LPphr9B4wY

# Save game:
[Ayers Adventure.zip](https://github.com/OpenRCT2/OpenRCT2/files/949690/Ayers.Adventure.zip)

**Comment by Gymnasiast** [comment]
This is caused by having 'select by track type' on using ride entries that have their first track type set to 255 (ride entries can have up to three track types, although this does not seem to be used much or really work properly).

I fixed this in the ride groups PR.

**Comment by Gymnasiast** [comment]
Solved by 96a7a8ab508f09e3d0220ca6b363fa8ee8874201.
