### ISSUE TITLE
Crash if 128 attractions are selected in scenario editor

### ISSUE THREAD

**Issue by mariuszkurek** [OpenRCT2/OpenRCT2#5401]
**OS:** Windows 8.1 x64
**Version:** 0.0.7
**Commit/Build:** 0219da2

Game can:
- crash when saving the scenario, when you open that one, the entrance is textureless and any interaction with it causes a crash
- save scenario properly, but when you try to open roller coaster tab in order to build one, another crash happens

- [ ] Reproducible in RCT2 (vanilla)? Exception Raised - Access Violation; Error Location: Unknown
- [ ] Multiplayer? don't know

**Steps to reproduce:**
1. Open scenario editor
2. Choose 128 attractions (I choose every roller coaster and something else at random)
3. Make it "playable" (entrance, territory)
4. Save

**Dump+save file**
Post below, I couldn't upload because "We don’t support that file type."

**Comment by janisozaur** [comment]
[84e1d1c1-532d-4b3d-83a3-f37b17fbf8ff.zip](https://github.com/OpenRCT2/OpenRCT2/files/951236/84e1d1c1-532d-4b3d-83a3-f37b17fbf8ff.zip)

**Comment by janisozaur** [comment]
@oscareczek nice avatar there.

**Comment by siomy11** [comment]
Couldn't replicate this on my game, will try again.

**Comment by oscareczek** [comment]
Forgotten to mention:
1. Error while crashing says "Failed to load water pallete"
2. I use Polish "Złota Edycja" version of RCT2.

**Comment by janisozaur** [comment]
It only does so after https://github.com/OpenRCT2/OpenRCT2/commit/73efe0755dbb73574db3f028da377c717e0a23fd

**Comment by Nubbie** [comment]
Commit 0219da2 for Janisozaur's dumpfile

**Error message;**
Unhandled exception at 0x00007FF8DE664B17 (openrct2.dll) in 84e1d1c1-532d-4b3d-83a3-f37b17fbf8ff.dmp: 0xC0000005: Access violation reading location 0x00000037C5C47028.

Call stack;
```
>	openrct2.dll!load_palette(...) Line 525	C
 	openrct2.dll!TitleSequencePlayer::PrepareParkForPlayback() Line 431	C++
 	openrct2.dll!TitleSequencePlayer::LoadParkFromFile(const char * path=0x0000001fc353c7a8) Line 363	C++
 	openrct2.dll!TitleSequencePlayer::ExecuteCommand(const TitleCommand * command) Line 255	C++
 	openrct2.dll!TitleSequencePlayer::Update() Line 140	C++
 	openrct2.dll!title_load() Line 150	C++
 	openrct2.dll!window_loadsave_select(rct_window * w, const char * path=0x0000001fc131f690) Line 786	C
 	openrct2.dll!window_loadsave_textinput(rct_window * w=0x00007ff8df46f680, int widgetIndex, char * text=0x00007ff8dee948e0) Line 446	C
 	openrct2.dll!window_text_input_key(rct_window * w=0x00007ff8df470040, int key) Line 347	C
 	openrct2.dll!game_handle_keyboard_input(...) Line 1524	C
 	openrct2.dll!game_update(...) Line 287	C
 	openrct2.dll!rct2_update(...) Line 408	C
 	openrct2.dll!OpenRCT2::RunGameLoop() Line 427	C++
 	openrct2.dll!openrct2_launch() Line 301	C++
 	openrct2.dll!LaunchOpenRCT2(int argc, wchar_t * * argvW) Line 40	C++
 	[External Code]	
```

Local;
```
		dest_pointer	Variable is optimized away and not available.	
+		g1	{offset=0x0000001fd29ad040 <Error reading characters of string.> width=-14424 height=-15533 ...}	rct_g1_element
		palette	Variable is optimized away and not available.	
		water_type	Variable is optimized away and not available.	
		width	Variable is optimized away and not available.	
		x	Variable is optimized away and not available.	
```

**Comment by Gymnasiast** [comment]
I cannot reproduce this any more, and it has been four years, so I'm assuming it has been solved.
