### ISSUE TITLE
Add a button to clear all windows

### ISSUE THREAD

**Issue by Pikamander2** [OpenRCT2/OpenRCT2#5403]
When you're managing a bunch of different rides and staff and guests, it's easy to end up with a bunch of windows open. Sometimes you just want to clear them all off to make things less cluttered.

In OpenTTD, you can press the Delete key to instantly close all of your open windows. Since OpenRCT2 doesn't seem to use this key, can we make it close all open windows?

**Comment by Margen67** [comment]
Shift+Backspace

**Comment by Gymnasiast** [comment]
Have you never bothered to look in the Shortcut Keys window? This function has been in RCT since the _very first edition_!
