### ISSUE TITLE
Crooked House Tracked Rides Not Running

### ISSUE THREAD

**Issue by GForceNE** [OpenRCT2/OpenRCT2#5417]
**OS:** Windows 10]
**Version:** [0.0.7]
**Commit/Build:** [1ab90d8]

A common hack used in some RCT parks is to change the ride track type to "crooked house", this enables the track to become invisible... often useful for realistic rapids rides to hide the default rapids track.  However, upon loading these in Open, the rides do not run and will simply sit in the station forever and never move.  The ride will being to work again if the track type is switched back to the original type, in this case river rapids... and also if its then moved back to crooked house.  So its simply an issue when loading games up and not when creating new rides, at least untill the games are re-loaded.

This basically breaks a large number of parks that rely on this hack for rides to run.

- [No] Reproducible in RCT2 (vanilla)?
- [YES] Multiplayer?

**Steps to reproduce:**
1. Load Park with a tracked ride set to "crooked house" track type.  I can supply more examples if needed.

**Screenshots / Video:**
-Ride upon loading up the park simply does not dispatch vehicles.
![worlds of fun 2017-04-30 15-30-17](https://cloud.githubusercontent.com/assets/18511011/25567410/c1269372-2dba-11e7-9d0f-d16eee1c45f4.png)

-Ride set back to the original track type, double closed and re-opened, works again.
![worlds of fun 2017-04-30 15-30-58](https://cloud.githubusercontent.com/assets/18511011/25567409/c126905c-2dba-11e7-9864-ba0a1bd762a3.png)

**Save game:**
[G Force's Worlds of Fun - G Force.zip](https://github.com/OpenRCT2/OpenRCT2/files/966947/G.Force.s.Worlds.of.Fun.-.G.Force.zip)

**Comment by duncanspumpkin** [comment]
Caused by https://github.com/OpenRCT2/OpenRCT2/pull/5008
