### ISSUE TITLE
[RCT1 Import] Real name behavior is like in RCT1 and not like in RCT2.

### ISSUE THREAD

**Issue by Horsti12** [OpenRCT2/OpenRCT2#5418]
In RCT1 when you start a park the games not have real names so everytime you have to select "show real names" in the options if you want the real names.

In RCT2 it is the exactly the opposite. It has "show real names" already selected when you load a new scenario. And here now comes the problem. When you import a RCT1 scenario file (SC4) than it has the exact behavior as in RCT1.

So it should be changed that when you import a RCT1 scenario (SC4) in the OpenRCT2 that the option "show real names" is already selected. Or that we have a option in the option menu to select if we want real names when we start a new scenario or guest numbers.

**Comment by rwjuk** [comment]
The 'show real names of guests' option is currently stored in the save game/scenario - this is a technical limitation of the original RCT(2) save formats.

In RCT1, it was off by default for all scenarios, and in RCT2, on by default. So when you import an RCT1 scenario, ORCT2 is simply loading the setting from the file.

A persistent setting (i.e. you set it once and it carries across all games) is planned, but will require some careful thought.

**Comment by Gymnasiast** [comment]
The changes @rwjuk mentioned have been implemented in the meantime, so closing this.
