### ISSUE TITLE
Can't connect to server via IPv6

### ISSUE THREAD

**Issue by Leurak** [OpenRCT2/OpenRCT2#5430]
**OS:** Ubuntu Server 16.04
**Version:** 0.0.7
**Commit/Build:** b713b79

When hosting a dedicated server, I can't connect using IPv6.

The console says `IPV6_V6ONLY failed. 92`.
92 means Protocol not available, but it works fine with a lot of other applications. When redirecting the port locally using socat, I can even join using IPv6, so there seems to be nothing wrong with the server or firewall.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Start a (in my case headless) server
2. Try to join using IPv4 - it works
3. Try to join using IPv6 - it fails
4. Redirect the port locally using socat - it works

**Comment by Leurak** [comment]
There should be a way of specifying the listening IP address, as want a dedicated IPv6 address for the server. This might also fix this problem.

**Comment by Leurak** [comment]
Currently working on that

**Comment by ipatix** [comment]
So does that mean that IPv6 still doesn't work if I don't specify the listen address manually? Honestly, having to do that seems like a crude workaround. Also, is there a way to specify multiple addresses (v4 + v6)?

**Comment by IntelOrca** [comment]
I think you would need to create two sockets, one that listens on IPv4 and one that listens on IPv6. This would be a separate enhancement request.

**Comment by ipatix** [comment]
So it's not possible to just listen on * and have IPv6 function correctly?

**Comment by IntelOrca** [comment]
From my understanding, * still has to either represent IPv4 or IPv6, it can not do both without separate sockets.
