### ISSUE TITLE
Dedicated Server Build

### ISSUE THREAD

**Issue by Leurak** [OpenRCT2/OpenRCT2#5434]
It would be awesome to have a build without all the graphical stuff that just contains the server, making use of way less dependancies.

**Comment by janisozaur** [comment]
We are already working on that: https://github.com/OpenRCT2/OpenRCT2/pull/5336

**Comment by Leurak** [comment]
Okay. I thought I could do it but if there are already other people working on it...

**Comment by janisozaur** [comment]
The PRs are far(?) from solving this and there will surely be still work to do, so your help would be appreciated. Join us on gitter to coordinate the efforts.

**Comment by janisozaur** [comment]
#5458 has been merged

**Comment by janisozaur** [comment]
We can now offer a fully headless build that doesn't require SDL2
