### ISSUE TITLE
Scenery picker resets colors

### ISSUE THREAD

**Issue by Phyxion** [OpenRCT2/OpenRCT2#5437]
If you select a tree, for example, with the scenery picker, it resets the last used colors (for example, for a block) to the default colors. If you use the regular object window, it remembers this.

**Comment by IntelOrca** [comment]
The scenery eyedropper tool will set the colours to that of the object you picked. If the object does not have any colours, then it will probably be the default ones.

**Comment by Broxzier** [comment]
It may be nicer to only overwrite the colours that the selected object uses.
