### ISSUE TITLE
Mechanics never get to ride

### ISSUE THREAD

**Issue by Phyxion** [OpenRCT2/OpenRCT2#5439]
Not sure if this is related to #5002 (the only mechanic related issue I could find)
Pinging @zaxcav

Using the latest dev build (14ec639b4769a80227bb0eb0ba446d0c176dc11f)
[Ayers Adventure.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/979944/Ayers.Adventure.sv6.txt)

In this save, you'll see that _The Thundering Eel_ is broken. The mechanics either just give up or walk around the park (at the opposite direction). They never seem to get to the ride.

**Comment by Phyxion** [comment]
![bug](https://cloud.githubusercontent.com/assets/7643972/25759094/5c0f130e-31d1-11e7-82ec-feba48f50f9e.png)

Most mechanics seem to make said route (blue one they should be taking).
At 'end' they just give up -> another mechanic is selected.

**Comment by Gymnasiast** [comment]
Tagging @zaxcav , our pathfinder. ;-)

**Comment by zaxcav** [comment]
@Phyxion The path is not connected to the exit of Thundering Eel, so the mechanics cannot walk in.
Reconnect the path to the exit and the problem is resolved.

**Comment by Phyxion** [comment]
Hmm, I see, totally missed that. Why isn't the path connected then, am I wondering. If you play the game a little faster, you'll see that _Spinny_ isn't connected either (and mechanics don't go to it either).

Maybe mechanics should be able to step over that (tiny) bit of gravel?

**Comment by Margen67** [comment]
If clearance checks are disabled and hover over the entrance with the footpath window open it will disconnect any nearby paths.
