### ISSUE TITLE
Autosaves in Landscape folder aren't being cleaned up

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#5440]
**OS:** Windows 10
**Version:** 0.0.8
**Commit/Build:** 14ec639

I left the game open in the background while in the scenario editor for a while, and now there are a lot of auto saves in the _My Documents/OpenRCT2/Landscape_ directory.

**Steps to reproduce:**
1. Open scenario editor
2. Let the auto-save feature kick in 10+ times
3. Notice how after the 11th save, the oldest one doesn't get removed

**Comment by rwjuk** [comment]
This is because the `limit_autosave_count()` function only checks the `save` folder, not the `landscape` one. I'm on it.
