### ISSUE TITLE
about arabic support

### ISSUE THREAD

**Issue by Omaranwa** [OpenRCT2/OpenRCT2#5441]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.0.8]
**Commit/Build:** [e.g. 426e106]

hello there can i add arabic lang to this game

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by Gymnasiast** [comment]
Yes, you can. In short, you need to go the [Localisation repository](https://github.com/OpenRCT2/Localisation) and follow the instructions [here](https://github.com/OpenRCT2/Localisation#creating-a-new-language).

If you need more help, please say so.

After you have finished your initial translation, we will add support to the game code to display Arabic.

**Comment by Nubbie** [comment]
I would say this issue is done :D

**Comment by Omaranwa** [comment]
yep iam working on it

**Comment by Nubbie** [comment]
You could close it and we thank you for your contribution :)

**Comment by Gymnasiast** [comment]
Closing this as it was a question which has been answered.
