### ISSUE TITLE
Staff patrol area duplicates

### ISSUE THREAD

**Issue by thegreatpl** [OpenRCT2/OpenRCT2#5445]
**OS:** Windows 10
**Version:** 0.0.7
**Commit/Build:** 

When creating patrol areas for staff, sometimes the patrol area is duplicated across onto another staff member. For instance, when Mechanic 1 has a patrol area created, mechanic 2 gets the same patrol area at the same time. Mechanic 3, bought later, meanwhile, does not get the patrol area. Any changes to the patrol area through either of the Mechanics will change the patrol area for both of them. 

**Steps to reproduce:**
1. Hire 2 mechanics (may only be on parks which already have one? Not sure. Was playing White Water Park from RCT1. I had, however, noticed some odd behaviour previously while playing, but not actually realised what was happening). 
2. Add patrol area to one of them. 
3. The other mechanic should now have the same patrol area. 

**Save game:**

**Comment by rwjuk** [comment]
I can't seem to replicate this on the latest build - could you download that and retry?

**Comment by thegreatpl** [comment]
Save attached. If I recall, I did use the newgame from within a different scenario, and do tend to hire staff when paused. 

Pokey Park was what I started this scenario from. Possibly coming from Katies Dreamland. Though may have dodged back to main menu. Actually, I may have peeked at the newly unlocked scenario. 

Version build I'm using would be 1dffe4e, based on the build times. 
[White Water Park attempt 1.zip](https://github.com/OpenRCT2/OpenRCT2/files/981184/White.Water.Park.attempt.1.zip)

**Comment by rwjuk** [comment]
Confirmed that mechanic 1 & 2's patrol areas seem 'linked' in that save - you edit one patrol area and it affects the other. Newly hired mechanics do not seem to exhibit any oddities.

**Comment by rwjuk** [comment]
This is an RCT1 import bug, quoting @IntelOrca 

> The resolution is add code to the S4Importer for setting gStaffModes, gStaffPatrolAreas and staff_id for staff peeps

**Comment by IntelOrca** [comment]
@Gymnasiast
