### ISSUE TITLE
Guests not attracted to Funtopia

### ISSUE THREAD

**Issue by RogoDarius** [OpenRCT2/OpenRCT2#5449]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.0.8]
**Commit/Build:** [e.g. f2debce]

Closing and reopening Funtopia does not replenish guests. (I did this so I could get money from entrance fees.)
This occurs in multiplayer and singleplayer.
Also for some reason in multiplayer, you can't set prices for any rides (not helping the money situation).
I even tried modifying the existing rollercoasters in case guests are attracted to rides under construction. - This didn't seem to do anything either.

- [No] Reproducible in RCT2 (vanilla)?
- [Yes] Multiplayer?

**Steps to reproduce:**
1. Close park
2. Close all rides
3. Set entrance fee to £20
4. Build some rides if you like
5. Re-open everything
The only way I can get guests to enter the park is with an advertising campaign then I'm maxed out on loan.

**Screenshots / Video:**
![funtopia](https://cloud.githubusercontent.com/assets/12530301/25782882/41e5870e-334a-11e7-9cee-b7b472622289.PNG)

**Save game:**
[Funtopia.zip](https://github.com/OpenRCT2/OpenRCT2/files/981735/Funtopia.zip)

**Comment by rwjuk** [comment]
I don't think this is a bug. I ran the save you provided on maximum speed for a while, and saw that guests are being generated at about the rate I'd expect (comparing against closing and reopening Funtopia in a fresh game and doing nothing else).

Closing and re-opening a park will not help you gain extra money in "pay to enter park/free rides" scenarios. In "free entry/pay for rides" scenarios, closing and re-opening all rides can gain you a small amount of extra income.

The reason you cannot charge for rides is that scenarios are one or the other - free rides or free park entry - as in the original games.

**Comment by RogoDarius** [comment]
I've used this loads of times in the original game and the guests always come back to some value depending on how many rides there are in the park.
For the park to be opened with like 8 rides & a load of shops and have 5 guests come in in the first 15 minutes was bizarre.
Aside from this, I should mention that the park allows me to charge an entrance fee as well as ride admission in singleplayer but only an entrance fee in multiplayer.
The reason we pulled this maneuver in multiplayer was because there were 200 guests in the park, yet we'd gained no money from their entrance fees - so we closed the park, and usually, all 200 would come back in a few months or so, but they simply didn't. (Meaning we couldn't get anywhere in this relatively easy park from the original game.)
So we gave up playing :( which was not what we expected to do that evening.

**Comment by rwjuk** [comment]
Is your copy of Funtopia from the original RCT1 (i.e. an SC4 file) or an RCT2 recreation (an SC6 file)?

**Comment by RogoDarius** [comment]
I'd guess it must be an SC4 - I just chose it from the main ORCT2 menu after importing the previously installed RCT data.

**Comment by rwjuk** [comment]
Awesome, thanks. Will investigate.

**Comment by RogoDarius** [comment]
Thanks - it definitely felt odd to us (2 people who've played a lot of the first 3 games).
I'd be playing ORCT2 right now if it weren't for these few niggles. :D

**Comment by Gymnasiast** [comment]
Hm, I tested it. Even after setting the entry price to £0 hardly any guest comes in. Yet the park rating is more than sufficient enough.

**Comment by rwjuk** [comment]
Starting to wonder whether this is a general bug with SC4 imports, as I'm seeing a similar failure to generate guests in a couple of other SC4 scenarios I tested...

**Comment by rwjuk** [comment]
Here's a ZIP of a Southern Sands savegame generated from an SC4 and SC6 for testing. The SC4 version has the bug.

[Southern Sands.zip](https://github.com/OpenRCT2/OpenRCT2/files/983343/Southern.Sands.zip)

**Comment by rwjuk** [comment]
I know what's going on here - `gNumGuestsHeadingForPark` is ending up with ludicrously high values (> 65000). Looking into why now.

**Comment by rwjuk** [comment]
@RogoDarius Attached is a fixed version of your Funtopia save should you wish to continue playing it.
[Funtopia.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/984898/Funtopia.sv6.zip)

**Comment by RogoDarius** [comment]
Thanks! :D We'll give it a go.

**Comment by RogoDarius** [comment]
While this works, I'm concerned as to what should be happening regarding entrance fees & ride tickets.
In singleplayer, you can charge for both, in multiplayer, you can only charge for entrance fees.
Yet I'm pretty sure in the original game, this was a park where you should only be able to charge for ride tickets.
Does this need raised, or is this a quick enough importing fix for .sv4?

**Comment by rwjuk** [comment]
As far as I know, in single player the park behaves as expected for an RCT1 (CF/AA) import - free rides, pay for park entry. Can you charge for rides as well?

**Comment by RogoDarius** [comment]
Yeah if I start a singleplayer game on Funtopia, I can charge for both. - If I do it in multiplayer, it's just entrance fees.
Both of these are incorrect, as it should be rides only. (As in RCT+AddedAttractions)

**Comment by rwjuk** [comment]
@RogoDarius That doesn't happen for me - can you raise a separate bug report about that.

**Comment by RogoDarius** [comment]
Ok :)

**Comment by RogoDarius** [comment]
Raised separate bug as 5457^
