### ISSUE TITLE
Crashing is predictable with current version

### ISSUE THREAD

**Issue by TerryRCT2** [OpenRCT2/OpenRCT2#5461]
**OS:** Windows 7
**Version:** 0.0.8-2
**Commit/Build:** a53b01d

I downloaded this version of OpenRCT2 within the past 24 hours, and I've found two ways that it will "fail to recreate the dump" and crash, one being as simple as attempting to enter a multiplayer server. The other way is by opening the Object Selection and adding a piece of scenery. Both ways crash the game every time without fail.

- [NO] Reproducible in RCT2 (vanilla)?
- [YES] Multiplayer?

**Steps to reproduce:**

Method One
1. Open Multiplayer
2. Click on a server

Method Two
1. Open a saved park
2. Add scenery to object selection*
3. Place scenery
4. Wait indefinitely

*This is even the case if every ride that isn't already in use is removed from the Object Selection. 

**Screenshots:**

![image](http://i.imgur.com/55RE9aX.jpg)

![image](http://i.imgur.com/La2tlmw.jpg)

**Comment by janisozaur** [comment]
Yes, the library we use for creating dumps has been misbehaving lately. You can still generate a dump that will be very useful to us. Just induce a crash, then when the error message pops up, don't close it, but follow these steps: https://support.kaspersky.com/us/general/dumps/1419

**Comment by IntelOrca** [comment]
For the crash in the server list, is it only for a specific server or does it happen with every server?

**Comment by Nubbie** [comment]
Does this issue still occur for you?
