### ISSUE TITLE
"NO ENTRY" Signs Not Operational

### ISSUE THREAD

**Issue by Cruplezone** [OpenRCT2/OpenRCT2#5462]
**OS:** MacOS
**Version:** 0.0.8
**Commit/Build:** a53b01d

Usually renaming a walkway banner sign to 'NO ENTRY' is supposed to prevent peeps from entering and IIRC the sign is supposed to turn red. Neither of these occur

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Comment by rwjuk** [comment]
You need to click the "no entry" button on the sign window to make it function as a no entry sign. Simply changing the text won't do it.

![screen shot 2017-05-10 at 13 19 11](https://cloud.githubusercontent.com/assets/16639257/25898258/4641705c-3583-11e7-913f-34f73f09a426.png)

**Comment by Cruplezone** [comment]
@rwjuk thank you I am a goofball

**Comment by rwjuk** [comment]
No problem! 👍
