### ISSUE TITLE
scenario_objective_check_guests_by function uses improper value types

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#5465]
On 3331ab8, while reviewing #5455.

It looks like `scenario_objective_check_guests_by` in `src/openrct2/scenario/scenario.c` function uses improper types to validate required conditions (`sint16` locally vs `uint16` of the globals)

**Comment by Gymnasiast** [comment]
Speaking broadly, I have encountered a lot of places where the either the size or signedness of the integer did not make a whole lot of sense to me.
