### ISSUE TITLE
Available Construction Rights View Only Works Once

### ISSUE THREAD

**Issue by Androgeos** [OpenRCT2/OpenRCT2#5470]
**OS:** Windows 10
**Version:** 0.0.8
**Commit/Build:** b83934d to 3ba33d0

In any scenario where construction rights are available for sale, the Land tool will only indicate construction rights correctly when it is opened for the very first time after the scenario, or a saved game of the scenario, is loaded. If the Land tool is closed and reopened, it will not indicate such tiles, although the player can still purchase and build on them normally.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

# Steps to reproduce:
1. Start a scenario with construction rights available for purchase by the player.
2. Open the Land tool.
3. Click the button to purchase construction rights and purchase some construction rights.
4. Close the Land tool.
5. Repeat Steps 2 (and 3).
6. Save the game.
7. Load the game you just saved.
8. Repeat Steps 2 to 5.

# Video
https://www.youtube.com/watch?v=K41SN7IAFYs

**Comment by rwjuk** [comment]
Whoops - this one's my fault. Introduced while fixing #4748!
