### ISSUE TITLE
Game Crashes When Keyboard Used for Naming/Unresponsive to Shortcuts

### ISSUE THREAD

**Issue by coasterninja** [OpenRCT2/OpenRCT2#5473]
**OS:** macOS Sierra 10.12.2
**Version:** v0.0.8-HEAD build 89972d4
**Commit/Build:** 2197/db8b03e

OpenRCT2 will open with one of three screens: The regular screen, the regular screen with console activated, and only the background with no playing options. When able to go to a game, no keyboard shortcuts (ENTER to rotate, C to chat, all of them!) will be functional. Attempting to enter text in a text box will cause OpenRCT2 to crash.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Enter Multiplayer or Single Player game
2. Attempt to use keyboard and prepare to see nothing happen until you attempt to name anything

Example of blank screen:
![nothing](https://cloud.githubusercontent.com/assets/28678687/26029510/83579132-3804-11e7-8419-d9822e85d01e.jpeg)

**Comment by rwjuk** [comment]
Do these issues occur in the latest build from the develop branch (i.e. what you'd get from the launcher or if you followed the instructions in the readme)? The commit hash you referenced (89972d4) seems to be from a pull request branch.

**Comment by Broxzier** [comment]
Did you accidentally press 't' by any chance?

**Comment by rwjuk** [comment]
The crash on using a textbox has been fixed as of 202b069. Looking into the other issues now.

**Comment by IntelOrca** [comment]
@rwjuk thanks

**Comment by rwjuk** [comment]
General keyboard input issues fixed as of c155d0e.
