### ISSUE TITLE
Feature: Toggle All Option For Rides Cheats Menu

### ISSUE THREAD

**Issue by xp4xbox** [OpenRCT2/OpenRCT2#5474]
This would be a very useful feature for especially me, because whenever I create hacked rides, i need most cheat options enabled, and it is annoying to have to re-enable them every time I want to work on a custom ride.

![ne workbench 2017 by louis 2017-05-14 09-02-13](https://cloud.githubusercontent.com/assets/24964930/26034042/64a04290-3884-11e7-8c5a-76a4ac30bef6.png)

**Comment by Gymnasiast** [comment]
We plan to save cheats in saved games when we switch to our own format. That would be the preferred solution to this problem IMO.

**Comment by harrysbird** [comment]
I Love to have Save Cheats Feature but it's Requires New Save Format for that's

**Comment by xp4xbox** [comment]
Too arbitrary.
