### ISSUE TITLE
Sprite index crash for car view on car ride

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#5489]
**OS:** Windows 10
**Version:** 0.0.8
**Commit/Build:** bfa03583fabe4968bc37e8477649da24af1fd95f

**Steps to reproduce:**
1. Open Grand Prix ride window.
2. Select Car 1 view.

**Screenshots / Video:**
![image](https://cloud.githubusercontent.com/assets/1482259/26167184/01c2810e-3b2e-11e7-8146-1f638e5a57ea.png)

**Save game:**
[bpb.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/1008571/bpb.sv6.txt)

**Comment by rwjuk** [comment]
Can reproduce this by simply loading the regular Blackpool Pleasure Beach SC4. That's a suspiciously large number... something weird going on!

**Comment by IntelOrca** [comment]
> That's a suspiciously large number...

Not sure if you are being sarcastic or not. `0xFFFFFFFF` or `-1` - either the importer needs checking or we need to guard against this.

**Comment by rwjuk** [comment]
@IntelOrca Oh I recognised it and assumed that a stray `-1` value had gotten in somehow. I'll have a look in a bit.
