### ISSUE TITLE
Attempting to log into servers results in crash

### ISSUE THREAD

**Issue by denosor** [OpenRCT2/OpenRCT2#5496]
Windows 10
0.0.8
bd7bf49

When attempting to connect to multiplayer servers, slightly before being complete downloading map, it comes up with a dialogue 'Failed to create the dump. Please file an issue...' followed by a crash.

- [N] Reproducible in RCT2 (vanilla)?
- [Y] Multiplayer?

**Steps to reproduce:**
1. Connect to server
2. Wait until it comes up with dialogue

**Screenshots / Video:**
https://www.youtube.com/watch?v=is9vWV2DFxA

**Comment by IntelOrca** [comment]
Does it happen with every server?

**Comment by denosor** [comment]
So far yes, all servers that are actually playable (the others do not give me permissions) on i cannot connect to. The dump file is here

**Comment by PFCKrutonium** [comment]
Upload it to Mega.co.nz or a similar service.

**Comment by AnnaSaysHi** [comment]
From the looks of the video, that crash is identical to the one i've been getting. I'd like to ask where you got your copy of RCT2 from and if you can play scenarios you've downloaded off the internet (scenarios created by yourself should work).

**Comment by denosor** [comment]
Before i tried open rct2, i used a copy from steam however my friends steam share somehow got logged out so i torrented a copy off the internet. Could that be the cause? I might buy one if this is the case. Also my dump file is here: https://mega.nz/#!J7AGRRjA!RO6zopdqHjDfIfV7kvlk0AL0RjI6SKzpHruxKahgQ4Q

**Comment by IntelOrca** [comment]
I was unable to find anything helpful after inspecting the dump. Only that it failed somewhere in `Network::UpdateClinet()`:
```
if (!ProcessConnection(*server_connection)) {
    // Do not show disconnect message window when password window closed/canceled
>   if (server_connection->AuthStatus == NETWORK_AUTH_REQUIREPASSWORD) {
        window_network_status_close();
    } else {
```

**Comment by denosor** [comment]
So what exactly do you think is the issue? is it an issue with connecting to the servers?

**Comment by IntelOrca** [comment]
It's hard to tell and we don't have very much logging in place to help diagnose the problem.

Could you try hosting a server and then opening a new instance of OpenRCT2 and connecting to localhost?

**Comment by AnnaSaysHi** [comment]
I tried this and could connect to my own server.

**Comment by IntelOrca** [comment]
@AnnaSaysHi What version of RCT2 were you using when it crashed?

**Comment by AnnaSaysHi** [comment]
I was using the demo, downloaded off a site I don't remember. It also couldn't play scenarios that I downloaded off the internet.

**Comment by Gymnasiast** [comment]
@denosor I have a hunch... could you give a directory listing of the ObjData folder of your RCT2 installation?

**Comment by rwjuk** [comment]
We should probably throw a "you don't have <suchandsuch> object files" error in cases like this, rather than just crashing - assuming that is indeed the cause, which seems likely given how Anna's case was resolved.

**Comment by Gymnasiast** [comment]
@rwjuk. Indeed. Currently, the display of missing files is completely broken - it either does not display anything, or a completely unrelated error.

The reason I'm asking @denosor for a listing is to verify if missing files are the culprit in his/her case.

**Comment by rwjuk** [comment]
@Gymnasiast I think that should go on the list of things to fix up for 0.0.8 - happy to work on it.

**Comment by janisozaur** [comment]
Aren't there checks for missing files when we start up?

**Comment by Gymnasiast** [comment]
@janisozaur Only for g1.dat. It doesn't check for the 772 standard .DAT files. This allows OpenRCT2 to be used with the Mini Game, which lacks some .DAT files (I think 4X4.DAT is an example).

It would be better if OpenRCT2 would warn the user if it lacks some of the 772 standard files.

**Comment by denosor** [comment]
What is a directory listing? do you want me to send you the names of all of the files in that folder?

**Comment by Gymnasiast** [comment]
Yes, indeed.

**Comment by denosor** [comment]
[Direcory listing.txt](https://github.com/OpenRCT2/OpenRCT2/files/1020051/Direcory.listing.txt)

**Comment by janisozaur** [comment]
Can you post the whole output, though?

**Comment by denosor** [comment]
OK here it is: 
09/13/2002  02:51 AM            17,951 TH2.DAT
09/13/2002  02:51 AM           382,464 THCAR.DAT
09/13/2002  02:51 AM            23,389 THL.DAT
09/13/2002  02:51 AM             7,149 THRS.DAT
09/13/2002  02:51 AM             2,378 THT.DAT
09/13/2002  02:51 AM            16,288 TIC.DAT
09/13/2002  02:51 AM             4,847 TIG.DAT
09/13/2002  02:51 AM            14,096 TITC.DAT
09/13/2002  02:51 AM             3,538 TJB1.DAT
09/13/2002  02:51 AM             3,256 TJB2.DAT
09/13/2002  02:51 AM             5,082 TJB3.DAT
09/13/2002  02:51 AM             4,373 TJB4.DAT
09/13/2002  02:51 AM             4,073 TJF.DAT
09/13/2002  02:51 AM             8,685 TJP1.DAT
09/13/2002  02:51 AM             4,513 TJP2.DAT
09/13/2002  02:51 AM            17,847 TJT1.DAT
09/13/2002  02:51 AM            22,842 TJT2.DAT
09/13/2002  02:51 AM            11,888 TJT3.DAT
09/13/2002  02:51 AM            10,405 TJT4.DAT
09/13/2002  02:51 AM             8,974 TJT5.DAT
09/13/2002  02:51 AM             7,495 TJT6.DAT
09/13/2002  02:51 AM             2,539 TK1.DAT
09/13/2002  02:51 AM             2,617 TK2.DAT
09/13/2002  02:51 AM             2,780 TK3.DAT
09/13/2002  02:51 AM             2,833 TK4.DAT
09/13/2002  02:51 AM            20,148 TL0.DAT
09/13/2002  02:51 AM            23,596 TL1.DAT
09/13/2002  02:51 AM            20,114 TL2.DAT
09/13/2002  02:51 AM            23,036 TL3.DAT
09/13/2002  02:51 AM            12,105 TLC.DAT
09/13/2002  02:51 AM            10,502 TLP.DAT
09/13/2002  02:51 AM            26,541 TLT1.DAT
09/13/2002  02:51 AM            28,740 TLT2.DAT
09/13/2002  02:51 AM             1,452 TLY.DAT
09/13/2002  02:51 AM            12,716 TM0.DAT
09/13/2002  02:51 AM            14,325 TM1.DAT
09/13/2002  02:51 AM            16,187 TM2.DAT
09/13/2002  02:51 AM            12,711 TM3.DAT
09/13/2002  02:51 AM             7,884 TMBJ.DAT
09/13/2002  02:51 AM            20,722 TMC.DAT
09/13/2002  02:51 AM             8,257 TMG.DAT
09/13/2002  02:51 AM             5,385 TMJ.DAT
09/13/2002  02:51 AM             1,547 TML.DAT
09/13/2002  02:51 AM             7,963 TMM1.DAT
09/13/2002  02:51 AM             3,690 TMM2.DAT
09/13/2002  02:51 AM             2,349 TMM3.DAT
09/13/2002  02:51 AM             3,097 TMO1.DAT
09/13/2002  02:51 AM             5,452 TMO2.DAT
09/13/2002  02:51 AM             3,960 TMO3.DAT
09/13/2002  02:51 AM            20,513 TMO4.DAT
09/13/2002  02:51 AM             5,117 TMO5.DAT
09/13/2002  02:51 AM            19,139 TMP.DAT
09/13/2002  02:51 AM             5,325 TMS1.DAT
09/13/2002  02:51 AM             3,893 TMW.DAT
09/13/2002  02:51 AM            17,704 TMZP.DAT
09/13/2002  02:51 AM            18,303 TNS.DAT
09/13/2002  02:51 AM            18,539 TNSS.DAT
09/13/2002  02:51 AM             4,809 TNTROOF1.DAT
09/13/2002  02:51 AM            23,014 TOFFS.DAT
09/13/2002  02:51 AM         1,527,106 TOGST.DAT
09/13/2002  02:51 AM             8,118 TOH1.DAT
09/13/2002  02:51 AM            29,048 TOH2.DAT
09/13/2002  02:51 AM            12,842 TOH3.DAT
09/13/2002  02:51 AM           375,072 TOPSP1.DAT
09/13/2002  02:51 AM             3,485 TORN1.DAT
09/13/2002  02:51 AM             4,650 TORN2.DAT
09/13/2002  02:51 AM             1,927 TOS.DAT
09/13/2002  02:51 AM            11,909 TOT1.DAT
09/13/2002  02:51 AM             7,219 TOT2.DAT
09/13/2002  02:51 AM             2,753 TOT3.DAT
09/13/2002  02:51 AM             4,885 TOT4.DAT
09/13/2002  02:51 AM             6,874 TOTEM1.DAT
09/13/2002  02:51 AM             1,704 TP1.DAT
09/13/2002  02:51 AM             1,794 TP2.DAT
09/13/2002  02:51 AM             8,055 TPM.DAT
09/13/2002  02:51 AM             3,419 TQ1.DAT
09/13/2002  02:51 AM             3,731 TQ2.DAT
09/13/2002  02:51 AM            19,581 TQF.DAT
09/13/2002  02:51 AM             2,292 TR1.DAT
09/13/2002  02:51 AM             2,381 TR2.DAT
09/13/2002  02:51 AM           284,982 TRAM1.DAT
09/13/2002  02:51 AM             3,366 TRC.DAT
09/13/2002  02:51 AM            15,105 TRF.DAT
09/13/2002  02:51 AM            11,032 TRF2.DAT
09/13/2002  02:51 AM            11,128 TRF3.DAT
09/13/2002  02:51 AM            15,246 TRFS.DAT
09/13/2002  02:51 AM            40,618 TRIKE.DAT
09/13/2002  02:51 AM             8,332 TRMS.DAT
09/13/2002  02:51 AM             4,765 TROPT1.DAT
09/13/2002  02:51 AM            82,144 TRUCK1.DAT
09/13/2002  02:51 AM             7,599 TRWS.DAT
09/13/2002  02:51 AM             5,252 TS0.DAT
09/13/2002  02:51 AM             3,407 TS1.DAT
09/13/2002  02:51 AM             4,445 TS2.DAT
09/13/2002  02:51 AM             2,835 TS3.DAT
09/13/2002  02:51 AM             2,483 TS4.DAT
09/13/2002  02:51 AM             2,486 TS5.DAT
09/13/2002  02:51 AM             3,521 TS6.DAT
09/13/2002  02:51 AM            24,148 TSB.DAT
09/13/2002  02:51 AM             2,530 TSC.DAT
09/13/2002  02:51 AM             8,089 TSC2.DAT
09/13/2002  02:51 AM             8,398 TSCP.DAT
09/13/2002  02:51 AM             2,685 TSD.DAT
09/13/2002  02:51 AM             3,666 TSF1.DAT
09/13/2002  02:51 AM             3,748 TSF2.DAT
09/13/2002  02:51 AM             4,236 TSF3.DAT
09/13/2002  02:51 AM            19,904 TSG.DAT
09/13/2002  02:51 AM             6,605 TSH.DAT
09/13/2002  02:51 AM             2,427 TSH0.DAT
09/13/2002  02:51 AM             2,919 TSH1.DAT
09/13/2002  02:51 AM             1,852 TSH2.DAT
09/13/2002  02:51 AM             2,954 TSH3.DAT
09/13/2002  02:51 AM             2,847 TSH4.DAT
09/13/2002  02:51 AM             1,748 TSH5.DAT
09/13/2002  02:51 AM            25,608 TSHRT.DAT
09/13/2002  02:51 AM            36,658 TSK.DAT
09/13/2002  02:51 AM             7,572 TSM.DAT
09/13/2002  02:51 AM           138,472 TSMP.DAT
09/13/2002  02:51 AM             6,971 TSNB.DAT
09/13/2002  02:51 AM             9,863 TSNC.DAT
09/13/2002  02:51 AM            18,785 TSP.DAT
09/13/2002  02:51 AM             8,417 TSP1.DAT
09/13/2002  02:51 AM            11,541 TSP2.DAT
09/13/2002  02:51 AM             9,502 TSPH.DAT
09/13/2002  02:51 AM             4,451 TSQ.DAT
09/13/2002  02:51 AM             8,824 TST1.DAT
09/13/2002  02:51 AM             5,588 TST2.DAT
09/13/2002  02:51 AM             2,883 TST3.DAT
09/13/2002  02:51 AM             1,820 TST4.DAT
09/13/2002  02:51 AM             1,929 TST5.DAT
09/13/2002  02:51 AM             7,949 TSTD.DAT
09/13/2002  02:51 AM            14,005 TT1.DAT
09/13/2002  02:51 AM            27,083 TTF.DAT
09/13/2002  02:51 AM             1,815 TTG.DAT
09/13/2002  02:51 AM             7,157 TUS.DAT
09/13/2002  02:51 AM            12,705 TVL.DAT
09/13/2002  02:51 AM            16,501 TWF.DAT
09/13/2002  02:51 AM            11,215 TWH1.DAT
09/13/2002  02:51 AM            10,822 TWH2.DAT
09/13/2002  02:51 AM           148,773 TWIST1.DAT
09/13/2002  02:51 AM           169,347 TWIST2.DAT
09/13/2002  02:51 AM            15,416 TWN.DAT
09/13/2002  02:51 AM            12,940 TWP.DAT
09/13/2002  02:51 AM            17,073 TWW.DAT
09/13/2002  02:51 AM         1,099,573 UTCAR.DAT
09/13/2002  02:51 AM         1,099,757 UTCARR.DAT
09/13/2002  02:51 AM            95,730 VCR.DAT
09/13/2002  02:51 AM           762,401 VEKDV.DAT
09/13/2002  02:51 AM         1,163,938 VEKST.DAT
09/13/2002  02:51 AM         1,036,809 VEKVAMP.DAT
09/13/2002  02:51 AM            94,666 VREEL.DAT
09/13/2002  02:51 AM             7,075 WAG1.DAT
09/13/2002  02:51 AM             7,469 WAG2.DAT
09/13/2002  02:51 AM             2,565 WALLBADM.DAT
09/13/2002  02:51 AM             1,628 WALLBB16.DAT
09/13/2002  02:51 AM             2,881 WALLBB32.DAT
09/13/2002  02:51 AM             2,873 WALLBB33.DAT
09/13/2002  02:51 AM             2,922 WALLBB34.DAT
09/13/2002  02:51 AM             1,008 WALLBB8.DAT
09/13/2002  02:51 AM             1,271 WALLBR16.DAT
09/13/2002  02:51 AM             2,136 WALLBR32.DAT
09/13/2002  02:51 AM               843 WALLBR8.DAT
09/13/2002  02:51 AM            23,293 WALLBRDR.DAT
09/13/2002  02:51 AM             2,508 WALLBRWN.DAT
09/13/2002  02:51 AM             1,609 WALLCB16.DAT
09/13/2002  02:51 AM             2,843 WALLCB32.DAT
09/13/2002  02:51 AM               988 WALLCB8.DAT
09/13/2002  02:51 AM            24,889 WALLCBDR.DAT
09/13/2002  02:51 AM            24,763 WALLCBPC.DAT
09/13/2002  02:51 AM             2,811 WALLCBWN.DAT
09/13/2002  02:51 AM             1,499 WALLCF16.DAT
09/13/2002  02:51 AM             2,608 WALLCF32.DAT
09/13/2002  02:51 AM               955 WALLCF8.DAT
09/13/2002  02:51 AM             2,106 WALLCFAR.DAT
09/13/2002  02:51 AM            24,639 WALLCFDR.DAT
09/13/2002  02:51 AM            24,483 WALLCFPC.DAT
09/13/2002  02:51 AM             2,737 WALLCFWN.DAT
09/13/2002  02:51 AM             3,210 WALLCO16.DAT
09/13/2002  02:51 AM             2,663 WALLCW32.DAT
09/13/2002  02:51 AM             2,708 WALLCX32.DAT
09/13/2002  02:51 AM             2,891 WALLCY32.DAT
09/13/2002  02:51 AM             2,780 WALLCZ32.DAT
09/13/2002  02:51 AM             3,308 WALLGL16.DAT
09/13/2002  02:51 AM             4,946 WALLGL32.DAT
09/13/2002  02:51 AM             2,483 WALLGL8.DAT
09/13/2002  02:51 AM             1,659 WALLIG16.DAT
09/13/2002  02:51 AM             2,055 WALLIG24.DAT
09/13/2002  02:51 AM             4,825 WALLJB16.DAT
09/13/2002  02:51 AM             2,132 WALLJN32.DAT
09/13/2002  02:51 AM             2,045 WALLLT32.DAT
09/13/2002  02:51 AM             2,077 WALLMM16.DAT
09/13/2002  02:51 AM             2,215 WALLMM17.DAT
09/13/2002  02:51 AM             2,341 WALLMN32.DAT
09/13/2002  02:51 AM             1,908 WALLNT32.DAT
09/13/2002  02:51 AM             2,186 WALLNT33.DAT
09/13/2002  02:51 AM             2,628 WALLPG32.DAT
09/13/2002  02:51 AM             1,468 WALLPOST.DAT
09/13/2002  02:51 AM             3,265 WALLPR32.DAT
09/13/2002  02:51 AM             3,057 WALLPR33.DAT
09/13/2002  02:51 AM             3,079 WALLPR34.DAT
09/13/2002  02:51 AM             1,802 WALLPR35.DAT
09/13/2002  02:51 AM             2,035 WALLRH32.DAT
09/13/2002  02:51 AM             2,866 WALLRK32.DAT
09/13/2002  02:51 AM             1,607 WALLRS16.DAT
09/13/2002  02:51 AM             2,848 WALLRS32.DAT
09/13/2002  02:51 AM               993 WALLRS8.DAT
09/13/2002  02:51 AM             5,437 WALLSC16.DAT
09/13/2002  02:51 AM             2,054 wallsign.dat
09/13/2002  02:51 AM             1,613 WALLSK16.DAT
09/13/2002  02:51 AM             2,457 WALLSK32.DAT
09/13/2002  02:51 AM             2,637 WALLSP32.DAT
09/13/2002  02:51 AM             1,330 WALLST16.DAT
09/13/2002  02:51 AM             2,052 WALLST32.DAT
09/13/2002  02:51 AM             1,030 WALLST8.DAT
09/13/2002  02:51 AM             1,670 WALLSTFN.DAT
09/13/2002  02:51 AM             1,417 WALLSTWN.DAT
09/13/2002  02:51 AM             1,263 WALLTN32.DAT
09/13/2002  02:51 AM             3,990 WALLTXGT.DAT
09/13/2002  02:51 AM             2,898 WALLU132.DAT
09/13/2002  02:51 AM             2,879 WALLU232.DAT
09/13/2002  02:51 AM             1,740 WALLWD16.DAT
09/13/2002  02:51 AM             3,027 WALLWD32.DAT
09/13/2002  02:51 AM             3,000 WALLWD33.DAT
09/13/2002  02:51 AM             1,104 WALLWD8.DAT
09/13/2002  02:51 AM             2,238 WALLWDPS.DAT
09/13/2002  02:51 AM            21,367 WALLWF32.DAT
09/13/2002  02:51 AM            11,348 WASP.DAT
09/13/2002  02:51 AM             5,868 WBR1.DAT
09/13/2002  02:51 AM             2,523 WBR1A.DAT
09/13/2002  02:51 AM             4,557 WBR2.DAT
09/13/2002  02:51 AM             1,688 WBR2A.DAT
09/13/2002  02:51 AM             1,702 WBR3.DAT
09/13/2002  02:51 AM             2,274 WBRG.DAT
09/13/2002  02:51 AM             4,152 WBW.DAT
09/13/2002  02:51 AM             5,690 WC1.DAT
09/13/2002  02:51 AM            16,293 WC10.DAT
09/13/2002  02:51 AM            16,641 WC11.DAT
09/13/2002  02:51 AM            16,082 WC12.DAT
09/13/2002  02:51 AM             8,617 WC13.DAT
09/13/2002  02:51 AM             5,915 WC14.DAT
09/13/2002  02:51 AM             2,326 WC15.DAT
09/13/2002  02:51 AM             2,047 WC16.DAT
09/13/2002  02:51 AM             4,938 WC17.DAT
09/13/2002  02:51 AM             5,374 WC18.DAT
09/13/2002  02:51 AM             5,344 WC2.DAT
09/13/2002  02:51 AM            15,389 WC3.DAT
09/13/2002  02:51 AM            17,184 WC4.DAT
09/13/2002  02:51 AM            17,199 WC5.DAT
09/13/2002  02:51 AM            17,220 WC6.DAT
09/13/2002  02:51 AM            16,897 WC7.DAT
09/13/2002  02:51 AM             9,471 WC8.DAT
09/13/2002  02:51 AM            16,186 WC9.DAT
09/13/2002  02:51 AM           656,800 WCATC.DAT
09/13/2002  02:51 AM             6,033 WCH.DAT
09/13/2002  02:51 AM             1,839 WCHG.DAT
09/13/2002  02:51 AM             8,508 WCW1.DAT
09/13/2002  02:51 AM             7,077 WCW2.DAT
09/13/2002  02:51 AM             7,349 WDBASE.DAT
09/13/2002  02:51 AM            22,508 WDIAG.DAT
09/13/2002  02:51 AM             5,327 WEW.DAT
09/13/2002  02:51 AM             4,732 WFW1.DAT
09/13/2002  02:51 AM             1,722 WFWG.DAT
09/13/2002  02:51 AM             5,156 WGW2.DAT
09/13/2002  02:51 AM             4,694 WHG.DAT
09/13/2002  02:51 AM             1,559 WHGG.DAT
09/13/2002  02:51 AM            10,095 WHORIZ.DAT
09/13/2002  02:51 AM             4,403 WJF.DAT
09/13/2002  02:51 AM             4,011 WMF.DAT
09/13/2002  02:51 AM             1,585 WMFG.DAT
09/13/2002  02:51 AM           384,616 WMMINE.DAT
09/13/2002  02:51 AM           329,449 WMOUSE.DAT
09/13/2002  02:51 AM         1,635,617 WMSPIN.DAT
09/13/2002  02:51 AM             7,417 WMW.DAT
09/13/2002  02:51 AM             6,657 WMWW.DAT
09/13/2002  02:51 AM            26,437 WONTON.DAT
09/13/2002  02:51 AM             1,928 WPF.DAT
09/13/2002  02:51 AM               784 WPFG.DAT
09/13/2002  02:51 AM             6,136 WPW1.DAT
09/13/2002  02:51 AM             5,188 WPW2.DAT
09/13/2002  02:51 AM             6,536 WPW3.DAT
09/13/2002  02:51 AM             5,387 WRW.DAT
09/13/2002  02:51 AM             2,526 WRWA.DAT
09/13/2002  02:51 AM           261,505 WSPOUT.DAT
09/13/2002  02:51 AM             4,013 WSW.DAT
09/13/2002  02:51 AM             4,096 WSW1.DAT
09/13/2002  02:51 AM             1,575 WSW2.DAT
09/13/2002  02:51 AM             1,579 WSWG.DAT
09/13/2002  02:51 AM             1,383 WTRCYAN.DAT
09/13/2002  02:51 AM             1,409 WTRGREEN.DAT
09/13/2002  02:51 AM             1,330 WTRGRN.DAT
09/13/2002  02:51 AM             1,350 WTRORNG.DAT
09/13/2002  02:51 AM            47,802 WWBANK.DAT
09/13/2002  02:51 AM            10,148 WWTW.DAT
09/13/2002  02:51 AM             3,069 WWTWA.DAT
09/13/2002  02:51 AM           500,099 ZLDB.DAT
09/13/2002  02:51 AM           489,374 ZLOG.DAT
             772 File(s)     73,927,743 bytes
               2 Dir(s)  158,197,743,616 bytes free

C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2\ObjData>

**Comment by janisozaur** [comment]
Can you post the whole output, though?

> 772 File(s) 73,927,743 bytes

```
$ wc -l ~/Downloads/Direcory.listing.txt 
299 /home/janisozaur/Downloads/Direcory.listing.txt
```

**Comment by Gymnasiast** [comment]
It appears as if you only have the base game, not the WW and TT expansions. Is there an open server that does not use WW or TT, so we can check whether that's the issue?

**Comment by denosor** [comment]
what does WW or TT stand for?

**Comment by Gymnasiast** [comment]
Wacky World and Time Twister. Both are expansion packs for RollerCoaster Tycoon 2.
