### ISSUE TITLE
RCT1 path check is case-sensitive on Linux

### ISSUE THREAD

**Issue by rwjuk** [OpenRCT2/OpenRCT2#5507]
**OS:** Linux
**Version:** 0.0.8
**Commit/Build:** latest

The check for `csg1.1` and `csg1.dat` on setting an RCT1 path is case sensitive - lower case works, upper case does not.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Clear your RCT1 path if set.
2. Rename `csg1.dat` to `CSG1.DAT`.
3. Try to set the RCT1 path again.
4. OpenRCT2 says the directory is invalid.

EDIT: This bug does **not** occur on macOS.

**Comment by rwjuk** [comment]
@PFCKrutonium ran into this, testing on Gitter confirmed this bug

**Comment by PureTryOut** [comment]
So this is what prevents me from using my RCT1 installation! Thanks for reporting it, hoping to see this fixed soon.

**Comment by rwjuk** [comment]
@PureTryOut As a workaround until then, you can change the case of CSG1.DAT to csg1.dat - that'll get it working.

**Comment by PFCKrutonium** [comment]
The RCT2 music css50.dat is also case sensitive, I ran into this when replacing my title music with music from Planet Coaster.

**Comment by PFCKrutonium** [comment]
Upon further poking, it seems that because of the case sensitivity, except for loading scenarios, it breaks RCT1 import, in that it cant load sprites, music (where applicable) etc, because the casing is incorrect.
