### ISSUE TITLE
Crash when trying to build Junior Roller Coaster

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#5509]
OS: Windows 7
Version: 0.0.8
Commit/Build: 2f9f613

OpenRCT2 crashes when trying to build a Junior Roller Coaster

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

Steps to reproduce:
1. Open the Gravity Gardens scenario
2. Place your mouse over the Junior Roller Coaster picture in the new ride menu

Dump file: (This is a .gz archive because for some reason .zip was not working)
[9dcf0a79-a03f-40cb-ba2e-40d5b29a7453.dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/1030307/9dcf0a79-a03f-40cb-ba2e-40d5b29a7453.dmp.gz)

**Comment by rwjuk** [comment]
Doesn't occur for me on macOS 10.12 with that scenario.

**Comment by SidaRadis** [comment]
After a bit of testing, I think I have found what was causing the crash. I figured it was probably due to some of my downloaded custom tracks so I removed them using vanilla but OpenRCT2 kept crashing. I also tried with the latest stable version and noticed a few new tracks suddenly appeared (they did not appear in vanilla). It was only after I removed these tracks that the crashing stopped. The same behaviour seems to happen with the Mini Roller Coaster but it does not crash the game.

**Comment by rwjuk** [comment]
Could you upload one or two of the tracks that you think caused the issue so we can figure out what's causing it?

**Comment by SidaRadis** [comment]
(Remove the .txt)
[Choo Choo JrRollerCoaster PnkFloyd12.TD6.txt](https://github.com/OpenRCT2/OpenRCT2/files/1032808/Choo.Choo.JrRollerCoaster.PnkFloyd12.TD6.txt)
[KK2MarshmallowMayhemReddBaron.TD6.txt](https://github.com/OpenRCT2/OpenRCT2/files/1032809/KK2MarshmallowMayhemReddBaron.TD6.txt)
[Teddy Terror - Spunknit.TD6.txt](https://github.com/OpenRCT2/OpenRCT2/files/1032810/Teddy.Terror.-.Spunknit.TD6.txt)

**Comment by jensj12** [comment]
These files don't seem to be any different than the UCES tracks I have. No crashes for me. Win10 - dabaddd

**Comment by SidaRadis** [comment]
These files most certainly come from the UCES pack. It might be a custom scenery/vehicle issue because I just noticed my OpenRCT2 object folder is empty.

**Comment by rwjuk** [comment]
@SidaRadis Could you ZIP the TD6s and re-upload? Just in case saving them as text files has messed with the encoding.

**Comment by SidaRadis** [comment]
Github refuses to let me attach a .zip, would .gz be acceptable?

**Comment by rwjuk** [comment]
@SidaRadis Absolutely :)

**Comment by SidaRadis** [comment]
[Choo Choo JrRollerCoaster PnkFloyd12.TD6.gz](https://github.com/OpenRCT2/OpenRCT2/files/1033073/Choo.Choo.JrRollerCoaster.PnkFloyd12.TD6.gz)
[KK2MarshmallowMayhemReddBaron.TD6.gz](https://github.com/OpenRCT2/OpenRCT2/files/1033072/KK2MarshmallowMayhemReddBaron.TD6.gz)
[Teddy Terror - Spunknit.TD6.gz](https://github.com/OpenRCT2/OpenRCT2/files/1033071/Teddy.Terror.-.Spunknit.TD6.gz)

**Comment by rwjuk** [comment]
Hmm... none of those cause issues for me (macOS 10.12, latest build). I'll see if I can get some more eyes on this.

**Comment by SidaRadis** [comment]
One month later, this somehow seems this be fixed. I tried it this morning and no crash occurred.
I have a quick question while I'm here: Is the ability to build steep inclines on Junior Roller Coasters intended? I don't remember it being possible in vanilla (Select rides by track type is unchecked)

**Comment by Patrik356b** [comment]
@Gymnasiast would probably know

**Comment by Gymnasiast** [comment]
It's not possible in vanilla, and in OpenRCT2 only when importing or when using a vehicle capable of drawing them.
