### ISSUE TITLE
Suggestion: Quick reconnect button for multiplayer

### ISSUE THREAD

**Issue by hypocube** [OpenRCT2/OpenRCT2#5512]
Recently a friend and I have had an issue with desynchronizations in multiplayer, so we came up with an idea of a "Quick reconnect" button in the multiplayer menu that would simply refresh the connection with the server. Otherwise we would have to re-enter the IP every time (because we were doing a LAN thing and not a public server).

Thanks for reading, I hope I put this in the right place.

**Comment by Gymnasiast** [comment]
I think this was suggested before, but discouraged because it increases load on the server. (Of course, for a LAN server this would not apply as much.)

Thing is that we'd much prefer to work on actually getting rid of the desyncs, rather than working around it.

**Comment by janisozaur** [comment]
I think there is some merit to this request: rather than having a "resync" button (to which I'm very much against), we could store the last entered server information so that user doesn't have to re-enter it when he opens "multiplayer" window. Especially when the program has not been restarted.

**Comment by hypocube** [comment]
Thanks for replying. I get what you mean about desyncs, so janisozaur's idea would be work perfectly. Our idea really just boils down to having something to make reconnecting to the same server more convenient. 

Thank you for making RCT2 multiplayer a reality.

**Comment by Nubbie** [comment]
Mentioned in #3134 and suggested at #2695 (closed) - A idea like Janisozaur would work better then avoiding the problem
