### ISSUE TITLE
Game Crashes When Trying to Open Ride Creator on any downloaded scenario.

### ISSUE THREAD

**Issue by stewtf2** [OpenRCT2/OpenRCT2#5514]
**OS:** [ Windows 10]
**Version:** [0.0.6 x64]
**Commit/Build:** [493bb62]

When ever I try to open up the ride creator on a custom downloaded scenario, the game crashes.
 no problems on vanilla rct2 scenarios.
I can't even join multiplayer servers.
**# EDIT: HEY, BIG NEWS, JUST FOUND OUT IT HAPPENS ON RANDOM SCENARIOS. I TRIED IT ON ELECTRIC FIELDS AND IT HAPPENED THERE TOO.**

**Steps to reproduce:**
1. Open up a custom Scenario
2. Open Ride Creator
3. Error Sound
4. Error Message
5. Cry

It failed to create a dump file. (According to the error message)

Video: https://youtu.be/KcXGvVQlOiU

**Comment by Gymnasiast** [comment]
"This video is private."

**Comment by rwjuk** [comment]
The video now works. Could you upload one of the scenarios where this bug occurs (you'll need to ZIP the file so that Github accepts it).

Also, once the game has crashed, please follow these instructions to create a dump file, and upload that too: https://support.kaspersky.co.uk/general/dumps/8158

**Comment by Nubbie** [comment]
The video is down and OP seem to be gone

**Comment by Gymnasiast** [comment]
Closed this due to the video being down and the OP not responding.

@stewtf2 Feel free to comment if you're still around and have put the video up again.
