### ISSUE TITLE
Missing Wooden Wild Mine Ride

### ISSUE THREAD

**Issue by RogoDarius** [OpenRCT2/OpenRCT2#5515]
**OS:** Windows 10
**Version:** 0.0.8
**Commit/Build:** eaf9343

While playing Sprightly Park, (Added Attractions) I received a notification that I'd researched a new ride, "Wooden Wild Mine Ride". But when clicking the blue icon or navigating to New Roller Coasters there is no such ride available.

- [X] Reproducible in RCT2 (vanilla)?
- [X] Multiplayer?

**Screenshots / Video:**
![sprightly park](https://cloud.githubusercontent.com/assets/12530301/26543212/e3ab6340-4454-11e7-839a-ebbf460e640e.PNG)

**Save game:**
[Sprightly ParkB.zip](https://github.com/OpenRCT2/OpenRCT2/files/1035335/Sprightly.ParkB.zip)

**Comment by Gymnasiast** [comment]
You most likely have 'Sort rides by track type' on. Try building a wooden wild mouse and switch the vehicle type to 'Wooden Wild Mine Ride'.

**Comment by RogoDarius** [comment]
Right, yes it is that.
Not confusing at all. ;)

**Comment by Gymnasiast** [comment]
I know I know, I'm addressing it in #5504 ;-)
