### ISSUE TITLE
edge scroll trouble on 0.0.8 - 26196c6 

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#5518]
not sure if duplicate, this was happening when i tested for #4142 on Win8.1x64
[toyboxpark.zip](https://github.com/OpenRCT2/OpenRCT2/files/1041401/toyboxpark.zip)

zip file has sv6 which was created just now from the scenario editor, a video and a single custom object fron UCES

**Comment by IntelOrca** [comment]
We already have several issues for broken scrolling, e.g. #2589

**Comment by Patrik356b** [comment]
Posted in a rush, but okay

**Comment by IntelOrca** [comment]
#5383 aims to fix it, although it doesn't look like the PR will be finished.
