### ISSUE TITLE
Refactor platform_directory_delete() to remove FTS dependency

### ISSUE THREAD

**Issue by rwjuk** [OpenRCT2/OpenRCT2#5520]
`fts.h` is included, and FTS used, for `platform_directory_delete()` on POSIX systems.

This function is only called from `DeleteItem()` in `TitleSequenceManager.cpp` - the function that deletes title sequences.

Including FTS for one very infrequently called function is inefficient - `platform_directory_delete()` should be rewritten to avoid using it.

**Comment by janisozaur** [comment]
See also: http://wiki.musl-libc.org/wiki/FAQ#Q:_why_is_fts.h_not_included_.3F
