### ISSUE TITLE
Infinite loop on first run if neither Zenity nor kdialog are installed

### ISSUE THREAD

**Issue by rwjuk** [OpenRCT2/OpenRCT2#5521]
If OpenRCT2 is run on a system without Zenity or kdialog, the 'choose directory' function that is called on startup to allow setting of the RCT2 path ends up in an infinite loop.

Found by @PFCKrutonium while testing with musl on Alpine linux.

**Comment by PFCKrutonium** [comment]
It also doesn't let you leave the loop if you have them installed, but click cancel...?
