### ISSUE TITLE
Choppy framerate

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#5533]
Windows 8
v0.0.8 9b041e0

The game is very choppy at the moment, heard report from others too. It's like being in multiplayer where the game seems constantly accelerate and decelerate, but in single player.

**Comment by PFCKrutonium** [comment]
Can you record a video to show us what you mean?

**Comment by Gymnasiast** [comment]
Does it say "DEBUG" in the title screen?

**Comment by Liampie** [comment]
Nope. But it seems the problem has vanished as quickly as it appeared. Weird stuff.

For the future, PFC, what is the best way to record a video?

**Comment by Patrik356b** [comment]
I would highly recommend https://obsproject.com/download
