### ISSUE TITLE
Unable to select any full screen resolutions

### ISSUE THREAD

**Issue by DCMeGaMaxX** [OpenRCT2/OpenRCT2#5534]
**OS:** Windows 10 Version 1703
**Version:** 0.0.8
**Commit/Build:** 9b041e0

This bug prevents the resolution from being changed in fullscreen mode. Using windowed mode or fullscreen borderless works fine, Screenshot below shows the resolution dropdown menu being selected, but nothing is happening.

**Screenshots / Video:**

![diamond heights 2017-06-01 23-36-15](https://cloud.githubusercontent.com/assets/16751824/26711014/36e735c2-4723-11e7-8a5f-d67c21bf2edf.png)

**Comment by Patrik356b** [comment]
Does it save and work on restart?

**Comment by telk5093** [comment]
Same as me.
