### ISSUE TITLE
SDL_Init(SDL_INIT_VIDEO) is called even when using --headless option

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#5537]
**Commit/Build:** 79d76759bb3c1979e8935272d6624a0a4e278ebd

https://github.com/OpenRCT2/OpenRCT2/blob/79d76759bb3c1979e8935272d6624a0a4e278ebd/src/openrct2-ui/UiContext.cpp#L90

`SDL_Init(SDL_INIT_VIDEO)` is called regardless of `--headless` switch.

**Comment by IntelOrca** [comment]
I would like to make the code path as similar as possible as openrct2-cli for headless flag. It will require parsing the command line arguments before creating the OpenRCT2 context.
