### ISSUE TITLE
fatal error: too many errors emitted.

### ISSUE THREAD

**Issue by iezed** [OpenRCT2/OpenRCT2#5541]
**OS:** [OSX 10.10.5]
**Version:** [0.0.8]
**Commit/Build:** [9bd4284]

Hi, I have this error when try to build : 
/usr/local/include/SDL2/SDL_platform.h:73:5: error: 'TARGET_OS_TV' is not defined, evaluates to 0 [-Werror,-Wundef]
#if TARGET_OS_TV
    ^
In file included from /Users/fabrizio/github/games/OpenRCT2/src/openrct2/cheats.c:17:
In file included from /Users/fabrizio/github/games/OpenRCT2/src/openrct2/cheats.h:20:
/Users/fabrizio/github/games/OpenRCT2/src/openrct2/common.h:294:1: error: expected parameter declarator
assert_struct_size(registers, 7 * 4);
^
/Users/fabrizio/github/games/OpenRCT2/src/openrct2/common.h:227:48: note: expanded from macro 'assert_struct_size'
#define assert_struct_size(x, y) static_assert(sizeof(x) == (y), "Improper struct size")
....
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
Thanks.

**Comment by janisozaur** [comment]
Looks like your compiler is​ too old. The other issue is a problem with your SDL2. Again, it might be too old. Can you provide versions of both of them?

**Comment by iezed** [comment]
I have sdl2: stable 2.0.5 installed via homebrew and 
gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)

**Comment by janisozaur** [comment]
We explicitly [request C11 from the compiler](https://github.com/OpenRCT2/OpenRCT2/blob/develop/OpenRCT2.xcodeproj/project.pbxproj#L3511), but apple being themselves, [lie about C11 support](https://forums.developer.apple.com/thread/15070). You can try working around this by either using older-but-likely-supported `_Static_assert` instead of the C11 version in `common.h`, or just completely forgoing it, as we have upstream checks that verify this integrity. The proper solution would be migrating to conformant compiler.

The other error, with SDL2, I can provide workaround for, but ideally should be solved upstream.

**Comment by iezed** [comment]
Thanks, I will try to use homebrew GCC instead.

**Comment by AaronVanGeffen** [comment]
While using a more recent GCC from Homebrew will probably solve this for you, I am curious: why are you still on OS X 10.10? It no longer gets security patches and the like from Apple.

You should be able to upgrade to 10.11 on all hardware, which already offers an updated toolchain, if you cannot upgrade to 10.12 for whatever reason.

**Comment by iezed** [comment]
I have just mobile connection, the update it's to big. :(

**Comment by janisozaur** [comment]
@iezed can you please check #5549 for us, if it generates any warnings with xcode 7?

**Comment by iezed** [comment]
With xcode project I have this error : 

Ld /Users/fabrizio/Library/Developer/Xcode/DerivedData/OpenRCT2-epbanyvebcmsrxdbyuzoabksynnx/Build/Products/Debug/OpenRCT2.app/Contents/MacOS/OpenRCT2 normal x86_64
    cd /Users/fabrizio/github/games/OpenRCT2-develop
    export MACOSX_DEPLOYMENT_TARGET=10.8
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -L/Users/fabrizio/Library/Developer/Xcode/DerivedData/OpenRCT2-epbanyvebcmsrxdbyuzoabksynnx/Build/Products/Debug -L/Users/fabrizio/github/games/OpenRCT2-develop/libxc/lib -F/Users/fabrizio/Library/Developer/Xcode/DerivedData/OpenRCT2-epbanyvebcmsrxdbyuzoabksynnx/Build/Products/Debug -filelist /Users/fabrizio/Library/Developer/Xcode/DerivedData/OpenRCT2-epbanyvebcmsrxdbyuzoabksynnx/Build/Intermediates/OpenRCT2.build/Debug/OpenRCT2.build/Objects-normal/x86_64/OpenRCT2.LinkFileList -Xlinker -no_pie -Xlinker -rpath -Xlinker @executable_path/../Frameworks -mmacosx-version-min=10.8 -stdlib=libc++ -fobjc-link-runtime -lopenrct2 -lz -lcurl -liconv -lcrypto -ljansson -lpng16 -lSDL2 -lSDL2_ttf -lspeexdsp -lzip -Xlinker -dependency_info -Xlinker /Users/fabrizio/Library/Developer/Xcode/DerivedData/OpenRCT2-epbanyvebcmsrxdbyuzoabksynnx/Build/Intermediates/OpenRCT2.build/Debug/OpenRCT2.build/Objects-normal/x86_64/OpenRCT2_dependency_info.dat -o /Users/fabrizio/Library/Developer/Xcode/DerivedData/OpenRCT2-epbanyvebcmsrxdbyuzoabksynnx/Build/Products/Debug/OpenRCT2.app/Contents/MacOS/OpenRCT2

Undefined symbols for architecture x86_64:
  "_CTFontDescriptorCopyAttribute", referenced from:
      _platform_get_font_path in libopenrct2.a(macos.o)
  "_CTFontDescriptorCreateWithNameAndSize", referenced from:
      _platform_get_font_path in libopenrct2.a(macos.o)
  "_OBJC_CLASS_$_NSAlert", referenced from:
      objc-class-ref in UiContext.macOS.o
      objc-class-ref in libopenrct2.a(macos.o)
  "_OBJC_CLASS_$_NSOpenPanel", referenced from:
      objc-class-ref in UiContext.macOS.o
  "_OBJC_CLASS_$_NSSavePanel", referenced from:
      objc-class-ref in UiContext.macOS.o
  "_OBJC_CLASS_$_NSWindow", referenced from:
      objc-class-ref in UiContext.macOS.o
      objc-class-ref in libopenrct2.a(macos.o)
  "_kCTFontURLAttribute", referenced from:
      _platform_get_font_path in libopenrct2.a(macos.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Gymnasiast** [comment]
Have you loaded the code from #5549 into your Xcode 7?

**Comment by iezed** [comment]
With the code from rwjuk:push/xcodev8, I have this error : 
Failed to load project at '/Users/fabrizio/github/games/OpenRCT2/OpenRCT2-push-xcodev8/OpenRCT2.xcodeproj', incompatible project version.

**Comment by janisozaur** [comment]
ah, great!

**Comment by Gymnasiast** [comment]
Ok, we have now merged #5549. This does not fix compilation on Xcode 7, as that requires more effort than we are willing to take. But at least you now get a warning that it is unsupported in Xcode 7, rather than happily loading but failing to compile.
