### ISSUE TITLE
platform_get_locale_date_format is not implemented for Linux.

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#5548]
`platform_get_locale_date_format` is not implemented for Linux.

I did try to write an implementation using `std::locale` and `date_order`, but I could not get it to pick up the system locale or anything from the `LANG` or `LC_*` environment variables without throwing runtime exceptions.

**Comment by SijmenSchoon** [comment]
I just looked into this, also with std::locale, but this does not seem to be implemented yet. Looking at the documentation of std::locale, this is said about date_order:

```
       *  NOTE: The library always returns noorder at the moment.
```

I honestly don't expect this to be implemented anytime soon.
