### ISSUE TITLE
ride_ratings_test should be run on CIs

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#5552]
**Commit/Build:** bd20c92

[Ride ratings test](https://github.com/OpenRCT2/OpenRCT2/pull/5047) has recently been merged, but disabled for CI as requiring the assets to be present.

It is a valuable test to prove we didn't accidentally change some logic and it would be best if we could have it running on Travis (or AppVeyor).

**Comment by IntelOrca** [comment]
They are now run on CI.
