### ISSUE TITLE
Can't hire staff - randomly named guest appears instead who can't be sacked.

### ISSUE THREAD

**Issue by davewthompson** [OpenRCT2/OpenRCT2#5558]
**Windows 10**
**v0.0.8-develop**
**f3b4c88**

Adding a new staff member - handyman or mechanic - in a new game doesn't work; a random guest window appears with a random name and this new entity cannot be sacked.

- [N] Reproducible in RCT2 (vanilla)?
- [N] Multiplayer?

**Steps to reproduce:**
1. Create a new game.
2. Try and hire a staff member.

**Comment by IntelOrca** [comment]
Caused by #5295
