### ISSUE TITLE
Crash when opening Wooden Roller Coaster Tab

### ISSUE THREAD

**Issue by UnsaltedCashews** [OpenRCT2/OpenRCT2#5559]
**OS:** Windows 10
**Version:**  0.0.8
**Commit/Build:** f3b4c88

When I attempt to open the menu for building wooden roller coasters the game hangs for a couple of seconds then crashes with no dump file. This happens in any scenario and inside the track design manager and roller coaster designer.

Edit: I'm not sure how to submit a dump, I had to manually create one through task manager and after compressing it, its still too big to submit (65,454 KB)

Reproducible in RCT2 (vanilla)? No
 Multiplayer? Probably

**Steps to reproduce:**
1.  Open Ride Menu
2.  Select Wooden Roller Coaster tab
3. Game Crash

**Comment by IntelOrca** [comment]
If its just wooden roller coasters, it may related to your track designs. Do you have a lot of custom track designs? Can you try temporarily removing them and see if it still crashes?

Your track designs are located in either your RCT2 install directory under `Tracks`, or your user directory (`Documents/OpenRCT2/tracks`)

**Comment by UnsaltedCashews** [comment]
You know, I did download a lot of track packs, but that was awhile back. As
far as I know, there is nothing custom. As for removing them, there's
probably over 300 prebuilt wooden roller coaster designs (Which are all
located in the RCT2 directory, all sorted alphabetically in a nice long
list along with every other track design) that I have so... yeah
 I did start having issues last week which is the weird thing, before that
everything was fine.

Actually now that I think about it, I did download a 64 bit build and then
reverted back to the 32 bit, and that's when I started having problems. The
other thing too is that it only happens on the computer which I installed
the 64 bit version.

**Comment by hypocube** [comment]
I'm having the same issue. I have all the original wooden coaster designs plus maybe 10 more. I haven't done any reverting versions, though.

I removed all my tracks and accidentally clicked on the American Railroad, which led me to finding out that ALL rides produce this error. Even flatrides.

**Comment by IntelOrca** [comment]
@hypocube I have just fixed this now, this appeared to be a regression from a very recent change.

**Comment by rwjuk** [comment]
Closing, fixed in 2501df6

**Comment by UnsaltedCashews** [comment]
Awesome thanks!

**Comment by IntelOrca** [comment]
I feel like the regression I fixed was added after the original post. Re-open this issue if the bug still occurs.

**Comment by janisozaur** [comment]
I'm going to re-open it, as f3b4c88 predates what was to be the regression cause.

**Comment by UnsaltedCashews** [comment]
Well I went back to check if things were fixed, and now I realize that I have the same issue as hypocube :(

**Comment by UnsaltedCashews** [comment]
I have a dump file now, take a look!
[Dump.zip](https://github.com/OpenRCT2/OpenRCT2/files/1066772/Dump.zip)

**Comment by janisozaur** [comment]
That dump comes from a626a4a, a build more than half a year old. It's not worth even opening.

**Comment by UnsaltedCashews** [comment]
...
Oops wrong dump file :/

**Comment by UnsaltedCashews** [comment]
Okay here is the CORRECT dump file
[Dump2.zip](https://github.com/OpenRCT2/OpenRCT2/files/1068616/Dump2.zip)

**Comment by Nubbie** [comment]
**Error message;**
Unhandled exception thrown: read access violation.
ori was nullptr.

**Call stack;**
```
>	openrct2.dll!TrackDesignRepository::GetCountForObjectEntry(unsigned char rideType='4', const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & entry={...}) Line 119	C++
 	openrct2.dll!get_num_track_designs(ride_list_item item={...}) Line 861	C
 	openrct2.dll!window_new_ride_paint_ride_information(rct_window * dpi=0x007df8e0, rct_drawpixelinfo * item={...}, ride_list_item x=3, int y=348, int width=595, int) Line 892	C
 	openrct2.dll!window_new_ride_paint(rct_window * w=0x708f9950, rct_drawpixelinfo * dpi=0x007df8e0) Line 768	C
 	openrct2.dll!window_draw_single(rct_drawpixelinfo * dpi, rct_window * w=0x708f9950, int left=0, int top=0, int right=640, int bottom=576) Line 1727	C
 	openrct2.dll!window_draw(rct_drawpixelinfo * dpi=0x007df940, rct_window * w=0x708f9480, int left=0, int top=0, int right=640, int bottom=576) Line 1623	C
 	openrct2.dll!window_draw_all(rct_drawpixelinfo * dpi, short left=0, short top, short right, short bottom=576) Line 579	C
 	openrct2.dll!OpenRCT2::Drawing::X8DrawingEngine::DrawDirtyBlocks(unsigned int x, unsigned int y=0, unsigned int columns=5, unsigned int rows=9) Line 467	C++
 	openrct2.dll!OpenRCT2::Drawing::X8DrawingEngine::DrawAllDirtyBlocks() Line 436	C++
 	openrct2.dll!OpenRCT2::Drawing::X8DrawingEngine::Draw() Line 228	C++
 	openrct2.dll!SoftwareDrawingEngine::Draw() Line 110	C++
 	openrct2.dll!OpenRCT2::Context::RunVariableFrame() Line 431	C++
 	openrct2.dll!OpenRCT2::Context::RunGameLoop() Line 354	C++
 	openrct2.dll!OpenRCT2::Context::Launch() Line 339	C++
 	openrct2.dll!OpenRCT2::Context::RunOpenRCT2(int argc=3292616, char * * argv=0x00323dd0) Line 136	C++
 	openrct2.dll!NormalisedMain(int argc=1, char * * argv=0x00d322f8) Line 60	C++
 	openrct2.dll!LaunchOpenRCT2(int argc=1, wchar_t * * argvW=0x00d1d350) Line 52	C++
 	openrct2.exe!wmain(int argc=1, wchar_t * * argvW=0x00d1d350, wchar_t * envp=0x00d1f7c8) Line 32	C++
 	[External Code]	
```

**Autos;**
```
-		entry	""	const std::basic_string<char,std::char_traits<char>,std::allocator<char> > &
		[size]	0	unsigned int
		[capacity]	15	unsigned int
+		[allocator]	allocator	std::_Compressed_pair<std::_Wrap_alloc<std::allocator<char> >,std::_String_val<std::_Simple_types<char> >,1>
+		[Raw View]	{...}	const std::basic_string<char,std::char_traits<char>,std::allocator<char> >
```

**Locals;**
```
		this	Variable is optimized away and not available.	
+		<begin>$L0	{Name={...} Path={...} RideType=??? ...}	std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<TrackRepositoryItem> > >
		count	50	unsigned int
+		entry	""	const std::basic_string<char,std::char_traits<char>,std::allocator<char> > &
+		item	{Name="Dueling Dreams" Path=<Error reading characters of string.> RideType=52 '4' ...}	TrackRepositoryItem
+		ori	0x00000000 <NULL>	const ObjectRepositoryItem *
+		repo	0x042b5b60 {...}	IObjectRepository *
		rideType	52 '4'	unsigned char
```

**Comment by Gymnasiast** [comment]
@UnsaltedCashews Can you still reproduce this issue? Can you upload the "Dueling Dreams" track design?

**Comment by UnsaltedCashews** [comment]
I appreciate you looking at this again after three years, thanks 💯 . Haven't had any issues opening the Wooden Roller Coaster track for as long as I can remember. May have been resolved somewhere along the way. Yep, if its still required I can upload the track design, have to dig it up. Let me know

**Comment by Gymnasiast** [comment]
Yes, please. I keep some "naughty" track designs, so I can test for issues resurfacing.

**Comment by UnsaltedCashews** [comment]
Perfect, here's Dueling Dreams, god speed 👍 

[Dueling Dreams.zip](https://github.com/OpenRCT2/OpenRCT2/files/5308342/Dueling.Dreams.zip)
