### ISSUE TITLE
Action and chat log should not re-open log file for each line

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#5562]
#5557 merged new code for logging multiplayer actions. The issue with this code is that it re-opens a file every time log is appended. This is highly inefficient and bad code.

It should be fixed to open log file once and keep writing there. See my comments here (and below): https://github.com/OpenRCT2/OpenRCT2/pull/4273#pullrequestreview-7583468

**Comment by cching0L2** [comment]
Taking a look at this issue right now
