### ISSUE TITLE
Game doesn't release old Audio Outputs (inconsistently.)

### ISSUE THREAD

**Issue by Krutonium** [OpenRCT2/OpenRCT2#5566]
**OS:** Arch Linux
**Version:** 0.0.8
**Commit/Build:** f04439e0a (and earlier)

It is possible to have the game spew audio forth from the depths of hell, inconsistently. It happens when switching the audio output device, but as of yet is inconsistent. All times it has happened, I loaded the game went to Options, and changed the output. Once the bug has begun, the more times you switch, the more confused outputs get.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open Options
2. Toggle Audio Device

**Screenshots / Video:**
https://youtu.be/RnnuoQIWz2U
![audiobug](https://user-images.githubusercontent.com/3945538/26899558-785ea08e-4b9d-11e7-882f-cb1e233fdbb1.png)

**Comment by Gymnasiast** [comment]
> @Krutonium : “It hasn't resolved explicitly, but doesn't seem to be a problem any more either.”

Closing for this reason. Can be reopened if the problem resurfaces.
