### ISSUE TITLE
Peeps don't leave the park if they're happy and they have cash; causes issues in parks with entrance fees.

### ISSUE THREAD

**Issue by davewthompson** [OpenRCT2/OpenRCT2#5569]
**Windows 10 x64**
**v0.0.8-develop**
**6e21614**

When playing a level where a park entrance fee is charged (for example, Factory Capers) guests will arrive into the park but never appear to leave!

For example, in my current game, the current date is 26th March, Year 3. Of the 2,130 guests who have entered the park, 2,118 are still in the park, meaning only 12 have left the park since it was opened.

I checked the source code, and see below comment for an explanation - the game is coded never to send guests home if they're happy and have money.

- [ N ] Reproducible in RCT2 (vanilla)?
- [ Not Tried ] Multiplayer?

**Steps to reproduce:**
1. Start "Factory Capers"
2. Build a park.
3. Wait.

**Save game:**
Attached
[Factory Capers.zip](https://github.com/OpenRCT2/OpenRCT2/files/1060554/Factory.Capers.zip)

**Comment by davewthompson** [comment]
I think the issue here is in peep.c:722, in the peep_decide_whether_to_leave_park method.

If a guest is happy, and has enough money, they'll *never* leave the park... so if you have a set of cash machines in your park (or the guests are arriving with a considerable amount of money) then they will never, ever leave the park.

This means it's hard to keep adding new rides the later you get through the levels as the income from park entrance tickets begins to drop.

I perhaps think that a guest should always consider leaving the park *if* the park has an entrance fee *and* they've been either in the park for a certain duration or they've been on a set % of rides.

Any thoughts?

**Comment by Gymnasiast** [comment]
I doubt that is the issue. A refactoring error is more likely to be the culprit here. I remember testing something else recently and noticed the park rating was way too high. Most likely the same issue as this.

**Comment by davewthompson** [comment]
Not sure if it's a bad refactor; there's a quote above the method/function which clearly says:

>     /* Peeps that are happy enough, have enough energy and
>     * (if appropriate) have enough money will always stay
>     * in the park. */

#[peep.c:peep_decide_whether_to_leave_park](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/peep/peep.c)

**Comment by Gymnasiast** [comment]
Yes, and that is how it should work. People get unhappy quickly enough in normal circumstances, but it looks like they stay happy for too long for some reason.

**Comment by davewthompson** [comment]
Yeah, agreed, so perhaps some logic should be added that makes people too tired out from walking around / bored / etc so they do go home!!!

**Comment by rwjuk** [comment]
Something very odd is going on here! I tested that save by using the debug tools to set all guests' happiness to minimum. That worked, but within 30 seconds or so most were at maximum happiness again...

Investigating.

**Comment by Gymnasiast** [comment]
I just solved a refactoring error that caused an underflow, meaning it would set happiness to very high levels when in case where it should have set it to very low ones. Could be the culprit, though that needs investigating.

**Comment by sjoerddebruin** [comment]
Seems to have solved it, can't replicate it in the most recent version.
