### ISSUE TITLE
Clicking Multiplayer Button in main menu crashes the game if no save game exists. 

### ISSUE THREAD

**Issue by Devoider** [OpenRCT2/OpenRCT2#5575]
Windows 10
V. 0.0.8 - dev build 12c84d8

Clicking Multiplayer Button in main menu crashes the game if no save game exists. 

**Steps to reproduce:**
1. Open new install
2. click multiplayer
3. Crash ensues. 

Was helping a friend start the game the first time and wanted to try multiplayer, he clicked multiplayer and it immediately crashed, played a save game and then it didn't crash. I made a fresh install and hid my save-games folder and the same issue happened.

**Comment by rwjuk** [comment]
I'm not sure this is related to the save game folder - the game will crash on opening the MP window on the very first run at the moment, but it has a different cause. Once #5712 is merged, please retry and see if the issue persists.

**Comment by rwjuk** [comment]
Could you retest this on the latest build now that #5712 has been merged?
