### ISSUE TITLE
crash in object selection

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#5588]
**OS:** Windows
**Commit/Build:** 71b63a3c8a1ea39fd1d5d39f0ef556c6066dc98e

_Reported to me from NEdesigns, I haven't investigated yet_

Save
[Riverland 1 Season 001.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/1066323/Riverland.1.Season.001.sv6.zip)

- during single player open object selection (the scenario editor window for object selection
- find an unused small scenery item and uncheck it (for example "cactus)
- proceed to check any other small scenery item that was formerly unused
- now close the object selection window again to save the new selection
- CRASH

**Comment by IntelOrca** [comment]
Not sure if this fix is going to fix the specific issue this user is having as I got it just by hovering objects. But I can not reproduce crash after fix.
