### ISSUE TITLE
The map menu displays the park with weird colours

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#5596]
Windows 8
v0.0.8
3988b77

The in-game map window shows the park with different colours than it used to, or what is used in ClosedRCT. Most notable, rides are no longer displayed in red but in blue, making the map very hard to read. Red stands out. Blue looks like water. The secondary view, the rides-focused one, also looks funny because the tiles without a ride or path are displayed in black, and no longer in gray.

I assume this is a bug, but it's actually a nice idea to play with these colours. It should be totally up to the user though. Can this be included in the interface theme options? I would surely have a lot of fun with that. But first I would make the rides red again. ;)

**Comment by Gymnasiast** [comment]
This affects both the regular view and the rides view of the Map window.

**Comment by Gymnasiast** [comment]
Most likely to be caused by 

The rides being blue is caused by changing:
`0xB700`
to
`MAP_COLOUR_2(PALETTE_INDEX_135, PALETTE_INDEX_0)`
but the latter amounts to `0x8700`, rather than `0xB700`. It should have been
`MAP_COLOUR_2(PALETTE_INDEX_183, PALETTE_INDEX_0)`
