### ISSUE TITLE
Game fails on startup (macOS Sierra)

### ISSUE THREAD

**Issue by jeroenwallaeys** [OpenRCT2/OpenRCT2#5603]
**OS:** [Mac OS X 10.12.5]
**Version:** [0.0.8]

The games failes on startup. Error message can be found attached to this issue.

[OpenRCT2 error.pdf](https://github.com/OpenRCT2/OpenRCT2/files/1069373/OpenRCT2.error.pdf)

**Comment by janisozaur** [comment]
@jeroenwallaeys can you please **NOT** post the stack trace as PDF? It makes it extremely tedious to work with.

**Comment by IntelOrca** [comment]
[stacktrace.txt](https://github.com/OpenRCT2/OpenRCT2/files/1069429/stacktrace.txt)

**Comment by rwjuk** [comment]
Can reproduce this - only happens on first startup, without a configured RCT2 directory. I imagine it's related to the changes in #5526.
