### ISSUE TITLE
Miniature Railway vehicle bug when using 'select rides by track type'

### ISSUE THREAD

**Issue by rwjuk** [OpenRCT2/OpenRCT2#5609]
This happens only if you're in 'select rides by track type' mode.

1. Add the School Bus Ride and San Francisco Tram to a park
2. Build a Miniature Railway track
3. Set the vehicle type to 'School Bus'
4. Set the vehicle type (back) to 'San Francisco Tram'
5. See below - '0 cars in train' and no visual.

![capture](https://user-images.githubusercontent.com/16639257/27098103-4b7e723a-506e-11e7-931a-6c704097285b.PNG)

**Comment by Gymnasiast** [comment]
An interesting issue. It's most likely caused by the game trying to keep the number of cars the same when switching trains, but apparently not taking zero cars into account or the lower limit. If you click the button to increase the number of cars per train, it will revert to normal again.
