### ISSUE TITLE
'PLATFORM_MODIFIER' defined twice on macOS

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/OpenRCT2#5617]
**OS:** macOS
**Version:** 0.0.8
**Commit/Build:** 1dae7f9f3255777e516cc999182cdca458a4451c

Recent refactoring seems to have introduced this macro error:

```
[ 91%] Building C object CMakeFiles/openrct2.dir/src/openrct2-ui/input/keyboard_shortcut.c.o
In file included from /Users/aaron/Projects/OpenRCT2/OpenRCT2/src/openrct2-ui/input/keyboard_shortcut.c:34:
/Users/aaron/Projects/OpenRCT2/OpenRCT2/src/openrct2-ui/input/KeyboardShortcuts.h:28:13: error: 'PLATFORM_MODIFIER' macro
      redefined [-Werror,-Wmacro-redefined]
    #define PLATFORM_MODIFIER CTRL
            ^
/Users/aaron/Projects/OpenRCT2/OpenRCT2/src/openrct2-ui/../openrct2/platform/platform.h:52:13: note: previous definition is here
    #define PLATFORM_MODIFIER CMD
            ^
1 error generated.
```

**Comment by Gymnasiast** [comment]
Xcode also complains about this, even though it will let you compile anyway.
The solution is to surround the block in keyboard_shortcut with an ifndef.

**Comment by janisozaur** [comment]
Have we not enabled Xcode's `-Werror`?

**Comment by IntelOrca** [comment]
No block, they just need removing from platform.h

**Comment by AaronVanGeffen** [comment]
The problem persists. @rwjuk removed the define for `KEYBOARD_PLATFORM_MODIFIER`, rather than the conflicting `PLATFORM_MODIFIER CMD`.

**Comment by rwjuk** [comment]
@AaronVanGeffen D'oh! New PR open with correct fix.
