### ISSUE TITLE
Cannot load RCT2 files from directory with accents on macOS

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#5622]
This appears to have broken again recently. It now crashes because it cannot load any scenery objects, even though it does accept the path (i.e. it does not ask me to select a directory where my RCT2 files reside).

**Comment by rwjuk** [comment]
Hmm... I'm guessing somewhere is missing the Unicode normalisation function.

**Comment by Gymnasiast** [comment]
It must be something new, as it did work up until a few days ago.

Can you reproduce it?

**Comment by rwjuk** [comment]
When I manage to revive my macOS machine, I will let you know! (battery weirdness...)

In the meantime, @marijnvdwerf @LRFLEW - can you replicate?

**Comment by LRFLEW** [comment]
Hmm... can't seem to replicate it. I copied my RCT2 folder to have the name `rct2 with áccénts`, renamed my config file, and selected the folder in-game. Even after restarting the game, it worked just fine. I can mess with different Unicode normalizations in the config file to see if I can force it.

**Comment by tupaschoal** [comment]
@Gymnasiast or @AaronVanGeffen can you see if this still happens?

**Comment by aidan-waite** [comment]
I just did the following test and was unable to reproduce the error.

MacOS 10.15.7
Open RCT2 commit a2841199 (latest on develop branch as of yesterday)
Filepath: /Users/aidanwaite/öåáúñ_rct2files/RollerCoasterTycoon2TTP_EN

I created several new games and they all worked as expected.

**Comment by Gymnasiast** [comment]
I'm just going to assume it is no longer occurring, then. A lot has changed since 2017, including the removal of a useless round-trip widechar conversion in Posix.cpp that caused issues.
