### ISSUE TITLE
scenario_load_and_play_from_path needs minor refactoring

### ISSUE THREAD

**Issue by rwjuk** [OpenRCT2/OpenRCT2#5623]
Returns `sint32`, but the result is treated as a `bool`, flow control could be clearer.

**Comment by Gymnasiast** [comment]
Indeed. By the way, it's by no means the only occurrence.

**Comment by rwjuk** [comment]
Oh I don't doubt it - I just came across this one while finishing up the missing object window PR and didn't want to forget. Perhaps I'll do a mass sweep on weird function signatures like the `sub_<hex>` stuff...

**Comment by rwjuk** [comment]
`scenario_load()` goes on my hit list too.

**Comment by rwjuk** [comment]
Fixed in #6077
