### ISSUE TITLE
Game starts to flicker after Alt+Tabbing out and closing all other tabs beside OpenRCT2

### ISSUE THREAD

**Issue by Wuisj** [OpenRCT2/OpenRCT2#5625]
**OS:** Windows 10
**Version:** 0.0.8-develop build
**Commit/Build:** 5f5f12a

**Steps to reproduce:**
1. Open OpenRCT2 Launcher and start the game
2. Alt+Tab out of the game and start for example your internet browser
3. Close all tabs but OpenRCT2 and OpenRCT2 will automatically try to get fullscreen

**Comment by rwjuk** [comment]
Can I just confirm - you say you're on version 0.0.6 - that's quite an old build, are you sure that's the one you have? If so, could you download the latest version from openrct2.org and retry with that one? Thanks!

**Comment by Gymnasiast** [comment]
Another thing is that '2164' is not a valid commit number. What we need is the seven-character build hash, which is displayed in the title screen and looks a bit like `a1b2cd3`.

But yes, make sure your game is updated to the latest `develop` version first.

**Comment by Wuisj** [comment]
I see, apparently earlier on I probably had problems with the develop version and I didn't know where to exactly submit issues, so I just went to the stable build. I think both the version and build I gave are of the launcher. I'm going to play for the rest of the evening so I'll notify if I encounter the bug in the develop version which would be build "5f5f12a", could I be right?

**Comment by rwjuk** [comment]
Yes, `5f5f12a` is the latest build.

**Comment by rwjuk** [comment]
@Wuisj I can't replicate this in the develop build... could you use some screen recording software to record a video of exactly what happens?

**Comment by Wuisj** [comment]
I would love to show you a recording of what happens, but the problem is, if I have a recording software running, the problem doesn't occur. Make sure you have closed all apps but OpenRCT2, make sure of this through the task manager. If it doesn't trigger then, try opening and closing your internet browser.

I can show you a recording with my mobile phone though, this doesn't make a clear view though, also apologies that when I Ctrl+Alt+Delete to get task manager to start, I don't show the screen. Here it is: https://youtu.be/D0K8n2Z2XA0

Also, I can show you a screenshot of my OpenRCT2 settings:
![joshua valley park 2017-06-19 00-16-37](https://user-images.githubusercontent.com/29460565/27264701-9b8fa8ec-5484-11e7-8fbc-7c61e1162bfc.png)

**Comment by IntelOrca** [comment]
Does the problem occur if you set drawing engine to `Software`?

I suspect the issue may be driver related and something SDL2 would possibly need to fix.

**Comment by Wuisj** [comment]
Both Software and Fullscreen (borderless) seem to fix the issue individually. (So not both required) Thanks!

**Comment by rwjuk** [comment]
Closing this as it's likely to be a driver-related issue, and a workaround exists.
