### ISSUE TITLE
Issue with Freefall Drop Mode, Downward Launch Mode, Rotating Lift Mode and Upward Launch Mode

### ISSUE THREAD

**Issue by xp4xbox** [OpenRCT2/OpenRCT2#5629]
OS: Windows 7
Version: 0.0.8
25b6c61

In vanilla, while using those operating modes for a tracked roller coaster, the vehicle moves backwards in a steady pace. In openrct2, the vehicle's does frequent pauses so it moves much slower.

- [both] Multiplayer?

**Steps to reproduce:**
1. Build any tracked roller coaster as you would for a reverse-inclined one.
2. Set the ride operation mode to either downward launch or freefall drop mode.
3. Run the ride.

![bumbly bazaar 2017-06-15 21-38-19](https://user-images.githubusercontent.com/24964930/27208478-e19872d8-5213-11e7-85a3-4b36031daf36.png)
![bumbly bazaar 2017-06-15 21-38-38](https://user-images.githubusercontent.com/24964930/27208479-e19b1b8c-5213-11e7-84b8-0d7de5239bb6.png)

**Save game:**

[save.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/1079517/save.sv6.txt)

**Comment by xp4xbox** [comment]
I think the problem relates to this code `   switch (ride->mode){
    case RIDE_MODE_UPWARD_LAUNCH:
    case RIDE_MODE_ROTATING_LIFT:
    case RIDE_MODE_DOWNWARD_LAUNCH:
    case RIDE_MODE_FREEFALL_DROP:
        if (vehicle->velocity >= -131940){
            vehicle->acceleration = -3298;
        }
        if (vehicle->velocity < -131940){
            vehicle->velocity = vehicle->velocity / 16;
            vehicle->acceleration = 0;
        }

        eax = vehicle_update_track_motion(vehicle, &ebx);
        if (!(eax&(1 << 5)))
`

**Comment by xp4xbox** [comment]
I can guarantee that the problem is with this section of code, because when I tested out upward launch and rotating lift mode, the same bug occurred. If someone could help me out on this, I would be very appreciative, since this bug is necessary to be fixed for me.

**Comment by xp4xbox** [comment]
OK, now I can confirm that that is the problem because, I was messing around with the numbers, and I was able to get the train go super fast and smooth.

**Comment by duncanspumpkin** [comment]
I've checked vanilla that bit of code is identical.

**Comment by duncanspumpkin** [comment]
Its probably an issue with `vehicle_update_track_motion`.

**Comment by xp4xbox** [comment]
Huh,  I was able to get the operating mode almost working by changing those numbers.

**Comment by xp4xbox** [comment]
Actually it could be, since that effects all 4 modes.

```
case RIDE_MODE_UPWARD_LAUNCH:
    case RIDE_MODE_ROTATING_LIFT:
    case RIDE_MODE_DOWNWARD_LAUNCH:
    case RIDE_MODE_FREEFALL_DROP:
        if (vehicle->velocity >= -131940){
            vehicle->acceleration = -3298;
        }
        if (vehicle->velocity < -131940){
            vehicle->velocity = vehicle->velocity / 16;
            vehicle->acceleration = 0;
        }

        eax = vehicle_update_track_motion(vehicle, &ebx);
        if (!(eax&(1 << 5)))
            break;
```

**Comment by xp4xbox** [comment]
I tested it out and...

0.0.3.1 works fine
but 0.0.4 doesnt

**Comment by duncanspumpkin** [comment]
Okay found the bug. Turns out you were right. Problem was in that code segment. Try spot the issue. 

```
        if (vehicle->velocity >= -131940){
            vehicle->acceleration = -3298;
        }
        if (vehicle->velocity < -131940){
            vehicle->velocity = vehicle->velocity / 16;
            vehicle->acceleration = 0;
        }
```

Symptoms: velocity saw toothing (https://commons.wikimedia.org/wiki/File:Sawtooth_wave.svg) when it should be smooth acceleration to a max velocity before oscillating slightly at max velocity. 

Cause: The code that should keep the velocity near max velocity is actually making it a 16th of the value. WOOPS. That should actually just decrease the speed by a 16th.

Solution:
```
            vehicle->velocity -= vehicle->velocity / 16;
```
