### ISSUE TITLE
Issue with loan interest adding money

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#5635]
OS: Windows 7
Version: 0.0.8
Commit/Build: 9e1711c

I noticed that the loan interest in the Alton Towers scenario (.sc4) actually adds money instead of subtracting it. I thought it could be an issue with RCT1 importing but after additional testing in a sandbox scenario (.sc6) the issue seems to be that when the loan interest get too high it becomes a positive number. 

Screenshots:
![alton towers 2017-06-16 15-46-35](https://user-images.githubusercontent.com/28242696/27242500-85145af2-52ab-11e7-87d6-c3ca75423302.png)

**Comment by rwjuk** [comment]
Hmm, `current_interest_rate` is stored in SV6 as a `uint8`(!)...

**Comment by rwjuk** [comment]
@SidaRadis Nice find - you're right, it's caused by integer overflow.

**Comment by SidaRadis** [comment]
This might need to be re-opened because the issue is still happening in the latest build.

**Comment by SidaRadis** [comment]
I did some quick testing with a 5 000 000 loan at different interest rates.
8% = -48 828/month
9% = +49 926/month
10% = +43 822/month
11% = +37 719,20/month
20% = -17 212/month
30% = +26 610/month

**Comment by rwjuk** [comment]
Clearly #5637 didn't fix this entirely.
