### ISSUE TITLE
Right mouse dragging is affected by higher game speed

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#5647]
OS: Windows 7
Version: 0.0.8
Commit/Build: 312adaf

Dragging the view point with right mouse becomes progressively faster when you increase the game speed. For example, dragging is faster in hyper speed than in quick speed. (only normal speed is unaffected)

Edit: Increasing or decreasing the price of a ride also has the same issue.

**Comment by ZehM4tt** [comment]
I think its possible this is my fault by a recent change of mine, I will take a look into this.

**Comment by ZehM4tt** [comment]
Just tested this, will submit a PR to fix this.

**Comment by SidaRadis** [comment]
Should this be closed ? I believe #5650 fixed this issue.
