### ISSUE TITLE
Android builds aren't pushed to openrct2.org

### ISSUE THREAD

**Issue by marijnvdwerf** [OpenRCT2/OpenRCT2#5657]
- [ ] `develop` and `master` builds should be signed with a private key
- [ ] Built APKs should be deployed to website (Currently having arm and x86 builds)

**Comment by marijnvdwerf** [comment]
@JarnoVgr You handle the website, right? Can you add two new platforms for this?

**Comment by JarnoVgr** [comment]
Tomorrow I'll drop you the details via gitter. :)

**Comment by SinisterSoft** [comment]
Is an APK going to be built for openrct2.org (like the other builds) or are there build instructions so I can make the APK myself?

**Comment by marijnvdwerf** [comment]
Given the current status, deployment to openrct2.org seems unlikely.

**Comment by SinisterSoft** [comment]
Are there build instructions then?  Where should the originals files go?

**Comment by janisozaur** [comment]
https://www.reddit.com/r/rct/comments/6i595z/openrct2_now_has_android_support/dj3o6qi/?context=10000

The APKs we build are pushed to transfer.sh for now

**Comment by marijnvdwerf** [comment]
Only occasionally though, and the current build is failing, meaning no new builds.

Anyway, the builds aren't exactly playable yet either.

**Comment by janisozaur** [comment]
The problem here is the android builds take way too long to be part of our regular CI run. I have relegated them to be cron-based and they are built daily.

I can make them be deployed to openrct2.org, but it will be hard to figure out which builds have android builds and which don't, most falling in the latter category.

@JarnoVgr is there any way you could apply filter to the list of builds to only show those with android APKs?

**Comment by JarnoVgr** [comment]
@janisozaur Could you start pushing them, even if they're cron-based? I have some ideas on how to display the builds. :) Thanks!

**Comment by janisozaur** [comment]
@JarnoVgr what's the flavourID?

**Comment by JarnoVgr** [comment]
@janisozaur 
Android ARM and ARM64 is flavour 11.
Android x86 and x86_64 is flavour 12.

If there's just one arch or when combined, please use 11 and let me know so I can update the text. :)

**Comment by janisozaur** [comment]
both are used and I have pushed a commit to make travis deploy builds to .org and restarted cron-job. We'll see if it works.

**Comment by janisozaur** [comment]
https://travis-ci.org/OpenRCT2/OpenRCT2/jobs/295982398

**Comment by janisozaur** [comment]
https://travis-ci.org/OpenRCT2/OpenRCT2/jobs/296301403 this is a job that used that new commit, but didn't quite work yet.

> `{"error":1,"errorMessage":"POST variables missing or invalid: fileName, version, gitHash, gitBranch, flavourId"}`

I have to check what went wrong.

**Comment by janisozaur** [comment]
> `{"error":0,"processed":true,"downloadId":2996,"fileHash":"c6fbaf801911a475f7c5de2c466073e81073a30ea88e2f1122ad7c3a0edd9033","fileSize":11547800,"url":"http:\/\/cdn.limetric.com\/games\/openrct2\/0.1.2\/develop\/13dd00e\/12\/OpenRCT2-0.1.2-develop-13dd00e-android-x86.apk"}`

I consider this done.
