### ISSUE TITLE
Assertion failed errors in file "peep/peep.c" on parks from nedesigns.com

### ISSUE THREAD

**Issue by PendingOperation** [OpenRCT2/OpenRCT2#5658]
**OS:** Windows 10
**Version:** 0.0.8
**Commit/Build:** 1074010

When opening parks from Nedesigns, assertion errors occur after letting the game play without doing anything. it is possible to hit ignore a billion times and continue playing, but it comes back after some time.

- [No] Reproducible in RCT2 (vanilla)?
- [not tried] Multiplayer?

**Steps to reproduce:**
1. Download any of the parks: https://www.nedesigns.com/park/3000/thorpe-park/download/
https://www.nedesigns.com/park/3835/sunset-lake/download/
2. Wait for error, to speed things up, feel free to fast forward(same result).

**Screenshots / Video:**
Thorpe Park:
![thorpepark](https://user-images.githubusercontent.com/27915009/27296957-4c445748-5523-11e7-85bc-286f42bec55c.jpg)
Sunset Lake:
![sunsetlake](https://user-images.githubusercontent.com/27915009/27297009-6ecfec14-5523-11e7-9c32-03b4927198b7.jpg)

**Save games:*
https://www.nedesigns.com/park/3000/thorpe-park/download/
https://www.nedesigns.com/park/3835/sunset-lake/download/

**Comment by Gymnasiast** [comment]
The two errors you bumped into are corruptions in the state of the save. We can correct them automatically.

**Comment by IntelOrca** [comment]
@Gymnasiast These are hacked saves, so we will probably have to assume this state can exist and protect against it.

**Comment by Gymnasiast** [comment]
Yes, which means clamping it to valid values, and outputting an error/warning saying we did.

**Comment by janisozaur** [comment]
I'm not convinced @IntelOrca, I've seen some servers that I don't think were using such hacked parks and yet exhibited these issues.

**Comment by IntelOrca** [comment]
@janisozaur ok... but the parks mentioned were created with vanilla RCT2.

**Comment by Chaosmeister** [comment]
I just looked into this and I can't say if it is hacked or not.
How should this be automatically fixed? 
Remove the whole ride? Change the station tiles to straight track tiles?
Ignore the station?
Right now it accesses the array `ride->exits` out of bounds and ultimately creates nonsense coordinates for the `peep_go_to_ride_exit()` call

**Comment by Gymnasiast** [comment]
By replacing the assert with code that clamps the value within the correct bounds and emits a warning saying it did.

**Comment by Chaosmeister** [comment]
Well that was too easy 🙃

**Comment by janisozaur** [comment]
First of all, there are two separate issues reported here. It's very annoying to work with such reports, furthermore @PendingOperation posted JPEG(!) screenshots which are unsearchable, so good job at that.

I'm not convinced this is only due to hacked parks. The assert should stay in, rather than that park should be fixed on import and generate a warning then – that way imported park has no way of triggering the assert, while we can still have the check do its thing in case there really is a bug somewhere else. We already do that with some park variables.
