### ISSUE TITLE
ASSERTION FAILED! Failed to reallocate 3f20020 to have 0 bytes

### ISSUE THREAD

**Issue by Jasper128** [OpenRCT2/OpenRCT2#5659]
**OS:** Windows 7
**Version:** 32 bit
**Commit/Build:** ?

I am trying to install OpenRCT2. I have a windows 7 32 bit system.
So I downloaded the x86 exe file from the github (it was the most current version - v0.0.8 def76ed)
Upon finishing the installation I exited the setup with "Launch Openrct2" checked.
A blank window came up (as seen on the screenshot) with the ASSERTION FAILED error popout coming a few seconds after. Even if I only launch the exe as single file. So I uninstalled that version, and tried it with past versions, ranging from v0.0.6 builts until the todays version and they all gave me the same error. Even with the OpenRCT2 Launcher. I see the window where it says Play (and a little progress bar) and Options, but as soon as I click on play, I get the Assertion Failed error.

- [NO] Reproducible in RCT2 (vanilla)?
- [NO] Multiplayer?

**Steps to reproduce:**
1. Installing OpenRCT2 (any version) 32-bit installer
2. Launching openrct2.exe

**Dump file**
https://puu.sh/woFAM.DMP

**Screenshots / Video:**
https://puu.sh/woAZF.jpg

**Save game:**
No, because i dont even get that far

**Comment by Gymnasiast** [comment]
Which version of RollerCoaster Tycoon 2 do you have?
Can you open a command prompt, navigate to your OpenRCT2 directory, run openrct2.com and copy-paste its output?

**Comment by Nubbie** [comment]
@Jasper128 
Still having issues?

**Comment by Nubbie** [comment]
Feels like OP has left (not been active, just posted this issue on account), no dump, no jpg, should it be closed?

**Comment by Jasper128** [comment]
shouldnt be closed.
you are wrong
i did provide a dump and jpg
problems still remain

On Mon, Nov 20, 2017 at 7:49 PM, Michael Steenbeek <notifications@github.com

**Comment by janisozaur** [comment]
@Jasper128 the link you posted leads to a 404 and there is no stack trace. If you can provide the dump/stack trace/repro steps, then please re-open this issue.

**Comment by Gymnasiast** [comment]
@Jasper128 You put in stuff that links to a 404, did not specify any version besides two ancient ones and answered NONE of our questions. Why do you expect help?
