### ISSUE TITLE
Road pathways

### ISSUE THREAD

**Issue by alecward92** [OpenRCT2/OpenRCT2#5675]
**OS:** [WIndows 7]
**Version:** [0.0.8]
**Commit/Build:** [e.g. 53be8da]

I have noticed the past few maps I have hosted, (Freedom Server) The road pathways "disappear". When first launching a map they show up and I can build as I please, but once I update/restart the server, they turn into a standard pathway when selecting paths. The road will remain placed on the map, but I cannot add more road after the server restarts. Just the standard pathway. I attached a screenshot to what I have done in the beginning of the map compared to what I can do later on.

![1](https://user-images.githubusercontent.com/29580508/27348037-57fe66b0-55b8-11e7-8841-9d04e666d795.png)

**Comment by Gymnasiast** [comment]
Laying down roads requires the 'Sandbox mode' cheat. Cheats are reset when restarting the server. (We plan to save the cheat state in the saved games eventually.)

**Comment by alecward92** [comment]
I had no idea. Just tried it and it works. Never even realized Sandbox Mode was on at the time of making that road. But it makes sense. Thanks!!
