### ISSUE TITLE
Underground balloons

### ISSUE THREAD

**Issue by RogoDarius** [OpenRCT2/OpenRCT2#5677]
**OS:** Windows 10
**Version:** 0.0.8
**Commit/Build:** 7748184

Guests are able to drop balloons while underground.
I don't remember this ever occurring in the original games.

- [X] Reproducible in RCT2 (vanilla)?
- [X] Multiplayer?

**Steps to reproduce:**
1. Make an underground park
2. Sell balloons
3. Press H and V
4. Watch balloons being dropped from under-ground paths

**Screenshots / Video:**
![beforeballoon](https://user-images.githubusercontent.com/12530301/27355655-bf370aee-5603-11e7-86ab-b6e5cc935b21.PNG)

![afterballoon](https://user-images.githubusercontent.com/12530301/27355727-f5bd97a4-5603-11e7-8ed3-2fdad4d61fbe.PNG)

**Comment by 733737** [comment]
does this still occur?

**Comment by Broxzier** [comment]
@733737 This is something anyone can test.

**Comment by 733737** [comment]
is it really a bug? baloons would still travel upwards inside of a cave.

**Comment by MASHzj** [comment]
If it is, it's not really necessary to fix such a minor thing in my opinion.

**Comment by duncanspumpkin** [comment]
![image](https://user-images.githubusercontent.com/1277401/232288554-ef6798ab-8906-4714-8d91-065abe4acd36.png)
vanilla did no checks for this. Only the two scenario rands and a check that the location was not null.

**Comment by ZehMatt** [comment]
> is it really a bug? baloons would still travel upwards inside of a cave.

Balloons ordinarily don't phase shift through ceilings, so not a bug but rather oversight. I still think we can fix this by simply checking if there is another tile element above the guest before releasing the balloon.

**Comment by 733737** [comment]
Does this bug need an 0.4.6 milestone label?
