### ISSUE TITLE
Refactor some network Packets that affect the game state to be tick bound.

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#5684]
Currently networking the player list is not bound to ticks where it should since the client always lags behind the server. We should perhaps refactor some packets to use game commands instead of being a simple network packets.

Example with PLAYERLIST packet:
  Player (3) is currently placing tracks, issuing game commands at client Tick 33331
  Player (1) kicks Player (3) at client Tick 33332
  Server executes place track at Tick 33333, send game command back to clients.
  Server executes kick at Tick 33333 and sends the new player list to all clients, player is removed at this point.
  Player (2) receives place track from Player (3) at client Tick 33332, queues the command.
  Player (2) receives PLAYERLIST, executed at point of arrival which removes the player if hes missing in the list received.
  Player (2) executes at Tick 33333 the place track command, however the player does not exist anymore.

It should be clear that we can not remove players from the game state earlier than when the Server did it, the client has to always catch up otherwise this will cause faulty logic in the game state.
  
In some cases this is not a issue if the client is usually able to catch up fast enough however with higher latency this might be not the case. 

I would like to hear some suggestions and ideas on how we should process with such specific things. One suggestion is, we could also include in the packet header the tick by default and tell each client if he has to wait or not for the tick to be reached, however this requires a common queue to keep order in tact.

**Comment by Gymnasiast** [comment]
To me, it looks reasonable. The thing is I know next to nothing about the network layer, so I can't really comment. This is something for @IntelOrca @janisozaur and @zsilencer (if he is active again).

**Comment by janisozaur** [comment]
We could have server remove kicked player's actions from the queue or if it fails to do so (e.g. the action has been already sent for the tick), defer kicking until earliest next tick.

**Comment by duncanspumpkin** [comment]
Why not just delay the kick for a nominal amount of ticks and disallow any future commands after the kick is in the queue.

**Comment by ZehM4tt** [comment]
@janisozaur On the server client actions are never queued they are directly processed and then sent to the clients, theres no chance catching it before messages go out, it would be really rare to be on the same Tick where kick and place track happens from two different clients.

Clients should always do the same as the server in the same order and the same time, manipulating anything between seems error prone.

@duncanspumpkin The kick command is already bound to a tick, the real issue is that the playerlist is not and so the order of things is messed up like prematurely removing the player, it would be no issue if playerlist was a command since the server first sends the kick and then the playerlist.

**Comment by zsilencer** [comment]
PLAYERLIST does **not** affect game state

Game commands are separate, they are not tied to the player list at all.  The only reason kicking is a game command is to make use of the client->server, permission thats already there etc.  (modifying groups needs to be  a game command tho, cause that can actually affect future commands being rejected by server)

Lets say you actually did this, when someone paused the game causing no more ticks to be processed, if someone joined the game or disconnected they would not even appear until it was unpaused.

**Comment by ZehM4tt** [comment]
Thats how pausing usually works when theres a round trip involved. The other way would be to simply have a separate list for the player list to show but the actual client cant vanish not before the kick command is executed on the client.
