### ISSUE TITLE
"Do net let testing rides crash" does not work when two trains crash into each other

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#5688]
OS: Windows 7
Version: 0.0.8
Commit/Build: fef10c1

If you test a ride with the "Do net let testing rides crash" setting on and two trains collide into each other the crash still occurs instead of the normal "reset".

**Comment by Gymnasiast** [comment]
The option is a kludge anyway, to be replaced by a ghost train eventually.

**Comment by rwjuk** [comment]
Yeah, I'm guessing the game can't reset the ride quickly enough when trains actually collide. Not much we can do about that as @Gymnasiast rightly said.

**Comment by SidaRadis** [comment]
Fair Enough
