### ISSUE TITLE
Opening 

### ISSUE THREAD

**Issue by Alan489** [OpenRCT2/OpenRCT2#5689]
**OS:** Win10
**Version:** 0.0.8
**Commit/Build:** 1F00469

- [ Has happened several times ] Reproducible in RCT2 (vanilla)?
- [ Unknown ] Multiplayer?

**Steps to reproduce:**
1. Go into game
2. (What happened to me) Use Six Flags create your own 
3. Have cheats enabled on the following:
   a. Open park
   b. no money cheat
   c. own all land
4. Go into build attractions menu several times
5. Allow some time to pass between selecting the menu, and whatever coaster/attraction you want

**Dump file**
[a65acab9-e450-416b-8088-c56652268ad4(1f00469_x86-64).dmp.txt](https://github.com/OpenRCT2/OpenRCT2/files/1095961/a65acab9-e450-416b-8088-c56652268ad4.1f00469_x86-64.dmp.txt)

**Save game:**
[a65acab9-e450-416b-8088-c56652268ad4.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/1095962/a65acab9-e450-416b-8088-c56652268ad4.sv6.txt)

**Comment by rwjuk** [comment]
What actually happens after point 5? The game just crashes?

**Comment by Gymnasiast** [comment]
Your problem is not clear, neither is your title. And you said

`[ Has happened several times ] Reproducible in RCT2 (vanilla)?`

which is probably not what you meant.

**Comment by Alan489** [comment]
Yeah, sorry about that, I rushed it a bit. I figured out thr cause, I
forgot I was using RCT1 as well, and the problem was that my RCT1 install
was actually corrupted. Sorry about that!

**Comment by Gymnasiast** [comment]
Don't worry, good to hear your problem is solved. 👍
