### ISSUE TITLE
Unable to build steep slopes for Junior Roller Coasters

### ISSUE THREAD

**Issue by RQWorldblender** [OpenRCT2/OpenRCT2#5691]
**OS:** Ubuntu GNU/Linux 16.04
**Commit/Build:** 92988a60203066d1f91f310af6e20bf9fb49896a

For about the past two weeks, I have wondered about what happened to the ability to build junior roller coasters with steep slopes (while the track pieces are still drawn in-game, they can't be built or selected from the ride construction window, so I can only build these rides in the way that has been imposed in the original game. Did something else cause this to accidentally happen, or is this now intentional?

**Steps to reproduce:**
1. Open any scenario that already has junior roller coasters available to build.
2. Click "Build custom design", or
3. Build an existing design that contains steep slopes, see these two track designs for an example:
[LeftWined.td6.txt](https://github.com/OpenRCT2/OpenRCT2/files/1096323/LeftWined.td6.txt)
[RightWined.td6.txt](https://github.com/OpenRCT2/OpenRCT2/files/1096324/RightWined.td6.txt)
4. It is possible to use these steep slopes and reuse them, but that is going to be hard to do, and if building from these pieces, then only the steep slope to slope and steep slope to flat pieces can be selected.

**Screenshots / Video:**
![2017-06-22 17-19-12](https://user-images.githubusercontent.com/13372387/27458493-f9f27698-576e-11e7-9afd-11d2d0edb853.png)

**Comment by rwjuk** [comment]
@Gymnasiast Could this be related to the ride groups change?

**Comment by Gymnasiast** [comment]
This is indeed related. It was changed deliberately. The reason for that is that we used to ignore what a vehicle was actually capable of and enabled steep inclines anyway. This caused glitches on steep inclines.

With the ride groups PR, vehicles for the Junior Roller Coaster have been split into two groups: Junior Roller Coaster (without steep inclines) and Classic Mini Roller Coaster (with steep inclines, higher height, etc.). To be able to see the latter you'll need vehicles capable of taking steep inclines. I have two of those: [Classic Ladybird Trains](https://files.gitter.im/OpenRCT2/OpenRCT2/xWv3/RCT1ZLDB.DAT) and [Classic Log Trains](https://files.gitter.im/OpenRCT2/OpenRCT2/xWv3/RCT1ZLOG.DAT).

**Comment by RQWorldblender** [comment]
I just tried out the two DAT files; they work as intended (I think that the graphics are probably coming straight from Rollercoaster Tycoon 1), but I have the following minor complaints:
- Max # of trains for Classic Ladybird Trains is 8 instead of 10.
- Max # of trains for Classic Log Trains is 9? instead of 10.

I tested with a simple design with a station platform that is 6 units long.

P.S. If possible, can the Spinning Cars also be tested out here, too (create another DAT file containing this type of train)?

**Comment by Gymnasiast** [comment]
Oh, yes, I forgot about that. Thing is, the limit in those files is set to 10, but there also seem to be a friction cap in RCT2 that prevents more than 8/9 cars from being used in this case. I'll take a took if that limit can be removed.

The graphics are indeed directly from RCT1.

There is a conversion of the Spinning Cars. I don't have it on this laptop, so I would have to find it on my desktop, but I'm not near it at the moment.

**Comment by Gymnasiast** [comment]
I have just raised the friction cap. Please download the newest version and try again. Both trains should now be able to work with 10 cars.

**Comment by RQWorldblender** [comment]
I tried out the newest version just now, and it worked! Now here's that I'm wondering: Are Classic Mini Roller Coasters going to be available out-of-the-box, or do I have to download these DAT files for every new installation I do? BTW, I'm still waiting on the Spinning Cars, but there's no need to rush this.

**Comment by IntelOrca** [comment]
You should keep your custom objects in your `documents\openrct2\object` directory, this is your user data that can be backed up and will be preserved between installs of OpenRCT2.

**Comment by Gymnasiast** [comment]
[SFSPIN.DAT.zip](https://github.com/OpenRCT2/OpenRCT2/files/1099851/SFSPIN.DAT.zip)

Here are the Spinning Cars. You'll need cheats to put them onto the Classsic Mini Coaster.
They're not a very good conversion, but they'll have to do until we replace the object format, at which point it will be a lot easier to load RCT1 stuff directly.
