### ISSUE TITLE
Unable to run (0xc0000022)

### ISSUE THREAD

**Issue by pGore33p** [OpenRCT2/OpenRCT2#5697]
**OS:** Windows 8 64 bit
**Version:** 0.0.8
**Commit/Build:** b9e9ddf

For some reason, when I try to run the executable, it just pulls up this error. My antivirus is disabled, i have admin privileges but alas.

Older versions worked before so I have no idea why it doesn't work now.

Any ideas?

I have DirectPlay enabled. It still doesn't work

**Comment by Gymnasiast** [comment]
I have never seen this error at all.

Open a Command Prompt, navigate to the OpenRCT2 directory and run
```
openrct2 --verbose
```
and paste the output.

BTW: You don't need DirectPlay for OpenRCT2. You only need it for RCT1 and RCT2.

**Comment by pGore33p** [comment]
Where's the output? It doesn't give me anything in the command prompt when i try that

**Comment by rwjuk** [comment]
Okay, can you take a screenshot of the error you get when trying to run the game?

**Comment by pGore33p** [comment]
![openrct 2](https://user-images.githubusercontent.com/10586092/27509784-a323fea8-5904-11e7-9641-66cc7185548b.PNG)

That basically says: "The application failed to start correctly. Press OK to end the application."

**Comment by Gymnasiast** [comment]
Can you provide the _last_ version number that worked, and the first that didn't?

**Comment by pGore33p** [comment]
I don't really remember the last version it was like a year ago. I think it was 0.0.4.

**Comment by Gymnasiast** [comment]
We really need to know which version still works.  Try out older versions until you find one that works, then pinpoint the exact version that introduced this error for you.

Although I have to say I'm not sure if it's really an error in OpenRCT2, but we'll find out.

**Comment by janisozaur** [comment]
~~Poor man's~~ Windows' user's `strace`: https://knowledge.autodesk.com/search-result/caas/sfdcarticles/sfdcarticles/The-application-was-unable-to-start-correctly-0xc0000022-Click-OK-to-close-the-application.html

**Comment by pGore33p** [comment]
Version 0.0.7 is causing the issue. All the previous versions do work. It may be one of the 0.0.6 builds.

**Comment by IntelOrca** [comment]
This message can appear if you are running x64 apps on 32-bit OS or if DLLs are called that are a different architecture.

**Comment by pGore33p** [comment]
I have a 64 bit system so that's not the cause.
And which DLLs do you mean?

**Comment by rwjuk** [comment]
Let's say you have a 64-bit process, but it tries to load and call a 32-bit DLL. 

The '32-bit shaped' block won't fit in the '64-bit shaped' hole, and the whole process crashes. I somehow doubt that's the problem here though. Could you try the following please?

1. Run OpenRCT2, let it crash.
2. Press CTRL-SHIFT-ESC to load Task Manager
3. Right click the OpenRCT2 process in the list and click 'Create Dump'.
4. Upload the dump file it gives you here for us to have a look at.

**Comment by pGore33p** [comment]
Here it is.

**Comment by pGore33p** [comment]
http://www.mediafire.com/file/q0kxn6xq78ta1g4/openrct2.DMP

here it is.

**Comment by rwjuk** [comment]
Hmmm.... windbg reports the bugcheck as `LOADER_INIT_FAILURE_80000003`, which makes me think that IntelOrca's DLL suspicions might be right. The full windbg analysis is [here](https://gist.github.com/rwjuk/70f430541277b915f0e021189146489c).

**Comment by IntelOrca** [comment]
@pGore33p Could you try download and using the 32-bit version?

**Comment by rwjuk** [comment]
Furthermore, if that doesn't work, could you do this - it'll help us with diagnostics.

1. Download Process Monitor: https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx
2. Run it.
3. Run OpenRCT2 and let it crash.
4. In Process Monitor, go to "File > Save".
5. Leave all options at their default setting, save the PML file somewhere and upload it here.

**Comment by pGore33p** [comment]
Nah, didn't work.
The PML file: https://www.mediafire.com/?et6tuo78wauu65l

**Comment by rwjuk** [comment]
@pGore33p Interesting, I can see from the trace that OpenRCT2 tries to load its DLL (`openrct2.dll`) but gets an access denied error. I'm not sure what could cause that without looking at your machine.

@IntelOrca - any suggestions for further diagnostics?

**Comment by IntelOrca** [comment]
Sometimes virus scanners have been known to block OpenRCT2.

**Comment by pGore33p** [comment]
My antivirus is disabled so that isn't the case too.
It's strange that both the x86 and x32 versions don't work


I hope it gets fixed soon :/

**Comment by pGore33p** [comment]
I don't think that's related, but I just got this EXACT same error when i tried to open Skype, but I don't remember doing anything to my computer over the past few days/weeks.

**Comment by rwjuk** [comment]
If the exact same issue is happening with other applications, it is *very* unlikely to be an issue with OpenRCT2. The reason older versions work is probably because back then we didn't need to load a separate DLL.

It's likely to be something on your system blocking the loading of DLLs. I'll close this as it's not really an OpenRCT2 issue.

**Comment by IntelOrca** [comment]
Older versions did not use a DLL, (but not too old) did not use a DLL - that is probably also why.

**Comment by pGore33p** [comment]
Still can't get it to work even though i disabled every thing that can potentionally block my dll.
I guess I'll just refer to PC Support Forums then. Idk.

**Comment by IntelOrca** [comment]
@pGore33p you could install a clean Windows 10.

**Comment by janisozaur** [comment]
Or Linux.
