### ISSUE TITLE
Usernames may not be automatically detected for multiplayer

### ISSUE THREAD

**Issue by rwjuk** [OpenRCT2/OpenRCT2#5707]
Blank-named multiplayer users have been noticed recently, and lack of autodetection was reported during testing of #5706 (see [this comment](https://github.com/OpenRCT2/OpenRCT2/pull/5706#issuecomment-310929898)).

**Comment by janisozaur** [comment]
somewhat relevant may be the timing of https://github.com/OpenRCT2/OpenRCT2/issues/4301#issuecomment-310868004

**Comment by ibara** [comment]
To add a data point, I just installed the latest development build on a Win x64 machine, and it also did not autodetect the username.

**Comment by rwjuk** [comment]
Confirmed. `platform_get_username()` isn't actually ever called!
