### ISSUE TITLE
Unable to close park

### ISSUE THREAD

**Issue by bsamario** [OpenRCT2/OpenRCT2#5728]
**OS:**  Windows 10

I made a custom scenario and when I play it does not give me the option to close the park. I prefer to be able to build my park then open it.. Also it did not let me unclick the "no money" option, I like to know I am making a profit. Thank you!

**Comment by IntelOrca** [comment]
You can not open or close the park when money is turned off.

**Comment by bsamario** [comment]
how can I turn the money off? when I tried it would not let me change

**Comment by IntelOrca** [comment]
Unable to turn money off appears to be a bug:
#5730
