### ISSUE TITLE
Disable creating money effect when building in pause mode

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#5733]
This causes money effect spam and is also a big part of the problem in https://github.com/OpenRCT2/OpenRCT2/issues/3479 .

**Comment by bsamario** [comment]
Hi! Would this cause the game to keep crashing giving the message 
"assertion failed!
file: paint/sprite/sprite.c
line:86
expression: false"
I took your advice yesterday and used the cheat to allow money and close the park but maybe I did it while the game was paused? Now my game won't play a few minutes without crashing :(

**Comment by Gymnasiast** [comment]
That's another problem. Please open a new Issue for that.
