### ISSUE TITLE
"assertion failed" message

### ISSUE THREAD

**Issue by bsamario** [OpenRCT2/OpenRCT2#5739]
**OS:**Windows 10
 
Hello, I recently enabled the cheats, closed my park, and changed it from no money to money enabled. Now I keep getting the message
"assertion failed!
file: paint/sprite/sprite.c
line:86
expression: false"
I'm not even sure what sprite is, I've been searching the forums and see the word used but I'm not understanding. 

Save game:
[Pine Hills Parkbecky - Copy1.zip](https://github.com/OpenRCT2/OpenRCT2/files/1113214/Pine.Hills.Parkbecky.-.Copy1.zip)

**Comment by xp4xbox** [comment]
I could not replicate the issue, I was able to enable to money no problem, here is the save with the money enabled--->
[Pine Hills Parkbecky - Copy.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/1113266/Pine.Hills.Parkbecky.-.Copy.sv6.txt)

**Comment by Gymnasiast** [comment]
What is your OpenRCT2 version? You just deleted the field, but it's there for a _very good reason_.

**Comment by bsamario** [comment]
I changed the version a few times, downloading a new one about an hour before I posted this to see if that would help. I'm not sure which one as there have been a few new versions in the last few hours but I'll update to the newest and try again. Also I am not sure how to reproduce because I will just play for a  few minutes and it happens randomly, or freezes when I go attempt to save.

**Comment by bsamario** [comment]
I am now using version b39723a. Still having same problem, was building scenery for about 5 minutes and game froze randomly.

**Comment by Nubbie** [comment]
Commit: 03299b9
Could not replicate on neither save-files

**Comment by Gymnasiast** [comment]
I'm going to consider this solved. If it isn't, please let us know.
