### ISSUE TITLE
OpenRCT2 locking up consistently, no reports

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#5750]
**OS:** Windows 8.1
**Version:** 0.0.8
**Commit/Build:** 3ca84dc

OpenRCT2 has been locking up a lot since I started playing again yesterday. I've only just found it happening consistently, so here is this bug report.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open this file (rename to .sv6)
![ne s sandwich springs crashes](https://user-images.githubusercontent.com/3454156/27765388-77fb59aa-5e64-11e7-82b2-0a62cb6638ab.png)
2. Wait between 20 seconds and 26 seconds
3. Locked up:
![image](https://user-images.githubusercontent.com/3454156/27765394-9ab75da4-5e64-11e7-8c8d-75868b3d391c.png)

**Comment by zsilencer** [comment]
Looks like same as #3675

**Comment by ccoors** [comment]
Also #5184

**Comment by PFCKrutonium** [comment]
I'm sitting in a Server with ~ 7 people, and this is happening far too frequently to be left alone imho.

**Comment by PFCKrutonium** [comment]
![crasg](https://user-images.githubusercontent.com/3945538/27767177-ec852db2-5ebb-11e7-9187-52971abbcf1e.png)

**Comment by IntelOrca** [comment]
For this saved game, the damage is already done - ride 22 has its `last_peep_in_queue` set to a sprite that is not a peep. So I can't determine what caused this state from this saved game alone.
