### ISSUE TITLE
Title sequences are noticeably desynchronized

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#5752]
This is submitted for tracking purposes.

Commit 14443b30f1113420d6e55b2a8e12e20d72768ca0 changed title sequence seconds from 800 ms to 1000 ms. This creates issues because shots are taking on average 2 seconds longer than they were designed to and that time difference stacks, with negative results. Roller coasters are no longer in the frame and the camera spends time looking at non-moving rides.

<strike>It was proposed and agreed that title sequences could use decimal values, and for compatibility with older sequences, non-decimal values would use the legacy 800 ms time unit:

`1.` -> 1000 ms
`1.0` -> 1000 ms
`1` -> 800 ms</strike>

**Comment by IntelOrca** [comment]
I didn't agree to that. What I want to do is change the format of wait commands to now be in milliseconds and update our title sequences to use milliseconds. For example a wait command of `10` will become `8000` (10,000 * 0.8)

**Comment by spacek531** [comment]
I started penning this before you edited, so, sorry about that.

**Comment by spacek531** [comment]
pull request converting Title Sequence Seconds to ms: https://github.com/OpenRCT2/title-sequences/pull/1

**Comment by Gymnasiast** [comment]
Is this fixed now?

**Comment by IntelOrca** [comment]
Yes
