### ISSUE TITLE
Guests will not wait in queues

### ISSUE THREAD

**Issue by Trongsin** [OpenRCT2/OpenRCT2#5753]
**OS:** [Windows 10]
**Version:** 0.0.8
**Commit/Build:** cb28381

I actually joined the forum for this reason. In RCT2 vanilla, guests would wait for hours (literally) as long as entertainers and TVs were in the line. In Open RCT2 that's not the case. They start complaining after a few minutes even with entertainers and TVs. It's a real bummer because I spend a lot of time on long, themed queues. I really like the realism of long queues, makes your big attractions seem that much bigger. Any word if there is a way to fix this or if a change is coming?
Everything about Open RCT2 is amazing, but I would love to see TVs and entertainers working like they did in vanilla. 

 

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

Files were uploaded on the official OpenRCT2 forum.

https://openrct2.org/forums/topic/2531-guests-will-not-wait-in-queues/

**Comment by spacek531** [comment]
In this case, Reproducible in RCT2 would _not_ be checked, because the bug does not happen in RCT2.

**Comment by Gymnasiast** [comment]
You haven't filled in the form properly. Fill them in please. Especially the commit/build is important.

**Comment by Trongsin** [comment]
I apologize, I don't know the information on the form all that well. Where can I find commit/build info?

**Comment by Gymnasiast** [comment]
In the lower left of the title screen, looks a bit like 426e106.

**Comment by Trongsin** [comment]
Thanks! Is there any other information I need?

**Comment by Trongsin** [comment]
Wanted to post a quick follow up message to see if there was anything else I needed information wise.

**Comment by Gymnasiast** [comment]
No, not at this time.
