### ISSUE TITLE
Low performance when ride list window is open

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#5756]
When opening the ride list window, the game grinds to a halt. This is due to the recent addition of the "ride has track" check that is invoked every tick.

**Comment by pizza2004** [comment]
I was wondering.  If you build a ride but fail to add any track, this change makes it not appear in the rides list, so how would you select it to delete it?  Or does it automatically delete itself once you leave construction?

**Comment by IntelOrca** [comment]
> Or does it automatically delete itself once you leave construction?

Yes

**Comment by Gymnasiast** [comment]
Would checking for overall_view != 0xFFFF suffice?

**Comment by rwjuk** [comment]
@Gymnasiast what does `ride->overall_view` mean?

**Comment by Gymnasiast** [comment]
It sets the coordinates that are used when you select 'Overall view' in the first tab (where you can switch between Overall view, Station 1, Station 2, Train 1, Train 2, etc.).

**Comment by rwjuk** [comment]
@Gymnasiast Oooohhh... can we rely on that being 0xFFFF (and not, say, some junk value) if a ride has no non-ghost elements? I think I've found a solution, but if that works...

**Comment by IntelOrca** [comment]
It might not be 0xFFFF if you remove the original piece, but still in construction mode.
