### ISSUE TITLE
Crash when closing ride window

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#5759]
**OS:** Windows 8.1
**Version:** 0.0.8
**Commit/Build:** cb28381

Sometimes when clicking the X button on a window, the game crashes.
Possibly related to crashes when clicking the rotate map button.

**Steps to reproduce:**
1. Build your park, minding your own business
2. Close a ride window via the X button
3. Boom. Crash.

**Dump file**

tba

**Comment by IntelOrca** [comment]
Can you upload the saved game that crashed?

**Comment by spacek531** [comment]
It's inconsistent and I have yet to reproduce it. When I do (and manage to grab the dump file) I will upload it.

**Comment by IntelOrca** [comment]
Closing as it can't be solved without a dump or reliable steps to reproduce. Hopefully its the same issue as #5795.
