### ISSUE TITLE
.parkseq files cannot be played if the sequence is in a subfolder

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#5770]
**OS:** 0.0.8
**Version:** windows 8.1
**Commit/Build:** aec214c

If OpenRCT2 is set to play a .parkseq sequence and the .parkseq sequence is stored in a subfolder of the zip, OpenRCT2 will not play the selected sequence but the sequence one below in the list of sequences. Specifically, this list:

![image](https://user-images.githubusercontent.com/3454156/27805271-a23829ac-5fe8-11e7-945b-e68af4fafffe.png)

Structure of playable .parkseq:
`sequence.parkseq
-\script.txt
`

Structure of unplayable .parkseq:
`sequence.parkseq
-\somefolder
--\script.txt
`

.parkseq files have the potential to store multiple title sequences, which OpenRCT2 does not yet recognize (it shows the name of the .parkseq file), so playing parks in subfolders of .parkseq files requires some additional searching. The quickest fix I can think of is to discard the .parkseq file if no `script.txt` is found in the root, _or_ automatically set the sequence to the RCT1/OpenRCT2 fallback instead of playing the next script in line.

[possible to play.zip](https://github.com/OpenRCT2/OpenRCT2/files/1120393/possible.to.play.zip)
[impossible to play.zip](https://github.com/OpenRCT2/OpenRCT2/files/1120394/impossible.to.play.zip)

**Comment by IntelOrca** [comment]
Well I think this is expected behaviour, although not obvious what is happening. The script.txt must be in the root of the zip archive otherwise it cannot be played. If a title sequence cannot be played, it automatically changes to the next one in the list.

**Comment by spacek531** [comment]
Can we change the behavior to set it to the default OpenRCT2 sequence then? The catch behavior is a little odd.
