### ISSUE TITLE
peeps and ride trains are not drawn the first frame when a park loads

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#5779]
**OS:** windows 8.1
**Version:** 0.0.8
**Commit/Build:** Obe6OO3

Peeps, ride trains, balloons, and probably a few other objects are not drawn the first frame when a park loads. This is rather jarring in title sequences and forms almost a flash frame, especially when you have poor framerate like me.

Example of issue: https://gfycat.com/InsistentEminentEastrussiancoursinghounds

**Comment by IntelOrca** [comment]
Does this happen if you turn off "uncapped FPS"?

**Comment by spacek531** [comment]
it does, but holy time dilation batman

**Comment by IntelOrca** [comment]
It will be a similar issue to this then: #2104

**Comment by spacek531** [comment]
I downloaded the 0.0.5 version to compare and it is not happening even with uncapped FPS enabled.

**Comment by spacek531** [comment]
This doesn't seem to happen any more.
