### ISSUE TITLE
FR: 1/100,000 guests is Voldemort, and Drowning them causes every ride in the park to explode.

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#5780]
An important feature yet to be discussed for 0.1.0.

**Comment by spacek531** [comment]
Praise Ted

**Comment by Gymnasiast** [comment]
![facepalm](http://i.imgur.com/iWKad22r.jpg)

**Comment by spacek531** [comment]
FR actually stands for Friend Request

**Comment by PFCKrutonium** [comment]
[*Bows*](https://gitter.im/OpenRCT2/OpenRCT2/non-dev?at=595b52274bcd78af567325b2)
