### ISSUE TITLE
Twitch integration enhancements

### ISSUE THREAD

**Issue by Chaosmeister** [OpenRCT2/OpenRCT2#5782]
- [ ] add a message to fetch the status of your own visitor ("!status") like hunger/thirst/money etc.
with the option to whisper it to the requester so the chat window isn't cluttered.
- [ ] add an option to (somehow) limit the number of messages generated by followed twitch park visitors.
also limit the amount of messages generated by the "!news" message.
- [ ] if possible: receive case sensitive names from the twitch chat. (my nick `T0mmes` is changed to `t0mmes` for the visitor name).

**Comment by Gymnasiast** [comment]
We removed the Twitch integration.

If these requests are still applicable, you could propose them to the https://github.com/oli414/StreamIntegrationPlugin repository instead.
