### ISSUE TITLE
Opening an incomplete ride moves the viewport to unrelated place

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#5787]
**OS:** Linux
**Commit/Build:** 705b8f2ff

1. Open a park
2. Create a rollercoaster, place a few tracks, entrance and exit. Do not close the track circuit.
3. Try opening the park
4. Observe main viewport being taken to irrelevant place

**Recording:**
https://gfycat.com/CelebratedFocusedGull

**Save game:**
[aaa.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/1123034/aaa.sv6.txt)

**Comment by IntelOrca** [comment]
What ride causes this within the saved game?

**Comment by janisozaur** [comment]
There isn't one, the save is a map that was loaded before I started building such a ride.

**Comment by IntelOrca** [comment]
This is caused by the front of the station being a ghost element.
