### ISSUE TITLE
Empty scenarioname becomes invisible list entry

### ISSUE THREAD

**Issue by Chaosmeister** [OpenRCT2/OpenRCT2#5788]
**OS:** [Windows 10]
**Version:** [0.0.8]
**Commit/Build:** [705b8f2fffed676f16e3541c2e6c45ed2ff002d9]

**Steps to reproduce:**

1. create a scenario without setting a name or extract the appended scenario to your scenario folder. ⬇️  
2. find the scenario in the "choose scenario"-window

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/13346344/27842487-c5c09fda-610a-11e7-955b-fdafc11a5c74.png)
![image](https://user-images.githubusercontent.com/13346344/27842445-78cb495a-610a-11e7-83d1-86fa9324bdcb.png)

**Save game:**
[Sandbox.zip](https://github.com/OpenRCT2/OpenRCT2/files/1123040/Sandbox.zip)

**Comment by kylegarza21** [comment]
Taking a look :)
