### ISSUE TITLE
The game freezes with maptile (0,0) on screen after an autosave

### ISSUE THREAD

**Issue by Chaosmeister** [OpenRCT2/OpenRCT2#5795]
**OS:** [Windows 10]
**Version:** [0.0.8]
**Commit/Build:** [4e4022d693d4149eddea906ec71f22ddc626411f]

If the appended scenario is loaded, an autosave has occurred and maptile (0,0) is in the active viewport, the game freezes

**Steps to reproduce:**
1. load the appended scenario.
2. wait for an autosave.
3. pan the camera to the top of the map.

**Save game:**
[Sandbox.zip](https://github.com/OpenRCT2/OpenRCT2/files/1123149/Sandbox.zip)

**Comment by spacek531** [comment]
I got a crash on autosave, but I wasn't near the map edge, so it might not be related:

https://www.dropbox.com/s/09ikwgfmzmlhuss/openrct2%20crash%20on%20autosave.7z?dl=0

**Comment by janisozaur** [comment]
#5801 got reverted until some improvements are implemented
