### ISSUE TITLE
crash in title while window out of focus

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#5798]
**OS:** windows 8.1
**Version:** 0.0.8
**Commit/Build:** 68c819c

I opened OpenRCT2 and was doing some stuff in git when I heard the windows error sound and I saw this:

![image](https://user-images.githubusercontent.com/3454156/27852480-31a41d7c-6114-11e7-9908-3e1c80838024.png)

Why it crashed is unknown because I have never gotten a crash here before and I didn't see anything out of the ordinary because I was doing things in other programs.

dump file: [title crash unknown reason.zip](https://github.com/OpenRCT2/OpenRCT2/files/1123740/title.crash.unknown.reason.zip)

**Comment by Nubbie** [comment]
Had issues open the dumpfile and getting kernalbase.dll to work with it, but here is the rest that could be recovered
**Error message;**
Unhandled exception at 0x00007FFDAC9495FC in fba9d7e8-d067-4d21-ac26-3f81a7f3eee9(68c819c_x86-64).dmp: Microsoft C++ exception: IOException at memory location 0x000000E0A384F428.

**Call stack (breakpoint openrct2.dll!FileStream::FileStream);**
```
 	KERNELBASE.dll!RaiseException()	Unknown
 	[External Code]	
>	openrct2.dll!FileStream::FileStream(const char * path=0x000000e0a384f490, int fileMode) Line 89	C++
 	openrct2.dll!TitleSequenceGetParkHandle(TitleSequence * seq, unsigned __int64 index) Line 158	C++
 	openrct2.dll!TitleSequencePlayer::ExecuteCommand(const TitleCommand * command) Line 292	C++
 	openrct2.dll!TitleSequencePlayer::Update() Line 143	C++
 	openrct2.dll!title_update() Line 183	C++
 	openrct2.dll!rct2_update(...) Line 426	C
 	openrct2.dll!OpenRCT2::Context::RunVariableFrame() Line 422	C++
 	openrct2.dll!OpenRCT2::Context::RunGameLoop() Line 360	C++
 	openrct2.dll!OpenRCT2::Context::RunOpenRCT2(int argc=-1549409152, char * * argv=0x0000000001040800) Line 136	C++
 	openrct2.dll!NormalisedMain(int argc=1, char * * argv=0x000000e0a39fb8a0) Line 65	C++
 	openrct2.dll!LaunchOpenRCT2(int argc, wchar_t * * argvW) Line 55	C++
 	[External Code]	
```

**Locals (breakpoint openrct2.dll!FileStream::FileStream);**
```
+		this	0x000000e0aebf3240 {_file=??? _ownsFilePtr=??? _canRead=??? ...}	FileStream *
		fileMode	Variable is optimized away and not available.	
		mode	Variable is optimized away and not available.	
+		modeW	0x000000e0af83d9c0 <Error reading characters of string.>	wchar_t *
+		path	0x000000e0a384f490 "C:\\Users\\pat\\Documents\\OpenRCT2\\title sequences\\Spacek 008 Sequence fork 1\\Ill Paradise timer base.sv6"	const char *
+		pathW	0x000000e0af811210 <Error reading characters of string.>	wchar_t *
```

**Autos  (breakpoint openrct2.dll!FileStream::FileStream);**
```
-		path	0x000000e0a384f490 "C:\\Users\\pat\\Documents\\OpenRCT2\\title sequences\\Spacek 008 Sequence fork 1\\Ill Paradise timer base.sv6"	const char *
			67 'C'	const char
-		this	0x000000e0aebf3240 {_file=??? _ownsFilePtr=??? _canRead=??? ...}	FileStream *
+		IStream	{...}	IStream
		_file	<Unable to read memory>	
		_ownsFilePtr	<Unable to read memory>	
		_canRead	<Unable to read memory>	
		_canWrite	<Unable to read memory>	
		_disposed	<Unable to read memory>	
		_fileSize	<Unable to read memory>	
```

**Comment by Chaosmeister** [comment]
The referenced issue has the same error.
I'm pretty sure it's the same crash.

**Comment by tupaschoal** [comment]
Linked issue, which seems to be the same, has been closed, so I'm assuming this has been fixed as well, let us know if you can reproduce it still
