### ISSUE TITLE
Crash when opening server in command after 68c819c

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#5800]
**OS:** Windows 10
**Version:** 0.0.8
**Commit/Build:** 68c819c

Game crashes if I open multiplay server via command window.
3151b2b has no such issue.
I used Mega Park.sc6 that is saved when it is just opened the Mega Park scenario.
It is also crashes whatever map I use.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Open a command line(Win+R)
2. Type ``(openrct2 path)/openrct2 host "%USERPROFILE%%\Documents\OpenRCT2\save\Mega Park.sv6" --port 11753 --password (some password)``
3. It crashes with error like below:
![image](https://user-images.githubusercontent.com/10726524/27875585-ac5a92d2-61ee-11e7-9fb8-38aa8206f599.png)

**Dump file**
[635ac8be-ddee-48e3-807c-da89833e3119.zip](https://github.com/OpenRCT2/OpenRCT2/files/1125413/635ac8be-ddee-48e3-807c-da89833e3119.zip)

**Screenshots / Video:**

**Save game:**
[Mega Park.zip](https://github.com/OpenRCT2/OpenRCT2/files/1125420/Mega.Park.zip)

**Comment by PFCKrutonium** [comment]
I was about to report this, same issue, here is my dump: https://pastebin.com/raw/ciPqX2L6

**Comment by PFCKrutonium** [comment]
[Bumbly Beach.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/1125424/Bumbly.Beach.sv6.txt)
