### ISSUE TITLE
Capped game speed malfunctioning

### ISSUE THREAD

**Issue by jensj12** [OpenRCT2/OpenRCT2#5810]
**OS:** Windows 10
**Version:** 0.0.8
**Commit/Build:** 0d554ed

When uncap fps is disabled, the game has problems keeping the correct game speed. Every second or so, the game speed spikes to ~60. This results in the simulation being too fast and everything sometimes speeds up for a moment.
My machine has no problems running the game, uncapping fps gets me to 100+ on average.
So far, I can reproduce it on all parks I've opened.

**Steps to reproduce:**
1.  Disable uncap fps

**Screenshots / Video:**
https://youtu.be/hT169oEQ3z4

**Comment by jensj12** [comment]
#5848 fixed this during normal gameplay, but after loading a save (or probably anything that blocks the game for some time) the game goes hyper-speed for some time. Easily noticable in the second park of the title sequence, as it starts with a moving coaster train in the view.

**Comment by ZehM4tt** [comment]
When you say some time how long are we talking, 1-2 seconds?

**Comment by jensj12** [comment]
About a second. Here's a video: https://youtu.be/f_f6Z3zByeg

**Comment by jensj12** [comment]
Fixed by #5848 and #5862.
