### ISSUE TITLE
Cannot host multiplayer on releases after aec214c

### ISSUE THREAD

**Issue by mozar99** [OpenRCT2/OpenRCT2#5811]
**OS:** [e.g. Server 2012]
**Version:** [e.g. 0.0.8]
**Commit/Build:** [e.g. ae3bc61]

A few days ago I upgraded my multiplayer servers to aec214c without any issues. Today I upgraded to ae3bc61 and now it is not possible to connect to the servers. They will not show up on the master server list and when I attempt to manually connect to them via IP address the game just reports "no data" . When I revert back to aec214c everything works again but since it's on an older network version users will not connect.

When I load the saved map on ae3bc61 in single player mode it works fine. This issue only happens when attempting to host a multiplayer game.

- [ ] Reproducible in RCT2 (vanilla)?
- [x ] Multiplayer?

**Steps to reproduce:**
1. 
2.

**Comment by rwjuk** [comment]
That's strange, as I'm not sure how adding null guards (which is what ae3bc61 does) would cause this.

**Comment by mozar99** [comment]
The issue could have been caused any release between aec214c and ae3bc61. I listed them below. To ensure maximum up time on the servers I only upgrade when there is a new network version.

develop 0.0.8 build 68c819c	1 day ago
develop	0.0.8 build 3151b2b 1 day ago
develop	0.0.8 build 4e4022d 1 day ago
develop	0.0.8 build 705ad7c	1 day ago
develop	0.0.8 build a558423	1 day ago
develop	0.0.8 build 705b8f2	1 day ago
develop	0.0.8 build b0fece0	2 days ago
develop	0.0.8 build 5698796	2 days ago
develop	0.0.8 build 0aaff43	2 days ago
develop	0.0.8 build c7de74f	2 days ago
develop	0.0.8 build 0be6003 2 days ago
develop	0.0.8 build 048c543	2 days ago
develop	0.0.8 build 0422699 2 days ago

**Comment by rwjuk** [comment]
Ahhhhh I missed that! Thank you!

**Comment by janisozaur** [comment]
aec214c...ae3bc61

**Comment by rwjuk** [comment]
@mozar99 Does it happen with any save game or just a specific one?

**Comment by mozar99** [comment]
@rwjuk It happens with multiple saved games with different objects/rides in them.

**Comment by mozar99** [comment]
So out of the ~10 servers I host only one works on the newer releases. The one that does work is mostly a blank map. This makes me think its something to do with custom content, but even the map that does work has custom content in it. I have test with and without "export plug-in objects with saved games" but it does not seem to matter

[maps.zip](https://github.com/OpenRCT2/OpenRCT2/files/1128347/maps.zip)

**Comment by rwjuk** [comment]
Excellent - thanks

**Comment by rwjuk** [comment]
@mozar99 Can you export those with objects? I can't load them.

**Comment by mozar99** [comment]
Same maps with export plug-in objects with saved games. 

[Desktop.zip](https://github.com/OpenRCT2/OpenRCT2/files/1128463/Desktop.zip)

**Comment by rwjuk** [comment]
@mozar99 On the latest `develop` build, I cannot replicate this. If I start a server with the 'does not work' build and then try to connect to it, it works. Could someone else try and see if they can reproduce the bug?

**Comment by mozar99** [comment]
not sure if it matters but these are being run in headless mode. Did the format in any of the .json files recently change? Is there a way I can turn on verbose logging on a headless server?

**Comment by mozar99** [comment]
could it have anything to do with me running multiple instances of openrct at the same time on the same computer? 

![serverlist](https://user-images.githubusercontent.com/29951295/27927094-e50a80ac-6247-11e7-8083-95f6b1beb972.png)

**Comment by mozar99** [comment]
not sure what the issue was but everything is now working with network version 8-30, thank you devs
