### ISSUE TITLE
OpenRCT2 doesn't start up

### ISSUE THREAD

**Issue by Gammadivided** [OpenRCT2/OpenRCT2#5816]
**OS:** Windows 7
**Version:** 0.0.8
**Commit/Build:** f6cb731

When opening the game using the launcher, it does not start up, staying at a blank white screen. If I try to interact with it, it doesn't respond. I cannot provide a save file or a dump file as the game doesn't crash, it simply doesn't start. I've tested it with multiple versions, including the latest "Stable" build.

**Steps to reproduce:**
1. Open the game using the Launcher.

**Screenshots / Video:**

![not responding](https://user-images.githubusercontent.com/11410845/27938665-dfc9c4c4-6295-11e7-9e02-de38a40ae999.png)

**Comment by spacek531** [comment]
I've sometimes experienced this. Did you install or change any scenery or ride DAT files? It might be refreshing the list which can take a long time if you have a lot.

**Comment by Gammadivided** [comment]
No, I didn't add or remove any objects or rides. The game behaves differently for me when doing that, so it's something different causing this.

**Comment by Gymnasiast** [comment]
Open a command prompt, `cd` to OpenRCT2's directory and do
```
openrct2 --verbose
```
Copy and paste the output.

**Comment by janisozaur** [comment]
@Gammadivided can you test the builds from #5812 ?

**Comment by Gammadivided** [comment]
@Gymnasiast I've tried it and it outputs... nothing. Command prompt doesn't show anything, and the game just opens like normal (and doesn't start up).

@janisozaur I tested the most recent build (I presume that's post-#5812) and it still doesn't work. If you mean something different, please elaborate, as I'm still a bit lost with GitHub.

**Comment by rwjuk** [comment]
@Gammadivided Okay, we'll need to do some more in-depth diagnostics. Could you try the following please?

1. Download Process Monitor: https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx
2. Run it.
3. Run OpenRCT2 and let it lock up (wait about 10 seconds after it locks up before moving to the next step).
4. In Process Monitor, go to "File > Save".
5. Leave all options at their default setting, save the PML file somewhere and upload it here.

**Comment by Gammadivided** [comment]
UPDATE: I tried what Gymnasiast told me again and the game started up after outputting a lot of text. Sadly, I closed the window down without thinking twice and I can't paste the output anymore. It seemed to be loading objects, so maybe @spacek531 was right after all.

**Comment by Gymnasiast** [comment]
We have had people before who too quickly assumed the game was locked up. Basically, if this happens again, wait at least a few minutes.
