### ISSUE TITLE
tunnel portal drawing regression

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#5819]
**Commit/Build:** one of the last 0.0.8 builds

The steep-slope-to-vertical piece is allowed to stick out 2 units above ground in RCT2. OpenRCT2 0.0.5 draws portals for this correctly:
![image](https://user-images.githubusercontent.com/3454156/27957370-0dcc0228-62d3-11e7-8854-e4b8d71ed2b1.png)

0.0.8 (and by extension 0.1.0, in the beginning) does not draw this correctly:
![image](https://user-images.githubusercontent.com/3454156/27957404-346e4ada-62d3-11e7-834a-6e7c3a68ef6a.png)

**Comment by duncanspumpkin** [comment]
Its not really a regression its just been wrong since it was implemented.
