### ISSUE TITLE
Add console command to strip out unused objects

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#5820]

**Comment by rwjuk** [comment]
One use case: stripping objects from parks used in the title sequence makes them load faster.

**Comment by Gymnasiast** [comment]
It will still support commands like these, unless I'm _very_ mistaken. (Can you confirm this @IntelOrca ?)

**Comment by rwjuk** [comment]
Oh in that case yeah, a console command is fine.

**Comment by IntelOrca** [comment]
Duplicate of #1329

**Comment by rwjuk** [comment]
Closing as dupe of #1329.
