### ISSUE TITLE
Feature request: replace objects that are in use

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#5821]
The in game object selector allows you to check and uncheck objects in the savegame, but only if those objects are not in use yet. What Parkdat offers is swapping objects, even the ones that are in use. This is very useful to replace bugged objects by improved ones, adjusting foliage by playing with tree types, adding new objects after having hit the limit, or whatever. You can also use it open savegames that have objects in use that no one (or just you) has. You can make parks that use the expansions accessible again. There are many applications for this, more than I mentioned, and I use it a lot. It would be great.

edit: another important application: changing scenery tabs. If you do that in the object selector, it automatically (de)selects the objects in that tab too. Can mess up your bench bad.

**Comment by xp4xbox** [comment]
Would give another reason to move away from SV6.

**Comment by Liampie** [comment]
Unless OpenRCT doesn't add this option it's a reason to NOT move away from SV6, if anything.

**Comment by jensj12** [comment]
Adding this is not a reason to keep SV6. Still I'd like to see this feature, including an option to replace items you don't have by some you do have when opening a save.

**Comment by Gymnasiast** [comment]
This is not related to SV6. Please keep on-topic.

**Comment by Nubbie** [comment]
#2961 duplicate
