### ISSUE TITLE
Feature request: being able to raise/lower content on multiple tiles at the same time

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#5822]
See title. This is something that you can do with the 8cars trainer: you would raise/lower (or remove!) on tiles with a specific land type by any amount you would like. You could choose to raise/lower land, paths, rides, banners, walls, small scenery, all of them, or combinations. You could also choose one or multiple land types on which the trainer would perform the action. If you wanted to raise an entire section of a park, or a building, whatever, you would mark that area with a weird land type like purple grid. In 8cars you would say something along the lines of 'raise all land, paths, scenery and rides on tiles that use the purple grid texture'. Very useful. The tile inspector can only raise one thing at a time, not tens of thousands with a single click.

**Comment by xp4xbox** [comment]
Related to #5149
