### ISSUE TITLE
Feature request: being able to change operating mode without closing the ride

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#5824]
See title.

**Comment by Nubbie** [comment]
Why?

**Comment by xp4xbox** [comment]
Duplicate https://github.com/OpenRCT2/OpenRCT2/issues/5608

**Comment by Liampie** [comment]
Thanks. Apparantly I knew about this when it was first incorporated, but it slipped from my mind. I think it's very arbtirary what functions get hidden in the console, and which ones get a place in the GUI. Which is WHY it slipped from my mind... Anyway, this can be closed! Sorry for another brainfart

**Comment by rwjuk** [comment]
#5384 already implemented it.
