### ISSUE TITLE
Feature request: count map data/knowing how far you're off the limits you are

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#5826]
I know that you want to get rid of the limits at some point, but we're not quite there yet. It would be nice if you had a window somewhere that showed how much limited things you're using. Something like this:

Object limit: 56344/196608 (or whatever the limit was)
Ride limit: 34/255
Sprite limit: something/something
Banner limit: something/something
Staff limit:  something/something

Whatever. That kind of stuff.

**Comment by IntelOrca** [comment]
Should be made available via scripting API.
A dedicated window can be plug-in.

**Comment by janisozaur** [comment]
@IntelOrca I think with new roadmap to do the new format first and script engine afterwards this should be addressed earlier. It can still be moved to plugin later on.

**Comment by oli414** [comment]
This issue can be closed as it has been added with #6368

**Comment by janisozaur** [comment]
@IntelOrca close it or leave re-labelled as plugin?
