### ISSUE TITLE
Feature request: change guest's clothes colours

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#5827]
The RCT1 savegame modifer would allow you to change all the guest's clothes to colours of your choosing. Not very useful, but something similar in OpenRCT would be awesome. For example, giving every peep a salmon pink shirt would make it appear as if they're wearing swimming gear. For this, the pants and shirts colours should be modifiable separately.

**Comment by xp4xbox** [comment]
Would be good for a console command.
