### ISSUE TITLE
Feature request: modify cluster tool size

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#5828]
See title. It would be great for doing foliage in smaller spaces for example. Someone just asked this in the stream chat and it has been talked about before on multiple occasions!

**Comment by IntelOrca** [comment]
**Related:** #1387

**Comment by rwjuk** [comment]
This is certainly something the scripting system would allow you to do, but I can also see the value in implementing this in the core game. Thoughts?

**Comment by Liampie** [comment]
Thought: the vast majority of players do not want to bother with a scripting system. The current clutter tool has an arbtirary size, it would make sense if the size was adjustable same as the land tool and the water tool. Imagine if the land tool was always 15x15 tiles... To me it's no question that this is a function that belongs in the actual game! :)

**Comment by IntelOrca** [comment]
> the vast majority of players do not want to bother with a scripting system

@Liampie we will make it easy to just download other people's scripts that add such features

**Comment by AaronVanGeffen** [comment]
Implemented by #10357.
