### ISSUE TITLE
Feature request: remove unused objects

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#5830]
Rather than removing unused objects one by one, which takes a long time, a button to do all at once would be very welcome.

At New Element we always remove the unused objects for releases to reduce the file size (using Parkdat), but OpenRCT has been changing something in the savegames so that sometimes we can't do this anymore without breaking the savegame. I don't understand how it happens, but OpenRCT2 having this functionality would solve it. I'm sure many people would find this useful, far beyond just the NE management team!

**Comment by spacek531** [comment]
I was actually talking about my workflow for prepping the parks for the sequence which involved parkdat->remove unused items. Two devs were practically tripping over each other to implement it, so I think there is a very good chance that this will come early in 0.1.1 development.
