### ISSUE TITLE
Deleted saves keep comming back?

### ISSUE THREAD

**Issue by Anymal104** [OpenRCT2/OpenRCT2#5831]
**OS:** [Windows]
**Version:** [0.0.8]
**Commit/Build:** [22a936b]
**Type** [x64]

I was sorting some off my saves in the Openrct2 folder, and put some in subfiles and deleted others I don't need anymore. When I launched Openrct2 the saves where back in the folders... I tried it multiple times, and even cleared my pc's bin. But still the saves came back... I guess the game cashes the saves and puts them back in the folder from it? (Important: The saves I deleted weren't in the original rct2 folders)

- [Yes] Reproducible in RCT2 (vanilla)?
- [No] Multiplayer?

**Steps to reproduce:**
1. Have a save from Openrct2 you can delete;
2. Delete it in the Openrct2 folder (in the Documents folder);
3. Start up Openrct2
4. The deleted file is back in the folder of Openrct2

**Comment by IntelOrca** [comment]
These saves are copied from your RCT2 install. Delete them from there.

**Comment by Anymal104** [comment]
Oh derp... Sowwee
