### ISSUE TITLE
Feature request: tile inspector window automatically resizes when you click on a tile

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#5832]
The tile inspector shows only four or five lines by default. Most tiles you click on have much more than four of five things on them... It's very annoying to resize the window size all the time. Either this, or a larger default window size. Whatever it is now, it's not enough.

edit: Elaboration: my memory was a bit fuzzy when I was writing this but I just checked the tile inspector again and it's only after having clicked a tile that 75% of the window becomes dedicated to buttons and controls, with the list of objects being reduced to about 6 objects/lines. Which is awful if you want to mess with the order of the objects and there are 40 of them. That's the real issue here: the balance between the controls and the table of objects is very off. This should auto-resize!

**Comment by spacek531** [comment]
I think it shouldn't resize so that it's larger than your window size with a bit of padding so you can resize it further without issue.

**Comment by Liampie** [comment]
Naturally, spacek! The tile inspector window is very small anyway, so it could be at least doubled or tripled before it starts coming close the game's window boundaries.

**Comment by xp4xbox** [comment]
For me its a good size because I have a small 13'' screen.

**Comment by ryanmahan** [comment]
Has this issue been resolved? Looking to make my first contribution and couldn't replicate this. @Liampie what is your screen res and size?

**Comment by Patrik356b** [comment]
@xp4xbox anything reasonably modern should have enough native resolution to allow a larger window, but just like @Liampie you are going to be limited by the scaling assuming you are running the recommended resolution in windows

**Comment by xp4xbox** [comment]
I have an actual monitor now, so its no problem.
