### ISSUE TITLE
Feature request: open the game by double clicking a savegame (edit: nevermind)

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#5833]
I have not managed to make OpenRCT the default program to open savegame files with. If I want to view a park I have to open the game first and then manually browse to the savegame file. Double clicking is much more convenient, so you can also open parks right away when you download them in a zip or something.

**Comment by spacek531** [comment]
I believe a PR recently was added that allowed file association with OpenRCT2: https://github.com/OpenRCT2/OpenRCT2/pull/5754

**Comment by xp4xbox** [comment]
@Liampie in windows, you just select open with, and check the box always use this program to open this type of file or something.

**Comment by Liampie** [comment]
Okay, I don't know why I couldn't get this to work last time I checked. Brainfart I guess. It's fixed now, thanks for the wake-up call :P
