### ISSUE TITLE
Headless hosting

### ISSUE THREAD

**Issue by alecward92** [OpenRCT2/OpenRCT2#5841]
**OS:** WIndows 7
**Version:** 0.0.8
**Commit/Build:** ac81072

So I decided I wanted to host 2 servers on one PC. Ports are forwarded properly as they are join-able from an outside source. But one thing that is different then the traditional way is this "studder" effect that keeps making objects jumpy. Anyone who joins sees the same issue and it's rather annoying to play on. As I'm typing, I took one down and have my primary running ((FREEDOM) Main). Still the same in headless. When I kill headless and run the traditional way, no studder. or issues. I'll attach my config.ini and .bat files that I am using for this since I may have a wrong setting or something. I'll leave it running for any Dev who wants to join and see for the next few hours.
Thanks!

[config.zip](https://github.com/OpenRCT2/OpenRCT2/files/1133477/config.zip)

**Comment by janisozaur** [comment]
@PFCKrutonium you faced the same issue, right? Any more insights?

**Comment by ZehM4tt** [comment]
I've noticed two things that affect this. 
1. The headless server uses RunFixedFrame, commenting out the condition to run variable frame removes the stutter, assuming uncap fps is set.
2. When variable frame is used the uncap fps play the next role, having it set removes the stutter.

I'm not exactly sure how this affects the updates yet, perhaps @IntelOrca knows something I don't.

**Comment by alecward92** [comment]
I take it this isn't something I can just edit in the config file?

**Comment by ZehM4tt** [comment]
Correct

**Comment by PFCKrutonium** [comment]
@janisozaur Nope, one server on the machine, and I was focused completely on the broken sprites.

**Comment by janisozaur** [comment]
@alecward92 is this still an issue? There were some fixes recently that should've taken care of this.

**Comment by alecward92** [comment]
No issues here! Smooth as butter! Thanks a bunch :)
