### ISSUE TITLE
New 'missing scenery' window that pops up when you try to load a savegame can't be closed with a hotkey

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#5849]
I always use backspace, the default hotkey, to close any windows. It doesn't work for this one.

edit:

version 0.0.8 ba2f129 in windows 8

**Comment by xp4xbox** [comment]
@Liampie did you check the keyboard shortcuts in the menu?

**Comment by Liampie** [comment]
What should I check? The hotkey works for every other window.
