### ISSUE TITLE
Unable to run on Wine on Mac OSX due to a missing libstdc++-6

### ISSUE THREAD

**Issue by mzmiric5** [OpenRCT2/OpenRCT2#585]
It looks like the libstdc++-6.dll which is dynamically linked against in mingw32 is no longer shipped as part of wine-utils in new wine (at least for mac osx). 

When running `wine openrct2.exe` the following error is returned:
`err:module:import_dll Library libstdc++-6.dll (which is needed by L"Z:\\Users\\miso\\gitHub\\OpenRCT2\\openrct2.dll") not found
err:module:import_dll Library openrct2.dll (which is needed by L"Z:\\Users\\miso\\gitHub\\OpenRCT2\\openrct2.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"Z:\\Users\\miso\\gitHub\\OpenRCT2\\openrct2.exe" failed, status c0000135`

This can be resolved by simply statically linking to that lib during the build process.

**Comment by RollingStar** [comment]
@mzmiric5 I encounter the same issue that KamilSJaron encountered.

Linux Mint MATE 17.2 x64 ([full log](http://pastebin.com/hXk32Fhf)). I think I have the DLL (I downloaded it separately), but I don't know where it should go.

    wine openrct2.exe
    err:module:import_dll Loading library libwinpthread-1.dll (which is needed by L"F:\\openrct2.dll") failed (error c000007b).
    err:module:import_dll Library openrct2.dll (which is needed by L"F:\\openrct2.exe") not found
    err:module:LdrInitializeThunk Main exe initialization for L"F:\\openrct2.exe" failed, status c0000135

**Comment by mzmiric5** [comment]
@RollingStar hmm, that's strange, what version r u running, are you building from source and is the install working correctly for you? I would recommend running ./clean.sh and then ./install.sh prior to running ./build.sh if you are building from source
