### ISSUE TITLE
Ride preview shadow flickers when trying to build on uneven terrain or in the air

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#5865]
**OS:** [Windows 10]
**Version:** [0.0.8]
**Commit/Build:** [ae282f7]

The ride preview shadow flickers when the cursor isn't on a tile with flat terrain. See [this video](https://www.youtube.com/watch?v=LuYb_74RSuU&feature=youtu.be) for what I mean exactly. I only noticed it today, so it must be a new bug.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Do what I did in the video.

**Comment by Patrik356b** [comment]
noticed this too on 250a66c today

**Comment by rwjuk** [comment]
Video of this bug courtesy of @PFCKrutonium - https://youtu.be/dUr7ewO-bOw

**Comment by PFCKrutonium** [comment]
It's flashing at about the framerate of the game, I think.

**Comment by zsilencer** [comment]
Regression caused by 60bf5083fc1b077e7ece8ed0e3dcacc4e8d2bbba
