### ISSUE TITLE
Sprites twitch when the game is paused

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#5866]
**OS:** Linux
**Version:** 0.0.8
**Commit/Build:** 250a66c45f7585ad3ea42652f94c586639320127

Sprites twitch when the game is paused and uncap FPS is enabled.

**Comment by rwjuk** [comment]
Regression in #5848 / a8af3c767067ade2a985363055a3a30baba6fbad. Tagging @ZehM4tt

**Comment by Margen67** [comment]
I also notice this in multiplayer even when the server isn't paused.

**OS:** Windows 10 Pro x64
**Version:** 0.0.8
**Commit/Build:** https://github.com/OpenRCT2/OpenRCT2/commit/ae282f782ef5669a7996687c021b1a255804241a
