### ISSUE TITLE
Apparently unused ride types?

### ISSUE THREAD

**Issue by X123M3-256** [OpenRCT2/OpenRCT2#5871]
I was looking at the ride code and I noticed [several ride types](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/ride/ride.h#L561) that appear to be unused. The only place they are referenced outside of a comment is in [this function](https://github.com/OpenRCT2/OpenRCT2/blob/23882ae7a63b6c5470b26dc65acca920b763a0f2/src/openrct2/ride/ride.c#L8529-L8627) which doesn't seem to do much.

I was wondering if there's a reason these ride types are here? I thought that all the ride types were in use.

**Comment by IntelOrca** [comment]
In RCT1, the all the shops and stalls used to be separate ride types. These unused numbers are those ride types.

**Comment by Gymnasiast** [comment]
Some slots of RCT1 shops have been filled, though.

**Comment by IntelOrca** [comment]
@Gymnasiast All I am saying is that all the empty slots are shops or stalls in RCT1 - its not a coincidence.

**Comment by X123M3-256** [comment]
Are these slots needed for compatibility with RCT1 save files or could they be used for new ride types?

**Comment by Gymnasiast** [comment]
@IntelOrca I know, it was an addition to your comment.

@X123M3-256 They're not needed, they were most likely left open for ease of converting.

**Comment by X123M3-256** [comment]
Do you guys want to keep them open? If I were to submit a PR that adds a new track type in one of these slots, would it be rejected?

**Comment by Gymnasiast** [comment]
1) No, we don't want to keep them open.
2) I wouldn't. But I'd like Ted's confirmation here.

**Comment by IntelOrca** [comment]
A new track type? This would need a lot of discussion - I am not sure we would even want to consider than until we have a new save format.
