### ISSUE TITLE
Title squence flashes through the the openrct2 script on 250a66c

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#5874]
So i just fetched the latest version and first noticed a different issue #5873 and didn't notice the title sequence was reset. When i switched it back to openrct2 it flickers/flashes through every viewpoint rapidly.

https://drive.google.com/file/d/0B6GFAyrg1QhycmdZQ3o5ZnRNNU0/view?usp=sharing

OpenRCT2-0.0.8-develop- 250a66c -windows-x64.exe
OS: Windows 8.1

On e7eb5f7 the title screen was fine

**Comment by IntelOrca** [comment]
You need to update your title sequences. Run `msbuild openrct2.proj /t:DownloadTitleSequences`

**Comment by janisozaur** [comment]
I've seen it happen in released builds, at least on Windows

**Comment by janisozaur** [comment]
https://www.twitch.tv/videos/158099404 1:37:00

**Comment by Patrik356b** [comment]
that's kinda cumbersome tbh. 

And how is this a non-bug? 
I mean, the update should "update" this too

**Comment by IntelOrca** [comment]
@Patrik356b if you are building the game yourself, you need to run `msbuild openrct2.proj` so that it can check to see if the sequences need updating and update them.

**Comment by Patrik356b** [comment]
@IntelOrca i do NOT build it myself, which is why i'm asking WHY this is a non.-bug?

**Comment by Patrik356b** [comment]
Update: i have tried to manually update the title sequence:
```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Patrik>"c:\program files (x86)\msbuild\14.0\bin\msbuild.exe" D:\openrct2
-develop\openrct2-develop\openrct2.proj /t:DownloadTitleSequences
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 12/7/2017 13:12:17 PM.
Project "D:\openrct2-develop\openrct2-develop\openrct2.proj" on node 1 (Downloa
dTitleSequences target(s)).
DownloadTitleSequences:
  Downloading 'https://github.com/OpenRCT2/title-sequences/releases/download/v0
  .1.0/title-sequence-v0.1.0.zip'.
  Extracting to 'D:\openrct2-develop\openrct2-develop\bin\data\title'.
Done Building Project "D:\openrct2-develop\openrct2-develop\openrct2.proj" (Dow
nloadTitleSequences target(s)).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:06.35
```

Replacing the files in OpenRCT2 install folder, overwriting the old ones did not help.

**Comment by IntelOrca** [comment]
Do you have any title sequences in your `documents/openrct2/title sequences` directory?

**Comment by Patrik356b** [comment]
that folder is empty

**Comment by IntelOrca** [comment]
From your video, it looks like you are running an old title sequence. Can you list all the title sequences you have in your OpenRCT2 install directory?

**Comment by Patrik356b** [comment]
```
C:\Program Files (x86)\OpenRCT2\data\title>dir /s /b
C:\Program Files (x86)\OpenRCT2\data\title\openrct2
C:\Program Files (x86)\OpenRCT2\data\title\openrct2.parkseq
C:\Program Files (x86)\OpenRCT2\data\title\rct1
C:\Program Files (x86)\OpenRCT2\data\title\rct1.parkseq
C:\Program Files (x86)\OpenRCT2\data\title\rct1aa
C:\Program Files (x86)\OpenRCT2\data\title\rct1aa.parkseq
C:\Program Files (x86)\OpenRCT2\data\title\rct1aall
C:\Program Files (x86)\OpenRCT2\data\title\rct1aall.parkseq
C:\Program Files (x86)\OpenRCT2\data\title\rct2
C:\Program Files (x86)\OpenRCT2\data\title\rct2.parkseq
C:\Program Files (x86)\OpenRCT2\data\title\openrct2\Cypress Grove Title.sv6
C:\Program Files (x86)\OpenRCT2\data\title\openrct2\Ill Paradise.sv6
C:\Program Files (x86)\OpenRCT2\data\title\openrct2\script.txt
C:\Program Files (x86)\OpenRCT2\data\title\openrct2\TaCW.sv6
C:\Program Files (x86)\OpenRCT2\data\title\openrct2\Title Sequence Park 1.sv6
C:\Program Files (x86)\OpenRCT2\data\title\rct1\script.txt
C:\Program Files (x86)\OpenRCT2\data\title\rct1aa\script.txt
C:\Program Files (x86)\OpenRCT2\data\title\rct1aall\script.txt
C:\Program Files (x86)\OpenRCT2\data\title\rct2\script.txt
```

this was the easiest way to list them

**Comment by Gymnasiast** [comment]
Hm, it looks as if you have all sequences twice.

Try the following: uninstall OpenRCT2, clear the `C:\Program Files (x86)\OpenRCT2` folder, reinstall OpenRCT2 and see if it persists.

**Comment by Patrik356b** [comment]
That seems to have solved it. Not sure why.

**Comment by IntelOrca** [comment]
@Patrik356b We have changed title sequence scripts to now use milliseconds. This means all title sequences made prior to this upcoming release need amending.

**Comment by Patrik356b** [comment]
Like i said before, the installer SHOULD have updated them. I'm not sure WHY it did not.

**Comment by IntelOrca** [comment]
The installer did update them, but it not delete the old ones - and you still had the old sequence selected.

**Comment by Patrik356b** [comment]
oh, in that case it makes more sense, but is a bit awkward
