### ISSUE TITLE
Leaving bumper cars without building causes assertion

### ISSUE THREAD

**Issue by Juloow** [OpenRCT2/OpenRCT2#5880]
**OS:** Windows 10
**Commit/Build:** 0.1.1 build 3d48754

It's the second time something like that happens to me, I saved my park and quited ORCT2. When I reopened the game, the launcher update to version 0.1.1 build 3d48754 and when I tried to open the save on a server it crashed. I can't open this file or any other autosave, all files are corrupted.
Please, I beg you, can you fix this? I spend a lot amount of time on this...

- [ ] Reproducible in RCT2 (vanilla)? I don't think so
- [ ] Multiplayer? It crashed after updating to 0.1.1 build 3d48754 and trying to open a server with the save

**Screenshots / Video:**
https://images.discordapp.net/attachments/234774211330048012/334829179717550080/corru.png?width=400&height=230

**Save game:**
 https://we.tl/oxLcSr2ZS8 you can download it from wetransfer

**Comment by PFCKrutonium** [comment]
Your screenshot is super tiny - Drag and drop it onto a message here and GitHub will embed it for you,

**Comment by rwjuk** [comment]
@PFCKrutonium You can just strip the parameters from the URL to get a bigger version https://images.discordapp.net/attachments/234774211330048012/334829179717550080/corru.png

**Comment by rwjuk** [comment]
Crashes in `vehicle_update_sound()` - a ride with type `RIDE_TYPE_NULL` has gotten into the SV6 somehow, causing the assert on line 4886 to fire.

**Comment by Juloow** [comment]
Update: SupraTheHedhehog fixed the file. Apparently it was because I used bumper cars and deleted the structure with tile inspector to only have the cars left. The game didn't liked that I guess. 
Thank you for being so reactive.

**Comment by Gymnasiast** [comment]
Good to hear! We're still going to investigate though, we want to avoid it crashing.

**Comment by janisozaur** [comment]
I changed the label to `bug`, as this hits on our own asserts rather than simply crashing.

@Juloow provided comment on how we can try reproducing it, so now we can try making the behaviour correct.

**Comment by Nubbie** [comment]
[Sci Fi Thing 2.zip](https://github.com/OpenRCT2/OpenRCT2/files/1149410/Sci.Fi.Thing.2.zip)
Re-upload in case download link goes invalid/gets removed

**Comment by janisozaur** [comment]
Dupę od #3375?

**Comment by Nubbie** [comment]
@janisozaur Uploading dump soon
