### ISSUE TITLE
Unlock All Prices Cheat Persists When Switching from RCT1 to LL and RCT2 Scenarios

### ISSUE THREAD

**Issue by CharlesLove** [OpenRCT2/OpenRCT2#5881]
**OS:** Windows 10
**Version:** 0.1.1
**Commit/Build:** 3d48754

When loading a RCT1 scenario (imported from the original game; Deluxe in my case), the Unlock All Prices cheat will activate correctly for those scenarios. However, if you then load Loopy Landscapes or RCT2 scenarios, this cheat will persist incorrectly until you restart the game. Basically ever scenario will have unlock all prices selected from then on.

This only happens after loading RCT1 scenarios. When going from LL or RCT2 to RCT1, the Unlock All Prices cheat triggers like it should. Perhaps LL and RCT2 scenarios need to force Unlock All Prices off.

**Steps to reproduce:**
1. Load a RCT1 (minus Loopy Landscapes) scenario.
2. Load LL or RCT2 scenario.

**Comment by Gymnasiast** [comment]
An original scenario is always "pay for entry, pay for rides".
An LL scenario can set a flag to mark it as "free entry, pay for rides", or also be "pay for entry, pay for rides".

**Comment by CharlesLove** [comment]
I've made it so loading a new scenario automatically resets all cheats. This does not affect loading save files as they don't hold cheat information. This is done before the Unlock All Prices cheat is turned on for RCT1 (minus LL) scenarios that use it.

This does mean cheats will be dropped or could be different if you start a new scenario then load a save file that may have had cheats used at the time. In the case of the Unlock All Prices cheat, ride and admission prices are both saved regardless, so you can easily toggle on or off Unlock All Prices and continue as normal.
