### ISSUE TITLE
same save that worked fine 2 weeks ago now runs at half fps and speed only

### ISSUE THREAD

**Issue by FischNE** [OpenRCT2/OpenRCT2#5882]
**OS:** Windows 10
**Version:** 0.1.1
**Commit/Build:** 224a1db

ISSUE:
I hadn't played ORCT2 in 2 weeks and hardly even touched my laptop in the meantime. I'm working on a park that has a lot of objects, but that was perfectly ok 2 weeks ago. Now that I wanted to continue working on it, the same save game from 2 weeks suddenly only runs at half the normal speed. All things on the map move at half speed, the coasters looks a bit ridiculous because of it and the peeps are also extremely slow. Seeing as I didn't change anything on my laptop, my only conclusion is, that ORCT2 deals with the framerate differently now than it did before? I never had framerate issues.

- [ ] Reproducible in RCT2 (vanilla)? | Can't say because Vanilla doesn't work for me somehow.
- [X] Multiplayer? | Happens in Multiplayer and Singleplayer.

**Steps to reproduce:**
1. load file
2. watch frame rate and peep movement

**Save game:**
[Riverland 7 Season 140.zip](https://github.com/OpenRCT2/OpenRCT2/files/1144849/Riverland.7.Season.140.zip)

**Comment by jensj12** [comment]
If you are running low on batteries, windows halves the speed of ORCT2 automatically. Check if that's the case.

**Comment by IntelOrca** [comment]
Can you provide the FPS you are seeing before and after, for both uncapped and capped FPS please?

**Comment by FischNE** [comment]
I always run my laptop plugged in. The fps is somwhere between 15 and 23 for uncapped, and is currently up to 26 if I remove that checkmark.

Before I believe it was at 30+.

**Comment by FischNE** [comment]
It seems it really depends on where on the map I am. If I'm in spots without rollercoasters the FPS can still reach up to 40. But where the coasters are it randomly becomes ridiculously slow. It didn't use to do that and I changed nothing.

**Comment by IntelOrca** [comment]
It doesn't sound like you were getting a particularly good FPS before either. Most of the computation of the game is rendering which is single threaded - this means a good frame rate can only be achieved with a higher clock speed (regardless of how many cores your CPU may have). We aim to improve this over time.

All I can suggest is that you lower your resolution or increase the in-game scaling so that the game does not have to render as many pixels.

**Comment by FischNE** [comment]
Well I was just guessing my FPS from before. I'd definitely say it hit 60 at times also.
It honestly was absolutely not a problem until my 2 week pause in which I didn't change anything about my laptop. I felt no significant FPS drop beforehand I'd say.

**Comment by IntelOrca** [comment]
It completely depends on what part of the park you are looking at. If you look at empty space, you will get high FPS, if you look at an area where there are lots of moving things - you will get a low FPS.

**Comment by FischNE** [comment]
I definitely realize that but I built the entire park without frame rate issues and now it's kind of become impossible to build realistic coasters as I can't judge the speed and everything runs at half the fps it used to two weeks ago.
I'm definitely aware that the fps can change depending on what you look at. But certain parts of the park are suddenly unplayable when they definitely weren't two weeks ago. I'd change whatever problem I have with my laptop to fix it, but I didn't touch my laptop much in the meantime, so I doubt something would've changed so drastically.

**Comment by janisozaur** [comment]
@FischNE can you run `openrct2 benchgfx <path to your park>` with a build from ~2 weeks ago and 224a1db?

**Comment by FischNE** [comment]
Sorry but where can I find a build that goes further back than the ones on the latest list?

Also what's openrct2 benchgfx?

**Comment by janisozaur** [comment]
You can just prepare a link yourself to any of the built commits on `develop`, you can see the ones from ~2 weeks ago here: https://github.com/OpenRCT2/OpenRCT2/commits/develop?after=7f5c56de72d4bb6c5ddf3a429ac40835eed76142+139

`openrct2 benchgfx` is a subcommand to run a basic rendering benchmark. See https://github.com/OpenRCT2/OpenRCT2/pull/5655

**Comment by zsilencer** [comment]
This is from #5848

**Comment by janisozaur** [comment]
@FischNE there were some fixes that were merged in the meantime, how's your experience now?

**Comment by FischNE** [comment]
@janisozaur Thanks a lot for the response. I can definitely feel improvement! Is there still room for further optimization and fixing? The experience is definitely better than before again but it's hard to say whether it reaches the fluency of before yet. I don't remember if it was 100% fluent, but I think it was. So it's not at 100% yet for me, but it has improved in the meantime.

**Comment by janisozaur** [comment]
@FischNE can you post your `config.ini` file and provide your CPU, GPU models? If there's some specific part of the park that causes slowdowns, can you post a screenshot as well (including all the in-game windows you usually have opened)?

**Comment by FischNE** [comment]
[config.zip](https://github.com/OpenRCT2/OpenRCT2/files/1214855/config.zip)

Intel(R) Core(TM) i7-4720HQ CPU @2.60 GHz 2.60 GHz
RAM: 8,00 GB
Intel(R) HD Graphics 4600
NVIDIA GeForce GTX 960M

[Riverland 8 Season 115.zip](https://github.com/OpenRCT2/OpenRCT2/files/1214873/Riverland.8.Season.115.zip)


This part causes the most issues, without any windows being open at all.

![riverland 2017-08-10 14-30-44](https://user-images.githubusercontent.com/18613267/29170366-8e36ffec-7dd8-11e7-853d-519995d407d0.png)

**Comment by janisozaur** [comment]
OK, I will check if there's anything I can do about it. In the meantime, can you check if switching the renderer from `software` to `software with hardware display` affects performance for you?

**Comment by FischNE** [comment]
Not really any changes sadly. FPS is still at around 17 in that spot and everything is in super slow mo.

**Comment by IntelOrca** [comment]
@FischNE what FPS do you get if you set your window scale to 2?

**Comment by FischNE** [comment]
@IntelOrca 40FPS but it looks like this which isn't really playable either:

![riverland 2017-08-10 14-40-09](https://user-images.githubusercontent.com/18613267/29170675-040ead54-7dda-11e7-8543-2d113b2e7d08.png)

**Comment by Patrik356b** [comment]
FischNE, what happens if to add openrct2.exe to the nvidia control panel and set it to use the nvidia card?

**Comment by FischNE** [comment]
@Patrik356b I went into the NVIDIA control panel and tried to do that (never been in that control panel before and I'm not 100% certain I did the right thing)

I added programfiles/openrct2.exe to the control panel and set it to NVIDIA high performance processor instead of "NVIDIA global setting". The only other available setting than those two was integrated GPU. Should I choose that?

The NVIDIA high performance processor sadly didn't change RCT's performance, even after rebooting.

**Comment by IntelOrca** [comment]
@FischNE could you download older builds and tell us which ones yield a better FPS?

**Comment by janisozaur** [comment]
For a coarse-level check, use the releases here: https://github.com/OpenRCT2/OpenRCT2/releases, we can go into finer-grained checks later on.

**Comment by janisozaur** [comment]
In a totally unscientific way, I compared v0.0.7 and v0.1.1. Running with software+hwd renderer, in windowed fullscreen on Linux I got ~1fps more using the former, so it was around 18fps vs around 17fps.

**Comment by Patrik356b** [comment]
@FischNE yes.

**Comment by Gymnasiast** [comment]
This issue has not been updated for three years. Most stuff will no longer be applicable.
