### ISSUE TITLE
Release source tarball with title sequence assets?

### ISSUE THREAD

**Issue by ibara** [OpenRCT2/OpenRCT2#5887]
Is there one? This would be greatly useful for packagers.

**Comment by ibara** [comment]
It doesn't need to be for testing versions. Just the release tarballs.

**Comment by janisozaur** [comment]
The title sequences are their own sources…

**Comment by janisozaur** [comment]
You can also fetch them yourself from https://github.com/OpenRCT2/title-sequences

**Comment by ibara** [comment]
Yes I know and that's what I'm going to do. It's just easier for packagers to have them together.

**Comment by janisozaur** [comment]
Can this be closed now then?

**Comment by ibara** [comment]
Yup!
