### ISSUE TITLE
Giant screenshot does not work while using OpenGL renderer

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#5889]
**OS:** Linux
**Commit/Build:** a808da910

1. Make OpenRCT2 use OpenGL renderer
2. Load a park
3. From floppy menu, select `giant screenshot`, I only tested maximally zoomed out

Expected result:
Screenshot of the park gets written to a file

Actual result:
[Garbage](https://user-images.githubusercontent.com/550290/28187423-fdd83796-681e-11e7-8f23-cadd72cb5875.png) gets written to a file.

**Comment by Richard-L** [comment]
My result is always a completely black image instead.

**Comment by Gymnasiast** [comment]
Currently ( c457de1ecec3cb1bd9d0747d6883c51224e122ae ), it hits an assert.

**Comment by IntelOrca** [comment]
Giant screenshot should just use the software renderer.
