### ISSUE TITLE
Rendering of textured surface is broken with OpenGL

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#5890]
**OS:** Linux
**Commit/Build:** a808da9

Load the attached park, switch between renderers, observe the difference.

Software:
![openrct2_232](https://user-images.githubusercontent.com/550290/28187770-23dc8b8a-6820-11e7-82e2-6ea8dd939457.png)

OpenGL:
![openrct2_233](https://user-images.githubusercontent.com/550290/28187781-28e2fc9a-6820-11e7-9763-e77764aa5966.png)

**Save game:**
[opengl.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/1146670/opengl.sv6.txt)

**Comment by ZehM4tt** [comment]
If you look at the X8DrawingEngine you can see that FillRect has a bunch of features which are not implemented in the shader.

**Comment by duncanspumpkin** [comment]
OpenGL does not handle primary and secondary colours for special sprites that have alternative zoomed images. Easy to fix.
