### ISSUE TITLE
Changelog assumed to be next to executable

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#5891]
Changelog is only looked for in `${exe_path}/changelog.txt`. For Linux distributions, this is typically under `/usr/share/doc/openrct2/changelog.txt`.

**Comment by Mailaender** [comment]
On openSUSE the convention is `/usr/share/doc/packages/openrct2/changelog.txt`

**Comment by janisozaur** [comment]
Fixed in #6110
