### ISSUE TITLE
Error message from tile inspector is empty

### ISSUE THREAD

**Issue by Ryder17z** [OpenRCT2/OpenRCT2#5904]
Running version 250a66c currently.

See the little red box under the tile inspector window:
![openrct2_2017-07-15_02-16-48](https://user-images.githubusercontent.com/2000703/28234822-65809736-6904-11e7-91ee-d3a76e4fb56e.png)

Stepping the base height number up or down a few times gives an empty error message.

I was playing around with the tile inspector to see how it works basically.

https://www.nedesigns.com/park/3190/mm2014-r2-black-mesa-research-facility/

**Comment by Patrik356b** [comment]
Update: turns out this was scenery hiding the ground tiles as well.
