### ISSUE TITLE
(RCT1) Urban Park Entrance Problem

### ISSUE THREAD

**Issue by TheLarry98** [OpenRCT2/OpenRCT2#5905]
There is a Problem in the Urban Park from Added Attractions. The entrance and exit are switched, so the queue line goes away from the exit, instead of to the entrance. 
This happens since Chris Sawyer made a mistake when he builds the park. (so also in RCT1). 
![screenshot_12](https://user-images.githubusercontent.com/12634026/28239180-16c689b8-6966-11e7-8454-1174a22be8d7.png)

I don't know if it would be possible to fix this, without changing the SC4 file. (Similar to the missing land purchases)

**Comment by rwjuk** [comment]
We could swap the entrance and exit in the same way we patch up un-purchaseable land tiles.

**Comment by CharlesLove** [comment]
`// Station
        dst->overall_view = src->overall_view;
        for (sint32 i = 0; i < RCT12_MAX_STATIONS_PER_RIDE; i++)
        {
            dst->station_starts[i] = src->station_starts[i];
            dst->station_heights[i] = src->station_height[i] / 2;
            dst->station_length[i] = src->station_length[i];
            dst->station_depart[i] = src->station_light[i];

            dst->train_at_station[i] = src->station_depart[i];

			if (_s4.scenario_slot_index == SC_URBAN_PARK) {
				if (src->entrance[0] == 25141) // Ride 1
				{
					dst->entrances[i] = src->exit[i];
					dst->exits[i] = src->entrance[i];
				}
				if (src->entrance[0] == 24621) // Ride 2
				{
					dst->entrances[i] = src->exit[i];
					dst->exits[i] = src->entrance[i];
				}
			}
			else
			{
				dst->entrances[i] = src->entrance[i];
				dst->exits[i] = src->exit[i];
			}
            
            dst->queue_time[i] = src->queue_time[i];
            dst->last_peep_in_queue[i] = src->last_peep_in_queue[i];
            dst->queue_length[i] = src->num_peeps_in_queue[i];
        }

        dst->num_stations = src->num_stations;`

I've tried swapping ride exit and entrances in S4Importer.cpp in the ImportRide function, it doesn't seem to do anything for the rides themselves.

**Comment by Gymnasiast** [comment]
@CharlesLove You need to modify both the Ride struct (like you did) and the actual map element.
