### ISSUE TITLE
undefined reference to `pthread_create'

### ISSUE THREAD

**Issue by Mailaender** [OpenRCT2/OpenRCT2#5907]
I need help in fixing this compiler error.

**OS:** openSUSE Tumbleweed
**Version:** 0.1.0

```
[  183s] CMakeFiles/libopenrct2.dir/src/openrct2/network/TcpSocket.cpp.o: In function `std::thread::thread<TcpSocket::ConnectAsync(char const*, unsigned short)::{lambda(std::promise<void>)#1}, std::promise<void> >(TcpSocket::ConnectAsync(char const*, unsigned short)::{lambda(std::promise<void>)#1}&&, std::promise<void>&&)':
[  183s] /usr/include/c++/7/thread:126: undefined reference to `pthread_create'
[  183s] CMakeFiles/libopenrct2.dir/src/openrct2/network/http.cpp.o: In function `thread<http_request_async(const http_request_t*, void (*)(http_response_t*))::<lambda(const HttpRequest2&, void (*)(http_response_t*))>, HttpRequest2, void (*&)(http_response_t*)>':
[  183s] /usr/include/c++/7/thread:126: undefined reference to `pthread_create'
[  183s] collect2: error: ld returned 1 exit status
[  183s] make[2]: *** [CMakeFiles/libopenrct2.dir/build.make:8968: libopenrct2.so] Error 1
[  183s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/OpenRCT2-0.1.0/build'
[  183s] make[1]: *** [CMakeFiles/Makefile2:135: CMakeFiles/libopenrct2.dir/all] Error 2
[  183s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/OpenRCT2-0.1.0/build'
[  183s] make: *** [Makefile:133: all] Error 2
[  183s] error: Bad exit status from /var/tmp/rpm-tmp.nz572k (%build)
```

**Steps to reproduce:**
https://build.opensuse.org/package/show/home:Mailaender:branches:games/openrct2

**Comment by janisozaur** [comment]
Add `-pthread` to linker flags. `cmake .. -DCMAKE_SHARED_LINKER_FLAGS=-pthread` should be good enough as a workaround. I have encountered this in the past as well, but not always. I haven't figured out the required conditions that cause the need for pthread, but I'll either fix it, if I figure it out, or provide a workaround upstream.

**Comment by ZehM4tt** [comment]
The need for pthread is because the use of std::thread in TcpSocket.

**Comment by janisozaur** [comment]
@ZehM4tt one of my machines needs pthread, while the other does not, even though they should be using the same environment.

**Comment by ZehM4tt** [comment]
Thats strange, maybe its compiler/linker version specific?

**Comment by janisozaur** [comment]
@Mailaender in what circumstances do you get this error? Can you list version of your cmake and compiler? Can you provide cmake's `compile_commands.json` (`CMAKE_EXPORT_COMPILE_COMMANDS`) and other relevant pieces of information? I can no longer reproduce it on either of my machines.

**Comment by Mailaender** [comment]
`-DCMAKE_SHARED_LINKER_FLAGS=-pthread` helped solve this so I didn't investigate further. cmake version is currently 3.8.2 (Tumbleweed is rolling release, not sure what version was used 2 weeks ago) and we enforced to gcc-c++ >= 6 during the package creation to fix across openSUSE version.

**Comment by janisozaur** [comment]
Is the workaround still required?

**Comment by Mailaender** [comment]
No: https://build.opensuse.org/request/show/514824

**Comment by janisozaur** [comment]
Great, thanks!
