### ISSUE TITLE
Import mp.dat from RCT1 installation

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#5909]
Currently Mega Park is not imported from RCT1 installations without manual intervention. The game must search for `${RCT1}/Data/mp.dat` and rotate each byte of the file by 4 bits to get it into standard SC4 format.

**Comment by twocows** [comment]
Can confirm Mega Park doesn't show up on my end even with scenario_hide_mega_park set to false and scenario unlocking off.

**Comment by CharlesLove** [comment]
Mega Park does import if you have SC21.SC4 in your Scenarios folder. This requires either having the file on hand or beating all the original scenarios first, though. So people that want Mega Park right this moment can do so by downloading one of those nearly complete save file packs for the original game and plowing through that to unlock it.

**Comment by Patrik356b** [comment]
I can not remember what i got this from, but if anyone just want to jump right into the mega park, use this sc6: [Mega Park.zip](https://github.com/OpenRCT2/OpenRCT2/files/1152326/Mega.Park.zip)
