### ISSUE TITLE
Switching from Fullscreen (borderless window) to Windowed does not update UI positions

### ISSUE THREAD

**Issue by zsilencer** [OpenRCT2/OpenRCT2#5917]
**OS:** Linux
**Version:** 0.1.1
**Commit/Build:** 1b042506d

**Steps to reproduce:**
1. Go into Fullscreen (borderless window) mode
2. Switch to Windowed mode with a different sized window than fullscreen.
3. Notice that the toolbar, fps counter, etc is not positioned correctly.

**Comment by tupaschoal** [comment]
I couldn't reproduce this on v0.3.1
