### ISSUE TITLE
cmake should use BUILD_SHARED_LIBS and BUILD_STATIC_LIBS

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#5918]
Currently libopenrct2 is always built as a shared library. The standard CMAKE option: `BUILD_SHARED_LIBS` and `BUILD_STATIC_LIBS` should be used to control whether `libopenrct2.so` or `libopenrct2.a` is built. If `libopenrct2.a` is built, the only binary artefact that is installed should be `openrct2` or `openrct2-cli`.

**Comment by janisozaur** [comment]
The purpose of this is to have `openrct2` linked statically to `libopenrct2`, but all other items should come as dynamic dependencies, right? So it `openrct2` should dynamically load say `jansson`, but not `libopenrct2`?

We should probably have a message stating that's the case as it may confuse users or packagers.

I'd like have an option to also statically link to all our required libraries: `jansson`, `sdl2` and so on, this makes distributing mingw builds so much easier for me.

**Comment by IntelOrca** [comment]
> The purpose of this is to have openrct2 linked statically to libopenrct2, but all other items should come as dynamic dependencies, right? So it openrct2 should dynamically load say jansson, but not libopenrct2?

Yes

> I'd like have an option to also statically link to all our required libraries: jansson, sdl2 and so on, this makes distributing mingw builds so much easier for me.

We already do, `ENABLE_STATIC`.
