### ISSUE TITLE
Very long object list cannot be scrolled

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#592]
Since my RCT2 was ten years old when I copied it to OpenRCT2, it should be no surprise I have accumulated a ludicrous amount of plug-in objects (my ObjData contains nearly 7000 files, including the original RCT2 ones). This makes the list of Small Objects in the Scenario Editor so long it's not scrollable any more.

This bug is present in both vanilla RCT2 and OpenRCT2.
(Since I'm probably the only one crazy enough to test OpenRCT2 with a setup like this, I sometimes seem to catch bugs that are hard to reproduce. So if you need a copy of my (1.4 GB) setup, I can provide it.)

**Comment by janisozaur** [comment]
@Gymnasiast how's this in current builds?

**Comment by Gymnasiast** [comment]
Still the same, though the list is no longer stuck (which I fixed myself) and the scrollbar thumb is no longer 0.1 mm high (fixed by a contributor): at some point, the checkboxes stop drawing. Then the list items themselves stop drawing (though the preview when hovering keeps working).

**Comment by IntelOrca** [comment]
> at some point, the checkboxes stop drawing. Then the list items themselves stop drawing (though the preview when hovering keeps working).

You are probably going past 32767 pixels high in the list which is the limit of drawing. Can't really fix until full implementation or UI engine re-write.

**Comment by Wuzzy2** [comment]
One possible (probably partial) fix would be to force a minimum size for the scroll bar (about 10 pixels or so) simply to make sure it can always be grabbed.

**Comment by Gymnasiast** [comment]
@Wuzzy2 The scroll bar is already fixed (in the way you described).

**Comment by IntelOrca** [comment]
It would be a large change, but you can probably change all the scroll offsets in the window struct and event handlers to 32-bit integers now.

**Comment by Gymnasiast** [comment]
That would certainly be a solution.
However, splitting the list into pages does have the advantage of being easier to handle by the user.

**Comment by marijnvdwerf** [comment]
I've never seen a scrollable list split into pages, except for RCT2 and Gmail. So I'm not sure about the 'being easier to handle by the user'.

**Comment by Gymnasiast** [comment]
So you think a list of several kilometres is easier to handle than one split into pages? To me, that makes no sense.

**Comment by marijnvdwerf** [comment]
Splitting it up in pages doesn't serve any purpose, as the position of the items isn't fixed. It sounds like the search system needs to be improved upon.

**Comment by Patrik356b** [comment]
@Gymnasiast
He's probably using imperial thus this :) 

I like the idea of splitting the items, possibly the most flooded letters (or group of letters) gets their own pages, i.e: A-G, H, I-Z when you have lots of objects called something that begins with H.
