### ISSUE TITLE
Placing guest spawn doesn't do anything every 3rd click

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#5920]
**OS:** Windows 10 x64
**Version:** 0.1.1-develop
**Commit/Build:** 587d354

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Go to scenario editor, in the map window click the peep spawn button
2. Place two peep spawns
3. Click two more times to replace the ones that were placed
4. Click a third time now doesn't seem to replace the first, but doesn't do anything
5. Clicking again will replace one

Here I click on every other tile, notice how it skips every third:
![](http://i.imgur.com/K8ZIRTT.gif)

**Comment by Patrik356b** [comment]
aren't we supposed to be able to set 4 of these?

**Comment by Broxzier** [comment]
@Patrik356b I think you're confusing park entrances with peep spawn points. As far as I know, there's always been a limit of two spawn points, but 4 park entrances.

**Comment by Patrik356b** [comment]
I always thought that you could "only" place 4 of these because of the 4 park entrances limit.

But I never tested it. Vanilla RCT2 can set up spawns by itself, so i never looked into this.

**Comment by Gymnasiast** [comment]
No, you can only set two peep spawns in total. (And four park entrances.)

**Comment by IntelOrca** [comment]
> But I never tested it. Vanilla RCT2 can set up spawns by itself, so i never looked into this.

Vanilla and OpenRCT2 both have the ability to manually move the peep spawns as well as automatically placing them on footpaths that you place next to the edge of the map.
