### ISSUE TITLE
this track design gives you insane amounts of money

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#5931]
**OS:** 8.1
**Version:** 0.1.0
**Commit/Build:** 587d354

![image](https://user-images.githubusercontent.com/3454156/28293989-0406ec3a-6b0c-11e7-9930-d7639801e10a.png)

It has something to do with scenery, but I haven't quite nailed down what exactly. In the track design preview window, the design will not appear and the expected cost will not show if scenery is checked, but will if scenery is unchecked.

[bugged money.zip](https://github.com/OpenRCT2/OpenRCT2/files/1154342/bugged.money.zip)

**Comment by jensj12** [comment]
What is the in-game name of the scenery piece? I need to enable it somehow to investigate what's going on. I can't open the track design.

**Comment by spacek531** [comment]
There should be a SCENICRR.DAT included in the zip.

**Comment by jensj12** [comment]
I'm looking for the in-game name so I can find it in the object selection without scanning through pages of custom scenery items. I have copied that file to my objects folder.

**Comment by spacek531** [comment]
It's called "Scenic Railway" and it's a wooden roller coaster.

**Comment by jensj12** [comment]
I can confirm the free money bug when building with scenery. Even worse, this is what I get when money is disabled:
![happy park 2017-07-18 15-53-46](https://user-images.githubusercontent.com/13868449/28320816-dce5ec16-6bd1-11e7-9125-066e76b0899e.png)

**Comment by PFCKrutonium** [comment]
May they rest in pieces.

**Comment by Liampie** [comment]
> I'm looking for the in-game name so I can find it in the object selection without scanning through pages of custom scenery items. I have copied that file to my objects folder.

Parkdat is your friend.
