### ISSUE TITLE
Refactor tile to unit conversions

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#5935]
In the code base we have a lot of multiply and divide (or bit shifts) when converting from tiles to units and units to tiles visa versa. We should make the helper functions below and use them everywhere. This also ensures consistency of using bit shift (faster for signed numbers) instead of multiply and divide.

```c
uint8 UnitsToTiles(sint16 units)
{
    return (uint8)(units >> 5);
}

sint16 TilesToUnits(uint8 tiles)
{
    return (sint16)(units << 5);
}
```

**Comment by janisozaur** [comment]
> using bit shift (faster for signed numbers) instead of multiply and divide.

This is precisely the scenario in which you should not be using bit shifting, as this is undefined behaviour.

**Comment by IntelOrca** [comment]
Only if you use the undefined operations.

**Comment by rwjuk** [comment]
Also not at all sure about relying on implementation-defined behaviour. Would the increased performance really make that much difference?

**Comment by ZehMatt** [comment]
@IntelOrca is this still a thing?

**Comment by duncanspumpkin** [comment]
We have moved the majority of the code to use tile coords or coords with the conversion functions in the constructors. This i think can be closed now.
