### ISSUE TITLE
Unplug sound device causes no music

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#594]
If there are two sound devices plugged in to the computer, e.g. speakers and USB headphones and the default is set to the headphones. Music will work through the headphones, but when the headphones are removed, the music stops instead of playing through the speakers. When going on the options dialog, the list of sound devices doesn't update and shows the headphones still. When selecting any sound device, the game hangs. Sound seems to be fine.

**Comment by IntelOrca** [comment]
There is a bug in [SDL_CloseAudioDevice](https://wiki.libsdl.org/SDL_CloseAudioDevice) as far as I can tell, at least for me using xaudio2. When this is called for a device which has been unplugged, the function freezes indefinitely.

**Comment by zsilencer** [comment]
Did you try SDL_PauseAudioDevice before the SDL_CloseAudioDevice ?

**Comment by IntelOrca** [comment]
Now that we are using SDL 2.0.4, it appears there are still issues with hot plugging sound devices. I need to do more investigation but I have noticed that the game no longer hangs when selecting sound devices after the device list has changed.

Would anyone be able to check what works, what doesn't work regarding this for Linux and OSX?

**Comment by janisozaur** [comment]
This doesn't affect Linux at all. The sound gets sent to PulseAudio, which handles all the outputs, so you unplug, change and do other things without affecting the game.

**Comment by IntelOrca** [comment]
@janisozaur Does the sound device dropdown in options update correctly and allow you to switch between them?

**Comment by janisozaur** [comment]
![selection_094](https://cloud.githubusercontent.com/assets/550290/12231050/fa9dee34-b854-11e5-9ade-ca123422c33b.png)

![sound_095](https://cloud.githubusercontent.com/assets/550290/12231051/ff500ca0-b854-11e5-812b-471a8ce50206.png)

**Comment by IntelOrca** [comment]
I don't seem to have issues with this anymore.
