### ISSUE TITLE
Bumbly Beach completion does not allow username input or save to highscores.dat

### ISSUE THREAD

**Issue by Ryder17z** [OpenRCT2/OpenRCT2#5942]
Running version 250a66c on win8.1 currently.

This may be caused by something in this savegame: 
[Bumbly Beach.zip](https://github.com/OpenRCT2/OpenRCT2/files/1156017/Bumbly.Beach.zip)

I sped up the game and then reset the speed a shortly before the objective ends:
[openrct2_2017-07-18_15-46-04](https://user-images.githubusercontent.com/2000703/28320213-46dc653e-6bd0-11e7-8158-97dcd0250b7d.jpg)

[openrct2_2017-07-18_15-37-16](https://user-images.githubusercontent.com/2000703/28319961-9c1291e6-6bcf-11e7-9cfa-ec45b197455d.jpg)

![openrct2_2017-07-18_15-37-58](https://user-images.githubusercontent.com/2000703/28319940-8a7c9738-6bcf-11e7-84f4-4e3800b8df16.jpg)

**Comment by Nubbie** [comment]
#2851, still seem to be a issue, save might help out :)

**Comment by Patrik356b** [comment]
Tried this from scratch and it didn't happen this time. There's bound to be something strange about that save.

**Comment by rwjuk** [comment]
I know I've completed BB in OpenRCT2 and it allowed me to enter a name, so it must be something to do with this save. This doesn't mean that the bug shouldn't be investigated though, as we need to stop whatever happens in this case from actually happening!

**Comment by swannet** [comment]
I've the same issue with a several parks (not just Bumbly Beach) from the Original RCT 1 files. I'm running the latest develop on Win8. Is it useful to provide a save after finishing the park? Didn't have a save before, I'll try to find a 100% reproduce scenario. But according to #2851 this will be hard I guess as reloading the same save sometimes works

**Comment by Patrik356b** [comment]
Gymnasiast commented 2 days ago

I'm going to consider this solved. It should be working, unless you loaded up and saved a save in the few days the develop version was broken. In this case your save is "corrupted".
--

From #6624
