### ISSUE TITLE
Hedge Maze: no track preview if paused

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#5943]
Running version 250a66c on win8.1 currently.

The preview for hedge maze does not work when paused.

![openrct2_2017-07-18_20-38-19](https://user-images.githubusercontent.com/2000703/28333945-d441cbfc-6bf9-11e7-9ba2-cd7b26e2b82b.jpg)

Works correctly if the cheat "allow building in paused mode" is enabled.

**Comment by Gymnasiast** [comment]
Mazes almost seem to have no more in common with other ride types than with scenery or footpaths. They're defined by exceptions. -,-

**Comment by rwjuk** [comment]
@Gymnasiast I think we might need a 'maze bug' label given how different they are to anything else!

**Comment by Patrik356b** [comment]
lol
