### ISSUE TITLE
Trains without upstop wheels crash very easily on steep-up-to-slope-up

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#5945]
This is actually an issue that goes all the way back to RCT1: it's impossible to make a dingy slide go over a steep-up-to-slope-up piece without it flying off the track even though the slope-down-to-steep-down allows for -1 g.

![image](https://user-images.githubusercontent.com/3454156/28352312-856e24a6-6c0a-11e7-899e-aac639e1c8e9.png)

On my scenic railway trains, at 43 kph the train crashes, and at 35 kph the train fails to crest the hill. 43 and 35 are the nearest speeds that brakes can be set to.

These steep up slopes exist in real life and it would be great if I could recreate them in OpenRCT2.

**Comment by Patrik356b** [comment]
How does the "tunnel option" affect this? U vs O

**Comment by spacek531** [comment]
it doesn't fly off on tunnels

**Comment by HaasJona** [comment]
So looking at the source and excluding turns/lateral g, a vehicle will derail if the following conditions are met:

* The track is not covered
* The vehicle is on an upwards slope and the vertical g is ≤ -0.4 (-0.45 for bob rides)
* Or the vehicle is on a downwards slope and the vertical g is ≤ -0.8 and it is not on a steep slope

This seems quite lenient to me, physically speaking the vehicle should derail pretty much as soon as the vertical g is < 0.

**Comment by spacek531** [comment]
Doing some tests with the 6-seater wooden, it appears the maximum vertical g's you can experience when going over a steep slope *and* make it over the crest is -0.6 g. I believe this figure will always be higher than the corresponding steep slope down because the forces are calculated from the front car.
![image](https://user-images.githubusercontent.com/3454156/28593645-e56af58c-7141-11e7-885b-d79e41473bbb.png)

Regardless, cresting steep hills is mutually-exclusive with the current criteria.

Anyway, on real scenic railways, they go over the crests of these steep hills at not an insignificant pace, and based on some tests I think a threshold of -1 g will achieve a behavior that looks like the real rides. Some people might not appreciate the dinghy slides not crashing in exactly the same ways, so this feature is probably best-left for when the new object format gets added.

**Comment by HaasJona** [comment]
Scenic railway roller coasters are typically being braked at the top of the hill (sometimes manually by a brakeman). -1g would be equivalent to riding upside down, so not only would the car fly of the track but also you would need restraints for the guests that are more elaborate than on typical side friction coasters.

The game physics isn't super good, but I think in this case the problem isn't that the g force displayed in the game is unrealistic, but that the slope transition pieces are just too harsh and unflexible. In reality you can obviously adjust the slope in a finer way to not cause negative vertical g forces.

**Comment by spacek531** [comment]
I believe this was changed a few years ago.
