### ISSUE TITLE
Headless server is not able to read language files

### ISSUE THREAD

**Issue by Jannyboy11** [OpenRCT2/OpenRCT2#5949]
**OS:** Arch Linux
**Version:** Linux (x86-64) (NO_RCT2)
**Commit/Build:** 70f1e94

hi there, latest development build broke my headless server, it can't open the language file. I don't think it's a permission issue in my linux system since previous build worked fine, and I chown-ed the whole directory recursively to make the rct user owner of all files.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. clone the repo from github
2. follow install instructions (linux)
3. start headless server
4. watch the program not being able to read the language files

**Screenshots / Video:**
![8a4f018e023c1a383e309d9a0fb67f4d](https://user-images.githubusercontent.com/5656370/28368422-92dc025e-6c94-11e7-9d20-900467b3702a.png)

**Save game:**
Not sure if it matters, but here it goes. It's the Ghost Town level with some cheats applied.
[Ghost Town.zip](https://github.com/OpenRCT2/OpenRCT2/files/1159174/Ghost.Town.zip)

**Comment by IntelOrca** [comment]
It is looking in the wrong location, unless you really do have your `language` directory at the root of your filesystem?

**Comment by IntelOrca** [comment]
This is the directory location find order:
1. `--openrct-data-path`
2. current directory (might be exe path or arg 0 - I can't remember)
3. `/usr/share/openrct2`

**Comment by Jannyboy11** [comment]
Thanks, no the language directory is not at the root of my filesystem. ;-) The current working directory doesn't include the language folder either, and I'd like to keep it that way. Gonna try to copy them to /usr/share/openrct2, thanks! 👍

**Comment by janisozaur** [comment]
I think it tries a few places and only reports the last one that failed.
I usually do `ln -s ../data` and that's enough for openrct2 to load all the files correctly.

**Comment by Jannyboy11** [comment]
I tried that, couldn't connect with my client because it was out of date.

**Comment by IntelOrca** [comment]
@Jannyboy11 the package can't be out of date, it is nothing more than an automated script that builds the latest commit on `develop`. You force update the package whenever you like.

**Comment by Jannyboy11** [comment]
Ah thanks. That's my misunderstanding then. There were no updates in the package and I couldn't connect to the server. So by process of elimination I figured it must have been out of date. I'll force update it tonight.
