### ISSUE TITLE
Open doors when any train passes through

### ISSUE THREAD

**Issue by jensj12** [OpenRCT2/OpenRCT2#5951]
Walls with doors in them can only be placed on certain rides (like ghost train, car ride or wild mouse), but with cheats, they can be placed on any ride (like a wooden coaster or mini golf). The sad thing is that the doors no longer open and close when a train passes.
Feature request: properly open and close doors when used on any tracked ride, not just a small selection.

**Comment by Patrik356b** [comment]
I want this too. A problem may be getting it to work well with high speeds

**Comment by janisozaur** [comment]
My eyes read "Open doors when any train passes through", but my brain says "Script engine hook on sprite collision detection"

**Comment by Gymnasiast** [comment]
@janisozaur Mine don't. I doubt it's that much effort to open doors for everything - it could very well be less than it is now.
