### ISSUE TITLE
New feature: unlock things by purchasing land/construction rights they are built on

### ISSUE THREAD

**Issue by Ryder17z** [OpenRCT2/OpenRCT2#5957]
Sometimes it would be nice if there was certain things that could only be unlocked by purchasing a special piece of land/construction rights.

I think the ideal way this would work is to have this area marked with a different flag and you buy the whole area for convenience reasons.

This is probably suited best for the upcoming plugin though.

**Comment by Gymnasiast** [comment]
Can't say I like this, but what people do with plug-ins is entirely up to them.

**Comment by Patrik356b** [comment]
@Gymnasiast Hence the last lie of the original post.

**Comment by IntelOrca** [comment]
@Patrik356b is it worth being an issue on here if its just a plugin idea though?

**Comment by Patrik356b** [comment]
@IntelOrca I don't know where else to put it.
