### ISSUE TITLE
Semi-transparent/Semi-translucent ghost pieces/construction markers

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#5960]
Sometimes when building, i keep switching back-and-forth between the two current option as a mixture of both does not exist, example:

![leafy lake 2017-07-20 13-39-07](https://user-images.githubusercontent.com/2000703/28416519-a69651a8-6d54-11e7-8541-ade6d1eecb26.png)

I don't know how this would be achieved, but it would be very handy.

**Comment by Gymnasiast** [comment]
Can you hold back a bit on the feature requests?

**Comment by Patrik356b** [comment]
That's the last one though.

**Comment by Gymnasiast** [comment]
I wouldn't count on this being implemented. It has the unfortunate combination of (likely) not being easy to implement and not having that much appeal to other players. (You're the first person I have ever heard using the see-through ghosts, not kidding.) It's also something not easily implemented by a plug-in. But if someone proves me wrong with a non-intrusive PR, I'll happily merge it.


(By the way, I don't understand the thumbs-down and the confused faces. If one user opens three feature requests in two hours, is it odd that I ask them to slow down a bit?)

**Comment by AaronVanGeffen** [comment]
>  I don't understand the thumbs-down and the confused faces. If one user opens three feature requests in two hours, is it odd that I ask them to slow down a bit?

I'd rather see someone make three distinct feature requests, screenshots and everything, than one big issue with vague requests, to be honest. To me, it wasn't exactly flooding the issue tracker.

Just to add, I think this feature shouldn't be too hard to implement once we inevitably move towards a palette-less renderer. With full 32-bits colours available, transparency effects should become much easier to achieve, too.
