### ISSUE TITLE
Finish 5 roller coasters objective

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#597]
The original game allowed the objective to be set on a scenario if there is no money.
There however the following problems:
- [ ] Scenario editor does not check if there are five rollercoasters (you would need to convert a saved game anyway)
- [x] The game didn't exclude null rides from its ride loop check.
- [ ] The game didn't check if the ride was a rollercoaster.
- [ ] The game didn't check if the ride was one of the five partially pre-built rollercoasters.

**Comment by Gymnasiast** [comment]
What is the current state of this?

**Comment by IntelOrca** [comment]
Updated the issue to use checkboxes, status is unchanged.
