### ISSUE TITLE
Headless Servers lost the ability to load Scenarios

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#5973]
Instead, they can ONLY load saves.

Recently means anywhere from 11:45PM EST 2017-07-22 (now) to after the period of time where we were dealing with Sprite Corruption on headless servers.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. ./openrct2 host ~/RCT2/Scenarios/Europe\ -\ Renovation.SC6 --headless
2. Failed to load '/home/krutonium/RCT2/Scenarios/Europe - Renovation.SC6'
    Park is not a saved game.

(I modified S6Import to load it anyway... That didn't go well.)

**Comment by telk5093** [comment]
It seems that not only headless servers but also single play.
I cannot load scenario and just title sequence appears if I double click SC6 files on Windows.
