### ISSUE TITLE
"Different colors per vehicle" does not work on any type of rollercoaster

### ISSUE THREAD

**Issue by sublimechasm** [OpenRCT2/OpenRCT2#5974]
**OS: Windows 7 x86-64** 
**Version: 0.1.1-develop**
**Commit/Build: bc88cb9**

I opened a saved track of mine and it had different colors per vehicle but when I loaded it up it was all the same color

- [no] Multiplayer?

**Save game:**

**Comment by IntelOrca** [comment]
I can not reproduce this, can you provide details steps please?
