### ISSUE TITLE
Custom Music 1 & 2 Missing

### ISSUE THREAD

**Issue by CharlesLove** [OpenRCT2/OpenRCT2#5977]
**OS: Windows 10**
**Version: 0.1.1**
**Commit/Build: 3409662** 

Custom Music 1 and 2 are missing from the dropdown list for ride music. Not sure what build this happened in, but must have been quite recent.

**Steps to reproduce:**
1. Change ride music.
2. Custom Music 1 and 2 aren't there.

**Dump file**

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/5576972/28500678-05337d46-6f92-11e7-83c0-b7406e23be48.png)

**Comment by rwjuk** [comment]
Do you have the custom WAV files in the `Data` directory?

**Comment by CharlesLove** [comment]
Yes. It works on an older 0.1.1 build I have based on 3d48754 which was the last commit on July 12, so something must have broken in that time.

**Comment by CharlesLove** [comment]
As of July 24th this appears to have been fixed.
