### ISSUE TITLE
Issue with ride list window when using the quick demolish feature in pause mode

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#5981]
OS: Windows 7
Version: 0.1.1
Commit/Build: c929311

If you demolish a ride in pause mode with the quick demolish feature you get what is shown in the screenshot below. This behavior also happens to a certain extent when the game is not paused but the "0 people on ride" only appears for a short moment. 

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

Steps to reproduce:
1. Pause the game
2. Use the quick demolish feature

Screenshot
![six flags over texas 2017-07-23 22-26-41](https://user-images.githubusercontent.com/28242696/28506058-7b96e1f8-6ff6-11e7-95bf-c568720bd648.png)

**Comment by rwjuk** [comment]
I have a feeling I introduced this bug with my tweaks to the ride list window - either way, I'll fix it.
