### ISSUE TITLE
Can't rebind to socket if process is killed while someone is connected

### ISSUE THREAD

**Issue by WizardOfTheWest** [OpenRCT2/OpenRCT2#5984]
**OS:** [edit] Ubuntu 16.04 and Antergos/Arch Linux
**Commit/Build:** [edit] e431c812fa995d44d11d3458ebeed3c111b355de

As the title suggests, killing the openrct2 server process (while headless, not sure about non-headless) while having any connections, will make it so it gives the error of `Unable to bind to socket.` when attempting to start it back up. [edit] I should also add that the error only happens for about a minute, it lasts until Linux cleans up the unused socket (or something close to this).

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Host a server headlessly
2. Connect to said server
3. Kill server process
4. immediately attempt to start server again

**Comment by IntelOrca** [comment]
Can you please fill in the OS, version and commit information. The OS is particularly important for this issue.
