### ISSUE TITLE
Staff not getting paid / no loan interest

### ISSUE THREAD

**Issue by HighFlyerPL185** [OpenRCT2/OpenRCT2#5998]
**OS:** Windows 7
**Version:** 0.1.1

RCT2 vanilla savegame and scenario, edited using scenario editor.
Everything explaining the issue is located here, including steps to reproduce, and save game.

https://openrct2.org/forums/topic/2568-staff-arent-getting-paid-no-loan-interest/

**Comment by IntelOrca** [comment]
This saved game seems have ended up in a state where `gDateMonthTicks` is not a multiple of 4. If it is not a multiple of 4, it ends up skipping weekly updates such as paying wages. I am not sure how it ended up in this state.

**Comment by rwjuk** [comment]
We should probably sanitise that on S6 import - set it to the closest multiple of 4.

**Comment by IntelOrca** [comment]
Hmm, I was going to do it when it updates `gDateMonthTicks`.

**Comment by rwjuk** [comment]
The thing is, if it ends up as not a multiple of 4 owing to something we've done, then that's a bug that we should fix. Silently correcting it may hide other issues.

**Comment by IntelOrca** [comment]
> Silently correcting it may hide other issues.

We have had to resort to this for many bugs recently. There are only four places where it is set. To 0, +4, from S4 and from S6. So I can't see what would have caused this within OpenRCT2.

**Comment by rwjuk** [comment]
Oh I don't think we currently have a bug that's causing this, I'm just concerned about hiding any future issues. Then again, it's no big deal to clamp it on update really.
