### ISSUE TITLE
Assumed Datafile bug: Angled support structure

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#6006]
![openrct2_2017-07-25_21-57-08](https://user-images.githubusercontent.com/2000703/28591087-bdc5be98-7184-11e7-80f1-841bb9c6b4b7.png)

The two square support structures that has the same visual style can be removed when the same restriction is in place
[2017-07-25_22-06-44](https://user-images.githubusercontent.com/2000703/28591374-c9999d42-7185-11e7-88cc-148b111d3d4b.jpg)

**Comment by spacek531** [comment]
On the other hand, being able to set scenery as impossible to destroy would be a great feature.

**Comment by Patrik356b** [comment]
That's actually a nice idea @spacek531

**Comment by Patrik356b** [comment]
Tested again on 45b7569 and as I thought, no difference.

Here is a sv6 to reproduce the issue: 
[test2-2.zip](https://github.com/OpenRCT2/OpenRCT2/files/1441529/test2-2.zip)

**Comment by Gymnasiast** [comment]
RCT2 considers everything over 6 metres a tree. There is no flag to mark something as a tree.

**Comment by IntelOrca** [comment]
@Gymnasiast we'll see about that!

\*adds isTree property to json schema\*

**Comment by duncanspumpkin** [comment]
There are so many useless flags I'm surprised there isn't a is tree flag

**Comment by Gymnasiast** [comment]
A PR to add this flag to the JSON objects is here: https://github.com/OpenRCT2/objects/pull/22

**Comment by Gymnasiast** [comment]
PR for the rest of this issue is here: https://github.com/OpenRCT2/OpenRCT2/pull/8891
