### ISSUE TITLE
Potential issue with guests 'vomiting' while walking along stations

### ISSUE THREAD

**Issue by rwjuk** [OpenRCT2/OpenRCT2#6007]
This was reported on gitter (![see screencap](https://user-images.githubusercontent.com/16639257/28595835-9d8f938e-718d-11e7-92ee-0e7ecbdb1f6d.PNG)). User reported that hungry guests were vomiting (in itself odd) while on ride stations, thus blocking the station.

Upon joining the server, the admins had unfortunately set all guests' hunger to minimum to get around the issue. It is quite possible that this isn't a bug, but I'll record it here anyway as @ZehM4tt wanted to have a look. [Save game from the server](https://github.com/OpenRCT2/OpenRCT2/files/1174897/hunger_bug.zip) - a cursory inspection didn't turn up anything odd.

**Comment by ZehM4tt** [comment]
https://github.com/OpenRCT2/OpenRCT2/issues/1992 😄
