### ISSUE TITLE
Issue when deleting scenery in SC4 scenarios

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#6009]
**OS:** Windows 7
**Version:** 0.1.1
**Commit/Build:** 9a49490

Deleting some of the scenery somehow makes the game lower the ground under the scenery item (see screenshot below). After deleting it once, if you try to delete it again the game thinks that the item isn't within the park limits. The issue seems to occur only with scenery that is close to park borders. On the other hand, the "auto-delete" function when building rides works fine and doesn't create this bug. I tried to reproduce the issue in SC6 scenarios but everything seems to be working without problems.

Note: Using the "Own all land" cheat after trying to delete some problematic scenery crashes the game. I can provide a dump file if needed.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Screenshot:**
![forest frontiers 2017-07-25 18-21-38](https://user-images.githubusercontent.com/28242696/28596896-2239c5ac-7169-11e7-8c8c-e83a62cf098c.png)

**Comment by rwjuk** [comment]
Well this one's an oddity. Confirmed that it happens.

**Comment by Gymnasiast** [comment]
@rwjuk @duncanspumpkin This looks dodgy: https://github.com/OpenRCT2/OpenRCT2/pull/5308/files#diff-683c5d3a8e4e4bf01a3ebe74c157cdbbR218

**Comment by Patrik356b** [comment]
I see a funny variable name: "gUnk" :thumbsup:
(Yes, i know the name itself isn't affecting anything)

**Comment by Gymnasiast** [comment]
gUnk = global unknown

**Comment by Wolfscopez** [comment]
Ditto on having issues with this.

**Comment by duncanspumpkin** [comment]
can you provide a scenario with this happening

**Comment by rwjuk** [comment]
Any SC4 should do, but here's FF. [sc0.zip](https://github.com/OpenRCT2/OpenRCT2/files/1181037/sc0.zip)

**Comment by duncanspumpkin** [comment]
tah. I can never be bother to get my RCT1 disc out to install.

**Comment by duncanspumpkin** [comment]
Lol i know the issue.

**Comment by rwjuk** [comment]
@duncanspumpkin What is it - this one's been bugging me!

**Comment by duncanspumpkin** [comment]
Turns out you should probably check to make sure that when deleting scenery you are deleteing scenery and not whatever comes up first.
