### ISSUE TITLE
Assertion Failed, Sprite 65535 when opening a Scenario

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#6010]
**OS:** Windows 10
**Version:** 0.1.1
**Commit/Build:** 9a49490

Attempting to open this SC6 crashes the game

**Steps to reproduce:**
1. Attempt to open this SC6
2. [Woodland Thrills.zip](https://github.com/OpenRCT2/OpenRCT2/files/1174984/Woodland.Thrills.zip)

**Dump file**

[Dump.zip](https://github.com/OpenRCT2/OpenRCT2/files/1174986/Dump.zip)

![crash](https://user-images.githubusercontent.com/3945538/28596953-69c1c780-7169-11e7-902f-5a6ade420174.PNG)

**Comment by rwjuk** [comment]
Only happens when loading via file association.

**Comment by PFCKrutonium** [comment]
![Blame the Ducks](https://vignette2.wikia.nocookie.net/herebemonsters/images/6/62/Duck-Sprite.png)
