### ISSUE TITLE
Assertion failed when opening saved game

### ISSUE THREAD

**Issue by detroitsubaru** [OpenRCT2/OpenRCT2#6013]
OS: Windows 8.1
Version: v0.1.1-develop 
build 587d354

When attempting to open saved game it gives me this error.

![image](https://user-images.githubusercontent.com/30458548/28606612-db70ad56-71a5-11e7-88b2-30d43d69b275.png)

![image](https://user-images.githubusercontent.com/30458548/28606623-eaea028c-71a5-11e7-8ec2-876ff6958e0d.png)

Happens every time, haven't tried in vanilla.

Dump file and SV6 file:

[OpenRCT2.zip](https://github.com/OpenRCT2/OpenRCT2/files/1175585/OpenRCT2.zip)

saved game:

[HugePark7-10-17.zip](https://github.com/OpenRCT2/OpenRCT2/files/1175590/HugePark7-10-17.zip)

**Comment by Patrik356b** [comment]
Vanilla:
![rct2_2017-07-26_15-32-28](https://user-images.githubusercontent.com/2000703/28623929-b89b1560-7217-11e7-82f2-2871f3567a46.png)

bb09019 gives a different error:
![2017-07-26_15-34-36](https://user-images.githubusercontent.com/2000703/28624151-86f3ce34-7218-11e7-9c92-30e1def1e4fd.png)
![2017-07-26_15-35-13](https://user-images.githubusercontent.com/2000703/28624150-86e76e78-7218-11e7-9cef-a71abf95f01e.png)
[3311743b-7799-4c7b-87bc-e247293e7af4(bb09019_x86-64).zip](https://github.com/OpenRCT2/OpenRCT2/files/1176716/3311743b-7799-4c7b-87bc-e247293e7af4.bb09019_x86-64.zip)

**Comment by rwjuk** [comment]
This is a problem with the objects packed with the save - upon attempting to decode a certain chunk the `uncompressedLength` ends up being zero. Unsurprisingly, `Memory::Reallocate` doesn't like this.

**Comment by Gymnasiast** [comment]
The current version does not crash, but prints an error to stderr (`Corrupt RLE compression data.`), and goes back to the title screen, not displaying anything in-game.
