### ISSUE TITLE
Holding the Arrows Doesn't Work in MP For Arbitrary Ride Type Changes

### ISSUE THREAD

**Issue by xp4xbox** [OpenRCT2/OpenRCT2#6017]
OS: Windows 7
Version: 0.1.1
Commit/Build: 3f345c6

While playing in multiplayer holding down the two arrows for arbitrary ride type changes does not work as it does in singleplayer.
- [x] Multiplayer?

**Comment by xp4xbox** [comment]
tagging @wolfreak99

**Comment by wolfreak99** [comment]
Thank you for tagging me on this, I just posted a [Pull request](https://github.com/OpenRCT2/OpenRCT2/issues/6019) that fixes this. Could you download one of the AppVeyor builds and see if it fixes it for you as well? If it does, let me know either in this thread (make sure to tag me so I get the notification), or in the [Pull request](https://github.com/OpenRCT2/OpenRCT2/issues/6019), thanks!

AppVeyor builds:
[Windows 32-bit](https://ci.appveyor.com/project/IntelOrca/openrct2-ject9/build/0.1.1.9616/job/covb6m204rhr7wt8/artifacts) | [Windows 64-bit](https://ci.appveyor.com/project/IntelOrca/openrct2-ject9/build/0.1.1.9616/job/43v5upmpyoufmaak/artifacts)

**Comment by xp4xbox** [comment]
@wolfreak99 it still doesnt work for me.

**Comment by wolfreak99** [comment]
From the builds listed or from the launcher? because it's not merged with the official build yet.

**Comment by xp4xbox** [comment]
The builds listed.

**Comment by wolfreak99** [comment]
Okay, I think I just now fixed it, I've also tested in multiplayer, but could you verify for me that this works properly now?

AppVeyor builds:
[Windows 32-bit](https://ci.appveyor.com/project/IntelOrca/openrct2-ject9/build/0.1.1.9616/job/3hpd02q2bc0w5dvk/artifacts) | [Windows 64-bit](https://ci.appveyor.com/project/IntelOrca/openrct2-ject9/build/0.1.1.9616/job/doehamsi9uicnjej/artifacts)

**Comment by xp4xbox** [comment]
@wolfreak99 Yep, it works.
