### ISSUE TITLE
vehicle colors regression

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#6021]
**OS:**Windows 8.1
**Version:** 0.1.0
**Commit/Build:** 4af64bb

OpenRCT2 no longer can paint individual vehicles:

![image](https://user-images.githubusercontent.com/3454156/28641618-c082c574-7204-11e7-8955-819966175200.png)

The regression occurred between 2017/7/19 and 2017/7/26

**Comment by Gymnasiast** [comment]
Looks like the bug report that IntelOrca closed today or yesterday because he couldn't reproduce it.

**Comment by spacek531** [comment]
I looked in the closed bug reports and I didn't see it

**Comment by Gymnasiast** [comment]
Yours has more info anyway.
