### ISSUE TITLE
'select ride to advertise' dropdown does not display all items

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#6026]
**OS:** 8.1
**Version:** 0.1.0
**Commit/Build:** 4af64bb

![image](https://user-images.githubusercontent.com/3454156/28648782-18dc2100-7225-11e7-8097-4871392be05e.png)

I am not able to select the Speedy Arrow ride.

Park download: https://www.nedesigns.com/park/1641/calypso-theme-park-la/

**Comment by Gymnasiast** [comment]
It only lists the 40 most reliable rides.

I could change this to 128, although that would mean a big list and potentially still too few entries.

I'm inclined to raise the limit 128 but stop listing rides that are not open. That would make the list a whole lot easier to navigate if you have lots of rides used for decoration or merging.
