### ISSUE TITLE
console does not display all items

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#6027]
**OS:** 8.1
**Version:** 0.1.0
**Commit/Build:** 4af64bb

With the park linked below, entering `rides list` results in this mess:

![image](https://user-images.githubusercontent.com/3454156/28648866-ca5a698c-7225-11e7-8eed-bf9bec3db1c8.png)

https://www.nedesigns.com/park/1641/calypso-theme-park-la/

**Comment by IntelOrca** [comment]
The actual issue is that the text is messy when the console buffer is filled up to the maximum. There also many string truncation warnings posted to stdout.

**Comment by AaronVanGeffen** [comment]
This has already been solved by c965f854d80595f9317817fe64ccad1dab32ad2c.
