### ISSUE TITLE
Trouble switching to the Music tab on Merry-Go-Rounds

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#6043]
Running 6f2020e currently, this has not been an issue before:

https://puu.sh/wUEus/0f6ebe1377.mp4

Only occurs when trying to jump from paint tab or measuments tab to the music tab.

This quite annoying as the first thing I do when I build one of these is to mute the music.

**Comment by rwjuk** [comment]
I can't replicate this on the latest build.

**Comment by Patrik356b** [comment]
Oddly enough didn't happen again after I restarted the computer.

**Comment by rwjuk** [comment]
Okay, let us know if it happens again.
