### ISSUE TITLE
rides default to "separate colors per train" instead of "all vehicles same color"

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#6045]
**OS:** Windows 8.1
Version: 0.1.0
Commit/Build: 4af64bb

Probably introduced in the same PR as the vehicles color bug. By default rides now have separate colors per train instead of all vehicles in the same color.

**Comment by Gymnasiast** [comment]
Cannot reproduce this on https://github.com/OpenRCT2/OpenRCT2/commit/d1cd2e08b5e5233f4bcacc164e97da6cfa87fe90, so I'll assume this has been fixed.
