### ISSUE TITLE
Scrolling in spin boxes does not work any more

### ISSUE THREAD

**Issue by ccoors** [OpenRCT2/OpenRCT2#6047]
**OS:** Arch Linux
**Version:** 0.1.1
**Commit/Build:** c595d24ebd9f4002f6d0ff06999913802b6950eb

Scrolling does not work any more in e.g. the 'Clear Scenery' or 'Land' window. Before I could just hover the mouse over the area selector and scroll to adjust the size, this doesn't work any more.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open the 'Land' window
2. Hover the mouse over the area selector spinner
3. Scroll with the mouse wheel

**Comment by wolfreak99** [comment]
I don't recall this being a thing in OpenRCT2. When you say "Before" are you talking about on vanilla RCT2, or OpenRCT2?

**Comment by ccoors** [comment]
This was in OpenRCT2. I just checked the 0.0.7 release.
