### ISSUE TITLE
Flying Coaster Animation Speed Decrease

### ISSUE THREAD

**Issue by TheFlyerMan1** [OpenRCT2/OpenRCT2#6056]
Hi -- one thing that's been really bugging me about RCT2 is the speed at which the flying coaster tilts. Real life flyers take 3 seconds to tilt, as opposed to the miniscule amount of time it takes in-game. Could this please be rectified?

**Comment by Patrik356b** [comment]
Can be: Yes
Should be: maybe (not) ? 

The game isn't aiming for a high level of realism anyway.

**Comment by Gymnasiast** [comment]
I don't remember the Flying Coaster tilting. Are you really referring to the B&M Flyer?

**Comment by spacek531** [comment]
I'm pretty sure that the behavior he is talking about is linked to the restraints animation.

**Comment by rwjuk** [comment]
Can you provide a screenshot of the exact ride you're referring to @TheFlyerMan1 ? Thanks.

**Comment by TheFlyerMan1** [comment]
I do indeed mean the Flying Coaster. I would have stated otherwise if the aforementioned coaster was the laydown coaster.

![B&M flyer in the menu screen](https://i.gyazo.com/ba0629110460337ca71a8ed977c20576.png)

**Comment by Gymnasiast** [comment]
Hm, the restraints close too quickly on any coaster, really. But yes, as Patrick pointed out, the game isn't aiming for a high level of realism anyway. It would probably annoy most people that their roller coaster takes another 3 seconds to depart, just for a more realistic animation.

**Comment by Androgeos** [comment]
When I first played RCT3, I thought the trains travelled a bit too slowly, but they really were travelling at the correct speed - it's just that I spent so many years playing RCT1 and RCT2 that it warped my perception of actual physics such that I felt that a train travelling at 60 km/h should look like it goes around the track a lot faster.

**Comment by Gymnasiast** [comment]
Since there does not seem to be a clear majority for this change, I'll close this issue.
