### ISSUE TITLE
quick demolish can delete protected ride

### ISSUE THREAD

**Issue by Lastorder-DC** [OpenRCT2/OpenRCT2#6071]
**OS:** Windows 7
**Version:** 0.1.1
**Commit/Build:** 4ed970a

quick demolish can delete protected ride(demolish disabled ride)

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open ride list window
2. Try to delete protected ride
3. ride is deleted

**Comment by wolfreak99** [comment]
What is a map to test this on?

**Comment by Lastorder-DC** [comment]
any scenario with protected ride will be ok.
I tested with Haunted Harbour scenario.

![haunted harbour 2017-07-29 23-23-11](https://user-images.githubusercontent.com/18280396/28745523-00c261dc-74b5-11e7-8285-8d51856606f1.png)
(Wooden rollercoaster is protected, but can be removed with quick demolish)

Save file : 
[Haunted Harbour.zip](https://github.com/OpenRCT2/OpenRCT2/files/1185005/Haunted.Harbour.zip)
