### ISSUE TITLE
Multi-dimension coaster sprites corrupted + crash

### ISSUE THREAD

**Issue by jensj12** [OpenRCT2/OpenRCT2#6073]
**OS:** Windows 10
**Version:** 0.1.1
**Commit/Build:** 2ec0df1

The sprites for the multi-dimension coaster can become corrupted. After that, opening the rollercoaster tab in the build new ride window crashed my game.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
I have yet to find a reliable way to reproduce the issue. What I did: open lots of saves until you encounter some corruption, then open new ride window and switch to coaster tab.

**Dump file**
[OpenRCT2CrashDumpMDcoaster.zip](https://github.com/OpenRCT2/OpenRCT2/files/1185081/OpenRCT2CrashDumpMDcoaster.zip)

**Screenshots / Video:**
A video is available for download here: https://openrct2.org/forums/topic/2564-um/

**Save game:**
Any game with a MD coaster may or may not work. On this save the sprites got corrupted: 
[Bogus sandbox.txt](https://github.com/OpenRCT2/OpenRCT2/files/1185084/Bogus.sandbox.txt) (I may have switched to another save before the crash)

**Comment by jensj12** [comment]
[Made my own video](https://youtu.be/YFNlNpGUozU). Where the video hangs, it has crashed. This is the dump it created and I saved right before starting the video. Loading lots of saves seems to work.
[OpenRCT2CrashDumpMDcoasterWithSave.zip](https://github.com/OpenRCT2/OpenRCT2/files/1185093/OpenRCT2CrashDumpMDcoasterWithSave.zip)

**Comment by IntelOrca** [comment]
My guess is that it is related to the image list not correctly allocating the images which is likely for multi-dimensional coaster as it has so many images to allocate. The image list can become fragmented after many object loads and unloads reducing the number of free image slots available.

**Comment by Nubbie** [comment]
Dump from OpenRCT2CrashDumpMDcoasterWithSave.zip

Error message;
Unhandled exception thrown: read access violation.
colourSrc was 0xFFFFFFFFFFFFFFFF.

Call stack;
```
>	openrct2.dll!gfx_draw_sprite_raw_masked_software(rct_drawpixelinfo * dpi, int x, int y, int maskImage, int colourImage=-1) Line 659	C++
 	openrct2.dll!window_new_ride_scrollpaint(rct_window * w=0x00007ffc714aacc0, rct_drawpixelinfo * dpi=0x000000768a8ff5c0, int scrollIndex=4) Line 862	C
 	openrct2.dll!widget_scroll_draw(rct_drawpixelinfo * dpi=0x000000768a8ff6e0, rct_window * w=0x00007ffc714aacc0, short widgetIndex) Line 770	C
 	openrct2.dll!window_draw_widgets(rct_window * w=0x00007ffc714aacc0, rct_drawpixelinfo * dpi=0x000000768a8ff6e0) Line 1754	C
 	openrct2.dll!window_new_ride_paint(rct_window * w=0x00007ffc714aacc0, rct_drawpixelinfo * dpi=0x000000768a8ff6e0) Line 820	C
 	openrct2.dll!window_draw_single(rct_drawpixelinfo * dpi, rct_window * w=0x00007ffc714aacc0, int left, int top, int right=640, int bottom=448) Line 1728	C
 	openrct2.dll!window_draw(rct_drawpixelinfo * dpi=0x000000768a8ff7a0, rct_window * w=0x00007ffc714aa7e0, int left=0, int top=256, int right=640, int bottom=448) Line 1623	C
 	openrct2.dll!window_draw_all(rct_drawpixelinfo * dpi, short left, short top, short right, short bottom) Line 584	C
 	openrct2.dll!OpenRCT2::Drawing::X8DrawingEngine::DrawAllDirtyBlocks() Line 404	C++
 	openrct2.dll!OpenRCT2::Drawing::X8DrawingEngine::PaintWindows() Line 232	C++
 	openrct2.dll!OpenRCT2::Paint::Painter::Paint(OpenRCT2::Drawing::IDrawingEngine *) Line 54	C++
 	openrct2.dll!OpenRCT2::Context::RunFixedFrame() Line 495	C++
 	openrct2.dll!OpenRCT2::Context::RunGameLoop() Line 465	C++
 	openrct2.dll!OpenRCT2::Context::RunOpenRCT2(int argc=-1010635504, char * * argv=0x00000252c3c503a0) Line 159	C++
 	openrct2.dll!NormalisedMain(int argc=1, char * * argv=0x00000252c3c503a0) Line 65	C++
 	openrct2.dll!LaunchOpenRCT2(int argc, wchar_t * * argvW) Line 55	C++
 	[External Code]	
```

**Comment by Gymnasiast** [comment]
From our Gitter channel:
![](https://files.gitter.im/OpenRCT2/OpenRCT2/non-dev/piwz/Montagne-magique-Six-Flags-2018-03-29-13-36-09.png)

**Comment by Gymnasiast** [comment]
These parks appear to hit image limits. Is there any reason why the limit is 0x40000?

**Comment by Gymnasiast** [comment]
I can no longer reproduce this issue on the current develop version of OpenRCT2. Could you try for yourself to see if the issue is solved?

**Comment by jensj12** [comment]
I can't (easily) reproduce this currently.
