### ISSUE TITLE
Add warning to title screen if game is running on elevated permission/administrator account(not message)

### ISSUE THREAD

**Issue by fromthere** [OpenRCT2/OpenRCT2#6079]
![king-county-amusements-2017-07-31-21-36-15](https://user-images.githubusercontent.com/10338434/28778212-5dc76226-7639-11e7-923c-9e85d7cb569f.png)
`<My suggestion>`

Warning message is really annoying because I'm using administrator account so game detects I'm running with elevated permission. This way message will not annoying, and users will notice warning more easily.

**Comment by Gymnasiast** [comment]
The whole point of the message and it being annoying is that you shouldn't be using an administrator account to do stuff that doesn't require it. That includes OpenRCT2. Your attack surface is high enough without running everything as administrator.

**Comment by janisozaur** [comment]
The whole point of this is to not run with elevated permissions, so in a way, it is _meant to be annoying_. Run OpenRCT2 with lowered permissions and it will be OK.

I vote for closing with `wontfix`.

**Comment by rwjuk** [comment]
If you're on Windows, you should really have UAC on, which runs processes non-elevated unless you (or the process) specifically requests elevation. OpenRCT2 does not need administrative permissions in 99.9% of use cases.

**Comment by jamtraks** [comment]
I'm having this problem too however in my case i have a message box come up before i can start the game.
![elevated permissions](https://user-images.githubusercontent.com/17103908/42700823-e065ee22-8692-11e8-9a7f-829be865b245.jpg)

Elevated permission usually means you are opening something as the administrator which is what most people are... the administrator, so this would be annoying for most people trying to play openrct2. Why would you guys have "added" this to openrct2?

**Comment by AaronVanGeffen** [comment]
@jamtraks Please read the messages in this thread. It's been explained several times.
