### ISSUE TITLE
Scenario Editor saves scenarios to incorrect directory by default

### ISSUE THREAD

**Issue by Keatzee** [OpenRCT2/OpenRCT2#6085]
**OS:** Windows 7
**Version:** 0.1.1
**Commit/Build:** 84eebb1

The "Save Scenario" file dialog in the Scenario Editor asked to save in `OpenRCT2/Scenarios` by default. It should use `OpenRCT2/scenario` instead.

**Comment by tupaschoal** [comment]
I cannot reproduce this on v0.3.1
