### ISSUE TITLE
Desync when constructing path with scenery in its way.

### ISSUE THREAD

**Issue by ZehM4tt** [OpenRCT2/OpenRCT2#6089]
Connecting footpath with scenery between seems to cause desyncs, the action will in fact never take place on the server.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Load the savegame for host.
2. Join as client and connect the missing footpath, scenery will not be removed on server.

**Save game:**
[desync04.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/1189074/desync04.sv6.txt)

**Comment by janisozaur** [comment]
Looks like a duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/3852

**Comment by ZehM4tt** [comment]
True.
