### ISSUE TITLE
[Bug] Newest Updates widened ride clearances

### ISSUE THREAD

**Issue by MessiahOfFire** [OpenRCT2/OpenRCT2#6092]
Windowns 10
v0.1.1 Ofe6066

When attempting to build scenery along the edges of small tracked rides (car rides and wild mine rides mainly), at seemingly random points I can not place scenery along the ride's track in places which should normally allow scenery placement in previous version. 

- Not Reproducible in the vanilla game, or older versions of Open.
**Steps to reproduce:**
1. Build small tracked ride
2. Attempt to build scenery along its side

Screenshot: https://drive.google.com/open?id=0Bzd-AVDy3MIFblF1TWlXSUtvRjg 
Save: https://drive.google.com/open?id=0Bzd-AVDy3MIFQWJzMHhSLTVpTWc

**Comment by Gymnasiast** [comment]
Cannot reproduce in OpenRCT2, v0.4.2-226 (a4b60e8ed6 on steep-flume, DEBUG).
