### ISSUE TITLE
Bug: admission price resets to free when loading game

### ISSUE THREAD

**Issue by hottentottententententoonstelling** [OpenRCT2/OpenRCT2#6095]
OS: Windows 8.1 (64-bit)
Version: 0.1.0 release

Whenever I start a scenario, the admission prices of the default attractions aren't set to free (see first picture). When I save the game, re-open rct and load the game the prices are forces to free.

Screenshots / Video:
![initial](https://user-images.githubusercontent.com/25718992/28817478-a1475dd4-76a8-11e7-8191-b9de0d59e77a.png)
![final](https://user-images.githubusercontent.com/25718992/28817484-a5ed169e-76a8-11e7-906f-ccb416aeaeab.png)

Save game:
[Katie's Dreamland.txt](https://github.com/OpenRCT2/OpenRCT2/files/1190036/Katie.s.Dreamland.txt)

**Comment by Gymnasiast** [comment]
This is a SV6 limitation. Turn on the 'Unlock all prices cheat' and the prices will jump back again.
(We set that cheat on the initial import, but afterwards we can't detect if a save has been loaded from SV4 or not.)

**Comment by hottentottententententoonstelling** [comment]
Ok thanks for the fast response, I will try this

**Comment by hottentottententententoonstelling** [comment]
Thanks it worked 👍

**Comment by PFCKrutonium** [comment]
(It was because we were having a hard and heavy discussion in gitter, and it has notifications. We spent a little while trying to decipher your username).

**Comment by hottentottententententoonstelling** [comment]
Huh, nevermind, why I this not turned on by default?

**Comment by PFCKrutonium** [comment]
It was only on by default in RCT1, and we have no way of determining if a save is from RCT1 vs 2.
