### ISSUE TITLE
Some last bytes of the player name in multiplay seems to be cutted in Korean

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#6097]
**OS:** Windows 10
**Version:**  0.1.1
**Commit/Build:** 2f3a30f

When the player name in multiplay is setted as non-english language, such as Korean, it seems to be cutted the some last bytes of it.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Set Language as Korean
2. Set player name as Korean, such as ``텔크``(means "TELK") like below image.
 It is ``\xED\x85\x94\xED\x81\xAC`` in UTF-8 encoding.
 ![image](https://user-images.githubusercontent.com/10726524/28826738-1de7fe68-7706-11e7-8442-85c1fc18092a.png)
3. Player name is displayed incorrectly. ``텔퀀`` is ``\xED\x85\x94\xED\x80\x80`` in UTF-8 encoding.
 But I think it is caused by being cutted some last bytes of player name. (It is only my opinion)
![image](https://user-images.githubusercontent.com/10726524/28827326-2ce96878-7708-11e7-9862-322aad7e366b.png)
4. [Additional] Terminate OpenRCT2 game and re-run and open multiplay window.
 Then incorrect player name is shown again like this:
 ![image](https://user-images.githubusercontent.com/10726524/28827639-2b530838-7709-11e7-8568-a2f093d89893.png)

**Comment by Nubbie** [comment]
#2756 related?

**Comment by Gymnasiast** [comment]
@Nubbie No.

**Comment by telk5093** [comment]
I found that String::Trim() trims utf8 letter incorrectly.
It was fixed when I compile the game with this line commented:
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/config/Config.cpp#L367

**Comment by AaronVanGeffen** [comment]
You're right, there does seem to be a corruption issue with multibyte strings here.

Quick steps to reproduce:
1. Set `player_name` to `テストー` in config.ini:
`player_name = "テストー"`
2. Set language to Japanese so the characters are displayed.
3. Observe the following in-game:
![screenshot_20171223_021133](https://user-images.githubusercontent.com/604665/34315832-b2c82774-e786-11e7-90cd-2dc28db3f8d6.png)
4. In your favourite editor, notice:
`player_name = "テスト<E3>"`
