### ISSUE TITLE
Paths don't connect to exit

### ISSUE THREAD

**Issue by hottentottententententoonstelling** [OpenRCT2/OpenRCT2#6100]
OS: e.g. Windows 8
Version: 0.1.1
Commit/Build: 2f3a30f

Paths do not connect to the park entrance/exit so that guests cannot leave the park

Screenshot:
![six flags magic mountain 2017-08-01 17-33-35](https://user-images.githubusercontent.com/25718992/28833536-e3463836-76df-11e7-8bfb-d339d2d5b9c1.png)

**Comment by hottentottententententoonstelling** [comment]
I can confirm that this bug does not exist in the stable version 0.1.0

**Comment by rwjuk** [comment]
@hottentottententententoonstelling Can you attach the save game (.SV6) for this park? You'll need to ZIP it before uploading as Github doesn't like SV6 files.

**Comment by hottentottententententoonstelling** [comment]
[Six Flags Magic Mountain.txt](https://github.com/OpenRCT2/OpenRCT2/files/1192200/Six.Flags.Magic.Mountain.txt)
(Maybe you have to delete and re-add those paths to see the bug, since this file is from the master version 0.1.0)

**Comment by Poligrizolph** [comment]
This bug is also present in Canary Mines: The only steps required for this bug to present itself are to replace the path tile in front of the park gate. This bug persists even if the path is replaced after that.
