### ISSUE TITLE
Highest drop height in ride preview is incorrect 

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#6113]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.1.0]
**Commit/Build:** [e.g. 6d1f732]

In the ride preview for rides that have a "highest drop height", it doesn't give the correct height. It seems like it takes the amount of drops the ride has, and just puts a unit for meters after it. I have looked at about 15 different coasters, and they all had stats like "drops: 7, highest drop height: 7m". When I put the game in imperial units it converts the meters to feet, so a ride with 7 drops will have a displayed highest drop height of 22ft, and not 7ft.

I have noticed this bug for quite a while already, so it's not a new one.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer? I don't think you can build pre-built rides in multiplayer

**Steps to reproduce:**
1. Look at a ride preview of any coaster.

**Screenshots / Video:**
http://imgur.com/a/xMmZ4

**Comment by Gymnasiast** [comment]
Ok, this is odd. I don't ever see it set, except when importing from SV6 or when the start drop is higher than the current value. It never seems to set the value to the actual highest drop height.

**Comment by Gymnasiast** [comment]
You mean in the track list preview, right?
