### ISSUE TITLE
Random title screen music not random on launch

### ISSUE THREAD

**Issue by flipflop97** [OpenRCT2/OpenRCT2#6115]
**OS:** Arch Linux
**Version:** 0.1.0
**Commit/Build:** 34614b2

I have selected random title screen music in settings and have installed both rct2 and rct1 correctly. I noticed when casually playing the game that I'm hearing the rct2 title screen music much more often than the rct1 one, so I tested to see if this was true. I launched the game a few dozen times and all of the times the rct2 music started playing. When coming back from a saved game the title screen music does seem random as is the case when you change the option in settings. So it looks like the music isn't random only just after launching the game.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Setup rct1 folder
2. Set title screen music to random
3. Launch the game
4. Listen to not so random rct2 music

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by Patrik356b** [comment]
I believe this because a perceived inversion of https://en.wikipedia.org/wiki/Pseudorandomness but I could be wrong

**Comment by flipflop97** [comment]
Ok, so apparently now the same is happening but with the rct1 song. It indeed seems like some pseudorandom value is not updating when just starting the game.

**Comment by Chaosmeister** [comment]
I don't understand much of the math that's going on within  
`util_srand()` and `util_rand()`
but the first returnvalue of `util_rand()` after seeding is always even:

This becomes an inifinite loop.
```
uint32 test = 0;
while (!test)
{
    util_srand((uint32)time(0));
    test = util_rand() % 1;
}
```

the next returnvalue looks like it is pseudorandomized correctly.

**Comment by IntelOrca** [comment]
I mentioned this to @duncanspumpkin and he said he just grabbed some code off the internet. It looks like it isn't good enough so it will need replacing with a better algorithm.

**Comment by flipflop97** [comment]
Is there a reason to use a self-implemented random function? C has its own random function in the stdlib library that doesn't have this issue. I suggest just using this built in rand function instead of util_rand if that's not a problem.
