### ISSUE TITLE
Miniature railway's wheels no longer turn

### ISSUE THREAD

**Issue by GustavGoblin** [OpenRCT2/OpenRCT2#6118]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.1.0]
**Commit/Build:** [e.g. 426e106]

The miniature railway's driving wheels are static and do not rotate. This does not happen in RCT2 and hasn't happened in any previous version of ORCT2 I've seen.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by jensj12** [comment]
Please fill in the placeholder and remove any you're not using. In particular, fill in the commit/build number.  If possible, find the last build that did work and the first one that no longer worked. It helps tracking down where the bug was introduced.

**Comment by rwjuk** [comment]
Regression in 9c7c553ccce395bddf424f4f44b519d1b836be07 / #6058
