### ISSUE TITLE
Feature suggestion: Konami code easter egg

### ISSUE THREAD

**Issue by wolfreak99** [OpenRCT2/OpenRCT2#6120]
There has been a big history of games, programs, sites, devices, implementing the konami code as an easter egg. I feel it would be pretty cool to do the same, I'm not sure what the function would do exactly, that would be up for debate. 

My suggestion was originally going to be opening a link to a rick roll, but considering it may be blocked in some countries, this could be a good alternate. Especially with it being rct related.
 https://www.youtube.com/watch?v=ZE0_oyK1Juo

**Comment by rwjuk** [comment]
The input handling for such a code (tracking keystrokes and such) would not be simple, particularly given that people can set up keyboard shortcuts. That aside, I just don't think this is something I think the game needs.

**Comment by Patrik356b** [comment]
@rwjuk peeps rename "cheat" might be a better solution, since that's how the original easter eggs are triggered

**Comment by wolfreak99** [comment]
@rwjuk  I mean as far as shortcuts, all you'd have to do is listen to the arrows and then if it's sequenced "up, up, down, down, left, right, left, right" within a short time, then ignore the following keystroke "b" and "a", unless the next one is not "b" or a long enough delay occurs. This was more less just a random thought, i probably should have actually used the forums for that though..

**Comment by Lastorder-DC** [comment]
that would be good for plugin, not default function.
