### ISSUE TITLE
Feature: Recording

### ISSUE THREAD

**Issue by tcek** [OpenRCT2/OpenRCT2#6121]
Would it be at all possible to have a record button that can record a 30-60 second clip and automatically save in a GIF animation image or even a video? Would be cool for rollercoasters or showing people what a custom ride does.

**Comment by Patrik356b** [comment]
I use this for that; http://www.screentogif.com/

It's a great tool.

**Comment by PFCKrutonium** [comment]
I'm fairly sure ShareX works too. Available online as well as on Steam.

**Comment by Patrik356b** [comment]
I totally missed that there was a gif recording in ShareX. good to know 😄

**Comment by tcek** [comment]
Thanks, guys.

**Comment by Margen67** [comment]
There's also a gif-recording branch but it's dead

**Comment by janisozaur** [comment]
Well, it works, but the performance hit of that recording was too high to be merged
