### ISSUE TITLE
This track design fails to save/load correctly

### ISSUE THREAD

**Issue by jensj12** [OpenRCT2/OpenRCT2#6123]
**OS:** Windows 10
**Version:** 0.1.1 develop
**Commit/Build:** 2dc8746

I built a rollercoaster with 4 stations and a dummy coaster to sync them. Whenever I try to save and load the coaster, ~$30000 is charged but the coaster is not built. Disabling clearance checks does not help. While building, I switched from inverted coaster to steel looping coaster. #6094 does not fix this.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Save track design
2. Load track design

**Screenshots / Video:**
![happy park 2017-08-04 22-48-47](https://user-images.githubusercontent.com/13868449/28995157-78bd61d8-79e1-11e7-89b0-a339ba6c27a8.png)

**Save game:**
[Quadruple steel racer.td6.txt](https://github.com/OpenRCT2/OpenRCT2/files/1202328/Quadruple.steel.racer.td6.txt)
[Racers Park.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/1202329/Racers.Park.sv6.txt)

**Comment by duncanspumpkin** [comment]
Refer to #9472 for further details as to why this happens.

**Comment by Ryder17z** [comment]
This one can't be built: [Steel Twister 1.zip](https://github.com/OpenRCT2/OpenRCT2/files/4146416/Steel.Twister.1.zip)
Sample Park: [steel-twister-savegame.zip](https://github.com/OpenRCT2/OpenRCT2/files/4146452/steel-twister-savegame.zip)
created with: 3f837f5 today

**Comment by Gymnasiast** [comment]
@Ryder17z Your design cannot be built due to a different bug. Could you create a separate issue for it?
