### ISSUE TITLE
Scenario editor: allow path tool to change park entrance path

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#6125]
A couple of friends has commented that it's a bit fiddly to replace the standard path tile in the park entrances and they would wand the path tool to be able to change the existing tiles for these.

**Comment by trigger-death** [comment]
![Wish Granted](https://i.imgur.com/8t6sym5.gif)

**Comment by Gymnasiast** [comment]
Implemented by #6479.
