### ISSUE TITLE
Wrong line height in Info window (in korean)

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#6126]
**OS:** Windows 10
**Version:** 0.1.1
**Commit/Build:** 6b48f43

Changelog button is hidden by texts since line height of korean is quite wide than english's.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Set to Korean
2. Open ``About 'OpenRCT2'`` window.

**Dump file**

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/10726524/29001921-1a6e9b7e-7ad1-11e7-88b6-bbde568bf394.png)

**Comment by AaronVanGeffen** [comment]
With 4fe70294e2d7658678546494faa0215deda76bb0 merged, the text should no longer overlap the changelog button.
