### ISSUE TITLE
Junior coaster suddenly can't do steep slopes anymore

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#6127]
**OS:** Windows 10
**Version:** 0.1.0
**Commit/Build:** 6b48f43

A week ago I built a junior coaster using steep slopes in the [forest frontiers guest challenge](https://www.reddit.com/r/rct/comments/6qasn6/2challenge_accepted_forest_frontiers_with_1690/) I posted on Reddit. Today I wanted to build another junior coaster, but suddenly it can't do steep slopes anymore. I've found another issue where "select rides by track type" caused that issue, but I haven't changed any of my settings between a week ago and today. I have always had "select rides by track type" off. I can still build my saved designs that include steep slopes without a problem, as you can see [here](http://imgur.com/a/wBr4s)

- [ ] Reproducible in RCT2 (vanilla)? not applicable
- [x] Multiplayer?

**Steps to reproduce:**
1. Try building a junior and see if you can build steep slopes.

**Comment by djh101** [comment]
You were able to build steep slopes? I've never been able to in RCT2 or OpenRCT2.

**Comment by Patrik356b** [comment]
Afaik rct2 doesn't have steep slopes but rct1 does. Don't quote me on this tho

**Comment by djh101** [comment]
Correct, RCT1 did but RCT2 created the mini roller coaster and then removed steep slopes on the junior coaster. OpenRCT2 also didn't have steep slopes on the junior roller coaster, unless they changed it in the last month (though if you open an RCT1 scenario like Diamond Heights with a prebuilt junior roller coaster it will still have steep slopes).

**Comment by Patrik356b** [comment]
I think this depends on what kind of train is put on the track.

**Comment by PFCKrutonium** [comment]
OpenRCT2 has had steep slopes on mini coasters for a while now, actually.

**Comment by djh101** [comment]
Mini coasters have always had steep slopes but junior never have (at least not since RCT1).

**Comment by PFCKrutonium** [comment]
Sorry, Junior. It was re-added as part of the compat code for importing RCT1 parks.

**Comment by djh101** [comment]
Yes, as I said, they can have steep slopes if you load a scenario or saved game from RCT1 with the ride already built but there is no option for adding steep slopes manually in the ride builder, unless there is a cheat or something that I don't know about.

**Comment by rwjuk** [comment]
Closing this, see #5691 for details on this change.
