### ISSUE TITLE
Guest List not updating after a ride rename

### ISSUE THREAD

**Issue by linkinpark9812** [OpenRCT2/OpenRCT2#6129]
**OS:** Windows 10 x64
**Version:** 0.1.1
**Commit/Build:** c1598c2

If you have the Guest List window open, specifically in summary view, the list only refreshes every several seconds or so. Due to this, if that window is open while you rename a ride/attraction, and that name appears in the summary list, it will show as a blank string until the next refresh comes around.

- [X] Reproducible in RCT2 (vanilla)?
- [X] Multiplayer?

**Steps to reproduce:**
1. Open Guests window
2. Click the All guests(summarized) tab
3. Find a ride/attraction currently listed.
4. Proceed to open that ride window and rename it, while keeping the Guests window open
5. After the rename, you should see it appear blank for up to several seconds.

**Comment by linkinpark9812** [comment]
Related Pull Request: https://github.com/OpenRCT2/OpenRCT2/pull/6130

**Comment by ralmazrouei** [comment]
its updating but as fast as it should be, any recommendation on how to make it updates faster ?

**Comment by IntelOrca** [comment]
Probably best to force a refresh when you rename a ride. Updating the refresh interval can slow the game down if there are lots of guests in the park.

**Comment by Gymnasiast** [comment]
Fixed for the summary, the regular pages (guests on ride, guests thinking about ride, guests queuing for ride) still need doing.

**Comment by tupaschoal** [comment]
Cannot reproduce this anymore in v0.3.1
