### ISSUE TITLE
Icon alignment issue on Vehicle Tab on Ride window

### ISSUE THREAD

**Issue by linkinpark9812** [OpenRCT2/OpenRCT2#6131]
**OS:** Windows 10
**Version:** 0.1.1
**Commit/Build:** 6b48f43

On any ride where the train hangs lower than the track, the vehicle icon on the vehicle tab on the ride window is also lowered, cutting the image off and misalignment it.

- [X] Reproducible in RCT2 (vanilla)?
- [X] Multiplayer?

**Steps to reproduce:**
1. Open a ride window of a ride with a train lower than the track (eg. Inverted Vertical Shuttle roller coaster, Suspended Swinging Cars roller coaster, etc.
2. Note on the vehicle tab (whether clicked or not) shows the train icon much lower than it should be.

![screenshot_2](https://user-images.githubusercontent.com/30772334/29003933-6a62e370-7a85-11e7-9a0f-8afad891e4b4.jpg)

**Comment by linkinpark9812** [comment]
Related pull request: https://github.com/OpenRCT2/OpenRCT2/pull/6132

**Comment by duncanspumpkin** [comment]
@linkinpark9812 I've removed you linking comments github handels that as long as your PR has a reference to it.
