### ISSUE TITLE
Signs/flags showing possible land to buy/get construction rights on not shown after selecting construction rights.

### ISSUE THREAD

**Issue by black1104** [OpenRCT2/OpenRCT2#6133]
**OS:** Windows 10 (x86-64)
**Version:** 0.1.1
**Commit/Build:** 6b48f43 provided by AppVeyor

After opening land rights window you can see what land you can buy and same should apply to construction rights. After selecting construction rights then signs/flags are no longer shown for both land purchase and construction rights purchase. This is visual only, you can still purchase land/rights. Closing land rights window doesn't fix the issue. Closing and reopening/changing park fixes the issue until you select construction rights again.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Select a park where you can buy construction rights (preferably with land additional land to buy).
2. Open 'Land rights' window.
3. Select construction rights.

**Screenshots / Video:**

After opening 'Land rights' tool:
![step 1](https://user-images.githubusercontent.com/30781587/29006895-e2c160bc-7af8-11e7-9cfb-a0d70c0a4d72.png)

After selecting building rights:
![step 2](https://user-images.githubusercontent.com/30781587/29006900-fea49402-7af8-11e7-8a0d-9b75bca7b5c5.png)

After selecting land purchase back:
![step 3](https://user-images.githubusercontent.com/30781587/29006901-0a5fb74a-7af9-11e7-8815-cf46a60d768c.png)

**Comment by Chaosmeister** [comment]
I'm on it!
