### ISSUE TITLE
Scenarios incorrectly categorized when using Polish version of RCT2.

### ISSUE THREAD

**Issue by black1104** [OpenRCT2/OpenRCT2#6134]
**OS:** Windows 10 (x86-64)
**Version:** 0.1.2
**Commit/Build:** 6547116 provided by AppVeyor

All parks included in original RCT2 and its expansions with exception of scenario 'Rock 'n' Roll - Rock 'n' Roll' appear in 'Other parks' tab instead of their appropriate tabs when using Polish version of the game.

All file names use original, English name but in-game scenario names are in Polish.

This could potentially affect other languages but I only own Polish version. Almost definitely related to Polish scenario names as scenario 'Rock 'n' Roll - Rock 'n' Roll' is unnafected.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Install Polish version of RCT2 or use Polish scenarios.
2. Open game.
3. Open scenario selection window.

**Screenshots / Video:**

When using categorization by difficulty:
![expert](https://user-images.githubusercontent.com/30781587/29006983-8fa22f90-7afa-11e7-987c-09fb3ccd08ff.png)

When using categorization by game/expansion:
![other](https://user-images.githubusercontent.com/30781587/29006995-d75337ee-7afa-11e7-8bb6-c3f82e082ef8.png)
![time twister](https://user-images.githubusercontent.com/30781587/29006999-de7b03b2-7afa-11e7-964f-ef3f44ffeb62.png)

**Comment by rwjuk** [comment]
@black1104 Can you provide one of the Polish SC6s that is incorrectly categorised? Any random one should do.

**Comment by black1104** [comment]
@rwjuk here's one of the scenarios.

[Extreme Heights.zip](https://github.com/OpenRCT2/OpenRCT2/files/1204319/Extreme.Heights.zip)

**Comment by black1104** [comment]
Possibly related.

I noticed that almost all attractions and scenery objects use Polish language when having OpenRCT2 set to English (same as with scenarios). Attractions that share Polish and English name (Top Spin) use English description while others use Polish description (in that case several of Polish letters are not displayed correctly). 

I used RCT2 Object Editor and found that all Polish text is stored as English. Some files have Polish set in place of both American and British English while others only one of them (the other one is empty). There's a chance that there are some using both Polish and English, but I checked less than 10 files.

This Friday/Saturday/Sunday I'll take a look a little bit more and provide some files.


Should I create a separate issue thread for this?

**Comment by black1104** [comment]
Rename files to .DAT

Here's attraction with Polish name and description in-game:
[C3D.TXT](https://github.com/OpenRCT2/OpenRCT2/files/1236336/C3D.TXT)

Here's attraction with English name and description in-game:
[TOPSP1.TXT](https://github.com/OpenRCT2/OpenRCT2/files/1236337/TOPSP1.TXT)

**Comment by Gymnasiast** [comment]
The Polish version was translated in an incompatible way. They just replaced the English strings with Polish ones.

I do have the Polish version (I extracted stuff from it), so I might just investigate at some point. But generally, I recommend a regular RCT2 version (disk, GOG or Steam).
