### ISSUE TITLE
River Rapids Selection of "Whirlpool" changes back to normal track piece while building

### ISSUE THREAD

**Issue by fuchsilp** [OpenRCT2/OpenRCT2#6137]
**OS:** Windows 7 x64
**Version:** 0.1.1 
**Commit/Build:** 304a7f3

When you build a River Rapids and you choose the "Whirlpool" piece and build it, then the selection jumps back to the regular track piece. When you choose the Waterfall or the Rapids, the choosen track piece stays chosen.

- [x] Reproducible in RCT2 (vanilla)? Didn't test in RCT2, but in RCT1+LL it is reproducible
- [ ] Multiplayer? Didn't test it in multiplayer

**Steps to reproduce:**
1.  Build a River Rapids
2.  Choose "Whirlpool"
3. Build "Whirlpool".
4. Look now at the shown track piece.

**Dump file**
No dump file available

**Comment by rwjuk** [comment]
I imagine this is working as intended - as the waterfall section can be (probably was designed to be) longer than one tile, whereas the whirlpool element was designed to be singular.

**Comment by IntelOrca** [comment]
I agree, the game always has to choose a suitable following track piece for every track piece. I can see the player likely wanting another waterfall after a waterfall, but not a whirlpool.

**Comment by Patrik356b** [comment]
It is more realistic with only certain parts used once in a sequence
