### ISSUE TITLE
'Too low' error when placing shops/stalls at very lowest level

### ISSUE THREAD

**Issue by rwjuk** [OpenRCT2/OpenRCT2#6138]
See [post on forums here](https://openrct2.org/forums/topic/2585-cant-construct-this-here-too-low/).

Replication steps:

1. Open Thunder Rock.
2. Try to place a stall on the ground level area (e.g. by the entrance).
3. Get 'Cannot construct this - too low' error.

EDIT: Seems this has been marked as 'wontfix' in the past (#1833), as a likely SV6 limit. However, you can build at the lowest level in RCT1 just fine. If it wasn't an SV4 limit I doubt it's an SV6 limit.

**Comment by Horsti12** [comment]
This also happends to the scenario Micro Park:
#4937

**Comment by rwjuk** [comment]
@Horsti12 #6139 fixes that one too - thanks.

**Comment by LordMarcel** [comment]
This also happens to tracked ride stations. You can build towards the lowest level and then build the station, but you cannot place the station on the lowest level as the first piece.
