### ISSUE TITLE
CSS50.dat is never loaded

### ISSUE THREAD

**Issue by woj1993** [OpenRCT2/OpenRCT2#6141]
OS: Windows 10
Version: 15063.483
Commit/Build: 18791fa

Css50.dat is copied into data directory of RCT2 but it don't load.

**Steps to reproduce:**
1. Rename Css17.dat rom RCT1 to Css50.dat and copy it to RCT2 data folder. 
2. Start game and try to select Roller Coaster Tycoon 1 theme music.
3. Watch game information that you don't have Css50.dat.

**Comment by rwjuk** [comment]
It'd be far easier to set the [RCT1 path in the options](https://github.com/OpenRCT2/OpenRCT2/wiki/Loading-RCT1-scenarios-and-data) to load the RCT1 music (and scenarios, some sprites, etc.)

**Comment by woj1993** [comment]
True but if it is not supported information box should be actualized.
P.S. Descriptions in Polish language don't mention possibility of adding RTC1 patch.

**Comment by janisozaur** [comment]
@woj1993 

> P.S. Descriptions in Polish language don't mention possibility of adding RTC1 patch.

Please see https://github.com/OpenRCT2/Localisation/pull/1161
