### ISSUE TITLE
Multiplayer missing on Android

### ISSUE THREAD

**Issue by ApocalypsjeNL** [OpenRCT2/OpenRCT2#6143]
**OS:** Android 7.1.2
**Version:** 0.1.1
**Commit/Build:** 591aa8a

When playing on Android the Multiplayer button is missing

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Install the latest debug apk
2. Launch it

**Screenshots / Video:**
http://i.imgur.com/tqJoyXS.jpg

**Comment by AaronVanGeffen** [comment]
This is left out on purpose, as the Android builds are compiled without network support.

**Comment by ApocalypsjeNL** [comment]
Why is it compiled without network support if I may ask?

**Comment by janisozaur** [comment]
Because compiling openssl is a hassle

**Comment by flipflop97** [comment]
If compiling openssl for Android is the problem, maybe you can take a look at [how Termux does it](https://github.com/termux/termux-packages/tree/master/packages/openssl) (Termux is a terminal emulator with an included package manager for Android).

**Comment by Gymnasiast** [comment]
@janisozaur Perhaps compiling LibreSSL would be less of a hassle? It omits a lot of useless junk in OpenSSL.

**Comment by janisozaur** [comment]
It's probably no big deal using one or the other, just need to find some motivation to do it.

**Comment by IntelOrca** [comment]
Perhaps we can do a similar thing to how zip works, have it use a Java proxy to something in the Android SDK?

**Comment by Gymnasiast** [comment]
@IntelOrca That might be better, yes.

**Comment by janisozaur** [comment]
This is done now.
