### ISSUE TITLE
Can't install?

### ISSUE THREAD

**Issue by CamGillies** [OpenRCT2/OpenRCT2#6147]
Windows 10
0.1.1 build 4601265

So I downloaded the installer properly, and run it which brings up the installer window.  This window then appears to immediately freeze.  I am unable to click next, cancel or X, and I can't even drag the window around my desktop.  I have to ctrl-alt-delete to close it.  I have tried earlier builds to the same effect.  Any advice?

**Comment by IntelOrca** [comment]
Could you attach a screenshot of the window that freezes?

**Comment by Nubbie** [comment]
@CamGillies Does this still occur?
