### ISSUE TITLE
Moving camera capped at 40fps

### ISSUE THREAD

**Issue by flipflop97** [OpenRCT2/OpenRCT2#6152]
**OS:** Arch Linux
**Version:** 0.1.1
**Commit/Build:** f253730

When moving the camera, either with the arrow keys, screen borders or dragging with the mouse, the movement still seems capped at 40fps even when the option `uncap FPS` is checked. It looks exactly the same when this option is unchecked. The camera movement should also happen at 60fps (or higher if the screen supports it).

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Check `uncap FPS`
2. Move the camera
3. Repeat the same with `uncap FPS` unchecked and compare the results

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by duncanspumpkin** [comment]
Moving the camera uses a lot of processing. Are you sure it's not that your computer can't render any more. Easy test would be lower the resolution and load an empty map

**Comment by flipflop97** [comment]
Yes, I'm noticing exactly the same with a new park and a really small resolution window. The camera movement is the same with or without the option checked.

**Comment by ZehMatt** [comment]
There are quite some changes required making the camera frame independent and I don't think its that easy, the movement speed uses a constant value based on 40 ticks, running faster than that makes the camera move a lot faster depending on how many frames you get. There are other UI things involved that would run too fast, I accidentally moved them before and everything was off.

**Comment by knexfan0011** [comment]
> There are quite some changes required making the camera frame independent and I don't think its that easy, the movement speed uses a constant value based on 40 ticks [...] .

I just stumbled upon something regarding this: When you move the camera using the ingame minimap, then the camera does actually update at a higher rate, at least 120hz!
I recorded the behavior here:
*[Video](https://www.youtube.com/watch?v=LGaGRi46ODQ).*
This was recorded at 120fps, then slowed down to half speed and 60fps, make sure to watch at 720p to get 60fps.
As you can see, the difference in smoothness between just the mouse(0:20) or arrow keys (0:40) and mouse movement through the minimap(1:05) is drastic.

This means the game already has support for a higher camera update rate (at least 120hz), it's just not used by the more common means of moving the camera for some reason.

**Comment by Richard-L** [comment]
@knexfan0011 this is amazing!!!!! That's the kind of panning we need.

Is it still this smooth when the game is unpaused though?

**Comment by Richard-L** [comment]
Interestingly, the smooth panning is also in effect when using the "Locate this on Main View" in ride windows or the entrance gate. Why is it the panning is so smooth here, but not otherwise when holding RMB?

**Comment by knexfan0011** [comment]
> @knexfan0011 this is amazing!!!!! That's the kind of panning we need.
> 
> Is it still this smooth when the game is unpaused though?

Yes it's not impacted by game speed at all, even on Turbo Speed it looks that smooth, I just wanted to eliminate any possible framedrops due to the added system load of recording at 120fps

**Comment by tellovishous** [comment]
This is something I just noticed myself. Can confirm that with Uncap FPS on, the view motion is still frame-locked, but it's totally smooth when changing the view from minimap or clicking the "Locate this" button. Would like this to be fixed.

**Comment by mrpenguinb** [comment]
RCT Classic has smooth camera panning, this would be a very nice QOL improvement and would heighten the game's presentation.
