### ISSUE TITLE
Inventarisation of remaining windows in libopenrct2

### ISSUE THREAD

**Issue by marijnvdwerf** [OpenRCT2/OpenRCT2#6154]
- [x] Banner.cpp.o
- [x] DemolishRidePrompt.cpp.o
- [ ] Dropdown.cpp.o
- [x] EditorBottomToolbar.cpp.o
- [x] EditorMain.cpp.o
- [x] EditorObjectSelection.cpp.o
- [x] Error.cpp.o
- [x] Finances.cpp.o
- [x] GameBottomToolbar.cpp.o
- [x] Guest.cpp.o
- [x] GuestList.cpp.o
- [x] InstallTrack.cpp.o
- [x] LoadSave.cpp.o
- [x] Map.cpp.o
- [x] MapTooltip.cpp.o
- [x] MazeConstruction.cpp.o
- [x] NetworkStatus.cpp.o
- [x] NewCampaign.cpp.o
- [x] NewRide.cpp.o
- [x] ObjectLoadError.cpp.o
- [x] Park.cpp.o
- [x] Player.cpp.o
- [x] Research.cpp.o
- [x] Ride.cpp.o
- [x] RideConstruction.cpp.o
- [x] RideList.cpp.o
- [x] Scenery.cpp.o
- [x] Sign.cpp.o
- [x] Staff.cpp.o
- [x] StaffFirePrompt.cpp.o
- [x] TextInput.cpp.o
- [x] TileInspector.cpp.o
- [x] TitleCommandEditor.cpp.o
- [x] TitleEditor.cpp.o
- [x] TitleScenarioSelect.cpp.o
- [x] Tooltip.cpp.o
- [x] TopToolbar.cpp.o
- [x] TrackList.cpp.o
- [x] TrackManage.cpp.o
- [x] TrackPlace.cpp.o

### Tooltip.cpp.o
 - `T` `window_tooltip_close` (input.c, `ui`)
 - `T` `window_tooltip_open` (input.c)
 - `T` `window_tooltip_reset` (input.c)
 - `T` `window_tooltip_show` (input.c)

### Dropdown.cpp.o
 - `T` `dropdown_index_from_point` (input.c)
 - `T` `dropdown_is_checked`
 - `T` `dropdown_is_disabled` (input.c)
 - `T` `dropdown_set_checked` (`ui`)
 - `T` `dropdown_set_disabled` (`ui`)
 - `D` `gAppropriateImageDropdownItemsPerRow` (land_tool.c, `ui`)
 - `S` `gDropdownDefaultIndex` (land_tool.c, input.c, `ui`)
 - `S` `gDropdownHighlightedIndex` (input.c, `ui`)
 - `S` `gDropdownIsColour` (input.c)
 - `S` `gDropdownItemsArgs` (land_tool.c,`ui`)
 - `S` `gDropdownItemsFormat` (land_tool.c, input.c, `ui`)
 - `S` `gDropdownLastColourHover` (input.c)
 - `S` `gDropdownNumItems` (`ui`)
 - `T` `window_dropdown_close`
 - `T` `window_dropdown_show_colour` (`ui`)
 - `T` `window_dropdown_show_image` (land_tool.c,`ui`)
 - `T` `window_dropdown_show_text` (`ui`)
 - `T` `window_dropdown_show_text_custom_width` (`ui`)

### EditorObjectSelection.cpp.o
 - `T` `reset_selected_object_count_and_size()`
 - `T` `tolower(int)`
 - `D` `typeinfo for list_item`
 - `S` `typeinfo name for list_item`
 - `T` `editor_check_object_group_at_least_one_selected`
 - `T` `window_editor_object_selection_open`

**Comment by marijnvdwerf** [comment]
Done:

# Windows that open with arguments

### Banner.cpp.o
 - `T` `window_banner_open`

### Player.cpp.o
 - `T` `window_player_open`
 - `D` `window_player_overview_widgets`
 - `D` `window_player_page_enabled_widgets`
 - `D` `window_player_page_widgets`
 - `D` `window_player_statistics_widgets`

### Sign.cpp.o
 - `T` `window_sign_open`
 - `T` `window_sign_small_open`
 - `D` `window_sign_widgets`


# Windows with different views

### Finances.cpp.o
 - `T` `window_finances_open`
 - `T` `window_finances_research_open`
 
### Park.cpp.o
 - `T` `window_park_awards_open`
 - `T` `window_park_entrance_open`
 - `T` `window_park_guests_open`
 - `T` `window_park_objective_open`
 - `T` `window_park_rating_open`

**Comment by marijnvdwerf** [comment]
- `EditorObjectSelection` either needs to be completely refactored, or the `remove_unused_objects` command needs to be removed.
- The tile inspector is still strongly coupled to methods in tile_inspector.c. Should probably use some form of callbacks for the actions instead.

**Comment by IntelOrca** [comment]
`remove_unused_objects` should be re-written to not use the object selection window.

**Comment by AaronVanGeffen** [comment]
Looks like Dropdown.cpp has been moved to the ui subproject in the mean time. Can this be closed?
