### ISSUE TITLE
AI Pathing Issues

### ISSUE THREAD

**Issue by OneKnight1** [OpenRCT2/OpenRCT2#6155]
**OS:** [Windows 10]
**Version:** [0.1.1]
**Commit/Build:** [63fbd13]

AI gets stuck in non-direct path. It seems like it tries to follow a path in a direct way to a ride, but will get stuck if there's a dead end along the path. Pictures probably explain better than my words do.

- [?] Reproducible in RCT2 (vanilla)? Unlikely, I don't think the AI is the same as in vanilla.

**Steps to reproduce:**
1.  Build an L-shaped path where one side is a large part of peep-traffic
2.  Add a ride on the lesser-used part of the path
3.  At the area close to the traffic, have a path that leads close to the ride, but ends up at a dead end.

**Screenshots / Video:**
Screenshot showing guests crowding in one area to go to a ride to the east.
![scr2](https://user-images.githubusercontent.com/30916290/29199482-e62bb46a-7e12-11e7-8ef4-e1adaa5cac90.png)

The ride in question with the path in view (just following the 3-width path).
![scr1](https://user-images.githubusercontent.com/30916290/29199486-ea88401e-7e12-11e7-83b9-22e2992236f3.png)

**Save game:**
[Big Lake in Center.txt](https://github.com/OpenRCT2/OpenRCT2/files/1216802/Big.Lake.in.Center.txt)

**Comment by duncanspumpkin** [comment]
You've made a path that is really hard to pathfind. Avoid loops that involve walking further away to get to a ride. This is a well known limitation of rct peep pathfinding.
