### ISSUE TITLE
Info log of a player to display what the person last actions were and when.

### ISSUE THREAD

**Issue by Tommygun7468** [OpenRCT2/OpenRCT2#6161]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** 63fbd13

Placement could be near the money symbol in the players window. Its purpose would be to show you the actions this player took (eg 11:51 - modify groups, 12:04 - Terraform)

- [x] Multiplayer?

**Comment by ZehMatt** [comment]
I believe with the new game action system this is covered as all parameters are written to the log.
