### ISSUE TITLE
Canoes clutter at station platform

### ISSUE THREAD

**Issue by flipflop97** [OpenRCT2/OpenRCT2#6168]
**OS:** Arch Linux
**Version:** 0.1.1
**Commit/Build:** f25e730

After building a canoe attraction and waiting a few minutes, guests seem to get stuck at the station entrance. They clutter with the result none of them can get to to station (once in a while some boat manages to get to the station, this happens not more than 1 time a minute). This issue seems to happen too with other attraction types like this but less often/severe than with canoes.

- [x] Reproducible in RCT2 (vanilla)?  
*Probably, I can vaguely remember this happening on rct2 but I can't test it right now.*
- [ ] Multiplayer?

**Steps to reproduce:**
1. Build a canoe attraction with many boats and many people using it.
2. See the boats clutter at the station entrance.

**Screenshots / Video:**
![screenshot from 2017-08-12 19-01-10](https://user-images.githubusercontent.com/13943260/29242662-1aea225c-7f91-11e7-81a9-5d82dec1d590.png)

**Save game:**
[Canoe Clutter.zip](https://github.com/OpenRCT2/OpenRCT2/files/1219929/Canoe.Clutter.zip)

**Comment by jensj12** [comment]
Duplicate of #866

**Comment by flipflop97** [comment]
Oops, didn't see that
