### ISSUE TITLE
Crash when open server headless using save file or take screenshot via command line

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#6184]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** 294cef3

When I open headless server using a save file, game crashes and multiplay server is not opened.
I used command line something like this:
``(game path)\openrct2.exe host "%USERPROFILE%/Documents/OpenRCT2/save/some savefile.sv6" --port (port_number) --headless``

It is normal and server is successfully opened when I use 14f92be, but this issue occurs just after 294cef3.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
(Explained above)

**Dump file**
[dump.zip](https://github.com/OpenRCT2/OpenRCT2/files/1225879/dump.zip)

**Comment by Nubbie** [comment]
Unhandled exception thrown: read access violation.
mainWindow was nullptr.

call stack;
```
>	openrct2.dll!game_load_init(...) Line 1194	C
 	openrct2.dll!OpenRCT2::Context::OpenParkAutoDetectFormat(IStream * stream=0x00000025ed8ff5c8, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & path={...}) Line 712	C++
 	openrct2.dll!OpenRCT2::Context::Open(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & path={...}) Line 376	C++
 	openrct2.dll!OpenRCT2::Context::Launch() Line 469	C++
 	openrct2.dll!OpenRCT2::Context::RunOpenRCT2(int argc=144606496, char * * argv=0x0000000000000000) Line 158	C++
 	openrct2.dll!NormalisedMain(int argc=6, char * * argv=0x0000013e089e8520) Line 53	C++
 	openrct2.dll!LaunchOpenRCT2(int argc, wchar_t * * argvW) Line 55	C++
 	[External Code]	
```
Autos
+		mainWindow	0x0000000000000000 <NULL>	rct_window *
		zoomDifference	Variable is optimized away and not available.

**Comment by telk5093** [comment]
Additional: There is a problem with taking screenshot via console command, seems to be related about this.
