### ISSUE TITLE
Number of guests on ride not fully invalidated

### ISSUE THREAD

**Issue by jensj12** [OpenRCT2/OpenRCT2#6185]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** cff7080

Half of the last '0' from '100' remains visisble after the number of guests drops to 99. If that alone doesn't trigger it, it's a maze with the capacity set to exactly 100 guests.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open the ride window, last tab
2. Have 100 guests on that ride
3. Wait till it drops to 99

**Screenshots / Video:**
(top-right corner)
![the openrct2 group park 6 2017-08-15 21-06-45](https://user-images.githubusercontent.com/13868449/29332583-cf89dfc4-8200-11e7-85fb-267fee138968.png)

**Comment by rik-smeets** [comment]
I can't reproduce this issue, it's probably been resolved sometime since this bug was submitted.
