### ISSUE TITLE
All rings in Space Rings use the same secondary colour

### ISSUE THREAD

**Issue by flipflop97** [OpenRCT2/OpenRCT2#6193]
**OS:** Arch Linux
**Version:** 0.1.2
**Commit/Build:** 4a3b54332

When changing individual colors for the Space Rings attraction the secondary color is not working as it should. The secondary color of ring 1 is used on all rings, the primary color is working fine.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open a scenario with Space Rings available
2. Build a new Space Rings attraction
3. Change the individual secondary colors of ring 2-4
4. Notice they don't change but instead use the color of ring 1

**Screenshots / Video:**
![screenshot from 2017-08-17 14-01-08](https://user-images.githubusercontent.com/13943260/29411341-bc79c96c-8354-11e7-9bdb-e7fa85df370b.png)

**Save game:**

[Botany Breakers.zip](https://github.com/OpenRCT2/OpenRCT2/files/1231163/Botany.Breakers.zip)

**Comment by janisozaur** [comment]
It looks like you're using commits that do not come from our repository.

Can you do one of the following:
a) verify the bugs reproduce on commits from our main branch `develop`
b) make sure the commit is found on GitHub
c) specify what commit on `develop` was it based on and what changes have been applied?

**Comment by flipflop97** [comment]
Hmm strange, I installed the game via the AUR package which should get the latest source directly from the releases page. I tested it on the latest develop version (4a3b54332) where this problem also exists. I'll update the versions in the bug report.
