### ISSUE TITLE
You cannot cancel RCT1 directory selection 

### ISSUE THREAD

**Issue by Invictaz** [OpenRCT2/OpenRCT2#6198]
Windows 7 64.
0.1.2 Develop

If you click on "select RCT1 files" the game minimizes and you get to see the directory window. If you cancel that the game is either still minimized or returns a black screen with music playing. CTRL ALT DELETE shows a game that is not responding.

**Comment by Keatzee** [comment]
Reproduced on Windows 7 64bit. The game has to be in fullscreen mode; windowed mode works fine. It's stuck at `ShowDirectoryDialog()` on line 156 of UiContext.Win32.cpp.

**Comment by Chaosmeister** [comment]
I'm on it!
