### ISSUE TITLE
Inverted Hairpin Coaster vehicle tab is not centered 

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#6199]
**OS:** Windows 7
**Version:** 0.1.2
**Commit/Build:** 6547116

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

Screenshot:
![2017-08-18 19-43-52](https://user-images.githubusercontent.com/28242696/29481291-a1b6c7ac-844d-11e7-84cb-0995c6c9686e.png)

**Comment by rpstester** [comment]
Also occurs on Windows 10, build 40b026a
