### ISSUE TITLE
RCT1 scenario import - custom scenarios are not imported

### ISSUE THREAD

**Issue by black1104** [OpenRCT2/OpenRCT2#6201]
**OS:** Windows 10 (x86-64)
**Version:** 0.1.2
**Commit/Build:** 6547116 provided by AppVeyor

Custom RCT1 scenarios (competition parks replacements) are not imported to OpenRCT2.

I found only 2 scenarios. If there is a need for it then I can upload .zip file with both.

[Example scenario 1](http://rctgrotto.coastergrotto.com/file.jsp?argId=334)
[Example scenario 2](http://rctgrotto.coastergrotto.com/file.jsp?argId=335)

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Install custom scenarios for RCT1 (Drexler patch might be required) and make sure that they work
2. Set RCT1 location in OpenRCT2 and restart
3. Try searching for scenarios in scenario selection

**Comment by nccvoyager** [comment]
This may be related to #6250 as the competition scenarios do not create an entry in OpenRCT2, but an "empty" field does appear in OpenRCT2 when they are in the RCT Scenarios directory.
This appears to be true for all "competition" scenarios, including the "official" ones.

The full set of "official" competition scenarios is available here:
http://www.jumpjet.info/Classic-Games/Windows/RCT/Scenarios/Scenarios.html
(About half way down the page.)
From what I can tell, these are in fact the "official" competition scenarios, and are linked to from the RCT wiki.
http://rct.wikia.com/wiki/Competitions

While the three promotional magazine "Extra" scenarios are loaded properly by OpenRCT2, the "competition" scenarios simply fail to show up, a single empty field being created instead.

All of these "official" competition scenarios, (as well as the unofficial RCTOA Acres sandbox,) load properly in RCT, and a "Competitions" tab is shown if any one of them is in the RCT Scenarios directory.

Using GOG RCTD release, and GOG RCT2TTP release. 
(Current OpenRCT2 version questionable; downloaded September 10th, installer labelled release-20170527.)

**Comment by Gymnasiast** [comment]
Hm, interesting thought. It could be true as I believe I have RCTOA Acres installed. I'd have to test that.
