### ISSUE TITLE
Guests are not ejected from Broken benches

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#6202]
**OS:** Any
**Version:** Any
**Commit/Build:** Any

If a guest is sitting on a bench when it is broken, the guest is not removed from the bench. Instead, they continue to sit there, until they decide to get up.

- [x] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Have guest on Bench
2. Another guest breaks the bench
3. The guests continues sitting on the broken bench.

![](https://files.gitter.im/PFCKrutonium/OpenRCT2-OpenScenarios/LPoV/Luciferous-Woods-2017-08-19-22-45-18.png)

**Comment by ipatix** [comment]
Do the broken benches affect anything except visuals and vandalism thoughts of the guests?

**Comment by Gymnasiast** [comment]
Yes, no guests will sit down on a broken bench.

**Comment by ipatix** [comment]
@PFCKrutonium said this happens in vanilla too. So it might be intended behaviour.

**Comment by ZehMatt** [comment]
I would propose that peeps don't break benches where other peeps sit on.

**Comment by adammunich** [comment]
If I recall correctly, guests didn't do this in the original game either.

**Comment by Keatzee** [comment]
I think that if a bench is broken while a peep is sitting on it, that peep should become angry and start breaking benches too :smiling_imp:

**Comment by PFCKrutonium** [comment]
@adammunich They would continue to sit on a broken bench in vanilla too, but I hardly think this is intended behavior @ipatix
