### ISSUE TITLE
Load save game window not changing colors when a custom theme is applied

### ISSUE THREAD

**Issue by GustavGoblin** [OpenRCT2/OpenRCT2#6207]
**OS:** Windows 7
**Version:** 0.1.2
**Commit/Build:** [e.g. 6547116]

When the Load/Save colors are changed for a custom theme, the load screen is still blue.

![blank slate 2017-08-20 21-55-05](https://user-images.githubusercontent.com/30665347/29503632-a49795aa-85f6-11e7-833b-ae45ef7f5a7f.png)

**Comment by Gymnasiast** [comment]
Can't reproduce this on 65ab767.

**Comment by AaronVanGeffen** [comment]
Yeah, this was addressed in #6408.
