### ISSUE TITLE
Ride Time In 3 Particular Parks Suddenly Ridiculously High

### ISSUE THREAD

**Issue by jamtraks** [OpenRCT2/OpenRCT2#6209]
**OS:** vista 32-bit
**Version:** launcher v. 0.0.6 x86
**Commit/Build:** build 2720  hash 6547116

The ride lengths of all "timed" rides in three parks i have created and saved, are suddenly ridiculously high and inaccurate.  

- [ did not test ] Reproducible in RCT2 (vanilla)?  
- [ did not test ] Multiplayer?

**Steps to reproduce:**
1. open a park and check ride's "ride times"
2. 

**Dump file**
n/a
**Screenshots / Video:**
![ridetime](https://user-images.githubusercontent.com/17103908/29537026-1d19161a-868e-11e7-9309-07a9937a27a4.jpg)
**Save game:**
[Crazy Castle By Josh Marsilio 3.63.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/1240064/Crazy.Castle.By.Josh.Marsilio.3.63.sv6.zip)

**Comment by Gymnasiast** [comment]
Some months ago, there was a bug that broke ride times. It was fixed after a few days.
You most likely created your save in that broken version.

It should not occur with rides created in current versions of OpenRCT2.

**Comment by jamtraks** [comment]
well wthell am i supposed to do now?

**Comment by PFCKrutonium** [comment]
Replace the ride.

**Comment by Gymnasiast** [comment]
No, you don't need to replace it. Just enter construction mode, clearing the stats and test the ride again. Or just ignore it, it's harmless.

**Comment by jamtraks** [comment]
If there was a bug that broke the ride times, there should just as easily be a "bug" that can fix them again, this is really silly.

**Comment by Gymnasiast** [comment]
No, that's not how it works at all. The original value is gone. Just do the above steps, you only need to do it once.
