### ISSUE TITLE
The "Find your RCT2 Files" window is far larger than needed

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#6215]
**OS:** Arch Linux
**Version:** 0.1.2
**Commit/Build:** 90ea8eee8

It's _huge_
![massive](https://user-images.githubusercontent.com/3945538/29698028-9d2f23aa-8920-11e7-9bf3-b016c5045578.png)

Perhaps it should be smaller?

**Comment by Gymnasiast** [comment]
It's a Zenity quirk, I think. We could force a new line, though.
