### ISSUE TITLE
Can't build Android app

### ISSUE THREAD

**Issue by RQWorldblender** [OpenRCT2/OpenRCT2#6216]
**Version:** 0.1.2-develop
**Commit/Build:** 90ea8eee88b89760a4dddcdcf34cffdbe727a8a5

When running gradle or gradlew in the openrct2-android folder, the build runs as expected, but ends in:
`  clang: error: no such file or directory: '/home/richard/OpenRCT2/src/openrct2/rct2.c'
  clang: error: no input files
  ninja: build stopped: subcommand failed.
`
 The only way to get rid of this error is to stop referencing the no-longer existing file in question. All that exists is `rct2.h`, which doesn't help me solve my compilation problems.

**Comment by janisozaur** [comment]
That's odd. Are you sure you're not using cached project? All the cmake projects are set up to use only the current sources and we have evidence it builds just fine: https://travis-ci.org/OpenRCT2/OpenRCT2/jobs/268528806

**Comment by janisozaur** [comment]
That's odd. Are you sure you're not using cached project? All the cmake projects are set up to use only the current sources and we have evidence it builds just fine: https://travis-ci.org/OpenRCT2/OpenRCT2/jobs/268528806

**Comment by RQWorldblender** [comment]
I solved my own problem by having to remove the `openrcts-android` directory, then resetting it by `git checkout --force HEAD`. That took away the traces of my old build, and now my build continues as normal.
