### ISSUE TITLE
Alternative locations for toolbars

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#622]
Some people may want to left align, centre or right align their top and bottom toolbars. Perhaps even a custom location, particularly if the application window is spread across multiple monitors.

**Comment by RollingStar** [comment]
Building an in-game way to re-arrange the buttons might be overkill. Assuming people do want to re-arrange their buttons, a list of X,Y co-ordinates for each button could be placed in the config file instead.

And most people are probably fine with the buttons staying in the same spot they've always been.

**Comment by Patrik356b** [comment]
It would be nice if you could rearrange the toolbar locations like in Need For Speed Porsche.
(You hold down a key combo, game gets paused and you can move everything around as you want, hit enter to save or esc to discard the changes)

**Comment by janisozaur** [comment]
See also https://www.reddit.com/r/rct/comments/3xuxlz/orct_moving_menus_for_multiple_monitors/

I imagine we could possibly make the toolbar follow the cursor so it would be available on the screen you're currently using. If you move the cursor to another screen, the toolbar will do so too.

**Comment by marijnvdwerf** [comment]
What if you would make the toolbar order a config file option? No UI for customizing it, except maybe for enabling/displaying features.
```
top_toolbar = pause | fastforward | file_menu | network | cheats | debug | - | zoom_out | zoom_in | rotate | view_menu | map | ~ | news | guests | staff | park | rides | research | finances | - | construct_ride | path | scenery | water | land | clear_scenery
```

Would be parsed ignoring whitespace. Vertical bars would seperate the different items. `-` would be simple fixed-width whitespace, ~ would be fluid width whitespace, value gets calculated based on current screen width, minus other content, divided by number of fluid whitespace items. If there is no fluid whitespace in the toolbar, it will be appended at the end (making the toolbar left aligned)

**Comment by Horsti12** [comment]
This would be a very good feature :)
