### ISSUE TITLE
Place objects on paths while press Ctrl

### ISSUE THREAD

**Issue by fuchsilp** [OpenRCT2/OpenRCT2#6220]
Placing every bench, bin, light and so on alone could be a quite cumbersome work in RCT.

As OpenTTD player, i have a feature idea.

In OpenTTD you can let the game build signals all along a track to the next switch when you build a single signal, keep holding left mouse button and CTRL, then you move the mouse few tiles along the track and release the buttons/keys. The result is placed signals with the given distance to each other on the track.

Would be great to have such a feature in OpenRCT2.

**Comment by Gymnasiast** [comment]
Something for a plug-in.


Also, CTRL is already tied to locking the height of a scenery object.

**Comment by fuchsilp** [comment]
Yes, that is true, I used CTRL in my text because OpenTTD uses this key for that function. But any other key is also okay.

**Comment by jensj12** [comment]
CTRL currently doesn't do anything when placing benches/bins/lamps/signs.
