### ISSUE TITLE
Make the invention list window in scenario editor resizable

### ISSUE THREAD

**Issue by Keatzee** [OpenRCT2/OpenRCT2#6221]
The invention list window in the scenario editor is currently really clunky and awkward to use, especially when you have a long list of inventions. I think making the window resizable (like the object selection window) would help quite a bit.

**Comment by ReikaKalseki** [comment]
Also nice would be some sort of "group by ride type" or "sort by 'tier'" features, to eliminate the bulk of the busywork. It is a massive pain to ensure your first unlocked coaster is not the MultiDimension or Heartline (with more 'basic' coasters like Suspended, Standup, and Virginia Reel being unlocked far later) when the initial sorting is completely random.
