### ISSUE TITLE
Some guests have too much energy

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#6223]
**OS:** Windows 10
**Version:** [e.g. 0.1.1]
**Commit/Build:** 6547116

In my savegame, some guests have too much energy :P Their energy value seems to be too high (underflow or overflow issue?) and thus causing the energy bar in their information tab to go outside the window. See attached screenshot.

**Steps to reproduce:**
1. Load the attached savegame.
2. Look for Christel K. (one of the guest affected by this issue)
3. Look at here personal information tab: look at the energy value bar.

**Screenshots / Video:**
![knipsel](https://user-images.githubusercontent.com/4948213/29776840-46523094-8c0a-11e7-9352-4345b1914286.PNG)

**Save game:**
[ANMAopen.zip](https://github.com/OpenRCT2/OpenRCT2/files/1256986/ANMAopen.zip) (ignore the silly names XD)

**Comment by Gymnasiast** [comment]
If you load up the park in vanilla, does this guest have low energy, or?

**Comment by mrtnptrs** [comment]
@Gymnasiast I will try to get vanilla to work and test this. I will report back soon

**Comment by mrtnptrs** [comment]
I can't reproduce this in vanilla. There the energy bar is correctly filled. So, it probably is an OpenRCT2 issue only.

**Comment by PFCKrutonium** [comment]
Probably related to #6196

**Comment by duncanspumpkin** [comment]
It might be related to the change to energy recently that capped it at 127 instead of the full 255 range.

**Comment by Gymnasiast** [comment]
@duncanspumpkin Not sure if that is the cause. 128 seems to be the limit - check the drawing code in the Guest window - the math will draw 255 happiness as full, but 128 energy as full. I capped it at 128 since that appeared to be the maximum

**Comment by ccoors** [comment]
I have the same issue with 1f3ccae8b17b7c29d10c4dd14751f2d9e6c586d8. He just sits on a bench forever and doesn't get up.

![tyson](https://user-images.githubusercontent.com/8963459/30004203-2f8d4b76-90cb-11e7-8a71-d9f872f0dece.png)

**Comment by Gymnasiast** [comment]
Has been solved by https://github.com/OpenRCT2/OpenRCT2/commit/6621faf27a6c059899b7bd3a6575c05c7c92e400.

_Was_ related the PR Duncan mentioned, but not because of the capping value. I mucked up a min/max somewhere else.
