### ISSUE TITLE
Failed starting up in Ubuntu 14.04

### ISSUE THREAD

**Issue by ApocalypsjeNL** [OpenRCT2/OpenRCT2#6226]
**OS:** Ubuntu 14.04 amd64
**Version:** 0.1.2
**Commit/Build:**519d5bc

When trying to launch or set the rct2 data path with ./openrct2 it throws this error:
./openrct2: relocation error: /home/apocalypsjenl/Documents/OpenRCT2/libopenrct2.so: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Try to open openrct2 file in Ubuntu 14.04

**Comment by janisozaur** [comment]
Ubuntu 14.04 is too old and not supported by us. You can still compile it yourself, if you want to.

https://github.com/OpenRCT2/OpenRCT2/issues/6112 might help, but it's still far off in the future.
