### ISSUE TITLE
Scenery doesn't cost to build when included in a saved design

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#6229]
**OS:** Windows 10
**Version:** 0.1.1
**Commit/Build:** 6b48f43

When you build a saved design that has scenery included, it costs the same as it does without saved scenery, as you can see [here](http://imgur.com/a/3Myey).

This does not happen in vanilla.

**Comment by jensj12** [comment]
Possibly caused by #6094.
