### ISSUE TITLE
win32:malware-gen virus detected in latest launcher upload

### ISSUE THREAD

**Issue by jamtraks** [OpenRCT2/OpenRCT2#6236]
**OS:** vista 32-bit
**Version:** 0.0.6
**Commit/Build:** OpenRCT2 Build: 2683, OpenRCT2 Git Hash: 247fdc2

i was getting a message of a blocked virus, "win32:malware-gen"  by my anti virus software, now i am just getting a "connection closed" message at the end up the launcher's upload and the game won't open. 

- [no ] Reproducible in RCT2 (vanilla)?
- [na ] Multiplayer?

**Steps to reproduce:**
1. open launcher
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by Gymnasiast** [comment]
We can't do much about, pardon my French, crap virus scanners that detect malware that _isn't there_.

(You're using an outdated version of OpenRCT2, by the way.)
