### ISSUE TITLE
Problem with a specific park

### ISSUE THREAD

**Issue by HoeGaatie1611** [OpenRCT2/OpenRCT2#6238]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** ef5ad36

I wanted to create a huge park ($2.000.000 park value challenge), but after about 4 hours playing the game keeps crashing. I've got no idea why and I haven't got much information either. The only thing I can say is that

- The game freezes and you will just get the "This program has stopped working" message. No specific error boxes.
- On this specific save it will crash on March 14'th.
- When you close down all the rides it won't crash.
- The save file won't open at all on the unmodded version of RCT2.
- Closing down the Observation tower delays the crash by about 1.5 month (Arround April 18).
- Closing down the first Launched Freefall makes the game crash even quicker.
- Closing down the Reverse Freefall Coaster delays the crash too.

When I tried to close down all the rides and open them one by one, the game still crashed no matter in what order I opened the rides
That's about all the information I've got. I've tried to google the problem, but couldn't find the answer. Hopefully someone can help me with this. I'm currently running the latest version for windows.

Thanks in advance!

Sidenote: Also the game crashed before this whole situation, and that crash included a dmp file. Maybe it can help.

[Rollercoaster Tycoon 2 Corrupted Save.zip](https://github.com/OpenRCT2/OpenRCT2/files/1270591/Rollercoaster.Tycoon.2.Corrupted.Save.zip)

**Steps to reproduce:**
1. Simply open the save game
2. Wait until March 14'th

**Dump file**
Dump file including the save has been provided in the Zip file above.

**Save game:**
Save game has been included in the Zip file above.

**Comment by ZehMatt** [comment]
It seems that its trying to find the peep in the queue which is at the front and gets stuck there.

**Comment by ugattie1611** [comment]
Thanks for the answer. It makes sense, but is there a way to fix it?

**Comment by jensj12** [comment]
You can remove all guests in the park (look in the cheats window), that should get rid of any loop in queued peeps.
