### ISSUE TITLE
what is win32:malware-gen?

### ISSUE THREAD

**Issue by jamtraks** [OpenRCT2/OpenRCT2#6240]
**OS:**vista 32-bit
**Version:** launcher version 0.0.6
**Commit/Build:** Build: 2683 Hash: 247fdc2

when i try to run the launcher and at the end of it's download, my avg anti-virus software is detecting "win32:malware-gen", and blocking openrct2 from opening. What is win32:malware-gen? is this something that is always detected or attached to the openrct2 download for everyone, or is this being generated or injected by something else on my computer such as a virus that only i have??? i'd really like to know if this file is truly harmless and something that everyone downloads or if it is coming from something else...
and if this is always attached to the openrct2 download what is it exactly and why is it there?

- [ na] Reproducible in RCT2 (vanilla)?
- [na ] Multiplayer?

**Steps to reproduce:**
1. run and download openrct2 with launcher
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by Keatzee** [comment]
The launcher is independent from OpenRCT2 and is not developed here. Please leave an issue at [PFCKrutonium/OpenRCT2Launcher](https://github.com/PFCKrutonium/OpenRCT2Launcher) and @PFCKrutonium will help you out

**Comment by Keatzee** [comment]
And by the way, don't panic, it's a false alarm

**Comment by jamtraks** [comment]
okay, i posted my question there thankyou anyway.

**Comment by rwjuk** [comment]
Closing this as it's not related to the core project.
