### ISSUE TITLE
multi-dimension coaster's car-angulation inacurate

### ISSUE THREAD

**Issue by jamtraks** [OpenRCT2/OpenRCT2#6245]
**OS:**vista 32-bit
**Version:** 0.1.2 x86
**Commit/Build:** 49066ba

This multi dimension coaster's car angulation is non reflective of what i programmed. Several game updates ago the ride _was_ displaying the car-angles that i programmed. I tested this coaster in vanilla by opening the same exact park in vanilla, and the coaster's car angulations **_were_** reflective of what i intended.

- [does not occur in vanilla] Reproducible in RCT2 (vanilla)?
- [did not test] Multiplayer?

**Steps to reproduce:**
1. observe car-angulation of coaster while it operates in openrct2 vs. observing it's car angulation while it operates in vanilla.
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

[the fourth dimension by  JoshMarsilio 1.0.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/1272707/the.fourth.dimension.by.JoshMarsilio.1.0.sv6.zip)

**Comment by janisozaur** [comment]
Can you provide a version where it worked properly for you?

**Comment by jamtraks** [comment]
Just now, I opened two other versions of the coaster that haven't been altered, and were saved about 16 months ago. Those two other versions are having the same problem. Like i said before, if i open these save files in vanilla the cars angulate the way i intended, but in openrct2 there is suddenly a problem that wasn't there about a month ago. So the problem seems to be in the openrct2 software.

**Comment by jensj12** [comment]
There is most likely a change in the code responsible for the MD coaster, that changed how the cars react to the given rotation angles. If there's an OpenRCT2 version we know the code worked fine of, it greatly helps the debugging process.
Try to find the paint debug window and check 'use RCT2/original/vanilla drawing code' to see if it makes a difference.

**Comment by janisozaur** [comment]
I don't think that option works anymore

**Comment by marijnvdwerf** [comment]
"vanilla drawing mode" never worked for tracked vehicles, afaik.

**Comment by jamtraks** [comment]
No, checking 'use RCT2/original/vanilla drawing code' didn't fix the problem. Also it would be very difficult for me to reinstall older versions of orct2 to check for which version did work, but if i find some extra time i might do that.

**Comment by oli414** [comment]
My investigation so far: Setting `VEHICLE_ENTRY_FLAG_7` will actually allow the seat rotation to be drawn properly. This flag, however, isn't in the ARRX.dat (Multi-dimension coaster) object file. My guess would be that a different, redundant, flag is set specifically for the multi-dimension coaster of which the flag-check has gone missing since a certain update.

Does anyone happen to know of a flag that is unique to the multi-dimension coaster?
