### ISSUE TITLE
Invalid entry in RCT1 Scenario List

### ISSUE THREAD

**Issue by RoelerCoaster** [OpenRCT2/OpenRCT2#6250]
**OS:** Windows 10
**Version:** 0.1.2-develop
**Commit/Build:** a13c307

At the top of the RCT1 Scenario list is an empty, invalid scenario entry.
Clicking on it crashes the game.

I also get multiple errors like this in the console:
`Scenario conflict: '' ignored because it is newer.`

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Screenshots / Video:**

![rct1scenarioentry](https://user-images.githubusercontent.com/5968886/30005899-ca2dcd24-90ec-11e7-8245-e1d13ccceaa9.png)

**Comment by Gymnasiast** [comment]
Can confirm. I have it too, but only on one of my systems.

**Comment by Gymnasiast** [comment]
Ok, I think I found the cause: it cannot handle custom RCT1 scenarios. It finds a .SC4, tries to give it a name, but fails. It ends up with index 0 (the same as Forest Frontiers).

Here is an example:
[rctoa.zip](https://github.com/OpenRCT2/OpenRCT2/files/1350316/rctoa.zip)

@RoelerCoaster Do you know if you have custom RCT1 scenarios installed?

**Comment by RoelerCoaster** [comment]
Are the official competition scenarios and promotional scenarios considered custom? Because then the answer is yes.

**Comment by Gymnasiast** [comment]
Just checked. As far as the _code_ is concerned, the competition scenarios are considered custom. (That is, they need to be added to the list to be considered official.)

**Comment by RoelerCoaster** [comment]
The entry is now gone, but now the following error message is printed multiple times every time I open the scenario window:
`ERROR[scenario\ScenarioRepository.cpp:492 (ScenarioRepository::AddScenario)]: Tried to add scenario with an empty filename!`
Is that supposed to happen now?

**Comment by Gymnasiast** [comment]
No. Can you send me the custom scenarios?

**Comment by RoelerCoaster** [comment]
I got them from here if I remember well: http://www.jumpjet.info/Classic-Games/Windows/RCT/Scenarios/Scenarios.html

But I also attached the ones I have just to be sure:
[CompetitionScenarios.zip](https://github.com/OpenRCT2/OpenRCT2/files/1353630/CompetitionScenarios.zip)

**Comment by Gymnasiast** [comment]
I cannot reproduce this issue with the ones you included. Do you happen to have more custom ones?

**Comment by RoelerCoaster** [comment]
I deleted `scenarios.idx` to generate a fresh one and that seemed to have solved the problem. I guess it still contained invalid data from before the fix?

**Comment by Gymnasiast** [comment]
Most likely, yes. Since they _were_ on the list (just with an empty name), the code to reindex them was not called.
