### ISSUE TITLE
Completing RCT1 scenarios doesn't display check + name

### ISSUE THREAD

**Issue by JarnoVgr** [OpenRCT2/OpenRCT2#6252]
**OS:** Windows 10 x64
**Version:** 0.1.2
**Commit/Build:** a13c3079

Completed RCT1 scenarios (either from a GOG or Steam RCT Deluxe installation) do not show the check + name. And thus, doesn't unlock other scenarios.

**Steps to reproduce:**
1. Win a scenario by either using the cheat or by playing. Enter name.
2. View "Start new game" list. Completion does not display.

**Comment by AaronVanGeffen** [comment]
Related to #6250, probably.
