### ISSUE TITLE
Make install fails because of incorrect sha1sum

### ISSUE THREAD

**Issue by PeterMitrano** [OpenRCT2/OpenRCT2#6256]
**OS:** [Ubuntu]
**Version:** [16.04]
**Commit/Build:** [a13c30795db9ef757ec964eb04ed7d6818cbb9ab]

When cmake downloads the title sequences zip, it gets the hash of `da39a3ee5e6b4b0d3255bfef95601890afd80709` which is incorrect. Downloading the file manually works.

**Steps to reproduce:**
1. `cmake .. && sudo make install`

** Error output **
```
CMake Error at cmake_install.cmake:40 (file):
  file DOWNLOAD HASH mismatch

    for file: [/usr/local/share/openrct2/title/title-sequences.zip]
      expected hash: [b587d83de508d0b104d14c599b76f8565900fce0]
        actual hash: [da39a3ee5e6b4b0d3255bfef95601890afd80709]
             status: [1;"Unsupported protocol"]

```

**Comment by janisozaur** [comment]
`da39a3ee5e6b4b0d3255bfef95601890afd80709` is the sha1sum of empty input. check your internet connectivity.

**Comment by PeterMitrano** [comment]
My connection is fine, and it's totally reproducible for me. But you're right, the resulting file is empty. I think it has to do with CMake not using openssl. I'm using cmake 3.7.1. I'll post the solution here once I find it so others can benefit.

**Comment by janisozaur** [comment]
Do note this can be due to use of `sudo`, if your system has some files lying around from earlier build or `sudo` is stripping your environment of variables e.g. `https_proxy`. Easy way to check would be cleaning the build, doing e.g. `make package` or `make DESTDIR=//some/directory/ install` and then you can retry with `sudo`.

**Comment by PeterMitrano** [comment]
**compiling cmake with --system-curl fixed it**. I also upgrade to cmake 3.9 but I doubt that was it. 

This post was what helped me [https://stackoverflow.com/a/33512778/3353601](https://stackoverflow.com/a/33512778/3353601)
