### ISSUE TITLE
Peeps cannot find park exit after moving in sandbox mode.

### ISSUE THREAD

**Issue by saxman1089** [OpenRCT2/OpenRCT2#6261]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** 2e8d1b5

Working on a park that's a re-creation of a real-life park. Moved the park entrance using the sandbox mode, now peeps have major trouble finding the exit. Cannot fix by replacing the original entrance. 

Tried to reproduce in a different park, but couldn't reproduce the issue. I've attached the park I'm having the issue in.
[Knoebels_v1.10 - Copy.txt](https://github.com/OpenRCT2/OpenRCT2/files/1290212/Knoebels_v1.10.-.Copy.txt)

**Comment by Gymnasiast** [comment]
Is the new entrance properly connected to the path? Could you provide a screenshot?

**Comment by saxman1089** [comment]
Entrance is a custom-invisible entrance, but using the tile inspector, it is connected. Also independently verified over at the OpenRCT forums by another person (imlegos). Screenshots are attached showing the paths outside and inside the park.

![knoebels amusement resort 2017-09-10 14-01-36](https://user-images.githubusercontent.com/20549965/30251592-bf6d2648-9630-11e7-9536-c8fb38f81bd0.png)
![knoebels amusement resort 2017-09-10 14-01-48](https://user-images.githubusercontent.com/20549965/30251593-c0dad444-9630-11e7-8c6b-5a1decc75180.png)

**Comment by zaxcav** [comment]
I took a look at the save and replied in the forums.
The problem is inconsistent path edge connections further up the path.
This is breaking the generation of the wide flags which in turn interferes with correct function of the pathfinding.
This screenshot shows where there are some troublesome path tiles with inconsistent edge connections between neighboring path tiles.
![bad_edges1](https://user-images.githubusercontent.com/20344978/30296569-e77210b2-9744-11e7-8fde-b617418232c4.png)
 In the example shown (the path tile under the tree next to the bench where all the peeps turn the corner) all the edge connections are preset.  This is inconsistent with the neighboring path tile with the bench (the bench would not appear if all edges were connected).

**Comment by saxman1089** [comment]
So it is definitely park specific! Thanks for your help. I'll need to find a new way to make those full tile gravel  portions under the trees without having large inconsistent path matches.

**Comment by saxman1089** [comment]
So this issue has popped back up, in the same park. All the paths have been fixed, and peeps still are having major issues finding the exit. @zaxcav posted this over on the forums:

"The pathing looks fine.  The wide path flags calculated from the edges look normal.
I turned on the path finding debugging to see if there's something weird happening there.
The peeps leaving the park are using the following location for their destination: x: 2, y: 75, height: 14.
The exit location is however at x:2, y: 94, height: 14.
This explains why they aren't leaving.
I added some debugging to print out the entrance location in the map data.
There are 2 park entrance locations in the map data:
Entrance 0: 2, 94, 14
Entrance 2: 2, 75, 14
At what ever location the currently stuck peeps were when they decided to leave, they were closer to the entrance 2 location.
How you get rid of this obsolete entrance location data I do not know.
Maybe someone else can help you out there."

**Comment by saxman1089** [comment]
Here's the save file.

[Knoebels_v1.22.zip](https://github.com/OpenRCT2/OpenRCT2/files/1326975/Knoebels_v1.22.zip)

**Comment by zaxcav** [comment]
@saxman1089 To help understand this problem better, do you recall how you removed the entrance that was previously at location 2, 75? Did you use the scenario editor or the tile inspector?

**Comment by saxman1089** [comment]
It was removed using the scenario editor.
