### ISSUE TITLE
RCT1 Scenarios - Loading a Saved RCT1 Scenario Causes Park Pricing Conversion

### ISSUE THREAD

**Issue by WittyWhiscash** [OpenRCT2/OpenRCT2#6264]
**OS:** Windows 10
**Version:** 0.1.1
**Commit/Build:** 4601265

Loading a save from an imported RCT1 scenario, played in RCT2, and then saved in RCT2 (Basically using the import path for RCT1 and playing the scenarios through there), causes an odd pricing conversion from the park being FtE, PfR (Free to Enter, Pay for Rides) to PtE, FfR (Pay to Enter, Free for Rides).

**Steps to reproduce:**
1. Ensure your path to your RCT1 installation has been defined in the options menu.
2. Open up an RCT1 scenario from the OpenRCT2 menu list.
3. This instance of the scenario should, theoretically, be FtE, PfR.
4. Save it and close down the program.
5. Restart the program, and load up the scenario.
6. Theoretically, it should be PtE, FfR.

**Dump file**

**Screenshots / Video:**

![dynamite dunes 2017-09-11 16-55-33](https://user-images.githubusercontent.com/21300678/30300526-5bcf6384-9712-11e7-9b9c-9da17d725b55.png)
![leafy lake 2017-09-11 16-56-15](https://user-images.githubusercontent.com/21300678/30300534-6b35af72-9712-11e7-903e-6a4a69fe5317.png)

For absolute specifics: 

**BEFORE** Saving and Closing down the program
![diamond heights 2017-09-11 16-56-36](https://user-images.githubusercontent.com/21300678/30300543-75a21e6e-9712-11e7-8be4-ba21c3b9b43c.png)

**AFTER** Saving and Closing down the program
![diamond heights 2017-09-11 16-57-35](https://user-images.githubusercontent.com/21300678/30300557-975f77ea-9712-11e7-8ba3-7c818b359190.png)

**Save game:**

[RCT Saves For Inspection.zip](https://github.com/OpenRCT2/OpenRCT2/files/1294282/RCT.Saves.For.Inspection.zip)

Quick notes: *Leafy Lake* and *Dynamite Dunes COMPLETION* are scenarios that have been completed, while *Diamond Heights* was just opened up and had some prices tinkered with before making the save.

**Comment by Gymnasiast** [comment]
RCT1 parks were either PtE, PtR (original, AA) or FtE, PtR. The former is not supported in SV6 (as is only supports PtE, FtR and FtE, PtR). We turn on a cheat (Unlock all prices) on the first import, but if you load up your game again, you will need to turn it on yourself.

This is a very well known issue to us, but one we cannot get rid of without first moving off SV6.
