### ISSUE TITLE
Ride count is 255 for clients that join a server

### ISSUE THREAD

**Issue by 60trainhunter** [OpenRCT2/OpenRCT2#6267]
**OS:** [Windows 10]
**Version:** [0.1.2]
**Commit/Build:** [0.1.2 build c6e162e]

park tab says 255 rides when there is no rides in ride list!

- [ ] Reproducible in RCT2 (vanilla)?
- [ yes] Multiplayer?

**Steps to reproduce:**
1. try to build something! in muiti server as a player! not host!
![razor rocks 2017-09-13 00-58-48](https://user-images.githubusercontent.com/30908785/30360342-c773bbd2-981e-11e7-97ac-952487fc38b1.png)

2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by Gymnasiast** [comment]
Please fill in the form correctly. You didn't specify OS, version or build.

**Comment by 60trainhunter** [comment]
fixed the form.

**Comment by Gymnasiast** [comment]
It is an underflow. It subtracts 1 from a number that cannot be negative, which therefore rolls over to 255. A bug, but not really a 'major bug'.

**Comment by IntelOrca** [comment]
What are the steps to reproduce this?

**Comment by 60trainhunter** [comment]
just run a test server and pick a scenario and have someone build anything. Under this build. Or you can visit. Mot server 0 to see for yourself.  Then you should get that desync box too.

**Comment by 60trainhunter** [comment]
This Happens the very start of the map!!

**Comment by IntelOrca** [comment]
OK - yes this is a fairly bug. When the client joins, their ride count is 255 which means that new rides built by the server or other client will error for the client with a too many rides error.
