### ISSUE TITLE
Demolishing a launched freefall track piece removes the entrance and exit

### ISSUE THREAD

**Issue by flipflop97** [OpenRCT2/OpenRCT2#6274]
**OS:** Arch Linux
**Version:** 0.1.2
**Commit/Build:** 867779362

When demolishing a piece of a attraction like a launched freefall (similar attractions like roto-drop are also affected) the entrance and exits are removed, which shouldn't happen.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Build a custom launched freefall or similar ride.
2. Build a few track pieces and place the entrance and exit.
3. Demolish a track piece and watch the entrance and exit disappear.

**Screenshots / Video:**
https://gfycat.com/GiddyUnacceptableKitfox

**Comment by Gymnasiast** [comment]
Also happens with other towers. (Observation and roto-drop.)
