### ISSUE TITLE
Ability to select an entire edge for raising/lowering land.

### ISSUE THREAD

**Issue by pizza2004** [OpenRCT2/OpenRCT2#6276]
I'd say the title explains what I'd like.  If it's not something people think should be in the game just say, but otherwise I'd like to implement it, I'm just having trouble finding where in the code one would go about doing this.

**Comment by Despotico** [comment]
My sugestion is to exclude this behavior from current selection mechanism, as swaping between corners, whole tile and edge will be a bit problematic.

Instead - Ctrl click could do the trick (when ctrl is pressed selection swaps to the edges only).

Already implemented the highlighting, will try to do the rest.

**Comment by Despotico** [comment]
This is what I have now (cost seems to be calculated correctly):
https://imgur.com/a/JWsgc
For some reason I cannot upload anything here :<

FYI: @pizza2004  @Gymnasiast

**Comment by Gymnasiast** [comment]
You can implement it if you like, @Despotico , I don't think that @pizza2004 will object to that.
But be warned that we can be quite stringent about the quality of code that goes into the game. This is to keep the code base maintainable and to reduce the likelihood of errors.

**Comment by pizza2004** [comment]
I don't mind at all.  When you say you can't upload, do you mean you're having trouble creating a pull request?

**Comment by Despotico** [comment]
I meant picture uploading by dragging or selection, always ends error for me (tho I am not sure if .pngs are allowed).

I am working on something else before I request pul. Also thinking about redoing part of my solution a bit.

**Comment by pizza2004** [comment]
Implemented in #6510.
