### ISSUE TITLE
Multi dimension coaster seats not rotating.

### ISSUE THREAD

**Issue by ciscodisco1** [OpenRCT2/OpenRCT2#6280]
**OS:** [Windows 10]
**Version:** [0.1.1]
**Commit/Build:** [**4601265**]

So I plan to build a multi dimension coaster in my park, but the seats on the ride don't rotate. I tried building the X model and looked in a fresh start of magic mountain, but the seats don't rotate at all on the prebuilt ride either. I tried building a flat version too so I could see the seats more and they don't seem to work at all.

Verision 0.1.1 build 4601265 by AppVeyor, on Windows 10 is the verision I'm using

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1.  Build the multi dimension coaster
2.  Make some wiggly bits with the change angle
3. Note that the seats don't rotate

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by Gymnasiast** [comment]
Appears to be the same problem as #6245.

**Comment by ciscodisco1** [comment]
Yes, exactly the same problem as #6245, didn't see that thread first.

**Comment by Gymnasiast** [comment]
Ok, closing this as a duplicate then.
