### ISSUE TITLE
Allow building queue paths in scenario editor

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#6292]
**OS:** Windows 10 Pro x64
**Version:** 0.1.2-develop
**Commit/Build:** 5c2870c

In the scenario editor, the queue button is missing from the path builder window.

**Comment by Gymnasiast** [comment]
Intentional.

**Comment by Broxzier** [comment]
I figured, but I fail to see a reason. Will this cause issues?

**Comment by Gymnasiast** [comment]
Well, you can't build rides on the scenario editor, so there's little point.

**Comment by IntelOrca** [comment]
This is just something vanilla did. We have not and had no reason to change it yet. With the ability to now change scenario options in-game and the sandbox mode - the scenario editor is almost redundant.

**Comment by Broxzier** [comment]
@Gymnasiast: While mostly true, just now I was building an entrance of the park and wanted to use queue lines inside a building, but couldn't do so in the scenario editor. In this case it's only an annoyance.

**Comment by Gymnasiast** [comment]
The reason the limit was put in was probably to keep the dialog cleaner. It is a little bit less confusing for the users.

However, I doubt it really matters that much. I could get rid of the limitation if @IntelOrca has no objections.

**Comment by IntelOrca** [comment]
I am fine with it being removed.

**Comment by Gymnasiast** [comment]
Implemented in 18db4a5.
