### ISSUE TITLE
Screenshot sound not played when the game is paused

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#6293]
**OS:** Windows 10 Pro x64
**Version:** 0.1.2-develop
**Commit/Build:** 5c2870c

When making a screenshot when the game is paused, the sound feedback is missing. I remember there also being a window that would show the filename in RCT2 which also seems to be missing, but can't test it right now.

- [ ] Reproducible in RCT2 (vanilla)? (can't get RCT2 to run for some reason)
- [ ] Multiplayer?

**Steps to reproduce:**
1. Pause Game
2. Press Ctrl+S to make a screenshot

**Comment by Gymnasiast** [comment]
Showing the filename was intentionally removed, to avoid subsequent screenshots having annoying notifications on them if you take many of them in a short time.

**Comment by PFCKrutonium** [comment]
@Gymnasiast Perhaps we could add it back, and simply remove it in the event another screenshot is taken?

**Comment by slonermike** [comment]
The sound issue is actually a far more general problem.  I hear no sounds at all while paused.

**Comment by aidan-waite** [comment]
I'm looking into this right now
