### ISSUE TITLE
When Deleting from Track Design Manager - Preview Freezes

### ISSUE THREAD

**Issue by rpstester** [OpenRCT2/OpenRCT2#6301]
**OS:** Windows 10 Pro 1703 x64
**Version:** v0.1.2
**Commit/Build:** develop build 4e3a38b provided by AppVeyor

When I go in to the Track Design Manager, and choose a ride type, then I can hover over the titles and see the ride preview on the right.  If then I click on one and choose to delete it, it asks "are you sure".  If I then delete it, the hovering and the preview on the right stop working, so I can no longer see the tracks that I want to review or modify.  But I can still click on the titles to rename or delete.

To work around this, I can close the track listing screen and go back to the ride selection screen, and when I click on the same ride type again, then the hovering and previewing is restored.  This behavior has not worked correctly in the last week (when I first noticed).

- [ ] Reproducible in RCT2 (vanilla)? No, the hovering and previewing continued to work correctly in the original RCT2.
- [ ] Multiplayer? Have not tried it.

**Steps to reproduce:**
1. Launch the Track Design Manager
2. Choose a type of ride
3. Choose a saved track and delete it
4. Try to hover around to look at the other saved tracks, but you won't be able.

If I can help elaborate the issue further, then just let me know. Thanks!

**Comment by rwjuk** [comment]
Fixed in https://github.com/OpenRCT2/OpenRCT2/pull/6636
