### ISSUE TITLE
Mechanic dedicated pathing not working...

### ISSUE THREAD

**Issue by SierraJet** [OpenRCT2/OpenRCT2#6306]
**OS:** [e.g. Windows 7]
**Version:** [e.g. 0.1.1]
**Commit/Build:** [e.g. 4601265]

Blue dedicated path for mechanics to patrol and respond to calls is not working. Rides are not selecting nearby mechanics that are assigned to an area. Since all mechanics are assigned to an area in my game (very large park) the rides keep trying to call a mechanic to no avail. This feature does function correctly in RCT2 base.

***My mistake. Located the problem. Thanks for the reply***

**Steps to reproduce:**
1. 
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by duncanspumpkin** [comment]
Full in the template and provide a save game

**Comment by SierraJet** [comment]
all good my mistake...thanks!
