### ISSUE TITLE
Fail to create title sequence if title sequences folder does not exist

### ISSUE THREAD

**Issue by TyPR124** [OpenRCT2/OpenRCT2#6308]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** Current Develop

If the "title sequences" folder does not exist, creating a new title sequence fails with console output:

Unable to open 'D:\...\Documents\OpenRCT2\title sequences\test.parkseq'

Despite the failure, the new title sequence is added to the in-game list, though it will fail to load if you try to select it.

I would expect the game to create the title sequences folder if needed, and also to not display the new title sequence if file creation still fails in some way.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Delete or rename your title sequences folder
2. Launch game, go into settings, and create a new title sequence

I may look into it myself, though I am new to the project so it might take a while to sort things out.

**Comment by TyPR124** [comment]
#6311 Submitted fix for this behavior. Welcome to feedback.

**Comment by rpstester** [comment]
I can confirm this behavior on build 40b026a.  I was getting a "failed to load - file contains invalid data" message when trying to create my own title sequence, but thanks to your post, @TyPR124 , I learned what I needed to do, and so now I have created my own title sequence.  

Please make the error message suggest how to solve the problem, or prompt the user to create a "Title Sequences" folder, or automatically create it.  Thanks!

**Comment by TyPR124** [comment]
Resubmitted fix, now #6332. This only fixes the issue of the directory not being auto-created. I think there are other improvements that can be made to Zip and title sequences, but this much smaller and simpler change fixes the main issue that most new users will run into.
