### ISSUE TITLE
When loading a RCT1 save that results in completing the scenario, does not prompt for name and does not check the scenario in the menu

### ISSUE THREAD

**Issue by rpstester** [OpenRCT2/OpenRCT2#6314]
**OS:** Windows 10
**Version:** 0.1.2 
**Commit/Build:** 40b026a (but has been happening for almost two weeks, when I first tried OpenRCT2)

Since I started playing RCT1 how many years ago, I would save my game on Oct. 31 or just before winning.  This way, if I installed the game on a new computer, I would just load my saves and win the scenarios, so I could unlock the parks without replaying all of them.  

I have pointed OpenRCT2 to my RCT1 installation, and I see all the scenarios (plus CF and LL), but only the top five are unlocked.  I tried to load my original saves from RCT1 into Open RCT2, but when I beat the scenario, it almost never prompts for my name, and even if it does, it does not "check" the scenario or unlock the next one. 

I know there have been related issues, such as #6252 and #6286, but even so, I still cannot unlock RCT1 scenarios in OpenRCT2 from my RCT1 saved games.  I'm assuming that this is supposed to work.  I have reviewed all original and CF saves from RCT1 so far, and a few will prompt me for my name, but none will unlock the next scenarios in the OpenRCT2.  I know they work for RCT1, as I have used them many times. 

P.S.  My saves from RCT2 will check the RCT2 scenarios in OpenRCT2.

Not reproducible in RCT1 or RCT2 original. N/A to multiplayer.

**Steps to reproduce:**
1.  Point OpenRCT2 to RCT1 installation folder
2. Load a nearly-completed-park saved game that was saved by RCT1 original.
3. Wait for winning of scenario
4. Completion window pops up, but no button for entering my name
5. **Does not check scenario or unlock a new one.**

Here is my Forest Frontiers save from 2010, saved on Oct. 31 and about to win.
[COM Forest Frontiers 2010.zip](https://github.com/OpenRCT2/OpenRCT2/files/1339100/COM.Forest.Frontiers.2010.zip)

Please let me know if you have more questions.  Thanks!

**Comment by rpstester** [comment]
It may be worth noting that I have already completed all of these scenarios in my RCT1 installation.

**Comment by rwjuk** [comment]
@rpstester Could you give #7029 a go  - should fix this.
