### ISSUE TITLE
When loading a save from RCT1, does not show all available rides to build

### ISSUE THREAD

**Issue by rpstester** [OpenRCT2/OpenRCT2#6315]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** 40b026a

When loading a saved game from RCT1 (plus CF/LL), it does not show in OpenRCT2 all the available rides that were available when loading the game in RCT1.  This has happened repeatedly on my saves from RCT1 that I've opened in OpenRCT2. 

**Steps to reproduce:**
1. Load my saved game below into OpenRCT2
2. Notice the Merry-Go-Round, Haunted House, and Ferris Wheel
3. Try to build a Merry-Go-Round, Haunted House, or Ferris Wheel

**Screenshots / Video:**

Here is what RCT1 shows on this park:
![cannot build rides -rct1](https://user-images.githubusercontent.com/32249806/30945409-21b54198-a3cc-11e7-9156-ea4b848faf05.png)

Here is what it shows in OpenRCT2:
![cannot build rides that have been built](https://user-images.githubusercontent.com/32249806/30945406-1b5dc310-a3cc-11e7-8568-d99ccd097b15.png)

**Save game:**

Here is the saved game if you'd like to examine further:
[Pleasure Island CONT 2013.zip](https://github.com/OpenRCT2/OpenRCT2/files/1339158/Pleasure.Island.CONT.2013.zip)

Please let me know if you have any further questions. Thanks!

**Comment by blackhand1001** [comment]
I got an even worse result. I opened up the save and had no objects able to be built.
