### ISSUE TITLE
Cannot sack staff that have not been placed

### ISSUE THREAD

**Issue by zyliwax** [OpenRCT2/OpenRCT2#6318]
**OS:** Linux
**Version:** 0.1.1 and above
**Commit/Build:** 4601265 and newer

Staff whose location is "(select location)" cannot be sacked by any available means.

- [ ] Reproducible in RCT2 (vanilla)? Cannot verify on my platform (even with Wine -- the game exits after a "CD-ROM drive not found" error), but does not occur in RCT1.

**Steps to reproduce:**
1. Optional: disable "Automatically place staff"
2. Pick up a staff member (and/or if following step 1, hire a new staff member) so that their location is "(select location)". Doesn't matter what type of staff.
3. Attempt to sack the staff member, either by using the "quick fire" method from the Staff window or the trash can from the staff member's own window.
4. Staff member will still be employed.

**Comment by rpstester** [comment]
Can reproduce on Windows 10, build 1de4b26.
Even though it asks you are you sure you want to fire the employee, and you confirm, employee is still there.
