### ISSUE TITLE
Default Cheat option

### ISSUE THREAD

**Issue by blackhand1001** [OpenRCT2/OpenRCT2#6321]
It would be useful if the cheats could be saved to the preferences store and would be enabled next time you start the game on a global basis.

**Comment by Gymnasiast** [comment]
Has been asked before. The project lead and some team members are against saving cheat status globally. When we move to our own object format, they will be saved in the save file itself.

**Comment by blackhand1001** [comment]
I know this was closed but one area where a default cheats config matters is when starting a new scenario rather than loading a new map. Also for headless servers.
