### ISSUE TITLE
Can't quit window for RCT1 path selecting

### ISSUE THREAD

**Issue by janzev** [OpenRCT2/OpenRCT2#6330]
**OS: Windows 10 Home 1607 64 Bit**
**Version: OpenRCT2, v0.1.1**
**Commit/Build: build 4601265 provided by AppVeyor**

When selecting RCT1 path in the settings you cannot quit the opened window. It doesn't matter if you select or don't select any path.

**Steps to reproduce:**
1. Open options of OpenRCT2.
2. Go to Miscellaneous.
3. Click on (empty) box for 'Path to RCT1 installation'.
4. The opened window with black background cannot be quitted. If you click on OK the window gets minimized. After maximizing the window again the window is still there.

**Comment by Gymnasiast** [comment]
This has been fixed. You're using an outdated build. Please upgrade to the newest `develop` version.

**Comment by IntelOrca** [comment]
@Gymnasiast this is the 1.1 release, it is not outdated.

**Comment by Gymnasiast** [comment]
@IntelOrca That release was on 9 August.

**Comment by IntelOrca** [comment]
It is the latest release. People should continue to use it unless they feel like switching to develop to have bugs fixed.
