### ISSUE TITLE
Saving game uses illegal memory

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#6334]
**Commit/Build:** 58b980d6b

Regression from https://github.com/OpenRCT2/OpenRCT2/pull/6257.

https://github.com/OpenRCT2/OpenRCT2/blob/58b980d6babac98b31c03fd3e9417b63c6e8a4b0/src/openrct2/game.c#L1223-L1233 leaks the scope of local variable `name`, which is used when handling intent.

Other calls to `intent_set_string` should be inspected too.

**Comment by Gymnasiast** [comment]
Solved by #6395.
