### ISSUE TITLE
Cannot rename random saved parks using Convert Save to Scenario

### ISSUE THREAD

**Issue by rpstester** [OpenRCT2/OpenRCT2#6337]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** 58b980d

I have used the Convert Save Game to Scenario for three different parks.  In vanilla RCT2, I can rename the park and scenario in all three cases.  In OpenRCT2, the change buttons were grayed out in two of the three, with no way I've found to enable those buttons.  

I have attached some of my saved games.  I think if it was the same base park, then any different file that park was saved as will act the same way.  Also, it seems like all the scenarios that shipped with RCT2 vanilla are unable to edit, but some of the original scenarios are working.  (I downloaded a third-party set of scenarios that were the original scenarios like Forest Frontiers upgraded to RCT2.)  Finally, a save from a scenario built from scratch works.  But I haven't had time to test exhaustively. 

This is the first time I've tried it, so I don't know how long it's been a problem. 

Not Reproducible in RCT2+WW (original)

**Steps to reproduce:**
1.  Start the Convert Saved Game to Scenario process
2.  Select a saved game.
3.  My hunch is that if it was a saved game from a RCT2 scenario, then it will not let you change the park or scenario name(s).  

**Save game:**

[Amity Airfield.zip](https://github.com/OpenRCT2/OpenRCT2/files/1346775/Amity.Airfield.zip) - doesn't work
[Bumbly Beach.zip](https://github.com/OpenRCT2/OpenRCT2/files/1346776/Bumbly.Beach.zip) - works
[Crazy Castle Again.zip](https://github.com/OpenRCT2/OpenRCT2/files/1346777/Crazy.Castle.Again.zip) - doesn't work
[Dino Wild Force Park.zip](https://github.com/OpenRCT2/OpenRCT2/files/1346781/Dino.Wild.Force.Park.zip) - works

As usual, just let me know if you'd like any more information. Thanks!

**Comment by Gymnasiast** [comment]
Original RCT2 scenarios have embedded scenario text objects. Vanilla probably took them out when converting.

I'm not sure if I should consider our behaviour incorrect. After all, including a scenario text object means the scenario name should be overridden. I'm therefore inclined to say 'non-bug'.

Hint: you can remove the scenario text object from the save using the Object Selection.

**Comment by Gymnasiast** [comment]
I am going to consider this not a bug. Please take out any scenario text objects if you don't want them to override your scenario name (since that's what they are for).
