### ISSUE TITLE
Unlock Vehicle Limits cheat does not allow setting of "zero" vehicles per train

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#6341]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.1.1]
**Commit/Build:** 11cdcea

I have created a CTR for a eurofighter train. This was accomplished by setting the minimum, maximum, and zero cars to 2. When I applied the cheat (to get more trains on the ride), I am unable to get Open to set the train to 2 cars long.

![image](https://user-images.githubusercontent.com/3454156/31052998-8dfc2646-a647-11e7-8964-93f75b1ee747.png)

**Comment by Gymnasiast** [comment]
Does this still occur? If so, we will need the object file in question.

**Comment by spacek531** [comment]
Yes, it still occurs on OpenRCT2, v0.4.2-210-g752eec1 (752eec1 on develop) provided by GitHub

[GREURO.zip](https://github.com/OpenRCT2/OpenRCT2/files/10189546/GREURO.zip)
