### ISSUE TITLE
Multiple objects on the same tile

### ISSUE THREAD

**Issue by swannet** [OpenRCT2/OpenRCT2#6343]
**OS:** macOS
**Version:** 10.12.6
**Commit/Build:** v0.1.2 [11cdcea](https://github.com/OpenRCT2/OpenRCT2/commit/11cdcea72bcff323c66d5c0e0df03901bec8941e) OpenRCT2 Build: 2820

Its possible to build multiple objects on the same tile (without having zero clearance turned on). So you can build a tree in the middle of the road without removing the road or affecting the normal behaviour of the road. This also applies for rides you can build your own (like coasters). "Normal" rides like the ferris wheel can not be build 'in' the road and will automatically build above the road (like vanilla RCT2).

When you build a saved track (for example a coater) you can build and operate the coaster like normal even if there are trees on the tiles where the coaster is.

Expected behaviour:
An error you can't build the object or ride / automatically remove objects that are in the way when placing a saved track. 

**NOTE**: Tested in also the stable v0.1.1-HEAD build 2681 (DEBUG) version of the game. This bug is **not** reproducible in the stable version of the OpenRCT2.

**NOTE 2**: The zero clearance is **not** checked in the cheats menu. Turning the option on and back off will result in the expected behaviour. Even when the game restarts. Also switching back to stable and forward to development this bug isn't reintroduced

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer? 

**Steps to reproduce:**
1. Build any object
2. Build any other object on the same title

**Screenshots / Video:**
<img width="424" alt="screen shot 2017-10-01 at 14 19 52" src="https://user-images.githubusercontent.com/550021/31054484-da5daaf2-a6b3-11e7-8b5d-12be30e56ad1.png">

**Save game:**
[Multiple Object Bug.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/1347114/Multiple.Object.Bug.sv6.zip)

**Comment by alecward92** [comment]
Have you tried using the tile inspector? You can raise and lower items on a tile and copy and paste other objects to any tile.

**Comment by swannet** [comment]
I don't know if there was something changed according to this but with a fresh install (removed the OpenRCT2 folder from Application Support), I can't reproduce the bug anymore.

**Comment by Gymnasiast** [comment]
No ideas what caused this. I'll just close this, if it plays up again you can reopen this issue.
