### ISSUE TITLE
Peeps unable to find park exit

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#6344]
See screen. 300 peeps in park, wanting to go home, all paths connected, otherwise functional park entrance, peep entry points in the right spot. All the peeps are doing is walking in weird patterns. Same for single player and multiplayer

![ne s mirage islands 2 2017-10-01 16-35-05](https://user-images.githubusercontent.com/19242088/31055749-c2a8cb3a-a6c7-11e7-91b1-1b7ca72acea6.png)

Park is hosted almost 24/7 as NewElement Multiplayer if you want to have a look.

Using v0.1.2 11cdcea on Windows 8

**Comment by Nubbie** [comment]
Please upload the save-file of the park

**Comment by alecward92** [comment]
After joining, saving the park, and running in single player, the park appears to work just fine. I sent in a tram of 250 guests, lowered the guest parameters, and watched them leave the through the exit with no issues. I don't know if the issue was solved before this message, but I'm seeing no issues on my end

**Comment by alecward92** [comment]
I'm running ffaa340 so it sounds like maybe an update did it?

**Comment by alecward92** [comment]
Running 11cdcea now and did the same thing. Still no issue. Maybe a multiplayer issue?

**Comment by alecward92** [comment]
[NE MP Map v2.zip](https://github.com/OpenRCT2/OpenRCT2/files/1347606/NE.MP.Map.v2.zip)

Here's a save file @Nubbie  I thought this was a little small in size but I did have export plugin data on so that should be alright right?

**Comment by Liampie** [comment]
Some do leave indeed, but eventually plenty of them will stay and in the end stuck peeps destroying the park rating is all you'll have. Try this save.

[peep jams.zip](https://github.com/OpenRCT2/OpenRCT2/files/1348212/peep.jams.zip)

**Comment by saxman1089** [comment]
This sounds like a similar issue to one I was having a few weeks back. Was the entrance moved using the sandbox mode and the old entrance deleted using the tile inspector? Check out this thread over at the forums if so. 

https://openrct2.org/forums/topic/2605-peeps-cant-find-park-exit-after-moving-it-in-sandbox-mode/?page=2

**Comment by zaxcav** [comment]
@Liampie I checked out the save file in peep jams.zip.
@saxman1089 is absolutely correct.
There are 2 entrance locations in the save file.
Entrance location 0 is at 25,2,16
Entrance location 1 is at 33,2,18
The peeps that are stuck are all heading towards entrance location 0.

**Comment by saxman1089** [comment]
@Liampie , I was able to fix this in my park. Let me know if you need help with it. DM me on NE or the OpenRCT2 forums and I'd be happy to help you out.

**Comment by Gymnasiast** [comment]
Fixed by https://github.com/OpenRCT2/OpenRCT2/pull/6539
