### ISSUE TITLE
remove please

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#6345]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.1.1]
**Commit/Build:** [e.g. 426e106]

- [x] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by Liampie** [comment]
I don't know how this happened, please delete

**Comment by Gymnasiast** [comment]
We can't delete issues. We can close it, but you can do so yourself as well.
