### ISSUE TITLE
map freeze/crash

### ISSUE THREAD

**Issue by 60trainhunter** [OpenRCT2/OpenRCT2#6346]
**OS:** [windows10]
**Version:** [1.2-3]
**Commit/Build:** [11cdcea]

this map keeps freezing/crashing i don't know why? in multiplayer it crashes both host and players!
[autosave_2017-10-01_11-46-17.zip](https://github.com/OpenRCT2/OpenRCT2/files/1347323/autosave_2017-10-01_11-46-17.zip)

- [ ] Reproducible in RCT2 (vanilla)?
- [yes] Multiplayer? and offline

**Steps to reproduce:**
1.  run this map and wait a few moments should freeze momentarily. 
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by 60trainhunter** [comment]
UPDATE try merging tracks  too!

**Comment by Nubbie** [comment]
It's recommended that you enable the option 'Export plug-in objects with saved games', as the save you provided does contain custom objects

Could you provide the save-file with that setting on / upload the file 'SANDMKY.dat'?

**Comment by 60trainhunter** [comment]
that setting was enabled

**Comment by Nubbie** [comment]
Missing the "SANDMKY.dat" file to open it, could you upload the file from the objects folder?

**Comment by 60trainhunter** [comment]
[SANDMKY.zip](https://github.com/OpenRCT2/OpenRCT2/files/1347462/SANDMKY.zip)

**Comment by 60trainhunter** [comment]
there you go

**Comment by Nubbie** [comment]
For @60trainhunter: Thanks, have now analyzed it, to temporarily fix your problem with the save freezing, use the cheat 'remove all peeps' :)

**Comment by Phyllostachys** [comment]
Is any body working on this? I'd like to explore it if not.

**Comment by IntelOrca** [comment]
@Phyllostachys not that I know of, feel free 👍

**Comment by Phyllostachys** [comment]
Hmm, apparently I'm missing the Wacky World expansion (but I do have the Time Twister expansion I guess).

**Comment by AaronVanGeffen** [comment]
Does this still happen? I tried testing myself, but in addition to SANDMKY, I'm missing quite a few objects:

* Ardy'sMu
* ARGO20
* ARGO21
* GAPATHX3
* HPPATH3
* MS-DOOR1
* MTCHOCRF
* MTTL1
* MTTSP1
* MTTSP2
* MTUMBRLL
* NESU15
* NESUD14
* XXRFMT01
* XXRFMT02
* XXRFMT03
* XXWLMB05
* XXWLMB09
* XXWLWD01
* XXWLWD09

**Comment by Broxzier** [comment]
The freeze happens at 7th Oktober, year 6 for me. It gets stuck in the same loop that https://github.com/OpenRCT2/OpenRCT2/issues/7229 got stuck in, namely `ride_queue_insert_guests_at_front`. OP may have used the "exploding guests" cheat that caused this.

Here's a save with the objects included: [autosave_2017-10-01_11-46-17.zip](https://github.com/OpenRCT2/OpenRCT2/files/2063754/autosave_2017-10-01_11-46-17.zip)

**Comment by 733737** [comment]
park does not freeze or crash even on october 9th, year 6

**Comment by tupaschoal** [comment]
Could not reproduce using save provided by @Broxzier and going through the date mentioned. Thanks for checking @733737 !
