### ISSUE TITLE
Invalid use of DISABLE_G2_BUILD in travis scripts

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#6349]
**OS:** Linux

`DISABLE_G2_BUILD` is not set properly on travis, but checked for when building `g2`. This causes issues when setting up new travis instances.

**Comment by Margen67** [comment]
Travis isn't used anymore.

**Comment by Broxzier** [comment]
Shouldn't we remove the Travis files then?

**Comment by duncanspumpkin** [comment]
As far as i know we have removed them
