### ISSUE TITLE
Unable to open language pack file in Flatpak build from installation path

### ISSUE THREAD

**Issue by ykgmfq** [OpenRCT2/OpenRCT2#6357]
**OS:** [Fedora 26, Flatpak]
**Version:** [v0.1.2-develop]
**Commit/Build:** [cbe5b1d]

When running my [Flatpak build](https://github.com/ykgmfq/org.openrct2.OpenRCT2) the game immediately stops after this error:

`[dmp@notebook ~]$ flatpak run org.openrct2.OpenRCT2
ERROR[/run/build/openrct2/src/openrct2/localisation/LanguagePack.cpp:103 (FromFile)]: Unable to open /language/en-GB.txt: Unable to open '/language/en-GB.txt'
ERROR[/run/build/openrct2/src/openrct2/localisation/LanguagePack.cpp:103 (FromFile)]: Unable to open /language/de-DE.txt: Unable to open '/language/de-DE.txt'
ERROR[/run/build/openrct2/src/openrct2/Context.cpp:321 (Initialise)]: Failed to open configured language...
ERROR[/run/build/openrct2/src/openrct2/localisation/LanguagePack.cpp:103 (FromFile)]: Unable to open /language/en-GB.txt: Unable to open '/language/en-GB.txt'
FATAL[/run/build/openrct2/src/openrct2/Context.cpp:324 (Initialise)]: Failed to open fallback language...`

If the data path to the **build directory** is given the game works:

`[dmp@notebook ~]$ flatpak run org.openrct2.OpenRCT2 --openrct-datapath=/home/dmp/fp_build/files/share/openrct2/`
 
However, when it receives the actual **installation path** the output is:

`[dmp@notebook ~]$ flatpak run org.openrct2.OpenRCT2 --openrct-data-path=/home/dmp/.local/share/flatpak/app/org.openrct2.OpenRCT2/current/active/files/share/openrct2/
ERROR[/run/build/openrct2/src/openrct2/platform/posix.c:743 (platform_resolve_openrct_data_path)]: Could not resolve path "/home/dmp/.local/share/flatpak/app/org.openrct2.OpenRCT2/current/active/files/share/openrct2/", errno = 2`

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Comment by Gymnasiast** [comment]
Now we gained official Flatpak support, I'm quite sure this issue is solved. Please let us know if it isn't.
