### ISSUE TITLE
Game crashes when I try to build a Go Karts

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#6378]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** f2195b4

The game crashes when I click on the Go Karts in the ride selection screen. I've tried this in multiple save files so it's not an issue caused in a specific park.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer? It doesn't crash in multiplayer, but I do get an "invalid ride type" error, which I don't get with other rides.

**Steps to reproduce:**
1. Try to build a go karts

**Comment by duncanspumpkin** [comment]
Duplicate of #6376
Can you check with the very latest build.

**Comment by duncanspumpkin** [comment]
I'm pretty sure it is the same bug I've just tried it with the latest build and its not crashing.

**Comment by LordMarcel** [comment]
just checked, it works now, thanks
