### ISSUE TITLE
Scenery tab editor

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#6382]
It would be very helpful for (at the least) NE's community to be able to configure new scenery tabs. One anecdote I heard was that some of Louis!'s benches, the objects in the tabs are outdated and are very glitchy; people who swap out the objects for newer versiond end up having massive miscellaneous tabs. It would be helpful if there was a scenery tab editor in OpenRCT2.

**Comment by FischNE** [comment]
I definitely support this! It would be an insanely good addition if you could swap objects in and out from the tabs. Otherwise if you change your object selection you'll eventually end up with a lot of objects in the miscellaneous tab.

**Comment by Gymnasiast** [comment]
Defining tabs will be easy to do in the new object format. Creating objects in general is something I think would be better handled outside OpenRCT2 proper in general.

Also, I remember Henry Winkelstein creating a tool to create scenery tabs. Not sure if you are aware of its existence?

**Comment by spacek531** [comment]
I posted this as a feature request because the object viewer is massively useful for selecting objects - more useful than remembering all the object names, or whatever you're meant to do with this:

![image](https://user-images.githubusercontent.com/3454156/31273325-f84d08ea-aa42-11e7-93c1-3131e7ae2861.png)

There's no instructions and only 2 of the pages seem to work.

**Comment by IntelOrca** [comment]
Try this:
https://trigger-death.github.io/RCT2Tools/GroupCreator/

**Comment by Gymnasiast** [comment]
@spacek531 There used to be instructions. You're meant to drag-and-drop the objects into it.

**Comment by Nubbie** [comment]
Do highly suggest @trigger-death "Group Creator" Intelorca suggested. Impressive how well it works in a basic way

Being able to create custom object-tabs are a mixed bag for me, it feels like a feature for more advanced users than the basic player, and as a more advanced user you might expand to 3rd-party softwares if they are as good as the "Group Creator"
You could say the same for the titlesequence-editor, but it had no good 3rd-party software afaik

**Comment by spacek531** [comment]
@Nubbie Can you explain why you think the title sequences should be edited in a separate program? There are no softwares I can think of that have a scripted camera editor where the editor is a 3rd party software.

RCT3 has its flying camera editor... ingame
Team Fortress 2 has its replay editor... ingame
Every Trackmania game (there are like, 8 of them, stretching back to 2003) has its camera editor... ingame

**Comment by Gymnasiast** [comment]
Can we just stay on-topic, please?

**Comment by Gymnasiast** [comment]
I'm going to close this issue. With the json-based new object format coming up, there is little reason to implement support for created .DAT scenery group, even if we wanted to.
