### ISSUE TITLE
Loading saved RCT1 games disables admission prices for rides

### ISSUE THREAD

**Issue by ccoors** [OpenRCT2/OpenRCT2#6387]
**OS:** Arch Linux
**Version:** 0.1.2
**Commit/Build:** 0217734c4ef4b83e2e68f8c239c03bf37e43637d

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Start a new game with a RCT1 scenario
2. Make sure the park has an admission price and build a ride that also has an admission price
3. Save the game
4. Load the game
5. The ride admission prices are disabled

**Comment by ccoors** [comment]
Oh, this appears to require a new save format (#1000). Then maybe a warning should be displayed on saving.. ?

**Comment by Gymnasiast** [comment]
I'm not sure that would really help all that much.
