### ISSUE TITLE
Trying to open an invalid ride moves other client's viewport

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#6389]
**Commit/Build:** 25b72260d

Regression from #5053

- [x] Multiplayer

**Steps to reproduce:**
1. Start a server with some map
2. Connect a client to the server, make sure their viewports are showing different parts of the map
3. As a server, create a ride, but do not build a complete circuit, don't place any entrance nor exit
4. Exit the construction mode and try opening the ride

**Expected result:**
Client's viewport is unaffected

**Actual result:**
Client's viewport moves to the location of the ride

Note: https://github.com/OpenRCT2/OpenRCT2/pull/6381 fixes some issues, I haven't tested if that's one of the fixed ones.

**Comment by duncanspumpkin** [comment]
Yes #6381 would fix this. The error is that the server is running an invalid game command.

**Comment by duncanspumpkin** [comment]
Closed by #6381
