### ISSUE TITLE
After completing objective, saved name does not appear in scenario list

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/OpenRCT2#639]
I completed the objective for the 'Over The Edge' park ('Africa - Victoria Falls' in the scenario list) and entered my name. However, when I returned to the scenario list, the completion tick and name do not appear.

Maybe this has something to do with the scenario's name not matching the park's, or perhaps even because I continued playing the park from a saved game? This one may need further investigation, but I thought I might as well throw it out here for now...

**Comment by Gymnasiast** [comment]
I didn't even get the option to enter my name when I completed a non-default scenario (Evergreen Gardens) with a higher company value than I had previously. I can supply both the SC6 and SV6 (on 31 october, year 4), if needed.

**Comment by IntelOrca** [comment]
See #844 and #1962.
