### ISSUE TITLE
"invalid ride type" error when building ride with no default color schemes set

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#6394]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.1.1]
**Commit/Build:** b56ad77

When placing a ride without any default color schemes set, RCT2 shows an error message of "invalid ride type", and the error background appears to be slightly malformed:

![image](https://user-images.githubusercontent.com/3454156/31305133-23f65b64-aae7-11e7-8dc1-bb4c57241289.png)

This bug I believe cropped up sometime in the last 72 hours.

this .DAT file has no default color schemes set:
[TSTGAUG2.txt](https://github.com/OpenRCT2/OpenRCT2/files/1364328/TSTGAUG2.txt)

**Comment by spacek531** [comment]
Just did a manual bisection via portable version downloads. The bug was introduced in 1089bd2d56ccd01c7d3a1adc57b4a1488b0fb571

**Comment by PFCKrutonium** [comment]
1089bd2 is a commit that bumps the Multiplayer Network Version... So it's going to probably be a commit immediately before or after.

**Comment by Gymnasiast** [comment]
It's going to be https://github.com/OpenRCT2/OpenRCT2/pull/5053.
