### ISSUE TITLE
Load/Save window theme is not applied

### ISSUE THREAD

**Issue by ccoors** [OpenRCT2/OpenRCT2#6407]
**OS:** Arch Linux
**Version:** 0.1.2
**Commit/Build:** 2d993671599ffd133b56694f68de1837ff605cbb

Editing the colors of the load/save window in a custom theme only affects the load/save window if it is currently open. After closing and opening it again, it stays blue.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Create a custom theme
2. Open a load/save window
3. Change the load/save window colors
4. Close the load/save window and reopen it

**Screenshots / Video:**
![2017-10-07-231000_5120x1080_scrot](https://user-images.githubusercontent.com/8963459/31311807-babfc0bc-abb4-11e7-97bd-3b635c3f9f1d.png)

(Also, notice the missing scrollbar in the theme window, but I can't reproduce that yet)

**Comment by AaronVanGeffen** [comment]
Looks like its widget colours are all set to COLOUR_LIGHT_BLUE in `window_loadsave_open`. I'm guessing those should be loaded from a theme, instead.
