### ISSUE TITLE
can't create voids or "caves" in land masses

### ISSUE THREAD

**Issue by jamtraks** [OpenRCT2/OpenRCT2#6410]
**vista 32-bit** [e.g. Windows 10]
**v0.1.2** [e.g. 0.1.1]
**34685b "0" or "o"** [e.g. 426e106]

This is a suggestion and question. Is there a way to create voids inside land masses while still leaving layers of land especially the top layers so that i can create caves to build inside of? i do think there is currently, so i am making this a suggestion; that the tile inspector or something else is altered in a way to make this a possibility.
I may be unable to respond to any answers because of lack of internet access, and i may be offline for weeks, but thanks anyway.

- [na ] Reproducible in RCT2 (vanilla)?
- [na] Multiplayer?

**Steps to reproduce:**
1. na
2. na

**Dump file**

**Screenshots / Video:**

![creating voids in land](https://user-images.githubusercontent.com/17103908/31313068-08d2e258-aba5-11e7-99a8-8948c4085546.jpg)

**Save game:**

**Comment by Gymnasiast** [comment]
No, this is not possible, and most certainly not as easy as you think it is.
There is scenery that can emulate this, though.
