### ISSUE TITLE
Maze preview only shows scenery

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#6413]
**OS:** Windows 7
**Version:** 0.1.1
**Commit/Build:** e737b31

**Screenshots / Video:**
![2017-10-08 08-08-36](https://user-images.githubusercontent.com/28242696/31316677-3eb34f56-ac00-11e7-858b-979cf50d10d2.png)

**Comment by Gymnasiast** [comment]
All of them? Or just one?

**Comment by SidaRadis** [comment]
All of them

**Comment by AaronVanGeffen** [comment]
This wouldn't happen to be on OpenGL, right?

**Comment by SidaRadis** [comment]
No, I use software (hardware display)

**Comment by duncanspumpkin** [comment]
Likely caused by the actions pr.

**Comment by SidaRadis** [comment]
I tested the last stable version and this bug still occurs. This issue has been in the game for weeks if not months.

**Comment by duncanspumpkin** [comment]
Caused by https://github.com/OpenRCT2/OpenRCT2/pull/6051

Fix incoming
