### ISSUE TITLE
Can't set Corkscrew Coaster Launch speed high enough

### ISSUE THREAD

**Issue by ccoors** [OpenRCT2/OpenRCT2#6414]
**OS:** Arch Linux
**Version:** 0.1.2
**Commit/Build:** e737b3108c2bf16e0f1bde5313764a8715aa4a25

The Steam version of RCT1 contains a lot of tracks called `u(nnnn).td4`. `u(3809).td4` for example is a track for the Corkscrew Coaster. It has a launch speed of 75 km/h. If I build it in OpenRCT2, the launch speed is initially at the 75 km/h, but changing the speed limits it to 43 km/h. But if I don't change it and save and then reload the game, it's still at 75 km/h, so it's not a save file limitation. Also, I can import a save file from RCT1 with the correct speed.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Build a Corkscrew Coaster with the Track `u3809`
2. Click on the gears and try to change the launch speed

**Screenshots / Video:**
RCT2:
![2017-10-08-143622_5120x1080_scrot](https://user-images.githubusercontent.com/8963459/31316942-046bbddc-ac38-11e7-885c-8dfa6db9a472.png)

RCT1:
![2017-10-08-143655_5120x1080_scrot](https://user-images.githubusercontent.com/8963459/31316943-046e0c54-ac38-11e7-9e90-f2ec3f5a8e65.png)

**Comment by Gymnasiast** [comment]
How far can you set the speed in RCT1?

**Comment by SidaRadis** [comment]
60 mph or 96 km/h is the limit in RCT1. Maybe selecting rides by track type could allow for the same speeds as RCT1?

**Comment by Gymnasiast** [comment]
No, I've just raised the limit to 96 km/h again, no exceptions.
