### ISSUE TITLE
Guests get stuck in paths

### ISSUE THREAD

**Issue by ghost** [OpenRCT2/OpenRCT2#6416]
**OS: Windows 10 Creators Update**
**Version:0.1.1 Stable**
**Commit/Build: 4601265**

I was hosting my RCT2 co-op server and my friend was building a food court of course the guests get stuck there and wouldn't get out. Will there be a hotfix for the stable build to fix this issue?

**Comment by BPCD1999** [comment]
I just found out it's every time guests gets near to shops/stalls.

**Comment by ts6815** [comment]
Take a close look at the way your pathing is arranged. It's hard to explain simply but have a read here -- http://rct.wikia.com/wiki/Paths -- it may be that the placement of your food court "traps" guests as an outgrowth of the algorithm for pathfinding which has some systemic flaws.

I'm not a contributor to the project but I believe there are people working on the problem, however it is a rather complex issue.

**Comment by Gymnasiast** [comment]
AI is indeed complex. And I'm afraid to say you provided way too little information to even have the slightest hope of fixing it. At the very least, you need to upload a save file, and a screenshot showing the incorrect behaviour.

**Comment by Nubbie** [comment]
@BPCD1999 
Does this still occur? 
Can you upload a save-file where this issue happens?
