### ISSUE TITLE
Crash when selecting attraction

### ISSUE THREAD

**Issue by JonatanRaven** [OpenRCT2/OpenRCT2#6418]
Windows 10
v0.1.2
1089bd2

When I select an attraction to build the game crashes to desktop.
It happened in my last game when I tried to build certain rollercoastes but I just avoided building that particular coaster.

In my recent game it crashes when I'm trying to build Go Karts.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1.  Start a game
2.  Try to build Go Karts

**Dump file**

**Screenshots / Video:**

![2017-10-09_02-53-56](https://user-images.githubusercontent.com/32624849/31322835-ba56ff92-ac9e-11e7-9c4f-27cdf090f6d6.png)

![2017-10-09_02-57-06](https://user-images.githubusercontent.com/32624849/31322826-9dc312b2-ac9e-11e7-84e9-70f9b1f9ee73.png)

**Save game:**
[Dusty Greens.txt](https://github.com/OpenRCT2/OpenRCT2/files/1367342/Dusty.Greens.txt)

**Comment by duncanspumpkin** [comment]
Use the most recent build.
