### ISSUE TITLE
Investigate using ccache on Travis

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#6419]
**Commit/Build:**  c724074 

Travis already has some support for ccache: https://docs.travis-ci.com/user/caching/#ccache-cache and it appears it could speed things up for us too. Especially as we move towards C++ and there are lots of code that is not modified between the jobs, like ride painting code.

The issue here is we use docker for build jobs and it will require some work to extract the cached data properly and then installing it again.

It also depends on https://github.com/OpenRCT2/OpenRCT2/pull/6409 to get rid of setting the git commit hash in compiler invocation for every file.

This should be investigated for Linux and macOS jobs.

**Comment by vector-of-bool** [comment]
At my workplace, we use ccache + Docker to great effect. Full rebuilds are a matter of seconds.
