### ISSUE TITLE
Junior Roller Coaster can be built too high with default settings

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#6425]
**OS:** Windows 7
**Version:** 0.1.2
**Commit/Build:** b05bdf2

The Junior Roller Coaster can be built to a height of 14 units with the "select rides by track type" unchecked while in vanilla the maximum was 11 units. Enabling the select rides by track type option makes the Junior R.C. build at the correct height. This issue is present in the latest stable version (0.1.1).

**Comment by Gymnasiast** [comment]
This was deliberately changed for RCT1 parity. Though that was before the ride groups were introduced.

**Comment by SidaRadis** [comment]
Thank you for the explanation.
I have another quick question on ride groups if you don't mind. I noticed The Steel Twister Roller Coaster can have vertical slopes when the "Select rides by track type option" is on but I'm pretty sure this was in impossible RCT1. On the other hand, the Hyper-Twister cannot have vertical slopes with the same settings. Is this intended behavior?

**Comment by Gymnasiast** [comment]
> The Steel Twister Roller Coaster can have vertical slopes when the "Select rides by track type option" is on but I'm pretty sure this was in impossible RCT1

I don't know about RCT1, but it most certainly was possible in RCT2. Whether RCT1 supported a track element is not relevant for ride groups.

> On the other hand, the Hyper-Twister cannot have vertical slopes with the same settings. Is this intended behavior?

Yes. Hyper-Twisters are non-inverting Twister Roller Coasters with a higher maximum height. They get their excitement from their height differences and speed.


The idea behind ride groups is mostly to allow switching to other vehicle types in a way that RCT1 allowed. Grouping is done based on capabilities and function. For example, the regular Twister, Stand-up Twister and Floorless trains are all used on the same kinds of roller coasters (with loops and all) and are thus grouped together.

**Comment by Gymnasiast** [comment]
On second thought, the non-ride group behaviour should probably be inverted. I raised it before ride groups were introduced.

**Comment by Gymnasiast** [comment]
With ride groups now enforcing the correct limit, this issue is solved.
