### ISSUE TITLE
Renaming rides in Online play frequently crashes the client. 

### ISSUE THREAD

**Issue by blackhand1001** [OpenRCT2/OpenRCT2#6426]
**OS:** [e.g. Windows 10]
**Version:** 0.1.2-develop build 8603141

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
Start a game and build some rides, then try renaming them. Certain rides will crash if you try to rename them. I can't narrow down what causes it but its not exactly rare. Rejoining and attempting to rename it again will crash as well. 

**Dump file**
I'll get a crash dump when I am home later and upload it.

**Comment by janisozaur** [comment]
426e106 is a really old version, update to current builds.

**Comment by blackhand1001** [comment]
Whoops sorry, i didn't use that build. The build I used was from this weekend.

**Comment by Gymnasiast** [comment]
@ZehMatt

**Comment by ZehMatt** [comment]
Is this perhaps a duplicate? #6390

**Comment by Gymnasiast** [comment]
Likely. But perhaps @blackhand1001 can provide us with a dump?

**Comment by YoloSweggLord** [comment]
It only seems to affect certain rides. If anyone from New Element is reading this before I get a chance Monday, could you upload the current multiplayer park? Renaming the dive coaster works fine, but renaming the invert crashes my client.

**Comment by Gymnasiast** [comment]
Fixed in https://github.com/OpenRCT2/OpenRCT2/commit/ce73d3a8a570bf6200e25fa6e4d92c2993c45862.
