### ISSUE TITLE
Favourite ride of guests in RCT1/AA scenarios defaults to ride at index 0

### ISSUE THREAD

**Issue by trigger-death** [OpenRCT2/OpenRCT2#6445]
When loading an RCT1/CF scenario, guests already existing in the park will have their favorite ride defaulted to the ride at index 0. This does not happen with any other scenarios, including those from LL.

**OS:** Windows 7
**Version:** 0.1.2
**Commit/Build:** 42d6a10952ff02308a9047771fe9722f4d7b0758

- [ ] Reproducible in RCT1? *Guests have correct N/A in RCT1*
- [ ] Multiplayer? *(Untested)*

***

![Preview](https://i.imgur.com/tbFEZQT.png)
*Sophie and Lasse loaded with Funtopia scenario have a favorite ride they've never been on*

![Preview](https://i.imgur.com/MFqdKBr.png)
*Helen F. in Rotting Heights likes a ride that has never been finished*

I'll try looking into this as my first goal after coming back to OpenRCT2.

**Comment by Gymnasiast** [comment]
I believe you're right. I don't remember this being a feature in RCT1-0, but I do remember it from LL. I could even spin up an AA install, but I find your examples convincing enough.
