### ISSUE TITLE
Player not seeing items on my server

### ISSUE THREAD

**Issue by Remixful** [OpenRCT2/OpenRCT2#6449]
**OS:** Windows 10
**Version:** 0.1.1
**Commit/Build:** Don't know, I guess this https://github.com/OpenRCT2/OpenRCT2/commit/46012651c531e9d5b5202b9521ced8126e30ce8f

Friend can't see one of the fence objects in the scenery build menu.

- [ ] Reproducible in RCT2 (vanilla)? 
- [x] Multiplayer?

**Steps to reproduce:**
1. Host server
2. Ask client to look at the scenery build menu, they won't have the fence

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/8620268/31491355-0c2dc6de-af15-11e7-86ba-b5c0bc819d29.png)
Me (above)
![image](https://user-images.githubusercontent.com/8620268/31491389-1ae6c716-af15-11e7-86a3-164aa98fb6dd.png)
Friend (above)

**Comment by Gymnasiast** [comment]
Both screenshots have 23 fences, and the same at that. The only difference is that you have your colour set to black while your friend picked bordeaux red.

**Comment by Remixful** [comment]
Haha, we were up all last night and both of us were so tired that we didn't even notice.
