### ISSUE TITLE
spawn point multiplayer server crash as host

### ISSUE THREAD

**Issue by 60trainhunter** [OpenRCT2/OpenRCT2#6469]
**OS:** [Windows 10]
**Version:** [0.1.2-15]
**Commit/Build:** [ce73d3a]

load any map in multiplayer then add new entrance any where no owned land on path, then try adding a new peep spawn point as Server HOST. should crash

- [ ] Reproducible in RCT2 (vanilla)?
- [yes] Multiplayer?

**Steps to reproduce:**
1. place new spawn point as SERVER HOST
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by janisozaur** [comment]
I think there's already an issue for that

**Comment by Nubbie** [comment]
somewhat related: https://github.com/OpenRCT2/OpenRCT2/issues/5901

Do you have a dumpfile from the crash?
