### ISSUE TITLE
Predefined title sequence filename issues

### ISSUE THREAD

**Issue by trigger-death** [OpenRCT2/OpenRCT2#6470]
The underlying filenames of predefined title sequences cause a few issues when it comes to custom title sequences. Firstly, duplicating a predefined title sequence will open the rename textbox window with its filename instead of it's proper name. Second, naming a title sequence after the filename of a predefined title sequence will cause it to be treated as a predefined title sequence.

**OS:** Windows 7
**Version:** 0.1.2
**Commit/Build:** ce73d3a *and earlier*

- ~~Reproducible in RCT2 (vanilla)?~~
- ~~Multiplayer?~~

**Steps to reproduce (#1):**
1. Open the title sequence editor.
2. Select a predefined title sequence.
3. Press Duplicate.
4. The name will use the predefined filename.

**Steps to reproduce (#2):**
1. Open the title sequence editor.
2. Press Create or Duplicate
3. Name the title sequence `rct1`, `rct1aa`, `rct1aall`, or `rct2`. <sup>*(openrct2 isn't effected because it's name is identical to it's proper name)*</sup>
4. Named park takes proper name and next index of predefined sequence and cannot be edited.

**Comment by Nubbie** [comment]
Isnt this fixed with ur PR? :P
