### ISSUE TITLE
Virustotal flag as trojan the windows zip file

### ISSUE THREAD

**Issue by garaboncias** [OpenRCT2/OpenRCT2#6474]
**OS:** windows
**Version:** 0.1.1
**Commit/Build:** [e.g. 426e106]

I download the game files from https://openrct2.website/ and virus scanner flag as trojan
https://www.virustotal.com/
see:
https://www.virustotal.com/hu/file/cb8d46eb3f5e3e5f2d71afee0275c1f865c53c507d91d0dc1b176909df1f3bbe/analysis/

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. download the windows game files from https://openrct2.website/
2. test it with https://www.virustotal.com/

**Dump file**

**Screenshots / Video:**
https://www.virustotal.com/hu/file/cb8d46eb3f5e3e5f2d71afee0275c1f865c53c507d91d0dc1b176909df1f3bbe/analysis/

**Save game:**

**Comment by IntelOrca** [comment]
We are unable to do anything about this. Each build is hit and miss with some virus scanners.
