### ISSUE TITLE
Rides can be demolished in pause mode without the "allow building in pause mode" cheat

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#6478]
**OS:** Windows 7
**Version:** 0.1.2
**Commit/Build:** fd459f0

Rides can be demolished in pause mode without using any cheats. The amount of money refunded when demolishing in pause mode is also displayed when it shouldn't be.

**Comment by duncanspumpkin** [comment]
Likely related to the game action pr

**Comment by SidaRadis** [comment]
I can still reproduce this issue with build a3c64bb. Rides can still be demolished in pause (refund price appearing when it shouldn't is fixed though).

**Comment by AaronVanGeffen** [comment]
That is expected, as a3c64bb does not contain the fix yet. The fix was pushed with b96657c0cd6d6cd5f9c18a5114ebe6456200db68, which has a3c64bb as its parent.
