### ISSUE TITLE
Openrct2 crashes when I try to do a new game on a custom scenario

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#6483]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** ffdc854

Doing new game on a scenario that came with the game works fine, but custom scenarios make the game crash immediately. Loading saved games that are on custom scenarios works fine though.

- [ ] Reproducible in RCT2 (vanilla)
- [x] Multiplayer

**Comment by Gymnasiast** [comment]
I just fixed a bug regarding scenario text entries. Please wait for the new build to become available and try again.

**Comment by Gymnasiast** [comment]
I'm going to consider this solved, but feel free to reopen if the issue persists.
