### ISSUE TITLE
Cannot save converted scenario

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/OpenRCT2#6486]
**OS:** Arch Linux
**Version:** 0.1.2
**Commit/Build:** 08f7aba8174a96e3732e728725a52e747b973c60

When converting a saved game to a scenario, the following assertion error is triggered as soon as the player clicks the "Next step: save game" button.

```
Actual type doesn't match requested type
openrct2: ../src/openrct2/core/Guard.cpp:107: void Guard::Assert_VA(bool, const char*, __va_list_tag*): Assertion `false' failed.
Aborted (core dumped)
```

**Comment by marijnvdwerf** [comment]
Introduced by 72b3896

**Comment by Nubbie** [comment]
Related issue https://openrct2.org/forums/topic/2686-editor/
