### ISSUE TITLE
Boat hire boats do not return to station

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#6497]
**OS:** [e.g. Windows 8]
**Version:** [e.g. 0.1.2]
**Commit/Build:** [e.g. 6a66ef8]

Boats on any boat hire attraction without tracks do not return to the station. Rather, they just move in one general direction. Problem appeared first in 6a66ef8.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Build boat hire without tracks
2. Open it
3. Watch them not return to station

**Dump file**

**Screenshots / Video:**

![the great circle 2017-10-16 21-32-05](https://user-images.githubusercontent.com/6469413/31631760-fd1fec7c-b2ba-11e7-8b1b-37e3f54529bd.png)

**Save game:**

**Comment by Nubbie** [comment]
Duplicate #866

**Comment by deurklink** [comment]
For clarity, this worked fine before latest build 6a66ef8

**Comment by duncanspumpkin** [comment]
https://github.com/OpenRCT2/OpenRCT2/commit/f27a7a5918216937829908be7e4128eb5cabaf23#commitcomment-25016291
Think this is the issue. Cast to uint8 instead of sint16.
