### ISSUE TITLE
Some strings are broken

### ISSUE THREAD

**Issue by ccoors** [OpenRCT2/OpenRCT2#6514]
**OS:** Arch Linux x86_64
**Version:** 0.1.2
**Commit/Build:** ec22d04089e5516658427ae58c2a7f956c01f98e

Some strings appear to be broken. Happens in every language.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Screenshots / Video:**
![2017-10-18-132240_5120x1080_scrot](https://user-images.githubusercontent.com/8963459/31717449-35f6eb8e-b40c-11e7-8610-e08c340c2fdc.png)
![2017-10-18-135444_5120x1080_scrot](https://user-images.githubusercontent.com/8963459/31717450-360fe76a-b40c-11e7-854d-aa7323cac684.png)

**Comment by AaronVanGeffen** [comment]
I can reproduce these with other languages on macOS. Wonder what's causing the regression.
