### ISSUE TITLE
No rain and thunder animation on OpenGL renderer

### ISSUE THREAD

**Issue by carlu93** [OpenRCT2/OpenRCT2#6515]
**OS:** Windows 10 1607
**Version:** 0.1.2
**Commit/Build:** ec22d04

When using the OpenGL renderer rain and thunder is not animated. The option for rendering weather is on! I haven't found a bug report for this and the wiki page didn't state the problem. Maybe this is something new related to some of the recent changes that got introduced. 

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Start the game with the OpenGL renderer
2. Open a park
3. Force rain or wait until it rains
4. No animation rendered

**Screenshots / Video:**
![screen](https://user-images.githubusercontent.com/16781908/31718822-8b4e4118-b411-11e7-83f8-db135056c9f5.jpg)

**Comment by runfalk** [comment]
I can confirm this is the case on Linux as well. I have no idea if it's related but spending animations (the floaty red and green numbers) doesn't work properly either. They almost never show, and when they do I don't know why.
