### ISSUE TITLE
Peeps can't exit this park

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#6520]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.1.2]
**Commit/Build:** 814b28c

Peeps are not going through the entrance and leaving the park even when they reach the tile next to the entrance.

**Steps to reproduce:**
1. load this .SV6 file: [dang peeps can't even find the entrance.txt](https://github.com/OpenRCT2/OpenRCT2/files/1397132/dang.peeps.can.t.even.find.the.entrance.txt)
2. Observe peeps with the "leaving the park" status. Many are ways away from the entrance. If you follow the peep in a separate view you will see them reach the tile adjacent to the park entrance... then make a U-turn and wander inside the park some more.

**Comment by rwjuk** [comment]
Where did this park come from? Was anything done to the entrance in terms of hacking it (e.g. raising/lowering it with trainers/the tile inspector)?

**Comment by zaxcav** [comment]
@spacek531 @rwjuk Looks like the tile inspector was used.
The park entrance data contains the following entrances:
Entrance 0 at 76,80,14
Entrance 1 at 76,80,2
Entrance 2 at 75,81,14

Entrance 0 is the only one still there.
The peeps that can't get out are trying to leave via Entrance 2.

**Comment by spacek531** [comment]
in a more recent version, Entrance 2 is completely gone (as far as I know) from tile inspector use; I cannot place more than 2 other entrances. Is there a way to fix this?

**Comment by duncanspumpkin** [comment]
You could adjust the save to fix the entrance data.

**Comment by spacek531** [comment]
Sure, let me just whip out my save file adjuster utility...

**Comment by duncanspumpkin** [comment]
If you have visual studio installed just load the park with the debugger on. Place a breakpoint and then adjust the the gparkentrance structure to remove the invalid entries.

**Comment by rwjuk** [comment]
File attached with exactly this done to it. If anyone else comes across this, you need to set the 'x' property of the unwanted entrance entries to `-32768` (which tells the game 'ignore this one' basically).

[dang.peeps.can.t.even.find.the.entrance.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/1404513/dang.peeps.can.t.even.find.the.entrance.sv6.zip)

**Comment by Gymnasiast** [comment]
Fixed by https://github.com/OpenRCT2/OpenRCT2/pull/6539.

**Comment by spacek531** [comment]
Fixing on import is a nifty way of doing this. Thanks!
