### ISSUE TITLE
Make all land tools behave the same

### ISSUE THREAD

**Issue by ccoors** [OpenRCT2/OpenRCT2#6530]
All tools that act on land regions behave slightly different.

1. Clear Scenery/Random tree cluster: When a region inside and outside of the park is selected, it works as specified on the region inside the park and the outside region is ignored.
2. Land/Water tool: When using the mountain option regions outside of the park area are not affected. When not using the mountain tool, you can raise or lower the land until area outside of the park is affected, then the whole action is blocked.
3. ~~Land rights: If the selected region has a single square that can not be bought, the action is blocked.~~ (fixed in #6610)

I would actually prefer if all tools behaved like 1. Thoughts?

**Comment by flipflop97** [comment]
+1 for consistency, this really bothers me sometimes.

**Comment by blackhand1001** [comment]
I agree with this one as well. I was actually gonna suggest the same.
