### ISSUE TITLE
Donut shop not rendered correctly

### ISSUE THREAD

**Issue by ccoors** [OpenRCT2/OpenRCT2#6535]
**OS:** Arch Linux x86_64
**Version:** 0.1.2
**Commit/Build:** 7ac4bf669ae765e00c9e687c7e4b89eb1d355876

From one viewing angle the donut shop is not rendered correctly.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Screenshots / Video:**
![2017-10-21-161658_5120x1080_scrot](https://user-images.githubusercontent.com/8963459/31852647-8651b8f4-b67b-11e7-9a5c-f7f7a1223e51.png)
![2017-10-21-161715_5120x1080_scrot](https://user-images.githubusercontent.com/8963459/31852648-866d8a5c-b67b-11e7-9dbc-c95017cd5679.png)

**Comment by duncanspumpkin** [comment]
What is wrong. You haven't said. Software renderer or opengl?

**Comment by rwjuk** [comment]
Confirmed - see below. When the shopfront is facing to the left, the counter is rendered yellow as it should be. When the front is facing to the right, you get the black areas visible.

This was with the software renderer on the latest build.

![openrct2_2017-10-24_14-20-44](https://user-images.githubusercontent.com/16639257/31945307-b701bd9e-b8c6-11e7-9e2e-a5f9effd85e7.png)
![openrct2_2017-10-24_14-21-10](https://user-images.githubusercontent.com/16639257/31945308-b71912e6-b8c6-11e7-8df1-6e1f26b2080b.png)

**Comment by duncanspumpkin** [comment]
Does this effect vanilla? It looks like a . dat image mistake.

**Comment by rwjuk** [comment]
No, it renders correctly in vanilla.

![rct2_2017-10-24_14-45-53](https://user-images.githubusercontent.com/16639257/31946557-10ef83c4-b8ca-11e7-8437-83a5ecffb2d7.png)

**Comment by ccoors** [comment]
Oh, yes, sorry, I guess my bug report was not very good. I really meant those black pixels.

**Comment by Gymnasiast** [comment]
We have had issues with that before... the [Rainbow path from TT](https://github.com/OpenRCT2/OpenRCT2/issues/1749) springs to mind, for example.
Also, the pause button is affected by it.
