### ISSUE TITLE
Balloon shop thumbnail not colourised

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/OpenRCT2#6536]
**OS:** macOS 10.13
**Version:** 0.1.2
**Commit/Build:** 7ac4bf669ae765e00c9e687c7e4b89eb1d355876

The balloon thumbnail in the rides window isn't properly colourised — balloons are black as a result. The ride construction window appears fine, however.

Tested with software rendering.

**Steps to reproduce:**
1. Open a scenario with the balloon shop invented.
2. Click 'new rides', 'shops'
3. Find the thumbnail having black balloons

**Screenshots / Video:**
![screen shot 2017-10-21 at 20 19 42](https://user-images.githubusercontent.com/604665/31854677-4ecba242-b69d-11e7-9d54-ad1227d6497f.png)

**Comment by Gymnasiast** [comment]
That's not the original balloon stall. It might be a bugged .DAT. Could you upload it?

**Comment by AaronVanGeffen** [comment]
Ha, you're right! The original uses blue balloons, of course... I must've deleted the wrong file at some point while cleaning up the object folder. I just restored the original, which doesn't suffer the problem.

Anyway, here goes: [BALLO.DAT.zip](https://github.com/OpenRCT2/OpenRCT2/files/1404415/BALLO.DAT.zip)

**Comment by AaronVanGeffen** [comment]
Just for the record: I thought this might be fixed by 5035492f8cf93a03eac799a92f8cb30df2bb3ed9, but it is not.

**Comment by trigger-death** [comment]
The balloon stall you uploaded is not the correct one. It uses the same preview image as the regular balloon stall. The balloon stall in your preview is not a duplicate, but one modified using stall creator as you can see it using the default stall creator background.

Also, this is most likely a remap color issue. And remap colors shouldn't be present in preview images (with the exception of water).

**Comment by AaronVanGeffen** [comment]
Yeah, @Gymnasiast already pointed out it was not the original one in an earlier comment. I'm not sure I agree with you on whether or not it's worth addressing, however. If properly supported, more people might start to make their shops recolourable, after all.

**Comment by Gymnasiast** [comment]
Can you load up this file in vanilla and see what it does?

Also, the preview image should not have remappable colours. It is a preview.
It's no problem having remappable colours on the actual stall. In fact, a very early one (the Dippin Dots stall from AE) is recourable.

**Comment by AaronVanGeffen** [comment]
With the attached object file present in the ObjData dir, I am unable to run the original game, neither using Wine nor in a Windows 10 VM. When the file is removed, the game launches without any problems, however.

I don't know how I ever picked up the object file in question, but I guess this settles the matter.
