### ISSUE TITLE
Preview not being removed for for Lift "Oil Derrick" when mouse dragged.

### ISSUE THREAD

**Issue by wesley42666** [OpenRCT2/OpenRCT2#6551]
**OS:** Windows 10
**Version:** v0.1.1
**Commit/Build:** Build 4601265

When building the default design for Lift called Oil Derrick, the game will not remove preview from the previous location when you move the mouse.

- [ ] Reproducible in RCT2 (vanilla)? No issues. Only in OpenRCT
- [ ] Multiplayer? Untested

**Steps to reproduce:**
1. Create a new "Build your own sixflags" park.
2. Create ride -> Lift
3. Pick Oil Derrick
4. Move mouse around.

**Dump file**
None

**Screenshots / Video:**
https://imgur.com/iUcSu7c

**Save game:**
Can easily be recreated in any savegame that has Oil Derrick enabled. Can be build by default in "Build your own Six Flags park" scenario.

**Comment by duncanspumpkin** [comment]
Can this be tested in the latest build.

**Comment by Gymnasiast** [comment]
Cannot reproduce in 6757633.

Please update to the latest stable.

**Comment by IntelOrca** [comment]
v1.1 is the latest release (stable)

Update to a develop build if you want the fix.

**Comment by wesley42666** [comment]
Could not replicate in the latest develop build (d924d77).
