### ISSUE TITLE
Android build lacks full immersive mode without top navbar

### ISSUE THREAD

**Issue by Invictaz** [OpenRCT2/OpenRCT2#6553]
**OS:** Android 6.0.1
**Version:** 0.1.2

The top bar is still shown with batterlife etc. This part of the screen cannot be used for scrolling with the mouse pointer.

**Screenshots / Video:**
![screenshot_20171025-001240](https://user-images.githubusercontent.com/20338545/31970749-71cdc350-b919-11e7-9b77-9477f23d09ad.png)

**Comment by Invictaz** [comment]
@AaronVanGeffen Please don't close issues that are NOT solved.

**Comment by Gymnasiast** [comment]
https://github.com/OpenRCT2/OpenRCT2/pull/10402 added fullscreen mode to Android.

**Comment by AaronVanGeffen** [comment]
It was my intention to leave a note with the PR number, but got sidetracked. Sorry about that.

**Comment by Invictaz** [comment]
Seems it requires Android 9 now :(

**Comment by Gymnasiast** [comment]
Well, it beats not having it run at all, which was the case until NuclearFej fixed it.

Now, can you please act a little less entitled? First, you assume the problem has not been fixed _without checking if that was the case_, then you place a rude comment to Aaron and when we point out that the bug has, in fact, been fixed, you're complaining that it doesn't work on your device. If you want support for Android 8, we're happy to accept your PRs.

**Comment by Invictaz** [comment]
I don't know what you want to read, but that was in no way a rude intended comment. 
And he started to close an issue without referring to the fix. The fix is appreciated.
