### ISSUE TITLE
Game actions write to stdout under normal circumstances

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#6561]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** be4fe7b681054fca071bec82f16361237128c471

When building rides or opening them, the following is written to stdout.
```
INFO[actions\GameAction.cpp:175 (GameActions::Execute)]: [sv] GameAction::Execute
```

This kind of stuff should be using `log_verbose` not `log_info`.

**Comment by rvoortman** [comment]
I'm working on it.

**Comment by duncanspumpkin** [comment]
@rvoortman only team members can assign themselves. It's a bit limited really.

**Comment by rvoortman** [comment]
@duncanspumpkin Thank you very much! Please bear with me since this is going to be my first contribution; I'm planning to contribute more, but I first have to dive into the codebase a little more.
