### ISSUE TITLE
I can only build using custom rides only id there a way so i can use preset built in like normal?

### ISSUE THREAD

**Issue by LightySan** [OpenRCT2/OpenRCT2#6563]
![untitled](https://user-images.githubusercontent.com/33108703/32031340-92678a14-b9ce-11e7-937e-e7064e660449.png)
 then i click the ride and instantly goes to custom building!!
![untitled2](https://user-images.githubusercontent.com/33108703/32031362-c2c92456-b9ce-11e7-8f54-9add215f274d.png)
can you please help? or explain how to fix please???

**Comment by LightySan** [comment]
im playing online with a friend aswell so yea i like the prebuilt car ride ^3^ its cool

**Comment by Krutonium** [comment]
There is not a way to use prebuilt rides in Multiplayer, no.

**Comment by LightySan** [comment]
OH ok thank you I did't know this and you were a great help.
