### ISSUE TITLE
Scenario not marked as cleared

### ISSUE THREAD

**Issue by flipflop97** [OpenRCT2/OpenRCT2#6566]
**OS:** Arch Linux
**Version:** 0.1.2
**Commit/Build:** c9c0c07

Upon clearing Gentleman's Garden from the OpenScenario Project the button to enter my name doesn't show up and it doesn't show as cleared on the new game menu. I haven't tested this yet with other scenarios on this build.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Install Gentleman's Garden scenario
2. Clear this scenario (load the savegame and fast forward for a few seconds)

**Dump file**

**Screenshots / Video:**
![screenshot from 2017-10-26 21-27-34](https://user-images.githubusercontent.com/13943260/32072873-841510e6-ba94-11e7-8f28-385c59921ad8.png)

**Save game:**
[Gentleman's Garden.zip](https://github.com/OpenRCT2/OpenRCT2/files/1419772/Gentleman.s.Garden.zip) (Just before clearing)  
[Gentlemans Garden - Xedoh - Beginner.sc6](https://github.com/Krutonium/OpenRCT2-OpenScenarios/raw/91ecb50d6e6cb25b6229d5dadf208d46840bec29/Scenarios/Gentlemans%20Garden%20-%20Xedoh%20-%20Beginner.sc6)

**Comment by TonyLaV** [comment]
Please go into Documents\OpenRCT2

Make a copy of the file highscores.dat ( Backup)

Delete the file in OpenRCT2 folder

Complete Gentlemens Garden again.

If you are able to typ in your name then do it.

Close Game

Go back to Documents\OpenRCT2

Open highscores.dat with Wordpad.

Look if Gentlemans Garden is typed in or another scenario.

If another scenario is typed in then replace the scenario name with gentlemans garden.

for example

six flags magic mountain.SC6 to gentlemans garden.SC6

After that look if your scenario is marked as won.

**Comment by flipflop97** [comment]
Hmm... loading my save and clearing it still doesn't allow me to input my name. Do I need to create a new save for this to work?

Build 7a099d90c

**Comment by Gymnasiast** [comment]
Yes. Or load an old save, one from RCT2 for example.
