### ISSUE TITLE
Smoothed Nearest Neighbor scaling

### ISSUE THREAD

**Issue by flipflop97** [OpenRCT2/OpenRCT2#6568]
UI scaling works perfect for me at integer scales. For 2x you can use Nearest Neighbor to still make it look good by keeping the 'sharp' look. At non-integer scaling there's the choice between Nearest Neighbor and Linear (Anisotropic looks the same as Linear to me), which both don't look really good in my opinion. Linear looks a bit blurry and NN looks deformed.

So I thought of this scaling method that is essentially the same as NN but with smooth edges (I don't know if it has a name). I made a few images upscaled to 1.5x to describe what I exactly mean: [linear](https://user-images.githubusercontent.com/13943260/32074323-42423e3c-ba99-11e7-9606-278ae354281d.png), [nearest neighbor](https://user-images.githubusercontent.com/13943260/32074324-425b675e-ba99-11e7-846a-54d8c046e4a9.png), [**smooth nearest neighbor**](https://user-images.githubusercontent.com/13943260/32074325-427439f0-ba99-11e7-87de-31ebbd1b6681.png). I made it by first upscaling 2x with NN and then downscaling it to 1.5x with linear scaling.

It looks sharper than linear scaling and not deformed like NN scaling. I think this scaling method will make the game look much better at non-integer values. Could this be added as an extra scaling method?

**Comment by janisozaur** [comment]
> Could this be added as an extra scaling method?

Sure, submit a PR.

**Comment by LinusU** [comment]
Wow, that actually looks much better 😄 I wonder if there is any existing games using something similar, I've never seen this technique before...

**Comment by flipflop97** [comment]
Well, it was just an idea with a mockup I made. I'm trying to figure out how to implement this, but it doesn't look that easy as it apparently isn't any kind of standard in SDL2.
