### ISSUE TITLE
Scenario in Wacky Worlds / Time Twister not marked as cleared

### ISSUE THREAD

**Issue by TonyLaV** [OpenRCT2/OpenRCT2#6573]
**OS:** [e.g. Windows 7]
**Version:** [0.0.6 x64]
**Commit/Build:** [2970]

I cant enter my name when i finish one of the scenarios of Wacky Worlds or Time Twister.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1.  Start Alcatraz
2.  Win the Scenario

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by rwjuk** [comment]
@TonyLaV You say you're running **0.0.6**. This is a very, very old version - could you download the latest build and retry?

**Comment by TonyLaV** [comment]
Im using the OpenRCT2 Launcher. The program downloads automatically the latest version.
I installed this version 

https://github.com/LRFLEW/OpenRCT2Launcher/releases/tag/v0.0.6

I also installed the latest file from here

https://openrct2.org/downloads

Sadly there is no difference and i still cant enter my name.

**Comment by janisozaur** [comment]
Launcher is completely external project and its version is not relevant at all. Please provide OpenRCT2 version.

**Comment by TonyLaV** [comment]
Im sorry, i didnt know that.

i downloaded this file ----> 0.1.2 build 3125956

I still cant enter my name.

**Comment by AaronVanGeffen** [comment]
> I still cant enter my name.

Are you trying with an old save, or a scenario as it triggers completion?

**Comment by TonyLaV** [comment]
With an old save file and with the cheat " win the scenario".

When i finish a scenario in RCT2 with this cheat , it allows me to enter my name.
When i finish a scenario in Wacky Worlds or Time Twister it does not.

Im using the german version and i only downloaded the RCT 1 Maps.
The cheat is also working with the RCT 1 Maps.

**Comment by TonyLaV** [comment]
I discovered something strange and it might help to fix the problem!

When i finish one off the scenarios in Time Twister or Wacky Worlds , i can enter my name when i finish the scenario the first time. 

BUT the scenario is not marked as won... SIX FLAG MAGIC MOUNTAIN gets cleared and i can see the same name which i used after completion.

So when i win Alcatrax for example , and i type in ''John''  as name , not the scenario Alcatraz is marked as cleared , the scenario Magic Mountain gets the marker and the name John.

**Comment by AaronVanGeffen** [comment]
Sounds like you're experiencing the same issue as #6248, then.

**Comment by TonyLaV** [comment]
Yeah, i already found the problem , but  im not able to solve it. 
In Documents\ OpenRCT2 there is a file called **highscores.dat**
Instead of Crater Carnage , Magic Mountain is typed in by the program.

I made screenshots here 
![crater carnage 2017-11-02 00-42-25](https://user-images.githubusercontent.com/33175850/32303286-dffd6836-bf67-11e7-9ea6-cb936f427d91.png)
![crater carnage 2017-11-02 00-42-38](https://user-images.githubusercontent.com/33175850/32303287-e2b5607e-bf67-11e7-80dd-ce857fa9d9a2.png)
![crater carnage 2017-11-02 00-44-06](https://user-images.githubusercontent.com/33175850/32303288-e40ed5a4-bf67-11e7-8f05-9230808110fd.png)
![test](https://user-images.githubusercontent.com/33175850/32303293-e71262ca-bf67-11e7-97b9-4a4c563c1275.jpg)

**Comment by Gymnasiast** [comment]
Fixed by https://github.com/OpenRCT2/OpenRCT2/commit/8422556bc1d19e8b5e697b72cce3ceccd24a4b56.
