### ISSUE TITLE
Footpath window won't go into underground mode

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/OpenRCT2#6575]
**OS:** macOS
**Version:** 0.1.2
**Commit/Build:** bc3b579b922674bafb658d24117923e5bf538bea

When the footpath window is active, I am unable to manually toggle the underground view mode. Clicking its toolbar icon enables it for a frame or so, but immediately switches back. When I use a keyboard shortcut instead, it doesn't even seem to trigger.

I realise this may be intentional, with the path tool automatically toggling underground view as needed. However, it consistently did not do so for me while I was trying to construct a path in the Gravity Gardens scenario, so not being able to toggle it manually was quite annoying.

**Comment by jensj12** [comment]
As soon as you hover over terrain on which you can place a path with the (click to place) path tool open, underground view is disabled. IIRC (can't check), the vanilla RCT2 only disabled it when moving the mouse, allowing you to remain in underground view as long as the mouse is not moved.

**Comment by AaronVanGeffen** [comment]
I thought I'd try and fix it, but I can no longer reproduce this. Tried with several scenarios, including the save I originally experienced the issue in. I'm assuming it was fixed in the mean time, intentionally or not.
