### ISSUE TITLE
Cannot hire entertainers in specific park

### ISSUE THREAD

**Issue by saxman1089** [OpenRCT2/OpenRCT2#6593]
**OS:** Windows 10
**Version:** 0.1.2-develop
**Commit/Build:** fb74d12

In my current park (attached), I cannot hire entertainers, but can hire other staff. When I press the button to hire entertainers, I get a red error box with the text "Cannot hire staff..." I am under the staff limit.

**Steps to reproduce:**
1.  Open attached park.
2.  Try to hire an entertainer.

**Screenshots / Video:**
![knoebels amusement resort 2017-10-30 21-41-40](https://user-images.githubusercontent.com/20549965/32203657-26b150b6-bdbb-11e7-98db-4bd9473da1b4.png)

**Save game:**
[Knoebels_v1.42 - Copy.txt](https://github.com/OpenRCT2/OpenRCT2/files/1429303/Knoebels_v1.42.-.Copy.txt)

**Comment by rwjuk** [comment]
It seems that no entertainer costume objects have been selected - where did this park come from originally?

**Comment by saxman1089** [comment]
It was a CSO workbench I got from online somewhere. I started the park over two years ago now, so I don't remember exactly where. I also looked in the object selection tool and couldn't see any way to add entertainer types, but I was wondering if something like this was the problem.

**Comment by Gymnasiast** [comment]
> It seems that no entertainer costume objects have been selected - where did this park come from originally?

Well, that's odd. The panda, tiger and elephant costumes should _always_ be available.

**Comment by IntelOrca** [comment]
No, I think you need the default scenery groups to enable the costumes. All costumes are available via scenery groups.

**Comment by Gymnasiast** [comment]
On it.

**Comment by IntelOrca** [comment]
We could force enable the panda, tigar and elephant regardless of scenery groups.

**Comment by Gymnasiast** [comment]
> We could force enable the panda, tigar and elephant regardless of scenery groups.

Well, guess what approach I took?

**Comment by saxman1089** [comment]
Many thanks to both of you! I really appreciate it! =)
