### ISSUE TITLE
Cmake: "No package 'sdl2' found" on Fedora Linux

### ISSUE THREAD

**Issue by fafrd** [OpenRCT2/OpenRCT2#6597]
**OS:** Fedora 25
**Version:** 0.1.2
**Commit/Build:** 3125956

Cmake is mad at sdl2, won't let me compile. installed Fedora dependencies per [https://github.com/OpenRCT2/OpenRCT2/wiki/Building-OpenRCT2-on-Linux](https://github.com/OpenRCT2/OpenRCT2/wiki/Building-OpenRCT2-on-Linux).

output of cmake:
```~/games/OpenRCT2/build $ cmake ..
-- Unsupported CFLAG: -Wmissing-variable-declarations
-- Unsupported CXXFLAG: -Wmissing-variable-declarations
-- Checking for module 'libpng>=1.6'
--   Found libpng, version 1.6.27
-- Checking for module 'sdl2'
--   No package 'sdl2' found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:412 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:588 (_pkg_check_modules_internal)
  src/openrct2-ui/CMakeLists.txt:15 (PKG_CHECK_MODULES)
  CMakeLists.txt:115 (include)


-- Configuring incomplete, errors occurred!
See also "/home/kian/games/OpenRCT2/build/CMakeFiles/CMakeOutput.log".
See also "/home/kian/games/OpenRCT2/build/CMakeFiles/CMakeError.log".
```

**Steps to reproduce:**
1. Try to build on fedora 25 using instructions from wiki

**Dump file**
[CMakeError.log](https://github.com/OpenRCT2/OpenRCT2/files/1432633/CMakeError.log)
[CMakeOutput.log](https://github.com/OpenRCT2/OpenRCT2/files/1432634/CMakeOutput.log)

**Comment by janisozaur** [comment]
Looks like wiki is missing sdl2 package, likely `SDL2-devel`. Please check and update wiki accordingly.

**Comment by fafrd** [comment]
Needed SDL2-devel yeah. ty. I updated the wiki
