### ISSUE TITLE
No permissions on headless server, users.json not saved

### ISSUE THREAD

**Issue by YellowberryHN** [OpenRCT2/OpenRCT2#6609]
**OS:** Linux (Ubuntu 16.04)
**Version:** 0.1.1
**Commit/Build:** Build 4601265

I am prevented from doing anything on my headless server, due to lack of permissions, which I am lacking the files to set. And it doesn't seem to be reading the files anyway.

- [ ] Reproducible in RCT2 (vanilla)?
- [X] Multiplayer?

**Steps to reproduce:**
1. Start headless server
2. Join server
3. Have no permissions
4. Leave server
5. Shutdown server
6. users.json unchanged, no groups.json

**Comment by Krutonium** [comment]
The workaround for this right now is to make a non-headless server, connect to it, give yourself perms, then move the relevant files to your headless machine.

**Comment by janisozaur** [comment]
I think `groups.json` is only created when you modify groups from default ones.

With https://github.com/OpenRCT2/OpenRCT2/pull/5183 `users.json` is saved on headless server, and you can modify it to add your user as you would normally.

So I'm confused what is this issue really about?

**Comment by IntelOrca** [comment]
@janisozaur we have had this question before. Because the headless server has no front end to change permissions it has to be done manually by changing files or in a normal sever first.

**Comment by janisozaur** [comment]
We create a `users.json` which has an entry for the server, but as the server has no key, the `hash` entry is left blank. This could be alleviated by first generating the key in server's (user's) name and then using it to fill in the entry.
