### ISSUE TITLE
OpenGL: colors distorted when using Intel drivers

### ISSUE THREAD

**Issue by carlu93** [OpenRCT2/OpenRCT2#6614]
**OS:** Windows 10 1607
**Version:** 0.1.2
**Commit/Build:** 8da1cad

When using the OpenGL renderer colors are somehow distorted. Changing to Software (Hardware accelerated) fixes it.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Use OpenGL renderer
2. See the colors getting distorted

**Screenshots / Video:**
![karts coasters 2017-11-03 22-38-42](https://user-images.githubusercontent.com/16781908/32396961-cc41a2cc-c0e7-11e7-8982-ad9898662db8.png)

**Comment by AaronVanGeffen** [comment]
Just for our reference, what kind of video card are you using?

**Comment by janisozaur** [comment]
@carlu93 can you:
* Specify you GPU
* Provide GPU driver version information
* Post a screenshot of the same scene with software renderer?

**Comment by Patrik356b** [comment]
Damn, that orange coaster looks so nice though, I'm envious xD

**Comment by carlu93** [comment]
Sure guys. Sorry for the delay.
1. Intel HD 630 (Kaby Lake)
2. Driver Version: 22.20.16.4771
3. 
![karts coasters 2017-11-04 10-28-40](https://user-images.githubusercontent.com/16781908/32404173-17037412-c14b-11e7-92dd-60481c880cd7.png)

Ahh using it with my NVIDIA 1060 (mobile) works actually. (Driver Version: 388.13)

**Comment by RugnirViking** [comment]
I am also seeing this issue with my video card being nvidia 940MX

**Comment by tabytac** [comment]
Also have the same issue using Intel HD 630 integrated graphics but changing to MX150 dedicated GPU on my laptop with a restart fixes it.

**Comment by Ryder17z** [comment]
I wonder if it's limited to just intel HD 600 series

**Comment by Ryder17z** [comment]
Intel HD 5500 has the same or worse issues

![image](https://user-images.githubusercontent.com/2000703/94407667-019f8e00-0174-11eb-93e9-5455af0ae05b.png)
