### ISSUE TITLE
Cant enter name in Future- First Encounter ( Time Twister )

### ISSUE THREAD

**Issue by TonyLaV** [OpenRCT2/OpenRCT2#6616]
**OS:** [Windows 7]
**Version:** [0,1,2
**Commit/Build:** [ce6ae6d]

I cant enter my name after finishing Future- First Encounter.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1.  Finish the Scenario by cheating or load my savegame. ( Its in german )
2. If you are loading my Savegame you have to repay the loan. ( 1000 € )

**Dump file**

**Screenshots / Video:**

![ausserirdische extravaganz 2017-11-04 10-43-08](https://user-images.githubusercontent.com/33175850/32404297-6e7150a0-c14d-11e7-8601-0d1d00610c1a.png)

**Save game:**

[Außerirdische Extravaganz.txt](https://github.com/OpenRCT2/OpenRCT2/files/1443102/Ausserirdische.Extravaganz.txt)

**Comment by runfalk** [comment]
I had the same issue today (same version but om Linux 64-bit) with Electric Fields. I completed the goal but did not get to input my name. It doesn't display as completed in the main menu either.

**Comment by AaronVanGeffen** [comment]
Both of you appear to be using a version that should have the recent fix from #6603. It would seem that fix wasn't good enough, then.

**Comment by TonyLaV** [comment]
With this fix i was able to complete the missions before. They didnt work before this fix. ( I wasnt able to enter my name or the scenario was not marked as won)

I dont know why this mission and probably others dont work now.

**Comment by muemart** [comment]
Did you by any chance load from a savegame before beating the scenario? Does it work if you beat the scenario in one sitting without saving and loading?

**Comment by runfalk** [comment]
I reloaded my game from an autosave because of #6617 

I haven't tried beating it in one go.

**Comment by TonyLaV** [comment]
No because i already tried to win the scenario with the cheat "win scenario" .

It worked every time and i was able to enter my name.  The WW and TT Scenarios are the only ones which are making problems for me.

**Comment by runfalk** [comment]
I loaded my save with the development build for #6621 but it did not allow me to enter my name once I reached the goal.

**Comment by TonyLaV** [comment]
When i delete the highscore.dat in Douments/OpenRCT2 im able to enter my name and the scenario is marked as won.

If i replace the highscore.dat with the backup again im again not able to enter my name.

**Comment by muemart** [comment]
@runfalk Your savegame is already damaged so it won't register correctly. I can try to fix it if you want it to work, but it shouldn't happen again when starting a new scenario.

@TonyLaV Can you upload your highscore.dat?

**Comment by TonyLaV** [comment]
Sure

Here:

[highscores.txt](https://github.com/OpenRCT2/OpenRCT2/files/1444323/highscores.txt)

**Comment by runfalk** [comment]
@muemart thank you, but since it's just a 2 year scenario I can just replay it :smiley:

**Comment by muemart** [comment]
Here is your savegame, it should work now.
[Ausserirdische.Extravaganz.txt](https://github.com/OpenRCT2/OpenRCT2/files/1445328/Ausserirdische.Extravaganz.txt)
I couldn't find anything wrong with your highscores, and beating this scenario works fine for me, so best try again with the fixed savefile.

**Comment by TonyLaV** [comment]
Thank you soo much. Everything is working now.

**Comment by rwjuk** [comment]
@TonyLaV Is this still an issue?

**Comment by TonyLaV** [comment]
No, I did not know if anyone else has a question.
