### ISSUE TITLE
Maze deletion costs insane amounts of money

### ISSUE THREAD

**Issue by runfalk** [OpenRCT2/OpenRCT2#6617]
**OS:** Linux Mint 18.3 (64-bit) and Windows 10 (64-bit)
**Version:** 0.1.2 
**Commit/Build:** ce6ae6d

If I try to delete Maze 1 I lose about £200M. This happens regardless of whether the host or the client deletes it. This problem does not affect the adjacent Maze 2.

- [ ] Reproducible in RCT2 (vanilla)? *No idea, don't have the game installed.*
- [x] Single player
- [x] Multiplayer

**Steps to reproduce:**
1. Select Maze 1
2. Delete Maze one

**Dump file**

**Screenshots / Video:**
![electric fields 2017-11-04 15-04-49](https://user-images.githubusercontent.com/864128/32406132-0ab815fa-c173-11e7-8470-470da1554cf6.png)

![electric fields 2017-11-04 15-04-50](https://user-images.githubusercontent.com/864128/32406140-1edc2e04-c173-11e7-8d52-c48dad0d9ec5.png)

**Save game:**
[Electric Fields.zip](https://github.com/OpenRCT2/OpenRCT2/files/1443245/Electric.Fields.zip) (not acutal zip, just renamed sv6)

**Comment by duncanspumpkin** [comment]
Issue is caused by the maze element not being fully hollowed out. I've made a PR with it fixed but you can also fix it by hollowing out that maze element at the top right.

**Comment by runfalk** [comment]
Thank you!

**Comment by telk5093** [comment]
This issue is occurs again in 67ebf40
