### ISSUE TITLE
Crash when loading Covey Cove

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#6618]
Hello! I found a park that causes OpenRCT to crash upon opening. They still exist!
https://www.nedesigns.com/park/826/covey-cove/

Using v0.1.2 ce6ae6d on Windows 8.

**Comment by IntelOrca** [comment]
This doesn't crash for me. It may have done before @Gymnasiast added the entrance / exit position fixes as there is a lot of instances of that written to stdout when opening the park - but it does load and run.
