### ISSUE TITLE
Winning some scenarios not working (Diamond Heights, Bumbly Beach) not working

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#6624]
I suspect there is something wrong with my old savegame, running build 45b7569

From the current point, just fast-forward until the scenario ends:

![openrct2_2017-11-06_04-16-16](https://user-images.githubusercontent.com/2000703/32423966-ead88660-c2a9-11e7-9ca7-025966a486de.png)

[Diamond Heights.zip](https://github.com/OpenRCT2/OpenRCT2/files/1444835/Diamond.Heights.zip)

**Comment by Patrik356b** [comment]
[Bumbly Beach2.zip](https://github.com/OpenRCT2/OpenRCT2/files/1445009/Bumbly.Beach2.zip)
![openrct2_2017-11-06_05-23-38](https://user-images.githubusercontent.com/2000703/32425346-bf055ad2-c2b2-11e7-9e44-a07e168fa2eb.png)

**Comment by muemart** [comment]
There was a bug with this that was fixed yesterday. Try again with the latest version and it should work. It's possible that savegames are broken and need manual fixing, but your saves should be fine.

**Comment by Patrik356b** [comment]
Retested on 8be9e15 - Diamond Heights sv6 is working, but not Bumbly Beach

**Comment by muemart** [comment]
The Bumbly Beach save you attached above works fine for me. If you overwrote the savegame then it probably broke, but the one attached here is ok.

**Comment by TheDevelo** [comment]
I had the same problem with my save on Botany Breakers. I tried it with new saves and the cheat option to win a scenario and found that if you used the Hyper Speed option, you couldn't win it, while you can win if you use any speed below Hyper Speed.

**Comment by Gymnasiast** [comment]
I'm going to consider this solved. It should be working, unless you loaded up and saved a save in the few days the develop version was broken. In this case your save is "corrupted".

**Comment by Patrik356b** [comment]
@Gymnasiast Fair enough I guess
