### ISSUE TITLE
No sound when pausing regression.

### ISSUE THREAD

**Issue by andoruB** [OpenRCT2/OpenRCT2#6626]
**OS:** Debian Sid 64-bit
**Version:** 0.1.2-develop build
**Commit/Build:** 4a66e98 / 4a66e98

There seems to be a regression from issue #2065. When I pause the game, I no longer hear any sounds (when selecting items from menus or clicking on buttons, or constructing. Turning the sound off, then on doesn't fix this issue, nor does changing the sound device.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Run the game normally.
2. Pause it, then click on various items.

**Comment by tupaschoal** [comment]
This doesn't happen anymore in v0.3.1
