### ISSUE TITLE
Idea: Implement features Chris Sawyer originally wanted to add, but which never made it into the final game.

### ISSUE THREAD

**Issue by Wimali** [OpenRCT2/OpenRCT2#663]
I imagine this would only be possible once the game has been "translated" more/completely, but I thought I'd post this already. Lookie here: http://www.nicscorner.com/evo_of_rct.htm

Tunnels, rusty tracks, trial circular entrance buildings, the track getting destroyed if a car blows up, a bus which brings more people to the park (maybe other vehicles as well, actually show how people arrive?). 

Just some inspiration!

**Comment by eezstreet** [comment]
Do you know if any of those art assets are preserved? The circular entrances look good, and they were added in RCT:LL anyway. Also those slides are cool.

**Comment by Gymnasiast** [comment]
@eezstreet: RCT1:LL introduced entrances with a circular _banner_, but otherwise still square. The entrance on the page has a circular base.

**Comment by Corsleutel** [comment]
I like the 'track needing a paint job'. Have it as an extra option for handyman's, also adding an option to have them paint coasters before they start to deteriorate. Also have this last option for grass would be nice, making your park always look well maintained.

**Comment by Gymnasiast** [comment]
Closed as @Wimali opened separate issues (which we prefer)/
