### ISSUE TITLE
Discord Integration

### ISSUE THREAD

**Issue by Krutonium** [OpenRCT2/OpenRCT2#6639]
I would like to suggest a new integration: Discord!

[Announcement](https://discordapp.com/rich-presence)

Discord now offers "Rich Integration", including the ability to show stats about current game, the ability to request to join a game, and more, which would be very interesting for our community, since by and large they congregate on Discord. We could show information like Guest Count, Park Rating, Scenario Name and Scenario Goal.

[Docs](https://discordapp.com/developers/docs/rich-presence/how-to)

Their API is [MIT](https://github.com/discordapp/discord-rpc/blob/master/LICENSE) Licensed, and available on GitHub, [Here](https://github.com/discordapp/discord-rpc). 

This would allow players to join each other, though port forwarding would still need to be handled, or at the very least share near-real-time statistics about their current games via Discord.

Thank you for your time.

**Comment by IntelOrca** [comment]
What platforms is this available for?

**Comment by janisozaur** [comment]
Looks interesting. It also looks like it's not tied to any particular platform?

**Comment by IntelOrca** [comment]
It is a library, so I was just wondering how widely distributed it was. It might try it out for Windows first and make it an optional requirement for Linux.

**Comment by janisozaur** [comment]
It looks like they are using some other json library, https://github.com/miloyip/rapidjson so we would have to bundle it as well or switch over?

**Comment by IntelOrca** [comment]
Yeah, but then you just find that we want to use some other library which uses some other json library and you can't win.

vcpkg does not have the discord library unfortunately so it means adding it to that too 😢

**Comment by janisozaur** [comment]
> RapidJSON is self-contained and header-only

@IntelOrca, I think it's right up your alley.

**Comment by IntelOrca** [comment]
Now that we use vcpkg, it doesn't make too much difference. I suppose it is more convenient even in that case.

**Comment by IntelOrca** [comment]
If the discord client ships the library as well, maybe we can just dynamically load that.

**Comment by janisozaur** [comment]
They have precompiled versions, it seems, I'm not sure for what platforms.

**Comment by janisozaur** [comment]
Win32 and Win64, both dynamic and static versions.

**Comment by IntelOrca** [comment]
Yeah, I was just wondering if they are shipped with discord. If so we can just load it from the user's discord installation.

**Comment by Krutonium** [comment]
```
**PS C:\Users\pfckr\AppData\Local\Discord> tree /F /A
Folder PATH listing
Volume serial number is 9AD1-7476
C:.
|   app.ico
|   SquirrelSetup.log
|   Update.exe
|
+---app-0.0.298
|   |   app.ico
|   |   blink_image_resources_200_percent.pak
|   |   content_resources_200_percent.pak
|   |   content_shell.pak
|   |   d3dcompiler_47.dll
|   |   Discord.exe
|   |   ffmpeg.dll
|   |   icudtl.dat
|   |   libEGL.dll
|   |   libGLESv2.dll
|   |   natives_blob.bin
|   |   node.dll
|   |   pdf_viewer_resources.pak
|   |   snapshot_blob.bin
|   |   Squirrel.exe
|   |   SquirrelSetup.log
|   |   ui_resources_200_percent.pak
|   |   views_resources_200_percent.pak
|   |
|   +---locales
|   |       am.pak
|   |       ar.pak
|   |       bg.pak
|   |       bn.pak
|   |       ca.pak
|   |       cs.pak
|   |       da.pak
|   |       de.pak
|   |       el.pak
|   |       en-GB.pak
|   |       en-US.pak
|   |       es-419.pak
|   |       es.pak
|   |       et.pak
|   |       fa.pak
|   |       fake-bidi.pak
|   |       fi.pak
|   |       fil.pak
|   |       fr.pak
|   |       gu.pak
|   |       he.pak
|   |       hi.pak
|   |       hr.pak
|   |       hu.pak
|   |       id.pak
|   |       it.pak
|   |       ja.pak
|   |       kn.pak
|   |       ko.pak
|   |       lt.pak
|   |       lv.pak
|   |       ml.pak
|   |       mr.pak
|   |       ms.pak
|   |       nb.pak
|   |       nl.pak
|   |       pl.pak
|   |       pt-BR.pak
|   |       pt-PT.pak
|   |       ro.pak
|   |       ru.pak
|   |       sk.pak
|   |       sl.pak
|   |       sr.pak
|   |       sv.pak
|   |       sw.pak
|   |       ta.pak
|   |       te.pak
|   |       th.pak
|   |       tr.pak
|   |       uk.pak
|   |       vi.pak
|   |       zh-CN.pak
|   |       zh-TW.pak
|   |
|   \---resources
|       |   app.asar
|       |   electron.asar
|       |
|       \---bootstrap
|               discord_rpc.zip
|               discord_toaster.zip
|               discord_utils.zip
|               discord_voice.zip
|               manifest.json
|
\---packages
    |   Discord-0.0.298-full.nupkg
    |   RELEASES
    |
    \---SquirrelTemp**
```
This is a directory listing of a default Discord install.

**Comment by Krutonium** [comment]
discord_rpc.zip in this case contains a NodeJS Version of the API, as far as I can tell.

**Comment by IntelOrca** [comment]
ok - vcpkg it is then

**Comment by janisozaur** [comment]
https://github.com/Microsoft/vcpkg/pull/2174

https://github.com/OpenRCT2/Dependencies/commit/aad738bf3d00ed866f6e86583a6d4ed062cbf034
