### ISSUE TITLE
certain Flying Coaster track piece does not exist

### ISSUE THREAD

**Issue by Ryder17z** [OpenRCT2/OpenRCT2#6641]
Version: 8be9e15
![2017-11-10_20-27-18](https://user-images.githubusercontent.com/2000703/32675059-d90bbd4e-c655-11e7-8458-d0031cfe81d0.jpg)

**Comment by zzril** [comment]
Cannot reproduce on f9d8c5923dff5c1fb2f119d1e54f630d450b9f2f. Was this solved by now?

**Comment by Ryder17z** [comment]
Doesn't seem to be a related commit. It should have been solved by commits affecting other tracked rides with similar issues, which could've been quite some time ago given the age of this bug report.

**Comment by zzril** [comment]
Yes, it was probably solved much earlier. Just wanted to give a definite point in time where I know the bug does not exist anymore.

Anyway, this can probably be closed.
