### ISSUE TITLE
a couple of issues with mazes

### ISSUE THREAD

**Issue by DollyMixedUpWoman** [OpenRCT2/OpenRCT2#6642]
**OS:** Windows 7
**Version:** 0.1.2
**Commit/Build:** d3692df

I've had a couple of issues re: mazes.
While moving a maze blueprint around (it hadnt been placed previously, i was still deciding where to put it) i was charged a ridiculous amount of money for my indecisiveness (see first screenshot)
When I attempted to recreate the issue in a fresh load of the scenario the game crashed whilst i was browsing maze blueprints. This issue has occurred to me in the past but not recently so i assumed it had been fixed in subsequent updates.

- [ ] Reproducible in RCT2 (vanilla)? - I don't know, i'm not sure where I put the disc to play vanilla!

**Steps to reproduce:**
1. Attempt to build a maze
2. move the blueprint deciding where to build
3. be charged lots of money
4. attempt to recreate original issue
5. watch game crash 

**Screenshots / Video:**
![error](https://user-images.githubusercontent.com/33560724/32684150-d6131646-c678-11e7-86a1-80a697772374.jpg)
![maze crash game](https://user-images.githubusercontent.com/33560724/32684153-dad22cc6-c678-11e7-869a-a17546710d8d.jpg)

**Save game:**

[Fruit Farm Maze Issue.txt.zip](https://github.com/OpenRCT2/OpenRCT2/files/1463117/Fruit.Farm.Maze.Issue.txt.zip)

**Comment by duncanspumpkin** [comment]
I changed the maze placement code earlier in the week. Looks like some parts are still wrong.

**Comment by Nubbie** [comment]
Could not reproduce on commit d3692df with the steps, even with a positive balance
Same with "newest" commit  891de0a

**Comment by DollyMixedUpWoman** [comment]
So I have only managed to recreate the money issue within the Fruit Farm RCT1 scenario. Attached is the save file for the scenario after I replayed and won it. As soon as i try to build the maze the money goes weird again.
![maze money](https://user-images.githubusercontent.com/33560724/32716673-c9908caa-c84e-11e7-89e6-3170fe30755e.jpg)
[Fruit Farm.zip](https://github.com/OpenRCT2/OpenRCT2/files/1466094/Fruit.Farm.zip)

I have loaded other saved games and have only replicated the game crashing when using the maze construction window.

![maze crash 2](https://user-images.githubusercontent.com/33560724/32716810-3f6a7a58-c84f-11e7-8127-9e912f40c7c4.jpg)

I don't know if it is relevant but these are all RCT1 scenarios I am playing... I haven't tried with RCT2 ones yet!

I do use the launcher so this has all been recreated this morning on commit 3fbdf11.

**Comment by Nubbie** [comment]
Still cant replicate,
Can you upload all maze designs?

**Comment by DollyMixedUpWoman** [comment]
[Pick Your Own Corn.zip](https://github.com/OpenRCT2/OpenRCT2/files/1472474/Pick.Your.Own.Corn.zip)

Hope this helps! As far as I know the rest are all the standard designs included in RCT1 and RCT2.

**Comment by Nubbie** [comment]
Yes it did :)
Could not crash the game on commit d3692df & 58e8ef5 _("newest")_
But the [Pick your own corn]( https://github.com/OpenRCT2/OpenRCT2/files/1472474/Pick.Your.Own.Corn.zip) object seems to be a bit broken, spams tool-tips, and with the combination of savefile "Fruit Farm Maze Issue.txt.zip", it makes you lose all cash

**Comment by AaronVanGeffen** [comment]
I cannot reproduce the issue, including with the Pick Your Own Corn track provided. So, this seems to have been resolved already, probably per the merge of #6966.
