### ISSUE TITLE
Cant bind Mouse Buttons ( Mouse 4 , 5 etc.)

### ISSUE THREAD

**Issue by TonyLaV** [OpenRCT2/OpenRCT2#6643]
**OS:** [Windows 7]
**Version:** [0.1.2]
**Commit/Build:** d3692df

1. I cant bind the sidebuttons of my mouse. The game doesnt recognizes the buttons.

2. Question:

Is it possible to create a button ingame which enables me to close all windows? Im playing only with my mouse and im not using my keyboard. 

- [ x] Reproducible in RCT2 (vanilla)?
- [ x] Multiplayer?

**Steps to reproduce:**
1. Try to assign the sidebuttons.

**Comment by Patrik356b** [comment]
While it's not the best solution, you can download autohotkey for free and write a script to make those buttons do something in OpenRCT2 and other software.

https://autohotkey.com
https://lexikos.github.io/v2/docs/Hotkeys.htm
https://lexikos.github.io/v2/docs/KeyList.htm

**Comment by TonyLaV** [comment]
Ok thank you. Should i close this thread?

**Comment by Patrik356b** [comment]
Should be kept open as it's a good suggestion to implement.

**Comment by hokasha2016** [comment]
My team and i will attempt to fix this issue and keep you guys informed

**Comment by hokasha2016** [comment]
@TonyLaV what mouse do you use if you dont mind me asking, because i believe i know the issue that the game doesnt recognize more than the left and right clicks; however id like to double check my findings.

**Comment by Patrik356b** [comment]
Hmm. Makes me wonder if the game recognizes "browser back/forward" because I have my Roccat Nyth set up like that.

**Comment by hokasha2016** [comment]
I've discovered that if you initialize the mouse binds of button 4 or 5, the back and forward, to keyboard values such as a shortcut (i.e. alt+4 or simply number 4 on the keypad) then the game will read it and it will be usable. This leads me to believe that not all of the buttons are detected, not even the scroll key is detected when used as a button rather than a scroller.

**Comment by hokasha2016** [comment]
@Patrik356b since there are keyboard shortcuts for the browser back/forward function, it might detect the same shortcut but im not quiet sure

**Comment by ocalhoun6** [comment]
_While_ we're on the subject of recognizing mouse inputs...

It would be nice if certain windows in-game could recognize side-scrolling. (Particularly, the mini-map, finances window, and ride graphs.) I know support for side-scrolling isn't super common, but certain windows seem like they could really make good use of it.

**Comment by ZBrettonYe** [comment]
The problem I have right now is SDL library have different code for keyboard and mouse input. I have hard to find the solution for this issue

**Comment by IntelOrca** [comment]
Resolved by #13848
