### ISSUE TITLE
Can't change username

### ISSUE THREAD

**Issue by Remixful** [OpenRCT2/OpenRCT2#6644]
**OS:** Windows 10
**Version:** 0.1.1
**Commit/Build:** 4601265

Can't change username

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

My username won't change on multiplayer.
I've even tried editing it in config.ini (which does save) and it doesn't change my username still.

**Update**:
My username only changes when I join other servers. It does not change when I create a server. It uses the same username I used when I last hosted. I've tried restarting multiple times, starting new games, picking random scenarios. It doesn't change.

**Comment by Remixful** [comment]
Deleting users.sjon in `Documents\OpenRCT2` fixes it.

**Comment by IntelOrca** [comment]
Duplicate of #5792
