### ISSUE TITLE
Max cars per trains rct1 vs rct2 discrepancies. 

### ISSUE THREAD

**Issue by blackhand1001** [OpenRCT2/OpenRCT2#6646]
RCT1 had higher max car counts for the following rides:
Steel Twister could have 8 cars instead of 7
Wooden coaster 2 row could have 7 cars instead of 6.
Looping Coaster could have 8 cars instead of 7.

It makes sense to either patch these files or add code in to fix increase them. Especially since there are many real life coasters of these types with these numbers of cars. 

I will update this thread with additional ones as I find them.

**Comment by blackhand1001** [comment]
For steel twister the change is only supposed to apply to the normal sitdown coaster. Not the rest. They were all correct. You lowered the max car count on the hypertwister wide train with your fix.

**Comment by Gymnasiast** [comment]
> You lowered the max car count on the hypertwister wide train with your fix.

I doubt that. Was it more than 8?

**Comment by blackhand1001** [comment]
Yes it was 9 for hypertwister. You can confirm that with Nitro in the Great Adventure scenario.

**Comment by Gymnasiast** [comment]
Ok, and the Floorless was 7 in RCT1?

If so, I'm going to keep that at 7, for consistency with the rest.

**Comment by blackhand1001** [comment]
Floorless was 8 in rct1 but it already is correct so it doesn't need a fix. Only sit down and standup need the fix.

**Comment by Gymnasiast** [comment]
I pushed a fix.
