### ISSUE TITLE
Changelog window causes FPS drop

### ISSUE THREAD

**Issue by flipflop97** [OpenRCT2/OpenRCT2#6647]
**OS:** Arch Linux
**Version:** 0.1.2
**Commit/Build:** 891de0ad3

When the changelog window is open, my FPS drops from 60+ FPS to about 20-40 FPS depending on the map and zoom level.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open the changelog window
2. Watch the FPS change

**Comment by AaronVanGeffen** [comment]
This still happens on 01e14e10bbf93df3dbfc588ea63f72d4184093a6.
