### ISSUE TITLE
While in Scenario Editor, the next/previous buttons may disappear

### ISSUE THREAD

**Issue by Ryder17z** [OpenRCT2/OpenRCT2#6653]
Version: bd0bd9e
![openrct2_2017-11-12_05-20-12](https://user-images.githubusercontent.com/2000703/32695950-8e9743a4-c769-11e7-8f77-99a50673be6c.png)

**Comment by jensj12** [comment]
Tap 'T'. Also works in normal gameplay.

**Comment by Patrik356b** [comment]
Okay, good to know.

**Comment by Gymnasiast** [comment]
Yes, but there are more cases where this happens without the user pressing 'T'.

**Comment by Patrik356b** [comment]
I didn't encounter this before, nor do I know how to reproduce it

**Comment by Gymnasiast** [comment]
I’m going to assume it was just an accidental press of `T` and that there are no other (more complicated) bugs that cause this.

**Comment by Ryder17z** [comment]
I don't think that is the case but I don't know. It's possible that the issue has been resolved by accident already.
I'll come back to this issue if I can reproduce it on a current build.
