### ISSUE TITLE
Crashes if window sizes have not proper ratio at scenario editor in additional languages

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#6656]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** 04f0048

Game crashes in certain circumstance.

**Steps to reproduce:**
1. Set window size(``window_height`` and ``window_width``) as ``721`` and ``481`` respectively, with not proper ratio like below: (Notice that window size as 721x481, not 720x481)
2. Change the language as the additional language, such as Chinese, Korean, Japanese, Arabic, Russian or etc.
3. Enter Scenario Editor or Track Designer, then game crashes without dump files.

**config.ini** :
```
window_height = 481
window_snap_proximity = 5
window_width = 721
```

**Dump file**
No dump files are created.

**Comment by Nubbie** [comment]
Have noticed the game crashes & create assertion errors when the game switch font
This might be a reliable way to test it - will see if I can create a dump tomorrow

**Comment by telk5093** [comment]
It is not reproduced in the recent builds, I think it is fixed anyway. I'll close it.
