### ISSUE TITLE
Scratchy Audio in 0.1.2

### ISSUE THREAD

**Issue by Asylum0722** [OpenRCT2/OpenRCT2#6667]
**OS:** Windows 10 x64 (Fall Creators update)
**Version:** 0.1.2
**Commit/Build:** 5409ded

I've noticed that since last Saturday or Sunday (so probably an eariler commit before this), all of the music in the game sounds noticeably more scratchy. I've compared this to the stable build and the stable build sounds much better. It is only an issue with the music.

- [ ] Reproducible in RCT2 (vanilla)?

- [x] Multiplayer?

**Steps to reproduce:**
1. Download Development build
2. Open the game, it is immediately noticeable in the title music.

**Comment by IntelOrca** [comment]
This is possible related to Windows builds now using SDL 2.0.7.

**Comment by HexRealm** [comment]
I can confirm this also happens on my desktop & laptop, both are running Windows 8.1. The stable branch sounds normal.

**Comment by blackhand1001** [comment]
I also am having this issue. Its quite bad.

**Comment by Krutonium** [comment]
I've noticed it as well.

**Comment by IntelOrca** [comment]
I am unable to reproduce this which makes it very difficult for me to investigate. Is there anyone able to look into this that does experience this issue?

**Comment by Patrik356b** [comment]
Also unable to reproduce on same OS

**Comment by Krutonium** [comment]
It might be an interaction with Audio Drivers, since it went away when I installed non-generic drivers on my computer.

**Comment by telk5093** [comment]
Same for me, and I've installed many old versions that can be found in [here](https://ci.appveyor.com/project/IntelOrca/openrct2-ject9/history),
In my case, this issue doesn't occur in 04f00484 (11334) and firstly occurs in 787c9acc (11335, seems that user's commit that does not exists not).
And note that the right after history was something about Discord integration(3fbdf117).

**Comment by IntelOrca** [comment]
@telk5093 no, it is most likely the update to SDL 2.0.7

**Comment by shiioo** [comment]
Also have that issue, playing with the latest build 1f4643b19c7cb7af3a90abcf543a1bc5e0ad46bf
Running on Windows 7 x64 with a Sound Blaster Z soundcard (and its latest official drivers).

**Comment by ufos** [comment]
Same issue here but I'm using Windows 7 64bit and Realtek ALC1150 soundcard. Right now it's just unplayable for me. :/

**Comment by Seddigirl** [comment]
I'm having the same scratchy audio on linux on both 0.1.1 and 0.1.2 with a scarlett 2i2

**Comment by heinermann** [comment]
Issue occuring for me on 0a28b6e provided by AppVeyor (Win10 64-bit).

**Comment by Patrik356b** [comment]
I'm curious as to why it doesn't happen on some setups, like my desktop where I use an usb DAC

**Comment by Seddigirl** [comment]
I am using a usb DAC too and it happens for me

**Comment by KamenRiderBlackRX** [comment]
Installed the lastest build (cc27bee), having the same issue (Win10 64-bit).

**Comment by xenoswift** [comment]
Just installed RCT2, vanilla is fine but having the same problem on 0.1.2-develop ( 3fbdf11 ). Running Win7 64-bit, Realtek ALC892 on driver version 6.0.1.7023, outputting to Razer Kraken 7.1V2 which is USB (driver version: 14.0.20.592).

**Comment by Lastorder-DC** [comment]
Reproduciable at build 14075b8.
my soundcard driver is `Cirrus Logic CS4208 (AB 123)`(Macbook Pro with Retina 2015 Early).

Building openrct with version 13 dependencies(which uses SDL 2.0.6) solves problem for me.

**Comment by ivivaitylin** [comment]
Just installed the game for the first time and having this problem, using build 676bb47
64 bit version, running x64 Windows 10, fully updated. Using a Logitech G930 headset.

**Comment by blackhand1001** [comment]
Is there any progress on investigating this issue?

**Comment by AaronVanGeffen** [comment]
> Is there any progress on investigating this issue? Perhaps revert back to sdl 2.0.6 until the issues with the 2.0.7 are resolved?

SDL 2.0.6 will crash the game; reverting to 2.0.5 may fix the issue for you.

@ZehMatt was looking into this with some success the other day. Hopefully, it will be resolved soon.

**Comment by HugoZink** [comment]
Same problem here. Hope you can find it soon.

**Comment by Gymnasiast** [comment]
I have taken off the 'Windows' label, since I also get this on my Linux system.
