### ISSUE TITLE
Banner limit calculation bug?

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#667]
I had a few times that I got a warning about I reached the banner limit. Now once again and I only build something around 5 banners. On some sites they say the limit is 250, but nobody knows it exactly and it also seems nobody knows if only the placable banner are counted into this limit or also the ones from the queues etc. 

But after building 5 banners in a not so large park and then getting this message about I reached the Banner limit?! There seems to be a bug in the calculation in the number of the Banner limit. This bug occurs in OpenRCT2, but also in vanilla RCT2.

**Comment by Gymnasiast** [comment]
Can you upload a SV6 of that park which only contains 5 banners? It might help with investigating.

**Comment by mrtnptrs** [comment]
Here is the savefile: https://drive.google.com/file/d/0Bwc5O5IR0pMpUTczbkxQa1lQUWc/view?usp=sharing

**Comment by Gymnasiast** [comment]
I tested it in both vanilla RCT2 (US CD version) and OpenRCT2. The SV6 behaves the same in both versions Destroying a banner allows one to build one again, but after that the message appears again.

The park itself is pretty simple, no custom objects or rides (just incredibly silly names) and not a lot of scenery - in other words, not a SV6 you might expect to cause problems. The only thing I can imagine (and that's just an educated stab in the dark) is that the game has a banner counter somewhere, which contains an incorrect value.

**Comment by mrtnptrs** [comment]
Sorry for the names, I played it with my sister and I of course have to work on her nerves ;) But could it be this bug is also present in OpenRCT2?

**Comment by Gymnasiast** [comment]
Yes, the error is present in both vanilla RCT2 and OpenRCT2. I tested it in both.

Any bugs that are in vanilla RCT2 are also in OpenRCT2, unless they are fixed by the OpenRCT2 developers (obviously).

**Comment by mrtnptrs** [comment]
Could it be possible to just remove (or comment out the code of) the Banner limit, till this bug is fixed? Or isn't the code for the banner limit decompiled yet or is this far too difficult?

**Comment by duncanspumpkin** [comment]
Banner limit check will probably be in GAME_COMMAND_50 which has not been done yet. It wouldn't be a good idea to comment out the limit anyway since the knock on effects can be unexpected. It is likely when game command 50 is finished that the issue causing this bug may be found.

**Comment by IntelOrca** [comment]
Note: e9b5282 was only a fix for saved games that were affected by this bug.

**Comment by Gymnasiast** [comment]
The save in question was created (and apparently corrupted) by vanilla RCT2. The bug that _causes_ the corruption might or might not be in OpenRCT2.

**Comment by mrtnptrs** [comment]
I can now confirm that the corruption is not vanilla-only, as this also happened to me with a completely fresh started scenario in OpenRCT2 (build you own six flags park, the same scenario as the above save file.) So, the save was created in OpenRCT2 and never opened in RCT2. So, OR the specific scenario has a corrupted banner count at start OR OpenRCT2 contains the same bit of bugged code that causes this corruption.

Save file:
[Six Fingers.zip](https://github.com/OpenRCT2/OpenRCT2/files/371820/Six.Fingers.zip)
