### ISSUE TITLE
Switch number of cars and trains back to a dropdown menu instead of a ticker. 

### ISSUE THREAD

**Issue by blackhand1001** [OpenRCT2/OpenRCT2#6670]
Switch number of cars and trains back to a dropdown menu instead of a ticker. 

It allowed you to see in one step how big you can make a train and you were able to see the train limits without closing a ride. This was how it was in rct2.

**Comment by duncanspumpkin** [comment]
It was changed for a reason.

**Comment by blackhand1001** [comment]
Surely we can modify the code for the cheat to work with a drop-down. I can take a look at that later today.
