### ISSUE TITLE
Deployed Linux builds missing discord-rpc.so

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#6675]
**OS:** Linux
**Version:** 0.1.2
**Commit/Build:** 0f3b6b1590de8044fdbd277a5e69d35fced0b7dc

The deployed Linux builds link to `discord-rpc.so` but do not distribute it. Users will get an error message saying it can't find it when trying to run the game.

**Comment by janisozaur** [comment]
Depends on already merged https://github.com/discordapp/discord-rpc/pull/30, I will submit a pr to fix this later today

**Comment by janisozaur** [comment]
Fixed in https://github.com/OpenRCT2/OpenRCT2/pull/6676

**Comment by IntelOrca** [comment]
@janisozaur still missing from builds.
