### ISSUE TITLE
MSVC ARM builds

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#6682]
**OS:** Windows 10
**Commit/Build:** 36236d8

List of (known) issues preventing MSVC from creating ARM (UWP) builds. This is also collecting all the roadblocks not in OpenRCT2 itself, but also in its dependencies.

- [x] ~~libzip does not compile, it tries to use deprecated POSIX functions, mainly WinCryptoAPI. See https://github.com/OpenRCT2/OpenRCT2/pull/6629 for a workaround.~~ ~~Fix for UWP got merged upstream: https://github.com/nih-at/libzip/pull/16, still need to wait for another release to update vcpkg.~~ merged in https://github.com/Microsoft/vcpkg/pull/2633

- [x] ~~discord-rpc does not build due to `CreateFileW`, `lstrcpyW`, `RegCreateKeyExW` are not available. This can possibly be triggered on x86 as well for UWP packaging.~~ Not a strict requirement, will skip it for initial version
- [x] ~~jansson uses unavailable [`GetModuleHandle` in `json_object_seed`](https://github.com/akheron/jansson/blob/bc5741fb1ac730ead24e9bd08977fc6c248e04b0/src/hashtable_seed.c#L114)~~ Fixed in https://github.com/Microsoft/vcpkg/pull/2244
- [x] ~~sdl2 does not build properly for ARM with MSVC, looks like setup issue, where it uses VS2015 directory even with VS2017?~~ works as of e6c65b93b125cf0be13254cf2f5a9d27cb009707
- [x] ~~speexdsp cmake [hardcodes `_USE_SSE` define](https://github.com/Microsoft/vcpkg/blob/790c3777b7eaf3c8d1894abc2694038e2858141d/ports/speexdsp/CMakeLists.txt#L21), which makes speexdsp pull in x86/x86-64-only `xmmintrin.h` (and then use it)~~ Fixed in https://github.com/Microsoft/vcpkg/pull/2245
- [x] freetype works as of 1b2f75b
- [x] zlib works as of 1b2f75b
- [x] libpng works as of 1b2f75b
- [x] curl works as of 1b2f75b
- [x] Google benchmark requires an update to gather clocks: https://github.com/google/benchmark/pull/1052

**Comment by janisozaur** [comment]
Log from attempt at building x86-uwp version: 
[x86-uwp.log](https://github.com/OpenRCT2/OpenRCT2/files/1503413/x86-uwp.log)

@IntelOrca any chance you can help out with any of that?

**Comment by IntelOrca** [comment]
These will all be things that are not available in UWP, e.g. registry, common file dialogs etc. You will have to exclude those features from compilation until you find an alternative.

**Comment by janisozaur** [comment]
Yeah, I know. I was hoping more of you could look into path resolution, as this will need to be implemented anyway. There are also some instances of `lstrcpyW` that might need changing to something else.

We can live without file deletion.

**Comment by IntelOrca** [comment]
You would have to move to using Windows 10 API. When I looked into using the game bar API awhile ago, I found using these APIs a pain in C++ because they are built for .NET and therefore have to be access via COM mechanisms.

**Comment by IntelOrca** [comment]
This is an example of how you might get files in C++:
```c++
auto folderPicker = ref new FolderPicker();
folderPicker->SuggestedStartLocation = PickerLocationId::DocumentsLibrary;
folderPicker->FileTypeFilter->Append("*");

create_task(folderPicker->PickSingleFolderAsync()).then(
    [](StorageFolder^ folder)
    {
        create_task(folder->GetFilesAsync()).then(
            [](IVectorView<StorageFile^>^ files)
            {
                auto count = files->Size;
                for (unsigned int i = 0; i < count; i++)
                {
                    auto file = files->GetAt(i);
                    wprintf(L"%s\n", file->Path->Data());
                }
            });
    });
```

Access is granted to a folder when the user selects it via the folder picker.

**Comment by janisozaur** [comment]
So far this has mostly concerned UWP builds, but it is possible to target desktop as well: http://pete.akeo.ie/2017/05/compiling-desktop-arm-applications-with.html

**Comment by janisozaur** [comment]
With https://github.com/Microsoft/vcpkg/pull/2633 merged ask the libraries we use are capable of producing builds targeting UWP. The remaining work is in OpenRCT2 itself.

**Comment by janisozaur** [comment]
vcpkg now supports `arm-windows` triplet (https://github.com/Microsoft/vcpkg/pull/2371) and there's no need to fully support UWP.

I haven't yet checked status of our required libraries when using this triplet.

**Comment by janisozaur** [comment]
There were builds uploaded to https://github.com/janisozaur/arm64-binaries/tree/master/openrct2

**Comment by janisozaur** [comment]
![screenshot](https://user-images.githubusercontent.com/550290/124398879-6b0e8780-dd18-11eb-8819-0f19ccc6d013.png)
