### ISSUE TITLE
Ride stats not calculated for shuttle-style rides

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#6687]
**OS:** Windows 8
**Version:** 0.1.2
**Build:** 9a40219

Ride intensity, nausea and excitement is no longer calculated for rides which do not consist of a full circuit, like reverse-incline launched shuttles or reverse freefall rollercoaster, or shuttle loop. Latest version where this is still working correctly is build 13f99f4

**Steps to reproduce:**
1. Build shuttle ride
2. test it

**Comment by Gymnasiast** [comment]
Also fixed in 81ee4793dfb77b795e7158f9c568af774a8bd04a.
