### ISSUE TITLE
Can't hear the ride music

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#669]
You can't hear the ride music, as it just doesn't play, even if you turn it on.

**Comment by Gymnasiast** [comment]
That's odd. It does play for me. (Running via Wine.)

**Comment by mrtnptrs** [comment]
I could reproduce this with a SV6 savefile from RCT2. There was no ride music playing anymore and also when I enabled it at attractions, I did not hear it. Maybe it's also good to mention that I'm using the Steam version of RCT2?

**Comment by Gymnasiast** [comment]
Have you turned on Music in the Options window? (I.e. not just at the rides themselves?)

**Comment by mrtnptrs** [comment]
Well, good point, will look at it! :)

**Comment by mrtnptrs** [comment]
Sorry, this didn't help, Music was already turned on at the options window. I checked it now again, but I did too last night. Also changing the sound quality and check the Sound option (aanvinken) doesn't resolve the problem.

**Comment by AaronVanGeffen** [comment]
It works for me in Wine, too. Are you compiling the game yourself, or using the automated builds?

**Comment by mrtnptrs** [comment]
Automatic builds...

**Comment by AaronVanGeffen** [comment]
Really shouldn't be, as Wine is an implementation of the Windows API.

Do sound effects work, e.g. guests chattering, cash sound? If not, try choosing a different sound device.

**Comment by mrtnptrs** [comment]
Chosing an other sound device doesn't solve the problem... But I will look if I hear the other sounds correctly.

**Comment by mrtnptrs** [comment]
Ok, now I found the real issue. The sound plays, but it's almost impossible to hear, because of the other sounds, but primarily because the much higher resolution; this causes the closest zoom option to be much further away then at Vanilla RCT2. This makes the distance between you and the ride bigger an that's why you almost can't hear the music. Could I be right?

**Comment by Gymnasiast** [comment]
I use a 1920x1200 screen in window mode. Compared to vanilla RCT2 it doesn't seem softer. However, I do get choppy sound sometimes, which may be related.

**Comment by duncanspumpkin** [comment]
I also can not notice any differences. I play with it at default 640*480.

**Comment by mrtnptrs** [comment]
But there is still a bug in OpenRCT2 that doesn't let me change the resolution, so I can't look if this resolves my problem.

**Comment by mrtnptrs** [comment]
Ok, after playing in windowed mode (with a smaller resolution) I can finally hear the ride music, but it seems to be less loud then in vanilla RCT2.

**Comment by Gymnasiast** [comment]
This report is now a year old, and OpenRCT2 has changed a lot. Do you still have this issue?

**Comment by janisozaur** [comment]
We fixed a bunch of audio bugs recently and there was no response from issue author in a long time – closing.

**Comment by mrtnptrs** [comment]
Sorry, forgot about this issue, yes, it got fixed
