### ISSUE TITLE
Entrance gets deleted when any track piece is deleted in building mode

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#6690]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** 8ffe7d5

Whenever I delete any track piece of a ride to alter it, the entrance also gets deleted. Happens since 9a40219

**Screenshots / Video:**
![test park 2017-11-17 19-44-34](https://user-images.githubusercontent.com/25930360/32963333-ec2c5788-cbcf-11e7-9407-8c2da61ba707.png)
![test park 2017-11-17 19-44-37](https://user-images.githubusercontent.com/25930360/32963336-ee0bffe0-cbcf-11e7-905d-1c636e03af0c.png)

**Comment by Patrik356b** [comment]
Might be caused by a slip-up in #6668

**Comment by Gymnasiast** [comment]
I think it's the same issue as in https://github.com/OpenRCT2/OpenRCT2/issues/6274.

Can you test with a two/three day old build?
