### ISSUE TITLE
Problems With Multiplayer (What Version?)

### ISSUE THREAD

**Issue by TurtleShroom** [OpenRCT2/OpenRCT2#6694]
**OS:** Windows X (Sixty-Four Bit)
**Version:** N/A
**Commit/Build:** N/A

- [N] Reproducible in RCT2 (Vanilla)?
- [Y] Multiplayer?

**Steps to reproduce:**
1. Open RCT2 in the last stable version from three months ago OR in the latest Development Build from three hours ago
2. Check the MP Server list

**Dump file**

**Screenshots / Video:**

![glitch](https://user-images.githubusercontent.com/17663470/32976632-e607fa42-cbe8-11e7-9195-3f3bb3a768c6.png)

-------------------------------

Good evening.

I am struggling with getting my version to match the one that everyone else is using. I have no idea where to find it or what it is. I have tried this with both the most recent Development Build AND the last stable version from three months ago.

The attached screenshot, shown above, is the error I get. This error occurs on every server but one that I have tried. Everyone has the version mentioned in the screenshot, but I can't find that version.

Is there anything that can be done to help me locate the correct version? As I said, I tried the last stable version AND the latest Development Version. I have tried it with and without the Launcher.

Thank you for your assistance.
-TURTLESHROOM

**Comment by Krutonium** [comment]
Download and use the Launcher, make sure it is set to Development, and it *should* work.

**Comment by telk5093** [comment]
Download the latest **develop**ment version, not stable.

**Comment by janisozaur** [comment]
We occasionally change network version, whenever there are changes either to simulation of logic or the way clients interact. Most will use latest release or current develop. You can check chafes to network versions here: https://github.com/OpenRCT2/OpenRCT2/blob/06cd6a958e7efdbb8ec01594a0604627c00e9c83/src/openrct2/network/network.h#L54
