### ISSUE TITLE
libpng12.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zayuim** [OpenRCT2/OpenRCT2#6697]
**OS:** Ubuntu 17.10
**Version:** Latest Stable and Developers 
**Commit/Build:** OpenRCT2 Build: 2681

Despite installing not only libpng but also making sure all other dependencies mentioned on the [launcher page](https://github.com/LRFLEW/OpenRCT2Launcher/releases/tag/v0.0.6). When I go to launch the game (the launcher itself works fine). I get `libpng12.so.0: cannot open shared object file: No such file or directory`

This issue is odd because the game has worked previously.

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Dump file**
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen factors.
   QT_SCALE_FACTOR to set the application global scale factor.
/home/user/.config/OpenRCT2/bin/openrct2: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory

**Comment by IntelOrca** [comment]
I think the distributed Linux builds target Ubuntu 16.04. It might be that you have recently updated your distro. In any case install the `libpng12` package if possible.

**Comment by Gymnasiast** [comment]
Libpng12 is not available in anything beyond 16.04. Ubuntu has moved on to Libpng16.

However, you could try to install it from a deb: https://packages.ubuntu.com/xenial/libpng12-0
Pick 'amd64' if you have a 64-bit Intel or AMD processor, pick 'i386' if you have a 32-bit Intel or AMD processor.

**Comment by Gymnasiast** [comment]
@zayuim Have you tried this?

**Comment by zayuim** [comment]
@Gymnasiast Yes it does, sorry for the wait. In an older develop and stable version, it was asking for some more dependencies, however after trying again after an update they all seem satisfied. Was there an update in a develop that changed this

**Comment by Gymnasiast** [comment]
So I gather this is solved? I'll close the issue then.
If you have more problems, please let us know.
