### ISSUE TITLE
Maze rendering issues

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#6700]
Version: 8be9e15 / 03299b9 (Win x64 8.1/10)
![openrct2_2017-11-19_17-48-09](https://user-images.githubusercontent.com/2000703/32992978-e732db98-cd51-11e7-83dc-ee52591e0bc5.png)
Does work correctly in 45b7569

**Comment by marijnvdwerf** [comment]
Introduced by #6685
