### ISSUE TITLE
Make multiple rides calculate test-data at the same time

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#6703]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** 03299b9

Related:
#5257, #4695, #5070

As rides gets calculated with the data about itself, if it gets stuck in a loop, no other coasters can calculate their data as only one can be calculated at a time

> [This is usually caused by one particular ride getting stuck in an infinite loop while calculating results. Can happen with hacked rides.](https://github.com/OpenRCT2/OpenRCT2/issues/5257#issuecomment-282227768)

> [This was discussed before with the solution off letting more coasters get calculated the same time](https://github.com/OpenRCT2/OpenRCT2/issues/5070#issuecomment-272619416)

**Comment by YoloSweggLord** [comment]
Would you set a limit on how many rides could be calculated at once? If not, would too many rides being calculated start to cause performance issues?

**Comment by Nubbie** [comment]
Think I've heard from Duncan the score gets re-calculated which, if it lowers performance, could create lag spikes, so a hardcoded limit would be safe I presume

**Comment by YoloSweggLord** [comment]
Then the issue becomes that someone could build multiple stat-breaking rides, flooding out the limit. How about a system which calculates the *n* most recent rides?

**Comment by janisozaur** [comment]
@YoloSweggLord that's unfeasible for multiplayer.

**Comment by Nubbie** [comment]
Well, rather 3 coaster needs to be "broken" than one
If not, which I heard were rejected, a time-limit and error message of some sort

**Comment by IntelOrca** [comment]
The problem is that SV6 can only store progress for one ride. This means that it would require extra data to be sent across network for the progress of extra rides and they are lost for good if saving to SV6.

**Comment by sjoerddebruin** [comment]
Was added in #19683.
