### ISSUE TITLE
List of available vehicles in New Ride window is too wide in certain circumstances

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#6717]
**OS:** Windows 7
**Version:** 0.1.2
**Commit/Build:** 2a01c22

The list of List of available vehicles in the New Ride menu can sometimes go outside of the window.

**Screenshots:**
![sand box - no money 2017-11-21 10-48-54](https://user-images.githubusercontent.com/28242696/33082475-e44e0236-ceaa-11e7-9419-56751acc3f75.png)
If you move the view while this bug is present you get this:
![sand box - no money 2017-11-21 10-48-58](https://user-images.githubusercontent.com/28242696/33083009-379536b6-ceac-11e7-9f86-2db6c5f512b0.png)
(The letters disappear if you move the view again)

**Comment by Gymnasiast** [comment]
I know this could happen, but I wanted to see how many problems it would cause (if any).

**Comment by Gymnasiast** [comment]
Fixed in develop.
