### ISSUE TITLE
Unable to set audio level of title music?

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#6720]
I never noticed that this was an issue before. I thought "Title screen music" was affected by the two sliders we already have.

Currently running: a98c936

**Comment by Gymnasiast** [comment]
Can confirm.

The 'sound' switch used to be a master switch, but this was changed for unknown reasons.

**Comment by Nubbie** [comment]
Discussion about change etc: https://github.com/OpenRCT2/OpenRCT2/pull/3001
