### ISSUE TITLE
Park name isn't displayed 

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#6739]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** 585fc1a (which is the commit this issue occurs firstly)

Park name isn't showed as you can see in the below screenshot.
This issue occurs at 585fc1a first, and works fine at 86ec210.

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/10726524/33281796-ce1ffd22-d3e9-11e7-988d-36a1c36de28c.png)

**Comment by janisozaur** [comment]
Ok, that's interesting. I wouldn't have expected https://github.com/OpenRCT2/OpenRCT2/commit/585fc1afce26cae4952c023d2be718843dd9d86f to change anything. I'll check what's the issue there.

**Comment by telk5093** [comment]
@janisozaur It works again at 585fc1a, sorry to bother you. But it is strange...
