### ISSUE TITLE
message: "openrct.exe - Entry Point Not Found"  (OPENRCT2 NOT WORKING)

### ISSUE THREAD

**Issue by jamtraks** [OpenRCT2/OpenRCT2#6740]
**OS:** Vista 32-bit
**Version:** Launcher Version: 0.0.6 x86 or any recent openrct2 version
**Commit/Build:** OpenRCT2 Build: 3112, OpenRCT2 Git Hash: a3be15c

I had been without internet access for weeks before today and the openrct2 version i was using during that time worked well enough that i could play, (though it did freeze once in a while before loading). Now today after my launcher has installed the latest "develop" version... i cannot open openrct2 at all, i get this message: openrct2.exe - Entry Point Not Found    (x) The procedure entry point K32GetModuleFileNameExW could not be located in the dynamic link library KERNEL32.dll

- [did not test ] Reproducible in RCT2 (vanilla)?
- [n/a ] Multiplayer?

**Steps to reproduce:**
1. press "play" button after opening launcher
2. 

**Dump file**
<none created

**Screenshots / Video:**
![openrct2 kernel error](https://user-images.githubusercontent.com/17103908/33286090-736566fe-d382-11e7-87b5-d563406a971a.jpg)

**Save game:**
n/a

**Comment by jamtraks** [comment]
HUH???

**Comment by jamtraks** [comment]
please explain

**Comment by janisozaur** [comment]
This is not an issue with OpenRCT2, but with launcher, so file this against launcher.

**Comment by jamtraks** [comment]
how do i do that?

**Comment by jamtraks** [comment]
btw i tried downloading the newest version from openrct2.org and had the same problem how is this not an openrct2 issue?

**Comment by jamtraks** [comment]
okay so i submitted the issue there it seems to have come up here

**Comment by LRFLEW** [comment]
Googling the problem I found [this page](https://answers.microsoft.com/en-us/msoffice/forum/msoffice_install-mso_other/the-procedure-entry-point/7d3b9a16-f313-4f66-ac78-e5db2941966d).

Are you specifically running Vista SP1? I don't think we officially support anything older than that.

**Comment by jamtraks** [comment]
I'm using windows vista 32-bit service pack 2 on a year2006 Toshiba laptop. The game was working on this computer when i was using an openrct2 version from about 2 months ago. I don't know what has changed since then, but the newer and current versions of openrct2 are not opening at all, and i get the message seen above.

Though... I _did_ experience many game freezes, when using the working version of openrct2 from 2 months ago... The game would often freeze at start when i pressed the "play" button on the launcher, and when this happened i would have to either close openrct2 (using control alt delete) and restart it, or wait about three minutes and the game would suddenly start on it's own.

This freeze seemed to be associated with 1 of 4 issues: 

1. Openrct2 thought i had an internet connection when i only had a _partial_ connection to "xfinity hotspot" (xfinity gives all computers connected to their network, a partial connection, so that a person can then activate full internet access with a payment to xfinity through a web browser). This tricks some programs into thinking that a computer is connected to the internet when really, it's not.

2. I opened openrct2 too soon after waking up the computer. ((I had just "woken up" my laptop (by lifting the screen and opening it) and so, the computer was not quite ready to start openrct2)).

3. My computer uses a dual-core processor (amd athlon x2 64) (32-bit processor). This seems to sometimes confuse openrct2, and i notice 2 windows opening at the start of the game as if the computer is trying to open two instances of openrct2.

4. Openrct2 was resetting it's options and settings about every third or fifth time i opened it. 
Every third or fifth... or sixth (or first or second etc...)  Time i opened openrct2, the game displayed newly added features and fixes, as if i had just updated to a newer version of openrct2 when in fact i hadn't updated at all.

- i apologize for this here "text wall" but it _is_ my best explanation of the problem.
- i really hope that this issue can be solved without me having to update my computer, or worse; having to buy a new one.
- thanks
