### ISSUE TITLE
Allow setting two directories for RCT1

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#6749]
Both the disk and Steam version of RCT1 use two separate directories for all the files:
- For the disk version, there is the had disk directory, the RCT1 CD directory and the LL CD directory. A combination of either Hard disk + LL CD or RCT1 CD + LL CD is needed to have everything (sprites + scenarios)
- For the Steam version, there is a "hard disk" directory and a "CD" directory.
- GOG does something else still.

The current approach of setting one directory is not sufficient. Unless the user copies the missing files manually to that directory, but then you could ask yourself why we even bother supporting an RCT1 path and don't store the stuff in one of our own directories.

Of course, that _is_ an alternative. Especially if we can copy files from RCT1 dirs automatically.

**Comment by IntelOrca** [comment]
How does #6173 tie in with this?

**Comment by Gymnasiast** [comment]
It seems to sort-of add the "CD" directory as a second directory, although in a less-flexible way.

**Comment by IntelOrca** [comment]
Do we need to always search both paths or do we decide based on the file we are looking for? For example do we need to look for scenarios from both places and then remove duplicates?

**Comment by Gymnasiast** [comment]
We need to look in both places. Which file is where depends on the version (disk/Steam).

**Comment by Gymnasiast** [comment]
#11418 added clear directions to copy `csg1i.dat` when setting a path. Combined with the fact that the GOG and Steam versions work as-is, I don't think this is worth pursuing further.
