### ISSUE TITLE
Check number of entries in CSG1.DAT

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#6750]
It has happened that a user accidentally set an RCT1 path to a CD or installation that only had the base game and not the expansions. This results in crashes. We should check the number of entries in CSG1.DAT and not load it if it contains too few.

**Comment by IntelOrca** [comment]
My recent changes should return `nullptr` for a g1 entry that does not exist. Checking the result of getting an entry is better and then just a warning if the RCT1 path is not LL.

**Comment by Gymnasiast** [comment]
Implemented in 2a6f2c1763b099f6f8463d19a6271c779fb59b95.
