### ISSUE TITLE
Maze destruction overflow bug is still exists

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#6755]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** 5d5d64a

Overflow bug when destruct a maze is still exists.

**Steps to reproduce:**
1. Build Maze.
2. No any construction, just close the build window.
3. Demolish the maze
4. Money overflows.

**Screenshots / Video:**
![maze bug](https://user-images.githubusercontent.com/10726524/33450213-69539f9a-d64e-11e7-9a71-d81dab836b34.gif)

**Comment by RealRexen** [comment]
Not sure if this will help but I found this https://www.reddit.com/r/rct/comments/7jyk04/2_i_tried_building_a_hedge_maze_above_a_dodgems/

**Comment by Nubbie** [comment]
https://openrct2.org/forums/topic/2765-maze-on-top-of-tree-demolish-max-negative-money/
