### ISSUE TITLE
Object Piece Missing from Scenery Window

### ISSUE THREAD

**Issue by Ziscor** [OpenRCT2/OpenRCT2#6756]
**OS:** OS X 10.9.5
**Version:** 0.1.2
**Commit/Build:** 5d5c64a

I have a park here that I've been using a wall piece in, and it seems I can't see it in the object placement scenery window anymore, even though the object is visible around the park. Using Eyedropper Tool on one of the places where the object has been placed doesn't work, the window just does the white border thing for a second, like when you open up a window.

The object is called "Wall-Castle-Light©ToonTowner" and the file name is "XXWLCL02.DAT". It should export with the save that I'll provide down below.

**Screenshots:**
The object as it appears in the Scenery Selection:
![screen shot 2017-12-01 at 1 59 33 pm](https://user-images.githubusercontent.com/18721353/33474402-6d852500-d6a0-11e7-8cfd-bd250595df69.png)
Not sure if that'll be useful, but the object can be seen on the upper-right corner building in this image, which is near one of the edges of the park, for an example (in-case the eye-dropper issue needs to be verified):
![screen shot 2017-12-01 at 2 11 48 pm](https://user-images.githubusercontent.com/18721353/33474682-ab457ed4-d6a1-11e7-8ec1-0be5d8b5805c.png)

**Save game:**
[Zaccanapoli (peepable).sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/1520886/Zaccanapoli.peepable.sv6.zip)

**Comment by Gymnasiast** [comment]
The maximum amount of objects on the 'Miscellaneous' tab is 256 (up from 128 in vanilla RCT2). I counted, and it does indeed show 256 of them.

I'll raise the maximum (again).
