### ISSUE TITLE
An assertion failed - Invalid Font index 65675

### ISSUE THREAD

**Issue by TonyLaV** [OpenRCT2/OpenRCT2#6761]
**OS:** Windows 7
**Version:** [0.1.2]
**Commit/Build:** [1f456d3)

Game crashes when clicking on select objects in debug mode.
A window appears and gives me the information 

An assertion failed - Invalid Font index 65675

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**

Activate Debug mode and click on select objects.

**Comment by SidaRadis** [comment]
I have a similar issue when I try to open the invention list window
An assertion failed - Invalid font index 65586

**Comment by saxman1089** [comment]
Same here, 65675.

**Comment by WelderGame3** [comment]
This happens whenever i open the scenario editor.
65675.

**Comment by janisozaur** [comment]
@AaronVanGeffen

**Comment by AaronVanGeffen** [comment]
Okay, that answers my question in #6638. I've had but very little to do with the sprite font, though. Perhaps @IntelOrca or @marijnvdwerf has an idea?
