### ISSUE TITLE
Crash Upon Starting Scenario Editor

### ISSUE THREAD

**Issue by WelderGame3** [OpenRCT2/OpenRCT2#6762]
**OS:** Windows 7 64 Bit
**Version:** 0.1.2
**Commit/Build:** 1f456d3

Assertion Failed - Invalid font index 65675

- [N] Reproducible in RCT2 (vanilla)?
- [N] Multiplayer?

**Steps to reproduce:**
1. Open Up Scenario Editor
2. Self Explanatory.

**Dump file**
None

**Screenshots / Video:**
![report](https://user-images.githubusercontent.com/34178229/33511366-29cf63cc-d6df-11e7-8c40-81ce224441a1.PNG)

**Save game:**
None

Please help me fix this, I want to create a scenario.

**Comment by Patrik356b** [comment]
I believe #6638  introduced this issue, in the meantime, you can go back to this version: 
https://openrct2.org/downloads/develop/516c573

I get the same error on 1f456d3 and f52544d

**Comment by WelderGame3** [comment]
Switched to stable in the launcher, it works now, I will switch back when its fixed.

**Comment by Patrik356b** [comment]
Please keep this issue open until it has been fixed officially.

**Comment by WelderGame3** [comment]
Done.

**Comment by Patrik356b** [comment]
since nobody bothered to tag the dupe...    #6761
