### ISSUE TITLE
Changelog window won't open

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#6766]
**OS:** Windows 10 and Android 7.0 (Samsung Galaxy S8+)
**Version:** 0.1.2
**Commit/Build:** 33d0fa9

If you go to the about OpenRCT2 window and try to open the Changelog-window, it doesn't open that window.

**Comment by AaronVanGeffen** [comment]
Is it even shipped in the Android build?

**Comment by mrtnptrs** [comment]
Idk, but it also won't open when using Windows 10, as I said earlier above (I tested that of course as I suspected first it was an Android-only bug, but it isn't.)

**Comment by AaronVanGeffen** [comment]
Hmm. It used to open for me if it were in a `doc` subdirectory in the same directory as the binary. That is no longer the case. I'm guessing this regression relates to the recent changes to the platform code, then.

**Comment by AaronVanGeffen** [comment]
As far as I can tell, Windows and macOS builds ship with the changelog file in the place I would expect them to.

Is this still an issue on Windows for you, @mrtnptrs?

**Comment by mrtnptrs** [comment]
Yes, the automated Windows build ships with the changelog file (macOS not tested). The problem is that is is in the main directory (with the executable); OpenRCT2 seems to only be able to find it when it is in the data-folder. As soon as you place the changelog.txt file in the data folder, the changelog screen works again. So, two options to fix this: making OpenRCT2 recognize the changelog.txt file from the main directory or place the changelog.txt file in the data-directory.

**Comment by AaronVanGeffen** [comment]
It certainly used to be able to find the file in the same directory as the running executable. Sounds like a regression.

**Comment by mrtnptrs** [comment]
> It certainly used to be able to find the file in the same directory as the running executable. Sounds like a regression.

Yeah, I think I can fix it.

**Comment by mrtnptrs** [comment]
I thought editing this line:
https://github.com/OpenRCT2/OpenRCT2/blob/c8f822ea70ba41deefdef2767235d7ecdd744281/src/openrct2/PlatformEnvironment.cpp#L95
to 'return DIRBASE::OPENRCT2;' would fix it, but strangely it doesn't. It still only recognizes the changelog.txt file only when it is in the data-folder.... Why?

**Comment by ZehMatt** [comment]
Maybe you could log the file path returned to see if its actually correct? Or simply build the whole thing with the Debug configuration and step over the code to see how it builds the path.
