### ISSUE TITLE
Software (hardware display) + Scaling + fullscreen results in a black screen after alt-tabbing back into the game

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#6767]
**OS:** Windows 10 x64
**Version:** 0.1.2
**Commit/Build:** 33d0fa9

**Steps to reproduce:**
1. Set the renderengine to Software (hardware display) (Software and OpenGL work fine)
2. Set to fullscreen (not fullscreen (borderless)!)
3. Use any other scale factor than 1.0.
4. Alt-Tab out of the game (Screen has already become black, see the preview in the task bar)
5. Alt-Tab in the game.
6. The screen is black, you hear all the normal sounds. So it seems like the game runs fine, except it produces no visual output and instead serves me a black screen.

Edit: When it shows a black screen it still accepts input, as I can still then click in the bottom right corner to close OpenRCT2 the normal way.

**Comment by flipflop97** [comment]
This seems to specifically happen when Smooth Nearest Neighbor scaling is used in combination with Software (hardware display) rendering on Windows, I can't reproduce it on Linux or with other settings.

**Comment by Gymnasiast** [comment]
I also noticed this on a friend's computer, but that didn't use window scaling. Are you sure window scaling is a "requirement" for this bug?

**Comment by Broxzier** [comment]
The same thing was just confirmed by All_Heil_Lord_Pepe on Discord. Their scaling was also set to 1.0.

**Comment by Richard-L** [comment]
Same here but with scaling set to x1.25. 

> OpenRCT2, v0.2.4-767-ge66a6754f (e66a675 on develop) provided by GitHub
> Windows (x86-64)

Issue is fixed when using "borderless".

**Comment by chaitanyathengdi** [comment]
I've noticed it when using 2.00 scaling as well, all else being equal.

**Comment by janisozaur** [comment]
Should get solved with https://github.com/OpenRCT2/OpenRCT2/pull/16070
