### ISSUE TITLE
Feature : Remember cheats when restart game

### ISSUE THREAD

**Issue by TonyLaV** [OpenRCT2/OpenRCT2#6769]
Is it possible to save the cheat config? I mean the bonus features like building in pause mode.
It would be a nice feature , because i often build in pause mode and always forget to activate the cheat.

**Comment by duncanspumpkin** [comment]
This has been discussed many times. When we make our new save format we may consider doing this

**Comment by Patrik356b** [comment]
@TonyLaV You could maybe write an [autohotkey](https://autohotkey.com/) script to do this for you as an alternative solution (would require finding the right places to click, but is possible to do)
