### ISSUE TITLE
List of rides for advertising campaign is not long enough

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#6775]
**OS:** Windows 7
**Version:** 0.1.2
**Commit/Build:** 837b177

Screenshot:
![screenshotfactory capers 2017-12-03 17-55-41](https://user-images.githubusercontent.com/28242696/33531768-c56bec8e-d85f-11e7-93cb-4d6891614804.png)

**Comment by Patrik356b** [comment]
Perhaps it's time to turn the drop down box into a window?
@Gymnasiast @janisozaur @IntelOrca

**Comment by Gymnasiast** [comment]
I changed this from 40 to 128, but I noticed that I missed an occurrence. I'll fix it.

**Comment by Gymnasiast** [comment]
Fixed in b0c784e/
