### ISSUE TITLE
Options - Hardware window has a buggy string

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#6782]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** b9a6382

A string in the options window is buggy
Seems to be linked with PR #6764 (837b177) as commit 107461b _(the one before)_ works fine

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open up the options window
 

**Screenshots / Video:**

![options window](https://user-images.githubusercontent.com/17282384/33566089-4528860c-d91f-11e7-9339-436d5f140020.png)

**Comment by AaronVanGeffen** [comment]
That seems like it may have been caused by #6764, yes. Wonder why it looked fine for me. Will investigate later.

**Comment by AaronVanGeffen** [comment]
Found the problem. As of #6764, the widget for the Steam overlay check has a height of 1px instead of 11px…
