### ISSUE TITLE
Building mazes performs clearance checks when disabled

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#6801]
**OS:** Windows 10
**Version:** 0.1.2-develop
**Commit/Build:** 40cea0e

Clearance is always checked when building mazes, even when clearance checks have been disabled.

**Steps to reproduce:**
1. Disable clearance checks from the golden shovel dropdown menu
2. Try to build through anything with your maze

**Comment by Gymnasiast** [comment]
Not surprised. Mazes have about as much in common with other rides as they have with balloons.
