### ISSUE TITLE
Symbolic links to directories are not descended by FileScanner

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#6803]
**OS:** Linux
**Version:** 0.1.2
**Commit/Build:** 40cea0e7e7de6c109214fbecf6507d303ba3f3ce

If you have symbolic link directories in your `object`, `track` or `scenario` directory, they are not searched when indexing files.

**Comment by ipatix** [comment]
Isn't searching symbolic links usually a dangerous thing incase you run into endless loops (for example by going up a directory and finding the same symbolic link again)?

**Comment by Patrik356b** [comment]
@ipatix such links or shortcuts should be resolved by the OS, but I haven't investigated this.

I know shortcuts are resolved on windows though.

**Comment by IntelOrca** [comment]
I have already done the fix in another branch, it just needs committing to `develop`.

**Comment by ipatix** [comment]
@Patrik356b I just tried to created a symlink inside a direrectory to itself on Linux and I can use opendir/readdir and crawl the symlink as long as I want. Which means a program might fall into this.

But still, is there a commonly used algorithm which is used accross for all major operating systems to decide whether a symlink loops or not? It certainly doesn't work on Linux and a quick shot at google told me that it's up to the application to deal with that (like 'find').
