### ISSUE TITLE
Multiplayer Permissions are not visible / no checks visible

### ISSUE THREAD

**Issue by TonyLaV** [OpenRCT2/OpenRCT2#6804]
**OS:** [e.g. Windows 7]
**Version:** [e.g. 0.1.2]
**Commit/Build:** [40cea0e]

The permissions for every group are not visble for me. It doesnt matter which group, no group has any permission , even host or admin has no permission.

The permissions are working , **only the function to build multiple trees at same time is not working for me**. It should work because i have the permission for it.

- [ ] Reproducible in RCT2 (vanilla)?
- [ X ] Multiplayer?

**Screenshots / Video:**

![sunny swamps remastered 2017-12-09 16-43-47](https://user-images.githubusercontent.com/33175850/33797044-f9e705b6-dd00-11e7-8343-85c0f01228b9.png)

**Comment by janisozaur** [comment]
can you post `groups.json` and provide the data in issue template?

**Comment by TonyLaV** [comment]
{
    "default_group": 1,
    "groups": [
        {
            "id": 0,
            "name": "Admin",
            "permissions": [
                "PERMISSION_CHAT",
                "PERMISSION_TERRAFORM",
                "PERMISSION_SET_WATER_LEVEL",
                "PERMISSION_TOGGLE_PAUSE",
                "PERMISSION_CREATE_RIDE",
                "PERMISSION_REMOVE_RIDE",
                "PERMISSION_BUILD_RIDE",
                "PERMISSION_RIDE_PROPERTIES",
                "PERMISSION_SCENERY",
                "PERMISSION_PATH",
                "PERMISSION_CLEAR_LANDSCAPE",
                "PERMISSION_GUEST",
                "PERMISSION_STAFF",
                "PERMISSION_PARK_PROPERTIES",
                "PERMISSION_PARK_FUNDING",
                "PERMISSION_KICK_PLAYER",
                "PERMISSION_MODIFY_GROUPS",
                "PERMISSION_SET_PLAYER_GROUP",
                "PERMISSION_CHEAT",
                "PERMISSION_TOGGLE_SCENERY_CLUSTER",
                "PERMISSION_PASSWORDLESS_LOGIN",
                "PERMISSION_MODIFY_TILE",
                "PERMISSION_EDIT_SCENARIO_OPTIONS"
            ]
        },
        {
            "id": 1,
            "name": "Spectator",
            "permissions": [
                "PERMISSION_CHAT"
            ]
        },
        {
            "id": 2,
            "name": "User",
            "permissions": [
                "PERMISSION_CHAT",
                "PERMISSION_TERRAFORM",
                "PERMISSION_SET_WATER_LEVEL",
                "PERMISSION_TOGGLE_PAUSE",
                "PERMISSION_CREATE_RIDE",
                "PERMISSION_REMOVE_RIDE",
                "PERMISSION_BUILD_RIDE",
                "PERMISSION_RIDE_PROPERTIES",
                "PERMISSION_SCENERY",
                "PERMISSION_PATH",
                "PERMISSION_CLEAR_LANDSCAPE",
                "PERMISSION_GUEST",
                "PERMISSION_STAFF",
                "PERMISSION_PARK_PROPERTIES",
                "PERMISSION_PARK_FUNDING",
                "PERMISSION_TOGGLE_SCENERY_CLUSTER"
            ]
        },
        {
            "id": 3,
            "name": "Probezeit",
            "permissions": [
                "PERMISSION_CREATE_RIDE",
                "PERMISSION_BUILD_RIDE",
                "PERMISSION_RIDE_PROPERTIES",
                "PERMISSION_SCENERY",
                "PERMISSION_PATH"
            ]
        }
    ]
}

**Comment by janisozaur** [comment]
It doesn't look like the one from your screenshot at all, there are no groups named `Untouchables` or `I am the BIG` in this file.

**Comment by TonyLaV** [comment]
This is not my server , i dont have a server.

**Comment by TonyLaV** [comment]
Please help me. 

When i use release version everything works fine.
But im only able to play multiplayer with develop version.

I still cant change any permissions. There are no checks at all.

**Comment by ShalokShalom** [comment]
Did you delete your previous comment and with that the file? If so, can you provide the correct one?

**Comment by TonyLaV** [comment]
I cant provide a correct one, because grups.json only provides the the groups of my own server. But in my own server anything is working fine. When im playing on another server , no checks are visible and im not able to build multiple trees . But i have the permission for it.
