### ISSUE TITLE
Inventarisation of `interface/window.c` uses.

### ISSUE THREAD

**Issue by marijnvdwerf** [OpenRCT2/OpenRCT2#6808]
##### actions/GameActionCompat.cpp
  - window_close
  - window_close_by_class
  - window_close_by_number
  - window_find_by_class
  - window_find_by_number
  - window_invalidate_by_class
  - window_invalidate_by_number

##### actions/GameActionRegistration.cpp
  - window_close
  - window_close_by_class
  - window_close_by_number
  - window_find_by_class
  - window_find_by_number
  - window_invalidate_by_class
  - window_invalidate_by_number

##### audio/Audio.cpp
  - window_get_previous_viewport

##### Cheats.cpp
  - window_invalidate_by_class

##### cmdline/ConvertCommand.cpp
  - window_close_by_class

##### Context.cpp
  - window_close_all

##### drawing/lightfx.c
  - window_get_main

##### drawing/Rain.cpp
  - gWindowNextSlot
  - g_window_list

##### drawing/string.c
  - gCurrentWindowColours

##### drawing/X8DrawingEngine.cpp
  - window_draw_all
  - window_reset_visibilities
  - window_update_all
  - window_update_all_viewports

##### Editor.cpp
  - gWindowUpdateTicks
  - tool_cancel
  - window_close_all
  - window_find_by_class
  - window_get_main
  - window_invalidate
  - window_invalidate_by_class
  - window_set_location

##### Game.cpp
  - gWindowMapFlashingFlags
  - gWindowUpdateTicks
  - tool_cancel
  - window_close_by_class
  - window_dispatch_update_all
  - window_get_main
  - window_invalidate
  - window_invalidate_by_class
  - window_resize_gui
  - window_update_all

##### interface/console.c
  - gWindowUpdateTicks
  - window_close_all
  - window_get_main
  - window_set_location
  - window_set_window_limit

##### interface/Screenshot.cpp
  - window_get_main

##### interface/Theme.cpp
  - gWindowNextSlot
  - g_window_list

##### interface/viewport.c
  - gWindowNextSlot
  - g_window_list
  - textinput_cancel
  - window_draw_all
  - window_event_resize_call
  - window_find_from_point
  - window_get_main
  - window_init_all
  - window_invalidate
  - window_is_visible

##### interface/viewport_interaction.c
  - window_find_by_class
  - window_find_from_point

##### interface/widget.c
  - gCurrentTextBox
  - gTextBoxFrameNo
  - gTextBoxInput
  - gTextInput
  - window_event_scroll_paint_call
  - window_get_scroll_data_index

##### management/Award.cpp
  - window_invalidate_by_class

##### management/Finance.cpp
  - gToolbarDirtyFlags
  - window_invalidate_by_class

##### management/Marketing.cpp
  - window_close_by_class
  - window_invalidate_by_class

##### management/NewsItem.cpp
  - tool_set
  - window_bring_to_front_by_class
  - window_event_mouse_down_call
  - window_find_by_class
  - window_invalidate
  - window_invalidate_by_class

##### management/Research.cpp
  - window_invalidate_by_class

##### network/Network.cpp
  - window_invalidate_by_class
  - window_invalidate_by_number

##### network/NetworkPlayer.cpp
  - window_invalidate_by_number

##### object/ObjectManager.cpp
  - window_close_by_class

##### peep/Peep.cpp
  - gToolbarDirtyFlags
  - widget_invalidate
  - window_close_by_number
  - window_event_invalidate_call
  - window_find_by_number
  - window_invalidate
  - window_invalidate_by_class
  - window_invalidate_by_number

##### peep/Staff.cpp
  - window_close_by_class
  - window_invalidate_by_class
  - window_invalidate_by_number

##### rct2/S6Exporter.cpp
  - window_close_construction_windows

##### ride/ride.c
  - tool_cancel
  - tool_set
  - window_close_by_number
  - window_close_construction_windows
  - window_event_mouse_up_call
  - window_event_resize_call
  - window_find_by_class
  - window_find_by_number
  - window_get_main
  - window_invalidate
  - window_invalidate_by_class
  - window_invalidate_by_number
  - window_scroll_to_location
  - window_update_viewport_ride_music

##### ride/ride_ratings.c
  - window_invalidate_by_number

##### ride/track_design_save.c
  - window_close_construction_windows

##### ride/Vehicle.cpp
  - gToolbarDirtyFlags
  - gWindowAudioExclusive
  - gWindowNextSlot
  - g_window_list
  - window_find_by_number
  - window_invalidate
  - window_invalidate_by_number

##### scenario/scenario.c
  - gToolbarDirtyFlags
  - window_close_all_except_flags
  - window_close_by_class

##### windows/_legacy.c
  - tool_cancel
  - tool_set
  - window_close_by_class
  - window_event_mouse_up_call
  - window_find_by_class
  - window_find_by_number
  - window_invalidate

##### world/map.c
  - window_bring_to_front_by_number
  - window_close_by_number
  - window_find_by_class
  - window_invalidate

##### world/park.c
  - gToolbarDirtyFlags
  - window_invalidate_by_class

**Comment by marijnvdwerf** [comment]
- [ ] _window_dispatch_update_all (2)
- [ ] _gToolbarDirtyFlags (6)
- [ ] _gWindowMapFlashingFlags (1)
- [ ] _gWindowUpdateTicks (3)
- [ ] _gCurrentWindowColours (1)
- [ ] _gTextInput (1)
- [ ] _gWindowAudioExclusive (1)
- [ ] _window_update_all_viewports (1)
- [ ] _window_is_visible (1)
- [ ] _window_update_all (2)
- [ ] _window_invalidate (12)
- [ ] _window_set_window_limit (1)
- [ ] _window_close (3)
- [ ] _window_find_by_number (7)
- [ ] _window_close_by_class (10)
- [ ] _window_close_by_number (5)
- [ ] _window_find_by_class (8)
- [ ] _window_close_all (3)
- [ ] _window_find_from_point (1)
- [ ] _window_event_invalidate_call (1)
- [ ] _window_invalidate_by_class (16)
- [ ] _window_invalidate_by_number (9)
- [ ] _window_invalidate_all (1)
- [ ] _widget_invalidate (1)
- [ ] _window_get_scroll_data_index (1)
- [ ] _window_bring_to_front_by_class (1)
- [ ] _window_bring_to_front_by_number (2)
- [ ] _window_get_main (9)
- [ ] _window_scroll_to_location (1)
- [ ] _window_set_location (3)
- [ ] _window_rotate_camera (1)
- [ ] _window_zoom_set (1)
- [ ] _window_draw (1)
- [ ] _window_event_resize_call (2)
- [ ] _tool_set (3)
- [ ] _tool_cancel (4)
- [ ] _window_event_mouse_up_call (2)
- [ ] _window_event_mouse_down_call (1)
- [ ] _window_event_scroll_paint_call (1)
- [ ] _window_resize_gui (2)
- [ ] _window_close_construction_windows (3)
- [ ] _window_update_viewport_ride_music (1)
- [ ] _textinput_cancel (1)
- [ ] _gCurrentTextBox (1)
- [ ] _g_window_list (8)
- [ ] _gWindowNextSlot (8)
- [ ] _gTextBoxInput (1)
- [ ] _gTextBoxFrameNo (1)

**Comment by Gymnasiast** [comment]
Since this ticket is almost two years old and the relevant code has seen many changes, I'll close it, since it's likely outdated.
