### ISSUE TITLE
Track Designer not showing any rides on Linux

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/OpenRCT2#6810]
**OS:** Arch Linux
**Version:** 0.1.2
**Commit/Build:** 8951d1b3329d26fd31b3a3218f06082937ee6aa1

On Linux, neither the Track Designer nor the Track Design Manager is showing any rides for me. It seems to be working as expected on macOS.

Rebuilding caches reveals 207 files in the track design index, however, and I am able to build pre-designed tracks just fine.

I have compiled v0.1.1 as well, with the same result, so it does not appear to be a recent regression.

![screenshot_20171210_220746](https://user-images.githubusercontent.com/604665/33809399-91b839d2-ddf6-11e7-8932-726f568d7741.png)

**Comment by Gymnasiast** [comment]
The track designs manager is really the ugly step-bastard child of the family in terms of attention and love it gets. It also selects based on vehicle, rather than on ride group, like the track list does.

**Comment by AaronVanGeffen** [comment]
For whatever reason, I can no longer reproduce this. I'm closing this assuming this was a problem on my end.
