### ISSUE TITLE
Underwater Patrol Area Difficult to Work With

### ISSUE THREAD

**Issue by pizza2004** [OpenRCT2/OpenRCT2#682]
I know this isn't necessarily a priority, but I've been playing RCT lately and in order to maximize my space I've built out over water with paths and coasters and when trying to set patrol areas for my staff I've run into a couple of issues:

1) It's impossible to properly distinguish between the patrol area set for your currently selected staff member and the gray version representing what's been set before.

2) It's very difficult to tell whether you've set the patrol area in a way that encompasses whatever path is up on supports over the water.

My suggestion is that you just show the patrol area on top of the water instead of under it, and make it so when you click on the water it selects the square you clicked on, instead of whatever land is visible through the one you clicked on.  I feel like this change could make setting patrol areas for staff much much easier.  I honestly don't mind other ways of handling the problem either, I just think it's something that should be addressed.

**Comment by RollingStar** [comment]
Would another color of patrol area work better over water? If the water is blue, for example, maybe the patrol area marker could be red when placed over water, to provide better contrast. But then it may create user confusion to have two colors for the same thing.

Note that there are 5 water color options.

**Comment by IntelOrca** [comment]
@RollingStar I think the issue is from an input point of view. It would be easier to click the surface of the water and have the surface tile be the tile you clicked on for the patrol area where as currently you have to click the land tile the water surface tile is over which is not straight forward particular if the water is deep.

**Comment by pizza2004** [comment]
Implemented by #10830.
