### ISSUE TITLE
 The far-edge vertical terrain sides get filled with invalid data

### ISSUE THREAD

**Issue by ExecThTs** [OpenRCT2/OpenRCT2#6821]
**OS:** Windows, 17.09
**Version:** v0.1.2-dev
**Commit/Build:** cc27bee
**Screen mode:** Fullscreen, borderless
**Drawing engine:** Software (hw d.)
Day/Night cycle off.

The far-edge vertical terrain sides get filled in from the framebuffer/vram/anything.

**Steps to reproduce:** (No exact at the moment)
1. Create a new park with a scenario
2. Navigate the camera to an edge of the map

**Scenario file**
[171212-greatbig.sc6.zip](https://github.com/OpenRCT2/OpenRCT2/files/1556859/171212-greatbig.sc6.zip)

**Screenshots / Video:**
https://imgur.com/a/LvZwQ

**Comment by Patrik356b** [comment]
Just to clarify: Windows 10, version 1709

**Comment by duncanspumpkin** [comment]
https://github.com/OpenRCT2/OpenRCT2/pull/6735 possible cause

**Comment by Felipedzs** [comment]
I have the exact same bug.
It started for me on the build 8772d74.
The build 5fa2922 (The one before it) seems fine to me.
I'm using Windows 10, version 1709

**Comment by duncanspumpkin** [comment]
https://github.com/OpenRCT2/OpenRCT2/pull/6819 okay then it's probably caused by this
