### ISSUE TITLE
Crash on Single Player

### ISSUE THREAD

**Issue by GrandpaDVA** [OpenRCT2/OpenRCT2#6827]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.1.1]
**Commit/Build:** [e.g. 426e106]

Game starts ok, opens single player saved file, then get crash notification. Happens on all saved game files.

- [ ] Reproducible in RCT2 (vanilla)? 
![orctcrash](https://user-images.githubusercontent.com/34551224/34007645-8774005a-e0d0-11e7-9b01-cd605f61c001.jpg)

**Screenshots / Video:**

**Save game:**

UPDATE: I uninstalled ORCT and reinstalled version "eed00ea" but not the launcher.  I was then able to open and use all saved files.

**Comment by Gymnasiast** [comment]
You might have been using an old version before you updated. Since no problems persist, I'll consider this solved. Let us know if you still get crashes.
