### ISSUE TITLE
Rebuilding toilets and food-attractions doesn´t work in sv4

### ISSUE THREAD

**Issue by o-fighter** [OpenRCT2/OpenRCT2#6833]
**Windows 10 Home German**
Build: 4aff132

After open a sv4 Safegame, the food attractions and toilets are gone.
Trying to build a new one at same place won´t work. Also raising land at this positions doesn´t work.
It says undefinedString.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Take a RCT1 sv4 Savegame with attractions like toilet or for exemple Burgersale or Lemonade.
2. Open it in OpenRCT2 and the food-attractions and toilets are gone.
3. Try to build a new one at same place, it won´t work. Also raise land at this positions won´´t work.

or

1. Go to the place in my safegame shown in screenshot
2. try to build a new foodsale, attraction or raise land at the position shown in screenshot

**Screenshots / Video:**
![error 2](https://user-images.githubusercontent.com/34587780/34070937-4b779ef0-e26e-11e7-8089-222fff6557f9.png)
![error](https://user-images.githubusercontent.com/34587780/34070938-4b902e98-e26e-11e7-8a78-7246b3c06800.png)

**Save game:**
[Leafy Lake RCT2.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/1564794/Leafy.Lake.RCT2.sv6.txt)

**Comment by Gymnasiast** [comment]
Could you also upload the original SV4 file?

**Comment by o-fighter** [comment]
[Leafy Lake2 neu.SV4.txt](https://github.com/OpenRCT2/OpenRCT2/files/1565845/Leafy.Lake2.neu.SV4.txt)

**Comment by rwjuk** [comment]
The errors below are logged to the console. I also noted that no rides are available for construction after loading the save - I fear the SV4 is corrupt in some way.

`ERROR[...\src\openrct2\ride\ride.c:231 (get_ride_entry)]: invalid index 255 for ride type
ERROR[...\src\openrct2\ride\shops\shop.cpp:43 (shop_paint_setup)]: Error drawing shop, rideEntry or firstVehicleEntry is NULL.`

**Comment by Gymnasiast** [comment]
> I also noted that no rides are available for construction after loading the save

That could also be an OpenRCT2 error. Needs testing in RCT1LL.

**Comment by Patrik356b** [comment]
I tried to load the file in RCT Deluxe (GoG version) and this is what i get:
![2017-12-27_23-29-40](https://user-images.githubusercontent.com/2000703/34395097-19675c18-eb5e-11e7-905b-f34961ce531c.png)

**Comment by rwjuk** [comment]
Confirmed with my copy of RCT1 - same error as @Patrik356b.

**Comment by Gymnasiast** [comment]
This could be simply cheat detection - have you got the Drexler patch installed?

**Comment by Patrik356b** [comment]
Unfortantly, there are a bunch of versions that the Drexler patch does not support,

However, I did dig up my RCT1 box and it seems Drexler worked on that as i was able to load this [workbench](https://www.nedesigns.com/park/2150/rct1-guide-aceworkbench-rctll-v12-126x126/).

It can't load the savegame from OP though. (same error message)

**Comment by Gymnasiast** [comment]
While RCT1 indeed fails, there are still bugs in our implementation as well. More precisely, it fails to add rides from the map that have no vehicles in RCT1 - which include all shops. Normally, research would take care of that, but that could easily be corrupted (not to mention that we muck it up as well, probably).

This is how it looks with my fixes:

![happypark 2017-12-31 18-37-27](https://user-images.githubusercontent.com/1478678/34463370-f6e53e72-ee59-11e7-9ff7-c9418aec25f3.png)
