### ISSUE TITLE
Multiplayer Scenery Cluster Permission

### ISSUE THREAD

**Issue by RoyTheDragon** [OpenRCT2/OpenRCT2#6836]
**OS:** Windows 7
**Version:** 1.2 (network -22
**Commit/Build:** Recent (on the OpenRCT2.org webpage.)

- [x] Multiplayer?
--
When i was about to add trees to my coaster in multiplayer, i noticed (even as an admin) that I cannot enable the cluster feature.
is there something going on here?

**Screenshots / Video:**
https://cdn.discordapp.com/attachments/386026660991991818/391786414381203457/unknown.png

**Comment by AaronVanGeffen** [comment]
#7028 is a duplicate of this issue. I'll leave the other one open, as it contains more info.
