### ISSUE TITLE
Inset colour not correctly applied

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/OpenRCT2#6840]
**OS:** Arch Linux, macOS
**Version:** 0.1.2
**Commit/Build:** 3d7d7bee71096f4b96f97a34270031e556433a75

When using certain TTF fonts, the inset effect isn't properly applied to the disabled 'Display Resolution' label. This is just using the usual `COLOUR_FLAG_INSET`, which seems to be applied properly in other places — including when Traditional Chinese or Japanese characters are used.

The problem does not happen with Simplified Chinese, Korean, or the sprite font. Really puzzling.

Japanese:
![screenshot_20171217_215212](https://user-images.githubusercontent.com/604665/34083783-450b603e-e376-11e7-8790-9e8bb549d7ee.png) 

Simplified Chinese:
![screenshot_20171217_220840](https://user-images.githubusercontent.com/604665/34083834-df3fe260-e376-11e7-8247-90349a05077f.png)

Sprite font:
![screenshot_20171217_215227](https://user-images.githubusercontent.com/604665/34083784-4527f00a-e376-11e7-8d73-f09b93fe65e7.png)

**Comment by marijnvdwerf** [comment]
Does this happen on all background colours?

**Comment by AaronVanGeffen** [comment]
Ah, I think I see where you're going with this… Good question! I just checked with a bunch of other colours, and no, it seems to be happening to most of them.

![screenshot_20171224_001438](https://user-images.githubusercontent.com/604665/34323226-73e9172a-e83f-11e7-963f-e69ca3c6f2a2.png)

**Comment by AaronVanGeffen** [comment]
Fix:
```diff
-STR_2360    :{WINDOW_COLOUR_2}ウィンドウ解像度:
+STR_2360    :ウィンドウ解像度:
```
