### ISSUE TITLE
Re-enable Ubuntu nightly builds

### ISSUE THREAD

**Issue by tintou** [OpenRCT2/OpenRCT2#6842]
According to [this bug](https://bugs.launchpad.net/ubuntu/+source/bzr-git/+bug/1084403), it's now possible to have git-to-git imports in Launchpad so it makes everything easier.

**Comment by janisozaur** [comment]
I'm not sure if this is catalogued somewhere already; the issues with reviving the launchpad jobs now:

* verifying all our debian control files work, especially libpng version
* launchpad builders don't have access to the Internet, so they need some other way of embedding title sequences, probably via `nest`

another minor issue that could be addressed would be to stop using `__DATE__` and `__TIME__`.

**Comment by janisozaur** [comment]
More discussion here: https://github.com/OpenRCT2/OpenRCT2/issues/5139

**Comment by janisozaur** [comment]
See https://github.com/OpenRCT2/OpenRCT2/issues/5139#issuecomment-366255761
