### ISSUE TITLE
Logo artifacts when changing scale

### ISSUE THREAD

**Issue by flipflop97** [OpenRCT2/OpenRCT2#6845]
**OS:** both Windows 10 & Arch Linux
**Version:** 0.1.2
**Commit/Build:** aa23370

When on the title screen, changing the scaling factor causes artifacts in the lop-left corner logo. It seems like this area is improperly invalidated.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Go to title screen and open settings
2. Change the scaling factor

**Comment by Nubbie** [comment]
![menolikescaleithuwtie](https://user-images.githubusercontent.com/17282384/34165619-12daf170-e4dd-11e7-88e1-7ab86ffe6551.png)
