### ISSUE TITLE
Zoomed out overview windows cause lots of lag

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#6846]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** aa23370

Some overview windows are very zoomed out and show a lot more than just the ride when the ride is small. The game has trouble rendering stuff in the overview windows, which causes a lot of lag. In the image below I already have a modest amount of lag with just a couple of windows opened. In larger parks, this can make the game unplayable with a bunch of windows open. This didn't happen in vanilla because the windows were way more zoomed in.
![forest frontiers 2017-12-18 19-31-27](https://user-images.githubusercontent.com/25930360/34121938-0bbeda94-e42b-11e7-8ea2-97317851da40.png)

**Comment by IntelOrca** [comment]
The algorithm for rides should be tweaked, it zooms out too much even for small flat rides like spiral slide.

**Comment by AaronVanGeffen** [comment]
This doesn't seem to be completely resolved yet… Shops, which use the same window, are still zoomed out all the way.

![screenshot_20180103_135652](https://user-images.githubusercontent.com/604665/34521429-fd0f9424-f08d-11e7-88b2-34c276966bd2.png)

**Comment by rwjuk** [comment]
@AaronVanGeffen I think for shops we can sensibly override that algorithm and fix it to `0`

**Comment by AaronVanGeffen** [comment]
A quick and dirty patch to work around the issue:
```diff
-    // Each farther zoom level shows twice as many tiles (log)
-    // Appropriate zoom is lowered by one to fill the entire view with the ride
-    // Value clamped to a minimum of 0 to prevent underflow
-    sint32 zoom = Math::Max((sint32)ceil(log(size / 80)) - 1, 0);
-    view->zoom = Math::Clamp<uint8>(0, zoom, 3);
+    if (size >= 80)
+    {
+        // Each farther zoom level shows twice as many tiles (log)
+        // Appropriate zoom is lowered by one to fill the entire view with the ride
+        view->zoom = Math::Max((sint32)ceil(log(size / 80)) - 1, 0);
+    }
+    else
+    {
+        view->zoom = 0;
+    }
```

This seems to have other disadvantages though, with respect to centring of rides in the viewport…

**Comment by AaronVanGeffen** [comment]
The issue should be addressed by https://github.com/OpenRCT2/OpenRCT2/pull/6929
