### ISSUE TITLE
Can't build in multiplayer

### ISSUE THREAD

**Issue by Handyman13** [OpenRCT2/OpenRCT2#6852]
**OS:** [Windows 10]
**Version:** [0.1.2]
**Commit/Build:** [12a3550]

So when I join a server that im usually on, I try to build for example an ice cream store but all I get is a small red rectangle with no text []. I've tried exiting openrct2, reconnecting to my wifi but when I join the server again and click on something in the menu where you choose what attraction to build, it happens again. a red narrow rectangle with no text. Why does this happen? I'm promoted to access, which means I can build rides and change landscaped and change cheats. Help! (The server is Mozar FFA but it's not important).

Not reproducible in RCT2 (vanilla)
Only works in multiplayer

1. Join a server and get a rank that lets you build.
2. Try to build.

https://i.imgur.com/yURgKQt.jpg

**Comment by mozar99** [comment]
when the ride cap is reached the game no longer informs the user of the ride limit.
