### ISSUE TITLE
Corruption in RCT2 scenario names when using Japanese

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/OpenRCT2#6855]
**OS:** Arch Linux, macOS
**Version:** 0.1.2
**Commit/Build:** 4678829e03e17e561547059547851a26d55862e0

Building the scenario index when the Japanese language pack is active appears to result in some corruption. English appears to be unaffected.

As the index is being built, string truncation messages containing garbage appear in the console:

```
Building scenario index (148 items)
WARNING[../src/openrct2/util/util.c:354 (safe_strcpy)]: Truncating string "芠苈芽芾芯苌荖荢荎荘荴莉荢荏荘腅荸莋荍腛苰" to 64 bytes.
WARNING[../src/openrct2/util/util.c:354 (safe_strcpy)]: Truncating string "芠苈芽芾芯苌荖荢荎荘荴莉荢荏荘腅荏莌腛荧荁" to 64 bytes.
WARNING[../src/openrct2/util/util.c:354 (safe_strcpy)]: Truncating string "芠苈芽芾芯苌荖荢荎荘荴莉荢荏荘腅草莉莓荟苰" to 64 bytes.
WARNING[../src/openrct2/util/util.c:354 (safe_strcpy)]: Truncating string "芠苈芽芾芯苌荖荢荎荘荴莉荢荏荘腅荽荗荢荎荽" to 64 bytes.
WARNING[../src/openrct2/util/util.c:354 (safe_strcpy)]: Truncating string "芠苈芽芾芯苌荖荢荎荘荴莉荢荏荘腅草腛药腛荥" to 64 bytes.
```

Bisecting reveals this to be a regression as a result of 2b2e617086576ae515a44685500957c846bf54c7.

**Steps to reproduce:**
1. Switch to Japanese language pack
2. Delete scenario.idx
3. Start the game
4. Look at any tab containing RCT2 scenarios.

**Screenshots / Video:**
![screenshot_20171221_200712](https://user-images.githubusercontent.com/604665/34270964-8fad2e80-e68a-11e7-8bde-c134aaee2d42.png)

**Comment by AaronVanGeffen** [comment]
Looking at the changes introduced in 2b2e617086576ae515a44685500957c846bf54c7, I've come up with the following hotfix, which seems to fix the issue:

```diff
diff --git a/src/openrct2/object/StringTable.cpp b/src/openrct2/object/StringTable.cpp
index d1fc9f14d..8e83b4de5 100644
--- a/src/openrct2/object/StringTable.cpp
+++ b/src/openrct2/object/StringTable.cpp
@@ -120,11 +120,16 @@ void StringTable::Sort()
                 return String::Compare(a.Text, b.Text, true) < 0;
             }
 
-            if (a.LanguageId == gCurrentLanguage)
+            uint8 languageId =
+                (gCurrentLanguage <= RCT2_LANGUAGE_ID_PORTUGUESE) ?
+                RCT2ToOpenRCT2LanguageId[gCurrentLanguage] :
+                LANGUAGE_UNDEFINED;
+
+            if (a.LanguageId == languageId)
             {
                 return true;
             }
-            if (b.LanguageId == gCurrentLanguage)
+            if (b.LanguageId == languageId)
             {
                 return false;
             }
```

There is probably a better way, so I'm not PR'ing anything quite yet.

**Comment by Gymnasiast** [comment]
`gCurrentLanguage` contains the OpenRCT2 language id (or should do), not the RCT2 one. Not sure why your diff appears to work (haven't tried it myself).

**Comment by AaronVanGeffen** [comment]
You're right, all that effectively does is hide the bug. I have a better hypothesis now. 

`RCT2ToOpenRCT2LanguageId` marks language 9 as Japanese, and `rct2_language_is_multibyte_charset` (called by `rct2_language_string_to_utf8`) in turn marks it as using a multibyte charset.

However, `convert_multibyte_charset` and specifically `convert_specific_language_character_to_unicode` do not handle conversion for the Japanese encoding yet, and is instead just returning the code point directly.

I think it's likely Shift JIS is used? Do you remember what you ended up using when you extracted the object data? Either way, we should probably implement a conversion function.
