### ISSUE TITLE
Sound problem and crashing

### ISSUE THREAD

**Issue by komodor1** [OpenRCT2/OpenRCT2#6863]
**OS:** Linux Ubuntu
**Version:** 17.10
**Commit/Build:** a29c4f4

- [?] Reproducible in RCT2 (vanilla)?
- [?] Multiplayer? 

First problem is the crashing on startup. When the main menu shows up, game crash after 3-4 seconds. When I set "sound = false", there's no more problem with crashing.
My second problem is very distorted sound in main menu. I've attached mp3 file of captured audio.
[sound.zip](https://github.com/OpenRCT2/OpenRCT2/files/1586088/sound.zip)

**Comment by AaronVanGeffen** [comment]
Which version of SDL are you using? Crashes with 2.0.6 are expected; sound problems with 2.0.7 are tracked in #6667.

**Comment by komodor1** [comment]
Problem fixed. I've updated SDL to version `2.0.7+dfsg1-3ubuntu1` from https://packages.ubuntu.com/bionic/amd64/libsdl2-2.0-0/download and now there's no more crashes and sound distort. Thank u so much.
