### ISSUE TITLE
Function named map_get_corner_height is duplicated in source code with different definitions

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#6868]
https://github.com/OpenRCT2/OpenRCT2/blob/b574c231720112c92b548b9b89099924604224e6/src/openrct2/world/map_helpers.c#L180-L205

https://github.com/OpenRCT2/OpenRCT2/blob/b574c231720112c92b548b9b89099924604224e6/src/openrct2/world/map.c#L1453-L1490

**Comment by Gymnasiast** [comment]
One of the functions was removed in #6999 because it was only used by an unused function, thereby solving this.
