### ISSUE TITLE
The new guest search icon can overlap with the map icon

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#6869]
**OS:** Windows 7
**Version:** 0.1.2
**Commit/Build:** b574c23

**Steps to reproduce:**
1. Open a ride window
2. Go to the last tab
3. Click on any of the three guests tabs to the right

Screenshot:
![compound park 2017-12-26 15-17-49](https://user-images.githubusercontent.com/28242696/34364211-9c1f5178-ea51-11e7-889b-160f7a8589e8.png)

**Comment by AaronVanGeffen** [comment]
Ouch. How did none of us notice that during testing... Should be an easy fix, though.
