### ISSUE TITLE
crash when loading groena lund

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#6870]
**OS:** Windows 10
**Version:** e.g. 0.1.2
**Commit/Build:** 8fdec42

Download here: https://www.nedesigns.com/park/3891/groena-lund/
I downloaded Gröna Lund from NE and loaded the save. This message appeared:

![image](https://user-images.githubusercontent.com/3454156/34369228-fba376f2-ea6e-11e7-8b86-663cdc1a6eec.png)

Attempts to load the park always result in that dialog box (albeit with a different commit hash after I updated)

**Dump file**
https://www.dropbox.com/s/9fdm1s84earb9lo/openrct2.zip?dl=0

**Comment by Gymnasiast** [comment]
In general, errors like this point to a corrupted state. RCT2 will happily return sprite 65535, but might still crash later on.

**Comment by rwjuk** [comment]
I was able to load the given SV6 without issue - could someone else give it a test? Could it be corrupted object files?

**Comment by Broxzier** [comment]
I'm also not getting any errors, not even when using a build made from 8fdec42ff9b8956f6c502b683dec08141ec20fc7.
@spacek531 When loading the park, is there anything being printed to the console window for you?

**Comment by spacek531** [comment]
I opened the .com with --verbose and this was the most notable thing:
```
WARNING[util\Util.cpp:356 (safe_strcpy)]: Truncating string "_Tr∩┐ñffa Hesten / Aim the Hors" to 32 bytes.
An assertion failed, please report this to the OpenRCT2 developers.
Version: OpenRCT2, v0.1.2-develop build 74abb6e provided by AppVeyor
Tried getting sprite 65535```

**Comment by spacek531** [comment]
When loading the park in VS debug mode, this is the call stack I get:

![image](https://user-images.githubusercontent.com/3454156/34547108-988d2596-f0ad-11e7-9a35-caa655c00ed4.png)

I realized the file may have been corrupted somehow, so I have included it below:

[Broken Lund.zip](https://github.com/OpenRCT2/OpenRCT2/files/1602222/Broken.Lund.zip)

**Comment by janisozaur** [comment]
@spacek531 please don't post screenshots for information that should be conveyed in textual form.

**Comment by Gymnasiast** [comment]
I cannot open this zip (at least not on macOS, even with Keka). Can you just upload the SV6 or alternatively: compress as RAR?

**Comment by Gymnasiast** [comment]
I had no problem loading this on macOS.

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/8fdec42ff9b8956f6c502b683dec08141ec20fc7/src/openrct2/ride/ride.c#L2046

@spacek531 were you doing anything in the game or have you simply loaded the save?

**Comment by spacek531** [comment]
The game immediately crashed on import.

**Comment by janisozaur** [comment]
Does it still occur with current `develop`, 58d3259 ?

**Comment by spacek531** [comment]
I used the launcher and it updated to d91fd13, same issue still.

**Comment by Broxzier** [comment]
Can you try to temporarily rename your objects folder, so that it doesn't load them?

**Comment by spacek531** [comment]
it still happened

**Comment by Gymnasiast** [comment]
I think this is a Windows-only issue, and might be caused by text encoding conversion. #6958 and #7092 might be caused by the same error.

**Comment by Gymnasiast** [comment]
Could you re-test this with the newest develop?

**Comment by spacek531** [comment]
I just downloaded the latest via the launcher, and the same thing happens: the sprite 65535 dialog box pops up.

**Comment by AaronVanGeffen** [comment]
Hmm. The save is loading fine for me using 504e6359335c1d1c5966e323453be06c7d7dfd12 on Linux.

@Gymnasiast's hypothesis that it's due to a text encoding error is an interesting one, though I think there would have to be some memory corruption involved for it to lead to a sprite error. Could tie in with #6895, which we've been having trouble reproducing?

**Comment by janisozaur** [comment]
@spacek531 I noticed the zip with park from NEDesigns has malformed entry with sv6. By any chance, does renaming the extracted file fix the issue? I downloaded acc61368471ae MSVC (i686) build and was able to load it just fine with wine.

It looks like you are using AMD64 version, can you try that park with the i686 build? Or on another system?

**Comment by janisozaur** [comment]
On my system extracting the files from the zip without any changes results in a new file named `Grna Lund.sv6`, in base64: `R3LClG5hIEx1bmQuc3Y2Cg==` which causes the offending character to get misinterpreted as some format specifier and results in the entry being shown as such (i686 MSVC build, wine, load saved game window):

![zaznaczenie_266](https://user-images.githubusercontent.com/550290/36029011-b1709898-0da1-11e8-8ce2-6466c2e0891e.png)

**Comment by spacek531** [comment]
When using build f003366 provided by the launcher on my intel CPU using a re-named file, the exact same behavior occurs.

**Comment by Broxzier** [comment]
It finally crashes on my end with the same stack trace that @spacek531 posted before. Ride 103 (__Beckholmen/Kranlast) has too many vehicles. The ride has visibly only 1 vehicle, selecing any other vehicle will make the ride viewport focus on the corner of the map. Setting `ride->num_vehicles` to 1 and then unpausing the game makes it no longer crash.

This should be fixable by making sure no entries in `ride->vehicles` (up to index `ride->num_vehicles - 1`) have the value `SPRITE_INDEX_NULL`.
