### ISSUE TITLE
Game crash shortly after loading a certain save file

### ISSUE THREAD

**Issue by Failsnail** [OpenRCT2/OpenRCT2#6873]
**OS:** Windows 8.1

test 1;
**Version:** 0.1.1
**Commit/Build:** 4601265

test 2;
**Version:** 0.1.2-develop
**Commit/Build:** 4455925

Loading this save file seems to work fine, and the game will run for about one second before crashing without a clear reason. Vanilla RCT2 doesn't work on my system, so I can't check if it has the same issue. I do get crashes at random moments in openRCT2, I just happened to have saved the game just before it crashed this time (so I guess that rules out a saving/loading issue).

**Steps to reproduce:**
load the attached save file, that's all

**Save game:**
[Crazy Castle 2.zip](https://github.com/OpenRCT2/OpenRCT2/files/1589121/Crazy.Castle.2.zip)

**Comment by rwjuk** [comment]
I ran this save without problems for about a minute - could you download the latest build and retest?

**Comment by thachachec** [comment]
Duck suck nipple. Plant sex dicks and flick pineapple breast.

**Comment by Failsnail** [comment]
I just tested it on a9aaaf1 and the crash is exactly the same as it was before.
Is there anything I could do to give more details?

A video wouldn't be interesting, really. The program works fine for about one second, just enough to pan or select a ride (which makes its window appears as usual). After that second it stops responding, I probably should have used the word "freeze" instead of "crash" in hindsight.

![crash](https://user-images.githubusercontent.com/10279508/34387182-fb1f4f30-eb2c-11e7-9927-e7c868af82d7.png)

**Comment by AaronVanGeffen** [comment]
Could you open the console version (`openrct2.com`) instead of the .exe to see whether anything of interest is logged there? You might have to open it through a command prompt to see the console output.

**Comment by rwjuk** [comment]
Here's a copy I ran for a few minutes - give it a go.

[Crazy Castle test.zip](https://github.com/OpenRCT2/OpenRCT2/files/1589494/Crazy.Castle.test.zip)

**Comment by Failsnail** [comment]
The save you send works absolutely fine. Left it run for some time, build a new ride, nothing special.

> Could you open the console version (openrct2.com) instead of the .exe to see whether anything of interest is logged there? You might have to open it through a command prompt to see the console output.

Did this and it showed nothing, both in release and develop.
