### ISSUE TITLE
Too wide line height

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#6891]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** [e.g. 426e106]

I know that @AaronVanGeffen made line height of bottom status bars looks better in CJK, but it seems weird as you can see.
It is placed upward too much. I think there should be more top margin.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Screenshots / Video:**
![2017-12-28 23-37-33](https://user-images.githubusercontent.com/10726524/34413671-3adfec14-ec28-11e7-89da-4602df8fa388.png)

(Mouse hovered)
![image](https://user-images.githubusercontent.com/10726524/34413764-c32d22da-ec28-11e7-95c8-f73b1c034602.png)

**Comment by AaronVanGeffen** [comment]
You're right, it does look off like that. Button captions really ought to be vertically centred… It's one of the next things I've been aiming to tackle.
