### ISSUE TITLE
Accented characters are not loaded properly in develop, but are saved properly.

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#6895]
Since the Release version has been published, a bug has been introduced that improperly loads accented characters. Consider this .SV6 file:
[á file.txt](https://github.com/OpenRCT2/OpenRCT2/files/1594210/a.file.txt)

In the Release version, the merry-go-round's name is "aáa" but in Develop, the merry-go-round's name is "a?a". This is frustrating to players who use non-standard character sets.

Non-standard characters are able to be saved in Develop and load properly in Release.

The versions I have tested and confirmed are 74abb6e (the earliest develop version I can download from the openrct2 website), and 4459eb0.

When using a debug version with code dated to aa23370 the bug does not occur.

I am using Windows 10 64 bit home edition.

**Comment by AaronVanGeffen** [comment]
Seems to be working fine for me on Linux. We're using a different conversion library on Linux and macOS, though. Are you on Windows, by any chance?

**Comment by rwjuk** [comment]
Working as expected on macOS, therefore by process of elimination this must be a Windows-specific issue.

**Comment by rwjuk** [comment]
Okay, so this is interesting - using the latest build on Windows 10, the special character displays as normal.

@spacek531 Could you retry with the latest build, and specify which build of Windows you're running?

**Comment by spacek531** [comment]
the data folder as requested by @rwjuk 
[data.zip](https://github.com/OpenRCT2/OpenRCT2/files/1594821/data.zip)

**Comment by rwjuk** [comment]
@spacek531 Well, that doesn't seem to be the issue - ran ORCT2 with that `data` folder and still couldn't reproduce this or #6870

**Comment by spacek531** [comment]
More info:

![image](https://user-images.githubusercontent.com/3454156/34457754-a247c92e-ed6f-11e7-8eb2-c75f21aaca2f.png)

![image](https://user-images.githubusercontent.com/3454156/34457757-b62bf852-ed6f-11e7-903f-6c9df1ddf91e.png)

(using 74abb6e extracted to a different location)

**Comment by rwjuk** [comment]
Could you try the attached SV6 and report back? Contains a ride named with various non-ASCII characters.

[Forest Frontiers_accenttest.zip](https://github.com/OpenRCT2/OpenRCT2/files/1594893/Forest.Frontiers_accenttest.zip)

**Comment by spacek531** [comment]
In Develop, they are all question marks. In Release 0.1.1, they are all proper characters.

Files with accented characters appear appropriately in Develop e.g. "a file" and "Grona Lund"

![image](https://user-images.githubusercontent.com/3454156/34547083-550d3a40-f0ad-11e7-8319-de17cbe24a1f.png)

**Comment by IntelOrca** [comment]
@spacek531 Can you still reproduce this?

**Comment by AaronVanGeffen** [comment]
Possibly solved by 214df1cf75535f8d9beef217383af1c17b59b5c8?

**Comment by spacek531** [comment]
This appears to be fixed.
