### ISSUE TITLE
Remove LOADRCT1 and LOADMM commands

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#6898]
Now #6598 has been merged, these commands can be removed. They'll have to be removed from the title sequences first, so this will be after 0.1.2.

**Comment by AaronVanGeffen** [comment]
Perhaps this could be tackled in the transition following #4575? Assuming we'll pick that up eventually.

**Comment by Gymnasiast** [comment]
Possibly, but stuff like #4575 tends to take longer than planned.
