### ISSUE TITLE
tile editor: 'make real entrance' button for entrance huts

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#6916]
A button that appears when an entrance hut is selected that updates the station's hut location to the currently selected entrance hut. It will allow disconnected entrances to be made relatively easily, much easier than hex editing or editing via source code or debugger.

**Comment by Gymnasiast** [comment]
You can just cut and paste the entrance, OpenRCT2 will fix this on the next import. Though it could do with better handling.

**Comment by zaxcav** [comment]
I started implementing such functionality a while back, but I'm short on time as always and having a bit of a time-out from active contribution at the moment.
So if no one else beats me to it I'll finish this up at some point.
I got as far as coding the GUI additions to the Tile Inspector and stubbing a new game action (so this will also work during network play - which is another big advantage vs the current "fix on load" code).  Nothing tested yet though, so could be complete trash!

**Comment by spacek531** [comment]
@Gymnasiast this was not my experience, using a build dated to aa23370 (debug version for VS) when I opened up the Entrance field in the debugger it showed the original value, even though the copied entrance hut was above the original.

**Comment by Gymnasiast** [comment]
I was talking specifically about moved entrances.
In any case: why would one _copy_ an entrance? (This is not meant rhetorically.) It breaks all sorts of stuff.

**Comment by spacek531** [comment]
To move it, obviously. OpenRCT2 does not have any functionality to move objects arbitrarily outside of copy/pasting with the tile inspector, so copying it is.

**Comment by Gymnasiast** [comment]
Seems like adding cutting functionality to the tile inspector would be a good idea as well then.

**Comment by zaxcav** [comment]
Excellent points.
Copy really doesn't make sense for any type of entrance/exit.
Cut makes more sense, at least with respect to the current limitations inherited from vanilla - e.g. one entrance per ride station, max 4 entrances per park. Paste just has to deal with the additional places that keep track of the entrances/exits. Are there intents to change these particular limitations eventually when moving to a new save format? It would be nice to keep the future in mind with whatever we do here.

**Comment by spacek531** [comment]
A potentially simpler option is to fix the entrance/exit field when the hut is pasted. Cutting then becomes "copy then delete," where the deletion can happen at the user's leisure.

**Comment by xp4xbox** [comment]
Yeah I really like the "cut" idea, would be very useful for me.

**Comment by Broxzier** [comment]
This is not implemented.
