### ISSUE TITLE
Shops won't connect to path in Bumbly Bazaar

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#6919]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** ef657ca

Bumbly Bazaar has ten prebuilt shops when you start the scenario. When I delete the path and replace it, the ten original shops refuse to connect to the new path. This doesn't happen with any shops I build myself in the scenario. I've also tried this in a few other scenarios with prebuilt shops and it only happened in Bumbly Bazaar. This does not happen in vanilla. I've restarted the game and the scenario a couple of times but it still happens.

**Screenshots / Video:**
https://www.youtube.com/watch?v=Q7YHF6_E1hg&feature=youtu.be

**Comment by tobiaskohlbau** [comment]
I'm able to confirm this for the row which involves the Lemonade Stand the opposite site works fine.

**Comment by rwjuk** [comment]
It's not specific to this scenario - removing the path and replacing it next to a store in that orientation won't reconnect it.
