### ISSUE TITLE
Queue path tiles get replaced by normal path on mouse-over with path scenery

### ISSUE THREAD

**Issue by iliis** [OpenRCT2/OpenRCT2#6923]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** eb4a892

When trying to build foothpath scenery (such as litter bins, benches, lamps or jumping fountains) hovering over a queue path will replace it with a normal footpath.

- [ ] Reproducible in RCT2 (vanilla)? I don't think so, but haven't tried as it doesn't run on my PC :(
- [ ] Multiplayer?

**Steps to reproduce:**
1. Build a few tiles of queue path. It doesn't have to be connected to a ride. Existing paths from a savegame or scenario work as well.
2. Select some foothpath scenery (for example a normal bench) from the scenery window.
3. Move the cursor over the queue path. It will get replaced by a normal foothpath.

![pathbug](https://user-images.githubusercontent.com/933300/34527413-c0c94a6a-f0a5-11e7-9e08-c0519ce1ff6c.png)

**Comment by Gymnasiast** [comment]
Might have been caused by https://github.com/OpenRCT2/OpenRCT2/commit/eb4a8924d19387b7e566ae4587bb3b86c2638361.

**Comment by Broxzier** [comment]
It has indeed been caused by eb4a8924d19387b7e566ae4587bb3b86c2638361. I'll fix it asap.

**Comment by iliis** [comment]
Oh wow, that was a fast response! This fixed it indeed, well done! And thanks :)
