### ISSUE TITLE
Demolishing a ride freezes the game

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#6948]
**OS:** Windows 7
**Version:** 0.1.2
**Commit/Build:** 61dfb3d

Demolishing a ride crashes the game  (The game freezes and has to be killed in process manager)

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open the Electric Field scenario
2. Demolish the Boat Ride

**Dump file**
The game doesn't produce a dump file when this crash occurs.

**Comment by duncanspumpkin** [comment]
Argh sounds like the change to destruct of thoughts is getting stuck in a loop. Will look at it tomorrow

**Comment by mozar99** [comment]
this bug breaks every single multiplayer server.

**Comment by AaronVanGeffen** [comment]
However inconvenient, isn't exclusive to multiplayer, though. A fix is on the way, fortunately: https://github.com/OpenRCT2/OpenRCT2/pull/6953

**Comment by Eld0r** [comment]
confirmed. Happend on my multiplayer server, too.
whenever me or a client destroy or build back (to nothing) a specific attraction.
It happen every time for the stands: _hot chokolade_, _information_ (every other stand work fine)
and for: _wooden roller coaster_, _mini train_ (a few others work fine, we don't try to overplay all)

**Comment by TyPR124** [comment]
#6960 should fix this.
