### ISSUE TITLE
Game freezes when selecting a pre-built track design to build.

### ISSUE THREAD

**Issue by Luigi-San** [OpenRCT2/OpenRCT2#6949]
**OS:** Windows 10
**Version:** 0.1.2 
**Commit/Build:** 15d0a72

The game freezes when selecting a pre-built track design to build, regardless of ride type, vehicle type, and design.

**Steps to reproduce:**
1. Open any scenario.
2. Choose any ride type that has pre-built track designs available.
3. Choose any design. The game should freeze at this point.

**Comment by rwjuk** [comment]
This, like #6948, is a regression in #6937.
