### ISSUE TITLE
255 ride limit error not displayed anymore

### ISSUE THREAD

**Issue by mozar99** [OpenRCT2/OpenRCT2#6954]
**OS:** windows
**Version:** [e.g. 0.1.2]
**Commit/Build:** [e.g. 426e106]

when attemping to build more than 255 rides the error message says "can't construct this here", it should say "ride limit reached" . This is confusing for users who cant figure out why they cannot build.

- [ ] Reproducible in RCT2 (vanilla)?
- [x ] Multiplayer?

**Steps to reproduce:**
1. make 255 rides or and shops
2. try to build one more. error "can't construct this here"
3. it should say "ride limit reached"

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by Krutonium** [comment]
Impressive (because of the implication) bug report.

**Comment by duncanspumpkin** [comment]
This is caused by the game action refactor i expect. We lost a lot of the error messages.
