### ISSUE TITLE
Recent messages are not coloured

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#6958]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** 94946ce13b7e7fa9988336942214b585a5cce5b1

Recent messages window shows the messages uncoloured and instead just has a question mark at the beginning. This only happens in release builds.

**Left:** Release build (from openrct2.org)
**Right:** Debug build

![image](https://user-images.githubusercontent.com/1482259/34635029-fd0addf8-f281-11e7-8e67-ba26d82694cf.png)

**Comment by AaronVanGeffen** [comment]
Possibly related to #6951?

**Comment by rwjuk** [comment]
Interestingly I can't seem to reproduce this...

**Comment by IntelOrca** [comment]
I was not able to reproduce this on clang/Linux.

**Comment by SidaRadis** [comment]
I can reproduce this on Windows 7.

1. Start a game and everything works fine
2. Save the game
3. Load the save game and every message before the save doesn't have a color.
