### ISSUE TITLE
Demolishing a ride freezes the game

### ISSUE THREAD

**Issue by TonyLaV** [OpenRCT2/OpenRCT2#6963]
OS: Windows 7
Version: 0.1.2
Commit/Build: b7b4e3a

Demolishing a ride crashes the game (The game freezes and has to be killed in process manager)

This bug has been closed but it still isnt fixed 

Steps to reproduce:

Open the Electric Field scenario
Demolish the Boat Ride

**Comment by Gymnasiast** [comment]
Appears to have been caused by https://github.com/OpenRCT2/OpenRCT2/commit/26c35b5c28407ec8c0b363cff97b0ca32321be71.
