### ISSUE TITLE
Maze entrance does not connect to path on acting client.

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#6971]
**Commit/Build:** [e.g. df98548]

Building a maze and setting the entrance next to an existing footpath will not connect the path to the entrance on the client building it which is causing a desync.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Join the host.
2. Build a maze.
3. Set the entrance next to an existing path.
4. Desync

**Comment by Gymnasiast** [comment]
Perhaps related to #6919?

**Comment by ZehMatt** [comment]
So far I only noticed it with the maze entrances.

**Comment by ZehMatt** [comment]
No longer happening, I guess this was fixed with one of the game actions.
