### ISSUE TITLE
Research: Last development field is identical to progress field

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#6972]
**OS:** Windows 7
**Version:** 0.1.2
**Commit/Build:** 7d5de63

**Screenshots / Video:**
![compound park 2018-01-07 10-01-33](https://user-images.githubusercontent.com/28242696/34650691-2eb71738-f393-11e7-9213-7937c1bf8a5d.png)

**Comment by SidaRadis** [comment]
Everything works fine until the designing stage is reached, at that moment the last development becomes the next ride that will be developed.

**Comment by Gymnasiast** [comment]
@SidaRadis Fixed in 3d9466a2f.
