### ISSUE TITLE
Loading a save game breaks the build scenery window

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#6990]
**OS:** Windows 7
**Version:** [e.g. 0.1.1]
**Commit/Build:** [e.g. 426e106]

Loading a save game only displays the miscellaneous tab and sometimes a few other items. Interestingly, accessing the object selection window seems to resolve the issue.

**Screenshots / Video:**
![crazy castle 2018-01-10 12-46-07](https://user-images.githubusercontent.com/28242696/34787139-4346090c-f604-11e7-9550-ed381e50b5f0.png)

**Comment by SidaRadis** [comment]
I can still replicate this issue with the latest build. 
I attached a saved game of a scenario where it still occurs: 
[Walton Park.zip](https://github.com/OpenRCT2/OpenRCT2/files/1620480/Walton.Park.zip)

**Comment by Gymnasiast** [comment]
I did notice that the export was still not good. I just pushed another fix for that.

Anyway, consider everything you saved during that time to be broken.
