### ISSUE TITLE
Issues with Virtual Floor invalidation

### ISSUE THREAD

**Issue by rwjuk** [OpenRCT2/OpenRCT2#7002]
The Virtual Floor seems to have invalidation issues.

According to @JeroenDStout it performs better in terms of displaying correctly at higher frame rates.

![image](https://files.gitter.im/OpenRCT2/OpenRCT2/pW3Y/tear.gif)

**Comment by JeroenDStout** [comment]
![tear](https://user-images.githubusercontent.com/14242454/34831119-48de1368-f6e6-11e7-9ed0-b49c751d21d8.gif)

In slowmotion, the effect of moving the floor vertically seems to show some columns being updated ahead of others. My guess is that if the framerate is too low it somehow never gets to some columns which might cause the smearing of the horizontal bug.

**Comment by AaronVanGeffen** [comment]
This is a shame. I'm sorry we missed this during testing...

**Comment by JeroenDStout** [comment]
It is fair to say this one is hard to find if the game has a great performance! After a clean reboot the effect is barely visible unless I am running a very busy park.

To narrow it down, I found this is not happening with the land raising lowering, so may be it is isolated to the invalidation of the virtual floor tiles specifically?

![tear](https://user-images.githubusercontent.com/14242454/34842785-d1470982-f70c-11e7-81fd-08fb2e42385c.gif)

It looks like the tiles are either updated out of sync (an optimisation of update issue?) or the path is moved in-between drawings (but that is not possible as the game is single-threaded?).
