### ISSUE TITLE
Placing pre made coaster layout makes the park disappear

### ISSUE THREAD

**Issue by phadd-f** [OpenRCT2/OpenRCT2#7004]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** develop build 47a2360

I made a floorless coaster design in the coaster designer. Now I open an empty bench (a save game downloaded from NE) and when placing the specific coaster the park disappears. The screen talks for itselfs.

I tried the same in a scenario, same result. 

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1.  Make a coaster design in the coaster design tool
2.  Open a save game or open a scenario
3. Place designed coaster in the map

**Dump file**

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/26711761/34836837-5a7fc158-f6f9-11e7-8f07-cb044132e908.png)

**Save game:**

**Comment by Gymnasiast** [comment]
We're not going to be able to do anything without that track design...

**Comment by phadd-f** [comment]
[Venom.zip](https://github.com/OpenRCT2/OpenRCT2/files/1623489/Venom.zip)

**Comment by rwjuk** [comment]
I can't replicate this - does it happen reliably (i.e. every time, in any park)?

**Comment by phadd-f** [comment]
I tried some other things in another bench/park. Placing the same Venom track gave the same result. I reopened the bench/park and placed a standard rct premade layout of another coaster type. Those didn't give any problems. Just as I placed a custom premade lay-out from another coaster type than Venom, also no problems.

Then when I tried to place a premade floorless coaster lay-out (but not Venom), the problem was back again. Going from this result, the problem isn't on the park or bench, but with the floorless coaster type (steel twister coaster). Maybe some other types of coasters have the same issue?! I had no problems with the normal steel coaster and junior coaster.

For information, I used it first on this bench (the fixed one): https://www.nedesigns.com/topic/33919/ne-workbench-2017-by-louis/?hl=bench&fromsearch=1

**Comment by janisozaur** [comment]
Can you check the fix in https://github.com/OpenRCT2/OpenRCT2/pull/7012 ?

**Comment by phadd-f** [comment]
I've updated my openrct and the problem is gone.

**Comment by duncanspumpkin** [comment]
Could this also be the source of the -1 park size bug?

**Comment by janisozaur** [comment]
Maybe, but you'd have to check which variable was overwritten. `dv /f gMapSelectionTiles + Util::CountOf(gMapSelectionTiles)` should tell you
