### ISSUE TITLE
[Suggestion] More options in the launcher

### ISSUE THREAD

**Issue by Xardoz** [OpenRCT2/OpenRCT2#7008]
This is only a suggestion, from this thread : https://openrct2.org/forums/topic/2789-launcher-add-version-selection/

The user Eld0r suggested
"_It would be nice to have a version selection in launcher. (maybe for the last 2 days like on the website)
So game restarts (for whatever reason) will not force a update.
We mostly play in a group of four on my server and the server runs some hours, one or two days.
Actually we play through scenarios, but parks are getting bigger. Sometimes one of us joins later or take a pause.
I want to change to development version to use pause_server_if_no_clients.
The update rate is high (this is exemplary, I love it), but often game versions get different between us._ " 

I completed with some suggestions. It would be nice to : 
- have the possibility to disable automatic update
- to see what is (what are ?) the latest(s) version(s) available and from when it is
- to have a button to update manually (and if possible with the version you want).

**Comment by AaronVanGeffen** [comment]
I'm sorry to be the bearer of bad news, but the launcher is a very different, unofficial project. The first post in the forum thread you're linking contains a link to its official GitHub repository. Please file a ticket there instead.

**Comment by Xardoz** [comment]
No problem, I'm very sorry ^^" I'll try to be more careful next time, and I'm posting this in the right github right now.
Sorry again !

**Comment by Gymnasiast** [comment]
@Xardoz Oh, don't worry. No harm done.
