### ISSUE TITLE
Avast! blocks OpenRCT2

### ISSUE THREAD

**Issue by jupiterbjy** [OpenRCT2/OpenRCT2#7009]
**OS:** [Win10]
**Version:** [All versions are affected for 3~4 years]
**Commit/Build:** [bf06948]

I couldn't get result with keyword Avast, so I assume I'm only one reporting this issue.

I'm using openrct2 for about 3~4 years, and for that entire time Avast! kept inspecting and reporting openrct2.exe as 'potential threat', but this don't happen when I run it either via shortcut or adding it to steam. I reported about it at Avast! for years but nothing changed for years.

Even worse, although it's related to Launcher not Openrct2 itself, Windows smartscreen always block me installation of both x86 or 64bit Launcher as 'Threat'. And that don't even update game at all, for 3 years.

As Avast! support center ignore my report, only way to fix is finding and replacing code, which is nearly impossible. Glad it don't attack RCT1/2/3 at least,

*EDIT: Current version now trigger Avast! at any method, from this version now I can't launch openrct2 without blocking Avast!

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Install Avast! Free version
2. Run it with either OpenRCT2 Launcher or directly openrct2.exe file. Shortcut or using Steam prevent this issue.

**Screenshots / Video:**

https://youtu.be/DXH6tw-k68M
↑Openrct2 launcher triggering Avast!, After that inspection file was sent to Avast!.

![bandicam 0229](https://user-images.githubusercontent.com/26041217/34867882-29828604-f7c5-11e7-9fb8-079ec544cf99.png)
↑Avast! keep attacking and removing uninstall.exe, I don't care, I won't uninstall this beauty.

**Comment by IntelOrca** [comment]
You should be able to add an exception rule to certain directories such as `C:\Program Files (x86)\OpenRCT2` so that avast won't scan it.

**Comment by Gymnasiast** [comment]
@IntelOrca It happens both with and without the Launcher, as OP said in step 2.


@jupiterbjy We're not doing anything shady with your system. The fault lies with Avast!. There isn't much we can do about that. If they don't reply to your reports your only other option is dump Avast! and install a better AV.

**Comment by Patrik356b** [comment]
Weird. Today is the first time avast became hostile against OpenRCT2 for me. I previously switched because AVG had such a period. I guess I'll go back to Avira...

**Comment by jupiterbjy** [comment]
Ofcourse I do believe OpenRCT2 devs, and already used exception for that file, but existence of exception is surely not a desirable way of keeping system safe. That's just like "Welcome, please use this exception and infect my system!".

I just wanted to inform you guys so someday it could be fixed. And as Patrik356b said, today's build is alerting Avast! more than usual. Maybe you need to check code what went wrong.

Just cleared 5 more rct1 senarioes and pretty sure OpenRCT2 itself is running fine.

**Comment by Gymnasiast** [comment]
> That's just like "Welcome, please use this exception and infect my system!".

No, it isn't. It's telling Avast! that OpenRCT2 is safe and nothing else. Unless we put malicious code in OpenRCT2 - which we never will - allowing OpenRCT2 is not going to undermine your security.

Again, we cannot do anything, it's probably the result of changes Avast! made to its product.

**Comment by IntelOrca** [comment]
OpenRCT2 is compiled with Microsoft's latest compiler version. Often it takes awhile for AV software to update their known binary signatures.

**Comment by jupiterbjy** [comment]
I guess so, similar happend with PPSSPP daily build some months ago. But if Window smartscreen attacks it just like it does to launcher - I guess only Chris Sawyer could fix then.  Thanks for replying, guys
