### ISSUE TITLE
Suspended coaster banks in the wrong direction when going backwards

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#7011]
**OS:** [Windows 8.1]
**Version:** [0.1.2]
**Commit/Build:** Original bug

Suspended swinging coasters will bank to the inside of corners when going backwards. This behaviour was also in the original RCT2, but looks really weird. 

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Make a suspended coaster that goes backwards at some point. It will bank to the inside of corners.

**Screenshots / Video:**
Continuous track:
https://imgur.com/gallery/Cd9Rl
Shoestringed coaster:
https://imgur.com/gallery/JJScR

**Comment by deurklink** [comment]
I guess the same happens for all free swinging rides. This is a bobsled coaster that exhibits the same behaviour: https://imgur.com/gallery/cEOXn

**Comment by duncanspumpkin** [comment]
Can you normally make a suspended coaster go backwards?

**Comment by deurklink** [comment]
Yes, during a rollback.

**Comment by deurklink** [comment]
Adding abs() seems to fix it
`static void vehicle_update_swinging_car(rct_vehicle * vehicle)
{
    sint32 dword_F64E08 = abs(_vehicleVelocityF64E08);`
