### ISSUE TITLE
Feature: Show constituents of park rating

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#7027]
**OS:** [Any]
**Version:** [e.g. 0.1.2]
**Commit/Build:** [Any]

Park rating is a feature of the game that is never really explained well, and it is hard for someone to figure out what is wrong with a park unless he knows how park rating is calculated. Maybe there could be a debug option that shows the player for example how much points were lost because of litter, or how many points were added because of the amount of happy peeps in the park.

It would involve rewriting calculate_park_rating() in park.cpp to save the intermediate results in that calculation in variables.

**Comment by deurklink** [comment]
Testing:
![parkrating](https://user-images.githubusercontent.com/6469413/34918213-907c5070-f94f-11e7-9213-7ac753b96487.png)
Just found out that in one of my parks, litter is actually causing the park rating to be low. Always thought it was lost peeps. Removing all litter with cheats immediately raised the park value to max again.

**Comment by duncanspumpkin** [comment]
This is one of the mechanics of the game. Working out what is wrong with your park.

**Comment by Krutonium** [comment]
If you open the guests window, and sort by thoughts, chances are it would have told you near the top a lot of guests were thinking there was a lot of litter.

**Comment by deurklink** [comment]
Actually, the litter was very spread out throughout the park, so guests didn't complain about it. The game just counts every litter sprite.

**Comment by Krutonium** [comment]
Hm... Frankly I've never had a huge issue with it. I tend to overhire janitors though.

**Comment by deurklink** [comment]
It's not a huge issue, it is more a nice-to-have debug feature. Anyway, I have made a local copy of Park.cpp which stores these values for me which I can then read out with microsoft visual studio so I think this issue can be closed. Should we ever need to do something with it I can share the code.

**Comment by janisozaur** [comment]
Sounds very much like something that should be available through a plugin.
