### ISSUE TITLE
Permission Denied in Scenery Cluster when permission is enabled in any rank

### ISSUE THREAD

**Issue by ghost** [OpenRCT2/OpenRCT2#7028]
**OS: Windows 10 Home x64 Build 1709**
**Version: 0.1.2-28**
**Commit/Build: 3ba0cc3**

Hello, one of my mods tried to enable scenery cluster for something and he gets permission denied message when he tries to enable scenery cluster in my server. The cluster permission is checked in the moderator group when this was happening.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Join my server for testing purpose.
2. Try enabling scenery cluster to see if you are getting the same bug.

**Screenshots / Video:**

![](https://cdn.discordapp.com/attachments/391224125571727364/402177490946097192/unknown.png)

![](https://cdn.discordapp.com/attachments/391224125571727364/402177320481325066/unknown.png)

**Comment by Patrik356b** [comment]
if you re-open the settings window, is the box still checked?

**Comment by TonyLaV** [comment]
its the same problem i have. Only when i start an own server i can see the checks. When i join another sever no rank has any checks, even admin and i dont have the cluster permission. When i load release version everything works fine.

**Comment by daand12** [comment]
bump, still not fixed yet, only the host is able to use Scenery Cluster.

**Comment by AaronVanGeffen** [comment]
Probably related to #6804
