### ISSUE TITLE
Reliability goes above 100% on old rides that lack inspection

### ISSUE THREAD

**Issue by sjoerddebruin** [OpenRCT2/OpenRCT2#7030]
**OS:** MacOS 10.13
**Version:** 0.1.2
**Commit/Build:** 3ba0cc3

Noticed that my Enterprise had a higher reliability than 100%. I tried to reproduce this in a new game and found out that the reliability will overflow at a certain point. This will cause less breakdowns for quite some time.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1.  Build some ride and set inspection on never. Place some mechanic for the breakdowns.
2. Use cheats to move time 15 years in advance.
3. Change the speed of the game and notice the reliability going down very quick (as expected).
4. At some point it will reach zero, then it will overflow to above 250% and slowly going down.

**Dump file**

**Screenshots / Video:**
![schermafdruk 2018-01-14 20 31 27](https://user-images.githubusercontent.com/5605979/34920011-217e75dc-f96c-11e7-831c-ea1cbbc2b609.png)

**Save game:**
[Overflow.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/1629737/Overflow.sv6.zip)

**Comment by ryanmahan** [comment]
Seems to be an issue with moving the time forward, after testing with just hyper speed on, the ride breaks down at reliability = 0 as intended
