### ISSUE TITLE
Korean letters are invisible in OpenGL

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenRCT2#7038]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** 5af2b6c

Taken from the foru by **vpsxhtusm**; https://openrct2.org/forums/topic/2799-korean-characters-disappear-in-opengl-mode/

The korean font is invisible while you render the game in OpenGL

![image](https://user-images.githubusercontent.com/17282384/35037972-6c50210a-fb79-11e7-91a0-b575d69a576d.png)

**Comment by AaronVanGeffen** [comment]
It's not just Korean — OpenGL rendering engine doesn't render TTF text at all. It is one of my biggest gripes with it, and one of the main reasons it's still deemed experimental…
