### ISSUE TITLE
Map window not rendering properly when using OpenGL

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/OpenRCT2#7039]
**OS:** any
**Version:** 0.1.2
**Commit/Build:** 5af2b6c2146a60496429cb7e1de4a56c67fee2a1

The map window is not rendered properly when using the OpenGL renderer. This has been known for a while; I'm filing this issue to bring the remaining [issues with the OpenGL engine](https://github.com/OpenRCT2/OpenRCT2/wiki/OpenGL-renderengine-issues) back to the issue tracker.

- [ ] Most of the map isn't rendered at all.
- [ ] Only the vehicles of the rides (red stripes) get rendered at the map of rides and stalls.
- [ ] When you resize the map window an make it larger, the extra, non-used space of the map/park itself gets the same brown color as the surrounding UI instead of the normal black.
- [ ] At the people map, only the people get rendered and not the surroundings.

**Comment by IntelOrca** [comment]
Fixed in 710da039a4c2639620fcdc4fcd0cd20c413532fa.
