### ISSUE TITLE
Junior roller coaster freezes game when it has an infinite loop (merged into itself)

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#7052]
**OS:** [e.g. Windows 8.1]
**Version:** [0.1.2] 
**Commit/Build:** [48c3225] - I think i vaguely recall someone mentioning this to me months ago

When you merge a junior coaster track into itself and test it, the game freezes. I tested several other roller coaster types and they appear to work fine without freezing.
EDIT: Same seems to happen for minitiature railways and monorails. I have attached a save file with the same track for different rides. It looks like only the type of car on the track matters. You can place a looping roller coaster car on the junior track and it will work fine. 

![image](https://user-images.githubusercontent.com/6469413/35125386-b8e4f9ba-fca9-11e7-83a8-410290f27623.png)

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Build track as shown in image above
2. Test track

**Save file**
[Junior coaster test.zip](https://github.com/OpenRCT2/OpenRCT2/files/1644796/Junior.coaster.test.zip)

**Comment by duncanspumpkin** [comment]
Someone needs to check if we ever did tortoise and hare for get next track piece.

**Comment by duncanspumpkin** [comment]
https://github.com/OpenRCT2/OpenRCT2/issues/2081
