### ISSUE TITLE
Screenshots always fail

### ISSUE THREAD

**Issue by tcek** [OpenRCT2/OpenRCT2#7054]
Windows 10
0.1.2 
d972570

The standard screenshot always fails for me. Has been doing it for months now, on every park, but thought I'd make a new issue just in case the bug could be something more.

The giant screenshot works. 

It's annoying when you want to show your work to others but can't. The only way to do it is if you print screen, then open it in Photoshop, which is time consuming. 

I did however print the screen for you here and edited in PS, to show you what it says. 

![rctbug](https://user-images.githubusercontent.com/21962525/35131652-4adcbef6-fcbf-11e7-84f5-91280bdc385d.jpg)

[Screenshot Bug.zip](https://github.com/OpenRCT2/OpenRCT2/files/1645083/Screenshot.Bug.zip)

**Comment by janisozaur** [comment]
Any logs?

**Comment by tcek** [comment]
Nope, the game never gave me any logs. Sorry.

**Comment by duncanspumpkin** [comment]
It's probably a file access issue. Are you running openrct2 from program files or some other directory that you shouldn't be running it from?

**Comment by tcek** [comment]
I think I'm running it from My Documents, lol.

**Comment by tcek** [comment]
Nope, just checked. The OpenRCT2 Launcher is in the program files, so running it from there.

**Comment by tcek** [comment]
I did attach a save file, too.

**Comment by tcek** [comment]
My anti-virus program won't let me download a non-launcher build, this is what I get:

![threat](https://user-images.githubusercontent.com/21962525/35156986-77e619fe-fd2a-11e7-91c3-f82db6e3c834.jpg)

**Comment by Gymnasiast** [comment]
Tell AVG where it can stick its "threat warning".
Or, in more parliamentary language: either whitelist this in AVG, temporary disable AVG, or replace it with a better AV.

**Comment by tcek** [comment]
I got output, the game loaded as soon as I dragged the .com file into command prompt. The screenshots are working fine now. I haven't tried the Launcher again, but I suppose they just won't work on that?

Thanks for the help, much appreciated.
