### ISSUE TITLE
Doors in land textures for ghost train rides do not appear when loading SV4

### ISSUE THREAD

**Issue by saxman1089** [OpenRCT2/OpenRCT2#7059]
In vanilla RCTLL, doors appear in the land textures when a ghost train ride passes through. In OpenRCT2, it appears that this behavior is not carried over, as the areas that are supposed to be doors are holes. See the comparison image below. I'm not sure if this can be fixed given the limitations of the SV6 file format, but I thought I would report it nonetheless.

RCTLL:
![capture](https://user-images.githubusercontent.com/20549965/35176313-40e46bec-fd46-11e7-8183-c50211b10bb6.PNG)

OpenRCT2:
![aceworkbench_v11 2018-01-19 18-02-30](https://user-images.githubusercontent.com/20549965/35176350-76a7dffc-fd46-11e7-87cb-1ca5505c4f9c.png)

**Comment by Gymnasiast** [comment]
I don't think it's a limitation of the SV6 format. It's just that it needs implementing too.

**Comment by IntelOrca** [comment]
@Gymnasiast It appears that you have been assigned to implement it xD

**Comment by Gymnasiast** [comment]
@IntelOrca Yes, and not completely undeserved ;-)

**Comment by saxman1089** [comment]
Good to hear that its not a limitation. I also had to copy some files over from the LL cd to my local folder to get this to work, should I file a separate issue for that?

**Comment by Patrik356b** [comment]
@saxman1089 this is basically why you can specify an RCT1 installation folder in the options menu.

**Comment by saxman1089** [comment]
@Patrik356b this was after I had specified the RCT1 installation folder. I think these files are only contained on the CD, and not copied over automatically.

**Comment by Gymnasiast** [comment]
@saxman1089 No, it is entirely expected. The CD version does not copy csg1i.dat, ever.

**Comment by Gymnasiast** [comment]
This is how Chione looks now (with added terrain surfaces and landscape doors):

![aceworkbench_v11 2020-12-23 13-15-30](https://user-images.githubusercontent.com/1478678/102995295-0a102680-4521-11eb-8caa-f227a6d13236.png)
