### ISSUE TITLE
Avast detects 32 bit versions as infected

### ISSUE THREAD

**Issue by Sunlitspace542** [OpenRCT2/OpenRCT2#7063]
Avast detects 32 bit versions as infected. Please help!

**Comment by rwjuk** [comment]
Does it say what exactly it's picking up on?

**Comment by Gymnasiast** [comment]
Possible solutions:
1. Whitelist it in Avast.
2. Ditch Avast.

Obviously, the real solution would be for Avast to fix their stuff. In any case, we cannot fix problems in OpenRCT2 that aren't there.

**Comment by Patrik356b** [comment]
It is their real-time protection feature suspecting something. AVG sometimes does the same. It is eventually fixed by definition updates but might take a while for that to happen.

**Comment by Sunlitspace542** [comment]
It says it identifies the 32 bit launcher, the 32 bit portable version, and the 32 bit installer as infected with 
Win32.malware.gen I don't think this is any help though.

**Comment by Sunlitspace542** [comment]
Here's a screenshot:
![warning](https://user-images.githubusercontent.com/35207254/35194932-d7a852ac-fe89-11e7-953a-3e1da85940a3.PNG)

**Comment by AaronVanGeffen** [comment]
This means Avast is detecting a generic signature. In this case, it is a false positive. Your best bet is probably to whitelist the file, as @Gymnasiast recommended.

**Comment by Nubbie** [comment]
So many reports about it being a virus..

**Comment by jamtraks** [comment]
Yes i've experienced the same problem with avast. You may simply have to uninstall your avast program to be able to run openrct2. I am currently using avg antivirus and it is allowing me to play openrct2. The win32:malware-gen is not something that only you has, it is something in the openrct2 software that avast is detecting but seems to be harmless only causing a false positive.

**Comment by Gymnasiast** [comment]
malware-gen is short for "malware-generic" and is used when the AV finds something it doesn't know about it, but considers suspicious. Anyway, you can always have a false positive, and that's where the whitelisting feature is there for.
