### ISSUE TITLE
Great Wall of China Scenario Missing Peep Spawn Point

### ISSUE THREAD

**Issue by saxman1089** [OpenRCT2/OpenRCT2#7065]
Background, see here: 

https://openrct2.org/forums/topic/2808-getting-no-guests-in-ww-asia-scenario/?tab=comments#comment-17984

After checking the scenario myself, I noticed the peep spawn point is not set, which is causing guests to not show up.

**Comment by Patrik356b** [comment]
Remnants of #4760 ?
