### ISSUE TITLE
Minimum wait time affects ride length on mouse coasters

### ISSUE THREAD

**Issue by YrHendyStu** [OpenRCT2/OpenRCT2#7074]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.1.1]
**Commit/Build:** [e.g. 426e106]

When building mouse coasters changing minimum wait time affects ride length.

- [*] Reproducible in RCT2 (vanilla)? (First spotted in Classic)
- [ ] Multiplayer?

**Steps to reproduce:**
1. Build mouse coaster or any with hairpin corners (Virginia Reel, Inverted Hairpin etc).
2. Toggle minimum wait time
3. Toggle chain lift speed to retest
4. Coaster will now display a different length

**Dump file**

**Screenshots / Video:**

**Save game:**

![image](https://user-images.githubusercontent.com/35706713/35243761-faff36bc-ffb5-11e7-8bd6-acc154d4073e.png)

**Comment by duncanspumpkin** [comment]
How interesting

**Comment by jensj12** [comment]
The track length is measured until the point where the first train comes to a stop inside the station. With more more trains waiting in the station, the track length is shorter (same for ride time).

**Comment by deurklink** [comment]
Interesting. This could give issues if your ride is near the minimum length required to not get a stat reduction.

**Comment by deurklink** [comment]
I just reproduced this in vanilla RCT2. I tried several tracked rides and it happens to all of them. It also influences other stats like ride time (and most likely average speed).

**Comment by YrHendyStu** [comment]
I had a comment on one of my YouTube videos where I show this happening which may have solved it. If this is correct then it isn't actually bug but a clever game mechanic.

By leaving 'minimum waiting time' on there are more cars in the station so the cars have to travel a shorter distance. By having 'minimum waiting time off' the cars have to travel the length of the track plus the length of the station until stopping.

**Comment by duncanspumpkin** [comment]
I had a thought about this. And i don't think there is anything we can really do about it. If you made it wait to reach end of station then you mess with the average speed. So i think this will stay as a won't fix
