### ISSUE TITLE
Queue line traps guests in some situations when zero clearance is on.

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#7077]
**OS:** [Windows 8.1]
**Version:** [0.1.2]
**Commit/Build:** [c965f85] -- Have been noticing it for a few days already

1. Disable clearance checks
2. Build queue line from station to path
3. When on path you want to connect to, select an upwards or downwards piece. Then cancel (close footpath building menu).
4. Queue line becomes disconnected from one side, creating a one-way path which traps guests.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Screenshots / Video:**
![queuelineglitch](https://user-images.githubusercontent.com/6469413/35290892-e8ff42d4-006b-11e8-8617-4a153fc62785.gif)

![queuelineglitch2](https://user-images.githubusercontent.com/6469413/35290897-ebfbdcc2-006b-11e8-884f-ad05b8d16193.gif)

![junior coaster test 2018-01-23 18-27-28](https://user-images.githubusercontent.com/6469413/35290903-f259c2dc-006b-11e8-889e-5bd9067a3ba6.png)

**Comment by Gymnasiast** [comment]
> Commit/Build: [e.g. c965f85] -- Have been noticing it for a few days already

You still need to properly fill it in.

**Comment by deurklink** [comment]
Removed the e.g. part
