### ISSUE TITLE
Map not completely drawn in Scenario Editor

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#7083]
**Commit/Build:** 981b67a90f8cd92ee2e8c42c17f6461a6d2e36b7

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Open Scenario Editor
2. Click next

Possibly introduced by https://github.com/OpenRCT2/OpenRCT2/pull/7066.
Tagging @IntelOrca.

![2018-01-27 23-23-09](https://user-images.githubusercontent.com/1478678/35476914-2c273b16-03b9-11e8-8f7a-f92d24eda878.png)

**Comment by AaronVanGeffen** [comment]
This wouldn't happen to be on OpenGL, would it?

**Comment by Gymnasiast** [comment]
I'm afraid so. :/

**Comment by AaronVanGeffen** [comment]
Happens to the best of us. It's a testament to @LRFLEW's recent work on the OpenGL engine that you didn't notice you were using it before this!
