### ISSUE TITLE
Winning a RCT1 scenario doesn't mark it as cleared in the new game window

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#7084]
**OS:** Windows 7
**Version:** 0.1.2
**Commit/Build:** 8f1100c

This seems to have been introduced in the past week as I tried build fdeaaa5 and the issue doesn't occur.
Edit: Diamond Heights seems to mark as completed Build your own Six Flags Great Adventure while Evergreen Gardens is Build your own Six Flags Holland.

**Steps to reproduce:**
1. Play a Roller Coaster Tycoon 1 scenario
2. Win the scenario
3. Look at the new game screen and it isn't marked as cleared

**Comment by Patrik356b** [comment]
I have had the same issue in the past with Bumbly Beach, but I don't think the cause is the same.

**Comment by sjoerddebruin** [comment]
Just to be clear, you are using the original scenario's and not the recreations?

**Comment by SidaRadis** [comment]
I am using the original .sc4 scenarios from my RCT1 folder.

**Comment by sjoerddebruin** [comment]
Can confirm now, played Barony Bridge and marked Rotting Heights as completed.
