### ISSUE TITLE
Blue Hurricane hypercoaster causing screen to be stuck on corner

### ISSUE THREAD

**Issue by AndrewC437** [OpenRCT2/OpenRCT2#7085]
**OS:** Windows 10 build 16299.192
**Version:** 0.1.2-devlop
**Commit/Build:** 8f1100c

When placing the premade hypercoaster "Blue Hurricane", the screen gets locked to the bottom corner.  You cannot scroll away from the corner.  Saving and reloading will NOT allow you to escape the corner.  This was not an issue in 0.1.1 build 4601265

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Start any game or scenario where you can place a hypercoaster and select it from the coaster style menu
2. Choose the premade coaster Blue Hurricane
3. Once your mouse moves outside of the brown box, the screen will get locked to the bottom corner.

**Screenshots / Video:**
https://www.youtube.com/watch?v=-vS_Ex-QTuY

**Comment by Gymnasiast** [comment]
Hm, odd. Can't reproduce this myself (Ubuntu 17.10, AMD64, c404c05fa8df22adb6e685e8d13f438bee0ffae2).

**Comment by SidaRadis** [comment]
Can reproduce this on Windows 7 with build d6bf08e. This might be a windows issue.

**Comment by jensj12** [comment]
Can confirm with this wooden coaster (I currently don't have the original RCT2 track designs): 
[Somehow Competitive.td6](https://github.com/OpenRCT2/OpenRCT2/files/1671166/Somehow.Competitive.txt)

**Comment by duncanspumpkin** [comment]
Sounds suspiciously like the map size being overwritten especially with the workaround in #7104.

**Comment by dylan1114** [comment]
I've had it happen with a wooden coaster now too, after it also happened with the log flume. The similarities are that both are rather large and have a lot of scenery. The workaround in #7104 may require you to resize quite a bit (I clicked '+' about 10 times and it unstuck) which may mean you seriously damage your park if it is maximum sized. But it atleast made me able to play again.

**Comment by duncanspumpkin** [comment]
I expect it's the track file overwriting memory that it shouldn't.
