### ISSUE TITLE
Banner texts (the ones over path) get a question mark in front of them after reloading park

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#7092]
**OS:** [Windows 8.1]
**Version:** [e.g. 0.1.2]
**Commit/Build:** [9d04593] This error has been around for quite some time already.

Path banners get a question mark in front of the text after saving and re-loading the park. I play on EN-GB language.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Place banner over path, type a text
2. Save and re-load park. Text will now have a question mark in front.

**Dump file**

**Screenshots / Video:**
![banner test](https://user-images.githubusercontent.com/6469413/35486313-c1518f62-046c-11e8-8262-5cd3e0b74c2d.png)

**Save game:**
[Banner test.zip](https://github.com/OpenRCT2/OpenRCT2/files/1671527/Banner.test.zip)

**Comment by Gymnasiast** [comment]
Possibly formatting codes getting messed up.

**Comment by deurklink** [comment]
@Gymnasiast indeed, when you save them with a different text color, they will be white again when you load (but the option is still set to the different color).

**Comment by IntelOrca** [comment]
Possibly duplicate of #6958

**Comment by Gymnasiast** [comment]
Yes, that could very well be the case, as I cannot reproduce it on Linux. There seems to be an encoding issue. I think that https://github.com/OpenRCT2/OpenRCT2/issues/6870 is also related.

**Comment by Gymnasiast** [comment]
Could you re-test this in the newest develop?

**Comment by deurklink** [comment]
Will check this when I get home today!

**Comment by deurklink** [comment]
@Gymnasiast Looks like it is fixed
