### ISSUE TITLE
Inverted Hairpin Coaster supports not existing Parts

### ISSUE THREAD

**Issue by Mondanzo** [OpenRCT2/OpenRCT2#7101]
**OS:** Windows 10
**Version:** 0.1.12 
**Commit/Build:** 6bd0b2b

You can build sloped tracks for the Hairpin coaster but the tracks doesn't even exist.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
1. Build a Hairpin Coaster
2.  Build a sloped track part

**Screenshots / Video:**
![](https://cdn.discordapp.com/attachments/388384297221881869/407627289912803328/unknown.png)

**Comment by Spacerat** [comment]
I'm unable to reproduce this bug on 6b21aac4ea9d916a5569592d7b935ab98f8e0280

**Comment by AaronVanGeffen** [comment]
Probably fixed as a solution to #7711.
