### ISSUE TITLE
problem when testing unfinished rides

### ISSUE THREAD

**Issue by 60trainhunter** [OpenRCT2/OpenRCT2#7123]
**OS:** [Windows 10]
**Version:** [0.1.2]
**Commit/Build:** [d91fd13]

Unfinished tracks wont test anymore. i have the box ticked for it too.

- [ ] Reproducible in RCT2 (vanilla)?
- [ yes] Multiplayer?

**Steps to reproduce:**
1.just go to any scenario/map and build a random coaster unfinished and test it.
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by AaronVanGeffen** [comment]
![screenshot_20180202_235824](https://user-images.githubusercontent.com/604665/35758556-f80679d0-0874-11e8-8d0a-2961d53afbf6.png)

Works for me on 5800a0874d9c15e4003dc1032abe708e9b3bff77. Could you give some more detailed steps to reproduce?

**Comment by 60trainhunter** [comment]
try multiplayer on the build i said above

**Comment by alecward92** [comment]
@60trainhunter  I've usually made that work on the host end of the server instead of the client because it causes a huge desync, at least in the past.

**Comment by Gymnasiast** [comment]
You really need to be more specific, as this is not reproducible. Does it _only_ happen in multiplayer? Do you need to be host, guest, or either?

**Comment by Gymnasiast** [comment]
No longer valid now "test unfinished rides" has been removed in favour of the ghost train simulation.
