### ISSUE TITLE
RCTOA Acres no longer work

### ISSUE THREAD

**Issue by Horsti12** [OpenRCT2/OpenRCT2#7124]
**OS:** Windows 10
**Version:** v0.1.2-develop build
**Commit/Build:** d91fd13

**Screenshots / Video:**
![crash rctoa acres](https://user-images.githubusercontent.com/12634026/35770832-5909f9b0-0923-11e8-81c2-a5de4fac5991.PNG)

When I open the park RCTOA Acres from the titlescreen the game will crash.

**Comment by Horsti12** [comment]
It seems that the launcher still not find a newer version.
So I have to wait until the update appears.
Thank you

**Comment by Gymnasiast** [comment]
No longer reproducible indeed, must be a problem with the Launcher or openrct2.org itself.
