### ISSUE TITLE
Saving the game outputs an error message

### ISSUE THREAD

**Issue by Gammadivided** [OpenRCT2/OpenRCT2#7135]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** 97032f7

Every time I try to save my game, no matter what park/save file it is, an error message appears (screenshot included below). Just clicking "Save Game" or "Save Game As" is enough to trigger the message, but it seems to be harmless, as no matter what I click afterwards (Abort, Retry or Ignore), the window just closes and the saving process continues as normal. One unusual side effect is that, after closing the error message, I can't open the system dialog box anymore. Since the game doesn't crash, no dump file gets created, and the game just proceeds as usual (except for the strange system dialog box problem). It doesn't hinder my gameplay too much, but it's quite annoying to deal with, and may warrant some looking into.

**Steps to reproduce:**
1. Open any save file
2. Click "Save Game" or "Save Game As"

**Screenshot:**

![filing a report](https://user-images.githubusercontent.com/11410845/35863913-c5d52388-0b82-11e8-976f-60381b0e10c9.png)

**Comment by Patrik356b** [comment]
Might be a good idea to create a manual dump when this error happens. It may prove useful to finding the cause of the issue.

**Comment by Gammadivided** [comment]
How do I go about doing that? Sorry, I'm not an expert on the field.
