### ISSUE TITLE
Wrong categorisation of objects

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#7136]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** a6cb15c

Trees, walls and other objects are incorrectly categorized.
These are the screenshot taken at **Forest Frontiers** scenario.
As you can see, trees and other objects are categorized in the Miscellaneous tab, not in their own tabs.

a6cb15c (wrong)
![image](https://user-images.githubusercontent.com/10726524/35864176-58b5a748-0b94-11e8-93b7-406d55eff5aa.png)

d91fd13 (correct)
![image](https://user-images.githubusercontent.com/10726524/35864177-5afa5ada-0b94-11e8-8182-734873afce26.png)

**Comment by Gymnasiast** [comment]
I'm 99% sure I caused this.

**Comment by IntelOrca** [comment]
@Gymnasiast I think it was me.
