### ISSUE TITLE
Water, gentle and transport rides can only have 1 vehicle/train

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#7137]
**OS:** Windows 7
**Version:** 0.1.2
**Commit/Build:** 97032f7

I don't believe this affects other ride types like Roller Coasters or Go Karts.

**Screenshots / Video:**
![crazy castle 2018-02-06 09-39-33](https://user-images.githubusercontent.com/28242696/35865735-51e833ca-0b23-11e8-8447-5363a47aace4.png)

**Comment by Gammadivided** [comment]
I've been having the same problem. I can't make water rides have more than one train without disabling vehicle limits. Windows 10 BTW

**Comment by IntelOrca** [comment]
Caused by #7062.
