### ISSUE TITLE
Allow more than 31 trains per ride

### ISSUE THREAD

**Issue by tehplanefreak** [OpenRCT2/OpenRCT2#714]
In RollerCoaster Tycoon 2, roller coasters had a cap on how many cars per train you could set, and no one could bypass such a limit, even with a trainer. I'd like to see this cap removed in OpenRCT2, if the logic involving this hasn't been decompiled already.

**Comment by AaronVanGeffen** [comment]
We'd all like to go there, of course. Unfortunately, much more of the game's logic needs to be decompiled before we can — OpenRCT2 still heavily relies on RCT2's routines in those areas.

**Comment by Gymnasiast** [comment]
8 cars per trainer has a function for 8 cars per train*, so even with RCT2's routines in place, there is some room around this limit. Although completely lifting the limit would indeed require much more decompilation. It's quite high on my wishlist as well. :)

* Which works on Windows 98 and on Linux via Wine, but I'm not sure whether it still works on Windows XP and higher, since I recall more functions suddenly not working, like 10 foot shops.

**Comment by IntelOrca** [comment]
These sorts of limits along with more than 255 rides, more than 10000 sprites, larger maps, more available objects in one park and more scenery themes require changing of the game structures which we can't do almost the whole game is decompiled. It will also result in saved games files which are no longer compatible with the original game. These changes will come in the distant future.

**Comment by tehplanefreak** [comment]
Thank you all for the comments. :) 

Gymnasiast, as a side note, I tried using the 8 cars per train function (1.302) on RCT2 running on a Windows 98 virtual machine, but it doesn't appear to work.

**Comment by Gymnasiast** [comment]
It might not work with non-US versions of the game, and not with all rides. Are you using the US version? And which rides are you trying it on?

**Comment by tehplanefreak** [comment]
I tried it with the Triple Thrill Pack (2.01.043, distributed by GOG) on a Corkscrew Coaster.

**Comment by Gymnasiast** [comment]
I think that the GOG version differs a little from the original CD version (which I have).

Strangely, it stopped working on my Wine installation as well.
Anyway, your best bet is probably waiting until OpenRCT2 can ease/eliminate this limit (after full decompilation, as IntelOrca said).

**Comment by sjoerddebruin** [comment]
Is this possible now?

**Comment by Gymnasiast** [comment]
@sjoerddebruin No. I have looked into it, but it looks like an SV6 limitation.

**Comment by Nubbie** [comment]
![possible](https://user-images.githubusercontent.com/17282384/28238288-aeeebc6c-6950-11e7-9612-ff5d644b7a5b.png)
Possible now with cheats to add over 32 cars per train

**Comment by Gymnasiast** [comment]
@Nubbie The OP wants more than 31 trains per ride. That is not yet possible and will have to wait for the new object format.

**Comment by Margen67** [comment]
This issue is missing the `requires new save format` label.

**Comment by Gymnasiast** [comment]
![afbeelding](https://user-images.githubusercontent.com/1478678/114190740-ee078800-994b-11eb-8069-a9e9ecf9ae07.png)

On the new-save-format branch :D

**Comment by nottud** [comment]
When creating a ride that qualifies by default for more than the cap by default this is not respected - can the code that calculates how many vehicles be changed to now respect the new higher limit providing as many vehicles as possible?

**Comment by Gymnasiast** [comment]
@nottud Please put that as a comment on the new save format pull request (#10664).
