### ISSUE TITLE
RollerCoasterTycoon 2 ride not showing in the Object selection, except under "Loopy Landscapes" filter (which it also, but not exclusively, belongs to)

### ISSUE THREAD

**Issue by alexjwalker** [OpenRCT2/OpenRCT2#7140]
**OS:**  - OS X El Capitan
**Version:** - OpenRCT2, v0.1.2-HEAD build b4018d3 (DEBUG)

I wasn't able to find "River Rafts" in the object selection, with the filter "Roller Coaster Tycoon 2" applied - even though it is a ride which is native to this game. I found it instead under "Loopy Landscapes" filter (which it is also part of, but not exclusively). I'm reporting this as it might be the case for other rides which are part of both games and could cause compatibility with OpenRct users who do not have RCT1 Data files.

- [ ] Reproducible in RCT2 (vanilla)? Yes
- [ ] Multiplayer? No - related to object selection

**Steps to reproduce:**
1. Open object selection
2. Apply "Roller Coaster Tycoon 2" filter

**Screenshots / Video:**
![screen shot 2018-02-06 at 23 40 15](https://user-images.githubusercontent.com/36211045/35888192-2853f41c-0b97-11e8-933d-ce9bdc2bfc5a.png)

![screen shot 2018-02-06 at 23 06 39](https://user-images.githubusercontent.com/36211045/35887720-738be270-0b95-11e8-8aa1-5c916419ee5b.png)

**Comment by IntelOrca** [comment]
I think @Gymnasiast intended for it to only appear under the first game that it was introduced so that you could see what rides a game introduced that didn't exist before.

**Comment by saxman1089** [comment]
I understand that intention, but it makes it really hard to find objects unless you know what game they were introduced in. Perhaps this information can be given a different way, perhaps through some text somewhere in the object selection window when the ride is selected.

**Comment by Patrik356b** [comment]
Other option is to list the entries in every place they exist (makes more sense to be, but i can understand the current system)

**Comment by Horsti12** [comment]
Just select RCT1, AA, LL and RCT2 and you have the same behaivour as before.

**Comment by Liampie** [comment]
The problem is that before, there was no overlap between the different categories. With the new additions there is overlap. Rides like this raft thing should show up under both LL and RCT2. Currently it makes no sense

**Comment by Horsti12** [comment]
@Liampie but than it also have to show the RCT2 in the Time Twister filter and RCT1, AA stuff in the Loopy Landscape filter

**Comment by saxman1089** [comment]
When you want to select objects from RCT2, you should be able to click the RCT2 checkbox, and show all the rides that were in RCT2; or for LL, click the checkbox and show all the rides that were in LL. That is how a filter should work, it should not matter when the rides appeared. Any other method of doing it is extremely confusing, and forces the user to figure out when a ride first appeared.

It should show rides that were in RCT2 in the TT folder, as the base RCT2 game's rides were still in the game after installing TT.

The categories should not be exclusive, i.e., each ride shouldn't just show up in 1 category. The ride should be shown for multiple categories where it is appropriate. For example, the river raft ride should show up in the LL folder, the RCT2 folder, the TT folder, and the WW folder, because this ride appeared in all of those games. It should not show up in the RCT1 folder, because it wasn't in that game.

**Comment by Gammadivided** [comment]
I do not understand why this change to the object selection was made in the first place (it was perfectly fine before), but I completely agree with saxman. If I choose RCT2, I expect to see all the rides that were in the base RCT2. No extra categories added should change that. To be completely honest, the added categories don't organize anything, they just make the object selection a mess, and make external programs like Parkdat appeal to even the most casual of players.

**Comment by Horsti12** [comment]
I still not know what your problem is.
The default selection is as before. (all ticked).
If you only want to show the things from the base rct2 game than just remove the filter from WW and TT and it will show you all things which were included in base game.

The only "problem" happens when you also deselect the other games.

The filter for rct1, aa and ll are useful when you for example want to build a classic rct1 type scenario with rct1 rides.
And you can also find more about the rct history since you can see which ride, path, scenery object, ... was added with each game.

**Comment by blackhand1001** [comment]
I agree with the other posters. Selecting on RCT2 should show all the rides that were in base RCT2.

**Comment by Gymnasiast** [comment]
All rides in base RCT1 were also in RCT1+LL. All rides in base RCT2 were also in WW. The filters select on introduction, and changing it only serves to make the selection more inconsistent.

> It literally takes me 3-4 times longer to select rides now

That makes no sense at all. It takes you all of 3 seconds to select the RCT1, AA, LL and RCT2 origins.

**Comment by saxman1089** [comment]
I should have been more clear: until I knew how it worked, it took me a long time to figure out what it was doing. Now that I know how it works, yes, it doesn't take any longer. In the end, my point is this: Shouldn't we be striving for gameplay that's intuitive? I would argue the system we had before was more intuitive than it is now.

**Comment by AaronVanGeffen** [comment]
I think, in the end, this is down to poor communication on the project's part. The system now works differently from how it used to, and therefore doesn't align with what seasoned players have come to expect from it.

Ideally, we'd announce this sort of change on some platform, but in this case, that hasn't happened. I can see why people consider it a bug.

Personally, though, even if I wasn't directly involved in the changes, I'm in favour of the new behaviour. As has been pointed out in this thread, the new behaviour makes it possible to easily see at what point in the RCT(2) timeline an object was introduced. The downside is that players will need to have more origin filters selected at the same time.

To me, that's totally worth it.

**Comment by alexjwalker** [comment]
Ok I see the logic, but I don't think it makes sense for a filtering/tagging system.

The reason I posted this report was because the new filtering structure suggests exclusivity. I was worried that by using a specific ride (which only appears under Loopy Landscapes filter), my save game/park would not be compatible for players who do not have RCT1 data files linked. Do you see where I am coming from?

**Comment by Liampie** [comment]
I'm not in favour. Before, I found it really convenient that I could filter out custom or default scenery, with a simple click. Now it's four times at much work. Yes, only a few more clicks. But it takes away so much of the convenience.

In either case I think that all rides and things introduced in RCT1 should also fall under RCT2. No one is going to filter out the rides that were introduced in RCT2 alone.

**Comment by Liampie** [comment]
But I don't use one setting, I alternate depending on what I need the object selection window for. Sometimes I want just custom scenery selected to see if the savegame is custom scenery free, for example.

**Comment by Gymnasiast** [comment]
What I could do is making the game automatically select RCT1, AA, LL and RCT2, if the user shift-clicks the RCT2 filter.

**Comment by Patrik356b** [comment]
@Gymnasiast
I like that idea.

**Comment by Liampie** [comment]
I totally support that idea! That would probably suit all purposes of the filters that have been brought up. Good thinking!

**Comment by Gymnasiast** [comment]
Because that goes against the user's expectations of how an interface works.

**Comment by Liampie** [comment]
Fair enough. Is there a manual for  'hidden controls' like potentially this one somewhere? If it's not written down anywhere, no one will be able to use it unless they read it right here.

**Comment by Patrik356b** [comment]
I suppose a tooltip could be used

**Comment by spacek531** [comment]
Maybe this is what the plan is, but I am tired so I'll just say what I want: in my opinion the presence of an object should be the union of its enabled groups, **not the intersection**. So, the Reverse Freefall coaster would show up with RCT2 checked or Loopy Landscapes checked. This means people who mainly switch between RCT2 and Custom (like me) don't have to worry about whether or not RCT1 and its expansions are enabled.

**Comment by Gymnasiast** [comment]
The issue has been fixed - items present in rct1/aa/ll and rct2 will now show up in both.
