### ISSUE TITLE
no previews for rollercoasters

### ISSUE THREAD

**Issue by User126** [OpenRCT2/OpenRCT2#7156]
**OS:** [Windows 10]
**Version:** [e.g. 0.1.2]
**Commit/Build:** [f003366]

![bug](https://user-images.githubusercontent.com/36316526/36055652-b663735e-0e62-11e8-8c0a-3d0079ba319d.png)

- [no] Reproducible in RCT2 (vanilla)?
- [?? ] Multiplayer?

**Save game:**
[Wacky Waikiki.zip](https://github.com/OpenRCT2/OpenRCT2/files/1712782/Wacky.Waikiki.zip)

**Comment by janisozaur** [comment]
This is because you have enabled _experimental_ opengl renderer. It is already tracked elsewhere.
