### ISSUE TITLE
Initialisation of `LanguagesDescriptors` may fail.

### ISSUE THREAD

**Issue by Jaxan** [OpenRCT2/OpenRCT2#7169]
**OS: all?**
**Version: 0.1.1**
**Commit/Build: 683ffcd**

Not a bug I encountered in-game, but a problem in the code.

The global array `LanguagesDescriptors` depends on the global variables `TTFFamilySansSerif, ...`. These variables are defined in separate translation units (i.e., source files). This is a problem, because C++ (or C) does not define a order in which these variables are initialised. So it might happen that `TTFFamilySansSerif, ...` are still `0` when `LanguagesDescriptors` is initialised. This depends on the compiler/linker.

`LanguagesDescriptors` are defined here:
https://github.com/OpenRCT2/OpenRCT2/blob/683ffcdadc5814eacfa2978c672217b148541bd4/src/openrct2/localisation/Language.cpp#L30

`TTFFamilySansSerif, ...` are defined here:
https://github.com/OpenRCT2/OpenRCT2/blob/683ffcdadc5814eacfa2978c672217b148541bd4/src/openrct2/interface/FontFamilies.cpp#L21

This might work *now*, but that is then just a coincidence. (I got this as an error from a static analyser.)  One way to fix this is to make `LanguagesDescriptors` into a function which has the static array locally (it will then be initialised the first time it is called).

**Comment by AaronVanGeffen** [comment]
Nice find. This is a potential explanation (and solution) for the game unexpectedly crashing when switching between TTF languages. It doesn't happen consistently, but when it does, logging indicated the game was trying to use/dereference a nullptr.

I'd welcome a PR for this, of course. ;)

**Comment by Jaxan** [comment]
I've been looking at this a bit more. I noticed that only the addresses are used (i.e., not the values) of `TTFFamilySansSerif, ...`. So initialisation should not matter here. So unless someone wants to add something, I believe we can close this issue.

@AaronVanGeffen you should file a separate issue if you can reproduce the crash.

This was probably a false alarm in the infer static analyser. I filed a bug report there: https://github.com/facebook/infer/issues/866
