### ISSUE TITLE
Jet skies can't cross broken down submarine ride

### ISSUE THREAD

**Issue by RM87** [OpenRCT2/OpenRCT2#717]
Jet skies can't cross broken down submarine ride.
savegame: http://web.zone.ee/rmihkel87-1/orct2/Botany_Breakers_c-water%20jam.SV6

**Comment by IntelOrca** [comment]
Does this happen in the original game?

**Comment by IntelOrca** [comment]
None of these rides are able to be fixed either in this saved game, and one mechanic mysteriously drowns on 25th March.

**Comment by duncanspumpkin** [comment]
This happens in the original game so dont expect this to be fixed anytime soon.

**Comment by Gymnasiast** [comment]
Of course they can't. The clearance of the submarine ride sticks to 1.5 m above water level, and the submarines themselves also stick out above water level.

**Comment by IntelOrca** [comment]
@Gymnasiast I agree, wouldn't make sense to make this possible. Think of the health and safety issues if peeps were allowed to jet ski into an area that a submarine which sticks out could pass through.

**Comment by Gymnasiast** [comment]
Closing as IntelOrca, Duncanspumpkin (see #2400) and I agree it is a wontfix.
