### ISSUE TITLE
Clicking any ride that has custom designs available crashes to desktop

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#7171]
**OS:** Windows 7
**Version:** 0.1.2
**Commit/Build:** c8b5cbb
 
**Steps to reproduce:**
1.  Open the build a new ride menu
2.  Click to choose a ride with custom designs
3.  Game crashes to desktop

**Comment by austindaut27** [comment]
Having the same issue. On macOS 10.12.6. Using the launcher, version 0.0.7.

**Comment by janisozaur** [comment]
Can you provide a stack trace?

**Comment by jupiterbjy** [comment]
Same issue here, build 3ea6a3e on Win10, and I can't find where the dump file is.
Roller coaster tycoon without roller coaster ;)

**Comment by halapli** [comment]
It's happening to me too. When playing with OpenGL rendering, it doesn't crash until I select one of the custom rides, since there are no previews.

**Comment by Gymnasiast** [comment]
Perhaps caused by #7167.
