### ISSUE TITLE
Savegame are no longer compatible with vanilla

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#7173]
Any savegames saved with the latest version of OpenRCT, or any recent version, are incompatible with vanilla by default. You can even open a fresh Crazy Castle scenario, save without doing anything, and for some reason the savegame will be incompatible. This is very annoying - if I want my savegames to be compatible with vanilla, I have to open them in an older version of OpenRCT first, then save again, and only then can I open them in vanilla again. I not only need vanilla for hacks, but also for preparing any parks in the NE Database.

Using version v0.1.2 3ea6a3e

**Comment by Gymnasiast** [comment]
Incompatible in what way? An error message? Crash?

Really, put a bit more effort in your issue reports. You didn't even bother to look up the version, much less pinpoint the first good version.

**Comment by AaronVanGeffen** [comment]
How long has this been happening? We've been refactoring a lot in this year alone. Looking at [the log for S6Exporter.cpp](https://github.com/OpenRCT2/OpenRCT2/commits/develop/src/openrct2/rct2/S6Exporter.cpp) gives you an idea what builds might be interesting to look at in terms of causing the regression.

**Comment by Gymnasiast** [comment]
Doesn't have to be S6Exporter, though. Could simply be something related to object or tile elements.

**Comment by AaronVanGeffen** [comment]
@Liampie Thanks for adding the version info. If you have time, could you try and help us track down (roughly) when the problem was introduced? That'll really help speed up a fix. (Not all of us use Windows, which makes testing things in vanilla a little harder…)

**Comment by Gymnasiast** [comment]
Well, I have been bisecting, but even 6c3e215907cf955e82a2f1cf1eb525ccaecc3114 yield this. That's a commit from _15 November_. Did this go unnoticed for that long?
