### ISSUE TITLE
Opening object selection crashes game

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#7175]
**OS:** [Windows 10]
**Version:** [0.1.2]
**Commit/Build:** [c8b5cbb] and later builds

Starting from build c8b5cbb, the game crashes as soon as you open Object Selection.

**Comment by AaronVanGeffen** [comment]
I don't see how c8b5cbb could have caused that, as it only affects macOS builds... The AVX2 merge slightly precedes it, though, which has more of an impact on Windows systems. Could you verify whether it happens with ac1a9368410cc13860fb6483181e2f6ab3413ddc?

**Comment by deurklink** [comment]
When testing where the problem originated, i used the windows installer found here: https://openrct2.org/downloads/develop/c8b5cbb
At the build before it, c672e60, the problem is not there.

**Comment by deurklink** [comment]
@AaronVanGeffen I loaded ac1a936 in my debugger, and when i tried to access object selection, i got this error:

![image](https://user-images.githubusercontent.com/6469413/36165239-2cda141e-10ef-11e8-9ea4-c2b74a010036.png)

**Comment by IntelOrca** [comment]
@deurklink can you post the call stack?

Also try out the latest `develop` as I just fixed #7171.

**Comment by deurklink** [comment]
@IntelOrca It doesn't crash in the lastest develop. I think we can close this.
