### ISSUE TITLE
Opening Object Selection Causes an Immediate Crash

### ISSUE THREAD

**Issue by saxman1089** [OpenRCT2/OpenRCT2#7181]
Version: v-0.1.2 develop build 3ea6a3e

As soon as the Object Selection window is clicked on, the game crashes. I've tried this with three different parks, with the same results every time.

**Comment by ArcticX9** [comment]
[MoA.zip](https://github.com/OpenRCT2/OpenRCT2/files/1722367/MoA.zip)

Same problem with this save.

**Comment by Col-E** [comment]
Same here. Any build-your-own ride crashes on selection in the latest develop.

**Comment by janisozaur** [comment]
This was fixed in 9cc8d36a0369d8cc843f57d1ad72d7ef03319269, update your versions.
