### ISSUE TITLE
Master server is gone

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#7185]
Primary master server at https://servers.openrct2.io is gone:

> No such app

This is tracking issue while we continue investigation.

**Comment by janisozaur** [comment]
As part of fixing #6277 I launched my own master server you can access at https://glacial-scrubland-24489.herokuapp.com/

To configure your client/server to use it, change your `config.ini` to have this: `master_server_url = "https://glacial-scrubland-24489.herokuapp.com/"`

**Comment by telk5093** [comment]
Now it seems works again

**Comment by telk5093** [comment]
Server is gone again now
