### ISSUE TITLE
OpenRCT is not working on Debian Buster because of libpng12 (and probably other distros)

### ISSUE THREAD

**Issue by Luraktinus** [OpenRCT2/OpenRCT2#7186]
**OS:** [Debian Buster]
**Version:** [0.1.1]
**Commit/Build:** [4601265]

./openrct2: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory

libpng12 not possible to install

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Trying to run it
2. praise

**Notes:**

#6697 is known to me and a kludge and not a solution

Please, Please use AppImage to be less of an headache for 80% of the Linux Community
https://appimage.org/

will be linking to https://github.com/AppImage/AppImages/issues/29 and calling @RazZziel for help

thanks

**Comment by janisozaur** [comment]
There is already https://github.com/OpenRCT2/OpenRCT2/issues/6112, can you please detail what are the differences between the three available formats?

Getting it packaged as snap required just a few minutes and a handful of lines in `snapcraft.yml` (which I don't think I have handy right now) and I worked with upstream developers to improve Arch (my distro of choice) support, which was the major roadblock when the issue was filed.

Please also take a look at https://github.com/OpenRCT2/OpenRCT2/issues/6842 / https://github.com/OpenRCT2/OpenRCT2/issues/5139

> libpng12 not possible to install

That's simply not true. Your `apt` may be unable to do that, which is a deficiency of your package manager, but there is nothing stopping users from installing `libpng12`.

**Comment by Luraktinus** [comment]
>That's simply not true. Your apt may be unable to do that, which is a deficiency of your package manager, but there is nothing stopping users from installing libpng12.

Ubuntu AND Debian (stable) already dropped support for that obsolete version of libPNG

solution: provide this obsolete version with the software (with appimage, flatpack, snap) or upgrade to the new version that offically replaces it.

Again, there is a difference between a "kludge" and a "solution"

**Comment by Gymnasiast** [comment]
> Please, Please use AppImage to be less of an headache for 80% of the Linux Community
> i will not compile or force an installation of an obsolete software in my clean system, because the devs dont upgrade their dependencies, end of story.

How about you approach us less aggressively? Do you honestly expect us to help you if you're talking to us like that?

In any case, we still compile against libpng12 because of Ubuntu 16.04. That will most likely change when Ubuntu 18.04 comes out.

**Comment by Luraktinus** [comment]
>In any case, we still compile against libpng12 because of Ubuntu 16.04. That will most likely change when Ubuntu 18.04 comes out.

i dont see a reason to wait that long,
ubuntu 17.10 is out already and dropped support while libpng16 is supported by ubuntu16.04 and up and also Debian

**Comment by Luraktinus** [comment]
and sorry for that "aggressiveness", i have mental issues and lose myself quickly

**Comment by Gymnasiast** [comment]
Ok, thanks.

> i dont see a reason to wait that long,
ubuntu 17.10 is out already and dropped support while libpng16 is supported by ubuntu16.04 and up and also Debian

Our CIs run on 16.04 and non-LTS images are not available. Furthermore, while libpng16 and libpng16-dev are available, attempting to install them means removing libfontconfig1-dev and libfreetype6-dev, both of which we need.

**Comment by Luraktinus** [comment]
what are the consequences of them being disabled?

**Comment by janisozaur** [comment]
> i will not compile or force an installation of an obsolete software

Said Debian user.

https://abi-laboratory.pro/tracker/timeline/libpng/ libpng 1.6 was first released 2013-02-14 and it only took 4 years for debian to notice: https://packages.debian.org/search?keywords=libpng and https://distrowatch.com/table.php?distribution=debian

I don't see what's the sudden rush all about. You're welcome to compile openrct2 on your system and we will properly use libpng 1.6.

We will gladly accept any help to improve the situation, which you so kindly offered, but in the meantime I would suggest you tone down your demands a bit, as you come through as overly aggressive.

See https://github.com/OpenRCT2/OpenRCT2/pull/6034 for rough idea of how the upgrade of relevant CI jobs to 18.04 is meant to look like (TL;DR: switch as soon as it's out)

**Comment by Luraktinus** [comment]
>Said Debian user.

yes, want to keep my system clean of kludges, i was forbidden to tinker with it unnecessary

**Comment by Gymnasiast** [comment]
> what are the consequences of them being disabled?

Well, we can't compile without libfontconfig1-dev and libfreetype6-dev, unless we disable TTF rendering. But since normal builds have TTF rendering on, this is not a good idea - it means bugs can easily go unnoticed.

Anyway, openrct2 can be compiled against libpng16, in case you compile stuff yourself.

**Comment by Luraktinus** [comment]
i hate compiling, i am not a dev (yet), just an annoyed user that wants to play this game

**Comment by Gymnasiast** [comment]
Well, we have given you a number of workarounds. It's up to you if you want to use them or not.

**Comment by Luraktinus** [comment]
then i would probably try the Android version instead

**Comment by Luraktinus** [comment]
congrats, the android version is playable, 
i really hope you make the Linux version easy to use soon

**Comment by janisozaur** [comment]
@Luraktinus you can try using the packages from launchpad: https://launchpad.net/%7Eopenrct2/+archive/ubuntu/nightly

**Comment by Luraktinus** [comment]
@janisozaur

i use Debian, i wrote that in the issue

**Comment by janisozaur** [comment]
so?

**Comment by Luraktinus** [comment]
so, no PPA for  me...

**Comment by janisozaur** [comment]
That's completely not true.

**Comment by Luraktinus** [comment]
i read that on the Debian Wiki, and i won't corrupt my system because some stranger told me to do...

i am an end-user, i want a properly packaged version of this game to be able to play it, like everyone else does that successfully but OpenRCT2

**Comment by Patrik356b** [comment]
The obvious solution for you @Luraktinus is to run vanilla under wine or a windows VM until OpenRCT2 can be updated since you seem paranoid of contamination.
(it's highly unlikely that you would break something by compiling this yourself. And that's why we have backups.)

By the way, the second portion of your last post seems cut off.

**Comment by Luraktinus** [comment]
i use wine for it already
(which is sad)

**Comment by janisozaur** [comment]
Ultimately it's up to you to use the builds we provide.

**Comment by Luraktinus** [comment]
@janisozaur 
how that???
the builds that youn provide dont work

**Comment by janisozaur** [comment]
This discussion is getting pointless. You said yourself you refuse to use the builds we provide: https://github.com/OpenRCT2/OpenRCT2/issues/7186#issuecomment-366438426

**Comment by Luraktinus** [comment]
the ppa builds are made for Ubuntu

**Comment by janisozaur** [comment]
And your point?

**Comment by Luraktinus** [comment]
i don't have Ubuntu

**Comment by janisozaur** [comment]
Why did you report the bug in the first place then?

**Comment by Luraktinus** [comment]
because your build does not work on my os

**Comment by janisozaur** [comment]
This is getting ridiculous.

So you try a build done on Ubuntu and file an issue but refuse to try use another build on the grounds "it is not your OS" and keep on whining how you refuse to apply the fix… so why did you file the issue in the first place? There are fallacies in your arguments.

As I said earlier:

> Ultimately it's up to you to use the builds we provide.

**Comment by IntelOrca** [comment]
@Luraktinus we do not support Debian, for Linux distros it is up to the community to provide packages through the package manager of the distro. We do not have the manpower to provide specific builds / maintenance for every distro as they are far too many and they all have their subtle differences.

You can either use a supported OS such as Windows or Ubuntu 16.04 or ask someone in the Debian community to provide a package for OpenRCT2.

**Comment by Gymnasiast** [comment]
Look, we have suggested several options. You have dismissed most of them. That's not helping. And while I'm not completely happy how @janisozaur handled some stuff here, you're not conversing in a very pleasant way either. In any case, this has gone out of hand, so I'll have to lock the conversation.

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/pull/7523 migrated our Ubuntu docker images from Ubuntu 16.04 to Ubuntu 18.04, our future builds will be using that as a base
