### ISSUE TITLE
Bizzarre Openrct2 guest AI behavior

### ISSUE THREAD

**Issue by ReakutheCrate** [OpenRCT2/OpenRCT2#7188]
OS: Windows 7 Home Premium (64 bit)
Version: 0.1.2
Commit/Build: 92c4c39

Seeing that Openrct2 could play rct1 scenarios, I wanted to replay them in a better engine, however something was off about the guests as I was playing.
Guests entering my park will not ride anything but roller coasters, ignoring every other rides queue lines in their path, even after the queue line is full for said roller coaster, they would still buy something from stalls along the way, but would ignore other lines, if I were to go into the debug menu and check prefer less intense rides, then the guests would fail to get on any of the rides provided.
If I were to load the save file in vanilla rct2, the guests would still do the exact same thing, however, any new guests in the park would start to get into the other queue lines like normal, while any of the previously existing would not.

[   ] Reproducible in RCT2 (vanilla)?
[   ] Multiplayer?

Steps to reproduce:
1. Built up several of the basic gentle and thrill rides in a straight path, with food stalls along the way.
2. Build a roller coaster at the end of the path of rides.

**Screenshots / Video:**
![orct2-1](https://user-images.githubusercontent.com/29901512/36264010-372eae8c-1231-11e8-8b3a-45b738c62b23.png)
![scr1](https://user-images.githubusercontent.com/29901512/36264050-507722ac-1231-11e8-91a9-a52602d029a7.png)

**Save game:**
[Save.zip](https://github.com/OpenRCT2/OpenRCT2/files/1728262/Save.zip)

**Comment by Gymnasiast** [comment]
Also tagging AI guy @zaxcav .

**Comment by duncanspumpkin** [comment]
That sounds like rct1 import issues. Probably messing up the preferences for rides.

**Comment by Gymnasiast** [comment]
Investigated. It has nothing to do with RCT1 import or preference issues. Guests simply think your rides are too expensive. When I lower the ride prices, they will join.

If a guest has paid for entry, there are not prepared to pay a lot for the rides.

**Comment by ReakutheCrate** [comment]
Which is more so bizarre, as this works flawlessly in rct1, the guest ai didn't change THAT much between 1 and 2.

**Comment by Krutonium** [comment]
To be fair, in RCT1 paying for both was expected. In RCT2, the opposite is true - you pay one or the other, not both. The guests are not super happy about that.

**Comment by Gymnasiast** [comment]
> Which is more so bizarre, as this works flawlessly in rct1, the guest ai didn't change THAT much between 1 and 2.

The guest AI saw tremendous changes in RCT2. Especially (but not exclusively) in the area of pathfinding. Furthermore, RCT2 saw several money-related balance changes: calculation of park value is different, loan interest is much higher, staff wages are higher, etc.
