### ISSUE TITLE
In RCT1 scenarios certain vehicles are available before being researched

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#7191]
**OS:** Windows 7
**Version:** 0.1.2
**Commit/Build:** da9502a

**Steps to reproduce:**
1.  Play the Forest Frontiers scenario
2. Research Roller Coasters
3. Log Trains for the Junior Roller Coaster are researched but have been available from the start of the scenario. 

**Screenshots / Video:**
![forest frontiers 2018-02-15 19-43-56](https://user-images.githubusercontent.com/28242696/36288503-ec50b4e8-1288-11e8-9807-66830854bfc2.png)

**Comment by Gymnasiast** [comment]
Can't reproduce on 2e362530748e54890bb591527ed1108dc2d1d2be. Has likely been fixed at some point.
