### ISSUE TITLE
Crowd Noises Absent

### ISSUE THREAD

**Issue by ArcticX9** [OpenRCT2/OpenRCT2#7196]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** 33c7b8e

Crowd noises seem to have disappeared recently. I have not changed any settings and made sure that all sound effects are on.

**Steps to reproduce:**
1. Open a park with sufficient guests
2. No crowd noises

**Comment by AaronVanGeffen** [comment]
Appears to be a regression of b2bc974fe7

**Comment by telk5093** [comment]
Is it also related to this that guest's clap sound is absent when scenario is cleared?

**Comment by Ziscor** [comment]
Just wanted to mention this also seems to affect rain. When weather is 'Thunderstorm' you can still hear the thunder, though. Using original disc version of RCT2.

**Comment by ZehMatt** [comment]
I'll probably refactor the whole audio thing whenever I got some spare time.
