### ISSUE TITLE
RCT3 style  queue placing

### ISSUE THREAD

**Issue by ThomasdenH** [OpenRCT2/OpenRCT2#720]
In RCT3 the queue placing is different and more useful compared to RCT2. When a queue is connected to a foot path, and a new piece of queue is placed besides it, the beginning of the path moves. In RCT2 this would just create an empty queue not connected to the ride. In my opinion it would be a great improvement if RCT2 would adopt the same behaviour.

**Comment by IntelOrca** [comment]
So basically, when you place a new queue tile, always connect it to the last queue you placed if the two tiles are adjacent and disconnect the last queue tile from a normal path in the process. Therefore it allows you to place a queue path down the side of a normal path without having to manually correct the attachments or temporarily remove the normal path.

**Comment by vzybilly** [comment]
I do remember when I was playing RCT2 afew months back that every now and then it would move the queue opening even after it connected to a path, it just wouldn't do it constantly... I don't remember what made it move but I do remember it happening in the original... maybe the conditions are to strict in 2 but more open in 3?

**Comment by ThomasdenH** [comment]
Are you sure? I tested every orientation and it doesn't seem to reconnect.

When a queue is already built alongside a path, and the queue on one tile is removed, the queue doesn't connect to the path as it would do normally. Therefore the queue can be placed back again without having to redo the original path.

**Comment by vzybilly** [comment]
It is pretty rare that it did what you said but I have gotten it to work once or twice in about 10 completed parks... so it's pretty hard to do but it did stand out to me since it doesn't normally... I'll see if I can't test later on...

**Comment by Gymnasiast** [comment]
You can click and drag queue paths to extend them in RCT2. I think that approach gives the user more control over his/her queue lines, especially when you have two adjacent queues for different rides, for example.

**Comment by ThomasdenH** [comment]
Hmm. Reclicking the old path seems to make it update to its preferred state. For example, clicking the red path, leads from this...
![First](http://i.imgur.com/Fj5Birg.png)
...to this:
![Second](http://i.imgur.com/dooGPWG.png)

I guess it prefers a certain orientation and chooses queues over ordinary path. Does it have the same effect as removing it?

**Comment by PFCKrutonium** [comment]
Would it help anyone if I uploaded a Video to Youtube and linked it, showing the difference?
