### ISSUE TITLE
RCT1 object source filters from #7106 are not functional

### ISSUE THREAD

**Issue by Umdlye** [OpenRCT2/OpenRCT2#7204]
**OS:** Windows 10 (x86-64)
**Version:** 0.1.2
**Commit/Build:** d5d9441

#7106 
![capture](https://user-images.githubusercontent.com/11657101/36501913-ba77f52a-1748-11e8-8254-85306fb90170.PNG)

**Comment by mrtnptrs** [comment]
Are you sure you pointed OpenRCT2 to the installation directory of RCT1? (As those filters you enabled all filter objects from RCT1)

**Comment by Gymnasiast** [comment]
@mrtnptrs Has nothing to do with that.

**Comment by mrtnptrs** [comment]
@Gymnasiast Just tested it myself (didn't think you would response so fast XD): indeed, only the RCT1 filters and its expansions don't work.

**Comment by Horsti12** [comment]
![filters openrct2](https://user-images.githubusercontent.com/12634026/36505331-71ac1230-1753-11e8-8917-9e48ba3ce48e.PNG)
For me the filters still work properly on d5d9441

**Comment by Gymnasiast** [comment]
@Horsti12 It most likely still works for you because you haven't regenerated your object cache.

**Comment by Gymnasiast** [comment]
Ugh, why does Github close issues _in another repository_?!

**Comment by IntelOrca** [comment]
Because you wrote `fix OpenRCT2/OpenRCT2#7204`

**Comment by Gymnasiast** [comment]
I know what I wrote, my point is that Github should not autoclose issues if I write that in _another repository_.

**Comment by IntelOrca** [comment]
Yes it should.
