### ISSUE TITLE
Current value of "Distance and Speed" field added to every string in Shortcut Keys menu, if Russian is a current language

### ISSUE THREAD

**Issue by alex-0xFF** [OpenRCT2/OpenRCT2#7208]
**OS:** Windows 10
**Version:** 0.1.1
**Commit/Build:** 4601265
&
**Version:** 0.1.2
**Commit/Build:** d5d9441

In Shortcut Keys menu there is excess addition of current value of "Distance and Speed" field. Only if Russian language selected.

**Steps to reproduce:**
1. Set Russian as current language
2. Open Shortcut Keys menu

**Screenshots / Video:**
![2018-02-22 17_42_26-openrct2](https://user-images.githubusercontent.com/9460684/36545520-25f0363a-17fa-11e8-8ac9-1d033a49cd64.png)
![2018-02-22 17_42_52-openrct2](https://user-images.githubusercontent.com/9460684/36545527-28a09fc8-17fa-11e8-94af-b3e47b5c9b7b.png)

**Comment by AaronVanGeffen** [comment]
This happens because `STR_SHORTCUT_ENTRY_FORMAT` (`STR_2781`) is set incorrectly in ru-RU.txt:
```
STR_2781    :{STRINGID}:{MOVE_X}{195}{STRINGID}{STRINGID}
```
Should be:
```
STR_2781    :{STRINGID}:{MOVE_X}{255}{STRINGID}
```

Feel free to PR the fix to the Localisation repo. :-)
