### ISSUE TITLE
hang when loading indiana jones park

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#7209]
sorry, I accidentally hit enter in the title field. I will fill in the rest of the report when I have the chance.

**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.1.1]
**Commit/Build:** [e.g. 426e106]

https://www.nedesigns.com/park/31/indiana-jones/

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by janisozaur** [comment]
Regression from https://github.com/OpenRCT2/OpenRCT2/pull/7139 or https://github.com/OpenRCT2/OpenRCT2/pull/7162

**Comment by duncanspumpkin** [comment]
spatial index of the file is broken.
