### ISSUE TITLE
Land tile smoothing occurs with edge tiles

### ISSUE THREAD

**Issue by YoloSweggLord** [OpenRCT2/OpenRCT2#7210]
**Version:** 0.1.2
**Commit/Build:** Develop d5d9441

With landscape smoothing turned on, the hidden edge tiles (which are grass by default and cannot be changed with landscape tools) will blend with the 'apparent'(visible) edge tiles at the same height. This looks quite odd. Ideally, the drawing engine should implement a check to disable blending between an invisible edge tile and a visible tile.

**Steps to reproduce:**
1. Turn on 'landscape smoothing' in the Options menu on the second tab
2. Lower one of the visible edge tiles down to the minimum height and paint it with a blendable texture. The tile will have a visible strip of grass blending next to the invisible tile.

**Screenshots / Video:**
![once upon a time in america 2018-02-22 14-37-10](https://user-images.githubusercontent.com/19209095/36563299-49ceeb84-17df-11e8-9d63-0e37dec1a8d5.png)

**Comment by magnusg** [comment]
To my knowledge this is a bug of the original RCT2 and not a bug from OpenRCT2.
Would still be nice if this could be fixed, even though I can only imagine very few cases where this will be bothersome in the game.
