### ISSUE TITLE
sprite dithering on import not working

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#7214]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.1.1]
**Commit/Build:** [e.g. d5d9441]

This wiki is out-of-date:

https://github.com/OpenRCT2/OpenRCT2/wiki/Sprite-compiler

Specifically, it does not accept flags to specify dithering method. I would like to use the dithering feature to convert truecolor images to the RCT2 palette for custom objects.

**Comment by xp4xbox** [comment]
I believe its uses json now. I had this problem last year right when they changed it. I just used an older commit.

**Comment by AaronVanGeffen** [comment]
> I believe its uses json now

Only for the generation of g2.dat. I think @spacek531 is talking about generating sprites for DAT objects?

**Comment by Gymnasiast** [comment]
The page describes how you can change the dithering method used when creating g2.dat. It hasn' t got to do with JSON, as this is passed as a command line argument.

Also, it looks like Kelson wants to use the g2 generating code to dither his images correctly, so he can use them for other purposes.

**Comment by ThomasdenH** [comment]
I have implemented this functionality. The relevant code has since been moved to [cmdline/SpriteCommands.cpp](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/cmdline/SpriteCommands.cpp). This is where the global variable `gSpriteMode` resides that is referenced in (CmdlineSprite.cpp)[https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/CmdlineSprite.cpp].

**Comment by ThomasdenH** [comment]
Ah, the modes have been renamed:

* `-m 0` is now `-m default`
* `-m 1` is now `-m closest`
* `-m 2` is now `-m dithering`

Hopefully that should solve the problem!

**Comment by ThomasdenH** [comment]
The wiki has been updated to reflect this change, so this issue can be closed.

**Comment by Gymnasiast** [comment]
I think it should be the other way round: OpenRCT2 should be fixed to use `default`, `closest` and `dithering` again.
