### ISSUE TITLE
Errors when building rides

### ISSUE THREAD

**Issue by austindaut27** [OpenRCT2/OpenRCT2#7215]
**OS:** macOS
**Version:** 0.1.2
**Commit/Build:** aba97e4 (current launcher version, I don't know the version that this error happened on)

Kind of a weird one, but I was playing Dynamite Dunes and trying to build a premade coaster in a certain spot. I kept getting errors that I couldn't build the ride. Sometimes the error message would say "Cannot build x here, land not owned by park!" even though the ride outline was totally in the park. Other times it would randomly select guest thoughts and say they were in the way. For example, "Cannot build here, 'I haven't finished my drink!' is in the way!". I took a screenshot of it - link is below.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Unknown

**Screenshots / Video:**
https://imgur.com/a/WXwPc

**Save game:**
Unfortunately I didn't save, so I don't have a save file

**Comment by Gymnasiast** [comment]
We will really need a set of steps to reproduce or a broken save in order to be able to solve this.

**Comment by austindaut27** [comment]
Ok. If anything like it happens again, I'll do my best to write down what I did and get a save. Thanks!
