### ISSUE TITLE
Duplicate code.

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#7226]
https://github.com/OpenRCT2/OpenRCT2/blob/269f398dd21cfaefa78eb5b12dd14648a799216d/src/openrct2/ride/transport/MiniatureRailway.cpp#L1329

is a duplicate of

https://github.com/OpenRCT2/OpenRCT2/blob/269f398dd21cfaefa78eb5b12dd14648a799216d/src/openrct2/ride/TrackPaint.cpp#L1651

and should be merged into one.

**Comment by devlontecron** [comment]
line 1329 in MiniatureRailway.cpp no longer exist in the latest code base. this can be closed(?)
