### ISSUE TITLE
Hyper-Twister Cannot Do Vertical Slopes

### ISSUE THREAD

**Issue by GigaG11** [OpenRCT2/OpenRCT2#7233]
**OS:** [Windows 10]
**Version:** [0.1.2]
**Commit/Build:** [8069a04]

The Hyper-Twister has, for a long time, been unable to do vertical slopes in OpenRCT2 despite being able to in RCT2. While switching the choosing vehicles as RCT1 option used to allow a path around this, I cannot use that option now. Therefore, hyper-twisters cannot have vertical slopes now despite being able to have them in vanilla RCT2.

- [ N ] Reproducible in RCT2 (vanilla)?
- [ Y ] Multiplayer? (Also occurs in SP, if memory serves)

1. Build Hyper-Twister Coaster
2. Make steep slope
3. There is no vertical slope button as there was in RCT2 Vanilla and RCTC.

**Comment by GigaG11** [comment]
Possibly related bugs also seem to restrict the Hyper-Twister and Hyper-Coaster from having Boosters

**Comment by Gymnasiast** [comment]
> Possibly related bugs also seem to restrict the Hyper-Twister and Hyper-Coaster from having Boosters

Those are not bugs. That is deliberate. I can't think of any Hyper-Twister or Hyper Coaster with boosters.

**Comment by GigaG11** [comment]
OK. I just found the boosters useful with Hypers in the past.

**Comment by Gymnasiast** [comment]
There is a cheat for it, though.
