### ISSUE TITLE
Request: "same price throughout park" box for all rides

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#7234]
The shops have a "same price throughout park" checkbox that automatically sets the price of all of that kind of shop to the same price, which is very useful. I often build very industrial parks with sometimes as much as 100 of the exact same coaster, and raising the price for all of them separately can be tedious. If there was the same option for all rides, it would save a lot of time in industrial parks. 
![bumbly bazaar 2018-03-06 10-45-57](https://user-images.githubusercontent.com/25930360/37025588-683780e4-212c-11e8-91ff-3b49f15752c9.png)
![six flags 2018-03-06 10-46-30](https://user-images.githubusercontent.com/25930360/37025590-69c6f5c0-212c-11e8-8559-15e9fa4e9090.png)

**Comment by Gymnasiast** [comment]
Plug-in stuff, AFAIC.
