### ISSUE TITLE
Unable to connect to any server (Disconnected: Connection Closed)

### ISSUE THREAD

**Issue by iluvparks** [OpenRCT2/OpenRCT2#7236]
**OS:** Windows 7 x64
**Version:** 0.1.2
**Commit/Build:** 2c6804f

every time I try to conect to any server, and the map loads, I get disconnected: connection closed. I've tried various servers, and everytime I get "Disconnected connection closed." Anti virus is allowing the program, so is the firewall. uninstalled and reinstalled, same issue. Before I can even connect, I get the waiting  cursor, and the game briefly freezes and thhen immediately, I get "Disconected: Connection Closed". I've never had this issue before. When I last played the game about 2 weeks ago, I didn't have the problem. Could a recent installation of a printer driver or printer software cause this?

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**
1.  Go to multiplayer
2.  Connect to any server

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by Broxzier** [comment]
Assuming you use the launcher, try again with the _openrct2.com_ file in _Documents/OpenRCT2/bin_, and check if there anything printed to the output window when it happens. Post the output here.

**Comment by iluvparks** [comment]
Doesn't seem like there is anything of use there. But all I get is:

INFO[network\Network.cpp:226<Network: :BeginClient>]: Connecting to 192.24.89.115:11753

The IP address varies based on what server I connect to. I get nothing when I get the error, however, I get the above output (again IP address is based on the server) when I try to connect to a server.

**Comment by tupaschoal** [comment]
Probably has been solved in the meantime. Please reopen if you're still facing problems
