### ISSUE TITLE
Feature request: Exploding balloons and ducks

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#7237]
The title says it all 😛 Instead of popping or quacking, the balloons or ducks explode when you click them if this cheat is enabled. Implementing this would mean a big improvement in the quality of OpenRCT2, and may anger PETA.

**Comment by Liampie** [comment]
I would absolutely love this.

**Comment by Gymnasiast** [comment]
I've seen of lot of inane feature requests in 3.5 years, but I still didn't expect this. This can be implemented as the `My mother didn't love me, so everything must DIE` plug-in when we finish the plug-in system.

**Comment by Broxzier** [comment]
For the time being it'll be fun to have this an Easter Egg setting from OpenRCT2, maybe it should only work when players have a certain value set in config.ini for example. The implementation is very simple, and once the plug-in system is ready there needs to be some kind of hook there anyway, so it can be replaced.

```
    if (gConfigGeneral.exploding_balloons)
    {
        audio_play_sound_at_location(SOUND_BALLOON_POP, x, y, z);
    }
    else
    {
        audio_play_sound_at_location(SOUND_CRASH, x, y, z + 12);
        sprite_misc_explosion_cloud_create(x, y, z + 14);
        sprite_misc_explosion_flare_create(x, y, z + 14);
    }
```

**Comment by Gymnasiast** [comment]
Anyone interested in implementing features like this: they would be a good fit for my https://github.com/Gymnasiast/everything-must-die plug-in. Of course, some hooks might need to be added to OpenRCT2 first.

**Comment by ZehMatt** [comment]
I guess we can close this now
