### ISSUE TITLE
Feature request: Duck invasion cheat

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#7238]
To assist in creating objects to explode for #7237 it would be helpful if we could spawn ducks at will, just like we can spawn guests. Not sure if PETA would like this or hate this. I think they would be neutral.

**Comment by Gymnasiast** [comment]
I'm getting a bit tired of all the silly feature requests you're opening.

**Comment by deurklink** [comment]
Not planning on submitting any more feature requests for now, these two just seemed very popular with anyone I asked about it :grin:

**Comment by Gymnasiast** [comment]
The ability to spawn ducks has since been implemented.
