### ISSUE TITLE
The remove Guest cheat option crashes the game on some maps

### ISSUE THREAD

**Issue by Jochem228** [OpenRCT2/OpenRCT2#7239]
- [ no] Reproducible in RCT2 (vanilla)?
- [no ] Specific to multiplayer?

**Steps to reproduce:**
1. Open the maps
2. Press the remove guest cheat
[The OpenRCT2 Group Park 7.96.zip](https://github.com/OpenRCT2/OpenRCT2/files/1789776/The.OpenRCT2.Group.Park.7.96.zip)

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by deurklink** [comment]
Hmm we probably need a guard for when peep index is SPRITE_INDEX_NULL
