### ISSUE TITLE
Feature: Extra Zoom Level & Independent UI/Game Scaling

### ISSUE THREAD

**Issue by Jademalo** [OpenRCT2/OpenRCT2#7241]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** ad4e50d

When playing OpenRCT2 on a more modern display, displaying at 1x pixel scaling causes both the game and UI to appear extremely small. There is a feature that allows scaling to be changed, and setting the scaling to 2x displays the game in a similar manner to when it was new.

While the game looks fantastic at 2x scaling, there is one major shortcoming of this - When zooming out, you lose a substantial amount of fidelity.

To remedy this, I have two suggestions.
The first is to split the UI scaling and the game world scaling into two separate options. This would allow the player to have a more reasonably sized UI on modern resolutions, but be able to display the game world at an unscaled pixel perfect resolution.
The second is to add an extra zoom level, x2. This would mean that when the game was set to 1x scale, you would be able to zoom in an extra notch in order to double each pixel and effectively give you the 2x scaled mode. The biggest advantage of this however would be on zooming out by a single step, you wouldn't lose fidelity like you do at present.

I have no idea how feasible this would be, but after playing for the last few months the main thing I find myself wanting is the ability to zoom out on occasion without losing fidelity. I still instinctively try to zoom out to see more sometimes, but everything becomes a blocky mess.

![2x Normal](https://user-images.githubusercontent.com/386846/37124966-726c4608-2262-11e8-89c5-0cb53b099296.png)
![2x Zoomed Out](https://user-images.githubusercontent.com/386846/37124976-77920d84-2262-11e8-916b-3e0a989554b2.png)
![1x Normal](https://user-images.githubusercontent.com/386846/37124980-79c2b662-2262-11e8-8c9a-ece7b5178098.png)
![1x Zoomed Out](https://user-images.githubusercontent.com/386846/37124983-7b5c64c8-2262-11e8-8ece-858c2135c08a.png)

**Comment by duncanspumpkin** [comment]
Both of these issues/solutions are already planned/discussed. We've been trying to uncouple the ui from the viewport for 3 years.
