### ISSUE TITLE
"Own ALL Land" Cheat is broken

### ISSUE THREAD

**Issue by TruePCs** [OpenRCT2/OpenRCT2#7251]
Operating System
	Windows 10 Pro 64-bit
CPU - Intel Xeon W3530 @ 2.80GHz	104 °F
RAM - 12.0GB Triple-Channel DDR3 @ 533MHz (8-8-8-20)
Motherboard - ASRock X58 Extreme (CPUSocket)	103 °F
Graphics - SONY 32" TV (1920x1080@60Hz) (Main), Acer 24" P243W (1920x1200@59Hz), 4095MB NVIDIA GeForce GTX 1050 Ti (Gigabyte)	103 °F
Storage - 931GB Seagate (SATA) 94 °F, 931GB Seagate (SATA) 76 °F, 111GB Solid State Disk (SSD) 87 °F, 931GB Seagate (SATA) 78 °F, 465GB Seagate (SATA) 87 °F, 279GB Maxtor (SATA)	81 °F

Steam version of RCT's, everything is up to date, RCT, Windows, etc
0.1.2 build 88af2d3

For some reason in the latest builds the "Own ALL Land" Cheat is broken.  In older versions like "OpenRCT2-0.1.2-develop-a5da22d-windows-x64" it works, but not in the newest one or that least the last one I tried a few minutes ago of a few back.  Uninstall has no effect, still will not work with newer versions.  Have not whittled down the exact build that this stops working but can when I have time.

Reproducible in RCT2 (vanilla)? NA
Specific to multiplayer? I only use Single

**Steps to reproduce:**
1.  Install new version, "Own ALL Land" Cheat will **not** work
2. Install old version and "Own ALL Land" Cheat does work

**Comment by duncanspumpkin** [comment]
Describe does not work. Does it do nothing. Does it do something different.

**Comment by Broxzier** [comment]
Looks like 45e892e5b59dbcf3064736314a6604fba30fca79 caused this. It loops over the first row of tiles, but doesn't reset X to 32 for the second row, so all other rows are skipped. You can see this behaviour, because one side of the map will get owned.

I have a fix ready, just making sure said commit doesn't have other side effects first.

**Comment by TruePCs** [comment]
dunkinspumpkin, sorry for not elaborating. Clicking button seems to have no effect at all.  Broxzier, glad someone else sees the issue, thanks for quick work.
