### ISSUE TITLE
Update changelog for 0.1.2

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#7279]
Changelog has not been updated in a while and should get updated for upcoming 0.1.2 release

**Comment by AaronVanGeffen** [comment]
While I agree we should give it a good once-over… Are any particular issues missing? We generally only add differences from the last release, so fixes addressing recent regressions aren't listed.

**Comment by Gymnasiast** [comment]
It was updated 14 hours ago. Do you mean it lacks stuff?

**Comment by janisozaur** [comment]
> Do you mean it lacks stuff?

We usually find things not mentioned in changelog that should've been and it's been quite some time since previous release, so let's just go over the commits merged since then and add any relevant stuff.
