### ISSUE TITLE
Damaged save does not properly print a warning

### ISSUE THREAD

**Issue by BunkyBoss** [OpenRCT2/OpenRCT2#7280]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.1.1]
**Commit/Build:** [e.g. 426e106]

I tried to load my save game but The game said "assertion failed" and "Encountered zero-sized chunk"

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

[King's Beach 2 (2).zip](https://github.com/OpenRCT2/OpenRCT2/files/1809379/King.s.Beach.2.2.zip)

**Comment by Gymnasiast** [comment]
Please fill in the OS/Version/Commit-Build fields.

**Comment by AaronVanGeffen** [comment]
When I open the save on edbca00d6674256825318aee0254f737f1dfab85, I do not get an assertion failure, but I do get an "Corrupt RLE compression data." error in my console.

**Comment by Gymnasiast** [comment]
Do you get the 'File contains invalid data' warning in the GUI?
(I think that has been broken for a long time.)

**Comment by AaronVanGeffen** [comment]
Good point. No, the game resets the title screen without any feedback…

**Comment by janisozaur** [comment]
Could it perhaps be related to the server disconnects we've been hearing of?

**Comment by RT12Productions** [comment]
I also have been getting **assertion failed** and **encountered a zero-sized chunk** errors in my OpenRCT2 lately...  even after I do an update!!

**OpenRCT2 version 0.1.3
development build 124fb0d
provided by AppVeyor
encountered a zero-sized chunk!**

**failed to allocate 1bff5040 (unsigned character) to have 0 bytes**

**Comment by Gymnasiast** [comment]
Closing this since the OP has not provided the needed information and seems to be gone.

@RT12Productions You have your own issue report.
