### ISSUE TITLE
Disable MSVC's /LTCG for tests.exe

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#7281]
**OS:** Windows
**Commit/Build:** edbca00

AppVeyor uses `/LTCG:incremental` for all built executables, including `tests.exe` (see https://ci.appveyor.com/project/IntelOrca/openrct2-ject9/build/0.1.2.13269/job/xcp9atneou0tsni5#L1041). I think this is unnecessary for tests and only wastes time: generating this code takes 40 seconds and removing `/LTCG` might substantially cut that time down.

https://github.com/OpenRCT2/OpenRCT2/commit/d93a07a58d50a50550a606ea58321f60fa627385 removed similar option for debug configuration, but there is no such entry in the repository anymore.

**Comment by IntelOrca** [comment]
I don't think I can do this because libopenrct2 and libopenrct2ui are compiled with `/GL` (Whole Program Optimization) which requires LTCG.
