### ISSUE TITLE
Rotating a maze track rotates each piece individually

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#7284]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** edbca00

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Build a maze and select any track you may have
2. Press Z or click the rotate button to rotate the maze
3. Observe how each piece gets rotated, rather than the entire track

Paths and scenery does get transformed properly.

**Screenshots / Video:**
![2018-03-14_13-41-11](https://user-images.githubusercontent.com/9705046/37403175-3d643b10-278e-11e8-9639-a78b6c4d9f47.gif)

**Comment by AaronVanGeffen** [comment]
Probably a regression of #6966. Tagging @ZehMatt

**Comment by janisozaur** [comment]
Regression from 45e892e5b59dbcf3064736314a6604fba30fca79

**Comment by janisozaur** [comment]
Ping @Gymnasiast
