### ISSUE TITLE
Stupid handyman

### ISSUE THREAD

**Issue by Servuc** [OpenRCT2/OpenRCT2#729]
Hi,

This is a very good idea, this game.
Just i've find that handyman clean the dustbin : 

----O-----+
     X        | Coaster exit
----O-----+

The O are the dustbin, and X the handyman.
Here the the handy man is a the end of a road (the next square is the exit) with dustbins.
And the handyman clean the right, the left, the right, the left ... and doesn't wash vomit :/

Have a good day, 
Sorry for my bad english

**Comment by duncanspumpkin** [comment]
I can't reproduce this could you provide a save game with the handyman problem.

**Comment by RM87** [comment]
It might happen when your handyman does have footprints set on the road tile but not on the coaster exit tile. Some people vomit already on the exit tile and this vomit  can graphically appear to be more on the road tile than the exit tile.

**Comment by Servuc** [comment]
I've check the handyman was in his footprints, but i've seen that others handymans do the same.
And @duncanspumpkin you have probably right, i've save sometimes before discover this bug.

Moreover, if the handyman was move with the cursor (by me), he does his works without problem.

**Comment by mrtnptrs** [comment]
Is this really a bug then? So, when the exit tile is not selected, the handyman doesn't clean there, isn't that just logic? :)
