### ISSUE TITLE
Update title sequence for 0.1.2

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#7292]
For tracking purposes only. TS PR in https://github.com/OpenRCT2/title-sequences/pull/6

Tag @spacek531.

**Comment by spacek531** [comment]
I originally wanted to include credits on the screen but I doubt I can write that feature before the rest of the v0.1.2 milestones are met. How the PR stands right now is good and I can't wait to see it in the next stable.
