### ISSUE TITLE
Custom footpaths invisible / Edit: Park entrance invisible too

### ISSUE THREAD

**Issue by TonyLaV** [OpenRCT2/OpenRCT2#7294]
**OS:** [e.g. Windows 7]
**Version:** [e.g. 0.1.2]
**Commit/Build:** [e.g. f311fb1]

The footpath is not visible. When i load my savegame into scenario editor the footpath is visible. After that the footpath is also visible when i play the map. When i close OpenRCT2 and load the map then, the footpath is not visible again. Check Screenshot

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1.  CANT UPLOAD SAVEGAME ITS 33MB BIG

![harambe in gefahr 2018-03-16 16-44-37](https://user-images.githubusercontent.com/33175850/37530675-669a46ac-293a-11e8-8285-63d62b2bd1be.png)
![harambe in gefahr 2018-03-16 16-44-57](https://user-images.githubusercontent.com/33175850/37530682-694cd090-293a-11e8-8bd9-a02c49271d96.png)

![harambe in gefahr 2018-03-16 16-45-43](https://user-images.githubusercontent.com/33175850/37530884-ecb20612-293a-11e8-9776-dfdc8dfc8636.png)

**Comment by AaronVanGeffen** [comment]
Does the issue only occur when you're using this saved game? It looks like there is some corruption going on in rendering the custom footpaths you're using.

I cannot reproduce the issue locally, so if you could upload your save somewhere else, that'd be much appreciated. (I would suggest saving it without any custom objects, but the issue might be related to some of them...)

**Comment by TonyLaV** [comment]
Ok here it is 

https://ufile.io/weaor

**Comment by TonyLaV** [comment]
The issue occur in every savegame which has custom footpaths. They are only visible in scenario editor but when i try to play the scenario they are invisible again.

**Comment by Broxzier** [comment]
Are there any warning printed to the console (the black window) when you start the game or when load those saves? You can open the openrct2.com file in the bin folder to see the console.

**Comment by AaronVanGeffen** [comment]
Here's what the attached save looks like to me. No console warnings. Which begs the question, how did you replace the paths and entrance, if not through actual custom objects?

![harambe in gefahr 2018-03-18 13-30-38](https://user-images.githubusercontent.com/604665/37565816-ae31ed72-2ab0-11e8-93e8-d8f8c91614b5.png)

**Comment by TonyLaV** [comment]
There is no warning or error. The custom objects where included in the object selection in scenario editor.
I didnt download anything or replaced anything. 

When i join any server with custom objects i can see them. But when im playing on my own server or offline there are still invisible.

**Comment by AaronVanGeffen** [comment]
Could it be that these custom objects have replaced the original data files?

**Comment by Broxzier** [comment]
Upon loading the saved game it's printing a lot of these lines for me:
```
ERROR[c:\projects\openrct2-ject9\src\openrct2\drawing\image.cpp:214 (gfx_object_allocate_images)]: Reached maximum image limit.
```
The paths also appear corrupt for me.

**Comment by TonyLaV** [comment]
No i dont think sp because the original paths are visible and when i load the scenario or the savegame in scenario edior everything looks like it should. 

After loading the file into scenario editor the savegame looks how it should. But when i close the game it is how it was before.

**Comment by Broxzier** [comment]
It looks like the objects you had selected all together exeeded the image limit. When removing all unused objects from the list, the park appears correctly when reloaded:

[harambe-in-gefahr-2.zip](https://github.com/OpenRCT2/OpenRCT2/files/1822705/harambe-in-gefahr-2.zip)

To prevent this behaviour in the future, there should be a check to predicted wether or not the new object will exceed the limit.

**Comment by TonyLaV** [comment]
Ok thanks.

But why did everything work fine before ? I have this problem since the youngest updates

**Comment by Gymnasiast** [comment]
> But why did everything work fine before ? I have this problem since the youngest updates

Can you find out which version exactly? That would help us a lot in determining the cause.

**Comment by TonyLaV** [comment]
I can try but im using OpenRCT2 Launcher..

The save removed nearly all rides. I have only 32 from 128 left :(

**Comment by TonyLaV** [comment]
How can i download versions older than 5 days ?

**Comment by AaronVanGeffen** [comment]
You can use commit ids to get builds from OpenRCT2.org. Here's one for [72114ec](https://openrct2.org/downloads/develop/72114ec6e8ac92caed6a870bcb080cab9af1ba42), released two weeks ago.

**Comment by TonyLaV** [comment]
Sorry but i dont understand what you mean. I installed this file but the visual bug is still there. I installed the  realease build too but the bug is there too. Can you send me a link for a version from 25.02 ?

**Comment by AaronVanGeffen** [comment]
If the bug is present in both v0.1.1 and the 8069a04 build, I find it hard to believe the issue wasn't present a week before.

You could try [57be3b44](https://openrct2.org/downloads/develop/57be3b44), which was built on February 25.

**Comment by TonyLaV** [comment]
Ok i dont get it. I created this map 1 week ago with a friend together. He played it with me online on different pcs and everything worked fine. I wanted to play this map again with my friend this weekend but the footpaths were invisible.

With the version from 25.02 i still have invisible paths ..

And i dont understand why the paths are visible when i first enter the scenario editor and then the saved game.

**Comment by TonyLaV** [comment]
When i enter scenario editor and go back to main menu the rides have a visual bug too. I cant make a screenshot at the main menu

**Comment by Gymnasiast** [comment]
It has been almost 4 years, do you still have this issue?

**Comment by TonyLaV** [comment]
I cant say i dont have this save anymore , im sorry
