### ISSUE TITLE
Error mismatch does not specify client's own network version

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#7299]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.1.1]
**Commit/Build:** [e.g. 426e106]

When attempting to connect to a multiplayer server that is not running the same version as your own, the server's network version is given, but not the client's. It would be handy to know, because my version was behind when I thought it was ahead; the launcher failed to update my game to the most recent version.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by janisozaur** [comment]
Client's network version is shown in the multiplayer window.

**Comment by AaronVanGeffen** [comment]
Your network version is shown in the server list:
![screenshot_20180318_102646](https://user-images.githubusercontent.com/604665/37564468-de618a44-2a96-11e8-835a-a6c9af0b8cd3.png)

What network version other servers are using is indicated when hovering over the green/red status indicators.
