### ISSUE TITLE
Visual glitch with virtual floor near map edges

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#7303]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** af8adfeb406492e775ac18f9f0abcc6e33cd17bf

Pressing Ctrl or Shift while having any tool active that doesn't place new tile elements shows the virtual floor at zero height (I assume) causing a visual glitch near the map edges.

**Steps to reproduce:**
1. Activate any tool that doesn't place new tile elements (tool tested: land, water, scenery removal, tile inspector, buying land)
2. Go to the map edge where you can see the outer walls
3. Hover over a tile near the edge and press Shift or Ctrl

**Screenshots / Video:**
![https://user-images.githubusercontent.com/9705046/37565510-f3d7935a-2aaa-11e8-8659-f66143c80346.png](https://user-images.githubusercontent.com/9705046/37565510-f3d7935a-2aaa-11e8-8659-f66143c80346.png)

**Comment by ZehMatt** [comment]
Is the virtual floor even supposed to visible at this point?

**Comment by AaronVanGeffen** [comment]
No, the land tool shouldn't activate it.

**Comment by Broxzier** [comment]
This is also visible when the surface is at the lowest possible height and when using the cut-away view.

It can also be reproduces when pressing Shift or Ctrl when holding an object that may not be raised (like trees).

![forest frontiers 2018-03-27 22-05-55](https://user-images.githubusercontent.com/9705046/37992095-13b896b2-320b-11e8-9734-5d5b64e7f9c6.png)
