### ISSUE TITLE
Park rating suddenly jumps to 0 with too many coasters with high ratings

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#7305]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** e70d201

I was building a park with the goal of getting a very high park value. To do this I built a lot of small and intense coasters because they give the most value for your buck. Suddenly, my park rating jumped from 999 to 0 without any explanation. I tested a few things and found out that if I removed the stats from one of my coasters, my rating jumped back to 999. I know you need a certain total intensity+excitement rating in your park to not get a rating penalty, so my guess is that I had too much stats and it overflowed or something. [Here](https://openrct2.org/forums/topic/2798-guide-how-to-calculate-park-rating/) is Deurklinks guide to the park rating which includes the bit about total ride stats.

I'm not sure if this happens in vanilla because the game crashes when I try to load the park.

**Steps to reproduce:**
1. Download the save
2. Remove the stats from one of the red coasters by toggling the chain lift or number of laps
3. Watch the park rating jump to 999
4. Retest the coaster to see the rating go to 0 again

**Screenshots / Video:**
![diamond heights 2018-03-18 15-09-38](https://user-images.githubusercontent.com/25930360/37566869-1f0941ea-2abf-11e8-97b3-676ca3c3e10a.png)

**Save game:**
[SP Diamond Heights 2.zip](https://github.com/OpenRCT2/OpenRCT2/files/1822733/SP.Diamond.Heights.2.zip)

**Comment by Gymnasiast** [comment]
Park rating != Park value.

In any case, this smells like an overflow.

**Comment by LordMarcel** [comment]
I typed value instead of rating a few times by accident, which is fixed now.
