### ISSUE TITLE
Triple Thrillpack not showing open in Open RCT2

### ISSUE THREAD

**Issue by RioMonkey** [OpenRCT2/OpenRCT2#7309]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.1.1]
**Commit/Build:** [e.g. 426e106]

I have a hard copy of RCT2 installed on my desktop and the GoG triple thrill pack installed but when i play openRCT2 they are not there. How can i get them in openRCT2

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by AaronVanGeffen** [comment]
Where exactly is the GOG game located on your system, and what is the game path set to in OpenRCT2?

**Comment by RioMonkey** [comment]
The icon is in a folder for all of my RCT stuff but GOG is on desktop in no
folder. I have no clue about the files or program files

**Comment by RioMonkey** [comment]
The icon is in a folder for all of my RCT stuff but GOG is on desktop in no folder. I have no clue about the files or program files

**Comment by Patrik356b** [comment]
Right click on the icon of RCT2 and select properties. You will now be able to see where RCT2 is located.

**Comment by RioMonkey** [comment]
ok i found the location: C:\....
