### ISSUE TITLE
Request: Freeze Staff/Guest Button

### ISSUE THREAD

**Issue by SensualEthiopianPoliceBrigade** [OpenRCT2/OpenRCT2#7316]
Similar to the walk fast/slow option for staff. The ability to freeze individual staff members and guests from their info boxes without having to go through the debug menu would be convenient.

**Comment by AaronVanGeffen** [comment]
How is this different from pausing the game?

**Comment by SensualEthiopianPoliceBrigade** [comment]
Because you can leave them frozen while the game runs. Frozen staff and guests are often used as scenery in many parks

**Comment by Broxzier** [comment]
For staff there is the command `staff set energy <staff ID> 0` to freeze an individual staff member. With `staff list` you can find the staff ID. This command could be renamed to `peep set energy` command instead so that it can be used for peeps too.

**Comment by SensualEthiopianPoliceBrigade** [comment]
I'm aware of this, but this is just a way to make the process easier and faster

**Comment by xp4xbox** [comment]
Arbitrary things like this should be kept in the console until the plugin system is implemented in my opinion.

**Comment by Liampie** [comment]
What do you mean with 'arbitrary'? I don't see why this should be buried in the console, while a lot of other stuff can be found in the cheats menu, or the rides menu/map menu after ticking a box in the cheats menu. For convenience, can't it just all go through the cheats menu? Isn't that what a cheats menu is for?

**Comment by Broxzier** [comment]
> @Liampie: Isn't that what a cheats menu is for?

Cheats are aimed at casual players trying to complete scenario objectives for example. Setting the staff speed is helpful for such a thing, while setting the invidual speed of a guest in the park is not. This would fit much better as a console command.

**Comment by thiebert** [comment]
Why not a button/dropdown on the staff page (toggle-able with a cheat) to set the speed of that particular staff?

**Comment by SensualEthiopianPoliceBrigade** [comment]
@Broxzier But then that beg's the question: Why is arbitrary ride types there, casual players can't make much use of that?

**Comment by Liampie** [comment]
Are you sure, Broxzier?

![kip](https://user-images.githubusercontent.com/19242088/37728208-faa9527c-2d39-11e8-8680-63b1b24bb749.png)

**Comment by Broxzier** [comment]
> Why not a button/dropdown on the staff page (toggle-able with a cheat) to set the speed of that particular staff?

That'll cluster up the user interface more than it needs to, reducing the user experience. Considering this is a feature that the majority of the players won't use. The players that will use it can already freeze staff using the console (`staff set energy <staff id> 0`) where looking for the ID will only take a few seconds (`staff list`). Surely if it's worth freezing individual staff members, the time it takes to look up the individual IDs of the peeps is not an issue.

> @Liampie: Are you sure, Broxzier?

Pretty sure. Look at the list you posted, all of those have a benefit to the game other than just aesthetics.

**Comment by xp4xbox** [comment]
Once there is a plugin system, you will be able to customize it how you like.

**Comment by phadd-f** [comment]
If you only want functions in the cheat menu for people that just want to play scenarios without thinking too much of easthetics, than you could easily scrap half of what is there in Liams screen. You don't need to put intamin giga trains on a wild mouse track for example to play out a scenario.

There are so much people playing the game more intense, and who use frozen staff heavily. Lucky we have it in the console, yes, but if you have to freeze like 5 or more staff members it is time consuming and not very handful. Making a button or something like it would make it so much easier and time saving. OpenRCT already made building so much faster, a button for freezing staff/peeps would just be a normal step in the direction you guys were already going.

You might get some normal users discovering the function and using it too.

**Comment by thiebert** [comment]
@Broxzier it's no more cluttered than the arbitrary ride type change drop down on rides. I don't really understand the reluctance to this, especially since increased staff speed can be included in the drop-down, which does have a tangible benefit to many users.

**Comment by thiebert** [comment]
To be clear, I'm suggesting: 
1.) a checkbox in the cheats menu to activate #2 and
2.) a dropdown in the individual staff window to set the speed for that staff. Could be "Double", "Normal", "Half", and "Freeze"

This allows scenario/mega-park type builders to set handymen and mechanic speeds higher to help them fix/clean areas faster, while keeping things like Entertainers from being too energetic and bouncy when used in themed areas. This also allows the NE crowd to freeze staff for aesthetic purposes. 

It doesn't increase the UI clutter, except on an opt-in basis from the cheats menu, and even then, in a tasteful way that can match some similar UIs such as the "Arbitrary Ride Type Change" field in a ride's window.

**Comment by RWErct2** [comment]
I want a button, that would be much better.

**Comment by duncanspumpkin** [comment]
This is a perfect thing for being a plug-in. It would be rarely used by normal users and it would be super simple to code.

**Comment by RWErct2** [comment]
@duncanspumpkin what do you mean with normal users?

**Comment by thiebert** [comment]
@duncanspumpkin plugins aren't available yet and there's pretty immediate demand for this from the NE community. I also expressed ways in which "normal" users might want to use the feature. 

There's also precedent for features that "normal" users won't typically use, such as arbitrary ride type changes.

**Comment by SensualEthiopianPoliceBrigade** [comment]
Do we at least have a timeframe as to when plug-ins will be implemented?

**Comment by Gymnasiast** [comment]
@IntelOrca is working on it. There is even some test code. I think he should be able to give you a time frame.

For the record: I think this feature should be a plug-in _eventually_. However, if we're still months from there, I think we _could_ implement it now. OTOH, there is at least a way to do this currently, even if it is a bit cumbersome.

**Comment by janisozaur** [comment]
There's some work already started, but it's anyone's guess when it will end up getting merged. There's a lot of code that needs to be written, reviewed, tested, fixed… and we are still busy with other things.

But as this is of such importance to you to have a button that executes such command, you're welcome to build yourself a version of openrct2 that has it, it's all open source.

**Comment by RWErct2** [comment]
I can't build my own openrct2.

**Comment by duncanspumpkin** [comment]
Its besides the point but you could use the CI's we have setup to build openrct2. All you have to do is fork and commit a change and the CI will handle building it.

**Comment by SensualEthiopianPoliceBrigade** [comment]
I don't know at all what that means. I'd be glad to do it myself but I suggested it because I genuinely don't know anything about code

**Comment by thiebert** [comment]
@RWErct2 I think that was more of a response to me.

@duncanspumpkin I don't think anyone from NE that's commenting here besides myself knows what CI is, or understands how to build the game otherwise.

**Comment by IntelOrca** [comment]
> Frozen staff and guests are often used as scenery in many parks

Other than for the sake of wanting to make a NCSO park, why not just use custom scenery to do it?

**Comment by thiebert** [comment]
@IntelOrca There's limited scenery slots, as I'm sure you know, and having various staff options fill some of those slots is often not an option. Additionally, there's positions and animation frames that one might try to capture, which might multiply the number of objects needed. 

Furthermore, staff names can convey extra storytelling information that objects cannot. 

Finally, freezing staff is generally more simple (with 8cars, with the console command, or with a new feature to handle this) than creating a new object might be for the average user.

**Comment by xp4xbox** [comment]
Fixed? #7329
