### ISSUE TITLE
Research window now shows the name of trains/cars for each ride, instead of the name of the ride itself.

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#7324]
**OS:** Windows 8
**Version:** e.g. 0.1.3
**Commit/Build:** ccb1b33

Research window now shows the name of trains/cars for each ride, instead of the name of the ride itself.

This happens not only for roller coasters, but even for flat rides that have vehicles, like the reverse freefall.

Shops/stalls, scenery, and rides without vehicles (like mazes or mini-golf) still appear in the research as normal.

![amity airfield 2018-03-20 12-58-13](https://user-images.githubusercontent.com/26573303/37679548-74ca23b2-2c3e-11e8-8c61-83663ca8d9d2.png)

- [no] Reproducible in RCT2 (vanilla)?
- [no] Specific to multiplayer?

**Steps to reproduce:**
1. Open research window.
2. Research any ride that has vehicles.

**Comment by Gymnasiast** [comment]
I'm aware of this, yes. It is supposed to be tackled in a research system update.

**Comment by AaronVanGeffen** [comment]
I think the same might be happening in the invention list.

![diamond heights 2018-03-20 23-23-50](https://user-images.githubusercontent.com/604665/37685964-c26e99d4-2c95-11e8-92c8-326efeea6039.png)

**Comment by Patrik356b** [comment]
@AaronVanGeffen 
Little note there: a scenario may have several train types for the same ride unlocked by research

**Comment by AaronVanGeffen** [comment]
@Patrik356b I am aware. It just looks strange if there is no mention of the ride you'll actually be building, though. Perhaps both ride and car types should be mentioned instead.

**Comment by Gymnasiast** [comment]
@AaronVanGeffen That was my plan, and I would have done, if it weren't for those meddling kids... er, strange way the strings in that window work.
