### ISSUE TITLE
When rides are hidden, transparent entrances' colored glass is still visible

### ISSUE THREAD

**Issue by L3P3** [OpenRCT2/OpenRCT2#7327]
**Version:** OpenRCT2, v0.1.3-HEAD
**Commit/Build:** 2ea62fe

I see that in several colors but I don't know it it appears elsewhere.

- [ ] Specific to multiplayer?
- [x] Reproducible in RCT2 (vanilla)?

**Steps to reproduce:**
1. Build a ride, set entrance style to "abstract"
2. Click on the eye and select "hide rides"

**Screenshots / Video:**
![cut](https://user-images.githubusercontent.com/4629449/37710472-0c9917aa-2d0e-11e8-96dc-0ef4933a3967.png)

**Comment by deurklink** [comment]
Same for abstract scenery, when scenery objects are hidden:
![image](https://user-images.githubusercontent.com/6469413/37768881-6c0cfc30-2dcf-11e8-9bae-8e706f628495.png)

**Comment by YoloSweggLord** [comment]
This also occurs with the text on 3D signs. Perhaps both are related?

**Comment by Broxzier** [comment]
![image](https://user-images.githubusercontent.com/9705046/37881224-f2ea1f0e-3094-11e8-8244-4bdd8289e5bb.png)
I'm unable to reproduce this with 3D signs. If you mean banners that you place on paths, those get transparent when enabling See-Through Paths.
