### ISSUE TITLE
Request: Shortcut keys for 'View Path Issues' and 'Cutaway View' view modes

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#7332]
Most of the other view modes have shortcut keys, which I find extremely useful to pop in and out of them whenever it's convenient. 

But I just checked the in-game list of shortcuts, and there are none for these newer view modes. It would be a lot quicker and more convenient if it was possible to turn them on or off without having to go through the menu each time.

Even if they're not assigned a key by default, it would be nice if they were in the list of things that a user can assign key bindings to.

**Comment by xp4xbox** [comment]
I am working on this.

**Comment by Gymnasiast** [comment]
Implemented in #7336.
