### ISSUE TITLE
Request :  Employees are not allowed to cross " Do not enter " sign

### ISSUE THREAD

**Issue by TonyLaV** [OpenRCT2/OpenRCT2#7333]
Would that be possible ?

**Comment by AaronVanGeffen** [comment]
Possible, yes, but I'm curious as to why you'd like to do this, as opposed to tackling this using patrol areas. We try to keep the options to a minimum.

**Comment by TonyLaV** [comment]
Because of that ;

![harambe in gefahr 2018-03-22 20-36-53](https://user-images.githubusercontent.com/33175850/37794141-e8509702-2e10-11e8-88a3-78696db9d28a.png)
![harambe in gefahr 2018-03-22 20-37-00](https://user-images.githubusercontent.com/33175850/37794142-e886645e-2e10-11e8-800e-173ee9f1d852.png)

**Comment by AaronVanGeffen** [comment]
This is why I mentioned patrol areas. I think you should look into using them instead.

**Comment by TonyLaV** [comment]
Yes youre right.
