### ISSUE TITLE
Scenario Editor: Can't add scenario name or park name

### ISSUE THREAD

**Issue by CoasterRider89** [OpenRCT2/OpenRCT2#7338]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** 924aed8 (I believe)

I had this issue in previous builds as well. Tried updating to see if it was fixed and it was not. Once I have gone through and selected all of the objects and editted the terrain in a custom scenario I find this problem. The buttons to change the Scenario's name and to change the Park's name are grayed out and cannot be selected. When I save the scenario I give it a file name. When I go back to the main menu and click Start New Game, the scenario is there, but it is blank, no name appears. If you click on the blank space it opens the scenario with no problem. Anyone know why I can't name the scenario? It's going to get hard to keep track of them with no names appearing...

I can get some screenshots this weekend if they are needed.

**Comment by Patrik356b** [comment]
at least the filename can be seen at the bottom of the window, it helps a little bit.

**Comment by Gymnasiast** [comment]
@Patrik356b Please, do not comment on everything you because you think you should.

**Comment by Gymnasiast** [comment]
Cannot reproduce. I need a set of steps to reliably reproduce this.

Does this happen with scenarios you created yourself, or with vanilla scenarios that you modified?

**Comment by Patrik356b** [comment]
@Gymnasiast shush. in other places you would get bashed for double posting.

**Comment by CoasterRider89** [comment]
After running a few tests, it just seems to be the one scenario in particular that has this issue. Every new scenario I create has the option to change the name. Maybe it's an object I have selected for the scenario, but I doubt that. File must have corrupted or something. Thanks for looking into, sorry to waste your time.

**Comment by Gymnasiast** [comment]
Could you upload that broken scenario nonetheless? I'd like to investigate.
