### ISSUE TITLE
Staff may auto-spawn on guests walking outside of paths

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#7341]
**OS:** [Windows 10]
**Version:** [0.1.3]
**Commit/Build:** [674e094]

When auto placing staff, they will spawn on a random walking guest. I think this was done to ensure that they will always spawn on a valid location reachable by guests. If guests are walking outside of paths however(because of removed paths or broken exits or something else), your staff may also spawn there. I am not sure if this requires fixing or not, but I decided to report this anyway, as this behaviour may not be intended.

In the following video this can be seen at around the 1:50 mark. The guy who made the video didn't notice because he was doing a speedrun, and some of his staff ended up walking in the grass for several years.

[https://www.youtube.com/watch?v=Dw0e9tzLmA8](url)

**Comment by IntelOrca** [comment]
Seems reasonable to disregard guests that are not on a footpath.

**Comment by woshinimen** [comment]
Hello @IntelOrca , I was thinking of doing my first open-source contribution on this project and was wondering if this is an issue that I could address.

**Comment by IntelOrca** [comment]
@woshinimen This is a good issue for someone new to the code base so feel free to look at it.
