### ISSUE TITLE
Please add a cmake option to build shared library instead of a static library

### ISSUE THREAD

**Issue by yurivict** [OpenRCT2/OpenRCT2#7342]

**Comment by janisozaur** [comment]
https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html

**Comment by IntelOrca** [comment]
You can use the official cmake property:
`cmake -DBUILD_SHARED_LIBS=on`

**Comment by yurivict** [comment]
Thanks!
