### ISSUE TITLE
Possible memory leak on headless server

### ISSUE THREAD

**Issue by lunalucadou** [OpenRCT2/OpenRCT2#7351]
**OS:** Ubuntu Linux 16.0404
**Version:** 0.1.3-HEAD
**Commit/Build:** ca17f03

OpenRCT2 slowly eats up more and more memory until the system is unusable and I have to reboot my EC2 instance (kill and pkill can't run because the system cannot allocate memory). After about 15 minutes it the OOM killer cleans it up but after about 10 minutes SSH becomes unresponsive due to low system resources.
I have tried several save files and it happens every time. I can connect and play until it disconnects my client because it runs out of memory.
I used to be able to host 3 headless servers on one system in addition to Nginx and an IRC logger, but I cannot even run 1 OpenRCT2 instance on my t2.micro.
I cannot reproduce this on Windows with the GUI. Only headless servers seem to be affected.

Command used in my systemd service file:
`/usr/share/lunarct2/openrct2 host /usr/share/lunarct2/user-data/save/autosave/current_autosave.sv6 --headless --port 11753 --user-data-path /usr/share/lunarct2/user-data`

- [ No ] Reproducible in RCT2 (vanilla)?
- [ Yes ] Specific to multiplayer?

**Steps to reproduce:**
1. `sudo systemctl start openrct2.service`
2. Wait

**Dump file**

**Screenshots / Video:**

Memory usage shortly before OOM killer took it out: https://i.imgur.com/2su2ySh.png

**Save game:**

Happens with any save I try, but if you want one:

[DIY Six Flags.txt](https://github.com/OpenRCT2/OpenRCT2/files/1845871/DIY.Six.Flags.txt)

Config.ini file:

[config.txt](https://github.com/OpenRCT2/OpenRCT2/files/1845872/config.txt)

**Comment by janisozaur** [comment]
I'll look into that, but is there a previous known working revision?

**Comment by telk5093** [comment]
I'm operating headless servers on Windows 10, and experiencing such memory leak problem as well.
Headless servers were using memory almost 3 ~ 500MiB even though it is headlesses.
Now I'm checking with d7c1983, and I think it works fine (20 ~ 80MiB).

**Comment by IntelOrca** [comment]
@davidlucadou Using 025827809e2aa76bee9fb1d48a5f0b931af7ef7f, I have tried hosting a headless sever and connecting a client to it for both Windows and ArchLinux. The memory consistently stayed below 25 MiB.

Are you able to track down which commit introduced the leak?

**Comment by janisozaur** [comment]
Or provide set of circumstances that cause increase in memory consumption? I tried some commits and just launching the game as host did not trigger that.

**Comment by AaronVanGeffen** [comment]
Sounds like this could be the same issue as #7440. Does this still happen?

**Comment by ZehMatt** [comment]
Probably fixed.
