### ISSUE TITLE
If the last queue path is sloped, guests will enter/exit the ride walking slow.

### ISSUE THREAD

**Issue by blackhand1001** [OpenRCT2/OpenRCT2#7358]
If the last queue path is sloped, guests will enter/exit the ride walking slow.

**Steps to reproduce:**
1. Build a ride a make the path connecting to the entrance sloped
2. The guests will walk in the station to the vehicle in slow motion. The game is still applying the sloped path multiplier to the guest walk speed until the guest exits the ride. This becomes even worse since its also applying the station speed modifier on top of it.

**Comment by SidaRadis** [comment]
This also applies to mechanics and can increase repair/inspection time significantly.

**Comment by blackhand1001** [comment]
Yeah the mechanic bug occurs if the last exit path tile is sloped.

**Comment by Gymnasiast** [comment]
Right, is this what https://github.com/OpenRCT2/OpenRCT2/pull/6673 aimed to fix?

**Comment by blackhand1001** [comment]
No thats a different thing.

**Comment by duncanspumpkin** [comment]
Although it's the same bit of code that likely needs editing

**Comment by blackhand1001** [comment]
I think its actually somewhere else. Wherever it applies the sloped path speed multiplier which is handled separately from the peep state speed multipliers.

**Comment by duncanspumpkin** [comment]
@blackhand1001 i think it is part of the `next_var_29` check within the function. `next_var_29` has a bunch of information within it about the tile.

**Comment by duncanspumpkin** [comment]
Yeah just checked `next_var_29 & (1 << 2)` is checking for a sloped path. And when sloped it halfs the speed. So your mod could be added to that check as well.

**Comment by duncanspumpkin** [comment]
Basically I think the best approach will be to properly clear next_var_29 when entering the ride. That should fix everything.

**Comment by blackhand1001** [comment]
Here is a pull request that fixes the issue.
https://github.com/OpenRCT2/OpenRCT2/pull/7380

**Comment by tupaschoal** [comment]
Fixed by #7380
