### ISSUE TITLE
Convert Save Game to Scenario - Unable to Change Scenario Name

### ISSUE THREAD

**Issue by Jademalo** [OpenRCT2/OpenRCT2#7360]
**OS:** [e.g. Windows 10]
**Version:** 0.1.3
**Commit/Build:** e960b3f

I was trying to make a new scenario out of Crazy Castle with unlimited money and a different victory condition in order to play some fun multiplayer with friends. 
I did the standard method in order to get an editable scenario out of it (Save, convert save to scenario, save landscape, load landscape), but the scenario name was uneditable.

After a bit of research, [this post ](https://openrct2.org/forums/topic/2296-modifying-a-scenario-doesnt-change-the-description/?do=findComment&comment=12733)had a clear guide of what to do, saying the issue was to do with the scenario name object and that I had to disable it.

The issue is that there is no scenario name object, no matter what I do, and there's no "newspaper" icon anywhere. 

There is also an old issue on this project that says to use the same workaround, but this is seemingly impossible - https://github.com/OpenRCT2/OpenRCT2/issues/6337

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/386846/38116775-74f68df4-33a9-11e8-959c-112ade956a3e.png)

**Save game:**
[Crazy Castle.zip](https://github.com/OpenRCT2/OpenRCT2/files/1862146/Crazy.Castle.zip)

**Comment by Gymnasiast** [comment]
A quick-and-dirty way: close OpenRCT2, move all files named STEX*.DAT out of your ObjData folder and try again.

**Comment by Jademalo** [comment]
Can confirm this does indeed work, got the scenario made now. Thanks!
Once the initial save has been made it seems like adding those files back doesn't affect anything further, so that's nice.

Has there been a change to remove that object selection menu?

**Comment by Gymnasiast** [comment]
Yes, there has. This has been done in preparation to removing support for STEX objects entirely - our save format will instead allow multiple languages to be specified directly.

**Comment by Jademalo** [comment]
Alright, thank you!
I was positive I was going crazy since nothing was making sense last night, lol.
