### ISSUE TITLE
[Site] 0.1.2 Master download link leads to 0.1.1 download page

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#7364]
https://openrct2.org/downloads/master/latest leads 0.1.1 download page, not 0.1.2 and so does https://openrct2.org/altapi/?command=get-latest-download&flavourId=1&gitBranch=master

I think it is needed to be updated.

Sorry if it is not proper here.

**Comment by AaronVanGeffen** [comment]
It's been reported on Gitter as well, recently. Unfortunately, we do not control OpenRCT2.org. We have reached out to the webmaster, but it's not something we can fix ourselves.

In the mean time, builds are available on https://openrct2.io/
