### ISSUE TITLE
Cannot Switch Ride Building Screen from Group By Track Types to Group By Rides

### ISSUE THREAD

**Issue by TurtleShroom** [OpenRCT2/OpenRCT2#7365]
**OS:** Windows X Sixty Four Bit (laptop)
**Version:** V0.13
**Commit/Build:** AA7FB35 Developer

Good evening.

The issue I am experiencing concerns a preference pertaining to the sortition of all available attractions and rides. By default, there are entries for each ride as written in RCT2. The Vintage Cars get one slot, the Car Ride gets another, and so on, despite sharing the same track.

There is a secondary option, which combines the rides and groups them by track type. This forces the Vintage Cars and Car Ride onto one slot, the Steeplechase and Soapbox Derby rides into one slot, and so on.

I HATE IT.

The problem is that, as of right now, I cannot seem to find the option to change it so that the traditional/default sortition is employed. I do NOT want rides grouped by track type! I want each ride to have its own operation!

How do I change it back? I can't stand this method of sortition; I want my default slots back!

Thank you for any assistance,
-TURTLESHROOM

****

- [N] Reproducible in RCT2 (vanilla)?
- [N] Specific to multiplayer?

**Steps to reproduce:**
1. Load game
2. Enter a park
3. Open the ride building list
4. If Group By Track is enabled, you're there

**Dump file**
N/A

**Screenshots / Video:**
![untitled](https://user-images.githubusercontent.com/17663470/38159383-f45ffeb6-3496-11e8-9dbb-20065f264039.png)

**Save game:**
[Dusty Greens.zip](https://github.com/OpenRCT2/OpenRCT2/files/1865155/Dusty.Greens.zip)

**Comment by Gymnasiast** [comment]
The old sorting made little sense: the racing cars, sportscars and trucks were put together, but the cheshire cats and vintage cars were not. In addition, the old approach also restricted access to several track pieces and made it impossible to switch vehicles afterwards.

I'm afraid we're not going to revert this decision. The RCT2 mechanism was disliked by a lot of people and supporting both means more complexity.

**Comment by TurtleShroom** [comment]
Both were supported for a long, LONG time. Continuing that support would require no significant effort. Forcing your will on others who prefer the other system is wrong.

I am not asking to change it back or make the correct version the default. I just want to be allowed to choose. I deserve a choice.

Playing the game with tracks crushed together is very difficult for me, because I can't remember what I've selected or where.

Not everyone plays the way you do. I deserve a choice, and I am sure the others who use the default system would be mad as well.

Railroading your personal preferences on others is a mistake.

**Comment by TurtleShroom** [comment]
This mechanism was liked by a lot of people, too, given it was the way we played it for about twenty years!

You can maintain choice, and the choice was already implemented! It's a matter of not wanting to.

**Comment by pizza2004** [comment]
You can always just play with an older version if it's that much trouble, can't you?  I've seen them implementing their own object files and stuff lately and so I would guess that maybe since they're doing that it's changing how the codebase works and it would take extra effort to support both methods going forward.

**Comment by Broxzier** [comment]
> @TurtleShroom I deserve a choice.

You already made your choice: to use OpenRCT2 instead of vanilla RCT2. You've gotten used to the way vanilla RCT2 handles things, OpenRCT2 changed it (and not just because it can be changed), and then you complain that it has. You can always use an older build from before, or play vanilla instead.

By all means, feel free to fork this project and revert the commit that changed the behaviour, then play with your own build.

So there are plenty of choices you can make.

**Comment by Gymnasiast** [comment]
@pizza2004 
> I've seen them implementing their own object files and stuff lately and so I would guess that maybe since they're doing that it's changing how the codebase works and it would take extra effort to support both.

That, combined with the fact that the current system had matured enough, is indeed the reason we removed it. We created a new object format and we weren't going to support _all_ of RCT2's cruft.

@TurtleShroom 
> Continuing that support would require no significant effort.

Oh, of course, you know this better than someone who actually _maintains the software_. If it would require no significant effort, then please do what @Broxzier suggested and maintain your own fork with this feature put back in. Prove that I have no idea what I'm talking about if it's this easy. Hell, if you know better than we do, why don't you just go ahead and fix some of the bugs we have a hard time fixing?

>  I deserve a choice.

Why do you deserve a choice? How much did you pay for OpenRCT2? How much do I get paid for working on it? You have an awfully big mouth for someone who got all of this for free, especially considering I am investing a lot of spare time into this without any financial gain.

You have no reason to demand we put this feature back, and especially not with the tone you're using. You don't have to like our decisions, you can discuss it with us, but the very least you could do is to treat us **normally**. I wouldn't tolerate this if this were a paid game and I got a salary from it, so I'm certainly not going to tolerate in these circumstances.
