### ISSUE TITLE
Feature request: Ride stats breakdown/itemization, virtual real-time testing, construction speedometer

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#7378]
I know this would be a pretty big project, but it could be really cool to have...
It might become a standard feature ... or it might be something that you enable/disable through the cheats menu.
----------Ride stats breakdown---------------------------------------------
Suppose that next to each excitement/intensity/nausea rating, there was a little button you could click, like so:
![57e415f675c52_theopenrctgrouppark42016-09-2219-32-48 png f212e8cdbf19c8e803632222aa5745cb](https://user-images.githubusercontent.com/26573303/38326317-5770c092-37fa-11e8-8380-7339ffae478b.png)
And if you clicked that button, it would open up another window with a breakdown/itemization of how that stat was calculated, such as:
Maximum speed (106km/h): +3.21 (+5.00 possible)
Drops (5): +2.13 (+4.00 possible)
Air Time (1.2 seconds): +1.52 (+3.00 possible)
Interaction with own track (3): +0.30 (+1.2 possible)
Interaction with path (6): +0.73 (+1.2 possible)
Underground sections (7): +0.14 (+.20 possible)
Track pieces more than 10 units above water (3): +0.23 (+1.00 possible)
Track pieces less than 10 units above water (8): +0.45 (+1.00 possible)
High intensity penalty (11.24): -4.32 (unlimited)
Low track length penalty (124m): -2.90 (-3.00 possible)
No inversions penalty (0): -3.00 (-3.00 possible)
... et cetera
(Obviously, these numbers are made up, but you get the idea)
And similar things for nausea and intensity. 
(Or, alternatively, there could just be _one_ button, which displays the breakdown for all three stats at once.)

--------virtual real-time testing------------------------------------------------------------
Part two ... because you didn't think I was done building castles in the sky _yet_ did you?

It would be extra cool and useful if these breakdown windows were available at all times, even when the ride is only partially constructed, updating in real time as you build the ride.
They would have to be based on hypothetical/virtual testing of the incomplete ride, handled by an algorithm working in the background, probably. 
But it would be really awesome to be able to have that window open and see your potential excitement rating rise as you begin to build track pieces over water. It would be really useful to be able to see it take a nosedive when you build a sharp turn at too high of a speed.

---------construction speedometer----------------------------------------------------------
Yes ... _and_ a part three. Getting a little too ambitious, probably.

If part two was done, it could then be possible to have a 'construction speedometer' -- in the construction window, place a little bit of text showing what speed the train/vehicle is estimated to be traveling when it reaches the piece you're currently building. Something like this:
![forest frontiers 2018-04-04 11-32-52](https://user-images.githubusercontent.com/26573303/38327113-47ac5eda-37fc-11e8-979d-23472cfc7bac.png)

Or ... possibly, this might be expanded even further, offering not only the speed, but the negative/positive vertical/lateral g forces that the currently selected track piece would produce:
![forest frontiers 2018-04-04 11-32-52](https://user-images.githubusercontent.com/26573303/38327242-a2f71456-37fc-11e8-9c3b-8c6881f79dcf.png)
This text might also turn red whenever they're high enough to cause an excitement penalty or a crash (ie, high negative vertical g's on a bobsled coaster).

-------------------------------------------------------
I know this is a daunting project, and it might not be feasible ... but it would be really fun and useful if it was implemented, so I thought I would put the idea out there.

**Comment by Gymnasiast** [comment]
I think all of these take away from the game _massively_, and I would veto any PR implementing them.

Having said that though, if someone were to write a plug-in for it, that would be fine.
