### ISSUE TITLE
What's wrong with this picture?

### ISSUE THREAD

**Issue by qwertychouskie** [OpenRCT2/OpenRCT2#7383]
**Version:** 0.1.3-dev
**Commit/Build:** g57b8ea4

![image](https://user-images.githubusercontent.com/13989090/38398871-44630072-3936-11e8-86bb-2f2b94041072.png)

hmm....

**Comment by Gymnasiast** [comment]
This is an issue tracker and not a game of Where's Wally.

**Comment by qwertychouskie** [comment]
Actually, I loaded the save and it seems to be a reverse drop coaster, it just looks weird.

**Comment by Gymnasiast** [comment]
Next time, if you think you found a bug, then just say what's wrong. Don't make it a guess-game.
