### ISSUE TITLE
Game randomly crashes and path item placement on slopes is inversed

### ISSUE THREAD

**Issue by nuclearslurpee** [OpenRCT2/OpenRCT2#7391]
**OS:** Windows 7
**Version:** 0.1.3
**Commit/Build:** develop bb42319

Game crashes apparently at random. This seems most likely to occur while or shortly after placing scenery objects (trees, etc.).

Additionally, path items such as trash bins or lamps cannot be placed on slopes. However, benches can be placed on slopes.

Windows gives the following problem details after a crash:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	openrct2.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5aca0cf2
  Fault Module Name:	openrct2.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	5aca0ceb
  Exception Code:	c0000005
  Exception Offset:	0000000000181eb9
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	1033
  Additional Information 1:	ef0c
  Additional Information 2:	ef0c71fb9bda5398eb5325384f9e2290
  Additional Information 3:	0592
  Additional Information 4:	0592cd80403729f4c0666c00ceaa89d1

**Steps to reproduce:**
Unsure. Crashes seem to occur most frequently when placing scenery.

**Save game:**

[Aqua Park.txt](https://github.com/OpenRCT2/OpenRCT2/files/1888414/Aqua.Park.txt)

**Comment by duncanspumpkin** [comment]
Try the latest version there was a mistake in path items.

**Comment by Gymnasiast** [comment]
Since this a very old report, it's likely not applicable to the current state of OpenRCT2. I'll therefore close it. If you still suffer from crashes, let us know and we'll reopen this report.
