### ISSUE TITLE
Park Partly Damaged After Latest Download

### ISSUE THREAD

**Issue by jamtraks** [OpenRCT2/OpenRCT2#7392]
<!- A latest park of mine that i last edited and saved several months ago, is suddenly missing pieces when opening it, after my latest launcher update done at 3 am or so today 4-09-18.
-->
**windows vista 32-bit**
**0.1.3:** 
**396a234**

After my latest openrct2 update via the launcher this night/early morning of 4-9-18, a particular park of mine has become "damaged". An object file is completely missing, ("arched doorway" that is not the exact file name), and there are several pieces missing from the park's structures, leaving holes in some buildings. I wonder; "am I going to have to manually rebuild these missing parts, or will the holes fill themselves, and be like they were intended to be, just by updating to a future version of openrct2? 
-Please note these holes in these structures did not exist days ago when using my previous openrct2 version.

- [did not test ] Reproducible in RCT2 (vanilla)?
- [did not test ] Specific to multiplayer?

**Steps to reproduce:**
1. open the park in the latest openrct2
2. observe missing pieces

**Dump file**

None created

**Screenshots / Video:**
![park error](https://user-images.githubusercontent.com/17103908/38486278-87f1698e-3baa-11e8-9566-30dae4cd48a9.jpg)
![park error 2](https://user-images.githubusercontent.com/17103908/38486284-8c053668-3baa-11e8-8d1e-e31ce285f33b.jpg)
![park error 3](https://user-images.githubusercontent.com/17103908/38486290-8f4b567c-3baa-11e8-9506-7b64facf2135.jpg)

**Save game:**

[Extreme Heights (REMIX) By Josh Marsilio 1.29.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/1888904/Extreme.Heights.REMIX.By.Josh.Marsilio.1.29.sv6.zip)

**Comment by duncanspumpkin** [comment]
Do you store your custom objects outside of the openrct2 folder?

**Comment by Broxzier** [comment]
I'm getting these warnings when loading the attached saved game:

```
[SNCBRDG2] Warning: Image table size longer than expected.
[KNGBRPA2] Warning: Image table size longer than expected.
[KNGBRP2B] Warning: Image table size longer than expected.
[KNGCOLPA] Warning: Image table size longer than expected.
[KNGGRTPA] Warning: Image table size longer than expected.
[NESUFF11] Warning: Image table size longer than expected.
[VARLB   ] Warning: Image table size shorter than expected.
INFO[c:\projects\openrct2-ject9\src\openrct2\object\objectmanager.cpp:452 (ObjectManager::GetInvalidObjects)]: Ignoring missing STEX entry.
[SNCBRDG2] Warning: Image table size longer than expected.
[KNGBRPA2] Warning: Image table size longer than expected.
[KNGBRP2B] Warning: Image table size longer than expected.
[KNGCOLPA] Warning: Image table size longer than expected.
[KNGGRTPA] Warning: Image table size longer than expected.
[NESUFF11] Warning: Image table size longer than expected.
[VARLB   ] Warning: Image table size shorter than expected.
```

**Comment by jamtraks** [comment]
I have 8500 objects (.dat files) at C:\Users\Josh\Documents\OpenRCT2\object. I have 2122 objects (.dat files) at C:\Program Files\OpenRCT2\ObjData. And i have 5565 objects (.dat files) at C:\Program Files\InfogramesInteractive\RollerCoaster Tycoon 2\ObjData.
If i go back and forth from opening plain old "openrct2" to opening "openrct2 launcher", the game takes 4 minutes to start as if the computer is completely reloading object files from somewhere.
My c: drive is not indexed either, i have not had the patience to allow it to index completely yet.

**Comment by duncanspumpkin** [comment]
Its loading fine for me. I expect this is a problem with the object files possibly being in the wrong location. Can you ensure that all of the custom .DAT files are in ` C:\Users\Josh\Documents\OpenRCT2\object`

**Comment by IntelOrca** [comment]
The missing pieces in the screenshot look like they are from the Wacky Worlds expansion pack. If objects from your Wacky Worlds installation set are not in `C:\Program Files\Infogrames Interactive\RollerCoaster Tycoon 2\ObjData` then they will not be displayed.

One example is `WMARBLE4.DAT`, what folder is this in for you?

**Comment by jamtraks** [comment]
WMARBLE4.DAT is in C:\Users\Josh\Documents\OpenRCT2\object, and also in C:\Program Files\OpenRCT2\ObjData it is **not** in "C:\Program Files\Infogrames Interactive\RollerCoaster Tycoon 2\ObjData". By the way, i never _officially_ installed or purchased any expansion packs. I only _officially_ installed the basic version of rct2 which i still have installed. But i did do something strange a while back through openrct2.org.... I was given a link to a "free" install of the expansion packs, but the install wanted to replace some of my critical rct2 files, or did not install completely, so i think i skipped some file-copies, and even may have cut and pasted some object files here or there.... so, i don't know if this would have caused any of my problem that is occurring now.
---- anyway  shown above is where WMARBLE4.DAT is.
I've always been confused as to why i have two object folders and two openrct locations, i've just always kept them both to avoid any problems.

**Comment by Broxzier** [comment]
Somehow the object from the Wacky Worlds expansion pack got into your `Documents\OpenRCT2\object` folder then. `C:\Program Files\OpenRCT2` may be the location of your OpenRCT2 install, but `C:\Program Files\OpenRCT2\ObjData` isn't loaded nor created by OpenRCT2.

I suggest you remove all vanilla/WW/TT objects from your `Documents\OpenRCT2\object` folder, remove the `C:\Program Files\OpenRCT2\ObjData` folder, get the official installer for the expansion packs, not some download you find somewhere, and install them in their default location. I'm pretty sure openrct2.org doesn't offer them for free.

**Comment by Liampie** [comment]
@duncanspumpkin is it a problem if there are custom objects in my Objdata folder? Could this be the reason why OpenRCT somtimes takes ten minutes to load for me?

**Comment by Gymnasiast** [comment]
@Liampie No, the only problem with having custom objects in your ObjData folder is that OpenRCT2 will not load them.

**Comment by jamtraks** [comment]
I've copied and pasted those missing object files into C:\Program Files\Infogrames Interactive\RollerCoaster Tycoon 2\ObjData. The problem seems to be resolved. thanks.
