### ISSUE TITLE
Non-mowing handyman can leave the path if there is a ride exit immediately above that path.

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#7402]
**OS:**  Windows 8
**Version:** e.g. 0.1.3
**Commit/Build:** 69bb1cd

I kept randomly having this handyman wandering around in the grass, rather than being on the path he was assigned to be on, so I watched him for a while to find out where he's leaving the path.

It turns out, he can leave the path directly under a ride exit that _would_ connect to that path ... if it was 2 squares lower. Yet the path is actually rendering as if it has a connection there, even though there is nothing for it to connect to. (No previous path was built on the spot it's trying to connect to.)

No guests try to leave the path at that spot (thank goodness), but it is problematic that the handyman keeps leaving.

I tried to re-create this glitch in a blank Forest Frontiers, but I couldn't get it to happen again. I'll include the save game where it did happen. This seems like it's an extremely rare glitch that may only show up during certain circumstances, but something to do with the way ride exits connect to paths.

- [Unknown] Reproducible in RCT2 (vanilla)?
- [no] Specific to multiplayer?

**Steps to reproduce:** (This is how I produced it in the first place. It's proving difficult to reproduce.)
1. Build a path along the ground.
2. Build a ride exit where it would connect to that path, except 2 spaces higher.
3. Connect that ride exit to a different path (this new path will overlap the first one).
4. Place a handyman on the lower path.

**Screenshots / Video:**
The situation:
![giggle downs 2018-04-11 03-37-13e](https://user-images.githubusercontent.com/26573303/38612412-7c82445a-3d3b-11e8-9533-38fb6c649fe4.png)

Without the red circle, in case that makes it easier to see:
![giggle downs 2018-04-11 03-37-13](https://user-images.githubusercontent.com/26573303/38612471-a51ad472-3d3b-11e8-9897-2fd5289d1661.png)

Ride exit visible (but now blocking view of the broken path):
![giggle downs 2018-04-11 03-37-21](https://user-images.githubusercontent.com/26573303/38612483-b0e2cdaa-3d3b-11e8-9281-05650397a669.png)

In 'highlight path issues mode' for best visibility -- I just caught him leaving the path!
![giggle downs 2018-04-11 03-37-51](https://user-images.githubusercontent.com/26573303/38612498-bea271de-3d3b-11e8-86a1-81f6da64d9c6.png)

**Save game:**
[Giggle Downs.zip](https://github.com/OpenRCT2/OpenRCT2/files/1898474/Giggle.Downs.zip)

**Comment by duncanspumpkin** [comment]
yes staff have slightly different checks for where they can walk. This causes them to leave the path in situations where guests don't.

**Comment by Broxzier** [comment]
The issue here is that the path stays connected to the entrance or exit after the ghost piece on the same tile moves away.
![forest frontiers 2018-04-15](https://user-images.githubusercontent.com/9705046/38781414-584835e8-40e4-11e8-8b73-de2bc8645ad9.png)
