### ISSUE TITLE
Rides can be covered by placing scenery underneath them

### ISSUE THREAD

**Issue by jensj12** [OpenRCT2/OpenRCT2#7405]
**OS:** Windows 10
**Version:** 0.1.3 develop
**Commit/Build:** 1cd88a1

Let the title and image speak for itself.

According to the OP of this forum thread, the results of putting scenery above rides are hard predict:
https://openrct2.org/forums/topic/2887-how-to-make-covered-sheltered-roller-coasters/

This piece of code is asking for some attention.
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/ride/Vehicle.cpp#L1830

- [ ] Reproducible in RCT2 (vanilla)? not tested
- [ ] Specific to multiplayer?

**Screenshots / Video:**
![happy park sb 2018-04-11 21-00-42](https://user-images.githubusercontent.com/13868449/38637570-cf0d0594-3dcb-11e8-879e-7c06bd3bd728.png)
Removing the scenery will make it rain "I don't want to ride while it's raining"-thoughts

**Save game:**
[CoveredCoaster.txt](https://github.com/OpenRCT2/OpenRCT2/files/1900124/CoveredCoaster.txt)

**Comment by duncanspumpkin** [comment]
l1837 is where the height should be checked against the tile.
