### ISSUE TITLE
Trying to place a bin and and hovering over a queue line crashes. 

### ISSUE THREAD

**Issue by blackhand1001** [OpenRCT2/OpenRCT2#7406]
**Version:** [e.g. 0.1.3]
**Commit/Build:** [e.g. f052416]

Trying to place a bin and and hovering over a queue line crashes. 

**Steps to reproduce:**
1. Go to the scenary window and select a bin. 
2. Hover your cursor over a queue line. The game will crash.

**Comment by Broxzier** [comment]
Tried with 073d0f7 but failed to reproduce this issue with an empty queue, queue that's not connected to a ride, queue with peeps on it, sloped queues, and with clearance checks disabled. Please provide more detailed steps about how to reproduce this issue.

**Comment by blackhand1001** [comment]
Disregard this. It happens on the peep branch but I just switched to the develop branch and it seems to be ok.
