### ISSUE TITLE
Title Sequence isn't working

### ISSUE THREAD

**Issue by BunkyBoss** [OpenRCT2/OpenRCT2#7419]
**OS:** [e.g. Windows x86-64]
**Version:** [e.g. 0.1.3]
**Commit/Build:** [e.g. dOad94b]

For Some random reason, the game doesn't like to insert/test custom title sequences. I put some park that i have made/ downloaded, and most of them have custom scenery/rides, which is a guess why it does this, but some of the regular title sequences use custom scenery and the tile inspector, so plz tell me how to fix this... and if anyone is wondering, the parks in my sequence are: Cedar Point, Diamondback at Kings Island, Vortex at Kings Island, Thrope Park, Kumba at Busch Gardens Tampa, Quickdraw Quarry, Gemini City, and Six Flags Carolina...
- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

(I can't put in the sequence file, so i'll just put Cedar Point in here....)
[Cedar Point.zip](https://github.com/OpenRCT2/OpenRCT2/files/1914063/Cedar.Point.zip)

**Comment by IntelOrca** [comment]
Put your sequence file into a zip file or rename the file extension to .zip, then it will let you upload it to GitHub.
