### ISSUE TITLE
Shops can auto-rotate towards queue lines

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#7424]
**OS:** Windows 7
**Version:** 0.1.3
**Commit/Build:** a1e0e63

Shops can auto-rotate towards a queue line instead of a regular path. Since shops facing queue lines are useless the auto-rotate function should prioritize normal paths.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Comment by Broxzier** [comment]
Pinging @Fusxfaranto

**Comment by tobyhinloopen** [comment]
I attempted to fix it here:

https://github.com/OpenRCT2/OpenRCT2/pull/7463
