### ISSUE TITLE
Scenario option Guest Happiness not in par with actual value

### ISSUE THREAD

**Issue by MisterSchmidt** [OpenRCT2/OpenRCT2#7425]
OS: _Windows 10_
version: _0.1.3_
build: _11207f9_

Editing the guest happiness value in the scenario editor doesn't have effect on the actual value. Checked it in multiple parks. 

After setting it by using the "set guest_initial_happiness" the value stayed that way. It felt like the effect of the happiness was only working after setting it with console, not with the menu. Should be obvious, but i'm not sure.

- [ **No** ] Reproducible in RCT2 (vanilla)?
- [ **No** ] Specific to multiplayer?

1. Start game.
2. Open a scenario or savegame.
3. Open Scenario options.
4. Edit the Guest Happiness value and save
5. Check in console by typing "get guest_initial_happiness"

In the screenshot you can find me checking both values in the menu (after saving) and console

![naamloos4](https://user-images.githubusercontent.com/11180804/38903517-867db538-42a5-11e8-8d74-685f2718a8cd.jpg)

EDIT: I made a goof, version of screenshot was 1.2 - Oe7cOf7.. but the issues also exist in 1.3

**Comment by Broxzier** [comment]
I'm unable to reproduce this. I tried it both by changing the value in the Scenario Options window and by changing the value using the in-game console command, and everything works as expected. Saving and then re-opening the park also shows the expected value.

**Comment by MisterSchmidt** [comment]
For example: I tried Forest Frontier opening the scenario editor..  Initial Guest Happiness is set to 54%.. Opening console typing the command results in a Guest Happiness of 15%.

**Comment by Broxzier** [comment]
What's the exact command you typed in?

**Comment by MisterSchmidt** [comment]
get guest_initial_happiness

**Comment by Broxzier** [comment]
When I start Forest Frontiers `get guest_initial happiness` gives me 54%. I've changed it to 60%, saved the park, reopened it, and then the command gives me 60%. Everything works as expected on my end.

**Comment by Gymnasiast** [comment]
To both: where did you get your Forest Frontiers scenario from? Directly from RCT1 or through a recreation pack?

**Comment by Broxzier** [comment]
Mine's directly from RCT1.

**Comment by moTechPlz** [comment]
**_OS: Windows 10_**

Cannot reproduce this either, worked correct for me.

**Comment by Broxzier** [comment]
Still unable to reproduce and haven't heard anything from @MisterSchmidt for a long time.
