### ISSUE TITLE
Unexpected Game Crash when Opening Ride Creation Tab after doing certain things.

### ISSUE THREAD

**Issue by killicus1103** [OpenRCT2/OpenRCT2#7428]
**OS:** macOS 10.11.6
**Version:** 0.1.3
**Commit/Build:** d0ad94b

When opening the ride creation menu after waiting a little bit, the game crashes with no warning.

- [Unknown] Reproducible in RCT2 (vanilla)?
- [No] Specific to multiplayer?

**Steps to reproduce:**
1. Create scenario with custom objects
2. Build some rides, then mess with them maybe using cheats.
3. *DON'T* build any rides after step 2!
4. After around a minute or so, try opening the ride creation menu.

**Dump File**
Please correct me and tell me how to get a dump file if this is wrong, as I feel this isn't it.
[Sample of OpenRCT2.txt](https://github.com/OpenRCT2/OpenRCT2/files/1936156/Sample.of.OpenRCT2.txt)

**Screenshots / Video:**

https://www.youtube.com/watch?v=ZwtUcQt69o0
Failed to reproduce once but did get it
**Save game:**

[niceland.txt](https://github.com/OpenRCT2/OpenRCT2/files/1936158/niceland.txt)

**Comment by killicus1103** [comment]
Will do as soon as I get back from vacation, as i’m leaving right now. First time releasing an issue, sorry.

**Comment by Gymnasiast** [comment]
> 2. Build some rides, then mess with them maybe using cheats.
3. DON'T build any rides!

These sound contradictory. Could you clarify this?

**Comment by killicus1103** [comment]
added dump file, save file, and fixed commit version

**Comment by janisozaur** [comment]
> Please correct me and tell me how to get a dump file if this is wrong, as I feel this isn't it.

This would be roughly the format, but it's not interesting without the crash in it.

**Comment by Gymnasiast** [comment]
Assuming this has been fixed as it’s been 4.5 years and we don’t have much to go on.
