### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by No0to** [OpenRCT2/OpenRCT2#7429]
**OS:** Windows 10

I was getting openrct2 and when I opened openrct2.exe (I also tried the installer) it said that there was a virus called "Heur.AdvML.C" by the way, I use Norton (yes, I know, haha)

- [ ] Reproducible in RCT2 (vanilla)?
No

- [ ] Specific to multiplayer?
No

**Steps to reproduce:**
1. Have Norton
2. Open openrct2.exe

**Comment by IntelOrca** [comment]
Doing a a virus check on the latest develop and master 64-bit and 32-bit installers is green for all tested scanners.
* https://www.virustotal.com/#/url/56b0321bac873a1639cdd23a6a55161ac95ae665fc8b0ac9e43b5e0050a92287/detection
* https://www.virustotal.com/#/url/9cb00b0cac86dc8d568ed59788dc8efbfcd9c96c0c04e533e3518d607bf5a88b/detection
* https://www.virustotal.com/#/url/a8657a44c8fb790de7d5a769e6f9a046e925ee317d1c488f6f02842fde429894/detection

This is a false positive if your downloaded game is authentic. Make sure your scanner is up to date.

**Comment by manuelVo** [comment]
`Heur.AdvML.C` isn't a regular virus signature. Warnings with this signature are generated by a machine learning algorithm. And one with quite a high false positive rate it seems when looking this up on the internet.

**Comment by qwertychouskie** [comment]
> (or get another AV program)

Or get Linux and never worry about an AV again ;)
