### ISSUE TITLE
Diagonal ride segments cannot be deleted if they are isolated.

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#7434]
**OS:** Windows 8
**Version:** 0.1.3
**Commit/Build:** a1e0e63

Normally, if you delete all the pieces of the ride you're building one by one (using the little red bulldozer button), when the last one that's connected to what you're working on disappears, it will be replaced by one piece of station platform ready to be built in the same spot.

But if you do this and the last piece you remove is a diagonal piece, you'll be unable to remove it. The bulldozer button will do nothing.

Not sure exactly what the expected behavior would be (probably replace it with a ghost station platform piece, facing either one way or the other?) but it's actually pretty annoying when this happens. You have to either demolish the whole ride, or you have to add more track pieces to what you're trying to remove, until you get to a non-diagonal piece, then you have to remove the diagonal piece first, _then_ remove the extra pieces you added in order to remove that one.

Not the kind of thing that's likely to come up often, but it's annoying when it does.

- [ edit: No ] Reproducible in RCT2 (vanilla)?
- [ No ] Specific to multiplayer?

**Steps to reproduce:**
1. build a track with a straight diagonal piece
2. delete the pieces before and after the diagonal
3. attempt to delete the diagonal piece

**Screenshot:**
![coaster crazy 2018-04-19 19-25-02](https://user-images.githubusercontent.com/26573303/39092339-a1ecd8c6-45c0-11e8-9bb2-5d6d5c305772.png)

**Comment by Broxzier** [comment]
Just tried it and it's not reproducable in vanilla RCT2. A difference I noticed is that no ghost appears behind the selected track piece in OpenRCT2.

**Comment by deurklink** [comment]
> Not the kind of thing that's likely to come up often, but it's annoying when it does.

It actually does come up often for me because I like to use lots of trackitecture.

**Comment by Gammadivided** [comment]
Adding to what deurklink says, it's also a frequent problem when placing tracks for merges/fake track pieces
