### ISSUE TITLE
Only first 32 vehicles of a train can be painted

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#7436]
**OS:** Windows 10
**Version:** 0.1.3
**Commit/Build:** 3006398

I wanted to paint this train which has 40 cars, but could only select the first 32 cars.

![Skywarp](https://user-images.githubusercontent.com/6469413/39064463-e7317e3e-44ce-11e8-973d-baafc7b58736.png)

1. Disable vehicle limits to make a train with more than 32 vehicles
2. Select different colors per car
3. Try to select cars after 32nd car

**Comment by Gymnasiast** [comment]
This is an SV6 limit. I might be able to fix it, but colours for car 33 and beyond will not be saved.

**Comment by spacek531** [comment]
the vehicle struct has a field for colors: https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/ride/Vehicle.h#L131

perhaps you could try writing to this directly?
