### ISSUE TITLE
Game is Acting Very Weird

### ISSUE THREAD

**Issue by BunkyBoss** [OpenRCT2/OpenRCT2#7438]
**OS:** Windows 8
**Version:**0.1.2
**Commit/Build:**426e106

When I open up the game, the title sequence is now just a blank grass field. Then I tried to load a save but, it said I was missing all of the objects that are in the game (all scenery, rides, etc.) you mainly get it if you download a park from an rct2 website if you don't have the custom scenery or rides that the park has. Well that screen appeared, but instead of custom objects, all of the regular objects from the original rct and rct2. So plz tell me how to fix it or if the game is just in maintenance.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**

**Screenshots / Video:**

Images here:
 [2nd capture](https://user-images.githubusercontent.com/37355403/39105296-c5511ddc-4650-11e8-875d-5d397125fdc7.PNG)

![capture](https://user-images.githubusercontent.com/37355403/39105300-c7d56ca2-4650-11e8-9e0c-ff38b5dd874d.PNG)

**Save game:**

**Comment by killicus1103** [comment]
you probably didn’t get a correct download of RCT2 if i has to guess. try downloading the demo from open rct2’s website

**Comment by Gymnasiast** [comment]
Well, is your problem solved, now, @BunkyBoss ?
