### ISSUE TITLE
Memory leak. All system memory used.

### ISSUE THREAD

**Issue by mozar99** [OpenRCT2/OpenRCT2#7440]
**OS:** Windows Server 2012
**Version:** 0.1.3 dev
**Commit/Build:** d0ad94b

When I start to host an online server the instance uses 12MB of ram. After three days this usage goes up to 500MB+. Eventually openrct2.exe will use all system memory. See attached screenshots. 

- [ ] Reproducible in RCT2 (vanilla)? unknown
- [x ] Specific to multiplayer?

**Steps to reproduce:**
1. Run a server for more than a few days. RAM usage starts low but eventually uses all RAM on system.
2. 

**Dump file**

**Screenshots / Video:**

![starting server](https://user-images.githubusercontent.com/29951295/39135289-d7490790-46d5-11e8-842c-f9bb70e5c676.png)
![serverafter3days](https://user-images.githubusercontent.com/29951295/39135290-d759ba54-46d5-11e8-8a5a-653cc73f98fe.png)

**Save game:**

**Comment by janisozaur** [comment]
We'll take a look, can you provide any more hints what's needed for reproducing this? Is running the server enough or does it need clients connect and perform actions? Maybe just clients connecting (without doing anything) is enough?

**Comment by mozar99** [comment]
Janisozaur, I'm not sure. I will run another instance but block connections to it on the firewall to test if it only happens when users connect.

**Comment by janisozaur** [comment]
How exactly do you launch your servers?

**Comment by janisozaur** [comment]
Does it also happen with the headless binary? Or is the full client required?

**Comment by mozar99** [comment]
I believe this started to happen after a network update but i cant say what update. I have added the map I use for hosting. Maybe its due to the ride selection / themes used in this map. 
[mozarTemplate.zip](https://github.com/OpenRCT2/OpenRCT2/files/2073255/mozarTemplate.zip)

**Comment by ZehMatt** [comment]
I tried to tackle this but I'm unable to actually reproduce it. I loaded your park and left it running for over 3 days and it never went above 200mb~ in total.

So I have two theories:
1. You have overlay software installed that may leak memory in the ORCT2 process.
2. You are doing something very specific over time which I did not.

To provide further assistance would you be so kind to create a full process dump of openrct2.exe after a day when it starts to increase memory?

You can do this by launching the Task Manager, select openrct2.exe process, right click and select "Create dump file", specify your location and save it. Once thats done please put it into an zip/rar and upload it here. 

This will allow me to inspect the allocated memory regions and your loaded binaries.

**Comment by mozar99** [comment]
Hi ZahMatt,
Thank you for all your assistance on. I have created a dump file. uncompressed its 1.4GB, the zip is 612MB. If its too big I can get a smaller dump.

http://67.41.198.94/mnt/openrct/mozarOpenRCTexe.zip

thanks,

**Comment by ZehMatt** [comment]
Well its typical if you dump the whole process including all its memory, thanks. I will have a look this weekend.

**Comment by janisozaur** [comment]
Based on discussion around https://gitter.im/OpenRCT2/OpenRCT2?at=5b2d3248d2abe46688809a42 https://gitter.im/OpenRCT2/OpenRCT2?at=5b325df90168e70c08f05057 and https://gitter.im/OpenRCT2/OpenRCT2?at=5b3389936ceffe4eba378690 it seems the prerequisites for this are:
running `.exe` (`.com` doesn't seem to exhibit the problem) with `--headless` option. There is no need for any clients to be connected.

**Comment by janisozaur** [comment]
Can you recheck with b278dce or later please?

**Comment by mozar99** [comment]
I upgraded the servers yesterday. Running 0.2.0-169 ( 79f1cf5 ) and I'm still seeing the same memory issue. Happy to upload another memory dump if you want.

![openrctmem](https://user-images.githubusercontent.com/29951295/43156214-bf3c37ae-8f36-11e8-948b-ada636896a62.jpg)

**Comment by AaronVanGeffen** [comment]
@mozar99 Could you try with one of the [AppVeyor artifacts](https://ci.appveyor.com/project/IntelOrca/openrct2-ject9/build/0.2.0.14861) for #7836?

**Comment by mozar99** [comment]
I believe the memory issue has been fixed. only 22mb of ram is being used. thank you!

**Comment by AaronVanGeffen** [comment]
Wow, that's great to hear! Thanks for testing.
