### ISSUE TITLE
button click sound is smaller than vanilla version & yellow arrow flickring on build mode

### ISSUE THREAD

**Issue by guljam** [OpenRCT2/OpenRCT2#7443]
click sound "TOCK TOCK"
and
installing object sound "BOOK BOOK" is smaller than vanillla version.

![gif3](https://user-images.githubusercontent.com/15816034/39157236-e45bafe0-4794-11e8-811f-8e1fa4074ed2.gif)

Some ride's buildmode's yellow cursor is very blinking.(ex. Car Ride)

**Comment by duncanspumpkin** [comment]
Unsure what you mean by sound issue.

Yellow flickering arrow has been annoying for quite some time. It needs reworked.

**Comment by tupaschoal** [comment]
Sound effect seems to be the same as #7490 and will be tracked there
