### ISSUE TITLE
Rides list windows has weird strings when building custom rides

### ISSUE THREAD

**Issue by SidaRadis** [OpenRCT2/OpenRCT2#7454]
**OS:** Windows 7
**Version:** 0.1.3
**Commit/Build:** 2ef549b

The rides list window only displays numbers after building a new custom ride. Custom rides designs that you have already saved in your track folder get named properly. Rides that don't have custom designs like the 3D Cinema or stalls also seem to work properly.

**Steps to reproduce:**
1. Build a custom ride with the build menu
2. Open the rides list window
3. See screenshot below

**Screenshots / Video:**
![beach barbecue blast 2018-04-27 16-45-53](https://user-images.githubusercontent.com/28242696/39384352-7ee54aa6-4a3a-11e8-85b4-2736213d9e3e.png)

**Comment by AaronVanGeffen** [comment]
Looks like it's printing the ride's generic string ids rather than their values. As soon as you name a ride, they show up properly as a user string.

**Comment by AaronVanGeffen** [comment]
I don't see how yet, but I've bisected this to 2d92ecf10b6702909cabe008faca481cdfb0d6eb. Indeed, it doesn't happen on its parent, 49cf840f282e209d7fdc716d858014e75dabd7f1, and reverting 2d92ecf10b6702909cabe008faca481cdfb0d6eb fixes the issue.

**Comment by AaronVanGeffen** [comment]
A week later and we're still no closer to resolving this. I therefore propose we revert 2d92ecf10b6702909cabe008faca481cdfb0d6eb (#7449) for the v0.1.3 release. As @duncanspumpkin said in #7449, we cannot store the colours above 32 in saves anyway.

After the release, we can look for another solution to #7436.

@Gymnasiast Is this acceptable to you?
