### ISSUE TITLE
Mute button aliases to Sound Effects incorrectly

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#7474]
**OS:** Windows 10
**Version:** 0.1.2
**Commit/Build:** 735cc2d

The mute button, when it is active, will disable `Sound Effects`. This is unintuitive because 1) music is also disabled even though `Ride Music` is not disabled, and 2) re-enabling `Sound Effects` while Mute is on does not unmute the game. This creates the odd experience where exiting the game while Mute is on will disable sounds when the game is closed and reloaded.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Load a park
2. Mute the game
3. Enable `Sound Effects` (sound effects are not re-enabled)
----
1. Load a park
2. Mute the game
3. Quit the game while it is muted
4. Start the game (sounds effects are disabled)

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by Gymnasiast** [comment]
Might already have been solved with the introduction of 'master volume'.
