### ISSUE TITLE
Mute cannot be controlled from the title screen even though it affects title screen

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#7475]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.1.2]
**Commit/Build:** 735cc2d

Even though Mute controls the sound on the title screen, it cannot be turned on or off when viewing the title screen.

It would be nice if there was an ability to start the game with the title sequence muted because I've found that it can be balanced really loud compared to some music I listen to.

Suggestion: save the Mute condition to options like `Sound Effects` and `Ride Music` are, add option in sounds tab.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Load a park
2. Mute the game
3. Return to title screen (cannot unmute game)
----
1. Listen to some soft music
2. Turn the volume up to acceptable levels
3. Open OpenRCT2 (better plug your ears!)

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by Gammadivided** [comment]
As a temporary solution, bind mute to a key. When you're in the title screen, just press that and the game will mute/unmute itself.

Adding to this though, if you reopen the game at a muted state, the title music will play, but the game sounds will be muted. It takes 2 presses of the mute key to fix this.

**Comment by spacek531** [comment]
The issue with the sound effects is this: https://github.com/OpenRCT2/OpenRCT2/issues/7474

**Comment by Gymnasiast** [comment]
I think this has been solved now the "Master volume" control has been introduced. Let us know if it isn't.
