### ISSUE TITLE
Trying to Change Park Name During MP Session Instantly Crashes Host Game

### ISSUE THREAD

**Issue by saxman1089** [OpenRCT2/OpenRCT2#7476]
Pretty self-explanatory by the subject. 

Steps to reproduce: Try to change the park name in MP, server crashes.

**Comment by Gymnasiast** [comment]
Please add the commit.
Also, is this as a user or as the server?

**Comment by saxman1089** [comment]
0.1.3 build 735cc2d, but I've seen this bug a few times on earlier versions.

It was as a user of the server.

**Comment by duncanspumpkin** [comment]
This no longer happens
