### ISSUE TITLE
Glitch when saving maze designs

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#7485]
**OS:** Windows 10
**Version:** 0.1.3
**Commit/Build:** 5f9d40b

When saving mazes a ton of weird glitches occurs. It says that saved scenery isn't available even though no scenery was saved, it has no exit when you try to build it, it doesn't appear when you build it, you can't demolish it, and when you try to edit it you get a ride building screen with just about every option available. The linked video shows it all. I've tried this with some other rides and so far it only happened with the maze.

**Steps to reproduce:**
1. Build a maze and save the design
2. Try to build the design

**Screenshots / Video:**
https://www.youtube.com/watch?v=Tr0vqtLLWb4&feature=youtu.be

**Comment by Gymnasiast** [comment]
Oh goodie, another maze design bug!

Mazes have as much in common with other rides as they have with platipi.

**Comment by jensj12** [comment]
After trying to build the ride (and the ride window pops up), the behavior there is the same as for any other non-existent ride, and can be seen by building any saved ride design that overlaps itself (or anything that generates an error while building for real, but not in ghost mode).

**Comment by LordMarcel** [comment]
I just found out that this behaviour is also present when you try to save coaster designs with 4 stations.

**Comment by tupaschoal** [comment]
This doen't happen anymore on v0.3.1
