### ISSUE TITLE
rct2objecteditor won't work (ik its not openrct2)

### ISSUE THREAD

**Issue by BunkyBoss** [OpenRCT2/OpenRCT2#7486]
**OS:*Windows 8
**Version: 13
**Commit/Build: 7168fb7

Yes i know this isn't openrct2, but it still rct type stuff. Im not saying to fix it (because you all didn't make it) but i'm asking if the program still works or how to fix it my self if anyone else had this problems. I've gotten a picture

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**

**Screenshots / Video:**

![capturenew](https://user-images.githubusercontent.com/37355403/39612105-1c0011b0-4ef8-11e8-9a88-a41952b82933.PNG) It's garbage i know...

**Save game:**

**Comment by Lastorder-DC** [comment]
Contact program developer. It's OpenRCT2 Issue tracker, not rct2objecteditor's Issue tracker.
You can also join [Gitter](https://gitter.im/OpenRCT2/OpenRCT2/non-dev) and ask stuff there.

**Comment by Gymnasiast** [comment]
This would indeed be better suited to the Gitter channel, as Lastorder-DC, or the OpenRCT2 forums.

Your drivers seem to lack OpenGL. If you're using drivers supplied by Microsoft, download new drivers from the manufacturer's website instead.
