### ISSUE TITLE
Twitch integration server seems to be shutted down

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#7488]
**OS:** Windows 10
**Version:** 0.1.3
**Commit/Build:** Recent

It seems that the twitch integration server(http://openrct.ursalabs.co/api/1/blahblah) is shutted down.
I'm wondering wether it is correct to post this issue here, please close this issue if it is not proper here.

p.s. Is the openrct.ursalabs.co official server of the openrct2 team?

**Comment by AaronVanGeffen** [comment]
I believe the Twitch server is run by @mzmiric5. We should probably move it to a service on our own domain on DigitalOcean at some point.

**Comment by qwertychouskie** [comment]
The domain has been parked: http://openrct.ursalabs.co/

![image](https://user-images.githubusercontent.com/13989090/39641450-b739b15c-4fbd-11e8-9edd-05914c4c0051.png)

**Comment by mzmiric5** [comment]
I haven't been active on this project for a while, and I no longer operate any services on the ursalabs domain, hence the issue with the service. That being said, I believe the server side of the Twitch integration is severely outdated, and most of the APIs it used are deprecated by Twitch. I might take a weekend to write a new up to date version for the features the old one offered, and have a chat with @IntelOrca to get it deployed on DigitalOcean or to point an ORCT owned subdomain to one of my Heroku instances.

**Comment by BenediktMagnus** [comment]
@mzmiric5 Is the code for the Twitch integration server public or is there at least a documentation for the API it provides (besides the client code)?

**Comment by telk5093** [comment]
@BenediktMagnus Nice

**Comment by Lastorder-DC** [comment]
@telk5093 This can be closed since twitch integration function is now removed.
