### ISSUE TITLE
Posix implementation of platform_file_copy does not work correctly

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#7494]
**OS:** Linux
**Version:** 0.1.3
**Commit/Build:** 0df569f0e24963f904156fdeb4130d3f5699d276

`platform_file_copy` fails in some cases on Linux. I have tried both Arch and Fedora. It might fail on macOS as it uses the same code but I haven't confirmed that.

Can be reproduced by duplicating the OpenRCT2 title sequence in the options / title sequence editor window. It will copy the file but the file size of the new file is much smaller than expected.

This is a good opportunity to add support for `std::filesystem` so that [std::filesystem::copy_file](http://en.cppreference.com/w/cpp/filesystem/copy_file) can be used instead. [OpenLoco](https://github.com/OpenRCT2/OpenLoco/blob/master/src/openloco/windows/promptbrowsewnd.cpp) is a good example of how to set it up.

**Comment by Gymnasiast** [comment]
Seems to be OK as of c02c7925c3d4bc02377b5e1e159f128ed38ab7ee . We have also adopted std::filesystem in the meantime.
