### ISSUE TITLE
openrct2-cli docker image is broken

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#7497]
**Image:** openrct2/openrct2-cli:latest
**Commit/Build:** 907d318e1c28da06f01dcee8cb393b6c4786696a

```
docker pull openrct2/openrct2-cli
docker run openrct2/openrct2-cli -h
```

Produces:
```
openrct2-cli: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by openrct2-cli)
openrct2-cli: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by openrct2-cli)
```

**Comment by janisozaur** [comment]
Needs update to 18.04 as per https://github.com/OpenRCT2/OpenRCT2/pull/7523

**Comment by IntelOrca** [comment]
Relevant file: https://github.com/janisozaur/OpenRCT2/blob/develop/dockerfiles/openrct2-cli/Dockerfile
