### ISSUE TITLE
Game closes when trying to make path over map edge with sandbox mode on

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#7505]
**OS:** Windows 10
**Version:** 0.1.3
**Commit/Build:** ad0060f

If you try to build a path over the map edge, normally the game will give an error message, warning you that you're trying to build outside the map. In sandbox mode however, this check is not there.

If you try to build a path on the edge where the X or Y coordinate would become -1 when sandbox mode is on, the game closes. It doesnt crash or freeze, it just closes.

**Steps to reproduce:**
1. Make a path using the arrow tools, so with a ghost path being drawn in front
2. Create a path up to the map edge where the x or y coordinate is 0 with sandbox mode turned off (should work fine)
3. Do the same with sandbox mode turned on (game closes)

**Comment by Chaosmeister** [comment]
sandbox mode?  
clearance checks disabled?

I'm not sure what this is about.
