### ISSUE TITLE
Custom file save format - viable option

### ISSUE THREAD

**Issue by Nubebuster** [OpenRCT2/OpenRCT2#7506]
This is not a bug report, but rather a suggestion. 

I see that, for instance to save cheats with a park, writing a custom file save format is 'required'.
Wouldn't it be more viable to just make a second file next to the save file which contains openrct2 data?

I have been waiting for a while (over a year) to see implementation of cheats saving and other things like that. Unfortunately I am not familiar with C++, therefore I cannot implement this myself :(

**Comment by AaronVanGeffen** [comment]
You're right, this would provide a temporary workaround for the problem. It has been suggested in the past as well, in the context of providing a screenshot of the park in the load/save window.

However, the problem with adding such hacks, is that you will have to support them indefinitely. It would be a little frustrating if you could no longer properly load your saves once we switch to a proper format, wouldn't it?

This is one of the arguments for why it'll have to wait. I'm sorry.

**Comment by Gymnasiast** [comment]
As Aaron says.
Since we all do this in our spare time, it just won't go quicker than this, sorry.
