### ISSUE TITLE
Number of block sections in black, while everything else is in white.

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#7508]
**OS:** Windows 10
**Version:** e.g. 0.1.3
**Commit/Build:** 2512e49

This is a very minor and purely aesthetic UI issue, but it seems strange to me that the number of block sections is in black, while all other text in this window (and most other windows) is white.

- [ ? ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open the ride settings tab on any ride in block sectioned mode.

**Screenshots / Video:**
![dragon s cove 2018-05-11 13-31-19](https://user-images.githubusercontent.com/26573303/39946461-1782e758-5523-11e8-8f47-d439e4a52321.png)

**Comment by Broxzier** [comment]
That's because the number of block sections is there for information while the rest are options. This is consistent with other windows.

**Comment by pizza2004** [comment]
Shouldn't the words Block Sections: also be in black then?  Perhaps also changing the color to be a darker version of the main window color just like the other color is a lighter version of the background color so it matches better.

**Comment by Broxzier** [comment]
That would be inconsistent with the rest of the windows, and I think it looks out of place:
![image](https://user-images.githubusercontent.com/9705046/39949888-10d7c760-557e-11e8-894b-57bb62827d2d.png)

**Comment by pizza2004** [comment]
Well, I mean, I don't think the "Block Sections:" should be a different color than the number either way.  It just looks like a bug otherwise.  I don't have a good solution to fix it though I guess.
