### ISSUE TITLE
Water isn't cut down by view clipping tool

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#7518]
**Version:** 0.1.3
**Commit/Build:** c89e321f352612fdfa9367d6476ced8645320e47

The water level is above the clip-height (you can see the hill and path being cut off), but the water is not cut off:
![image](https://user-images.githubusercontent.com/9705046/40027974-c6db4d1a-57dc-11e8-9a8b-e7e1de652ac1.png)

I can think of two solutions:
- Not drawing the water at all. This makes it clear to see what's under water.
- Cutting the water level off at clip height. Gives more of a sense of looking underwater.

**Comment by tupaschoal** [comment]
Still happens on v0.3.1
