### ISSUE TITLE
Support non-latin language translation? (such as Korean)

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#753]
Hello, I'm a Korean RCT user and feel very glad to meet OpenRCT2 project.
I think it could be very wonderful and free game like Open Transport Tycoon Deluxe.

Since I translate OpenTTD into Korean,
I would like to translate OpenRCT2 too, but I have wondered if doesn't support non-latin languages yet.
(Once OpenTTD did)

1. Do you have any way for non-latin languages(e.g. Korean)?
2. If you, then the only thing what shall do is editing data/language/english.txt into korean.txt?

I'm new to here, please forgive me if I write this at wrong place.
I will wait your wonderful, memorable nice OpenRCT2 game.

**Comment by PFCKrutonium** [comment]
![korean](https://cloud.githubusercontent.com/assets/3945538/6091172/0ca4be68-ae6b-11e4-9170-2412ef0a0d99.png)

Unfortunately it doesn't seem there is support yet... I guess you are going to have to wait for someone to add it.

**Comment by telk5093** [comment]
Hmm... I think someone must be add it... OpenTTD had have the same problem until 2007. I wish OpenRCT2 can support all languages in one day. If it comes true and developers watched this, please contact me then I will translate this into Korean perfactly and also I will be honoured. And thanks for your comment and effort.

**Comment by adrian17** [comment]
There was a talk about it in [this issue](https://github.com/IntelOrca/OpenRCT2/issues/319), you should find an answer there.

**Comment by IntelOrca** [comment]
RCT2 is built around Windows-1252 fixed 8-bit encoding. It is unlikely that we will be able to change to UTF-8 until the whole game is implemented. You can still create a Korean language file so that it is ready for when the game does use UTF-8, just make sure that the language text file is encoded as UTF-8.

**Comment by RollingStar** [comment]
@IntelOrca, RCT1 supported Korean & Japanese. I've seen both of those personally. [Chris Sawyer's site](http://www.chrissawyergames.com/info.htm) says RCT2 supports Korean too.

>RollerCoaster Tycoon II (Win98/ME/XP/2000)  
>Widely available.  
>Languages: UK English, US English, French, German, Spanish, Swedish, Dutch, Italian, Japanese, Simplified Mandarin, Traditional Mandarin, Korean, Brazilian Portuguese.

**Comment by PFCKrutonium** [comment]
In the Linked Japanese Demo, the two odd files out are  Csg1.dat (14.5MB) and Csg1i.dat (521Kb)

**Comment by IntelOrca** [comment]
Yes, possibly by using the data files kanji.dat and tai.dat. But because the languages were hard coded resulting in many different versions of the game executable, I don't know the full details of how they worked yet.

**Comment by PFCKrutonium** [comment]
Ye, as I have discovered if you try to move the files to a normal install of RCT it causes it to load a green screen then raise an access exception.

**Comment by PFCKrutonium** [comment]
I made the Japanese version choke on my Deluxe Install's Data Folder, and it launched, but loading a Map immediately crashes the game.
![screenshot 25](https://cloud.githubusercontent.com/assets/3945538/6094493/e942e276-aef9-11e4-8b59-bfc5a9adc5d8.png)

**Comment by IntelOrca** [comment]
@PFCKrutonium We already have currency multiplication in place.

**Comment by PFCKrutonium** [comment]
Cool, didn't know ;)

**Comment by IntelOrca** [comment]
You can change the currency to Yen in the settings window, you'll see the difference.

**Comment by RollingStar** [comment]
@PFCKrutonium, @IntelOrca: I can provide guidance on getting versions of RCT1 to run / install. My method involves using the US game as a base for most of the files (most of them are unchanged between versions) and running the foreign-language installer.

As IntelOrca notes, the RCT.exe files are unique for each version. I never got the JPN demo running as a full game, and although I have a copy of RCT1 in Korean, I've never installed that either. My interest in the endeavor had waned by that point.

It doesn't look like this is currently a priority for you, IntelOrca, but later on if you ever want more versions to look at I can probably help you.

**Comment by IntelOrca** [comment]
I think there are currently the following issues:
* Non-Latin characters will be two bytes, which means that custom strings can only be half the maximum size. We can not increase the size until full implementation, it also breaks compatibility for original games there on.
* Not sure how many non-Latin character sprites are in the data files, but probably not all of them. Therefore we will need to implement drawing of true type or open font files to support all unicode characters. I think this is what OpenTTD does.
* All string related methods in OpenRCT2 need to be UTF-8 compatible.

I think the first action would be to change all string related functions, path / file functions to support UTF-8. And also use Windows' UTF-16 variants of API functions, converting strings where necessary.

**Comment by IntelOrca** [comment]
@telk5093 It would be very useful if you continued your translation for Korean as it can then be used to test UTF-8 when it is in the process of being implemented. Just carry on like you are, writing the text file in UTF-8.

**Comment by AaronVanGeffen** [comment]
@telk5093 Are you still interested in doing a Korean translation? The project now supports UTF-8, thereby making it possible to use Hangul.

**Comment by telk5093** [comment]
@AaronVanGeffen OMG, finally..! Sure I am :)

**Comment by Gymnasiast** [comment]
@telk5093 : Instructions for creating extra translations are here: https://github.com/OpenRCT2/Localisation
This is also the place to submit updated translations.

**Comment by IntelOrca** [comment]
UTF-8 support is now implemented.
