### ISSUE TITLE
Train/No.cars/Vehicles quantities frozen on custom or pre existing rides

### ISSUE THREAD

**Issue by GregHarp13** [OpenRCT2/OpenRCT2#7534]
MAC OSX 
0.1.3

Building any custom ride creates just one train and one car. The selection drop down lists in the ride settings do not open or allow changes to the quantity of trains or cars per train.

This issue is also apparent on pre-existing rides for example any roller coaster on a six flags park - the trains and car numbers are frozen.

Single Player Mode in use at time. ANY SCENARIO - even tried making my own scenario and issue exists there too.

**Steps to reproduce:**
1. Open any scenario
2. Attempt to change the number of trains or cars per train in the ride settings page. Go kart track is good example only one kart etc.

**Comment by AaronVanGeffen** [comment]
What build of 0.1.3 is this on? You can find the exact number at the bottom of the title screen, e.g. 4cb4c0b

**Comment by Broxzier** [comment]
bisect showed me that https://github.com/OpenRCT2/OpenRCT2/commit/34531f7 is the offending commit.

**Comment by IntelOrca** [comment]
It is probably my changes in `ride_get_smallest_station_length`. I just noticed the uint32 = -1 followed by min calls. Very confusing.
