### ISSUE TITLE
Render ẞ ligature in sprite font

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/OpenRCT2#7535]
Split off from https://github.com/OpenRCT2/OpenRCT2/pull/7385:

> At the risk of sounding blasphemous: we might want to map the ẞ to the glyph for ß so it's at least rendered with the sprite font…

Should be an easy issue to tackle.

**Comment by Gymnasiast** [comment]
Codepoint is `U+1E9E`.
