### ISSUE TITLE
Handymen underground do not water flowers above ground

### ISSUE THREAD

**Issue by nuclearslurpee** [OpenRCT2/OpenRCT2#7539]
**OS:** Windows 7 SP 1
**Version:** 0.1.3-develop
**Commit/Build:** db4ddec

It used to be possible to water gardens by placing handymen in a path tunnel 2 blocks beneath the gardens, [as shown here for example](https://openrct2.org/forums/topic/215-scenery-guide-tricks/). Recently I have tried to use this trick and it no longer works.

If this feature was removed intentionally in a previous build, it would be great to have it back as this was the only non-cheat method of keeping gardens from wilting if they are not built in a handyman-accessible location, or if one does not want ugly handymen tromping about in one's flower displays. Also, it provided a convenient excuse to trap handymen in inescapable subterranean tunnels as punishment for ignoring that spot of puke last month.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Place gardens somewhere.
2. Build a tunnel with paths 2 blocks beneath the gardens.
3. Place a handyman on the path assigned to water gardens.
4. (Optional) use the OpenRCT2 cheats menu to freeze weather to prevent rain. This is not necessary but makes it easier to observe the lack of behavior since rain can water the gardens.

**Screenshots / Video:**
![forest frontiers 2018-05-18 17-59-20](https://user-images.githubusercontent.com/38199386/40261516-af0a6a26-5ac6-11e8-89e2-25978b0226a3.png)

**Save game:**
[FF_test-water-gardens.txt](https://github.com/OpenRCT2/OpenRCT2/files/2018858/FF_test-water-gardens.txt)

**Comment by Patrik356b** [comment]
Sprinkler plug-in would be a future option

**Comment by deurklink** [comment]
Not having them be able to do this does make it more realistic though.

**Comment by Broxzier** [comment]
It looks like they can water flowers one land step higher than them, which I think is realistic. The two flower patches on the right wouldn't be watered.

![image](https://user-images.githubusercontent.com/9705046/40619638-204e4b36-6296-11e8-8f4f-0c0333980c1e.png)

Maybe we should restore it back to two steps, until there are other ways of watering flowers that are further away from the paths.
