### ISSUE TITLE
Unknown Crash After Loading Save File

### ISSUE THREAD

**Issue by GravityUnown** [OpenRCT2/OpenRCT2#7540]
**OS:** Mac OS Sierra 10.12.16
**Version:** v0.1.3-HEAD
**Commit/Build:** ee56021 (DEBUG)

I tried opening one of my old park files today and I got a 1 second glimpse of my park before the application crashed and closed unexpectedly. I am unsure if there's too much in the park or what but I am very confused and am unsure of what is causing it.

- [ ] Reproducible in RCT2 (vanilla)? No
- [ ] Specific to multiplayer? No

**Steps to reproduce:**
1. Open Save File
2. OpenRCT2 Just closes unexpectedly

[OpenRCT2_2018-05-18-192634_Patrick-Mason-Macbook.crash.zip](https://github.com/OpenRCT2/OpenRCT2/files/2018983/OpenRCT2_2018-05-18-192634_Patrick-Mason-Macbook.crash.zip)

**Comment by janisozaur** [comment]
```
Assertion failed: (false), function Assert_VA, file /Users/travis/build/OpenRCT2/OpenRCT2/src/openrct2/core/Guard.cpp, line 104.
 

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fffe51f9d42 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fffe52e7457 pthread_kill + 90
2   libsystem_c.dylib             	0x00007fffe515f420 abort + 129
3   libsystem_c.dylib             	0x00007fffe5126893 __assert_rtn + 320
4   website.openrct2.OpenRCT2     	0x000000010012bf08 Guard::Assert_VA(bool, char const*, __va_list_tag*) + 132
5   website.openrct2.OpenRCT2     	0x000000010012bfa0 Guard::Assert(bool, char const*, ...) + 128
6   website.openrct2.OpenRCT2     	0x00000001000834c3 peep_go_to_ride_entrance(rct_peep*, Ride*) + 61
7   website.openrct2.OpenRCT2     	0x00000001000833c5 rct_peep::UpdateRideAtEntrance() + 1009
8   website.openrct2.OpenRCT2     	0x00000001002d48ad peep_update_all() + 121
9   website.openrct2.OpenRCT2     	0x00000001000a08a4 game_logic_update() + 149
10  website.openrct2.OpenRCT2     	0x00000001000a07a4 game_update() + 400
11  website.openrct2.OpenRCT2     	0x00000001000ef01c OpenRCT2::Context::Update() + 144
12  website.openrct2.OpenRCT2     	0x00000001000eef41 OpenRCT2::Context::RunFixedFrame() + 123
13  website.openrct2.OpenRCT2     	0x00000001000eed15 OpenRCT2::Context::RunGameLoop() + 109
14  website.openrct2.OpenRCT2     	0x00000001000ee902 OpenRCT2::Context::Launch() + 152
15  website.openrct2.OpenRCT2     	0x00000001000ed1d8 OpenRCT2::Context::RunOpenRCT2(int, char const**) + 26
16  website.openrct2.OpenRCT2     	0x000000010007b76c main + 298
17  libdyld.dylib                 	0x00007fffe50cb235 start + 1
```

@GravityUnown can you share said park?

**Comment by GravityUnown** [comment]
Ah I knew I forgot something. I'm terribly sorry. Here is the save file of the park.
[Gravity's Ultra Park.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/2019596/Gravity.s.Ultra.Park.sv6.zip)

**Comment by janisozaur** [comment]
We can _probably_ fix the save for you (I will try looking into that later today if someone else doesn't do that first), but it would help us if you said something about it's history: was it created in OpenRCT2 only? Was it used in multiplayer? Do you know what versions of OpenRCT2 it was used in?

**Comment by GravityUnown** [comment]
I don't know if I can grab the specific version is was originally built in, but I do know it was created back in 2016 (May 12, 2016 I believe?), it was OpenRCT2 only, and it was strictly single player.

**Comment by Broxzier** [comment]
Three of the stations from the monorail somehow share their station index. You can observe this by pause-entering the save (so that the assertion isn't hit) and clicking on the stations and the ride entrances and exits. You'll see that when clicking the entrances, exits and queue banners of some of the stations, the first station gets selected. I've fixed this for you by rebuilding the ride entrances and exits.

[Gravity's Ultra Park-fixed.zip](https://github.com/OpenRCT2/OpenRCT2/files/2020339/Gravity.s.Ultra.Park-fixed.zip)

Do you remember doing anything strange when building the monorail?

**Comment by GravityUnown** [comment]
The fix works, oh my gosh I'm so relieved. Thank you so much, Broxzier.

The only thing weird I remember with the monorail was when I was working on it with a friend who suggested a specific option that makes it so each tram does not meet with each other and that the monorail ahead of it leaves immediate if another one is about to pull into the station. I'm not sure if that caused the crash but that's something we did.

**Comment by Broxzier** [comment]
You're welcome! I think you mean the ride setting "Leave if another train arrives at station". That setting and the timed opening of the monorail are perfectly normal game functions, and they should not have any impact on the station elements. What I meant with "anything strange" was things like merging tracks, disabling clearance, using arbitrary ride types while building, or using the tile inspector.

You mentioned you were using a build from 2016. Changes are this was a bug that was present at the time, but not anymore.

**Comment by GravityUnown** [comment]
Ah, okay. Well in that case I don't think we did anything particularly strange. This was my first park since starting OpenRCT2 so we didn't do anything out of the ordinary. But as long as its fixed now I'm happy. I really appreciate the help once more.
