### ISSUE TITLE
Large tram not working

### ISSUE THREAD

**Issue by willpreebs** [OpenRCT2/OpenRCT2#7545]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.1.2]
**Commit/Build:** [e.g. 426e106]

The "Large Tram" function stopped working when it had previously on the same park. Not sure if this is the reason, but I recently downloaded the launcher as the game had not been updated for a week or so. Afterwards, the large tram doesn't work.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Download latest build via RCT2open launcher
2. Enable cheats
3. Click on "Large Tram"
4. Be sad as it no longer dumps hundreds of guests at the entrance who immediately complain "It's too crowded here"

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by willpreebs** [comment]
Ok, I have tried it again on both the original scenario and a different one, and it only works on the new one. On a similar note, 0 guests seem to be entering my park on the old scenario altogether. I think that it might be because I played around with the scenario settings such as park size, entrance, etc. and it might have screwed up the park. However, the guests see no problem LEAVING the park as the guest count has dropped from 3,200 to 2,300 in about 2 years.

**Comment by willpreebs** [comment]
I made sure that no guests were entering using the "remove guests" function and fast-forwarded and the guest count remained at 0.

**Comment by AaronVanGeffen** [comment]
Sounds like you may be having problem with your peep spawn points.

You can reset the peep spawn points from the map window if sandbox mode is enabled. To do this, first enable debugging tools in the options window, and then enable sandbox mode in the cheats window.

**Comment by willpreebs** [comment]
Ok, still nobody entering

**Comment by willpreebs** [comment]
@AaronVanGeffen

**Comment by AaronVanGeffen** [comment]
You'll have to give me a little more info to go on… What *exactly* did you do?

**Comment by willpreebs** [comment]
Originally, I had sandbox mode enabled and I accidentally decreased the park size so the path leading to the entrance gate was disabled. I realized my mistake and fixed the size and pathing, but no guests were entering. Just now, I re-enable sandbox mode, deleted the path and gate and put them back, but still nobody entered.

**Comment by AaronVanGeffen** [comment]
Path and gate alone aren't enough. You'll have to make a spawn point as well:

![screenshot_20180520_210101](https://user-images.githubusercontent.com/604665/40282517-ea876cec-5c70-11e8-9ca9-dd7c4bfabf1d.png)

**Comment by willpreebs** [comment]
@AaronVanGeffen  Ok, thanks that helps a lot!
