### ISSUE TITLE
Ingame CLI command for saving park

### ISSUE THREAD

**Issue by janzev** [OpenRCT2/OpenRCT2#7549]
Please add an ingame CLI command for saving the current park (e.g. "save_park").

This would be really usefull for dedicated (--headless) servers if you want to start them on server boot. Now the game starts every time at the same point because the server doesn't save any changes to the loaded park. I know that there are autosaves but copying an renaming the autosaves is pretty awkward.
https://openrct2.org/forums/topic/2926-multiplayer-savegames/

**Comment by Patrik356b** [comment]
I'd assume such a command would use the scenario name or input file when saving unless specified

**Comment by janzev** [comment]
I think the optimal solution would be a universal command with some optional arguments.

For example:
`save_park` -> saves park with current filename or scenario name on the local machine
`save_park remote` saves park with current filename on the remote server (headless or cli version)
`save_park thisisatest.sv6` saves park with specified filename on the local machine
`save_park remote thisisatest.sv6` saves park with specified filename on the remote server (headless or cli version)

**Comment by Krutonium** [comment]
Why is having a command that tells it to save remotely not safe?

**Comment by qwertychouskie** [comment]
DoS by filling up the system drive with a bajilion saves?

**Comment by Krutonium** [comment]
Obvious solution would be to not let just anyone trigger a save lol.

**Comment by IntelOrca** [comment]
Or it be a permission.

**Comment by janzev** [comment]
My intention with this issue was that you don't have to connect seperately to the server to save the park. 

Is there a multiplayer permission for the ingame console? (I'm not sure at the moment) If yes, then it is a safe command because only allowed users can use the command. 

@IntelOrca A permission for this special command (or for each single console command) would be really nice but I think that would be too much. A permission just for the ingame console would be enough in my opinion.

**Comment by janisozaur** [comment]
Implemented in #8078
