### ISSUE TITLE
Stock tracks unable to be used online (v0.1.3)

### ISSUE THREAD

**Issue by shibatan** [OpenRCT2/OpenRCT2#7553]
**OS:** OSX 10.13.4 and Windows 10
**Version:** v0.1.3
**Commit/Build:** b763a32 *and* ee56021 (only ones I've tested)

While playing online, pre-designed tracks are unavailable. For example, if you select any ride which typically comes with stock tracks, such as the Log Flume, it will begin Station Platform placement as if you clicked Custom.

- [NO] Reproducible in RCT2 (vanilla)?
- [YES] Specific to multiplayer?

**Steps to reproduce:**
1. **Launch/Join** online server
2. **Click** _Build New Ride/Attraction_
3. **Select** any ride that comes with pre-designed tracks, such as a rollercoaster 
4. (Notice that you were automatically entered in custom build mode)

**Comment by AaronVanGeffen** [comment]
I don't think there is an open issue about it — the only ones I found had already been closed. However, building predesigned rides in multiplayer has deliberately been disabled, as there is currently no mechanism to transfer TD6 files over safely.

In the past, it's been suggested to interpret and build the ride design as separate game actions, but as that'd remove atomicity, it's likely to lead to more problems.

It basically boils down to: someone hasn't stepped up to fix it yet.

**Comment by janisozaur** [comment]
And in the past it was also blocked on GameActions not being implemented yet. They're merged now, so it should be easier to implement.

**Comment by shibatan** [comment]
Thank you, @AaronVanGeffen and @janisozaur. 
Let me know if there’s any way I can help other than making the change myself.

**Comment by klardotsh** [comment]
Speaking in very rough terms, how new-to-this-codebase-friendly would this task be? I work in software (not C++, but I'm familiar with it), so I'd be willing to help on this if it's not a total Pandora's Box that'll take months :)

**Comment by Patrik356b** [comment]
@klardotsh Why don't you grab the source and have a look?

**Comment by klardotsh** [comment]
I can read all day, but nothing's going to beat the general guidance of the folks who actually maintain this project and have the domain knowledge of what roads might need traveled and/or footguns one will encounter along the way.

So, sure, I'll poke around, but my question still stands.

**Comment by janisozaur** [comment]
I wouldn't recommend starting with this issue. There is a fair amount of design that has to go into this feature:
* how are the rides going to be transported to the server?
* how the server is going to build them?
  - piece-by-piece, as is currently done?
we could even go one step further and check the following:
* what is the impact on other connected clients, are there ways of mitigating it?
  - is it still to be done in a single tick? maybe spread across multiple ticks?
  - pre-cache the track before it gets placed?

Even in the easy solution, there's a lot of work to do.

**Comment by Gymnasiast** [comment]
Was implemented in #10189.
