### ISSUE TITLE
Coasters with incomplete tracks only save the first station piece

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#7561]
**OS:** Windows 10
**Version:** 0.1.3
**Commit/Build:** 06105c3

When you save the design of a coaster with an incomplete track, such as a boomerang, the saved design will only have the first station piece when you build it. You will even be able to save and build it if either or both the entrance and exit aren't on the first station piece.

**Steps to reproduce:**
1. Build launched coaster with incomplete track
2. Save the track 
3. Build that track

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/25930360/40554763-123cdc70-6047-11e8-9c48-73b00c7cf920.png)

**Comment by AaronVanGeffen** [comment]
I'm a little surprised it lets you save it to begin with… As far as I know, test results are required for the TD6 format?

**Comment by LordMarcel** [comment]
It tests like any other coaster with the "powered launch without passing station" setting. This coaster never makes it over the hill, but just returns to the station and stops.

**Comment by jensj12** [comment]
I have it fixed locally. Will submit in a single PR with #7568.
