### ISSUE TITLE
Tile inspector window issues

### ISSUE THREAD

**Issue by Umdlye** [OpenRCT2/OpenRCT2#7564]
**OS:** Win10 x64
**Commit/Build:** 7be4072

- The window close button does not work until a tile element is selected
- The 'rotate', 'remove' and 'corrupt element' buttons are not grayed out until a tile element is selected and unselected [(left = new, right = old)](https://user-images.githubusercontent.com/11657101/40563428-02ba91a2-6065-11e8-8cb9-edda61e91c8c.PNG)

**Comment by Broxzier** [comment]
A regression from https://github.com/OpenRCT2/OpenRCT2/pull/7548. It's one of the main things that I _aimed_ to improve (and did for some buttons) but completely broke for the others. I'll fix it in a bit.
