### ISSUE TITLE
Trying to demolish a continuous circuit without a station crashes the game

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#7568]
**Version:** 0.1.3
**Commit/Build:** cce3769

The game hangs when trying to demolish a ride that has a 'continuous' circuit that doesn't go through a station.
This only makes the client hang in multiplayer, the server is not affected.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Build any tracked ride and create a circuit without a station in it (a circle using 4 turns for example)
2. Open the ride window and click the Demolish button
Result: the game hangs

Alternatively, start building a track with a station, but make it loop with itself (not passing through the station).

I think there was a very similar bug with testing/opening a ride in such situations before.

**Screenshots / Video:**
To clarify what I mean with the alternative method:
![forest frontiers 2018-05-27 16-31-36](https://user-images.githubusercontent.com/9705046/40587133-7d66d0e8-61cb-11e8-99c9-4704e802e874.png)

**Comment by jensj12** [comment]
Caused by the cost prediction from my PR. Will look into it.

**Comment by AaronVanGeffen** [comment]
@jensj12 This may come in useful: #7062
