### ISSUE TITLE
Add ability to remap WASD as the Arrow Keys.

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#757]
My laptop has tiny arrow keys, and I would appreciate this ability a lot. I know you can move with the mouse, but I prefer the WASD Keys.

**Comment by RollingStar** [comment]
Specifically, it's not currently possible to remap the pan view function from arrows to anything else.

**Comment by Phasedetect** [comment]
I would love to see this added. For trackpad users who have trouble right-click panning, it would enable the left hand to always be on the keyboard while the right hand is dedicated to the mouse.
