### ISSUE TITLE
Queue paths connect to regular paths through fences

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#7572]
**OS:** Windows 10
**Version:** 0.1.3
**Commit/Build:** 15ae358

Queue paths will connect to regular paths through fences
![image](https://user-images.githubusercontent.com/25930360/40589217-cb941c6c-61e9-11e8-8e63-0d743639084b.png)

**Comment by mattbeaudin** [comment]
Currently looking at it on Version 0.2.0 and it seems that they won't connect until you hover the queue path builder over an adjacent available space.

Before:
![queuebug-before](https://user-images.githubusercontent.com/20703680/42854802-9c803f60-8a0b-11e8-9ee2-26e05f4aa741.png)

After:
![queuebug-after](https://user-images.githubusercontent.com/20703680/42854805-a09afca2-8a0b-11e8-9c18-70f9142ee7d2.png)
