### ISSUE TITLE
Error Loading Objects For Park

### ISSUE THREAD

**Issue by GravityUnown** [OpenRCT2/OpenRCT2#7576]
**OS:** Mac OS Sierra 10.12.16
**Version:** v0.1.3-HEAD
**Commit/Build:** 617372f (DEBUG)

I've been out of commission for a while due to personal job reasons and such so I haven't been around that much to see what I missed, but basically I came back to OpenRCT2 recently to check out my old save files and noticed that a vast majority of my save files now will not load anymore. I instead get a pop up window explaining that certain objects (mainly custom ones it appears?) could not be found anymore for some reason so the save files do not load at all.

Thankfully I still have an older version I can fall back to, but 80% of my save files are unable to load on the most current experimental build. I have an included a sample of one save file that seems to be the most greatly affected. I'm not sure if an update build at some point while I was gone changed the way it loads certain objects, but I find this a little alarming.

Reproducible in RCT2 (vanilla)? No
Specific to multiplayer? No

**Steps to reproduce:**
1. Load Save file
2. Get an error window after clicking save file

**Screenshots / Video:**
![screen shot 2018-05-28 at 8 19 04 am](https://user-images.githubusercontent.com/17536087/40616409-8fbcd0e6-6250-11e8-843d-5daeba1ba1ba.png)

**Save game:**
[The Perfect Bird.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/2045245/The.Perfect.Bird.sv6.zip)

**Comment by Broxzier** [comment]
Those objects were most likely loaded from the _ObjData_ folder in your RCT2 installation directory (or possibly from RCT2's VirtualStore folder in appdata), but OpenRCT2 only loads the original game files from those locations now. To make OpenRCT2 find custom objects too, you'll have to copy them over to your _Documents/OpenRCT2/object_ folder.

**Comment by GravityUnown** [comment]
Hi there, thanks for the reply. I don't seem to have an OpenRCT2 folder in my main documents folder. Do I need to create it myself, or is there another possible location to put it in?

**Comment by Broxzier** [comment]
OpenRCT2 should have created one, it's also where config.ini is stored.

to find it, try running openrct2.com with the --verbose flag from a command prompt window (`openrct2.com --verbose`). The paths should be printed right at the beginning.

```
> openrct2.com --verbose
OpenRCT2, v0.1.3-develop build 617372f provided by AppVeyor
Windows (x86-64)
@

VERBOSE: time is 2018/05/28 16:26:46
VERBOSE: registering AVX2 mask function
VERBOSE: DIRBASE::RCT1    : C:\GOG Games\RollerCoaster Tycoon Deluxe
VERBOSE: DIRBASE::RCT2    : C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2
VERBOSE: DIRBASE::OPENRCT2: D:\Data\Documents\OpenRCT2\bin\data
VERBOSE: DIRBASE::USER    : D:\Data\Documents\OpenRCT2
VERBOSE: DIRBASE::CONFIG  : D:\Data\Documents\OpenRCT2
VERBOSE: DIRBASE::CACHE   : D:\Data\Documents\OpenRCT2
```

**Comment by GravityUnown** [comment]
Ah would this happen to be on Windows only? Because I'm using a Mac, haha.

I found an object folder in the Application Support OpenRCT2 directory and copied the RCT2 objects into that folder as you suggested and everything works again!

**Comment by Broxzier** [comment]
Yeah that was my bad, I overlooked that in the first post. Glad to hear it's working now! You may have copied the vanilla RCT2 objects over too, but that shouldn't really be a problem.
