### ISSUE TITLE
Clicking same price throughout park on accident

### ISSUE THREAD

**Issue by Nubebuster** [OpenRCT2/OpenRCT2#7578]
When you click just below the price setter in a roller coaster you check the box for 'same price throughout park' button. When lowering the photo price I accidentally click there and all the coasters are affected. This is really annoying as it takes me several minutes to set all the prices back to their original. Can this be fixed easily?

In this image I have marked what should not affect the button in red and the part what I am trying to click instead in green
![315c3a3b280b6bba4957146dccd27168](https://user-images.githubusercontent.com/7793993/40628423-40a590c2-62c5-11e8-856c-87d88016b5d0.png)

**Comment by Gymnasiast** [comment]
> This goes for all spinners, they're tricky to point at with a sensitive mouse.

^ that. They were made for a time when 640x480 was common, and 1024x768 was high.

**Comment by AaronVanGeffen** [comment]
I think we should consider replacing the spinners with horizontal [+] and [-] buttons, personally…

**Comment by Gymnasiast** [comment]
Hah, seems like you and I had the same idea :-P

**Comment by janisozaur** [comment]
Wasn't that idea already floated some years ago? I don't remember if that was in one the issues or on gitter…

**Comment by AaronVanGeffen** [comment]
Let's spin-off the discussion about the spinners to #7579, shall we? :)

**Comment by HaasJona** [comment]
There could still be some more room in that window, the "k" from "park" actually seems to touch the border of the input box above.

It's also not clear from this screenshot if the "same price throughout park" applies to the on-ride-photo only or for both prices.

**Comment by AaronVanGeffen** [comment]
This will be solved by #7579:

![screenshot_20180531_225242](https://user-images.githubusercontent.com/604665/40807711-5af0633c-6525-11e8-9b5d-6698ebbfe23d.png)

**Comment by Gymnasiast** [comment]
> I'm wondering whether we should indent the 'profit per item sold' labels as well. Thoughts?

That sounds like a good idea to me. The 'price' labels are intended to nicely align with the 'same price' label, so the same should apply to 'profit per item sold'.
