### ISSUE TITLE
Self-Merging Track more than Once on a Ride Causes Track to Disappear

### ISSUE THREAD

**Issue by saxman1089** [OpenRCT2/OpenRCT2#7594]
First showed up in f805c8d as far as I can tell, also present in 3137469

Trying to self-merge a track, and if I try it more than once (as is common in shoestringing) the track to be merged into disappears. See the gif below.

![merge](https://user-images.githubusercontent.com/20549965/40756482-dd00a410-6451-11e8-9f9e-42ff7b44fa2c.gif)

As you can see, the first merge works fine, but when I go to complete the second, it deletes the existing track. This happens regardless of whether, in my situation here, I build the straight track or curved track.

**Comment by jensj12** [comment]
I suppose it has to do with the merge being backwards, not whether it's the first or second. Can't test right now. Probably caused by #7580 @Broxzier.

**Comment by Broxzier** [comment]
Previously ghosts wouldn't be shown if there was going to be collission, but now clearance checks are properly ignored they are, and as a result they remove the wrong element. I think it's getting the first track element at that the start position of the track, and removes the first track sequence it finds. A check should be added to compare track sequence IDs before deleting it.
