### ISSUE TITLE
Clearance checks disabled causes auto-delete of coaster stations if moused over with a new ride station ghost piece

### ISSUE THREAD

**Issue by myn0k** [OpenRCT2/OpenRCT2#7597]
**OS:** Win7 64bit
**Version:** 0.1.3
**Commit/Build:** 06e043b

With clearance checks disabled, moving the ghost first placement piece of a rollercoaster station over an existing, complete rollercoaster's station deletes the complete rollercoaster's station pieces automatically. No click for placement is needed for the new ride, simply mousing over causes the deletion.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Create a rollercoaster (mine was a junior rollercoaster)
2. With clearance checks disabled, click to build a new custom rollercoaster, and mouse the ghost first station piece over the existing rollercoaster's station and it should delete the station pieces.

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by blackhand1001** [comment]
I've seen this happen with other types of track as well. I think any identical piece of track it will delete.

**Comment by Broxzier** [comment]
Somewhat related to, and fixed by https://github.com/OpenRCT2/OpenRCT2/pull/7596

**Comment by myn0k** [comment]
Ok, sorry, things move so quickly around here I didn't realize there was already a fix coming in a future update.

**Comment by Broxzier** [comment]
Don't worry about it! It isn't obvious that it's the same issue, since you are simply hovering over the ride instead of building backwards. I'd rather see multiple reports for an issue, than no reports at all. :smile:
