### ISSUE TITLE
Visual bug in the invention list

### ISSUE THREAD

**Issue by Chaosmeister** [OpenRCT2/OpenRCT2#7601]
#7562 introduced a visual bug in the invention list:

The (always researched) items in the upper list should be rendered _INSET_

**Steps to reproduce:**
1.  compare pre #7562(1a2958df843f1f3342191e1217d7fe1e0c225db9) with current development(df1e8af73708acf53da3d9e75d3401aa5f7fe284)
2.  The items in the upper list are currently rendered with the incorrect font.

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/13346344/40813358-b21358bc-653a-11e8-9e75-acb9fee894f1.png)

**Comment by AaronVanGeffen** [comment]
Here's what it's supposed to look like:

![screenshot_20180601_182915](https://user-images.githubusercontent.com/604665/40852116-b56b93aa-65c9-11e8-9e47-ec81e000ce91.png)

It's a bit puzzling that outlined items can still be dragged between sections. Possibly another bug? Not a regression though, as far as I can tell.

**Comment by Chaosmeister** [comment]
That bug you mention will be fixed with my pull request #7522

**Comment by Gymnasiast** [comment]
@Chaosmeister Could you create a separate PR for fixing that bug? I'd like to have that fix for 0.2.0, which will be released soon.

**Comment by Chaosmeister** [comment]
this won't fix the incorrect rendering thoug. just the picking.

**Comment by AaronVanGeffen** [comment]
Feel free to revert part of 1a2958df843f1f3342191e1217d7fe1e0c225db9 -- that is, re-introduce the use of a buffer instead of drawing directly from string id. Please do keep the other changes, including the string clipping.

**Comment by AaronVanGeffen** [comment]
I have submitted a PR with an alternate fix for the issue with inset text: https://github.com/OpenRCT2/OpenRCT2/pull/7638
