### ISSUE TITLE
Screenshot command for non-existing park creates empty .png file

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#7602]
**OS:** Windows 10
**Version:** 0.1.3
**Commit/Build:** b94f5ea9d84b3a876a0e0e54436f13232122028c

For example: `openrct2.com screenshot "i-dont-exist.sv6" "output.png"` creates a the file `output.png`, even though the saved game does not exist.

**Comment by AaronVanGeffen** [comment]
On a related note, if you open OpenRCT2 from the command line with a non-existing file as its first parameter, it will show a black window (with an FPS counter, if enabled) as well. I'm fairly sure we have an outstanding issue for this, but I can't find it at the moment.

Another thing to look at in the same code path: #6260

**Comment by tupaschoal** [comment]
> For eample: `openrct2.com screenshot "i-dont-exist.sv6" "output.png"` creates a the file `output.png`, even though the saved game does not exist.

I tried this today and got

> Unable to open 'i-dont-exist.sv6'
> Failed to load park.

> On a related note, if you open OpenRCT2 from the command line with a non-existing file as its first parameter, it will show a black window (with an FPS counter, if enabled) as well. 

This doesn't happen anymore either, the game opens with a red tooltip error that it failed to load data, but it's fully functional
