### ISSUE TITLE
Feature: Order vehicles in vehicle selection drop-down by name

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#7606]
**OS:** Windows 10
**Version:** 0.1.3
**Commit/Build:** e91777b

I love the fact that the ride types in arbitrary ride types list are ordered now! 
Just like was done for ride types in arbitrary ride types cheat, I think the vehicle types could also benefit from being ordered alphabetically. When you allow many vehicle types, the list gets very big and it is difficult to find the vehicle type you want to use.

![image](https://user-images.githubusercontent.com/6469413/40848493-b4e8709c-65bf-11e8-90f7-834e02a941c2.png)

**Comment by AaronVanGeffen** [comment]
Ouch, yes, this is certainly another candidate for the same treatment. I'll look into it.

**Comment by saxman1089** [comment]
Yes yes yes yes please!
