### ISSUE TITLE
Feature: Resizing staff window should also resize name column

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#7613]
**OS:** Windows 10
**Version:** 0.1.3
**Commit/Build:** cb536a1

The staff window can be resized horizontally, but it will result in a lot of unused space. I think it would be nice if the name column would also be resized so more of the name can be shown.

![image](https://user-images.githubusercontent.com/6469413/40866887-74562a10-6600-11e8-99d4-1b9e0cd55252.png)

**Comment by AaronVanGeffen** [comment]
Interesting use of staff names… :stuck_out_tongue: Thanks for making an issue about this!

The guest list similarly doesn't make use of its extra space, although it's probably less of an issue there.

**Comment by deurklink** [comment]
Just took this from a park from NE 😛 They like mentioning each other in staff names.
