### ISSUE TITLE
Bugs for #7579

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#7616]
**OS:** Windows 10
**Version:** 0.1.3
**Commit/Build:** d09fc19

- [x] As you can see, brake/booster widget is not implemented yet.
![image](https://user-images.githubusercontent.com/10726524/40877560-ebe74e7a-66bd-11e8-8a83-820a3d3cacae.png)

- [ ] And -/+ in korean is rather thin and biased to right (about 1~2px?) as you can see above.
![image](https://user-images.githubusercontent.com/10726524/40877577-3039ec72-66be-11e8-9869-08b6558d16ff.png)

@AaronVanGeffen

**Comment by AaronVanGeffen** [comment]
Looks like I forgot to adjust an invalidation function for the ride window.

Not sure what best to do about the +/- buttons themselves. Perhaps we could force the use of the sprite font there?

**Comment by telk5093** [comment]
If there are default +/- sprite, then it would be great.

**Comment by IntelOrca** [comment]
> Not sure what best to do about the +/- buttons themselves. Perhaps we could force the use of the sprite font there?

Yes, that is what you should be doing. It is what is done for the dropdown caret for example.

**Comment by AaronVanGeffen** [comment]
> Yes, that is what you should be doing. It is what is done for the dropdown caret for example.

That would look nice on these buttons, but it would probably be best not to render *all* +/- characters with sprite glyphs at all times. Would be very disruptive in normal TTF text, I imagine.

**Comment by IntelOrca** [comment]
@AaronVanGeffen I think there is a flag or something you set around draw calls you want to force as sprite font. It isn't done on a character type basis.

**Comment by AaronVanGeffen** [comment]
When discussing this with @Broxzier just now, we supposed we could leverage the unicode [dingbats codepoints](http://www.unicode.org/charts/PDF/U2700.pdf) 0x271A and 0x2796 to represent plus and minus characters that should always be drawn with the sprite font. Could easily be patched into `utf8_should_use_sprite_for_codepoint`.

Would be nicer than checking for two string ids in the widget rendering code to set a flag before rendering, I think. The language files will have to be changed, though... Thoughts?
