### ISSUE TITLE
Same scream used too often

### ISSUE THREAD

**Issue by meatbee** [OpenRCT2/OpenRCT2#7618]
**OS:** Windows 7
**Version:** 0.1.3.  
**Commit/Build:** debb6cd

Almost every scream generated is the same single person one used for the haunted house.
In the example every scream was the same one, but often it's just the most used one.

Also, on a related note the sound is ticking, as you can hear in the video.
**Steps to reproduce:**
1. Open "Six Flags over Texas" park
2. Navigate to "Titan"

**Screenshots / Video:**

https://streamable.com/m962z

**Comment by AaronVanGeffen** [comment]
Is this any different in the original game?

**Comment by meatbee** [comment]
Yes it is. Sorry.

**Comment by qwertychouskie** [comment]
IMO just because it's how the original game does it doesn't mean it's not a valid issue.
