### ISSUE TITLE
Audio position does not consider window scale.

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#7622]
It sounds slightly odd when you play with any scale higher than 1 since the audio position is not scaled. If we want to keep window scaling should the position at where sounds are played use the same scaling?

**Comment by Broxzier** [comment]
It sounds as intended to me. Thing near the sides of the screen should pan to only one of the channels. When the window scale is bigger, the screen area is smaller, making things at the edge move more towards the edge. Is that what you consider slightly odd?

To make sure the audio is panned correctly, I just tested it with a park with one loud coaster in the middle and moved around to make the coaster appear near the edges of the screen.

Window scale factor of 2.00, had to move the camera only a little to make the coaster at the edge of the screen:
![image](https://user-images.githubusercontent.com/9705046/40887120-e03862f4-6743-11e8-9136-d8054711f660.png)

Windows scale of 0.75, had to move a lot to make the coaster be at the edge of the screen:
![image](https://user-images.githubusercontent.com/9705046/40887125-e71a7cd8-6743-11e8-81c4-ca6a1b70a3b4.png)

As you can see, in both cases when the coaster is near the edge, one side is playing the sounds while the other is near silent.

**Comment by ZehMatt** [comment]
Here is an example https://share.epic-domain.com/2018-06-03%2015-54-57.mp4

**Comment by Broxzier** [comment]
The merry-go-round sounds correct too, to me. Its beyond the edge at the top, and the higher the window scale factor, the larger the distance from the edge. The same would happen if you were in a hot air balloon and get closer to the ground. While high up, you can hear a lot, and as you drop down, you hear less and less of what is around you, and more of what is right underneath you.
