### ISSUE TITLE
Server disconnects clients immediately 

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#7630]
**OS:** Windows 10
**Version:** 0.1.3
**Commit/Build:** 5c7d477

I have been hosting several servers without many issues for months.

Since a few days, my servers will work fine for an hour or so, but people who log in will quickly get a desync though. After an hour or so everyone who logs in will immediately get disconnected. I heard someone else who usually hosts a server has the same problem. (Freedom server)

I tried hosting on my other laptop as well (on the same network, different port) and it seems to have the same issues. That makes me think it is either something on the network or somethign caused by a recent update of OpenRCT2. I opened two test servers now, I am open to any suggestions. 

Edit: Problems started since i updated my host laptop last Sunday.

Edit 2: I am running windows 8.1 and windows 10 on my laptops. The other person who has problems with hosting is running windows 10. I just asked someone who didnt have issues and he was running windows 7.

**Comment by janisozaur** [comment]
Suspected regression from  #7609

**Comment by deurklink** [comment]
I will try running it with a command prompt when I get home, see if it generates any error messages.

**Comment by deurklink** [comment]
Moving back to the build before #7609 solves the issues. I assume that the people who do not experience any issues while hosting simply haven't updated their server to the latest version.

**Comment by IntelOrca** [comment]
@deurklink do you know how I can produce this without leaving a server on for over an hour?

**Comment by deurklink** [comment]
The only way I could reproduce this was by leaving on the server for a while. Perhaps it can be sped up if a lot of different people connect to the server(?). I don't really know where the problem comes from so this is just speculation.

**Comment by IntelOrca** [comment]
If you have a server that is disconnecting people I could try to connect to it and debug it.
