### ISSUE TITLE
Selected trains in object selection, still can't select them in the ride options.

### ISSUE THREAD

**Issue by ThePlasmaWolf** [OpenRCT2/OpenRCT2#7641]
**OS:** [Windows 10]
**Version:** [0.1.3-develop]
**Commit/Build:** [2edec95]

I used a save file to edit as load as landscape in the scenario editor. Then I removed everything from the map and flattened it, changed its size etc. The goal was to have a good 'template' of scenery objects from object selection available. Then the following bug occurs.

I am unable to select different vehicle types, after picking them from object selection. A newly added ride will let me build that ride from the build new ride menu, but then it will have only one vehicle to choose from, even if I have multiple vehicles selected in object selection (e.g if I add the bobsleigh penguin trains, I can only ever choose penguin trains even if I later add all the other train options). The only way to get a different vehicle is to remove all relevant rides from the object selection, for which you'd have to remove any built ride of that type first. (i.e. demolish the penguin train bobsleigh, then remove all bobsleighs from object selection, and then add e.g 6-seater bobsleighs).

If I use the "Show vehicles from other rides" cheat, then I will only get the vehicles that each selected ride has available for me. Here the same bug happens. Adding a vehicle from a different ride through object selection won't give me that vehicle as an option. (e.g. If I have my penguin bobsleigh trains, and a vertical drop coaster selected in object selection, then use this cheat, I can select the vertical drop coaster trains that have been selected at first, say the 6-seat. Then adding the 8-seat vertical drop trains in object selection won't let me select the 8-seat in the bobsleigh, but the 6-seat can be selected).

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Load a save file (not a scenario) as landscape in scenario editor.
2. Remove all objects on the map, flatten the map, change the size (possibly not necessary, these are the things I did).
3. Save as scenario.
4. Load scenario.
5. The bug should occur: adding trains for rides through object selection won't let you select the trains in the built ride's options.

**Dump file**
[Wooden Test 1.zip](https://github.com/OpenRCT2/OpenRCT2/files/2087035/Wooden.Test.1.zip)

**Comment by Gymnasiast** [comment]
It looks like most of the vehicles in that file are simply not invented.

**Comment by deurklink** [comment]
Looks like they will not be invented either since it's a no money map.

**Comment by ThePlasmaWolf** [comment]
Going into the inventions and sending everything to the top (is invented) solved it. I can now pick the vehicles I want. *Sigh* So simple.

**Comment by Gymnasiast** [comment]
You can simply close the issue.
