### ISSUE TITLE
Vertical Drop Coaster has Large Loop enabled incorrectly

### ISSUE THREAD

**Issue by nuclearslurpee** [OpenRCT2/OpenRCT2#7645]
**OS:** Windows 7
**Version:** 0.1.3
**Commit/Build:** 0fc4cad

The Vertical Drop Coaster is able to be built with Large Half Loop elements, which should not be enabled without cheats. This behavior persists even if the "Enable all track pieces" cheat is selected and de-selected.

Interestingly, using the "Enable all track pieces" cheat seems to have no effect when it should be enabling other inversions, etc. shared with other B&M-tracked rides. I'm not sure if this is affecting other rides as well since I'm not very familiar with which other rides gain track pieces from the cheat, but it probably is (I've checked to see that the Looping Coaster does not gain access to any of the inversions available to the LIM Launched Coaster, which has the same track type, but I don't know if it should). This may therefore be a more general error with that cheat.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Start a scenario with Vertical Drop Coaster researched (or use the Track Designer)
2. Build a Vertical Drop Coaster with a Large Loop element

**Screenshots / Video:**
![canary mines 2018-06-09 16-20-02](https://user-images.githubusercontent.com/38199386/41196259-a64600b6-6c01-11e8-9a30-e60a77d5fe10.png)

**Comment by ocalhoun6** [comment]
It was deliberately added in a while back for some reason.

Personally, I like having it a lot, even if it's not totally accurate to the original game. Almost every vertical drop coaster I build ends up having one or two.

**Comment by nuclearslurpee** [comment]
That's fair, then, I didn't know that decision was made. However, the issue with "enable all track pieces" is still a problem unless for some reason the Vertical coaster isn't supposed to show any other elements with the cheat on (despite them being present for other B&M tracks), so that probably still merits a look.

**Comment by Gymnasiast** [comment]
The large half loop was indeed added deliberately.

'Enable all track pieces' is only used within a ride type, that is: if you build a Car Ride and enable it, it will also show Monster Truck pieces, since these share their ride type. Vertical Roller Coaster and Twister Roller Coaster do not. However, this cheat could be extended to also include them.
