### ISSUE TITLE
Merry-go-round music turns into static

### ISSUE THREAD

**Issue by TheMathsGod** [OpenRCT2/OpenRCT2#7649]
OS: Windows 10
Game version: Spans multiple, since I first got openRCT2 a couple of weeks ago.

The merry-go-round music will turn into static whenever it reaches a certain point in the song. It is always the same point, and it will always become static when it reaches this point. It can be temporarily fixed by turning the "play music" option off and on again as this resets the music position, but this becomes annoying after multiple times.

The issue happens on every build I have had since getting the game, in every scenario, and is 100% consistent no matter what else I do.

**Comment by Broxzier** [comment]
There may be something wrong with your game files then. The music for merry-go-rounds is stored in `css4.dat` to `css17.dat`, excluding `css10.dat`. You could open these files with a media player to check if the noise is present. And you can compare their MD5 hashes with this table:

|**file**|**MD5 hash**|
|----|----|
| css4.dat | b2e0354a11cc8c678b7671d9f247c929 |
| css5.dat | f649abef341a6a090d0a642ef6cdfc81 |
| css6.dat | e30c2cd7cf4aa2e67f8a8777f87af78e |
| css7.dat | 03217e73c2a838b96305a3e72fa944a6 |
| css8.dat | 3a719dab49f641efa79b64d6a6ad10ce |
| css9.dat | 70c6cc983c38cbaed01fdb38a7cf8da3 |
| css11.dat | 1df2c449f1b6fa75d099dd4a95d02fa0 |
| css12.dat | f4147a86efc830b0128ffeba6340835a |
| css13.dat | 74be9a6ce21149a7bdaf6e1b34aa2013 |
| css14.dat | 67d0f5778835b953ac1ec2cc93b237f1 |
| css15.dat | e8e8db9d8d3e7961e0144da820e8432e |

**Comment by TheMathsGod** [comment]
How would I view the MD5 hashes? There's a couple of MD5 hashing websites I've seen but they use a string input. I tried opening one of the files (css4.dat) in notepad but it's just a whole load of random characters, so I assume that means it's stored in binary format rather than text-based. Can I still copy/paste this into one of these websites, or is there a better way?

**Comment by Broxzier** [comment]
Open Command Prompt or PowerShell, browse to the Data folder in your OpenRCT2 installation folder, and run: `CertUtil -hashfile css4.dat MD5`. Change `css4.dat` for each file of course.

**Comment by Broxzier** [comment]
7-zip can calculate other hashes, if you find that easier to do, but sadly no md5. I can provide the SHA-1 hashes for example if you find that easier.

![image](https://user-images.githubusercontent.com/9705046/41205415-57747204-6cf3-11e8-8481-3053c47b7955.png)

**Comment by TheMathsGod** [comment]
I did manage to find a website that let me upload the files, and it turns out css11.dat is the corrupt file, as it threw up an incorrect hash. Could you provide a download of the working file?

**Comment by TheMathsGod** [comment]
Could do. I've got the disk version, and this laptop has no disk drive, but my other computer has no sound. So I'll have to do what I did when I got openRCT2 on here and reinstall onto the other computer, and copy the files with a USB stick. A bit of a pain, but it works, I guess.

**Comment by TheMathsGod** [comment]
I now cannot seem to be able to reinstall RCT2. After deleting the game, I've tried reinserting the disk, but it just has the option to play the game with no attempt to reinstall. There's just the play button which throws up an error.

**Comment by TheMathsGod** [comment]
A reinstall has given the correct hash file now, so hopefully it should be fixed. I'll close the issue when I know it's working.

**Comment by TheMathsGod** [comment]
Let the music play for a bit, and it's now been fixed.
