### ISSUE TITLE
No registry lookup for RCT2's files

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#765]
Previously in my copy of Open RCT2, it looked for data files in the same place as the original Roller Coaster Tycoon 2's install location (You know, something like C:/Program Files/Infogames Interactive / Roller Coaster Tycoon 2). Now it tries to look for files in the Open RCT2 folder instead, which shouldn't happen since that's not how it worked before.

So I ended up with this flooding the console.
![whataload](https://cloud.githubusercontent.com/assets/4167951/6097847/f325e766-af99-11e4-943b-9a94247c72fb.png)

**Comment by RollingStar** [comment]
ORCT2 will eventually use separate data files from RCT2. Maybe that time is already happening.

**Comment by Superjustinbros** [comment]
But why, may I ask, would be a better thing?

**Comment by PFCKrutonium** [comment]
It will allow for things like Free Graphics Replacements and Music Replacements etc etc etc, so that you don't need to actually own RCT2 to play - Basically what OpenTTD did.

**Comment by Superjustinbros** [comment]
So where am I supposed to copy all my RCT2 stuff to?

**Comment by PFCKrutonium** [comment]
So far as I know, it should still be reading from your normal program files. Hold on while I poke.

**Comment by RollingStar** [comment]
Maybe the ORCT2 team will come up with better formats for all of the files, allowing open replacements as PFCKrutonium says. I personally prefer FLAC files to WAVE files, and regular RCT2 uses WAVE files for the sound. All of RCT2 is designed to be obfuscated and difficult to modify. I think that ORCT2 should be designed with clear data formats that are easy to modify.

**Comment by PFCKrutonium** [comment]
Everything is loading fine on my end... Delete [MyDocuments]/OpenRCT2/config.ini , and see if that fixes it.

**Comment by Superjustinbros** [comment]
Nope, I deleted the config file and it still can't find the game files.
For some reason it also re-creastes the deleted configure file when I try to launch the game after deleting it.

Do you think maybe it has something to do with C:/Program Files/Infogames Interactive / Roller Coaster Tycoon 2 only having the Data, Landscapes, ObjData, Saved Games, Scenarios, and Tracks folders and no other files? DO I also need the original RCT2 exe even though it wasn't required before?

**Comment by PFCKrutonium** [comment]
You should probably have those files, yah. Not 100% sure what may be missing, but it can't hurt to have them in place.

**Comment by IntelOrca** [comment]
You don't need rct.exe. It still looks in data and objdata from your RCT2 install directory. Eventually we will store imported custom objects in the user folder while keeping the official objects in the install directory. The cache created is however stored in the user folder now. Try deleting that.
```documents\OpenRCT2\plugin.dat```

**Comment by Superjustinbros** [comment]
Funny how I could originally run ORCT2 just fine without all these, I mean back in September the only issues I really ran across were the whole shoddy downloading custom files and the game refusing to load when I try to start it after a download attempt.

What other files does the Infogames RCT2 folder include by default, and can I use the files form the GOG release?

**Comment by duncanspumpkin** [comment]
It sounds to me like either the plugin.dat file is broken or your config.ini is pointing to the wrong directory for the install directory. If it started working after deleting plugin.dat then that was probably why. If it is still not working have a look at config.ini and confirm that the directory that it has for the install location is the same as where you have it installed. GOG release works fine for the files required. But you do need to install the game as the registry entries created during the install are required to load the correct directory into config.ini.

**Comment by IntelOrca** [comment]
@duncanspumpkin 
> the registry entries created during the install are required to load the correct directory into config.ini

Are you sure about this?

The directory is only found by checking if the following directories exist in order of:
```
C:\Program Files\Infogrames\RollerCoaster Tycoon 2
C:\Program Files (x86)\Infogrames\RollerCoaster Tycoon 2
C:\Program Files\Infogrames Interactive\RollerCoaster Tycoon 2
C:\Program Files (x86)\Infogrames Interactive\RollerCoaster Tycoon 2
C:\Program Files\Atari\RollerCoaster Tycoon 2
C:\Program Files (x86)\Atari\RollerCoaster Tycoon 2
C:\GOG Games\RollerCoaster Tycoon 2 Triple Thrill Pack
```

**Comment by duncanspumpkin** [comment]
Oh right i never actually looked at config.ini generation just guessed it would do something like look at the reg.

**Comment by PFCKrutonium** [comment]
For the record if you delete the config.ini and use my Launcher (https://github.com/PFCKrutonium/OpenRCT2Launcher) it will regenerate it with the location as located in the registry.

**Comment by Gymnasiast** [comment]
This report is so old, I don't think it applies anymore. The relevant code has seem a lot of changes as well. I think this can be closed.

**Comment by duncanspumpkin** [comment]
I don't see why we don't look up the address in the registry.

**Comment by IntelOrca** [comment]
This issue is open waiting for someone to implement registry lookup. I expect it would also have to handle any compatibility solutions Windows does.

**Comment by IntelOrca** [comment]
The registry code already exists, it just needs to be used correctly when searching for the game if it can't find it in the usual directories.

**Comment by duncanspumpkin** [comment]
#504 covers this better
