### ISSUE TITLE
Rides are making tram sounds

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#7657]
Some rides are making the tram 'bell' sound, while they actually are not a tram. Horses are not trams! Cars are closer to trams but they're still no trams. Lots of cars here, and they all make tram sounds:
https://www.nedesigns.com/park/4091/h2h8-r2-tubiao-action-park/

I think it may have to do with tracked rides using crooked house mode.

Using version 0.2.0 bcd4e9c on Window 8

**Comment by AaronVanGeffen** [comment]
Probably introduced by https://github.com/OpenRCT2/OpenRCT2/pull/6998, which added claxon sound effects to crossing trains.

**Comment by Gymnasiast** [comment]
The map in question has lots of tracks crossing streets.

I think the claxon sounds should be reserved to just trains and trams. That would probably solve 99% of the problem.

**Comment by spacek531** [comment]
I think the sound should depend on the `sound_range` of the vehicle. I have made custom trams, and sometimes they ride on different ride tracks, so already creating a whitelist of ride types and ride track types will be insufficient.

**Comment by IntelOrca** [comment]
It does already but it probably needs revising.

https://github.com/OpenRCT2/OpenRCT2/blob/b043428cf03c0d391f6fd5595e29674fcf4b8ccf/src/openrct2/ride/Vehicle.cpp#L10050-L10054
