### ISSUE TITLE
Feature request: option to use windows interface for saving/loading savegames

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#7658]
I appreciate the effort to make everything aesthetically consistent, but OpenRCT's window for loading and saving savegames is just inferior in functionality to the normal windows window, with more advanced viewing options and easier browsing. I have to manually switch everytime and that's a bit annoying. Can there be an option to use the normal window by default?

**Comment by Gymnasiast** [comment]
One thing I notice is that you keep asking for ways to turn stuff off, rather than requesting fixes or enhancements. Why don't you outline what would make the built-in window better for you? Bypassing the built-in window is something that might be considered as a last resort, if improving the built-in window proves inviable.

**Comment by AaronVanGeffen** [comment]
I think it's a reasonable request. Our load/save window cannot rename files, use bookmarks for quick locations, move files, ...

**Comment by Liampie** [comment]
![ideas](https://user-images.githubusercontent.com/19242088/41231594-c7e77a00-6d83-11e8-980d-30bf1a69046e.png)

Comparison with the windows screen and how I like to see it.

**Comment by thiebert** [comment]
I've been opening a lot of parks with long filenames and I'm unable to read them in the in-game explorer. I have to manually resize the window, which puts it off-center, unless I do even more work to re-align it, or alternatively, open my native file-explorer to read the file names. If this thread is gathering improvements for the file explorer, I'd like to suggest the ability to allow it to open at a larger size consistently.

Alternatively, why re-invent the wheel? Native file explorers are what users are generally accustomed to using, and they're feature-rich already. To match their functionality precisely could be an eventual goal, especially for consistency's sake. However, the time invested to do that is likely immense as compared to allowing users to default to the already-available solution of using their native explorer.

**Comment by AaronVanGeffen** [comment]
Not all of the platforms OpenRCT2 supports provide such a load/save dialog screen. That, and the added consistency you mentioned, favours the approach we have taken, I think. One of the goals is to augment the load screens with park/scenario thumbnails and that sort of thing, to enhance the experience.

I'd argue the current approach is fine for most players, but I can see the need for a setting that bypasses the screen altogether. Someone just needs to pick it up. :)
