### ISSUE TITLE
More music options

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#7660]
1. It would be great if all rides had the option to play all music. Right now, a merry go round can only play merry go round music, and for example no rock music. Similarly a coaster cannot play merry go round music. 

2. In addition to this, it would be cool if you the music dropdown menu not only showed merry go round music as an option, but also with a submenu that allows for a single merry go round tune to be repeated rather than shuffling through the whole 'playlist'.

3. A control failure speeds up merry go round music, which is cool - I used that to my advantage here for example: https://www.nedesigns.com/park/4119/h2h8-r4-incident-at-billy-wonkas/ A while back I played with speeding up/slowing down the other RCT music pieces using the x0.5/x1.25 and so fort options on youtube, and often I thought the effect was incredible. A small adjustment to the speed can result in music with an entirely different feel. This could maybe be a console feature? Speed up/slow down any ride's music, without the ride needing to break down in a specific way.

**Comment by jamtraks** [comment]
I think what would be even cooler would be a way to drag and drop custom audio files and add them to rides. The current method, which i do not quite understand, requires adding audio files to rct2 sub folders and is very confusing to me. I would really like to be able to add my own audio tracks to rides in a more straight forward way. 
Also since most ride music would be best as being small "loops" or repeating clips of songs, there should also be a simple audio editor incorporated into rct2.

**Comment by Patrik356b** [comment]
@jamtracks how is it confusing?
The vanilla Readme states what it supports. 

(although it has been forgiving for me regarding bitrate)

But WAV files get big very quickly and having only two custom audio files isn't ideal with OpenRCT2

**Comment by jamtraks** [comment]
> "and having (only two) custom audio files isn't ideal with OpenRCT2"
Don't you mean "(more than) two custom audio files"?
-Well that's why im suggesting an audio editor that works with waves and mp3s, and hopefully rct2 rides play wavs and mp3s... Anyway im suggesting an audio editor so people can make their own small loops from longer songs.

**Comment by ShadowPhrogg32642342** [comment]
In-universe the Merry-go-round music is different from the others: it is played by an **organ** , not the usual PA system like the other rides. This is why it slows down when the circuit breaker trips (the usual amplifier system would just shut up) or speeds up with a control failure.

**Comment by Gymnasiast** [comment]
Point 1 and 2 are tackled by the new-save-format branch. I don't think 3 would be that useful to most people.
