### ISSUE TITLE
libcrypto now required

### ISSUE THREAD

**Issue by davidhealey** [OpenRCT2/OpenRCT2#7662]
**OS:** Linux Mint 64bit
**Version:** 18.3
**Commit/Build:** Release v0.2.0

The launcher updated my game last night and now when I click the play button it just closes. So I ran the executable in the terminal and it produces this - error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory - I tried installing various libcrypto++ packages including the dev and the i386 but that didn't solve the issue.

It also required libpng16-16 but I was able to install that without issue.

**Comment by Gymnasiast** [comment]
This is not a bug.
