### ISSUE TITLE
Objects and rides invisible in custom scenario

### ISSUE THREAD

**Issue by Soninmyeyes** [OpenRCT2/OpenRCT2#7666]
**OS:** Windows 10
**Version:** 0.2.0
**Build:** e39f89c

**The issue:**
I created a sandbox scenario with as many rides and scenery objects selected as the limits would allow. When I try to use this scenario, an apparently random assortment of ride preview images and scenery objects are invisible (or, in the case of animated objects, replaced by a wobbling square).

Which and how many items are glitched varies each time I start a new park from the scenario or open a park created from it. (For instance, there may be no invisible scenery objects and only a handful of invisible rides, or there may be more objects glitched than not.)

I have experienced this issue for several weeks now, so yes, OpenRTC2 has been opened and closed many times and the issue has persisted.

Based on a suggestion in the forum, in the launcher under Branch, I switched from Develop to Release, and on this occasion, almost all of the objects were glitched.

Forum discussion: https://openrct2.org/forums/topic/2931-scenery-and-rides-not-loading-for-custom-scenario/

**Steps to reproduce:**
1. Create a custom scenario with a lot of rides and objects selected--at or near the maximum in each category. (Note: this glitch does not appear for custom scenarios with only a few rides and objects selected.)
2. Start a new park using that scenario or open a park previously created from the scenario.

**Screenshots / Video:**
![missingrides](https://user-images.githubusercontent.com/40150885/41265872-63b3ec82-6dc2-11e8-8151-ec759c78584b.png)

![openrct2_sceneryglitch_preview gif 014c114e69afa85c970a164028cf5389](https://user-images.githubusercontent.com/40150885/41265609-1d504200-6dc1-11e8-8a9f-9f921acff9aa.gif)

**Save game:**
[Free Play.zip](https://github.com/OpenRCT2/OpenRCT2/files/2092285/Free.Play.zip)

**Comment by Gymnasiast** [comment]
I haven't yet investigated the file, but by the looks of it the game ran out of room for images.

**Comment by Soninmyeyes** [comment]
That's what I seems like to me, though if so, should the maximum allowed
items be adjusted?

**Comment by IntelOrca** [comment]
What happens if you load this saved game into vanilla?

**Comment by Soninmyeyes** [comment]
Does this explain the inconsistent behavior, where sometimes most of the
images load and sometimes most are missing?

**Comment by Gymnasiast** [comment]
@IntelOrca @AaronVanGeffen This is hardly the first user running into image limits. Are these limits dictated by SV6? It doesn't look like they are to me, but I wanted to check first.

**Comment by IntelOrca** [comment]
@Gymnasiast they aren't.

**Comment by IntelOrca** [comment]
@Gymnasiast The limit can be raised, but keep in mind our current ranges. They probably need to be reorganised.

```
0x00000 = G1
0x0726E = OBJECTS
0x4F2C0 = G2
0x60000 = CSG
0x70000 = TEMP
0x7FFFF = MAX
```

**Comment by Gymnasiast** [comment]
If I read that correctly, we have room for nearly 70000 images for G2 (0x60000 - 0x4F2C0). That's quite a big amount for the handful of images that reside there. If we change the start of G2 to 0x5F000, there is still room for 4096 images in G2, but we also gain room for 40000 extra object images.

**Comment by IntelOrca** [comment]
@Gymnasiast The other bits are used for colour remapping.

**Comment by Gymnasiast** [comment]
Ok.
If I subtract 0x726E from 0x4F2C0, I get 0x48052, or 294994. However, MAX_IMAGES is set to 262144. Is there any reason for this difference?

**Comment by IntelOrca** [comment]
I don't think I ever changed `MAX_IMAGES`, that is just what it was in vanilla.

**Comment by Gymnasiast** [comment]
The only thing I can imagine is 0x80000 - 200000. (0x4F2C0 == 324288)

**Comment by Gymnasiast** [comment]
Can't reproduce this issue any more, at least not on the save you provided. If you have save that still does exhibit this behaviour, please let us know.
