### ISSUE TITLE
3-wide paths are sometimes handled poorly

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#7672]
**OS:** [Windows 10]
**Version:** [0.2.0]
**Commit/Build:** [7373987]

My parks often have a 3-wide paths as the main path in the park
When paths are attached to it, the game often fails to disable the correct path tiles, leading to guests getting lost. This is an inconvenience that has been in the game for a long time already.

![image](https://user-images.githubusercontent.com/6469413/41334277-55063a0e-6ee5-11e8-9c3b-0583a642a5b5.png)

In the above image, peeps that walk on the red path will walk around in circles indefinitely because they cannot get to the exit, and they will end up getting lost. There is no way for them to get to the path with the blue line.

I think this behaviour is why in the original RCT2 big paths were turned into a grid.

**Save game:**

[3widepaths.zip](https://github.com/OpenRCT2/OpenRCT2/files/2096896/3widepaths.zip)

**Comment by Gymnasiast** [comment]
Summoning @zaxcav .

**Comment by deurklink** [comment]
Here's another park which has huge issues with the 3-wide paths:
[Multiplayer park - Server 1 Round 10.zip](https://github.com/OpenRCT2/OpenRCT2/files/2106879/Multiplayer.park.-.Server.1.Round.10.zip)

The paths with wide path flag are white:
![multiplayer squares 10 2018-06-15 18-55-52](https://user-images.githubusercontent.com/6469413/41480196-e2a594ce-70cd-11e8-901f-0a6ea6d34a98.png)

**Comment by zaxcav** [comment]
I thought I'd seen somewhat recently that the wide paths still excluded the "grid" mentioned in the original post, but clearly not as evidenced in the screen shot from @deurklink.

I don't recall, but I presume I deactivated this in the code that set the wide path flags to cut down on intersections in the heuristic search.
The thing to do to resolve this would be to reactivate this "grid".
Question is how detrimental this will be to the heuristic search which isn't that great in the first place.
In the worst case, the grid will run right up the middle of a 3 wide path turning the entire path into intersections == death for the current heuristic search.
In the best case, some balancing may be needed: trade off between grid size and/or heurisitic search limits.

Personally I'd vote for an alternative solution. However improving the wide path flag calculation would be non-trivial.

**Comment by deurklink** [comment]
Maybe until we have better pathfinding, a good solution would be to re-enable the grid, but make it larger. In the above screenshots the problems would already be a lot smaller if the paths connected in just a few places.

**Comment by L3mmy** [comment]
I have a Build your own Six Flags map and i used 5-wide path, and guest used them in line, but they only make 3 line, 1 left, 1 middle, 1 right
