### ISSUE TITLE
Rides show up as random numbers in guest's ride list

### ISSUE THREAD

**Issue by youredrowning** [OpenRCT2/OpenRCT2#7674]
**OS:** macOS 10.13.5
**Version:** 0.2.0
**Commit/Build: 7fbbce5

Rides have a custom name or standard name, but show up as random number in guests' favourite rides.
<img width="193" alt="screen shot 2018-06-13 at 17 51 21" src="https://user-images.githubusercontent.com/35399927/41363031-33f94628-6f33-11e8-970b-7ca04da3ef95.png">
<img width="316" alt="screen shot 2018-06-13 at 17 51 37" src="https://user-images.githubusercontent.com/35399927/41363032-34152b40-6f33-11e8-83d5-68abfb179240.png">
16 = Observation Tower 1

**Comment by Gymnasiast** [comment]
Sounds very similar to https://github.com/OpenRCT2/OpenRCT2/issues/7454.

**Comment by youredrowning** [comment]
Does indeed, this bug however is with favourite rides only. In the "Rides"-list, they show up with the full name, see below 

<img width="340" alt="screen shot 2018-06-13 at 18 11 55" src="https://user-images.githubusercontent.com/35399927/41363894-5e8af38a-6f35-11e8-968c-584f74eee962.png">

**Comment by Gymnasiast** [comment]
I know, this is a different bug, but most likely one with the same cause. That's why I linked to #7454.
