### ISSUE TITLE
Camera stuck on the map's edge

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#7676]
**OS:** Windows 10
**Version:** 0.2.0
**Commit/Build:** 6b22a9d

Sometimes the camera gets stuck on the map's edges. Rotating the map moves the edge the camera gets stuck on. In the map window, you can see that the view area is very small for how far it is zoomed out.

![](https://cdn.discordapp.com/attachments/450316748734988289/456554823517601813/Show.png)
It's a bit difficult to see, but the 4 corners of the viewport area are inside the red circle. Setting the window scale to something else will fix this weird behaviour, and the viewport area indicated on the map reflects it.

**Steps to reproduce:**
1. Load the attached saved game
2. Try moving the camera around

This was reported in a Discord server. I don't know how to reproduce creating a saved game with a broken camera. He said that it was fine when he saved the park, but when he opened it the next time the camera was glitched out.

I'm guessing this has something to do with the zoom level.

**Comment by IntelOrca** [comment]
I was able to reproduce it by going into the scenario editor, making the map 256x256, saving the landscape then loading it again.
