### ISSUE TITLE
problem with server list

### ISSUE THREAD

**Issue by 60trainhunter** [OpenRCT2/OpenRCT2#7677]
**OS:** [Windows 10]
**Version:** [ 0.2.0-2]
**Commit/Build:** [6b22a9d]

 Please look at this asap!
servers are there and are able to log in if you faved them! but they do not show the green orb instead they show dark red orb. and they are advertised. they are online too. the Man of Teal servers.
![servers are active but not showing green orb](https://user-images.githubusercontent.com/30908785/41379350-bd790cb6-6f2f-11e8-8639-f669c700ff96.PNG)

- [ ] Reproducible in RCT2 (vanilla)?
- [yes] Specific to multiplayer?

**Steps to reproduce:**
1.  load a server a see if another player can see it
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by Broxzier** [comment]
They are red because their network version does not match yours, you can see your version on the bottom-right of the server list. The first build with version number 0.2.0-2. is only about an hour old. The server still use 0.2.0-1.
