### ISSUE TITLE
Error building through cmake on macOS

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/OpenRCT2#7685]
**OS:** macOS
**Version:** 0.2.0
**Commit/Build:** ac0c1ba94ae3bb8b76f93d47cd5978be4c5934e4

Building through cmake on macOS fails due to promoted warnings in OpenSSL:

```
[125/388] Building CXX object CMakeFiles/libopenrct2.dir/src/openrct2/core/Crypt.OpenSSL.cpp.o
FAILED: CMakeFiles/libopenrct2.dir/src/openrct2/core/Crypt.OpenSSL.cpp.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DOPENGL_NO_LINK -D__ENABLE_LIGHTFX__ -I/usr/local/Cellar/libzip/1.5.1/include -I/usr/local/Cellar/jansson/2.11/include -I/usr/local/Cellar/libpng/1.6.34/include/libpng16 -I/usr/local/Cellar/openssl/1.0.2o_1/include -I/usr/local/opt/freetype/include/freetype2 -Wnull-dereference -Wnon-virtual-dtor -Wmissing-variable-declarations -Wmissing-field-initializers -Wunreachable-code-break -Wrange-loop-analysis -Wdocumentation -Wredundant-decls -Wignored-qualifiers -fstrict-overflow -Wstrict-overflow=1 -fstrict-aliasing -Werror -Wundef -Wmissing-declarations -Winit-self -Wall -Wno-unknown-pragmas -Wno-missing-braces  -Wno-comment -Wshadow -Wnonnull -DDEBUG=0 -Wno-error=objc-method-access -fPIC -std=gnu++17 -MD -MT CMakeFiles/libopenrct2.dir/src/openrct2/core/Crypt.OpenSSL.cpp.o -MF CMakeFiles/libopenrct2.dir/src/openrct2/core/Crypt.OpenSSL.cpp.o.d -o CMakeFiles/libopenrct2.dir/src/openrct2/core/Crypt.OpenSSL.cpp.o -c ../src/openrct2/core/Crypt.OpenSSL.cpp
In file included from ../src/openrct2/core/Crypt.OpenSSL.cpp:24:
In file included from /usr/local/Cellar/openssl/1.0.2o_1/include/openssl/pem.h:70:
In file included from /usr/local/Cellar/openssl/1.0.2o_1/include/openssl/x509.h:87:
/usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ecdsa.h:295:14: error: parameter 'flags' not found in the function declaration [-Werror,-Wdocumentation]
 *   \param  flags flags value to set
             ^~~~~
/usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ecdsa.h:295:14: note: did you mean 'name'?
 *   \param  flags flags value to set
             ^~~~~
             name
/usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ecdsa.h:301:14: error: parameter 'ecdsa_method' not found in the function declaration [-Werror,-Wdocumentation]
 *   \param  ecdsa_method  pointer to existing ECDSA_METHOD
             ^~~~~~~~~~~~
/usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ecdsa.h:302:14: error: parameter 'name' not found in the function declaration [-Werror,-Wdocumentation]
 *   \param  name name to set
             ^~~~
3 errors generated.
[130/388] Building CXX object CMakeFiles/libopenrct2.dir/src/openrct2/core/FileScanner.cpp.o
ninja: build stopped: subcommand failed.
```

The Xcode project lives by its own rules and appears to be unaffected.

**Comment by AaronVanGeffen** [comment]
Patching out this line in CMakeLists.txt makes it work again:
https://github.com/OpenRCT2/OpenRCT2/blob/56250b4/CMakeLists.txt#L109

@janisozaur Do you have a preferred way of dealing with this? We could just leave it out on macOS, I guess, but perhaps we shouldn't apply it to libraries in the first place.

**Comment by janisozaur** [comment]
You seem to be using old OpenSSL, does it still happen if you use current version? I can compile just fine even with this warning enabled.

**Comment by AaronVanGeffen** [comment]
On Linux, I am able to compile to compile just fine with 1.1.0h as well. On macOS, however, I have both 1.0.2o and 1.1.0h installed through homebrew due to various package dependencies. It seems cmake selects 1.0.2o instead — and can't find 1.1.0h even when I change the version requirement here:
https://github.com/OpenRCT2/OpenRCT2/blob/56250b4/src/openrct2/CMakeLists.txt#L47

I noticed we've already got a hack for macOS here:
https://github.com/OpenRCT2/OpenRCT2/blob/56250b4/src/openrct2/CMakeLists.txt#L9

When amended to read `/usr/local/opt/openssl@1.1/lib/pkgconfig` instead, cmake still picks the wrong version…

I'll investigate, but I'm really doubting whether the added warning is worth all this.

**Comment by janisozaur** [comment]
In case of this warning I'd have to agree.

We already fixed what required fixing, I think you can submit a fix for this issue: comment out the warning, leave a comment why it is disabled.
