### ISSUE TITLE
Request: Further refinements of staff list scrolling

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#7688]
**OS:** [Windows 8]
**Version:** [e.g. 0.2.0]
**Commit/Build:** [e39f89c]

The staff list has been updated to work better for long staff names when the window is embiggened, but it is not very good for normal-length staff names in combination with long task names:
![octagon park 2018-06-14 18-15-27](https://user-images.githubusercontent.com/26573303/41450341-db37e7bc-701b-11e8-99b7-9c55b4a95445.png)
In this example, there's lots of empty space next to the mechanics' names (squiggly line) ... and yet, the listing of what they're doing is cut off in a few places (circles).
There's also more space than necessary between the task assignment icons and the name of the task they're currently doing.

There are a few ways this could be resolved... I think the best (though also perhaps the most labor-intensive, coding-wise) would be to have the window detect the length of strings in each column and resize that column to fit the data inside it (with upper limits to prevent the staff names alone from taking up the entire width). 

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Hire several mechanics, wait for them to inspect/repair rides.
2. Open the staff window to the mechanics tab.
3. Stretch the window to its maximum width.

**Comment by AaronVanGeffen** [comment]
Hmm, the 50-50 split might not have been the best choice for normal scenarios, I agree. As you said, the ideal way of fixing this would be to detect string length and adjust the column width accordingly, but those are rather expensive operations in our current framework.

Perhaps we should opt for a 40-60 split instead? Or even 30-70?

**Comment by Patrik356b** [comment]
Either that, or if it was possible, allowing the user just to drag a divider to manually specify it.

**Comment by ocalhoun6** [comment]
Seems like it wouldn't be _that_ resource-intensive to have a small function that went through the names of all staff and determined the length of the longest string in the set. Then have that function run when:
-Opening a new scenario or saved game
-Hiring new staff
-Renaming staff
And save the result as a variable.
Then the staff window could just reference that variable in deciding how wide the columns should be. (Defaulting to the vanilla RCT2 default setup if the variable is somehow not set.)

The function _would_ be relatively resource-intensive ... but it wouldn't need to run very often. And even with a maxed-out staff list (what is the max ... like, 200, right?) I doubt the delay would be noticeable from a user's perspective.

**Comment by AaronVanGeffen** [comment]
I'd like to keep the columns split irrespective of staff names. If we'd always make the name column as wide as the widest name, it'd be too easy to abuse in multiplayer.

Currently, we're using a 50:50 split:
![offset_50_50](https://user-images.githubusercontent.com/604665/44006356-81791084-9e83-11e8-9375-91944bd71889.png)

Earlier, a 30:70 split was proposed. This leads to an unacceptable cut-off, imo:
![offset_30_70](https://user-images.githubusercontent.com/604665/44006354-8130331e-9e83-11e8-8a7f-6c292b3326a0.png)

Even 40:60 has this issue, to some extent. A compromise would be a 42:58 split:
![offset_42_58](https://user-images.githubusercontent.com/604665/44006355-815829e6-9e83-11e8-94e0-04ef8c48e2bc.png)

This might not be wide enough for all languages, however. Ideally, a player could drag the column divider themselves, but our widget system simply doesn't allow for this to happen (yet).

Either way, the last picture sees a 16% width increase for the action column. Good enough?
