### ISSUE TITLE
Deleting a 0-tile maze gives an overflow error that will take all your money away

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#7689]
**OS:** [Windows 8]
**Version:** [e.g. 0.2.0]
**Commit/Build:** [e39f89c]

![octagon park 2018-06-14 20-51-49](https://user-images.githubusercontent.com/26573303/41450569-7a45026c-701d-11e8-9443-abf0ac120a7d.png)

**Steps to reproduce:**
1. Build a 1-tile maze.
2. Fill in all the pathways on the maze (the one tile will disappear).
3. Close the construction window (the ride window will open, centered on the bottom corner of the map).
4. Demolish the (nonexistant) ride (the confirmation window will appear, as in the screenshot, and instead of granting you money, it threatens to remove a ludicrous amount).

- [ ? ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Comment by Gymnasiast** [comment]
Oh joy, another maze bug. The value is INT32_MIN, by the way.

**Comment by jensj12** [comment]
Returning `MONEY_UNDEFINED` is fine I think, it should just be caught by the caller. For demolishing rides, it should indeed give $0, but attempting to refurbish such a ride should generate an error instead of being completely free.

**Comment by moTechPlz** [comment]
If there is no maze designed when you exit the maze construction window, no ride should be created or ride window opened. This is also the same behaviour when you delete all track pieces of a tracked ride and then close the ride construction window. This will prevent;
- Ride window centering on a 0.0 location
- Wrong demolish return calculated

**Comment by felixpelletier** [comment]
> ride_try_get_origin_element

But then, what if the track *is* too large?
