### ISSUE TITLE
Problem with guests freezing on certain tiles of path

### ISSUE THREAD

**Issue by JappyNE** [OpenRCT2/OpenRCT2#7690]
**OS:** [Windows 10]
**Version:** [ 0.2.0]
**Commit/Build:** [fdb1d198]

So this error is quite a strange one but it's been bugging me quite a lot.
Peeps seem to be frozen on certain tiles of path. They walk onto it, bunch together and start complaining about how busy it is which makes them unhappy and brings down my park rating. After a while though they do move on but freeze just a few tiles further again. From a previous tip I used the debugging tools and it does seem something is wrong with the tiles they are walking on and nothing I do seems to fix it.

**Screenshots / Video:**
![problem1](https://user-images.githubusercontent.com/40169350/41457259-6114d6da-7083-11e8-97ef-ba9a059b1f40.PNG)

**Save game:**
[BB - Problem.zip](https://github.com/OpenRCT2/OpenRCT2/files/2105252/BB.-.Problem.zip)

**Comment by deurklink** [comment]
There's a hidden track on the paths, right? I see guests on some sort of bicycle. Also, the blocked tiles can only come from the peep crossing behavior.

**Comment by JappyNE** [comment]
Yes, there's path on the tiles. What do you mean with the peep crossing behaviour?

**Comment by deurklink** [comment]
Recently, behaviour was added which makes peeps wait for trains if they cross a path. That's also what is happening here.

**Comment by JappyNE** [comment]
Can that be undone some way?

**Comment by deurklink** [comment]
You could play on the release version instead of develop, it doesn't have this peep behaviour implemented.

**Comment by JappyNE** [comment]
Update on this: I tried deleting the ride in the release version, and opened the save in the dev version without it but guests still are frozen solid on the tiles that used to have the ride cross it. Can this be fixed, or better, can this ride work crossing path in the dev version wthout the peep problem?

**Comment by Gymnasiast** [comment]
Another affected save: https://www.nedesigns.com/park/4013/riverland/download/

The proposed solution is to limit the peep crossing behaviour to just miniature railways. This should not be too difficult to achieve.
