### ISSUE TITLE
Servers do not get registered on master server list

### ISSUE THREAD

**Issue by 60trainhunter** [OpenRCT2/OpenRCT2#7696]
**OS:** [Windows 10]
**Version:** [0.2.0-3]
**Commit/Build:** [0cf256a]

Some thing is wrong with Server list. It not registering MOT, Mozar's Servers and other servers. they are all advertised and up to date. Please Fix this all I've been getting is this screenshot. I am an Admin of MOT i even tried restarting MOT's servers too nothing. please tell me i am not the only one experiencing this.
![some thing is wrong with server list](https://user-images.githubusercontent.com/30908785/41471572-089fa1b6-7082-11e8-9d86-2be5c9dc2cca.PNG)

- [ ] Reproducible in RCT2 (vanilla)?
- [yes] Specific to multiplayer?

**Steps to reproduce:**
1. Open Server List and see if you see MOT's and Mozar's servers and provide a screenshot of the list
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by deurklink** [comment]
I am experiencing the same. Servers can still be reached through IP. It seems advertising is broken because servers that run on older version still show.

**Comment by Broxzier** [comment]
A quick test shows that advertising does work at first, but the server disappears from the master server after a few minutes.

May be related to https://github.com/OpenRCT2/OpenRCT2/pull/6978

**Comment by telk5093** [comment]
So am I. My headless servers (using 0.2.0-3) are not registered in master server, too.
0.2.0-2(6b22a9d) works fine for me.

**Comment by Broxzier** [comment]
@telk5093 0cf256a (with network version 0.2.0-3) _does_ advertise successfully for me. Check https://servers.openrct2.io/ when starting to host to see if yours does not appear. They just seem to stop advertising after a few minutes.
