### ISSUE TITLE
Allow users/groups/permission commands from the console

### ISSUE THREAD

**Issue by jochembroekhoff** [OpenRCT2/OpenRCT2#7698]
**OS:** ArchLinux (ARM)
**Version:** 0.2.0-master (0.2.0-2 from AUR)
**Commit/Build:** 6ced8e2

When running a multiplayer server, all users and group settings need to be mannualy modified in `groups.json` and `users.json`. This can be quite tricky if the host is running in headless mode.
For example when you want to change the group of the user that joined the first, you need to know somehow the user's ID to add it to `users.json` and assign it to a group.

It would be really handy if there were commands like `groups <add|edit|remove> [<args>]` and `users <list|edit> [<args>]`.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**
1. Start a server in headless mode.
2. Try to modify the group of the first user that joins.

**Comment by whiskeytangofoxy** [comment]
To add to this issue: even if you know a user's ID hash (from looking at the `keys/` directory on the client computer, for example), I believe a `groups.json` is still necessary to provide anything more than Admin-level permissions to that user once connected. As `groups.json` is not generated either, I think it should be either generated or included with some default roles.

**Comment by hibroseph** [comment]
Is there still any interest in this? I ran into this issue and might be interested in working on this.

**Comment by Broxzier** [comment]
This is already possible through the plug-in API.

**Comment by hibroseph** [comment]
@Broxzier can you link me to where this public API is/documented.

**Comment by ocalhoun6** [comment]
But the plug-in API is not easily accessible while in-game.

Of course, there's always #13471

**Comment by Broxzier** [comment]
@hibroseph https://github.com/OpenRCT2/OpenRCT2/blob/develop/distribution/openrct2.d.ts

> @ocalhoun6 But the plug-in API is not easily accessible while in-game.

No it isn't. It's accessible from the interactive console.
