### ISSUE TITLE
Severe crash during multiplayer

### ISSUE THREAD

**Issue by meatbee** [OpenRCT2/OpenRCT2#7708]
**OS: Win 7**
**Version: 0.2.0**
**Commit/Build: 65d1c7f**

Game crashes so hard in multiplayer that entire computer is rendered unresponsive for upwards of 10 minutes (task manager is unresponsive/crashes repeatedly, after 2/3 minutes mouse disappears and keyboard shortcuts stop working).

- [nope] Reproducible in RCT2 (vanilla)?
- [The two times it has happened have been in multiplayer] Specific to multiplayer?

**Steps to reproduce:**
1. Be in multiplayer game
2. ? I think it has something to do with ride building, as it generally happens when someone is greifing a server by building crash rides everywhere.

**Comment by Gymnasiast** [comment]
I'm afraid we cannot do anything without a dump or specific steps to reproduce.
