### ISSUE TITLE
Missing steep slope segments for Junior RollerCoaster

### ISSUE THREAD

**Issue by Dente222** [OpenRCT2/OpenRCT2#7710]
**OS: Windows 7 **
**Version: 0.2.0**
**Commit/Build: 0ec3ccd** 

Its impossible to build steep slopes in Junior Roller Coaster
they are not in the editor

**Screenshots / Video:**
On picture you can see that same Roller Coaster have steep slopes but you cant build them on your own
![missing slopes](https://user-images.githubusercontent.com/9505159/41570709-d00956ce-7367-11e8-925a-1179570a6494.png)

backup if image will not gonna show up
[https://i.imgur.com/F3Uy82q.png](url)

**Comment by Gymnasiast** [comment]
You need to build a "Classic Mini Roller Coaster" or enable the "Display all track pieces" cheat. The Junior Roller Coaster trains do not support steep inclines - their use on the Arachnophobia is a temporary hack until we can probably import their RCT1 counterparts.
