### ISSUE TITLE
Invisible turns on Hairpin Coaster

### ISSUE THREAD

**Issue by youredrowning** [OpenRCT2/OpenRCT2#7711]
**OS:** macOS
**Version:** 10.13.5
**Commit/Build:** 0ec3ccd

Both left-hand and right-hand curve are invisible and the ride 'floats' in mid-air. 

<img width="1084" alt="screen shot 2018-06-19 at 17 51 47" src="https://user-images.githubusercontent.com/35399927/41609142-64aa684a-73ea-11e8-8c7d-a05115ce652d.png">
<img width="1569" alt="screen shot 2018-06-19 at 17 55 20" src="https://user-images.githubusercontent.com/35399927/41609144-64dd264a-73ea-11e8-8bc5-a4c069c1706e.png">

**Comment by Gymnasiast** [comment]
Cannot reproduce. Please upload your save.

**Comment by jensj12** [comment]
The inverted hairpin coaster has no banked turns as far as I know. Those track pieces shouldn't have been enabled in the first place.

**Comment by Gymnasiast** [comment]
Thanks, Jens, I can reproduce it now!

I think this a bug introduced with JSON objects.
