### ISSUE TITLE
Feature: Have the virtual floor show land not owned by park as an obstacle

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#7713]
**OS:** [Windows 8]
**Version:** [e.g. 0.2.0]
**Commit/Build:** [8a9dfa6]

Sometimes -- especially when building high up, building in places where the owned land is narrow/restrictive, or building around construction rights, it would be really helpful if the virtual floor showed un-owned land as an obstacle.

Currently, it displays as if un-owned land is a perfectly valid place to build:
![pleasure island 2018-06-19 23-37-41](https://user-images.githubusercontent.com/26573303/41641413-0e745e6a-741a-11e8-8c3c-8c1f4b6771a6.png)

It would be helpful sometimes, though, for the virtual floor to show the white rim of being blocked by something when it buts up against the park boundary. Basically, it could read un-owned land just like an obstacle ... just like the air-powered coaster track in the screenshot above.

Edit: another screenshot that more simply displays the 'issue':
![forest frontiers 2018-06-19 23-44-04](https://user-images.githubusercontent.com/26573303/41641613-abc68652-741a-11e8-927a-fc5c7f858795.png)
It's showing the trees outside the owned land as obstacles ... but I think it would be much more helpful to show the un-owned land itself as an obstacle.

**Steps to reproduce:**
1. Use the virtual floor feature near the park boundary.

**Comment by Umdlye** [comment]
Implemented by #7837
