### ISSUE TITLE
ride flags 7, 16, 18

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#7720]
ride flag 7: `RIDE_ENTRY_FLAG_DISABLE_WANDERING`

Allows boats to wander for several minutes before attempting to find their way to the station. When this flag is enabled on a boat ride, boats immediately attempt to go to the station. 
https://github.com/OpenRCT2/OpenRCT2/blob/c640427d89065595a962d9c1f3ad34c8e59a2b46/src/openrct2/ride/Vehicle.cpp#L4634

ride flag 16: `RIDE_ENTRY_FLAG_DISABLE_DOOR_CONSTRUCTION`

Disallows placing walls on the same tile as a track, I think.
https://github.com/OpenRCT2/OpenRCT2/blob/c640427d89065595a962d9c1f3ad34c8e59a2b46/src/openrct2/world/Wall.cpp#L88

ride flag 18: `RIDE_ENTRY_FLAG_DISABLE_COLLISION_CRASHES`

Disallows vehicles from crashing into each other and exploding.
https://github.com/OpenRCT2/OpenRCT2/blob/c640427d89065595a962d9c1f3ad34c8e59a2b46/src/openrct2/ride/Vehicle.cpp#L8390
https://github.com/OpenRCT2/OpenRCT2/blob/c640427d89065595a962d9c1f3ad34c8e59a2b46/src/openrct2/ride/Vehicle.cpp#L8712

**Comment by Krutonium** [comment]
Flag 18 seems like it would be a handy cheat.

**Comment by Gymnasiast** [comment]
This should be paired with an update to JSON objects.

**Comment by Gymnasiast** [comment]
Flag 16 makes it impossible to build doors over the track. It is only set on the Spinning Roller Coaster.

**Comment by spacek531** [comment]
Looking in the vanilla rides, it appears no rides actually use flag 7 in the object files themselves. How this can be, I do not know, since vanilla rides wander properly whereas custom rides make a beeline for the station.

**Comment by spacek531** [comment]
I made an error with flag 7, it does not *allow* wandering, but *disallows* wandering. So I will update the PR accordingly.
