### ISSUE TITLE
Feature request: json file type describe colors by index

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#7721]
X123M3-256's RCT2RideGenerator describes default colors using the color's index. It would be nice if I could do the same in the json format so I don't have to remember the names of every single color I want, since I have the indexes almost memorized.

Color | Index
-|-
Black | 0
Gray | 1
White | 2
Dark purple | 3
Light purple | 4
Bright purple | 5
Dark blue | 6
Light blue | 7
Icy blue | 8
Dark water | 9
Light water | 10
Saturated green | 11
Dark green | 12
Moss green | 13
Bright green | 14
Olive green | 15
Dark olive green | 16
Bright yellow | 17
Yellow | 18
Dark yellow | 19
Light orange | 20
Dark orange | 21
Light brown | 22
Saturated brown | 23
Dark brown | 24
Salmon pink | 25
Bordeaux red | 26
Saturated red | 27
Bright red | 28
Dark pink | 29
Bright pink | 30
Light pink | 31

**Comment by Gymnasiast** [comment]
Memorising indices isn't easier than remembering colour names, I'd say. I'm not sure that allowing RCT2 colour indices is going to make creating objects easier in the long run.
