### ISSUE TITLE
Asks to save when leaving server

### ISSUE THREAD

**Issue by lennon12** [OpenRCT2/OpenRCT2#7725]
**OS:** [Windows 7 Ultimate]
**Version:** [e.g. 0.2.0-119]
**Commit/Build:** [c640427]

When I leave a multiplayer game (ones that I do not host), it asks if I want to save. What does this mean?

Reproducible in RCT2 (vanilla)? - No
Multiplayer Specific? - Yes

**Steps to reproduce:**
1. Leave a multiplayer game

**Comment by AaronVanGeffen** [comment]
Well, it allows you to make a local copy of the scenario. Can be useful if a remote server unexpectedly crashes or something.
