### ISSUE TITLE
Track Designer and Track Designs Manager Sporadically Crashing

### ISSUE THREAD

**Issue by Soninmyeyes** [OpenRCT2/OpenRCT2#7727]
**OS:** [Windows 10
**Version:** 0.2.0-120
**Commit/Build:** 2e36253

The Track Designer and Track Designs Manager are crashing on load most of the time, apparently at random. If the Track Designs Manager manages to load, if I then try to import a design using the Install New Track Design tool, the game crashes (so far, that's happened every time). There are no error messages. See the videos attached.

I found two other issues related to the Track Designs Manager crashing (#2741 and #4525), but they occurred under different conditions.

**Steps to reproduce:**
1. Try to open Track Designer or Track Designs Manager
2. Most of the time, the game will simply shut down.
3. If Track Designs Manager loads successfully, try to use Install New Track Design.
4. Once you select the file and try to load it, the game will close.

**Screenshots / Video:**

Attempt to open Track Designer:
![opentrackdesignercrash](https://user-images.githubusercontent.com/40150885/41810982-0c8e8fe0-76d5-11e8-811a-3e0b78c10c3b.gif)

Attempt to open Track Designs Manager:
![opentrackdesignsmanagercrash](https://user-images.githubusercontent.com/40150885/41810983-10099084-76d5-11e8-9ab3-840e2f81b875.gif)

Attempt to open file with Install New Track Design:
![installnewtrackdesigncrash](https://user-images.githubusercontent.com/40150885/41810985-1271d0b6-76d5-11e8-88ef-9678c79dfb92.gif)

**Comment by AaronVanGeffen** [comment]
Likely related to https://github.com/OpenRCT2/OpenRCT2/issues/7707
