### ISSUE TITLE
Custom Scenario crashes game

### ISSUE THREAD

**Issue by mimmimine123** [OpenRCT2/OpenRCT2#7728]
The game starts very fast, I search for one scenario I'd like, but then I decided to create a custom scenario but as soon as I clicked the small button, the game froze and then crashed. Is it a "my computer problem" or something I missed?

**Comment by AaronVanGeffen** [comment]
You've left out quite a bit of information. What platform are you on? What build are you using? And could you attach a zip of the scenario in question?

**Comment by AaronVanGeffen** [comment]
See #7707, #7727.

**Comment by mimmimine123** [comment]
Sorry, I read both of the two threads but I cannot understand what is the problem... By the way, thank you

**Comment by mimmimine123** [comment]
I'm on Windows 10, the version is 0.2.0-124, and I mean when I select the "Scenario Editor"

**Comment by AaronVanGeffen** [comment]
Then you're experiencing the same issue as the issues linked describe. There's little you can do about it. Easiest workaround is to use an older build, like the 0.2.0 release.

**Comment by mimmimine123** [comment]
Thank you very much 👍
