### ISSUE TITLE
macOS builds lack title sequences

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#7734]
**OS:** macOS
**Version:** 0.2.0+
**Commit/Build:** f963f969c10229a07b10a82a2b200f4ca98a1bb3

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

macOS builds lack title sequences. Viewing the package contents reveals an empty `resources/title` directory

**Comment by IntelOrca** [comment]
Do you know when this started happening?

**Comment by AaronVanGeffen** [comment]
```
version="0.2.0"
zipname="title-sequence-v$version.zip"
liburl="https://github.com/OpenRCT2/title-sequences/releases/download/v$version/$zipname"
```

It seems someone was a bit overzealous when they changed the version info. We did not release a new title sequence for v0.2.0.

**Comment by IntelOrca** [comment]
This is quite a bad issue, we should probably do a new release because of this.

**Comment by AaronVanGeffen** [comment]
I agree, this does not look good. Let's discuss options in the team chat.
