### ISSUE TITLE
why is it necessary to open a port for others to join a server?

### ISSUE THREAD

**Issue by jamtraks** [OpenRCT2/OpenRCT2#7742]
**OS:** win 32 bit
**Version:** current version
**Commit/Build:** na

I haven't been able to start a server of my own, and it seems like other players are having the same frustration, because the server they create doesn't actually show up for other players to see/join unless they take many steps to open a "port" through their internet service provider.
Could there be some way to alter the openrct2 software so that opening a port isn't necessary? 

**Steps to reproduce:**
1. try starting a server without opening ports and nobody can see or join the server.
2.

**Comment by IntelOrca** [comment]
> open a "port" through their internet service provider

I don't think it is common for ISPs to block ports, usually all you need to do is open them on your gateway (router).

> Could there be some way to alter the openrct2 software so that opening a port isn't necessary?

There are a few workarounds such as hole punching or UPnP (#2661) but they are not easy to implement.

**Comment by qwertychouskie** [comment]
Some code could probably be borrowed from SuperTuxKart (https://github.com/supertuxkart/stk-code) as it has full punch-through support for both local and global games (and it's also GPL3).  https://github.com/supertuxkart/stk-code/search?q=stun&unscoped_q=stun

Note that if you want to test this functionality, you'll need the git version, and to launch with the `--online` flag.

**Comment by janisozaur** [comment]
While certainly nice, I believe STUN cannot cater for TCP, only for connection-less protocols. It would require us to have the connection implemented in the application layer.

**Comment by qwertychouskie** [comment]
STK uses enet which has a reliable mode (and is probably better for games than TCP).
