### ISSUE TITLE
Enable Closer Zoom Levels

### ISSUE THREAD

**Issue by Krutonium** [OpenRCT2/OpenRCT2#775]
On some Higher resolutions, it starts to become difficult to see anything... Not super important at the moment, as it would probably take a fairly large amount of time to get this working.

**Comment by mrtnptrs** [comment]
I would also really like to be able to zoom closer on high resolutions, as it is then also for me now difficult to see everything. Would this indeedly be much work?

**Comment by PFCKrutonium** [comment]
I was talking to @IntelOrca  and it very well may be a fair sum of work, ye.

**Comment by adrian17** [comment]
> it starts to become difficult to see anything...

Not just the game elements themselves, but the whole interface is harder to read. Zooming wouldn't help with this.

It should be possible to make a game use a smaller resolution than the window and before blitting it, upscale it to the window resolution with SDL_gfx.

**Comment by duncanspumpkin** [comment]
This would be a major pain to implement and would have to be left until reversing is finished. As an interim I think its best to do what @adrian17 suggests and just put it at a lower resolution and expand it that way.

**Comment by Phyxion** [comment]
+1, I can hardly see anything at 1440p.

**Comment by IntelOrca** [comment]
This feature should **not** be expected any time soon.

**Comment by Phyxion** [comment]
What about the solution adrian mentioned (maybe as a temporarily fix)?

**Comment by NoseKnowsAll** [comment]
I understand why this is not about to be implemented, but I would also like to say that both me and my girlfriend would very much appreciate this feature once OpenRCT2 is further down the pipeline.

**Comment by popealex** [comment]
+1 to adrian17's suggestion.  If I knew anything about graphics programming I would give is a shot!

**Comment by adrian17** [comment]
With SDL2's renderer upscaling whould be fairly easy to add by using [this function](https://wiki.libsdl.org/SDL_RenderSetLogicalSize).

**Comment by Horsti12** [comment]
This is now possible with the scale factor so it can be closed.

**Comment by IntelOrca** [comment]
@Horsti12 That is not the same thing as it requires changing an permanent option and scales the UI as well.

**Comment by AaronVanGeffen** [comment]
I'd like to make a proposal to tackle this, now that everything has been implemented.

At the moment, zoom levels are stored in a `uint8` and applied by right-shifting values as appropriate: the closest zoom level is 0 (i.e. no shifting), and the furthest one is 3.

What if we abstract this shifting to a function, say `apply_zoom`?

We could then change the signature for zoom to `sint8`, and change the zoom shifting accordingly: >= 0 would work as it does currently, but < 0 would *left shift* instead on the absolute value.

This would double the zoom levels available to viewports.

Could this work?

**Comment by Broxzier** [comment]
Sounds like a good solution. The tricky part will probably be finding _all_ uses of the zoom level. It applies to rendering the viewports, to the UI, to mouse input and probably more.

**Comment by IntelOrca** [comment]
@AaronVanGeffen unfortunately this is the most trivial of all the things that need doing. There is no code for scaling up, only scaling down. All those drawing routines need to be written for enlarging scale and then the even harder part to get right are the necessary changes to the viewport routines which alter the dpi structures.

**Comment by AaronVanGeffen** [comment]
Thanks. That's unfortunate, even if it's not entirely unexpected… I had a feeling it was too easy to be the whole story, heh.

**Comment by pizza2004** [comment]
So, when you zoom in and out does the game have different sprites it uses for different zoom levels, or is it handled in the game somehow?  Also, would it be possible on Retina displays on Mac and possibly an equivalent setup on Windows to allow a person to zoom out but keep the same level of detail as you would normally have at the full zoom level, since the pixels are technically there?

**Comment by AaronVanGeffen** [comment]
> So, when you zoom in and out does the game have different sprites it uses for different zoom levels, or is it handled in the game somehow?

The game effectively skips pixels when zoomed out. It also doesn't bother drawing certain things, like banner text and smaller objects.

> Also, would it be possible on Retina displays on Mac and possibly an equivalent setup on Windows to allow a person to zoom out but keep the same level of detail as you would normally have at the full zoom level, since the pixels are technically there?

For that we'd need to decouple the UI drawing from the rest of the game first. Unfortunately, right now, it's all just one big canvas.

**Comment by pizza2004** [comment]
Yeah, I know about the uncoupling stuff, I just wondered if it's something that would be considered in the future.

If it's just skipping pixels I think what would be nice is for the game to take the set DPI into account once everything is uncoupled and just skip pixels or double pixels based on the zoom level so that technically if you set the DPI high enough you could be at the maximum zoom level with the full detail because you have the pixels on your display.  Then the game could also support higher resolution sprites and it would just need to have it set so it knows when to switch between doubling and halving.

Also it might be nice in the future to specifically allow for sprites rendered at different zoom levels to be added in packs I imagine.  That would allow for people to do things like render 3D models into sprites but each zoom level has a separate sprite meaning you get a better quality look on the zoomed out version.

**Comment by IntelOrca** [comment]
> So, when you zoom in and out does the game have different sprites it uses for different zoom levels

Some sprites such as surface elements have a different image for each zoom level. Hopefully we can just scale up zoom 0 for the closer zoom levels.

**Comment by stellarpower** [comment]
In the meantime, would it be possible to leave the UI elements the same and render the park on the same canvas as currently, and then simply scale this up, along with translating mouse co-ordinates to match?

**Comment by stellarpower** [comment]
And as a really quick fix, would it be possible to tie in a floatable on-screen magnifier that can be toggled on and off? I was thinking of investigating using whatever comes with Mint for that to use over the game.

**Comment by ZehMatt** [comment]
I'm afraid this is still no easy task and there are no quick ways around it.

**Comment by janisozaur** [comment]
Only OpenGL has this feature for now, going to reopen for implementation in others.
