### ISSUE TITLE
Feature request: scroll wheel input on cash-on-hand display increases or decreases loan amount

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#7757]
I find myself often clicking the amount of money on-hand in order to open up the financial window and increase or decrease the loan. (Which I can now do very handily with the mouse's scroll wheel on top of the loan amount.)

This could be streamlined by using a scroll wheel input directly on that number, instead of having to click it and go to a different window. Then money could be added or subtracted from the loan extremely conveniently.

The area I'm talking about, in case I'm using the wrong term and it's not clear:
![nevermore park 2018-07-03 20-01-07](https://user-images.githubusercontent.com/26573303/42254848-a6bb869c-7efd-11e8-8f56-1a6658ba0ef3.png)

It might not be 100% intuitive to people unfamiliar with the feature, but I think most novices wouldn't even notice it at all, since they'd be unlikely to try scrolling there. Maybe a little informational pop-up or tooltip could come out when you scroll on it to let you know that you're adjusting the loan amount and what the new loan amount is.

**Comment by AaronVanGeffen** [comment]
I'd really prefer for us not to implement this. As you said, it's not intuitive at all. Taking a loan or repaying one should be a conscious effort, IMO.

**Comment by Gymnasiast** [comment]
Plug-in stuff then.

**Comment by AaronVanGeffen** [comment]
I suppose it makes it easier to look for things a plug-in system would ideally (eventually) support… But yes, they do clutter up the issue tracker, of course.

**Comment by IntelOrca** [comment]
Big feature requests or plug ins could be moved to a separate repository, like https://github.com/dotnet/csharplang.
