### ISSUE TITLE
Touchscreen presses are handled twice

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#7760]
**OS:** Windows 10
**Version:** 0.2.0
**Commit/Build:** 0aff800 (release)

This was reported here: https://openrct2.org/forums/topic/2984-touchscreen

> New to OpenRCT2, and loving it so far.... However, my computer (Laptop) has a touchscreen, and I would like to use it to play, as it helps reduce pain in my wrist and fingers, but in OpenRCT2, when I touch something on the screen, it acts as if it clicked twice! (clicking the rotate button rotates twice, clicking "Hire new mechanic" hires two, etc..) This does not happen when I play standard RCT or RCT2... (I can use the touchscreen as normal!)
> 
> Is there any fix for this??
> 
> If more info is needed, I am playing on Windows 10, and my computer is a Lenovo Edge 15.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Comment by hawkerm** [comment]
Yeah, I see this too.

**Comment by flipflop97** [comment]
The issue seems to be Windows specific; I can reproduce it on Windows 10 but not on Linux/Gnome.

**Comment by youngspe** [comment]
I've been experiencing this with a Surface Pro. I set up some tracepoints in UiContext::ProcessMessages() and found that the game receives the SDL_FINGERDOWN and SDL_FINGERUP messages as expected, but then immediately after the finger is released, SDL_MOUSEBUTTONDOWN and SDL_MOUSEBUTTONUP are fired in quick succession. Could this be a bug in SDL?

This was with build 2ccc183f186560c2b159ec753ece9bd568a85121 running on Windows 10 version 1803.

**Comment by IntelOrca** [comment]
@youngspe It may be expected behaviour if those mouse events don't fire before your finger interaction. If it doesn't fire the mouse events then any game that doesn't support finger events would not work at all on touch screens. Is there some sort of flag on those mouse events that says whether it for a finger action or not?
