### ISSUE TITLE
Vehicles hacked on different type of train become invisible when vehicle type disabled

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#7772]
**OS:** Windows 10
**Version:** 0.2.0
**Commit/Build:** 3f8c3c3

A minor bug i discussed with @Broxzier , he recommended me to make an issue so we don't forget about this later.

Anyway, i spawned some covered cars on the middle 2 vehicles of a train using Visual Studio.
When I submitted the park to NE, a helpful mod disabled all unused objects, including the covered cars, because they were not marked as being used, while technically they were in the game.

![image](https://user-images.githubusercontent.com/6469413/42473641-77312f68-83c5-11e8-94b9-bb9282748ca6.png)

The result was that the middle cars of the train turned invisible.

**Comment by Gymnasiast** [comment]
I thought the NE mods still used ParkDat? @Liampie ?
