### ISSUE TITLE
Object does not appear in scenery window

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#7776]
**OS:** Windows 10
**Version:** 0.2.0
**Commit/Build:** 0aff800

I have found an object that cannot be placed because it does not appear in the scenery selection window.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Start a new park
2. Select the scenery object attached to this post
3. Miscellaneous tab does not appear (if it was not already there)
4. Object does not appear in miscellaneous tab

[MGLBDG.DAT.txt](https://github.com/OpenRCT2/OpenRCT2/files/2186013/MGLBDG.DAT.txt)

**Comment by Gymnasiast** [comment]
The object requests to be put in the "Walls and Roofs" group, and that's what OpenRCT2 does.

(It must therefore also be reproducible in vanilla.)
