### ISSUE TITLE
Crash when importing a track design

### ISSUE THREAD

**Issue by frenchiveruti** [OpenRCT2/OpenRCT2#7786]
**OS:** Windows 10 Windows (x86-64)
**Version:** Both 0.2.0 stable (0aff800) and v0.2.0-145 (ab20dcd on develop)
**Commit/Build:** 0aff800 && ab20dcd

When you create a track inside the game and want to import it to another park, the game crashes upon the installation of the beforementioned track, no matter if the track was obtained from the internet or self-made inside the game.

- [ ] Reproducible in RCT2 (vanilla)?  
**NO**, the track I created inside OpenRCT2 gets loaded just fine in the GOG game version I have.
- [ ] Specific to multiplayer? No.

**Steps to reproduce:**
1. Open ORCT2.
2. Go to "Track Designs Manager"
3. Click on "Install New"
4. Select previously made/Downloaded **td6** file

**Dump file**
_How the hell do I do this? I can't find information about this._
Here's a log file (using openrct2 --verbose, note that openrct2.**exe** _won't_ work with --verbose) : 
[log.txt](https://github.com/OpenRCT2/OpenRCT2/files/2198900/log.txt)
[log-DevBuild.txt](https://github.com/OpenRCT2/OpenRCT2/files/2198902/log-DevBuild.txt)

**Screenshots / Video:**
[Replay 2018-07-16 15-22-48.zip](https://github.com/OpenRCT2/OpenRCT2/files/2198908/Replay.2018-07-16.15-22-48.zip) [~3.7MB]
https://youtu.be/4zG11Y8sgCs

**Save game:**
Does not Apply.

**Comment by frenchiveruti** [comment]
To add something, it seems like it has to do with some JSON implementations in the code when using the DAT files from the original game?

**Comment by frenchiveruti** [comment]
Yes, of course, here are the ones I've tried out so far.
I've imported them into GOG RCT2 and they worked just fine. 
The problem is entirely within my OpenRCT2 game.

**Comment by frenchiveruti** [comment]
Yes, of course, here are the ones I've tried out so far.
[track.zip](https://github.com/OpenRCT2/OpenRCT2/files/2199239/track.zip)

I've imported them into GOG RCT2 and they worked just fine.
The problem is entirely within my OpenRCT2 game.

**Comment by janisozaur** [comment]
I'm unable to reproduce it. @frenchiveruti any chance you can provide us with a dump of said crash?

**Comment by frenchiveruti** [comment]
[dumps.zip](https://github.com/OpenRCT2/OpenRCT2/files/2199387/dumps.zip)
I used this application:
https://docs.microsoft.com/en-us/sysinternals/downloads/procdump
With the command:
D:\Programas\ProcDump64\procdump64.exe -e 1 -f "" -64 -w openrct2.exe C:\dumps
-e makes the dump when the program fails
-f Filter the first chance exceptions
-w Waits for the proccess "openrct2" to actually appear.
-64 as the game runs in 64 bits.

**Comment by IntelOrca** [comment]
```
>	openrct2.dll!format_append_string(dest=0x0000009e9d4ff6d0, size=0x0000009e9d4ff590, string=0x6977545f70696c46) Line 345	C++
 	openrct2.dll!format_string_part_from_raw(dest=0x0000009e9d4ff6d0, size=0x0000009e9d4ff590, src=0x00000000000017fe, args=0x0000009e9d4ff598) Line 1047	C++
 	openrct2.dll!format_string_part(dest=0x0000009e9d4ff6d0, size=0x0000009e9d4ff590, format, args=0x0000009e9d4ff598) Line 1096	C++
 	[Inline Frame] openrct2.dll!format_string(args=0x00007ffe109eebc8, ) Line 1147	C++
 	[Inline Frame] openrct2.dll!DrawText() Line 109	C++
 	openrct2.dll!DrawTextCompat(dpi=0x0000009e9d4ff780, x=163, y=280, format, args, colour='\0', alignment=LEFT, underline=false) Line 121	C++
 	[Inline Frame] openrct2.dll!gfx_draw_string_left() Line 153	C++
 	openrct2.dll!window_install_track_paint(w, dpi=0x0000009e9d4ff780) Line 265	C++
 	[Inline Frame] openrct2.dll!window_event_paint_call() Line 1540	C++
 	openrct2.dll!window_draw_single(dpi, w=0x000001fc8028bae0, left, top, right=720, bottom=480) Line 1224	C++
 	openrct2.dll!window_draw(dpi=0x0000009e9d4ff830, w=0x000001fc80287400, left=0, top=0, right=720, bottom=480) Line 1113	C++
 	openrct2.dll!window_draw_all(dpi, left, top, right, bottom) Line 2043	C++
 	[Inline Frame] openrct2.dll!OpenRCT2::Drawing::X8DrawingEngine::DrawDirtyBlocks() Line 457	C++
 	openrct2.dll!OpenRCT2::Drawing::X8DrawingEngine::DrawAllDirtyBlocks() Line 390	C++
 	openrct2.dll!OpenRCT2::Drawing::X8DrawingEngine::PaintWindows() Line 223	C++
 	openrct2.dll!OpenRCT2::Paint::Painter::Paint(de) Line 46	C++
 	[Inline Frame] openrct2.dll!OpenRCT2::Context::RunFixedFrame() Line 890	C++
 	[Inline Frame] openrct2.dll!OpenRCT2::Context::RunFrame() Line 859	C++
 	openrct2.dll!OpenRCT2::Context::RunGameLoop() Line 830	C++
 	openrct2.dll!OpenRCT2::Context::RunOpenRCT2(argc=-173648240, argv=0x000001fcf5a65698) Line 214	C++
 	openrct2.dll!NormalisedMain(argc=1, argv=0x000001fcf5a5b680) Line 60	C++
 	openrct2.dll!LaunchOpenRCT2(argc=1, argvW=0x0000000000000030) Line 46	C++
```

**Comment by IntelOrca** [comment]
@frenchiveruti Could you test if the following build fixes your issue?

https://ci.appveyor.com/api/buildjobs/0hmii79lcedn05k7/artifacts/artifacts%2Fopenrct2-portable-release-x64-882e34b.zip

**Comment by frenchiveruti** [comment]
Hi @intelorca I will test it as soon as I get home, thanks.

**Comment by frenchiveruti** [comment]
Hi @IntelOrca , the build you've provided me works wonders, I now have the ride inside my park.
Thanks.
