### ISSUE TITLE
missing "openrct2.dll" ?

### ISSUE THREAD

**Issue by some-won** [OpenRCT2/OpenRCT2#7791]
**OS:** Windows 10
**Version:** 0.2.0

A window opens up saying that "openrct2.dll" is missing and redownloading it might fix it. [url](http://prntscr.com/k7nsq1)

**Steps to reproduce:**
1. Downloaded
2. Run openrtc2.exe

**Dump file**

[OpenRCT2-develop.zip](https://github.com/OpenRCT2/OpenRCT2/files/2203191/OpenRCT2-develop.zip)

**Screenshots / Video:**

[http://prntscr.com/k7nsq1](url)

**Comment by Gymnasiast** [comment]
You downloaded the source code, rather than the compiled game.

You can download compiled versions from [here](https://openrct2.org/downloads).
The same page also has a link to the Launcher, which can keep the game up to date for you.
