### ISSUE TITLE
OpenRCT2 Launcher not working

### ISSUE THREAD

**Issue by L3mmy** [OpenRCT2/OpenRCT2#7796]
**OS:** Windows 10
**Version:**0.2.0-3
**Commit/Build:** 426e106

I have a bug with my launcher, the launcher won't launch OpenRCT2, it keeps saying Unable to launch the Game, i've asked for help on the Discord server, i've tried unistalling and re-intalling the launcher, i can't get the files in the bin folder to re-appear !

- [ ] Reproducible in RCT2 (vanilla)?
- [X] Specific to the OpenRCT2 Launcher

**Dump file**

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/41308252/42939040-a8985de2-8b54-11e8-998b-0b4908a5fbf8.png)

**Save game:**
*Not Specific to a game file*

**Comment by janisozaur** [comment]
This is OpenRCT2 project, not the launcher. Please file this bug with the launcher.

**Comment by Gymnasiast** [comment]
To be a little bit less abrasive than Janisozaur, the launcher is a separate project.

The best place to ask is the [OpenRCT2.org forums](https://openrct2.org/forums/). I have some ideas about what it could be (like anti-virus), but I can help you better if you open a topic there.

**Comment by Broxzier** [comment]
That was my first thought too. On the Discord server L3mmy mentioned he's using Avast, which has had similar reports before. Only the `openrct.exe` and `openrct2.com` files were not in the list, before he created this issue.

![](https://cdn.discordapp.com/attachments/450316748734988289/469448152877891584/unknown.png)

He also mentioned that the ".dll **was** an .exe", but the file size doesn't match.

**Comment by Gymnasiast** [comment]
@L3mmy Do you have Avast as your anti-virus program? Uninstall it and switch to Windows Defender. Avast has been a problem for a lot of users.

**Comment by Patrik356b** [comment]
@Gymnasiast
 I'd just like to point out that the issue could happen with any AV. I have personally not have any issues with Avast and OpenRCT2.

AVG did have a rough time with OpenRCT2 a long time ago, but now it seems to be alright. I'll leave this thread now though.
