### ISSUE TITLE
Porting to android

### ISSUE THREAD

**Issue by greatjack1** [OpenRCT2/OpenRCT2#7798]
I would want to port this game to android. Are their any technical reasons why this is unfeasible such as lack of certain libraries or gfx engine available? Or just no none has done it yet?

**Comment by janisozaur** [comment]
Huh? We have daily builds done for Android.

But feel free to tackle https://github.com/OpenRCT2/OpenRCT2/issues/7717 or https://github.com/OpenRCT2/OpenRCT2/issues/7536 or https://github.com/OpenRCT2/OpenRCT2/issues/7282 or any other of https://github.com/OpenRCT2/OpenRCT2/issues?q=is%3Aopen+is%3Aissue+label%3A%22Android+%28OS%29%22

**Comment by greatjack1** [comment]
Oh, my bad, Will get to work. Would love to contribute. Where can I find information about building the port?

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/wiki/Android

It's pretty much this: `ANDROID_HOME=/home/janisozaur/Android/Sdk ANDROID_NDK_HOME=/home/janisozaur/Downloads/android-ndk ./gradlew app:assembleARM`

**Comment by greatjack1** [comment]
Thanks
