### ISSUE TITLE
Title screen music unaffected by music volume control

### ISSUE THREAD

**Issue by TheJanzap** [OpenRCT2/OpenRCT2#7799]
**OS:** Windows 10 
**Version:** 0.2.0-152
**Commit/Build:** 8530d56

If a title screen music is selected, it is unaffected by the ride music volume slider in the options, so the music always blasts out at full volume. 
I would suggest to set the title screen music volume with the ride music slider or to create a seperate volume slider for it.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Go into options and select a title screen music
2. Change the ride music volume

**Comment by Patrik356b** [comment]
Related:
#6720
#3001
