### ISSUE TITLE
Translations of scenario name and description not used

### ISSUE THREAD

**Issue by J0anJosep** [OpenRCT2/OpenRCT2#7800]
**OS:** Ubuntu
**Version:** 18.04
**Commit/Build:** 9c46187b911681f9b2ede5af42da19337f319555

Some strings regarding scenarios and their description show up in English when a translation is available. Given that in Catalan there is a translation for a given scenario and its description:
- In the list of scenarios in the main title screen, RCT2 scenarios and descriptions aren't translated to the selected language (RCT1 scenarios use the correct translation instead). They are translated once you start a game, but not on the list of scenarios.
- When you start a RCT1 scenario, once the game has started, the scenario name isn't correctly translated (scenario description is correctly translated).

2 images of the different bugs attached.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
For the RCT2 unused translations:
1. Set Catalan language.
2. Go to "Start a new game" and **open a list of scenarios from RCT2. Here you can see scenarios and descriptions are in English.**
3. If you start a game with a RCT2 scenario, then both name and description of scenario are shown in Catalan.

For the RCT1 unused translations:
1. Set Catalan language.
2. Go to "Start a new game" and open a list of scenarios from RCT1. Here you can see scenarios and descriptions are in Catalan.
3. If you start a game with a RCT1 scenario, **the name of the scenario is shown in English** and the description in Catalan.

**Dump file**

**Screenshots / Video:**

![rct2_scenarios_untranslated](https://user-images.githubusercontent.com/3152990/43004123-151c957a-8c2f-11e8-9579-0217adff929c.png)
![imatge](https://user-images.githubusercontent.com/3152990/43004171-41fca940-8c2f-11e8-9d71-96f5f9c65296.png)

**Save game:**

**Comment by AaronVanGeffen** [comment]
Coincidentally, a similar question was asked by @frenchiveruti on Gitter a few days ago. The localisation in question had translated the identifier for the scenarios as well, making it impossible to apply the translations.

For an example of correct targetting, see e.g. https://github.com/OpenRCT2/Localisation/commit/bbd7a40b83732fa9dc8cfcbb0aaacd043b92b110. Note that the scenario name between < and > should not be translated.

**Comment by J0anJosep** [comment]
@AaronVanGeffen  In the commit you are referring to, which I wrote, what exactly should I change? Anyway, it is strange that in some lists the strings are translated and in other places they aren't.

**Comment by AaronVanGeffen** [comment]
Haha, I didn't notice it was your commit… It should definitely work, then. Could be a case of the scenario cache not having been invalidated, then.

Try changing to English, then re-open the scenario window — it should take a few seconds if it's refreshing. Go back to Catalan and do the same. Your translations should then show up.

**Comment by Gymnasiast** [comment]
That, or go to `/home/joanjosep/.config/openrct2` and remove `scenario.idx`.

**Comment by J0anJosep** [comment]
@Gymnasiast @AaronVanGeffen  Thank you! Both suggestions worked for RCT2 scenarios. But for RCT1 scenarios, the problem persists.

**Comment by frenchiveruti** [comment]
I guess it's something to do with a Cache for the game, like the scenarios.idx?

**Comment by Gymnasiast** [comment]
Catalan language file looks correct. This bug should be gone. Let me know if it isn't.
