### ISSUE TITLE
Incorrect clearance height for sloped paths

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#7812]
**Version:** 0.2.0
**Commit/Build:** fd133aa

Taken from: https://openrct2.org/forums/topic/3010-bad-path-clearance-check/

>  The clearance check above paths that slope down toward the bottom left in relation to the default rotation is one unit less than it should be. In the picture, the paths on the left demonstrate that. The other directions have the same clearance check as the paths on the right. This inconsistency isn't present in RCT2.
>
> Interestingly, the clearance check seems to work correctly when the sloped paths are built as part of ride scenery. When those paths are rebuilt, the clearance check for those paths becomes bad again.

This can be confirmed with the tile inspector.

**Steps to reproduce:**
1. Build a sloped path one way
2. Build another sloped path in a direction perpendicular to it
3. Observe how the clearance height does not match for one of them

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Screenshots / Video:**
![](https://openrct2.org/forums/uploads/monthly_2018_07/5b55041aab7c9_2018-07-2215-20-56.png.67d213840c48c75ef7e9660db0ad6507.png)

**Comment by Gymnasiast** [comment]
Cannot reproduce this on 41d09a26912543730add515d58d4d43ebb045623 . Is this solved?

**Comment by Gymnasiast** [comment]
Assuming it is. Let me know if it's not the case.
