### ISSUE TITLE
Interpunct sprite not used

### ISSUE THREAD

**Issue by J0anJosep** [OpenRCT2/OpenRCT2#7817]
**Commit/Build:** fd133aae8a771341228c702357121aad27e29517

Some words in Catalan use the [interpunct](https://en.wikipedia.org/wiki/Interpunct). Right now it is not detected and a flag is drawn instead of it.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Change to Catalan language.
2. Search for some string that contains the interpunct (Options->Advanced->Path to RCT1 installation or Select Scenario->Added Parks->Gentle Glen).

**Screenshots / Video:**

![punt_volat](https://user-images.githubusercontent.com/3152990/43147797-2c4efc14-8f64-11e8-8e94-e40b38b6eded.png)

**Comment by Gymnasiast** [comment]
That's one for sprite font man!


(The reason you're seeing a flag is because Chris Sawyer replaced characters in Windows-1252 he didn't need with characters he did need. The flag is used in Locomotion to mark airports.)

**Comment by Gymnasiast** [comment]
I have opened #7821 to add this (and several other characters):

![millennium mines 2018-07-24 21-06-19](https://user-images.githubusercontent.com/1478678/43160746-5cec0796-8f86-11e8-86bf-b5282b462dfd.png)

**Comment by J0anJosep** [comment]
Thank yo, spritefontman!!
