### ISSUE TITLE
Hosting Server ipv6 error

### ISSUE THREAD

**Issue by KingJulian13** [OpenRCT2/OpenRCT2#7819]
**OS:** Windows 10
**Version:** 0.2.0
**Commit/Build:** 0aff800

I'm trying to host a server and opened the default port 11753 (TCP). Sadly I'm only getting the following error in console when trying to host, even with my entire firewall off.

`D:\Steam\steamapps\common\openrct2>openrct2 host C:\...\OpenRCT2\save\Johannes.sv6 --port 11753
Ready for clients...
Unable to advertise (500): An unknown error has occured. If this state persists, please contact the developers.
INFO[c:\projects\openrct2-ject9\src\openrct2\network\networkserveradvertiser.cpp:195 (NetworkServerAdvertiser::OnRegistrationResponse)]: Retry with ipv4 only
Unable to advertise (404): Unable to reach game server, make sure your ports are open.`

- [ ] Reproducible in RCT2 (vanilla)?
- [X] Specific to multiplayer?

**Comment by IntelOrca** [comment]
IPv6 does not currently work. This has already been reported: https://github.com/OpenRCT2/OpenRCT2/issues/7632
