### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [OpenRCT2/OpenRCT2#7825]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in [a function like “NetworkConnection::SetLastDisconnectReason”](https://github.com/OpenRCT2/OpenRCT2/blob/f6b5f9e3ae216f23b74445b9fbd573f985e24c83/src/openrct2/network/NetworkConnection.cpp#L155 "Update candidate").

**Comment by Gymnasiast** [comment]
I think you're referring to the nullptr check if `_lastDisconnectReason`? That's correct, yes, it is not needed. Can you open a pull request for it?

**Comment by elfring** [comment]
Would any other software developers like to improve affected places quicker (than me)?

**Comment by Gymnasiast** [comment]
The idea of open source is that you do the fix yourself and open a pull request, not that you ask other people to do it for you.
