### ISSUE TITLE
Guests getting in queue line

### ISSUE THREAD

**Issue by L3mmy** [OpenRCT2/OpenRCT2#7826]
**OS:** Windows 10
**Version:** 0.2.0
**Commit/Build:** 426e106

If a queue line is built and it has an access to a path, if you build another another queue line next to the queue line that's connected, if a guest is near the queue line, the guest can go through the queue line 

- [X] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**

1. Put a queue line connected to a ride entrance and connect it to a path

2. Build another queue line when there's a guest heading towards the queue line 

**Screenshots / Video:**
I can't screen because this bug requires to put a queue line and the guest go through just after i put the queue line

**Save game:**
*Not specific to save file*

**Comment by jensj12** [comment]
Sounds familiar to #3499. Please do make a screenshot (there’s a keyboard shortcut for it) so I can understand what the issue is, or make a video (use win+G to open the game bar, then click record).
