### ISSUE TITLE
Copied entrances and exits stay when demolishing ride

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#7828]
**OS:** Windows 10
**Version:** 0.2.0
**Commit/Build:** 80f6724

Ride entrances and exits that have been copied with the tile inspector are not removed when demolishing a ride.

Clicking on them or sometimes even hovering over them with the mouse can crash the game.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Build a ride that has entrances/exits (no shops/stalls)
2. Copy the entrance with the tile inspector, and paste it somewhere
3. Demolish the ride

**Result**: The entrance still there. Clicking on it crashes the game.

**Comment by martip23** [comment]
I'd like to take this issue on. I'd appreciate some guidance on the relevant classes/methods/variables that would be useful to begin reading.

**Comment by jensj12** [comment]
The demolish game action has a function demolish_tracks (or similar). This loops over all tile elements (everything, not just the ride) and removes all track pieces from that particular ride. Also checking for entrances and exits of that ride there should do the trick.

**Comment by cjgaspari** [comment]
@martip23 let me know if you work on this issue further, if not I'd like to pick it up. :)

**Comment by martip23** [comment]
I am working on it. I've been trying to get the build to run but I finally have time today.
