### ISSUE TITLE
Rotated information kiosk can cause 'unreachable' messages

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#7829]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.2.0]
**Commit/Build:** [e.g. 426e106]

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Build a information kiosk, but make the arrow not face the path
2. Open it.
3. Wait for the message to appear.

We have had this error before - it's even one of the first issues I reported!

**Screenshots / Video:**
![](https://openrct2.org/forums/uploads/monthly_2018_07/5b551995d8f98_Sandbox2018-07-2216-54-31.png.ab9d1ad124d7bcae45007f2951b82198.png)

**Comment by Patrik356b** [comment]
I never understood why it had the arrow as it is supposed to be reachable from any direction. I typically just place it in a corner of a path.

**Comment by Broxzier** [comment]
Yeah, drawing the arrow could be ommited for information kiosks (and possibly other shops/stalls where direction doesn't matter).

**Comment by Gymnasiast** [comment]
Yes, but now it helps us address an error.

**Comment by duncanspumpkin** [comment]
Does it work correctly if you remove and replace the footpath element? Cause it could just be forgetting to recheck for connections.
