### ISSUE TITLE
g1.DAT NOT CONBINED WITH OPENRCT 2

### ISSUE THREAD

**Issue by Edwardcae** [OpenRCT2/OpenRCT2#7832]
-->
**OS:** [ Windows 7]
**Version:** [0.2.0]
**Commit/Build:** [ 426e106]

The gt1.dat file is not combined with the installer.

- [ Maybe] Reproducible in RCT2 (vanilla)?
- [no ] Specific to multiplayer?

**Comment by Broxzier** [comment]
You probably mean `g1.dat`, which is a file from RCT2 itself, not OpenRCT2.

**Comment by Edwardcae** [comment]
so.. where is the g1.dat file then?
\

**Comment by Broxzier** [comment]
in the data folder of your RCT2 installation directory.

**Comment by Edwardcae** [comment]
which folder

**Comment by Gymnasiast** [comment]
You need to have RollerCoaster Tycoon 2 in order for OpenRCT2 to work.

On startup, it will ask you where the _RollerCoaster Tycoon 2_ folder is.

**Comment by Edwardcae** [comment]
I choce C:/Program Files

**Comment by Edwardcae** [comment]
![image](https://user-images.githubusercontent.com/41781604/43314071-6704c37c-91c4-11e8-955f-3debafeaaf80.png)

**Comment by Gymnasiast** [comment]
That's the wrong folder...

Have you installed RollerCoaster Tycoon 2 or not?

**Comment by Edwardcae** [comment]
yes.

**Comment by Gymnasiast** [comment]
Where is it installed?

**Comment by Edwardcae** [comment]
c:/Program Files/OpenRCT2

**Comment by IntelOrca** [comment]
You can not run OpenRCT2 for Windows XP (which looks like a VM anyway). Run it on your host or use a Windows 7+ VM.

**Comment by Edwardcae** [comment]
i am useing the host for open rct 2

**Comment by Edwardcae** [comment]
@Gymnasiast  NO,IT'S A VM

**Comment by Gymnasiast** [comment]
@Edwardcae That's not what I asked! I asked where you installed **ROLLERCOASTER TYCOON 2**, not where you installed OpenRCT2.

**Comment by IntelOrca** [comment]
You must have RollerCoaster Tycoon 2, either from the disc, steam or GOG. You must buy it if you don't yet own it to run OpenRCT2.

**Comment by Edwardcae** [comment]
Woops...

**Comment by Edwardcae** [comment]
Anyhoo.

**Comment by Edwardcae** [comment]
Do I must run rct2 (Roller Coster Tycoon 2)for the first time to run OpenRct2?

**Comment by janisozaur** [comment]
No, this is not required. Additionally, OpenRCT2 supports many more OSs and architectures than vanilla, so in many cases it would not even be possible.
