### ISSUE TITLE
Cannot load game data on linux anymore

### ISSUE THREAD

**Issue by faassen** [OpenRCT2/OpenRCT2#7833]
**OS:** Fedora 28
**Version:** 0.1.2, 0.2.0, develop

I always needed to compile OpenRCT myself as the precompiled linux version has some linking issue. But that's not a problem; it builds fine. I saw there was a new release and built 0.2.0, but do what I might, it wouldn't access my original game data anymore - lots of errors loading objects. I tried building develop as well, same problem.

When I finally switched back to 0.1.2 and rebuilt it, everything works fine

**Steps to reproduce:**
1. build openrct2 (at least 0.2.0 or upwards) on linux, make g2
2. point it at the original game data. (either during first startup or with set-rct2)
3. start openrct2 -- it will complain about missing objects during startup on the console, and selecting any park will also complain with lots of messages about missing objects.

Something must have changed since 0.1.2 that breaks this. I'm a bit mystified as to why: you'd think I'm not the only one to build this on Linux recently.

**Comment by Broxzier** [comment]
Do you have the json objects?

**Comment by janisozaur** [comment]
It sounds like you are indeed missing our json objects. Make sure you follow https://github.com/OpenRCT2/OpenRCT2/wiki/Building-OpenRCT2-on-Linux#compiling, the build system should download them automatically for you.

**Comment by faassen** [comment]
How do I verify whether I have the json objects? Are we talking about g2.dat?

I tried both 'make g2', as well as the 'make install' instructions you pointed me to yesterday already -- I remember the download taking place.

Note that these instructions rather confuse me:

DESTDIR=/some/writeable/path/ make install

but then completely ignores what I should be doing with the result in DESTDIR. Does it matter? Anyway, I just tried running the binary in /some/writeable/path/usr/local/bin (instead of the one in build) and I have the same problem (after adding a data directory with g2.dat).

I only get output along these lines when I try to start a park, by the way:

```
[BALLN   ] Object not found.
[BURGB   ] Object not found.
[CNDYF   ] Object not found.
[ATM1    ] Object not found.
[ARRT1   ] Object not found.
```

and so on. Yesterday I also got it during startup at some point, but that might've been with the 0.2.0 version instead of develop.

Are there changes to the compilation/installation procedure since 0.1.2? Because I manage to compile and run this successfully, both originally and yesterday. Were your json objects introduced afterwards?

**Comment by AaronVanGeffen** [comment]
Alternatively, the objects may be downloaded as a separate release from [the objects repository](https://github.com/OpenRCT2/objects/releases). Extract them to the `data/objects` folder.

**Comment by faassen** [comment]
Okay, I finally got it working by objects from from the repo you indicated, and installing it in `data/object` (not (`data/objects`). 

I am going to adjust the installation instructions as they're not super helpful -- they don't mention objects at all. They don't allow you to run openrtc locally anymore, only after a full 'make install' into /usr/local/. A custom DESTDIR as is recommended actually makes the installation fail, as the objects get stored into $DESTDIR/usr/local/share/openrct2/object and it just won't pick them up.

**Comment by faassen** [comment]
Okay, I've edited the https://github.com/OpenRCT2/OpenRCT2/wiki/Building-OpenRCT2-on-Linux document to make note of the `objects` directory and describe a `make install` derived way to get a functional data directory.
