### ISSUE TITLE
Exit all windows with Esc key

### ISSUE THREAD

**Issue by monsdar** [OpenRCT2/OpenRCT2#7838]
**OS:** Windows 10
**Version:** 0.2.0
**Commit/Build:** 5c2dd36

It is possible to close some game windows by pressing the Escape key (e.g. land and water tools). Other windows are not closeable by hitting escape, it is needed to manually click the X button (e.g. the visitors window).

It would help the usability a lot to enable pressing Esc for every window. This is especially true when many windows for peeps or rides are active.

Not sure how it was with vanilla RCT2, though I would declare it a usability improvement if it wasn't like that in vanilla.

**Steps to reproduce:**
1. Open water tool window
2. Hit escape
3. Window closes
4. Open visitors overview window
5. Hit escape
6. Window stays open

**Comment by monsdar** [comment]
You are right, just tested it. Backspace works with all window types. Still think it's a bit strange from a usability perspective that Esc works in some cases and not in others.

**Comment by AaronVanGeffen** [comment]
By default, the escape key is bound to cancelling construction mode:

![screenshot_20180729_223812](https://user-images.githubusercontent.com/604665/43370498-17eeed04-9380-11e8-9b91-aadae7a7458b.png)

**Comment by monsdar** [comment]
I think I got it then: Water tool and some others count as construction and therefore their menus are closed with Esc.

Technically this makes sense, from a usability standpoint I guess this could be implemented in a better way (?)

**Comment by IntelOrca** [comment]
Escape is cancel current tool. Cancelling the current tool will close its dedicated window.

**Comment by Gymnasiast** [comment]
I don't think there is a better way of implementing this.

**Comment by monsdar** [comment]
Ok, there has probably been more discussion about this as this topic deserves. Thanks a lot for your clarifications, very cool that there's such an active community around OpenRCT2!
