### ISSUE TITLE
peeps unable to enter park but are still able to leave.

### ISSUE THREAD

**Issue by amdcrash** [OpenRCT2/OpenRCT2#7842]
**OS:** windows 10 (version 1803 os build 17134.191)
**Version:** 0.2.0-143
**Commit/Build:** f728a50 develop

peeps unable to enter park but are still able to leave.

- [unknown ] Reproducible in RCT2 (vanilla)? 
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. see file save file, peeps count slowly going down but peeps unable to enter.

**Save game:**
[bug.zip](https://github.com/OpenRCT2/OpenRCT2/files/2244407/bug.zip)

**Comment by Broxzier** [comment]
There are a few issues with the park:
1. There are no paths behind two of the entrances, so when guests try to enter
2. The paths don't connect to the edgeof the map, so leaving guests will never be able to disappear
3. The guest entry/spawn points are missing

These are probably a result of having increased the map size and using the "own all land" cheat without taking the paths outside the park into account first. Here's a fixed version of the park: [Nirvana Gardens.zip](https://github.com/OpenRCT2/OpenRCT2/files/2244601/Nirvana.Gardens.zip)
