### ISSUE TITLE
Connecting via Hamachi

### ISSUE THREAD

**Issue by 2000game** [OpenRCT2/OpenRCT2#7844]
**OS:** e.g. Windows 10
**Version:** e.g. 0.2.0
**Commit/Build:** 0aff800

So my friend and I tried to create a server. We used Hamachi but it doesn't seem to work. When I try to connect to his server I'm getting the error  Connection timed out. Also the server doesn't seem to be online. I just copied the IP4 Address of my friend in Hamachi.

Also I'm getting the error Failed to open configured language: id was undefined at the start. Could this be related?

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

But I can connect to the normal open servers. So there isn't the problem.

**Comment by Broxzier** [comment]
Can you ping to the IP address of your friend? (Open command prompt or power shell and type `ping <the IP address>`.) If it fails, make sure you're properly connected through Hamachi.

**Comment by 2000game** [comment]
Yes, already tried that. It works.

**Comment by duncanspumpkin** [comment]
This doesnt sound to be an issue with OpenRCT2 and more likely Hamachi or other firewalls causing issues.
