### ISSUE TITLE
random cluster tool placing trees/shrubs above water

### ISSUE THREAD

**Issue by L3mmy** [OpenRCT2/OpenRCT2#7846]
**OS:**Windows 10
**Version:**0.2.0
**Commit/Build:**426e106

When using the random cluster tool, the object selected and placed may place other one above water

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1.Select anything that allows to be placed with the random cluster 
2. place it near the water and done !

**Screenshots / Video:**
![2018-08-02 09-03-51](https://user-images.githubusercontent.com/41308252/43567831-4b3dfac8-9633-11e8-8878-ea912b58f8b8.png)

**Save game:**
*Not save game specific*

**Comment by L3mmy** [comment]
Note : it works better with shrubs, some trees aren't above water like the magnolia tree

**Comment by Patrik356b** [comment]
Don't be so quick to close the report, it will only be harder for the devs to find this issue
