### ISSUE TITLE
Spiral coaster bugs

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#7854]
**OS:** Windows 10
**Version:** 0.2.0
**Commit/Build:** 3ccad7c

I get two different bugs with the spiral coaster. The first one is that I can't build a custom design and get this error if I try.
![image](https://user-images.githubusercontent.com/25930360/43677364-158d3856-9801-11e8-9c22-d98ac0257c31.png)

The second one is that I have two nameless empty designs that I also can't build, I also can't find them in my tracks folder.
![image](https://user-images.githubusercontent.com/25930360/43677383-4fc99ffa-9801-11e8-886d-afe947501413.png)

The only way I can build a custom design at the moment is to build a saved design and alter it.

**Comment by jensj12** [comment]
Confirmed. Can't build custom design nor the two empty designs. (Just to make sure it's not a local issue)

**Comment by Gymnasiast** [comment]
The Spiral RC has ride type index 0. That might be the/a culprit.

**Comment by Gymnasiast** [comment]
https://github.com/OpenRCT2/OpenRCT2/pull/10814 fixes the issue with building custom designs.
