### ISSUE TITLE
Game crashes when saving senario

### ISSUE THREAD

**Issue by L3mmy** [OpenRCT2/OpenRCT2#7855]
**OS:** Windows 10
**Version:** 0.2.0
**Commit/Build:** f3f4776

I was playing Fiasco Forest and the i was bored and wanted to go back to the main menu and so i saved the senario, because i hasn't saved it yet, i clicked on New file.

- [X] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Save the game
2. click on the New file button and click OK and the game crashes

**Save game:**
No save specific

**Comment by Broxzier** [comment]
426e106 is a month old already, the current last build is f3f4776, try using that one instead.

**Comment by L3mmy** [comment]
It looks like it's fixed
