### ISSUE TITLE
Triple Thrill Pack

### ISSUE THREAD

**Issue by Fabian272** [OpenRCT2/OpenRCT2#7856]
**OS:** Win 10
**Version:** 0.2.0
**Commit/Build:**

Today, i bought the pack of RCT1, 2 and 3 with all addon packs, i had RCT2 before however without the addon packs, i removed all previous OpenRCT2 versions and the no-addon RCT2 version files and installations, then i installed OpenRCT2, however it does not include the addon content
It works from my friend and still doesnt work after reinstallations of RTC2TTP
- [y] Reproducible in RCT2 (vanilla)?
- [n] Specific to multiplayer?

**Steps to reproduce:**
1. Install RTC2+TTP
2. Install the TTP content once the game downloaded via steam
3. Install OpenRCT2

**Comment by IntelOrca** [comment]
I your documents/OpenRCT2 folder you will see a file called config.ini. You might need to edit this file and change the RCT2 path to point to your steam RCT2 directory.

**Comment by Gymnasiast** [comment]
I just pushed an update to improve situations like these.

First, update OpenRCT2 to the latest `develop` version.
Then, go to Documents/OpenRCT2 and open `config.ini`. Simply clear the variable `game_path`.
Now start up OpenRCT2. It should autodetect the Steam installation of TTP.
