### ISSUE TITLE
Alignment in new save format

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#7859]
[New save format](https://raw.githubusercontent.com/IntelOrca/OpenRCT2/new-save-format/docs/save-format.md) lists e.g.

```
banner-element:
  object-id:                uint16
  index:                    uint32
  flags:                    uint8
  position:                 uint8
  (spare: 4)
```

but this creates a situation where values are not naturally-aligned. There are more situations which exhibit the same issue.

To obtain natural alignment, should we add padding or rearrange the fields?

**Comment by IntelOrca** [comment]
There may be a slight performance hit on risc but I doubt it's significant.
