### ISSUE TITLE
Feature suggestion regarding 'Persistent scenario savegames'

### ISSUE THREAD

**Issue by baaz11** [OpenRCT2/OpenRCT2#7860]
Hello,

I have a suggestion for a feature.
a. A toggleable checkmark in the settings that reads 'By default load park in progress' (to allow the disabling of the feature completely)
b. In the scenario selection window when you click on a scenario that you completed previously or have at least played it a while to autosave with its default name (e.g. ForestFrontiers.sv6), it will continue on the same savegame. But if you'd like to start the scenario from the beggining, there would be a 'New Park' button at the left side of the line of each scenario listed / or you could shift click to start from scratch.

I think it's simple enough to implement, and doesn't interfere with vanilla behaviour/feeling of the game. It simply modernizes the game it in a way that gives previously completed parks a more 'lasting' feel than those Windows 3.1 styled window save games all thrown in the same overflowing folder.
Because I've noticed, people either play scenarios just to complete them, many times not even saving the games if they're completed in one session; or entirely playing custom games disregarding the original scenarios. But sometimes I would like to continue playing a previous scenario that was completed and add to it.
This feature would auto load the last savegame of the scenario with the default name, not messing with multiple saves of different playthroughs.

![proposition](https://user-images.githubusercontent.com/42184451/43796018-4f770f9a-9a83-11e8-8e53-3100a69e7e8e.jpg)
EDIT: The picture shows a park Botany Breakers that is visible that was completed, and theres a save file (of the park which I played to complete the objective) which would be loaded if you would click on Botany Breakers. But if you would want to start a fresh scenario, then you would click on the 'New Park' button in the same line as the park you wish to play.

**Comment by Patrik356b** [comment]
I don't see the point ?

If you go into options, there is an option under the Miscellaneous tab to enable or disable progressive unlocking.

**Comment by baaz11** [comment]
I think you didn't understand as I intended. 
Progressive unlocking is just so you can't play the last park before completing the previous ones - as the name suggests, it disables higher tier parks before you complete the previous ones, like the ones grayed out in the picture in my post.
What I was talking about is that the autosaved parks you play (particularly the scenario parks), the ones that get saved under its original name of the park, or autosaved, are automaticly loaded when you click on the scenario name in the scenario window, not a fresh park everytime. So you wouldn't need to search for your park to continue in the saved file browser, but the parks in the scenario windows would be associated with the last savegame of that park. So it would make the scenario parks more 'lasting' in the sense that they dont get lost in the clutter of a save folder, but are linked to the scenario name in the scenario window. Also there would be a option to start a new park with this scenario thus the 'New Park' button in the picture in my post.
I hope you understand what I meant, english isn't my native language :)

**Comment by AaronVanGeffen** [comment]
Thanks for your feature request. I can see why having the scenario select screen act as a save game selector would save some hassle. Personally, I think it would be better to keep them separate, however. Perhaps this could be implemented as a plugin, when the plugin system is finished, though.

**Comment by Patrik356b** [comment]
Thanks for clarifying @baaz11
