### ISSUE TITLE
Can't type my name after the completion of a scenario (Utopia Park)

### ISSUE THREAD

**Issue by TomGarstenveld** [OpenRCT2/OpenRCT2#7861]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.2.0]
**Commit/Build:** [e.g. 426e106]

so i'm playing all the RCT 1 scenario's and i complete them and i fill in my name, but not with Utopia Park, I completed it for the first time and i can't type in my name, played it again with cheats so i'll get a high company value but that didn't work aswell.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Play Utopia park
2. Complete the park

**Dump file**

[highscores.txt](https://github.com/OpenRCT2/OpenRCT2/files/2268324/highscores.txt)

**Screenshots / Video:**

![glitch](https://user-images.githubusercontent.com/42190794/43806831-e78d8670-9aa5-11e8-9469-b30ba14a7d9d.png)

**Save game:**

Sorry i have no savegame

**Comment by AaronVanGeffen** [comment]
This is likely related to 7f4bb206aff57feb7a02bd093d2c39b3203e70eb changing the internal identification of the park. I'm guessing you started the save before those changes, then completed it after updating?
