### ISSUE TITLE
Feature request: "synchronize with adjacent stations" for transport rides

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#7865]
Currently, no transport rides can synchronize with adjacent stations, it would be great if they could.

**Comment by Broxzier** [comment]
Note: requires new format - it _can_ probably be saved in the SV6 format, but won't work for vanilla RCT2.

**Comment by AaronVanGeffen** [comment]
As long as vanilla RCT2 can safely ignore the flag, I'm fine with exposing the option for transport rides.

**Comment by frutiemax** [comment]
https://github.com/OpenRCT2/OpenRCT2/pull/10280

**Comment by frutiemax** [comment]
#10280

**Comment by Gymnasiast** [comment]
Has been implemented.
