### ISSUE TITLE
Typo in English (US)

### ISSUE THREAD

**Issue by confol1** [OpenRCT2/OpenRCT2#7869]
**OS:** Windows 10
**Version:** 0.2.0
**Commit/Build:** 8784dfb

There is a typo when you hover your mouse over the render weather effects option with the language English (US)
It should be "color" instead of "colour"

**Steps to reproduce:**
1. Go to Render weather effects in the options
2. Hover your mouse over it

Screenshot
![screenshot 1](https://user-images.githubusercontent.com/24375555/43932138-a36efa22-9bff-11e8-9e71-5ef007d0bb1e.png)

**Comment by janisozaur** [comment]
You can fix it yourself by modifying said string in https://github.com/OpenRCT2/Localisation/blob/master/data/language/en-US.txt

**Comment by Gymnasiast** [comment]
I pushed a fix to Localisation. It will be merged overnight.
