### ISSUE TITLE
Obvious error in core string library : String::StartsWith()

### ISSUE THREAD

**Issue by qqkookie** [OpenRCT2/OpenRCT2#7871]
**OS:** Windows
**Version:** 0.2.0
**Commit/Build:**

The String library of ORCT2 core library has obvious error.

From: OpenRCT2/src/openrct2/core/String.cpp  from line 108  to line 207:
Any knowledgeable C/C++ programmer will notice the obvious bug if look code carefully. 
The function `String::StartsWith(str, match)` is assumed to check that `match` is  starting part of `str`.  So   `String::StartsWith( "a", "abc")` should  return false value. 
 
Current code:
<PRE>
   bool StartsWith(const utf8* str, const utf8* match, bool ignoreCase)
    {
        if (ignoreCase)
        {
            while (*str != '\0' && *match != '\0')
            {
                if (tolower(*str++) != tolower(*match++))
                {
                    return false;
                }
            }
            return true;
        }
        else
        {
            while (*str != '\0' && *match != '\0')
            {
                if (*str++ != *match++)
                {
                    return false;
                }
            }
            return true;
        }
    }
</PRE>
But current implementation  fails to check to ensure that `"str"` is longer or equal than length of the `"match"`. So `String::StartsWith("a", "abc") `will returns true. It is obvious bug.

Correct implementation is like this:
<PRE>
    bool StartsWith(const utf8* str, const utf8* match, bool ignoreCase)
    {
        if (ignoreCase)
        {
            while ( *match != '\0')
            {
                if (*str == '\0' || tolower(*str++) != tolower(*match++))
                    return false;
            }
            return true;
        }
        else
        {
            while ( *match != '\0')
            {
                if (*str == '\0' || *str++ != *match++)
                    return false;
            }
            return true;
        }
    }
</PRE>

**Comment by bdupree5** [comment]
I was looking through the code and found that this was not implemented yet. I could take care of this for you.

**Comment by hokasha2016** [comment]
I made a PR for this fix
