### ISSUE TITLE
Some Asian tooltip text is truncated. Option "Disable audio on focus loss" does not work on ride music.

### ISSUE THREAD

**Issue by qqkookie** [OpenRCT2/OpenRCT2#7872]
**OS:** Windows 10
**Version:** 0.2.0
**Commit/Build:** 

The long tooltip text in some windows are truncated in Asian language like Korean. Here is example in Option screen >> Title screen music dropdown menu tooltip. Korean tooltip is truncated and error message is printed in debug version. It is due to the `gCommonStringFormatBuffer[256]`  buffer is way too small. Note that one  Asian character requires 3 bytes of UTF8 chars. Some tooltip text in Korean exceeds 425 bytes in UTF8 string. So the `gCommonStringFormatBuffer` buffer should be increase to 512 bytes. The source code for localisation/tooltip should be changed like below: 
On "OpenRCT2\src\openrct2\localisation\Localisation.cpp" : line 38
`char gCommonStringFormatBuffer[512];`

On "OpenRCT2\src\openrct2\localisation\Localisation.cpp" : line 66
`extern char gCommonStringFormatBuffer[512];`

On "OpenRCT2\src\openrct2-ui\windows\Tooltip.cpp" :  line 87
OLD:
    format_string(buffer, 256, id, gCommonFormatArgs);
NEW:
   `format_string(buffer, sizeof gCommonStringFormatBuffer, id, gCommonFormatArgs);

----------------------------------------------
2nd error is that if  Sound options are so that sound effect is disabled but ride music is enabled in Option , then  the "Disable audio on focus loss:" does not work. The Ride music keeps playing even after  focus loss. if ride music is enabled alone. To fix this error: 

From "OpenRCT2\src\openrct2-ui\UiContext.cpp", line 357
Original wrong code:
<PRE>
                    if (gConfigSound.audio_focus && gConfigSound.sound_enabled)
</PRE>
Correct code:
<PRE>
                    if (gConfigSound.audio_focus &&
                        (gConfigSound.sound_enabled || gConfigSound.ride_music_enabled))
</PRE>
This will stop playing the ride music also on focus loss.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?
**Screenshots / Video:**

![option](https://user-images.githubusercontent.com/39845532/43992881-0a1ea7f6-9dc0-11e8-9a6d-18064d2bc26d.png)

**Comment by AaronVanGeffen** [comment]
You've already suggested the code changes — again, feel free to open a PR. :)

**Comment by Gymnasiast** [comment]
Please do not put two separate issues into one report.
