### ISSUE TITLE
For  autosave frequency option, spinner control is better than dropdown memu.  

### ISSUE THREAD

**Issue by qqkookie** [OpenRCT2/OpenRCT2#7874]
**OS:** Windows 10
**Version:** 0.2.0
**Commit/Build:** 

In Option window, Advanced option tab, "Autosave frequency" option  config , dropdown menu is used to select autosave time period.  The dropdown menu has 6 choices: 1 min, 5 min, 15 min, 30 min, a hours and never.  But I think that time choices are little bit too coarse. 
IMHO, spinner control with +/- buttons is better than dropdown menu for this purpose for finer control over Autosave frequency, I think.  So I tried quick and dirty implementation. See for yourself. It look better, doesn't it?

The spinner will increment/decrement variable. i.e. Naver, 1 min , 2 , 3,...., 14, 15, 20, 25, 30, 40, 50, and an hours and back to Never.

![autosave](https://user-images.githubusercontent.com/39845532/43994326-14879caa-9dd6-11e8-81d6-e9b7367bee36.png)

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Comment by AaronVanGeffen** [comment]
> Commit/Build: Vanilla version

Vanilla RCT2 did not have autosaves.

While I see the logic in it being a spinner widget, I can see the logic behind it being a dropdown: you have two-click access to the most common options. Imagine having to go to 30 minutes from 1 minute: you'd have to click 29 times.

You could, of course, change the interval to something bigger — but then the same coarseness argument you're making would hold.

**Comment by Patrik356b** [comment]
![image](https://user-images.githubusercontent.com/2000703/44258216-9ce07e00-a20e-11e8-91dd-43b3b73a28a2.png)

this may look like overkill, but it would be the ideal solution.

**Comment by marijnvdwerf** [comment]
Why would this be required?
