### ISSUE TITLE
Editable shortcut key file in text format.

### ISSUE THREAD

**Issue by qqkookie** [OpenRCT2/OpenRCT2#7875]
**OS:** Windows 10
**Version:** 0.2.0
**Commit/Build:** 

The shortcut keys config is saved in "hotkeys.dat" as binary file. So it is hard to review or edit externally.  Changing shortcut with in-game Shortcut key config window one by one is little bit tedious and prone to error.  I wish that I can edit the shortcut key config file as text file with text editor. INI file like config file ("config.ini") will be better than binary file for it. Here is my example or suggestion.

As added bonus, please add new "Rotate construction object counter-clockwise." shortcut key.

--------------------------
<PRE>
[ShortcutKeys]
version = 11
count = 77
SHORTCUT_CLOSE_TOP_MOST_WINDOW = "Tab"
SHORTCUT_CLOSE_ALL_FLOATING_WINDOWS = "Escape"
SHORTCUT_CANCEL_CONSTRUCTION_MODE = "Delete"
SHORTCUT_PAUSE_GAME = "Space"
SHORTCUT_ZOOM_VIEW_OUT = "PageDown"
SHORTCUT_ZOOM_VIEW_IN = "PageUp"
SHORTCUT_ROTATE_VIEW_CLOCKWISE = "Return"
SHORTCUT_ROTATE_VIEW_ANTICLOCKWISE = "Backspace"
SHORTCUT_ROTATE_CONSTRUCTION_OBJECT = "X"
SHORTCUT_UNDERGROUND_VIEW_TOGGLE = "1"
SHORTCUT_REMOVE_BASE_LAND_TOGGLE = "H"
SHORTCUT_REMOVE_VERTICAL_LAND_TOGGLE = "J"
SHORTCUT_SEE_THROUGH_RIDES_TOGGLE = "3"
SHORTCUT_SEE_THROUGH_SCENERY_TOGGLE = "4"
SHORTCUT_INVISIBLE_SUPPORTS_TOGGLE = "5"
SHORTCUT_INVISIBLE_PEOPLE_TOGGLE = "6"
SHORTCUT_HEIGHT_MARKS_ON_LAND_TOGGLE = "8"
SHORTCUT_HEIGHT_MARKS_ON_RIDE_TRACKS_TOGGLE = "9"
SHORTCUT_HEIGHT_MARKS_ON_PATHS_TOGGLE = "0"
SHORTCUT_ADJUST_LAND = "SHIFT +F9"
SHORTCUT_ADJUST_WATER = "SHIFT +F10"
SHORTCUT_BUILD_SCENERY = "F10"
SHORTCUT_BUILD_PATHS = "F9"
SHORTCUT_BUILD_NEW_RIDE = "F11"
SHORTCUT_SHOW_FINANCIAL_INFORMATION = "F1"
SHORTCUT_SHOW_RESEARCH_INFORMATION = "I"
SHORTCUT_SHOW_RIDES_LIST = "F2"
SHORTCUT_SHOW_PARK_INFORMATION = "F3"
SHORTCUT_SHOW_GUEST_LIST = "F4"
SHORTCUT_SHOW_STAFF_LIST = "F5"
SHORTCUT_SHOW_RECENT_MESSAGES = "F7"
SHORTCUT_SHOW_MAP = "F6"
SHORTCUT_SCREENSHOT = "PrintScreen"
SHORTCUT_REDUCE_GAME_SPEED = "-"
SHORTCUT_INCREASE_GAME_SPEED = "="
SHORTCUT_OPEN_CHEAT_WINDOW = "CTRL +ALT +C"
SHORTCUT_REMOVE_TOP_BOTTOM_TOOLBAR_TOGGLE = "K"
SHORTCUT_SCROLL_MAP_UP = "Up"
SHORTCUT_SCROLL_MAP_LEFT = "Left"
SHORTCUT_SCROLL_MAP_DOWN = "Down"
SHORTCUT_SCROLL_MAP_RIGHT = "Right"
SHORTCUT_OPEN_CHAT_WINDOW = "/"
SHORTCUT_QUICK_SAVE_GAME = "F8"
SHORTCUT_SHOW_OPTIONS = "O"
SHORTCUT_MUTE_SOUND = "L"
SHORTCUT_WINDOWED_MODE_TOGGLE = "T"
SHORTCUT_SHOW_MULTIPLAYER = "SHIFT +/"
SHORTCUT_PAINT_ORIGINAL_TOGGLE = ""
SHORTCUT_DEBUG_PAINT_TOGGLE = ""
SHORTCUT_SEE_THROUGH_PATHS_TOGGLE = "G"
SHORTCUT_RIDE_CONSTRUCTION_TURN_LEFT = "Keypad 4"
SHORTCUT_RIDE_CONSTRUCTION_TURN_RIGHT = "Keypad 6"
SHORTCUT_RIDE_CONSTRUCTION_USE_TRACK_DEFAULT = "Keypad 5"
SHORTCUT_RIDE_CONSTRUCTION_SLOPE_DOWN = "Keypad 2"
SHORTCUT_RIDE_CONSTRUCTION_SLOPE_UP = "Keypad 8"
SHORTCUT_RIDE_CONSTRUCTION_CHAIN_LIFT_TOGGLE = "Keypad +"
SHORTCUT_RIDE_CONSTRUCTION_BANK_LEFT = "Keypad 1"
SHORTCUT_RIDE_CONSTRUCTION_BANK_RIGHT = "Keypad 3"
SHORTCUT_RIDE_CONSTRUCTION_PREVIOUS_TRACK = "Keypad 7"
SHORTCUT_RIDE_CONSTRUCTION_NEXT_TRACK = "Keypad 9"
SHORTCUT_RIDE_CONSTRUCTION_BUILD_CURRENT = "Keypad 0"
SHORTCUT_RIDE_CONSTRUCTION_DEMOLISH_CURRENT = "Keypad -"
SHORTCUT_LOAD_GAME = "CTRL +L"
SHORTCUT_CLEAR_SCENERY = "U"
SHORTCUT_GRIDLINES_DISPLAY_TOGGLE = "7"
SHORTCUT_VIEW_CLIPPING = ""
SHORTCUT_HIGHLIGHT_PATH_ISSUES_TOGGLE = "B"
SHORTCUT_PAUSE_GAME_ALT = ""
SHORTCUT_ZOOM_VIEW_OUT_ALT = "W"
SHORTCUT_ZOOM_VIEW_IN_ALT = "E"
SHORTCUT_ROTATE_VIEW_CLOCKWISE_ALT = "R"
SHORTCUT_ROTATE_VIEW_ANTICLOCKWISE_ALT = "Q"
SHORTCUT_ROTATE_CONSTRUCTION_OBJECT_CCW = "Z"
SHORTCUT_SCROLL_MAP_UP_ALT = "D"
SHORTCUT_SCROLL_MAP_LEFT_ALT = "A"
SHORTCUT_SCROLL_MAP_DOWN_ALT = "S"
SHORTCUT_SCROLL_MAP_RIGHT_ALT = "F"
</PRE>
--------------------------

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Comment by AaronVanGeffen** [comment]
Personally, I wouldn't mind it being moved to a JSON file or some-such. It's not a high priority for us, but feel free to submit a PR.

**Comment by Patrik356b** [comment]
@AaronVanGeffen json is only acceptable if linebreaks are supported in cases like this I think.

**Comment by AaronVanGeffen** [comment]
@Patrik356b We support line breaks in JSON files. See the JSON objects, for example.

**Comment by Patrik356b** [comment]
@AaronVanGeffen okay. I'm just so used to editing json files that gets run through StripNL so I was suspecting OpenRCT2 were no different from Scrap Mechanic and other games that uses the json format.

**Comment by IntelOrca** [comment]
YAML is better for configuration

**Comment by AaronVanGeffen** [comment]
We've been exploring the use of `yaml-cpp` for OpenLoco recently. Perhaps we could switch OpenRCT2's config from INI to YAML, too, then? (Probably best with a transition period of sorts where INI is still supported for migration…)

**Comment by IntelOrca** [comment]
For the plugin system, I would like to allow custom shortcuts to be registered. For this I was thinking of making the shortcut IDs strings instead and storing them in a new text based file format (json or yaml) where we can preserve all the shortcuts even if you haven't loaded the plugin that registered it.

Additional to that, I would like to allow multiple bindings per shortcut and for mouse buttons to be possible bindings so that you can bind mouse 3 and 4 (usually the navigational buttons on the mouse).

**Comment by rottier** [comment]
I'll give it a shot! I think a human readable ini-file is a good start. Would be nice to go full YAML in the future for all(?) configuration files.

**Comment by AaronVanGeffen** [comment]
I think the loading of shortcut bindings has not been implemented at all yet, though — it is just part of the config struct at this point. You're welcome to implement an alternative. However, going for INI at this point only to replace it with YAML soon-ish seems like a waste of your time. We already have YAML bindings, so I suggest you use those instead. :slightly_smiling_face:

**Comment by IntelOrca** [comment]
@rottier I currently have a branch where I am working on revising keyboard shortcuts for the purpose of plugin use. You're right YAML is where we want to head for shortcuts but we need to do some preamble work to get a YAML library first. Would you be able to work on a different issue instead?

**Comment by rottier** [comment]
> @rottier I currently have a branch where I am working on revising keyboard shortcuts for the purpose of plugin use. You're right YAML is where we want to head for shortcuts but we need to do some preamble work to get a YAML library first. Would you be able to work on a different issue instead?

Sure thing, thanks for notifying, I'll try to find another issue that's somewhat within my ballpark.
