### ISSUE TITLE
Sava file browser list sort by file name should sort in logical order, not  dictionary order.

### ISSUE THREAD

**Issue by qqkookie** [OpenRCT2/OpenRCT2#7877]
**OS:** Windows 10
**Version:** 0.2.0
**Commit/Build:** 

Currently OpenRCT2 save/load file browser sort and list file names in dictionary order: i.e. "ParkSave12" comes  before "ParkSave2".  But MS Windows file explorer lists files in so-called logical/natural order. i.e. "ParkSave2" comes before "ParkSave12". IMHO, windows way of logical sort for file name is better than file list sorted in dictionary order. It can be implemented very simply: Just change 2 lines of code in "LoadSve.cpp"

OpenRCT2\src\openrct2-ui\windows\LoadSave.cpp :  line 760~ line 764
OLD CODE:
<PRE>
        case SORT_NAME_ASCENDING:
            return strcicmp(a.name.c_str(), b.name.c_str()) < 0;
        case SORT_NAME_DESCENDING:
            return -strcicmp(a.name.c_str(), b.name.c_str()) < 0;
</PRE>
NEW CODE:
<PRE>
        case SORT_NAME_ASCENDING:
            return strlogicalcmp(a.name.c_str(), b.name.c_str()) < 0;
        case SORT_NAME_DESCENDING:
            return -strlogicalcmp(a.name.c_str(), b.name.c_str()) < 0;
</PRE>

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Comment by AaronVanGeffen** [comment]
Sounds good. Feel free to submit a PR for this.

**Comment by duncanspumpkin** [comment]
Was this implemented?

**Comment by AaronVanGeffen** [comment]
Not yet.

**Comment by nexgenration** [comment]
should 
```C++

        default:
            return strcicmp(a.name.c_str(), b.name.c_str()) < 0;
```
also be changed to 
```C++

        default:
            return strlogicalcmp(a.name.c_str(), b.name.c_str()) < 0;
```
???

**Comment by AaronVanGeffen** [comment]
Yes, that sounds like a good catch.

**Comment by hokasha2016** [comment]
Hey, I'm playing with issue and I havent seen a PR for it. ive done the fix as mentioned above, but i dont believe its changed anything in terms of the order the files are shown.

**Comment by hokasha2016** [comment]
Ill make the PR for it now

**Comment by hokasha2016** [comment]
ive made a PR for this issue, im sorry for the many unnessecary commits
