### ISSUE TITLE
Scroll shortcut keys ignore SHIFT/CTRL/ALT modifiers. 

### ISSUE THREAD

**Issue by qqkookie** [OpenRCT2/OpenRCT2#7878]
**OS:** Windows
**Version:** 0.2.0
**Commit/Build:** 

Scroll shortcut keys like Scroll right/left/up/down keys ignore SHIFT/CTRL/ALT modifiers. 
For example, if I set plain "D"  key (without any modifier) as scroll right (in "WASD" formation), then pressing SHIFT-D or CTRL-D or ALT-D will also scrolls screen to the rightdirection. This is only applies to the 4 scroll (Scroll right/left/up/down) keys. All other keys honour modifier keys and works as expected.

EDIT: added fix code

-------------------
ORIGINAL
OpenRCT2\src\openrct2-ui\input\KeyboardShortcuts.cpp: line 171 ~192
<PRE>
        if (shortcutKey & SHIFT)
        {
            if (!keysState[SDL_SCANCODE_LSHIFT] && !keysState[SDL_SCANCODE_RSHIFT])
                continue;
        }
        if (shortcutKey & CTRL)
        {
            if (!keysState[SDL_SCANCODE_LCTRL] && !keysState[SDL_SCANCODE_RCTRL])
                continue;
        }
        if (shortcutKey & ALT)
        {
            if (!keysState[SDL_SCANCODE_LALT] && !keysState[SDL_SCANCODE_RALT])
                continue;
        }
#ifdef __MACOSX__
        if (shortcutKey & CMD)
        {
            if (!keysState[SDL_SCANCODE_LGUI] && !keysState[SDL_SCANCODE_RGUI])
                continue;
        }
#endif
</PRE>
-------------------
Fixed code
<PRE>
        if ((bool)(shortcutKey & SHIFT) !=
            (keysState[SDL_SCANCODE_LSHIFT] || keysState[SDL_SCANCODE_RSHIFT]))
            continue;
        if ((bool)(shortcutKey & CTRL) !=
            (keysState[SDL_SCANCODE_LCTRL] || keysState[SDL_SCANCODE_RCTRL]))
            continue;
        if ((bool)(shortcutKey & ALT) !=
            (keysState[SDL_SCANCODE_LALT] || keysState[SDL_SCANCODE_RALT]))
            continue;
#ifdef __MACOSX__
        if ((bool)(shortcutKey & CMD) !=
            (keysState[SDL_SCANCODE_LGUI] || keysState[SDL_SCANCODE_RGUI]))
            continue;
#endif
</PRE>
-----------------

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Comment by bdupree5** [comment]
I all this to the code and make a pull request if one is not added already.
