### ISSUE TITLE
Lag with lots of Guests

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#788]
Once you get above ~1500 peeps, the game starts to noticeably lag, but in the original RCT2 this was not the case. To test I loaded a map and put 9601 people on screen, which lagged pretty bad. I loaded the same map in RCT2 and it didn't lag nearly as much. Perhaps someone could take a look at the code handling the peeps and see if it can be improved speed wise?

https://www.dropbox.com/s/isj8fuyteiiowzs/9601.SV6?dl=1

**Comment by IntelOrca** [comment]
Although we can't actually compile OpenRCT2 with optimisations yet, I would still expect the unoptimised code to still handle 1500 peeps.

**Comment by adrian17** [comment]
I see a slight slowdown when all of them are visible on the screen (which indeed seems to be larger in OpenRCT2), but besides that, I don't experience any lags.

**Comment by PFCKrutonium** [comment]
I have had an idea - would it be possible to monitor the FPS and call update more often (like pressing the Speedup Button), so we can maintain the speed of the game, even if we are not actually rendering more frames?

**Comment by rustinlee** [comment]
@PFCKrutonium I don't wanna speak for anyone working on this but I have to assume [delta timing](https://en.wikipedia.org/wiki/Delta_timing) would be horrifically difficult to retroactively implement for RCT2.

**Comment by PFCKrutonium** [comment]
@rustinlee Actually I think the recent addition of unlimited fps kindof did that - since the graphics are no longer tied to the game speed to the same degree.

**Comment by IntelOrca** [comment]
We have also now enabled optimisations, so the performance is a lot better.

**Comment by PFCKrutonium** [comment]
^That too. I think we can close this topic.
