### ISSUE TITLE
Headless server log is stored incorrectly if server name contains CJK in Ubuntu

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#7883]
**OS:** Ubuntu 18.04.1 LTS
**Version:** 0.2.0
**Commit/Build:** b25cb8c

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

It is about #6547 again, in headless server, server log is incorrectly stored if server name contains CJK.
I pulled a request #6565 and worked fine in Windows 10.
But when I try to start server in **Ubuntu**, korean server name is not correctly handled.
I have no idea where is problem, so I ask you a help.

In _config.ini_:
```
(...)
server_name = "서버"
(...)
```

openrct2-cli displays:
```
(...)
WARNING[/home/orct/build/src/openrct2/platform/Posix.cpp:108 (platform_utf8_to_multibyte)]: truncated string /home/orct/serverlogs/����
(...)
```
And a directory with corrupted name is generated. I have no idea whether log text file is in or not.
.
.

Notes:
 1. _config.ini_ file is using UTF-8 encoding
 1. ``locale`` command shows:
 ```
 LANG=ko_KR.UTF-8
 LANGUAGE=
 LC_CTYPE="ko_KR.UTF-8"
 LC_NUMERIC="ko_KR.UTF-8"
 LC_TIME="ko_KR.UTF-8"
 LC_COLLATE="ko_KR.UTF-8"
 LC_MONETARY="ko_KR.UTF-8"
 LC_MESSAGES=POSIX
 LC_PAPER="ko_KR.UTF-8"
 LC_NAME="ko_KR.UTF-8"
 LC_ADDRESS="ko_KR.UTF-8"
 LC_TELEPHONE="ko_KR.UTF-8"
 LC_MEASUREMENT="ko_KR.UTF-8"
 LC_IDENTIFICATION="ko_KR.UTF-8"
 LC_ALL=
 ```

**Comment by AaronVanGeffen** [comment]
It does something similar for me, although the characters aren't mojibake'd.

```
$ grep server_name ~/.config/OpenRCT2/config.ini
server_name = "ターディス"
$ ./openrct2-cli host ~/.config/OpenRCT2/save/ファントピア.SV6 
ERROR[../src/openrct2/object/ObjectFactory.cpp:432 (CreateObjectFromJson)]: Object rct2.rckc has an incorrect sourceGame parameter.
ERROR[../src/openrct2/network/TcpSocket.cpp:143 (Listen)]: IPV6_V6ONLY failed. 92
WARNING[../src/openrct2/platform/Posix.cpp:108 (platform_utf8_to_multibyte)]: truncated string /home/aaron/.config/OpenRCT2/serverlogs/ターディス
Ready for clients...
```

**Comment by telk5093** [comment]
I put a printf for debug at Posix.cpp#L190 like this:
```
(...)
bool platform_ensure_directory_exists(const utf8* path)
{
    mode_t mask = openrct2_getumask();
    char buffer[MAX_PATH];
    platform_utf8_to_multibyte(path, buffer, MAX_PATH);
    printf("platform_ensure_directory_exitsts / path = %s\n", path);
    printf("platform_ensure_directory_exitsts / buffer = %s\n", buffer);

    log_verbose("Create directory: %s", buffer);
(...)
```

And it shows: (a tested server name was ```테스트용 서버```)
![image](https://user-images.githubusercontent.com/10726524/61180072-4b718680-a64b-11e9-9c82-1236596bf9d5.png)
(Don't mind ```Path debug:``` line, which was a debug line only for me)

As you can see above, ```buffer``` can't store correct utf8 characters.
I have a doubt if there is a problem with ```platform_utf8_to_multibyte()``` function in Posix.cpp.

**Comment by IntelOrca** [comment]
It is a bug in `utf8_to_widechar`. That should be changed to use libicu. It also shouldn't do any of this if the OS codepage is already UTF-8.

**Comment by Gymnasiast** [comment]
@telk5093 Would you be able to test if #9637 fixes this issue?

**Comment by telk5093** [comment]
@Gymnasiast I pulled your ``test/utf-posix`` repository and so build the game myself, and it seems it generates server logs correctly. I'm not sure, but I think it fixes this issue.
