### ISSUE TITLE
Unfinished preserved rides can be demolished with quick demolish

### ISSUE THREAD

**Issue by Umdlye** [OpenRCT2/OpenRCT2#7884]
**OS:** Win10 x64
**Version:** 0.2.0-270
**Commit/Build:** 78e23e6

Demolishing them gives you the error you'd get when trying to destroy preserved track but demolishes the whole thing anyway while leaving behind some ghost bits.

![2018-08-12_22-35-43](https://user-images.githubusercontent.com/11657101/44006236-07a45298-9e81-11e8-9997-a1394b367359.gif)

**Comment by AaronVanGeffen** [comment]
It shows the wrong error string, anyway, right? "Local authority forbids demolition or modifications to this ride" is the right one.

**Comment by Umdlye** [comment]
This is a scenario where you have to complete the rollercoasters, so you can (and should) modify them.
