### ISSUE TITLE
Error when opening a SV4 park

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#7892]
**OS:** Windows 10
**Version:** 0.2.0
**Commit/Build:** 13c326e

When I open the attached save file I get this error a couple of minutes after opening the park.
![image](https://user-images.githubusercontent.com/25930360/44047384-747a6d8c-9f2e-11e8-9a4b-34e94318a83d.png)
It doesn't really do anything, as whichever option I click (abort/retry/ignore) it disappears and the game continues like normal.

**Save game:**
[Workbench_Giraty.txt](https://github.com/OpenRCT2/OpenRCT2/files/2284037/Workbench_Giraty.txt)

**Comment by Broxzier** [comment]
That value is most likely the result of an underflow. Recounting the number of guests heading for the park on import will probably fix it.

**Comment by Gymnasiast** [comment]
No longer reproducible as of OpenRCT2, v0.4.2-226 (a4b60e8ed6 on steep-flume, DEBUG).
