### ISSUE TITLE
Crash while loading save, fixed by unpacking objects in vanilla

### ISSUE THREAD

**Issue by Umdlye** [OpenRCT2/OpenRCT2#7894]
**OS:** Win10 x64
**Version:** 0.2.0-286
**Commit/Build:** 81b788f

Loading this save made the game crash, managed to fix it by successfully loading it in vanilla, saving it without packed objects then copying the unpacked objects to the OpenRCT2 object folder and loading the new save there. The same method for someone else who had trouble loading a different park.

Included in the .zip are the old save, the new save and the packed custom objects.

[crash.zip](https://github.com/OpenRCT2/OpenRCT2/files/2284692/crash.zip)

**Comment by Umdlye** [comment]
Narrowed it down to `LöWE.DAT`. I assume it doesn't like packed objects with special characters in the filename.

**Comment by tupaschoal** [comment]
I cannot reproduce this in 0.3.1 anymore. Please reopen if you manage to, thanks!
