### ISSUE TITLE
The Config InitWite/IniReader GetFloat() should use double float, not single float

### ISSUE THREAD

**Issue by qqkookie** [OpenRCT2/OpenRCT2#7896]
**OS:** Windows
**Version:** 0.2.0
**Commit/Build:**

In Config INI file handler InitWite/IniReader, the GetFloat() and WriteFloat() routines currently  uses 32 bit single float type. But they should use 64 bit double float instead of single float.
For example, I save some data "12345.6" in INI file using WriteFloat(), then it is saved as something like
"12345.599842" due to float point number rounding error. Reading it using GetFloat() it also subject to similar error. Converting it to int32_t subject to truncation error. 

Using 64 bit double  precision float will abolish such problems.  12345.6 will be saved as "12345.600000" and much safer from rounding error or truncation hazzard. 

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Comment by janisozaur** [comment]
We hardly use any real values in the code, making them double seems pointless to me, even in light of your arguments.

We will not be able to use the exact values and upon conversion to SP floats for consumption promoting them on save to DP floats will yield the same value as would using SP on save.

If a user wants to modify a value they can, but it will be a subject to what I said above anyway, DP or not.

I veto this.

**Comment by qqkookie** [comment]
Currently, WriteFloat() or GetFloat() is not used at all in any current source code.  So there is no impact on existing code.  No performance impact. So why not improve for better?

It is not for code or game working. It is for human who read the INI file.  For example,  MONEY32 type is int32_t. So int can be saved and restored exactly with  WriteInt32()/GetInt32().  No round error to worry about.  But it $1234.56  will be saved  such like `current_cash = 123456` .  Quite misleading, isn't it?

IMHO, it would be better to save it as `current_amount =1234.560000` for human to read and edit INI file manually. I can not think of any downside for it.

**Comment by Broxzier** [comment]
`WriteFloat` and `GetFloat` _are_ used.

https://github.com/OpenRCT2/OpenRCT2/blob/0d99186085c7d8d262a14167e0c88ebcbfca9fdb/src/openrct2/config/Config.cpp#L193

For values with a fixed precision, integers are more reliable than floating points for the exact reason you stated. Floating points (that includes doubles also) can be inaccurate for higher precision values.

**Comment by jensj12** [comment]
Different currencies use different values, all derived from the same integer representation (in this example, `123456`). Even though a double looks far more precise than a float, using an int is still strictly more precise.
If you really want to hand-edit files, you should be able to do the conversion manually. If not, use in-game cheats.

**Comment by IntelOrca** [comment]
If you wanted precision then you would use a decimal type (something coded in bcd). However for the properties we do use floats for, we expect the numbers to be a power of 2 fraction which is stored accurately.
