### ISSUE TITLE
Feature Request: Option to turn off Scroll Wheel Zooming (i.e. for trackpads)

### ISSUE THREAD

**Issue by Kuriibo** [OpenRCT2/OpenRCT2#7905]
On a laptop with a multitouch trackpad, where clicking with two fingers is a right-click, it is difficult to pan the camera, as the game often zooms in/out instead, since moving up/down with two fingers on the trackpad is treated as turning the scroll wheel. This could be alleviated easily by giving the player the option for the game to not zoom in/out when it receives input from the scroll wheel.

**Comment by Gymnasiast** [comment]
To me, this sounds like a problem with the touchpad, rather than OpenRCT2, and in any case, it seems not many people want this. I'll therefore close this.
