### ISSUE TITLE
Unable to save new scenarios

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#7911]
**OS:** Windows 10
**Version:** 0.2.0-316
**Commit/Build:** ea8bab9

When starting a new scenario, the park cannot be saved. It can only overwrite existing park files.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Start a new scenario
2. Save the park as a file that does not exist yet
3. An "Invalid characters used" error is given

This works from starting a previously saved game but saving it with a new name too:
1. Load an existing save
2. Save with a new name
3. An "Invalid characters used" error is given

**Comment by L3mmy** [comment]
That is one of a weird bug

**Comment by RustD0GGY** [comment]
Yup, having to rely on autosaves for now.

**Comment by Broxzier** [comment]
As a temporary work around, you can open the system file browser, create a dummy scenario file (just copy another one and rename it, or create a text file then rename it to have the SV6 extension), and overwrite that file. Then saving does work.
