### ISSUE TITLE
RCT1 title sequence timing is off

### ISSUE THREAD

**Issue by jensj12** [OpenRCT2/OpenRCT2#7913]
**OS:** Windows 10
**Version:** 0.2.0-316
**Commit/Build:** ea8bab9

The RCT1 title sequences stay longer at the same screen than in the original game (or physics are very different, but that's unlikely). This is especially notable on Diamond Heights, Karts & Coasters and Three Monkeys Park, where coaster trains are already (almost) gone when the screen is focused on them.

**Steps to reproduce:**
1. Set title sequence to one from RCT1
2. Go to main menu and watch

**Comment by AaronVanGeffen** [comment]
This is just speculation, but think this could have been introduced when we changed the wait times to milliseconds.

**Comment by Gymnasiast** [comment]
Which RCT1 scenarios are you using? SC4 ones or Crappage's recreations?

**Comment by Gymnasiast** [comment]
It might have been caused by https://github.com/OpenRCT2/title-sequences/pull/1, which multiplied all intervals by 8000, expect for the original RCT1 and RCT2 ones.

If it turns out to be caused by that, it would be a good moment to replace the `LOADRCT1` commands as well.

**Comment by AaronVanGeffen** [comment]
> It might have been caused by OpenRCT2/title-sequences#1, which multiplied all intervals by 8000, expect for the original RCT1 and RCT2 ones.

The PR you're linking was updating the timing for the *original* sequences, by a factor 1000. One was forgotten, which has been [addressed](https://github.com/OpenRCT2/title-sequences/commit/a857f04d6cd2fdb56fcade724ff7a4a770b85a8c)...

**Comment by Gymnasiast** [comment]
It updated the _custom_ sequences by multiplying by 800, though. I think it should have done the same with the original ones.
