### ISSUE TITLE
Fedora build - ICU Libraries were not found, uc required

### ISSUE THREAD

**Issue by bloggi85** [OpenRCT2/OpenRCT2#7915]
**OS:** Fedora 28
**Version:** 28
**Commit/Build:** v 0.2.0 (0aff800)

When building on a vanilla fedora environment and following the instructions in the Quickstart guide I get an error saying that a dependency is missing:

```
[laurent@localhost build]$ cmake ../
-- Unsupported CXXFLAG: -Wmissing-variable-declarations
-- Unsupported CXXFLAG: -Wunreachable-code-break
-- Unsupported CXXFLAG: -Wrange-loop-analysis
-- Unsupported CXXFLAG: -Wtautological-unsigned-zero-compare
No discord-rpc detected, to enable clone discord-rpc to root directory: /home/laurent/bin/OpenRCT2
-- The following ICU libraries were not found:
--   uc (required)
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Failed to find all ICU components (missing: ICU_INCLUDE_DIR ICU_LIBRARY
  _ICU_REQUIRED_LIBS_FOUND) (Required is at least version "59.0")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindICU.cmake:317 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/openrct2/CMakeLists.txt:115 (find_package)
  CMakeLists.txt:204 (include)


-- Configuring incomplete, errors occurred!
See also "/home/laurent/bin/OpenRCT2/build/CMakeFiles/CMakeOutput.log".
See also "/home/laurent/bin/OpenRCT2/build/CMakeFiles/CMakeError.log".
```

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. On a vanilla fedora setup, follow the steps at https://openrct2.org/quickstart/install/linux/fedora
2. The game won't build and an error will be shown.

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by bloggi85** [comment]
I think all we need to do is to add a line into the instructions to install this dependency?

In particular, update the Fedora instructions to specifically install the `libicu-devel` along all other dependencies:
Update the page at https://openrct2.org/quickstart/install/linux/fedora 

FROM
`
sudo dnf install gcc gcc-c++ jansson-devel \
SDL2_ttf-devel openssl-devel \
speexdsp-devel libcurl-devel \
cmake fontconfig-devel freetype-devel \
libpng-devel libzip-devel mesa-libGL-devel
`
TO
`
sudo dnf install gcc gcc-c++ jansson-devel \
SDL2_ttf-devel openssl-devel \
speexdsp-devel libcurl-devel \
cmake fontconfig-devel freetype-devel \
libpng-devel libzip-devel mesa-libGL-devel libicu-devel`

That seemed to do the trick for me

**Comment by janisozaur** [comment]
Fixed in https://github.com/OpenRCT2/openrct2.github.io/commit/74d0cb1bfa103fc926372862e59f9fe7a1fae5c6 you can update the wiki page yourself, none of us runs fedora.

**Comment by bloggi85** [comment]
Thanks for the quick response @janisozaur 
Looks like somebody beat me to it and already created a PR for it: https://github.com/Limetric/OpenRCT2.org/pull/34
