### ISSUE TITLE
Zero-sized chunk problem

### ISSUE THREAD

**Issue by L3mmy** [OpenRCT2/OpenRCT2#7917]
**OS:** Windows 10
**Version:** 0.2.0
**Commit/Build:** 3e2f814

I want to load my save of my boardwalk park, i saved it yesterday no poblem, but when i tried and load it this morning, OpenRCT2 gave me a error message

- [X] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
 I have no idea why it happened

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/41308252/44330307-f80cad80-a466-11e8-90ae-53426b887040.png)

**Save game:**
[Boardwalk Last try.zip](https://github.com/OpenRCT2/OpenRCT2/files/2301776/Boardwalk.Last.try.zip)

Thanks

**Comment by AaronVanGeffen** [comment]
The save compresses down to 17.4kb. I'm afraid it's been corrupted…
