### ISSUE TITLE
Missing Rides in Botany Breakers

### ISSUE THREAD

**Issue by JonnyDaenen** [OpenRCT2/OpenRCT2#7927]
**OS:** MacOS
**Version:** 0.2.0
**Commit/Build:** f8c765f

When starting the "Botany Breakers" campaign, the following rides are missing:
- Jet Skis
- Swans
- Water Tricycles

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Start Botany Breakers
2. Open Ride Construction
3. Go to "Water Rides"

Expected: rides are there
Observed: rides are not there

**Comment by Gymnasiast** [comment]
They are grouped together under "Boat Hire". Just build a boat hire and select a vehicle afterwards. You can always switch.
