### ISSUE TITLE
Automatically create `track`, `scenario`, `save` and `object` folders

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#7930]
We get frequent questions about where to place stuff, as people do not expect they have to create those folders themselves in many circumstances. If the folders are already there it's a lot easier to see where to put stuff.

**Comment by Osmodium** [comment]
I'd be happy to try to take this on. Any suggestion to where to start looking?

**Comment by Gymnasiast** [comment]
I believe we have a function called "ensuredirectoryexists" or something like that. Not sure where the put the code for it, perhaps just after .ini creation might be a good location.

**Comment by IntelOrca** [comment]
It can be done during Context initialisation, e.g. here:
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/Context.cpp#L351

**Comment by Osmodium** [comment]
Thanks! Will take a look at it :)

**Comment by Osmodium** [comment]
I just had a thought. Wouldn't it be easier to create the folders on install since it is already creating some folders at that point?

**Comment by IntelOrca** [comment]
@Osmodium 

- Install it for all users, so new users after install point will not get them.
- A lot of people use launcher or portable builds which do not use the installer.
- macOS has no installer.
- For Linux you are relying on packagers implementing it

**Comment by Osmodium** [comment]
Got it! Thanks again :)

**Comment by AaronVanGeffen** [comment]
> I wanted to ask where you'd think the button to open the "OpenRCT2" directory should be placed.
> I have experimented with placing it under misc, but I wanted to hear about it first.

Personally, I don't think it has any place in the options screen. If anywhere, I think the loading screen is more appropriate.

**Comment by Broxzier** [comment]
The load/save dialogue would be my first pick, perhaps next to the "use system file browser" button.

Also can you add the `heightmap` folder to the list of folders? Just like saved games, the files don't _have to_ be in that folder, but it's where OpenRCT2 starts when the user has to pick one.

**Comment by Gymnasiast** [comment]
No, it's not the `landscape` folder, but could you add that one as well to the 'ensured' folders?

I think the toolbox is indeed the correct location to put this.

**Comment by IntelOrca** [comment]
A link to the object directory can also be on the object manager window.

**Comment by Osmodium** [comment]
I've now added the heightmap folder, which means that these folders will be created if they don't exist:

- heightmap
- landscape
- object
- save
- scenario
- track

**Comment by Broxzier** [comment]
Two more folders that could be added to that list are:

- themes
- title sequences

**Comment by Osmodium** [comment]
I have made a test where I add a button to the toolbox dropdown menu. This works in this commit (for windows) https://github.com/Osmodium/OpenRCT2/commit/37b641b3277e0f28dfa083c1ee2abb114d4a9963
Would the implementation be the right way to go about it, or is there some other preferred way?

![image](https://user-images.githubusercontent.com/234248/44791853-e7fd7800-aba2-11e8-9fbd-48bd2235944d.png)

**Comment by Osmodium** [comment]
This commit https://github.com/Osmodium/OpenRCT2/commit/8d857dde4334122cf93078166aa4b0c1349c1b8f introduces an open button on every save/load window. This button will open the specific folder for that type of save/load. i.e. when in the "Heightmap"-save/load, the button will open the heightmap folder.

![loadgame](https://user-images.githubusercontent.com/234248/44853926-89e69880-ac67-11e8-8619-e554c3fb8a1d.png)
![loadlandscape](https://user-images.githubusercontent.com/234248/44853932-8d7a1f80-ac67-11e8-9605-3179cf33f7e3.png)
![loadheightmap](https://user-images.githubusercontent.com/234248/44853935-8eab4c80-ac67-11e8-89b3-e94170b0dee8.png)

I have kept the general button in the toolbox, since not all custom content folders are being access direclty from the save/load window.

I will probably use this commit for a PR if no objections are made beforehand :)

**Comment by AaronVanGeffen** [comment]
I'd prefer to have a different PR for the automatic creation of folders, and another for the button.

As for the proposed button, I think it would be better if it included a verb, e.g. "Open %s folder".

**Comment by Osmodium** [comment]
Sure I'll do that :) As for the addition of a verb to the button in the save/load window, it was omitted due to the space available, and I was thinking about other languages. But I sure can add it, and then I guess we'll see at a later point.

**Comment by AaronVanGeffen** [comment]
On second thought, I wonder if the button is necessary at all, if you're including the "Open custom content folder" in the toolbox dropdown. It might just clutter the load/save window unnecessarily with an option few will use.

**Comment by Gymnasiast** [comment]
Has been implemented.
