### ISSUE TITLE
No refund for removing footpath when building coaster 

### ISSUE THREAD

**Issue by bjschuit** [OpenRCT2/OpenRCT2#7931]
**OS:** Win10
**Version:** 0.2.0
**Commit/Build:** latest dev build (and before)

When building the first piece of a coaster, you can right-click tiles to remove i.e. trees or footpaths. However, when deleting footpaths, they are removed but there is no refund of €10 as there should be when removing a footpath. 

- [ ] Reproducible in RCT2 (vanilla)? (will test later, might be)
- [ ] Specific to multiplayer?

**Comment by Broxzier** [comment]
I'm unable to reproduce this issue. As you can see, I'm building a coaster and you can see the +€10 from a path that got removed by rightclicking it:

![forest frontiers 2018-08-27 23-33-04](https://user-images.githubusercontent.com/9705046/44687474-9e514800-aa51-11e8-9d5c-8a13287225d4.png)

Can you try again with the latest develop build (72ad5ee)?

**Comment by bjschuit** [comment]
Doesn't occur anymore in the same level on latest build. Maybe just a temporary bug. Sorry for bothering, will test a bit more next time I run into something ;).

**Comment by felixpelletier** [comment]
Should this issue be closed?

**Comment by bjschuit** [comment]
Yes can be closed, cannot reproduce it anymore. Thank you.
