### ISSUE TITLE
libicuuc.so.60 not found

### ISSUE THREAD

**Issue by simbalion** [OpenRCT2/OpenRCT2#7937]
**OS:** Debian 9

Started the OpenRCT2 launcher, it auto-updated, and now won't load because it's looking for a library which doesn't exist in Debian stable/testing/backports.

**Comment by AaronVanGeffen** [comment]
Is this package installed? https://packages.debian.org/stretch/libicu57

**Comment by simbalion** [comment]
That's a different version. The appropriate one, if it existed, would be named libicu60

**Comment by AaronVanGeffen** [comment]
Ah, I see what you mean. It's likely because our .deb packages are compiled on Ubuntu 18.04, which probably does use ICU v60, then.

We've been using ICU for quite some time, by the way... What version were you on prior to updating?

@janisozaur Any thoughts on this?

**Comment by simbalion** [comment]
when I first installed openrct2 I had to install the package. But I don't know when that was or what version it was.

**Comment by AaronVanGeffen** [comment]
Are you referring to the game or the launcher? Because the latter not a project we develop. (Confusing, I know.)

**Comment by simbalion** [comment]
I've told you everything I know.

**Comment by Gymnasiast** [comment]
You could try installing https://packages.debian.org/buster/libicu60 . I know it's from buster, but it does not have a lot of dependencies, so it might just work.

**Comment by Berbe** [comment]
Another strategy would be to run OpenRCT2 in a container. Haven't tried LXC/D, but I am running a (derivative) of Debian Stretch and I am successfully running the game in a container from the latest Ubuntu version, which has all the documented required libraries.

... or go for backports, if you are not afraid of things getting messy and don't mind setting up APT pinning.

**Comment by simbalion** [comment]
Backports doesn't have the package or I wouldn't have raised an issue.

What would be better is if the launcher would not auto update.

**Comment by Gymnasiast** [comment]
We do not develop the launcher.

**Comment by baryluk** [comment]
Please provide some of the dependencies in the tar.gz together with the executable files as dynamic libraries (and provide a shell script to do use them via LD_LIBRARY_PATH), or link statically some of these libraries. I would say libicu, jansson library, libzip4, libpng16, SDL2, libogg, libvorbis, liblz4, liblzma5. And libssl1.1 for libzip4. All of these libraries are notorious for being updated frequently with fixes, new ABIs (sometimes not backward compatible!) and security fixes, and new soname. So, they should be provided by the game as a fallback when distro don't provide them in standard location. However, do not provide indirect dependencies from SDL to other libraries. As of the fontconfig, I have no idea what is proper action to make for it, as using very outdated library, but newer cache formats from distro could be a bad idea.

I made a small tool to extract direct dependencies, and recursively traverse dependencies of binaries and libraries.

I did ignore ld-linux.so.2 libc.so.6 libm.so.6 libdl.so.2 libpthread.so.0 librt.so.1, as these libraries are used by almost any other library, and it adds too much clutter.

![bzium](https://user-images.githubusercontent.com/110322/67284378-06b87f80-f4c5-11e9-8234-46c2c1542095.png)

**Comment by Gymnasiast** [comment]
@baryluk This issue is about the launcher, not the game.


Since we do not develop the launcher (and even if we did, this would have been the wrong repository to report issues against), I'm going to close this. Launcher bugs can be reported at https://github.com/LRFLEW/OpenRCT2Launcher

**Comment by IntelOrca** [comment]
@Gymnasiast I don't think it is. That is just how the user managed to update to the latest version which now requires libicu which wasn't available on Debian.

**Comment by Gymnasiast** [comment]
@IntelOrca It's hard to say if they don't answer our questions properly.

**Comment by baryluk** [comment]
Not really. The issue with libicu isn't because of the bug in the launcher tho. Using OpenRCT2 with or without launcher leads to the same result and is due same underlying issues - not distributing OpenRCT2 with proper dependencies.

**Comment by IntelOrca** [comment]
Well we already have another issue for AppImage / snap which is usually way forward when it comes to distributing all dependencies. I think this can stay closed as we already have another issue for bundles.

**Comment by Gymnasiast** [comment]
baryluk's point about the amount of dependencies is not even what this issue was originally opened for. 

It was OpenRCT2 being built against a newer version of libicu than the OP's Debian installation offered.

Closing again, then.

**Comment by baryluk** [comment]
The issue is not fixed, as the problem is still there, so I don't know is it a duplicate of some other issue?

I don't see reference to other issues in this issue.

**Comment by Gymnasiast** [comment]
@baryluk We don't support Ubuntu 17.10 and earlier, and the same applies to their respective Debian versions. Ubuntu 18.04, on which the binary we provide is compiled, has ICU 60, which the Debian version of the OP does not have. They can still try to compile it themselves or pull libicu60 from a deb archive. But we're not going to try to modify the binary to link against something older than ICU 60.

**Comment by Ruedii** [comment]
Ubuntu 19.10 ships with ICU 63 and reports the same error.  It does not provide verion 60 at all because 63 is backwards compatible (generally the libicu package is backwards compatible but not forwards compatible.)

Ideally it should look for "libicuuc.so" instead of the versioned file.

If an older version is used it MIGHT fail on a broken symbol, but at least it will work on newer versions.

**Comment by Gymnasiast** [comment]
@Ruedii There is a PPA already: https://openrct2.io/getting-started/index.html

We always recommend people to check if there is a repository available for their distro, since it tends to work better than the tarball and also because it updates the game for you.

**Comment by Berbe** [comment]
The correct behaviour would be to check for versions "equal or higher" for dependencies which are backwards-compatible.

Hence, if `libicu63` is backwards-compatible with `libicu60`, it could make sense to allow building against a newer version of the dependency. Colloquially, it would make no sense not to allow it.

**Comment by AaronVanGeffen** [comment]
Unfortunately, they are not binary compatible, so the point is moot. The binaries we offer for download are targetting a particular version of Ubuntu. I'm not sure if we've upgraded to 20.04 yet; I'm guessing we haven't.

There is a [Launchpad PPA for OpenRCT2](https://launchpad.net/~openrct2), whose builds should be using the libicu version for your particular version of Ubuntu. Perhaps that helps resolve the problem.

**Comment by janisozaur** [comment]
As evident in https://github.com/OpenRCT2/openrct2-docker-build/pull/1, we're still using 18.04. That's useful for CI purposes, as we try to maintain at least some compatibility with outdated systems.
