### ISSUE TITLE
Key validation problem because of my name

### ISSUE THREAD

**Issue by Wardergrip** [OpenRCT2/OpenRCT2#7954]
**OS:** Windows 10 Home
**Version:** 0.2.1
**Commit/Build:** Idk?

So, if I want to join a server it says: key validation failed or something. I contacted someone that knows more and after a while we discovered it is because my computer's name is Reï. The ï is a unknown symbol for OpenRCT2 resulting in searching: Re´". He won't find the key because Re´" doesn't excist. 

- [ ] Reproducible in RCT2 (vanilla)? Nope, you don't need a key there.
- [ ] Specific to multiplayer? Yea 

**Steps to reproduce:**
1. Your computer's name has a weird symbol
2. Try to join a server

**Comment by janisozaur** [comment]
Please attach logs and check if changing the name used in OpenRCT2 from `Reï` to `Rei` (in the server browser window or `config.ini`) helps or not. Please fill in the commit field too.

**Comment by IntelOrca** [comment]
Setting my player name to `Reï` works for me. I do not know how it ended up with `Re´`.

**Comment by IntelOrca** [comment]
It logged out `C:\Users\Re├»\`.

Although that looks wrong, I think that is the correct UTF-8 string. That is what I saw as my player name which worked.

**Comment by Gymnasiast** [comment]
I hesitate to call that 'correct'. If the user folder shows up as `Reï` in Windows and doesn't in OpenRCT2, that's a bug in OpenRCT2 IMO.

**Comment by IntelOrca** [comment]
It is the "expected behaviour" then... I think there is something else wrong. The user name is obtained using the correct APIs for unicode support and converted to UTF-8. The keys are opened using filestream which converts back to UTF-16 for the fopen. I don't know where the problem lies.

**Comment by IntelOrca** [comment]
> Round-trip converting Windows path names is a bad idea.

Ideally we should use `std::path` to eliminate this but it isn't a bad idea, you don't lose any information converting from UTF-16 to UTF-8.

> but Windows doesn't actually use UTF-16. It's UCS-2

Actually it very much depends on the particular API function you are using and how you use it. I believe most are UTF-16 now otherwise it would be impossible to have filenames containing unicode points > `0xFFFF`.

> Granted, if anyone actually does this and complains when things break, it's their fault. But still, platforms being dumb is something that should be accounted for.

Does what? Use non ASCII characters?

**Comment by keiyakins** [comment]
You don't lose any information converting from *valid* UTF-16 to UTF-8. The core functions of Windows, however, *don't use UTF-16*. They use UCS-2. If you put valid UTF-16 in and don't do any slices or anything it stays valid, but Windows is perfectly happy to have a file with, for instance, an unpaired 0xD800 in it.

**Comment by IntelOrca** [comment]
@Wardergrip Could you please try out develop: 208a689 or later and let me know if you still have any issues?

**Comment by m0nk33** [comment]
On windows, latest version (0.2.6).
Had the same issue, key verification failed while multiplayer (LAN). 
This happend because my name was ":) something".
I deleted the ":)" and it worked.
