### ISSUE TITLE
Package as App Image

### ISSUE THREAD

**Issue by tian2992** [OpenRCT2/OpenRCT2#7955]
Packaging as an App Image would mean fully portable linux packages, no dependency hell.

According to their docs, this appimage bins can be generated via Travis pipeline

**Comment by IntelOrca** [comment]
Related: #6112

**Comment by AaronVanGeffen** [comment]
We had someone ask about AppImage the same thing a few days ago as well: #7940. That was closed due to it being similar with #6112 as well.
