### ISSUE TITLE
Ő, ő, Ű` and ű (Hungarian characters) render as question marks

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#7956]
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** e8301e7

Pretty straight forward, these characters don't have a sprite font yet: `Ő` `ő` `Ű` `ű`

They are part of the [Hungarian alphabet](https://en.wikipedia.org/wiki/Hungarian_alphabet).

- [x] Reproducible in RCT2 (vanilla)? (probably, haven't tried)
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Rename anything (park, ride, guest)
2. Enter the string `ŐőŰű`

**Comment by Gymnasiast** [comment]
Before I start making glyphs for them: has anyone requested them? (And not in the way of the Romanian characters?)

**Comment by Broxzier** [comment]
Yes, in the Roller Coaster & Friends Discord server there was someone who wants to improve the Hungarian translations, and he found that these glyphs were missing.
