### ISSUE TITLE
OpenRCT2 Scenario Editor bugs.

### ISSUE THREAD

**Issue by DonVGC** [OpenRCT2/OpenRCT2#7969]
**OS:** [e.g. Windows 7]
**Version:** [e.g. 0.2.1] both latest stable and development
**Commit/Build:** [e.g. a1fd033]

When loading a RCT2 scenario (specifically a .SC6 file) through the Scenario Editor, in Options-Financial, the option "No Money" is always selected by default, and the park objective is always Number of Guests in Park: 2000. It means that somehow the scenario editor is now bugged and isn't loading the correct objectives and settings of the .SC6 files scenarios.

- [ ] Reproducible in RCT2 (vanilla)? Nope, RCT2 vanilla loads .SC6 scenarios properly, with the proper objectives.
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Load a .SC6 scenario in the OpenRCT2 scenario editor
2. Go to the next steps until Options- Financial and Objective Selection are chosen.

**Dump file**

**Screenshots / Video:**

![incorrect](https://user-images.githubusercontent.com/42961631/45021077-463cb780-aff6-11e8-85cf-76f10f0a37ab.png)

**Save game:**

**Comment by Gymnasiast** [comment]
This issue is likely related to https://github.com/OpenRCT2/OpenRCT2/issues/4466.

I have no idea what causes it, though. Could it be memory corruption?

**Comment by DonVGC** [comment]
I don't think this is related to #4466 in the case of memory corruption, since the issue happens at the instant load of a scenario. Just tried this again in my laptop, with a new install of RCT2 Triple Thrill Park from Steam and the OpenRCT2 stable build. Same thing happened, loaded a .SC6 scenario and No Money is checked by default and the Park Objective is still wrong (like in my screenshot)

**Comment by DonVGC** [comment]
This issue is still present in the latest development build (OpenRCT2 v0.2.6-fc43494). Is there any way to fix it?

**Comment by janisozaur** [comment]
Sure, submit PR

**Comment by chaitanyathengdi** [comment]
Same thing happening for me, as I wanted to do something simple: modify an existing scenario.
More specifically, I wanted to change Forest Frontiers to have free rides instead of free park entry and see how it goes.
Virtually none of the initial things are same when loaded though: available rides, research rides, initial money, initial loan amount,...
As such, I have no way of knowing what was there in the SC6 file and what has been added when loading.

**Comment by chaitanyathengdi** [comment]
Works fine when loading on RCT2's scenario editor, but of course I get fewer options; such as missing the original Forest Frontiers financial situation: chargeable rides and chargeable park entry.
