### ISSUE TITLE
Improvement: Clear 'inspection overdue' status when inspection interval changed to 'Never'

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#7975]
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** a1fd033

When a ride is overdue for inspection, changing the inspection interval to 'Never' should stop mechanics from trying to head for the ride. I have a park now with multiple mechanics always occupied with trying to inspect several rides that are used for scenery (parked cars) which they cannot possibly reach.

The rides used to have an inspection interval of 10 minutes because i forgot to change it earlier. Changing it to 'Never' doesn't stop the mechanics from wanting to inspect them.

If the mechanic who wants to go to the ride is picked up and placed back, a different mechanic will try to head for the ride instead.

**Comment by Gymnasiast** [comment]
I'm chalking this up as a bug, since 'Never inspect' and 'Inspect one last time and then never do it again' are different things - users expect the first to happen.

**Comment by deurklink** [comment]
I just checked, and this behaviour was also in the original game, so maybe it should be labeled 'Original bug'
