### ISSUE TITLE
When building Air powered coaster backwards; Slope up does not work.

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#7981]
![2018-09-09_01-47-06](https://user-images.githubusercontent.com/2000703/45259692-cf773400-b3d2-11e8-8744-57e8b50044e7.jpg)

Something isn't executing when hitting the indicated button.  Happens in scenarios and track designer.

Version: ab20dcd

**Comment by Patrik356b** [comment]
Just tested this in rct1 (and later rct2) with the same result

**Comment by moerrek** [comment]
Maybe related to #7464 ?

**Comment by Patrik356b** [comment]
I didn't find that one before, but I think it's the same issue

**Comment by Patrik356b** [comment]
Oops
