### ISSUE TITLE
Not loading anything from $RCT/ObjData?

### ISSUE THREAD

**Issue by srett** [OpenRCT2/OpenRCT2#7982]
**OS:** Linux
**Version:** 0.2.1

I wanted to upgrade to v0.2.1 so I checked out that version from the git repo and compiled. After that, my previously working (mid 2017) OpenRCT2 setup would show an empty flat map in the main menu and refuse to start a new park, reporting a ton of missing objects. I deleted *.idx in `~/.config/OpenRCT2` and launched the game with --verbose:
```
...
VERBOSE: FileIndex:Scanning for *.dat;*.pob;*.json;*.parkobj in '/home/srett/games/OpenRCT2/data/object'
VERBOSE: FileIndex:Scanning for *.dat;*.pob;*.json;*.parkobj in '/home/srett/.config/OpenRCT2/object'
VERBOSE: file '/home/srett/.config/OpenRCT2/objects.idx' exists = 0
Building object index (0 items)
VERBOSE: FileIndex:Writing index: '/home/srett/.config/OpenRCT2/objects.idx'
VERBOSE: Create directory: /home/srett/.config/OpenRCT2
VERBOSE: mkdir(/home)
VERBOSE: mkdir(/home/srett)
VERBOSE: mkdir(/home/srett/.config)
VERBOSE: mkdir(/home/srett/.config/OpenRCT2)
Finished building object index in 0.00 seconds.
VERBOSE: FileIndex:Scanning for *.td4;*.td6 in '/Tracks'
VERBOSE: FileIndex:Scanning for *.td4;*.td6 in '/data/srett/RollerCoaster Tycoon 2 Triple Thrill Pack/Tracks'
VERBOSE: FileIndex:Scanning for *.td4;*.td6 in '/home/srett/.config/OpenRCT2/track'
VERBOSE: file '/home/srett/.config/OpenRCT2/tracks.idx' exists = 0
Building track design index (204 items)
...
```
So it looks like it just doesn't bother checking ObjData, but according to
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/object/ObjectRepository.cpp#L84
this seems intentional. I assumed it would load any required files on-the-fly, but for some reason that doesn't happen for me. `strace ./openrct2` doesn't show a single access attempt to $RCT/ObjData when trying to start a new park. What's going wrong here? I temporarily fixed this by adding `env.GetDirectoryPath(DIRBASE::RCT2, DIRID::OBJECT),` to the constructor call above so I can play now, but I wonder how it should actually work.

**Comment by Broxzier** [comment]
Have you downloaded the JSON objects?

**Comment by srett** [comment]
Aww man, f*sk me. Just when I thought I double-checked everything before opening an issue. I unzipped to `data/objects` not `data/object` (I guess since the it's called objects.zip?)...

Everything works as intended now. Sorry for the noise! (Maybe make the game yell at the user if they're too stupid to set it up? :>)
