### ISSUE TITLE
Request/discussion: Change when G-forces show up in red on the stats screen

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#7983]
Below -1.99 negative G's, the numbers show up as red on the stats screen, even though you get excitement for negative G's up to -2.50. If this was changed so that negative G's wouldn't get red until -2.50 it would be clearer where the cutoff is. 

For lateral G's you get a penalty above 2.80 G's, but 2.80 G's itself already shows up as red, despite not giving a penalty. Changing this to 2.81 to match the penalty threshold would clear up confusion around the edge case of 2.80

Lastly, there's the positive G's, which is different again. They show up as red above 4.99, even though they don't give any penalty and never stop giving excitement. The negative G's also don't give a penalty, which makes the red color on the two vertical G's a bit useless in my opinion. It might be there for realism, but the difference between 4.85 and 4.95 is the same as the difference between 4.95 and 5.05.

If any of these do get changed, the thresholds for the graphs showing up red with the new feature should be changed as well.

**Comment by guillochon** [comment]
Addressed part of this in #7986, but wasn't sure how to address your last point. Thoughts anyone?

**Comment by e-foley** [comment]
Are you certain that negative gs don't give a penalty? There's a function [`ride_ratings_apply_max_negative_g_penalty()`](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/ride/RideRatings.cpp#L1602)  in RideRatings.cpp that seems to get called to divide certain ride ratings in half when the negative gs exceed a threshold (different on different rides).

**Comment by LordMarcel** [comment]
That penalty for not enough negative G's is one that divides all stats by 2 and differs per ride. Some rides have different thresholds and some rides don't have a requirement for negative G's at all. Here is a list of all those requirements: https://www.reddit.com/r/LordMarcel/comments/78maqk/rct2_table_with_the_minimum_stat_requirements_for/

So yes, it is a penalty, but it's not related to the stats being in the red, and it doesn't give extra intensity or nausea.

**Comment by cching0L2** [comment]
What's the status of this issue right now?  If nobody's working on it can I?
