### ISSUE TITLE
Unintentionally made a ride that maxes out cash when created

### ISSUE THREAD

**Issue by Supradyke** [OpenRCT2/OpenRCT2#7987]
**OS:** [Windows 7]
**Version:** whichever one the launcher automatically updated me to, the title screen says "0.2.1-43"

I made a ride called Silvera and whenever I create it with scenery included, it maxes out my cash (doesn't max out cash when scenery is not included)

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. play uild Your Own Magic Mountain in multiplayer
2. mass delete all the scenery
3. own all land cheat
4. no money cheat
5. create ride near the road where X originally was
6. save the ride with "Select Near Scenery"
7. accidentally include the road footpath pieces
8. open new scenario that uses money and create the ride with scenery included
9. profit

**Dump file**

[Silvera .TD6 and multiplayer map save file.zip](https://github.com/OpenRCT2/OpenRCT2/files/2368573/Silvera.TD6.and.multiplayer.map.save.file.zip)

**Screenshots / Video:**
![silvera](https://user-images.githubusercontent.com/38723042/45327432-1bce8b00-b51d-11e8-94ba-2ab75301c535.png)

**Comment by James103** [comment]
Probable cause: The road footpath pieces are not supposed to be built in normal gameplay, so they have an undefined/invalid cost value.
Solution: If scenery is saved in a track design that is not supposed to be built in normal gameplay, then a warning should be generated and the offending pieces of scenery (the road footpath pieces) are not built.

**Comment by Patrik356b** [comment]
I don't see why it would have a cost included for footpath when this can be looked up by checking height of land & height of path plus the slope conditions

**Comment by Gymnasiast** [comment]
Another report came in via Reddit: https://www.reddit.com/r/rct/comments/amytkb/i_randomly_discoveredcreated_an_infinite_money/

> I was playing OpenRCT2 the other day and I built a go karts track that I had designed in another park. I mirrored it so that I could more easily build the path, and when I placed it, I got over $214 m. Crazy! It brought my amount of money to the same number every time I built it, **and it reduced my company value by the same number**

The second bit is also interesting, but most likely another issue.

**Comment by James103** [comment]
This bug also occurs if the track design attached is built with the front facing southwest (i.e. rotated 90 deg clockwise) and mirrored, causing your money to be set to $214,748,364.70 (2^31-1 dimes).
Track design: https://drive.google.com/file/d/1z3rriHZDjUj4E_6rUO47iQDZe0BtRoZX/view
Video: https://www.youtube.com/watch?v=xm0hzkB7Zjc
Reddit post: https://www.reddit.com/r/rct/comments/amytkb/i_randomly_discoveredcreated_an_infinite_money/

**Comment by duncanspumpkin** [comment]
This happens when a footpath element fails to be placed whilst using the track place tool. When it fails the money is increased by 0x80000000 (which is our magic bad command value).
