### ISSUE TITLE
Remove floating objects

### ISSUE THREAD

**Issue by Richard-L** [OpenRCT2/OpenRCT2#7990]
Would it be possible to add a console command that removes any floating object?

- Ducks
- Balloons
- Waving price tags of things people pay for

Thanks

**Comment by Gymnasiast** [comment]
Ah, I see you followed my instructions.

It should be easy once the plug-in support is here. Personally, I wouldn't mind having a built-in console command for it either.

**Comment by Richard-L** [comment]
I agree, a console command seems appropriate.

**Comment by Umdlye** [comment]
Implemented by #10863
