### ISSUE TITLE
Deleting scenery and footpaths on Construction Rights tiles

### ISSUE THREAD

**Issue by Supradyke** [OpenRCT2/OpenRCT2#7991]
**OS:** Windows 7 
**Version:** 0.2.1-66
**Commit/Build:** a5ad9a3

I found what I assume is an unintended method of deleting footpaths and scenery on tiles with Construction Rights, which normally shouldn't allow such a thing, considering the purpose of construction rights is to not have the right to remove whats on it and only construct _over_ it.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open park with Construction Rights (Great Adventure, for this example)
2. Open "Clear Scenery" with Footpaths selected
3. Click an area with nothing on it, and slowly drag into the footpaths and other assorted items that you normally shouldn't have access to deleting (going too fast will give the "Can't delete; Land not owned" message like it properly should)   

**Screenshots / Video:** 
![ga](https://user-images.githubusercontent.com/38723042/45531630-3e2f0580-b7b6-11e8-8532-e71edabcbac4.png) 

_no cheats were activated for this_
![ga2](https://user-images.githubusercontent.com/38723042/45532303-302eb400-b7b9-11e8-93d7-3678746a0cb9.png)

 
_"With this character's death, the thread of prophecy is severed. Restore a saved game to restore the weave of fate, or persist in the doomed world you have created."_
![dg](https://user-images.githubusercontent.com/38723042/45532614-4c7f2080-b7ba-11e8-98e6-dc76575c471b.png)

**Comment by duncanspumpkin** [comment]
Does this still happen?

**Comment by autofire372** [comment]
Just tested; it doesn't happen anymore.
