### ISSUE TITLE
Game crashes after Network Desync

### ISSUE THREAD

**Issue by Cloud-Striker** [OpenRCT2/OpenRCT2#7996]
Details:
- OS: Win 7 Professional 64 bit
- Version: 0.2.1-77 develop
- Commit/Build: 47eea29
- Does this issue appear in RCT2?: no
- Is this issue specific to multiplayer?: yes

Game keeps crashing just after a Network Desync

Steps to reproduce:
1. Join server
2. Network Desync Detected
3. Game crashes

[dump.zip](https://github.com/OpenRCT2/OpenRCT2/files/2385779/dump.zip)

**Comment by ZehMatt** [comment]
Can not reproduce this issue, please let us know if this still happening.

**Comment by Cloud-Striker** [comment]
Given that this thread is two years old, I fully expect it not to. Thread can be closed.
________________________________
Von: ζeh Matt <notifications@github.com>
Gesendet: Montag, 28. September 2020 04:08
An: OpenRCT2/OpenRCT2 <OpenRCT2@noreply.github.com>
Cc: Cloud-Striker <discord94@outlook.com>; Author <author@noreply.github.com>
Betreff: Re: [OpenRCT2/OpenRCT2] Game crashes after Network Desync (#7996)


Can not reproduce this issue, please let us know if this still happening.
