### ISSUE TITLE
Track design preview window shows nothing

### ISSUE THREAD

**Issue by with-a-k** [OpenRCT2/OpenRCT2#8007]
**OS:** Windows 10 (x86)
**Version:** 0.2.1-117 (c1d2201 on develop) provided by AppVeyor
**Commit/Build:** c1d2201

When building a tracked ride, viewing a pre-saved track design does not show a preview of the track and scenery in the ride construction window.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Start a new game anywhere
2. Open ride construction window for any tracked ride

**Screenshots / Video:**
![A fresh game on Fort Anachronism. An imported track design is selected, but even the ones that come with RCT2 are affected.](https://user-images.githubusercontent.com/6319591/45714339-89e30580-bb4e-11e8-88a5-acd2ae8fc6bb.png)

**Comment by janisozaur** [comment]
Regression from https://github.com/OpenRCT2/OpenRCT2/pull/7992

**Comment by Gymnasiast** [comment]
Possibly this bit: https://github.com/OpenRCT2/OpenRCT2/pull/7992/files#diff-eb2c8ea8b585bd3ae712f6ed156062cfR2329

I'll check when I get home.

**Comment by deurklink** [comment]
Also, for every ride that was saved with scenery it will say the scenery is not available, even if it is.
