### ISSUE TITLE
Game files are not found when put into the OpenRCT2 folder

### ISSUE THREAD

**Issue by Hornwitser** [OpenRCT2/OpenRCT2#8015]
**OS:** Windows 7
**Version:** 0.2.1

The readme notes that game files will be searched for in the loacation of openrct2.exe.  This is implemented in `Config::FindRCT2Path` by looking in `gExePath`, but after dcb92a466dbc1684d2dc6d827b894fa83d2d693b `gExePath` is no longer initialized.

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Copy RTC2 game files to the folder where openrct2.exe is located.
2. Observe that openrct2.exe does not find the game files.

Another thing to note is that the RCT2 game files have a folder name `Data`, while OpenRCT2 has a folder named `data`.  It looks like on Linux this becomes two separate folders, while on Windows which uses a case insensitive filesystem it's one folder.  Not sure what to make of that, it trips my OCD.

**Comment by Hornwitser** [comment]
If you do not support this, you should remove the [line in the readme.txt that says you do](https://github.com/OpenRCT2/OpenRCT2/blob/d0e318a2a2323734104dd45750a98607a368f46b/distribution/readme.txt#L100) as well as the [currently broken code that implements it](https://github.com/OpenRCT2/OpenRCT2/blob/d0e318a2a2323734104dd45750a98607a368f46b/src/openrct2/config/Config.cpp#L639-L642).  Note: might be worth looking at #1305 where this was proposed and implemented.

**Comment by IntelOrca** [comment]
As far as I know this still works.
See `Platform::GetInstallPath` called here:
`https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/PlatformEnvironment.cpp#L127`

`Platform::GetInstallPath` returns running executable directory unless overridden by `--openrct-data-path`.

`gExePath` is old dead code that needs deleting.

**Comment by Hornwitser** [comment]
It doesn't work, because I tried it.  _And it didn't work_.  If you think the steps I did is incorrect I encourage you to specify why they are so.  I followed the instructions in the [readme.txt](https://github.com/OpenRCT2/OpenRCT2/blob/d0e318a2a2323734104dd45750a98607a368f46b/distribution/readme.txt) provided with the game, which say and I quote:

> When you start OpenRCT2 for the first time, it will look for the RCT2 data files
in the following locations:
> - [... snip lots of install locations ...]
> - The location of the openrct2.exe (where OpenRCT2 was extracted/installed)

I see nowhere in this readme where it says putting the files there are discouraged.

Looking through the code I found `Config::FindRCT2Path`, a function that looks through the paths mentioned in the readme.txt, and then it does

```cpp
if (platform_original_game_data_exists(gExePath))
{
    return gExePath;
}
```

Which I'm pretty sure is the code that implements the searching the location of the openrct2.exe.

Also, I think you're getting confused here.  Because when I installed RCT2 to `C:\Program Files (x86)\Infogrames Interactive\RollerCoaster Tycoon 2` and launched OpenRCT2 for the first time, it found the RCT2 game files auto magically.  No "RCT2 files must always be specified using command line or config."  necessary.

**Comment by IntelOrca** [comment]
It may have looked in the same location as OpenRCT2 before but has since been removed as we discourage it. The readme is out of date unfortunately.

We however always try to look in common install locations to auto find RCT2. If found then it is saved in config so technically it is still specified by config.

**Comment by Gymnasiast** [comment]
I have the RCT2 files in the OpenRCT2 folder since the dawn of time, and it still works for me.
