### ISSUE TITLE
Game keeps running in the background

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#8021]
**OS:** Windows 10
**Version:** 0.2.1-133
**Commit/Build:** 346a9ec

After having played in multiplayer, either as host or as client, closing the game will close the window, but the process will continue to exist. The client stays connected to the server and the ports to stay in use, making the player keep receiging packets and unable to host a new server.
The game appears to be stuck on a network thread.

Right now the only solution is to close the game through task manager.

This may be related to the crash in #7881.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**
1. Go online either by hosting or joining a server
2. Close the game

**Comment by AaronVanGeffen** [comment]
Sounds like the kind of problem #7952 aimed to tackle...?

**Comment by mozar99** [comment]
still experiencing this issue. 
This is a frustrating issue in multiplayer as Openrct cannot be updated while the game is unknowingly running in the background. People think the launcher is keeping their game up to date but cannot join recently updated servers as they are stuck running on an old version. Mass confusion.

**Comment by Patrik356b** [comment]
Imo the updater should prompt the user to restart the computer before attempting to update if there are multiple instances of OpenRCT2 running

**Comment by Gymnasiast** [comment]
@Patrik356b If you're talking about the launcher: that's not part of the project (and certainly not part of this repo).

**Comment by Broxzier** [comment]
I'm positive that #8464 has fixed this.

**Comment by Gymnasiast** [comment]
Do we have any idea whether this issue was present in the last release or only in develop?
