### ISSUE TITLE
Custom Rides Filtered by Default

### ISSUE THREAD

**Issue by natek11** [OpenRCT2/OpenRCT2#8024]
**OS:** Windows 7
**Version:** newest

On the object selection screen, the default option is to hide custom objects, which is not very user-friendly and creates confusion.

- [no] Reproducible in RCT2 (vanilla)?
- [no] Specific to multiplayer?

**Steps to reproduce:**
1. have custom objects
2. load object selection screen
3. unless changed already by user, the default is that Hide Custom Objects is checked

**Comment by Gymnasiast** [comment]
I have finally tested it and I cannot reproduce it when clearing my config. It could that you (and the other user reporting this) had their config created before more categories were added.
