### ISSUE TITLE
Game crashes soon after opening park (online)

### ISSUE THREAD

**Issue by Fraser-Watson** [OpenRCT2/OpenRCT2#8025]
**OS:** Windows 10
**Version:**  0.2.1
**Commit/Build:** 40c683e

Game crashes soon after joining server

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open a park or join an online game. Preferably one of decent size, seems to happen faster if there's more guests.
2. Play for a bit, move view around the map, zoom out, etc.
3. Witness crash

**Dump file**
[Dump.zip](https://github.com/OpenRCT2/OpenRCT2/files/2420186/Dump.zip)

**Save game:**
[My Land.zip](https://github.com/OpenRCT2/OpenRCT2/files/2420194/My.Land.zip)

**Comment by myn0k** [comment]
Crash occurred for me opening an MP map I saved in SP. Possibly related?

[722f9f62-ca3d-4de5-a0ef-afdbd0329c05(40c683e_x86-64).txt](https://github.com/OpenRCT2/OpenRCT2/files/2420282/722f9f62-ca3d-4de5-a0ef-afdbd0329c05.40c683e_x86-64.txt)

**Comment by Broxzier** [comment]
`0xC0000005` access violation. The crash seems to happen in `vehicle_next_tower_element_is_top` when attempting to access an element as a track, but `.AsTrack()` (most likely) returned a nullptr.

**Comment by Fraser-Watson** [comment]
Is this something I could possibly fix myself? I tried it on another computer and it didn't seem to crash (not sure if I just didn't play for long enough though). 

It was fine last night. Only just started having issues this morning.

**Comment by Gymnasiast** [comment]
I have been able to trace one crash to hovering a ride banner.

**Comment by Gymnasiast** [comment]
@Broxzier Thanks! That indeed crashes in the same place and is solved by my fix.

**Comment by Gymnasiast** [comment]
I have pushed fixes for both crashes, so I'll close this issue. Keep an eye on your Launchers.
