### ISSUE TITLE
Ride entrance sign click causes game crash

### ISSUE THREAD

**Issue by Fraser-Watson** [OpenRCT2/OpenRCT2#8028]
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** 9ff79e6

Clicking on any ride entrance sign will result in a game crash

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open any game
2. Click on ride entrance sign

**Dump file**
[Dump.zip](https://github.com/OpenRCT2/OpenRCT2/files/2423849/Dump.zip)

**Comment by Gymnasiast** [comment]
Do you mean the entrance building or the queue banner?

**Comment by Fraser-Watson** [comment]
Sorry, the banner. The hover now does not result in a crash, but when clicking the banner, I get a crash.
