### ISSUE TITLE
Game crashes when painting rides

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#8030]
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** 149ad18

When I paint individual track pieces of a ride the game crashes shortly after. it doesn't crash immediately, but it has crashes within a minute of me starting painting 3 times. This happened in three different save files so it's not specific to a single save.

**Steps to reproduce:**
1.  Paint a ride with the alternative color scheme
2.  Wait for a crash

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/25930360/46201256-dcbd7980-c313-11e8-986c-610351701db9.png)

**Comment by tombomp** [comment]
Have you got a save file which crashes for you? i've tried reproducing this in 0.2.1 and can't get it to happen.

**Comment by LordMarcel** [comment]
[save.zip](https://github.com/OpenRCT2/OpenRCT2/files/2429166/save.zip)
It's happened to me in these three saves.

**Comment by LordMarcel** [comment]
It seems to be track-specific. I have tested a couple of different track types and I don't get a crash with the wooden and giga track types but I do get a crash with the junior, compact inverted, corkscrew, monorail, and twister track type.

**Comment by tombomp** [comment]
My apologies, I opened a new issue #8047 because I skimmed your report quickly and thought yours was happening on 0.2.1 but I see now it was happening on a recent build. Do you think this is what's happening? (clicking on entrance with the paint tool making it crash)

**Comment by Gymnasiast** [comment]
Can’t reproduce as of https://github.com/OpenRCT2/OpenRCT2/commit/c0eade9c88ec95882a20bf1959b5c8d69248371b , assuming it is fixed.
