### ISSUE TITLE
Add pre commit hook to autoformat sources

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#8038]
It's a bit tedious to run `clang-format -i` on every file you edit. It's also easy to overlook, causing lots of commits just to fix formatting. This is all stuff that could be handled by a pre commit hook, saving everyone (or at least mortals who don't always do perfect formatting) time and frustration.

Since not everybody has `clang-format` installed, it should do a check for it first.

**Comment by AaronVanGeffen** [comment]
Hooks are local to your git repository, though — they don't carry over when you push/fetch/clone.

**Comment by IntelOrca** [comment]
Yeah, that would certainly work.

**Comment by AaronVanGeffen** [comment]
Sounds like `git clang-format` is what you're looking for. Built-in, too.

**Comment by Gymnasiast** [comment]
Considering both Aaron's comments, I'm closing this. (`git clang-format` has worked quite nicely for me.)
