### ISSUE TITLE
Launched Freefall downward launch not working correctly underground.

### ISSUE THREAD

**Issue by Baini92** [OpenRCT2/OpenRCT2#8039]
**OS:** Windows 10
**Version:** v0.2.1-181
**Commit/Build:** 1e381bd

The Launched Freefall is not launching as intended when put underground with the downwards launch function. It will just launch at equal to roughly 49 km/h of the upwards launch. If put above ground it will launch as normal.

**Steps to reproduce:**
1. Construct Launched Freefall underground.
2. Set operating mode to "Downward launch"
3. Test/open the ride.

**Comment by Gymnasiast** [comment]
I think this has been solved. Could you test if it is? And if it isn't, could you upload a save that shows this behaviour?

**Comment by Baini92** [comment]
It has been solved in the newest development build yes.
