### ISSUE TITLE
Crash when using the paint tool and you click an entrance/exit

### ISSUE THREAD

**Issue by tombomp** [OpenRCT2/OpenRCT2#8047]
**OS:** Windows 10
**Commit/Build:** 0231fd7

If you have the ride paint tool active and you click an entrance/exit, you get a crash. Track.cpp Line 2286 "this was nullptr" in TrackElement::GetRideIndex(), called from line 4276 in Ride.cpp 
`if (tileElement->AsTrack()->GetRideIndex() != w->number)`

The line was last touched by commit a3e9c63fc3474831aa58402871910ab4d73aa954 

- [no] Reproducible in RCT2 (vanilla)?
- [no] Specific to multiplayer?

**Steps to reproduce:**
1. On any tracked ride, click the paint tool
2. Click on an entrance or exit
3. Crash

**Comment by Gymnasiast** [comment]
Can I just say that I appreciate the research you already did for this bug? 👍
