### ISSUE TITLE
Build fails on visual studio 2017 15.8.x

### ISSUE THREAD

**Issue by jamalf** [OpenRCT2/OpenRCT2#8052]
**OS:** Windows 10
**Commit/Build:** dc18edcd3 (dc18edcd3720a41b0cab08b45158242745a346fd)

The currently included google test library does not compile on recent versions of vs2017. See discussion on the issue here:
https://github.com/google/googletest/issues/1616

This issue was fixed in google test here https://github.com/google/googletest/commit/f66ab00704cd47e4e63ef6d425ca14b9192aaebb

**Steps to reproduce:**
1. Install the latest version of visual studio 2017. (Encountered on v 15.8.6)
2. Open a developer console and attempt to compile the solution as described in the readme.

**Comment by Gymnasiast** [comment]
Summoning @IntelOrca

**Comment by IntelOrca** [comment]
Was this from a clean repository, did it download a fresh version of gtest?

**Comment by jamalf** [comment]
> Was this from a clean repository, did it download a fresh version of gtest?
> 
> I suggest running `msbuild openrct2.proj /t:downloadlibs` and trying again.

I must have messed something up, though i'm not sure what - it was a clean repository. I've since re-cloned it and it builds correctly. Sorry for the misleading issue!
