### ISSUE TITLE
Game falsly detects desync

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#8055]
**Version:** 0.2.1
**Commit/Build:** 0231fd7

Usually shortly after joining a server, the game detects a desync. After staying connected for a couple of minutes, popping balloons still works. It would be way too coincidental that the sprite ID on the server matches the ones in my local game exactly.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**

0. Enable the option to stay connected after desyncing
1. (Host and then) join a multiplayer server
2. Wait for the desync to happen (usually only takes a few seconds on my end)
3. Wait for a couple of minutes
4. Perform any game action that works with Sprite IDs, and notice how it works perfectly fine even for sprites that spawned minutes after the desync was detected.

**Comment by Broxzier** [comment]
Unfortunately, it still happened on 46ae093.

**Comment by AaronVanGeffen** [comment]
https://github.com/OpenRCT2/OpenRCT2/pull/8803 hasn't been merged yet. As I understand it, it should be fixed when it is?

**Comment by duncanspumpkin** [comment]
#8803 is just an additional test for the ci's the fix was already merged.

**Comment by ZehMatt** [comment]
The park loaded might play a role in this. I used to get desyncs quite consistently doing this:
"openrt2 host parks/electric-fields.sv6"
"openrct2 join 127.0.0.1"

Which seems to be fixed with the export/import changes.

**Comment by Broxzier** [comment]
After a bunch of testing and trying things out with @ZehMatt we found out that this has to do with **autosaves**. When hosting a self-made save (possible requiring objects to be exported) there is no desync, but when hosting from an autosave it does desync immediately.
