### ISSUE TITLE
Game detected as "virus" by Microsoft Security Essentials.

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#8061]
**OS:** Windows 7
**Version:** All recent versions

Ever since last month, every attempt at downloading and booting up OpenRCT2 has led to Microsoft Security Essentials popping up, stopping the program, and removing the EXE.

Apparently it's detecting a trojan called "Fuery.b!cl" in the files.

**Comment by janisozaur** [comment]
This is not issue tracker of Microsoft Security Essentials. We don't ship Fuery.b!cl, all our MSVC builds are done using AppVeyor in pristine VMs and you can track the whole process or you can build everything from source yourself if you still don't trust or process.

**Comment by Superjustinbros** [comment]
So what can I do then to bypass these and get OpenRCT2 to actually download on my system, if this is the place to ask?

**Comment by janisozaur** [comment]
If your point is to bypass Microsoft Security Essentials, why are you using it in the first place?

I don't know how to answer your question.

**Comment by Broxzier** [comment]
For as long as MSE detects OpenRCT2 as a virus, you have to either white-list the websites it's downloading from (if possible) or temporarily disable it completely, and add the OpenRCT2 folder as an exception.
