### ISSUE TITLE
Construction error about local authority not allowing construction that high is shown as (undefined string) every other height

### ISSUE THREAD

**Issue by tombomp** [OpenRCT2/OpenRCT2#8064]
**OS:** Windows 10]
**Version:** 0.2.1 and latest develop
**Commit/Build:** f468bef6cce7b55e0b5104f7260da8bb07675913

"local authority won't allow construction above tree height" errors get displayed as (undefined string) - `STR_CONSTRUCTION_ERR_UNKNOWN` in code - every other height step (when you're holding shift). so eg in the attached park you click to build a swinging inverter pirate ship, you get (undefined string), hold shift and move it 1 up, you get the proper error, move it 1 higher again and you get the (undefined string) again. 

I did try to investigate but I find the error code stuff a little baffling. All I can say is the error is set on line 1093 of Track.cpp. 

Related to #7439 and #8014 

- [no] Reproducible in RCT2 (vanilla)?
- [no] Specific to multiplayer?

**Steps to reproduce:**
1. Open attached save
2. Try and build an inverted pirate ship

**Save game:**
[Raceway Park.zip](https://github.com/OpenRCT2/OpenRCT2/files/2457788/Raceway.Park.zip)

**Comment by Patrik356b** [comment]
Does this affect any other rides?

**Comment by tombomp** [comment]
> Does this affect any other rides?

Sorry I wrote this in a confusing way - it affects every ride as far as I know

**Comment by Gymnasiast** [comment]
Since the fix caused other bugs, I have reverted them.
