### ISSUE TITLE
Conflicting declaration of 'char* strndup' with 'C' linkage

### ISSUE THREAD

**Issue by PureTryOut** [OpenRCT2/OpenRCT2#8065]
**OS:** Alpine Linux (Edge)
**Version:** 0.2.1
**Commit/Build:** 8ac731e2124ecfb43f592c7f1cc5dd6902d5d83f

Probably important to note, this system uses musl rather than glibc. Trying to build OpenRCT2 for it fails at the very start:

```
[  0%] Building CXX object CMakeFiles/libopenrct2.dir/src/openrct2/Cheats.cpp.o
In file included from /usr/include/fortify/wchar.h:24,
                 from /usr/include/c++/8.2.0/cwchar:44,
                 from /usr/include/c++/8.2.0/bits/postypes.h:40,
                 from /usr/include/c++/8.2.0/iosfwd:40,
                 from /usr/include/c++/8.2.0/memory:72,
                 from /home/pmos/build/src/OpenRCT2-0.2.1/src/openrct2/GameState.h:14,
                 from /home/pmos/build/src/OpenRCT2-0.2.1/src/openrct2/Cheats.cpp:12:
/usr/include/string.h:69:7: error: conflicting declaration of 'char* strndup(const char*, size_t)' with 'C' linkage
 char *strndup (const char *, size_t);
       ^~~~~~~
In file included from /home/pmos/build/src/OpenRCT2-0.2.1/src/openrct2/Cheats.h:13,
                 from /home/pmos/build/src/OpenRCT2-0.2.1/src/openrct2/Cheats.cpp:10:
/home/pmos/build/src/OpenRCT2-0.2.1/src/openrct2/common.h:85:7: note: previous declaration with 'C++' linkage
 char* strndup(const char* src, size_t size);
       ^~~~~~~
make[2]: *** [CMakeFiles/libopenrct2.dir/build.make:63: CMakeFiles/libopenrct2.dir/src/openrct2/Cheats.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/libopenrct2.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Install Alpine Linux (for example in a VM)
2. Install the required dependencies: `apk add cmake jansson-dev libzip-dev libpng-dev curl-dev fontconfig-dev icu-dev sdl2-dev speexdsp-dev mesa-dev`
3. Try to build the program

**Comment by AaronVanGeffen** [comment]
Sounds like this ifdef needs adjusting:

https://github.com/OpenRCT2/OpenRCT2/blob/1334b745dc870d1e7f3a902ba540e84159e02ba9/src/openrct2/platform/Shared.cpp#L46-L49

Feel free to submit a PR to make your setup work as well.

**Comment by janisozaur** [comment]
And https://github.com/OpenRCT2/OpenRCT2/blob/1334b745dc870d1e7f3a902ba540e84159e02ba9/src/openrct2/common.h#L82-L86

**Comment by PureTryOut** [comment]
C++ itself is not a problem, usages of glibc specific stuff is.

I don't really know how to fix this myself... I guess adding `undefined(__GLIBC__)` would do?
