### ISSUE TITLE
Game crashes when a train spawns on the cable lift on a giga coaster in block mode

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#8068]
This happens in both vanilla and openrct2.

**Steps to reproduce:**
1. Build a coaster like this with the blue station being station 1
![image](https://user-images.githubusercontent.com/25930360/46684997-b55c8b80-cbf4-11e8-847a-04c1065ceb72.png)
2. Set the ride to block sectioned mode with 2 trains
3. Test the ride

**Comment by duncanspumpkin** [comment]
I'm pretty sure this is a duplicate.

**Comment by duncanspumpkin** [comment]
How is this different to #1122?

**Comment by LordMarcel** [comment]
Oops, I forgot to check if it was already reported, apologies for that.
