### ISSUE TITLE
Small grammar issue in guest thought string

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#8074]
**OS:** Windows 8
**Version:** 0.2.1
**Commit/Build:** 5a3efe9

Very small issue -- I could even fix it myself if I knew how to make new merges...

But right now the string reads "`<ride name> is really good value`" when it should be "`<ride name> is a really good value`". That's all. Just needs the 'a' added in.

**Steps to reproduce:**
1. price a ride cheap
2. check guest thoughts about it

![bumbly beach 2018-10-09 19-42-48](https://user-images.githubusercontent.com/26573303/46712565-8f3fe700-cc06-11e8-9dce-4d62bc7141af.png)

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/7660dc804277f849a2867cee0917b1db550f2a5f/data/language/en-GB.txt#L873

You can use GitHub web UI to make changes

**Comment by ocalhoun6** [comment]
should be fixed in #8075
