### ISSUE TITLE
The mini roller coaster has access to the spiral chain lifts from the spiral coaster

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#8083]
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** d5be45e

The spiral chain lift should be exclusive to the spiral coaster.

**Comment by Gymnasiast** [comment]
Context: this has been reported at my request.

**Comment by duncanspumpkin** [comment]
What was the reasoning for this change or was it just a bug from implementation?

**Comment by ocalhoun6** [comment]
- the mini roller coaster can use chain lifts on normal inclined turns anyway

- the mini roller coaster cars don't quite have the right sprites for the spiral chain lift (if you watch one using it, you'll see the angle of the cars doesn't quite match the angle of the track)

- it doesn't have the spiral lift hill in any other version of RCT

- if you really want to use the spiral lift hill anyway, you can still do it by using arbitrary ride type changes and/or track merging

**Comment by Gymnasiast** [comment]
@duncanspumpkin An implementation bug. In vanilla, they are not available on the Mini RC.
