### ISSUE TITLE
End quotes in STR_2901

### ISSUE THREAD

**Issue by J0anJosep** [OpenRCT2/OpenRCT2#8085]
STR_2901 is:
`STR_2901    :{WINDOW_COLOUR_2}(Samples courtesy of Spectrasonics {ENDQUOTES}Liquid Grooves{ENDQUOTES}) 
`
Is the use of ENDQUOTES instead of OPENQUOTES intentional? Why?

**Comment by J0anJosep** [comment]
Thanks for the rapid fix.
I think it also appears in translations as ”Liquid Grooves”.

**Comment by Gymnasiast** [comment]
I have opened an issue in Localisation to address those.
