### ISSUE TITLE
Bug with my saved maze design

### ISSUE THREAD

**Issue by Nerevar98** [OpenRCT2/OpenRCT2#8090]
**OS:** Windows 7
**Version:** 0.2.1
**Commit/Build:** 04ce2b9

I saved my recent maze design and when I wen't to check it out, there are a few things that are odd:

There's no ride preview, though saving other custom ride designs seems to provide a preview.

Placing it is wonky, the thing is invisible and crashes my game when I try to interact with it in a few ways.

Trying to demolish it says that it'll give me -$214,748,365 back.

Not sure what's going on, like I said, other rides I save seem to be behaving normally, just the maze is acting this way.

**Comment by tombomp** [comment]
Can you upload the saved design? You'll find it in Documents\OpenRCT2\track with the name you saved it as. Zip it (right click->send to compressed folder) and drag and drop it on the comment form.

**Comment by Nerevar98** [comment]
[The Maze.zip](https://github.com/OpenRCT2/OpenRCT2/files/2476907/The.Maze.zip)

Yeah, here it is. It seems to happen anytime I save a maze design. No issues saving ride designs of other rides though. Thanks!

**Comment by tombomp** [comment]
Thanks for the report, looks like a simple typo in the map design saving code: line 947 in TrackDesignSave.cpp should be `location = ride_get_exit_location(rideIndex, 0);` - right now it says `ride_get_entrance_location` when the entrance had already been saved just above. Just checked it and the saving and loading of a maze design works fine with that fix.

**Comment by Nerevar98** [comment]
Thanks for the fix! So I've never looked into the code of OpenRCT2 before, would you mind telling me where I would find the TrackDesignSave.cpp to fix that on my end, or pointing me towards a guide? I can't find any .cpp files in the installation. Thanks!

**Comment by tombomp** [comment]
Sorry that was an unhelpful response on my part! If you wait a day or so the fix should appear in the development builds that you can download on https://openrct2.org/downloads

**Comment by Nerevar98** [comment]
Oh great thank you so much! I ended up finding the source code anyway so I'm looking through it and found what you were talking about, not sure how to create a build of it to actually use, but I fixed it haha interesting stuff, anyway thanks again!
