### ISSUE TITLE
Crash help

### ISSUE THREAD

**Issue by Jacx85** [OpenRCT2/OpenRCT2#8092]
**OS:** [Windows 10]
**Version:** [.2.1-24
**Commit/Build:** [18307e3]

Im not sure what the issues was, i was letting the game run and it created this error.

[RCT Error.zip](https://github.com/OpenRCT2/OpenRCT2/files/2476878/RCT.Error.zip)

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by Gymnasiast** [comment]
Could you fill in the build hash?

**Comment by Jacx85** [comment]
im not sure how to do that

**Comment by Jacx85** [comment]
> Could you fill in the build hash?

i figured it out

**Comment by Gymnasiast** [comment]
I'm not 100% sure we should close this - it does contain a dump.
