### ISSUE TITLE
Probably incorrect title of Create new title sequence dialogue

### ISSUE THREAD

**Issue by alex-0xFF** [OpenRCT2/OpenRCT2#8102]
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** 6992be8

While entering name of new title sequence, dialogue title says "Duplicate".

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1.  Start the game
2. Go to Options
3. Press Edit Title Sequence... button
4. Press Create button

**Screenshots / Video:**
![2018-10-16 23_35_34-openrct2](https://user-images.githubusercontent.com/9460684/47045918-aa799c00-d19c-11e8-9243-6d9129fe6730.jpg)

**Comment by tombomp** [comment]
Line 297 of TileEditor.cpp - even has the comment `// TODO: This should probably be 'NEW'`
