### ISSUE TITLE
Support discord release of RCT2

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8107]
RCT2 Triple Thrill Pack has recently been made available on the Discord store for anyone with a Nitro subscription.

https://discordapp.com/store/skus/489157993385033788/rollercoaster-tycoon-2-triple-thrill-pack

On Windows the game is by default installed to:
`%LOCALAPPDATA%\DiscordGames\RollerCoaster Tycoon 2 Triple Thrill Pack\content\Game`

Full file listing: https://pastebin.com/raw/Knk0g24M

Investigation is still needed as to whether the game can be installed on non-Windows platforms.

**Comment by Krutonium** [comment]
Based on the file list, this release is identical to the Steam release of the game, which is itself a copy of a Disc based release.
