### ISSUE TITLE
Three different folder names are used for title sequences

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#8110]
This is something that stood me out when writing a tutorial about the user folder. The precreated folder in the user's directory is named `sequence`. The default ones are in `title`, and `GetUserSequencesPath()` uses `title sequences`.

This makes no sense. It should use one folder name. I propose using `sequence`.

**Comment by IntelOrca** [comment]
If `GetUserSequencesPath()` returns `title sequences` why is a folder called `sequence` precreated?

**Comment by IntelOrca** [comment]
Probably due to C and C++ cross.

**Comment by Gymnasiast** [comment]
I don't know, both functions follow C++ naming convention.

Anyway, the reason I wanted to opt for `sequence` is because of three reasons:
- It's precreated already, making it easier for the users
- Its naming is consistent with the rest, unlike `title sequences`.
- It's easier to understand than `title`.

**Comment by bdupree5** [comment]
Hey guys i'm trying to work on this issue, what exactly is the problem? In the function GetUserSequencesPath() needs to call on the table? Or needs to return "sequence" instead of "title sequence"? I'm just a bit confused.

**Comment by IntelOrca** [comment]
@bdupree5 I think for now just replace all variations with `sequence`.

**Comment by bdupree5** [comment]
I will get on it thanks.
