### ISSUE TITLE
Make early scenario completion a cheat?

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#8112]
This issue is a discussion issue.
Recently #7187 was merged, which adds an option which allows you to win a scenario early by ignoring the time requirement. I don't like this.

I suggest this feature should be turned into a cheat because it directly affects the scenario goal by making it easier to win and it messes with the gameplay.

## Rationale

This is an *extreme* change in gameplay.

This “early scenario completion” feature would break some scenarios as it messes with the intention of the scenario designer.
Imagine there's a scenario in which you already start with a lot of guests and you are close to the guest goal. But the scenario is made in such a way that the challenge is not to reach the target guests, but to *sustain* this amount of guests as well (hence the time requirement).
Also, in RCT, getting a lot of guests quickly is easy if you pour tons of money in marketing. But *sustaining* them is usually the tricky part.

Another problem I have is that high scores are not comparable with this anymore. A playthrough in which the player played through the whole time requirement is considered to be equally “valid” as a player who went the quick path, and both get a highscore entry.

Therefore, early scenario completion should be a cheat.

**Comment by IntelOrca** [comment]
Given cheats do not currently prevent highscores from being recorded what difference does marking the early completion checkbox as a cheat make? It doesn't make it any harder to activate as cheats is also a checkbox on the options window.

**Comment by deurklink** [comment]
Personally, I don't really see it as a cheat but more as a function to make speedrunning this game viable.
