### ISSUE TITLE
OpenRCT freezes at start

### ISSUE THREAD

**Issue by Vendettaw0w** [OpenRCT2/OpenRCT2#8117]
**OS:** [e.g. Windows 7 ]
**Version:** [Both: the stable version and newest dev. Version]
**Commit/Build:** [e.g. 426e106]
_____

So...I just bought RCT 2 Triple Thrill Pack from Steam, downloaded and installed it and started it afterwards. All fine. Game runs etc.

Then i wanted to install OpenRCT and now the issues begin:

After the installation, when i want to start ORCT, the windows error sound comes up, the screen freezes, CPU-Usage freezes aswell and i have to terminate the process via the taskmanager. However the funny thing is, that the background music runs smoothly until i terminate the process. 

I tried uninstalling both, the game at steam and ORCT. I tired the develop version and the "stable" one. I also tried compability mode and launch as admin. Neither of those things worked :/ Someone in the chat asked me to launch it via command mode and with "verbose", to get some kind of logs in the command window. I also have a dumpfile here. 

I am not that familiar with issues like that. I had a cracked rct a long while ago and open rct worked with that one....also i am not that famliar with cmd menues, logs etc. so pls dont hesitate to tell me, if something is missing. i ll try to put it in here asap. 

Thanks a lot in advance!
_____

[Dumpfile.zip](https://github.com/OpenRCT2/OpenRCT2/files/2493817/Dumpfile.zip)

**Screenshots / Video:**
![orct-error](https://user-images.githubusercontent.com/44278174/47188445-55728d00-d338-11e8-87c5-410377428922.png)
![v4](https://user-images.githubusercontent.com/44278174/47188449-586d7d80-d338-11e8-9246-9f88c770fad1.png)

**Comment by IntelOrca** [comment]
The crash is `0xC000001D: Illegal Instruction`, in other words the AVX2 instructions are being executed on a CPU that doesn't support it. Investigation is required as to why it thinks the CPU supports it.

Further more, AVX2 is not explicitly disabled for 32-bit builds and should be as there is currently no work around.

**Stack trace:**
```
>	openrct2.dll!mask_avx2(width, height=0x00000003, maskSrc=0x000000000935b82d, colourSrc=0x000000000937c22d, dst=0x000000000445eebe, maskWrap=0x00000020, colourWrap=0x00000020, dstWrap=0x000003a0) Line 24	C++
 	openrct2.dll!gfx_draw_sprite_raw_masked_software(dpi=0x00000000002ef280, x=0x00000000, y=0x000070e1, maskImage, colourImage) Line 830	C++
 	[Inline Frame] openrct2.dll!gfx_draw_sprite_raw_masked(colourImage=0x00007121, ) Line 238	C++
 	openrct2.dll!paint_attached_ps(dpi=0x00000000002ef280, ps=0x000007fee2559e28, viewFlags) Line 556	C++
 	openrct2.dll!paint_draw_structs(dpi=0x00000000002ef280, ps=0x000007fee2559e28, viewFlags=0x00000400) Line 532	C++
 	openrct2.dll!viewport_paint_column(dpi=0x00000000002ef280, viewFlags=0x00000400) Line 929	C++
 	openrct2.dll!viewport_paint(viewport, dpi, left=0xfdee, top, right=0x0148, bottom=0x0860) Line 903	C++
 	openrct2.dll!viewport_render(dpi=0x00000000002ef3a0, viewport, left=0x0000013c, top=0x00000182, right=0x0000ff36, bottom=0x00000860) Line 825	C++
 	openrct2.dll!window_main_paint(w, dpi) Line 90	C++
 	[Inline Frame] openrct2.dll!window_event_paint_call() Line 1594	C++
 	openrct2.dll!window_draw_single(dpi, w=0x0000000009b89db0, left, top, right=0x00000284, bottom=0x000001e6) Line 1277	C++
 	openrct2.dll!window_draw(dpi=0x00000000002ef450, w=0x0000000009b89db0, left=0x0000013c, top=0x00000284, right=0x00000284, bottom=0x000001e6) Line 1154	C++
 	openrct2.dll!window_draw_all(dpi, left, top, right, bottom) Line 2110	C++
 	[Inline Frame] openrct2.dll!viewport_shift_pixels() Line 409	C++
 	openrct2.dll!viewport_move(x, y, w=0x0000000009b89db0, viewport=0x000007fee2334be0) Line 500	C++
 	openrct2.dll!viewport_update_position(window=0x0000000009b89db0) Line 632	C++
 	openrct2.dll!WindowManager::SetMainView(x, y, zoom, rotation=0x00000000) Line 500	C++
 	openrct2.dll!TitleSequencePlayer::PrepareParkForPlayback() Line 505	C++
 	openrct2.dll!TitleSequencePlayer::LoadParkFromStream(stream=0x0000000003071a20, hintPath={...}) Line 467	C++
 	openrct2.dll!TitleSequencePlayer::ExecuteCommand(command=0x0000000007501d40) Line 307	C++
 	openrct2.dll!TitleSequencePlayer::Update() Line 144	C++
 	[Inline Frame] openrct2.dll!OpenRCT2::TitleScreen::TryLoadSequence() Line 249	C++
 	openrct2.dll!OpenRCT2::TitleScreen::Load() Line 146	C++
 	openrct2.dll!OpenRCT2::Context::Launch() Line 758	C++
 	openrct2.dll!OpenRCT2::Context::RunOpenRCT2(argc=0x005436c8, argv=0x00000000005436d0) Line 216	C++
 	openrct2.dll!NormalisedMain(argc=0x00000002, argv=0x000000000055a070) Line 60	C++
 	openrct2.dll!LaunchOpenRCT2(argc=0x00000002, argvW=0x0000000000000009) Line 46	C++
```

**Comment by janisozaur** [comment]
You are running it on an unsupported OS version that doesn't issue the required xsave before issuing avx2 calls. Not really our problem IMO.

**Comment by janisozaur** [comment]
To be less specific:
You are running win 7 without SP1, which is not supported.

**Comment by IntelOrca** [comment]
@Vendettaw0w can you confirm what version of Windows 7 you are running and whether or not you have SP1 installed?

**Comment by Vendettaw0w** [comment]
Sry guys, didnt have a lot of time the past few days. I had to reset my PC and re-installed win7. I always had issues when i tried to update it, probably because its out of date or whatever. I just installed win10 Pro and everything works fine. So i guess the case can be closed. However thanks a lot for ur help guys <3
