### ISSUE TITLE
Server crashes when giving the park a title

### ISSUE THREAD

**Issue by cablegunmaster** [OpenRCT2/OpenRCT2#8121]
**OS:** Ubuntu 18.04
**Version:** [e.g. 0.2.1]
**Commit/Build:** 38cc469

Server loop exits , and disconnects all players.
This issue is reproduceable.

- [ No ] Reproducible in RCT2 (vanilla)?
- [ x ] Specific to multiplayer?

**Steps to reproduce:**
1.  Create a server
2.  Give the park a name.
Server crashes.

This issue seems very straight forward, where could I find a dump file ? On client side I don't get anything. Related log might just be because of clicking outside the Map? (might be a seperate issue). 

ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                                                    ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                             ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                      VERBOSE: Signature verification ok. Hash 9a4c208f63f659f2d55d19aa233b62cce6e751df
                                                                                                       VERBOSE: file '/root/.config/OpenRCT2/users.json' exists = 1
                                                                                                                                                                   VERBOSE: Server sends objects list with 13 items
                                   VERBOSE: Object autocars (checksum d343e3b4)
                                                                               VERBOSE: Object HALLPA01 (checksum e6365ee5)
                                                                                                                           VERBOSE: Object SLDBODY  (checksum c5a945e4)
                                                                                                                                                                       VERBOSE: Object RICBRIC4 (checksum 92dda045)
                                   VERBOSE: Object AE-CHAOT (checksum 8abb0351)
                                                                               VERBOSE: Object JBpcn    (checksum da5fd7b3)
                                                                                                                           VERBOSE: Object FAID-CRS (checksum 923b326c)
                                                                                                                                                                       VERBOSE: Object MetRTube (checksum 36f13695)
                                   VERBOSE: Object MSSPIN   (checksum 70bee424)
                                                                               VERBOSE: Object ROADOPJB (checksum 533b0f3c)
                                                                                                                           VERBOSE: Object RIDETESJ (checksum f35976a9)
                                                                                                                                                                       VERBOSE: Object AE-SWIM  (checksum 34b9fafa)
                                   VERBOSE: Object PATHWD   (checksum 7a2b2d1)
                                                                              VERBOSE: Client requested 0 objects
                                                                                                                 VERBOSE: Sending map of size 4764400 bytes, compressed to 190591 bytes
       ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                                                ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                         ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                  ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                                                           ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                    ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                             ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                                                                      ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                               ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                        ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                                                                                 ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                          ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                   ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                                                                                            ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                                     ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                              ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
       ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                                                ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                         ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                  ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                                                           ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                    ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                             ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                                                                      ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                               ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                        ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                                                                                 ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                          ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                   ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                                                                                            ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                                     ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                              ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
       ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                                                ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                         ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                  ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                                                           ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                    ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                             ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                                                                      ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                               ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                        ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                                                                                 ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                          VERBOSE: Signature verification ok. Hash 6e99c4a5179f1b1c28fc7e1bdf42f2497ca0bb50
           VERBOSE: Signature verification ok. Hash 6e99c4a5179f1b1c28fc7e1bdf42f2497ca0bb50
                                                                                            VERBOSE: file '/root/.config/OpenRCT2/users.json' exists = 1
                                                                                                                                                        VERBOSE: Server sends objects list with 13 items
                        VERBOSE: Object autocars (checksum d343e3b4)
                                                                    VERBOSE: Object HALLPA01 (checksum e6365ee5)
                                                                                                                VERBOSE: Object SLDBODY  (checksum c5a945e4)
                                                                                                                                                            VERBOSE: Object RICBRIC4 (checksum 92dda045)
                        VERBOSE: Object AE-CHAOT (checksum 8abb0351)
                                                                    VERBOSE: Object JBpcn    (checksum da5fd7b3)
                                                                                                                VERBOSE: Object FAID-CRS (checksum 923b326c)
                                                                                                                                                            VERBOSE: Object MetRTube (checksum 36f13695)
                        VERBOSE: Object MSSPIN   (checksum 70bee424)
                                                                    VERBOSE: Object ROADOPJB (checksum 533b0f3c)
                                                                                                                VERBOSE: Object RIDETESJ (checksum f35976a9)
                                                                                                                                                            VERBOSE: Object AE-SWIM  (checksum 34b9fafa)
                        VERBOSE: Object PATHWD   (checksum 7a2b2d1)
                                                                   VERBOSE: Client requested 0 objects
                                                                                                      VERBOSE: Sending map of size 4764400 bytes, compressed to 188307 bytes
                                                                                                                                                                            ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                                     ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                              ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
       ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                                                ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                         ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                  ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                                                           ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                    VERBOSE: Signature verification ok. Hash d2b1c8608f6bcdcd1652847d4ebd4960ee578abb
                                                                                                                                                                     ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                              ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                       ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                                                                                               VERBOSE: Signature verification ok. Hash d2b1c8608f6bcdcd1652847d4ebd4960ee578abb
                                                                                VERBOSE: file '/root/.config/OpenRCT2/users.json' exists = 1
                                                                                                                                            VERBOSE: Server sends objects list with 13 items
            VERBOSE: Object autocars (checksum d343e3b4)
                                                        VERBOSE: Object HALLPA01 (checksum e6365ee5)
                                                                                                    VERBOSE: Object SLDBODY  (checksum c5a945e4)
                                                                                                                                                VERBOSE: Object RICBRIC4 (checksum 92dda045)
            VERBOSE: Object AE-CHAOT (checksum 8abb0351)
                                                        VERBOSE: Object JBpcn    (checksum da5fd7b3)
                                                                                                    VERBOSE: Object FAID-CRS (checksum 923b326c)
                                                                                                                                                VERBOSE: Object MetRTube (checksum 36f13695)
            VERBOSE: Object MSSPIN   (checksum 70bee424)
                                                        VERBOSE: Object ROADOPJB (checksum 533b0f3c)
                                                                                                    VERBOSE: Object RIDETESJ (checksum f35976a9)
                                                                                                                                                VERBOSE: Object AE-SWIM  (checksum 34b9fafa)
            VERBOSE: Object PATHWD   (checksum 7a2b2d1)
                                                       VERBOSE: Client requested 1 objects
                                                                                          VERBOSE: Client requested object FAID-CRS
                                                                                                                                   VERBOSE: packing 1 objects
                                                                                                                                                             VERBOSE: exporting object FAID-CRS
               VERBOSE: Sending map of size 4795502 bytes, compressed to 199017 bytes
                                                                                     ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                              ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                                                                       ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                         ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                                                                                  ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                           ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                    ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                                                                                             ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                                                                                      ERROR[/opt/openrct2/src/openrct2/world/Map.cpp:220 (map_get_first_element_at)]: Trying to access element outside of range
                                                               VERBOSE: Create directory: /root/.config/OpenRCT2/save/autosave
                                                                                                                              VERBOSE: mkdir(/root)
                                                                                                                                                   VERBOSE: mkdir(/root/.config)
                                                                                                                                                                               VERBOSE: mkdir(/root/.config/OpenRCT2)
                                     VERBOSE: mkdir(/root/.config/OpenRCT2/save)
                                                                                VERBOSE: mkdir(/root/.config/OpenRCT2/save/autosave)
                                                                                                                                    VERBOSE: file '/root/.config/OpenRCT2/save/autosave/autosave_2018-10-19_14-52-42.sv6' exists = 0
                                                    VERBOSE: saving game
                                                                        VERBOSE: [sv] GameAction::Execute

                                                                                                         VERBOSE: [sv] GameAction::Execute

                                                                                                                                          VERBOSE: Signature verification ok. Hash 9a4c208f63f659f2d55d19aa233b62cce6e751df
                                           VERBOSE: file '/root/.config/OpenRCT2/users.json' exists = 1
                                                                                                       VERBOSE: Server sends objects list with 13 items
                                                                                                                                                       VERBOSE: Object autocars (checksum d343e3b4)
                   VERBOSE: Object HALLPA01 (checksum e6365ee5)
                                                               VERBOSE: Object SLDBODY  (checksum c5a945e4)
                                                                                                           VERBOSE: Object RICBRIC4 (checksum 92dda045)
                                                                                                                                                       VERBOSE: Object AE-CHAOT (checksum 8abb0351)
                   VERBOSE: Object JBpcn    (checksum da5fd7b3)
                                                               VERBOSE: Object FAID-CRS (checksum 923b326c)
                                                                                                           VERBOSE: Object MetRTube (checksum 36f13695)
                                                                                                                                                       VERBOSE: Object MSSPIN   (checksum 70bee424)
                   VERBOSE: Object ROADOPJB (checksum 533b0f3c)
                                                               VERBOSE: Object RIDETESJ (checksum f35976a9)
                                                                                                           VERBOSE: Object AE-SWIM  (checksum 34b9fafa)
                                                                                                                                                       VERBOSE: Object PATHWD   (checksum 7a2b2d1)
                  VERBOSE: Client requested 0 objects
                                                     VERBOSE: Sending map of size 4764400 bytes, compressed to 192119 bytes
                                                                                                                           VERBOSE: [sv] GameAction::Execute

                                                                                                                                                            VERBOSE: Signature verification ok. Hash 0edfd6ffefad5936f1e92ac9c4c9eb2864a80c4c
                                                             VERBOSE: Signature verification ok. Hash 0edfd6ffefad5936f1e92ac9c4c9eb2864a80c4c
                                                                                                                                              VERBOSE: file '/root/.config/OpenRCT2/users.json' exists = 1
                          VERBOSE: Server sends objects list with 13 items
                                                                          VERBOSE: Object autocars (checksum d343e3b4)
                                                                                                                      VERBOSE: Object HALLPA01 (checksum e6365ee5)
                                                                                                                                                                  VERBOSE: Object SLDBODY  (checksum c5a945e4)
                              VERBOSE: Object RICBRIC4 (checksum 92dda045)
                                                                          VERBOSE: Object AE-CHAOT (checksum 8abb0351)
                                                                                                                      VERBOSE: Object JBpcn    (checksum da5fd7b3)
                                                                                                                                                                  VERBOSE: Object FAID-CRS (checksum 923b326c)
                              VERBOSE: Object MetRTube (checksum 36f13695)
                                                                          VERBOSE: Object MSSPIN   (checksum 70bee424)
                                                                                                                      VERBOSE: Object ROADOPJB (checksum 533b0f3c)
                                                                                                                                                                  VERBOSE: Object RIDETESJ (checksum f35976a9)
                              VERBOSE: Object AE-SWIM  (checksum 34b9fafa)
                                                                          VERBOSE: Object PATHWD   (checksum 7a2b2d1)
                                                                                                                     VERBOSE: Client requested 0 objects
                                                                                                                                                        VERBOSE: Sending map of size 4764400 bytes, compressed to 192387 bytes

**Comment by cablegunmaster** [comment]
"VERBOSE: [sv] GameAction::Execute  Segmentation fault (core dumped) "
is the only output given , can't get a dump or anything. 
Is there any way to get more output from server side, so I could provide more information?

**Comment by cablegunmaster** [comment]
[_opt_openrct2_OpenRCT2_openrct2.0.crash.zip](https://github.com/OpenRCT2/OpenRCT2/files/2496846/_opt_openrct2_OpenRCT2_openrct2.0.crash.zip)

**Comment by cablegunmaster** [comment]
[core.zip](https://github.com/OpenRCT2/OpenRCT2/files/2496937/core.zip)

**Comment by ZehMatt** [comment]
Can you try the latest build and see if its still crashing?

**Comment by cablegunmaster** [comment]
New version I shall Install on the server on friday.

**Comment by cablegunmaster** [comment]
could be reopened? I tried this with Hash commit: 590196b and its still occuring.
