### ISSUE TITLE
I can't delete a scrolling sign.

### ISSUE THREAD

**Issue by cablegunmaster** [OpenRCT2/OpenRCT2#8129]
**OS:** Windows , host Ubuntu 18.04
**Version:** 0.21
**Commit/Build:** 38cc469

There is a sign in the park (probably build by someone else) And as Admin I try to delete it but I can't nothing happens. in english its called "Scrolling sign"

- [yes ] Specific to multiplayer?

**Steps to reproduce:**
1. let another player build the scrolling sign
2. let an person who has the rights delete it. (not sure if it has to be another person or not).

**Screenshots / Video:**
![scrollingsign](https://user-images.githubusercontent.com/8159246/47254219-5e11b300-d45f-11e8-9137-1aca8d5387b9.png)

**Save game:**
[autosave_2018-10-20_09-50-44.zip](https://github.com/OpenRCT2/OpenRCT2/files/2498010/autosave_2018-10-20_09-50-44.zip)

**Comment by duncanspumpkin** [comment]
@Gymnasiast is this realted to recent issue with banners?

**Comment by Gymnasiast** [comment]
Very likely. Saves made between September and yesterday are affected.

**Comment by duncanspumpkin** [comment]
I think it is therefore safe to close this then
