### ISSUE TITLE
"(undefined string)" error when attempting to build some/most track designs

### ISSUE THREAD

**Issue by RCTMASTA** [OpenRCT2/OpenRCT2#8134]
**OS:** Win10 Enterprise x64
**Version:** develop
**Commit/Build:** a8e46f5

I'm encountering an "(undefined string)" error on the (currently) latest commit that prevents me from placing many track designs--the strange thing is that it's not apparently consistent in regards to what designs are and aren't placeable. For the most part, this even effects saved track designs that were _just created_ from other rides in the save.

Every Air Powered Coaster design works, for example, but for some reason even some vanilla RCT2 designs like Microfobia fail to place, even on completely flat terrain, as the included image demonstrates.

- Reproducible in RCT2 (vanilla)? Don't know where I put the disc. But, uh, probably not.
- Specific to multiplayer? No.

**Steps to reproduce:** (note that I am unsure if this is even reproducible)
1.  Open Track Designer. Select the Wooden Roller Coaster.
2. Observe that, if this bug is in effect, some of the tracks won't have preview images, and those that don't will fail to build with the "(undefined string)" error.

**Screenshots / Video:**
![](https://i.gyazo.com/8f6ca884ee9d953d2c6abac41414d51f.png
)

Seems like it may be a similar effect to the one described in #7439 but this is probably more serious, as it is almost completely blocking the use of track designs.

**Comment by Topodic** [comment]
Having this problem as well, seems to be in regards to sloped curve pieces - I haven't tested extensively, but on both the Junior Roller Coaster and Wooden Roller Coaster, I cannot build said elements.

**Comment by RCTMASTA** [comment]
![](https://i.gyazo.com/a02bb5c31d9c772cb9eefba5bc18ec9f.png)

Can confirm. I didn't even notice this before. Yikes.

**Comment by hoodratstuff** [comment]
Inline Twists, Barrel Rolls, S-bends, and single tile special elements (photos, brakes) work. All other inversions, helices, and large sloped turns cannot be built. Any designs that incorporate these elements cannot be built.

**Comment by hoodratstuff** [comment]
#8130 seems to have fixed this issue as well.

**Comment by Gymnasiast** [comment]
Should have been fixed now the offending commit has been reverted.
