### ISSUE TITLE
Disabling clearance checks and holding shift allows building coasters in between normal heights

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#8137]
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** 45381b0

If you have disabled clearance checks, you can now accidentally (by holding shift to change the height) build your coasters at heights that are between the normal heights allowed for coasters. This can be quite annoying if you did not intend to do this (and if you practically always build with clearance checks disabled, like me)

**Comment by Gymnasiast** [comment]
this will have been caused by https://github.com/OpenRCT2/OpenRCT2/commit/45381b099753665ba98ab6908084fe0fdf95d990

I'm afraid I will have to revert it, and https://github.com/OpenRCT2/OpenRCT2/commit/a8e46f5eecf05bd6ba060561334be11a3ff58b1d too.

**Comment by Gymnasiast** [comment]
Should now have been fixed.
