### ISSUE TITLE
Buying land with “no money” cheat reduces your money

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#8139]
**OS:** GNU/Linux
**Version:** 0.2.1

- [ ] Reproducible in RCT2 (vanilla)? I don't know.
- [ ] Specific to multiplayer? No.

If you buy land in a scenario with money but with the “no money” cheat enabled, you can run out of money.
Also, the “buy land” button disappears when you enable the “no money” cheat, although there might be still land to get.

**Steps to reproduce:**

1. Play any scenario with money and buyable land (e.g. Forest Frontiers)
2. Go into buy land menu and keep it open
3. Set scenario to 'no money' using cheat menu
4. Buy a lot of land
5. Game still uses invisible money pool, and you can actually run out of money

**Screenshots / Video:**
> ![Buying land](https://user-images.githubusercontent.com/6469413/47361911-6f62f580-d6d3-11e8-8999-b0d4b20f9364.png)

**Possible solution**
The solution requires 2 steps:

1. When “buying” land in such a scenario with the “no money” cheat, do not touch the money.
2. When “no money” is activated via the cheat (rather than a scenario), do not hide the “buy land” icon in the park menu (since there still might be buyable land).

**Credits**
Reposted from https://github.com/OpenRCT2/OpenRCT2/issues/8113#issuecomment-432339174 (thanks, @deurklink!)

**Comment by joshtucker132** [comment]
My team would like to work on this issue.

**Comment by duncanspumpkin** [comment]
@joshtucker #8703 might fix this issue.

**Comment by ZehMatt** [comment]
Just tested this with #8703, it indeed fixes the issue, it will just buy the land without any issues.

**Comment by Nazey** [comment]
Someone should mark this issue as being fixed if #8703 fixes it.
