### ISSUE TITLE
Reliabiility of mazes and crooked houses can go below 100%

### ISSUE THREAD

**Issue by Wuzzy2** [OpenRCT2/OpenRCT2#8142]
**OS:** GNU/Linux
**Version:** 0.2.1

The displayed reliabiility (not the real reliability) of mazes and crooked houses can go below 100% although these attractions never break.

- [ ] Reproducible in RCT2 (vanilla)? I don't know. Maybe.
- [ ] Specific to multiplayer? No.

**Steps to reproduce:**
1. Build a maze and a crooked house
2. Open them and let guests in
3. Play for a long time

Effect: The reliability level will slowly decline (down to 0%, eventually) although these attractions never break.

Expected effect: Since these attractions can't break down, I expect the reliability to stay at 100% forever. It's as if they have an “intrinsic” 100% reliability.

Fun fact: Refurbishing is disabled for these attractions. So to bring up reliability back to 100%, you have to bulldoze the attraction and rebuild it. xD

**Comment by felixpelletier** [comment]
Working on that at the moment.
