### ISSUE TITLE
Game freezes upon demolishing mazes at odd heights

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#8151]
**Version:** 0.2.1
**Commit/Build:** 95175b4

Yet another fun maze bug, this one causes the game to freeze when demolishing a maze that has been messed around with using the tile inspector.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

Not specific to multiplayer, but it can freeze the server.

**Steps to reproduce:**
1. Build a maze (1 tile is enough)
2. Use the tile inspector to raise/lower any any part to a height it can normally not be on (half steps)
3. demolish the ride
4. The game freezes

**Comment by felixpelletier** [comment]
I think I found the culprit. PR #8183
