### ISSUE TITLE
Guests won't ride pickup trucks in the rain.

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#8154]
**OS:** Windows 8
**Version:** 0.2.1
**Commit/Build:** 5a3efe9

Isn't the pickup truck car for the car ride supposed to count as a covered ride, so guests will want to ride it in the rain? It's not working that way for me, though.

Possibly related to [this other issue someone on reddit is having with trying to get a ride to register as indoor](https://www.reddit.com/r/rct/comments/9r5lj5/guests_wont_ride_this_in_the_rain/)

**Steps to reproduce:**
1. Build car ride
2. Select pickup trucks as vehicle
3. Wait for rain
4. Observe that guests won't enter queue while it's raining.

![onamaga beach 2018-10-23 10-31-37](https://user-images.githubusercontent.com/26573303/47469950-6730b600-d7b8-11e8-8a5d-94c589823157.png)

**Comment by Gymnasiast** [comment]
You deleted the important bit from the template: whether this happens in vanilla.

**Comment by ocalhoun6** [comment]
My vanilla installation has become error-prone for some reason and usually crashes on startup.

**Comment by Gymnasiast** [comment]
A flag check reveals that TRUCK1 does not have the `hasShelter` flag set, but loads of other vehicles do.

It probably means that guests wouldn't ride it in vanilla. Which does not matter much, by the way -- it just means it's an original bug, not an OpenRCT2-specific one.

**Comment by IntelOrca** [comment]
Do the trucks have windows? Perhaps you would still get wet when inside them.

**Comment by Gymnasiast** [comment]
Well, the chairlift cars would have the same problem, but are marked as sheltered as well.

**Comment by deurklink** [comment]
I just tested it in vanilla RCT2 and guests will not ride pickup trucks in rain. 
They _will_ ride both the chairlift cars with a roof and the ski lift cars without a roof in the rain.

**Comment by Gymnasiast** [comment]
I have pushed https://github.com/OpenRCT2/objects/commit/571386fe065a03d73905ff65380d5eae7fa46ad5 to set the shelter bit on pick-up trucks, and remove it from ski-lift chairs.

**Comment by deurklink** [comment]
I will make the linked reddit post into a separate issue.

**Comment by Broxzier** [comment]
With the OP's issue being handled, can this be closed? @Gymnasiast

**Comment by Gymnasiast** [comment]
Not yet - there needs to be an object release first. We'll do one just before the 0.2.2 release - thanks for reminding me.

**Comment by Gymnasiast** [comment]
Should be fixed -- could you check @ocalhoun6 ?

**Comment by ocalhoun6** [comment]
Yes, seems to work properly now. Just tested it and they'd ride pickup trucks in the rain, but not racing cars in the rain.
