### ISSUE TITLE
BACKTRACE 930133 window_close

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8164]
Happened on 3e45743

<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/930133464d4e457b38715153e74d9b9e2d55ab73818bd62f134c81597506b7cc?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Sat Oct 27 2018 00:02:50)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>window_close -> window_text_input_mouseup -> input_state_widget_pressed -> game_handle_input_mouse -> game_handle_input -> context_handle_input -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment]
Weird, I had to upload symbols manually to get the line numbers from the DLL. The ones from exe were resolved correctly. Symbol upload needs to be looked into

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/590196b78e9ff32e6c29fd62daec3c818b86e089/src/openrct2/interface/Window.cpp#L225
