### ISSUE TITLE
transfer.sh will shutdown 30th of November 2018

### ISSUE THREAD

**Issue by fromthere** [OpenRCT2/OpenRCT2#8166]
> **transfer.sh will shutdown 30th of November 2018**
> After running transfer.sh for 4 years, it has to come to an end. I started this project, because I needed something quick and simple to share files between from the command line. Now it has grown out of control, with millions of files being shared each month, and no longer sustainable and affordable to keep it running for free. From day one the code has been opensource, of which you can run your own instance. Special thanks to Andrea Spacca for maintaining the opensource version, the amazing community for all efforts, the patrons for all support and to Gopher  for being you. 
> So Long, and Thanks for All the Fish. 
> **Remco Verhoef**.

As title says, transfer.sh will shutdown 30th of November 2018.

**Comment by IntelOrca** [comment]
transfer.sh is currently used in out Travis scripts so they will need changing.

**Comment by alex-0xFF** [comment]
> Don’t Panic! transfer.sh will live on!
>After running and supporting transfer.sh for 4 years on my own, I’m happy to announce we are partnering with Storj Labs to keep the project going. From day one, the transfer.sh code has been open source. Storj has a commitment to open source sustainability and reached out to help us find a way to keep our project alive. Stay tuned for updates on the partnership with Storj, but for now, please continue to enjoy the service!
>Blue skies, Remco Verhoef

**Comment by fromthere** [comment]
Closing since transfer.sh no longer shuts down.(Will re-open if transfer.sh is closing again)
