### ISSUE TITLE
BACKTRACE d4e6be utf8_get_next -> WindowManager::OpenWindow

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8173]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/d4e6be53d38565291d4bc3f590b73a67a0e9c81a3d96922a68294fd7f0646874?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Sat Oct 27 2018 21:43:07)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> 590196b: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>utf8_get_next -> WindowManager::OpenWindow -> context_open_window -> window_server_list_mouseup -> input_state_widget_pressed -> game_handle_input_mouse -> game_handle_input -> OpenRCT2::TitleScreen::Update -> OpenRCT2::Context::Update -> SDL_PeepEvents_REAL -> SDL_WaitEventTimeout_REAL -> SDL_PollEvent_REAL -> UiContext::ProcessMessages -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> wmain</code></td></tr>
</table>

**Comment by janisozaur** [comment]
Still happening. I wasn't able to reproduce it, perhaps it's something Windows-only?
