### ISSUE TITLE
Scenario Editor does not preserve Invention List order in loaded landscapes

### ISSUE THREAD

**Issue by Topodic** [OpenRCT2/OpenRCT2#8175]
**OS:** Windows 7 x64, Ubuntu 18.04
**Version:** 0.2.1+
**Commit/Build:** 590196b78e9ff32e6c29fd62daec3c818b86e089

Upon loading an existing scenario as a landscape, the invention order of the scenario is not preserved. This appears to occur with scenarios included with the game as well as custom scenarios. The ordering seems random, yet consistent in what is present in each category across loads. This issue does not appear to be present in the original version of the game.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Load scenario in Scenario Editor

2. Compare Invention List to scenario when played

**Screenshots / Video:**
_OpenRCT2_:
![2018-10-27_15-01-43_openrct2](https://user-images.githubusercontent.com/43795565/47609760-dcd79480-d9f9-11e8-9993-6629c568a920.png)

![2018-10-27_15-02-17_openrct2](https://user-images.githubusercontent.com/43795565/47609763-e3fea280-d9f9-11e8-9dd0-924121a52ba9.png)

![2018-10-27_15-02-47_openrct2](https://user-images.githubusercontent.com/43795565/47609764-e660fc80-d9f9-11e8-948a-0ab7fa2302c1.png)

![2018-10-27_15-03-13_openrct2](https://user-images.githubusercontent.com/43795565/47609766-e7922980-d9f9-11e8-8377-5bf48b291184.png)

_Vanilla_:
![scr2](https://user-images.githubusercontent.com/43795565/47609773-00024400-d9fa-11e8-987b-80b7fb1333f6.png)

**Comment by Patrik356b** [comment]
I suspect regression. Pretty sure this was working previously

**Comment by ocalhoun6** [comment]
> I suspect regression. Pretty sure this was working previously

It's been like this a long time for me ... not sure how long, but at least since Dec 2017 -- I have a scenario saved with that date that I remember having the same problem with.
