### ISSUE TITLE
Ride entrance banner still uses the unmodified default strings

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#818]
When you build a new ride, e.g. a Looping Roller Coaster, (Open)RCT2 will show a default name, e.g. Looping Roller Coaster 1. When you open that saved game in another language version of (Open)RCT2, it will show the default name in that language. (Also applies to non-renamed staff, for example).

But the entrance banner in OpenRCT2 still seems to take the name from the original (unmodified) strings. This results in a wrong/different name on the entrance banner, as can be seen in the screenshot.

![scr6](https://cloud.githubusercontent.com/assets/1478678/6227880/535ba17c-b6a5-11e4-84b9-1da007648286.png)

**Comment by duncanspumpkin** [comment]
Now that is an interesting bug. I dont think this can be fixed at present as the graphics code for drawing the text on entrances/banners has not been done. It will still be using the old text lookup code and will return the english name. I take it when you rename it fixes itself.

**Comment by IntelOrca** [comment]
Unfortunately, this is another case of something that hasn't been implemented yet to be able to fix, just like the ride construction window.

**Comment by Gymnasiast** [comment]
Fixed in UTF-8 branch.
