### ISSUE TITLE
Cannot claim land or set construction rights over ride entrances or exits

### ISSUE THREAD

**Issue by Topodic** [OpenRCT2/OpenRCT2#8187]
**OS:** Ubuntu 18.04
**Version:** 0.2.1+
**Commit/Build:** 83c3f3a9056cf788749aedbddedaf52592a4adb8

When in sandbox mode, you can remove park land or construction rights over a ride entrance or exit, but cannot grant them. This occurs regardless of the entrance or exit's height relative to the ground. Not sure if there is a way to test this in vanilla due to the lack of sandbox mode.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open a scenario and enable sandbox mode
2. Remove land or construction rights over ride entrance/exit and attempt to restore them

**Screenshots / Video:**

https://www.youtube.com/watch?v=Qj6jKOd4VuM

**Comment by Gymnasiast** [comment]
This is most likely caused by code that has to prevent the _park_ entrance from getting owned, but end up guarding all types of entrance.
