### ISSUE TITLE
BACKTRACE 10101b WallCheckObstruction

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8197]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/10101b37c351600d6b7b774216e0be46544d47fc109a9672d695cafe6790b78f?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Thu Nov 01 2018 00:51:45)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> 698426d: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>WallCheckObstruction -> WallPlace -> game_command_place_wall -> game_do_command_p -> try_place_ghost_scenery -> top_toolbar_tool_update_scenery -> game_handle_input -> context_handle_input -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by ZehMatt** [comment]
Probably fixed and backtrace has no more data
