### ISSUE TITLE
Double entrance/exit when placing them on same tile with clearance checks disabled

### ISSUE THREAD

**Issue by giraty** [OpenRCT2/OpenRCT2#8200]
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** f186860

There's double entrance and exit that could happen if you put them with ZC on the same tile, depends on the step.

- [x ] Reproducible in RCT2 (vanilla)?
- [x ] Specific to multiplayer?
This was done offline only

**Steps to reproduce:**
1. Turn ZC on.
2. Place entrace and exit in the same tile. For example we place entrance first, then the exit on the same tile.
3. Select exit again, place it on another location in the station. Now you have 2 exits in a station.

**Dump file**: None

**Screenshots / Video:**
![](https://cdn.discordapp.com/attachments/356546567391674372/507557997233307679/unknown.png)

![](https://cdn.discordapp.com/attachments/356546567391674372/507564573352525844/unknown.png)

**Comment by Broxzier** [comment]
Zero clearance is not the same as disabled clearance checks. Did you use 8cars to make all clearance heights zero, or did you use the cheat provided by OpenRCT2?

**Comment by giraty** [comment]
Cheat from OpenRCT2
