### ISSUE TITLE
Only quarter scenery objects in the southwest corner can be painted

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#8201]
**Version:** 0.2.1
**Commit/Build:** f8add7f

Painting quarter tile scenery elements only works for items placed on the southwestern side. When there are multiple small scenery items on the same tile at the same height, painting any of them affects the one in the SW corner.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Place a few quarter scenery objects that can be painted
2. Paint them

Expected: The object under the mouse cursor gets painted.
Actual result: The object in the SW corner of the tile gets painted.

**Comment by deurklink** [comment]
Ok, this one is really annoying...
![paintbug](https://user-images.githubusercontent.com/6469413/47993009-ba770280-e0ee-11e8-9310-dc5ad9fef866.gif)
