### ISSUE TITLE
Game crash with blockbrake mode and track merges.

### ISSUE THREAD

**Issue by JakobPCoder** [OpenRCT2/OpenRCT2#8202]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.2.1]
**Commit/Build:** [e.g. 426e106]

The game crashes when trying to test a coaster that is runing in blockbrake mode
and has these 3 things:
1. normal track merges
2. compled track of the original coaster(to make the block brake mode work)
3. somthing like this: https://www.youtube.com/watch?v=08pfSHzWAy8 (a part where the cars goes backwards)
   

**Steps to reproduce:**
you can either build a coaster like described above or download the test track i build to reproduce it (lol.zip)
It truns fine in normal mode with 1 car but crashes in block brake mode with 2 cars.

**Screenshots / Video:**
https://www.youtube.com/watch?v=08pfSHzWAy8

**Save game:**
[lol.zip](https://github.com/OpenRCT2/OpenRCT2/files/2540280/lol.zip)

**Comment by 733737** [comment]
game no longer crashes while testing this ride.

**Comment by tupaschoal** [comment]
Works for me as well
