### ISSUE TITLE
Added attractions scenario's show up twice with both added attractions and loopy landscapes installed

### ISSUE THREAD

**Issue by Assassin877** [OpenRCT2/OpenRCT2#8211]
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** 0cd7f1e

Added attractions scenario's show up twice in the scenario selection list when both added attractions and loopy landscapes are installed.

**Steps to reproduce:**
1. Have OpenRCT2 use a copy of RCT1 with both added attractions and loopy landscapes installed.

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/43112034/47933165-1580dd80-ded4-11e8-81ca-8e83fabd9c3d.png)

**Comment by Broxzier** [comment]
That's odd. OpenRCT2 only loads them from one folder. Do you have copies of them in your _OpenRCT2/track_ folder? I doubt the original expansion pack installers don't recognize each other and write copies of these files.

Where did you get your RCT1 expansions from (Steam/GOG/Disc)?

**Comment by Assassin877** [comment]
I am using the Rollercoaster Tycoon Gold Edition (physical discs). 

When enabling debugging tools, I noticed I have the scenario twice in my scenario folder. Seems like the Loopy Landscapes installer renamed the scenario's from the Added attractions installer to Old_<Scenario name> and placed it's own version in the folder as well. Removing the Old_ versions from the scenario folder fixes the problem.

![image](https://user-images.githubusercontent.com/43112034/48356584-e0744800-e696-11e8-8d3f-565a9e77ffcd.png)
