### ISSUE TITLE
Faulty folder recreation in "save"

### ISSUE THREAD

**Issue by Richard-L** [OpenRCT2/OpenRCT2#8219]
>Place an SV6 in a subfolder in the default "save" directory.
>Open the park and close OpenRCT2.
>Delete the subfolder and its contents. Open OpenRCT2 back up.
>An empty subfolder with the same name as before is created, as it looks for that folder in the "open park" dialogue.

It should instead notice the folder has been deleted, and go to the default "save".

Thanks

**Comment by hokasha2016** [comment]
My team and i would like to attempt to fix this issue

**Comment by bdupree5** [comment]
We will be submitting a pull request for this issue today.
