### ISSUE TITLE
Feature: Allow climate to be changed while playing scenario

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#8222]
**OS:** Windows 10
**Version:** 0.2.1

I like that you can edit many of the scenario options while playing a scenario. One option that is missing however, is the option to change the climate of the map. Some workbenches that are distributed as .sv6 files are stuck with an annoying climate type because of this.
It would be great if a feature was added which allows us to change the climate while playing a scenario.

**Comment by ZehMatt** [comment]
There is a way to change it already, unless I'm missing the issue?
![2018-11-04_16-37-01](https://user-images.githubusercontent.com/5415177/47966185-f3ac6580-e04f-11e8-9f81-e7f7b9fa9670.jpg)

**Comment by deurklink** [comment]
What i mean is the climate. So when you make a scenario, you select whether it will be a Cold climate, or Hot and dry, etc.

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/f8add7f62e0c80cbe95c0db81cbee66fa435530b/src/openrct2/interface/InteractiveConsole.cpp#L803

**Comment by deurklink** [comment]
It would probably be more user-friendly if it could be found in the scenario options, like where it's found when creating a scenario.
![image](https://user-images.githubusercontent.com/6469413/47966559-20627c00-e054-11e8-89d4-066d6f85c4d3.png)

**Comment by AaronVanGeffen** [comment]
Not sure why it's hidden in the scenario options while in-game... But if we can change it through the console, we should be able to sort it through the GUI as well.

**Comment by Patrik356b** [comment]
@ZehMatt "Freeze climate" is probably wrong wording. Should be "Freeze weather" logically.

**Comment by Gymnasiast** [comment]
@AaronVanGeffen What @deurklink says is not correct. The empty spot has "Cash per guest (average)" in the Scenario Editor. (Still not sure why it is hidden, though.)

The climate selection is in the final window: Objective Selection. That should be made available.

**Comment by deurklink** [comment]
I wasn't really referring to that empty spot, just showing there was no way to select the climate in the scenario options.. Anyway, it is normally indeed in the objective selection window:
![image](https://user-images.githubusercontent.com/6469413/47992850-43416e80-e0ee-11e8-8a66-eb5978a6c548.png)
Maybe it could be turned into a tab, or maybe its own item in the debug options drop-down menu.

**Comment by IntelOrca** [comment]
I think climate should be moved to the park options tab in the previous window.

**Comment by Gymnasiast** [comment]
Makes sense, but it's still a good idea to make the Objective Selection available - it enables to user to modify the objective and change what rides are under a preservation order. (The cheats window only has options for 'Have fun' and 'All destructible', respectively.)

**Comment by IntelOrca** [comment]
There are some caveats if I remember rightly. The scenario name and details are stored in a separate field, probably like SV6 header or something which won't update the objective window in-game.

**Comment by Gymnasiast** [comment]
If that's the case, the fields in question should be hidden.

**Comment by IntelOrca** [comment]
Not sure what you mean, I meant separate variables in the code.
