### ISSUE TITLE
Painting tool only works on 1 out of every 4 quarter tiles.

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#8223]
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** 3aeb87b

If you try to paint quarter tile scenery items, they will only be painted if they're on a specific corner of the tile.
![paintbug](https://user-images.githubusercontent.com/6469413/47969750-9ed31400-e07c-11e8-821f-d00081adba39.gif)

**Comment by tombomp** [comment]
#8201 is the same bug
