### ISSUE TITLE
Paths of pre-built rides are built incorrectly

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#8236]
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** 3aeb87b

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Build any pre-built ride
2. Paths/Queues are built incorrectly as you can see below.

**Dump file**

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/10726524/48113154-dfa97380-e29c-11e8-94d0-37c2651d4ce4.png)
![image](https://user-images.githubusercontent.com/10726524/48113226-43cc3780-e29d-11e8-8a52-57c0d26465c9.png)

Sorry and please let me know if it is a duplicated.

**Comment by Gymnasiast** [comment]
Most likely the result of one of my tile element refactors. But that will need to be bisected.
