### ISSUE TITLE
Add option to choose between RCT1 and Loopy Landscapes title screen music

### ISSUE THREAD

**Issue by Assassin877** [OpenRCT2/OpenRCT2#8238]
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** 0cd7f1e

The title screen music from RCT1 is different from the one used in the Loopy Landscapes expansion (the ending). At the moment there are two options for title screen music: RCT1 and RCT2. It would be good to have the option to choose between both versions for the RCT1 title screen music.

**Comment by Gymnasiast** [comment]
OpenRCT2 can only connect to one RCT1 folder, and frankly, I don't think it's worth doing all the work needed just so you can easily select a slightly shorter version of the RCT1 theme. And the (I expect few) people who do prefer it could always overwrite the newer theme with the older one.

I guess that, one day, we'll have title music as objects, so people can add anything they like. Until then, it's too much hassle.

**Comment by Patrik356b** [comment]
I think only a handful of people have noticed this anyway.
