### ISSUE TITLE
"Freeze climate" is probably wrong wording. Should be "Freeze weather" logically.

### ISSUE THREAD

**Issue by Patrik356b** [OpenRCT2/OpenRCT2#8245]
I mentioned this previously but nobody read my post.

![img](https://user-images.githubusercontent.com/5415177/47966185-f3ac6580-e04f-11e8-9f81-e7f7b9fa9670.jpg)

version: 18f1fab but doesn't apply because this is an old thing.

_Originally posted by @Patrik356b in https://github.com/OpenRCT2/OpenRCT2/issues/8222#issuecomment-435755758_

**Comment by Gymnasiast** [comment]
Has been changed now.
