### ISSUE TITLE
Very Rarely, This Happens. (Title Bar Missing)

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#825]
It appears to be brought on by using Alt+Tab, and even then is a fairly rare thing.

![screenshot 17](https://cloud.githubusercontent.com/assets/3945538/6241315/0a41f614-b6e9-11e4-9b4c-39ebf748694a.png)
![screenshot 18](https://cloud.githubusercontent.com/assets/3945538/6241316/0a458306-b6e9-11e4-8cec-8efe99603c09.png)
![screenshot 19](https://cloud.githubusercontent.com/assets/3945538/6241317/0a47bc52-b6e9-11e4-8521-0bed7204bbc9.png)

**Comment by mrtnptrs** [comment]
But you're testing this on the new Windows 10 technical preview. Can you also reproduce this on a stable windows version?

**Comment by PFCKrutonium** [comment]
I have had it occur on Windows 8.1 Update 1, Yes.

**Comment by IntelOrca** [comment]
@PFCKrutonium does this still happen?

**Comment by PFCKrutonium** [comment]
I haven't had this happen in a very long time, closing.
