### ISSUE TITLE
Rides and scenery placeable outside of map with ZC and Sandbox mode enabled

### ISSUE THREAD

**Issue by Topodic** [OpenRCT2/OpenRCT2#8264]
**OS:** Windows 7, Ubuntu 18.04
**Version:** 0.2.1+
**Commit/Build:** de12a8d

With zero clearance and sandbox mode, rides and scenery that can use the scattered placement do not produce an "Off edge of map" error like pathing does and can be constructed outside of the boundaries of the map. This crashes the game when an entity would be placed on an X or Y greater than 255 or less than 0. Rides operate just fine out of the edges of the map so long as the absolute boundaries are not reached. It does not seem like a dump file is produced.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Turn on sandbox mode and zero clearance
2. Begin constructing a ride or scattering scenery out of the edges of the map 
3. Witness crash past 0 or 255 X/Y

**Comment by janisozaur** [comment]
What do you mean by "sandbox mode"?

**Comment by IntelOrca** [comment]
@janisozaur sandbox mode is a toggle setting under the cheat toolbar menu.

**Comment by Broxzier** [comment]
Related: #7587
