### ISSUE TITLE
BACKTRACE 40bdfc LdrpDecrementModuleLoadCountEx -> LdrUnloadDll -> FreeLibrary

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8267]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/40bdfc8b4f8371824796c0ab608c0f5820bb4b6cad84c46df1a16870a825494d?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Fri Nov 16 2018 17:49:16)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> 3a1c141: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>LdrpDecrementModuleLoadCountEx -> LdrUnloadDll -> FreeLibrary -> DestroyDeviceLHDDI -> D3D9ResetDevice -> D3D_Reset -> D3D_RenderPresent -> HardwareDisplayDrawingEngine::Display -> HardwareDisplayDrawingEngine::EndDraw -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment]
Some d3d stuff
