### ISSUE TITLE
Inconsistent behavior of water/land/etc tools

### ISSUE THREAD

**Issue by adrian17** [OpenRCT2/OpenRCT2#828]
(all of this is behavior of original game; these are not really bugs, but still it's behavior that could be implemented better)
- When you try to lower water level outside of park area, you don't get an "Land not owned by park" error message - instead, the game plays the sound of changing water level as if you were doing it. Trying to raise water level correctly displays an error.
- When you try to lower water level inside the park where there's no water, I think there should be an additional error message displayed - currently it's also playing the sound of successfuly changing water level.
- When you try to use the tools outside of the map (on the black space), Land and Water tools show "land not owned by park" message, while Clear Scenery, Scenery and Footpath tools don't do anything (which I think is better behavior).

**Comment by Gymnasiast** [comment]
1) Agreed
2) I don't think it should display an error, it's clear enough. It should not play a sound effect though.
3) I think all tools should display an error.

**Comment by IntelOrca** [comment]
I think it should display an error if all all tiles in your selection fail. It should not display an error if at least one tile succeeds.

**Comment by tupaschoal** [comment]
This is what I get with the latest build:

- When you try to lower water level outside of park area, you don't get an "Land not owned by park" error message - ~instead, the game plays the sound of changing water level as if you were doing it. Trying to raise water level correctly displays an error.~
- When you try to lower water level inside the park where there's no water, I think there should be an additional error message displayed - ~currently it's also playing the sound of successfuly changing water level.~
- When you try to use the tools outside of the map (on the black space), Land and Water tools show "land not owned by park" message, while Clear Scenery, Scenery and Footpath tools don't do anything (which I think is better behavior).

**Comment by Gymnasiast** [comment]
I have just tested it. It now consistently shows errors, except:
- When lowering water in a tile with no water (no sound effect is played any more)
- When using the Clear Scenery tool with some tiles inside and some outside.

I consider above behaviour correct. For this reason, I'll consider this issue solved.

**Comment by tupaschoal** [comment]
What about the non-strikedthrough parts of my analysis?

- When you try to lower water level outside of park area, you don't get an "Land not owned by park" error message (which happens with all other tools)
- When you try to lower water level inside the park where there's no water, I think there should be an additional error message displayed
- When you try to use the tools outside of the map (on the black space), Land and Water tools show "land not owned by park" message, while Clear Scenery, Scenery and Footpath tools don't do anything (which I think is better behavior).

**Comment by Gymnasiast** [comment]
The non-striked through parts were either outdated or subject to opinion. But let's run through them:

> When you try to lower water level outside of park area, you don't get an "Land not owned by park" error message (which happens with all other tools)

This is not the case anymore. It does display a message.

> When you try to lower water level inside the park where there's no water, I think there should be an additional error message displayed

I disagree. It's obvious to the user there is no water to lower. No need to spam useless error messages.

> When you try to use the tools outside of the map (on the black space), Land and Water tools show "land not owned by park" message, while Clear Scenery, Scenery and Footpath tools don't do anything (which I think is better behavior).

Also not the case any more. All tools display a message, with Clear Scenery only showing one if the entire selection is outside the park, which I consider correct.

**Comment by tupaschoal** [comment]
>When you try to lower water level outside of park area, you don't get an "Land not owned by park" error message (which happens with all other tools)

>This is not the case anymore. It does display a message.

Are you sure? I mean for raising I get the error, but for lowering I don't 🤔 

> I disagree. It's obvious to the user there is no water to lower. No need to spam useless error messages.

I'm ok with that

> When you try to use the tools outside of the map (on the black space), Land and Water tools show "land not owned by park" message, while Clear Scenery, Scenery and Footpath tools don't do anything (which I think is better behavior).

> Also not the case any more. All tools display a message, with Clear Scenery only showing one if the entire selection is outside the park, which I consider correct.

This is talking about out of bounds (the void), not outside of the park and it still shows the behavior I quoted. I think not showing anything for any tool when applied on the void would be ideal as well. They currently mimic the behavior of when you try to use them outside park limits

**Comment by Gymnasiast** [comment]
![afbeelding](https://user-images.githubusercontent.com/1478678/77696010-fc873980-6fac-11ea-8bdb-52cf470b180a.png)

> This is talking about out of bounds (the void),

OK, that's indeed still there. I prefer creating another issue for that, though - this one was always a collection of semi-related issues to begin with. Could you create one?

**Comment by tupaschoal** [comment]
Now I get where we were differing, I was trying to lower water where there is none:
![image](https://user-images.githubusercontent.com/6443427/77710099-e5941780-6fab-11ea-8381-5d116d998d36.png)
