### ISSUE TITLE
BACKTRACE a249dc move_sprite_to_list -> S4Importer::ImportSprites -> S4Importer::Import

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8285]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/a249dc252e83aba66a3509260ce1440b003a0fc6eeb7d1e67e8e2918223d1f7b?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique errors: [openrct2]</b></a><br /><b>2</b> occurrence(s) <b></b> since (Wed Nov 21 2018 21:26:15)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.com</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> 1abb31a: <em>2</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>move_sprite_to_list -> S4Importer::ImportSprites -> S4Importer::Import -> OpenRCT2::Context::LoadParkFromStream -> OpenRCT2::Context::LoadParkFromFile -> context_load_park_from_file -> game_load_or_quit_no_save_prompt_callback -> window_loadsave_select -> window_loadsave_scrollmousedown -> input_widget_left -> game_handle_input_mouse -> game_handle_input -> context_handle_input -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment]
Additionally, loading the attached park (from #8271) results in:
```
#4  0x00005555577b8026 in Guard::Assert_VA (expression=false, message=0x0, args=0x7fffffffb9a0) at ../src/openrct2/core/Guard.cpp:97
#5  0x00005555577b8325 in Guard::Assert (expression=false, message=0x0) at ../src/openrct2/core/Guard.cpp:67
#6  0x0000555557d11f1f in peep_go_to_ride_entrance (peep=0x55555b749160 <_spriteList+184064>, ride=0x55555b3ec244 <gRideList+11556>) at ../src/openrct2/peep/Guest.cpp:2280
#7  0x0000555557d0f1bf in peep_find_vehicle_to_enter (peep=0x55555b749160 <_spriteList+184064>, ride=0x55555b3ec244 <gRideList+11556>, car_array=std::vector of length 5, capacity 8 = {...}) at ../src/openrct2/peep/Guest.cpp:2375
#8  0x0000555557d0d84e in rct_peep::UpdateRideAtEntrance (this=0x55555b749160 <_spriteList+184064>) at ../src/openrct2/peep/Guest.cpp:3396
#9  0x0000555557d44c50 in rct_peep::UpdateRide (this=0x55555b749160 <_spriteList+184064>) at ../src/openrct2/peep/Guest.cpp:5071
#10 0x0000555557d63d3d in rct_peep::Update (this=0x55555b749160 <_spriteList+184064>) at ../src/openrct2/peep/Peep.cpp:1259
#11 0x0000555557d634d9 in peep_update_all () at ../src/openrct2/peep/Peep.cpp:440
#12 0x0000555557659f65 in OpenRCT2::GameState::UpdateLogic (this=0x60200052bdb0) at ../src/openrct2/GameState.cpp:259
#13 0x0000555557658df4 in OpenRCT2::GameState::Update (this=0x60200052bdb0) at ../src/openrct2/GameState.cpp:151
#14 0x000055555761238b in OpenRCT2::Context::Update (this=0x612000156ac0) at ../src/openrct2/Context.cpp:961
#15 0x0000555557610e4d in OpenRCT2::Context::RunFixedFrame (this=0x612000156ac0) at ../src/openrct2/Context.cpp:872
#16 0x000055555760e414 in OpenRCT2::Context::RunFrame (this=0x612000156ac0) at ../src/openrct2/Context.cpp:845
#17 0x000055555760d9a3 in OpenRCT2::Context::RunGameLoop (this=0x612000156ac0) at ../src/openrct2/Context.cpp:816
#18 0x000055555760d554 in OpenRCT2::Context::Launch (this=0x612000156ac0) at ../src/openrct2/Context.cpp:788
#19 0x00005555575ee04a in OpenRCT2::Context::RunOpenRCT2 (this=0x612000156ac0, argc=2, argv=0x7fffffffdb58) at ../src/openrct2/Context.cpp:227
#20 0x0000555556e6cc37 in main (argc=2, argv=0x7fffffffdb58) at ../src/openrct2-ui/Ui.cpp:60
```
[park-8285.sv6.gz](https://github.com/OpenRCT2/OpenRCT2/files/2824941/park-8285.sv6.gz)
