### ISSUE TITLE
BACKTRACE 040e4a vehicle_update_motion_dodgems -> vehicle_update_dodgems_mode -> vehicle_update_waiting_to_depart

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8299]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/040e4a98e4695fc331dc8d9dd6c846260f040c1a18008ce055819b9498ec85de?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique errors: [openrct2]</b></a><br /><b>2</b> occurrence(s) <b></b> since (Sun Nov 25 2018 23:26:46)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.com</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> 88b2f5f: <em>1</em>, 18f1fab: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>intdiv</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>vehicle_update_motion_dodgems -> vehicle_update_dodgems_mode -> vehicle_update_waiting_to_depart -> vehicle_update -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment]
Still happening.
```
>>> bt
#0  0x00005555581879b4 in vehicle_update_motion_dodgems (vehicle=0x55555b77fc60 <_spriteList+408064>) at ../src/openrct2/ride/Vehicle.cpp:6403
#1  0x000055555814cf3d in vehicle_update_dodgems_mode (vehicle=0x55555b77fc60 <_spriteList+408064>) at ../src/openrct2/ride/Vehicle.cpp:2447
#2  0x00005555580e6d3f in vehicle_update (vehicle=0x55555b77fc60 <_spriteList+408064>) at ../src/openrct2/ride/Vehicle.cpp:1968
#3  0x00005555580e5f4b in vehicle_update_all () at ../src/openrct2/ride/Vehicle.cpp:1345
#4  0x0000555557659f6f in OpenRCT2::GameState::UpdateLogic (this=0x60200052bdb0) at ../src/openrct2/GameState.cpp:261
#5  0x0000555557658df4 in OpenRCT2::GameState::Update (this=0x60200052bdb0) at ../src/openrct2/GameState.cpp:151
#6  0x000055555761238b in OpenRCT2::Context::Update (this=0x612000156ac0) at ../src/openrct2/Context.cpp:961
#7  0x0000555557610e4d in OpenRCT2::Context::RunFixedFrame (this=0x612000156ac0) at ../src/openrct2/Context.cpp:872
#8  0x000055555760e414 in OpenRCT2::Context::RunFrame (this=0x612000156ac0) at ../src/openrct2/Context.cpp:845
#9  0x000055555760d9a3 in OpenRCT2::Context::RunGameLoop (this=0x612000156ac0) at ../src/openrct2/Context.cpp:816
#10 0x000055555760d554 in OpenRCT2::Context::Launch (this=0x612000156ac0) at ../src/openrct2/Context.cpp:788
#11 0x00005555575ee04a in OpenRCT2::Context::RunOpenRCT2 (this=0x612000156ac0, argc=2, argv=0x7fffffffdb58) at ../src/openrct2/Context.cpp:227
#12 0x0000555556e6cc37 in main (argc=2, argv=0x7fffffffdb58) at ../src/openrct2-ui/Ui.cpp:60
>>> info locals
collideSprite = 65535
ride = 0x55555b3ecc4c <gRideList+14124>
nextVelocity = 0
eax = 0
edx = 0
rideEntry = 0x7fffffffc940
vehicleEntry = 0x61c000060880
ebx = 16777217
_eax = 16742536
>>> p vehicle->mass
$1 = 0
```
Loading the park is enough to trigger.
[park-8299.sv6.gz](https://github.com/OpenRCT2/OpenRCT2/files/2824920/park-8299.sv6.gz)
