### ISSUE TITLE
BACKTRACE 2edbe9 rct_peep::UpdateRideMazePathfinding -> rct_peep::UpdateRide

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8300]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/2edbe9f958634cf422a02677e5389afa8223f65115f62ebeadf49be5fce359e9?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Mon Nov 26 2018 14:27:15)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> d0108b3: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>rct_peep::UpdateRideMazePathfinding -> rct_peep::UpdateRide -> rct_peep::Update -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> wmain</code></td></tr>
</table>

**Comment by janisozaur** [comment]
To be fixed with https://github.com/OpenRCT2/OpenRCT2/pull/8599

**Comment by Gymnasiast** [comment]
#8599 has been merged, so this has been fixed.
