### ISSUE TITLE
BACKTRACE 81fe55 window_ride_vehicle_dropdown

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8303]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/81fe55363d1de52f0183b90929b0949ad1fd777e704658a2c5866eb4fd703909?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Tue Nov 27 2018 00:35:06)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>commit:</strong> d0108b3: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>window_ride_vehicle_dropdown -> input_state_widget_pressed -> game_handle_input_mouse -> game_handle_input -> context_handle_input -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment]
Looks like it's still present, missing nullptr check in https://github.com/OpenRCT2/OpenRCT2/blob/92412d4bab085fe5adbdac80f67af4a50d2fab98/src/openrct2-ui/windows/Ride.cpp#L2889, no idea how it became nullptr
