### ISSUE TITLE
Building on Windows with the default command gives low FPS

### ISSUE THREAD

**Issue by wisegoodvin** [OpenRCT2/OpenRCT2#8309]
**OS:** Windows 10 Ent, 1608 LTSB
**Version:** 0.2.1
**Commit/Build:** a9a583d
**Compiller:** MS Visual Studio 2017 Community (15.8.9)

If i try to build the game with default build command from `readme.md`: `msbuild openrct2.proj /t:build /p:platform=x64`, i've got maximum 14 in-game FPS.
This happens because in the build project file `openrct2.proj` the default configuration set to "Debug".
I think this is not a glitch, but normal user will be surprised, because he wants to play the game, and not look at 14 FPS because of the extra debug information.
I see two solutions:
1. Change the readme.md instruction to the following `msbuild openrct2.proj /t:build /p:platform=x64 /p:Configuration=Release`
2. Change the default configuration to `Release`.

I would choose the second option #8308

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Run `msbuild openrct2.proj /t:build /p:platform=x64` build command from `readme.md`
2. Run game

**Dump file:**

Not needed.

**Screenshots / Video:**

![default](https://user-images.githubusercontent.com/15244551/49139854-d774af00-f303-11e8-9ce8-6453e7e89c61.png)

**Save game:**

Not needed.

**Comment by javierdlg** [comment]
For future reference, fix was to add `/p:configuration=release` to the build commandline
