### ISSUE TITLE
BACKTRACE 83f40c ride_shop_connected -> scenario_week_update

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8318]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/83f40c982c5cf4f775e590b9c9fb4aa3e24eda2df1bd86e3e136f02dd29f6607?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Fri Nov 30 2018 02:58:12)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> *: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> E:\\Documents\\OpenRCT2\\d6f7a206-829b-41fb-a444-1299af10f629.sv6.gz: <em>1</em><br><strong>commit:</strong> eeaca61: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>ride_shop_connected -> scenario_week_update -> scenario_update -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment]
Unsure, I couldn't reproduce it on `develop` or eeaca61, but I don't recall any fix in that area.
