### ISSUE TITLE
BACKTRACE 5007fd jumping_fountain_continue -> sprite_misc_update / S6Importer::ImportTileElement

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8326]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/5007fd88b333d2ce5b775326c6057ccca744b96079ec321db6db7b732ae3ef1e?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique errors: [openrct2]</b></a><br /><b>6</b> occurrence(s) <b></b> since (Fri Nov 30 2018 19:02:30)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>6</em><br><strong>attachment_config.ini:</strong> *: <em>6</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\mrvos\\OneDrive\\Documenten\\OpenRCT2\\c1f27ae5-a0ca-4e9d-8f45-f989291e0849.sv6.gz: <em>1</em>, C:\\Users\\mrvos\\OneDrive\\Documenten\\OpenRCT2\\33792541-c419-4ec1-b569-ea29c5a16009.sv6.gz: <em>1</em>, C:\\Users\\mrvos\\OneDrive\\Documenten\\OpenRCT2\\03f41c6c-4c56-4cc5-bdfb-7402a9ca40de.sv6.gz: <em>1</em>, C:\\Users\\mrvos\\OneDrive\\Documenten\\OpenRCT2\\4997ef09-bc38-4afd-96ef-54538c5a1ea9.sv6.gz: <em>1</em>, C:\\Users\\mrvos\\OneDrive\\Documenten\\OpenRCT2\\d24c0d13-182e-4013-825a-3f14444fdb2c.sv6.gz: <em>1</em>, C:\\Users\\mrvos\\OneDrive\\Documenten\\OpenRCT2\\6b854cb8-8252-4aa9-9599-ee5b7c33db98.sv6.gz: <em>1</em><br><strong>commit:</strong> eeaca61: <em>6</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>jumping_fountain_continue -> sprite_misc_update -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment]
[park_jumping_fountains_8326.sv6.gz](https://github.com/OpenRCT2/OpenRCT2/files/2634948/park_jumping_fountains_8326.sv6.gz)

**Comment by janisozaur** [comment]
Loading the park on current `deleop` yields:
```
#4  0x0000555557ebd728 in S6Importer::ImportTileElement (this=0x7fffc12ff800, dst=0x55555b4fecc8 <gTileElements+458184>, src=0x7fffc13724b8) at ../src/openrct2/rct2/S6Importer.cpp:1027
#5  0x0000555557eb8834 in S6Importer::ImportTileElements (this=0x7fffc12ff800) at ../src/openrct2/rct2/S6Importer.cpp:881
#6  0x0000555557ea687d in S6Importer::Import (this=0x7fffc12ff800) at ../src/openrct2/rct2/S6Importer.cpp:213
#7  0x00005555575f4d31 in OpenRCT2::Context::LoadParkFromStream (this=0x612000156ac0, stream=0x7fffffffd220, path="/home/janisozaur/Downloads/park_jumping_fountains_8326.sv6", loadTitleScreenFirstOnFail=true) at ../src/openrct2/Context.cpp:530
#8  0x00005555575f3dfe in OpenRCT2::Context::LoadParkFromFile (this=0x612000156ac0, path="/home/janisozaur/Downloads/park_jumping_fountains_8326.sv6", loadTitleScreenOnFail=true) at ../src/openrct2/Context.cpp:497
#9  0x000055555760ca10 in OpenRCT2::Context::Launch (this=0x612000156ac0) at ../src/openrct2/Context.cpp:718
#10 0x00005555575ee04a in OpenRCT2::Context::RunOpenRCT2 (this=0x612000156ac0, argc=2, argv=0x7fffffffdb48) at ../src/openrct2/Context.cpp:227
#11 0x0000555556e6cc37 in main (argc=2, argv=0x7fffffffdb48) at ../src/openrct2-ui/Ui.cpp:60
```
