### ISSUE TITLE
BACKTRACE a5d386 OpenRCT2::Drawing::X8DrawingContext::FillRect -> gfx_fill_rect -> gfx_fill_rect_inset

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8327]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/a5d3869bb691822aebf5880800177d025afcf4c63bb38dd647f07869481bad80?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Fri Nov 30 2018 20:13:39)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> *: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\mrvos\\OneDrive\\Documenten\\OpenRCT2\\16529dae-117c-471a-984f-7b80d95df419.sv6.gz: <em>1</em><br><strong>commit:</strong> eeaca61: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>OpenRCT2::Drawing::X8DrawingContext::FillRect -> gfx_fill_rect -> gfx_fill_rect_inset -> window_news_scrollpaint -> widget_scroll_draw -> widget_draw -> window_draw_widgets -> window_draw_single -> window_draw -> window_draw_all -> OpenRCT2::Drawing::X8DrawingEngine::DrawAllDirtyBlocks -> OpenRCT2::Drawing::X8DrawingEngine::PaintWindows -> OpenRCT2::Paint::Painter::Paint -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/381e2c12bcf4b61390ff6bd97f52891f35bde4a6/src/openrct2/drawing/X8DrawingEngine.cpp#L550
`dpi` seems to be invalid
