### ISSUE TITLE
BACKTRACE 0dd8ba map_animation_invalidate_wall -> map_animation_invalidate_all

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8329]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/0dd8baa2aa7151573d7384535aedc34ea35fb05e57b66d8b4910d1303c35ec67?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique errors: [openrct2]</b></a><br /><b>3</b> occurrence(s) <b></b> since (Fri Nov 30 2018 21:18:10)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>3</em><br><strong>attachment_config.ini:</strong> *: <em>3</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\mrvos\\OneDrive\\Documenten\\OpenRCT2\\264d36fa-7f4c-48cb-b623-2110ce411819.sv6.gz: <em>1</em>, C:\\Users\\mrvos\\OneDrive\\Documenten\\OpenRCT2\\3f3e3230-c987-4531-a875-3945b34ec15d.sv6.gz: <em>1</em>, C:\\Users\\mrvos\\OneDrive\\Documenten\\OpenRCT2\\c41c52e0-427f-43b2-8abc-5612afbe5794.sv6.gz: <em>1</em><br><strong>commit:</strong> eeaca61: <em>3</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>map_animation_invalidate_wall -> map_animation_invalidate_all -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment]
Fixed in f5f3bfe087d4a8869431fe043d01b76656c70c00
