### ISSUE TITLE
BACKTRACE d4b87a window_tile_inspector_scrollpaint -> widget_scroll_draw -> widget_draw

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8330]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/d4b87a6464c8c3e1fd6f5eb697f0c474ad3dac183b4586bfe49435da6216e173?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique errors: [openrct2]</b></a><br /><b>2</b> occurrence(s) <b></b> since (Fri Nov 30 2018 21:44:55)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>2</em><br><strong>attachment_config.ini:</strong> C:\\Users\\mrvos\\OneDrive\\Documenten\\OpenRCT2\\3cb59e5c-8ebd-4432-9dd4-b7277bcd06ef.ini: <em>1</em>, C:\\Users\\mrvos\\OneDrive\\Documenten\\OpenRCT2\\4c778691-1e1a-4b62-8b63-36b348f5dc8b.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\mrvos\\OneDrive\\Documenten\\OpenRCT2\\3cb59e5c-8ebd-4432-9dd4-b7277bcd06ef.sv6.gz: <em>1</em>, C:\\Users\\mrvos\\OneDrive\\Documenten\\OpenRCT2\\4c778691-1e1a-4b62-8b63-36b348f5dc8b.sv6.gz: <em>1</em><br><strong>commit:</strong> c74ef92: <em>2</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>window_tile_inspector_scrollpaint -> widget_scroll_draw -> widget_draw -> window_draw_widgets -> window_tile_inspector_paint -> window_draw -> window_draw_all -> OpenRCT2::Drawing::X8DrawingEngine::DrawAllDirtyBlocks -> OpenRCT2::Drawing::X8DrawingEngine::PaintWindows -> OpenRCT2::Paint::Painter::Paint -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> wmain</code></td></tr>
</table>

**Comment by janisozaur** [comment]
The crash is reported at https://github.com/OpenRCT2/OpenRCT2/blob/fdba61002fa26afc391c4ff986f2b60ca26857a3/src/openrct2-ui/windows/TileInspector.cpp#L2154

**Comment by janisozaur** [comment]
My bad, I thought it checked out the commit in question successfully, but it didn't. Upon closer inspection it is a crash in https://github.com/OpenRCT2/OpenRCT2/blob/c74ef92561392ce4708291b2f88d2f173ba561e2/src/openrct2-ui/windows/TileInspector.cpp#L2153-L2156 which on current develop is still present as https://github.com/OpenRCT2/OpenRCT2/blob/381e2c12bcf4b61390ff6bd97f52891f35bde4a6/src/openrct2-ui/windows/TileInspector.cpp#L2164-L2167 and appears to be missing `nullptr` check
