### ISSUE TITLE
BACKTRACE 8b1f42 rct_peep::SetState -> vehicle_update_unloading_passengers -> vehicle_update

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8332]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/8b1f42fc90eb78fc99aba51426e263487a707c51e09118da9a6818f6eb263339?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Fri Nov 30 2018 23:13:32)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> *: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\Frank Artmont\\Documents\\OpenRCT2\\dc6d1235-91dd-451d-8d7b-56c4f33ced7b.sv6.gz: <em>1</em><br><strong>commit:</strong> eeaca61: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>rct_peep::SetState -> vehicle_update_unloading_passengers -> vehicle_update -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment]
Still happening.
```
#4  0x00005555577b8026 in Guard::Assert_VA (expression=false, message=0x555559886f40 <.str.1> "Tried getting sprite %u", args=0x7fffffffc140) at ../src/openrct2/core/Guard.cpp:97
#5  0x00005555577b7e65 in openrct2_assert_fwd (expression=false, message=0x555559886f40 <.str.1> "Tried getting sprite %u") at ../src/openrct2/core/Guard.cpp:31
#6  0x000055555903565a in get_sprite (sprite_idx=65535) at ../src/openrct2/world/Sprite.cpp:83
#7  0x0000555557d21ee0 in rct_peep::UpdateRideEnterVehicle (this=0x55555b75e060 <_spriteList+269824>) at ../src/openrct2/peep/Guest.cpp:3964
#8  0x0000555557d44c96 in rct_peep::UpdateRide (this=0x55555b75e060 <_spriteList+269824>) at ../src/openrct2/peep/Guest.cpp:5086
#9  0x0000555557d63d7a in rct_peep::Update (this=0x55555b75e060 <_spriteList+269824>) at ../src/openrct2/peep/Peep.cpp:1274
#10 0x0000555557d634d9 in peep_update_all () at ../src/openrct2/peep/Peep.cpp:440
#11 0x0000555557659f65 in OpenRCT2::GameState::UpdateLogic (this=0x60200052be90) at ../src/openrct2/GameState.cpp:259
#12 0x0000555557658df4 in OpenRCT2::GameState::Update (this=0x60200052be90) at ../src/openrct2/GameState.cpp:151
#13 0x000055555761238b in OpenRCT2::Context::Update (this=0x612000156ac0) at ../src/openrct2/Context.cpp:961
#14 0x0000555557610e4d in OpenRCT2::Context::RunFixedFrame (this=0x612000156ac0) at ../src/openrct2/Context.cpp:872
#15 0x000055555760e414 in OpenRCT2::Context::RunFrame (this=0x612000156ac0) at ../src/openrct2/Context.cpp:845
#16 0x000055555760d9a3 in OpenRCT2::Context::RunGameLoop (this=0x612000156ac0) at ../src/openrct2/Context.cpp:816
#17 0x000055555760d554 in OpenRCT2::Context::Launch (this=0x612000156ac0) at ../src/openrct2/Context.cpp:788
#18 0x00005555575ee04a in OpenRCT2::Context::RunOpenRCT2 (this=0x612000156ac0, argc=2, argv=0x7fffffffdb58) at ../src/openrct2/Context.cpp:227
#19 0x0000555556e6cc37 in main (argc=2, argv=0x7fffffffdb58) at ../src/openrct2-ui/Ui.cpp:60
```
Park is enough to trigger the crash 
[park-8332.sv6.gz](https://github.com/OpenRCT2/OpenRCT2/files/2824831/park-8332.sv6.gz)
