### ISSUE TITLE
BACKTRACE 484496 game_command_remove_large_scenery -> map_clear_scenery_from_tile

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8341]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/484496edc9a6ba6dc225d60a44185500f83f383f68d4a23d3367842a27806a13?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Sat Dec 01 2018 16:01:33)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\mrvos\\OneDrive\\Documenten\\OpenRCT2\\412b4d13-46c9-47c2-a474-efcf8e3ad017.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\mrvos\\OneDrive\\Documenten\\OpenRCT2\\412b4d13-46c9-47c2-a474-efcf8e3ad017.sv6.gz: <em>1</em><br><strong>commit:</strong> ebd4e8f: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>game_command_remove_large_scenery -> map_clear_scenery_from_tile -> map_clear_scenery -> game_command_clear_scenery -> game_do_command_p -> top_toolbar_tool_update_scenery_clear -> game_handle_input -> context_handle_input -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment]
Looks like a missing nullptr check in https://github.com/OpenRCT2/OpenRCT2/blob/381e2c12bcf4b61390ff6bd97f52891f35bde4a6/src/openrct2/actions/LargeSceneryRemoveAction.hpp#L79-L84
