### ISSUE TITLE
Ride's exit is rendered incorrectly while building it

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#8349]
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** 3c63402

![wrong_exit](https://user-images.githubusercontent.com/10726524/49360445-80644500-f71c-11e8-867a-80a1d6fb9480.gif)

Ride's exit is incorrectly rendered when it is building as you can see above GIF.

**Steps to reproduce:**
1. Build any ride
2. Click exit button

**Comment by danielg0** [comment]
This also happens on Linux (4.19.4) on build `f488c4bf3`. Also, the transparent 'ghost' exit can still function as a normal exit if ride building is exited before the real exit is constructed.
This allows the ride to open as though an exit had been constructed, as you can see below.
![GIF](https://user-images.githubusercontent.com/34688856/49545985-22c82800-f8d7-11e8-8e53-4b48339af127.gif)

**Comment by janisozaur** [comment]
Regression from a9a583dcd143971aeb459aa6d9c641dbcf12ef0d
