### ISSUE TITLE
Game never closes.

### ISSUE THREAD

**Issue by mozar99** [OpenRCT2/OpenRCT2#8351]
**OS:** Windows Server 2012r2
**Version:** 0.2.1-373
**Commit/Build:** a9a583d

Game never closes. Makes updating impossible unless I go into task manager and kill all running instances. Has been an issue for months.

![gamenevercloses](https://user-images.githubusercontent.com/29951295/49385107-cd72f780-f6d9-11e8-839a-9650cd76ac44.png)

- [ ] Reproducible in RCT2 (vanilla)? no
- [ ] Specific to multiplayer? no

**Steps to reproduce:**
1. run game, close game. its still running.
2. 

**Screenshots / Video:**
Attached

**Comment by mozar99** [comment]
Using OpenRCT2 Launcher for updating and for launching the game

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/issues/8021
