### ISSUE TITLE
BACKTRACE 536525 OpenRCT2::GameState::UpdateLogic

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8355]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/536525daae6c64baff07e514bebccc5c48a684826cf32914e9d3a69a28df2aa1?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Tue Dec 04 2018 20:01:12)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\RobTe\\OneDrive\\Documents\\OpenRCT2\\69b23972-4351-4c05-81c6-2dbd44f80231.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\RobTe\\OneDrive\\Documents\\OpenRCT2\\69b23972-4351-4c05-81c6-2dbd44f80231.sv6.gz: <em>1</em><br><strong>commit:</strong> c845924: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment]
This is an interesting one, but it's almost impossible to find the objects to load it.

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/c8459249566fbf8a425109e41efebdab3d7e6558/src/openrct2/GameState.cpp#L266

**Comment by janisozaur** [comment]
I have narrowed down the objects missing to this list:
```
[BATMAN  ] Object not found.
[BATMANSG] Object not found.
[AGRENL  ] Object not found.
[DJ      ] Object not found.
[D-WT01  ] Object not found.
[METROOF2] Object not found.
[MWB-0003] Object not found.
[PLYSTRUC] Object not found.
[FMLTPBFC] Object not found.
[CGSMTRAK] Object not found.
[C-WALEPL] Object not found.
[JADEJAVU] Object not found.
[JAMNDBND] Object not found.
[JANINJA ] Object not found.
[METROOF1] Object not found.
[SF-DRF  ] Object not found.
[C-WALEPC] Object not found.
[C-WALEP3] Object not found.
[C-WALEP4] Object not found.
[C-WALEPD] Object not found.
[C-WALEPW] Object not found.
[C-WALEP1] Object not found.
[C-WALEP2] Object not found.
[C-WALEP6] Object not found.
[C-WALEP5] Object not found.
[C-LEGO D] Object not found.
```

**Comment by janisozaur** [comment]
[park_8355_modified.sv6.gz](https://github.com/OpenRCT2/OpenRCT2/files/2650463/park_8355_modified.sv6.gz)

This is a somewhat modified version of the uploaded park. Modifications included replacing the missing objects with others and removing the scenery groups. All the other objects I could find have been embedded in that save.

**Comment by janisozaur** [comment]
the park crashed in a weird spot, loading the modified version I posted yields no results, I would like for someone to take a look at the dump provided. @Broxzier @IntelOrca @ZehMatt ?

**Comment by ZehMatt** [comment]
Sure, I'll take a look.
