### ISSUE TITLE
BACKTRACE 9e49d2 map_reorganise_elements -> SmallSceneryPlace -> game_command_place_scenery

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8357]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/9e49d2e3d8044fadefbbe187e0685a0bea0cf3e64ff66e8f5b658a2403d59490?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Tue Dec 04 2018 21:08:55)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\mrvos\\OneDrive\\Documenten\\OpenRCT2\\bc91580d-321a-43ee-9c7b-da6aab9ef5cd.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\mrvos\\OneDrive\\Documenten\\OpenRCT2\\bc91580d-321a-43ee-9c7b-da6aab9ef5cd.sv6.gz: <em>1</em><br><strong>commit:</strong> 3c63402: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-write</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>map_reorganise_elements -> SmallSceneryPlace -> game_command_place_scenery -> game_do_command_p -> try_place_ghost_scenery -> top_toolbar_tool_update_scenery -> game_handle_input -> context_handle_input -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment]
Unsure about this one, looks to be still valid

**Comment by ZehMatt** [comment]
Game actions
