### ISSUE TITLE
Hang when using the mouse wheel to change number of vehicles

### ISSUE THREAD

**Issue by roosen5** [OpenRCT2/OpenRCT2#8358]
If you are stopping a ride when people are still in the ride/queue, and then going to the vehicle options and changing the number of trains/cars using the mouse wheel, then the game will hang.
This won't send a crash report either because it is looping indefinitely

I already found the problem, and I have a fix for this but I don't have permission to push it
To explain the problem:

```
The sprite_remove in Sprite.cpp tries to find itself inside the quadrant.
It does not find itself, and because the rest of the code assumes that it will always find it
The normal code tries to set the value of the next_in_quadrant so that whoever points at it, will now point at its next sprite.
But because it didn't find whoever was pointing to it, it would set the pointer to SPRITE_INDEX_NULL to its next sprite.
This would lead to cycles in the linked list

The reason that the sprite was not found is that during the entry of a ride, the position of a peep is set to LOCATION_NULL
Exiting a ride sets it back to whatever the location is of an exit.
However stopping a ride that still has people in it would go wrong, as the people are removed from the ride through ride_remove_peeps

This function was called during the PaintWindows.
The fact that this function is called during the painting is the problem, because of the tweening:
Before painting all the positions are stored (Which would at that point be the LOCATION_NULL), during the painting
the peep would be removed from the ride, setting their location to the enrance/exit
After painting is done all the positions are restored again, so the patched position is forgotten and then it would be
removing a sprite with location LOCATION_NULL and that goes wrong
```

- [ No] Reproducible in RCT2 (vanilla)? There is no mouse wheel option to change the index at all 
- [ No] Specific to multiplayer?

**Steps to reproduce:**
1. Open the save file
2. Stop the ride that is framed
3. Change the number of vehicles with the mouse wheel

**Screenshots / Video:**
See a sample of the crash here:
https://mega.nz/#F!1xsV0CJT!UyDJDXRpRq13MwDsl2NMpA?858hCKha

**Save game:**
[Crash_Example.zip](https://github.com/OpenRCT2/OpenRCT2/files/2646616/Crash_Example.zip)

**Comment by roosen5** [comment]
If somebody could give me permission to push a branch I could submit the changes there and create a pull request

**Comment by Gymnasiast** [comment]
@roosen5 The way Github works is that you fork the repo, push it to a branch there and then create a PR. There is no need to have write permissions on the repo you want to create a PR against.

**Comment by roosen5** [comment]
Pull request created at: https://github.com/OpenRCT2/OpenRCT2/pull/8375
