### ISSUE TITLE
BACKTRACE f1aa24 ff2vs::CConverterToVertexShader::PrepareToDraw -> D3D_RenderCopy

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8359]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/f1aa249efb3c1de5bf1e78c4b7b7dcf6b9d8abf30bcc543e9da6ac184ec89411?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Wed Dec 05 2018 04:14:28)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> *: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> *: <em>1</em><br><strong>commit:</strong> a9a583d: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>ff2vs::CConverterToVertexShader::PrepareToDraw -> D3D_RenderCopy -> SDL_RenderCopy_REAL -> HardwareDisplayDrawingEngine::Display -> HardwareDisplayDrawingEngine::EndDraw -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment]
Not something we can resolve
