### ISSUE TITLE
BACKTRACE fb3ad7 window_footpath_set_provisional_path_at_point -> window_footpath_toolupdate

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8363]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/fb3ad79e386228b4ea590bd44287c92d559679d28f07544ebf053e25fddd77ff?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Wed Dec 05 2018 11:53:45)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>RCT2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> *: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> *: <em>1</em><br><strong>commit:</strong> 88b2f5f: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>window_footpath_set_provisional_path_at_point -> window_footpath_toolupdate -> game_handle_input -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> wmain</code></td></tr>
</table>

**Comment by janisozaur** [comment]
This is still happening, it's very common

**Comment by IntelOrca** [comment]
Duplicate of #8513.
