### ISSUE TITLE
BACKTRACE 007a89 track_place -> game_command_place_track -> track_design_place_ride

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8369]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/007a894da209ef1bd44e5d219bde255b3e3c01ba9d692fbb0d8828a586410da1?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Wed Dec 05 2018 20:51:31)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> *: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\Ryan\\Documents\\OpenRCT2\\42eb5354-b838-413f-808b-dcfccb101cb6.sv6.gz: <em>1</em><br><strong>commit:</strong> eeaca61: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>track_place -> game_command_place_track -> track_design_place_ride -> place_virtual_track -> place_track_design -> game_command_place_track_design -> game_do_command_p -> window_track_place_toolupdate -> game_handle_input -> context_handle_input -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by duncanspumpkin** [comment]
Track place has been reworked. I'm closing this. If it reoccurs in the new code can work off the latest.
