### ISSUE TITLE
Objects archives

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#8370]
Objects downloaded from NEDesigns.

This is to make sure there is archive available for easy access to anyone looking for lots of custom objects.
Split to parts under 10MB to fit on GitHub.

[nedesigns.tar.gz.split_aj.gz](https://github.com/OpenRCT2/OpenRCT2/files/2650563/nedesigns.tar.gz.split_aj.gz)
[nedesigns.tar.gz.split_ai.gz](https://github.com/OpenRCT2/OpenRCT2/files/2650564/nedesigns.tar.gz.split_ai.gz)
[nedesigns.tar.gz.split_ah.gz](https://github.com/OpenRCT2/OpenRCT2/files/2650565/nedesigns.tar.gz.split_ah.gz)
[nedesigns.tar.gz.split_ag.gz](https://github.com/OpenRCT2/OpenRCT2/files/2650566/nedesigns.tar.gz.split_ag.gz)
[nedesigns.tar.gz.split_af.gz](https://github.com/OpenRCT2/OpenRCT2/files/2650567/nedesigns.tar.gz.split_af.gz)
[nedesigns.tar.gz.split_ae.gz](https://github.com/OpenRCT2/OpenRCT2/files/2650568/nedesigns.tar.gz.split_ae.gz)
[nedesigns.tar.gz.split_ad.gz](https://github.com/OpenRCT2/OpenRCT2/files/2650569/nedesigns.tar.gz.split_ad.gz)
[nedesigns.tar.gz.split_ac.gz](https://github.com/OpenRCT2/OpenRCT2/files/2650570/nedesigns.tar.gz.split_ac.gz)
[nedesigns.tar.gz.split_ab.gz](https://github.com/OpenRCT2/OpenRCT2/files/2650571/nedesigns.tar.gz.split_ab.gz)
[nedesigns.tar.gz.split_aa.gz](https://github.com/OpenRCT2/OpenRCT2/files/2650572/nedesigns.tar.gz.split_aa.gz)

Size and file name of objects in archive:
https://gist.github.com/janisozaur/1057351fa309706b8dbe7066cdee76e9

**Comment by adrianoaaguiar** [comment]
Hey, I know it's been a while, but since NE site shut down I've been trying to find some objects to open  an old .sv6 of mine. Of all files the only one I could open and extract was the first ".split_aa", the rest of it appears to be corrupted. Am I missing any step or doing something wrong?

**Comment by janisozaur** [comment]
They all work fine. I added checksums to the listing. Not really expecting any errors, but try validating them on your end.

**Comment by IntelOrca** [comment]
I think what is confusing is that all the files have the gz extension even though it is split.

@adrianoaaguiar you need to run `cat nedesigns.tar.gz.split_* > nedesigns.tar.gz && gzip -d nedesigns.tar.gz`.

**Comment by janisozaur** [comment]
@IntelOrca what's the use of intermediate file? I would suggest extracting it directly from the archive: `cat nedesigns.tar.gz.split_* | tar xz`

> I think what is confusing is that all the files have the gz extension even though it is split.

GitHub only whitelists some filenames and wouldn't let me use `nedesigns.tar.gz.split_aa`. In hindsight I might've better used `nedesigns.tar.gz.split_aa.txt`

**Comment by IntelOrca** [comment]
> @IntelOrca what's the use of intermediate file? I would suggest extracting it directly from the archive: cat nedesigns.tar.gz.split_* | tar xz

Maybe they want the intermediate file?

**Comment by adrianoaaguiar** [comment]
> I think what is confusing is that all the files have the gz extension even though it is split.
> 
> @adrianoaaguiar you need to run `cat nedesigns.tar.gz.split_* > nedesigns.tar.gz && tar -zxvf nedesigns.tar.gz`.
> 
> On windows in cmd, you can do `type nedesigns.tar.gz.split_* > nedesigns.tar.gz` then use something like 7zip to open it.

Tried it, says access denied.

**Comment by Ryder17z** [comment]
> > I think what is confusing is that all the files have the gz extension even though it is split.
> > @adrianoaaguiar you need to run `cat nedesigns.tar.gz.split_* > nedesigns.tar.gz && tar -zxvf nedesigns.tar.gz`.
> > On windows in cmd, you can do `type nedesigns.tar.gz.split_* > nedesigns.tar.gz` then use something like 7zip to open it.
> 
> Tried it, says access denied.

I have a solution for you. This batch script merges the split files together. You can then open the file in 7zip and extract all objects.

[nedesign_unsplit.bat.txt](https://github.com/OpenRCT2/OpenRCT2/files/6481703/nedesign_unsplit.bat.txt)


@janisozaur Pro tip: numerical filename splits does have better support, alphabetical doesn't have much, if any support in most windows compression software

**Comment by janisozaur** [comment]
> @janisozaur Pro tip: numerical filename splits does have better support, alphabetical doesn't have much, if any support in most windows compression software


So they should be named nedesigns.tar.gz.split_00.gz instead?

**Comment by Ryder17z** [comment]
That is correct. Or at least still seems to be. I haven't used split
archives in a few years but the situation looks exactly the same.
