### ISSUE TITLE
Refactor gErrorType, gErrorStringId

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#8376]
Only the S6Importer currently uses them, they can be removed by directly showing the error in there. Relatively easy refactor.

**Comment by kennycastro007** [comment]
Is this still open? I've been looking for issues to work on all night, so it'd be nice to find one still open!

**Comment by ZehMatt** [comment]
You can give it a shot

**Comment by kennycastro007** [comment]
What exactly are gErrorType and gErrorStringId doing? I see they're being set but I can't see where they're being used. I checked Diagnostics.h but still couldn't tell where they were being used once set

**Comment by AaronVanGeffen** [comment]
They are both used in GameState.cpp.

**Comment by kennycastro007** [comment]
I've finished the refactor, it still compiles just fine. What are the next steps to completing the issue? i.e How do I start the pull request? Can someone create the branch for the issue or do I have to do something else?

**Comment by AaronVanGeffen** [comment]
Fork the repository and push it to a branch on your fork. Then create a pull request.
