### ISSUE TITLE
BACKTRACE 51c9b4 banner_get_closest_ride_index -> SignSetNameAction::Execute

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8380]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/51c9b4a2214e67dfa249937d724ca1be0f697e29568ddf849cf649fa42da4d2f?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Thu Dec 06 2018 20:42:37)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\Joseph\\Documents\\OpenRCT2\\380379b7-5a8a-46cd-9e0d-53cffe9bc25e.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\Joseph\\Documents\\OpenRCT2\\380379b7-5a8a-46cd-9e0d-53cffe9bc25e.sv6.gz: <em>1</em><br><strong>commit:</strong> dc7d141: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>banner_get_closest_ride_index -> SignSetNameAction::Execute -> GameActions::Execute -> window_sign_textinput -> window_text_input_mouseup -> input_state_widget_pressed -> game_handle_input_mouse -> game_handle_input -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> wmain</code></td></tr>
</table>

**Comment by janisozaur** [comment]
Probably still happening

**Comment by ZehMatt** [comment]
Its out of bounds, see https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/world/Banner.cpp#L420-L426
