### ISSUE TITLE
Ghost objects show up in the mini-map

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#8385]
**OS:** Windows 8
**Version:** 0.2.1
**Commit/Build:** 5a3efe9

Not sure if this is the way things are intended to be or not, but ghost objects that have not yet been built will show up on the mini-map as if they've already been built.

If this isn't the way things are supposed to work, it seems like it would be fairly easy to fix, just an extra line to check if something has the ghost flag before drawing it on the mini-map.

- [?] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. On a bare map (for visibility)
2. Open the mini-map
3. Prepare to build something large (for visibility)
4. See it on the map before committing to build it.

**Screenshots / Video:**

![2018-12-01 19-53-42](https://user-images.githubusercontent.com/26573303/49630292-6340a800-f9a2-11e8-9106-48d7be3c6727.png)

**Comment by Krutonium** [comment]
Did you mean Windows 8.1?

**Comment by ocalhoun6** [comment]
Yeah, sorry that was a typo.

**Comment by duncanspumpkin** [comment]
This is the way it is meant to work. There was some discussion about whether the colour should be changed.
