### ISSUE TITLE
BACKTRACE cca533 surface_paint -> sub_68B3FB -> paint_session_generate

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8387]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/cca533499d9077bad9bd52093553cf20ef0b9b8eb33f3bb774c350496c70a142?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Fri Dec 07 2018 23:03:26)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> *: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\Stefan\\Documents\\OpenRCT2\\6ba1cd51-a1bc-4e6c-a4fd-f93bb25b0920.sv6.gz: <em>1</em><br><strong>commit:</strong> eeaca61: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>surface_paint -> sub_68B3FB -> paint_session_generate -> window_main_paint -> window_draw -> window_draw_all -> OpenRCT2::Drawing::X8DrawingEngine::DrawAllDirtyBlocks -> OpenRCT2::Drawing::X8DrawingEngine::PaintWindows -> OpenRCT2::Paint::Painter::Paint -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> wmain</code></td></tr>
</table>

**Comment by janisozaur** [comment]
No idea about this one
