### ISSUE TITLE
Breakdown messages show up in (original?) English sometimes

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#839]
See the screenshot. About one out of every ten breakdown messages is in English (probably the original strings), even though the rest are in Dutch.

![scr8](https://cloud.githubusercontent.com/assets/1478678/6284258/6b173bbe-b8ee-11e4-87e6-0df1db31a18a.png)

**Comment by IntelOrca** [comment]
Those recent messages are stored as entirely raw strings as soon as they are generated. Has this saved game always been played in the same language?

**Comment by Gymnasiast** [comment]
No, but the problem is that one out of ten breakdown messages are _generated_ in English. I wasn't talking about storage.

**Comment by IntelOrca** [comment]
Okay, @duncanspumpkin thinks that this is due to a piece of code not being implemented yet which triggers a ride to breakdown - similar to an unimplemented window.
