### ISSUE TITLE
BACKTRACE 2c46ef RideCreateAction::Query -> GameActions::Query

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8404]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/2c46ef33a8c9d7ca3b617deaf45039e5de7d8f31344148e0e43616692df04cee?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Mon Dec 10 2018 00:15:14)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\mwrrf\\OneDrive\\Documents\\OpenRCT2\\902af6d4-fc01-4793-a4a9-ade081a4e50d.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\mwrrf\\OneDrive\\Documents\\OpenRCT2\\902af6d4-fc01-4793-a4a9-ade081a4e50d.sv6.gz: <em>1</em><br><strong>commit:</strong> d980630: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>RideCreateAction::Query -> GameActions::Query -> GameActions::Execute -> Network::ProcessGameCommands -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by ZehMatt** [comment]
This crash is because of this line https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/actions/RideCreateAction.hpp#L104 where rideEntry is nullptr.

I mean the fix seems easy however I'm not sure how to treat this situation. Should it return an error or just ignore the fact it has no entry? Execute would need to be adjusted too then.

**Comment by Gymnasiast** [comment]
A ride without an entry sounds like a can of worms. Better to have it return an error.

**Comment by ZehMatt** [comment]
I would guess that this has something to do with hacked rides. So should I just introduce a new error if the entry is missing?

**Comment by Gymnasiast** [comment]
Well, there is no ride yet - after all RideCreateAction is called, in order to create a new one. That might be because of an error in the New Ride window.

Whatever the cause, a new error message is fine.

**Comment by janisozaur** [comment]
Still happening https://github.com/OpenRCT2/OpenRCT2/blob/381e2c12bcf4b61390ff6bd97f52891f35bde4a6/src/openrct2/actions/RideCreateAction.hpp#L104
