### ISSUE TITLE
Add new station type: no platform

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8407]
Currently there is a object conflict error due to two json objects having the same object ID. That needs to be fixed and the `noPlatforms` attribute needs to be implemented.

**Comment by lwatson2016** [comment]
Has this issue been fixed? What does it involve?

**Comment by AaronVanGeffen** [comment]
Not yet; it cannot be resolved until we've switched to a new save format.

**Comment by Gymnasiast** [comment]
99% can. Working on it involves uncommenting some code in `EditorObjectSelection.cpp` so you can select station objects, making sure the `noPlatforms` property is read in `StationObject.cpp`, and finally modifying the relevant code to not draw the platforms.
