### ISSUE TITLE
Save game failed!

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#8411]
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** 4863b7c

Newest build is quite broken.. When trying to save the game it will fail! Autosaves do seem to work so that is currently the only way to save the game..
![test park 2018-12-10 10-35-49](https://user-images.githubusercontent.com/6469413/49723638-936c9d00-fc67-11e8-8ee4-548dc5569748.png)

**Comment by IntelOrca** [comment]
@deurklink Could you provide more information? I have started a few scenarios and also loaded an old save game and in all cases I am able to save successfully.

**Comment by IntelOrca** [comment]
I just tried the latest build and I am not able to reproduce. If you start the game and then start a new scenario of crazy castle and then save it, does it fail?

**Comment by deurklink** [comment]
It does indeed fail..

**Comment by IntelOrca** [comment]
Okay I have figured how to reproduce it now. It only happens when export objects is enabled.
