### ISSUE TITLE
Rides tab in object selection window is broken

### ISSUE THREAD

**Issue by Umdlye** [OpenRCT2/OpenRCT2#8414]
**OS:** Win10 x64
**Version:** 0.2.1
**Commit/Build:** 85b443f

**Steps to reproduce:**
1. Open object selection window
2. Click rides tab

![2018-12-10_19-03-22](https://user-images.githubusercontent.com/11657101/49751696-5e376d80-fcae-11e8-8d4b-f29dce5195ff.gif)

**Comment by Gymnasiast** [comment]
Likely caused by https://github.com/OpenRCT2/OpenRCT2/commit/4b77d763036abf10474759c9980c72f14aef4dcf .
