### ISSUE TITLE
BACKTRACE 33c323 UserCallWinProcCheckWow'::1'::fin$0

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8419]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/33c323388727f854b4ec0ce1cc320f999d88d57962b10df4e28ffef5e77ab026?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Tue Dec 11 2018 17:53:47)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\\\37777\\37777\\37777\\37777\\37777\\37777\\37777\\37777\\37777\\Documents\\OpenRCT2\\5b94a020-0964-4487-96f3-16bba66bb18f.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\\\37777\\37777\\37777\\37777\\37777\\37777\\37777\\37777\\37777\\Documents\\OpenRCT2\\5b94a020-0964-4487-96f3-16bba66bb18f.sv6.gz: <em>1</em><br><strong>commit:</strong> 9f048c4: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>exception</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>UserCallWinProcCheckWow'::1'::fin$0</code></td></tr>
</table>

**Comment by janisozaur** [comment]
Some Windows' stuff

**Comment by Gymnasiast** [comment]
Well, has it been fixed?

**Comment by IntelOrca** [comment]
@Gymnasiast Not sure what is wrong to be able to fix it. I think it's only worth further investigation if it is a frequent occurrence.
