### ISSUE TITLE
Banner at entrance to queue line not deleted when ride is deleted

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#8426]
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** cf44ea7

Open a park with existing attractions. Delete the rides. On some rides, the banner to the queue will not be removed, and those banners will display no text until a new ride fills that ride slot. 
![image](https://user-images.githubusercontent.com/6469413/49898285-e78aa380-fe58-11e8-9f3a-dff93c0d0c91.png)
Also, the path still stays connected in the direction where the entrance was.

**Comment by deurklink** [comment]
![image](https://user-images.githubusercontent.com/6469413/49898604-bd85b100-fe59-11e8-8d82-298a9f9c31c0.png)
Some guests will still try to queue

**Comment by janisozaur** [comment]
Looks like a regression?
