### ISSUE TITLE
BACKTRACE ca848f Microsoft::CoreUI::Resources::ResourceTracker::TrackWorker

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8432]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/ca848f6686b00dc58b391dd659aa92a5bbb2651436d4a6be63353b66ca4ebe90?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Thu Dec 13 2018 07:57:05)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> *: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> *: <em>1</em><br><strong>commit:</strong> a9a583d: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>Microsoft::CoreUI::Resources::ResourceTracker::TrackWorker -> Microsoft::CoreUI::Messaging::AlpcSendMessageAdapter::BatchedFlush -> Microsoft::CoreUI::Messaging::MessageBatchFlusher::FlushPendingStreams -> Microsoft::CoreUI::Dispatch::EventLoop::Callback_RunCoreLoop -> Microsoft::CoreUI::Dispatch::UserAdapter::OnUserDispatch -> Microsoft::CoreUI::Dispatch::UserAdapter_DoWork -> Microsoft::CoreUI::Dispatch::UserAdapter_WindowProc -> KiUserCallbackDispatch -> ZwUserPeekMessage -> PeekMessageW -> WIN_PumpEvents -> SDL_PollEvent_REAL -> UiContext::ProcessMessages -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment]
No something we can address
