### ISSUE TITLE
BACKTRACE 5eb826 map_obstruction_set_error_text -> map_can_construct_with_clear_at

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8436]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/5eb826d1f1464cb08a1403472b6bbe4d438384a38dd94fc107d1f4f2cd1ddc94?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Fri Dec 14 2018 06:31:28)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\Stefan\\Documents\\OpenRCT2\\9024b49b-38db-4d33-8e25-81e965e68126.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\Stefan\\Documents\\OpenRCT2\\9024b49b-38db-4d33-8e25-81e965e68126.sv6.gz: <em>1</em><br><strong>commit:</strong> 0060c88: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>map_obstruction_set_error_text -> map_can_construct_with_clear_at(int,int,int,int, -> game_command_place_large_scenery -> game_do_command_p -> try_place_ghost_scenery -> top_toolbar_tool_update_scenery -> window_top_toolbar_tool_update -> game_handle_input -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> wmain</code></td></tr>
</table>

**Comment by janisozaur** [comment]
Likely still happening
