### ISSUE TITLE
land style selection box presenting choices out of order

### ISSUE THREAD

**Issue by spacek531** [OpenRCT2/OpenRCT2#8437]
**OS:** [e.g. Windows 10]
**Version:** v0.2.1-214
**Commit/Build:** f8d9127

recent update has changed the order of land tiles when selecting which land tile to use

expected:
![image](https://user-images.githubusercontent.com/3454156/49990140-7a970c80-ff31-11e8-8e09-423c0009509f.png)

actual:
![image](https://user-images.githubusercontent.com/3454156/49990115-605d2e80-ff31-11e8-8fc4-2c42a5bd12a2.png)

(a palette is used in the 2nd image, which is why the green grid is brown)

**Comment by IntelOrca** [comment]
When we have a new save format the user will be able to select which terrains are available and thus the order and selection will be different depending on the scenario so it isn't worth forcing a specific order.

**Comment by spacek531** [comment]
how are they ordered then? object load index? object name?

here are some thoughts based on different assumptions:
- when loading, store the locations of all land tile objects and after loading, organize them into the original order and custom land tiles get sorted behind using a different method
- when importing a park, do the above
- LUT in the drawing code

I don't believe in impossible.

**Comment by IntelOrca** [comment]
It is not impossible, we just see it as unnecessary.

The order is based on the object list order of the scenario which by default is the original RCT2 terrain ID.
