### ISSUE TITLE
BACKTRACE 374bd6 ride_modify -> operator delete -> window_ride_construction_update_state_get_track_element

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8441]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/374bd659e3385b10df7762a31a05c5ffb6caae7e568325c75ec3bf28654aecee?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Fri Dec 14 2018 20:18:44)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\Stefan\\Documents\\OpenRCT2\\f3c99b0c-b222-4c06-9fa8-669e7f9e398c.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\Stefan\\Documents\\OpenRCT2\\f3c99b0c-b222-4c06-9fa8-669e7f9e398c.sv6.gz: <em>1</em><br><strong>commit:</strong> 0060c88: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>ride_modify -> operator delete -> window_ride_construction_update_state_get_track_element -> SDL_ShowCursor_REAL -> context_show_cursor -> game_handle_input_mouse -> game_handle_input -> context_get_cursor_state -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::Launch -> FinalExceptionHandlerPad58</code></td></tr>
</table>

**Comment by janisozaur** [comment]
Most likely still valid, the crash is in https://github.com/OpenRCT2/OpenRCT2/blob/0060c887b72f74003ca26d5719cf2899ef747cfa/src/openrct2/ride/Ride.cpp#L2021 but most likely unchecked tile element in https://github.com/OpenRCT2/OpenRCT2/blob/0060c887b72f74003ca26d5719cf2899ef747cfa/src/openrct2/ride/Ride.cpp#L1285-L1309

**Comment by janisozaur** [comment]
[park-8441.sv6.gz](https://github.com/OpenRCT2/OpenRCT2/files/2824789/park-8441.sv6.gz)
