### ISSUE TITLE
Track designer is bugging out

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#8450]
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** 04c3d9a

When I try to enter the track designer, weird things happen.
- Sometimes it loads normally and works fine
- Sometimes the game outright crashes
- Sometimes it opens but you're not able to select any of the rides, and a large part of the screen will be in weird colors. May also crash at some point.
![image](https://user-images.githubusercontent.com/6469413/50045428-d75e0880-0092-11e9-83bc-73d2648ee182.png)
![image](https://user-images.githubusercontent.com/6469413/50045439-f6f53100-0092-11e9-8272-fc70b6dac988.png)

**Comment by Gymnasiast** [comment]
Bisecting points to one of the changes that @IntelOrca made to the window for https://github.com/OpenRCT2/OpenRCT2/pull/7961 .
