### ISSUE TITLE
Junior booster track piece doesn't connect properly

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#8456]
**OS:**  Windows 10
**Version:** 0.2.1
**Commit/Build:** b915bc3

![image](https://user-images.githubusercontent.com/25930360/50047782-a98db980-00bc-11e9-8c34-2990a1c2e168.png)
This visual glitch only seems to happen when the screen is rotated so that the booster pieces are aligned from the bottom left to the top right or vice versa.

**Comment by duncanspumpkin** [comment]
Is this only a bug in OpenRCT2 and not vanilla?

**Comment by IntelOrca** [comment]
@duncanspumpkin vanilla did not have booster track pieces.
