### ISSUE TITLE
BACKTRACE 77655e rct_peep::UpdateRideAdvanceThroughEntrance -> rct_peep::UpdateRide 

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8462]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/77655e1d3859842ce08ce5c42a18358ce703bf18593ee169c8c3d6167ed27b26?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Sun Dec 16 2018 23:16:15)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\Stefan\\Documents\\OpenRCT2\\d96fd9a8-3037-45ab-96be-ffd8d23dfa98.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\Stefan\\Documents\\OpenRCT2\\d96fd9a8-3037-45ab-96be-ffd8d23dfa98.sv6.gz: <em>1</em><br><strong>commit:</strong> abbdab9: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-write</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>Guard::Assert_VA -> openrct2_assert_fwd -> rct_peep::UpdateRideAdvanceThroughEntrance -> rct_peep::UpdateRide -> rct_peep::Update -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> wmain</code></td></tr>
</table>

**Comment by janisozaur** [comment]
```
#0  0x00007ffff6905d7f in raise () from /usr/lib/libc.so.6
#1  0x00007ffff68f0672 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff68f0548 in __assert_fail_base.cold.0 () from /usr/lib/libc.so.6
#3  0x00007ffff68fe396 in __assert_fail () from /usr/lib/libc.so.6
#4  0x00005555577b8026 in Guard::Assert_VA (expression=false, message=0x5555595ee460 <.str.3> "Peep substate should be LEAVE_ENTRANCE", args=0x7fffffffbd40) at ../src/openrct2/core/Guard.cpp:97
#5  0x00005555577b8325 in Guard::Assert (expression=false, message=0x5555595ee460 <.str.3> "Peep substate should be LEAVE_ENTRANCE") at ../src/openrct2/core/Guard.cpp:67
#6  0x0000555557d1436e in rct_peep::UpdateRideAdvanceThroughEntrance (this=0x55555b73e260 <_spriteList+139264>) at ../src/openrct2/peep/Guest.cpp:3595
#7  0x0000555557d44c5e in rct_peep::UpdateRide (this=0x55555b73e260 <_spriteList+139264>) at ../src/openrct2/peep/Guest.cpp:5074
#8  0x0000555557d63d7a in rct_peep::Update (this=0x55555b73e260 <_spriteList+139264>) at ../src/openrct2/peep/Peep.cpp:1274
#9  0x0000555557d634d9 in peep_update_all () at ../src/openrct2/peep/Peep.cpp:440
#10 0x0000555557659f65 in OpenRCT2::GameState::UpdateLogic (this=0x602000627890) at ../src/openrct2/GameState.cpp:259
#11 0x0000555557658df4 in OpenRCT2::GameState::Update (this=0x602000627890) at ../src/openrct2/GameState.cpp:151
#12 0x000055555761238b in OpenRCT2::Context::Update (this=0x612000156ac0) at ../src/openrct2/Context.cpp:961
#13 0x0000555557610e4d in OpenRCT2::Context::RunFixedFrame (this=0x612000156ac0) at ../src/openrct2/Context.cpp:872
#14 0x000055555760e414 in OpenRCT2::Context::RunFrame (this=0x612000156ac0) at ../src/openrct2/Context.cpp:845
#15 0x000055555760d9a3 in OpenRCT2::Context::RunGameLoop (this=0x612000156ac0) at ../src/openrct2/Context.cpp:816
#16 0x000055555760d554 in OpenRCT2::Context::Launch (this=0x612000156ac0) at ../src/openrct2/Context.cpp:788
#17 0x00005555575ee04a in OpenRCT2::Context::RunOpenRCT2 (this=0x612000156ac0, argc=2, argv=0x7fffffffdb58) at ../src/openrct2/Context.cpp:227
#18 0x0000555556e6cc37 in main (argc=2, argv=0x7fffffffdb58) at ../src/openrct2-ui/Ui.cpp:60
```
Park is enough to reproduce.
[park-8462.sv6.gz](https://github.com/OpenRCT2/OpenRCT2/files/2824778/park-8462.sv6.gz)
