### ISSUE TITLE
Electric Fields Boats Bug

### ISSUE THREAD

**Issue by RugnirViking** [OpenRCT2/OpenRCT2#8467]
**OS:** Windows 10
**Version:** 0.2.1-448
**Commit/Build:** ce3711d on dev branch

When in electric fields, deleting the boat ride leaves the queue line still existing leading to a now unnamed ride in the top of the map.
Testing has shown this behavior is not found in vanilla rct2. The savegame when loaded in rct2 is broken, but performing the same steps from the default electric fields scenario does not cause this issue.

- [ NO ] Reproducible in RCT2 (vanilla)?
- [ NO ] Specific to multiplayer?

**Steps to reproduce:**
1. Open a fresh save of Electric Fields
2. Delete the boat ride
3. Note the queue line still has a sign at the front as if it is a ride queue
4. Click the sign to open a bizzare meta-ride
5. Click the Vehicle Details tab to cause a crash
6. If you now place a **shop** or ride it will become a queue line for that ride, even if it is not connected to the or shop at all. Guests will queue in the line orderly, but when they get to the end they will just leave the line as if the ride were too expensive.
**Dump file**

[1bf573ff-88b5-49a3-bc3b-463dd077f8c1(ce7311d_x86-64).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/2686229/1bf573ff-88b5-49a3-bc3b-463dd077f8c1.ce7311d_x86-64.dmp.gz)

**Screenshots / Video:**

**Save game:**
[1bf573ff-88b5-49a3-bc3b-463dd077f8c1.txt](https://github.com/OpenRCT2/OpenRCT2/files/2686225/1bf573ff-88b5-49a3-bc3b-463dd077f8c1.txt)
This save shows the issue. I have slightly changed the queue line before deleting the boat ride, and it still had the same effect

**Comment by ZehMatt** [comment]
Thanks for the report, however I think this might be a duplicate, see https://github.com/OpenRCT2/OpenRCT2/issues/8426
