### ISSUE TITLE
BACKTRACE 3dd31b vehicle_get_head -> vehicle_update_crossings

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8477]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/3dd31b46f031fbc1d7da2fd6800988467e3081f0756ba9624fbf772198331ab7?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Tue Dec 18 2018 02:38:38)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> E:\\Documents\\OpenRCT2\\ab80b58c-cec0-4ec2-b886-773c3c500c17.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> E:\\Documents\\OpenRCT2\\ab80b58c-cec0-4ec2-b886-773c3c500c17.sv6.gz: <em>1</em><br><strong>commit:</strong> 183e508: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-write</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>Guard::Assert_VA -> Guard::Assert -> vehicle_get_head -> vehicle_update_crossings -> vehicle_update_track_motion_forwards -> vehicle_update_track_motion -> vehicle_update_travelling -> vehicle_update -> OpenRCT2::GameState::UpdateLogic -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment]
Similar to https://github.com/OpenRCT2/OpenRCT2/issues/8231, but not a dupe. Still valid
