### ISSUE TITLE
BACKTRACE fbed11 Object::GetLegacyData -> track_design_mirror_scenery

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8480]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/fbed11eadb9624c32efb13ce6399eba129a3d7a38ac7d5217cee0667ebfeace3?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Tue Dec 18 2018 13:58:05)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\a\\Documents\\OpenRCT2\\731e9d88-3149-404b-a91f-70a1fc49ace7.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\a\\Documents\\OpenRCT2\\731e9d88-3149-404b-a91f-70a1fc49ace7.sv6.gz: <em>1</em><br><strong>commit:</strong> 0060c88: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>unhandled-exception</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>Object::GetLegacyData -> track_design_mirror_scenery -> window_track_place_mouseup -> input_state_widget_pressed -> game_handle_input_mouse -> game_handle_input -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::Launch -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> wmain</code></td></tr>
</table>

**Comment by janisozaur** [comment]
Still valid, see https://github.com/OpenRCT2/OpenRCT2/issues/8535
