### ISSUE TITLE
BACKTRACE 62f05d load_palette

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8488]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/62f05dad4013a4191c42f7a3684394a0b07c55d8760e73dd53a76ee7fe00c7b6?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Wed Dec 19 2018 04:27:10)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>RCT2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\YSL\\Documents\\OpenRCT2\\daefc271-62f6-4d97-aacd-82331942038b.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\YSL\\Documents\\OpenRCT2\\daefc271-62f6-4d97-aacd-82331942038b.sv6.gz: <em>1</em><br><strong>commit:</strong> 183e508: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-write</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>Guard::Assert_VA -> Guard::Assert -> load_palette -> TitleSequencePlayer::PrepareParkForPlayback -> TitleSequencePlayer::LoadParkFromStream -> TitleSequencePlayer::ExecuteCommand -> TitleSequencePlayer::Update -> OpenRCT2::TitleScreen::Load -> window_loadsave_select -> window_loadsave_mouseup -> input_state_widget_pressed -> game_handle_input_mouse -> game_handle_input -> context_handle_input -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment]
This can still happen
