### ISSUE TITLE
Park freezes upon opening

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#8492]
Using v0.2.1-454 38b26e0 on Windows 8

When opening the park found in the attachment, the park freezes within a second. Opening the park while paused does not change that. There is no error message or dump, the game just freezes.

[PT2-Xuan Lu - a Chinese Myth.zip](https://github.com/OpenRCT2/OpenRCT2/files/2694662/PT2-Xuan.Lu.-.a.Chinese.Myth.zip)

**Comment by ZehMatt** [comment]
The reason why this is happening is because some sprite points to its self in the quadrant lists.
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/paint/sprite/Paint.Sprite.cpp#L52

I managed to resolve the freeze by breaking out if the sprite points to its self as the next element but thats not gonna resolve the issue that something sets it like that.

**Comment by IntelOrca** [comment]
This stuff can be recalculated anyway. Just loop through all the sprites and reset their next in quadrant ids.

**Comment by ZehMatt** [comment]
Question is then when should that happen? That feels like working around the actual issue, I'll have a look at this the next few days.

**Comment by IntelOrca** [comment]
This information should be stored in a save file as it is purely for optimisation of the game logic. How it gets into that could be difficult to narrow down and we haven't yet eliminated the possibility of it being from the vanilla game or a trainer.

**Comment by ZehMatt** [comment]
In think in this example we can actually catch the write as it spins for a few ticks before it actually freezes up.

**Comment by ZehMatt** [comment]
Or not, I'm slightly puzzled.

**Comment by 733737** [comment]
this park does not crash or freeze in the latest build.

**Comment by tupaschoal** [comment]
Verified it does not freeze anymore on 0.4.6, thanks @733737 !
