### ISSUE TITLE
Remove_unused_scenery removes map data

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#8493]
Using v0.2.1-454 38b26e0 on Windows 8

When I use the command remove_unused_objects, it removes much more than that. All land tiles disappear and the park becomes an incredible, kinda interesting looking glitchfest. I'm pretty certain this is a bug. It's also done this for every park I tried it with.

Example:
![afbeelding](https://user-images.githubusercontent.com/19242088/50218197-4eddb180-038b-11e9-9236-d5e89ec6c741.png)

**Comment by IntelOrca** [comment]
I think the fix is to prevent the function from touching the surface and station objects. I think saving it and loading the map again will fix your issue though while still removing the unused objects.

**Comment by janisozaur** [comment]
I feel like this is already known, but it's a regression from 06f203a7e70d59f3a79bc2a2f19be890f0233a0a
