### ISSUE TITLE
A new crash (Wednesday

### ISSUE THREAD

**Issue by RT12Productions** [OpenRCT2/OpenRCT2#8503]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.2.1]
**Commit/Build:** [e.g. 426e106]

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by RT12Productions** [comment]
OS:  Windows 10
Version:  0.2.1
Commit/Build:  develop 7568123

Here's a new saved game crash:

[072b3872-ad4e-4725-b983-e846d4dfa336(05ede45_x86-64).dmp.gz](https://github.com/OpenRCT2/OpenRCT2/files/2696916/072b3872-ad4e-4725-b983-e846d4dfa336.05ede45_x86-64.dmp.gz)

Thank You!

**Comment by Gymnasiast** [comment]
Please upload crash reports when the game asks you to, that makes it much easier for us. Also, you didn’t fill in any information.

(The error reports here are likely to be outdated.)
