### ISSUE TITLE
Underground roto-drop is not going up

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#8508]
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** b572fff

Roto-drop that is built in underground is not going up and tend to keep in underground

**Screenshots / Video:**
![zyro](https://user-images.githubusercontent.com/10726524/50324694-dfe79080-0523-11e9-9c7e-92f6e55292c2.gif)

**Comment by Gymnasiast** [comment]
Most likely caused by the code searching for the tile element above and finding a surface element instead of a track element.

Could you upload an affected save? Makes it easier for me to investigate than trying to replicate it myself.

**Comment by telk5093** [comment]
[mega.zip](https://github.com/OpenRCT2/OpenRCT2/files/2703728/mega.zip)
Here you are
