### ISSUE TITLE
BACKTRACE 4d7db8 `safe_strcpy -> window_server_start_open`

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8510]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/4d7db81a6fc49d7edd1e976d1012090903d44388c0a8d32677e4bead6e90afe2?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Fri Dec 21 2018 06:09:55)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\Lesly\\Documents\\OpenRCT2\\52f657ec-6c92-4916-8fdd-50987ec48e6a.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\Lesly\\Documents\\OpenRCT2\\52f657ec-6c92-4916-8fdd-50987ec48e6a.sv6.gz: <em>1</em><br><strong>commit:</strong> ec06a9a: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>WindowManager::OpenWindow -> context_open_window -> input_state_widget_pressed -> game_handle_input_mouse -> game_handle_input -> context_handle_input -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2 -> SbpDeterimineDllContext</code></td></tr>
</table>

**Comment by ZehMatt** [comment]
I recall fixing this, can't find the PR.
