### ISSUE TITLE
BACKTRACE fb5c66 Json::FromString -> std::_Func_impl_no_alloc<,void,OpenRCT2::Network::Http::Response 

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8511]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/fb5c662eddc0165636b32e0fdb8aad7cbd44c2f737da6d5fda4fe2c5baf1a0ec?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Fri Dec 21 2018 09:39:16)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.com</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> D:\\trash\\desctoptrash\\executables\\openrct2\\srv\\\\b8118f07-228a-4869-9e8a-cc9f859c4373.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> D:\\trash\\desctoptrash\\executables\\openrct2\\srv\\\\b8118f07-228a-4869-9e8a-cc9f859c4373.sv6.gz: <em>1</em><br><strong>commit:</strong> ec06a9a: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>unhandled-exception</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>Json::FromString -> std::_Func_impl_no_alloc<<lambda_d66adf5fb8c0b7959d3f40695bfcd6bf>,void,OpenRCT2::Network::Http::Response &>::_Do_call -> std::_LaunchPad<std::unique_ptr<std::tuple<<lambda_b4dc34ea0f811813b0e5ae2ef13b6161> >,std::default_delete<std::tuple<<lambda_b4dc34ea0f811813b0e5ae2ef13b6161> > > > >::_Go -> std::_Pad::_Call_func -> thread_start<unsigned int (*)(void *)></code></td></tr>
</table>

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/381e2c12bcf4b61390ff6bd97f52891f35bde4a6/src/openrct2/core/Json.cpp#L63 thrown in a lambda and left uncaught
