### ISSUE TITLE
BACKTRACE 09f020 Object::~Object -> SmallSceneryObject::scalar deleting destructor' -> ObjectManager::UnloadAll

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8517]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/09f02073e0b6eaa5e7745951a62159145a019fa4995eba9ea4eb34b39732d148?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Sat Dec 22 2018 06:18:46)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>openrct2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\user\\Documents\\OpenRCT2\\4d6d9b6c-6382-4df5-bc74-7a88ef25bb2b.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\user\\Documents\\OpenRCT2\\4d6d9b6c-6382-4df5-bc74-7a88ef25bb2b.sv6.gz: <em>1</em><br><strong>commit:</strong> 73345b4: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy_deallocate -> Object::~Object -> SmallSceneryObject::scalar deleting destructor' -> ObjectManager::UnloadAll -> Editor::Load -> window_title_menu_dropdown -> input_state_widget_pressed -> game_handle_input_mouse -> game_handle_input -> context_handle_input -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by IntelOrca** [comment]
I don't think the park would be useful as it looks like the crash happened when entering the scenario editor?

**Comment by janisozaur** [comment]
Yes, it appears that way, but the park still is invalid and we should handle it gracefully.

**Comment by janisozaur** [comment]
In one of the duplicates, https://github.com/OpenRCT2/OpenRCT2/issues/8487, the call stack is a bit different:
`gfx_object_free_images -> RideObject::Unload -> ObjectManager::UnloadAll -> OpenRCT2::Context::~Context -> OpenRCT2::Context::scalar deleting destructor' -> NormalisedMain -> LaunchOpenRCT2`

**Comment by janisozaur** [comment]
This (and) duplicates seem to be caused by one of the commits to scenario editor/the way the objects were loaded that was already reverted (can't find exactly which commit that was). There is still a park that is causing a crash mentioned in a comment above, but I will submit a separate issue for that.
