### ISSUE TITLE
OpenRCT2's sound issue

### ISSUE THREAD

**Issue by pGore33p** [OpenRCT2/OpenRCT2#852]
So I use very good DJ headphones (KOSS Porta-Pro they are the best) and I suddenly heard very loud cracks... wasn't able to get to the rest of the game itself. They are loud and it wanted my ears explode, seriously. I frightened wtf was happening with the game and I went to hospital (no joking here, I had headaches and stayed a night). I don't know what happened in the game I didn't change anything... nothing in the settings, checked the audio drivers... no issue... no programs were running (except skype) This happened yesterday at night and just now I am back, might not go to school tommorow.

**Comment by zsilencer** [comment]
This happened how long after playing or right when you opened the game up?  Were all sounds cracks or only some, such as you could hear rides or music still?  There is a known issue with this in my tests but only happened when the audio output needed to be converted, see my comment in mixer.cpp.  At the time it seemed to be a off by one error somewhere, as it would load samples starting from the offset just before where it was done in the previous callback.

**Comment by pGore33p** [comment]
Well, czech republic takes everything seriously didn't hurt too much but it was so loud! I am scared to open the damn game again. It was just when I opened the game, wasn't able to get anywhere tho... if you are wondering, no I don't know which audio driver I used. I am using Realtek HD Audio. Still dunno if this is fault of the game or the audio itself, I need to examine that.

Also one thing: I can't open the game.

**Comment by RollingStar** [comment]
@pGore33p, that's an awful issue. I suggest limiting the maximum volume on your computer when listening through headphones, and only using headphones for software that is thoroughly tested and well-trusted. Since OpenRCT2 is still in development, it might be a bad idea to use headphones with it.

**Comment by pGore33p** [comment]
The volume was set to 20 and also sorry I use them frequently so taking them off for just one game is obnoxious. They work very well and I have them 2 years.
