### ISSUE TITLE
BACKTRACE 8c3257 snprintf -> DataSerialiser::operator<< -> FootpathRemoveAction::Serialise

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#8522]
<table>
    <tr>
        <td><img src='https://backtrace.io/images/icon.png' width=30 height=30 /></td>
        <td><a href='https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/8c32570d259ea6ad32419591d2b4024062b6ada075d758f79778c18e3db70a5d?_t=W3sibmFtZSI6IndvcmtmbG93In1d'><b>New unique error: [openrct2]</b></a><br /><b>1</b> occurrence(s) <b></b> since (Sat Dec 22 2018 09:53:25)<br /></td>
    </tr>
</table>

<table>
<tr><td><strong>Application</strong></td><td>RCT2.exe</td></tr>

<tr><td><strong>Attributes</strong></td><td><strong>attachment_park.sv6:</strong> *: <em>1</em><br><strong>attachment_config.ini:</strong> C:\\Users\\k2000\\Documents\\OpenRCT2\\881bb6a8-30db-4e1b-842f-523fa8647d56.ini: <em>1</em><br><strong>attachment_park.sv6.gz:</strong> C:\\Users\\k2000\\Documents\\OpenRCT2\\881bb6a8-30db-4e1b-842f-523fa8647d56.sv6.gz: <em>1</em><br><strong>commit:</strong> 73345b4: <em>1</em><br></td></tr>
<tr><td><strong>Classifiers</strong></td><td><strong>invalid-read</strong> </td></tr>
<tr><td><strong>Frames</strong></td><td><code>common_vsprintf<__crt_stdio_output::standard_base,char> -> vsnprintf -> snprintf -> DataSerialiser::operator<<<int> -> FootpathRemoveAction::Serialise -> GameActions::Execute -> game_handle_input_mouse -> game_handle_input -> context_handle_input -> OpenRCT2::GameState::Update -> OpenRCT2::Context::Update -> OpenRCT2::Context::RunVariableFrame -> OpenRCT2::Context::RunGameLoop -> OpenRCT2::Context::RunOpenRCT2 -> NormalisedMain -> LaunchOpenRCT2</code></td></tr>
</table>

**Comment by janisozaur** [comment]
@ZehMatt want to take a look?

**Comment by ZehMatt** [comment]
The mdmp is somewhat puzzling, it crashes in realloc and all pointers look more or less okay at this point. I'll try to reproduce it somehow
