### ISSUE TITLE
Vertical Edges Not Showing

### ISSUE THREAD

**Issue by rpstester** [OpenRCT2/OpenRCT2#8524]
**OS:** Windows 10, 1803
**Version:** v0.2.1-474 
**Commit/Build:** (2530cd1 on develop)

I just noticed that when I try to add vertical edges to land, that only the plain, wood, black wood, and ice are showing.  If I try to apply any other edge, such as stone, metal, colored wall, skyscraper, etc. it charges me the money but doesn't change.  

Also, the game displays only those four existing edges.  I can load a scenario such as Razor Rocks that should have the grey walls, but they appear as normal dirt walls.  This is happening on new scenarios as well as saved games.  

I could be mistaken, but I think these were the only four edges available in all of RCT2.  In that case, the edges I am not seeing are the ones brought over from RCT1.  The "release" version of oRCT2 only has the original four available.  

I thought for sure the new vertical land faces were working earlier this week, but I could be wrong.  

Reproducible in RCT2 (vanilla)?  No
Specific to multiplayer? No

**Steps to reproduce:**
1.  Open a park in oRCT2 "develop"
2.  See the new land choices
3.  Try to apply one - does not change, but charges money

Please let me know if you have any questions.

**Comment by Gymnasiast** [comment]
These only work if you have RCT1 linked to OpenRCT2. Previously, these were hidden if you didn't, but recent changes broke this behaviour.

**Comment by IntelOrca** [comment]
It is because we now use JSON files to get the information necessary to display the surface images which you didn't have due to the PPA not distributing them.

**Comment by Gymnasiast** [comment]
@intelorca What are you talking about? This user clearly says he's on Windows. And if the objects were missing, no terrain would work - the user only has non-working RCT1 edges.

@rpstester Then you probably linked the base game - OpenRCT2 only works with LL or Deluxe.

**Comment by IntelOrca** [comment]
@Gymnasiast I am getting this mixed up with the Ubuntu issue.

**Comment by StrangeAnomoly** [comment]
Just to add to this, this only appears to affect a small amount of Users.
I am running Windows 7 Pro, have RCT1 installed and linked to OpenRCT and I do not have this issue.

**Comment by Gymnasiast** [comment]
@StrangeAnomoly It affects users who do not have RCT1 linked. That's not really a small amount. The problem is that OpenRCT2 used to hide the extra land edges if the user did not have RCT1 installed.

**Comment by StrangeAnomoly** [comment]
@Gymnasiast 
Oh, okay, nice to know. I didn't realise this was actually the issue here.
I stand corrected!

**Comment by rpstester** [comment]
Sorry to bring this up again, but I'm noticing it more as I play through Corkscrew Follies.  In Haunted Harbor, there should be vertical edges with doors on the ghost train (tunnel of horror). See the RCT Wiki for a [screenshot](https://rct.fandom.com/wiki/Haunted_Harbour/Scenario_Guide?file=Haunted_Harbor_RCT_2.jpg).  On my installation of OpenRCT2, it's just dirt.

I was wondering if this (edges with automatic doors) has been implemented in OpenRCT2 yet.  I have linked my installation to RCT1 with Loopy Landscapes installed on my machine, and I have those tile edges available, as I said, but they don't show.  Should I expect to see the original CF/LL edges manifest in OpenRCT2?
Thank you.

**Comment by Gymnasiast** [comment]
The doors have not been implemented in OpenRCT2, but the edges should still show up as stucco, not dirt.

To repeat my earlier question: which version of RCT1 have you linked? It's most likely that you have the base game linked, rather than RCTLL/RCT Deluxe.

**Comment by rpstester** [comment]
@Gymnasiast as I said I have RCT with Loopy Landscapes.  I bought the original game, and then I bought LL which includes Corkscrew Follies.  I only have one RCT1 folder on my computer.  Is there a screenshot I can show you to demonstrate what I have?

**Comment by Gymnasiast** [comment]
Could you check if CSG1i.dat (note the extra 'i') is present in the RCT1\\Data folder on your hard drive? If not, copy it from the RCT1 LL CD and try again.

If that doesn't help, could you provide me with:
- The contents of the `rct1_path` variable in `C:\Users\YouName\Documents\OpenRCT2\config.ini`
- The size of your CSG1.DAT or CSG1.1 file?

**Comment by rpstester** [comment]
I copied the file as you said, and here is what a get now, a big improvement:
![image](https://user-images.githubusercontent.com/32249806/52159017-d4cc6800-266c-11e9-9179-36b02480207f.png)
Thanks!  That's what I was looking for!

**Comment by Sakraloperette** [comment]
YES!!!!!! @Gymnasiast Thank you so much. FINALLY!!!!

**Comment by AaronVanGeffen** [comment]
Okay, so luckily there is no bug. We should probably show a popup or something if the file cannot be found when the folder is set, though.

**Comment by Gymnasiast** [comment]
@AaronVanGeffen In addition, we should show a warning if the RCT1 assets are requested, but cannot be loaded (whether an RCT1 path is set or not).

**Comment by Sakraloperette** [comment]
@Gymnasiast the link check will not suffice though. I had the problem though I had installed rct1, aa, ll, all rct2 games (and everything with the „complete installation“ setting) and after that started openrct2, linked rct1. It seems that in some installations (min are the original ones from 1999, germany) this csgi file isnt copied from the cd in full installation.

**Comment by AaronVanGeffen** [comment]
@Sakraloperette Exactly, yes. Thanks for elaborating on your situation ­— I think we're on the same page! :)

**Comment by Gymnasiast** [comment]
@Sakraloperette 

> the link check will not suffice though.

Hence why I propose showing a warning when the asset files are not loaded, despite the sprites being requested. As I said, that works whether the RCT1 files are linked correctly or not.

> this file is mandatory.

Not quite. You can play OpenRCT2 without this file and even open RCT1 files with it (though with degraded experience, as is obvious from this bug report).

**Comment by Sakraloperette** [comment]
@Gymnasiast 

> Hence why I propose showing a warning when the asset files are not loaded
yeah, sorry, I misread your comment.

> Not quite
well, as you say yourself its a degraded experience. Further, there is no error shown, it just costs money to paint the edges and seeing nothing. So I would say its mandatory to have that file in order to have a full functioning game. 
But lets not nitpick on our choice of words. I'm very glad you guys fixed my game and that I can enjoy playing it from now on! So thanks again! Keep up the good work!

**Comment by Gymnasiast** [comment]
OpenRCT2 will now hide any land edge that hasn't got its images loaded.

In addition, I have opened issue #8857.
