### ISSUE TITLE
Surface and wall tiles seem to not be displaying

### ISSUE THREAD

**Issue by RQWorldblender** [OpenRCT2/OpenRCT2#8527]
**OS:** Ubuntu 18.04
**Commit/Build:** Any build after 06f203a7e70d59f3a79bc2a2f19be890f0233a0a

Surface and wall tiles seem to not be rendering at all, causing anything that should be closed to remain, unless something else (footpaths, scenery, and rides) draws over where there would be land. Additionally, the land tool doesn't display any tiles, not even the default ones. I believe all this is happening due to #8405. The track designer and track manager seem to be unaffected, as long as I don't scroll to the terrain edges, where they will not draw, and the drawing errors will occur as usual.

- [ ] Reproducible in RCT2 (vanilla)? No
- [ ] Specific to multiplayer? No

**Steps to reproduce:**
1. Just open the game.
2. The drawing errors are present as soon as the main menu is present.

**Screenshots / Video:**
![forest frontiers 2018-12-16 01-50-07](https://user-images.githubusercontent.com/13372387/50379762-02f36c80-0618-11e9-9a79-d5b5ceda5e39.png)

**Comment by IntelOrca** [comment]
You need to update your objects, the ones that are distributed with the game.

**Comment by RQWorldblender** [comment]
I don't know which objects, and where they are located. I used to have to not do additional work before 12/10, so it's a surprise to me.

**Comment by Gymnasiast** [comment]
@IntelOrca There could be a bug in the PPA.

**Comment by Gymnasiast** [comment]
Has now been fixed.
