### ISSUE TITLE
Feature Request: Automatically purchase land

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#8534]
**OS:** Windows 8
**Version:** 0.2.1
**Commit/Build:** 2530cd1

In scenarios where buying land is an important step, it could be much more convenient (and efficient) to have the option to automatically buy the land whenever you try to build something on land that's for sale. (Or also buy construction rights when applicable.) Basically the same way that scenery is automatically cleared out of the path of what you're building.

There are three different ways I can think of this being implemented:

1: A checkbox in the land purchasing window that would act as a third land-buying mode (as opposed to the buy land/buy construction rights options already there). Select this mode, and the land will automatically be purchased when you try to build anything on it. This implementation would have to be deliberately turned on every time you want to use it by first opening the land purchasing window. The purchase price listed in the land purchasing window would be calculated based on how many squares of land you're about to buy if you build the current ghost object.

2: A permanent setting in the options menu that you can turn on and off, letting it become more like the way trees are automatically removed from the path of the ride you're building -- something you usually don't have to think about.

3: A checkbox in the ride/path/scenery construction windows, which may or may not stay persistently selected after closing and re-opening those windows. Then, with the 'automatically buy land if necessary' option checked, the land purchase price would be added to the price of building whatever item you're trying to build on for-sale land. This one is more complicated, but it has an advantage in that if (for example) you want to automatically buy land for ride construction but _not_ for path or scenery construction, you'd be able to do that.

It seems like a feature that would save a lot of time and effort in certain scenarios -- might also save some money by making it easy to buy only the land you need, rather than large blocks at a time or selecting single squares one at a time. If it's felt that it stretches the game mechanics/economics too far, then it might be best to use option number 2 above, or even put it in the cheats menu. But I think it's a feature that could be one more way for OpenRCT2 to be better than all the alternatives.

Additional considerations:
- If using option 3 above, you might want to have it display the for-sale land markers like it does when you open the land purchasing window whenever the option is turned on.
- Under any of the options, it might be useful to have the virtual floor feature begin to distinguish not only between owned land and non-owned land, but also have a different way to display land that's for sale.

**Comment by Patrik356b** [comment]
Should be a plugin I think.

**Comment by Krutonium** [comment]
While I agree it would make a good plugin, I think it also needs a hair more balance - like buying 3 blocks in every direction for every purchase - You would never purchase JUST the square meter your thing is going on.

**Comment by harrysbird** [comment]
They should add Plugin API after new save format come out. 
but this is good idea.

**Comment by chaitanyathengdi** [comment]
> While I agree it would make a good plugin, I think it also needs a hair more balance - like buying 3 blocks in every direction for every purchase - You would never purchase JUST the square meter your thing is going on.
"Never" is a strong word - I did just that when I was building a long railroad and needed to buy land in a corner, which I would otherwise ignore.
