### ISSUE TITLE
Issue:  Fun Spot Emporia (a fictional park in Emporia, Virginia, U.S.A.)

### ISSUE THREAD

**Issue by RT12Productions** [OpenRCT2/OpenRCT2#8536]
**OS:**  Windows 10
**Version:**  0.2.1
**Commit/Build:**  develop-476-16b9c53

When I was playing with the scenario/saved game _Fun Spot Emporia_ on **OpenRCT2**, after I build a few new rides, and attempt to save the saved game, it then crashes.

**Comment by janisozaur** [comment]
How about you post the park in question?

**Comment by janisozaur** [comment]
Or basically any details as to what happened?
