### ISSUE TITLE
detect RCT1 disc install

### ISSUE THREAD

**Issue by Sunlitspace542** [OpenRCT2/OpenRCT2#8540]
Could you please add a feature to detect RCT1 disc install on startup?

**Comment by Gymnasiast** [comment]
We already do that. If it fails to auto-detect, you can set a path in the Options window.

Do note that you will have to manually copy CSG1i.DAT from the CD to your hard disk in order for the RCT1 sprites to work. This is not copied by the RCT1 CD installer.
