### ISSUE TITLE
DISABLE_OPENGL Doesn't Work

### ISSUE THREAD

**Issue by dchokola** [OpenRCT2/OpenRCT2#8542]
**OS:debian buster/sid**
**Version:v0.2.1-483-g153ab1542**
**Commit/Build:153ab1542**

`cmake -DDISABLE_OPENGL=1` does not actually disable SDL/OPENGL build-time requirement.

A headless server shouldn't link to graphical libraries.

**Comment by dchokola** [comment]
I made a "works for me" patch against latest develop branch (v0.2.1-483-g153ab1542):

[headless.patch.txt](https://github.com/OpenRCT2/OpenRCT2/files/2717703/headless.patch.txt)

**Comment by janisozaur** [comment]
Will you make a PR?
