### ISSUE TITLE
Incorrect design names

### ISSUE THREAD

**Issue by Hezkore** [OpenRCT2/OpenRCT2#8544]
Windows 10
OpenRCT2, v0.2.1-482 (8721bef on develop)

I'm new to RCT1 and RCT2, but I believe the RCT1 rides all have incorrect names when selecting an existing design.
Most of them have the name `"u(xxx)"` where xxx is some random number.

**Steps to reproduce:**
1. Add RCT1 via `--rct1-data-path` as well as RCT2 via `--rct2-data-path`
2. Place a ride and select an existing design for it

![openrct2_2019-01-01_04-22-03](https://user-images.githubusercontent.com/1727541/50570149-90a02c00-0d7d-11e9-853f-561186d204f0.png)

**Comment by Patrik356b** [comment]
This also applies to manually copy-pasting the tracks from rct1 to the tracks folder for OpenRCT2 (which is what I have done)

**Comment by Gymnasiast** [comment]
RCT1 Deluxe comes with user-supplied track designs that are named liked this. It's easily visible if you look in RCT1's Tracks folder.
