### ISSUE TITLE
Money effect sometimes not rendered with OpenGL renderer

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#8547]
Sometimes its not visible sometimes it is.

**Comment by Hezkore** [comment]
I don't think I've ever seen money effect render even once when using OpenGL.
I thought it was one of the missing features.

**Comment by DevNebulae** [comment]
@Hezkore You can, you just need to look which side the entrance is facing. See my investigation on issue #8582 (which is now merged with this one).
