### ISSUE TITLE
Scenery removal tool removes fences and paths while paused

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#8553]
While the game is paused, the scenery removal tool is able to get rid of fences and paths (when removing paths is enabled), but not small scenery or large scenery. Looks like a little bug to me! Removing fences only can be a useful thing I'm sure, but that could be implemented in another way. :P

v0.2.1 31298bd on Windows 8

**Comment by Gymnasiast** [comment]
We should probably also split out small scenery and walls (and just default to having both enabled by default) in the Clear Scenery tool.

**Comment by lwatson2016** [comment]
Is the ideal behavior here for the scenery removal tool to remove nothing when the game is paused?

**Comment by duncanspumpkin** [comment]
Does this still happen?

**Comment by aw20368** [comment]
@duncanspumpkin I checked that this no longer happens on latest develop.
![PauseSceneryRemove](https://user-images.githubusercontent.com/29646196/59165191-060ae800-8ae6-11e9-97a1-b3281314ec07.png)
