### ISSUE TITLE
Vehicle Design/Scenary Unavailable

### ISSUE THREAD

**Issue by D1JL** [OpenRCT2/OpenRCT2#8569]
This may have been asked before however, I searched and found no referance.

Many of the pre-maid coasters available, there is a discloser at the bottom of the picture window. 
(Design Includes Scenery Which Is Unavailable) 
(Vehicle Design Unavailable - Ride Performance May Be Affected) 
Is there a way to see what is required to view these rides in the manner that the designer intended? 
Sometimes it is good to learn other's techniques. 
Thanks, 
Dave

**Comment by jensj12** [comment]
Duplicate of #5860.
