### ISSUE TITLE
Block brake speed

### ISSUE THREAD

**Issue by monsterrideop** [OpenRCT2/OpenRCT2#8570]
**OS:** Linux OpenSuSE Tumbleweed
**Version:** 0.2.1-1.2
Installed via OS repository.

Feature request: Add a speed setting to the block brakes.
I don't even know if it is possible but it would allow for a more "real" feel to the coasters as many do not slow down when they hit their block brake sections.

**Comment by AaronVanGeffen** [comment]
For what it's worth, https://github.com/OpenRCT2/OpenRCT2/pull/7737 is adding this, but the PR is on hold for now.
