### ISSUE TITLE
Error in Station.cpp

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#8571]
Line 107:
```
            if (vehicle->var_CE < dh || (vehicle->var_CE < dh && vehicle->sub_state > dl))
```
This logic is quite odd.
It wasn't always like this though:
```
			if (dh > vehicle->var_CE)
				continue;

			if (dh < vehicle->var_CE) {
				ride->lifecycle_flags &= ~VEHICLE_STATUS_WAITING_TO_DEPART;
				dh = 0;
				sub_6AC2AF(ride, stationIndex, dl);
				return;
			}

			if (dl > vehicle->var_51)
				continue;
```
Source of the latter example: https://github.com/OpenRCT2/OpenRCT2/commit/cf59455d6914de47b095ef974eb0f9b8d76056cc#diff-25c5ab1d9a52d4cd6bc3be9b7140ce43R140

**Comment by IntelOrca** [comment]
Hard to determine how odd it is when there are so many unknown variables.

**Comment by Gymnasiast** [comment]
Well, there are, but the line on top boils down to:
```
if (a || (a && b)
```
I would call that odd. It's equivalent to `if (a)`, but that's not what the older code does.

**Comment by IntelOrca** [comment]
The old code is odd as well. I assume `vehicle->var_51` is `vehicle->sub_state`.
The old code:
```
    if (dl > vehicle->var_51)
        continue;
```
is at the bottom of the loop so that part is complete redundant.
