### ISSUE TITLE
ATM Machines

### ISSUE THREAD

**Issue by acrossthestars07** [OpenRCT2/OpenRCT2#8575]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.2.1]
**Commit/Build:** [e.g. 426e106]

Hello! Love this version of Roller Coaster Tycoon!
I've been playing the original scenarios using Open RCT2, and I was wondering if there was any way ATM machines could be added under Shops/Stalls. I know this shop was designed for RCT2, but it would be awesome if I could implement it in the original. Speaking of which, is there any way that more shops/stalls can be added to different worlds, or is there a way you can pick the ones you want? I have no idea if that's possible as I'm not by any means a computer/coding expert. I just thought I'd ask. 

Thanks so much!

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by jensj12** [comment]
In the options, enable debugging tools. Then in-game, you’ll find two cogs in the top toolbar. Open object selection there and enable the ATM.

**Comment by Patrik356b** [comment]
Can I ask why they have been hidden?

**Comment by Gymnasiast** [comment]
@Patrik356b Nothing is hidden. The original RCT1 scenarios did not come with ATMs, so OpenRCT2 will not magically make them available.

**Comment by Patrik356b** [comment]
Ah. I misinterpreted this.

**Comment by arwerchan** [comment]
Did this feature to toggle cash machines get removed? Enabling debugging tools does not allow me to select an "Open object selection" option under the two cog icon toolbar.  Running build version "OpenRCT2,  (14184ab) Linux (x86-64)"

**Comment by duncanspumpkin** [comment]
We moved object selection from the debugging tools dropdown to the cheat tools dropdown as it was being used for more than debugging. You will find it under the golden shovel dropdown.

**Comment by arwerchan** [comment]
> We moved object selection from the debugging tools dropdown to the cheat tools dropdown as it was being used for more than debugging. You will find it under the golden shovel dropdown.

Thanks for the update.  I see the golden shovel for the cheats, but I don't see any options pertaining to enabling ATM/cash machines.  Perhaps the scenario I had loaded did not support that? I only saw the cheat option to give guests money directly.
