### ISSUE TITLE
Booster pieces for water coaster missing

### ISSUE THREAD

**Issue by F0ndue** [OpenRCT2/OpenRCT2#8583]
**OS:** Windows 10
**Version:** 0.2.1-591
**Commit/Build:** 746feaa

Pretty selfexplanatory: the implementation of booster pieces for the water coaster would be greatly appreciated. Gymnasiast instructed me to submit this issue after I talked to him on the New Element Discord.

**Comment by ocalhoun6** [comment]
While we're at it ... I seem to remember the water coaster having banked inclined turns available, but it doesn't now. Am I mis-remembering it? (That's entirely possible; maybe it's the mini steel coaster I'm thinking of.)

**Comment by Patrik356b** [comment]
@ocalhoun6 Afaik the sprites necessary do not exist for this train type

**Comment by Gymnasiast** [comment]
Now implemented (thanks @deurklink !)
