### ISSUE TITLE
Ducks are not spawning!

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#8584]
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** 746feaa

Ducks no longer seem to spawn!

**Steps to reproduce:**
1. Create large body of water (code says you need at least 25 tiles of water at same height in a 7x7 area)
2. Wait forever
3. No ducks seem to spawn

**Comment by Gymnasiast** [comment]
Heavens, no! We must fix this immediately!

**Comment by deurklink** [comment]
That's interesting, because I thought they always have a water body as target.. Could it be that the coordinates are somehow wrong?

**Comment by tomlankhorst** [comment]
The month must be < APRIL

https://github.com/OpenRCT2/OpenRCT2/blob/92412d4bab085fe5adbdac80f67af4a50d2fab98/src/openrct2/scenario/Scenario.cpp#L332-L341

**Comment by deurklink** [comment]
Yes I know that, I only check in March and April

**Comment by janisozaur** [comment]
But `april < april` does not hold.

**Comment by AaronVanGeffen** [comment]
> But `april < april` does not hold.

`april <= april` does, fortunately. ;)

**Comment by janisozaur** [comment]
I see the earlier comment got amended to fix that. Indeed, the code linked has LE, rather than LT, but I overlooked that.

**Comment by tomlankhorst** [comment]
@deurklink But you haven't seen any ducks? 

If you're building from source you could set a breakpoint at `openrct2/scenario/Scenario.cpp:425` to see what happens when the game tries to create the ducks.

**Comment by deurklink** [comment]
I know, and I already played a bit with that to see what would happen, but not enough to draw any conclusions from it yet

**Comment by tomlankhorst** [comment]
Well, I wonder, does it ever come to line 465? Then it should draw ducks. 
If it doesn't, but it comes to line 461, no (found) water is big enough.
  ,, ,,  line 443, no (found) water height is zero.
  ,, ,,  line 438, no (found) water is in the park.

Of course, it might be less simplistic than that but that should at least point out where the logical flaw is.

**Comment by ZehMatt** [comment]
Another important factor is that the tiles are randomly selected if you don't have a lot of water then its less likely they will spawn.

**Comment by deurklink** [comment]
One map I tested on was Leafy Lake.. That one should have enough water, right?

**Comment by ZehMatt** [comment]
You still have to consider when I'm talking random tile it literally picks a random value for x and y within the range of the entire map not just within your park and that only happens once per game week, so yes and no?

**Comment by tomlankhorst** [comment]
@ZehMatt, well, the current implementation spends a maximum of hundred tries to find a single suitable tile for spawning, so in practice, this should often be successful in a water-rich map. 

@deurklink To be certain, you are looking for them on the closest zoomlevel, right? What's on line 9 of your `object/rct2/water/rct2.wtrcyan.json` in the data directory? 

```json
"allowDucks": true,
```

**Comment by tomlankhorst** [comment]
Interesting investigation @deurklink, could it be a not-so-sane random
number generator for the scenario ?

**Comment by deurklink** [comment]
OK I think i found an issue.. The tile coordinates it generates all start are all between 64 and 255-64. To illustrate what that means in Forest Frontiers, the icy area is where the game will never check for water to create ducks at.. 
![image](https://user-images.githubusercontent.com/6469413/51437087-3f5acc80-1c99-11e9-8abc-7e7662a41c12.png)

**Comment by deurklink** [comment]
And here's Leafy Lake.. 
![image](https://user-images.githubusercontent.com/6469413/51437123-eb9cb300-1c99-11e9-9623-8b44ddc54320.png)
I think we've found the root of the ducks issue 😁

**Comment by deurklink** [comment]
OK I replaced the original code for coordinate generation:
```
    r = scenario_rand();
    x = (scenario_rand() & 0xFF) * 32;
    y = (scenario_rand() & 0xFF) * 32;

    //original code:
    //x = ((r >> 16) & 0xFFFF) & 0x7F;
    //y = (r & 0xFFFF) & 0x7F;
    //x = (x + 64) * 32;
    //y = (y + 64) * 32;
```

And look at that! A leafy lake full of ducks!
![image](https://user-images.githubusercontent.com/6469413/51437218-89dd4880-1c9b-11e9-880f-53be2742e740.png)

**Comment by tomlankhorst** [comment]
This is great. Seems like a sign issue to me.

Maybe comment on the magic

**Comment by deurklink** [comment]
Actually, it seems to be intended (hence the x+64 part). I just checked in vanilla rct2 and it looks like an original bug (or intended behaviour). In Crazy Castle, for example, the ducks only stick to a small corner of the map.

**Comment by Gymnasiast** [comment]
Reopening since the fix has been reverted (it caused crashes).
