### ISSUE TITLE
guest list

### ISSUE THREAD

**Issue by acrossthestars07** [OpenRCT2/OpenRCT2#8588]
-->
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** 8ac731e

Hello! 
I seem to be encountering a problem when viewing the guests in the Guest Window. When I scroll down the lowest I can go, I cannot see all of my guests. Even when I expand the window, the lowest it will go is to the "R" names. I took a screenshot to show you. I get the same problem when I select individual guest's thoughts as well. 
Any thoughts on what I can do to fix this? 

Thanks so much!
  Fill in the placeholders below. Delete any headings and placeholders that you do not fill in.
![volcania 2019-01-14 04-36-04](https://user-images.githubusercontent.com/43876284/51108117-aa4a6600-17b6-11e9-99a1-3c74e515ac7c.png)

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. 
2. 

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by Gymnasiast** [comment]
You didn't fill in the form correctly. The version and build hash are especially important.

**Comment by acrossthestars07** [comment]
Sorry about that!
I have the latest version available: 0.2.1 build 8ac731e
Is that all you needed? Not sure what the build hash is unless I entered it just now with the version. Let me know. Thanks!

**Comment by Gymnasiast** [comment]
8ac731e is indeed a build hash.

0.2.1, build 8ac731e is indeed the latest _release_ version. However, we also have "develop" builds. Could you try switching to it to see if it solves the problem? If you use the OpenRCT2 Launcher, look in the options. If you're using regular, downloaded builds, download the latest build off `openrct2.org` .

**Comment by jensj12** [comment]
Can confirm on 51fc2fe. The cutoff point seems to be around 2650 guests on the tested park. Open any park and send a few large trams.

**Comment by Gymnasiast** [comment]
Odd. We have had this problem before, not sure why pagination would be broken again.

**Comment by Gymnasiast** [comment]
I have been able to reproduce. If you have 3100-3200 guests in your park, you will indeed not be able to scroll down all the way, but there won't be a page dropdown yet - that page dropdown only appears when crossing the 3500 guest mark, it appears. Perhaps we should just paginate per 2000 guests, seems more than enough to me.

**Comment by ocalhoun6** [comment]
While we're at it, wouldn't it be more intuitive if it automatically skipped to page 2 (and so on) whenever you scrolled down to the very bottom of the page and attempted to scroll further?

**Comment by tomlankhorst** [comment]
@Gymnasiast There's the scroll widget limit and the pagination limit. These currently do not match. 

https://github.com/OpenRCT2/OpenRCT2/blob/6ef01b3cd3dc655939241e5df5179a443c0f9519/src/openrct2-ui/windows/GuestList.cpp#L493

How to track down the maximum number of items in the scroll widget?

**Comment by AaronVanGeffen** [comment]
> How to track down the maximum number of items in the scroll widget?

I believe it was split in order to not make the scrollbar thumb too small. There is no set limitation to how big a scrollable area can be.

**Comment by tomlankhorst** [comment]
Seems that the height cutoff `0x7BF2` (=31730) and the per-page number (3173) were not consistent with `SCROLLABLE_ROW_HEIGHT`

**Comment by AaronVanGeffen** [comment]
Sounds like an unfortunate side-effect of #6522. This has been in for a while!

**Comment by acrossthestars07** [comment]
Sorry, is this problem resolved? i see the thread is marked as closed. 
So I tried to download the developer version of the game, but I had a ton of issues. I have a Windows laptop, so I tried to download both the 64 and the 86 version. Every time I tried to open the download, a window popped up saying that I did not have administrative permission, then it aborted. My antivirus went crazy too. Do I need to download the developer version in order for this problem to be resolved? If so, I might need some help. 
Thanks so much!

**Comment by Gymnasiast** [comment]
Yes, this bug is solved.

Some antivirus programs don't trust OpenRCT2 for some reason. You need to whitelist OpenRCT2 for it to work, or switch to another AV program.

The newest `develop` version (which is indeed what you need) can be download here: http://cdn.limetric.com/games/openrct2/0.2.1/develop/57193aa/7/OpenRCT2-0.2.1-develop-57193aa-windows-x64.exe
You can also use the launcher, which auto-updates the game for you. It can be downloaded here: https://github.com/LRFLEW/OpenRCT2Launcher/releases/download/v0.0.7/OpenRCT2Launcher-win.exe

**Comment by janisozaur** [comment]
Keep in mind there's no launcher for the launcher so you need to update it manually whenever it's required.

**Comment by IntelOrca** [comment]
> Keep in mind there's no launcher for the launcher so you need to update it manually whenever it's required.

It does however notify you when there is an update for the launcher available:
https://github.com/LRFLEW/OpenRCT2Launcher/blob/develop/updater.cpp#L85
