### ISSUE TITLE
DMP files and More

### ISSUE THREAD

**Issue by D1JL** [OpenRCT2/OpenRCT2#8589]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.2.1]
**Commit/Build:** [e.g. 426e106]

I have only been using OpenRCT2 for a short time and my OpenRCT2 folder is becoming overwhelmed with, DMP, GZ ARCHIVE, Configuration Settings, and ASSOC-SAVEGAME files.
1. Can I put all of these files into a subdirectory of their own?
2. Maybe a subdirectory could be made and all of these files could go into it AUTOMATICALLY.

Thanks,
Dave

- [NO ] Reproducible in RCT2 (vanilla)?
- [NO ] Specific to multiplayer?

**Comment by D1JL** [comment]
The info you are looking for is IN my opening post.
OS: [e.g. Windows 10]
Version: [e.g. 0.2.1]
Commit/Build: [e.g. 426e106]

As for the OpenRCT2 folder, I thought that may be obvious in that it is the one created when OpenRCT2 is installed automatically in the documents folder on my hard drive.

Maybe I should not used the word overwhelmed but instead just said that a large number of the above mentioned files (or should I list them again) are now populating my OpenRCT2 folder on my hard drive in my documents directory within my Windows 10 operating Hewlett Packard  computer.
Thank you,
Are there any more questions?

BTW: I left the stats out of my very first post because I didn't know to use this forum and I was OVERWHELMED by the instructions.
The other times, I am sorry but I did not think they were relevant to the question I asked.
However, I have corrected my ways and I am including them in the future.

**Comment by D1JL** [comment]
Is it possible to remove the invalid/incomplete label so that original question may be answered?
1.Can I put all of these files into a subdirectory of their own?
2.Maybe a subdirectory could be made and all of these files could go into it AUTOMATICALLY.
As I did provide the stats in my opening post and I believe I covered everything else in my second.

**Comment by IntelOrca** [comment]
You can move or delete the files as you wish but the game will continue to place new dump files into the top level directory. You can just clean it out every so often.

**Comment by janisozaur** [comment]
@D1JL If you are not going to consume them in any way (report to us or investigate yourself) why keep them around at all?

**Comment by D1JL** [comment]
@janisozaur, that is a good point.
When a real crash did happen the files were sent, mostly automatic, I think I just had to confirm the send.
However, many times I created the problem myself with adding/removing scenery objects.
I didn't think you wanted files based on my screwups.
I am still new to OpenRCT2 and not what to do or not.
I will delete the old ones at some point and only keep what is current just in case.

I do appreciate your answers as they do help me learn. 
That is why I asked in the first place because I didn't know if I could delete or move them.

**Comment by Gymnasiast** [comment]
@D1JL 
> The info you are looking for is IN my opening post.
OS: [e.g. Windows 10]
Version: [e.g. 0.2.1]
Commit/Build: [e.g. 426e106]

You didn't fill any of them in. That's what I'm talking about. All of them still contain their example data, not the actual versions you're using.

**Comment by IntelOrca** [comment]
@D1JL on the title screen if you look at the bottom right you will see the version information. Copy that into your issue when you post one.

**Comment by D1JL** [comment]
@Gymnasiast @IntelOrca 
Thank you, Sorry, I didn't understand how that worked.  :)
I will make sure everything is provided in the future.
