### ISSUE TITLE
Framerate delimiter speeds up guests

### ISSUE THREAD

**Issue by Alicecomma** [OpenRCT2/OpenRCT2#8591]
**OS:** Windows 10
**Version:** Both 0.2.1 and current dev build
**Commit/Build:** Both 8ac731e and 51fc2fe

Without the framerate delimiter, guests move as normal (e.g as expected from RCT1) at any framerate.

Turning on the framerate delimiter causes all guests/staff to move at speeds proportional to the framerate. In specific, lower framerates increase the guest/staff speed, suggesting that their speed increases as v = v0 * 40/FPS, or similar. This is especially noticeable at FPS of about 6-10, in savefiles with many guests.

**Steps to reproduce:**
1. Enter a crowded savefile and find a spot where FPS is about 6-10
2. Toggle framerate delimiter in the options menu (first tab)
3. Observe guest speeds and repeat step 2 to see the difference

**Screenshots / Video:**
I could record if necessary, but the combination of low FPS in-game and high enough FPS to get a good recording may be very difficult to achieve on my computer set-up.

**Comment by IntelOrca** [comment]
What do you mean by the framerate delimiter?

**Comment by Richard-L** [comment]
Well uncap fps, no?

**Comment by ZehMatt** [comment]
If the game runs with Uncap FPS and the Framerate drops below 30 or something the peeps seem to run slightly faster.

**Comment by IntelOrca** [comment]
I think the game will update more than one cycle per draw frame if the FPS is low, sort of as a catch up.

**Comment by ZehMatt** [comment]
I'm already on it, the issue is that it has two loops, it should only run one in a fixed rate. Almost done.

**Comment by ZehMatt** [comment]
Can you test with https://ci.appveyor.com/project/IntelOrca/openrct2-ject9/builds/21642174/job/w0qnd297bp8t951g/artifacts if that fixes the issue?
