### ISSUE TITLE
Sign contents on mouse hover

### ISSUE THREAD

**Issue by Richard-L** [OpenRCT2/OpenRCT2#8593]
Just a quick suggestion: how about automatically showing a sign's text in appropriate complementary colour, on hovering the mouse, where currently it already shows the sign type and "right-click to modify".

![image](https://user-images.githubusercontent.com/4934209/51198410-770df100-18f4-11e9-8609-61166ddef4b1.png)

Thanks for considering.

**Comment by Liampie** [comment]
I think this is a great idea, but in the case of banner facing away from the viewer like in this example, you're not supposed to read the banner. I think ideally this feature should only work from banners that are facing you.

**Comment by Xkeeper0** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/1077535/52020319-b9633080-24a5-11e9-80b3-6ebc0387d26c.png)

**Comment by Gymnasiast** [comment]
@Xkeeper0 Open a pull request and we can help you get it up to scratch.

**Comment by Richard-L** [comment]
@Xkeeper0 I think that's awesome !

**Comment by Umdlye** [comment]
Implemented by #8659
