### ISSUE TITLE
'Screenshot failed' due to park name character?

### ISSUE THREAD

**Issue by Richard-L** [OpenRCT2/OpenRCT2#8598]
A "screenshot failed" prompt appears when trying to take screenshots on this park: https://www.nedesigns.com/park/1698/60/

The park has an asterisk in its name. Perhaps is that the problem?

**Comment by janisozaur** [comment]
![60*60 2019-01-17 22-12-57](https://user-images.githubusercontent.com/550290/51349284-2e496a00-1aa5-11e9-9dfd-4e5fa35f770b.png)

![60*60 2019-01-17 22-13-01](https://user-images.githubusercontent.com/550290/51349296-343f4b00-1aa5-11e9-8fb1-0b9ea834c93a.png)

Works just fine for me.

**Comment by Gymnasiast** [comment]
@janisozaur That's not terribly helpful -- Linux allows asterisks in file names, and Windows does not.

**Comment by ocalhoun6** [comment]
Yes, it's probably because the park name gets incorporated into the filename for the screenshot, and Windows doesn't allow * in file names.

Seems like it shouldn't be too hard to add a bit of code into the screenshot process to strip special characters from the file name before saving.

**Comment by tomlankhorst** [comment]
Currently, there's some Windows specific [filename](https://github.com/OpenRCT2/OpenRCT2/blob/92412d4bab085fe5adbdac80f67af4a50d2fab98/src/openrct2/interface/Screenshot.cpp#L118) processing. Could extend that for more general sanitation and share that functionality with other parts of the code that interface with the filesystem?

**Comment by bdupree5** [comment]
Hello, me and my team would like to work on this issue, we will continue to update you as we continue our work.

**Comment by janisozaur** [comment]
There's PR already open against this issue: https://github.com/OpenRCT2/OpenRCT2/pull/8611

**Comment by bdupree5** [comment]
Thank you for letting me know.
