### ISSUE TITLE
OpenRCT2 draws supports in places where vanilla wouldn't

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#8601]
So I noticed while looking at some older parks that a coaster's supports where showing, where they should be blocked. I don't think this has always been a problem with OpenRCT. I guess it has something to do with the drawing order on those tiles? 

I took two screens of the exact same thing in the exact (pixel perfect) location. A high quality gif alternating between the two would make the differences clear, but I don't know how to do that, so I'll just upload the two .pngs I have, and you have to do the alternating yourself if you download them...

Note the flying coaster supports, but also the tram supports.

![scr1](https://user-images.githubusercontent.com/19242088/51396232-f989f100-1b3e-11e9-800e-956d14dd93d1.png)
![varmland park - dimi 2008-2011 2019-01-18 16-25-13](https://user-images.githubusercontent.com/19242088/51396233-f989f100-1b3e-11e9-82df-04bd7f9966ae.png)

The park in question: [Dimi - Värmland Park.zip](https://github.com/OpenRCT2/OpenRCT2/files/2773542/Dimi.-.Varmland.Park.zip)
https://www.nedesigns.com/park/1869/vaermland-park/

Using v0.2.1-600 (92412d4) on Windows 8

**Comment by AaronVanGeffen** [comment]
Hmm, that does look a little overzealous. Something to do with detecting the custom supports, maybe?

**Comment by Liampie** [comment]
The custom supports likely have nothing to do with it, they rarely influence the coaster's supports, especially in this case as the track is inverted, meaning that the supports are on the side on an entirely different tile. Besides, the tram is also affected even when there isn't a coaster near it (see top of screen for example)

**Comment by tomlankhorst** [comment]
![ezgif-1-8101965993b7](https://user-images.githubusercontent.com/675432/51494687-cb641580-1db9-11e9-98b2-520438292a83.gif)

**Comment by Liampie** [comment]
I found two more examples:

https://www.nedesigns.com/park/714/barkwood-amusement-park/

Very noticable here, maybe a better park to use to figure out what's wrong:
https://www.nedesigns.com/park/605/jetstream/

**Comment by duncanspumpkin** [comment]
Make a minimal map that suffers from the bug. I don't want anything apart from the scenery that is not causing the block and the track. The examples from this are too complex and I don't know enough about how it is meant to work to make a minimal version.

**Comment by Liampie** [comment]
> 
> 
> Make a minimal map that suffers from the bug. I don't want anything apart from the scenery that is not causing the block and the track. The examples from this are too complex and I don't know enough about how it is meant to work to make a minimal version.

Only just saw this message. I isolated the differences between vanilla and Open, as shown in the screens above, in this savegame:

[supportsbug.zip](https://github.com/OpenRCT2/OpenRCT2/files/6907989/supportsbug.zip)

**Comment by duncanspumpkin** [comment]
For reference this is OpenRCT2 as of 30/07/21
![image](https://user-images.githubusercontent.com/1277401/127676093-b527dd96-9d59-4b40-b945-d013ed1f4fc2.png)

And this is vanilla RCT2
![image](https://user-images.githubusercontent.com/1277401/127677406-5ecba68b-9d72-4d2c-ac88-1712a684fdc5.png)
Its clear that the base supports have not been drawn. Also the quadrant it is drawn in is different.

**Comment by duncanspumpkin** [comment]
[8601S.zip](https://github.com/OpenRCT2/OpenRCT2/files/6909156/8601S.zip)
This is a super minimal save that suffers from the bug. Loads fine in vanilla and OpenRCT2.

**Comment by duncanspumpkin** [comment]
ARGHHH can't believe i went round and round in so many circles and its something super obvious:

```
    // ToonTowner's base blocks. Make them allow supports on top and put them in the Walls and Roofs group.
    if (identifier == "XXBBCL01" ||
        identifier == "XXBBMD01" ||
        identifier == "ARBASE2 ")
    {
        SetPrimarySceneryGroup(scgWalls);

        _legacyType.flags |= SMALL_SCENERY_FLAG_BUILD_DIRECTLY_ONTOP;
    }
```

**Comment by Gymnasiast** [comment]
This is not a bug. All vanilla base blocks allow supports on top, and so I fixed ToonTowner’s base blocks to also allow them. The bug is that TT forgot to set that flag on his objects in the first place.

**Comment by Liampie** [comment]
I don't think OpenRCT should concern itself with the properties of custom objects, it's outside the realm of what OpenRCT sets out to do.
