### ISSUE TITLE
Wall piece collision detection deviates from vanilla

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#8602]
This is something that has bothered me for multiple years now, but I never bothered to file the report. Here we go. :P 

The screen should make the differences clear. Wooden supports, either a coaster's, path's or an object's, only get removed because of the placement of a wall if it's one clearance below it or at the same height. If it's two clearances below it, it will still draw the support. This isn't the case in vanilla. Seems like a small issue and hardly noticable, and in this example screen it is, but in practice it means that if you open old parks there may be random black supports spawned by raised objects in places where they are very unwelcome.

![wallsupports](https://user-images.githubusercontent.com/19242088/51397465-9b124200-1b41-11e9-8ae0-51d717d0fc1e.png)

Using v0.2.1-600 (92412d4) on Windows 8

**Comment by Gymnasiast** [comment]
Noticed this as well, but didn't know it was caused by wall collision detection. That certainly helps.

**Comment by Broxzier** [comment]
This wasn't the case around 2 years ago, back then reordering the elements was required to see the supports.

**Comment by aw20368** [comment]
@Broxzier may I work on this?
