### ISSUE TITLE
OpenRCT makes duplicates of your savegame folder

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#8603]
All my savegames are stored in my vanilla RCT folder, since that's a convenient place where I like having my savegames stored. I put downloaded parks there, I save parks there, I do everyhing there. What OpenRCT does in the background is copying any .sv6 file that's in that folder into its own OpenRCT savegames folder. If I remove files from my own savegames folder, the files will remain in the OpenRCT folder. If I change the name of a folder within my savegames folder, OpenRCT will just copy that entire folder as if it were a new one. This is obviously taking up a lot of space on my hard drive. 

What's worse is that it does this for every account on your computer, since OpenRCT is stored in the user folder. I have two accounts on my laptop, and sometimes I use OpenRCT while being on that other account. So I don't just have one duplicate of every savegame that has ever passed my actual savegames folder, I have TWO duplicates, and for some savegames and sub folders even more than two! I just removed literally 10 GB of duplicate savegames.

To me this is very annoying and I doubt this is how you guys wants OpenRCT to operate. Besides, it's 2019, why can't I pick my own folder where I want to store my savegames? It would be great if this problem could be resolved.

Using v0.2.1-600 (92412d4) on Windows 8

**Comment by janisozaur** [comment]
It's 2019, why can't you just symlink whatever you want?

**Comment by AaronVanGeffen** [comment]
> It's 2019, why can't you just symlink whatever you want?

Windows has no GUI interface to do this. Don't expect normal users to dig around in a command-line to symlink folders on Windows.

Regardless, it's off-topic. The copying of saves should be a one-time thing, anyway.

**Comment by IntelOrca** [comment]
I mean, it would be nice to remove the copy but a lot of users want their RCT2 saved games accessible when moving to OpenRCT2 but we also do not want to encourage using anything other than the user's home directory for storing them.

**Comment by Liampie** [comment]
> You can specify the folder by launching OpenRCT2 like this:
> OpenRCT2.exe --user-data-path="C:\OpenRCT2Data"
> Where it would use C:\OpenRCT2Data instead of C:\Users%USERNAME%\Documents\OpenRCT2

I can change the directory OpenRCT uses for all its files? That'd be very helpful. I don't know where to type this line though. I can open cmd, but what do I do next?

@jani: I don't know what symlinking is and I doubt I can make it work. Remember, I'm not an IT guy.

**Comment by ZehMatt** [comment]
You can either create a shortcut or a batch file or use the command line.

**Comment by tomlankhorst** [comment]
@Liampie 
Navigate to the folder containing your 'openrct2.exe', right-click the .exe, select 'create shortcut'. 
Right-click the shortcut, select 'properties'. There's a target field: append the flags to it. 
Note: IF the target field has quotes (") around the filename, place the arguments AFTER the quoted target. 

Something like: 
`"C:\Games\OpenRCT2\OpenRCT2.exe" --user-data-path="C:\OpenRCT2Data"`

At least, that's how it is done in my memory of Windows.

**Comment by Broxzier** [comment]
If you wish to manage both folders as one, copy over the files from _Documents\OpenRCT2\save_ to your _RCT2\Saved Games_ location, then delete the save folder and make it a symbolic link. Do that by opening the _Documents\OpenRCT2_ folder in command prompt and run `symlink /J save "C:\PATH_TO_YOUR_RCT2_FOLDER\Saved Games"`.

**Comment by IntelOrca** [comment]
@Broxzier Not heard of symlink before, for me I do `mklink /D src dest`

**Comment by Broxzier** [comment]
@IntelOrca Whoops! That was a typo, I meant mklink as well.

**Comment by Patrik356b** [comment]
@IntelOrca symlink is just an abbreviation of "Symbolic Link"
