### ISSUE TITLE
Removing Pathments

### ISSUE THREAD

**Issue by tillablepower1973** [OpenRCT2/OpenRCT2#8607]
I wanted to place a infomation box in the middle of park so i removed a 2 normal paths and just decided to crash on me. Any ideas can solve this or try and fix it

**Comment by IntelOrca** [comment]
@tillablepower1973 when it crashed, did it ask you if you wanted to submit a crash report?

**Comment by tillablepower1973** [comment]
yes it did

**Comment by bdupree5** [comment]
Hello, Me and my team would like to try and fix this issue, we will keep you updated as we continue our work.

**Comment by Broxzier** [comment]
@bdupree5 Thanks, but this issue does not give enough information to know what's happening. You could try to reproduce the issue, but without knowing what the reporter did exactly it's pretty much a shot in the dark. If you _are_ able to find out how to reproduce this issue, then that would be very helpful.

**Comment by bdupree5** [comment]
We can give it a try. Thanks for the update about it. If it appears to difficult I will let you know.

**Comment by bdupree5** [comment]
We have decided not to work with this issue, as stated before there was not enough information.
