### ISSUE TITLE
[Request] Add new Cheat: Automatic "Good value" ride pricing

### ISSUE THREAD

**Issue by Sqoops** [OpenRCT2/OpenRCT2#8610]
Can you include a new cheat option that every time a ride value changes (including due to age) the game will change the price of the ride to the new "Good value" price automatically?

I've completed a part of this process but it lacks the whole cheat toggling option and is therefore always active.

By editing
 ...\OpenRCT2\src\openrct2\ride\RideRatings.cpp

Below the line
    ride->value = std::max(0, value);
add this new line:
    ride->price = std::max(0, value/2);

**Comment by AaronVanGeffen** [comment]
I think this would be something more suited to a plugin, personally.

**Comment by IntelOrca** [comment]
If this is a cheat, why not just cheat for money and make all your rides free?
