### ISSUE TITLE
Feature request: User-configurable default prices for rides and shops

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#8612]
**OS:** Windows 8
**Version:** e.g. 0.2.
**Commit/Build:** 2350cd1

It would be a really nice convenience feature to have something in the options menu (or at the very least, an editable config file that future updates won't change) that would allow you to change the default prices for each type of ride and shop/stall.

For example, I personally like to raise the prices of pretty much every shop by .30, charge .30 for restrooms, 20.00 for umbrellas. As for rides, I often end up charging 3.00 for each coaster, rather than the default of 2.00. For certain flat rides (the crooked house and 3D cinema) I almost always _lower_ the price so I don't have to worry about lowering it later when they become less popular.

Thanks to #8610, I realized that this could perhaps be made easier. Maybe I shouldn't have to adjust the price every time I open a new ride or stall...

Of course this option menu would be initialized with RCT2's default default prices, so anyone who didn't know about it or didn't want to be bothered with it could simply never open that options page and never have to worry about it. In that case, the default prices would behave exactly like RCT2 and there would be no noticeable change. There should probably also be a 'reset to defaults' option on that page, to change all the default prices back to their normal values.

I see it as a convenience feature, along the same lines as automatically opening stalls when they're placed, or automatically placing staff when you hire them.

**Comment by Nazey** [comment]
My team and I would like to work on this issue

**Comment by duncanspumpkin** [comment]
Your welcome to work on this but we may not merge the change as ideally this would be solved in a plugin in the future when we finish the plugin system

**Comment by Nazey** [comment]
Ok, should we just write it as if it were to be merged, or is there a specific branch for plugins? (or something of the sort)

**Comment by Broxzier** [comment]
There is a [plug-in branch](https://github.com/OpenRCT2/OpenRCT2/tree/epic/plug-in), but its support is very limited and it has been a while since it was last updated.

**Comment by Gymnasiast** [comment]
Plugins have arrived in the meantime ;)
