### ISSUE TITLE
Graphic issues with OpenGL

### ISSUE THREAD

**Issue by UsernamelessEntity** [OpenRCT2/OpenRCT2#8623]
**OS: Windows 10
**Version: v. 0.2.1-608
**Commit/Build: 7de1152

When changing the scaling whilst using OpenGL as renderer the game absolutely shits itself. Many sprites are not rendering, menu's become blank and many things are popping in and out of view.
I did some further experimenting with it, and is is the OpenGL rendering option. Which I have used before without this happening

- [ ] Reproducible in RCT2 (vanilla)? nope
- [ ] Specific to multiplayer? nope

**Steps to reproduce:**
1.  Start OpenRCT2
2.  Go to options
3. Select OpenGL Drawing Engine
4. Change scaling
5 Magic...?

**Screenshots / Video:**
![20190121200258_1](https://user-images.githubusercontent.com/42636406/51494426-e6825580-1db8-11e9-8bf3-af01e072304d.jpg)
![20190121200651_1](https://user-images.githubusercontent.com/42636406/51494427-e6825580-1db8-11e9-81f6-ab7004cf6996.jpg)
![20190121200715_1](https://user-images.githubusercontent.com/42636406/51494428-e6825580-1db8-11e9-923c-97fad3789394.jpg)

**Save game:**
The most relevant seemed the settings in the config file, but that is it

[general]
always_show_gridlines = false
autosave = 1
autosave_amount = 10
confirmation_prompt = false
currency_format = EUR
custom_currency_rate = 10
custom_currency_affix = SUFFIX
custom_currency_symbol = "Ctm"
edge_scrolling = true
edge_scrolling_speed = 12
fullscreen_mode = 2
fullscreen_height = 1080
fullscreen_width = 1920
rct1_path = "C:\\Program Files (x86)\\Steam\\steamapps\\common\\RollerCoaster Tycoon Deluxe"
game_path = "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Rollercoaster Tycoon 2"
landscape_smoothing = true
language = en-GB
measurement_format = SI
play_intro = false
save_plugin_data = true
debugging_tools = true
show_height_as_units = false
temperature_format = CELSIUS
window_height = 480
window_snap_proximity = 5
window_width = 720
default_display = 0
drawing_engine = SOFTWARE_HWD
uncap_fps = true
use_vsync = true
test_unfinished_tracks = true
no_test_crashes = false
date_format = DD/MM/YY
auto_staff = true
handymen_mow_default = false
default_inspection_interval = 2
last_run_version = "0.2.1"
invert_viewport_drag = false
load_save_sort = 0
minimize_fullscreen_focus_loss = true
day_night_cycle = true
enable_light_fx = false
upper_case_banners = false
disable_lightning_effect = false
allow_loading_with_incorrect_checksum = true
steam_overlay_pause = true
window_scale = 1.000000
scale_quality = SMOOTH_NEAREST_NEIGHBOUR
show_fps = true
trap_cursor = false
auto_open_shops = false
scenario_select_mode = 1
scenario_unlocking_enabled = true
scenario_hide_mega_park = true
last_game_directory = ""
last_landscape_directory = ""
last_scenario_directory = ""
last_track_directory = ""
use_native_browse_dialog = true
window_limit = 64
zoom_to_cursor = true
render_weather_effects = true
render_weather_gloom = true
show_guest_purchases = true
show_real_names_of_guests = true
allow_early_completion = false
virtual_floor_style = GLASSY

[interface]
toolbar_show_finances = true
toolbar_show_research = true
toolbar_show_cheats = true
toolbar_show_news = true
toolbar_show_mute = true
console_small_font = false
current_theme = "*RCT2"
current_title_sequence = "*OPENRCT2"
object_selection_filter_flags = 16383

[sound]
audio_device = ""
master_sound = true
master_volume = 100
title_music = 2
sound = true
sound_volume = 100
ride_music = true
ride_music_volume = 100
audio_focus = true

[network]
player_name = "Usernameless_Entity"
default_port = 11753
listen_address = ""
default_password = ""
stay_connected = true
advertise = true
maxplayers = 16
server_name = "Server"
server_description = ""
server_greeting = ""
master_server_url = ""
provider_name = ""
provider_email = ""
provider_website = ""
known_keys_only = false
log_chat = false
log_server_actions = false
pause_server_if_no_clients = false

[notifications]
park_award = true
park_marketing_campaign_finished = true
park_warnings = true
park_rating_warnings = true
ride_broken_down = true
ride_crashed = true
ride_warnings = true
ride_researched = true
guest_warnings = true
guest_lost = false
guest_left_park = true
guest_queuing_for_ride = true
guest_on_ride = true
guest_left_ride = true
guest_bought_item = true
guest_used_facility = true
guest_died = true

[twitch]
api_url = ""
channel = ""
follower_peep_names = true
follower_peep_tracking = false
chat_peep_names = true
chat_peep_tracking = true
news = false

[font]
file_name = ""
font_name = ""
x_offset = 0
y_offset = 1
size_tiny = 1
size_small = 0
size_medium = 0
size_big = 0
height_tiny = 0
height_small = 0
height_medium = 0
height_big = 0
enable_hinting = true
hinting_threshold = 0

**Comment by UsernamelessEntity** [comment]
I have a HP Pavilion with a I5-8300H, Intel UHD Graphics 630 and a NVIDEA GeForce GTX 1050.
THe issues are only there using the OpenGL drawing engine. and doing some further experimenting on different builds gave me the same results. Those are the graphical issues shown in the screenshots above and that the issues will slightly and temporarily be reduced when changing the rendering settings for weather.
The game was using the Intel integrated graphics chip.
When forcing windows to use the GTX 1050 everything works fine.

**Comment by UsernamelessEntity** [comment]
[DxDiag.txt](https://github.com/OpenRCT2/OpenRCT2/files/2797146/DxDiag.txt)

I saved a dxdiag.
The problem is only there when I forced OpenRCT2 to use the integrated graphics chip. I installed a clean copy of OpenRCT2, RCT2 and RCT. The problems seemed to have fixed themself than, but when i forced it to use the integrated graphics chip, it completely shat itself once again.
Like I said above, when fiddling with the rendering effects it is possible to let it run with the OpenGL drawing engine in a very unstable state. It appears that the game starts with refusing certain parts to be drawn/shaded. This means that most of the game gets drawn correctly, but certain object/colour combinations are not drawn/drawn completely black (like the object has an Albedo of 0). It will run in this state for a brief period, and then will switch to something comparable with the screenshots provided above. I will try to get some screenshots of the game in this intermediate state.

**Comment by UsernamelessEntity** [comment]
![20190125184906_1](https://user-images.githubusercontent.com/42636406/51763198-3f602f80-20d2-11e9-960e-a5632198900c.jpg)
Here you can clearly see that the game stops drawing certain parts. Here are certain track pieces drawn with an albedo of 0. All the track pieces that are black are normally a different colour form the yellow track. Also a lot of other objects appear not to have been drawn by the game.
Hope this helps

**Comment by IntelOrca** [comment]
I expect this is a problem with your CPU graphics driver. Many have issues with OpenGL and the feature set we use may be just beyond the capabilities of yours. Make sure your CPU drivers are up date.

**Comment by AaronVanGeffen** [comment]
This looks related to, if not the same issue as, #6614.

**Comment by UsernamelessEntity** [comment]
Looks like the problems have the same root. The main difference being that the problem escalates further on my laptop. Was interesting to see that #6614 has an Intel 630 integrated graphics chip as well.
Also, I have updated all the drivers I could find, but to no avail.
I'll use the NVIDEA graphics card for now.  If you need to test something I will be happy to help.

**Comment by UsernamelessEntity** [comment]
I will try the 32 bit version of OpenRCT2 and see what happens

**Comment by UsernamelessEntity** [comment]
Checked the 32 bit version. It didn't work.

**Comment by UsernamelessEntity** [comment]
Could some Team Viewer sessions help you guys out? I am willing to lend out my Laptop as remote developer hardware.

**Comment by plynml-c** [comment]
@UsernamelessEntity I'm happy to say I have a solution for you. I believe this is unrelated to OpenRCT2. I have the same exact graphics card and issue.

Be sure your NVIDIA drivers are installed. Whenever those are installed, or likely already pre-installed, go to your NVIDIA Settings / NVIDIA Control Panel -- most likely there's an icon in your taskbar, right click it and open the NVIDIA Control Panel.

On the far right of the NVIDIA Control Panel Window: 3D Settings -> Manage 3D settings. Now, in Global Settings, look for the line "OpenGL rendering GPU". Change the dropdown from "Auto-Select" to "GeForce GTX 1050"

![image](https://user-images.githubusercontent.com/18249772/55519909-dd7af380-5647-11e9-859d-c0ce7edf98c2.png)

![image](https://user-images.githubusercontent.com/18249772/55519756-1a92b600-5647-11e9-833f-c52c5824e4db.png)

![image](https://user-images.githubusercontent.com/18249772/55519789-457d0a00-5647-11e9-81ba-a7eb6e0339e8.png)

Let me know whether this works or not. "Auto-Select" was the default for me.

P.S. Thank you to each and every contributor to this project, and great work. I'm a big fan

**Comment by giantmustache** [comment]
I am experiencing the same issue. My laptop only has Intel HD Graphics 520 (driver 23.20.16.4973) and supports opengl 4.5. Software rendering works fine, but there are a couple of things that do not look how they are supposed to look like, like the buttons, text and terrain:

![image](https://user-images.githubusercontent.com/5402708/85980864-73d0cd00-b9e3-11ea-932d-f41c50171b97.png)

**Comment by duncanspumpkin** [comment]
Sprites are split up into different atlases of images. I suspect the intel graphics card is for some reason not letting one of the atlases draw that would explain why its a large proportion of sprites but with another large proportion rendering correctly.

**Comment by IntelOrca** [comment]
It might be exceeding some of the capabilities of the gpu / driver. We don't check any of the maximum texture sizes, memory etc. or necessarily if all the APIs return valid return codes.
