### ISSUE TITLE
[Feature Request] Chat button on the UI

### ISSUE THREAD

**Issue by TheEssemCraft** [OpenRCT2/OpenRCT2#8634]
Currently, to chat in multplayer games, the only option is to press the C button on the keyboard. This can be an issue for users that use touchscreens (like Android users) and can't use a keyboard on anything but textboxes. Adding a chat button on the UI would be useful for accessibility, as it can not only give these users a way to chat, but can also help with general accessibility.

**Comment by TheEssemCraft** [comment]
EzioisAwesome56 managed to get the mute button to work as a chat button with his fork: https://github.com/EzioisAwesome56/OpenRCT2/commit/ecae8af61b47efa8cbdc6d06cdaac136788b76d0

**Comment by Xkeeper0** [comment]
Since #8648 got merged, should this be resolved?
