### ISSUE TITLE
README suggestion: Similar Projects OpenJK

### ISSUE THREAD

**Issue by pdewilde** [OpenRCT2/OpenRCT2#8643]
**Commit/Build:**  3b176cd

I was gong to try a PR, but could not get the MD formatting right. I think Open Jedi Knight should be added in the similar projections section of the README. [This is their Github](https://github.com/JACoders/OpenJK)

**Comment by Gymnasiast** [comment]
OpenJK looks indeed related, at least in terms of development. But I do think we should keep the number of related projects in the README down to a manageable number. Currently, we mention our "cousin project" (OpenLoco), as well as 3 remakes of very popular games. 

I'm therefore a little bit inclined not to add it to the README, but if another team member thinks it should be added, I'm fine with that too.
