### ISSUE TITLE
Setting date is not networked

### ISSUE THREAD

**Issue by Lindenk** [OpenRCT2/OpenRCT2#8649]
**OS:**
Linux
**Version:**
0.2.1
**Commit/Build:** 
e.g. 426e106]

Spectators can set the date under the cheats menu.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**
1. Open cheats menu
2. Click 'Set Date'

**Comment by Xkeeper0** [comment]
I just checked this and it only does this locally (and usually immediately causes a desync). Join (Apr 3, Y4), set date (Mar 1, Y1), exit and rejoin (Apr 3, Y4).

**Comment by Gymnasiast** [comment]
@Xkeeper0 Ah, thanks! That also explains why spectators can do so - if the command is not networked, then it obviously will not check for permissions either.

Making the command networked should take care of both issues.

**Comment by Gymnasiast** [comment]
Fixed.
