### ISSUE TITLE
Crash upon saving scenario

### ISSUE THREAD

**Issue by FlyingThunder** [OpenRCT2/OpenRCT2#8651]
**OS:** Win10
**Version:** 0.2.1
**Commit/Build:** 8ac731e

The game crashed upon saving of my custom scenario. The file was still saved succesfully and i can play my scenario (thank god).

[7z dump.zip](https://github.com/OpenRCT2/OpenRCT2/files/2808914/7z.dump.zip)

**Comment by Gymnasiast** [comment]
There is a good chance this bug has already been fixed, since you're using the latest "release". We recommend switching to "develop".

**Comment by Xkeeper0** [comment]
I just had it happen.

OS: Ubuntu 16.04
Commit: accac88

It does not always happen, but weird things occur when it doesn't. In one case, after the scenario saved, the title screen was missing all buttons. In another instance, the quit button (and _only_ the quit button) was missing.

I managed to get it to segfault under valgrind (it took _forever_). The log from that is here: https://pastebin.com/G5frjMyW

Here is a backtrace from `gdb` as well (though a different run): https://pastebin.com/FU7LWNjk

**Comment by ZehMatt** [comment]
Some of the mentioned issues are fixed, the crash upon saving the scenario will be fixed by #9738
