### ISSUE TITLE
Crash after loading same saved file always happens a 1-2 mins after opening

### ISSUE THREAD

**Issue by eperlow19** [OpenRCT2/OpenRCT2#8653]
**OS:** [Windows 10]
**Version:** [0.2.1]
**Commit/Build:** [8ac731e]

<So openrct2 started crashing about 1 - 2 minutes after opening the same saved file each time. It does not matter whether i add scenery/build or just spectate: it seems to always crash. The error that comes up refers to an issue regarding "Sprite 65535" and i am not sure what that is or what it means. After clicking the abort option (the only proceed-able option), a window tells me to file the issue on github, with the dump and saved file/game. So here i am. Can someone please help? Thank you! This is a great community :)>

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open saved game.

2. Spectate or move around, and then about a minute or so in, it crashes.

**Dump file**

[TVEdump.zip](https://github.com/OpenRCT2/OpenRCT2/files/2812164/TVEdump.zip)

**Screenshots / Video:**

![2019-01-30](https://user-images.githubusercontent.com/47173821/51976080-72475200-2449-11e9-86b0-e814563dfb90.png)

**Save game:**

[treetopvalleyexpressway.zip](https://github.com/OpenRCT2/OpenRCT2/files/2812165/treetopvalleyexpressway.zip)

**Comment by janisozaur** [comment]
@eperlow19 please don't post screenshots that should be text.

https://openrct2.sp.backtrace.io/dashboard/openrct2/project/openrct2/group/edc7de16e340ff1bb5693fb41559a50290b3a69d8a293c4aac1765fcac2a5f48

**Comment by eperlow19** [comment]
@janisozaur oh, im sorry i wasnt aware.. am i supposed to make an account on that website? it wont take my email....

**Comment by Gymnasiast** [comment]
@eperlow19 No, only we can access backtrace. It's a note for us.

**Comment by eperlow19** [comment]
ah i see. And yeah sure - would that be the download at the openrct2 website called: (OpenRCT2-0.2.1-develop-3aad9a4-windows-win32.exe)?

**Comment by ZehMatt** [comment]
The issue is still present, following line is the cause https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/peep/Guest.cpp#L2360

I think that assignment is not even necessary since the for-loop body will obtain it.

**Comment by janisozaur** [comment]
@eperlow19 please disregard @gymnasiast, he does not pay attention, you're already on the latest `develop` build.

**Comment by janisozaur** [comment]
You should be able to download an updated build and it should work correctly then

**Comment by eperlow19** [comment]
@janisozaur so i should head over to the openrct2 website and get the most recent build (develop), and open the save file on that new version, correct?

**Comment by janisozaur** [comment]
Yes

**Comment by eperlow19** [comment]
@janisozaur It works again! thanks a lot guys! saved file has been running on the updated version and didnt crash. MUCH appreciated.
