### ISSUE TITLE
Missing track pieces in air-powered coaster

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#8663]
**OS:** Windows 8
**Version:** 0.2.1
**Commit/Build:** 66c5713

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

Air-powered coaster is missing a couple small track segments at the beginning and end of slopes. They are drawn from some angles, but not from others. See screenshot:

![the seventh circle 2019-02-02 22-39-50](https://user-images.githubusercontent.com/26573303/52174044-424ac800-2743-11e9-8414-a046edfc0798.png)

**Comment by Gymnasiast** [comment]
Has already been reported in https://github.com/OpenRCT2/OpenRCT2/issues/8585 and fixed in https://github.com/OpenRCT2/OpenRCT2/commit/3b176cd6eb41301b70f8883b3f0add34a4483bd5 . Please update before you report an issue.
