### ISSUE TITLE
Negative values not displaying (correctly).

### ISSUE THREAD

**Issue by RoboAtelier** [OpenRCT2/OpenRCT2#8674]
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** c436a65

Whenever a number reaches a negative value, instead of displaying the current negative value, the value displayed is 2^32 - 1 (4,294,967,295) subtracted by the negative value. This might be related to commit 8a395e3.

- [N] Reproducible in RCT2 (vanilla)?
- [N] Specific to multiplayer?

**Steps to reproduce:**
1. Open up any (Open)RCT2 scenario.
2. Check any ride stats, the financial summary, or any statistic that can produce a negative value.

**Screenshots / Video:**
![wow](https://user-images.githubusercontent.com/27904956/52312459-9c809e80-2978-11e9-85f6-8c254b021aeb.png)
![restroom](https://user-images.githubusercontent.com/27904956/52312864-36951680-297a-11e9-9392-23aedc1d4a4c.png)

**Comment by Xkeeper0** [comment]
Reverting the given commit does fix the issue.

**Comment by duncanspumpkin** [comment]
Sign extension is currently not working as memcpy does not do sign extension. `format_string_code` requires modification for every memcpy that is trying to copy a signed value smaller than 64bit. 

Suggest the following change:

Existing:
```
std::memcpy(&value, *args, sizeof(int32_t));
``` 

New:
```
int32_t tempValue{0};
std::memcpy(&tempValue, *args, sizeof(int32_t));
value = tempValue;
```
