### ISSUE TITLE
Refactor Game Do Command to remove redundant code

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#8677]
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/Game.cpp#L604-L618

There is redundant code in the old game_do_command code. Any reference to a `GAME_COMMAND_xxx` that has been ported to the new game action framework (marked by a `// GA` in game.h) can probably be deleted. See above for an example. 

`else if (command == GAME_COMMAND_CREATE_RIDE && *ebp == 1)` can never be reached as there is no longer anything that calls game_do_command with `GAME_COMMAND_CREATE_RIDE`.

**Comment by phillipwalters** [comment]
I removed the redundant code. It still builds and runs, but is there something else I should do to test it?

Changes can be viewed at https://github.com/phillipwalters/OpenRCT2/commit/14835b9e314ba6bf6c20222ad3de6217945c5298

**Comment by duncanspumpkin** [comment]
That is always the problem with redundant code. You are never 100% sure it can never be hit. Make a PR with your changes thanks.

**Comment by phillipwalters** [comment]
Alright, pull request created!
