### ISSUE TITLE
Refactor Game Actions to set player last action coord

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#8679]
There should be a call to `network_set_player_last_action_coord` with the game command coordinates during the execute branch of the game action. This should only be called if the coordinates are valid (`!LOCATION_NULL`). 
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/actions/GameAction.cpp#L284

As it stands at present game actions do not record where the player used them. Unlike their game command counter parts.

**Comment by jmyre1999** [comment]
My team and I would like work on this issue

**Comment by ZehMatt** [comment]
There is already a PR doing this, https://github.com/OpenRCT2/OpenRCT2/pull/8704

**Comment by Nazey** [comment]
yeah 8704 was merged, so this issue is irrelevant.
