### ISSUE TITLE
Autosave settings don't react to user input

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#8682]
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** 57471ed

The autosave settings cannot be changed by clicking on them. The only thing that works is changing the number of autosaves, but only when you use the scroll wheel.

![image](https://user-images.githubusercontent.com/6469413/52372243-f015e980-2a57-11e9-9c80-afa1a8b101ff.png)

**Comment by Broxzier** [comment]
Everything below the checkboxes seem to ignore mouse clicks now, including the RCT1 path buttons.

**Comment by Gymnasiast** [comment]
I had a user report that last bit.

**Comment by Broxzier** [comment]
I've got a fix ready, it was a regression from https://github.com/OpenRCT2/OpenRCT2/pull/8648.
