### ISSUE TITLE
[WIP] Helper bash script for 'xcode fix required'

### ISSUE THREAD

**Issue by tomlankhorst** [OpenRCT2/OpenRCT2#8695]
So, adding files to xcode projects takes some time and is quite repetitive and removing the xcode project from the repo will prob. take some time. (#8650)
Nobody likes repetitive and I figured it's [worth the effort](https://xkcd.com/1205/) to ease the process a bit.

I mocked up a little script. 

1. It reads all open issues and finds those that have the `xcode fix required` label
2. For each of these issues, get the PR data
3. Determine the ref and path of the `pr-head`
4. Fetch and checkout the PR
5. Show a summarized diff (what files have been added?)
6. Open Xcode
7. **Manually** add the files
8. Show the resulting diff
9. Add and commit the diff
10. Push the commit to your `fix` remote yielding a new `fix-head`
11. Open a URL to the Github 'create PR' page to the appropriate base (`pr-head`) and head (`fix-head`).

btw: `brew install jq`

```bash
#!/bin/bash

echo "This script reads open PRs that need xcode fixes."
echo "To do this, Github credentials are needed."
echo 

USER=tomlankhorst
echo -n "Github password for '$USER':"
read -s PASSWORD; echo

REMOTE=tomlankhorst
ISSUES="https://api.github.com/repos/OpenRCT2/OpenRCT2/issues?labels=Xcode%20Fix%20Required"
GET="curl -u $USER:$PASSWORD -s"

ISSUES_JSON=$($GET $ISSUES)

# Get the JSON and find the pull_request.url field, then replace all NULL with empty strings
# and remove those strings
PR_URLS=$(echo "$ISSUES_JSON" | jq -r '.[] | .pull_request.url | select (.!=null)' | awk NF)
PR_COUNT=$(echo -n "$PR_URLS" | grep -c '^')

echo "Got $PR_COUNT PRs"

for PR_URL in $PR_URLS; do 
	PR_JSON=$($GET $PR_URL)
	PR_NO=$(echo "$PR_JSON" | jq -r '.number')
	PR_REF=$(echo "$PR_JSON" | jq -r '.head.ref')
	PR_REF_UNIQ="$PR_NO-$PR_REF-fix"
	PR_NAME=$(echo "$PR_JSON" | jq -r '.head.repo.full_name')
	
	echo
	echo "This is $PR_NAME's $PR_REF (#$PR_NO)"
	echo
	git fetch origin pull/$PR_NO/head:$PR_REF_UNIQ
	git checkout $PR_REF_UNIQ
	git diff --summary develop

	read -p "Press [enter] to open the xcode project, press [n] to skip" ANS
	if [ "$ANS" == "n" ] ; then
		echo "Skipping..."; continue;
	fi

	open OpenRCT2.xcodeproj
	read -p "Press enter when the project is edited"
	git diff 
	read -p "All ok? Press enter to add, commit, push and create PR"

	git add .
	git commit -m "Add files to xcode project\n\nUsing helper script"
	git push -u $REMOTE

	open "https://github.com/$PR_NAME/compare/$PR_REF...$USER:$PR_REF_UNIQ"
done
```

**Comment by LinusU** [comment]
Another thing that I can personally recommend and that might be worth looking into would be to generate to Xcode Project on demand. It eliminates basically every merge conflict by deterministically generating the project from a small Yaml file, it also makes changes to the project much easier to review since they aren't buried in a lot of verbose xml files.

https://github.com/yonaskolb/XcodeGen

**Comment by AaronVanGeffen** [comment]
@LinusU #8650 aims to do this through CMake :)

**Comment by tomlankhorst** [comment]
There is indeed an ongoing effort to centralize build configuration through
CMake. This is an interesting suggestion though!

Op ma 18 feb. 2019 om 13:23 schreef Aaron van Geffen <
notifications@github.com>:
