### ISSUE TITLE
Raising land costs money in No-Money scenarios

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#8696]
**Version:** 0.2.1-750
**Commit/Build:** f32531c

**Steps to reproduce:**
1. Open any scenario
2. Disable money (cheats or scenario options)
3. Raise or lower land

**Comment by duncanspumpkin** [comment]
And what happens?

**Comment by Broxzier** [comment]
@duncanspumpkin Money is taken from non-displayed money pool, and when empty it gives the user the error that they don't have enough money.

![](https://cdn.discordapp.com/attachments/450316748734988289/543559174433275932/unknown.png)

**Comment by Gymnasiast** [comment]
This bug also plagues the Scenario Editor.
