### ISSUE TITLE
Wide path flags isn't being set correctly

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#8698]
**Version:** 0.2.1-750
**Commit/Build:** f32531c

Wide flags for paths aren't being set correctly, making guests walk in circles and getting lost.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Screenshots / Video:**
Before:
![](https://cdn.discordapp.com/attachments/411655823396438019/543798400823328783/RCF_Multiplayer_Squares_18_2019-02-09_15-19-32.png)

After:
![](https://cdn.discordapp.com/attachments/411655823396438019/543798425162874898/RCF_Multiplayer_Squares_18_2019-02-09_15-19-37.png)

Every path piece that has more than 2 edges connecting to non-wide paths (the non-ghost paths, shops, park entrance, etc) is considered a junction. IIRC peeps can only look 16 junctions ahead when pathfnding.

**Comment by deurklink** [comment]
Almost looks like RCT1 pathfinding now

**Comment by deurklink** [comment]
![image](https://user-images.githubusercontent.com/6469413/52800961-21f10680-307d-11e9-8532-0c9015a0f158.png)
This is what it does to my double paths.. Obviously leads to guests getting lost.

**Comment by ZehMatt** [comment]
Looks like it. I think I wanted to eliminate the useless condition while forgetting removing the rest of it.
