### ISSUE TITLE
Park cannot be saved in a certain map

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#8701]
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** f32531c

Some of scenario(or park) cannot be saved with error: "Game save failed!"
But _autosave works_!
And it generates a save file anyway, but it is corrupted. Some maps seem to be partially saved.
Note that it is made from korea so may contain some korean letters.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open a map
2. Try to save
3. Error message occurs
4. Although the save file is generated, it's contents is corrupted. Also it is not loadable.
5. However autosaves are correctly saved and could be loaded.

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/10726524/52536791-68efab00-2da2-11e9-9cbe-b7ad42e6a022.png)
(Please ignore lots of question marks, it is written in korean)

**Save game:**
[saved_failed_maps.zip](https://github.com/OpenRCT2/OpenRCT2/files/2849154/saved_failed_maps.zip)
```
Dong-Seo-Nam-Buk.sc6 : scenario file that has error
Dong-Seo-Nam-Buk_saved_failed.sv6 : saved file with corruption after error occurs (~1KiB)
MultiplayMap_v3.1.sv6 : save file that has error
MultiplayMap_v3.1_saved_failed.sv6 : saved file with corruption (~1.4KiB)
```

**Comment by phillipwalters** [comment]
I wasn't able to replicate this in Linux. Dong-Seo-Nam-Buk.sc6 loads and I can save based on that just fine.

**Comment by AaronVanGeffen** [comment]
Thanks for checking it out. OpenRCT2's Unicode handling works differently on Windows, so this still warrants further investigating, though.

**Comment by phillipwalters** [comment]
I just gave it a go in Windows 10 as well, and I was able to save to file names with Hangul characters. I only tried two, though:

**Comment by telk5093** [comment]
@phillipwalters I've tried to save Dong-Seo-Nam-Buk.sc6 into these:
```
Make a name for your paradise.sv6 (<= default park name)
test.sv6
ㄱㄴㄷㄹ.sv6
```

Whatevery I try, it fails to save.
And

**Comment by phillipwalters** [comment]
@telk5093 Sorry it took so long, but I was able to save this map in Windows with the same file names as you including in a directory that has Korean characters in the name. I'm pretty new to this project, but I'll try to poke around and see if I can find anything.

**Comment by telk5093** [comment]
@phillipwalters thanks for reviewing but my directory path was ``C:\Users\TELK\Documents\OpenRCT2\save``, it doesn't contain korean characters.

**Comment by phillipwalters** [comment]
Ah, in your screenshot it looked like it was. I tried in a directory without Korean characters as well, though.

**Comment by phillipwalters** [comment]
@telk5093 Which version are you running?

**Comment by telk5093** [comment]
@phillipwalters I always use the latest development version. I've tested at 5538fe3 again and it doesn't have solved.

**Comment by phillipwalters** [comment]
@duncanspumpkin Mind if I submit a PR with a few lines to log save game errors to the console?

**Comment by duncanspumpkin** [comment]
Sure go ahead

**Comment by phillipwalters** [comment]
@telk5093 I've added some code to print save error messages to the console. Not sure when it'll be in the release, but when you get a chance, run the game with the command prompt and let me know what you get.

**Comment by duncanspumpkin** [comment]
It is in the most recent develop version so if you could re run with that version it would be great.

**Comment by telk5093** [comment]
I've checked in 8bf6939, and there were no such error message on console.

1. First, I've run the game by openrct2.com, not openrct2.exe to see command prompt.
2. I tried to open _Dong-Seo-Nam-Buk.sc6_ scenario
3. Below error messages have occured:
```
ERROR[c:\projects\openrct2-ject9\src\openrct2\object\objectfactory.cpp:229 (ObjectFactory::CreateObjectFromLegacyFile)]: Error: Unable to open 'D:\Games\OpenRCT2\ObjData\LITTERPA.DAT' when processing object D:\Games\OpenRCT2\ObjData\LITTERPA.DAT
[rct2.dlc.litterpa] Warning (3): Unable to open 'D:\Games\OpenRCT2\ObjData\LITTERPA.DAT'
ERROR[c:\projects\openrct2-ject9\src\openrct2\object\objectfactory.cpp:229 (ObjectFactory::CreateObjectFromLegacyFile)]: Error: Unable to open 'D:\Games\OpenRCT2\ObjData\BIGPANDA.DAT' when processing object D:\Games\OpenRCT2\ObjData\BIGPANDA.DAT
[rct2.dlc.bigpanda] Warning (3): Unable to open 'D:\Games\OpenRCT2\ObjData\BIGPANDA.DAT'
ERROR[c:\projects\openrct2-ject9\src\openrct2\object\objectfactory.cpp:229 (ObjectFactory::CreateObjectFromLegacyFile)]: Error: Unable to open 'D:\Games\OpenRCT2\ObjData\ZPANDA.DAT' when processing object D:\Games\OpenRCT2\ObjData\ZPANDA.DAT
[rct2.dlc.zpanda] Warning (3): Unable to open 'D:\Games\OpenRCT2\ObjData\ZPANDA.DAT'
ERROR[c:\projects\openrct2-ject9\src\openrct2\object\objectfactory.cpp:229 (ObjectFactory::CreateObjectFromLegacyFile)]: Error: Unable to open 'D:\Games\OpenRCT2\ObjData\SCGPANDA.DAT' when processing object D:\Games\OpenRCT2\ObjData\SCGPANDA.DAT
[rct2.dlc.scgpanda] Warning (3): Unable to open 'D:\Games\OpenRCT2\ObjData\SCGPANDA.DAT'
ERROR[c:\projects\openrct2-ject9\src\openrct2\object\objectfactory.cpp:229 (ObjectFactory::CreateObjectFromLegacyFile)]: Error: Unable to open 'D:\Games\OpenRCT2\ObjData\PANDAGR.DAT' when processing object D:\Games\OpenRCT2\ObjData\PANDAGR.DAT
[rct2.dlc.pandagr] Warning (3): Unable to open 'D:\Games\OpenRCT2\ObjData\PANDAGR.DAT'
```
4. I've downloaded all missing objects from nedesigns and retried.
5. No additional error messages occured and saving has failed again.

**Comment by phillipwalters** [comment]
I'll have to try downloading those and see if I can get anywhere. It might be a few days, though.

**Comment by phillipwalters** [comment]
Those files aren't in ObjData on my install. They reside in what for you would be c:\projects\openrct2-ject9\object. Maybe try putting them there? Beyond that, I'm about at the end of what I can realistically help with on this one. Sorry, but maybe someone who's a bit more familiar with the project can help.

**Comment by telk5093** [comment]
Add: Even ```Panda World``` cannot be saved for me

**Comment by Gymnasiast** [comment]
@telk5093 Do you still get this bug?

**Comment by telk5093** [comment]
@Gymnasiast I can't reproduce this anymore since the save files themselves are not even able to load.
Maybe the save files are corrupted, imo.

However, loading scenarios and saving them was now successful, I think you may close this issue.
