### ISSUE TITLE
Mountain tool clipping large scenery

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#8706]
Mountain tool has clipping issues with large scenery and paths. Likely introduced during game action refactor. Look at map clear at.

**Comment by hokasha2016** [comment]
Me and my team would like to attempt in fixing this issue

**Comment by Broxzier** [comment]
@hokasha2016 Thanks for offering, but a pull-request to fix this has already been submitted by Duncan: https://github.com/OpenRCT2/OpenRCT2/pull/8707
