### ISSUE TITLE
Use CoordsXYZ for _currentTrackBegin and _previousTrackPiece

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#8725]
Refactor `_currentTrackBeginX`, `_currentTrackBeginY`, `_currentTrackBeginZ` into `_currentTrackBegin` by using the `CoordsXYZ` struct.

Same changes apply to `_previousTrackPiece`

See `Ride.cpp`.

**Comment by ndngo** [comment]
Hello @duncanspumpkin, I would like to help with this issue!

**Comment by duncanspumpkin** [comment]
Great. It shouldn't be too hard to find what needs changed. Let me know if you have any issues.

**Comment by ndngo** [comment]
Hello @duncanspumpkin, is the scope of the refactoring limited to `Ride.cpp` or should I also refactor all the instances where `_currentTrackBegin` and `_previousTrackPiece`?

**Comment by IntelOrca** [comment]
@ndngo Do it for all references across all source files.

**Comment by duncanspumpkin** [comment]
#8759 has fixed this
