### ISSUE TITLE
Remove gTrackGroundFlags by returning it within GameActionResult

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#8726]
After #8694 is finished the `gTrackGroundFlags` can be removed. Will require returning a subclass of GameActionResult with the correct additional field.

This will help reduce number of global vars that litter the codebase.

**Comment by Nazey** [comment]
#8694 is merged currently, is this issue ready to be worked on?

**Comment by ZehMatt** [comment]
Yep

**Comment by Nazey** [comment]
Cool, would definitely like to give this a go. What exactly did gTrackGroundFlags do?

**Comment by duncanspumpkin** [comment]
Its used to indicate if you are trying to build underground or above ground. This won't be super easy to do you first need to make a new subclass of GameActionResult which can pass back the value to the callee. `RideCreateGameActionResult` is an example of a subclass that we created to pass back the ride index to the callee. You will need to create something similar.

**Comment by Nazey** [comment]
Yeah, if it is going to be similar to `RideCreateGameActionResult`, then it may be beyond our skill level. Thanks for looking out.

**Comment by duncanspumpkin** [comment]
Well i can help guide you through it. I think you will learn lots trying.

**Comment by Nazey** [comment]
Ok, I am willing to try, but I don't even know where to start besides possibly creating the subclass.

**Comment by ZehMatt** [comment]
Thats a good place to start, thats what you want to return at the end. This subclass allows you to transfer more data into the result for later use, like in the callback.

**Comment by duncanspumpkin** [comment]
So the first thing you need to do is take a look at `TrackPlaceAction`. You want this game action to return instead of a `GameActionResult` a `TrackPlaceActionResult`. This `TrackPlaceActionResult` will be a subclass of `GameActionResult`. 

The subclass has to include one new field for the extra track ground flags.

After creating the subclass you will need to change every reference to `GameActionResult` within `TrackPlaceAction` into `TrackPlaceActionResult`. As soon as you change the macro in line 22 it should start telling you where there are issues. Every `std::make_unique<GameActionResult>` will need changed to `std::make_unique<TrackPlaceActionResult>`. If I used the helper function `MakeResult` that will need changed into `std::make_unique<TrackPlaceActionResult>`.

When you are doing this you might notice that the first parameter is always the same `STR_RIDE_CONSTRUCTION_CANT_CONSTRUCT_THIS_HERE`. Perhaps make your subclass set this in its constructor to save putting it in every call. This part is optional.

After making these changes to `TrackPlaceAction` you will then have to change the callbacks `RideConstructPlacedForwardGameActionCallback` and `RideConstructPlacedBackwardGameActionCallback` within `src/openrct2-ui/windows/RideConstruction.cpp`. Start by just changing the `GameActionResult` into `TrackPlaceActionResult` within the declaration.

Finally you can adjust `RideConstruction.cpp#L1809` using the value from the `TrackPlaceActionResult` instead of the global variable.

Check it all compiles and works. You will know it works if the game knows to turn underground mode on whilst placing tracks that go from above ground to underground.

Finally remove the global variable.

**Comment by Nazey** [comment]
Ok, I am still a bit confused on `TrackPlaceAction`. It is a class, correct? We cannot seem to find any reference to it. `TrackPlaceActionResult` is the class we are to create, so should that go inside of the `actions` folder in libopenrct2?

**Comment by duncanspumpkin** [comment]
`TrackPlaceAction` is a class but its definition is hidden a bit as we use the macro `DEFINE_GAME_ACTION` to do some magic. Create the new normal class at the top of the `TrackPlaceAction.hpp` file and adjust the game action result within `DEFINE_GAME_ACTION(TrackPlaceAction, GAME_COMMAND_PLACE_TRACK, *******)`.

If you look at `RideCreateAction.hpp` you will see we created the `RideCreateGameActionResult`. You're basically making the exact same thing but for the track place.

**Comment by Nazey** [comment]
Sorry for no response for the past week, schoolwork was a bit of a burden. Anyways, I can't seem to find TrackPlaceAction.hpp anywhere in the xcode project.

**Comment by duncanspumpkin** [comment]
Are you using the latest commit? xcode often gets forgotten because I personally can't add files to it. Feel free to add it. It should be in src/openrct2/actions.

**Comment by Nazey** [comment]
Huh, doesn't look like it is there, but there seems to be a conflict between the src folder and the xcode project itself. It shows a bunch of .hpp and .cpp files, but barely any of them show up in the xcode project. I guess they just need to be added from the xcode interface?
![Screen Shot 2019-03-11 at 12 21 56 PM](https://user-images.githubusercontent.com/16726699/54139715-842cf500-43f8-11e9-8912-6471da040252.png)
![Screen Shot 2019-03-11 at 12 23 12 PM](https://user-images.githubusercontent.com/16726699/54139716-84c58b80-43f8-11e9-8d6d-d7d573eb440c.png)

**Comment by ZehMatt** [comment]
Since all game actions are headers only we don't require to add those into the xcode project currently, most people don't have OSX to include them in the project.

**Comment by duncanspumpkin** [comment]
Are you using the latest commit? That might explain why they aren't in your source folder yet.

**Comment by Nazey** [comment]
Yep, wasnt paying attention. Using latest commit now.

**Comment by Nazey** [comment]
Ok, for the extra field for the ground flags, should it be a public variable like below, or make the variable private and have a function that returns that value?
![Screen Shot 2019-03-13 at 12 22 13 PM](https://user-images.githubusercontent.com/16726699/54296247-ecabdb80-458a-11e9-99fa-d666afa2e506.png)

**Comment by ZehMatt** [comment]
At the moment we just leave them public for the result, so thats fine.

**Comment by duncanspumpkin** [comment]
I'd just make it public there is no issues with access for this. Ps. I think you might need a constructor that takes: error, error message and error args. And the default constructor should still pass `STR_CANT_CREATE_NEW_RIDE_ATTRACTION` instead of 0.

**Comment by Nazey** [comment]
Ok. Would the new constructor just look like this? 
`    TrackPlaceActionResult(GA_ERROR error, rct_string_id message, uint8_t* args)
    : GameActionResult(error, STR_CANT_CREATE_NEW_RIDE_ATTRACTION, message)
    {
    }`
I don't know where the args would be used in the constructor.

**Comment by Nazey** [comment]
Messed around with the code a bit more, and when I was trying to compile it (just for fun) I noticed it was erroring out `TrackPlaceActionResult` saying it needed an overloaded constructor with 3 and 4 arguments, so I kind of replicated the constructors with GameActionResult, and it actually compiled and ran. It's definitely not right, as I still don't know what needs to go inside of those constructors.
![picture](https://user-images.githubusercontent.com/16726699/54401681-ffafd000-469e-11e9-9b12-bd00ef597fbf.png)

**Comment by ZehMatt** [comment]
You don't need them all, TrackPlaceActionResult should always use STR_CANT_CREATE_NEW_RIDE_ATTRACTION as the title and requires only error type and message. If args is unused you don't need the overload.

**Comment by Nazey** [comment]
That's what I thought as well, but when I started changing `std::make_unique<GameActionResult>` to `std::make_unique<TrackPlaceActionResult>` it errors out saying that it needs one with 3, 0, and 4 arguments. Am I doing something wrong here?

**Comment by duncanspumpkin** [comment]
Yes i think zehmatt is forgetting that there is an args requirement. You need to remove the errorTitle from each of the make uniques since that is set by the new constructors

**Comment by Nazey** [comment]
@duncanspumpkin Am I supposed to remove the `rct_string_id title` from each constructor args? Or rather from something along the lines of this:
` return std::make_unique<TrackPlaceActionResult>(
                    **GA_ERROR::DISALLOWED**, STR_RIDE_CONSTRUCTION_CANT_CONSTRUCT_THIS_HERE, STR_LAND_NOT_OWNED_BY_PARK);
            }`

**Comment by Nazey** [comment]
Ok, think I have the right constructors now, game compiles fine, I changed `RideConstructPlacedForwardGameActionCallback` and `RideConstructPlacedBackwardGameActionCallback ` to account for the new subclass, but what do I actually check for the new variable `GroundFlagCount` that I have created to make sure that the game changes to underground mode?

![picture](https://user-images.githubusercontent.com/16726699/54496100-b4c1d280-48c1-11e9-8f20-d1e6f7d2ee89.png)

**Comment by Nazey** [comment]
I really don't know where to go from here.

**Comment by duncanspumpkin** [comment]
Why don't you PR what you have and we can discuss it. The line you have highlighted you need to remove `gTrackGroundFlags` and replace it with `res->GroundFlagCount`
