### ISSUE TITLE
RCT closing while trying to build more attractions

### ISSUE THREAD

**Issue by crispinhatt** [OpenRCT2/OpenRCT2#8727]
**OS:** [e.g. Windows 10]
**Version:** 0.2.1
**Commit/Build:** 8ac731e

**Steps to reproduce:**
1. have a park with 110 attractions
2. try to put more attractions that are not on the "transport" tab

**Dump file**

[OpenRCT2 Dump.zip](https://github.com/OpenRCT2/OpenRCT2/files/2881440/OpenRCT2.Dump.zip)
**Screenshots / Video:**

![capturar](https://user-images.githubusercontent.com/42774384/53038610-ef1f8780-345b-11e9-92de-d1ec6cde2033.PNG)

**Save game:**

[Six Flags do fgordo.zip](https://github.com/OpenRCT2/OpenRCT2/files/2881443/Six.Flags.do.fgordo.zip)

**Comment by duncanspumpkin** [comment]
Please fill in the form correctly as it saves us time working out what has give wrong. I've edited your post with the details from the screenshot.

**Comment by crispinhatt** [comment]
> Please fill in the form correctly as it saves us time working out what has gone wrong. I've edited your post with the details from the screenshot.

sorry, it's my first time posting something here on github, I'm kind of lazy about it.

**Comment by IntelOrca** [comment]
@crispinhatt It is likely this issue is fixed in the latest develop version. Try using that.

**Comment by duncanspumpkin** [comment]
It's fine just try to remember it in future. Makes things nice and neat.

**Comment by Gymnasiast** [comment]
You're using the 0.2.1 release (commit 8ac731e). You didn't fill that in correctly, but the screenshot tells us that. I have tried using this file on the current develop. Here, it doesn't crash any more. Please update your game to the latest `develop`. One thing to note, however, is that you used all 255 slots: 110 rides, 70 stalls, 75 facilities.

I did notice that the error message I got when trying to place a new ride wasn't complete - it only showed the error title, but no explanation.

**Comment by crispinhatt** [comment]
> You're using the 0.2.1 release (commit [8ac731e](https://github.com/OpenRCT2/OpenRCT2/commit/8ac731e2124ecfb43f592c7f1cc5dd6902d5d83f)). You didn't fill that in correctly, but the screenshot tells us that. I have tried using this file on the current develop. Here, it doesn't crash any more. Please update your game to the latest `develop`. One thing to note, however, is that you used all 255 slots: 110 rides, 70 stalls, 75 facilities.
> 
> I did notice that the error message I got when trying to place a new ride wasn't complete - it only showed the error title, but no explanation.

is there any possibility of increasing the number of maximum slots in a future update?

**Comment by duncanspumpkin** [comment]
Eventually but we need a new save format first
