### ISSUE TITLE
Issue with Host moving peeps or staff members desync multiplayer

### ISSUE THREAD

**Issue by ageekhere** [OpenRCT2/OpenRCT2#8731]
**OS:** Windows 10
**Version:** Version 0.2.1 build 971480b
**Commit/Build:** 8ac731e
**Map** crazy castle
**Number of players** 2

I am guessing this is already i known issue, just posting my findings. 

When the Host picks up a peep or staff member and moves it, it will often trigger a desync for the clients. However if a client moves a peep or staff member it does not seem to cause a desync (More testing is still needed to determine if a client can cause a desync by moving peeps and staff members).

It seems to be an issue with the host moving peeps or staff member (creating staff members too). Could be that the host is not sending the correct data to the clients.
 
- [ ] Reproducible in RCT2 (vanilla)? NA
- [ ] Specific to multiplayer? Yes

**Steps to reproduce:**
1. Host selects a peep or staff member and moves it to a new location
2. Client often desync

**Comment by ZehMatt** [comment]
Thanks for the report. We are currently working on moving more game commands towards the new game action system to prevent desyncs, moving the peep is not ported yet so please bare with us, we are working on it.

**Comment by ageekhere** [comment]
Has this issue been fixed?

**Comment by ZehMatt** [comment]
Yes
