### ISSUE TITLE
Incomplete warning when all ride slots are full

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#8736]
**OS:** Ubuntu 18.04
**Version:** 0.2.1+
**Commit/Build:** 9a746c4

1. Load the save in #8727
2. Try building a new ride
3. Error message has a title ("Cannot create ride/attraction"), but lacks the explanation.

**Comment by duncanspumpkin** [comment]
I get too many rides/attractions

**Comment by duncanspumpkin** [comment]
One bug is that the title has been cutoff `STR_CANT_CREATE_NEW_RIDE_ATTRACTION` is the title and should be in the GameActionResult.

**Comment by Gymnasiast** [comment]
Hm, I might have been on an older build than 9a746c4 . I will test when I get to my own system.

**Comment by Gymnasiast** [comment]
Tried it at d31e92e652965c84df4939adb2554edf11496a95 . It gives an explanation ("Too many rides/attractions") but no title.
