### ISSUE TITLE
savegame from original game crashes when cruising through map

### ISSUE THREAD

**Issue by Sakraloperette** [OpenRCT2/OpenRCT2#8739]
b7db6cb
MacOS

hey guys,

first of all, thank you all so much for developing may childhood fav game. 
Im currently playing on OpenRCT2-0.2.1-develop-b7db6cb-macos, but had this issue with previous builds of 0.21 (before that I didnt know about openrct).

when Im browsing through a map of certain old save games, the game crashes instantly. I found out, that it depended on certain attractions that the game couldn't show. I have the clipboard of the error that macOS gave me:

Application Specific Information:
Assertion failed: (false), function vehicle_visual_splash_effect, file /Users/travis/build/OpenRCT2/OpenRCT2/src/openrct2/ride/VehiclePaint.cpp, line 3096.
( i have more, if you need the longer version just say it)

The attractions which caused the crash were "launched free fall" (this is weird, because I can build a new free fall tower within this exact loaded game and it doesnt crash) and "observation tower".

would be great if you guys can fix this, so my games wont crash anymore!

thanks in advance!

**Comment by Sakraloperette** [comment]
ok it seems that it not those two rides, but another one. i assumed it, because the game crashed when clicking on the rides through the "Rides/Attractions in Park" window. But its another ride, that would also be shown in the ride-overview-window. It has to be the bumpercars ride in my game, because I demolished all attractions and shops but the bumpercars ride, and the game crashes when opening the ride. Weird none the less, because I can build a new bumpercar ride without crashing.

**Comment by duncanspumpkin** [comment]
Can you upload the save game.

**Comment by Sakraloperette** [comment]
sure. this is the one where I deleted most of the rides but it still crashes. Just load the game and scroll to the left then it will crash (at least over here it does).
[crashtest.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/2895330/crashtest.sv6.zip)

**Comment by IntelOrca** [comment]
@Sakraloperette Thanks, could you also upload the original SV4?

**Comment by Sakraloperette** [comment]
here you go. 
[Pacific Pyramids.SV4.zip](https://github.com/OpenRCT2/OpenRCT2/files/2896787/Pacific.Pyramids.SV4.zip)
