### ISSUE TITLE
openrct2/openrct2-cli container crashes immediately

### ISSUE THREAD

**Issue by Meulen92** [OpenRCT2/OpenRCT2#8767]
**OS:** Linux/Docker
**Version:** develop
**Commit/Build:** 6a0cff267611ab196ef4ccf1ef832bc1dd95911d

The docker image openrct2/openrct2-cli is broken since this release.
It refuses to even print a single line of output on trying to run the container.

**Steps to reproduce:**
1. docker run --rm -p 11753:11753 -it openrct2/openrct2-cli:develop host \<path to save\>

Thank you for your support!
Keep up the good work.

**Comment by IntelOrca** [comment]
I can't reproduce this.
Does the following command work?

`docker run --rm openrct2/openrct2-cli:develop --version`

**Comment by Meulen92** [comment]
$ docker run --name openrct2 openrct2/openrct2-cli:develop --version
OpenRCT2,  (da03305 on develop)
Linux (x86-64)

$ docker run -d --name openrct2 -p 11753:11753 -it openrct2/openrct2-cli:develop host game.sc6
$ docker logs openrct2
$

Empty log and no container running.

**Comment by IntelOrca** [comment]
What is `game.sc6`? Is that something you have added to the container?

**Comment by Meulen92** [comment]
Thanks for your time @IntelOrca.

The docker container works again since this update:

$ docker run --name openrct2 openrct2/openrct2-cli:develop --version
OpenRCT2,  (68730b3 on develop)
Linux (x86-64)

$ docker logs openrct2
ERROR[../src/openrct2/network/TcpSocket.cpp:143 (Listen)]: IPV6_V6ONLY failed. 92
object index out of date
Building object index (2100 items)
Unable to save index: '/home/openrct2/.config/OpenRCT2/objects.idx'.
Unable to open '/home/openrct2/.config/OpenRCT2/objects.idx'
Finished building object index in 0.06 seconds.
track design index out of date
Building track design index (506 items)
Unable to save index: '/home/openrct2/.config/OpenRCT2/tracks.idx'.
Unable to open '/home/openrct2/.config/OpenRCT2/tracks.idx'
Finished building track design index in 0.04 seconds.
scenario index out of date
Building scenario index (143 items)
Unable to save index: '/home/openrct2/.config/OpenRCT2/scenarios.idx'.
Unable to open '/home/openrct2/.config/OpenRCT2/scenarios.idx'
Finished building scenario index in 0.99 seconds.
Ready for clients...

**Comment by IntelOrca** [comment]
@Meulen92 You may have been running into #8769 which should be fixed now.

**Comment by IntelOrca** [comment]
Duplicate of #8767.
