### ISSUE TITLE
Incorrect Position on Load

### ISSUE THREAD

**Issue by PFCKrutonium** [OpenRCT2/OpenRCT2#878]
Load the same save file more than once, and the game will move you to a random corner of the map. Only seems to happen with the autosave save.

**Comment by Patrik356b** [comment]
I get that bug with the original rct2 game if i enter a scenario and return to the main menu afterwards. It only affects the menu though.

**Comment by rwjuk** [comment]
Cannot replicate - tried loading the same autosave over itself (with that save already active) and quitting to menu and reloading the save and did not get the random position bug.
