### ISSUE TITLE
Version info in Travis builds is incomplete

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/OpenRCT2#8782]
The git environment on Travis does not seem to be working as expected. `git describe` yields an empty string, and branch is set to HEAD instead.

Expected version line (local build):
```
OpenRCT2, v0.2.1-903-g5b0367 (g5b0367 on master, DEBUG)
```

Instead reads (Travis build):
```
OpenRCT2,  (g5b0367 on HEAD, DEBUG)
```

This is probably related to git clone depth: https://github.com/travis-ci/travis-ci/issues/7422. Hence, releases weren't affected when tested.

We may have to run `git fetch --unshallow` to get this info to show up properly, but I'd prefer not to do that as it probably slows down the CI builds quite a bit.

Related issue: https://github.com/OpenLoco/OpenLoco/issues/283

**Comment by AaronVanGeffen** [comment]
| Command | # Commits |
| ---- | --- |
| git rev-list v0.0.1..v0.0.2 --count   | 3573 |
| git rev-list v0.0.2..v0.0.3 --count   | 1595 |
| git rev-list v0.0.3..v0.0.3.1 --count | 11   |
| git rev-list v0.0.3.1..v0.0.4 --count | 1534 |
| git rev-list v0.0.4..v0.0.5 --count   | 3592 |
| git rev-list v0.0.5..v0.0.6 --count   | 453  |
| git rev-list v0.0.6..v0.0.7 --count   | 624  |
| git rev-list v0.0.7..v0.1.0 --count   | 730  |
| git rev-list v0.1.0..v0.1.1 --count   | 284  |
| git rev-list v0.1.1..v0.1.2 --count   | 1756 |
| git rev-list v0.1.2..v0.2.0 --count   | 795  |
| git rev-list v0.2.0..v0.2.1 --count   | 334  |
| git rev-list v0.2.1..develop --count   | 890  |

I think we'd be fine if we increased the depth to the last 1000 commits.

Travis only allows specifying up to 50 commits, however. We _can_ manually run `git fetch --depth=1000`, or indeed go all the way with `git fetch --unshallow`.

Thoughts? @janisozaur

**Comment by duncanspumpkin** [comment]
What are the implications of the change? Does it just take longer to compile? Are we talking seconds, minutes, hours?

**Comment by AaronVanGeffen** [comment]
It will take some time to fetch the commits in question, yes. Should be in the order of tens of seconds, but I have not tested this on Travis yet. We could include it as `time git fetch --depth=1000` to see the overhead it would add, though.

**Comment by AaronVanGeffen** [comment]
https://travis-ci.org/OpenRCT2/OpenRCT2/jobs/499188143
```
$ time git fetch --depth=1000
[...]
real	0m17.761s
user	0m20.924s
sys	0m1.344s
```

**Comment by tomlankhorst** [comment]
I suggest a [condition](https://docs.travis-ci.com/user/conditions-v1) that checks whether the commit is tagged. 
Then, run fetch with `--shallow-since` a year ago. 
The version output only matters for releases, devel builds have access to all commits anyway.

**Comment by AaronVanGeffen** [comment]
Shallow clones only fetch tags if they relate to the fetched commits. The issue here is that we version our builds based on the offset of the current commit compared to the last release. Currently, there have been over 900 commits since v0.2.1. This implies the v0.2.1 tag is not fetched, unless …
