### ISSUE TITLE
Tile Inspector Improvements

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#8791]
After #8781 the tile inspector broken column is now a path only flag (it used to also show if a block brake was closed). It should be moved out of the column and into the group box.

In addition we should expose the `BLOCK_BRAKE_CLOSED` flag and the `INDESTRUCTIBLE_TRACK_PIECE` on the track group box. `BLOCKED_BY_VEHICLE` could also be exposed in the footpath group box but I think it gets reset possibly every tick so might not be useful.

**Comment by joshtucker132** [comment]
@Broxzier Are you still working on this issue?

**Comment by Broxzier** [comment]
@joshtucker132 I haven't started yet, feel free to work on it.

**Comment by joshtucker132** [comment]
How do you access the group boxes?

**Comment by jmyre1999** [comment]
@Broxzier What are group boxes?

**Comment by duncanspumpkin** [comment]
The group box is the tile type specific box at the bottom. Circled red

![image](https://user-images.githubusercontent.com/1277401/56075603-e5abff00-5dbc-11e9-9ab6-6671e6976fa1.png)

https://github.com/OpenRCT2/OpenRCT2/pull/8574 was a PR that added a new detail to a group box. It may give clues on how best to modify the window to add the required new detail.

**Comment by jmyre1999** [comment]
How do I access the tile inspector? I thought it would be available but enabling debug tools but the button still isn't there.

**Comment by jmyre1999** [comment]
Do you want the BLOCK_BRAKE_CLOSED flag and the INDESTRUCTIBLE_TRACK_PIECE to be put in the track details section of the group box?

**Comment by duncanspumpkin** [comment]
Yes put both those in the group box

**Comment by jmyre1999** [comment]
I pretty much got it, just not sure about getting the proper string

**Comment by duncanspumpkin** [comment]
Do you mean new strings? Feel free to make a draft PR if you want help.

**Comment by Broxzier** [comment]
@jmyre1999 I just made a similar change to the tile inspector, maybe this helps you find what you need: https://github.com/OpenRCT2/OpenRCT2/pull/9128/commits/ac7bc977367be8839f2a4647dd87f2155d704ff6

Mainle the changes in `en-GB.txt`, `StringIds.h` and `TileInspector.cpp`.

**Comment by joshtucker132** [comment]
Should the broken flag show up in the group box only if it evaluates to true?

**Comment by duncanspumpkin** [comment]
Ideally have it the same as all of the other group box flags and make it clickable.

**Comment by joshtucker132** [comment]
What do you mean by clickable? Nothing appears to happen when I click on any of the other flags. Do you mean make it a check box?

**Comment by duncanspumpkin** [comment]
Yeah a check box.

**Comment by joshtucker132** [comment]
![Screen Shot 2019-04-23 at 12 14 51 PM](https://user-images.githubusercontent.com/46719255/56597940-81115100-65c1-11e9-85d8-0ceaeb9279b2.png)

So something like this?

**Comment by jmyre1999** [comment]
@Broxzier Your commit you referenced me to was of great help, thank you

@duncanspumpkin Should BLOCK_BRAKE_CLOSED and INDESTRUCTIBLE_TRACK_PIECE be clickable as well?

**Comment by duncanspumpkin** [comment]
Yes i think that would make sense. I'm not sure when the block brake one would be useful but no harm adding it

**Comment by joshtucker132** [comment]
@duncanspumpkin I'm having trouble getting the checkbox to stay selected. If I hold down the mouse, a checkmark appears, but as soon as it is released the checkmark disappears and a small red line appears below the checkbox. Any advice on how to fix this issue? I tried to follow the implementation of the "sloped" flag. Is there another flag that is more comparable to the "broken" one?

**Comment by duncanspumpkin** [comment]
Create a draft pr and we will be able to take a look. I'm not very knowledgeable on our windows so will need to see code.

**Comment by jmyre1999** [comment]
I believe I have gotten all functionality working properly, but I am having issues with my newly defined strings. For some reason, when I try to use them they instead result in {undefined string} rather than my defined values. 
![image](https://user-images.githubusercontent.com/39494196/56856700-2adc3f00-692e-11e9-9825-ca49b02e3357.png) 
![image](https://user-images.githubusercontent.com/39494196/56856708-519a7580-692e-11e9-8dd6-af5d36f3b734.png) 
![image](https://user-images.githubusercontent.com/39494196/56856727-88708b80-692e-11e9-9dfb-fecc3b6110d0.png) 
![image](https://user-images.githubusercontent.com/39494196/56856733-9aeac500-692e-11e9-908b-df2b7a3b6d14.png)

**Comment by duncanspumpkin** [comment]
Do you symlink your data folders so that your language files are used when you run the game?

**Comment by jmyre1999** [comment]
That might be the problem. One of my team members ran my branch on their machine and did not have this issue.

Also, what is the block brake closed flag used for?

**Comment by duncanspumpkin** [comment]
When a train is going around a continuous block brake circuit track it will need to close and open the block brake as it proceeds through each section.

**Comment by jmyre1999** [comment]
Ah I see, thanks!
