### ISSUE TITLE
Can't place any trees on slopes

### ISSUE THREAD

**Issue by BirbSMB** [OpenRCT2/OpenRCT2#8793]
**OS:** Windows 10
**Version:** 0.2.1-47
**Commit/Build:** f0092b7

I literally can't place trees on sloped terrain the way it worked in vanilla RCT2. This latest update seems to have broken the way trees work. Not sure how...

**Comment by duncanspumpkin** [comment]
Can you give an example tree type.

**Comment by duncanspumpkin** [comment]
Okay I know the reason. Fixed in place scenery branch. #8773
