### ISSUE TITLE
Ensure tile_element_height is used correctly

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#8800]
`tile_element_height` is often used incorrectly. It returns the surface height `int16_t` and also the water height `int16_t` in one `sint32_t`.

The function needs to be modified to return a tuple and all callees need to be checked to ensure they are using the correct parts.

**Comment by duncanspumpkin** [comment]
Much better idea would be to split it into `tile_element_water_height` and `tile_element_height`. Returned value is a `coordZ` rather than a `tileCoordsZ` maybe have that as a comment as we don't have separate types for them yet.

**Comment by nicolewright** [comment]
Me and my team are going to work on this issue!

**Comment by duncanspumpkin** [comment]
Great. I think someone on gitter the other week mentioned they were looking into this as well. I've not seen any more about it though.

**Comment by lwatson2016** [comment]
So the return type is a tuple?

How should the coord.z variable be dealt with if tile_element_height returns a tuple<int16_t, int16_t> (tile_element_water_height, tile_element_height) ?

https://github.com/OpenRCT2/OpenRCT2/blob/9f2e1d74501ff064aac1ecc38cc3a3ab890afce0/src/openrct2/world/Map.cpp#L1374-L1381

**Comment by AaronVanGeffen** [comment]
As discussed above, you can split the function rather than changing it to return a tuple. In most cases, the water height is not needed, so outright splitting seems to be the more efficient solution.

**Comment by ZehMatt** [comment]
Also on a side note, don't use tuples when its a pair, theres std::pair :)

**Comment by nicolewright** [comment]
It doesn't seem like there's much of a difference between water tiles and surface tiles...where should i start when splitting the function?

**Comment by duncanspumpkin** [comment]
Water data is encoded into surface tiles. The vast majority of functions that call this function only care for the surface height. If the callee does a right shift of 16 with the result then it is obviously using the water height. You first need to create a second function that only does the water height calc. Then you can look at every caller and choose the correct combination.

**Comment by Nazey** [comment]
Ok. I can only find like one reference to water height, would it literally just be line 480 in `Map.cpp`? 
`uint32_t height = (tileElement->AsSurface()->GetWaterHeight() << 20) | (tileElement->base_height << 3);`

Or do we need to adjust for the slope of the water as well?

**Comment by duncanspumpkin** [comment]
The water height is just the tileElement->AsSurface()->GetWaterHeight() << 20 part. You need to make a function called get water height that returns that value. Don't forget that your function is no longer needing to be left shift by 16 so it would be << 4 or preferably * 16.

**Comment by nicolewright** [comment]
So is this all we need in the water height function? Still a bit confused on what all needs to be in there. 
![gitsceenshot](https://user-images.githubusercontent.com/46659974/55296866-4adf1800-53ed-11e9-8de3-19fd7c775896.JPG)

**Comment by duncanspumpkin** [comment]
Yup. Nice and simple function to return the bigZ water height at a known x/y coordinate. I think it should probably not return 16 on failure but instead return 0. This would match the old function. The slightly harder task is to work out which callers of `tile_element_height` need to be changed to `tile_element_water_height`.

**Comment by lwatson2016** [comment]
Should the original tile_element_height function return only the last 16 bits for the land height, so return an int16_t instead of int32_t?

If so, how should this be dealt with when the current call to tile_element_height fills an object with int32_t fields such as below? 

Other times, the int32_t returned from tile_element_height is passed to other functions requiring an int32_t parameter. How should we deal with this?

https://github.com/OpenRCT2/OpenRCT2/blob/e34e06db4ceb48ff4d0a104e7d299b097ea91365/src/openrct2/world/Map.cpp#L1279-L1283

**Comment by duncanspumpkin** [comment]
> Should the original tile_element_height function return only the last 16 bits for the land height, so return an int16_t instead of int32_t?

Yes I would say it should return an `int16_t`. But at the same time it doesn't matter if it returned a `int32_t`. The maximum value that this function will return is well within 15bits.

> If so, how should this be dealt with when the current call to tile_element_height fills an object with int32_t fields such as below?

Coord.z in that example below is an example of a variable that is incorrectly taking the water height when all it should have is the surface height. `network_set_player_last_action_coord` does not understand the water height data.

> Other times, the int32_t returned from tile_element_height is passed to other functions requiring an int32_t parameter. How should we deal with this?

That is where you will have to investigate to work out if it is doing this for the correct reasons (after all that is the name of this issue ;) ). Maybe the function does need the water data. Most of the time it doesn't.

**Comment by TruptiM18** [comment]
Hi, 
Is the issue still open? Can I work on it?

**Comment by Nazey** [comment]
We pr #9087 open right now for this.
