### ISSUE TITLE
Pause/Unpause freezing RCT1 levels

### ISSUE THREAD

**Issue by utechtl** [OpenRCT2/OpenRCT2#8832]
OS: [Win 10 x64 ]
Version: [e.g. 0.2.1]
Commit/Build: [e.g. 426e106]

On the original RCT1 levels pausing the game, changing the car count and unpausing the game causes intermittent freezing on the game. It's occurred on Funtopia and Barrony Bridge. The rides it's happened on are Spinning Wild Mouse, Log Flume, Go Karts, and Boat Hire. 

**Steps to reproduce:**
1. Pause game
2. Close ride
3. Change vehicle count for ride
4. Open ride
5. Unpause game

I can't get it to reproduce on command to grab a video of it, I've tried a few different times. I'll try again later tonight

**Comment by duncanspumpkin** [comment]
Scenarios are not special after loading. What do you mean by freezing. Decreased frame rate?

**Comment by utechtl** [comment]
Freezing as blue spinning wheel, prompting the wait or close program popup from windows.

On Mar 8, 2019, at 12:07 AM, Duncan <notifications@github.com<mailto:notifications@github.com>> wrote:


Scenarios are not special after loading. What do you mean by freezing. Decreased frame rate?

**Comment by Gymnasiast** [comment]
@duncanspumpkin It can still be a result of incorrectly importing SC4/SV4 files.

**Comment by Gymnasiast** [comment]
Do you still get this problem?

**Comment by Gymnasiast** [comment]
Issue seems to be abandoned, and OpenRCT2 has changed massively since then. Closing this.
