### ISSUE TITLE
Refactor Peep::TimeInPark for Staff/Guest.

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#8848]
For staff this field is used to track the employment date, for peeps its used to the track the time they have been in the park.

**Comment by devlontecron** [comment]
Hey, I wanna look into doing this but I'm confused on what you want refactor; Are you saying there should be a new field for staff?

**Comment by ZehMatt** [comment]
Sorry for the late response. The field is used for the Staff to track the employment date which uses ```gDateMonthsElapsed``` and for Guests the field tracks when they entered the park using ```gScenarioTicks```. So the best thing would be to pack this field into an union an add an additional one, something like:
```
union
{
    int32_t TimeInPark;
    int32_t HireDate;
}
```
Additionally it would be good to add new getter members to Staff and Guest that results the corresponding field. In the future we can decouple them when we have our own save format.

**Comment by aw20368** [comment]
I'll work on this. For guests, I think `TimeInPark` is misleading, can this be renamed to `ParkEntryTime` for example?

**Comment by duncanspumpkin** [comment]
Yes please rename it. don't forget to update the rct2 / rct1 structs if required as well
