### ISSUE TITLE
Game action errors are shown to everyone.

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#8851]
If the client does something via game actions that produces an error the host will also see the error message if its not headless, so do the other clients. Errors should be only shown to the client who invoked the game action and not everyone.

**Comment by duncanspumpkin** [comment]
Is that true for every action?

**Comment by ZehMatt** [comment]
Actually now that you mention it, its not the case, but there are some strange things happening.

**Comment by ZehMatt** [comment]
On further investigation it seems that this is caused by nested ones which aren't supposed to show anything since the top level action will deal with it. Will open a PR the next days
