### ISSUE TITLE
gCheatsEnableAllDrawableTrackPieces not networked

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#8859]
This is currently not networked. It should be added in Network::LoadMap and Network::SaveMap

**Comment by Gymnasiast** [comment]
Do you mean it should be on or off for everyone? I don't think it should, as it's mostly a UI cheat -- it unhides track pieces that do not properly fit the nature of the ride type. An example is steep inclines and log bumps on the Car Ride.

**Comment by ZehMatt** [comment]
Cheats can be only used on the server if I'm not mistaken, so if clients wants this cheat on they gotta ask for it, it should be networked like any other cheat imho.
