### ISSUE TITLE
RCT1 competition scenarios are classified incorrectly

### ISSUE THREAD

**Issue by realConfol** [OpenRCT2/OpenRCT2#8875]
**OS:** Windows 10
**Version:** 0.2.2
**Commit/Build:** 1d9b17a

If you have the competitions downloaded for rollercoaster tycoon deluxe, the competitions aren't considered original DLC Parks and when playing the scenario, the objective says build the best ... you can. Another issue is OpenRCT2 has more rides available that you can build like the Ferris Wheel. The Scenario is only suppose to have the themings available and the one specific ride that the name of the competition is. 
If you need the competitions, here is the official link: http://www.jumpjet.info/Classic-Games/Windows/RCT/Scenarios/Scenarios.html

- [ ] Reproducible in RCT2 (vanilla)? No
- [ ] Specific to multiplayer? No

**Steps to reproduce:**
1. Have any competition scenario from RCT1
2. Load it up in OpenRCT2
3. Go to Other parks and scroll down.
4. Click it.

**Save game:**
Here's an example of a broken competition in OpenRCT2:
[Competition Example.zip](https://github.com/OpenRCT2/OpenRCT2/files/2969172/Competition.Example.zip)

**Comment by Gymnasiast** [comment]
This is three issues, really:

- Classification
- Objective
- Research/availability

I have now changed this issue to be only about the first point, and will create separate issues for the other two.
