### ISSUE TITLE
Refactor format_string and family.

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#8876]
There are currently a lot of mixed cases on how its used. Some examples:
```c++
set_format_arg(0, uint32_t, peep->id);
utf8* curName = gCommonStringFormatBuffer;
rct_string_id curId = peep->name_string_idx;
format_string(curName, 256, curId, gCommonFormatArgs);
```
```c++
uint16_t args[] = { static_cast<uint16_t>(date_get_month(value)), static_cast<uint16_t>(date_get_year(value) + 1) };
uint16_t* argsRef = args;
format_string_part(dest, size, STR_DATE_FORMAT_MY, (char**)&argsRef);
```
```c++
set_format_arg(0, uint32_t, _window_guest_list_groups_argument_1[i]);
set_format_arg(4, uint32_t, _window_guest_list_groups_argument_2[i]);
set_format_arg(10, uint32_t, numGuests);
gfx_draw_string_left_clipped(dpi, format, gCommonFormatArgs, COLOUR_BLACK, 0, y, 414);
```

Also set_format_arg would write to the global variable gCommonFormatArgs where this should be ideally a user provided buffer and better yet not having the need of a variable like this.

format_string could be something like sprintf where its using variadic arguments, to keep it type safe this can be implemented using variadic template arguments.

Refactoring this will be probably a huge effort but improves overall the entire code base, also making the use format_string and such thread safe by avoiding the global variable.

**Comment by duncanspumpkin** [comment]
You can't get rid of the global format args very easily it's very embedded into everything.

**Comment by IntelOrca** [comment]
There are a lot of usages which you can fix easily. The hard ones will be where functions only set the arguments but don't actually invoke the format, e.g. hover status.

**Comment by ZehMatt** [comment]
I already planned on doing some PR's on that. The first thing on the list would be to simply introduce a new function and then gradually replace those instances, I need to first get a better understanding on how exactly the string comes together, the way the data is stacked upon those temporary buffers is hard to grasp.

**Comment by ZehMatt** [comment]
I believe this is mostly solved
