### ISSUE TITLE
Submarine Ride does not count as indoors

### ISSUE THREAD

**Issue by autofire372** [OpenRCT2/OpenRCT2#8882]
**OS:** Windows 10
**Version:** 0.2.2
**Commit/Build:** 57b8fba32

The Submarine Ride, despite having enclosed vehicles, does not count as an indoor ride; consequently, guests will refuse to ride it when it is raining.

The attached save was made during rain, so reproducing this should be as simple as checking what guests are thinking about "Space Subs".

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1.  Open any scenario that starts you with the Submarine Ride
2. Build one of any length and open it
3. Wait for rainfall or use the cheats menu to force it to rain, and watch as guests refuse to ride the fully-enclosed subs.

**Dump file**

**Screenshots / Video:**
![Leafy Lake 2019-03-15 18-44-41](https://user-images.githubusercontent.com/8486750/54465754-24fe1600-4753-11e9-9dfb-8e8d1a44c63d.png)

**Save game:**
[SubBug.zip](https://github.com/OpenRCT2/OpenRCT2/files/2973160/SubBug.zip)

**Comment by Gymnasiast** [comment]
I have updated the object: https://github.com/OpenRCT2/objects/commit/45c087219b5648d45b88776134f8e9b9925a7c63

An objects release is needed before this fix lands in OpenRCT2 proper, though.

**Comment by Gymnasiast** [comment]
This should now have been fixed. Could you update your game and check?

**Comment by Gymnasiast** [comment]
This should now have been fixed. Could you update your game and check?

**Comment by Gymnasiast** [comment]
Requires adjustment of RideRatings.cpp.
