### ISSUE TITLE
Peep tracking is not synchronized.

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#8900]
Enabling peep tracking on a multiplayer session will cause a desync as the flags are set directly without the server knowing about it.

**Comment by janisozaur** [comment]
There's a similar problem where the handymen will have a "flashing" state set to them when being observed via a map. It might have an issue reported for that, don't remember.

**Comment by ZehMatt** [comment]
I think I fixed that one ages ago by using a separate array, might be a different issue you are talking about.
