### ISSUE TITLE
All staffs with the same number share the patrol area

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#8910]
**OS:** Windows 10
**Version:** 0.2.2
**Commit/Build:** 8bf6939

All staffs who have the same number share the same patrol area.
It was occured if there are staffs with the same number.

**Steps to reproduce:**
1. Open any scenario, for example, _Forest Frontier_.
2. Hire a handyman and a mechanic (or security, entertainer if you want)
3. Set a patrol area of handyman
4. Then the other staffs share the exact area with the handyman

See GIF below: (handyman and mechanic only)
![녹화_2019_03_18_02_04_15_673](https://user-images.githubusercontent.com/10726524/54494887-3d705b00-4922-11e9-8bdf-50112df54cef.gif)

**Comment by duncanspumpkin** [comment]
Lol staff index not set. Will fix it in a jiffy
