### ISSUE TITLE
Quickstart instructions for Fedora not working

### ISSUE THREAD

**Issue by leggettc18** [OpenRCT2/OpenRCT2#8913]
**OS:** Fedora Workstation 29
**Version:** 0.2.2
**Commit/Build:** 298c9f523 on HEAD, DEBUG

After following the Quickstart instructions on the website for Fedora Linux, the game does not work properly. The main menu buttons are visible and the music plays but no background or sound effects are present. Trying to launch in a scenario results in a box saying some scenario files are missing, downloading them does not work. Upon reading the wiki, I found more information that allowed the game to run properly. Specifically the `make install` step that created the necessary files. I also tried running it from the build directory with `./openrct2 --openrct-data-path=../data` but that caused an error to appear saying "Cannot open g2.dat". As I said, it does work fine after running `make install`

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Follow the QuickStart guide on the website for Fedora.
2. Attempt to run the game from the local directory.

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by IntelOrca** [comment]
Which website are you referring to? Can you provide a link?

**Comment by leggettc18** [comment]
I actually tried the Quickstart instructions for both of the following: https://openrct2.org/ and https://openrct2.io/

**Comment by IntelOrca** [comment]
The openrct2.org instructions don't cover building, only acquiring RCT2 files.

https://github.com/OpenRCT2/OpenRCT2/wiki/Building-OpenRCT2-on-Linux instructions are better, and it basically does say to do `make install`.

The instructions on https://openrct2.io/ are missing the bit about make install, so that needs correcting. This issue should probably be raised against https://github.com/OpenRCT2/openrct2.github.io.

**Comment by leggettc18** [comment]
Good point, I didn't think about raising it there. I'll do that. Although thinking about it now the best "solution" would be for a Fedora package to be made... perhaps I'll look into that.

**Comment by IntelOrca** [comment]
I know of one currently:
https://copr.fedorainfracloud.org/coprs/nauticalnexus/openrct2/

**Comment by Evidlo** [comment]
I also ran into the issue.  You just need to do `DESTDIR=. make install` after following the quickstart guide, as mentioned [here](https://github.com/OpenRCT2/OpenRCT2/wiki/Building-OpenRCT2-on-Linux#running-it-from-the-build-directory).

**Comment by Gymnasiast** [comment]
The build instructions have since been updated.
