### ISSUE TITLE
Whispering Cliffs: Incorrect win condition

### ISSUE THREAD

**Issue by WaxxyOne** [OpenRCT2/OpenRCT2#8921]
Windows 10

**Steps to reproduce:**
1. Start the Whispering Cliffs scenario in RCT: Corkscrew Follies
2. The Victory Condition requires a Park Value of $170,000 instead of the correct $17,000.

**Comment by AaronVanGeffen** [comment]
I believe this is intentional, to compensate for RCT1 using a different way of calculating the park value.

**Comment by Gymnasiast** [comment]
Exactly. Achieving a £170,000 park value in RCT2 is about as hard as achieving a £17,000 one in RCT1, which uses a wholly different park value calculation.

**Comment by Patrik356b** [comment]
Is stuff like this put up on the wiki?

**Comment by Gymnasiast** [comment]
It is now: https://github.com/OpenRCT2/OpenRCT2/wiki/FAQ-&-Common-Issues#i-loaded-an-rct1-savescenario-but-there-are-some-differences
