### ISSUE TITLE
Rides don't crash in test mode

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#8922]
**OS:** [Windows 10]
**Version:** [0.2.2]
**Commit/Build:** [a9e9993]

We're doing a round on my server where everyone has to make a cannon to launch a coaster vehicle as far as possible. However, we have to close our ride after spawning the car, because rides won't crash in test mode. I guess this is a leftover from when we had the option to stop crashing in test mode? Or is this supposed to happen?

**Comment by Broxzier** [comment]
You've probably enabled `no_test_crashes` once before. To turn it off, run this from the in-game console: `set no_test_crashes 0`.

**Comment by deurklink** [comment]
When testing it locally on my server pc, the rides crash as intended. As soon as i play in a server however, the rides stop crashing again. I used the above mentioned command a few times, both inside and outside the server but it didn't really seem to do much.

**Comment by duncanspumpkin** [comment]
I think your server must have it set. Its not a networked action so you will have to change the value from the server.

**Comment by duncanspumpkin** [comment]
I tried to reproduce the issue but was not successful.

**Comment by deurklink** [comment]
The console command didn't do anything when i used it in the server, from the host. In my config file i can see no_network_crashes is set to false. I have tried restarting the server, and doing the console command before and after restarting but i keep getting the same results. I also tried the console command in a single player game and starting the server after that but still same results.

**Comment by Gymnasiast** [comment]
Now we removed that option in favour of simulation, are you still having this issue?
