### ISSUE TITLE
Price sync is not able to check

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#8941]
**OS:** Windows 10
**Version:** 0.2.2
**Commit/Build:** 6d99426

Price sync. is not able to check

**Steps to reproduce:**
1. Build any shop/stall
2. Try to check the price sync. checkbox

**Comment by jensj12** [comment]
More reports are flowing in on the forum: 
https://openrct2.org/forums/topic/3636-same-price-throughout-park-selection
