### ISSUE TITLE
Refactor Ride.inversions

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#8965]
Ride.inversions has three different types of data that is stuffed into it. ~~We will ignore `holes` for now as golf rides are super special.~~
```
    union
    {
        uint8_t inversions; // (???X XXXX)
        uint8_t holes;      // (???X XXXX)
        // This is a very rough approximation of how much of the ride is undercover.
        // It reaches the maximum value of 7 at about 50% undercover and doesn't increase beyond that.
        uint8_t sheltered_eighths; // (XXX?-????)
    };
```
~~There should be an getter and setter for inversions and sheltered_eighths (and probably holes).~~

These should be split into 3 different fields that are set correctly from s4/s6 importer/exporter.

**Comment by IntelOrca** [comment]
The fields can be separated completely now, the ride struct can be changed as much as we like.

**Comment by duncanspumpkin** [comment]
Good point. That would be even better.
