### ISSUE TITLE
Servers running network version 0.2.2-9 do not show up on master server list.

### ISSUE THREAD

**Issue by mozar99** [OpenRCT2/OpenRCT2#8972]
**OS:** [Server2012]
**Version:** [0.2.2-9]
**Commit/Build:** [d41822e]

Servers running network version 0.2.2-9 do not show up on master server list.
users can only connect if they know the servers IP address and port number, or if they previously marked the server as favorite .

- [ ] Reproducible in RCT2 (vanilla)?
- [X] Specific to multiplayer?

**Steps to reproduce:**
1.  Host a server running the latest build.
2.  Check server list. It wont be there

**Comment by IntelOrca** [comment]
Possibly caused by this commit:
https://github.com/OpenRCT2/OpenRCT2/commit/d41822e0f50596ddc2071e35a93a29418b8c8540

@ZehMatt are you able to investigate?

**Comment by ZehMatt** [comment]
I'm unable to advertise, all I get is 
```
Unable to advertise (500): Timed out while waiting for server response.
```
I'm not exactly sure how the mentioned commit would cause this.

**Comment by ZehMatt** [comment]
The only thing I can think off is that on the master server the packet number is actually hardcoded, I'll give it some tries.
