### ISSUE TITLE
Opening the “New Ride” window noticably slows down game

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#8988]
**OS:** Ubuntu 18.04
**Version:** 0.2.2+
**Commit/Build:** 731af7473202b931ce243321bc7c42f9800dafc9

Using a debug build, I get 37 FPS at 1920x1200 in a certain park. When opening the New Ride window on the roller coasters page, this drop down to 15 FPS. This is using software rendering mode with no hardware display.

**Comment by ZehMatt** [comment]
Not sure what GCC/Clang does on debug builds but on MSVC its the debug iterators being slow as hell, primarily caused by font_sprite_get_codepoint_offset

**Comment by ZehMatt** [comment]
Using std::unordered_map over std::map gave me a huge improvement, should probably use that if sorting doesn't matter.

**Comment by ZehMatt** [comment]
Actually now that I think about it, there are not many elements, this should be a sorted vector with std::pair values where we could binary search which should be even much faster than map/unordered_map

**Comment by IntelOrca** [comment]
I thought `std::map` was doing a binary search.

**Comment by janisozaur** [comment]
That seems to be the case. And perhaps also the reason why it might be slow, as N might just not be large enough.
