### ISSUE TITLE
Error messages when there's not enough money is shown as undefined string

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#9000]
**OS:** Windows 10
**Version:** 0.2.2
**Commit/Build:** 0b41c0f

When I try to build a RIDE with not enough money, the error message, says not enough money, is shown as (undefined string).
it is correctly shown when I landscape, watering, build paths or put scenaries. Just for building a ride.
Maybe it is related to #8957, and sorry if it is duplicated.

**Steps to reproduce:**
1. Make money not to enough to build any rides.
2. Try to build a ride (not a scenary or landscaping)

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/10726524/55284220-e4d2a080-53ac-11e9-953b-18bd478591ac.png)

**Comment by duncanspumpkin** [comment]
This is to do with the game actions.

**Comment by ZehMatt** [comment]
It hits this line:
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/actions/TrackPlaceAction.hpp#L204
