### ISSUE TITLE
Refactor gCurrentFontSpriteBase and gCurrentFontFlags

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#9013]
Both are currently global and would be best if the drawing functions would take a parameter for this, ex.: gfx_draw_string, gfx_draw_string_left, gfx_draw_string_centred, gfx_draw_string_right, draw_string_left_underline etc.

Ideally one would pass to the functions some struct which can be something like
```c++
struct TextFont // TBD
{
    TextFont(uint16_t base, uint16_t flags = 0) : spriteBase(base), fontFlags(flags) {}
    uint16_t spriteBase;
    uint16_t fontFlags;
};
```
Instead of assigning the global variables before drawing text.

**Comment by duncanspumpkin** [comment]
Most callers expect it to be of a certain type. It should have a default value of standard text

**Comment by Gymnasiast** [comment]
This has been done in the meantime.
