### ISSUE TITLE
Verify that nullptr check exists for calls like map_get_first_element_at

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#9014]
A lot of issues currently come from missing nullptr checks after calls to functions like map_get_first_element_at, map_get_nth_element_at, map_get_surface_element_at, map_get_path_element_at, map_get_banner_element_at. 
Each reference should be checked if it will handle the result correctly, currently the fixes are case by case, which can be avoided by doing all of them for once.

**Comment by joshtucker132** [comment]
My team can work on this issue.

**Comment by lwatson2016** [comment]
What should be the error/action if the result is NULL?
I.e. if null, then ....?

**Comment by duncanspumpkin** [comment]
That will depend on the function. Game actions should always return a game action result. Some functions it will be safe to just error and return some functions it will be best to do a hard crash.

**Comment by janisozaur** [comment]
If nullptr is returned, it means no such element we found for the given tile and effectively there is nothing to process. In other words it means:
1. Don't crash
2. Exit the function gracefully, possibly propagating error if that makes sense.

**Comment by tupaschoal** [comment]
I'm willing to work on this :)

**Comment by tupaschoal** [comment]
All `map_get_banner_element_at` are currently already checked for invalid returns

**Comment by tupaschoal** [comment]
I've added another PR, #10091 with other places I found. Lesson of the day is not to trust VS's "Find all References" or "Call Hierarchy" :|

**Comment by tupaschoal** [comment]
I guess this can be closed now :)
