### ISSUE TITLE
Undefined String in options menu

### ISSUE THREAD

**Issue by hokasha2016** [OpenRCT2/OpenRCT2#9019]
**OS:** Windows 10
**Version:** 0.2.2
**Commit/Build:** dc90b28

I was building the game to make sure that a fix i was working on was working fine, However when opening the options menu i found an ``` undefined string``` next to the video options such as VSync and Show FPS. I was assuming it is a simple fix such as identifying the String in the necessary language packet, in my case English, however after opening all the language packets they all have the same issue. I believe that the String was used and called upon but never initialized.

![issue](https://user-images.githubusercontent.com/46494088/55450939-e1067000-559e-11e9-8fc2-2b0ddad1bed4.PNG)

I feel that it would be a quick fix, its just a matter of tracing. Will try to fix myself, but i am curious if this was always an issue or not because this is the first time seeing it.

**Comment by hokasha2016** [comment]
So i checked an older version of this game, march 26th i believe, and apparently whatever that feature was it was never added. So I'm guessing this is a new feature of some kind?
![issue](https://user-images.githubusercontent.com/46494088/55452857-6d1c9580-55a7-11e9-9cda-083a37e7cdbb.PNG)

**Comment by ZehMatt** [comment]
This is indeed a new feature but the string should be included in en-GB.txt, make sure you have the correct language file after building.
The missing string is
```
STR_6305    :Multithreading
```
![openrct2_2019-04-03_07-14-513945a2483c70a405d](https://user-images.githubusercontent.com/5415177/55454517-7a09ab00-55e0-11e9-8e1b-7dab799c16a7.jpg)

**Comment by duncanspumpkin** [comment]
It's because you use en us instead of gb. The new string will be translated soon. This issue should be against the language repo

**Comment by ZehMatt** [comment]
I always thought it will always fall back to en-GB if the string is missing

**Comment by duncanspumpkin** [comment]
Well then the other reason will be because they aren't doing a complete build and copying the language file

**Comment by hokasha2016** [comment]
So after looking around, i found that in en-GB.txt in ```data\language``` does contain the string as mentioned above, however it wasnt located in the ```bin\data\language```.
