### ISSUE TITLE
Feature: Open doors and portcullis doors with tile inspector

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#9029]
**OS:** Windows 10
**Version:** 0.2.2
**Commit/Build:** dc90b28

To open doors, we now have to build a door, let a ride drive through it and remove the ride when the door is open. Then the open door can be copied with tile inspector and placed wherever we want.

It would save a lot of work if we could just click a doorway or portcullis door with tile inspector, and set the open state from there.

![image](https://user-images.githubusercontent.com/6469413/55474416-5e6ac880-5611-11e9-90b9-bf5a1c012a42.png)

**Comment by duncanspumpkin** [comment]
This is tied to another issue. Let me just find it.

**Comment by duncanspumpkin** [comment]
#8791 was what i was thinking about but it doesn't actually refer to the right change so this can stay open. For wall elements that can animate you should be able to set the animation frame from the tile inspector and see what frame it is on the interface.

**Comment by ocalhoun6** [comment]
>we now have to build a door, let a ride drive through it and remove the ride when the door is open. Then the open door can be copied with tile inspector and placed wherever we want.

There actually is a (slightly) easier method already. At least you don't have to delete any rides.

1: Build a door on top of an existing ride track; stand by with the pause button

2: As the train goes through it, pause the game.

3: Use the tile inspector to copy/paste the door in this state

4: Use the tile inspector to delete the original door (if you want)

5: Un-pause the game. The door should remain open, and now you can freely make more copies of it.

Only a little bit easier, but it's not necessary to build and then demolish a ride just to get open doors. (Assuming you have at least one tracked ride already in your park.)

**Comment by deurklink** [comment]
I don't mind the normal method @ocalhoun6 , it would just be a lot faster and nicer if we could set it to a certain animation frame using the tile inspector. But thanks for sharing your method!

**Comment by joshtucker132** [comment]
Since my team is working on #8791, we can also try and tackle this one.

**Comment by oli414** [comment]
@joshtucker132 still planning to look into it? Otherwise, I'll have a look

**Comment by AaronVanGeffen** [comment]
@oli414 Josh posted his message nearly a year ago. Please, feel free.

**Comment by oli414** [comment]
People will be very happy to have all these different options for doors:

![image](https://user-images.githubusercontent.com/2348094/78148568-45b80d00-7435-11ea-9412-12ea8b2a3020.png)

@duncanspumpkin is this what you had imagined?

**Comment by duncanspumpkin** [comment]
Yes that looks perfect.

**Comment by ocalhoun6** [comment]
Hm... Could this 'animation frame' setting apply to other animated scenery as well?
It could be useful on art parks to freeze certain normally-moving scenery items in place, or to be able to select just the perfect part of the animation for them to be stopped in. Either just because the animation is annoying, because you want it to look like a static statue, or because you want to freeze it at just the moment when that Elvis points his finger or the moment when that light flashes so the light always stays on...

**Comment by oli414** [comment]
@ocalhoun6 to my knowledge other animated scenery is automatically animated and can thus not be frozen. So the animation frame setting on those wouldn't make much sense.

The freezing of animated scenery would probably need to be a new feature request.

**Comment by duncanspumpkin** [comment]
It would be quite annoying to freeze an animation. Map animations are recreated on park load you would have to override a bunch of things and that would mean additional flags and we don't have an easy way to add more flags without changing the save format.

**Comment by cherct** [comment]
Right now, it is only possible to fully open a door in one direction with the tile inspector (right door), there are some frames missing for the other direction as it can only open one frame (left door).

![grafik](https://user-images.githubusercontent.com/62889822/80280177-c7cce600-8702-11ea-9268-92a7b9a681af.png)

I got this after I built a car ride through it:

![grafik](https://user-images.githubusercontent.com/62889822/80280333-b6380e00-8703-11ea-9173-bd6da97cbdea.png)

Both doors are at animation frame 5 now, so maybe there should be a toggle for opening direction.

b417da7
