### ISSUE TITLE
Scenery Preview Costs Money

### ISSUE THREAD

**Issue by Krutonium** [OpenRCT2/OpenRCT2#9042]
**OS:** Windows 10
**Version:** 0.2.2
**Commit/Build:** dc90b28

Looking at the preview for a ride that has scenery charges your bank account for the cost of the scenery contained in the preview

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Go to build a ride (Any with scenery)
2. Move back and forth over a ride with scenery and watch your money disappear.

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/3945538/55520718-8119d300-564b-11e9-9774-db3ec811d946.png)

**Save game:**
[Crazy Castle.txt](https://github.com/OpenRCT2/OpenRCT2/files/3041188/Crazy.Castle.txt)

**Comment by duncanspumpkin** [comment]
All commands for scenery placement previews should pass flag 5 which means no money spent. I'm half way through a refactor of track design and will fix this issue in that.
