### ISSUE TITLE
Remove gSceneryTileElement by returning it within GameActionResult

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#9054]
Another similar one to #9053 but this time for Wall, Large and Small Scenery Place Actions. Will require returning a subclass of GameActionResult with the correct additional field.

This will help reduce number of global vars that litter the codebase.

Note this cannot be completed until LargeSceneryPlaceAction is finished #9055.

**Comment by boucks** [comment]
If no one else is working on this, I would love to tackle this as my first issue!

**Comment by duncanspumpkin** [comment]
There is some over lap with #9053 so but there is no harm both of you creating a solution and then merging them.

**Comment by Nazey** [comment]
@boucks are you still working on this?

**Comment by boucks** [comment]
@Nazey yeah, I'm going to get to it this weekend!

**Comment by boucks** [comment]
I believe that I have the basic idea of the subclass and constructors from referencing #8726 but I am having trouble with removing gSceneryTileElement using my subclass. I'm struggling to find the definition of gSceneryTileElement. Could anyone offer assistance?

**Comment by Nazey** [comment]
@boucks should be in Scenery.cpp. Are you working in xcode/visual studio by any chance?

**Comment by boucks** [comment]
Thank you, and I am working in visual studio.

**Comment by Nazey** [comment]
Yeah no problem. You can look through all of the files for a variable like that really quickly by just using the "search solution explorer" textbox in visual studio.

**Comment by boucks** [comment]
I'm trying to use the tool but every time I type in the variable it says "No results found." I was able to find where it was initialized in Scenery.cpp but I want to also find the definition so I know how to use my subclass to remove it. Any suggestions?

**Comment by duncanspumpkin** [comment]
Your file cache might have got old with us adding lots of files. Vs sometimes messes up due to the way we add files. The way to fix it is to delete everything in the .vs folder in OpenRCT2 apart from cmakesettings.json then let it rebuild. Note it will reset to x86 so you will have to rechoose x64.

**Comment by boucks** [comment]
Okay, I think I might have gotten it, here is an example of one of the subclasses I made: 
![CodeSnipet](https://user-images.githubusercontent.com/23228727/56483243-abb2bb00-6496-11e9-9cf4-5c4cfad79e6a.PNG)

I then removed the gSceneryTileElements from TopToolbar.cpp doing this:
![CodeSnip2](https://user-images.githubusercontent.com/23228727/56483297-f2a0b080-6496-11e9-842b-d8d8ea7f7b02.PNG)

Do I also need to change the SetCallback from GameActionResult to my subclass as mentioned in #8726?

I removed the initialization of gSceneryTileElement from Scenery.cpp but I now am trying to compile it and am not sure if it is working. What I am trying is running the openrct2.sln in VS after I ran msbuild in the developer command prompt. When I try to open and run openrct2.sln it tells me I have 984 errors but none that I looked at seem to be related to my changes. I also tried to set the startup item to be openrct2.sln but that gives me an error "The startup project could not be launched. Verify debug settings for the startup project." Not sure if my VS is messed up or if I am doing something wrong. Could this also be related to the cache? I will try and remove that now.

I would love if you could let me know if there is any way I can test my changes to make sure I am doing it correctly.

**Comment by boucks** [comment]
Okay, I think I fixed some issues. I now compile successfully except when I delete gSceneryTileElement from Scenery.cpp. I tried deleting all the files except cmakesettings.json from the .vs folder but am still not able to use the solution explorer. I might be missing a reference to gSceneryTileElement? Are there any references outside of TopToolbar.cpp? Sorry for asking so many questions.

**Comment by duncanspumpkin** [comment]
@boucks can i be annoying and ask if you could hold off for a day. https://github.com/OpenRCT2/OpenRCT2/pull/9109 is ready to be merged and it will make everything much simpler for this (no need to create a new class for Large and Small scenery you just need to add a new field. You would still need to create a new class for Wall place though).

gSceneryTileElement is used in:
1. actions/SmallSceneryPlaceAction.hpp
2. actions/LargeSceneryPlaceAction.hpp
3. actions/WallPlaceAction.hpp
4. <ui>/windows/TopToolbar.cpp

It is defined in World/Scenery.cpp and declared in World/Scenery.h.

**Comment by duncanspumpkin** [comment]
#9109 is now merged. Could you rework ontop of the current develop.

**Comment by boucks** [comment]
Alright I have added my changes to the current develope branch and everything seems to be building correctly now, should I make a PR?
