### ISSUE TITLE
Land/water tools show prices when money is disabled

### ISSUE THREAD

**Issue by Umdlye** [OpenRCT2/OpenRCT2#9067]
**OS:** Win10 x64
**Version:** 0.2.2
**Commit/Build:** 7376e16

![openrct2_2019-04-07_11-10-43](https://user-images.githubusercontent.com/11657101/55681371-1b1c9c80-5926-11e9-91e4-9f5272026f45.png)

**Comment by elInfidel** [comment]
Can I take this one? Any advice on where to start looking if so?

**Comment by duncanspumpkin** [comment]
I changed how the cost checking works. Previously the game command returned 0 on no cost games. It now returns an amount and it is up to the caller to display it correctly. You will need to modify the ui for each of the windows to not draw when money is off.

**Comment by elInfidel** [comment]
Thanks, I've reproduced and solved for the land window. Time permitting I'll fix the other windows & get a PR up.

**Comment by Gymnasiast** [comment]
82c73e1 fixed this issue partially: the amounts still show up in the editor.

**Comment by elInfidel** [comment]
> [82c73e1](https://github.com/OpenRCT2/OpenRCT2/commit/82c73e18c7ffba179db20e557f034e7c1ad262ed) fixed this issue partially: the amounts still show up in the editor.

I can't reproduce this in the latest develop, can you give me steps to reproduce. It appears that PARK_FLAGS_NO_MONEY is set when in the scenario editor so I don't see the costs rendering anyway. Would you prefer to see SCREEN_FLAGS_EDITOR alongside that no money check to make things more understandable?

**Comment by Gymnasiast** [comment]
I could reproduce this yesterday, but I will double check.

**Comment by Gymnasiast** [comment]
I can't reproduce it any more either.

**Comment by elInfidel** [comment]
Awesome! Sorry I forgot to make a pr for the change log, thanks for making one :-)
