### ISSUE TITLE
Feature: Tile Inspector Shortcut Keys

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#9073]
**OS:** Windows 8
**Version:** e.g. 0.2.2
**Commit/Build:** 426e106

Using the tile inspector can be pretty tedious sometimes, especially when you end up doing the same thing over and over again on a thousand different tiles in a big project.

Some of it could be made quicker and easier if the tile inspector had shortcut keys.

It would be useful to have shortcut keys for:
- copy
- paste
- insert corrupt element
- delete

And if you wanted to get really fancy, maybe also for:
- increase/decrease x/y location
- rotate object

Most of these could probably remain unassigned until the player feels the need to set them, although Ctrl +C and Ctrl +V for copy and paste would be pretty obvious choices, and I think they're not yet assigned to anything else.

This could *massively* speed up certain tedious tasks with the tile inspector when working with a large number of similar tiles that all need to be modified.

**Comment by Patrik356b** [comment]
Ctrl + h could be used to hide something using corrupt element (it hides the opera browser and is commonly used to replace things)

Ctrl + ijkl could be used for movement (some games change camera angle using this) 
Ctrl + uo could be used for rotation

**Comment by AaronVanGeffen** [comment]
I can see why it would be nice to have the option to set shortcuts for these actions. We probably shouldn't set any defaults for them, though.

**Comment by Gymnasiast** [comment]
We already have `Z` to rotate the currently selected object in the scenery window. That could easily double up as the rotate key in the Tile Inspector.

**Comment by Patrik356b** [comment]
@AaronVanGeffen perhaps a checkbox in the tile inspector ítself could do the trick to enable/disable them?

**Comment by AaronVanGeffen** [comment]
@Patrik356b I meant that users should assign them in the shortcut settings. There are only so many keys on keyboards, so if we add a bunch of new defaults they're bound to conflict with people's existing set-ups.

**Comment by bitman2049** [comment]
This was implemented in https://github.com/OpenRCT2/OpenRCT2/pull/10430, so this ticket can be closed.
