### ISSUE TITLE
Sign texts overwrite newest sign in multiplayer

### ISSUE THREAD

**Issue by deurklink** [OpenRCT2/OpenRCT2#9083]
**OS:** Windows 10
**Version:** 0.2.2
**Commit/Build:** e01b5f9

When someone renames a sign in multiplayer, the newest sign in the map will get the text, and the older one will just be renamed "sign".

This is very annoying because we use signs to show who is building where in multiplayer.

Possibly related, when someone renamed a shop one of the rides automatically got the same name as the shop.

**Comment by duncanspumpkin** [comment]
This is caused by ghosts. I need to make a bit of a change for how signs get allocated numbers.
