### ISSUE TITLE
Feature: save/load-persistent cheat enable via 'cheat code' staff names.

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#9084]
**OS:** [e.g. Windows 8
**Version:** e.g. 0.2.2
**Commit/Build:** 426e106

If you have cheats enabled, exit the game, then restart and load the same map again, all the cheats will be turned off again.

This is usually fine, but sometimes people want the cheats to persist in the save file.

Obviously, we can't do that without a new save format. Unless...

If each cheat had a 'cheat code' you could type in as a staff name in order to enable it, those names would be recorded in the save file. A function that runs when loading the save (and when renaming staff) could look through the list of staff names for the various 'cheat code' names, then enable the corresponding cheats. Another function would have to run when a staff is renamed or fired -- checking that staff name to see if it matches any cheat codes and then turning off the corresponding cheat.

That way, you can make persistent cheat codes for your save file, as well as having a nostalgic, easter-eggy way to enable cheats.

Something like, "Name a staff member 'Clickety Clack' to allow chain lift on all track pieces," or, "Name a staff member 'Neat Freak' to disable litter." I'd use staff names, rather than peep names, so you don't have problems when the specially-named peep leaves the park.

**Comment by duncanspumpkin** [comment]
No that is overly complex and would be a pain to keep after we create a new save format.

**Comment by Ryder17z** [comment]
Maybe a plugin would be the best way to do it

**Comment by duncanspumpkin** [comment]
When we have the new save format we will save the cheats with the file correctly. No need for a plugin.
