### ISSUE TITLE
Switch to more modern JSON library

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/OpenRCT2#9088]
I'd like us to switch to a more modern JSON backend to replace the C library we're currently using.

[JSON for Modern C++](https://github.com/nlohmann/json#examples) looks very promising. It's been packaged for Homebrew, vcpkg/nuget, Arch Linux (AUR), and even [Debian](https://packages.debian.org/stretch/nlohmann-json-dev) ships it.

**Comment by tupaschoal** [comment]
I can vouch for https://github.com/nlohmann/json, I've seen pretty heavy usage of it with no problems

**Comment by AaronVanGeffen** [comment]
Perhaps the best way to go about this, is to introduce the new library to the codebase and then rewrite the existing code in smaller refactor projects. It's more than a little daunting otherwise.
