### ISSUE TITLE
Small scrolling sign can't be recolored

### ISSUE THREAD

**Issue by Umdlye** [OpenRCT2/OpenRCT2#9097]
**OS:** Win10 x64
**Version:** 0.2.2-240
**Commit/Build:** 8632eb7

Small scrolling signs (the wall type ones) can't be recolored.

![2019-04-14_17-57-00](https://user-images.githubusercontent.com/11657101/56095635-1c7a3600-5edf-11e9-81b1-8b2eb778a314.gif)

**Comment by duncanspumpkin** [comment]
Its the same reason why all signs are broken right now. #9083

**Comment by Umdlye** [comment]
Yeah, had a hunch but figured I'd submit it just in case. Thanks :)

**Comment by duncanspumpkin** [comment]
I didn't actually check but I'm 90% confident it is the same reason.
