### ISSUE TITLE
Extra viewport does not preserve center on map rotate.

### ISSUE THREAD

**Issue by RM87** [OpenRCT2/OpenRCT2#910]
Extra viewport does not preserve its center on map rotate.
Probably original bug.

**Comment by Gymnasiast** [comment]
I don't think it's an original bug, particularly because the extra viewport functionality was introduced by OpenRCT2 ;).

**Comment by adrian17** [comment]
It's already known: https://github.com/IntelOrca/OpenRCT2/pull/520#issuecomment-59037043

But it's good to see a separate issue on this

**Comment by tupaschoal** [comment]
Still happens on v0.3.1
