### ISSUE TITLE
Mazes don't cost more or less based on height.

### ISSUE THREAD

**Issue by Krutonium** [OpenRCT2/OpenRCT2#9104]
**OS:** Windows 10
**Version:** 0.2.2-246
**Commit/Build:** cdf5870

Mazes do not changed in price depending on elevation, unlike every other anything in the game.

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Build a maze on the ground
2. Now build one in the air or on water.

**Comment by duncanspumpkin** [comment]
Is this in vanilla?

**Comment by Krutonium** [comment]
Actually, apparently Yes.
