### ISSUE TITLE
Use a vector for station locations list in sub_6CB945

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#9110]
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/ride/Ride.cpp#L7253-L7376

`TileCoordsXYZD locations[(MAX_STATIONS * 2) + 1];` should be replaced by a `std::vector<TileCoordsXYZD> locations;`

https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/ride/Ride.cpp#L7274
Can then be modified to use a ranged for loop.

**Comment by IntelOrca** [comment]
You can use `for (x : y)` on a array too. `std::array` might be better in this case, it really depends on how often the function is called. We should try to avoid mallocs where possible in game / draw tick unless it is infrequent or re-used per tick.

**Comment by duncanspumpkin** [comment]
I want to avoid the requirement for the end marker. Yes it should probably be checked how often this is called.

**Comment by duncanspumpkin** [comment]
I've confirmed it is not used every tick. It is therefore okay to use a vector for this.

**Comment by ZehMatt** [comment]
Too bad STL does not provide a fixed size vector container.

**Comment by janisozaur** [comment]
Isn't that just `std::array`?

**Comment by ZehMatt** [comment]
std::array has no push/erase. It acts more like a C array with iterators.

**Comment by janisozaur** [comment]
Why would you want to have `push()`? It's a fixed size array. I don't quite understand the use case you want.

**Comment by ZehMatt** [comment]
std::vector is dynamic in space where I want one with finite room but still have the model of being able to insert and remove elements just by taking a slot in our finite memory storage, so capacity would stay at fixed N where size is dynamic in the range from 0 to N thus avoiding allocations that std::array offers. Its not exactly a new concept.

**Comment by IntelOrca** [comment]
You basically want `std::tuple<std::array<T, N>, size_t>` with all the push, pop method etc. We could make our own although perhaps unnecessary for this.

**Comment by ZehMatt** [comment]
Yeah not for this maybe, but if we wan't to replace more arrays where elements are added/erased dynamically more often this might be a good idea to implement at some point.

**Comment by lwatson2016** [comment]
I can work on this! To confirm, you want to use `std::vector` for this?

**Comment by duncanspumpkin** [comment]
For this i think a vector will be fine. It's not ideal but it will work.
