### ISSUE TITLE
Refactor gVehicleSoundParamsList into a non global variable

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#9113]
gVehicleSoundParamsList is only used within the vehicle param update function. It has no reason to be a global variable and is cleared every tick. It should be replaced by a local variable that is passed into the required function. At the same time it could be replaced with a std::array.

**Comment by stevexu-umich** [comment]
Hello! There doesn't seem to be anyone working on this right now, so is it alright if my team takes a look at it? It looks like a good introduction to the project.

**Comment by duncanspumpkin** [comment]
Sure feel free to go ahead and implement it

**Comment by 41northstudios** [comment]
@stevexu-umich are you and your team still working on this? I could try and take a crack at it if it won't conflict with your work.

**Comment by UltimaBGD** [comment]
Has there been any update on this issue? If there hasn't been, I wouldn't mind taking a look.

**Comment by duncanspumpkin** [comment]
Don't think anyone has looked at implementing it. Feel free to give it a shot.
