### ISSUE TITLE
Install commitlint bot

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#9116]
The commit messages should adhere to a common standard, it makes them easy to browse especially when using `--oneline` log option.

See
* Our commit message style:https://github.com/OpenRCT2/OpenRCT2/wiki/Commit-Messages
* https://www.git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines
* https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
* https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53
* https://chris.beams.io/posts/git-commit/
… and many more

To keep the messages tidy, we should use a tool such as https://github.com/apps/commitlint/

**Comment by AaronVanGeffen** [comment]
We briefly tried this with the OpenLoco repository, but deemed it too inflexible for the moment. The lack of any configurability was a huge dealbreaker for us there.

**Comment by janisozaur** [comment]
For reference: the test was done mainly in https://github.com/OpenLoco/OpenLoco/pull/324 and the style the bot ships with prevents using `Fix #XYZ: Some details here` subject line, which turned off even me.

**Comment by Gymnasiast** [comment]
Implemented by https://github.com/OpenRCT2/OpenRCT2/pull/11410.
