### ISSUE TITLE
Executing game action of disconnected user crashes server

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#9124]
**OS:** Ubuntu Server 18.04
**Version:** 0.2.2
**Commit/Build:** 

Just now one of my multiplayer servers crashed, and when looking in the logs to find the cause I found this:

```
[2019/04/21 21:47:48] Mitsubishi has disconnected (Connection Closed)
[2019/04/21 21:47:48] [sv] GA: TrackRemoveAction (00000004) (_networkId = 00000202; _flags = 80000000; _playerId = 2; _trackType = 00000000; _sequence = 00000000; _origin = CoordsXYZD(x = 2016, y = 3392, z = 144, direction = 3); ) OK
```

The action `TrackRemoveAction` has _playerId 2, looking up higher in the list this seems to be the same user as the one who just disconnected (this same user constantly keeps disconnecting because of bad internet).

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**
1. Connect to a server with terrible internet
2. Perform a bunch of actions and hope to disconnect just before one gets executed

**Dump file**
Not sure if these are automatically generated on Ubuntu Server. It does say "Core dumped", but I have no idea where.

**Comment by duncanspumpkin** [comment]
@ZehMatt could you have a look at this. I was under the impression that disconnected players had their GA's removed.

**Comment by ZehMatt** [comment]
Ideally the player will be removed at the end of the tick not during network update so the commands will be at least processed before he leaves as the client already handles the player list that way as well, this can't be out of order like that. I'll see to fix it

**Comment by Broxzier** [comment]
@ZehMatt I'm not sure if this was the case here or if it is related, but I noticed that sometimes players are listed multiple times.
