### ISSUE TITLE
Cannot open sv4 files from system file browser

### ISSUE THREAD

**Issue by Liampie** [OpenRCT2/OpenRCT2#9132]
OpenRCT can open (most) .sv4 files through its own file browser, but when you switch to the system file browser, either through the button in the ORCT file browser window or the setting that makes the system file browser the default, this isn't the case anymore. When you try to open an .sv4 file through the file browser, literally nothing happens.

Using version 0.2.2 462bafc on windows 8.

**Comment by Gymnasiast** [comment]
Seems to have been caused by https://github.com/OpenRCT2/OpenRCT2/commit/45a92a73564df4dc54a4eb725512f432f459d7e8 (@broxzier)
