### ISSUE TITLE
Can't load libcrypto.so.1.1

### ISSUE THREAD

**Issue by JakobDev** [OpenRCT2/OpenRCT2#9156]
**OS:** Ubuntu Mate 16.04
**Version:** 0.2.2
**Commit/Build:** 298c9f5

If I try to run OpenRCT2, it will give the following error:
```
./openrct2: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```
All libcrypto packages are installed.

**Comment by AaronVanGeffen** [comment]
Our Ubuntu builds are built for Ubuntu 18.04. Unfortunately, Ubuntu 16.04 does not ship with the right version of the library in question.

**Comment by Wilma456** [comment]
How can I install it manually?

**Comment by AaronVanGeffen** [comment]
Normally, I would advice to compile manually (see our wiki), but you'd have to backport a lot of Ubuntu packages. Additionally, libcrypto would likely not be the only problem; it's been linked to more recent versions of libpng, libicu and what not.

OpenRCT2 has been programmed in C++17. As it needs a toolchain that supports C++17, currently at least Ubuntu 18.04 is required to build reasonably out-of-the-box.

**Comment by Wilma456** [comment]
Is there any AppImage or Snap which contains all needed libs?

**Comment by IntelOrca** [comment]
AppImage and Snap don't typically include libstdc++ which you will need the later version of.
