### ISSUE TITLE
The option "Allow testing of unfinished track" is not synced over multiplayer

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#9194]
**Version:** 0.2.2
**Commit/Build:** f1b9c71524ca4f80b37637902e99b1d846bd2411

Exactly what the title says. A server could spawn vehicles if it has this option enabled, while the client hasn't.
This option should either be synced with the server, or send along with the spawn command.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**
1. Host one instance, connect with another
2. Enable "Allow testing of unfinished tracks" option on the server, and disable it on the client
3. Spawn a train on the server

You'll be greeted with the desync message pretty shortly afterwards.

**Comment by ZehMatt** [comment]
How come this is a normal option rather than a cheat? Not exactly sure where/how to synchronize this one specific setting as it can change during gameplay.

**Comment by ocalhoun6** [comment]
> How come this is a normal option rather than a cheat?

It stays active after restarting the game or loading a new map. All of the cheats are off by default and have to be turned on every time you start the game.

**Comment by AaronVanGeffen** [comment]
@ZehMatt When the option was introduced in 37221f0aae (2015-05-22) multiplayer hadn't been introduced yet. Syncing it has probably never been taken into consideration before…

@ocalhoun6 Trouble is, we do sync cheat status, but not any of the global options.

**Comment by ZehMatt** [comment]
Also the requirement would be to introduce a new game action for a single option which I believe should be rather a cheat given that they are no ghost trains (yet) and the original game never allowed to do this without memory hacking. So I guess this should go for a discussion @all

**Comment by Gymnasiast** [comment]
Since it's more or less a hack, and because it will go away when a proper ghost train can be introduced, I would just disable it in multiplayer.

**Comment by AaronVanGeffen** [comment]
Disabling the feature altogether in multiplayer is not a solution, imo. We have been working towards enabling more features in multiplayer as of late; it shouldn't be the other way around.

**Comment by IntelOrca** [comment]
I am working on ghost train simulation which will resolve this.

**Comment by ZehMatt** [comment]
Gonna close this because of #9222
