### ISSUE TITLE
Request: Cheat for Zero Clearance Whole Map

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#920]
Reddit user IntrovertedIntrover has suggested adding an additional cheat that forces zero clearance on the whole map. ~~Since there isn't much point implementing a toggle function like 8cars at present it would be a whole map no way to reverse function.~~

http://www.reddit.com/r/openrct2/comments/2z965l/so_how_exactly_does_zero_clearance_work/

~~This should be relatively easy to implement so I'm leaving it for someone else to do. Have a look at how the current zero clearance cheat works and modify it to iterate over every map tile. Have a look at map.c if you need help on how to iterate over every tile. Should add a warning on the cheat window to say this function can not be reversed.~~

Since it isn't long until all of the scenery placement commands are complete do not try to implement this at the moment. When all scenery placement is finished this can be done correctly without destroying maps.

**Comment by IntelOrca** [comment]
Implemented nicely in the new-better-disable-clearance branch.
