### ISSUE TITLE
Game not displaying properly on launch

### ISSUE THREAD

**Issue by Isakabibble** [OpenRCT2/OpenRCT2#9203]
**OS:** [MacOsX]
**Version:** [0.2.2]

I installed the game on a windows pc to avoid having to use wine to install it.  When I launch the game it shows me a corner of the screen but all of the hitboxes for the menus are in their proper places in the application window. I cannot change the scaling because of my inability to see where I am clicking in the window

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/50251328/57166671-85f3b300-6dc0-11e9-8126-08fa4a9d9499.png)

**Comment by AaronVanGeffen** [comment]
This problem was been fixed sometime after 0.2.2 release in #8929. Please try a `develop` build instead.
