### ISSUE TITLE
Add Peep sprite index to the Guest Debug Tab 

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#9231]
https://github.com/OpenRCT2/OpenRCT2/pull/8558 introduced the Guest debug tab. It would be useful to display the `sprite_index` within the debug tab. The information should be of the form `Sprite Id: {...}`. Where `{...}` is replaced with the relevant `sprite_index`.

You will need to make changes to the Guest window file: https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2-ui/windows/Guest.cpp

`void window_guest_debug_paint(rct_window* w, rct_drawpixelinfo* dpi)` draws all of the information for the guest debug tab. You will need to modify this function to display the sprite index at the top of the window before `STR_PEEP_DEBUG_POSITION`. Study #8558 for values are formatted into a string.

A new string will be required within https://github.com/OpenRCT2/OpenRCT2/blob/develop/data/language/en-GB.txt and a new enum entry within https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/localisation/StringIds.h

Suggested string `STR_6318    :{WINDOW_COLOUR_2}Sprite Id: {BLACK}{INT32}`

Additional note. The tab will be too small after adding this additional information. Modify `window_guest_page_sizes` to correct this.

Commit message should follow the commit message standard https://github.com/OpenRCT2/OpenRCT2/wiki/Commit-Messages

**Comment by janisozaur** [comment]
Implemented in https://github.com/OpenRCT2/OpenRCT2/pull/9256
