### ISSUE TITLE
Assertion when passing a directory as the park on command line

### ISSUE THREAD

**Issue by zachary-D** [OpenRCT2/OpenRCT2#9240]
**OS:** Ubuntu Server 18.04
**Version:** 0.2.2
**Commit/Build:**  298c9f523

I installed everything fresh and when trying to start a headless server, some assertions fail and (as far as I can tell) the game server does not start as I cannot connect to it.

serverhost@open-rct2:~/OpenRCT2$ ./openrct2-cli host ~/serversaves --port 11753
An assertion failed, please report this to the OpenRCT2 developers.
Version: OpenRCT2, v0.2.2 (298c9f523 on HEAD)
Failed to allocate array of 9223372036854775807 * h (1 bytes)
Attempted to read past end of file.
An assertion failed, please report this to the OpenRCT2 developers.
Version: OpenRCT2, v0.2.2 (298c9f523 on HEAD)
Failed to allocate array of 9223372036854775807 * h (1 bytes)
Attempted to read past end of file.
Unable to detect file type.
openrct2 $

- [ ~ ] Specific to multiplayer?

**Steps to reproduce:**
1. run openrct2-cli with the above arguments

**Comment by janisozaur** [comment]
Can you share the file you use?

**Comment by ZehMatt** [comment]
The size looks like its int64_t(-1) and since the argument points to a folder rather than a sv6 I wonder if thats the cause for this.

**Comment by IntelOrca** [comment]
@zachary-D You are passing a directory rather than a single save file to load. It should be something like `./openrct2-cli host ~/serversaves/park.sv6`.

11753 is the default port so you don't need to specify that.
