### ISSUE TITLE
Rename SPRITE_LIST_NULL to SPRITE_LIST_FREE

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#9258]
In reset_sprite_list this is set to MAX_SPRITES
https://github.com/OpenRCT2/OpenRCT2/blob/0ff19f071f44a0474b9f5dd60d9106488a3046aa/src/openrct2/world/Sprite.cpp#L183

And is then decremented in move_sprite_to_list
https://github.com/OpenRCT2/OpenRCT2/blob/0ff19f071f44a0474b9f5dd60d9106488a3046aa/src/openrct2/world/Sprite.cpp#L440

So I think it makes more sense to call it SPRITE_LIST_FREE

**Comment by scaryghosty** [comment]
Tackled... check out my PR: https://github.com/OpenRCT2/OpenRCT2/pull/9260
