### ISSUE TITLE
Limit access to move_sprite_to_list

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#9266]
Currently theres code using create_sprite passing an arbitrary argument for the the sprite list where the argument bl controls which list will link the sprite in it and sometimes we have code that calls move_sprite_to_list after calling create_sprite.
Given that create_sprite has some check for the misc list which seems to limit the amount of sprites to 300, calling move_sprite_to_list after create_sprite would basically bypass this check.

Some examples:
https://github.com/OpenRCT2/OpenRCT2/blob/19783726798c1ca76d2c1a2906e5eb6fd566e7ce/src/openrct2/world/Sprite.cpp#L761
Passes 1 instead of SPRITE_LIST_LITTER

https://github.com/OpenRCT2/OpenRCT2/blob/19783726798c1ca76d2c1a2906e5eb6fd566e7ce/src/openrct2/rct1/S4Importer.cpp#L1351
Passes SPRITE_IDENTIFIER_PEEP instead of SPRITE_LIST_PEEP and then calls move_sprite_to_list

I'm not entirely sure if the parameter to create_sprite is supposed to only accept the sprite list type but this is something that should be looked into.

Sometimes its also calling move_sprite_to_list even tho the parameter is already correct.

**Comment by Gymnasiast** [comment]
I have tried to refactor `create_sprite()`, but I had no idea what kind of argument it takes. It's clear as mud.

Do note that S4Importer is our own code, so its behaviour can differ from code that was implemented from RCT2.

**Comment by ZehMatt** [comment]
I also believe this is a possible cause for some of the corrupted saves where sprites end up in places where they don't belong because of the invalid parameter in some cases, its just a guess but would explain some very strange things I encountered.

**Comment by Gymnasiast** [comment]
Addressed by https://github.com/OpenRCT2/OpenRCT2/commit/63549dee5782fbe3e2fae7b2313e41fde2c8101d.
