### ISSUE TITLE
Can't save to new file

### ISSUE THREAD

**Issue by chall0** [OpenRCT2/OpenRCT2#9267]
**OS:** Linux
**Commit/Build:** 035bb6593b8c189f457365b7af3b9d54d2ff3b0a

To prevent saving to a directory name, this commit adds checks that the given filename refers to a regular file.  But this overlooks one important case where the name shouldn't (yet) be a regular file: saving to a new file.

**Steps to reproduce:**
1. Choose "Save Game As" from the menu
2. Select "New file"
3. Specify a file that doesn't already exist
4. Watch the save fail

**Workaround:**
Create a file of the desired name, and then save over the top of it.

**Comment by IntelOrca** [comment]
Yeah, it should only do the check if `fileMode` is set to `FILE_MODE_OPEN`.
