### ISSUE TITLE
Money Effect Cpp Refactor

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#9270]
The money effect sprite is still in its original form from when we implemented it. It could do with being refactored into something more cpp'y. 
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/world/MoneyEffect.cpp

For inspiration of what it should look like have a look at Balloon.cpp
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/world/Balloon.cpp

The money effect struct `rct_money_effect` should have the following `public` member functions:

1. `static void CreateAt(...)`
2. `static void Create(...)`
3. `void Update()`
4. `rct_string_id GetStringId(...) const` consider refactoring this to return a `std::pair`

Two new `public` member functions should be added to `rct_sprite` struct.

1. `bool isMoneyEffect()`
2. `rct_money_effect* AsMoneyEffect()`

This issue is mainly an exercise in renaming functions and should be easy to follow for anyone with a basic understanding of C++. If you require further help please leave a message here or on gitter.

All C++ functions should follow the coding style guidelines. https://github.com/OpenRCT2/OpenRCT2/wiki/Coding-Style Make sure all local variables are in lower camelCase and all function names are in upper CamelCase.

When commiting in git try to stick to the commit message format. https://github.com/OpenRCT2/OpenRCT2/wiki/Commit-Messages

**Comment by aw20368** [comment]
I've made the desired changes into a commit for this issue for a new branch (locally on my computer). However, when I try to publish that branch in Github Desktop, it tells me "Authentication failed. You may not have permission to access the repository....".  It says I can't create a pull request before publishing the branch.

This is my first issue, so I'm not sure I'm doing this correctly. If I am, may I have permission to publish?

**Comment by IntelOrca** [comment]
@aw20368 you need to fork the repository first and push to that. Then you create a pull request which merges the branch from your fork into this repository (upstream).

See https://guides.github.com/activities/forking/.
