### ISSUE TITLE
Support RCT Classic style scenario grouping

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/OpenRCT2#9284]
Recently, I've been musing about whether or not we should support the scenario grouping as seen in RCT Classic. It shouldn't be much work on our end to introduce and maintain, while potentially making it easier for new players to play the game in the 'unlock scenarios' variant.

According to the [RCT Fandom Wiki](https://rct.fandom.com/wiki/RollerCoaster_Tycoon_Classic), RCT Classic groups the scenarios as below. Like scenarios, new groups become available once previous groups have been finished.

### Graphite Group (Black) 
* Forest Frontiers
* Dynamite Dunes
* Leafy Lake
* Diamond Heights
* White Water Park
* Trinity Islands
* Three Monkeys Park
* Factory Capers
* Katie's Dreamland

### Emerald Group (Green) 
* Bumbly Beach
* Karts & Coasters
* Evergreen Gardens
* Crazy Castle
* Mel's World
* Mystic Mountain
* Pacific Pyramids
* Crumbly Woods
* Paradise Pier

### Ruby Group (Red) 
* Millennium Mines
* Electric Fields
* Haunted Harbour
* Barony Bridge
* Funtopia
* Canary Mines
* Future World
* Gentle Glen
* Jolly Jungle

### Sapphire Group (Blue) 
* Iceberg Islands
* Volcania
* Arid Heights
* Razor Rocks
* Crater Lake
* Vertigo Views
* Paradise Pier 2
* Dragon's Cove
* Good Knight Park

### Amethyst Group (Purple) 
* Fun Fortress
* Amity Airfield
* Bumbly Bazaar
* Whispering Cliffs
* Hydro Hills
* Sprightly Park
* Magic Quarters
* Fruit Farm
* Pokey Park

### Coral Group (Orange) 
* Butterfly Dam
* Coaster Canyon
* Thunderstorm Park
* Harmonic Hills
* Roman Village
* Swamp Cove
* Adrenaline Heights
* Botany Breakers
* Rotting Heights
* Lightning Peaks

### Ivory Group (White) 
* Utopia Park
* Ivory Towers
* Thunder Rock
* Dusty Greens
* Fungus Woods
* Gravity Gardens
* Wacky Warren
* Grand Glacier
* Crazy Craters
* Icarus Park

### Bronze Group 
* Dusty Desert
* Woodworm Park
* Sunny Swamps
* Frightmare Hills
* Thunder Rocks
* Octagon Park
* Pleasure Island
* Icicle Worlds
* Ghost Town (RCT2)
* Infernal Views

### Silver Group 
* Fiasco Forest
* Pickle Park
* Giggle Downs
* Mineral Park
* Coaster Crazy
* Pacifica
* Alpine Adventures
* Extreme Heights
* Lucky Lake
* Rainbow Summit

### Gold Group 
* Rainbow Valley
* Urban Park
* Geoffrey Gardens
* Southern Sands
* Tiny Towers
* Nevermore Park
* Terror Town
* Megaworld Park
* Venus Ponds
* Micro Park

### Bonus
* Tycoon Park

**Comment by ocalhoun6** [comment]
Maybe make that an option?

I guess some people might like it better that way ... but others will prefer it as it is now.

**Comment by Gymnasiast** [comment]
@ocalhoun6 I doubt that Aaron would propose making it mandatory.

**Comment by AaronVanGeffen** [comment]
> Maybe make that an option?

Of course. :) Just like how you can choose between grouping by source game or difficulty now.

> As for the proposal itself: wouldn't the grouping fall flat on its face when the user does not have the RCT1 scenarios?

It would lack quite a few scenarios, yes, but all groups include some RCT2 scenarios as well.

**Comment by Dracheron** [comment]
As much as I hate resurrecting this discussion, I think with the new save format impending we take a look from that perspective as well as consider the other various things in the original games that did not make it to classic.

I have noticed that none of the real parks in any game made it into Classic, as well as every last _Wacky Worlds_ and _Time Twister_ scenario.  Beyond which, Mega Park didn't make it, as well as the scenarios Urban Jungle and Fort Anachronism as well as the three promotional parks.  Also, when I looked carefully at the groups, I noticed that the gold and sapphire groups had no RCT2 parks whatsoever, which would cause the the grouping to fall flat on its face when the user has none of the RCT1 scenarios as @Gymnasiast said, beyond the missing scenarios as well.  However, the new save format would allow us to place the RCT1 scenarios into the base files no problem going forward as compatibility will no longer be a thing, and to fix some scenarios to be in their original standing, would need to have some settings fixed.  That workaround though would fix the scenarios as they appear in Classic, however, it falls flat on its face in its own right when we consider that the Real Parks, Bonus parks, and every park in _Wacky Worlds_ and _Time Twister_ would need to be accounted for, totaling a staggering 49 levels between Mega Park (bonus), Fort Anachronism (bonus, with normal objective), the Eight Real Parks (Alton Towers, Blackpool Pleasure Beach, Heide-Park, Six Flags Holland, Six Flags Great Adventure, Six Flags Belguim, Six Flags Magic Mountain, and Six Flags Over Texas), the "Build Your Own" versions of the five Six Flags parks, Build Your Own Six Flags Park (other), Panda World (DLC, Challenging), Urban Jungle (Loopy Landscapes cut material), and then the 17 scenarios making up _Wacky Worlds_ and the 14 scenarios making up _Time Twister_.

In addition, we would need to place the scenario Tycoon Park into the base files as well.  For the aforementioned reasons in my previous paragraph, the scenario listings as presented by @AaronVanGeffen would fall flat on their face.  However, once we have the new save format in, there shouldn't be anything that would prevent us from getting a new set of groups in and modifying the progression from what I can tell.

**Comment by Gymnasiast** [comment]
Grouping is not affected by the save format. Scenarios only set their difficulty, sorting them into groups is the group's responsibility. The issue here, as far as I'm concerned, is besides difficulty and origin, we would have to support yet another way of grouping, and I'm not convinced the added maintenance burden is worth it.

**Comment by AaronVanGeffen** [comment]
As for the save format: the new save format could support a scenario belonging to multiple groups, I suppose (origin, difficulty, whatever else we throw at it). Not blocking for this issue, either way.

I'm not too fussed about the maintenance argument — it's just one more mapping, after all. However, the fact that a lot of scenarios are missing in the proposed list does make me rethink the usefulness. I probably wouldn't use it myself if base-game scenarios are filed under 'Other' or some such.

**Comment by Gymnasiast** [comment]
Considering we _both_ think it wouldn't be very useful, shall we just close this, then?

**Comment by virginviolet** [comment]
I don't think RCT Classic is missing any scenarios from the original games.
Only the scenarios that OP listed have a progression system, the rest I believe are unlocked from the start.

# Start New Park

## More Park Scenarios

### Challenging Parks

- Panda World

### “Real” Parks

- Six Flags Belgium
- Six Flags Great Adventure
- Six Flags Holland
- Six Flags Magic Mountain
- Six Flags Over Texas

### Other Parks

- Build Your Own Six Flags Belgium
- Build Your Own Six Flags Great Adventure
- Build Your Own Six Flags Holland
- Build Your Own Six Flags Magic Mountain
- Build Your Own Six Flags Over Texas
- Build Your Own Six Flags Park

# Start New Park - Wacky Worlds

### Beginner Parks

- Africa – Victoria Falls
- Asia – Great Wall of China Tourism Enhancement
- North America – Grand Canyon
- South America – Rio Carnival

### Challenging Parks

- Africa – African Diamond Mine
- Asia – Maharaja Palace
- Australasia – Ayers Rock
- Europe – European Cultural Festival
- North America – Rollercoaster Heaven
- South America – Inca Lost City

### Expert Parks

- Africa – Oasis
- Antarctic – Ecological Salvage
- Asia – Japanese Coastal Reclaim
- Australasia – Fun at the Beach
- Europe – Renovation
- N. America – Extreme Hawaiian Island
- South America – Rain Forest Plateau

# Start New Park - Time Twisters

### Beginner Parks

- Dark Age – Robin Hood
- Prehistoric – After the Asteroid
- Roaring Twenties – Prison Island
- Rock 'n' Roll – Flower Power

### Challenging Parks

- Dark Age – Castle
- Future – First Encounters
- Mythological – Animatronic Film Set
- Prehistoric – Jurassic Safari
- Roaring Twenties – Schneider Cup

### Expert Parks

- Future – Future World
- Mythological – Cradle of Civilization
- Prehistoric – Stone Age
- Roaring Twenties – Skyscrapers
- Rock 'n' Roll – Rock 'n' Roll
