### ISSUE TITLE
Save current group in scenario list window

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenRCT2/OpenRCT2#9285]
Something I've noticed playing Locomotion is that it remembers which scenario group (tab) was active last time the scenario list window was used. It uses the normal config struct to achieve this. We should be able to easily introduce something similar.

A potential pitfall is that OpenRCT2 allows you to change the scenario grouping type. The setting should be reset to the first tab when switching types. Such a reset should also happen if an invalid setting is encountered in general, e.g. because RCT1 is no longer linked, or if the config INI file has been tampered with.

**Comment by Spongeloaf** [comment]
I'd like to give this one a shot. It sounds simple enough, but I'm sure I'll manage to crash the game a few dozen times.

**Comment by Spongeloaf** [comment]
Should it be persistent across game sessions?

**Comment by AaronVanGeffen** [comment]
> Should it be persistent across game sessions?

That is what I had in mind, yes. You can use the game config for this.

**Comment by Spongeloaf** [comment]
I've got it working already, I just need to do a little more digging to ensure edge cases won't be missed.
