### ISSUE TITLE
Starting advertisements in multiplayer causes desync

### ISSUE THREAD

**Issue by DoveCannon** [OpenRCT2/OpenRCT2#9287]
OS: Windows 10
Version: v0.2.2-467
Commit/Build: 74fa30a

In multiplayer games as soon as someone starts an advertisement the clients desync nonstop and no amount of resync fixes the issue. After reconnecting the clients immediately desync and see no advertisements running. The host appears unaffected.

This has been happening for many months and seems to happen on every map.

The map we are on tonight is Australasia - Fun At The Beach and it's happening.

**Comment by DoveCannon** [comment]
After the advertisement ran out on the host we all reconnected, no instant desync.

**Comment by monkman71** [comment]
Verified. 

Advertisements seem to have some effect on multiplayer network sync.

**Comment by ZehMatt** [comment]
This seems to be a regression from #8716. MarketingCampaign::Flags are not saved/loaded which is basically a different bug and the desync being a side effect.

**Comment by DoveCannon** [comment]
Tested this in dev last night. Starting an advertisement did not cause an instant desync and upon reconnecting from another desync advertisements were as expected. Thanks for the fix.
