### ISSUE TITLE
Move peep_easter_egg_peep_interactions into a member function

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#9291]
The `peep_easter_egg_peep_interactions` function is currently a static function in the `Peep.cpp` file. It is really a Guest only member function and should therefore be moved to improve readability.
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/peep/Peep.cpp#L3397-L3433

Create a new member funciton of the `Guest` struct called `UpdateEasterEggInteractions`. Move the code from Peep.cpp to the new member function in Guest.cpp. All of the functions related to updating easter egg interactions should also be moved: `peep_apply_easter_egg_to_nearby_guests`, `peep_give_passing_peeps_purple_clothes`, `peep_give_passing_peeps_pizza`, `peep_make_passing_peeps_sick`, `peep_give_passing_peeps_ice_cream`. Perhaps these should also be reworked to use a more C++'y implementation. 

In addition make sure all local variables are in lower camelCase and all function names are in upper CamelCase. https://github.com/OpenRCT2/OpenRCT2/wiki/Coding-Style

When commiting in git try to stick to the commit message format. https://github.com/OpenRCT2/OpenRCT2/wiki/Commit-Messages

**Comment by WhiteRaven02** [comment]
Is this issue still relevant?

**Comment by AaronVanGeffen** [comment]
> Is this issue still relevant?

Yes, it hasn't been picked up yet.

**Comment by WhiteRaven02** [comment]
Can I ask you some questions to you personnally? I`m newbe on Git. And how can I do that, if you are agree?

**Comment by AaronVanGeffen** [comment]
Feel free to join us in the dev channel on Gitter if you have any questions.
