### ISSUE TITLE
Refactor Vehicle state setting

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#9295]
When you change state on a vehicle the vehicle window should also be invalidated. This set and invalidate should be wrapped within a member function so that it can't be forgotten. In addition sub_state is often reset to 0. The sub_state reset needs a bit of further investigation into if this should also be moved into the member function. This is very similar to the Peep::SetState member function.

Create a new public member function of `rct_vehicle` called `SetState` it should take a `vehicle_status` enum as input. You should name the currently unnamed enum (see `vehicle.h`). The function should: set the state; invalidate the window; and depending on investigation of `sub_state`, reset `sub_state` to zero;. After creating the new member function replace all instances of `vehicle->state = xxxx; vehicle_invalidate_window(vehicle); ...` with the new member function. There may be some instances of `vehicle->state = xxxx;` that do not at present invalidate the window. Most likely those are wrong and they should invalidate the window. This task will involve some investigation.

In addition make sure all local variables are in lower camelCase and all function names are in upper CamelCase. https://github.com/OpenRCT2/OpenRCT2/wiki/Coding-Style

When commiting in git try to stick to the commit message format. https://github.com/OpenRCT2/OpenRCT2/wiki/Commit-Messages

**Comment by Spongeloaf** [comment]
I'll give it a shot.

**Comment by Spongeloaf** [comment]
Question time: When you wrote `vehicle->state = xxxx;`, did you mean `vehicle->status = xxxx;` ? Unless I am crazy or blind (Both are entirely possible), I do not see a member or rct_vehicle (or it's parent, rct_sprite_common). However, many places where `vehicle_invalidate_window(vehicle);` is called, I also see `vehicle->status` and `vehicle->sub_state`.

**Comment by duncanspumpkin** [comment]
Yes sorry i meant status. You could just have sub state default value of 0 instead of creating another function and overloading. I think it's important to always consider the sub state when setting status.

**Comment by Spongeloaf** [comment]
My primary hesitation for setting sub_state automatically is that I found a handful of functions that change the status but don't modify the sub_state at the same time. What should be done about those?

**Comment by duncanspumpkin** [comment]
Well you could pass in the current sub state. It's also possible that those functions aren't setting the state correctly.

**Comment by Spongeloaf** [comment]
> There may be some instances of vehicle->state = xxxx; that do not at present invalidate the window. Most likely those are wrong and they should invalidate the window.

Are there any cases you know of that SHOULD NOT invalidate the window? Could calling `invalidate_window()` somewhere where it shouldn't be cause a problem? Visual Studio has found `vehicle->state = xxxx;` in vehicle.cpp, ride.cpp, cablelift.cpp, and gtest-type-util.h.

**Comment by duncanspumpkin** [comment]
Yes I'd leave any importer exporter code alone. There is no harm in calling it and imho it should be called any time the state changes.

**Comment by Spongeloaf** [comment]
In that case, I think this is good to go. There are no more direct assignments to status and the only call to invalidate_window() is now in SetState. I'll create a PR.

**Comment by Spongeloaf** [comment]
We have a new minor issue. 

`s4importer.cpp(1254): error C2440: '=': cannot convert from 'uint8_t' to 'VEHICLE_STATUS'` 

The importer is pulling a uint8t from an `rct1_vehicle` struct. We have a few options here, but I'm not familiar enough with this project to know which is the best.

1. Insert some code in s4importer (and possibly also s6exporter) to safely convert the int to an enum. This seems like the simplest option, but I'm not sure what sort of error handling we may need to include.

2. Change the datatype of the rct1 vehicle to `VEHICLE_STATUS` I do not know how dangerous this could be.

3. Revert the datatype of rct_vehicle::status back to uint8t. This seems counterproductive to the idea of refactoring.

What do you think?

**Comment by duncanspumpkin** [comment]
Point 1 is the correct approach. The rct1/2 structs should all be uint8/16/32. It shouldn't be hard to convert it just check for a value outside of range then do a cast.
