### ISSUE TITLE
tt and ww (+pmt1 and revf1) missing when opening a save

### ISSUE THREAD

**Issue by ricardowordo** [OpenRCT2/OpenRCT2#9326]
Windows 10
0.2.2-34
Commit/Build: don't know

when opening a save it says its missing a few objects.
mostly wacky worlds and time twister, but also the pmt1 and revf1 files.
when pushing the button download everything it downloads then does nothing.
also can't join multiplayer (don't know if it's related to the problem)

Reproducible in RCT2 (vanilla)? don't know
Specific to multiplayer? no

![problem](https://user-images.githubusercontent.com/51166489/58565794-a7b15000-822f-11e9-80cf-f9f32b9b2767.png)

**Comment by X123M3-256** [comment]
Have you checked if those objects are actually present in your ObjData folder? If not, you may need to reinstall RCT2 (the first two objects should be present even if you don't have the expansions).

The download button downloads objects from the NE database; if they are not found there (which these objects won't be), it won't do anything.

**Comment by Gymnasiast** [comment]
This is odd, with the JSON object, there should never be a missing vanilla or WW/TT object (only invisible ones).

Could you upload your save, please?

**Comment by ricardowordo** [comment]
> This is odd, with the JSON object, there should never be a missing vanilla or WW/TT object (only invisible ones).
> 
> Could you upload your save, please?

it happens on every save

**Comment by ricardowordo** [comment]
> Have you checked if those objects are actually present in your ObjData folder? If not, you may need to reinstall RCT2 (the first two objects should be present even if you don't have the expansions).
> 
> The download button downloads objects from the NE database; if they are not found there (which these objects won't be), it won't do anything.

redownload doesn't work

**Comment by Gymnasiast** [comment]
Can you update the newest version and see if the issue is still there?

**Comment by ricardowordo** [comment]
That was a year ago it has since been fixed.
