### ISSUE TITLE
Game Crashes when object without image is shown in scenery tab

### ISSUE THREAD

**Issue by AvanineCommuter** [OpenRCT2/OpenRCT2#9352]
I ran into an issue where I selected an object in the object selector with no preview image. When I scrolled down to where it would appear in the Scenery tab, the game crashes. Just wanted to post in case this wasn't brought up before.

**Comment by AaronVanGeffen** [comment]
Could you attach the object in question?

You also left out the version and platform information we ask for in our template. As this may be relevant to your case, please add this as well.

**Comment by Broxzier** [comment]
When reporting issues here, please do not remove the fields but fill them in instead. We don't have much to work with now.

**Comment by AvanineCommuter** [comment]
Sorry I’m not very familiar with the rules here. 

How do I find the version I’m using? I use launcher so I assume it’s whatever the latest automatic download is. 

I can’t remember which object it was. But I have dozens upon dozens of objects in the object selector that has no preview image. I believe it was something with “bridge” in its name, from the large scenery tab. Sorry I can’t be more specific! :(

**Comment by Ryder17z** [comment]
version is visible in bottom left corner at the main menu of the game

**Comment by Broxzier** [comment]
If you can reproduce this, please try and tell us what object it is that causes the game to crash exactly. When you hover over the object in the Object Selection list, you will see the name and path of the object on the bottom of the window.

**Comment by tupaschoal** [comment]
Closing for lack of reproducibility
