### ISSUE TITLE
Opening object selection or hitting shift+backspace freezes game.

### ISSUE THREAD

**Issue by DCMeGaMaxX** [OpenRCT2/OpenRCT2#9360]
**OS:** [Windows 10 1903]
**Version:** [0.2.2-483]
**Commit/Build:** [dd0649d]

The game will freeze, however sounds will still play and some textures will remain animated (water in log flume)

Opening the scenario editor is fine, but going to the landscape editor and going back to object selection freezes the game.

- [No] Reproducible in RCT2 (vanilla)?
- [No] Specific to multiplayer?

**Steps to reproduce:**
1. Open the object selection menu.
2. Hitting shift+backspace.

**Comment by BlackendSun** [comment]
The same thing happened to me when I go to the invention list

**Comment by Broxzier** [comment]
This is a regression from #9330.
