### ISSUE TITLE
Ad campaigns end too soon

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#9411]
**OS:** Windows 10
**Version:** 0.2.2
**Commit/Build:** 99772ab

In vanilla and up until recently in openrct2, the number of weeks for ad campaigns would start counting down at the start of the next week after you bought the ad. This allowed you to get at most one extra week for free.

Now it is the other way around. If you buy an ad, it starts counting down as if you bought the ad on the first day of the week you bought it in. This means that you potentially only get a single week from a two-week ad. I'm not sure if this was an intentional fix, but I'd argue that this is worse, as instead of getting some extra for free you can get seriously ripped off if you buy at the wrong time.

**Comment by Gymnasiast** [comment]
Appears to be an error. https://github.com/OpenRCT2/OpenRCT2/pull/8716 refactored it, even introduced a flag to mark the first week, but doesn't actually set it.
