### ISSUE TITLE
Increase the height of the Arrow Dynamics tracks for better RCT1 compatibility

### ISSUE THREAD

**Issue by Generalcamo** [OpenRCT2/OpenRCT2#9428]
Consider increasing the height of the Arrow Corkscrew and Hypercoaster to closer match RCT1. Currently, several of the rides included in RCT1 deluxe are impossible to build due to the lowered height limitation. This includes the Pepsi Max Big One in Blackpool Pleasure Beach, which was one of the tallest coasters Arrow built.

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Comment by Gymnasiast** [comment]
Implemented by https://github.com/OpenRCT2/OpenRCT2/pull/9434.
