### ISSUE TITLE
Move Jumping Fountain Update into member functions

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#9474]
The Jumping Fountain Update functions are currently static functions in the Fountain.cpp file. All of them should really be rct_jumping_fountain only member functions and should therefore be moved to improve readability. To begin with move only the `jumping_fountain_update` function into a public member function.
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/world/Fountain.cpp#L152-L191

Create a new public member function of the `rct_jumping_fountain` struct called `Update`. Rename the existing `jumping_fountain_update` function and correct all of the variables that are used in the function. After this has been completed you can continue on to move every update called function listed below into the `rct_jumping_fountain` struct. All of the subsequent member functions should probably be private. Don't try to move them all at once take your time and split them up into a couple compilable commits, it will be easier to review and then you wont get lost. Take extra care with local variables aliasing existing member variables (especially x, y, z).

`jumping_fountain_continue`, `jumping_fountain_goto_edge`, `jumping_fountain_bounce`, `jumping_fountain_split`, `jumping_fountain_random`, `jumping_fountain_create_next`

In addition make sure all local variables are in lower camelCase and all function names are in upper CamelCase. https://github.com/OpenRCT2/OpenRCT2/wiki/Coding-Style

When commiting in git try to stick to the commit message format. https://github.com/OpenRCT2/OpenRCT2/wiki/Commit-Messages

**Comment by 41northstudios** [comment]
I'll work on this issue
