### ISSUE TITLE
Running `simulate` command on park yields `Completed: (null)`

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#9476]
**OS:** Linux
**Commit/Build:** 6bd298b3a

Running `simulate` command on a park yields invalid value.

Actual output:
```
$ ./openrct2-cli simulate ~/.config/OpenRCT2/save/titleseq/CocoaBayou.sv6 1
Running 1 ticks...
Completed: (null)
```

Expected output:
```
$ ./openrct2-cli simulate ~/.config/OpenRCT2/save/titleseq/CocoaBayou.sv6 1
Running 1 ticks...
Completed: 150e13adb0876f4ef18d675ebca143877e11a294
```

**Comment by IntelOrca** [comment]
I don't think this has ever worked.

**Comment by janisozaur** [comment]
Thanks!

**Comment by ZehMatt** [comment]
It used to work until the sprite hash was refactored into a struct, also thanks for fixing it, the thing went unnoticed for a while actually.

**Comment by IntelOrca** [comment]
@ZehMatt It didn't work while its been in `develop`, it must have only worked within your branch.

**Comment by ZehMatt** [comment]
https://github.com/ZehMatt/OpenRCT2/blob/3148549d6dbc916de7f3a0616202e64827190ee4/src/openrct2/world/Sprite.h

It used to return const char* but I refactored that later on.
