### ISSUE TITLE
Process exit code is always 0

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#9477]
The function NormalisedMain is currently returning gExitCode but gExitCode is never assigned anywhere. The process should return EXIT_FAILURE when something wen't wrong and EXIT_SUCCESS when everything goes according to plan.

So everything that currently results gExitCode has to be refactored.

**Comment by DzikiChrzan** [comment]
I'd like to take this. I presume task is stall available?

**Comment by AaronVanGeffen** [comment]
No, #10048 aims to tackle this already.
