### ISSUE TITLE
Staff cannot be hired in pause mode

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#9485]
**OS:** Ubuntu 19.04
**Version:** 0.2.2+
**Commit/Build:** b25c1c80887d571a69989838cc7a2513903af700

You cannot hire staff in pause mode. This is possible in vanilla and used to be possible in OpenRCT2. Most likely caused by the Game Action port of the relevant function.

**Comment by 41northstudios** [comment]
Investigating
