### ISSUE TITLE
Refactor of Game Actions to use CoordsXY

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#9495]
For the past couple years we have slowly been moving the old Game Command framework into Game Actions. This is now almost complete (all networked commands have moved over). Over the past few years we have slowly moved to a consistent style of using CoordsXY... for all big coordinates (32 units per tile). Game Actions should all use CoordsXY... for all X Y... parameters. 

> For reference we call things big coordinates (CoordsXY) if they are 32 units for each tile for X and Y. Small coordinates (TileCoordsXY) are 1 unit for each tile for X and Y. The Z coordinate works a bit differently. Each tile has a base height and clearance height which is a small coordinate. This is converted to a big coordinate by multiplying by 8. There are also some items that take a micro z coordinate which is half of a small coordinate (see park entrances). So for Z coordinates you see a lot of `*8, *16`. Big coordinates can be converted into screen coordinates and should be preferred in almost all situations. Small coordinates should only be used for tile references (a lot of game actions are actually for tile references but it is still preferred to move to big coordinates). 

Below is a list of game actions that should be refactored to take a CoordsXY... term:

1. WallRemoveAction: Uses TileCoordsXYZD these are small coordinates (1 unit per tile). Move to CoordsXYZD.
2. SmallSceneryRemoveAction: Uses X, Y, baseHeight as separate terms. X and Y are large coordinates, baseHeight is a small coordinate. Move to CoordsXYZ.
3. RideSetColourSchemeAction: Uses X, Y, Z, Direction as separate terms. X, Y and Z are large coordinates. Move to CoordsXYZD.
4. PlaceParkEntranceAction: Uses X, Y, Z, Direction as separate terms. X and Y are large coordinates, Z is a micro coordinate. Move to CoordsXYZD.
5. MazeSetTrackAction: Uses X, Y, Z, Direction as separate terms. X, Y and Z are large coordinates. Move to CoordsXYZD.
6. LargeSceneryRemoveAction: Uses X, Y, baseHeight, direction as separate terms. X and Y are large coordinates, baseHeight is a small coordinate. Move to CoordsXYZD.
7. FootpathRemoveAction: Uses X, Y, Z as separate terms. X and Y are large coordinates, Z is a small coordinate. Move to CoordsXYZ.

Notice how in the above list the Z coordinate is sometimes in terms of small, big, micro. That is confusing and is precisely why this is being refactored.

When changing the above you will need to change the calling functions as well as the game action. All changes will require a network version bump. If you are getting into any problems just ask. If you don't feel comfortable doing them all just do one or two. No need to change them all in one go.

(I'm pretty sure all of the game actions now follow this but just in case) In addition make sure all local variables are in lower camelCase and all function names are in upper CamelCase. https://github.com/OpenRCT2/OpenRCT2/wiki/Coding-Style

When commiting in git try to stick to the commit message format. https://github.com/OpenRCT2/OpenRCT2/wiki/Commit-Messages

**Comment by 41northstudios** [comment]
I'll start working on this

**Comment by 0Cufox0** [comment]
I'll also try my best

**Comment by AaronVanGeffen** [comment]
Please don't both do the same thing. Coordinate your efforts on Gitter.

**Comment by 0Cufox0** [comment]
> Please don't both do the same thing. Coordinate your efforts on Gitter.

On it, sorry it's my first time with open-sourcing, I'm trying to get used to things(I know this isn't the best place to start)

**Comment by 0Cufox0** [comment]
> I'll start working on this



> I'll start working on this

can you please tell me how far you made it with this?

**Comment by 41northstudios** [comment]
It’s in progress.

**Comment by AaronVanGeffen** [comment]
Feel free to make a WIP PR with your work so far.

**Comment by 41northstudios** [comment]
> Feel free to make a WIP PR with your work so far.

Will do. Sorry, haven't gotten much done on this the last few days (traveling during the holiday here in the US) but am resuming work today and will hopefully have some work to show shortly. Just need to get my changes to a good commit point.

**Comment by 41northstudios** [comment]
@0Cufox0 why did you work on this issue when I told you I was working on it??!? 

Bah - my own fault for not posting a PR I suppose (been out of commission with a sinus infection for a week and a half), but next time I'd appreciate you not working on the same issue I already sunk a bunch of time into.

**Comment by 0Cufox0** [comment]
@41northstudios oww I'm so sorry it's all my bad nah, I just got too excited cause I found something to do....
Don't worry I'll be better than that next time ,
sorry for I wasted your time! 
Hope you're better now :< <3

**Comment by 41northstudios** [comment]
Thanks. No worries, just try to coordinate next time. Welcome aboard. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by duncanspumpkin** [comment]
Closed by #9531
