### ISSUE TITLE
libcrypto/OpenSSL error for new Linux builds (Ubuntu 18.04)

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#9506]
**OS:** Ubuntu 18.04
**Version:** 0.2.2
**Commit/Build:** e149722a154725460385e1a1c0af8c66c02b95d2

When trying to run the Linux build downloaded from [OpenRCT2.org API (which redirects it to GitHub)](https://openrct2.org/altapi/?command=get-latest-download&gitBranch=develop&flavourId=9), I get the following error:

```
OpenRCT2/openrct2: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by /home/me/downloads/temp/OpenRCT2/libopenrct2.so)
```

This was not the case with builds downloaded from OpenRCT2.org before.

**Comment by Broxzier** [comment]
Running a build of e149722 that I made myself with `cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo && make` does not give me this error.

**Comment by Gymnasiast** [comment]
On Ubuntu 19.04, I get this error: 
`libzip.so.4: cannot open shared object file: No such file or directory`

**Comment by janisozaur** [comment]
I can load https://github.com/Limetric/OpenRCT2-binaries/releases/download/v0.2.2-a7f8960/OpenRCT2-0.2.2-develop-a7f896015-linux-x86_64.tar.gz on a fresh Ubuntu 18.04 VM just fine. I'm going to assume @Broxzier doesn't have the required library installed.

**Comment by janisozaur** [comment]
The package in question is `libssl1.1`

**Comment by Gymnasiast** [comment]
Since OpenRCT2 works correctly in a VM for me as well, I'm going to chalk this up as a problem on Broxzier's system.

**Comment by Broxzier** [comment]
It was indeed an issue on my end. Apparently the package used for the build has changes, and my machine was behind.
