### ISSUE TITLE
Time Twister object artdec29 conversion problem

### ISSUE THREAD

**Issue by EtienneGL** [OpenRCT2/OpenRCT2#9520]
**OS:** Windows 7
**Version:** 0.2.2-584
**Commit/Build:** a7f8960

The Time Twister object Art Deco Inverted Corner Section of the code artdec29 is not converted properly in OpenRCT2. It is shifted toward the center of the tile and moved upward instead of being on the corner of the tile at the right height. Considering the object is not corrupted in the original game, this is an OpenRCT2-only bug. It's not specific to singleplayer or multiplayer.

**Steps to reproduce:**
This can easily be noticed in the scenario Roaring Twenties - Skyscrapers:
1. In both vanilla RCT2 Time Twister and OpenRCT2, open the scenario Roaring Twenties - Skyscrapers.
2. Look at the orange and turquoise art-deco building on the top left of the map when you start the scenario. Compare the building in the 2 games.

You can also just compare the object in question in a different Roaring Twenties scenario or in the scenario editor.

**Dump file**
No dump file needed.

**Screenshots / Video:**
Original RCT2 Time Twister:
![SCR1](https://user-images.githubusercontent.com/33940430/60636271-c7fe9c80-9de3-11e9-91ed-4dc4ecb35b76.png)

OpenRCT2:
![Metropolis 2019-07-03 22-18-02](https://user-images.githubusercontent.com/33940430/60636305-e49ad480-9de3-11e9-9c70-c3cb11577f4d.png)

**Save game:**
No save needed. You only need the Time Twister expansion and the scenario in question.

**Comment by Gymnasiast** [comment]
I have now fixed the object in the `objects` repository. I will now have to do an objects release before this bug can be closed.

**Comment by Gymnasiast** [comment]
Now fixed.
