### ISSUE TITLE
Door/Portcullis sounds are not working

### ISSUE THREAD

**Issue by Generalcamo** [OpenRCT2/OpenRCT2#9533]
**OS:** [e.g. Windows 10]
**Version:** v0.2.2-8ff0cf9

Extends #8108 
Doors and Portcullises are supposed to play a sound when they open and close. However, this currently does not play, leaving only silence.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Build a Tunnel of Horror ride
2. Place a door on a track piece
3. Hear no sound

**Comment by Ryder17z** [comment]
Does zoom level affect this?

**Comment by duncanspumpkin** [comment]
I'm going to take a wild guess and say this only happens in json objects and not in custom objects. And I'll also take a wild guess that json objects store door sound under "doorSound" and not "scrollingMode" that the game currently looks for them under.

**Comment by duncanspumpkin** [comment]
Okay there are multiple bugs here. One is the code looking for the wrong field. One is the code using the wrong x variable. One is the json objects incorrectly setting the sound.

This is going to be annoying to fix as we need to check every door and make sure they agree with vanilla.
