### ISSUE TITLE
Riders' Screams randomly cut off on diagonal drops

### ISSUE THREAD

**Issue by Generalcamo** [OpenRCT2/OpenRCT2#9534]
**OS:** Windows 10
**Version:** v0.2.2-8ff0cf9

On diagonal drops, the riders' screams tend to cut off randomly, then restart soon after (sometimes with a different scream, sometimes not). This is a vanilla bug as I do remember it in both RCT1 and RCT2, so finding the cause may be more difficult.

- [x] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Build a long diagonal drop on a ride (like the Hyper Twister) 
2. Listen to the screams cut off

**Comment by zzril** [comment]
I noticed this bug while investigating another, unrelated one ( #19780 ).  
It can be observed, for example, in "Goliath" (Six Flags Magic Mountain) in the valley after the large diagonal drop: Guests do not scream on the steep diagonal section, but start to scream when entering the valley.

I tested this in singleplayer mode, on Linux, on a build based on commit 72753778e7d763136f263151b56c9f68cfd5b8d6 .

From what I can tell, this is the logic that determines whether guests scream:
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/ride/Vehicle.cpp#L5535-#L5548
(This is only executed when the train is going forward, and has a minimum speed of 2.75 mph. A similar code section a few lines up determines when to scream when the train is going backwards.)

The code iterates through all vehicles of the train and checks their Pitch value (which encodes the current pitch / "slope").

I could not find a good explanation for the meaning of the different Pitch values, so ran some experiments in gdb. This is what I found:  
| tile                 | Pitch value |
|----------------------|-------------|
| vertical up          | 0x0a = 10   |
| steep up             | 0x04 = 04   |
| steep diagonal up    | 0x34 = 52   |
| gentle up            | 0x02 = 02   |
| gentle diagonal up   | 0x33 = 51   |
| level                | 0x00 = 00   |
| gentle diagonal down | 0x36 = 54   |
| gentle down          | 0x06 = 06   |
| steep diagonal down  | 0x37 = 55   |
| steep down           | 0x08 = 08   |
| vertical down        | 0x12 = 18   |

These values are all for straight pieces. The transitions between different slopes occuring in the valley after Goliath's diagonal drop produce these Pitch values:  
`0x37`, `0x07, `0x06`, `0x36`, `0x35`, `0x00`, `0x32`, `0x33`, `0x02`, `0x03`, `0x34`. (Ordered by first occurence of the respective value in gdb.)

The steep diagonal down piece produces a Pitch value of 0x37 = 55. This is larger than 23, so the above code will not call ProduceScreamSound as long as the train is entirely on the steep diagonal drop section.  
However, both at the start of the drop and in the valley, Pitch values of 7 and 6 occur, leading to ProduceScreamSound getting called at those 2 points.  
This results in 2 distinct screams, a correct one at the start of the drop and a second (incorrect) one in the valley.

A fix would probably include adding a check for the Pitch values >= 24 occuring in the diagonal drops (and transitions to/from them), and making sure ProduceScreamSound gets called correctly there. This should lead to ProduceScreamSound getting called continously over the drop every tick, which - if I understand correctly -  is supposed to result in only one scream.  
(Currently, it would result in the scream being looped, but that's a different bug, see #19780 .)  
The same would then need to be repeated for the case where the train is going backwards.

---

Another approach would be to try to re-use the logic from UpdateMeasurements (starting [here](https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/ride/Vehicle.cpp#L1591)) that is responsible for counting drops for the stats.
