### ISSUE TITLE
Revamp scenario select window

### ISSUE THREAD

**Issue by LaPingvino** [OpenRCT2/OpenRCT2#954]

**Comment by IntelOrca** [comment]
My plan is to revamp the scenario select dialog with the groups RCT1, AA, LL, RCT2, WW, TT and custom other ones. RCT1 scenarios will have opt-out unlocking feature and hidden mega park scenario.

**Comment by crazyurbanmyth** [comment]
Will there be a custom set of scenario's for the game that come with it? If so do you need custom scenarios made for the game?

**Comment by PFCKrutonium** [comment]
I imagine custom scenarios, but it is too early I think to be making them. I mean, if you want to...

**Comment by LaPingvino** [comment]
It would be cool to have an RCT1-style unlock-based OpenRCT2 scenario series for the 1.0 release. ;)

**Comment by Wimali** [comment]
I think what would make the most sense is to have three menu's-- Classic, Sandbox & Campaign. Campaign would be scenario's consisting of multiple "maps", where you have to unlock them one by one (like Star Wars Galactic Battlegrounds, for lack of a better comparison), Sandbox would be, well, sandbox maps; and Classic would be all the original maps from RCT1 & RCT2 + expansions.

**Comment by Patrik356b** [comment]
I fully agree with the post above

**Comment by pizza2004** [comment]
Well, I think IntelOrca outlined how it should work well.  There doesn't need to be some classic mode, but I think maps should be in 'packs', where if you click RCT2 it'll bring up the menu like it looks in RCT2, or if you click RCT1 it bring it up like it looks in RCT1.  You could do a few other things, like allow people to make their own custom packs, and let regular custom maps be in the RCT2 one or whatever.

**Comment by AaronVanGeffen** [comment]
This has been implemented per #2628.
