### ISSUE TITLE
CI builds should depend on clang-format result

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#9542]
We can avoid a lot of unnecessary building if the build process depends on the clang-format stage. This should also simplify the process of people trying to fix the format by getting faster CI responses.

**Comment by duncanspumpkin** [comment]
But wont that mean we need to fix the formatting before we fix the compilation of the code?

**Comment by ZehMatt** [comment]
Pretty much.

**Comment by janisozaur** [comment]
I would also make clang-format not download any docker images, but use a (mostly?) static binary instead.

**Comment by tupaschoal** [comment]
This is already the case
