### ISSUE TITLE
Refactor some map functions

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#9557]
As we are always striving to make things more readable one of the main areas is making it clear as to what type of coordinate to call a function with. There are a number of map functions where it is not clear if you should use small or big coordinates. 

> For reference we call things big coordinates (CoordsXY) if they are 32 units for each tile for X and Y. Small coordinates (TileCoordsXY) are 1 unit for each tile for X and Y. The Z coordinate works a bit differently. Each tile has a base height and clearance height which is a small coordinate. This is converted to a big coordinate by multiplying by 8. There are also some items that take a micro z coordinate which is half of a small coordinate (see park entrances). So for Z coordinates you see a lot of *8, *16. Big coordinates can be converted into screen coordinates and should be preferred in almost all situations. Small coordinates should only be used for tile references (a lot of game actions are actually for tile references but it is still preferred to move to big coordinates).

From a quick look at world/map.cpp there are the following functions that use ambiguous coordinates:

1. `map_can_build_at`: Uses big coordinates should have a parameter of CoordsXYZ.
2. `map_is_location_owned`: Uses big coordinates should have a parameter of CoordsXYZ.
3. `map_is_location_owned_or_has_rights`: Uses big coordinates should have a parameter of CoordsXY.
4. `map_coord_is_connected`: Uses small coordinates should have a parameter of TileCoordsXYZ. `face_direction` isn't really tied to the tile coordinate for this function so shouldn't become part of that parameter.
5. `tile_element_height` and its sister function `tile_element_water_height`: Both use big coordinates should have a parameter of CoordsXY.
6. `map_get_lowest_land_height` and its sister function `map_get_highest_land_height`: Both use big coordinates should have a single parameter of MapRange.
7. `map_is_location_at_edge`: Uses big coordinates should have a parameter of CoordsXY.
8. `tile_element_insert`: Uses small coordinates should have a parameter of TileCoordsXYZ.

The above functions are not a complete list (but for now lets just think about them) and are used in a considerable number of locations. Be very careful when changing them and make sure tests pass after modifying each one.

In addition make sure all local variables are in lower camelCase and ~~all function names are in upper CamelCase.~~ **Don't change the function names at this time. They will renamed later when they are refactored into a more cpp structure.** https://github.com/OpenRCT2/OpenRCT2/wiki/Coding-Style

When commiting in git try to stick to the commit message format. https://github.com/OpenRCT2/OpenRCT2/wiki/Commit-Messages

**Comment by Gymnasiast** [comment]
> There are also some items that take a micro z coordinate which is half of a small coordinate (see park entrances)

I want to refactor those out. I already did so with the peep spawns.
