### ISSUE TITLE
Fixing ride chain sounds

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#9568]
Ride | Current sound | Proposal
-- | -- | --
SLC | Friction wheels | Classic chain sound or Arrow sound
Reverser RC | Classic chain sound | Side-friction RC sound

**Comment by iking96** [comment]
@Gymnasiast What does SLC stand for?

**Comment by Gymnasiast** [comment]
It stands for Suspended Looping Coaster, indeed. In RCT2 and OpenRCT2, it is referred to as "Compact Inverted Coaster".
