### ISSUE TITLE
Korean texts are overflow in the scenario objective window

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#9574]
**OS:** Any OS
**Version:** 0.2.3
**Commit/Build:** 6eda049

Scenario objective tab(window) can't display whole korean texts when the description is very long as you can see below (since korean text's line height is wider than english)
I think it will be great if the window's size could be longer or flexible.

![image](https://user-images.githubusercontent.com/10726524/61214036-c321dd00-a741-11e9-8fac-c40f048e4608.png)

**Comment by AaronVanGeffen** [comment]
Hmm, our window system isn't flexible enough to handle such matters universally. However, if this is an exceptional case, I'm sure we can work something out.

**Comment by AaronVanGeffen** [comment]
Could you give an example of a scenario that exhibits this behaviour?

**Comment by telk5093** [comment]
@AaronVanGeffen [The scenario which of the screenshot I attached above from](https://rctsc.telk.kr/download?no=142)
