### ISSUE TITLE
objective can't display right when choose Chinese-Simplified language

### ISSUE THREAD

**Issue by htf6782414** [OpenRCT2/OpenRCT2#9575]
**OS:** [e.g. Windows 10 64bit]
**Version:** [e.g. 0.2.3]
**Commit/Build:** [e.g. ac7a1eb-master]

**Steps to reproduce:**
1. run openrct2.exe and change the language to Chinese-Simplified.
2. start a new game.
3.move the mouse to the "Crazy Castle " ，then the objective display in the right part.

In English，it is right.  “To have at least **1,500** guests in your park at the end of **October,Year 4**, with a park rating of at least 600”

But in Chinese ,it is wrong. "在4年,7月之前乐园内至少有31游客, 并且乐园评分不低于 600" (To have at least **31** guests in your park at the end of **July,Year 4**, with a park rating of at least 600) [You can see it by 2 Screenshots]

the number of guests and the time both be wrong, I open the language files in /date/language/, and find it in en-GB.txt and zh-CN.txt.

"STR_2386    :{BLACK}To have at least {COMMA16} guests in your park at the end of {MONTHYEAR}, with a park rating of at least 600"

"STR_2386    :{BLACK}在{MONTHYEAR} 之前乐园内至少有 {COMMA16} 游客, 并且乐园评分不低于 600"

Why the value of {MONTHYEAR} and {COMMA16} will change when I change the language to Chinese-Simplified?

**Screenshots / Video:**
![english](https://user-images.githubusercontent.com/52906001/61216307-8f45b800-a73f-11e9-8a53-99de87b953aa.jpg)

![Chinese](https://user-images.githubusercontent.com/52906001/61216340-a2f11e80-a73f-11e9-8824-9083c2ba76ed.jpg)

**Comment by AaronVanGeffen** [comment]
The placeholders are in a different order in the language file, but the arguments in the program will not be. Hence, the `{MONTHYEAR}` will interpret the value meant for the `{COMMA16}` and vice versa.

To solve this, the `{MONTHYEAR}` should be preceded by a `{POP16}`, e.g. `{POP16}{MONTHYEAR}`. Similarly, the `{COMMA16}` should be preceded by a `{PUSH16}`, e.g. `{PUSH16}{COMMA16}`.

It's a little cumbersome, but used to effect in the Korean and Japanese language files, too.

**Comment by telk5093** [comment]
I think this will work:
```
STR_2386 :{BLACK}在{POP16}{POP16}{MONTHYEAR} 之前乐园内至少有 {PUSH16}{PUSH16}{PUSH16}{COMMA16} 游客, 并且乐园评分不低于 600
```
Note that there are TWO ``{POP16}``s in front of ``{MONTHYEAR}``, and THREE ``{POP16}``s in front of ``{COMMA16}``

We, korean, do not change ``{COMMA16}`` and ``{MONTHYEAR}``'s order in STR_2386,
but Korean translation using such technique in other obejectives such as (STR_2387)[https://github.com/OpenRCT2/Localisation/blob/master/data/language/ko-KR.txt#L1739]

**Comment by Gymnasiast** [comment]
Fixed by https://github.com/OpenRCT2/Localisation/pull/1736.
