### ISSUE TITLE
Visitors are hanging at the edge of the playfield

### ISSUE THREAD

**Issue by mase76** [OpenRCT2/OpenRCT2#9621]
Hi!
I have multiple visitors hanging at the edge of the playfield. They anounce, that they are hungry, thirsty, etc, but I am not able to let them move around again. I am also not able to pick them up. It is greyed out.
I have made a screenshot.
![hang](https://user-images.githubusercontent.com/2173853/61591317-d6133200-abc5-11e9-9eff-f9825baa54cf.png)

**Comment by Gymnasiast** [comment]
You made an error in your scenario (or the one who made the scenario did), by placing or leaving a guest entry point there. You need to either fix the scenario, or turn on Sandbox mode, open the Map window, select the guest entry point tool and click the _real_ one until the incorrect one disappears.

**Comment by jensj12** [comment]
To get rid of the guests there, simply place a footpath in front of them. Do what Gymnasiast said to prevent any new guests from spawning there.
