### ISSUE TITLE
Some object's expected cost is estimated as $0

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#9625]
**OS:** Windows 10
**Version:** 0.2.3
**Commit/Build:** 5342a6d

The expected cost of some object that positioned in the bottom of the scenary window is estimated as $0. I think the only large objects' cost seems to be estimated as $0.

**Steps to reproduce:**
1. Open a scenary window
2. Select some object, especially large object such as mine buildings
3. Hover mouse cursor into main game view
4. See the scenary window's bottom.

**Screenshots / Video:**
See the "Cost:", which is positioned in the right bottom of scenary window.
![1](https://user-images.githubusercontent.com/10726524/61611797-b3514e00-ac97-11e9-8b65-435f8543fd6c.gif)

**Comment by ZehMatt** [comment]
If I had to guess then I would say its probably LargeSceneryPlaceAction not resulting the correct cost on Query
