### ISSUE TITLE
Ride Ratings Refactoring

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#9676]
Ride ratings (src/openrct2/ride/RideRatings.cpp) has a number of variables that are labelled by their register name or by a hex number. All of these variables are now known and should be refactored to explain things easier.

For example:
```
    rating_tuple var_10E_rating = get_flat_turns_rating(ride);
    excitement += var_10E_rating.excitement;
    intensity += var_10E_rating.intensity;
    nausea += var_10E_rating.nausea;

    rating_tuple var_110_rating = get_banked_turns_rating(ride);
    excitement += var_110_rating.excitement;
    intensity += var_110_rating.intensity;
    nausea += var_110_rating.nausea;
```
`var_10E_rating` is now known to be used for flat turns. So this variable should be `flatTurnsRating`. There are numerous cases very similar to this throughout this source file.

In addition make sure all local variables are in lower camelCase ~~and all function names are in upper CamelCase.~~ **Don't change the function names at this time. They will renamed later when they are refactored into a more cpp structure.** https://github.com/OpenRCT2/OpenRCT2/wiki/Coding-Style

When commiting in git try to stick to the commit message format. https://github.com/OpenRCT2/OpenRCT2/wiki/Commit-Messages

**Comment by jgottula** [comment]
I'll take a stab at this. Will post a PR when I have something ready.
