### ISSUE TITLE
Entering custom size for water/land tool allows confirmation with main enter key, but not numpad enter key

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#9684]
**OS:** Windows 8
**Version:** 0.2.3
**Commit/Build:** 8378790

When you're entering the desired size of the tool in the water or land tool with the keyboard, it lets you confirm entry with the main enter key, but _not_ with the numpad enter key.

I'm talking about when you click the number in one of these windows:
![Forest Frontiers 2019-07-29 23-21-51](https://user-images.githubusercontent.com/26573303/62105683-e8d9d680-b257-11e9-9ab9-a74915c8fa1c.png) 
![Unnamed park 2019-07-29 22-58-51](https://user-images.githubusercontent.com/26573303/62105692-ed05f400-b257-11e9-89fa-7a7eb8d8777b.png)
and then a dialog box pops up to let you type in a number between 1 and 64.

You can then submit the number by clicking the OK button on that window, _or_ by pressing the keyboard's main enter key, but _not_ the numpad enter key. This is inconvenient when typing in the number on the numpad.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Select land or water tool.
2. Click the number in the center of it.
3. Type in a valid number.
4. Attempt to submit by pressing the numpad enter key.

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by jgottula** [comment]
Based on some quick testing, the same thing also applies to:
- the OK/Cancel input window that appears when clicking on price up/down boxes
- the OK/Cancel input window that appears when setting a park/ride/guest's name

Also it's probably worth mentioning that while normal Enter triggers the OK button action, there isn't any key that does the same the Cancel button. Backspace just edits the text box, and Escape doesn't do anything at all. Probably it would be desirable for Escape to trigger Cancel...? Unless I'm missing something here.

**Comment by jgottula** [comment]
And yeah, even if you have a tool window open in the background (e.g. the raise/lower land tool window), which would normally be closed by the Escape key as per the default keyboard shortcuts, and then in the foreground you decide to rename a peep or a ride or whatever, and that input box is up, the Escape key input doesn't make it to the tool window in the background. So it seems like having Escape map to Cancel wouldn't be problematic.
