### ISSUE TITLE
Number entry for land/water tool size disables shortcut keys

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#9685]
**OS:** Windows 8
**Version:** 0.2.3
**Commit/Build:** 8378790

When entering in a number with the keyboard for the size f the land/water tools, keyboard shortcuts that use the ctrl key don't work.
For example, it's impossible to take a screenshot of the number entry window by pressing ctrl+s.
In that example, the 's' does not get typed in the the text entry, but it also doesn't trigger the desired shortcut key.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open the land or water tool.
2. Click the number in the tool for keyboard size entry.
3. Before submitting the new number, attempt to take a screenshot by pressing ctrl+s.
4. The shortcut key does not work.

**Comment by Gymnasiast** [comment]
I think the reason for this is that keys like CTRL are also used for character entries on many keyboard layouts. Because of this, I fear that fixing this will cause problems with text input.
