### ISSUE TITLE
Feature: Make main view follow a person/vehicle by double-clicking center view button

### ISSUE THREAD

**Issue by ocalhoun6** [OpenRCT2/OpenRCT2#9711]
**OS:** Windows 8
**Version:** 0.2.3
**Commit/Build:** 8378790

It would be nice in some cases to have the main view follow a particular guest/staff member/ride vehicle the way a window view does. I think there's already a way to do that somehow, but as far as I'm aware, there's no _easy_ way to do that.

I think an intuitive and easy way to do it would be to have the center view button (red arrow in image below) have two actions. On a single click, it would center the main view on the same target as the window. But if you double click it, it would have the main view follow that target until the cursor touches the edges of the screen again. (I think trying to scroll the view normally should break out of this following mode, but having it quit following when you close the window might also make sense.) The center view button could remain depressed like the notification button on this peep's window remains depressed.

The double-click to center things already has an analogous control. When you double click on the view tab (green arrow in the image below), that gives you the audio from that window. So I think double-clicking the center view button makes a lot of sense for how to activate this view following mode.

And, as an extra bonus, it doesn't clutter anything up or make anything confusing. Players who don't use this feature will probably never notice it or know that it's there.

![Red Sea 2019-08-01 21-41-09](https://user-images.githubusercontent.com/26573303/62345488-7c551680-b4a7-11e9-9cca-456c1c83a87a.png)

**Comment by duncanspumpkin** [comment]
Double clicking is not used by the UI at all. Clicking twice on the overview tab causes the sound to be disabled. That is not the same as double clicking which has to happen within a certain amount of time. If this was to be added the correct way would probably be a dropdown box from the center view button.

**Comment by Mkerian10** [comment]
@duncanspumpkin What about making it shift-click or something similar?

**Comment by Liampie** [comment]
If it's easy to add new buttons, you can also use the camera pictogram.

**Comment by SevenChords** [comment]
any update on if/when this is going to be implemented?
