### ISSUE TITLE
large scenery banners have incorrect colour and scrolling

### ISSUE THREAD

**Issue by Gammadivided** [OpenRCT2/OpenRCT2#9715]
**OS:** Windows 10
**Version:** 0.2.3-101
**Commit/Build:** fcc41b4

All of a sudden, I've noticed that, in my park, all my 2-wide scrolling text signs were the wrong color. The background color still loads fine, but all text, which was previously a bunch of different colors for different signs, turned black (and a weird off-white in some cases). The text also keeps stuttering instead of scrolling properly. After a bit of experimenting, I've been able to reproduce this in every park I opened, so it's not a bug specific to one save file. Strangely, this issue only occurs with 2-wide scrolling signs, not with 1-wide, path signs, or entrance scrolling text. This is a pretty small and harmless bug, but one that still warrants fixing, as it renders scrolling signs unusable in some cases.

I don't think this is a language-related issue, as I've tried it with both English (US) and English (UK). Still the same bug.

**Steps to reproduce:**
1. Open any park that includes the 2-wide scrolling text sign as an object
2. Place the 2-wide scrolling sign
3. Try to recolor the banner text - the text will remain black (or beige?)

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/11410845/62384096-a972f900-b57b-11e9-93ec-ff10ac85db36.png)

**Comment by telk5093** [comment]
![image](https://user-images.githubusercontent.com/10726524/62387061-97ea1b00-b594-11e9-9715-6c45e07ab715.png)

For CJK users, something similar issue occurs at the park/ride name sign, too.
