### ISSUE TITLE
invalid path to RCT1

### ISSUE THREAD

**Issue by legluondunet** [OpenRCT2/OpenRCT2#9720]
**OS:** 
Linux Ubuntu 19.04
**Version:**
last git version from 4 august 2019
**Commit/Build:** [e.g. 426e106]
./openrct2 -v
OpenRCT2, v0.2.3-105 (c3234b144 on develop, DEBUG)
Linux (x86-64)

openRCT2 gave me an error message: RCT1 path invalid

**Steps to reproduce:**
1. in options, advanced parameters, click "path to RCT1"
2. I set the path to my RCT1 Gog install and it gave me an error message

verbose log:
```
VERBOSE: CreateObjectFromJsonFile("/home/legluondunet/Bureau/OpenRCT2/build/usr/local/share/openrct2/object/official/station/openrct2.station.noentrance.json")
VERBOSE: CreateObjectFromJson(...)
VERBOSE: 112 / 721 new objects loaded
VERBOSE: Inspecting ride entrance / exit locations
VERBOSE: executing "which zenity 2> /dev/null"...
VERBOSE: executing "/usr/bin/zenity --title='Veuillez choisir votre installation de RCT1' --file-selection --directory /"...
WARNING[/home/legluondunet/Bureau/OpenRCT2/src/openrct2/util/Util.cpp:417 (safe_strcpy)]: Truncating string "/home/l" to 8 bytes.
VERBOSE: file '/home/l/Data/CSG1.DAT' exists = 0
VERBOSE: file '/home/l/Data/CSG1.1' exists = 0
VERBOSE: show error, �Veuillez choisir une installation valide de RCT1
```
My path to RCT1: /home/legluondunet/Games/rollercoaster-tycoon-deluxe/drive_c/GOG Games/RollerCoaster Tycoon Deluxe
Why openRCT2 truncated my path to '/home/l/ ?
It seems openRCT2 does not support long path with space to RCT1?

Thank you for your help.

**Comment by IntelOrca** [comment]
Could you try editing your config file manually and setting the RCT1 path?
It is probably located at `/home/legluondunet/.config/OpenRCT2/config.ini`.

This issue might be related to the file input dialog.

**Comment by legluondunet** [comment]
If I manually put the path to RCT1 to the config file, it works.

**Comment by IntelOrca** [comment]
You can also pass the path as a command line argument `--rct1-data-path <path>`

**Comment by legluondunet** [comment]
Could you say me where is the code where you call Zenity window?

**Comment by IntelOrca** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2-ui/UiContext.Linux.cpp#L210

**Comment by legluondunet** [comment]
Finally too complicated for me :D

**Comment by Kuriibo** [comment]
I‘ve had a similar issue on MacOS. I installed the original discs through WINE, and when I used the options menu to select the RCT1 path, it said it was invalid. When I set the path in the .ini manually, it works just fine.

**Comment by visor841** [comment]
Just another data point, had the same thing happen to me (invalid when choosing in-game, but works fine when setting the path manually using the config file). Xubuntu 18.04.

**Comment by Gymnasiast** [comment]
Fixed by https://github.com/OpenRCT2/OpenRCT2/commit/f7a8f5a0c7243db52dd6ec61ac662835e492bdf7.
