### ISSUE TITLE
Banners have undefined strings

### ISSUE THREAD

**Issue by ZehMatt** [OpenRCT2/OpenRCT2#9728]
Setting text on any banner doesn't seem to work currently.

![2019-08-05_18-48-41](https://user-images.githubusercontent.com/5415177/62481156-efb19d80-b7b1-11e9-9d5d-061ba1287364.gif)

There is also no more a visible effect for when setting the "No entry"

**Comment by IntelOrca** [comment]
I can't reproduce this. Which park are you specifically trying this on?

**Comment by ZehMatt** [comment]
It doesn't seem to be park related, during the title sequences I can see a lot of corrupted banners as well.
![openrct2_2019-08-05_19-59-37c98a3544a94452f15](https://user-images.githubusercontent.com/5415177/62484976-afefb380-b7bb-11e9-991a-2666feaefe77.jpg)

**Comment by IntelOrca** [comment]
Are you getting this in a build from openrct2.com?

**Comment by ZehMatt** [comment]
![openrct2_2019-08-05_22-43-37549a27a0b1df606f9](https://user-images.githubusercontent.com/5415177/62493907-85f5bb80-b7d2-11e9-9892-46434555002a.jpg)

**Comment by IntelOrca** [comment]
@ZehMatt what language is your game set to? Does it do this when set to English UK?

**Comment by ZehMatt** [comment]
Few things I've tried so far:
1. Software Renderer.
2. Software (HW) Renderer.
3. Different Language (US/UK, German, Dutch)
4. Different Parks.
5. Multithreading on/off.
It seems somewhat random, sometimes it actually works

**Comment by ZehMatt** [comment]
I can no longer reproduce this, I have no idea when it got fixed.
