### ISSUE TITLE
Vertical Height is not taken into account when choosing which entrance to path to

### ISSUE THREAD

**Issue by jbreitung** [OpenRCT2/OpenRCT2#9729]
**OS:** Windows 10
**Version:** 0.2.3
**Commit/Build:** ac7a1eb

I found out that people are getting stuck when building big paths (2 or 3 blocks thick). This issue also occures with maintenance workers when they are called to repair something. 

- not Reproducible in RCT2 (vanilla)

**Steps to reproduce:**
1. Download my savegame
2. Go to the location you can see in the screenshot

**Screenshots / Video:**
![People_stuck_on_big_path](https://user-images.githubusercontent.com/22149422/62490337-59897180-b7c9-11e9-86b5-bdce25a2a714.PNG)

**Save game:**
[UltimatoPark.zip](https://github.com/OpenRCT2/OpenRCT2/files/3469116/UltimatoPark.zip)

**Comment by duncanspumpkin** [comment]
Thats not a great layout for a park in terms of pathing. The ai is not designed for this layout at all and you have made a classic U shaped trap for the peeps (they have to move further away from the destination to get closer to it). I strongly suspect the vanilla game would also suffer from this but perhaps in a slightly different way.

**Comment by duncanspumpkin** [comment]
![image](https://user-images.githubusercontent.com/1277401/62490848-4921c880-b7c2-11e9-89dc-cf4379f51fc2.png)

**Comment by duncanspumpkin** [comment]
Actually on further inspection its because you have two entrances and its trying to path to the nearest which is the top one.

**Comment by duncanspumpkin** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/peep/GuestPathfinding.cpp#L2076 Should be modified to add a component from the Z difference between the peep and the entrance.

**Comment by duncanspumpkin** [comment]
After adding the appropriate factor 
![image](https://user-images.githubusercontent.com/1277401/62491878-0ca39c00-b7c5-11e9-97d2-d2c96a87a7b5.png)
