### ISSUE TITLE
Where is the latest build 0.2.3 in the releases tab for Linux?

### ISSUE THREAD

**Issue by ich777** [OpenRCT2/OpenRCT2#9744]
Hope i don't overlooked something but where is the latest build (0.2.3) in the 'releases' section for Linux?

Regards, ich777

**Comment by duncanspumpkin** [comment]
https://github.com/OpenRCT2/OpenRCT2/pull/9548 isnt this this

**Comment by JarnoVgr** [comment]
The release of v0.2.3 was kinda problematic as macOS and Linux builds weren't automatically built. macOS was built manually by @AaronVanGeffen .

**Comment by AaronVanGeffen** [comment]
They were built: https://travis-ci.org/OpenRCT2/OpenRCT2/builds/556998142

Something went wrong transferring them to OpenRCT2.org, however.

**Comment by JarnoVgr** [comment]
@AaronVanGeffen The problem is that releases weren't using https://openrct2.org builds before. The files were manually added to the GitHub releases page, which wasn't done for macOS and still isn't for Linux.
