### ISSUE TITLE
window_close from ride construction window causes a crash

### ISSUE THREAD

**Issue by UrbanSoldier9** [OpenRCT2/OpenRCT2#9752]
**Version:** 0.2.3
**Commit/Build:** 746d784b0e1e6033d2791c7ae5302ad0d41d34c4

**Steps to reproduce:**
Close the ride construction window before placing any track. Crash.

![image](https://user-images.githubusercontent.com/1277401/62658626-1eba4180-b961-11e9-8d46-c416c9b7bd96.png)

**Comment by UrbanSoldier9** [comment]
im new to this whole bug reporting but ever since i found out about open rct2 ive been in love with it ever since but ive had a few problems here and there, thats the only downside other than that im glad open rct2 exists

**Comment by UrbanSoldier9** [comment]
aaaaaand they just had an update making the game unlaunchable...... greeeeeeat.... please fix....

**Comment by duncanspumpkin** [comment]
https://github.com/OpenRCT2/OpenRCT2/commit/746d784b0e1e6033d2791c7ae5302ad0d41d34c4 this is fixed now (as far as i can understand from your issue)

**Comment by duncanspumpkin** [comment]
Also updates don't make the game unlaunchable. Maybe you're talking about the community created launcher which has known issues at this time. That isn't developed by us.

**Comment by duncanspumpkin** [comment]
Argh okay I see what your bug is its not fixed.
