### ISSUE TITLE
sorry to bring another issue buuuut now it wont launch.

### ISSUE THREAD

**Issue by UrbanSoldier9** [OpenRCT2/OpenRCT2#9754]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.2.3]
**Commit/Build:** [e.g. 426e106]
after just posting the last issue and it being fixed (fastest ive seen) now the game says it cant launch (or the launcher says it cant launch) its unfortunate, but if it is on other peoples end then it might be something on my computer, just let me know but i was able to launch it before the last update....

- [ nope ] Reproducible in RCT2 (vanilla)?
- [ nope ] Specific to multiplayer?

**Steps to reproduce:**
1. try to launch the game

**Comment by duncanspumpkin** [comment]
That isn't supported by us.

**Comment by UrbanSoldier9** [comment]
ok...i would still like to figure out how to fix it....

**Comment by duncanspumpkin** [comment]
https://github.com/LRFLEW/OpenRCT2Launcher/issues
