### ISSUE TITLE
Crashes on loaded save game

### ISSUE THREAD

**Issue by THEBATLORD** [OpenRCT2/OpenRCT2#9813]
[openrct2882019BATLORD.zip](https://github.com/OpenRCT2/OpenRCT2/files/3484951/openrct2882019BATLORD.zip)
. Windows 7]
**Version:** [e.g. 0.2.3]
**Commit/Build:** [e.g. 426e106]

Upon loading a saved game from last night, the game loads objects, but not ride track or flat ride bases. dump file, save game, and a screenshot of where the game hangs are all in the zip file. I'm aware this issue has come up before but not in the last 6 months

- [ ] Reproducible in RCT2 (vanilla)? vanilla doesn't want to run on my system using the steam version of rct2 triple thrill pack
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. start open RCT2
2. Load save file
3. ???
4. profit

**Comment by benjeater** [comment]
Having the same issue here on macOS.

MacOS Mojave - 10.14.6
OpenRTC2, v0.2.3-200

New game works fine, but any attempt to open a saved game (autosave or manual save) exits the game entirely with a crash report (attached)

[RTC2 Crash.txt](https://github.com/OpenRCT2/OpenRCT2/files/3485096/RTC2.Crash.txt)

**Comment by THEBATLORD** [comment]
Well it no longer crashes but now the game is running in a corrupted state where none of the ride track is loaded in, guests will walk to the end of a queue and get stuck, ride trains don't move. it's actually pretty funny.
![Uploading rct2 not crashing.png…]()

**Comment by IntelOrca** [comment]
@THEBATLORD Is this when loading a saved game?

**Comment by THEBATLORD** [comment]
Correct. The same saved game.

**Comment by IntelOrca** [comment]
That saved game is corrupt, if you desperately need to revive it then it is possible, just upload it and I can fix it.
