### ISSUE TITLE
Doors/Portcullis do not check to make sure doors are open causing double opens

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenRCT2/OpenRCT2#9902]
`vehicle_update_scenery_door` and `vehicle_update_handle_scenery_door` do not first check that a door is open before reopening it. This used to not be an issue as only one car in a train would open/close a door. Now that all vehicles open/close doors invisible cars can reopen a door causing duplicate animations/sound.

**Comment by Spongeloaf** [comment]
I'll take a shot at this one. I can reproduce it easily enough.

**Comment by duncanspumpkin** [comment]
Should be quite simple to do.
