### ISSUE TITLE
Giga Coaster supports not respecting objects underneath

### ISSUE THREAD

**Issue by Andy608** [OpenRCT2/OpenRCT2#9908]
**OS:** [e.g. Windows 10]
**Version:** [e.g. 0.2.3]
**Commit/Build:** [e.g. 426e106]

I noticed the Giga coaster supports do not get removed when building over pathways and/or certain rides.

**Steps to reproduce:**
1. Open any world.
2.  Build a Giga coaster over a path or ride.

**Screenshots / Video:**

![Screenshot 2019-08-19 03 46 05](https://user-images.githubusercontent.com/7517525/63248097-9ecf8980-c234-11e9-8547-3b6c2694e403.png)

![openrct_gigacoaster_support_glitch](https://user-images.githubusercontent.com/7517525/63248106-a2fba700-c234-11e9-8065-49372074d6ef.png)

![Screenshot 2019-08-19 03 45 17](https://user-images.githubusercontent.com/7517525/63248115-a858f180-c234-11e9-91d2-e044ed4429ca.png)

**Comment by AaronVanGeffen** [comment]
Possibly related to #8601

**Comment by ocalhoun6** [comment]
Isn't this normal? Very wide sections of path and certain rides -- like the hedge maze and space rings -- have always allowed supports to be built on them, haven't they?

**Comment by ZehMatt** [comment]
I just tested this with the original, a footpath would generally prevent supports to show up, I'm guessing the maze would count as the same.

**Comment by IntelOrca** [comment]
When tile elements are "painted", they set a 3x3 mask to say where supports are and aren't allowed. You can even get it show these masks using the debug draw options.

**Comment by Gymnasiast** [comment]
I was quite sure that @ocalhoun6 was right, but I made sure to test in vanilla anyway:

![SCR2](https://user-images.githubusercontent.com/1478678/63549075-fc631f00-c52f-11e9-97eb-4558f44cc608.PNG)

Since vanilla does this and the behaviour also doesn't seem buggy, I consider this to be working as intended

**Comment by ocalhoun6** [comment]
Just adding a note @Andy608 -- 

If you need to override this behavior for one reason or another, you can use the tile inspector, ctrl+click on the ride track above the tile where you don't want supports, and then click the 'move down' button in the list of objects a few times to place the ride track below the surface in the list. That will should the supports disappear without changing anything else, though it could get a bit tedious if there are a lot of supports you want to remove this way.

**Comment by IntelOrca** [comment]
There are also custom invisible scenery objects specifically for hiding supports.
