### ISSUE TITLE
Objective "10 coasters with length" works different (from stable)

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#9909]
**OS:** Windows 10
**Version:** 0.2.3
**Commit/Build:** 406ec7f

(It may be a question, I have no idea it is a bug or not.)

The attached save file is from a scenario which of its objective is building 10 different coasters with length 1,200m, and I built **11** coasters:
```
(name / excitement / length)
(1) Virginia Rill / 7.96 / 1438m
(2) Mini / 7.30 / 1535m
(3) Looping / 7.68 / 1408m
(4) Spining Wild Mouse / 8.20 / 1235m
(5) Steeplechase / 7.16 / 1474m
(6) LIM Launched / 7.28 / 1211m
(7) Bobsleigh / 7.04 / 1448m
(8) Flying / 8.90 / 1489m
(9) Vertical Drop / 9.09 / 892+902m = 1794m
(10) Junior / 7.13 / 2288m
(11) Stand-up / 7.01 / 1494m
```

All coasters are above 7.00 excitements with more than 1,200m length.
What I first doubted was coasters' TYPE.
So I checked related codes in here:
https://github.com/OpenRCT2/OpenRCT2/blob/90cc8856421aa0c60aa79aa393465678c9d04796/src/openrct2/scenario/Scenario.cpp#L842
and I notice that it is checked by ride's _subtype_.
But their _subtypes_ in the game (checked via ``rides list`` command in console) are like below, which is all different:
```
(1) Virginia / 028
(2) Mini / 019
(3) Looping / 021
(4) Spining Wild Mouse / 098
(5) Steeplechase / 058
(6) LIM / 023
(7) Bobsleigh / 004
(8) Flying / 075
(9) Vertical Drop / 026
(10) Junior / 029
(11) Stand-up / 092
```

When I revert my game 0.2.3 **stable**, the game clears my scenario.
If there was no changes in ways to check clear scenarios which of its objective is building 10 coasters with length 1,200m, I think it is a bug.

**Save game:**
[Hope and dream park.zip](https://github.com/OpenRCT2/OpenRCT2/files/3515311/Hope.and.dream.park.zip)

**Comment by Gymnasiast** [comment]
It was a bug, caused by the game counting subtypes above 90 (they can go up to 254).
