### ISSUE TITLE
Ghost pieces break maps on multiplayer for the client

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#9920]
**OS:** Tested on both Windows 10 and Ubuntu 18.04
**Version:** v0.2.3-277
**Commit/Build:** af2ad80

When playing on a multiplayer server, everything seems to work fine. Actions get through, and nothing looks to be wrong, but upon reconnecting the map is very broken on the client side. On tiles where things got changed, surface elements with a base height of 255, which is likely a result of all elements having been removed from that tile as well as strange edges (possibly missing tiles?). On the server, all is good, however. After having messed around for a bit, I think it's ghost pieces that cause the issue.

In some cases it looks like a tile is rendering the objects of the tile next to it. Probably because its own element list is empty and it loops until an element with the end-of-tile flag set. This could possibly cause crashes too.

Everything worked fine on a build from 5 days ago: 406ec7f

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Specific to multiplayer?

**Steps to reproduce:**
1. Host any park
2. Connect to it as a client
3. On either the host or client, build something (paths, ride)
4. Disconnect the client and reconnect again
5. Notice how on the changed tiles there appear to be massive pillars of surface elements.

This can also be replicated more easily:
1. Host any park
2. With the pathing tool, hover over some owned tiles to make a ghost appear
3. Connect to the server as a client

**Screenshots / Video:**
![Whispering Cliffs 2019-08-22 18-26-58](https://user-images.githubusercontent.com/9705046/63532530-2b1ace80-c50b-11e9-969a-18888bb648b1.png)
![](https://cdn.discordapp.com/attachments/452101260921929728/613497182439604267/Knipsel.PNG)
![](https://cdn.discordapp.com/attachments/411655823396438019/613497399549362206/unknown.png)

**Comment by ZehMatt** [comment]
The regression is from #9903

**Comment by Broxzier** [comment]
On further inspection, the issue seems to be that the map is not loaded properly when connecting to a server. It looks to be skipping one row of tiles each time:

Server:
![Forest Frontiers 2019-08-22 20-34-35](https://user-images.githubusercontent.com/9705046/63540525-80131080-c51c-11e9-9f8c-4947642752f5.png)

Client:
![Forest Frontiers 2019-08-22 20-35-20](https://user-images.githubusercontent.com/9705046/63540520-7e494d00-c51c-11e9-9a2e-9599ab53c500.png)
