### ISSUE TITLE
Traffic light in Ride list does not match actual statuses

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#9924]
**OS:** Ubuntu 19.04
**Version:** 0.2.3+
**Commit/Build:** 4cf1d1eb69c6253a2d9da8712f350e9ac458b8c1

It's often not illuminated or even red when all the rides are open.

**Comment by duncanspumpkin** [comment]
Do you mean the traffic light that tells trains if they are allowed to leave the station?

**Comment by Gymnasiast** [comment]
No, I was talking about the traffic light in this window:

![Blackpool Pleasure Beach 2019-08-23 08-10-02](https://user-images.githubusercontent.com/1478678/63570436-753c9800-c57d-11e9-8e86-c2c60ca557a7.png)

Since all rides are open, it should be green.
