### ISSUE TITLE
Africa - Oasis park has wrong peep spawn

### ISSUE THREAD

**Issue by jensj12** [OpenRCT2/OpenRCT2#9926]
**OS:** Windows 10
**Version:** 0.2.3
**Commit/Build:** 4cf1d1e

Peeps spawn somewhere inside the terrain close to the entrance, instead of on the path to the entrance.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open WW Africa - Oasis park and send a large tram.

**Screenshots / Video:**
A screenshot has been posted on the [forums](https://forums.openrct2.org/topic/4478-mirage-madness-afrika-oase-guest-dont-spawn/), but it's too small to see the problem.

**Fix:**
https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/openrct2/rct2/S6Importer.cpp#L890

**Comment by Gymnasiast** [comment]
Does not occur on vanilla.
