### ISSUE TITLE
Giant screenshot's made from command line aren't positioned right

### ISSUE THREAD

**Issue by Broxzier** [OpenRCT2/OpenRCT2#9941]
**Version:** v0.2.3-305
**Commit/Build:** e19b3f5

Taking giant screenshots from command line generates images where the camera seems to be focussed on one of the corners of the map. The rotation of the map also doesn't seem to be right.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open OpenRCT2 with command line arguments: `screenshot save.sv6 out.png giant 2 1`, where 1 is the rotation. For 0 it works right, for 1-3 it breaks.
2. Open out.png

**Screenshots / Video:**
Rotation 0:
![out-0](https://user-images.githubusercontent.com/9705046/63654976-4b07f780-c782-11e9-82d7-41dbaf41ea96.png)

Rotation 1:
![out-1](https://user-images.githubusercontent.com/9705046/63654977-4c392480-c782-11e9-800f-2b37d8414403.png)

Rotation 2:
![out-2](https://user-images.githubusercontent.com/9705046/63654981-51966f00-c782-11e9-987b-f4eef95315b7.png)

Rotation 3:
![out-3](https://user-images.githubusercontent.com/9705046/63654980-4fccab80-c782-11e9-806b-7cdf9ef26b7c.png)

**Comment by IntelOrca** [comment]
Is this only when zoomed out?
