### ISSUE TITLE
Overwriting scenery with rides does not cost additional money

### ISSUE THREAD

**Issue by Padankadank** [OpenRCT2/OpenRCT2#995]
When you place a ride on top of trees it deletes them but does not subtract the cost of removing the tree.  Right clicking while holding a ride does work correctly by subtracting money.

**Comment by Gymnasiast** [comment]
Cannot reproduce this. Keep in mind that the cost estimate when placing the ride is adjusted for the cost of tree removal.

**Comment by ThomasdenH** [comment]
I think this issue can be closed. I can't reproduce it either and @Gymnasiast's explanation seems rather likely.

**Comment by duncanspumpkin** [comment]
Yeah this has come up before. It does work its just it subtracts it from the overal value just like in RCT2.
