### ISSUE TITLE
Resizing map while game is paused may result in endless bug loop causing game to freeze

### ISSUE THREAD

**Issue by Solioss** [OpenRCT2/OpenRCT2#9955]
**OS:** Windows 10 (x86-64)
**Version:** 0.2.2
**Commit/Build:** 298c9f5

(This was brought from the OpenRCT2 forums : https://forums.openrct2.org/topic/4479-resizing-map-while-game-is-paused-may-result-in-endless-bug-loop-causing-game-to-freeze/ )

BUG : When shrinking the map with sandbox tools while the game is paused, game may start spamming the "Construction not possible while game is paused" error with the corresponding sound effect, resulting in loud constant noise and game freezing completely. This does not happen in the scenario editor (which, unsurprisingly, does not have a pause button). 

- [ ] Reproducible in RCT2 (vanilla)? **No** (requires use of cheats specific to OpenRCT2)
- [ ] Specific to multiplayer? **No**

**Steps to reproduce:**
1. Open the game.
2. Open any map containing objects (e. g. any scenario or saved game with progress). I've tested on "Build you own Six Flags park", "Six Flags Belguim" and "Crazy Castle" maps. The map's objects (trees, decorations, paths...) should preferably be close to its borders.
3. Pause the game.
4. Make sure the "Allow construction while paused" cheat is disabled.
5. Enable sandbox mode.
6. Open the map menu to access map editing tools.
6.1. Recommended before next step : Lower your volume (yeah, I jumped when it happened to me the first time)
7. Reduce the size of the map several times. It can go normally until the game has to delete a tile which has an object on it, in which case it will attempt to delete the object, causing the "Cannot build while game is paused" error and, apparently, making the game retry to delete the object again and again, resulting in a spam of the error's sound effect and in a complete game freeze. The game may or may not have had the time to display its last words in its ultimate render frame before it freezes : "Can't construct this here... Construction not possible while game is paused!"

**Known temporary fixes** (use any) : 
- Make sure the "Allow construction while game is paused" cheat is enabled
- Do not pause the game while shrinking the map
- Clean the map's edges before shrinking it

**Comment by ZehMatt** [comment]
I can not reproduce this, should be fixed. I do recall we converted this to a game action to work properly.
