### ISSUE TITLE
Scrolling gets stuck on some rotations and maps

### ISSUE THREAD

**Issue by Garogolun** [OpenRCT2/OpenRCT2#996]
1. Choose scenerio "Prehistoric - After the Asteroid" (i.e. Crater Carnage).
2. Rotate view 90 degrees clockwise.
3. Scroll the view all the way to the bottom.
4. Try to scroll up again.

This bug exists in vanilla RCT2 too.

**Comment by mrtnptrs** [comment]
I can confirm this bug still happens of course, but holding your right mouse button and scrolling up aggressivly will let you move out of the corner.

**Comment by Margen67** [comment]
Here's another save where the bug occurs:
[MozarsTemplate2.zip](https://github.com/OpenRCT2/OpenRCT2/files/874247/MozarsTemplate2.zip)
