### ISSUE TITLE
Giant screenshot crops park with high land

### ISSUE THREAD

**Issue by IntelOrca** [OpenRCT2/OpenRCT2#9962]
Clockwork cliffs:
https://www.nedesigns.com/park/4633/clockwork-cliffs/

![](https://www.nedesigns.com/uploads/parks/4633/aerialm4497.png)

**Comment by Gymnasiast** [comment]
Why is it a non-bug?

**Comment by IntelOrca** [comment]
Original reporter was using latest release rather than develop.
