### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nyn0** [OpenRCT2/OpenRCT2#9965]
Error will execution run game.
How to fix?.
Unable to load g1.dat. Your RollerCoaster Tyconn 2 path may be incorrectly set
![15674974348751507714728](https://user-images.githubusercontent.com/54836842/64154526-449d0e00-ce5b-11e9-86f8-2d413acbb9ab.jpg)

**Comment by duncanspumpkin** [comment]
You should set your RollerCoaster Tycoon 2 directory to fix that. Then it will be able to find g1.dat.

**Comment by nyn0** [comment]
Ok, I will try tomorrow
