### ISSUE TITLE
Wait for quarter load fails

### ISSUE THREAD

**Issue by jensj12** [OpenRCT2/OpenRCT2#9970]
**OS:** Windows 10
**Version:** 0.2.3-324
**Commit/Build:** 1d6e4d7

Wait for quarter load does not wait for any guests. Trains will still leave as if this option was not selected (even empty).

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Open RCT1LL scenario Megaworld Park
2. Observe Viper (in the sand area)
Or build any coaster and enable 'wait for quarter load'. (I checked multiple coasters in different parks, but coincidentally only corkscrews)

**Comment by aw20368** [comment]
I'll work on this. A few notes:

- Reproducible on coasters other than corkscrews, I used the mine train in Dynamite Dunes.
- Reproducible all the way back in 0.0.5
- Not exactly reproducible in RCT1...however, it still fails to actually wait for a quarter load. It will wait for something close enough (i.e. train will not depart with 2 passengers in the situation below).
![Quarter](https://user-images.githubusercontent.com/29646196/64902079-f7951500-d66e-11e9-8e85-64b6e3f41f12.png)
