### ISSUE TITLE
Miniature steamtrains can go backwards in shuttle mode

### ISSUE THREAD

**Issue by LordMarcel** [OpenRCT2/OpenRCT2#9991]
**OS:** Windows 10
**Version:** 0.2.3
**Commit/Build:** 1efc774

Since a while ago different train types for the same track don't show up as different rides anymore in the ride selection screen. This caused some operating types to become available for train types that didn't have those operating types in vanilla. This includes shuttle mode for steamtrains. Shuttle mode was only intended for trams, which can go in either direction, but for the streamtrain this just doesn't make sense that they can go backwards.

**Screenshots / Video:**
https://www.youtube.com/watch?v=R9st-xexh4I

**Comment by TechandMusic462** [comment]
I mentioned this in the comments on your video about transportation rides, but shuttle mode steamtrain rides do actually exist in real life. In the German park Fort Fun, in Sauerland, there is such a ride where the train shuttles back and forth, like in this OpenRCT2 update. Yes, it looks a little funny, but it's not wholly unrealistic, and I wouldn't be surprised if more parks have this. I'd suggest keeping it in, you can always opt to not use it if you do not like the trains going backwards :-)

**Comment by Gymnasiast** [comment]
The local steam railway around here has no turntable and thus also just puts the locomotive in reverse.

Besides: the only way to disable the mode is by splitting trams and miniature railways. To me, that is too big a price for something that is a very minor bug at worst.
